### ISSUE TITLE
Feature Request: xBR shader and xBRZ filter for GSDX in both PS2 and PSX mode.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#10]
Could you please implement  xBR shader or xBRZ filter or both in GSDX plugin. It would be very beneficial for both PS2 and PSX 2D and sprite-based games.
xBR and xBRZ are pixel art scaling algorithms ,they give best results in 2D/sprite based games with low resolution textures and games with pre-rendered backgrounds which dont upscale well with higher internal resolutions but they also give good results in 3D games.  xBR/xBRZ are already used with good results in emulators like Retroarch , Higan, Desmume and PPSSPP.
Here is explanation:http://code.google.com/p/2dimagefilter/wiki/ImageScaling#xBR
http://www.vogons.org/viewtopic.php?t=34125
Here is newest xBR source code including hybrid variants: https://github.com/libretro/common-shaders
Source code for xBRZ is in source code of HqMAME : https://sourceforge.net/projects/hqmame/  ,http://sourceforge.net/projects/hqmame/files/xBRZ.zip/download,  Spline36: http://code.google.com/p/remote-joy-lite-fix/source/browse/trunk/RemoteJoyLite_pc/spline36.psh
https://github.com/xbmc/xbmc/tree/master/xbmc/cores/VideoRenderers/VideoShaders
Here is comparison for 3D graphics:http://blog.metaclassofnil.com/?p=306
Here is official tutorial about xBR: http://www.libretro.com/forums/viewtopic.php?f=6&t=134
http://forum.zdoom.org/viewtopic.php?f=19&t=37373&sid=57269f5e32514a88a5d5252839c9ff6a&start=45
Some 2D graphics of old version of xBR: http://imgur.com/a/ZZiiH
I also found interesting algorithm Libdepixelize: http://bazaar.launchpad.net/~vinipsmaker/libdepixelize/trunk/revision/184
http://vinipsmaker.wordpress.com/tag/libdepixelize/
https://sourceforge.net/projects/inkscape/
There is also ''Ours'' but I cant find source code for it anywhere: http://research.microsoft.com/en-us/um/people/kopf/pixelart/supplementary/
 But Libdepixelize and Ours both use Kopf-Lischinski algorithm so they should have similiar effects.
http://www.mediafire.com/download/22o6ahnchkbzhef/Shaders.rar
http://www.mediafire.com/download/86bo6bl66cnwv2j/chromaNEDI.rar
https://github.com/jpsdr/NNEDI3
http://forum.doom9.org/showthread.php?t=170727

**Comment by VIRGINKLM** [comment]
Your argument about XBRZ being good or not is irrelevant. In the case of a github feature request, nobody cares about your points about XBRZ being wrong because it's not a forum discussion thread. The fact is that there is a huge amount of emulation scene fans that really enjoy XBRZ texture scalling... ...and the context ends here. With PPSSPP leading the way and lots of other emulators now following these steps (PS1, N64...) it's safe to say that everybody would turn to see if PCSX2 would follow on a such well recieved feature. It's no ta leage of who likes it or not, making points etc, it's a polite-asking feature request and it's actually possible. Now it's up to somebody with the interest and skill to pick it up. If closed source plugins like Pete's OpenGL2 could be modified to achieve such effect then I bet PCSX2/GSDx can aswell. Let's just not argue if it's possible or not.

**Comment by Squall-Leonhart** [comment]
nobody cares

**Comment by mirh** [comment]
#800

**Comment by shinra358** [comment]
Scalefx x9 is identical to 6xbrz. It is located in retroarch common shaders. It is a multipass shader. It is not as performance costly as xbrz is. So you guys might want to consider using this instead.

**Comment by Papermanzero** [comment]
It would be great for games like metal slug, megaman, etc.

**Comment by shinra358** [comment]
are we there yet ?  xD

**Comment by MRCHEESE97** [comment]
I would like to have a deeper knowledge to implement it, unfortunately not.
However I have an idea how this goes, bilinear filtering is pixel art just like Xbrz, so if it can be implemented, it goes right here. We need an expert developer on the subject.
![image](https://user-images.githubusercontent.com/46450049/97360816-afce4e80-186c-11eb-9d76-8f4c1bc0f4fc.png)

**Comment by RedDevilus** [comment]
Perhaps someone on PPSSPP, it works great there.

**Comment by ADormant** [comment]
@MRCHEESE97 
https://github.com/stenzek/duckstation/commit/6f250a4ff7ffc06c68ed9d48ee7b97f925d354d8
https://github.com/flyinghead/flycast/pull/57/files
https://github.com/stenzek/duckstation/commit/62892b02d11893bc8079523da079ac04960f79f6
https://github.com/stenzek/duckstation/commit/5635ee1d7c521e1a1cd590bf804287d30c901948
https://github.com/stenzek/duckstation/commit/ae1e4b1b8fd52690ecda600232141e6ed1df1d4d

**Comment by bajolzas** [comment]
Just wanted to say that I am very much looking forward to this feature being implemented and not having to choose between blocky or blurry 2D assets.

Also for those that argue that "developers did not intended for the graphics to look that way" well, they did not intend for their ps2 games to be played on a PC either, but here we are...

**Comment by Papermanzero** [comment]
then I would like to add bicubic

**Comment by shinra358** [comment]
the reason why xbrz is highly desired is because it looks great and is the
closest thing to high rez textures. it has to be internally coded for it to
work properly. all the other shaders can be acquired thru 3rd party means.
xbrz is technically a scaler.

**Comment by ISuckGood** [comment]
![2021-04-06_17h16_08](https://user-images.githubusercontent.com/42075250/113734722-dafe7900-96fb-11eb-91a4-aeb572ca14c1.png)
Which is better ? Xbr or nearest neighbor ?

**Comment by Papermanzero** [comment]
biliear and/or bicubic 😅

**Comment by michaelpegaso** [comment]
> ![2021-04-06_17h16_08](https://user-images.githubusercontent.com/42075250/113734722-dafe7900-96fb-11eb-91a4-aeb572ca14c1.png)
> Which is better ? Xbr or nearest neighbor ?

😻😻😻❤❤❤

**Comment by seta-san** [comment]
> xbr or nearest neighbor ?

nearest neighbor. your mistaking the smooth look of xbr with an HD upscale. what it is, is a smoothed over approximation of nearest neighbor. i don't think any game studio would have intentionally made a game that looks like the xbr. it some how looks blockier and chunkier than nearest neighbor.

**Comment by LuismaSP89** [comment]
Xbrz forever, I really love this filter in all emulators, and for those who don't want this feature implemented, nobody is forcing you to enable this option in case someone implements the filter on the pcsx2.

**Comment by bajolzas** [comment]
> > xbr or nearest neighbor ?
> 
> nearest neighbor. your mistaking the smooth look of xbr with an HD upscale. what it is, is a smoothed over approximation of nearest neighbor. i don't think any game studio would have intentionally made a game that looks like the xbr. it some how looks blockier and chunkier than nearest neighbor.

It literally does not matter what game studios would or would not have their games look like.

xBR is not perfect, but it is the closest we are going to get in real time to high resolution 2D assests (short of texture replacement, wich not all games will have; and it fills disc space, wich might not be ideal to some people, depending on the amout of games they own).

If you prefer nearest neighbor, nice, luckily that option is already available to you.

This is not a discussion of wich is better (wich is highly subjective); this is about having the option to use a feature that is already available in other emulators, that a number of people enjoy.

**Comment by F0bes** [comment]
Locking as the discussion here hasn't been very productive.
If you're interested in implementing these shaders please open a pull request.
If you're wondering about the status of this feature request, check if there is a linked pull request.

**Comment by lightningterror** [comment]
Closing as low priority, and what fobes said.
