### ISSUE TITLE
[BUG]: Yakuza 1 Lines in the middle of the screen

### ISSUE THREAD

**Issue by MR-WADS** [PCSX2/pcsx2#10009]
### Describe the Bug

When using resolutions higher than native, two black lines cross the screen (one vertical, the other horizontal)
Using Half-Pixel Offset fixes this, however it introduces minor ghosting and a transparent vertical line in the middle of the screen.

### Reproduction Steps

Use resolutions higher than native on any renderer.

### Expected Behavior

Clean image with no lines.

### PCSX2 Revision

1.7.5041

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600g

### GPU

RTX 3060

### GS Window Screenshots

![photo_2023-09-23_13-40-35](https://github.com/PCSX2/pcsx2/assets/124984582/60a15c41-3b05-4e4e-8e96-604f646cafd8)
![photo_2023-09-23_13-40-25](https://github.com/PCSX2/pcsx2/assets/124984582/d23fbad7-6d6c-4f19-8e4a-e00c7a9abb27)
![photo_2023-09-23_13-40-27](https://github.com/PCSX2/pcsx2/assets/124984582/df9abd72-36a2-4211-b136-9f6c28919579)
![photo_2023-09-23_13-40-30](https://github.com/PCSX2/pcsx2/assets/124984582/612351b7-6f8c-4f63-918e-b0f4210836fe)
![photo_2023-09-23_13-40-31](https://github.com/PCSX2/pcsx2/assets/124984582/d9e0f298-dfb9-4424-ae65-3985b9d7f274)
![photo_2023-09-23_13-40-33](https://github.com/PCSX2/pcsx2/assets/124984582/ebac7748-8a30-4f80-92d2-fd722f69e685)

**Comment by MrCK1** [comment]
We don't accept bug reports for upscaling issues. Please use Discord or the forums if you require further support.
