### ISSUE TITLE
[BUG]: Time Crisis 3 (SLUS-20645) not recognizing memory cards

### ISSUE THREAD

**Issue by Castor215** [PCSX2/pcsx2#10004]
### Describe the Bug

After calibrating the lightgun (simulated with a mouse) the game brings up a message that there is no memory card inserted into slot 1. This happens with both a folder memory card and emulated 8MB memory card.
![tmcrs3](https://github.com/PCSX2/pcsx2/assets/132155746/12a0659c-2d39-46b4-837c-df6af2037267)

### Reproduction Steps

Start Time Crisis 3 with a memory card inserted.

### Expected Behavior

Memory card detected.

### PCSX2 Revision

v1.7.5040 (AppImage)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian

### CPU

Ryzen 5600X

### GPU

1050Ti

**Comment by stenzek** [comment]
<img width="605" alt="image" src="https://github.com/PCSX2/pcsx2/assets/11288319/f386a38e-0c7f-413a-9897-b7172dd4fd5b">

Works fine here. Sounds like a support issue - please use Discord/the forums.
