### ISSUE TITLE
[Feature Request]: add Makefile?

### ISSUE THREAD

**Issue by BJNFNE** [PCSX2/pcsx2#10016]
### Description

Would it be possible to add a Makefile?

### Reason

It would be then easier to compile it over gcc/make instead of Cmake

### Examples

No examples

**Comment by stenzek** [comment]
Have you ever managed a large project with dependencies (which also use CMake) with a Makefile? Also keep in mind we support multiple platforms.

So yeah, no thanks. PRs welcome, but I **really** see absolutely zero advantage to pure Makefiles.
