### ISSUE TITLE
Allow PCSX2 to read dumped textures from folders inside dump folder

### ISSUE THREAD

**Issue by Kane20233** [PCSX2/pcsx2#10026]
### Description

Allow PCSX2 to read already dumped textures from folders or nested folders inside dump folder to avoided repetition.

### Reason

This will make dumping textures easier when it's needed it, and dumping process organized.

### Examples

Let say I want to dump textures in sessions or by level or grouping, when current level is dumping and need to stop in middle of the level and to continue dumping other time. I would make folders inside dump folder and moves the dumps to this folder, then next time when I continue dumping I don't want already dumped textures to be dumped again as I already move them to a new folder or nested folders according to set preference or grouping.

Just like nested folder when loading textures but this one for the dump folder.

**Comment by stenzek** [comment]
The texture dumper doesn't work this way. It looks for a matching file in the dump directory, and skips dumping if it already exists. 

It doesn't scan subdirectories. Doing so for every dump would be slow.

**Comment by Kane20233** [comment]
Thank you for the clarification.
