### ISSUE TITLE
[BUG]: Setup Wizard "Open in Explorer" is not OS agnostic

### ISSUE THREAD

**Issue by marijnvdwerf** [PCSX2/pcsx2#10037]
### Describe the Bug

The 'Bios Image' step in the setup wizard has a button labeled 'Open in Explorer...'. This doesn't match the name of the file manager in macOS: Finder.
![image](https://github.com/PCSX2/pcsx2/assets/737603/1f368508-2844-42b0-b051-5f3ff3c9a4a5)

### Reproduction Steps

- Follow setup wizard

### Expected Behavior

Button says 'Open in Finder...'

### PCSX2 Revision

v1.7.5063

### Operating System

macOS 12 (Monterey)

**Comment by refractionpcsx2** [comment]
yes "Open Location" would probably be a better label for it

**Comment by stenzek** [comment]
This is a bit of a nitpick, and I'm not sold on it. Making buttons per platform is pretty gross, and I'm a little concerned that users might not understand what "open location" means. Maybe "Open in File Browser".

**Comment by coornio** [comment]
Maybe?

![image](https://github.com/PCSX2/pcsx2/assets/11655762/945d8be7-79d2-4d1f-ac43-fc2f7273a345)

Except we rename it with "folder" instead of "file".
