### ISSUE TITLE
Dog's Life crashes with OpenGL and internal resolution set to 4x

### ISSUE THREAD

**Issue by JimmySnails** [PCSX2/pcsx2#1003]
Latest rev from today (1.3.1 - 1487)
Just open Dog's Life PAL, start a new game and after the intro sequence it immediatly crashes. (when the game enter Smell-O-Vision)
This doesn't happen with internal resolution set to 1x - 3x, just with 4x. 
(also works with direct3d plugin)

I'm using an ATI Radeon R9 290. 

Only setting i've changed from default is skipdraw to 1 or else the menu has red lines in it. 

I've also tried the supervu setting but same behaviour.

**Comment by gregory38** [comment]
Not enough memory to handle big resolution. I don't know how to make it more robust.

Redbar could likely be (partially) emulated. Disable VU speedhack, enable GS depth emulation and maybe others accurate options.

**Comment by Talantyyr** [comment]
I do have 16gb of ram, but i guess you mean memory handling of pcsx2?

It's not a big issue for me, 3x resolution is good enough for me, just wanted to report that because it's a crash...

**Comment by yorkiesandskittles** [comment]
I'm guessing memory means VRAM here, not regular RAM i.e. the RAM in your 290, which is definitely less than 16GB.

**Comment by gregory38** [comment]
Yes I mean VRAM. Could you test again latest git version. Various memory optimization were done.

* You need openGL
* Skipdraw must be 0. Better disable Hw hack actually.

**Comment by FlatOutPS2** [comment]
Still crashes. Issue seems to be more RAM related than VRAM. VRAM usage is high near crash, but doesn't max out. RAM does spike by 2GB+ when it crashes.

**Comment by MrCK1** [comment]
Issue was reported by one of our testers as resolved. The game no longer crashes when upscaling past 4x
