### ISSUE TITLE
[BUG]: Jak and Daxter: The Precursor Legacy has broken character shadows and model issues (mostly eyes) on Hardware (Vulkan doesn't have character shadow problems) 

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#10039]
### Describe the Bug

Broken character shadows that is shaped in a cape like fashion except for Vulkan and all hardware renders has issues rendering character models (mostly eyes)

### Reproduction Steps

Broken shadows (Use Vulkan)
Both (Software)

### Expected Behavior

No broken shadows and improperly rendered character models

### PCSX2 Revision

v1.7.5064

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 3700X 8-core processor 

### GPU

Nividia GTX 1070 TI

**Comment by AkihitoZero5454** [comment]
[Jak and Daxter - The Precursor Legacy_SCUS-97124_20230927233024.gs.zip](https://github.com/PCSX2/pcsx2/files/12745224/Jak.and.Daxter.-.The.Precursor.Legacy_SCUS-97124_20230927233024.gs.zip)

**Comment by AkihitoZero5454** [comment]
[Jak II_SCUS-97265_20230927234909.gs.zip](https://github.com/PCSX2/pcsx2/files/12745332/Jak.II_SCUS-97265_20230927234909.gs.zip)
Jak II has also broken character shadows and when starting a new game and after saving it crashes but you can load the game and play

**Comment by stenzek** [comment]
First link is dead. Game works fine. You've obviously messed with your config, because both of those symptoms sound like appropriate fixes not being applied.

Please use Discord or the forums for support, not the issue tracker.
