### ISSUE TITLE
[BUG]: Dirge of Cerberus missing graphics during cutscene 

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#10031]
### Describe the Bug

During Chapeter 1 - The Flames of Kalm when the helicopter is scanning Vincent the character model is missing partially. Starts with build v1.7.4943

### Reproduction Steps

Run the game is HW mode and watch the opening cutscene for that mission/chapter. 

### Expected Behavior

The entire character model should be visible during the scan. 

### PCSX2 Revision

v1.7.5061

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default 

### GS Window Screenshots

![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230925183454](https://github.com/PCSX2/pcsx2/assets/12180630/00097a1c-a705-4a3d-ae75-f13387cab79a)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/12719934/snaps.zip)

**Comment by refractionpcsx2** [comment]
is this a new bug? did it ever work? if so, do you know when it broke?

**Comment by refractionpcsx2** [comment]
Something depth related going on here, if I disable depth emulation I get this, which is the foreground without blending with the background.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/cd407a5f-abfb-449f-9ed5-16111de204dc)

**Comment by jkelly91** [comment]
@BParks21 @refractionpcsx2 

Not sure if this is helpful but I was able to fix this by switching to software rendering..Not ideal if you are looking for a scaled resolution experience but it does work. 

![image](https://github.com/PCSX2/pcsx2/assets/70504939/b7a275a3-26f3-4b8c-b3c7-5792e872c48b)

**Comment by refractionpcsx2** [comment]
It doesn't really help, but thanks

**Comment by Jakey757** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/49990481/b87fad42-7a3b-4feb-a580-7d31810032ca)
tex in rt is closer but still not quite there

**Comment by BParks21** [comment]
Seems fixed now.

**Comment by Mrlinkwii** [comment]
yeah looks good with the gs dump 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/d9a60ed0-b1b9-424d-a9e6-bc4e6e1af806)
