### ISSUE TITLE
[BUG]: Midnight Club 3: DUB Edition Remix crashes with a GSUploadQueue error when using HW renderer

### ISSUE THREAD

**Issue by mradermaxlol** [PCSX2/pcsx2#10048]
### Describe the Bug

I observe pretty reliable crashes of the game if run with hardware rendering. Upscaling and/or other graphic options don't seem to matter: the game doesn't crash with software rendering, but it does with hardware rendering. Plain and simple.
Switching between Vulkan/OpenGL makes no change here.

### Reproduction Steps

1) Enable HW rendering (enabling upscaling seems to make PCSX2 crash slightly earlier)
2) Load the save state
3) Exhibit the crash ~15 seconds after the race start/restart until it crashes ~15 seconds after the start

[savefile.zip](https://github.com/PCSX2/pcsx2/files/12776847/savefile.zip) (I hope I attached the correct one, should be at the very start of the race)

### Expected Behavior

Game doesn't crash with HW rendering enabled.

### PCSX2 Revision

v1.7.5067 (latest flatpak)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 5 3550H

### GPU

Radeon RX560M

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/11138966/741c0299-d75c-4e80-b8bc-387c6042472b)
![image](https://github.com/PCSX2/pcsx2/assets/11138966/1d1bf7dc-dbde-4e60-bd72-03f174158bba)

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/11138966/3b206e25-e1d1-48bd-a912-f68de5a1812d)

### Logs & Dumps

I see this entry in my system logs when PCSX2 crashes:
`kernel: amdgpu 0000:01:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring comp_1.0.1 test failed (-110)`

PCSX2 itself only prints this if run from console:
`/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:1230: reference std::vector<GSState::GSUploadQueue>::back() [_Tp = GSState::GSUploadQueue, _Alloc = std::allocator<GSState::GSUploadQueue>]: Assertion '!this->empty()' failed.`

**Comment by JordanTheToaster** [comment]
Doesn't crash for me on Windows using the savestate provided.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/56054d4a-dab9-4ec6-a08e-3bdb7f6f0110)

**Comment by Mrlinkwii** [comment]
can i also get a copy of a memcard :)

**Comment by mradermaxlol** [comment]
> can i also get a copy of a memcard :)

[memcard.zip](https://github.com/PCSX2/pcsx2/files/12829283/memcard.zip)

**Comment by mradermaxlol** [comment]
This issue seems to be nonexistent now. I don't know whether there have been any changes to PCSX2 during October that have fixed things or it was just my host system acting up in the first place.

Either way - thanks a lot and keep up the good work :)
