### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by HElNKEL** [PCSX2/pcsx2#10040]
### Describe the Bug

Sudden frame dumps in all Ace Combat games (4, 5, Zero). Seems to toggle whenever facing a certain direction.
Good example is on Ace Combat 5's Rendezvous, where peeking down to the ground at all dumps frames into nothing.
Used to work fine, suddenly does not anymore after an update. Playing around with every setting accomplishes nothing. Not a CPU or GPU bottleneck, both aren't even halfway to peaking.

(Screenshot when looking at target area)
![image](https://github.com/PCSX2/pcsx2/assets/146308874/8faf0114-e21d-4313-a5d9-bd5fddedae5d)

(Screenshot when looking away from target area)
![image](https://github.com/PCSX2/pcsx2/assets/146308874/49c2f1cc-ea34-42e6-ac67-2b08a1b68636)

### Reproduction Steps

>Can be in any sight mode, third person, first, or camera
>Any setting, tested at both 3x resolution and Native PS2
>Any Aspect Ratio, any interlacing setting

Genuinely any circumstance, any setting. Simply look at a specific area on just about any mission and the frames and speed drop like a rock.

### PCSX2 Revision

Nightly v1.7.5064

### Operating System

Windows 11

### CPU

AMD Ryzen 3 2300X Quad-Core Processor

### GPU

Radeon RX 570 Series

### GS Settings

At time of most recent check:

DISPLAY
>>Fullscreen Mode: Borderless Fullscreen
>>Aspect Ratio: Standard (4:3)
>>FMV Aspect Ratio: Standard (4:3)
>>Deinterlacing: Adaptive (Top Field First)
>>Bilinear Filtering: None
NO CHECKS

RENDERING
>>Internal Resolution: Native (PS2)
>>Mipmapping: Automatic
>>Texture Filtering: Bilinear (PS2)
>>Trilinear Filtering: Trilinear (PS2)
>>Anisotropic Filtering: Off
>>Dithering: Unscaled
>>Blending Accuracy: Basic
>>Texture Preloading: None
NO CHECKS

TEXTURE REPLACEMENT
>Asynchronous Texture Loading

POST PROCESSING
CAS: None
NO CHECK
TV Shader: None
NO CHECK

OSD
>Show OSD Mssgs
>Show FPS
>Show CPU Usage
>Show Stats
>Show Settings
>Show Frame Times
>Show Speed %
>Show GPU Usage
>Warn about Unsafe

NO RECORDINGS

ADVANCED:

GS Dump: Zstandard
Allow Exclusive Fullscreen: Automatic
Override Texture Barriers: Automatic

### Emulation Settings

SPEED CONTROL
>Normal - 100
>Fast - 200
>Slow - 50
Limiter Tested both On and Off, no difference

SYSTEM SETTINGS
EE Cycle Rate: 100
EE Cycle Skipping: Disabled
Affinity Control: Disabled
>Enable Multithreaded VU1 (MTVU)
>Enable Instant VUI

FRAME PACING
Maximum Frame Latency: 2 Frames
>Scale to Host Refresh Rate (Tested on/off)

### Logs & Dumps

GSdump just to be absolutely sure, taken when frames dump off.
[ac5gsdump.zip](https://github.com/PCSX2/pcsx2/files/12745295/ac5gsdump.zip)

**Comment by stenzek** [comment]
Not a bug. It's reading back hardware textures (RB number is non-zero). CPU is waiting for the GPU, that's why nothing is maxed out.

Use software renderer, disable readbacks, lower resolution, etc, are all possible mitigations. But you can't "fix" the game asking for downloads.
