### ISSUE TITLE
Rule of Rose - overlapping shadows

### ISSUE THREAD

**Issue by SimplyLiz** [PCSX2/pcsx2#1005]
![2015-11-28 2](https://cloud.githubusercontent.com/assets/7029836/11451314/1a1fec0e-95c2-11e5-8e12-5bacbd30229f.png)

Latest rev from today (1.3.1 - 1487)

The shadows are slightly overlapping the characters. Happens in Software / Hardware. (core related?) All Settings are set to default except hacks - Use software mode for FMV.

Savegame (the scene in the screenshot). (NTSC version)
http://workupload.com/file/OniFxpwz

**Comment by willkuer** [comment]
What happens if you increase vu clamping to extra + preserve sign? What happens if you use superVU?

**Comment by Talantyyr** [comment]
Set both VU settings to superVU -> no difference
Set VU Clamping to "Extra + Preserve Sign" -> No difference.

**Comment by gregory38** [comment]
It could also be a read/write texture (GSdx doesn't emulate them properly even in SW mode)

**Comment by MrCK1** [comment]
@JimmySnails Can you retest on the latest git build please?

**Comment by lightningterror** [comment]
Still present on latest build.

**Comment by refractionpcsx2** [comment]
This is accurate to the PS2

![image](https://user-images.githubusercontent.com/6278726/141445346-fb7b25be-3f28-4b36-939d-93b262c394b8.png)
