### ISSUE TITLE
Request to change GameDB upscaling settings for Haunting Ground.

### ISSUE THREAD

**Issue by F0bes** [PCSX2/pcsx2#10054]
### Discussed in https://github.com/PCSX2/pcsx2/discussions/9907

<div type='discussions-op-text'>

<sup>Originally posted by **EnekoT2001** September  4, 2023</sup>
Since the change from HPO: vertex to special and round sprite half, the depth of field effects are kinda broken.

They look very low resolution no matter what internal resolution you set and don't align correctly on the X axis (resulting in an outline on characters).

Example:
![Haunting Ground_SLES-52877_20230904051228](https://github.com/PCSX2/pcsx2/assets/42989949/fac434f6-d32e-403a-96ea-e5038221f386)

(for reference, vertex HPO looked like this)
![Haunting Ground_SLES-52877_20230904181553](https://github.com/PCSX2/pcsx2/assets/42989949/20e072c7-9d5c-46e1-8a4f-58b4c479ec0d)

By trying different settings I found a workaround:

First, to fix the low resolution of the effect, all it needs is forcing filtering.
The problem is that forcing bilinear makes that outline issue even worse and doesn't look much better anyway, forcing trilinear (with bilinear set to PS2, with bilinear set to forced it doesn't do anything) does look way better, but the outline is still present, even if a bit less noticeable.

bilinear forced:
![Haunting Ground_SLES-52877_20230904182448](https://github.com/PCSX2/pcsx2/assets/42989949/9376891e-3f67-416d-89cd-6b18b153098a)

Bilinear PS2, trilinear forced:
![Haunting Ground_SLES-52877_20230904051026](https://github.com/PCSX2/pcsx2/assets/42989949/6b4029e6-4dd7-4144-9738-61177ebb0adb)

The ideal solution I found is to set bilinear filtering to nearest and trilinear to forced, there are no drawbacks that i can see (except the DoF effect not showing at the top edge of the screen but it's just a few pixels, and tbh vertex HPO had similar issues anyway)
This gets rid of the outline, the DoF effect is well filtered so it doesn't look super low resolution and doesn't seem to break anything else. Tested in over a dozen cutscenes already.

Bilinear nearest and trilinear forced:
![Haunting Ground_SLES-52877_20230904175619](https://github.com/PCSX2/pcsx2/assets/42989949/80004df4-4d29-4264-968e-cefdb167f35d)

Bilinear filtering (forced or PS2) moves the image a few pixels to the left and that's what causes the outlines. Trilinear doesn't seem to move the image at all so that's why it doesn't cause any issues, not sure if this is an inaccuracy on the emulator end or just how the ps2 handles bilinear filtering (or this game being weird as usual).

I also have gsdumps alongside the screenshots with each setting if anyone wants to take a look at them: https://drive.google.com/file/d/1tAVsv4PYXskJBwYIF7500hc8uBVCvkpn/view?usp=sharing google drive link bc it's bigger than 25MB
Also, im using a new version of the widescreen patch from nemesis2000 I got from ps2wide.net (it fixed the FOV on cutscenes, but these issues show up even without WS patches active)

Anyway, I hope these findings will be taken into consideration, I'm not sure if regular render settings can be changed through the GameDB but as it is now, this is the only way to get rid of these issues and I really couldn't find any bugs caused by these settings, if anything it's more accurate to how it looks on real hardware (i compared it with software rendering a lot of times too)</div>

**Comment by Mrlinkwii** [comment]
it looks like  their is no perfect up-scaling fixes for this game , its been rechecked and no matter what you do its not 100% perfect
