### ISSUE TITLE
[BUG]: Disgaea freezing on Intro while recording FFMPEG

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#10058]
### Describe the Bug

The emulator/game freezes if you try to record a video for approximately 40 seconds.

### Reproduction Steps

1) Start Disgaea
2) Start Video Capture mode
3) Wait 20 seconds
4) The game is frozen now.

### Expected Behavior

The game (and video capture) would not freeze.

### PCSX2 Revision

v1.7.5075

### Operating System

Windows 11

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by Meerkov** [comment]
I don't seem to get issues with other games (e.g. Dynasty Warriors 3 Extreme Legends)

**Comment by stenzek** [comment]
I think we can merge this in with #8679 - likely the same issue. Same symptoms, anyway.

**Comment by Meerkov** [comment]
Note: this is not in fullscreen mode.

Might be helpful to see if there was ever a version where this didn't freeze up.
