### ISSUE TITLE
Option to enable/disable linux stdout/stderr redirection

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1006]
I need to disable it for debug purpose. I have a crash with asan. Error is printed on the console but application is killed before the text is written to the log.

**Comment by turtleli** [comment]
Ok. I'll try and have it done quickly.

**Comment by gregory38** [comment]
Thanks. Actually it seems that redirecting console to stdio does the trick.

As a side note do you think the extra thread impact the perf?

**Comment by turtleli** [comment]
It shouldn't have much effect unless the plugins are spamming messages. The threads will probably be waiting at the blocking read most of the time, and I assume the kernel won't switch to the threads if they have nothing to do.

**Comment by gregory38** [comment]
Ok. It was to be sure. I managed to spot my stack issue. The option to redirect console to stdio is enough for me. So I'll close the issue. (hope you didn't spend too much time on it)
