### ISSUE TITLE
[BUG]: taito memory games 

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#10086]
### Describe the Bug

these games need half round sprite

taito memories joukan
SLPM-66057
TCPS-10115
SLKA-25297 (Korea, Special Package)
SLPM-66402 (Taito Best)
TCPS-10160 (Taito Best)
SLPM-66775

taito memories joukan 2
SLPM-66649
TCPS-10178
SLPM-55017 (Eternal Hits)

taito memories gekan
SLPM-66092
TCPS-10124
SLPM-66521 (Taito Best)
TCPS-10164 (Taito Best)
SLPM-66776 (Eternal Hits)

taito memories gekan 2
SLPM-66713
TCPS-10183
SLPM-55018 (Eternal Hits)

### Reproduction Steps

play the game

### PCSX2 Revision

1.7.5095

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### GS Window Screenshots

![Taito Memories Gekan_SLPM-66092_20231010142106](https://github.com/PCSX2/pcsx2/assets/8851653/a20c41ef-8a11-43fc-8ece-f05b398e2f93)

**Comment by Mrlinkwii** [comment]
can  i have a gs dump just to double check ? :)

**Comment by seta-san** [comment]
[Taito Memories Gekan_SLPM-66092_20231010143727.gs.zip](https://github.com/PCSX2/pcsx2/files/12861237/Taito.Memories.Gekan_SLPM-66092_20231010143727.gs.zip)
