### ISSUE TITLE
[BUG]: `Automatic Update` download size is always shown as zero.

### ISSUE THREAD

**Issue by tomasz-rozanski** [PCSX2/pcsx2#10087]
### Describe the Bug

The Automatic Update dialog always shows the update size of 0.00 MB.

![image](https://github.com/PCSX2/pcsx2/assets/11074159/08861461-c2c5-4777-b86d-0c4558df3fe1)

### Reproduction Steps

* Select menu `Help->Check for Updates...`
* If the update is available, an `Automatic Update` dialog window will open
* No matter, how many changes there is in the update, the last line of text in the dialog reads: ```Installing this update will download 0.00 MB through your internet connection.```

### PCSX2 Revision

1.7.5093

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
This is  a UI issue

**Comment by F0bes** [comment]
The issue isn't the UI. Our website API doesn't report the download size yet. It'll be implemented soon.
