### ISSUE TITLE
[BUG]: Emulator runs slow when limiting the processor power management

### ISSUE THREAD

**Issue by Xerlientt** [PCSX2/pcsx2#10097]
### Describe the Bug

I know this is a very specific issue that most people probably don't even encounter due to it's nature, but ever since I've had to reduce my processor power management to 99% to avoid overheating, the emulator runs slow no matter what settings I use (and I've tried practically everything)

I haven't encountered this issue with any other emulators so it's specific to PCSX2

### Reproduction Steps

In the processor power management options, maximum set to 99% instead of 100%

### Expected Behavior

Slow-down on all games regardless of settings

### PCSX2 Revision

v1.7.5105

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Are you on an intel CPU? because this is a common problem on intel (especailly older chips around skylake era), and there's not much we can do about it, it's just the CPU ramping down in the time the emulator is waiting for vsyncs.

**Comment by stenzek** [comment]
Not really sure what you expect us to do here. If you're going to limit processor speeds, then of course there's going to be slowdown.

If it's a mobile chip and this is preventing it from turboing, then it may very well be too slow to run heavier games.

**Comment by Xerlientt** [comment]
> Not really sure what you expect us to do here. If you're going to limit processor speeds, then of course there's going to be slowdown.
> 
> If it's a mobile chip and this is preventing it from turboing, then it may very well be too slow to run heavier games.

I was wondering if there was a way to work around this, because as previously mentioned, none of the other emulators have this problem, from Dolphin to even Xemu, not to mention there's a lot of heavy games I've managed to play without issues, so again this is VERY specific to PCSX2

**Comment by refractionpcsx2** [comment]
The Github is not really the place for support issues, if you would like to ask questions I really suggest visiting either the forum or the Discord, people are very happy to help there.

The Github is really for tracking bugs (which are definitely the fault of PCSX2) and code improvements.

**Comment by Xerlientt** [comment]
Alright... is there a way to delete this thread now?

**Comment by refractionpcsx2** [comment]
It's fine, we've closed it.
