### ISSUE TITLE
[BUG]: Tekken Tag Tournament / changing the FOV causes consistent FPS drops

### ISSUE THREAD

**Issue by Pcsx2user** [PCSX2/pcsx2#10098]
### Describe the Bug

this is an old issue that seems haven't been specifically reported and haven't been fixed during recent Nightly versions either , so I decided to specify the problem - the emulation engine seems to lost stability whenever stage's FOV changes in two scenarios : in ogre stage and in Yushimitso stages , both of which have significant frame drops down to below 40s from the locked 60fps when you move back to the edges and FOV get wide - in all other scenarios game runs smoothly and perfect, so I think that it can be also a problem with rendering engine or specific latency in depth rendering that should be solved 

### Reproduction Steps

Just go to any battle mode (practice , Arcade, etc) and when you choose or reached to the related stages go back as far as you can up to the edges of the screen, and performance will drop consistently 

### PCSX2 Revision

1.7.5104

### Operating System

Windows 10 (64bit)

### CPU

I5 1035G1

### GPU

GeForce MX450

### GS Settings

All Default Settings (Vulkan)

### Emulation Settings

All default settings

**Comment by Pcsx2user** [comment]
> I suspect it might just be your computer isn't good enough.
> 
> Can you post a GS Dump from when it's running slow?

Hello sir, you can see GS Dump in this attached file, this was the issue in another scenarios too , but mostly fixed in the recent updates, except these two that I've mentioned - I can get locked 60FPS in any other case  ; you can also test the situation that I explained and see if you're faced with same problem (specially Ogre stage)
[Tekken Tag Tournament_SLUS-20001_20231013132623.gs.zip](https://github.com/PCSX2/pcsx2/files/12892362/Tekken.Tag.Tournament_SLUS-20001_20231013132623.gs.zip)

**Comment by refractionpcsx2** [comment]
yes, the Ogre stage is very heavy, as you can see in my screenshot I'm only just getting 70fps, that's because the game is doing over 7000 draws, it's pretty heavy

![image](https://github.com/PCSX2/pcsx2/assets/6278726/ab60cc9d-1e93-4ef9-a20d-f5bdce69ad97)

**Comment by Pcsx2user** [comment]
what is your typical FPS in another scenarios?

**Comment by refractionpcsx2** [comment]
double, if not treble that.

**Comment by Pcsx2user** [comment]
> double, if not treble that.

Oh interesting, I hope there's a way to improve this one in the next updates - also I do appreciate your quick and helpful assistance , hope developers can make it better

**Comment by refractionpcsx2** [comment]
Not sure there's much we can do, the game is hammering the GS, we can maybe improve it in future, but I'm not going to guarantee it, it's working correctly, just needs a good machine.

Anyway, closing as this isn't a bug.
