### ISSUE TITLE
[BUG]: can't find rc_api_info.h

### ISSUE THREAD

**Issue by d0sensuppe** [PCSX2/pcsx2#10109]
### Describe the Bug

On building the package from source, the build always crashes upon reaching 70%. 
I am met with the following build error:
`/usr/include/fmt/core.h:1580:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
"`

### Reproduction Steps

Compile builds from the lalatest slackbuild on Slackware 15.
Newer builds not possible due to outdated libraries.

### PCSX2 Revision

v1.7.3526

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Slackware64 15  

### Logs & Dumps

[ 40%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/Achievements.cpp.o
/tmp/SBo/pcsx2-1.7.4879/pcsx2/Achievements.cpp:48:10: fatal error: rc_api_info.h: No such file or directory
   48 | #include "rc_api_info.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:109: pcsx2/CMakeFiles/PCSX2.dir/Achievements.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:889: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by stenzek** [comment]
Why are you asking us for help with a "slackbuild"? This is not our responsibility, speak to the packager.

Furthermore, we only support the latest nightly, not something hundreds of versions old.

Every PCSX2 release has built fine on our infrastructure on Linux. Our build scripts are public, so you can reproduce them.

Slackware has ancient libraries/compilers. Use the AppImage/Flatpak, or failing that, run the Windows version in Wine.
