### ISSUE TITLE
[BUG]: Item drops in Jak 3 are incorrectly colored in HW mode.

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#10104]
### Describe the Bug

The ammo along with health drops are incorrectly colored. This used to be fixed by setting blending to high, but alas it does not work anymore.

### Reproduction Steps

Use my gs dump:
[Jak 3_SCUS-97330_20231014050549.gs.zip](https://github.com/PCSX2/pcsx2/files/12901368/Jak.3_SCUS-97330_20231014050549.gs.zip)

### Expected Behavior

Check software mode.

### PCSX2 Revision

1.7.5105

### Operating System

Windows 11

### CPU

I7-6700

### GPU

1050 TI

### GS Settings

Default

**Comment by JordanTheToaster** [comment]
Not a bug needs high blending.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/4c4efc45-93c8-44b6-8cb4-d35abdc17eaf)

**Comment by Buzzardsoul** [comment]
@JordanTheToaster Can you try using direct3d11?

**Comment by JordanTheToaster** [comment]
It won't work on DX11 without ROV

**Comment by stenzek** [comment]
You have nvidia, you shouldn't be using directx.
