### ISSUE TITLE
[BUG]: Program crash when pluging joy-stick

### ISSUE THREAD

**Issue by chawapolavanew** [PCSX2/pcsx2#10100]
### Describe the Bug

1. I bought a new joystick controller. (anitech model j235)
2. I try to connect with PCSX2
3. It seems like they are not compatible. It looks like the joystick always holds the down button.
4. I tried to download its driver and installed it.
5. after that, when I connected the joy-stick USB to my computer, PCSX2 crashed.

### Reproduction Steps

1. download driver name "VL807USB Vibration Joystick(4a12k)3.60" and install.
2. when you connect the joystick to a computer, the PCSX2 crashes.

### Expected Behavior

PCSX2 does not crash and Joy-stick is working.

### PCSX2 Revision

1.7.5106

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[log&dump.zip](https://github.com/PCSX2/pcsx2/files/12895255/log.dump.zip)

**Comment by kamfretoz** [comment]
GitHub isn't for support, join our discord server and we can help you.

**Comment by stenzek** [comment]
```C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL:EZFRD64.DLL (0000000010000000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL'
```
Known buggy driver. Not our fault.

See https://www.google.com/search?q=EZFRD64.DLL+crash
