### ISSUE TITLE
[Idea] Link config guide within emulator/add help menu item

### ISSUE THREAD

**Issue by Sarania** [PCSX2/pcsx2#1011]
I submit this idea for discussion. Basically we currently have a config guide, and we are currently about to have an even better voiced one when I get done with it. I think it would be a good idea to link it within the emulator. Not to make me more famous :p but rather to help the less technically inclined users. From what I've observed the non tech people tend to search for a help link within whatever program they use. PCSX2 has no help menu proper, but I submit that a Help item could be added to the misc menu which pops a dialog that links some useful stuff like the config guide, perhaps a BIOS dumping guide, and some other things I probably will think of later. Oh and maybe the wiki.

What are your thoughts on this? @refractionpcsx2 @ssakash @turtleli @gregory38 (Sorry for pinging!)

**Comment by Nobbs66** [comment]
I think it would be a good idea, though I help tab might be more useful than putting it in the misc tab.

**Comment by gregory38** [comment]
nice improvements are always welcome

**Comment by ssakash** [comment]
I already have a local branch ready with the code for menu item and dialog , just ping me when you have completed the voice config guide and I'll add it's respective link to the dialog and make a PR. but we also probably need to include other documents/ information which might help users ? suggestions are welcome.

**Comment by ssakash** [comment]
Well, it seems like I have to code it again from scratch as my local branch is missing ! 

@Sarania : could you provide something like a blueprint on how the dialogs content should look ? I didn't really like my previous one ;)

**Comment by Sarania** [comment]
I can do that, give me a day or so to mock something together!

**Comment by FlatOutPS2** [comment]
I created a new menu for the custom build with wiki link from the forum. We could keep the new menu, call it Help and also include these links. It sticks out more than hiding it in the Misc menu.

**Comment by gregory38** [comment]
any status ?

**Comment by lightningterror** [comment]
What are we gonna do with this ?

**Comment by ssakash** [comment]
I think I still have a branch I did earlier for this one, would probably need to rebase it with the latest GUI changes though.

**Comment by lightningterror** [comment]
I will close this as it's really low priority, plus we really made most of the process pickup things automatically so users don't need to bother with non default settings anyway.
Also we link config guide and faq during first time setup.
