### ISSUE TITLE
[BUG]: Xenosaga Episode III artifacts from version v1.7.5100

### ISSUE THREAD

**Issue by gingsz** [PCSX2/pcsx2#10110]
### Describe the Bug

After [#10093 ](https://github.com/PCSX2/pcsx2/pull/10093) graphical artifacts appear in game. It's there in native res, not just upscaled.

[v1.7.5099](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5099)
![Xenosaga Episode III - Also Sprach Zarathustra  Disc 2 of 2 _SLUS-21417_20231014125555](https://github.com/PCSX2/pcsx2/assets/4439930/b57b0ff4-1531-457d-bde7-4976aab9498c)

[v1.7.5100](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5100) and all version after
![Xenosaga Episode III - Also Sprach Zarathustra  Disc 2 of 2 _SLUS-21417_20231014125812](https://github.com/PCSX2/pcsx2/assets/4439930/56a8f16d-c7a6-414f-88a4-ad19f93ee04f)

### Reproduction Steps

Play the game.

### Expected Behavior

No artifacts.

### PCSX2 Revision

v1.7.5109

### Operating System

Windows 11

### CPU

I5-4570

### GPU

GTX 1650

**Comment by stenzek** [comment]
Why did you not provide a GS dump?
