### ISSUE TITLE
[BUG]: Scale to host refresh rate + 120hz display + vsync = FastForward not disabling

### ISSUE THREAD

**Issue by user18081972** [PCSX2/pcsx2#10120]
### Describe the Bug

When monitor = 120hz
Gsync = OFF
When renderer = Vulkan/OpenGL
Vsync = true
Scale to host refresh rate = true

While in a fullscreen game.
When ToggleFramerate/ToggleFastForward hotkey is used to start, and then stop a speedup, the game stays sped up, and wont return to 100% speed unless you toggle out of fullscreen and back into fullscreen.

3 things seem to solve this:
1. Setting vsync=false solves this, when monitor=120hz.
2. When monitor=60hz, vsync can stay on and the issue is also fixed.
3. Using a DirectX renderer (in exclusive fullscreen atleast)

### Reproduction Steps

1. Have 120hz monitor, set it to 120hz.
2. Disable any vsync overrides on the GPU driver level. (e.g. Nvidia control panel)
3. Turn Gsync/freesync (VRR) off if available for your monitor (Due to "scale to host refresh rate")
4. set scale to host refresh rate = true
5. Set vsync = true
6. bind either ToggleFrameLimit or ToggleFastForward to a key.
7. Start a game
8. Enter fullscreen if not already
9. Toggle either key, so the game speeds up
10. Toggle the key again, so the game SHOULD return to 100%, but wont (for me)

### Expected Behavior

Game should return to 100% speed after the hotkey is used to toggle back to being framelimited / no longer fast forwarding.
While a monitor is set to 120hz, and scale to host refresh rate is on.

I might be wrong on this, maybe 'scale to host refresh rate' is just incompatible with this scenario.

### PCSX2 Revision

v1.7.5120

### Operating System

Windows 11

### CPU

i9-11900KF

### GPU

3080 10GB

### GS Settings

default

### Emulation Settings

default

### GS Window Screenshots

not really a graphical issue in this sense I believe.

### Me rambling
This is NOT a big issue, since i can just change my monitors refresh rate to 60hz and its solved, which is probably better for framepacing anyway.
Also my monitor supports 59.94hz, so 'Scale to host refresh rate' is uncessesary if i just set my monitor to 59.94hz, if i understand it correctly.
But then again my monitor also supports 119.88hz which divides perfectly into 59.94 NTSC as opposed to 60hz, but also has this issue.

**Comment by JordanTheToaster** [comment]
You shouldn't be using scale to host as you already have VRR regarding the issue I cannot reproduce it on current master.
