### ISSUE TITLE
[BUG]: The Japanese version of Tekken Tag Tournament does not display the game name

### ISSUE THREAD

**Issue by andymage593** [PCSX2/pcsx2#10129]
### Describe the Bug

The Japanese version of Tekken Tag Tournament does not display the game name

### Reproduction Steps

The Japanese version of Tekken Tag Tournament does not display the game name

### Expected Behavior

Want to include the game title Tekken Tag Tournament Japanese version。
PBPX-95201
CRC:40DA9BB8
![image](https://github.com/PCSX2/pcsx2/assets/127004996/d41aed89-703a-43ad-987b-021facf8dd9f)

### PCSX2 Revision

PCSX2 v1.7.5122

### Operating System

Windows 11

### CPU

13th Gen lntel(R) Core(TM)i7-13700KF

### GPU

NVIDIA GeForce RTX 2060

**Comment by Berylskid** [comment]
Have you made sure if your `PBPX-95201` is actually a Tekken disc?

According to GameIndex, this disc is `Utility Disc [Version 1.00]` instead.

**Comment by Mrlinkwii** [comment]
redump tells me its a Utility Disc http://redump.org/disc/23522/ , what probbally happened is the tekken demo reused a serial (wouldnt be the first time) so id recommend  manually changing the name in pcsx2

**Comment by andymage593** [comment]
I have manually modified the correct name。
![image](https://github.com/PCSX2/pcsx2/assets/127004996/a1f681ec-9ca1-4100-b2a7-fc1a2e97acf4)

**Comment by refractionpcsx2** [comment]
Won't fix on this one, they used a generic serial, potentially a pirate copy, not sure.

Either way, they used a different discs serial, and we rely on the serial to display the names, so yeah, if you want a custom name, you'll need to do it yourself, I'm afraid.
