### ISSUE TITLE
[BUG]: The retro arcade game Tekken 1, Tekken 2, and Tekken 3 included in Tekken 5 has line issues.

### ISSUE THREAD

**Issue by andymage593** [PCSX2/pcsx2#10132]
### Describe the Bug

The retro arcade game Tekken 1, Tekken 2, and Tekken 3 included in Tekken 5 has line issues.
![T1](https://github.com/PCSX2/pcsx2/assets/127004996/ebb2335f-cc1f-4496-9e75-81f1f44a1c17)
![T2](https://github.com/PCSX2/pcsx2/assets/127004996/0da69938-6638-4184-9ccc-3a8fa429783e)
![T22](https://github.com/PCSX2/pcsx2/assets/127004996/8636de15-a583-4e53-9cc0-047253608ac3)
![T222](https://github.com/PCSX2/pcsx2/assets/127004996/9abad3cf-6be5-48a2-9adb-cdf1336c9348)
Both Tekken 1 and Tekken 2 have texture line errors。
![T3](https://github.com/PCSX2/pcsx2/assets/127004996/05353076-d3d4-42bb-baa5-231b76bfc2ff)
Tekken 3 display texture outline is wrong and looks like floor tiles。
All the above errors can only be displayed normally in software rendering mode, but the picture is extremely unclear.

### Reproduction Steps

The retro arcade game Tekken 1, Tekken 2, and Tekken 3 included in Tekken 5 has line issues.

### Expected Behavior

![image](https://github.com/PCSX2/pcsx2/assets/127004996/483db35c-8ceb-4e08-bbed-48aa2d22e1f3)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/99e659ff-47d8-48a4-a5f4-b1b6fe00c6ac)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/1e885e9b-e11c-4691-89c8-daa39ff519bb)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/e594352a-872d-493d-9ae4-ca8d6058b835)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/23df0394-c195-4e32-b75d-71ea8beefa11)

### PCSX2 Revision

v1.7.5122

### Operating System

Windows 11

### CPU

13th Gen lntel(R) Core(TM)i7-13700KF

### GPU

NVIDIA GeForce RTX 2060

**Comment by stenzek** [comment]
Please see this note in the issue template: *We do not accept issues relating to upscaling at this time.*.

PS1 games are even more picky with UVs than PS2 games.

**Comment by andymage593** [comment]
Is there any way to solve this problem?

**Comment by refractionpcsx2** [comment]
You can visit the discord and we can try to help you fix it for you, but this is a support issue, so not really related to this github.
