### ISSUE TITLE
[BUG]: The Acid Rain battle scene in Tekken 5 does not display time numbers, and the menu page also displays errors.

### ISSUE THREAD

**Issue by andymage593** [PCSX2/pcsx2#10131]
### Describe the Bug

The Acid Rain battle scene in Tekken 5 does not display time numbers, and the menu page also displays errors.
![QQ截图20231017114307](https://github.com/PCSX2/pcsx2/assets/127004996/bb0bb7b8-88f4-4213-aef9-57ec1c4fb604)
![QQ截图20231017125515](https://github.com/PCSX2/pcsx2/assets/127004996/9efe2498-bacb-4c2d-beeb-9315e84c8faf)
https://lh3.googleusercontent.com/pw/ADCreHdhHoQgwv0quy_thBi0dGUmmE4dtduO-QmTFVdgHHPMrGiNJrnUw5BO5tABfFCXxCDOHfN1R-J3-lbqDE9LyWRNtIpirX0ZKN6f5poQAVjgqW25GGmlqQXGoC9nMcvkdUwRdwPjbhf-UXkxERBS-Bpq3ZK07CP0oQa9s_8H0BtJMYAnEzQjiuUEz_TSbzRi2VaF7f4EAxyLe4kEl7MpSvtRcrKcY4-Go5dGgSoWWOLuZSBDZPG6oB8c8DvNgMvQ_Q60p9aukFcKOUMbVUReoQv96QKnhMO-PBhwLnI_CTQzPM9p4CfUBo5SwS8qRBFUylXmI7uz3jPPrtBOm9OlgO5NjJPrk6TN0nLqOt_HtovrdA-hjw5lSk8uSN0PGaIhswlmRT6T7BIStUor94pV3cvrIdAGXd3J1eWxcZcy46slAwpxRN46TUANJ7XlK876-TyxZ8W7y21Yu0ITR2pJ5lUUZAlq4RCdwq8xO5QGlXKEELNLGmlMotv4LNa65WpT2Ti2modkU17-lKjdYELX7hhVyPE9AYMnrSoEsq_GqvDyMjYCtdjryP3pCtZPJ-RFF0e6jqYUHl46VbAWUfI-Q1IqDNc9wG-C0xPVUArQY4Hd5Mo5TDaq4RtkU3-JUTcTjDBWEaAcq5FSvQwSQB17wUTpkoFbHvlJaUKGWbt4FNKmLn7yvANHT7eaTaN1URTCbt1XNIPiNXs_7sD0NDdYNORf9i9OhppNZycuWUEkwChxcwTOTdO4PyDO-NNdMpH_a-yljehn9p8dysYJ36DVElREKEdhF0b4E5Uz3mjftPYKvReF2vH2ZqdeAPPVfJouC5dbgAoEP_8kOBujDp7WlQiphKzb3uepqorD02or0wpPMmSqC6iormYGHGDdFfeLtD7emEQC7w07TYqNB3NQ=w824-h460-s-no-gm?authuser=0

### Reproduction Steps

The Acid Rain battle scene in Tekken 5 does not display time numbers, and the menu page also displays errors.

### Expected Behavior

![image](https://github.com/PCSX2/pcsx2/assets/127004996/fce3573f-e0fa-43b3-960f-d951043e56a4)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/34a072b8-57fe-43d9-abcd-a384f60b8cca)

### PCSX2 Revision

v1.7.5122

### Operating System

Windows 11

### CPU

13th Gen lntel(R) Core(TM) i7-13700KF

### GPU

NVIDIA GeForce RTX 2060

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/127004996/cb8149af-afe4-4677-9425-ffb76aac3e39)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/8d6d6cac-c2a8-4892-8c5a-12a68c710612)

**Comment by JordanTheToaster** [comment]
GS Dumps of the issue.

[Tekken 5 Acid Rain Issue.zip](https://github.com/PCSX2/pcsx2/files/12924441/Tekken.5.Acid.Rain.Issue.zip)

**Comment by andymage593** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/127004996/ba1801c5-ac57-4d5b-a32e-4483a1d09190)


> GS 问题的转储。
> 
> [铁拳 5 酸雨问题.zip](https://github.com/PCSX2/pcsx2/files/12924441/Tekken.5.Acid.Rain.Issue.zip)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/5276cbf6-6d32-482a-afcc-af416b0d3fe6)
I have this Japanese version, but the number is different. Can I use it? Also, how to use this file? Is there any loading tutorial?

**Comment by stenzek** [comment]
It's probably the CRC hack breaking.

**Comment by andymage593** [comment]
The new version has fixed this problem
![image](https://github.com/PCSX2/pcsx2/assets/127004996/65f8a9d7-35c6-47e0-98ce-df00b0dca405)
![image](https://github.com/PCSX2/pcsx2/assets/127004996/47b60ee4-c95f-4dea-bcfc-f260e5542a41)
