### ISSUE TITLE
[Feature Request]: Upcoming changes to publishing to Flathub

### ISSUE THREAD

**Issue by barthalion** [PCSX2/pcsx2#10133]
### Description

Flathub will be enabling server-side build validation on a tentative date of November 6th. This will require some changes to your pipeline for publishing new builds:

- the validation part can be replicated by using `docker pull ghcr.io/flathub/flatpak-builder-lint:latest` on the ostree repo produced by flatpak/flatpak-builder. Example usage: `flatpak-builder-lint --exceptions repo /path/to/ostree/repo`
- `flat-manager-client create` needs to include `--build-log-url $URL`, where $URL points to a pipeline building the flatpak. This is also exposed by the latest release of the flatpak/flatpak-github-actions/flat-manager GitHub Action.

**Comment by stenzek** [comment]
Has this been enabled early? I'm seeing `Api call to https://hub.flathub.org/api/v1/build/59429/publish failed with status 400, details: {'current-state': 'failed', 'error-type': 'wrong-repo-state', 'expected-state': 'ready', 'message': 'Build failed: 1 out of 2 checks failed (flatpak-builder-lint)', 'status': 400}` in the actions log.

Was going to look at it on the weekend, been crazy busy work with lately and haven't had time.

**Comment by stenzek** [comment]
Looks like it's gone through now, thanks :)

Given it was failing one of the lint checks, obviously there's something we need to address on our side, I'll sort that out in the next few days. Good luck with the issue hunting!
