### ISSUE TITLE
[Feature Request]: Place a Cheats button on the in-game toolbar

### ISSUE THREAD

**Issue by platyhooks** [PCSX2/pcsx2#10147]
### Description

It would be nice to have a Cheats icon on the in-game toolbar that displays the cheat manager with less clicks.

### Reason

Right now when using or troubleshooting cheats. You need to launch a game and then click settings, click game properties, and then click cheats to get to the cheats menu. It would streamline the user experience if there was a shortcut on the toolbar that just opened the game specific cheats manager instead of having to go three clicks deep to get at it.  
  
While if you have functioning reliable cheats that work consistently this is bearable. If you are troubleshooting cheats, especially ones that require a reboot this can be tedious. (i.e. Romance of the Three Kingdoms)

![1](https://github.com/PCSX2/pcsx2/assets/73786333/e07c1c07-f16d-476d-a8c2-ed55b6373d5e)

![2](https://github.com/PCSX2/pcsx2/assets/73786333/b300aa05-808c-4dcd-8600-8be258c49b47)

### Examples

PCSX2:
![pcsx2](https://github.com/PCSX2/pcsx2/assets/73786333/ed184dd9-e4bb-4d17-91a3-c008350e5efc)

DuckStation:
![Duckstation](https://github.com/PCSX2/pcsx2/assets/73786333/07ad22d6-16ce-42e9-8186-8a5eab90ef6e)

I apologize if this somehow already exists and I have missed it or has been previously decided on and I'm bringing up a closed decision.

Thank you.

**Comment by stenzek** [comment]
DuckStation has a cheat manager UI. No equivalent exists in PCSX2 for the button to be hooked up to. If you made it open game properties and select the cheats submenu, it's saving one mouse click (to select the menu category), and wasting space in an already-overcrowded toolbar.

You can open game properties by right clicking in the game list, or from the settings button, and leave the window open throughout reboots .

**Comment by platyhooks** [comment]
OK!
Thank you for tip on the right-click option on game list. That is very helpful.
