### ISSUE TITLE
[Feature Request]: Achievement Sound Settings

### ISSUE THREAD

**Issue by yojoehojo** [PCSX2/pcsx2#10149]
### Description

1. A slider for the volume of the achievement sound
2. A setting that allows you to change the achievement sound, if you put a sound file in the same folder as the main sound file then you should be able to select that, the main one, or any other possible sound in that said folder. (I know it's a wav file, but I'm using the most basic terms to hopefully get across the point as understandable as possible)

### Reason

It's a little weird that the achievement sound is an xbox sound, kind of takes me out of the experience of playing a PlayStation 2 title and while I know I could turn off the sound or change it through digging around in the folders, I don't mind hearing something for when I get an achievement and I'm aware that if I were to change the sound manually then the updates would automatically change it back. If this were a setting, then it could be scripted to stay with the changes.

Also, it's way too loud. Needs a Volume slider of its own.

### Examples

Say you want the sound to be the same sound as getting a trophy via the psn or maybe to make it more specific to the PS2 era of gaming you want to make it the sound of the cursor noise in the memory card interface. You put that in the folder, select it in the settings menu of the PCSX2 app and now every time the application updates that sound is THE sound for it. Oh but you didn't take the time to edit the base volume of the file? that's okay, there's a slider to lower the percentage of the volume so it doesn't blast your ears out.

**Comment by stenzek** [comment]
> A slider for the volume of the achievement sound

Not possible. We just call [PlaySound](https://learn.microsoft.com/en-us/previous-versions//dd743680(v=vs.85)), which is handled by the OS, not mixed into our audio stream. If I remember correctly, it uses the system notification volume.

> A setting that allows you to change the achievement sound, if you put a sound file in the same folder as the main sound file then you should be able to select that, the main one, or any other possible sound in that said folder. (I know it's a wav file, but I'm using the most basic terms to hopefully get across the point as understandable as possible)

The resources directory is off-limits to you as a user. Anything you put in there will be overwritten with updates.

> Also, it's way too loud. Needs a Volume slider of its own.

You can always turn the sound effects off - there's an option for that already.

**Comment by yojoehojo** [comment]
> > A slider for the volume of the achievement sound
> 
> Not possible. We just call [PlaySound](https://learn.microsoft.com/en-us/previous-versions//dd743680(v=vs.85)), which is handled by the OS, not mixed into our audio stream. If I remember correctly, it uses the system notification volume.

Could rescript it a teensy bit,

 
> > A setting that allows you to change the achievement sound, if you put a sound file in the same folder as the main sound file then you should be able to select that, the main one, or any other possible sound in that said folder. (I know it's a wav file, but I'm using the most basic terms to hopefully get across the point as understandable as possible)
> 
> The resources directory is off-limits to you as a user. Anything you put in there will be overwritten with updates.
 
You could just change where that resource is stored just like memory cards has it's own folder. I know this is slightly different, but admittedly you are coming off pretty rudely when I'm asking for realistically the smallest tweak.

**Comment by refractionpcsx2** [comment]
Tbh it's pretty rude of you to assume it's just a small tweak and we're being resistant to it.

If it's a small tweak, you have no trouble in making your own PR for the change, we are an open source project, contributions are welcome.

**Comment by stenzek** [comment]
> Could rescript it a teensy bit,

It's not a "teensy bit", you would have to open an audio stream, buffer samples, and write them on demand, which is silly for just a notification sound. Not to mention it could cause stutter.

But if it's just a "smallest tweak" and you know better, please open a PR as refraction said, we'd appreciate it.
