### ISSUE TITLE
[BUG]:  NFL Quarterback Club 2002 Freezes when starting QB Challenge mode [SLUS-20154]

### ISSUE THREAD

**Issue by mysteria25** [PCSX2/pcsx2#10156]
### Describe the Bug

The game freezes right after QB Challenge mode begins to start. However, audio continues to play.  Exhibition games start fine, but the game also freezes right before controller 1/player1 kicks the ball (kick offs, Extra point etc).  If you change the player one controller to cpu before the kick, it will not freeze but it will freeze every time if player 1 is set to kick.

Game dump has been checked and Verified.  No cheats or widescreen patches are being used. This game has been doing this for many years on PCSX2 since I can remember, but apparently has never been reported on here.

### Reproduction Steps

At the main menu, just go to QB Challenge and let it load.  It will freeze as soon as the field shows.  For kicks to freeze, just kick off or kick extra point after TD.

### Expected Behavior

No freezes, it should just play normally.

### PCSX2 Revision

PCSX2 Nightly - v1.7.5140

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

GTX 1660 Super

### GS Settings

Software mode, hardware mode,  freezes either way.

### Emulation Settings

Default settings, without MTVU.  Also tried many manual game Fixes.  Still freezes.

### GS Window Screenshots

https://github.com/PCSX2/pcsx2/assets/80365365/2a4aa529-7816-47c9-862c-74ae10a8a642

**Comment by prafullpcsx2** [comment]
Can you try this patch file and report if it fixes the bug (Also whether it creates other issues ingame).

https://forums.pcsx2.net/attachment.php?aid=78434

**Comment by mysteria25** [comment]
So far, so good.  Awesome job prafull, thank u!  I will update if I notice any other issues.

**Comment by Goatman13** [comment]
Just in case. This game (and Fuuraiki 1/2) needs proper error handling for IPU GetMacroblockModes(). Setting ECD is only implemented for VDEC, and sadly correct behavior for IDEC is not documented anywhere.

What games seems to expect is that error in GetMacroblockModes() will **end command** and set ECD. There is no mention of that anywhere but when error occur inside IPU it's reasonable to abandon current encoding.
