### ISSUE TITLE
GSDx OpenGL: Heavy terrain glitching (Ace Combat 5)

### ISSUE THREAD

**Issue by markubiak** [PCSX2/pcsx2#1015]
PCSX2 Version: 1.3.1-git, October 5 2015 (from Arch Linux repositories.  pcsx2-git built manually also has issue)
PCSX2 Options: Safest preset, speedhacks off, no options change the issue whatsoever
Plugins used: GSDx OpenGL, SPU2-X, OnePad, rest null
Plugin versions: GSDx 1.0.0 AND 0.1.16
Description: 
![gsdx_20151201184054](https://cloud.githubusercontent.com/assets/2127493/11518996/e989abec-985b-11e5-8e7e-cc52b44ae067.png)
![gsdx_20151201184057](https://cloud.githubusercontent.com/assets/2127493/11518995/e987d7e0-985b-11e5-910d-1c59e66fc3df.png)
![gsdx_20151201184059](https://cloud.githubusercontent.com/assets/2127493/11518997/e98af038-985b-11e5-96aa-262e28f4edd7.png)
![gsdx_20151201184101](https://cloud.githubusercontent.com/assets/2127493/11518998/e98ae5d4-985b-11e5-8063-cd5aa25eb4d3.png)
When using GSDx OpenGL, there are very heavy texture glitches for the terrain, and only the terrain.  This issue does not occur for planes, ships, or environmental objects (bridges, buildings).  This error occurs both in software and hardware mode, and happens in exactly the same way.  The texture glitches are NOT static as they appear in the picture, they change as I move through the map.  They  act in "tiles" that kind of move through the map.  It's very odd.  I'm going to report this as an OpenGL issue, because other users do not report this issue when using the DirectX11 software renderer.
PC Specs: i7-4700HQ, Nvidia GTX860M (error occurs both with integrated and discrete graphics)
Other comments: Hardware render also has black lines, as reported on the wiki page for Ace Combat 5.  Software mode otherwise works 100% fine for me.

**Comment by willkuer** [comment]
If it happens in sw and hw I would not expect that it works in dx.
Can you please screenshot gsdx settings?
The issue sounds a bit like lack of mipmapping.

**Comment by markubiak** [comment]
Mipmapping was disabled.  I reenabled it and the issue has evolved slightly.  Now it seems that the textures are all of a uniform color, but they are still not accurate and they still jump/move.  It looks a bit better though.
![gsdx_20151201194751](https://cloud.githubusercontent.com/assets/2127493/11519994/ad9ef390-9864-11e5-8646-834f6f6ffa41.png)
![gsdx_20151201194752](https://cloud.githubusercontent.com/assets/2127493/11519995/ada17b06-9864-11e5-8b2a-3545e489dd8d.png)

As requested, here is a screenshot of the settings (after enabling mipmapping):
![screenshot from 2015-12-01 19-48-22](https://cloud.githubusercontent.com/assets/2127493/11520009/c792004e-9864-11e5-9c12-0ba9b70c49f8.png)
![screenshot from 2015-12-01 19-48-29](https://cloud.githubusercontent.com/assets/2127493/11520008/c790285a-9864-11e5-997f-a6f6d43b02bf.png)
![screenshot from 2015-12-01 19-48-30](https://cloud.githubusercontent.com/assets/2127493/11520010/c7923bb8-9864-11e5-8fbd-ce0366d055ba.png)

**Comment by willkuer** [comment]
This is better? Looks worse to me. Now you only have black and white stripes, or?

Emulation/Core settings are default? Then I would recommend to create a small GSdump.

This might be a similar problem as the dbz problem @ssakash submitted once. I think the z-ordering in the far distance wasn't working there which resulted in flickering. Did this ever got resolved?

**Comment by ssakash** [comment]
> Did this ever got resolved?
Nope

**Comment by willkuer** [comment]
Btw you mentioned black and white lines in HW mode not in SW. Is the latest doublett of screenshots taken in HW or SW?
Mipmapping works only for SW.

**Comment by willkuer** [comment]
> here's that issue link: #544

:D first comment on that issue is a reference to this issue. Possibly they are really related.

**Comment by markubiak** [comment]
They seem somewhat similar, but my issue is much worse.  I'll try to get a video up later tonight.

**Comment by mirhl** [comment]
......
This is just an issue with mipmapping. Plain and simple.

**Comment by markubiak** [comment]
Here's two videos where I demonstrate the texture glitches with and without mipmapping, hopefully it helps.

[No Mipmapping](https://www.dropbox.com/s/cexga3obysopudy/ac5_no_mipmapping.webm?dl=0)
[Mipmapping](https://www.dropbox.com/s/0i0qwtmz0p4ukp9/ac5_with_mipmapping.webm?dl=0)

**Comment by mirhl** [comment]
There are no glitches here with OGL SW + mipmapping.

**Comment by gregory38** [comment]
I'm curious of how many people will install linux if they know they can run the SW rendering with upscaling :p (Just kidding)

I'm a bit lost will all those messages. So is the issue related to the lack of mipmapping in HW? Or is there any others issue?

**Comment by markubiak** [comment]
The only issue is texture glitching with the terrain. It happens in both hardware and software rendering.   willkuer suggested that it was related to mipmapping, so I provided videos with the  GSDx mipmapping option on and off.

**Comment by gregory38** [comment]
ok. I think I have some strange glitches on GT4 too I need @rz5 to do additional test.

**Comment by markubiak** [comment]
@mirhil AFAIK software rendering always works at native res.  It doesn't upscale regardless of GSDx settings. This hypothesis is confirmed by the fact that my game looks like shit.

**Comment by mirhl** [comment]
The point is that software rendering should *always* work ***only*** in native res. 

And @gregory38 it works and it has always worked in software mode with mipmapping enabled. On windows 7 and 8 at least. 100% sure. 

All this fuss (that I don't understand if others understood) comes from this odd UI issue that still state SW even when it's blatantly HW.

**Comment by markubiak** [comment]
I'm not sure if I was unclear on this, but the problem occurs with both software rendering and hardware rendering.

**Comment by mirhl** [comment]
Yes, you have been clear. 
And I'm telling you the problem is actually with dumb HW/SW selection.

**Comment by markubiak** [comment]
Okay, is that on my end?  Is there anything I can try on my end to help figure out/solve the problem?

**Comment by mirhl** [comment]
Check in the ini if Renderer=13

**Comment by willkuer** [comment]
You could as well press F9 during gameplay. One option should look blurry but correct the other upscaled but flickering.

**Comment by markubiak** [comment]
Renderer = 13.

[Here](https://www.dropbox.com/s/bqsuiojw234e8e9/ac5_sw_hw_all_mipmapping.webm?dl=0) is a combined video showing hardware and software rendering modes, as well as no mipmapping vs. mipmapping.  Hopefully this answers all questions about my configuration.

**Comment by willkuer** [comment]
13 = OGL_SW

Still if mirhl gets the correct image something is odd.
Can you please remove your settings (gsdx.ini) or just reinstall pcsx2 to check if something is borked with your config? Which crc does your iso have? It's written in the emulog.

**Comment by markubiak** [comment]
> SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_208.51;1
> (SYSTEM.CNF) Software version = 1.00
> (SYSTEM.CNF) Disc region type = NTSC
> ELF (cdrom0:\SLUS_208.51;1) Game CRC = 0x39B574F0, EntryPoint = 0x0031C138
> (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_208.51;1
> (SYSTEM.CNF) Software version = 1.00
> (SYSTEM.CNF) Disc region type = NTSC
> (GameDB) Patches Loaded: 4

I deleted all config files and reinstalled pcsx2.  Absolutely no change to the glitch whatsoever.

**Comment by gregory38** [comment]
@markubiak 
Is the issue recent or is it a regression?  Could you check PCSX2 configuration to use default. No speedhack, no manual gamefix etc...

It could be a linux/windows mismatches but it is strange.

**Comment by gregory38** [comment]
hum, could it be that I don't support patch correctly on linux
```
Serial = SLUS-20851
Name   = Ace Combat 5 - The Unsung War
Region = NTSC-U
Compat = 5
[patches = 39B574F0]
	comment=Rearranging COP2 instructions that use old results
	
	patch=0,EE,001A3B94,word,48498800
	patch=0,EE,001A3B98,word,4B00682C
	patch=0,EE,001A3BA4,word,484A8800
	patch=0,EE,001A3BA8,word,4B0C682C
[/patches]
```

**Comment by markubiak** [comment]
To whoever tested the issue against their own system, did you test the first campaign mission?  I don't remember issues until the third campaign mission.  However, the first arcade mission has this issue really bad, so that's a good one to test.

I realize that's kind of important now that I think about it.

**Comment by mirhl** [comment]
@willkuer I was so sure, because I thought HW settings were expected to gray out as in windows version. Though gregory said that's not the actual behavior under linux so I guess I was wrong. 

Still, I confirm again it all works good here with SW+mipmaps. 

@gregory38 those hacks are only needed to fix the third problem [here](https://code.google.com/p/pcsx2/issues/detail?id=219) after the work done by [sudonim](https://code.google.com/p/pcsx2/source/detail?r=5734) to fix incorrect COP2 recompilation

**Comment by markubiak** [comment]
Would my BIOS version matter?  I own a PS2 slim but saw the process to extract the BIOS and just "legally acquired" a Japanese one instead.

**Comment by rz5** [comment]
@markubiak Thanks for all the info you're providing. Out of curiosity, are you using the proprietary Nvidia driver or the nouveau one?

**Comment by markubiak** [comment]
I'm using the proprietary nvidia driver, but I've also tested my integrated Intel GPU (using Mesa) with no changes.

**Comment by willkuer** [comment]
One (the first japanese) bios is different than the others. Which version to you use?

**Comment by markubiak** [comment]
It's listed as `Japan v01.00(17/01/2000). Console`

**Comment by willkuer** [comment]
Thats exactly the only version that can make trouble with pcsx2. I dont know though if the bios matters at that point...

**Comment by markubiak** [comment]
I tested the BIOS listed in the edit and still had issues.  @gregory38 are you able to test AC5?  Maybe it's an issue with the Linux libraries...

**Comment by markubiak** [comment]
The plot thickens.

I rebooted into my Fedora 23 install on my laptop and ran the same tests.  To my surprise, running it in Software mode with my Nvidia card works great!  It was using an older Nvidia driver, 352.something, so I rebooted into Arch to test and compare the OpenGL features enabled on each driver.  They differed, but the interesting thing is that it worked perfectly in software mode on Arch!  I have no idea what changed.  It wasn't a BIOS issue, I retested that and both the Japanese and USA BIOSs work.  Nvidia drivers didn't update.  No configurations changed.  Honestly, I'm dumbfounded.  The bug persists under hardware mode for sure, but software mode now works fine.

Hmm.

**Comment by mirhl** [comment]
Which somewhat strengthen my idea it was a glitch in sw/hw selection or mipmapping engaging at most.

**Comment by willkuer** [comment]
I think the video contradicts that. But nevertheless that hw mode is lacking support for mipmapping is well known. All other problems seem to be resolved. I think this issue can be closed.

**Comment by markubiak** [comment]
That's fine with me. If the issue ever comes back up and I find out what caused it, I will be certain to comment on this with the solution.

Thanks for the help guys!  I feel like a little kid again replaying games I truly love.
