### ISSUE TITLE
[BUG]: Gran Turismo 4 - "Get Ready to Drive" message stuck on screen until camera change

### ISSUE THREAD

**Issue by AnthonyRyuki** [PCSX2/pcsx2#10165]
### Describe the Bug

If you start any race on GT4 on a rolling start, the "Get Ready to Drive" message won't disappear when the race starts and you gain control of the car. To make disappear, you need to change camera. This is annoying as the message gets on top of the suggested gear for the next corner.
![Gran Turismo 4_SCUS-97328_20231022183234](https://github.com/PCSX2/pcsx2/assets/62845774/d88fa599-9f98-4291-b7c5-4c23798533f1)

### Reproduction Steps

Start any race that starts with a rolling start.

### Expected Behavior

Said message should disappear when the race starts.

### PCSX2 Revision

v1.7.5144

### Operating System

Windows 10 (64bit)

### CPU

i5-4460S

### GPU

Intel HD Graphics 4600 (my PC has no dedicated video card)

**Comment by refractionpcsx2** [comment]
You need to change the EE Clamping under per game settings (right click game in your list, then properties)->Advanced to full for races, but change it back to Normal for the license tests.

If you can't see this section you need to go to Tools->Show Advanced first.

**Comment by AnthonyRyuki** [comment]
Thank you.

**Comment by AnthonyRyuki** [comment]
Unfortunately, doing this did not fix the issue.

**Comment by Technostrophe** [comment]
If you need further support, come on over to the Discord.
