### ISSUE TITLE
[Feature Request]: Readd Enable Leaderboards toggle to RetroAchievements

### ISSUE THREAD

**Issue by Bubblegum3390** [PCSX2/pcsx2#10161]
### Description

I would like to request to have the option to turn off RetroAchievement Leaderboard tracking again, just like how it was before the change.

### Reason

I really don't like having it in the same setting as Hardcore, as it causes a bunch of alert sounds and tracker indicators I do not want to see, and if I turn them off I lose the alerts and trackers for cheevos which I do want to see.

### Examples

![oldgood](https://github.com/PCSX2/pcsx2/assets/110075513/8681473e-e1b0-4908-8a9d-cd47e2ba4eab)
![newbad](https://github.com/PCSX2/pcsx2/assets/110075513/83e87895-385b-4203-8a0a-7fa4063c7cbb)

**Comment by stenzek** [comment]
We use rc_client now which does not currently support this.
