### ISSUE TITLE
[BUG]: two player mode time crisis 2 shot too high

### ISSUE THREAD

**Issue by magicray1028** [PCSX2/pcsx2#10169]
### Describe the Bug

Using two player mode on time crisis 2 with relative input causes the shot to be a few inches higher than the crosshair. But in full screen one player or menus both shots are perfectly accurate .

### Reproduction Steps

Play 2 player split screen mode

### Expected Behavior

Shot should be aligned with crosshair

### PCSX2 Revision

Current version 

### Operating System

Windows 11

### CPU

I5 13600K

### GPU

Rtx 3080

**Comment by refractionpcsx2** [comment]
did you enable screen offsets? because by default (screen offsets disabled) the picture gets stretched out, which is technically incorrect.

**Comment by magicray1028** [comment]
Offsets is disabled , should I turn it on?

**Comment by magicray1028** [comment]
you are a genius! it works with offset on and no recalibration needed!
