### ISSUE TITLE
[BUG]: "Properties" - grayed out

### ISSUE THREAD

**Issue by VirusVenomForever** [PCSX2/pcsx2#10167]
### Describe the Bug

when i try right click on game - "Properties" - grayed out. Why is that?
![image](https://github.com/PCSX2/pcsx2/assets/77768568/d04997e5-dd74-46ab-aafa-184797be2db6)

### Reproduction Steps

Add any .iso game into your library.
Right-click on it.

### Expected Behavior

The Properties option should be selectable, opening up the same menu as for image-based games.

### PCSX2 Revision

v.1.7.5144

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Works fine here, what the heck is IHUDER?

**Comment by Buzzardsoul** [comment]
I cannot replicate it.

**Comment by stenzek** [comment]
Working as intended. If the game doesn't have a serial (isn't in the database), then this option is disabled because we can't generate a game settings ini filename for it.
