### ISSUE TITLE
[BUG]: Linux Appimage does not Export Menu for use in Global Menu

### ISSUE THREAD

**Issue by d-air1** [PCSX2/pcsx2#10173]
### Describe the Bug

Hey, so this one isn't a big deal, but I noticed that if I build pcsx2 from source or download the flatpak. I can see the menu inside of the kde plasma global menu, but when I downloaded the appimage. The menu seems to be hardcoded into the app window. Is there any reason for that?

### Reproduction Steps

1. Use KDE Plasma or some linux operating system / desktop environment that provides a global menu. KDE and Unity are the only ones I know of that have one on linux. 
2. Download the pcsx2 appimage.
3. Open the appimage while having the global menu widget in effect. 

### Expected Behavior

Should see pcsx2's menu inside of the global menu and not in the app window like when I used the flatpak or built from source.

### PCSX2 Revision

v1.7.5148

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### Potentially Helpful
I just wanted to add that I tried the rpcs3 and citra appimages and both of those show their menu's correctly.

**Comment by kamfretoz** [comment]
That's due to how the AppImage works. If you need/want the system-wide global menu, you'll need Flatpak/Built from source

**Comment by d-air1** [comment]
> That's due to how the AppImage works. If you need/want the system-wide global menu, you'll need Flatpak/Built from source

Hey thanks for the speedy reply, and I had thought that appimage might be the problem. A few minutes ago I edited the initial report to include that I had tried the rpcs3 and citra appimages and both of those do work with the global menu. I was looking at the pcsx2 source code myself, but was stumped.

**Comment by d-air1** [comment]
Thanks.
