### ISSUE TITLE
[Feature Request]: Macro buttons hold

### ISSUE THREAD

**Issue by DolphinDan400** [PCSX2/pcsx2#10178]
### Description

Having a toggle to keep the specified macro buttons held until said macro is pressed again would be pretty useful to have.

### Reason

The main use I can think of would be the PS2 Pop'n Music games, if the Pop'n controller was plugged into the PS2, the game inputs would change to accommodate new controller layout. 
A Pop'n controller is detected by holding the **left**, **right** and **down** directions on the d-pad simultaneously and this can actually be done with any controller, however you have to keep the directions held all the time in order to use this controller mode, this can be done via external programs but it would be much easier to have an option to keep a button macro held until pressed again.

![Popn-Music-Mini-Controller](https://github.com/PCSX2/pcsx2/assets/94821269/f1bcb76a-e1c9-4f10-800e-a1adb1b6a94d)

### Examples

In the macro menu, check the buttons to be pressed, and have a toggle to have the buttons held until the macro is pressed again.

**Comment by stenzek** [comment]
This isn't really an appropriate use case - if you want to support this type of controller, the controller itself should be implemented, or an option added to mask the buttons.

Having to push a macro on startup is super janky.
