### ISSUE TITLE
[BUG]: Cabela's Dangerous Hunts 2 a Black Screen when Continiung from the Australian level to the Alaskan level . please help  

### ISSUE THREAD

**Issue by Maxioflex** [PCSX2/pcsx2#10174]
### Describe the Bug

i was playing and finshing the Australian hunting level in Cabela's Dangerous Hunt's 2 and after entering the Argentinan level from that it crashed and got struck in a Black screen .

### Reproduction Steps

i Picked the Iso from my specialized folder and after the game loaded up i pressed load then continue's after continue's and after i booted up where i left off it got struck in this Black screen like a Void 

### Expected Behavior

should have played a cutscene and started the level

### PCSX2 Revision

i got the newer version

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

i don't have a one

### CPU

it's a normal one

### GPU

i have none

### GS Settings

i have none

### Emulation Settings

it's normal

### GS Window Screenshots

![qwe](https://github.com/PCSX2/pcsx2/assets/135292600/c0b06871-d034-4314-a843-fef68567cb5e)

### Logs & Dumps

none

**Comment by Mrlinkwii** [comment]
you seem to need help in general , so id recommend join the discord

**Comment by refractionpcsx2** [comment]
Github is not for support issues, please use the forum or discord as suggested above.
