### ISSUE TITLE
[BUG]: Can only use OpenGP on PCSX2 Beta Version

### ISSUE THREAD

**Issue by TradeDraft** [PCSX2/pcsx2#10180]
### Describe the Bug

Comes Up when loading up a Game in PCSX2 with Error:

Failed to Create Render Device. This many be due to your Render (everyone accept OpenGL) or because your Graphics Card need to be Updated.

Done this in last few Days Updates

### Reproduction Steps

Open PCSX2 then Set Render to something that is Not OpenGL then Try load a Game and Error Pops Up

### Expected Behavior

Game to Load Normally

### PCSX2 Revision

pcsx2-v1.7.5148-windows-x64-QT

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Sorry, we don't provide support for pirates for legal reasons (this was pointed out to you in the forums).

GitHub is not for support issues, either.
