### ISSUE TITLE
[Feature Request]: Bring back Wayland support on the AppImage version

### ISSUE THREAD

**Issue by fmnm04** [PCSX2/pcsx2#10182]
### Description

Revert the changes made by #10179 and bring back wayland support as an optional feature for the appImage version of the emulator by setting the correct QT_QPA_PLATFORM value.

### Reason

Wayland support has been removed completely without even leaving the mere option of enabling it with an env variable just because of minor functionality bugs that only some users were having inconveniences with (see #10179). I'm not asking to bring back wayland as the default option like it was before the PR but it wouldn't hurt anyone to have it as an option like it's the case for many other emulators and applications.

### Examples

Many other emulators and applications like Yuzu, mGba or rpcs3 have optional, non default wayland support and yes, it's buggy in some cases, but that's not a reason for it to be  removed completely.

**Comment by stenzek** [comment]
We already replied to you, please don't flood our issue tracker, that's just childish behaviour. Thanks.
