### ISSUE TITLE
[BUG]: Regression - Ratchet Deadlocked Weather Effects Broken

### ISSUE THREAD

**Issue by Bubblegum3390** [PCSX2/pcsx2#10198]
### Describe the Bug

The weather effect is glitched, resulting in it being cut off on the bottom part of the screen, and some weather effects are rendered inaccurately. The issue is completely independent of and happens on all renderers, hardware and software, and on native and upscaled resolutions. I believe this to be a regression as the issue is not present on 1.7.4425.

### Reproduction Steps

Using the change weather cheat and setting to Heavy Sand Storm results in the issue being the most easily noticeable.

### Expected Behavior

This is the effect rendered correctly on 1.7.4425
![4425](https://github.com/PCSX2/pcsx2/assets/110075513/99c482ac-a98c-4ad8-9003-8eb697017472)

### PCSX2 Revision

1.7.5163

### Operating System

Windows 10 (64bit)

### CPU

i5-6500

### GPU

GTX 1060 6GB

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/110075513/51fe4bc8-49ed-4871-a08c-cc951c02ed6a)
![image](https://github.com/PCSX2/pcsx2/assets/110075513/705af669-290e-42d1-818d-56e9e7d8c9d2)

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/110075513/eaccece9-6e1a-4fb7-b51d-9466c46779aa)

### GS Window Screenshots

![latest5163](https://github.com/PCSX2/pcsx2/assets/110075513/6f6f145a-11a9-4abd-ae1e-6971e6956af2)

### Logs & Dumps

[Ratchet - Deadlocked_SCUS-97465_20231029013402.gs.zip](https://github.com/PCSX2/pcsx2/files/13197254/Ratchet.-.Deadlocked_SCUS-97465_20231029013402.gs.zip)

**Comment by stenzek** [comment]
Can you bisect it to an exact build? 4425 is over 1,000 commits away from current master.

**Comment by Bubblegum3390** [comment]
I have found the issue began on 1.7.5061. It does not happen on 5060 or older.

**Comment by lightningterror** [comment]
Regression from https://github.com/PCSX2/pcsx2/pull/10023 then.

**Comment by refractionpcsx2** [comment]
darn, oh well at least software is broken too, makes it easier to find out why.
