### ISSUE TITLE
[Feature Request]: Display Achievements (From RetroAchievements)

### ISSUE THREAD

**Issue by ben132** [PCSX2/pcsx2#10208]
### Description

This is a request to have the Achievements available, and completed, if logged into Retro Achievements.

### Reason

I have had a small issue on figuring out what games have achivements, especially with the PAL games.

### Examples

It could be another column displaying the total completed achievements percentage, or completed out of total achievements, yet again if logged into RA.

**Comment by refractionpcsx2** [comment]
We only request the list of achievements when you load the game.  Apart from it being slow to load the list for everything (some people have quite a few games), it's very unfair on the RetroAchievements people as it'll put a bunch of load on their server, for a couple of people who care, it's not really feasible.

**Comment by ben132** [comment]
I would be useful maybe if when you open the game it stores it in a cache, then displays it, only updating the achievements, if new ones are added, when the game is relaunched.

**Comment by RedDevilus** [comment]
Similar to how steam does a progress bar with for example 5 (completed) / 132 (all unlockable achievements) and when you click on it you see when you achieve what? The easier method would just be going through RetroAchievements or download the whole file and have it stored locally as you suggest.

But I'm not sure how much strain all these different methods will cause vs just a token and the new logging push system.

**Comment by ben132** [comment]
I cannot imagine that it would have much if at all strain as it load the data when the game is launched anyway, in fact I can imagine it maybe faster, negligible so, as it would have the majority of the data already downloaded, icons, percentages, names etc.  Also you could have "Offline" Achievements and "Online" Achievements.

But I maybe wrong.

**Comment by refractionpcsx2** [comment]
I'm thinking wider than you, we have tens of thousands of people playing PCSX2 in a given period, all of them will be spamming the Retro Achievement servers.

**Comment by ben132** [comment]
It mainly that I cannot see specifically if my version of the game has achievements, but that is a suggestion for RA, not PCSX2.  So I will make a suggestion relating to that in there forum.

**Comment by refractionpcsx2** [comment]
if it says there's no achievements when you run it, then there isn't any. You will find most of the games with them are NTSC versions, but yeah it could be clearer on the site.

If you would like them, you will need to request it with them too.

**Comment by refractionpcsx2** [comment]
But if a game has achievements is constantly changing, and sets could be removed, I don't really want two sources of truth.

**Comment by RedDevilus** [comment]
There is another issue there are the main sets and the other type being subsets which have different behaviour as well. Not sure why they exist but it's another level of complexity.

**Comment by Valtekken** [comment]
> There is another issue there are the main sets and the other type being subsets which have different behaviour as well. Not sure why they exist but it's another level of complexity.

Based on what I've seen, some subsets are for "challenge" variants of achievements. Something like speedrun achievements, no death run achievements, etc.
In all likelihood though, something like what the user was requesting was just for the base achievement sets

**Comment by stenzek** [comment]
The achievement set is not meant to be cached in any way. Sorry.

**Comment by stenzek** [comment]
Probably should be more clear about why:
1. We use [rc_client](https://github.com/RetroAchievements/rcheevos/) as the achievements backend now, which abstracts all the game identification/server lookups/etc (we just handle the hashing). So such a request would have to be made there as well, before we could implement it.
2. Getting unlock information requires a `start_session` API call, and this currently has performance issues on RAWeb. Some users actually report timeouts when starting games. They're working on it, but we would **not** want to spam the server with such expensive calls.
