### ISSUE TITLE
[Feature Request]: MechaPwn console information support

### ISSUE THREAD

**Issue by ab310714gz4700** [PCSX2/pcsx2#10213]
### Description

Same as real hardware

### Reason

Console info is not correct

### Examples

none

**Comment by F0bes** [comment]
Can you further explain this request?

**Comment by refractionpcsx2** [comment]
if you mean the model number isn't correct, that means your BIOS dump is incomplete, as that's stored in the NVM and displays properly on a good dump

![image](https://github.com/PCSX2/pcsx2/assets/6278726/1cbe8b5d-7247-41b6-bff0-dd65d035bbbc)

**Comment by F0bes** [comment]
I don't know about you but I can't read minds.
"Console information is not correct" doesn't mean much to anyone but you.
