### ISSUE TITLE
Clang and others unused variable warning

### ISSUE THREAD

**Issue by willkuer** [PCSX2/pcsx2#1021]
Clang shows a lot of unused parameters (-Wunused-parameter ~ 2800). This spams the output and possibly is also not nice to have in production code. Is there interest to tackle this?

If yes, what would be the preferred way?

1. casting unused variables to void
    ```
    #define Unused(var) ((void)var)
    ```

2. Omiting variable name in function definition
    ```
    void function(type1 used, type2 unused)
    ```
    to
    ```
    void function(type1 used, type2 /*unused*/)
    ```

3. Removing variable from function definition and possibly adjust all caller
    ```
    void function(type1 used, type2 unused)
    ```
    to
    ```
    void function(type1 used)
    ```

**Comment by gregory38** [comment]
3 is not possible. Those warnings are often related due to "top" virtual function which are empty. However the "bottom" function aren't.

Otherwise there is also option 4. Just disable the warning.

**Comment by willkuer** [comment]
Disabling the warning would produce less git noise then all of the other options and would probably require less time and effort. The question is just if this warning should be considered as important or not.

**Comment by gregory38** [comment]
In theory, useless param impact perf but
* core spend 80% of the time in recomp (no function)
* often called  functions are better inlined
* future (64 bits) will use register (perf impact will be even lower)
So I'm favor to remove this useless warning

**Comment by gregory38** [comment]
```
Is there interest to tackle this?
```
Build compilation is too slow so I don't use it. But yeah, it would be cool to have a readable log. I spotted a bad warning: virtual table of the object that is overwritten on wx stuff ( @turtleli did you see it?). Otherwise +90% of the warnings are just noise.

**Comment by turtleli** [comment]
I'm sure I saw that warning, but I must have forgot about it. It probably does need fixed. The warning about shifting negative numbers in yuv2rgb.cpp needs looked into as well.

On the unused warnings - Perhaps disabling the warnings for GSdx would work? That's where most of the warnings are coming from, the main culprits being GSDevice.h (~1700) and GSLocalMemory.h (~400). IMO some of the empty virtual functions in the GSDevice class could probably be made abstract as well.

**Comment by gregory38** [comment]
By abstract you mean pure virtual (=0) ?

**Comment by turtleli** [comment]
Yes, pure virtual.

**Comment by gregory38** [comment]
What is the status ?

**Comment by willkuer** [comment]
Obviously turtleli changed the behavior. We have now 6 unused warnings but those are unused local variable or unused result. I would close this then.


Interestingly we have two more warnings in x64 of type Wunused-but-set-variable.
