### ISSUE TITLE
[BUG]: Analog Trigger sensitivity is too high(?)

### ISSUE THREAD

**Issue by ZippyZolton** [PCSX2/pcsx2#10217]
### Describe the Bug

Hey, I would like to apologise in advance because I'm not sure how far spread this issue is, I don't have the time to test thoroughly at the moment but this has been something bothering me enough to start an issue to see if this is something that anyone else experiences. I currently use a DualSense and have been playing Enthusia Racing, with accelerate and braking (in-game) mapped to L2 and R2 since I knew they were pressure sensitive on OH. For some reason, they seem to register at 100% force at less than half the travel, here is a video to demonstrate;
https://github.com/PCSX2/pcsx2/assets/28773304/eb70f08a-0649-45c3-b470-4a23883fc616
I would like further insight to know if this is an issue caused by the game or the SDL compatibility. One feature that I think could mitigate this is allowing to set the sensitivity of analog triggers, so that this could be prevented no matter what controller and game you're playing on.

### Reproduction Steps

Play Enthusia Racing and other similar titles with R2 and L2 mapped to Accelerate and Brake respectively

### Expected Behavior

Triggers should be much less sensitive than they actually are

### PCSX2 Revision

v1.7.5176

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
This is not a bug. PCSX2 doesn't scale controller inputs, because every controller is different.

Adjust the sensitivity, either for both triggers in settings, or per-bind by shift-clicking it.

**Comment by ZippyZolton** [comment]
I was not aware shift-clicking would access options as that's not a common enough thing for me to consider, sorry.
