### ISSUE TITLE
[BUG]: Xbox Controller LB acting like D-Pad down when trying to Map

### ISSUE THREAD

**Issue by nick71223** [PCSX2/pcsx2#10220]
### Describe the Bug

When i try to map my xbox controller every single button works perfectly fine except for LB and D-Pad down

for some reason Pcsx2 sees them as the exact same button

using an external controller tester shows that the buttons perform normally outside of pcsx2

### Reproduction Steps

Press LB when mapping L1

### Expected Behavior

it should see it as LB

### PCSX2 Revision

v1.7.5178

### Operating System

Windows 11

**Comment by stenzek** [comment]
This is likely a support issue, not a bug. Please use the Discord server or forums.
