### ISSUE TITLE
Allow custom location for save state folders

### ISSUE THREAD

**Issue by njradford** [PCSX2/pcsx2#1022]
Allow users to designate a location for the save state folder, similar to the memory card issues, so that they can be externalized to a different location on the OS. The most useful application of this would be allowing services such as Drive and Dropbox to push the newest versions of the save states to the user's server.

**Comment by turtleli** [comment]
Plugin/BIOS Selector -> Folders lets you change the save state location. Does that not work?

**Comment by njradford** [comment]
Ah. My bad this can be closed.
