### ISSUE TITLE
[Feature Request]: Code Injection

### ISSUE THREAD

**Issue by ben132** [PCSX2/pcsx2#10223]
### Description

This maybe possible but I cannot see anything specific.  
My request is to be able to inject code into a game, similar to a rom hack, to be able to add new content to an old game, ie Mods.

### Reason

To be able to enhance, a game with new maps, weapons and so on.  As happens with pc games making the games feel new and interesting years after.

### Examples

There are no examples other that pc mods, maybe Cheat Engine, and [Racman for Ratchet and Clank](https://github.com/MichaelRelaxen/racman).

**Comment by refractionpcsx2** [comment]
Really outside of the scope of the emulator, those should be done externally.

You can create patches if you need to modify values in the game.
