### ISSUE TITLE
[Feature Request]: Option to Mute While Fastfowarding

### ISSUE THREAD

**Issue by Maelstrom1** [PCSX2/pcsx2#10234]
### Description

Duckstation has a nice little box (now a slider) you can check/move to mute all game audio whenever you turn on fastforward. 

### Reason

should (hopefully) be pretty easy to implement and id much rather be listening to nothing at all than garbled audio

### Examples

in duckstation:
![image](https://github.com/PCSX2/pcsx2/assets/20371049/469a7246-ff79-4f65-80e9-232db9e167be)

**Comment by refractionpcsx2** [comment]
you can just map the fast forward button to the mute button at the same time, then when you toggle it, it will also toggle mute.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/9906fe6a-ce14-4722-b7bf-b9133663992c)

**Comment by Maelstrom1** [comment]
gdi i guess that works
