### ISSUE TITLE
[BUG]: HDMI resolution conflict

### ISSUE THREAD

**Issue by Zengurasu** [PCSX2/pcsx2#10236]
### Describe the Bug

When the game is played using a HDMI TV resolution, the native resolution is not showing in game.

The system does not downgrade the graphics and sustain the HDMI resolution.

### Reproduction Steps

Thats all.

### Expected Behavior

I expected a downgrade, because the HDMI resolution can stuttering for low end pcs.

### PCSX2 Revision

v.1.7.5186

### Operating System

Windows 11

### CPU

Intel Celeron 6305

### GPU

UHD Graphics

**Comment by Mrlinkwii** [comment]
I'm confused what you mean ,can you explain further what you mean ?        what your describing probably isn't a PCSX2 problem

**Comment by stenzek** [comment]
If you mean the resolution should match the game, then no, we can't make your GPU output PAL/NTSC.

Besides, we crop overscan by default, and don't emulate the analog signal (only the timing).

> Intel Celeron 6305

This is the reason it's slow, not the resolution. 2 cores at 1.8GHz is **not** enough to emulate PS2. Minimum 3, and higher clock.

**Comment by Zengurasu** [comment]
> If you mean the resolution should match the game, then no, we can't make your GPU output PAL/NTSC.
> 
> Besides, we crop overscan by default, and don't emulate the analog signal (only the timing).
> 
> > Intel Celeron 6305
> 
> This is the reason it's slow, not the resolution. 2 cores at 1.8GHz is **not** enough to emulate PS2. Minimum 3, and higher clock.

Well, actually this core works fine.

When you play games without using a HDMI cable, you can run around 99% of the games.

Just Shadow of the Colossus had a few problems, but runs ok too. And even more, this 99% is working fine with using a native 4GB ram.

What I trying to say is:

The native resolution on the "Graphics settings" is totally workable, when you run without a HDMI cable.

But, If you use the HDMI cable, this "native resolution" is not readable, because the system forces to a HDMI resolution.

To make things more clear, lets imagine:

The PS2 console originally works for PAL and NTSC resolution thats equal of the "native graphic settings" on the PCSX2. If you try use a HDMI cable on the original PS2, the games can still running, but is not your native function do this.

So for emulation purposes:

I already saw this downgrade happening before, but for old emulators like Sega Genesis and Super Nintendo.

I know, you gonna say:

"Its because the 3D system is upscalable"

But in fact, we could have a software device that locks and sustain the native resolution, even If you use a HDMI.

**Comment by Zengurasu** [comment]
If you guys can't solve, I understand.

But maybe is time to rethink about the minimum requirements.

As I said before, this Intel Celeron 6305 is running 99% of the games perfectly, using only 4GB ram.
