### ISSUE TITLE
[Feature Request]: Game list selectable by controller.

### ISSUE THREAD

**Issue by Zengurasu** [PCSX2/pcsx2#10239]
### Description

I think that would be cool If the game list could be selectable by controller.

Like the raspberry emulator systems.

### Reason

Just for practicality.

### Examples

Raspberry emulator system.

**Comment by RedPanda4552** [comment]
Use Big Picture mode.

Please stop using GitHub for support issues. The issue template clearly asks you to use Discord or the forums. GitHub is for technical issues only.
