### ISSUE TITLE
[Feature Request]: AARCH64 (ARM) support?

### ISSUE THREAD

**Issue by LAP87** [PCSX2/pcsx2#10235]
### Description

I (and many others) would like to see this awesome emulator be available for use on the myriad of new high-performance single board computers (SBC's) that have come out!
Is this feasible within the pcsx2 development team or is this more of something "someone else has to build from the ground up"? 

Love you guys, keep on rocking!

### Reason

It makes it possible to bring my ps2 with me at the cost of a few grams, using desktop x86 linux / windows isn't very easily done with the SBC's. 

### Examples

Batocera, Retropie and others based on the work of libretro have aarch64/arm64 clients that all come prepackaged with emulators, all but one glaring omission.

**Comment by stenzek** [comment]
Gosh no, times 1000. Why on earth would we want to do anything to assist those examples, which are nothing but commercialized knockoffs of others work, license violation (shitretro), and blatant piracy?

Combined with the fact that the majority of those boards are **not** powerful enough to emulate PS2. Only RK3588 comes close.

And do you have any idea how much work this actually is? What I developed a few years back took months of evening/weekends worth of time to develop, let alone debug/fix all the randomly broken games. It's not something you just casually do with a feature request, or change some compilation parameters. We're talking tens of thousands of lines of code.

PCSX2 will get support for Apple Silicon in the next few months (see https://github.com/PCSX2/pcsx2/issues/10042#issuecomment-1739674394), and thus Linux on Apple Silicon as well. But not SBCs (they don't even have desktop GL drivers, let alone Vulkan).

**Comment by guest9232** [comment]
@stenzek why don't you tell us how you really feel

**Comment by TailsFanLOL** [comment]
> PCSX2 will get support for Apple Silicon in the next few months (see https://github.com/PCSX2/pcsx2/issues/10042#issuecomment-1739674394), and thus Linux on Apple Silicon as well.

If you don't want to implement other ARM platforms, what makes Apple Silicon different?
Also, I have no idea what the code looks like, but how long would it take to make it architecture agnostic?

**Comment by TheLastRar** [comment]
> > PCSX2 will get support for Apple Silicon in the next few months (see [#10042 (comment)](https://github.com/PCSX2/pcsx2/issues/10042#issuecomment-1739674394)), and thus Linux on Apple Silicon as well.
> 
> If you don't want to implement other ARM platforms, what makes Apple Silicon different? Also, I have no idea what the code looks like, but how long would it take to make it architecture agnostic?

They are no longer contributing to the project, another (new?) developer would have to come in for any work on this to be done.

**Comment by aenertia** [comment]
I would add the sm8250 (which has full mesa/mainline support) - of which a growing number of devices are incorporating, to the list of targets. That and the Snapdragon Elite Laptops.

**Comment by TailsFanLOL** [comment]
> I would add the sm8250 (which has full mesa/mainline support) - of which a growing number of devices are incorporating, to the list of targets. That and the Snapdragon Elite Laptops.

And high end RockChip and Nvidia Tegra... And at this point it's just easier to implement a generic armv8.x instruction set.

**Comment by retropieuser** [comment]
> > I would add the sm8250 (which has full mesa/mainline support) - of which a growing number of devices are incorporating, to the list of targets. That and the Snapdragon Elite Laptops.
> 
> And high end RockChip and Nvidia Tegra... And at this point it's just easier to implement a generic armv8.x instruction set.

Especially as more & more viable setups are arm based over x64 machines. At that point I imagine the discussion would be different
