### ISSUE TITLE
[BUG]: GOD OF WAR 2 HUD BUG

### ISSUE THREAD

**Issue by Isaac0liveira** [PCSX2/pcsx2#10238]
### Describe the Bug

The game runs normally until Kratos faces Zeus for the first time
![image](https://github.com/PCSX2/pcsx2/assets/61355645/9f868a65-0ff2-4109-a15a-72841bb980ee)

ALSO: The fullscreen at Windows 11 don't hide the toolbar.
Nightly v1.7.5186

### Reproduction Steps

Only launched the game and played until face Zeus for the first time.

### Expected Behavior

HUD being black.

### PCSX2 Revision

Nightly v1.7.5186

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Seeing this a lot recently.

I suggest you rip your copy of the game properly, I suspect a lot of people are pirating a bad copy and blaming us.  Verify your ISO, you'll probably find it's broken, rerip your disc.

If you still have problems, please visit the discord.

**Comment by Isaac0liveira** [comment]
But i also tested it in previous builds, and it worked. So, i'm just here to report the bug, not to blame you guys or something like this, just try to look if is something that have to be corrected to make the further versions even better than actuals.

**Comment by refractionpcsx2** [comment]
I mean if you can prove your iso isn't broken, you aren't using savestates and it's still broken, I will happily take it as more than just a support issue.

**Comment by stenzek** [comment]
Bad pirate dumps not working isn't our problem. Dump game from disc again, use the verifier in game properties to check it, then we can investigate.

"It worked in previous builds" is meaningless unless you can quantify it with the build number where it broke.
