### ISSUE TITLE
[BUG]: WWE Smackdown Shut Your Mouth hanging from IPU problems

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#10232]
### Describe the Bug

regression from #9951 this commit specifically https://github.com/PCSX2/pcsx2/pull/9951/commits/3157f1aac6019b71716e6fcd4462c9a96914f9e6

### Reproduction Steps

try starting a game as Steve Austin, it'll hang during his intro.

### Expected Behavior

not hanging

### PCSX2 Revision

v1.7.5023+

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5900X

### GPU

RTX 2080Ti

**Comment by GitHub-Khi** [comment]
I discovered this patch once and it helps temporarily (at least for me). :D

**Comment by refractionpcsx2** [comment]
Thanks but I don't really want to patch it, I'd rather fix it 📦 
I guess other people can use that for now, if they want.

**Comment by GitHub-Khi** [comment]
It is nice that now it seems to be the turn of the WWE games. There is a lot to fix in certain games. But okay, enough with my comment if it does not contribute to the problem. Good luck anyway! :)

**Comment by refractionpcsx2** [comment]
I mean, it was working, I broke it :P
