### ISSUE TITLE
[BUG]: Jonny Moseley Mad Trix - Alpha issues caused by internal anti-aliasing

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#10258]
### Describe the Bug

This one is a bit of a long story, but it's worth it.  In issue #6636 I made mention of an issue where some graphics that are supposesd to have transparent borders have either incorrectly-colored or even pink outlines, such as the some menu graphics seen here:

![17menupinkoutlines](https://github.com/PCSX2/pcsx2/assets/58268914/d3371f1e-1b46-4646-aae5-ba4e52581d3a)

as well as the crowd texture in the stands which could either have a pink or incorrectly-colored outline.  This was brushed off in that issue as "The crowd issue is just something that happens if you upscale or use Anisotropic Filtering, not a bug, but a restriction in upscaling."  However, that may not be the case.

A few months ago, an early development prototype of the game was found. Now, I know mentioning a dev prototype in an issue isn't the best idea (and why I've been fearing opening this issue for over a month), however this actually led me to the real problem behind the pink/colored artifacting - it's NOT upscaling related, it's anti-aliasing related.

If you boot up this build and reach its main menu:

![17](https://github.com/PCSX2/pcsx2/assets/58268914/e92a4432-8197-400f-a27f-2430bd90eda9)

all the parts that are supposed to be transparent are filled with that same pink.  Like before, this pink does NOT go away in software rendering and it does NOT exist when run on a real PS2.  Now, if we go over to 1.6.0 stable and use the OpenGL renderer:

![160ogl](https://github.com/PCSX2/pcsx2/assets/58268914/4ef64c7e-fe6a-4fda-a16b-a01e359bbcdf)

Issue completely fixed.  If you use 1.6.0's software renderer, it'll still have the pink:

![160software](https://github.com/PCSX2/pcsx2/assets/58268914/8cd046e1-e34b-4633-b736-2a45227c472f)

The reason the title of this issue has "internal anti-aliasing" in it is because if you use 1.6.0's software renderer, but disable the "Edge Anti-Aliasing" option:

![160softwarenoaa](https://github.com/PCSX2/pcsx2/assets/58268914/a11416e6-0259-4cf5-a0c7-de4b7baeb019)

It's fixed once more.  With this in mind, I went back to the retail release, still on 1.6.0, and tried both the OpenGL renderer and Software renderer with Edge Anti-Aliasing disabled.  Sure enough, in both cases, the pink outlines on these menu graphics were fixed:

![nopink](https://github.com/PCSX2/pcsx2/assets/58268914/7c721e3f-dae8-44a3-af60-edffcc71612a)

and the crowd did not have a weirdly-colored outline.

Unfortunately, on latest 1.7, the above fixes don't work.  OpenGL renderer still has pink in all of the above cases, and disabling Software renderer's anti-aliasing option also no longer fixes it.  Therefore, I'm convinced the issue is actually related to something anti-aliasing related internally.  I pray this complex issue can be fixed.

### Reproduction Steps

Boot up the game on 1.7 using any renderer and any settings.  Some 2D graphics will have outlines that are either pink or incorrectly-colored.

Boot up the game on 1.6.0 stable using either OpenGL Hardware or Software with "Edge Anti-Aliasing" disabled.  All 2D graphics will render properly.

### Expected Behavior

All 2D graphics should be rendered without any garbage/corrupted outlines or pink.

### PCSX2 Revision

v1.7.5198

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 SUPER

**Comment by Mrlinkwii** [comment]
can i have a gs dump :)

**Comment by SlyCooperReloadCoded** [comment]
1.7 GS dump with the pink outlined menu graphics on-screen:
[Jonny Moseley Mad Trix_SLES-50619_20231109155640.zip](https://github.com/PCSX2/pcsx2/files/13312750/Jonny.Moseley.Mad.Trix_SLES-50619_20231109155640.zip)

Should I get a 1.6.0 GS dump on the same screen?

**Comment by refractionpcsx2** [comment]
No, it doesn't matter, 1.7 is fine

**Comment by SlyCooperReloadCoded** [comment]
I hope the inclusion of testing of a dev build of the game doesn't make people not take it as seriously.  I feared opening this at all for over a month because I've had a similar experience in the past.  A real issue tossed to the wayside because "dev build used, unpredictable results" but I think I'm on the mark with this one.

Also, while getting that gs dump, I noticed even more transparent parts of textures that are pink on 1.7 but not on 1.6.0 with the test settings.  Definitely the same issue.

**Comment by refractionpcsx2** [comment]
I'd rather you tested on the latest dev build, I don't really care how it worked 4 years ago, the problem is now and a lot of things have changed since then.

**Comment by SlyCooperReloadCoded** [comment]
No, I meant the game itself.  A dev build of the game.  The settings that fixed that inevitably fixed retail, but I was still a little worried.

**Comment by refractionpcsx2** [comment]
Does this happen in the final version of the game? I'd be more interested in that, we don't support prototypes.

**Comment by SlyCooperReloadCoded** [comment]
Yes it does.  The screenshots with text in them, the course names, those are retail.  The big pink boxes, those are the prototype.  However, they're both transparency issues and the settings that fixed the big pink boxes in the prototype also fixed the incorrect pink rendering in retail copies.

**Comment by refractionpcsx2** [comment]
If it's broken in the final version then I'm interested in fixing it.

**Comment by SlyCooperReloadCoded** [comment]
Fair enough.

**Comment by refractionpcsx2** [comment]
Setting the texture filtering to nearest also seems to clear it up, so I wonder if there's a bad interaction with Bilinear and AA.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/ecf0e0d8-18a7-4a0f-b5f9-75cdc120e6c8)

Does Nearest filtering clean up the other scene too where it goes nuts?

**Comment by SlyCooperReloadCoded** [comment]
Nope.  I did find that Nearest filtering trick too, it helps with 1.6.0 OpenGL, I used it for my screenshots.  However, with 1.7, it doesn't matter if it's Bilinear or Nearest, OpenGL or Software, it's still very pink in that scene.  1.6.0 tests show it's likely still an AA issue:

1.6.0 OpenGL Bilinear:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/b50d13fc-8eda-4923-b8f2-5bb36aa42cd0)

1.6.0 Software Bilinear:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/413ed521-d079-4c35-96d2-97289cd94379)

1.6.0 OpenGL Nearest:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/b2d0c3b5-df01-42ac-9b8b-00f753d286bc)

1.6.0 Software Nearest:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/f704de84-67b0-42fa-85a9-7068ef5188fc)

1.6.0 Software Bilinear w/AA Disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/77b704d1-700f-4593-aa89-78e039d8d036)

1.6.0 Software Nearest w/AA Disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/508e163f-fbe8-497b-b8aa-322b8e3d13bf)

**Comment by refractionpcsx2** [comment]
okay, well it looks like the reason I'm getting pink edges is from the bilinear, and the texture looks like this

![00031_f5000_itex0_0307c_P_8](https://github.com/PCSX2/pcsx2/assets/6278726/532ee71a-5caf-40c8-bf2d-76471f83c39a)

and it uses an alpha test to kill the bits you shouldn't be able to see.  Anti Aliasing isn't enabled for these draws, so I wonder if the alpha test affects bilinear filtering as well, that'd be annoying in hardware.

**Comment by SlyCooperReloadCoded** [comment]
All renderers and filtering options tend to look like this in 1.7:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/111fe53d-a637-4e13-ba3f-31e32a5277fe)

Additionally, something else I should mention, trees in this menu scene in both retail copies and the prototype have pink in their transparent parts, nether of which are present on real hardware:

Retail:
![Capture2](https://github.com/PCSX2/pcsx2/assets/58268914/890a2e9b-0ddf-4287-a413-deb76252b037)

Prototype (a lot more obvious here, and Nearest is used here):
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/bec8b6e0-a8ee-4f2a-8690-451d3cffaff6)

**Comment by refractionpcsx2** [comment]
Well this is either a core bug, or just how the game is

this is the GS dump running on my PS2

![image](https://github.com/PCSX2/pcsx2/assets/6278726/cccc77cc-22dd-4ed6-afa2-3bb6a32ee163)

**Comment by SlyCooperReloadCoded** [comment]
That's odd.  There's a real PS2 playthrough online that doesn't have that, that's how I know it doesn't affect real hardware.

**Comment by SlyCooperReloadCoded** [comment]
Also there were some updates in the 1.5.0-1.6.0 time where lots of pink was added in places it shouldn't be, like the crowd.  That used to always be pink, but that's never pink on retail.

**Comment by refractionpcsx2** [comment]
I loaded up the actual game, it has pink.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/0cf6dd94-8aa3-4abe-99a4-3dc5ab395f4d)

**Comment by SlyCooperReloadCoded** [comment]
I don't know if you're able to load a GS dump without the game build itself, but if you can, here's a dump on that screen with lots of pink:
[Jonny Moseley Mad Trix (Europe) (Pre-Alpha)_ABCD-12345_20231109164332.zip](https://github.com/PCSX2/pcsx2/files/13313083/Jonny.Moseley.Mad.Trix.Europe.Pre-Alpha._ABCD-12345_20231109164332.zip)

**Comment by refractionpcsx2** [comment]
If you want to remove the pink, you will need to patch the game.

**Comment by SlyCooperReloadCoded** [comment]
Are you able to load the GS dump I just sent or do you need to have the build on hand?  Just to get some closure on that, even if there isn't going to be a fix for it.

**Comment by refractionpcsx2** [comment]
Here, your game is broken at that point in time.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/467f5564-2c16-4d62-a25a-8a376454f7fb)

**Comment by SlyCooperReloadCoded** [comment]
Fascinating.  I'm assuming whatever 1.6.0 was doing couldn't be brought over without affecting anything else.  I would just use 1.6.0 but it's one of the few titles that suffered from controls bugs and it's unplayable there.  Alright, this has been enlightening.

**Comment by refractionpcsx2** [comment]
I'm not bringing over the wrong behaviour, no. We're not trying to be a broken emulator for the sake of broken games, we want to be authentic to the console. I'm loathed to add broken options to make a prototype which was already broken by design work.  I would suggest you use the old version if you want that behaviour.

**Comment by SlyCooperReloadCoded** [comment]
The reason I ask is because this is what that texture looks like.  Your earlier explanation of the game killing the pink bits doesn't make sense because there's no pink here.

![3bb5b7a9e05655d7-e1d47e8f4eeafa7b-000061d3](https://github.com/PCSX2/pcsx2/assets/58268914/b2951752-de31-4731-83b6-1815b7c79475)

**Comment by SlyCooperReloadCoded** [comment]
Some textures are actually pink in the transparent parts:
![bea648ff81d396bc-57e2ba51f4b78270-00005dd3](https://github.com/PCSX2/pcsx2/assets/58268914/33a0d29f-3712-41a4-a4c7-a3a825849867)

**Comment by refractionpcsx2** [comment]
Dunno where you got those, but these are the textures.

![00036_f5000_itex0_0319c_P_8](https://github.com/PCSX2/pcsx2/assets/6278726/4ec2b35f-9f95-4815-9133-adba005ae642)
![00038_f5000_itex0_0332c_P_8](https://github.com/PCSX2/pcsx2/assets/6278726/66b8f879-1acc-4bf8-a167-4b04ae5a65c5)

**Comment by SlyCooperReloadCoded** [comment]
Odd, I got them from the texture dumping feature.  Alright, I'm done, internal texture modding for this game will happen eventually.

**Comment by refractionpcsx2** [comment]
if it's any help, the problem is the very top colour of the palette is where the pink is coming from.

![00036_f5000_itexp_02820_C_32](https://github.com/PCSX2/pcsx2/assets/6278726/7db3a009-cef5-429d-9b50-75087427b8b8)

But yeah, nothing we can do about it, custom textures are your saviour.

**Comment by SlyCooperReloadCoded** [comment]
Something to note is that if I use the texture replacement feature to replace the problematic textures with just a transparent square that I also got from a dumped game texture (no modification), I get this:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/42ea219b-ee88-4ac3-b4b2-68e5b66d1a14)

**Comment by refractionpcsx2** [comment]
you need to make sure your alpha channel is correct, it needs to have 128 over the top of the lines, and 0 everywhere else.

**Comment by SlyCooperReloadCoded** [comment]
This wasn't modified in any way, it's an actually transparent texture dumped from the game.  It works properly as a replacement in retail copies.  Something to add onto this, when I dump the texture for the outside trees in retail copies and then use that as a replacement texture for the pink trees in this build, the new texture applies, but it's still pink.  I think this is the game doing something weird.

**Comment by refractionpcsx2** [comment]
*shrug* I dunno, I'm just telling you how the game works :P it's doing alpha tests on the texture and only drawing anything with an alpha greater than zero

oh hah, of course, they aren't using alpha blending, but they are using Anti-Aliasing, so the alpha value for the whole texture is actually the "coverage" value, which is 128 for every pixel, so they pretty much screwed that up, you're not going to get a transparent texture, you're gonna have to either patch the game to disable AA, or cheese it and draw the background as part of your texture.
