### ISSUE TITLE
[feature request]: Game compatibility column

### ISSUE THREAD

**Issue by davidhedlund** [PCSX2/pcsx2#10256]
### Description

[Vita3K](https://github.com/Vita3K/Vita3K) has a "[Compat](https://vita3k.org/compatibility.html)" column for all OS builds. It would be useful to adopt this for PCSX2.

### Reason

* https://pcsx2.net/compat/ will change over time.
* People frequently forget to check the compatibility page.

### Examples

# Vita3K examples

## Vita3K for GNU/Linux

![image](https://github.com/cemu-project/Cemu/assets/6416073/391c9e00-38df-4466-82c3-c2c90da9ddda)

## [Vita3K for Android](https://github.com/Vita3K/Vita3K-Android)

![image](https://github.com/cemu-project/Cemu/assets/6416073/59f1b3a8-4638-40c2-8d54-eb6e8cc3c105)

**Comment by Mrlinkwii** [comment]
already exists
![image](https://github.com/PCSX2/pcsx2/assets/17685135/5ed6611d-bfe3-4f6d-9d59-1162718e8f75)
