### ISSUE TITLE
[Feature Request]: Enable default host filesystem path

### ISSUE THREAD

**Issue by Dnawrkshp** [PCSX2/pcsx2#10259]
### Description

I'm hoping to open up the discussion for a new setting for a "default host filesystem root path". When booting from any source other than an elf, the ``hostRoot`` will be set to this path. If HostFs is enabled, then all requests to access the host filesystem will resolve into the configured root path.

If the default host root path is configured to ``C:\Users\me\Documents\`` then ``host:content.txt`` would resolve to ``C:\Users\me\Documents\content.txt`` when booting an ISO with HostFs enabled.

### Reason

- How will it make things easier for you?

I host servers for R&C UYA and Ratchet: Deadlocked online multiplayer. We offer custom maps that our users can download and put onto their USB drive. For PCSX2, we provide a FAT32 format img file with all the custom maps preloaded. This has worked great for us for the past couple years. Thank you PCSX2 team for making it possible. But recently we released tools for members of our community to create and distribute their own custom maps for R&C UYA. With new maps coming from different sources, some in an unfinished WIP state, the preloaded FAT32 img we normally distribute for our PCSX2 users can no longer keep up. As we would have to require users to download the full FAT32 image every time even a single map is changed or added.

It would be incredibly helpful to our community if PCSX2 users had a way to load the maps on par with PS2 users (drag and drop files into a folder).

### Examples

Example of how the setting could look.

![image](https://github.com/PCSX2/pcsx2/assets/2020854/e3378c79-db21-4b87-93ff-1a736bcc780d)

**Comment by Dnawrkshp** [comment]
If this is reasonable I'm happy to create a PR for it.

**Comment by stenzek** [comment]
What's the problem with just putting the iso in its own directory with these files? It's unreasonable to have a niche option like this just for one game.

**Comment by Dnawrkshp** [comment]
Totally understand. Anything we could get to have it work would be appreciated. Having the host fs root be set to the directory of the iso would work perfect.

**Comment by Mrlinkwii** [comment]
implemented in  #10261
