### ISSUE TITLE
[Feature Request]: Disable cheats and patches when clicking Clear Settings button in Game Properties

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#10255]
### Description

Right now when clicking Clear Settings button in Game Properties cheats and patches are still ticked as enabled and indeed if you ckeck the game .ini file you can see that all settings are blank, while the patches and cheat section still show as enabled. 

Only manually disabling the cheats and patches works. 

I would like that clicking Clear Settings patches and cheats would be disabled too, it makes more sense, since patches and cheats modify the game emulation and can sometimes cause issues. 

### Reason

Easier and more reasonable way of resetting game properties. Less confusion. 

### Examples

Nothing to add. I think the description is already good enough as an example.

**Comment by Mrlinkwii** [comment]
fixed in #10530
