### ISSUE TITLE
[BUG]: Tony Hawk's Underground 2 FPS drops while seeing lens flare effect

### ISSUE THREAD

**Issue by thefakesound** [PCSX2/pcsx2#10267]
### Describe the Bug

All other times game runs perfectly fast but when camera turns to the sun, FPS significantly drops
I remember when lens flare effect was totally absent in hardware mode, but a few month ago (I guess), lens flare was added and game has been running perfectly. But a few versions ago (doesn't really know when and what was changed), this glitch occurs and still present in every release

### Reproduction Steps

Just run Boston level (Unlocked from the start) for example and move camera to the sun

### Expected Behavior

Game to run without fps drops like it was before

### PCSX2 Revision

1.7.5200

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Steam Deck

### CPU

Zen 2

### GPU

RDNA 2

**Comment by refractionpcsx2** [comment]
Speed isn't really a bug.  The most likely thing is it's doing hardware readbacks to do the sun effect.

you could try disabling them under the Per Game Settings->Graphics->Advanced and also try the "Spin" options at the bottom of Settings->Graphics->Rendering.

This will probably make the sun disappear again, but that's your choices. if you need further help please visit out discord

**Comment by thefakesound** [comment]
I'm sorry for commenting, but I decided to create an issue entry exactly because there was releases when sun and lens flare was presented and no speed was affected. So I thought maybe this is a small bug someone didn't notice and could be easy to fix.
Thanks for answer

**Comment by refractionpcsx2** [comment]
If you truly think it's a bug, please come to the discord and we can look at it and decide if it's a regression or something else going on.
