### ISSUE TITLE
[BUG]: Burnout 3 FPS drops a bit right before crash

### ISSUE THREAD

**Issue by thefakesound** [PCSX2/pcsx2#10268]
### Describe the Bug

Right before crash player's car FPS drops a bit or microfreeze happens
Strange thing that Both Mac and Linux (Steam deck) version of PCSX2 has this issue while both aetherSX2 Mac and Android version hasn't

### Reproduction Steps

Just run any race and crash player's car into opponent

### Expected Behavior

To run without microfreezes like AetherSX2

### PCSX2 Revision

1.7.5200

### Operating System

macOS 13 (Ventura)

### CPU

M1

### GPU

M1

**Comment by stenzek** [comment]
This is because it's double jitting. Won't be fixed until I finish PCSX2's Apple Silicon dynarecs.

See https://github.com/PCSX2/pcsx2/issues/10042#issuecomment-1739674394

**Comment by thefakesound** [comment]
Wow, would be great to have native arm version eventually.
But strange thing that this microfreeze in burnout occurs in linux version on steam deck too

**Comment by stenzek** [comment]
We don't support steam deck,  they use modified configurations.
It's also a mobile device, which means lower clock speeds will make it more susceptible to spikes when VU programs are compiled.
This is *not* a bug
