### ISSUE TITLE
[Feature Request]: Debugger Memory Search - Search Values Greater than, Lesser than, or not equal

### ISSUE THREAD

**Issue by Daniel-McCarthy** [PCSX2/pcsx2#10266]
### Description

The debugger's Memory Search functionality can be expanded to allow more search options other than direct == checks.
I propose for numeric values (non-string, non-array) we add the ability to search for values greater than the given input value, less than the input value, or not equal to the input value.

This would give the user more ways to find particular memory addresses they are searching for. This would make things significantly easier for those making patches for games as well.

A dropdown can be included below the search bar that defaults to Equality ==, but can be changed to >, <, or !=.

### Reason

Currently the Debugger's Memory Search feature allows only direct equality checks. This is very helpful, however there are situations that are not possible to effectively cover with just == checks.

For example:
- Floating point numbers with remainder. While the current == check allows for a small window of tolerance to find a float value within a level of precision, it may be impossible to find a value if you do not know the exact remainder (e.g. 5.1 or 10.756). Allowing to search for values greater than 4, then [scan again](https://github.com/PCSX2/pcsx2/issues/9720) for values < 5 would allow you to find values in that ballpark.
- Values you don't know the precise number for. If a value changes and you know the initial value, you can find the initial value via a search, then with [next scan](https://github.com/PCSX2/pcsx2/issues/9720) filter to values that are _not_ that value anymore. Additionally, if you know a value is non-zero but are unsure of the exact value, != 0 is a useful search.

Among other use cases, this type of search functionality would make finding memory addresses significantly easier, particularly ones who's values change frequently or have non-obvious searchable values.

### Examples

Example of Search type dropdown from CE:
![image](https://github.com/PCSX2/pcsx2/assets/4957200/dc55b465-b39a-45ba-891e-1df2597d9d89)

**Comment by stenzek** [comment]
Can also use DuckStation's as a reference:
<img width="787" alt="image" src="https://github.com/PCSX2/pcsx2/assets/11288319/5fd30b68-1896-4dca-8215-d95579804582">

**Comment by Daniel-McCarthy** [comment]
Excellent, looks great and has more options that I hadn't suggested. Thanks for the share!

Also as a side note, I'm interested in implementing this feature. I have created an issue to track it, and want to work on it once #10260 is done as it will impact this area of the code base.

**Comment by stenzek** [comment]
Feel free to grab any useful code from DS, relevant parts are mostly around here:
<https://github.com/stenzek/duckstation/blob/d141692df3f2da7dea12ae902637f97d777e9552/src/core/cheats.h#L202-L277>
<https://github.com/stenzek/duckstation/blob/d141692df3f2da7dea12ae902637f97d777e9552/src/core/cheats.cpp#L2818-L3050>
<https://github.com/stenzek/duckstation/blob/d141692df3f2da7dea12ae902637f97d777e9552/src/duckstation-qt/cheatmanagerdialog.cpp#L883-L977>

Relicensing is fine, PCSX2 already contains plenty of DS code :-)

**Comment by Risae** [comment]
Shouldn't this be closed since https://github.com/PCSX2/pcsx2/pull/10441 has been merged?

**Comment by userse31** [comment]
I have a bit of experience using "GameGuardian" on my rooted phones to force myself out of bounds in Avelog's Mouse Simulator.

The unknown initial value thing was EXTREMELY useful!
