### ISSUE TITLE
[BUG]: SLES 53703 - SLUS 21311 King Kong, Peter Jackson's graphic artifacts vignette/green blur/white lines in rain

### ISSUE THREAD

**Issue by Nerboruto** [PCSX2/pcsx2#10263]
### Describe the Bug

problem occurs with both software/hardware modes at native or upscaled resolution
bad resolution?

green effect

![King Kong, Peter Jackson's - The Official Game of the Movie_SLES-53703_20231110151647](https://github.com/PCSX2/pcsx2/assets/10599012/4fc6636f-2261-4d21-bcae-054fb3474e41)

during rain it seems that size of screen area is wrong you see white lines, difficult to capture.

bad vignette colors
![King Kong, Peter Jackson's - The Official Game of the Movie_SLUS-21311_20231110154836](https://github.com/PCSX2/pcsx2/assets/10599012/93314ea2-bcc8-40ea-862c-c1693a1541ab)

rainbow lines

![King Kong, Peter Jackson's - The Official Game of the Movie_SLUS-21311_20231110155347](https://github.com/PCSX2/pcsx2/assets/10599012/9b629cd9-730b-47ba-9179-a11287ca839f)

white lines

![King Kong, Peter Jackson's - The Official Game of the Movie_SLES-53703_20231110190820](https://github.com/PCSX2/pcsx2/assets/10599012/ca27ebab-891e-4523-8469-414efebca212)

### Reproduction Steps

run game scene 1 and 2.

### Expected Behavior

no green, no white lines, strange colors vignette effect bug.

### PCSX2 Revision

v 1.7.5200

### Operating System

Windows 10 (64bit)

### Logs & Dumps

green blur gs dump 

[King Kong, Peter Jackson's - The Official Game of the Movie_SLES-53703_20231110151647.gs.zip](https://github.com/PCSX2/pcsx2/files/13320427/King.Kong.Peter.Jackson.s.-.The.Official.Game.of.the.Movie_SLES-53703_20231110151647.gs.zip)

bad vignette color 

[King Kong, Peter Jackson's - The Official Game of the Movie_SLUS-21311_20231110154836.gs.zip](https://github.com/PCSX2/pcsx2/files/13320566/King.Kong.Peter.Jackson.s.-.The.Official.Game.of.the.Movie_SLUS-21311_20231110154836.gs.zip)

rainbow lines

[King Kong, Peter Jackson's - The Official Game of the Movie_SLUS-21311_20231110155347.gs.zip](https://github.com/PCSX2/pcsx2/files/13320759/King.Kong.Peter.Jackson.s.-.The.Official.Game.of.the.Movie_SLUS-21311_20231110155347.gs.zip)

white lines

[King Kong, Peter Jackson's - The Official Game of the Movie_SLES-53703_20231110190820.gs.zip](https://github.com/PCSX2/pcsx2/files/13322163/King.Kong.Peter.Jackson.s.-.The.Official.Game.of.the.Movie_SLES-53703_20231110190820.gs.zip)

**Comment by Nerboruto** [comment]
> can i have a save state

It's at the beginning of the game. just start a game.

**Comment by Buzzardsoul** [comment]
Autoflush fixes issue number 1 and 3.

**Comment by Nerboruto** [comment]
> Autoflush fixes issue number 1.
> 
> Edit: nevermind, the green line is not supposed to be there at all.

autoflush_sw = true in my ini

**Comment by refractionpcsx2** [comment]
I recorded some videos off my PS2 for you


https://github.com/PCSX2/pcsx2/assets/6278726/96a7aba4-a102-4fc8-a10f-4049a2da4666

In this one look on the right hand side at both the part with the girl and looking in to the air.
https://github.com/PCSX2/pcsx2/assets/6278726/ef5a725b-a0b3-4664-b010-3189ec0997b4


https://github.com/PCSX2/pcsx2/assets/6278726/00d8a7fe-e28c-45f7-8112-9503356a8e4a

Software seems to pretty much match the game's jankiness, you can fix up hw with a few hw fixes to make it match as close as possible

**Comment by Nerboruto** [comment]
Thanks...
