### ISSUE TITLE
[BUG]: Game gets stuck during FMV on Mac

### ISSUE THREAD

**Issue by mikesk8** [PCSX2/pcsx2#10275]
### Describe the Bug

During the FMV the game got stuck; as per video attached. 

https://github.com/PCSX2/pcsx2/assets/46671688/f7918434-8f75-4f58-a73b-470a387c1ca5

### Reproduction Steps

I have both a memory and state saves available. In both cases, the game gets stuck.

### PCSX2 Revision

1.7.5205

### Operating System

macOS 12 (Monterey)

### CPU

i5

### GPU

Radeon PRO 570 4GB

### GS Settings

4x native rendering in PCSX2 and Progressing mode in the game itself. Rest default.

**Comment by mikesk8** [comment]
I checked with both Progressive ON and OFF in the game and in both cases it gets stuck.

**Comment by refractionpcsx2** [comment]
How big is your iso file for gow?

**Comment by mikesk8** [comment]
8.522.792.960 bytes (8,52 GB on disk)

**Comment by refractionpcsx2** [comment]
Okay can you go to the per game properties in the interface and verify your disc just to make sure that's okay. Thanks :)

**Comment by mikesk8** [comment]
<img width="706" alt="Screenshot 2023-11-15 at 11 32 35" src="https://github.com/PCSX2/pcsx2/assets/46671688/0463a785-907f-450c-964d-1e4a49531b05">

It seems its a wrong ROM ;-( I have not checked it before ;(

**Comment by refractionpcsx2** [comment]
I would start by redumping your disc in that case, I've never heard of gow fmvs being problematic

**Comment by mikesk8** [comment]
Thanks a lot for your help! ;-)

**Comment by refractionpcsx2** [comment]
No problem, I hope that fixes it :) if not, you should join our discord and ask on there, then we can troubleshoot the problem further
