### ISSUE TITLE
64 bits port tip/trick/documentation

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1027]
Meta tracker to keep useful information for a 64 bits port
- INC/DEC opcode issue

```
INC/DEC still exist in 64-bit code, since only their short forms for registers (opcodes 40h-4Fh) have
 been used for other purposes, and their long forms (opcodes 0FEh-0FFh) are still available.

Any such "conversion" would not be suitable, since "INC EAX" is not the same as "ADD EAX,1" - the 
second one affects CF, while first one doesn't. This is important and utilized feature - thus they could 
not remove the INC/DEC from the instruction set.
```

Note I think we don't use the flag on PCSX2.
- Memory model (quote from Agner's assembly guide)

```
32-bit absolute addressing in 64 bit mode

A 32-bit constant address is sign-extended to 64 bits. This addressing mode works only if it 
is certain that all addresses are below 2^31. It is safe to use 32-bit absolute addressing in Linux and 
BSD main executables, where all addresses are below 2^31 by default, but it cannot be used in 
shared objects. 32-bit absolute addresses will normally work in Windows main executables as well 
(but not DLLs), but no Windows compiler is using this possibility. 32-bit absolute addresses cannot 
be used in Mac OS X, where addresses are above 2^32 by default. 


There is absolutely no reason to use absolute addresses for simple memory operands. Rip-
relative addresses make instructions shorter, they eliminate the need for relocation at load 
time, and they are safe to use in all systems. 
```

32 bits addressing would help to make the x86 (recompiler) code portable to x64

Displacement and immediate are 4 bytes sign extended to 8 bytes.
There are a couple (1?) of exception of special opcodes that can uses 8 bytes constant.
- **Inlined ASM would need to be ported to a new syntax (intrinsic)**

Need to be done
- [x] pcsx2/IPU/yuv2rgb.cpp
- [x] plugins/spu2-x/src/Mixer.cpp

Need to be removed
- [ ] pcsx2/x86/iPsxMem.cpp (unused)
- [ ] pcsx2/x86/iR3000A.cpp (unused)
- [ ] plugins/GSdx/stdafx.h (atomic)

**Comment by gregory38** [comment]
Inlined ASM port would need to be ported to a new syntax due to the following reason
* incompatible with perf on linux
* incompatible with clang on osx
* incompatible with MSVC on x64

Need to be done
* pcsx2/IPU/yuv2rgb.cpp
* plugins/spu2-x/src/Mixer.cpp

Need to be removed
* pcsx2/x86/iPsxMem.cpp (unused)
* pcsx2/x86/iR3000A.cpp (unused)
* plugins/GSdx/stdafx.h (atomic)

**Comment by gregory38** [comment]
Took me days to find back this commit.
https://github.com/tectronics/pcsx2-playground/commit/75e6df336544c0ba77182ff7a38fbee9feae2581

**Comment by gregory38** [comment]
Displacement and immediate are 4 bytes sign extended to 8 bytes.
There are a couple (1?) of exception of special opcodes that can uses 8 bytes constant.

**Comment by ramapcsx2** [comment]
Are there any updates? I think yuv2rgb is done, right :)

**Comment by gregory38** [comment]
Yes. Otherwise no progress,

**Comment by feikname** [comment]
I understand the core needs porting, but what about the dependencies such as libgtk2 and libportaudio2, why does pcsx2 needs their i386 versions rather than x64? perhaps with a few quirks in the build system, couldn't it simply use them instead?

**Comment by feikname** [comment]
@gregory38 Sorry for the bump (it will be my first and last one), its just in case you missed the notification, can I get a reply please?

**Comment by gregory38** [comment]
You cannot mix different architecture like that. Either you have 1 process (== executable + ALL dependencies) in 32 bits or in 64 bits.

The only solution is to port all recompiler to 64 bits.
