### ISSUE TITLE
[BUG]: Inability to use Memory Cards with data in game

### ISSUE THREAD

**Issue by Neigdoig** [PCSX2/pcsx2#10279]
### Describe the Bug

As a result of these latest updates to PCSX2, any memcards with data on them (specifically added when using mymc for my case) will not be recognized by a game I'm playing. I tried this in two games, and I think this issue affects the emulation side, and not the game side.

### Reproduction Steps

1. Use MyMC to add save data to an already formatted memory card
2. Add the memory card of the game you want to play (of course, if it has data for said game)
3. Launch the game

### Expected Behavior

What should happen here is that the game should recognize the card and load the data, and then you can play the game with said data already on that card.

### PCSX2 Revision

1.7.5207

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.2 "Vicroria"

**Comment by Mrlinkwii** [comment]
are you using folder memcardss ? file memcards ? are teh memcards in port1? , this seems like  a support issue

**Comment by Neigdoig** [comment]
> are you using folder memcards ? file memcards ? are the memcards in port1? , this seems like a support issue
This issue affects file .ps2 memcards.

> can we aleast have a copy of the memcards
I will go ahead and make a zip of the ones I'm using once I'm done with an upload. All of them have this affliction, since I think the emulator doesn't even recognize that the cards are in port 1, making the game think there is no card in there.

**Comment by Mrlinkwii** [comment]
have you been using save states by any chance

**Comment by Neigdoig** [comment]
> have you been using save states by any chance

I don't like using save states.

**Comment by stenzek** [comment]
Not really sure why you would think it is our fault when you're using another tool.

If the game has issues saving and loading *itself*, not when editing the memory card with a third-party tool, then we can reopen. But otherwise, this is invalid.
