### ISSUE TITLE
[BUG]: Achievement Rich Presence Option Missing

### ISSUE THREAD

**Issue by TheRhysWyrill** [PCSX2/pcsx2#10289]
### Describe the Bug

Just went to the achievement tab after updating and noticed the absence of `Use RA Rich Presence` and wondering if the removal of this was intended? I've looked through the commits and can't see anywhere this was directly mentioned.

### Reproduction Steps

Go to the Achievements tabs, it used to be directly next/under the `Hardcore Mode` toggle depending on if using Big Picture or not.

### PCSX2 Revision

v1.7.5216

### Operating System

Windows 11

**Comment by stenzek** [comment]
Not a bug. I am not justifying it further for someone who violated our copyright and encouraged harassment for profit.
