### ISSUE TITLE
[BUG]: "Reload Cheats" button doesn't work

### ISSUE THREAD

**Issue by Iristallite** [PCSX2/pcsx2#10282]
### Describe the Bug

Pressing the "Reload Cheats" button doesn't reload cheats properly.

RAM values are still frozen based on the old version of the pnach file (confirmed by pausing, manually editing with debugger, then unpausing; the value instantly reverted to what the old version of the pnach file specified.)

Let's say "Patch A" and "Cheat B" do the exact same modification.
Patch A is, as the name would suggest, located in the "patches" folder.
If I modify Patch A with an external text editor, save the file, then press "Reload Patches", it works as expected and the new patch overrides the old one in memory.

If I do the same for Cheat B, (modifying the file and saving it), pressing "Reload Cheats" only reloads the descriptions, authors, and names of cheats. The old version of the cheat code is stuck in memory until PCSX2 is restarted.

I should clarify that this isn't me being silly and having Patch A override Cheat B, as at no point are Patch A and Cheat B enabled at the same time. Only one is active at a time, for the purpose of this demonstration.

### Reproduction Steps

Preresiquites:

* Have a .pnach file that modifies a memory address in the "cheats" folder

1. Start a game
2. Open the "Game Properties" window and the debugger
3. Open the pnach file in an external editor
4. Enable the cheat code
5. Observe the memory address in the debugger.
5a. If you pause, edit it, then unpause, it should immediately revert to what the cheat sets it to.
6. Modify the pnach file to write a different value to the address.
7. Save the pnach file.
8. Press "Reload Cheats"
9. Observe, using the debugger, that the memory address is still frozen (refer to 5a) at the value specified by the **previous** version of the pnach file (i.e. the one we just overwrote.)

### Expected Behavior

I believe it should behave like the "Reload Patches" button, which actually works and updates the patch in memory to match any changes made to the pnach file externally.

### PCSX2 Revision

Nightly v1.7.5209

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

**Comment by refractionpcsx2** [comment]
do you have example patches?

**Comment by Iristallite** [comment]
Yes, I just whipped up an example that can demonstrate the issue. (Had to save as a .pnach.txt because github won't let me attach a .pnach

[Sonic Unleashed Example.pnach.txt](https://github.com/PCSX2/pcsx2/files/13385182/Sonic.Unleashed.Example.pnach.txt)

**Comment by refractionpcsx2** [comment]
Thanks
