### ISSUE TITLE
[Feature Request]: Exit hotkey

### ISSUE THREAD

**Issue by munt-kaicho** [PCSX2/pcsx2#10293]
### Description

It would be good to be able to bind closing the emulator when pressing Esc or a different key of the user's choice.

### Reason

It's good to have the option from a UX point of view.

### Examples

Dolphin and MAME both have good ways of handling things, where you can map a key to exit the emulator but they can also be configured in a way where if a game is running it asks you for confirmation before closing to avoid accidental shutdowns.

**Comment by stenzek** [comment]
Did you not check the hotkey list before making this request? :/

**Comment by munt-kaicho** [comment]
@stenzek 
I don't see it as an option in my hotkey list. I'm on the latest nightly.

![image](https://github.com/PCSX2/pcsx2/assets/77757752/009085d1-0657-45f0-b7a5-a530ba3a3af2)
![image](https://github.com/PCSX2/pcsx2/assets/77757752/32b3d96f-a03e-4f95-8472-a8ea749508de)

**Comment by bigol83** [comment]
It's shutdown virtual machine hotkey, it has the exact same function as in Dolphin.

**Comment by stenzek** [comment]
Bind shutdown, disable confirm, then use ALT+F4 to exit.

**Comment by refractionpcsx2** [comment]
Then start the emulator with the -batch commandline in your shortcut, then when you shut down the virtual machine, the whole thing will exit

**Comment by munt-kaicho** [comment]
But I don't want to run -batch in case I wanna change the ROM

**Comment by stenzek** [comment]
I already said that you can close with ALT+F4 after shutting down emulation.

I don't see the need to bloat the ingame menu, and hotkey list with an exit hotkey specifically.

**Comment by munt-kaicho** [comment]
Alright.
I'll just stick to batch mode I guess.
I just opened an issue for a related bug:
https://github.com/PCSX2/pcsx2/issues/10294
