### ISSUE TITLE
[Feature Request]: Local persistence of URLs used in the cover downloader.

### ISSUE THREAD

**Issue by Igor-da-SilvaRodrigues** [PCSX2/pcsx2#10297]
### Description

The built-in cover downloader would remember URL's inserted in the text area. When exiting and re-starting the emulator, the URL's previously inserted should still be there. It would also be great if the same could be done to the "Use Serial File Names" checkbox.

![image](https://github.com/PCSX2/pcsx2/assets/77209950/de75193b-b52a-464e-b91f-f7cb2bea6c61)

This could be useful for automatically downloading cover arts at startup, but this isn't what this issue is about.

### Step by Step on how the feature would work

1. The user would insert several URL's in the Cover Downloader screen.
2. The user would re-start PCSX2
3. The user would come back to the Cover Downloader, and it's 

### Reason

This feature would allow for easier experience when dealing with cover arts, as the URLs would be stored locally be the emulator. The user would only have to go back to the Downloader screen and click a button to download new cover arts. Keeping a backup of these URL's would be responsibility of the user, and only optional. 

### Examples

How the text area would look after restart.
![image](https://github.com/PCSX2/pcsx2/assets/77209950/e4744fd9-ab35-4415-b4ee-865b70e3a75a)

**Comment by refractionpcsx2** [comment]
No, as mentioned before https://github.com/PCSX2/pcsx2/issues/8013#issuecomment-1409637302

**Comment by Igor-da-SilvaRodrigues** [comment]
Is it possible then to access the downloader through scripts or the cli? Or could that also be considered piracy?

**Comment by stenzek** [comment]
No interest in doing that, sorry.
