### ISSUE TITLE
[BUG]: Shutdown confirmation box broken while fullscreen

### ISSUE THREAD

**Issue by munt-kaicho** [PCSX2/pcsx2#10294]
### Describe the Bug

![image](https://github.com/PCSX2/pcsx2/assets/77757752/f551ce6a-7f70-421a-bc0c-4309b7d70fbc)

![image](https://github.com/PCSX2/pcsx2/assets/77757752/8537ff2b-731d-471d-80e9-a90b2f90d3fa)

Running on Nightly v.1.7.5216
Confirmation box for shutting down is broken when pressing shutdown hotkey while fullscreened.
It displays correctly when emulator is in windowed mode.

Windows scaling is at 100% and not running any window customization software.

### Reproduction Steps

Run game in fullscreen and press the "Shut Down Virtual Machine" hotkey.

### Expected Behavior

Properly rendered confirmation box.

### PCSX2 Revision

Nightly v.1.7.5216

### Operating System

Windows 11

**Comment by stenzek** [comment]
I'm going to guess you're using exclusive fullscreen?

**Comment by munt-kaicho** [comment]
I'm in OpenGL, only option I have is borderelss.

**Comment by bigol83** [comment]
It happens with both exclusive fullscreen and borderless fullscreen mode i can confirm. Also, can confirm it only happens with fullscreen mode, not when emulation is in a window.

**Comment by stenzek** [comment]
Not really sure we can do much about it to be honest, it's probably something to do with mode switching, and potentially a Qt bug. I've never encountered this myself, but I'll try to reproduce it later anyway..

**Comment by stenzek** [comment]
Okay, seems it's a new issue. A bisect would have been helpful.
