### ISSUE TITLE
Is libjpeg-turbo a requirement?

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1029]
Hi,

I thought I read somewhere that PCSX2 required libjpeg-turbo?

One place I did notice this is Arch Linux;

https://www.archlinux.org/packages/community/i686/pcsx2/

I'm running Slackware and it comes with libjpeg-v8a, is this ok?

thank you

**Comment by gregory38** [comment]
Only the deprecated (and not build by default) zzogl requires some jpeg headers (maybe not the lib)

**Comment by Geyup** [comment]
I'd contact the Arch maintainer to let him/her know that libjpeg-turbo is not a dependancy...

So I'm assuming by your reply libjpeg-v8a is fine?

thank you again gregory38

**Comment by gregory38** [comment]
If you build with extra plugin, you need a libjpeg version (I think all versions are likely fine)

**Comment by Geyup** [comment]
thank you
