### ISSUE TITLE
Question: 1.3.1 Plugins?

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1030]
Hi gregory38,

Can you please tell me for 1.3.1 is this all the plugins it builds?

/usr/lib/pcsx2/libzzogl-0.4.0.so
/usr/lib/pcsx2/libspu2x-2.0.0.so
/usr/lib/pcsx2/libFWnull-0.7.0.so
/usr/lib/pcsx2/libonepad-1.1.0.so
/usr/lib/pcsx2/libUSBnull-0.7.0.so
/usr/lib/pcsx2/libGSdx-0.1.16.so
/usr/lib/pcsx2/libCDVDnull.so

I just want to make sure I have my compile options correct?

```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
    -DWX28_API=TRUE \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBIN_DIR=/usr/bin/32 \
    -DCMAKE_LIBRARY_PATH=/usr/lib \
    -DGAMEINDEX_DIR=/usr/share/pcsx2 \
    -DPLUGIN_DIR=/usr/lib/pcsx2 \
    -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/32/wx-config \
    -DwxWidgets_wxrc_EXECUTABLE=/usr/bin/32/wxrc-2.8 \
    -D{GLSL_API,PACKAGE_MODE,REBUILD_SHADER,XDG_STD}=ON \
    -DCMAKE_BUILD_TYPE=Release ..
        
  make
  make install DESTDIR=$PKG
```

thank you

**Comment by gregory38** [comment]
May I suggest to read the cmake log file. Otherwise extra plugins are oldies in bad state.

**Comment by gregory38** [comment]
Wait what is 1.3.1 for you? Don't tell me that you use the old git test tag.

**Comment by gregory38** [comment]
As a side note glsl option is useless (and not supported) (done for zzogl). You don't need to rebuild shader (mostly impact zzogl).

**Comment by gregory38** [comment]
Bonus question (then I stop the spam) why do you use wx2.8?

**Comment by Geyup** [comment]
Old git test tag, I don't understand?

I thought 1.3.1 only uses wx2.8? Or you suggesting it's best to update to the latest git version for wx3?

thank you for your time and help, much appreciated!

**Comment by gregory38** [comment]
There wasn't any 1.3 release. 1.3 is the latest git (closer of 1.4 rc btw). We added a tag a long time ago to test build bot.

There is a gtk3 option but not well tested. You can still use 2.8 but it is clearly eol.

Others questions => yes

**Comment by Geyup** [comment]
Ok well, releases like this are assumed as a release and stable;

https://github.com/PCSX2/pcsx2/releases

ok thanks for everything!

**Comment by gregory38** [comment]
Sorry for the confusion, it is likely github that generate a release because we added a tag.
It is often safer to keep PCSX2 flags. Various flags uses to crash the program. I fixed several of them but some issue might remain.
```
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
```

**Comment by Geyup** [comment]
Sorry what are you showing me with the two flags below? I use them already...

```
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
```

**Comment by gregory38** [comment]
I mean that I don't recommend to use those options.

**Comment by Geyup** [comment]
ahhh ok thanks

**Comment by turtleli** [comment]
That's really up to your scripting preferences and whether you'd like to keep it in your SlackBuild script or not.

**Comment by Geyup** [comment]
Gregory38 said he didn't recommend these;

```
-DCMAKE_C_FLAGS="$SLKCFLAGS" \
-DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
````

So then I don't see any point in the last set of flags I posted? If so can you please explain why I'd keep them? Because all I see they would of been needed for are the two flags I just posted above...

hmm

thank you

**Comment by turtleli** [comment]
Personally, I'd remove or comment them, but I wasn't sure whether you like having your SlackBuilds follow a standard format or not. That's what I meant by "up to you".

**Comment by Geyup** [comment]
Ahh ok I'll remove then, no need, thanks...
