### ISSUE TITLE
[BUG]: Time Crisis 2 Guncon2 single-player calibration issue using Vjoy

### ISSUE THREAD

**Issue by ZTylerDurden** [PCSX2/pcsx2#10305]
### Describe the Bug

Intro calibration screen works fine except beyond that screen there's an "invisible wall" on each side including incorrect line-of-sight.

In these videos you can see I'm successfully targeting the edges during calibration.  However, beyond that screen I can't shoot the edges:  
https://www.youtube.com/watch?v=JIHZpJ-hODc
https://youtu.be/weD_rlXwpd0

I understand these games have manual x,y overrides mile-stoned in pcsx2 with TC2 included:
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/USB/usb-lightgun/guncon2.cpp

I'm using a vjoy-based infrared light gun and I'm part of the development team of said light gun.  Resident Evil Dead Aim by comparison works perfectly.

I've tried setting aspect ratio to auto 4:3 / 3:2, offsets on/off, overscan on/off but it doesn't make a difference.  Maybe there's a certain combination between the three values above that I didn't try yet.

The 4-point infrared system I'm using is practical and I'm happy to send my materials to whoever would like to try reproducing the issue.

### Reproduction Steps

All default settings, then:
Controller Global settings -> Uncheck "Enable Sdl Input Source" and Check "Enable Dinput Input Source"
USB Port 1 -> Guncon2 and configure inputs and relative aiming axis

### Expected Behavior

Should maintain line-of-sight after calibration with no "invisible walls" on the sides of the screen.

### PCSX2 Revision

V1.7.5223

### Operating System

Windows 10 (64bit)

### CPU

i7-8700k

### GPU

RTX 4070

### Emulation Settings

Controller Global settings -> Uncheck "Enable Sdl Input Source" and Check "Enable Dinput Input Source"
USB Port 1 -> Guncon2 and configure inputs and relative aiming axis

**Comment by stenzek** [comment]
Does it happen with a controller, and mouse?
Use the crosshair image to see where on the screen it's mapping the axis to.

You also should not be using DInput for anything.

**Comment by ZTylerDurden** [comment]
_Does it happen with a controller, and mouse?_

Yes.  Demonstration below.  You should be able to reproduce this issue with a mouse in Gcon2 mode.  If you can't, it'll be something on my side.
https://www.youtube.com/watch?v=ZE_iZnZw9-o

_You also should not be using DInput for anything._
Tried both SDL Input and Dinput. Both result in the same behavior.

**Comment by stenzek** [comment]
Invalid. Issue is with the widescreen patch.

In the future, please don't report bugs with patches enabled.

**Comment by ZTylerDurden** [comment]
Confirmed.  Widescreen patch enabled by default and was left ticked.

Thanks.
