### ISSUE TITLE
Releasing host memory maps for virtual systems...

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1031]
I just compiled the latest git version today in Slackware; ```PCSX2 1.3.1-20151207111040```

When I click on System > Exit, I then get this message at the terminal;

```Releasing host memory maps for virtual systems...```

The GUI disappears but the log still remains on the desktop and the message just stays in the terminal and it never completes exiting...

**Comment by turtleli** [comment]
I pushed a fix so it should work now. Please test.

**Comment by Geyup** [comment]
yeah it works now, thanks
