### ISSUE TITLE
Shadow of rome. What is the current way to fix the bluriness?

### ISSUE THREAD

**Issue by ffrasisti** [PCSX2/pcsx2#10332]
### Describe the Bug

Hey, Shadow of Rome uses some weird post fx lines to do DOF, so it almost always looks terrible unless some workaround is deployed at high resolutions. On the old pcsx2 1.6 i followed the guide on the wikia to fix it, after updating to the latest nightly, it doesnt quite work.
 I tried following the outdated recommendations on the wikia for the nightly and the skipdraw its says to use to fix the blur broke the game. Using half pixel offset Vertex results in still having some blurriness
the fix for me was Half Pixel Offset -> Special (Texture)
De-interlacing -> Automatic (Default)
Bilinear Filtering -> Bilinear (Smooth)

I am unsure whether to use "Disable Interlace Offset". I've left it on. Can someone give the game a look and update the wikia?

### Reproduction Steps

Open the game on all default settings but set rendering to about 1440p

### PCSX2 Revision

1.7.5240

### Operating System

Windows 10 (64bit)

### CPU

9900k

### GPU

RTX 3080TI

**Comment by stenzek** [comment]
The issue tracker is not for user support, please use the Discord server and/or forums.

And stop spamming issues.
