### ISSUE TITLE
[BUG]: "007 Russia with Love" lights visible through walls

### ISSUE THREAD

**Issue by nesaruM** [PCSX2/pcsx2#10349]
### Describe the Bug

On 007 Russia with Love, default settings, 4x native, blending full (recommended). some lights are visible through walls
![007 - From Russia with Love_SLUS-21282_20231202205603](https://github.com/PCSX2/pcsx2/assets/150381934/496b928b-7f99-4da1-8135-fe29a25fb223)
![007 - From Russia with Love_SLUS-21282_20231202205609](https://github.com/PCSX2/pcsx2/assets/150381934/45682f48-2304-4dc2-aca2-a2a54e843473)
![007 - From Russia with Love_SLUS-21282_20231202212016](https://github.com/PCSX2/pcsx2/assets/150381934/de86a172-5d10-4348-8fa0-1d56204b9735)
![007 - From Russia with Love_SLUS-21282_20231202212019](https://github.com/PCSX2/pcsx2/assets/150381934/bf8237e7-5149-4d16-9db0-c08254f193e3)

### Reproduction Steps

guess just play on hardware

### PCSX2 Revision

v.1.7.5253

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i5-10500H CPU

### GPU

Geforce GTX 1650 Laptop GPU

### Logs & Dumps

[russia with love.zip](https://github.com/PCSX2/pcsx2/files/13537283/russia.with.love.zip)

**Comment by refractionpcsx2** [comment]
Oh, I didn't realise it was just an upscaling issue, we don't take issues for those as per the template guidelines.

I did have a look anyway and Half Pixel Offset Normal fixes it but causes a line in the middle of the screen in other areas.

Another solution which works (which we can't do automatically) is set your texture offsets to 500, 500 and it will fix it.  But we can't do anything beyond this.
