### ISSUE TITLE
Linux Mint 17.3 MATE held package

### ISSUE THREAD

**Issue by captug** [PCSX2/pcsx2#1035]
i just do a fresh install of Linux Mint 17.3 MATE and add the ppa for pcsx2. It went well until I try to install it and an error occur. It says broken package and need to be fixed.

I try to fix it using the fix broken packages on Synaptic. But then again it shows an error

E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: Unable to correct dependencies

I have installed pcsx2 on linux mint 17.2 xfce before and there is no problem at all. Any idea how to fix this? 

thank you

**Comment by gregory38** [comment]
It is likely a missing 32 bits dependencies. Without log we can't help.

**Comment by captug** [comment]
how to generate a log? I will post it here

**Comment by gregory38** [comment]
Better asking the question in the forum. Others mint user can help you.
Otherwise any info could be useful. The only info so far you've posted is "don't work on my computer". And I could reply here ppa is working, do same install as me.

**Comment by captug** [comment]
ok I will try on the forum. Thank you
