### ISSUE TITLE
[BUG]: Need for speed: MOST WANTED 2005 on pcsx2 "Sundays appear as halos"

### ISSUE THREAD

**Issue by Naniboy007** [PCSX2/pcsx2#10351]
### Describe the Bug

![Screenshot 2023-12-03 at 10 38 24 AM](https://github.com/PCSX2/pcsx2/assets/113497507/064b7aa1-f658-44bc-8fb5-28de3abb6afb)
 graphical artifacts !
sun rays appear circular halos after adding HD textures.
please help fix this issue.

### Reproduction Steps

![Screenshot 2023-12-03 at 10 38 24 AM](https://github.com/PCSX2/pcsx2/assets/113497507/a57bf1ae-88ee-480d-8342-8914c8e430fd)
appears after hd textures added to game library.

### PCSX2 Revision

v1.7.5253

### Operating System

macOS 13 (Ventura)

### CPU

M1

### GPU

Metal

### GS Window Screenshots

![Screenshot 2023-12-03 at 10 38 24 AM](https://github.com/PCSX2/pcsx2/assets/113497507/9e44e3b6-73bd-480a-a1ce-0ebc57483edc)

**Comment by refractionpcsx2** [comment]
This is a support issue with the maker of the texture pack, this doesn't belong on here, this is for emulator bugs only
