### ISSUE TITLE
[BUG]: Monster Hunter 1 US version gets it's image cut if you have a savefile.

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#10369]
### Describe the Bug

The game doesn't cover the full 4:3 aspect ratio if you have a SaveFile on the memory card, here you can see it happening even on software mode, this will not go away until you reboot the game with no SaveFile and once you save, it will reappear.
1.No SaveFile on Memory Card
![Monster Hunter_SLUS-20896_20231207153428](https://github.com/PCSX2/pcsx2/assets/89411895/b11a1d57-b52a-4881-b6bd-67a00d9e6c77)
2. SaveFile on Memory Card.
![Monster Hunter_SLUS-20896_20231207153238](https://github.com/PCSX2/pcsx2/assets/89411895/12251a8c-0d84-4a77-8188-5f4a20ebf581)

### Reproduction Steps

1.Boot the game while having a save for Monster Hunter 1 on the memory card.
2. You should be able to see it on the first cutscene that shows up before the main menu

### PCSX2 Revision

v1.7.5263

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

### CPU

Ryzen 5 5600

### GPU

Rx 6600

### Logs & Dumps

[GS Dump No issue.zip](https://github.com/PCSX2/pcsx2/files/13605379/GS.Dump.No.issue.zip)
[GS Dump with issue.zip](https://github.com/PCSX2/pcsx2/files/13605380/GS.Dump.with.issue.zip)
Memcard: [mhus.ps2.zip](https://github.com/PCSX2/pcsx2/files/13605655/mhus.ps2.zip)

**Comment by Mrlinkwii** [comment]
upon further investigation , it seems to be user error
