### ISSUE TITLE
[BUG]: Midnight Club 3 DUB Edition Remix (NTSC-U) (SLUS-21355) camera glitch with 60FPS patch

### ISSUE THREAD

**Issue by ParovozNFF** [PCSX2/pcsx2#10362]
### Describe the Bug

Hello!
NTSC-U version of Midnight club 3 DUB edition Remix has a camera glitch when 60 fps patch from the emulator's "Patches" menu is applied. The camera changes into "look back" position for a frame or two every several seconds. Seemingly it happens more often when the car is turning at high speed. So far it replicates with every combination of settings, starting with default ones, when the patch is applied. When it isn't, everything is fine. EE overclock is set at 300% as the patch requires it.
Configs and logs are in the attached .zip, i hope i got the right files.
Thanks for your work!

### Reproduction Steps

Run NTSC-U version of Midnight club 3 DUB edition Remix with 60 FPS patch from the "Patches" menu applied and EE overclock set to 300% as suggested.

### Expected Behavior

For camera to not glitch.

### PCSX2 Revision

1.7.5261 (latest nightly)

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600 6-core processor

### GPU

Nvidia GeForce GT 1030

### Logs & Dumps

[MC3DER 60 fps camera glitch.zip](https://github.com/PCSX2/pcsx2/files/13574605/MC3DER.60.fps.camera.glitch.zip)

**Comment by Mrlinkwii** [comment]
As mentioned in the patch window , their is no support for patches , I'd advise contacting the patch author :)
