### ISSUE TITLE
[Feature Request]: Input Recorded File to specify the exact version rather than the overall version.

### ISSUE THREAD

**Issue by Spikestuff** [PCSX2/pcsx2#10366]
### Description

Basically as the title says. What is shown in the .p2m2 files is the overall version that's used rather than a specific version.

### Reason

Say for instance movie that was created using v1.7.5259. The .p2m2 file only states that it was made in v1.7.0
It would be better to know the exact version for ease of getting a movie to sync rather than something that can be avoided if the exact dev build is known. At least a factor would be known.

### Examples

The [Tool-Assisted Emulator BizHawk](https://github.com/TASEmulators/BizHawk) outlines in its replayed files:
- The version of BizHawk which was used (dev builds would also be outlined as the exact build).
- Which version of the title is being used (PCSX2 only shares the title, it doesn't mention if it's PAL for instance).
- If a bios is in use, and what bios that is (hash information or saying v2.0).

![image](https://github.com/PCSX2/pcsx2/assets/12412764/c0da0e64-34c9-424c-a404-c1c3a95249dd)
In this example I'm using BizHawk 2.9.1 so it highlights in yellow that a different version is used for the creation of the file.

I'm aware of the difference of something that can be perceived through a text editor and something that requires HxD but this is for demonstration purposes to at least show what's on BizHawk's side.

If this is reason to change the title to be more of a "More detailed information for .p2m2 files" to at least incorporate mention the other two points mentioned then so be it as long as it helps sharing .p2m2 files around and having a better bit of sanity to know information.

**Comment by lightningterror** [comment]
@Spikestuff try https://github.com/PCSX2/pcsx2/pull/10381

**Comment by Spikestuff** [comment]
Yes it does work. Sorry on the massive enough delay to respond but thank you very much.
