### ISSUE TITLE
[BUG]: In the latest V1.7.2567 release, Vulkan is not available for AMD R9 370 series

### ISSUE THREAD

**Issue by BDJoe360** [PCSX2/pcsx2#10375]
### Describe the Bug

In the latest V1.7.2567 release, Vulkan is not available for AMD R9 370 series

### Reproduction Steps

You can play the game before the upgrade, and after the upgrade, the game will appear: Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated

### PCSX2 Revision

V1.7.2567

### Operating System

Windows 10 (64bit)

### Logs & Dumps

Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated.

**Comment by stenzek** [comment]
We have required Vulkan 1.1, plus a few extensions for some time now. This is a GCN1.0 GPU, ancient by today's standards, so it's not surprising that AMD doesn't support the newer extensions on it.

**Comment by TellowKrinkle** [comment]
It should work fine on Linux or with the NimeZ/Amernime/whatever they're called now 3rd party drivers

**Comment by mirh** [comment]
It ***is*** actually totally surprising since AMD has been supporting vulkan 1.1 since 2018, and 1.2 since 2020 (pretty much on day 1).
Older cards on windows never got 1.3, sure enough.. But this doesn't make sense unless OP is using some stone age driver.

**Comment by TellowKrinkle** [comment]
We require VK_KHR_push_descriptor, which isn't even part of Vulkan 1.3. AMD added support for it semi recently, but after dropping support for older GCN GPUs.

**Comment by mirh** [comment]
[I see](https://github.com/PCSX2/pcsx2/pull/9742), sorry.
