### ISSUE TITLE
[Feature Request]: Texture Replacement: Only Reload New Texture Replacements

### ISSUE THREAD

**Issue by ch1ckenstripper** [PCSX2/pcsx2#10389]
### Description

Hello, long time PCSX2 user here <3
I have discovered the power of real time texture upscaling. The only thing that would make it seamless as possible for anyone doing this would be to change the current way the texture replacements are refreshed.
Currently, **all** the textures "flash" back to the originals for a split second when they are reloaded. There needs to be a way to only look for new textures, not reload ones that are already loaded. 

### Reason

Even with an SSD this "texture flash" is still noticeable, especially if ideally (to me) you would be looking for newly upscaled textures every few seconds.
Due to the nature of the texture dumping, currently, real time upscaling is the best way to have a seamless experience. This small change would allow the user to be completely unaware that the game they were playing was getting remastered as they were playing it (aside from the clearly **[GARGANTUAN](https://getyarn.io/yarn-clip/9c050442-d2a0-43f3-a0bb-5af145aa4b2c)** boost in detail!)

### Examples

1: I'm no coder.
2: I tried to open up the source and the only thing I could think of with what I could understand would be to just not clear the 
    cache on texture replacements refresh? Idk but I couldn't get anywhere on my own.
3: See 1. 
4: Thank you!

**Comment by stenzek** [comment]
Not possible. The TC doesn't keep track of the replacements, they're just injected in place of the normal hash cache textured. So reloading just flushes/empties the texture cache, and it gets re-populated by local memory, or injected replacements.

You could turn off async loading, but that would mean lagging every time you reloaded. Pick your poison.

> Due to the nature of the texture dumping, currently, real time upscaling is the best way to have a seamless experience. This small change would allow the user to be completely unaware that the game they were playing was getting remastered

This is not the intended use case for texture replacements.
