### ISSUE TITLE
Automatic controller configuration for XInput devices

### ISSUE THREAD

**Issue by mirhl** [PCSX2/pcsx2#1038]
We were discussing on IRC of better ways to streamline PCSX2 setup. 

Besides what the title implies, it would be *awesome* if "DualShock-compliant hardware" also could be detected and have their special features (like button sensitivity) enabled by default. 
On Windows I guess this would correspond to detecting Scarlett.Crush driver.

**Comment by rz5** [comment]
@KrossX's pokopom plugin mapped my xinput gamepad controls to a PS2 controller without me needing to do so.

Unlike the included non-default xpad plugin, it has a nice GUI. It does not handle DirectInput gamepads though.

**Comment by rz5** [comment]
An alternative to using padPokopom would be to add a feature to LillyPad: make it autoconfigure xinput devices.

**Comment by ramapcsx2** [comment]
Making an xinput pad plugin the default on Windows is fine by me. We would need to check about padPokopom's license and permission from KrossX. Xpad works as well, right? We do have the sources for that included.

**Comment by KrossX** [comment]
Pokopom is MIT in general with imported code having their own license, usually LGPL or GPL. But the only advantage over xpad is an option here and there, nothing that cannot be ported over.

I would suggest instead to have default LilyPad settings for XInput controllers. It's customizable, easy to modify if needed and keeps LilyPad as default plugin on Windows.

**Comment by ramapcsx2** [comment]
Thanks, KrossX.
Unfortunately we're lacking somone who could whip up a patch for Lilypad to do this.
Think you could give it a try? :p

**Comment by KrossX** [comment]
Well, sure, but I was thinking of something simple like a premade INI file that would be installed if there's no previous INI file present. So yeah, I can make an INI and attach it here. =D

APIs are all enabled by default, so just having control settings for port1 and port2 for XInput[0] and XInput[1] devices respectively should do the trick.

Being setup only, avoids overriting previous user settings. Users that do not have a xinput controller would need to setup theirs and can just clear the current configuration easily.

Other than that, I can try adding Scarlett.Crush pressure support but for usage with its xinput wrapper though.

**Comment by ramapcsx2** [comment]
Wow, great!
I'll see if I can test this here :)

**Comment by ramapcsx2** [comment]
Test successful. Just having any 360 pad connected, it works out of the box with this ini. No need to go to the config dialog at all.
This should help new users quite a bit :)

**Comment by Sarania** [comment]
Definitely support this. This is nice. Even though I'm not a noob, I find I have to reconfigure my controller more than I'd like(read: Update PCSX2 more than I'd like for testing, and I always revert config completely for testing XD) so it's useful for non noobs too.

**Comment by KrossX** [comment]
So.. how to implement it? My guess would be to place the file inside **bin/inis** then do some NSIS magic to copy it to the right place if necessary.

**Comment by willkuer** [comment]
I think there is a save profile function in lilypad. A corresponding load profile function exists therefore as well.

You could save this setting as lilypad profile and call the profile loader function on xinput recognition. Maybe a dialog asking if the user wants to use a preconfigured config for his xinput device would be nice.

**Comment by mirhl** [comment]
XInput bindings are.. well, XInput bindings. I don't see how somebody could remotely want to reject them. 
Of course they should just be loaded whenever there isn't any LilyPad.ini already in place.

**Comment by willkuer** [comment]
I guess asking doent hurt. It will also show the user directly that his mapping was already done. So users that are used to do it manually will not be confused.

**Comment by KrossX** [comment]
Any custom detection would require messing up more LilyPad code, which is something I wanted to avoid by just putting an INI file in the appropriate place. This simple thing also allows xinput devices to be hot plugged and be ready to use.

The Lily files are basically copies of the INI settings, and there would still be the problem of where to install the file. This then requires extra code in LilyPad to load the file when necessary, and "when necessary" requires extra checks.

**Comment by ramapcsx2** [comment]
We'll go with NSIS "magic" ;)

**Comment by willkuer** [comment]
Btw. Why dont you mess up lilypad code? You dont want to invest more time into it or you have the feeling that it would overcomplicate the plugin code wise or reduce usability?

**Comment by KrossX** [comment]
Because the way I'm thinking it, trying to do do the same thing in code ends up in a complicated solution that is less robust than the simple one.

**Comment by ramapcsx2** [comment]
Turns out we might have to do it in code after all though.
The nsis installer doesn't create any files in My Documents, leaving it up to the first time wizard.
Now the wizard can create the folders in the right place, but it would have to move the .ini there as well.
You can see how this can get messy. The uninstaller also wouldn't know about this file and might not clean up properly. I think we can fix that though.
To be clear: There wouldn't be a problem in a binary release. We just put the file in /bin/inis and that'd be it. The problem is the combination of nsis installer and our first time wizard, coupled with all the variations due to user account rights..
It would probably be best if Lilypad had a default configuration stored within and would load that in case it doesn't find an .ini.

**Comment by KrossX** [comment]
Hmmm... adding the file as resource and copying it when PCSX2 sends the ini path might do the trick. No fancy detection nor anything like that.

**Comment by ramapcsx2** [comment]
Could you whip up a patch for this? I've no idea how that would work :p

**Comment by KrossX** [comment]
[Done!](https://github.com/KrossX/pcsx2/commit/3b2d3763f255e80973aa85b087fcf25b7c3a6b91)

**Comment by ramapcsx2** [comment]
You've earned yourself some cookies :p

**Comment by mirhl** [comment]
Thanks you all!

**Comment by KrossX** [comment]
Lies! This ain't done yet. =O

#1040 has the required SCP pressure support by default.

**Comment by mirhl** [comment]
My ticket was just about auto-configuring. 
Pressure support albeit greatly appreciated was another matter.

**Comment by KrossX** [comment]
Oh alright then.
