### ISSUE TITLE
[BUG]: Incorrect resolution shown in status bar for ICO in 1x scale [SCUS-97113]

### ISSUE THREAD

**Issue by TwilightSlick** [PCSX2/pcsx2#10393]
### Describe the Bug

In the status bar the game ICO [SCUS-97113] shows in its resolution section that it is rendering at 512x448 progressive when using 1x scale. This is actually incorrect to what the output is on console, the game actually outputs in 240p 512x224. Is this some sort of party trick the PS2 is doing, having the game's framebuffer at 480p then throwing out half the image to display at 240p in the end?

### Reproduction Steps

Run the US version of ICO [SCUS-97113] with the status bar turned on. The resolution will display as 512x448, progressive

### Expected Behavior

Status bar should show ICO running at 512x224 progressive, as it does on console.

### PCSX2 Revision

v1.7.5281

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
It's not really incorrect. The framebuffer that's being scanned out is actually 448 high, and it is progressive output (just not 480p).

**Comment by refractionpcsx2** [comment]
The NTSC version requests an interlaced resolution

DISPLAY[1] DX=636 DY=50 DW=2559 DH=447 MAGH=4 MAGV=0
SMODE2 INT=1 FFMD=1 DPMS=0

Here you can see INT (interlacE) is set, FFMD is set to FRAME mode (read every line) and the requested height is 448 (it's DH+1), we're outputting exactly what he game is telling us to, not what it does internally with draws.

The PAL version however does say 512x256, and the PCRTC settings are as follows

DISPLAY[1] DX=656 DY=36 DW=2559 DH=255 MAGH=4 MAGV=0
SMODE2 INT=0 FFMD=1 DPMS=0

As you can see, INT (interlacing) is off, and the requested height is 256, which is the progressive signal you're expecting. Why they did this for the NTSC version? I have no idea, but it's not our bug.
