### ISSUE TITLE
[BUG]: Macro triggers using logical OR instead of logical AND for multi-button triggers

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#10398]
### Describe the Bug

Setting a macro to trigger on multiple keys will cause any of the member keys individually to set off the macro. This affects any macros with 2+ trigger keys involved.

E.g. SDL-0/RightShoulder & SDL-0/B

Pressing SDL-0/RightShoulder, or pressing SDL-0/B will activate the macro.

Instead, both should be pressed to activate the macro.

### Reproduction Steps

Set up a macro, hold one button then press and release another to make a multiple key trigger. Pressing either of the two buttons without the other will set off the macro when it shouldn't.

### Expected Behavior

Pressing one of but not all members of a macro trigger should not set off the macro. Pressing all members should.

### PCSX2 Revision

v1.7.5285

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Duplicate of https://github.com/PCSX2/pcsx2/issues/8192 - I explained what's going on there (probably not in enough detail).

**Comment by RedPanda4552** [comment]
Closing in favor of #8192
