### ISSUE TITLE
Noob-friendly GSdx renderer auto-selection

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1039]
We were discussing on IRC of better ways to streamline PCSX2 setup. 

One of the usual things I have to help others to adjust is the bloody renderer. 
I just know Windows situation, but I guess somebody else could expand this for Linux. 

At the moment here, pcsx2 just defaults on D3D9. 
But I guess we may all agree OGL is so superior it would be a crime not to use that, *assumed system supports it*. 
...
This, except for AMD cards that, at least on my PC see framerate halved. I'd propose those to default on D3D11.

The only corner case I see in the end are Intel IGPs. Opinions are welcome.

**Comment by ramapcsx2** [comment]
I'd still default to ogl no matter what. Chances are, the speed is good enough on people's machines anyway.
If not, they will have to tweak their config anyway. And in that case we can recommend to switch to D3D11 first.

**Comment by willkuer** [comment]
I'm not sure about the status but i think older intel igpu's crash gsdx upon OGL selection during boot. It was at least like that before. Maybe gregory fixed it already.

For linux the case is simple: there is just ogl.

There is one enum value in GSRendererType that represents the default. Currently it uses dx9 (hw) for windows and ogl (hw) otherwise. If one removes the 'ifdef windows' all would fallback to ogl on first run/missing ini.

**Comment by vsub** [comment]
> Maybe gregory fixed it already.
Nope(at least here).
Starting any game while using my HD4600,pcsx2 crashes the moment the game actually start(no videos\ingame cut scenes)

For example:
KH2FM - new game...skip the scenes or load a save
Ar Tonelico 2 - skip the intro(video)after starting a new game or just load a save

**Comment by mirhl** [comment]
> For linux the case is simple: there is just ogl.

Lol. I must be dumb. 

Anyway I guess it was a bit implicit that there should a fallback. Which, I believe should be d3d9 considering on Windows that's been a constant for at least the last 10 years. 

Speaking of the AMD problem.. I'm not sure. Since there's no difference in framerate between native and 2x, I'd dare to say opengl is having some problem of draw calls flood. 
And that's cutting cpu cycles otherwise available to EE. 

And I mean, I just have a dual core, so I can't really that. But if AMD was not to be using threaded optimization, everybody is going to have a *very* bad time, considering 2x my C2D@3Ghz would mean you need a 6GHz cpu (mhh no) or a 3GHz one with two times the same IPC. 
And I would guess there's isn't anything lower than a modern i7 with these requirements

**Comment by gregory38** [comment]
Dx driver must be MT (partially done by ms layer). I got a big boost with MT on openGL nvidia. Yet it only manages to reach the dx level. I think there is still room for a couple of optimization (upload of texture/uniform...). However AMD driver is slow as ass. I'm nearly sure they have something equivalent but it is likely enabled on some games (profile).

**Comment by Geyup** [comment]
Linux might be simpler but there is Hardware, Software and OpenCL...

**Comment by willkuer** [comment]
Ocl doesnt work. I thougt it is disbled as well.
We always used hw renderr by default. I wouldn't change that.

As long as windows intel igpu's are not stable on ogl i would keep dx9 as default. We have some igpu users in the forum.

**Comment by ssakash** [comment]
Windows XP is also limited to D3D9 so I guess it should be the default renderer.

**Comment by gregory38** [comment]
Opencl need to be removed from the vector configuration.

I asked a special trace on the issue but never got a reply. The issue is that an opengl function reports an invalid parameter but I don't know which one... that a shame because I could potentially disable the unsupported extensions (or people could complain on Intel tracker)

**Comment by willkuer** [comment]
Dolphin claims ogl3.3 is winxp compatible iirc. I havent cross checked that. So possibly it would even work for xp. If i understood correctly ogl >= 4 features are not mandatory. Still gsdx might crash using higher accuracy settings as they require ogl >= 4. so probably we just keep it like that...

Maybe one could use OGL at least on nvidia gpu's. Or on gpus that support nrcessary OGL functions. I currently don't know how hard it would be to implement that.

**Comment by gregory38** [comment]
The full gl implementation is done in the driver (whereas dx top layer is done by ms). So even gl4 must work.

**Comment by gregory38** [comment]
I removed the openCL from the GUI in latest git (hum didn't test it actually, shame on me)

**Comment by Nobbs66** [comment]
Yeah, I don't think OGL should be default. The issues with compatibility on intel IGPUs as well as being slow as ass on AMD cards would probably cause quite a few angry users wondering WTF happened. D3D11 would probably be the best choice. I know it's not compatible on XP, but if you're running that old of an OS, your PC is likely too weak for PCSX2 in the first place

**Comment by bositman** [comment]
Defaults should work on every hardware out there, that's why we set DX9 as the default for all these years. ATM DX9 systems should be negligible, so it makes sense to set DX11 as default but certainly not OpenGL. There are TONS of graphics cards that do not support the openGL extensions we require and having that as default is very wrong IMO

**Comment by ramapcsx2** [comment]
Thanks for the input so far.
I've learned that some (all?) Intel cards currently won't work at all with gl, so that's a bummer.

**Comment by gregory38** [comment]
Ivy bridge and below. IB is potentially fixable if someone generate me a good backtrace. SB misses most of the useful gl extensions. Of course I mean on windows. On linux, SB and up are supported.

**Comment by willkuer** [comment]
Dx10/11 is only available on specific cards. Therefore it is dynamically added at runtime to the configuration. We can not statically set dx11 as default if we dont remove the runtime addition of dx11 or add a runtime fallback to dx9.

To be honest i would keep dx9. It is the renderer with highest compatibility. Also it isnt that bad.

**Comment by mirhl** [comment]
I wonder if [GPU PerfStudio](http://developer.amd.com/tools-and-sdks/graphics-development/gpu-perfstudio/) or [CodeXL](http://developer.amd.com/tools-and-sdks/opencl-zone/codexl/) couldn't be used to get down on the AMD cards problem. 
Another (perhaps simpler but with no warranty) way would be trying other [games profiles](http://www.kn00tcn.net/site/ati-catalyst-profiles/). 

@willkuer OCL did work last time I tried it, albeit quite slowly (bedore it got removed). 

@bositman and everybody else
My idea was dynamically detecting the best possible setting during startup. *That*'s going to work for everybody. 

At the moment I can think to a checklist like: 
```
If (GL is available & !=AMD !=intel)
    set GL
else
    if (D3D11 is available)
        set D3D11
    else
        set D3D9
```
Sorry if it looks simplistically too stupid, I guess everything can be improved.

**Comment by ssakash** [comment]
D3D level check is actually easy on windows side. I'm not sure about the AMD | Intel detection case when people use default hardware device option. but probably feasible with some other detection factor.

**Comment by willkuer** [comment]
As gregory has these nice 'buggy_amd_driver' defines i guess one could as well detect on runtime the vendor.

**Comment by mirhl** [comment]
PCSX2 is already able to detect driver vendors (this is how it disables GL_ARB_separate_shader_objects with AMD cards for example)

And.. speaking of ocl.. what would have been the matter with a driver version check there too?

**Comment by ssakash** [comment]
Gregory removed OpenCL option from the renderer box. I'm not sure why people would even consider using OpenCL at it's current state.

**Comment by rz5** [comment]
Some pseudo code I got with the help of @gregory38 

```
#include <pcsx2\plugins\GSdx\GS.cpp> // to use GSWndWGL()
#include <string> // to use std::string

    // wizard code before plugin selection page

    auto glWindow = GSWndWGL();
    glWindow.Create("Checking OpenGL vendor name", 640, 480);
    // We now have a OpenGL context created, so we can call glGetString()

    std::string vendor( (char const*) glGetString(GL_VENDOR) );
    if (vendor == "Nvidia Corporation") {
        // Generate a GSdx.ini that uses the OpenGL hardware renderer
    } else {
        // Generate a GSdx.ini that uses the D3D11 hardware renderer
    }

    // rest of the wizard code
````

**Comment by mirhl** [comment]
Shouldn't OGL check also control if we have 3.2?
>  // Generate a GSdx.ini that uses the D3D11 hardware renderer

And I'd replace this with another [check](http://stackoverflow.com/questions/29826036/how-to-determine-the-system-directx-is-11-or-11-1) for D3D_FEATURE_LEVEL_11_0 (*else* good old evergreen D3D9)

**Comment by Sarania** [comment]
I definitely support changing things away from DX9. Basically my thoughts are:

If we can do a good auto selection, then do that. DX11 for modern AMD and Intel, OGL for modern Nvidia, DX9 for really old crap.

If we can't do a good auto selection then DX11. I am making the new voiced config guide soon and I will have a part explaining about which renderer to use on what hardware so that will help nvidia doods know what to use.

**Comment by ramapcsx2** [comment]
I would like to delay any auto configuration for now.
There are 2 dangling issues with the current ideas:
- relying on vendor strings that can change over time
- The AMD OpenGL driver might improve and make the differentiation obsolete.

For the time we should default to DX11 and fall back to DX9 on unsupported hardware.
The config guides should mention that there's an improved OpenGL renderer available and recommended on cards that well support it. That means Nvidia cards and probably fast AMD cards as well.

**Comment by willkuer** [comment]
> For the time we should default to DX11 and fall back to DX9 on unsupported hardware.

So delay or implement this suggestion?

**Comment by mirhl** [comment]
> relying on vendor strings that can change over time

So.. wouldn't it just fallback to DX11 regardless?

**Comment by ssakash** [comment]
#1284 now properly does the check for Direct3D level on the dialog. If your GPU supports D3D11 then the dialog will initialize with D3D11 as the initial renderer else, it falls back to D3D10. if it doesn't even support D3D10 then it'll finally fall back to D3D9. 

Unfortunately, I'm not sure where it'd be ideal to default to OpenGL. opinions are appreciated.

**Comment by mirh** [comment]
Either you check for nvidia and set opengl, or check for intel and amd and fallback to dx path I guess. 
It all depends on whether we want opengl or directx default for "others",

**Comment by ssakash** [comment]
> Either you check for nvidia and set opengl, or check for intel and amd and fallback to dx path I guess.

https://github.com/PCSX2/pcsx2/pull/1384 now checks for Nvidia's Vendor ID and sets OpenGL as the default renderer. (but only for cards with at least DX11 Support, check the comment [here](https://github.com/PCSX2/pcsx2/pull/1384/files#diff-2e3cb05a216dedd48ed473a62719708eR324)

**Comment by mirh** [comment]
I'm just wondering if a "blacklist" approach couldn't be more *orthodox*. 
Like `desc.VendorId != 1002 && desc.VendorId !=8086`

And pre nvidia OGL 4 cards, correctly fall back to dx10 or dx9, should it be the case?

**Comment by ssakash** [comment]
> I'm just wondering if a "blacklist" approach couldn't be more orthodox.
Like desc.VendorId != 1002 && desc.VendorId !=8086

I don't see the merit on black listing instead of just explicitly checking for Nvidia vendor ID. I prefer the latter since code is better and more readable.

> And pre nvidia OGL 4 cards, correctly fall back to dx10 or dx9, should it be the case?

Yes, currently that's the case.

**Comment by mirh** [comment]
> I don't see the merit on black listing instead of just explicitly checking for Nvidia vendor ID. I prefer the latter since code is better and more readable.

? I don't see why two != instead of a single == would be less readable. 
My -kind of philosophical- issue is that technically it's AMD and Intel that sucks, not nvidia doing anything special.

**Comment by FlatOutPS2** [comment]
Technically, the two not cases is better. If there are or will be any other vendors that release OGL4+ supporting GPU's they will be automatically accepted, unlike the current situation. The current code does look neater, and if there aren't any Venders known to be developing those GPU's there's little sense in changing it.

**Comment by mirh** [comment]
Would have preferred the default opengl with blacklist approach (rather than default directx with opengl whitelist) but whatever.
