### ISSUE TITLE
I don't see PCSX2-linux.sh as necessary

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1041]
I'm not not quite following or seeing the point to this script, other then the GL optimizations for an Nvidia user.

It states in the script the purpose is to launch PCSX2 from the same repository every time, because there is no guarantee on the directory when PCSX2 is launched from a shortcut.

How can there be no guarantee with a shortcut? That would be user error. ```ln -s``` is pretty straight forward and works, and I've never seen shortcuts created as ```Launchers``` in Desktop Enviroments fail.

Sorry am I missing something here?

I read or was told in the past that the ```3rdparty``` directory is not needed in Linux, so I remove it at build time.

So this line then seems of no benefit;

MY_LD_LIBRARY_PATH=${MY_LD_LIBRARY_PATH:+$MY_LD_LIBRARY_PATH:}$DIR/3rdPartyLibs

Next, what if we are using wx3? Because this next line seems to be for wx2? I also don't have ```STL``` support compiled in wxgtk.

MY_LD_LIBRARY_PATH=${MY_LD_LIBRARY_PATH:+$MY_LD_LIBRARY_PATH:}/usr/lib/wx-2.8-stl

Don't misunderstand me, I appreciate anything being done here to help the end-user. 

If I can make a suggestion, I would suggest that some sort of README be created specifically for this purpose of startups help or optimizations added to the /usr/doc, rather then just creating a script, and having it installed into the system. I saw this installed into /usr/bin after I compiled, packaged and installed PCSX2.

**Comment by Geyup** [comment]
If I want to run only the GL optimization on the CLI, this is correct?

```
LD_LIBRARY_PATH="/usr/lib" __GL_THREADED_OPTIMIZATIONS=1 /usr/bin/32/PCSX2 "$@"
```

thank you

**Comment by gregory38** [comment]
```I don't see PCSX2-linux.sh as necessary``` So ?

```
option(DISABLE_PCSX2_WRAPPER "Disable including the PCSX2-linux.sh file")
```

What do you want to achieve exactly? Distribute a package? There is a .desktop/menu file to execute PCSX2 properly.

```
If I can make a suggestion, I would suggest that some sort of README be created specifically for this purpose of startups help or optimizations added to the /usr/doc, rather then just creating a script, and having it installed into the system. I saw this installed into /usr/bin after I compiled, packaged and installed PCSX2.
```
Are you aware that 100% (minus you) of my user just want to play their PS2 game, not read a hundred of doc file to fire the program ;)

**Comment by Geyup** [comment]
You're not being completly honest and I know better, been a Slackware geek for over 15 years and I know many other distros out there that compile from source PCSX2, so either the end-user deals with it, or a pkg maintainer for the distro. I'm not the only one. :) But nice try, trying to weed me out, LOL...

Thanks, wasn't sure if you had an option to disable it at compile time. :)

DISABLE_PCSX2_WRAPPER

As I was asking before, this works from the CLI to launch? 

```
LD_LIBRARY_PATH="/usr/lib" __GL_THREADED_OPTIMIZATIONS=1 /usr/bin/32/PCSX2 "$@"
```
It seems to work for me, just want to make sure?

Thank you very much for your time gregory38, it's grealtly appreciated!

Keep up the good work!

**Comment by gregory38** [comment]
Your command line seems to be good. LD_LIBRARY_PATH is useless (linker default normally).

**Comment by Geyup** [comment]
Linker default? Sorry I'm lost at the moment, can you please show me how you'd run it?

thank you

**Comment by gregory38** [comment]
```
 how you'd run it?
```
=> PCSX2-linux.sh  ;)

Anyway, your command is fine. Don't understand why you don't use PCSX2.desktop file.

**Comment by Geyup** [comment]
I use Openbox, and to be honest not sure it launches them from the menu, I've never played with it.

But I see in the desktop file it's excuted like below, so I can just run that from the CLI too?

```env __GL_THREADED_OPTIMIZATIONS=1 PCSX2```

thank you again for your time, greatly appreciated!

**Comment by Geyup** [comment]
This is how my Openbox menu.xml looks from before

```
<item label="PCSX2" icon="/home/foo/.icons/AwOken/clear/128x128/apps/pcsx2.png">
    <action name="Execute">
      <command>PCSX2</command>
      <startupnotify>
        <enabled>yes</enabled>
      </startupnotify>
    </action>
  </item>
```

**Comment by gregory38** [comment]
From CLI you can use
```
__GL_THREADED_OPTIMIZATIONS=1 PCSX2
```
You menu file will work but slower on Nvidia driver.

**Comment by Geyup** [comment]
I'll change it;

```<command>__GL_THREADED_OPTIMIZATIONS=1 PCSX2</command>```

thank you gregory38, much appreciated!

**Comment by Geyup** [comment]
Actually you have to make it this in Openbox;

```env __GL_THREADED_OPTIMIZATIONS=1 PCSX2```
