### ISSUE TITLE
[BUG]: Karaoke Revolution Series - Unable to Persist System Data to Memory Card

### ISSUE THREAD

**Issue by JWatersMeet** [PCSX2/pcsx2#10413]
### Describe the Bug

When starting any of the Karaoke Revolution series games, I am asked at start-up to create the system data on the memory card. I am unable to do this, it continusly asks for the data to be recreated in a loop. Please see the video below.
I don't believe this is related to the recent memory card changes as this has been happening for as long as I can remember,
All other games store to the same memory card without issue, and the card has enough free space. When checking the card via the PS2 bios, the Karaoke Revolution data isn't present.

https://github.com/PCSX2/pcsx2/assets/136824455/c7dfe8ce-def0-4727-9a6a-41bd9ed1233b

### Reproduction Steps

1. Start any of the Karaoke Revolution titles - I would suggest Karaoke Revolution JPop Best 1 (SLPM-62369)
2. Press OK when asked to create the system data.
3. Get stuck in a loop of being asked to create the system data.

### Expected Behavior

1. Start any of the Karaoke Revolution titles - I would suggest Karaoke Revolution JPop Best 1 (SLPM-62369)
2. Press OK when asked to create the system data.
3. System data is created and not asked for again.

### PCSX2 Revision

1.7.5296

### Operating System

Windows 11

**Comment by RedPanda4552** [comment]
Seeing a lot of stuff flooding over DECI2, but it specifically shows sceMcChDir failing with status -4.

**Comment by RedPanda4552** [comment]
Replicated on hardware, not an emulation bug.
