### ISSUE TITLE
[BUG]: Vulkan Doesn't Support my Graphics Card Now?

### ISSUE THREAD

**Issue by ZHassanQ** [PCSX2/pcsx2#10426]
### Describe the Bug

Previously (A long time you can say) when I use PCSX2 I always use vulkan for my GTX 1650, now when I use vulkan it shows “(default)” without an option to change it, and when I try to launch a game it just crash and says “Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated.” then it says “No physical devices found. Does your GPU and/or driver support vulkan?”

Note: My driver is up-to-date, Windows is also up-to-date.

### Reproduction Steps

Use vulkan and launch any game.

### Expected Behavior

Game launching perfectly using vulkan as a renderer with my GPU

### PCSX2 Revision

v1.7.5303

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Please use the Discord for support issues.

**Comment by ZHassanQ** [comment]
> Please use the Discord for support issues.

Okay.
