### ISSUE TITLE
Question: English only compile no languages installed?

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1042]
Is there a compile flag option I can use at build time to not compile/install the languages? 

thank you

**Comment by gregory38** [comment]
It would be nice to keep a single issue or open a forum thread.

What is your issue exactly ?
```
# generation .po based on src  : -DCMAKE_BUILD_PO=TRUE|FALSE
```

**Comment by Geyup** [comment]
Sorry gregory38 for all the posts, I just wanted English only...

thank you for your time.

**Comment by Geyup** [comment]
I added to my build script, ```-DCMAKE_BUILD_PO=FALSE``` but it still built and installed the languages .

**Comment by gregory38** [comment]
Hum, well it is possible that I force the build for release mode. What is the issue to install the mo file, I mean a translated gui is much nicer.

**Comment by Geyup** [comment]
I only want English and no locales...

Hmm this can't be just set as an option?

option(CMAKE_BUILD_PO 



thank you

**Comment by gregory38** [comment]
There are already too much option for useless stuff (seriously a couple of files won't kill a computer). As a side note, if you plan to build PCSX2 for yourself only, it could be handy to build it as a portable build instead (not package mode).
Anyway, just remove the local directory, 99% of chance that it will work.

**Comment by Geyup** [comment]
I've been removing the local directory, it would just be nice if there was an option to not enable at build time...

thank you for your time

**Comment by gregory38** [comment]
We already have too much options. I'm against to create additional option for each files of the projects in order to save nothing.

**Comment by Geyup** [comment]
Yes I understand, just thought the source had a flag to not install...
