### ISSUE TITLE
[Feature Request]: PlayStation Theme

### ISSUE THREAD

**Issue by NotAGanesh** [PCSX2/pcsx2#10436]
### Description

a Theme For PCSX2 Nightly
PS4/5 Style Theme 
![PCSX2 PlayStation Mode compress file](https://github.com/PCSX2/pcsx2/assets/105713980/d64c5219-86bb-45d5-9142-7e24c4ce42b0)

### Reason

Need More Themes for PCSX2 Nighly

### Examples

In concept art you can see PlayStation Theme

**Comment by refractionpcsx2** [comment]
Sorry, we're not redesigning the UI again.  There are colour schemes in PCSX2 already for PS2 style, and you can make a custom style should you want different colours

**Comment by NotAGanesh** [comment]
> Sorry, we're not redesigning the UI again. There are colour schemes in PCSX2 already for PS2 style, and you can make a custom style should you want different colours

Ok but Please add more themes

**Comment by refractionpcsx2** [comment]
There's already 12 lol
