### ISSUE TITLE
Keep Main Window Title Bar Name Consistent with Root Folder Name

### ISSUE THREAD

**Issue by DPersonalized** [PCSX2/pcsx2#1043]
Currently, the name used for PCSX2's title bar is **much** different to the name of the root folder. This is what I mean:

Folder: pcsx2-v1.3.1-1538-gd3ec74b-windows-x86
Title: PCSX2 1.3.1-20151211085228

I would be very grateful if the name for the title bar could be changed to that of the root folder, since it's basically impossible to tell which version I'm currently using. 

Something like this would be preferable - at least for me, anyway:

PCSX2 1.3.1-1538-gd3ec74b (capitalized and no OS name)

**Comment by Ryudo300** [comment]
Agreed. I actually name it exactly like you did except without the additional code at the end of it.
"PCSX2 GIT 1.3.1-1478" is what I use. (Since I have some older versions labeled as SVN)

**Comment by DPersonalized** [comment]
I'm bumping this to say that another good reason for this change is that the current title names are so long, they don't even fit in the title bar.

![longtitle](https://cloud.githubusercontent.com/assets/8225831/17335217/1522b358-58d1-11e6-8747-4efee31f6606.png)

Here's how short they could actually be:
![shorttitle](https://cloud.githubusercontent.com/assets/8225831/17335258/3cdf5108-58d1-11e6-8990-7202d10c92c3.png)

So not only would this shorten the title significantly, but it would also allow it to be consistent with the root folder name at the same time. 

The "Git" part isn't necessary, since it can be assumed that all development versions after around 1.0.0 are from Git and not SVN. It can also be assumed that all builds with the extra four digits are development versions and not stable versions.

**Comment by gregory38** [comment]
So date is kind of useless, so I will update to add the hash version instead. However I don't know how to get builldbot internal counter (not sure it can be done)

**Comment by FlatOutPS2** [comment]
The timestamp is useless, the date can be help, even though it's partially hidden due to the timestamp.

**Comment by gregory38** [comment]
date of the commit ? So far I'm heading to the following
```
% git describe 
v1.5.0-dev-1574-g5b3dfc3
```

**Comment by gregory38** [comment]
Could someone test the PR #1655 Thanks you.
