### ISSUE TITLE
[BUG]: Slow motion doesn't work

### ISSUE THREAD

**Issue by TrentynplayzYT** [PCSX2/pcsx2#10438]
### Describe the Bug

Slow-Motion speed doesn't work, no matter what hotkey i bind it to.

### Reproduction Steps

Press your current bind for "Slow Motion Speed", if it is under 100%, it will not work.

### Expected Behavior

Press the binded key/key combination and it slows the game down to the setting you choose.

### PCSX2 Revision

1.7.5312

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
Works correctly here.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/994ef16a-faba-4058-9717-f93df5e74de3)

**Comment by stenzek** [comment]
You're probably using achievements hardcore mode, which inhibits slowdown to prevent "cheating".

**Comment by TrentynplayzYT** [comment]
thanks, works now.
