### ISSUE TITLE
weird UI issues: missing menu items, menu items with missing/broken text

### ISSUE THREAD

**Issue by majewsky** [PCSX2/pcsx2#1045]
Best illustrated with a screenshot:

![screen23](https://cloud.githubusercontent.com/assets/24696/11906927/75c3495c-a5d0-11e5-8269-86eadf006112.png)

I can still launch the ISO that I had already selected and that seems to work as before, but I cannot make any configuration changes because that menu is missing.

The time when the error started occurring correlates storngly with an [update of the C++ ABI in Arch Linux](https://www.archlinux.org/news/c-abi-change/) and, most likely due to that, an upgrade of the pcsx2 package:

```
$ grep pcsx2 /var/log/pacman.log
[2015-11-27 20:31] [PACMAN] Running 'pacman -S pcsx2'
[2015-11-27 20:31] [ALPM] installed pcsx2 (1.3.1-5)
[2015-12-11 22:52] [ALPM] upgraded pcsx2 (1.3.1-5 -> 1.3.1-6)
```

I have a strong feeling that this is related, but maybe you have some additional insight on why this error manifests. The downstream bug is at https://bugs.archlinux.org/task/47356

**Comment by turtleli** [comment]
Commit f1cb2cfa35efc68ce4443d6ed5633c17c2b9309a fixes this issue.

It's probably best to use pcsx2-git from AUR for now - we're nearing a 1.4.0 release so we could do with additional testing, and 1.3.1 isn't an actual release, the 1.3.1 tag was added to test the Windows buildbot.

**Comment by avih** [comment]
> the 1.3.1 tag was added to test the Windows buildbot.

Nope, it was changed to 1.3.1 to sync up the version numbers between the git tag, the buildbot and the window title of pcsx2 itself.

This is because the previous tag/title were not synced correctly.

Next time we update the version, do remember to also update the tag ;)

**Comment by gregory38** [comment]
The issue is that people don't understand that 1.3.x aren't stable release. If we create a 1.5 tag when we fork, I'm nearly sure they will use it instead of the 1.4. (which remind me that I need to bump the version to 1.5).
