### ISSUE TITLE
[BUG]: Bloom Ghosting When Upscaling - Disney-Pixar Cars

### ISSUE THREAD

**Issue by tangomike99** [PCSX2/pcsx2#10451]
### Describe the Bug

When upscaling, the bloom effect around bright lights and neon at night is no longer a soft effect. Instead, ghosting appears in all directions around the lights.

### Reproduction Steps

1. Ensure that upscaling is enabled within PCSX2.
2. Load into Cars during night sequences. Within Radiator Springs, pay attention to the city neon.

### PCSX2 Revision

v1.7.5317

### Operating System

Windows 10 (64bit)

### CPU

 i7-2600K

### GPU

GTX 1070Ti

### GS Settings

I have tried various hardware hacks, including half-pixel offset, round sprite, and texture offsets. None of these settings make enough of an impact to correct or work around the issue.

### GS Window Screenshots

Here is a screenshot at 4x native:
![Disney-Pixar's Cars_SLUS-21151_20231222160854](https://github.com/PCSX2/pcsx2/assets/78033856/1d66ac7e-7f76-4478-81c7-bb21c10f8e23)

### Logs & Dumps

[Disney-Pixar's Cars_SLUS-21151.zip](https://github.com/PCSX2/pcsx2/files/13756810/Disney-Pixar.s.Cars_SLUS-21151.zip)

**Comment by tangomike99** [comment]
Here is a screenshot at native, for comparison.
![Screenshot 2023-12-22 162704](https://github.com/PCSX2/pcsx2/assets/78033856/f015ed54-3c39-4b54-8398-44189761fa00)

**Comment by JordanTheToaster** [comment]
**We do not accept issues relating to upscaling at this time**

**Comment by Mrlinkwii** [comment]
as mentioned when  making the issue your notified  , We do not accept issues relating to upscaling at this time as mentioned by @JordanTheToaster  , id advise either asking on the discord or on the forums for help :)
