### ISSUE TITLE
[Feature Request]: Add support for Preproduction discs with Wibu-Box USB Security Dongle protection

### ISSUE THREAD

**Issue by 7Seventy7** [PCSX2/pcsx2#10453]
### Description

Many PS2 preproduction DVD-Rs/CD-Rs shipped with Wibu-Box USB Security Dongle protection. People are hacking the roms so that the beta dumps will work on PCSX2.

### Reason

There are a few reasons why it would be ideal for PCSX2 to add support for Wibu-Box USB Security Dongle protection games.

- Simplicity: Instead of having to hack every disc image with this type of protection, it would be more efficient to build in support on an emulator level.
- Preservation: As a video game preservationist (buzzword!) I've datted many betas at Redump and No-Intro. Having multiple versions of roms floating around can lead to confusion and duplication. Also it would be nice if a 'pure' rom would just work with the emulator straight away.
- Avoiding future confusion: Many people who have such beta discs may dump them, expecting them to work on PCSX2, and throw the discs away / getting rid of them when they don't work. Additionally, not everyone who has beta discs has the expertise (or even knows where to look) to figure out how to hack such games.

### Examples

You can find examples of Wibu protected pre-patched roms and patches by searching "wibu" in hiddenpalace.org's website.

**Comment by refractionpcsx2** [comment]
We have no real interest in supporting prototypes directly as the likelyhood that they are just pirated materials is very high, as you proved in your OP by linking to the download site, so I'm gonna say no to this.

**Comment by 7Seventy7** [comment]
? You can easily buy betas on ebay every day of the week.
There are literally dozens if not hundreds listed at any moment. They're not so rare that only pirates have them.
But I guess you've made your decision and a lot of unique game builds will be unplayable via emulation.
