### ISSUE TITLE
[BUG]: Screen tearing while scrolling roms list

### ISSUE THREAD

**Issue by Androxilogin** [PCSX2/pcsx2#10460]
### Describe the Bug

While scrolling the rom list in game grid mode I get screen tearing. Is there a fix for this?

### Reproduction Steps

Scroll the list in game grid mode.

### Expected Behavior

Smooth, clear picture while scrolling.

### PCSX2 Revision

1.7.5327

### Operating System

Windows 10 (64bit)

### Logs & Dumps

That's really all there is to it.

**Comment by stenzek** [comment]
Running non-vsynced is not a bug. The issue tracker is not for support, please use Discord/the forums.
