### ISSUE TITLE
[BUG]: Latest version does not recognize at least PS4-PS5 controllers  anymore

### ISSUE THREAD

**Issue by LucianoGarciaPanero** [PCSX2/pcsx2#10467]
### Describe the Bug

The app no longer recognizes neither my PS5 controller nor a virtual simulated (dsx) PS4 controller. I downgraded to the app version that i was using yesterday [v1.7.5323](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5323) and the problem was fixed. Skimming through the lastest releases maybe https://github.com/PCSX2/pcsx2/pull/10459 ([v1.7.5329](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5329)) is the culprit, but i dont know

### Reproduction Steps

1 -> Download latest pcsx2 release
2 -> Connect PS4-PS5 controller
2 -> Play a previous controller working game or just go to settings and try to rebind -> nothing will happen

### Expected Behavior

Controller working

### PCSX2 Revision

v1.7.5332

### Operating System

Windows 10 (64bit)

**Comment by LucianoGarciaPanero** [comment]
No, the only one that i have is the one that you said in resources

**Comment by refractionpcsx2** [comment]
okay, can you please post your emulog after starting the emulator.  if you go to tools->enable file logging, then shut down the emu and reopen it, then close it again and upload the `emulog.txt` from the logs folder.

**Comment by bigol83** [comment]
I use a ds4 and i have no issues with latest build

**Comment by LucianoGarciaPanero** [comment]
I updated the emulator again and now it recognized the ps5 controller... First time that this happened in a long time so i thought it was a bug, my bad.

Sorry for the inconvenience
