### ISSUE TITLE
[BUG]: The Suffering - Emulation hang when loading level 

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#10472]
### Describe the Bug

Game crashes during loading screen of "An Eye for an Eye Makes The Whole World Blind" . Tested back to at least 0.9.4, appears to have never worked properly. Rounding/clamping and interpreters do not affect issue.

### Reproduction Steps

Load memory card into "Surfacing" level. Turn right into hallway and proceed towards the back of the room(if you are headed in the right direction, there is short meeting with an "electric man" who disappears). Head down a long hallway and turn left until you see a door at the end. Upon confirming, loading screen will appear and TLB miss.

### Expected Behavior

Game will load without crashing.

### PCSX2 Revision

v1.7.5336

### Operating System

Windows 11

### CPU

Ryzen 7900X

### GPU

RTX 4090

### GS Settings

Defaults

### Emulation Settings

Defaults

### GS Window Screenshots

Final door/hallway before loading screen
![The Suffering_SLUS-20636_20231225120448](https://github.com/PCSX2/pcsx2/assets/16314399/fd5623cc-c560-41f0-b702-0bb597da4932)

Loading screen crash:
![The Suffering_SLUS-20636_20231225120619](https://github.com/PCSX2/pcsx2/assets/16314399/0d1b7f1b-c355-4fb7-baa1-c84247f1ef5b)

### Logs & Dumps

Debugger screenshot:
![image](https://github.com/PCSX2/pcsx2/assets/16314399/581aa6b1-18d0-4eb8-98ca-aca4e3cce5d4)

Memory card (rename to .ps2)
[thesuffering.zip](https://github.com/PCSX2/pcsx2/files/13766847/thesuffering.zip)

**Comment by prafullpcsx2** [comment]
Are you sure the memory card save isn't corrupted by some cheats/patch? I am asking this because there are videos of PCSX2 available on youtube with that level loading perfectly fine.

**Comment by Buzzardsoul** [comment]
Only one way to find out. We have to test this save on an actual PS2.

**Comment by Buzzardsoul** [comment]
I tested this on my PS2 with this save and have replicated the issue. Your savedata is likely corrupted.

**Comment by refractionpcsx2** [comment]
Thanks for testing!

**Comment by Buzzardsoul** [comment]
> > I tested this on my PS2 with this save and have replicated the issue. Your savedata is likely corrupted.
> 
> @Buzzardsoul
> 
> I appreciate your efforts in testing the game. I believe the save file shared above is indeed mine. I have not used any cheats or modifications, and my PCSX2 installation is mostly unmodified. Therefore, I am confident that the save file itself is not corrupt.
> 
> I have also tested the save file on my PS2 using OPL, and I encountered the same issue there. OPL also froze on the loading screen. This suggests that the problem may lie with OPL as well, not just PCSX2.
> 
> Regarding the gameplay videos of the game running in PCSX2 on YouTube, it is possible that they used a different region of the game. I tried testing the game with a different region, but the save file was not compatible.
> 
> I hope this information is helpful in identifying the source of the issue.

Savedata corruption can come as a result of many things. For instance, PCSX2's timing is nowhere near perfect and could potentially lead to data corruption. Likewise with normal gameplays. This issue could possibly be a result of a glitch going unnoticed by its developers during the time the game was being developed.
