### ISSUE TITLE
[BUG]: Ace Combat Zero - Text Messages for Hit/Destroy/Miss are only empty boxes

### ISSUE THREAD

**Issue by TytusDeZoo3123** [PCSX2/pcsx2#10489]
### Describe the Bug

The game worked very smoothly and with zero issues when I first played it, however one of the nightly updates introduced an issue - whenever I launch a missile and a green/red box pops up telling me if it was a hit/destruction/miss it only displays an empty green/red rectangle with no text, also I've had an issue where the whole emulator froze completely while a missile was chasing an enemy plane, which didn't happen before. The only way I managed to fix the game was running in software mode, which is obviously not ideal.

### Reproduction Steps

Simply play any mission on any rendered except software mode and shoot at any target - the box that pops up will be empty with no notification about hit/miss

### Expected Behavior

After firing at a target you should be notified if it was a straight hit or a miss, not shown an empty green/red rectangle

### PCSX2 Revision

v1.7.5345

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5 9300H @ 2.40GHz

### GPU

3071MB NVIDIA GeForce GTX 1050 (Lenovo)

### Emulation Settings

Nothing special aside from 1080p resolution (when not using software renderer), antialiasing, vsync and blending set to high like the emulator suggested

**Comment by Buzzardsoul** [comment]
Can you upload a GS dump? You can find the option to dump at the end of the 'Tools' tab.

**Comment by refractionpcsx2** [comment]
Couldn't reproduce this, but I did get another bug which I caused recently, so I'm fixing that.

**Comment by refractionpcsx2** [comment]
Can you try #10490 ?

**Comment by TytusDeZoo3123** [comment]
Well the bug is gone now but now there's a new issue when there's this black texture glitching thats happening with the ground texture right from the first mission

**Comment by lightningterror** [comment]
Can you upload a gsdump?

**Comment by refractionpcsx2** [comment]
> Well the bug is gone now but now there's a new issue when there's this black texture glitching thats happening with the ground texture right from the first mission

That's what my PR was fixing :/

**Comment by refractionpcsx2** [comment]
Well, I think I found the actual bug, can you try that PR again, it should be okay now
