### ISSUE TITLE
[Feature Request]: Hotkeys to increase/decrease analog sensitivity

### ISSUE THREAD

**Issue by GrimPixel** [PCSX2/pcsx2#10481]
### Description

Add hotkey assignment options to change analog sensitivity by ±1%, ±5%, ±25%.

### Reason

It is convenient.

### Examples

I don't know which “other software” has it.

**Comment by stenzek** [comment]
Sorry, not really possible with the controller system design. Sensitivity is an attribute/property of the controller type, not all controllers have it, therefore it is not exposed in a generic way.

Also pretty niche. We'd have a hotkeys list a mile long if we accommodated all of these.
