### ISSUE TITLE
[Feature Request]: Debugger: Force to use Equals search comparisons for search type Array of byte and String

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#10480]
### Description

I want PCSX2 to force Equals search comparison and to gray out search comparison box while Array of byte or String is selected.

Example of my idea:
1. Select "Not Equals" as search comparison
2. Select "String" as search type
   - Then immediately search comparison box gets grayed out, but "Not Equals" remains shown
   - Now user can search for String with Equals comparison
3. Select "Double" as search type
   - Then immediately search comparison box gets activated as "Not Equals" (previous selected search comparison)

### Reason

I think just internally forcing "Equals" comparison is better than showing this prompt unless other search comparisons are planned for Array of byte and String.

<img width="478" alt="image" src="https://github.com/PCSX2/pcsx2/assets/91955473/feafc828-8a5f-4bb5-a0b5-2da941db0267">

### Examples

Not sure

**Comment by Daniel-McCarthy** [comment]
Just to add some thoughts on here, it does get pretty tricky quickly to handle all the different options to limit/not limit depending on type, and if it's a filter search or a new search, which is why I had kept it as messages that give context for now.

I do intend to add more options for arrays, but only for filter searches. My expectation is that a user has to use equals *only* for an initial search, then for each filter search they should be able to use `changed`/`not changed`/`equals`/`not equals` eventually.

**Comment by Joshua-1248** [comment]
Having the option to search for Unknown Initial Values would be nice to have alongside the changed/unchanged & increased/decreased operators.

It would make code searching much more efficient.

**Comment by Berylskid** [comment]
> I do intend to add more options for arrays, but only for filter searches. My expectation is that a user has to use equals _only_ for an initial search, then for each filter search they should be able to use `changed`/`not changed`/`equals`/`not equals` eventually.

That sounds even better. Then I prefer this request only for initial searches.

**Comment by Risae** [comment]
> Just to add some thoughts on here, it does get pretty tricky quickly to handle all the different options to limit/not limit depending on type, and if it's a filter search or a new search, which is why I had kept it as messages that give context for now.
> 
> I do intend to add more options for arrays, but only for filter searches. My expectation is that a user has to use equals _only_ for an initial search, then for each filter search they should be able to use `changed`/`not changed`/`equals`/`not equals` eventually.

Thank you very much for all of your contributions to the PCSX2 Debugger! It enabled us users (or fan translators) to accomplish so much more!
