### ISSUE TITLE
[Feature Request]: Add Toggle To Mute Emulation Audio In Settings

### ISSUE THREAD

**Issue by Joshua-1248** [PCSX2/pcsx2#10484]
### Description

While PCSX2 does allow you to mute the emulation audio with a vertical volume slider, there is noticeably no tick box present to achieve the same effect.

So essentially;

1. Open PCSX2 settings
2. Navigate to Audio tab
3. To the right where the Volume slider usually is, there could be a tickbox just underneath it with the words "Mute Audio" that you can toggle on and off at will.

### Reason

Makes it more convenient to toggle emulation audio on and off without having to set the volume slider to 0%-100% manually to achieve the same effects.

### Examples

Duckstation has this under it's Audio settings:

![Screenshot from 2023-12-26 15-36-04](https://github.com/PCSX2/pcsx2/assets/64272857/19dc38a1-5d36-4f0c-9785-fc6de5953896)

**Comment by Jakey757** [comment]
PCSX2 has a hotkey you can bind to mute audio, `Toggle Mute`.

**Comment by Mrlinkwii** [comment]
as mentioned this already exists in the hotkey settings 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/ac2f0f40-69b0-456e-aaca-704433691bff)

**Comment by Joshua-1248** [comment]
Ah... Didn't see that.

Will mark this as resolved then.

Thanks for the swift response.
