### ISSUE TITLE
[BUG]: BIOS language other than English

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#10515]
### Describe the Bug

In some games, errors occur when a language other than English is selected in the BIOS. One of them is the Rune: Viking Warlord SLUS-20109. Specifically, it stays on the loading screen in a loop at the beginning right before entering the main menu.
To make sure my BIOS is not corrupted, I used the biosdrain.elf tool again on two PS2 models I have with the same result.

### Reproduction Steps

Enter the BIOS, "System Configuration", select Spanish for example. Shut down and load the game Rune: Viking Warlord SLUS-20109

### PCSX2 Revision

v1.7.5370

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
have you tried this on real hardware,

**Comment by RedDevilus** [comment]
Think it was one of the Tomb Raider games that also crashed if you used the wrong language, instead of normally defaulting to the first language in the index of a game or English or supported BIOS language that overlaps with game (besides English scenarios).

**Comment by Mrlinkwii** [comment]
im asking if it happens on real hardware :/

**Comment by F0bes** [comment]
I can reproduce this on genuine hardware. SCE, I'm offering to replace the QA testers assigned to this game (please this is a cry for help I need the employment)
