### ISSUE TITLE
[Feature Request]: D3D12

### ISSUE THREAD

**Issue by rodrigo1593** [PCSX2/pcsx2#10512]
### Description

allow d3d12 to be disabled using command line arguments like: --nod3d12 :)

### Reason

its simple it will launch pcsx2 without d3d12 dll requirement / without directx 12 forced requirement :)

### Examples

sorry there is no examples :(

**Comment by refractionpcsx2** [comment]
What possible reason would you want this?

**Comment by Mrlinkwii** [comment]
If you mean you want win 7 support that's not gonna happen , qt version pcsx2 uses dosnt support it , I'd advise updating to Linux/win 11

**Comment by refractionpcsx2** [comment]
Oh don't get me wrong, I'm not going to accept this feature request because it's pretty ridiculous, but I'm curious what insane reason came to this request.

**Comment by stenzek** [comment]
If you can provide a legitimate reason that D3D12 shouldn't be linked, then I'm happy to switch to loading it dynamically.

But Win7 or Win8 support is **not a legitimate reason**. We use memory management APIs from Win10 1803+, and Qt6 does not support Win7/Win8 either.

**Comment by rodrigo1593** [comment]
because i saw this.... https://github.com/Darthagnon/pcsx2-win7
sorry for disturb you guys...

**Comment by refractionpcsx2** [comment]
well it will be up to them to remove it, if they're making some hacked up win7 build, not us.

**Comment by stenzek** [comment]
Notice how it's almost 4.000 commits and a year and a half old. It's missing a **lot**, and that was before we used the aforementioned APIs, for a significant speed gain.
