### ISSUE TITLE
[BUG]: (Linux) make install doesn't install anything

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#10517]
### Describe the Bug

I am packaging PCSX2 for openSUSE Linux. It used to succeed but now it fails. `make` works fine. But `make install` doesn't install anything to /usr/

### Reproduction Steps

```
mkdir build
cd build
cmake ..\
  -DCMAKE_INSTALL_PREFIX=/home/abuild/rpmbuild/BUILDROOT/pcsx2-1.7.5371~git20231231/ \
  -DCMAKE_BUILD_TYPE=Release \
  -DUSE_LEGACY_USER_DIRECTORY=ON \
  -DUSER_CMAKE_C_FLAGS="-Wno-narrowing" \
  -DUSER_CMAKE_CXX_FLAGS="-Wno-narrowing" \
  -DXDG_STD=ON \
  -DPACKAGE_MODE=ON \
  -DDISABLE_ADVANCE_SIMD=ON \
  -DPLUGIN_DIR="/usr/lib/pcsx2" \
  -DGAMEINDEX_DIR="/usr/share/pcsx2" \
  -DGLSL_SHADER_DIR="/usr/share/pcsx2" \
  -DDOC_DIR="/usr/share/doc/pcsx2"
make
make install
```

### Expected Behavior

Files should be installed

### PCSX2 Revision

1.7.5371

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

openSUSE Tumbleweed

**Comment by stenzek** [comment]
Working as intended. These packaging options have long since been removed, PCSX2 only supports self-contained builds, since system-wide installs create all kinds of issues (resource conflicts between builds, etc).
