### ISSUE TITLE
[BUG]: Ethernet Device not selectable. PCAP not available under Ethernet Device Type since V 1.7.5327

### ISSUE THREAD

**Issue by Kilrgrn** [PCSX2/pcsx2#10520]
### Describe the Bug

Downloaded newest nightly (v1.7.5376) as instructed on PCSX2 Discord. Issue persists. 

Unable to choose an `Ethernet Device`. Only two choices are `TAP` and `Sockets`

Image1 is v 1.7.5324
Image2 and 3 are v1.7.5376
![image1](https://github.com/PCSX2/pcsx2/assets/108644709/e8119ca5-9870-4ace-a2cf-10f9b9d44516)
![image2](https://github.com/PCSX2/pcsx2/assets/108644709/9978da14-1269-432b-81e5-348467cc3233)
![image3](https://github.com/PCSX2/pcsx2/assets/108644709/967d6505-8523-4146-8384-b2d74245ab37)

### Reproduction Steps

Downloading to the latest nightly build since V 1.7.5327.

### Expected Behavior

Being able to select a different `Ethernet Device`.
Being able to see and choose PCAP Bridged and PCAP Switched.

### PCSX2 Revision

v1.7.5376

### Operating System

Windows 10 (64bit)

**Comment by weirdbeardgame** [comment]
If that's in Linux you cannot use AppImage or Flatpak. You have to compile or use a package. It's an issue with permissions. Also the GitHub is not a support form, please ask on the discord for support

**Comment by weirdbeardgame** [comment]
Are you running it as admin? It could be an odd windows permission thing

**Comment by Kilrgrn** [comment]
> Are you running it as admin? It could be an odd windows permission thing
I was not at the time. Let me try that real fast and report back.

**Comment by Kilrgrn** [comment]
Unfortunately launching as admin did not correct the issue.

**Comment by forrvalhalla** [comment]
Issue caused by #10448 (1.7.5327)
