### ISSUE TITLE
[Feature Request]: Show Widescreen patches as Enabled in ''Patches'' if they are Enabled

### ISSUE THREAD

**Issue by mrtawsiti3** [PCSX2/pcsx2#10528]
### Description

When you Enable Widescreen Patches, Global or Game setting (i tested only with game setting, i assume its the same for global setting), Widescreen 16:9 patch appears in ''Patches'' category and it shows it as unticked (disabled), even tho in game the patch is activated.

Ticking this option ON or OFF in ''Patches'' category does nothing. Patch stays activated cuz of the Game/Global setting for Widescreen patches is being set to enabled.

Solution i had in mind:
Gray out this ''Widescreen 16:9'' patch when Enable Widescreen Patches is ON so user can not tick/untick it and make it shows as ticked so user knows that it is activated/enabled for sure.

### Reason

correctness, less confusion, more control and more polished QT for users.

### Examples

![gow2 patches](https://github.com/PCSX2/pcsx2/assets/35630219/132002ec-7c2e-4398-81f7-6360cd5d8810)
![gow2 p](https://github.com/PCSX2/pcsx2/assets/35630219/3acdd0ca-6073-4df6-8127-6a1caa09cf75)

**Comment by stenzek** [comment]
The two settings are completely unrelated UI-wise from one another, so not really doable.

Personally, I'd advocate for removing the WS/NI toggle from game settings entirely.

**Comment by kamfretoz** [comment]
Honestly, having a global toggle for WS/NI patches is just asking for disasters. Since patches are meant to be explicitly enabled per-game.

**Comment by Daniel-McCarthy** [comment]
It does add a bit of unneeded complexity both in the handling of patches (auto-detection/enabling of them) and on the UI of handling them.

It's not much to have the user enable them, and also at least partially decouples the idea that we're responsible for Widescreen to work as a standard feature/universal setting, rather than just a patch we supply and it works or it doesn't/mileage varies.

**Comment by stenzek** [comment]
The global toggle is fine imo, just the per-game one that needs to go.

**Comment by refractionpcsx2** [comment]
If we remove the per-game options for enabling widescreen/no interlacing (and probably cheats too?), then the patches/cheats screens are going to need tri-state check boxes, as right now there's no way to explicitly disable patches if global is on, apart from those current global overrides, but this is going to suck if somebody wants widescreen/no interlace enabled on all games when available, but the patch is broken for 1 game and they can't disable it.

**Comment by BParks21** [comment]
I think the tri-state would be the best solution honestly. Look forward to seeing it happen.
