### ISSUE TITLE
Metal Slug 3 analog controls not working

### ISSUE THREAD

**Issue by VermeilChan** [PCSX2/pcsx2#10539]
### Describe the Bug

The left analog stick does not control character movement in Metal Slug 3

### Reproduction Steps

Launch Metal Slug 3.
Wait for the title screen to appear.
Click the Start button.
Select Arcade Mission.
Choose a character.
Once in-game, try to use the left analog stick to move the character.

### Expected Behavior

The character should move in response to the left analog stick's input.

### PCSX2 Revision

v1.7.5384

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 3 3200G

### GPU

AMD Radeon(TM) Vega 8 Graphics

**Comment by Mrlinkwii** [comment]
Dose the game support analog  sticks on real hardware?

**Comment by refractionpcsx2** [comment]
I'm pretty sure it doesn't.

**Comment by refractionpcsx2** [comment]
It's very difficult to find information to support this either way (even the box don't mention analog or digital), however I found this review on Metacritic, not that it's solid proof, but it's the *only* think I've found

![image](https://github.com/PCSX2/pcsx2/assets/6278726/8ee72a9b-0fa5-4a7d-9d75-5e2f306e5bb4)

**Comment by refractionpcsx2** [comment]
Got my solid proof, here's an excerpt from the manual

![image](https://github.com/PCSX2/pcsx2/assets/6278726/cd98d635-7ebc-42f1-bb2b-944fcb7fd458)

**Comment by VermeilChan** [comment]
> Got my solid proof, here's an excerpt from the manual
> 
> ![image](https://private-user-images.githubusercontent.com/6278726/293784705-cd98d635-7ebc-42f1-bb2b-944fcb7fd458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMzQ2NTcsIm5iZiI6MTcwNDIzNDM1NywicGF0aCI6Ii82Mjc4NzI2LzI5Mzc4NDcwNS1jZDk4ZDYzNS03ZWJjLTQyZjEtYmIyYi05NDRmY2I3ZmQ0NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMjIyNTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI0OTZhNGZiY2E0M2QwNDNkZWU1YjdmMTViNzE0MmI4NjNhMDg2YjBjZmQyNTJlNTZjODcxNmU1YjU5MDA0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GfDqQvneSPbypxnax_vt__qMSjV1fZ1D56aH4Deh2VY)

I'm not really sure what that means but it works in v1.6.0

**Comment by Mrlinkwii** [comment]
1.6 is wrong :)

**Comment by refractionpcsx2** [comment]
1.6 hacked how controllers worked, it doesn't surprise me.

**Comment by RedPanda4552** [comment]
1.6 specifically has a hack in it which, if the game never issues a command to elevate the pad out of PS1 digital mode, will forcefully clone your analog inputs and inject them over top of whatever dpad inputs were rightly received. So stating they worked in 1.6 simply reinforces that this is not normal behavior.

If you want to use your analog sticks in a game that does not natively support it, simply map your analog sticks to your dpad, and set an appropriate button deadzone so that slightly tapping the stick does not immediately register as a full press.

**Comment by VermeilChan** [comment]
Okay thanks 👍
