### ISSUE TITLE
GSdx software only options do not gray out when a Hardware renderer is selected

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#1053]
Vice versa works fine (Hardware options grayed out when a software renderer is selected) so for both consistency and usability we should do the same for the software renderer only options.
I believe @ssakash can handle this easily :)

**Comment by rz5** [comment]
Can the height of the GSdx GU be easily changed dynamically in function of which renderer selected?

If so, would it be more desirable to hide the "Hardware Mode Settings" section and shrink the GUI such that it only shows the "Software Mode Settings" section when a SW renderer is chosen?

**Comment by willkuer** [comment]
I think @turtleli just changed that to support users who regularly use f9. Hw and sw renderer are not fixed when you leave the config. Therefore you need to be able to adjust them.

I think the proper behaviour would be to enable hw settings as well on sw renderer selection. Actually i think it was always like that but maybe i dont remember correctly.

**Comment by turtleli** [comment]
Nope, wasn't me. Software mode was like that before I made changes.

> I think the proper behaviour would be to enable hw settings as well on sw renderer selection.

I prefer that too, though that use case is probably smaller. Specifically, I think anything that can be toggled with a hotkey should not have enabled/disabled behaviour, but perhaps that wouldn't be so newbie friendly. Dunno.

**Comment by ssakash** [comment]
I think you're missing an important information here, after a F9 toggle the current renderer isn't recorded at the GSDX plugin settings that means that whenever you change your settings you'll be kicked back to your original renderer ( the one before the initial F9 toggle). so yeah, you can't really change the SW exclusive options and remain back at software mode if you were initially there at hardware mode before the toggle.

> Can the height of the GSdx GU be easily changed dynamically in function of which renderer selected?

 you can change dimension for the elements, I don't think you can do for the dialog itself. for the elements the function was IIRC ``SetWindowsPos(handle to window , x , y , width , height)``

**Comment by ssakash** [comment]
If anyone has a better idea feel free to suggest , I'll be changing the code in parallel.

**Comment by ssakash** [comment]
well #1056 got merged yesterday. so software mode options now get grayed out when using a hardware renderer , any other stuffs left to be added ?
