### ISSUE TITLE
[BUG]: Retroachievements Active Icon Not Showing

### ISSUE THREAD

**Issue by Ouroboros2460** [PCSX2/pcsx2#10557]
### Describe the Bug

Hey guys, I am having an issue with a certain achievement in Retroachievements for Sly 2. Basically the achievement should have a little icon in the bottom right when it is "active", but it does not. But when I pause the emulator and go to Achievements, it does appear under Active correctly. Is it possible the state can get out of sync between these?

I asked about this in Discord and someone suggested that maybe there is a maximum number of Retroachievements overlay elements (there are three leaderboards and then the icon here)?

My settings look like this:
![image](https://github.com/PCSX2/pcsx2/assets/19391901/5588faf0-7926-48bb-9a02-028accfb7776)

Here is what the overlay area looks like:
![image](https://github.com/PCSX2/pcsx2/assets/19391901/9880647d-36ea-4591-a36d-567f075777f8)

Thanks!

### Reproduction Steps

Walk forward in the save state to start the elephant mission

### Expected Behavior

The icon for the active achievement should appear.

### PCSX2 Revision

v1.7.5400

### Operating System

Windows 11

### Logs & Dumps

[Sly2Elephant.zip](https://github.com/PCSX2/pcsx2/files/13847705/Sly2Elephant.zip)

**Comment by stenzek** [comment]
Those are leaderboard trackers, not achievements.

Not all achievements show challenge trackers. Check with RAIntegration, but I suspect this is probably just how the author set things up.

**Comment by Ouroboros2460** [comment]
This is a bug in the RA code; Jamiras is working on a fix. Thanks!
