### ISSUE TITLE
PCSX2 doesn't show games on main screen after choosing directory[BUG]: 

### ISSUE THREAD

**Issue by Deimos715** [PCSX2/pcsx2#10559]
### Describe the Bug

When I choose games directory, PCSX2 doesn't show games there. In terminal, it says:
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation

### Reproduction Steps

1. I press "Add game directory...", choose a directory (e.g. ps2-games) and press "Choose".
2. In the window "Scan Recursively?", I press "Yes".
3. There is a message "No games in supported formats were found".

### PCSX2 Revision

v1.7.5400

### Operating System

Linux (64bit) - Specify distro below
Ubuntu 22.04.3 LTS

**Comment by refractionpcsx2** [comment]
Which distro/version? You didn't fill that information in.

**Comment by Deimos715** [comment]
Updated information

**Comment by Mrlinkwii** [comment]
scanning and adding directories works here  ( also on 22.04.3 )

**Comment by stenzek** [comment]
Those messages are from Qt, and not fatal.

This is a support issue, please use the Discord server/forums.
