### ISSUE TITLE
[BUG]: Gran Turismo 4 (Japanese version) Crash on International B license test.

### ISSUE THREAD

**Issue by gbzinsheikk** [PCSX2/pcsx2#10550]
### Describe the Bug

When trying to load the 5th test on the International B License, during the load the fps massively tanks and after a while the whole PCSX2 application crashes. This was tested on the American and Japanese version of the game, only the Japanese version have this bug.

### Reproduction Steps

Start the game and go to the International B license tests, from there take the 5th test (1 Lap guide run in Costa di Amalfi).

### Expected Behavior

The test should load normally as all the others

### PCSX2 Revision

1.7.5395

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro 

### CPU

AMD Ryzen 7 3700U

### GPU

Radeon Vega Mobile Gfx (8) (integrated graphics)

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/78001245/46922183-c072-4e0c-99a9-815cc1406845)
![image](https://github.com/PCSX2/pcsx2/assets/78001245/2510789d-9907-41d2-af52-a4ba0f11d13d)

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/78001245/39f896b1-f096-49f1-92f4-6966f4dae574)

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/13837854/emulog.txt)

**Comment by stenzek** [comment]
1. What is the backtrace? (it'll print it to the terminal)
2. Appimage or flatpak?
3. Post a memory card so we can reproduce.

**Comment by gbzinsheikk** [comment]
1. [backtrace.txt](https://github.com/PCSX2/pcsx2/files/13837958/backtrace.txt)
2. Tried on both, same issue. 
3. [Mcd001.ps2.zip](https://github.com/PCSX2/pcsx2/files/13837882/Mcd001.ps2.zip)
4. ![image](https://github.com/PCSX2/pcsx2/assets/78001245/0a33d82b-5c41-4738-9cfc-f5f2d44967d9)

**Comment by stenzek** [comment]
1. That screenshot does not show the dump verified.
2. Did you clear game settings? IIRC this is how it used to behave when you forced full EE FPU clamping. You should not override **any** clamping now.

**Comment by gbzinsheikk** [comment]
1. 
![image](https://github.com/PCSX2/pcsx2/assets/78001245/2c828eae-8d86-4bfd-9c94-b9aa79a64f81)
2. The EE clamping is set to normal, but for the sake of testing I've just reset the emulator configs, and the issue persists.

**Comment by XieTieqiang** [comment]
windows x64-v1.7.5396 has the same problem, you need to change the following settings.

Advanced -> Rounding Mode[Nearest], Clamping Mode[Full]

**Comment by gbzinsheikk** [comment]
Doesn't setting clamping mode to full breaks other license tests?

**Comment by stenzek** [comment]
It shouldn't need full clamping anymore. And yes, full used to cause breakage.

I'll have to see what blocks need the higher clamping and see if there's another conservative change that can be made...

**Comment by stenzek** [comment]
Well, this was a can of worms. Forcing nearest rounding for everything, **or** forcing chop for division fixes it. It boils down to the rounding of division going the wrong way in this monstrosity of a function. 

![image](https://github.com/PCSX2/pcsx2/assets/11288319/61a2a5d0-4660-4a4c-a82a-96c9c6bf6b15)

After checking with Silent and Nenkai, turns out I'm not going crazy seeing this, and the crazy float arithmetic here is intended.

However, it also appears to just be a validation function. So we can just patch it out.... Drop this in a file named `SCPS-17001_AEAD1CA3.pnach` in patches, and then enable it in game properties -> patches.
```
[Disable CRC Validation]
patch=1,EE,205719D8,extended,24420001
patch=1,EE,205719DC,extended,03E00008
```

But I'm thinking having a configurable round mode for division might be a better option.

**Comment by XieTieqiang** [comment]
SCAJ-30007 also has issues, please fix them

**Comment by stenzek** [comment]
What issues? Does changing the FPU division rounding mode to Nearest in Advanced Settings fix it?
