### ISSUE TITLE
[BUG]: cmake 3.21 fails early

### ISSUE THREAD

**Issue by Randrianasulu** [PCSX2/pcsx2#10564]
### Describe the Bug

On Slackware 15.0 I run into cmake abort.

cmake version 3.21.4

it was saying unsupported platform. After a bit of looking around I patched it and next it complained about qt6.

### Reproduction Steps

try to run linux  build with cmake <3.25

### Expected Behavior

cmake finds Linux on linux.

### PCSX2 Revision

 v1.7.5405

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Slackware

### Logs & Dumps

[cmake_check.txt](https://github.com/PCSX2/pcsx2/files/13851939/cmake_check.txt)

I tried to make patch that allows me to see more err messages (sdl2 2.28 was found in slackware -current, but qt6 a bit of big ask for now, will retry if I found way to build it )

**Comment by refractionpcsx2** [comment]
It is an unsupported platform, everything on Slackware is massively out of date compared to every other distro. 

Honestly if you want to patch it and you're struggling with Qt, then you will need to ask Qt, though they will probably also say "get a better OS".

**Comment by stenzek** [comment]
<3.25 works fine - our Ubuntu 22.04 builders are on 3.22.

If you run an ancient OS and libraries, then you need to use period-correct software. Or, the AppImage/Flatpak exist. Probably need the latter, your libstdc++ is likely too old to run the AppImage.

**Comment by mickski56** [comment]
Slacker here
@refractionpcsx2  & @stenzek are both correct in what they say.
However QT6 is available from slackbuilds.org, pcsx2 builds and run fine here on 15.0 thanks for all the hard work.

**Comment by Randrianasulu** [comment]
@mickski56 thank you for info. Unfortunately qt6 from slackbuilds.org says it will need 40gb of hdd space for build. I do not have that much at the moment.

Yet, I tried appimage of pcsx2 on Slackel 7.7.1 x64 under qemu/virgl - and it worked as far as bios screens.

My big idea was to see if our (cinelerra-gg) DVD disks can be played on pcsx2 in dvd player mode (some of my latest modifications to our  libavformat based muxing code might break dvd creation). But because dvd playback in pcsx2 still open issue here I was prepared to check if any patches still needed.

But this is just ... me. Weird late night idea.

**Comment by stenzek** [comment]
Qt does not require 40gb to build. You can run our deps build script to produce the slim version we use on our runners.

https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/scripts/linux/build-dependencies-qt.sh
