### ISSUE TITLE
[BUG]: God Of War II Black Artifacts

### ISSUE THREAD

**Issue by Dantedevil10** [PCSX2/pcsx2#10563]
### Describe the Bug

if you are Playing Normaly ,Maybe The Game not Present this ,But Sometimes when I Have Played The Game ,I Enter On a Cutscene and When Kratos return to the Gameplay ,the hud and some graphics like the yellow save be in black or not appear , i have tested the bug and on My Pcsx2 it's Working , is easy to appear this , All you have to do is : Load a save ,then go back to the title screen (Quit The Game) , and when you come back you have to start a new game and skip the first scene / i have tested on default settings of the emulator and its working too

### Reproduction Steps

All you have to do is : Load a save ,then go back to the title screen (Quit The Game) , and when you come back you have to start a new game and skip the first scene

### Expected Behavior

![God of War II 06_01_2024 20_02_13](https://github.com/PCSX2/pcsx2/assets/125316907/80a05ff2-1e25-4cda-915a-ce6c88259b46)
![God of War II 06_01_2024 20_02_20](https://github.com/PCSX2/pcsx2/assets/125316907/a3a6dba1-0fbe-4222-b6aa-fd2ec7e8f065)

### PCSX2 Revision

v1.7.5405

### Operating System

Windows 10

### CPU

i3-7100u

### GPU

intel hd 620

### Emulation Settings

![PCSX2 Settings 06_01_2024 20_07_34](https://github.com/PCSX2/pcsx2/assets/125316907/45a9a7a9-a8c7-4054-a092-c91ca7e7e4cb)
![PCSX2 Settings 06_01_2024 20_08_09](https://github.com/PCSX2/pcsx2/assets/125316907/5bf917cf-8355-4713-b83f-90164c09950d)
![PCSX2 Settings 06_01_2024 20_08_28](https://github.com/PCSX2/pcsx2/assets/125316907/0a315d90-0278-4c32-b96e-d56a8e13995f)

### Logs & Dumps

[God of War II_SCUS-97481_20240106203217.gs.zip](https://github.com/PCSX2/pcsx2/files/13851674/God.of.War.II_SCUS-97481_20240106203217.gs.zip)

**Comment by mrtawsiti3** [comment]
Happened to me only once, same place.
I was using Tab to fast forward through the intro.

**Comment by refractionpcsx2** [comment]
Can you verify your disc under the right click properties of the game in your list, It's probably a broken image.

**Comment by Dantedevil10** [comment]
> Can you verify your disc under the right click properties of the game in your list, It's probably a broken image.

The MD5 is in Red ,looks like this is it,Sorry i'll close the issue

**Comment by Dantedevil10** [comment]
So I reopened it because I tried again with a new iso, I checked and everything is fine, and the same way I describe the bug it works on this iso too

**Comment by stenzek** [comment]
This is a support issue - I can't reproduce the issue. And if GOW2 _was_ broken, we'd have hundreds of angry users.

Reset your settings, you've messed with a bunch of them
Update your graphics driver.
If you're still having issues, use the forums or discord server.
