### ISSUE TITLE
[BUG]: Weird red semi transparent effect in Neversoft's Gun

### ISSUE THREAD

**Issue by GoodWall533** [PCSX2/pcsx2#10562]
### Describe the Bug

As the title says, a semi transparent effect appears whenever there's a sunset. The effect can appear from either the giant letters above the npcs and even buildings and houses in the level. This happens in every renderer except Software.

![Gun_SLUS-21139_20240106184032](https://github.com/PCSX2/pcsx2/assets/73701483/3199ac3a-d10e-4504-aefc-4d9994d6aa1d)
![Gun_SLUS-21139_20240106192525](https://github.com/PCSX2/pcsx2/assets/73701483/1b0a926e-0555-4d1c-b582-1a9caf253903)

### Reproduction Steps

This can easily be observed when the player arrives in the town of Dodge City which is in the beginning of the game.

### Expected Behavior

![Gun_SLUS-21139_20240106185109](https://github.com/PCSX2/pcsx2/assets/73701483/dceddd10-0b56-4bfa-9e42-6be2da7efe25)
As one can see in the screenshot, the red effect isn't meant to show up.

### PCSX2 Revision

PCSX2 Nightly - v1.7.5404

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3500x

### GPU

NVIDIA GeForce GTX 960

### GS Settings

![2024-01-06 (3)](https://github.com/PCSX2/pcsx2/assets/73701483/1414a913-e197-4e69-a22e-a06bdeaec28d)

### Emulation Settings

![2024-01-06 (1)](https://github.com/PCSX2/pcsx2/assets/73701483/beb205d8-56f4-46f2-a8b2-79e7e1ca1375)

**Comment by Mrlinkwii** [comment]
are you using any widescreen patches ?

**Comment by GoodWall533** [comment]
no. nothing.

**Comment by lightningterror** [comment]
Can you upload a gs dump?

**Comment by GoodWall533** [comment]
[snaps.zip](https://github.com/PCSX2/pcsx2/files/13851636/snaps.zip)
Included two gs dumps just in case

**Comment by Buzzardsoul** [comment]
Tex in RT is causing this.
