### ISSUE TITLE
[BUG]: PINE stopped working

### ISSUE THREAD

**Issue by karas84** [PCSX2/pcsx2#10582]
### Describe the Bug

PINE no longer works in the latest builds. It simply does not connect to PCSX2 anymore. I've narrowed the problem down to version v1.7.5327. It was working fine up to version v1.7.5326, but since v1.7.5327 it does not work anymore.

### Reproduction Steps

- Enable PINE in PCSX2 settings and restart PCSX2
- Launch any game
- Launch PINE and attempt to connect to PCSX2
- PINE gives a connection error

### Expected Behavior

PINE connects to PCSX2

### PCSX2 Revision

v1.7.5420

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 23.04

**Comment by Mrlinkwii** [comment]
@karas84  can you check https://github.com/PCSX2/pcsx2/pull/10584 ?

**Comment by karas84** [comment]
Seems to be working!
