### ISSUE TITLE
[BUG]: [SLUS-21285] Ultimate Spider-Man (Limited Edition) - Software Renderer causes UI text to go missing (Ubuntu 22.04 - flatpak)

### ISSUE THREAD

**Issue by fabberr** [PCSX2/pcsx2#10583]
### Describe the Bug

Using the Software Renderer causes some of the game's UI text to go missing. Text within the Pause menu shows up correctly while other menus (Main menu and Unlockables menu, for instance) display no text whatsoever:

![Ultimate Spider-Man  Limited Edition _SLUS-21285_20240108154744](https://github.com/PCSX2/pcsx2/assets/65140794/45199624-8806-4661-b3b4-92f355abdeef)
(more screenshots below)

The game has some performance issues when running it on HW mode and most sources recommend running it on SW mode. This fixed the performance issues I was facing but unfortunately causes this graphical bug to occur and I couldn't find any online resources on how to fix it.

Using the latest nightly build v1.7.5400 (flatpak) on Ubuntu 22.04 as of opening the issue.

### Reproduction Steps

- Use the Software Renderer

### Expected Behavior

All of the in-game UI text should appear.

### PCSX2 Revision

PCSX2 Nightly v1.7.5400 (flatpak)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04

### CPU

11th Gen Intel i5-11320H (8) @ 4.500GHz

### GPU

NVIDIA GeForce MX450

### GS Settings

- Renderer: `Software`
- Adapter: N/A

### Display
![image](https://github.com/PCSX2/pcsx2/assets/65140794/a4444605-f130-45a3-b5ed-b4004f79246f)

### Rendering
![image](https://github.com/PCSX2/pcsx2/assets/65140794/db221b5b-c4ad-4aaa-8d73-2d19dbfde561)

### Post-Processing
![image](https://github.com/PCSX2/pcsx2/assets/65140794/ebf3a60c-2017-4942-acd8-445245658a72)

### Emulation Settings

- Default Settings used (`Multithreaded VU1` disabled).
![image](https://github.com/PCSX2/pcsx2/assets/65140794/6309188a-959e-4995-b6cd-253d7f9fc9d2)

### HW Rendering (Vulkan)
![image](https://github.com/PCSX2/pcsx2/assets/65140794/e8784981-0d66-4c08-b89d-86d50f37bd35)

### SW Rendering
![image](https://github.com/PCSX2/pcsx2/assets/65140794/64f8ccce-f2b9-48ae-a786-84503b06891f)

### HW Rendering (Vulkan)
![image](https://github.com/PCSX2/pcsx2/assets/65140794/4788caaa-eea5-4259-86ff-86245062ad16)

### SW Rendering
![image](https://github.com/PCSX2/pcsx2/assets/65140794/04a02869-a7eb-4701-b40d-a7e394b28a60)

### HW Rendering (Vulkan)
![image](https://github.com/PCSX2/pcsx2/assets/65140794/786e114d-578a-46bd-bc85-883d2b5509b7)

### SW Rendering
![image](https://github.com/PCSX2/pcsx2/assets/65140794/09d74175-3967-48db-9982-32e2162f0434)

### Logs & Dumps

Here are the single-frame dumps taken of the Main and Unlockables menu under SW Rendering:

- [Ultimate Spider-Man [Limited Edition]_SLUS-21285_20240108152949_main_menu_sw_rendering.zip](https://github.com/PCSX2/pcsx2/files/13865088/Ultimate.Spider-Man.Limited.Edition._SLUS-21285_20240108152949_main_menu_sw_rendering.zip)
- [Ultimate Spider-Man [Limited Edition]_SLUS-21285_20240108153025_unlockables_menu_sw_rendering.zip](https://github.com/PCSX2/pcsx2/files/13865094/Ultimate.Spider-Man.Limited.Edition._SLUS-21285_20240108153025_unlockables_menu_sw_rendering.zip)

**Comment by Mrlinkwii** [comment]
when did this start ? do you know

**Comment by JordanTheToaster** [comment]
Likely just a Linux issue it works correctly under Windows.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/8ac50339-e4e3-4713-9f25-39b84e215129)
****

**Comment by fabberr** [comment]
> when did this start ? do you know

I am unsure if this issue was present in previous versions sorry, only started messing with emulators on Linux a couple days.


> Likely just a Linux issue it works correctly under Windows.
I imagined it'd be a Linux thing. Couldn't find anything on the issue with some googling.

**Comment by refractionpcsx2** [comment]
It seems like it broke with #10425, but only for linux.

What further confuses me is I didn't change any GS renderer stuff here. the core interlace/video mode settings were changed here, but I'm not sure why they would affect a GS dump.  We're investigating now.

**Comment by Mrlinkwii** [comment]
I believe this was fixed with #10607 , @fabberr  can you double check

**Comment by fabberr** [comment]
Works on my Machine™ (v1.7.5446)

![image](https://github.com/PCSX2/pcsx2/assets/65140794/acda7300-93ce-41bf-82ef-edba6ca896ca)

Thanks for the support, you guys rock.
