### ISSUE TITLE
[Feature Request]: Exit Hotkey

### ISSUE THREAD

**Issue by dragoonDorise** [PCSX2/pcsx2#10580]
### Description

RPCSX2 is missing the ability to be closed using a hotkey. You can do this in windows with ALT F4, but in Linux it just ignores both ATL F4 or CTRL Q.

### Reason

This will make it easy to control in an HTPC using a gamepad, now you can exit the emulation with a shortcut and if you use big picture you can also exit from there, but those are extra steps that could just be done in one single step.

### Examples

These emus have this feature: Citra, Retroarch, Dolphin, Duckstation, RPCS3, Yuzu, ScummVM, Vita3K, Xemu

**Comment by stenzek** [comment]
ALT+F4 works fine for me on Linux (KDE).

Sorry, but this argument is rubbish. An exit hotkey would cause the confirm shutdown/save state dialog to open, the same way that a VM shutdown does, which requires mouse input. If the goal is to make it easier for controllers, then that's already worse than the intended way, which is to have one button/combination to open the Pause Menu -> Close/Shutdown (forget what it is in PCSX2) -> Save, then Exit from the main menu.

Unless you disable saving on shutdown, in which case users can't save their progress for quick resume from the game list.

Also, maybe check the things you're quoting, DuckStation uses the same code for this sort of thing as PCSX2, and it does not have a quit hotkey for the same reason.

**Comment by dragoonDorise** [comment]
@stenzek In PCSX2 the Shutdown Machine Hotkey takes you back to the Emulator, but in DuckStation the PowerOff Hotkey closes the Emulation and the Emulator. That's what I meant, if it was possible to to have the same PowerOff functionality in PCSX2 like DuckStation already have, English is not my first language, so sorry If didn't properly explain myself when opening the issue.

Regarding the keyboard hotkey, I forgot to specify that this happens while in game scope in SteamOS or ChimeraOS, CTRL Q does work on some other emus like Citra for instance.

**Comment by refractionpcsx2** [comment]
You can run pcsx2 with nogui or batch, and it will close on exit.

**Comment by dragoonDorise** [comment]
@refractionpcsx2 @stenzek I completely forgot about -batch, that does the trick, thanks!
