### ISSUE TITLE
[BUG]: Fast & Furious - Bugged Car Textures (Partial Regression) [SLUS-21449]

### ISSUE THREAD

**Issue by forrvalhalla** [PCSX2/pcsx2#10594]
### Describe the Bug

In _The Fast and the Furious_, car textures are broken and periodically turn black.

This is a partial regression from #9690. Both HW behaviors are broken I'm pretty sure (looks inaccurate), but on earlier builds the cars do not turn completely black.

### Reproduction Steps

1. Start new game
2. Watch car turn black on countdown

### Expected Behavior

Cars should not turn black, and be accurate to SW/PS2

### PCSX2 Revision

v1.7.5426

### Operating System

Windows 10 (64bit)

### CPU

i5-7600K

### GPU

GTX 1050ti

### GS Window Screenshots

pcsx2-v1.7.4872 HW
![Fast and the Furious, The_SLUS-21449_20240109192035](https://github.com/PCSX2/pcsx2/assets/53349573/acba38a0-2d5b-40e3-972d-78e344d1ae49)
pcsx2-v1.7.4871 HW
![Fast and the Furious, The_SLUS-21449_20240109191945](https://github.com/PCSX2/pcsx2/assets/53349573/1a366831-4f02-40d0-a54c-e54a4943e42d)
pcsx2-v1.7.4872 SW
![Fast and the Furious, The_SLUS-21449_20240109192052](https://github.com/PCSX2/pcsx2/assets/53349573/abfb43db-6a3e-419f-9aa0-132ca313a508)
Real PS2 (My capture card sucks! But there is zero footage of this scene on YT.)
![Screenshot 2024-01-09 18-51-23](https://github.com/PCSX2/pcsx2/assets/53349573/3ade09aa-5ea7-4c1a-b348-b4008a029041)

### Logs & Dumps

Multi-frame GS Dump
https://cdn.discordapp.com/attachments/611194120806989835/1194451632830808089/Fast_and_the_Furious_SLUS-21449_20240109115603.gs.zst

**Comment by rodrigoba2099** [comment]
Onimusha: Dawn of Dreams tem BUG #

**Comment by rodrigoba2099** [comment]
Onimusha: Dawn of Dreams tem BUG de pcsx2-qt

**Comment by refractionpcsx2** [comment]
excuse me?
