### ISSUE TITLE
[Enhancement] [Question]Namco Station Emulation

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1059]
Should we not add like Dolphin did for certain systems, the emulation of Namco Station for people owning such a Station?

I think we should discuss this here...

**Comment by Depersonalized** [comment]
I think we should discuss this in the PCSX2 forums ;)

**Comment by TheLastRar** [comment]
IIRC, someone did try to look into this a while back after discovering that the 246? BIOS booted, but was unsuccessful in loading games.

**Comment by trader5896** [comment]
Yeah, this is what I looked into too in forums. I think, that the main problems are bios interaction with pcsx2 and the dongle.

Bios actions seem to be main problems for the games, which don't boot (5 or 6 games) and True crimes LA. This should be looked in later....But the devs of course need Namco 246 System...:D

**Comment by mirhl** [comment]
Dumping ps2 bios is already damn hard, go [figure out](http://forums.pcsx2.net/Thread-PCSX2-works-with-the-Namco-System-246-BIOS) how it's possible for that (even though it should). 
And developers would need original hardware of course to do this lawfully. 

So I'd say if any, this would only be realistically possible after we have a working HLE fps2bios or whatever.
