### ISSUE TITLE
USBqemu: no device is listed 

### ISSUE THREAD

**Issue by Kormann** [PCSX2/pcsx2#106]
<b>SPECS</b>
O.S.: Windows 7 x64 Home Premium SP1 with x86 & x64 Visual Studio 2005, 2008, 2010, 2012, 2013.
BUILD: from PCSX2 1.2.1 Stable to PCSX2 1.3.0 (GIT Weekly Builds: 213-g0616708]
PLUGIN: USBqemu 0.1.0 by @gigaherz 

<b>REPRODUCE BUG</b>
1) Run PCSX2.exe and Go to menu: Config > Plugin BIOS Selector.
2) Go to Plugins > USB > USBqemu 0.1.0 and hit APPLY.
3) Go to USBqemu 0.1.0 and hit CONFIGURE.

<b>BUG REPORT</b>
At USBConfigure screen there is no way to select any device at port 1 or 2. The dropdown menu is blank.

![usbqemu](https://cloud.githubusercontent.com/assets/8125662/3540443/f5527396-0842-11e4-83ab-fda704b8820d.jpg)

If you check "Enable Logging" option or leave it blank, it saves correctly to USBqemu.ini at INIS folder.

<i>USBqemu.ini</i>

<pre>
[Interface]
Logging=FALSE
</pre>

<b>WORKAROUND</b>
1) Exit PCSX2.
2) Backup your old USBqemu.dll
3) Download and extract <a href="http://forum.coldbird.net/viewtopic.php?f=32&amp;t=1606" target="_blank">USBqemu 0.1.0 custom, version 2014/06/08 - by jackun (based on gigaherz's USBqemu)</a> into PLUGINS folder. <a href="https://dl.dropboxusercontent.com/u/235773/USBqemu.dll" target="_blank">[Direct link here]</a>

4) Run PCSX2 again and go to Config > Plugin BIOS Selector > USB > USBqemu 0.1.0 > CONFIGURE.</li>
5) As you can see below, there is a list of devices that you can select.</li>

![usbqemu_air_gamer](https://cloud.githubusercontent.com/assets/8125662/3540608/7d0d37c0-0844-11e4-87de-05ffa1661307.jpg)
6) In my case, I selected Keyboard because I wanted to use it with Network Adapter Start-up Disc and Biohazard Outbreak on private server (obsrv.org). Hit OK when you are done.
7) As this custom plugin doesn't work properly while in games (3 and M keys keep pressing until forever), close PCSX2. 
8) Now delete this custom USBqemu plugin from PLUGINS folder. This plugin is useful to create a INI file with the devices that was set early in step 5.

<i>jackun's USBqemu.ini</i>

<pre>
[Interface]
Logging=FALSE
Dev0=1
Dev1=0
Path=
</pre>

9) Copy the original USBqemu backup again into PLUGINS folder.
10) Now you are good to run your game and start chatting online.

If you check again the USBqemu's USBConfigure screen, you still can't list or choose a device. You only can do that with the custom build by jackun's (Air_gamer post at Prometheus).

Bug originally reported at: http://forums.pcsx2.net/Thread-Bug-Report-gigaherz-s-USBqemu-plugin-no-device-is-listed

**Comment by Blackbird88** [comment]
Is this suppoed to work in games? It doesn't work for me in Half-Life

**Comment by jeyseaf** [comment]
can someone post new link,
this one is not working anymore

**Comment by bositman** [comment]
Get it here https://github.com/jackun/USBqemu-wheel/releases

**Comment by jeyseaf** [comment]
thx
