### ISSUE TITLE
[BUG]: Ghost inputs when using multiple profiles on one game

### ISSUE THREAD

**Issue by Hinkiii** [PCSX2/pcsx2#10605]
### Describe the Bug

Emulator sending inputs from a unbound pad

### Reproduction Steps

Set a profile with bindings for player 1 and player 2 on separate controllers, rebind to make another profile, even with everything cleared on pad 2 it'll still read inputs from the initial profile

### Expected Behavior

To send the inputs as they're mapped on screen

### PCSX2 Revision

v1.7.5435

### Operating System

Windows 11

**Comment by RedPanda4552** [comment]
This is not how profiles work. Profiles are for having alternative mappings for different games. Profiles are not for switching mappings in real time.

To use a custom profile, you must set it on your per-game settings. Follow the instructions that were given on the prompt when you created your profiles.

GitHub is for technical issues, not general support. Please use the Discord server (linked on the PCSX2 website) for general support.
