### ISSUE TITLE
[BUG]: PCSX2 no longer building in linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#10608]
### Describe the Bug

PCSX2 no longer builds on linux.  Build log includes the following:
```
CMake Error at cmake/Pcsx2Utils.cmake:16 (message):
  Unsupported platform.
Call Stack (most recent call first):
  CMakeLists.txt:33 (detect_operating_system)
```

### Reproduction Steps

Attempt building

### Expected Behavior

PCSX2 builds properly.

### PCSX2 Revision

51ceab1f3c226508d0745ccf2e8894efb69cdaaa

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.2

### Logs & Dumps

[build.log](https://github.com/PCSX2/pcsx2/files/13914727/build.log)

**Comment by stenzek** [comment]
> -- The C compiler identification is GNU 12.3.0

Not a supported compiler.

It builds fine the CI.

**Comment by Shoegzer** [comment]
Thanks, and that does make sense of course, although it's built using gcc 12.3.0 in the past.  Did something recently change?

**Comment by stenzek** [comment]
We haven't used GCC in some time, because produces slower code than clang. PCSX2 also doesn't build with GCC13 due to what appears to be a bug that manifests when you use intrinsics.

**Comment by Shoegzer** [comment]
Thanks again.  I last built pcsx2 with gcc 12.3.0 on commit e9fca78c13b9a7cf35f271ed0518ec748f6a12ba, about a month ago.  I guess what you're saying is that gcc has been deprecated since then.  It's good to know in advance that it won't build with gcc 13 at all.  Is there a guide to building pcsx2 with clang?  I couldn't find anything, but I'm probably just blind.

**Comment by stenzek** [comment]
The CI build scripts are here:

https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/linux_build_qt.yml
https://github.com/PCSX2/pcsx2/tree/master/.github/workflows/scripts/linux

**Comment by Shoegzer** [comment]
Actually I found the PCSX2 [build guide](https://wiki.pcsx2.net/PCSX2_Documentation/Compiling_on_Linux) which provides steps for compilng with clang.  The document indicates the following should be done:

`mkdir build && cd build && cmake --preset=clang-release .. && ninja `

However this produces the following error: 
```
CMake Error: Could not read presets from /home/testing/Desktop/pcsx2/pcsx2: Unrecognized "version" field
ninja: error: loading 'build.ninja': No such file or directory
```
Build log: [build.log](https://github.com/PCSX2/pcsx2/files/13925084/build.log)

clang, lld and ninja-build are installed.

Shouldn't this work?

**Comment by Mrlinkwii** [comment]
The wiki is mostly out of date and shouldn't be used

**Comment by Shoegzer** [comment]
Thanks, but what would the command-line equivalents be now?  I was hoping to avoid running all those CI build scripts if possible.

**Comment by refractionpcsx2** [comment]
https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux

**Comment by stenzek** [comment]
You need to build the dependencies, unless your distro has qt 6.6 and the latest SDL. Then create a cmake toolchain file pointing it to clang/lld, and run cmake with the prefix path and toolchain file overridden.

**Comment by Shoegzer** [comment]
Thanks, guys.

@refractionpcsx2 The document you linked to has the same steps as the ones I followed in my previous post with `cmake --preset=clang-release` specifically.  I'm just not sure why I get the `Could not read presets` error as shown above but I guess the steps really are outdated?

@stenzek My environment variables have been preconfigured to use qt 6.6.1 that I built, and I use `-DCMAKE_PREFIX_PATH=/usr/local/include/SDL2` which points to SDL2-2.28.5 which is the latest.

I didn't realize creating a cmake toolchain file was necessary. After searching for a way to do that specifically, the closest I've found was [this](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#toolchain-files) but I can't find an example that more closely matches a linux build environment.  If the guide above gets updated I guess it should provide those steps if it's now needed.

**Comment by stenzek** [comment]
Like we both said, everything needed is in the CI scripts above. If you're not going to bother reading those, then it's silly to expect us to explain exactly what the issue is to you.

**Comment by Shoegzer** [comment]
I think you misunderstood my intent but it's okay.  I realize it's all within the CI scripts, I've indeed been reading through them and although I'm new to the CI process I'm sure I'll find the new way to build the project eventually.  I was just trying to suggest that the build guide @refractionpcsx2 pointed to was nice because it avoided the need to analyze scripts to figure out how to compile the project and make meaningful contributions.  

The "old method" of just adding `--preset=clang-release` to the cmake apparently worked, and is in keeping with the simple way many projects are built.  PCSX2 has evidently evolved beyond that, which is entirely fine, but I think having a working method documented in the guide rather than just "follow our CI" as it currently states at the top would be a good thing lest others run into the same issue I did and ask silly questions.  

I mean heck, I'd even be happy to submit PRs to update it mysefl if I could figure this out, if we're all in agreement that would help the project.

**Comment by stenzek** [comment]
I didn't add the presets, can't even remember who did at this point. But the CI doesn't use them, nor do I use them for local builds.

I specifically added the note at the top of the wiki page because I didn't have the energy to rewrite it at the time. If you want to do so, go nuts.

**Comment by Shoegzer** [comment]
Okay, I made some changes to the linux build section of the Wiki that primarily describes the process of compiling manually using clang/llvm.  Can someone mark me as a contributer so I can commit them for review?

**Comment by Shoegzer** [comment]
Thanks.  I've made some draft changes which update and streamline the build process, but with some areas that need more information, such as dependency version requirements and optional CMake flags. I can make more updates in these areas, I just want to be sure they're accurate first.

**Comment by refractionpcsx2** [comment]
Okay, thanks. I've put the lock back on for now to prevent defacing, but if somebody wants to mention any further changes I can remove the lock temporarily when you are ready :)

Thanks for updating it.
