### ISSUE TITLE
[Enhancement] PS2 Offline Servers Revivial Project

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1061]
Status: Low-Long Term

It might be, that you think, I spam here, but this is really not my intention. I will add important thing, which I think to be important:

This Idea is very intresting and could bring more PCSX2 users perhaps.

As you know, most of the servers for Network playable games are closed. But how would it be, if pcsx2 as a domain for example "pcsx2/Servers/pcsx2network/GT4" have the domains revived.

Someone need to buy the old IP adresses of these servers and fans of these particular game scenes (like Resident Evil outbreak scene) program the database for the game and we could play these games offline as well.

This is good idea I think and all running from one Network.

Problems:
-Amount of money for buying ips and for the pcsx2 server to maintain all the traffic
-Mancraft for programming DB's(reviving the servers)
- A way to fake the original disc that he is bound with old ip adress:"192.1.1.1" for example, but indeed it's another ip, which is pcsx2.net

**Comment by mrRosset** [comment]
IP adress != domain name

**Comment by willkuer** [comment]
Once we had a thread about a guy willing to revive a server. The problem is just that you need to know what the server does. And how could you know as they are obviously not open source. This is a lot of work and mostly impossible I would say.

**Comment by trader5896** [comment]
There are several groups trying to revive their fan base servers. Perhaps they should get in contact with pcsx2?

**Comment by willkuer** [comment]
Because then...?
It would be easier?
Pcsx2 devs would revive the servers?
Game server devs would program pcsx2?

These are completely different projects. Pcsx2 contains some basic networking and allows playing a lot of games. That should be sufficient for game server devs to revive if all other informations are available.

**Comment by trader5896** [comment]
No, you understand it wrong... 

Pcsx2 as a community, will revive the ps2 back and it's base for all of this. 

For example :

http://obsrv.org/viewtopic.php?t=545

These people have revived Resident Evil. Every person with a obsrv.org account can join there. 

But my idea would be, everybody with a pcsx2 account should be able to play all online network games, they played back in that time again with the usage of the emulator. 

Pcsx2 will be the best place for this, which will unite all devs and scenes and this is really good for now. 

If for example fans of Gt4 revived the server, they send the files for starting the network interaction to bositman. He would start the network client and everybody owning pcsx2 could play their games as they did in early times. It's less complicated with one community, one emulator... 

It would be even better if the ps2's could actually bind to the Pcsx2 server, but this is not possible, because the ip is burnt into disc. Pcsx2 should be able to fake the cd to read another ip. 

Pcsx2 is number one forum for ps2 not emulation only. This is the reason, why I believe this should be made.

**Comment by alfio8788** [comment]
You can redirect data from it's original IP to another one through routers with routing capabilities, a linux distro with ip tables and such that is not a problem.

In my opinion Pcsx2 is a PS2 emulator and as such should be able only to do things PS2 did (excluding PS1 emulation, there are so many good alternatives it makes no sense to code the same thing over and over again).

Let Pcsx2 deal with emulation of ps2 games and such, server softwares can be made by others and released to the public to host on your own servers, they have close to nothing in common with emulation of ps2 itself.

**Comment by mirhl** [comment]
> Pcsx2 is number one forum for ps2 not emulation only

Citation needed. And regardless, I don't think there was ever something centralized like PSN today, that requires replacing system functions. 
And everything can just work hijacked just fine on original hardware too. 

If any, potential network reverse engineers could ask for features helping in their task to be included inside pcsx2. But that's another (and *specific*) story.

**Comment by trader5896** [comment]
Pcsx2 is the best ps2 community that exists today. This would really make things easier for people... I just asked around.

This would be like a system for all in one. 

Pcsx2 users do normally have a pcsx2 account. Imagine someone wants to play in future, where this feature works : He just needs to login with his pcsx2 account and all the playing will work. 

And routing emulation, is this something like faking the DVD to take another ip?

**Comment by trader5896** [comment]
This will lead to union too according to my opinion...
