### ISSUE TITLE
[BUG]: Manhunt 2 Pause / Main Menu Shaking

### ISSUE THREAD

**Issue by Bigmac9922** [PCSX2/pcsx2#10613]
### Describe the Bug

If you pause the game on hardware mode the pause menu will have horrible shaking. However on software mode there will be little to none. Setting the half pixel offset to Align to native seems to fix the issue on hardware mode. This should be added in the automatic hardware fixes.

### Reproduction Steps

Enable Align to native and disable it on hardware mode to see the drastic change in effects. Then compare it to software mode. Align to native seems to fix the issue making it like software mode. 

### Expected Behavior

Similar to software mode it should have way less shaking.

### PCSX2 Revision

v1.7.5442

### Operating System

Windows 11

### CPU

12700k

### GPU

RTX 4080 OC

### GS Settings

Hardware mode with all default settings except resolution being 4k. Then applying the align to native with manual hardware fixes enabled to stop the issue.

### Emulation Settings

Default

**Comment by Mrlinkwii** [comment]
dose this issue happen at native res ?

**Comment by lightningterror** [comment]
@Bigmac9922 Can you upload a gs dump?
