### ISSUE TITLE
[BUG]: Ratchet 3 player texture regression

### ISSUE THREAD

**Issue by ZwipZwapZapony** [PCSX2/pcsx2#10626]
### Describe the Bug

When playing Ratchet & Clank 3: Up Your Arsenal with any hardware renderer (Direct3D 11/12, OpenGL, or Vulkan), the player's texture occasionally bugs out. Changing any(?) graphics setting in PCSX2 fixes it temporarily. Caused by #10589 (v1.7.5434).

### Reproduction Steps

\- Play the game casually for a random, unpredictable amount of time
\- OR zoom in with the Flux Rifle weapon
\- OR load the attached save state

### PCSX2 Revision

v1.7.5449

### Operating System

Windows 10 (64bit)

### CPU

i9-9900K

### GPU

RTX 2080 Ti

### GS Window Screenshots

|v1.7.5434 and onwards (Wrong)|v1.7.5433 (Correct/Expected)|
|:-:|:-:|
|![image](https://github.com/PCSX2/pcsx2/assets/14360666/c85469e0-8eb0-46fa-8cbb-83a0e217b0c3)|![image](https://github.com/PCSX2/pcsx2/assets/14360666/2a117315-78ee-41ee-88fa-95f6a6e94297)|

### Logs & Dumps

Save State (SCES-52456): [[Ratchet & Clank 3 Player Texture Regression Save State.zip]](https://github.com/PCSX2/pcsx2/files/13929586/Ratchet.Clank.3.Player.Texture.Regression.Save.State.zip)
~~GS Dump: [[Ratchet & Clank 3 Player Texture Regression GS Dump.zip]](https://github.com/PCSX2/pcsx2/files/13929585/Ratchet.Clank.3.Player.Texture.Regression.GS.Dump.zip)~~ ***(Does not display the issue!)***

**Comment by refractionpcsx2** [comment]
Here's a GS dump which does show it

[Ratchet & Clank 3_SCES-52456_20240113220655.gs.zip](https://github.com/PCSX2/pcsx2/files/13929665/Ratchet.Clank.3_SCES-52456_20240113220655.gs.zip)

**Comment by refractionpcsx2** [comment]
Can you try this PR build and confirm it's okay now? https://github.com/PCSX2/pcsx2/actions/runs/7515461411/artifacts/1167614007

**Comment by ZwipZwapZapony** [comment]
That PR fixes it. :thumbsup:

**Comment by refractionpcsx2** [comment]
Thanks for testing :) The fix should be live about 30 minutes after this message in 1.7.5454
