### ISSUE TITLE
[GSDX][Enhancement] Selecting between 50/60 HZ

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1062]
Status: Low pririty

You were talking about this issue, which is solved, but there could be a intresting feature to add:
https://github.com/PCSX2/pcsx2/issues/1013

Selecting between:
-Automatic
-50 HZ (PAL)
-60 HZ (NTSC)

This is just useful for people, who want 60 HZ for games supporting 50 HZ....

**Comment by willkuer** [comment]
Do you know if there is a general approach for all games? I don't think a game database for 50/60Hz hacks is what we need and want to have here.

Also as you see they don't seem to work well with pcsx2. (The mentioned issue is still not fixed but rather rejected...)

**Comment by ssakash** [comment]
>  (The mentioned issue is still not fixed but rather rejected...)

that's because it's not an accurate issue to begin with. The ISO at the first test seemed to be tampered.

on the other hand, I'm not exactly sure how to explicitly set a video mode for a certain game. @gregory38  any idea ? one idea would probably be to force set the CMOD and other registers value to a different video modes respective value but I'm not even sure whether that's possible.

**Comment by trader5896** [comment]
@ssakash , this is just low priortiy for now. I just added this issue as "At least we have all bugs documented somewhere"... For the first there are much more serious problems.

**Comment by trader5896** [comment]
@willkuer the issue has been fixed (#1013), because the original ps2/ps3 will emulate the game in the way it is, in the pirated pre-patched way. Just for people who need as a enhancement, they should be able to set it manually 50/60 HZ.

**Comment by mirhl** [comment]
The issue has not been *fixed*. It has been *closed*. Which doesn't mean nobody cares anymore, but just that it was misleading. 
We all know resolution autodetection is not okay. See #961 and following pull requests. 
Of course, if PS2 was able to autoadjust, *physically* it has to be possible to replicate the system state here too. 
But, along with all the other mysteries of the console, there's a lot of undocumented and analogically sorcering stuff involved. 

I don't know details but if any the question should be: how reasonably accurate can we expect emulation to be? And if and only if the answer is "never enough", only then give up and implement manual selection.

**Comment by trader5896** [comment]
Fixed means for me, that it is emulating the software accurate. This is not per se a bug, which is by pcsx2. Much more the games problem. I just wanted to let you know, that we should this great feature for people. Or at least document it and say "we don't make this for this and that reason."

**Comment by trader5896** [comment]
Fixed means for me, that it is emulating the software accurate. This is not per se a bug, which is by pcsx2. Much more the games problem. I just wanted to let you know, that we should this great feature for people. Or at least document it and say "we don't make this for this and that reason."
