### ISSUE TITLE
[BUG]: Bug in the game : Totally Spies Totally Party!

### ISSUE THREAD

**Issue by miguelmaro8** [PCSX2/pcsx2#10620]
### Describe the Bug

First, i want to say that i know nobody plays this game anymore and that it is too old, but i really wanted to play this game because it reminds me of my childhood.
So, the bug is: the game starts and runs perfectly, really, just the cutscenes that get a little buggy, but the real problem is the characters. The characters that you play with or that you play against, the items inside the gameplays such as lasers and other characters, they simply bug. It glitches the whole screen, like it's totally out of shape. I really don't know what it's happening, but if you guys could fix that i would be so happy. 

### Reproduction Steps

There aren't really steps to make this happen, it just happens everytime.

### Expected Behavior

The characters should be in shape, like it should be (the bodies, heads, arms, legs..), items inside the game should be in shape (buckets, lasers, the animals, the selection button, the dice...), the main issue is you can't see a character like it should be, so this should be fixed.

### PCSX2 Revision

1.7.133

### Operating System

Windows 11

### CPU

 AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~3701 Mhz

### GPU

AMD Radeon RX 580 2048SP

### GS Window Screenshots

![Captura de tela 2024-01-12 185936](https://github.com/PCSX2/pcsx2/assets/156477701/b85e10f3-3b36-42f8-ba9e-0caa5b4a79a8)
![Captura de tela 2024-01-12 190011](https://github.com/PCSX2/pcsx2/assets/156477701/f5ca311b-2392-4be6-8740-99ca95e37c53)
![Captura de tela 2024-01-12 190019](https://github.com/PCSX2/pcsx2/assets/156477701/b4bafc2f-5e46-4b12-b89f-edbaba9bef84)
![Captura de tela 2024-01-12 190104](https://github.com/PCSX2/pcsx2/assets/156477701/40ef43be-9fd0-4748-82a4-15b23651f3de)

**Comment by Mrlinkwii** [comment]
```
PCSX2 Revision

1.7.133
```

are sure about that version?

**Comment by JordanTheToaster** [comment]
Please use the latest version as it's fixed there. If you need support otherwise please use the Discord.

**Comment by refractionpcsx2** [comment]
Very old builds are not supported, this should be fixed on newer builds to the best we can.

**Comment by TheTechnician27** [comment]
Testing this on 1.7.5431 (courtesy my little sister's childhood game collection), I can confirm it is not an issue anymore.

**Comment by miguelmaro8** [comment]
Guys, my bad. The version wasn't updated, i was playing with an old one. It got fixed. Thank you so much for helping me, really. 😊
