### ISSUE TITLE
[BUG]: Samurai Warriors 2 Xtreme Legends - incorrect AI behavior in Sugoroku mode (SLUS-21726)

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#10622]
### Describe the Bug

In Sugoroku, the minigame, there is another minigame called 'reveal' where you are supposed to kill the enemies while they are in their holes. However, in PCSX2, these enemies surround you instead of digging holes to kill them in, which makes killing them easy and not as fun. This glitch can only be fixed by setting the clock speed to 50%.

### Reproduction Steps

Play Sugoroku until the game 'reveal' is selected in a challenge, or just load my savestate:
[SLUS-21726 (3C93E16A).01.zip](https://github.com/PCSX2/pcsx2/files/13925239/SLUS-21726.3C93E16A.01.zip)

### Expected Behavior

For the enemies to remain inside of their holes like this:
![Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20240113034535](https://github.com/PCSX2/pcsx2/assets/126727903/90244a7e-d7a0-4796-916b-6a869da9959b)

Instead of surrounding you (which is bad)

![Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20240113034847](https://github.com/PCSX2/pcsx2/assets/126727903/7ec8100b-deed-40a2-a0fa-34ffc6db717d)

### PCSX2 Revision

1.7.5416

### Operating System

Windows 11

### CPU

i5-7600

### GPU

GTX 1050 TI

**Comment by Buzzardsoul** [comment]
Setting any of those 2 addresses to 0 fixes the issue, but I do not know what these offsets are for

![dd](https://github.com/PCSX2/pcsx2/assets/126727903/11725561-5ed1-4483-87d7-0c3f3ea0948c)

**Comment by refractionpcsx2** [comment]
Can you translate them to PS2 addresses? Your PC memory addresses aren't a great deal of use to us, unfortunately.

**Comment by Buzzardsoul** [comment]
> Can you translate them to PS2 addresses? Your PC memory addresses aren't a great deal of use to us, unfortunately.

0x70000174

**Comment by refractionpcsx2** [comment]
Thanks, that's scratchpad memory, so doesn't really help a ton

**Comment by Buzzardsoul** [comment]
> Thanks, that's scratchpad memory, so doesn't really help a ton

This is the offset of the instruction causing the glitch: 0x00100244

**Comment by refractionpcsx2** [comment]
That may be more useful, thanks :)

**Comment by Buzzardsoul** [comment]
Correct me if I were wrong, but isn't it an issue with one of the ee's timers rather than fpu?

**Comment by refractionpcsx2** [comment]
how did you come to that conclusion?

**Comment by Buzzardsoul** [comment]
> how did you come to that conclusion?



because this instruction is taking its value from 0x10000800 to a0. Just a hypothesis.
![untitled](https://github.com/PCSX2/pcsx2/assets/126727903/04779983-fcf6-44e2-a1e2-faee45ac0e80)

**Comment by refractionpcsx2** [comment]
and what are the values in 0x10000800, 0x10000810, 0x10000820? 

does it access any of those (or 10000830, though less likely)

**Comment by Buzzardsoul** [comment]
> and what are the values in 0x10000800, 0x10000810, 0x10000820?
> 
> does it access any of those (or 10000830, though less likely)

Only 0x10000800, and the value is always different, but 65 or something above it is likely what is accurate, and the value is affected by ee's clock speed.

**Comment by Buzzardsoul** [comment]
I've designed a patch to test the timer's value on both pcsx2 and ps2 via opl, and it seems that the value in decimals, is typically 44 on PS2, and 24 on PCSX2. Inside of the challenges it is different but I have no idea what it should be.
`patch=1,EE,00397E80,word,00000001
patch=1,EE,005C1E28,word,65300000
patch=1,EE,005C1E58,word,65300000
patch=1,EE,005EC270,word,05030100
patch=1,EE,005EC2A0,word,04030100
patch=1,EE,005EC2D0,word,04030100
patch=1,EE,005EC300,word,05030100
patch=1,EE,00614320,word,05030100
patch=1,EE,00614350,word,05030100
patch=1,EE,00614380,word,05030100
patch=1,EE,006143B0,word,04030100
patch=1,EE,00584DB0,word,00000010
patch=1,EE,00584DB4,word,06010000
patch=1,EE,00584DC0,word,00000010
patch=1,EE,00584DC4,word,06010000
patch=1,EE,00584DD0,word,00000010
patch=1,EE,00584DD4,word,06010000
patch=1,EE,00584DD8,word,00000010
patch=1,EE,00584DDC,word,06010000
patch=1,EE,00584DE0,word,00000010
patch=1,EE,00584DE4,word,06010000
patch=1,EE,00584DE8,word,00000010
patch=1,EE,00584DEC,word,06010000
patch=1,EE,00584DF0,word,00000010
patch=1,EE,00584DF4,word,06010000
patch=1,EE,00584E00,word,00000010
patch=1,EE,00584E04,word,06010000
patch=1,EE,00584E10,word,00000010
patch=1,EE,00584E14,word,06010000
patch=1,EE,00584E20,word,00000010
patch=1,EE,00584E24,word,06010000
patch=1,EE,00584E28,word,00000010
patch=1,EE,00584E2C,word,06010000
patch=1,EE,00584E30,word,00000010
patch=1,EE,00584E34,word,06010000
patch=1,EE,00584E38,word,00000010
patch=1,EE,00584E3C,word,06010000
patch=1,EE,00584E40,word,00000010
patch=1,EE,00584E44,word,06010000
patch=1,EE,00584E50,word,00000010
patch=1,EE,00584E54,word,06010000
patch=1,EE,00584E60,word,00000010
patch=1,EE,00584E64,word,06010000
patch=1,EE,00584E70,word,00000010
patch=1,EE,00584E74,word,06010000
patch=1,EE,00584E80,word,00000010
patch=1,EE,00584E84,word,06010000
patch=1,EE,00584E90,word,00000010
patch=1,EE,00584E94,word,06010000
patch=1,EE,00584Ea0,word,00000010
patch=1,EE,00584Ea4,word,06010000
patch=1,EE,00584Ea8,word,00000010
patch=1,EE,00584Eac,word,06010000
patch=1,EE,00584Eb0,word,00000010
patch=1,EE,00584Eb4,word,06010000
patch=1,EE,00584Eb8,word,00000010
patch=1,EE,00584Ebc,word,06010000
patch=1,EE,00584EC0,word,00000010
patch=1,EE,00584EC4,word,06010000
patch=1,EE,00584EC8,word,00000010
patch=1,EE,00584ECC,word,06010000
patch=1,EE,00584ED0,word,00000010
patch=1,EE,00584ED4,word,06010000
patch=1,EE,00584EE0,word,00000010
patch=1,EE,00584EE4,word,06010000
patch=1,EE,00584EF0,word,00000010
patch=1,EE,00584EF4,word,06010000
patch=1,EE,00584EF8,word,00000010
patch=1,EE,00584EFC,word,06010000
patch=1,EE,0010222C,word,249B0000
patch=1,EE,00102230,word,0064082B
patch=1,EE,00102234,word,00000000
patch=1,EE,0010024C,word,0803FFD4
patch=1,EE,00100250,word,00000000
patch=1,EE,00100254,word,AC640174
patch=1,EE,00100258,word,03E00008
patch=1,EE,000FFF50,word,3C170064
patch=1,EE,000FFF54,word,26F77000
patch=1,EE,000FFF58,word,26F726B0
patch=1,EE,000FFF5C,word,AEFB0000
patch=1,EE,000FFF60,word,08040094`

**Comment by Buzzardsoul** [comment]
I've tested the timer's value on both pcsx2, and ps2 via opl, and it seems that the value in decimals, is typically 44 on PS2, and 24 on PCSX2. Inside of the challenges it is different but I have no idea what it should be.

**Comment by Buzzardsoul** [comment]
This means the value is 1.8x bigger on OPL, as opposed to PCSX2.

**Comment by refractionpcsx2** [comment]
the CPU is probably taking longer on the PS2, because of bus contention, cache misses etc, we don't emulate any of that.  slowing down the EE is probably the closest you can do.

**Comment by refractionpcsx2** [comment]
then there's no easy or quick solution for this, I'm afraid.
