### ISSUE TITLE
[BUG]: Local patches containing only "gsaspectratio" setting are not loaded

### ISSUE THREAD

**Issue by ribolovac510** [PCSX2/pcsx2#10625]
### Describe the Bug

After #10565 local patches that contain only the "gsaspectratio" setting are no longer loaded. Patches that also have patch= lines are loaded though.
Some games have an internal widescreen option and in those cases I was creating .pnach files to stretch the image to 16:9, for example I used:

> [Widescreen 16:9]
> description=Renders the game in 16:9 aspect ratio, instead of 4:3.
> gsaspectratio=16:9

Using patches like those and checking the "Enable Widescreen Patches" option I was getting the "1 game patch active" message when starting the game and the image was stretched accordingly. This is no longer the case, no message is shown and only patches that also contain patch= lines are being loaded.
I know that I could just set the aspect ratio in the per-game settings but I preferred the method above as the bios startup sequence was not getting stretched, as it does using the aspect ratio setting.

### Reproduction Steps

Create a local .pnach file for any game as mentioned above. Start game, image should be stretched to 16:9 instead of being 4:3.

### Expected Behavior

Old behavior as explained above.

### PCSX2 Revision

v1.7.5449

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Working as intended. I couldn't think of why you'd want to set the aspect, without a corresponding patch.

If you want to change the AR for a game that has a built-in mode, you would use Graphics -> Aspect Ratio instead.
