### ISSUE TITLE
[BUG]: Settings prompt stretched below the panel

### ISSUE THREAD

**Issue by GrimPixel** [PCSX2/pcsx2#10649]
### Describe the Bug

The lowest part of  prompt is hidden by the panel.
![button](https://github.com/PCSX2/pcsx2/assets/39795763/493d0bc0-c7f7-4c94-b370-7b0bb59684ad)

### Reproduction Steps

Just open Settings

### PCSX2 Revision

v1.7.5418

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

**Comment by refractionpcsx2** [comment]
What is your screen resolution?

**Comment by GrimPixel** [comment]
It's 1280x720 on a 1080p screen.

**Comment by refractionpcsx2** [comment]
Okay, we don't support 720 height, that's very antiquated. why not run at 1080p? can you not scale your UI if things look too small?

but height needs to be at least 768, I believe.

**Comment by GrimPixel** [comment]
Because it is a laptop. The screen is not that big.

**Comment by refractionpcsx2** [comment]
if it's a 1080p screen, then it can do more than 720.

**Comment by kamfretoz** [comment]
> Because it is a laptop. The screen is not that big.

Most new laptops nowadays have at least 1366x768 which is the minimum resolution we support.

**Comment by GrimPixel** [comment]
Thanks for the advice. It shows the buttons now in 1368x768.
I just feel comfortable to read texts in larger font. Not a big deal to change to the new resolution.

**Comment by Valtekken** [comment]
> Thanks for the advice. It shows the buttons now in 1368x768. I just feel comfortable to read texts in larger font. Not a big deal to change to the new resolution for me.

You can use UI scaling to keep the new resolution and have larger texts and UI elements:
![image](https://github.com/PCSX2/pcsx2/assets/112526564/0c252879-ef27-425f-9f74-f6a078e93783)

**Comment by refractionpcsx2** [comment]
They're on Linux @Valtekken :) But there is probably something similar they can use.

**Comment by GrimPixel** [comment]
Thank you for the tip. My distribution only supports autodetect, 100% and 200%.

**Comment by stenzek** [comment]
Both Wayland and Xorg support fractional scaling - I run 150% at 4K myself.

Anyway, like refraction said, not a bug, requiring 768 height in 2024 isn't unreasonable, otherwise we'd have to remove options and/add more tabs.
