### ISSUE TITLE
[BUG]: Pads occupying multitapped slots (B-D) are still initialized after multitap is removed

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#10650]
### Describe the Bug

Pads which are configured to be anything other than Not Connected still are initialized in memory and appear in the OSD, even after the multitap they belong to has been disabled.

### Reproduction Steps

Enable a multitap, switch one or more pads in its B-D slots to anything other than Not Connected and set some mappings to test with. Disable the multitap.

Controllers will still show up on the OSD in the bottom left, and their inputs will show as well.

### Expected Behavior

Multitapped pads should not show in the UI, and should be forced to Not Connected, if their multitap they belong to is not present.

### PCSX2 Revision

1.7.5462

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
fixed by #10661
