### ISSUE TITLE
[Language File] Language File Icon, while selecting the right language

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#1065]
Status: Low priority

It would be nice to see the language icon of the language you select. Please download the file below and rename it's ending to .rar.

I have made a picture containing all countries icons and a .ODF file, where the pixels are.

So @turtleli and @ssakash could make it per Wxwidgets?

If "ar_SA" then search in .ODF File for the countries pixel, then go and show the icon right or left behind the Language.

![example](https://cloud.githubusercontent.com/assets/16439140/12006384/97717998-abd4-11e5-884e-bb461c84b457.jpg)

![a](https://cloud.githubusercontent.com/assets/16439140/12006314/c5ddd40a-abd1-11e5-8228-59772be7a9cd.jpg)

**Comment by turtleli** [comment]
Some languages are official languages of multiple countries. Do we add all the flags? Or do we just add the "main" associated country/countries?

I fail to see how this can work. Closing.

**Comment by trader5896** [comment]
Yeah we just should add 48 languages or so..., but is this idea really so bad?

**Comment by willkuer** [comment]
Its maybe not bad for you as German. But what about the austrian or swiss guys?
English = US or UK?

The problem here is that you would like to connect flags/nations to languages. Bit these concepts are not translatable/bi-directional mappable into each other.

The idea is good. But there is no solution.

**Comment by trader5896** [comment]
For me as a German it's problematic too... Because there are tree countries using German language :"Germany, Swiss, Austria (not Australia) "

But This could be possible with another technique... Will you make it happen if I solve this problem? 

I cannot C++, but there you could help me make this happening somehow. 

I could make a new DB file with pictures and this time it will work of course... But would you make the programming part for me @turteli?
