### ISSUE TITLE
[BUG]: Welcome to Universal Studios Japan - Can't move

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#10667]
### Describe the Bug

it's like the character is stuck against an invisible wall. 

### Reproduction Steps

start a game and try to walk.

### Expected Behavior

you can move

### PCSX2 Revision

1.7.5476

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Emulation Settings

turning mVU Flag Hack off seems to fix it. Don't know if this issue requires futher investigation.

**Comment by refractionpcsx2** [comment]
Probably just needs a game db entry then, should be enough
