### ISSUE TITLE
[GSdx D3D11] GitS - SAC HUD Issue

### ISSUE THREAD

**Issue by HudsonHornet** [PCSX2/pcsx2#1066]
Workaround for latest git df356694c52601080e7807d43894b1f49f1a9f49:
Speedhack preset - 1. (Not tried other presets)

D3D11 plugin with default settings:
![gsdx_d3d_default_safest_screen](https://cloud.githubusercontent.com/assets/16260433/12007263/b72eec1e-ac0d-11e5-9ee5-3fe72445b9e6.png)
No HUD. Also, notice #1026

Next, select *CRC Hack Level - partial(OpenGL recommended)* or lower:
![gsdx_20151226200439](https://cloud.githubusercontent.com/assets/16260433/12007275/04e62bac-ac0e-11e5-8c9a-1315df83b297.png)
Graphics became weird, but HUD is visible now.

And finally, select *Texture Filtering - Bilinear(Forced)*:
![gsdx_d3d_crc_partial_bilinear_forced_screen](https://cloud.githubusercontent.com/assets/16260433/12007285/4abf3baa-ac0e-11e5-9aa9-5158c444f699.png)
Voila, looks almost like it should, except small HUD sprite alignment issues(crosshair, destination point) and console output "Please fix me! wa 0 wg 0"

**Comment by gregory38** [comment]
Or you could use openGL with accurate blending on basic (at least).

**Comment by gregory38** [comment]
Issue is limited to D3D. You can use openGL instead (note latest git version doesn't work with AMD due to an AMD driver bug). Therefore I'm closing this report.
