### ISSUE TITLE
HLE Bios ?

### ISSUE THREAD

**Issue by zminhquanz** [PCSX2/pcsx2#1068]
In the furture , could you development HLE Bios similar PPSSPP , ePSXe . Play! PS2 Emulator on Mobile is using HLE bios

**Comment by willkuer** [comment]
Somebody started that slready. The name of this project is 'fps2bios'. It still needs some love before it works and currently there is no dev around willing to tackle this project.

Also it is not really part of pcsx2 as fps2bios replaces the ps2 bios 1:1. it should not be shipped with pcsx2 to avoid possible legal matters.

**Comment by gregory38** [comment]
I'm sorry you miss Christmas by 3 days. Maybe next years ;)

So yes we could do it. It is already on the TODO list.
```
https://github.com/PCSX2/pcsx2/wiki/Contributing-%28TODO-List%29
```

There are already too much noise on this tracker so I close the issue.
