### ISSUE TITLE
[BUG]: Phantasy Star Universe & Phantasy Star Universe - Ambition of the Illuminus (US & Japan) (PAL not tested) won't boot up.

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#10681]
### Describe the Bug

Whenever I try to boot up Phantasy Star Universe and its expansion. It'll show only a black screen and hang. The dumps are fine as I tested them in PCSX 1.6.0 and they work but for the Nightly Dev versions they don't seem to work.

### Reproduction Steps

No known reproduction steps.

### Expected Behavior

Properly booting up

### PCSX2 Revision

v1.7.5485

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 3700X 8 Core Processor 

### GPU

GTX 1070 TI

**Comment by kamfretoz** [comment]
Please use our Discord for support issues
