### ISSUE TITLE
[BUG]: There is no sound in SLPS-25482 after update to newest version

### ISSUE THREAD

**Issue by CateeNavi** [PCSX2/pcsx2#10685]
### Describe the Bug

After update to newest version
I have a game called  **"Yuki Katari [Renewal Version]" SLPS-25482**  with no luck to have any audio in game.
Bios and other games do have sounds working.
The game audios will work fine in **version 1.6** and older night release I currently use **( v1.7.4928 )**

### Reproduction Steps

Just launch the game with default setting pcsx2 provide.

### Expected Behavior

Should have sound working normally just like the old versions. 

### PCSX2 Revision

v1.7.5486

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
That's a 500 build range you've given. Need to narrow it down to the exact build where it regressed.

**Comment by CateeNavi** [comment]
> That's a 500 build range you've given. Need to narrow it down to the exact build where it regressed.

I find out the right build is **v1.7.5118** when this issues begin. **v1.7.5117** works just fine.
![snap](https://github.com/PCSX2/pcsx2/assets/148787848/91539800-41f5-497c-80ee-e72687b36a0a)
It might causing by this rewrite, or some changes in this build than v1.7.5117.

**Comment by stenzek** [comment]
Awesome, thanks.

Regression from https://github.com/PCSX2/pcsx2/pull/10084.

**Comment by Mrlinkwii** [comment]
@CateeNavi  can you check #10678 for me :)

**Comment by CateeNavi** [comment]
@Mrlinkwii I downloaded 
**PCSX2-windows-Qt-x64-sse4-msvc-pr[10687]-sha[cbb2e12]-title[SPU VolumeSlide disregard phase when exp  decr].zip**
from that post.  Game audios are working in this build. Problem solved.

**Comment by stenzek** [comment]
Great. Thank you for checking.
