### ISSUE TITLE
[Feature Request]: Namco neGcon controller support

### ISSUE THREAD

**Issue by Gabriel2Silva** [PCSX2/pcsx2#10698]
### Description

As initially discussed with Stenzek and pandubz on Discord, the Namco neGcon is officially supported by a bunch of PS2 titles such as Ridge Racer V. You can technically emulate a DS2 with the neGcon, but then officially supported games won't expose neGcon calibration options or change buttons prompts to neGcon prompts (I, II, A, B).

### Reason

Would enable accurate emulation of the Namco neGcon controller in officially supported titles.
Would enable for better steering precision in racing games, considering you can't replicate the "neGcon mode" twist precision even when using it as a DualShock 2.

### Examples

![RRV](https://github.com/PCSX2/pcsx2/assets/71518165/b967ba5e-2e1b-4142-83ab-59ebad8d47e4)
Example screenshot of how Ridge Racer V behaves once it detects a neGcon controller: button prompts are changed to match the neGcon and a special "neGcon calibration" option is unlocked.

**Comment by Mrlinkwii** [comment]
Already mentioned in https://github.com/PCSX2/pcsx2/issues/4763

**Comment by Gabriel2Silva** [comment]
Here's some footage (original hardware capture) demonstrating the special neGcon options exposed by Ridge Racer V (SLUS-20002) once it detects a neGcon controller.

https://github.com/PCSX2/pcsx2/assets/71518165/26332588-0f36-4aac-a149-88cc27dc45fa

**Comment by Xenphor** [comment]
It would be really nice to have analog controls in RRV.
