### ISSUE TITLE
[Feature Request]: `Debugger` Functions - Adding `column labels` to the functions view

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#10692]
### Description

Currently the functions view does not have any column labels. It would improve the user experience if both of them have a simple label like `Memory Address` and `Function Name`:

![Screenshot 2024-01-21 073707](https://github.com/PCSX2/pcsx2/assets/37260321/b639c5bf-0716-4f20-955f-a89cc2e61488)

### Reason

This is a Quality-of-Life feature request for the PCSX2 debugger.
This would make sure the user instantly knows what each column represents.

### Examples

Other Debugger views already have this, for example the `Registers` VU0f view:

![Screenshot 2024-01-21 074911](https://github.com/PCSX2/pcsx2/assets/37260321/828aa570-1437-4444-b4b5-e82ac571f874)

**Comment by Risae** [comment]
I noticed that quite a lot of views do not have any column labels. I'll keep this Issue for the Functions View for now.

**Comment by Mrlinkwii** [comment]
this was fixed in #10224
