### ISSUE TITLE
[BUG]: Input recording errors when loading save state while paused

### ISSUE THREAD

**Issue by kamijoan** [PCSX2/pcsx2#10704]
### Describe the Bug

When recording inputs using save states I noticed that there's inconsistencies on the inputs played when loading a state mid-recording. This is not about random numbers or being deterministic, there's 2 different and consistent situations that happen.
While you are playing an input recording and:
1. When you load state while the emulation is paused and then resume it.
2. When you load state with the emulation running.

The second situation replays the correct inputs as if you just played the recording from the start, the first situation seems to skip some of the first few inputs that should happen right after it loads, that what it seems to me but I can't really be sure what it's actually happening there.

### Reproduction Steps

Have an input recording, or be mid-recording it.
Have a save state in some point in the middle of that recording, preferably right before complex inputs or something that should be easy to notice that the end result changes.
Playing the recording.
Loading that save state while the emulation is running normally, probably seeing the normal result.
Pausing the emulation, loading the save state and resuming the emulation, the result should be different as something probably happened to some inputs.

### Expected Behavior

Seeing no change to the inputs when the state is loaded while paused. It can be seen while playing, but I'm sure it also happens while recording, so constantly loading state while recording inputs leaves some "damaged" spots in the recording itself.

### PCSX2 Revision

v1.7.5483

### Operating System

Windows 10 (64bit)

**Comment by CoopeZz** [comment]
I experience same issues described here.

The analog inputs seems to be affected most. I tried to break a session where digital inputs were used only and it looks promising. Pausing desync recording for some reason, criticals are loading screens and similar parts of the games. I dont use frame-skipping.

**Comment by kamijoan** [comment]
Looks like the same as this and it's better explained or at least understood.
https://github.com/PCSX2/pcsx2/issues/11454
