### ISSUE TITLE
[BUG]: Wipeout Fusion menu screens have graphical issues

### ISSUE THREAD

**Issue by PoloniumRain** [PCSX2/pcsx2#10703]
### Describe the Bug

Some of the menu screens have misaligned and/or stretched graphics. Here is an example on the Time Trial track selection screen:

![TimeTrialMenu](https://github.com/PCSX2/pcsx2/assets/50634894/09135a60-fa9b-42db-b58d-9200fbaa88b1)

Left is real hardware, right is PCSX2. 

I've highlighted the most obvious issues with arrows but pretty much the whole screen is vertically stretched and some graphics are misaligned.

### Reproduction Steps

Start the game and go the the menu screen. Go through each submenu (Arcade, Time Trial etc) and many will have the above issues, but it's maybe the most obvious on the Arcade and Time Trial track selection screen (shown in the above image).

### Expected Behavior

Menu graphics should be in the correct proportions and properly aligned.

### PCSX2 Revision

1.7.5499

### Operating System

Windows 10 (64bit)

### CPU

AMD Threadripper 3960X

### GPU

Nvidia RTX 3080

**Comment by refractionpcsx2** [comment]
Can you provide a GS Dump please

**Comment by PoloniumRain** [comment]
You're right. It seems to have been due to a setting i had enabled, but i thought they were all set the default when they weren't. Sorry about that! I'll close this then.
