### ISSUE TITLE
[BUG]: the emulator not appearing in discord profile status win11

### ISSUE THREAD

**Issue by Renard88** [PCSX2/pcsx2#10718]
### Describe the Bug

i just downloaded the latest nightly version and when open the emu not appearing in discord even when i checked the discord option in emu setting and i tried to close discord and the emu many times also tried to open them as administrator and still not appearing.

the strange thing the old ver of emu appear in discord without problems but the problem only happened with nightly ver

### Reproduction Steps

just running the app and went to discord and nothing appear there even if game run 

### PCSX2 Revision

v1.7.5509

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
Not a bug you need to add nightly directly to Discord to get it detect PCSX2.
