### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by Derpolino** [PCSX2/pcsx2#1071]
Hello, I have a problem, when i select iso, start it, it doesn't work ! :(

There is nothing that opens :/

Look this :
![Screenshot](http://i.imgur.com/kUMAoFC.png)

Please help :/
(Sorry for my english, I'm french c:)

**Comment by ssakash** [comment]
please direct support questions at the forums : http://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows

**Comment by gregory38** [comment]
Regardez le forum s'il vous plait ;)
