### ISSUE TITLE
Time Crisis 2 and 3 (NTSC-U) Split Screen Issue

### ISSUE THREAD

**Issue by jinwk00** [PCSX2/pcsx2#1073]
Only half of the screen (1P) is shown inside the game. 
![tc3_cutscene](https://cloud.githubusercontent.com/assets/15257326/12027177/8677524e-ad90-11e5-9820-5f9efd472a48.png)
This is the cutscene part(which needs to look like this way), but
![tc3_ingame](https://cloud.githubusercontent.com/assets/15257326/12027179/930f7fea-ad90-11e5-9030-6efdf104f4fd.png)
This is the in-game part. It only shows 1P, and reduces resolution by itself to fit into screen.

This issue is related to https://github.com/PCSX2/pcsx2/pull/1067

**Comment by jinwk00** [comment]
Bump? Still no good, everything is still zoomed in.

Note on the top 640x448 turned into 320x224.

**Comment by willkuer** [comment]
I think you need to wait a bit longer. Some issues like this dont get fixed for years as we are lacking devs. Fortunately there was a lot of fighting with aspect ratios and resolutions recently and possibly there is currently some knowledge present in some heads - even if i think your proposed hack is pointing somewhere else. Additionally the devs are currently preparing a release and have a lot of work.

Bumping issues is often not needed and doesnt accelerate improvements. Especially not on a weekly base. Providing additional information is nive though.

**Comment by gregory38** [comment]
Do you have the bug in both SW and HW renderer? Or only the latter.

**Comment by jinwk00** [comment]
I know what HW Rendering is, but what is SW Rendering?

**Comment by jinwk00** [comment]
Nope. Still no good. Still says 320x224 on top on software also.

**Comment by ssakash** [comment]
This is an issue with co-ordinate handling so yes, it should probably be present at all renderers.

@gregory38 

The code actually makes a bit sense:

``if(src[i].right - src[i].left == 0.5) {``
``src[i].left = 0;``
``src[i].right = 1;``
``dst[i].top += dst[i].bottom*0.25;``
``dst[i].bottom -= dst[i].bottom*0.25;``
}

maybe it's a special case for handling the splitscreen modes ?
