### ISSUE TITLE
[BUG]: Texture Replacement shown in poorer quality for some textures when in Vulkan - Steam Deck

### ISSUE THREAD

**Issue by zealvix** [PCSX2/pcsx2#10748]
### Describe the Bug

Textures looking noticeably worse (jaggy/lower resolution) despite being loaded successfully.
This only occurs when using "Auto" or "Vulkan" on Steam Deck/SteamOS, using "Opengl" textures shows correctly.

Not sure if this is specific to Steam Deck (drivers used?) or a problem with the Linux build in general, do not have an alternative Linux device to test.

Tried a number of texture packs/games and noticed the same issue.
Suikoden V (https://gbatemp.net/threads/suikoden-v-usa-hd-remaster-widescreen-texture-pack.609820/) used below as an example as the issue can be observed easily at the title page.

Issue to affect mainly 2D stuff like icons, text and similar image, and does not occur (or maybe its not as as visible) on textures on 3D models etc.

### Reproduction Steps

1. Setup PCSX2 for texture replacement for the game used (e.g Suikoden V), use higher than native resolution (2x or 3x is fine).
2. Boot up the game with default/vulkan renderer, press start to reach the main screen (or any area where textures should be replaced), take note of the quality of the textures replaced (or use a screenshot/photo).
3. Without exiting/restarting, change the renderer to OpenGL, you should see a massive change/difference in the texture quality shown after a few seconds.

### PCSX2 Revision

v1.7.5531

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Steam OS 3.5.7 - Stable

### CPU

Custom AMD Zen 2 cpu - 4 cores up to 3.5ghz

### GPU

Integrated RDNA2 8 CUs

### GS Window Screenshots

No custom textures
![steamdeck_no custom textures](https://github.com/PCSX2/pcsx2/assets/37977511/eacd087b-3423-42f9-b0da-9bcd76bc5002)

Custom texture - OpenGL
![steamdeck_opengl](https://github.com/PCSX2/pcsx2/assets/37977511/6488d8c8-f708-4835-9211-bfe04a8eb873)

Custom texture - Vulkan
![steamdeck_vulkan](https://github.com/PCSX2/pcsx2/assets/37977511/3d32077c-e0c7-4339-b040-960cb1e1ca27)

Comparison of the textures using opengl and vulkan, where opengl looks correct while vulkan is not.
Replacement textures are confirmed to have loaded (title changed to "HD remaster") even when using vulkan.

Same is observed when on external monitor, or on the inbuilt screen.
Running the game in game mode or when in desktop mode does not make a difference.

**Comment by stenzek** [comment]
Sorry, we can't support potentially-illegal distributed texture packs. The replacement feature is intended only for your own use.
