### ISSUE TITLE
[BUG]: Non-hexadecimal keys write 0 in Memory Viewer

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#10745]
### Describe the Bug

Pressing `G` key in Memory view writes `0` (nibble) to current cursor.
- `G` key is hotkey for "Go to address", but it somehow writes 0 to emulated memory.

### Reproduction Steps

1. Start PCSX2
2. Run a game
3. Open Debugger
4. Pause the game
5. Select non-0 nibble in Memory viewer
6. Press `G` key

### Expected Behavior

`G` key should just open "Go to address" without modifying emulated memory.

### PCSX2 Revision

v1.7.5531

### Operating System

Windows 11

### Logs & Dumps

https://github.com/PCSX2/pcsx2/assets/91955473/9aa152e5-b5e3-45a5-92be-53c00daf0064

**Comment by TheTechnician27** [comment]
I was able to reproduce this. I'll glance over the code on MemoryViewWidget.cpp, but I doubt I'm competent enough to find what the issue is.

**Comment by TheTechnician27** [comment]
This is going to sound absolutely demented, but there's a switch statement whereby the escape key writes a 0 to the currently selected nibble. Is it possible that the G key is simultaneously being processed as Qt::Key::Key_Escape and the G key for the goto prompt?

**Comment by TheTechnician27** [comment]
The h key also writes 0 to the nibble, so I'm actually wondering if it defaults to 0 if it's not 1–9 or a–f.

**Comment by Berylskid** [comment]
That sounds right. `Ctrl` + `G` works as goto but without writing `0`.
