### ISSUE TITLE
[BUG]: Clumsy Shumsy doesn't get beyond memory card screen.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#10744]
### Describe the Bug

game gets to a memory card screen.. goes no further. no button inputs accepted. Pad problem? Memory Card problem? timing issue? i don't know. 

### Reproduction Steps

just start the game. it'll get to the memory card screen on it's own and softlock

### Expected Behavior

be able to get further and play the game

### PCSX2 Revision

1.7.5531

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

**Comment by refractionpcsx2** [comment]
Can confirm it doesn't respond to the pad (Eyetoy detection seems fine).

Last config is
 [Pad] DS2 Config Finished - P1/S1 - AL: Off - AB: Usable - VS: Disabled - VL: Disabled - RB: D (0x00000000)

However, the wiki also notes slowdown/freezing is the eyetoy is connected, so it could still be that, but seems somewhat unlikely.

**Comment by prafullpcsx2** [comment]
False report. Game is playable.

**Comment by refractionpcsx2** [comment]
oh, it requires eyetoy input, makes sense.

**Comment by seta-san** [comment]
can you get the buttons to activate? the video feed is too much of a slide show to be able to activate them for me.

**Comment by refractionpcsx2** [comment]
You need to reconfigure the framerate of your camera.  Prafull sent me a video of it working absolutely fine for him (not public for doxx reasons ofc)

**Comment by seta-san** [comment]
Do we know what the frame rate should be?

**Comment by refractionpcsx2** [comment]
Not sure, he said "it was set to 30fps, so I set it to full and that fixed the problem"

**Comment by seta-san** [comment]
Is that something we have to setup in our OS? Or can the emulator force it?

**Comment by prafullpcsx2** [comment]
Yes you need to increase fps to maximum supported by your webcam either through your webcam settings or you can do the same through obs too. Game works almost perfect.

**Comment by seta-san** [comment]
i found my camera's problem. it only supports 30fps no matter how low the resolution.

**Comment by refractionpcsx2** [comment]
Then it's insufficient as an eye toy :P
