### ISSUE TITLE
[Feature Request]: Removing of duplicate "Setting" line from the "System" tab

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#10750]
### Description

There are two "Settings" option line, which have completely similar functions: one is inside the "System" tab, and the second one is right next the "System' tab. The "system-tab-inside" one can be erased as useless.

### Reason

Getting rid of the unnecessary duplicate option makes the interface more compact.

### Examples

.

**Comment by AmyRoxwell** [comment]
Could you please describe the request better? maybe even take some pictures, cuz right now its not very clear what you mean :b

**Comment by Daniel-McCarthy** [comment]
These are not duplicates, the one in `System` is for PCSX2 specific settings (which makes sense to be under system IMO) and the `Settings` menu to the right is for game specific settings, which is an entirely different set of menus/configuration.
The only redundancy is in naming.

**Comment by refractionpcsx2** [comment]
> These are not duplicates, the one in `System` is for PCSX2 specific settings (which makes sense to be under system IMO) and the `Settings` menu to the right is for game specific settings, which is an entirely different set of menus/configuration. The only redundancy is in naming.

actually the settings menu is the global settings, unless you choose "game properties", then it goes tot he per-game settings.

So technically it is duplicated, yeah

**Comment by OnlyVoidd** [comment]
Apparently the settings button in the "System" tab is required for macOS users, see commit 7a4ef32210a6a25aa47e17c19ed5e55f93adc3aa

**Comment by F0bes** [comment]
Closing as it's not a large issue and removing the Settings from the Menu option will probably break some users workflow at this point.
