### ISSUE TITLE
[BUG]: NTSC custom rate limiting not applied to PAL game

### ISSUE THREAD

**Issue by ameenross** [PCSX2/pcsx2#10756]
### Describe the Bug

I'm running GT4 with a 480p patch for vastly improved graphics. However, the game engine will run the physics as if it were running at 50fps, but PCSX obviously switches to 59.94 by default. This causes the game to run too fast. So we need to slow it back down to 50fps. Currently I'm doing that by abusing the slomo mode at 83.4%. However, ideally I'd like to use a custom NTSC frame limit for this in the game properties. The value I enter there, however, is not respected.

![image](https://github.com/PCSX2/pcsx2/assets/859737/828cb062-a1ce-4a06-baf6-cd8fa52c1a56)

PAL limit *is* respected:
![image](https://github.com/PCSX2/pcsx2/assets/859737/ab650ba5-7abc-450b-8af2-b1fb6a140670)

NTSC limit is *not* respected:
![image](https://github.com/PCSX2/pcsx2/assets/859737/a111bb18-169f-454c-ab50-e5fe1a0439ad)

### Reproduction Steps

- running GT4 PAL (SCES 51719)
- went to game properties and entered some custom values for rate limiting; 30 for NTSC mode and 25 for PAL mode, just as an experiment
- applied a 480p patch
- game switches to 480p with NTSC frame limit (59.94) in the race, instead of the 30 I entered

This is the patch I applied:

```pnach
patch=1,EE,20A57E70,extended,00000001
```

### Expected Behavior

I expected the screenshot showing `SDTV 480p Progressive` to show a frame limit of 30 instead of 59.94

### PCSX2 Revision

v1.7.5536

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22 LTS

**Comment by refractionpcsx2** [comment]
There is no limit change for 480p, that is a completely separate mode right now, so it would need an additional setting in there.

If somebody fancies adding it, then, sure, but right now, it's not possible without hacking the code, I'm afraid.

**Comment by ameenross** [comment]
Hmm, alright. Well I just though of a slightly better workaround. I can set the PAL frame limit to 59.94% and then run the game at

- 83.4% in normal speed mode (25 FPS)
- 166.8% in fast-forward mode (50 FPS)
- 41.7% in fast-forward mode (100 FPS)

It's a little bit finicky, but I guess at the end of the day it does get the job done. Thanks for your response, and thanks for all your efforts on the emulator, of course!

**Comment by refractionpcsx2** [comment]
No problem :) Thanks!
