### ISSUE TITLE
[BUG]: FFX International will not boot if you have network settings enabled but no HDD image.

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#10754]
### Describe the Bug

Trying to boot FFX International (Jp) while having Ethernet enabled will cause the game to fail to boot, leaving just a black screen, happens also on windows.
(Basically It won't boot if you have DEV9 enabled without providing any HDD image.)
![Screenshot_01312024_192556](https://github.com/PCSX2/pcsx2/assets/89411895/8c7d4982-5aaf-45c0-bc9b-b3242419dee4)
You can workaround it by creating or using a HDD raw image, doesn't need to be formatted.
![Screenshot_01312024_192657](https://github.com/PCSX2/pcsx2/assets/89411895/9432c083-aa04-4d98-aac8-e70458b09ee1)

### Reproduction Steps

1. Enable Ethernet on game properties or globally
2. Try to boot the game.

### PCSX2 Revision

v1.7.5535

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

### CPU

Ryzen 5 5600

### GPU

Rx 6600

**Comment by Mrlinkwii** [comment]
its been noted it happens on windows iswell

**Comment by AmyRoxwell** [comment]
> I've tested it myself but I dunno if you wanna test #10761 too
The issue is solved with that Pr :D!!
![Screenshot_02032024_004411](https://github.com/PCSX2/pcsx2/assets/89411895/f161cb98-311b-43db-8f4e-3c7268d48a26)

![Screenshot_02032024_004432](https://github.com/PCSX2/pcsx2/assets/89411895/07fa7394-ca36-4c6a-a7ff-be4080842df8)
