### ISSUE TITLE
Issue with Vsync and OpenGL Fullscreen tearing

### ISSUE THREAD

**Issue by tsunami2311** [PCSX2/pcsx2#1075]
http://forums.pcsx2.net/Thread-Slowdown-when-using-V-sync-and-OpenGL

**Comment by Sagnip** [comment]
Hello, I'm the original poster on the forum. Just to make things simpler I will explain the problem here:

Basically, If you enable Vsync while using the OpenGL backend it causes slowdown.
This occurs when using the PCSX2 setting, and also occurs if you activate Vsync through driver software (with setting off in PCSX2).
This occurs in all games, regardless of any other settings (or at least any I've tested).
Slowdown only occurs in fullscreen when Vsync is on (because Vsync only takes effect in fullscreen).

**Comment by tsunami2311** [comment]
forgot the part about opengl in fullscreen is tearing, before one didnt need to check vsync in pcsx2 keep fullscreen from tearing, my original coment about it could be something nvidia mucked up in 361.43 drivers, and i to lazy to down grade to find outm if it drivers or pcsx2 builds.

I know there was some change in reguards to vsync a while back, not sure if that has anything to do with it

**Comment by Sagnip** [comment]
Yep, that is probably it, that is why I was getting confused in on the forum because I'm almost certain OGL is in exclusive fullscreen. There are quite a few things that point towards this that I mentioned there, I had just assumed all the backends were that way but after looking OGL seems to be the only one using exclusive.

So, basically we need 2 fixes:

1. Make OGL's fullsceen borderless fullscreen (This will eliminate the need for Vsync for those who have Aero running.)
2. fix Vsync in OGL for people who don't have Aero.

**Comment by Blackbird88** [comment]
Can confirm. With D3D11 there is no tearing at all in fullscreen (I don't even need Vsync) 
While with OpenGL in fullscreen there is tearing everywhere.

**Comment by vsub** [comment]
There is something else too...while vsync is enabled and using OpenGL,you can't go above your screen refresh rate when you disable the fps limit...you can't also use the Turbo(TAB)

You can while using DX and you still will not see screen tearing even if you are running at above full speed

You see screen tearing even while using slow motion while vsync disabled in OGL mode

**Comment by Sagnip** [comment]
seems about right OGL in 16:9 is exclusive, needs to be changed.

**Comment by willkuer** [comment]
All of you know that we have like one thread per week requesting exclusive fullscreen instead of borderless windowed because borderless is soooo bad?

**Comment by Sagnip** [comment]
No, I'm just saying exclusive would be a good option for those who don't have Aero (so they can have no screen tearing too) Also the main point is that OGL is in exlcusive fullscreen right now, and it is causing issues with trying to apply Vsync, it needs to be changed TO borderless

**Comment by tsunami2311** [comment]
@Sagnip 

You are right setting pcsx2 to 4;3 = Opengl Windowed(fullscreen) setting pcsx2 to 16:9 or stretched= Fullscreen exclusive, which explains the why it needs vysnc enable to not tear. question is why is opengl acting like this while DX yes windowed boardless for all? fix so they all use windowed borderless would be great. seeing i use only opengl these days

I also prefer Windowed fullscreen and have for very long time, I never liked the delay from exluclisve when tabing out of games. that and i like windows aero verison more, it removes tearing but dont limit to monitors hz

**Comment by Sagnip** [comment]
The only reason I said it needs an exclusive toggle for people that don't have Aero is because (at least to my knowledge) you can't apply Vsync to a windowed application (borderless or w/e not counting Aero) it would have to be applyed to the Operating system.

Now it may be possible to apply Vsync globally to effect the OS using driver software if Aero is disabled (someone would have to test this that is on an OS that they can disable Aero on.)

**Comment by gregory38** [comment]
See also #842

**Comment by Sagnip** [comment]
Thanks Gregory, both issues are caused by the same thing once 16:9 OGL gets a borderless fix it will should allow higher framerates with Vsync like the other Backends allow too.

**Comment by tsunami2311** [comment]
it was working correct with earlier builds recent build started acting like this,

Windows aero AKA windowed and windowed fullscreen are only thing that allow no tearing and no hz limit, actual Fullscreen exclusive will limit to hz of monitor, and yes disable aero in win7 will result in forcing vsync will not stop tearing in anything but fullscreen exlucsive, i still dont see why one would disable it out side win7 it not simple to do, atlest i never found simple way.


put opengl fullscreen16:9 and stretch  back to windowed fullscreen like it was  in earlier builds like month ago or more, in last few days i start geting build but i didnt note which one i had cause i didnt think opengl would some how get switch to fullscreen exclusive  when 16:9 or stretch is used.

**Comment by tsunami2311** [comment]
i just went back to 56f2e74 build which long before i start changing git builds i think. it still happen to switch to fullscreen exclusive for 16:9 and stretch for opengl, DX11 is uneffect

are we all using Nvidia drivers that reporting this? and if so what drivers ? im on 361.43 maybe nvidia drivers are to blame? dont know but need to get switch back to windowed fullscreen  again.

**Comment by Sagnip** [comment]
I sort of doubt drivers are making the PCSX2 launch in exclusive fullscreen... maybe you just didn't notice the tearing before?

**Comment by tsunami2311** [comment]
possible but for most part when launch PCSX2 i go in to fullscreen mode, besides nvidia and drivers have cause issues before, so not out of the realm of possiblity.

Then again test again hour ago and Opengl was launching in  full screen exclusive  which i know it never did before, and i only saw tearing cut scene videos like the FFXII intro video but not in the actual game

**Comment by tsunami2311** [comment]
just went back as far as gaa8f584 Opengl FUllscreen is tearing, where it was not before and it is using Fullscreen exclusive to .

At this point  i think it nvidia drivers changed, that are causing this tearing, cause I never had tearing in opengl ever before nor didn pcsx2 ever have opengl run in full screen exclusive

Seeing i would out right noticed the delay and tearing is one thing I would never put up so i would notice that instantly.

**Comment by gregory38** [comment]
The window creation is done by the core. Core isn't aware of the API (or the GS plugin). So if behavior is different, it must be driver overwritting the behavior. Might worth to check the hidden option of the driver.

**Comment by Sagnip** [comment]
A good way to find out would be to see if someone with AMD drivers is having the same issue

**Comment by tsunami2311** [comment]
@gregory38 what hidden options? but know when I start using win10 and initial drivers for nvidia 16:9 mode was not going to fullscreen exclusive, seeing as i refuse to do anything with out vsnyc so i know when thing start tearing, also know some of the initial nvidia drivers for win10 had bug where  vsync would randomly not work

**Comment by vsub** [comment]
I found something interesting(maybe it will help finding the problem)
Depending on your desktop resolution,you will not get screen tearing(vsync disable)

800x600 - only 16:9 don't get screen tearing
1024x768 - only 16:9 don't get screen tearing
1280x800 - tearing only while using stretch
1280x1024 - tearing only while using stretch
1366x768 - tearing only while using stretch and 16:9 looks like stretch(perfect full screen without black borders)
1440x900 - tearing only while using stretch
1600x900 - no tearing only with 4:3
1680x1050 - tearing only while using stretch(barely visible)
1920x1080 - no tearing only with 4:3

**Comment by tsunami2311** [comment]
tearing is simply happening cause 16:9 and stretch in Opengl for what ever reason is using fullscreen exclusive, so unless have forced vsync on ins pcsx2 or nvcp it gona tear. which also why opengl 16:9 and strech both have slight delay and black screen flash when tabing.

No mode of pcsx or GSDX has actual had fullscreen exclusive since .98 it annoying bug where the bug is coming from i dont know,  at some point i might test the first drivers for win10 which was around time i was play FFXII in fullscreen 16:9 and there was no tear and wasnt using fullscreen  exclusive either. (win10 10240 builds)

Drivers? PCSX2 change? Win10 Change 10240 builds (June ~sept) vs TH2 10586 builds (november ~ current release)? dont know but never did any this before

Find out why opengl in 16:9 and stretch is using fullscreen exlucisve and put back to windowed fullscreen and there wont be issue.

1920x1080 here

**Comment by vsub** [comment]
Ok I found a way to "fix" it.
It works while using 16:9/Stretch(it will not work on Win8 if you use metro start menu)

Go fullscreen=>press the windows key to exit from exclusive fullscreen=>click on the taskbar to close the start menu=>click on the game window to hide the taskbar

And here,fullscreen(16:9/stretch),no screen tearing and no frame drop

**Comment by tsunami2311** [comment]
guess what I just found out the problem... it Nvidias drivers. went back 353.62 there first win10 drivers.

test opengl 16:9 and stretch and it in windowed fullscreen mode and there so there is no tearing and no delay and black screen flash when tabing. i gona reboot and test again. but at this point it got to be drivers,

**Comment by tsunami2311** [comment]
wow it get more intresting the more i dig..

353.62 + g223b7da = Opengl 16:9 and Stretch Windowed Fullscreen
356.62 + gac0d7f7 	= Opengl 16:9 and stretched Fullscreen exclusive.

So that means some thing went wrong with one nvidia drivers after 353.62 and something went wrong with pcsx2 since g223b7da.

If some one else using Windows 10 want to test 353.62 drivers and  the g223b7da in opengl 16:9 and stretch in fullscreen to comfirm my find tha would be great. cause i that to think i imagining things now

**Comment by vsub** [comment]
If you don't do it right(if it's actually possible on Win10)the screen will blink when you return to the game and that means you are back to exclusive fullscreen.

This seems to work even better(at least here)
Go fullscreen=>press the windows key=>click on the GSds window in the taskbar(not somewhere else)
I tried this at least 10 times and the window never blinks and the taskbar disappear

**Comment by tsunami2311** [comment]
No go on win10 screen blinks and remains in fullscreen exclusive. From what I found out from my tests  it combination of what nvidia did to there drivers since 353.62 which gathering happened in either (355.60,355.82 or 355.98) cause 358.50 is bugged and what happen after https://github.com/PCSX2/pcsx2/commit/223b7daa1d625a93dbb7daf9d7d2490544172526 build.

Like said some else need to test  353.62 drivers and https://github.com/PCSX2/pcsx2/commit/223b7daa1d625a93dbb7daf9d7d2490544172526 to see if it working in  in windowed fullscreen.

**Comment by tsunami2311** [comment]
I reported this to nvidia atlest the part thats cause by them but nvidia wont dont do anything about, like they didnt about the dx11 stretching/zoom bug.

some were along the line something also went wrong in one of pcsx2 builds. after 223b7da build

**Comment by zaps166** [comment]
V-Sync doesn't work on Linux and nVidia proprietary drivers. It ignores V-Sync option in nVidia panel and pcsx2 configuration.
V-Sync is always enabled on Intel drivers (vblank_mode=0 to disable on Intel).

I don't use compositing.

**Comment by tsunami2311** [comment]
dont know about linux but in windows if you disable composition which disable the "aero" and its built in vsync,  no amount of  change in the  game or nvcp of vsync will enable vsync in windowed program, both settings only apply to  FULL SCREEN EXCLUSIVE programs, no windowed or windowed fullscreen program will be effected there for they will tear if you disable aero ( which really only doable on win7 in 8 or higher it more complicated to disable aero). 

There is possibility this happens in linux too if compositing is same thing, but seeing i never used linux i dont know.

**Comment by zaps166** [comment]
OpenGL compositing on Linux/X11 is the same thing like DWM(Aero) on Windows. So without compositing vsync is required for all applications to prevent tearing. With tripple-buffering works very fast (as fast as without vsync, but no tearing and it also limits frames to refresh rate).
On Windows 7/8/(10?) in exclusive full screen DWM/Aero is automatically disabled on nVidia and AMD drivers, but probably not on Intel.

In Pcsx2/Linux, V-Sync doesn't work (GS Window) and it also ignores V-Sync set in nVidia panel, but on Intel drivers V-Sync is enabled every time and the only way to disable is use env. variable "vblank_mode=0".

For GSdx developers: On X11/Linux there are (at least) 3 different functions to V-Sync. Two of them are necessary to set V-Sync on different drivers. Here is an example for Windows and Linux/X11 with proper priority (glXSwapIntervalMESA as first, glXSwapIntervalSGI as second): https://github.com/zaps166/QMPlay2/blob/b6bfd92a5c2640eafc675b1246ade43e4e50e0a2/src/modules/OpenGL2/OpenGL2Writer.cpp#L367

**Comment by tsunami2311** [comment]
likes i said NVCP settings for vsync are IGNORED for all things windowed, it only applies to fullscreen exclusive. keeping composition enabled is only way i know of keeping windowed programs from tearing.

which from what you said is same issue on linux. it either a driver issue or os issue, in windows xp i had vsync enable by defualt to keep windowed and fullscreen exlcusive from tearing in windows 7 and up it been set to  program decide, cause of aero has it own verision of vsync, also dont see why anyone would disable aero/composition either tearing is ugliest thing be it windows or linux

**Comment by zaps166** [comment]
I can see glXSwapIntervalEXT in code, I didn't notice it earlier. It works on nVidia, but probably not on Intel/Mesa (consider to use glXSwapIntervalMESA and glXSwapIntervalSGI).

I debugged the code and V-Sync doesn't work, because Pcsx2 always passes 0 to the function ignoring settings in pcsx2. "Config->Emulation settings->GS Window->Wait for Vsync on refresh" is checked, but in "void GSWndOGL::SetVSync(bool enable)" - "enable" variable is always "false". When I pass "1" to the function, then Vsync works properly.

Vsync doesn't slowdown the game if triple-buffer is enabled in OpenGL. With Vsync I'm able to set proper monitor refresh rate and disable frame limiting. If anyone has slow down with Vsync - enable triple-buffer, on OpenGL it works very good!

I recommend to use tri-state checkbox: disable, don't change (drivers default), enabled. Currently (on Linux, I don't know about Windows) it is always disabled!

**Comment by gregory38** [comment]
Vsync is disabled if you disable frame limiting. The logic works this way.

**Comment by zaps166** [comment]
Ok, thanks, it works with enabled frame limiting (the vsync doesn't apply when game is running - why?).
It is good logic to disable vsync when frame limiting is disabled, but when vsync is enabled __and__ frame limiting is enabled the it can cause slow down especially without triple-buffer, right?

It is fine to play PAL game on 50Hz refresh rate and NTSC game on 60Hz refresh rate (0.001% faster :D) and then if someone know what he does - frame limiting is not needed. Vsync does the limit.

It will be nice to have one more checkbox :)

I must try "glXSwapIntervalEXT" on Intel/Mesa. As I remember - it doesn't work there.

Thanks for great work - currently pcsx2 works much better on Linux (force feedback due to SDL2, OpenGL on GSdx)! I tried it also a few years ago and it was unusable on Linux :D

**Comment by tsunami2311** [comment]
@zaps166 

yes i am sure, forcing Vsync in NVCP has not work for worked in windowed programs since  win7, IF desktop composition is disabled.this true for both opengl and dx.

Win7 and up use Aero/desktop composition version of vsync which eliminates   tearing  withOUT cap framerates at monitor hz limit.

And as mention at current Opengl is being sent into Exclusive Fullscreen with 16:9 and stretch, which combination of nvidia driver issue and something thent went wrong in pcsx2 builds. which  which i proved with my test above on my system.

**Comment by tsunami2311** [comment]
just test latest build 41d13dc

Tearing in  opengl 16:9 and stretch mode still happens, cause it still getting forced into  fullscreen exclusive. with 361.43

353.62 up to this build 223b7da  opengl in 16:9 and stretched run in windowed fullscreen like it should. 353.62 and 41d13dc force 16:9 and stretched into fullscreen exclusive. 

with 353.62 with 223b7da  and any builds after words?( question mark is there cause i not entirely sure which build  is where pcsx2 went wrong in this equation drivers force opengl 16:9 and stretched into fullscreen exclusive.

Just know both nvidia drivers and pcsx2 build are to blame, dx is not effected. weather this makes sense to gregory i dont know.

Likes said i will keep and on on newer builds and newer nvidia drivers to see if nvidia fixes what they broke on there end.

**Comment by MrCK1** [comment]
I was poking around in the code; and I did find that some GS stuff looks a bit old/hacky. It has references to VSync and frame skipping. I don't know if talking a look at this code may help in the future.

https://github.com/PCSX2/pcsx2/blob/master/pcsx2/GS.cpp
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/GSState.cpp

**Comment by tsunami2311** [comment]
someone else on Windows 10 64bit (preferable) cause that what i tested this on

Need to test
353.62 + 223b7da 
and see if  Opengl in 16:9 and Stretch use windowed fullscreen (dbl click the window) tabing out will be instant and there will be NO screen flashing black

then test

353.62 + ac0d7f7 
and see if OpenGL in 16:9 and stretch mode are using Fullscreen exclusive (dbl click the window) tabing out will NOT be instant and it will result in the screen FLASHING black

I cant be the only person that can test this... this alone tells me something in pcsx2 changed between those builds. other wise both builds would be using windowed fullscreen. if something didnt change please explain how 1 build on the same drivers results in windowed fullscreen like it should while later builds results in Fullscreen exclusive. 

361.43 + 223b7da 
do fullscreen exclusive regardless. Probably is 2 things not just drivers Again 4:3 mode is not effect with this forcing of fullscreen exclusive  16:9 or Stretch must be set in GS Window

**Comment by tsunami2311** [comment]
issue still happens with 361.93 nvidia drivers when using Stretch/16:9 opengl fullscreen exclusive is still forced.

And 361.93 with 223b7da still forces fullscreen exclusive with setting above. 

353.62 + 223b7da work proper, and use fullscreen windowed correct, so this issue is still  both drivers and pcsx2..

and i see no one really tested what i asked either.

**Comment by Sagnip** [comment]
Link me to everything I need for those 2 test scenarios and I will test them, I just kinda gave up on this because it seems no one really cares, and now just use a AHK scrip that can put programs in borderless windowed mode.

**Comment by tsunami2311** [comment]
http://www.nvidia.com/download/driverResults.aspx/87791/en-us
353.62

http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-740-g223b7da&platform=windows-x86
223b7da 
Dbl click the window it will go in Windowed fullscreen (borderless) in opengl   **16:9/stretched/4:3** 

http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-1579-gac0d7f7&platform=windows-x86
ac0d7f7

Dbl click the window it will go into Fullscreen Exclusive in opengl  **16:9/stretched** this will in turn cause tearing cause vsync is not enabled in pcsx2 and aero does not effect fullscreen exculisve the game will also flash black screen and have second delay before start menu appears and the game image is returned   4:3 uneffected

If pcsx2 is left in 4:3 mode in any build or any driver windowed fullscreen (borderless) is used
You can pretty much test any recent nvidia driver with the 223b7da  and it will force fullscreen exclusive in both builds.

DX11 is unffected by any of this.

If you have the same results as i do then it both nvidia issue and something that went wrong in pcsx2 between 223b7da and ac0d7f7 all test done on windows 10 64bit

**Comment by turtleli** [comment]
Maybe it's related to the wx3.0 change. I suggest testing v1.3.1-807-g5c58bd2 and v1.3.1-813-g7aa3613 from the buildbot.

**Comment by tsunami2311** [comment]
you sir are correct it not nvidia drivers its i what changed in pcsx2

v1.3.1-807-g5c58bd2
with 361.93
Opengl 16:9/stretched both go in to  windowed fullscreen (borderless)

1.3.1-813-g7aa3613
with 361.93
Opengl16:9/stretched both go in to fullscreen (elusive)

**Comment by vsub** [comment]
I can also confirm
v1.3.1-807-g5c58bd2 with 361.43 has no screen tearing and the blinking when going full screen definitely looks like what you see while switching from window to borderless fullscreen.

With 813,the blink is longer(back screen for half a second)and the screen tearing is there

**Comment by tsunami2311** [comment]
great news, i was starting to think it was the gnomes in my pc, and seeing as 361.93 act the same way with 807 being windowed fullscreen (borderless) likes it should in all modes.

and

813 forcing Fullscreen exclusive ins 16:9/stretch which does the blinking and tearing.

this rules out it was nvidia issue, it what ever happend between the v1.3.1-807-g5c58bd2 and 1.3.1-813-g7aa3613 builds. now we can get this fixed

**Comment by vsub** [comment]
Forgot to mention this...I used the pcsx2 version of 1.3.1-807 and the latest plugins so it's definitely something in the pcsx2 side,not GSdx.

**Comment by turtleli** [comment]
7aa3613 was basically updating from wxWidgets 2.8 to wxWidgets 3.0, which is a big change.

Does this only affect NVIDIA or does it affect AMD and Intel as well? (on Windows)

To me, it seems like it's caused by a combination of factors:
1 - Window style (or some other) change that took place migrating from wx2.8 to wx3.0
2 - Rendering area fitting the full screen (either stretch or the resolution aspect ratio matching the used aspect ratio - see vsub's earlier post)
3 - Driver interference when the rendering window takes up the full screen when OpenGL is used (PCSX2 does not know whether DX9/11 or OpenGL is being used).

**Comment by tsunami2311** [comment]
Dont know about amd or intel dont own any of those cards.

Just know 16:9 and Stretched in OpenGL get forced in to fullscreen exclusive 4:3 mode run in windowed fullscreen (borderless)

DX11/9 all run windowed fullscreen (borderless) in 4:3/16:9/stretched

**Comment by vsub** [comment]
You have another problem with Intel and OGL...it doesn't work at all.
This problem exist only while using OGL but I don't know about AMD

**Comment by tsunami2311** [comment]
any news on this now that we know what build it went wrong in?

**Comment by tsunami2311** [comment]
btw this is no longer a external problem, as such the label should be changed. seeing it cause by pcsx2 changed from working correct with g5c58bd2 and g7aa3613 no longer work correct, so it what ever changed between those 2 builds.

**Comment by vsub** [comment]
You can change it yourself...there is an edit button at the right of the title.

**Comment by turtleli** [comment]
Could still be an Nvidia thing. I found this as one of the changes in the wxWidgets fullscreen code:
```
        // Full screen windows should logically be popups as they don't have
        // decorations (and are definitely not children) and while not using
        // this style doesn't seem to make any difference for most windows, it
        // breaks wxGLCanvas in some cases, see #15434, so just always use it.
        newStyle |= WS_POPUP;
```
http://trac.wxwidgets.org/ticket/15434

I'll link a build later for testing to see if it is this change.

**Comment by tsunami2311** [comment]
@vsub i know there is but i see no such function to edit it if there was i would of done it.

@turtleli if it is nvidia problem then why are all drivers i tested, working  on  (16:9/43/stretch) all windowed (fullscreen) borderless and g7aa3613 16:9/stretch forcing fullscreen exclusive? I wouldnt be surpised ,but the above testing the 2 above with all the drivers i listed all seem to work correctly in   g5c58bd2  but not g7aa3613. wouldnt this prove the opposite?

That ticket you linked it in reference to 3D stero which is require separate drivers to be installed, that i have never installed on my pc to begin with. i would think that would only apply if the 3d stereo drivers are installed.

i will test your build when it linked

**Comment by turtleli** [comment]
Well, if NVIDIA are providing special behaviour in certain cases, we might be hitting that special case. Also, DirectX has an exclusive fullscreen setting, OpenGL and the WGL extensions don't, or at least I am not aware of it. So any exclusive fullscreen behaviour for OpenGL should be driver related.

Link: https://ci.appveyor.com/api/buildjobs/4fe8emtdaww1k784/artifacts/pcsx2-v1.5.0-dev-376-g800f323-that_fix-175-vs2015-Win32-AppVeyor.7z

**Comment by vsub** [comment]
@turtleli 
No screen tearing with this one...I even disabled the vsync in my nvidia control panel(in pcsx2 is also disabled).
The aero is applying the vsync the same way it does in DX mode

**Comment by turtleli** [comment]
Alright, thanks for testing. I suspect the change might have also been responsible for the other fullscreen issue you previously encountered (#820)

I googled WS_POPUP and OpenGL got http://stackoverflow.com/questions/2656531/tearing-in-opengl

I'll commit the fix shortly.

**Comment by tsunami2311** [comment]
@turtleli 
Build looks good, Opengl in 16:9 and Stretched are both running in Windowed (fullscreen) borderless, Just like 4:3 in opengl  and DX11 all 16:9/stretch/4:3 all windowed (fullscreen) borderless too.

As such that all in windowed (fullscreen) borderless Aero works there for so does vsync.

What i dont get is why this issue was specific to just 16:9/stetched, but it great we got this fixed

**Comment by gregory38** [comment]
http://forums.pcsx2.net/Thread-GSdx-1-0?pid=514372#pid514372

Someone complain of small micro-stuttering  in both DX11/openGL on win10. Vsync on/off. It said it seemed to be good on win7.
