### ISSUE TITLE
Gameindex: "Anti-Blur" option

### ISSUE THREAD

**Issue by sestain** [PCSX2/pcsx2#10753]
### Description

I noticed that some games benefit a lot from "Anti-Blur" and thought that it would be nice to have a GameDB variable for it.

### Reason

* If somebody already added "Anti-Blur" for a specific game and it reduced/removed blur, I don't need to enable it manually.
* Better image quality in games since blur is gone.
* Less configuring, automation, and ease of use.

### Examples

Crash Twinsanity: Blur was gone after Anti-Blur was enabled. (One of my games I can confirm with confidence benefits from Anti-Blur)

**Comment by Mrlinkwii** [comment]
It's enabled by default , so I think their is no need for a gamedb option

**Comment by refractionpcsx2** [comment]
I agree, for the very few games that need it disabled, it can be done per game
