### ISSUE TITLE
[BUG]: Starting game from command line does not load custom game properties. Custom game properties cannot be edited in big picture.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [PCSX2/pcsx2#10757]
### Describe the Bug

When launching game using command line,
1. custom game properties are not loaded.
2. game properties cannot be edited from big picture.

### Reproduction Steps

1. Launch game like this 
```
D:\Games\RetroBat\emulators\pcsx2\pcsx2-qtx64-avx2.exe -fullscreen -batch -bigpicture -- D:\Games\RetroBat\roms\ps2\Gran Turismo 4 (USA) (v2.00).chd
```
2. Custom textures are not loaded. 
3. Here are the global settings 
![image](https://github.com/PCSX2/pcsx2/assets/10744241/063f6785-e4f2-44ad-8235-3478c84956af)
![image](https://github.com/PCSX2/pcsx2/assets/10744241/0815db43-15cd-43d6-9e9a-6ec13f899496)
4. Here are custom game properties 
![image](https://github.com/PCSX2/pcsx2/assets/10744241/30e044a3-b104-4b25-b66b-c18d2f098f57)
5. If I enable load texture in global settings, custom textures are loaded. This is how I confirm the custom game properties are not loaded.
6. I also cannot access game properties in big picture. Option is there. When selecting, nothing happens.
![image](https://github.com/PCSX2/pcsx2/assets/10744241/697526c0-bfa8-44f1-b54a-1a7f9f238ee8)

### Expected Behavior

1. Game properties are loaded when launching game from command line.
2. Game properties in big picture mode should be accessible.

### PCSX2 Revision

v1.7.5536

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Works for us (the testers checked it), I suggest you try without your launcher in case that's messing things up, if you still have a problem, you should visit the discord

https://cdn.discordapp.com/attachments/315544036184293386/1202616387709964380/2024-02-01_21-05-39.mp4

**Comment by syaifulnizamyahya** [comment]
Happy to report that the texture not loading issue is not an issue. Its because of my settings that screws things up.
But the second issue, where game properties are not accessible, I still experience it even after full reinstall PCSX2. The issue is also reported by others here. https://www.reddit.com/r/EmuDeck/comments/15vjw22/can_no_longer_open_game_properties_for_individual/

There is a workaround there. Currently trying it. Will report back.

**Comment by refractionpcsx2** [comment]
Can you try without emudeck or any launcher please. As I said, we tried it from the commandline and game properties is perfectly accessible.

**Comment by syaifulnizamyahya** [comment]
I actually did run WITHOUT any launcher. Install PCSX to separate folder. Run from default settings. Ill make a video about it sometime tonight.
