### ISSUE TITLE
[BUG]: Widescreen patches not working

### ISSUE THREAD

**Issue by 4rmanDC** [PCSX2/pcsx2#10760]
### Describe the Bug

I'm starting to play Harry Potter and the Sorcerer's Stone [SLUS-20826] but the widescreen patch is not working. Then I downloaded a pnach file and it didn't work neither.

### Reproduction Steps

![Captura de pantalla 2024-02-01 170028](https://github.com/PCSX2/pcsx2/assets/91060357/f74211da-b8f0-40bd-ac07-86a7428d2bce)

![Captura de pantalla 2024-02-01 170154](https://github.com/PCSX2/pcsx2/assets/91060357/8fe9f9e4-e178-4c2b-b49e-e7f11db822f8)

![Captura de pantalla 2024-02-01 170543](https://github.com/PCSX2/pcsx2/assets/91060357/37ba1ab6-ecb5-464b-82ac-f81472c0f5bc)

### Expected Behavior

Apparently It used to work in older versions.
![Captura de pantalla 2024-02-01 170737](https://github.com/PCSX2/pcsx2/assets/91060357/b17fbac1-50aa-45e8-b879-00cd478bb78f)

### PCSX2 Revision

v1.7.5536

### Operating System

Windows 10 (64bit)

**Comment by RedPanda4552** [comment]
SLUS-20826 has no widescreen patches included with the emulator, there is nothing for us to disable.

If you have further issues with widescreen patches included with PCSX2, the correct repository to report broken patches is https://github.com/PCSX2/pcsx2_patches

**Comment by 4rmanDC** [comment]
I tried Persona 3 FES and Tales of the Abyss. But the widescreen patches manually downloaded only works if active as "cheat". Active as "patch" (properly labeled) I still get the message "not active or unavailable".  I think it's worth to check this.
