### ISSUE TITLE
[Feature Request]: Appimage update via AppImageUpdate

### ISSUE THREAD

**Issue by samuraikid0** [PCSX2/pcsx2#10776]
### Description

Add the missing information to the appimage for it to be able to update with AppImageUpdate

https://github.com/AppImageCommunity/AppImageUpdate

Thanks !

### Reason

Easy way to update AppImage apps

### Examples

Librewolf appimage for example is able to update via AppImageUpdate

**Comment by stenzek** [comment]
I looked into this a long time ago, and I don't believe it's possible, since it requires a fixed URL to pull the zsync info from. Which we don't have, and our release setup will never work that way.

PCSX2 has a built-in updater, so any benefit is kinda negated to begin with.
