### ISSUE TITLE
[BUG]: Widescreen patches won't work if Retroachievements hardcore mode is active.

### ISSUE THREAD

**Issue by 4rmanDC** [PCSX2/pcsx2#10770]
### Describe the Bug

I've downloaded a properly labeled pnach file with widescreen and 60 fps patches, but these won's work if hardcore mode is active.

### Reproduction Steps

It works perfectly without loggin in to retroachievements.com and when logged in but with harcore mode switched off.
![Captura de pantalla 2024-02-04 013500](https://github.com/PCSX2/pcsx2/assets/91060357/fdbb137b-eec8-4ed6-b5ed-7fb720e829bd)

Then I switch on hardcore mode, the emulation restarts, but the patches won't be active anymore.
![Captura de pantalla 2024-02-04 014233](https://github.com/PCSX2/pcsx2/assets/91060357/15922f21-6a3d-4ad0-8f29-4c693852d3b2)

### Expected Behavior

Maybe patches are erroneously considered as cheats.

### PCSX2 Revision

v1.7.5540

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Working as intended. Custom patches are not supported in HC mode, as a very basic anti-cheat measure.

**Comment by refractionpcsx2** [comment]
Keep in mind if you have a widescreen patch we don't have, and you're confident it works properly, you can submit it to our pcsx2_patches repo, and it will be included in future releases.
