### ISSUE TITLE
[Feature] Add create game config similar PPSSPP

### ISSUE THREAD

**Issue by zminhquanz** [PCSX2/pcsx2#1077]
Because each game each different config

**Comment by Blackbird88** [comment]
But isn't the Game Database Editor exactly that?

**Comment by willkuer** [comment]
No not really.

But we have frontends for that. Please check the forum for pcsx2bonus and other frontends in the tools section.

**Comment by lightningterror** [comment]
Closing in favor of #2551 which is much more detailed.
