### ISSUE TITLE
[BUG]: Ace Combat 04: terrain texture missing at close range

### ISSUE THREAD

**Issue by PositronCannon** [PCSX2/pcsx2#10789]
### Describe the Bug

Same issue as in https://github.com/PCSX2/pcsx2/issues/10271.  The terrain textures in mission 11 "Escort" disappear when you get close to it.

The issue can be fixed by enabling Framebuffer Conversion, or by setting CPU Sprite Render Size to 128 and Blended Sprites/Triangles (default for the game is 64/Sprites Only).

I've attached a GS dump below.

### Reproduction Steps

- Run PCSX2 with all default settings
- Start mission 11 and get close to the ground

### PCSX2 Revision

v1.7.5550

### Operating System

Windows 11

### CPU

i7-12700H

### GPU

RTX 3060

### GS Window Screenshots

![Ace Combat 04 - Shattered Skies_SLUS-20152_20240208001021](https://github.com/PCSX2/pcsx2/assets/65429992/4d78bb5a-a7b9-4461-a6ee-c521f8a61956)

### Logs & Dumps

[AC04 terrain bug.zip](https://github.com/PCSX2/pcsx2/files/14202576/AC04.terrain.bug.zip)

**Comment by refractionpcsx2** [comment]
There's been a few of these :( Why are you such a pain Ace Combat?

I'll take a look in to why it's breaking, would rather avoid a higher CPU Sprite.

**Comment by PositronCannon** [comment]
> Why are you such a pain Ace Combat?

😅

And like last time, it also happens in Ace Combat Zero when the HUD is disabled. The same fixes apply there as well.

![Ace Combat Zero - The Belkan War_SLUS-21346_20240208002420](https://github.com/PCSX2/pcsx2/assets/65429992/1b5ea062-8760-4890-86c6-ac56c8a64451)

Thanks for looking into it!
