### ISSUE TITLE
[Feature Request]: Name sanitization for gamedb names

### ISSUE THREAD

**Issue by TellowKrinkle** [PCSX2/pcsx2#10780]
### Description

The GameDB names are currently used directly as filenames for covers, etc, which means they cannot contain symbols that are banned from filenames (see #10766 and #10475).  We should automatically remove those symbols when generating filenames so this isn't an issue

### Reason

The names in the GUI should not be limited by what is/isn't a valid filename

### Examples

See #10766 and #10475

**Comment by Mrlinkwii** [comment]
Should be fine with  https://github.com/PCSX2/pcsx2/pull/10494

**Comment by TellowKrinkle** [comment]
Thanks for the confirmation
