### ISSUE TITLE
[BUG]: BigPicture not immediately launched when -bigpicture is passed.

### ISSUE THREAD

**Issue by weirdbeardgame** [PCSX2/pcsx2#10781]
### Describe the Bug

When the CLI arg big picture is passed, there is a noticeable delay where the Desktop UI will render initially before switching to BigPicture.

### Reproduction Steps

Pass -BigPicture or -fullscreen -bigpicture, see the Desktop UI then bigpicture starts

https://github.com/PCSX2/pcsx2/assets/22896793/01221390-368d-487e-b47f-4387f0e85db0

### Expected Behavior

No desktop UI

### PCSX2 Revision

v1.7.5543

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by weirdbeardgame** [comment]
Note this is tested to happen in AppImage and compiled builds of pcsx2

**Comment by stenzek** [comment]
Working as intended. BP runs on top of the standard UI, and MTGS takes time to get started, more so on some systems than others, due to driver initialization time.

**Comment by parkerlreed** [comment]
The original post is still fairly quick, but this takes 10 seconds to load on Steam Deck for example. So you stare at the desktop UI for a bit longer during the wait. Would be nice for the big picture UI to take precedence (and ideally find out why initialization is so slow depending on the drivers)

**Comment by stenzek** [comment]
It's nearly instantaneous on my system. So as far as I can see, there is no issue. If SD has problems, then someone who actually owns one can debug and work around it. I'm not going to buy one to do so.

BP UI is "secondary", I don't see why it should take precedence.

**Comment by weirdbeardgame** [comment]
I think he means "Presedence" in that when the command is passed the order of operations should favor the initalization of Big Picture mode.

**Comment by stenzek** [comment]
And how would you do that? It's not like there's two separate UIs. BP presents through the game display window, the "desktop" UI is always going to run.
