### ISSUE TITLE
Add 400% and 500% "EE cycle rate" overclock option

### ISSUE THREAD

**Issue by pepodmc3** [PCSX2/pcsx2#10798]
### Description

The feature its already implemented in the emulator, but at 300% max.
I want to expand it a little more, to 400% and 500%.

### Reason

That option is needed when you apply a 60 fps patch to certain games.

In particular the game "Darkwatch". You need to put the option at 300% so the game doesnt have too much slowdowns in heavy scenes with a lot of enemies/effects.

But, sometimes, there are still some slowdowns when a a lot of red souls are on the screen along enemies and other effects.

So, a 400% / 500% option would help to fix at 100% these slowdowns when you play with the 60 fps patch applied.

### Examples

The emulator already have the option implemented, but not at that percent of overclock.

**Comment by refractionpcsx2** [comment]
I'm adversed to adding higher than 300% as this is already rough on stability as it is, and you'd be surprised how many people just crank up these settings, I hate to think how broken it would be with these additional settings.

If you want to do it on your copy, edit the `PCSX2.ini` and find `EECycleRate` and change the value to 4 or 5, that will be roughly what you want, but I don't want to add this to the UI, sorry.

**Comment by pepodmc3** [comment]
> I'm adversed to adding higher than 300% as this is already rough on stability as it is, and you'd be surprised how many people just crank up these settings, I hate to think how broken it would be with these additional settings.
> 
> If you want to do it on your copy, edit the `PCSX2.ini` and find `EECycleRate` and change the value to 4 or 5, that will be roughly what you want, but I don't want to add this to the UI, sorry.

but doing that will make the ee ciclerate overclock to be higher than 300?
If thats the case theres no problem if it doesnt appear on the ui

**Comment by refractionpcsx2** [comment]
nah I was mistaken, we clamp it to 3, but I still don't want to go higher, you're free to fork the code and remove the cap/increase the bar, if you like.

**Comment by pepodmc3** [comment]
> nah I was mistaken, we clamp it to 3, but I still don't want to go higher, you're free to fork the code and remove the cap/increase the bar, if you like.

im an ingorant in this subject, its very difficult to do?

**Comment by pepodmc3** [comment]
> CYCLERATE

I have to download the source code of the emulator, change that parameter and then build it?

**Comment by pepodmc3** [comment]
> probably not, you will need to edit the MAX_EE_CYCLERATE (I might have the name wrong), and edit the dropdown in the Qt interface to have a bigger range, but that'd probably be it.

in which file i can find that parameter to change it?

**Comment by refractionpcsx2** [comment]
pcsx2\config.h line 939

**Comment by pepodmc3** [comment]
> pcsx2\config.h line 939

So, in that like if i put 4 would be equivalent of 400% and 5 equivalent of 500% ?

**Comment by refractionpcsx2** [comment]
It's not an exact art, the numbers we've given are just guesses :P but maybe, sure.  You can push it further, if you want.

**Comment by pepodmc3** [comment]
> edit the dropdown in the Qt interface to have a bigger range

" edit the dropdown in the Qt interface to have a bigger range"

And for this one, which file i need to modify and what parameter?

Thanks for taking time in anwering my questions

**Comment by refractionpcsx2** [comment]
Ideally you edit the `pcsx2-qt\Settings\EmulationSettingsWidget.ui` in the qt designer, but you can add the extra options manually to the end of the eeCycleRate combo box, as long as you're comfortable with a little bit of html :P

**Comment by pepodmc3** [comment]
> Ideally you edit the `pcsx2-qt\Settings\EmulationSettingsWidget.ui` in the qt designer, but you can add the extra options manually to the end of the eeCycleRate combo box, as long as you're comfortable with a little bit of html :P

this " edit the dropdown in the Qt interface to have a bigger range"

Its for the ui so you can go past 3 and put 4 in that option?

What i mean, the qt interface step its really needed to make this work?  
or with modifing "config.h" and put max cyclerate to 4 its enough to, then, modify PCSX2.ini and put EECycleRate=4 and make it work?

**Comment by refractionpcsx2** [comment]
if you just append the new options, it will increase the range for the dropdown, yes.  You will need to add enough to match the increase you made to the MAX_EE_CYCLE_RATE

**Comment by refractionpcsx2** [comment]
just editing the config.h will be enough for you to be able to edit the PCSX2.ini manually

**Comment by pepodmc3** [comment]
> just editing the config.h will be enough for you to be able to edit the PCSX2.ini manually

Is this right or its wrong or outdated?

make sure you use git clone --recurse-submodules
Required Dependencies for QT
If you are developing against the pcsx2-qt solution, you will need to do the following:

Download the binaries from here https://github.com/PCSX2/pcsx2-windows-dependencies/releases/
tools / symbols are not required
Extract into the main folder (where the PCSX2_qt.sln file is); you should see a new deps folder after extraction
Ensure you have opened the *-qt .sln file.
Required Build Applications
[Visual Studio Community](https://www.visualstudio.com/downloads/)
Installing just the "Desktop development with C++" workload should be enough, otherwise select individually:
C++ ATL for v142 build tools (x86 & x64)
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows 10 SDK
[Git for Windows](https://git-scm.com/download/win)
Other Requirements

**Comment by refractionpcsx2** [comment]
uhh think that's up to date, yeah

**Comment by pepodmc3** [comment]
> uhh think that's up to date, yeah

which file i need to download here:

https://github.com/PCSX2/pcsx2-windows-dependencies/releases/

the lastest dependencies build?

**Comment by pepodmc3** [comment]
> yes

can you build it for me? because i made partitions of my ssd disk and my c drive is full and i dont have space to install visual studio, and because of the position of the partitions, i cant reduce one partition and extend C (i would have to delete the next partition to it to extend its size) 
. C is only 35gb and full of programs only, i cant move anything.
Would be a one time favor. If you dont mind

**Comment by pepodmc3** [comment]
> yes



> yes

I tried to compile it but it gave me 3 errors:

https://i.imgur.com/zTv2xj3.png

What i need to do?

**Comment by refractionpcsx2** [comment]
where did you extract the deps folder?

it should be like this (I've removed my path except the structure inside the code)

![image](https://github.com/PCSX2/pcsx2/assets/6278726/42f46e33-1e88-4a7e-a2e3-a3b0775427e6)

**Comment by pepodmc3** [comment]
> where did you extract the deps folder?
> 
> it should be like this (I've removed my path except the structure inside the code)
> 
> ![image](https://private-user-images.githubusercontent.com/6278726/303839113-42f46e33-1e88-4a7e-a2e3-a3b0775427e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzE5NDMsIm5iZiI6MTcwNzU3MTY0MywicGF0aCI6Ii82Mjc4NzI2LzMwMzgzOTExMy00MmY0NmUzMy0xZTg4LTRhN2UtYTJlMy1hM2IwNzc1NDI3ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTMyNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDllY2I2MzBiZjQ1ZjUxY2YxNTc3NTJkNWQ1NGM2ZGViMjkxM2VlZWEwOTI0MjcxODNhOTIzYjYzNTI2ZjdkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k4tT74E5P45zVS3tSMorchCbwJgeuwd_weyhAj4pCiA)
> 
> ![image](https://private-user-images.githubusercontent.com/6278726/303839154-6d9e4214-e4b2-4dae-91d6-65d54c9af9ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzE5NDMsIm5iZiI6MTcwNzU3MTY0MywicGF0aCI6Ii82Mjc4NzI2LzMwMzgzOTE1NC02ZDllNDIxNC1lNGIyLTRkYWUtOTFkNi02NWQ1NGM5YWY5YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTMyNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDBlMzIyMDU0ZDMwMjBkZmM4NTMzMGZiY2ViMDY1MDVkMjU4MjM0MzQ4OTM3ZGViOGNiYzY5ZDE0MTM3YzMzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EJmShGKnC6xmFhkUSBBNQ7nZiqMrFtUzMQI9uxXnfiA)

<img width="960" alt="sdfsf" src="https://github.com/PCSX2/pcsx2/assets/38732891/3e737ce9-df62-475d-9a58-810145995121">

**Comment by refractionpcsx2** [comment]
and how does it look inside that folder?

**Comment by pepodmc3** [comment]
> and how does it look inside that folder?

ops sorry, seems that was an error from my part, i will check again XD

**Comment by refractionpcsx2** [comment]
okay, when you change it, be sure to restart Visual studio, so it can freshly see the files :)

**Comment by pepodmc3** [comment]
> okay, when you change it, be sure to restart Visual studio, so it can freshly see the files :)

The build is done without erros, but i dont know where it is

**Comment by refractionpcsx2** [comment]
it goes in the `bin` folder

**Comment by pepodmc3** [comment]
> it goes in the `bin` folder

thanks a lot for the help man!

**Comment by refractionpcsx2** [comment]
keep in mind at the top of Visual Studio you had it set to "Debug" so that build might be quite slow.

For best performance use Clang Release AVX2 (word order may be different)

**Comment by refractionpcsx2** [comment]
> > it goes in the `bin` folder
> 
> thanks a lot for the help man!

no problem, enjoy :)

**Comment by Buzzardsoul** [comment]
I know this is closed, but I just wanna add that this might be useful for debugging. Adding an underclock to 30% or 40% is also useful.

**Comment by pepodmc3** [comment]
> > > it goes in the `bin` folder
> > 
> > 
> > thanks a lot for the help man!
> 
> no problem, enjoy :)

Last question, this parameter accept numbers like 3.2 , 3.5 , etc , or just integer number?

**Comment by refractionpcsx2** [comment]
just integers

> I know this is closed, but I just wanna add that this might be useful for debugging. Adding an underclock to 30% or 40% is also useful.

Useful how?

**Comment by Buzzardsoul** [comment]
> just integers
> 
> > I know this is closed, but I just wanna add that this might be useful for debugging. Adding an underclock to 30% or 40% is also useful.
> 
> Useful how?

Useful for determining if an issue was related to timing.

**Comment by refractionpcsx2** [comment]
50-300 does that just fine.

**Comment by Buzzardsoul** [comment]
In #10622, it didn't work 100% of the time. For instance, single-player challenges. So it can sometimes miss some cases. Having this option would ensure that more cases are covered. I'm more than aware these options are unsuitable for gaming, but they definitely are assistive to comprehensive debugging.

**Comment by wefalltomorrow** [comment]
I assume there's still no chance of adding this to release builds? Alongside a slider like mentioned in #3769

**Comment by JordanTheToaster** [comment]
> I assume there's still no chance of adding this to release builds? Alongside a slider like mentioned in #3769

No it won't be added.

**Comment by wefalltomorrow** [comment]
> > I assume there's still no chance of adding this to release builds? Alongside a slider like mentioned in #3769
> 
> No it won't be added.

That's a bit sad, but fair enough.
