### ISSUE TITLE
[BUG]: AppImage version of PCSX2 fails to update

### ISSUE THREAD

**Issue by Roguefort8** [PCSX2/pcsx2#10794]
### Describe the Bug

When attempting to update PCSX2 via it's built-in updater, it fails to do so. A error window shows the following:

> Failed to download latest release info: 0

![Screenshot](https://github.com/PCSX2/pcsx2/assets/159486396/0264fe6b-cfdc-45fa-9a73-6131c5ce2380)

### Reproduction Steps

1. Download the latest version of PCSX2
2. Launch it
3. Click `Help`
4. Click `Check for updates`

### Expected Behavior

PCSX2 will check for updates. If it finds, it will show the usual update page with the change log.

### PCSX2 Revision

v1.7.5550

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Opensuse Tumbleweed 20240201

### Logs & Dumps

```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Forcing X11 instead of Wayland, due to various protocol limitations
and Qt issues. If you want to use Wayland, launch PCSX2 with
I_WANT_A_BROKEN_WAYLAND_UI=YES set.
```

**Comment by Roguefort8** [comment]
The only workaround for this is to manually update it by going to the website or the GitHub repo.

**Comment by refractionpcsx2** [comment]
What channel is your copy set to for updates under settings->interface?

**Comment by Roguefort8** [comment]
> What channel is your copy set to for updates under settings->interface?

- nightly

**Comment by refractionpcsx2** [comment]
okay, strange.  any firewalls or anything that could be blocking PCSX2? cos right now, this is just you :P

**Comment by Roguefort8** [comment]
> okay, strange. any firewalls or anything that could be blocking PCSX2? cos right now, this is just you :P

Probably. OpenSuse has a strict firewall enabled by default. I could check if I knew which ports it goes. _Or figuring out how to let an appimage pass it_

**Comment by Roguefort8** [comment]
Note: In previous versions, it used to be able to update. But ever sinse a x version that I don't remember that it shows this issues. I can try on `v1.7.4994` and the auto updater window shows up:

![Screenshot2](https://github.com/PCSX2/pcsx2/assets/159486396/481870cd-c6a3-41ca-9e81-9c52eb16d78b)

**Comment by refractionpcsx2** [comment]
could be when we changed to the HTTP downloader, but not sure if that's something your system decided it doesn't like or a missing package or what, couldn't tell you, I'm afraid.

**Comment by Roguefort8** [comment]
I digged that update change log for `updater` and `AppImage` mentions. Nothing on the updater though, but on AppImage:

`CI/Linux: Use wildcard for AppImage libc downgrade (Connor McLaughlin)`

#10652 

Maybe it caused this?

**Comment by Mrlinkwii** [comment]
doubt it

**Comment by Mrlinkwii** [comment]
the appimage updater works here , so i thing this is most likely a firewall issue

**Comment by Roguefort8** [comment]
Ok so who here knows how to add an AppImage service to YaST Firewalid? Because I can't figure it out...

**Comment by Mrlinkwii** [comment]
it would be miles better if you join the discord for support

**Comment by Roguefort8** [comment]
> it would be miles better if you join the discord for support , see the readme for the link

Thanks, however I don't have the time today. Tomorrow I'll join.

**Comment by refractionpcsx2** [comment]
well, as this is most likely a support issue, I'm gonna close this for now. If it can be proven it's actually a bug (usually would be good to see others affected too), then we can reopen.
