### ISSUE TITLE
[BUG]: Widescreen patch won't turn off even after disabling it in the patch menu [Armored Core 2 SLUS-20014]

### ISSUE THREAD

**Issue by Tenome** [PCSX2/pcsx2#10804]
### Describe the Bug

I have the "Enable Widescreen Patches" option turned ON in the main menu, and the in-game Widescreen Patch turned OFF in the per-game config. PCSX2 still launches the game with the Widescreen Patch applied (the console log also says it's enabling the patch). This persists even after resetting. When I check the .ini file, it correctly doesn't list the Widescreen Patch as enabled. Both my global and per-game settings are set to Auto 4:3, so it's not that.

For some reason, PCSX2 is just refusing to recognize that I turned off the widescreen patch. Of course, if I disable Widescreen Hacks in the global settings, it fixes this but I don't want to do that.

How can I resolve this?

It seems I'm not the only one who's had this problem with the buggy widescreen patch feature. Here's a post from 3 years ago.
https://www.reddit.com/r/PCSX2/comments/jpxoed/how_do_i_disable_a_widescreen_patch/

### Reproduction Steps

Enable Widescreen Patches in the main settings
Enable the widescreen patch for Armored Core 2 (might not be necessary, but I think this is where PCSX2 gets "stuck" and refuses to disable the patch after), launch the game to apply it, then exit
Disable the widescreen patch, launch game

![pcsx2-qt_98GWSJZR5T](https://github.com/PCSX2/pcsx2/assets/12216081/2b40b197-46dd-4b17-b2a7-84e302870d0e)
![pcsx2-qt_GTBwziqN7L](https://github.com/PCSX2/pcsx2/assets/12216081/788a1ee5-79be-433d-b94a-f2d26b5e3ea6)

### Expected Behavior

PCSX2 does not apply the widescreen patch when I disable the checkbox.

### PCSX2 Revision

v1.7.5553

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[    0.0782] Couldn't find translation for system language en-US, using en instead
[    0.0789] Loaded translation file for language en
[    0.2726] PCSX2 v1.7.5553
[    0.2727] Savestate version: 0x9a4b0000
[    0.2730]
[    0.2730]
[    0.2731] Host Machine Init:
[    0.2731]   Operating System = Microsoft Windows 10+
[    0.2732]   Physical RAM     = 32692 MB
[    0.2732]   Processor        = AMD Ryzen 5 1600
[    0.2733]   Core Count       = 6 cores
[    0.2733]   Thread Count     = 12 threads
[    0.2734]
[    0.2734] x86 Features Detected:
[    0.2734]   AVX AVX2
[    0.2735]
[    0.2752] SDLInputSource: Using Controller DB from resources.
[    0.4267] SDLInputSource: 803 controller mappings are loaded.
[    0.4270] XInput controller 0 connected.
[    0.4322] (Achievements) Hardcore disabled
[    0.4323] (Achievements) Encore mode disabled
[    0.4324] (Achievements) Unofficial disabled
[    0.4324] (Achievements) Spectator mode disabled
[    0.4324] (Achievements) Attempting login with user 'Tenome'...
[    0.4325] (Achievements) Attempting to log in Tenome (with token)
[    0.5520] (SDLInputSource) Controller 0 inserted
[    0.5523] (SDLInputSource) Opened game controller 0 (instance id 0, player id 0): XInput Controller
[    0.5524] (SDLInputSource) Controller 0 has 6 axes and 11 buttons
[    0.5525] (SDLInputSource) Rumble is supported on 'XInput Controller' via gamecontroller
[    0.5841] Scanning E:\Games\Playstation 2 (recursively)
[    0.8790] (Achievements) Tenome logged in successfully
[    3.4369] Current version: v1.7.5553
[    3.4375] Latest version: v1.7.5553
[    3.4378] Last checked version:
[    3.4384] No update needed.
[    3.4390] (AutoUpdaterDialog) All HTTP requests done.
[   39.3228] Loading BIOS...
[   39.3231] BIOS Found: USA     v02.20(10/02/2006)  Console 20060210-142424
[   39.3259] BIOS rom1 module not found, skipping...
[   39.3260] BIOS rom2 module not found, skipping...
[   39.3263] Opening CDVD...
[   39.3269] isoFile open ok: E:\Games\Playstation 2\Armored Core 2 (USA).iso
[   39.3270]   Image type  = DVD
[   39.3274]  * CDVD Disk Open: DVD, Single layer or unknown:
[   39.3278]  * * Track 1: Data (Mode 1) (1731888 sectors)
[   39.3366] [GameDB] Has not been initialized yet, initializing...
[   39.3870] [GameDB] 12801 games on record (loaded in 50.35ms)
[   39.3872] Disc changed to Armored Core 2 (USA).iso.
[   39.3881]   Name: Armored Core 2
[   39.3886]   Serial: SLUS-20014
[   39.3890]   Version: 2.00
[   39.3893]   CRC: 0D168765
[   39.3898] Loading game settings from 'C:\Users\ \Desktop\pcsx2-v1.7.4249-windows-64bit-Qt\gamesettings\SLUS-20014_0D168765.ini'...
[   39.3902] Applying settings...
[   39.3911] [Unsafe Settings] Fast CDVD is enabled, this may break games.
[   39.3912] OSD [unsafe_settings_warning]:  Fast CDVD is enabled, this may break games.
[   39.4240] Hash for 'SLUS_200.14' (3428152 bytes, 3428152 bytes hashed): 642ffd8e7d5dfbd2ed4dcd4143450b5e
[   39.4246] Reopening memory cards...
[   39.4255] McdSlot 0 [File]: my memory card.ps2 [8 MB, Formatted]
[   39.4259] McdSlot 1 [File]: my memory card2.ps2 [8 MB, Formatted]
[   39.4271] HLE Host: Set 'host:' root path to: E:\Games\Playstation 2
[   39.4271]
[   39.4275] EE/iR5900 Recompiler Reset
[   39.6238] Opening GS...
[   39.8295] GPU 0: NVIDIA GeForce GTX 1080 Ti
[   39.9248] VK_EXT_provoking_vertex is supported
[   39.9249] VK_EXT_memory_budget is supported
[   39.9258] VK_EXT_calibrated_timestamps is supported
[   39.9262] VK_EXT_rasterization_order_attachment_access is NOT supported
[   39.9265] VK_EXT_attachment_feedback_loop_layout is supported
[   39.9269] VK_EXT_full_screen_exclusive is supported
[   39.9272] VK_KHR_driver_properties is supported
[   39.9288] Read 240 entries from 'C:\Users\ \Desktop\pcsx2-v1.7.4249-windows-64bit-Qt\cache\vulkan_shaders.idx'
[   40.1978] Vulkan Graphics Driver Info:
[   40.1979] Driver 551.92.0
[   40.1989] Vulkan 1.3.271
[   40.1994] Conformance Version 1.3.7.1
[   40.1997] 551.23
[   40.2001] NVIDIA
[   40.2005] NVIDIA GeForce GTX 1080 Ti
[   40.2034] Opening SPU2...
[   40.2042] Initializing SndBuffer at sample rate of 48000...
[   40.2073] (Cubeb) Using normal 2 speaker stereo output.
[   40.2110] (Cubeb) Minimum latency: 10.00 ms (480 audio frames)
[   40.2298] Initializing Pad...
[   40.2299] Initializing SIO2...
[   40.2305] Initializing SIO0...
[   40.2310] Opening DEV9...
[   40.2346] Opening USB...
[   40.2347] Opening FW...
[   40.2457] VM subsystems initialized in 922.99 ms
[   40.2470] Processor count: 6 cores, 12 processors
[   40.2470] Cluster count: 1
[   40.2475] Ordered processor list: 0, 2, 4, 6, 8, 10, 1[SMT 1], 3[SMT 1], 5[SMT 1], 7[SMT 1], 9[SMT 1], 11[SMT 1]
[   40.2710] (Achievements) Identified game: 3316 (642ffd8e7d5dfbd2ed4dcd4143450b5e)
[   40.4457] ELF Loading: cdrom0:\SLUS_200.14;1, Game CRC = 0D168765, EntryPoint = 0x00100008
[   40.9663] (Achievements) Game 3316 loaded, hardcore disabled
[   40.9666] Rich presence updated: Not In Sortie 📁 | Arena Rank: 0 🔰 | Credits: 0 💰 | Success: 0 ✔️ | Failure: 0 ❌ | Human Plus: 0 ➕
[   41.3150] ELF cdrom0:\SLUS_200.14;1 with entry point at 0x1048584 is executing.
[   41.3152] ELF changed, active CRC 0D168765 (cdrom0:\SLUS_200.14;1)
[   41.3166] Found 2 game patches in SLUS-20014_0D168765.pnach.
[   41.3173] Found 1 cheats in C:\Users\ \Desktop\pcsx2-v1.7.4249-windows-64bit-Qt\cheats\SLUS-20014_0D168765.pnach.
**[   41.3175] Enabled patch: Widescreen 16:9**
[   41.3179] Enabled patch: No-Interlacing
[   41.3184] Enabled patch: True Analogs
[   41.3188] OSD [LoadPatches]: 2 game patches, 1 cheat patches are active.
[   41.3194] Applying core settings...
[   41.3201] Patch: Setting aspect ratio to 16:9 by patch request.
[   41.3203] Patch: Setting deinterlace mode to 1 by patch request.
[   41.3208] [Unsafe Settings] Fast CDVD is enabled, this may break games.
[   41.3213] OSD [unsafe_settings_warning]:  Fast CDVD is enabled, this may break games.
[   41.3218] (GameDB) Changing EE/FPU clamp mode [mode=2]
[   41.3222] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[   41.3222] Updating CPU configuration...
[   41.3336] Updating GS configuration...
[   41.7178] EE/iR5900 Recompiler Reset
[   42.9989] (UpdateVSyncRate) Mode Changed to NTSC.
[   42.9992] (UpdateVSyncRate) Mode Changed to NTSC.
[   43.9655] [Pad] DS2 Config Finished - P1/S1 - AL: Off - AB: Usable - VS: Disabled - VL: Disabled - RB: D (0x00000000)
[   45.1668] [Pad] DS2 Config Finished - P1/S1 - AL: Off - AB: Usable - VS: Normal - VL: Normal - RB: D (0x00000000)
[   49.0040] [Pad] DS2 Config Finished - P1/S1 - AL: On - AB: Locked - VS: Normal - VL: Normal - RB: D (0x00000000)
[   49.2042] [Pad] DS2 Config Finished - P1/S1 - AL: On - AB: Locked - VS: Normal - VL: Normal - RB: D (0x00000000)
[   49.3376] [Pad] DS2 Config Finished - P1/S1 - AL: On - AB: Locked - VS: Normal - VL: Normal - RB: D (0x00000000)
[   49.5045] [Pad] DS2 Config Finished - P1/S1 - AL: On - AB: Locked - VS: Normal - VL: Normal - RB: D (0x00000000)
[   49.7379] (VMManager) Pausing...
[   51.9720] Add 9 seconds play time to SLUS-20014 -> now 2393
[   51.9722] (Achievements) Unloading game 3316
[   52.2308] Skipping updating pipeline cache 'C:\Users\ \Desktop\pcsx2-v1.7.4249-windows-64bit-Qt\cache\vulkan_pipelines.bin' due to no changes.

**Comment by prafullpcsx2** [comment]
Looks like you are using some old version of nightly because widescreen patch option has already been removed from per game settings.

**Comment by Tenome** [comment]
> Looks like you are using some old version of nightly because widescreen patch option has already been removed from per game settings.
Is there a newer nightly than 1.7.5553? That's what's listed on the site. The per-game patch option is still there.
![pcsx2-qt_ZJTNjVOPVu](https://github.com/PCSX2/pcsx2/assets/12216081/d398efc3-37ff-453e-9b7a-88817606cd92)

**Comment by refractionpcsx2** [comment]
have you put one in your cheats folder?

**Comment by refractionpcsx2** [comment]
anyway this is a support request, please use our discord for that.
