### ISSUE TITLE
Changing Adapter in GSdx automatically sets your renderer to OpenGL Hardware

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#1080]
Normal behavior: Changing adapter does not change whatever renderer you had set.
@ssakash have fun :P

**Comment by gregory38** [comment]
@ramapcsx2 we need to check it for the release.

**Comment by turtleli** [comment]
Ok, the issue seems to be that it's changing to the saved renderer, it's not actually changing specifically to OpenGL.

I'll have a fix ready soon.
