### ISSUE TITLE
[BUG]: Lights shining through objects when using Hardware Renderer

### ISSUE THREAD

**Issue by Lordmau5** [PCSX2/pcsx2#10806]
### Describe the Bug

Lights seem to shine through walls.
The first few screenshots were taken with upscaling enabled, but the last ones are without it.
I've tried all HW renderers (Vulkan, OpenGL, DX11, DX12) and it happens on all of them.
The only fix is to temporarily switch to the SW renderer and then back, **but** this will only fix the issue for the lights that are currently being rendered - if I drive further and find "new lights" then those will be broken again.

<details>
<summary>Screenshots</summary>

![image](https://github.com/PCSX2/pcsx2/assets/1345036/df31a4bb-3589-48d6-94f0-4514f49c8606)
![image](https://github.com/PCSX2/pcsx2/assets/1345036/5008a85b-6bc9-46f8-9f8e-7d201dc1cd3a)
![image](https://github.com/PCSX2/pcsx2/assets/1345036/77bd1599-3583-4605-bb2d-56d32657d9c7)
![image](https://github.com/PCSX2/pcsx2/assets/1345036/9cc33f97-3346-48ee-a403-3f8fe585fbd8)

</details>

<details>
<summary>After switching to SW renderer and back (or just using SW renderer the entire time)</summary>

![image](https://github.com/PCSX2/pcsx2/assets/1345036/7b0588f3-03bf-4645-93c2-4817dab49326)

</details>

### Reproduction Steps

Launch `The Italian Job` with a HW renderer and drive around the city. Lights (traffic lights, car headlights, etc.) should be shining through walls

### Expected Behavior

The lights should be properly culled (?) behind walls.

I remember seeing an issue with other games but I can't find it anymore...

### PCSX2 Revision

v1.7.5553

### Operating System

Windows 11

### CPU

AMD Ryzen 9 5950X

### GPU

RTX 3090

**Comment by refractionpcsx2** [comment]
Did you disable hardware readbacks to stop it being slow?

**Comment by TheTechnician27** [comment]
> Did you disable hardware readbacks to stop it being slow?

This reminds me of how lights show through walls in The Godfather when it's upscaled. Lordmau, if you're upscaling currently, does it help when you set the resolution to 'Native'?

**Comment by Lordmau5** [comment]
I actually can't find the option in the game's graphics settings right now... I got the `Manual Hardware Renderer Fixes` enabled and tried various things before (e.g. GPU Target CLUT on different settings etc.)

Is the Readbacks option only in the OSD when I'm in the game? Or in some advanced menu I don't have enabled?

**Comment by refractionpcsx2** [comment]
in the per-game settings where you have the manual fixes, disable manual fixes, and go to the advanced tab in the same place, and make sure hardware readbacks is set to accurate.

**Comment by Lordmau5** [comment]
I don't seem to have an `Advanced` tab in here
![image](https://github.com/PCSX2/pcsx2/assets/1345036/b1f98ced-6912-4d63-ae8f-b8695c04976d)

**Comment by refractionpcsx2** [comment]
okay, can you click "clear settings" in the bottom left?

**Comment by Lordmau5** [comment]
Just did, still no Advanced tab, should I try to reproduce it with the cleared settings?

**Comment by refractionpcsx2** [comment]
yes

**Comment by Lordmau5** [comment]
That uh... fixed the issue. Even when upscaled to 1440p (since I had that set in my global settings)

Maybe in the past I *did* set something that caused these issues which was later on fixed?

**Comment by refractionpcsx2** [comment]
Yeah you enable the advanced tab under the tools menu, my guess is you had it on in the past and turned that option on.

Anyways was a support issue, probably best to check with the discord first next time. Thanks

**Comment by Lordmau5** [comment]
> probably best to check with the discord first next time. Thanks

Apologies for this - had this issue for quite some time and just never managed to find a fix - I was thinking about popping into the Discord before but it honestly did not cross my mind this time 😅 
Will do in the future first though if I find some more issues in other games!
