### ISSUE TITLE
[BUG]: Dump corrupted textures

### ISSUE THREAD

**Issue by c0rexe** [PCSX2/pcsx2#10819]
### Describe the Bug

When you start the texture dump process it throws endless corrupted textures (almost 10,000 per minute)

### Reproduction Steps

1. Boot a game (Harry Potter and the Prisoner of Azkaban [SLUS-20926])
2. Open Grahpics Properties
3. Select Dump Textures
4. Dump correct textures and much more corrupted textures

### Expected Behavior

Dump only correct textures

### PCSX2 Revision

v1.75558

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
this is working as intended

**Comment by refractionpcsx2** [comment]
If they are palette textures, they're not meant to look correct. It's also possible it will dump more than it actually uses, which isn't uncommon. How each individual game handles it is different, and it's not always convenient.

But yeah, most likely working as intended.,

**Comment by c0rexe** [comment]
No, it's not working as intended.

These textures aren't even textures at all.
There is an assumption that they are generated depending on the frame rate, respectively 30-50 pieces per second to infinity

Here are a few examples
![1a0592cdf7d29b96-e7884e8e2ef854ef-00006a93](https://github.com/PCSX2/pcsx2/assets/153430211/f2c7b5d2-93fa-44ec-be09-3bae4669e532)
![1ac6b8b9e73b93d8-e7884e8e2ef854ef-00006a93](https://github.com/PCSX2/pcsx2/assets/153430211/25e9de32-91a2-49ce-a509-d225d5312229)
![1b4fff5eab5f5c88-e7884e8e2ef854ef-00006a53](https://github.com/PCSX2/pcsx2/assets/153430211/40f17a21-49d9-4e6d-baf3-e9243a31854f)
![1bb2f6ad796b415d-e7884e8e2ef854ef-00006a53](https://github.com/PCSX2/pcsx2/assets/153430211/57ddd670-789a-47f6-8852-5e0f46c21310)
![1c8f94eedb6e6ba3-e7884e8e2ef854ef-00006a93](https://github.com/PCSX2/pcsx2/assets/153430211/abc57997-670e-4a95-adad-66e2c678ce0c)
![1cac59ab7ab8fdcd-e7884e8e2ef854ef-00006a53](https://github.com/PCSX2/pcsx2/assets/153430211/79fa6af3-12df-4281-9478-8a37387f6d2a)
![1d5c30a6e94c9ee5-e7884e8e2ef854ef-00006a53](https://github.com/PCSX2/pcsx2/assets/153430211/4c326693-0f60-4a46-92cf-4af3ed742e91)
![1d589e4145719b01-e7884e8e2ef854ef-00006a93](https://github.com/PCSX2/pcsx2/assets/153430211/a491b727-216e-4265-93b6-5469dfce9b22)

**Comment by Mrlinkwii** [comment]
1) it is working as intended  , not all ps2 games  like the dump texture feature , due to how said game is made ,

2) please dont put  actual dumped  textures on the issue
