### ISSUE TITLE
[BUG]: Upscaling overcrops screen on Software renderer

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#10814]
### Describe the Bug

While upscaled internal resolution is selected in HW setting, PCSX2 crops multiplied pixels from screen on SW.
- It doesn't occur while internal resolution is set to Native in HW setting.

### Reproduction Steps

1. Boot a game
2. Open Game Properties
3. Select upscaled resolution (e.g. 2x Native)
4. Increase any of Crop value (e.g. Top: 20px)
5. Toggle renderer (Press F9 or select it directly in settings)
6. See overcropped screen

### Expected Behavior

HW's internal resolution setting should not affect cropping on SW.

### PCSX2 Revision

v1.7.5556

### Operating System

Windows 11

**Comment by Berylskid** [comment]
Visual evidence (2x Native and Left: 30px)

https://github.com/PCSX2/pcsx2/assets/91955473/1222a28d-d6b5-4e27-9547-8ad168ce1349

**Comment by refractionpcsx2** [comment]
looks like software matches native x3 (probably software and native x3). I'm not sure which is right, but it's evident it shouldn't be doing this.
