### ISSUE TITLE
[Feature Request]: CustomOverlay

### ISSUE THREAD

**Issue by SysVR** [PCSX2/pcsx2#10834]
### Description

Overlays a message at an arbitrary location.

### Reason

Display specific game values, such as movement speed or coordinates,
display notes.

predefined function
display digits Format:#
**%H:(address,digit,display digits[optional])** //Hex
**%D:(address,digit,display digits[optional])** //Decimal
**%F:(address,digit,display digits[optional])** //Float
**%S:(address,digit,character code)** //String
**%I:(ControllerID,Button/Stick[optional],Press Strength Value[optional])**  //ControllerInput
**print(variable)**
local ~variable=basic arithmetic operations

Other than this, the text is considered normal text.

Size and color can also be specified with markdown tags.

### Examples
It probably does not exist in existing emulators. (I have never seen it).
local SPD=3600/%D:(0x00102333A,2,###,###)
SPEED print(SPD) KM/h
SPEED 001,234 KM/h

SPEED %D:(0x00102333A,2) Meter/s
SPEED 001,234 Meter/s

X:%D:(104333A,2,#.##) Y:%D:(104333C,2,#.##) Z:%D:(104333E,2,#.##)
X:21331.22 Y:0.00 Z:21213.05

**Comment by Mrlinkwii** [comment]
due to how ps2 games are made this cant be done

**Comment by Daniel-McCarthy** [comment]
> due to how ps2 games are made this cant be done

If I am understanding correctly, the expectation is not for PCSX2 to handle knowing game specific values, but to allow displaying an overlay that the user can configure to display memory values.

It would be on the user to set it up per game how they want, and all they need to know is the addresses/types they want to have put on the screen, and PCSX2 supplies the configurable overlay.

**Comment by stenzek** [comment]
Such a concept would be better suited to a general scripting system, because having a "format" that encompasses all use cases is impractical.

But we don't have any plans to add this in the near future.

**Comment by SysVR** [comment]
> Such a concept would be better suited to a general scripting system, because having a "format" that encompasses all use cases is impractical. Definitely don't want to add a markdown parser to pcsx2.
> 
> But we don't have any plans to add this in the near future.

Or use Lua scripts.
https://github.com/pocokhc/pcsx2-1.4.0-rr

**Comment by RedDevilus** [comment]
There is already PINE to do stuff that can access PCSX2, the game and your own PC. Only limit is imagination and coding skills and effort.

**Comment by stenzek** [comment]
I guess we can close this then, since it's not going to happen in the way OP has requested, and it can be achieved through PINE already.

PRs welcome to implement it of course, assuming it meets quality standards.
