### ISSUE TITLE
Deleted this post.

### ISSUE THREAD

**Issue by twarnercool2** [PCSX2/pcsx2#1083]
Nevermind.

**Comment by willkuer** [comment]
How could such issues as this one and the other recently created one ever be tackled/fixed? You dont provide any information at all.

The problem that emulation is slow is also nothing new or unexpected but rather points at your underpowered system for a specific game. Get a better pc and it will br solved by itself.

Do you get dramatic low speeds like <5fps/10% and you have an i7-6700k overclocked above 4.5GHz and all other games run fluently? Or do you have an AMD Sempron @ 1.8 GHZ and this game drops to ~30fps/50%?

Dies it always happen? How does this game react to speedhacks? Cpu/gpu/ee/gs bottleneck?

How can you omit such information and expect that this ever gets 'fixed'?

**Comment by twarnercool2** [comment]
Nevermind, delete this post.
