### ISSUE TITLE
Being able to use asynchronous texture loading and precache textures at the same time

### ISSUE THREAD

**Issue by pepodmc3** [PCSX2/pcsx2#10832]
### Description

Hello.
I want to being able to use asynchronous texture loading and precache textures at the same time, using two folders, one for the textures you want to load asynchronously and other folder for the textures you want to precache. 

### Reason

Im making a texture pack for the game darkwatch. The texture pack will be big (8gb perhaps more).  I'm using an SSD.

Working with dtx1 textures as always as possible, the game loads textures asynchronously pretty fast, but some menus images, if i put them at 4k , there will be always a 1 second or little more of late loading of the texture.

And the precache option take time until it load all textures to memory, and, as the order is arbitrary, sometimes , some textures doesnt get to load before you reach the point where it appears on screen.

So, this way, i can choose which texture is better to load asynchronously, and which textures are better to precache ((bigger ones, menu, loading, etc).

Plus, this would alleviate the long precache load and the amount of ram needed.

### Examples

A lot of emulators have custom texture support and these two ways of loading custom textures , but there is not an emulator that let you use them at the same time.

**Comment by stenzek** [comment]
I don't see the point. Precaching is a pretty silly option in the first place; modern SSDs are more than fast enough to bring a texture in within a frame, and generally it'll have little visibility for at least a few frames, the first time it's used.

If there's a particular scenario where it's lagging, for a second it may be your system (e.g. AV), or it's a bug (in which case post the texture and a GS dump).

Having multiple directories is also unnecessary complexity.
