### ISSUE TITLE
[BUG]: Cars: Mater-National Championship – TLB misses

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#10843]
### Describe the Bug

While playing Cars: Mater-National Championship, you can play a race against another player. If you select the third track to race on, the game bugs out (this is immediately fixed if you move your selection away from that track). According to link, an error "Gif Unit - GS packet size exceeded VU memory size!" occurs.

This occurs on the latest v1.7.5572, and it does not matter if it's from a fresh save, save state, or save file from online. It is present in HW and SW rendering and does not appear to be related to any setting. link, myself, and refraction, as well as the user who brought it to our attention, were all able to recreate this consistently, and it occurs on Aether, so it does not appear to be a regression.

Per refractionpcsx2:

* "already tried all rounding, clamping, flag hacks etc; turning off MTVU and underclocking the EE seems to make it break in a different way"
* "I got past it once by luck"
* I got it to crash without any patches"
* "Play! CTD's [ref could not test it on Dobie at the time]"

### Reproduction Steps

First, you'll need to unlock the mode, so the easiest way to do this if you don't already have a save file is to get one from online. From there, load into the save, select 'Versus', select 'Race', and then move your selection over to the right twice (the third track). The game will bug, and the window will suddenly shift very dramatically to the bottom right. 

### Expected Behavior

The track selection should display normally just like the other ones.

### PCSX2 Revision

v1.7.5572

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro – Flatpak

### CPU

Ryzen 7 5800X

### GPU

GTX 1070

### GS Settings

Default (see above)

### Emulation Settings

Default (see above)

### GS Window Screenshots
How it should look (taken on PCSX2 for another race selection)
![Disney-Pixar's Cars - Mater-National Championship_SLUS-21637_20240222125145](https://github.com/PCSX2/pcsx2/assets/12673964/5096125c-8fa9-4873-bb58-5d584e7b6770)

How it looks for the third track
![Disney-Pixar's Cars - Mater-National Championship_SLUS-21637_20240222125149](https://github.com/PCSX2/pcsx2/assets/12673964/ccae8586-05e7-4511-9b53-03b3fd8faf8c)

**Comment by refractionpcsx2** [comment]
the Packet size errors come after the TLB misses, so I consider them unimportant.

**Comment by refractionpcsx2** [comment]
Tried the game on my PS2, it crashes on there too, guess the game is just broken.

I got to this point, Press left, then the game never responded again
![image](https://github.com/PCSX2/pcsx2/assets/6278726/2b69920c-9880-4d6c-b048-b8f8a5b65e80)

**Comment by refractionpcsx2** [comment]
Me and Prafull did some further investigation, if you start a new game and use the cheat ALLYORS, the versus race selection works fine, however saving the game results in TLB misses.  So there's definitely something messed up happening in this game (but not an emulation bug).

Apparently the PAL release is fine, also.
