### ISSUE TITLE
[BUG]: 007 - Everything or Nothing (USA) - Car doesn't become invisible when activating cloaking.

### ISSUE THREAD

**Issue by Newtype14** [PCSX2/pcsx2#10849]
### Describe the Bug

In 007 - Everything of Nothing, when driving the Porsche Cayenne, you can press a button to cloak the car, making it invisible. In software mode, it works, but in hardware mode (Vulkan, D3D11/12, OpenGL), the car changes color but it doesn't go invisible. Or, it goes invisible only for a brief moment. The cloaking works in the sense that enemies cannot see you, but graphically the car isn't cloaked.

### Reproduction Steps

The first mission where you can do this is called "Serena St. Germaine". It's the 6th or 7th mission. The mission starts with you driving the car, so right away you can press L1 to activate the cloaking and see if it works. I've tried changing every setting in PCSX2 to try and fix this, but nothing worked.

### PCSX2 Revision

PCSX2 Nightly v1.7.5574

### Operating System

Windows 10 (64bit)

### CPU

Intel i7-8700k

### GPU

NVIDIA GTX 1070 Ti

### Emulation Settings

Renderer: Vulkan
Internal resolution: 4x
Blending accuracy: Full

Everything else is default.

### GS Window Screenshots

What it should look like:
![Software](https://github.com/PCSX2/pcsx2/assets/49800083/66cf50de-a5be-4d01-8202-7702ce559133)

What it actually looks like:
![Vulkan](https://github.com/PCSX2/pcsx2/assets/49800083/2a4bb226-4c88-42d8-b7ce-b8004a5ea18a)

**Comment by JordanTheToaster** [comment]
Post a GS dump please.

**Comment by Newtype14** [comment]
> Post a GS dump please.

It's my first time, I don't know when I should press SHIFT + F8. Do I just activate the cloaking and press SHIFT + F8 for just one frame?

**Comment by JordanTheToaster** [comment]
> > Post a GS dump please.
> 
> It's my first time, I don't know when I should press SHIFT + F8. Do I just activate the cloaking and press SHIFT + F8 for just one frame?

Yes

**Comment by Newtype14** [comment]
[007 - Everything or Nothing_SLUS-20751_Cloaking_issue.zip](https://github.com/PCSX2/pcsx2/files/14389027/007.-.Everything.or.Nothing_SLUS-20751_Cloaking_issue.zip)

**Comment by JordanTheToaster** [comment]
> [007 - Everything or Nothing_SLUS-20751_Cloaking_issue.zip](https://github.com/PCSX2/pcsx2/files/14389027/007.-.Everything.or.Nothing_SLUS-20751_Cloaking_issue.zip)

Can you post a savestate in that spot please.

**Comment by Mrlinkwii** [comment]
and a memcard is possible

**Comment by Newtype14** [comment]
After playing around a bit more, I realized that the car will only be invisible if an enemy is directly in your line of sight. You can destroy the car that you're chasing at the start of the mission, then test this with the wreck of the car. When the wreck is in your line of sight, the car will be invisible, but as soon as you drive past it or face another direction, the car loses its invisibility. Here's a save state with the enemy vehicle destroyed: [SLUS-20751 (6848699B).01.zip](https://github.com/PCSX2/pcsx2/files/14390716/SLUS-20751.6848699B.01.zip)

This isn't normal. If you play the game in software mode, the invisibility effect is active whenever you want it to be.

**Comment by lightningterror** [comment]
Preload frame fixes it.

**Comment by Newtype14** [comment]
Indeed it works! Great find!
As a side note, if you want the loading screens to render correctly, you have to enable "Screen Offsets".
