### ISSUE TITLE
[Feature Request]: Increased Value, Decreased Value, Changed Value and Unchanged Value

### ISSUE THREAD

**Issue by thelastlive** [PCSX2/pcsx2#10845]
### Description

I want new filter searches that allow me to find values that were either increased, decreased, changed or unchanged.

### Reason

I own a PlayStation 2 game that renders player's health in a bar so the exact value of player's health is unknown until it's address is found.

Thanks to Daniel McCarthy work I can search all values not equal to 0 as a workaround to the missing "Unknown initial value" feature but when I let player to lose some health I need to do a "decreased value" filter search which is currently missing.

### Examples

Some PlayStation 2 games that render player's health in a bar are: Devil May Cry, God of War, Kingdom Hearts and Resident Evil 4

**Comment by kamfretoz** [comment]
I suppose this is what you're looking for? #10837 which is already WIP as well.

**Comment by thelastlive** [comment]
> I suppose this is what you're looking for? #10837 which is already WIP as well.

I didn't notice this but it doesn't seem that #10837 talks about "unchanged value" filter search.

**Comment by thelastlive** [comment]
> I suppose this is what you're looking for? #10837 which is already WIP as well.

I didn't notice this. Thank you.

**Comment by kamfretoz** [comment]
> I didn't notice this. Thank you. But I want to know why merging is blocked there?

It's not blocked, merging can only be done by the team.
Also it's still under review and testing, it will be merged once we deemed that it is ready.
