### ISSUE TITLE
"Treasure planet" still spins out.

### ISSUE THREAD

**Issue by twarnercool2** [PCSX2/pcsx2#1084]
The game, while lasts longer than before, still spins out.

**Comment by willkuer** [comment]
What is that supposed to mean?
Can you please provide all relevant information?

Just imagine you are a dev unfamiliar with this game and you read suxh an issue. Where and how would you start to solve this?

**Comment by twarnercool2** [comment]
It works fine for a little bit. Then the camera spins out,

**Comment by bositman** [comment]
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues
