### ISSUE TITLE
[Feature Request]: Debugger - Live updating of data and other debugger info

### ISSUE THREAD

**Issue by Daniel-McCarthy** [PCSX2/pcsx2#10840]
### Description

A user requested to have the debugger automatically refresh/update live while the debugger is open. Currently things like the `MemoryView` widget only update when the user interacts with it. If you click the window, it refreshes, but otherwise stays in the same state.
The desirable behavior would be for it to automatically refresh on some interval so that the user can see it update regularly, and if data is changing it requires no additional interaction.

### Reason

Very useful to be able to see the data change as you may be getting an incorrect impression about whether something has/has not changed or whether it changes regularly. A user may be expecting a value and waiting, but even though the memory *has* updated it doesn't display to the screen without another interaction.

### Examples

Here is an example where I set data in the memory via PINE, and may get the impression it didn't work, or didn't happen, but only updates once I click. Although the FFFFFFFF was there from the start, it didn't show until clicked.
A user might expect this to happen immediately, but should at least update on some frequency.
![PCSX2-DebuggerUpdatingDelay](https://github.com/PCSX2/pcsx2/assets/4957200/773fe5b1-920d-4b71-b88a-e89488a6253a)

**Comment by refractionpcsx2** [comment]
I would say at very most it should update at the same speed as the OSD, which is probably once per second or something, I don't recall if we can vary that.  Any quicker is gonna put a bunch of load on the UI thread and a lot of cross-thread talking.

**Comment by Daniel-McCarthy** [comment]
> I would say at very most it should update at the same speed as the OSD, which is probably once per second or something, I don't recall if we can vary that. Any quicker is gonna put a bunch of load on the UI thread and a lot of cross-thread talking.

I agree, I think once a second would be very beneficial as it is. Any frequency would is better than none, and immediate updates isn't a fair expectation.

**Comment by Mrlinkwii** [comment]
fixed in #10860
