### ISSUE TITLE
[Feature Request]: Add new context menu "Find out what accesses/reads from/writes to this address" to Memory Search results

### ISSUE THREAD

**Issue by thelastlive** [PCSX2/pcsx2#10847]
**I want to know what Daniel McCarthy thinks about it**

### Description

Recently the Memory Search results received a new context menu with the option called "Go to in Disassembly" according to the feature request https://github.com/PCSX2/pcsx2/issues/10370

Below "Go to in Disassembly" add three new options:

1. Find out what accesses this address.
2. Find out what writes to this address.
3. Find out what reads from this address.

Option 1. Inserts a new data breakpoint or watchpoint of type "Read and Write" at the right clicked address.

Option 2. Inserts a new data breakpoint or watchpoint of type "Write" at the right clicked address.

Option 3. Inserts a new data breakpoint or watchpoint of type "Read" at the right clicked address.

### Reason

This can be done without this feature but doing this without this feature is both more tedious, time consuming and error prone because in the new breakpoint dialog after selecting the type of the new breakpoint (either "Read", "Write" or "Read and Write") the user has to type and enter all the 8 hexadecimal digits of the address that he or she found with the help of the new Memory Search feature of the PCSX2 Qt Debugger in order and verify and make sure that he or she doesn't mistakenly do a typo and with this feature the user doesn't have to because with this feature the user can do this with just two simple clicks (one right click on the address he or she wants to insert the new data breakpoint or watchpoint to show the context menu and left click to choose the type of the data breakpoint or watchpoint that he or she wants) and this is both more convenient, quick and error free.

### Examples

I am using the latest version of PCSX2 Qt emulator to play a PlayStation 2 shooter game that I own.

In this game the player has a finite ammunition for each weapon that he or she owns when playing fair but I want to play this shooter game unfair and have infinite ammunition cheat for all the weapons that the player owns.

To achieve this infinite ammunition cheat I have to find the MIPS instruction (either SB, SH or SW) that updates my ammunition every time I shoot with any weapon and replace it with a NOP instruction that does nothing when executed so that my ammunition is not decreased when shooting with any weapon and thus achieving infinite ammunition.

To find that MIPS instruction I have to first find the address of my ammunition in the memory of the PlayStation 2 shooter game.

The address of my ammunition can be found with the help of the new "Memory Search" feature of the PCSX2 Qt Debugger.

First I see that my ammunition is 100 shells and assuming that this is an unsigned word (4 bytes = 32 bits in MIPS architecture) I am firstly looking for 100 when clicking on the Search button.

Many words with value == 100 are found and their addresses are listed.

To narrow down this list I fire super shotgun that depletes 2 shells and my shells is now 98.

Then I am going back to Memory Search, set Value to 98 and click on the "Filter Search" button.

The addresses of fewer words with value == 98 are now in the list but this is still too many so I return to game, fire super shotgun again and now my shells is 96.

Going back to Memory Search, setting value to 96 and clicking "Filter Search" button again and now the list contains the address of my shells.

Right click this address and a context menu pops up.

In this context menu click "Find out what writes to this address".

This action inserts a new data breakpoint or watchpoint of size "Word" (because I was looking for a word at first) and of type "Write".

Now return to game and fire super shotgun again.

The PlayStation 2 shooter game pauses and breaks into the debugger and the disassembly view shows the SW instruction that updates my shells.

Finally right click that SW instruction and in the context menu that appears click "NOP instruction".

The SW instruction that updates my shells has been replaced by a NOP instruction that does nothing when executed.

Now resume the game and enjoy having infinite shells.

The same procedure can be done and repeated for all other kinds and types of ammunitions including bullets, nails, rockets, missiles, cells and etc.

**I want to know what Daniel McCarthy thinks about it**

**Comment by Daniel-McCarthy** [comment]
Hey there, if you're just looking for a way to create a memory breakpoint (on access/write/read) from the `MemoryView` widget when right clicking on memory, that's perfectly reasonable.

I'd imagine like:
![image](https://github.com/PCSX2/pcsx2/assets/4957200/cb709584-52c9-42d5-a917-5bbfc2f0d59e)
Or just `Add Breakpoint....` and bring up the dialog for them to select which type.
Is that essentially what you're looking for?


Also, I'm not the only one working on the debugger nor the person who created it. It'd be better not to put a name on it as anyone may pick it up. If you'd like feedback in general, an easy way would be in the PCSX2 discord.

**Comment by thelastlive** [comment]
> Hey there, if you're just looking for a way to create a memory breakpoint (on access/write/read) from the `MemoryView` widget when right clicking on memory, that's perfectly reasonable.
> 
> I'd imagine like: ![image](https://private-user-images.githubusercontent.com/4957200/307338603-cb709584-52c9-42d5-a917-5bbfc2f0d59e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDExODEsIm5iZiI6MTcwODcwMDg4MSwicGF0aCI6Ii80OTU3MjAwLzMwNzMzODYwMy1jYjcwOTU4NC01MmM5LTQyZDUtYTkxNy01YmJmYzJmMGQ1OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTUwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ5MTk5YmIxNjk1NjQ5ZTM1ZGI1YTU4M2E3ZDViN2VlMDQ4ZjE5MTY3YzQwZDJkZWY4N2JlNzNjNjQxMzMzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3UWdHJhiIDP7lXLbRTZx3bxAnZvlRuCyyM0dhpp-EMw) Or just `Add Breakpoint...` and bring up the dialog for them to select which type. Is that essentially what you're looking for?
> 
> Also, I'm not the only one working on the debugger nor the person who created it. It'd be better not to put a name on it as anyone may pick it up. If you'd like feedback in general, an easy way would be in the PCSX2 discord.

I submitted #10374 before submitting this and F0bes closed it as not planned and also locked it.

I was angry when he did it because this is an easy feature request that simply creates a new data breakpoint at the right clicked address and I was shocked why it wasn't closed as complete.

And #10374 wasn't my first feature request about the debugger but I had more feature requests in January of 2023 and it doesn't seem that Stenzek and F0bes like me at all.

Since then I blocked both Stenzek and F0bes and I wish that I will no longer read their comments anymore nor their activity.

I saw all your commits and contributions to the debugger of PCSX2 and I think that I can only trust you.

**Comment by F0bes** [comment]
I don't believe the earlier revisions of your linked FR (you've edited it multiple times) made it clear that you wanted _just_ a memory breakpoint set. Whether or not, I'm not opposed to having a shortcut to create a breakpoint from the memory search result context menu.

**Comment by thelastlive** [comment]
> I don't believe the earlier revisions of your linked FR (you've edited it multiple times) made it clear that you wanted _just_ a memory breakpoint set. Whether or not, I'm not opposed to having a shortcut to create a breakpoint from the memory search result context menu.

Why not?

**Comment by F0bes** [comment]
I believe you've misunderstood me.
I'm okay with this feature request.

**Comment by F0bes** [comment]
> **I don't believe the earlier revisions of your linked FR (you've edited it multiple times) made it clear that you wanted _just_ a memory breakpoint set.** Whether or not, I'm not opposed to having a shortcut to create a breakpoint from the memory search result context menu.

**Comment by thelastlive** [comment]
> > **I don't believe the earlier revisions of your linked FR (you've edited it multiple times) made it clear that you wanted _just_ a memory breakpoint set.** Whether or not, I'm not opposed to having a shortcut to create a breakpoint from the memory search result context menu.

The description of #10374 was super simple and clear. I don't know how to make it simpler and clearer.

**Comment by refractionpcsx2** [comment]
I suggest you start being a bit more respectful, if you want to remain here. The fact you were previously banned means I should just ban you outright, but I'm choosing not to.

Be careful how you approach future replies.

**Comment by thelastlive** [comment]
> I suggest you start being a bit more respectful, People here are trying to help, and if you want something, being a rude and disrespectful isn't going to get you what you want. if you want to remain here.
> 
> Be careful how you approach future replies.

I don't want to be a rude and disrespectful person. I am just sad that good contributors, like Daniel McCarthy, don't see my feature requests because they were closed.

**Comment by refractionpcsx2** [comment]
That's not the part I was on about, I was on about being rude about fobes and stenzek who put a lot of damn work in to this emulator, then you come here slagging them off.

**Comment by thelastlive** [comment]
> That's not the part I was on about, I was on about being rude about fobes and stenzek who put a lot of damn work in to this emulator, then you come here slagging them off.

I did not mean it.

**Comment by stenzek** [comment]
Renamed this issue and the other dupe as well. Please do not put others' names in the title, it comes across as demanding. Remember that we're a team of volunteers.

**Comment by thelastlive** [comment]
> Renamed this issue and the other dupe as well. Please do not put others' names in the title, it comes across as demanding. Remember that we're a team of volunteers.

Understood

**Comment by DanielMcCarthyFan** [comment]
> Hey there, if you're just looking for a way to create a memory breakpoint (on access/write/read) from the `MemoryView` widget when right clicking on memory, that's perfectly reasonable.
> 
> I'd imagine like: ![image](https://private-user-images.githubusercontent.com/4957200/307338603-cb709584-52c9-42d5-a917-5bbfc2f0d59e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODk2NDksIm5iZiI6MTcwODc4OTM0OSwicGF0aCI6Ii80OTU3MjAwLzMwNzMzODYwMy1jYjcwOTU4NC01MmM5LTQyZDUtYTkxNy01YmJmYzJmMGQ1OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTU0MjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA0M2JmNjFhZGJlZDA2M2YzZmNmZDNiNjcxY2FlMzM4ZDZhODI2MmY3MDM4ODUzY2NmMWFjYjgxMzNjYjU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TWi-IsFe47_YpBdD6k3g3ZbABMgEjPBRgQGxmvqua0Y) Or just `Add Breakpoint...` and bring up the dialog for them to select which type. Is that essentially what you're looking for?
> 
> Also, I'm not the only one working on the debugger nor the person who created it. It'd be better not to put a name on it as anyone may pick it up. If you'd like feedback in general, an easy way would be in the PCSX2 discord.

I would like to have the "Add Breakpoint" option in the context menu of the MemoryView widget but I would also like to have the "Add Breakpoint" option also in the context menu of the Memory Search results widget like how the "Go to in Disassembly" option was added there.

Do you know what is the Memory Search results widget? This is not the MemoryView widget but this is the ListView that shows all found addresses from the last search or filter search.
