### ISSUE TITLE
Update WS patches

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#1085]
There have been lots of changes since last update and we should get the latest before the release.
@avih is in charge :P

**Comment by avih** [comment]
I am? :) (on it)

**Comment by avih** [comment]
Seems like Devina won't release a cleanup of the archive before some conditions are met. See http://forums.pcsx2.net/Thread-September-2015-progress-report?pid=500526#pid500526

Ping me once this changes.

**Comment by bositman** [comment]
Thanks avih
