### ISSUE TITLE
[Feature Request]: Make PCSX2 automatically detect built in gamepad input for gaming handhelds like ROG Ally, to be able to navigate GUI.

### ISSUE THREAD

**Issue by Bobble80** [PCSX2/pcsx2#10858]
### Description

I’d like to see if it’s possible to add the feature into PCSX2 for it to automatically detect gamepads so you can navigate through the GUI using said gamepad instead of needing to use a mouse. 

I use PCSX2 on some gaming handheld PC’s like the ROG Ally and the emulator currently doesn’t pick up the built in gamepad on the device. I have to use either a mouse and keyboard or the touch screen on the handheld to select the game I want to play. 

### Reason

I’m not asking for any complicated functions to be implemented. I’d just like to be able to use the d-pad or joystick to be able to navigate through the game library and then use the A button to run the game. 

A couple of the main PC emulators have this feature right now and makes things a lot easier when playing on a gaming handheld with built in controls. 

### Examples

This feature is currently available in a couple of emulators at the moment, like Yuzu, PPSSPP, RetroArch and recently RPCS3 has just added it. 
![65A76C08-2A91-4182-9FAC-2CFBFC6433ED](https://github.com/PCSX2/pcsx2/assets/155309955/a23e30a8-e74a-4ecd-86cc-7173d180e76b)

**Comment by Mrlinkwii** [comment]
you can use big picture mode  to navigate though the settings using your controller
