### ISSUE TITLE
[BUG]: FIFA Street 2 have graphical glitches on the interface

### ISSUE THREAD

**Issue by Heroneet** [PCSX2/pcsx2#10859]
### Describe the Bug

Fifa Street 2 still having annoying graphical glitches, but now, they happen just with the interface while in match.

### Reproduction Steps

Just run the game and enter in a Quick Match, but this issue gets more evident when:

1. You score a gamebreaker goal.
2. In-game, go to Options > Video Options > Camera, and change it to "Side Cam Far".

### Expected Behavior

Graphical glitches don't happen.

### PCSX2 Revision

v1.7.5577

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

LMDE 6 - Flatpak

### CPU

i5-7400

### GPU

RX 570

### GS Settings

Internal Resolution: 6x Native (~2160p/4k)

### GS Window Screenshots

![Screenshot from 2024-02-24 16-10-18](https://github.com/PCSX2/pcsx2/assets/150282026/7ba11bfe-90eb-4248-895a-487eac4f8d53)
![Screenshot from 2024-02-24 16-10-31](https://github.com/PCSX2/pcsx2/assets/150282026/80f1b2b7-b3bd-435c-b811-71d5fff3d5d5)

**Comment by refractionpcsx2** [comment]
probably path3 masking stuff, I know that game has trouble with that.

**Comment by prafullpcsx2** [comment]
I can't reproduce this issue on my system. Can you upload a gsdump with issue clearly visible?

**Comment by refractionpcsx2** [comment]
It's probably a core problem, you'd be better served with a savestate.

**Comment by Heroneet** [comment]
> I can't reproduce this issue on my system. Can you upload a gsdump with issue clearly visible?

[FIFA Street 2_SLES-53797_20240227200400.gs.zip](https://github.com/PCSX2/pcsx2/files/14426601/FIFA.Street.2_SLES-53797_20240227200400.gs.zip)

**Comment by prafullpcsx2** [comment]
Blended sprites/triangles fixes this

**Comment by Heroneet** [comment]
> Blended sprites/triangles fixes this

Tested with CPU Sprite Render Size 6 (384 Max Width) + Blended Sprites/Triangles, now it runs without any issues.

**Comment by prafullpcsx2** [comment]
> > Blended sprites/triangles fixes this
> 
> Tested with CPU Sprite Render Size 6 (384 Max Width) + Blended Sprites/Triangles, now it runs without any issues.

Are you sure 6 is needed? I tried with cpu sprite render size 1 and it seemed to be working fine. Can you recheck with 1?

**Comment by Heroneet** [comment]
> > > Blended sprites/triangles fixes this
> > 
> > 
> > Tested with CPU Sprite Render Size 6 (384 Max Width) + Blended Sprites/Triangles, now it runs without any issues.
> 
> Are you sure 6 is needed? I tried with cpu sprite render size 1 and it seemed to be working fine. Can you recheck with 1?

It works with CPU Sprite Render Size 1 too

**Comment by refractionpcsx2** [comment]
We've already added a fix to the gamedb
