### ISSUE TITLE
[BUG]: Crash of the Titans, Pad not responding in mission 12

### ISSUE THREAD

**Issue by FahrentH8t** [PCSX2/pcsx2#10851]
### Describe the Bug

In Crash of the Titans mission 12 (Weapons of Mass Construction), there is a certain area that pad becomes unresponsive to anything other than basic movement.

### Reproduction Steps

Boot up Crash of the titans. Mission 12.
Reach the point of the screenshot and try to progress further you will see the bug after the 2nd jump area or so.
![unknown_2024 02 23-23 42](https://github.com/PCSX2/pcsx2/assets/28109940/d55a1498-9db6-466e-9451-d53c1dafd028)

i post savestate and memcard
[mem.zip](https://github.com/PCSX2/pcsx2/files/14389800/mem.zip)
[SLUS-21583 (C6E85EF0).01.zip](https://github.com/PCSX2/pcsx2/files/14389850/SLUS-21583.C6E85EF0.01.zip)

### Expected Behavior

to work i guess.

### PCSX2 Revision

v1.7.5574

### Operating System

Windows 11

### CPU

i3-13100F

### GPU

RX 6600XT

### GS Settings

Internal Resolution: 3x Native (~1080p)
Everything else is default.

### Emulation Settings

Default.

**Comment by FahrentH8t** [comment]
Went back to 1.7.5312 and problem was still there.
Unfortunately build before 1.7.5312 are not compatible with save state.

**Comment by stenzek** [comment]
Have you verified your game? Not using any cheats? Are you sure the game is supposed to behave this way? Compare it to your real PS2.

**Comment by kamfretoz** [comment]
Works on my machine, control still works after the 4th jump platform.

https://github.com/PCSX2/pcsx2/assets/14798312/1bc02628-4c24-4c15-942d-0a03bc23260e

**Comment by stenzek** [comment]
Great! Thanks for checking.
