### ISSUE TITLE
[BUG]: Flickering in FlatOut 2

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#10865]
### Describe the Bug

In some levels the left side of the screen is flickering

Vulkan / OGL / D3D :
https://github.com/PCSX2/pcsx2/assets/41426906/3794a84a-fc57-46e0-87d7-eeca6f387a37

Software :
![FlatOut 2_SLES-54003_20240227154819](https://github.com/PCSX2/pcsx2/assets/41426906/f735f973-20ef-4fe8-8675-451ca04cda4b)

### Reproduction Steps

"Derby Bowl 1" is one of those levels

### Expected Behavior

Screen is not flickering anymore

### PCSX2 Revision

v1.7.5579

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

Ubuntu 22.04 has the same problem

### CPU

i7-4790 / i7-11700B

### GPU

GT 1030 / GTX 1050

### GS Settings

Default settings

### Emulation Settings

Default settings

### GS Window Screenshots

[snaps.zip](https://github.com/PCSX2/pcsx2/files/14421451/snaps.zip)

**Comment by prafullpcsx2** [comment]
Enabling frame buffer conversion seems to fix it for the gs dump. You can try it with the game also.

**Comment by refractionpcsx2** [comment]
FBC stops it flickering but it doesn't get rid of it (that light isn't there in software)

**Comment by refractionpcsx2** [comment]
This is a regression from #9251

**Comment by evildeadhc** [comment]
1.7.5592, rtx2060super, windows 10, Vulkan\D3D\OGL. I have exactly the same flickering on the left side of the screen. I've tried fbc, it helps but it has dramatically impact on performance. It isn't depend on level, although menu works well.
