### ISSUE TITLE
Commit to 1.4.x branch and merge it then to master

### ISSUE THREAD

**Issue by jobermayr** [PCSX2/pcsx2#1086]
Advantages:
- not forget to push a commit in 1.4.x branch to master
- have a clean history with only one commit  for same thing
- merging e. g. 5 commits take only one merge commit and not 5 "real" commits like ATM
- tells merge conflicts (if source file differs between branches)

**Comment by avih** [comment]
Not sure what point you're trying to make. So far the 1.4.x branch gets some cherry-picked commits from master, and that's it. It doesn't need to merge back to master since it came from master to begin with.

Please explain yourself better, preferably in the form of:
1. You now do A, B, C.
2. This is bad because X, Y, Z.
3. So it would better to instead do J, K, L.

**Comment by jobermayr** [comment]
cherry-pick is only for one commit (e. g. backporting)
merge is for all commits (e. g. forwarding changes in a branch to master)

See how mixxx managed it:
https://github.com/mixxxdj/mixxx/network
first line is master, second is 1.12 branch
-> they committed to 1.12 branch and then merged the whole branch to master

**Comment by gregory38** [comment]
Well in this case it is backporting. It wasn't planned to integrate such commits in the first place. Besides people do a PR on master not the branch directly. Git can handle the history mess, so it isn't a big deal.

**Comment by jobermayr** [comment]
If anybody detects a regression in a 3 month old commit in master branch I am sure you don't know extemporaneously whether the commit is in 1.4.x branch or not (master and 1.4.x have different hashes for the very same commit).
With "git merge origin/1.4.x" you know exactly that it was for 1.4.x branch since you have only one commit with the same hash.

**Comment by gregory38** [comment]
I'm closing the issue to keep the issue tracker manageable. But I'm afraid that next release will be the same mess.
