### ISSUE TITLE
[BUG]: PCSX2 version 1.7.5590 flagged as trojan virus.

### ISSUE THREAD

**Issue by Morphof** [PCSX2/pcsx2#10878]
### Describe the Bug

When downloading the emulator, windows defender flags PCSX2 as a trojan script called Wacatac.B!ml

### Reproduction Steps

Download nightly build version 1.7.5590

### PCSX2 Revision

PCSX2 1.7.5590

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
This is a false positive, happens all the time on and off, nothing we can do about it
