### ISSUE TITLE
[BUG]: DPad input not detected for XBox Series Controller when in wired mode

### ISSUE THREAD

**Issue by birthtothunder** [PCSX2/pcsx2#10871]
### Describe the Bug

Xbox Series controller Dpad buttons are not detected, It works fine in Bluetooth, just not wired. I believe [this](https://github.com/PCSX2/pcsx2/issues/8483) talked about my specific issue but it was dropped.

It's not a controller/linux issue, the controller works perfectly in RPCS3 or any other software that uses SDL.

### Reproduction Steps

1. Open PCSX2
2. Go to Controllers
3. Go to Controller Port 1
4. Attempt to assign any button with the Dpad
6. It fails

### Expected Behavior

1. Open PCSX2
2. Go to Controllers
3. Go to Controller Port 1
4. Attempt to assign any button with the Dpad
5. The Dpad is detected and the button is assigned with the Dpad
### PCSX2 Revision

1.7.5585

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS

**Comment by stenzek** [comment]
I'm pretty sure this is a system specific issue, and nothing on our end. Game controllers shouldn't be relying on hats, that's a joystick thing.

**Comment by birthtothunder** [comment]
Fixed it by installing xone.

**Comment by RFxGAMER** [comment]
Hi i ran into the same problem in PCSX2 and PPSSPP what is “xone.” And how can i get it
