### ISSUE TITLE
[Feature Request]: update of CHD to support ZSTD

### ISSUE THREAD

**Issue by Papermanzero** [PCSX2/pcsx2#10879]
### Description

https://docs.mamedev.org/tools/chdman.html#createraw

Mame 0.262 introduced zstd as data compression. It would be good to update to the newest chd version to use the benefits from zstd over zlib.

### Reason

This is an increase of reading speeds and compression for archives

### Examples

The example is that reading speeds are increased and compression is much higher with the new chd version

**Comment by lightningterror** [comment]
This is already implemented.

**Comment by Papermanzero** [comment]
Thank you 🙏
