### ISSUE TITLE
NFS - MW brakes

### ISSUE THREAD

**Issue by Andre98** [PCSX2/pcsx2#1088]
![2](https://cloud.githubusercontent.com/assets/16597553/12177807/60df44a2-b56e-11e5-8ab2-991aa027f5fa.png)
So I gave a some tries with Pcsx2, and i gotta say that i really like it. I used to play a game before on my ps2 but I never saw it again so i decided to play with the emulator. I have almost no problem with it, only the fps sometimes.
But that's not the issue. The real issue is when I'm playing Need For Speed : Most Wanted
I don't know why this happens but I've pretty much tried everything, changing settings, enabling/disabling hacks but it still doesn't do anything. When i'm in game, I start getting laggy and after a while the game completly brakes and the sound just keeps looping like an error sound. It makes for me impossible to play it, since i can't progress. Before i didn't have any problem.

**Comment by Andre98** [comment]
Forgot to mention that this pops out on the pcsx2 console : 
padman: DMA Busy ID = 0d4f0002 ret = 1
        SB_STAT = f0000102

**Comment by willkuer** [comment]
Probably you should visit the forum (forums.pcsx2.net). You are clearly looking for support and not reporting a bug with complete information.
The github issue tracker on the other hand is not a good place to get support.

**Comment by Andre98** [comment]
I reported cause I don't know if this is a real bug, and I'm not an expert on computers yet .. I just found that it is some kind of Dma problem (guess related to Sound) and don't know how to fix it.

**Comment by vgturtle127** [comment]
@Andre98 This game has always had frame rate drops, so that probably isn't the issue. What is the serial number of the game you are running?

**Comment by gregory38** [comment]
Try version from here (don't test one by one): http://buildbot.orphis.net/pcsx2/ if you're able to find a working version. If yes, try to find the first version that break.

**Comment by refractionpcsx2** [comment]
I'm going to mark this as fixed, as i suspect all the NFS games are fine now in OGL
