### ISSUE TITLE
[BUG]: Texture Dumping/Replacement changed dumping behavior of number textures in NCAA and Madden Football games

### ISSUE THREAD

**Issue by antdroidx** [PCSX2/pcsx2#10894]
### Describe the Bug

Starting in [V1.7.4034 ](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4034)and newer, the way player uniform numbers in NCAA Football 06 (and other NCAA games in this series) and Madden series games started to dump differently than previous. Instead of dumping a file that dumps numbers 0-7 and another file that dumps 8-9, it dumps each number individually.

This is interesting because the actual texture file for this game is 0-7 and 8-9 as it was in older versions, and not individual files as is in V1.7.4034 and newer.  The original game's textures are in MMAP file format from EA.

We are interested if there is way to revert back to how textures were dumped as we had made several mods to these football games and have not been able to upgrade to later PCSX2 emulators due to this texture update change. We made thousands of uniforms with the old uniform number textures.

![e7cb950a6a722576-86372989f9238953-00005dd4](https://github.com/PCSX2/pcsx2/assets/24241868/ec06a60c-a9d1-495b-a3bc-9bcb141b4b87)
![779b9990d0061ded-86372989f9238953-00006214](https://github.com/PCSX2/pcsx2/assets/24241868/0a68a146-1549-4828-97aa-b5880a6a7214)
![Screenshot 2024-03-06 204728](https://github.com/PCSX2/pcsx2/assets/24241868/7aec586f-53b3-407f-a914-13a43959c0c7)

### Reproduction Steps

Loaded NCAA Football 06 and texture dumped using [V1.7.4033](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4033) and got 0-7 and 8-9 textures as intended.

Loaded NCAA Football in [v1.7.4034](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4034) and textured dump and got individual texture files, not intended.

### Expected Behavior

Texture dump numbers 0-7 and another file that dumps 8-9, as it was originally intended by EA.

This is interesting because the actual texture file for this game is 0-7 and 8-9 as it was in older versions, and not individual files as is in V1.7.4034 and newer.  The original game's textures are in MMAP file format from EA.

### PCSX2 Revision

pcsx2-v1.7.5600-windows-x64-Qt

### Operating System

Windows 11

### CPU

AMD 6800U

### GPU

AMD Radeon 680M

**Comment by stenzek** [comment]
It's likely when I added region textures.

I have no interest in supporting the "old" behaviour, because not only would it be messy, region textures are advantageous for many games; it prevents random junk getting hashed, instead constraining the "texture" to the region the game specifies it to be clamped with. Since GS texture sizes must be powers of 2, it's the only way developers could achieve non-power-of-2 sized textures.
