### ISSUE TITLE
[BUG]: Ratchet & Clank vendor interface crashes with Vulkan renderer

### ISSUE THREAD

**Issue by attilavs2** [PCSX2/pcsx2#10896]
### Describe the Bug

The entire emulator crashes when trying to open a Gadgetron vendor in Vulkan mode, similar to #2088

### Reproduction Steps

Go up to any Gadgetron vendor and press triangle, i haven't tried yet but the same issue probably is present on inforobots too.

### Expected Behavior

The interface appearing on the various screens and the game continuing to run, like in OpenGL mode.

### PCSX2 Revision

v.1.7.5596

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian 12

### CPU

Pentium Gold 8505

### GPU

Intel UHD graphics 48EU mobile (Alder Lake)

### GS Settings

Vulkan renderer, rest default.

### Emulation Settings

No non-default emulation settings.

### GS Window Screenshots

![Screenshot_20240307_115302](https://github.com/PCSX2/pcsx2/assets/60986544/3893216f-404b-4c4d-b5e4-00ba2516005e)
Trying to open the first vendor on planet Novalis

**Comment by JordanTheToaster** [comment]
Please update your GPU drivers.

https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by lightningterror** [comment]
Can you upload the any crash dump/log/stacktrace?
Also a gsdump taken in sw renderer where the crash would appear.

**Comment by attilavs2** [comment]
> Please update your GPU drivers.
I am using the latest provided by the Debian repositories.
>Can you upload the any crash dump/log/stacktrace?
Will do

**Comment by TheTechnician27** [comment]
Runs without issue on my laptop with an i5-1240P (Xe graphics). Tested on v1.7.5584 and v1.7.5600.

![Ratchet   Clank_SCUS-97199_20240307081449](https://github.com/PCSX2/pcsx2/assets/12673964/6c52070c-3b7b-4cfd-86a8-895dda482df0)

**Comment by stenzek** [comment]
Dump runs fine for me on NVIDIA on Windows, with no validation layer errors reported. Not that the layer has 100% coverage, but usually if we're doing something wrong, it triggers a warning.

If it's crashing with the GS dump, then this is likely a driver bug. Debian is notorious for shipping ancient packages. Since @TheTechnician27 stated it doesn't occur on newer drivers, I'm going to close as invalid.
