### ISSUE TITLE
Pcsx2 linux with print GL error enabled broken GCC 5.3?

### ISSUE THREAD

**Issue by maximu** [PCSX2/pcsx2#1089]
crash always for me
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Core dumped.

>Program received signal SIGABRT, Aborted.
[Switching to Thread 0xeebdeb40 (LWP 20692)]
0xf7fd9bf0 in __kernel_vsyscall ()
(gdb) where
#0  0xf7fd9bf0 in __kernel_vsyscall ()
#1  0xf66e2e66 in raise () from /usr/lib32/libc.so.6
#2  0xf66e44e7 in abort () from /usr/lib32/libc.so.6
#3  0xf6969e55 in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc-5.3.0/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0xf6967943 in __cxxabiv1::__terminate (handler=0xf6969d00 <__gnu_cxx::__verbose_terminate_handler()>)
    at /build/gcc-multilib/src/gcc-5.3.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#5  0xf69679bd in std::terminate () at /build/gcc-multilib/src/gcc-5.3.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
#6  0xf6967c81 in __cxxabiv1::__cxa_throw (obj=0xeba93230, tinfo=0xf6a66428 <typeinfo for std::length_error>, dest=0xf697cd30 <std::length_error::~length_error()>)
    at /build/gcc-multilib/src/gcc-5.3.0/libstdc++-v3/libsupc++/eh_throw.cc:87
#7  0xf6991ca4 in std::__throw_length_error (__s=0xf6a1eaa9 "basic_string::_M_create") at /build/gcc-multilib/src/gcc-5.3.0/libstdc++-v3/src/c++11/functexcept.cc:86
#8  0xf69ff09a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create (this=0xeebddb50, __capacity=@0xeebddb2c: 4294967295, 
    __old_capacity=0) at /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/32/libstdc++-v3/include/bits/basic_string.tcc:142
#9  0xf07742c4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0xeebddb50, 
    __beg=0xee24bed8 "GSDeviceOGL::Create", __end=<optimized out>) at /usr/include/c++/5.3.0/bits/basic_string.tcc:223
#10 0xf07743a5 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char const*> (__end=0xee24bed7 "", 
    __beg=0xee24bed8 "GSDeviceOGL::Create", this=0xeebddb50) at /usr/include/c++/5.3.0/bits/basic_string.h:195
#11 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (__end=0xee24bed7 "", 
    __beg=0xee24bed8 "GSDeviceOGL::Create", this=0xeebddb50) at /usr/include/c++/5.3.0/bits/basic_string.h:214
#12 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=..., __n=4294967295, __s=0xee24bed8 "GSDeviceOGL::Create", 
    this=0xeebddb50) at /usr/include/c++/5.3.0/bits/basic_string.h:448
#13 GSDeviceOGL::DebugOutputToFile (gl_source=33354, gl_type=33385, id=2989, gl_severity=33387, gl_length=-1, gl_message=0xee24bed8 "GSDeviceOGL::Create", 
    userParam=0x0) at /home/mrc/pcsx2/plugins/GSdx/GSDeviceOGL.cpp:1525
#14 0xebbbc5ab in ?? () from /usr/lib32/xorg/modules/dri/i965_dri.so
#15 0xf077df01 in GSDeviceOGL::Create (this=0xee201d80, wnd=0xee23b228) at /home/mrc/pcsx2/plugins/GSdx/GSDeviceOGL.cpp:215
#16 0xf07bf7db in GSRenderer::CreateDevice (this=0xee2020e0, dev=0xee201d80) at /home/mrc/pcsx2/plugins/GSdx/GSRenderer.cpp:79
#17 0xf076cff0 in _GSopen (dsp=dsp@entry=0x9df6500 <pDsp>, title=title@entry=0xf081ea85 "", renderer=GSRendererType::OGL_SW, threads=<optimized out>)
    at /home/mrc/pcsx2/plugins/GSdx/GS.cpp:469
#18 0xf076d5df in GSopen2 (dsp=0x9df6500 <pDsp>, flags=1) at /home/mrc/pcsx2/plugins/GSdx/GS.cpp:536
#19 0x08097170 in SysMtgsThread::OpenPlugin (this=0x9ee48d0 <mtgsThread>) at /home/mrc/pcsx2/pcsx2/MTGS.cpp:195
#20 0x08098fda in SysMtgsThread::OnResumeInThread (this=0x9ee48d0 <mtgsThread>, isSuspended=true) at /home/mrc/pcsx2/pcsx2/MTGS.cpp:570
#21 0x082c9147 in SysThreadBase::StateCheckInThread (this=0x9ee48d0 <mtgsThread>) at /home/mrc/pcsx2/pcsx2/System/SysThreadBase.cpp:324
#22 0x08097dbb in SysMtgsThread::ExecuteTaskInThread (this=0x9ee48d0 <mtgsThread>) at /home/mrc/pcsx2/pcsx2/MTGS.cpp:276
#23 0x0838c22f in Threading::pxThread::_try_virtual_invoke (this=0x9ee48d0 <mtgsThread>, method=<optimized out>)
    at /home/mrc/pcsx2/common/src/Utilities/ThreadTools.cpp:545
#24 0x0838d53f in Threading::pxThread::_internal_execute (this=0x9ee48d0 <mtgsThread>) at /home/mrc/pcsx2/common/src/Utilities/ThreadTools.cpp:644
#25 0x0838d67e in Threading::pxThread::_internal_callback (itsme=0x9ee48d0 <mtgsThread>) at /home/mrc/pcsx2/common/src/Utilities/ThreadTools.cpp:684
#26 0xf6877315 in start_thread () from /usr/lib32/libpthread.so.0
#27 0xf67a0d6e in clone () from /usr/lib32/libc.so.6

If disable GL print this error not are present and working fine.

**Comment by gregory38** [comment]
Driver change. By the way I suggest to run a release build  (it would be faster)

**Comment by maximu** [comment]
Yes, I always use Release build only one active gdb/debug for debugging to give more precise information thx the fix :+1: :)

**Comment by gregory38** [comment]
Code is never called in release build.
