### ISSUE TITLE
[BUG]: Smash Cars PAL freezes randomly

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#10897]
### Describe the Bug

The game freezes a few minutes after starting randomly even sometimes on the circuit loading screen. I have tried both vulkan and D3D11 with the same result, as well as at 50 Hz and 60 Hz. Sometimes errors are shown in the textures in case it can affect this problem in any way.

### Reproduction Steps

Freezes randomly. It happens with the latest version 1.75600 and I also tried it with 1.75105

### PCSX2 Revision

1.75600

### Operating System

Windows 11

### CPU

AMD Ryzen 5 5600H

### GPU

AMD Ryzen 5 5600H

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Smash Cars_SLES-51800_20240307164304.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/14526831/Smash.Cars_SLES-51800_20240307164304.gs.zst.zip)

**Comment by Mrlinkwii** [comment]
when did the issue start  ? or was things a thing always happenening

**Comment by JordanTheToaster** [comment]
> > when did the issue start ? or was things a thing always happenening
> 
> If you are referring to the pcsx2 version, I couldn't say, I have only tried those two recent versions and it has the same problem. I have seen that a problem with this has never been opened and it is possible that it was always there

It was fixed before but it seems to have re-broken at some point and now I've re-fixed it so hopefully it will stay working or otherwise I will scream.
