### ISSUE TITLE
[BUG]: Broken shuffle effect  on superman shadow of apokolips

### ISSUE THREAD

**Issue by Mrlinkwii** [PCSX2/pcsx2#10908]
### Describe the Bug

~~broken shuffle effect  in superman shadow of apokolips  is a regression  form #9745 (1.7.4899)~~
New regression from https://github.com/PCSX2/pcsx2/pull/10923

### Reproduction Steps

run the gs dump provided 

### PCSX2 Revision

v1.7.5603

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu ,  but also happens on windows

### CPU

Intel Xeon E5-1620 v3 (8) @ 3.600GHz

### GPU

NVIDIA Quadro K2200

### Logs & Dumps

~~[broken shuffle effect.zip](https://github.com/PCSX2/pcsx2/files/14547898/broken.shuffle.effect.zip)~~
[Superman.gs.zip](https://github.com/PCSX2/pcsx2/files/14676169/Superman.gs.zip)

**Comment by lightningterror** [comment]
Re opening as there's a new regression.
