### ISSUE TITLE
[BUG]: Automatic mapping my X-Plorer wired Xbox 360 guitar controller

### ISSUE THREAD

**Issue by Gagert** [PCSX2/pcsx2#10905]
### Describe the Bug

When auto-mapping my X-Plorer wired guitar controller with PCSX2, a couple of inputs that are auto-mapped are wrong. Here's what the auto-mapper configured:

![Guitar Auto mapped](https://github.com/PCSX2/pcsx2/assets/8365446/2c5d93d1-ae47-46eb-abc9-e2461de4494c)

Here's what the inputs are like when manually configuring each of the buttons for the X-Plorer controller:

![Guitar Hero user mapping](https://github.com/PCSX2/pcsx2/assets/8365446/080cd159-75b3-41c9-89fa-247fd212eda4)

The global settings I've used for my controllers on this profile:

![Guitar auto mapped settings](https://github.com/PCSX2/pcsx2/assets/8365446/182f581c-aa3f-41a0-a2cf-68355691d86a)

(I can't get the tilt-function to work by moving the X-Plorer controller in any direction regardless of mappings, seen in Issue #10906).

### Reproduction Steps

Use a wired X-Plorer Xbox 360 guitar controller, and use PCSX2. I suppose I have the required reproduction steps listed above more or less.

### PCSX2 Revision

v1.7.5603

### Operating System

Windows 11

### CPU

i7-12700KF

### GPU

GTX 1080 Ti

**Comment by stenzek** [comment]
Sorry, auto-mapping is only guaranteed to work for a "standard" pad-like controller. It's impossible to know what arrangement non-standard controllers are going to have; that's why SDL ships with a controller DB, but again, only handles pads.
