### ISSUE TITLE
[BUG]: Recording in macOS produced broken video

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#10919]
### Describe the Bug

Starting a Video Capture on macOS will results in a glitchy video with purple strips on them.

Bisected to v1.7.5374 (#10506)

Here is the video example:

https://github.com/PCSX2/pcsx2/assets/14798312/6d03b006-2fd8-4d5f-b543-4a88887ee3d0

### Reproduction Steps

1. Fire up a game or start the BIOS.
2. Start a video recording, wait for a few seconds then stop it.
3. Observe the resulting video.

### Expected Behavior

The recording produces normal video.

### PCSX2 Revision

v1.7.5608

### Operating System

macOS 13 (Ventura)

**Comment by TellowKrinkle** [comment]
This appears to be fixed by #10986 / v1.7.5682

**Comment by stenzek** [comment]
Guessing it was `--disable-x86asm` that broke it then.

Which is kinda annoying, since it means you have to install nasm to build deps, even if you're on Apple Silicon.

**Comment by TellowKrinkle** [comment]
Well they did warn us that it would get us a crippled build, guess it was more crippled than we expected.

#11078 adds an option to not build ffmpeg to the CI script so as long as you don't need recording support, you can use that to avoid needing nasm
