### ISSUE TITLE
[BUG]: Open Debugger causes the lock on icon to disappear from the screen in Kingdom Hearts: Re:Chain of Memories (SLUS-21799_A287DF74)

### ISSUE THREAD

**Issue by rpcs2** [PCSX2/pcsx2#10925]
### Describe the Bug

I can see the lock on icon on the screen in Kingdom Hearts: Re:Chain of Memories (SLUS-21799_A287DF74) before I open the debugger but after I open the debugger I no longer can see the lock on icon on the screen anymore.

Additionally I don't see the green triangle icon on the screen too when I need to press it to unlock and open a door or to advance a sleight in game after opening the debugger but before opening the debugger I do see the green triangle icon on the screen too.

### Reproduction Steps

1. Boot Kingdom Hearts: Re:Chain of Memories (SLUS-21799_A287DF74)
2. Begin new game and lock on any enemy target and notice the blue circle that appears on the locked on enemy target.
3. Open the debugger and minimize the debugger window.
4. Return to the game to see that the blue circle (lock on icon) has been disappeared.

### Expected Behavior

I expect to keep seeing the lock on (blue circle) and the green triangle icons after opening the debugger.

### PCSX2 Revision

v1.7.5607.0

### Operating System

Windows 11

### CPU

Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 6 Logical Processor(s)

### GPU

GTX 950

### GS Settings

Please note that PCSX2 is **not** in PSX mode because this issue about a PlayStation 2 game, not a PSX game, so this game cannot be played in PSX mode.

Also note that I am playing this game at a native resolution which means that upscaling is disabled.

I also disabled all cheats and patches including all the widescreen and no-interlace patches too.

I know that using the "Assemble new instruction(s)" feature, the memory editor, register editing and etc of the debugger wrong can cause issues in game that aren't exist without the debugger but all what I did is just to open the debugger and then minimize it's window which means that I did not do any "Assemble new instruction(s)", memory and register edit and etc so no issue should be created but if there is still new issues this means that the function that opens the debugger causes new issues in game that weren't before.

I know that the solution to this issue is to not open the debugger at all but this is not a solution for me because I am not playing games without any cheats and patches that I want or need.

And I need this amazing debugger to make my own cheats and patches because with this debugger I can make cheats and patches that cannot be found in the internet and I will never request cheats and patches from others.

I already know how to use this amazing debugger to make my own cheats and patches and I have already made a lot of cheats and patches to this game that make this game much easier and fun to play, at least for me, and I won't quit using this amazing debugger just because of this issue.

A meantime workaround to this issue until this issue is resolved is I can restart and use PCSX2 until the next time I need or want to use this amazing debugger again when I want or need more new cheats or patches for the current game that I am playing.

Except this issue PCSX2 seems perfect for me and well done.

**Comment by stenzek** [comment]
Either user error, or some race condition caused by the debugger<->core interaction. If the latter, there's tons of them, and it would require significant refactoring to eliminate completely.

Also, repeatedly making alts is lame, we can spot you a mile away.
