### ISSUE TITLE
If AutoDock is enabled(it is by default)moving the main window moves the console too(even if it's maximized)

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1092]
Maximize the console and try moving the main window while AutoDock is enabled

Also if you close pcsx2 while the console is maximized,the next time you start pcsx2,the console will still be with the maximized size(w1936, h1066)but not maximized and moved next to the main window which let's say you placed at the far right side of the screen.

**Comment by willkuer** [comment]
Are you talking about dualscreen setups? I think i never tried it but on a single monitor i guess i cannot maximize the console window and still see the main window. (?)

**Comment by ssakash** [comment]
willkuer: you can still close it using the taskbar.

@vsub : I guess the fix would be to not record the width , height values of the log windows when it's maximized ?

**Comment by willkuer** [comment]
It was more about the first part: moving the main window while the console is maximized.

For the second part I would rather guess that vsub wants to save the maximized window state on shutdown.

**Comment by vsub** [comment]
@willkuer 
> It was more about the first part: moving the main window while the console is maximized.

What do you mean you can't...just maximize the console,click on the main window taskbar button and move the window.

@ssakash the best solution would be to remember that the window was maximized and don't or/and don't save window size and position while exiting pcsx2 if the window is maximized.
Personally when I want to also see the console,I maximize it and bring the game window over it.

If the console is maximized,autodock is enabled and you try to move the main window,the console window will be moved to the left side of the main window,the maximized state(the button)will still stay and also the size will also be at the maximized size making the window kinda useless that way because he becomes too big for something that is not maximized

**Comment by ssakash** [comment]
@vsub 

There was a fix pushed for this, are you satisfied with the current handling of the console window size ?

**Comment by vsub** [comment]
Not really:
1.If the console is maximized while closing pcsx2,the text time you start pcsx2,it will at the same not maximized size but the position will always be at  x-8,  y-8(this is the maximized position)

2.If AutoDock is enabled(I don't use it but still,this behavior is wrong),moving the main window also moves the console even if it's maximized(the console keep the maximized status but the size is the size of the not maximized).

The only difference between now and before is that now the size is not saved while closing pcsx2 if the console is maximized but the position still is.(the position of the maximized window...like before)

**Comment by turtleli** [comment]
I commited some fixes - is the behaviour better?

**Comment by vsub** [comment]
Yes,that's better,thanks.
Case closed
