### ISSUE TITLE
[BUG]: NBA ShootOut series HW mode issues

### ISSUE THREAD

**Issue by Wdub888** [PCSX2/pcsx2#10934]
### Describe the Bug

There are some bugs that aren't presents in software mode.
I tested 2 games of Sony's exclusive NBA games NBA ShootOut 2001 & NBA ShootOut 2003 and I think this issues are present in 2004 version as well.

2003 version in Vulkan mode has some issues like this (I tested in practice mode).
first black and white and overall different jersey, shorts and skin color when MipMapping is on Auto:
![NBA Shootout 2003_SCUS-97217_20240315235147](https://github.com/PCSX2/pcsx2/assets/121665302/f9a15dcf-6f52-47e2-9ca2-d76646ce2959)

in software mode this issues aren't present:
![NBA Shootout 2003_SCUS-97217_20240315235246](https://github.com/PCSX2/pcsx2/assets/121665302/49296e40-73ee-463e-bcf1-1ead68d5f7ee)

after putting mipmapping on basic or full shorts textures gets better but there are some flickering mainly on hands (for an example y'all can see Derek Fisher left hand):
![NBA Shootout 2003_SCUS-97217_20240315235427](https://github.com/PCSX2/pcsx2/assets/121665302/e3db4381-7630-4f8a-82a8-b5272511d5b7)

also in HW mode in this pictures even after enabling Mipmapping settings the court Lines are Jagged and it isn't so colorful as well.
Also there is some little shadow or reflection [idk :)] that is present in software mode but can't be seen in HW mode.
![NBA Shootout 2003_SCUS-97217_20240315235246 1](https://github.com/PCSX2/pcsx2/assets/121665302/69a4b904-aa13-40de-9ea9-3232c8688a13)

but it can be fixed with blending accuracy on Maximum:
![NBA Shootout 2003_SCUS-97217_20240315235706](https://github.com/PCSX2/pcsx2/assets/121665302/3c9da408-09c2-4e11-a87c-a88f1d5ac487)

I think it was worth the mention.

about 2001 version same texture issues are present:
![NBA ShootOut 2001_SCUS-97114_20240316000104](https://github.com/PCSX2/pcsx2/assets/121665302/ddf371cb-9bc3-43e3-884e-c7556eb45de2)

software mode:
![NBA ShootOut 2001_SCUS-97114_20240316000136](https://github.com/PCSX2/pcsx2/assets/121665302/b249f4b3-f8cc-42c0-b268-cca8d3a15e52)

but after enabling MipMapping it can be fixed and there aren't any skin and hands issues like 2003:
![NBA ShootOut 2001_SCUS-97114_20240316000202](https://github.com/PCSX2/pcsx2/assets/121665302/979f26ea-ce41-45ce-9445-2e2972485b04)

also I think that text in the court floor staples center is more blurry in HW mode.

### Reproduction Steps

Vulkan mode & after that switch on Software mode (in 2003 practice court is a good place to check this issues)

### Expected Behavior

Fixing texture and mipmapping issues.
fixing jagged lines in court and also make it more colorful and accurate to software mode.
fixing text or some textures in court (I don't know it's present in other courts)

### PCSX2 Revision

v1.7.5617

### Operating System

Windows 10 (64bit)

### CPU

Intel i5-1035g1

### GPU

Nvidia GeForce MX130

### Logs & Dumps

GSdump
[NBA Shootout 2003_SCUS-97217_20240315235129.gs.zip](https://github.com/PCSX2/pcsx2/files/14620758/NBA.Shootout.2003_SCUS-97217_20240315235129.gs.zip)

**Comment by bigol83** [comment]
So these are highly experimental settings but to match hardware renderer with software you can use 

Mipmapping Full
Trilinear Filtering Trilinear (Ps2)
Blending Accuracy Maximum

and then Manual Hardware Renderer Fixes
CPU Sprite Render Size at 8 with Blended Sprite/Triangles

These settings can really slow down emulation (especially with that GPU) and can cause some other graphics issues. 

But i thought it would be useful to point them out so you can test them. @Wdub888

**Comment by Wdub888** [comment]
> So these are highly experimental settings but to match hardware renderer with software you can use
> 
> Mipmapping Full Trilinear Filtering Trilinear (Ps2) Blending Accuracy Maximum
> 
> and then Manual Hardware Renderer Fixes CPU Sprite Render Size at 8 with Blended Sprite/Triangles
> 
> These settings can really slow down emulation (especially with that GPU) and can cause some other graphics issues.
> 
> But i thought it would be useful to point them out so you can test them. @Wdub888

performence is actually solid (28-30fps) 3x Upscaling. thanks.
