### ISSUE TITLE
[BUG]: Log Window can be closed from Windows Taskbar and UI thinks it's still enabled

### ISSUE THREAD

**Issue by sestain** [PCSX2/pcsx2#10939]
### Describe the Bug

Log Window has close button disabled on the window itself but on the taskbar it's still clickable which doesn't update the UI option.

https://github.com/PCSX2/pcsx2/assets/35299377/fb58a606-0b42-4a48-8089-27c223037f2f

### Reproduction Steps

1. Enable Log Window
2. Close Log Window through Taskbar
3. "Tools" dropdown (Shows Log Window being enabled when it's not)

### Expected Behavior

Disable the ability to close the Log Window through Taskbar (not sure if this is even possible) or update the condition accordingly.

### PCSX2 Revision

v1.7.5618

### Operating System

Windows 11

**Comment by stenzek** [comment]
You're not meant to be able to close the window via the taskbar. You can't differentiate between a user-initiated close request, and the application being forced to exit, hence why I disabled the close button in the first place.
