### ISSUE TITLE
[Feature Request]: Auto Start in Big Picture Mode

### ISSUE THREAD

**Issue by devmaars** [PCSX2/pcsx2#10938]
### Description

A setting that enable big picture mod automatically when the emulator is opened, should fit well in the "behavior section"
![image](https://github.com/PCSX2/pcsx2/assets/163019521/b5e9cbe7-7e60-4826-bba6-659be76d5f07)

### Reason

As someone who prefer big picture mod and i think there are many like me.
currently to enter big picture mod you have to manually click "System -> Start Big picture Mod" and this setting is not saved so you have to do it every time you open the emulator.
![image](https://github.com/PCSX2/pcsx2/assets/163019521/45574483-1084-404a-9c68-e56b2e0da115)

### Examples

A perfect example is Steam in the screenshot below
![image](https://github.com/PCSX2/pcsx2/assets/163019521/c17414c5-6860-4929-8cbd-551ad0f41a7f)

**Comment by Mrlinkwii** [comment]
you can already do this  with the cli parameter  https://wiki.pcsx2.net/Command-line_support 

` -bigpicture: Forces PCSX2 to use the Big Picture mode (useful for controller-only and couch play).`

**Comment by stenzek** [comment]
As link said, this already exists via CLI.

We also don't want to encourage users to only use BP mode, since it's missing several features present in the full Qt UI.

**Comment by TheTechnician27** [comment]
Reopening exclusively to mark completed as a formality, as this feature now exists.

**Comment by TheTechnician27** [comment]
Completed now. `Settings` > `Interface` > `Start Big Picture UI`.
