### ISSUE TITLE
Huge speed drop with accurate blending(anything above basic)on ZOE2 this time

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1093]
If accurate blending is set on anything other than Basic,the speed goes(start the new game and exactly when you can move)from 200 to 40.

Fast accurate blending doesn't help at all
The speed difference is very small between modes extent with Ultra

**Comment by gregory38** [comment]
Fast accurate blending accelerate fbmask operation that are enabled at basic level.

The next level enable accurate blending for all sprite operations. It would be slow if the game uses a ton of sprite primitive to do the rendering. A better collision algo migth help to reduce the speed impact. The question is "is it really worth it ?". I.e. are the rendering better with more accurate option.

Anyway, please generate me a gsdump so I can look at it carefully.

**Comment by gregory38** [comment]
@turtleli 
would you like to do some GSdx contribution ?

The idea is to improve GSRendererOGL::PrimitiveOverlap to generate a list of number of consecutive primitives that don't overlap. And then use this information in SendDraw to split the draw call efficiently.
So for example {10, 3, 5} will tell you that you could draw it as
```
barrier();
DrawIndexedPrimitive(start, 10 sprites (20 vertices));
barrier();
DrawIndexedPrimitive(start + 20, 3 sprites (6 vertices));
barrier();
DrawIndexedPrimitive(start + 26, 5 sprites (10 vertices));
```
Current code is dumb, is just split draw call primitive by primitives. With the previous example it would be 18 draws + 18 barriers.

Note: code is quite hot, so code need to be fast as fast it can.

**Comment by turtleli** [comment]
I think I understand the idea. I could probably make an attempt at it, most of the code is already there.

**Comment by gregory38** [comment]
Yes, there are some bad codes ;)

By the way, rintersect and runion requires to have a nice rectangle. I put various if operation but it can surely be done in full sse (min/max/blending). It would be surely faster.

I will advice to keep current code to double-check that you're splits don't have any overlapping. Otherwise it creates strange & subtle graphics corruptions.

**Comment by gregory38** [comment]
If you have some doubt, push a branch and ping me. I will glady give you my feedback ;)

**Comment by vsub** [comment]
gregory38 
> Anyway, please generate me a gsdump so I can look at it carefully.

I never actually done this(I think it was with Shift+F8)
Do I need to only press it or hold it(for how long)and do I need to enable some special settings while creating it?

**Comment by gregory38** [comment]
@vsub 
http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

Settings aren't important.

**Comment by vsub** [comment]
@gregory38 here,change the extension to rar
![gsdx](https://cloud.githubusercontent.com/assets/5032540/12223096/b963f892-b7d6-11e5-8e6b-0a73c4a6c6c7.jpg)

**Comment by gregory38** [comment]
Ok. I confirm there are a couple of nasty draw calls from the log:
```
Type:Perf	ID:2644	Severity:Info	Message:Split single draw in 4991 draw
Type:Perf	ID:2647	Severity:Info	Message:Split single draw in 234 draw
Type:Perf	ID:2656	Severity:Info	Message:Split single draw in 327 draw
```
First one is a killer. Potentially we can disable accurate blending when the number of primitive is above 1000 (it is too slow to be usable anyway).

@turtleli 
If you need some input to see the draw call content. Or to replay dump with extra log info. There are a lots of niceties to help debug,

**Comment by turtleli** [comment]
I took a quick look at the dump. The 4991, 234 and 327 draws can probably be reduced to 693, 62 and 87 draws using the current collision detection algorithm.
```
4991 sprites can be split into 693 draws.
2 sprite draws: 158
3 sprite draws: 217
4 sprite draws: 157
5 sprite draws: 91
6 sprite draws: 35
7 sprite draws: 24
8 sprite draws: 7
9 sprite draws: 2
10 sprite draws: 1
2479 sprite draws: 1

234 sprites can be split into 62 draws.
2 sprite draws: 14
3 sprite draws: 14
4 sprite draws: 18
5 sprite draws: 9
6 sprite draws: 4
7 sprite draws: 1
8 sprite draws: 2

327 sprites can be split into 87 draws.
2 sprite draws: 21
3 sprite draws: 26
4 sprite draws: 13
5 sprite draws: 12
6 sprite draws: 11
7 sprite draws: 3
8 sprite draws: 1
```

So there's some room for improvement.

**Comment by gregory38** [comment]
Ah interesting. 693 seems a bit too much, could be doable on very good CPU. You could check the perf on linux if you set the variable ` linux_replay ` between 2 and 90. (check release build).

I think we can push the behemoth call into a higher level. We could amend this line with something like ` m_vertex.next < 1000`
```
		case ACC_BLEND_SPRITE:          sw_blending |= m_vt.m_primclass == GS_SPRITE_CLASS;
```

**Comment by turtleli** [comment]
> I think we can push the behemoth call into a higher level. We could amend this line with something like m_vertex.next < 1000
> 
>         case ACC_BLEND_SPRITE:          sw_blending |= m_vt.m_primclass == GS_SPRITE_CLASS;

I tested my branch on the dump - frame rate increases from 26.6fps to 52.5fps on my system (i5-4590, quad core 3.3GHz Haswell, NVIDIA GTX970). So yes, something like that will probably be needed. I'll PR soon(ish) so we can get more testing and discussions.

**Comment by gregory38** [comment]
What is your starting point ? (The top one?)

**Comment by turtleli** [comment]
Starting point? I don't understand.

**Comment by gregory38** [comment]
Yes it would interesting to compate basic/medium/high
(Above level are too much. Debug purpose)

**Comment by turtleli** [comment]
Ok, might be fine after all. I tested them all anyway :)

| ACC Blend | Before | After |
| --- | --- | --- |
| Basic | ~170 | ~170 |
| Medium | ~38 | ~137 |
| High | ~38 | ~137 |
| Full | ~38 | ~137 |
| Ultra | 26.5 | 52.6 |

Though perhaps I should test some other draw call intensive games, I can probably find dumps on the forums somewhere.

**Comment by gregory38** [comment]
Did you try the fast fbmask hack? It only impact first level (on some limited situation)

**Comment by turtleli** [comment]
Just tested it - I don't notice any effect, but the fps fluctuate too much at basic for me.

**Comment by turtleli** [comment]
Well, one stupid bug fix later and assuming there aren't any other silly mistakes

| ACC Blend | Before | After |
| --- | --- | --- |
| Basic | ~170 | ~170 |
| Medium/High/Full | ~38 | ~109 |
| Ultra | 26.5 | ~47 |

Still a good improvement. WIll PR initial work tonight so it can get some review/test.

```
1342:Type:Perf	ID:1299	Severity:Info	Message:Split single draw (229 sprites) into 53 draws: consecutive draws(frequency): 2(9) 3(14) 4(11) 5(6) 6(2) 7(7) 8(3) 10(1)
1365:Type:Perf	ID:1329	Severity:Info	Message:Split single draw (276 sprites) into 67 draws: consecutive draws(frequency): 1(1) 2(10) 3(19) 4(12) 5(14) 6(4) 7(3) 8(1) 9(3)
2701:Type:Perf	ID:2644	Severity:Info	Message:Split single draw (4991 sprites) into 1142 draws: consecutive draws(frequency): 1(1) 2(137) 3(258) 4(268) 5(213) 6(142) 7(71) 8(27) 9(15) 10(6) 11(3) 12(1)
2705:Type:Perf	ID:2647	Severity:Info	Message:Split single draw (234 sprites) into 56 draws: consecutive draws(frequency): 2(9) 3(18) 4(13) 5(5) 6(1) 7(5) 8(3) 9(1) 11(1)
2715:Type:Perf	ID:2656	Severity:Info	Message:Split single draw (327 sprites) into 77 draws: consecutive draws(frequency): 2(11) 3(17) 4(20) 5(14) 6(6) 7(5) 8(3) 9(1)
4049:Type:Perf	ID:3971	Severity:Info	Message:Split single draw (4997 sprites) into 1152 draws: consecutive draws(frequency): 1(1) 2(138) 3(279) 4(266) 5(212) 6(129) 7(71) 8(32) 9(14) 10(5) 11(4) 12(1)
4053:Type:Perf	ID:3974	Severity:Info	Message:Split single draw (174 sprites) into 42 draws: consecutive draws(frequency): 2(9) 3(8) 4(12) 5(3) 6(5) 7(3) 8(1) 10(1)
4070:Type:Perf	ID:3995	Severity:Info	Message:Split single draw (394 sprites) into 93 draws: consecutive draws(frequency): 2(18) 3(21) 4(20) 5(12) 6(8) 7(8) 8(3) 9(3)
5405:Type:Perf	ID:5310	Severity:Info	Message:Split single draw (4934 sprites) into 1144 draws: consecutive draws(frequency): 1(2) 2(138) 3(279) 4(277) 5(205) 6(122) 7(65) 8(29) 9(14) 10(7) 11(2) 12(3) 13(1)
5409:Type:Perf	ID:5313	Severity:Info	Message:Split single draw (180 sprites) into 38 draws: consecutive draws(frequency): 2(5) 3(7) 4(10) 5(3) 6(2) 7(8) 8(2) 10(1)
5432:Type:Perf	ID:5343	Severity:Info	Message:Split single draw (396 sprites) into 97 draws: consecutive draws(frequency): 2(17) 3(24) 4(27) 5(8) 6(11) 7(7) 8(1) 9(1) 10(1)
```

**Comment by gregory38** [comment]
Not bad. It would really help to reduce the cost of the basic/medium level.

I need to check a gs dump that uses a lots of small sprite to do a full screen effect. It will be the maximum to trigger accurate blending in the medium level.

**Comment by turtleli** [comment]
@vsub PR was merged. Has the speed improved? Can this issue be closed?

**Comment by vsub** [comment]
If those results are expected\normal(using native res),then it's fixed

None - ~190
Basic - ~180
Medium/High/Full - ~130
Ultra - ~55

**Comment by ssakash** [comment]
@vsub

comparison between the older build (before this commit was added) would be nice.

**Comment by vsub** [comment]
By "older build" you mean some specific build or any 1.1.1 build.
If it's the second,it was like I posted in the first post...anything above basic was reducing the speed to 40fps and below.

If you need the results from some specific build,then I'll try it when I get home,just tell me which one

**Comment by ssakash** [comment]
>By "older build" you mean some specific build or any 1.1.1 build.

 By older build I meant the version before the merge of #1115 .  try this [build](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-87-g38c5488&platform=windows-x86).

just to compare the improvement in the speed :)

**Comment by gregory38** [comment]
@vsub 
Could you compare at 2x/3x. Because I'm sure you don't play at native. We can change a bit the code but 130 seems fine from a performance of view. What is your opinion?

**Comment by vsub** [comment]
3x Native,TF(Bilinear),AF(16x),CRC(Partual),Hardware Depth\Accurate Date off

v1.5.0-dev-87-g38c5488
None\Basic - 135
Medium\High\Full - 35
Ultra - 25

v1.5.0-dev-93-g254081e
None/Basic - 135
Medium\High\Full - 75
Ultra - 42

It seems to be the same...I lose the same speed while using the fixed build compared to the same build but at Native(the result is similar to turtleli)

60fps loss seems too much but that's my opinion and if I don't see an improvement worth the big fps loss,I'll probably not use the option(that's what I do for everything,not just pcsx2)

Btw I have the PAL version of the game
If those are the expected results,then ok,case closed

**Comment by gregory38** [comment]
@vsub what is your cpu?

**Comment by vsub** [comment]
i7 4771 at 3.5(3.7-3.9 with turbo),GTX750TI,16GB RAM

**Comment by gregory38** [comment]
I think we need to disable the effect when there are too many polygons. The idea was to catch postprocesing effect. It isn't the case here.

So we need to test somethings like that. I set the 200 but 100 migth be more than enough.
```
diff --git a/plugins/GSdx/GSRendererOGL.cpp b/plugins/GSdx/GSRendererOGL.cpp
index 494ed32..feb4e3c 100644
--- a/plugins/GSdx/GSRendererOGL.cpp
+++ b/plugins/GSdx/GSRendererOGL.cpp
@@ -389,7 +389,7 @@ bool GSRendererOGL::EmulateBlending(GSDeviceOGL::PSSelector& ps_sel, bool DATE_G
                                                                                sw_blending |= (ALPHA.A != ALPHA.B) &&
                                                                                                ((ALPHA.C == 0 && m_vt.m_alpha.max > 128) || (ALPHA.C == 2 && ALPHA.FIX > 128u));
                case ACC_BLEND_CCLIP_DALPHA:    sw_blending |= (ALPHA.C == 1) || (m_env.COLCLAMP.CLAMP == 0);
-               case ACC_BLEND_SPRITE:          sw_blending |= m_vt.m_primclass == GS_SPRITE_CLASS;
+               case ACC_BLEND_SPRITE:          sw_blending |= m_vt.m_primclass == GS_SPRITE_CLASS && m_drawlist.size() < 200;
                case ACC_BLEND_FREE:            sw_blending |= (ps_sel.fbmask  && !m_unsafe_fbmask) || impossible_or_free_blend; // blending is only free when we use slow fbmask
                default:                        sw_blending |= accumulation_blend;
        }
```
