### ISSUE TITLE
Issue with SelectPcsx2Plugins.cmake?

### ISSUE THREAD

**Issue by dieselmachine** [PCSX2/pcsx2#1094]
I was having trouble compiling, specifically the spu2-x plugin was yielding this message:

Skip build of spu2-x: miss some dependencies:check these libraries -> soundtouch (>=1.5), alsa, portaudio (>=1.9), sdl (>=1.2) pcsx2 common libs

I had all the deps installed, so i went rooting around through the cmake files and found this:

if((APPLE AND PORTAUDIO_FOUND AND SOUNDTOUCH_FOUND AND SDLn_FOUND AND common_libs)
    OR (LINUX AND ALSA_FOUND AND PORTAUDIO_FOUND AND SOUNDTOUCH_FOUND AND SDLn_FOUND AND common_libs))

On my machine, the "LINUX" variable wasn't defined, but the variable "Linux" was. After changing the casing, I was able to compile. It's "Linux" everywhere else in that file, so I'm thinking it's a typo?

**Comment by gregory38** [comment]
Thanks for the info. Yes, recent OSx change.
