### ISSUE TITLE
Terminator 3 Redemption[BUG]: 

### ISSUE THREAD

**Issue by marcelooutbreak** [PCSX2/pcsx2#10947]
### Describe the Bug

Hello my developer friends, the game Terminator 3 Redemption has a graphics bug, can you solve it?

### Reproduction Steps

The game is giving a graphical error only in this part.

### Expected Behavior

This part was supposed to be in first person.

### PCSX2 Revision

1.7.5617

### Operating System

Windows 10 (64bit)

### Logs & Dumps

![Terminator 3 - The Redemption_SLES-52283_20240319195813](https://github.com/PCSX2/pcsx2/assets/164095230/ae590714-165c-4929-b470-610d56287d60)
![Terminator 3 - The Redemption_SLES-52283_20240319195818](https://github.com/PCSX2/pcsx2/assets/164095230/eec867f8-d6ca-4187-9d8f-6a54c6a7249c)
![Terminator 3 - The Redemption_SLES-52283_20240319195825](https://github.com/PCSX2/pcsx2/assets/164095230/be5e7f0c-e4e8-4d60-ba3f-58154b747b67)
![Terminator 3 - The Redemption_SLES-52283_20240319195829](https://github.com/PCSX2/pcsx2/assets/164095230/b901bcc2-3222-4172-92bc-bfc9d8fbb053)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/14657730/snaps.zip)

**Comment by lightningterror** [comment]
Game needs Autoflush on sprites.
