### ISSUE TITLE
[BUG]: MGS3: Subsistence visual glitch when answering radio call

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#10951]
### Describe the Bug

Playing MGS3: Subsistence, you often get and answer radio calls. During this, Snake kneels down and answers the call. During this process, on PCSX2 (hardware mode, not software mode), part of the screen gets cut off. This only happens on Subsistence; it does not happen on Snake Eater, the original version of the game.

### Reproduction Steps

Play Metal Gear Solid 3: Subsistence until right after you retrieve your backpack from the tree. Answer the radio call yourself or let Snake answer it automatically. A large portion of the bottom part of the screen will be blacked out for a short time.

### Expected Behavior

The entire screen should remain visible during this process, both as shown in Snake Eater and as shown in SW mode in Subsistence.

### PCSX2 Revision

v1.7.5584 and v1.7.5625

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

### CPU

Ryzen 7 5800X

### GPU

GTX 1070

### GS Settings

Default (InstantDMAHack both on and off for Subsistence, as I was testing the reason behind a GameDB entry)

### Emulation Settings

Default

### Logs & Dumps

Original Snake Eater GS dump (no issue): [Metal Gear Solid 3 - Snake Eater_SLUS-20915_20240320231910.zip](https://github.com/PCSX2/pcsx2/files/14681754/Metal.Gear.Solid.3.-.Snake.Eater_SLUS-20915_20240320231910.zip)

MGS3 Subsistence dump (issue): [Metal Gear Solid 3 - Subsistence [Disc 1 of 3]_SLUS-21359_20240320231236.zip](https://github.com/PCSX2/pcsx2/files/14681764/Metal.Gear.Solid.3.-.Subsistence.Disc.1.of.3._SLUS-21359_20240320231236.zip)

**Comment by RedDevilus** [comment]
[HWandSWDrawsMGS3.zip](https://github.com/PCSX2/pcsx2/files/14681790/HWandSWDrawsMGS3.zip)

**Comment by TheTechnician27** [comment]
Binary search confirms this was broken by #10670. I have no idea why this is present in Subsistence but not Snake Eater, but nonetheless it is a regression.

**Comment by refractionpcsx2** [comment]
If it hits that pr , it usually means something underlying that the old code was hiding

**Comment by bigol83** [comment]
> Binary search confirms this was broken by #10670. I have no idea why this is present in Subsistence but not Snake Eater, but nonetheless it is a regression.

It actually happens in MGS3 Snake Eater too 

Master 

![Metal Gear Solid 3 - Snake Eater_SLES-82024_20240322000144](https://github.com/PCSX2/pcsx2/assets/38129260/d57331ea-446e-44c5-9191-a4fb26fcac4a)

**Comment by TheTechnician27** [comment]
> > Binary search confirms this was broken by #10670. I have no idea why this is present in Subsistence but not Snake Eater, but nonetheless it is a regression.
> 
> It actually happens in MGS3 Snake Eater too

That's... Huh. I tried replicating it on my own copy of Snake Eater, and it passed with flying colors. @bigol83, are you playing on NTSC-U?

**Comment by bigol83** [comment]
I'm playing PAL version of Snake Eater

**Comment by TheTechnician27** [comment]
> I'm playing PAL version of Snake Eater

That could be it. I'm on NTSC-U. At the very least, it should be fixed now in ref's new PR.
