### ISSUE TITLE
[SPU2-X] Sound problems with SDL Audio and Linux

### ISSUE THREAD

**Issue by zaps166** [PCSX2/pcsx2#1095]
I'm using Arch/Manjaro Linux with SDL 2.0.4, PCSX2 1.4.0 and PulseAudio. There are problems with the SDL Audio:
- SDL API: alsa - sound plays good, but the CPU usage by pcsx2 process is very high,
- SDL API: pulseaudio - CPU usage is normal, but the sound is crackling.

It doesn't depend on any game, it happens also in PS2 BIOS.

I tried other 32-bit game which uses SDL 2.0.4 and sound over pulseaudio works fine, but as I remember in SDL 2.0.3 works fine (but I'm not 100% sure).

Card: HDA Intel PCH
Chip: Realtek ALC892
PulseAudio 7.1, Samplerate: 48000Hz, Resampler: speex-float-3

**Comment by gregory38** [comment]
http://forums.pcsx2.net/Thread-Sound-problems-with-SDL-Audio

**Comment by zaps166** [comment]
Ok, thanks. I thought if NFSIISE works correctly on SDL 2.0.4, so it is pcsx2 bug.

**Comment by gregory38** [comment]
Well it could still be a PCSX2 bug that used to work by chance. Besides from PCSX2 point of view, Alsa/Pulseaudio are exactly the same, there are backend of SDL. So yes, so far I will lean toward SDL regression.

**Comment by gregory38** [comment]
I updated spu2x code to avoid the SDL issue. So you need to get either a more recent SPU2X or SDL2.0.3.

**Comment by zaps166** [comment]
Works properly, thanks!
I reviewed the code now. I don't think it is a bug in SDL2 (but I didn't test it).

```
int SDL_OpenAudio(SDL_AudioSpec* desired, SDL_AudioSpec* obtained)

This function opens the audio device with the desired parameters, and returns 0 if successful, placing the actual hardware parameters in the structure pointed to by obtained. 
```

```
if (SDL_OpenAudio(&spec, NULL) < 0) {
```
You pass "&spec" as first argument and NULL as second which should return proper buffer size.

```
if(samples != spec.samples) {
    ...
    samples = spec.samples;
}
```
It the code above you get the samples from data which you pass to SDL2. The SDL2 (should, but I didn't test it) returns obtained data in second parameter.

```
buffer = std::unique_ptr<StereoOut_SDL[]>(new StereoOut_SDL[spec.samples]);
```
can be simplified to:
```
buffer.reset(new StereoOut_SDL[spec.samples]);
```

Please correct me if I'm wrong.

**Comment by gregory38** [comment]
(Note: not my code)

https://wiki.libsdl.org/SDL_OpenAudio

```
If obtained is NULL, the audio data passed to the callback function will be guaranteed to be in the requested format, and will be automatically converted to the actual hardware audio format if necessary. If obtained is NULL, desired will have fields modified. 
```

**Comment by gregory38** [comment]
But the SDL code doesn't do that. So I will change PCSX2 code.

**Comment by zaps166** [comment]
Ah, OK, right.
I wrote something in SDL2 Audio more than a year ago, so I don't remember, but I think that was also problems with buffer size on SDL 2.0.3 (and 1.2.x?) and ALSA/dmix. It is better to rely only on buffer size passed to callback (just like your recent patch) to avoid problems on custom ALSA configuration...

**Comment by gregory38** [comment]
Hum, found this in the SDL_code. So yes if obtained is null. It will replace value in desired.
```
    if (obtained) {
        id = open_audio_device(NULL, 0, desired, obtained,
                               SDL_AUDIO_ALLOW_ANY_CHANGE, 1);
    } else {
        id = open_audio_device(NULL, 0, desired, desired, 0, 1);
    }

```

**Comment by zaps166** [comment]
```
#include <SDL2/SDL.h>
#include <iostream>

using namespace std;

int main()
{
    if (SDL_Init(SDL_INIT_EVERYTHING))
        return -1;

    SDL_AudioSpec spec, obtained;
    memset(&spec, 0, sizeof spec);
    memset(&obtained, 0, sizeof obtained);

    spec.freq = 44100;
    spec.format = AUDIO_S16SYS;
    spec.channels = 2;
    spec.samples = 2048;

    if (SDL_OpenAudio(&spec, &obtained))
        return -2;

    cerr << spec.samples << ' ' << obtained.samples << endl;

    return 0;
}
```
Console output:
```
2048 1024
```




```
#include <SDL2/SDL.h>
#include <iostream>

using namespace std;

int main()
{
    if (SDL_Init(SDL_INIT_EVERYTHING))
        return -1;

    SDL_AudioSpec spec;
    memset(&spec, 0, sizeof spec);

    spec.freq = 44100;
    spec.format = AUDIO_S16SYS;
    spec.channels = 2;
    spec.samples = 2048;

    if (SDL_OpenAudio(&spec, NULL))
        return -2;

    cerr << spec.samples << endl;

    return 0;
}
```
Console output:
```
2048
```


So it doesn't change the value in desired... I don't understand the docs:
```
If obtained is NULL, the audio data passed to the callback function will be guaranteed to be in the requested format, and will be automatically converted to the actual hardware audio format if necessary. If obtained is NULL, desired will have fields modified.
```
So it doesn't guarantee, because it just doesn't work properly and it doesn't change desired if obtained is NULL...

**Comment by gregory38** [comment]
Was is tested on SDL 2.0.4 or a previous version. I only have the 2.0.2 code in local. Maybe they change the behavior.

**Comment by zaps166** [comment]
I tested on 2.0.4. I can also compile 2.0.3 and 2.0.2 for test. Maybe 2.0.4 changed only the default buffer size, but bug with obtained/desired existed long before?

Could you try on your local these two programs with different buffer sizes?

**Comment by gregory38** [comment]
build command? (yes I'm lazy)

**Comment by zaps166** [comment]
```
g++ -O2 file.cpp -lSDL2 -o file && ./file
```

**Comment by gregory38** [comment]
g++ sdl2.c -o sdl2 -lSDL2
15:10 gregory /tmp % ./sdl2                   
zsh: exit 254   ./sdl2
15:10 gregory /tmp %

**Comment by zaps166** [comment]
you have error here:
```
if (SDL_OpenAudio(&spec, NULL))
```

So probably the spec is incorrect for SDL2.0.2 (lack of callback doesn't work in 2.0.2?)

**Comment by zaps166** [comment]
```
static void audioCallback(void *userdata, Uint8 *stream, int len) {}
```
and for spec:
```
spec.callback = audioCallback;
```

**Comment by gregory38** [comment]
```
./sdl1 
2048 940
```
```
 ./sdl2 
940

```

**Comment by zaps166** [comment]
about SDL2 code:
```
    if (obtained) {
        id = open_audio_device(NULL, 0, desired, obtained,
                               SDL_AUDIO_ALLOW_ANY_CHANGE, 1);
    } else {
        id = open_audio_device(NULL, 0, desired, desired, 0, 1);
    }
```

I don't see SDL_AUDIO_ALLOW_ANY_CHANGE when obtained is NULL, maybe this is a problem?

And from 2.0.4:
```
id = open_audio_device(NULL, 0, desired, NULL, 0, 1);
```
I can't see desired in fifth argument... And in 2.0.4 I can't see any line to replace desired when obtained is NULL.

So the SDL documentation is wrong for me

**Comment by zaps166** [comment]
Ok, so the sizes are different...

**Comment by gregory38** [comment]
Normally  SDL_AUDIO_ALLOW_ANY_CHANGE doesn't have any impact. It tells SDL that it must provide what it is requested.
Do you have this code in open_audio_device or did they add some condition.
``` 
    /* If the audio driver changes the buffer size, accept it.
       This needs to be done after the format is modified above,
       otherwise it might not have the correct buffer size.
     */
    if (device->spec.samples != obtained->samples) {
        obtained->samples = device->spec.samples;
        SDL_CalculateAudioSpec(obtained);
    }
```

**Comment by zaps166** [comment]
Yes, OK, in our case it seems to be working properly.

So the bug (probably) is (2.0.4):
```
id = open_audio_device(NULL, 0, desired, NULL, 0, 1);
```
and 2.0.3:
```
id = open_audio_device(NULL, 0, desired, desired, 0, 1);
```

So it is better to use obtained in PCSX2, because 2.0.4 has a bug...

**Comment by gregory38** [comment]
Ah yes that the issue. It doesn't report the modification anymore because of the NULL pointer.

**Comment by zaps166** [comment]
The SDL2 doc webpage is obsolete. It differs from SDL 2.0.4 and SDL 2.0.3 doc in header file.

I can't see "If obtained is NULL, desired will have fields modified" in header file even in SDL 2.0.3.

"the audio data passed to the callback function will be guaranteed to be in the requested format, and will be automatically converted to the hardware audio format if necessary" - this doesn't work properly...

So it is better to use obtained as a second argument...

**Comment by gregory38** [comment]
No matter what the doc says. API behavior mustn't change between minor release.

```
So it is better to use obtained as a second argument...
```
Yes. But in this case we need to use the new open function to force SDL to use current config => `SDL_OpenAudioDevice`

Patches are welcomes.

**Comment by zaps166** [comment]
Agree, so someone must report a bug.

I can try to create a proper patch, but not today.

**Comment by gregory38** [comment]
@zaps166 
Read this thread http://forums.pcsx2.net/Thread-Sound-problems-with-SDL-Audio
Which  lead to https://bugzilla.libsdl.org/show_bug.cgi?id=3228

**Comment by zaps166** [comment]
Ok, I missed this thread, thanks
