### ISSUE TITLE
[Feature request] [OnePAD] Gamepad hot-plugging on Linux

### ISSUE THREAD

**Issue by zaps166** [PCSX2/pcsx2#1096]
- run pcsx2,
- connect a gamepad,
- go to OnePAD settings,
- the gamepad is not visible.

**Comment by gregory38** [comment]
Just keep your pad plugged ;)

FWIW, detection of gamepad is done during the init of the plugin. Potentially we can relaunch an auto detection of them in the GUI. But there are more important priority.

**Comment by nhydock** [comment]
Suggestion for this: since PCSX2 has been moving over to SDL2, could OnePad make use of the [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) when compiled with SDL2 support?

**Comment by gregory38** [comment]
SDL1 is still supported for older distribution. It is also required if wx is built against sdl1. Dunno maybe we can drop it now.

**Comment by ac3d912** [comment]
This could (possibly?) address an issue where a wireless gamepad is disconnected, and then reconnected.
e.g. PS3 DualAxis controller using sixad: battery dies; charge it for a bit, plug it in...

Right now: I hope you saved.
OnePad periodically re-polls: Success!

**Comment by noammor** [comment]
This enhancement will enable using PCSX2 with a Steam Controller with Steam Home Streaming, see [here](http://forums.pcsx2.net/Thread-Attempting-to-use-Steam-Home-Streaming-with-PCSX2).

**Comment by FlatOutPS2** [comment]
> This enhancement will enable using PCSX2 with a Steam Controller with Steam Home Streaming

PCSX2 and other PAD plugins already support hot-plugging, so it should work for most people.

**Comment by gregory38** [comment]
Onepad doesn't support hot-plug. If we can drop SDL1, we could upgrade to the game controller API. The new API would help us to support auto-configuration and hot-plugging.

**Comment by gregory38** [comment]
I gave a quick look at the new game controller API which is quite nice
* Allow to automatically setup joystick (like xinput)
* Support new event for hot plugging
* Likely better support of various joystick.

However it would be more difficult to setup the mapping. Potentially it can be done with external tools. (see the list below)
* https://github.com/AntiMicro/antimicro/wiki/Adding-A-New-Game-Controller-Mapping-under-AntiMicro
```
Besides AntiMicro, Steam Big Picture Mode and the Game Controller Map test program
 bundled in the SDL source code (test/controllermap.c) are the only GUI applications for
 creating the raw mapping string. Of those two, Steam Big Picture Mode is the more
 friendly option to use for creating a mapping string; the Game Controller Map test
 program can take a bit of fidling to build. You can check the config.vdf file (config/config.vdf)
 and look for the value of SDL_GamepadBind.
```

**Comment by gregory38** [comment]
Onepad2 supports hot plug.
