### ISSUE TITLE
Daily build PPA version is incorrect

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#1097]
The daily PPA as posted [here] (https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily), and as started by [this] (https://github.com/PCSX2/pcsx2/issues/948) issue, is out of date version-wise (date should be 1.5-something).  

@helkaluin or @gregory38 can you look into this?

Thanks..

**Comment by helkaluin** [comment]
Version changed to 1.5.0 (it's currently defined in the recipe: https://code.launchpad.net/~pcsx2-team/+recipe/pcsx2-github-mirror-daily).

**Comment by gregory38** [comment]
Can't you get it from the source code?
Shell example with some grep.
```
get_pcsx2_version()
{
    local major=`grep -o "VersionHi.*" $LOCAL_REPO/pcsx2/SysForwardDefs.h | grep -o "[0-9]*"`
    local mid=`grep -o "VersionMid.*" $LOCAL_REPO/pcsx2/SysForwardDefs.h | grep -o "[0-9]*"`
    local minor=`grep -o "VersionLo.*" $LOCAL_REPO/pcsx2/SysForwardDefs.h | grep -o "[0-9]*"`
    release=`grep -o "isReleaseVersion.*" $LOCAL_REPO/pcsx2/SysForwardDefs.h | grep -o "[0-9]*"`
    version="$major.$mid.$minor"
}
```

**Comment by helkaluin** [comment]
Unfortunately the Launchpad system can only get its version either directly from the recipe or extracting it from `debian/changelog`.

I'll update the `debian/changelog` on the Launchpad branch if you want, Greogry?

**Comment by i30817** [comment]
Since launchpad will not (ever) allow run() commands on recipes, you can't grep it from source or even repository (outside of the few whitlisted info like commit number / hexdecimal string).

**Comment by Shoegzer** [comment]
I noticed the PPA was updated [here] (https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily), but when I did an "add-apt-repository ppa:pcsx2-team/pcsx2-daily" to add it (I'm on Trusty), I noticed the following version reflected as "Latest Version":

3:1.3.1~git201601072049~ubuntu14.04.1

...so still outdated, apparently.  

Also, I noticed PPA information posted for [the mirror] (https://code.launchpad.net/~pcsx2-team/+recipe/pcsx2-github-mirror-daily) indicates build failure for Trusty.  Any ideas if this is the problem, and if so, what the source of the problem would be?

**Comment by gregory38** [comment]
if you want we can change the changelog in git to have a better default version (if it can help)

**Comment by Shoegzer** [comment]
I think we know now that it's related to build failure on Trusty ;) so whenever you can look into it, would be great.

**Comment by gregory38** [comment]
I don't understand the error. GCC4.8 is working on my machine. Would it be possible to require gcc4.9 in the buld?

**Comment by helkaluin** [comment]
@Shoegzer The version is now correct.  Can you close this?

The Trusty issue is an entirely different thing.  I've reported it here: https://github.com/PCSX2/pcsx2/issues/1106

@gregory38 I'm afraid not.  The toolchain versions are specific to each Ubuntu release.  Trusty uses 4.8.4.

**Comment by Shoegzer** [comment]
@helkaluin Sure - issue closed.  I wasn't able to confirm a proper version specifically but I'm 99% sure it's related to the other issue as you reported.  Thanks for your help.
