### ISSUE TITLE
[BUG]: God of War 1 bad cloud edges in hardware mode

### ISSUE THREAD

**Issue by superblobster** [PCSX2/pcsx2#10973]
### Describe the Bug

The clouds at the beginning of the intro have weird edges (in-engine, not the FMV that is shown immediately after this scene).
This only occurs in hardware and even in native resolution. Does not occur in software.
![God of War_SCUS-97399_20240326151321](https://github.com/PCSX2/pcsx2/assets/60817163/10c6c933-6aa7-47ca-a725-d6cfed1da6c2)

Note: I have a gz.zst dump, but github refuses to allow me to upload it. Reproduction should be easy though as it happens right at the beginning of the game.

### Reproduction Steps

Start a new game with any hardware renderer and look at the clouds behind Kratos.

### Expected Behavior

Clouds should look normal as in software mode:
![God of War_SCUS-97399_20240326151326](https://github.com/PCSX2/pcsx2/assets/60817163/cf74212d-7645-487e-bfac-bf98396ccb98)

### PCSX2 Revision

1.7.5644

### Operating System

Windows 10 (64bit)

### CPU

3570k

### GPU

GTX 1060

### GS Settings

default

### Emulation Settings

default

**Comment by lightningterror** [comment]
You rename the dump to a .zip and upload it.

**Comment by superblobster** [comment]
I did, and it still gives me the message "We don’t support that file type."

**Comment by lightningterror** [comment]
Can you upload it somewhere else and post a link to it then?

**Comment by superblobster** [comment]
https://filebin.net/3b8oecijv5vofhd5/God_of_War_SCUS-97399_20240326155148.gs.zst

**Comment by bigol83** [comment]
Made a video to show how it behaves


https://github.com/PCSX2/pcsx2/assets/38129260/e778b0cd-0458-4b4f-aede-f03a1d82ef1b


Look at the top right clouds

**Comment by superblobster** [comment]
Could this actually be related to #3692 ?

**Comment by stenzek** [comment]
No, it's not Z fighting, it's two pass AFAIL shenanigans. I have a fix in the works.
