### ISSUE TITLE
[BUG]: Ar Tonelico 1 - display broken background texture - hardware mode

### ISSUE THREAD

**Issue by jitingcn** [PCSX2/pcsx2#10979]
### Describe the Bug

Using the default settings and attempting to render scenes in Ar Tonelico with either automatic or any hardware rendering option, I have observed that portions of the background are not displayed correctly; they appear incomplete or truncated. This issue persists consistently across different scenes. Switching from software renderer to automatic or any hardware renderer may also crash PCSX2 .
I have identified this issue introduce at version v1.7.5642 (https://github.com/PCSX2/pcsx2/pull/10966) and persists in the latest version.
![Ar tonelico - Sekai no Owari de Utai Tsuzukeru Shoujo_SLPS-25604_20240327223830](https://github.com/PCSX2/pcsx2/assets/25289725/17863249-8d75-4ad1-92ee-fce4197823f7)

### Reproduction Steps
[at1jp save states.zip](https://github.com/PCSX2/pcsx2/files/14775467/at1jp.save.states.zip)

Load save with default settings, open menu then open the list.

### Expected Behavior

![image](https://github.com/PCSX2/pcsx2/assets/25289725/8b81704b-f825-4839-8c18-0f7db7426c6a)

### PCSX2 Revision

v1.7.5642

### Operating System

Windows 11

### CPU

3700x

### GPU

4070 Ti Super

### Logs & Dumps

[gsdump.zip](https://github.com/PCSX2/pcsx2/files/14775424/Ar.tonelico.-.Sekai.no.Owari.de.Utai.Tsuzukeru.Shoujo_SLPS-25604_20240327223830.zip)
[crashlog.zip](https://github.com/PCSX2/pcsx2/files/14775435/crashlog.zip)

**Comment by lightningterror** [comment]
So we don't forget: Issue is valid rect size is wrong for rta correction, need to figure out why, this seems like an old issue that was previously masked.
