### ISSUE TITLE
[BUG]: Persona 4 - Broken Shadow on Hardware Mode

### ISSUE THREAD

**Issue by Ir-boop** [PCSX2/pcsx2#10975]
### Describe the Bug

Some specific enemy in game has a kinda broken/glitchy shadows when you engage them in battle. I already tried another enemies type almost through the game, however as far as i know only this specific enemy has this issue.

### Reproduction Steps

Engage in battle with Minotaur Iv on Heaven Dungeon (on floor 8-9). Kinda hard tough, since enemies encounter are randomize. Maybe a save state help?

Save states just in case:
[Persona 4 Save states.zip](https://github.com/PCSX2/pcsx2/files/14771008/Persona.4.Save.states.zip)

### Expected Behavior

Shadows should behave like on software mode.

### PCSX2 Revision

v1.7.5645

### Operating System

Windows 11

### CPU

i5-4570

### GPU

GTX 1050

### GS Settings

default

### Emulation Settings

default

### GS Window Screenshots

Hardware:
![broken shadow (hardware)](https://github.com/PCSX2/pcsx2/assets/96909828/579ec1cf-39c4-43e3-8ace-dddd185e862e)

Software:
![normal shadow (software)](https://github.com/PCSX2/pcsx2/assets/96909828/c29e2d07-a411-4e7a-8875-08eddfc0bfad)

### Logs & Dumps

gs dump:
[Persona 4 shadows glitchy.zip](https://github.com/PCSX2/pcsx2/files/14771010/Persona.4.shadows.glitchy.zip)

**Comment by refractionpcsx2** [comment]
Just had a quick look at the dump, and in its current state the hardware renderer wouldn't be happy with that.

```TEST
	ATE:1
	ATST:5
	AREF:6
	AFAIL:3
	DATE:1
	DATM:1
	ZTE:1
	ZTST:2
```
This is the pixel tests it does for that draw, so it's alpha testing the source texture, then alpha testing the destination, then depth testing lol. That's kind of a one two punch kinda deal (we already have a chicken and egg problem with Alpha Test + Z Test)

There's some changes being worked on as we speak which MIGHT help this, so I'll let them know to give it a shot with their changes :)

**Comment by Ir-boop** [comment]
Yeah, thanks for the heads up.

**Comment by Ir-boop** [comment]
Can confirm, #10977 seems to have fixed the issue.
