### ISSUE TITLE
[BUG] [MacOS] Exiting Big Picture mode triggers error.

### ISSUE THREAD

**Issue by Jepl4r** [PCSX2/pcsx2#10995]
### Describe the Bug

Every time I exit Big Picture mode from the X button on the top right, MacOS shows a window that says "PCSX2 has quitted unexpectedly".
It only happens with Big Picture mode.
I'm using a MacBook Pro 2021 14" with an M1Pro.

### Reproduction Steps

Open PCSX2, select Big Picture mode and quit with the X button. It happens in both windowed and fullscreen.

### Expected Behavior

MacOS doesn't show the "PCSX2 has quitted unexpectedly" window.

### PCSX2 Revision

v1.7.5656

### Operating System

macOS 14 (Sonoma)

**Comment by stenzek** [comment]
Please post the crash log.

**Comment by Jepl4r** [comment]
@stenzek Here's the log that comes attached to that window.
[PCSX2 Big Picture MacOS.txt](https://github.com/PCSX2/pcsx2/files/14811516/PCSX2.Big.Picture.MacOS.txt)
