### ISSUE TITLE
[Feature Request]: Animation at Background

### ISSUE THREAD

**Issue by NotAGanesh** [PCSX2/pcsx2#10997]
### Description

**_Dear PCSX2 Team,_**

I hope this message finds you well. First and foremost, I want to express my sincere appreciation for the incredible work you’ve done with the PCSX2 emulator. As a long-time user and enthusiast, I’ve thoroughly enjoyed reliving classic PlayStation 2 games on my PC thanks to your emulator.

Recently, I had the pleasure of using the PPSSPP emulator, which features animated backgrounds. These dynamic backgrounds not only enhance the visual appeal but also create a more immersive experience for users. As someone who appreciates aesthetics and customization, I couldn’t help but wonder if a similar feature could be implemented in PCSX2.

I understand that development priorities are complex, and every feature must be carefully considered. However, I kindly request that you explore the possibility of adding animated backgrounds to PCSX2. Even a subtle animation would go a long way in enhancing the overall user experience.

Thank you for your dedication to this remarkable project, and I look forward to seeing how PCSX2 continues to evolve.

**_Best Regards,
NotAGanesh_**

<hr>

### Reasons:
- Aesthetics and Personalization:
  - Animated backgrounds enhance the visual appeal of the user interface. They make the emulator feel more dynamic and engaging.
  - Users appreciate customization options, and animated backgrounds allow them to personalize their experience. Different animations can cater to various tastes.
 
- Immersive Experience:
   - When you launch an emulator or any application, the initial screen can set the tone for the entire experience. Animated backgrounds create a sense of immersion.
   - For gaming emulators like PCSX2, the background animation can evoke nostalgia or excitement related to the platform (in this case, the PS2).

- Personalization:
   - Customization options are always appreciated by users. Allowing us to choose or even upload our own animated backgrounds would make PCSX2 feel more personalized.

- Technical Showcase:
   - Implementing smooth animations requires skill, and showcasing this feature would demonstrate PCSX2’s capabilities beyond just game emulation.

### Features:
- UI Background Image:
   - You can select an image to use as the background for PCSX2’s menus. This allows you to personalize the emulator’s appearance. Simply choose an image that you like and set it as the backdrop.

### Examples:

example: [https://codepen.io/Priler/details/QpbyGd](url)

**Comment by stenzek** [comment]
Sorry, no, zero interest from any of us on this.

Pull requests are welcome of course, if you would like to implement this yourself.
