### ISSUE TITLE
[Feature Request]: Support for Phantasy Star Universe (PSU) online mode

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#10996]
### Description

This would enhance PCSX2's networking capability to support PSU in its online mode, which is currently not supported according to the [wiki page](https://wiki.pcsx2.net/Phantasy_Star_Universe).  Note that unofficial servers such as [Clementine](https://psu-clementine.net/) exist at least for PC users to continue playing on after the official servers were shut down.

### Reason

It would be nice to be able to play this game online, particularly if could be made possible to play interoperatively with PC users on the Clementine server.  If not, then perhaps a server-side implementation could be developed to support PCSX2 users independently. 

### Examples

Phantasy Star Online (PSO) can be played in online mode with Dolphin, and several unofficial servers even accept players from the Dreamcast, GC/Dolphin, Xbox and PC interoperatively, though of course the technology behind that implementation is entirely different.  Therefore it is understood this feature request may be canceled if this request is deemed infeasible. It is also assumed such a feature would require server-side development as well.

**Comment by refractionpcsx2** [comment]
We aren't in the business of making unofficial servers, that's for others to do, we don't have time for that, it's basically a full time project.

 If the game doesn't work with a custom server designed for PS2, then let us know and we can look in to it.

**Comment by Shoegzer** [comment]
Thanks.  I had assumed by what was written in the wiki that there are limitations within PCSX2 itself that would prevent a server from accepting it: 

> Unfortunately, not working on PCSX2

From what you're saying though, I suppose it's entirely based on the server.  That's good to know at least.

**Comment by RedDevilus** [comment]
Some games beyond needing a custom server need a DNAS patch, which basically DNAS does is point to Sony Servers (which are long dead similarly to GameSpy for PC games) and some hardcode them in so you need to make them to be able to redirect them to a custom server. Atleast that's how I understood the networking to do it's thing.

**Comment by Shoegzer** [comment]
Thanks, and I would imagine that to be especially so if the servers are hardcoded IPs vs. DNS names that can locally resolve to alternate addresses without such a patch.  I'm sure there aren't any DNAS patches for this game though, given there are no custom servers (yet) for the PS2 port.  In time perhaps.

**Comment by AmyRoxwell** [comment]
@Shoegzer Here is an important thing you need to know, it's not that pcsx2 doesn't support the servers, it's that there are no fan-made servers, period, for the ps2 version.
There was some information about it and explanation on their forums from the Clementine Staff of why it didn't worked...but they nuked their forums so sadly I cannot give you a more concrete answer...

**Comment by Shoegzer** [comment]
That is indeed the assumption even though I'll admit that the psu wiki page threw me off, the way it was written.  I wish we knew the real reason there are no unofficial servers for it, it's too bad the forums are gone. I imagine it has something to do with the ps2 server's unique method of maintaining connections and exchanging data that is perhaps unlike the PC version and more difficult to reverse engineer.  That would at least offer some shred of hope for future efforts to preserve the experience as it were.
