### ISSUE TITLE
VirusTotal detected Trojan.Heur!.02052023

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11002]
### Describe the Bug

VirusTotal detected Trojan.Heur!.02052023
https://www.virustotal.com/gui/file/3998fd997a0fc944081d9b4e08b5763a0919dfb16ca6a3939bb77ea42f8ce80a/detection

### Reproduction Steps

N/A

### PCSX2 Revision

v1.7.5659

### Operating System

Windows 11

**Comment by stenzek** [comment]
False positive from a no-name vendor. Both our code and build processes are public and transparent (in this repository), there's no place malware could be added.

Of course it's up to you as a user to decide whether to trust our code, and audit the code if needed.
