### ISSUE TITLE
[BUG]: DreamWorks Bee Movie Game SLES-55016 Textures glitch

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#11004]
### Describe the Bug

When starting a new game and after the first fmv the game looks like the image, both in DX11 and in OpenGL in hardware mode. In Software mode it looks good

### Reproduction Steps

I have tested version 1.7.3790 and it looks good, without errors in the textures, at some point it broke

### PCSX2 Revision

1.7.5659

### Operating System

Windows 11

### CPU

AMD Ryzen 5 5600H

### GPU

AMD Ryzen 5 5600H

### Emulation Settings

Default

### GS Window Screenshots

![DreamWorks Bee Movie Game_SLES-55016_20240331095655](https://github.com/PCSX2/pcsx2/assets/151682118/b606f1c1-8070-41f8-bb9e-cf1c422bef6c)

### Logs & Dumps

[DreamWorks Bee Movie Game_SLES-55016_20240331100615.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/14814611/DreamWorks.Bee.Movie.Game_SLES-55016_20240331100615.gs.zst.zip)

**Comment by Mrlinkwii** [comment]
Can you find when it exactly broke :)

**Comment by TheTechnician27** [comment]
[DreamWorks Bee Movie Game_SLUS-21622_20240331110337.zip](https://github.com/PCSX2/pcsx2/files/14816621/DreamWorks.Bee.Movie.Game_SLUS-21622_20240331110337.zip)

I can't reproduce this in OpenGL on NTSC-U in the latest nightly v1.7.5659. Ryzen 7 5800X, GTX 1070, default settings, Manjaro Flatpak. Attached above is the screenshot (captured while rendering with OpenGL) as well as the GS dump. Time-wise, it's a few frames off from what you captured, but I didn't see any of what you mentioned. Could be a version thing.

**Comment by refractionpcsx2** [comment]
Well I reproduced it, fixing.
