### ISSUE TITLE
[BUG]: GUI, missing information on the status bar.

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11006]
### Describe the Bug

When a game starts, it shows rendering backend, internal resolution etc. on the status bar. If you change rendering backend on the fly, the resolution information is missing.

![pcsx2_001](https://github.com/PCSX2/pcsx2/assets/165537229/d66cd6a8-813a-4a7c-ae1b-5d44328ea8f3)
![pcsx2_002](https://github.com/PCSX2/pcsx2/assets/165537229/020719b8-2b03-44a7-baa6-e76603f5b044)

### Reproduction Steps

Starts a game, change backend while the game is running.

### Expected Behavior

Backend, internal resolution information displayed properly on the status bar.

### PCSX2 Revision

v1.7.5659

### Operating System

Windows 11

**Comment by stenzek** [comment]
The trigger for this is more complex. It's not something users are likely to hit, so I never bothered looking into it.
