### ISSUE TITLE
[BUG]: Super Robot Taisen Z Special Disk, graphic bugs have existed for over a decade

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11001]
### Describe the Bug

Super Robot Taisen Z Special Disk
1. Character's avatar is transparent.
This bug has existed for a decade, if you search it on Google
https://forums.pcsx2.net/Thread-super-robot-taisen-Z-special-disk-transparent-avatar

2. Black spots on the game UI

3. There are spots on the ground

These bugs exist with
D3D11, OpenGL on Windows
Metal on macOS

For Linux,
All of the backends are good without any issues.

Software backends are all good for the 3 platforms.

### Reproduction Steps

1. Character's avatar is transparent: Just play the game, enter a battle with animation playback on.
2. Black spots on the game UI：Select a unit, choose command "Attack", then choose an enemy's unit.
3. Spots on the background: In game on the battle field

### Expected Behavior

1.Character avatar should be opaque.
2.There should be no spots on the UI.

### PCSX2 Revision

v1.7.5659

### Operating System

Windows 11

### CPU

i5-5287U

### GPU

Intel Iris Graphics 6100

### GS Window Screenshots

![Super Robot Taisen Z_SLPS-25887_20240331134504](https://github.com/PCSX2/pcsx2/assets/165537229/529141e2-2b53-42a9-8b24-4256afcd28c2)
![Super Robot Taisen Z_SLPS-25887_20240331134823](https://github.com/PCSX2/pcsx2/assets/165537229/5093885b-b17a-441a-a4eb-cc147295bd83)
![Super Robot Taisen Z_SLPS-25887_20240331134452](https://github.com/PCSX2/pcsx2/assets/165537229/12b61821-5c1c-4252-b559-6e0f5981a763)
![Super Robot Taisen Z_SLPS-25887_20240331134810](https://github.com/PCSX2/pcsx2/assets/165537229/63878f93-b89d-4d0d-9506-b0e78cf82cca)
![Super Robot Taisen Z_SLPS-25887_20240331143610](https://github.com/PCSX2/pcsx2/assets/165537229/5006ea73-1e88-48e8-b0dd-93f8549387c3)

### Logs & Dumps

[Super Robot Taisen Z_SLPS-25887_issue.zip](https://github.com/PCSX2/pcsx2/files/14814334/Super.Robot.Taisen.Z_SLPS-25887_issue.zip)

**Comment by JordanTheToaster** [comment]
1 is only an issue on DX11/12 bellow medium blend it works correctly on basic blend on Vulkan and OpenGL. 2 I cannot reproduce.

**Comment by Bonney01** [comment]
1 is fixed by selecting blending accuracy Medium
2 is fixed by selecting blending accuracy  Maximum
3. But there are spots on the ground even selecting blending accuracy Maximum
![Super Robot Taisen Z_SLPS-25887_20240331143610](https://github.com/PCSX2/pcsx2/assets/165537229/81b92879-75e1-4dce-bb4f-945f34371b1d)
[Super Robot Taisen Z_SLPS-25887_20240331143610.zip](https://github.com/PCSX2/pcsx2/files/14814392/Super.Robot.Taisen.Z_SLPS-25887_20240331143610.zip)

**Comment by JordanTheToaster** [comment]
That also looks okay on my end. I suspect this is just the fact you have a fairly old Intel iGPU.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/5423cf29-ea4b-4d31-b7a3-bf14da0708ef)

**Comment by lightningterror** [comment]
Can't reproduce 3 either, 1, as Jordan mentioned, 2 first pic matches sw renderers.

**Comment by Bonney01** [comment]
@JordanTheToaster
Could you make a test on D3D11?

**Comment by JordanTheToaster** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/80843560/5c477102-e02c-429c-909f-2b5e6b1d5ecc)

**Comment by Bonney01** [comment]
Why the game has no issue on Linux, it's the same CPU.

**Comment by Mrlinkwii** [comment]
Dx11/12 aren't the best at blending ( while it is being improved they lag behind vulkan/opengl etc)

**Comment by stenzek** [comment]
DX11 has no software blending, and Intel's GL drivers are buggy.

We can't denormalize the alpha for this game, because it draws with a vertex alpha of 137, and one of the textures has a max alpha of 127, which modulated is above 128.

Metal is fine on my M2 Pro Macbook, both with fbfetch forced off, and on. So, likely a graphics driver bug also if you have issues. PCSX2 runs on this older hardware, but driver bugs are out of our control.

**Comment by Bonney01** [comment]
> DX11 has no software blending, and Intel's GL drivers are buggy.
> 
> We can't denormalize the alpha for this game, because it draws with a vertex alpha of 137, and one of the textures has a max alpha of 127, which modulated is above 128.
> 
> Metal is fine on my M2 Pro Macbook, both with fbfetch forced off, and on. So, likely a graphics driver bug also if you have issues. PCSX2 runs on this older hardware, but driver bugs are out of our control.

Thanks for the explanation.

I asked ChatGPT, it says PS2 texture's alpha value has a range of 0-2 instead of 0-1.
An alpha value in the range of 0-1 (or 0-127 in 8-bit terms) represents a gradient from transparent to opaque.
An alpha value in the range of 1-2 (or 128-255 in 8-bit terms) doesn’t affect transparency but is used for special effects, such as controlling the intensity of specular highlights or emissive effects.

So an alpha value 137 which exceeds 127 is not an invalid value, but for some special effects instead of transparency.

**Comment by stenzek** [comment]
ChatGPT doesn't know about the intricacies of PS2 hardware. Please don't post generative AI hallucinations here.

Alpha is still 0-255. The range is "doubled" solely as a side effect of the blend equation, `((A - B) * C + D) >> 7`, which causes it to be divided by 128, rather than 256.
