### ISSUE TITLE
Log incorrectly states why .DLL files with unsupported CPU instructions don't load

### ISSUE THREAD

**Issue by vgturtle127** [PCSX2/pcsx2#1101]
My CPU doesn't support AVX or AVX2, and when I start I get:

Path: C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX.dll
File is not a valid dynamic library.
Some kinda plugin failure: C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX.dll
[wx] Failed to load shared library 'C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX.dll' (error 1114: a dynamic link library (DLL) initialization routine failed.)
Path: C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX2.dll
File is not a valid dynamic library.
[wx] Failed to load shared library 'C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX2.dll' (error 1114: a dynamic link library (DLL) initialization routine failed.)
Some kinda plugin failure: C:\Users\Turtle\Downloads\PS2\pcsx2\plugins\GSdx32-AVX2.dll

It should say that the .DLL file/plugin has unsupported CPU instructions, not that it isn't a valid dynamic library or that initialization failed.

I'm not sure if you guys were aware of this, or if you were just focused on other, less cosmetic things, but I thought I would mention it.

We can discuss how to fix it in this issue, if need be.

Thanks for listening! :smile:

**Comment by vsub** [comment]
If you ask me,I think the best solution would be to not display them at all in the console or in the GS drop down list if the cpu don't support them.

Seeing all those errors don't look nice.
The other solution would be to delete them from the plugins folder

**Comment by gregory38** [comment]
Error isn't generated by us but the library (wx). The error appears because it fails to relocate the symbol (ie initialize the library). There isn't any flags on the library that tell you the ISA so you can't report this kind of error.

**Comment by willkuer** [comment]
One couls ommit the error in release mode.

**Comment by vgturtle127** [comment]
@gregory38 I had a feeling wxWidgets was responsible. :smile:

**Comment by turtleli** [comment]
Those messages come from Windows, wxWidgets just passes it along. Though the "some kinda plugin failure" and "File is not a valid dynamic library" messages could probably be removed since they're useless (wxWidgets passes along better error messages for both Windows and Linux anyway).

**Comment by vgturtle127** [comment]
@turtleli Oh, OK. I assumed Windows would also know the difference between an SSE4 build of something of something and an AVX build of something, at least enough to inform the user they don't have the CPU instruction. Maybe I am just too versed in common sense for Microsoft. :stuck_out_tongue_closed_eyes:

**Comment by lightningterror** [comment]
I'll remove this from 1.6 milestone. It's not a big issue, let's keep the milestone realistic.

**Comment by lightningterror** [comment]
Closing as we are merging plugins in to core.
