### ISSUE TITLE
[Feature Request]: Is it feasible to lower the OS requirements?

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11017]
### Description

Lower the OS requirements to macOS 10.15+

### Reason

PCSX2 runs mainly on intel/amd ISA.
macOS 10.15.7 Catalina, this version is the last version purely for Intel devices, above versions introduce Apple silicons, to avoid performance down, old intel devices are better to keep using this version of macOS. Is there any special needs of new OS APIs?

### Examples

Zed editor, its system requirements is macOS 10.15+
https://zed.dev/download

**Comment by stenzek** [comment]
No. Qt's minimum is 11.0, out of our control. Feel free to submit patches to Qt.

Might be some things in Metal as well. Pretty sure I used some in DuckStation.

**Comment by Bonney01** [comment]
> No. Qt's minimum is 11.0, out of our control. Feel free to submit patches to Qt.
> 
> Might be some things in Metal as well. Pretty sure I used some in DuckStation.
> 
> Edit: It's also unsupported by Apple. You shouldn't connect devices running unsupported operating systems to the internet, since you're no longer getting security patches, your chances of getting pwned increase.

Thanks for your explanation and advice.
Actually I run the emulator on an old device offline, but created this issue on another new device which is online.
