### ISSUE TITLE
Linux Mint Mate Edition 17.2 64 bit PCX2 asks to uninstall 214 packages.

### ISSUE THREAD

**Issue by matthekc** [PCSX2/pcsx2#1102]
It is not a major issue for me (I just won't update), but I wanted to let you know.

**Comment by vgturtle127** [comment]
@matthekc 214?! That's crazy!

To clarify, when you try to uninstall PCSX2 it tries to uninstall TWO HUNDRED AND FOURTEEN packages?

**Comment by frantisekz** [comment]
Probably broken dependencies. Can you send list of packages to be uninstalled by upgrading pcsx2?

**Comment by gregory38** [comment]
The issue is Mesa EGL. SDL2 requires it. Open a bug in your distribution. And try to install those command, you will see that issue isn't related to PCSX2.
```
sudo apt-get install libsdl2-2.0-0:i386 libsdl2-2.0-0:amd64 
```
```
sudo apt-get install libegl1-mesa:i386 libegl1-mesa:amd64   
```
```
sudo apt-get install  libwayland-egl1-mesa:amd64  libwayland-egl1-mesa:i386     
```

**Comment by matthekc** [comment]
Sorry guys, I was in a hurry and filed the bug with you instead of the PPA with Gregory... I see Gregory has spotted it.  Like I said not a big deal for me, but I thought you might want to know.

**Comment by matthekc** [comment]
I already posted the issue on the Linux Mint forums in case someone else runs into the issue.  My main concern is someone accidentally ruining their install...

**Comment by matthekc** [comment]
Sorry Greg,
This is sorta my spam email I sign up for things with but sorry for the late reply...  Like I said for me it's not a real issue I will get my upgrade with 16.04.Do you still want me to help troubleshoot I hide the update and more or less forgot about the issue?
 

    On Sunday, January 10, 2016 6:22 PM, Gregory Hainaut <notifications@github.com> wrote:
 

 The issue is Mesa EGL. SDL2 requires it. Open a bug in your distribution. And try to install those command, you will see that issue isn't related to PCSX2.sudo apt-get install libsdl2-2.0-0:i386 libsdl2-2.0-0:amd64 
sudo apt-get install libegl1-mesa:i386 libegl1-mesa:amd64   
sudo apt-get install  libwayland-egl1-mesa:amd64  libwayland-egl1-mesa:i386
