### ISSUE TITLE
[BUG]: Replacement texture color issues on main character in Dragon Quest VIII (8)

### ISSUE THREAD

**Issue by kurtbixby** [PCSX2/pcsx2#11022]
### Describe the Bug

Custom textures for the main character in Dragon Quest 8 no longer show the correct color. The colors are extra bright and there appear to be issues with transparency calculations. I'm using the "HD Remaster" texture pack from [this video](https://www.youtube.com/watch?v=0dY7F9G9898). The problem occurs at native resolution as well.
This problem popped up between March 25th and today. I don't know what my old, functional build number was.

Bright Lighting Regular Textures
![DQ8BrightRegular](https://github.com/PCSX2/pcsx2/assets/3386323/57e29077-84d7-4d28-b38d-f302fc38c03a)
Bright Lighting Custom Textures
![DQ8BrightCustom](https://github.com/PCSX2/pcsx2/assets/3386323/65317cf7-e25e-4c4a-8efa-0922ae86e62c)
Dark Lighting Regular Textures
![DQ8DarkRegular](https://github.com/PCSX2/pcsx2/assets/3386323/81ca9dda-c9f7-4e4a-8c60-cad63b209816)
Dark Lighting Custom Textures
![DQ8DarkCustom](https://github.com/PCSX2/pcsx2/assets/3386323/18b61ec9-1555-4c8e-a067-101bef220ff0)

### Reproduction Steps

Open Dragon Quest 8 with the custom texture packs to see the incorrect colors. Toggling "Load Textures" in the game properties menu off and on fixes and causes the problem.

### PCSX2 Revision

v1.7.5669

### Operating System

Windows 11

### CPU

AMD 5900X

### GPU

Nvidia 4090

### Logs & Dumps

GSDump
https://1drv.ms/u/s!An_Rtf_vDrr0tiun3uEFgNPlYHV2?e=8NIUde

**Comment by RedDevilus** [comment]
Would've https://github.com/PCSX2/pcsx2/pull/11020 fixed it?

**Comment by kurtbixby** [comment]
I get intended behavior on build 5663, but the textures break on build 5664.

**Comment by stenzek** [comment]
If the alpha in the texture is wrong, it may cause rendering issues now.

**Comment by stenzek** [comment]
Nevermind, linking to downloads, such packs can be argued to be derived works and thus piracy.
