### ISSUE TITLE
Text and noise not rendering correctly on Silent Hill 3

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#11037]
### Describe the Bug

The font on SH3 will lose all detail if blending is set to anything except Full.
The noise effect that happens when you are on the otherworld (only if you have the noise effect enabled on settings) doesn't render without blending set to medium

Setting blending to full fixes those issues and it doesn't seem to cause performance issues on amd gpus like the rx6600

### Reproduction Steps

For the font issue:
1. Boot the game without changing blending from default
2. you should see it immediately on the main menu
For the Noise effect issue:
1. Start a new game
2. Once you skip the cutscenes you should notice that there is no noise effect.

### Expected Behavior

Font shouldn't look so pale and noise should be applying 

### PCSX2 Revision

v1.7.5678

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

### CPU

Ryzen 5 5600

### GPU

Rx 6600

### GS Window Screenshots

Font:
Default:
![image](https://github.com/PCSX2/pcsx2/assets/89411895/2fb6964a-0a89-4a31-ac84-0a879b3299b9)
Full:
![image](https://github.com/PCSX2/pcsx2/assets/89411895/11694b2d-535e-4cdb-b3b8-45b3becd6b53)

Noise effect:

Default:
![Screenshot_04_04_2024-19](https://github.com/PCSX2/pcsx2/assets/89411895/4569d301-2200-4d98-ac1a-6c340f31f68a)
Medium:
![Screenshot_04_04_2024-20](https://github.com/PCSX2/pcsx2/assets/89411895/bc4976e2-4411-4d22-ba57-18ac9594d7d2)

**Comment by Mrlinkwii** [comment]
ok , ill label  this as gamedb , and ill let who ever add a blending rec for SH3 ( which will be the best way forward )

**Comment by AmyRoxwell** [comment]
> ok , ill label this as gamedb , and ill let who ever add a blending rec for SH3 ( which will be the best way forward )

Alright, thanks!
