### ISSUE TITLE
 GL_ARB_separate_shader_objects with Geometry Shaders on Mesa corrupts output

### ISSUE THREAD

**Issue by frantisekz** [PCSX2/pcsx2#1103]
Upstream issue: https://bugs.freedesktop.org/show_bug.cgi?id=93650
Example of corruption: http://imgur.com/a/DW7nt
Tested on Mesa 11.1 and git.

**Comment by gregory38** [comment]
Thanks.

**Comment by frantisekz** [comment]
Fixed upstream, I'll retest when new Mesa is released (I don't have time to recompile Mesa atm) and I'll report back.

**Comment by gregory38** [comment]
Normally it must be fine in Mesa 11.1.2

**Comment by frantisekz** [comment]
It works fine with Mesa 11.2.0
