### ISSUE TITLE
[Feature Request]: File management for Data stored on the HDD

### ISSUE THREAD

**Issue by EdEddED** [PCSX2/pcsx2#11030]
### Description

Since PCSX2 doesn't support MagicGate and thus a way to load a version of the PS2 Browser with Hard Drive support, nor homebrew like wlaunchELF, I was hoping that there could be a way for the emulator itself to manage files stored on the emulated HDD.

It could be located in the Network & HDD panel, where someone would go to enable the HDD feature. From there, they can click a button or switch menu panels to bring up a list of all titles and save games stored on the HDD. This menu would allow someone to select install or save data, and delete it on its own, without requiring reformatting.

### Reason

Apart from not having to reformat the HDD every time someone wants to erase a single item from the HDD, It'll allow users to manage their Hard Drive storage without needing 3rd party or copyrighted software (The aforementioned MagicGate, the HDD Utility Disc, etc.).

In addition, it would also make using the virtual HDD much less of a hassle to use - While you can uninstall game data through each individual game's install feature, it's very time consuming and also doesn't do anything about save files, unless the game also has a built-in way to delete its own saves off of the hard drive (The Japanese Version of Ace Combat 04, for example, does not have this option).

### Examples

I can imagine this HDD list working similarly to either the game list that's available in the main screen of PCSX2 now, or as a separate bespoke dialog box. Perhaps it could look and function similar to how the Gamecube Emulator Dolphin handles memory cards (though, naturally, only with the HDD's contents instead of two memory cards).

In the example below, Open and Create allows the user to... well, open and create new memory card files for the window to manage.
<img width="762" alt="Screenshot 2024-04-03 at 5 18 42 PM" src="https://github.com/PCSX2/pcsx2/assets/38295703/a66b23a1-94aa-40f6-a056-9e02cda1a047">

**Comment by stenzek** [comment]
Given the rarity of games that actually use the HDD, I don't think it's worthwhile for the application itself to have this.

It's a lot of work, you'd basically have to implement the filesystem itself, and a browser on top of that. And then it'd have to be validated fairly strongly, to ensure data integrity is preserved. A quick google search suggests that there's already tools that can do this, as well, but CLI-based.

Therefore, I think it makes more sense to mark this as a WONTFIX, but if someone wants to implement the filesystem within the PCSX2 core, and create a file browser UI in Qt, then we'd be happy to consider accepting a pull request.
