### ISSUE TITLE
BIOS list appears empty

### ISSUE THREAD

**Issue by DigitalMajestic** [PCSX2/pcsx2#11034]
### Describe the Bug

As of 1.7.5676 the BIOS list in settings appears empty. The BIOS is still able to be read if previously selected and games still launch but selecting it is not possible.

### Reproduction Steps

Open BIOS tab in settings

### Expected Behavior

BIOS to appear in list

### PCSX2 Revision

1.7.5676

### Operating System

Windows 11

### Logs & Dumps

![image](https://github.com/PCSX2/pcsx2/assets/40978750/554887d4-5286-468a-83a1-9fb63ac71bd2) photo stolen from Pandubz, thanks Pan

**Comment by DigitalMajestic** [comment]
First time setup wizard is also broken. If you haven’t set your bios before, you’ll need to manually specify the file name in pcsx2.ini

**Comment by lightningterror** [comment]
Regression from https://github.com/PCSX2/pcsx2/pull/11015
