### ISSUE TITLE
[BUG]: Ridge Racer V Body rendering Issue

### ISSUE THREAD

**Issue by crashGG** [PCSX2/pcsx2#11047]
### Describe the Bug

The car body is rendered incorrectly both in competition and replay.
![Ridge Racer V_SLUS-20002_20240407202109](https://github.com/PCSX2/pcsx2/assets/80488411/2b2a82a6-6a0b-449f-8300-9c8768102489)

### Reproduction Steps

You can see it immediately as soon as you enter the game

### PCSX2 Revision

newest master

### Operating System

Windows 10 (64bit)

### CPU

amd 7840h

### GPU

amd 780m

**Comment by Mrlinkwii** [comment]
can i have a gs dump

**Comment by JordanTheToaster** [comment]
Already an issue #3639

**Comment by Mrlinkwii** [comment]
closing  as its a duplicate
