### ISSUE TITLE
[BUG]: Enabling USB Mouse HID on games doesn't let you access any menu on GUI

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#11051]
### Describe the Bug

For games that have mouse support: There is a current bug where you cannot click on the pcsx2 GUI (and if you are like me and removed all the hotkeys, your only options is fully shutting down the emulator)

### Reproduction Steps

1. Make a profile or use Shared and enable USB Mouse HID
2. Boot any game that has mouse support
3. Try to click on the toolbar or your game properties window

![Screenshot_04_07_2024-22](https://github.com/PCSX2/pcsx2/assets/89411895/a924bb96-e656-428f-9b72-353f6303db76)

### Expected Behavior

Being able to click on the PCSX2 GUI while having mouse enabled.

### PCSX2 Revision

PCSX2 v1.7.5688

### Operating System

Windows 11

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

**Comment by stenzek** [comment]
Not really sure how you expect it to be handled. PCSX2 captures the mouse.

The intended workflow is to have a pause hotkey, hit that, then it releases the mouse. If that's not happening, then there's a bug here. If it is, then it's user error and invalid ;)

**Comment by kamfretoz** [comment]
Yeah it's similar to how cursors are handled on VMs like VMware or VirtualBox, basically have a key to release the cursor.

**Comment by AmyRoxwell** [comment]
> Not really sure how you expect it to be handled. PCSX2 captures the mouse.
> 
> The intended workflow is to have a pause hotkey, hit that, then it releases the mouse. If that's not happening, then there's a bug here. If it is, then it's user error and invalid ;)

Could it be a way to have a toggle to stop the capture of the mouse? it can a bit annoying if I need to change settings + online games cannot be paused or you will get disconnected so...

**Comment by stenzek** [comment]
Then the movement in the window would get desynced with the guest pointer, it would move out of the window for FPS type cameras, etc.
