### ISSUE TITLE
[Feature Request]: Retain Previously Used URL for Cover Downloads

### ISSUE THREAD

**Issue by vandersdg** [PCSX2/pcsx2#11050]
### Description

Introduce functionality within the system to store the last used URL for cover downloads. Upon installing a new game, the system will automatically populate the URL field with the previously used URL, allowing users to proceed with the download without the need for manual input.

### Reason

Currently, when installing new games, users are required to manually paste the URL for downloading covers each time. This process can be repetitive and time-consuming. To streamline the experience, it would be beneficial to implement a feature that remembers and retains the previously used URL for cover downloads. This way, users won't have to repeatedly input the same URL for every installation.

### Examples

![Captura de tela de 2024-04-07 19-54-23](https://github.com/PCSX2/pcsx2/assets/90361836/c7567855-b8f4-4a1f-8dc8-7495ddcc46d8)

**Comment by refractionpcsx2** [comment]
Not happening https://github.com/PCSX2/pcsx2/issues/8013#issuecomment-1409637302

**Comment by vandersdg** [comment]
I am gonna assume you guys are just lazy.

**Comment by refractionpcsx2** [comment]
assume what you like, you shouldn't need to be constantly updating your covers. But insulting us is the worst way to bring us around to your side.
