### ISSUE TITLE
[BUG]: NeoGeo Online Collection Vol. 7 - KOF - Nests Hen [NTSC-J]

### ISSUE THREAD

**Issue by Yagami-kun** [PCSX2/pcsx2#11058]
### Describe the Bug

Black lines around the characters on KOF'99 Evolution & on KOF 2000 loading screens ¬¬
On NeoGeo Online Collection Vol. 3 - KOF - Orochi Hen this dont happens u.u

### Reproduction Steps

Using a higher res u.u

### PCSX2 Revision

Nightly v1.7.5317 release

### Operating System

Windows 11

### CPU

i5-10400

### GPU

RTX 3060

### GS Window Screenshots

https://i.imgur.com/e5UGEY9.png

### Logs & Dumps

[KOF Nests Hen - Black lines around the characters .rar](https://mega.nz/file/FwsRRCQR#lRiR58ZW5x43n2oyl5GvUyd8Vv_NCxF-Jo6ZDEx9xZs)

**Comment by Mrlinkwii** [comment]
We do not accept issues relating to upscaling at this time.

We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling.

**Comment by Yagami-kun** [comment]
But yours dont even want to consider that??????Most PS2 games are already at least functional so I believe its time to see these smaller details u.u

**Comment by JordanTheToaster** [comment]
> But yours dont even want to consider that??????Most PS2 games are already at least functional so I believe its time to see these smaller details u.u & what solutions would those u mentioned be??????

There is no point upscaling a 2D game like this and this isn't even possible to fix I've checked.

**Comment by Yagami-kun** [comment]
> > But yours dont even want to consider that??????Most PS2 games are already at least functional so I believe its time to see these smaller details u.u & what solutions would those u mentioned be??????
> 
> There is no point upscaling a 2D game like this and this isn't even possible to fix I've checked.

Dude what u say doesnt make sense,because there are games like KOF Orochi Hen that I mentioned before where this type of problem doesnt occur (>'-'<)
