### ISSUE TITLE
[BUG]: White spots on dialog box in Super Robot Taisen Z 

### ISSUE THREAD

**Issue by Bonney01** [PCSX2/pcsx2#11062]
### Describe the Bug

#10994 has fixed the black spots on the ground in this issue #11001

Blending Accuracy: Maximum
OpenGL, Software: perfect with no issues
Direct3D11: white spots on dialog box

### Reproduction Steps

Start game with セツコ, the firt dialog box of talking to ジェリド

### Expected Behavior

No white spots on the dialog box

### PCSX2 Revision

v1.7.5698

### Operating System

Windows 11

### CPU

i5-5287U

### GPU

Intel Iris Graphics 6100

### GS Settings

Renderer: Direct3D11
Blending Accuracy: Maximum

### GS Window Screenshots

![Super Robot Taisen Z_SLPS-25887_20240411122059](https://github.com/PCSX2/pcsx2/assets/165537229/5cf058e2-13dd-4315-b02b-a8056efd4ae6)

### Logs & Dumps

[Super Robot Taisen Z_SLPS-25887_20240411122059.zip](https://github.com/PCSX2/pcsx2/files/14941499/Super.Robot.Taisen.Z_SLPS-25887_20240411122059.zip)

**Comment by stenzek** [comment]
Why are you using maximum blending? That is not the standard configuration.

![image](https://github.com/PCSX2/pcsx2/assets/11288319/7fe66274-5093-4c7c-840d-2e260b1dcb0e)

Looks fine to me on both Windows and Linux (llvmpipe). Could be a driver bug, but given we don't have this GPU, can't do much about it.

**Comment by Bonney01** [comment]
But it has no issues with OpenGL renderer.

PS: I can't find a way to report bugs of DuckStation, so I report a bug to you here, DuckStation has graphic issues with Metal or Vulkan renderers on macOS Monterey.

**Comment by stenzek** [comment]
Doesn't mean it's not a driver bug. My A750 corrupts the depth buffer in a similar way in DX12 when zclamp is enabled, so while I checked this dump and zclamp isn't used, doesn't mean it isn't something similar.

**Comment by Bonney01** [comment]
#10994 has fixed the black spots on the ground in this issue #11001
@lightningterror could give a better solution?
