### ISSUE TITLE
[BUG]: nothing happen after replay an input file

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#11060]
### Describe the Bug

nothing happen after try to play an input recording file.

### Reproduction Steps

boot the game.
tools -> input recording -> New and start recording then stop it.
tools -> input recording -> play and select the file.
and nothing happened.

https://cdn.discordapp.com/attachments/315544036184293386/1227246657964474480/asdfg.mp4?ex=6627b584&is=66154084&hm=9f45b88023f2d9faec5f9a97791a51ddc8409df4503ba9ecabad6d1514b0e7f1&

(at v1.7.5696, the system console says 
> [REC]: Input recording file opening failed. Error - No such file or directory

but now {v1.7.5698}, even the console says nothing 

### PCSX2 Revision

v1.7.5698

### Operating System

Windows 11

**Comment by sestain** [comment]
v1.7.5673 last working version

v1.7.5674 broke opening input recording

**Comment by TheLastRar** [comment]
Can you test https://github.com/PCSX2/pcsx2/pull/11332
