### ISSUE TITLE
[BUG]: Devil May Cry PAL FMVs corrupted by subtitles

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#11074]
### Describe the Bug

Devil May Cry PAL version has corrupted FMVs when subtitles are activated. 

### Reproduction Steps

Play game intro with subtitles 

### Expected Behavior

No graphics corruption 

### PCSX2 Revision

1.7.5703

### Operating System

Windows 10 (64bit)

### CPU

i5 12400f

### GPU

Rtx 3060

### GS Window Screenshots

![322267890-ac62fdc7-8fb2-4b60-856a-ee00843e1f47](https://github.com/PCSX2/pcsx2/assets/38129260/44b354ac-2cf5-4107-ab87-db5e98e76416)

### Logs & Dumps

[Devil.May.Cry_SLES-50358_20240414125502.gs.zip](https://github.com/PCSX2/pcsx2/files/14970756/Devil.May.Cry_SLES-50358_20240414125502.gs.zip)

**Comment by Mrlinkwii** [comment]
just so it wont get lost 

Details: Two layers, it writes the background, but never draws to the target, so the transfer list gets destroyed, and by the time it gets picked up by the PCRTC on the next frame, it has no history of the writes.


![image](https://github.com/PCSX2/pcsx2/assets/17685135/2e2c22e6-e34f-42aa-a36b-a4595f644ad5)
