### ISSUE TITLE
Fatal Frame 1, issues rendering Ghosts

### ISSUE THREAD

**Issue by weirdbeardgame** [PCSX2/pcsx2#11070]
### Describe the Bug

In Fatal Frame 1 there's an enabled gs hardware hack align sprite that forces Ghosts to render without black lines. An issue that only exists in HW mode and not Sw even without upscaling.

This is presumably because of a reverse GS download gone wrong.

### Reproduction Steps

Turn off Align sprite and see the thicc lines.
![image-3](https://github.com/PCSX2/pcsx2/assets/22896793/a23fcfda-69d3-4315-bea5-71d41db9d74b)

### Expected Behavior

No HW hack, no lines.

### PCSX2 Revision

Any 1.7 buold

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 3700x

### GPU

Raedon 6600 xt

### GS Settings

Manual fixes enabled

**Comment by stenzek** [comment]
You didn't provide a GS dump.

> In Fatal Frame 1 there's an enabled gs hardware hack align sprite that forces Ghosts to render without black lines. An issue that only exists in HW mode and not Sw even without upscaling.

Align sprite has no effect at native resolution, nor for software.

> This is presumably because of a reverse GS download gone wrong.

What is a "reverse GS download"? I've never heard of it.
