### ISSUE TITLE
Cold Winter (U) - Shadows Cast on Wrong Surfaces

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1108]
-PCSX2 version: PCSX2 1.5.0-20160108223555

-PCSX2 options: Defaults, no settings modifications affect the issue.

-Plugin settings: GSDX High Accuracy Blending for correct lighting and shadowing.

-Description: Cold Winter has a lot of shadow casting objects such as chairs and tables and crates and, of course, NPCs. In this case, a dead guard is casting a shadow not only beneath him, but a bugged version on the wall nearby.

-How to replicate: Start a new game. There will be bed shadows cast on the walls of the room. Walking out of the room and down the hall, you'll see the bugged shadow as depicted in the attached image.

-Last known version to work: Never worked, to my knowledge.

-PC specifications: CPU: Intel Core Quad @ 3.2Ghz GPU:Geforce GTX 750ti 2GB OS: Windows 10 64 Bit

Other comments: Issue occurs on all renderers, both GL and DX, HW and SW.

![wrong_shadows](https://cloud.githubusercontent.com/assets/10704701/12233160/831675fa-b8b0-11e5-9a5a-0cdb7d3b3f67.jpg)

**Comment by refractionpcsx2** [comment]
Does this still happen in new builds with OpenGL?

**Comment by MrCK1** [comment]
@AmbientMalice Any update on this with latest git?

**Comment by gregory38** [comment]
@AmbientMalice ping, any update on latest git ?

**Comment by MrCK1** [comment]
@AmbientMalice Can you check the shadows too? I meant to ask you earlier.

**Comment by AmbientMalice** [comment]
Still happening.

**Comment by MrCK1** [comment]
Closing in favor of newer issue, still present on latest master - https://github.com/PCSX2/pcsx2/issues/3881
