### ISSUE TITLE
[Feature Request]: Joystick 8BitDo Ultimate wireless isn't yet supported by the SDL2 game controller API

### ISSUE THREAD

**Issue by PedroMussato** [PCSX2/pcsx2#11095]
### Description

(GameDB) 9858 games on record (loaded in 135ms)
onepad: Joystick (8BitDo Ultimate wireless,GUID:05000000c82d00001230000000010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (8BitDo Ultimate wireless,GUID:05000000c82d00001230000000010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

### Reason

This is a verry common controller and it works on Windows, but on Linux I can't use it.

### Examples

Use the 8bitdo ultimate wireless via Bluetooth or Wired doesn't works on PCSX2 on Linux (tested on Ubuntu and Debian12).

**Comment by RedDevilus** [comment]
Can you please download the nightly from: https://pcsx2.net/   and try again? 1.6 stable is from 2020 and uses outdated mappings for Linux Side.

**Comment by RedDevilus** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/24227051/fa1534e9-b5ad-4b10-8171-a328c4bf12f6)

I do see that mapping available, so 1.7 should work fine.

**Comment by refractionpcsx2** [comment]
If it doesn't work on the newest nightly version you need to tell SDL or the controller DB, because that's not really something we deal with. We just support what it tells us

Try here first: https://github.com/mdqinc/SDL_GameControllerDB
Then here if all else fails: https://github.com/libsdl-org/SDL
