### ISSUE TITLE
Unreal Tournament (NTSC-U) [SLUS-20034] Game Freezes/Breaks

### ISSUE THREAD

**Issue by yoshijin** [PCSX2/pcsx2#1109]
The game freezes after the last frag in the first deathmatch when there is onscreen prompt to press "Fire" button. Tried everything from Hardware to Software mode, MTVU off, and also tried messing with VU.
I'm Using
PCSX2 1.4.0 (Also been trying git builds)
CPU: AMD 555 BE 3.2 GHz
GPU: HD 5770
RAM: 4 GB 

Previously reported #268

**Comment by ssakash** [comment]
your issue ticket is a duplicate one then since #268 already exists, please add more information via comments on #268 instead of creating a new one, Thanks.

**Comment by yoshijin** [comment]
Okay
