### ISSUE TITLE
[BUG]: Bottom menu bar obscures the bottom-most achievement/leaderboard entry

### ISSUE THREAD

**Issue by CookiePLMonster** [PCSX2/pcsx2#11101]
### Describe the Bug

The bottom entry in the scrollable achievement/leaderboard lists is cut off ever since the bottom menu bar was introduced:
![image](https://github.com/PCSX2/pcsx2/assets/7947461/b3f1a76d-be16-462f-86ee-1777bd37c077)

### Reproduction Steps

1. Run any game with achievements.
2. Pause it and navigate to Achievements or Leaderboards.
3. Scroll down all the way to the bottom.
4. Observe the bottommost entry is obscured.

### Expected Behavior

The bottommost entry is fully visible.

### PCSX2 Revision

v1.7.5715

### Operating System

Windows 11

**Comment by stenzek** [comment]
Tacked onto #11100.
