### ISSUE TITLE
[BUG]: USB Wheel Force Feedback cuts out occasionally

### ISSUE THREAD

**Issue by cybersoldier8** [PCSX2/pcsx2#11128]
### Describe the Bug

While playing Gran Turismo 4 with a Fanatec CSL DD 5nm wheel, the force feedback cuts out occasionally. It seems to happen roughly every 1-1.5 minutes, and lasts until the game registers another spike in force feedback, such as running over a curb or colliding with another car. This may just be an issue with Gran Turismo 4, I don't have any other games that support a force feedback wheel to test it with.

### Reproduction Steps

- Download the latest 1.7.5727 nightly release
-In Controller settings, set up USB Port 1 as a Wheel Device, Driving Force Pro (rev11.02), steering, throttle, brake, and force feedback bound to SDL-1 (the Fanatec wheel).
- Boot Gran Turismo 4
- Begin an Arcade mode race on Laguna Seca, with the Toyota MR2 AW11
- Drive around the track
- About 1 minute into the race, usually around turn 5-7, force feedback suddenly cuts out on the wheel. Steering and all other inputs continue to work but driving the car becomes very difficult with no force feedback.
- Drive the car over any of the nearby curbs, and force feedback kicks back in.

### Expected Behavior

I would expect force feedback to be consistent through an entire race at least.

### PCSX2 Revision

1.7.5727 nightly

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Please don't make multiple issues when it's potentially a hardware specific problem.

See #11129.
