### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Dokman** [PCSX2/pcsx2#1113]
So in the wiki there is no guide to how to translate correctly
and you chould have to update with the new link

PS: i think it's not important but...

**Comment by ssakash** [comment]
I guess the translation guide does need to be updated : http://wiki.pcsx2.net/index.php/PCSX2_Documentation/Translation_Guide

Either way, most of translation related doubts seem to be asked at the translators subforum so asking there would also be helpful for new translators.

**Comment by gregory38** [comment]
@Dokman Ping me if above answer isn't enough
