### ISSUE TITLE
[BUG]: RetroAchievements unlock sound doesn't play

### ISSUE THREAD

**Issue by nokia8801** [PCSX2/pcsx2#11141]
### Describe the Bug

The Xbox 360 Achievement sound that is supposed to play when you unlock an achievement from RetroAchievements never plays. Leaderboard sound also doesn't play. I have yet to hear any sound from bin/resources/sounds/achievements/.

### Reproduction Steps

I don't really know as it never played for me. I've been using [pcsx2-avx-git](https://aur.archlinux.org/packages/pcsx2-avx-git) from the AUR for the past four months. 

Arch Linux
Qt 6.7.0 with qt6-wayland
GNOME 46.1 on Wayland

### Expected Behavior

It should play.

### PCSX2 Revision

v1.7.5733

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

**Comment by Mrlinkwii** [comment]
can you try the appimage

**Comment by nokia8801** [comment]
Just tried the appimage with two hardcore achievements, still no sound. Does Wayland perhaps affect it? I have 
```
SDL_VIDEODRIVER=wayland
SDL_AUDIODRIVER=pipewire
```
as environment variables. Or could it be related to Qt? None of the bin/resources/sounds/achievements/ sounds ever played for me in any game. The Achivements>Enable Sound Effects setting is turned on both globally and per-game. The log window also doesn't have anything significant other than the fact that the achievement successfully unlocked and awarded.

**Comment by stenzek** [comment]
You're probably missing aplay or whatever the binary is that it runs to play the sound effect.

**Comment by stenzek** [comment]
Works fine here, so invalid.

Please don't open any reports in the future about any third-party packages, such as the AUR. They're hacked up and known to be broken.

**Comment by nokia8801** [comment]
I understand but I said I tried the appimage and it also didn't work? Shouldn't it contain everything necessary for the sounds to play?

**Comment by stenzek** [comment]
No, sound effects simply shell out to `aplay`.

https://github.com/PCSX2/pcsx2/blob/c831f5759f94d7545da8a8afdf3ec2afdfe3e803/common/Linux/LnxMisc.cpp#L169-L176

**Comment by nokia8801** [comment]
You are right. Installing alsa-utils on Arch Linux fixed the issue. Though I don't know how I would've known about this even if I wasn't running a "hacked up and known to be broken" package like you described (I guess no official Arch package does that) and ran the appimage or flatpak.

**Comment by nokia8801** [comment]
Is [pcsx2](https://aur.archlinux.org/packages/pcsx2) or [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git) fine? I'm on an iGPU so any native compilation benefits are needed for performance reasons for me, I'd rather not use a binary package.

**Comment by stenzek** [comment]
None of those packages are maintained by us. The performance benefit of multi-ISA builds is in the order of less than 1-2%. It's really not worth it. And this is coming from someone who previously argued to keep separate SSE4/AVX2 builds. Anyone claiming a measurable performance benefit from `-march=native` is likely full of, since the majority of CPU time gets spent in the JIT on the EE/VU threads. It will also do *nothing* for GPU performance.

If you *must* compile yourself, you can follow the guide at https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux. But keep in mind you're also on your own here if you encounter any issues.

**Comment by nokia8801** [comment]
Thanks. I guess I might use [pcsx2-latest-bin](https://aur.archlinux.org/pcsx2-latest-bin.git) instead since it just install the AppImage binary.

**Comment by stenzek** [comment]
I'd recommend against it, because if it's like the other "bin" packages I've seen, they extract the appimage, which means you won't get automatic updates.

**Comment by nokia8801** [comment]
I just saw the recent 85a33971e7b68651a8c0b2594c6ed2c6ce7b8f88 commit, I guess it relates to this issue. Thanks a lot. Since I use pipewire and also have pipewire-pulse and pipewire-alsa installed so I can use apps that utilize them, I did not know or think I needed alsa-utils which includes aplay on Arch Linux. Thanks again.

PS: I did not mean to troll or come off as arrogant in my Wayland issue. That was not my intention, I hope we don't get off on the wrong foot. GNOME does indeed not play well with anything the Linux community does unfortunately and it's a hell to theme Qt apps, let alone properly use them on Wayland. I mainly use labwc (wlroots) these days and have GNOME installed as a fallback (I also have a KDE machine but that's separate). I was just hopeful that at least PCSX2 could be built without X11 requirement/dependencies. So please don't take it the wrong way, it was truly not my intention and I felt a bit sad when you said it was "bait" and 'trolling". Thanks for everything you do.
