### ISSUE TITLE
[BUG]: Can't build without X11 dependencies

### ISSUE THREAD

**Issue by nokia8801** [PCSX2/pcsx2#11149]
### Describe the Bug

Trying to build without X11 support and only with Wayland support. CMake fails to generate setup. I have already read:

https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux
https://github.com/PCSX2/pcsx2/pull/10179

and various issues created about Wayland.

I know that Wayland can still be used and is supported (QT_QPA_PLATFORM=wayland and I_WANT_A_BROKEN_WAYLAND_UI=YES). The reason I'm trying to build without X11 at all is because I'm trying to build a minimal Wayland only setup with [labwc](https://github.com/labwc/labwc) (stacking wayland compositor) and [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots)  which make X11 and XWayland optional dependencies and not required, meaning I can set up a Wayland only system.

### Reproduction Steps

```
sudo pacman -S clang cmake compiler-rt cppdap extra-cmake-modules llvm ninja qt6-tools qt6-wayland rhash --asdeps
git clone --recursive https://github.com/PCSX2/pcsx2.git
cd pcsx2/
cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=mold" -DCMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=mold" -DCMAKE_PREFIX_PATH="$PWD/deps" -DDISABLE_ADVANCE_SIMD=OFF -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DWAYLAND_API=ON -DX11_API=OFF -DUSE_VULKAN=ON -DENABLE_SETCAP=OFF -GNinja
```

### Expected Behavior

It should build? I'm not sure if Wayland only is supported. It builds when `-DX11_API=ON` is set but not when -`DX11_API=OFF` is set even though `-DWAYLAND_API=ON` is set in both scenarios.

For my use case Wayland works perfect so I really don't want this to be the usual Wayland vs X11 scenario. At the end of the day they're just tools. I'm trying to build a minimal Wayland only setup with labwc and wlroots. You can close if it's not appropriate or not a bug in the build process.

### PCSX2 Revision

v1.7.5746

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### Logs & Dumps

```
-- The C compiler identification is Clang 17.0.6
-- The CXX compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Version: 3.29.2
-- CMake System Name: Linux
-- Building for Linux.
-- Building with Clang/LLVM.
-- BuildType set to Devel by default
-- Building for x86-64.
-- Found Git: /usr/bin/git (found version "2.44.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")
-- Found PNG: /usr/lib/libpng.so (found suitable version "1.6.43", minimum required is "1.6.40")
-- Found JPEG: /usr/lib/libjpeg.so (found version "80")
-- Found Zstd: /usr/lib/libzstd.so (Required is at least version "1.5.5")
-- Found LZ4: /usr/lib/liblz4.so
-- Found the following WebP libraries:
--  WebP (required): /usr/lib/libwebp.so
-- Found WebP: /usr/include
-- Found Freetype: /usr/lib/libfreetype.so (found suitable version "2.13.2", minimum required is "2.11.1")
-- Found Shaderc: /usr/lib/libshaderc_shared.so
-- Found CURL: /usr/lib/libcurl.so (found version "8.7.1")
-- Found PCAP: /usr/lib/libpcap.so
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Could NOT find Vtune (missing: VTUNE_LIBRARIES VTUNE_INCLUDE_DIRS) 
-- Found FFMPEG: /usr/include (found version "6.1.1") found components: avcodec avformat avutil swresample swscale
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- AIO found
-- LIBUDEV found pkg
-- Wayland: Egl requires Client
-- Found Wayland_Client: /usr/lib/libwayland-client.so (found version "1.22.0")
-- Found Wayland_Egl: /usr/lib/libwayland-egl.so (found version "18.1.0")
-- Found Wayland: /usr/lib/libwayland-client.so;/usr/lib/libwayland-egl.so (found version "1.22.0") found components: Egl
-- Could NOT find Libbacktrace (missing: LIBBACKTRACE_LIBRARY LIBBACKTRACE_INCLUDE_DIR) 
-- Checking for module 'dbus-1'
--   Found dbus-1, version 1.14.10
-- ryml: using C++ standard: C++20
-- ryml: importing subproject c4core (SUBDIRECTORY)... /home/nokia/Downloads/temp/pcsx2/3rdparty/rapidyaml/rapidyaml/ext/c4core
-- c4core: using C++ standard: C++20
-- ryml: -----> target ryml PUBLIC incorporating lib c4core
-- Looking for fts_open
-- Looking for fts_open - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off_t
-- Check size of off_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Performing Test HAVE_FICLONERANGE
-- Performing Test HAVE_FICLONERANGE - Success
-- Performing Test HAVE_NULLABLE
-- Performing Test HAVE_NULLABLE - Success
-- Looking for include file pulse/pulseaudio.h
-- Looking for include file pulse/pulseaudio.h - found
-- Looking for include file alsa/asoundlib.h
-- Looking for include file alsa/asoundlib.h - found
-- Looking for include file jack/jack.h
-- Looking for include file jack/jack.h - found
-- Looking for include file sndio.h
-- Looking for include file sndio.h - found
-- Looking for include file sys/soundcard.h
-- Looking for include file sys/soundcard.h - found
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Version: 10.1.2
-- Build type: Devel
-- Performing Test HAS_NULLPTR_WARNING
-- Performing Test HAS_NULLPTR_WARNING - Success
Using tag: v1.7.5747
Using precompiled headers.
-- Configuring done (1.5s)
CMake Error at common/CMakeLists.txt:166 (target_link_libraries):
  Target "common" links to:

    X11::X11

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by stenzek** [comment]
Sorry, not a supported configuration. Wayland is broken by design, and the various "committees" are too busy sniffing their own farts to implement the functionality required by application developers. This is well-documented.

PCSX2 does not function correctly under Wayland, due to various Qt, driver, and compositor issues. That's why the AppImage forces XCB as the Qt Platform Abstraction (and displays a scary warning), and the Flatpak forces X as well.

**Comment by stenzek** [comment]
I don't care for Wayland vs X wars. I just care about things working. PCSX2 under Wayland does **not** work. Game list doesn't repainted, it crashes on NVIDIA, etc. Even if it did compile, it's going to be buggy, then you'd be complaining about that.

Regardless, it's still not going to compile successfully, even if you strip all mentions of X from the build system, because you didn't build the dependencies correctly.

**Comment by nokia8801** [comment]
I get it, truly. But all I wanted to know was if it can be built, not if PCSX2 on Wayland performs worse compared to X11, has horrible bugs or doesn't even work at all. (Though I have been using it with Wayland all this time so...)

My issue was about the build process and the application itself but it seems to be steering towards Wayland itself so I guess I'll leave this be.

I sort of expected something like this. https://github.com/flightlessmango/MangoHud/issues/1281

But no worries, hopefully Wayland can one day be satisfactory for the PCSX2 team! (even though it wasn't my issue)

**Comment by stenzek** [comment]
> Though I have been using it with Wayland all this time so...

You've been using it under XWayland. That works fine. It's native Wayland/QPA that's the issue.

> My issue was about the build process and the application itself 

And you continue to ignore my statement that I've said 3 times now, that it still won't compile because you didn't build the dependencies correctly.

**Comment by nokia8801** [comment]
> You've been using it under XWayland.

Well, on my system, building it with `-DWAYLAND_API=ON`, running it with `QT_QPA_PLATFORM=wayland`, and observing that both the Qt application window and the game window (be it fullscreen or windowed) cannot be tracked by xeyes, cannot be seen by xwininfo, neither `xwayland` nor `mutter-x11-frames` is a running (or sleeping) process before, during or after a PCSX2 launch, in a GNOME Wayland session, with an Intel iGPU, we're just gonna have to disagree on that point.

So it made me wonder, if it **_can_** be used with Wayland, surely it could be built with Wayland only and not require X11, you know. 

But what do I know, I'm not a dev, just a newbie user so I'm out of my element here. For all I know there could be very deep rooted code that relies on X, that's why I asked if it was possible and you keep saying it is not so I'll stop asking. I hope I did not sound like the classic entitled open source user. Thanks again.

**Comment by stenzek** [comment]
> in a GNOME Wayland session

Now you're just trolling. Every Qt application is broken under GNOME in a glaringly obvious way.

Locking. Can't believe I took the bait.
