### ISSUE TITLE
[Feature Request]: Please restore 'Remove Frame Limiter' 

### ISSUE THREAD

**Issue by brad86m** [PCSX2/pcsx2#11152]
### Description

Without being able to remove frame limiter, a lot of titles will apply their own double buffer sync. This is obviously an issue if a title can not hold the target frame rate you are trying to achieve. The variable frame rate is preferred over the harsh drop back to the nearest double sync the game requires. 

Shadow of the Colossuses as an example. 

### Reason

.

### Examples

.

**Comment by stenzek** [comment]
What has game vsync got to do with the emulation speed frame limit?

**Comment by brad86m** [comment]
If a game like Shadow of the Colossus is running internally at say 51-59 fps with overclock, it will not allow itself to stay there, instead hard locking down to 50. With the limiter removed, the internal sync method is ignored, allowing the game to freely run as high as it can. Externally capping the frame limit with another tool. I use RivaTuner. The variableness is very much preferred for these games, over the sudden harsh locking down that double buffer brings. I'm on a Gsync display, so that variable 50-60 frame rate is great.

**Comment by stenzek** [comment]
Then set the speed to something above 100%.

Or push F4.
