### ISSUE TITLE
[BUG]: BIOS startup sequence flickering on Direct3D 11 Renderer

### ISSUE THREAD

**Issue by ribolovac510** [PCSX2/pcsx2#11156]
### Describe the Bug

On Direct3D 11 Renderer the PS2 BIOS startup sequence flickers. The flickering got introduced with #11073.

You can see it on the video below:

https://github.com/PCSX2/pcsx2/assets/74596991/84ec4526-3c76-4c9a-9b27-933fb5dca057

It is even more pronounced in fullscreen:

https://github.com/PCSX2/pcsx2/assets/74596991/8c34e7dc-908b-4a9d-8ef2-fe4d77e0c1a2

### Reproduction Steps

Set Renderer to Direct3D 11 and start BIOS.

### Expected Behavior

No flickering.

### PCSX2 Revision

v1.7.5750

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3060

### GS Settings

Internal resolution: 4x Native

**Comment by JordanTheToaster** [comment]
You have an Nvidia GPU you shouldn't be using DX11.

**Comment by GitHub-Khi** [comment]
Maybe the same as that: https://forums.pcsx2.net/Thread-Direct3D-11-issue-in-certain-games-since-v1-7-5704

**Comment by ribolovac510** [comment]
Hi, I'm using the DX11 Renderer on Hot Wheels - World Race as it has performance issues, the frame rate is very unstable on any other renderer no matter which settings I choose, and that's where I noticed the flickering. If you'd like to investigate I could open a new issue on that.

**Comment by JordanTheToaster** [comment]
> Hi, I'm using the DX11 Renderer on Hot Wheels - World Race as it has performance issues, the frame rate is very unstable on any other renderer no matter which settings I choose, and that's where I noticed the flickering. If you'd like to investigate I could open a new issue on that.

Join the Discord for support.

**Comment by refractionpcsx2** [comment]
This looks like the old Nvidia DX bug rearing its head again...

**Comment by ribolovac510** [comment]
Interestingly enough, having anything drawn on OSD, FPS counter or any other indicator, fixes the flickering.
