### ISSUE TITLE
Rumble racing NTSC-U DX12 SHADOW FLICKERING

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#11158]
### Describe the Bug

on dx12 the car shadows flicker

### Reproduction Steps

Use dx12

### Expected Behavior

Shadow flickering 

### PCSX2 Revision

1.7.5755

### Operating System

Windows 11

### CPU

R7 7480hs

### GPU

4070m

### GS Settings

Not important tested with all settings it's a dx12 issue

**Comment by JordanTheToaster** [comment]
Please post a GS dump.

**Comment by refractionpcsx2** [comment]
It's fine that this is an issue to look in to, but why are you using DX on a 4070?

**Comment by Emi-pcsx2** [comment]
> It's fine that this is an issue to look in to, but why are you using DX on a 4070? You should be using the automatic renderer.

Because I get better performance. Huge difference

**Comment by refractionpcsx2** [comment]
since you're on a laptop, it's probably nothing to do with DX being faster, it's likely vulkan is using your iGPU because you don't have a profile set up for PCSX2.

Performance difference should be marginal

**Comment by Emi-pcsx2** [comment]
> since you're on a laptop, it's probably nothing to do with DX being faster, it's likely vulkan is using your iGPU because you don't have a profile set up for PCSX2.
> 
> Performance difference should be marginal

I've checked that, idk why. But nonetheless, I don't mind.

**Comment by Emi-pcsx2** [comment]
> Please post a GS dump.

If it is still needed, I will tomorrow or later

**Comment by Emi-pcsx2** [comment]
> Please post a GS dump.

@![Rumble Racing_SLUS-20174_20240429004446.gs.zst.gz](https://github.com/PCSX2/pcsx2/files/15143912/Rumble.Racing_SLUS-20174_20240429004446.gs.zst.gz)

**Comment by lightningterror** [comment]
Game requires medium blend when using dx11/12, tho you should be using vulkan.

**Comment by Emi-pcsx2** [comment]
> since you're on a laptop, it's probably nothing to do with DX being faster, it's likely vulkan is using your iGPU because you don't have a profile set up for PCSX2.
> 
> Performance difference should be marginal

How do I do this?

**Comment by refractionpcsx2** [comment]
in the nvidia control panel, 3d settings, add pcsx2 as an application, then make sure it's set to use your dedicated/high performance GPU, then hit apply.

then restart PCSX2.
