### ISSUE TITLE
[BUG]: SSX huge performance regression

### ISSUE THREAD

**Issue by DonelBueno** [PCSX2/pcsx2#11166]
### Describe the Bug

Performance on the game SSX has regressed tremendously since PR #11010. The draw calls and barriers almost quadrupled, which explains the drop in speed.

Before:
![PCSX2_2024_04_29_18_22_31_532](https://github.com/PCSX2/pcsx2/assets/4239694/5db82b5f-73aa-48ab-90b3-67a77ecb9a73)

After:
![PCSX2_2024_04_29_18_18_17_137](https://github.com/PCSX2/pcsx2/assets/4239694/1930ba01-6501-45a5-aa16-00f0ca098abd)

### Reproduction Steps

Just boot the game and enter in a race.

### Expected Behavior

Performance back to where it was pre PR #11010

### PCSX2 Revision

v1.7.5760

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5800x

### GPU

GTX 1070

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/4239694/4f3bcddb-db5b-4cb1-96d4-ad6bd25eb38c)

### Logs & Dumps

[SSX_SLUS-20095_20240429185907.gs.zip](https://github.com/PCSX2/pcsx2/files/15155395/SSX_SLUS-20095_20240429185907.gs.zip)

**Comment by lightningterror** [comment]
Can you post a gs dump?

**Comment by DonelBueno** [comment]
> Can you post a gs dump?

I updated the main post with a dump.

**Comment by DonelBueno** [comment]
Running my own dump:

![PCSX2_2024_04_29_20_46_48_549](https://github.com/PCSX2/pcsx2/assets/4239694/5bdaeac2-9bd9-496a-8d11-2cc40cf6f158)

Blending at high:

![PCSX2_2024_04_29_20_48_24_395](https://github.com/PCSX2/pcsx2/assets/4239694/e89db3ce-e62c-43a9-bf90-8a9411c847d9)

**Comment by refractionpcsx2** [comment]
Might need to do a multi frame dump (shift + ctrl + f8 is the default map I think) that may capture it.

**Comment by DonelBueno** [comment]
Even a 66 MB multi frame dump still keeps the good performance. A tried on another scene, this was the worst performance I got when running a MF dump:

![PCSX2_2024_04_29_21_19_51_575](https://github.com/PCSX2/pcsx2/assets/4239694/a8b5c40b-a4b1-452e-8284-622fa30628a4)

Still a lot better than actual in-game performance. If you want the dump anyway, I uploaded it on my GDrive (30 MB, max here is 25 MB): https://drive.google.com/file/d/1IsHlVOAPh-0EdB7nMauXQfkOPkzsVdnT/view?usp=sharing

**Comment by refractionpcsx2** [comment]
yeah I can't reproduce it with the dump, it's still about 8000 barriers, which i what I expect. I guess we'll have to run the game.

**Comment by JordanTheToaster** [comment]
Fine here on a 2070 Super with full blend at 4x.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/bf2dd43a-0abb-4663-b8ba-cbea4abd2db9)

**Comment by stenzek** [comment]
Why are you using full blending? Of course it's going to be slow.

**Comment by stenzek** [comment]
Okay, Jordan informed me that the lighting needs it.

Unless it can be captured in a dump, I'm inclined to say it's working as expected. The linked PR was not only a performance improvement, but also a correctness fix.

**Comment by refractionpcsx2** [comment]
I tried my darndest this morning to reproduce your bug, and I can't do it.

Are you running any patches or anything? Because otherwise I have no idea how you've managed it.

**Comment by DonelBueno** [comment]
Maybe it's specific to the GTX 1000 series, that's the only thing I can think of.

**Comment by stenzek** [comment]
There's no GPU specific code in pcsx2. Only NVIDIA specific in general.

**Comment by DonelBueno** [comment]
I've finally discovered the cause: a texture pack. Disabling it make the performance go back to normal.

No idea why it didn't do that before PR #11010

**Comment by stenzek** [comment]
Probably because the texture pack has incorrect alpha, and it's resulting in different alpha ranges on the RT.
