### ISSUE TITLE
[BUG]: Graphical glitch in Crash Nitro Kart

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#11160]
### Describe the Bug

In Deep Sea Driving track there is a speed booster that is not rendered correctly, as shown in the picture below:

![image](https://github.com/PCSX2/pcsx2/assets/27839354/6713a1bb-a24e-461a-bedf-45ade8ffd21b)

### Reproduction Steps

Load the game -> Single Player -> Quick Race -> Easy or any other difficulty level -> Select Deep Sea Driving in the track selector and then select your character. The glitch is in the second speed booster, which can be reached very quickly from the starting line.

All this process should take less than 2 minutes to reproduce.

### Expected Behavior

The booster was supposed to render correctly as happens with the others. I'm not sure if other parts of the game are affected by this glitch.

### PCSX2 Revision

1.7.5756

### Operating System

Windows 10 (64bit)

### CPU

i5-10400

### GPU

GTX 1660Ti

### GS Settings

It affects all renderers as far as I've tested, so I don't think the GS settings are necessary.

Thank you so much for your time and work.

### Logs & Dumps

[CNK.zip](https://github.com/PCSX2/pcsx2/files/15146369/CNK.zip)

**Comment by JordanTheToaster** [comment]
Going to need a savestate in that spot.

**Comment by dezraj** [comment]
Ok, here it is:
[SLUS-20649 (8F943CF3).zip](https://github.com/PCSX2/pcsx2/files/15146429/SLUS-20649.8F943CF3.zip)

Thank you for your super fast reply.

**Comment by JordanTheToaster** [comment]
> Ok, here it is: [SLUS-20649 (8F943CF3).zip](https://github.com/PCSX2/pcsx2/files/15146429/SLUS-20649.8F943CF3.zip)
> 
> Thank you for your super fast reply.

Fixed in 11161

**Comment by dezraj** [comment]
Thank you so much for the fast solution.

By the way, I suppose the title of this game is incorrect in the game database. The game is currently named Crash Bandicoot Nitro Kart, but I think the correct title is just Crash Nitro Kart. Anyway, thank you again for your work.
