### ISSUE TITLE
[BUG]: Code Lyoko: Quest For Infinity invisible text

### ISSUE THREAD

**Issue by Thebestsilver7** [PCSX2/pcsx2#11174]
### Describe the Bug

The game texts look fine, however, the save data texts are not visible, the box looks like it has no content inside. The first time you save the game you get a Yes/No option, and you can't see what you are replying to as you don't see that text either.
![codelyokoPS2saveIMG2](https://github.com/PCSX2/pcsx2/assets/33263205/457e404c-c127-42d6-b7d9-94a18b60833f)
![codelyokoPS2saveIMG3](https://github.com/PCSX2/pcsx2/assets/33263205/c3a33a00-0681-4e0d-a096-cf4203354028)

### Reproduction Steps

Receive the first save game dialogue automatically or visit the save game menu in the game..
![codelyokoPS2saveIMG1](https://github.com/PCSX2/pcsx2/assets/33263205/d1a6e134-f92f-4d42-81ef-f3402191161f)

### Expected Behavior

The game should display the text of the dialogue boxes mentioned above.

_(Screenshots taken from YouTube gameplay of what it should look like.)_

![image](https://github.com/PCSX2/pcsx2/assets/33263205/504d8a50-b569-4e47-9762-59023a232c12)
![image](https://github.com/PCSX2/pcsx2/assets/33263205/6a773ada-6f20-4feb-b586-20dafd3b358e)

### PCSX2 Revision

v1.7.5760

### Operating System

Windows 10 (64bit)

### CPU

i7-5820

### GPU

Nvidia Quadro M2000

**Comment by refractionpcsx2** [comment]
I think I got a GS dump of this ages ago and it was doing it even on my PS2 with the GS dump, which likely means this is a core bug.
