### ISSUE TITLE
Growlanser - Heritage of War :  Incorrect depth of models in hardware mode.

### ISSUE THREAD

**Issue by Kolrath** [PCSX2/pcsx2#1117]
Didn't see this posted anywhere on the Github issue tracker so I figured I'd put it up here.

In the game "Growlanser - Heritage of War" there seems to be an issue involving the depth that models are rendered at in comparison to the background and foreground of a scene.

When using hardware mode 3D models are ALWAYS shown above any 2D images that make up the background or foreground.  In the screenshot below you can see that the player characters model is visible overtop of the barrel and tree which he should be standing behind.
![growlanser - heritage of war - hardware mode](https://cloud.githubusercontent.com/assets/8617529/12314955/8d5529f0-ba43-11e5-86de-6d6d69845e7b.png)

In software mode the layer is working correctly with the player model being draw ontop of the background image but behind the foreground images of the barrel and tree.
![growlanser - heritage of war - software mode](https://cloud.githubusercontent.com/assets/8617529/12314957/9661821e-ba43-11e5-999a-99260a38ee74.png)

I wasn't able to check any further to see if software mode is always correct or if it to ever has issues.  Unfortunately the performance in software mode varies too drastically for me to test much.

When doing research on this issue I only found a few brief postings from about 2012 and the only potential solutions mentioned were to run it in software if it performs well enough or to wait for Directx10 to be added as it was believed that it would be capable of addressing the layering issue.

I tried messing around with the various hack options available to see if anything could be done to help alleviate the depth issues, but there were no visible changes of any kind.  Also tested the game while using a freshly installed default build of both the latest stable and the latest beta build set to maximum accuracy to verify whether or not it could be tied to something like a speedhack or altered setting.  No luck in either case.

If any further information is required feel free to let me know.  I hope its possible that this issue can be fixed.

**Comment by prafullpcsx2** [comment]
Depth issues are known to be fixed in Opengl mode with HW depth option ticked. Have you tried it yet? Please try with opengl mode and confirm whether the bug still persists.

**Comment by Kolrath** [comment]
Went back and double checked using OpenGL(Hardware) as the graphics plugin choice.  Tested with the "Hardware Depth" option ticked as well as unticked.

Either way the results were exactly the same as the original posts hardware mode screenshot.  Bug still persists and all models are still displayed overtop of all 2D elements such as the background and foreground.

**Comment by Kolrath** [comment]
Figured I'd post again with an another update... I actually had some progress even...

Firstly, in my initial posting I forgot to mention that the specific version of the game I was testing this all on is the NTSC-U region release of Grownlanser Heritage of War.  PCSX-2 shows it as being SLUS-215.  Just incase this is one of those odd instances where the region / version of the game applies in some fashion.

I had never really messed around too much with OpenGL mode because I have an AMD GPU and I always see this error message in the log...
"Buggy driver detected, GL_ARB_separate_shader_objects will be disabled
Note the extension was fixed on Mesa 11.1, you will need a manual overwrite to use it
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_separate_shader_objects is NOT SUPPORTED
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_copy_image is available
INFO: GL_ARB_buffer_storage is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_clip_control is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available
OpenGL renderer is slow on AMD GPU due to inefficient driver. Sorry."
... and since it says it will be slow, and that seperate shader objects aren't supported, I generally ignored it in favor of using Directx11 which usually runs well for me.

However, since it was stated that OpenGL(Hardware), specifically with the Hardware Depth setting, is useful for fixing depth related issues and I had some free time lately I decided to hop in and mess around with it a bit more to see if I could get any kind of results.


(I tried to take screenshots, but unfortunately when I'm using OpenGL(Hardware) any screenshots I take simply end up being entirely black.  So my apologies, but this will all just be text.)

In OpenGL(Hardware) mode having the Hardware Depth option ticked or unticked produces the same results as in the initial posting of Directx11(Hardware) where the model depth is incorrect.

But, if you have Hardware Depth ticked and the Hardware Hack - Preload Data Frame enabled the models seem to be rendering at the correct depths and matching up with Software mode.  This only works with both the hack and the depth option ticked, if the depth option is unticked then the models are still rendered incorrectly.

So it seems that the Preload Data Frames is useful in addressing the model depth issue!  Though I'm unsure why or to what degree it it "fixes" the problem.  

According to the mouse-over description, Preload Data Frames "Uploads GS data when rendering a new frame to reproduce some effects accurately.  Fixes black screen issues in games like Armored Core: Last Raven."

This stuff is all pretty much "black magic and arcane arts" to me so I don't really know what anything is actually doing specifically, but I hope that information might be helpful in giving one of you "rocket surgeons" with more knowledge and ability at least a potential starting point for solving this issue.

I have only checked the very starting scene / level in the game.  I haven't progressed beyond that screen to test whether or not it "fixes" all model issues or just some.  Since I have an AMD GPU and OpenGL doesn't sound like it gets along with it well I didn't want to test further and risk reporting something as an emulation issue when it may actually just be a conflict between that plugin and my AMD drivers.  If anyone out there doesn't have this AMD / OpenGL issue and would like to test it out further I'd be curious to know the results.  Or if there is a way to fix the conflict with AMD / OpenGL I could try to test further myself when I get more time.




For the sake of being as complete as possible I tried testing the game out using Directx11(Hardware) with the Preload Data Frame hack enabled.  Unfortunately, no dice... the issue with incorrect model depths still occurs.


As a side note, while testing the OpenGL(Hardware) plugin I did find that setting the Bilinear filtering option from Bilinear (Forced) to Bilinear (PS2) "fixed" a lot of the black lines and gaps between sprites.  Sadly, it only marginally helped with addressing the gaps on the animated portions of the character faces on 2D dialogue / menu screen sprites.  

None of the other things that commonly address sprite gaps and black lines, like the Half-Pixel Offset, the Sprite Align, Round Sprite, or Sprite, did anything noticeable at all.  With the exception of the Wildarms Offset which, oddly, causes all the 3D models not to render at all.  So unfortunately, it would seem that even if the model depth issue can be solved the sprite gaps will likely persist.  

Directx11(Hardware) was the same when it came to attempting to address the black lines and sprite gaps with the exception that the Wildarms Offset hack doesn't cause the 3D models to no longer be shown.



I think thats about the extent of my ability to get results.  If anything else needs tested in regards to this please let me know.  I'll be happy to help if I can.

**Comment by willkuer** [comment]
@gregory
Does peoload data frame has any drawbacks? Does it crash rendering for other games or is quite demanding? Maybe one could change the default value to enabled?

**Comment by gregory38** [comment]
@Kolrath,
Separate shader object isn't important because the extension is optional.

Sprite gaps are maybe not sprite gaps ;) but interpolation issue. I added some hacks to mitigate it for flat sprites, but you screw if the game uses 2 triangles to render a rectangle texture. Anyway, upscaling is just a PITA.

So yes, it seems the game need both depth support (well depth effect) and the "preload frame" hack. The latter isn't really a hack. It just properly initialize the target. Normally GSdx just left garbadge with the hope that games will just do a reset of it anyway. And as a matter of fact most games render first a black screen. However most != all, and so games reuse old target data. It is quite sensible on the rendering and it could badly impact the performance. So it is disabled by default. But maybe it will work well enough, I really don't know.

**Comment by Kolrath** [comment]
@gregory38 
Thanks for the response.

When you say that the "separate shader object" isn't important because its optional, what does that entail exactly?  I can understand that optional would mean its not required for the game to be playable, but will certain effects or anything be missing?
I tried checking around the PCSX2 forums and the next, but couldn't find anything out about it.

Also on that same topic, is there anything that I can do to get it supported despite me using an AMD card?  
I see that the log says "Note the extension was fixed on Mesa 11.1, you will need a manual overwrite to use it", but I couldn't find any further information regarding this on the PCSX2 forums or anywhere else.  

If its talking about the AMD graphics drivers themselves, I'm currently using the last AMD drivers which were available right before AMD swtiched everything to their "Crimson" series of drivers.  Specifically "AMD-Catalyst-15.11.1Beta-64Bit-Win10-Win8.1-Win7-Nov14". I haven't gotten Crimson because some other software I use has issues with it and I've had plenty of friends telling me horror stories about them and recommending that I wait till more of their issues are ironed out.

In regards to the lines / sprite gaps, these are some screenshots of it...
![growlanser - heritage of war - sprite gaps 1](https://cloud.githubusercontent.com/assets/8617529/12451323/b5fd3394-bf56-11e5-8ede-19ab86e6722a.png)
![growlanser - heritage of war - sprite gaps 2](https://cloud.githubusercontent.com/assets/8617529/12451333/bdc609ac-bf56-11e5-8f06-7151fe19d352.png)
Those are screenshots taken with the Bilinear Filtering set to Bilinear(PS2).  The effects are less than what occurs with it set to Bilinear(Forced) but its still pretty crazy.  Resolution was set at 4x Native.

I didn't experiment with the lines shown on that first screenshot of the intro / map, but with the character sprite in the menu I tested all the usual hacks that I've used to address similar issues in other games, even the previous Growlanser games, and had no noticeable results.

As for whether the issue is sprite gaps or an interpolation issue... that is, sadly, well beyond me.  Its all total wizardry to me so I wouldn't know the difference.  When I see an issue that looks like that in a game I just call it "lineage problems", "black lines", "or sprite gaps" because I don't know any better than to call it like I see it.... and for me all I see are sprites with lines or gaps between sprites.

Is there any official term in use for this "line problem" so that if I ever have to discuss someone who isn't a caveman like myself they'll know what I'm talking about?

Since none of the usual hacks are having any effect on this games "line" problem... would I be correct in assuming that there isn't any solution or potential work around?  Aside from the obvious solution of just not using any upscaling and running it in native resolution of course.  Is there perhaps an obscure hack or anything else that that I may have missed testing out?

Just for further clarification on the "Preload Frame" explaination... am I roughly correct in interpretting what you're saying as that its essentially just doing a screen / graphics data clear between each rending to the screen to prevent garbage data from being displayed or read?  

Aside from the potential impact on performance is there any other possible issues to be on the lookout for when having "preload frame" enabled?  

It wasn't an option that I've ever used before, and I don't even think it was available last time I played through a game, so I don't know what if anything to look out for.  I'm primarily concerned about things that might appear to be an emulation issue, but are actually just a result of that setting being used, kinda like the "sprite gaps" that can result from upscaling, as I don't want to risk incorrectly report something as an issue when its not.

Regarding the model / depth issue in general...
Since its possible to get it working on OpenGL(Hardware) mode does that mean it would be possible to also get it working on Directx11(Hardware)?

With Dx11(H) the "Preload Data Frames" option being enabled or disabled doesn't change anything with the model issue.  It seems that only in conjunction with OpenGL's "Hardware Depth" option does it have an results.  Is the hardware depth option highly specific to the OpenGL(H) rendering works or would something like that be able to also be added into Dx11(H)?

Thanks once again for the response!  I really appreciate it.  Sorry, for all my questions and annoying longwindedness... I'm just always curious, trying to understand things better, and I try to be as thorough as possible when reporting anything.

**Comment by gregory38** [comment]
```
When you say that the "separate shader object" isn't important because its optional, what does that entail exactly? I can understand that optional would mean its not required for the game to be playable, but will certain effects or anything be missing?
```
optional means faster with it, slower without it. SSO allow to compile only the fragment shader. Whereas the old method requires to recompile the vertex shader (+ geometry shader). (that being said extension doesn't seem to improve perf on amd anyway)
A bug was reported on AMD, I'm still waiting a confirmation. The mesa driver (linux) is working.

Upscaling is just a big hack. Unfortunately it create interpolation/line issues. I try to add more hack in the mix to reduce the effect. It works on some game but not all of them. So sorry, but I'm afraid, I can't do better.

Preload frame just reuse the data of a previous rendering.
Without the hack: do rendering 1; create a new framebuffer; do rendering 2
with the hack: do rendering 1; create a new framebuffer; upload rendering 1 data into the framebuffer; 
do rendering 2.
I don't know the impact. Normally it must be safe but GSdx is very very complex.

Technically depth support could be implemented in DX11 but someone need to do it. Until then, it is openGL only. However the accurate blending which is often used with depth effect can't be done in DX11 (blame MS, maybe DX12).

Anyway, you can try openGL with AMD. If it is too slow, you can switch back to DX11.

**Comment by Kolrath** [comment]
I wanted to drop in again quick to post a bit more information incase its of use to anyone else...

I did an entire playthrough of Growlanser Heritage of War using build "pcsx2-v1.5.0-dev-72-gc73d626-windows-x86" and the OpenGL Hardware graphics plugin.

The game is entirely playable using OpenGL Hardware and it fixes the depth issue throughout.  I encountered no areas of the game which were unplayable due to rendering or otherwise.  No lingering depth issues occured either.  There were only a few minor issues and where possible I tested them in comparison to Directx11 Hardware to see if there was a difference and also found any viable workarounds for the situations where applicable.

Issues encountered:
1 - In comparison to Directx11 Hardware, OpenGL Hardware was much slower.  The game ran at ~100% at almost all times with the following exceptions.  Some menu screens would have random slowdowns, but aside from making the music sound off it wasn't an issue.  Any area with fog would run at reduced speed so combat, especially when magic was involed, would be slow as well as any dialogue audio but none of this ever affected playability of the game as such locations were few.  Playing in a window as opposed to fullscreen would have a noticeable impact on performance, especially in dialogue and combat.  It wasn't possible to "turbo" the game by setting the frame limiter to 120 fps as the game was always just teetering at 60 fps.  If you have a beastly computer compared to mine you may not encounter any of these slowdown issues and might even be able to use "turbo" without issue, but if you're on a low-end computer you may need to swap graphics plugins at times.

These issues weren't present in Directx11 Hardware so if speed / performance / or "turbo" is needed that is a viable alternative, though you will of course have to deal with the model depth issues during that time.

2 - Video cutscenes, whether triggered by storyline events or certain high level magic spells, will cause flickering graphics glitches when the video is over and the game returns to normal.  This is occurs whether you skip the video or let it finish on its own and its especially bad in areas where there is the 3D water effects present.  The flickering seems to be somewhat related to the model depth issues since the majority of times the parts of 3D models that are flickering are parts that would be hidden by 2D terrain.  This only seems to happen in OpenGL Hardware as testing with Directx11 Hardware I never was able to get this glitch to occur.  While its annoying when it happens its luckily very easily fixed.  Simply press F9 twice to cycle to software rendering and then back to hardware rendering again and the flickering will be gone until another video plays.  This wasn't an issue for the majority of the game, but nearing the final moments there are many enemies that can regularly cast spells that have a video so you may find yourself cycling rendering modes often.

3 - Its possible for the game to become locked up when doing the "Dungeon Girl" quests near the end of the game where you help the girl find the right well to build a "Secret Dungeon" in.  Normally, you can speak to merchants in or near the inns of towns to fast travel, but at one, maybe two, points during the end portions of the "Dungeon Girl" quest line the fast travel merchants become messed up.  Attempting to speak to one will either hang immediately when their dialogue should start or will open their dialogue window but display no text and hang.  The game continues going in them background as NPCs continue to mill about but the player is hung up and you have to reload your game.  I doubt this was an OpenGL issue as I hadn't double checked it with Directx11, but I figured I'd mention it just to be on the safe side.  I didn't find a solution to this issue occuring, but the simple workaround to it is to just avoid fast traveling and walk to required locations for the quest.  When the quest was finished , and the "Secret Dungeon" is built, the fast travel system worked fine again.  However, I'd advise being on the safe side and saving into a different save slot so you can go back and try again incase it stays broken.


Overall, the game was entirely playable without any issues that hindered enjoyment, playability, or completabilty of the game.  So if anyone out there was holding off on playing this game due to potential issues... you don't need to.


@gregory38 
Thanks for your previous response.  Also, you have no need to apologize for anything, especially any hacks that you or anyone else has managed to pull off.  Everything you guys have done has been amazing so far and I'm still blown away at how far this emulator has come and what all you guys have been able to do.  Looking forward to seeing the future of PCSX2 and any other projects you guys contribute to.

**Comment by bugseeker159** [comment]
Hello
I'm having trouble with Rockbein story arc
Whenever i open (or try to open) the menu, the game freezes and stays like that.
Any idea how i can fix this ?
