### ISSUE TITLE
[BUG]: Fullscreen speed is limited to 59.84 FPS even with speed limiter off (macOS)

### ISSUE THREAD

**Issue by checktext00** [PCSX2/pcsx2#11178]
### Describe the Bug

if you play a game or launch the bios, it will be limited to 59.84 FPS when in fullscreen **unless** you originally launch it in fullscreen and *never* exit fullscreen. if you exit, it will then show this bug

### Reproduction Steps

go to Interface > Game Display > enable Start Fullscreen
go to Graphics > OSD tab > enable Show FPS (and Show Speed Percentages if you like)

*not required but makes diagnosing easier, enable Interface > Game Display:
- Double-Click Toggle Fullscreen
- Render To Separate Window*

launch the ps2 bios and remove the speed limiter (tab hotkey by default?), now it goes up to a very high FPS, double-click or press the PCSX2 assigned hotkey to exit fullscreen **[note 1]** (FPS stays high, and now the bug is triggered), go back to fullscreen (FPS limit is now 59.84, at least on my MacBook as that's my native display refresh rate).

with a US/Japanese bios/game this will be 100% of normal speed, and with a European (PAL) bios/game 120%

**[note1]** using the macOS native green "traffic light" icon in the upper-left of the app window or using View > Exit/Enter Full Screen from the menu bar to **both** exit and re-enter fullscreen won't trigger the bug, so I guess that the bug is triggered specifically by PCSX2's "non macOS native" way to enter and exit fullscreen when using double-click or the PCSX2 fullscreen hotkey - my log shows `acquireRenderWindow() recreate=false fullscreen=false render_to_main=false surfaceless=false` when exiting (or `fullscreen=true` when entering) fullscreen the non-native way, and nothing when using the native macOS controls

----

This only happens when the actual content is being shown on the screen, if the fullscreen window is showing off-screen in another macOS "space" (you can switch between full-screen apps and spaces by swiping left or right with 3 or 4 fingers on a MacBook trackpad by default), it will remove the speed limit until you re-show the content

easy way to check this (with the system sound on), launch the ps2 bios, go to System Configuration > Language, click X to enter the language selector and hold left or right on the d-pad to cycle between language options. Now keep holding left or right and switch macOS spaces, the speed will increase (you can hear the cycling getting faster), switch back and it goes back to 59.84 FPS

### Expected Behavior

fullscreen shouldn't affect the speed limiter

### PCSX2 Revision

v1.7.5769

### Operating System

macOS 11 (Big Sur)

**Comment by stenzek** [comment]
Can't do much about this unfortunately, it's the OS/compositor limiting presentation rate, or more specifically, the rate at which drawables can be grabbed. Happens more frequently on external monitors.

**Comment by checktext00** [comment]
@stenzek hey I retried this with the new version of PCSX2 (v1.7.5865) and this bug is now fixed when using the Metal renderer, but there is a new bug where the Vulkan renderer will now only render at 50% speed when in fullscreen (for both PAL and NTSC titles, still on macOS 11 Big Sur)

I can open a new issue for that new bug if you like

**Comment by stenzek** [comment]
It's not a bug. Maybe just mailbox vs FIFO, but we really don't care about Vulkan on macos, it's only really there for debugging, and I'll probably drop it soon with the minimum version bump.
