### ISSUE TITLE
Why The Quick Version Jump?

### ISSUE THREAD

**Issue by Geyup** [PCSX2/pcsx2#1118]
HI,

A ```.9th``` of a version release change comes aftger a year, 1.3.1 to 1.4.0, and then only three days after the release of 1.4.0, there is 1.5.0 being worked on.

Why such a quick jump from 1.4.0 to 1.5.0?

thanks

**Comment by vsub** [comment]
The odd numbers are used for betas
0.9.6 - official
0.9.7 - beta
0.9.8 - official
0.9.9 - beta
1.0.0 - official
1.1.? - beta
1.2.? - official
1.3.? - beta
1.4.? - official
1.5.? - beta

When 1.6.? is released,then then will start using 1.7.?

**Comment by REJack** [comment]
i would say they use [Semantic Versioning](http://semver.org/)
the jump from 1.4.0 to 1.5.0 is because there are new features 
a 1.4.1 version would contain only bugfixes
a beta or releasecanidate info etc is after the version number like 1.5.0-dev tag

**Comment by willkuer** [comment]
There are no relevant new 'features'. Vsub is right. It was always like that. If an urgent bugfix occurs i guess one would rather add the lower version number of both, release and dev (1.4.0/1.5.0. --> 1.4.1/1.5.1) - at least this is how it was done for the 1.2 release. With other words odd and even numbers are a parallel versioning system that are always bumped at the same time.

**Comment by gregory38** [comment]
First this isn't a facebook wall. And then the release isn't 1.5.0 but 1.5.0-__DEV__ (emphasize is mine), see https://github.com/PCSX2/pcsx2/releases
