### ISSUE TITLE
[BUG]: PCSX2 no longer builds on Linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#11185]
### Describe the Bug

PCSX2 no longer builds on Linux (at least Ubuntu and downstream distros such as Mint), apparently due to insufficient libpng version (shouldn't correct version be in externals?).  The following exception is thrown to the build log:

```
CMake Error at /usr/local/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PNG: Found unsuitable version "1.6.37", but required is at
  least "1.6.40" (found /usr/lib/x86_64-linux-gnu/libpng.so)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.28/Modules/FindPNG.cmake:177 (find_package_handle_standard_args)
  cmake/SearchForStuff.cmake:14 (find_package)
  CMakeLists.txt:39 (include)
```

### Reproduction Steps

Attempt to build.

### Expected Behavior

PCSX2 builds properly.

### PCSX2 Revision

Bad build: b67b5556174fd50dc3ed0a28043e8f683d8111b1
Last known good build: b2b7fa36bbfa8aeb04aef79661263d1298a92ccf
(can bisect if needed)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.3

### Logs & Dumps

[build.log](https://github.com/PCSX2/pcsx2/files/15206503/build.log)

**Comment by stenzek** [comment]
Yes, it does. If it didn't, our CI wouldn't pass.

If you're using someone else's build script/package, you shouldn't be creating issues in our repo, as the template states.

Otherwise, follow https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux, including the dependencies build process.

**Comment by Shoegzer** [comment]
I'm not using anyone else's build script, I'm following the linux build process (which I helped to write).  In any event I see that a requirement to build dependencies has been recently added, and so I added the necessary steps locally.  I believe this is the only change since it last compiled successfully.  However, even after adding these steps there is still a build failure at least in Ubuntu/Mint distros.

[Here](https://github.com/PCSX2/pcsx2/files/15206608/build.log) is the corresponding build log from this attempt.

I'll bisect this when I have time tomorrow in case it helps.

**Comment by stenzek** [comment]
You're probably missing setting the prefix path, since it's searching the system instead of the deps directory.

The CI runners use Ubuntu 22.04, so Ubuntu is definitely fine.

**Comment by TellowKrinkle** [comment]
(You need `-DCMAKE_PREFIX_PATH=path-to-dependencies` so cmake finds the dependencies you built)

**Comment by Shoegzer** [comment]
Thanks @TellowKrinkle.  In the above attempt I had used `-DCMAKE_PREFIX_PATH="$PWD/deps" `, which is relative to the `pcsx2/build` directory. I believe that should have done it?

**Comment by stenzek** [comment]
The wiki page says to use `-B build`, and run `cmake` within the root directory. So `$PWD/deps` will point to the correct path. `$PWD/deps` inside the build directory, assuming you ran the deps build script in the root, won't.

**Comment by Shoegzer** [comment]
Thanks, that and a few other issues were fixed locally and it builds fine now.

Interesting approach to build deps within the project.  Building from scratch takes longer than it had previously (approx. 15- vs. 3-minutes on this test system) but I assume this was done to avoid complications with libraries among distros.

**Comment by stenzek** [comment]
It ensures consistency with versions across platforms. Windows/Mac needs to build them anyway, so it makes sense to have Linux on the same version, avoiding version-specific issues.

We don't bump versions that frequently, so it's not a huge deal for development. For Windows, we have a package that can be downloaded to avoid building deps completely. The build time for PCSX2 itself is actually lower, since glslang/libwebp/etc are no longer building as part of it.
