### ISSUE TITLE
[Feature Request]:  Make android support with mesa turnip

### ISSUE THREAD

**Issue by Dwisantosobk** [PCSX2/pcsx2#11191]
### Description

Please make android version with mesa turnip support.
I see this feature make good performance in some emulator.

### Reason

Because some people like traveling and need ps2 in their mobile phone. I hope pcsx2 team can make android version 

### Examples

[
![Screenshot_20240505_014948_Lime3DS](https://github.com/PCSX2/pcsx2/assets/86861327/19b9901f-daf3-4b3a-a0ab-2875f8aa2c7b)
]

**Comment by refractionpcsx2** [comment]
We have no interest in making an android version
