### ISSUE TITLE
[BUG]: Ratchet & Clank: Up Your Arsenal -- blurry 3D objects even with no anti-aliasing

### ISSUE THREAD

**Issue by Yasand123** [PCSX2/pcsx2#11194]
### Describe the Bug

The image looks blurry with default settings, the only way to make it sharp (meaning where I can see actual pixels with no interpolation) is when I have texture filtering in the rendering tap set to nearest. There's an important distinction here to be made, I am not talking about textures, I'm talking about 3D objects, their outline would look blurry if "texture filtering" is set to anything other than nearest, which should not be the case.

This happens when running at 1x internal resolution and with no patches.

I have Bilinear filtering set to none in the Display tap to avoid anything that might affect the sharpness. So this is completely a rendering thing, not a displaying thing.

No anti-aliasing is enabled.
"Anti-blur" setting does not affect this.

Image with Texture Filtering set to `Bilinear (PS2)` which is the default:
![image](https://github.com/PCSX2/pcsx2/assets/14009700/8e0a4d9a-4e34-4b3f-bc2a-333575ae947d)

Here's when Texture Filtering set to `nearest`:
![image](https://github.com/PCSX2/pcsx2/assets/14009700/06f16abb-cc75-4bc8-bbf7-9b04b319f3b1)

### Reproduction Steps

- Run PCSX2
- Launch the game
- Keep default setting
- Image is blurry

### Expected Behavior

Pixels should not be smeared or interpolated.

### PCSX2 Revision

v1.7.5782

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

3700x

### GPU

2060s

**Comment by stenzek** [comment]
This is a support issue, not a bug. Please use the forums/discord chat.
