### ISSUE TITLE
Customising user data/config dir on Linux

### ISSUE THREAD

**Issue by akien-mga** [PCSX2/pcsx2#1119]
Hi there,

I just packaged v1.4.0 for Mageia (a community-driven Linux distribution) and am trying it out currently. The first thing I noticed is that PCSX2 will create a user data dir in ```${HOME}/PCSX2``` to hold the bios, memcards, logs, etc. by default.

Some of those paths can be customized from the GUI, e.g. the path to the bios files, memcards, sstates, but I think not all of them. But mainly, there seems to be no option to redefine completely the path to the whole user data dir to use for example XDG_DATA_HOME (```${HOME}/.local/share/PCSX2```) or XDG_CONFIG_HOME (```${HOME}/.config/PCSX2```). Of course now that I write about it I can see that it would not be easy to redefine the path to the user data dir if it's the same dir that contains the config saying where it is ;)

Thus I would propose (for Linux, but it might be relevant for other OSes too) to put by default the main config file in XDG_CONFIG_HOME, which would have at least a config file that gives the path to the main user data dir as PCSX2 currently has it. The default value could stay ```${HOME}/PCSX2``` if it's what is deemed most convenient for most users (as you need to access it to dump the BIOS in it for example) - I can guess however that many Linux users like me will prefer to have this folder somewhat "hidden" and not cluttering the root of the ```${HOME}``` folder, and thus be able to redefine the path to the main data dir as e.g. ```${HOME}/.local/share/PCSX2```.

I haven't checked the source code myself yet to see how hard this would be to implement though, so feel free to comment. :)

**Comment by gregory38** [comment]
There is a cmake option to use xdg_config_dir

**Comment by akien-mga** [comment]
Oh thanks, I must have missed that. Closing then :)

**Comment by akien-mga** [comment]
For future reference, it's ```XDG_STD=TRUE```.
