### ISSUE TITLE
[BUG]: Vulkan Doesn't Support my Graphics Card Now?

### ISSUE THREAD

**Issue by goday33** [PCSX2/pcsx2#11200]
### Describe the Bug

In Pcsx2 v1.7.4886 I use vulkan for my Geforce 920m, but in in Pcsx2 v1.7.4887 and later versions when I use vulkan  and I try to launch a game it just crash and says “Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated.”

### Reproduction Steps

Use vulkan and launch any game.

### Expected Behavior

Game launching perfectly using vulkan as a renderer with my GPU

### PCSX2 Revision

Pcsx2 v1.7.4886

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
Please use the Discord for support in future but yes your GPU is far too old to use Vulkan.

**Comment by TellowKrinkle** [comment]
If you enable the log window, it'll print the missing required extensions to it.
