### ISSUE TITLE
[Feature Request]: natively support compressed memory cards

### ISSUE THREAD

**Issue by checktext00** [PCSX2/pcsx2#11205]
### Description

PCSX2 to natively create, read, and write zip-compressed memory cards. Zip is a good format as it's very portable, so any other app could work with it or the user can just unzip it to use it somewhere else

### Reason

each PS2 memory card is around 8MB, which is limiting if you want to create one memory card per game title. The same empty memory card zip-compressed is just 9KB (when using the macOS built-in right-click > Compress) and around 300-500KB with a couple of saves

### Examples

I think Duckstation has amazing memory card  support, because of the features it offers, which are really only practical with small memory card sizes. Hopefully PCSX2 could implement some of those features in the future as well like:
- separate memory card per game serial/title/file title (i know folder memory cards exists but they [have](https://github.com/PCSX2/pcsx2/issues/4870) [problems](https://github.com/PCSX2/pcsx2/issues/3918)
- use single card for multi-disc games

**Comment by Mrlinkwii** [comment]
may i ask what you mean by compressed memory cards?

**Comment by refractionpcsx2** [comment]
On windows you have NTSC compression which does this for you, but I guess linux/mac users don't have that pleasure.

**Comment by F0bes** [comment]
Linux users can use BTRFS if they really need the space.

**Comment by refractionpcsx2** [comment]
We don't implement that though, right?

**Comment by F0bes** [comment]
BTRFS would be an alternative to the EXT4 filesystem (think FAT32 vs NTFS). So we would support it no problem, it would be abstracted away from us.

**Comment by checktext00** [comment]
@Mrlinkwii I mean instead of saving a memory card as `Mcd001.ps2` and taking up 8MB you would save it as `Mcd001.ps2.zip` and take up ~300KB

If I had 100 games with one memory card each, I'd be using over 800MB when I could be using 30MB with compression. It's the same way that PCSX2 can read compressed `chd` format games, but just for reading and writing `.ps2.zip` memory cards

on some filesystems it does this sort of thing for you, true - but for example Batocera can run on exFat and that filesystem doesn't support compression. on macOS i'm not sure either, because it supports de-duplication if 2 files are exact copies, but i'm not sure about when they're just 90% copies (like memory cards)

**Comment by stenzek** [comment]
> but for example Batocera can run on exFat

Not our job to care about piracy ridden redistributors.

> macOS i'm not sure either

You could just use folder memcards.

I'm inclined to say this is a WONTFIX, because you can't randomly seek in a zip file, you have to decompress up until that point. Writes are more problematic, because you have to decompress the whole thing, update the sector that was written, then re-compress the whole file. Taking a second to save memcards might be fine for 8MB, but definitely not for 128MB.

So we'd have to devise some per-sector/block compression scheme, which would limit the ratio, since the window is much smaller. Then it wouldn't work with third-party tools, either.

**Comment by stenzek** [comment]
No, the zip index lets you jump between different **files** within the archive, not seek to arbitrary points within a **single file**.
