### ISSUE TITLE
[BUG]: Unhandled SIGBUS on game boot

### ISSUE THREAD

**Issue by andreicristianstroe** [PCSX2/pcsx2#11208]
### Describe the Bug

Using the provided AppImage, PCSX2 crashed upon booting a game. It goes to a black screen for a second and then crashes. Opening the AppImage through the terminal, the error is `Unhandled SIGBUS at 0x7e3d6917c647`. I tried resetting all settings, using all renderers (Vulkan, OpenGL and Software).

### Reproduction Steps

Run PCSX2 through the AppImage
Boot any game
PCSX2 will crash after about a second of showing a black screen

### Expected Behavior

Game should boot normally.

### PCSX2 Revision

v1.7.5788

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### Logs & Dumps

Forcing X11 instead of Wayland, due to various protocol limitations
and Qt issues. If you want to use Wayland, launch PCSX2 with
I_WANT_A_BROKEN_WAYLAND_UI=YES set.
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
*************** Unhandled SIGBUS at 0x7e3d6917c647 ***************
  0x005cf8571e3c37 CrashSignalHandler [/home/runner/work/pcsx2/pcsx2/common/CrashHandler.cpp:311]
  0x007e3d69058e1f
  0x007e3d6917c647
  0x005cf856d69f7f StrideMemCpy [/home/runner/work/pcsx2/pcsx2/common/../common/StringUtil.h:282]
  0x005cf856d69f7f CopyTextureDataForUpload [/home/runner/work/pcsx2/pcsx2/pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp:257]
  0x005cf856d69f7f Update [/home/runner/work/pcsx2/pcsx2/pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp:350]
  0x005cf856ce5b5b UpdateImGuiFontTexture [/home/runner/work/pcsx2/pcsx2/pcsx2/GS/Renderers/Common/GSDevice.cpp:385]
  0x005cf856e6e05b Initialize [/home/runner/work/pcsx2/pcsx2/pcsx2/ImGui/ImGuiManager.cpp:164]
  0x005cf856c5c8e3 OpenGSDevice [/home/runner/work/pcsx2/pcsx2/pcsx2/GS/GS.cpp:139]
  0x005cf856c5cd65 GSopen [/home/runner/work/pcsx2/pcsx2/pcsx2/GS/GS.cpp:302]
  0x005cf856a3f001 ThreadEntryPoint [/home/runner/work/pcsx2/pcsx2/pcsx2/MTGS.cpp:168]
  0x005cf8572022d4 operator() [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591]
  0x005cf8572022d4 ThreadProc [/home/runner/work/pcsx2/pcsx2/common/Linux/LnxThreads.cpp:237]
  0x007e3d690aa1ce
  0x007e3d6912b6eb
  0xffffffffffffffff
*******************************************************************

**Comment by Mrlinkwii** [comment]
what pc spec ? because it works for me

**Comment by stenzek** [comment]
This is something with your system, or the meme distro, because nobody else can reproduce this crash.

SIGBUS is probably a misalignment exception, but we're not calling any functions that mandate alignment.

**Comment by stenzek** [comment]
From the small tidbit of info I've been given about this, I'm wondering if it's a libc issue with meme distro, especially since this started appearing randomly out of nowhere.

What I do know:
 - The pointers and data getting passed in look sane.
 - It's a SIGBUS on a memory read. The read in this case is the imgui texture data. Not an NFS share, GPU memory, etc, or something that should actually result in a SIGBUS.
 - That leaves alignment exceptions. If someone can dump the value of `rdi`, or whatever register it's reading from on the crashing instruction (**and** provide a full backtrace from a debug build), I can confirm this.
 - If the source register is not aligned, then it is not our bug.

**Comment by A-w-x** [comment]
linux 6.8.9 change broke few things
https://gitlab.freedesktop.org/drm/amd/-/issues/3343 should be it

@andreicristianstroe downgrade to 6.8.8, confirmed working by another arch user

**Comment by andreicristianstroe** [comment]
I am indeed running 6.8.9, just tested on my laptop with a simillar software configuration and a Ryzen cpu and everything works fine.

Will try downgrading to 6.8.8 and post back.

Also, Duckstation exhibits the same problem with the same error messages.

**Comment by A-w-x** [comment]
the isssue is about amd gpus and not specific to pcsx2 or duck, other apps crash too, you can check it for more info

**Comment by andreicristianstroe** [comment]
Cannot test at the initial desktop configuration atm, just did a full system upgrade on my laptop which included glibc 2.39-4 and ran pcsx2 again, no change, games still run. The laptop also has an amd gpu, vega 10. The desktop also had a full system upgrade as of 6-7 hours ago, so it should be on the same software as the laptop.

**Comment by stenzek** [comment]
Kernel change would explain the SIGBUS. It was actually the other way around, a write, not read, AT&T syntax trolled me (just didn't update the post).

**Comment by AntonyZ89** [comment]
Same here, using Arch and Ryzen 7 5600X + RX 6600 XT, do you use a window manager? I'm using i3wm and I think this might be related but I have no clue where to go to solve it :((

**Comment by Mrlinkwii** [comment]
@AntonyZ89 this is an arch  issue see https://gitlab.freedesktop.org/drm/amd/-/issues/3343

**Comment by andreicristianstroe** [comment]
Looks like it's a problem with the kernel rather than arch specifically. Didn't try downgrading the kernel yet but I have upgraded my gpu to a rx 570, no other changes, and the problem still persists. On the amd igpu of my laptop it does not crash. None of those 2 systems have the option of rebar afaik.
