### ISSUE TITLE
[BUG]: intro video for Midnight Club is stretched and off-center

### ISSUE THREAD

**Issue by checktext00** [PCSX2/pcsx2#11212]
### Describe the Bug

The intro video for Midnight Club: Street Racing is stretched and off-center when the "Screen Offsets" setting (in Graphics > Display tab) is disabled (which it is by default)

This happens with software rendering as well as hardware

edit: I'm sorry to say I forgot that I also had the "Show Overscan" setting on, and when Show Overscan is off, this "glitchy" part of the intro video is hidden, so I don't really know if it qualifies as a bug

### Reproduction Steps

Play Midnight Club: Street Racing with the Screen Offsets setting off
edit: also Show Overscan needs to be enabled

### Expected Behavior

intro video should be centered and not streched

### PCSX2 Revision

1.7.5788

### Operating System

macOS 11 (Big Sur)

### CPU

Intel 64-bit

### GPU

Intel integrated

### Emulation Settings

edit: I also had Show Overscan enabled

#### How it should look (Screen Offsets enabled)
![MC-good](https://github.com/PCSX2/pcsx2/assets/158559026/102ca7b7-7e11-4e5b-8a75-089b1a373d22)

#### How it looks with a PAL version (Screen Offsets disabled)
![MC-PAL](https://github.com/PCSX2/pcsx2/assets/158559026/d929d943-ab33-4bcc-a6a4-0bb3f9410ec1)

#### How it looks with the NTSC version (Screen Offsets disabled)
![MC-NTSC](https://github.com/PCSX2/pcsx2/assets/158559026/a60b873d-2d47-48f4-9c8b-f5fa78c0d25f)

**Comment by checktext00** [comment]
I forgot that I also had "Show Overscan" enabled, edited my original issue

**Comment by checktext00** [comment]
I also noticed that when "Show Overscan" is off, the image gets stretched (aspect ratio isn't preserved) while hiding the "glitchy" part of the video. I don't know if that's also how a real PS2 behaves. I can add screenshots if requested

**Comment by refractionpcsx2** [comment]
That's working as intended, some games rely on screen offsets in situations like this, having them disabled it does its best but sometimes fails to display correctly, so may be better to use screen offsets in this game.

As for Overscan's ratio, I'm away, it's kind of on my TODO to sort out.

**Comment by checktext00** [comment]
@refractionpcsx2 cool, also I may have been wrong here:

> I also noticed that when "Show Overscan" is off, the image gets stretched (aspect ratio isn't preserved) while hiding the "glitchy" part of the video.

it's when Show Overscan is on and Screen Offsets is off, while Aspect Ratio is set to Auto Standard (4:3 Interlaced / 3:2 Progressive)

**Comment by refractionpcsx2** [comment]
yeah I never did any work correcting the aspect for overscan, though the normal aspects aren't technically correct either, so I need to look at them.
