### ISSUE TITLE
AMD OGL issues

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1121]
Gregory used to mention [GL_ARB_separate_shader_objects](https://community.amd.com/thread/194895)
Probably there are more (e.g. multithreaed optimization)

@bositman could you retweet that link to amd?
https://twitter.com/grahamsellers

**Comment by gregory38** [comment]
Please tweet it at graham sellers
Ask it if him or an AMD engineer can give it a look at the testcase.
Thanks you.

**Comment by bositman** [comment]
I don't understand what I'm supposed to do? :P

**Comment by ssakash** [comment]
he's asking you to tweet the [bug report](https://community.amd.com/thread/194895) to [graham sellers](https://twitter.com/grahamsellers) on twitter, not sure why he's specifically asking you,,,,

**Comment by gregory38** [comment]
Dont do it. Delroth fordward the bug report to his amd contact.
(and I want to keep my tweeter virginity ;) )

**Comment by gregory38** [comment]
@mirh 
So, did they add the fix in their Lara's driver ?

**Comment by mirh** [comment]
Uh, no, they didn't. 
I thought I already mentioned that on IRC.

**Comment by gregory38** [comment]
Let's close the issue. AMD will release a fix in the next major driver release.

**Comment by mirh** [comment]
Next™

**Comment by avih** [comment]
Not sure if that's how it "supposed" to be right now, but for me on AMD gpu it's not only slow, but also broken visually on many (most) games. That's what I see at my log:
```
3.x GL context successfully created
OpenGL information. GPU: AMD Radeon R9 M200X Series. Vendor: ATI Technologies Inc.. Driver: Core Profile Forward-Compatible Context 15.200.1046.0
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
OpenGL renderer is slow on AMD GPU due to inefficient driver. Sorry.
```

I didn't try many GSdx configurations, but currently, for OpenGL HW I have:
- CRC Hack level: partial
- Enabled HW depth
- Enabled Accurate date
- Blending accuracy: medium

**Comment by gregory38** [comment]
There is a bug in the AMD driver. I used to have tons of code in GSdx to workaround it. I decide to remove the workaround as AMD said they will provide a fix. My guess was 3 months of QA, but it seems to be more (they said that driver was fixed mid of January). So currently you can either use an old GSdx plugin, use Dx.

**Comment by avih** [comment]
Well, most GSdx progress happens with OpenGL, and the improvements which are being advertised many time refer to GSdx OGL, but if all AMD users are effectively excluded from all this progress until who knows when the driver can work reasonably well with the code, then.. well.. it's not great.

I didn't conduct a survey, but I'd imagine a fair amount of users use AMD GPUs. It's a shame to exclude them from this progress (and I'm not counting myself here actually, as I do have an nvidia system, but I like to test with AMD too occasionally).

**Comment by gregory38** [comment]
The not-yet compatible change was made begin of April (the 7th). (nearly 3 months after the AMD fix) You can still have most of the openGL niceties. You miss so far some depth fixes and soon a channel shuffle effect. But globally you have 90% of the stuff.

AMD (itself) said the driver was fixed but they need to finish QA before doing a public release. I don't know the frequency of AMD driver update but I guess it is a matter of a couple of months.

I'm sorry for AMD's user but they need to be patient.

**Comment by avih** [comment]
My main point is that drivers have bugs. I bet nvidia drivers have bugs too, and maybe you even worked around some nvidia issues too. Bugs will always exist. But developers typically try to work around them where possible such that users with buggy drivers could still use the application.

Now, I honestly don't have a clue how much effort/hackery it would require to make it reasonably useful for AMD GPUs and work around this issue, and I definitely can't tell you what to do with your time.

And neither of us can know when it would be fixed at the driver. Maybe in few months, maybe never.

While it's true that the DX renderers still work, and so do the OpenGL rendered until some weeks ago, you also cannot deny that by now the OpenGL renderer is more advanced than DX and that further improvements are likely to happen mostly at the OpenGL side.

Which means that AMD users are out of all this.

I totally understand you not wanting to work around it. But the bottom line is unchanged here. We're leaving AMD users out.

**Comment by gregory38** [comment]
https://community.amd.com/thread/194895
Quoting AMD:
```
The issue has been resolved and the fix will be part of a future driver release.
 In the meantime, if you use dual-source blending, don't use separate shader objects.
```
```
It missed the driver release in March (the one with Vulkan, etc. - which was 
already in lock-down when the fix was written.) It's scheduled for a future 
release. Keep in mind any public release goes through a lot of testing and
 QA! In the meantime, please use the workaround (i.e. don't use separate shader objects.)
```
Honestly if they never release the fix... I'm counting on all AMD's users to pressure AMD to release it. We will go to the twitter/facebook/redit road if it the only solution. So far I trust them, they said that they need more time, so let's wait. I've high hope that it will be release in the next release. And hopefully they release a driver every 3-6 months.

Yes all drivers have bugs but
* when I report bugs to Mesa, they fix it and release a fix
* when I report bugs to Nvidia, they fix it and release a fix
* Never report a bug on Intel Windows.
* when I report bugs to AMD, some stays in the limb. We spend time with Mirh to create a small testcase to AMD then to report it again and again to various place. Hopefully Dolphin helps us to ping an AMD guys. Otherwise, a Dx9 feature won't still be usable....

**Comment by avih** [comment]
> We will go to the twitter/facebook/redit road if it the only solution

:)

**Comment by mirh** [comment]
16.5.2 is out and still nothing. 
Anyway, I wonder if [this](https://community.amd.com/thread/198250) isn't also related.

**Comment by gregory38** [comment]
Well just ask them if they use separate shader object + dual source blending. 
Anyway so far they only release hotfix. We need a big driver release

**Comment by mirh** [comment]
See #1508.

**Comment by mirh** [comment]
Aaaand, we are go https://community.amd.com/thread/205798
@gregory38
