### ISSUE TITLE
[Feature Request]: Show covers in list view

### ISSUE THREAD

**Issue by ipkpjersi** [PCSX2/pcsx2#11226]
### Description

I would like to be able to show covers (cover images) in list view.

### Reason

It makes things easier being able to see the logo of a game so you can see right away which game you want to play rather than having to read text.

### Examples

Here is an example of this feature in RPCS3 showing the icons in the list view:
![](https://i.imgur.com/yn0rpOB.png)

You can see there is the icon right beside the name in the list view.

**Comment by stenzek** [comment]
Sorry, no, this whole require a second set of images, and with the size of rows, nothing would be legible anyway.
