### ISSUE TITLE
ADD :- ASYNC AUDIO AGAIN

### ISSUE THREAD

**Issue by VIKNESWAR-R** [PCSX2/pcsx2#11221]
### Describe the Bug

Without ASYNC AUDIO synchronization lot of bugs in most games please add again ASYNC Option

### Reproduction Steps

Without ASYNC AUDIO synchronization lot of bugs in most games please add again ASYNC Option

### Expected Behavior

Without ASYNC AUDIO synchronization lot of bugs in most games please add again ASYNC Option

### PCSX2 Revision

Latest PCSX2 Nightly 

### Operating System

Windows 10 (64bit)

### CPU

AMD RYZEN 3 3250U

### GPU

AMD RADEON VEGA 3 GRAPHICS

**Comment by RedPanda4552** [comment]
This does not help us understand at all what the issue is. Please explain what games have issues, what specific parts of those games have issues, what the specific audio bugs are, and how async mix would have fixed them.

Also, please include information about game performance (e.g. if the games are running full speed or not).

**Comment by stenzek** [comment]
If you can't be bothered to write a proper post, I can't be bothered to write a proper reply :)

No.

**Comment by VIKNESWAR-R** [comment]
BURNOUT REVENGE AUDIO AND VIDEO LAGS WHILE HITTING THE CAR WHILE IN TIMESTRECHED ON THE OTHER HAND IN ASYN MODE ITS WORK FINE

**Comment by VIKNESWAR-R** [comment]
THAN TELL ME THE BEST SETTINGS FOR PCSX2 NIGHTLY RUNNING AT 720P
MY PC SPECIFICATIONS:-
RYZEN 3 3250U
AMD RADEON VEGA 3 GRAPHICS
8 GB RAM
256GB SSD
WINDOWS 10 64 BIT

**Comment by VIKNESWAR-R** [comment]
> This does not help us understand at all what the issue is. Please explain what games have issues, what specific parts of those games have issues, what the specific audio bugs are, and how async mix would have fixed them.
> 
> Also, please include information about game performance (e.g. if the games are running full speed or not).

BURNOUT REVENGE AUDIO AND VIDEO LAGS WHILE HITTING THE CAR WHILE IN TIMESTRECHED ON THE OTHER HAND IN ASYN MODE ITS WORK FINE

**Comment by VIKNESWAR-R** [comment]
THAN TELL ME THE BEST SETTINGS FOR PCSX2 NIGHTLY RUNNING AT 720P
MY PC SPECIFICATIONS:-
RYZEN 3 3250U
AMD RADEON VEGA 3 GRAPHICS
8 GB RAM
256GB SSD
WINDOWS 10 64 BIT

**Comment by stenzek** [comment]
Please use the Discord server or forums for support, thanks.
