### ISSUE TITLE
[BUG]: widesreen games not working in full screen

### ISSUE THREAD

**Issue by Setsuna01Fr** [PCSX2/pcsx2#11227]
### Describe the Bug

when trying to play games like xenosaga or tales of legendia instead of having the 16/9 aspect ratio in fullscreen the aspect ratio is ok but croped 
Cf : ![Capture](https://github.com/PCSX2/pcsx2/assets/169517746/8c15bcdd-cd15-4079-9afe-61a11b0a0144)

i've tried D3D12, Vulkan, interlace settings, anabling and ddisabling widesreen hacks and no change !

### Reproduction Steps

launch a widesreen game

### Expected Behavior

have the game in fullscreen 

### PCSX2 Revision

v1.1.5798

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
This is not a bug. Please use the forums or discord server for support.
