### ISSUE TITLE
[BUG]: PCSX2 crash after choosing game

### ISSUE THREAD

**Issue by fifqaaa** [PCSX2/pcsx2#11224]
### Describe the Bug

The application shuts down immediately when I try to run any game 

### Reproduction Steps

1. Run PCSX2
2. Select any game
3. Wait few seconds
4. PCSX2 close itself

### Expected Behavior

After the choose, the game should run as usual

### PCSX2 Revision

v1.7.5793

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS Linux x86_64 (KDE Plasma)

### Logs & Dumps

*************** Unhandled SIGBUS at 0x7625571779b7 ***************
  0x006268ab21ac47 CrashSignalHandler [/run/build/pcsx2/common/CrashHandler.cpp:311]
  0x00762557051e7f
  0x007625571779b7
  0x006268aad9f41f StrideMemCpy [/run/build/pcsx2/common/../common/StringUtil.h:282]
  0x006268aad9f41f CopyTextureDataForUpload [/run/build/pcsx2/pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp:257]
  0x006268aad9f41f Update [/run/build/pcsx2/pcsx2/GS/Renderers/Vulkan/GSTextureVK.cpp:350]
  0x006268aad1ae2b UpdateImGuiFontTexture [/run/build/pcsx2/pcsx2/GS/Renderers/Common/GSDevice.cpp:385]
  0x006268aaea42cb Initialize [/run/build/pcsx2/pcsx2/ImGui/ImGuiManager.cpp:164]
  0x006268aac92fd3 OpenGSDevice [/run/build/pcsx2/pcsx2/GS/GS.cpp:139]
  0x006268aac93455 GSopen [/run/build/pcsx2/pcsx2/GS/GS.cpp:302]
  0x006268aaa74ce1 ThreadEntryPoint [/run/build/pcsx2/pcsx2/MTGS.cpp:168]
  0x006268ab239344 operator() [/usr/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../include/c++/13.2.0/bits/std_function.h:591]
  0x006268ab239344 ThreadProc [/run/build/pcsx2/common/Linux/LnxThreads.cpp:237]
  0x007625570a1e38
  0x007625571299c3
  0xffffffffffffffff
*******************************************************************

**Comment by Mrlinkwii** [comment]
dulplicate of #11208  , this is a arch issue this is an arch issue see [gitlab.freedesktop.org/drm/amd/-/issues/3343](https://gitlab.freedesktop.org/drm/amd/-/issues/3343)
