### ISSUE TITLE
[BUG]: 1.7 not applying widescreen patches on the fly

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#11235]
### Describe the Bug

1.7 has a bug where it acts like it's applying the "Enable Widescreen Patches" setting on the fly (it even prints a message to the OSD that says "1 game patches are active.") but it's not. You need to have had the "Enable Widescreen Patches" setting enabled BEFORE launching the game and then it works.

### Reproduction Steps

0. Make sure "Enable Widescreen Patches" is disabled.
1. Launch a game
2. Enable the "Enable Widescreen Patches" setting.

### Expected Behavior

When I enable the "Enable Widescreen Patches" setting, I expect the widescreen patch to be enabled.

### PCSX2 Revision

v1.7.5803

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Not a bug. If the patch is set to apply on ELF load, not constantly, then it's not going to apply until the game is rebooted.

**Comment by karasuhebi** [comment]
Thanks for explaining that!

A case could be made that this is bad UX though. Based on how PCSX2 is behaving, users are expecting for the patch to have been applied on the fly and it sounds like that's not always going to be the case.

Could a note be added to the OSD message so that it says "Some patches won't apply until the game is rebooted"

**Comment by stenzek** [comment]
Potentially.. you'd have to save a list of patches that were present on boot, and compare the current list against it.
But the reverse is also true - you can't "unapply" a patch after it's been applied once (for constant nor ELF-load).

**Comment by karasuhebi** [comment]
Are you saying we need to do this even to just add a line to the OSD message? I was thinking we could just add it in without having to do anything else.

I was looking at like 723 on Patch.cpp:
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Patch.cpp#L723

**Comment by stenzek** [comment]
And how would you know if there's any ELF-load patches that weren't applied before? You don't want to display "will apply on next reset" unconditionally on constant patch enable, nor on boot.

**Comment by karasuhebi** [comment]
I mean we can just adjust the wording to be less committal. Would it be okay if it said "Some patches might not apply until the game is rebooted" or am I missing something and that still does not meet the requirements?

**Comment by stenzek** [comment]
We try not to half ass things these days. If you're going to make such a change, do it properly.

**Comment by karasuhebi** [comment]
Understood. Just so I'm clear, what needs to be done in order for it to be considered as being done properly?

**Comment by stenzek** [comment]
> Potentially.. you'd have to save a list of patches that were present on boot, and compare the current list against it.

IMO it's not worth it. I guess another option could be to yolo apply on-load ELF patches if the ELF has already been loaded. Not like potentially crashing the game if it's overwritten that code is much worse than having a half-loaded patch :P

Or, I suppose, when the user checks the patch in game properties in the first place, check if the VM is running and the serial matches, and if so, prompt them to restart then.
