### ISSUE TITLE
[BUG]: GTA VCS - Water rendering bug on Windows + Vulkan + >1x Resolution Scale

### ISSUE THREAD

**Issue by Wolver32** [PCSX2/pcsx2#11238]
### Describe the Bug

Follow up of #10720, while testing the fix for RDNA3 cards for Windows + Vulkan I noticed that the water in GTA Vice City Stories is rendered incorrectly, with grey / black lines forming squares. Resolution Scale seems to be the culprit here, because native res looks normal. I haven't noticed if other areas of the game are affected, but it's extremely easy to spot it while Vic is in the water.
This again seems to be a Windows only issue, Vulkan + Linux renders everything correctly. Windows + DX12 is also fine. Wonder if it's again a RDNA3 specific issue given that RADV doesn't show any problem.

I'll leave some screens here:
- Windows + Vulkan + 8x Resolution Scale
![VCS_VK_Win](https://github.com/PCSX2/pcsx2/assets/130566900/8594dae4-e52b-489b-8743-b1e4d3325590)

- Windows + Vulkan + 4x Resolution Scale
![VCS_VK_Win_4x](https://github.com/PCSX2/pcsx2/assets/130566900/5436c122-047d-4e5c-95d0-6ac757e2bb3d)

- Windows + Vulkan + Native Resolution
![VCS_VK_Win_Native](https://github.com/PCSX2/pcsx2/assets/130566900/800f4cc2-d877-4462-9c39-4266eecf705e)

- Windows + DX12 + 8x Resolution Scale
![VCS_DX12](https://github.com/PCSX2/pcsx2/assets/130566900/81fe1f67-c630-4c78-8220-7e994c69c00c)

- Linux (Fedora) + Vulkan + 8x Resolution Scale
![VCS_Linux](https://github.com/PCSX2/pcsx2/assets/130566900/6b58b9b5-c760-4fbd-a197-e20bdb1992c3)

And I'll also leave 2 GS dumps that I took from Windows (remove the final .zip extension):
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240512171505.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/15286803/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240512171505.gs.zst.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240512171533.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/15286806/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240512171533.gs.zst.zip)

### Reproduction Steps

Set Vulkan backend on Windows with >1x Resolution Scale and go into the water in GTA Vice City Stories.

### PCSX2 Revision

v1.7.5803

### Operating System

Windows 11

### CPU

Intel Core i5-12600KF

### GPU

AMD Radeon RX 7800 XT

**Comment by stenzek** [comment]
Fatal Frame II has the same issue, it's on the triangle edges. Already tried a bunch of things to work around it, extra barriers, splitting tris, no dice. So driver bug most likely.

![image](https://github.com/PCSX2/pcsx2/assets/11288319/69d251b5-0346-4828-b3d0-61f4ab73dd72)
