### ISSUE TITLE
[BUG]: Big Picture Mode shows advanced features in Graphics section

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#11239]
### Describe the Bug

With the option to show advanced settings turned off, Big Picture Mode still shows advanced settings in the Graphics section.

### Reproduction Steps

Turn off the option to show advanced settings
Go into BPM and verify that it shows some advanced settings

### PCSX2 Revision

v1.7

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
What "advanced features"?

**Comment by karasuhebi** [comment]
These
![image](https://github.com/PCSX2/pcsx2/assets/6857825/030bc986-2ef9-47e9-98aa-796d4d76923a)

**Comment by kamfretoz** [comment]
> These. And as you can see, the option is turned off.

Should be fixed by #11244

**Comment by karasuhebi** [comment]
Thanks!
