### ISSUE TITLE
[Feature Request]: Adding customization screen for CRT-Lottes shader

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#11231]
### Description

It would be much more comfortable to have a graphical customization screen for post-processing shaders (crt-lottes in particular) like it was made for DuckStation.

### Reason

Will make post-processing shaders settings (current and future ones) easier to handle.

### Examples

The same in DuckStation:

![Screenshot from 2024-05-11 20-09-02](https://github.com/PCSX2/pcsx2/assets/96921167/7de7b2be-5133-4a84-8aea-e8578d7d7efc)

![Screenshot from 2024-05-11 20-26-18](https://github.com/PCSX2/pcsx2/assets/96921167/00b6f6e9-367b-4149-b86c-76ebbf29b5eb)

**Comment by stenzek** [comment]
Not possible with the current implementation.

It'll happen when I ditch GSDevice for DS's GPUDevice. But no immediate plans for that.

**Comment by NU11V01D** [comment]
Can we at least get some way to use aperture grille instead of shadow mask? Sorry for commenting in such an old thread.
