### ISSUE TITLE
[BUG]: Hitman 2 - Silent Assassin Texture filtering issue in HW mode

### ISSUE THREAD

**Issue by Wdub888** [PCSX2/pcsx2#11240]
### Describe the Bug

In Hitman 2: Silent Assassin there is some inaccurate texture filtering in HW mode that isn't present in SW mode.

Hardware (Vulkan):
![Hitman 2 - Silent Assassin_SLUS-20374_20240512220124](https://github.com/PCSX2/pcsx2/assets/121665302/8e22ecf3-446b-43db-8b92-86f0547fabdd)

Software:
![Hitman 2 - Silent Assassin_SLUS-20374_20240512220056](https://github.com/PCSX2/pcsx2/assets/121665302/aa82853b-7f27-4e69-923a-883e44e43212)

### Reproduction Steps

Changing from HW mode to SW mode

### Expected Behavior

More accurate to SW mode.

### PCSX2 Revision

v1.7.5803

### Operating System

Windows 10 (64bit)

### CPU

i5-1035g1

### GPU

Nvidia GeForce MX130

### Logs & Dumps

GSdump:
[hitman2.zip](https://github.com/PCSX2/pcsx2/files/15287304/hitman2.zip)

**Comment by bigol83** [comment]
It needs Mipmapping Full + Trilinear Ps2 Filtering

**Comment by Wdub888** [comment]
thanks! it got fixed.

**Comment by stenzek** [comment]
Does it actually *need* mipmapping/trilinear? Is any part of the game broken without it?

Most games will behave like this, because the current default in HW is to have mipmapping off.
