### ISSUE TITLE
Test Drive  Unlimited (E) - Different Graphics behaviour on HW mode. cars reflections.

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#1125]
-- PCSX2 1.5.0-20160117163859 - compiled on Jan 17 2016
-- PCSX2 options: Defaults, no settings modifications affect the issue.
-- Operating System =  Microsoft Windows 10 Home (build 10586), 64-bit
-- CPU name         =  Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
-- GPU: GeForce GT 755M/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: 
-- Bios Found: Europe  v02.00(14/06/2004).

Running at native resolution, while software mode is the most accurate option but also quite demanding (with my hardware did not reach full speed). I notice actually DX9 behaves better with cars texture reflections than OpenGL, and DX11 which basically are not rendered at all on OpenGL, and DX11.

I wonder if some features are missing on most modern backend, specially OpenGL one, with by far is becoming quite good.

I added images that shows the difference.

Software Mode:
![image](https://cloud.githubusercontent.com/assets/3447089/12379495/5d26b688-bd5c-11e5-831a-7ecc68ba48c5.png)

OpenGL:
![image](https://cloud.githubusercontent.com/assets/3447089/12379498/86d4c006-bd5c-11e5-95ce-931b3cad8593.png)

DX11:
![image](https://cloud.githubusercontent.com/assets/3447089/12379500/9c0155a2-bd5c-11e5-9bbc-56c9bf263eed.png)

DX9:
![image](https://cloud.githubusercontent.com/assets/3447089/12379501/b1fdaf90-bd5c-11e5-8b85-da0a3d992b08.png)

**Comment by gregory38** [comment]
Did you test the blending accuracy option?

**Comment by willkuer** [comment]
Also please use crc hack level none or partial with ogl (hw)

**Comment by MarcoEstevez** [comment]
Yes, crc hack set to none makes DX9 looks similar to DX11, the pick I took was on CRC level "Partial (OpenGL Recomended)".

so then I guess... the fact to have some reflections on DX9 is probably due a hack, that only applies to that backend apparently, or?.

BTW I tried Blending Accuracy set to "Ultra" with OpenGL, still no reflections.

**Comment by gregory38** [comment]
Wait. In which CRC level do you have the reflection on dx9?

**Comment by MarcoEstevez** [comment]
CRC level "Partial (OpenGL Recomended)".

After changing it to none, reflections were gone on DX9

**Comment by willkuer** [comment]
This is the opposite of what the hacks normally should do.
CRC None means emulate everything (even if broken)
CRC Aggressive means emulate almost nothing

That's why everybody is confused.

OGL, Dx10 on CRC none don't show the reflection?

**Comment by MarcoEstevez** [comment]
Sorry iphone sucks

**Comment by gregory38** [comment]
And what is the status of the minimal level?

**Comment by MarcoEstevez** [comment]
Ok, Ive done more tests.

DX9: CRC Level none  (flat textures)
![image](https://cloud.githubusercontent.com/assets/3447089/12399807/6f00778e-be1c-11e5-8f17-e35e2a5c3482.png)

DX9: CRC Level: Minimum  (shows reflects on car textures)
![image](https://cloud.githubusercontent.com/assets/3447089/12399836/a59e4866-be1c-11e5-8c58-1a7d2d210fc2.png)

DX9: CRC Level: Partial  (shows reflects on car textures)
![image](https://cloud.githubusercontent.com/assets/3447089/12399921/332cc25c-be1d-11e5-829d-b57b76f0cb51.png)

same situation (reflections) on all rest of levels and DX9. Full and Aggressive.

I repeated same above tests against DX11 and OpenGL, flat colors textures for the cards on all CRC levels no difference.

**Comment by willkuer** [comment]
I think it would help if you could create a gs dump of this scene and upload it somewhere.

**Comment by MarcoEstevez** [comment]
Here you have, I took two dumps for comparison purposes, DX9 and OpenGL.

https://drive.google.com/file/d/0ByJrCj2X0ZpAbzZoNE50MlZvYlE/view

**Comment by willkuer** [comment]
Thank you very much. Like this gregory can directly look into the problematic stuff.

Actually you dont need to create several dumps. Dumps are not videos (gs output) but the data from pcsx2 to the plugin (gs input). So settings normally.dont affect the gs dump.

**Comment by MarcoEstevez** [comment]
I see now, so they are like a list of commands, then every plugin interpret these on his own fashion, right?, good to know.

**Comment by gregory38** [comment]
could you test the preload frame data hack (or a similar name)

**Comment by MarcoEstevez** [comment]
Yes, It did work. many many thanks Gregory.

I opened this issue cause I thought was something missing on modern graphics APIs, but I'm suspecting now it is just a hardware issue, I have saw a tremendous improvement on OpenGL back-end, I just remember not many months back DX11 was far superior than OpenGL one and now Is right the opposite, in particular that game looks great aside, the little flat card color surface, but in general activating hacks broke more things ( too blurry and foggy scene ) than fixes IMO, so please feel free to close that issue if you consider. I now improvements are always on your road-map, so eventually HW will come accurate as SW at some point. or computers much powerfull ( SW mode looks so awesome, isn't it  :-D ) 

Here how it looks on OpenGL.

OpenGL + "preload frame data hack".
![image](https://cloud.githubusercontent.com/assets/3447089/12402844/018c9156-be30-11e5-8dee-abf7c20818c5.png)

OpenGL without HW hacks
![image](https://cloud.githubusercontent.com/assets/3447089/12402956/d0f44c86-be30-11e5-96e3-77dc8f0768d6.png)

Software Mode
![image](https://cloud.githubusercontent.com/assets/3447089/12402970/f82e4252-be30-11e5-9bb0-37de637602bc.png)

**Comment by willkuer** [comment]
Btw you have crt shaders enabled. The horizontal stripes are not part of the emulation or game but only additional postprocessing. You might want to look into gsdx hotkeys how to cycle through them. I think it was f7.

Interesting that missing preload hack leads to crc hack inversion.

**Comment by MarcoEstevez** [comment]
I Know, I love those filters, PCSX2 tastes just like the real thing, looks even better at full screen.

**Comment by gregory38** [comment]
Is the color correct? It's hard to say with the extra shader.

**Comment by willkuer** [comment]
Btw. you still have skipdraw at 50(!) and TC offset nonzero...
It's impressive how nice this game looks at native though..

**Comment by MarcoEstevez** [comment]
@gregory38: I'll test "OpenGL + preload frame data" and "SW", both without shaders being applied when I got home, but havent notice any diference regarding colors, I saw hack seems to introduce like and extra brightness layer, Could I have any other settings under hacks that affects?

@willkuer. You want me to change any other settings under "Hacks Configuration" dialog?, I don't remember have changed ever any of those settings before.

**Comment by willkuer** [comment]
Skipdraw and tc offset (x and y) are 0 by default. Tc offset probably doesn't harm much in native resolution. However skipdraw can remove a lot of effects.

**Comment by MarcoEstevez** [comment]
I did change tc offset and Skipdraw... all to 0, while keeping preload frame data, and remove postprocssing shaders.

OpenGL + Hacks  (no crt shaders)
![image](https://cloud.githubusercontent.com/assets/3447089/12432236/890e87a4-befa-11e5-92e0-ed4223600ae7.png)

Software Mode ( no crt shaders)
![image](https://cloud.githubusercontent.com/assets/3447089/12432321/ee4b23ca-befa-11e5-9e47-410b744fcd85.png)

Looks like old settings skipdraw=50 and tc offset were badly contributing or messing up graphics, I can really say now HW is so close to SW one. I did not notice any issues with shadows, textures, or graphical glitches, impressive!!!!!. I can only say great job Guys.

another shot with reflections on hardware mode.
![image](https://cloud.githubusercontent.com/assets/3447089/12432636/a565edd2-befc-11e5-9c3a-a44654de2c49.png)

Thanks.

**Comment by gregory38** [comment]
Could we do a summary (without the picture) or the required option to enjoy the game on openGL
* CRC ?
* accurate ?
* HW hack ?

Thanks you.

**Comment by MarcoEstevez** [comment]
I'll try to summarize all settings we tested during that Issue and what might be the best.

But before doing so, and keeping on mind all test we did was based on January builds, more precise
( PCSX2 1.5.0-20160117163859 - compiled on Jan 17 2016 )

I did noticed... this game never worked before on any internal resolution other than Native one. I don't really know what change since January you guys did, but what a great surprise to my eyes today since for the very first time on PCSX2 History TD-Unlimited is running on glorious HD, thanks for such a fantastic job.

**Settings:**
---------------------------------------------------------------------------------------------------------------

PCSX2 Version:       1.5.0-20160426190932 - compiled on Apr 26 2016
Internal Resolution:  3x (works on any)
CRC:                        None (Debug).
Enable HW Hacks;   Marked
          Hacks Config: all unmarked except "Preload Data Frame" (needed for light and reflections effects)
                                  TC Offset X: 0
                                  TC Offset Y: 0
Hardware Depth:  Marked
Accurate Date:      Marked
Blending Unit Accurate. Medium (same results with "Basic" or "High")

**Comment by gregory38** [comment]
Thanks you. Maybe we will need to move the preload data frame hack into the main menu. It solves various issues.

**Comment by AmbientMalice** [comment]
>Thanks you. Maybe we will need to move the preload data frame hack into the main menu. It solves various issues.

I was thinking about asking for the same thing, since it's a crucial fix some games should have enabled by default.

**Comment by NickDeBeenAIE** [comment]
Here's what happens when you play the US version of TDU:


![Pcsx2 Screenshot 2021 11 14 - 23 26 40 25](https://user-images.githubusercontent.com/60248725/141682067-9a0afc45-498b-4a62-9c23-0bfb52e7d8f4.png)

Can anyone explain what I'm supposed to do to mitigate this?
