### ISSUE TITLE
[Feature Request]: Remember cover download URL

### ISSUE THREAD

**Issue by glottisfaun0000** [PCSX2/pcsx2#11256]
### Description

Add option for PCSX2-qt to remember URLs used for the Cover Downloader

### Reason

I want to run the cover downloader everytime I add a new game to PCSX2, and every time I do that I retrieve the URL provided by https://github.com/xlenore/ps2-covers/ from a bookmark. That url has been the same since I started using PCSX2, so if it was remembered it would save me retrieving that url every time I want to run the downloader.

### Examples

- Maybe a checkbox next to "Use serial file names" that says "Remember url(s)", writing it to a config file.

**Comment by stenzek** [comment]
Sigh. Been discussed many times before, downloading covers from anywhere other than your own server is piracy. And if it's your own server, you should know the URL.

**Comment by xCENTx** [comment]
> And if it's your own server, you should know the URL.

Just out of curiosity , if the user did not include a url to a server containing covers for download . . . would this request have been taken a bit more seriously? I have my own server to download covers from (i scan my legitimate covers and host them privately for myself) I have to agree that it would be nice if I didn't have to enter this URL in every single time I get a package from ebay containing my new game.

**Comment by MrCK1** [comment]
> > And if it's your own server, you should know the URL.
> 
> Just out of curiosity , if the user did not include a url to a server containing covers for download . . . would this request have been taken a bit more seriously? 

Not sure why you're focusing on that point. It's already been discussed many times  and the decision still stands
- https://github.com/PCSX2/pcsx2/issues/8013
- https://github.com/PCSX2/pcsx2/issues/11050
- https://github.com/PCSX2/pcsx2/issues/8206
