### ISSUE TITLE
[BUG]: gzip'ed ISOs take much longer to load in 1.7.0 vs 1.6.0

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#11255]
### Describe the Bug

In v1.6.0 stable, Final Fantasy X: International gzip'ed took 13 seconds to boot.

In the v.1.7 nightlies, it takes 16 seconds to even get past the gam elist and into a black screen and then 28 seconds in total to get it to boot into the game.

I'm working on bisecting 1.7 nightlies now to find where the regression was introduced.

### Reproduction Steps

Launch a .gzip'ed ISO in a v1.7 nightly and see how long it takes to load compared to v1.6.0 stable.

### Expected Behavior

I expect it to launch just as quickly as before.

### PCSX2 Revision

v1.7.5813

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
The gzip code is utterly disgusting and crash prone. I've been waiting to remove it for some time...

So I guess this is a good opportunity to raise the question of if anyone is still relying on it.

**Comment by karasuhebi** [comment]
I would imagine not many people rely on it, no. Does PCSX2 have usage stats like Dolphin does to track this kind of thing?

**Comment by stenzek** [comment]
No, because it is a privacy nightmare.

**Comment by karasuhebi** [comment]
Ah I see.

In other news, I found what the issue is and it's not a regression, so this issue can probably be closed.

At some point between 1.7.0-1719 and 1.7.2576, someone must've touched the code for the gzip index because PCSX2 complains about the size of the existing gzip index file:
![2024-05-15 23_07_58-Log_Window](https://github.com/PCSX2/pcsx2/assets/6857825/44c8c7ab-82a1-48ff-a865-051991cbff63)

**Comment by karasuhebi** [comment]
I can bisect further if there's interest in knowing when and what was changed but honestly I'd argue that's irrelevant.

What I think might need to be changed (if we're changing anything at all regarding gzip) is the behavior of PCSX2 when it creates a new index but there's already one there: It refuses to overwrite the old one. This is nice and all but it results in PCSX2 needing to make a new one every time it launches unless the user manually deletes the old one. I'd argue it's better if it just makes a new one with a different filename.

**Comment by stenzek** [comment]
I changed a fair bit of code there, because it was so janky and unreliable that it would crash PCSX2 if you scanned any gzip files that were corrupted, or were not game dumps. I know the index creation does work, because I tested it.

But I'd rather just purge the code completely, because while it doesn't crash all the time now, it is still missing a _lot_ of error checking/validation, which is really something you want when dealing with user-provided files.

**Comment by karasuhebi** [comment]
Want me to close out this Issue, then?

**Comment by stenzek** [comment]
It's fine, I'll open a purge PR later and link it, and give it a few days if someone wants to object with a "real" use case.

Normally I wouldn't be so quick to jump to purging a feature, but using gzip is arguably a terrible choice these days - the format isn't meant to be seekable, and there's much better alternatives.

**Comment by karasuhebi** [comment]
1.7.2002 doesn't complain about incorrect size of the gzip index but 1.7.2003 does. Change must've been introduced during 1.7.2003 but the only thing I see tied to that build is PR #4914. Anyway, I'll leave this Issue to you. Thanks, stenzek!

**Comment by refractionpcsx2** [comment]
A lot of people use gzip, I wouldn't remove it, personally (as sucky as it is)

**Comment by karasuhebi** [comment]
Thanks, stenzek!

**Comment by RedDevilus** [comment]
From what I can tell from empirical viewpoint (well more a guess). Gzip is used around 5% or less of all users, which to be fair is the lowest of all the methods. Atleast it's not bzip2 from a past CDVD plugin though not sure if that was Linuzappz ISO CDVD plugin where it was less than a percentage and probably quite awful compared to gzip, or atleast redundant with all the already available methods.
