### ISSUE TITLE
[BUG]: Log Window's "Close" button doesn't do anything

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#11262]
### Describe the Bug

The close button for the Log Window is grayed out. Also the "Close" option under the "Log" menu does nothing.

### Reproduction Steps

With the Log Window open, click on Log -> Close.
Nothing happens.

### Expected Behavior

I expect the Log Window to close when the "Close" option is selected.

### PCSX2 Revision

v1.7.5817

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
Think that was intended:

https://github.com/PCSX2/pcsx2/pull/10949
https://github.com/PCSX2/pcsx2/issues/10939

**Comment by stenzek** [comment]
Working as intended, we can't differentiate between application-being-closed and user-initiated-window-close.

**Comment by karasuhebi** [comment]
Wouldn't we want remove the Close option from the Log Window?
![image](https://github.com/PCSX2/pcsx2/assets/6857825/92975198-4d28-4b04-960e-42e044e91cb8)
