### ISSUE TITLE
[BUG]: Bilinear (PS2 or Forced) Filtering Creates Line Tearing on Screen (KH2FM)

### ISSUE THREAD

**Issue by Xaddgx-Absol-Brasse** [PCSX2/pcsx2#11265]
### Describe the Bug

PCSX2 is now generating artifacting lines that go from the top to the bottom of the screen in the game, when Texture Filtering is set to anything except Nearest. There is a chance this is also an upscaling issue on this version, but it's hard to tell at Native resolution. However, this is a regression regardless, because this issue did not exist on older versions with the exact same settings. In the below video, I demonstrate the issue clearly, first using an HD texture pack to give a more precise visual of where the screen tears, and then I move over to the vanilla version of the game, while comparing between Bilinear (PS2) and Nearest once your eyes are aware of where to look.
https://www.youtube.com/watch?v=CQnazEuLBfQ

Note: GSDumps included below are exported on the vanilla game, unmodded. The first is from the latest Nightly, the second is from the last version I used that didn't have the issue [v.1.7.2746]. Sorry, I don't update often.

### Reproduction Steps

Boot the game, and get the camera close to the player's face to easily tell, then set texture filtering to anything that isn't Nearest. Easier to see when upscaled. 

### Expected Behavior

Rendering should not cause tearing, and be as accurate as it was on older versions, if Bilinear (PS2) is recommended as the default setting for texture filtering on startup.

### PCSX2 Revision

v1.7.5817

### Operating System

Windows 10 (64bit)

### CPU

Intel i7-6700k

### GPU

Nvidia GeForce GTX 1080 Ti

### GS Settings

Internal Resolution is 5x. I can't visually tell if it's happening on Native.
Anisotropic Filtering is set to 16x, but the issue persists even when off.
Shade Boost is active, but the issue persists even when off.
Screen Offsets is active, but the issue persists even when off.

### GS Window Screenshots

First image is one with tearing on new version, second image is no tearing on old version. Both are Bilinear (PS2)
https://imgur.com/a/ZDIUIGe

### Logs & Dumps

[KH2FM Bilinear Filtering Bug GSDump [v1.7.5817].zip](https://github.com/PCSX2/pcsx2/files/15354003/KH2FM.Bilinear.Filtering.Bug.GSDump.v1.7.5817.zip)
[KH2FM Bilinear Filtering Old Version GSDump [v1.7.2746].zip](https://github.com/PCSX2/pcsx2/files/15354100/KH2FM.Bilinear.Filtering.Old.Version.GSDump.v1.7.2746.zip)

**Comment by Mrlinkwii** [comment]
can i have a screenshot of both versions :)

**Comment by stenzek** [comment]
Compare with software. If native matches, it's likely fine.

**Comment by Xaddgx-Absol-Brasse** [comment]
> can i have a screenshot of both versions :)

Absolutely, edited the original post to include an Imgur link for both.

**Comment by Xaddgx-Absol-Brasse** [comment]
> Compare with software. If native matches, it's likely fine.

Here are screenshots for that. Hardware Native is the top, Software is the bottom. Both Bilinear PS2.
https://imgur.com/a/voJwE1B

**Comment by JordanTheToaster** [comment]
Those lines are due to autoflush and the bloom being misaligned due to upscaling.

**Comment by stenzek** [comment]
I can't see any "tearing", and if it matches software at native, then it's an upscaling issue and thus invalid.
