### ISSUE TITLE
[BUG]: The file pcsx2-qt.desktop Exec lines fails to function (at least on KDE Plasma)

### ISSUE THREAD

**Issue by HoodedDeath** [PCSX2/pcsx2#11273]
### Describe the Bug

Using `Exec=pcsx2-qt` does not function for me on Plasma. Needs to be changed to the full path in order for it to work. On my Arch installation, using the AUR package `pcsx2`, the desktop file needs to be changed to use `Exec=/usr/bin/pcsx2-qt` in order to function.

### Reproduction Steps

Use the desktop file that uses `Exec=pcsx2-qt`. Application will try to launch, but will be unable to find the application.

### PCSX2 Revision

v1.7.5788

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by HoodedDeath** [comment]
Decided to not make a pull request at this time since I have no confirmation whether or not the correct path would be `/usr/bin/pcsx2-qt` on all/most distros

**Comment by refractionpcsx2** [comment]
Is this just for the AUR?

**Comment by HoodedDeath** [comment]
I currently only have Arch machines, so I can't test other distros, but the AUR package directly installs `.github/workflows/scripts/linux/pcsx2-qt.desktop`, so I would assume any other native package that does the same is effected as well.

**Comment by refractionpcsx2** [comment]
okay we don't use package mode, if it's AUR you need to let the packager know, it's nothing to do with us.

**Comment by refractionpcsx2** [comment]
This is the first I've heard of this problem, though, I'll reopen but I suspect the answer from more linux'y people will be "works fine as it is, user error" or something.

**Comment by HoodedDeath** [comment]
I understand you only support linux builds via flatpak and appimage. Strangely, I've been using the AUR package for a long while and only had this issue with a recent reinstallation of my system.

You got an opinion of me making a PR for fixing the .desktop file?

**Comment by weirdbeardgame** [comment]
The AUR uses a launch script that's executed by the desktop file. https://aur.archlinux.org/cgit/aur.git/tree/pcsx2-qt.sh?h=pcsx2-git

Pcsx2 is installed into `opt` with the resources folder, and the launch script is called from the desktop file. So any manual fixes to the desktop here may or may or may not make a difference.

If you want to figure out if it's related to Linux as a whole vs just the AUR, DM me on discord (Weirdbeardgame)

**Comment by TheLastRar** [comment]
> The AUR uses a launch script that's executed by the desktop file. https://aur.archlinux.org/cgit/aur.git/tree/pcsx2-qt.sh?h=pcsx2-git

Worth noting they appear to be talking about the [pcsx2](https://aur.archlinux.org/packages/pcsx2) AUR, rather than your [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git) AUR.

**Comment by weirdbeardgame** [comment]
Yeah, there's not a huge difference from what I can tell between the two aside from no launch script, but that's a worthy note.

**Comment by HoodedDeath** [comment]
> The AUR uses a launch script that's executed by the desktop file. https://aur.archlinux.org/cgit/aur.git/tree/pcsx2-qt.sh?h=pcsx2-git
> 
> Pcsx2 is installed into `opt` with the resources folder, and the launch script is called from the desktop file. So any manual fixes to the desktop here may or may or may not make a difference.

That launch script is in `/usr/bin` and shows up in path via `which`. Issue being that, to my knowledge/experience, a desktop file requires the Exec line to be a canon path. I have modified the file on my installation to use `Exec=/usr/bin/pcsx2-qt` instead of `Exec=pcsx2-qt` and that fixed the application not launch via the application entry.

**Comment by HoodedDeath** [comment]
> > The AUR uses a launch script that's executed by the desktop file. https://aur.archlinux.org/cgit/aur.git/tree/pcsx2-qt.sh?h=pcsx2-git
> 
> Worth noting they appear to be talking about the [pcsx2](https://aur.archlinux.org/packages/pcsx2) AUR by eclairevoyant, rather than your [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git) AUR.

Correct, I am using eclairevoyant's AUR package. But it looks like the -git package also just installs the provided .desktop file that had caused my issue.

**Comment by stenzek** [comment]
What part of
> We do not accept issues pertaining to Linux builds other than the official AppImage and Flatpak.
> Please contact your packager for support. We have no control over other builds, nor can we investigate any issues, and historically they have been known to be broken.
> This includes pre-configured "distributions" such as EmuDeck, the "AUR", etc.

In the issue template was not clear? These packages are actively hostile to us, since the packagers are uncooperative, and **known to be broken**.

>  I have modified the file on my installation to use Exec=/usr/bin/pcsx2-qt instead of Exec=pcsx2-qt and that fixed the application not launch via the application entry.

Why would we want to accept something that "fixes" a package, that has nothing to do with us?

**Comment by HoodedDeath** [comment]
I simply came here because the file causing my problem is in this repository.

**Comment by stenzek** [comment]
So? It works perfectly fine for our use, which is creating the AppImage/Flatpak. If you're trying to use it for something else, that is not our problem.

Sorry to be blunt, but if you can't even be bothered to read the issue template, then I'm not going bother writing a detailed response explaining why this is the case.
