### ISSUE TITLE
[BUG]: Dragon Quest: Shōnen Yangus to Fushigi no Dungeon

### ISSUE THREAD

**Issue by Japanese1** [PCSX2/pcsx2#11288]
### Describe the Bug

The cursor is displayed incorrectly

### Reproduction Steps

title screen

### PCSX2 Revision

1.7.5835

### Operating System

Windows 11

### CPU

12900

### GPU

rtx4060

### GS Window Screenshots

![Dragon Quest - Shoenen Yangus to Fushigi no Dungeon_SLPM-66363_20240522222956](https://github.com/PCSX2/pcsx2/assets/16571453/ed68f8e8-59d4-42e2-a5a3-1e691a9993d9)

**Comment by refractionpcsx2** [comment]
looks like a bad widescreen patch.

Can you try the game without the widescreen patch and see if it displays okay?

**Comment by Mrlinkwii** [comment]
confirmed its teh widescreen patch 

off 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/1ebef16d-e137-4393-b466-03505b4f87fb)


on 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/5c4b0a9b-9f31-4402-89b3-b32ad0c0ea32)

**Comment by refractionpcsx2** [comment]
We'll disable the patch on our end
