### ISSUE TITLE
${omodec}?

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#1129]
What is this supposed to display? I thought it's some leftover from old versions so I deleted PCSX2_ui.ini, but turns out it's not. I never see it change to display anything.
![image](https://cloud.githubusercontent.com/assets/4414625/12386676/8c435b04-bdc7-11e5-9860-85697060485a.png)

**Comment by avih** [comment]
`${omodec}` shouldn't show up at all after you delete `PCSX2_ui.ini`, however AFAICT it was removed without a good readon. It should have been a combined frame/interlaced mode which was added at 45606202 but seem to be accidentally removed at commit c73f87ac.

@ramapcsx2 @ssakash why was it removed? what did it fix?

**Comment by Blackbird88** [comment]
But it does show up lol. No clue why, but it does.

**Comment by avih** [comment]
Yes, the file gets re-created after you delete it, and the default value doesn't have it. However, previous versions of PCSX2 did create `${omodec}`. You probably used one of these previous versions of PCSX2 in between which added it to the new ini file.

**Comment by Blackbird88** [comment]
Well the thing is. It was latest git build, but it was probably some rare bug tbh.

**Comment by avih** [comment]
No, it wasn't some rare bug. The string `${omodec}` doesn't appear anywhere - feel free to search it yourself, so PCSX2 latest git version definitely 1000% didn't create it at the ini file.

**Comment by Blackbird88** [comment]
* I don't have any old version installed and use portable.ini
* I deleted the PCSX2_ui.ini
* It appeared again

**Comment by avih** [comment]
So you're not running the latest git. The latest git version just doesn't have this string anywhere, so it just cannot create it. Please point me to the exact place where you downloaded your PCSX2 version and I'll try that too.

**Comment by avih** [comment]
And why did you close the issue if it's still not solved?

**Comment by Blackbird88** [comment]
http://buildbot.orphis.net/pcsx2/index.php

It got solved by deleting it 2nd time.

**Comment by avih** [comment]
Did you delete it the first time while PCSX2 was running?

**Comment by Blackbird88** [comment]
Ah yes. Could that be it?

**Comment by avih** [comment]
Not could, was. PCSX2 reads the ini values when it starts, and writes them when it closes. If your ini had this value and PCSX2 read it, and you deleted the ini while PCSX2 was running, then it was written again (including the `${omodef}` which was read when it started) when it got closed.

So like I said initially, it shouldn't show up after you delete the ini file.

Regardless, there are still two issues:
1. It shouldn't have been removed at c73f87a.
2. We need a better system to change the default template values.

Right now, the default template gets written to the ini if it's not there, but once it's at the ini, it will not change on its own even after we change the default value at PCSX2 itself (which is the reason it got left there after it was removed from the default). So we need a system to fix that, and regardless we probably want to restore this value.

Please leave this issue open until we handle these two subjects. Thanks.

**Comment by Blackbird88** [comment]
Any particular reason it gets written again when it closes?

**Comment by avih** [comment]
That's how the ini system works. It also writes the ini files after changes which you do via the UI etc (while PCSX2 is running).

**Comment by Blackbird88** [comment]
Oh. OK thanks for riddling this out for me. I don't think I had this happen yet. I usually delete config files whenever I feel like it lol
