### ISSUE TITLE
[Feature Request]: Support Windows on Arm

### ISSUE THREAD

**Issue by CCNHsK-Dev** [PCSX2/pcsx2#11293]
### Description

I find PCSX2 will support Apple Silicon (#10235)
So, I hope this will support windows on arm too.

### Reason

Lastly Surface Pro has windows on arm version. 
I think future windows on arm have more user. 

### Examples

About mac and windows, we can see arm64 is future. 
If will not support windows on arm now,
Maybe planning to it??...

Sorry for my bad englist
Lastly, thank your team about the great work :)

**Comment by refractionpcsx2** [comment]
Nope, only Apple M silicon is getting it.

**Comment by TheLastRar** [comment]
How many people own Windows on Arm devices?

**Comment by CCNHsK-Dev** [comment]
I know windows on arm market share is low.
If multiple user use it in the future, 
or if microsoft lanuches easier arrach64 dev migration
will you add support on the plan?

thank

**Comment by RedDevilus** [comment]
> How many people own Windows on Arm devices?

Windows Surface Pro and some other devices like Lenovo ThinkPad X13s but more importantly those Windows on those Thumb drive form factor. There is some upcoming Snapdragon X Elite like from Lenovo.

So probably notable in a few years. But don't expect to be bigger than 2-3% marketshare at this time (Don't quote me on that, because I can't seem to find credible sources).

**Comment by CCNHsK-Dev** [comment]
> > How many people own Windows on Arm devices?
> 
> Windows Surface Pro and some other devices like Lenovo ThinkPad X13s but more importantly those Windows on those Thumb drive form factor. There is some upcoming Snapdragon X Elite like from Lenovo.
> 
> So probably notable in a few years. But don't expect to be bigger than 2-3% marketshare at this time (Don't quote me on that, because I can't seem to find credible sources).
> 
> To be fair as said above, Apple just has the advantage of being at the forefront of stronger ARM devices.

about apple, I agree. 

About Windows, I think desktop and gaming laptop windows on arm will have 1% low marketshare..

I'm surface pro x & pro 4 i7 user, pro x provide x2-3 battery time and similar performance.
Also, Surface Series future maybe has windows on arm only. 
so, I think  non-hign performance / 2 in 1 windows devies future will have more user.

**Comment by RedDevilus** [comment]
> > > How many people own Windows on Arm devices?
> > 
> > 
> > Windows Surface Pro and some other devices like Lenovo ThinkPad X13s but more importantly those Windows on those Thumb drive form factor. There is some upcoming Snapdragon X Elite like from Lenovo.
> > So probably notable in a few years. But don't expect to be bigger than 2-3% marketshare at this time (Don't quote me on that, because I can't seem to find credible sources).
> > To be fair as said above, Apple just has the advantage of being at the forefront of stronger ARM devices.
> 
> about apple, I agree.
> 
> About Windows, I think desktop and gaming laptop windows on arm will have 1% low marketshare..
> 
> I'm surface pro x & pro 4 i7 user, pro x provide x2-3 battery time and similar performance. Also, Surface Series future maybe has windows on arm only. so, I think non-hign performance / 2 in 1 windows devies future will have more user.

Only thing I forgot was Raspberry Pi and other SBCs, but yeah those aren't powerful compared to the future ones.

**Comment by RedDevilus** [comment]
But it's besides the point with PCSX2 to be honest. People and contributors esspecially need to have an intrest in it and also need to maintain it besides all the other OSes, which seems pretty lukewarm.

**Comment by talynone** [comment]
If you google around there's a custom ARM 64 Windows build of AetherSX2 that works really well.
