### ISSUE TITLE
[Feature Request]: Pause emulation when menu is opened

### ISSUE THREAD

**Issue by robinhood2014** [PCSX2/pcsx2#11303]
### Description

When I open one of the menus while a game is running, I'd like the emulator to pause the state.

### Reason

Right now, when I open a menu, the emulation continues right along. This can be very inconveniencing when, for example, I want to save a state which I can load later in a situation that demands it.

### Examples

In RetroArch, I can press a hotkey (F1) to bring up its menu, and doing this pauses the emulation of whatever core and content is currently running.

**Comment by stenzek** [comment]
The default behaviour *is* to pause when you open the in-game menu...
