### ISSUE TITLE
[BUG]: VISUAL ARTIFACT - Barbie Horse Adventures - Riding Camp (USA)

### ISSUE THREAD

**Issue by shoyguer** [PCSX2/pcsx2#11304]
### Describe the Bug

When playing the game, there is this visual artifact, seems like some shader problem? I seems to duplicate the objects, giving this transparent + blurry effect.

![Screenshot_8](https://github.com/PCSX2/pcsx2/assets/42917725/2b5ac8e4-e590-4d2f-b260-809629e16e91)

### Reproduction Steps

Open the game, play the game

### Expected Behavior

We should have a sharp image instead of this duplicate blurry shader. Thanks for your help!

### PCSX2 Revision

v1.7.5845

### Operating System

Windows 11

### CPU

Ryzen 5 5600

### GPU

RTX 2060

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/42917725/2f7cb17a-8d07-4e44-a915-b2203d51b0f6)

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/42917725/f4311a56-f9b0-49a0-b9e3-979f57d1b069)

![image](https://github.com/PCSX2/pcsx2/assets/42917725/1f56114c-2779-401b-88bc-fa09c09af8e2)

![image](https://github.com/PCSX2/pcsx2/assets/42917725/6a3709d5-fcd2-4b3c-ac28-cf5d757a4d87)

![image](https://github.com/PCSX2/pcsx2/assets/42917725/6f8f7772-96ed-43ec-9693-7fff7877ba20)

![image](https://github.com/PCSX2/pcsx2/assets/42917725/5ddae28e-1069-4f94-b7a1-5de4779d34da)

![image](https://github.com/PCSX2/pcsx2/assets/42917725/ecf8312e-3161-430f-b507-03ca6fe4511a)

**Comment by JordanTheToaster** [comment]
Please post a GS dump you can make one via tools save single frame dump.

**Comment by sigarettenstank** [comment]
Barbie shouldn't have eaten that pill she found on the ground. 

![1665324942828](https://github.com/PCSX2/pcsx2/assets/95235094/19e92a70-414c-4f54-bc45-ce12563815f4)

**Comment by stenzek** [comment]
Does it happen at native? We don't accept upscaling issues as the template states.

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/f9354cfb-f06a-458d-8e81-5c010c23c0a5)
 native res 
[issue.zip](https://github.com/PCSX2/pcsx2/files/15482931/issue.zip)
seems fine here , 
 
 this is an upscaling issue 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/086dc6f7-ce6a-4361-b010-d68edee69772)
