### ISSUE TITLE
[BUG]:  SpongeBob creature from the krusty krab NTSC-U | SLUS-21391 Visual bug

### ISSUE THREAD

**Issue by metalex10** [PCSX2/pcsx2#11305]
### Describe the Bug

The bug itself is that in the spongebob game as shown in the image when you are close to those pink or green things the same ones have to appear next to the hearts but with ticking, this is shown on the original console or in some versions of pcsx2 but in OPENGL and the latter in software mode

In the second image you can see what I say was taken from a YouTube gameplay I left in a reference video

[[](url)](https://youtu.be/F900RepQZdQ?t=509)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/e216a277-c2d0-42b9-9e12-ffebdbbfc407)

![image](https://github.com/PCSX2/pcsx2/assets/3173507/6599d558-b4a9-4295-8353-25adcf852a82)

### Reproduction Steps

It happens when you pass by any of the pink or green models (Patrick Star or Plankton) you should see an animation next to the hearts (lives) but this does not occur

### PCSX2 Revision

v1.7.5845

### Operating System

Windows 11

### CPU

i5-1135G7

### GPU

Intel Iris Xe Graphics

**Comment by metalex10** [comment]
Fixed on v1.6.0 
with this emulation settings
![image](https://github.com/PCSX2/pcsx2/assets/3173507/e75a4100-8466-4a0d-9cd4-055b2968222f)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/af63b7ad-2c11-4c7d-acc3-145211fdaa79)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/ee68589a-d1ad-4a33-bc02-8e8f1ca31430)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/e5e1cb1e-5e5e-4074-b690-2a753c67f5fd)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/28a88500-93a7-4352-8e60-62f02d38dcf1)
![image](https://github.com/PCSX2/pcsx2/assets/3173507/eaf5f8ba-05b9-4ddb-a7dd-7e0d5a568a52)

**Comment by metalex10** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/3173507/113b0377-dae0-4930-b305-4e6cb138b354)

**Comment by Mrlinkwii** [comment]
can i have a gs dump ?

**Comment by kamfretoz** [comment]
Works fine here, v1.7.5853

https://github.com/PCSX2/pcsx2/assets/14798312/b3465454-16be-4fad-9a12-d80bf0925e83

**Comment by metalex10** [comment]
> v1.7.5853

what config have?

**Comment by kamfretoz** [comment]
> what config have?

@metalex10 Default, just make sure you're on the latest nightly build.
