### ISSUE TITLE
Emulator crash when starting any race (Gran Turismo 4)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1131]
-PCSX2 version: v1.5.0-dev-116-g44f1281

-PCSX2 options: Defaults, speedhacks disabled

-Plugins used: GSdx, SPU2-X, xpad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The emulator will crash when entering any race in Gran Turismo 4

-How to replicate: Get to race selection screen and select A-spec (track preview, A-spec, B-spec, ect)

-Last known version to work: The last build I raced in already included the accurate blend fix (v1.5.0-dev-93-g254081e)

-PC Specs: Windows 7 54-bit SP1, i5-4460, GTX-750 1GB SC 

Nvidia Geforce Driver - 361.43

This bug seemed to appear recently. Any race I try to start in GT4 crashes the emu. The furthest you can get to any race is the selection screen that includes A-spec and B-spec options, ect. 

During the time after selecting "enter race" to reaching the race preview screen; my physical memory usage went from 27% to 84%! After selecting A-spec, my memory usage was around 50% and would jump around as the emulator sat at a black screen and crashed. 

The odd thing is that Process Hacker only reports 666.62MB of memory used, but the physical memory usage is 80%. Is there some sort of memory spike that isn't being reported?

![gt4emucrash](https://cloud.githubusercontent.com/assets/16314399/12405737/d6e6941c-be14-11e5-80ad-ad4f08dac7a7.png)

After replicating the crash multiple times, I managed to get a Nvidia OpenGL Driver error code 6. (An application has requested more GPU memory than is available in the system.) I never had a memory error with PCSX2 at all. 

I was also able to duplicate this as monitoring the GPU memory usage during the race preview screen showed that it was nowhere close to the limit and the error came at a random point during the track flyover.

![nvoglcrash](https://cloud.githubusercontent.com/assets/16314399/12405745/ebbc2b4a-be14-11e5-8be1-8d3763767f59.png)

 Another Screenshot showing GPU Memory Usage before Crash
![gpuandsharedmemusage](https://cloud.githubusercontent.com/assets/16314399/12406257/59591a92-be19-11e5-8888-873a9c1a2774.png)

emulog.txt: http://pastebin.com/vKYaep8d

**Comment by MrCK1** [comment]
OK, so I've narrowed this down to a memory allocation issue. I manged to start the race without crashing. 

This comparison photo shows how the system is allocating too much memory while data is being loaded; and it is causing stuttering.

Once the word START appears on-screen, the shared memory returns to normal and the framerate recovers.
![memoryalloc](https://cloud.githubusercontent.com/assets/16314399/12407728/e0ae1a84-be27-11e5-9611-37e88a5b781b.png)

**Comment by gregory38** [comment]
What is your resolution? Native or upscaled?

**Comment by refractionpcsx2** [comment]
This normally only happens if you upscale and haven't got the 4gb patch on the pcsx2.exe, the transition sends your machine mental.

**Comment by alfio8788** [comment]
I do not have this problem personally (memory use spikes but no crashes) using my asus n550jv, small drop (3-4 fps from the average) but nothing more when i use scaling (up to 4x), just for testing purposes, is it possible to have a build of that version without the LARGEADDRESSAWARE enabled? (I am unable to build it on my own in this moment)

**Comment by refractionpcsx2** [comment]
Did we put it in as standard now? I can't remember haha. It should be less likely to crash if it is enabled.

**Comment by alfio8788** [comment]
Yes it's standard, been kinda "complaining" about it, i know it would make the thing crash easier but i remember using GT4 way before this was done and i wasn't crashing at all even on low memory systems, no framerate drop as well, anyway it's just for personal testing, if something weird comes out i will report ASAP

**Comment by refractionpcsx2** [comment]
I suspect the two are unrelated.
this is the build before the patch: http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-1469-g1437640&platform=windows-x86

this is the next available build after: http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-1473-gdf87b64&platform=windows-x86

**Comment by alfio8788** [comment]
Thank you, will report my findings once i get a 10 minutes break

**Comment by MrCK1** [comment]
I was running the game at 4x native; but hasn't large address aware been standard for a while?

I am always on the newest build whenever possible.There was always stutter at the beginning of races, but the loading screens never had a problem until I downloaded one of yesterday's commits.

**Comment by refractionpcsx2** [comment]
Can you find which build cause it? if it was only yesterday it shouldn't be too difficult to trace

**Comment by MrCK1** [comment]
The build I'm on now is also when the bugs appeared: v1.5.0-dev-116-g44f1281

Before that, I had this one: v1.5.0-dev-102-g5bf1251

**Comment by willkuer** [comment]
So please check which build is broken between those.

**Comment by alfio8788** [comment]
After a bit of playing around i can say that LARGEADDRESSAWARE helps the emulation and i can confirm that the crash comes in after dev-93 (i tried the dev-110 and it crashes), sadly i couldn't try all the versions as i do not have a lot of time right now, i do not know which other settings @MrCK1 is using ("default" is a bit generic) and i do not use the same exact platform (Win10 x64, i7-4700HQ, GT750m 4GB (driver 361.43), 16GB ddr3@1600mhz, disabled Windows paging, GS plugin is AVX2).

**Comment by MrCK1** [comment]
@willkuer I will try to find which build potentiallly caused this issue

@alfio8788 I'll try the other plugins and see if the issue still comes up. The emulator isn't crashing every time, just running slowly. During those times; the GS usage was around 90-100% while the EE and VU's are 0-10%

This is probably unrelated but I'm getting a black screen and the EE console is spewing bits about COP0. I believe this is related to commit https://github.com/PCSX2/pcsx2/commit/72e8d083b7b882ffee262b68af2f098f6e642c3f from 2 days ago?
`EE: Unrecognized COP0 op 4297003c`
`EE: Unrecognized op c0000024`
`EE: Unrecognized COP0 op 402d0000`

**Comment by gregory38** [comment]
This commit is normally a nop so why do you believe it is related to your issue?
