### ISSUE TITLE
[BUG]: Patched sharderc prevent packaging for Linux

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#11314]
### Describe the Bug

I saw here is a shaderc patch in this repository. However it is impossible to patch system shaderc library. And shaderc source is not included in 3rdparty folder. This makes it impossible to build PCSX2 on Linux with cmake...

### Reproduction Steps

Build pcsx2 on Linux

### PCSX2 Revision

1.7.5853

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

openSUSE Tumbleweed

**Comment by TheLastRar** [comment]
This script https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/scripts/linux/build-dependencies-qt.sh will download and patch shaderc. You then set the cmake prefix for PCSX2 to point to the built dependencies

This is detailed in the wiki https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux#build-procedure

**Comment by stenzek** [comment]
Not a bug. Follow the build instructions.

PCSX2 does not support system packages for most dependencies.
