### ISSUE TITLE
[BUG]: TXRD2 headlight clipping

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#11319]
### Describe the Bug

In dx11/12 the headlights clip in the ground (player car only)

### Reproduction Steps

Use dx11/12

### Expected Behavior

Headlight beams clipping 

### PCSX2 Revision

5856

### Operating System

Windows 11

### CPU

7840hs

### GPU

4070

**Comment by Mrlinkwii** [comment]
can i have a gs dump?

**Comment by Emi-pcsx2** [comment]
I will do it later today, and I am using dx12 because I get better performance than vulkan. No clue why. Tried adjusting nvidia 3d settings and allat but still nun

**Comment by adrianseonu** [comment]
i'm having same issue.

**Comment by refractionpcsx2** [comment]
> I will do it later today, and I am using dx12 because I get better performance than vulkan. No clue why. Tried adjusting nvidia 3d settings and allat but still nun

You're getting better performance because it does a worse job, hence your Jak problem you tried to report. You should be using Vulkan, unless you're struggling to get full speed.

**Comment by Emi-pcsx2** [comment]
Visually I see no difference in vulkan/dx12 so I see no reason not to use it

**Comment by JordanTheToaster** [comment]
> Visually I see no difference in vulkan/dx12 so I see no reason not to use it

You tried reporting one such case of DX being awful yourself you've seen it before different.

**Comment by refractionpcsx2** [comment]
> Visually I see no difference in vulkan/dx12 so I see no reason not to use it

Except Jak and TXRD2?

**Comment by Emi-pcsx2** [comment]
Jordan can you please rephrase i do not understand

**Comment by lightningterror** [comment]
Game requires sw blending which will work only on vk/gl.

**Comment by Emi-pcsx2** [comment]
> > Visually I see no difference in vulkan/dx12 so I see no reason not to use it
> 
> Except Jak and TXRD2?

Every time I encounter a problem regarding dx11/12, I report it here. I've played alot of games which means barely any have a difference. So why not take advantage of the better performance

**Comment by Emi-pcsx2** [comment]
> Game requires sw blending which will work only on vk/gl.

So use one of those, got it

**Comment by Emi-pcsx2** [comment]
> And we've told you both times it's because Direct3D is incapable of doing the blending required to do the effect you're reporting broken.
> 
> Stop using Direct3D and reporting graphical problems with it, it *can't* do what Vulkan can do.

I didn't know such information, I just report because it looks broken, sorry
