### ISSUE TITLE
Jak 1 shadow problem

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#11318]
### Describe the Bug

On dx11-12 the characters got shadow problems 

### Reproduction Steps

Use dx11-12

### Expected Behavior

Broken shadows (characters)

### PCSX2 Revision

1.7.5856

### Operating System

Windows 11

### CPU

7840hs

### GPU

4070

**Comment by refractionpcsx2** [comment]
Known and unfixable, use Vulkan or OGL.
