### ISSUE TITLE
[Feature Request]: key automation

### ISSUE THREAD

**Issue by Chipipablo** [PCSX2/pcsx2#11326]
### Description

Adding a script mode or something to enable keyboard automation on game.

### Reason

When we need to repeat a button for so long, sometimes during minutes having an automation mode where you can config the repeated key and interval would be really helpful.

### Examples

We could use a hotkey to enable/disable an automation.

**Comment by Mrlinkwii** [comment]
you can already do this with the macro feature 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/b3350c70-4479-41d9-9f06-ef5533d4648b)

**Comment by stenzek** [comment]
Yup, already a thing.
