### ISSUE TITLE
[Feature Request]: ffmpeg streaming

### ISSUE THREAD

**Issue by Chipipablo** [PCSX2/pcsx2#11325]
### Description

Add a feature to perform live streaming of current game.

### Reason

This will bring us a way to share our videogames using a light way as ffmpeg in place of OBS or others, also this will adapt to game screen easily

### Examples

As same way there's a menu item to record the screen, would be great to have the same for streaming. Even would be great if we could set out custom ffmpeg parameters to create a custom recording/streaming.

**Comment by Mrlinkwii** [comment]
Use OBS and other streaming programs

**Comment by refractionpcsx2** [comment]
You can also already record videos.
