### ISSUE TITLE
[BUG]: XInput Starts sending Keyboard Inputs

### ISSUE THREAD

**Issue by CountZeroOr** [PCSX2/pcsx2#11338]
### Describe the Bug

While using a Bluetooth Xinput Device (Tested on Xbox One Controller and 8Bitdo SN30 pro+), after inputting several controller inputs, the software will start recognizing button inputs on the controller as being the keystrokes for shortcuts in PCSX2 (A on an X-Input device/X on the PS2 controller as fullscreen, Start as opening the pause menu in the emulator, Xinput B as toggling pause, etc.)

Clicking out of the game into a different program, and then clicking back into it recovered the issue temporarily, but it would return several minutes later.

### Reproduction Steps

Load a game in the emulator (Issue was mainly observed in Xenosaga Part 1), play for a few minutes, and the issue will start occurring on its own.

### Expected Behavior

I expected the button inputs to fit with the button mappings for the PS2 Dual Shock.

### PCSX2 Revision

v1.7.5865

### Operating System

Windows 11

**Comment by stenzek** [comment]
Nothing to do with PCSX2. Disable steam input. Chat to the folks on the forums or discord server, they can provide further assistant.
