### ISSUE TITLE
[BUG]: When using the option "intemal Resolution" ps2 *2, I found that cpu usage increased significantly

### ISSUE THREAD

**Issue by zack-huangzihan** [PCSX2/pcsx2#11339]
### Describe the Bug

When using the option "intemal Resolution" ps2 *2, I found that the cpu usage increased significantly, my back-end uses opengl, can you guide me to the code position of scaling after rendering the game screen, I want to try to use some algorithms to optimize it, at present, I look at the code select "ps*2", After 800 * 1280, it seems that an 800*1280 texture is directly created in the code, can you guide me, where is the zoom code position?

### Reproduction Steps

When using the option "intemal Resolution" ps2 *2, I found that cpu usage increased significantly

### PCSX2 Revision

latest

### Operating System

Linux (64bit) - Specify distro below

### CPU

i5

### GPU

mali(use opengl)

**Comment by stenzek** [comment]
What? Half this report does not make sense, nor did you correctly fill out the form.

Yes, higher internal resolution does marginally increase CPU usage. This is because degenerate triangles that cover zero area at 1x may cover pixels at higher scale, and we disable the culling when rendering upscaled. But it's not a large difference, usually only in the order of a couple of hundred draw calls.

If CPU usage is the problem, use Vulkan.

**Comment by zack-huangzihan** [comment]
I would like to know where the gl code inside pcsx2 is handled when I set the high resolution? Can you point it out?

**Comment by zack-huangzihan** [comment]
pcsx2/GS/Renderers/HW/GSRendererHW.cpp：

**Comment by zack-huangzihan** [comment]
pcsx2/GS/Renderers/HW/GSRendererHW.cpp：

g_gs_device->CopyRect(sTex, dTex, sRect, destX, destY); 


When I choose to zoom in twice, the texture in this step I find is already enlarged, I want to find the original resolution buf

**Comment by stenzek** [comment]
There's lots of CopyRect() calls. Put a breakpoint on the on you want, and you'll see where it's called from.

**Comment by zack-huangzihan** [comment]
I have tried to add breakpoints, but still can't find, let me briefly describe, when I use the following option, where is the logic of the code to determine whether to scale twice? In what way is it scaled?@stenzek
![20240606170534](https://github.com/PCSX2/pcsx2/assets/44903277/48829115-dd12-439c-ae71-b3295adea815)

**Comment by zack-huangzihan** [comment]
I have tried to add breakpoints, but still can't find, let me briefly describe, when I use the following option, where is the logic of the code to determine whether to scale twice? In what way is it scaled?@stenzek
![20240606170650](https://github.com/PCSX2/pcsx2/assets/44903277/d5f72804-55e9-42e0-93e2-020640d227ff)
