### ISSUE TITLE
[BUG]: Vulkan Bug

### ISSUE THREAD

**Issue by NickOddssey** [PCSX2/pcsx2#11336]
### Describe the Bug

Hi developers, every time I choose Vulkan as the renderer the games end up closing. This happens in all the games, the games even work for a second, but then they close and an error message appears on the screen. I've tried everything, I've updated my drivers, I've checked that my PC supports Vulkan, I've disabled all the hacks and I've left the whole game in its original version, but nothing works.
![Captura de tela 2024-06-04 232147](https://github.com/PCSX2/pcsx2/assets/171757806/3bc91417-a4e4-49d2-892f-6f2ee793db83)
![Captura de tela 2024-06-04 232055](https://github.com/PCSX2/pcsx2/assets/171757806/02f1b5b2-8b5c-4e52-b63a-26a491dff818)
![Captura de tela 2024-06-04 232039](https://github.com/PCSX2/pcsx2/assets/171757806/d9326d91-4653-4888-9234-c0ede00b459c)

### Reproduction Steps

The bug is simple: open any game with the vulkan option checked.

### PCSX2 Revision

1.7.5865

### Operating System

Windows 11

### CPU

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.20 GHz

### GPU

Integrated.

### GS Settings

![God of War_SCUS-97399_20240604234326](https://github.com/PCSX2/pcsx2/assets/171757806/f85e7d53-4828-400c-932f-151cd828afa2)
[God of War_SCUS-97399_20240604234326.zip](https://github.com/user-attachments/files/15572465/God.of.War_SCUS-97399_20240604234326.zip)

### Emulation Settings

I didn't change it.

**Comment by JordanTheToaster** [comment]
You cannot use Vulkan on older iGPUs like yours as it's unstable. In future please use the Discord for support.
