### ISSUE TITLE
[BUG]: Cannot boot into the game on BIOS 2.50 (europe) with Fast Boot disabled.

### ISSUE THREAD

**Issue by kirillparaev** [PCSX2/pcsx2#11343]
### Describe the Bug

If BIOS v2.50 is used, any game cannot be booted without enabling Fast Boot option in PCSX2's settings. Instead of booting the game, BIOS opens up ps2's browser.

### Reproduction Steps

1 - use 2.50 bios
2 - disable fast boot
3 - boot any game

### Expected Behavior

Booting into the game with ps2's intro screens

### PCSX2 Revision

v1.7.5865

### Operating System

Windows 11

### CPU

i5-10210U

### GPU

GeForce MX 350

**Comment by Mrlinkwii** [comment]
is the game of the same region?

**Comment by kirillparaev** [comment]
game is US, bios is EU. EU game on EU 2.50 works fine. however, US 2.30 bios is able to boot any region without fastboot

**Comment by Mrlinkwii** [comment]
>game is US, bios is EU. 

this is working as intended , like it would on real hardware
