### ISSUE TITLE
[Feature-Request] - Adding hotkey to rotate against available resolutions (only HW mode)

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#1135]
I would love to have It for changing (looping) through "IR" Internal Resolution values, as we do actually have for Interlacing (F5) or TV shaders (F7).

I'm not sure how hard to develop this it might be, and of course its low, low prio, but I found it pretty handy since in Hardware Mode some games plays well at max host machine resolution (custom one), some others needs Native and many of the rest can do any IR but they can have difficulties in reaching 100% emulation speed at some level, so it would be pretty easy to adjust to the level they require without pausing and open GSdx dialog.

basic specifications for request: 
1. add hotKey to change IR of the emulation.
1b  IR will change accordingly available IR list (GS dialog)
2.   Hot key should be only active while on HW mode.

What do you think guys?

If my request is taken into consideration, I would suggest another one related to this. Which is to add a second custom IR to the list, cause having a HotKey to quickly changing between IRs, there is another type of games that does not have performance problems but they can only render well at some specific IR, for instance (Enthusia Professional Racing) this game runs well at native, and use to run full speed at any resolution, but for some reasons also generate vertical black lines on the render so it only render properly above native IR at an specific factor of 60 points.

Having an additional Custom IR we can cover most of the cases without changing it manually.
-- games that runs at any IR: Custom1 ( Max IR suported by your graphic card or monitor)
-- games that needs an specific IR:  Custom2  ( for example 1260 x 708 )
-- games that runs well at any IR but has troubles reaching full speed.
-- games that needs Native resolution ( for example. Test Drive Unlimited )

**Comment by willkuer** [comment]
This post is a bit confusing.

I think most people dont want to cycle through internal resolutions. Most games can be easily handled at 4xnative (full hd) on most modern gpu's.

Custom resolutions are close to be dropped because of missing accuracy. I wouldnt expect another cr option.

What you are looking for is a front end. Pcsx2 has two availsble frontends iirc. Pcsx2bonus and something with launch...


The vertical black stripes are probably solved by the align hack (gsdx hw hacks).

**Comment by MarcoEstevez** [comment]
I see your point. you might be right

what I was thinking, may I did not explain correctly.

If you run a game and notice some glitches, or suspect something might not be correct, you do press F9 and easily change between SW and HW. right?

I thought... same principle could apply to IR since some games only runs well at native.

 
but as I said you might be right, and adding such feature it doesn't make sense at all.

**Comment by willkuer** [comment]
I don't know if it makes sense. Maybe a switch between current and native resolution would make sense. I am not a tester and rarely need to play with native resolution. And even if I do, opening the plugin config and readjusting the IR is quite fast.

We don't have many spare hotkeys so one would probably need a a complex hotkey like Ctrl+/Shift+/Alt+F5/F7 or whatever.

So far nobody needed such a feature so I guess we won't need it in the future but who knows. Maybe more than just you had this idea but never posted about.

**Comment by MarcoEstevez** [comment]
All right, most probably its just me :D

Feel free to close this issue if you consider. or correspond to me to close it, I just didnt use to github protocol yet.

**Comment by gregory38** [comment]
If you want native resolution, your best bet is F9. As said no room for more hotkey, and I don't see the improvement.

**Comment by TheTechnician27** [comment]
'Increase Upscale Multiplier' and 'Decrease Upscale Multiplier' hotkeys now exist; tagging accordingly.
