### ISSUE TITLE
[BUG]: PCSX2 v1.7.5870 won't boot

### ISSUE THREAD

**Issue by danives** [PCSX2/pcsx2#11350]
### Describe the Bug

Tried to update to the latest version and the updater crashed out. Instead deleted the older version, loaded up the new one and nothing happens after double clicking on the executable.

### Reproduction Steps

Download new version and execute

### PCSX2 Revision

v1.7.5870

### Operating System

Windows 11

### Logs & Dumps

[crash-2024-06-07-17-45-58-339.txt](https://github.com/user-attachments/files/15742670/crash-2024-06-07-17-45-58-339.txt)

[crash-2024-06-07-17-45-58-340.dmp](https://github.com/user-attachments/files/15742671/crash-2024-06-07-17-45-58-340.dmp)

**Comment by refractionpcsx2** [comment]
Please use the discord for support issues.
