### ISSUE TITLE
[BUG]: Jak X - Changing the bios language does not load game

### ISSUE THREAD

**Issue by Reco2126** [PCSX2/pcsx2#11357]
### Describe the Bug

When changing the BIOS to the Spanish language, and the game (Jak X) is started from Full Boot, the game will start, but it will remain in black screen before loading the introduction cinematic.

### Reproduction Steps

Set the BIOS to Spanish:
![01](https://github.com/PCSX2/pcsx2/assets/51425327/7d0bfb1e-77c3-42c0-930d-dfdf17a99815)
![02](https://github.com/PCSX2/pcsx2/assets/51425327/632f1d8a-cfa9-47f3-ac41-f503a7a5522b)

Press **_Shutdown_** and Right click on Game and then _**Full Boot**_. Then, the game will boot and as seen will show the logos and play the THX video.
![03](https://github.com/PCSX2/pcsx2/assets/51425327/ef9662bb-5219-440f-b625-22e2c1b6e1db)
![04](https://github.com/PCSX2/pcsx2/assets/51425327/83a0eaf5-8873-4a1b-8b3e-48a13e1989c4)
![05](https://github.com/PCSX2/pcsx2/assets/51425327/1b8d1da7-1b42-4877-bfdc-d3c55b3a4651)
![06](https://github.com/PCSX2/pcsx2/assets/51425327/13a3ff7f-a27e-42de-b0f0-e5881da5415f)
![07](https://github.com/PCSX2/pcsx2/assets/51425327/2a9f4874-4ccd-41ba-95c4-f08f31b06f4b)
![08](https://github.com/PCSX2/pcsx2/assets/51425327/33ae3a6a-931e-4af5-821d-1451182f62cc)

After that screen will remain black.
![09](https://github.com/PCSX2/pcsx2/assets/51425327/c1ea1ba2-96f6-4131-b301-389be267fea5)

### Expected Behavior

The game should start normally, but in the Spanish language.

### PCSX2 Revision

v1.7.5873

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

SteamOS

### CPU

AMD Custom APU 0405

### GPU

Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] (rev ae)

### GS Settings

![GS06](https://github.com/PCSX2/pcsx2/assets/51425327/7995b4d8-61c3-41a3-9e56-545d9ba8126c)
![GS05](https://github.com/PCSX2/pcsx2/assets/51425327/2efebb0c-9f24-4eb0-a19c-7fcbac84a7bc)
![GS04](https://github.com/PCSX2/pcsx2/assets/51425327/08d17edc-d3dd-441c-99ac-644ece5acf97)
![GS03](https://github.com/PCSX2/pcsx2/assets/51425327/e6b942f9-2fec-43bd-9d0b-1212f1fda794)
![GS02](https://github.com/PCSX2/pcsx2/assets/51425327/07abf335-4cbf-42f0-b43a-0192bc055c59)
![GS01](https://github.com/PCSX2/pcsx2/assets/51425327/d1ef04ff-25f6-478a-9909-5ea8aaabcf40)

### Emulation Settings

![ES01](https://github.com/PCSX2/pcsx2/assets/51425327/10bf96c2-a2e2-4c31-8a96-2d72f43f0723)

**Comment by refractionpcsx2** [comment]
Set my BIOS to Spanish, exited, full booted the with the same version as you, intro played fine and got to the menu without problem

![image](https://github.com/PCSX2/pcsx2/assets/6278726/7d41084c-4f12-4ec0-87a1-7d3a4e78c118)


I would recommend verifying your ISO from the per game properties there, maybe check your memcard isn't corrupt. If you have any further problems please visit the discord,
