### ISSUE TITLE
[BUG]: Bluetooth controller gets disconnected after 15 minutes of play on M1 Mac, Sonoma 14.4.1

### ISSUE THREAD

**Issue by eldandelion** [PCSX2/pcsx2#11358]
### Describe the Bug

When connecting DualShock controller over bluetooth, it keeps disconnecting every 15 minutes on M1 Mac, so that it needs to be turned on and reconnected. 

Version of Mac OS is Sonoma 14.4.1.

Connecting controller over USB doesn't cause this issue. 

Similar problem was found on RPCS3 emulator 
https://github.com/RPCS3/rpcs3/issues/12290

### Reproduction Steps

Connect controller over bluetooth and play for 15 to 30 minutes

### PCSX2 Revision

v1.7.5873

### Operating System

macOS 14 (Sonoma)

**Comment by stenzek** [comment]
This is 100% out of our control, and likely should be tested/reported as a SDL bug instead.

Assuming it is the same issue, I'm not really sure I like the idea of setting "exclusive mode" as a hackfix, presumably that blocks anything else concurrently from accessing the device.

**Comment by Behodar** [comment]
> I'm not really sure I like the idea of setting "exclusive mode" as a hackfix

I realise this is an old issue, but just for clarification: the issue with RPCS3 is that the library it uses was opening in exclusive mode by default. The fix was to _prevent_ it from going into exclusive mode.
