### ISSUE TITLE
[BUG]: Updater broken + Newer builds not launching

### ISSUE THREAD

**Issue by AnthonyACS** [PCSX2/pcsx2#11352]
### Describe the Bug

A few days ago I was gonna update the emulator when prompted as usual but noticed after downloading, a little progress bar window pops up but it does nothing and the emulator closes itself within a second or two, the window says something like "Win32ProgressCallback".
I tried downloading the latest nightly version instead and the emulator doesn't even launch, latest version that still works for me is pcsx2-v1.7.5865-windows-x64-Qt

### Reproduction Steps

Attempting to update the emulator / launch some of the most recent releases

### PCSX2 Revision

v1.7.5866 - v1.7.5871 (latest as of now)

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[logs.zip](https://github.com/user-attachments/files/15746265/logs.zip)

**Comment by kamfretoz** [comment]
Update your VCREDIST version on Windows and try again. Also please use our Discord for support.

**Comment by stenzek** [comment]
Yep. MS has done _something_, I can't be arsed to dig into it any deeper, but it _looks_ like an ABI break. Specifically in `_Mtx_lock()`. Affects DuckStation too.
