### ISSUE TITLE
[BUG]: Status bar not fully readable

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#11360]
### Describe the Bug

Some letters are cut off.
![Bildschirmfoto vom 2024-06-09 11-01-28](https://github.com/PCSX2/pcsx2/assets/41426906/6308ae6c-4122-41b0-b063-68fb80d2519e)

### Reproduction Steps

Start a game in pcsx2 appimage and look what will happen

### PCSX2 Revision

v1.7.5873

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04

**Comment by stenzek** [comment]
Font issue, it's fine on other platforms.

Can't pick a size that works for everyone, but leaves gaps on the majority of systems.
