### ISSUE TITLE
[Feature Request]: Lossless libx264 video recording (or at least some way to disable the default rate control setting)

### ISSUE THREAD

**Issue by Gabriel2Silva** [PCSX2/pcsx2#11379]
### Description

Discussed this on Discord #help-linux-mac, they suggested me to open a Feature Request.

Currently, there's no way to capture lossless video with the libx264 (or libx264rgb) encoders using the built-in recording feature. In fact, it is not possible to capture lossless anything that's not FFV1 or other intrinsically lossless codec.

This happens because even though there's an "Extra Arguments" field, you can't disable the default bitrate control setting, so you can't use -crf 0 or -qp 0, therefore disallowing lossless libx264.

This also happens with libx265. The --lossless argument is used for lossless encodes. Using `lossless` or `--lossless` as an "Extra Argument" results in `Invalid argument (-22)`, and using `lossless = 1` "works", except it doesn't, as the encode is still limited to the maximum bitrate enforced by PCSX2 rate control setting.

![Screenshot_20240611_155030](https://github.com/PCSX2/pcsx2/assets/71518165/34ac8e21-e1ae-4beb-b7f9-7fb392d6431f)

There should be a way to disable the default rate control setting, as it apparently takes priority over other rate control arguments passed by the user, such as crf.

In the end, even though lossless recording sounds "pointless" or "unnecessary", for people who use PCSX2 at native resolutions, it isn't such a huge compromise. Lossless ±480p is pretty small (filesize) compared to higher resolutions lossless recordings.

### Reason

Allows for better flexibility when passing arguments to the recording feature, especially important/common arguments such as rate control settings.

Allows for lossless h.264/h.265 (HEVC)/etc captures.

### Examples

`ffmpeg -i input -c:v libx264 -preset ultrafast -qp 0 output.mkv` should provide a fast (real-time) lossless CPU encode that can be achieved even in relatively weaker processors.

**Comment by homeisfar** [comment]
Out of curiosity, since I'm looking into something else about video rendering, I looked into this. Are you sure about your findings? I found that adding `crf = 0` as an argument overrode the bitrate setting and indeed produced a lossless recording. I did have some gnarly artifacting for the first few seconds when I recorded to an mp4, which did not happen when I recorded into an MKV.

**Comment by Gabriel2Silva** [comment]
> Out of curiosity, since I'm looking into something else about video rendering, I looked into this. Are you sure about your findings? I found that adding `crf = 0` as an argument overrode the bitrate setting and indeed produced a lossless recording. I did have some gnarly artifacting for the first few seconds when I recorded to an mp4, which did not happen when I recorded into an MKV.

I'm not very active on GitHub, so sorry for the late reply.

You're right, `crf = 0` definitely overrides the PCSX2 rate control setting. It's strange because I remember testing for this specifically, but maybe it was the "gnarly artifacting for the first few seconds" that got me confused.

Anyway, this means that lossless x264 is possible and this issue can probably be closed. Thanks.
