### ISSUE TITLE
Crash when re-enable SDL input source or else[BUG]: 

### ISSUE THREAD

**Issue by phoe-nix** [PCSX2/pcsx2#11377]
### Describe the Bug

when i want to play other games, i need disable input, bcz there is no background input option in qt.
so i disable sdl input source, but when i enable the emu crashed every time.

### Reproduction Steps

run game and disable sdl input source or dinput or else, then re-enable, emu will crash.
and when choose controlle to Not Connected, then choose DualShock2, controller will not be use.
i used XS controller with usb wired.

### PCSX2 Revision

1.7.5881

### Operating System

Windows 10 (64bit)

### CPU

i5-7600

### GPU

GTX 1070

**Comment by stenzek** [comment]
Please use the Discord server or forums for support, this is likely because you have a broken driver installed (e.g. "USB Vibration").

**Comment by stenzek** [comment]
Then post the crash dump (both txt and dmp), and we can check.

**Comment by phoe-nix** [comment]
but there is not crash dump txt and dmp files created. and it crash when disable input source in 1.7.5886, not re-enable.  i should say, emu process closed by itself, not crash? it happend on my friend PC,too,  he used PS4 controller.
and i know why controller not work after i chose 'Not Connected', i boot biohazard outbreak(residenvt eivl outbreak) game via .ELF, bcz i need fast loading. 
these didnt happend in old version, like 1.7.4638.
and i hope there is an option to disable background input.

**Comment by CookiePLMonster** [comment]
Fixed in https://github.com/PCSX2/pcsx2/pull/11544
