### ISSUE TITLE
[Feature Request]: change how the save state cycle feature works

### ISSUE THREAD

**Issue by Gadetron** [PCSX2/pcsx2#11370]
### Description

have the function that cycles save states upon creating one work before making a save state instead of after, so you dont end up in a slot with the incorrect save state when you click load, if it is set to do it whenever you click make a save state then it would make the save in the next slot then move to it as the now active slot, so it loads that one when you click load save state.

### Reason

the current method is annoying as you have to manually go back a slot every time you need to load it as thats the last state made

### Examples

just how it is now, just have it cycle before making a new save instead of after.

**Comment by stenzek** [comment]
By the same logic, having it this way would be annoying, because you couldn't reload the save you just made without cycling all the way back.

If you want it to "automatically move to the next slot", bind the same key to both save and next slot.

**Comment by Gadetron** [comment]
no you'd be in the slot of the most recent save, as you'd move the next slot then save instead of making the save and moving to a new slot

**Comment by stenzek** [comment]
That should be possible by binding next slot + save to the same hotkey, like I said. Assuming the slot increment hotkey gets processed first.

**Comment by TheTechnician27** [comment]
Reopening to mark completed as this feature now exists as the hotkey "Select Next Slot and Save State". This is obscure enough that someone looking for it like the OP might not have noticed.
