### ISSUE TITLE
[BUG]: Gran Turismo 3: A-Spec (NTSC-J) Graphics on both gauges is faulty - lines above each number is thin when it is supposed to be thick.

### ISSUE THREAD

**Issue by Seraphim-20** [PCSX2/pcsx2#11384]
### Describe the Bug

The lines in the gauges above the numbers are not thick when they are supposed to be. I have provided screenshots from the PAL version of what is expected and have checked this on my actual PS2 to confirm the Japanese version isn't like that.

### Reproduction Steps

Enter a race/time trial with any car or track for the same result. Fastest route is to check through arcade mode.

### Expected Behavior

The lines in in the gauge above the numbers should be full and thick.

### PCSX2 Revision

v1.7.5886

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5700X3D

### GPU

Asrock RX-6600 

### GS Settings

![settings - display](https://github.com/PCSX2/pcsx2/assets/149935504/e9a787b1-1436-437d-97ed-e4b1a7d45bff)
![settings - rendering](https://github.com/PCSX2/pcsx2/assets/149935504/e22997f1-ca88-4f22-b7c6-a8c2c0d237e4)
![settings - post process](https://github.com/PCSX2/pcsx2/assets/149935504/b25903f4-463b-49b1-b9c1-87099391045d)
![settings - textures](https://github.com/PCSX2/pcsx2/assets/149935504/893049d3-d585-401e-a8b8-a271d70c3cf7)

Also, show speed is checked.
Settings for PAL version are basically the same except blending accuracy is set to high instead of max.

### Emulation Settings

![settings - emulation](https://github.com/PCSX2/pcsx2/assets/149935504/8683b943-1046-42fc-9b44-51c08704b025)

### GS Window Screenshots

![ntsc -1](https://github.com/PCSX2/pcsx2/assets/149935504/a11c6958-0960-44d8-ab01-a775d4c53a9d)
![ntsc - 2](https://github.com/PCSX2/pcsx2/assets/149935504/7057ba2d-34f6-442a-9316-d8a05f88c3c6)
![Pal 1](https://github.com/PCSX2/pcsx2/assets/149935504/1b9edb69-5e3b-4642-82d3-eb960e48fc8e)
![Pal 2](https://github.com/PCSX2/pcsx2/assets/149935504/2aa496c7-fc02-44fe-b08a-93865e1af8af)

**Comment by Mrlinkwii** [comment]
can i have a gs dump?

**Comment by Seraphim-20** [comment]
> can i have a gs dump?
Sorry for taking so long to respond but I can't figure out how to upload the gs file.

**Comment by Seraphim-20** [comment]
> can i have a gs dump?

Update, sorry I couldn't figure it out so i just uploaded it to google drive. 

https://drive.google.com/file/d/1qKrSj_edJoB-NKeJGu0hiUSPvvjb0uGw/view?usp=drive_link

**Comment by Seraphim-20** [comment]
> cool , thats fine enough , ill have a look

Awesome, thanks. Sorry again about the wait.

**Comment by JordanTheToaster** [comment]
It's an AA1 issue which means it won't look correct outside of Software mode.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/5357515e-845b-403d-b801-0bc5e35056a6)

**Comment by Mrlinkwii** [comment]
mentioned in the meta issue  #5069

**Comment by Seraphim-20** [comment]
Oh okay, thanks for looking into this for me!
