### ISSUE TITLE
[BUG]:  SPS in Jackie Chan Adventures (SCES-52412)

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#11389]
### Describe the Bug

SPS when entering Spain in Jackie's and Jade's character models. Fixed by disabling Instant VU1

https://github.com/PCSX2/pcsx2/assets/126727903/4c335029-deeb-4a37-a037-d2c4e7198a54

### Reproduction Steps

Simply reach Spain. Or use my savestate:
[SCES-52412 (AC4DFD5A).01.p2s.zip](https://github.com/user-attachments/files/15827370/SCES-52412.AC4DFD5A.01.p2s.zip)

### Expected Behavior

No SPS

### PCSX2 Revision

1.7.5886

### Operating System

Windows 11

### CPU

i7-7600

### GPU

GTX 1050 TI

### GS Settings

Default

### Emulation Settings

Default

**Comment by Virtua64** [comment]
Putting the EE Cycle rate to 180% or 300% seems to fix it

**Comment by Buzzardsoul** [comment]
Assuming no one gets around to it, I'll create a pr for this once I have the time.

**Comment by JordanTheToaster** [comment]
> Putting the EE Cycle rate to 180% or 300% seems to fix it if Instant VU1 is enabled

Checked myself and these fixes don't work you need to disable MTVU and IVU to properly fix it.
