### ISSUE TITLE
[BUG]: GamesDB Namco Transmission v1.03 detected as Soul Calibur II

### ISSUE THREAD

**Issue by silentq** [PCSX2/pcsx2#11388]
### Describe the Bug

When scanned in the Namco Transmission v1.03 Demo Disc is detected as Soul Calibur II.  This demo disc originally came as a bundle but even though in the GamesIndex has an entry for this game it is brought in still as Soul Calibur II SLUS-20643. However when I verify the iso is clearly detecting the distinction in the title but still the wrong SLUS:
![Boxes](https://github.com/PCSX2/pcsx2/assets/2636426/284534ba-d45e-4d7a-b4db-5ffa260b38ce)
![SetupUX](https://github.com/PCSX2/pcsx2/assets/2636426/25adb1b3-a4c5-463f-8375-84d6bef6ef02)

When I investigated the GamesIndex I find an entry for this title however its SLUS-20643BD:
![GamesIndex](https://github.com/PCSX2/pcsx2/assets/2636426/99136bae-34fe-407a-9529-fbe31b5efd36)

However the RedumpIndex is still SLUS-20643:
![RedumpIndex](https://github.com/PCSX2/pcsx2/assets/2636426/445fac90-5e55-4252-9931-86fc8cd91f0e)

Even Manually updating this entries and re-scanning the title still gets imported as Soul Calibur II.

### Reproduction Steps

Scan Namco Transmission v1.03 (Soul Calibur II Pack-In) into PCSX2.

### Expected Behavior

Game should be Recognized as Namco Transmission v1.03

### PCSX2 Revision

v1.7.5887

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
It shares the same serial as SC2 because it was bundled with it.

**Comment by silentq** [comment]
> It shares the same serial as SC2 because it was bundled with it.

Yep, its odd because on Redump.org I see the following:
![image](https://github.com/PCSX2/pcsx2/assets/2636426/96192926-8a16-4a85-a5db-99491b179312)

I am a little confused what is this mysterious BD serial?  It seems to be a distinguishing factor here.

**Comment by Mrlinkwii** [comment]
ok on the box it says SLUS-20643BD  in the disc  it has a excusable as SLUS_206.43 ( the one that pcsx2 systems uses )  so that's why it says Soul Calibur II , someone will have to update  the GameDB ( probably @JordanTheToaster ) , 

 you can edit the name  in properties ( since automatically its wrong ) and add a different cover
