### ISSUE TITLE
[BUG]: eglGetDisplay returning 0x3000 (EGL_SUCCESS) Counts as an error

### ISSUE THREAD

**Issue by behrad2k** [PCSX2/pcsx2#11399]
### Describe the Bug

Tried opening a game, and got "Failed to create render device. This may be due to your GPU not supporting the chosen renderer (OpenGL), or because your graphics drivers need to be updated." I have a 4070. Opened the logs and saw it returns eglGetDisplay returns 0x3000 which is EGL_SUCCESS. Why does this count as an error?

### Reproduction Steps

1. Use X11 and mesa.
2. Set renderer to OpenGL.
3. Boot up a game.

### Expected Behavior

It just boots up

### PCSX2 Revision

v1.7.1337

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

i9-14900k

### GPU

RTX 4070 OC

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/139690696/bcacaa33-d611-4129-918c-7bb2cb92fa78)

### Emulation Settings

Default

### Logs & Dumps

![image](https://github.com/PCSX2/pcsx2/assets/139690696/285336ab-ff01-4dab-8c01-ab0cb6de45a5)

**Comment by stenzek** [comment]
I suspect this is an issue with your system, apparently someone else with Meme Linux is also broken.

It just logs whatever `eglGetError()` is, when `eglGetDisplay()` returns `EGL_NO_DISPLAY`.

https://github.com/PCSX2/pcsx2/blob/9c57ac34e319da547b21f7907f999d98d540a57a/pcsx2/GS/Renderers/OpenGL/GLContextEGL.cpp#L209-L221

**Comment by behrad2k** [comment]
then how do i fix it? running pacman -R mesa breaks a bunch of packages

**Comment by JordanTheToaster** [comment]
> then how do i fix it? running pacman -R mesa breaks a bunch of packages

Use the proprietary driver and Vulkan.

**Comment by stenzek** [comment]
This is not a Meme Linux support forum. Please use the Discord server or forums.

**Comment by behrad2k** [comment]
> > then how do i fix it? running pacman -R mesa breaks a bunch of packages
> 
> Use the proprietary driver and Vulkan.

that completely broke it

**Comment by TellowKrinkle** [comment]
Got some details from a user who had this issue a few days ago in the discord server, see #11407

(Temporary solution: build from source or use the pcsx2-git aur package)

**Comment by stenzek** [comment]
I'll sort that out. But please do not recommend using the AUR package, the maintainer is completely incompetent as we're all familiar with, and it is known to be broken.

Personally, I'd recommend the Flatpak instead, it sidesteps all these issues and gives a consistent environment.

**Comment by TheLastRar** [comment]
> I'll sort that out. But please do not recommend using the AUR package, ... and it is known to be broken.

Out of curiosity, what is know to be broken about it? Like what bug or issue is specific to pcsx2-git?

**Comment by stenzek** [comment]
Read the comments on the page, it's a depressing stream of incompetency.

Different/incorrect cflags, but broken paths (due to obsessions with /usr/share and such), using Wayland (broken gamelist/fullscrene/etc), incorrect dependency versions, incorrect compiler versions, etc

**Comment by flavionm** [comment]
What about the binary AUR package, `pcsx2-latest-bin`? It pulls the latest AppImage straight from here, so it should be fine, right?

**Comment by stenzek** [comment]
I don't really see why that's necessary? iIRC those "binary" packages extract the appimage, which means you'll have QPA issues, and the automatic updater won't work.

Just put the appimage somewhere writable, and symlink it in /usr/local/bin or whatever if you must.

**Comment by TheLastRar** [comment]
You'll have to check if the launch script is reused or not (I think it is?).
(As side note, of the 3 other pcsx2 aur packages, only `pcsx2-git` provides its own launch script to disable wayland)

Extracting the appimage is needed for setting the file capabilities for pcap networking, but I'm not aware of any other usecase.
