### ISSUE TITLE
[BUG]: Shin Sangoku Musou 4 - Moushouden,use hd texture pack,something wrong

### ISSUE THREAD

**Issue by QJYEAH** [PCSX2/pcsx2#11393]
### Describe the Bug

![真三国无双4：猛将传_SLPM-66101_20240610031542](https://github.com/PCSX2/pcsx2/assets/15781690/a8e6cada-958e-4de6-8cdc-19a4e0095ed8)

![真三国无双4：猛将传_SLPM-66101_20240610031759](https://github.com/PCSX2/pcsx2/assets/15781690/0bcc8f83-41a5-4b17-9538-af21c0a75cda)

### Reproduction Steps

PCSX2 1.7.5835 version

### PCSX2 Revision

1.7.5835

### Operating System

Windows 10 (64bit)

### CPU

R7 5700X3D

### GPU

RTX 4070Ti

**Comment by refractionpcsx2** [comment]
probably incorrect alpha values on the textures from not being scaled correctly, not our bug.

Best talk to the creator of the pack./

**Comment by QJYEAH** [comment]
> probably incorrect alpha values on the textures from not being scaled correctly, not our bug.
> 
> Best talk to the creator of the pack.
When i use pcsx2-v1.7.5373（2023 12.31）,the problem gone

**Comment by refractionpcsx2** [comment]
Yes, because it didn't care about alpha values.
