### ISSUE TITLE
[BUG]: All renderers except software crash with nouveau drivers

### ISSUE THREAD

**Issue by behrad2k** [PCSX2/pcsx2#11400]
### Describe the Bug

All renderers crash if you use nouveau. Except software which is the only way you can run the rest of the renderers for some reason (Switching to Hardware mode from a game started in Software mode)

### Reproduction Steps

1. Install nouveau
2. Switch renderer to anything except software
3. Boot a game up

### Expected Behavior

The game booting up as normal

### PCSX2 Revision

v1.7.5900

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

i9-14900k

### GPU

RTX 4070 OC

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/139690696/b191a2ef-7deb-4849-a2c1-5904baa565b3)

### Emulation Settings

Default

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/139690696/c89e36e5-96d2-4945-a3cf-f69070571151)
![image](https://github.com/PCSX2/pcsx2/assets/139690696/1bb34570-a5dc-44c3-bc93-2ceffdd353e9)

### Logs & Dumps

`[  475.1303] Failed to create any GL context: eglGetDisplay() failed: 12288 (0x3000)
[  475.1303] Failed to create GS device
[  475.1344] ReportErrorAsync: Error: Failed to create render device. This may be due to your GPU not supporting the chosen renderer (OpenGL), or because your graphics drivers need to be updated.
[  475.1364] GS failed to open.
[  475.1365] Failed to open GS.
`

**Comment by stenzek** [comment]
Not a supported driver for us.

**Comment by behrad2k** [comment]
why?

**Comment by Mrlinkwii** [comment]
nouveau drivers are fundamentally broken please use the proprietary drivers , we are done here

**Comment by stenzek** [comment]
Also, this is an issue **with your system**, as I said in the other thread. Please stop opening threads, and use the Discord server.

Proof:
![Screenshot from 2024-06-15 11-51-52](https://github.com/PCSX2/pcsx2/assets/11288319/c48c061a-bbbd-4c6a-9f34-f30f120bf510)
