### ISSUE TITLE
[BUG]: Sphinx The Cursed Mummy - flickering ground in HW renderers

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#11409]
### Describe the Bug

Ground is flickering in HW renderers. Settings do not seem to affect it

### Reproduction Steps

Boot game, observe ground

### Expected Behavior

Ground should not flicker

### PCSX2 Revision

v1.7.5905

### Operating System

Windows 11

### CPU

Ryzen 7900X

### GPU

RTX 4090

### GS Settings

Defaults

### GS Window Screenshots

Defaults

### Logs & Dumps

![Sphinx and the Cursed Mummy_SLUS-20482_20240616104132](https://github.com/PCSX2/pcsx2/assets/16314399/d388a41b-b347-4427-adc6-d470488a72d9)
[GSdump](https://github.com/user-attachments/files/15858724/Sphinx.and.the.Cursed.Mummy_SLUS-20482_20240616104132.zip) (rename to .gs.xz)

**Comment by lightningterror** [comment]
Seems that GPU Palette Conversion fixes, needs to be debugged why it breaks.

**Comment by MrCK1** [comment]
Correction, fixed by https://github.com/PCSX2/pcsx2/pull/11442
