### ISSUE TITLE
[BUG]: Cheats don't apply quickly enough

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#11411]
### Describe the Bug

When the game is started, the cheats don't get applied until 3 seconds. This makes it impossible for cheats that launch during boot ex. the ones at the beginning of the main function.
This also applies for the demo discs where there are multiple CRCs included.
This isn't the problem in 1.6 as the cheats load as soon as the CRC is loaded.

### Reproduction Steps

1. Enable a cheat that loads during boot up
2. Start the game

### Expected Behavior

Cheats applied immidiately.

### PCSX2 Revision

Latest

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 5600

### GPU

AMD Radeon RX 6700

**Comment by refractionpcsx2** [comment]
use mode 2 instead of 0 or 1 in your patch, maybe.

**Comment by YukiXXL** [comment]
like, patch=2,EE,... ?
Is there a documentation on PCSX2 cheats/patches and what does what?

**Comment by refractionpcsx2** [comment]
0 = load on boot
1 = load every vsync
2 = load immediately and every vsync (I think??) I forget, but I'm sure that mode was added because ssome people wanted them earlier.

**Comment by YukiXXL** [comment]
Works with patch=0,EE,...
Thank you.

I wonder what does EE stand for. I would appreciate the documentation or a source file link where the things are defined for it if you have the time to find it. Thank you again.

**Comment by refractionpcsx2** [comment]
It stands for emotion engine, `iop` is the other option so you can patch that side too

**Comment by RedDevilus** [comment]
> 0 = load on boot 1 = load every vsync 2 = load immediately and every vsync (I think??) I forget, but I'm sure that mode was added because some people wanted them earlier.

Yeah type 2 just combines type 0 on boot and type 1 for every vsync. I haven't seen many people use them as it's not only niche but a lot of people don't know it exists still :P
