### ISSUE TITLE
[BUG]: Vsync does not allow using frame limit option in Directx

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#11425]
### Describe the Bug

Since v1.7.5841, using directx does not allow you to use the frame limit (F4 or TAB keys by default). With vulkan it works

### Reproduction Steps

Enable vsync option, start a game and press F4 key

### PCSX2 Revision

v1.7.5912

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
Working as intended as far as I understand.

**Comment by JordanTheToaster** [comment]
Yes like I said it's intentional.
