### ISSUE TITLE
[BUG]: Tekken 5 PAL SCES-53202: Visual error when scaling image in Devil Within

### ISSUE THREAD

**Issue by PeterDelta** [PCSX2/pcsx2#11428]
### Describe the Bug

When you start Devil Within, some visual effects appear in the image that should not be there. Only happens when scaling from x2.

### Reproduction Steps

Start Devil Within, new game and when you move around the stage a little they begin to appear.

### Expected Behavior

clean image

### PCSX2 Revision

v.1.7.5912

### Operating System

Windows 11

### CPU

AMD Ryzen 5 5600H

### GPU

AMD Ryzen 5 5600H

### GS Settings

scaling x2

### Emulation Settings

default

### GS Window Screenshots

![Tekken 5_SCES-53202_20240619195454](https://github.com/PCSX2/pcsx2/assets/151682118/75d7c6e4-84f4-4aa2-99b5-1dcc57f5b5bb)

### Logs & Dumps

[Tekken 5_SCES-53202_20240619195454.gs.zst.zip](https://github.com/user-attachments/files/15904441/Tekken.5_SCES-53202_20240619195454.gs.zst.zip)

**Comment by JordanTheToaster** [comment]
We don't accept upscaling issues but also it looks fine here.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/0f992d3b-585e-4aee-a467-6068c0ae0b0a)
