### ISSUE TITLE
[BUG]: Inhibit screensaver doesn't work

### ISSUE THREAD

**Issue by inabareisen** [PCSX2/pcsx2#11437]
### Describe the Bug

The screensaver still activates even when the inhibit screensaver option is checked. I am using xss-lock on Arch Linux with X11.
I can use `loginctl lock-session` to activate the screensaver and `xdg-screensaver` from the command line works to inhibit and uninhibit the screensaver so xss-lock does indeed listen to DBus messages. I checked the PCSX2 code and it too uses DBus so it _should_ work, yet when I launch a game I get "Failed to inhibit screen saver" in the log window.

I'm using the official AppImage release of PCSX2.

### Reproduction Steps

xss-lock with i3lock as screensaver on Arch with nightly AppImage release of PCSX2 (v1.7.5913) downloaded from the official website.

### Expected Behavior

The screensaver should be inhibited.

### PCSX2 Revision

v1.7.5913

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### Logs & Dumps

[   23.1583] Failed to inhibit screen saver.

**Comment by stenzek** [comment]
Use bizarre setups, expect bizarre bugs. I'm not wasting hours setting up meme environments, sorry.

If you can debug what's going on, happy to provide a fix.

**Comment by spixi** [comment]
I have the same issue using PCSX2 v2.2.0 on Gentoo with LightDM as display manager.

I also would like to note that this is not a bizarre setup or a meme environment.
