### ISSUE TITLE
[BUG]: (CLI) Game with hyphen in name is taken as a flag

### ISSUE THREAD

**Issue by Maxsafer** [PCSX2/pcsx2#11438]
### Describe the Bug

When passed an iso through the CLI support on windows, that contains a hyphen e.g. "Guitar Hero Encore - Rocks the 80s (USA).iso" it takes the hyphen as a flag and as a result it says "Unknown parameter '-'".
Tested with an older version and this would not happen (1.6.0).

Version that has issue: pcsx2-v1.7.5913-windows-x64-Qt

### Reproduction Steps

D:/Downloads/EMULATORS/"PCSX2 1.6.0"/pcsx2-qt.exe "D:/Downloads/EMULATORS/PCSX2 1.6.0/games/Guitar Hero Encore - Rocks the 80s (USA).iso"

or

D:/Downloads/EMULATORS/"PCSX2 1.6.0"/pcsx2-qt.exe D:/Downloads/EMULATORS/"PCSX2 1.6.0"/games/"Guitar Hero Encore - Rocks the 80s (USA).iso"

### Expected Behavior

An iso being launched.

### PCSX2 Revision

v1.7.5913

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Not a bug.

If you read the command line help, that's why the `--` parameter exists.

**Comment by TheLastRar** [comment]
I would have thought that with the 1st example being in path being quoted would treat the whole thing as a path, regardless of spaces or hyphens contained within?

**Comment by Maxsafer** [comment]
> I would have thought that with the 1st example being a path being quoted would treat the whole thing as a path, regardless of spaces or hyphens contained within?

Me too... I have since added the "--" flag before my game file and it indeed works, sorry for misreading the doc.

**Comment by stenzek** [comment]
> I would have thought that with the 1st example being a path being quoted would treat the whole thing as a path, regardless of spaces or hyphens contained within?

We're not doing anything special with path parsing, if anything's doing it, it's Qt.

**Comment by TheLastRar** [comment]
I've managed to repo the issue using command prompt
The issue did not occur when I changed `D:/Downloads/EMULATORS/"PCSX2 1.6.0"/pcsx2-qt.exe` to `"D:/Downloads/EMULATORS/PCSX2 1.6.0/pcsx2-qt.exe"`
The issue did not occur when using powershell, even with the original command line.

This seems like a command prompt bug
