### ISSUE TITLE
[BUG]: Some textures pop and fade in Castlevania Curse of Darkness [SLUS-21168]

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#11436]
### Describe the Bug

Some textures show up and disappear as the screen rotates. Happens noticeably in HW, but hard to see in SW.

### Reproduction Steps

Use my savestate and rotate the screen.

### Expected Behavior

Static textures that don't disappear.

### PCSX2 Revision

1.7.5913

### Operating System

Windows 11

### CPU

I7-7600

### GPU

GTX 1050 TI

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Software:
https://github.com/PCSX2/pcsx2/assets/126727903/9264669b-3414-42b1-a808-919ae7734056

Vulkan:
https://github.com/PCSX2/pcsx2/assets/126727903/5e0dd2c8-9b73-4d74-8300-8ce311f90afc

### Logs & Dumps

Gs dumps:
[snaps.zip](https://github.com/user-attachments/files/15931583/snaps.zip)
Savestate:
[SLUS-21168 (3A446111).01.zip](https://github.com/user-attachments/files/15931584/SLUS-21168.3A446111.01.zip)

**Comment by JordanTheToaster** [comment]
Looks like z fighting which there isn't much you can do about if it's the game itself doing it even in software.

**Comment by refractionpcsx2** [comment]
Closing in favour of #3692 I have mentioned it there.
