### ISSUE TITLE
[BUG]: Cheat Engine Debugger not working

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#11433]
### Describe the Bug

When using Cheat Engine's debugger, it doesn't detect anything accessing the adress.
PCSX2 Debugger doesn't help when there are too many codes accessing one address and constantly pauses the game while Cheat Engine marks how many times which code accessed it and doesn't pause the game.

### Reproduction Steps

1. Open Cheat Engine and attach it to PCSX2 process.
2. Find the adress and press F5 or F6.

### Expected Behavior

Counts of codes accessing it appear in the small window.

### PCSX2 Revision

Latest Nightly

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
We can't provide guarantees when access counting from external processes.
Ensure that your address is part of the **EEMem** memory location.
Ensure that you've **disabled** the _EE Recompiler_ and the _Fast Memory Access_ options in the advanced tabs.

If you'd like more support, I recommend that you join our discord. We have a special channel for patching and reversing.

**Comment by YukiXXL** [comment]
Disabling Fast Memory Access helped. Thank you.
