### ISSUE TITLE
Kingdom Hearts 2 & Final Mix + Tron bug

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#11441]
### Describe the Bug

The lighting effects in certain areas of the Tron world do not behave correctly like they do in SW mode.

### Reproduction Steps

Go to Tron and observe the lighting on the floor.

### Expected Behavior

Should behave like SW mode. 

### PCSX2 Revision

v1.7.5913

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

https://drive.google.com/file/d/1E4uhSrdkNj20vvURYzKdxinjO4n-ZDiT/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Good old mipmapping shinanigans, probably supposed to be trilinear filtering between two textures, but for some reason it can't, there's a lot of things like this in HW.

Hopefully it can be fixed in the future.

**Comment by BParks21** [comment]
Thought it was mipmapping but wasn't sure.
