### ISSUE TITLE
[BUG]: Street Fighter Alpha Anthology + Vampire: Darkstalkers Collection - Lines when upscaled at x2 and more

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#11452]
### Describe the Bug

When upscaled, somes games in the collection have textures lines which weren't present before
Only Street Fighter Zero 3 + Pocket Fighter aren't affected.

Round Sprite Half is activated and doesn't solve everything.

### Reproduction Steps

Launch Street Fighter Zero 1, Darkstalkers

### Expected Behavior

No lines like here when the games were first solved https://github.com/PCSX2/pcsx2/issues/3481

### PCSX2 Revision

v1.7.5921

### Operating System

Windows 11

### CPU

7600x/i3-12100

### GPU

7900 XT / Intel UHD 730

### GS Window Screenshots

![Street Fighter Zero - Fighters Generation_SLPM-66409_20240623150711](https://github.com/PCSX2/pcsx2/assets/47425204/9e6e8f98-648b-47ed-8181-c7a9cceaf9f4)
![Street Fighter Zero - Fighters Generation_SLPM-66409_20240623150737](https://github.com/PCSX2/pcsx2/assets/47425204/bcfe5a35-0a66-42dc-8407-448ec301a9c8)
![Vampire Darkstalkers Collection_SLPM-65998_20240623150842](https://github.com/PCSX2/pcsx2/assets/47425204/e19ae370-a89e-4233-94da-7722e7fb6b05)

### Logs & Dumps

[snaps.zip](https://github.com/user-attachments/files/15944716/snaps.zip)

**Comment by refractionpcsx2** [comment]
1: as per the issue template we don't take upscaling issues
2: It's 2d, you can't upscale it, play it in native or software.

**Comment by Immersion95** [comment]
It's a shame, it was perfect before. Thanks anyway.

**Comment by Immersion95** [comment]
I’ve made a patch that outputs the game at 384×448, which results in pixel-perfect native resolution, since upscaling is broken for this game.

Check my PR in the patches repo there : https://github.com/PCSX2/pcsx2_patches/pull/714

**Comment by Gabriel2Silva** [comment]
> I’ve made a patch that outputs the game at 384×448, which results in pixel-perfect native resolution, since upscaling is broken for this game.
> 
> It's only for the japanese versions. I'll do the other regions if people are interested.
> 
> [CPS2_384x448_FINAL.zip](https://github.com/user-attachments/files/27320464/CPS2_384x448_FINAL.zip)

I am definitely interested in a patch for the US version. The unusual CPS2 ratio pisses me off tremendously.

**Comment by Immersion95** [comment]
> > I’ve made a patch that outputs the game at 384×448, which results in pixel-perfect native resolution, since upscaling is broken for this game.
> > It's only for the japanese versions. I'll do the other regions if people are interested.
> > [CPS2_384x448_FINAL.zip](https://github.com/user-attachments/files/27320464/CPS2_384x448_FINAL.zip)
> 
> I am definitely interested in a patch for the US version. The unusual CPS2 ratio pisses me off tremendously.

It's done, you can check it here : https://github.com/PCSX2/pcsx2_patches/pull/714.

I've aldo done it for SFIII:3S.

Just go to "files changed" and download the one that you want.

Please tell me if you encounter any bug :).
