### ISSUE TITLE
[BUG]: RetroAchievements - Leaderboard download failed

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#11451]
### Describe the Bug

Opening any leaderboard in DuckStation/PCSX2's pause menu shows the following error.
![image](https://github.com/PCSX2/pcsx2/assets/4414625/0c1dbfa5-4182-41ca-9f80-7b0c33873a56)

### Reproduction Steps

1. Enable RetroAchievements
2. Start any game with leaderboards (such as GT4)
3. Open Pause menu
4. Try to open any Leaderboards
5. Error happens

### PCSX2 Revision

1.7.5921

### Operating System

Windows 11

**Comment by kamfretoz** [comment]
Can confirm.

![image](https://github.com/PCSX2/pcsx2/assets/14798312/7899fe6d-3bc7-46b6-a6c4-d6d277e9f451)

**Comment by stenzek** [comment]
Sounds like an upstream API change.

**Comment by stenzek** [comment]
Works fine here. Maybe a temporary server issue.

I'll bump rcheevos anyway.
