### ISSUE TITLE
Lighting is a bit broken in Ratchet & Clank 3

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#11465]
### Describe the Bug

On Aquatos there is a little rendering bug at the beginning. The door's lights look pixelated.
![Screenshot 25-06-2024 18-16-11](https://github.com/PCSX2/pcsx2/assets/90133207/d09ad55b-83e1-43c0-b35c-ec7b011fe488)
Blending accuracy (minimum) fixes this, but brokes shadows.
![Screenshot 25-06-2024 18-16-35](https://github.com/PCSX2/pcsx2/assets/90133207/c6fdf708-b67a-42d0-bc7b-3e0a8f8aa932)
![Screenshot 25-06-2024 18-17-10](https://github.com/PCSX2/pcsx2/assets/90133207/6e55bbe2-0e47-4628-953f-cce8a2f5dd05)

### Reproduction Steps

Go to Aquatos

### PCSX2 Revision

v1.7.5935

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/eb0dcf83-c06b-477a-9429-134a5d9a5712)
please reset settings , please put dithering and aniso back to default

**Comment by EvilPlayer1** [comment]
> ![image](https://private-user-images.githubusercontent.com/17685135/342930828-eb0dcf83-c06b-477a-9429-134a5d9a5712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTAyODIsIm5iZiI6MTcxOTM0OTk4MiwicGF0aCI6Ii8xNzY4NTEzNS8zNDI5MzA4MjgtZWIwZGNmODMtYzA2Yi00NzdhLTk0MjktMTM0YTVkOWE1NzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIxMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTVmMTkyNWY3NDc4OGE4NGU0ZmMxMmU2MjBiOWRhMzY0ODhjNTdjNDEwYTI1MzA4MjIzODA4MmVmMGM1MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yuyAaYcgTtwok59Tgb1sqan_z6rfgSkO0QdIB1SzVdU) please reset settings , please put dithering and aniso filtering back to default

didn't help

**Comment by refractionpcsx2** [comment]
Can you post a GS Dump of the issue, get it on screen then go to Tools->Single frame GS Dump, then Tools-Open Data Folder and navigate to `snaps` to find it and post it here (you will need to zip it up)

**Comment by EvilPlayer1** [comment]
[bug.zip](https://github.com/user-attachments/files/15979512/bug.zip)

**Comment by JordanTheToaster** [comment]
Looks identical to software so I'm not sure what the issue is.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/6cb63bdb-a6c9-4836-8f45-f2652ed75f11)

![image](https://github.com/PCSX2/pcsx2/assets/80843560/553c0446-c893-4fb6-a73f-60b6ce1858c6)

**Comment by EvilPlayer1** [comment]
> Looks identical to software so I'm not sure what the issue is.
> 
> ![image](https://private-user-images.githubusercontent.com/80843560/342969393-6cb63bdb-a6c9-4836-8f45-f2652ed75f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjY4NTMsIm5iZiI6MTcxOTM2NjU1MywicGF0aCI6Ii84MDg0MzU2MC8zNDI5NjkzOTMtNmNiNjNiZGItYTZjOS00ODM2LThmNDUtZjI2NTJlZDc1ZjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAxNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMmVjODE1ZTIyYjk1MjAwYWFjN2E1NjU0ODRkNmNkNjhlNTFlMDhmYTIyN2Y0MzNjNWZmMjhhODI3OTE1NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2CUdq9_OMOaJcgwCjrGHf96V9Wb2NRDxAJKiygnzyI)
> 
> ![image](https://private-user-images.githubusercontent.com/80843560/342969437-553c0446-c893-4fb6-a73f-60b6ce1858c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjY4NTMsIm5iZiI6MTcxOTM2NjU1MywicGF0aCI6Ii84MDg0MzU2MC8zNDI5Njk0MzctNTUzYzA0NDYtYzg5My00ZmI2LWE3M2YtNjBiNmNlMTg1OGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAxNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmY2IyMjkwZWI3YjlkMjAxZmNlMGY5NzM1YmI2MTJkMGM4OThkNTAxNDFiOGQyZmMwOWRiMDliMmUwNjlmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dk99hMS6Z8jy5rzacGGb0_8X16GNwid_dmgr45pB2jA)

![Screenshot 26-06-2024 04-50-44](https://github.com/PCSX2/pcsx2/assets/90133207/53ae5176-851f-4315-9b79-dda8934845ec)
broken and blurred upscaling

**Comment by JordanTheToaster** [comment]
>  broken and blurred upscaling

**We do not accept issues relating to upscaling at this time.
We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling.**

**Comment by stenzek** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/11288319/5072267f-15e2-4447-b95d-245def285c81)

Downsampled postfx, it's going to be broken when the input texture is much smaller than the render target, and exacerbated the higher you upscale.

**Comment by EvilPlayer1** [comment]
> ![image](https://private-user-images.githubusercontent.com/11288319/342984266-5072267f-15e2-4447-b95d-245def285c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTg3NTQsIm5iZiI6MTcxOTQxODQ1NCwicGF0aCI6Ii8xMTI4ODMxOS8zNDI5ODQyNjYtNTA3MjI2N2YtMTVlMi00NDQ3LWI5NWQtMjQ1ZGVmMjg1YzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTUwODA1YWRiYzhkZWQ5ZGNlMTFmNzUxZjdjYmUzZDYwMWE1ZGJhZTVkYzVlNzM3NGJhNjc4YTE5ZTEyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZUUS8KO9GDmlAY0Z5TxG2kgR-rEiHtCHv8V-TvlzqaA)
> 
> Downsampled postfx, it's going to be broken when the input texture is much smaller than the render target, and exacerbated the higher you upscale.

![Screenshot 26-06-2024 19-16-30](https://github.com/PCSX2/pcsx2/assets/90133207/5c444ed1-8155-4d86-ad3a-011f79f34cc0)
and how you'll explain this? you think it's normal behavior with default settings? pixelated garbage is everywhere

**Comment by JordanTheToaster** [comment]
>and how you'll explain this? you think it's normal behavior with default settings? pixelated garbage is everywhere

You are upscaling it was explained what the problem was.

**Comment by EvilPlayer1** [comment]
![Screenshot 26-06-2024 19-35-09](https://github.com/PCSX2/pcsx2/assets/90133207/42468fc8-f92c-4e90-a747-5fba4b9af389)
![Screenshot 26-06-2024 19-35-15](https://github.com/PCSX2/pcsx2/assets/90133207/28f80a15-6bd7-4215-9432-0d9594c03d02)
I turned on hacks and now it's fixed. Just like in native rendering

**Comment by refractionpcsx2** [comment]
It's because the effectrs are being natively scaled, making everything native resolution isn't "Fixing" it, it just makes everything else suck too.

If you wait for stens Box Filter PR, it will look less sucky, but you can't have upscaling and have the lights not completely destroyed, garbage and off centre, and have it look super pretty.

**Comment by EvilPlayer1** [comment]
![Screenshot 26-06-2024 19-54-51](https://github.com/PCSX2/pcsx2/assets/90133207/b5ca62fe-1f09-4506-92d0-bfbfae7f8c28)
With this settings it looks good I think.
But there's also a noticeable "drawing line"
![Screenshot 26-06-2024 19-57-00](https://github.com/PCSX2/pcsx2/assets/90133207/4f4b2c43-c568-489f-bbaa-b1a448c66ef7)
which can be fixed by gpu palette conversion
![Screenshot 26-06-2024 20-00-58](https://github.com/PCSX2/pcsx2/assets/90133207/f3e06eab-a2a4-4439-bcd9-d78ca11a15b5)
I've heard that R&C 3 uses some kind of blur technology, so the problem is that Aquatos needs special settings to work correctly, while other planets don't need more than default settings

**Comment by refractionpcsx2** [comment]
IT's not really fixed if *all* your lighting is gone, is it
