### ISSUE TITLE
How to compile PCSX2 in Linux 64bit?

### ISSUE THREAD

**Issue by jobs-git** [PCSX2/pcsx2#1146]
Help would me much appreciated

**Comment by willkuer** [comment]
http://lmgtfy.com/?q=How+to+compile+PCSX2+in+Linux+64bit%3F

We have a forum for such questions...

**Comment by gregory38** [comment]
https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux

http://wiki.pcsx2.net/index.php/PCSX2_Documentation/Chroot_and_64-bit_Linux

**Comment by jobs-git** [comment]
Haha, Thanks! I am gonna test it sooner after build :)
