### ISSUE TITLE
[Feature Request]: Separate model texture filtering from sprite texture filtering

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#11478]
### Description

Bilinear filtering looks great on model textures, but not UI, sprites, and icons, and nearest looks great on UI and sprites, but looks bad on 3D models, its a win/lose situation on both cases, so why not do what Duckstation does?

![image](https://github.com/PCSX2/pcsx2/assets/72826232/9a308c0b-6b67-472a-aeee-4b69c500dd19)

It's a problem that's bugged me personally on PSX since I don't remember when, but at least nearest on PS1 doesnt look as bad (since the PS1 was designed with nearest in mind and did not support bilinear)

### Reason

Make UI's crisp and clear without the need of HD texture packs or forcing the whole game to run as nearest
### Examples

I attach some examples, this happens on every (almost) all PS2 games with any of the bilinear options.

Dual Hearts:
![image](https://github.com/PCSX2/pcsx2/assets/72826232/64eceb1f-93dc-434c-ac29-3225a4d51527)
![image](https://github.com/PCSX2/pcsx2/assets/72826232/55b08ae2-08ce-405f-9b3e-94b704eb2930)
Rogue Galaxy:
![image](https://github.com/PCSX2/pcsx2/assets/72826232/5c6b2a67-078e-4885-9ca2-1920185411f4)
![image](https://github.com/PCSX2/pcsx2/assets/72826232/f5592277-73d9-4835-8724-85ad6915202a)
Blood Will Tell:
![image](https://github.com/PCSX2/pcsx2/assets/72826232/d44e1a74-7aa3-448f-813c-0a26a0ec4215)
![image](https://github.com/PCSX2/pcsx2/assets/72826232/c80f0f01-2f39-43fe-a4ee-883862445272)
Shadow of Rome
![image](https://github.com/PCSX2/pcsx2/assets/72826232/0840b4be-ae8f-45bc-8945-f70c12a98871)
![image](https://github.com/PCSX2/pcsx2/assets/72826232/548b0669-e7ae-4265-90de-c4f80e2ed4bd)

As you can see, UI elements, icons, text, become ultra sharp and very crisp, instead of the blurry mess that is shown with bilinear.

**Comment by refractionpcsx2** [comment]
The only problem with this request is a lot of downsampling (blur/post effects) are done with sprites, and they will *require* bilnear.

The GS doesn't have any "this is UI" specifiers or anything.  I guess we could say if it's not currently a render target then do it, I guess...

**Comment by NineKain** [comment]
There is no hurry, just something I'd really love, since I love user interfaces, and I love when they are crisp!

**Comment by stenzek** [comment]
-1. Any heuristics here are going to be very unreliable and break things, just like the force bilinear mode.

**Comment by MrCK1** [comment]
Closing since it is not really a feasible option at this time.
