### ISSUE TITLE
[BUG]: Debugger: "Copy segment" does not work in Memory Viewer

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#11487]
### Describe the Bug

In PCSX2 debugger, you can see "Copy segment" in context menu of Memory Viewer. But it just copies 1 byte instead.

### Reproduction Steps

1. Run a random game
2. Open PCSX2 debugger
3. Go in "Memory" tab
4. Right-click anywhere in memory viewer
5. Hit "Copy segment"
6. Paste the copied data to somewhere like text editor
7. You can see just one byte data was copied

### Expected Behavior

It should copy a segment (4 bytes data) instead.

### PCSX2 Revision

v1.7.5947

### Operating System

Windows 11

**Comment by F0bes** [comment]
It trims when it probably shouldn't. 0x00000012 -> 0x12.
But I can't reproduce it copying one byte.

**Comment by Berylskid** [comment]
> In your reproduction steps, you didn't mention switching the view to 4 bytes. Just so we are on the same page, the segment size is dependent on what byte view you have selected. (Show as 8 bytes = 8 byte segment size)

That makes sense. Sorry for bothering.
