### ISSUE TITLE
Missing wxWidgets in Fedora

### ISSUE THREAD

**Issue by jobs-git** [PCSX2/pcsx2#1149]
In case you get wxWidget not found, this might happen if you did not specify sdl-1.2 while using wxGTK 2.8, by default the build.sh will attempt to compile with SDL2 which however not compatible with wxGTK 2.8, thus the error occur. To fix this, you should just do:

    build.sh --wx28 --sdl12

**Comment by gregory38** [comment]
Please this isn't a forum. It already difficult enough to find real issues.
