### ISSUE TITLE
[BUG]: Harvest Moon a wonderful life special edition ISSUE EVERY I ALREADY ON DATE 7

### ISSUE THREAD

**Issue by terserah47** [PCSX2/pcsx2#11494]
### Describe the Bug

I dont know why its always to be like this, but when i sleep and the date is 7 Spring (new game) its crash, always tired and its repeatedly always sleep by himself every time the character woke up and he sleep again because tired. I tried a new game and just sleep until date 7, and then still sleep again n again. I turn on the never tired cheat its still like that

### Reproduction Steps

i dont know, please help me

### PCSX2 Revision

v1.7.5953

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Please use the discord for support, this isn't the place for it. https://discord.com/invite/TCz3t9k
