### ISSUE TITLE
[BUG]: Kuma Uta - Name Input Character Panel Corrupt

### ISSUE THREAD

**Issue by JWatersMeet** [PCSX2/pcsx2#11496]
### Describe the Bug

The name input panel at the start of Kuma Uta is corrupt. The selection lens moves between the characters, but the characters themselves are not drawn correctly.

This happens on all rendered types, including Software.

GS Dump and screenshot below.

### Reproduction Steps

1. Start Kuma Uta
2. Click through the opening scenes to the name entry dialogue
3. Notice that the characters are not displayed correctly in the selection panel.

### Expected Behavior

Each japanese character should be visible in it's own square.

### PCSX2 Revision

v1.7.5953

### Operating System

Windows 11

### CPU

Ryzen 5900HX

### GPU

Built-In Graphics

### GS Window Screenshots

[Kumauta_SCPS-11031_20240703135941.zip](https://github.com/user-attachments/files/16085453/Kumauta_SCPS-11031_20240703135941.zip)
4764-0381-4c83-937c-3033d86457aa)
![Kumauta_SCPS-11031_20240703135941](https://github.com/PCSX2/pcsx2/assets/136824455/6843bdce-d1e6-4ec7-b6a1-1869f15ba997)

**Comment by Buzzardsoul** [comment]
Not a GS issue:

![image](https://github.com/user-attachments/assets/2c16b8cd-d26a-442a-b53a-e74fbd489384)

**Comment by Buzzardsoul** [comment]
@JWatersMeet Can you start the game with ee clamp mode set to full? It strangely fixed it for me.

**Comment by Mrlinkwii** [comment]
@Buzzardsoul  starting the game with clamping full can fix it

**Comment by Buzzardsoul** [comment]
> @Buzzardsoul starting the game with clamping full can fix it

Nice! I'll create a pr for this when I can. Also, it seems extra + preserve sign can also fix it. Strange game.

**Comment by Mrlinkwii** [comment]
@Buzzardsoul  you can add it to the pr alrerady open , id say use v over sign

**Comment by JWatersMeet** [comment]
Sorry for the late reply - yes full clamping fixes this.
