### ISSUE TITLE
Baldur's Gate Dark Alliance II - Interlace issues, Occasional tree polygon stretching 

### ISSUE THREAD

**Issue by Ceekur** [PCSX2/pcsx2#1151]
Just a small issue considering Baldur's Gate DA 2. While it works quite well now on PCSX2 1.4.0, I was encouraged to make this post on two issues. In certain outdoor maps, the polygons of trees will occasionally go wacky across the screen based on where you walk, such as seen in the attached image. This occurs regardless of texture filtering modes, hardware / software, CRC Level, or other option toggles. Without any trees, everything is rendered without issue (second image).

There is also a general issue of interlacing, where the HUD requires it (usually Auto or Blend) to keep it from jumping, but the actual 3D world benefits from None, otherwise the ground texture will blur as you move.

![bugpcsx2baldurtrees](https://cloud.githubusercontent.com/assets/16966633/12691989/19276542-c6a6-11e5-8ed3-60030f7272e8.png)

![emubgda2c](https://cloud.githubusercontent.com/assets/16966633/12692008/5825d63e-c6a6-11e5-81f4-dcdab65e674d.png)

**Comment by willkuer** [comment]
Please check different vu settings. Possibly vu clamping to full+preserve sign fixes this issue.

**Comment by Ceekur** [comment]
VU and EE settings are both already on Full or Extended. This was required to fix the black texture / slow texture pop-in issue I used to have.

**Comment by willkuer** [comment]
Vu rounding/supervu?

**Comment by Ceekur** [comment]
None of the VU0 / VU1 settings, as well as Advanced Recompiler modes affected the tree polygons at all.

**Comment by willkuer** [comment]
Great thank you. I would still guess that this is some kind of vu floating point precision issue but maybe its indeed not fixable using current code. Lets hope one of the devs has the game and energy to tackle this issue.

**Comment by refractionpcsx2** [comment]
How about speedhacks? Have you got any of them turned on? maybe the mVU Flag Hack makes a difference.

**Comment by Ceekur** [comment]
EE Cycle 1, INTC Spin, Wait Loop, and mVU Flag were on. However turning them all off also had no effect (other than a higher EE percentage, naturally).
The stretched polygons for the trees aren't permanent when you're outside, just occasionally when you're run along, you'll see a stretch of them across your screen for an instant. If you stand still, you can find a spot that does it, but it'll only be a flicker if you're playing the game normally, running along and fighting monsters.

**Comment by refractionpcsx2** [comment]
I just had a run around for a bit and didn't experience a single glitch anywhere. I'd suggest deleting all your PCSX2 ini's and trying the game again on default settings, if that doesn't work, try the newest GIT version as that's what I'm using and there is no problems.

**Comment by gregory38** [comment]
@Ceekur Does the issue still occured ?

**Comment by Ceekur** [comment]
Yes, it still occurs in a recent GIT version of 1.5 (it's a minor issue in motion though). Oddly when I tested after a settings adjust, the beginning of the game was fine, but it popped back up during the Red Fang quest and in the Air Realm, where there are more trees.

**Comment by MrCK1** [comment]
I was just looking around and maybe this is related to #954?

As stated in #954, try switching VU0 to Interp and see if it changes slightly?

**Comment by gregory38** [comment]
@Ceekur A fix was done on the VU. Could you retest latest GIT.

**Comment by ramapcsx2** [comment]
I've tried reproducing it. No tree SPS. I couldn't get it to happen on an older build either.
Also I've never seen it happen back when the game had the half-screen issue.

**Comment by MrCK1** [comment]
@Ceekur were you running any other external tools with Windows when you experienced this bug?

**Comment by MrCK1** [comment]
Should we just close this/mark as invalid at this point? User never responded, we don't know what external programs were running; and nobody has been able to reproduce this.

**Comment by ramapcsx2** [comment]
Yep.
