### ISSUE TITLE
[BUG]: NULL graphic render eats up RAM.

### ISSUE THREAD

**Issue by foxsevent** [PCSX2/pcsx2#11510]
### Describe the Bug

Been doing some automated grinding in KH FIM and to get the most FPS I selected the NULL rendered since all I need to do is hold a button and after a while I noticed that PCSX2 would crash, after some investigating I noticed that PCSX2 with the NULL rendered selected continues to increase RAM usage until it crashes I assume.

### Reproduction Steps

Just start any game with the NULL graphic render selected and watch the RAM usage slowly rise.

### Expected Behavior

Switching to any other render fixes the issue and restores normal RAM usage.

### PCSX2 Revision

PCSX 1.7.5957

### Operating System

Windows 11

### Logs & Dumps

Here are the dump files of the latest crash and a screenshot of RAM usage after few mintues.
[PS2.zip](https://github.com/user-attachments/files/16117455/PS2.zip)
![Przechwytywanie](https://github.com/PCSX2/pcsx2/assets/64225743/dc37f090-97c1-48d0-832a-ef0dec3ada76)

**Comment by escape209** [comment]
I was able to reproduce this. It seemed to be worse in some games than others, but I observed a memory leak of about 100MB per minute with Burnout Dominator using Null renderer, about half that in Burnout, and over 200MB per minute in Ratchet and Clank.
