### ISSUE TITLE
Compilation error: no matching function for call to ‘wxString'

### ISSUE THREAD

**Issue by jobs-git** [PCSX2/pcsx2#1152]
I am compiling pcsx2 in Linux and have satisfied all dependency including wxWidget-2.8, gtk2 and sdl1.2. When I run make, it stops in compiling `Dump.cpp` and then throws the error above. How do I fix this?

These are some Details:

```
pcsx2/pcsx2/Dump.cpp: In function ‘void iDumpBlock(u32, u32, uptr, u32)’:
pcsx2/pcsx2/Dump.cpp:257:62: error: no matching function for call to ‘wxString::Format(const char [101], uptr, const wxChar*, const wxChar*)’
     (u32) x86_pc, WX_STR(obj_filename), WX_STR(dump_filename))
                                                              ^
pcsx2/pcsx2/Dump.cpp:257:62: note: candidate is:
In file included from pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from pcsx2/pcsx2/PrecompiledHeader.h:25,
                 from pcsx2/pcsx2/Dump.cpp:16:
/usr/include/wx-2.8/wx/string.h:1208:19: note: static wxString wxString::Format(const wxChar*, ...)
   static wxString Format(const wxChar *pszFormat, ...) ATTRIBUTE_PRINTF_1;
                   ^
/usr/include/wx-2.8/wx/string.h:1208:19: note:   no known conversion for argument 1 from ‘const char [101]’ to ‘const wxChar* {aka const wchar_t*}
```

**Comment by gregory38** [comment]
wx2.8 isn't supported anymore on dev branch. So either you switch to the stable version. Or you upgrade to wx3.0. I will completely remove wx2.8 from git.

**Comment by jobs-git** [comment]
When I set wx3.0, the compilation wont get past, it says 3.0 is experimental.

**Comment by gregory38** [comment]
The experimental part is GTK3, not wx3.0. Could you past me the log because it must compile normally. Except --extra plugin which aren't supported anymore.

**Comment by jobs-git** [comment]
I guess its the GTK3, as far as I can remember when I did the build process while enabling wx3.0, it goes with SDL2 and GTK3. I will post a log of that, as of now I am trying to recompile wx since the default package of fedora does not go nicely with PCSX2.

**Comment by gregory38** [comment]
Otherwise someone posts a PR with a fix. And you can still use the stable branch 1.4.x

**Comment by jobs-git** [comment]
The problem was on Fedora, default wx3.0 package was on GTK3 by default so causing the compilation halt on PCSX2, now, when I used my manual compiled wx3.0 with gtk2, proceeds as it should, will close this now.
