### ISSUE TITLE
[BUG]: ShanWan  PC/PS3/Android Gamepad,GUID:03000000632500007505000011010000

### ISSUE THREAD

**Issue by 22612091009** [PCSX2/pcsx2#11523]
### Describe the Bug

Hi mate, my device can detect gamepad use jstest but pcsx2 not support my gamepad

### Reproduction Steps

![2024-07-09-20:40:11-screenshot](https://github.com/PCSX2/pcsx2/assets/162968785/51598115-964a-4b68-91a5-66a4e678dc67)

### PCSX2 Revision

Latest Stable

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Endevour OS

### Logs & Dumps

uspending single plugin: PAD
	Saving PAD
onepad: Joystick (ShanWan     PC/PS3/Android Gamepad,GUID:03000000632500007505000011010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (ShanWan     PC/PS3/Android Gamepad,GUID:03000000632500007505000011010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.Recovering single plugin: PAD

**Comment by JordanTheToaster** [comment]
Please use the Discord for support.

**Comment by lightningterror** [comment]
The controller is supported if you use update to latest dev.
