### ISSUE TITLE
[BUG]: Debugger: Function list keeps displaying functions of first booted game

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#11529]
### Describe the Bug

PCSX2 debugger keeps displaying functions of first booted game.
- After shutting down VM, it refuses to refresh.
- So for example at current master, I have to close PCSX2 every time I compare some functions between similar games.

### Reproduction Steps

1. Run PCSX2.
2. Open debugger.
3. Boot a random game.
4. Shut down VM after function list gets generated.
5. Boot another game.
6. Now debugger keeps displaying same functions and refresh button does nothing.

### Expected Behavior

Function list should display currently running game's functions.

### PCSX2 Revision

v1.7.5973

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
i think you need to refresh for it to update

**Comment by Berylskid** [comment]
I wrote it didn't work at the 6th reproduction step... Sorry, I should've written it in Description section as well.

**Comment by F0bes** [comment]
https://github.com/PCSX2/pcsx2/pull/10224 completely rewrites the symbol system. If it still does not work after that PR is merged, I will look into it. No point now because it'll probably just cause merge conflicts and be erased.

**Comment by Berylskid** [comment]
Fixed as of 2.1.212.
