### ISSUE TITLE
[BUG]: Link to BIOS dumping incorrect

### ISSUE THREAD

**Issue by Jacko123490** [PCSX2/pcsx2#11524]
### Describe the Bug

In the setup wizard, on the BIOS image stage there is a link to the guide on dumping a PS2 BIOS. 
![image](https://github.com/PCSX2/pcsx2/assets/88093156/dbed11ed-1edb-4bf9-b09a-69d3f58386e0)

This link appears to be broken and gives a "page not found message".

The hyperlink used is: https://pcsx2.net/docs/setup/gather#how-to-dump-your-ps2-bios
I am assuming it is supposed to be linking to this page: https://pcsx2.net/docs/setup/bios/ 

### Reproduction Steps

- Run the PCSX2 setup wizard.
- Continue to the BIOS Image step
- Click the link marked "here" in the text on dumping a PS2 BIOS

### PCSX2 Revision

v1.7.5971

### Operating System

Windows 10 (64bit)

**Comment by kamfretoz** [comment]
Oh right, i forgot to update the link. Fix is coming soon.

**Comment by Mrlinkwii** [comment]
check #11525  for me when its built
