### ISSUE TITLE
[BUG]: Without Warning freezes in the menu

### ISSUE THREAD

**Issue by Sapelain** [PCSX2/pcsx2#11536]
### Describe the Bug

I start the game, I pass the language selection when at most 5 seconds have passed in the game's initial menu, the game freezes.
It doesn't matter if you change vulcan or opengl or directx. Does not work.
I have tested it on an old version (PCSX2 v1.7.3771 AVX2) that I have and it works perfectly.

### Reproduction Steps

https://streamable.com/bpiwy6?src=player-page-share
[emulog.txt](https://github.com/user-attachments/files/16189414/emulog.txt)

### PCSX2 Revision

PCSX2 QT 1.7.5976

### Operating System

Windows 10 (64bit)

**Comment by kamfretoz** [comment]
Please use Discord for support.
