### ISSUE TITLE
[Feature-Request] Remote GS window

### ISSUE THREAD

**Issue by marcussacana** [PCSX2/pcsx2#1154]
Could create a plugin to allow i play ps2 games in my psp using the pcsx2 + wifi or usb connection...?

For sample the PSPDisp shows the windows screen in the psp, if exist a way to run the pcsx2 minimized playing in my psp and same time allowing another person use my computer ^^

**Comment by refractionpcsx2** [comment]
I have answered your question here: http://forums.pcsx2.net/Thread-Special-GS-plugin-request

It isn't really something we can do with a plugin, you would need to find better tools to stream individual windows.
