### ISSUE TITLE
[Feature Request]: D3D12 renderer support for feature level 12_1 or higher to fix blending support

### ISSUE THREAD

**Issue by Kirby0Louise** [PCSX2/pcsx2#11543]
### Description

Having read the recent PCSX2 2.0 blog post, I was surprised to learn that the D3D backends supposedly "lack features" for blending.  After taking a quick look at the code, I think I found the problem:  D3D devices are initialized [with](https://github.com/PCSX2/pcsx2/blob/2f46e5a8406e4832ba60c5ab1ba2fd16a074ab1f/pcsx2/GS/Renderers/DX12/GSDevice12.cpp#L181) FL 11_0, rather than FL 12_1 or 12_2, which include support for Rasterizer Ordered Views, a technique in D3D that allows for accurate, custom blending.

Other emulators such as Xenia have shown ROV is a proven method for emulating custom blending and even solving bugs on Intel GPUs

### Reason

This is a good feature to add because it will improve accuracy on the D3D12 backend, which is particularly important for the community Xbox ports of PCSX2 (as these consoles only support other APIs via a translation layer that can sap performance).  D3D12 is also compatible with Window's built in AutoHDR and AutoSR features, while other backends are not.  Also mentioned in the PCSX2 2.0 blog post was instability on Intel GPUs in GL and Vulkan, this would provide a stable backend with improved accuracy support for these machines.

### Examples

https://www.intel.com/content/www/us/en/developer/articles/technical/rasterizer-order-views-101-a-primer.html
https://learn.microsoft.com/en-us/windows/win32/direct3d12/rasterizer-order-views
https://github.com/xenia-project/xenia/wiki/ROV

**Comment by JordanTheToaster** [comment]
Already a thing #7655

**Comment by Kirby0Louise** [comment]
Thanks.  It would still be prudent to init with the highest feature level available to the device instead of defaulting to 11_0.

**Comment by RedDevilus** [comment]
> Thanks. It would still be prudent to init with the highest feature level available to the device instead of defaulting to 11_0.

I don't see how bumping the minimum feature level would help with the discrepancy of blending accuracy compared to like Vulkan side.

**Comment by Kirby0Louise** [comment]
It doesn't, but it's still good practice to ask for the highest feature level available unless you have a good reason to use a lower one.  Regardless if ROV is supported there shouldn't be any trouble supporting required blending.
