### ISSUE TITLE
[BUG]: Your Microsoft Visual C++ Runtime appears to be too old for this build of PCSX2

### ISSUE THREAD

**Issue by ivadham** [PCSX2/pcsx2#11558]
### Describe the Bug

![old](https://github.com/user-attachments/assets/2b164b55-dece-45c0-aef4-4983a5b4f8f8)

While the latest version of VC_redist.x64.exe is installed, the "Old Visual C++ Runtime Detected" part of PCSX2 still insists that the runtime appears to be too old.

My current version is 14.40.33810.0
The "Old Visual C++ Runtime Detected" mistakenly reports: 14.26.28720.3

### Reproduction Steps

Just launch the PCSX2. Restarting the system won't help.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 11

**Comment by ivadham** [comment]
OK, I looked at the code in VCRuntimeChecker.cpp. There are multiple msvcp140.dll files on my PC, but I guess our main focus should be on two of them:

- C:\Windows\SysWOW64\msvcp140.dll (Current version: 14.40.33810.0)
- C:\Windows\System32\msvcp140.dll (Current version: 14.26.28720.3)

**Comment by ivadham** [comment]
This is interestingly odd! While Microsoft Visual C++ 2015-2022 Redistributable - 14.40.33810.0 was installed (I double-checked in Programs and Features), I had to download VC_redist and choose the "Repair" option to reinstall it.

It is fixed now. Thanks!

**Comment by ivadham** [comment]
> It would seem like you updated your 32-bit runtime, while PCSX2 needs the 64-bit runtime.

That's the point, but the other way around.

The SysWOW64's version, as I mentioned above, was 14.40.33810.0, which was already higher than the minimum required version (14.38.33135.0).

So, the checking should have passed successfully, but it didn't.
I think the `VCRuntimeCheckObject` is targeting the msvcp140.dll file in the System32 folder, which is the 32-bit runtime. So basically, `VCRuntimeCheckObject` is looking for and validating the wrong file for the 64-bit architecture.

Correct me if I’m wrong, @CookiePLMonster.

**Comment by CookiePLMonster** [comment]
SysWOW64 files are the 32-bit libraries on the 64-bit systems. system32 is the "native" 64-bit files.

**Comment by ivadham** [comment]
Oh, I see. Thanks.
