### ISSUE TITLE
[BUG]: Graphics issue in DQ8

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#11559]
### Describe the Bug

After the healing effect this popped up:
![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20240715093624](https://github.com/user-attachments/assets/f94ac520-a085-47e1-998d-aa2539d493cd)

### Reproduction Steps

Go into the water and let yourself heal
[SLES-53974 (945FBF31).01.p2s.zip](https://github.com/user-attachments/files/16231397/SLES-53974.945FBF31.01.p2s.zip)

### Expected Behavior

No glitches

### PCSX2 Revision

v2.0.2

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04

### CPU

i7-11700B

### GPU

GTX 1050

### GS Settings

widescreen, IR x6, texture dumping

### GS Window Screenshots

[snaps.zip](https://github.com/user-attachments/files/16231377/snaps.zip)

**Comment by bigol83** [comment]
CPU Sprite Render at 3 Blended sprite/triangles fixes it but introduces other side effects. This issue seems to happen only in healing water. I checked reproducing it while standing in normal water and it doesn't happen. It also happens while going from menu to ingame, not just after the healing effect, still only when you are in healing water.

**Comment by Kupo91** [comment]
Here is another spot:
https://youtu.be/hf7BJnIbBDE
The glitch is also visible in the sequence after the heal
[SLES-53974 (945FBF31).01.p2s.zip](https://github.com/user-attachments/files/16247421/SLES-53974.945FBF31.01.p2s.zip)

**Comment by bigol83** [comment]
Yeah, it happens during transitions near healing water. Rather specific issue.

**Comment by Kupo91** [comment]
The corruption started with https://github.com/PCSX2/pcsx2/releases/tag/v1.7.5659

**Comment by bigol83** [comment]
So, it's this PR https://github.com/PCSX2/pcsx2/pull/10974
