### ISSUE TITLE
[BUG]: ATV Offroad Fury 3 does not use multithreading/only uses one thread

### ISSUE THREAD

**Issue by iocked1337** [PCSX2/pcsx2#11557]
### Describe the Bug

In ATV Offroad Fury 3, I've found a bug that does not distribute the load of processing across all cores provided to the application. This comes into effect moreso with systems that do not score above ~1800 on Geekbench 6. To make this problem go away, enable EE Cycle Skipping, though this will severely impact performance.

### Reproduction Steps

Play on default settings, other ATVs being rendered will slow down the game by a given (if not significant) amount, depending CPU performance. 

### Expected Behavior

Simulation speed should not change, only the emulated console's framerate.

### PCSX2 Revision

v2.0.3

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

"Steam OS Holo" 3.6.8

### CPU

AMD Custom APU 0405 (Steam Deck)

### GPU

AMD Custom GPU 0405 (Steam Deck)

### Emulation Settings

To make this problem go away, enable EE Cycle Skipping, though this will severely impact performance. 

All other settings have been tested, or left to default.

**Comment by JordanTheToaster** [comment]
The game is working as intended it has MTVU disabled I presume to prevent issues so the EE load is very high while the Steam Decks CPU is fairly weak. On my 5600x the game runs fine so I see no issues here.

![image](https://github.com/user-attachments/assets/49b2a595-ffcc-4bf6-8725-6196ed62d38a)

**Comment by iocked1337** [comment]
"Play on default settings, other ATVs being rendered will slow down the game by a given (if not significant) amount, depending CPU performance."

Try a Championship or Single Event instead, with AI.

**Comment by JordanTheToaster** [comment]
> Try a Championship or Single Event instead, with AI.

Also works fine but I can see it has a readback which will tank performance even more for the Steam Deck you can try disable those in game properties > advanced otherwise the game is just heavy and won't run well on weaker hardware like yours.

**Comment by iocked1337** [comment]
I'll test that. I can also try on my 10900k system to see if this issue persists with stronger hardware.

**Comment by iocked1337** [comment]
Same issue on my 10900k system, even near-the same level of slowdown.

![pcsx2-qt_UahSMJmfON](https://github.com/user-attachments/assets/da74e69b-092d-45a5-907c-2d6ccac8cc2a)

**Comment by JordanTheToaster** [comment]
> Same issue on my 10900k system, even near-the same level of slowdown.

As I said there is a readback which will slow down slower systems you can disable it if you want to increase performance but breaking some rendering there is nothing else you can do.

**Comment by iocked1337** [comment]
I can't find the setting to disable it. Do you mean "Wait Loop Detection," or "INTC Spin Detection?"

**Comment by JordanTheToaster** [comment]
> I can't find the setting to disable it. Do you mean "Wait Loop Detection," or "INTC Spin Detection?"

![image](https://github.com/user-attachments/assets/d656b0cb-9aba-4ddb-9100-e7e3b9d1826d)

**Comment by iocked1337** [comment]
Should have pointed me to Graphics first. Performance barely increased on both systems.

**Comment by Buzzardsoul** [comment]
> Should have pointed me to Graphics first. Performance barely increased on both systems.

It's partially because of your 6x upscaling.

**Comment by iocked1337** [comment]
> It's partially because of your 6x upscaling.

How so? Jordan is also running 6x upscaling and claims no issues.

**Comment by Buzzardsoul** [comment]
> > It's partially because of your 6x upscaling.
> 
> How so? Jordan is also running 6x upscaling and claims no issues.

Upscaling is a hack that comes without a warranty. Also, what gpu are you using with that 10900k?

**Comment by iocked1337** [comment]
> Also, what gpu are you using with that 10900k?

XFX RX 6800, latest drivers and Resizable BAR On.

**Comment by F0bes** [comment]
Closing as this is just a performance issue related to your hardware. Unfortunately MTVU is pretty good, but not perfect, and readbacks can really suck.

**Comment by PurpleTonberry** [comment]
Extremely disappointing performance on a 5800X3D and a 9070XT. Disabling readbacks helps a little bit, but it still can't run at 100% speed in races with the AI racers on screen, doesn't matter what the render resolution is. MTVU and EE overclocks don't help, only EE underclocks, which makes the game feel horrible to play. Its compatibility rating really shouldn't be as high as it is if the majority of the game cannot be run at full speed on high end hardware.

I genuinely think this issue should be re-opened, this is not a low spec problem.
