### ISSUE TITLE
[Feature Request]: cmake option to disable libbacktrace

### ISSUE THREAD

**Issue by chrysos349** [PCSX2/pcsx2#11566]
### Description

It'd be good to make `libbacktrace` optional during the build.

Thanks for the great emulator!

### Reason

- One less lib to worry about.
- Not everybody needs traces.
- Some distros disallow packages with no tagged releases. `libbacktrace` has none.

### Examples

`cmake ... -DBACKTRACE=OFF`

**Comment by F0bes** [comment]
It's merged into 2.1.13, no need to apply the patch in https://github.com/chrysos349/void-packages/commit/fc51b8e8539075ca66c9fc1feb7bc040f1b1e1ae :^)

**Comment by chrysos349** [comment]
@F0bes great! thanks a lot!
