### ISSUE TITLE
[Feature Request]: 7z extraction of roms in a directory before launch

### ISSUE THREAD

**Issue by ghost911-hub** [PCSX2/pcsx2#11570]
### Description

Format 7z rom support

![all 7z](https://github.com/user-attachments/assets/a88ca0f0-a768-4801-9c3f-22fda600e835)
![chd vs 7z](https://github.com/user-attachments/assets/0c2109a2-b8c9-42e0-918e-59e28454e30f)
![chd all size](https://github.com/user-attachments/assets/9c716d8b-7fc6-4bb8-9869-f4674a88fb42)

### Reason

Hello already thank you for your work and the emulator you provide a great service to the community I compared the game formats it would be wise to add the 7z format I gained 50% more space not insignificant compared to chd or gzip it is an open source format and is free and much superior to gzip format

### Examples

several emulators already support the 7z format
![biz](https://github.com/user-attachments/assets/9a4859bc-d869-4a79-925d-6b79c5c7e55f)

**Comment by refractionpcsx2** [comment]
Not possible, because 7zip can't be indexed in blocks like gzip, which is a requirement.

**Comment by ghost911-hub** [comment]
Even an extraction in a directory of our choice is not possible? before the iso launch

**Comment by crashGG** [comment]
The compression ratio of chd is already quite high, why do we have to use 7z to compress it once more? Is hard disk space so precious nowadays? ¯\_(ツ)_/¯

**Comment by RedDevilus** [comment]
Some old stats when I compressed games:
```
41 entries
ISO= 141GB
CSO= 100GB
CHD= 96GB
Or in percentages:
ISO= 100%
CSO = 71%
CHD = 68%
```

Yes, I know some games have a lot of fluff that does nothing where you can go from 4 GB to 500 MB or 2 GB to 1.5 GB, hence the average percentages.

Only issue is when you compress ISO (DVDs) to CHD and you want to make them ISO again, kinda a chore. So I'll keep it CSO for ISO and CHD for bin + cue. If you don't really care about easy converting back and want a bit more space then regular users can also do just CHD. Yes I know Launchbox has 7z option but that basically unzips it first (can take quite awhile when you want to play a game) and then deletes it, which isn't only SSD wear but time loss but technically that isn't playing 7z. 

I'm surprised you want even more formats when the current setup does several: Gzip, CSO, CHD, ZSO.

**Comment by RedPanda4552** [comment]
As refraction said, a hard requirement is indexing which is simply not an option here. I could get into the semantics of why using 7z format for game images is not a good idea, but it is moot.

**Comment by ghost911-hub** [comment]
I find the 7z option interesting because for a game that we play we do not need to delete it and decompress it each time it will remain in a temporary folder finally 50% space saving is not negligible when we has a large game library has a simple 7z extraction would be welcome decompression in a Ramdisk takes little time or an SSD
