### ISSUE TITLE
[BUG]: Regression Resolution Scaling (Onimusha 3: Demon Siege SLES-51914)

### ISSUE THREAD

**Issue by Ziegenbeisser** [PCSX2/pcsx2#11584]
### Describe the Bug

In the 2.1.9 version there is a regression in scaling for demon siege.
It works fine in other games (tested in Onimusha 2) but for Onimusha 3 it is not working.
Any scale selected will look worse than the native one.

I am reporting this since the update broke feature completely for this game, and not because of some artefacts as you are aware of them.
Compared it with my Steamdeck version which is older and not updated it scales (version 1.7.5370)

![image](https://github.com/user-attachments/assets/79c964af-b553-40da-a1d8-cd7716ad5326)

### Reproduction Steps

https://github.com/user-attachments/assets/565f05e0-0721-458d-a183-e14a7f05f753

### Expected Behavior

Ingame Resolution to go up
Resolution scaling to work as it worked in version 1.7.5370

### PCSX2 Revision

2.1.9

### Operating System

Windows 11

### CPU

Intel i7 8700K

### GPU

RTX 2080

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![image](https://github.com/user-attachments/assets/8b73b915-2ced-4a7b-8470-746de3feda54)
![image](https://github.com/user-attachments/assets/581a2195-adbb-4865-8618-46b51e71dfd2)

**Comment by Mrlinkwii** [comment]
can i have a gs dump

**Comment by Ziegenbeisser** [comment]
[Onimusha 3 - Demon Siege_SLES-51914_20240718201305.zip](https://github.com/user-attachments/files/16287293/Onimusha.3.-.Demon.Siege_SLES-51914_20240718201305.zip)

**Comment by Mrlinkwii** [comment]
seems to be working here 
![image](https://github.com/user-attachments/assets/dc849484-22c9-4095-9779-30a4507a62d3)
vs 

![image](https://github.com/user-attachments/assets/3fdee4b0-7e05-46f1-ab5f-b13678183407)

see the persons face  and the concrete pillar

**Comment by Ziegenbeisser** [comment]
I have downloaded the older version and set it up. To provide a screenshot how it looked before.
![image](https://github.com/user-attachments/assets/108c5775-4e5a-4f0c-989d-9aa041fe7a79)

**Comment by Ziegenbeisser** [comment]
added gs dump [Onimusha 3 - Demon Siege_SLES-51914_20240718203901.zip](https://github.com/user-attachments/files/16287676/Onimusha.3.-.Demon.Siege_SLES-51914_20240718203901.zip)

**Comment by JordanTheToaster** [comment]
This is caused by native scaling you can disable it if you do not like the depth of field effect present which will restore the "sharper" look.

![image](https://github.com/user-attachments/assets/396db3a9-5046-4f8e-a733-23f36b967fe0)

**Comment by Ziegenbeisser** [comment]
![image](https://github.com/user-attachments/assets/94946405-6e9a-4cdc-8ac0-f1d70a9be681)
In which option i can disable native scaling?
Do you mean the resolution multiplier? But that's what's currently buggy that it makes the image blurier on higher resolution instead of sharper like in the screenshot shown???

**Comment by JordanTheToaster** [comment]
Game Properties > Graphics > Rendering > Enable Manual Hardware Fixes.
