### ISSUE TITLE
[BUG]: Need for Speed Most Wanted : Lens Flare con error

### ISSUE THREAD

**Issue by GonzaArg** [PCSX2/pcsx2#11580]
### Describe the Bug

![NFSMW](https://github.com/user-attachments/assets/9b0a5b5a-2a94-4464-97d1-e0ccbdbb446d)
![image](https://github.com/user-attachments/assets/62a56f45-1d88-48e3-907c-f61d153eadf5)

### Reproduction Steps

perdon pero soy un novato en esto espero se entienda 
![image](https://github.com/user-attachments/assets/286cc1f5-1e74-4f91-a1ae-9d5abbd73bc5)
![image](https://github.com/user-attachments/assets/5a798f32-5c7c-4f76-9b98-5839a8fea042)

### PCSX2 Revision

v2.1.9

### Operating System

Windows 10 (64bit)

**Comment by GonzaArg** [comment]
Tambien experimente muchos bajones de fps en NfsMW cuando hay mucho que dibujar y cuando estoy solo en la carretera sube de nuevo a 60fps mas alla que mi hardware es obsoleto todos los otros juegos funcionan bien en resolucion 1080p y 900p

**Comment by JordanTheToaster** [comment]
Sorry we don't provide support or accept issues for GPUs that only have DX10.
