### ISSUE TITLE
[BUG]: Current Pad Database broke support for controllers.

### ISSUE THREAD

**Issue by LingKuja** [PCSX2/pcsx2#11583]
### Describe the Bug
As mentioned in the push update #11564:
> PAD: Update to latest controller database 

This Database update starting with version 2.1.1 has broken the support for most controllers.
Controller that are natively xinput compliant are now being detected as something else entirely on the emulator, but not on the system. I can still the controllers just fine up to the Nightly version 2.1.0, for example.
This issue is happening on both Linux and Windows as well.

### Reproduction Steps

Simply pair any controller, like the 8BitDo SN30 Pro, or a DualShock 3 controller.

### Expected Behavior

Expected to see it listed as "Xbox One Controller";
it is instead listed as "8Bitdo Zero 2" and negates any Analog inputs.
While the DualShock 3 is not listed at all (using the DSHidMini workaround since lilypad is no longer supported).

### PCSX2 Revision

Nightly, v2.1.1 onward

### Operating System

Linux (64bit) - Specify distro below;
Windows 10 (21H2)

### If Linux - Specify Distro

Ubuntu (Latest Kubuntu LTS)

**Comment by Mrlinkwii** [comment]
make an issue upstream https://github.com/mdqinc/SDL_GameControllerDB

**Comment by offalynne** [comment]
If the issue is DB related (which I do not believe) then PCSX2 is incorrectly ingesting/using the DB. The issues reported indicate a problem with PCSX2, not the `gamecontrollerdb` text file.
