### ISSUE TITLE
[Feature Request]: Search for ffmpeg files in the user folder, not in the program folder

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#11599]
### Description

![Unbenannt](https://github.com/user-attachments/assets/e1f5c555-f995-46ad-bc04-78ad57751083)

If you use more than one build, for example stable, latest nightly and some older nightlies to test bugs etc. it would be useful if pcsx2 could load the dll files from the user folder in Documents. So you need just one location for these files (just as we do with the bios, memory card etc.). At the moment you need to have the files in that build folder, from which you are recording.

### Reason

Convenience

### Examples

-

**Comment by CookiePLMonster** [comment]
This is a bad idea for security reasons - Documents are user-writable, which means any app could potentially drop malicious replacements of those DLLs. If you have PCSX2 installed as non-portable in Program Files, the directory is write-protected and requires elevation to add or replace the files.

**Comment by F0bes** [comment]
Can't you just have a directory like `C:\\ffmpeg\` with the dlls and add that to your PATH environment variable? Or even plop them into system32.

**Comment by CookiePLMonster** [comment]
Putting them in system32 risks other apps mistakenly thinking "their" variations of ffmpeg are installed, and idk how stable their ABI is.

**Comment by F0bes** [comment]
If you really want to do this, put the ffmpeg libraries in your PATH (and hope that other applications don't conflict). I'm not really interested in adding special dynamic linking directories.
