### ISSUE TITLE
[BUG]: red dead revolver (SLUS 20500) launched failed

### ISSUE THREAD

**Issue by CODspielen** [PCSX2/pcsx2#11601]
### Describe the Bug

When I launch the game, I get stuck on the loading screen, and then the emulator quits automatically.

### Reproduction Steps

Just start the game (SLUS 20500).

### Expected Behavior

Game should be launched into the main menu.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 11

**Comment by CODspielen** [comment]
![微信截图_20240720173118](https://github.com/user-attachments/assets/b3be35f5-1ffb-4fa8-9115-578c8c2d8d46)
Just at this screen, then the emulator quits automatically. I tried other games, all success, only SLUS 20500 cannot be launched for now.

**Comment by JordanTheToaster** [comment]
Please use the discord for support issues.
