### ISSUE TITLE
[BUG]: pcsx2 crashed when starting game

### ISSUE THREAD

**Issue by CODspielen** [PCSX2/pcsx2#11603]
### Describe the Bug

https://github.com/user-attachments/assets/7e5de81b-4fc9-4356-b976-4b8d217ed81b

### Reproduction Steps

when starting game red dead revolver [SLUS-20500], pcsx2 crashed and quit itself, as in the video.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
As stated before please use the Discord for support issues please do not spam them on here.
