### ISSUE TITLE
[BUG]: Need for Speed Underground (SLUS-20811) Strange Line on Cars in the Tunnel with non-Native Resolutions

### ISSUE THREAD

**Issue by sinisterseed** [PCSX2/pcsx2#11606]
### Describe the Bug

There seems to be some kind of an artifact appearing on cars, traversing them vertically in the infinite tunnel when using non-native resolutions. Switching to Native makes the line disappear, but upscaling brings it back regardless of the camera position (it changes and adapts along with it).

Screenshot of it:

![Need for Speed - Underground_SLUS-20811_20240720190312](https://github.com/user-attachments/assets/55d373b2-c6a5-48fa-b5d7-77767ab41031)

### Reproduction Steps

Simply fire up the game and go to the Career or Customization menus to see the cars. There should be a line traversing them on their backs.

### Expected Behavior

No weird lines on cars.

### PCSX2 Revision

v2.1.18

### Operating System

Windows 11

### CPU

AMD Ryzen 5 5600X

### GPU

RX 6700 XT

### GS Settings

Default, save for upscaling (3.5x).

**Comment by JordanTheToaster** [comment]
You'll need to play at native 4x internal or 8x internal nothing else will fix it.
