### ISSUE TITLE
[BUG]: Analog stick not working in Bloody Roar 4

### ISSUE THREAD

**Issue by zombiekutez** [PCSX2/pcsx2#11612]
### Describe the Bug

I'm using PCSX2 build v2.1.20, playing Bloody Roar 4 using xbox series s controller via bluetooth, the left analog stick is not working, i have try turn on/off analog button but nothing work here is my setting.
![1](https://github.com/user-attachments/assets/9d4538a0-6ad1-48d4-8889-8bcb95f51a38)
![2](https://github.com/user-attachments/assets/26cabe96-ea80-4e35-befb-9f31a7963abe)
![3](https://github.com/user-attachments/assets/ffcfdfaf-0ee8-4645-9886-0075a5209065)
The analog stick working perfect if use old PCSX2 build (testing on v1.7.2981)
So this bug make i understanding why.

### Reproduction Steps

Add game to folder => load game form launcher => game working good, but left analog stick not working.

### PCSX2 Revision

v2.1.20

### Operating System

Windows 10 (64bit)

### CPU

i7 4790

### GPU

RX  6600

**Comment by JordanTheToaster** [comment]
Please use the Discord for support issues.
