### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Armandokevin** [PCSX2/pcsx2#11627]
### Describe the Bug

Hello, very good, first of all, congratulations for the enormous work. I'm having a hard time mapping the apiatola in the "relative pointing" I think this can be done manually by editing a file, right? I wanted to know what file it is, and what exactly I should have put in the fields: up, down, left and right. Thank you very much in advance

### Reproduction Steps

When I enter the controller settings menu

### PCSX2 Revision

latest 2.0.2

### Operating System

Windows 11

**Comment by lightningterror** [comment]
Use/join our discord for support.

**Comment by Armandokevin** [comment]
> Use/join our discord for support.

Ok, and what is your discord. thank you and I'm sorry

**Comment by TheLastRar** [comment]
> > Use/join our discord for support.
> 
> Ok, and what is your discord. thank you and I'm sorry

https://discord.com/invite/TCz3t9k

**Comment by kamfretoz** [comment]
Help > Discord server

![image](https://github.com/user-attachments/assets/efa93191-d6f0-404d-a448-aa6aaa6be0a1)

**Comment by Armandokevin** [comment]
I didn't see it from my mobile. Excuse me

**Comment by Armandokevin** [comment]
Good again. Look, excuse me, but I have asked in the diacord that you have sent me, but they tell me that they don't give me support there, so I should ask here.

**Comment by F0bes** [comment]
You are on the pcsx2/PCSX2 repository.
You asked in discord for support for a fork.

Go to that forks GitHub, or that forks discord and ask for support if you want help with their fork.
