### ISSUE TITLE
[Feature Request]: Add random game button

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#11625]
### Description

Add a button e.g. in System or Tools called 'Start Random Game' which pulls from your current GameList and selects a single option to boot. Either this would be greyed out while the VM is running *or* some way would need to be found to swap without screwing up the memory card while saving (e.g. waiting until the five-second delay is over).

I intend to implement this myself and am only putting this here as a signal that the feature request is acknowledged and will be worked on.

### Reason

This feature gets requested a lot by users like myself which have a fairly large games library and then end up with decision paralysis because they can't decide what to play. Although anyone can just go to a random number generator online and request a number mod whatever, adding the randomizer into PCSX2 proper makes it more convenient but more importantly plays to human psychology in a way that feels much less mechanical than just retrieving a number from an RNG and manually finding the corresponding game.

It's the same effect as going to somewhere like an online streaming platform where you have a million choices but "there's nothing to watch", but then if something comes on on TV, you might just say "eh, sure, I'll watch this."

### Examples

Go to Tools > Start Random Game or System > Start Random Game. This option could be hidden by default and enabled manually in the Interface settings.

**Comment by lightningterror** [comment]
Close your eyes and just click on a game, problem solved, otherwise this is pointless.

**Comment by JordanTheToaster** [comment]
He is going to fulfill this request himself there is no need to close this just because you do not like it.

**Comment by TheTechnician27** [comment]
> Close your eyes and just click on a game, problem solved, otherwise this is pointless.

The option wouldn't be there because this is some huge logistical issue for humans to do (although it slightly simplifies the process); the option would be there because human psychology means that this option is meaningfully different from what you suggested.

**Comment by lightningterror** [comment]
Silly requests don't belong as a core feature in the main program.

Also please don't re open requests if the team decides it's not a good idea/worth adding.

**Comment by TheTechnician27** [comment]
> Silly requests don't belong as a core feature in the main program.
> 
> Also please don't re open requests if the team decides it's not a good idea/worth adding.

Still PRing this FYI.

**Comment by refractionpcsx2** [comment]
Tech, that's absolutely disrespectful of the teams wishes.

**Comment by TheTechnician27** [comment]
> It's a wonderful idea, but only when it's separate program from PCSX2. Alternatively, though, why can't anyone use any random number generator online for this instead?

When it's a separate program from PCSX2, its usability falls through the floor, and it becomes a hacky, logistical nightmare compared to literally just writing three lines of code to mod out a random number by the game list's cardinality (exposed by GameList.cpp) and then opening the index of that game. The implementation which I've created (it is ready and being looked at internally) is completely trivial and much, much more usable (that is to say: usable at all. I would never make a separate script because it would be a useless piece of crap that nobody would ever use). Here's the function that does this:

```void MainWindow::onStartRandomGameActionTriggered()
{
	std::srand(std::time(nullptr));
	if (GameList::GetEntryCount() > 0)
		startGameListEntry(GameList::GetEntryByIndex(static_cast<u32>(std::rand() % GameList::GetEntryCount())));
}```

But I guess I could also make a worse version with 300 lines of Python code.

I already explicitly mentioned why the "just query an RNG on the Internet" is essentially the worst possible version of this, but I can elaborate further; in no particular order: 1) You need to have working Internet access or an offline RNG utility on your desktop or phone. 2) You then need to go to your web browser to a separate website or into said app. 3) You need to manually count the number of rows and columns (at best if you have just one or two directories you pull from, you can go to your file manager and check the directory properties, adding them all up) to find the game count to know what the upper bound is (completely impractical for the target demographic who would be suffering from decision paralysis from too many choices). 4) Then you need to manually enter the bounds and obtain the result. 5) You then have to switch to the Game Grid format if you haven't already and count out the number of rows and columns to get to this desired game. The entire point of this feature is that it's something quick when you don't know what to play, not a DnD session.

Compare this convoluted two-minute-per-roll process now to clicking on `Start Random Game` and being in-game in milliseconds in both the default UI and the big picture one. It's elegant, trivial, causes basically no maintenance overhead, and fixes a problem multiple users have asked me alone if we have plans for. Saying "just write an external script" is a backdoor way of shutting down the idea altogether because nobody would ever implement something that unfit for purpose.

**Comment by F0bes** [comment]
> It's a wonderful idea, but only when it's separate program from PCSX2. Alternatively, though, why can't anyone use any random number generator online for this instead?

Scalerize, you were previously blocked from this organization and banned from our online platforms (including your multiple alt accounts). From my understanding your previous account `Scalerize` was also nuked from GitHub due to your conduct.

You are once again blocked from our org, and a report will be made to GitHub. You are not welcome here, you have blatantly disrespected multiple of our team members and have burnt bridges indefinitely. Do not come back.
