### ISSUE TITLE
[BUG]: version 1.4.0 doesnt open.(windows 7 ultimate)

### ISSUE THREAD

**Issue by tizibc** [PCSX2/pcsx2#11620]
### Describe the Bug

im on windows 7 ultimate and when i try to open the exe it doesnt open and instead gives the error 0xc000007b i tried installing both portable and installer versions and both dont work, also i tried installing microsoft visual c++ and it doesnt work

### Reproduction Steps

i dont know how to reproduce it

### PCSX2 Revision

1.4.0

### Operating System

Windows 11

**Comment by tizibc** [comment]
help:(

**Comment by F0bes** [comment]
We don't provide support for 1.4 anymore.

**Comment by RedDevilus** [comment]
We don't support older stables below v2.0 as the time of writing. W7 is also 4 years out of support date. Also template you said w11
