### ISSUE TITLE
[Feature Request]: New keyboard shortcut close emulator and start bic picture

### ISSUE THREAD

**Issue by enriquealcaraz** [PCSX2/pcsx2#11623]
### Description

I would like you to add a keyboard shortcut to close the emulator (as it exists in duckstation) directly from the controller. Yes it is true that you have one to close the game but I would like one that closes the emulator. For those of us who play in stream it's a pain not being able to close it directly, 

I would also like you to add a keyboard shortcut to start the bic picture mode.

### Reason

I play in stream with playnite and the problem is that I can't close the emulator with the controller in the stream session and it forces me to exit the application and re-enter.

### Examples

The duckstation play 1 emulator has this option

**Comment by ichee** [comment]
You can add to the launch shortcut `-bigpicture` `-fullscreen` `-nogui`
to start in fullscreen big picture mode, and with no gui, exiting game will exit everything.

**Comment by enriquealcaraz** [comment]
The idea was to use playnite to load all the games and select them, but I have already solved the problem by creating a hotkey. Thank you very much anyway.
