### ISSUE TITLE
[BUG]: [SLUS-20238] Crash Bandicoot - The Wrath of Cortex bad fog, serious regressions

### ISSUE THREAD

**Issue by WavesOfSalt** [PCSX2/pcsx2#11639]
### Describe the Bug

Fog is not rendered correctly and hasn't for a while in this Crash game. The last known time it rendered correctly was way back when the OpenGL software renderer was still in there. How do I know this? The last version of AetherSX2 also doesn't render the fog correctly, but the software renderer there does.
![incorrect fog](https://github.com/user-attachments/assets/3a96e2a6-1b9a-4a82-bf62-884ba053ff20)
(software renderer on latest version)
![incorrect fog current pcsx2 software](https://github.com/user-attachments/assets/7a5f83a0-d1a0-4e16-8af4-d27a299ffd40)
![older pcsx2, AetherSX2, same issue on vulkan](https://github.com/user-attachments/assets/dac36fc5-dd33-48f4-91f0-745e9f7d2a0e)
![older pcsx2, AetherSX2, issue fixed with legacy Opengl software renderer](https://github.com/user-attachments/assets/97b7a0a7-e11c-468f-aff8-eac2b60caece)

Also, the latest update introduced a major, primarily vulkan-based, performance loss, mostly a 20 to 30 fps loss across the board even in-menus, which seemingly can't be reverted by downgrading versions, but many games (could not test them all) return to normal performance by switching to Direct3d, with the (as far as I know) exception of Black (shown at 00:00:50.293), which cannot be ran at full speed anymore regardless of settings. It is understood this performance issue wasn't there in v2.1.27, although as stated before, downgrading does not fix it.
https://github.com/user-attachments/assets/10b4e5e4-e0ce-42ff-a23b-e50be524a815

### Reproduction Steps

Open PCSX2
Start The Wrath of Cortex. In the case of issue 2, any game at all.

### Expected Behavior

![older pcsx2, AetherSX2, issue fixed with legacy Opengl software renderer](https://github.com/user-attachments/assets/8db8bc02-0228-4b60-8226-d3cd8448e5a6)
The fog should look like this. Otherwise, the expected behavior is full speed.

### PCSX2 Revision

v2.1.36

### Operating System

Windows 11

### CPU

Ryzen 3800x

### GPU

RTX 3070 ti

**Comment by WavesOfSalt** [comment]
I couldn't possibly explain why, but after restarting the whole installation from scratch, things on the Windows side were fixed. The solution WASN'T a video setting, it was shredding everything. I guess we'll never know why. I guess worth nothing is that the version I started that installation with was a pre-release of 1.7.0. Although, due to the clashing with the upscaled assets, I wish I could disable the fog.

I was about to close this, EXCEPT now I get this strange pixilation around Crash. What is that? Is it supposed to render like that? Doesn't seem related to either texture packs, the renderer, or upscaling. It was tough to capture. This is not a video compression artifact. It looks like that.

https://github.com/user-attachments/assets/d804b5c1-3be1-4cd9-866b-a525aa09657a

**Comment by WavesOfSalt** [comment]
I couldn't possibly explain why, but after restarting the whole installation from scratch, things on the Windows side were fixed. The solution WASN'T a video setting, it was shredding everything. I guess we'll never know why. I guess worth nothing is that the version I started that installation with was a pre-release of 1.7.0. Although, due to the clashing with the upscaled assets, I wish I could disable the fog.

I was about to close this, EXCEPT now I get this strange pixilation around Crash. What is that? Is it supposed to render like that? Doesn't seem related to either texture packs, the renderer, or upscaling. It was tough to capture. This is not a video compression artifact. It looks like that.

https://github.com/user-attachments/assets/d804b5c1-3be1-4cd9-866b-a525aa09657a

**Comment by lightningterror** [comment]
Can you upload a gs dump?

**Comment by WavesOfSalt** [comment]
Is this enough?
[Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20240812212728.zip](https://github.com/user-attachments/files/16593338/Crash.Bandicoot.-.The.Wrath.of.Cortex_SLUS-20238_20240812212728.zip)

**Comment by JordanTheToaster** [comment]
> Is this enough? [Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20240812212728.zip](https://github.com/user-attachments/files/16593338/Crash.Bandicoot.-.The.Wrath.of.Cortex_SLUS-20238_20240812212728.zip)

This is just how the game looks you can check yourself on PS2 I can add HPO Special to make hardware slightly closer to Software but that is it.
