### ISSUE TITLE
[BUG]: one controller is being recognized as two and is double inputting on def jam fight for NY

### ISSUE THREAD

**Issue by Shneed7** [PCSX2/pcsx2#11631]
### Describe the Bug

When in game my controller double inputs and would skip over options when trying to navigate the main menu or would double clicks on the options when I try to select them. Like there are two controllers doing the same action.

### Reproduction Steps

Just lunch the game normally and try to maneuver thru the main menu. 
Using a PS4 DualShock controller. 
PCSX2 settings on default. 

### Expected Behavior

as said previously, when in game my controller would double input and would skip over options or double clicks on the options when traversing the menu with the toggles or d-pad, and would double click the X and triangle buttons

### PCSX2 Revision

v2.0.2

### Operating System

Windows 11

### CPU

 i7-10750H

### GPU

NVIDIA GeForce RTX 2070

### GS Window Screenshots

![Screenshot 2024-07-27 190934](https://github.com/user-attachments/assets/19fbaae0-4962-480c-ac50-dd2520809231)

**Comment by MrKingG33** [comment]
I had the same problem with the controller and not being able to hit the done button when creating a user Id in story mode. hope someone can help because this game is too good not to be able to play this game.

**Comment by Mrlinkwii** [comment]
![image](https://github.com/user-attachments/assets/49f04b2b-ccb0-44b5-a799-e1baa985c893)
 can you make sure you havent double mapped your controller

**Comment by F0bes** [comment]
Closing due to waiting feedback status for more than a month.
