### ISSUE TITLE
[BUG]: Your Microsoft Visual C++ Runtime appears to be too old for this build of PCSX2

### ISSUE THREAD

**Issue by ValcristRoda** [PCSX2/pcsx2#11645]
### Describe the Bug

![image](https://github.com/user-attachments/assets/60433981-49df-45d0-bba7-90832036f559)
I have the newest vc_redist installed. I have also tried using repair and restarted. The issue still persists. Another person had the same problem and used repair and it fixed for them. This did not work for me.

https://github.com/PCSX2/pcsx2/issues/11558

The previous thread where someone had the same issue right there.

### Reproduction Steps

Open any pcsx2-qt.exe release.

### PCSX2 Revision

2.02, 2.1.38.0

### Operating System

Windows 11

**Comment by F0bes** [comment]
Just to confirm, you are downloading the x64 vc redist ? The x86 one is not used with PCSX2.

**Comment by ValcristRoda** [comment]
> Just to confirm, you are downloading the x64 vc redist ? The x86 one is not used with PCSX2.

So I fixed this and I have a fix for anyone else who has this issue probably. Just don't copy the files to the folder anymore if this happens. Do a fresh one via the installer. It fixed it for me. Probably a dll file not in the package or something.

**Comment by F0bes** [comment]
Glad you got it working.

**Comment by kushmin1** [comment]
@ValcristRoda i have this same issue. Kindly walk me through how to fix it

**Comment by ValcristRoda** [comment]
> @ValcristRoda i have this same issue. Kindly walk me through how to fix it

I had to do a fresh install with the installer. No copying things over or anything like that. So I lost whatever I had with my old install. Doing it fresh fixed it for me.

**Comment by kushmin1** [comment]
> > @ValcristRoda i have this same issue. Kindly walk me through how to fix it
> 
> I had to do a fresh install with the installer. No copying things over or anything like that. So I lost whatever I had with my old install. Doing it fresh fixed it for me.

omgg i dont wanna lose my game progress
damn

**Comment by kushmin1** [comment]
> > @ValcristRoda i have this same issue. Kindly walk me through how to fix it
> 
> I had to do a fresh install with the installer. No copying things over or anything like that. So I lost whatever I had with my old install. Doing it fresh fixed it for me.

is it possible to copy the data from the memory card?

**Comment by F0bes** [comment]
Memory card files can be transferred. If you need help, go to our discord for support please.
