### ISSUE TITLE
Plugin Shutdown function is not called!

### ISSUE THREAD

**Issue by RebelliousX** [PCSX2/pcsx2#1165]
PCSX2 does call PADshutdown() when exiting the emu if and only if the user started emulation (by showing the GS window) at least once since launching PCSX2.

PCSX2 doesn't call plugin shutdown callback function when the user doesn't start the emulation, even if the user invoked Configure.

I can't use std::atexit() because I want to signal a running/sleeping thread to exit by a conditional variable. If I do use std::atexit() with std::thread it will throw an exception `std::system_error`.

Creating a static structure variable with a destructor to it, it does get called, but suffers the same issue as std::atexit, besides, according to [this](http://en.cppreference.com/w/cpp/utility/program/exit) static variables destructors are called after std::atexit finishes.

PCSX-R or PSX emu do call Shutdown for the plugins when exiting and have no issues.

Although the OS will reclaim any memory leaked, it is bad to leave it to the OS at termination.

Edit: I am not using DllMain(), wxWidgets in a dll doesn't use DllMain, so I can't be notified of exit in this case.

**Comment by TheLastRar** [comment]
IIRC this is because PCSX2 doesn't call Init until you start emulation.

**Comment by RebelliousX** [comment]
@TheLastRar  Delay loading the dll will confuse pcsx2. It must be loaded at startup.
The real entry point is hidden in wxwidgets macro, if you look at the dll sample in wxwidgets library you will know what I am talking about.

I can however do a small modification (4 lines of code) to wxwidgets library to solve my problem. But I would have prefered a same behavior as PSX emus, since the the plugin API is similar.

**Comment by turtleli** [comment]
IIRC it's a bit inconsistent - PCSX2 doesn't call Init when it's started, but if you switch plugins then Init will be called, even without starting emulation.

IMO it probably would be a good idea to call Init at startup, so plugins can rely on Init/Shutdown always being called and it'd make the plugin handling a bit more consistent.
