### ISSUE TITLE
[BUG]: Vulkan API Crashes games

### ISSUE THREAD

**Issue by BlueSpyro** [PCSX2/pcsx2#11650]
### Describe the Bug

Every time i launch a game in Vulkan its crash after i try start new game or load game, i tested in stable version(v2.0.2) and works fine with no crashses only got this problem in dev versions, i don't know if was just me or something i just do in my laptop other programs seems to work fine

### Reproduction Steps

I start Kingdom Hearts 2 Final Mix and after i get in menu i try load game and just close emulator

### PCSX2 Revision

v2.1.43.0

### Operating System

Windows 10 (64bit)

### CPU

Intel Celeron 6305

### GPU

Intel UHD Graphics

### Emulation Settings

![Captura de Tela (190)](https://github.com/user-attachments/assets/0d0a6e4d-86bd-4055-87b2-6256cccbc752)
![Captura de Tela (192)](https://github.com/user-attachments/assets/d7b0a4d3-49ce-46d1-adca-944ec977a339)
![Captura de Tela (193)](https://github.com/user-attachments/assets/9b1fb72e-ca10-4f5a-85ad-fca90b93a34a)
![Captura de Tela (194)](https://github.com/user-attachments/assets/62fee9e4-aef7-4943-b616-2ae8875b3032)
![Captura de Tela (195)](https://github.com/user-attachments/assets/6af6a877-9dbd-4f91-81b9-b7e773aea12a)
![Captura de Tela (196)](https://github.com/user-attachments/assets/17c14734-f34e-449a-a100-0969f7b2f7c7)
![Captura de Tela (197)](https://github.com/user-attachments/assets/dfe6d433-4819-484c-b514-5aebbf20b371)

### Logs & Dumps

[crash report.zip](https://github.com/user-attachments/files/16431164/crash.report.zip)

**Comment by RedPanda4552** [comment]
Not a bug, please use Discord for support.
