### ISSUE TITLE
[BUG]: Image ripple error when playing PES 2013, 2014 on version 2.0

### ISSUE THREAD

**Issue by hungvntb** [PCSX2/pcsx2#11654]
### Describe the Bug

Image ripple error when playing PES 2013, 2014 on version 2.0. As I passed the ball back and forth across the stadium, I noticed that the midfield line occasionally appeared wavy. This issue does not appear on version 1.6

### Reproduction Steps

As I passed the ball back and forth across the stadium, I noticed that the midfield line occasionally appeared wavy. This issue does not appear on version 1.6

### Expected Behavior

Fix Image ripple error when playing PES 2013, 2014 on version 2.0

### PCSX2 Revision

v2.0.2

### Operating System

Windows 10 (64bit)

### CPU

i5-10400F

### GPU

RTX 3060

**Comment by JordanTheToaster** [comment]
Please use the Discord for support issues.
