### ISSUE TITLE
[BUG]: Cover images not show up on Appimage (Linuxdeploy problem)

### ISSUE THREAD

**Issue by Ir-boop** [PCSX2/pcsx2#11665]
### Describe the Bug

Using appimage on v2.1.57 game cover do not show up on game list despite it's already set on "covers" directory.
See below:
![Screenshot from 2024-08-05 09-39-45](https://github.com/user-attachments/assets/2619cb7c-d152-4f69-bc3b-9653eb94c054)
It's fine on previous revision (v2.1.56):
![Screenshot from 2024-08-05 09-41-30](https://github.com/user-attachments/assets/ae09b847-5e0f-4ab6-a9b0-c91ceaa0115c)

Note: The issues also happens on Duckstation not long ago and already fix. The problem seems related to linuxdeploys issues.
https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/184

### Reproduction Steps

Just load the appimage with game cover already set and see the game list.

### Expected Behavior

Game cover show up just like before.

### PCSX2 Revision

v2.1.57

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 22

**Comment by Mrlinkwii** [comment]
@Ir-boop  can you  double check this , this should be fixed now if you update  :)

**Comment by Ir-boop** [comment]
Yeah, the problem seems to be fixes on the new build as the upstream .
