### ISSUE TITLE
Richard Burns Rally - Native upscaling makes bottom of the screen not render properly

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1167]
-PCSX2 version: pcsx2-v1.5.0-dev-275-g119f6de-windows-x86

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: Using any native upscaling makes the bottom of the screen not render properly.
However, with custom resolutions the screen is rendered how it should. 
http://forums.pcsx2.net/attachment.php?aid=39025

-How to replicate: Open game with any of the GSDX hardware renderers and use native upscaling 2x or higher.

-Last known version to work: Never worked

-PC specifications: CPU: Intel Core i5 4590 GPU: AMD Radeon HD6000 @ 2GB OS: Windows 7 Ultimate x64

Other comments: screenshot is from issue posted on the PCSX2 forum: http://forums.pcsx2.net/Thread-Richard-Burns-Rally?pid=247723
It looks the same on current git version.

**Comment by ssakash** [comment]
which specific values of the custom resolution works fine with this game ?

**Comment by FlatOutPS2** [comment]
At least the default 1024x1024, 2048x2048, and I believe 1024x1082(double of the native resolution).

**Comment by refractionpcsx2** [comment]
What does the resolution at the top of the window say? 512x541? that's an odd size.

**Comment by FlatOutPS2** [comment]
Yes, it's 512x541. Odd, but true.

**Comment by refractionpcsx2** [comment]
The problem is the heigh is currently calculated at the same size as the width, which is obviously too small in this game, usually it's bigger than the height should be.

The problem is, at that point, checking what we check (the frame buffer width) doesn't actually give a height, so we are going to have to think of a genius way to check both to see which is bigger.

**Comment by refractionpcsx2** [comment]
@ssakash @gregory38 maybe one of you two has a bright idea for this,  considering the height is in a different class not referencable by the texture cache.

**Comment by willkuer** [comment]
Cantyou just make the cache slightly larger than the width? Something like 1.1×width? I guess the performance drecrease will be neglectable, or?

**Comment by refractionpcsx2** [comment]
I did do something similar for a bit, there was quite a performance impact, especially at higher scaling

**Comment by gregory38** [comment]
It kill memory usages. Imagine, you see what 10 extra lines by RT but each lines is width * 4 B. But we don't have any choice. Maybe put a bigger H when W isn't too big.

**Comment by gregory38** [comment]
I think we can try to bump the 512 to 550.
```
	m_height = buffer_size < 1024 ? 512 : 1024;
```
Might break scaling too.

Hum, does it work in 1x aka native?

**Comment by FlatOutPS2** [comment]
There's no issue with 1x.

I've build GSDX with
`    m_height = buffer_size < 1024 ? 550 : 1024;`
This fixes natve 3x and up, but 2x native is still bugged with this change.

**Comment by ssakash** [comment]
I'm not sure about the logic of the current scaling function so I rewrote the function based on the height of the display rectangle rather than the current estimation of height of frame memory. It's a pain really , why the heck does GS not have a register for Frame memory height similar to FBW ?

@FlatOutPS2 - here's the GSDX Plugin : https://www.dropbox.com/s/o4xb7n2z1fo6a1s/GSdx32-SSE2.dll?dl=0

can you check whether the problem is resolved on all resolutions ?

**Comment by ssakash** [comment]
Also worth to check whether it fixes any other issues with upscaling.

**Comment by FlatOutPS2** [comment]
That plugin does fix the scaling issue, but it introduces another issue. It seems to turn off hardware depth on native/1x. In RBR you need hardware depth to show the car shadow, which disappears at native with this plugin.

**Comment by ssakash** [comment]
Hardware depth works for other native scaling resolutions ( 2x , 3x , 4x... ) ? the issue seems a bit weird.

**Comment by FlatOutPS2** [comment]
Yes, the car shadow is there on the other native scaling resolutions. It is there on native with the default plugin, so it's definitely due to the adjusted plugin.

**Comment by ssakash** [comment]
Okay, here's take 2 on the scaling function : https://www.dropbox.com/s/o4xb7n2z1fo6a1s/GSdx32-SSE2.dll?dl=0

I'm a bit positive that It'll fix the regression with hardware depth, @FlatOutPS2 - Please also look out for other regressions , counting on you ;)

**Comment by FlatOutPS2** [comment]
Take 2 definitely fixes the hardware depth regression and all of the scaling issues in RBR. I'll do more testing to see if nothing else regressed.
