### ISSUE TITLE
[BUG]: Psychonauts freeze/crash

### ISSUE THREAD

**Issue by Zulthar** [PCSX2/pcsx2#11676]
### Describe the Bug

When going up the elevator to reach Doctor Loboto, after the cutscene the emulator freezes or crashes during the loading screen

### Reproduction Steps

Go up the elevator to reach Doctor Loboto, watch or skip the cutscene, then within a second or two the game freezes/crashes. It's inconsistent

### Expected Behavior

the game loads to the next area, starting with a cutscene

### PCSX2 Revision

v2.1.68

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Mint

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

GeForce GTX 1650

### Logs & Dumps

Apologies, no .dmp was generated, and the emulog.txt file was empty

**Comment by Farran666** [comment]
I'd love to test it. Do you have a memory card, or savestate?

**Comment by Zulthar** [comment]
[Save State for testing.zip](https://github.com/user-attachments/files/16563463/Save.State.for.testing.zip)

This is a resume state

**Comment by Farran666** [comment]
Seems it might be something wrong with your game? I saved to memory card, and loaded the game through there and all the problems disappeared. Here's my savestate:
[SLUS-21120 (2373FD16).01.zip](https://github.com/user-attachments/files/16639137/SLUS-21120.2373FD16.01.zip)

**Comment by Zulthar** [comment]
What OS do you use? I suspect it's a linux thing

**Comment by Farran666** [comment]
> What OS do you use? I suspect it's a linux thing

I'm using Windows 11.

**Comment by Farran666** [comment]
@Zulthar Can you verify your game? Right click the game > properties > look at the bottom right and hit verify.

**Comment by Farran666** [comment]
This is from your savestate:
![image](https://github.com/user-attachments/assets/8431264c-e039-4301-b345-b6aaa7d03426)

And this is from mine: 
![image](https://github.com/user-attachments/assets/84a60df1-f067-43d4-8116-2e7baa2f2b55)

Yours loads on my game, albeit with missing textures. That's why I'm thinking your game dump is bad.

**Comment by F0bes** [comment]
> That's why I'm thinking your game dump is bad.
Agreed. If you need support please visit our discord.
