### ISSUE TITLE
[BUG]: Snow White and the 7 Clever Boys Stuttering [SLES-56420]

### ISSUE THREAD

**Issue by pinguupinguu** [PCSX2/pcsx2#11682]
### Describe the Bug

The entire game on latest nightly stutters in emulator, making unplayable.

### Reproduction Steps

Load game, and boot through entry screens.

### Expected Behavior

The game to run at a normal pace. 

### PCSX2 Revision

v2.1.72

### Operating System

Windows 11

### CPU

AMD Ryzen 7 3700x 8-Core

### GPU

Nvidia GEForce RTX 2060 Super

### Logs & Dumps

[emulog.txt](https://github.com/user-attachments/files/16552969/emulog.txt)

**Comment by lightningterror** [comment]
Please use the discord for support.
