### ISSUE TITLE
[Feature Request]: Swich default flatpak version to stable instead of nightly

### ISSUE THREAD

**Issue by dragon99919** [PCSX2/pcsx2#11688]
### Description

I know this probably isn't a huge deal, but it might be misleading to some people. When you install PCSX2 from flatpak using default option that software manager of distro comes with, it's the nightly version of the PCSX2. Shouldn't the default flatpak version be switched to stable, like for example Dolphin does? I know you chose which version you want to install from website, but if you're just browsing through flatpak repos, that won't be an option there. The funny thing is that flatpak indeed states that nightly version as stable.

### Reason

So people won't complain that much about fixes for "stable" release which it clearly isn't.

### Examples

Any software manager of any distro that supports flatpak.

**Comment by ynhhoJ** [comment]
Or maybe there should be two builds: `Nightly` and `Stable`.

Because I definitely want to use **only** `nightly` version.

**Comment by F0bes** [comment]
Once we get flatpak builds fixed I'll be looking into moving our currently nightly builds to `beta` and having `stable` be our actual stable builds. I'm unsure if I'll manage to downgrade the `stable` branch yet.

**Comment by dragon99919** [comment]
As far as I know, this should be possible. Dolphin did something similar when announcing their new version management - lots of people were playing with achievements on when installing stable flatpak version only for it to be downgraded one day and everyone was surprised. ; D

**Comment by dragon99919** [comment]
Was this fixed in the latest release or is it waiting for next one? Looking at flathub page it still shows version v2.1.226 as downloadable stable.

**Comment by F0bes** [comment]
We are currently dealing with an issue on flathub.
