### ISSUE TITLE
[BUG]: Low FPS when memory card data is written to a Google Drive folder

### ISSUE THREAD

**Issue by nottanumber** [PCSX2/pcsx2#11681]
### Describe the Bug

My memcard data is set to save/retrieve data from a cloud mounted folder using the desktop Google Drive application with Stream files enabled. I've seen some odd slowdown that I can only reproduce when the memcard folder is on the virtual drive the Google Drive application creates. This is most apparent when saving games (FFX), but it happens when loading some games as well (GoW)

* Game FPS drops from a consistent 60FPS -> ~15FPS (FFX)
* Video FPS drops in a similar way (FFX)
* EE %: 15% -> ~8% (FFX)

This drop is not reproducible when copying the cloud folder to a local folder and loading PCSX2 memory card data from my SSD. I assume the GDrive application has some sort of overhead that is in conflict with PCSX2, but I can't reproduce similar FPS drops on other emulators or other applications. I am quite curious if other types of stores perform in similar ways on Windows.

### Reproduction Steps

1. Set Memory Cards folder to Google Virtual Drive location `G:\My Drive\pcsx2\` or a folder of your choice
2. Note full 60 FPS prior to save in games like GoW2 or FFX-International
3. Save in-game
5. Note FPS drop to ~15FPS, sound/music skips, and overall game slowdown during save

### Expected Behavior

Without knowing the nuances of how GDrive stages its files (cache? temp storage?) it is hard to say. I would expect some slowdown and overhead in general when saving to the drive but not enough to cause an FPS drop. Task manager doesn't show any disk or CPU contention

In general I would expect PCSX2 to not drop frames when saving to a Google Drive folder.

### PCSX2 Revision

v2.1.68

### Operating System

Windows 11

**Comment by weirdbeardgame** [comment]
Sounds like PCSX2 is getting caught in a loop because of the file lock waiting for GDrive to sync

**Comment by MrCK1** [comment]
There is latency associated with transmitting data over the internet (especially Google Drive), this is not a PCSX2 bug

**Comment by nottanumber** [comment]
Noting a write speed of 50MB/s (!) in task manager during the save. In comparison, the write speed doesn't go over 100 KB/s when saving directly to the SSD folder

**Comment by weirdbeardgame** [comment]
Yeah, because you're not trying to sync to GDrive. You're directly saving to hard storage.
The limiter is whatever the upload speed is and perhaps the Stream files setting you've mentioned.
As CK said, its not PCSX2 fault

**Comment by nottanumber** [comment]
I should have been more specific. The 50 MB/s rate only happens when saving to the virtual gdrive. In comparison, saving to a normal windows folder barely moves the needle on write rates at all.

In any case, swapping over to a OneDrive folder as the memory card location is working fine as alternative. I'm satisfied pointing the finger at GDrive for this case.
