### ISSUE TITLE
[BUG]: Weird rectangle appearing when holding the Square button on controller if frametime graph is displayed

### ISSUE THREAD

**Issue by bslenul** [PCSX2/pcsx2#11699]
### Describe the Bug

When holding the Square button on a controller while a game is running a grey rectangle appears in the middle of the screen + some white lines around the frametime graph. Only tested with XInput controllers, it's also not happening with a keyboard.

![image](https://github.com/user-attachments/assets/3205135d-f57b-4043-8776-62b739dc1d06)

If I click with my mouse on the PCSX2 Window the bug won't show again during that game session, however it will happen again if I close the game and launch it again.

The bug only happens when the frametime graph is currently shown on-screen.

From my tests, it started happening with v2.1.75 (#11680), I can't reproduce the issue in v2.1.74.

#11693 fixes the issue for Jordan, but I grabbed the artifact from the GH Actions and I also built PCSX2 locally with that PR changes but for me it's still happening, which is why I still wanted to open an issue about it.

### Reproduction Steps

1. Have a XInput controller (but it might work with SDL or DInput, I haven't tested).
2. Enable the frametime graph from the OSD menu.
3. Start a game and hold Square button.

### PCSX2 Revision

v2.1.83

### Operating System

Windows 10 (64bit)

**Comment by mansoor909** [comment]
It may be related to the problem
When you move the mouse pointer continuously, the frametime graph vibrates frame

**Comment by techbot2342** [comment]
Happens to me too
