### ISSUE TITLE
[BUG]: Half Life - cannot start the game - 

### ISSUE THREAD

**Issue by mikesk8** [PCSX2/pcsx2#11690]
### Describe the Bug

I have a verified US Half Life version. After starting the game I try to start the main game. The game detects there is no save data and asks to continue. However, after pressing to continue it goes back and saying no save data - loop. Please help ;-) Thank you!
![IMG_0982](https://github.com/user-attachments/assets/14e636b6-edd9-44e4-a5de-fc98b41d0461)

### Reproduction Steps

as above.

### PCSX2 Revision

2.1.74

### Operating System

macOS 13 (Ventura)

### CPU

i5

### GPU

Radeon Pro 570

**Comment by mikesk8** [comment]
Verified as Half-Life (USA) [SLUS-20066] (Version 2.40).

**Comment by bslenul** [comment]
Not sure to understand the issue, if you don't have a save, then click "New Game" instead of "Load Game" 🤔 

And if you mean you can't exit that menu, just press Triangle as mentioned on the UI:

![image](https://github.com/user-attachments/assets/ad4fe149-d1f6-46fb-b918-ebbb6566e8ba)

**Comment by mikesk8** [comment]
> Not sure to understand the issue, if you don't have a save, then click "New Game" instead of "Load Game" 🤔
> 
> And if you mean you can't exit that menu, just press Triangle as mentioned on the UI:
> 
> ![image](https://private-user-images.githubusercontent.com/33353403/356819813-ad4fe149-d1f6-46fb-b918-ebbb6566e8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDU0NzYsIm5iZiI6MTcyMzMwNTE3NiwicGF0aCI6Ii8zMzM1MzQwMy8zNTY4MTk4MTMtYWQ0ZmUxNDktZDFmNi00NmZiLWI5MTgtZWJiYjY1NjZlOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE1NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZmY4YzhkYTlhOWIyNGRmZGE5NDA4ZDUyYmVlNjgyYjVhMTM3NDlmYWUxNDk2OGQ0MmQ0MjFkZTRkN2ExZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gt9uXgP1GlsxEIpAIIklnXEXPyt3brJStyoDBG0uNtI)

Thanks for the answer. I don't see New Game option. If I press X to play Half Life I get to this screen. Something is strange :(

**Comment by mikesk8** [comment]
https://github.com/user-attachments/assets/78366fd8-726b-4ef6-895d-ef062050dc40

It seems there is something wrong as I directly go to the Load screen and not selection. I have a feeling there is something wrong with my controller in this game.

**Comment by mikesk8** [comment]
I have found the way top solve it. PCSX2 was detecting 2 controllers while only 1 was connected.
