### ISSUE TITLE
[BUG]: Silent Hill 3 missing graphics

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#11697]
### Describe the Bug

In Silent Hill 3 there is an hallway with butterflies blocking the way. This is how it looks on Ps2 hardware 
![Cattura](https://github.com/user-attachments/assets/4f6ec08b-cbf2-4cfa-9803-d5f5c8b99062)

Using Pcsx2 both hardware and software renderers those butterflies are invisible 

### Reproduction Steps

Reach the spot with the black butterflies 

Use this memory card, it's for PAL version of the game, load the save and reach that spot. 
[SH3.zip](https://github.com/user-attachments/files/16573134/SH3.zip)

### Expected Behavior

Butterflies to be visible, not invisible

### PCSX2 Revision

2.1.83

### Operating System

Windows 10 (64bit)

### CPU

Intel i5 12400f

### GPU

rtx 3060

### Emulation Settings

Default

### Logs & Dumps

Dumps are not useful for this issue.

**Comment by bslenul** [comment]
For anyone not familiar with the game and wanting to reproduce the issue, this is the path to get to the butterflies (you don't need to fight any enemy or anything, Triangle to open the map):

![image](https://github.com/user-attachments/assets/60c39f07-225d-4ad7-9c1a-0d439c43353d)

Seems to be tied to the framerate? The butterflies only disappear when the game is running at 60FPS (achieved by selecting the 60Hz mode in-game + enabling the 50Hz patch in PCSX2), from quick tests they appear fine at 25FPS (50Hz mode in-game), 30FPS (60Hz mode in-game) and 50FPS (50Hz mode in-game + 50Hz patch).

**Comment by bigol83** [comment]
Just checked, can confirm that's a side effect of 50/60 fps patch bundled by emulator.
