### ISSUE TITLE
[BUG]: Tales of Destiny 2 overworld glitch

### ISSUE THREAD

**Issue by lion65816** [PCSX2/pcsx2#11707]
### Describe the Bug

I've tried playing **Tales of Destiny 2** (Japanese exclusive), not to be confused with Tales of Eternia and most of the time I exit out into the overworld (which is in 3D, unlike the 2D submaps of the main game), the polygons for lack of a better term, go apeshit.

### Reproduction Steps

From what I can tell this seems to happen when the 2D graphics kind of "break" leaving a sort of black seam in the graphics (**fake edit:** no it just happens when you exit and enter the overworld a lot?), as it didn't really do this when I loaded up my save file from v1.6.0 (which I was using until a friend told me it was playable on 2.0 nightly, which I used more for games like Summon Night 3 and Devil May Cry) until I went in deeper into a mid to late game dungeon, the Spiral Cave, where I found one of those seams.

When I got out to try and rearrange my equipment and such to handle the boss better, the 3D graphics broke.

This isn't really reported anywhere I can find, and I really would like to avoid using the Discord server due to social anxiety.

This is mostly fixed in the older v1.6.0 and the game is pretty much playable from start to finish, barring an occasional sound stutter bug in the battle victory screen that results in a hardlock during fade out.

### PCSX2 Revision

v2.1.88

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800X

### GPU

RTX 4060 Ti

### Emulation Settings

I've only really altered the rendering mode to Software, I believe the Hardware rendering issue of black blob polygons is still in 2.0?

![graphics1](https://github.com/user-attachments/assets/fa676eb1-0e4d-4e69-8d73-8d7d5139b994)
![graphics2](https://github.com/user-attachments/assets/b7f5e828-3ed7-486d-8b95-ab3c8eb3872a)

### GS Window Screenshots

I've included images here.

The seam:
![Tales of Destiny 2_SLPS-25172_20240813083952](https://github.com/user-attachments/assets/e204c520-e098-4524-8e7f-044162988d44)

The 3D overworld, normally:
![Tales of Destiny 2_SLPS-25172_20240813084037](https://github.com/user-attachments/assets/326f75e9-95b2-4f44-b401-e5a7c2a2342c)

The 3D overworld, when its glitching (the vertices are going insane, really):
![Tales of Destiny 2_SLPS-25172_20240813084201](https://github.com/user-attachments/assets/dd010048-2775-4b04-9515-7410ee55a7e0)

### Logs & Dumps

GS dump is over here:
[Tales of Destiny 2 3D Polygon Explosion.zip](https://github.com/user-attachments/files/16596304/Tales.of.Destiny.2.3D.Polygon.Explosion.zip)

Hope I've supplied enough to work this bug out. I'll move everything back to v1.6.0, I'm totally fine with dealing with the stutter bug for now.

**Comment by Farran666** [comment]
Sounds like an sps. Do you have a savestate?

**Comment by lion65816** [comment]
Hold up, I'll post one in a while. I've already reconfigured everything to the other version.

Give me an hour or so, I'll have this tab open to remind me. (bowing emoji i guess lol)

**Comment by lion65816** [comment]
Here you go, fam.

[Tales of Destiny 2 state.zip](https://github.com/user-attachments/files/16596690/Tales.of.Destiny.2.state.zip)

**Comment by Farran666** [comment]
Needs `mvuFlag: 0` for the sps. As for the seam, it's only present when I'm using the software renderer.

**Comment by lion65816** [comment]
I see, let me give it a go.

**Comment by lion65816** [comment]
Yeah seems to have worked.

For casual users reading this, it's under the Advanced tab, check the Show Advanced Settings check under the Tools section of the Toolbar. The flag was under "Hack do Indicador de mVU" for me, since I am using the kinda messy but usable PT-PT translation.

I'll keep playing and let you know if anything comes up. Thanks, though!

I'll let my friend know as well, even if he can't read Japanese. Walkthroughs do exist after all!

**Comment by lion65816** [comment]
Okay, I'm at the endgame, just prepping for the final dungeon and the post-game dungeon (Aqua Labyrinth, no details needed) and it's mostly stable.

Only real issue is the AI sometimes malfunctioning and causing stuff like Kyle repeatedly jumping. While fighting Gaap in the Kalviola Temple before the endgame timeline, there was a point where Loni just didn't do anything which is weird?

I am playing the game at 2x speed due to how slow paced it is for me, like just generally, not in terms of slowdown (I'm doing the same with Summon Night 3) so I can sort of deal with it regardless.

**Feel free to close this for now**, but if you wish to explore the AI issue, consider opening a new issue? Hope I was helpful.

(also i accidentally closed my firefox with a keyboard shortcut while typing HELP)

**Comment by Farran666** [comment]
> Okay, I'm at the endgame, just prepping for the final dungeon and the post-game dungeon (Aqua Labyrinth, no details needed) and it's mostly stable.
> 
> Only real issue is the AI sometimes malfunctioning and causing stuff like Kyle repeatedly jumping. While fighting Gaap in the Kalviola Temple before the endgame timeline, there was a point where Loni just didn't do anything which is weird? It's fixable by just attacking or moving away in battle though.
> 
> I am playing the game at 2x speed due to how slow paced it is for me, like just generally, not in terms of slowdown (I'm doing the same with Summon Night 3) so I can sort of deal with it regardless.
> 
> **Feel free to close this for now**, but if you wish to explore the AI issue, consider opening a new issue? Hope I was helpful.
> 
> (also i accidentally closed my firefox with a keyboard shortcut while typing HELP)

If you have a savestate of the bug maybe I can look into it.

**Comment by lion65816** [comment]
> If you have a savestate of the bug maybe I can look into it.

I haven't been able to trigger it reliably sadly.

**Comment by lightningterror** [comment]
Closing as the sps issue was resolved.
