### ISSUE TITLE
[BUG]: Tourist Trophy running slow since version 2.1.60.

### ISSUE THREAD

**Issue by guily666999** [PCSX2/pcsx2#11708]
### Describe the Bug

US Bios, US version of Tourist Trophy and all versions of PCSX2 I tried below 2.1.60 the game runs fine while from that version and above to the latest the game runs slow for me, not only lower FPS but kinda a bit in slow motion even the sound is a bit slow.

Also I'm using a complete texture pack made by me.

### Reproduction Steps

Just open PCSX2, play the game go to arcade, time trial, chose any track, any bike and play...

### Expected Behavior

Game should have run fine at 60 FPS like the versions below...

### PCSX2 Revision

2.1.60 to 2.1.88

### Operating System

Windows 10 (64bit)

### CPU

I7 8700K OC to 4.9ghz

### GPU

Strix ROG RX 6700 XT

### GS Settings

![Captura de Ecrã (299)](https://github.com/user-attachments/assets/8e0d2d50-f47a-47bb-bccb-e4bcfef63801)
![Captura de Ecrã (293)](https://github.com/user-attachments/assets/4556b082-5a4f-48d2-951a-ddc43c80307b)
![Captura de Ecrã (294)](https://github.com/user-attachments/assets/66006597-866d-4310-af28-e46e92da6cde)
![Captura de Ecrã (295)](https://github.com/user-attachments/assets/5fe0946f-369a-4233-a0f5-c90faaccae03)
![Captura de Ecrã (296)](https://github.com/user-attachments/assets/d7511088-e928-48af-a7b1-1eafe7547030)
![Captura de Ecrã (297)](https://github.com/user-attachments/assets/21d286f3-d877-4579-9a46-e3ffeaaa949c)
![Captura de Ecrã (298)](https://github.com/user-attachments/assets/c55bfe32-0ba4-40b7-97c8-56db5d534afd)

**Comment by lightningterror** [comment]
We don't support piracy.
