### ISSUE TITLE
[BUG]: PCSX2 incorrectly limits FMV speed

### ISSUE THREAD

**Issue by Farran666** [PCSX2/pcsx2#11700]
### Describe the Bug

PCSX2 limits the frame rate according to the game's region, but not its video's speed, resulting in freezes in both #11023 and #4886 as well as incorrect audio in #3603 all because videos were playing faster than they were designed to.

### Reproduction Steps

Check the linked issues.

### Expected Behavior

For PCSX2 to automatically detect the FMV speed and set it as the frame rate limit for as long as the fmv runs.

### PCSX2 Revision

2.1.71

### Operating System

Windows 11

### CPU

i5-8400

### GPU

GTX 1080 TI

**Comment by F0bes** [comment]
We don't limit the frame rate. We provide the sync clocks and the game controls the rest.
