### ISSUE TITLE
[BUG]: Prince of Persia - The Sands of Time (Europe) (Demo) doesnt detect your gamepad in Prince of Persia 1

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#11726]
### Describe the Bug

load the game and choose Prince of Persia 1
it doesnt find your gamepad it use the keyboard

### Reproduction Steps

load the game and choose Prince of Persia 1

### Expected Behavior

use your gamepad

### PCSX2 Revision

v2.1.98

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 31.92 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3

### GPU

NVIDIA GeForce RTX 3060'

**Comment by RedPanda4552** [comment]
Please use the Discord for support.

**Comment by benderscruffy** [comment]
i dont join Discords
