### ISSUE TITLE
[BUG]: Tony Hawk's Underground missing load screens/flickering graphics 

### ISSUE THREAD

**Issue by joepogo** [PCSX2/pcsx2#11745]
### Describe the Bug

Just testing on the newest nightly build. 

Using hardware mode on standard settings the loading screens are missing and levels have flickering graphics when skating around. 

Changing to dx11 or dx12 doesn't matter. I tested an older build and this issue is not present. 

### Reproduction Steps

Start a game and the loading screens are missing and then start a new game and the graphics are flickering all over the area. This is especially apparent on ground textures. 

### PCSX2 Revision

V2.1.104

### Operating System

Windows 11

### CPU

Unknown 

### GPU

Unknown

**Comment by JordanTheToaster** [comment]
Please use the Discord for support.

**Comment by joepogo** [comment]
I'm sorry, I'm new to all of this. So report the bug is discord instead?
