### ISSUE TITLE
[Feature Request]: Request for Franchise and Chronology Sorting Fields in PCSX2 Game List

### ISSUE THREAD

**Issue by TobbyCy** [PCSX2/pcsx2#11747]
### Description

I would like to propose a new feature that enhances the organization and sorting capabilities of the game list in PCSX2. Specifically, I suggest adding two new fields: Franchise and Chronology Order. These fields would allow users to categorize and sort games not just by their titles, but by their franchise and the correct order within that franchise.

### Reason

This feature would be particularly beneficial for franchises like Jak and Daxter, Ratchet and Clank, Sly Cooper, GTA, Splinter Cell, and others where the titles do not necessarily reflect the correct order of play.

### Implementation Suggestion:

    Add two optional metadata fields to the game list: Franchise (string) and Chronology Order (integer).
    Allow sorting of the game list by these fields in addition to the existing title and other criteria.

Thank you for considering this feature request. I believe it would greatly enhance the user experience for those managing large collections of games in PCSX2.

### Examples

For example, the current sorting by game titles can lead to incorrect orderings in certain franchises. Consider the Jak and Daxter series, where sorting by title results in the following order:

    Jak 3
    Jak And Daxter - The Lost Frontier
    Jak And Daxter - The Precursor Legacy
    Jak II - Renegade
    Jak X - Combat Racing

This order does not reflect the chronological or narrative sequence of the games. By introducing a Franchise field with a value such as "Jak and Daxter" and an Order field where each game is assigned a number reflecting its place in the series (e.g., 1 for "The Precursor Legacy," 2 for "Jak II," etc.), users could easily sort and display games in the correct narrative sequence.

**Comment by F0bes** [comment]
I agree that this would be a good idea.
This is also requrested [here](https://github.com/PCSX2/pcsx2/issues/11666) so I will close this issue as a duplicate.
