### ISSUE TITLE
[BUG]: Emulator opens and closes, or doesn't open at all

### ISSUE THREAD

**Issue by Zukeberg** [PCSX2/pcsx2#11740]
### Describe the Bug

I have a problem starting the emulator, I click on it to open, but nothing happens, I uninstalled it, downloaded the winrar file, I did the whole process, when I click on the program, it simply doesn't open, when I put it on the system windows 8 compatibility, it opens the screen and then closes it

### Reproduction Steps

![error](https://github.com/user-attachments/assets/ffcf8611-9dcd-415a-aced-a59ef97eb271)
he opens this page and then closes it

### PCSX2 Revision

v2.0.2

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 5600gt

### GPU

ryzen 5 5600gt integrated board

**Comment by RedPanda4552** [comment]
Please use the Discord for support.

**Comment by Zukeberg** [comment]
what is the discord link?
