### ISSUE TITLE
[BUG]: Folder memory card not loading saves (GTA LCS - EU)

### ISSUE THREAD

**Issue by grzi** [PCSX2/pcsx2#11754]
### Describe the Bug

Using folder memory card on my macbook pro M1 isn't loading game saves (on GTA LCS).

### Reproduction Steps

- Use a mac (can't say if it's Mac related or not)
- Create a .ps2 memory card (8Mo). 
- Format the memory card in the bios
- Open the game
- Complete the first mission, save, quit.
- Convert to folder
- Insert folder memory card in slot 1 to replace the .ps2 one
- Launch the game 
- The game restart from scratch, whereas with the .ps2 it's ok.

### Expected Behavior

Convert from .ps2 to folder memory card should be consistent. 

### PCSX2 Revision

v2.0.2

### Operating System

macOS 14 (Sonoma)

### Logs & Dumps

[memory8mo.txt](https://github.com/user-attachments/files/16754142/memory8mo.txt)
[folder.txt](https://github.com/user-attachments/files/16754143/folder.txt)

**Comment by MrCK1** [comment]
We don't provide support for piracy. For further assistance, please use the Discord and send proof of console/game ownership with your username/date
https://discord.gg/NmMNtWmJ
```
[  573.2695] BIOS Found: USA     v02.20(10/02/2006)  Console 20060210-142424
[  573.2734] BIOS Found: Europe  v01.90(23/06/2003)  Console 20030623-142401
[  573.2758] BIOS Found: USA     v02.00(14/06/2004)  Console 20040614-100909
[  573.2791] BIOS Found: USA     v01.60(07/02/2002)  Console 20020207-164243
[  573.2823] BIOS Found: China   v01.90(23/06/2003)  Console 20030623-142419
[  573.2855] BIOS Found: Europe  v01.70(27/02/2003)  Console 20030227-193050
[  573.2883] BIOS Found: Europe  v01.60(04/10/2001)  Console 20011004-175839
[  573.2912] BIOS Found: Japan   v01.20(27/10/2000)  Console 20001027-191435
[  573.2927] BIOS Found: Asia    v02.20(05/09/2006)  Console 20060905-125923
[  573.2964] BIOS Found: Europe  v02.20(05/09/2006)  Console 20060905-125923
```

**Comment by kattjevfel** [comment]
I'm having this exact issue but on linux, pcsx2 v2.3.0. None of my saves from a memory card folder will load and saving and restarting the game will result in PCSX2 not finding it. Also seemingly only on GTA LCS and GTA VCS.

**Comment by Mrlinkwii** [comment]
@kattjevfel  please use discord for support
