### ISSUE TITLE
[Feature Request]: Setup Implement Plugin Library

### ISSUE THREAD

**Issue by mame-rr-player001** [PCSX2/pcsx2#11762]
### Description

It seems that there're no Plugin Library Setup Function in PCSX2  since v2.0.0.
I want to implement and QEmu plugin.
Please implement this function as v1.6.0.
Thanks

### Reason

I want to implement and QEmu plugin.

### Examples

PCSX2 v1.6.0

**Comment by F0bes** [comment]
The entire plugin subsystem has been removed, and will not be returning. If you want to implement additional features, you need to add them to pcsx2 directly.

**Comment by mame-rr-player001** [comment]
Thanks for you to reply.
I see as you say.
I use PCSX2 v1.6.0 to play in implement some Plugins.

**Comment by TheLastRar** [comment]
What are you wanting implemented?

**Comment by TheLastRar** [comment]
USB devices can be setup in Settings->Controllers->USB Port 1/2
Support for both wheels and GunCon 2 can be found there.

If you need help setting up those devices, feel free to ask in our discord.
If you are wanting a device that is still unsupported, see this tracking issue https://github.com/PCSX2/pcsx2/issues/4763

**Comment by mame-rr-player001** [comment]
Thanks I can setup GunCon 2 as you say.
I'll try to setup wheel too later...

And..., ah..., I hava question.
How can I setup Forcefeedback in wheels setup?

**Comment by TheLastRar** [comment]
> And..., ah..., I hava question. How can I setup Forcefeedback in wheels setup?

I'm unsure as I don't have a wheel, 
You may want to ask in our discord for help https://pcsx2.net/discord

**Comment by mame-rr-player001** [comment]
Thanks for your reply.
I'll do as it is.
And then I hope it will implement correct forcefeedback setup.
