### ISSUE TITLE
[BUG]: sly 2 ntsc u shadow problem

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#11761]
### Describe the Bug

in dx12 sly's shadow sometimes goes invisible

### Reproduction Steps

use dx12

### Expected Behavior

missing shadow

### PCSX2 Revision

2.119

### Operating System

Windows 11

### CPU

7840hs

### GPU

4070

**Comment by JordanTheToaster** [comment]
You shouldn't be using DX12 in future please use the Discord for support.

**Comment by Emi-pcsx2** [comment]
> You shouldn't be using DX12 in future please use the Discord for support.

It works better for my computer, we have talked about this before

**Comment by JordanTheToaster** [comment]
> > You shouldn't be using DX12 in future please use the Discord for support.
> 
> It works better for my computer, we have talked about this before

And I've told you before that DX12 is awful and you have a 4070 that is perfectly capable of Vulkan.

**Comment by Emi-pcsx2** [comment]
> > > You shouldn't be using DX12 in future please use the Discord for support.
> > 
> > It works better for my computer, we have talked about this before
> 
> And I've told you before that DX12 is awful and you have a 4070 that is perfectly capable of Vulkan.

I literally get worse performance and there is no visual difference
