### ISSUE TITLE
[BUG]: Shadow Hearts: Covenant menu sprite lines when upscaling

### ISSUE THREAD

**Issue by gingsz** [PCSX2/pcsx2#11766]
### Describe the Bug

When upscaling the game other than native resolution, lines appear in the menu graphics.

### Reproduction Steps

Start game, open menu.

### PCSX2 Revision

v2.1.120

### Operating System

Windows 11

### CPU

i7-4790

### GPU

RTX 4060

### GS Window Screenshots

Upscaled:
![Shadow Hearts - Covenant  Disc 1 of 2 _SLUS-21041_20240901161257](https://github.com/user-attachments/assets/3bf1f5f8-db7d-46f1-8e6f-e842b0362931)

Native Resolution:
![Shadow Hearts - Covenant  Disc 1 of 2 _SLUS-21041_20240901161331](https://github.com/user-attachments/assets/af5c1ef9-4801-48a6-9685-33f988944f97)

With Full sprite rounding, fixes a little, but the 3d render becomes blurry.

![Shadow Hearts - Covenant  Disc 1 of 2 _SLUS-21041_20240901161500](https://github.com/user-attachments/assets/96d2ee16-258a-40ea-8bb9-0e48d8606846)

### Logs & Dumps

Gs dump [Shadow Hearts - Covenant SLUS-21041_20240901162432.gs.zip](https://github.com/user-attachments/files/16829259/Shadow.Hearts.-.Covenant.SLUS-21041_20240901162432.gs.zip)

**Comment by Mrlinkwii** [comment]
We do not accept issues relating to upscaling at this time.
 We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling.
 
 use the discord for help with upscaling

**Comment by GitHub-Khi** [comment]
Ever tried Texture Filtering: Nearest with Round Sprite: Half?
![1](https://github.com/user-attachments/assets/150907d4-a288-4f65-ac7c-7783cfae51a6)
