### ISSUE TITLE
[BUG]: "Donald Duck: Goin' Quackers" / "Donald Duck: Quack Attack" fails to start

### ISSUE THREAD

**Issue by jroyvde** [PCSX2/pcsx2#11770]
### Describe the Bug

On starting the game, a black screen is shown with the text, "Initializing..." in the bottom-right corner. The game never progresses from this screen. This happens with both the USA (Goin' Quackers) and Europe (Quack Attack) versions of the game. Both dumps are redump-verified with the correct hash. The problem also occurs even with cheats, widescreen and interlacing patches, and gamefixes all disabled. It also happens with both compressed .chd and the standard .bin/.cue pair.

![Screenshot_20240902_113859](https://github.com/user-attachments/assets/7655ec44-19ec-48e3-861a-4933da2dfb91)

### Reproduction Steps

Try to play Donald Duck: Goin' Quackers or Quack Attack in PCSX2.

### Expected Behavior

The game should play normally.

### PCSX2 Revision

v2.1.121 (Flatpak)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Fedora 40

### CPU

12 × AMD Ryzen 5 5600 6-Core Processor

### GPU

AMD Radeon RX 5700 XT

### Logs & Dumps

[log.txt](https://github.com/user-attachments/files/16831354/log.txt)

**Comment by Farran666** [comment]
OpenSpace engine games are very sensitive to VU0 timing. Have you tried lowering the ee cyclerate?

**Comment by Goatman13** [comment]
Disable Multitap is settings. ScePadPortOpen overwrites required data (opcode at 0x002321B0) when multitap is enabled. 
No idea why, looks like game bug, but older pcsx2 is fine. Maybe something in new SIO implementation?

**Comment by Goatman13** [comment]
> which older version did you try @Goatman13

That's not gonna be helpful :D It was 1.7.3045 (wx)...
Maybe op can help here with bisecting version when it was broken.

**Comment by Mrlinkwii** [comment]
Sorry for the additional question is it broken on 2.0 ? @Goatman13

**Comment by Goatman13** [comment]
Yes, it's broken on stable 2.0.0, on stable 2.0.2, and on latest nightly.

**Comment by prafullpcsx2** [comment]
The game works fine here. May be this is some sort of compatibility issues with specific Bios?

**Comment by jroyvde** [comment]
It's definitely to do with the multitap, after turning it off the game starts fine. I'll try testing with older versions when I get some free time to see if we can figure out where the change happened.

Would also be curious to know if the same thing happens on real hardware, if anyone happens to have a multitap and a copy of the game.

**Comment by Goatman13** [comment]
> The game works fine here. May be this is some sort of compatibility issue with specific Bios?

Looks like only multitap in second port is problem.
Mtap 1 = Working
Mtap 2 = Not Working
Mtap 1+2 = Not Working

I retested this just for sure on old 1.7.3045 and it is fine even with active Mtap in port 2.

**Comment by mrtawsiti3** [comment]
I remember trying this game and it did not work like montha ago. Can confirm

**Comment by bslenul** [comment]
Bisected, game loads fine in 1.7.4862 but gets stuck in 1.7.4863, so it started happening with one of the 2 commits from PR #9664

**Comment by RedPanda4552** [comment]
Did some hardware tests, this game appears to be coded with hot glue and popsicle sticks. This might be one of the more disappointingly funny hardware tests I've done in a long time.

Test cases are formatted as Port 1 / Port 2 / Result:

- DS2 / None / Boot
- None / DS2 / Fail
- Mtap + DS2 (slot A) / None / Fail
- None / Mtap + DS2 (slot A) / Fail
- DS1 / None / Fail
- None / DS1 / Fail
- Digital / None / Fail
- None / Digital / Fail
- DS2 / Digital / Fail
- DS2 / DS1 / Fail
- DS2 / Mtap (Empty) / Fail

Now we take a step into absurdity. I had to try this for the sake of completeness, and I was not disappointed.

- IR Receiver / None / Boot
- Mtap + IR Receiver (slot A) / None / Fail
- IR Receiver / DS2 / Fail
- DS2 / IR Receiver / Fail
- None / None / Stuck at "Initializing"

The last one here being a different result is not a mistake. All other cases froze at a black screen. 

This test set is not exhaustive, there are many more permutations I could run through. But I think this gets the point across.

The most curious thing about this behavior is that multitaps are designed to behave like a basic passthrough device if no actual initialization is done; for example, the PS2 BIOS makes no attempt to load libmtap and does no kind of initialization or handshake with the multitap. However, the multiap as a hardware device will after receiving power, default to slot A as its active slot and patiently await a command from the console to switch slots. Or, sit there forwarding to slot A forever if the console never does send a slot switch command.

So... If having a multitap inserted ends up then causing the game to hang in the same manner as having a non-DS2 controller... That suggests that: 

1. The game is explicitly checking if the controller reports itself as having DS2 features, and ditching itself into a trap or death loop if not.
2. The game is explicitly loading libmtap, only to check if a multitap is present, and again ditch itself into a trap or death loop if a multitap is found.

So there definitely is some inaccuracy in PCSX2. Towards the side of, PCSX2 is being more forgiving and somehow enabling the game to boot, when it shouldn't? Which is very odd, but now we've certainly got another interesting test case to look at.

**Comment by RedPanda4552** [comment]
Going to close this for now. There are accuracy improvements to be made, but since the behavior in PCSX2 is actually more forgiving to the user because of the lesser accuracy, I'm not inclined to keep an open issue.
