### ISSUE TITLE
[BUG]: crash when trying to access menus

### ISSUE THREAD

**Issue by Mkeays501** [PCSX2/pcsx2#11772]
### Describe the Bug

whenever i try to open the settings or anything involved with that the app freezes forcing me to kill it

### Reproduction Steps

relaunch, try to click on settings, crash. kill relaunch , try to access settings, crash

### Expected Behavior

to be able to change bios

### PCSX2 Revision

v2.1.121

### Operating System

Windows 11

### If Linux - Specify Distro

kali linux

### Logs & Dumps

[emulog.txt](https://github.com/user-attachments/files/16838162/emulog.txt)

**Comment by JordanTheToaster** [comment]
Please use the Discord for support issues.

**Comment by Mkeays501** [comment]
Do I absolutely need to use discord ? I'm not on discord anymore

**Comment by JordanTheToaster** [comment]
> Do I absolutely need to use discord ? I'm not on discord anymore

Yes.

**Comment by F0bes** [comment]
We have the forums if you're more comfortable there.
