### ISSUE TITLE
[Feature Request]: GUI - move away Post-processing from Graphics to it's own separate section.

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#11775]
### Description

I know there have been quite nice cooperation instances between [PCSX2](https://github.com/PCSX2/pcsx2) and [duckstation](https://github.com/stenzek/duckstation ) emulation projects and some features of the later has been incorporated to PCSX2 already

I personally like the way duckstation approaches post-processing shaders, could it be some interest on port it over, also include the many shaders duckstation have out-of-the-box.

### Reason

Given the many aspects both emulators shares, GUI-wise but functional wise too. I consider duckstation shader / post-processing features superior to PCSX2 and thus PCSX2 could greatly benefit by porting these features over.

Now, It might be that there are fundamental / technical reasons why this could not be possible, or at least easily ported as is that I'm not aware of 

### Examples

PCSX2
![image](https://github.com/user-attachments/assets/62f44bad-6ce6-4c4e-8f96-ff87f7f328fc)

duckstation
![image](https://github.com/user-attachments/assets/e5f8a4c8-a33e-451d-b349-a51064fb0c0a)

**Comment by lightningterror** [comment]
It fits more where it is as it's related to graphics.

**Comment by F0bes** [comment]
If we had an entire external shader system it might make sense for the extra window space. Currently we just have small dropdown and some sharpening settings and like lightningterror said; it's current position makes sense.
