### ISSUE TITLE
[BUG]: Pitfall: The Lost Expedition underwater levels graphic bug

### ISSUE THREAD

**Issue by Tmesys** [PCSX2/pcsx2#11776]
### Describe the Bug

Most of the scene is blue, we can't see anything mostly. Bug occurs when using OpenGL driver, it's almost OK for Vulkan driver with some glitches and artifacts, software driver works OK. Please note that when bringing up the menu using start, everything looks OK with OpenGL.

Hope this helps, thank you.

### Reproduction Steps

Just enter an underwater level, screenshots from the "flooded cave level" . 

Using BIOS SCPH-77008 (Europe version v02.20 date 01/02/2006.

**Level using Opengl driver :**

![image](https://github.com/user-attachments/assets/89ab4c1b-d17c-4f9c-9cd3-c5cf45ecc4e2)

**Level using Vulkan driver :**

![image](https://github.com/user-attachments/assets/79d5ed36-be68-4dc7-9ecb-bb2a54fa95c3)

**Level using Software driver :**

![image](https://github.com/user-attachments/assets/6dbe3b22-a55f-4725-bfab-3ed89b148c01)

**Start menu using OpenGL driver :** 

![image](https://github.com/user-attachments/assets/bdde8965-111b-4df8-89c5-829ae8993a02)

### Expected Behavior

Should work as when software driver is used.

### PCSX2 Revision

2.1.95

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Xubuntu 20.04.1 LTS - Kernel 6.10.7 custom build

### CPU

i3-10110U

### GPU

Intel iGPU UHD graphics CML GT2

### GS Settings

![image](https://github.com/user-attachments/assets/d9f24f3d-8913-4f20-82ea-cbb5e271835c)

### Emulation Settings

![image](https://github.com/user-attachments/assets/8c106c8f-37b5-4c56-bb88-d770f54357a0)

### GS Window Screenshots

![image](https://github.com/user-attachments/assets/99c5c7a9-85b6-4e46-b227-4a4404bb613d)
![image](https://github.com/user-attachments/assets/8152211f-e4a9-425b-9d25-9259d13e2a38)
![image](https://github.com/user-attachments/assets/1d4685f0-efb7-40e7-bd0e-dfc38a26ef92)
![image](https://github.com/user-attachments/assets/32854b1a-2db5-49ae-8529-69e118e8bcef)
![image](https://github.com/user-attachments/assets/9870e550-188a-4696-9e79-81f36d63c37b)

**Comment by JordanTheToaster** [comment]
Please use our Discord or the forums for support in future.
