### ISSUE TITLE
[BUG]: FileSystem: recursive CreateDirectoryPath with absolute path broken on Windows

### ISSUE THREAD

**Issue by scurest** [PCSX2/pcsx2#11784]
### Describe the Bug

If `FileSystem::CreateDirectoryPath` is called in the following situation

* on Windows
* with an absolute path (eg. `C:\...`)
* with recursive=true
* and the parent directory does not exist yet (ie. recursive is necessary)

then it will always fail to create the directory because of a bug in the [recursive implementation](https://github.com/PCSX2/pcsx2/blob/7d6f74083ba656f7de0a6a2148be4851bf987620/common/FileSystem.cpp#L1726-L1777).

The way recursive CreateDirectoryPath works is given `C:\aaa\bbb`, it will attempt to create the following sequence with CreateDirectoryW

```
C:
C:\aaa
C:\aaa\bbb
```

However for `C:`, CreateDirectoryW fails with `ERROR_PATH_NOT_FOUND` instead of what the code is expecting, `ERROR_ALREADY_EXISTS`. (Note that `C:\`, `\\?\C:`, and `\\?\C:\` all produce the same result.) This causes it to stop at the first step with an error.

I have a [work-around](https://github.com/PCSX2/pcsx2/commit/854e82e53d6ca0ecf70832734456fc0196a10902) that skips a prefix ending with `:\`. This is working for me, but I don't know how robust it is.

### Reproduction Steps

I found this while working on a branch where I called CreateDirectoryPath. I don't know if there is a way to actually trigger this bug from within main PCSX2, so if you don't want to track this without a repro, you can close it.

AFAICT CreateDirectoryPath is called with recursive=true only twice in the codebase, once in [QtHost.cpp](https://github.com/PCSX2/pcsx2/blob/7d6f74083ba656f7de0a6a2148be4851bf987620/pcsx2-qt/QtHost.cpp#L1596) and once in [MemoryCardFolder.cpp](https://github.com/PCSX2/pcsx2/blob/7d6f74083ba656f7de0a6a2148be4851bf987620/pcsx2/SIO/Memcard/MemoryCardFolder.cpp#L2000). I don't know whether these callsites are vulnerable or not.

### PCSX2 Revision

f1abee5d0ba5af70454b1c956bce42060d3cd98e

### Operating System

Windows 10 (64bit)

**Comment by TheLastRar** [comment]
Can you give the change here a test https://github.com/PCSX2/pcsx2/pull/11798
