### ISSUE TITLE
[Feature Request]: Add more shaders to emulator

### ISSUE THREAD

**Issue by madruded** [PCSX2/pcsx2#11785]
### Description

Please, add more TV shaders to emulator and CRT filters. Same as Duckstation have.

### Reason

The reason is to perfectly play and rescue the nostalgia times.

### Examples

Duckstation emulator has a lot of shaders

![Captura de tela 2024-09-07 094141](https://github.com/user-attachments/assets/8b85bb49-6307-4270-9696-77f93434b187)

**Comment by F0bes** [comment]
This isn't that high of a priority. If someone wants to bring over shaders they are free to do so.

**Comment by tails101** [comment]
for me, crt beam simulator is a must have with bfi.
it gives that signature crt motion clarity.
