### ISSUE TITLE
[BUG]: Version number reported by Windows Builds of PCSX2 does not follow semantic versioning standard

### ISSUE THREAD

**Issue by AstralPhnx** [PCSX2/pcsx2#11780]
### Describe the Bug

The latest stable builds of PCSX2 are being packaged in a way whereby the windows installer package is applying a version number in the system registry that does not follow the semantic versioning standards (see here https://semver.org/). Should be just 2.0.2 not v2.0.2.

As a result, the ability to update PCSX2 using the winget package manager and the winget community repos is currently broken. 
I first considered updating the winget manifest itself but all manifest files are supposed to obey semantic versioning standards, hence the following issue report. Should be a relatively simple fix I imagine. 

### Reproduction Steps

Shouldn't be necessary but see attached screenshot to see how PCSX2 is reporting to windows as "v2.0.2" and how that makes winget unable to parse the package version properly. Note the value of v2.0.2 being reported in the Version column. Semantic Versioning Standards mean that the v should be dropped from the version number so it just reports as 2.0.2. You'll also be able to see this behavior reflected if you check the version number via the Add Remove Programs part of the control panel.

![image](https://github.com/user-attachments/assets/6ccec342-4b77-48ae-8c83-ef268ee42ff5)

### Expected Behavior

Should be showing as 2.0.2 instead of v2.0.2 

Again, should be a simple fix. You'll probably just need to tweak the innoinstaller package so it reports properly.

### PCSX2 Revision

2.0.2

### Operating System

Windows 11

**Comment by F0bes** [comment]
Thanks for reporting.
I've changed our installer action (which we will be using in the future) to remove the leading v from the program version.
https://github.com/PCSX2/pcsx2-installer/commit/882baa5f5548a5b30cb873ee01589b60bfe12932
See here
![image](https://github.com/user-attachments/assets/83dd50b9-1456-4434-8859-a9f8cd0002a9)
(as opposed to v2.1.141)

**Comment by F0bes** [comment]
Also, I don't want to change the installer binary for the existing v2.0.2. We will see this change in production next release 
(which is hopefully soon!)
