### ISSUE TITLE
[Feature Request]: Ignore Dumping of Hash Changing Textures

### ISSUE THREAD

**Issue by ch1ckenstripper** [PCSX2/pcsx2#11792]
### Description

I'm not sure if anyone has asked for this particular feature. I understand the texture dumping/replacement  is complicated to say the least. I use an auto upscaler that runs automatically and refreshes the textures in game while I'm playing. So the game gets "remastered" as I'm going. 
My problem specifically: The textures that load every frame that dump thousands of files in short order to the folder.
The textures with changing hashes that appear every time you say... open a menu, isn't a problem. It's the ones that load every frame that make the autoupscaler unusable and clog up.
Long story short, if there is a way to detect every-frame texture dumping and disable it, or ignore dumping changing hashes... I would be overjoyed.
Thanks!

### Reason

Making texture packs is... difficult right now, you have to play the whole game to dump all the textures to upscale them right? So the solution to me is real-time upscaling. Can't do that with a folder of 60,000 "garbage" files. You guys already put a "refresh texture replacements" hotkey: that is what makes real-time replacement viable.

### Examples

Many games have at least some animated texture that changes hashes. I have found Silent Hill 2's fog to do this.

**Comment by F0bes** [comment]
IIRC the correct explanation is that we dump textures when they are read by the GS, not when they are sampled by the GS.
The GS reads in 2^n width and height "blocks". This means that games will read 128x128, but might only use 100x100. What's left over is still calculated in the hash, but the contents might be random garbage.
It has been discussed many times, but from my understanding there no is way to reliably tell what part of a texture is used and what is not.
We just consider games that generate a bunch of these "garbage" textures as not feasible for texture replacement.
