### ISSUE TITLE
Switching plugins makes FolderMemoryCard to not work

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1179]
1.Start any game(I only tried 3 but it's probably the same for any game)
2.Switch any plugin(GSdx in my case but pcsx2 act the same way when you are changing plugins)and hit yes.

Now when you try to access the card,it will say that the card is not detected.
If you restart the game(no pcsx2 restart nor running another game first)it will also not detect the cards

**Comment by willkuer** [comment]
I guess filememorycard works just fine?

Just pinging again @AdmiralCurtiss to ask for help.

**Comment by turtleli** [comment]
This only seems to happen when "Automatically manage saves based on running game" is enabled.

The filter string becomes empty when any plugin is switched, therefore no saves are detected.

**Comment by AdmiralCurtiss** [comment]
Don't merge that commit, I'll see if I can make the whole filter setting procedure less brittle (it's quite ugly...), but this is indeed what's going on there, resetting the cached filter string on memory card plugin closing so the next setting causes a re-index fixes it.
