### ISSUE TITLE
[Feature Request]: Please hide the cursor when in game

### ISSUE THREAD

**Issue by NastyFlytrap** [PCSX2/pcsx2#11797]
### Description

Im playing with a controller, obviously. I dont need to see the cursor. Please make it invisible

### Reason

Its annoying to have it on screen

### Examples

Any game where you arent using the mouse

**Comment by RedPanda4552** [comment]
Settings > Interface > Hide Cursor in Fullscreen

Or, if you are not playing in fullscreen, move the cursor off of the window area or to the edge of the screen.

GitHub is for technical discussion and issues. For future help and support, please use our Discord or the PCSX2 Forums.
