### ISSUE TITLE
[BUG]: ATV Offroad Fury 2 upscaling causes texture corruption on certain levels

### ISSUE THREAD

**Issue by viksmir** [PCSX2/pcsx2#11803]
### Describe the Bug

Playing certain levels on ATV Offroad Fury 2 when emulating with non-default PS2 resolution (so any sort of upscaling) corrupts textures. The texture of the track map was replaced by the alphabet map. Another texture in the bottom right also became corrupt.

Some other game modes work okay.

### Reproduction Steps

This issue can be reproduced by loading a specific level (the default level):
- (1) Single Player
- (2) Race
- **Event Type** - Amateur Nationals
- **Environment** - Prospect Springs
- **Race Mode** - Single Race
- **Number of Labs** - 5
- **Difficulty** - Normal

The issue appears immediately upon loading a level. The corrupted texture of the track map actually changes a few times (interesting detail).

The issue was tested with the initial release (v1.0) and the re-release (v2.0). 

### Expected Behavior

Expected to upscale an image without texture corruption.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5800X3D

### GPU

RTX 3090

### GS Settings

Internal Resolution set to anything other than Native.

### GS Window Screenshots

![image](https://github.com/user-attachments/assets/253abe64-a80f-467e-a119-ec88f836aecb)

**Comment by JordanTheToaster** [comment]
Update to the latest nightly and it'll be fixed.
