### ISSUE TITLE
[BUG]: Crash Tag Team Racing Loading Screen Assertion Fail FQC

### ISSUE THREAD

**Issue by ironhulk33** [PCSX2/pcsx2#11827]
### Describe the Bug

So this happend at least an hour or so after a updated to 2.1.156. Was Playing Crash Tag Team Racing ((Verfiyed Game and its good)) and every loading screen when loading into a race is crashing the game. I have a photo i can provide down bellow but what it says is:

"Assertion Failed in function ReadFIFO_VIF1
(D:\a\pcsx2\pcsx2\pcsx2\FiFo.cpp:32):

FQC + 0 on VIF FIFO READ!

Press Abort to exit, Retry to Break to debugger, or Ignore to attempt to Continue."

Serial is SLUS-21191 and CRC is AA525269

### Reproduction Steps

Im on a save state but any race i load into and on the loading screen after like 30sec it just gives me this bug.

### Expected Behavior

Load in after screen and start race like normal.

### PCSX2 Revision

2.1.156 and 154

### Operating System

Windows 10 (64bit)

### CPU

AMD FX(TM)-6300 Six-Core Processor

### GPU

Radeon(TM) RX 460 Graphics

### GS Window Screenshots

![CTTR assertion fail](https://github.com/user-attachments/assets/7d3cec8e-e42b-4ccc-95d8-731a0a40f3ba)

**Comment by kamfretoz** [comment]
Can't repro on v2.1.157:

Game boot up just fine and i can get into the races.

![pcsx2-qt_SA2BfqMqsN](https://github.com/user-attachments/assets/ed718b8f-e71c-460a-bd2c-02758bbdd403)

![pcsx2-qt_lfuOxYr4hG](https://github.com/user-attachments/assets/56e19894-3d16-4b41-9c91-3cbd6a2fb3f1)

**Comment by ironhulk33** [comment]
Thats Werid because im in astro world and i cant go and move on from anywhere....

**Comment by kamfretoz** [comment]
> Thats Werid because im in astro world and i cant go and move on from anywhere.... 

Please send your memcards and savestate up until that point.

**Comment by ironhulk33** [comment]
how?

**Comment by kamfretoz** [comment]
> how? Ill help out to replacate it on yalls end. Im good now i was just dumping the game to make a HD pack. I found a 100% save and dumped what i needed.

First make a savestate where its easy for us to trigger the crash, then Tools -> Open Data Directory, then go to the `sstates` folder and send the savestate here

And for good measure send us the memcard containing the appropriate save data as well, it should be on the `memcards` folder. Send it here and let us know the reproduction step for the crash.

**Comment by ironhulk33** [comment]
where do i share it on here is what im asking cause it doesnt let me add them

**Comment by kamfretoz** [comment]
Astro Land works just fine here, you probably have a broken savestate.

![image](https://github.com/user-attachments/assets/db60ab93-2779-4af2-b0d7-d2d2621415a1)

![image](https://github.com/user-attachments/assets/e120e76e-c639-4afa-8ac8-7df52fac9772)

**Comment by F0bes** [comment]
Can you confirm, do you always load from a savestate? Or do you load the game fresh (as if you just turned on the PS2) and load from the memory card?

**Comment by F0bes** [comment]
Confirmed on Discord that this is the case.

Days since savestates were used as memory cards and the game broke: 0
