### ISSUE TITLE
[BUG]: Tela de loading do Spartans : Total War

### ISSUE THREAD

**Issue by JonasYato** [PCSX2/pcsx2#11821]
### Describe the Bug

SEMPRE QUE PASSO A FAZE DOS BARBAROS LOGO DEPOIS DE MATAR BEALWOLF, VAI PARA TELA DE LOADING ESCRITO START, LOGO DEPOIS DISSO O JOGO CAI FPS PARA O 5 E TRAVA NO LOADING INFINITO

### Reproduction Steps

Abrir o jogo
iniciar o load da faze dos barbaros
finaliza a faze.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 11

### CPU

i5 11 geração

### GPU

placa integrada intel iris X

**Comment by Farran666** [comment]
@JonasYato Have you verified your dump?

**Comment by MrCK1** [comment]
Please use the discord for general support
https://discord.com/invite/TCz3t9k
