### ISSUE TITLE
[Feature Request]: God of War 2 - Cheat for Automatically completing QTE's

### ISSUE THREAD

**Issue by Veelkyn** [PCSX2/pcsx2#11831]
### Description

Okay, so before the PCSX2 2.0 update, there was a cheat that allowed users to bypass the context sensitive button pressing sequences. However, the new update seems to have broken this and now this code does not work. Can someone figure out what changed and how we can replicate it in the new PCSX2 version? Thank you. 

Here is the old cheat code for reference. There were two versions of it, one where it happened automatically, one where it could be disabled in game. 

```//context sensitive button presses

comment=Kratos Does Most Context Sensitive Button Moves Automatically (After You Enter Into One In Battle By Pressing Circle)
//note: Most button symbols dont even appear on screen,just sit back and watch Kratos perform them.
//note: The rapid button press does appear on screen but you dont have to do it,Kratos will always win.
//note: I haven't tested this in all situations so problems may occur,I have tested it against a few enemies and the [censored] boss and it worked flawlessly.
//note: The code doesn't seem to work on doors though.
patch=1,EE,201AA470,extended,03E00008
patch=1,EE,201AA474,extended,00000000
patch=1,EE,201A9F00,extended,03E00008
patch=1,EE,201A9F04,extended,00000000

//comment=Kratos Does Most Context Sensitive Button Moves Automatically (After You Enter Into One In Battle By Pressing Circle) (R1+L1+Right=On/R1+L1+Left=Off)
//note: same as above, if it causes glitches at certain spots, this one will allow you to disable when necessary
//patch=1,EE,E004F3DF,extended,0032F45C
//patch=1,EE,201AA470,extended,03E00008
//patch=1,EE,201AA474,extended,00000000
//patch=1,EE,201A9F00,extended,03E00008
//patch=1,EE,201A9F04,extended,00000000
//patch=1,EE,E004F37F,extended,0032F45C
//patch=1,EE,201AA470,extended,27BDFFD0
//patch=1,EE,201AA474,extended,7FB10010
//patch=1,EE,201A9F00,extended,27BDFF80
//patch=1,EE,201A9F04,extended,7FB50010```


### Reason

It's a very useful cheat that greatly enhances enjoyment of God of War 2. If you're someone who never liked the quick time events and simply wanted to watch Kratos do his cool killing animations on their own, this helped a lot. 

### Examples

This is how the cheat works in question. It's clean, flashy, and better to watch. 

https://streamable.com/zisc45

**Comment by F0bes** [comment]
I recommend you visit our discord to receive extended support instead.

**Comment by Veelkyn** [comment]
> I recommend you visit our discord to receive extended support instead.

I already have, unless your thinking of a different discord. But someone in the discord recommended I post this here lol. 

I'm in the "Patching-and-reversing" channel if you want to see me there.

**Comment by F0bes** [comment]
Beryl tried to fix your patch to make it conform to proper pnach standards. They then told you that if it doesn't work it's an issue with the patch itself. We have no way to provide support for the patches unfortunately as just creating them takes a lot of time and effort.
If you are 100% sure that it worked on a previous version, are you able to figure out what version broke?

**Comment by Veelkyn** [comment]
> Beryl tried to fix your patch to make it conform to proper pnach standards. They then told you that if it doesn't work it's an issue with the patch itself. We have no way to provide support for the patches unfortunately as just creating them takes a lot of time and effort. If you are 100% sure that it worked on a previous version, are you able to figure out what version broke?

yeah, sorry, I misunderstood them. And yes, I'm sure. If you look at the bottom of my post, where it says examples, I linked to a streamable video of how it looks when this cheat is working properly. I don't recall the PCSX2 version I used to capture that footage, but it worked. I can try a nightly before the 2.0 patch to see if it works there, just to make sure. 

And I just found all this on the internet. I have no idea how I would even check to see what broke.
