### ISSUE TITLE
[BUG]: Densha De Go Ryojohen With Zuiki

### ISSUE THREAD

**Issue by jaoxford** [PCSX2/pcsx2#11836]
### Describe the Bug

Thanks so much for putting the work into this. I've tried my Zuiki with all PS2 DDG titles and they work flawlessly. I'm using the Type 2 controller preset. 

However, I've stumbled upon one oddity. when playing Ryojohen, I want to set my controller type to be that type, so I can have control of the door operation. The issue is the brakes have this weird offset. My understanding is that in Ryojohen when using that specific controller, there aren't 8 levels of brake as is the case with Type 2 controls. So to get to the minimum braking force I need to put my brakes to level 4. 

Surely it should apply the brakes on level 1 when using the Zuiki controller.

By the way I found out I could do this from this PR: https://github.com/PCSX2/pcsx2/pull/11723

### Reproduction Steps

Play the game with a Zuiki controller, set the controller type to Ryojohen. Open the game

![image](https://github.com/user-attachments/assets/b1b76ee0-f4b9-40b4-b2f2-fc8b8d2b804e)

### Expected Behavior

I think it should apply the brakes when the controller is set to brake level 1, and not level 4.

### PCSX2 Revision

2.1.156

### Operating System

Windows 11

### CPU

Ryzen

### GPU

RTX2060

**Comment by jaoxford** [comment]
Having tested this, I believe the door operation works fine with the Zuiki and using type 2 controls. I think that was due to a misunderstanding on my part. I suppose I should only really use the Ryojouhen preset with that actual controller?

**Comment by joestringer** [comment]
@jaoxford yeah I added in case someone has a USB controller that can more easily vary the input axis. In practice when using a Zuiki you should always use Type 2, as the Zuiki has notches in the axis just like the Type 2. If you'd like to play Ryojōhen with non self-lapping brakes like in the base game, I'd suggest just using a Playstation controller and reduce the sensitivity so it's easier to feather the increase/decrease of brake pressure.

**Comment by jaoxford** [comment]
Thanks for your response! I might have to treat myself to the Ryojōhen controller! 😆

**Comment by joestringer** [comment]
@jaoxford tempting! Just be warned - the current feature in pcsx2 hasn't been tested at all with the Ryojōhen controller and it probably doesn't work without extra code changes.
