### ISSUE TITLE
[BUG]: Windows build doesn't correctly load ELF files in WSL filesystem

### ISSUE THREAD

**Issue by zachary-cauchi** [PCSX2/pcsx2#11843]
### Describe the Bug

When trying to load a homebrew ELF file from my dev environment in WSL, and PCSX2 is running on Windows natively, PCSX2 fails to correctly load  and always produces the below error:
`[    8.7544] TLB Miss, pc=0x80005558 addr=0x0 [load]`
The above error is followed by multiple TLB misses. When the debugger is opened, it looks like nothing is loaded.
When the program is loaded from a Windows native folder, PCSX2 loads it properly as expected.
When tested with a verified ELF file (wLaunchELF), the same error occurs.

### Reproduction Steps

1. Open PCSX2 on Windows.
2. Download a copy of `BOOT.ELF` from the [wLaunchELF](https://github.com/ps2homebrew/wLaunchELF/releases/tag/latest) latest dev build.
3. Place a copy in a Windows folder of choice (eg. `C:\Users\foo\Downloads`).
4. Place a copy in a WSL folder (eg. `\\wsl.localhost\Ubuntu\home\foo\Downloads`).
5. In PCSX2, select `System > Start File...` and open the Windows file created in step 3.
6. The file should load correctly.
7. Close and reopen PCSX2.
8. Select `System > Start File...` and open the WSL file created in step 4.
9. The game screen should stay black and the Log Window should reoport multiple TLBMiss errors starting with `[    8.7544] TLB Miss, pc=0x80005558 addr=0x0 [load]`.

### Expected Behavior

* When loading the WSL file in step 8, the game screen should show the same output as when loading the file in step 6.
* The log window should not show multiple TLBMiss exceptions.

### PCSX2 Revision

v2.0.2

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[pcsx2-logs.txt](https://github.com/user-attachments/files/17138301/pcsx2-logs.txt)

**Comment by Mrlinkwii** [comment]
are you building pcsx2 or using the appimage ?

**Comment by F0bes** [comment]
I can reproduce it here. I'll look into it.

**Comment by F0bes** [comment]
Okay. It's because Windows doesn't let us get away with using forward slashes for WSL paths.

Removing or stubbing the following function fixes the issue. I'll have to see if this is still required. We might get away with just having it exist for *NIX platforms.

> // This is a workaround for GHS on *NIX platforms
// Whenever a program splits directories with a backslash (ulaunchelf)
// the directory is considered non-existant

```diff
diff --git a/pcsx2/IopBios.cpp b/pcsx2/IopBios.cpp
index c27d49ccc..ceb8be82a 100644
--- a/pcsx2/IopBios.cpp
+++ b/pcsx2/IopBios.cpp
@@ -153,9 +153,9 @@ namespace R3000A
 	// the directory is considered non-existant
 	static __fi std::string clean_path(const std::string& path)
 	{
-		std::string ret = path;
-		std::replace(ret.begin(), ret.end(), '\\', '/');
-		return ret;
+		//std::string ret = path;
+	//	std::replace(ret.begin(), ret.end(), '\\', '/');
+		return path;
 	}
 
 	static int host_stat(const std::string& path, fio_stat_t* host_stats, fio_stat_flags& stat = ioman_stat)
```

**Comment by zachary-cauchi** [comment]
I see. Is there any way I can help?

**Comment by F0bes** [comment]
I have a PR with a fix here https://github.com/PCSX2/pcsx2/pull/11844
I just need to do some tests on Linux (I will later today) to see if it can be removed outright or just for Windows builds.
