### ISSUE TITLE
[BUG]: Armored Core 2: No Analog Functionality

### ISSUE THREAD

**Issue by Gamershy** [PCSX2/pcsx2#11842]
### Describe the Bug

While I've played other games, analog sticks work fine, even in Armored Core 2 - Another Age, however only with the base Armored Core 2, the analog sticks straight don't work. Pressing the sticks in works properly, but only the d-pad reads input. No settings have been changed between the two games.

### Reproduction Steps

None, just try to play the game with a PDP Xbox one controller

### Expected Behavior

Analog sticks should work.

### PCSX2 Revision

v2.1.168

### Operating System

Windows 11

### CPU

AMD Ryzen 7 6800H w/ Radeon Graphics

### GPU

NVIDIA GeForce RTX 3060 (Laptop GPU)

### GS Settings

None changed

### Emulation Settings

None changed

**Comment by TransparentBlue** [comment]
Same behavior as playing on real hardware, the analog sticks are not used besides L3 and R3 by default in AC2
