### ISSUE TITLE
[BUG]: Shadow Hearts: Covenant Fusion enemy off position

### ISSUE THREAD

**Issue by gingsz** [PCSX2/pcsx2#11840]
### Describe the Bug

When you fight a fusion enemy, sometimes the character model(or is it an animated 2d sprite probably) is totally in wrong position. Everything is in default setting and resolution. Whats strange that in most of the time it's correct in the gs dump, but i managed to make one that has the problem. In game switching to software renderer fixes it, but in the gs dump not.

### Reproduction Steps

Fight level 3 fusion enemy.

### PCSX2 Revision

2.1.164

### Operating System

Windows 11

### CPU

i7-4790

### GPU

RTX 4060

### GS Window Screenshots

![Shadow Hearts - Covenant  Disc 2 of 2 _SLUS-21044_20240922205357](https://github.com/user-attachments/assets/29cd1912-6cfc-4ada-ba31-fbfe855a31d3)
![Shadow Hearts - Covenant  Disc 2 of 2 _SLUS-21044_20240922205200](https://github.com/user-attachments/assets/6f1726c6-7deb-44e8-b265-b534c9d34569)
![Shadow Hearts - Covenant  Disc 2 of 2 _SLUS-21044_20240922205401](https://github.com/user-attachments/assets/ff41a041-5e8c-4352-848e-5ca7305e1f81)

### Logs & Dumps

[Shadow Hearts - Covenant [Disc 2 of 2]_SLUS-21044_20240922204743.gs.zip](https://github.com/user-attachments/files/17090889/Shadow.Hearts.-.Covenant.Disc.2.of.2._SLUS-21044_20240922204743.gs.zip)

**Comment by Farran666** [comment]
If it's baked into the dump then it needs a savestate.

**Comment by gingsz** [comment]
[SLUS-21044 (F3BDB2E6).03.zip](https://github.com/user-attachments/files/17090903/SLUS-21044.F3BDB2E6.03.zip)
I made one

**Comment by gingsz** [comment]
Actually I was very dumb, or not(Not sure). Somehow gamefixes doesn't applied to disc2, but I'm sure that manual fixes was disabled. (And I'm pretty sure I didn't get the autoflush=2 warning on that version) Actually "autoFlush: 2 # Makes the shadow monsters appear." in GameDB fixed this a long time ago. So this can be closed, user error (or not).
