### ISSUE TITLE
[BUG]: Error Code: 19fa44 Pilot down: Behind Enemy lines

### ISSUE THREAD

**Issue by Dvwvv** [PCSX2/pcsx2#11852]
### Describe the Bug

Can't even start the game, it show system message of aSurface, _asurface3d_init(), failed
![image](https://github.com/user-attachments/assets/43564b10-f28d-4ec7-b31b-256f489729fd)

### Reproduction Steps

Just downloaded the pilot down iso file from *removed*
and mounted the iso file and installed the game it doesn't start no matter what i do. Tried to find fixes online but can't find any.

### Expected Behavior

The game was supposed to be started without any issue as it did for most of the people.

### PCSX2 Revision

latest version

### Operating System

Windows 11

### CPU

AMD Ryzen 5 7520U with Radeon Graphics    

### GPU

AMD Radeon Graphics Processor (0x1506), Advanced Micro Devices, Inc. compatible

### GS Settings

normal settings, no advance changes or anything

### GS Window Screenshots

![image](https://github.com/user-attachments/assets/edb857c9-cbb6-44ba-aa56-ef0221f10b1d)

### Logs & Dumps

Error code
:19fa44
aSurface, _asurface3d_init(), failed

**Comment by Mrlinkwii** [comment]
We don't support piracy.
