### ISSUE TITLE
[Feature Request]: Exit PCSX2 after game closes option in interface

### ISSUE THREAD

**Issue by quantum-glitch** [PCSX2/pcsx2#11859]
### Description

A check box option to close PCSX2 on game exit built into the interface tab, just like RPCS3 has.

### Reason

I use Playnite as my game library manager and so it becomes irritating to have to manually close the app every time i want to switch titles, having this feature would be insanely beneficial.

### Examples

Example SS of RPCS3.
![Screenshot 2024-09-29 172704](https://github.com/user-attachments/assets/6d1333c1-7b7d-4ba4-88e2-2af03e1f480f)

**Comment by F0bes** [comment]
What's your definition of game exit?
When you press escape and the game closes to the game list? 

Remember, unlike the PS3, most games on the PS2 don't have a feature to return to OSDSYS. You would just reset the console without your disc if you wanted to access your memory card or change OSDSYS settings.

**Comment by quantum-glitch** [comment]
> What's your definition of game exit? When you press escape and the game closes to the game list?
> 
> Remember, unlike the PS3, most games on the PS2 don't have a feature to return to OSDSYS. You would just reset the console without your disc if you wanted to access your memory card or change OSDSYS settings.

Yes exactly like that, so when i press ESC and close the game it would also terminate the game list, which in turn would allow Playnite (my game library manager) to recognize the emulator process as no longer running, thus my game library GUI would be able to auto restore itself, allowing me to select a different title to launch.

I dont need to access the PS2 system menu or memory card, everything from launching games to opening the emulator i have running through Playnite so this wouldnt be an issue for me.

**Comment by F0bes** [comment]
I believe passing the `-batch` argument to PCSX2 is what you want. When you stop the VM it will close PCSX2.

**Comment by quantum-glitch** [comment]
> I believe passing the `-batch` argument to PCSX2 is what you want. When you stop the VM it will close PCSX2.

I've tried this argument, however when i add this argument and attempt to run a title i get error "cannot use batch mode, because no boot filename was specified" and i don't know how to resolve this.

**Comment by F0bes** [comment]
You wont be able to use the PCSX2 gamelist when using the batch argument. You will need to configure your game library manager to pass the game to PCSX2 via the commandline.

An example is as follows:
`pcsx2-qt -batch D:\\Games\PS2\Tetris_Worlds.chd`

**Comment by quantum-glitch** [comment]
> pcsx2-qt -batch

I tried this but when running a title it will open for a millisecond then instantly close as shown in the clip.

https://github.com/user-attachments/assets/47a6344a-da65-4d7b-91f2-39b416fa91fa

**Comment by F0bes** [comment]
Can you go to `Tools -> Enable File Logging` in PCSX2. Save the settings and then execute it with the launcher again. Then upload the emulog.txt file PCSX2 generates?
The log file can be found in `Tools -> Open Data Directory` and in the `logs` folder.

**Comment by quantum-glitch** [comment]
> Can you go to `Tools -> Enable File Logging` in PCSX2. Save the settings and then execute it with the launcher again. Then upload the emulog.txt file PCSX2 generates? The log file can be found in `Tools -> Open Data Directory` and in the `logs` folder.

[emulog.txt](https://github.com/user-attachments/files/17180171/emulog.txt)

**Comment by F0bes** [comment]
`ReportErrorAsync: Error: Requested filename 'E:\EMU GAMES\ps2\Enter the Matrix (USA) (v1.01).iso D:\EMUs\ps2\pcsx2-qtx64-avx2 --fullscreen --nogui D:\EMU GAMES\ps2\Enter the Matrix (USA) (v1.01).iso' does not exist.`

Somewhere you are passing arguments with double dashes. That isn't proper anymore and will lead to issues, simply replace them with single dashes. These arguments don't appear to match what is in your screenshot either. I believe you have something misconfigured.

**Comment by quantum-glitch** [comment]
> `ReportErrorAsync: Error: Requested filename 'E:\EMU GAMES\ps2\Enter the Matrix (USA) (v1.01).iso D:\EMUs\ps2\pcsx2-qtx64-avx2 --fullscreen --nogui D:\EMU GAMES\ps2\Enter the Matrix (USA) (v1.01).iso' does not exist.`
> 
> Somewhere you are passing arguments with double dashes. That isn't proper anymore and will lead to issues, simply replace them with single dashes. These arguments don't appear to match what is in your screenshot either. I believe you have something misconfigured.

I managed to figure out where i went wrong & have now rectified it, thanks for conversing with me helped a lot.

**Comment by F0bes** [comment]
Awesome, glad it was figured out.
