### ISSUE TITLE
[Feature Request]: Make a breakpoint in Scratchpad memory

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#11862]
### Description

Create a breakpoints on a Scratchpad memory.

### Reason

The Scratchpad memory address starts with 7, which cannot be debugged using breakpoints to see where the value gets written.

### Examples

Always useful in modding communites.

**Comment by F0bes** [comment]
Memory breakpoints will work for SPR. The issue is the fact that games also use the DMAC to access the SPR.
This is a duplicate of https://github.com/PCSX2/pcsx2/issues/394
