### ISSUE TITLE
[BUG]: Flatpak updates

### ISSUE THREAD

**Issue by adrianosiqueira** [PCSX2/pcsx2#11878]
### Describe the Bug

Hello, I would like to ask if there are any issue with the flatpak updates. It's been a while since the last one.

![Image](https://github.com/user-attachments/assets/847d04af-8a00-428e-be36-e976c6e1441a)
![Image](https://github.com/user-attachments/assets/9799478f-632d-41a0-8d27-75e1235589a4)

### Reproduction Steps

`flatpak update`

### Expected Behavior

It should get the latest version of the app.

### PCSX2 Revision

v2.1.168

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

KDE Neon

**Comment by F0bes** [comment]
Thanks, looking into it.

**Comment by F0bes** [comment]
Nevermind, I think my only laptop (which is used for everything) just died permanently 😃😃. If anyone wants to investigate the flatpak issues feel free.

**Comment by F0bes** [comment]
Okay, flatpak builds are fixed and the most recent version is available on Flathub again.

**Comment by adrianosiqueira** [comment]
Got it. Thank you.
