### ISSUE TITLE
[BUG]: While using Simplified Chinese GUI, PCSX2 crashes after load any game with RetroAchievements set available

### ISSUE THREAD

**Issue by djlain** [PCSX2/pcsx2#11874]
### Describe the Bug

When you set the PCSX2 Language to Simplified Chinese (简体中文 zh-CN), then turn on and login in to RetroAchievements, PCSX2 will crash (without any caution and no crash logs) when you load any game with RetroAchievements set available. Have tried on Window 10 and 11, also start from a clean setting, still got the same result. Please check this, thanks very much!

### Reproduction Steps

https://github.com/user-attachments/assets/8b631907-650f-42d7-b785-240694f37d8d

All the step mentioned above was in the video.

### Expected Behavior

Set Language to any other except Simplified Chinese (like Traditional Chinese, Japanese, English) will prevent the crash, so this BUG seems Simplified Chinese only at the moment.

### PCSX2 Revision

Nightly v2.1.182 and Stable v2.0.2

### Operating System

Windows 11

**Comment by F0bes** [comment]
Updating to the latest nightly should fix the issue.
