### ISSUE TITLE
[BUG]: Any game by Polyphony Digital crashing the emu (e.g Gran Turismo 4, i think even every game crashes)

### ISSUE THREAD

**Issue by styalos** [PCSX2/pcsx2#11879]
### Describe the Bug

Loading anything but BIOS crashes the emulator (e.g Gran Turismo 3, 4). Somehow i may have destroyed my memory card.

### Reproduction Steps

Reset system settings twice while in games mentioned ^

### Expected Behavior

I didn't expect the emu to do that...

### PCSX2 Revision

2.1.185 Nightly

### Operating System

Windows 11

### Logs & Dumps

[Crashes.zip.zip](https://github.com/user-attachments/files/17270407/Crashes.zip.zip)

**Comment by styalos** [comment]
Adding to this, i can't use any other version of PCSX2 that isn't 2.0.0..

**Comment by JordanTheToaster** [comment]
You can use our Discord or forums for support.

**Comment by styalos** [comment]
Bruh i wasted all this time and effort for that response? Waste of my time really ngl

**Comment by RedPanda4552** [comment]
> Bruh i wasted all this time and effort for that response? Waste of my time really ngl

GitHub is for technical discussion and bug tracking, not for support. Please use the Discord or forums as previously stated.
