### ISSUE TITLE
[BUG]: Cutscene slowdowns in The Getaway

### ISSUE THREAD

**Issue by Patrxgt** [PCSX2/pcsx2#11876]
### Describe the Bug

The Getaway has unlocked framerate in the cutscenes, which results in slowdowns and audio desync, because guest and host cannot keep up with the unusually high amount of frames that game tries to render.

### Reproduction Steps

1. Turn on the game.
2. Click on "New Game" in the main menu.
3. Watch the first in-game cutscene.

### Expected Behavior

Framerate in both cutscenes and gameplay is locked internally to 30 fps.

### PCSX2 Revision

v2.1.183

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 3500X 3.6 GHz (with 4.1 GHz "turbo" mode)

### GPU

NVIDIA GeForce RTX 2060 (6GB VRAM)

### GS Settings

![Image](https://github.com/user-attachments/assets/d7c1e6f2-446f-4800-b018-1581378ff038)
![Image](https://github.com/user-attachments/assets/29408905-2c56-44f3-931b-f8b36ecaa1b8)
![Image](https://github.com/user-attachments/assets/f0401e60-1afd-4d3c-b4a6-ba55756ce3e8)
![Image](https://github.com/user-attachments/assets/dc29ee55-799c-4eea-917c-df545a01a749)

### Emulation Settings

![Image](https://github.com/user-attachments/assets/7e0b273e-946f-417a-9007-384fbc32c8e8)

### GS Window Screenshots

![Image](https://github.com/user-attachments/assets/f787ff7b-316a-4d5a-8ab1-a44a497d947f)
![Image](https://github.com/user-attachments/assets/13d3131f-af7d-470d-b983-5739de24a522)

**Comment by Farran666** [comment]
Same issue as #3603

**Comment by JordanTheToaster** [comment]
> Same issue as [#3603](https://github.com/PCSX2/pcsx2/issues/3603)

This is not the same issue.

**Comment by JordanTheToaster** [comment]
The game in cutscenes is just incredibly hard to run this isn't really a bug at all.

**Comment by Patrxgt** [comment]
> The game in cutscenes is just incredibly hard to run this isn't really a bug at all.

xD? All of the cutscenes run in 30 FPS on the original PS2, so it isn't an expected behavior. Also, closing an issue before I had a chance to reply is just childish and shows that you aren't interested in fixing inconsistencies of the emulator.

**Comment by JordanTheToaster** [comment]
> isn't an expected behavior.

Some games do run faster on PCSX2 this isn't a "bug" or "inconsistency" it's just the result of us not wanting to make emulation overly heavy by emulating things like GS back pressure which would slow down games that do run fast. The game otherwise runs fine if you have the hardware for it as you can see here.

![Image](https://github.com/user-attachments/assets/88f12495-1f5d-4d11-b826-7a963d0def8f)

**Comment by Patrxgt** [comment]
Still, there should be an option to internally lock the framerate in problematic games like this one. Not everybody has RTX 2070 SUPER like you do and can struggle with running games without slowdowns and sound stretching.

**Comment by JordanTheToaster** [comment]
> Still, there should be an option to internally lock the framerate in problematic games like this one. Not everybody has RTX 2070 SUPER like you do and can struggle with running games without slowdowns and sound stretching.

It's a CPU limit not a GPU limit and the 5600x is not exactly "top end" anymore.

**Comment by Patrxgt** [comment]
That doesn't answer my request for internal frame limiter one bit.

**Comment by JordanTheToaster** [comment]
> That doesn't answer my request for internal frame limiter one bit.

Because as far as I know that isn't possible.

**Comment by F0bes** [comment]
If the game isn't relying on VSYNC clocks and is slamming the GS with data there isn't much we can do, we're at too low of an emulation level.
It might be relying on backpressure which we don't emulate. There is an experimental branch [dma_gifbackpressure](https://github.com/PCSX2/pcsx2/tree/dma_gifbackpressure) that kind of guestimates some backpressure. You can see if that helps.
