### ISSUE TITLE
[BUG]: ntsc can run pal games but pal bios can't run ntsc games when fast boot is disabled.

### ISSUE THREAD

**Issue by tails101** [PCSX2/pcsx2#11872]
### Describe the Bug

this is pretty much what the title say.
it only works one way when fast boot is disabled.
the game does not boot and the emulator hang in the firmware menu.
everything works correctly when fast boot is disabled.
there is another issue when fast boot is disabled.
due to the bios miss match the ps2 logo is corrupted.

i like to have my console boot screen when a game is emulated

### Reproduction Steps

set a pal bios
disable fast boot
run a game from another region.

### Expected Behavior

well it should work.
a solution would be to have 3 bios slot.
one for each region or the emulator need the ability to switch bios if needed by itself.
this would fix the corrupted ps2 logo
and it will be less hacky than the current implementation of the region free.

### PCSX2 Revision

2.0.2

### Operating System

Windows 11

**Comment by tails101** [comment]
And the scrambled PS2 logo fixing then?....
This is intended?

[https://www.reddit.com/r/PCSX2/comments/r8skl6/i_think_the_ps2_logo_doesnt_appears_correctly_on/](url)

**Comment by F0bes** [comment]
We don't implement any of the hardware region checks. The software region check is emulated normally **unless you fast boot.**
To clarify;
On **full boot** we try to match a normal console without any of the hardware region checks.
On **fast boot** we bypass the software region check. So I suppose the target would be a region free console for fast boot.

Hope that answers your question.

**Comment by tails101** [comment]
Yes this is perfect.
Thanks for the answer.
