### ISSUE TITLE
[Feature Request]: add dinput Force Feedback support

### ISSUE THREAD

**Issue by Sasha349** [PCSX2/pcsx2#11900]
### Description

After moving to SDL Force feedback in GT4, Enthusia,etc. may randomly disabling for 10-15 seconds. Think this is current SDL issue. There a big count of issues which describe wheel FFB loss. Im try to add more logging to current version of emulator locally and SDL not respond any errors. Last normal working FFB in pcsx2-1.7.3727 use Dinput FFB. Test with Moza R12.

### Reason

It will allow to use default Dinput FFB.

### Examples

https://github.com/PCSX2/pcsx2/issues/3926
https://github.com/PCSX2/pcsx2/issues/11735
https://github.com/PCSX2/pcsx2/issues/11128
https://github.com/PCSX2/pcsx2/issues/11833

**Comment by mirh** [comment]
I think #11906 and #11915 are actually closer to your ballgame.
Though I suppose #7196 really did set up a pretty simplified version of the older driver (I see no dinput `CreateEffect` calls in the code) so the feature request could still be legit.

**Comment by Sasha349** [comment]
Seems in current branch dinput FFB removed. in older version it stored in pcsx2\USB\usb-pad\dx\dinput.cpp

**Comment by F0bes** [comment]
There were FFB fixes merged recently. Have these fixed your issues with FFB dropping out on SDL?

**Comment by Sasha349** [comment]
> There were FFB fixes merged recently. Have these fixed your issues with FFB dropping out on SDL?

Test today around 2h using Moza R12 and no FFB drop at this time.

**Comment by F0bes** [comment]
Awesome to hear. Closing as completed.
