### ISSUE TITLE
(Hosting request) Create a Radicle backup and mirror to protect your development

### ISSUE THREAD

**Issue by hardBSDk** [PCSX2/pcsx2#11921]
### Description

[Radicle](https://radicle.xyz/) is a platform for peer-to-peer Git repositories, your repository works like a torrent where anyone can be a seeder of your code.

This will increase the download speed, add a backup and protect the project from GitHub problems.

### Reason

Above.

### Examples

None.

**Comment by F0bes** [comment]
This wont be in our roadmap. More infrastructure equals more costs. If it continues to grow and become somewhat of a standard then adoption may be considered. But this is the first time I've heard about it.
