### ISSUE TITLE
[BUG]: The Great Escape - Glitched Textures and Disappearing Objects While Moving the Camera

### ISSUE THREAD

**Issue by LtFrankDrebin** [PCSX2/pcsx2#11930]
### Describe the Bug

There are glitched black textures that can be seen on the borders of the screen in the outdoor areas of the second level (and possibly in the others). The world objects disappear and reappear on the screen while moving the camera.

### Reproduction Steps

Load the second level and go to the camp gates. You'll notice black triangular textures appearing on the screen while moving the camera. Then enter the guard hut to the left of the gates and move the camera around. You'll notice that various objects in the hut (books, utensils, telephones etc) disappear and reappear on the screen as you're moving the camera. I've attached a link to the video showcasing these two bugs:

https://youtu.be/O3w-afgRZ08

### Expected Behavior

The outdoor and indoor areas should be rendered correctly, without glitched black textures on the borders of the screen and disappearing objects.

### PCSX2 Revision

2.1.214

### Operating System

Windows 10 (64bit)

### CPU

i9-9900KF

### GPU

RTX 2080 Ti

### GS Settings

![Image](https://github.com/user-attachments/assets/751175ff-756d-4933-93de-a05a51b98e77)
![Image](https://github.com/user-attachments/assets/0322e01b-bb2d-490d-bbae-559d37a61760)
![Image](https://github.com/user-attachments/assets/4283053f-de9c-441e-9d6d-038f5a78aad3)
![Image](https://github.com/user-attachments/assets/096fcc1f-14f2-4f21-84fc-3581e5ff6df4)
![Image](https://github.com/user-attachments/assets/c3bbbfbe-1308-4f76-9780-b2613cf47cf6)

### Emulation Settings

Any (these glitches occur at default settings and in software mode as well).

### GS Window Screenshots

Glitched black textures can be seen on the borders of the screen.

![Image](https://github.com/user-attachments/assets/0fd3a9de-4bfd-43d2-b571-3f545d790424)
![Image](https://github.com/user-attachments/assets/524e1620-46eb-4523-902b-76ebb19e546d)
![Image](https://github.com/user-attachments/assets/2fdbbba9-516e-4a0c-983c-214557ce56e9)

World objects disappear and reappear while moving the camera.

Two cups are standing on the box to the right.

![Image](https://github.com/user-attachments/assets/5d5262a9-41b7-4375-8a66-b19b5084d7dd)

I moved the camera, now they are gone.

![Image](https://github.com/user-attachments/assets/285ed1d0-1750-4d61-b163-38d41bc21052)

A cup, a book and a bowl can be seen on the bench.

![Image](https://github.com/user-attachments/assets/1b2ac0de-a168-42c7-b740-0006e1b9af63)

The camera moved, and the three objects disappeared.

![Image](https://github.com/user-attachments/assets/8d3cf979-a8d0-4369-b77b-40dd8ee13642)

Pay attention to the objects on the table and a pile of books on the top of the brown drawer behind a sleeping guard.

![Image](https://github.com/user-attachments/assets/27d09181-52c9-4140-bdea-07f6bd5c2533)

I moved the camera, everything is gone now.

![Image](https://github.com/user-attachments/assets/f6c931e4-b9be-4d61-b402-fd682cfd9b97)

### Logs & Dumps

[Glitched Black Texture On The Left 1.zip](https://github.com/user-attachments/files/17450519/Glitched.Black.Texture.On.The.Left.1.zip)
[Glitched Black Texture On The Left 2.zip](https://github.com/user-attachments/files/17450520/Glitched.Black.Texture.On.The.Left.2.zip)
[Glitched Black Texture On The Right 1.zip](https://github.com/user-attachments/files/17450521/Glitched.Black.Texture.On.The.Right.1.zip)
[1. Disappearing Objects 1 - BEFORE.zip](https://github.com/user-attachments/files/17450524/1.Disappearing.Objects.1.-.BEFORE.zip)
[2. Disappearing Objects 1 - AFTER.zip](https://github.com/user-attachments/files/17450523/2.Disappearing.Objects.1.-.AFTER.zip)
[3. Disappearing Objects 2 - BEFORE.zip](https://github.com/user-attachments/files/17450525/3.Disappearing.Objects.2.-.BEFORE.zip)
[4. Disappearing Objects 2 - AFTER.zip](https://github.com/user-attachments/files/17450526/4.Disappearing.Objects.2.-.AFTER.zip)
[5. Disappearing Objects 3 - BEFORE.zip](https://github.com/user-attachments/files/17450528/5.Disappearing.Objects.3.-.BEFORE.zip)
[6. Disappearing Objects 3 - AFTER.zip](https://github.com/user-attachments/files/17450527/6.Disappearing.Objects.3.-.AFTER.zip)
[Memory Card Saves for Testing.zip](https://github.com/user-attachments/files/17450604/Memory.Card.Saves.for.Testing.zip)

**Comment by JordanTheToaster** [comment]
It's a broken widescreen patch you can use the discord or forums for support in future.

**Comment by ke5koB** [comment]
@LtFrankDrebin 
Fixed patch. Please check. I only tested it at the very beginning of the game.
[SLUS-20670_D600925B.zip](https://github.com/user-attachments/files/17491661/SLUS-20670_D600925B.zip)

**Comment by LtFrankDrebin** [comment]
Thank you for the fix, @ke5koB!  I've just loaded my save near the guard hut, and there are no more black tearing at the borders of the screen, and the items from the hut stay in one place, they no longer pop in and out depending on the camera position. I'm currently playing through the game and will report if I see anything, but the bug appears to have been fixed. Could you notify the developers so that they incorporate your fix in the next update?

**Comment by ke5koB** [comment]
You're welcome! I think the developers will get a notification about new messages and will add a fixed patch themselves. If not, you can open a new issue [here](https://github.com/PCSX2/pcsx2_patches) with a request to update the patch.

**Comment by LtFrankDrebin** [comment]
@ke5koB: Oops, it seems I spoke too soon. Upon aditional inspection, it seems two cups in the far corner of the hut are still affected by this bug: https://youtu.be/_k-P9wrtySU 

I added my save in the hut for testing (load "Winter Breakout" from Memory Card 1).

[Save.zip](https://github.com/user-attachments/files/17506044/Save.zip)

**Comment by LtFrankDrebin** [comment]
Also the text in the notebook where objectives are listed is misaligned:(

![Image](https://github.com/user-attachments/assets/3260f3a8-9425-4c90-9d13-50a0696c245a)
![Image](https://github.com/user-attachments/assets/67cfad96-b1d8-4c71-81f7-2755986eb802)

**Comment by ke5koB** [comment]
The disappearing cups in this case are a standard optimization of the game. It has nothing to do with Pcsx2 or the widescreen patch. Without the patch you will see the same thing.
I found how to fix the objectives screen, but unfortunately it also broke the interaction with objects. So it's better to leave everything as is.

**Comment by LtFrankDrebin** [comment]
Could you post your pnach file on Discord and PCSX2 forum, please, and write what measures you've already attempted? Maybe other members will be able to come up with a fix.

**Comment by ke5koB** [comment]
Here you go, but I'm sure it's useless. [SLUS-20670_D600925B.zip](https://github.com/user-attachments/files/17508722/SLUS-20670_D600925B.zip)

**Comment by ke5koB** [comment]
Sorry, I commented out a couple of lines and forgot about it. Objectives screen should work like before now.[SLUS-20670_D600925B.zip](https://github.com/user-attachments/files/17513069/SLUS-20670_D600925B.zip)

**Comment by LtFrankDrebin** [comment]
@ke5koB: Do you use Discord, **ke5koB**? Could you help with a widescreen fix for the PC version as well, please? We've run into the same inventory bugs as last year and could use your assistance.

Here's an invite link to our the Great Escape channel:https://discord.gg/eBVB5FuC
