### ISSUE TITLE
Add kaillera netplay support

### ISSUE THREAD

**Issue by mxsymeg** [PCSX2/pcsx2#11949]
### Description

https://kaillerareborn.github.io/

### Reason

Hopefully support for kaillera netplay can be added in subsequent releases!

### Examples

![Image](https://github.com/user-attachments/assets/7f29b758-5525-42d1-bb26-4afcc80fe6d3)

**Comment by F0bes** [comment]
Someone is free to implement this but I don't believe it's enough of a priority to keep on our tracker.
