### ISSUE TITLE
[Feature Request]: Global/Per game Hotkeys  (Mainly for savestate)

### ISSUE THREAD

**Issue by MilitantTurtle** [PCSX2/pcsx2#11945]
### Description

Would really like per game hotkey settings (Mainly for controller users), This would allow me to set save/load state buttons per game, and not have it affect other games.

### Reason

For example on Need For Speed Underground L3/R3 are unused, so having savestate buttons assigned to them make it really easy.
Having one set of button combos is also not reliably consistent on games because of differing control schemes and/or fast paced games (again Need for Speed Underground is a good example), as well as already having scripts set up for button combos in other programs (autohotkey/xpadder).

### Examples

I'm not sure if this exists in other software, but ideally it would be the same structure as other settings, where global setting is in effect unless overwritten by per game settings.

**Comment by AmyRoxwell** [comment]
> ### Description
> 
> Would really like per game hotkey settings (Mainly for controller users), This would allow me to set save/load state buttons per game, and not have it affect other games.
> ### Reason
> 
> For example on Need For Speed Underground L3/R3 are unused, so having savestate buttons assigned to them make it really easy. Having one set of button combos is also not reliably consistent on games because of differing control schemes and/or fast paced games (again Need for Speed Underground is a good example), as well as already having scripts set up for button combos in other programs (autohotkey/xpadder).
> ### Examples
> 
> I'm not sure if this exists in other software, but ideally it would be the same structure as other settings, where global setting is in effect unless overwritten by per game settings.

This is implemented on the current controller system via profiles, when you make a new profile it would ask you if you want to copy the current configuration you using:

![Image](https://github.com/user-attachments/assets/18e901d7-9085-425f-872d-9c794ce4b08e)

Then, you can enable this option to have custom hotkeys on that profile, making a completely blank hotkey file for that profile:

 ![Image](https://github.com/user-attachments/assets/e60eb8ae-d627-4b38-b2b7-5b3446c0c8f3)

Then, you can right click a game on your PCSX2 library, click game properties and choose that profile!

![Image](https://github.com/user-attachments/assets/cad5168f-1e50-491a-9819-3950c59d34cf)

**Comment by MilitantTurtle** [comment]
@AmyRoxwell Thank you, I was right clicking and looking in game properties, I didn't expect it to be more complicated.
 I haven't tried it yet but I'll close the ticket because I believe you lol.

**Comment by AmyRoxwell** [comment]
> [@AmyRoxwell](https://github.com/AmyRoxwell) Thank you, I was right clicking and looking in game properties, I didn't expect it to be more complicated. I haven't tried it yet but I'll close the ticket because I believe you lol.

If you would prefer, we have a discord where we could assist you with any questions you may have!
