### ISSUE TITLE
[BUG]: Invalid operator?

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#11964]
### Describe the Bug

Whenever I try to set up a condition in a breakpoint it sas "Invalid operator".
What are possible conditions to use?
For example, if I wanted it to break only when the byte size at the address is 5?

### Reproduction Steps

1. Open the debugger
2. Add a breakpoint and write into condition

### PCSX2 Revision

Latest Nightly

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
I'm not entirely sure what you're trying to do. If you can give me an example I'd by happy to help.

Overall the conditionals are pretty straightforward. I've put some examples below.

`$t0 == 0x00`
`($t0 <= 0x1123) && ($s0 & 0x1)`
`[0x480031] == 0x00` (memory address 0x480031 is 0)

Introduced in https://github.com/PCSX2/pcsx2/pull/7870 are some extra references.

You can do neat things like so
`[load]==0x00`
If you put this conditional on a **load** instruction it'll only break if the value loaded (the address is `load`) is 0.

**Comment by YukiXXL** [comment]
> I'm not entirely sure what you're trying to do. If you can give me an example I'd be happy to help.

I am trying to break when 0x1 gets written at a certain address. What I need to enable and what needs to be written in the Condition?

**Comment by F0bes** [comment]
Set a write memory breakpoint at that address and in the condition put `[store] == 1`
