### ISSUE TITLE
[BUG]: Linux AppImage is not packaged properly

### ISSUE THREAD

**Issue by rumly111** [PCSX2/pcsx2#11975]
### Describe the Bug

When I run the appimage:

```
~/Applications> ./pcsx2-v2.2.0-linux-appimage-x64-Qt_7b94af669937ba2e0e7fb3e5a7bff3a6.AppImage 
execv error: No such file or directory
```

I get an error `execv error: No such file or directory`

The AppImage is not packaged properly I think. The previous stable (2.0.2) AppImage works fine.

### Reproduction Steps

```
cd ~/Applications
./pcsx2-v2.2.0-linux-appimage-x64-Qt_7b94af669937ba2e0e7fb3e5a7bff3a6.AppImage
```

### PCSX2 Revision

2.2.0

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

**Comment by kamfretoz** [comment]
Uninstall AppImageLauncher, this is a known issue and is out of our control.

See: https://github.com/PCSX2/pcsx2/pull/11667#issuecomment-2274205427
