### ISSUE TITLE
[Feature Request]: User-made subtitles for games that don't have them

### ISSUE THREAD

**Issue by LtFrankDrebin** [PCSX2/pcsx2#11983]
### Description

Is it possible for the PCSX2 developers to add support for user-made subtitles? These subtitles should be in an easy-to-edit text format and activated just like current pnach cheats and widescreen patches. Members of the community themselves will provide texts and timecodes for their subtitles, and the emulator should be able to process those text files and display them on screen. Subtitles for both speech with fixed timings (like in cutscenes) and ambient phrases uttered by NPCs at random should be supported by the emulator. 

### Reason

Quite a few PS2 games (like the X-Files: Resist or Serve, the Great Escape etc) do not have any subtitles, which makes playing them very inconvenient for people with bad hearing. This feature will make PS2 games more accessible for people with hearing disability.

### Examples

One notable example of subtitle support being added to very old games decades after they were released is community patches for Dark Engine games: [SS2 Community Patch](https://www.systemshock.org/index.php?topic=7116.0) for System Shock 2, [TFix](https://www.ttlg.com/forums/showthread.php?t=134733) and [T2Fix](https://www.ttlg.com/forums/showthread.php?t=149669) for Thief 1 & 2, which added subtitle support not only for the base games, but also for fan missions created by the community.

**Comment by F0bes** [comment]
This is out of scope for PCSX2. We don't even have a great heuristic when detecting when an FMV begins and ends. I don't even want to think of how we would figure out _what_ FMV is playing. I'd expect this to be more doable on Dolphin, though, I'm not sure of the exact details regarding the Wii or Gamecube FMV pipeline, so it's just speculation.
