### ISSUE TITLE
[BUG]: Pause icon no longer appears in the OSD, hides OSD instead

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2#11981]
### Describe the Bug

When using the pause hotkey (default spacebar) while the OSD is enabled, it no longer shows the pause icon, instead the whole OSD is hidden. The icon used to show along with the fast foward, turbo, and slow motion icons in the same place at the top right corner, those icons were relocated at some point in the OSD and now the pause icon is gone.

### Reproduction Steps

Enable the `Show Indicators` option at least in OSD settings, press the pause hotkey and watch the OSD go poof.

### Expected Behavior

There should be an icon to let the user know they paused their own game and it isnt frozen or broken.

### PCSX2 Revision

v2.3.5

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
it broke in  #11657
