### ISSUE TITLE
[BUG]: it fail on up and down with joystick setting

### ISSUE THREAD

**Issue by waldolin** [PCSX2/pcsx2#11989]
### Describe the Bug

PCSX2 v2.2.0 
it failed on "up and down" with  joystick setting
controller port 1
I add joystick all detected
but when I add up and down, it will conflict with up and down very faster

### Reproduction Steps

controller port 1
I add joystick all detected
but when I add up and down, it will conflict with up and down very faster

### Expected Behavior

use  joystick 

### PCSX2 Revision

2.2.0 

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
Please use the Discord or forums for support.
