### ISSUE TITLE
[BUG]: Tales of Symphonia (SLPS-25400) - Black Screen No Crash

### ISSUE THREAD

**Issue by reianayami** [PCSX2/pcsx2#11987]
### Describe the Bug

Good afternoon, in the Japanese version of Tales of Symphonia there is a issue where about halfway through the game, the screen goes black and just sits there. There is no app crash, the FPS marker is still moving without issue, the actual scene has sound which does stop, but after watching the exact moment in happens on a english version playthrough (at 6:09 https://www.youtube.com/watch?app=desktop&v=LVOPYYGdfHg) the music does indeed stop. So it seems like its all normal behavior except for obviously not progressing.

### Reproduction Steps

Happens whenever the dialogue is finished when they capture 2 characters for lying about being full elves. 

### Expected Behavior

The game should continue as normal. Due to this the game is currently unplayable. 

### PCSX2 Revision

v2.2.0

### Operating System

Windows 11

### CPU

i5-12500

### GPU

GTX 3050ti

### Emulation Settings

All renders at native resolution.

### GS Window Screenshots

![Image](https://github.com/user-attachments/assets/7597293c-2ead-4497-816d-72d67895de2d)

### Logs & Dumps

[Tales of Symphonia_SLPS-25400_20241108172406.gs.zip](https://github.com/user-attachments/files/17684709/Tales.of.Symphonia_SLPS-25400_20241108172406.gs.zip)

**Comment by JordanTheToaster** [comment]
Please use the Discord or forums for support.
