### ISSUE TITLE
GameIndex.dbf new entry

### ISSUE THREAD

**Issue by hoholee12** [PCSX2/pcsx2#1199]
Serial = SLUS-21260
Name   = Ed, Edd, 'n Eddy - The Mis-Edventures
Region = NTSC-U
Compat = 5

setting eeRoundMode = 2 fixes the missing text.

**Comment by ssakash** [comment]
why not make a pull request ?

**Comment by hoholee12** [comment]
@ssakash 
https://github.com/hoholee12/pcsx2/commit/30e8c27312f4c116f43a04aeb17857a851298653
