### ISSUE TITLE
[BUG]: SLPM-62482 Pachinko Slot Tokodensho - Inoki Festival Graphic Glitch

### ISSUE THREAD

**Issue by nassau-tk** [PCSX2/pcsx2#12004]
### Describe the Bug

Software Rendering will draw the graphic correctly.

But, Other rendering will happen glitch same position.

[Software rendering]
![Image](https://github.com/user-attachments/assets/f297f764-ec2e-401c-a3b4-f5fdcdf50dad)

[Vulkan and other HW rendering]
![Image](https://github.com/user-attachments/assets/06ce4dce-3099-4230-aa02-29d1c34d8003)

### Reproduction Steps

Set rendering Vulkan/OpneGL/D3D any OK.
It will happen in the game screen on the right side.

### Expected Behavior

We wish drawing the graphic correctly.

### PCSX2 Revision

v2.3.14

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800X

### GPU

GeForce RTX3060

### Logs & Dumps

[Pachinko Slot Tokodensho - Inoki Festival_SLPM-62482_20241113183932_SWrendering.zip](https://github.com/user-attachments/files/17730142/Pachinko.Slot.Tokodensho.-.Inoki.Festival_SLPM-62482_20241113183932_SWrendering.zip)

[Pachinko Slot Tokodensho - Inoki Festival_SLPM-62482_20241113183948_Vulkan.zip](https://github.com/user-attachments/files/17730144/Pachinko.Slot.Tokodensho.-.Inoki.Festival_SLPM-62482_20241113183948_Vulkan.zip)

**Comment by Farran666** [comment]
I've tried it on 1.7.3628 and got the same result. It is unlikely to be a regression
 ![Image](https://github.com/user-attachments/assets/5212dff3-77ce-4205-96b7-37e9006d9716)

**Comment by nassau-tk** [comment]
What!?
Great!!
