### ISSUE TITLE
[BUG]: Baldur's Gate: Dark Alliance

### ISSUE THREAD

**Issue by Cibomatto2002** [PCSX2/pcsx2#12008]
### Describe the Bug

When saving with a save state and loading it it will corrupt saving in game when you save in the game.

### Reproduction Steps

save with save state then reload it next try to save to the memory card you will see it says game is corrupt.

### Expected Behavior

Save without saving saying save game is corrupted.

### PCSX2 Revision

2.3.16

### Operating System

Windows 11

**Comment by RedPanda4552** [comment]
Not a bug, this is consistent behavior with using savestates to try and rewind a game behind the current memory card status. Please use the Discord or forums for support.
