### ISSUE TITLE
[BUG]: Linux builds failing

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#12018]
### Describe the Bug

Linux builds are failing with Vulkan-related errors such as:
```
/home/testing/Desktop/pcsx2/pcsx2/pcsx2/GS/Renderers/Vulkan/VKShaderCache.cpp: At global scope:
/home/testing/Desktop/pcsx2/pcsx2/pcsx2/GS/Renderers/Vulkan/VKShaderCache.cpp:111:11: error: ‘::shaderc_compilation_status_to_string’ has not been declared; did you mean ‘shaderc_compilation_status_success’?
  111 |         X(shaderc_compilation_status_to_string) \
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reproduction Steps

Ensure all dependencies are up to date, and follow the linux build procedure specified [here](https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux#dependencies).

### Expected Behavior

Working binary is produced.

### PCSX2 Revision

a507964f3390e2a6c1e446cc9fda84f3b94ee931

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 22 (Ubuntu 24.04 base) / kernel 6.8

### Logs & Dumps

[build.log](https://github.com/user-attachments/files/17791832/build.log)

Note: Last known working build was produced with commit 185b85f86aa0d4a38b6c032fd317627120ecf589.  I can bisect if necessary.

**Comment by F0bes** [comment]
We currently depend on a patched shaderc. You can look at how we do so by our Linux GitHub actions scripts.

**Comment by Shoegzer** [comment]
Ah okay, thanks.  I think you're referring to [this](https://github.com/PCSX2/pcsx2/blob/256a946f961814bdcb0a64a2f6243ee6a1a017f7/.github/workflows/scripts/linux/build-dependencies-qt.sh#L248)?  If so, this patch is executed with `build-dependencies-qt.sh`, which I'm already doing as part of the build process.  What am I missing?

**Comment by Shoegzer** [comment]
Hey thanks. I had set CMAKE_PREFIX_PATH to include deps, though merging #11292 did fix the issue and it compiles now.

**Comment by weirdbeardgame** [comment]
What distro?

**Comment by Shoegzer** [comment]
Linux Mint 22 as noted above.
