### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by Emironparas** [PCSX2/pcsx2#12013]
### Describe the Bug

I am experiencing input issues specifically with the game Crash Tag Team Racing (USA) on PCSX2 2.3.17 (Nightly Build). The game responds to the default keyboard controls, but if I try to rebind the keyboard keys or switch to a controller, no inputs are registered in the game.

This issue only occurs with Crash Tag Team Racing (USA). Other games work flawlessly, and their controls can be reconfigured without any problems. I’ve tried multiple troubleshooting methods, but the issue persists for this particular game.

This problem didn't appear before pcsx2 v2.

### Reproduction Steps

.

### PCSX2 Revision

2.3.17 and the stable version

### Operating System

macOS 14 (Sonoma)

**Comment by F0bes** [comment]
Please visit our forums or discord for support.
