### ISSUE TITLE
[BUG]: True Crime: New York City: Weird Draw Distance or lighting bug when running at higher internal resolutions

### ISSUE THREAD

**Issue by rrrcabral** [PCSX2/pcsx2#12010]
### Describe the Bug

I know it's in the rules not to report upscaling, but since this isn't listed as a known issue on the Wiki, I'm reporting it here in case it's not known, and someone adds it to the Wiki.
But there is this problem of a blinking black "wall" appearing on the horizon while walking on the streets,
but only if you raise the internal resolution to any value above the native one. There is no such problem on the native one.

screens: https://imgur.com/a/errors-y69m87i

### Reproduction Steps

I don't even need to say the hardware/configurations on which this happens because besides me I saw about 3 other people on forums/reddit reporting the same problem, but in case this is useful:
3x native upscaled. aspect ratio: 16x9, game running in ingame native widescreen and native progressive-scan enabled.

and someone else's system that had the same problem on reddit is:
"CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
Graphics: Intel HD Graphics 630 & NVIDIA GeForce GTX 1050
Memory: 8GB Ram
OS: Windows 10 Home
PCXS2 Version 2.0.2 Stable
Only changes really are the aspect ratio and Internal Resolution is 3x Native.
her description: the distance seems to be darker or just black. it only seems to effect the roads, you can see a sharp line where the roads go near black"

### PCSX2 Revision

v2.3.17

### Operating System

Windows 11

### CPU

AMD Ryzen 5 1600AF

### GPU

Nvidia GTX 960 2GB,

**Comment by JordanTheToaster** [comment]
You can add it to the wiki yourself.

**Comment by ca5dx** [comment]
I'm sure if this was some pedo anime game they'd get right on it

**Comment by rrrcabral** [comment]
I added it to the Wiki

**Comment by germansassone** [comment]
I solve that with this configs, look at the pictures the part circled in red

![Image](https://github.com/user-attachments/assets/6ab67466-aeb0-4d90-a6c8-abf7a1cf21b3)

![Image](https://github.com/user-attachments/assets/df4d64c9-19d8-450b-af51-33bb2f170aa5)

![Image](https://github.com/user-attachments/assets/ce20f9ad-a49f-456b-9e7d-96e619083529)

![Image](https://github.com/user-attachments/assets/995059fa-99f2-456a-9466-4a8ef2f10cc8)

I started playing all the missions and until now, there is no mayor issue, I will report back when I finish the game 100%

**Comment by RFD960** [comment]
Thank you very much for your post, @germansassone. There only seems to be minor bugs with the pavement/road textures flickering a texture sheet rarely, and the rain pouring from the sky not rendering (but snow does, weirdly enough) and the sun flare/corona looks a bit odd. Would you happen to know if there are ways to fix these at the current time?

**Comment by germansassone** [comment]
> Thank you very much for your post, [@germansassone](https://github.com/germansassone). With your settings, in HW mode there only seems to be minor bugs with the pavement/road textures flickering a texture sheet rarely, and the rain pouring from the sky not rendering (but snow does, weirdly enough) and the sun flare/corona looks a bit odd. Would you happen to know if there are ways to fix these at the current time?

The sun will work almost perfect with this configs, try them out, I forgot to post that I could finish the game, no big issues that worth mentioning

![Image](https://github.com/user-attachments/assets/ea0e1fdf-cadf-4505-821a-d4a6f9726f03)

![Image](https://github.com/user-attachments/assets/9e94be13-fe9a-4a7c-a02f-087b086f758a)

![Image](https://github.com/user-attachments/assets/383a92e8-7ecb-4f18-a286-cb440f5e477a)

![Image](https://github.com/user-attachments/assets/1ec4196c-b1b6-4ad7-a4a6-38c9f4ff95ad)

I have to clirify, I don't know how to solve the **rain** issue, I tried many combinations of configs, none of them works. That's all.

**Comment by RFD960** [comment]
Excellent, excellent. Thank you for your speedy response.

**Comment by germansassone** [comment]
Rain render fixed

<img width="892" height="594" alt="Image" src="https://github.com/user-attachments/assets/fe69cf56-98ad-473c-b8bc-41b5844b6933" />

source: https://github.com/PCSX2/pcsx2/pull/13681
