### ISSUE TITLE
[BUG]: Monster House - Graphic Issue

### ISSUE THREAD

**Issue by germansassone** [PCSX2/pcsx2#12029]
### Describe the Bug

The game has graphical issues in some levels

### Reproduction Steps

Level "Ground Floor" - Savegame at 13% percent.

### Expected Behavior

The video shows graphical issues

### PCSX2 Revision

PCSX2 2.3.25

### Operating System

Windows 10 (64bit)

### CPU

Intel 10400

### GPU

Geforce 1060 6gb Edition EVGA

### GS Settings

I don't know

### Emulation Settings

Hardware and Software emulation equally liable
Default

### GS Window Screenshots

https://youtu.be/UnRAgkVPLT0

### Logs & Dumps

I don't know how to do It. If you explain to me how to do It, then I will do It. I did not understand the guide.

**Comment by JordanTheToaster** [comment]
Please use the Discord or forums for support.
