### ISSUE TITLE
[BUG]: WRC 3 Car shadow bug in Turkey stage

### ISSUE THREAD

**Issue by harrylarry4** [PCSX2/pcsx2#12044]
### Describe the Bug

Problem only with d3d11 and d3d12 renderer .
In the Turkey stage the car shadow covers with cars own under reflection.But other renderers looks fine.

### Reproduction Steps

Run time trial and select Turkey with any car.

### Expected Behavior

Shadow must look like software rendered version.

### PCSX2 Revision

2.3.35

### Operating System

Windows 10 (64bit)

### CPU

i3-10105f

### GPU

GT-730

### Logs & Dumps

[sw.zip](https://github.com/user-attachments/files/17947143/sw.zip)
[dx11and12.zip](https://github.com/user-attachments/files/17947170/dx11and12.zip)

**Comment by Mrlinkwii** [comment]
i suspect this will need high blending on dx11/12 ( since dx11/12 is bad at blending)

**Comment by JordanTheToaster** [comment]
This is working as intended DX11 and DX12 are both less accurate than OpenGL and Vulkan and won't render some games properly as a result.
