### ISSUE TITLE
Compatibility with older glibc

### ISSUE THREAD

**Issue by lucasmz1** [PCSX2/pcsx2#12045]
### Description

could you please make an appimage for old glibc, I'm on Slacware 15, you could use the ubuntu 20.04 as base for the build.

### Reason

don't run on slackware 15

### Examples

all you gonna need is to compile libdecor

**Comment by JordanTheToaster** [comment]
We do not support outdated Ubuntu versions please update to at least 22.04 or use an older version of PCSX2.

**Comment by Samueru-sama** [comment]
> We do not support outdated Ubuntu versions please update to at least 22.04 or use an older version of PCSX2.

Hey you don't have to support older distros, just bundle everything in the AppImage and they will work on any distro, **even musl ones**.

See [this](https://github.com/ivan-hc/AM/discussions/1120) for examples and I also have this appimage of [ppsspp](https://github.com/pkgforge-dev/PPSSPP-AppImage) where I bundle everything and it works on any distro.
