### ISSUE TITLE
[BUG]: Call of Cthulhu: Destiny's End - cutscene to game transition crashes emulator

### ISSUE THREAD

**Issue by darkfalzx** [PCSX2/pcsx2#12057]
### Describe the Bug

This bug is for the incomplete 2005 E3 build of Call of Cthulhu: Destiny's End from hiddenpalace.
Emulator crashes at the end of each of in-engine cutscenes. If a cutscene is skipped by pressing START, crash is avoided.

The last emulator version tested is v2.3.40. This crash occurs in every version of PCSX2 going back to v1.4.0, and appears to happen regardless of emulation or rendering settings.

### Reproduction Steps

Start the game, and select Start Demo in the main menu.
Walk toward the overturned pickup truck, and press X when prompted.
A cutscene will play.
Just as the cutscene ends, and the control is about to be relinquished back to the player, the emulator window closes.

### Expected Behavior

The demo is fully playable, and stable on PS2 hardware.

### PCSX2 Revision

v2.3.40

### Operating System

Windows 10 (64bit)

### CPU

i9 10850k

### GPU

RTX 3080 10GB

### GS Window Screenshots

![Image](https://github.com/user-attachments/assets/d2686d5b-214c-4148-80f0-58bec29eddec)

### Logs & Dumps

[crash-2024-12-03-10-45-00-673.zip](https://github.com/user-attachments/files/17995507/crash-2024-12-03-10-45-00-673.zip)

**Comment by JordanTheToaster** [comment]
We do not support piracy.

**Comment by darkfalzx** [comment]
Not a pirate game. Never completed or sold. Unreleased Prototype.

**Comment by F0bes** [comment]
"I didn't pirate it, I just downloaded it online"

The game, it's art, music, models, etc are still considered under copyright. We aren't going to support it.
