### ISSUE TITLE
[Feature Request]: Automatic save states

### ISSUE THREAD

**Issue by Fire-Cube** [PCSX2/pcsx2#12065]
### Description

I would need a feature that automatically creates a save state of the game every 60 seconds, for example.
It should be a function where you can specify in which slot and at what interval a save state should be saved.

### Reason

It is very useful for some unstable games or pcs. When it crashes you will not loose a large amount of playtime

### Examples

I think it is very clear

**Comment by JordanTheToaster** [comment]
This is not the intended way to use savestates if you are having issues with games crashing please use the forums or Discord for support.
