### ISSUE TITLE
[BUG]: Reading from 0x1000F000 significantly hinders the speed of the Emotion Engine.

### ISSUE THREAD

**Issue by Loy2up** [PCSX2/pcsx2#12085]
### Describe the Bug

As the title suggests, reading from this specific offset severely slows down the clock speed. Even when reading from it and writing to the zero register, which rejects all writes, LW'ing this offset somehow slows down the emulation, which doesn't affect the original PS2 and other emulators.

### Reproduction Steps

LW from 0x1000F000 and compare it to an LW from other offsets.

### Expected Behavior

No slowdowns.

### PCSX2 Revision

2.3.50

### Operating System

Windows 11

### CPU

Intel Core i5-12400F

### GPU

NVIDIA GeForce RTX 4060

**Comment by refractionpcsx2** [comment]
Try disabling the INTC hack in the settings. That is designed to skip the EE forward to the next event if it's read from several times as games do this to wait for vsync, but if you're doing it for other reasons you might just end up increasing your EE load.

**Comment by Loy2up** [comment]
> Try disabling the INTC hack in the settings. That is designed to skip the EE forward to the next event if it's read from several times as games do this to wait for vsync, but if you're doing it for other reasons you might just end up increasing your EE load.

I was under the misapprehension this was a bug. I reported it thinking it'd cause a havoc of sync issues. Thanks!
