### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by Naval-777** [PCSX2/pcsx2#12080]
### Describe the Bug

Latest nightly build (11/12/2024), D-pad up and right trigger no longer work. Works on Steam games. Reset configuration using auto-remapper, clear and auto-remapper as well as reset to default then auto rebind. D-pad up can be manually rebound and works in games, shows as "SDL-0/+LeftY" instead of "SDL-0/DPadUp". This is not the case with the right trigger, manual remap would not register right trigger input at all. Tested in THPS3 and POP: Warrior Within.

### Reproduction Steps

Tried to do a board switch in Tony Hawk's Pro Skater 3 using the right trigger and saw there was no input registered, discovered the issue with the D-pad up in the menus. Attempts to fix this have been detailed in the description.

### Expected Behavior

D-pad up and right trigger to register on PCSX2 

### PCSX2 Revision

v2.3.54

### Operating System

Windows 10 (64bit)

### Logs & Dumps

N/A, no crash

**Comment by JordanTheToaster** [comment]
Please use the forums or Discord for support issues.
