### ISSUE TITLE
[BUG]: New Windows installation has littered my documents folder with files and folders instead of using %appdata%\Roaming

### ISSUE THREAD

**Issue by spinstartshere** [PCSX2/pcsx2#12095]
### Describe the Bug

My documents folder is littered with folders and configuration files created by programs, and my documents folder is synchronised to my OneDrive and, therefore, to my other computers. This means that it's not possible for me to set a different configuration for each of my computers, and I also don't want things like shaders and other cached data to be forever synchronised to my OneDrive. There's been a big push from Microsoft in recent years to encourage end users to synchronise their documents folders to OneDrive.
`
%appdata%\Roaming` exists for a reason and it should be utilised for its intended purpose.

### Reproduction Steps

Install PCSX2

### Expected Behavior

All configuration files should be written to `%appdata%\Roaming`.

### PCSX2 Revision

2.2.0

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
This is not a bug if you wish to not have the config in your documents folder you can use a portable install.

**Comment by spinstartshere** [comment]
You have provided an installer, so it's not unreasonable to expect the installer to use the correct folders. The program, once installed, also doesn't provide an option to set a config directory.

What's the rationale for using the documents folder rather than the Roaming directory, which exists for the purpose of storing user-specific configuration files?

**Comment by JordanTheToaster** [comment]
Backwards and forwards compatibility as the documents folder has always been used by PCSX2.

**Comment by spinstartshere** [comment]
The solution to that would be to provide the choice of where this folder should exist - and using the portable version of the program isn't really a solution to this problem for people who want to use the installer.
