### ISSUE TITLE
[Feature Request]: Bringing back the global toggles for Widescreen and No-Interlace Patches, but better

### ISSUE THREAD

**Issue by CookiePLMonster** [PCSX2/pcsx2#12113]
### Description

#12078 removed global Widescreen and No-Interlace Patch toggles citing support maintenance and UX clarity as reasons. This led to some confusion about the current state of these patches, and now forces users to audit per-game settings for **every single game** they own.

The main issues with the global toggles were:
* Users enabled them once and forgot about them, which led to support issues with people swearing they have no patches enabled, when they had.
* The **Patches** screen had a very confusing UI for those fixes - despite these toggles being globally enabled, these patches were unchecked in the list, gaslighting the user into believing that:
   * They were disabled (they were not)
   * They had a choice of toggling them on/off per game (they did not)
 ![Image](https://github.com/user-attachments/assets/91918655-9456-47b1-9727-4e24d24eb1a3)

While those are legitimate issues, they do not outweigh the downsides of forcing users to do the additional legwork. I propose the following:

1. Bring back the toggles exactly how they were.
2. Keep those toggles global only, do not show them in menus per-game.
3. Adjust the **Patches** screen with the following changes:
   1. Make Widescreen/No-Interlace patches support tri-state checkboxes.
   2. Add an additional text notifying the user about the global state of those patches.
   3. Make the tri-state checkbox work as logically expected:
       * Undefined (box) - use the global option
       * Unchecked - disable the patch regardless of the global option
       * Checked - enable the patch regardless of the global option

Here's how the revised screen could look:
![Image](https://github.com/user-attachments/assets/e117aa1b-3a84-4de4-a1ac-145aa4e5db53)

### Reason

Better user experience. No need to enable patches per-game over and over. Global toggles like this also exist in other emulators (e.g. Flycast).

**Comment by crashGG** [comment]
I agree with restoring the global SW and No-interlacing switch and improving the display to a smarter approach.

When a function needs to be used repeatedly, it is logically necessary to use a global switch.

I can also understand why maintainers simply cut this feature because it is difficult to explain to confused novice users when they encounter this problem.but,**Don't throw the baby out with the bathwater**,right?

**Comment by Mrlinkwii** [comment]
>I can also understand why maintainers simply cut this feature because it is difficult to explain to confused novice users when they encounter this problem.but,Don't throw the baby out with the bathwater,right?

@crashGG i mean sometimes it may be needed  , when people can easily enable & disable patches in 3 clicks

**Comment by crashGG** [comment]
> [@crashGG](https://github.com/crashGG) i mean sometimes it may be needed , when people can easily enable & disable patches in 3 clicks
> I prefer to turn on the global switch by default to enjoy the improvements brought by the patch. When a (very few) patch is broken, click 3 times to turn off the patch. Instead of the current situation where each game needs to click 3 times to turn on the improvement, and when a patch is broken, it still needs to click 3 times again to turn off.

That's the point of global switches: to eliminate duplication.

**Comment by CookiePLMonster** [comment]
> In fact, the previous version only needed a simple modification to achieve this function. That is, add the WS and Ni patches to be controlled in per-game setting (Just like in the main settings), and write a note in the "patches" to guide the user to set in "Graphics".like this:

That's the idea behind my current proposal, yeah. Should combine benefits of both having and not having a global toggle.

**Comment by CookiePLMonster** [comment]
Created #12117 to resolve this.
