### ISSUE TITLE
[BUG]: Controller doesnt work in Crash tag team racing

### ISSUE THREAD

**Issue by Emironparas** [PCSX2/pcsx2#12119]
### Describe the Bug

[BUG]: Hi! PCSX2-v1.7.5815 versio was the last versio where controller worked in crash tag team racing. Every version after this versio dont work. You can even change the keyboard settings and nothing changes. every other game works fine but crash tag team racing is unplayable with a controller after PCSX2-v1.7.5815. It has been over 8 months. please fix this!!!!!!

### Reproduction Steps

.

### Expected Behavior

.

### PCSX2 Revision

v2.3.75

### Operating System

MacOS

**Comment by Loy2up** [comment]
Tag Team Racing is working fine. Are you using savestates, or the debugger? Are you sure you're setting up controller 1 - not 2?

**Comment by Mrlinkwii** [comment]
this sounds like a support issue , not an actual  issue , can you join  the discord for support

**Comment by Emironparas** [comment]
and no, im not using save states nor debugger. I have tried for hours to change all type of settings but nothing seems to work. Only thing that works is playing with the version that was launched in May2024

**Comment by Emironparas** [comment]
Sure! Where can I find the discord?

**Comment by Mrlinkwii** [comment]
check the link on the readme :)
