### ISSUE TITLE
[BUG]: Tales of Destiny - Director's Cut Widescreen Bug

### ISSUE THREAD

**Issue by amarantsnipersnake** [PCSX2/pcsx2#12110]
### Describe the Bug

im using the pnach cheat file for widescreen and i have some bug on the UI is not perfectly align on the screen and the sky is not filling the screen in battle
heres the code that im using down below.. can someone help me for this i want to play this in widescreen not stretched screen.

gametitle=Tales of Destiny: Director's Cut (SLPS-25842)

[Widescreen 16:9]
gsaspectratio=16:9
author=nemesis2000

patch=1,EE,0015DD04,word,3C013F20
patch=1,EE,0015DD08,word,34216D3A
patch=1,EE,0015E190,word,00000000
patch=1,EE,0015E198,word,3C013F40
patch=1,EE,0015E19C,word,4481C800
patch=1,EE,0015E1A4,word,46196b42
patch=1,EE,0015E1A8,word,E7AD0040
patch=1,EE,0015E20C,word,3C0143D6

//No interlacing by asasega
patch=1,EE,201A7054,word,00000000
patch=1,EE,201A70DC,word,00000000

[No-Interlacing]
description=Attempts to disable interlaced offset rendering.
gsinterlacemode=1
patch=1,EE,20109FA8,extended,A620066C

### Reproduction Steps

![Image](https://github.com/user-attachments/assets/7502a69d-c26c-4153-bcda-a9aedd68e9f3)

### PCSX2 Revision

v2.2.0

### Operating System

Windows 10 (64bit)

### CPU

i5 10th gen

### GPU

gtx 1650

**Comment by Mrlinkwii** [comment]
please bring any widescreen issues to the widescreren repo https://github.com/PCSX2/pcsx2_patches not **here**
