### ISSUE TITLE
[Feature-Request] - Add automatic aspect ratio switching during FMV playback

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#1212]
Many games support 16:9 either natively (...-ish) or via widescreen hacks for real-time content.

However, pre-rendered content, especially in the latter case, tends to be either 4:3 or letterboxed 16:9, requiring a 4:3 aspect ratio to display properly. An option to switch to 4:3 aspect ratio during FMV playback, similar to the switch to SW mode, would be much appreciated.

**Comment by turtleli** [comment]
Feature has been added by FlatOutPS2. Issue resolved.
