### ISSUE TITLE
Black screen in hardware Renderer

### ISSUE THREAD

**Issue by arshamatonyan** [PCSX2/pcsx2#1214]
I have passed Silent Hill 3 on pcsx2 and have noticed one graphics problem. then you play the disk game shows an intro video. In software rendering mode in DX9,DX11,OpenGL the video is visible but in hardware modes of any API black screen is shown.

**Comment by gregory38** [comment]
Might be related to #1222

**Comment by FlatOutPS2** [comment]
It is. Thanks to #1222 it doesn't flicker in software mode anymore and it is visible in hardware, but in hardware mode it's very dark and there's a grid over the video, like some sort of scanline effect.
