### ISSUE TITLE
[Feature-request]suggestion for gameindex.dbf

### ISSUE THREAD

**Issue by hoholee12** [PCSX2/pcsx2#1216]
beatmania IIDX 3rd - 8th style games have problems with framerate(https://github.com/PCSX2/pcsx2/issues/450)
so i have to manually change framerateNTSC from 59.94 to 59.84 to make the audio sync.
but then it will also desync beatmania IIDX 9th - 16th style games and other games in general.

how about putting framerate option as one of the gamefixes by putting it in gameindex.dbf
something like this:

Serial = SLPM-65156
Name   = Beatmania IIDX - 6th Style
Region = NTSC-J
FramerateNTSC = 59.84

thanks:)

**Comment by willkuer** [comment]
Not sure if a general solution to a special problems is reasonable. I think a pnach solution would be more elegant. However tjat might be more complicated.


Is 59.84 the only valid frequency? What is the uncertainty? 0.01 Hz or even less?

**Comment by hoholee12** [comment]
i dont follow how gameindex.dbf modification is a general solution..

**Comment by willkuer** [comment]
I meant that probably all games require the base framerate and only one game requires a different value. Introducing a new general switch for only one instance might not be reasonable.

I understand though that your idea is indeed a working solution. Maybe all core settings should be adjustable in the gamedb.



As i said the most elegant way would be to implement this idea as a pnach. Then it would instantly work. However it mightbot be possible. Maybe some smart guy as prafull could realize it as pnach.

**Comment by hoholee12** [comment]
arent pnach and gameindex.dbf the same thing by syntax?

maybe we could add some loop here and there to delay frame, but i dont think thats a good idea..

just an educated guess:)

**Comment by hoholee12** [comment]
i noticed that only 3rd - 8th style run in progressive mode by default.
and the other 9th - 16th style run in interlaced and do not have this problem.

maybe there is a problem in the progressive mode portion of the emulator??

**Comment by ssakash** [comment]
I don't think it's reasonable to allow modification of base frequency on GameDB. Also modifying the base frequency isn't the right solution for your problem, there's a probably some bug on the counters instead which causes the following issue.

**Comment by hoholee12** [comment]
@refraction is working on this issue, so i will close this thread for now...
