### ISSUE TITLE
[VIF regression] R5404 broke shadows in Downhill Domination and Twisted Metal: Head-On - Extra Twisted Edition

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#1218]
**PCSX2 version:**
* v1.5.0-dev-381-g93ab2f0-master-561-vs2015-Win32-AppVeyor (2016-02-26; PR #1205's automated build).
* Regression started in R5404 (2012-09-05; ad3720c107f4f0aeae7f4e9151b0ddcbb535b9d5)

**PCSX2 options:**
Defaults. No options modifications affect this issue.

**Plugins used:**
Defaults (GSdx32-AVX, LyliPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk). No particular plugins affect this issue.

**Plugin settings:**
GSdx (Direct3D11/OpenGL software and hardware modes). No settings modifications affect this issue.

**Description:**
I'm reporting this issue for two games in one shot because they share similar game engines, the same problem and essentially come from the same developer (Incognito Entertainment and a spinoff of it called Eat Sleep Play).

In R5403 and below, shadows rendered decently in Downhill Domination and Twisted Metal: Head-On - Extra Twisted Edition. This was tested with Direct3D11's software and hardware modes. OpenGL support had yet to be added in that era's versions of GSdx.

Starting in R5404, shadows broke in both games. Normal shadow outlines still appear, but they're complemented by thin, flickering triangles. The triangles are as dark as the shadows and spin around in a circular pattern around cyclists/vehicles that are in motion.

**Screenshots:**
* Downhill Domination
  1. [R5403](https://cloud.githubusercontent.com/assets/13129485/13551581/f463439c-e30c-11e5-9619-517f37b3f94d.png)
  2. [R5404](https://cloud.githubusercontent.com/assets/13129485/13551587/0d1c95dc-e30d-11e5-89be-e828925fdb37.png)
  3. [v1.5.0-dev-381-g93ab2f0-master-561-vs2015-Win32-AppVeyor](https://cloud.githubusercontent.com/assets/13129485/13551590/11f20d6c-e30d-11e5-98e5-9282f161c9ac.png)
* Twisted Metal: Head-On - Extra Twisted Edition
  1. [R5403](https://cloud.githubusercontent.com/assets/13129485/13551592/15d95d90-e30d-11e5-98f3-fbb49222d28b.png)
  2. [R5404](https://cloud.githubusercontent.com/assets/13129485/13551593/19194b5a-e30d-11e5-9849-b6095fe5700d.png)
  3. [v1.5.0-dev-381-g93ab2f0-master-561-vs2015-Win32-AppVeyor](https://cloud.githubusercontent.com/assets/13129485/13551594/1c6b1a72-e30d-11e5-91ec-811bbac4c55d.png)

**How to replicate (Downhill Domination):**

1. Launch PCSX2.
2. Open GSdx's plugin settings, select Direct3D11 or OpenGL's software renderers.
3. Fast boot the game.
4. Skip the game's intros, then wait at the title screen. Don't press any buttons.
5. After 1-2 minutes, the game's attract mode will start. It'll load a desert level called "Red Pass, Utah FR".
6. The camera will pan across the level, then focus on individual cyclist bots in a sample race.
7. While the camera is focusing on moving cyclists, look closely at their shadows. Triangular shadows will appear alongside the cyclists' normal shadow outlines.
8. To see the issue outside of attract mode, press any button to exit it.
9. From the game's title screen, press X, select "SINGLE PLAYER", pick any character, "START NEW GAME", "SINGLE EVENT", then "FREERIDE".
10. At the "INVENTORY" screen, press Start, select "RED PASS FR", then launch it.
11. Press any button to skip the camera pan of the level and start the race.
12. Cycle down the mountain and look closely at your cyclist's shadows. They may initially look normal, but after a little while while, triangular shadows will start appearing alongside the cyclists' normal shadow outlines.

**How to replicate (Twisted Metal: Head-On - Extra Twisted Edition):**

1. Launch PCSX2.
2. Open GSdx's plugin settings, select Direct3D11 or OpenGL's software renderers.
3. Fast boot the game.
4. Skip the game's memory card screen and intros.
5. At the title screen, select "Twisted Metal: Lost" and skip its intro.
6. At the main menu screen, select "SINGLE PLAYER", "ENDURANCE", pick "RoadKill" and select the "Suburban Terror" level.
7. Start the match. Once in-game, hold down all shoulder buttons and press these d-pad buttons in sequence: right, left, down, up. An "Invulnerable On" notification should appear. This will prevent the opponent from being able to quickly kill you.
8. Drive around. Triangular shadows will appear alongside the car's normal shadow outlines.

**Last known version to work:**
R5403 (2012-09-05; 31f685c490c691f3987e69057f21c7131d02a772)

**PC specifications:**
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; OS: Windows 7 SP1

**Other comments:**
After R5404 [ad3720c107f4f0aeae7f4e9151b0ddcbb535b9d5], two subsequent revisions (R5482 [ac54bad33c0e3a8f7ccc56f948fa8e6ba15ffe79] and R5544 [c30f67b76750fa42d060ee7ff6e6355bf353bd6a]) fixed issues that started in the former for certain games. Maybe @sudonim1 and/or @refractionpcsx2 would be in the best position to resolve this?

**Comment by refractionpcsx2** [comment]
Ugh another game broken by this, how annoying. Okay I'll look in to this at some point.

**Comment by refractionpcsx2** [comment]
Should be solved now on master branch

**Comment by gregory38** [comment]
Good jobs

**Comment by Aced14** [comment]
@refractionpcsx2 Thanks :)! I recently double-checked both games and didn't notice any remaining signs of glitched shadows.

**Comment by refractionpcsx2** [comment]
Awesome :)

**Comment by Ghaleon777** [comment]
The glitched shadows aren`t a problem anymore, but the black glitches around the car textures and fire glitches are a problem since ages; I really hope those can be fixed
