### ISSUE TITLE
Display FPS, EE, GS, the processing status of the VU to the console

### ISSUE THREAD

**Issue by Japanese1** [PCSX2/pcsx2#1219]
FPS while playing in full screen, EE, GS, we want you to view the processing status of the FPS, etc. to the console because I want to check the processing status of the VU.

**Comment by vsub** [comment]
What do you mean,how exactly will you display the FPS in the console...spamming the console every ? seconds with the info or?

If you need something simple and quick,here is an AutoHotkey script

```
Loop
{
Sleep,1000
IfWinNotActive,AHK_class wxWindowNR
{
ToolTip
Continue
}
WinGetPos,X,Y,A
If X != 0
{
ToolTip
Continue
}
WinGetTitle,Title,A
If Title not contains GSdx
Continue
StringSplit,Title,Title,|
ToolTip,% Title5 " | " Title8 " | " Title9 " | " Title10,0,0
; ToolTip,% Title, X, Y
}
```
If you open the autohotkey console(double click on the tray icon)and go to View=>Variables,you'll see which variable what info holds and you can place the Info? in ToolTip like the example above
Or if you what to get all the info the exact same way it is the game window in window mode,delete the SplitString and the ToolTip below it and remove the ; infront of the other ToolTip

**Comment by gregory38** [comment]
I can tell you that you will better enjoy your gameplay if you look at the game rendering instead of the console. Either your play (don't care about fps), either you profile (don't care about full screen).
