### ISSUE TITLE
[Request]Change how the scrollbar works in the console

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1220]
It's been like this since forever.
If you want to go up or to the top,your only option is to use the mouse wheel(which is slow)or use PageUp(which is a little faster but also slow)

The Home/End buttons do nothing and trying to move up by using the scrollbar always goes to the bottom once you release the left mouse button.

**Comment by MrCK1** [comment]
Since we're discussing the console - I'd like to note that "always on top" option hasn't worked for a while either

**Comment by turtleli** [comment]
Could you provide a bit more detail on what behaviour you are requesting?

**Comment by vsub** [comment]
?
I just want to be able to use the scrollbar,when I click and hold the scrollbar and move up/down,when I release the left mouse button to stay on that position.

This is normal behavior anywhere but in pcsx2,if you release the left mouse button,it will always automatically scroll to the bottom even if the emulation is paused and nothing new  appears in the console.

Lets say you start a game,enable all of the logging options(including CDVD reads)and when the game start you want to get the crc(or get some other info)

Since you can't use the scrollbar,you have you press page up(or hold it)until you reach to the point where the crc is(you can't as I said also use the Home key to go to the top)

**Comment by turtleli** [comment]
Hmm. Is the emulation pause/resume behaviour when using the scrollbar useful to anyone?

I have this working in my branch, but it'll return to the bottom of the console for game requires gamefixes due to the pause/resume behaviour (because it'll add stuff to the console). If I remove the pause/resume behaviour then it'll work for all games until a new message appears in the console.

**Comment by vsub** [comment]
Well it has its uses but if you/someone else like to keep that feature,at least make the scrollbar to not go to the bottom when the emulation really is paused(pressing esc or closing the GS window)

**Comment by willkuer** [comment]
Maybe only auto move down if the scrollbar is in the lowest position and keep scrollbar position otherwise?

**Comment by vsub** [comment]
Yes,that's even better

**Comment by turtleli** [comment]
willkuer's suggestion sounds good, though it may be difficult to implement.

I updated the console behaviour - it shouldn't go back to the bottom until more text appears in the console.

And it seems that the pause/resume scrollbar behaviour is Windows only, which is a bit strange.

**Comment by bositman** [comment]
Finally I can check out the log while a game is running  good job :)

**Comment by turtleli** [comment]
It seems intended, but I'm wondering whether it should be removed. I'll remove it in a week if nobody voices an objection and provides a use case.

**Comment by vsub** [comment]
Thanks,that's better.
And about the other feature,it's probably added as a faster way to apply thing rather than using Esc=>Resume

For example enabling/disabling the cheats or widescreen patches while ingame has no effect(at least the last time I check)until you pause=>resume or you can use it to apply one time cheats again

**Comment by turtleli** [comment]
The cheats/widescreen patch thing (which you mentioned in #841) is more of a bug IMO. I think the last time I tried to fix it I couldn't get the widescreen patches to disable without restarting PCSX2, though maybe that's an existing bug (maybe related to #1310).

On another note, regarding the Always On Top menu option - I may just remove it since it's non functional. If anyone is trying to implement the feature, please let me know.

**Comment by avih** [comment]
Seems we're not the first to want to not scroll to the bottom automatically, and seems there's no obvious way to do that.

Been discussed here: https://forums.wxwidgets.org/viewtopic.php?t=39976 and to a lesser degree here https://groups.google.com/forum/#!topic/wx-users/Iw0Zw61nyyo

**Comment by gregory38** [comment]
Is the initial issue still open ?  From previous comment it seems to be fixed, so shall we close the issue.

**Comment by FlatOutPS2** [comment]
Original issue is gone. It would be nice if there was an option to stop it from automatically jumping down on new console messages, but that's just a minor nuisance.

**Comment by gregory38** [comment]
ok let's close it. We have too much issue open already ;)
