### ISSUE TITLE
[Regression] Resident Evil 4 PAL 50hz frame buffer size spam

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1224]
Description:
ssakash's  commit "Detect RT size based on display and frame registers." from pcsx2-v1.5.0-dev-407 seems to cause a regression in Resident Evil 4's 50hz(PAL) mode. It makes the game to constantly switch frame buffer size and spam the console with:
"Frame buffer size set to  448x512 (1344x1536)
Frame buffer size set to  512x512 (1536x1536)"

Options and plugins all default, except using HW renderer with above native resolution

How to replicate:
Use pcsx2-v1.5.0-dev-407-gedef3ad or later. Select one of the hardware renderers using higher than native resolution, and boot the PAL version of Resident Evil 4 without turning on Progressive Scan.

Last known version to work:
v1.5.0-dev-405-g8839632

**Comment by ssakash** [comment]
I assume the width of this game is something not referable by the FBW register. Is the width not a multiple of 64 ? what's the native resolution of this game ?

I think maybe the game constantly changes the FBW value between 7/8. hence. I'll provide a patch for you test in a moment.

**Comment by ssakash** [comment]
@FlatOutPS2

Could you test #1225  ?

**Comment by gregory38** [comment]
Note FB buffer must never be reduced.

**Comment by FlatOutPS2** [comment]
The commit fixes the issue. I didn't notice any regressions in other games I've tried(including BG, RBR and Nitro Kart) either.

The native resolution of this game is actually 427x512.

**Comment by ssakash** [comment]
> The native resolution of this game is actually 427x512.

![crazy](http://ultraimg.com/images/image3874e.jpg)

> The commit fixes the issue. I didn't notice any regressions in other games I've tried(including BG, RBR and Nitro Kart) either.

Thanks :) , please watch our for further regressions.
