### ISSUE TITLE
SSE4 or AVX on Linux

### ISSUE THREAD

**Issue by teo6389** [PCSX2/pcsx2#1236]
Hello I found an old thread dated about a year ago with the same question. Will we ever get libsdx with sse4 or AVX support on linux? I just downloaded the latest version of pcsx (1.4.0) and it still uses sse2. Thank you in advance

**Comment by refractionpcsx2** [comment]
The emulator itself doesn't really benefit from AVX2 or SSE4, in fact the windows build only uses SSE2 as well.  The only thing that benefits is GSDX, which I'm not sure what that is built with on linux, presumably just SSE2 unless multiple builds are made (like with windows)

**Comment by refractionpcsx2** [comment]
it's more likely because you are using DirectX on windows and OpenGL or Software mode on linux. The architecture used will make no more than ~2fps difference.

Do you have an AMD graphics card?

**Comment by teo6389** [comment]
No, my gpu is nvidia

**Comment by refractionpcsx2** [comment]
hmm, then performance should be similar in opengl mode for you. if it is about half the speed in linux, i would assume your opengl driver isn't letting you use multithreading

**Comment by teo6389** [comment]
OK, how can I verify that?

**Comment by refractionpcsx2** [comment]
I don't know as i don't use linux but @gregory38  should lol

**Comment by gregory38** [comment]
Which version of PCSX2 did you download. If you build it manually, it will pick all the optimizations (more than windows). Otherwise, on the official build, I added AVX2/SSE4 for GSdx.

How do you run PCSX2?

**Comment by teo6389** [comment]
I installed it using the ppa, I didn't build it my self. The version is 1.4.0. And I run it from my application menu of my OS(kubuntu)

**Comment by teo6389** [comment]
Is there a tutorial to show me how to build it? Thank you

**Comment by willkuer** [comment]
This is a good point to visit the forum (forums.pcsx2.net) instead of getting help here. You need support while this page is for developer discussion. There are probably dozen explanations for your problem but to solve them one would need more information. I would rather ask in the forum for support instead of asking the devs.

**Comment by gregory38** [comment]
Yes,  and try to use the provided wrapper to launch PCSX2 correctly. Check also accurate option in gsdx.

**Comment by teo6389** [comment]
Sorry for posting.... I just thought it was a development issue that I was missing the sse4 option

**Comment by gregory38** [comment]
no worry. Anyway as Ref said, SSE4 is unlikely to be the issue. MT drivers is enabled automatically by `PCSX2-linux.sh`
