### ISSUE TITLE
lilypad for mac?

### ISSUE THREAD

**Issue by mgracer48** [PCSX2/pcsx2#1248]
Where can i get it
i see youtube videos where mac users have it but where can i get it for mac

**Comment by Blackbird88** [comment]
WINE?

**Comment by mgracer48** [comment]
Lol whoever uses wine for pcsx2 won't get a good performance ill tell u that

**Comment by mgracer48** [comment]
just use the mac version

**Comment by willkuer** [comment]
You have no idea what you are talking about. You compare pcsx2 0.97 (native) vs pcsx2 1.4 (wine).


This is not a forum. It's a bug tracker for the devs. Please respect that and use the forum to get support.

**Comment by gregory38** [comment]
Core + sound + input will be as fast as native on wine.

The only bad impact is potentially GSdx. But it is faster than zzogl anyway. IMHO, GSdx would remain fast except few games that are limited by the gpu driver. (And it is potentially faster on slow drivers, read AMD here).

**Comment by willkuer** [comment]
I read that wine has some problems with threading resulting in overhead in mt applications. However it was really complicated to get facts about wine and mt and not just opinions. If that is true core might be slower especially with mtvu.

Sound is slightly restricted as not all api's are supported. ( i think xaudio is missing while portaudio and dsound exist but could be wrong)

Imo the main problem is that people try to emulate on pre-2011 macbooks with i3's  and igpu.

**Comment by mgracer48** [comment]
lol my mac is late 2011 so i guess im good

**Comment by gregory38** [comment]
Even with a threading overhead, most of the cpu time in mtvu is inside the recompiler. Threading impact is likely very small. Anyway, wine is by far the best option. And a basic Mac port will likely be slower.

**Comment by mgracer48** [comment]
i done wine and it might be the cause of the slow mo sound #1250

**Comment by refractionpcsx2** [comment]
Please stop using github for support, if you want to ask questions please use the forum, we're trying to keep the noise to a minimum on here.
