### ISSUE TITLE
Battle for bikini bottom sound issue

### ISSUE THREAD

**Issue by mgracer48** [PCSX2/pcsx2#1250]
If you run the game for some people (like me) the sound is in slow motion and really annoying and makes it playable but annoying

**Comment by DPersonalized** [comment]
Are you running at full speed?

**Comment by mgracer48** [comment]
title screen is 35 fps
my spaces actually might not be good
here they are
processor : 2.4 GHz Intel Core i5
Intel HD Graphics 3000 512 MB
8gb ram

**Comment by mgracer48** [comment]
It makes sense heavy iron studios did a great job with this game though i did have better performance with dolphin

**Comment by refractionpcsx2** [comment]
if your game isn't running at full speed then that isn't a bug it's due to the speed of your computer, thus this is an issue for the forums as support.
