### ISSUE TITLE
Samurai Western - not text (Guide)

### ISSUE THREAD

**Issue by n1dminhd** [PCSX2/pcsx2#1262]
Pcsx2 1.5.0-490
Opengl HW - SW
DX11 HW - SW
DX9 HW- SW
Game full speed but not text
![untitled](https://cloud.githubusercontent.com/assets/4449742/14012311/a24e2b10-f1d7-11e5-934c-663265c0ecfb.jpg)
![untitled 2](https://cloud.githubusercontent.com/assets/4449742/14012317/a8c86ad2-f1d7-11e5-9550-2c73ee34631a.jpg)

**Comment by Catarax** [comment]
Try it on stable 1.4 release to see.

**Comment by n1dminhd** [comment]
Yes
![untitled 2](https://cloud.githubusercontent.com/assets/4449742/14017814/9ee2a486-f1fc-11e5-94f5-aafef414558a.jpg)
![untitled](https://cloud.githubusercontent.com/assets/4449742/14017815/9f14bcfa-f1fc-11e5-84fa-ee7dd6d9f93b.jpg)

**Comment by Catarax** [comment]
Okay, there is a kind of bug on the actual dev version. Tekken Tag Tournament doesn't have text in menu too. Seems related.

**Comment by willkuer** [comment]
If it doesnt work in sw its probably a core issue. Maybe the lateat vif change by ref is the reason? Please try the following build without those changes:

http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-479-gbe34b96&platform=windows-x86

**Comment by MrCK1** [comment]
This might be the same issue encountered in #1200 - Ed, Edd, 'n Eddy had missing menu text as well, and was fixed by setting VU Rounding to Positive

**Comment by gregory38** [comment]
@refractionpcsx2 could you share with us your valuable feedback :)

**Comment by refractionpcsx2** [comment]
I'll have a look, this shouldn't have made anything that worked on 1.0.0 not work anymore though xD

**Comment by refractionpcsx2** [comment]
Works fine for me on my code? 

![samuirai](https://cloud.githubusercontent.com/assets/6278726/14032621/06d11230-f20c-11e5-9704-ed8e51dcdb9b.jpg)

I'm updating to a newer version to see if it's broken since.

**Comment by refractionpcsx2** [comment]
After some testing, I can label it. Off you go @gregory38 :P

- [ ]

**Comment by n1dminhd** [comment]
Pcsx2 1.5.0-492
- OGL HW. DX11 HW not text
- DX11 SW ok text

**Comment by gregory38** [comment]
Arg. I wrongly read that it was broken in sw too. Either i need to thighten the hack. (Or my hack overflow a little). Or there is another bug in the mix.

**Comment by refractionpcsx2** [comment]
> Arg. I wrongly read that it was broken in sw too.

I did exactly the same thing, that confused me, especially when it worked fine for me lol

**Comment by gregory38** [comment]
Note for myself: check if both Alpha test and Depth test are disabled to allow the hack.

**Comment by n1dminhd** [comment]
What the "Alpha test and Depth test" ?
take a photo

**Comment by gregory38** [comment]
the important word was "myself" ;) Alpha and Depth tests are pixel tests done by the GS renderer. If the test is fail the target mustn't be updated.
The current hack detects a rectangle clear. And translate it as a write of 0 in memory. It won't work if some pixels mustn't be written.

**Comment by n1dminhd** [comment]
Pcsx2 1.5.0-498

![untitled 2](https://cloud.githubusercontent.com/assets/4449742/14060309/d41bd98c-f392-11e5-943f-d7e2d53d123e.jpg)
![untitled](https://cloud.githubusercontent.com/assets/4449742/14060310/d4207d5c-f392-11e5-8767-6da25f65128d.jpg)
