### ISSUE TITLE
Bios USA 2.3 (PS2 Boot Logo Weird with PAL game)

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1263]
Bios : USA 2.30
Boot : Full
Game : Any PAL game
Build : v1.5.0-dev-498-ga99750a

The Playstation 2 logo goes completely wrong if the game ain't NTSC.
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/14062194/14c60bee-f396-11e5-9fa0-8c324dd0ad5d.png)

**Comment by deadair3210** [comment]
Does the rest of the game look normal and its just the logo, or is the entire game like that?

**Comment by Catarax** [comment]
No issues with the PAL games.
Just the PS2 logo in software or hardware mode at the beginning.

**Comment by willkuer** [comment]
I think that it even boots is rather a bug.

**Comment by deadair3210** [comment]
Can you post a log of you getting the weird logo. I'll look and see if I can notice anything weird

**Comment by refractionpcsx2** [comment]
This isn't a bug, the logo is encrypted and only the right region BIOS can decrypt it correctly, this is completely normal.
