### ISSUE TITLE
Bios Europe 2.3 (Full Boot doesn't allow NTSC games)

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1264]
Bios : Europe 2.30
Boot : Full
Game : Any NTSC game
Build : v1.5.0-dev-498-ga99750a

The european bios can't load an NTSC game with a full boot. Only fast boot works.

![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/14062221/19eee112-f397-11e5-94fd-c44a66df08ff.png)

The japanese bios 2.20 can't load a PAL game in full boot  also.

**Comment by deadair3210** [comment]
I'm going to go out on a limb and say that its because of the region lockout. Europe bios is meant for PAL games and will refuse to play NTSC or NTSC-J. Japanese bios is meant for NTSC-J and will refuse to play PAL or NTSC. Fast boot skips the bios, so the region lock never gets a chance to stop the game from booting.

**Comment by Catarax** [comment]
Sure, but I don't understand why only the USA bios is able to play all kind of games then (PAL, NTSC-J).

**Comment by mirh** [comment]
Pretty sure pcsx2 is supposed to give 0 damns about locking.

**Comment by willkuer** [comment]
I think this is really the point of fastboot. It overcomes the lock.

**Comment by deadair3210** [comment]
I'm pretty sure that the USA bios cant boot PAL or NTSC-J games correctly either, though im not sure.
The point of fastboot is to start execution at the start of the game, completely skipping all bios code except hardware init. This includes the lockout,as its a purely a software thing

**Comment by refractionpcsx2** [comment]
This is the region lock in the BIOS this isn't an issue with the emulator, if you want to use PAL games on an NTSC BIOS please use the fast boot.

If you "need" to use full boot for a specific game, you will have to install a modchip in your PS2 and redump the BIOS with the modchip enabled to bypass the region locking.

**Comment by mirh** [comment]
I was thinking.. If fast boot is the only way to bypass regional locking then
And if full boot is the only way to have non-default languages in games.. 

Wouldn't this mean we have a "hole" there?

**Comment by refractionpcsx2** [comment]
It's not really a hole that is our fault. If we can come up with a way to bypass the region check then sure, we could do that, but it's really not something which is a priority, nor something i particularly want to look in to :P
