### ISSUE TITLE
[GSdx hardware regression] GS memory clear fix broke textures in most of Incognito/Eat Sleep Play's games

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#1267]
**PCSX2 version:**
* v1.5.0-dev-498-ga99750a (2016-03-26; a99750ae8761ad0c8a69c547f2bf0560537367a9).
* Regression started in v1.5.0-dev-487-g8e5e770 (2016-03-19; 8e5e770fd12f9c9b2cdd266846af3e84ac39da94)

**PCSX2 options:**
Defaults. No options modifications affect this issue.

**Plugins used:**
Defaults (GSdx32-AVX, LyliPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk). No particular plugins affect this issue.

**Plugin settings:**
GSdx (Direct3D11/OpenGL hardware modes).

**Description:**
I recently came across 8e5e770fd12f9c9b2cdd266846af3e84ac39da94's commit message and noticed its description claims it fixes #768 and possibly #855. Twisted Metal: Head-On - Extra Twisted Edition's FMVs have a nearly identical issue, so I figured I'd give that commit's build a shot to see if TMHOETE had benefited. It did, but at a cost... All text and certain visual effects started disappearing in GSdx hardware mode. Nothing changed with a99750ae8761ad0c8a69c547f2bf0560537367a9.

I later went through Incognito/Eat Sleep Play's other games and noticed most of them have been negatively impacted as well (except Downhill Domination). In some cases, menus and HUDs have become completely unusable. Certain in-game objects have also lost their textures.

If I run into the issues and press F9 to switch to GSdx software mode, they persist. Running the games from scratch in GSdx software mode (without toggling to hardware) looks fine. Hardware mode also looks fine if I enable ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini before launching PCSX2.

Any chance the GS memory clear fix could be revised to better accommodate these games (and magazine/etc demos of them) by default? IMO the burden shouldn't be on the user to manually change an ini file for this developer's games. It's also a lose-lose situation for TMHOETE because its FMVs benefit from the GS memory clear fix, whereas other parts get broken by it.

**Screenshots:**
* Twisted Metal: Black
  1. [v1.5.0-dev-498-ga99750a (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14069574/ee31da10-f469-11e5-8056-dfe0faaf6b2a.png)
  2. [v1.5.0-dev-498-ga99750a (OpenGL hardware, ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini)](https://cloud.githubusercontent.com/assets/13129485/14069576/f2cbe5a2-f469-11e5-96bd-59f0a02d869b.png)
* Twisted Metal: Black Online
  1. [v1.5.0-dev-498-ga99750a (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14069590/0639ff16-f46a-11e5-98cb-ff898e4a6a4b.png)
  2. [v1.5.0-dev-498-ga99750a (OpenGL hardware, ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini)](https://cloud.githubusercontent.com/assets/13129485/14069592/082c33de-f46a-11e5-99e3-bfea456b1986.png)
* War of the Monsters
  1. [v1.5.0-dev-498-ga99750a (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14069595/19150b44-f46a-11e5-9494-d610accefa1c.png)
  2. [v1.5.0-dev-498-ga99750a (OpenGL hardware, ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini)](https://cloud.githubusercontent.com/assets/13129485/14069596/1ae7e1a8-f46a-11e5-915a-08a76fe32341.png)
* Twisted Metal: Head-On - Extra Twisted Edition
  1. [v1.5.0-dev-498-ga99750a (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14069604/288e3abe-f46a-11e5-90c4-d385e9045048.png)
  2. [v1.5.0-dev-498-ga99750a (OpenGL hardware, ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini)](https://cloud.githubusercontent.com/assets/13129485/14069605/29821ae4-f46a-11e5-9bbc-5f2550f31ea0.png)

**How to replicate (Twisted Metal: Black):**

1. Launch PCSX2.
2. Open GSdx's plugin settings, select Direct3D11 or OpenGL's hardware renderer and ensure "Enable HW Hacks" is unchecked.
3. Fast boot the game.
4. Skip the game's intros and select any mode/car/level to get in-game.
5. Once in-game, look at the HUDs. Part of the radar HUD will be black, as well as almost everything in the weapon HUD.
6. Drive around the level. Certain objects won't have any detail at all.
7. Steps 5 and 6 didn't work as expected. Various textures are missing.

**How to replicate (Twisted Metal: Black Online):**

1. Ensure a PS2 network configuration is present on your virtual memory card. This game lacks a built-in network configuration utility.
2. Launch PCSX2.
3. Open GSdx's plugin settings, select Direct3D11 or OpenGL's hardware renderer and ensure "Enable HW Hacks" is unchecked.
4. Fast boot the game.
5. Skip the intro FMVs and select "LAN" in the main menu.
6. Create a game room and go in-game. Parts of the radar and weapon HUDs will be solid grey or black.
7. Drive around the level. Certain objects won't have any detail at all.
8. Steps 6 and 7 didn't work as expected. Various textures are missing.

**How to replicate (War of the Monsters):**

1. Launch PCSX2.
2. Open GSdx's plugin settings, select Direct3D11 or OpenGL's hardware renderer and ensure "Enable HW Hacks" is unchecked.
3. Fast boot the game.
4. Skip the intro FMVs and select "1 Player - adventure".
5. Most of the monster icons will appear black and some text will be missing.
6. Step 5 didn't work as expected. Most icons should've contained images and white border outlines. Left-aligned "1", "2", "3" and "4" text should've also appeared.

**How to replicate (Twisted Metal: Head-On - Extra Twisted Edition):**

1. Launch PCSX2.
2. Open GSdx's plugin settings, select Direct3D11 or OpenGL's hardware renderer and ensure "Enable HW Hacks" is unchecked.
3. Fast boot the game.
4. The game will launch into a completely black screen with background music.
5. Press X to proceed, skip the FMVs, then select "Twisted Metal: Head-On".
6. No text will appear in the menu.
7. Steps 4 and 5 didn't work as expected. Step 4 is supposed to be a memory card menu and step 5 is a main menu interface.

**Last known version to work:**
v1.5.0-dev-486-gc87e4a4 (2016-03-21; c87e4a45829e13469b4e6d4f78f1e848caf1972a)

**PC specifications:**
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; OS: Windows 7 SP1

**Other comments:**
@gregory38 FYI.

**Comment by gregory38** [comment]
Of course, the purpose wasn't to remove parr of the rendering.
Could you generate me a gs dump (search forum how to, basically shift f8)

Maybe I just miss a check of the target format.

**Comment by gregory38** [comment]
I pushed a new git commit that could potentially fix some of your issues. Could you give it a try?

**Comment by Aced14** [comment]
@gregory38 Thanks :)!

Looks like f6ee94589ffe86ff61d72cf33a425fdf3bc93d4d fixed all 4 games. All of them now look like their second screenshots without needing to set ``UserHacks=1`` and ``UserHacks_DisableGsMemClear=1`` in GSdx.ini.

Furthermore, in TMHOETE, FMVs are now benefiting from the clear fix without any negative impacts on anything else.

On another note, in TMHOETE, your latest commit has restored some weapon firing effects that had gone missing in 8e5e770fd12f9c9b2cdd266846af3e84ac39da94. All of these effects look completely perfect in OpenGL hardware mode now. Direct3D11 still has some longstanding issues, but that's out of scope for this issue.

**Screenshots (Twisted Metal: Head-On - Extra Twisted Edition):**
1. [v1.5.0-dev-498-ga99750a (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14087192/b86d976a-f4f6-11e5-98d3-026a3cd29bd1.png)
2. [v1.5.0-dev-504-gf6ee945 (OpenGL hardware, no hacks)](https://cloud.githubusercontent.com/assets/13129485/14087194/bd89fd2e-f4f6-11e5-864f-e884e1fbf224.png)

Are you still interested in a GS dump? Not sure if there's any value in it anymore since this issue's been resolved. Btw I'm planning on reporting more issues related to Incognito/Eat Sleep Play's games in the future.

**Comment by gregory38** [comment]
Good news. Perfect.

No need of the dump. I have thousands of them already.

**Comment by willkuer** [comment]
Unfortunately there is no obvious reputation system, therefore: You did a good job here. Reports like yours make it much easier for the devs to fix errors. Thanks for spending your free time helping the community.

**Comment by Aced14** [comment]
@gregory38 Ok, cool :).

@willkuer Thanks :)! I know how frustrating it can potentially be to work with overly-short/non-descriptive issues. So I try to go all-out with mine.

I guess regression issues benefit the most from it, since if the reporter is willing to devote enough time to researching, they can pinpoint exactly when it started and hopefully make developers' lives much easier.

The closest feature GitHub has to a reputation system at this time seems to be reactions:
[GitHub Blog: Add Reactions to Pull Requests, Issues, and Comments](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)
