### ISSUE TITLE
Random Stutter @ 60fps

### ISSUE THREAD

**Issue by mxoagn** [PCSX2/pcsx2#1272]
What i can only assume is that the internal emulator refresh rate is different to the desktop, my desktop marks out on Nvidia and CRU at 60hz, i am running Devil May Cry 3 and a few other US games at 60fps but every about 15 seconds i get a few seconds of stuttering. 

Vsync is on, 60fps is fully maintained during this time, i get the same issue on ps1 emulation but not on Gamecube/Wii if i make a custom 30hz refresh rate or vsync to 60 on games that can,

**Comment by willkuer** [comment]
There are several explanations for your issue including but not only cpu performance reduction by intel eist/speedstep, turbo-boost, overheating, power saving, background processes, vsync/windows aero, bad settings, disk access times, typical emulation problems. 

However we have a support forum where you can discuss all these possibilities with the supporters. Only if it was confirmed to be an issue with the emulator a bug report can be filled either here or in the forum. In the forum the bug report will be handled appropriately and transfered here to keep the same style and necessary information to help devs as much as possible to solve the issues.

With the given information this issue can not be considered a valid bug report. Please visit the forum instead and ask for support.

**Comment by Dokman** [comment]
@mxoagn you need to turn off hyperthreating and i think it will works correctly

**Comment by gregory38** [comment]
I close the report as it ought to be discussed on the support forum instead. (and I'm afraid except tuning various config nothing can't be done).
