### ISSUE TITLE
Problem FPS Bandai Game in Movie

### ISSUE THREAD

**Issue by zerr10** [PCSX2/pcsx2#1279]
ok in Version " pcsx2-r5875+ shaders+fx and last plugin from version 1.4.0 SEE2 " everything is in order Stable FPS 50 in game Naruto Ultimate Ninja Movie , but last version I mean pcsx2 1.4.0 +
EmuCR-pcsx2-20160403-x86 problem whit FPS in movie all game Bandai Naruto Why ??? same option all i dont understand... in version **" pcsx2-r5875 "** i have Stable **FPS 50** But New Version only **45 FPS Slow...** all same option... this will by fix ??? i have pc : # **AMD APU A8 3870 4x3.0Ghz  R7 250X 2GB 8 GB RAM DUAL 1866Mhz** windows 10 pro pls fix this , i think is some problem whit new EE Scale Cycle. before i can use EE Cycle like ps2 standard mode but now i need use some option bicause i have only 45 fps when i use some option movie is ok is 50 fps but sometime when i use some skill naruto is problem whit sound but fps no go down Strange....
pcsx2-r5875 + shaders + fx" in this version stable 50 fps +all skill normal sound. normal speed in movie , new pcsx2-20160403-x86 problem only 45 fps pls. fix.
**i use GS plugin gsdx-sse2 it seems to me that something is wrong with the exe file because I use the same plug-in versions of both the old and the new and still new version has a problem with stability
whether it will support DX12? Maybe it would help **

problem here whit fps bandai game in version **pcsx2-20160403-x86 1.5.0** Strange... in old veersion pcsx2-r5875 i have same option + fx + shader but fps is good normal speed in movie all is good... but now is problem last version, same 1.4.0
i use GS plugin gsdx-sse2 it seems to me that something is wrong with the " exe " file because I use the same plug-in versions of both the old and the new and still new version has a problem with stability, win 10 pro 64x AMD APU A8 3870 4x3.0Ghz 8 GB DUAL 1866Mhz R7 250X Now every time I have to use some options EE cycles because they have only 45 fps when I use cycles, it again is a problem with something else, for example, with the sound of some techniques for instance in Naruto. even disabling shaders and setting the lowest native resolution does not help
in the new version you have cobination of cyckle EE **Sad**  :(Please fix, is that at least it was like in the old version of **# PCSX2-r5875 {1.2.1) **

**Comment by willkuer** [comment]
Or you just use the old version if it rather fits your expectations.

Please visit the support forum to discuss with the community if your problem is indeed something that needs to be fixed on the code base. However this issue tracker here is for development discussion and your post neither fulfills the expectation of a bug report or something else. What you need is support.

**Comment by gregory38** [comment]
As stated above, you need to discuss it on the forum. Nobody will help you here.
