### ISSUE TITLE
Shaman King - Power of Spirit : (1.5.0-546 - Black screen) & (1.4.0 -  Normal )

### ISSUE THREAD

**Issue by n1dminhd** [PCSX2/pcsx2#1280]
PCSX2 1.5.0-546 : OGL HW + DX9 HW + DX11 HW + OGL SW

![untitled 6](https://cloud.githubusercontent.com/assets/4449742/14312262/c386dae6-fc15-11e5-9e8e-4aa7dca159c2.jpg)

PCSX2 1.4.0 : OGL HW

![untitled](https://cloud.githubusercontent.com/assets/4449742/14312312/e9763972-fc15-11e5-99a9-23f43ec40a21.jpg)
![untitled 2](https://cloud.githubusercontent.com/assets/4449742/14312315/ef9572dc-fc15-11e5-8855-c0c03b7497e7.jpg)
![untitled 3](https://cloud.githubusercontent.com/assets/4449742/14312319/efea7958-fc15-11e5-9dd9-ee4f53dc001a.jpg)
![untitled 4](https://cloud.githubusercontent.com/assets/4449742/14312316/efc8841a-fc15-11e5-842b-c10db58e640f.jpg)
![untitled 5](https://cloud.githubusercontent.com/assets/4449742/14312318/efe90f00-fc15-11e5-9f1d-0f65e29f41bf.jpg)

**Comment by willkuer** [comment]
Can you please check which version broke the game?

**Comment by n1dminhd** [comment]
Yes, sure
![untitled](https://cloud.githubusercontent.com/assets/4449742/14315000/f27fbfca-fc24-11e5-949d-98fa7d2579bc.jpg)

**Comment by n1dminhd** [comment]
1.5.0
Ok

1.5.0-268
Ok

1.5.0-336
Ok

1.5.0-546 ( New download + New Config (original Config))
Ok

but now with the old config, 1.5.0-546 still black screen

**Comment by n1dminhd** [comment]
I delete old config and config same old config
1.5.0-546 Ok
I still do not understand

**Comment by willkuer** [comment]
Well better to have no problem at all.

I guess your problem is thus not reproducible/fixed? If yes, you could close the issue.

**Comment by n1dminhd** [comment]
Ok
