### ISSUE TITLE
Valkyrie Profile 2 - In game has significantly blurry graphics.

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1282]
`Slackware64-Current`

`pcsx2-b8a023d_2016.04.05_master-x86_64-1_git`
`mesa-compat32-e09d04c_2016.02.21_master-x86_64-1_gitcompat32`
`xf86-video-nouveau-b824d36_2016.01.13_master-x86_64-1_git`

When trying to play `Valkyrie Profile 2` the opening cut scenes work flawlessly, but the in game is extremely blurry to the point that the game is not playable.

I have made a trace using apitrace showing the issue which has been reported to show the same with nvidia drivers, but it has also been suggested that pcsx2 may or may not be doing something that would result the issue being hardcoded into the trace?

http://ks392457.kimsufi.com/orbea/stuff/apitrace/PCSX2_Valkyrie_Profile_2.trace.xz

![1](http://i.imgur.com/BBQQ0WY.png)

**Comment by willkuer** [comment]
According to forum path of neo (matrix) has a similar issue and might be related. (Sw fixes the issue for matrix)

**Comment by orbea** [comment]
Yes, it seems sw is a work around, I will leave this open since hw is still broken. Thanks,

**Comment by gregory38** [comment]
Did you enable hardware depth and try several level of crc. The game uses a special effect to blur the screen.

**Comment by orbea** [comment]
I have `Full Depth Emulation` checked and have tried crc settings `none, 'partial' (My default), 'full' and 'aggressive'. None of it make a difference.

**Comment by willkuer** [comment]
Enable hw hacks + skipdraw = 100?

**Comment by orbea** [comment]
Yes, that works better, after some experimentation I found that just `Enable User Hacks` + skipdraw = 50 (or more) fixes the blurriness, however the Title / Chapter screen fails to display and the subtitles only partially render.

**Comment by willkuer** [comment]
Yes that's more or less expected. Maybe a crc hack can remove the blurriness or gregory fixes the next major glitch within two weeks...

**Comment by gregory38** [comment]
Hum, it feels like a regression. Did you enable upscaling ?

Could you 
* generate me a gs dump => http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
* test older version to ensure it is a regression (the best will be to find the bad commit).
* Post your GSdx.ini option

**Comment by refractionpcsx2** [comment]
did you try different levels of Accurate Blending? That makes a difference on VP2

**Comment by gregory38** [comment]
Maybe accurate date ? Nouveau doesn't support it yet.

**Comment by orbea** [comment]
`Accurate Date` makes no difference, I'm not sure if I should be able to, but I do not see any `Accurate Blending`.

* Here is a gs dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_Valkyrie_Profile_2.tar.xz
* If needed I will test older versions later today or if not that sometime this weekend when I have more time.
* Here is my GSdx.ini
```
MaxAnisotropy = 0
ModeHeight = 480
ModeWidth = 640
Renderer = 12
ShadeBoost = 0
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
TVShader = 0
UserHacks = 0
UserHacks_AlphaHack = 0
UserHacks_AlphaStencil = 0
UserHacks_ColorDepthClearOverlap = 0
UserHacks_DateGL4 = 0
UserHacks_DisableGsMemClear = 0
UserHacks_DisablePartialInvalidation = 0
UserHacks_HalfPixelOffset = 0
UserHacks_MSAA = 0
UserHacks_NVIDIAHack = 0
UserHacks_SkipDraw = 50
UserHacks_SpriteHack = 0
UserHacks_TCOffset = 0
UserHacks_WildHack = 0
UserHacks_align_sprite_X = 1
UserHacks_round_sprite_offset = 0
UserHacks_safe_fbmask = 0
UserHacks_unsafe_fbmask = 0
aa1 = 0
accurate_blending_unit = 1
accurate_date = 0
aspectratio = 1
capture_enabled = 0
capture_out_dir = /tmp/GSdx_Capture
capture_resx = 1280
capture_resy = 1024
capture_threads = 4
crc_hack_level = 2
debug_glsl_shader = 0
debug_opengl = 0
dump = 0
extrathreads = 6
fba = 1
filter = 2
fxaa = 0
interlace = 7
logz = 1
mipmap = 1
msaa = 0
nativeres = 1
ogl_texture_storage = 0
ogl_vertex_storage = 0
ogl_vertex_subdata = 1
override_GL_ARB_bindless_texture = -1
override_GL_ARB_buffer_storage = -1
override_GL_ARB_clear_texture = -1
override_GL_ARB_clip_control = -1
override_GL_ARB_copy_image = -1
override_GL_ARB_direct_state_access = -1
override_GL_ARB_draw_buffers_blend = -1
override_GL_ARB_explicit_uniform_location = -1
override_GL_ARB_gpu_shader5 = -1
override_GL_ARB_separate_shader_objects = 1
override_GL_ARB_shader_image_load_store = -1
override_GL_ARB_shader_subroutine = -1
override_GL_ARB_shading_language_420pack = -1
override_GL_ARB_texture_barrier = -1
override_GL_ARB_texture_storage = -1
override_GL_ARB_viewport_array = -1
override_GL_EXT_texture_filter_anisotropic = -1
override_geometry_shader = -1
paltex = 0
png_compression_level = 1
preload_frame_with_gs_data = 0
renderer = 13
resx = 1024
resy = 1024
save = 0
savef = 0
savel = 5000
saven = 0
savet = 0
savez = 0
shadeboost = 1
shaderfx = 0
shaderfx_conf = /home/orbea/dummy.ini
shaderfx_glsl = /home/orbea/dummy.glsl
texture_cache_depth = 1
upscale_multiplier = 1
vsync = 0
windowed = 1
```

**Comment by gregory38** [comment]
Which version of GSdx do you have? Could you try to delete you ini file ? And start with a fresh one. On latest version, you have an "Internal resolution" and a "Blending Unit Accuracy" combo box in the hardware mode settings.

Here the rendering on my computer. Right is the upscaled resolution.

![vp2](https://cloud.githubusercontent.com/assets/1569559/14359273/fa16969c-fcf0-11e5-979b-d4b5b38ebd3d.png)

**Comment by gregory38** [comment]
The issue appears when GL_ARB_shader_image_load_store isn't supported.

**Comment by gregory38** [comment]
Sigh, I'm feeling, I have lost 2 days to support oldies (aka missing of GL4 stuff). Anyway, I hope I didn't break anything. Just grab latest git.

**Comment by orbea** [comment]
Awesome, thanks! I updated to `pcsx2-17886a9_2016.04.07_master-x86_64-1_git` and now it works.

To answer the other questions, I do have those options now that you pointed them out, I was just not understanding and I have `GSdx (GCC 5.3.0, AVX) 1.0.0 [libGSdx-1.0.0]`.

**Comment by gregory38** [comment]
Yes, I know, Linux option names are slightly different.
