### ISSUE TITLE
Star Ocean - Unplayable stutter / lag

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1286]
```
Slackware64-current

pcsx2-17886a9_2016.04.07_master-x86_64-1_git
mesa-compat32-e09d04c_2016.02.21_master-x86_64-1_gitcompat32
xf86-video-nouveau-b824d36_2016.01.13_master-x86_64-1_git
```
When playing `Star Ocean: Till the End of Time` after the first cut scenes the game is unplayable due to a stutter or lag effect, controls are very slow to respond and the audio is glitched in a stop / start manner. This also occurs briefly when switching between cut scenes.

Here is a GS dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_Star_Ocean.tar.xz

The opengl sw renderer does not suffer from this issue, but is also very slow.
A work around is the `Skipdraw` hw hack, this resolves the issue with just a value of `1`. Higher values will result in the map and any other popup information not displaying correctly.

**Comment by gregory38** [comment]
Or try the full crc level

**Comment by willkuer** [comment]
Is this a performance issue and thus related to your pc?

What are ypour specs?

**Comment by orbea** [comment]
The full crc level also resolves it, I was using partial.

I'm not convinced this is a performance issue, I have  `GTX 780 Ti` card (Best performance for nouveau currently) and use the high pstate setting.

**Comment by FlatOutPS2** [comment]
Full CRC level solves the performance issues, but it removes some effects including shadows.

**Comment by gregory38** [comment]
Yes it will remove the shadow. Without nvidia driver and a 4ghz cpu it is a no go. 
The only way to emulate a effect (at full speed) will be a SW implementation on the GPU.

**Comment by orbea** [comment]
Unfortunately the nvidia driver has a multitude of unrelated issues and is ultimately less trust worthy than the less powerful nouveau driver. Certainly not something I want on my os. Is it possible to point out what specific ways mesa and / or nouveau could improve that would help PCSX2 work better?

**Comment by gregory38** [comment]
I understand the choice of mesa but the effect is awful to emulate for the driver. A faster driver will help (but honestly I'm not even sure it will be faster on nvidia driver). A GPU driver is a tons of work. It would need months/years of optimization. First step woull be to compare Nvdia vs Nouveau. If there a difference, profile mesa to find the issue.

Again the alternative is to bypass the standard gpu rendering pipeline and do our own render on the shader. Latest gpu allows it but someone need to code it. Besides it will be very heavy on the GPU.

**Comment by gregory38** [comment]
Same issue as #984 

I'm closing this bug (GPU limitation actually) as duplicate.
