### ISSUE TITLE
SPU2-X-dev windows build faild at vs2015 update 2

### ISSUE THREAD

**Issue by yxmline** [PCSX2/pcsx2#1288]
SPU2-X-dev windows build
Error LNK1295 "/ OPT: NOREF" and "/ LTCG: incremental" specifications are not compatible; do not use the link "/ LTCG: incremental"

**Comment by refractionpcsx2** [comment]
Good catch, fixed now :)

**Comment by willkuer** [comment]
Steps to reproduce?

**Comment by dukuo** [comment]
Basically tried to add `gl` to a project, and got stuck in rebuilding with node-gyp, with no luck.
