### ISSUE TITLE
GSDX: Custom Resolution and Texture Offset Issue on Linux

### ISSUE THREAD

**Issue by z1lt0id** [PCSX2/pcsx2#1292]
Hi guys,

Thanks for the great emulator - but I have to issues with the current Linux git build.
- Unlike the Windows version I can't seem to find an entry for custom resolution. It gives me the option to select a custom resolution but not state what the resolution is.  Here is the screenshot below.

![pcsx2-1](https://cloud.githubusercontent.com/assets/2316366/14507181/dcf7d8d2-0204-11e6-941d-c619245134c4.png)
- It seems I cannot save the offset hacks in GSDX.  For example if I input Xenosaga's recommended one 0000 1000 it does not save it at all.  I checked permissions and that isn't an issue, its the only thing that doesn't save when modifying the GSDX options on Linux.  Below is the screenshot.

![pcsx-2](https://cloud.githubusercontent.com/assets/2316366/14507207/ffc32420-0204-11e6-94c0-3227fbcdebf1.png)

I maybe just wasting your time, and I'm doing something wrong - if not I hope this submission helps.

**Comment by willkuer** [comment]
For tc offset: Have you tried 00001000? I think this is saved in a real odd way in the ini. Windows gui obviously looks different.

Gregory our current linux and gsdx dev doesnt like custom res upscaling. Possibly it is not implemented. You can check the ini as well. Why do you want to use custom res anyways? Upscaling multiplier is almost always better.

**Comment by z1lt0id** [comment]
@willkuer I tried inputting 00001000 in the dialog box but it didn't save - I'll try manually editting the ini files.  As for custom res - I was just trying to do it because there were some custom res recommendations to fix up certain issues in Xenosaga 2 (shadow issue?)

**Comment by z1lt0id** [comment]
A quick note I checked the ini file on the Windows build for 0000 1000 and this is what I got.
`UserHacks_TCOffset=65536000`

**Comment by gregory38** [comment]
Custom resolution is bad for plenty of reasons. I ought to remove it completely from the gui. The width and height can still be set in the ini. However maybe we could replace it with a spin box that continuously range from 1.0 to 8.0.
Anyway openGL linux is muc more accurate than Dx. The recommandation is likely bad.

For the tc offset, I need to double check it. Did you try to hit enter?

**Comment by gregory38** [comment]
And the ini likely contain a decimal value (not hex)

**Comment by willkuer** [comment]
The ini file seems to save a bit shifted value of the right number and the left value added. I saw that once in the code and was kind of confused why it was lile that. I think the readout of tjis value happens in os independent code. Thus you can just copy paste the value from windows.

These tc offsets were often used to remove upscaling issues. A lot of them were fixed using the align sprite hack (which you use). As said by gregory you possibly don't need the tc offset at all.

**Comment by z1lt0id** [comment]
@gregory38 @willkuer 
I'll take note of using the align sprite hack and see how it goes.  I did notice more accuracy in the opengl renderer especially when it come to post-processing effects.  I'll test it just using the sprite align hack and forget about the tc offsets.  And thanks for pointing out the custom res thing - I'll never touch that option.  

As for press enter - you know I never tried ;)

**Comment by z1lt0id** [comment]
@gregory38 @willkuer 
I'll take note of using the align sprite hack and see how it goes.  I did notice more accuracy in the opengl renderer especially when it come to post-processing effects.  I'll test it just using the sprite align hack and forget about the tc offsets.  And thanks for pointing out the custom res thing - I'll never touch that option.  

As for press enter - you know I never tried ;)

**Comment by z1lt0id** [comment]
@gregory38 @willkuer 
I'll take note of using the align sprite hack and see how it goes.  I did notice more accuracy in the opengl renderer especially when it come to post-processing effects.  I'll test it just using the sprite align hack and forget about the tc offsets.  And thanks for pointing out the custom res thing - I'll never touch that option.  

As for pressing enter - you know I never tried ;)

**Comment by z1lt0id** [comment]
@gregory38 @willkuer 
I'll take note of using the align sprite hack and see how it goes.  I did notice more accuracy in the opengl renderer especially when it come to post-processing effects.  I'll test it just using the sprite align hack and forget about the tc offsets.  And thanks for pointing out the custom res thing - I'll never touch that option.  

As for pressing enter - you know I never tried ;)

**Comment by z1lt0id** [comment]
@gregory38 @willkuer 
I'll take note of using the align sprite hack and see how it goes.  I did notice more accuracy in the opengl renderer especially when it come to post-processing effects.  I'll test it just using the sprite align hack and forget about the tc offsets.  And thanks for pointing out the custom res thing - I'll never touch that option.  

As for pressing enter - you know I never tried ;)

**Comment by z1lt0id** [comment]
So the OpenGL renderer on Linux seems to be having some issues. Windows OpenGL doesn't show the issues.  Both are running the latest git release.  Here are some screenies of Xenosaga 3 and the GSdx settings. As you can see the shadows are not rendering correctly. 
![xeno-1](https://cloud.githubusercontent.com/assets/2316366/14540616/41dc7fae-02c9-11e6-8f77-2c2304f17a43.jpg)

And here are the GSdx settings
![xeno-3](https://cloud.githubusercontent.com/assets/2316366/14540666/84ad8d46-02c9-11e6-8346-c9114292364a.png)
![xeno-4](https://cloud.githubusercontent.com/assets/2316366/14540671/8ab39730-02c9-11e6-9951-a4fb75bb0302.png)

**Comment by gregory38** [comment]
Gpu?  Drivers?

**Comment by willkuer** [comment]
Also possibly reducing the crc hack level to partial as some effects are removed by full.
It would be good to visit the forum though to get support. This place is more a bug tracker. The tc offset gui issue could indeed be a bug but if you now look for support for a specific game the forum will be more reasonable.

**Comment by z1lt0id** [comment]
No problems.
@gregory38 Nvidia GTX 970 - Nvidia blob 364.16

**Comment by z1lt0id** [comment]
In the end I just deleted the GSdx.ini file, reloaded up the plugin and chose the appropriate settings. Saved it, quit PCSX2 and edited the ini with the windows output for tc offset and it resolved the problem.
![fixed-xeno3](https://0x0.st/Zo2.jpg)

On saying that still had issues saving the tc offset from within pcsx2.

**Comment by gregory38** [comment]
tc offset work here if I press enter. (not ideal I know)

**Comment by z1lt0id** [comment]
I realised this some time after.  Maybe remove the need to press Enter though - seems rather counter-intuitive.

**Comment by gregory38** [comment]
Don't know if gtk support it (and I don't know how to do it neither). But patches are always accepted
