### ISSUE TITLE
[gsdx] SW StretchRect is buggy

### ISSUE THREAD

**Issue by clbr** [PCSX2/pcsx2#1295]
GSDeviceSW::StretchRect writes over the destination texture's bounds. I confirmed this in 1.4.0, but since the file hasn't been touched in git, the bug also affects git master.

This code reproduces it:
```
GSTexture *dst = dev->CreateTexture(640, 448);
GSTexture *src = dev->CreateTexture(640, 224);
dev->DoInterlace(src, dst, 3, true, 1);
```

valgrind log:
```
==13701== Invalid write of size 4
==13701==    at 0x4E89D20: GSDeviceSW::StretchRect(GSTexture*, GSVector4 const&, GSTexture*, GSVector4 const&, int, bool) (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E8930B: GSDeviceSW::DoInterlace(GSTexture*, GSTexture*, int, bool, float) (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E750B8: _GSopen(void**, char const*, GSRendererType, int) [clone .constprop.64] (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E7552D: GSopen (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x400683: main (in /tiedostot/mv/c/ps2plug/GSdx/app)
==13701==  Address 0xca40120 is 0 bytes after a block of size 1,146,880 alloc'd
==13701==    at 0x4C20BB9: memalign (in /opt/valgrind/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13701==    by 0x4C20C7C: posix_memalign (in /opt/valgrind/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13701==    by 0x4F10750: _aligned_malloc(unsigned long, unsigned long) (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4F00A39: GSTextureSW::GSTextureSW(int, int, int) (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E891E1: GSDeviceSW::CreateSurface(int, int, int, bool, int) (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E7507A: _GSopen(void**, char const*, GSRendererType, int) [clone .constprop.64] (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x4E7552D: GSopen (in /tiedostot/mv/c/ps2plug/GSdx/libGSdx-1.0.0.so)
==13701==    by 0x400683: main (in /tiedostot/mv/c/ps2plug/GSdx/app)
==13701==
```

**Comment by clbr** [comment]
The same applies to the non-linear codepath.

**Comment by gregory38** [comment]
A trace on dev build will be nice. (To have line number).

**Comment by clbr** [comment]
The line number is useless, because it points to the SW ShaderCopy line, as expected.

I have a partial fix: the SW texture map has a bug in the Map calculation with an offset. Patch:
http://pastebin.ca/3503462

**Comment by clbr** [comment]
Oh, it's actually complete, despite the comment about the linear path being buggy. This patch fixes both the linear and non-linear paths.

**Comment by gregory38** [comment]
Patch sound good. Could you open a PR. Thanks.

**Comment by clbr** [comment]
On limited internet right now, so can't fork+clone for a few days. Why not apply the patch with git am? It will use my details correctly, "git am foo.patch" in a pcsx2 dir.

**Comment by refractionpcsx2** [comment]
i think the idea of having a PR first is so we can test it before merging to make sure there's no adverse effects.  our system auto builds any PR's so they can be tested easily.

**Comment by willkuer** [comment]
Isn't it suprising that this was never found? I mean this pr makes a big difference...

**Comment by gregory38** [comment]
I can merge the pr from my phone whereas I need a physical acces to my computer to apply a patch. Besides I try it but it isn't as straigthforward as expected. Paths aren't good (maybe I need an option) and I have conflict (seems to be space diff). Anyway we can do it but it take more time.

**Comment by refractionpcsx2** [comment]
> Isn't it suprising that this was never found? I mean this pr makes a big difference...

do you know any games affected by this?

**Comment by willkuer** [comment]
No I don't. I just thought that if valgrind finds it it is not dead code. Might be wrong though. It just appears to me as a rather large change on the code level for the almost perfectly working sw renderer.

**Comment by refractionpcsx2** [comment]
There is a difference between a profiler finding a bug and games using it could mean that this will do very little to help.  Coverity found a ton of issues with PCSX2 which we know will never happen because we know games don't do it (or our code doesn't do it), so it probably won't actually affect anything.

That said, it doesn't mean it won't fix any bugs, not everything is perfect in software mode, so there is a chance this might happen sometimes.

**Comment by clbr** [comment]
All I needed to hit this bug was start the PS2 bios on a software
device. Nothing else, no games needed, but any interlaced game would
also have sufficed. It crashed pcsx2 instantly for me.

It doesn't affect the GL/DX devices, because those do deinterlacing in
hw. There might be other paths where this helps though.

@gregory
I made a pull request last night?

**Comment by gregory38** [comment]
Yep I saw it, but I still need to sleep ;) I merged your change. Let's hope it helps to fix some bugs.
