### ISSUE TITLE
build.sh can't find wxWidgets without -DwxWidgets_CONFIG_EXECUTABLE='/usr/bin/wx-config-3.0'

### ISSUE THREAD

**Issue by frantisekz** [PCSX2/pcsx2#1296]
Running `./build.sh --release --gtk3 --clean` results with cmake unable to find wxWidgets. Command .`/build.sh --release --gtk3 --clean -DwxWidgets_CONFIG_EXECUTABLE='/usr/bin/wx-config-3.0' ` works.

Fedora 24, cmake 3.5.1, wxGTK3-3.0.2

**Comment by gregory38** [comment]
So far PCSX2 will check
* /usr/bin/wx-config (debian)
* /usr/bin/wx-config32-3.0 (used to be the others)

I guess I can change the path for fedora 24...

**Comment by frantisekz** [comment]
File /usr/bin/wx-config32-3.0 doesn't exist on Fedora.

Anyway, I can't find out why it's broken in Fedora 24 compared to Fedora 23. I've browsed package git (https://pkgs.fedoraproject.org/cgit/rpms/wxGTK3.git/log/?h=f24) for changes compared to Fedora 23, but there are only fixes for Wayland and GTK 3.20.

**Comment by gregory38** [comment]
Could you try this patch http://pastebin.com/c9M9RYLZ

**Comment by gregory38** [comment]
same with a parenthesis fix http://pastebin.com/c9M9RYLZ

**Comment by frantisekz** [comment]
Yup, fixes this issue :)
