### ISSUE TITLE
Compilation broken with GCC6

### ISSUE THREAD

**Issue by frantisekz** [PCSX2/pcsx2#1297]
Compilation with GCC6 is not working. I've tried to disable simd (--no-simd) but result is same.
```
[  9%] Building CXX object common/src/Utilities/CMakeFiles/Utilities.dir/CheckedStaticBox.cpp.o
/home/fanys/pcsx2/common/src/x86emitter/cpudetect.cpp: In member function ‘void x86capabilities::SIMD_EstablishMXCSRmask()’:
/home/fanys/pcsx2/common/src/x86emitter/cpudetect.cpp:68:23: error: ‘_fxsave’ was not declared in this scope
  _fxsave(&targetFXSAVE);
                       ^
common/src/x86emitter/CMakeFiles/x86emitter.dir/build.make:86: guide for target „common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o“ failes
make[2]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o] Error 1
CMakeFiles/Makefile2:273: guide for target „common/src/x86emitter/CMakeFiles/x86emitter.dir/all“ failed
make[1]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/all] Error 2
```

**Comment by gregory38** [comment]
Could you grep -r _fxsave in /usr/lib/gcc ? (Or wherever your distrib put gcc include file)

**Comment by frantisekz** [comment]
```
/usr/lib/gcc/x86_64-redhat-linux/6.0.0/include/fxsrintrin.h:_fxsave (void *__P)
/usr/lib/gcc/x86_64-redhat-linux/6.0.0/include/fxsrintrin.h:  return __builtin_ia32_fxsave (__P);
/usr/lib/gcc/x86_64-redhat-linux/6.0.0/include/fxsrintrin.h:_fxsave64 (void *__P)
/usr/lib/gcc/x86_64-redhat-linux/6.0.0/include/fxsrintrin.h:    return __builtin_ia32_fxsave64 (__P);
```

**Comment by gregory38** [comment]
Hum, on debian I have a 32 bits include (by the way you can grep word with -w)
```
/usr/lib/gcc/i586-linux-gnu/4.9/include/fxsrintrin.h:_fxsave (void *__P)
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/fxsrintrin.h:_fxsave (void *__P)
```
Do you still have a gcc 5 install?

**Comment by gregory38** [comment]
well both files are the same here. Could you post the fxsrintrin.h file? Normally the file is included by `x86intrin.h`.  And enabled by the gcc option `-mfxsr`

**Comment by frantisekz** [comment]
> Do you still have a gcc 5 install?
No, that's not possible by default in Fedora - if I want multiple GCC's, I need to compile them and then set PATH to different gcc.

fxsrintrin.h - http://pastebin.com/wJENF7A3

Btw, I don't even have  /usr/lib/gcc/i686-redhat-linux/6.0.0/include/fxsrintrin.h on my system.

**Comment by gregory38** [comment]
Do you have this include /usr/lib/gcc/i686-redhat-linux/6.0.0/include/ path. The file seems to be normal. (aka no change).
Could you check your compilation flag ? You must have `-mfxsr` in some build_* files if you use --no-simd (otherwise it used to be enabled by default)

**Comment by frantisekz** [comment]
Directory /usr/lib/gcc/i686-redhat-linux/6.0.0/include/ doesn't exist. 
I have only 2 files in  /usr/lib/gcc/i686-redhat-linux/6.0.0 : libstdc++fs.a  libstdc++.so

> Could you check your compilation flag ?

I have found this: `CXX_FLAGS = -msse -msse2 -mfxsr -march=i686 -pipe -fvisibility=hidden -pthread -fno-builtin-strcmp -fno-builtin-memcmp -mfpmath=sse -Wall -Wno-attributes -Wno-missing-field-initializers -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value  -Wstrict-aliasing -Wstrict-overflow=2  -D_FORTIFY_SOURCE=2  -Wformat -Wformat-security -DNDEBUG  -O2   -std=c++11 -Wno-invalid-offsetof -pthread   -fno-strict-aliasing -Wno-parentheses -Wstrict-aliasing -Wno-char-subscripts -Wno-missing-braces  -fno-strict-aliasing -Wno-parentheses -Wstrict-aliasing -Wno-char-subscripts -Wno-missing-braces -DWX_PRECOMP`

**Comment by jcdenton2k** [comment]
I found something that might help, at least for Ubuntu:
http://askubuntu.com/questions/26498/choose-gcc-and-g-version

One needs to make sure that the distro is using the proper GCC and G++ versions when multiple versions are installed.  I'm not familiar with how other non-Debian distros will work on that issue.

I documented my results here in a non-pcsx2 context:
https://github.com/FreedomBen/rtl8188ce-linux-driver/issues/92#issuecomment-211112727

**Comment by frantisekz** [comment]
> I found something that might help

Thanks for help, but this issue is not about choosing different GCC version. It is solution to get pcsx2 compiled, but it's important to have working compilation under latest GCC - this can be achieved by reporting bug to GCC, which will probably take ages to solve or by fixing/modifying application itself.

This issue is not some top priority bug - as you have said, most distributions are using older GCC versions (even Fedora does so, I am running yet to be released Fedora 24).

**Comment by gregory38** [comment]
Could you try to add this line
```
#include "x86emitter/x86_intrin.h"
```
in top of common/src/x86emitter/cpudetect.cpp

**Comment by frantisekz** [comment]
Works with include added. Thanks

**Comment by Soukyuu** [comment]
I'm still getting this trying to build 1.4.0 on arch linux x64, even with `#include x86_intrin.h` or `#include x86emitter/x86_intrin.h` - there is also no x86_intrin.h on my system as far as I can tell. gcc-multilib 6.1.1

**Comment by Soukyuu** [comment]
nvm, apparently the code has changed much between 1.4.0 and current git master, so it's not trivial to just add the line - I will try getting the git snapshot to build instead.

**Comment by frantisekz** [comment]
@Soukyuu PCSX2 stable won't probably work with latest GCC unless @gregory38 decides to port fixes to stable and release point release.

I'd recommend you opening a new issue if you have issues with GCC 6.1.

**Comment by gregory38** [comment]
Yeah I did quite a good jobs :p
I don't have time to install gcc 6 on my debian system (still 4.9). But you're free to help us ;)

**Comment by Soukyuu** [comment]
The current git master compiles fine with 6.1.1, so I don't think there is anything to be done for an older stable version.

**Comment by gregory38** [comment]
@sergiomb2 thanks you for the patch. I pushed it in the 1.4 branch. Sorry for the delay, I just saw your patch due to another complain.
