### ISSUE TITLE
Jak series problems

### ISSUE THREAD

**Issue by TheJordanator** [PCSX2/pcsx2#1298]
Hi,

I am probably being a pain by opening an issue here about this but this is very important to me. I have been playing the Jak games since I was 4 and want to play them on my pc with a high resolution with not as many graphical errors.

Here are some problems for the series that haven't been solved:

**Jak and Daxter: The Precursor Legacy**
- Has eye problems. Interestingly, you can get one eye working right but not the other.

**Jak II**
- Has hair, skin, eyes, and shadow problem. - I did find a way to fix the shadows problem by using the alpha hack. (Shadows are not fixed in software mode)

**Jak 3**
- pretty much the same as Jak II but with a huge "missing" desert (looks black)

I really wish that I could play these games on the PC with a high res - I would love to just go and code a whole new plugin just for these games but sadly I am too dumb to do that. Please help.

**Comment by FlatOutPS2** [comment]
Issue already open here: https://github.com/PCSX2/pcsx2/issues/50

**Comment by gregory38** [comment]
Closed as duplicate.
