### ISSUE TITLE
"SLPS_257.18.GUNDAM SEED Destiny VS. Z.A.F.T Ⅱ PLUS" NOT RUN FROM v1.5.0-dev-561-g1208dbe

### ISSUE THREAD

**Issue by lantsing** [PCSX2/pcsx2#1300]
from v1.5.0-dev-561-g1208dbe ,"SLPS_257.18.GUNDAM SEED Destiny VS. Z.A.F.T Ⅱ PLUS" NOT run very well in gsdx-ogl

**Comment by refractionpcsx2** [comment]
I presume you are this guy? http://forums.pcsx2.net/Thread-Kidou-Senshi-Gundam-SEED-Destiny-Rengou-vs-Z-A-F-T-II-Plus-Black-Screen

Yeh anything after that will not work on your AMD GPU until AMD apply the fix they did about 3 months ago, it is still awaiting QA to go in to the driver. Stick to the old version until then.
