### ISSUE TITLE
 Aura for Laura by soopadoopa  missing effects

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1303]
PCSX2 version: GIT v1.5.0-dev-625-g87867be
 CPU options: EE/IOP defaults, VUs defaults
 Plugins used: GSdx GIT, SPU2-X GIT

http://www.pouet.net/prod.php?which=10435
source code is available from the site aswell

first couple of screens are missing the scroller in the middle of the screen
then the next couple of screen have a missing effect which is hard to describe

if you watch it on youtube and compare it you will see the difference
https://www.youtube.com/watch?v=PmsjaRriGt8

**Comment by willkuer** [comment]
Have you tried OGL with some hogher accuracy settings (blending, hw depth)?

**Comment by willkuer** [comment]
And what about sw mode (F9)?

**Comment by TheLastRar** [comment]
doesn't this freeze in hardware mode (at least in DX)?

**Comment by MrCK1** [comment]
Boots just fine in OGL besides the missing screens.

**Comment by FlatOutPS2** [comment]
Boots in both OGL and DX, is missing the scrolling bar & text, then crashes in both OGL and DX HW when the blocky object should appear before a landscapish background. You can see the background lanscape, but not the object."MyAssertion failed: next2<maxlev2  file:pixel.cpp , function:addpixel , line:152" is thrown in the log.
Missing text also occurs in software mode, but doesn't crash like Hardware modes.

**Comment by RedDevilus** [comment]
Still same result on the homebrew doing:
`MyAssertion failed: next2<maxlev2  file:pixel.cpp , function:addpixel , line:152`

**Comment by Mrlinkwii** [comment]
this seems not to freeze anymore in HW mode

**Comment by lightningterror** [comment]
Confirmed, looks good now.
