### ISSUE TITLE
 Funslower by soopadoopa demo black screen

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1307]
PCSX2 version: GIT v1.5.0-dev-625-g87867be
CPU options: EE/IOP defaults, VUs defaults
Plugins used: GSdx GIT, SPU2-X GIT

http://www.pouet.net/prod.php?which=3966
nothing but a black screen

**Comment by MrCK1** [comment]
Can't get this one to work at all.

**Comment by FlatOutPS2** [comment]
Doesn't seem to boot properly.
