### ISSUE TITLE
 Aftersun by Napalm demo black screen

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1308]
PCSX2 version: GIT v1.5.0-dev-625-g87867be
CPU options: EE/IOP defaults, VUs defaults
Plugins used: GSdx GIT, SPU2-X GIT

http://www.pouet.net/prod.php?which=8381
nothing but a black screen

**Comment by MrCK1** [comment]
I don't think there is anything that can be done here. This "demo" lacks a proper cdkey like a Sony licensed game would. If you really want to try this demo, I would recommend using your own console.

```
ExecutePs2GameDisk
cdvdReadKey(0, 0, 75)
(IsoFS) Block 0x10: Primary partition info.
(IsoFS) Filesystem is ISO9660
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\AFTERSUN.ELF;1
(SYSTEM.CNF) Software version = 1.10
(SYSTEM.CNF) Disc region type = PAL
(IsoFS) Block 0x10: Primary partition info.
(IsoFS) Filesystem is ISO9660
Initializing Elf: 5104874 bytes
ELF (cdrom0:\AFTERSUN.ELF;1) Game CRC = 0xEE066339, EntryPoint = 0x008DDDFC
CDVD.KEY = 00,00,00,00,00,04,05
cdvdReadKey(0, 0, 3075)
(IsoFS) Block 0x10: Primary partition info.
(IsoFS) Filesystem is ISO9660
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\AFTERSUN.ELF;1
(SYSTEM.CNF) Software version = 1.10
(SYSTEM.CNF) Disc region type = PAL
CDVD.KEY = 00,00,00,00,00,00,01
ReadKey failed

```

**Comment by FlatOutPS2** [comment]
Works fine here, both OGL and DX11, hardware and software modes.

**Comment by MrCK1** [comment]
Gave this a random go. Works for me as of latest git.

We can close this now.

**Comment by FlatOutPS2** [comment]
Does it still crash with v1.5.0-dev-625 or v1.4.0?

**Comment by MrCK1** [comment]
The program doesn't work on v1.5.0-dev-625 and v1.4.0. Both gave me a black screen.

**Comment by lightningterror** [comment]
Works fine on my end as well so I'll close this.
