### ISSUE TITLE
Previous WS Hack loaded still running after new Fast Boot

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1310]
When I load a game with widescreen hacks and then I play another game in **Fast Boot** => The code of the previous widescreen hack is still loaded when I play the new game !

The WS hack code should be clear when I start a new game because it seems to make games starting as a blackscreen when i play/change lot of games without exiting PCSX2.

It seems dangerous for PCSX2 to keep widescreen hacks for games that don't need them.

**Example :**
- I play Dragon Ball Z Budokai 2 (PAL) with 3 widescreen hacks from **GAMEDB**
- Then, I do another boot : Dragon Ball Z Budokai 2 (NTSC) with 0 widescreen hacks loaded but the 3 widescreen hacks from Dragon Ball Z Budokai 2 (PAL) are peviously loaded and it will fit **luckily** the NTSC version.

**Proof :**
**01) PAL Version loaded with Fast Boot [3 widescreen hacks]**
![zkztx8c](https://cloud.githubusercontent.com/assets/3964507/14828093/b1e5338e-0be5-11e6-96be-2c02caf420ce.png)

**02) Then NTSC Version loaded with Fast Boot [0 widescreen hacks]**
![ntsc](https://cloud.githubusercontent.com/assets/3964507/14828219/4ab44780-0be6-11e6-8694-a0610e1132ef.png)
_You'll see that the previous widescreen hacks are loaded on the NTSC version despite saying 0 ws hacks_

**Comment by Aced14** [comment]
FWIW, here's a quote of an old Google Code issue that goes into further detail:

> **Issue 1455: Switching ISOs re-applies first game's pnach(es) to second one...**
> Reported by @Aced14, Dec 23, 2013
> 
> * Status: Accepted
> * Owner: ----
> * Type-Defect
> * Priority-Medium
> 
> 
> **1) Did the game ever work correctly (i.e. not have this problem) on the Official PCSX2 build or an earlier version of PCSX2 playground?
> (If so, please specify the latest pcsx2-playground or Official revision that last worked.)**
> N/A
> 
> **2) What steps will reproduce the problem?**
> 1. Launch PCSX2.
> 2. Enable pnaches via "System - Enable Cheats" and/or "System - Enable Widescreen Patches".
> 3. Go to "CDVD - ISO Selector - Game A" (i.e. any game that has cheats and/or widescreen patches available for it).
> 4. Go to "System - Boot CDVD (fast)".
> 5. Wait for game A to start up.
> 6. Go to "CDVD - ISO Selector - Game B" (i.e. a different game - doesn't matter if cheats/widescreen patches aren't available for it).
> 7. In the "Confirm ISO image change" window, click the "Reset" button.
> 8. Depending upon how much game A's pnach hacks interfere with it, game B will potentially run in a very unstable fashion.
> 
> **3) What exactly happens when you experience this issue (listing any console errors or screen output you receive)?**
> Upon switching from game A to game B, PCSX2 won't cease repeatedly writing game A's pnach hacks into memory until shortly after game B has launched. As a result, if any of game A's pnach hacks correspond to addresses used by game B to store its own ELF's MIPS instructions, game B will become unstable (triggering console errors, crashes, etc).
> 
> **4) What version of PCSX2 are you using? On what operating system? Plugins?**
> * PCSX2 Version: R5766
> * OS: Windows 7 Ultimate SP1 (64-bit)
> * Plugins: Defaults
> 
> **5) Please provide any additional information below.**
> * If game A is shut down (via "System - Shutdown") before switching the ISO to game B and fast booting it, this issue won't occur. Only the "fast" way of switching between games is affected.
> * Feel free to use something like Cheat Engine to observe one of the addresses from game A's pnach(es). For example, try launching games A and B separately with pnaches disabled, and note down the values that are normally stored in that address by each game. Then, repeat item 2)'s steps to observe what's happening. So long as game B's game engine doesn't overwrite that address in live memory, game A's pnach value will remain in that address once game B is "fast" switched to.
> * If needed, I could provide a really concrete example of this in two specific games.
> 
> **6) Attachments.  *IMPORTANT!*  We have a limited storage quota on GoogleCode, so please keep attachments to UNDER 200k!  Do not upload blockdumps!  Do not upload MP3 dumps or screenshots in BMP format.  Try to use 3rd party image hosts for screenshots when possible.**
> N/A
> 
> Reply 1 by @ramapcsx2, Dec 23, 2013
> Thanks for the report. This could be a bit tricky to fix, could be just an oversight too though :p

**Comment by avih** [comment]
Can someone ( @Aced14 ?) please check if this is now fixed with the recent commits? Are there any related remaining issues?

**Comment by Aced14** [comment]
@avih From what I can tell, 56adb85a87c763f078b57f395cdf8fc60917ca32 has completely fixed this issue :).

I came up with a quick test involving widescreen patches that used to lead to failure in older builds. In 093704f0738a42425dc9e5592195966671350662, if I fast boot War of the Monsters, then fast switch to Twisted Metal: Head-On - Extra Twisted Edition, the latter game crashes and causes various log errors to appear. None of those issues occur anymore in 56adb85a87c763f078b57f395cdf8fc60917ca32.

**Comment by avih** [comment]
Nice. Glad to hear.
