### ISSUE TITLE
Weird Double Full Boot Crash

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1311]
**Build :** Latest
**Steps :**
01) Booting Dragon Ball Z Budokai 2 (PAL) Full Boot (I'm in game menu)
02) Then booting Dragon Ball Z Budokai 2 (NTSC) or any game in full boot will crashs PCSX2 like that :
![j8feqnq](https://cloud.githubusercontent.com/assets/3964507/14829001/b5977556-0be9-11e6-8ce8-5e58704eb03d.png)

When I do the NTSC (Full Boot) first then the PAL release (Full Boot), I don't have this issue.

**Comment by FlatOutPS2** [comment]
Have you tried full booting to other games from Budokai 2 PAL?

**Comment by Catarax** [comment]
After Budokai 2 (PAL) in Full Boot, all PAL/NTSC games crashs in Full Boot.

**Comment by turtleli** [comment]
Has this issue been resolved?

**Comment by lightningterror** [comment]
Tested it, didn't experience the mentioned issue after several attempts.
Closing.

Could be some Emulation settings you probably forgot to change back.
