### ISSUE TITLE
Silent Hill: Shattered Memories Fast Boot Issue

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1324]
-PCSX2 version: v1.5.0-20160429001616

-PCSX2 options: Fast Boot.

-Plugins used: Defaults

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: Fast Boot causes Kaufmann to not appear during the initial interview.
FlatOut edit: This likely only affects the NTSC-U version of the game.

-How to replicate: Boot game in Fast Boot Mode, and watch/skip your way to scene where he greets you with "I'm glad you came."

-Last known version to work: Never worked, AFAIK.

-PC specifications: CPU: Intel Q9400z GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit

![gsdx_20160423180712](https://cloud.githubusercontent.com/assets/10704701/14933214/a66cf70c-0eca-11e6-8780-3fe197785861.png)

**Comment by prafullpcsx2** [comment]
He does appear in SW mode whether you use fast boot or full boot.

**Comment by FlatOutPS2** [comment]
Tested with latest git. He always shows up in HW mode too.

**Comment by prafullpcsx2** [comment]
AFAIK he doesn't appear in HW mode unless we use skip draw = 1.

**Comment by FlatOutPS2** [comment]
The only non-default setting I used was scaling to 2x. He appeared with both OGL and D3D.

**Comment by prafullpcsx2** [comment]
Tried every setting and he still doesn't appear in HW mode :D 

Even tried a totally fresh install. Mine is NTSC version if that makes any difference. :P 

May be a it's a rare windows driver related issue.

**Comment by FlatOutPS2** [comment]
> Mine is NTSC version if that makes any difference. :P

I'm guessing that it does. I'll reopen and add that this is likely a NTSC-U only issue.

**Comment by themanwiththeplan911** [comment]
tried both Software and HW(OGL) and it works fine on latest git on the NTSC-U game
![1](https://user-images.githubusercontent.com/75482550/101175325-b4490c80-364d-11eb-9f66-b949a1542dd5.jpg)

**Comment by refractionpcsx2** [comment]
Thanks for the update :)
