### ISSUE TITLE
Silent Hill: Shattered Memories Cutscenes Berserk.

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1325]
-PCSX2 version: v1.5.0-20160429001616

-PCSX2 options: Full Boot Mode.

-Plugins used: Defaults

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The cutscene where Harry wakes up from the car crash runs extremely fast and Harry freezes after a few seconds, "floating" into position.

-How to replicate: Boot game in Full Boot mode, skip cutscenes, and answer the form and question(s).

-Last known version to work: Never worked. In 1.2.1, even the first cutscene with Kaufmann was affected.

-PC specifications: CPU: Intel Q9400z GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit

**Comment by FlatOutPS2** [comment]
Timing issues cause missing audio, broken physics, especially during cutscenes.

Start the game with framelimiter set to Max or Turbo. The first cutscene after the FMVs the NPC will be silent, and will float towards his seat. Setting framelimiter to normal reduces risk of issue. Second cutscene issue described above seems to always happen even with normal framelimiter.

According to [this](https://forums.pcsx2.net/Thread-Silent-Hill-Shattered-Memories-bugs-are-back
) forum thread the "INTC Spin Detection" speedhack used to resolve this some 8 years ago. This no longer works.

**Comment by refractionpcsx2** [comment]
Is this still an open issue? there was mention in the above PR that it improves this issue. Can you double check it on the latest development builds?

**Comment by themanwiththeplan911** [comment]
The NTSCU game runs almost properly if you enable Fast Texture Invalidation and set DELAY_CYCLES to 0 in SPU2.ini for some weird reason PAL is unaffected you can easily run it without Fast Texture Invalidation or Delay cycles but the flashlight is still broken on both it's a common issue with these games PPSSPP also exhibits it on both Climax Silent Hill games
likely related to Silent Hill origins (https://github.com/PCSX2/pcsx2/issues/2732) it has a similar issue with the flashlight where anything that the flashlight touches breaks and Fast Texture Invalidation somewhat helps 
![1](https://user-images.githubusercontent.com/75482550/101164471-ba36f180-363d-11eb-944b-e455f814cd14.jpg)

**Comment by refractionpcsx2** [comment]
Delay cycles no longer does anything on new master builds.

**Comment by themanwiththeplan911** [comment]
> 
> 
> Delay cycles no longer does anything on new master builds. But I'll mark this appropriately for the flashlight issue.

You're right i guess tho i think this issue should be closed and the flashlight issue moved to https://github.com/PCSX2/pcsx2/issues/1326 since there doesn't seem to be any speedups or weird timing issues anymore and that thread is more appropriate

**Comment by refractionpcsx2** [comment]
Ah, didn't realise there was already a related issue, I'll close this then :)  Do you want to mention the flashlight in that one?
