### ISSUE TITLE
Ghost in the Shell: Stand Alone Complex Post-Processing Issue

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1327]
-PCSX2 version: v1.5.0-20160429001616

-PCSX2 options: Defaults.

-Plugins used: Defaults

-Plugin settings: CRC Hack Partial.

-Description: Game uses some sort of post-processing effect for bloom, which is broken in all HW modes, and seemingly always has been. Was previously bypassed with CRC hack, but said Hack isn't part of Partial hack level.

HW
![gsdx_20160430122041](https://cloud.githubusercontent.com/assets/10704701/14933345/0afdb1ae-0ece-11e6-80c1-1b2753977dc7.png)
SW
![gsdx_20160430122050](https://cloud.githubusercontent.com/assets/10704701/14933347/10f83372-0ece-11e6-8b9d-7fff51a2aeaa.png)

Returning to HW leaves a burnt-in image of the bloom from the lights. Disappears when camera is moved.
![gsdx_20160430122053](https://cloud.githubusercontent.com/assets/10704701/14933348/17f4f566-0ece-11e6-93fa-bde6237e11b2.png)

-How to replicate: Play any part of the game with CRC Hack level lower than Full.

-Last known version to work: Never worked.

-PC specifications: CPU: Intel Q9400z GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit

**Comment by gregory38** [comment]
Please test #1322

**Comment by AmbientMalice** [comment]
>Please test #1322

No improvement.

**Comment by FlatOutPS2** [comment]
The pattern on screen looks a lot like the Ridge Racer V ingame intro.

**Comment by gregory38** [comment]
It look like the channel effect. But maybe a small variation of it.

**Comment by gregory38** [comment]
Could you generate me a gsdump
http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by AmbientMalice** [comment]
Here's a gsdump.

http://s000.tinyupload.com/?file_id=85369668738610385434

**Comment by MarcoEstevez** [comment]
Looks similar to the problem with Ridge Racer V

![image](https://cloud.githubusercontent.com/assets/3447089/14942384/ba0f9804-0fbb-11e6-8bbf-20641dae0850.png)

**Comment by gregory38** [comment]
The game seem to use the effect but differently. I need to debug properly. I will restore the CRC level for this game.

**Comment by MarcoEstevez** [comment]
For Ridge Race V, I saw you have Included on Master ticket #1318, you want me to post GS Dump, or create a separate Issue for that. This game had always suffer 3 kind of problems, FMV doesn't render on HW mode (see previous screen shot), SW is fine, cars textures are misplaced only on HW mode, software one renders it fine, and "under cars shadows" renders flat-white color no matter actually SW, HW or any backend you use.

**Comment by gregory38** [comment]
I'm fine. I've a couples (4-5) of dump to analyze. Currently I'm working only on the channel effect, it is already complicated enough. Bug seems to the same as Ghost in the Shell. So I will fix my current dump and then we will check Ridge Race V.

**Comment by MarcoEstevez** [comment]
Sure, and thanks for your amazing work.

**Comment by FlatOutPS2** [comment]
> Looks similar to the problem with Ridge Racer V

That's what I posted a day earlier. :S

**Comment by MarcoEstevez** [comment]
True, I did not read all thread until today  :P

**Comment by gregory38** [comment]
I analyzed the rendering engine of Ghost In the shell. So here a summary
```
foreach page of the rt do
      // Note: some channel effects require 2 draws instead of 1, I don't know why
      channel effect red to tmp_page_0
      channel effect green to tmp_page_1
      channel effect blue to tmp_page_2
      // Then copy the tmp data to the RT (done with 3 draw calls)
      rt_page_N = Frag_Color_0 * tmp_page_0 + Frag_Color_1 * tmp_page_1 + Frag_Color_2 * tmp_page_2
end foreach
```
Could someone give me a dump of Ridge Racer V. So I can try to find a solution that work for both.

**Comment by MarcoEstevez** [comment]
At work atm, but I'll provide one as soon as reach home.

**Comment by FlatOutPS2** [comment]
Ridge Racer V dump:
[Ridge Racer V.zip](https://github.com/PCSX2/pcsx2/files/246636/Ridge.Racer.V.zip)

**Comment by IceLancerSR** [comment]
I tried this vs dev-867 it doesnt happen
tried dx with partial crc and full crc, tried opengl with partial crc , screen seems fine
besides the obvious upscaling lines
http://imgur.com/xVLazpQ

**Comment by gregory38** [comment]
CRC hack was restored. So yes it is "fine" now. But I would love to find a way to fix it properly.

**Comment by AmbientMalice** [comment]
@IceLancerSR The basic problem is bloom effects are missing.

**Comment by IceLancerSR** [comment]
@AmbientMalice bloom? ah u mean light surrounding? thats not bloom :-/ 
then that is what is flashing in bottom right corner, the light that was suppose to surround object including weapons fire
lightn when shooting
http://imgur.com/iF6MtJq
http://imgur.com/sMhaK6x

**Comment by ivan89el** [comment]
It was possible to configure Ghost in the Shell: Stand Alone Complex with all the effects (almost) in the hardwar:
In GSdx.ini UserHacks_SkipDraw=1287 crc_hack_level=0 UserHacks=1 for high internal resolution Userhacks_align_sprite_X=1
You must use Opengl (hardware) renderer
The absence of shadows (even in software) can be cured by opening GameIndex.dbf with a text editor and deleting the line: patch = 0, EE, 001B0A3C, word, 48468800﻿
Sorry my english

**Comment by lightningterror** [comment]
@ivan89el can you provide me a gs dump ? I'll take a look at it.

**Comment by ivan89el** [comment]
GITS dump:
[GS.zip](https://github.com/PCSX2/pcsx2/files/1673572/GS.zip)
Rename GS.zip in GS.7z

**Comment by ivan89el** [comment]
@lightningterror
Build 2391 + only dx9 + Frame Buffer Conversion: 
There was a red transparent image 
http://fastpic.ru/view/105/2018/0528/_020bab646872eb330dfc73dbb8a28003.png.html

**Comment by lightningterror** [comment]
The game should run better on latest dev builds since the crc hack and the gamefix patches have been adjusted to add a few extra post processing effects to work.

Everything else it's up to Gregory to work his magic :smile: 
Closing this one since we have a meta issue already.
