### ISSUE TITLE
Haunting Ground HW Rendering Issues

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1328]
-PCSX2 version: v1.5.0-20160429001616

-PCSX2 options: Defaults.

-Plugins used: Defaults

-Plugin settings: CRC Hacks Off. No other settings make any difference. Preload hack fixes missing body textures, but that is another issue.

-Description: Game has some advanced visual effects that are completely absent in HW mode. Also, shadows occasionally flicker with black lines between the ground and your character.

SW Mode
![gsdx_20160430110523](https://cloud.githubusercontent.com/assets/10704701/14933450/12229c56-0ed3-11e6-8747-b5141cc3f4b3.png)

HW Mode
![gsdx_20160430110527](https://cloud.githubusercontent.com/assets/10704701/14933456/3a3d41c8-0ed3-11e6-9186-ba4d07e9dd82.png)

gsdx_20160430122053

-How to replicate: Play any part of the game with CRC Hack level lower than Full.

-Last known version to work: Never worked.

-PC specifications: CPU: Intel Q9400z GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit

**Comment by tabnk** [comment]
Awaiting a fix on post processing effect before start to play this game

**Comment by gregory38** [comment]
I made a change that could improve a bit the blooming. Only tested on my dump. Require at least CRC to minimal, and I think the game requires accurate blending to at least minimal.

I'm pretty sure that various post-processing effect are still bad. But a status would be nice.

**Comment by gregory38** [comment]
Hum, you might need preload hack. It is working on my side because RT is cleared on debug build.

**Comment by gregory38** [comment]
New git version that will avoid the bloom effect. You need to set hack on the minimum level (not less, not more)

**Comment by tabnk** [comment]
CRC at Partial.

Bloom and shadow effects are back :)

**Comment by jcdenton2k** [comment]
If this works, please add it by default to the GameDB as an automatic fix :)

**Comment by lightningterror** [comment]
I'll close this since a TC workaround is present if crc is at least minimum.
If it doesn't work then the crc id is likely missing.
