### ISSUE TITLE
Flashback 0.18.1 black screen

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1334]
PCSX2 version: GIT v1.5.0-dev-684-g6b5761d 	
CPU options: EE/IOP defaults, VUs defaults
Plugins used: GSdx GIT, SPU2-X GIT

*removed*

no matter if you choose to load the iso or elf nothing but a black screen

**Comment by refractionpcsx2** [comment]
That is copyrighted works, we will not help with piracy or illegal copies of games.

**Comment by benderscruffy** [comment]
that is not copyrighted work you fool
they are freely available on the site and so is the source code 
read the the readme aswell
what an idiot

**Comment by ssakash** [comment]
Flaming the developers isn't the right way to prove your point. 

Please make a new issue with more detailed information and by providing the content of the Emulog when you reproduce the issue. I'm not sure what copyrighted material you're talking about but if it isn't one then please also provide relevant material backing up your claim, thanks.  Though I highly suggest you make a bug reprt at our forums instead.
