### ISSUE TITLE
MGS3 shadow arounds objects when using native resolution>x1

### ISSUE THREAD

**Issue by ntelalis** [PCSX2/pcsx2#1336]
PCSX2 Version: 1.5.0 2-5-2016
PCSX2 Options: Defaults using OpenGL (Hardware),CRC Hack Level Partial

Mgs3 works great in OpenGL(Hardware) (sun effects,codec calls) with the latest changes but there is an issue when rendering the game above native resolution (x2,x3,custom,etc no difference). There seems to be some kind of shadow around all objects making the image kinda "blurry".

Screenshots

x2 (easy to see around snake)
![](http://i.imgur.com/cGHRuvI.jpg)

x1 working as intended
![](http://i.imgur.com/4AbXFaW.jpg)

Another one
x2
![](http://i.imgur.com/tjJHvmT.jpg)

x1
![](http://i.imgur.com/FEzXNqJ.jpg)

**Comment by ssakash** [comment]
Did you try Half-pixel offset hack ? Maybe also worth to check with other hardware hacks intended for fixing upscaling bugs.

**Comment by ntelalis** [comment]
Half-pixel offset hack fixes the issue. Thanks
