### ISSUE TITLE
Persona3: Flashing / strobing windows

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1342]
OS: `Slackware64-current`
`pcsx2-7c430c9_2016.05.04_master-x86_64-1_git`
`GSdx (GCC 5.3.0, AVX) 1.1.0 [libGSdx]`
`mesa-compat32-cf6dadb_2016.04.27_master-x86_64-1_gitcompat32`

I noticed a graphical issue in one area of `Shin Megami Tensei: Persona 3` (Second floor of the school) where all the windows on the upper walls will flash or strobe as the camera angel is changed.
I am not sure if this is an mesa, pcsx2 or an issue with the game itself.

What I have tried:
- Only occurs with the OpenGL Hardware renderer not software.
- Changing CRC levels does not make a difference.
- Skipdraw and other hacks also does not make a difference.

One way to retest this is to replay this trace made by apitrace with `apitrace replay Persona3_PCSX2.trace`.
http://ks392457.kimsufi.com/orbea/stuff/trace/Persona3_PCSX2.trace.xz

Here is a log of the apitrace replay output which may be useful.
http://ks392457.kimsufi.com/orbea/stuff/trace/logs/Persona3_trace.txt.xz

Here is a GS dump.
http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_Persona3.tar.xz

And a savestate for the area with the issue.
http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/sstates/SLUS-21621%20(970A1593).01.p2s.xz

**Comment by gregory38** [comment]
First, please test the rendering with GSdx SW renderer. If the rendering is correct, I will need multi frame gs dump to debug it (http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) and please do a basic xz of the gs file (not a tar gs of a directory, it would save me the conversion)

**Comment by orbea** [comment]
I did test the SW renderer, it does not occur there and only occurs with the HW renderer.

Here is a multi frame gs dump.
http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_Persona3_multi.tar.xz

**Comment by lightningterror** [comment]
@orbea what is the status on this, the links don't appear to work so I can't check.

**Comment by orbea** [comment]
@lightningterror Unknown, that server is long dead so the links are unfortunately broken and I don't have a convenient save to test easily. I'm not sure I can test soon, but I'll try starting a new save sometime to find out.

**Comment by lightningterror** [comment]
Needs basic mipmap, will need to automatic mipmapping soonish.
I reproduced the issue on sw render too without mipmapping.

**Comment by i30817** [comment]
> But I couldn't find any way of fixing the map offset without also causing problems with character portraits and there's **still misalignment when the portraits animate (blink),** so software is probably still the way to go for this game.


Just FYI, P3P in the PPSSPP had the same problem so the cause may be similar. Check around its issues.
