### ISSUE TITLE
[AMD GPU] Serious graphics problems all games opengl-hw recent builds

### ISSUE THREAD

**Issue by wingedonezero** [PCSX2/pcsx2#1343]
There's a bug that was only recent in newer builds. i Used to have blending accuracy on high and everything worked fine but now sometime since build pcsx2-v1.5.0-dev-511-gf1b3d7d. i cant play any games really unless i put it on ultra and that makes it painfully slow So i know for sure there is a error there because it used to work just fine until recently. I have a 8350fx and a 7970 xfx card all drivers up to date as well. ill post images as well of what all games do now on the newer builds unless i go ultra.
![blending unit error](https://cloud.githubusercontent.com/assets/15163316/15034225/57358418-1241-11e6-9688-b9b2bac11577.png)
![ultra](https://cloud.githubusercontent.com/assets/15163316/15034227/5a0b3192-1241-11e6-9019-2bed978dc842.png)

**Comment by wingedonezero** [comment]
![khtest](https://cloud.githubusercontent.com/assets/15163316/15034323/57718836-1242-11e6-9700-93537ae8b10b.png)

**Comment by wingedonezero** [comment]
Ive narrowed it down to somewhere in between these builds the problem is
v1.5.0-dev-569-gb9e8384 	Gregory Hainaut 	2016-04-07 22:29:35 	Download 	gsdx-ogl: move the mandatory extension into mandatory section
v1.5.0-dev-568-g121e92a 	Gregory Hainaut 	2016-04-07 22:28:11 	No build 	gsdx ogl: remove a now useless warning message
v1.5.0-dev-567-g4475c4f 	Gregory Hainaut 	2016-04-07 22:27:33 	No build 	gsdx linux: remove the old extension options
v1.5.0-dev-566-gcef76de 	Gregory Hainaut 	2016-04-07 22:24:12 	No build 	gsdx ogl: GL_ARB_direct_state_access is now mandatory
v1.5.0-dev-565-ga62019a 	Gregory Hainaut 	2016-04-07 22:17:22 	No build 	gsdx-ogl: found_GL_ARB_buffer_storage is now mandatory
v1.5.0-dev-564-g52e3c35 	Gregory Hainaut 	2016-04-07 22:11:35 	No build 	gsdx-ogl: GL_ARB_separate_shader_objects is now mandatory
v1.5.0-dev-563-gf751f70 	Gregory Hainaut 	2016-04-07 21:57:54 	No build 	gsdx ogl: GL_ARB_clip_control is now mandatory
v1.5.0-dev-562-gdfb4b5a 	Gregory Hainaut 	2016-04-07 21:51:37 	No build 	gsdx-ogl: GL_ARB_texture_barrier is now mandatory (GL4.5 extension)
v1.5.0-dev-561-g1208dbe 	Gregory Hainaut 	2016-04-07 21:46:42 	Download 	cmake: add an option to build the new legacy GSdx plugin + bump the new one to 1.1.0 (to ease reporting)
v1.5.0-dev-560-g8751203 	Gregory Hainaut 	2016-04-07 21:27:55 	No build 	fork GSdx into a GSdx_legacy plugin

**Comment by wingedonezero** [comment]
build v1.5.0-dev-559-g8ccdc05 does not have issue but v1.5.0-dev-569-gb9e8384 does and there are no builds in between for me to test further.

**Comment by wingedonezero** [comment]
![settings](https://cloud.githubusercontent.com/assets/15163316/15034581/fc03e7ca-1244-11e6-9885-6f354d4c39ce.png)

**Comment by wingedonezero** [comment]
those are the settings i use pretty basic and easy to reproduce ive tryed it on another of my pcs as well.

**Comment by okamiterasu** [comment]
That's a driver issue that was being worked around until 564. A real fix for it is supposed to be in the next driver release, so use an older build until then.

**Comment by wingedonezero** [comment]
Ok  thanks for the reply do you have a link to the info on the driver? Or what causes the problem so i know what to keep an eye out for.

**Comment by gregory38** [comment]
https://community.amd.com/thread/194895

**Comment by gregory38** [comment]
Meanwhile, I added a hack to latest git to reduce the broken level. But keep in mind that some rendering effect will still be broken. I can't do more without a working driver.

**Comment by wingedonezero** [comment]
Thanks for the info gregory38. That work around works better than before but i think its safer to stick with the older build for now. But now i know what to look for on the driver changelogs. Thank you for doing what you can for the time being to make it not so bad. Its weird from what i read the opensource linux drivers don't have those issues you would think they would see that and fix it right away,

**Comment by gregory38** [comment]
Open source got others issues. I send them some patches to fix a couple of them (I'm the one that mostly implemented the extension on mesa.). Others user/dev fix remaining one.
The major difference is that it doesn't take 4 years to fix the free driver but only 2 months.

**Comment by Dokman** [comment]
amd sucks...

**Comment by gregory38** [comment]
Yes better keep an older build for a couple of months.

**Comment by wingedonezero** [comment]
Ive noticed they seem to have stepped their game up on the open source drivers. It be nice if there was a gui to configue it though but that will prolly never happen though. But yea sticking with a older build is what ill do until then. Not a big deal most people use the stable version anyways.

**Comment by gregory38** [comment]
```
Ive noticed they seem to have stepped their game up on the open source drivers
```
What do you mean? Any source?

The open source driver works very well. No bug and full feature even for old iGPU like Sandy Bridge.

**Comment by NukeMania** [comment]
you are wrong AMD has release new beta for ubuntu and rc1 for steamos it's not catalyst but still proprietary driver

**Comment by gregory38** [comment]
Oh! They remove fglrx from debian. Well I think a proprietary high level driver still exists. But let's be honest this stuff is more or less dead. Default install will be Mesa. And most users will keep it. The proprietary driver will exist for pro applications.

**Comment by mirh** [comment]
AMDGPU is the [closed-open hybrid] continuation of fglrx, but it's not like it won't be updated and hopefully fixed. 
Did somebody test it?

**Comment by gregory38** [comment]
Googling a bit, I think it is named AMDGPU-PRO. But honestly I expect most AMD's user to switch to Mesa. There are too much issue with proprietary driver. And Mesa is working fine with PCSX2.

**Comment by NukeMania** [comment]
AMDGPU-PRO's 
vulkan part is good state but opengl part is coming  from fglrx you know what it is like

**Comment by mirh** [comment]
The issues they had with the former proprietary driver are exactly the reasons they now reinvented the wheel. 
I believe they should also star to share more code with windows one

**Comment by gregory38** [comment]
Hum the issue is that people will want to install a vulkan ready driver (even for no/single application).
```
 I believe they should also star to share more code with windows one
```
I don't know if they share code but they share bugs :p

**Comment by mirh** [comment]
Yes, sorry. 
With that, *I meant* that I'm looking forward to them starting to finally give some fuck to linux driver too. If I can explain :s

**Comment by TacoDeBoss** [comment]
Sorry to bump the thread, but... This is still a problem (on Windows) on AMD Radeon Software 17.2.1. Perhaps it's re-emerged, I don't think I had this problem on older 16.x.x Windows drivers.

**Comment by TacoDeBoss** [comment]
Confirmed, Radeon Software 16.12.2, Driver Version 16.50.2011-161223a-310011C doesn't have this problem.

I guess I need to figure out if I can submit a bug report to AMD.

**Comment by gregory38** [comment]
Oh you did notice it too https://community.amd.com/thread/205702
Pick your choice
* They doesn't care about their driver/users/OpenGL
* They break it on purpose to keep a low end segment
* They suffer of color blindness

So you have 3 possibilities
* Complain on the above thread
* Complain on Youtuber/Twitter AMD reviewer/vendor]
* Open an issue on Khronos CTS so they include/adapt the test from https://community.amd.com/message/2716352 in their conformance test suite. It will give AMD choice to either drop OpenGL 4.4/4.5 or fix their driver.

**Comment by TacoDeBoss** [comment]
@gregory38 Geez, what a mess. I'll look into it, thank you. Luckily, everything's working fine on Linux but the GSDX seems to be older so it's missing post effects on MGS3, my favorite game. Oh well.

**Comment by gregory38** [comment]
There is a daily PPA on Linux. Check pcsx2.net download section.

Note: I'm working with Mesa's dev so hopefully the next Mesa release will give you a speed boost.

Meanwhile, I will blacklist the AMD driver. I'm too busy with real issue and life.

**Comment by TacoDeBoss** [comment]
I'm already using the PPA, a build from 22 hours ago. Unfortunately, the Linux GSDX just doesn't seem to be up to par with the Windows one, so there's missing effects in MGS3.

Good to hear there may be a speedup in the future, too. :)

**Comment by gregory38** [comment]
```
 Unfortunately, the Linux GSDX just doesn't seem to be up to par with the Windows one, so there's missing effects in MGS3.
```
Are you sure your configuration is correct ? I'm on Linux. The OpenGL renderer on Linux can't be behind the Windows version.

**Comment by mirh** [comment]
> Sorry to bump the thread, but... This is still a problem (on Windesows) on AMD Radeon Software 17.2.1. 

Yes, we already know in #1552. 
If any though.. I guess it would be interesting to know the state of AMDGPU-PRO.

**Comment by TacoDeBoss** [comment]
@gregory38 Don't know what to tell you, man. This is Linux: `http://i.imgur.com/oOEVXed.png`

And this is Windows: `http://i.imgur.com/SZe6HL0.png`

**Comment by FlatOutPS2** [comment]
Are you using a different Blending Unit Accuracy setting on Linux?

**Comment by TacoDeBoss** [comment]
No, every setting is the same.

**Comment by TacoDeBoss** [comment]
The post effects used to be broken on MGS3, and if you set CRC hacks to none, you could see the broken post effects, but they got fixed months ago on Windows and have [remained broken on Linux.](http://i.imgur.com/jDaF5NH.png)

**Comment by FlatOutPS2** [comment]
Are you sure you're not accidentally using an older GSdx version?

**Comment by TacoDeBoss** [comment]
Not as far as I know. I just downloaded PCSX2 from the Linux PPA this morning.

**Comment by FlatOutPS2** [comment]
Did you have an earlier version still installed? The old plugins don't always get removed if you install a new one.

**Comment by TacoDeBoss** [comment]
No, this is the first time I've had PCSX2 on this distro installation.

**Comment by gregory38** [comment]
Need plugin name (hint don't use legacy). You PPA link. And a screenshot of your settings.

**Comment by TacoDeBoss** [comment]
@gregory38 Sorry it's taken me a bit, been occupied with other stuff.

PPA is https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily 

[This](http://imgur.com/a/ECjQj) is my settings.

**Comment by gregory38** [comment]
@TacoDeBoss something is wrong. Latest GSdx is 1.1.0
