### ISSUE TITLE
Gdk-CRITICAL / GLib-GObject-CRITICAL - assertion failures

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1344]
OS: `Slackware64-current`
WM: `spectrwm-2.7.2-x86_64-1_SBo`
`pcsx2-7c430c9_2016.05.04_master-x86_64-1_git`

Whenever accidentally clicking the window border of the GUI interface such as just above the menu tabs (System, CDVD, Config, ...) these assertion failures are printed in the console. This is a rather insignificant issue which has existed for a while so I am reporting it anyways.
```
(PCSX2:11715): Gdk-CRITICAL **: IA__gdk_window_get_events: assertion 'GDK_IS_WINDOW (window)' failed

(PCSX2:11715): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(PCSX2:11715): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by orbea** [comment]
This issue seems to have been restricted to `spectrwm-2.7.2`. It no longer happens with `spectrwm-3.0.1` which happened to be released today. I will close this issue for now unless its still worth solving more?

**Comment by EllisonYim** [comment]
spectrwm-3.1   also happen

**Comment by orbea** [comment]
Maybe something else updated on my system then, I still can't reproduce this anymore.
