### ISSUE TITLE
Final Fantasy X artifact bug

### ISSUE THREAD

**Issue by zminhquanz** [PCSX2/pcsx2#1345]
![image](https://cloud.githubusercontent.com/assets/11285640/15048141/5876d81e-1312-11e6-940c-77a4b0442d2d.png)

there is artifact graphic bug , when i'm using build version

**Comment by hellbringer616** [comment]
please post your PCSX2 revision, system specs (OS, CPU and clock speed, Videocard, RAM, etc) as well as your game region and PCSX2 settings.

I have ran through all of FFX International and haven't ran into this issue.

Edit: just checked when loading my file, same spot. no issues

**Comment by ssakash** [comment]
Please use the forums instead for support. The lack of information on the bug report doesn't help on reproducing the issue.
