### ISSUE TITLE
Legacy gsdx for opengl 3.05?

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#1347]
Until a few months ago, the gsdx plugin worked (very slowly of course, but still good enough to play games like FFXII international at 10 fps with the inbuilt frameskip) in linux on this very old portable (2007-2008). Now with larger extension requirements, the daily build fails at opening any game.
PPSSPP system information says my opengl version is 3.05

I've read that gsdx will have a legacy version. My question is if the legacy will work on my version of the opengl api and this kind of old hardware as it was until recently?

the failure messages on the window:

PCSX2 1.5.0-0 - compiled on May  3 2016
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Linux 3.19.0-58-generic x86_64
	Physical RAM     =  3947 MB
	CPU name         =  Intel(R) Core(TM)2 Duo CPU     T6600  @ 2.20GHz
	Vendor/Model     =  GenuineIntel (stepping 0A)
	CPU speed        =  2.193 ghz (2 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 0c08e39d
	x86EFlags        =  20100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins...
	Binding   GS: /usr/lib/games/PCSX2/libGSdx.so 
	Binding  PAD: /usr/lib/games/PCSX2/libonepad-1.2.0.so 
(GameDB) 9700 games on record (loaded in 575ms)
	Binding SPU2: /usr/lib/games/PCSX2/libspu2x-2.0.0.so 
	Binding CDVD: /usr/lib/games/PCSX2/libCDVDnull.so 
	Binding  USB: /usr/lib/games/PCSX2/libUSBnull-0.7.0.so 
	Binding   FW: /usr/lib/games/PCSX2/libFWnull-0.7.0.so 
	Binding DEV9: /usr/lib/games/PCSX2/libdev9null-0.5.0.so 
Plugins loaded successfully.

	HotSwapping to new ISO src image!
HLE Notice: ELF does not have a path.

Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
ERROR: GL_ARB_copy_image is NOT SUPPORTED
ERROR: GL_ARB_direct_state_access is NOT SUPPORTED
Closing plugins...
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
(p) GS plugin failed to open!(thread:MTGS)(thread:EE Core)
User-canceled plugin configuration after plugin initialization failure.  Plugins unloaded.

**Comment by orbea** [comment]
Try building PCSX2 with `-DGSDX_LEGACY=ON`?

**Comment by i30817** [comment]
I'm not building (using the ppa). I guess I will have to wait for the release, build it myself (which i frankly think will go pear shaped) or go bother the ppa guy to do a legacy package?

**Comment by gregory38** [comment]
What mesa version do you have?

**Comment by i30817** [comment]
glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 10.5.9

**Comment by gregory38** [comment]
And are you sure that you don't have an extra plugin that you need to select.

Otherwise it might be a good idea to upgrade your driver.

**Comment by gregory38** [comment]
wait current GSdx require at least 3.3 even legacy

**Comment by i30817** [comment]
Yeah, the only gs plugin in the options is :
GSdx (GCC 4.9.2, SSE2) 1.1.0 [libGSdx]

Something which might be important is that the directory in that these plugins are put is a read only system one, probably because of the package.
/usr/lib/games/PCSX2

**Comment by gregory38** [comment]
you can copy the plugin into your home directory and configure PCSX2 to use them.

**Comment by i30817** [comment]
If it does require 3.3, that must be recent(ish) because i remember using the emulator to play in January I think? 5 months or so.

**Comment by gregory38** [comment]
3.3 check  is  quite old. Srange. Honestly try to install a more recent Mesa. It might be enough.

**Comment by i30817** [comment]
Ah. I'd probably have to upgrade the whole system which would be a pain :sweat:

**Comment by orbea** [comment]
I just want to point out that I have a more or less OpenGL 4.0 capable card + driver, but I still get this.
```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 11.3.0-devel (git-cf6dadb)
```
Where if I do something like this.
```
$ glxinfo | grep "Core Profile"
OpenGL core profile version string: 4.2 (Core Profile) Mesa 11.3.0-devel (git-cf6dadb)
```

**Comment by gregory38** [comment]
Yes but I vaguely remember that first version that support gl 3.3 was sandy bridge. So far the error messages are 2 sw extensions that ought to work with any hardware. So upgrading mesa is the best solution.

**Comment by i30817** [comment]
Mmm... yeah:

glxinfo | grep "Core Profile"
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.9

**Comment by gregory38** [comment]
So you're good only miss mesa 11.2 ;) I didn't know that it was working for those old gpu.

**Comment by i30817** [comment]
Time to close this, i know what i have to do, thanks for the clarification.
