### ISSUE TITLE
LilyPad 0.11.0: Early PS1 Games not Supported

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1348]
When using LilyPad 0.11.0 on ePSXe, most of early games doesn't recognize the Dualshock 2 as a standard controller. They display a special screen of information when possible and the commands will not work.

**Rayman 1 :**
![mnrd7o7](https://cloud.githubusercontent.com/assets/3964507/15073096/f082c23c-1397-11e6-93ad-de5a41f422bf.png)

**Dragon Ball GT Final Bout :**
![dlc3ftz](https://cloud.githubusercontent.com/assets/3964507/15073125/0c007068-1398-11e6-9e8c-85a5c33f2c81.png)

Tekken 1 & 2 are also unplayable with the plugin.

**Comment by FlatOutPS2** [comment]
This is not a LilyPad issue. 

First, you'll need to disable the LilyPad controller option "Use analog mode if possible - PS1 only" in the Pads section of the General tab. These games only support the digital mode of the controller.

Secondly, you'll have to use a real PS1 BIOS file, as none of the external plugins seem to work with the "Enable HLE Bios" option.

**Comment by Catarax** [comment]
Thanks a lot FlatOutPS2, disabling "Use analog mode if possible - PS1 only" fixed everything and i'm still having vibration on new games.

**Comment by FlatOutPS2** [comment]
Yes, vibration should work even without analog mode. But the analog sticks won't work without it, though the left stick will still register input as a d-pad.

**Comment by turtleli** [comment]
#1398 was merged, so it should work even if "Use analog mode if possible" is enabled. I'll close this issue since the remaining issues are on the ePSXe side and we can't do anything about it.
