### ISSUE TITLE
Ubuntu 16.04 SegFault when openning PCSX2 (unstable from repository)

### ISSUE THREAD

**Issue by derekpock** [PCSX2/pcsx2#1351]
I have `pcsx2-unstable` installed, but I have the same issue with `pcsx2` (stable). Both were tried and  installed from the PPA repository.

When I attempt to run the program, it opens fine initially, but after I click next twice for the first-time configuration, I receive a segmentation fault:

<pre>
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"

(PCSX2:12715): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

Gtk-Message: Failed to load module "canberra-gtk-module"
Interface is initializing.  Entering Pcsx2App::OnInit!
Applying operating system default language...
Command line parsing...
Command line parsed!
Segmentation fault
</pre>

Is there another version I should try? It may be good to note that because I'm using Ubuntu 16.04 x64, I had to manually download and install `libsoundtouch0:i386` version 1.9.0-1, because it wasn't in the repos (`libsoundtouch1:i386` was, but `pcsx2-unstable` didn't like it).

**Comment by derekpock** [comment]
It was an issue with a bad plugin.

**Comment by smacheeri** [comment]
HI can you please let me know how you solved this issue..I have the exact same problem and I am stuck..

**Comment by jcdenton2k** [comment]
The repros seem to need some updating but that needs to be done by the package maintainers.  Go throw them a message/e-mail to get them to fix things.

**Comment by derekpock** [comment]
@smacheeri I had a bad plug-in in my pcsx2 directory. For me, reinstalling everything from scratch worked. I previously tried copying the working directory (with various config files and plugins) from an older computer over, but while using a newer version of pcsx2. This caused the exception. I cannot remember, but it was one of the input plugins that caused the issue.

**Comment by smacheeri** [comment]
Thanks for replying:)

**Comment by jcdenton2k** [comment]
Appreciate the update, thanks!
