### ISSUE TITLE
[GSdx hardware bug] FMVs flicker in Earth Defense Force 1 and 2.

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#1357]
**PCSX2 version:**
v1.5.0-dev-548-g8943a9d-gsdx-black-fmv-794-vs2013-Win32-AppVeyor (2016-04-04; PR #1222's final automated build)

**PCSX2 options:**
Defaults. No options modifications affect this issue.

**Plugins used:**
Defaults (GSdx32-AVX, LilyPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk). No particular plugins affect this issue.

**Plugin settings:**
GSdx (Direct3D11/OpenGL hardware modes). No hack modifications affect this issue.

**Description:**
In most variants of Earth Defense Force 1 and 2 (all NTSC-J versions and the PAL version of EDF1), FMVs flicker heavily during playback. The PAL version of EDF2 isn't affected because all of its FMVs were removed. None of Sandlot's other PS2 games are affected.

I originally brought up this issue in PR #1222's comments and posted a few related dumps. Since that PR was recently merged, I figured there'd be value in creating a separate issue for these games.

**Dumps:**
- Monster Attack (PAL-Unk):
  - [GS dump](https://aced14.github.io/pcsx2-gs-dumps/ma_gs_fmv-flicker-bug.7z)
  - [Multi-frame GS dump](https://aced14.github.io/pcsx2-gs-dumps/ma_gs_fmv-flicker-bug-2.7z)
  - [Block dump](https://aced14.github.io/pcsx2-gs-dumps/ma_block_fmv-flicker-bug.7z)

**How to replicate:**
1. Launch PCSX2.
2. Open GSdx's plugin settings and select Direct3D11 or OpenGL's hardware renderer.
3. Fast boot one of the following games (or use the [Linuz ISO CDVD plugin](http://wiki.pcsx2.net/index.php/Setting_up_Windows_version#Linuz_ISO_CDVD) to launch [Monster Attack's block dump](https://aced14.github.io/pcsx2-gs-dumps/ma_block_fmv-flicker-bug.7z)):
   - Simple 2000 Series Vol.31 - The Chikyuu Boueigun (NTSC-J)
   - Monster Attack (PAL-Unk)
   - Simple 2000 Series Vol.81 - The Chikyuu Boueigun 2 (NTSC-J)
4. Wait for the memory card and logo screens to appear.
5. At some point during the logo screens, a "D3PUBLISHER" FMV will play. It'll heavily flicker between black and its frames' "real" contents.

**Last known version to work:**
- Never worked.
- Oldest tested version: R5766 (2013-12-05).

**PC specifications:**
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; OS: Windows 7 SP1.

**Other comments:**
@gregory38 FYI.

**Comment by lightningterror** [comment]
Is this still an issue on recent dev build ?

**Comment by Aced14** [comment]
@lightningterror I just re-tested all 3 games in v1.5.0-dev-2339-g1292cd505 (2018-04-06; 1292cd505efe7c68ab87880b4fd6809a96da703c).

The same FMV flickering issue is still occurring in that build's GSdx D3D11 and OGL hardware renderers. No flickering of any kind occurs in D3D11/OGL's software renderers.

**Comment by Mrlinkwii** [comment]
is this still an issue on latest 1.7?

**Comment by Aced14** [comment]
Just tried 085332da2700f27ba9037a7789311a708a173db2 (pcsx2-v1.7.3108-windows-64bit-AVX2-wxWidgets) on an Intel Hades Canyon PC (NUC8i7HNK - CPU: i7-8705G, GPU: Radeon RX Vega M GL).

Setting the renderer to D3D11, exiting PCSX2, restarting it and trying to boot any of the games in question caused no startup graphics to appear (audio worked) as the console spammed "GS: Memory allocation failure." and ultimately crashed.

None of the other hardware renderers (D3D12, OpenGL, Vulkan) crashed, but unfortunately they were still all afflicted by FMV flickering.

So this issue is still relevant to this day :(.

**Comment by refractionpcsx2** [comment]
This is no longer a problem in 1.7 (I think it was fixed a couple of months ago.
