### ISSUE TITLE
nvidia 260GTX + Ar tonelico 2: world map clipping in oGL harwdare mode

### ISSUE THREAD

**Issue by Soukyuu** [PCSX2/pcsx2#1362]
The issue has been there since forever. I saw it on windows in all hardware modes and it's still present now on linux. nvidia or nouveau driver, it doesn't matter. I've also tried messing around with blending unit accuracy, accurate date and crc levels, without success.

It looks like this:
![image](https://cloud.githubusercontent.com/assets/2095054/15270017/9bea8cca-1a11-11e6-8a00-767477088333.png)
Moving the camera once in any direction introduces a horizontal cutoff plane in the middle of the screen:
![image](https://cloud.githubusercontent.com/assets/2095054/15270027/eb8b9df0-1a11-11e6-83ce-5220a7b0948d.png)
For comparison, the same scene in software mode:
![image](https://cloud.githubusercontent.com/assets/2095054/15270033/167cf55e-1a12-11e6-84a6-310b23a00d21.png)

From what I remember, ar tonelico 1 is also affected, maybe more GUST games.

**Comment by gregory38** [comment]
Hum I'm pretty sure that I have a dump to reproduce the issue I need to find it. Could be an half bottom screen issue like plenty of games

**Comment by gregory38** [comment]
I think I have found the bug. Depth clean doesn't work as expected because a smaller color buffer is still attached to the framebuffer.

**Comment by gregory38** [comment]
Please try latest git. It must be good now.

**Comment by Soukyuu** [comment]
Hmm, no (blending accuracy: ultra):
![image](https://cloud.githubusercontent.com/assets/2095054/15275922/ca93a814-1ad8-11e6-8706-3ac2bda8e8a4.png)

**Comment by gregory38** [comment]
Hum strange it was working on my dump. Maybe I need to test it on a release build. The issue isn't blending but framebuffer size.

**Comment by Soukyuu** [comment]
It appeared to work but once I moved the camera it broke again.

**Comment by gregory38** [comment]
Oh, that it is a different story ! I think I understand what happen.

**Comment by tsunami2311** [comment]
what happen to pcsx2 webpage/forums/wiki none of them working for last few days? yah i know it off topic i didnt want to make "git" issue about it, and i dont think git supports pm users.

**Comment by FlatOutPS2** [comment]
> what happen to pcsx2 webpage/forums/wiki none of them working for last few days? yah i know it off topic i didnt want to make "git" issue about it, and i dont think git supports pm users.

Can't really remember the last time a site with an active community was offline for so long without any sort of official statement. :/

**Comment by gregory38** [comment]
Normally there is a facebook post.

On the issue, ( @ramapcsx2  here the full story)

First draw call is a sprite to clean the z buffer
* start address is 0x2300
* width is 10 pages
* texture/scissor size is 640x448
* depth is 16 bits so it writes 70 (10w * 7h)  pages of data.


Next draw call will uses the buffer as 6 pages width with a scissor test of 384x672. So the above texture can be seen as a
* texture width: 6 pages * 64 pixels/page = 384
* texture height: 70/6 pages * 64 pixels/page =746

So as you can see the GS issue a write of 640x448 but actually it expects to clean a 384x746 area. Ideally the fix will transform the buffer to adapt the page width properly.

**Comment by gregory38** [comment]
@ramapcsx2 @Sarania @refractionpcsx2 
Guys, do you know if the issue impact severals games ?

I'm asking because a crc hack could be done in 10 minutes whereas proper implementation is likely weeks of works.

**Comment by gregory38** [comment]
I pushed a CRC hack. It would work for both DX and openGL normally. I put the CRC that I have in my gs dump, there is maybe several versions so we might need to add more entry.

**Comment by Soukyuu** [comment]
It's... still not working here. All I'm getting is
```
GL_ARB_draw_buffers_blend: not supported ! function pointer will be replaced
```
when changing to CRC aggressive, and it looks just the same as other settings - works upon first load, but navigating the map breaks it.

**Comment by gregory38** [comment]
What is the CRC of your game? Check the emulog (I don't know where it is printed)

**Comment by Soukyuu** [comment]
`ELF (cdrom0:\SLUS_217.88;1) Game CRC = 0xABA6BCE5, EntryPoint = 0x0010001C`

It's the pre-beta4 of the retranslation project, so if it's the ELF crc it's going by, it explains why it doesn't work...

**Comment by Soukyuu** [comment]
I changed the CRC in my build of pcsx2 and can confirm it works - thanks. I hope by the time we release the final version of our project there will be a general solution, else you'd have to add another entry for the patched release....

**Comment by gregory38** [comment]
General solution isn't easy. It will requires to shuffle pixels to transform the initial texture (I mean input texture, render target buffer and depth buffer) of size x1,y1 into a new texture of size x2,y2. It would be painful for the GPU, and might not work well with upscaling. Seriously it's just a giant mess.

**Comment by gregory38** [comment]
Shall we close the bug. You can ask me later to put your final CRC.

**Comment by Soukyuu** [comment]
I guess so. Thank you for the fix.

**Comment by Sarania** [comment]
Late to the show but no, I don't know of any others. I'd never noticed this one tbh!
