### ISSUE TITLE
Missing Widescreen Fixes/Patches

### ISSUE THREAD

**Issue by jcdenton2k** [PCSX2/pcsx2#1364]
Pastebin Link:
http://pastebin.com/wEBp3UMp

Because GitHub Formatting takes too long.

**Comment by FlatOutPS2** [comment]
Always nice to see an empty post. 

Widescreen patches archive isn't updated for every patch, but are added intermittently when there are enough new patches to make a worthy PR. You can always add a new patch you need to the cheats_ws folder.

**Comment by avih** [comment]
The wide screen patches are managed by Devina at the forum, at this thread: http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

Occasionally there's a new package of patches released at the forum, and once enough new patches accumulate, we update the repo with the new package.

One of the reasons is that the patches are packaged as a zip file together with pcsx2, and updating binary files at a source code repository is not something we should be doing often, preferably never, but still, we update `cheats_ws.zip` every few months usually.

**Comment by jcdenton2k** [comment]
@FlatOutPS2:
Always nice to get a cold unfriendly welcome from the locals.  FYI, it takes time to compile posts properly and I had already made the thread before realizing the post would get eaten if my browser messed up on me or crashed.

@avih:
I'm not posting on your stupid forums because your asshole forum mods are overly-aggressive jerks that ban/delete posts without a word.  So one of you can poke Devina to take a look and implement them if you like.
The beauty of GitHub is that I'm not going to be banned from all of GitHub just because someone disagrees with me.

**Comment by FlatOutPS2** [comment]
The Burnout games and Smash Court 2 and the Tomb Raider games all already have native widescreen support. The Kingdom Hearts games are already included in the archive

**Comment by avih** [comment]
Well.. I can't force you to use the forum, but the wide screen patches are managed there and there only, by Devina.

**Comment by jcdenton2k** [comment]
@FlatoutPS2:

The filenames didn't match the other ones already present within the archive.  That is curious.  I specifically checked to make sure there weren't any duplicates from either Devina's archive or the PCSX2 Git archive.

Let them sit here for posterity then.
