### ISSUE TITLE
Folder memory cards: Wrong filter for Tony Hawk's American Wasteland Collector's Edition

### ISSUE THREAD

**Issue by Pistachioman** [PCSX2/pcsx2#1367]
When "Automatically manage saves based on running game" is turned on in the memorycard manager when using folder memorycards, the Collector's Edition of THAW can't load it's saves after an emulator restart. The saves get filtered with SLUS-21295 (the collector's edition), but the game saves to SLUS-21208 (the normal edition). Turning off the filtering works as expected.

**Comment by turtleli** [comment]
I think it'll work if you add `MemCardFilter = SLUS-21208` to the GameIndex.dbf entry. Can you confirm this?

**Comment by Pistachioman** [comment]
Yes, doing that fixes the problem.
