### ISSUE TITLE
GSdx Feature Request - Default Settings Button

### ISSUE THREAD

**Issue by escape209** [PCSX2/pcsx2#1373]
This would be incredibly useful in case I completely screw up my settings and want to start over. This means I wouldn't have to worry about manually setting everything to default. It would also ensure that I am in fact using default settings if the need to do so were to arise.

**Comment by ssakash** [comment]
I'll add it for windows GUI if @refractionpcsx2 and @turtleli agrees with it.

**Comment by FlatOutPS2** [comment]
Would be good feature for the SPU2 plugin as well

**Comment by turtleli** [comment]
Well, it should be easy to do for GSdx once #1370 is completed and merged.

**Comment by MrCK1** [comment]
If we plan on implementing this for multiple plugins, why not combine the current "reset settings" dialog and plugin dialogues into a list?
![clearsettingsdlg_current](https://cloud.githubusercontent.com/assets/16314399/15551884/03971e5c-2286-11e6-819c-c37eb42af84d.png)

e.g.

- Clear ALL Settings (emu and plugins affected)
- Clear PCSX2 Configuration (emu affected)
- Clear Plugin Configurations (ALL plugins affected)
- Clear GSdx Configuration
- Clear SPU2 Configuration

**Comment by DPersonalized** [comment]
I'm fine with that, as long as there's a confirmation dialog box for all of them, as I always seem to click the wrong things in menus (bad motor skills.)

**Comment by refractionpcsx2** [comment]
I think a "reset all settings" would be good to have yeah, good idea :)

**Comment by FlatOutPS2** [comment]
> I think a "reset all settings" would be good to have yeah, good idea :)

It's already there of course. The downside with the current one is that it shuts down PCSX2 and you'll have to manually start it up again and doesn't affect plugin settings at all.

**Comment by refractionpcsx2** [comment]
Well I think 2 separate buttons might be a good idea, the user may not want to reset absolutely everything, they might only want to do the core settings.

Either that or have a dialog come up when you click reset so you can choose what gets reset.

**Comment by FlatOutPS2** [comment]
It's already possible to reset the core settings in the Emulation Settings menu by setting the preset back to 2. So I don't really know what the current reset/clear all settings function is good for. I think it regressed from its original function.

My suggestion is to fix the clear all/reset function so that it actually removes all settings again, add a "Clear all plugin settings" button to the config tab, and add set to default/clear settings buttons to the GSdx and SPU2 menu's.

**Comment by MrCK1** [comment]
That's kind of what I was getting at. I was thinking a checkbox for each component/plugin and click OK to reset; but using wxCheckbox is probably more complicated then we need.

Maybe something like this?
![wpf-checkboxlist](https://cloud.githubusercontent.com/assets/16314399/15582656/b426437c-2337-11e6-9cb1-34206f16dab9.png)

**Comment by FlatOutPS2** [comment]
Having to open another window just makes it less user friendly. Having just the two options in the config tab doesn't make it too crowded. And having a buttons in the plugin menu is convenient as the user who wants to reset all GSdx or SPU2 settings will probably already have the plugin menu open, or would anyway after resetting.

**Comment by ssakash** [comment]
what's the conclusion ? should it be added to individual plugin dialogs (or) should a separate dialog be added with options to clear defaults for specific plugins as @MrCK1 stated ?

**Comment by FlatOutPS2** [comment]
Instead of a seperate dialog window you could also use the arrow opening side tabs like the plugins and savestates have. But even if the conclusion would to create that, I would still add the buttons to the individual plugin dialogs, as you can't access the menu tabs when you're using the GSdx or SPU2-X dialogs.

**Comment by MrCK1** [comment]
> I would still add the buttons to the individual plugin dialogs, as you can't access the menu tabs when you're using the GSdx or SPU2-X dialogs.

Would it be easier/safer to wipe the configuration while the dialog isn't open? We wouldn't need to update the displayed values in the GUI window either.

On the GSdx side, some settings don't get affected until a reboot (CRC/HW hacks?) so we would have to force one or do something else right?

**Comment by FlatOutPS2** [comment]
You can just click on the clear/set to default button, then click the OK button and it will apply all settings immediately. A menu option would need to freeze the emulation as well, and as the plugin dialog window already does that, it only makes it easier to work with.

**Comment by mirh** [comment]
Mhh.. I dunno. 
Is it so troublesome to delete .ini file?

**Comment by ssakash** [comment]
As I said on https://github.com/PCSX2/pcsx2/pull/1509#issuecomment-239617170 , I have no plans on touching the GUI code anymore. (That's why I removed my assignment)

However the implementation of a default settings button should be feasible and rather easy.

**Comment by ramapcsx2** [comment]
It's somewhat easy if all plugins are ready to have their inis stripped from them.
This needs to work even when a game is playing / paused which could cause problems.
If that's clear, then the reset settings function can just delete a given list of *plugin.ini* files.

**Comment by marcoluc97** [comment]
@stenzek sorry to bother but in the new GUI there will be something like this?

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/154862134-d34a8d10-86f8-4330-96a2-c65825533603.png)

I hope this satisfies your answer. @marcoluc97

**Comment by marcoluc97** [comment]
So fast we'll yes I was checking old issue with GUI without QT still not involved. Thanks @RedDevilus

**Comment by lightningterror** [comment]
Closing, duplicate/newer issue at #6518.
