### ISSUE TITLE
Loading save state disabled the left stick [xenosaga I]

### ISSUE THREAD

**Issue by clbr** [PCSX2/pcsx2#1375]
In 1.4.0 on Linux / onepad, Xenosaga episode I, loading a save state somehow disabled the left controller stick on my DS3 clone. The d-pad and all other buttons still worked.

This was the second or third load, and the earlier loads worked fine. So the stick problem seems random.

**Comment by clbr** [comment]
Doing a "reboot cdvd (full)" and loading the same state, the stick worked again. So the state itself is fine, it's something in the loading procedure.

**Comment by clbr** [comment]
I forgot to say that once the stick got disabled, re-loading the save state did not fix it. It took a reboot and a re-load for the stick to get enabled.

**Comment by ramapcsx2** [comment]
The problem is most likely the state of the analog mode enabled flag in the pad plugin. It has to be preserved in the save state info.

**Comment by turtleli** [comment]
Probably related to #205. OnePad doesn't have a `PADfreeze()`, so it doesn't save or load pad state.

**Comment by gregory38** [comment]
I opened issue #1465 because I hadn't found this one. Way too much bug to handle.

Anyway, it seems doable to store some info is a nice structure to improve save state support.

**Comment by gregory38** [comment]
Could you test the PR #1476

**Comment by clbr** [comment]
Sorry, swamped with work.
