### ISSUE TITLE
Waifu2x in real time

### ISSUE THREAD

**Issue by Mickevincent** [PCSX2/pcsx2#1376]
Hello

I was told to check with you guys about my request too.
I don't know if you are familiar with the Waifu2x upscaler and filter. It's both web-based and in program form.
You can grab the program here

https://translate.googleusercontent.com/translate_c?depth=1&hl=en&prev=search&rurl=translate.google.se&sl=ja&u=https://github.com/lltcggie/waifu2x-caffe/releases&usg=ALkJrhivu32FwUwuPxodRAFRTS4bRFPimA

And here is a GLSL impementation.

https://github.com/ueshita/waifu2x-converter-glsl

My request is originaly to have this kind of upscaler and filter mainly for PS1 emulation since those games were rendered in really, really low res.
Here is some examples I have done by upscaling original backgrounds from FFVII and FFIX.

FFVII
http://i.imgur.com/X27lVJ5.jpg

FFVII
http://i.imgur.com/fYwxIBY.png

FFIX
http://i.imgur.com/zR1kjlE.jpg

FFVII
http://i.imgur.com/CzRczDb.jpg

And here's another batch of FFVII pictures
http://imgur.com/a/zzdBm

Well, as you can see this is probably the best option for making these games look as "hd" as possible. And it do looks really nice.

So, is there any possibility that we sometime can have a Waifu2x filter for realtime gaming? 
Please
/Mike

**Comment by FlatOutPS2** [comment]
Waifu 2x can takes several minute to complete a single picture(depending on size and settings), which means it's not suited to realtime work that displays 20-60 pictures per second.

Here's a request for xBRZ, which does work realtime, that will probably be added one day:
https://github.com/PCSX2/pcsx2/issues/800

**Comment by Mickevincent** [comment]
Well, when I'am doing it with the Waifu2x software in GPU mode it takes about 0.2 - 0.6 seconds to do one image. However... I have a 980Ti. So.. you are right that it is way too slow yet. But I don't know much about this tech stuff and I really want something that looks at least the same. But I'am guessing it may be a little bit too much at the moment :(

**Comment by refractionpcsx2** [comment]
0.2 seconds for one frame is massively too slow, to achieve 60fps we need it to be no more than 0.016 of a second, including the rendering time. even at 30fps you're talking 0.032 of a second per image, what you're suggesting is nearly 7x too slow and its best

**Comment by Mickevincent** [comment]
Oh yes I know :) however keep in mind that ps1 games often ran in around 20fps. Besides who knows how well optimized waifu is? Pherhaps it also does thinga that does not really improve ps1 pictures? Idont know. And with the incoming 1080ti we will get even more power :) look Iam just beeing optimistic because I really want this. But I know that you guys knows this better than me.

**Comment by refractionpcsx2** [comment]
I realise you're being optimistic :) But this isn't the PS1, it's the PS2 and a vast majority of users don't own an 980Ti or anything close, most have a mid-range card at best, so it would be a no go for them for sure :(

As far as I was aware Waifu2x wasn't really brilliant for things other than anime style drawings? as mentioned before xBRZ is probably a better option.

**Comment by Mickevincent** [comment]
Oh. I was recomanded to post on several different hubs just because you guys knows this. I still only want it for Ps1. And someone said that as long as it is ported to any emulator it will be easier to port to other emus. Yes, not many people do pherhaps own a 980ti. But its pc hardware wich gets cheaper everyday because of new hardware. Could we not see this as a "new generation" in ps1 emulation? I mean look at the pictures. It looks amazing. I have tried most other shaders also and sadly I dont think any comes close to waifu. I dont know how it would look in "3d games" like crash bandicoot. But ps1 still has aloooot of good pre-rendered games. Some of the best ever made if you ask me.

**Comment by Mickevincent** [comment]
Iam not giving up. This needs to happen.

**Comment by refractionpcsx2** [comment]
We aren' t being a conduit for you to get another emulator to implement it, we have far more important things to do.

**Comment by Mickevincent** [comment]
Ok. As I said it was just because you know your ways around this. Thanx anyway.
