### ISSUE TITLE
PCSX2 does not call USBsetRAM after hotswap or hotconfigure of the usb plugin

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#1378]
During normal boot the plugin gets passed a pointer to IOP memory via USBsetRAM.

This is not done if the plugin is hot-configured or hot-swapped during emulation.

In the latter case, it can lead to the usb plug-in trying to use a null pointer and crashing.

This call is not done in SysCorePlugins::OpenPlugin_USB()
https://github.com/PCSX2/pcsx2/blob/1208dbe8c7b3171163bf448edc37cae8ce3a6a0b/pcsx2/PluginManager.cpp#L1257
Instead it is made in cpuReset within R5900 code https://github.com/PCSX2/pcsx2/blob/93067ee30fe9bfd666cefb31481b7b0caf6f2e95/pcsx2/R5900.cpp#L97

**Comment by refractionpcsx2** [comment]
TBH I don't think hot swapping of plugins works anyway. I know hotswapping the GS plugin will cause the emulator to crash, I suspect it's the same for the others.

**Comment by FlatOutPS2** [comment]
GS Plugin hotswapping usually works. It only freezes PCSX2 in certain situation. Most other plugins are fine hotswapping, but the USB plugins actually crash PCSX2 because of the issue.
