### ISSUE TITLE
new linux system call => userfaultfd

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1379]
Found the option in 4.4 upgrade (from 4.1)

Full detail can be found here
https://www.kernel.org/doc/Documentation/vm/userfaultfd.txt

```
Userfaults allow the implementation of on-demand paging from userland
and more generally they allow userland to take control of various
memory page faults, something otherwise only the kernel code could do.

For example userfaults allows a proper and more optimal implementation
of the PROT_NONE+SIGSEGV trick.
```

PCSX2 uses the above trick. I don't think it really impact performance but it could potentially help to handle direct memory access (faster). Anyway it is something that ought to be investigated.

**Comment by seta-san** [comment]
is this still an issue? linux 4.4 seems to have fallen out of all support.
https://9to5linux.com/linux-kernel-4-4-lts-reaches-end-of-life-after-six-years-of-support

**Comment by refractionpcsx2** [comment]
Probably not, no, let's close for now.

**Comment by F0bes** [comment]
I don't think this was ever an **issue**. More of an RFC.

**Comment by refractionpcsx2** [comment]
I guess nobody C'd in 7 years :P
