### ISSUE TITLE
my dualcore cpu usage is max 75% at framerate not limited in tekken V and other games

### ISSUE THREAD

**Issue by Nerboruto** [PCSX2/pcsx2#1382]
I got 100% cpu usage only with MTVU enabled (microvu1 multi-threaded)
why?

**Comment by ssakash** [comment]
Please use the [forums](http://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows) instead for support / general questions. Github issue tracker is only used for **valid** bugs.
