### ISSUE TITLE
[OnePad] [Linux] DualShock 4 D-Pad key presses are not being recognised (via Bluetooth)

### ISSUE THREAD

**Issue by hazrpg** [PCSX2/pcsx2#1385]
- PCSX2 version: 1.4.0
- PCSX2 options: Defaults, no settings modifications affect the issue.
- Plugins used: GSdx [1.0.0], SPU2-X [2.0.0], OnePad [1.1.0], the rest are null plugins.
- Plugin settings: Defaults, no settings modifications affect the issue.
- Description: All regular keys map successfully (and correctly) however the D-Pad always maps to the sixaxis tilt positions (despite not tilting the controller). Sometimes the keys map to `JPOVR-0` or `JPOVL-0`, with repeated succession of trying to map them - but I can never got the opposite mappings. So JPOVR-0 seems to be right, and JPOVL-0 seems to be left - both seem to set randomly (but possibly due to the fact that I need to mash the keys in succession for it to be received). Mapping on any other software or emulators seem to be fine, the issue only seems to lie in PCSX2 and OnePad on Linux (Ubuntu 16.04).
- How to replicate: Pair the DS4 controller via Bluetooth (PS Button + Share button together to enter pair mode), open PCSX2 and attempt to map the d-pad buttons.
- Last known version to work: Never worked, tried by compiling the master branch, and the prepackaged PPA version.
- PC specifications: CPU: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz :: GPU: Nvidia Optimus GeForce 540M (and built-in Intel) :: OS: Ubuntu 16.04 (amd64 build - Linux Kernel 4.4.0-22).

**Comment by hazrpg** [comment]
I have managed to resolve this by manually setting the the hex numbers, however the numbers used when it tries to map manually are different to the ones that get "found". I ended up using these values:

    [0][12] = 0x30100
    [0][13] = 0x30200
    [0][14] = 0x30400
    [0][15] = 0x30800

The values that were being picked up were:

`0x30400` (working left), `0x2000a` (sixaxis tilt up), `0x30200` (working right)

I have attached the (now) working OnePAD.ini file (found in ~/.config/PCSX2/inis_1.4.0/) for others who may need it:
[OnePAD.ini.txt](https://github.com/PCSX2/pcsx2/files/298960/OnePAD.ini.txt)

**Comment by gregory38** [comment]
Could you post the game-pad name detected by onepd. (on 1.4 look at the top with button/axis number) ?

Which version of SDL2 do you have ?

**Comment by gregory38** [comment]
@hazrpg ping

**Comment by gregory38** [comment]
New onepad version available. Code is based on the SDL2 auto-setup feature. It should work now.

**Comment by lightningterror** [comment]
I'll close this since it has been marked as fixed and no feedback was provided for a year now.

If the problem remains it can be reopened.

**Comment by hazrpg** [comment]
Hi, I can confirm that the keypresses now work on onepad 1.3... however, the issue I have now is the right analogue doesn't work right (or at least the animation shown on screen). It picks up everything correctly:

![image](https://user-images.githubusercontent.com/115112/37473171-a5a0fe52-2865-11e8-9f36-108839a2f3eb.png)

However moving the controller analogue stick around only moves the pin up and down (left and right doesn't seem to work):

All the way up:
![image](https://user-images.githubusercontent.com/115112/37473223-d17bca66-2865-11e8-8f55-3d0549b4eb0e.png)

All the way down:
![image](https://user-images.githubusercontent.com/115112/37473239-de75b114-2865-11e8-82f7-2e35f2f02fc6.png)

All the way left:
![image](https://user-images.githubusercontent.com/115112/37473270-eba5ed0e-2865-11e8-936b-4d159f29efd0.png)

All the way right:
![image](https://user-images.githubusercontent.com/115112/37473295-f5559e44-2865-11e8-92b7-c409e6de8677.png)

**Comment by hazrpg** [comment]
- PCSX2 version: 1.5.0-0 (git) Oct 19 2016
- PCSX2 options: Defaults, no settings modifications affect the issue.
- Plugins used: GSdx [1.0.0], SPU2-X [2.0.0], OnePad [1.3.0], the rest are null plugins.
- Plugin settings: Defaults, no settings modifications affect the issue.
- Description: All regular keys map successfully (and correctly). The right analogue stick only appears to be working with up and down actions, despite all being mapped correctly with JAxis 3 Half-/+ JAxis4 Half-/+. Just tried play a game and although the animation tester doesn't show up correctly, its working fine in-game.
- How to replicate: Pair the DS4 controller via Bluetooth (PS Button + Share button together to enter pair mode), open PCSX2 and attempt to map the d-pad buttons.
- Last known version to work: Never worked, tried by compiling the master branch, and the prepackaged PPA version.
- PC specifications: CPU: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz :: GPU: Nvidia Optimus GeForce 540M (and built-in Intel) :: OS: Ubuntu 16.04 (amd64 build - Linux Kernel 4.4.0-22).
