### ISSUE TITLE
GSDX-PCRTC: Blurry Images on FFXII

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1389]
**Description**:
The entire rendered screen seems to ghost a few pixels to the left or right (this is easily seen around the character's legs) causing the whole screen to appear blurry.

![ffxii](https://cloud.githubusercontent.com/assets/6278726/15825277/02f1f624-2bfb-11e6-8c56-85e6c07792fe.jpg)

* **Last working build** : [v1.5.0-dev-786](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-786-g68eb377&platform=windows-x86)
* **Build to cause the issue** : [v1.5.0-dev-790](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-790-g60e0f3b&platform=windows-x86)

**GSDump**: **[download link](https://www.dropbox.com/s/dhn7zam59swu0cn/FFXII.rar?dl=0)**

**Comment by ssakash** [comment]
**(Before Merging #1234)**

**Native Resolution**:                                           

>Offset Width: 0.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 0.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 0.000000 , left: 127 , baseline :126 

**2X Native Resolution**:  
>Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 0.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 0.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 0.000000 , left: 127 , baseline :126 

**(After Merging #1234)**

**Native Resolution**:                                                     

>Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 1.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 1.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 1.000000 , left: 127 , baseline :126 

**2X Native Resolution**:
>Offset Width: 2.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 2.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 
Offset Width: 2.000000 , left: 127 , baseline :126 
Offset Width: 0.000000 , left: 126 , baseline :126 

Ha ! The issue unveils itself now ;)

**Comment by refractionpcsx2** [comment]
I replaced your image with the full size version, you couldn't see the issue in the thumbnail you had there

**Comment by FlatOutPS2** [comment]
I didn't get the lines at edges in my copy of FFXII. I've seen the same edge issue in some other games though, it believe it's OGL HW only. I'm not sure it's related.

**Comment by refractionpcsx2** [comment]
This happens in all renderers i believe.

**Comment by turtleli** [comment]
The display register values for the dump:
>Output 0 - DW: 2559 , DH: 447 , **DX: 634** , DY: 49, **MAGH: 4** , MAGV: 0
Output 1 - DW: 2559 , DH: 447 , **DX: 636** , DY: 50, **MAGH: 4** , MAGV: 0

GSState::GetDisplayRect() code:
```
rectangle.left = m_regs->DISP[i].DISPLAY.DX / (m_regs->DISP[i].DISPLAY.MAGH + 1);
```
So while FFXII shifts 1 pixel in the vertical direction, it only shifts 0.4 pixels in the horizontal direction (we shift 1 pixel at native)

**Comment by IceLancerSR** [comment]
UH UH.. the picture is Sooo bury that it hurts eyes..
here is high res picture 
http://imgur.com/7mthBvM

**Comment by FlatOutPS2** [comment]
There's already a high res picture in the OP, and there's a fix in the PR: https://github.com/PCSX2/pcsx2/pull/1390

**Comment by IceLancerSR** [comment]
@FlatOutPS2 i didn't mean anything bad by it. Just tought maybe to add comparison picture in order to promote fix to be pushed into main git :P

**Comment by refractionpcsx2** [comment]
You don't need to promote it, once everybody is happy with the fix it will be merged :)
