### ISSUE TITLE
Toy Golf Extreme (SLES- 55049) ball keeps falling through the table bug

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1397]
start a new game and the ball keeps on falling through the table so when you hit the ball it say out of bounds straight away
tried both opengl and dx11 and no change at all

**Comment by benderscruffy** [comment]
ok just found my solution
change clamping to Extra + Preserve Sign or Full

**Comment by benderscruffy** [comment]
can someone add this to the GameIndex please

**Comment by MrCK1** [comment]
Can you please post this in the forums instead? 

A compatibility/bug report would be much appreciated. The Git tracker is mainly reserved for dev work ;)

**Comment by benderscruffy** [comment]
no i just post to github
dont need to register on every forum that way
