### ISSUE TITLE
God of War II : Vertical lines under water and in hell

### ISSUE THREAD

**Issue by n1dminhd** [PCSX2/pcsx2#1400]
http://wiki.pcsx2.net/index.php/God_of_War_II

Vertical lines under water and in hell
Status: Active
Type: Minor
Description: Vertical lines under water and in hell
Workaround: Go into GSdx's plugin settings and turn the resolution to 'Native' OR if you want to keep the upscaling, turn on 'Aggressive-CRC' in the 'HW Hacks' section. Another workaround is to use "SkipDraw=60" in the 'HW Hacks' section.

But the latest PCSX2 no "Aggressive-CRC"
What should I do ?
Sorry, I bad Eng !

**Comment by ssakash** [comment]
Did you try setting ``CRC Hack level`` to ``Aggressive`` ?

**Comment by n1dminhd** [comment]
CRC hack Level : Aggressive
OK
Thanks !

**Comment by ssakash** [comment]
Is the Issue fixed with ``Aggressive`` CRC hack level ?

**Comment by n1dminhd** [comment]
Yes, fixed
Full (safest)
![untitled 2](https://cloud.githubusercontent.com/assets/4449742/15985109/15078cc8-300d-11e6-8511-1c954665ac1e.jpg)

Aggressive
![untitled](https://cloud.githubusercontent.com/assets/4449742/15985113/44fcb89a-300d-11e6-859c-652d9a6c0520.jpg)

**Comment by ipokampo** [comment]
This issue is back in 1.5.0/1.4.0/1.3.0. I'm using the PAL version which is Interlaced (not Progressive) dunno if that can affect the fix. But turning CRC check to 'Aggresive' does NOT fix the vertical lines in water. Help would be much appreciated
