### ISSUE TITLE
Cracking sound in Linux when using the PulseAudio SDL API

### ISSUE THREAD

**Issue by John-Gee** [PCSX2/pcsx2#1402]
Hello,

this is my first time using pcsx2, so I hope I am not missing something...

I am running version 1.4.0 on Arch Linux 64b, I use PA for my audio and it works fine with everything else that has a PA backend, but with pcsx2 I get extra noise on top of the standard sound..

I tried the different interpolation with no better result, but switching to ALSA (which should actually be still using PA but through the ALSA emulation layer) works just fine.

So far I've only tried to play Kingdom Hearts and Devil May Cry, and got the issue with both.
I guess this to not be related to a game, but something more generic.

Please ask me whatever else I can provide to help with this.
Thank you!

**Comment by tacchinotacchi** [comment]
Which SPUX module are you using? Latency in PCSX2 and in Pulseaudio
settings? Is Pulse set to high priority? Do you have a real-time kernel?
Il 11 giu 2016 12:55, "John" <notifications@github.com> ha scritto:

**Comment by turtleli** [comment]
Related to #1095 (basically it's caused by changes in SDL 2.0.4). Should be fixed in git.

**Comment by John-Gee** [comment]
Yup -git works (and I'm indeed on SDL2 2.0.4), sorry about the useless bug!

And thank you so much for the super quick reply!
