### ISSUE TITLE
Make inline GLSL code a bit more readable

### ISSUE THREAD

**Issue by aktau** [PCSX2/pcsx2#1404]
See https://open.gl/geometry (ctrl+f to `#define GLSL`) and http://stackoverflow.com/a/17542260.

GLSL basically lexes like C I believe, so you'd get some pretty good syntax highlighting out of that as well (which is why I'm not such a fan of the C++11 raw string approach).

Just a minor possible code cleanup I'd been thinking about.

**Comment by gregory38** [comment]
I'm not sure to understand what you mean.

Do you mean the res/glsl_source.h file ? Or do you mean the real glsl files in res/glsl/ directory ? The former is generated by script to easily embed GLSL code into the binary without distribution craziness. The former is properly highlighted in vim. Well maybe I cheated a little.
```    
autocmd BufNewFile,BufRead *.glsl,*.geom,*.vert,*.frag,*.gsh,*.vsh,*.fsh set filetype=glsl expandtab foldmethod=indent
```

**Comment by gregory38** [comment]
@aktau ping

**Comment by aktau** [comment]
Sorry! Got distracted.

> Do you mean the res/glsl_source.h file ? Or do you mean the real glsl files in res/glsl/ directory ? 

Yea, I meant the source embedded in locations like: [pcsx2/plugins/GSdx/res/glsl_source.h](../tree/master/plugins/GSdx/res/glsl_source.h), which is generated by [pcsx2/linux_various/glsl2h.pl](../tree/master/linux_various/glsl2h.pl). Instead of generating auto-concatenated strings of the form:

```
static const char* const merge_glsl =
	"//#version 420 // Keep it for editor detection\n"
	"\n"
	"in SHADER\n"
	"{\n"
	"    vec4 p;\n"
	"    vec2 t;\n"
	"} PSin;\n"
	"\n"
	"#ifdef FRAGMENT_SHADER\n"
	"\n"
	"layout(std140, binding = 10) uniform cb10\n"
	"{\n"
	"    vec4 BGColor;\n"
	"};\n"
...
```

The perl script could generate things like this:

```
#define GLSL(src) #src

static const char* const merge_glsl = GLSL(
    //#version 420 // Keep it for editor detection

    in SHADER
    {
        vec4 p;
        vec2 t;
    } PSin;

    #ifdef FRAGMENT_SHADER

    layout(std140, binding = 10) uniform cb10
    {
        vec4 BGColor;
    };
    ...
);
```

Which I find to be more readable. I'm not 100% sure this works with the inline comments, I haven't tested it.

But you're right, I hadn't noticed that these file were auto-generated, and if there are proper source files somewhere, it's less important.

**Comment by gregory38** [comment]
Well first line. However, I could add more details (which input file for example)
```
/*
 *  This file was generated by glsl2h.pl script
 *
```
But yeah, the file doesn't mean to be edited/read directly. It is only a poor solution to some gl limitation.
