### ISSUE TITLE
Onimusha 3 PAL: Sometimes the enemies disappear while you are hitting them

### ISSUE THREAD

**Issue by Oberworld** [PCSX2/pcsx2#1408]
Emulator: pcsx2-v1.5.0-dev-869
Game: Onimusha 3 PAL SLES-51914 (NTSC version not tested)

Description: Sometimes the enemies disappear while you are hitting them, more noticeable when more enemies on screen, like great battle before join Azuchi castle.

Fix: Needs Extra or Extra+preserve sign clamping mode on VUs menu. (I tested with Extra+ preserve sign and works ok, extra only need more testing but seems working too)

Request: Add this to automatic gamefixes.

**Comment by FlatOutPS2** [comment]
Please test and confirm if extra is enough.

And it would be great if someone could confirm this also applies to (one of) the NTSC versions.

**Comment by Oberworld** [comment]
Don't worry i'll do more testing and comment here when i'm sure if extra is enough.

**Comment by RazielZnot** [comment]
This also happens in the NTSC-U version, though very rarely. But when I played Heihachi bonus scenario, there was situation when enemies were knocked out through wall and this blocked story progression until I noticed that they are behind that wall. In the main game this happened without bad consequences to the story progression.

**Comment by lightningterror** [comment]
Is this still an issue or was it fixed? Can you re test the latest dev build ?

**Comment by atomic83GitHub** [comment]
It would be nice if you can test the game on the last 1.5dev to see if it's needed or not.

**Comment by lightningterror** [comment]
@Oberworld Status ?

**Comment by RedDevilus** [comment]
Anyone has this game and test if it works? (PAL or Different Regions.)
VU Clamping on Extra + preserve sign.
VU Clamping on Extra.
