### ISSUE TITLE
Couple of HW hacks are grayed out while using native.

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1410]
For example even at native,Ar Tonelico 2 still requires Sprite to Half to remove the lines inside the characters.
Also,even tho that the option is grayed out,if I enable it first while using 2x and the switch to native,the problem will be fixed...meaning,the option is only grayed out but still works as when it's not.

Tried the latest beta and some older rev from 5.11.2016

**Comment by refractionpcsx2** [comment]
Hmm, the hacks shouldn't be required at all in native, they are there to fix scaling bugs caused by upscaling.

**Comment by vsub** [comment]
No in SW mode is fine

**Comment by refractionpcsx2** [comment]
okay, I think really the issue should be addressed as the hw hacks shouldn't be required in native resolution, so i'm going to  mark this as a GSDX: Hardware issue so @gregory38 or somebody can take a look at what is going on

**Comment by gregory38** [comment]
Lines only appears in upscaling. So yes it will work in native but the hack will be disabled.

https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSRendererHW.cpp#L610

I'm closing the bug. Reopen it, if I didn't understood it correctly.

**Comment by mirh** [comment]
> Reopen it, if I didn't understood it correctly.

For the records, if dev closes it, only devs can reopen it. :s

**Comment by gregory38** [comment]
Great :) Less bug for me. :p

Could still bug me?

**Comment by vsub** [comment]
@gregory38
> Reopen it, if I didn't understood it correctly.

I'll try to explain again(Ar Tonelico 2)

Native(HW)/Custom Res(set to Native res) + Sprite to Off => Lines inside the characters
Native(HW)/Custom Res(set to Native res) + Sprite to Half(set to half by first switching to 2x scaling and then return to native)  => No Lines inside the characters

**Comment by refractionpcsx2** [comment]
I get that, but the point is the game shouldn't "need" that hack at all in native.  the sprite hack is there to solve upscaling issues, you aren't upscaling in native.

**Comment by vsub** [comment]
Those games act the same way(native + sprite to off = lines inside the characters)
Ar Tonelico 1/2
Atelier Iris 2/3
Mana Khemia 1/2

**Comment by gregory38** [comment]
Strange the hack is a nop in native. Could you check if large framebuffer option have any impacts.

**Comment by gregory38** [comment]
Actually, which hack exactly? There is a sprite alpha hack. And there is another one.

**Comment by vsub** [comment]
Below Round Sprite

**Comment by gregory38** [comment]
Could you post the ini file with only this hack on.

**Comment by vsub** [comment]
I just deleted the ini and run pcsx2 again(only enabled the hack and af  to x16(no that's not the problem)and run the game(no save state))
```
[Settings]
UserHacks_round_sprite_offset=0
UserHacks_SpriteHack=1
UserHacks_MSAA=0
UserHacks_AlphaHack=0
UserHacks_HalfPixelOffset=0
UserHacks_SkipDraw=0
UserHacks_WildHack=0
UserHacks_AlphaStencil=0
preload_frame_with_gs_data=0
Userhacks_align_sprite_X=0
UserHacks_safe_fbmask=0
UserHacks_DisableDepthSupport=0
UserHacks_DisablePartialInvalidation=0
UserHacks_TCOffset=0
Adapter=default
Renderer=12
interlace=7
upscale_multiplier=1
filter=2
accurate_blending_unit=1
crc_hack_level=3
MaxAnisotropy=16
paltex=0
large_framebuffer=1
logz=0
fba=1
aa1=0
mipmap=1
accurate_date=0
UserHacks=1
extrathreads=2
resx=1024
resy=1024
```

**Comment by gregory38** [comment]
Ah yes this hack. Do you have line (native no hack) in both dx and ogl ? Try to uncheck large fb too.

**Comment by vsub** [comment]
If the hack is not enabled,the lines are visible in all HW renderers and large fb on/off have no effect

**Comment by gregory38** [comment]
Could you test gsdx 1.4 (or even)

**Comment by vsub** [comment]
1.4 and the latest beta act the same way,the games need that hack in native.
If it matters,I'm using AVX2

**Comment by vsub** [comment]
I don't know since when but while using GSdx from v1.5.0-dev-1263-gde480ec(I didn't tried the latest beta)the lines inside the characters are not visible even at 8x scaling and without enabling the sprite hack

**Comment by vsub** [comment]
Not sure but probably yes.
If something happen again,I'll open it again(If I can that is,I've never opened closed issues by me)
