### ISSUE TITLE
Tekken 5 NTSC-U : Progressive Scan Screen Shaking

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1413]
**Game** : Tekken 5 (NTSC-U Version)
**Activate Progressive Scan :** Go to Options menu and select it
**Mode :** Software and Hardware have the issue
**Interlacing :** Auto

The screen will shake during the game after the option activated, can be mostly seen in the pause menu.

This is not an issue with my TV, I can play Burnout 2 or Dragon Ball Z Budokai 3 in progressive scan without screen shaking. Also, some people on the forums mentionned the same bug too.

**Comment by refractionpcsx2** [comment]
Try cycling the Interlacing mode to "none", I think it only auto detects that option when the game starts, of course the progressive scan option comes later.

**Comment by Catarax** [comment]
The shaking problem still occurs on "none", but it's even worst, the normal rendering ouput will shake too.

**Comment by refractionpcsx2** [comment]
hmm. that almost suggests the game is doing interlacing and not progressive like it says :/

**Comment by DPersonalized** [comment]
Does using an older revision solve the issue?

**Comment by monsterjamp** [comment]
Is there an interlacing mode in which there is no "shaking"?

**Comment by ssakash** [comment]
Could you provide a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) with multiple frames of the issue ? I might try looking into it. (In case it's a bug on GSDX)

A brief explanation from the linked thread:
> The first thing you want to do is boot your game in PCSX2 and get to whatever part has the bug. Then to generate the dump you press SHIFT + F8 for a single frame or CTRL + SHIFT + F8 for multiple frames. If you use the multi frame option, the important thing to note is that how long you hold down the key combination determines how long the GS dump is. If you press for 4 seconds, you get a 4 second dump. What you want to do is hold the keys long enough to capture the entirety of the graphics bug.

**Comment by Catarax** [comment]
GS Dump, https://mega.nz/#!KNZzAT7K!epNaonPoUeUYpM8j0mCOJ6Kl9ssIvx7wITZOXaRJ3Bs
(Pause Menu, Progressive Scan enabled)

If it's not enough, let me know.

**Comment by ssakash** [comment]
Hmm, GS register values seem to be sane and it does seem to use progressive scan mode (HDTV 480P).

```
PCRTC Log Dump #1
Video Mode : 480P 
Double Scan Flag : Disabled 
SMODE2 Registers : INT: 0 , FFMD : 1 , DPMS : 0 
DISP Output1 : Width: 1  , Height : 1 , Left: 0 , Top: 0 
DISP Output1 Registers: DX:0  , DY:0  , DW:0  , DH:0 , MAGH: 0 , MAGV: 0
DISP Output2 : Width: 640  , Height : 448 , Left: 156 , Top: 51 
DISP Output2 Registers: DX:312  , DY:51  , DW:1279  , DH:447 , MAGH: 1 , MAGV: 0
FRAME Output1 : Width: 1  , Height : 1 , Left: 0 , Top: 0 
FRAME Output2 : Width: 640  , Height : 448 , Left: 0 , Top: 0 
Real Size of Image : Width: 640 , Height: 448 
```

I can't look further into the issue without a block dump.

**Comment by ssakash** [comment]
@Catarax 

FWIW, could you check whether the issue exists on older versions like ``0.9.8 / 1.2.1`` ?

**Comment by Catarax** [comment]
**Block Dump** 
You can change the progressive scan from the options menu to debugg only :
https://mega.nz/#!PYxQGZAC!nXz4MyW-cR05pFaaYUsNdZciF1fsTnRQBO6FoeEcjeA

1.2.1 have the same issue. Can't find the 0.9.8 on internet.

**Comment by ssakash** [comment]
Thanks for the block dump. I'll look into it tomorrow, way past my bed time right now.

>1.2.1 have the same issue. Can't find the 0.9.8 on internet.

Here you go : http://pcsx2.net/download/category/34-pcsx2-v0-9-8.html

**Comment by ssakash** [comment]
Hmm, could you provide a bigger block dump ?  I couldn't even enter the main menu with this one. it crashes at the part where it says ``Accessing Memorycard Slot1 ``

> Block 207360 not found in dump
Block 207361 not found in dump
Block 207362 not found in dump
Block 207363 not found in dump
Block 207364 not found in dump
Block 207365 not found in dump
Block 207366 not found in dump
Block 207367 not found in dump
Block 207368 not found in dump

**Comment by Catarax** [comment]
Ah sorry, i've done a better one (tested also) :
https://mega.nz/#!OMonBAQR!M-GJHEFN2tliIoqzEjqDev3bKoafWq1pxl5hP0JSfdU

**Comment by ssakash** [comment]
Block dump still crashes before reaching main menu. same for the one provided at #1419 

>Block 209232 not found in dump
Block 209233 not found in dump
Block 209234 not found in dump
Block 209235 not found in dump
Block 209236 not found in dump
Block 209237 not found in dump
Block 209238 not found in dump
Block 209239 not found in dump
Block 209240 not found in dump

**Comment by ssakash** [comment]
Never mind, apparently skipping those videos made me bypass those errors. sorry for the trouble !

**Comment by ssakash** [comment]
I've managed to fix the issue but it's quite a weird fix. possibly my fix is a hack and there is something else causing the issue on this game (or) this game is quite weird.

**Comment by MrCK1** [comment]
This also happens in Band Hero when the game is paused. Previously, Progressive Scan could not be used because text would be invisible.

**Comment by TheHidingNoob** [comment]
SOLVED: just enable Wild Arms Offset in hardware hack and use progressive scan.

**Comment by Catarax** [comment]
Nice find, work great on Tekken 5.

**Comment by tabnk** [comment]
No, wild arms offset does fix shaking. However, Tekken 5 progressive mode will introduce square shape distortion in some scene.

**Comment by TheHidingNoob** [comment]
Didn't notice that, can you make a screenshot of scenes where this appears?

**Comment by tabnk** [comment]
Here is an example 

![alt text](http://oi60.tinypic.com/2ylvke9.jpg)

**Comment by FlatOutPS2** [comment]
Did you try OGL with CRC on Partial or lower and half-pixel offset?

**Comment by tabnk** [comment]
Tried OpenGL with all possible setting I'm can click :). Generally outcome will still be distorted after awhile.

**Comment by TheHidingNoob** [comment]
Now i see what you mean. Which version do you use, with the newest build, I don't have the distortion anymore. It could also be vu cycle stealing or one of the hardware hacks in the gdsx plugin. Try disabling them all except wild arm and align sprite.

**Comment by refractionpcsx2** [comment]
I thought those strange boxes had been fixed? I remember seeing it somewhere but I can't find it.

**Comment by tabnk** [comment]
No, it never fixed all. From official 1.4.0 till latest GIT build. :) I'm will give one more try with latest GIT build with all setting as new.

**Comment by tabnk** [comment]
Tekken 5 on pcsx2-v1.5.0-dev-925

![gsdx_20160701202306](https://cloud.githubusercontent.com/assets/10874582/16521480/c56300f4-3fc9-11e6-9c59-4bc33a30f61c.png)

**Comment by TheHidingNoob** [comment]
It had to be something with the gdsx plugin, can you make a screenshot of all settings of the graphics plugin menu?

**Comment by gregory38** [comment]
I did a hack to fix it. But then I did a new version that broke it again. I need to come back to it.  (Too much open topic)

**Comment by Catarax** [comment]
**Latest build + Progressive Scan** 

In Arcade Mode, this stage doesn't have the black bar in start menu (no problem in Practise Mode) :
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/18052533/2dcc6fea-6dfb-11e6-825f-a4619b11b2e5.png)

**Practise/Training Mode :**

![screenshot_5](https://cloud.githubusercontent.com/assets/3964507/18052598/8e365788-6dfb-11e6-8121-5ddc7a1613a3.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/3964507/18052602/92e4591a-6dfb-11e6-9f59-b4f6435b9c84.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/3964507/18052603/94d33a02-6dfb-11e6-84ce-4014f0249e1d.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/18052606/99f1db10-6dfb-11e6-96a0-c5b8e240abdf.png)
