### ISSUE TITLE
Burnout 3: Takedown NTSC - Visual, bloom-like streaks cover screen in multiplayer

### ISSUE THREAD

**Issue by Two-Tone** [PCSX2/pcsx2#1415]
-Description: In all but one multiplayer modes the game is in splitscreen and while in splitscreen mode the screen has these vertical bloom-like streaks that cover half the screen. If a player boosts, then their half of the screen will become near completely covered

-Screenshots: http://imgur.com/a/gi6Rb  Screenshots include additional info, such as what the artifacts look like in each hardware mode, what the game looks like in software, etc.

In this gifv you can actually tell that the artifacts are actually sort of like reflections of the surrounding area. http://i.imgur.com/QDml4rM.gifv

-How to replicate: Start any multiplayer game except Party Mode - Solo 

-Plugin settings/workaround: Set skipdraw to 3 in the HW Hacks options area in GSdx. Breaks different UI elements in game.

-PCSX2 version: pcsx2-v1.5.0-dev-903-gab1ab7b-windows-x86

-PCSX2 options: Happens with all emulation presets, with and without speedhacks

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins

-Last known version to work: Never 

-PC specifications: http://pcpartpicker.com/list/NpJ99W 
-OS Win7 Ultimate 64bit

**Comment by ssakash** [comment]
Is the issue present on OpenGL (hardware mode) ? make sure to have ``Disable depth emulation`` disabled.

**Comment by Two-Tone** [comment]
Yes. 

Could have sworn that I had remembered to mention that the linked screenshots have additional info, such as what the artifacts look like in each hardware mode, what the game looks like in software, etc.  Mentioning that now.

**Comment by DPersonalized** [comment]
I hate to be _that_ guy, but this is a known issue, and is documented here: http://wiki.pcsx2.net/index.php/Burnout_3:_Takedown

**Comment by Two-Tone** [comment]
There should still at least be a bug report for this.

Also, the listed workaround in that wiki does not work for me.  The only thing that did was setting skipdraw to 3.

**Comment by gregory38** [comment]
Yes yes, what you see is the depth buffer. As you can see on openGL the buffer begin to be emulated on the left. And then it wrongly reuse the same buffer 5 times. Note preload frame hack will impact the rendering (but maybe not better).

**Comment by Two-Tone** [comment]
Preload frame hack did affected it, but not for the better. http://imgur.com/a/2RVTm

So it's definitely the depth buffer.

**Comment by gregory38** [comment]
```
T:Oth	ID:2388	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x1a40, F:0x0)
T:Oth	ID:2388	S:Info	=> TC: Lookup Target(Depth) 1280x1024, miss (0x1a60, F:0x31)
T:Oth	ID:2388	S:Info	=> TC: dst Color hit (full): 8 (0x8c0, F:0x0)
```
The main issue is this draw call. The depth buffer overlap the color buffer.
Basically when you write the color of pixel (0, 0), a depth value will be written in the pixel (64, 32). And it is actually more complex as the depth value is used as a blending parameter too.

Blending is (Cs - Cd) * 2. Color Source is a previous rendering of the framebuffer, and Cd is likely the depth information. But it might depend on the race condition in the HW.

OoO, there is another nasty bug. The previous draw call will delete the buffer in 0x1a40.
```
T:Oth	ID:2385	S:Info	=> TC: Lookup Target(Color) 1280x1024, hit Depth (0x1a40, F:0x0 was F:0x31)
T:Oth	ID:2385	S:Info	=> TC: Lookup Target(Depth) 1280x1024, hit: 3 (0x1a40, F:0x31)
T:Oth	ID:2388	S:Info	=> TC: Remove Src Texture: 159 (0x1a40)
T:Oth	ID:2388	S:Info	=> TC: InvalidateVideoMemType: Remove Target(Depth) 3 (0x1a40)
T:Oth	ID:2388	S:Info	=> TC: InvalidateVideoMemType: Remove Target(Color) 209 (0x1a40)
```
Summary it is full of bugs :)

**Comment by gregory38** [comment]
Hum looking at the SW renderer. It seems to only write a constant (on my example 191,191,191) into the depth buffer. Maybe I could intercept the draw call and replace it with a manual clear.

**Comment by DPersonalized** [comment]
Also, would this be a different issue to the streaks that cover the screen in single player?

**Comment by Two-Tone** [comment]
Single player doesn't have any streaks

Or at least I've never seen any.

**Comment by gregory38** [comment]
Even with CRC off ?

**Comment by Two-Tone** [comment]
With CRC set to off I do see the streaks (in single player), minimal reduces the number of streaks greatly, and partial & higher gets rid of them entirely.

**Comment by DPersonalized** [comment]
For some reason, with OpenGL on the latest Git build, using any custom resolution at all on Burnout Revenge comes closer to fixing the streaks issue than all multiples of native (the non-custom resolutions.) This doesn't seem to work with Burnout 3, either. Strange.

**Custom resolution of 1666x1234**
![gsdx_20160710145719](https://cloud.githubusercontent.com/assets/8225831/16713981/5e65d66a-46ae-11e6-9369-0070001c9826.png)

**Native**
![gsdx_20160710145731](https://cloud.githubusercontent.com/assets/8225831/16713986/786cf408-46ae-11e6-823e-20301c350596.png)

**Comment by gregory38** [comment]
Yes more or less expected. Completely broken but less visible.

**Comment by Catarax** [comment]
**Single player for Burnout 3 NTSC in Progressive Scan 480p (need: X+Triangle at boot) is unplayable also (Hardware Mode) :** 👎 

![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/19346651/d99704b8-9144-11e6-9d4a-f56383b9dada.png)

**Progressive Scan (Software Mode) 👍  :**

![software](https://cloud.githubusercontent.com/assets/3964507/19346853/dab17a9e-9145-11e6-96e3-1f9ad205dd17.png)

**Single player without Progressive Scan (Hardware Mode):** 👍 

![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/19346718/21b374c0-9145-11e6-8f50-265111a81fe8.png)

Didn't created a new issue due to their resemblance.

Hardware Mode => OpenGL (Hardware), Aggressive CRC, no hacks, no blending accuracy

Using latest buid: v1.5.0-dev-1441-g733fd79

**Comment by andwan0** [comment]
Okay, I know there are work arounds/hacks to get around these graphical issues. But still, would be nice to have proper fix?

**Comment by MrCK1** [comment]
@UlsterRose Can you test this with https://github.com/PCSX2/pcsx2/pull/2122?

**Comment by UlsterRose** [comment]
Still getting the streaks with #2122. Should I be using `ENABLE_ACCURATE_BUFFER_EMULATION`?

**Comment by MrCK1** [comment]
No, you'd have to compile.your own bud for that. Is the effect lessened/worse in 2x native, ect. or custom reslolutions?

**Comment by UlsterRose** [comment]
I'd say there's a negligible difference between native and scaled resolutions in terms of how bad the effect is. That's with default settings, OpenGL.

**Comment by MrCK1** [comment]
FWIW, using Large Framebuffer gets rid of these streaks in HW mode

**Comment by lightningterror** [comment]
I forgot to mention this a while back but I did update the crc hacks to work on multiplayer mode as well. Bad draw calls will be skipped.

**Comment by jeremybris** [comment]
I used to experience this, but I don't anymore.

**Comment by MrCK1** [comment]
@jeremybris the issue is still active actually. It's just that the bad draws will be skipped as LT mentioned above.

**Comment by jeremybris** [comment]
@MrCK1 Oh, ok. I don't understand the technical jargon. :P

**Comment by Two-Tone** [comment]
Happy to FINALLY see this fixed!
