### ISSUE TITLE
All games: xbox controller and OnePad have sticky directions

### ISSUE THREAD

**Issue by PaulBGD** [PCSX2/pcsx2#1418]
Whenever I press up, down, left, or right, it will keep moving in that direction until I press a different direction.

Ubuntu 16.04

```
PCSX2 1.4.0-0- compiled on Jan  6 2016
Savestate version: 0x9a0b0000

Host Machine Init:
    Operating System =  Linux 4.4.0-24-generic x86_64
    Physical RAM     =  16008 MB
    CPU name         =  Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    Vendor/Model     =  GenuineIntel (stepping 02)
    CPU speed        =  3.298 ghz (12 logical threads)
    x86PType         =  Standard OEM
    x86Flags         =  bfebfbff 7ffefbbf
    x86EFlags        =  2c100000

Loading plugins...
    Binding   GS: /usr/lib/games/PCSX2/libGSdx-1.0.0.so 
    Binding  PAD: /usr/lib/games/PCSX2/libonepad-1.1.0.so 
    Binding SPU2: /usr/lib/games/PCSX2/libspu2x-2.0.0.so 
    Binding CDVD: /usr/lib/games/PCSX2/libCDVDnull.so 
    Binding  USB: /usr/lib/games/PCSX2/libUSBnull-0.7.0.so 
    Binding   FW: /usr/lib/games/PCSX2/libFWnull-0.7.0.so 
    Binding DEV9: /usr/lib/games/PCSX2/libdev9null-0.5.0.so 
Plugins loaded successfully.
```

**Comment by Catarax** [comment]
When you map a key with pcsx2 on a controller, at the first try, it may map a weird direction control and the second time, it'll map something right. 
And then you have to delete the wrong key you set at start and check if the game don't move anymore.
A bit messy.

I got some of theses mistakes, when i tried to map my 360 guitar to pcsx2 recently.

**Comment by PaulBGD** [comment]
I remapped every button and still no luck.

**Comment by Catarax** [comment]
Even a double time the key until you get the correct value? Possible that's more a linux issue about detecting here.

**Comment by Catarax** [comment]
Found a fix, only check "XINPUT" controller in Lilypad settings before going to map a 360 controller.

**Comment by PaulBGD** [comment]
That'd be nice, but sadly linux only has onepad.

**Comment by gregory38** [comment]
Could you test the PR #1895 ? If you pad is correctly detected, the mapping will be done automatically and hopefully right.

**Comment by gregory38** [comment]
Please could you test onepad 2

**Comment by PaulBGD** [comment]
Did #1895 make it into a release?

**Comment by gregory38** [comment]
It was merged into master branch. So you need a recent build such as daily ppa for example
