### ISSUE TITLE
Tekken 5: Tekken 3 (240p game) not displayed directly in Hardware Boot

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1419]
**Game :** Tekken 3 in Tekken 5
**Region :** NTSC-U/ PAL
**Boot Method :** Full Boot OpenGL (Hardware)
**Issue :** When you launch Tekken 3 (240p emulated game) in Tekken 5, you'll hear the sound of the game but there will be an infinite blackscreen.

**Fix 1)** Doing F9 will display the 240p game properly in Software Mode, then doing again F9 will display the game in Hardware Mode like it should (which has no particular trouble at all!). 
**Fix 2)** A pure Software Boot will display the 240p emulated game by default without trouble.

**Block Dump (NTSC-U)**
[Download](https://mega.nz/#!bBhSSYrK!JWTtKL_7fpNJ7uv5NHZ_tJrS-pu6Zv6J4AAle2KAOZ0)

**Process to reproduce** :
1) Go to "Arcade History" on the main menu
2) Choose "Tekken 3"
3) You'll hear "Good Morning!", then you should have the infinite blackscreen with the game music along, do 2 times F9 to see the game in hardware, that's what should be fixed.

**Note :**
Tekken 1 & 2 run properly directly in Hardware Boot, no work needed on them.

Hope someone could fix it, thanks!

**Comment by ssakash** [comment]
I checked the dump, issue seems to be fixed with ``OpenGL (hardware mode)`` and ``Preload data frame`` enabled. can you confirm ?

**Comment by FlatOutPS2** [comment]
Yeah, the preload fix solves this or OGL.

**Comment by Catarax** [comment]
Yes, fixed with Preload data frame checked.

**Comment by gregory38** [comment]
A note somewhere would be nice (for example the tooltip)
