### ISSUE TITLE
Harry Potter Philosopher's Stone - Severe slowdowns since 20160515 build (OpenGL only)

### ISSUE THREAD

**Issue by baptiste0602** [PCSX2/pcsx2#1420]
Harry Potter Philosopher's Stone has severe slowdowns since 20160515 GSDX build in OpenGL.
No problem in DX9/11.

My specs : Windows 10 - Nvidia GTX 670

**Comment by gregory38** [comment]
Which build exactly ? This one : v1.5.0-dev-756-ge776118 ?

Could you generate a me multi-frame gs dump. Dump ought to be around 100MB-1000MB (MAX) uncompressed => http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by baptiste0602** [comment]
Sorry, I forgot to indicate the build time.
I use "orphis automated builds", and it happen between "2016-05-14 17:18:16" :(OK) and "2016-05-15 15:00:52" (KO), so it could be these revisions : 
v1.5.0-dev-752-g8206032
v1.5.0-dev-751-gc054b09
v1.5.0-dev-750-gcaacb1d
v1.5.0-dev-749-gd47d9e5

I'll generate a GS dump when I get home.

**Comment by gregory38** [comment]
Timestamps aren't necessary in the chronological order. But I think I know the code that badly impact the perf. I guess you didn't have `accurate date` enabled on the older build ? Could you compare the speed of those setups
* old build accurate date disabled
* old build accurate date enabled
* new build accurate date disabled
* new build accurate date enabled

**Comment by baptiste0602** [comment]
I confirm no differences with/without "accurate date" option.
Here the GS dump : https://www.dropbox.com/s/yczr5yje2nwvy08/gsdx_20160620202115.zip?dl=0

**Comment by gregory38** [comment]
Could you edit the GSdx.ini file to manually disable an openGL extension. Use 0 for the following option.
```
override_GL_ARB_clear_texture = 0
```

**Comment by baptiste0602** [comment]
It's OK with GL extension disabled.
No change with 8bits texture enabled/disabled.

**Comment by gregory38** [comment]
What do you mean by OK ?
If you disable the extension, you will get back to full speed ?

**Comment by baptiste0602** [comment]
Yes, constant fullspeed.

**Comment by baptiste0602** [comment]
Thanks :+1:

**Comment by gregory38** [comment]
Well thanks to you for test and report ;)
