### ISSUE TITLE
GSdx32-AVX2.dll causes emulator crash

### ISSUE THREAD

**Issue by emko** [PCSX2/pcsx2#1423]
Running portable with First Time Configuration 

First screen language selector you press next and the program crashes 
i mange to recorded a video on what the progress on that screen was at it stopped at 
GSdx32-AVX2.dll before closing.

Removing GSdx32-AVX2.dll makes the configuration system work again. Once the emulator is configured i tried adding back that dll and it works fine untill you try open the plugins/bios selector menu then the program again crashes.

i have a i7 2600K this cpu does not support AVX2 maybe the emulator is trying to use it?

tested on v1.5.0-dev-911-g36e82ab	

```
PCSX2 1.5.0-20160619134551 - compiled on Jun 19 2016
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 14361), 64-bit
	Physical RAM     =  24543 MB
	CPU name         =  Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
	Vendor/Model     =  GenuineIntel (stepping 07)
	CPU speed        =  3.502 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 1f9ae3bf
	x86EFlags        =  28100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Reserving memory for recompilers...

Loading plugins...
	Binding   GS: C:\Emulators\pcsx2-v1.5.0\plugins\GSdx32-AVX.dll 
	Binding  PAD: C:\Emulators\pcsx2-v1.5.0\plugins\LilyPad.dll 
	Binding SPU2: C:\Emulators\pcsx2-v1.5.0\plugins\SPU2-X.dll 
	Binding CDVD: C:\Emulators\pcsx2-v1.5.0\plugins\cdvdGigaherz.dll 
	Binding  USB: C:\Emulators\pcsx2-v1.5.0\plugins\USBnull.dll 
	Binding   FW: C:\Emulators\pcsx2-v1.5.0\plugins\FWnull.dll 
	Binding DEV9: C:\Emulators\pcsx2-v1.5.0\plugins\DEV9null.dll 
Plugins loaded successfully.

(GameDB) 9705 games on record (loaded in 129ms)
[wx] Failed to load shared library 'C:\Emulators\pcsx2-v1.5.0\plugins\DEV9ghzdrk.dll' (error 126: the specified module could not be found.)


```

**Comment by DPersonalized** [comment]
Fairly certain this is the same as #999.

**Comment by gregory38** [comment]
Yes same.

**Comment by Blackbird88** [comment]
So what exactly is the reason for all the GSdx builds being separate?

**Comment by gregory38** [comment]
What do you mean ? You want a big library that dispatch to the good isa ?

Honestly the bad code is in PS1 emulation due to constant in global variable. Just moving the code into dynamic variable might be enough and it won't impact the perf too much.

**Comment by Blackbird88** [comment]
It was just a question. I am not programmer. I am curious why it has to be separate.

**Comment by mirh** [comment]
#796

**Comment by pal1000** [comment]
Intel(R) Core(TM) i7-2600K is part of 2nd generation Intel Core processors known as Sandy Bridge. AVX2 is only supported on 4th generation Intel Core processors and up. As @mirh pointed out the issue here is that the plugin version is listed despite being unsupported.
