### ISSUE TITLE
LilyPad : Multitap PS1 not supported in Crash Bash (ePSXe)

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1424]
**Game:** Crash Bash (USA)
**Issue :** ePSXe doesn't recognize at all a multitap linked from LilyPad in Crash Bash, even with the PAD 2 unplugged from LilyPad.
**LilyPad version :** Latest with the analog mode fixed
**LilyPad config:**
- PAD 1A
- PAD 1B
- PAD 1C
- PAD 1D
- PAD 2 Unplugged

**Comment by FlatOutPS2** [comment]
Which ePSXe version did you use?

Are you using a bios or using HLE? There are some problems with HLE and third party input plugins for ePSXe.

**Comment by Catarax** [comment]
Ah too bad.
Will take the native epsxe mutltitap support then, but the rumble is really bad compared to LilyPad (too heavy on constant/sinus).
You can close this I think.

**Comment by FlatOutPS2** [comment]
We could leave it open as a feature request. I'll have a look at it anyway.

**Comment by lightningterror** [comment]
I'll be closing this since our focus is PCSX2 and not ePSXe.
