### ISSUE TITLE
Use F11 as alternate fullscreen binding

### ISSUE THREAD

**Issue by Two-Tone** [PCSX2/pcsx2#1425]
In a lot programs (Such as Blender, GIMP, Firefox, and even some games) the function key F11 is an alternate method of making the program fullscreen. I know we have alt+enter, but F11 as an alternate option wouldn't hurt and is easier to hit (in my opinion).

**Comment by avih** [comment]
Are you aware that you can customize it yourself? Or is this request just to make it the default?

See https://github.com/PCSX2/pcsx2/blob/master/bin/PCSX2_keys.ini.default

**Comment by FlatOutPS2** [comment]
There's an alternate option by clicking the left mouse button twice. Should be easier to hit than Alt+Enter too if you're playing with just they keyboard.

**Comment by avih** [comment]
> There's an alternate option by clicking the left mouse button twice

Right, you can enable it via:
Menu > Emulation settings > GS Window > "Double click toggles full screen".

**Comment by FlatOutPS2** [comment]
It's on by default. :p

**Comment by avih** [comment]
I know, I added the double-click feature and the key customization ;)

**Comment by Two-Tone** [comment]
I was not aware. It didn't occur to me to look for for an ini file, although I know see that the default file is in the parent directory.

I do think it would be good to have it as an alternate option

**Comment by ssakash** [comment]
> I do think it would be good to have it as an alternate option

the ``F11`` could be used for something else instead, why do we need two hotkeys for a certain function ?

**Comment by avih** [comment]
> I do think it would be good to have it as an alternate option

Unfortunately our shortcuts system currently doesn't support two different shortcuts for the same action.

Also, while I do agree that many applications use F11 to toggle full screen, in games it's usually ALT+Enter, and I think PCSX2 is closer to a gage system than to "normal" application.

**Comment by Two-Tone** [comment]
> the `F11` could be used for something else instead, why do we need two hotkeys for a certain function?

Well, like I said in the parent post, F11 is widely used as a shortcut for fullscreening the running application.

But avih has pointed out the limitation that actions can't be bound to multiple shortcuts, so it's all moot.

**Comment by avih** [comment]
Shall we close this request then? or is there anything else to do here?

**Comment by refractionpcsx2** [comment]
I thought full screening was universally Alt+Enter?

**Comment by Nobbs66** [comment]
depends on the application. Most browsers are F11. Blender is ctrl+f11 I
believe.

**Comment by avih** [comment]
> while I do agree that many applications use F11 to toggle full screen, in games it's usually ALT+Enter, and I think PCSX2 is closer to a game system than to a "normal" application.

**Comment by refractionpcsx2** [comment]
> while I do agree that many applications use F11 to toggle full screen, in games it's usually ALT+Enter, and I think PCSX2 is closer to a game system than to a "normal" application.

that was my thinking. I always considered the emulator a "game", it's not really a browser or a 3d editor .

**Comment by avih** [comment]
Anyway, closing this now. If anyone thinks there's more to do here, feel free to post again and we can re-open it.
