### ISSUE TITLE
Destroy all Humans 2! NTSC-U - Material stretching across screen

### ISSUE THREAD

**Issue by EvilWiffles** [PCSX2/pcsx2#1436]
Emulator: pcsx2-v1.5.0-dev-923-g1f4f55b-windows-x86
Game: Destroy all Humans 2!
CRC: 42DF8C8C - SLUS 21439
Platform: Windows 10
GSDX DirectX 11 SW

Description: Garbage stretching across screen for split seconds, obstructing view. Rare occasion that it stays on screen. Likely mesh warping?
Example:
![glitch](https://cloud.githubusercontent.com/assets/18126664/16432037/f954e8a2-3db5-11e6-9d98-b5bfdf956387.png)

Fix: Use full clamping mode in EE/IOP under EE/FPU Advanced Recompiler Options.

Request: Add this to automatic gamefixes.

**Comment by Catarax** [comment]
So it requires eeClampMode = 3 in the gameIndex file, i'm right? 
Can do it (need confirmation from someone).

Also, can you check if the same thing is necesarry for the PAL version? (Probably too)

**Comment by EvilWiffles** [comment]
I believe so.
This doesn't solve peds and other objects sometimes falling through the map, unfortunately.

Doesn't appear to happen with PAL version.

**Comment by Catarax** [comment]
Try some other clamp modes or options to see if this bug could be fixed. I think it's possible.

**Comment by ramapcsx2** [comment]
Seconded.
Please check all combinations of clamp and round modes for EE/FPU and VUs.
It would be bad if the graphics fix caused the logic bug but it's possible.

**Comment by BreakPoints** [comment]
The following fixes the glitch:
In EE/FPU setting Clamping to Full, doesn't matter what the Round Mode is set to.
In VUs setting Clamping to None and Round Mode to Nearest or Positive.

**Comment by MrCK1** [comment]
Can someone verify whether or not the Rounding/Clamping modes above fix this issue? If so, they will have to be added to the GameDB.

**Comment by atomic83GitHub** [comment]
EE clamp mode to Full seems to be the correct fix, however the "falling through floor" issue need some investigation, we definitely need someone to test.
