### ISSUE TITLE
[Linux] OnePAD Gamepad 1 does not work

### ISSUE THREAD

**Issue by mariuszskon** [PCSX2/pcsx2#1441]
PCSX2 version: 1.5.0.r925.a065a1d-1 (from https://aur.archlinux.org/packages/pcsx2-git) due to #1402 

Issue: Using a keyboard or a Wii U Pro Controller (and most likely anything else) as Gamepad 1 in OnePAD does not work. There is no feedback (red buttons) shown (even with the Wii U Pro Controller, which **does** show feedback **if it is Gamepad 0**) and it does not work in games. However, it does get configured (configuration files appear to be correctly altered). Gamepad 0 works. Therefore, local multiplayer cannot be achieved.

Two OnePAD configs are attached (renamed to .ini.txt to help GitHub handle them)
[kb0pro1.ini.txt](https://github.com/PCSX2/pcsx2/files/342712/kb0pro1.ini.txt)
[pro0kb1.ini.txt](https://github.com/PCSX2/pcsx2/files/342714/pro0kb1.ini.txt)

How to replicate: Setup Gamepad 0 and Gamepad 1 in OnePAD, and try using Gamepad 1.

Last known version: Unknown, may have worked before the giant OnePAD upgrade.

Spces (probably irrelevant, but hey why not):
Host Machine Init:
	Operating System =  Linux 4.6.3-1-ARCH x86_64
	Physical RAM     =  3954 MB
	CPU name         =  AMD Athlon(tm) II X2 260 Processor
	Vendor/Model     =  AuthenticAMD (stepping 03)
	CPU speed        =  3.211 ghz (2 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 00802009
	x86EFlags        =  efd3fbff

Hope I didn't miss anything obvious.

PS Pretty much everything else works fine, good job :+1:

**Comment by gregory38** [comment]
Hum, it used to work. I really need to spend some time on the pad plugin.

**Comment by mariuszskon** [comment]
So you can confirm that this is also an issue for you? I was thinking that I might be alone :wink:

**Comment by aFoxNamedMorris** [comment]
Happening here as well. 
Xubuntu 15.04 64-bit
Linux Kernel 4.5.7

**Comment by gregory38** [comment]
Ah no I don't confirm, I haven't used my 2 pads for a too long time. I did a quick check before the new GUI integration. There is maybe a limitation with the mix of keyboard and pad.

**Comment by ddg1** [comment]
Can confirm this has happened to me since I started using PCSX2 on Linux, about 2 years ago. I've never been able to get the second pad working, but I always thought it was related to my system (Gentoo 64-bit).

**Comment by CodePhase** [comment]
I've been able to use 2 Playstation 3 Dualshock 3 controllers as Gamepad 0 and Gamepad 1 very recently.  I can't vouch for the code base as of about a week ago though because I upgraded to Fedora 24 and now can't compile PCSX2 to test it due to possibly a gcc error.  Once I get that worked out I'll report back.

It may be necessary to note that I was using SDL 1.2, GTK 2, and wxWidgets 3 at that time however.

**Comment by gregory38** [comment]
I'm pretty sure the bad interaction is with the keyboard. Code is new (and not from me). I quickly check the 2 pad before the merge but not the keyboard so...

**Comment by aFoxNamedMorris** [comment]
it's just annoying to not be able to use my Xbox360 controllers at all. I
don't have any other gamepads to test with. Sorry.

**Comment by gregory38** [comment]
@mariuszskon 
Looking at the code, it seems not (yet?) possible to setup mouse/keyboard/wiimote as 2nd pad. But it could work as 1st pad.

**Comment by gregory38** [comment]
I pushed some fixes to allow to setup the keyboard as 2nd pad. (note didn't tested the first pad).
However mouse/wiimote is limited to the 1st pad. It would need to redo the code to probe state instead to rely on event.

**Comment by ddg1** [comment]
In my case, it works now. Thank you!

**Comment by mariuszskon** [comment]
@gregory38 wow I didn't know that the second gamepad is so different from the first in terms of code. Luckily, I don't need mouse. Couldn't use my PC for some time, but I'll try to get back to you soon.
Oh yeah it's not technically a wiimote, but a pro controller (it's like a regular gamepad, not a vertical stick controller).

**Comment by gregory38** [comment]
For joystick we read the new state of the device and you compare it with the old state. During the configuration, a joystick will be mapped to a gamepad.

For keyboard/mouse it is handled differently, we receive an event (like 'a' pressed or 10 pixels left mouvement). There is no direct association of an event to a pad hence the bug. I cheated a bit for keyboard (because button are mapped to a single pad) but it won't work if someone plug 2 keyboards.

**Comment by mariuszskon** [comment]
Hey, you're amazing! Works fine for me here (with identical config and all)! Obviously, it would be desirable to have better support for keyboards etc., but I got what I wanted. Thanks!

**Comment by gregory38** [comment]
:smiley: 

Yes, multiples keyboards/mice will be nice to have but nobody complain so far, so very low priority.
