### ISSUE TITLE
Harry potter and the chamber of Secrets Audio Bug

### ISSUE THREAD

**Issue by mrchrismania** [PCSX2/pcsx2#1445]
the game runs at full speed no issues but the audio is constantly crackling and on Dolphin emulator ive tried the LLE and HLE recompilers even OpenAL and changing the latency but doesnt make a difference any help would be appreciated.

**Comment by ssakash** [comment]
I think you have come to the wrong place, Dolphin issue tracker is [over here](https://bugs.dolphin-emu.org/projects/emulator/issues)
