### ISSUE TITLE
Any chance for an iOS port ? 

### ISSUE THREAD

**Issue by nfsvsgta** [PCSX2/pcsx2#1449]

**Comment by FlatOutPS2** [comment]
No. Unless you're fine with waiting another 10 years or so.

**Comment by refractionpcsx2** [comment]
There is unlikely to be an android or iOS port.  The emulator might work on a new intel based mac, especially if you're using bootcamp.

**Comment by nfsvsgta** [comment]
This was so since play! Is a ps2 emu on android/iOS thought u guys could help in it

**Comment by refractionpcsx2** [comment]
We have enough on our plates not to have time to work on another emulator.

**Comment by nfsvsgta** [comment]
Hah

**Comment by nfsvsgta** [comment]
Well if u get time please do look at it
