### ISSUE TITLE
Matrix Path Of Neo Graphical Bug Fixed

### ISSUE THREAD

**Issue by mrchrismania** [PCSX2/pcsx2#1451]
i have a fix for matrix path of neo as the game renders all textures blue and white. and makes all the graphics screw up aswell when using Direct3D11.  now there are three fixes that i believe should be updated

1. Use software Rendering this will render all the textures correctly *note Requires a High end Cpu*
2. Use OpenGL Hardware and you will notice all the textures and everything will render correctly aswell the only bug i have noticed with this is was a transparant black rectangle on the top half of the screen.
3.OpenGl software mode will also work and is the better option it reduces cpu overhead and will run much smoother than Direct3D11 Software Rendering.

**Comment by refractionpcsx2** [comment]
Thanks for the information, but it isn't really a lot of use here.  I would suggest you do a compatibility report on he forum under the public compatibility list section, be sure to read the sticky on how to structure it :)
