### ISSUE TITLE
[GSdx] GTA San Andreas colorfilter not working

### ISSUE THREAD

**Issue by aap** [PCSX2/pcsx2#1457]
The colorfilter in GTA SA stopped working some time ago...I tested in D3D9 HW mode (opengl stopped working for me somewhere between build 555 and 569 on my laptop).
This is how it currently looks:
![pcsx2_nocolorfilter](https://cloud.githubusercontent.com/assets/1521437/16776253/dfab001c-4864-11e6-841a-3b8546b14d4f.png)
This is how it looked before:
![pcsx2_colorfilter](https://cloud.githubusercontent.com/assets/1521437/16776256/e1899e16-4864-11e6-876a-e584ce690cd1.png)
It last worked in build 640 and stopped working in build 650, sadly I couldn't test any version in between because there is no download and I was to lazy to compile them myself.
I tried to analyze the effect with PIX and found that it's translated to four D3D9 calls in the working case but only two in the not working case. I hope this is an easy fix.
Here is a GS dump.
http://aap.papnet.eu/gta/files/gtasa_colorfilter_gsdump.7z

**Comment by gregory38** [comment]
@FlatOutPS2 
could you run the dump on both GL and DX. Thanks you. I didn't manage to reproduce it with openGL.

**Comment by FlatOutPS2** [comment]
I just ran the game. :p
I reproduced the issue with both DX11 and DX9, OGL does not have the regression.

The regression is caused by dev-644:
https://github.com/PCSX2/pcsx2/commit/de38963904140259ca1b398234e04931f545bbf8

**Comment by gregory38** [comment]
Thanks you. You're very efficient.

Just one line impact DX. The one that autoskip the depth effect. It was my guess on IRC.
```
tex = tex_psm.depth ? m_tc->LookupDepthSource(context->TEX0, env.TEXA, r) : m_tc->LookupSource(context->TEX0, env.TEXA, r);
```

**Comment by gregory38** [comment]
Ok. I manage to reproduce it when I disable the depth.
Here an extract of the log:
```
T:Oth	ID:990	S:Info	=> TC: Lookup Target(Color) 1280x1024, hit: 4 (0xa00, F:0x0)
T:Oth	ID:990	S:Info	=> TC: Lookup Target(Depth) 1280x1024, hit: 5 (0x1b80, F:0x31)


T:Oth	ID:993	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x1b80, F:0x31)
T:Oth	ID:993	S:Info	=> TC: dst Color hit (full): 4 (0xa00, F:0x0)

T:Oth	ID:996	S:Info	=> TC: Lookup Target(Color) 1280x1024, hit: 4 (0xa00, F:0x0)
T:Oth	ID:996	S:Info	=> LookupDepthSource not supported (0x1b80, F:0x31)

T:Oth	ID:996	S:Info	=> TC: Lookup Target(Color) 1280x1024, hit: 4 (0xa00, F:0x0)
T:Oth	ID:996	S:Info	=> LookupDepthSource not supported (0x1b80, F:0x31)
```
WTF ! The annoying texture is 0x1b80
So it is a depth in draw call 990 but the game will blit the buffer 0xa00 to 0x1b80 in draw call 993. Why the hell they don't uses a color format !

**Comment by gregory38** [comment]
@ssakash I'm not sure I will call it a bug. It is working on openGL. Situation got better when I disabled the auto-skip depth related draw call. But it broke tons of games (vertical band). New code kinds of added it back which avoid 90% of the bad case for Dx.

Anyway, maybe we can try to do something differently. When we hit a Z format
1/ search in depth buffer, if we find a source but we don't support conversion => skip draw call
2/ search color buffer which don't need conversion

The bad news is that I don't think (current) Dx shader will support the absolute texture coordinate.

**Comment by ssakash** [comment]
> 1/ search in depth buffer, if we find a source but we don't support conversion => skip draw call

Yes, sounds good. This is actually the older behavior unless I'm wrong. ( No other way to workaround it till D3D supports depth)

**Comment by gregory38** [comment]
Actually it is back to 1.2 behavior (don't remember when I did my first depth implementation). I think it could hit the buffer correctly but the issue is coordinate.

Old code rescales the depth framebuffer (as it is currently done for the color). However the new code uses a texture reference with absolute coordinate, rescaling is done on the fly when the depth texture is sampled. See sample_depth in glsl source code ( https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/res/glsl/tfx_fs.glsl ). I won't do it on Dx code, no free-time, no easy way to test & debug on my side.

**Comment by gregory38** [comment]
Hum before I forget. Need to test what will happen if we call the standard source lookup function if we don't have a hit in the first step.
