### ISSUE TITLE
gcc build failure in common/include/x86emitter/x86_intrin.h

### ISSUE THREAD

**Issue by GhettoGirl** [PCSX2/pcsx2#1467]
In the file ```common/include/x86emitter/x86_intrin.h``` there is a issue with the preprocessor code. GCC 6.1 jumps into the wrong block and fails with ```Intrin.h``` no such file. I was able fix this very easily by adding a ``` || defined(__GNUC__)``` to the if check. Could it be that cmake is using ```gcc``` instead of ```g++``` to compile this? Because ```__GNUG__``` is only defined in g++, but not in gcc.

I guess the is a bug in one the CMakeLists, but I'm not sure. Maybe you could just extend this check with my suggestion.

Regards

```c++
// Because nobody can't agree on a single name !
#if defined(__GNUG__) || defined(__GNUC__)

// Yes there are several files for the same features!
// x86intrin.h which is the general include provided by the compiler
// intrin_x86.h which is a compatibility layer (as this file) but with a BSD license
// x86_intrin.h, this file, which is another compatibility layer
#include "x86intrin.h"
#include "intrin_x86.h"

#else

#include "Intrin.h"

#endif
```

**Comment by gregory38** [comment]
Gcc will be used to compile file with a .c extension. Anyway a pull request will be nice :)
By the way did you build the extra plugins ?

**Comment by GhettoGirl** [comment]
yes ```./build.sh --clean --extra --rel```

**Comment by gregory38** [comment]
Thanks for the info

**Comment by GhettoGirl** [comment]
I made a pull request :)
