### ISSUE TITLE
Air Ranger Rescue: texture scrambling

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1473]
![arr1](https://cloud.githubusercontent.com/assets/15942346/17070115/8415874c-505a-11e6-8f91-c92859b0cf88.jpg)
![arr2](https://cloud.githubusercontent.com/assets/15942346/17070123/8549fa1c-505a-11e6-82f7-c0a4c4db339c.jpg)
-PCSX2 version: latest master, stable versions down to 0.9.1.
-PCSX2 options: Default, tried all options, hardware and software renderers
-Plugins used: Default, and ZeroGS
-Description: Textures scramble right in front of the camera(looks similar to issues usually solved by XGKick game fix), especially when flying close to the ground. Some textures are also missing on the ground. The scrambling might be triggered by the missing textures, at it seems to happen when the facing away from nearby missing ground textures.
-How to replicate: Start mission( and fly around).
-Last known version to work: PCSX2 v0.9.0 (2006)

**Comment by ssakash** [comment]
Just to be sure, is the issue also present on the interpreters ?

**Comment by FlatOutPS2** [comment]
Yes, I tried all the Emulation Settings options.

**Comment by FlatOutPS2** [comment]
I went even further back in time and found the issue doesn't happen in v0.9.0. It was first introduced by 0.9.1.

**Comment by kozarovv** [comment]
Note for future researchers. Game require tight EE - VU0 timings, similar case to Sega Superstar Tennis.

**Comment by stoniemahonie** [comment]
This is still (or again) an issue. You can see it in freeflight or the first mission almost immediatly. It is not the whole time but quite often. Happens in HW and SW. Used the WX version for the gs dump. Happens also on latest git version.

I also tested it on 1.7.0-dev-1298. Seems fine there.

[gs_20220725152553_Air Rescue Ranger _PAL-E__SLES-50953_scrambled_textures_5344.zip](https://github.com/PCSX2/pcsx2/files/9181570/gs_20220725152553_Air.Rescue.Ranger._PAL-E__SLES-50953_scrambled_textures_5344.zip)

**Comment by refractionpcsx2** [comment]
> This is still (or again) an issue. You can see it in freeflight or the first mission almost immediatly. It is not the whole time but quite often. Happens in HW and SW. Used the WX version for the gs dump. Happens also on latest git version.
> 
> I also tested it on 1.7.0-dev-1298. Seems fine there.
> 
> [gs_20220725152553_Air Rescue Ranger _PAL-E__SLES-50953_scrambled_textures_5344.zip](https://github.com/PCSX2/pcsx2/files/9181570/gs_20220725152553_Air.Rescue.Ranger._PAL-E__SLES-50953_scrambled_textures_5344.zip)

Can you try enabling the "VU Sync" gamefix please? we might need to add that to the gamedb

**Comment by stoniemahonie** [comment]
This works. I could not read out from the mentioned pr #3593 that this is the fix. Thank you very much.
