### ISSUE TITLE
Star Ocean 3 doesn't seems to like Depth Emulation

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1475]
In the latest beta(and some older revs),if you use OGL(HW) and the "Disable Depth Emulation" option is not enabled,after a single battle most(if not all)of the text is replaced by weird white boxes.
![2016-07-24_111737](https://cloud.githubusercontent.com/assets/5032540/17082724/d22f61a0-5190-11e6-8a03-b573dcd3254c.jpg)

Happens while I'm using Native too or/and disable Large Framebuffer

**Comment by FlatOutPS2** [comment]
Which older revs?

**Comment by vsub** [comment]
Now that I check my old plugins again I found a working version but the time between working and not working is not small
GSDX 20160105132032 - the problem don't exist even with DE enabled
GSDX 20160410113140 - the problem exist

And switching from the newer to the older once the problem appear,does nothing.Infact it looks like once the problem appear,nothing can fix it except restart

**Comment by gregory38** [comment]
Hum, could we try to generate a gs dump on the bad screen to see if we can reproduce the issue with a basic testcase.

**Comment by vsub** [comment]
Here(rename the extension to rar)
![snaps](https://cloud.githubusercontent.com/assets/5032540/17085859/9c038006-51eb-11e6-8f4f-81cf11efe3c0.jpg)

Also sometimes(I don't know if this is also cased by thins problem)while using the Dimension Gate skill,even at native and with Large Framebuffer disabled,the gpu usage goes way too high and the speed goes to 45 and below
CRC is set to full and BUA to none
GTX750TI/i7 4771/16GB RAM

**Comment by FlatOutPS2** [comment]
The bug is caused by https://github.com/PCSX2/pcsx2/commit/da9577076cb5c52c762c07290cbcfd4e9a388096

The issue first appears when you get to The Traum Mountains, before that the game is fine.

**Comment by gregory38** [comment]
@FlatOutPS2 did you reproduce it with the dump or the game directly ?

**Comment by FlatOutPS2** [comment]
The game. The dump isn't very useful as the bug will always show up.

**Comment by gregory38** [comment]
With latest git, it is possible to dump the read texture, so maybe we can compare them (HW vs SW) even with a bad dump. IMHO, we send garbage to the EE. Maybe it could help to test the depth PR.

**Comment by FlatOutPS2** [comment]
![so3](https://cloud.githubusercontent.com/assets/15942346/17103429/86922f54-527e-11e6-9f3e-f3e357e95d0b.jpg)

This is the result of a build with `Read(t, t->m_valid);` replaced by `Read(t, r.rintersect(t->m_valid));`

**Comment by gregory38** [comment]
Potentially there is a format issue too or maybe we need to mask the upper bits. Could worth to try the new dump capabilities on a gs dump. 
* dump = 1
* save = 1
* saven = 0 (start)
* savel = 1000 (length)

Check texture that contains `read` in the name.

**Comment by FlatOutPS2** [comment]
How are you supposed to use those capabilities?

**Comment by gregory38** [comment]
```
const std::string root_sw("c:\\temp1\\_");
const std::string root_hw("c:\\temp2\\_");
```
Just enable those option on the ini file. It will dump everythin on the above directory. You need to do it from a dump this way. You can compare draw call by draw call between the hw renderer and the sw renderer.

For completeness, you could enable the dump of CRTC frame, input texture and z buffer.
```
savef = 0
savet = 0
savez = 0
```

Globally a gs dump will likely
1/ do some rendering
2/ read the rendering from EE
3/ **** do some stuff on EE **** (invisible for the dump) 
4/ reinject the previous texture in GS input
5/ do more rendering

GSdump only monitor the input. If `2` is broken, it will register a wrong `4`. So both HW and SW renderer will be bad. However you can still compare `2` in both renderer.

**Comment by FlatOutPS2** [comment]
> Just enable those option on the ini file. It will dump everythin on the above directory. 

I did but nothing happened.

**Comment by gregory38** [comment]
Did you try both renderer ? Strange. It work fine on my side. Maybe something is wrong with the path. Oh wait, you might need to create the `c:\temp1` and `c:\temp2` directory.

**Comment by FlatOutPS2** [comment]
Manually creating the directories was the solution. Would be nice if there was a log message if the dump succeeded or not(and where to find it if it does).

![so3 menu screen sw mode issue _00019_f5000_tex0_00000_36](https://cloud.githubusercontent.com/assets/15942346/17211502/2a061798-54ca-11e6-86bc-0f12aa102e3e.png)
![so3 menu screen sw mode issue _00019_f5000_tex0_00000_36_alpha](https://cloud.githubusercontent.com/assets/15942346/17211503/2a08f1fc-54ca-11e6-8c70-fb2f079c3407.png)
![so3 menu screen sw mode no issue _00019_f5000_tex0_00000_36](https://cloud.githubusercontent.com/assets/15942346/17211505/2a0d94a0-54ca-11e6-80e4-b970ac0d43b5.png)
![so3 menu screen sw mode no issue _00019_f5000_tex0_00000_36_alpha](https://cloud.githubusercontent.com/assets/15942346/17211504/2a0bdf20-54ca-11e6-8227-2496dbdc16b2.png)

**Comment by gregory38** [comment]
Maybe someone could port the code to Windows ;)
https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSUtil.cpp#L424

With issue, you mean HW renderer ?

**Comment by FlatOutPS2** [comment]
No, once the issue is triggered, it affects all renderers. There is no difference between HW and SW. So I made a second dump that doesn't have the issue to find out which texture was corrupted.

**Comment by gregory38** [comment]
Ok. But it is the texture that is read by EE or the input texture of the bad draw call ?

**Comment by FlatOutPS2** [comment]
It's the input texture.

**Comment by gregory38** [comment]
Hum, the trick is to find where comes from the texture. Are the "*_read_*" texture the same ? They ought to be impacted by the commit that generates the regression.

**Comment by FlatOutPS2** [comment]
The read textures are the same, there is only a difference in the alpha:
With issue:
![xso3 sw issue_00017_f5000_rt0_01a40_0_alpha](https://cloud.githubusercontent.com/assets/15942346/17213601/4d5fe786-54d5-11e6-93e8-65772341d5f5.png)
Without issue:
![xso3 sw no issue_00017_f5000_rt0_01a40_0_alpha](https://cloud.githubusercontent.com/assets/15942346/17213604/4f14ebbc-54d5-11e6-9d0c-8ce595c6a844.png)

**Comment by gregory38** [comment]
Hum strange. So if we do a summary.
* The "read" path break the rendering.
* read texture are same except the bottom
* if you reduce the size of the read (with intersection), it is better but not perfect.

Did you compare the size of `r` before/after intertersection ? It feels like we have invalid (useless) data in the gpu texture. Read will move them into the gs memory but it will overwrite valid data.

**Comment by FlatOutPS2** [comment]
I did a quick test, and there is a difference between r before and after, but the x,y,z,w, left, right, top, bottom values are the same.

**Comment by gregory38** [comment]
```
This is the result of a build with Read(t, t->m_valid); replaced by Read(t, r.rintersect(t->m_valid));
```
I mean size of ` t->m_valid` vs size of ` r.rintersect(t->m_valid)`

By the way, xyzw alias to left, right, top, bottom (not sure of the order)

**Comment by ssakash** [comment]
> By the way, xyzw alias to left, right, top, bottom (not sure of the order)

IIRC, ``x , y , z , w`` -> ``left , top , right , bottom``. ( not sure though, at mobile right now)

**Comment by FlatOutPS2** [comment]
I actually meant to replace xyzw with lrtb in my post (ssakash's order is correct though). :p 

`t->m_valid`
left=0, right=576, top=0, bottom=416 
`r.rintersect(t->m_valid)`
left=314, right=330, top=0, bottom=16

I just played the game with the Renderer in the plugin settings menu set to software, then switching to hardware with F9, and the corrupting path will never be triggered...

**Comment by gregory38** [comment]
Hum, looking at the size, it will both faster and safer to to the rintersect.

**Comment by FlatOutPS2** [comment]
I just added `if (GSUtil::HasCompatibleBits(psm, t->m_TEX0.PSM))` before the read and that makes it skip the corrupting depth effect. `t->m_TEX0.PSM` is PSM_PSMZ16 and `psm` is PSM_PSMZ24.

**Comment by gregory38** [comment]
Good catch. Go PR. I suggest to update the size of the read too it will be nicer for perf :)
