### ISSUE TITLE
Final Fantasy 12 IZJS does not like Fast Texture Invalidation

### ISSUE THREAD

**Issue by jcdenton2k** [PCSX2/pcsx2#1478]
Final Fantasy 12 IZJS (English Patched v0.22 final) (NTSC-J) SLPM_667.50 with CRC 1E7A88A7
AMD Phenom II X4 840
Windows 7 x64
Nvidia GTX 560 Ti with latest July drivers (also tested with older ones and same issue)

So like the title says, just a heads up to those playing FF12 IZJS in preparation for the upcoming HD re-release in 2017.  Be sure not to use Fast Texture Invalidation under Hardware Hacks in your GsDx video plugin settings.

If this issue is confirmed by others, then someone could add this info to the PCSX2 wiki.  That would be fantastic.

**Comment by ssakash** [comment]
Fast texture invalidation is a hack. Bugs should only be reported on Github if the issue occurs without any usage of hacks. These sort of information suits the forum (or) wiki more than the issue tracker.

Either way. leaving it open in case @gregory38 is interested for some testcase.

**Comment by FlatOutPS2** [comment]
You didn't say what happens when you do select it. :/

**Comment by jcdenton2k** [comment]
This issue is erratic and I cannot reproduce it quickly/accurately so I'll need to do more testing on it.  However it has also happened even with Fast Texture Invalidation disabled so it may be something else even with my preset/default setup.  I'll need to dig around more.

@ssakash PCSX2 forum mod jesalvein is driving away people like myself and many others that would otherwise contribute but are not fond of their 'methods' so telling me to use the forum will be a moot point

This issue was posted because of another similar issue that also references a 'hack' (Disable Depth Emulation):
https://github.com/PCSX2/pcsx2/issues/1475

When FTI is used, after some time (a few mins ) of gameplay it causes the entire game to graphically turn to garbage (not sure how to describe it) until the GSDX plugin is 'reset' by changing one of the settings.

I'm going to go ahead and close out this issue until I can reliably reproduce it.  When it happened with FTI disabled it really threw me off (and I'd already tested quite a bit).

**Comment by ssakash** [comment]
> PCSX2 forum mod jesalvein is driving away people like myself and many others that would otherwise contribute but are not fond of their 'methods' so telling me to use the forum will be a moot point

You should be fine if you follow [all the rules](http://forums.pcsx2.net/Announcement-Global-Forum-Rules) on the Forum.

> This issue was posted because of another similar issue that also references a 'hack' (Disable Depth Emulation):

That issue happens when the hack is ``disabled``.

As I said before,
> Fast texture invalidation is a hack. Bugs should only be reported on Github **if the issue occurs without any usage of hacks**.

**Comment by jcdenton2k** [comment]
After some more extensive testing, the issue is not related to Fast Texture Invalidation but a combination of something else on my computer not related to PCSX2.  This bug can be deleted if need be.
