### ISSUE TITLE
Persona 3 Fes NTSC - Character portraits animation offset

### ISSUE THREAD

**Issue by P3Fan** [PCSX2/pcsx2#1501]
-PCSX2 version:  v1.5.0-dev-1085
-PCSX2 options: Defaults
-Plugins used: Defaults (Gsdx)
-Plugin settings: Tested multiple GSdx DX9/11 hardware settings,hacks and rendering resolutions. The issue is fixed with a software renderer.

-Description: Setting the vertical resolution to anything other than native causes part of the character's face to be slightly offset during blinking animation. 
Here's how it looks using software renderer and hardware renderer with vertical res at native (448):
![Junpei](https://abload.de/img/soft16tsvx.gif)
![Red_creepy_girl 3/10](https://abload.de/img/soft3f3su6.gif)
![Hmm. not bad at all. 8/10](https://abload.de/img/soft4omusz.gif)

Here's the animation at anything other than native vertical res (including multiples of 448):
![Junpei](https://abload.de/img/hard1npscg.gif)
![Red_creepy_girl 3/10](https://abload.de/img/hard3lwj7t.gif)
![Hmm.. not bad at all. 8/10](https://abload.de/img/hard4ovbbu.gif)

-How to replicate: The issue affects every character portrait in the game
-Last known version to work: Unknown
-PC specifications: CPU: Intel Core i5 760  GPU:  GTX750Ti 2GB OS: Windows 10 (64-bit)

**Comment by MrCK1** [comment]
That's just an artifact of upscaling a sprite/FMV

**Comment by P3Fan** [comment]
Bummer, I was hoping it's something that could maybe be fixed/realigned. I'm not sure but i think the way that animation works is that another, smaller texture of closed eyes is overlaid on the regular big character sprite and upscaling messes up the Y coordinate of the smaller texture. If that's just a common problem with how sprites work then that's too bad. I guess I will have to deal with it.
Also I know it's a ridiculously small issue :P  but talking to people is ~66% of a Persona game and knowing that all their faces are a bit off bothers me.  It's one of those 'once you see it you can't unsee it' things. Especially when the rest of the emulation is pretty much perfect.

**Comment by jcdenton2k** [comment]
You can try one of the various 'hack' options for fixing sprites in either OpenGL or DirectX9 or DirectX11 and see which one works for you.  I know there are several of them.

Some OpenGL options:
Half Pixel Offset
Align Sprite
Wild Arms Offset (Devs should consider renaming this to 'Pixel Gap Offset' or something)
Round Sprite (Off, Half, Full)
Sprite (Off, Half, Full)

And try the equivalent HW Hack options if available on the DX side and see what works.
If you do find a solution do feel free to share it with us :)

Also on the PCSX2 Wiki there are a few problems/solutions that may apply to you, give em a go!
http://wiki.pcsx2.net/index.php?title=Shin_Megami_Tensei:_Persona_3_FES

**Comment by Sarania** [comment]
Just FYI you used to could fix this by setting texture filtering to "Nearest"

**Comment by FlatOutPS2** [comment]
In the PAL version it occurs on native/SW renderer as well. :/

**Comment by gregory38** [comment]
I think this one is texture offset. Check the tooltip

**Comment by FlatOutPS2** [comment]
> I think this one is texture offset. Check the tooltip

That's for the Persona 3 minimap. It might improve the issue on NTSC, PAL version might be bug in the port and perhaps show on PS2 as well.

**Comment by P3Fan** [comment]
Thanks for the feedback everyone. Unfortunately I had already tried pretty much every setting/hack possible before posting the issue. I've even manually checked all the vertical resolutions between 2x and 3x native, hoping that maybe at some magic value the scaling will fall into place. No luck.
I've just doublechecked the 'nearest' texture filtering option in combination with other hacks as well as the Y texture offset minimap fix, but nothing seems to help.

**Comment by FlatOutPS2** [comment]
Can you make a GS Dump of the issue? 
http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by P3Fan** [comment]
Here it is. I tried to time it the best I can but the emulation stops as I hold the buttons so I'm not sure if I captured the exact moment. I can try again if necessary.
[Persona 3 FES NTSC portrait offset.zip](https://github.com/PCSX2/pcsx2/files/429045/Persona.3.FES.NTSC.portrait.offset.zip)

**Comment by FlatOutPS2** [comment]
I can't tell for sure if you caught it. I think it would be better with a multiple frame dump. You'll have to press CTRL + SHIFT + F8. "If you use the multi frame option, the important thing to note is that how long you hold down the key combination determines how long the GS dump is. If you press for 4 seconds, you get a 4 second dump. What you want to do is hold the keys long enough to capture the entirety of the graphics bug. "

**Comment by P3Fan** [comment]
OK, looks like I wasn't holding the buttons long enough. 
https://www.dropbox.com/s/9l71kokv28mdzes/Persona%203%20FES%20NTSC%20portrait%20offset.zip?dl=0

**Comment by Kosyne** [comment]
I've got the same in 1.4.0. Tried out several hacks, filtering options, software and hardware renderers, but the problem consistently shows up when using anything but native res. Some settings make it ever so slightly less noticeable, but nothing I've tried gets rid of the flickering/sprite offset issues entirely.

There are quite a few forum posts about it too, and all seem to end with the OP just deciding to go with native res...

**Comment by Joqu** [comment]
Same issue here on 1.4.0. and the only thing that fixes it for me is playing in native res.

As far as I can tell it's a known issue, but any solutions I've come across aren't working for me, and I assume no longer do for anyone. I haven't found any new solution at least.

**Comment by P3Fan** [comment]
Not sure if this helps in any way in pinpointing the problem, or maybe this was already obvious, but this is how the game handles blinking animation. https://www.spriters-resource.com/resources/sheets/23/24744.png It looks like each portrait has a smaller "closed eyes" overlay texture. It appears that changing the vertical res causes that smaller texture to pop up in a wrong position/misaligned (a few pixels too high it seems).

**Comment by Enverex** [comment]
Just pinging this bug to add that the issue still occurs as of 22nd December GIT build.

**Comment by AlekLT** [comment]
I also couldn't solve this issue using the latest git build.

**Comment by Arthandas** [comment]
Still bugged on 1.6.0 no matter what texture filtering option is chosen. Maybe if we could set negative value for Y texture offset...

**Comment by lightningterror** [comment]
Closing since it's an upscaling issue.
