### ISSUE TITLE
Alex Ferguson's Player Manager 2001 [SLES 50429] (E) hang/crash in menus

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#1502]
-PCSX2 version: All versions after https://github.com/PCSX2/pcsx2/commit/372478c0ecfdd44508b04c9e6c803089405b7b8a

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: Default

-Plugin settings: Tried all.

-Description:  Game will hang in menus when you try to reach "done" button after selecting a name.

-Last known version to work: worked before r4741 on old google code. 

From my initial testing it seems the regression was introduced in this commit: https://github.com/PCSX2/pcsx2/commit/372478c0ecfdd44508b04c9e6c803089405b7b8a

So I am labeling this as a Vif issue.

**Comment by refractionpcsx2** [comment]
It was a VIF issue, all fixed now :) 

Tested MGS3, Project Zero 3, KH2 and Digital Devil Saga as well, all are still working fine.

**Comment by avih** [comment]
@refractionpcsx2 off topic, but you have a pending question to reply to for some days now :) let's wrap it up https://github.com/PCSX2/pcsx2/pull/947#issuecomment-236845859
