### ISSUE TITLE
Sengoku Basara 2 Heroes - Massive slowdown while loading 

### ISSUE THREAD

**Issue by adimetro00** [PCSX2/pcsx2#1503]
-PCSX2 version: v1.4.0
-PCSX2 options: Defaults
-Plugins used: Defaults (Gsdx)

So, while other parts of the game run fine, there's sudden, massive slowdown while in the loading screen.
This part is where the slowdown is.
![gsdx_20160807081945](https://cloud.githubusercontent.com/assets/10296602/17459893/f40d4cfa-5c77-11e6-9b18-607b99abf526.png)

**Comment by FlatOutPS2** [comment]
Have you tried it with the latest git release?

And does the slowdown occur in all renderers, or just the hardware renderers(if so, does it occur at native resolution) or even just in a specific renderer(OpenGL/Direct3D)?

**Comment by adimetro00** [comment]
Changing to native doesn't solve the problem.

**Comment by MrCK1** [comment]
I would still try the latest git release like FlatOut said. You can find that [here](http://pcsx2.net/download/development/git.html)

**Comment by MrCK1** [comment]
@adimetro00 Any status update on latest git?

**Comment by lightningterror** [comment]
A couple months ago I tested this and didn't spot any slowdowns.
