### ISSUE TITLE
AMD OpenGL Weirdness

### ISSUE THREAD

**Issue by UlsterRose** [PCSX2/pcsx2#1506]
With any of the VS 2015 builds, I experience multiple issues, one of which is this really strange "drunk vision" effect, which sort of looks like a really bad motion blur effect. This doesn't happen with the VS 2013 builds
![gsdx_20160808213907](https://cloud.githubusercontent.com/assets/8225831/17495428/f04a06f0-5db0-11e6-824a-e26b3d2a8e96.png)

![gsdx_20160808214014](https://cloud.githubusercontent.com/assets/8225831/17495446/fc91b7be-5db0-11e6-896c-44321ac24ab8.png)
I wasn't using shade boost here. This is with stock settings.

![gsdx_20160808214046](https://cloud.githubusercontent.com/assets/8225831/17495572/7a55b402-5db1-11e6-8990-32ae5a0f80ff.png)
Notice how a lot of the normally opaque textures, such as the EA Trax display, have become translucent. The drunk vision effect is also very noticeable in the sign in the top-left.

In addition to this, software mode usually just doesn't display anything at all. All these issues happen with both the AppVeyor VS 2015 builds and my own VS 2015 build, and none of them happen in either DX9 or DX11.

**Comment by gregory38** [comment]
Could you find the first build that have this behavior. It feels like a variable badly initialized due to the recent deferred init.

**Comment by FlatOutPS2** [comment]
So, which AMD GPU are you using and is your driver version completely up to date?

**Comment by DPersonalized** [comment]
@FlatOutPS2 I'm using a Radeon HD 7770. I can't download the latest drivers at the moment because my internet connection is being throttled to death. I should be able to test it again later today.

**Comment by DPersonalized** [comment]
It now seems like the AppVeyor builds are no longer affected, but my own VS 2015 builds, even with the very latest master, seem to still be affected.

**Comment by bositman** [comment]
Try doing a clean and then a rebuild on the GSdx solution

**Comment by DPersonalized** [comment]
@bositman Alright, so now the AppVeyor builds seem to be affected by the issue again! It doesn't seem to happen on the first run of an AppVeyor build, but it does on every run thereafter.

**Comment by DPersonalized** [comment]
EDIT 2: This also seems to be happening with the VS 2013 AppVeyor builds. Again, no idea why.

**Comment by ssakash** [comment]
Could you try and find the build which introduced the issue ? [**git bisect**](https://git-scm.com/docs/git-bisect) _might_ help.

**Comment by DPersonalized** [comment]
1.4.0 stable still has the issue. 1.2.1 stable makes the display driver crash and my screen fill with garbage as soon as the game gets to the first loading screen.

**Comment by mirh** [comment]
Could it be a problem with shader cache?

**Comment by gregory38** [comment]
It is easy, the bug is either from AMD's driver or from the bad AMD's driver ;)

So wipe-out your driver and reinstall it

**Comment by DPersonalized** [comment]
@gregory38 I uninstalled and reinstalled my drivers, but nothing's changed :(

**Comment by mirh** [comment]
With [DDU](https://github.com/Wagnard/display-drivers-uninstaller)?

**Comment by gregory38** [comment]
Did you try an older version of the driver? Be sure you have no running application in background

**Comment by DPersonalized** [comment]
@gregory38 I reverted to Catalyst 15.3, but still no change.

**Comment by mirh** [comment]
Try new 16.8.2

**Comment by DPersonalized** [comment]
@mirh It's still broken on 16.8.2.

**Comment by mirh** [comment]
> 1.2.1 stable makes the display driver crash

Uhhh, then I guess congratulation for having won the "Find pcsx2 [TDR](https://github.com/hrydgard/ppsspp/issues/8698) award". 
Seriously, I don't really think it's related to your issue (which btw, I couldn't reproduce on my Burnout **3** copy) but you may want to bissect where driver crashes stops to manifest, then help ppsspp guys in helping AMD helping users.

**Comment by mirh** [comment]
@DPersonalized Can you take a gsdump?

**Comment by gregory38** [comment]
Based on AMD record, I will mark this bug as external. Otherwise it is potentially a gsdx.ini issue.

**Comment by mirh** [comment]
Speaking of which.. I have a very strange OGL-only issue in #1842. That triggers god only knows when, and *seems* to be carried by save-states then. 
I could send you gs dumps when you have time.

**Comment by mirh** [comment]
Any update on this? Does #2125 change anything in this regard?

**Comment by UlsterRose** [comment]
This was an issue with AMD drivers, I believe, and it was certainly fixed at some point. Not sure when though.

**Comment by mirh** [comment]
So.. Runs >1 works good in your system then?
I'm not quite sure why only you was getting the problem, but if you can't reproduce it anymore, you can close.
