### ISSUE TITLE
An unspecified error occurred while trying to create the Redirect_Stderr thread.

### ISSUE THREAD

**Issue by nE0sIghT** [PCSX2/pcsx2#1510]
Hi,

This issue was originally reported at [Gentoo bugzilla](https://bugs.gentoo.org/show_bug.cgi?id=590840) for PCSX2 1.4.0 and git master branch

PCSX2 crashes on start with following message in console:
```
Interface is initializing.  Entering Pcsx2App::OnInit!
Applying operating system default language...
Command line parsing...
Command line parsed!
Thread creation failure.  An unspecified error occurred while trying to create the Redirect_Stderr thread.
Trace/breakpoint trap (core dumped)
```

PCSX2 Log window: https://590840.bugs.gentoo.org/attachment.cgi?id=442818
Critical error window: https://590840.bugs.gentoo.org/attachment.cgi?id=442820
System information: https://590840.bugs.gentoo.org/attachment.cgi?id=442892

How to debug this issue properly?

**Comment by gregory38** [comment]
Hum, there is a huge probability that `pthread_create` return an error.

Looking at the man page
```

ERRORS
       EAGAIN Insufficient resources to create another thread.

       EAGAIN A system-imposed limit on the number of threads was encountered.  There are a number of limits that may trigger this error: the RLIMIT_NPROC soft resource limit (set via setrlimit(2)), which limits the
              number  of  processes and threads for a real user ID, was reached; the kernel's system-wide limit on the number of processes and threads, /proc/sys/kernel/threads-max, was reached (see proc(5)); or the
              maximum number of PIDs, /proc/sys/kernel/pid_max, was reached (see proc(5)).

       EINVAL Invalid settings in attr.

       EPERM  No permission to set the scheduling policy and parameters specified in attr.

```
Attr is null so it remains error about the number of thread. Is it limited to a single guy ? The core dump is likely due to the missing thread. 

So it feels like a security policy is set somewhere to avoid fork bomb, however the limit is too low for PCSX2 which use lots of thread.

**Comment by gregory38** [comment]
@nE0sIghT 
Could you ask/test the following branch https://github.com/PCSX2/pcsx2/tree/pcsx2-verbose-thread-error

I updated the error message to print the error code of pthread.

**Comment by nE0sIghT** [comment]
Here is PCSX2 output:
```
Interface is initializing. Entering Pcsx2App::OnInit!
 Applying operating system default language...
 Command line parsing... 
Command line parsed! 
Thread creation error: Cannot allocate memory 
Trace/breakpoint trap (core dumped)
```
It's indeed some limit in place, however ulimit values, max threads and max pids looks good for me. I will try to investigate this deeper. Thanks for help!

**Comment by gregory38** [comment]
Maybe check the allowed stack size. Did the guy enable the sw renderer on gsdx? Check the number of extra thread.

**Comment by nE0sIghT** [comment]
I reproduces this crash with maximum stack size (ulimit -s) set to 1048576 (1G - this value was set by user having this problem).

I do not know if PCSX2 should work with such max stack size value. If not, I will close this issue.

**Comment by gregory38** [comment]
Seriously ! Each thread will require a stack. So in your opinion how many thread can be created with a stack of 1GB, remember PCSX2 is 32 bits only.

However it is a nice finding if one want to quikcly crash an applications.

**Comment by nE0sIghT** [comment]
Agreed, this is system misconfiguration.

Thanks!
