### ISSUE TITLE
gsdx postprocessing versus bilinear filtering

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1511]
Post Processing shader in GSdx uses a texture which is a copy of the current framebuffer. It means the size of texture and framebuffer is the same. So linear filtering impact is rather limited, if we sample at the same position as the pixels.

I'm sure linear filtering is useless for the ShadeBoost shader. But maybe it is used for External/FXAA shader. It would be nice to have a confirmation. If linear filtering is useless it can greatly reduce the load on the GPU memory bandwidth.

**Comment by gregory38** [comment]
@Asmodean- could you give me a feedback, thanks ?

**Comment by Asmodean-** [comment]
Sorry - bit of a late reply. Have crazy hours at work currently. So I've not been on here.

Yes, many of the effects within the gsdx post-processing use the gx linear filter as a base for the logic. While it's not "needed" for them to work. The effects who's logic are based on the assumption of having linear interpolation will not work as intended. Including FXAA. It won't provide the same level of AA if using (for example) point instead.

You could maybe make a define macro for the linear bool and have it set to a get config ini setting.

**Comment by gregory38** [comment]
Thansk for the info. I'm fine. Linear is useless for the shadeboost shader that why I'm asking. However, the final upscaling/downscaling to present the image on the monitor uses linear filtering. I'm afraid that it blurs the final picture. I need to add an option to test this one.

**Comment by gregory38** [comment]
Ok. I added an option in master to disable the linear filtering on "present". Let's keep linear for external shader.
