### ISSUE TITLE
Sega Superstars Tennis geometry issues

### ISSUE THREAD

**Issue by Nobbs66** [PCSX2/pcsx2#1519]
Core issue:

Issue title: Sega Superstars Tennis character geometry bug. 

-PCSX2 version: 1.5.0 GC782B62

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx 1.0.0, SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: Character geometry handled correctly in either the character selection screen or in an actual match 

-How to replicate: Pick a game mode and get to the character selection screen. 

-Last known version to work: Never worked

-PC specifications: CPU: Intel Core i7 5820K: Sapphire R9 Fury Tri X OS: Windows 10 Pro 64-bit

Other comments: Maybe a VU issue? SuperVU, MicroVU, and the VU interpreter all offered the same results, so who knows. 

-Image of issue: http://imgur.com/a/CJ7aT

**Comment by willkuer** [comment]
zerogs maybe?

**Comment by CalmCodeC** [comment]
What about software mode. did you test it ?

**Comment by refractionpcsx2** [comment]
this is either a VU or a COP issue, not sure which.

**Comment by ramapcsx2** [comment]
Haven't we fixed this once? I think it was VIF1 timing, iirc.

**Comment by refractionpcsx2** [comment]
> Haven't we fixed this once? I think it was VIF1 timing, iirc.

No, the game used to have path3 masking issues, causing flashing textures, but I fixed that ages ago. The game has always had SPS.

**Comment by ramapcsx2** [comment]
Okay, first thing to check is that VIF1 interrupt delay that currently breaks the intro to Shadowman 2 with SPS.

**Comment by refractionpcsx2** [comment]
I think I'd already tried that, I did look at this issue for a while and came out with no results.

Couldn't hurt to try it again in case I'm wrong.

**Comment by gregory38** [comment]
does anyone test the latest VU fix ?

**Comment by refractionpcsx2** [comment]
> does anyone test the latest VU fix ?

Just tried it, doesn't help

**Comment by gregory38** [comment]
Ok thanks you for the quick test.

**Comment by marcussacana** [comment]
... This bug is too old, how isn't fixed yet?

**Comment by refractionpcsx2** [comment]
I know exactly why it is broken, the game requires tight synchronisation between the EE and VU0, the developers have timed some of the writes to it precisely. I doubt it will ever get perfect, but to fix it requires a whole redesign of how the EE times itself and how the vu's synchronise, which is probably going to cause an impact in speed.

**Comment by marcussacana** [comment]
Hmm, I don't know how the ps2 work internally, but this mean is impossible even a game specific hack?

**Comment by atomic83GitHub** [comment]
Likely not, this game is possibly one of the most picky game which require a near cycle accurate VU0 and EE timing.

**Comment by marcussacana** [comment]
I understand, thanks for the information.
By the way, if like me, someone played this game a lot in childhood and wanted feel the nostalgia, the game also has for PS3, X360, DS and WII, you can try your luck with other emulators.

**Comment by refractionpcsx2** [comment]
This has been resolved on master.

**Comment by marcussacana** [comment]
wtf, really?

**Comment by refractionpcsx2** [comment]
yes, it's been fixed on master for a couple of months now.

**Comment by OMEGAZILLA** [comment]
Wait so no SPS anymore?

**Comment by refractionpcsx2** [comment]
nope

**Comment by OMEGAZILLA** [comment]
Hm, so I'm somewhat new to GitHub so how do I use the master files?

**Comment by Mvx69** [comment]
So, now it´s fixed?
