### ISSUE TITLE
Taking screenshot takes really long time at higher scaling

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1527]
The higher the scaling,the more I have to wait.
For example at 4x it needs ~8 seconds and at 8x it needs ~35 seconds
During that time,pcsx2 freezes,the GS is at 100% and all else is at 0(on weaker pc it will probably take even longer)

With the old format(bmp),it's less than 2 seconds at 6x

i7 4771 3.5ghz,GTX750TI,16GB ram

**Comment by FlatOutPS2** [comment]
Yeah, the PNG snapshots take waaaay too long at higher than native resolutions.

**Comment by turtleli** [comment]
I guess I should make it possible to change the compression level for screenshots too. I'll probably just reuse png_compression_level.

**Comment by gregory38** [comment]
Yes. Got ninja'd

**Comment by turtleli** [comment]
> Edit: or use a smaller level, like 6. It could be a good trade off

I'll probably make it configurable. 6 can still take a while, though it's nowhere near as long as 9. It's just a case of whether I reuse png_compression_level or not, since the use case is different (single image vs multiple images).
