### ISSUE TITLE
Videos freeze in Harry Potter and the Order of the Phoenix

### ISSUE THREAD

**Issue by antoyo** [PCSX2/pcsx2#1534]
Core issue:

Issue title: Videos freeze (Harry Potter and the Order of the Phoenix)

-PCSX2 version: 1.5.0 GIT c1f45dafa5ea62b8251f9f69e8d9972afc893605

-PCSX2 options: Defaults, no setting modifications affect the issue

-Plugins used: GSdx, OnePAD, SPU2-X, Linux Iso CDVD, the rest are null plugins

-Plugin settings: Defaults, no setting modifications affect the issue

-Description: The Harry Potter game have videos both in the game and before the title screen. The videos can sometimes freeze the emulator. The game is unplayable.

-How to replicate: Start the game and you will experience a freeze after killing the dementors (which is the first thing to do in the game) in the worst case.

-Last known version to work: Never worked

-PC specifications:
- CPU: Intel(R) Core(TM)2 CPU 6600  @ 2.40GHz
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] RV620 LE [Radeon HD 3450]
- OS: GNU/Linux 4.7.1 (ArchLinux) 64-bit

-Other comments: The pull request #1507 did not fix the video issues in the game Harry Potter and the Order of the Phoenix.

I still get many errors like:

```
---------
DMA Crash
---------

General DMA state:

    DMA enabled
    DMA transfer enabled
    Cycle-stealing off
    FIFO off
    Stall control source unspecified
    Stall control drain unspecified
    Release cycle 8
    DMA Stall interrupt disabled (interrupt state clear)
    MFIFO empty interrupt disabled (interrupt state clear)
    BUSERR interrupt clear
    Stall address 0x00000000

Channel 0 - VIF0 

    Channel stopped
    Channel interrupts disabled (interrupt state set)
    Chain mode
    Transfer address 0x005862e0
    Tag address 0x005862d0
    Transfer size 0 QWs
    TTE enabled
    TIE disabled
    Last tag was 0x7000
    No addresses on stack

Channel 1 - VIF1 

    Channel stopped
    Direction to memory
    Channel interrupts enabled (interrupt state clear)
    Chain mode
    Transfer address 0x00c40bb0
    Tag address 0x00c40b90
    Transfer size 0 QWs
    TTE enabled
    TIE enabled
    Last tag was 0x7000
    No addresses on stack

Channel 2 - GIF 

    Channel stopped
    Channel interrupts disabled (interrupt state set)
    Chain mode
    Transfer address 0x00c40b70
    Tag address 0x00c40b50
    Transfer size 0 QWs
    TTE disabled
    TIE disabled
    Last tag was 0x7000
    No addresses on stack

Channel 3 - fromIPU 

    Channel stopped
    Channel interrupts disabled (interrupt state set)
    Normal mode
    Transfer address 0x00003600 (scratchpad)
    Tag address 0x00000000
    Transfer size 0 QWs
    TTE disabled
    TIE disabled
    Last tag was 0x0000

Channel 4 - toIPU 

    Channel stopped
    Channel interrupts enabled (interrupt state clear)
    Chain mode
    Transfer address 0x015ca4f0
    Tag address 0x01629e90
    Transfer size 0 QWs
    TTE disabled
    TIE disabled
    Last tag was 0x0000

Channel 5 - fromSIF0 [running]

    Channel running
    Channel interrupts enabled (interrupt state clear)
    Chain mode
    Transfer address 0x00784360
    Tag address 0x00000000
    Transfer size 0 QWs
    TTE disabled
    TIE enabled
    Last tag was 0x0000

Channel 6 - toSIF1 

    Channel stopped
    Channel interrupts disabled (interrupt state set)
    Chain mode
    Transfer address 0x00796470
    Tag address 0x00021310
    Transfer size 0 QWs
    TTE disabled
    TIE enabled
    Last tag was 0x0000

Channel 7 - SIF2 

    Channel stopped
    Direction from memory
    Channel interrupts enabled (interrupt state clear)
    Normal mode
    Transfer address 0x00000000
    Tag address 0x00000000
    Transfer size 0 QWs
    TTE disabled
    TIE disabled
    Last tag was 0x0000

Channel 8 - fromSPR 

    Channel stopped
    Channel interrupts disabled (interrupt state set)
    Normal mode
    Transfer address 0x015a7080
    Tag address 0x00000000
    Scratchpad address 0x00003000
    Transfer size 0 QWs
    TTE disabled
    TIE disabled
    Last tag was 0x0000

IPU state :

    IPU is idle
    0 QWs in input FIFO
    0 QWs in output FIFO
    0 QWs in internal buffers
    Error code not detected
    Start code detected
    Bitstream is MPEG 2
    Frame type is I-frame
```

Does anyone else still have this issue with this game?

Thanks to fix this issue.

**Comment by willkuer** [comment]
The whole series is broken. Related to #362 and #1360.

So far no solution.

**Comment by FlatOutPS2** [comment]
My PR wasn't meant to fix all video related issues, it only resolved two specific IPU issues.

I don't have any of the Harry Potter games, so I don't even know what the issue is. Can you follow the issue template ( https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues ) and describe what the actual issue is.

**Comment by antoyo** [comment]
@FlatOutPS2 I updated the issue to follow the template.

**Comment by prafullpcsx2** [comment]
I don't have order of phoenix but this is one of those harry potter games which is supposed to work. So OP seems to be posting some different issue than #362 and #1360.

**Comment by atomic83GitHub** [comment]
I think this issue is invalid as this happen when a EA game disc is damage.

**Comment by tristanlifn** [comment]
i also have this issue, just putting this here
