### ISSUE TITLE
[Label] Savestate bump

### ISSUE THREAD

**Issue by winapp2** [PCSX2/pcsx2#1537]
Status:Trivial

Could you add the label "Savestate Bump", because some Pull Requests seem to need it. This is very important for PR's which will change the Savestate.

**Comment by winapp2** [comment]
https://github.com/PCSX2/pcsx2/pull/1331

https://github.com/PCSX2/pcsx2/pull/1383

These both could require the Savestate Bump label.

**Comment by gregory38** [comment]
Ssakash will decide and manage ;)

**Comment by ssakash** [comment]
Added a ``savestate version bump`` label for #1331. #1383 doesn't need it.

**Comment by winapp2** [comment]
Refraction says in https://github.com/PCSX2/pcsx2/pull/1383:

"I haven't done no, to be honest I didn't look at that. I kinda hoped I could switch to the recompiler with the cache on but it doesn't look like it :(

I could add a function to flush the cache on switching to the recompiler. **As for savestates, I didn't really want to break them again :p I guess it happens though**"

**Comment by refractionpcsx2** [comment]
No I said if i added some extra functionality I would need to bump it, but I haven't added it.

**Comment by winapp2** [comment]
Sorry, but does your Pr won't add this extra functionality or is it just a fallback?

**Comment by refractionpcsx2** [comment]
Firstly it isn't my PR, secondly, no it won't add it, that was something that can be addressed in the future possibly.
