### ISSUE TITLE
guitar hero 3 bug

### ISSUE THREAD

**Issue by NetoDevel** [PCSX2/pcsx2#1543]
Guitar Hero 3 is not working in version 1.4.0

**Comment by MrCK1** [comment]
If you're going to make a bug report, please follow the proper guidelines so we can determine your problem.

GH3 works fine in 1.4.0, but you may need to tweak some settings first

**Comment by NetoDevel** [comment]
'm using the default setting of the emulator , my video card is nvidia geforce optimus

**Comment by willkuer** [comment]
Please visit the forum at (forums.pcsx2.net) to get support or follow the guidlines for submitting a bug report.

This is a bug tracker not a support hotline.

**Comment by FlatOutPS2** [comment]
Go to Config -> Emulation Settings -> VU tab, and set Round Mode to "Nearest" (you might need to turn off the preset in the lower left part of the window).
Then go to Config -> Video (GS) -> Plugin Setttings, and set Renderer to any of the software modes.

If you still experience crashes after using these settings, update your first post with a proper bug report following the guidelines linked in the above post.

**Comment by refractionpcsx2** [comment]
The game works fine, if you are still having an issue after FlatOutPS2's suggestions, please post here again and I'll reopen this issue if it is valid.
