### ISSUE TITLE
[1.4.0] Build Issue on Gentoo

### ISSUE THREAD

**Issue by mmstick** [PCSX2/pcsx2#1544]
I'm having the compilation process just quit without any useful error messages, so I'm not sure what's causing the compilation issue.
I'm using GCC 5.4.0 with the following CPU flags:

```
CFLAGS="-march=native -O2 -ftree-vectorize -pipe"
CXXFLAGS="${CFLAGS}"
```

[log.txt](https://github.com/PCSX2/pcsx2/files/448934/log.txt)

**Comment by gregory38** [comment]
And is it working without the flag ? There are already set by default except  `-ftree-vectorize`
Hint: `grep -i error log` ;)
```
/var/tmp/portage/games-emulation/pcsx2-1.4.0/work/pcsx2-1.4.0/common/src/x86emitter/cpudetect.cpp:48:23: error: â_fxsaveâ was not declared in this scope
```
Hum, it seems you remove the support of some SSE instructions (search in gcc doc, fxsave)

**Comment by mmstick** [comment]
The fxsave instruction is enabled:

```
gcc version 5.4.0 (Gentoo 5.4.0 p1.0, pie-0.6.5) 
COLLECT_GCC_OPTIONS='-v' '-E' '-march=native' '-O2' '-ftree-vectorize'
 /usr/libexec/gcc/x86_64-pc-linux-gnu/5.4.0/cc1 -E -quiet -v - -march=sandybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -mno-aes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=sandybridge -ftree-vectorize -O2 -fstack-protector-strong
```

I'm not seeing anything in the [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/games-emulation/pcsx2/pcsx2-1.4.0.ebuild) that would disable it.

**Comment by gregory38** [comment]
Oh just notice that you want to compile 1.4
Try the git instead. I need to cherry pick a patch for 1.4 (or maybe I already did it)

**Comment by gregory38** [comment]
See #1297

**Comment by gregory38** [comment]
I pushed a fix on the 1.4 branch. Hopefully it would be better.

Note, git is rather unstable but it got plenty of fix. You might want to play with it.

**Comment by mmstick** [comment]
Compiling from git worked perfectly, and even with Graphite + Ofast optimizations, which boosted the speed of emulation by 50% over O2 for me.

```sh
GRAPHITE="-floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block"
CFLAGS="-march=native -Ofast ${GRAPHITE}"
CXXFLAGS="${CFLAGS}"
```

Only problem is, I've noticed that I'm not able to make any changes to emulation settings, except for MTVU, and the configuration windows aren't using scrolled windows so the windows are vertically too long for my 768p display to show.

**Comment by gregory38** [comment]
Wait, speed of the core or plugins ? HW or SW renderer ? Are you sure that it isn't AVX vs SSE2 ? Which options give you the best boost.

Please read the various user guide. You need to disable presets. There is a PR/work-on-going to improve the size of the window (seriously, it is a resolution of another century, laptop makers kill me)

**Comment by avih** [comment]
> seriously, it is a resolution of another century

It's definitely not. 1366x768 is the most common resolution out there, more than twice more common than the next popular resolution (1920x1080) http://www.rapidtables.com/web/dev/screen-resolution-statistics.htm

> Screen resolution display size statistics. Most common screen resolutions:
> Screen resolution 	Display
> ratio 	Usage 	Screen size / type
> 1366x768 	16:9 	19.1% 	14'' Notebook / 15.6'' Laptop / 18.5'' monitor
> 1920x1080 	16:9 	9.4% 	21.5'' monitor / 23'' monitor / 1080p TV
> ...

**Comment by gregory38** [comment]
Yes I know (btw your stats are 2 years old). Still laptop maker sell crappy&old display technology. Normally laptop display is closer of your eye so density of pixels ought to be bigger. I don't say that people must buy 4K display but full HD ought to be the standard.

**Comment by avih** [comment]
This is stats from this month from here http://www.hobo-web.co.uk/best-screen-size/ :
![b-ww-may-jul-2016](https://cloud.githubusercontent.com/assets/2164962/18230543/7648ecfc-72a7-11e6-9eb5-55e098ce664b.jpg)

**Comment by avih** [comment]
We can't aim for what we wish people would have, or what we can afford to have. We should aim at what people actually have.

**Comment by gregory38** [comment]
I think you miss the important point of my previous message.
```
There is a PR/work-on-going to improve the size of the window
```

**Comment by avih** [comment]
I didn't. I referred to your statement that it's a last-century resolution. It's not.

**Comment by mmstick** [comment]
@gregory38 It's not AVX versus SSE2; I can tell that AVX is enabled on both builds because Gsdx is named `Gsdx (GCC 5.4.0 AVX) 1.1.0`. I have a file at `/etc/portage/env/graphite-ofast` which contains:

```sh
GRAPHITE="-floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block"
CFLAGS="-march=native -Ofast ${GRAPHITE}"
CXXFLAGS="${CFLAGS}"
```

After setting `games-emulation/pcsx2 graphite-ofast` in `/etc/portage/package.env` and re-emerging pcsx2, the speed of emulation achieves a 50% boost in performance that I wasn't getting before using my default CFLAGS, which is `-march=native -O2 -ftree-vectorize`. I was getting 40% speed in Shadow of the Colossus before, whereas I can achieve 60% speed with Ofast+Graphite.

Optimization levels higher than O2 are known to achieve much bigger improvements with software that's heavy on math (ie: Mesa + Xorg + Video Codecs + Games), so I'd imagine that an emulator would be one of the type of applications that benefits the most. I do know that the x264 project uses `Ofast` in their builds because of that.

@avih The 768p resolution of laptops is last century. There's just this problem where laptop manufacturers refuse to pay a couple more cents per laptop, literally, to include a 1080p display, because they can charge higher prices for elusive 1080p models by artificially creating demand. I notice that they really do this with AMD models where the goal is to cripple AMD laptops as much as possible by doing the following:

- Selling laptops with cheap, low mAh capacity batteries that are even lower capacity than the battery in your average budget Android smartphone.
- Selling laptops exclusively with 768p displays, and not giving the option to purchase a 1080p model.
- Enforcing that all AMD laptops use a single DDR3/4 DIMM by only providing a single DIMM slot, even if the processor supports and requires dual/quad channel for the integrated graphics.
- Enforcing that all AMD models are locked at 15w TDP, even if you purchased a model exclusively because it has a 25/35w TDP for the purpose of gaming, thus defeating the purpose in actually purchasing a higher end processor because it will always run at 15W cTDP modes that cheaper models are advertised at.
- Underclocking memory to run at lower than recommended and advertised specs. A recent HP Envy x360 owner was forced to ship his laptop to HP and wait three weeks for them to flash the BIOS to get the single DDR3 1866Mhz DIMM to actually run at 1866MHz; and even though the processor supports DDR4 and the HP Envy X360 is being promoted as the flagship AMD laptop, HP refuses to sell it with DDR4 memory. They won't publicly release a BIOS that you can flash yourself.
- Or just terrible design flaws, such as how the HP Envy X360 was designed to place the left speaker in the middle of the laptop, which greatly dampens the sound of the left speaker and ruins the purpose in having a left speaker, since your audio is shifted to the right.
- And despite all this, selling these models at high prices.

**Comment by mmstick** [comment]
Found a quick fix for my resolution problem for GNOME users: Alt + F7 lets you drag windows offscreen so you can see the rest of the configuration windows.

**Comment by mmstick** [comment]
I'm not seeing an option for configuring presets. Where is that at?

**Comment by mmstick** [comment]
Nevermind, I found it hidden at the bottom of the Emulation Settings window, which required to be resized to show it.

**Comment by gregory38** [comment]
SW or HW renderer on GSdx ? All the math are inside GSdx. Core is special as it generates its own code. Globally could you tell me more about configuration so I can play with it properly and enable some flag by default.

**Comment by mmstick** [comment]
OpenGL hardware renderer, with default settings.

**Comment by gregory38** [comment]
Could you tell me which thread is mostly impacted ? EE/VU/GS.

I can profile easily GS side but my CPU is likely much faster than your. I'm limited by my GPU.
