### ISSUE TITLE
Clang tidy: readability simplify boolean expr

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1553]
Clang Tidy reports me this kind of constructs as bad construct. It is really minor, but I would like to have your opinion on this matter.

Code that trigger the boolean rules:
```
void foo(bool v1, bool v2) {
    if (v1 == true) {
    } else if (v2 == false) {
    }
}
```

Code fine with boolean rules:
```
void foo(bool v1, bool v2) {
    if (v1) {
    } else if (!v2) {
    }
}
```

Either we keep a mix of both construct. Or we keep only the 2nd one.

**Comment by gregory38** [comment]
@refractionpcsx2 @turtleli which version do you prefer ?

**Comment by refractionpcsx2** [comment]
I'm don't mind either way, I think v1 == true style bools are more readable, but both are fine.

**Comment by turtleli** [comment]
I prefer the second version, though both are fine.

**Comment by sudonim1** [comment]
Testing bools against bool constants just seems bizarre to me unless there's a special situation where that makes more sense to the reader.

**Comment by gregory38** [comment]
Ok. So I will replace the code to remove `true`/`false` constant.

**Comment by gregory38** [comment]
Ok I merged the branch to test a feature of github.

@ramapcsx2 @refractionpcsx2 @turtleli if the PR is a single commit, could you use the squash PR rather than merge PR. There is an arrow on the merge to the merge button to select the mode. Goal is to reduce branch pollution in the history.

**Comment by refractionpcsx2** [comment]
I always use "squash and merge" :)
