### ISSUE TITLE
GSdx HW/SW bug Megaman X Command Mission z fighting

### ISSUE THREAD

**Issue by woj1993** [PCSX2/pcsx2#1558]
## PCSX2 version:

pcsx2-v1.5.0-dev-1266-gccf198a-windows-x86
## PCSX2 options:

Full Clamping + Preserve sign, rounding to zero and MTVU. No options modifications affect this issue.
## Plugins used:

Defaults (GSdx32-AVX, LilyPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk). No particular plugins affect this issue.
Plugin settings:
GSdx (Direct3D11/OpenGL hardware modes). No setting affect this issue.
## Description:

Z fighting visible on final boss.
## Dumps:

https://www.dropbox.com/s/6pky3jhv2cwai1o/Megaman%20X%20Z%20fighting.7z?dl=0
## How to replicate:

Go to fight boss of 10 level.
## Last known version to work:

Never worked.
## Oldest tested version:

pcsx2 1.2.1
## PC specifications:

CPU: Intel Core i5-2300 2.80 GHz; GPU: Nvidia GT 440; OS: Windows 10 version 1607 compilation 14393.105
## Other comments:

@gregory38 This bug is in software mode too. I will not be able to connect to internet for a week.

**Comment by woj1993** [comment]
@gregory38 Can you check is this issue raport is correct?

**Comment by MrCK1** [comment]
I can see some minor flickering in the dumps, but it doesn't look like it's on us. It may just be the way the model was put together.
