### ISSUE TITLE
International Superstar Soccer (SLES-50039) - Graphical Issues in Menus

### ISSUE THREAD

**Issue by DPersonalized** [PCSX2/pcsx2#1560]
![gsdx_20160911232425](https://cloud.githubusercontent.com/assets/8225831/18420996/0578b4be-7877-11e6-8543-3df0c2f7df93.png)

International Superstar Soccer displays quite a few graphical glitches in the menus, present in both HW and SW mode, and in all backends.

![iss](https://cloud.githubusercontent.com/assets/8225831/18421006/2b23bcfe-7877-11e6-8010-698ccddc14aa.png)

From this console screenshot (credit to [YouTube user bucksby](https://www.youtube.com/channel/UCOtWZ23x3CycovXb_u3qiNg)), it should be fairly obvious as to what's wrong here. 

I have school in the morning, so I'll have to leave the bisecting until after then, although I'm fairly sure these issues were not present at one point.

**Comment by MrCK1** [comment]
Maybe try Preload Data Frame hack?

**Comment by gregory38** [comment]
What are the images ? Let's first focus on the SW renderer. First could you try the pr #1550 + edit gsdx.ini to add `UserHacks_AutoFlush = 1` with hw hack enabled. And tell us if the SW renderer work better ?

**Comment by FlatOutPS2** [comment]
Bug report and GS dump: 
http://forums.pcsx2.net/Thread-Bug-Report-International-superstar-soccer-PAL

**Comment by DPersonalized** [comment]
@gregory38 The PR doesn't appear to have any effect on the issue.

**Comment by gregory38** [comment]
Please test latest git. It must be better. The dump is only limited to the first menu. I can't check further.

**Comment by DPersonalized** [comment]
ISS looks identical to console now. Great work!

**Comment by gregory38** [comment]
Great. It is a good news :)
