### ISSUE TITLE
Is EE Clamping safe to be uncommented for Gran Turismo 4 in GameIndex.dbf?

### ISSUE THREAD

**Issue by rexcaptain501** [PCSX2/pcsx2#1563]
As Gran Turismo 4 has a minor problem with text ingame, you need EE Clamping to be set to 'Full' to fix the particular issue '('Ready...' staying on screen throughout particular races/licence tests)'. On the Forum I noticed that the fix was intentionally commented out in GameIndex.dbf, due to incompatibility with the License Tests in Gran Turismo Mode (http://forums.pcsx2.net/Thread-Gran-Turismo-4-Ready-stays-on-screen-all-race). I've tested using the fix settings (EE Clamping at Full) on a recent build and haven't seen any side effects at all, even in License Tests, working perfectly as far as I can tell.

Are there any side effects to using the fix that anyone is aware of? If not and no objections arise/objections are resolved, I'll make a pull request to change the applicable settings in GameIndex.dbf,

**Please note, I've only tested with PAL version SCES-51719, it would be helpful if someone could test a
 NTSC version**.

The setting in mind:
![clampsettings](https://cloud.githubusercontent.com/assets/10300935/18458965/fdd042b0-79b9-11e6-9ef0-385ee9c14bb6.PNG)

Testing Settings:

-PCSX2 version - 1.5.0 GIT 09-09-2016 (20160909215123)

-PCSX2 options: Balanced, with MTVU.

-Plugins used: GSdx32-SSE4, USBqemu-buzzR, along with the other default plugins.

-Plugin settings: Tested with GSdx32-SSE4 DX11 Mode, no side effects experienced.

**Comment by MrCK1** [comment]
I don't think so. It's also supposed to fix the in-game timer to display the proper lap time.

**Comment by rexcaptain501** [comment]
Nevermind, I just encountered a graphical error caused by Full EE Clamping that seems to be the cause of the game crashing when loading License Test A7 (other License Tests may be affected too). It looks like the only safe way to use Full EE Clamping is only when not playing the License Tests. Here's what it looks like if anyone is interested (the loading animation is not part of the corruption):
![capture](https://cloud.githubusercontent.com/assets/10300935/18462064/08469906-79d3-11e6-8207-8359bd90871d.PNG)
