### ISSUE TITLE
Battlefield 2: Black texture covering most of the screen in GSdx HW

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1565]
-PCSX2 version: 1.5.0-dev-1275 2016-09-14

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins

-Plugin settings: All HW renderers

-Description: All but the very top of the screen is covered by a black wall when using one of the Hardware renderers.

![battlefield 2](https://cloud.githubusercontent.com/assets/15942346/18557359/e107c584-7b6e-11e6-97ae-c6ffd35ad267.jpg)

-How to replicate: Boot the game and wait for the first menu.

-Last known version to work: Unknown, probably never worked

-PC specifications: CPU: Intel Core i5 GPU: AMD Radeon HD 6000 OS: Windows 7 64-bit

-Notes: 

Having a quick look with apitrace threw the following error:
**glDrawElementsBaseVertex(GL_TRIANGLES, 6, GL_UNSIGNED_INT, NULL, 0)**
`major api error 1000: glDrawElementsBaseVertex has generated an error (GL_INVALID_OPERATION)
glGetError(glDrawElementsBaseVertex) = GL_INVALID_OPERATION
warning: message: high error 1011: glGetProgramInterfaceiv failed because (depending on the operation) a referenced binding point is empty; a referenced name is not the name of an object; or the given name is otherwise not valid to this operation (GL_INVALID_VALUE)`

In debug build, when switching between HW and SW mode an assert message is thrown:
Assertion GSDeviceOGL.cpp 
Line: 1915
https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSDeviceOGL.cpp#L1915

And when running in SW mode the following message is shown in the debug log:
T:Error ID:17178    S:High  => glGetIntegerv parameter <pname> has an invalid enum '0x87fc' (GL_INVALID_ENUM)
- GS Dump:
  [Battlefield 2 menu.zip](https://github.com/PCSX2/pcsx2/files/475058/Battlefield.2.menu.zip)

**Comment by gregory38** [comment]
Which version of apitrace ? The stable version ? Or git ? I have some fixes to make it work with GSdx.

Anyway, looking at your screenshot. It is definitively a texture cache issue. I'm pretty sure the size of the band is a GS ram page (i.e. 32 pixels)

**Comment by FlatOutPS2** [comment]
I didn't know there was a stable version. I think the version I used was a git release, but several weeks old. I downloaded the latest one and the same errors appear.

Well, you'd know. I can only say it's not one of the TC issues that are flagged on a debug build, no log messages are tied to the issue.

**Comment by gregory38** [comment]
Hum, I'm not sure my patch are related to this issue. 

For the record (I really need to push the 2 last changes to upstream)
```
diff --git a/retrace/glretrace_main.cpp b/retrace/glretrace_main.cpp
index b53a818..eb9d5a7 100755
--- a/retrace/glretrace_main.cpp
+++ b/retrace/glretrace_main.cpp
@@ -664,10 +664,12 @@ debugOutputCallback(GLenum source, GLenum type, GLuint id, GLenum severity,
      * purely informative, and high frequency. */
     if (source == GL_DEBUG_SOURCE_API &&
         type == GL_DEBUG_TYPE_OTHER &&
-        severity == GL_DEBUG_SEVERITY_LOW &&
-        id == 131185) {
+        (severity == GL_DEBUG_SEVERITY_LOW || severity == GL_DEBUG_SEVERITY_NOTIFICATION) &&
+        (id == 131185 || id == 131076)) {
         return;
     }
+    if (type == GL_DEBUG_TYPE_PUSH_GROUP || type == GL_DEBUG_TYPE_POP_GROUP)
+        return;
 
     // Keep track of identical messages; and ignore them after a while.
     uint64_t messageHash =  (uint64_t)id
diff --git a/retrace/glstate.cpp b/retrace/glstate.cpp
index cda101d..6d4c2a4 100644
--- a/retrace/glstate.cpp
+++ b/retrace/glstate.cpp
@@ -175,6 +175,10 @@ BufferMapping::map(GLenum _target, GLuint _buffer)
     map_pointer = NULL;
     unmap = false;
 
+    if (_buffer == 0) {
+        return NULL;
+   }
+
     BufferBinding bb(target, buffer);
 
     // Recursive mappings of the same buffer are not allowed.  And with the
diff --git a/retrace/glstate_images.cpp b/retrace/glstate_images.cpp
index a51a22e..ac54264 100644
--- a/retrace/glstate_images.cpp
+++ b/retrace/glstate_images.cpp
@@ -907,6 +907,10 @@ getRenderbufferDesc(Context &context, GLint renderbuffer, ImageDesc &desc)
 static bool
 getFramebufferAttachmentDesc(Context &context, GLenum target, GLenum attachment, ImageDesc &desc)
 {
+    if (attachment == GL_NONE) {
+        return false;
+    }
+
     GLint object_type = GL_NONE;
     glGetFramebufferAttachmentParameteriv(target, attachment,
                                           GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE,
```

Anyway, I give it a quick look. And yes it is a texture cache issue. As you can see on the log below, the target isn't referenced with a single address. My guess is that 0x100 is a page line. Looking at the texture it could be a blit. I'm pretty sure you have a bump of memory usage. (not as big as GT4).
```
T:Oth	ID:3	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x100, C_32)
T:Oth	ID:3	S:Info	=> TC: src miss (0x1100, C_32)
T:Oth	ID:6	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x200, C_32)
T:Oth	ID:6	S:Info	=> TC: src miss (0x1200, C_32)
T:Oth	ID:9	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x300, C_32)
T:Oth	ID:9	S:Info	=> TC: src miss (0x1300, C_32)
T:Oth	ID:12	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x400, C_32)
T:Oth	ID:12	S:Info	=> TC: src miss (0x1400, C_32)
T:Oth	ID:15	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x500, C_32)
T:Oth	ID:15	S:Info	=> TC: src miss (0x1500, C_32)
T:Oth	ID:18	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x600, C_32)
T:Oth	ID:18	S:Info	=> TC: src miss (0x1600, C_32)
T:Oth	ID:21	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x700, C_32)
T:Oth	ID:21	S:Info	=> TC: src miss (0x1700, C_32)
T:Oth	ID:24	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x800, C_32)
T:Oth	ID:24	S:Info	=> TC: src miss (0x1800, C_32)
T:Oth	ID:27	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x900, C_32)
T:Oth	ID:27	S:Info	=> TC: src miss (0x1900, C_32)
T:Oth	ID:30	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xa00, C_32)
T:Oth	ID:30	S:Info	=> TC: src miss (0x1a00, C_32)
T:Oth	ID:33	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xb00, C_32)
T:Oth	ID:33	S:Info	=> TC: src miss (0x1b00, C_32)
T:Oth	ID:36	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xc00, C_32)
T:Oth	ID:36	S:Info	=> TC: src miss (0x1c00, C_32)
T:Oth	ID:39	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xd00, C_32)
T:Oth	ID:39	S:Info	=> TC: src miss (0x1d00, C_32)
T:Oth	ID:42	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xe00, C_32)
T:Oth	ID:42	S:Info	=> TC: src miss (0x1e00, C_32)
T:Oth	ID:45	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0xf00, C_32)
T:Oth	ID:45	S:Info	=> TC: src miss (0x1f00, C_32)
T:Oth	ID:48	S:Info	=> TC: Lookup Target(Color) 1280x1024, miss (0x1000, C_32)
```

**Comment by gregory38** [comment]
Oh by the way, Addresses are in blocks. And a DRAM page is 32 blocks. Therefore 0x100 == 8 pages. A 32 bit page (aka `C_32`) is 64x32 pixels, so framebuffer is 512x32 pixels which give you the top band

**Comment by RobertBColton** [comment]
This issue as well as the intro video flickering persists on the latest v1.5.0-dev.

**Comment by MistaMelon** [comment]
PCSX2 Version: v1.7.0-dev-1017 2021-02-27 07:11:23
Problem still exists, no settings seem to fix this issue.
All HW renderers have this problem
![image](https://user-images.githubusercontent.com/44997434/109388426-32444900-7907-11eb-8e94-6753f52bde30.png)

**Comment by tadanokojin** [comment]
GS caches read/write by page but draws 8x2 pixels left to right. So you page break much more in the horizontal direction.

So instead of doing the smart thing and copying in vertical strips a page wide, they sniffed a bunch of glue and did it in horizontal strips. Completely dumb and pointless. Probably the slowest way I've ever seen it done. Just doing a normal fullscreen sprite is likely faster on real hw.

Seems like a candidate for #3895

**Comment by iMineLink** [comment]
Here IIRC you would need to associate buffer offsetted draws to a previous render target to make the gpu draw all the strips in a single texture later used to display. Instead TC currently breaks up the draws by BP so creates one rt per stripe. Later when you read at BP of first stripe, you get just that and not the others (they are on different textures). I rewrote TC (somewhere in my repo) using *this* case as a test bench, implementing  the capability of creating one texture out of several (based on the required pages) but it's too slow right now (not in this specific case) and a bit broken (you need pixel perfect draw boundaries to mark pages..). If we want to go down the tex in rt way with current TC, you would need to make a mosaic of targets (unsupported) and allow "negative" offsets (first you have BP of first stripe, used for display also, then other stripes, so from 2nd stripe to first you go backwards). Likely better to find some HLE alternatives.

**Comment by refractionpcsx2** [comment]
Noting once this is fixed, it will need the SW FMV switch for the videos, since they're flashy on HW mode.

**Comment by Ezio-k** [comment]
Gpu change it to software

**Comment by marcondesu** [comment]
> Gpu change it to software

dude youre awsome, it works on pcsx2 1.5.0
