### ISSUE TITLE
Smuggler's Run: Minimap Depth Broken in GSdx HW OGL

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1568]
-PCSX2 version: PCSX2 1.5.0-20160916095837 - compiled on Sep 16 2016

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins

-Plugin settings: OGL HW Renderer, rest are default

-Description: Minimap depth is broken as seen in bottom-left of picture. SW mode is fine.

-Last known version to work: 1.4.0 - It doesn't seem to be a regression from any recent build - including bad rounding in Vice City's minimap. (So far I'm at dev-1048 with no success)

![gsdx_20160916170051](https://cloud.githubusercontent.com/assets/16314399/18601141/302e7494-7c2f-11e6-9d81-420abbe12983.png)

**Comment by FlatOutPS2** [comment]
I see a minimap, but it's on the bottom right of the picture. :p

**Comment by refractionpcsx2** [comment]
@FlatOutPS2 I think the issue is the minimap is going outside the confounds of the minimap circle, look at the stump of the tree behind it, the minimap map is going outside and cutting off bits of the tree

**Comment by FlatOutPS2** [comment]
Yes, I see the issue. I was just referring to the fact that the minimap is on the right side on the screen, not the left as mentioned in the description. ;)

**Comment by MrCK1** [comment]
Here's [the dump](http://www.filedropper.com/smugrunregressionsept16)

**Comment by FlatOutPS2** [comment]
Sadly the dump only shows black garbage in HW for me.

I thought Test Drive didn't boot. Has it been fixed?

**Comment by MrCK1** [comment]
No it hasn't. I have no idea how I got it to work. I think I unclamped the FPS and let it sit for at least 10 mins 

When I did get it working, I remembered to capture a savestate at the title screen; so that's what I use :)

**Comment by refractionpcsx2** [comment]
Test Drive has been working for ages afaik. You need the simulate VIF1 FIFO to get it to work. It should be in the gamedb though..

**Comment by MrCK1** [comment]
Maybe that's what it was :p

**Comment by FlatOutPS2** [comment]
> Test Drive has been working for ages afaik. You need the simulate VIF1 FIFO to get it to work. It should be in the gamedb though..

That's Test Drive Unlimited.

**Comment by refractionpcsx2** [comment]
oh yeh, my bad, thought it was eve of destruction :P

**Comment by FlatOutPS2** [comment]
Just got Test Drive to boot too, but I didn't see the issue(I have PAL version though). I did notice the pause menu options don't show up in hardware mode.

Can you add a GS dump for Test Drive and maybe a slightly longer dump of Smuggler's Run?

**Comment by MrCK1** [comment]
Oh yeah I remember testing that in a VS compile a few week ago.

[Here's another dump of Smuggler's Run](http://www.filedropper.com/smugrungsdumplongsept16) - also any reason why the shadows were always missing in HW renderer?

[Test Drive Dump](http://www.filedropper.com/testdriveminimapgsdump)

GSDumpGUI also gave me an assert for TD: `GSLocalMemory.h Line 233 bp < 16384`

**Comment by FlatOutPS2** [comment]
I don't see the issue in those 2 dumps either. It might be a driver issue. 

The long dump of Smuggler's Run does have an issue though. The first loop of the dump looks fine, but from the second one on, the ground starts flickering.

**Comment by gregory38** [comment]
Wait, is it really a regression ?

**Comment by refractionpcsx2** [comment]
Apparently it worked fine  on 1.4.0,  so I'd guess so

**Comment by gregory38** [comment]
Oh. Maybe it is because depth emulation wasn't enabled by default on 1.4.

**Comment by FlatOutPS2** [comment]
Can you reproduce it with the dump? Because I can't with the dumps or the pal version of TD...

**Comment by gregory38** [comment]
@MrCK1 did you generate the dump on the SW or the HW renderer?

**Comment by MrCK1** [comment]
@FlatoutPS2 one thing to note about Smuggler's run is that sometimes the ground flickers after starting a game. Toggling renders once fixes that

**Comment by MrCK1** [comment]
The depth issue is gone in both games now. Still trying to figure out which build fixed the regression.
