### ISSUE TITLE
French Translation Missing for Boot CDVD (Full)

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1570]
**Latest build (No French Translation)**
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/18607330/2c9a63ce-7cca-11e6-828e-7158817e085e.png)

**PCSX2 1.4 (correct French Translation)**
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/18607337/3fecf7a2-7cca-11e6-88b6-ff53da57e5a1.png)

**Comment by mirh** [comment]
It's not just French. 
And.. I dunno, if you have the time you could try to bisect this. 26 February build was still fine for example.

**Comment by gregory38** [comment]
just likely need to update the translation file. git build aren't official release so translation can be a bit off.

**Comment by mirh** [comment]
Bisected, this was introtuced in #1388.

**Comment by FlatOutPS2** [comment]
It's because this was expected to be merged: https://github.com/PCSX2/pcsx2/pull/1381/commits
But it never happened and I guess the translations weren't updated again afterwards.

**Comment by gregory38** [comment]
Translation must be unfuzzed but I think we are good now.The initial string is value so I'm closing this one.
