### ISSUE TITLE
Github recent improvement: review and project

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1580]
@PCSX2/owners @PCSX2/commiters 

Recently GH added some way to ease the review of PR. I think it is a good opportunity to discuss a bit about the feature. Do you like it, dislike it.

There are others alternative
- https://reviewable.io/
- https://www.codereviewhub.com/
- countless of them on google.

Do you have any experience with any external addons. Will it help us to add an extension to improve reviewing.

By the way, github added a project interface too. As far as google told me, (check tab after pull request), it is a way to group task/issue/pr on various card board. It could help you to manage your homework.

**Comment by ssakash** [comment]
> There are others alternative
    * https://reviewable.io/
    * https://www.codereviewhub.com/
    * countless of them on google.

I would prefer sticking to the review function of GitHub, it seems much better and doesn't need any other external integration. Personally I also dislike `` https://reviewable.io/``, Dolphin seems to use it and from the looks of it, it seems to allow reviewing only on an external site which is linked individually to every single Pull requests.

>By the way, github added a project interface too. As far as google told me, (check tab after pull request), it is a way to group task/issue/pr on various card board. It could help you to manage your homework.

Yeah, ``Projects`` tab seems rather useful. No clue how to use it though :P

**Comment by ramapcsx2** [comment]
@ssakash Using projects is simple:
- create a new project
- add columns / sections
- drag issues or prs (maybe more?) to your columns
