### ISSUE TITLE
[Feature Request] Open cheat folder in explorer window button.

### ISSUE THREAD

**Issue by ImSpecial** [PCSX2/pcsx2#1584]
This is a quality of life feature I'd like to see, similar to how you have for memory card management ie. "Open in Explorer" I'd like to see the same but for cheats, since if you want to add, disable, or edit your cheats you'll need to go into that folder to edit the pnach file in notepad or whatever, and where I keep my PCSX2 folder is quite a few levels deep on my HD, so it gets annoying I can't do this in a few clicks.

Not sure where you would put this option to open in explorer, maybe right underneath the "Enable Cheats" under System.

**Comment by vsub** [comment]
You can use my tool for both the save state info(with extra image preview)and also for what you want here
http://forums.pcsx2.net/Thread-Multi-Converter-Cheats-decrypter-converter-editor-and-much-more
This can also be useful
http://forums.pcsx2.net/Thread-Quick-pnach-tool
