### ISSUE TITLE
[Feature Request] Savestate "save successful/load successful" dialogs.

### ISSUE THREAD

**Issue by ImSpecial** [PCSX2/pcsx2#1585]
Optional of course as I can see some people wanting to have a clean, no message, no bother experience, but I would prefer to have a little message in the corner of my screen that says something along the lines of "save slot 1 saved" or "save slot 1 loaded" display when you save/loaded a savestate.

There has been a few time in my experience when I hit the save hotkey to save only to have it not actually save for some reason, so when I went to load it, what I thought was my last save, well it was much further back then I had thought it was and lost quite a bit of progress, oh well, but a message here would just let you know everything went okay.

**Comment by yxmline** [comment]
I think these messages better display with osd
https://github.com/PCSX2/pcsx2/pull/1431

**Comment by FlatOutPS2** [comment]
You shouldn't rely on savestates so much for saving your progress, it's better to use the in-game saves. But the savestate on-screen logs are part of the OSD pull request @yxmline linked, so your request will be fulfilled.

**Comment by RebelliousX** [comment]
I wonder why tell now no one suggested (according to my knowledge) using screenshot of the save state at the top right corner, exactly like Pete's plugins for PSX?! It is so helpful and saves time instead of going through and load the entire list of 10 save states just to find the one you need. Of course, forcing this is not good, so it should be an option. Personally, I liked the top OSD menu for Pete's plugins when pressing Del key to change settings on the fly.

**Comment by lightningterror** [comment]
Can this be closed since now we have OSD manager?

**Comment by avih** [comment]
> Can this be closed since now we have OSD manager?

Are you forgetting that the OSD is only available with OpenGL and that many AMD users cannot use it properly?

**Comment by FlatOutPS2** [comment]
Then you need reopen a lot of issues, like this(https://github.com/PCSX2/pcsx2/issues/1816) one that was recently closed, but only fixed for OpenGL.

**Comment by avih** [comment]
So effectively you decided that if it's fixed for OpenGL, then it's fixed? You do know many PCSX2 users use AMD GPUs, right?

**Comment by FlatOutPS2** [comment]
I didn't decide anything. I'm just saying we should be consistent. To be fair, ICO runs just fine in OpenGL even with 4x upscaling.

**Comment by lightningterror** [comment]
It was just a question and I'm also an AMD user as well.

And I also asked because it's a feature request (which is already done) , now it just needs to be ported to DirectX.

Anyway an alternative would be renaming the topic to "OSD port to Direct3D" or something.

**Comment by MrCK1** [comment]
@lightningterror was the OSD ever ported to DX11? I can't remember 😛

**Comment by lightningterror** [comment]
Nope never xD
Do you wanna port it ? :stuck_out_tongue:

**Comment by MrCK1** [comment]
No, but you can. I prefer OpenGL. 😛
