### ISSUE TITLE
[Linux] Odin Sphere does not recognise Start button

### ISSUE THREAD

**Issue by Hirato** [PCSX2/pcsx2#1589]
If I boot up Odin Sphere, all the splash screens go past and I can see the main menu.
However, it asks me to press Start, but none of the buttons I press is ever recognised as start.

PCSX2 is built from master with revision '6e2bf98'.
I'm using the OnePad input driver, I also gave Lilypad a quick try without much success (granted I don't know how to configure it in Linux, so that one might just be unconfigured).

Not sure if this is a regression either, since the wiki and forums suggests that it was working on windows as far back as 2009.

**Comment by gregory38** [comment]
For sure it used to work, as I play the game on my computer :+1: 
However lots of code was updated recently. Maybe I broke something  :cry:

**Comment by gregory38** [comment]
I will test it on my side.

**Comment by Hirato** [comment]
Just saw fc32b749dd3c8316b55ff58a5c7c9a143137064a land and it fixes the issue.

Might also want to see if #1598 is a duplicate.
