### ISSUE TITLE
GSDumpGUI crashes when executable is renamed

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1592]
Specifically I believe the "children" (client?) process is hardcoded to look for gsdumpgui.exe

**Comment by turtleli** [comment]
Try the patch below:
```
diff --git a/tools/GSDumpGUI/Forms/frmMain.cs b/tools/GSDumpGUI/Forms/frmMain.cs
index 12a9dfc..07e74a4 100644
--- a/tools/GSDumpGUI/Forms/frmMain.cs
+++ b/tools/GSDumpGUI/Forms/frmMain.cs
@@ -218,7 +218,7 @@ namespace GSDumpGUI
             psi.RedirectStandardOutput = true;
             psi.RedirectStandardError = false;
             psi.CreateNoWindow = true;
-            psi.FileName = AppDomain.CurrentDomain.BaseDirectory + "GsDumpGUI.exe";
+            psi.FileName = Process.GetCurrentProcess().ProcessName;
             psi.Arguments = "\"" + DLLPath + "\"" + " \"" + DumpPath + "\"" + " \"" + Function + "\"" + " " + SelectedRenderer;
             Process p = Process.Start(psi);
             p.OutputDataReceived += new DataReceivedEventHandler(p_OutputDataReceived);
```

**Comment by mirh** [comment]
Yes it works. 
While you are at it.. I'd also wonder why sometimes I have to click two time start button, before an actually-doing-something process appears.

**Comment by turtleli** [comment]
> While you are at it.. I'd also wonder why sometimes I have to click two time start button, before an actually-doing-something process appears.

Don't have a clue. I looked into the name bug because it sounded stupid and curiosity got the better of me. If you want this reopened so someone might look into the issue, ask (or just open a new issue).
