### ISSUE TITLE
Silent Hill: Shattered Memories. Many rendering bugs

### ISSUE THREAD

**Issue by Sunderland93** [PCSX2/pcsx2#1594]
-PCSX2 version: 1.4 and 1.5.0 GIT 25-09-2016
-PCSX2 options: enabled EE cyclerate (2) and VU stealing (1)
-Plugins used: GSdx (hardware & software), SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD, the rest are null plugins.
-Plugin settings: Defaults
-Description: I recorded all of bugs, that has in Silent Hill Shattered Memories on all render backends https://www.youtube.com/watch?v=QwOFionyNv8
-How to replicate: Just play Silent Hill: Shattered Memories
-Last known version to work: Never worked correctly on GSdx Hardware, on GSdx Software worked in PCSX r5337
-PC specifications: CPU: Intel Core i3-550, GPU: Asus GTX 760 DirectCU Mini, OS: Windows 8.1 and Debian 8.6.

**Comment by FlatOutPS2** [comment]
There already several issues open about this game, so I'll close this one. I suggest you add your video to this issue: https://github.com/PCSX2/pcsx2/issues/1326
