### ISSUE TITLE
When "Renderer" isn't set.. Unforeseen consequences

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1596]
Just try to replay [this](https://github.com/PCSX2/pcsx2/issues/1575#issuecomment-250288238) gsdump with a void gsdx.ini

After playing with the setting of a filled up config file.. I found that to be the odd cause.

**Comment by FlatOutPS2** [comment]
Yes, with a void gsdx.ini it looks like D3D9 Hardware mode. What's the issue?

**Comment by mirh** [comment]
Oh wait.. Renderer is the RENDERER, not **adapter**. 
I'm retarded. 

Good night.
