### ISSUE TITLE
not detect input from keyboard (game Ar Tonelico II)

### ISSUE THREAD

**Issue by ingalexander** [PCSX2/pcsx2#1598]
Hello to the comunity, thanks for this project
-PCSX2 version: PCSX2 1.5.0-0 - compiled on Sep 28 2016
-PCSX2 options: Defaults, no settings modifications affect the issue
-Plugins used: GSdx, SPU2-X, OnePAD,CDVDnull Driver
-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The game start without problem but in the first screen that ask for input, the game no detect any of the configured input in the keyboard.

-How to replicate: Start the game Ar Tonelico II and wait for the memory card dialog, can't pass the dialog because the inputs are not detected

-Last known version to work: PCSX2 1.4.0-4 2016-01-06 (from pcsx2.official.ppa repository) (not usable because is not compatible with ubuntu 16.04)

-PC specifications: CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz GPU: GeForce 820M/PCIe/SSE2 OS: Ubuntu 16.04 LTS 64-bit

**Comment by jcdenton2k** [comment]
1 - You should mention your OS at the beginning quite clearly.

2 - Make sure your controller options are configured and you have your controller detected under the OS itself.

3 - Try using LilyPad to test if it is still giving you trouble.

**Comment by gregory38** [comment]
@ingalexander Please test latest git version.

**Comment by ingalexander** [comment]
@gregory38 , Finish testing git version of 30 sept, it works perfectly now with onePad, thanks

**Comment by FlatOutPS2** [comment]
Then this issue can be closed.
