### ISSUE TITLE
GSDX: JAK2 USA(CRC: 9184AAF1) is still bugs

### ISSUE THREAD

**Issue by arcade1977** [PCSX2/pcsx2#1603]
Jak‘s hair and face are still exist strange bugs，eyes are black

**Comment by ssakash** [comment]
Please use the [forums](http://forums.pcsx2.net/index.php) instead for support. Your report lacks a lot of necessary information to be considered as a [**_valid_ bug report**](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues).
