### ISSUE TITLE
Ratchet & Clank series, Jak 3 - Incorrect transparency and specular

### ISSUE THREAD

**Issue by Dreadmoth** [PCSX2/pcsx2#1607]
-PCSX2 version: 3996fbe and newer
-PCSX2 options: Defaults, no settings modifications affect the issue
-Plugins used: GSdx, SPU2-X, LilyPad, cdvdGigaherz

-Plugin settings: Tested all GSdx hardware and software renderers. The issue is fixed by using a software renderer of GSdx. Issue intensity varies slightly between hardware renderers and OpenGL Blending Unit Accuracy levels.

-Description: Many transparent objects and sprites are more opaque and sometimes brighter than they're supposed to be in the Ratchet & Clank series and Jak 3. Specular effects are brighter / more intense than they're supposed to be in Ratchet & Clank 2, 3 and Ratchet Gladiator.

-How to replicate: 
**Ratchet & Clank:** Start a new game, inspect the cockpit of Ratchet's spaceship. Travel to planet Novalis and inspect water and Gadgetron vendor display.
Example image - Novalis water: [Hardware](http://i.imgur.com/DhFyq8T.png) | [Software](http://i.imgur.com/4wUVyAo.png) | [Hardware (last working version)](http://i.imgur.com/PghAHfc.png)
**Ratchet & Clank 2:** Start a new game, inspect the floor. Proceed up elevator and inspect "corona" effect around spotlights in following rooms.
**Ratchet & Clank 3:**  Start a new game, inspect Ratchet's spaceship - cockpit glass, paint specular, shadow of the ship. Proceed to the end of the first area and inspect shiny Galactic Ranger dropship. Travel to planet Florana and inspect shiny green glass domes and windows.
Example image - Ratchet's spaceship: [Hardware](http://i.imgur.com/d9NjRVw.png) | [Software](http://i.imgur.com/nHtzkFn.png) | [Hardware (last working version)](http://i.imgur.com/AQkLp15.png)
**Ratchet Gladiator:** Start a new game and travel to planet Catacrom Four. Inspect metallic structures in the environment.
Example image - metal structures and robot: [Hardware](http://i.imgur.com/BSwHf70.png) | [Software](http://i.imgur.com/C5KRFr0.png) | [Hardware (last working version)](http://i.imgur.com/cf0EyYs.png)
**Jak 3:** Watch intro cutscene and observe engine smoke trails and dust clouds.

-Last known version to work: c5f086b - with this version and earlier, most effects affected by the current issue look very similar to their appearance on software renderers when using D3D11 or OpenGL hardware renderers. With OpenGL hardware renderer and Blending Unit Accuracy of High or above, all affected effects look identical to software rendering.

-PC specifications: CPU: Intel Core i7 4770 @ 3.4Ghz GPU: Gigabyte GeForce GTX770 Windforce OC 4GB OS: Windows 7 SP1 (64-bit)

**Comment by gregory38** [comment]
Could you proive me a gs dump?

**Comment by Dreadmoth** [comment]
[Ratchet and Clank 3 - Florana - specular alpha.zip](https://github.com/PCSX2/pcsx2/files/510226/Ratchet.and.Clank.3.-.Florana.-.specular.alpha.zip)

**Comment by gregory38** [comment]
Well, would you have a dump with a more broken scene. I might need to compare draw by draw call. And it will be very hard here. I would prefer the water of the 1.

**Comment by Dreadmoth** [comment]
Okay: 
[Ratchet and Clank - Novalis - water opacity.zip](https://github.com/PCSX2/pcsx2/files/510256/Ratchet.and.Clank.-.Novalis.-.water.opacity.zip)
