### ISSUE TITLE
psxmode/GSdx: PS GPU24 support

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1608]
Psxmode uses a dedicated more for the display called PS_GPU24.

Here a potential layout.
- 32 bits layout with 2 block merged
  Block number by page

```
0 2 8 10
1 3 9  11
4 6 12 14
5 7 13 15
```

A block line contains 16 RGB packed pixels + 16 bytes of packing (Or potentially no packing.)

**Comment by sudonim1** [comment]
Just to head off any speculation and avoid duplicated work in case nothing gets committed for a while: we've worked it out.

**Comment by ramapcsx2** [comment]
Okay, I've seen it work and that's great to know :)
One tidbit: Would be nice to have it in SW and HW :)

**Comment by gregory38** [comment]
Actually I'm working on something that we could fit in GSLocalMemory (aka common code). It works on the HW too with the `preload frame with gs data` hack. However I've some strange flickering (even on SW). But it could be  gsdump issue.

**Comment by gregory38** [comment]
@ramapcsx2 could you test the last git.

**Comment by FlatOutPS2** [comment]
There are still several issues with the FMV's in both SW and HW.  There are artifacts popping up in the opening FMV of N4S and Ace Combat 2 has a horizontal half-screen split issue.

Preload hack for HW also seems to only work after pausing and resuming the emulator.

Still, great progress compared to before. :)

**Comment by gregory38** [comment]
![00035_f5035_fr0_00000_ps24](https://cloud.githubusercontent.com/assets/1569559/19130946/baab5664-8b4d-11e6-9113-ce6245b6aa09.png)
I'm not sure the issue is GSdx related. It feels like core send garbage from time to time.

**Comment by MrCK1** [comment]
@FlatOutPS2 JMMT also has the horizontal half split FMVs

**Comment by ramapcsx2** [comment]
Great work guys, Grandia works in SW :)
> I'm not sure the issue is GSdx related. It feels like core send garbage from time to time.
Yes, that's IOP DMA of garbage data when it was faster than CDROM. It's a core bug with the DMA controller that we need to fix.

**Comment by ramapcsx2** [comment]
This is the Final Fantasy 8 intro: 
![](https://i.imgur.com/bl2JQhU.png)

Blockdump here if you want to take a look :)
https://www.sendspace.com/file/y3swzm

**Comment by FlatOutPS2** [comment]
The Ace Combat 2 half-screen issue looks the same as the FF VIII intro. And the garbage in the image @gregory38 posted is the same as what appears in the N4S intro. So both seem like common issues.

**Comment by ramapcsx2** [comment]
So "FF8 intro" might be a little more tricky:
The image jumps around a lot, sometimes showing correct decoding but mostly the "half screen" version.
Maybe it has different scanline lengths or something like that.

**Comment by gregory38** [comment]
I found a description of the format end of chapter 5.2.2

The rectangular setting is the same as PSMCT16. And pixels are RGB packed by group of 4. So you have `R0G0B0 | R1G1B1 | R2G2B2 | R3G3B3`
