### ISSUE TITLE
Jak3: jak‘s hair or face is black

### ISSUE THREAD

**Issue by arcade1977** [PCSX2/pcsx2#1611]
This issue can be solved for a while by press F9*2 , but it will  become abnormal soon :

![-1](https://cloud.githubusercontent.com/assets/5054123/19196929/fc198f74-8ce9-11e6-9fc3-ad0ef1807303.jpg)
![-2](https://cloud.githubusercontent.com/assets/5054123/19196930/fc1a50e4-8ce9-11e6-8ae9-2f09e87b0521.jpg)

**Comment by FlatOutPS2** [comment]
Please follow our issue reporting guidelines (https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues) and use the default template: https://github.com/PCSX2/pcsx2/blob/master/ISSUE_TEMPLATE.md

**Comment by refractionpcsx2** [comment]
This is already being delt with in #168 along with all the other Jak games and their issues, so I'm marking this as a duplicate
