### ISSUE TITLE
psxmode: PGIF FIFO Overflow (C:12 Final Resistance)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1616]
***PCSX2 version:***
v1.5.0-dev-1436-g309b903-1931-vs2015-Win32-AppVeyor

***PCSX2 options:***
Default

***Plugins used:***
Default, 8x Native resolution in HW OGL

***Description of the issue:***
PCSX2 will crash upon completing the demo sequence in-game. Graphics are corrupted unless you boot in OGL SW and switch to HW

***How to reproduce the issue:***
Boot GSdx in OGL SW, and then switch to HW after it reaches the title screen. (if you did this correctly the fonts will be readable) On the title screen, let the "demo" run. After finishing, the game will return to the title screen; but PCSX2 crashes as it begins the 2nd playthrough

***Getting the PGIF Overflow to print in the console requires a bit of luck; so I've included 2 emulogs

[Emulog 1](http://pastebin.com/raw/DAyTu8E9): (crash without overflow) 
[Emulog 2](http://pastebin.com/raw/M1YjChyc) (includes crash w/ PGIF FIFO overflow)

***Last known version to work:***
N/A

***PC specifications:***
Intel Core i5-4460, nVidia GTX 970, Windows 10-64 Bit Build 14942

**Comment by ramapcsx2** [comment]
I suppose we need to put up a notice on this. Basically, psxmode reports aren't useful at this point. Half the emulation is missing and PGIF is guesswork without any hardware testing done yet.
Still, thanks for the enthusiasm ;)
