### ISSUE TITLE
WRC Series Regression September-October

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1618]
**Current dev build :**
- WRC - World Rally Championship (Blackscreen Startup Boot)
- WRC II Extreme (Blackscreen Startup Boot)
- WRC 3 (Blackscreen Startup Boot)
- WRC "5" Rally Evolved (Blackscreen Startup Boot)

**Games boot properly only on :**
- PCSX2 1.4 or PCSX2 1.5.0-20160925195544 (September build, may follow-up working too)

There is probably some recent CD decoding issues, should be easy to reproduce if you own one of thoses games. (Games are played with the ISO feature).

**Comment by FlatOutPS2** [comment]
It's just the latest build. It causes boot issues on several games.

**Comment by sudonim1** [comment]
This is me for some reason, not sure why yet.  I only removed the psxRegs.interrupt &= ~1; because I couldn't see that the LSB was set anywhere.

**Comment by sudonim1** [comment]
Actually not sure it's 733fd79 after all, I'm getting random test results.

**Comment by FlatOutPS2** [comment]
> Actually not sure it's 733fd79 after all, I'm getting random test results.

Trust me, it is. But it's not related to the psxRegs.interrupt/ IopEvt_SIFhack.

**Comment by FlatOutPS2** [comment]
`IopEvt_Cdvd` needs its value back.

**Comment by sudonim1** [comment]
I agree with your testing results but how the hell is that possible? It's only used as a bit index in psxRegs.interrupt and an index in psxRegs.sCycle and psxRegs.eCycle.  There is no code I can find which accesses any of these directly or indirectly by anything other than an IopEventId.  This bug is impossible.

**Comment by turtleli** [comment]
Probably here: https://github.com/PCSX2/pcsx2/blob/733fd79f46c29b7904c05741ece32a2cce61e4c2/pcsx2/R3000A.cpp#L183

```
	if( psxRegs.interrupt & ( (1ul<<5) | (3ul<<11) | (3ul<<20) | (3ul<<17) ) )
	{
		IopTestEvent(IopEvt_Cdvd,		cdvdActionInterrupt);
		IopTestEvent(IopEvt_Dma11,		psxDMA11Interrupt);	// SIO2
		IopTestEvent(IopEvt_Dma12,		psxDMA12Interrupt);	// SIO2
		IopTestEvent(IopEvt_Cdrom,		cdrInterrupt);
		IopTestEvent(IopEvt_CdromRead,	cdrReadInterrupt);
		IopTestEvent(IopEvt_DEV9,		dev9Interrupt);
		IopTestEvent(IopEvt_USB,		usbInterrupt);
	}
```

**Comment by sudonim1** [comment]
Okay thank you, I am apparently blind.
