### ISSUE TITLE
WX/GUI: Discuss possible string changes

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1620]
This issue is intended as a continuation of PR #1577 as turtleli suggested. If you'd like to see any strings changed, you can suggest them here

So far we have:
- [x]  Fix "Shutdown" menu state if necessary
- [x]  Change `Iso` to `ISO` (turtleli's suggestion)
- [x]  Resolve boot medium GUI behavior (#1381)
- [x]  Remove `HostFs` from GUI on release builds (user can still edit value via pcsx2_vm)
- [ ]  Reduce string size of gamefix panel help text.
- [x]  ~~Remove tooltip of ``Restore Defaults`` in speedhacks panel.~~ **(done by turtleli)**

**Comment by FlatOutPS2** [comment]
We should also still add part of this PR: https://github.com/PCSX2/pcsx2/pull/1381

For this behaviour: Properly display the boot medium on menu item Example: ISO , CDVD , BIOS

**Comment by piorrro33** [comment]
I personally am perfectly fine with all these changes, except that I would personally think that the Debug tab should be removed by default and may be enabled manually through an edit in a config file, or maybe simply shift it to the Misc. menu?

**Comment by gregory38** [comment]
```
Remove Host Filesystem option from menu - It's rarely used besides homebrew/demos and any user who needs to use it can just change the HostFs value in PCSX2_vm
```
Keep it on dbg/dev build.

**Comment by MrCK1** [comment]
Right now we're discussing other strings that could be changed in issue #1620 as you probably saw already. Until then this sits

**Comment by FlatOutPS2** [comment]
Why are you referencing this issue from within this issue? :S

**Comment by piorrro33** [comment]
I think he meant #1381.

**Comment by jcdenton2k** [comment]
I would also like to see Iso changed to ISO :)

**Comment by gregory38** [comment]
What is the status? If you want to update string it is now

**Comment by piorrro33** [comment]
Seems fine to me, but I'd add my comment above too, remove the Debug tab by default, since it's useless for most.

**Comment by ssakash** [comment]
@MrCK1 

Are you planning on doing these [suggested changes](https://github.com/PCSX2/pcsx2/issues/1620#issue-183052252) at #1577? I could handle it if you're busy. Sorry for the rush, as these changes should be handled before the translation update and @gregory38 seems to be in a bit of hurry for the 1.6 release :P

**Comment by piorrro33** [comment]
> Rather unlikely to happen.
Why? I mean, the end-user has no use of the debugger, and it would be pretty easy to hide.

**Comment by ssakash** [comment]
> Why? I mean, the end-user has no use of the debugger, and it would be pretty easy to hide. 

Yes, it's easy to hide. However I don't agree that it has no use for the end-user, it is useful for people who are interested in game hacking, translation patches and for other _miscellaneous_ stuffs.

Though honestly what's the harm in having a single debug tab in the main frame?

**Comment by piorrro33** [comment]
Oh you're right I forgot about them. And no there's no problem with having it, I just felt like it didn't have to be enabled by default.

Le sam. 5 nov. 2016 à 18:45, Akash <notifications@github.com<mailto:notifications@github.com>> a écrit :

Why? I mean, the end-user has no use of the debugger, and it would be pretty easy to hide.

Yes, it's easy to hide. However I don't agree that it has no use for the end-user, it is useful for people who are interested in game hacking, translation patches and for other miscellaneous stuffs.

Though honestly what's the harm in having a single debug tab in the main frame?

**Comment by MrCK1** [comment]
@ssakash You should probably handle that, I have some work to do :p 

If you recall, the fix you suggested fixed the shutdown function works but it isn't technically correct. I guess we could always revisit that later after merging.

Also, I would use FlatOut's suggestion for the language selector instead of mine for #1577.

```*this += Heading(L"Language switch will only affect newly opened windows.\n");```
```*this += Heading(L"Full change will not apply until PCSX2 is restarted.\n"); ```

**Comment by ssakash** [comment]
> If you recall, the fix you suggested for the shutdown function works but it isn't technically correct

How is it _technically_ not correct? I committed that same idea discussed on https://github.com/PCSX2/pcsx2/pull/1577#issuecomment-248964754 at #1651. (https://github.com/PCSX2/pcsx2/pull/1651/commits/6b185febd36bee80c11d2942f3a3bcbec27f7a93)

**Comment by MrCK1** [comment]
@ssakash Oh never mind :p

**Comment by gregory38** [comment]
In the gamefix panel
```
Manual game fixes will NOT increase your performance. In fact they may decrease it.
```
```
Manual game fixes will DECREASE your performance.
```
Goal is to reduce the string size and to have something easier to understand.

**Comment by refractionpcsx2** [comment]
> Goal is to reduce the string size and to have something easier to understand.

how about

> Manual game fixes might NEGATIVELY affect speed.

As some (like the EE Timing Fix) can actually bring a small speed boost.

**Comment by gregory38** [comment]
My understanding was that we don't want people to use those manual gamefixes. And surely not as a speed hack. So I think it  would better to avoid the may/migh/potentially/... (which I'm not sure can be translated exactly in others languages)

**Comment by refractionpcsx2** [comment]
Fairr enough :)

**Comment by avih** [comment]
> As some (like the EE Timing Fix) can actually bring a small speed boost.

While that might be true, I don't think we want to advertise it at the description/tooltip. In general, these fixes are really not about speed but actually about making the game not break.

That being said, I think we should make the text as long as we think is appropriate (within reason - probably not more than two sentences) to relay the info, which IMHO is mainly:
- It's not about speed.
- It's about working around breaking issues.
- It's likely to break things if used "randomly".

**Comment by gregory38** [comment]
Long text will generate a bigger space below (likely due to some bug in the gui stuff). And then people will small screen complain. So it would be better to have a string that goes straight to the fact.

**Comment by refractionpcsx2** [comment]
> Manual game fixes will break games and negatively affect performance. Only use these if you know what you are doing or for debugging purposes.

Hows that? It's shorter than what's there :P

**Comment by gregory38** [comment]
And the automatic stuff ? Do you want to keep the first part.
```
It's better to enable 'Automatic game fixes' at the main menu instead, and leave this page empty.
```
Or rephrased?

**Comment by refractionpcsx2** [comment]
Well the choice is to leave it out just to scare people away, or add on to the end "Required fixes are applied with 'Automatic game fixes' Enabled"

or something, to that effect.

**Comment by avih** [comment]
Option one: `Game fixes help with broken games and don't improve speed. Enabling fixes is likely to break many games if not used carefully. Automatic game fixes at the main menu will automatically enable carefully tested fixes for specific games`.

Option two: by default, hide this panel from the GUI (with the manual fixes disabled), as well as hiding the "automatic game fixes" at the main menu (while leaving it enabled). They can be restored to user control if some config is enabled (at `pcsx2.ui.ini`) - which is disabled by default.

This is a user facing message, developers and hackers would know that, so

**Comment by gregory38** [comment]
I will love 2 but I'm afraid there are still useful game fix (in particular the FMV gsdx hack). Otherwise we need to update the db.

1 is shorter than current string so it is good for me.

**Comment by avih** [comment]
> I'm afraid there are still useful game fix (in particular the FMV gsdx hack)

If this really is a feature which "normal" users should attempt (disclaimer - I personally never enabled it, nor manual game fixes in general), then we could leave it out of the "hidden for normal users" area.

The point is that the options which are most likely to damage when not used carefully are hidden by default.

**Comment by willkuer** [comment]
Maybe move the FMV fix to gs settings below 'synchronized MTGS'?
And accordingly EE timing hack (and gif fifo) to the EE/IOP settings below the rounding options (and VU xgkick hack to the VU setting page)?

I think EE timing hack and FMV hack are the most common ones. The new gif fifo appears to be still quite new and probably is not properly included in the gamedbf. The least often used hack I see in forum discussion is vu xgkick hack.  I never observed usage of all other game fixes.

**Comment by gregory38** [comment]
Hum, without moving stuff around. Maybe we can just hide the less used gamefix checkbox (based on an hidden value)

**Comment by turtleli** [comment]
How is the "Restore Defaults" button supposed to work on the Speedhacks Panel? I just noticed the tooltip says:

`Resets all speedhack options to their defaults, which consequently turns them all OFF.`

but it actually turns on INTC Spin Detection, mVU Flag Hack, and Enable Wait Loop Detection....

Does the string need changed or does the behaviour need changed?

**Comment by gregory38** [comment]
I suspect it kind of enable the recommended speedhack but in the meantime it disable the general speedhack button.
To be honest, I never use it. I think it would be more logical to really disable all speedhacks.
@FlatOutPS2 @avih any opinion ?

**Comment by FlatOutPS2** [comment]
>  but it actually turns on INTC Spin Detection, mVU Flag Hack, and Enable Wait Loop Detection....

As those are the "safe" speedhacks and rarely need to be turned off I'd prefer this to remain the behaviour.  Under normal circumstances I doubt anyone would want to turn on some speedhacks but not those three. If you want to turn off all speedhacks you can just use the toggle anyway.

**Comment by turtleli** [comment]
Hmm... actually, do we even need a tooltip there in the first place?

**Comment by FlatOutPS2** [comment]
> Hmm... actually, do we even need a tooltip there in the first place?

Probably not, `Restore Defaults` should be self-explanatory. Though the string can also be adjusted to say it disables all but the recommended speedhacks.

**Comment by gregory38** [comment]
Just remove it, less work on the translation side.

**Comment by ssakash** [comment]
Yeah, best to remove it. The word ``"Restore Default"`` itself is rather enough for users to interpret it's function.

**Comment by MrCK1** [comment]
I know there's still some ongoing work with WX here - but some of the dialogs contain excessive whitespace. Is something going to be done about this? :P

![dialogbox](https://cloud.githubusercontent.com/assets/16314399/21249375/883949e8-c30b-11e6-8246-e04853a28b04.png)

**Comment by turtleli** [comment]
About the Speedhacks panel EE cycle rate and VU cycle stealing slider descriptions - is the number at the start of the description necessary? If another option is added between the existing values, the strings will need changed and that'll require a translation update.

> I know there's still some ongoing work with WX here - but some of the dialogs contain excessive whitespace. Is something going to be done about this? :P

Probably not in the short term? It's kinda difficult to fix the current GUI code (or at least I think so).

**Comment by gregory38** [comment]
Any status ? are we done here ?

**Comment by piorrro33** [comment]
Maybe we can do something about what @MrCK1 mentioned?

**Comment by gregory38** [comment]
@MrCK1 @turtleli @refractionpcsx2 @ssakash ping? Is it fine, or do we want to update some stuff (I would like to keep the string frozen) ?

**Comment by ssakash** [comment]
@gregory38 

Your [suggestion](https://github.com/PCSX2/pcsx2/issues/1620#issuecomment-260120492) to reduce the string size at gamefixes panel hasn't been done yet (I don't care about it, just mentioning about it as you had assigned @refractionpcsx2 for the task of shortening it). Other than that one, I think we're fine.

**Comment by refractionpcsx2** [comment]
I didn't realise I was assigned that task.

**Comment by gregory38** [comment]
Forget about it. It isn't a solution. Some languages are quite verbose. The real solution will be to redo some GUI parts. The GUI better fit smaller screen but 1024x768 is just to small. The situation is barely better for others Wx768. But it is too late to change the 1.6 GUI.

**Comment by turtleli** [comment]
I think it's fine to close the issue.
