### ISSUE TITLE
World Rally Championship Graphics Issues (NTSC-U)

### ISSUE THREAD

**Issue by Catarax** [PCSX2/pcsx2#1624]
**Latest dev build - windows - OpenGL/DX11**

**Actually, the PAL WRC 1 release doesn't require any particular GSDX hacks to run without graphics issues.**
![pal](https://cloud.githubusercontent.com/assets/3964507/19399703/1da261a2-9253-11e6-9311-3bfc541eaafe.png)

**The NTSC release is completely broken for the car and some random 3D forms can popup :**

![ntsc](https://cloud.githubusercontent.com/assets/3964507/19399719/33064eaa-9253-11e6-8f50-fd3af57e9f6c.png)
![ntsc2](https://cloud.githubusercontent.com/assets/3964507/19399762/5f4ae994-9253-11e6-9e4a-34fd38485a09.png)

**Fix found:**
**GKickHack** reduces a part of the annoying graphics issues (map cleaned in-game) but the car remains glitchy.

I was looking to push it as a GameDB fix but since the PAL version doesn't require that, I doubt this is really necesarry yet.

**Comment by refractionpcsx2** [comment]
has it always been like this? has this happened recently? does it work with an older GSDX but a newer PCSX2.exe? We need a bit more info.

**Comment by Catarax** [comment]
PCSX2 1.4 => same bug and forgot to mention it was also in Software Mode too.

**Comment by refractionpcsx2** [comment]
ok, wel ill take this appropriately because it's unlikely to be a GSDX bug.

**Comment by FlatOutPS2** [comment]
I think I've seen this issue before. It might've been a speedhacks or corrupted ISO issue.

**Comment by Catarax** [comment]
The md5 of the iso is the same as the redump database, no corruption then?

**Comment by FlatOutPS2** [comment]
Try the disc to be sure and also turn all speedhacks off.

**Comment by Catarax** [comment]
Okay, still the same thing even with speedhacks off.

**Comment by FlatOutPS2** [comment]
And you weren't using any other non-default settings? 
Can you please post the contents of the emulog.txt file from the "PCSX2\logs" folder after the problem occurs.

**Comment by MrCK1** [comment]
@refractionpcsx2 Here's a log for you, the game has a VIF Unpack issue. Speedhacks, ect. don't affect the issue either.

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/1334846/emuLog.txt)

**Comment by kozarovv** [comment]
Delay problematic XGKicks by rearranging VU code, fix SPS on cars. Require XGKICK Hack to be manually enabled. 

CRC=5838e074

> patch=1,EE,0020efa0,word,8000033c
> patch=1,EE,0020efd8,word,80004efc
> patch=1,EE,0020f040,word,8000033c
> patch=1,EE,0020f0b0,word,80004efc
> patch=1,EE,0020f118,word,8000033c
> patch=1,EE,0020f188,word,80004efc

Console will still spam "VIF fill guessing" if dev logging is enabled.

**Comment by refractionpcsx2** [comment]
Nice work :) I'll add that to the gamedb (since it's unlikely to be fixed properly any time soon

**Comment by refractionpcsx2** [comment]
Closing this as the game now works in master without patches.
