### ISSUE TITLE
Haunting Ground CRC hack issue.

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1627]
I notice that with GL+auto flush hack+no CRC, character shadows seem to work correctly. I was wondering whether the relevant hack that removes shadows could be removed or made DX-only. If I was able to build PCSX2 myself, I'd use trial and error to figure out which hack is responsible. I'm assuming that it's a specific hack, and not a side effect of the bloom removal.

```
bool GSC_HauntingGround(const GSFrameInfo& fi, int& skip)
{
	if(skip == 0)
	{
		if(fi.TME && fi.FPSM == fi.TPSM && fi.TPSM == PSM_PSMCT16S && fi.FBMSK == 0x03FFF)
		{
			if (Dx_only)
				skip = 1;
			else
				return false;
		}
		else if(fi.TME && fi.FBP == 0x3000 && fi.TBP0 == 0x3380)
		{
			skip = 1; // bloom
		}
		else if(fi.TME && (fi.FBP ==0x2200) && (fi.TBP0 ==0x3a80) && fi.FPSM == fi.TPSM && fi.TPSM == PSM_PSMCT32)
		{
			skip = 1;
		}
		else if(fi.FBP ==0x2200 && fi.TBP0==0x3000 && fi.TPSM == PSM_PSMT8H && fi.FBMSK == 0)
		{
			skip = 1;
		}
		else if(fi.TME)
		{
			// depth textures (bully, mgs3s1 intro, Front Mission 5)
			if( (fi.TPSM == PSM_PSMZ32 || fi.TPSM == PSM_PSMZ24 || fi.TPSM == PSM_PSMZ16 || fi.TPSM == PSM_PSMZ16S) ||
				// General, often problematic post processing
				(GSUtil::HasSharedBits(fi.FBP, fi.FPSM, fi.TBP0, fi.TPSM)) )
			{
				skip = 1;
			}
		}
	}

	return true;
}
```

**Comment by gregory38** [comment]
Are shadows broken on SW ?

**Comment by gregory38** [comment]
Actually I meant "used to be broken" (check 1.4) as auto flush is now always on SW renderer.

**Comment by gregory38** [comment]
And to answer your original quesiton. Autoflush is only enabled when fi.FBP equals fi.TBP0 and fi.TME is enabled. So it is likley this part
```
        else if(fi.TME)
        {
            // depth textures (bully, mgs3s1 intro, Front Mission 5)
            if( (fi.TPSM == PSM_PSMZ32 || fi.TPSM == PSM_PSMZ24 || fi.TPSM == PSM_PSMZ16 || fi.TPSM == PSM_PSMZ16S) ||
                // General, often problematic post processing
                (GSUtil::HasSharedBits(fi.FBP, fi.FPSM, fi.TBP0, fi.TPSM)) )
            {
                skip = 1;
            }
        }
```
But it is hard to be sure without a real test. Rendering is often complex

**Comment by gregory38** [comment]
I pushed a better fix for the bloom effect on the git. Maybe minimal is enough for the game.

**Comment by gregory38** [comment]
I moved all the hack to the dx level. With latest fix, game seems to work quite well (still got minor issue). Therefore I'm closing this issue.

**Comment by AmbientMalice** [comment]
Thanks.
