### ISSUE TITLE
Stuart Little Big Photo Adventure (NTSC)

### ISSUE THREAD

**Issue by zster2** [PCSX2/pcsx2#163]
Eventually had time to find out which version broke this. It was working perfectly in 5366 and stopped in 5368 (there was no 5367 build). I've tested on multiple pc's so this is not a hardware issue. The comment against 5368 was "VIF: Some optimizations for the VIF Rec, some small clean-up/optimizations for VIF itself.". Game still works with EE timimg hack but there is quite a bit of graphic corruption. I'd imagine this is not a high priority game and I can always use an old version just pointing out compatibility went down so there may be something wrong there. Its still broken with the latest buid as at 22 July 2014

**Comment by refractionpcsx2** [comment]
well this seems to work fine these days. The loading screens are a little messy in OGL mode (not tried DX), software seems fine, at least mostly lol, could still be a core bug, but its minor, the game looks perfect and doesn't crash.
