### ISSUE TITLE
Ubuntu 16.04 can't install pcsx2-unstable from PPA

### ISSUE THREAD

**Issue by whereswaldon** [PCSX2/pcsx2#1631]
**_Description of the issue:**_
`sudo apt install pcsx2-unstable` fails with the following error:

```
$ sudo apt install pcsx2-unstable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pcsx2-unstable:i386 : Depends: libsoundtouch0:i386 (>= 1.8.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**_How to reproduce the issue:**_
I'm running Ubuntu 16.04. I've been able to install pcsx2 fine, it's just the unstable package that isn't installable. I've enabled the i386 architecture and the multiverse PPAs to no avail. I'm having a blast with the stable version, so this isn't a huge deal. I just wanted to make sure that this was documented/known.

**_Last known version to work:**_
1.4.0 installs fine.

**_PC specifications:**_
CPU: Intel® Core™ i7-6700K CPU @ 4.00GHz × 8
GPU: GeForce GTX 960/PCIe/SSE2
OS: Ubuntu 16.04, 64 bit

**Comment by gregory38** [comment]
Well I need to update the unstable PPA with a more recent version.

**Comment by whereswaldon** [comment]
Thanks for a quick reply. I now feel like an idiot because I can see that the unstable version is 1.3.1. Sigh. I'd assumed and well... we all know where that leads. Anyway, if/when you find time to update it, let me know. Thanks!

**Comment by tiagoplacido** [comment]
there's a ppa with daily builds if your interested https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by gregory38** [comment]
I updated the unstable version to latest 1.5. I don't know if it will work.

**Comment by whereswaldon** [comment]
It does install now, thank you. Also, thanks for the link to the daily builds. It might be worth adding that link to the install page in the Wiki. If you could submit PRs to wikis I would do it myself, but I don't think that's possible.

**Comment by gregory38** [comment]
Which wiki ? Github? Normally you have right to submit pr.

**Comment by whereswaldon** [comment]
Yes, the Github wiki. It isn't part of the repository contents, so I can't (or don't know how to) submit a PR to change it. It's not the same as trying to change code. As far as I know, you have to be a collaborator to alter a project's wiki. If I'm wrong, I would be happy to be corrected about this. I've been wishing that you could do this for a long time.

**Comment by gregory38** [comment]
Did you try it ? I didn't enable the option to limit it to user that can push.

**Comment by FlatOutPS2** [comment]
We should really add a link to the GitHub Linux Installation guide on the main PCSX2 site(at the 1.4.0 release download page) and the daily build launchpad site. The only link to a Linux installation guide currently available on the PCSX2 website is a dead link to a googlecode page in the outdated PCSX2 guide.

**Comment by gregory38** [comment]
@bositman we need your help for web stuff.

**Comment by whereswaldon** [comment]
@gregory38 I'm such an idiot. I've never tried to edit a Github wiki because I made bad assumptions about how they worked. I'm sorry for the confusion. I can edit it. I'll try to add the link when I'm next off of a mobile device. Thanks for your patience.

**Comment by bositman** [comment]
Just tell me what needs to be changed where, and I'll take care of it

**Comment by jcdenton2k** [comment]
Just wanted to say tyvm for updating this.  I'll be giving this a go within a month or so to put a dual-boot setup on my main gaming computer and see how that works.  :)

**Comment by MrCK1** [comment]
Honestly, try with Virtual Box instead of a dual boot. After a few installs with OpenSuse (horribly bloated IMO) and BunsenLabs; don't waste your time unless you plan on using Linux as a main OS.

**Comment by FlatOutPS2** [comment]
@bositman The Linux Installation guide( https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux ) should be linked from the PCSX2 webite. Personally, I think it's best placed on the stable release download page:
http://pcsx2.net/download/releases/linux.html

There's an outdated link to a googlecode Linux Compiling page in the v1.2.1 guide, which should probably be changed as well(the dead link is right at the top in the "Linux Users" section).
http://pcsx2.net/config-guide/official-english-pcsx2-configuration-guide.html

I don't know if who's handling the Linux daily build site, but a link on there would be great as well:
https://launchpad.net/%7Epcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by bositman** [comment]
Added the guide to the linux binary download on the website, also updated the configuration guide with the new link.

The daily build has been added some weeks ago, it's under Download->Development->Linux Dev Builds

**Comment by FlatOutPS2** [comment]
> Added the guide to the linux binary download on the website, also updated the configuration guide with the new link. 

Thanks :+1: 

> The daily build has been added some weeks ago, it's under Download->Development->Linux Dev Builds

Yes, I know. I meant adding a link to the Installation Guide on the daily build website.
