### ISSUE TITLE
psxmode: coverity regression

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1632]
You can connect with your github account
https://scan.coverity.com/projects/pcsx2-pcsx2?tab=overview

Here a summary of the issue
- [x] HwWrite.cpp around line 247 => missing break ?
- [x] pgif.cpp line 1125 => memory corruption
  -  overrun-call: Overrunning callee's array of size 256 by passing argument 16777215U in call to iopMemWrite32
- [x] spu2sys.cpp around line 1354
  - assigned_value: Assigning value 524280U to Cores[1].ExtEffectsStartA here, but that stored value is overwritten before it can be used.
- [x] spu2sys.cpp around line 931 => missing break ?
- [ ] Sio.cpp aournd line 857 => always return => chkTriggerInt is mosly dead code

**Comment by sudonim1** [comment]
Yeah there's some actually bad stuff in here, such psx compat quality.

**Comment by sudonim1** [comment]
Okay what is dma6_OTClear even for?

**Comment by ramapcsx2** [comment]
Ordering Table, something GPU related. It appears to be rarely used, if at all. I haven't seen a game trigger the logging yet.

**Comment by FlatOutPS2** [comment]
* [x] spu2sys.cpp line 1352 => clang-format SpacesBeforeTrailingComments set to 2 instead of 1 (`  //` instead of ' //')

:p

**Comment by sudonim1** [comment]
@ramapcsx2 well yes, it's not even referenced anywhere.  It doesn't seem like a likely hardware function in the first place though.

**Comment by MrCK1** [comment]
@ramapcsx2 Zohar's Domain has some good info. DMA Channel 6 is GPU OTC (reverse clear the Ordering Table)

**Comment by ramapcsx2** [comment]
It's definitely in the original hardware so it's ought to be doing something. I just haven't had the time to figure it out.

**Comment by sudonim1** [comment]
Uh really, a dma channel which just clears a table? That sounds bizarre.

**Comment by sudonim1** [comment]
Unless you mean it initialises a table in memory? We have that functionality in psxDma6(), you can probably just delete that function.

**Comment by sudonim1** [comment]
Certainly looks like a bigger buffer's required, but this may mean there are other bad assumptions in that module.

**Comment by gregory38** [comment]
I updated the size of sio buffer from 256 to 512.

**Comment by gregory38** [comment]
@sudonim1 
there is a new regression
find_first_not_of can return invalid value.
```
if ((!g_GameStarted || EmuConfig.HostFs) && 0 == path.compare(0, 4, "host") && path[path.find_first_not_of("0123456789", 4)] == ':')
```

@turtleli there are 2 for cdvd giga.

**Comment by sudonim1** [comment]
Ah, true.  Could just max(0, find_first_not_of).  The whole thing's a bit nasty and honestly I never knew exactly what paths we need to accept, I think host0: and host: are both used, but I guess host1: etc.'s actually unnecessary, I don't see why we would provide that even with different roots.  Unless host00: host000: etc. is equivalent, we could just simplify that.

**Comment by gregory38** [comment]
Do as you wish. But I forbit you to acess a negative element of an array ;)

**Comment by lightningterror** [comment]
Coverity was replaced by codacy, closing this.
