### ISSUE TITLE
Gran Turismo 4: 2 players - garbage on player 2 screen

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1636]
**_PCSX2 version:**_
pcsx2 v1.5.0 dev-1485-g264b764

**_PCSX2 options:**_
EE clamping full , VU clamping extra  (tried default as well)
speedhacks all default + mtvu and fast cdvd (tried without any speedhacks)
Render dx11 hw , opengl hw
Resolutions tested 2x 3x custom , crc tested safest dx11, partial opengl 

**_Plugins used:**_
avx2
everything default

**_Description of the issue:**_
When using dx11 or opengl hw render there is garbage on player 2 screen during the race.The issue appears at random and it depends on the position of player 1 and 2.
Usually a garbage rectangle appears on the top left on the player 2 screen, sometimes the whole player 2 screen flickers with garbage all over the screen. 
-The issue is not present on sw render.

SS of the rectangle garbage
https://i.snag.gy/Q2CaAo.jpg
GS dump 
https://drive.google.com/file/d/0B8cQAq-Ko9-uWjdJYW91dTUzUTQ/view?usp=sharing

SS of player 2 full screen garbage
https://i.snag.gy/DuaonE.jpg

**_How to reproduce the issue:**_
Play on 2 player split screen and race with either player 1 or 2 on hw render in either dx11 hw or opengl hw. Settings don't matter. During the race the rectangle will appear on the top left of the screen depending on the position , full player 2 screen garbage doesn't happen that often. It usually does on the third lap in the race.

**_Last known version to work:**_
none

**_PC specifications:**_
cpu I3 4160 ,gpu AMD R7 360 ,os Windows 7 64bit

**Comment by FlatOutPS2** [comment]
I've reproduced the issue. It reliably appears at several locations on the screen on some(sunny) tracks, before the race when the camera revolves around the car of player 2.

**Comment by lightningterror** [comment]
Hmm , try playing with another person. It's easier to reproduce then. The second ss I posted is on a night track so it doesn't really matter if it's sunny or dark (night).

Perhaps @gregory38 can take a look at it when he's free since he's the gs master xD

Oh and can tags/labels be added?

**Comment by gregory38** [comment]
I'm never free. Anyway, I didn't look at the dump but the likely hypothesis it is this one.
* 1st player is draw at location N
* 2nd player is draw at location N+offset
The HW will use to 2 different frame buffers but the CRTC display will likely expect a single frame buffer.

**Comment by MrCK1** [comment]
Issue still present on latest git as described above.

**Comment by lightningterror** [comment]
I just did a quick test and it is.

**Comment by refractionpcsx2** [comment]
Is this still a problem? can we get a new GS dump of the issue since the old one is no longer there.

**Comment by JordanTheToaster** [comment]
Cannot get it to happen on 1.7.4160 but I might just be lucky/unlucky.

**Comment by lightningterror** [comment]
Issue is resolved, don't know when tho.
Here is the dump for future reference.
[GT4 - 2 player garbage.gs.zip](https://github.com/PCSX2/pcsx2/files/10850896/GT4.-.2.player.garbage.gs.zip)
