### ISSUE TITLE
Making plugins translatable

### ISSUE THREAD

**Issue by TotalCaesar659** [PCSX2/pcsx2#1643]
PCSX2 has only main window for translating, but preferences of plugins (Gsdx etc.) have only English.
Can somebody make them translatable by PO files or something?
I could help with translation.

**Comment by FlatOutPS2** [comment]
Is the language set in PCSX2 currently even available for plugins to read?

**Comment by Drui7** [comment]
And why not make the emulator self-sufficient? Include the best of them in the project code (not in the form of additional binary libraries. But as a code in the executable file itself). And there let them have developed as a function for the entire program, absorb other possibilities (plugin-competitors). And the user will be easier, no need to download any more files, and localization will be available for all settings.
the more that will never be a worthy analogue of this emulator, which would use the same plug-ins.

**Comment by lightningterror** [comment]
> Is the language set in PCSX2 currently even available for plugins to read?

No. I believe the plugins configuration needs to be moved to the pcsx2 window in order for it to work and this will require a lot of work.

**Comment by lightningterror** [comment]
Closing this for the reason stated above.
