### ISSUE TITLE
Final Fantasy XII - GSdx Preload Frame Data HW Hack shadows issue

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1650]
***PCSX2 version:***
Stable build v1.4.0 and development builds v1.5.1537

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
"Preload Frame Data" HW hack causes some shadows to appear stretched and sometime show garbage data in Final Fantasy XII.
This option is needed to fix shadow issues/missing shadows in Hardware mode(the simple oval shadows under characters during gameplay are visible, but full shadows mostly shown during cutscenes aren't).

***How to reproduce the issue:***
Set the Renderer to "OpenGL (Hardware)", enable the "Preload Frame Data" HW hack, start the game, and watch the cutscene of the first boss (big flying machine), a few spikes shortly appear shooting out from its shadow.
Note; Don't turn on the Fast Invalidation HW hack. It makes it look even worse.

***Last known version to work:***
None AFAIK.

GS Dump (rename .pdf to .zip):
[Final Fantasy XII preload frame data texture isses.pdf](https://github.com/PCSX2/pcsx2/files/573847/Final.Fantasy.XII.preload.frame.data.texture.isses.pdf)

**Comment by RedDevilus** [comment]
Seems to be still a problem. Even in the FMV
Normal:
![image](https://user-images.githubusercontent.com/24227051/81484358-25098100-9245-11ea-8ffc-1db9a150c563.png)

Preload Frame Data
![image](https://user-images.githubusercontent.com/24227051/81484273-9694ff80-9244-11ea-9550-680100e528f7.png)

Use of savestates and loading without frame data: (seems to not invalidate old textures)
![image](https://user-images.githubusercontent.com/24227051/81484328-f4294c00-9244-11ea-9a5a-2dc387956dfa.png)
Preload Frame data, load savestates atleast 2 times and it fixes FMV somehow:
![image](https://user-images.githubusercontent.com/24227051/81484389-55e9b600-9245-11ea-89cc-bd51da5e1f2a.png)

**Comment by RedDevilus** [comment]
Re-uploaded it without that weird pdf renaming (still have to check if it's fixed) [Final Fantasy XII preload frame data texture isses_2.zip](https://github.com/PCSX2/pcsx2/files/7873909/Final.Fantasy.XII.preload.frame.data.texture.isses_2.zip)

**Comment by stenzek** [comment]
After 6 years, should be fixed by #7085 :)
