### ISSUE TITLE
Properly sandbox ioman host: hooks

### ISSUE THREAD

**Issue by sudonim1** [PCSX2/pcsx2#1652]
- [ ] Add a host directory setting (default GetDocuments() + "pcsx2_hostfiles"? Using the installation dir / working dir itself as we currently do is very unsafe with write access)
- [ ] Normalise the path after combining with the host directory, removing leading elements until the normalised path is the host directory or a path under the host directory.
- [ ] Refuse to perform any operation on the host directory itself except for dopen (for dread).
- [ ] Log attempts to break the sandbox.
- [ ] Make it clear in the source that symlink, ioctl, ioctl2 and devctl should absolutely not be implemented under any circumstances.

**Comment by gregory38** [comment]
If it is related to the "host elf" feature, you can add use C++ string rather than unsafe C functions.

**Comment by sudonim1** [comment]
I didn't add that because I already did that in my local branch.

**Comment by ramapcsx2** [comment]
`default GetDocuments() + "pcsx2_hostdevice" `<< a bit more like it, imo.
Otherwise this sounds like the thing to do.

**Comment by sudonim1** [comment]
Hmm, how should we handle loading elfs from outside of the host root? They're loaded through the normal EE ELF loader in the BIOS but with a host: path

**Comment by sudonim1** [comment]
Hmm maybe instead of using host: for that we should use a magic string like "hostelf:" which opens the specified elf regardless of its location on the host.

**Comment by uyjulian** [comment]
I feel like implementing the host: functionality as a plugin (for example a plugin that plugs into dev9 and emulates ps2client) is much cleaner.

Load the elf, then right after loading the elf, turn off the host: functionality.

**Comment by sudonim1** [comment]
@uyjulian no.

**Comment by sudonim1** [comment]
@uyjulian to be clear, we can probably hook iomanx just fine too if that's your concern.  If you're using ioman in your homebrew, it'll work, the intent is to be binary compatible and we don't mess with calls that aren't for our host:

Implementing the host filesystem as a block device over a poorly understood bus is about the least sane option possible.

**Comment by ramapcsx2** [comment]
We could continue to read from the external location where the elf is located (to read other files that may have been put there), but not write to that location. Only write to the new, safe host root.

**Comment by sudonim1** [comment]
That's sounding terrible, I'll do the special hostelf: device :P
