### ISSUE TITLE
PSI-Ops GSdx HW green layer covers objects

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1657]
***PCSX2 version:***
Development build v1.5.1581

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
In OGL HW a green layer covers 3D objects that are close to the camera.

In D3D11 HW the complete screen(except for the HUD) is cover in purple and the game runs really slow.
In D3D9 HW the bottom half of the screen is green and a green layers covers 3D objects like OGL HW and the game runs really slow.

Setting skipdraw to 1 removes the green/purple layer and the slowdown in D3D, but the game looks blurry. Setting it to 5 removes the blur but skipdraw obviously removes many of the other effects.

***How to reproduce the issue:***
Start a mission and make sure there's an object relatively closer to the camera..

***Last known version to work:***
None. OGL HW is completely green in HW with what looks like some top left corner artifact in v1.4.0.

***GSDump(rename .pdf to .zip):***
[PSI-Ops - objects are green close to camera.pdf](https://github.com/PCSX2/pcsx2/files/586224/PSI-Ops.-.objects.are.green.close.to.camera.pdf)

--
Off-topic note: Something seems wrong with the resume/restart behaviour in the latest git builds. When I restarted a game running from disc it suddenly booted to the BIOS. And when I resumed another disc game it gave an ISO error as it had apparently switched to thinking it was running from ISO. :/

**Comment by refractionpcsx2** [comment]
Have you tried ultra blending etc?

**Comment by FlatOutPS2** [comment]
> Have you tried ultra blending etc?

Yes, but I didn't try the kitchen sink.

**Comment by gregory38** [comment]
based on the description it is either a channel effect or a color shuffle effect (potentially linked to a texture cache bug)

**Comment by lightningterror** [comment]
Direct3D11 and OpenGL look identical now.

**Comment by dskaiser82** [comment]
I watched this video and he shared his specs.  This fixed it for me.
I think it was this:
(✓) Enable HW Hacks: Skipdraw 3

https://www.youtube.com/watch?v=Qe3mn22sDNE&t=674s
PCSX2 Settings:
Renderer: OpenGL (Hardware)
Interlacing (F5): Auto
Texture Filtering: Bilinear (PS2)
Internal Resolution: 8x Native
Anisotropic Filtering: 16x
Mipmapping: Basic (Fast)
CRC Hack Level: Automatic (Default)
_____________________________________________
(✓) Enable HW Hacks: Skipdraw 3
_____________________________________________
Requested by: King MoDzZ
_____________________________________________
My PC Specs:
CPU: Intel Core i7-4790K
GPU: GeForce GTX 1070
Ram: 12GB
OS: Microsoft Windows 7 Ultimate

**Comment by MrCK1** [comment]
> I watched this video and he shared his specs. This fixed it for me.
> (✓) Enable HW Hacks: Skipdraw 3

Unfortunately that doesn't actually fix the issue, it's just a workaround. This will remain open until the issue is fixed properly.

**Comment by seta-san** [comment]
i'm not seeing any of these green or purple issues. can someone confirm that this is resolved?  i've looked at ogl, d3d11, and vulkan all with basic blending and no skip draw

**Comment by seta-san** [comment]
or blurriness for that matter.

**Comment by dskaiser82** [comment]
It was a setting change....this video shows the issues but another video
showed me the setting to switch....So I solved the issue on my end.
Psi-Ops pcsx2 r5350, green Z-plane Problem - YouTube
<https://www.youtube.com/watch?v=86DXOrRtB00>

**Comment by seta-san** [comment]
okay. i still get the double image but only in d3d11..  all other renderers are fine.

**Comment by lightningterror** [comment]
All hw renderers are still broken, it's not resolved.

**Comment by seta-san** [comment]
Don’t know what to say. So far for me the game looks great other than the double image in d3d11

**Comment by seta-san** [comment]
comparing videos with dskaiser82..
https://www.youtube.com/watch?v=qYBFD-FQ04U

**Comment by lightningterror** [comment]
You can test the gsdump that is attached to the OP.

**Comment by seta-san** [comment]
honestly, i can't run the gsdump without it crashing on an assert error. because of that i can't really account for whatever possible differences between the gs debugger and actual game play. all i can say is that i'm absolutely not seeing what is being said is there. is it possible that it has a bad gs dump? or that older gs dumps didn't dump all the information that modern ones might?

**Comment by seta-san** [comment]
okay i did some looking back at builds..
it's
https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2282
1.7.2282 fixed this particular bug.

there are still 2 bugs i can see so far. first is the double image and second is that the game locks up for a bit with vertical bars before eventually coming back.

**Comment by seta-san** [comment]
fun story. you can make the problem come back by disabling depth emulation.
