### ISSUE TITLE
Reign of Fire - game freezes (GIF FIFO)

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1658]
***PCSX2 version:***
Development build v1.5.1581

***PCSX2 options:***
Default -> GIF FIFO

***Plugins used:***
DEFAULT

***Description of the issue:***
Game freezes/gets stuck in-game without the GIF FIFO game fix. With the GIF FIFO game fix it freezes shortly after. If you turn the fix off again before this second freeze it goes slightly further until it eventually freezes again. If you turn the fix back on before this you'll get further still and you'll need to keep repeating this process forever to keep playing. Once it freezes, toggling the fix won't help, so you need to know when to switch. This is doable during cutscenes, but almost impossible during gameplay. So the game isn't very playable. :p

***How to reproduce the issue:***
Just start the game.

***Last known version to work:***
Never worked AFAIK.

**Comment by FlatOutPS2** [comment]
Yes, it definitely is an improvement, it's actually very close to being fully playable. The short while I did get to play it, it seemed free of other issues.

**Comment by refractionpcsx2** [comment]
Nice!  Good to see there's another game which makes use of it

**Comment by refractionpcsx2** [comment]
Just to note, you no longer require GIF FIFO either, I think that just somehow poked the VIF when it had stopped :)
