### ISSUE TITLE
Jak 3 [PAL] really slow during catacomb levels.

### ISSUE THREAD

**Issue by Hirato** [PCSX2/pcsx2#1667]
***PCSX2 version:***
1.5.0.r4127.30a5922

***PCSX2 options:***
Clamping, gamefixes, etc are all default, all the safe speedhacks are enabled, and the GsDX CRC hacks are at the recommended OpenGL level.

***Plugins used:***
Using GsDX with 4x native, with partial CRC hacks and high blending unit accuracy.
Mipmapping is also on full at the trilinear filtering level; changing these options don't speed it up noticeably.

***Description of the issue:***
The game appears to trigger a bottleneck in GsDX, the software renderer can barely push 8 FPS, and the hardware renderer struggles even more. 
It seems to make very heavy use of mipmapping during these levels, so that might be related.

***How to reproduce the issue:***
Reach one of the levels where you race through the catacombs in Jak3, the first one is at approximately 33% completion.

GS dump here: https://my.mixtape.moe/vuxwpr.tar.xz (md5: 584afb598e46b2b91b91ad7745f03bbf)
The dump was taken with 1.5.0.r3869.fc32b74, but is still an issue in 1.5.0.r4127.30a5922

***Last known version to work:***
It works, it's just really slow.

***PC specifications:***
OS: x64 Arch Linux (last update Nov 2nd)
CPU: AMD FX8320
GPU: NVIDIA 770GTX (driver: 370.28)

**Comment by willkuer** [comment]
What are EE% and GS% during slowdowns?

Why do you think that mipmapping is the issue if changing the mipmapping level barely changes the output speed?

**Comment by Hirato** [comment]
@willkuer 
EE is about 18% or so, the GS is at 99% in HW mode.
I suspect mipmapping is related more due to intense data transfer to the GPU than anything to do with PCSX2's mipmapping implementation itself.
I'm not sure how much that GS dump covers I uploaded cover, I think it's only a few frames and its size is well over 50 MB.

**Comment by gregory38** [comment]
Could be the shadow. Did you test the speed on 1.4 ?

**Comment by Hirato** [comment]
I didn't test on 1.4.

I just rolled back to an earlier build I had that identifies itself as 1.3.1.r2407.60426a5 and it's just as slow there.
On a side note, it does render about 3x as fast at the 'None' blending unit accuracy level (I tend to use High as that's the OpenGL recommendation)

**Comment by FlatOutPS2** [comment]
Can you share a save file(memory card file) from near or at the catacombs?

**Comment by Hirato** [comment]
@FlatOutPS2 here you go https://my.mixtape.moe/ceszbb.tar.xz

**Comment by FlatOutPS2** [comment]
@Hirato Thanks 👍 

I can confirm the issue. I managed to make it playable on Software mode with the EE an VU sliders on the speedhacks tab, but Hardware mode takes extreme measure(very high skipdraw and max EE & VU sliders) to get decent framerates, but the speedhacks also cause false FPS so it doesn't ever feel smooth.

Skipdraw managed to remove the shadows, but that doesn't seem like the core issue here. Might be lighting related judging by the looks of the level.

**Comment by FerrazaDazzle** [comment]
I can confirm that OpenGL has a faster framerate but still laggy. (D3D11- 35FPS avg) (OpenGL- 50FPS avg)

**Comment by gregory38** [comment]
@FlatOutPS2 check the number of draw call in a gpu debugger. I already saw a rendering that miss vsync. So rendering is done serveral times for the same frames.

@FerrazaDazzle config ?

**Comment by FlatOutPS2** [comment]
> @FlatOutPS2 check the number of draw call in a gpu debugger. I already saw a rendering that miss vsync. So rendering is done serveral times for the same frames.

Number of draw calls is often 20000-50000, a significant increase over the aprox. 2000-10000 during the cutscene intro and 2000-7000 during the beginning of the game.

**Comment by FerrazaDazzle** [comment]
@gregory38 
![gs](https://cloud.githubusercontent.com/assets/13339690/20990349/fb7ddf2e-bd23-11e6-823e-2dc155b8d1cf.PNG)
![speedhacks](https://cloud.githubusercontent.com/assets/13339690/20990348/fb7d4e92-bd23-11e6-94c0-2a9d512d3a5d.PNG)

Those are the Speedhacks and GS configs, everything else is default (note, shader boost is on)

**Comment by FerrazaDazzle** [comment]
EE and VU literally make it full speed but way to un-smooth. I usually test builds, compared to the ones from January (2015) to now December (2016), the catacombs have had a SIGNIFICANT speedup, however still not running at full speed. mipmapping is definitely one cause here. 

PC Specs:
i7-5960X
GTX 980Ti
16 GB DDR4
Windows 10 Enterprise

**Comment by Hirato** [comment]
Our setups here aren't a fair comparison at all

In particular, you have the Blending Unit Accuracy option set to Basic, whereas I'm using High.
As I mentioned earlier in this bug, this option has a pretty significant effect on framerate, it increases it anywhere from 3-5 FPS to 15 - while not great it does make the level playable

And we really shouldn't be using the cyclerate speedhacks, they cause too many issues with games.
In this level, it seems to make it skip rendering a bunch of things properly., which in my case nets me a very janky but noticeably faster 40 FPS.

**Comment by willkuer** [comment]
If vu sends less data to the gs the rendering in the gs might be easier. Vu cycle stealing thus can help although the vu is not bottlenecked.

**Comment by FerrazaDazzle** [comment]
@Hirato i tried high and i totally agree with your comparison and at the opening scene when starting game, there are MORE corrupted textures on High than basic... And I do not use cycle rate speed hacks. its something to do with the way the game engine is handled probs, all games that use the same engine have same problems... any insight on the root of this cause?

**Comment by MrCK1** [comment]
Is there any point keeping this open? The issue seems to be more related to the user's system and their GSdx configuration rather than being an actual issue.

**Comment by SpiffyJUNIOR** [comment]
> Is there any point keeping this open? The issue seems to be more related to the user's system and their GSdx configuration rather than being an actual issue.
It's pretty clear this isn't a hardware issue.

**Comment by lightningterror** [comment]
Can this be retested? Recent opengl changes may give an improvement.

**Comment by Hirato** [comment]
I tried it again around the time Allesandro's palette management changes
were merged, but they didn't really have much of an effect during this
level.

Would love to give it another try with
f4090798644c1d21238e2c6603789b3176ad6a39 present, but at the moment I can't
build due to GCC 9.1 being broken.

**Comment by AlessandroVetere** [comment]
New palette management gives the real boost with 8-bit texture enabled, did you try setting the plugin that way?
The new SW render will give a consistent boost, in any case.

**Comment by Hirato** [comment]
The last one I've built identifies itself as 1.5.0-dev-3121-g079baaed9, which should correspond to this commit 079baaed9913d4c993500c43b323107b1de7438c 
I can't build a new one because of the GCC ICE issue, that will have to get fixed first.

HW mode (about 5 FPS)
![Screenshot_20190716_213435](https://user-images.githubusercontent.com/881518/61299102-0c416200-a812-11e9-931b-cfc3bf49c330.png)

SW Mode (13-14 FPS) - this result may be as well be due to the fact that I have a beasty threadripper 1950x now though...
![Screenshot_20190716_213906](https://user-images.githubusercontent.com/881518/61299184-32670200-a812-11e9-94cc-a1f9c4d4c8ab.png)

Options
![Screenshot_20190716_214211](https://user-images.githubusercontent.com/881518/61299405-9689c600-a812-11e9-8a47-3608f7960950.png)

I don't recall Auto Flush being there before, but with it disabled the level runs at about 23 FPS in software mode.
User Hacks is being used solely for trilinear filtering.


I'll leave an update with a much newer build once I can actually build one again.

**Comment by lightningterror** [comment]
Maybe lower blending to basic level?

**Comment by gregory38** [comment]
Test no blending. And no crc too.

**Comment by Hirato** [comment]
Is there really much point without getting a newer build first.

I'm assuming you only want me to check HW mode for those:
Basic Blending: 18-21
No Blending: 18-22
No blending + no CRC: 18-23

**Comment by bositman** [comment]
Also try AA to 0.

**Comment by Hirato** [comment]
That took a lot longer than I hoped it would...
GCC 9.2 just landed in arch, and with it, it seems I can build PCSX2 again (hooray~!)
So I have just built against revision 6b8763ba
The colours and stuff are WAY better though; jak's rendered correctly, less black corrupted textures, etc.

HW Mode: 8b textures enabled too
1x Native, 16xAA, Full Mipmap w/ Trilinear, Partial CRC, Full DATE, High Blending
5.75 FPS

1x Native, 1xAA, Full Mipmap w/ Trilinear, Partial CRC, Full DATE, High Blending
5.80 FPS - Aniso is so cheap, that I really don't expect it to change performance when its this low

1x Native, 16xAA, Full Mipmap w/ Trilinear, Partial CRC, Full DATE, Basic Blending
20-26

1x Native, 16xAA, Full Mipmap w/ Trilinear, Partial CRC, Full DATE, No Blending
21.5-24 - this is better

1x Native, 16xAA, Full Mipmap w/ Trilinear, Partial CRC, no DATE, No Blending
21-26 FPS

1x Native, 16xAA, Full Mipmap w/ Trilinear, No CRC, No DATE, No Blending
21-25 FPS

1x Native, 1xAA, Full Mipmap w/ Trilinear, No CRC, No DATE, No Blending
20-26 FPS (just so show that aniso is largely inconsequential here)

1x Native, 16xAA, Full Mipmap w/ Trilinear, No CRC, No DATE, No Blending
8b textures disabled this time...
23-29 FPS

SW: 8 extra threads
Edge AA + MipMap, no auto flush
15-20 FPS

MipMap, no edge AA + no auto flush
16-21 FPS

No Mipmap, no edge AA, no auto-flush
17-22

Any other settings worth checking?

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest master? Hopefully #5580 will improve auto flush performance for you.

**Comment by Hirato** [comment]
lightningterror's blending changes likely had more of an impact, since it's less about auto-flush and more about blending performance due to an extreme number of draw calls.

I'll give you some measurements at 4a634ca154b07faf59625ba698846fb94800f4ea,
it's kind of a pain to try branches with Arch's pkgbuild system.

OpenGL Hardware mode
4x Native w/ Basic Blending
w/o AF: 27-38 FPS 7516 6000-8000 DC/frame
with AF: 22-34FPS 6234-8375 DC/frame

4x Native w/ Medium Blending
w/o AF: 33-36 FPS 6000-8000 DC/frame
with AF: 24-31 F{S 6353-8478 DC/frame

4x Native w/ High Blending
w/o AF: 5-8 FPS 46500-55809 DC/frame
with AF: 4-7 FPS 39898 - 60147DC/frame

with Vulkan, the framerates are slightly worse, and it makes my entire system chug, and not just the game.

SW mode at the same revision, and 7 extra threads.
w/o AF: 29-41 FPS
with AF:24-34 FPS

a fresh GS Dump if you need it: https://filedn.com/lKkh864JfCPXI8IKXeYX5O5/JAK%203%20-%20catacombs%20gs_20220306090748.gs.xz

Hardware wise, I currently have a threadripper 1950x and an RX 580.
The framerate certainly is high enough to be playable on basic/medium blending and SW mode (PAL/50HZ), irrespective of auto-flush settings.

So I suppose the question is, is High still the recommended blending level for OpenGL?
I do notice the GS config has been dumbed down a fair bit, and has lost all the tooltips (which contained different recs for D3D and OpenGL).

**Comment by RedDevilus** [comment]
Basic blending has always been the recommended blending level. That's especially true if you have performance issues. 
![image](https://user-images.githubusercontent.com/24227051/156905621-0673342a-26b3-416d-8db7-bfeae64b9228.png)

If you run Windows with an AMD GPU like that RX 580 that's just leaving a lot of performance on the table. 
Either use Vulkan (for performance and better blending than DX11)
Or use Direct 3D11

**Comment by refractionpcsx2** [comment]
That's pretty much in line with what I expect on master, can you try on my PR?

**Comment by Hirato** [comment]
Sorry mate, I tried via the AppImage on the PR and that was a complete bust.
And it was really painful because it insists on using a portable configuration and not the stock config/cache folders, so I had to reconfigure everything to match.
And once that was done, it just blows up:
```
eglGetDisplay() failed 12288
Failed to crate any GL context
Failed to acquire host display
GS failed to open```

**Comment by refractionpcsx2** [comment]
dunno what's happening there, anyway it's in master now, so if you can get 1.7.2415, that has the fixes in

**Comment by Hirato** [comment]
as of fa78e1295ace393583e4daef5ebac404c8e43b4c


All without Autoflush:
OpenGL w/ basic blending 26-37 FPS
OpenGL w/ medium blending 26-37 FPS
OpenGL w/ high blending 6-7 FPS
Software: 32-42 FPS

All with Autoflush:
OpenGL w/ basic blending 23-37 FPS
OpenGL w/ medium blending 24-37 FPS
OpenGL w/ high blending 5-7 FPS
Software: 29-37

Not exactly very scientific measurements, I should probably be using gallium hud for it,
but that commit does seem to have reduced the variance between having it enabled or disabled a fair bit.

**Comment by refractionpcsx2** [comment]
8 render threads probably isn't helping you here, I can get 45fps in SW mode with 3 extra threads, I can't break 40fps with 8, so it could be worth you dropping that for software mode (3-4 is generally most optimal anyway)

For Hardware Vulkan with basic blending I get
Autoflush off: 53fps
Autoflush on: 45fps

On OpenGL I get 50fps regardless of Autoflush

I am on a 2080Ti mind. but yes this seems to be a very heavy scene.

**Comment by Hirato** [comment]
I do have a 16 core CPU so I was trying to make the best of it 🙂

3 extra threads do perform slightly better about 3 FPS in both scenarios.
Either way the performance is much improved since my last update from 2019.



With autoflush you may want to whip out your jetboard; while I'm in the
strip mine (the lever just after) raw uncapped HW performance is 88 FPS but
it drops to 25 when I pull out the jetboard and hover about on the ground.
It's out of scope for this ticket, but you may want to note it in the
master ticket for autoflush perf issues.

**Comment by lightningterror** [comment]
Might be even better on latest master, but aside from that not much can be done, in time we might find ways that improve performance further, but other than that that's pretty much it.
