### ISSUE TITLE
OGL/DX11: Certain games have corrupted mipmap textures with specific settings

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1668]
***PCSX2 version:***
PCSX2 1.5.0-20161119215208 - compiled on Nov 19 2016

***PCSX2 options:***
Safest preset

***Plugins used:***
All default plugins

GSDX - OGL HW/SW and DX11 HW 

***Description of the issue:***

- When certain settings are used, distant textures will become corrupted. **See steps to reproduce for the specific settings**.

- Based on my testing, _**this only affects games that take advantage of both the Half and Full Mipmap levels.**_

- OGL HW/SW and DX11 HW are affected. At the time of this writing, DX11 SW didn't appear to have this issue.

**Games tested/affected:** 
Formula One 2001, Smuggler's Run, Harry Potter and the Order of the Phoenix, Nascar 09

GSDump for Formula One: [formulaone2001_tcorrupttextures.zip](https://github.com/PCSX2/pcsx2/files/601913/formulaone2001_tcorrupttextures.zip)

**Unaffected Games:**
MGS3, R&C2, ATV Offroad Fury

(Note: In Formula One 2001: the black line at the top is an unrelated issue with render targets due to the 
in-game mirrors on the car)![gsdx_20161120021317](https://cloud.githubusercontent.com/assets/16314399/20461292/37d1732a-aec7-11e6-8436-019ec55c4dea.png)
![gsdx_20161120022913](https://cloud.githubusercontent.com/assets/16314399/20461347/2bfe5a0c-aec9-11e6-87d1-c4f936cec482.png)

***How to reproduce the issue:***
OGL Renderer: Disable "Allow 8-Bit textures, select Mipmap (Full) and Trilinear Filtering (Ultra)

DX11 HW Renderer: select Mipmap (Full)

***Last known version to work:***
Unknown

***PC specifications:***
Intel i5-6600K, Nvidia GTX 970. Windows 10 64-bit

**Comment by FlatOutPS2** [comment]
Is the issue in Nascar 09 the texture corruption on the car(s)? That seems to be solely related to texture filtering, because that already happened with older PCSX2 revisions when using `Bilinear (Forced)`(but also affects `Trilinear (Forced)` & `Trilinear (Ultra/Slow)` in newer revisions).

**Comment by MrCK1** [comment]
@FlatOutPS2 in NASCAR 09 Yes. IIRC the settings required to reproduce the issue in other games is not always the same as listed above

**Comment by FlatOutPS2** [comment]
> I don't know how recently the issue popped up in the other games however

Probably ever since mipmapping/trilinear TF were added.

I managed to reproduce the issue in Formula One 2001 with the options you mentioned for the OGL HW renderer, but it doesn't seem to affect SW mode at all. Direct3D11 HW doesn't seem to be affected either(probably because the issue only appears when using `Trilinear (Ultra/Slow)` which is not available for the D3D renderers).

**Comment by MrCK1** [comment]
@FlatOutPS2 The issue with ```Bilinear (Forced)``` is still present on latest git. This car's textures were corrupted upon loading a track.

![gsdx_20161212205040](https://cloud.githubusercontent.com/assets/16314399/21124380/a867e3c0-c0ac-11e6-8045-539ec5ccda64.png)

**Comment by FlatOutPS2** [comment]
I didn't say it wasn't present anymore, just that it also affected the new Trilinear Forced and Ultra options. ;)

The screenshot looks particularly bad, does it affect the scaling of the car body/wheels too?

**Comment by MrCK1** [comment]
I'll check again, the screenshot was taken in 16:9 widescreen at 4x native

**Comment by MrCK1** [comment]
Haven't been able to reproduce the issues ebin Formula One or Smuggler's Run. I don't think it's a problem anymore (and Nascar has its own issues) 

I'll reopen this if I notice anything else.
