### ISSUE TITLE
Regression: Fatal Frame 3 - texture/graphic glitches

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1674]
Last known working build v1.5.0-dev-1581-g1530eff
Regression build: v1.5.0-dev-1582-g49d5c42
All builds after 1582 have the same problem

Default speedhack + mtvu
crc full safest 3x native res
(these settings don't matter since I tested it without them as the issue is still present)

default plugins
***Description of the issue:***
Textures are glitchy , seen through walls , incorrectly rendered

***How to reproduce the issue:***
This issue can be reproduced by opening doors on certain parts and not walking towards the next room.
Example: on the first level from the beginning take the right and open the door but don't go through it , you will see the texture glitches , after that go back and you can see other textures are glitching through walls , some objects can be seen through walls as well.
The issue is present on opengl hw and dx hw mode. Software mode is fine.

Screenshots of glitches
![gsdx_20161124194649](https://cloud.githubusercontent.com/assets/18107717/20608639/e8b07f64-b283-11e6-9993-a2302789cea5.jpg)
![gsdx_20161124194733](https://cloud.githubusercontent.com/assets/18107717/20608640/e8b29736-b283-11e6-9ce7-e959652ef79b.jpg)
![gsdx_20161124194801](https://cloud.githubusercontent.com/assets/18107717/20608641/e8b40d78-b283-11e6-8147-d7732d0d9c57.jpg)

How it should look
![gsdx_20161124195624](https://cloud.githubusercontent.com/assets/18107717/20608585/6af66084-b283-11e6-938c-277a705fb334.png)

GS dumps
https://drive.google.com/open?id=0B8cQAq-Ko9-uSk5iaTBLdVdMRmc

***Last known version to work:***
v1.5.0-dev-1581-g1530eff

***PC specifications:***
i3 4160 , 16gb ram , r7 360 windows 7 64bit

**Comment by gregory38** [comment]
For the record, GSdump doesn't depends on the GS version.

**Comment by lightningterror** [comment]
@gregory38 I included from both 1581 and 1582 for comparison (non buggy and buggy version).
Thought it might help :)

**Comment by gregory38** [comment]
GS dump record the input of the gs plugin. Input doesn't depends on the plugin version (neither on the config). Anyway, I'm on it.

**Comment by gregory38** [comment]
@lightningterror 
Please test again latest git.

**Comment by lightningterror** [comment]
@gregory38 It is fixed now.

**Comment by FlatOutPS2** [comment]
I'll go ahead and close this then. :)
