### ISSUE TITLE
'Illegal Instruction' on configuration due to processor features

### ISSUE THREAD

**Issue by gamax92** [PCSX2/pcsx2#1677]
***PCSX2 version:***
``1.5.0~git201611251609 (from PPA)``

***Description of the issue:***
Plugin enumeration on configuration screen causes crash in libGSdx-AVX2.so due to not supporting AVX2. Instead of crashing the emulator should not list this plugin since it's not usable on this machine.

For that matter it also lists GSdx SSE4 which is also not supported here, but this doesn't crash the configuration screen, only when attempting to configure the plugin.

***How to reproduce the issue:***
Have a processor that doesn't support AVX2 and no configs, as soon as one clicks Next the emulator crashes in libGSdx-AVX2.so

***Last known version to work:***
(Unsure, sorry.)

***PC specifications:***
Processor that doesn't support AVX2. I know my processor sounds old given the lack of features but the games I run do at least run full speed.

**Comment by gregory38** [comment]
I will need a trace, my CPU support AVX2 so I can't reproduce it easily (I need to try with Valgrind). I'm afraid that GCC will use AVX2 instruction everywhere so any static code in the library will crash.

**Comment by gregory38** [comment]
Initially, I was afraid that code uses the faster BMI2 shift operation. However, I'm not sure the optimization is enabled (I didn't set -mbmi2).

**Comment by gregory38** [comment]
For my record, I can disable some optimization on global init.
https://gcc.gnu.org/onlinedocs/gcc/Function-Specific-Option-Pragmas.html

**Comment by i30817** [comment]
Just opening the plugin chooser dialog is enough after it is configured (I updated after already having it installed). I tried dbg but the ppa strips debugging symbols, maybe someone that can compile can help.

`Thread 1 "PCSX2" received signal SIGILL, Illegal instruction.
0xef576335 in ?? () from /usr/lib/games/PCSX2/libGSdx-AVX2.so
(gdb) bt
#0  0xef576335 in ?? () from /usr/lib/games/PCSX2/libGSdx-AVX2.so
#1  0xef5355fd in ?? () from /usr/lib/games/PCSX2/libGSdx-AVX2.so
#2  0xf7fe8365 in ?? () from /lib/ld-linux.so.2
#3  0xf7fe848e in ?? () from /lib/ld-linux.so.2
#4  0xf7fec75a in ?? () from /lib/ld-linux.so.2
#5  0xf7fe8204 in ?? () from /lib/ld-linux.so.2
#6  0xf7febf02 in ?? () from /lib/ld-linux.so.2
#7  0xf6bd8bf5 in ?? () from /lib/i386-linux-gnu/libdl.so.2
#8  0xf7fe8204 in ?? () from /lib/ld-linux.so.2
#9  0xf6bd930d in ?? () from /lib/i386-linux-gnu/libdl.so.2
#10 0xf6bd8c9e in dlopen () from /lib/i386-linux-gnu/libdl.so.2
#11 0xf7ea6cc1 in wxDynamicLibrary::RawLoad(wxString const&, int) ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#12 0xf7d9bf3c in wxDynamicLibrary::Load(wxString const&, int) ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#13 0x082d2ac8 in ?? ()
#14 0x082d3647 in ?? ()
#15 0x081fe582 in ?? ()
#16 0xf7d5fdef in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#17 0xf7efac95 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
---Type <return> to continue, or q <return> to quit---
`

**Comment by gregory38** [comment]
```
I tried dbg but the ppa strips debugging symbols
```
Normally, symbol are kept in the dbg package. Hum, actually I don't know what do the daily ppa :( I have a special rules for the main ppa
```
override_dh_strip:
      dh_strip --package=pcsx2-unstable --dbg-package=pcsx2-unstable-dbg
```
Too bad. At least it confirms that issue is located in the global constructor of the object.

**Comment by gamax92** [comment]
```
Thread 1 "PCSX2" received signal SIGILL, Illegal instruction.
0xe5c0c7a5 in GSScanlineConstantData::GSScanlineConstantData() () from /usr/lib/games/PCSX2/libGSdx-AVX2.so
(gdb) bt
#0  0xe5c0c7a5 in GSScanlineConstantData::GSScanlineConstantData() () at /usr/lib/games/PCSX2/libGSdx-AVX2.so
#1  0xe5bcb68d in _GLOBAL__sub_I_g_const () at /usr/lib/games/PCSX2/libGSdx-AVX2.so
#2  0xf7fe8485 in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xffffcff4, env=0xa8fd2e8) at dl-init.c:72
#3  0xf7fe85ae in call_init (env=0xa8fd2e8, argv=0xffffcff4, argc=1, l=<optimized out>) at dl-init.c:30
#4  0xf7fe85ae in _dl_init (main_map=main_map@entry=0xac46c00, argc=1, argv=0xffffcff4, env=0xa8fd2e8) at dl-init.c:120
#5  0xf7fec6ea in dl_open_worker (a=<optimized out>) at dl-open.c:575
#6  0xf7fe8331 in _dl_catch_error (objname=objname@entry=0xffffc3c4, errstring=errstring@entry=0xffffc3c8, mallocedp=mallocedp@entry=0xffffc3c3, operate=0xf7fec3c0 <dl_open_worker>, args=0xffffc3cc) at dl-error.c:187
#7  0xf7febf79 in _dl_open (file=0xabeba00 "/usr/lib/games/PCSX2/libGSdx-AVX2.so", mode=-2147483646, caller_dlopen=0xf7e8aca1 <wxDynamicLibrary::RawLoad(wxString const&, int)+193>, nsid=<optimized out>, argc=1, argv=0xffffcff4, env=0xa8fd2e8) at dl-open.c:660
#8  0xf6bacbf5 in dlopen_doit (a=0xffffc580) at dlopen.c:66
#9  0xf7fe8331 in _dl_catch_error (objname=0xa8fd2b4, errstring=0xa8fd2b8, mallocedp=0xa8fd2b0, operate=0xf6bacb80 <dlopen_doit>, args=0xffffc580) at dl-error.c:187
#10 0xf6bad2ed in _dlerror_run (operate=operate@entry=0xf6bacb80 <dlopen_doit>, args=args@entry=0xffffc580) at dlerror.c:163
#11 0xf6bacc9e in __dlopen (file=0xabeba00 "/usr/lib/games/PCSX2/libGSdx-AVX2.so", mode=2) at dlopen.c:87
#12 0xf7e8aca1 in wxDynamicLibrary::RawLoad(wxString const&, int) (libname=..., flags=2) at ../src/unix/dlunix.cpp:95
#13 0xf7d7ff4c in wxDynamicLibrary::Load(wxString const&, int) (this=0xffffc7a0, libnameOrig=..., flags=2) at ../src/common/dynlib.cpp:92
#14 0x082d23ba in Panels::PluginSelectorPanel::EnumThread::DoNextPlugin(int) ()
#15 0x082d3e47 in Panels::PluginSelectorPanel::OnProgress(wxCommandEvent&) ()
#16 0x081ff303 in Pcsx2App::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) ()
#17 0xf7d43def in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const (this=0xa8fe1c8, handler=0xabbbc08, functor=warning: RTTI symbol not found for class 'wxEventFunctorMethod<wxEventTypeTag<wxCommandEvent>, Panels::PluginSelectorPanel, wxCommandEvent, Panels::PluginSelectorPanel>'
..., event=...) at ../src/common/appbase.cpp:623
#18 0xf7edec85 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (entry=..., handler=0xabbbc08, event=...) at ../src/common/event.cpp:1392
#19 0xf7edf140 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) (this=0xabbbc08, event=...) at ../src/common/event.cpp:1751
#20 0xf7edf1e0 in wxEvtHandler::TryHereOnly(wxEvent&) (this=0xabbbc08, event=...) at ../src/common/event.cpp:1585
#21 0xf7edf29a in wxEvtHandler::TryBeforeAndHere(wxEvent&) (event=..., this=0xabbbc08) at ../include/wx/event.h:3671
#22 0xf7edf29a in wxEvtHandler::ProcessEventLocally(wxEvent&) (this=0xabbbc08, event=...) at ../src/common/event.cpp:1522
#23 0xf7edf303 in wxEvtHandler::ProcessEvent(wxEvent&) (this=0xabbbc08, event=...) at ../src/common/event.cpp:1495
#24 0xf7edfeb7 in wxEvtHandler::ProcessPendingEvents() (this=0xabbbc08) at ../src/common/event.cpp:1359
#25 0xf7d467b0 in wxAppConsoleBase::ProcessPendingEvents() (this=0xa8fe1c8) at ../src/common/appbase.cpp:520
#26 0xf78af8ec in wxApp::DoIdle() (this=0xa8fe1c8) at ../src/gtk/app.cpp:136
#27 0xf78afa0c in wxapp_idle_callback(gpointer) () at ../src/gtk/app.cpp:107
#28 0xf68fd38b in g_main_dispatch (context=0xa9205b0) at ././glib/gmain.c:3201
#29 0xf68fd38b in g_main_context_dispatch (context=0xa9205b0) at ././glib/gmain.c:3854
#30 0xf68fd779 in g_main_context_iterate (context=0xa9205b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3927
#31 0xf68fdb29 in g_main_loop_run (loop=0xab57d30) at ././glib/gmain.c:4123
#32 0xf70c5195 in gtk_main () at /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#33 0xf78d0c85 in wxGUIEventLoop::DoRun() (this=0xaa744e0) at ../src/gtk/evtloop.cpp:65
#34 0xf7d89a79 in wxEventLoopBase::Run() (this=0xaa744e0) at ../src/common/evtloopcmn.cpp:78
#35 0xf7d4b79f in wxAppConsoleBase::MainLoop() (this=0xa8fe1c8) at ../src/common/appbase.cpp:334
#36 0xf7d43830 in wxAppConsoleBase::OnRun() (this=0xa8fe1c8) at ../src/common/appbase.cpp:259
#37 0xf79ae48f in wxAppBase::OnRun() (this=0xa8fe1c8) at ../src/common/appcmn.cpp:304
#38 0xf7ddf338 in wxEntry(int&, wchar_t**) (argc=@0xf7f90520: 1, argv=0xa8eb4c0) at ../src/common/init.cpp:495
#39 0xf7ddf403 in wxEntry(int&, char**) (argc=@0xffffcf60: 1, argv=0xffffcff4) at ../src/common/init.cpp:507
#40 0x08067f6d in main ()
```
Full backtrace with all debugging symbols installed

**Comment by i30817** [comment]
Uh, i guess i forgot about the dbg package. Sorry, i see it on the apt-get listing now. Well, gamax92 got around to it, so no harm.

**Comment by gregory38** [comment]
Holy crap, gcc likely put clever optimization in the wrong path. I will check an objdump output. I hope it didn't impact windows user too :(

**Comment by gamax92** [comment]
Grabbed a Windows nightly build from Orphis just now, seems not to crash actually, plugin configuration screen comes up and AVX2 isn't listed. (SSE4.1 is still listed though which is wrong.)

**Comment by gregory38** [comment]
I pushed a fix. Hopefully it is the only constructor that is bad.

**Comment by gamax92** [comment]
Yep, this fixes it, no more SIGILL

**Comment by gamax92** [comment]
And no longer crashes on Windows, all GSdx plugins get listed now.

**Comment by gregory38** [comment]
For the record, SIGILL handler will be possible but it won't be portable so.
