### ISSUE TITLE
Broken terrain In shadow of the colossus - opengl hw

### ISSUE THREAD

**Issue by googl4** [PCSX2/pcsx2#1682]
Terrain doesn't render properly in game but seems to be fine in cutscenes, doesn't affect sw renderer
![sotc_hw](https://cloud.githubusercontent.com/assets/10489704/20807515/18071d86-b7f7-11e6-947a-d54adbfafb60.PNG)
same scene in sw 
![sotc_sw](https://cloud.githubusercontent.com/assets/10489704/20807529/317fe7c0-b7f7-11e6-9fa7-ca633beb3080.PNG)
[gs dump](https://www.dropbox.com/s/yu76xesrxp5zyxy/sotc_.gs?dl=0)

worked in 14xx builds I'll try to find the specific version if it helps

**Comment by willkuer** [comment]
Gsdx plugin settings?

**Comment by googl4** [comment]
sceenshot/gs dump was taken using defaults with ultra blending accuracy and accurate date.
no settings seem to make a difference

**Comment by googl4** [comment]
tested a few builds back to 679 and all have the same problem, it must have been driver update that broke it

**Comment by willkuer** [comment]
gpu vendor / driver? linux/windows?

**Comment by googl4** [comment]
nvidia 376.09 windows 7

**Comment by googl4** [comment]
tried 361.43 driver from december 2015 with pcsx2 1.4 and 1.5-1674, nothing makes a difference
I've played through the game since then, something else must have changed

**Comment by willkuer** [comment]
Are you using savestates?

**Comment by googl4** [comment]
No, full boot from a save file

**Comment by gregory38** [comment]
And did you try without accurate option (btw, ultra is only for debug) ?

Try to delete GSdx.ini file because some options aren't in the GUI so they could remain in the ini

**Comment by googl4** [comment]
ultra was only to be sure, I normally use high or full. I deleted gsdx.ini when trying different builds.
I don't remember the blending options affecting the the terrain but I'll see if none works

**Comment by willkuer** [comment]
Please post the full emulog after you observed the issue.

**Comment by googl4** [comment]
http://pastebin.com/LujTAknA

doesn't to have anything useful

**Comment by gregory38** [comment]
The dump is fine on my side (with the Free driver nouveau). What is your GPU ? Did you try to delete the ini file of the core ?

**Comment by willkuer** [comment]
OpenGL information. GPU: GeForce GTX 980 Ti/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver:
NVIDIA 376.09

**Comment by gregory38** [comment]
honestly no clue. Dump is fine on my side, so it is likely a configuration or driver issue.

**Comment by gregory38** [comment]
@googl4 Could you retry a fresh install of latest 1.5, it is a bad driver or a bad configuration or a bad build.

**Comment by googl4** [comment]
I tested it some more and it seems this game is very sensitive to software that hooks d3d/opengl calls like rivatuner.

**Comment by MrCK1** [comment]
@googl4 Update to the latest Rivatuner beta, the hooks won't interfere anymore

**Comment by gregory38** [comment]
Those buggy external softwares are a pain in the ***. There are already enough issues in PCSX2.
