### ISSUE TITLE
Galerians Ash (NTSC-U) - Several screens and texts missing.

### ISSUE THREAD

**Issue by piau9000** [PCSX2/pcsx2#1684]
***PCSX2 version:*** 1.5.0 build 1581.
***PCSX2 options:*** Tried all combinations of Clamp and Round. Also tried Software/Hardware mode and OpenGL/DirectX. Other settings are default.
***Plugins used:*** All default plugins.
***Last known version to work:*** I've not tested but, by reading some posts in the forum, I think it never worked.
***PC specifications:*** Intel Core I5 4690, EVGA Geforce GTX 750Ti, Windows 7 64 Bit.

***Description of the issue:*** Some texts and screens does not appear.
 The first example is right at the intro. The company logos in the intro does not appear. The screen keeps fading-in to white and fading-out to black. But the logos does not appear. You can only see the fade-in and fade-out. Here is how it's supposed to be:
https://www.youtube.com/watch?v=XJbII-_DGvE (right at the beggining)
Here is a gsdump:
http://www15.zippyshare.com/v/r5HlsZbg/file.html

Also, right at the beggining of the game, when the main character checks the body a text at the bottom says "Cain". Then the screens cut out to a door and then to a background with his face and the info about a item. Here's a video explaining it better:
https://www.youtube.com/watch?v=CZRys2oGYsk (go to min 8:47)
In pcsx2 it's really glitchy. The text "Cain" does not appear. When the screen cuts out to his face it is just a black background. The info about the item does not appear too. The only thing that appears is the 3D object floating.
Here's a gs dump of the specific part:
http://www15.zippyshare.com/v/gjRYRCaN/file.html
This bug appears during the entire game. Also some parts (puzzles) are unbeatable because of it.

**Comment by piau9000** [comment]
Okay. Effing zippyshare nuked all my files. :(
Sorry gregory. Here, I have reuploaded them just in case you need:

Intro:
http://www.mediafire.com/file/1mqggcocm3717ky/Galerians_2_-_Intro_Logos.zip
Ingame:
http://www.mediafire.com/file/82co4er6u8ha6ox/Galerian_2_-_Text_And_2D_Sceens.zip

**Comment by gregory38** [comment]
@piau9000 instead could you test the pr #1843 and tell me if it is working as expected.

**Comment by piau9000** [comment]
It seems that #1843 is not merged yet. I don't know how to build it myself.
But I tested rev 1910 and 1911 (the ones that make change to the grandient division) and the bug still persists.

**Comment by gregory38** [comment]
In the bottom of the PR (it is well hidden), there is a link to another build bot. You could test first the SW renderer and then the HW renderer. (the logo is working on SW)
* https://ci.appveyor.com/project/gregory38/pcsx2/build/1.2680-master/job/thw0ax8qjvkq8epl/artifacts

**Comment by piau9000** [comment]
Tested. It's working super fine now. :dancing_women: 
It even fixed another bug where the screen kept flashing red. I thought that it was unrelated to the missing texts so I did not reported it, but it seems that it was related.

**Comment by gregory38** [comment]
HW renderer too ?

**Comment by piau9000** [comment]
HW is still broken. The red flashing is still present on HW too.
But SW is pretty much fixed.

**Comment by gregory38** [comment]
Ok. I kinda expected it. The GPU doesn't like huge float value neither. Potentially we can avoid the division on the GPU when q is constant.

**Comment by gregory38** [comment]
@piau9000 Could you retry the HW OpenGL renderer ? I did a small fix, it might improve a bit the renderering.

**Comment by piau9000** [comment]
The bug still happen in HW mode.
Test with the last build on Orphis and the last one on AppVeyor.

A new message came up saying:
**Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38**

Do you want a new gsdump?

**Comment by gregory38** [comment]
I'm fine with current dumps. I only fixed sprite primitive but I think we have the same issue with triangles. 

```
Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38
```
Yes the game used bad ass float number.

**Comment by gregory38** [comment]
Yes the game uses triangles. I think we can improve a bit the code. But first, it would be nice if we could merge the code that upload vertices between both HW renderers.

**Comment by MadnessEmu** [comment]
I'm just an another guy that who was seeking a solution to solve this same problem here a long time ago, too shame that I'm not very understood in the programming, but hey! this version of PCSX2 that gregory38 posted, it worked! in OpenGL (software) mode, the text and the picture are spawned correctly now, great job and respect to you guys! thanks to the original poster and the gregory38 here again! 
i'll be keep testing the game and keep you guys posted

**Comment by MrCK1** [comment]
@MadnessEmu Can you please retest this on the latest git build with OpenGL Hardware and DX11 Hardware?

**Comment by redtvmax** [comment]
> @MadnessEmu Can you please retest this on the latest git build with OpenGL Hardware and DX11 Hardware?

On both hardware mode it is still happening

**Comment by UnknownChaos** [comment]
Hello, I'm new to the whole coding on PCSX2 if it's possible to help on this case since you can't proceed the game without the text being visible and I'm not sure if it requires replacing files or just edit the codes themselves. Thanks in advance to everyone contributing.

**Comment by redtvmax** [comment]
> Hello, I'm new to the whole coding on PCSX2 if it's possible to help on this case since you can't proceed the game without the text being visible and I'm not sure if it requires replacing files or just edit the codes themselves. Thanks in advance to everyone contributing.

Hey Pcsx2 is open source
you can download the code and fix it yourself and share it here 
than pcsx2 team might consider adding your fix to pcsx2 unless you fix it by using hack

**Comment by kozarovv** [comment]
Workaround for HW mode until proper fix will be done on GSDX side: https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=612276#pid612276

**Comment by refractionpcsx2** [comment]
Is this still an issue?

**Comment by lightningterror** [comment]
Part of Meta issue #5137
