### ISSUE TITLE
gigaherz driver for linux(partial)

### ISSUE THREAD

**Issue by JazzMaster** [PCSX2/pcsx2#1689]
we still dont seem to have a cdrom native linux plugin yet.
I believe the neogeo sources from neoCD team have a partial solution, if not full implementation from a mounted volume.

now, they are dated rhat, not rhel 5 ish but the code and binaries still run ok.

you might want to try cmake ui to trip the right compile options. (im on x64..)
there is a minor C glitch in the cdrom access code, and my C is rusty but I think I had it building at one point except for the cmake x86 on x64 issue(I hadnt changed the build and linker options).

im no C dev, but maybe this is in the right direction? Drat! I dont have the file, but its available online, both binary and sources.

**Comment by turtleli** [comment]
#1639 - cdvdGIgaherz was ported to Linux and the code was merged last month.
