### ISSUE TITLE
Glsl shader support request

### ISSUE THREAD

**Issue by wingedonezero** [PCSX2/pcsx2#1695]
Since work is being done one the psx side of things. Maybe you guys can add support for glsl. There are tons of shaders available already for that format. And it would be beneficial for the Gl backend when psx side becomes more stable. I have not many shaders besides whats included for the fx format. And from what i understand it was originally suppose to be only for the directx backend which seems like the gl one over took it. And it is doing better than directx one as of now, Of course i know this would only be available when using the gl driver. But it would add many options for all us. Like xbr and xbr lvl2 3d which works great for mixed content and so many more available. Plus it would work for the linux version and mac as well.

**Comment by gregory38** [comment]
Add shader of the openGL backend is in the glsl format (even builtin post-processing external shader). I don't understand what you want.

**Comment by wingedonezero** [comment]
I tryed to use one in the options before under select shader and config file. But most dont have a config file. And all i get is black screen. For reference i tryed the xbr one before from retro arch in glsl format. Are you saying its implimented already?

**Comment by gregory38** [comment]
Config can be an empty file. Anyway, I guess you don't know the shader theory. 

A shader computes an output data based on an input data. It is required to define the input/output interface. You could use any glsl shader but you need to update the interface to be compatible with PCSX2. If you try to use the PCSX2 shader on retroarch, you will get a black screen too.

**Comment by wingedonezero** [comment]
Ok i didn't know that because i use shaders from retroarch on a bunch of other emulators and haven't encountered that problem before.  So is it something that pcsx2 does differently so it has to be updated then. I understand. Is their anyway you could port like a hq4x and a xbr lvl2 3d shader? Maybe if you did that people would start making more shaders for pcsx2.

**Comment by gregory38** [comment]
PCSX2 uses modern GL only and uses shader for emulation. I guess most emulator uses shader as post-processing effects. Maybe they defined a common shader internal API.
