### ISSUE TITLE
Nascar 09: Slow, freezing, errors, ect. when using VU Interpeter or SuperVU

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1697]
***PCSX2 version:***
GIT v1.5.0-1709

***PCSX2 options:***
All Default, no speedhacks

***Plugins used:***
Default

***Description of the issue:***
When the emulator is switched to Interpreter/SuperVU, the game will slow to an unplayable state and GIF Unit errors will spam the console. The screen will begin to artifact with various graphical glitches and then freeze a few seconds later after the car spawns.

***How to reproduce the issue:***
Boot the game, start a race and switch the VU mode to Interpreter or SuperVU

***Last known version to work:***
N/A

***PC specifications:***
i5-6600k, GTX 970, Windows 10 64-bit

**Comment by FlatOutPS2** [comment]
So it's fine in the menu's?

**Comment by MrCK1** [comment]
Sorry, I should've been more specific. The menu still spams the console, but there's no issues there.

**Comment by refractionpcsx2** [comment]
wow, never seen a game actually use that :P does the GIF FIFO option help at all?

**Comment by MrCK1** [comment]
No, speed hacks didn't help. I'm assuming that you're referring to this :P

```Gif Unit - Signal or PSE Set or Dir = GS to EE```

**Comment by refractionpcsx2** [comment]
I didn't mean Speedhacks, I meant the GIF FIFO gamefix :P

**Comment by MrCK1** [comment]
Oops, no the GIF FIFO gamefix does nothing

**Comment by refractionpcsx2** [comment]
Ok thanks

**Comment by refractionpcsx2** [comment]
oh right.

Well, the interpreter is very buggy, so it's highly likely not to work on most games, SuperVU might get removed at some point, so there's not a great deal of point fixing it up, just use microVU.

**Comment by MrCK1** [comment]
OK, I'll was really only concerned since the interpreter didn't work (which it usually does on most games). I'm going to open another issue for the memory leak anyway, so I'll close this :P
