### ISSUE TITLE
[Improvement] Faster sequential snapshots

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1700]
***PCSX2 version:***
pcsx2-v1.5.0-dev-1711-g29d2292-windows-x86

***Description of the issue:***
I like to take a lot of screenshots of games, usually sequential snaps of a certain animation or cutscene. Problem is no matter how fast I press the snapshot key, there are a few seconds worth of delay between each generated screenshot. Meaning, that I can never get a quick sequential screenshot result.
I would be great if that delay was removed, so that if I press F8 four times in one second, I would get four screenshots of that specific time frame.

By the way, all settings are at default. As in, native resolution, no effects, no AA, etc.

***How to reproduce the issue:***
Just press F8 a bunch of times. 

***PC specifications:***
``(For example: CPU: Intel core i5 3470 GPU: none OS: Windows 7 64 Bit)``

**Comment by willkuer** [comment]
Please check the gsdx ini for a screenshot png compression entry. I think currently the compression is set to max - which will take more time. Set it manually to something lower should yield faster execution.

**Comment by turtleli** [comment]
I think the problem is actually that the screenshot filename is named based on the date and time, so you end up overwriting the file if you press F8 multiple times per second.

The default compression is max speed, not max compression.

**Comment by ReyVGM** [comment]
Ok, so could the naming be changed or maybe the time (with miliseconds) could be added? That way one could take multiple screens per second?

Do I need to make a new request or is this one fine?

**Comment by willkuer** [comment]
This one will be sufficient. Probably one can just add [here](https://github.com/turtleli/pcsx2/blob/6b950d0408a6fc7c12a070c277e48e0da4e60aaf/plugins/GSdx/GSRenderer.cpp#L530) some digits of the miliseconds or some random char sequence.

**Comment by ReyVGM** [comment]
Alright, cool. Hopefully someone is able to do it :)

**Comment by ssakash** [comment]
I was planning on capturing some screenshots to make a GIF file of an issue, but then eventually I found out that some of the screenshots were skipped for some reason and seems it's due to this bug!

Why wasn't this fixed earlier? Should be simple enough and I lost a bunch of my captured screenshots due to this stupid bug which resulted in my GIF looking not smooth. -_-

**Comment by ssakash** [comment]
> Ok, so could the naming be changed or maybe the time (with miliseconds) could be added? That way one could take multiple screens per second?

I don't think the tm structure stores the milliseconds data in it, we could probably get the milliseconds of the local time using some other library function, but probably not worth the effort, it would be better to just add a ``(2)``,``(3)`` next to the image's name to indicate that multiple images have been captured in a single second. (Yeah, following the same format which Windows does when it wants to add a new file which has a similar name of an old file present in the current directory)

**Comment by ReyVGM** [comment]
What the Dolphin guys did with this very same issue was just add a (1), (2) after each image. For example:
Game 07:59.png
Game 08:00.png
Game 08:00 (1).png
Game 08:00 (2).png

I believe that should be simple enough and would solve the issue.

**Comment by ssakash** [comment]
@ReyVGM : You could follow our discussion in **https://github.com/PCSX2/pcsx2/pull/1771#issuecomment-272637788**. Feel free to provide your opinions over there, best to concentrate the discussion on a single place.

**Comment by FlatOutPS2** [comment]
Why does this have high priority? :P

**Comment by ReyVGM** [comment]
Because ssakash _really_ wanted to make that GIF :P
