### ISSUE TITLE
[Improvement] Remove black screen when pausing/resuming the emulator

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1701]
PCSX2 version:
pcsx2-v1.5.0-dev-1711-g29d2292-windows-x86

Description of the issue:
Right now, when you pause and then resume the emulator, either from 'System -> Pause' or by pressing ESC, instead of the emulator resuming cleanly, it first throws a black screen.
It would be great if someone could improve that so that pausing/resuming is a clean process and isn't interrupted by a black screen first.

How to reproduce the issue:
I believe you first have to disable the "hide window when paused" so you can quickly press ESC to pause/resume to see the effect clearly.

PC specifications:
CPU: Intel core i5 3470 GPU: none OS: Windows 7 64 Bit

**Comment by lightningterror** [comment]
I wouldn't really call this an issue. The black screen appears because all plugins and configs are loaded again when resuming the emulator. It's the same when you change a setting and the emulator flashes black for a second.

**Comment by avih** [comment]
It's not "meant" to be there and it's unlikely we'll be able to reduce the duration for which it happens, but other than that, what @lightningterror said. When the emulation resumes/starts all the plugins and emulation components restart and it can result in a momentary black screen. Probably nothing to do about that.

**Comment by ReyVGM** [comment]
I see.

Just asking, but could there another way of pausing the emulator that could be implemented that doesn't do this?  I've never seen this happen with any other emulator, even with ones that use plugins. But then again, I guess every emu has it's own way of doing their stuff.

Thanks for the replies.

**Comment by avih** [comment]
> but could there another way ...

There's always another way, as the possibilities of code are literally endless. Finding this other way, however, while keeping everything else not broken - is a completely different story.

Patches are welcome.

**Comment by Evolution0** [comment]
Leave the last frame on screen and remove it when unpaused?

**Comment by ReyVGM** [comment]
I was just asking because I've used a lot of emulators across the decades and I've never seen any of them do that black frame thing, not even ones that heavily use plugins like PJ64. 

I don't want to raise a fuss or anything :P

**Comment by ReyVGM** [comment]
Question: aren't there other ways to 'freeze' the emulator without shutting down all the plugins? 
Is shutting everything the only way?

**Comment by avih** [comment]
Right now, yes, that's the only way.

**Comment by gregory38** [comment]
Most emulators don't use thread.

**Comment by sudonim1** [comment]
The frame buffer, and for that matter the frame buffer and crtc registers, don't actually exist in the emulator, they're in the GS plugin.
