### ISSUE TITLE
Kingdom Hearts II (USA) crashes PCSX2 during cutscene

### ISSUE THREAD

**Issue by autofire372** [PCSX2/pcsx2#1703]
With current builds of PCSX2, Kingdom Hearts II crashes the emulator during the cutscene immediately after the first fight with Pete in the Olympic Coliseum - Underworld. I think it's an audio emulation issue, as the crash occurs just as a character is about to speak in that cutscene.

**Comment by deadair3210** [comment]
Hardware? Config?  Original Version or Final Mix? CRC?

**Comment by autofire372** [comment]
OS: Windows 10 x64
CPU: Intel Core i7-4770k @4.4Ghz
GPU: Nvidia GeForce GTX 970, driver version 376.09

Config: http://pastebin.com/q0t1aCxj

Original version—Final Mix was never released for USA PS2

CRC: DA0535FD

The issue has been present in builds dating back at least a month—I will look to do further bisecting.

**Comment by autofire372** [comment]
OS: Windows 10 x64
CPU: Intel Core i7-4770k @4.4Ghz
GPU: Nvidia GeForce GTX 970, driver version 376.09

Config: http://pastebin.com/q0t1aCxj

Original Version—Final Mix doesn't exist for USA PS2

CRC: DA0535FD

This issue seems to go all the way back to 1.0, which can't be possible—I think it must a config error or a bad iso dump at this point.

**Comment by willkuer** [comment]
Please show the full emulog after you observed the issue (again pastebin please).

You enabled cheats. That can be an explanation.

**Comment by autofire372** [comment]
The issue was with a cheat code; turning off cheats stopped the crash. I dummied out the bad code in the pnach file, so I hopefully shouldn't encounter a similar issue again.
