### ISSUE TITLE
Attach SPU2-X volume control to Windows volume mixer setting

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1704]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd316791(v=vs.85).aspx

Then.. I guess something like this could be done with Pulseaudio too, but I dunno. 
EDIT: some of the stuff here may perhaps have something to help github.com/telegramdesktop/tdesktop/issues/418#issuecomment-276946421

**Comment by gamax92** [comment]
What? If I turn my system volume down PCSX2 gets quieter, and if I turn it up PCSX2 gets louder.

What is this?

**Comment by Nobbs66** [comment]
I believe the idea is to tie the volume control in spu2x to the volume mixer in Windows, rather than having two separate volume adjustments

**Comment by gamax92** [comment]
Is it specific to Windows then cause the SPU2-X I have doesn't have it's own volume controller.
Even if it does have it's own controller can't you just set it to 100%, ignore it, and just use your system volume controller instead of removing a feature for no reason?

You couldn't tie it to the system's volume because 50% windows volume + 50% SPU2-X volume results in 25% PS2 volume, you get a x^2 curve then.

**Comment by mirh** [comment]
> Even if it does have it's own controller can't you just set it to 100%, ignore it, and just use your system volume controller instead of removing a feature for no reason?

The feature is volume control from a place you find handy. 

There's no removal of any slider. 

> You couldn't tie it to the system's volume because 50% windows volume + 50% SPU2-X volume results in 25% PS2 volume, you get a x^2 curve then.

The idea is to make them the same thing. A change in the first is a change in the second and viceversa.

**Comment by FlatOutPS2** [comment]
> The idea is to make them the same thing. A change in the first is a change in the second and viceversa.

What if you want to reduce the PCSX2 volume, but not the Windows volume?

**Comment by willkuer** [comment]
I think it is only about the app-specific volume control. Like what you see when you open the 'mixer'. You can set a specific volume for each application separately.

To be honest I always use that one. I never used the spu setting and think it is rather pointless...

**Comment by mirh** [comment]
> What if you want to reduce the PCSX2 volume, but not the Windows volume?

![mixer](https://cloud.githubusercontent.com/assets/9366725/21262270/c677f670-c390-11e6-9bd0-d0c793a0c216.PNG)
I'm talking about this.

**Comment by refractionpcsx2** [comment]
I don't think linking the two would be sensible, for one if you left them both doing their own functions, the volume decrease would be exponential, giving you less flexability.

The only real solutions would be to fix SPU2-X to full volume then let you control it from windows, or just link the slider in SPU2-X directly to the windows slider and make it do nothing to the plugin itself.

However people still running XP (and possibly Vista?) will have issues because I don't believe either of them had independent controls. I couldn't say if linux would experience similar issues.

**Comment by mirh** [comment]
> I don't think linking the two would be sensible, for one if you left them both doing their own functions, the volume decrease would be exponential, giving you less flexability.

Indeed as I was saying 3 comments above, you'd have to ditch internal spu2-x volume control. 

> The only real solutions would be to fix SPU2-X to full volume then let you control it from windows, or just link the slider in SPU2-X directly to the windows slider and make it do nothing to the plugin itself.

I guess it would depend on if and how Windows remembers volume afterwards. 
Then depending on the answer, you'd have to ask yourself if volume should be "portable" (ie: stored in the .ini) or not. 

> However people still running XP (and possibly Vista?) will have issues because I don't believe either of them had independent application controls. I couldn't say if linux would experience similar issues.

The independent mixing was introduced in Vista iirc. 
Aside of that (and considerations others might want to raise against XP), I'm relatively confident Microsoft wouldn't have implemented this in Vista, knowing software wouldn't have worked on XP.

**Comment by refractionpcsx2** [comment]
Then that leaves the linux question, we should have this as portable as possible :) I'm not too concerned about XP as we have officially dropped that now.

**Comment by mirh** [comment]
Well, I thought ifdefs could do magic :p
I mean.. I guess it's kind of more messy considering you can either have plain ALSA or pulseaudio.

**Comment by refractionpcsx2** [comment]
I imagine so :P Not a linux buff though so I couldn't say for sure lol

**Comment by MrCK1** [comment]
I'll look into doing this in the future. The internal volume slider is dead to me without hotkeys anyways.

**Comment by lightningterror** [comment]
I never used it as well since I'm using the application volume slider.

If you want remove the slider from spu2-x go right ahead, tho many applications provide their own volume sliders so it _may very slightly come in handy_ ?

**Comment by RedDevilus** [comment]
I personally don't see why PCSX2 should be different. No other application/game that I know of links the OS slider to the internal volume slider and there are benefits having it detached. If you really don't like it you can also just ignore SPU2 window and just use the volume mixer.
