### ISSUE TITLE
CDVDgigaherz regression: Console errors when reading from physical drive

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1705]
***PCSX2 version:***
1.5.0-20161212230830 - compiled on Dec 13 2016

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults

***Description of the issue:***
While playing games from a CD drive, there will be stuttering and a few read errors that are not usually present. The degree of stutter depends on the game, so I have 2 test cases listed below. In general, the games will stutter regardless of whether or not read errors are being printed to the console at that time.

***How to reproduce the issue:***
The two games I tested were ATV Offroad Fury (DVD disk) and C-12 Final Resistance (PS1 game)

- **ATV Offroad Fury:** Stuttering while navigating menu screens, console errors while loading

- **C12: Final Resistance:** Console errors while loading, ~~~bad stuttering in both renderers, constantly fluctuating FPS in-game and menus (ranging from 60-10FPS). **As a comparison, _when I hot-swapped C12: Final Resistance to my ripped ISO file; the stuttering was eliminated completely_~~~ (I rechecked and this also occurs in 1540, so it's irrelevant now)

***Last known version to work:***
Regression was introduced between v1.5.0-dev-**1541** and v1.5.0-dev-**1566**. 

*After v1.5.0-dev-1540 (bug was NOT present yet) there were no builds until v1.5.0-dev-1566, where the bug was first found.

Here are the console errors reported in each game
ATV Offroad Fury: 
```* CDVD ReadFile failed: sectors 430848-430831: error 998```
```* CDVD ReadFile failed: sectors 430864-430831: error 998```

C12: Final Resistance: 
``` * CDVD ReadFile failed: sectors 18704-18704: error 1```
***PC specifications:***
i5-6600k, GTX 970, Windows 10 64-bit

**Comment by turtleli** [comment]
Do you have emulogs?

I think the DVD read errors are caused by the sector prefetch code attempting to read beyond the end of the disk. It's actually from before 1541, but I added additional debug messages so it's only being noticed now,

The single sector CD read failure is most likely from the keepalive thread so it's not critical (I'm not sure the keepalive thread is really doing its job properly), but the error message is a bit unexpected.

As for stuttering - that's hard to avoid. Perhaps a cache algorithm can be used but I don't think it'd help much. FWIW disk reading behaviour does seems different on Windows and Linux.

**Comment by FlatOutPS2** [comment]
I haven't noticed this and I've played several games from DVD in recent git builds.

I have noticed an issue where pausing and resuming can cause a DVD game to think it's running from ISO and fail to continue and vice versa. I've only encountered this issue a few times, but it was accross several PCSX2 versions. I wasn't able to reproduce it, so I'm not sure what's causing it.

**Comment by turtleli** [comment]
> I have noticed an issue where pausing and resuming can cause a DVD game to think it's running from ISO and fail to continue and vice versa.

Just to clarify: by vice versa you mean pausing and resuming an ISO makes it think it's running from DVD?

**Comment by FlatOutPS2** [comment]
> Just to clarify: by vice versa you mean pausing and resuming an ISO makes it think it's running from DVD?

Yes, and I recall once having it believe it was on No Disc, but I'm not sure if I was running and ISO or DVD at the time.

**Comment by turtleli** [comment]
Ok. Just checking whether it's a cdvdGigaherz or PCSX2 issue.

**Comment by ramapcsx2** [comment]
@turtleli The keepalive stuff needs to be investigated. I threw it together without good understanding of the systems involved and things like reading beyond offsets could happen. You can disable it as well if you want, but ideally something like it should be in place. It did help quite a bit when I tested it.

**Comment by turtleli** [comment]
Well, right now I'm thinking the keepalive stuff shouldn't be in a separate thread, but should be part of the main read thread. The current keepalive stuff doesn't seem to help on my system, though I don't have an idea of what would work better right now. I could make it read n seconds after the last read instead of after every 30 seconds which it's currently doing ,I don't know if that'd improve things though.

**Comment by FlatOutPS2** [comment]
I took a while, but I ran into the error too, while booting Everything Or Nothing. It throws several console messages ` * CDVD ReadFile failed: sectors 1703856-1703871: error 27` and slows initial loading down by over a third compared to earlier builds.

**Comment by turtleli** [comment]
Emulog? I kinda need to know the sector count to confirm whether I'm right or not.

I do know the latest builds are slower, but I don't have many ideas on how to speed things up safely (I perhaps shouldn't have reduced the max drive speed on Windows, though it did reduce spin up time for me).

**Comment by FlatOutPS2** [comment]
```
DvdRead: Reading Sector 1703616 (008 Blocks of Size 2064) at Speed=4x
DvdRead: Reading Sector 1703623 (008 Blocks of Size 2064) at Speed=4x
 * CDVD ReadFile failed: sectors 1703760-1703775: error 27
 * CDVD ReadFile failed: sectors 1703760-1703775: error 27
 * CDVD ReadFile failed: sectors 1703760-1703775: error 27
 * CDVD ReadFile failed: sectors 1703760-1703775: error 27
 * CDVD ReadFile failed: sectors 1703776-1703791: error 27
 * CDVD ReadFile failed: sectors 1703776-1703791: error 27
 * CDVD ReadFile failed: sectors 1703776-1703791: error 27
 * CDVD ReadFile failed: sectors 1703776-1703791: error 27
 * CDVD ReadFile failed: sectors 1703792-1703807: error 27
 * CDVD ReadFile failed: sectors 1703792-1703807: error 27
 * CDVD ReadFile failed: sectors 1703792-1703807: error 27
 * CDVD ReadFile failed: sectors 1703792-1703807: error 27
 * CDVD ReadFile failed: sectors 1703808-1703823: error 27
 * CDVD ReadFile failed: sectors 1703808-1703823: error 27
 * CDVD ReadFile failed: sectors 1703808-1703823: error 27
 * CDVD ReadFile failed: sectors 1703808-1703823: error 27
 * CDVD ReadFile failed: sectors 1703824-1703839: error 27
 * CDVD ReadFile failed: sectors 1703824-1703839: error 27
 * CDVD ReadFile failed: sectors 1703824-1703839: error 27
 * CDVD ReadFile failed: sectors 1703824-1703839: error 27
 * CDVD ReadFile failed: sectors 1703840-1703855: error 27
 * CDVD ReadFile failed: sectors 1703840-1703855: error 27
 * CDVD ReadFile failed: sectors 1703840-1703855: error 27
 * CDVD ReadFile failed: sectors 1703840-1703855: error 27
 * CDVD ReadFile failed: sectors 1703856-1703871: error 27
 * CDVD ReadFile failed: sectors 1703856-1703871: error 27
 * CDVD ReadFile failed: sectors 1703856-1703871: error 27
 * CDVD ReadFile failed: sectors 1703856-1703871: error 27
DvdRead: Reading Sector 0000016 (001 Blocks of Size 2064) at Speed=4x
DvdRead: Reading Sector 0000261 (001 Blocks of Size 2064) at Speed=4x
```

**Comment by turtleli** [comment]
Still missing the sector count, but yeah, I'll assume that's the end of the disk.

@MrCK1 Were your errors messages from the latest cdvdgigaherz version? The sector range in your error messages are in reverse order, but the sector range in FlatOut's error messages aren't (and they also match the current code).

**Comment by FlatOutPS2** [comment]
Oh, you meant this:
` * * Track 1: Data (Mode 1) (1703744 sectors)`

**Comment by turtleli** [comment]
Yes. Definitely a prefetch at the end of disk issue.

**Comment by FlatOutPS2** [comment]
Found another one. :P WRC 3 also throws error 27 and is also a prefetch at the end of disk issue.

**Comment by MrCK1** [comment]
@turtleli I was most likely still testing on dev-1566, so no. I'll test with the latest git tonight or tomorrow

**Comment by turtleli** [comment]
Try #1710, it should fix the prefetch at the end of disk issue.
