### ISSUE TITLE
[Request] Take screenshots while paused

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1707]
I know the answer will be "no" because the plugins shut down when you pause the emulator (or something close to that), but there might be an easy way to do it. 

Other emulators have had the same issue in which you can't take a screenshot (F8) while the emulator is paused, however, the way they have resolved it was to automatically advance one frame when you hit F8 while paused. Is that something that could be done here too?

**Comment by willkuer** [comment]
One could keep the last shown image in ram. One could also show that instead of the black screen that is annoying you.

**Comment by ReyVGM** [comment]
I support any kind of improvement.

**Comment by pmerry96** [comment]
This seems like a dead issue, is anyone interested in seeing this get implemented? If there is enough support I may look into finding a way to work this out.

**Comment by ReyVGM** [comment]
For people that take screenshots, yes it's important.
That way you can capture specific scenes without having to hit the screenshot button a hundred times hoping you catch what you want.

**Comment by RedDevilus** [comment]
I wonder what the difference from making snaps instead except the lossy or lossless format. (F8 or shift +F8 iirc)

**Comment by lightningterror** [comment]
Closing, trivial.
