### ISSUE TITLE
Project (Play!) is ps2 emu for all platforms. Including (android , iOS) need your help please.

### ISSUE THREAD

**Issue by Fadi5555** [PCSX2/pcsx2#1713]
Well first of all I would to thank you for this amazing project I really like it And using it daily because it's all in one.

Anyway this project as I said it's calld (Play!). It's ps2 emu for windows , MacOS , linux , iOS , android.
The creator of this project is called @jpd002 for long time he work on his project alone so that's why the project is slightly getting improve. Of course because of his work alone. So that's why we need you to help him on his project please. All of us dreaming to could play ps2 games on go like on android and iOS devices. We'll be very thankful for your help and appreciate a lot.

This is his link of his project:
https://github.com/jpd002/Play-

And this is an official thread talk about need people for help if you want to join or say something here:
https://github.com/jpd002/Play-/issues/503

And this is a screenshot of play! On my iPad Air 2 running resident evil 4:
![image](https://cloud.githubusercontent.com/assets/10546081/21419273/c321999e-c837-11e6-82cb-cce66e9f80c9.png)
![image](https://cloud.githubusercontent.com/assets/10546081/21419274/c362b0f0-c837-11e6-8a46-2af1ec6c1d38.png)

I'm sure you'll help him to improve it further more.
Thanks a lot for your kindness.

**Comment by ssakash** [comment]
This issue tracker on Github is only reserved for reporting bugs in the PCSX2 emulator, you shouldn't use this for advertising purposes.

We do understand your enthusiasm on attracting more developers for ``Play!`` but this probably isn't the right place for it, I suggest visiting subreddits like [r/emulation](https://www.reddit.com/r/emulation/) as lots of emulator developers roam around there.

**Comment by Fadi5555** [comment]
@ssakash I already made a thread there but please at least do me a favor and reopen this thread at least for three days only in order the others here see it.

This is my only request.
Thanks a lot.

**Comment by refractionpcsx2** [comment]
Sorry, we have enough of our own work to do without helping another project.  If they have any questions we are more than happy to answer them, but we are busy enough with our own project.

**Comment by willkuer** [comment]
Also have you asked jpd002 before posting here? I don't think advertising his own project on others projects webpages is something he would be proud of.
