### ISSUE TITLE
GUI/Win Additions and Improvements

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1715]
Ok so I have a requests / suggestions to add , I discussed some of these ideas with @gregory38 and @ssakash . I want to see what others think :)

1.  **Porting the OpenGL extension options from Linux to Windows.**``(Geometry Shader and one more )``
  - [ ] Add a configuration option above or below Shader configuration in video plugins.
  - [ ] The configuration option opens a separate popup where the extensions can be toggled.

2. **Hardware hacks GUI improvements**
 - [ ] "Round Sprite" and "Sprite" switch positions.
 - [ ]  Move "Skipdraw" above x,y offsets/ below sprites 
 - [ ]  Move MSAA above Sprite and Round Sprite

3. CRC Hack Level improvements
 - [ ] Change/Rename "Full (Safest)" to "Full (Direct3D Recommended)"
 - [ ] Change/Rename "Aggressive" to "Aggressive (Not Recommended)"

**Comment by FlatOutPS2** [comment]
> Add a configuration option above or below Shader configuration in video plugins.

That would again increase the hight of the window, which is already too high, so it would be good idea to also reorganize the window by making it landscape orientation, possibly removing the logo at at the top or whatever is preferred.

**Comment by ssakash** [comment]
> it would be good idea to also reorganize the window by making it landscape orientation, possibly removing the logo at at the top or whatever is preferred.

I think a better alternative would be to add a tab control, however I also don't mind the landscape orientation idea.

**Comment by FlatOutPS2** [comment]
> I think a better alternative would be to add a tab control

That could be best option as we would need two or three more seperate windows(one for OpenGL extension, one for OSD that will eventually be added, and 3D in a more distant future).

**Comment by lightningterror** [comment]
I added some more suggestions for CRC Hack level now , any thoughts ?

**Comment by lightningterror** [comment]
Closed since some of the improvements have been made as well as #1853
