### ISSUE TITLE
GSDX Setup Tuning: Initial setup uses sub-optimal CRC level in GSDX

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#1722]
After doing some experimenting, i noticed that when the initial setup of the plugins is done, GSDX defaults to OpenGL Hardware (good) and Full (Safest) CRC level (not so good). 

It would be better in this scenario to default to Partial (OpenGL Recommended).

I could do it but I refuse to touch GSDX and I know how much @ssakash loves it :P

**Comment by willkuer** [comment]
#1686 is the corresponding PR to solve the issue. I am just very slow because of lack of time. Sorry. :(

**Comment by refractionpcsx2** [comment]
Sorry! Didn't realise you were already on it :)

**Comment by refractionpcsx2** [comment]
@willkuer was assigned by @refractionpcsx2 just now

Github won't let me do it :(

**Comment by willkuer** [comment]
Perfect... put even more pressure on me...

**Comment by refractionpcsx2** [comment]
No pressure, take your time :)

**Comment by ssakash** [comment]
**Applies more pressure on willkuer** mwhahaha :evil

Just kidding,  take your time mate. ;)
