### ISSUE TITLE
Street Fighter EX3 Graphic Glitch

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1724]
***PCSX2 version:***
pcsx2-v1.5.0-dev-1711-g29d2292-windows-x86

***PCSX2 options:***
D3D11 Software. No enhancements.

***Plugins used:***
GSdx32-AVX
Also tried it on all the other graphic plugins and the same glitch happened.

***Description of the issue:***
Hokuto's skirt is tense like a satellite dish.

***How to reproduce the issue:***
Just pick Hokuto.

***PC specifications:***
CPU: i5 3rd gen 
GPU: None 
OS: Windows 7 64 Bit

GS DUMP
[GS Dump street fighter ex3 gfx glitch.zip](https://github.com/PCSX2/pcsx2/files/677643/GS.Dump.street.fighter.ex3.gfx.glitch.zip)

Character on the left, look at her skirt.
![zz](https://cloud.githubusercontent.com/assets/7338867/21550619/b0bd2abc-cdd1-11e6-9a36-ee852c0c8226.png)

**Comment by MrCK1** [comment]
This is already an open issue, see #954 for details.
