### ISSUE TITLE
Devil May Cry in-game text glitch

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1726]
PCSX2 version:
pcsx2-v1.5.0-dev-1711-g29d2292-windows-x86

PCSX2 options:
D3D11 Software. No enhancements.

Plugins used:
GSdx32-AVX
Also tried it on all the other graphic plugins and the same glitch happened.

Description of the issue:
While playing (not in a menu), if you press X to read a description of an object, instead of the text appearing on the bottom, it appears on top with part of the bottom background.

PC specifications:
CPU: i5 3rd gen
GPU: None
OS: Windows 7 64 Bit

GS DUMP
[devil may cry text glitch.zip](https://github.com/PCSX2/pcsx2/files/677787/devil.may.cry.text.glitch.zip)

![gsdx_20161229154931](https://cloud.githubusercontent.com/assets/7338867/21553505/0269a932-cddf-11e6-9cf4-9ebf56546fee.png)

**Comment by FlatOutPS2** [comment]
Try the latest git. Dump indicates it has been resolved.
