### ISSUE TITLE
Formula One 2001: Graphical Glitching (Not SPS)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1732]
***PCSX2 version:***
PCSX2 1.5.0-20161231174238 - compiled on Dec 31 2016

***PCSX2 options:***
Safest preset
Automatic gamefixes (XGKick for SPS) 
WS patch

***Plugins used:***
Defaults, OGL HW, 4x Native

***Description of the issue:***
So there's this weird spiking going on while driving around, but I think it's caused by the WS patch. If I boot the game without the WS patches there's no bugs. However, the bug reappears whenever the WS patch is enabled/loaded.

***How to reproduce the issue:***
Boot game, enable WS patch if necessary, enter a race and start driving.

***Last known version to work:***
PCSX2 1.5.0-20161119215208 - compiled on Nov 19 2016 (I last played the game when I was gathering data for #1668 and had no issues with the WS patch)

***PC specifications:***
Intel i5-6600k@4.7Ghz, Nvidia GTX 1070, Win 10 64-bit

[GS Dump](https://github.com/PCSX2/pcsx2/files/680402/F12001_WSPatchRegression.pdf) (Rename to .7z)

![gsdx_20170101234636](https://cloud.githubusercontent.com/assets/16314399/21584766/f1b8a600-d07d-11e6-9fe5-bce7ee3e5a92.png)

**Comment by FlatOutPS2** [comment]
Check if it really is a widescreen hack issue, because that would invalidate this issue. :P You should then also mention the issue in the widescreen patches thread on the forum to request a better patch.

**Comment by refractionpcsx2** [comment]
Everything does look a bit tall and thin, try it with widescreen patches disabled to see if things improve

**Comment by MrCK1** [comment]
I've determined that it is a widescreen patch issue.
