### ISSUE TITLE
PCSX2: Warning about widescreen hack?

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1733]
We've encountered lots of cases where widescreen hack causes various instability/issues with certain games, there was also a scenario where we were totally confused about a bug and at the end it turned out to be an [**issue with widescreen hacks!**](http://forums.pcsx2.net/Thread-Invalid-Bug-Report-Sly-2-Band-Of-Theives-NTSC-U?highlight=vsub)

To avoid such cases, my proposal is that we add a help message to the status bar of the console window when someone is hovering over the ``Enable Widescreen Patches`` menu item, the help message should indicate that the hack _might_ potentially cause issues in games.

 **(or)** 

Maybe we could add a console message at each boot of the virtual machine to warn the users that the hack might cause some problems. (Obviously, these warnings should only be printed on the console when widescreen hack is enabled)

Maybe it's unnecessary as the word "hack" already insinuates that it might potentially cause some issues, but I guess there's no harm in being more clear about this? Any opinion?

**Comment by FlatOutPS2** [comment]
Another option would be to add a popup warning when you try to enable it.

Whatever is done, make sure to do it for Cheats too. ;)

**Comment by refractionpcsx2** [comment]
As long as it's clear for us when we support it, im happy either way, I just like to be sure I can see if they have them turned on (and there is a patch for that game) so we can tell them to try turning them off :p

What would be even better is reporting the unstable patches to the widescreen patch guy on the forum so he can fix or remove them :)

**Comment by avih** [comment]
> What would be even better is reporting the unstable patches to the widescreen patch guy on the forum so he can fix or remove them :)

+1 to that.

The WS patches we ship with pcsx2 itself should be super stable. The less stable ones should be downloaded by the users who want to experiment. We once (not recently) tried establishing some quality standards to these patches, but IIRC couldn't get to full agreement on what should qualify... :/

Maybe we should re-open the subject considering that issue reports do sometimes end up WS related?

**Comment by FlatOutPS2** [comment]
> We once (not recently) tried establishing some quality standards to these patches, but IIRC couldn't get to full agreement on what should qualify... :/

You can't guarantee that anyway. A WS patch might be fine for 90% of the game, only to break down in the final stages of the game.

We should also add a warning telling users to check if cheats/widescreen patches are disabled in the git issue and forum bug report templates.

**Comment by avih** [comment]
> You can't guarantee that anyway.

Of course we can't. But the point is we couldn't even agree on a standard.


> We should also add a warning telling users to check if cheats/widescreen patches are disabled in the git issue and forum bug report templates.

Yup, that should be the first step regardless IMO too.

**Comment by mirh** [comment]
> Another option would be to add a pop-up warning when you try to enable it.

Far from seeing we mustn't.. But unless a great deal of patches is crap, to be honest, I would despise further making pcsx2 looks hacky, if I can explain.

**Comment by gregory38** [comment]
So what do we do ? Close or Update ?

**Comment by gregory38** [comment]
ping. What do you do ? In particular for 1.6

**Comment by mirh** [comment]
How about printing something \*whenever\* *any* pnach is loaded?
(with widescreen mentioned as a special case perhaps)

**Comment by lightningterror** [comment]
![image](https://user-images.githubusercontent.com/18107717/47165426-36eda100-d2fa-11e8-9cde-a2ba1703376b.png)

**Comment by mirh** [comment]
And would that include interlacing, 60fps, and cheats?
