### ISSUE TITLE
OSD Monitor doesn't update while fullscreen

### ISSUE THREAD

**Issue by Hirato** [PCSX2/pcsx2#1736]
***PCSX2 version:***
1.5.0.r4257.fce281473

***Plugins used:***
GSDX - OpenGL

***Description of the issue:***
With the OSD monitor enabled, the values update normally to copy what is in the titlebar.
Until you fullscreen the game window and the titlebar becomes hidden, then the monitor no longer updates.

***How to reproduce the issue:***
Check the 'Enable Monitor' checkbox in the OSD tab.
Run any game, and fullscreen the window

***PC specifications:***
OS: Arch Linux x86_64
GPU: Nvidia 770GT

Yay, first OSD bug report~!

**Comment by ssakash** [comment]
I guess the OSD monitor functions should probably be moved from ``void GSFrame::OnUpdateTitle( wxTimerEvent& evt )`` **(or)** not sure if it's intentional to only be updated in window mode?

**Comment by FlatOutPS2** [comment]
I guess the OSD monitor functions should probably be moved from void GSFrame::OnUpdateTitle( wxTimerEvent& evt ) (or) not sure if it's intentional to only be updated in window mode?

Does the title update get disabled in fullscreen on Linux? The monitor works fine on Windows in fullscreen.

**Comment by ssakash** [comment]
> Does the title update get disabled in fullscreen on Linux? The monitor works fine on Windows in fullscreen.

According to the code, yes. ;)
```
void GSFrame::OnUpdateTitle( wxTimerEvent& evt )
{
#ifdef __linux__
	// Important Linux note: When the title is set in fullscreen the window is redrawn. Unfortunately
	// an intermediate white screen appears too which leads to a very annoying flickering.
	if (IsFullScreen()) return;
#endif
```

**Comment by ssakash** [comment]
I'm not sure if it's safe to remove that early return, assigning the issue to turtleli as he probably knows what's best.

**Comment by gregory38** [comment]
From the one that I wrote the comment a long time ago ;) It is likely not safe. But it was on wx2.8/zzogl. That being said the issue was the title on the window bar. You can still compute the title and print it on the osd.

**Comment by Hirato** [comment]
I don't think that should cause any issues.
However that does explain why I can attach OBS to the window while it's fullscreen and not while it's windowed; it doesn't like the constantly updating window title.
