### ISSUE TITLE
Running --nogui causes player 2 not to be recognized

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#1738]
***PCSX2 version:***
1.5.0 dev 1756

***PCSX2 options:***
Default

***Plugins used:***
OpenGL software

***Description of the issue:***
If you start a game using CLI and the --nogui command, player 2 will not be recognized/mapped.

***How to reproduce the issue:***
Start a game using --nogui and try to play with 2 players.

***PC specifications:***
CPU: Intel Core i5 6300u GPU: Nvidia GTX 940m OS: Windows 10 64 Bit

**Comment by FlatOutPS2** [comment]
I used the same build, but I couldn't reproduce the issue. Did you use any other CLI options or change any other settings/plugins from the default?

**Comment by tony971** [comment]
I actually went through PCSX2Bonus. I didn't explicitly check any other options but I don't know if PCSX2Bonus uses any others by default.

**Comment by FlatOutPS2** [comment]
Start PCSX2 without using a third party app, check your player 2 bindings/mapping and then do a --nogui boot of just PCSX2. It should work without issue.

PCSX2Bonus uses individual settings per game so you should also check if it has player 2 bindings set up correctly for the game(s) you were trying to play.
