### ISSUE TITLE
Ecco the Dolphin: Defender of the Future [PAL-E] - hangs on first loading screen

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#1743]
***PCSX2 version:***
1.5.0-dev-1764

***PCSX2 options:***
defaults, see workaround down below

***Plugins used:***
GSdx11 SW, SPU2-X

***Description of the issue:***
Ecco the Dolphin [PAL-E] [SCES-50499] hangs on the very first loading screen after booting. 

***How to reproduce the issue:***
Boot the game with default settings

***Last known version to work:***
Never, as far as I can tell.

***PC specifications:***
i5-4690k, R9 270X, 16GB RAM, Win10 Pro x64 14393

***Workaround:***
Setting EE cyclerate to -3 while also disabling Wait Loop Detection will allow the game to load properly. Once the game has loaded, these settings can be changed again. The game seems to run fine.

Making this report mostly so it is on Github and can be properly tagged and tackled someday. It's a known issue after all. The workaround maybe less so. Maybe it can help track down this particular gremlin

**Comment by refractionpcsx2** [comment]
That's handy, previously we've used a hack in the code to get around the boot problem :)

**Comment by refractionpcsx2** [comment]
Hmm, that workaround doesn't work here, what about other settings?

**Comment by refractionpcsx2** [comment]
Oh wait! It does after Turteli's CDVD changes! awesome! :)

**Comment by trostboot** [comment]
That's odd. I've tried a number of speedhack combinations and those two were the only ones that mattered. Rest should be defaults. I'll double-check when I get back from walking the dog.

**Comment by refractionpcsx2** [comment]
No ignore me, it does work, and only those settings too, nice job! :)

**Comment by trostboot** [comment]
Sweet. Nice to have it narrowed down some more with the CDVD changes, too.

**Comment by refractionpcsx2** [comment]
I think some more are in order :)

**Comment by ramapcsx2** [comment]
Hm yea, it works intermittently with the workaround. I needed to retry a few times.
Anyway, fiddling with timing always made this game work. The previous 2 "fixes" where a different SIF delay and an IOP underclock, back when we used to have that.
It would be nice though if the flag change affected it. Is it related?

**Comment by refractionpcsx2** [comment]
Well my master didn't work when i posted before, because I hadn't updated to the new CDVD changes, now it does :)

**Comment by trostboot** [comment]
Hm, it seems to reliably fail when using a fresh PCSX2 instance, but seems to work on a second attempt without closing the instance. ~10 tries or so, always the same result.

**Comment by refractionpcsx2** [comment]
Further to this, it's due to the "Data ready" flag

**Comment by ramapcsx2** [comment]
Well, that is info! Promising!
