### ISSUE TITLE
R3000 breakpoints not working

### ISSUE THREAD

**Issue by Nisto** [PCSX2/pcsx2#1746]
***PCSX2 version:***
PCSX2 1.4.0-20160105132032- compiled on Jan  5 2016

***PCSX2 options:***
Default.

I also tested changing these settings without any luck:
- IOP -> Interpreter
- EmotionEngine -> Interpreter
- Enable speedhacks -> disabled
- Automatic gamefixes -> disabled

***Plugins used:***
Default.

***BIOS used:***
**Japan   v01.60(27/04/2001)  Console** (SCPH-30000 version 5.0 04/27/01 J)

***Games tested:***
- Final Fantasy X (SLPS-25050)
- Rakugaki Okoku 2 Maojo no Tatakai (SLPM-65637)
- World Soccer Winning Eleven 5 (SLPM-62053)

***Description of the issue:***
Breakpoints on the R3000 core doesn't appear to be working. Both cores give me the message "unimplemented" if I explicitly right-click on an opcode and press "toggle breakpoint", but evidently breakpoints *are* implemented at least for R5900, as they do work fine there.

I am positive that the addresses I put breakpoints on are reached. I have even been able to put in a printf call via the "assemble opcode" context menu function to verify it via the PCSX2 log.

I have tried the latest development version as well (v1.5.0-dev-1764-g80be9d9) and it seems the problem is still present there.

***How to reproduce the issue:***
Select and click an opcode to set a breakpoint. Alternatively, add it in the breakpoints tab, or click the "breakpoint" button at the top.

***Last known version to work:***
?

***PC specifications:***
CPU: Intel Core i7-6800K
GPU: ASUS GeForce GTX970
OS: Windows 7 SP1 64 bit

**Comment by MrCK1** [comment]
@Nisto You should try the latest dev build [here](http://pcsx2.net/download/development/git.html) - as your version is outdated.

**Comment by gregory38** [comment]
I confirm the "issue". Yes R3000 is another CPU which will need dedicated code. Interpreters aren't supported neither
