### ISSUE TITLE
GSDX CLUT: Romance of the Three Kingdoms VIII Text problem

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#1754]
Text on the menu has always displayed incorrectly however it was mostly right back in the 1.0.0 days. After sudonim's changes back in 2fbcafc85e3f8fd84340c68e147d3edacd6f34d0 the text became black and has stayed as such ever since.

Related forum thread with screenshots and info:  http://forums.pcsx2.net/Thread-ROTK8

Followup thread re-highlighting the issue: http://forums.pcsx2.net/Thread-Bug-Report-Romance-of-the-Three-Kingdoms-8-NTSC-U-C

Note has been made in GSClut.cpp line 162 under WriteCLUT32_I8_CSM1

**Comment by FlatOutPS2** [comment]
Why not just use this thread? https://github.com/PCSX2/pcsx2/issues/1628

**Comment by refractionpcsx2** [comment]
Bugger, didn't know there was one

**Comment by gregory38** [comment]
Please add all the info on the first report.

**Comment by refractionpcsx2** [comment]
Done

**Comment by FlatOutPS2** [comment]
I'm not sure many people know who `Refraciton` is.

**Comment by refractionpcsx2** [comment]
> I'm not sure many people know who Refraciton is.

fixed it smart arse :P
