### ISSUE TITLE
Graphic Issues with Monopoly Party

### ISSUE THREAD

**Issue by HDx64** [PCSX2/pcsx2#1755]
***PCSX2 version:***
PCSX2 v1.4.0_Stable and pcsx2-v1.5.0-dev-1705-g415090d-windows-x86

- **Note**: It's preferred to only report bugs which are present on the [latest development builds](http://pcsx2.net/download/development.html).

- **Note2**: The new backwards compatibility (psx) mode is in active development. Issue reports are too early at this point.

***PCSX2 options:***
Any setting including default settings

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset along with MTVU speed hack disabled. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***

GSDX plugin used - Any setting has graphics issues including default settings

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

The Monopoly Party game board is not displayed properly.  Major graphics glitches.

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

Just run the Monopoly Party program and try to play the game.

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

Unfortunately, I haven't found a PCSX2 version that works yet.

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

Windows 7 Home Premium 64-bit SP1, Intel Core i7 740QM @ 1.73GHz, 1024MB ATI Mobility Radeon HD 5870 Graphics, 16GB DDR3 Main Memory.

**Comment by MrCK1** [comment]
Do you know what renderer are you using? ( ie DirectX 11 or OpenGL)

Could you also upload a screenshot of the issue?

**Comment by HDx64** [comment]
Christian,

Thank you for the prompt reply!

I tried everything HW/SW DirectX11, OpenGL, etc.  I'll try to upload a
screenshot.

But, just in case I can't figure out how to upload a screenshot, please see
below.  The PCSX2 emulator should be displaying the game board but only a
very small portion of the game board is being displayed.  The rest of the
game board is black.


[image: Inline image 1]

**Comment by HDx64** [comment]
![monopoly party_speed_ 100 59 93 _ limiter_ normal _ gsdx d3d11 sw _ 640x448 _ auto](https://cloud.githubusercontent.com/assets/25023226/21793914/a32222ae-d6c3-11e6-97da-ba30404d7c78.jpg)

**Comment by prafullpcsx2** [comment]
This game requires supervu recompiler.

**Comment by refractionpcsx2** [comment]
Already on our list in #1638 :)

**Comment by HDx64** [comment]
That fixed it.  Thank you!

**Comment by FlatOutPS2** [comment]
> I tried playing the game and the game board is showing properly with the superVU Recompiler on VU1 as noted. However, some of the game tokens have undrawn parts and some are even completely invisible. For example, the dog token is missing its entire head. 

Try setting VU0 to superVU and try the non-default VU Round and Clamping mode settings.

**Comment by HDx64** [comment]
Christian,

"Try setting VU0 to superVU and try the non-default VU Round and Clamping
mode settings."

Thank you for the tips on the settings.  The game works now :)

Round Mode = *Chop/Zero* (Default)
Clamping Mode = *None*

Hayden

**Comment by MrCK1** [comment]
Has anyone tested this game on latest git to see if status has changed since #1835?

**Comment by FlatOutPS2** [comment]
No one has worked on improving microVU vs SuperVU, so there won't be a difference. The PR you've linked fixed an issue that affected both recompilers and the interpreter.

**Comment by MrCK1** [comment]
Forgot to close this. The clamping fix was added back in #2503
