### ISSUE TITLE
Full Spectrum Warrior - GSdx HW vertical lines regression

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1757]
***PCSX2 version:***
v1.5.0-dev-1779-g83b5bdb

***PCSX2 options:***
Default + VU1 set to SuperVU

***Plugins used:***
Default

***Description of the issue:***
Vertical lines flicker onscreen.

***How to reproduce the issue:***
Use Hardware renderer and load a mission.

***Last known version to work:***
Regression caused by:
https://github.com/PCSX2/pcsx2/pull/1185

GS Dump: 
[Full Spectrum Warrior - vertical lines regression.zip](https://github.com/PCSX2/pcsx2/files/696708/Full.Spectrum.Warrior.-.vertical.lines.regression.zip)

**Comment by gregory38** [comment]
Did you use either a EE or VU cycle rate speedhack ?

**Comment by gregory38** [comment]
You win a test round :) Thanks for the report and regression info.
