### ISSUE TITLE
Graphical glitch in Tales of Legendia

### ISSUE THREAD

**Issue by LorenzoConte97** [PCSX2/pcsx2#1761]
***PCSX2 version:***
v1.5.0-dev-1789-g8cf3a83

***PCSX2 options:***
Emulator Settings: 1 (Safe+)
GSdx Settings:
Adapter: Nvidia GTX 970
Render: OpenGL (Hardware)
Interlacing: Auto
Resolution: Native
Texture Filtering: Bilinear (PS2)
Anisotropic Filtering: off
Mipmapping: off
CRC level: Full
Blending Unit: Basic

***Plugins used:***
GS: GSdx 1.1.0 AVX2
PAD: LilyPad 0.12.0
SPU2: SPU2-X 2.0.0
CDVD: cdvdGigaherz 0.11.0

***Description of the issue:***
If I change the game Jak and Dexter: TPL with Tales of Legendia, I see the old image of Jak & dexter in the starting video.

screen: http://oi66.tinypic.com/34g8484.jpg

***How to reproduce the issue:***
Start jak and daxter: the precursor legacy
change iso and start tales of legendia (I clicked in "change disk")
and during the loading video there are old image from jak & dexter.

***PC specifications:***
CPU: Intel Core i5 4690k @ 3.5GHz
GPU: Nvidia GTX 970 G1 GAMING (last driver)
OS: Windows 7 Professional 64bit (last update)

**Comment by MrCK1** [comment]
This is somewhat of a minor issue. It's normal to "see" leftover data from any previously loaded game .

**Comment by gregory38** [comment]
If you don't do a reset between game, you get data of the older game. It feels like a normal behavior

**Comment by LorenzoConte97** [comment]
There is also if click "reset"

**Comment by gregory38** [comment]
Hit two time F9.
