### ISSUE TITLE
Ar Tonelico 2 - World Map renders incorrectly

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1762]
OS: `Slackware64-current`
`mesa-compat32-2016.12.29_b7699ce07c_master-x86_64-1_gitcompat32`
`pcsx2-2017.01.10_62c21fd58_master-x86_64-1_git`

In the game Ar Tonelico 2 (Patched with the Project Metafalica retranslation) the world map will render incorrectly. I've tried various options such as the CRC level and hacks which failed to make a difference. I also tried as far back as commit e329b6f and also found the same problem.

Gsdx dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_20170111150438_Ar_Tonelico_2_project_metafalica.gs.xz
Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/PCSX2_Ar_Tonelico_2_project_matafalica.trace.xz

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/pcsx2/2017-01-11-151210_1680x1050_scrot.png)

**Comment by FlatOutPS2** [comment]
Try it without applying the patch.

**Comment by orbea** [comment]
I just did, same result. Someone else was also able to reproduce with the apitrace using intel, so its probably either the mesa-core or pcsx2 itself.

**Comment by gregory38** [comment]
GSdx uses a CRC hack for this game. We need to check if it is enabled. What is your game CRC ?

**Comment by orbea** [comment]
Here is the crc32 for both isos I tried.
```
027a757f Ar_tonelico_2_Project_Metafalica.iso
49205494 ar_tonelico_2_us.iso
```
The latter (Unpatched iso) should be a redump as the md5sum, sha1sum and crc32 matches the following link.
http://redump2.rssing.com/chan-20787209/all_p337.html

md5sum - `1b83937656fd8fede5c0fbc8dbc11f8f`
sha1sum - `df94f6a165cfc829821a5a18c1e3bf650624de52`

To be clear I tried CRC hack levels none, partial, full and aggressive without any difference. Additionally loading the redump iso will print.
`Patches: No CRC found, using 00000000 instead.`

**Comment by gregory38** [comment]
GSdx CRC are different. Anyway they don't match.
{0xF46142D3, ArTonelico2, NoRegion, 0},

**Comment by gregory38** [comment]
File is GScrc.cpp, you can edit it and recompile it ;)

**Comment by orbea** [comment]
Maybe I'm missing something simple, but I tried the following patch and found no difference using the Project Metafalica iso. 
```
diff --git a/plugins/GSdx/GSCrc.cpp b/plugins/GSdx/GSCrc.cpp
index 4d97b33af..b2692b51b 100644
--- a/plugins/GSdx/GSCrc.cpp
+++ b/plugins/GSdx/GSCrc.cpp
@@ -26,7 +26,7 @@
 CRC::Game CRC::m_games[] =
 {
        {0x00000000, NoTitle, NoRegion, 0},
-       {0xF46142D3, ArTonelico2, NoRegion, 0},
+       {0x027A757F, ArTonelico2, NoRegion, 0},
        {0x2113EA2E, MetalSlug6, JP, 0},
        {0x42E05BAF, TomoyoAfter, JP, PointListPalette},
        {0x7800DC84, Clannad, JP, PointListPalette},
```

**Comment by gregory38** [comment]
Wait, where did you get the CRC ? You need to use the CRC computed by the emulator. Not an external CRC tool.

**Comment by refractionpcsx2** [comment]
gregory meant the CRC PCSX2 reports, not the CRC of the ISO file.

**Comment by orbea** [comment]
Right, I didn't understand that earlier, I didn't realize the CRC reported by PCSX2 would be different from what is reported by crc32. My bad...

PCSX2 reports these.

Project Metafalica - `GSdx Lookup CRC:C38067F4`
Redump US iso - `GSdx Lookup CRC:F95F37EE`
Old undub iso - `GSdx Lookup CRC:BC5F505` (Why is it one letter shorter than all of the others?)

These still don't match so this time I tried the following test.
```
diff --git a/plugins/GSdx/GSCrc.cpp b/plugins/GSdx/GSCrc.cpp
index 4d97b33af..503e8d4ba 100644
--- a/plugins/GSdx/GSCrc.cpp
+++ b/plugins/GSdx/GSCrc.cpp
@@ -26,7 +26,7 @@
 CRC::Game CRC::m_games[] =
 {
 	{0x00000000, NoTitle, NoRegion, 0},
-	{0xF46142D3, ArTonelico2, NoRegion, 0},
+	{0xC38067F4, ArTonelico2, NoRegion, 0},
 	{0x2113EA2E, MetalSlug6, JP, 0},
 	{0x42E05BAF, TomoyoAfter, JP, PointListPalette},
 	{0x7800DC84, Clannad, JP, PointListPalette},
```
Now the issue is resolved with CRC levels minimum or higher! Thanks.

So I next tried.
```
diff --git a/plugins/GSdx/GSCrc.cpp b/plugins/GSdx/GSCrc.cpp
index 4d97b33af..bdd2dec70 100644
--- a/plugins/GSdx/GSCrc.cpp
+++ b/plugins/GSdx/GSCrc.cpp
@@ -27,6 +27,9 @@ CRC::Game CRC::m_games[] =
 {
 	{0x00000000, NoTitle, NoRegion, 0},
 	{0xF46142D3, ArTonelico2, NoRegion, 0},
+	{0xF95F37EE, ArTonelico2, US, 0}, // redump
+	{0xC38067F4, ArTonelico2, US, 0}, // project metafalica
+	{0xBC5F505, ArTonelico2, US, 0}, // undub
 	{0x2113EA2E, MetalSlug6, JP, 0},
 	{0x42E05BAF, TomoyoAfter, JP, PointListPalette},
 	{0x7800DC84, Clannad, JP, PointListPalette},
```
This successfully resolves it for all three versions I have, should these extra CRC be added? As for this issue report, should it be closed or is it better to wait till the underlying hack is resolved (If possible)?

**Comment by gregory38** [comment]
```
 the underlying hack is resolved (If possible)?
```

Here the hack code with the explanation. I'm not sure you will understand it. But in short, the game uses a 640x448 sprite to write an 384x672 area... Unlike standard GPU the GS memory isn't linear.

```
	// world map clipping
	//
	// The bad draw call is a sprite rendering to clear the z buffer

	/*
	   Depth buffer description
	   * width is 10 pages
	   * texture/scissor size is 640x448
	   * depth is 16 bits so it writes 70 (10w * 7h) pages of data.

	   following draw calls will use the buffer as 6 pages width with a scissor
	   test of 384x672. So the above texture can be seen as a

	   * texture width: 6 pages * 64 pixels/page = 384
	   * texture height: 70/6 pages * 64 pixels/page =746

	   So as you can see the GS issue a write of 640x448 but actually it
	   expects to clean a 384x746 area. Ideally the fix will transform the
	   buffer to adapt the page width properly.
	 */

	GSVertex* v = &m_vertex.buff[0];

	if (m_vertex.next == 2 && !PRIM->TME && m_context->FRAME.FBW == 10 && v->XYZ.Z == 0 && m_context->TEST.ZTST == ZTST_ALWAYS) {
		GL_INS("OI_ArTonelico2");
		m_dev->ClearDepth(ds);
	}
```

**Comment by FlatOutPS2** [comment]
I added to PAL and NTSC-U CRC's to https://github.com/PCSX2/pcsx2/pull/1764

Hacked CRC's aren't supported. They're also likely to change when the patch is updated.

**Comment by orbea** [comment]
Thanks, that is fair enough. I guess I can patch it locally myself then. :)

I guess this issue could be closed when your PR is merged.

**Comment by orbea** [comment]
Not to argue too much, but retranslations like Project Metafalica are versioned, so the CRC could simply be commented as version 1.0 and then updated for further any future patch versions that are released? Given the extremely shoddy quality of the official translations I suspect I won't be the last person to run into this. :)

http://www.romhacking.net/translations/2833/

**Comment by piau9000** [comment]
I'm not a programmer but the "CRC change each update" problem can be solved by using gamecodes (SLUS 21788) instead of hashes.
Game codes don't change, even with patched games.

So instead of checking for the CRC it would check for the gamecode.

**Comment by refractionpcsx2** [comment]
the serial codes (SLUS etc) aren't always unique, which is why we use CRC, it's easier to identify between different games.  Putting the current CRC's and updating them whenever the translation changes will penalise people who have the older versions and create unnecessary work for us, so we avoid doing such things.

**Comment by orbea** [comment]
That is fair enough, just to be clear I was thinking of not removing the CRC for older patch versions and only adding new ones as they come out.

**Comment by i30817** [comment]
Wouldn't it be much easier for you to have the game code be the default and those few games that need a hack and have duplicate game codes use the crc?

Like, it's DRY and the default is something which you don't need to update over and over again, while at the same time making allowances for the 'problem children'.

**Comment by refractionpcsx2** [comment]
PCSX2 only sends one value to the GS, at the moment that is a CRC.  To send the CRC only in cases of duplication would mean maintaining a list of games which are duplicates, but we don't know what all of those are, we only know a select few.

Also in cases where the game serial is different but the CRC is the same because they used the same code on a different region, it would mean using multiple hacks for the same game, further cluttering up the list.

**Comment by gregory38** [comment]
It isn't the first report about this game. I don't know if we can find a better alternative. Maybe we could send both the CRC and the serial. Maybe extend the game DB (which is already too big for git) and make GSdx query it. Honestly I don't know but the situation is far from ideal here.

**Comment by orbea** [comment]
I'm not sure if this will lead to anything, but given your explanation it sounds more like a game issue than pcsx2 issue so I reported the problem to the Project Metafalica forum. With luck they may be able to figure something out for future versions of the patch. :)

http://w11.zetaboards.com/Revatail_Hymmne/single/?p=10004282&t=30116416
http://w11.zetaboards.com/Revatail_Hymmne/topic/30116416/1/

**Comment by gregory38** [comment]
It is legal on the GS to do that. So I won't call it game issue. It is however not compatible with standard GPU that have a fixed width framebuffer. But yes, we could imagine a hack on the game that provide the good dimensions (and the good FBW == frame buffer width value)

**Comment by Soukyuu** [comment]
I actually discussed this with @gregory38 in issue #1362 and I was told to report the final CRC once the final patch is released - which it is now. If you don't want to risk it breaking again should we update the patch (rather unlikely to happen anyway), maybe a functionality to allow loading CRC hacks externally could be added? Then we could ship a file that enables the hack for the current patch version ourselves.

**Comment by gregory38** [comment]
@Soukyuu @orbea so do we have a final CRC ? There is way to load external CRC. It was never tested on Linux (at least nobody report it to me) and it isn't built by default.

**Comment by orbea** [comment]
@gregory38 

I have been using this patch locally to avoid the issue, I think this should be the final crc for version 1.0 of the US patch. I haven't tried the patches for the PAL version or the undub.
```
diff --git a/plugins/GSdx/GSCrc.cpp b/plugins/GSdx/GSCrc.cpp
index 4af4ea80b..5b6b1c367 100644
--- a/plugins/GSdx/GSCrc.cpp
+++ b/plugins/GSdx/GSCrc.cpp
@@ -29,6 +29,7 @@ CRC::Game CRC::m_games[] =
 	{0xF46142D3, ArTonelico2, NoRegion, 0},
 	{0xF95F37EE, ArTonelico2, US, 0},
 	{0xCE2C1DBF, ArTonelico2, EU, 0},
+	{0xC38067F4, ArTonelico2, US, 0}, // project metafalica 1.0
 	{0x2113EA2E, MetalSlug6, JP, 0},
 	{0x42E05BAF, TomoyoAfter, JP, PointListPalette},
 	{0x7800DC84, Clannad, JP, PointListPalette},
```

**Comment by i30817** [comment]
You should reach out on the forums asking for the crc of the undub and patched pal versions too.

**Comment by sudonim1** [comment]
@refractionpcsx2 wait what? I'm not aware of any sony part number conflicts, but in any case it would be an API change and if changing the API it should be to part number + CRC like the database.

**Comment by Soukyuu** [comment]
@gregory38: sorry, I don't have access to a PC at the moment, so I can't check the crc. It is final, though. All three patches for the different game versions (EU, US, undub) result in the same iso, so the crc is the same as well.

**Comment by refractionpcsx2** [comment]
> @refractionpcsx2 wait what? I'm not aware of any sony part number conflicts, but in any case it would be an API change and if changing the API it should be to part number + CRC like the database.

Yeah I can't remember what it was, but there was something, i suspect demo discs might be a culprit of this, but I can't remember, plus the old PBPX thing..

**Comment by gregory38** [comment]
@Soukyuu confirm me the value of orbea. And I will add it or better ask orbea to do a PR ;)
