### ISSUE TITLE
Request: Move OSD Configuration?

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1773]
Currently osd configuration is located within GSdx settings which is an odd place for it if you ask me and doesn't fit considering what the other settings do.

Isn't it better to move it to the "GS" or "GS Window" tab in "emulation settings"?

**Comment by FlatOutPS2** [comment]
The OSD is not part of the PCSX2 core, it's part of the GSdx plugin. It prints to the GSdx window just like the PS2 graphics. So, no, it wouldn't fit better in emulation settings.
