### ISSUE TITLE
The Suffering Ties That Bind: Shadow corruption when GsCaptureDlg is called (F12)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1774]
***PCSX2 version:***
pcsx2-v1.5.0-dev-1799

***PCSX2 options:***
Defaults

***Plugins used:***
Default, OGL HW

***Description of the issue:***
While moving the character/at certain camera angles, dynamic shadows will be rendered incorrectly at the edge of the held weapon. The glitch is only present in OGL HW renderer, OGL SW/Dx had no issues.

***How to reproduce the issue:***
Start the game, play the game through to the intro sequence (where the player is restrained) look at the ground.

***Last known version to work:***
Unknown

[GS Dump](https://github.com/PCSX2/pcsx2/files/707053/TSTTB_shadowglitch.pdf) (rename to .7z)

***PC specifications:***
Intel Core i5-6600k@4.7GHZ, NVIDIA GTX 1070 8GB, Windows 10 64-bit

![gsdx_20170115195708](https://cloud.githubusercontent.com/assets/16314399/21967963/8aeadd4a-db5d-11e6-9e48-ce904f3cf7f6.png)
![gsdx_20170115200708](https://cloud.githubusercontent.com/assets/16314399/21968039/389361e2-db5e-11e6-8c24-c2a5fcda9ef1.png)
![gsdx_20170115195029](https://cloud.githubusercontent.com/assets/16314399/21967973/98460d48-db5d-11e6-8c8d-fcb41da616c7.png)

**Comment by FlatOutPS2** [comment]
Did you check the dump yourself? The shadow in the GS Dump looks the same with all renderers.

**Comment by MrCK1** [comment]
I didn't check the dump, but are you saying the issue is visible in all renderers or not at all?

**Comment by FlatOutPS2** [comment]
Not at all. The shadow of the weapon seems to end rather abruptly. I'm not sure that's the same on PS2, but it doesn't have spike from the images you posted here.

**Comment by MrCK1** [comment]
I just checked the dump - I see what you mean. I'll get another capture on Friday when I have access my main PC.

**Comment by FlatOutPS2** [comment]
> I just checked the dump - for some reason I can't view it with the OGL renderer - I just get a crash message.

Intel iGPU?

> Off-topic, but it seems like the GS thumbnail does not accurately represent the data from the dump. It looks like the thumbnail is captured from the PCSX2 output. Would it be possible to use the 1st frame of the GS dump to generate the thumbnail? Maybe this behavior could be improved/changed in the future?

Yes, it captures a regular snapshot before the dump starts. I made a dump of a game with a milisecond timer on screen a while ago and there's at least 3-4 frames delay between the contents of the dump and the accompanying snapshot.

**Comment by MrCK1** [comment]
No issues now, I forgot I was using my laptop :p

**Comment by FlatOutPS2** [comment]
@MrCK1 Any update on the issue or the gs dump result with the OGL renderer?

**Comment by MrCK1** [comment]
I haven't gotten around to checking. I'll take a look this weekend when I have access to my desktop. 

The issue probably hasn't changed. Last time I checked, the game still has a few missing effects, half-screen issue with certain post-effect, missing sun shadows cast from windows, and a display register size issue in all 3 renderers.

**Comment by FlatOutPS2** [comment]
> The issue probably hasn't changed. Last time I checked, the game still has a few missing effects, half-screen issue with certain post-effect, missing sun shadows cast from windows, and a display register size issue in all 3 renderers.

The issue has probably not changed, but the GS dump didn't show the issue or didn't show any difference between renderers(at least on my end).

**Comment by MrCK1** [comment]
@FlatOutPS2 The shadows aren't bugged anymore, but I've discovered a new problem in all renderers. During certain sequences of the game - which I believe involves render targets. the screen will flicker in HW mode; but SW displays garbage.

[GS Dumps](https://github.com/PCSX2/pcsx2/files/784509/TSTTB_GSdxGarbage.pdf) from both OGL renderers (rename to .7z)

SW Renderer
![gsdx_20170217173854](https://cloud.githubusercontent.com/assets/16314399/23085894/4de49b26-f538-11e6-9341-f7fa0c7cc4e5.png)

HW Renderer (I couldn't capture it properly so I slapped this together in MS paint ;P)
![tsttb_hwbugged](https://cloud.githubusercontent.com/assets/16314399/23085920/7815659c-f538-11e6-9d7e-1d79f62f706a.png)
This is the other half of what you see in HW renderer (it flickers between these the two "frames")
![gsdx_20170217173937](https://cloud.githubusercontent.com/assets/16314399/23086007/c83d92ec-f538-11e6-8bb8-ace90e096424.png)

**Comment by FlatOutPS2** [comment]
Toasty! 

I can see the issue in the dumps, it seems there's also some texture flickering on the TV screen.

**Comment by MrCK1** [comment]
@FlatOutPS2 I did some more investigating into the original shadow issue. It turns out instead that the glitch is "toggled" on and off every time the GSCaptureDlg is called, so I guess it might be a GS rounding issue. Here's another dump where the glitch is actually present, only OGL HW was affected in the dump 😛 

[TSTTB_shadowglitchrevised.pdf](https://github.com/PCSX2/pcsx2/files/805777/TSTTB_shadowglitchrevised.pdf) (rename to .7z)

**Comment by MrCK1** [comment]
@FlatOutPS2 I found an interesting issue related to savestate loading that was the cause of the SW corruption I mentioned here (It fits the bill as I was never able to reproduce this). I'm opening an issue for it later.
