### ISSUE TITLE
No sound with portaudio after upgrading to alsa-lib-1.1.3

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1775]
***PCSX2 version:***
`alsa-lib-compat32-1.1.3-x86_64-1compat32`
`portaudio-compat32-v190600_20161030-x86_64-1_SBocompat32`
`pcsx2-2017.01.15_f9c202514_master-x86_64-1_git`

***Plugins used:***
`SPU2-X 2.0.0 [libspu2x-2.0.0]`

***Description of the issue:***
After Slackware current upgraded to `alsa-lib-1.1.3` from `alsa-lib-1.1.2` and when using the portaudio module PCSX2 will do one of two things.
1. Games will have no audio.
2. Games will start with audio, but after a minute at most audio will suddenly die.

PCSX2 will now hang for a little while when trying to shutdown games.

The SDL2 audio module has no issues and downgrading to `alsa-lib-1.1.2` will allow audio to work again.
I also do not have pulseaudio installed so this happens with just alsa.

I am not sure if this is a pcsx2, portaudio or alsa issue, but hopefully starting here will at least help narrow it down. Is there anything else that can be useful to debug this?

***How to reproduce the issue:***
1. Install `alsa-lib-1.1.3`.
2. Start a game with the portaudio module.

***PC specifications:***
OS: `Slackware64-current`

**Comment by orbea** [comment]
As a sanity check I compiled alsa-lib-1.1.3 from source instead of using the slackware packages and was able to reproduce the issue. I do not have any other programs which I can really test portaudio with though.

For reference here is the alsa-lib v1.1.2 to v1.1.3 changelog.
http://www.alsa-project.org/main/index.php/Changes_v1.1.2_v1.1.3

**Comment by gregory38** [comment]
Well the issue is likely alsa or portaudio. Need to search on Google if projects got done issues. (Unfortunately Alsa 1.1.3 is quite young)

**Comment by gregory38** [comment]
https://github.com/JvanKatwijk/sdr-j-dab/issues/9

Could you check the env variable of the thread ?

**Comment by np511** [comment]
On Monday, January 16, 2017 11:59:59 AM EST Gregory Hainaut wrote:

> https://github.com/JvanKatwijk/sdr-j-dab/issues/9

>

> Could you check the env variable of the thread ?

If it is alsa or portaudio, why not try with PortAudio using a different backend?

**Comment by np511** [comment]
On Monday, January 16, 2017 11:59:59 AM EST Gregory Hainaut wrote:

> https://github.com/JvanKatwijk/sdr-j-dab/issues/9

>

> Could you check the env variable of the thread ?

Never mind;just reread the earlier post.

**Comment by orbea** [comment]
`LIBASOUND_THREAD_SAFE=0` makes no difference here. I will have to find where the alsa and / or portaudio developers expect bug reports and show them this issue.

**Comment by orbea** [comment]
__alsa-info.sh__
http://pastebin.com/zhwStRa4

http://alsa-project.org/main/index.php/AlsaInfo

**Comment by gregory38** [comment]
@orbea do you have more info ?  Tbh, I will advice you to use SDL2.

**Comment by orbea** [comment]
@gregory38 Sorry, no more info yet. I did opt to use SDL2 instead which works fine. I been meaning to bisect alsa-lib to find when this started, but I haven't gotten to it yet...

**Comment by orbea** [comment]
This problem seems resolved using alsa-lib-1.1.4.1. However there is now a significant audio performance difference with SDL2 vs portaudio, where SDL2 works seemlessly, portaudio will start stuttering for a while every few mins.

**Comment by mirh** [comment]
Is it still a thing?

**Comment by orbea** [comment]
Yes and no...

With pcsx2 commit fc1d9ae and `alsa-lib-1.1.6` sound now works with portaudio, but its significantly worse and unplayable compared to SDL2 with lots of audio stuttering.

**Comment by orbea** [comment]
With pcsx2 commit e2d8992, `alsa-lib-1.1.9` and at least two games this seems completely fixed so I am going to close this.
