### ISSUE TITLE
Add GL_ARB_shader_stencil_export support to handle accurate DATE

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1779]
Extension description: https://www.opengl.org/registry/specs/ARB/shader_stencil_export.txt
* Allow to write the stencil reference value from the shader.
* So we can directly write the alpha value in the stencil. It can be done with a single draw call for complex case (+ likely an extra draw call for the init)

Supported GPU:
* Recent Intel (gen9+), I think it mean skylake or newer
* Recent AMD
* Good news, Mesa supports it on the software renderer (so it can be implemented/tested on my Nvidia GPU)

Limitation:
* Another code path for DATE
* Will be deprecated by GL_ARB_fragment_shader_interlock (but I don't have the HW to implement it)

**Comment by refractionpcsx2** [comment]
Does this actually work on AMD cards? :P

**Comment by gregory38** [comment]
:rofl:  Don't be jealous ;)

**Comment by refractionpcsx2** [comment]
I'm not jealous, I don't own an AMD card, it was more of a mocking :P

**Comment by gregory38** [comment]
I know. But you ought to be jealous. I'm pretty sure it can provide a massive speed boost on scene that used complex DATE rendering. Anyway it isn't my priority but it could be a nice addition. (and maybe future Nvidia hardware will support it one day).

**Comment by mirh** [comment]
> Supported GPU: Recent

Don't you just need OGL [4.1](http://www.geeks3d.com/20101022/ati-catalyst-10-10a-hotfix-adds-opengl-4-1-support-and-9-new-extensions/) hardware?

> Will be deprecated by GL_ARB_fragment_shader_interlock

[Nvidia](http://www.geeks3d.com/20150817/nvidia-r355-58-with-opengl-2015-extensions/) and [intel](https://twitter.com/g_truc/status/638730864147476480) have it, but amd and mesa are a big mystery 😋 

> I'm not jealous, I don't own an AMD card, it was more of a mocking :P

Seriously, that was my first question too.

**Comment by FlatOutPS2** [comment]
> Seriously, that was my first question too.

We won't have an accurate answer until it's been applied.

**Comment by gregory38** [comment]
Nvidia only support it for Maxwell GPU and later. I will upgrade my GPU to a XX50 card when we have GDDR5X (or similar) and an available firmware for the free driver. Until then, don't hold you breath. It isn't implemented in Mesa currently.  Maybe they will implement it in their software renderer.

I don't know which AMD card support it. I think all DX12 class GPU are fine. Maybe all DX11 class GPU. @FlatOutPS2 do you have it in your driver ? Anyway, extension will remain optional. It is only a way to accelerate the shadow rendering of some games. Code is already optimized to use various fast path.

**Comment by FlatOutPS2** [comment]
GL_ARB_shader_stencil_export is supported by my driver, GL_ARB_fragment_shader_interlock is not. :P

**Comment by gregory38** [comment]
Yes interlock is a long term future.

**Comment by lightningterror** [comment]
Question , how to check if it's supported or not ?

**Comment by mirh** [comment]
As I linked, it's already supported. And if it's just an extension to 4.5 I'd expect everything from Haswell above to support it at least on linux one day. 

You can check with [gpu caps viewer](http://www.ozone3d.net/gpu_caps_viewer/) or [gl caps viewer](http://opengl.gpuinfo.org/download.php)

**Comment by gregory38** [comment]
No you don't understand the meaning of extensions. All gl features are extensions of a spec. From time to time, some of them are grouped together below a marketing number (therefore it is mandatory to implement them if you want to put the sticker on the box). To avoid marketing issue, some ARB extensions aren't linked to any marketing number. This way there are really optional. 

Intel Linux implementation requires gen9. So I don't think haswell will get it. Anyway, so far it is only something that worth an investigation. It might not work as expected, or it could be slower.

**Comment by gregory38** [comment]
Unfortunately I was confused with the other extension `AMD_shader_stencil_value_export.txt`

And even with the latter I'm not sure it is doable. We need something to change the value of the next stencil test not the current one (my main misunderstanding) which is useless.

Sorry for the hope.

**Comment by mirh** [comment]
> Intel Linux implementation requires gen9. So I don't think haswell will get it.

Well surprise surprise https://github.com/mesa3d/mesa/commit/939312702e35928770e5f90f7b053ece3d10e7ae#diff-d59cd5f9d5db0eb2f923d478a2cf1e17R224
🙃
