### ISSUE TITLE
The latest build is broken

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [PCSX2/pcsx2#1780]
Version: The lastest snapshot; 
OS: GNU\Linux Debian 8; 
I5 + Intel HD + Nvidia Geforce 520M;

Build params: cmake CmakeLists.txt -DCMAKE_BUILD_TYPE=Release -DPACKAGE_MODE=TRUE -DCMAKE_BUILD_STRIP=TRUE -DEXTRA_PLUGINS=TRUE -DSDL2_API=TRUE -DGLSL_API=TRUE -DEGL_API=FALSE -DGTK3_API=FALSE -DUSE_VTUNE=FALSE
make -j5
Error:
Opening GS
Current Renderer: OpenGL (Hardware mode)
glX-Version 1.4 with Direct Rendering
Failed to find glCreateQueries
Failed to find glCreateTextures
Closing plugins...

Build params: -/- -DEGL_API=TRUE  -DGLSL_API=FALSE
Error: Crash at boot anything...

**Comment by gregory38** [comment]
Don't use the extra plugin. Did you build yourself? Your Nvidia driver seems to be wrongly installed.

**Comment by Yrij-Zhavoronkov** [comment]
Don't use the extra plugin.  -- ok
Did you build yourself?  --yes
Your Nvidia driver seems to be wrongly installed.   why??  - other application works!

**Comment by gregory38** [comment]
Because I saw some openGL error. Do you have a legacy driver ? Or full openGL 4.5 support ?

**Comment by Yrij-Zhavoronkov** [comment]
Already 4.5?  4.4.0 NVIDIA 340.101.
And please.... dec the opengl version fo capability

**Comment by Yrij-Zhavoronkov** [comment]
Driver from Debian repository

**Comment by Yrij-Zhavoronkov** [comment]
Upgrade your driver.   This is the lastest version in Stable repository
Or use an older GSdx... how?
legacy GSdx isn't contain in extra plugins)

**Comment by gregory38** [comment]
There is jessie backport which contains 375.26-1~bpo8+1
Don't build latest master but build the 1.4.x branch 
You're right you need the option `-DGSDX_LEGACY=TRUE`

**Comment by Yrij-Zhavoronkov** [comment]
There is jessie backport which contains 375.26-1~bpo8+1 
Ussialy, after inststall anything on backport  i hame some bugs.. so no)
-DGSDX_LEGACY=TRUE .... i try it)

**Comment by Yrij-Zhavoronkov** [comment]
It's work!)  
http://radikal.ru/lfp/s19.radikal.ru/i192/1701/ed/ecf78ff4a8bdt.jpg/htm
