### ISSUE TITLE
Crash Tag Team Racing - microvu1: Program cache limit reached 

### ISSUE THREAD

**Issue by ghostravenstorm** [PCSX2/pcsx2#1785]
***PCSX2 version:***
1.4.0 and 1.5.0 dev 1803 g253057a

***PCSX2 options:***
default setup

***Plugins used:***
default plugins

***Description of the issue:***
Memory leak during gameplay causing the emulator to slowdown, halt unexpectedly for a few seconds, resume normally for a few minutes, then rinse, lather, and repeat. Gameplay is fine during races; problem only occurs while in third person adventure mode.

***How to reproduce the issue:***
Walk around in third person through the various zones, jumping on platforms, etc.

***Last known version to work:***
N/A

***PC specifications:***
Intel 2600K CPU, nVidia GTX 770, Windows 8.1 x64

**Comment by gregory38** [comment]
It isn't a memory leak. It is the normal behavior of recompiler when the PS2 program is updated every run.

**Comment by 15joeybloom** [comment]
Hey, I just wanted to drop in and say I have been experiencing this same issue with crash tag team racing. Crazy!
