### ISSUE TITLE
Silent hill 2 videos problem

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#1787]
***PCSX2 version:***
1.5 dev 1814-g21612ca

- **Note**: It's preferred to only report bugs which are present on the [latest development builds]
All ingame videos are unplayable "White flickering" unless you use software mode (Tested with all hardware video backends)

***PC specifications:***
i7 4790k 4,4ghz
16GB DDR3
GTX 970

**Comment by MrCK1** [comment]
What exactly is the issue here? Could you add more information?

**Comment by LuismaSP89** [comment]
[1.zip](https://github.com/PCSX2/pcsx2/files/725037/1.zip)

Here you can see a video of the problem "Captured with the F12 function of pcsx2 in (VfW) x264vfw -H.264 video format" (I put the extension .mkv to open it)

**Comment by FlatOutPS2** [comment]
Go to Config > Video (GS) > Plugin Settings, make sure Renderer is set to "OpenGL (Hardware)", turn on "Enable HW Hacks", go to Configure Hacks and enable the "Unscale Point Line" hack.

**Comment by LuismaSP89** [comment]
Yes, it works, a little pixelated, but it works. Thanks a lot. 

I see too the other option to enable always the software mode in the FMVs... is there a way for PCSX2 programmers to include this by default depending on the game that you´re playing? (Like the dolphin emulator does, with a database of default options per game)
