### ISSUE TITLE
Legacy of Kain Soul Reaver 2 Widescreen Hack Not Working

### ISSUE THREAD

**Issue by WizLizard** [PCSX2/pcsx2#1789]
PCSX2 version tested
pcsx2-v1.5.0-dev-1832-g5c7c945

Tested with default settings and tried every plugin. Widescreen hacks are working for all other games. Just try the game with the widescreen hack on and the game will remain stretched. I believe it was working on 1.4.0 stable but not sure. I know for a fact it works on 1.2.1. 

PC specifications:
i7 4790k
GTX 980
32gb ddr3

**Comment by FlatOutPS2** [comment]
The hack was removed as it was work in progress(it's wasn't wide enough for full widescreen). You can manually copy the old patch from the 1.2.1/1.4 releases if you want though. The PCSX2 team does not make the widescreen patches, so you'll need go to the appropriate thread on the forum (forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches) if you want further support.
