### ISSUE TITLE
Pressing Alt+Tab disables binded save loading.

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1797]
***PCSX2 version:***
pcsx2-v1.5.0-dev-1749-g9d1b27c-windows-x86

***PCSX2 options:***
Everything is default, except the "PCSX2_keys.ini"

***Description of the issue:***
If you press Alt+Tab to switch to another screen, then loading a save state through a bound key gets disabled while the emulator is running.

***How to reproduce the issue:***
This has been happening ever since I started using the emulator, but I could never figure out why it happened. But I finally found out today.
I have save state saving/loading to F2/F4. But whenever you press Alt+Tab to switch to another window, and then come back to the emulator, you can no longer load the save state through the bound key if the emulator is active. If the emulator is _paused_, then the bound save load works. (It also works if you load through the menu too.) 

I attached my ini just in case that is causing the issue.

[PCSX2_keys.zip](https://github.com/PCSX2/pcsx2/files/737877/PCSX2_keys.zip)

**Comment by FlatOutPS2** [comment]
It's not your ini. The same thing happens to the F4 key with default settings. After you alt-tab the F4 key no longer functions for its assigned purpose.

**Comment by Hirato** [comment]
Just tap that same alt button again.
It gets stuck in the PRESSED state because it doesn't get the RELEASE event because of the focus switch.
