### ISSUE TITLE
Buzz buzzers don't work!

### ISSUE THREAD

**Issue by fabioneves** [PCSX2/pcsx2#1802]
***PCSX2 version:***
Dev build 1.5-1875

***PCSX2 options:***
Everything default

***Plugins used:***
USBqemu

***Description of the issue:***
Buzz buzzers don't work! Nothing show up to select the device.
![issue](http://i.imgur.com/YNRTpve.png)

***How to reproduce the issue:***
Just connect the buzzers, they don't show up in USBqemu to select.

***PC specifications:***
OS: Windows 10 64 Bit

**Comment by FlatOutPS2** [comment]
The USBqemu plugin that comes with PCSX2 is basically a template that doesn't do anything. It should not be included in the builds.

To use the Buzz buzzers you'll need a special plugin. There is one, but it doesn't seem to work well, especially with newer PCSX2 versions: http://forums.pcsx2.net/Thread-USBqemu-Buzz-New-Release?highlight=buzzer

**Comment by fabioneves** [comment]
I got it to work with the plugin in this post:
http://forums.pcsx2.net/Thread-USBqemu-Buzz-New-Release?pid=369335#pid369335
