### ISSUE TITLE
Graphical issues with Blending Unit Accuracy and Devil May Cry

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1805]
***PCSX2 version:***
`pcsx2-2017.02.01_23d081ab2_master-x86_64-1_git`

***PCSX2 options:***
Occurs with or without all hacks disabled. The graphical noise will go away with the software rendering or if the `Blending Unit Accuracy` is set to `None (fastest)`.

***Plugins used:***
`GSdx (GCC 5.4.0 AVX/AVX) 1.1.0 [libGSdx]`

***Description of the issue:***
The game Devil May Cry will have excessive graphical noise on the bottom and top of the screen where the widescreen black borders are, this only occurs with OpenGL hardware rendering and the `Blending Unit Accuracy` enabled, it does not happen with software rendering.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/pcsx2/gsdx_20170206125313_(16).png)

GSDX dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_20170206125311_devil_may_cry.gs.xz

***How to reproduce the issue:***
1. Enable OpenGL Hardware Rendering
2. Enable `Blending Unit Accuracty` to any level.
3. Start a new game in Devil May Cry and skip the first cut scene with the select button.

***Last known version to work:***
I've tried commits back to August of 2016 and they all had the problem.

***PC specifications:***
CPU: `AMD 6350 FX` 
GPU: `GTX 780Ti` 
OS: `Slackware64-current`

**Comment by FlatOutPS2** [comment]
I cannot reproduce this issue on Windows with the dump and I haven't seen the issue when playing the game since last August either.

**Comment by orbea** [comment]
This is potentially something that occurs with only mesa or even certain mesa drivers? Unfortunately I don't have much else I can test with currently.

**Comment by gregory38** [comment]
@orbea mesa => nouveau ? Which mesa version ?

**Comment by orbea** [comment]
Yea, nouveau. I am currently using `mesa-2017.01.25_7c5629a269_master-x86_64-1_git`. I can try additional mesa commits if need be.

**Comment by gregory38** [comment]
I have the same issue on the older Debian version. I generated two small apitrace trace to compare the behavior. It smells fishy. 

I spot a wrong draw call (which read back the frame buffer), however I'm not sure accurate blending impact it directly. BUA mostly inserts glTextureBarrier for synchronization and split multiple-primitives draw call into multiple single-primitive draw calls. I suspect it creates some "delays" that lead to either a missing synchronization or invalid data in cache.

**Comment by gregory38** [comment]
I have a fix. I will push it in coming days (or maybe tonight).

**Comment by orbea** [comment]
Great! I haven't had a chance to try older mesa yet, but I guess I can just wait to test your fix when you have time to push it. :)

**Comment by gregory38** [comment]
Fix pushed.

**Comment by orbea** [comment]
Its fixed here too, thanks!
