### ISSUE TITLE
Graphical Corruption in Valkyrie Profile 2: Silmeria

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1809]
***PCSX2 version:***
`pcsx2-2017.02.08_213fa1c14_master-x86_64-1_git`
`mesa-compat32-2017.01.25_7c5629a269_master-x86_64-1_gitcompat32`

***PCSX2 options:***
Most options do not seem to affect it except for the user hacks `Disable Depth Emulation` and to a lesser extent `Preload Frame`.

***Plugins used:***
`GSdx (GCC 5.4.0 SSE2/AVX) 1.1.0 [libGSdx]`

***Description of the issue:***
In the game Valkyrie Profile 2: Silmeria when entering the Lost Forest at the beginning of the game there will be graphical corruption or artifacts throughout the center of the screen. This only occurs with the OpenGL renderer and not the software renderer. 

Additionally the user hack `Disable Depth Emulation` will produce a red screen in the area except for the minimap in the top left. After moving around back and forth for a while the red screen will either turn into big red dots or vanish, the graphical corruption with it. The hack `Preload Frame` will speed up the process in some places and corrupt the big red dots caused by `Disable Depth Emulation`.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/pcsx2/gsdx_20170208143829_valkyrie_profile_2.png)

GSDX dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_20170208143828_Valkyrie_Profile_2.gs.xz

***How to reproduce the issue:***
1. Start Valkyrie Profile 2 with the OpenGL Renderer.
2. Proceed through the first few cutscenes and the town until the forest at the beginning of the game.

***Last known version to work:***
I tried builds back to August of 2016 and did not find any that work, however newer builds are significantly faster with this game. Testing older builds is almost impossible while the game is now full speed or nearly full speed. :)

***PC specifications:***
CPU: `AMD 6350 FX`
GPU: `GTX 780Ti`
OS: `Slackware64-current`

**Comment by gregory38** [comment]
FWIW, `Disable Depth Emulation` means `I don't care about graphical glitches (due to missing depth effect emulation) but I want speed for my slow PC`

```
Testing older builds is almost impossible while the game is now full speed or nearly full speed. 
```
No. It is only the CRC level behavior. Put it on full and you will get the full speed.

**Comment by lightningterror** [comment]
The red screen is a depth effect which is not supported on D3D.
The other issue (horizontal and vertical lines) is similar to Tekken5 that has horizontal and vertical lines on the Moon stage which is an upscaling issue.

**Comment by orbea** [comment]
This was with OpenGL and native resolution.

**Comment by trostboot** [comment]
I can't confirm any graphical corruption with standard settings (obviously disabling depth emulation breaks stuff) at native resolution with OpenGL HW. Shadows are skipped via CRC on HW, but aside from that, output is near identical between SW and HW.

This on Win10 with a nvidia GPU as well.

**Comment by lightningterror** [comment]
People shouldn't disable Hardware Depth unless there are specific depth issues.

Or if you prefer to use higher level crc hacks over accuracy for more speed.

**Comment by lightningterror** [comment]
Shadows will work fine now on OpenGL, aside from that I will close this as it is an upscaling issue which is a general issue.
