### ISSUE TITLE
shin megami tensei games no longer need ee timing hack

### ISSUE THREAD

**Issue by KousukeItsagame** [PCSX2/pcsx2#1811]
***PCSX2 version:***
1.4.0

***PCSX2 options:***
ee timing hack

***Description of the issue:***
ee timing hack is no longer needed with shin megami tensei games
(digital devil saga 1 and digital devil saga 2 tested) probably persona 3 too and other games this hack applied to.
without disabling the hack game freeze at random intervals

***PC specifications:***
CPU: Intel i5 3470: amd r9 285 OS: Windows 10 64 Bit)``

**Comment by FlatOutPS2** [comment]
So the games now freeze with the gamefix enabled?

**Comment by KousukeItsagame** [comment]
yes, since the reboot of pcsx 2 actually,

**Comment by KousukeItsagame** [comment]
but then they didn't work without the hack
now they do :)

**Comment by ramapcsx2** [comment]
Okay, removed the hack from the database.
Please do tell us if you notice hanging again and the hack "re-fixes" it.

Commit with the removal:
f86ea9f19bd58f24271a5864e4b19ea7f6bc90e7

**Comment by ssakash** [comment]
> but then they didn't work without the hack
now they do :)

It would be nice to know on which commit caused this behavior.

**Comment by ramapcsx2** [comment]
I assume one of the core timing changes did this. It's probably a fortunate accident.

**Comment by FlatOutPS2** [comment]
It is only one user reporting this, so it might not work with all versions. Or, as it a random freeze issue, it might now just freeze at other/fewer intervals and the user was just lucky. We have very little to go on.

**Comment by refractionpcsx2** [comment]
I wonder when this was fixed (if it was), because none of the stuff which causes it has been touched in ages and last time i tested it (a few months back) it was still freezing.

**Comment by KousukeItsagame** [comment]
the ee timing hack worked for me in pcsx2 0.9.8
later releases had random freezes when ee timing hack was enabled
As you said it could be hardware related or a single case situation.
I'm going to test once more since I did hardware changes since then.

**Comment by KousukeItsagame** [comment]
pcsx 1.2.1 the ee timing hack doesn't work

**Comment by ramapcsx2** [comment]
We need to know about the current development version status. If the game hangs on this, and the EE timing hack fixes it, we need to put it back in.

**Comment by KousukeItsagame** [comment]
I can't confirm it. so I would leave it for now as it is

**Comment by KousukeItsagame** [comment]
My pc is acting funny :p

**Comment by ramapcsx2** [comment]
Okay. I read into your report that you played the game recently (or playing it at this time) and are using the latest development versions. I disabled the automatic gamefix based on that. If this is an error, then I will undo it.

**Comment by ramapcsx2** [comment]
@KousukeItsagame I just need to know if you'd rather revert the EE timing change, or not. 
It's no big deal to revert it but I need to know which it is: Keep or revert ;)

**Comment by FlatOutPS2** [comment]
I'd say keep it as it is now until we get a confirmation which is correct.

**Comment by ramapcsx2** [comment]
Okay. This will teach me not to act on single reports so quickly. Especially for timing hacks. Removing those is just too tempting ;p
