### ISSUE TITLE
Support llvmpipe on windows. Works around #345 and #1716

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#1813]
***PCSX2 options:***
``All default, Gsdx OpenGL (mainly software, hardware would be too slow)``

***Plugins used:***
``All default. Gsdx SSE4.1. AVX2 not supported by CPU.``

***Description of the issue:***
``Gsdx fails to initialize. It cannot create GL 3.x context. It appears GSdx cannot detect Core profile at all:``

```
PCSX2 1.5.0-20170208194254 - compiled on Feb  9 2017
Savestate version: 0x9a0d0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 14393), 64-bit
	Physical RAM     =  3975 MB
	CPU name         =  Intel(R) Core(TM) i3-2375M CPU @ 1.50GHz
	Vendor/Model     =  GenuineIntel (stepping 07)
	CPU speed        =  1.496 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 1dbae3bf
	x86EFlags        =  28100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Reserving memory for recompilers...

Loading plugins...
	Binding   GS: C:\Software\Development\projects\pcsx2\bin\plugins\GSdx32-SSE4.dll 
	Binding  PAD: C:\Software\Development\projects\pcsx2\bin\plugins\LilyPad.dll 
	Binding SPU2: C:\Software\Development\projects\pcsx2\bin\plugins\Spu2-X.dll 
	Binding CDVD: C:\Software\Development\projects\pcsx2\bin\plugins\cdvdGigaherz.dll 
	Binding  USB: C:\Software\Development\projects\pcsx2\bin\plugins\USBnull.dll 
	Binding   FW: C:\Software\Development\projects\pcsx2\bin\plugins\FWnull.dll 
	Binding DEV9: C:\Software\Development\projects\pcsx2\bin\plugins\DEV9null.dll 
Plugins loaded successfully.

(GameDB) 9709 games on record (loaded in 455ms)
HLE Notice: ELF does not have a path.


Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
Current Renderer: OpenGL (Software mode)
Failed to create a 3.x context
OpenGL information. GPU: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits). Vendor: VMware, Inc.. Driver: (Core Profile) Mesa 17.0.0-rc3
INFO: GL_EXT_texture_filter_anisotropic is NOT SUPPORTED
INFO: GL_ARB_gpu_shader5 is NOT SUPPORTED
INFO: GL_ARB_viewport_array is NOT SUPPORTED
ERROR: GL_ARB_separate_shader_objects is NOT SUPPORTED
INFO: GL_ARB_shader_image_load_store is NOT SUPPORTED
ERROR: GL_ARB_shading_language_420pack is NOT SUPPORTED
ERROR: GL_ARB_texture_storage is NOT SUPPORTED
ERROR: GL_ARB_copy_image is NOT SUPPORTED
ERROR: GL_KHR_debug is NOT SUPPORTED
ERROR: GL_ARB_buffer_storage is NOT SUPPORTED
INFO: GL_ARB_clear_texture is NOT SUPPORTED
ERROR: GL_ARB_clip_control is NOT SUPPORTED
ERROR: GL_ARB_direct_state_access is NOT SUPPORTED
INFO: GL_ARB_texture_barrier is NOT SUPPORTED
INFO: GL_ARB_get_texture_sub_image is NOT SUPPORTED

GL_ARB_viewport_array: not supported ! function pointer will be replaced
GL_ARB_texture_barrier: not supported ! Rendering will be corrupted
	Opening CDVD
isoFile open ok: C:\Software\pcsx2\storage\isos\Final Fantasy X (USA).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (2201280 sectors)
	Opening USB
	Opening FW
	Opening DEV9
Current Renderer: OpenGL (Software mode)
Error: GLLoader failed to get GL version
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
(pxActionEvent) GS plugin failed to open!(thread:MTGS)(thread:EE Core)
User-canceled plugin configuration after plugin initialization failure.  Plugins unloaded.

```

***How to reproduce the issue:***
``Just attempt to boot anything, BIOS included.``

***Last known version to work:***
``Probably never``

***PC specifications:***
``CPU: Intel Core i3-2375m GPU:  Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits). Vendor: VMware, Inc.. Driver: (Core Profile) Mesa 17.0.0-rc3; OS: Windows 10 64 Bit)``

PPSSPP doesn't have this issue. Here is a screenshot with PPSSPP detecting one of those missing extensions:
https://www.dropbox.com/s/zkfx9u4fe0cz7fx/llvmpipe-win.jpg?dl=0
Tested llvmpipe 17.0.0-rc3 in PPSSPP and it says it supports  GL_ARB_buffer_storage too. Got the idea for this enhancement after 63944e8 .

**Comment by gregory38** [comment]
The issue is not the extensions but the context flags

**Comment by pal1000** [comment]
Pre-built llvmpipe for windows is available [here](https://github.com/pal1000/mesa-dist-win/blob/master/17.0.0-rc3/x86/opengl32.dll?raw=true)

**Comment by gregory38** [comment]
I will fix the context flags. It will allow openGL under wine too.

However https://mesamatrix.net/ says that  GL_ARB_buffer_storage isn't supported

**Comment by gregory38** [comment]
@pal1000 could you test the PR (if it compiles fine)

**Comment by pal1000** [comment]
Yes, it compiles fine and it even works pretty well.  Tested with Final Fantasy X. MTVU speedhack helps a lot as I expected. Regarding GL_ARB_buffer_storage, I don't know what to say. I created a batch script that sets MESA_EXTENSION_OVERRIDE to an empty string and it still works. PCSX2 doesn't complain about not finding it either. Could it be that mesa matrix missed it somehow.

**Comment by pal1000** [comment]
Actually,  should keep it open until #1814 is merged.

**Comment by pal1000** [comment]
In the meantime I discovered a few llvmpipe specific problems:
1. If it is installed system-wide (see https://www.mesa3d.org/llvmpipe.html under Using - Windows section), Gsdx uses Windows bult-in OpenGL software renderer on first start and obviously fails. Have to retry to get llvmpipe. It might also prevent hardware GPU OpenGL from working, though I don't know for sure because I don't have a dGPU test this scenario.
2. You might get sometimes error (3) Cannot set PixelFormat followed by obvious failure either on start or when resume emulation.
