### ISSUE TITLE
Gsdx confusion with Mesa on Windows - OpenGL driver selection broken logic

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#1817]
***PCSX2 version:***
`v1.5.0-dev-1885-g f86ea9f`

***PCSX2 options:***
``All settings default. ``

***Plugins used:***
``Gsdx OpenGL SSE4.1 both HW and SW``

***Description of the issue:***
``Depending on how mesa is installed Gsdx may attempt to use other OpenGL drivers on first try in a sort of broken logic``

***How to reproduce the issue:***
``Case 1. Mesa is installed system wide as built-in OpenGL software renderer replacement`` per this [documentation](https://www.mesa3d.org/llvmpipe.html) - section Using Windows
Gsdx uses OpenGL implementation of selected adapter on first run. This is perfectly logic, but subsequent runs on same PCSX2 session lead to mesa being used. This happens if OpenGL implementation of selected adapter is not good enough, but it might happen regardless. Don't have good enough hardware to test. Restarting PCSX2 resets this cycle anew.
``Case 2. Gsdx is forced to use mesa by having mesa opengl32.dll present on same folder as pcsx2.exe``
Gsdx uses mesa regardless of the selected adapter as expected, but sometimes it may use or switch for one time to the OpenGL implementation of selected adapter when emulation is resumed from paused state leading to potential progress loss. Reference Device adapter seams to have the highest chances to replicate this glitch.

***Last known version to work:***
``Never``

***Suggestions on how to fix***
- permanently hide OpenGL modes for Reference Device and Microsoft Basic Renderer Driver;
- if at least one of the following conditions is met add an extra adapter, let's call it Mesa OpenGL Adapter having all Direct3D modes hidden:
1. opengl32.dll is present on same folder as pcsx2.exe;
2. Mesa is installed system wide as built-in OpenGL software renderer replacement.
- if condition 1 is met, regardless of condition 2 hide OpenGL modes to all adapters except Mesa OpenGL Adapter.

***PC specifications:***
``CPU: Intel Core I3-2375M GPU: Intel HD Graphics 3000 and Mesa llvmpipe 17.0.0-rc3-LLVM 3.9.1 OS: Windows 10 64 Bit)``

**Comment by gregory38** [comment]
What do you mean by selected device? You mean the GSdx option ? I'm not sure the option is compatible with openGL. We got various hack to select the good GPU for mixed d/iGPU laptop. openGL is really limited here.

**Comment by pal1000** [comment]
Changed device to adapter as that's how is being called in Gsdx Settings.

**Comment by gregory38** [comment]
I think adapter is DX only. I don't have the possibility to chose a device/adapter on openGL. Did you try to copy the DLL in the plugin directory too.

**Comment by pal1000** [comment]
It doesn't find it in plugin directory. Additionally if I remove mesa system wide installation for 32-bit applications it appears that PCSX2 attempts to use the IGPU as I get an error that I don't recall seeing before.
To summarize this is what I get for each mesa case

Case | Outcome
---- | ----------
No mesa installed | Possibly use the iGPU and fail consistently with "Failed to init wglCreateContextAttribsARB function pointer" regardless of what adapter is selected
Mesa installed system wide | Get " (3) Can't set The PixelFormat" on first attempt to boot any game or BIOS. If I retry, it works via mesa regardless of what adapter is selected
Dropped on same folder as pcsx2.exe | It uses mesa since first attempt, but you might get  " (3) Can't set The PixelFormat" when resume emulation and guaranteed when attempting to access Gsdx settings (Config - Video - Plugin settings), potentially leading to progress loss. All regardless of adapter
Mesa installed system wide and dropped on same folder as pcsx2.exe |  It uses mesa since first attempt, but you might get  " (3) Can't set The PixelFormat" when resume emulation and guaranteed when attempting to access Gsdx settings (Config - Video - Plugin settings), potentially leading to progress loss. All regardless of adapter

**Comment by gregory38** [comment]
Do you have a dGPU or only an iGPU ?

**Comment by pal1000** [comment]
Only iGPU.

**Comment by pal1000** [comment]
Updated the table as I can also get "Cannot create 2.0 context" on first run when Mesa is installed system-wide.

**Comment by gregory38** [comment]
Honestly, I'm not even sure it is fixable. I can change the code to retry N times but I think it would fails N times (unlike you're use case, I can't unload and reload the plugin). GSdx asks the driver to provides some gl features and reports an error when not supported. 

However I have an awful context leak. I need to fix some stuffs.

**Comment by pal1000** [comment]
This issue behavior changed after 674d223
Case | Outcome
---- | ----------
No mesa installed | Possibly use the iGPU and fail consistently with "Failed to init wglCreateContextAttribsARB function pointer" regardless of what adapter is selected
Mesa installed system wide | Get these 2 errors in this order: "Failed to create a 2.0 context",
" (3) Can't Set The PixelFormat" on first attempt to boot any game or BIOS. If I retry, it works via mesa regardless of what adapter is selected, No issues when attempting to access Gsdx settings (Config - Video - Plugin settings)
Dropped on same folder as pcsx2.exe | It uses mesa since first attempt, but you might get  " (3) Can't set The PixelFormat" when resume emulation and guaranteed when attempting to access Gsdx settings (Config - Video - Plugin settings), potentially leading to progress loss. All regardless of adapter
Mesa installed system wide and dropped on same folder as pcsx2.exe (normal copy or symbolic link) | Same as in previous case

**Comment by pal1000** [comment]
v1.5.0-dev-1894-g726f9d5 improved this isue as follows:

Case | Outcome
---- | ----------
No mesa installed | Possibly use the iGPU and fail consistently with "Failed to init wglCreateContextAttribsARB function pointer" regardless of what adapter is selected as expected. It is way below requirements
Mesa installed system wide | Get error "Failed to create a 2.0 context" in an error dialog on first attempt to boot any game or BIOS. If I retry, it works via mesa regardless of what adapter is selected, No issues when attempting to access Gsdx settings (Config - Video - Plugin settings)
Dropped on same folder as pcsx2.exe | It works as expected.
Mesa installed system wide and dropped on same folder as pcsx2.exe (normal copy or symbolic link) | Same as in previous case

**Comment by gregory38** [comment]
Do we need the global install? I don't think it is a good idea to do it btw.

**Comment by pal1000** [comment]
The global install ensures mesa is only used when needed. Windows OpenGL driver selection logic works like this if context creation is bug free:
- enumerate all OpenGL drivers until we find one that reports it supports demanded context or fail when none found;
- OpenGL drivers are enumerated in the following order: dGPU /eGPU (mainly adapters marked as high performance), iGPU /APU, custom OpenGL software renderer (e.g mesa) and finally Windows built-in OpenGL software renderer.

What you should happen with mesa system wide installed:
- On SandyBridge - mesa used automatically because iGPU is below context requirement;
- On IvyBridge - failure because we have the context but we lack extensions. Mesa won't load. Local deployed mesa is the only option. This is a technical limitation of  OpenGL driver selection algorithm;
- On Haswell and up - Always use iGPU.

**Comment by gregory38** [comment]
I'm not so sure that it is actually working (for example we added some code to force dGPU over iGPU). 

In order to setup advance option, I need to create a dummy context. The only requirements are color + depth + stencil support. Maybe we can drop depth/stencil for the window buffers. I don't know if you have access to my branch
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.2628-greg/ogl-win-intel-v2/job/2u5c4h9dhwhqrsoo/artifacts

**Comment by pal1000** [comment]
Thanks for trying but I don't see any change. Updated the table with WIN API errors for each case, This might soon become unworthy to fix as you said 3 comments above. 

Case | Outcome
---- | ----------
No mesa installed | Possibly use the iGPU and fail consistently with "Failed to init wglCreateContextAttribsARB function pointer" regardless of what adapter is selected as expected. It is way below requirements
Mesa installed system wide | Get error "Failed to create a 2.0 context" in an error dialog on first attempt to boot any game or BIOS along with WIN API error 2000 in log. If I retry, it works via mesa regardless of what adapter is selected, I also get "WIN API ERROR:87 ERROR:Failed to create a 3.x context with standard flags" when attempting to access Gsdx settings (Config - Video - Plugin settings), start, resume or restart emulation
Dropped on same folder as pcsx2.exe | It works as expected, but I get "WIN API ERROR:87 ERROR:Failed to create a 3.x context with standard flags" every time emulation is started, resumed or restarted and when Gsdx Settings is opened . If I pause emulation and resume I may also get "WIN API ERROR:2 ERROR:(3) Can't Set The PixelFormat." beforehand. Error 2 occurs every time I open Gsdx Settings when emulation is paused along with error 87 specified above.
Mesa installed system wide and dropped on same folder as pcsx2.exe (normal copy or symbolic link) | Same as in previous case 

Error 87 is obviously intentional based on its description.

**Comment by gregory38** [comment]
Sorry I can't do better. I propose to keep the current master state + local install

**Comment by pal1000** [comment]
I figured out he cause of this issue. It is the change of the type returned by  GSWndWGL::CreateContext() from bool to void back in de962d3 when windows llvmpipe support was added. I pushed I quick commit that fixes it, but I presume all those returns that were nuked in this process must be restored, which is definitely a pain.

**Comment by pal1000** [comment]
I got an idea about why this is happening, but would be tricky to fix. You were right about installing mesa system-wide is not a good idea because unlike GPU drivers, mesa drivers for Windows are complete OpenGL runtimes. GPU drivers on the other hand are just ICD hardware drivers selected by Windows built-in OpenGL runtime. Conclusion: 2 OpenGL runtimes end up fighting in a classic race condition.
#1836 seams promising, but didn't help so far.

**Comment by gregory38** [comment]
* I don't know if we can do better
* I'm not sure the mesa driver will be used by lots of user
Are you happy enough with current situation? And therefore can we close this bug?

**Comment by pal1000** [comment]
All right.
