### ISSUE TITLE
Visual Studio quick / subsequent build using Visual Studio GUI often leads to PCSX2 title bar to lie about its actual development version string

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#1818]
***PCSX2 version:***
``v1.5.0-dev-1885-g f86ea9f``

***PCSX2 options:***
``Doesn't apply to this issue``

***Plugins used:***
``Doesn't apply to this issue``

***Description of the issue:***
``If code changes since last compilation didn't touch directly or indirectly PCSX2 main project (project shown in bold in Solution Explorer) and you build using Visual Studio GUI (simply pressing F7 after loading the solution) then when build completes you will notice when you run the freshly built PCSX2 that its title bar has not been updated to reflect the new version string.``
Ideal case to reproduce is when the new commits since last compilation are only related to Gsdx.
Orphis buildbot was never affected because it always does clean build and has a dedicated script. 
Same issue as hrydgard/ppsspp#5575
That was never fixed but a workaround was provided, a script that I run before launching Visual Studio called git-version-gen.cmd.  I found a similar script in pcsx2\common\vsprops called prebuild.cmd. If is meant to execute at build time then it fails somehow and yes, Git is in PATH as expected when I build.
Ran the script manually from the Command Prompt having Git in PATH and figured it out why it fails. It creates a svnrev.h to every project but it only updates it when changes are made per project. So if pcsx2 main project doesn't change its svnrev.h remains behind triggering this issue. 
Screenshots
1. Build is up-to-date
![build-up-to-date](https://cloud.githubusercontent.com/assets/1138235/22865696/357044f6-f172-11e6-8da5-596328227f5a.png)
2. Source up-to-date
![source-up-to-date](https://cloud.githubusercontent.com/assets/1138235/22865713/82da8580-f172-11e6-850e-8192178fdde1.png)
![source-up-to-date-2](https://cloud.githubusercontent.com/assets/1138235/22865771/4e8bddaa-f173-11e6-8d09-1741a9c08856.png)
3. Compare title bar with Orphis buildbot
![pcsx2titlebarvsbuildbot](https://cloud.githubusercontent.com/assets/1138235/22865796/bc89c75e-f173-11e6-9c9a-68fe2c65ea42.png)

***Last known version to work:***
``Possibly never, I don't know, but possibly SVN builds were affected similarly``

***PC specifications:***
``Doesn't apply for this issue.``

**Comment by MrCK1** [comment]
Can't remember the name off the top of my head but you have to execute a bat file (or something similar) in the repo to generate the version string.

**Comment by pal1000** [comment]
Removing pcsx2\pcsx2\windows\VCprojects\svnrev.h before building works around this issue.

**Comment by gregory38** [comment]
Removing/Updating the .h file is annoying because it will recompile useless file. But yes you can add a pre/post build cmd to delete it. Can we close this issue as won't fix.

**Comment by pal1000** [comment]
OK.
