### ISSUE TITLE
(Request) GameIndex.dbf add this game

### ISSUE THREAD

**Issue by AkagiShiroe** [PCSX2/pcsx2#1827]
SD Gundam G Generation Wars (SLPS_259.41), can anyone also make a widescreen patches for this game?, if you can't find game disc anywhere or iso check this -removed-

**Comment by FlatOutPS2** [comment]
Piracy is not supported.

**Comment by AkagiShiroe** [comment]
sorry, this game are forgotten and f*cking ancient -,-.
