### ISSUE TITLE
Splinter Cell - Horizontal line with night vision goggles.

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1829]
***PCSX2 version:***
`pcsx2-2017.02.08_213fa1c14_master-x86_64-1_git`

***PCSX2 options:***
I tried various options, nothing seems to affect it. It doesn't occur with the software renderer.

***Plugins used:***
`GSdx (GCC 5.4.0 SSE2/AVX) 1.1.0 [libGSdx]`

***Description of the issue:***
In the game `Splinter Cell` there is a big horizontal line across the center of the screen if night vision is turned on (dpad left) and is excessively blurry below the line.

GS Dump - http://ks392457.kimsufi.com/orbea/stuff/games/pcsx2/snaps/gsdx_20170216074324_Splinter_Cell.gs.xz

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/pcsx2/gsdx_20170216074324.png)

***How to reproduce the issue:***
1. Start Splinter Cell with the OpenGL renderer.
2. Proceed to a point in the tutorial until you can use the night vision goggles.

***Last known version to work:***
I tried back to `pcsx2-2016.07.31_e329b6f_master-x86_64-1_git`, but it was still present and a similar issue has since been fixed which affected the logos and cutscenes before the main menu.

***PC specifications:***
CPU: `AMD 6350 FX`
GPU: `GTX 780Ti`
OS: `Slackware64-current`

**Comment by gregory38** [comment]
See issue #1339  => Splinter Cell (when using the optical cable)
I guess the night vision isn't the optical cable but the issue is likely the same.

**Comment by orbea** [comment]
Ah, thanks for pointing that issue out. I see it affects several games...

**Comment by gregory38** [comment]
Yeah. So far I don't have plan to tackle the issue.
