### ISSUE TITLE
GSdx missing GUI option 

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1830]
Self remainder

* W : linear present
* WL: wrap mem
* WL: SW texture filtering

**Comment by gregory38** [comment]
And #1758

**Comment by FlatOutPS2** [comment]
Where is linear present located on the Linux GUI?

**Comment by gregory38** [comment]
With post-processing shader. It was the only common section for all renderers. Besides it is really a bilinear filtering that is apply to the final image.

**Comment by gregory38** [comment]
As a side note, I'm sure we can find a better name than `linear present`

**Comment by FlatOutPS2** [comment]
> As a side note, I'm sure we can find a better name than linear present

What about Texture Filtering of Display? :P

**Comment by gregory38** [comment]
It is up to you.

**Comment by FlatOutPS2** [comment]
@gregory38 Did you add the wrap mem Linux GUI yet?

**Comment by gregory38** [comment]
Maybe. It could be in my forest ;)

**Comment by gregory38** [comment]
@FlatOutPS2 Actually it seems I didn't.

**Comment by FlatOutPS2** [comment]
@gregory38 I have a PR ready that includes the Windows GUI for the memory wrapping and split texture filtering, I'm just waiting for the TF PR to merge so I can rebase my PR. Are you going to add the wrap mem Linux GUI soon, or can it wait till after my PR(my PR still needs a memory wrapping tooltip though)?

**Comment by gregory38** [comment]
Wrap mem Linux can wait after your PR. I will address the issue of TF so we can go on.

**Comment by gregory38** [comment]
12d2c6be569ed4316d2f32320c836523dedbc088
