### ISSUE TITLE
SB: ROTFD - Bugged Steam/Smoke Effects Under OpenGL

### ISSUE THREAD

**Issue by UlsterRose** [PCSX2/pcsx2#1832]
***PCSX2 version:***
1.5.0-dev-1889

- **Note**: It's preferred to only report bugs which are present on the [latest development builds](http://pcsx2.net/download/development.html).

- **Note2**: The new backwards compatibility (psx) mode is in active development. Issue reports are too early at this point.

***PCSX2 options:***
All default, but using OpenGL HW and SW.

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset along with MTVU speed hack disabled. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
In the example I'm giving, the steam that comes off the grill in the main menu consists of opaque clouds in OpenGL HW, but it's meant to be a sort of vortex of steam.

***How to reproduce the issue:***
1. Boot the game with OpenGL HW.
2. Get to the main menu.

***Last known version to work:***
Unsure at the moment. I'll try to find one later on.

***PC specifications:***
CPU: AMD Athlon X4 750K
GPU: AMD Radeon HD 7770
RAM: 4GB DDR3
OS: Win 10 x64

OpenGL Hardware:
![gsdx_20170217220949](https://cloud.githubusercontent.com/assets/8225831/23085229/6bd693a2-f55e-11e6-8959-085c1539123f.png)

OpenGL Software (Expected Behavior):
![gsdx_20170217220957](https://cloud.githubusercontent.com/assets/8225831/23085237/7798253e-f55e-11e6-9453-7951ea30c334.png)

Oddly enough, D3D11, under all the depth-emulation related horror, seems to have the effects work just fine, more or less.

**Comment by MrCK1** [comment]
The shadows in the picture are also bugged in OGL HW. Must be part of a bigger problem.

**Comment by FlatOutPS2** [comment]
I assume you recently updated your AMD drivers, as it reintroduced an AMD OpenGL driver bug. See: https://github.com/PCSX2/pcsx2/issues/1552

**Comment by mirh** [comment]
Could you try to put [17.1.2 atioglxx](http://www77.zippyshare.com/v/Cvtx2vew/file.html) in pcsx2 folder?

**Comment by DisorderIy** [comment]
@mirh it doesn't seem to have any effect. That could be because I'm on 17.2.1 AMD drivers, but the file you provided says 17.1.2, which I think was the one before mine. Just a guess.

**Comment by mirh** [comment]
> That could be because I'm on 17.2.1 AMD drivers, but the file you provided says 17.1.2, which I think was the one before mine.

That was the assumption and the point. 

@FlatOutPS2  should be unrelated from that then

**Comment by FlatOutPS2** [comment]
>@FlatOutPS2 should be unrelated from that then

The game is fine on my side with same dev versions, it very much looks like the AMD driver bug and he's on 17.2.1. Maybe the 17.1.2 you provided didn't get loaded properly.

**Comment by mirh** [comment]
That fixed odd Playstation 2 logo on start here, so I don't guess so. 

On another note.. Who said this was an AMD bug in the first place?

**Comment by gregory38** [comment]
The screenshot screams at yet an AMD bug. I hope they didn't introduce a new one with their previous fix.
@DisorderIy could you either
* set accurate blending to the higer level
* provide a gs dump

**Comment by FlatOutPS2** [comment]
@gregory38 He already provided a gs dump in a previous issue: https://github.com/PCSX2/pcsx2/issues/1685

**Comment by gregory38** [comment]
Ok. Good. So yes it is the usual AMD mess. I think I will just black list all 2017 driver until we have news of them (likely end of 2017 anyway).

**Comment by lightningterror** [comment]
Closing this.
#1552
