### ISSUE TITLE
The: Matrix Path of Neo GPU issues in OpenGL HW renderer

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#1834]
***PCSX2 version:***
Latest 1.5.0 @607e016

***PCSX2 options:***
Default.

***Plugins used:***
Latest GSDx @607e016, OpenGL HW/SW renderer. Auto Flush hack partially fixes the tint issue. Texture issue still present regardless of settings.
SW works perfectly.

***Description of the issue:***
Weird blue-ish tint and texture issue.

***How to reproduce the issue:***
Launch the game with OpenGL HW renderer.

***Last known version to work:***
Pretty sure this never worked properly before

***PC specifications:***
CPU : Intel Core i7-3770S
GPU : Nvidia GeForce GTX 980
OS: Windows 10 Pro (1607) x64

OpenGL SW
![image](https://cloud.githubusercontent.com/assets/4414625/23212962/578acfae-f909-11e6-9e3b-9fc96704c80b.png)
OpenGL HW
![image](https://cloud.githubusercontent.com/assets/4414625/23212936/3ae084e8-f909-11e6-9bb5-6a4542349a0e.png)
OpenGL HW (Auto Flush)
![image](https://cloud.githubusercontent.com/assets/4414625/23213024/aab1e71c-f909-11e6-8c76-de20bfb29e33.png)
OpenGL HW (Auto Flush + Preload Frame Data)
![image](https://cloud.githubusercontent.com/assets/4414625/23213956/4ae10eb8-f90d-11e6-9ed3-27ac0e4ebc13.png)

**Comment by gregory38** [comment]
IMHO, it is the typical half screen bug.

**Comment by Blackbird88** [comment]
Oh. I didn't know this is common issue.

**Comment by gregory38** [comment]
You can read issue #1339

**Comment by gregory38** [comment]
I moved it to the confirmed section. I think we can close this issue. But it could be a good idea to add the game in the tooltip of autoflush option.

**Comment by Blackbird88** [comment]
Well damn I did search the issues, but didn't think the game could be in some list :D
Do you mean GameIndex? I'd like that.

**Comment by gregory38** [comment]
Github searches capabilities aren't ideal.

Not the gameindex file, only the option tooltip. A full automatic setup of the emulator/GSdx would be another project. An extension of the file would be a bad idea as it is already too big.

**Comment by gregory38** [comment]
If by this you mean the half screen bug.
* The purpose of the above issue is to have an open issue for one GSdx issue. Not an issue per game that hit the game GSdx issue. We already have +300 issues, it is impossible to manage.
Otherwise we're are on the same line ;)

**Comment by Blackbird88** [comment]
>We already have +300 issues, it is impossible to manage.
Nevermind then :D

**Comment by gregory38** [comment]
It is sad. If we manage to close 1 issue by week. It means that it will take nearly 6 years of work to flush the current mess (without counting any new bug).
