### ISSUE TITLE
GSdx: linear filtering option

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1837]
Currently we have a combo box to force the texture filtering mode
* always nearest
* PS2
* always bilinear
* trilinear
* trilinear (+ bilinear)
* trilinear forced

Some people want similar (near/bilinear) option for all renderers (namely the SW renderer).

Instead to add more code in the sw renderer. I want to change the code that does linear detection (in GSVertexTrace). And split the option in 2.

We will have a common option to select nearest/bilinear mode.
* always nearest
* PS2
* always bilinear but SPRITE (upscaling issue).
* always bilinear

Then we will have a dedicated option for trilinear for openGL.
* off (recommanded)
* trilinear
* trilinear always

I think it would make the configuration easier. And code easier too. But I want some feedbacks.

**Comment by gregory38** [comment]
@mirh @ssakash @FlatOutPS2 @refractionpcsx2 @turtleli

**Comment by MrCK1** [comment]
Just a side note - Trilinear Forced/Ultra can corrupt textures as I noted in #1668.

Regardless, I'm all for less options to confuse users, but personally I never noticed any improvement using anything higher than Bilinear (Forced).

**Comment by gregory38** [comment]
Yes I know. Effect is subtle. Some users might like it. Otherwise we can keep trilinear as debug only.

**Comment by mirh** [comment]
I call me out. 🙈 
I'm only good complaining about stuff between pcsx2 and the "external environment" these days.

**Comment by FlatOutPS2** [comment]
> Then we will have a dedicated option for trilinear for openGL.

Would it help if I ported it to D3D?

**Comment by gregory38** [comment]
Not really. I'm not sure the option is that useful. The main goal is to split bilinear from trilinear. And then do something more generic on the code

**Comment by gregory38** [comment]
And it might allow to move tri in the hack section

**Comment by FlatOutPS2** [comment]
It all sounds good to me, including the moving of tri to the hacks section.

**Comment by refractionpcsx2** [comment]
I agree with FlatOutPS2

**Comment by ssakash** [comment]
As an alternative opinion, do we even need the trilinear option if it isn't useful to most of the users? It could maybe be made as an INI variable for debugging necessities alone?

**Comment by FlatOutPS2** [comment]
> As an alternative opinion, do we even need the trilinear option if it isn't useful to most of the users? It could maybe be made as an INI variable for debugging necessities alone?

Several games need it for mipmapping: https://github.com/PCSX2/pcsx2/issues/1561

**Comment by gregory38** [comment]
Yes let's just move it in the hack section where it belong.

**Comment by gregory38** [comment]
Note I did some code. I will push it after the other HPO option to avoid any conflict.

**Comment by FlatOutPS2** [comment]
Should it be closed while the Windows side isn't merged yet?
