### ISSUE TITLE
[GSDX-TC] Regression in Jackie Chan Adventures

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1838]
Jackie Chan Adventures doesn't seem to like the skip of drawcall (https://github.com/PCSX2/pcsx2/commit/87fc4c1e44cfa7215cf1b327e0c0f93cadfb5bda) in #1760 , reverting that and adding back ``return LookupSource(TEX0, TEXA, r);`` seems to fix the half screen flickering issue in Jackie Chan Adventures. FYI, this game also enters the half right path which is there for the Snowblind games.

Before #1760:

![before](http://i.imgur.com/OqW64D8.png)

After #1760:

![after](http://i.imgur.com/4jcpoRe.png)

_**GSDump**_: [_**here**_](https://www.dropbox.com/s/8k47jq8h9qvbykp/JackieRegression.7z?dl=0)

**Comment by FlatOutPS2** [comment]
> FYI, this game also enters the half right path which is there for the Snowblind games.

What happens if you block it?

**Comment by ssakash** [comment]
> What happens if you block it?

Issue still exists even if you block the special case for Snowblind games. (I just mentioned about the ``half_right`` code path in case it might be useful)

**Comment by gregory38** [comment]
Hum, it could just require to handle the half case when we lookup the depth. I won't touch it now as I would like a more generic solution.

**Comment by gregory38** [comment]
@ssakash @FlatOutPS2 What about a crc hack with a big comment message to explain the situation.

**Comment by lightningterror** [comment]
There still seems to be some issues to iron out on D3D. The language select background is black instead of yellow.

Regression PR #1760

**Comment by lightningterror** [comment]
Fixed on d3d11.
