### ISSUE TITLE
[Enhancement] Include CLR DEV9 plugin

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#1841]
Consider including the CLR DEV9 plugin in master. It is, thus far, the only dev9 plugin with both network and hdd support, and the only one that games will properly detect the hdd in game.

Link to forum discussion and latest compiled download is [here](http://forums.pcsx2.net/Thread-Experimental-Winsock-based-DEV9-plugin-Now-with-HDD-Support).
Repository is [here](https://github.com/TheLastRar/CLR-DEV9).

**Comment by MrCK1** [comment]
Most users won't use DEV9. They can download it if they want it, but otherwise we want to keep the installation size low and reduce plugin clutter.

**Comment by ichee** [comment]
It could replace dev9ghzdrk since its functional use cases are fewer than CLR DEV9, plus having it present would increase the chances of improved development.

**Comment by mirh** [comment]
PS2 had both hdd and network support.. So I don't see why we should miss that. 
And size.. It's like 160KB? 

The "biggest" criticism I can find if any, is that a c# plugin feels weird in a sea of c++ 😛

**Comment by MrCK1** [comment]
Lol I think I misread the original comment :P but yeah I don't see any issue adding it.

**Comment by FlatOutPS2** [comment]
>The "biggest" criticism I can find if any, is that a c# plugin feels weird in a sea of c++ 😛

I do think it should be converted to C++ and clang-formatted before considering adding it to PCSX2. It shouldn't be that much work.

**Comment by lightningterror** [comment]
Closing #3764
