### ISSUE TITLE
[GSdx- OGL HW regression] Vector/Raster 3D OSD rendering in RTSS may cause corrupted graphics.

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1845]
***PCSX2 version:***
v1.3.1-170-gf0182f9 (https://github.com/PCSX2/pcsx2/commit/f0182f9a66ca897d415de3f72fd3fe82bbca6c53) to latest git
[v1.3.1-170 from Buildbot](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-170-gf0182f9&platform=windows-x86)

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults, OGL HW, 4x Native Resolution

***Description of the issue:***
In games such as Smuggler's Run, The Suffering TTB, and PS1 titles; certain graphical elements will become broken if F12 is pressed. On occasion, the games may boot up with the corrupted graphics, further confusing users.

***How to reproduce the issue:***
Boot a game, and either: 
- Press F12 and close the GSCapture dialog to see if corrupted graphics appear.
- Start a recording, then end it with F12 to see if corrupted graphics appear. 

***Last known version to work:***
pcsx2-v1.3.1-157-g258b734 (https://github.com/PCSX2/pcsx2/commit/258b73409ca393bfd3ce9d8966dd88a34a90d6ce) (v1.3.1-170 was the next build 2 days later)
[v1.3.1-157 from Buildbot](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-157-g258b734&platform=windows-x86)

[Here is a list of commits](https://github.com/PCSX2/pcsx2/commits/1.4.x?after=Y3Vyc29yOiEBKo7DaNPoil89AAMNBh4h%2FMmnKzEzOTk%3D) between builds 157 and 170 - Click "Older" to see the other half of the commits. 

***PC specifications:***
``Intel Core i5-6600k @3.2GHz, EVGA GTX 1070, Windows 10 64 Bit - build 15031)``

Examples:
![](https://media.giphy.com/media/YD16Zi5F5l8l2/giphy.gif)

![](https://media.giphy.com/media/JrXdcts7DPSUw/giphy.gif)

**Comment by FlatOutPS2** [comment]
>Press F12 and close the GSCapture dialog to see if corrupted graphics appear.

Can the issue trigger by just pressing F12 or does it only trigger if you close the dialog?

**Comment by MrCK1** [comment]
On newer builds, it only triggers if the dialog is closed or if a recording is stopped (using F12).

On the 1.3.1-170, the dialog doesn't work; but I can still trigger the issue on and off by pressing F12

**Comment by MrCK1** [comment]
Damn I feel stupid 😛 MSI Afterburner was the problem.

**Comment by FlatOutPS2** [comment]
Was it purely an MSI Afterburner issue or does it still not happen to 1.3.1 build 157?

**Comment by MrCK1** [comment]
No it was purely MSI Afterburner. That's why I didn't see the issue after I rebooted my PC

**Comment by FlatOutPS2** [comment]
Then it might still be worth looking into. It might be fixable in PCSX2 or it can be reported to the MSI Afterburner developers as an upstream issue. Many people use MSI Afterburner, so it's likely to affect quite a few people.

**Comment by MrCK1** [comment]
Thanks, I'll look into the issue as well. It may even be an Rivatuner Statistics Server because I have that linked to Afterburner.

**Comment by MrCK1** [comment]
Thanks, I'll look into the issue as well. It may even be an Rivatuner Statistics Server issue because I have that linked to Afterburner.

**Comment by MrCK1** [comment]
@FlatOutPS2 I found the bad commit, it was https://github.com/PCSX2/pcsx2/commit/6e386df535ec10f8d8d1aef9177bd3f02741c811 (gsdx-ogl: avoid to clean fully texture in DATE)

**Comment by ramapcsx2** [comment]
It begs the question: 
Do we want to cater to 3rd party tools that hook the renderer?

**Comment by MrCK1** [comment]
Unless there is a major problem that may affect a significant amount of end-users *_cough_ AMD _cough_ 

I believe writing code around 3rd party tools isn't a good idea, unless it can be done without creating a regression. It's still great that we have a reference to the cause of the issue if we choose to pursue it down the line, considering it's technically a GSdx issue.

In the future, I may update the issue template asking users to state what external programs are running such as monitoring tools or antivirus.

**Comment by gregory38** [comment]
It could also be a bug in the tool that update a state without restoring the old one. The above commit enables the scissor test to reduce the clear load (from Xmin,Ymin to Xmax,Ymax). Basically we don't clear the stencil value that we don't use. So I fail to see the GSdx issue here.

**Comment by MrCK1** [comment]
@gregory38 The author of RTSS released a new beta yesterday and the issue is gone. A frame I captured earlier shows that the API errors being returned were due to RTSS using Legacy OpenGL.

**Comment by gregory38** [comment]
See, it wasn't a GSdx issue. My GL renderer is top notch :stuck_out_tongue_closed_eyes:
