### ISSUE TITLE
Budokai 3 character faces don't show up in scouters unless in software mode.

### ISSUE THREAD

**Issue by MoochMcGee** [PCSX2/pcsx2#1847]
I'm using v1.5.0-dev-1912.

I've tried this with a variety of settings.
I have turned all CRC hacks off, turned up Blending Unit Accuracy to Ultra, and turned on Full mipmapping. Funny how I still get 60 FPS with these settings.

OS: Windows 10 Insider Preview 64 bit
CPU: Intel Core i3-3210
GPU: nVidia GeForce GTX 750Ti overclocked by about 200 MHz,
RAM: 10 GB of DDR3.

**Comment by FlatOutPS2** [comment]
Please remove issue template notes for readability, and try to reproduce the issue with all default settings.

**Comment by MoochMcGee** [comment]
I just reproduced it with default settings. The only difference is that I had to use the SSE4 version of GSDX because my processor doesn't support AVX2.

**Comment by FlatOutPS2** [comment]
Can you share a gs dump of the issue: http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by MoochMcGee** [comment]
[http://i.imgur.com/ZWO3eLu.png](url)

[https://mega.nz/#!h0FXEZBS!swKkaOqEgDCQb85QtVXwKNZjLYJzdfyEM80ErqYkdvI](url)

**Comment by MoochMcGee** [comment]
Another issue has been discovered with this game. During the Spirit Bomb attack from Goku, when the ki gauges is supposed to be filling up, they don't, even if you hit the Cross button in time. This also works in software mode.

https://mega.nz/#!ggkTDKjS!AxJXwD2wiPWoj2PI_M-wvHg5bbagde3V0fNDfCuTmsU

**Comment by FlatOutPS2** [comment]
@gregory38 This is a regression caused by https://github.com/PCSX2/pcsx2/pull/1538

**Comment by MoochMcGee** [comment]
@FlatOutPS2 Well, I guess that makes it easier to fix. This also happens in D3D11, though I haven't tried D3D9.

**Comment by gregory38** [comment]
@FlatOutPS2 @ssakash any of you, want to debut/fix it. Basically you need to
* find the bad draw call (`"Complex Alpha Test"` message can likely help you)
   * dump state framebuffer (`save = 1`, `saven=0`, `savel=9999`, `dump=1`)
   * compare SW/HW
* Dump GS state (check the txt file) to find which kind of ATE the game is doing
* try to understand what happen in the code

**Comment by FlatOutPS2** [comment]
The issue seems to be triggered by the `om_bsel.wa = false;` in `Alternate ATE handling: ate_RGB_then_ZA`.

Haven't looked into it any further though.

**Comment by gregory38** [comment]
It would be nice if you have the related context file. (mostly test + blending). Do you have the draw call number.

**Comment by ssakash** [comment]
> Edit: looking at the code. I don't how it can work ;) then_ZA was mostly a copy/past of then_Z.

Your older code actually made sense to me. :P 

I'm not sure why you think it won't work? In the ``then_ZA`` case, we're controlling the Z and A values and only having the RGB ones effective which is different from ``then_Z`` where we only control the Z value. ( Shouldn't that be on how it works? Though I think you also need to do an additional check to make sure that the format is ``RGBA32`` before applying it)

**Comment by gregory38** [comment]
It is rather complex so I won't be surprised of a strange corner case. We need to make sure there isn't any other pixel test enabled. And also check the hypothesis of commutativity (in particular the blend equation)

Note: I use apitrace to see the content of the vertex buffer, you can decode it based on the memcpy.

**Comment by gregory38** [comment]
@FlatOutPS2 I gave it a quick look. And you're close of the issue indeed it is related to wa handling.

**Comment by gregory38** [comment]
@FlatOutPS2 @ssakash tell me if you want to find the bug yourself, otherwise I will push a fix soon.

**Comment by FlatOutPS2** [comment]
@gregory38 So you already know how to fix it?

I haven't had the time to look at it any further, so you can push the fix as far as I'm concerned.

**Comment by gregory38** [comment]
Yes, I've known it since my previous post 2 days ago. No merit, it is my code and I know GS pretty well. I only compared the frame buffer between SW/HW based on your valuable feedback.

**Comment by LeCharlatan** [comment]
Hi everyone !
I did play this Dragon Ball Z Budokai 3 some weeks ago and I got this issue too.
Using Linux Ubuntu Xenial (then OpenGL) and using your official PPA for 1.5.0-dev
I finished the game since but, that wasn't easy using ultimate attacks :p

**Comment by ssakash** [comment]
@gregory38 

I haven't looked into it yet but this one looks really suspicious to me,

> a = !!(m_context->FRAME.FBMSK & 0xFF000000);

Instead of checking for masks on the alpha bits, shouldn't you check for no masks on the alpha bits? the bit on the framebuffer isn't updated when it's set to 1. If that's not the case then what's the point in enabling alpha test when writes to alpha bits are masked?

**Comment by gregory38** [comment]
@ssakash 
We have a winner :) Now you can do the PR :+1:

@LeCharlatan 
Too bad you didn't report the regression early.

**Comment by LeCharlatan** [comment]
@gregory38
Okay, I'll report bugs as soon as I discover it :)
