### ISSUE TITLE
Psx Mode Problems

### ISSUE THREAD

**Issue by wingedonezero** [PCSX2/pcsx2#1849]
#Games Tested#
Breath of Fire 3- Does not load
Breatch of FIre 4 - Does not load
Chaos Break (pal) - Graphics issues and after you select character crashes
Crisis Beat - loads but gets a "PGIF FIFO overflow! sz= 20000" error
Star Ocean 2 - Crashes after second intro screen

And the list goes on same problems either does not load or crashes after first or second screen. Also
garbage graphics on the ones that load far enough to see graphics. I didn't see a issue thread on psx mode tested games and problems. So i figured id start this one and people can add to it because booting seems to be the main problem right now.

![chaos break intro](https://cloud.githubusercontent.com/assets/15163316/23728743/773e818c-042c-11e7-8f76-af5bca5b67b9.png)
![crisis beat](https://cloud.githubusercontent.com/assets/15163316/23728751/7d15ca52-042c-11e7-9340-05f644e032c6.png)

**Comment by FlatOutPS2** [comment]
Please read the issue template before posting:

**Note2: The new backwards compatibility (psx) mode is in active development. Issue reports are too early at this point.**

**Comment by PanderTech** [comment]
As far as I can tell, the garbage graphics will often subside when using either D3D or OpenGL **software** mode.

Before:

![mk4b](https://user-images.githubusercontent.com/53921171/62804379-18d87380-babb-11e9-87b5-2326e2dc4449.PNG)

After:

![mk4a](https://user-images.githubusercontent.com/53921171/62804378-18d87380-babb-11e9-9729-0d90b37b7671.PNG)

FYI: I've only tried this on Mortal Kombat 4, which is the game shown in the screenshots.
