### ISSUE TITLE
UWP for xbox one dev

### ISSUE THREAD

**Issue by metalex10** [PCSX2/pcsx2#1856]
Hi I would like to know if I could get a version uwp for xbox one since I am a developer of this console and I would like to try the game there

**Comment by mirh** [comment]
Very unlikely pcsx2 is going any far on a 1.6GHz cpu, unless somebody first doesn't try to rebase *the whole* emulator on HSA (which I'm not sure xbox supports in the first place, thanks microsoft). 

Also.. How do you think bios/games could be provided by users?

**Comment by FlatOutPS2** [comment]
It won't happen, you're better off asking PPSSPP for an xbox port again.
