### ISSUE TITLE
Xenosaga Episodes I, II, III [NTSC-U]: glitchy save file screenshots

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#1857]
***PCSX2 version:***
1.5.0-dev-1927

***PCSX2 options:***
defaults, no speedhacks

***Plugins used:***
defaults, GSdx D3D11+OGL, SW+HW

***Description of the issue:***
When creating a savefile in Xenosaga I, the game also creates a small, highly compressed screenshot and saves it alongside the game data.
Screenshots for savefiles created by PCSX2 are noticeably more glitchy. HW renderers produce more glitches, but there is little if any difference between D3D11 and OGL.

![gsdx_20170313164242c](https://cloud.githubusercontent.com/assets/17594477/23863351/e37d50da-080f-11e7-971a-9abcb598aa11.png)
![gsdx_20170313164242d](https://cloud.githubusercontent.com/assets/17594477/23863363/e7e62804-080f-11e7-99b1-19cb60cb9e9a.png)
![gsdx_20170313164242e](https://cloud.githubusercontent.com/assets/17594477/23863361/e5f7c2e6-080f-11e7-9d00-43944f13d234.png)

***How to reproduce the issue:***
Save the game at a savepoint (one that doesn't crash to BIOS, preferably).

***Last known version to work:***
It's the same in 1.0.0, so was probably never more accurate.

***PC specifications:***
i5-4690k, R9 270X, 16GB RAM, Win10 14393 64bit

**Comment by gregory38** [comment]
Just to be sure, try to change the texture filtering option.

**Comment by trostboot** [comment]
Already did when looking at the HW modes, it makes no difference.

**Comment by gregory38** [comment]
On recent GIT the option impact the SW renderer too.

My guess is the bug is related to ST/Q rounding. We are either too accurate or not enough. It would be awful to debug. So it is very low priority.

**Comment by trostboot** [comment]
Made no difference for the SW renderer, as well.

> It would be awful to debug. So it is very low priority. 

I figured it would be both of this, but cataloguing issues can't hurt. :)

**Comment by gregory38** [comment]
```
I figured it would be both of this, but cataloguing issues can't hurt. :)
```
It takes me hours to only sort/tag the issue. 310 bugs => 1 fix / week => 6 years of work ;) I don't say to not report bug. But don't make the shortcut as more bug the merrier ;)

**Comment by ssakash** [comment]
Providing a [_GS dump_](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue might be useful.

**Comment by gregory38** [comment]
Might be tricky as the texture is maybe already wrong before the display. You might need a longer dump.

**Comment by trostboot** [comment]
Yeah, this is why I didn't make one initially. It should be created when opening the save menu, as changing the renderer afterwards doesn't affect it.

Here's a multiframe dump that hopefully captures it. (zip is so bad for compressing these ...)
[gsdx_20170313193712.zip](https://github.com/PCSX2/pcsx2/files/839279/gsdx_20170313193712.zip)

**Comment by ramapcsx2** [comment]
The image is a screen / framebuffer grab the game takes when creating the save file. The bug could happen there already. I don't think a GS dump can capture it.

**Comment by trostboot** [comment]
That's why the dump is from opening the save menu, as that's when the image is grabbed. If you change renderers afterwards, you'll still get the image that corresponds to what you were using when opening the save menu, as it's presumably already in memory by that point. 
Whether the dump itself is helpful or not I can't say, but if there is a time to capture it, that would be it.

**Comment by ramapcsx2** [comment]
Okay, the dump will be good if the actual problem happens in the GS. I'm assuming it is a core bug and thus outside of what GS dumps capture.

**Comment by gregory38** [comment]
Someone need to check the dump to find the source of the texture (likely a framebuffer). And how the frame buffer is resized.

**Comment by trostboot** [comment]
Perhaps unsurprisingly, this also affects Xenosaga Episode II ...
![gsdx_20170328170135](https://cloud.githubusercontent.com/assets/17594477/24413000/65e9cb5e-13da-11e7-98b8-a7df2e84b1fc.png)
(top PCSX2, middle PS2)

... as well as Episode III.
![gsdx_20170328171623](https://cloud.githubusercontent.com/assets/17594477/24413005/6c905c16-13da-11e7-8dea-565d0d35b8ee.png)
(top PS2, middle PCSX2)

Hooray for code reuse?

**Comment by gregory38** [comment]
Could you try the various EE/VU float options? Just to know if there is any impact.

**Comment by trostboot** [comment]
No difference at all, same for the various interpreters.

**Comment by ramapcsx2** [comment]
We should check if IPU is involved. This seems like a task for it. Simply check if an IPU0/1 DMA runs when saving a game.

**Comment by trostboot** [comment]
I took a look with trace logging enabled, no IPU mentions inbetween activating a save point and saving the game.

**Comment by MrCK1** [comment]
@trostboot Is the status any different on latest git?

**Comment by trostboot** [comment]
No, same as before.

**Comment by RedDevilus** [comment]
This should be better than before with the patches in the GameDB.

**Comment by trostboot** [comment]
I can spot no differences in all 3 games across all renderers on v1.7.2242. As before, there's slight variations between the different renderers, but no observable changes to save file snapshots created years ago.

The only GameDB additions I can find are crash prevention patches from ~1y ago. Were you referring to those? 
My understanding is those patches merely decrease the compression quality, but wouldn't affect whatever is causing the compressed image (or the underlying screenshot capture or whatever it is that's going wrong) to be glitchy in the way they are.

**Comment by Jakey757** [comment]
^The patch is only for Xeno 1 to prevent it from crashing, it doesnt affect the artifacts present enabled or disabled. Seeing as this affects 2+3 when neither of those games have a patch in the gamedb, its a different issue and not a result of the patch.

**Comment by refractionpcsx2** [comment]
I'm inclined to say this is nothing more than an upscaling issue now.  We did some testing with Xenosaga 1 (with and without the patch) and in software mode and mostly in HW native, it pretty much matches a save from a real PS2.

The games don't produce a good picture from upscaling, but it's likely they do some sort of bilinear'd rescale which isn't going to work in hardware, not much we can do about that.  As we don't really take bug reports for upscaling (which is all this remains to be) I'm gonna say this is done for now.  Maybe in the future we can do a scaled bilinear to improve that when upscaling, but I can't guarantee it.
