### ISSUE TITLE
Linux: Crash caused by presence of libGsdx-AVX2.so plugin on non-AVX CPU

### ISSUE THREAD

**Issue by r2rX** [PCSX2/pcsx2#1859]
Hey all,

I'm running Ubuntu 16.10 x64 (w/ GTX 780 & 378.13 drivers) on an i7 930 CPU. My system is running the latest version of PCSX2 from the official PPA.

If I open the Plugin/BIOS selector, PCSX2 hangs for a few seconds and crashes. The Stack Trace, from the Ubuntu error report, indicates an issue between the **libGsdx-AVX2.so** plugin and **/lib/ld-linux.so.2** (_/lib/i386-linux/gnu/ld-2.24.so_). When running PCSX2 via a terminal, the last entry recorded after crashing is **Illegal instruction (core dumped)**.

This has occurred over the builds i've tested during the last month or so. So far, deleting the plugin stops the crash from happening.

If there's any other specific information anyone would like, let me know.

**Comment by gregory38** [comment]
Arg. I enabled BMI2 instruction. I suspect there are some in a global constructor (or AVX2).

**Comment by turtleli** [comment]
Do you mean the official PPA, or the daily builds PPA?

**Comment by gregory38** [comment]
I think it means the official daily PPA.

**Comment by r2rX** [comment]
I'm using the daily builds PPA.

**Comment by turtleli** [comment]
I can't reproduce the crash on accessing the Plugin/BIOS selector, though I'm not using the PPA (I don't have a Debian/Ubuntu VM). However, I do see AVX/AVX2 instructions in `GSUtil::CheckSSE()` on my end. It seems related to the size of the `checks` array.

**Comment by gregory38** [comment]
Stack trace of the bug could help. It could depends on GCC version. I nearly sure it is related to BMI instructions There are used everywhere as fast shift.

**Comment by FlatOutPS2** [comment]
I didn't encounter the issue on Lubuntu 16.10 x64 when I recently tried PCSX2 v1.5.0 dev-1912 from the daily PPA either. It only crashed when I selected an unsupported plugin.

**Comment by gregory38** [comment]
```
It only crashed when I selected an unsupported plugin.
```
What do you mean by crash ? It must report a nice error message not crash.

**Comment by FlatOutPS2** [comment]
By crash I mean PCSX2 disappeared immediately and I only got a Lubuntu crash message shortly afterwards.

**Comment by gregory38** [comment]
No bueno ! Could you attach a gdb and post a stack trace.

**Comment by turtleli** [comment]
That crash is due to GCC deciding to use vector instructions to initialise an array when `GStest()` is called. Which is related to what I said earlier (I probably should have provided more context):

 >However, I do see AVX/AVX2 instructions in `GSUtil::CheckSSE()` on my end. It seems related to the size of the `checks` array.

**Comment by gregory38** [comment]
Oh. Ok. I'm surprised it didn't explode sooner. It used to work. Anyway, I need to check the ASM.

**Comment by gregory38** [comment]
I don't have AVX in GSUtils on my side.

However I think it will be safer/better to disable optimization/target here with the help of prama
* https://gcc.gnu.org/onlinedocs/gcc/Function-Specific-Option-Pragmas.html
```
#pragma GCC push_options
#pragma GCC target("sse2")
...
#pragma GCC pop_options
```

**Comment by gregory38** [comment]
I created the PR #1867 to disable GCC optimization. Hopefully it will be enough to avoid the issue.

**Comment by danilaml** [comment]
Sorry for kind of unrelated off-topic I was wondering why PCSX2 seems to be loading plugins with unsupported instruction set? (i.e. why it can't just detect available instruction sets in the core (which is just regular SSE2) and then loads corresponding plugins accordingly)?

**Comment by gregory38** [comment]
But how do you know the ISA of the plugin in a reliable way ? Hint plugin name isn't reliable.

**Comment by danilaml** [comment]
@gregory38 well, the current situation seems to be even less reliable. But enforcing convention (it's plugins responsibility to work correctly with emulator not the other way around) like all plugin's dlls should have the following format: `pluginName.ISA(if any special).dll/so` should solve most such things. Especially given that it looks like GSdx is the only active plugin that uses and benefits from having multiple builds for different ISA support levels.

**Comment by gregory38** [comment]
Yes current situation isn't perfect neither.
