### ISSUE TITLE
Ace Combat 5 - See through sun in HW renderers

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1860]
[Gs dump](http://www61.zippyshare.com/v/Zn7vCK0h/file.html). 
If I first toggle SW renderer, it then gets fixed.

**Comment by oldmud0** [comment]
In the future, I suggest attaching files via GitHub (just drop your files in the text box) instead of using sketchy file hosting sites.

**Comment by mirh** [comment]
TOO BAD THAT EVERY DAMN TIME I TRY TO ATTACH \*ANYTHING\* IT TELLS ME CONTENT IS NOT SUPPORTED

...

*sob*

**Comment by FlatOutPS2** [comment]
> TOO BAD THAT EVERY DAMN TIME I TRY TO ATTACH *ANYTHING* IT TELLS ME CONTENT IS NOT SUPPORTED

I had that for a while, but it's fine now. I could still upload zip files by renaming them to one of the other supported formats(like pdf).

**Comment by oldmud0** [comment]
Here, I repackaged it into a zip and uploaded it on GitHub.
[AC5sun.zip](https://github.com/PCSX2/pcsx2/files/843189/AC5sun.zip)

**Comment by lightningterror** [comment]
Ah I have that problem as well , that's why I use google drive when I post gs dumps on github.

**Comment by mirh** [comment]
I'll also dupe here the dump from @jupiterbjy that misses "colored halo" around explosions in HW renderer. 
https://drive.google.com/file/d/0BxWgr9SSY0qtYXVGN3JoNUt3Njg/view

(perhaps to mirror on github.. *sighs*)

**Comment by refractionpcsx2** [comment]
Can this be tried again with Auto Flush enabled on #5580 (or if it gets merged before you see this can you retry master)?

**Comment by coornio** [comment]
Tested in 2415 and it's all fixed. I should note, however, that autoflush is not necessary for the sun. It works fine with the hack turned off.

![image](https://user-images.githubusercontent.com/11655762/156919869-6c233c7b-26a5-48a0-9260-cb7967e12c44.png)

**Comment by mirh** [comment]
This is still bugged. 
Not to the same "like the plane wasn't even there" extent, but still.. some good amount of light goes through it. 
And if you switch between the sw CLUT render settings while you are occluding the sun, then rays stop to be a thing until you switch back and forth from the software renderer.

**Comment by mirh** [comment]
[Ace Combat - Squadron Leader_SCES-52424_20221211180936.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/10202772/Ace.Combat.-.Squadron.Leader_SCES-52424_20221211180936.gs.xz.zip)
Single frame dumps doesn't seem to be able to catch the issue.

**Comment by mirh** [comment]
Yes multi frame worked.
