### ISSUE TITLE
Ace Combat (5) Squadron Leader - missing clouds in Hardware mode

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1861]
***PCSX2 version:***
v1.5.0 dev-1927

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Clouds are missing in GSdx Hardware mode, regardless of setting and renderer. Fog and smoke effects are visible, and should not be confused with clouds.

***How to reproduce the issue:***
Boot the game and start a mission, then look for clouds in Software mode and switch to Hardware mode to notice they're gone.

***Last known version to work:***
Never worked AFAIK.

***GS Dump:***
[Ace Combat 5 clouds missing in HW.zip](https://github.com/PCSX2/pcsx2/files/842353/Ace.Combat.5.clouds.missing.in.HW.zip)

**Comment by mirh** [comment]
Oh right, thanks.

**Comment by atomic83GitHub** [comment]
Same issue on Ace combat 4 even with last 1.5dev

**Comment by lightningterror** [comment]
Still an issue on 1.7.2731.

**Comment by Kayael76** [comment]
I really wonder what causes this issue, it's the same for AC0 (same engine). Still not working on the latest nightly, whichever backend used in hardware.
