### ISSUE TITLE
SVC Chaos - Main menu invisible in Hardware mode

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#1862]
***PCSX2 version:***
v1.5.0 dev-1927

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
The main menu is completely black in Hardware mode. This is a regression following this commit:
https://github.com/PCSX2/pcsx2/commit/de38963904140259ca1b398234e04931f545bbf8
Specifically this line: `tex = tex_psm.depth ? m_tc->LookupDepthSource(context->TEX0, env.TEXA, r) : m_tc->LookupSource(context->TEX0, env.TEXA, r);`

***How to reproduce the issue:***
Set Renderer to any of the Hardware renderers, boot the game and advance to the main menu.

***Last known version to work:***
v1.5.0-dev-640

**Comment by gregory38** [comment]
Could it be linked to #1838 ? Does `LookupDepthSource` throw or return a bad texture ?

**Comment by MrCK1** [comment]
@FlatOutPS2 Care to retest this?

**Comment by FlatOutPS2** [comment]
@MrCK1 see https://github.com/PCSX2/pcsx2/pull/1868

**Comment by lightningterror** [comment]
Perhaps CanConvertDepth() check should be added to that line and also reuse the old code when depth isn't supported to fix the regression on D3D ?

**Comment by Immersion95** [comment]
This is still happening in the latest build with any HW renderer in the menu of those games : 
-SVC Chaos
-KOF2002

Should I open another issue ?

**Comment by refractionpcsx2** [comment]
No I'll just reopen this one.

**Comment by Immersion95** [comment]
> No I'll just reopen this one.
> 
> Can you post your CRC for SVC?

Here it is : 
- SVC Chaos 94834BD3
- KOF 2002 ABD16263

**Comment by refractionpcsx2** [comment]
I'm not sure if KOF 2002 is the same thing (we've never had a CRC entry for that) but your version of SVC Chaos is missing.

Can you give me the Serial/Region of your version of SVC Chaos so we can add it please

**Comment by Immersion95** [comment]
It is this one http://redump.org/disc/37370/

**Comment by refractionpcsx2** [comment]
Okay, your serial differs from the normal serial, is your version modified?

**Comment by Immersion95** [comment]
> Okay, your CRC differs from the normal CRC, is your version modified?

Mine is not and matches exactly the one from redump. I converted my CHD to BIN/CUE and I have the same CRC.

**Comment by refractionpcsx2** [comment]
okay I've added your CRC for SVC Chaos, it should be there in 1.7.2701

**Comment by Immersion95** [comment]
> okay I've added your CRC for SVC Chaos, it should be there in 1.7.2701

Thanks, it does work :).

I also tried the patch on KOF2002 and it also solves the issue there. It would be great to also patch this game.

**Comment by refractionpcsx2** [comment]
I saw you made that PR, but you said it didn't work?

**Comment by Immersion95** [comment]
It was a noob mistake, I just wanted to do a quick test on my build.

But I can definately try to do the PR to add the patches to Kof2002.

**Comment by refractionpcsx2** [comment]
sure, can do, just be sure to comment it, if you don't rename SVCChaos

**Comment by Immersion95** [comment]
I created the PR for KOF2002, this issue can now be closed as SVCChaos works great now.

**Comment by refractionpcsx2** [comment]
The issue won't be closed until your PR merges, however you can mention in the OP of your PR "Fixes #1862" and that will auto close it when we merge it.

**Comment by Immersion95** [comment]
> The issue won't be closed until your PR merges, however you can mention in the OP of your PR "Fixes #1862" and that will auto close it when we merge it.

I understand but my PR solves KOF2002, it doesn't have anything to do with SVCChaos.
