### ISSUE TITLE
Test Drive: IPU hang in middle of Event 5

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1863]
***PCSX2 version:***
PCSX2 1.5.0-20170315183046 - compiled on Mar 15 2017

***PCSX2 options:***
Defaults, SkipMPEG hack and EE cyclerate -3 (for loading screen) - testing with normal cyclerate still had no effect

***Plugins used:***
Defaults

***Description of the issue:***
Game hangs in middle of Event 5 while driving.

***How to reproduce the issue:***
Start Event 5, game will hang at the 2nd police roadblock.

***Last known version to work:***
Unknown

***PC specifications:***
 i5-6600k@4.7Ghz, GTX 1070 SC, Windows 10 64-bit

Emulog: http://pastebin.com/zPY1uXbR

**Comment by FlatOutPS2** [comment]
Disable the SkipMPEG hack, and after the event has loaded also set EE cyclerate back to 0.

**Comment by MrCK1** [comment]
@FlatOutPS2 Disabling it had no effect, it still hangs in the same place.

**Comment by prafullpcsx2** [comment]
A memory card save before event 5 and a savestate before the hang point may prove useful.

**Comment by MrCK1** [comment]
I'll have to post them in a few hours. Right now I need my beauty rest ;)

**Comment by MrCK1** [comment]
@prafullpcsx2 @FlatOutPS2 Here's the memory card before and a savestate during event 5. (rename to .7z)

[testdrive_ipuhang.pdf](https://github.com/PCSX2/pcsx2/files/849230/testdrive_ipuhang.pdf)

**Comment by FlatOutPS2** [comment]
I have no use for those. :p I did manage to reproduce the issue with the PAL version.

**Comment by prafullpcsx2** [comment]
I can't manage to reproduce the issue with my US version. Loaded the memory card save, started event 5, cleared it in one go and reached event 6.

**Comment by MrCK1** [comment]
The game chugs a little further when using "Ignore DMAC writes when it is busy" but still freezes shortly after the checkpoint behind the police cars. The debug logs so far don't show anything blatantly wrong either 😛

**Comment by MrCK1** [comment]
@prafullpcsx2 What US disk do you have (SLUS-XXXXX) and what settings did you test with? Unless the issue is somehow bios related, it seems odd that you are the only one who can't reproduce it.

**Comment by MrCK1** [comment]
Quick update on this - it seems that IPU_CTRL is getting stuck sending a continuous busy signal, causing the hang. I'll post a log later.

**Comment by prafullpcsx2** [comment]
@MrCK1 Mine is also 202.13 and your memory card save loads fine with that. I was using default settings to test it but I had skipmpeghack enabled. Will try again after disabling that and see if I can reproduce the issue.

**Comment by MrCK1** [comment]
@prafullpcsx2 @refractionpcsx2

```
void SetBusy(bool busy=true)
	{
		BUSY = busy ? 0x80000000 : 0;
```
According to IPU.h, 0x80000000 is equivalent to a busy signal right?

Here's the full log: https://pastebin.com/7qVtEeVQ

End portion where the hang occurs.
```
eReg(001b47e4 1b33382a): HwWrite32    @ 0x10002000/IPU_CMD          <- 0x40000000
IPU (001b47e4 1b33382a): write32: IPU_CMD=0x40000000
IPU (001b47e4 1b33382a): FDEC command. Skip 0x0 bits, FIFO 0x0 qwords, BP 0x0, CHCR 0x30000005
eReg(001cd998 1b333835): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
IPU (001cd998 1b333846): ipu0Interrupt: 1b333846
eReg(001cd998 1b333846): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
IPU (001cd998 1b33384e): ipu1Interrupt 1b33384e:
IPU1 running when IPU1 DMA disabled! CHCR 30000005 QWC 0
eReg(001cd998 1b33384e): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
IPU (001cd998 1b333886): ipu0Interrupt: 1b333886
eReg(001cd998 1b333886): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
eReg(001cd998 1b3338b0): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
IPU (001cd998 1b3338c6): ipu0Interrupt: 1b3338c6
eReg(001cd998 1b3338c6): HwRead32     @ 0x10002010/IPU_CTRL         -> 0x80000000
```

**Comment by prafullpcsx2** [comment]
@MrCK1 Can you please also make a separate gsdx HW issue from this game? when ingame press start and menu text is invisible. It becomes visible with preload data frame but font is messed up.

**Comment by FlatOutPS2** [comment]
@prafullpcsx2 https://github.com/PCSX2/pcsx2/issues/1739 issue already exists. ;)

**Comment by FlatOutPS2** [comment]
@MrCK1 Can you try event 5 with this: [pcsx2 - Test Drive.zip](https://github.com/PCSX2/pcsx2/files/948211/pcsx2.-.Test.Drive.zip)

**Comment by MrCK1** [comment]
@FlatOutPS2 It works great but there's quite a bit of stutter while driving now - one of which was at the point where the game used to freeze. Did it end up being an IPU issue after all? I also noted that these billboards are no longer corrupt upon approach in the patched .exe

Before:
![gsdx_20170421203206](https://cloud.githubusercontent.com/assets/16314399/25299879/37018ae2-26d2-11e7-9a0f-2ad88eac34dc.png)

After:
![gsdx_20170421203324](https://cloud.githubusercontent.com/assets/16314399/25299878/37006496-26d2-11e7-8f56-d2c7513b41da.png)

**Comment by prafullpcsx2** [comment]
I tried every possible setting but I can't reproduce the hang issue (with or without skipmpeg). Also the billboards were never corrupt for me. I checked the crc and mine is different than yours so most probably all these issues are related to specific version of the game.

**Comment by MrCK1** [comment]
@FlatOutPS2 Any status on this, or will a PR be in the works later?

**Comment by FlatOutPS2** [comment]
> Any status on this, or will a PR be in the works later?

I still need to do some work on the code, and then test it on a couple of games. Once that's done I'll make a PR.

The short lock ups you experienced are likely caused by my fix, I had one of those too at some point. The file I posted was an early hacky fix just meant to confirm if it worked for you too. I've not experienced the issue since I made a better version of the fix.

**Comment by MrCK1** [comment]
OK. Unless you already fixed it, there is also corruption for a brief second before the first Atari FMV starts.

**Comment by MrCK1** [comment]
@FlatOutPS2 any update on the the patch so far? A 1.6 release target would be nice :sticktongueout

**Comment by MrCK1** [comment]
@FlatOutPS2 when you get a chance, can you post a new URL or make a quick PR so I can test this code again? I'd like to look at other games with IPU problems.

**Comment by FlatOutPS2** [comment]
@MrCK1 It would be better if you could make a blockdump for a couple of those games so I can look into fixing those along with this issue.
