### ISSUE TITLE
Devil may cry 3 -big black horizontal stripe in bottom-

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#1864]
***PCSX2 version:***
PCSX2 v1.50-dev-1934-ga3efc77 (March-16th-2017)

***PCSX2 options:***
Tested with default and custom settigns (3x IR, bilinear forced, crc hack partial)

***Plugins used:***
AVX2, Using OpenGL (But the problem doesn´t belog to the video backend, i tested too with DX11 hardware, and the problem is the same)

***Description of the issue:***
A black stripe appear in bottom of Devil may cry 3 (Special edition, i don´t know if this happens too in normal edition) this stripe crops the image.

***Last known version to work:***
I don´t know exactly, but i downloaded the latest PCSX2  5 or 6 weeks ago, and all was working OK.

**Comment by ssakash** [comment]
Could you provide a screenshot of the issue? [GS Dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be useful.

**Comment by LuismaSP89** [comment]
@ssakash 

Of course, here it is:

https://we.tl/xaXh7aTkGt
