### ISSUE TITLE
Johnny Moseley Mad Trix: FMV Height Issues

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1871]
***PCSX2 version:***
1.5.0-dev-1933

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults

***Description of the issue:***
(This is the same issue mentioned a few months ago in #961) The displayed FMVs have various issues - flickering, doubled images, ect.

***How to reproduce the issue:***
Boot with any renderer/HW or SW and the first screen will appear with the issue.

***Last known version to work:***
Never - FMVs do not show but are audible in 1.2.1 and 1.4.0

***PC specifications:***
i5-6600k@4.7Ghz, GTX 1070 SC, Windows 10 64-bit

GSDump (Captured in HW renderer): [JMMT_FMV_glitched](https://github.com/PCSX2/pcsx2/files/853439/JMMT_FMV_glitched.pdf) (Rename to .7z)

Callstack: [JMMT_FMV_HWcallstack](https://github.com/PCSX2/pcsx2/files/853425/JMMT_FMV_HWcallstack.txt)

[Captured Frame](https://drive.google.com/open?id=0Bw4EU0WRGcbbMGpKb3JKNWwzcEU) (Download [RenderDoc](https://renderdoc.org/) to view)

API Debug Log: (corresponding EIDs are in the callstack as well)
![jmmt_debuglog](https://cloud.githubusercontent.com/assets/16314399/24083565/ae498bb4-0caf-11e7-9e66-842a59db9c7b.png)

**Comment by FlatOutPS2** [comment]
If it's the same issue already collected in the meta issue, why did you make a new one for it?

**Comment by MrCK1** [comment]
I always considered the meta issue as a collection of submitted issues. It would've just gotten further buried in that issue and this feels like the proper way to keep track 😛

**Comment by FlatOutPS2** [comment]
As the issue is already collected in the meta issue, creating new seperate issues for all the games in a meta issue will only clutter and bury many more issues not part of a meta issue.

**Comment by gregory38** [comment]
The goal of meta issue is to collect all games that share the same issue. 
We have already 300 open issues (still climbing). I can't​ find my kitten anymore.
