### ISSUE TITLE
SD Gundam G Generation Wars (J) : Save games not working Black Screen

### ISSUE THREAD

**Issue by AkagiShiroe** [PCSX2/pcsx2#1873]
im using pcsx2-v1.5.0-dev-1949, while using old version it only throw you off to Title Screen (New Game \ Load Game). heres some log.
[log.txt](https://github.com/PCSX2/pcsx2/files/861204/log.txt)

**Comment by FlatOutPS2** [comment]
Please follow the issue template for posting issues: https://github.com/PCSX2/pcsx2/blob/master/ISSUE_TEMPLATE.md

And please post the complete contents of the emulog.txt file after the problem occurs. The file can be found in "My Documents\PCSX2\logs" for the installer version or in "PCSX2\logs" for the portable/binary version.

**Comment by FlatOutPS2** [comment]
Piracy still not supported: https://github.com/PCSX2/pcsx2/issues/1827

**Comment by AkagiShiroe** [comment]
so , you don't give any support this game? it even doesn't listed on DB.. and hard to find the original.. really hard.
