### ISSUE TITLE
Gran Turismo 3 - GT Racing Pack [PBPX-95503] Memory Card folder invalid filter

### ISSUE THREAD

**Issue by alondero** [PCSX2/pcsx2#1878]
***PCSX2 version:***
Development build v1.5.1961

***PCSX2 options:***
Memory Card (Folder), everything else default

***Plugins used:***
Default settings

***Description of the issue:***
With memory card folders selected, the GT3 save data is filtered out from this game as whilst the internal serial code of this game is PBPX-95503, the game still writes to ''BASCUS-97102GAMEDATA'' as per normal GT3 discs.
Suspect line in the log:
``McdSlot 0: [Folder] *******\Memory Cards
(FolderMcd) Indexing slot 0 with filter "PBPX-95503"``

***How to reproduce the issue:***
0. Ensure Memory Card Folders are in use in slot 1 and no memory card inserted in slot 2
0. Boot and Save Game
0. Exit PCSX2 and load again
0. Note that the auto-load screen didn't pop up nor any progress has been noted

***Last known version to work:***
Suspect this has always been the case since Memory Card folders were introduced.

***PC specifications:***
Windows 10, 4790k, GTX 980, 32GB Ram

**Comment by alondero** [comment]
Not really sure how this can be solved *cleanly*, but thought I'd log it anyway. Not sure if there are any other special edition discs that this affects?

**Comment by turtleli** [comment]
PR #1879 was merged, so this should be fixed. Closing.
