### ISSUE TITLE
pcsx2 opengl fail to initialize

### ISSUE THREAD

**Issue by AkagiShiroe** [PCSX2/pcsx2#1884]
im using this version : pcsx2-v1.5.0-dev-1977-gdf32564
its give me this error :
3.x GL context successfully created
Failed to find glCreateQueries
Failed to find glBindImageTexture
Failed to find glMemoryBarrier
Failed to find glCreateTextures
Failed to find glTextureStorage2D
Failed to find glTextureSubImage2D
Failed to find glCopyTextureSubImage2D
Failed to find glBindTextureUnit
Failed to find glGetTextureImage
Failed to find glTextureParameteri
Failed to find glGenerateTextureMipmap
Failed to find glCreateFramebuffers
Failed to find glClearNamedFramebufferfv
Failed to find glClearNamedFramebufferuiv
Failed to find glClearNamedFramebufferiv
Failed to find glNamedFramebufferTexture
Failed to find glNamedFramebufferDrawBuffers
Failed to find glNamedFramebufferReadBuffer
Failed to find glNamedFramebufferParameteri
Failed to find glCheckNamedFramebufferStatus
Failed to find glCreateBuffers
Failed to find glNamedBufferStorage
Failed to find glNamedBufferData
Failed to find glNamedBufferSubData
Failed to find glMapNamedBuffer
Failed to find glMapNamedBufferRange
Failed to find glUnmapNamedBuffer
Failed to find glFlushMappedNamedBufferRange
Failed to find glCreateSamplers
Failed to find glCreateProgramPipelines
Failed to find glClipControl
i have this spec:
Intel Core I3 530 3,0Ghz
NVIDIA Geforce 9600 GT 512MB Vram
8gb RAM (4GB 2x slot)

**Comment by gregory38** [comment]
Nvidia didn't implement some openGL extensions in your GPU. Either you switch to Nouveau/Linux driver or you use DX or you buy a recent GPU. The latter is likely the best option.

**Comment by gregory38** [comment]
Hum, I will see if I can reduce the requirements for the SW renderer (but no guarantee that it will be enough)

**Comment by gregory38** [comment]
I reduce the requirements for the SW renderer. I think the SW renderer will work. No dice for the HW renderer that requires a complete driver.

**Comment by AkagiShiroe** [comment]
well i got this when trying SW Renderer : 
3.x GL context successfully created
Failed to find glCreateQueries
Failed to find glBindImageTexture
Failed to find glMemoryBarrier
Failed to find glCreateTextures
Failed to find glTextureStorage2D
Failed to find glTextureSubImage2D
Failed to find glCopyTextureSubImage2D
Failed to find glBindTextureUnit
Failed to find glGetTextureImage
Failed to find glTextureParameteri
Failed to find glGenerateTextureMipmap
Failed to find glCreateFramebuffers
Failed to find glClearNamedFramebufferfv
Failed to find glClearNamedFramebufferuiv
Failed to find glClearNamedFramebufferiv
Failed to find glNamedFramebufferTexture
Failed to find glNamedFramebufferDrawBuffers
Failed to find glNamedFramebufferReadBuffer
Failed to find glNamedFramebufferParameteri
Failed to find glCheckNamedFramebufferStatus
Failed to find glCreateBuffers
Failed to find glNamedBufferStorage
Failed to find glNamedBufferData
Failed to find glNamedBufferSubData
Failed to find glMapNamedBuffer
Failed to find glMapNamedBufferRange
Failed to find glUnmapNamedBuffer
Failed to find glFlushMappedNamedBufferRange
Failed to find glCreateSamplers
Failed to find glCreateProgramPipelines
Failed to find glClipControl
Failed to find glTextureBarrier
Failed to find glGetTextureSubImage
OpenGL information. GPU: GeForce 9600 GT/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: 
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is NOT SUPPORTED
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is NOT SUPPORTED
ERROR: GL_ARB_buffer_storage is NOT SUPPORTED
INFO: GL_ARB_clear_texture is NOT SUPPORTED
INFO: GL_ARB_clip_control is NOT SUPPORTED
INFO: GL_ARB_direct_state_access is NOT SUPPORTED
INFO: GL_ARB_texture_barrier is NOT SUPPORTED
INFO: GL_ARB_get_texture_sub_image is NOT SUPPORTED

GL_ARB_texture_barrier: not supported ! Rendering will be corrupted
DSA is not supported. Expect slower performance

probably you could just add 3.3 context option on GUI so people can switch between newer and older proccessing api.

**Comment by gregory38** [comment]
Thanks for the test. I'm afraid I can't do better.

Nvidia didn't implement some openGL basic features in theirs drivers.

We don't have resources to implement an alternate renderer (aka pure 3.3). And honesty it would be useless. It would be both slower and less accurate than D3D. I recommend you to upgrade to a newer GPU.

**Comment by AkagiShiroe** [comment]
thx im just like to see OpenGL performance on PCSX2.. since they do better on PPSSPP... also could you fix some bug on D3D renderer? both 9 and 10.. they have similiar bug on performance and rendering.. and i see there's a chance to implement Hardware tesselation... :) well lets see if i have C+ 2015 to work with it.,

**Comment by gregory38** [comment]
You know a faster GPU will bring you better performance (in particular for upscaling). D3D/OpenGL are mostly in par at same accuracy level. Well, you need an Nvidia driver for the best performance.

I only use Linux so no I can't fix D3D renderer. Someone is working to implement some fixes but it won't fix all bugs.

**Comment by mrcmunir** [comment]
INFO: GL_ARB_shader_image_load_store is NOT SUPPORTED

Really? nvidia has removed features for old GPUs?

I would swear that this function was supported on older drivers (I can not check it since I do not have HW nowadays) But in its day I had support on an Nvidia 8000

Luckily I already made the transition to linux: P

**Comment by gregory38** [comment]
```
INFO: GL_ARB_shader_image_load_store is NOT SUPPORTED

Really? nvidia has removed features for old GPUs?
```
This extension is about allowing atomic memory access from shader. It requires at least a DX11 class GPU. So I doubt that it was supported by a 8800 GTS.
