### ISSUE TITLE
Add version information to Inis, 

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#1889]
Avoid a repeat of confusion/launcher compatibility issues associated with using inis_x.x.x folders https://github.com/PCSX2/pcsx2/issues/1090

Would be able to avoid issues of old inis across git builds.

Might not be needed for every ini file, I think PCSX2 resets its inis when you install a new stable version.
GSDX probably needs it, as it has been adding and removing/changing defaults of some settings.

**Comment by MrCK1** [comment]
The only inis folder that is named is inis_1.4.0 - but that was accidental, and already fixed wasn't it? I don't really understand what this would do.

**Comment by avih** [comment]
IIRC we used a version number in 1.4 due to some last minute incompatibility which was already too late to fix for the release. In general, we don't want a version number for the inis folder.

**Comment by MrCK1** [comment]
Regardless of the version, this sounds better than what I currently implemented in #1699, where we just ask users to backup what they want and remove everything else.

Like you suggested, what I can do instead is rename the ```inis``` folder to ```inis-backup``` before removing anything to solve this issue.

**Comment by MrCK1** [comment]
@avih @TheLastRar I pushed a fix for this on my PR mentioned earlier. For all previous releases, the installer will duplicate the old ```PCSX2``` folder in Documents and rename it to ```PCSX2_backup``` 

Is that good for you guys?

**Comment by avih** [comment]
@MrCK1 TBH this is a huge PR to approve and discuss in one go. Personally I think it would be better if you split it to smaller chunks.

**Comment by MrCK1** [comment]
Can we close this issue now? I believe the feature (automatic settings backup) added in #1699 fufils the request asked here.

**Comment by willkuer** [comment]
Doesn't solve the problem for orphis/appveyor/portable installs (as explicitely requested in the OP) but only when using the full stable installer.

**Comment by lightningterror** [comment]
For GSdx this will break backwards compatibility, sometimes you'll need to switch between different GSdx revisions for testing or other reasons.

Also this will create a big clutter if you also want to number dev builds' inis.

Besides release version #1699 already has this covered for people to make things extra easy. Dev builds are dev builds, you need to do a little bit of tweaking.

I'll be closing this unless someone disagrees.
