### ISSUE TITLE
error 5 

### ISSUE THREAD

**Issue by gamesplayer1** [PCSX2/pcsx2#1891]
build1.4.0
[wx] Failed to create a temporary file name (error 5: access is denied.)
[wx] can't open user configuration file.

this happen to the whole pcsx2 
the bios, plugin and everything

is there a way to fix this?

**Comment by MrCK1** [comment]
It's a very rare bug (see #445)

Try checking the folder permissions or deleting the folder and trying again.

**Comment by gamesplayer1** [comment]
well i

**Comment by gamesplayer1** [comment]
thanks for the help

i use the binary installer instead of the standalone and it is much better and i can play the game normally
