### ISSUE TITLE
GameIndex layout restructuring

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1893]
In my opinion a batter database should be able to: 
- [ ] "show the link" between different editions of the same game - [example](https://github.com/PCSX2/pcsx2/issues/1842#issuecomment-284166986) on why
- [ ] moreover, have *gamefixes* shared between similar releases, with only patches made on a single SKU basis
- [ ] settle down the languages situation, by figuring out whether knowing single ones is a worth *[curiosity](https://github.com/PCSX2/pcsx2/pull/825#issuecomment-140798024)* too; or just drop the -really hardly informative- aggregate "counter" otherwise then

**Comment by MrCK1** [comment]
GameDB YAML implementation is merged into master. Closing this.
