### ISSUE TITLE
DEV9ghzdrk error in console

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1898]
This isn't a major issue but it's a bit annoying since it spams the console.
I wasn't able to find a git report about it , if there is one then this can be closed.

Right so every time I click on"Plugin/BIOS Selector" I get a console error.

[wx] Failed to load shared library 'D:\Program Files\PCSX2\plugins\DEV9ghzdrk.dll' (error 126: the specified module could not be found.)

I have no idea what It could be causing the issue since pcsx2 works without any problems. This has been an ongoing issue for every 1.5.0 build. 
1.4.0(binary) seems fine.
If 1.4.0 was compiled with vs2013 then I suspect the issue to be related to vs2015

I3 4160 //amd r7 360 // windows 7 ultimate 64bit

**Comment by MrCK1** [comment]
That message is hidden in release builds, so it's probably not a big deal

**Comment by Blackbird88** [comment]
That happens if Winpcap isn't installed since that pluzgin needs it.

**Comment by mirh** [comment]
Shouldn't we make an issue for the *new* Dev9 plugin btw?

**Comment by FlatOutPS2** [comment]
> That message is hidden in release builds, so it's probably not a big deal

It's hidden in stable builds(v1.4.0), not in v1.5.0 git builds.
