### ISSUE TITLE
istable build v1.4.0, meanless lines

### ISSUE THREAD

**Issue by Jaytt** [PCSX2/pcsx2#1899]
Line 85 to 90 on BiosTools.cpp 
Those lines will never be executed, is inpossible to the variable "i" to get that value.

**Comment by ssakash** [comment]
You mean this part?

```
        uint i;
	romdir rd;

	for (i=0; i<512*1024; i++)
	{
		fp.Read( rd );
		if (strncmp( rd.fileName, "RESET", 5 ) == 0)
			break; /* found romdir */
	}

	if (i == 512*1024)
	{
		throw Exception::BadStream( fp.GetStreamName() )
			.SetDiagMsg(L"BIOS version check failed: 'RESET' tag could not be found.")
			.SetUserMsg(_("The selected BIOS file is not a valid PS2 BIOS.  Please re-configure."));
	}
```

``i`` will have a value of ``512*1024`` (too lazy to calculate it) after the for loop ends without finding a match for 'RESET' in romdir. Hence, the exception will get thrown eventually when no match is found. Though I do understand why someone might misunderstand the code, maybe to make the code easier to understand we could use a found and exception logic.

Something like this,

```
       romdir rd;
       bool found_romdir = false;

        for (int i=0; i<512*1024; i++)
        {
               fp.Read( rd );
               if (strncmp(rd.fileName, "RESET", 5) == 0)
               {
                       found_romdir = true;
                       break;
               }
        }

        if (!found_romdir)
        {
                throw Exception::BadStream( fp.GetStreamName() )
                        .SetDiagMsg(L"BIOS version check failed: 'RESET' tag could not be found.")
```

Though I don't really care much about it, you can decide.

**Comment by gregory38** [comment]
I will close the issue. There are various way to write the code. It is way to minor to bother.
