### ISSUE TITLE
Move GameIndex.dbf to git LFS

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#1911]
https://github.com/blog/1986-announcing-git-large-file-storage-lfs
https://github.com/git-lfs/git-lfs/wiki/Tutorial
Seems sooo easy :d

**Comment by avih** [comment]
I don't think there's a need, since it's a text file and diffs are small on updates.
Why do you think it should use LFS?

**Comment by mirh** [comment]
Boss said so in https://github.com/PCSX2/pcsx2/issues/1894#issuecomment-295419825

**Comment by gregory38** [comment]
Maybe we should force a repack. But I'm afraid that doing extensive operation on this file is a bad idea.

**Comment by mirh** [comment]
> ok I was wrong. You can forgot what I said.

Should I rename this to anything else? Like move cheat_ws to LFS, or purge/repack/cleanup repo?
Or just close?

**Comment by avih** [comment]
> Should I rename this to anything else? Like move cheat_ws to LFS, or purge/repack/cleanup repo?
> Or just close?

How about we just close it, and in the future if we bump into an issue we want to handle, then we open a new issue?

**Comment by mirh** [comment]
Considering you seemed to be continuing arguing on the other issue, I thought your comments were better to be separated from there where they are a bit OT.
