### ISSUE TITLE
sprite issues with need for speed most wanted black edition (SLES_538.57)

### ISSUE THREAD

**Issue by wilfredkl** [PCSX2/pcsx2#1913]
PC Specs:

CPU: Intel Core i5-7400 @ 3.0Ghz
GPU: Nvidia GTX 1050 2GB 

Build Description: PCSX2 1.4.0 - Windows

BIOS Used: Europe v02.00(04/11/2004) Console

EE/VU Clamp modes: Normal/Normal
EE/VU Rounding: Chop/Chop

Speedhacks Used:

N/A

Gamefixes Used:

N/A

Amount of testing done (little/medium/much/completed-game): medium

Comments:

Game seems to run at normal speed at a 50 fps solid

Bugs:

Game hase weird shadow/light casting going on see attached screenshot (those square black and semi white are not supposed to be square) .
and I noticed that the auto flush hack costs me around 25 fps (that 50%)

additional testing done:

Tried changing all hacks / gamefixes - no change
tried adjusting the EE/FPU rounding/clamping and/or the VU rounding/clamping to see if it fixes the issue
Status but - no effect

[b]Playable[/b]

game crc CRC: 805C3B3A 

aditional note
quote from CK1 on forum 
Edit: Looks like it might be a sprite issue with GSdx. 

![screenshot 2017-04-20 22 31 46](https://cloud.githubusercontent.com/assets/7046515/25296707/fa6c630a-26e9-11e7-9d5c-512e034dcdeb.png)

**Comment by FlatOutPS2** [comment]
Disable (widescreen) patches and cheats.

**Comment by wilfredkl** [comment]
these are disabled by default on my system I don't need cheats (so I keep telling myself) and most games do seem to support widescreen by themselves

did a few test again and the alpha hack seems stops it from drawing the rectangles doing so but it turns the lightning way up 

screen shot from same scene (plus a few milliseconds)
![screenshot 2017-04-21 23 54 08](https://cloud.githubusercontent.com/assets/7046515/25297459/27b19c00-26ee-11e7-99dd-39d508b16ae1.png)

Overexposed screenshot outside (as inside tunnel it doesn't really show and matter)
![screenshot 2017-04-21 23 57 20](https://cloud.githubusercontent.com/assets/7046515/25297481/58503e7a-26ee-11e7-909e-d3515b093281.png)

**Comment by FlatOutPS2** [comment]
In the GSdx settings set Internal Resolution to any of the native scaling options.

**Comment by wilfredkl** [comment]
no change, except for my computers performance overexposure or rectangle blocks stay.

**Comment by MrCK1** [comment]
@wilfredkl It looks like your texture filtering is set to Nearest. I would change it to Bilinear instead, as that might be what you're seeing now.

**Comment by mirh** [comment]
Also give a look to auto-flush hack, because at least in ace combat it helped with "dust sprites".

**Comment by lightningterror** [comment]
Can someone retest/confirm that this is an actual issue?

**Comment by lightningterror** [comment]
I wasn't able to reproduce any issue, game is rendered perfectly with High blending on OpenGL.
DX misses parts of sw blending for extra accuracy.
