### ISSUE TITLE
Gsdx OpenGL logo-ogl.bmp on Windows

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#192]
Because this is important and you know it :D

Not really, but it'd be cool UI fix. I tried going on it myself, but I have no idea where to begin. I assume this is because OGL on Linux and Windows are separate or something.
Gsdx.rc
IDB_LOGO-OGL               BITMAP                  "res\\logo-ogl.bmp"
resource.h
#define IDB_LOGO-OGL

And there are some sort of controls that switch the images in Gsdx.rc.

**Comment by karasuhebi** [comment]
I wanna see the logo too. When you gonna get on this @gregory38? :P

**Comment by ssakash** [comment]
I think displaying the logo will be a easy task (not sure) I'll try looking at it.

**Comment by gregory38** [comment]
Windows is not my field so it won't be me.

By the way, if someone ought to extend the gui to support extra opengl option.

**Comment by gregory38** [comment]
@ssakash 

Any news on it?

**Comment by ssakash** [comment]
I have the commit ready. I'll PR it after testing it.

**Comment by ssakash** [comment]
I can confirm that the logo displays quite well using the same method for the DX9 & DX11 logo. though, the one I created isn't quite nice. I will try creating a new thread on the forums for new BMP logo for Opengl. I will choose any nice logo available at the entries.

**Comment by gregory38** [comment]
created? You didn't reuse res/logo-ogl.bmp

**Comment by ssakash** [comment]
you mean this one ? https://raw.githubusercontent.com/PCSX2/pcsx2/master/plugins/GSdx/res/logo-ogl.bmp

It looked rather outdated, I thought it would be better creating a new logo for the opengl renderer (or) should I keep using the current  res/logo-ogl.bmp ?

**Comment by Blackbird88** [comment]
You could always add new one later. It's just matter of replacing the file.

**Comment by karasuhebi** [comment]
I think you should use the one that's there for now. I would imagine if a new one will be made, that same person can make a new one for the D3D variants as well for visual consistency.

**Comment by ssakash** [comment]
okay, I will use the current one then.

**Comment by Nobbs66** [comment]
any update on this ssakash?

**Comment by ssakash** [comment]
the commit's ready, I'll PR it after @mirhl cross checks the commit. (he mentioned that he will compile and check it after 5 days) If anyone else can compile it before and check it, just let me know.

I don't have VS2013 currently. the PC which had it is not available right now.

**Comment by karasuhebi** [comment]
From what I've observed in GitHub, that's what PRs are for, so people can check your work to make sure it's good enough to merge. Why wait?

**Comment by ssakash** [comment]
First, I'd have to make sure that it does the specific work before even sending a PR for the specific feature.

Please wait a little more time for @mirhl to compile it and check it out. As mentioned already, if anyone else can help compliling then please let me know. I'll provide the commits.

**Comment by gregory38** [comment]
honestly you can pipeline the work. When you feel it is ready just do a pr. Just write in the PR the current level of testing and the extra test needed. This way people can review the code when people does the test.

And by the way, it would be nice if you could reduce the level of verbosity ;) I can see the pr, don't worry.

**Comment by Yashdhiman** [comment]
I have created a logo for pcsx2 , if you intrested , I will show you.

**Comment by Yashdhiman** [comment]
this

**Comment by bositman** [comment]
I talked to our forum user bmate about this and asked him if he could come up with a decent logo for OpenGL. Here is his work:
https://dl.dropboxusercontent.com/u/36122479/01.bmp
https://dl.dropboxusercontent.com/u/36122479/02.bmp
https://dl.dropboxusercontent.com/u/36122479/03.bmp
https://dl.dropboxusercontent.com/u/36122479/04.bmp
https://dl.dropboxusercontent.com/u/36122479/05.bmp
https://dl.dropboxusercontent.com/u/36122479/06.bmp

IMO any of these is better than the one linked above, and since @gregory38 is the one who brought it to life, I leave it to him which one will be used :)

**Comment by Blackbird88** [comment]
In that case he might as well replace DX10 logo with DX11.

**Comment by ssakash** [comment]
yes, everyone one of the logo's are Excellently done !

**Comment by ssakash** [comment]
@gregory38 

the PR is made to use the current res/logo-ogl.bmp on opengl renderer. now it's just a matter of replacing the BMP file with your preferred choice.

**Comment by Nobbs66** [comment]
I like the first one.

**Comment by ssakash** [comment]
I also liked that one but, let's give @gregory38  the decision on choosing the logo. he was the one who improved Ogl to it's current state so, IMO he is the one who deserves to choose the logo.

**Comment by gregory38** [comment]
I already made my choice. Surprise ;)

**Comment by ssakash** [comment]
I don't think there has been a change, either ways I guess the Issue could be closed now ?

**Comment by ssakash** [comment]
nice choice. :+1:
