### ISSUE TITLE
[GSdx HW Bug] (PR #1853) Direct3D11 Render on Intel HD

### ISSUE THREAD

**Issue by KazushiMe** [PCSX2/pcsx2#1921]
***Description of the issue:***

I've found that PR #1853 introduced a bug, which made **D3D11** Render on **Intel HD** Graphics (**7th Kabylake**) totally corrupted and severe glitches. Other renders(GL, D3D9, D3D11 SW) work flawlessly.

I tested **with the latest driver** (15.45.16.4627) and previously released version (15.45.16.4590). (It does not seem like a driver problem though.)

***PCSX2 options:***

Default 1 - Safest (with all speed hacks disabled)

***Plugins used:***

GSdx (have tested SSE2/4.1/AVX2), LilyPad, SPU2-X with all default settings.

***Screen shots and GS Dumps:***

I'd take PS2 US BIOS as an example:

**1969:**
![1969](https://cloud.githubusercontent.com/assets/10450345/25562904/c38924aa-2dc3-11e7-913a-52cad97275fa.png)

GS Dump: [1969.zip](https://github.com/PCSX2/pcsx2/files/966646/1969.zip)

**1976:**
![1976](https://cloud.githubusercontent.com/assets/10450345/25562915/ef113450-2dc3-11e7-8e10-7176ab593030.png)

GS Dump: [1976.zip](https://github.com/PCSX2/pcsx2/files/966647/1976.zip)

***PC specifications:***

Intel Core m3-7y30, Intel HD Graphics 615, 4G RAM, Windows 10 Pro RS2.

**Comment by MrCK1** [comment]
D3D11 HW works fine for me on Skylake. Does it happen in places.besides the bios? I know it likes to glitch from time to time.

**Comment by KazushiMe** [comment]
@MrCK1 Yes.

***TotA***
The bug causes 3D scenes to flicker. When I try to move, the whole screen will flicker between black and white. 2D scenes like menu seem okay. 

Screen shots:
![1](https://cloud.githubusercontent.com/assets/10450345/25563909/3c9b4c0a-2dd9-11e7-83e8-fbb1e3a21efe.png)
![2](https://cloud.githubusercontent.com/assets/10450345/25563910/3cbf46f0-2dd9-11e7-9c0a-177de13f6882.png)

GS Dump:
[gs.zip](https://github.com/PCSX2/pcsx2/files/966703/gs.zip)

**Comment by gregory38** [comment]
It would be nice to find the bad commit. But first be sure you didn't have a wrong option. Maybe the Intel driver didn't like one.

**Comment by KazushiMe** [comment]
I use the same settings for these two versions. Furthermore, I've tried to check other options except for HW Hacks, but it doesn't seem to make any difference.

***1969:***
![1969](https://cloud.githubusercontent.com/assets/10450345/25565021/57a74cb0-2df2-11e7-9f0c-6e4d2d370403.png)

***1976:***
![1976](https://cloud.githubusercontent.com/assets/10450345/25565025/5d3b421c-2df2-11e7-898e-38f14cd1beaf.png)

PS: When using "Microsoft Basic Render Driver", the framerate dropped and the graphics corruption still existed. It's a shame that with Kabylake, I could not test with older Windows versions like 7/8.1 in a high-stability, official way.

**Comment by MrCK1** [comment]
@KazushiMe What version of the Intel HD Graphics driver are you using? Lenovo has specific drivers for my machine, but it may help pinpoint if the problem is possible on Intel's side. (I just want to see how close my driver is to yours)

**Comment by KazushiMe** [comment]
@MrCK1 [15.45.16.4627](https://downloadcenter.intel.com/download/26669/Graphics-Intel-Graphics-Driver-for-Windows-15-45-)

**Comment by mirh** [comment]
> It would be nice to find the bad commit.

http://www71.zippyshare.com/v/D9MOG9dO/file.html
Unfortunately everything between the first and second-last didn't compile though.

**Comment by mirh** [comment]
^
@KazushiMe  if you could test it, you know

**Comment by KazushiMe** [comment]
@mirh, sorry that I've been away for several days.
6c0d6f9253e719fa52f3ce24acd610d6f8fb9f42-SSE4.dll works but dc55076ef49c2c08910fadfceb4f917b23d7fdfa-SSE4.dll does not.
Tested with r1969 and latest r2067.

**Comment by turtleli** [comment]
Try the GSdx from https://ci.appveyor.com/api/buildjobs/5a9vlher3yu94iio/artifacts/pcsx2-v1.5.0-dev-1972-g45524b9fe-572-vs2015-Win32-AppVeyor.7z , which corresponds to commit 975441dfe97eaf2c191bf98b3c8c43902c2b7e4f plus the following compile fixup:
```
diff --git a/plugins/GSdx/GSRendererDX.cpp b/plugins/GSdx/GSRendererDX.cpp
index 567d60af9..b4e69818d 100644
--- a/plugins/GSdx/GSRendererDX.cpp
+++ b/plugins/GSdx/GSRendererDX.cpp
@@ -292,8 +292,6 @@ void GSRendererDX::DrawPrims(GSTexture* rt, GSTexture* ds, GSTextureCache::Sourc
 	bool ate_first_pass = m_context->TEST.DoFirstPass();
 	bool ate_second_pass = m_context->TEST.DoSecondPass();
 
-	m_gs_sel.key = 0;
-
 	vs_cb.Texture_Scale_Offset = GSVector4(0.0f);
 
 	GSTexture* rtcopy = NULL;
```
The other commits in between shouldn't have any effect on rendering.

**Comment by KazushiMe** [comment]
@turtleli It works!👍

**Comment by turtleli** [comment]
Ok, thanks for testing. That means the regression was introduced in 557b672232c7cc6b10e8811d956decfee091c459.

**Comment by gregory38** [comment]
Hum, I'm surprised it is working. 

The gs configuration doesn't feel right. Input primitive is based on vertex trace input
```
m_gs_sel.prim = m_vt.m_primclass;
```

But sprite could be either lines (need GS) or triangles (done on CPU).
```
+	case GS_SPRITE_CLASS:
+		if (!m_vt.m_accurate_stq && m_vertex.next > 32) { // <=> 16 sprites (based on Shadow Hearts)
+
+			t = D3D11_PRIMITIVE_TOPOLOGY_LINELIST;
+		} else {
+			Lines2Sprites();
+
+			t = D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
+		}
+		break;
```

And it doesn't seem to be skipped in SetupGS.
```
-	if(sel.prim > 0 && (sel.iip == 0 || sel.prim == 3)) // geometry shader works in every case, but not needed
+	bool Unscale_GSShader = (sel.point == 1 || sel.line == 1) && UserHacks_unscale_pt_ln;
+	if((sel.prim > 0 && (sel.iip == 0 || sel.prim == 3)) || Unscale_GSShader) // geometry shader works in every case, but not needed
```

**Comment by turtleli** [comment]
@KazushiMe Try the GSdx from https://ci.appveyor.com/api/buildjobs/55s2taoq63gk42wc/artifacts/pcsx2-v1.5.0-dev-2116-g4ad7ffc1d-577-vs2015-Win32-AppVeyor.7z . It corresponds to commit f8787ca6b9ab654ba6fe6155a6fb875b61bd9e93 plus the following change:
```
+++ b/plugins/GSdx/GSRendererDX11.cpp
@@ -70,14 +70,7 @@ void GSRendererDX11::SetupIA(const float& sx, const float& sy)
 
 		break;
 	case GS_SPRITE_CLASS:
-		if (!m_vt.m_accurate_stq && m_vertex.next > 32) { // <=> 16 sprites (based on Shadow Hearts)
-
-			t = D3D11_PRIMITIVE_TOPOLOGY_LINELIST;
-		} else {
-			Lines2Sprites();
-
-			t = D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
-		}
+		t = D3D11_PRIMITIVE_TOPOLOGY_LINELIST;
 		break;
 	case GS_TRIANGLE_CLASS:
 
```

**Comment by KazushiMe** [comment]
@turtleli Yes, it runs flawlessly.
