### ISSUE TITLE
Add support for DUALSHOCK®4 USB Wireless Adaptor

### ISSUE THREAD

**Issue by Trevonn** [PCSX2/pcsx2#1924]
***PCSX2 version:***
PCSX2 1.5.0-20170430234119

***Plugins used:***
OnePAD 20170430234119 2.0.0

`onepad: Joystick (Sony Interactive Entertainment DUALSHOCK®4 USB Wireless Adaptor,GUID:030000004c050000a00b000011010000) isn't yet supported by the SDL2 game controller API`

**Comment by mirh** [comment]
My educate guess is that you need to be using SDL-git http://hg.libsdl.org/SDL/rev/b6b7d611973e
and kernel 4.10 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=de66a1a04c25f2560a8dca7a95e2a150b0d5e17e

**Comment by gregory38** [comment]
@mirh no you don't need a new SDL. You can configure it with Steam or any 3rd party tool to build the Kernel<->SDL2 mapping. And then you can use it with `SDL_GAMECONTROLLERCONFIG` env variable.

Nevertheless, thanks you for the commit. I will add it to our db.

**Comment by mirh** [comment]
I'm not sure that was [supposed](http://hg.libsdl.org/SDL/rev/6ea28e12d303) to work alone :s
Couldn't you just pull the whole db then? And what's the difference between that and gabomdq's?

**Comment by gregory38** [comment]
There are all the same stuff. There is a DB integrated in SDL2 directly (few). Gabomdq is another one (bigger). And now we have the onepad's DB which include SDL2+Gabomdq+extra mapping.

However I will add a way to read the mapping from a file. Env variable is limited to a single entry.

**Comment by mirh** [comment]
Oh, cool. 
Perhaps update the link in our db to point directly to the repo https://github.com/gabomdq/SDL_GameControllerDB

---
In other news, I just noticed [this patch](http://www.spinics.net/lists/linux-input/msg50051.html) headed for 4.12. It doesn't look good for us.

**Comment by gregory38** [comment]
Well, at least it solves my issue with pressure sensitivity emulation. Current SDL2 API limits the code to press/release state.  So no pressure emulation. I wanted to implement more complex query to improve the support of pressure. I didn't do it yet as it requires to map the button as axis in the db.

But it will become useless, if the kernel doesn't support the axis anymore.

**Comment by gregory38** [comment]
Hum emphasize is mine.
```
The next patches (9-11) improve dualshock 3 support:
- The axes/button mapping has been suboptimal for a long time with axes
  even leaking into the ABS_MT range due to large amount of analog buttons.
  The ds3 now complies to the Linux gamepad spec and support for the analog
  buttons was dropped as there is no good way of expressing them, digital
  button state is preserved. ***We provided patches to SDL2, which is the main
  library through which users typically use game controllers. ***
```
So basically, it will break all applications that didn't use SDL in the first place or an older SDL version. And by older I mean, likely-not-yet-released SDL. Great. I hope the said patches are just an update of the db mapping, otherwise I'm screw.

**Comment by mirh** [comment]
Is it so hard to just check it? 😆 
http://hg.libsdl.org/SDL/log/9f9160df4f1f/src/joystick/SDL_gamecontrollerdb.h 

Anyway, could you ping him on the mailing list? Or perhaps I could open an issue on bugzilla to ask for "extensions" of gamepad api?

**Comment by gregory38** [comment]
A good dev is a lazy dev. To meditate :) I need to check what I have added in our db.

API is here. But current way is 1 line of code. Complex way is more work (and soon useless)

**Comment by mirh** [comment]
?
I was referring exactly to the kernel side of the thing. 
They dropped analog buttons to conform to gamepad spec [and my guess and hope is that they just didn't think there could be enough (if not any at all) actual use-cases to warrant for further mind-work]
So I wanted to raise them this point (I'm wary of the mailing list though :s)

**Comment by gregory38** [comment]
I sure they won't change for a single app. It is lots of trouble for most people all those axes.

Tbh, we really need to find a list of game that really depends on this feature. And which "button" need to support pressure.

**Comment by nhydock** [comment]
I know Gran Turismo also uses the analog face buttons for acceleration and braking if a person doesn't want to use the analog sticks.  Mad Maestro is the only game I know off the top of my head that requires it, everything else just has it as a feature.

**Comment by deadair3210** [comment]
Metal Gear Solid 3 requires it for switching aiming modes, lightly hold square = gun while run, harder = stop and gun, harder = look through gun, stop

**Comment by mirh** [comment]
GTA, MGS, Ace Combat, Ridge Racer V, Psi Ops, Star Ocean 3, some DoA, Zone of the Enders 2, Gran Turismo, Baldur's Gate: Dark Alliance, The Bouncer, some MLB: The Show, perhaps some FIFA and F1 game. 

In other news, feel free to CC yourself or sth :)
https://bugzilla.kernel.org/show_bug.cgi?id=195643
