### ISSUE TITLE
IOP: TLB miss in my video mode test homebrew

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1930]
I was planning on looking into the undocumented privileged GS registers related to vertical and horizontal timings by monitoring the register changes in my [homebrew](https://www.dropbox.com/s/i5aeb9ele6roqg4/VModeTest.elf?dl=0) but seems like the master branch is failing to properly load it, the log spews out some TLB miss errors which weren't the case before when I tried with it on an older version of PCSX2.

Hence I decided to start looking for the commit which introduced the issue and ta-duh, it's this one! https://github.com/PCSX2/pcsx2/commit/b3b1f3ac685da28030993e70ae6433175060d57e

@sudonim1 : I'd prefer if you could fix it ASAP, thank you.

**Comment by sudonim1** [comment]
I'll look into this soon, but I'll quickly mention that the last guy who had a similar issue was loading his homebrew from a network share and it went away when he tried a local path.

**Comment by gregory38** [comment]
@sudonim1 any news ?

**Comment by sudonim1** [comment]
You'd think so, wouldn't you?

**Comment by ramapcsx2** [comment]
A workaround idea:
Put the elf onto a CD, run ulaunch.elf, navigate to the elf on the CD, run the elf.
It's not a lot of work, might do the job.

**Comment by seapancake** [comment]
This is working for me on 2148, has this been fixed or am I missing something?

**Comment by gregory38** [comment]
@ssakash is it still an issue ?
