### ISSUE TITLE
ubuntu zesty repository doesn't have a release file

### ISSUE THREAD

**Issue by segersj** [PCSX2/pcsx2#1932]
***Description of the issue:***
I cannot even attempt to install. the error message from synaptic is "The repository 'http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu zesty Release' does not have a Release file."

***How to reproduce the issue:***
Install Ubuntu Gnome 17.04 
add the repository
start synaptic
click reload (equivalent to sudo apt-get update)

***PC specifications:***
CPU: Core i7 7700k not overclocked GPU: Asus nvidia GTX 1080 Turbo OS: Ubuntu Gnome 17.04 

Thank you for reading this. :)

**Comment by gregory38** [comment]
Ah yes, last PCSX2 release is quite old. I will upload the 1.4 too. Note there is also a daily ppa (less stable but with various niceties)

**Comment by gregory38** [comment]
I launched new build for recent Ubuntu
* Yakkety is good
* Zesty build is on-going.

**Comment by lightningterror** [comment]
I'll close this since it has been marked as fixed and no feedback was provided for a year now.

If the problem remains it can be reopened.
