### ISSUE TITLE
Compilation failure with wxgtk 3.0.3

### ISSUE THREAD

**Issue by alucryd** [PCSX2/pcsx2#1933]
Hi guys,

It seems there are some breaking changes in wxgtk 3.0.3 compared to 3.0.2, pcsx2 fails to build on Arch Linux since the upgrade. Please find the relevant log below:

[  9%] Linking CXX shared module libdev9null-0.5.0.so
In file included from /build/pcsx2-git/src/pcsx2/common/include/Utilities/Dependencies.h:206:0,
                 from /build/pcsx2-git/src/pcsx2/common/src/Utilities/PrecompiledHeader.h:21,
                 from /build/pcsx2-git/src/pcsx2/common/src/Utilities/AlignedMalloc.cpp:19:
/usr/include/wx-3.0/wx/string.h:211:15: error: ‘wxUniChar wxCStrData::operator[](unsigned int) const’ cannot be overloaded
     wxUniChar operator[](unsigned int n) const { return operator[](size_t(n)); }
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:207:22: error: with ‘wxUniChar wxCStrData::operator[](size_t) const’
     inline wxUniChar operator[](size_t n) const;
                      ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1551:15: error: ‘wxUniChar wxString::operator[](unsigned int) const’ cannot be overloaded
     wxUniChar operator[](unsigned int n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1548:15: error: with ‘wxUniChar wxString::operator[](size_t) const’
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1563:18: error: ‘wxUniCharRef wxString::operator[](unsigned int)’ cannot be overloaded
     wxUniCharRef operator[](unsigned int n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1560:18: error: with ‘wxUniCharRef wxString::operator[](size_t)’
     wxUniCharRef operator[](size_t n)
                  ^~~~~~~~
[  9%] Built target dev9null-0.5.0
In file included from /build/pcsx2-git/src/pcsx2/common/include/Utilities/Dependencies.h:206:0,
                 from /build/pcsx2-git/src/pcsx2/common/src/Utilities/PrecompiledHeader.h:21,
                 from /build/pcsx2-git/src/pcsx2/common/src/Utilities/CheckedStaticBox.cpp:16:
/usr/include/wx-3.0/wx/string.h:211:15: error: ‘wxUniChar wxCStrData::operator[](unsigned int) const’ cannot be overloaded
     wxUniChar operator[](unsigned int n) const { return operator[](size_t(n)); }
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:207:22: error: with ‘wxUniChar wxCStrData::operator[](size_t) const’
     inline wxUniChar operator[](size_t n) const;
                      ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1551:15: error: ‘wxUniChar wxString::operator[](unsigned int) const’ cannot be overloaded
     wxUniChar operator[](unsigned int n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1548:15: error: with ‘wxUniChar wxString::operator[](size_t) const’
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1563:18: error: ‘wxUniCharRef wxString::operator[](unsigned int)’ cannot be overloaded
     wxUniCharRef operator[](unsigned int n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1560:18: error: with ‘wxUniCharRef wxString::operator[](size_t)’
     wxUniCharRef operator[](size_t n)
                  ^~~~~~~~
make[2]: *** [common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/build.make:87: common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/AlignedMalloc.cpp.o] Error 1
[  9%] Linking CXX shared module libcdvdGigaherz.so
[  9%] Built target cdvdGigaherz
make[2]: *** [common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/build.make:111: common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/CheckedStaticBox.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by gregory38** [comment]
It seems you're​ trying to compile with a 64 bit version of wxwidget. Please check your env.

**Comment by turtleli** [comment]
The ArchLinux lib32-wxgtk package no longer creates a wx-config32-3.0 symlink. It only has a wx-config32 symlink now. Which IMO makes sense, since `--version=` can be used to specify the wx version anyway. I think we should probably add it to the path check.

**Comment by gregory38** [comment]
Sigh. I updated cmake. Please tell me if it is good now

**Comment by alucryd** [comment]
It is, awesome, thank you very much!

**Comment by ssakash** [comment]
@gregory38 

Do we really need a ``Fixed`` label? Isn't closing the issue enough to show that it's fixed? :P

**Comment by gregory38** [comment]
Said the guy that created a thousand of them.

I think it is useful for thing that we know is likely fixed but someone need to validate the fix.
