### ISSUE TITLE
PCSX2 exits when started with -DUSE_ASAN=TRUE

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1939]
***PCSX2 version:***
`pcsx2-2017.05.08_9b0b32533_master-x86_64-1_git`
`gcc-7.1.0_multilib-x86_64-1alien`

***PCSX2 options:***
Occurs with a default configuration.

***Description of the issue:***
If PCSX2 is compiled with `-DUSE_ASAN=TRUE` it will open a pop-up when starting that prints the following and then cleanly exits. I have confirmed this with both debug and devel builds.
```
Thread creation failure. An unspecified error occurred while trying to create the SysExecutor thread.
```
In gdb this requires hitting `^c` before confirming the pop-up to get the following backtrace.
https://pastebin.com/VtAyVAdw

And with valgrind the following issue will occur.
```
$ valgrind PCSX2 
==2972== Memcheck, a memory error detector
==2972== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==2972== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==2972== Command: PCSX2
==2972== 
==2972==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
==2972== 
==2972== HEAP SUMMARY:
==2972==     in use at exit: 0 bytes in 0 blocks
==2972==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==2972== 
==2972== All heap blocks were freed -- no leaks are possible
==2972== 
==2972== For counts of detected and suppressed errors, rerun with: -v
==2972== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
I guess this is yet another`gcc-7.1.0` issue.. Unfortunately it may make diagnosing the other ones more difficult? 

***How to reproduce the issue:***
1. Compile PCSX2 with `gcc-7.1.0` and `-DUSE_ASAN=TRUE`
2. Start PCSX2.

***Last known version to work:***
Unknown, I have never used this option before.

***PC specifications:***
OS: `Slackware64-current`
CPU: `amd fx 6350`
GPU: `GTX 780 Ti`

**Comment by turtleli** [comment]
Potentially related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77982. The option is a debugging aid.

**Comment by gregory38** [comment]
I hope I don't hit this bug on my debian :(

**Comment by turtleli** [comment]
Well, seems I can't use asan here, and I tried both gcc 6.3 and clang 4 (ArchLinux). glibc is 2.25.

**Comment by gregory38** [comment]
Same issue here, glibc is 2.24. So I posted a workaround.

@orbea 
If you run asan with PCSX2, you need to set this env variable.
`ASAN_OPTIONS=allow_user_segv_handler=1:abort_on_error=1`
