### ISSUE TITLE
GSdx HW: Texture Filtering setting is being applied to SW renderer

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1946]
***PCSX2 version:***
v1.5.0-dev-2078

***PCSX2 options:***
Defaults, Automatic Gamefixes (Nearest VU Rounding for GIF Packet Overflow in GH3)

***Plugins used:***
GSdx, defaults

***Description of the issue:***
~~[This commit](https://github.com/PCSX2/pcsx2/commit/0af80b7c8634ce7eecc9d7b0fb0d4ddca34f5d84 (v1.5.0-dev-1930-g0af80b7)
) changes the behavior of texture filtering in SW renderer, causing small black lines to be visible through sprites in Guitar Hero 3. I don't know if it affects other games at this time.~~

If the texture filtering setting is changed in the HW renderer, that setting will be applied to the SW renderer when switching, causing undesired texture offset, ect.

***How to reproduce the issue:***
GH3: boot the game, load a stage, and check the sprites.

***Last known version to work:***
Never

~~Regression was introduced in commit https://github.com/PCSX2/pcsx2/commit/0af80b7c8634ce7eecc9d7b0fb0d4ddca34f5d84 (v1.5.0-dev-1930-g0af80b7)~~

***PC specifications:***
Intel Core i5-6600k, GTX 1070, Windows 10 64-bit Home Edition

**Comment by gregory38** [comment]
It isn't a bug, it is a feature. Non-PS2 option might break the rendering but it allow
* to increase speed with nearest filter
* to improve sharpness with nearest filter
* to improve smoothness with bilinear

I won't duplicate the option for SW/HW renderer. Beside code now is common for all renderers (HW, CL, SW...)

**Comment by lightningterror** [comment]
If it's intended to work this way can this be closed ?
