### ISSUE TITLE
OnePad 2.0 Dev: cannot recognize USB gamepad (Logitech F310)

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#1953]
***PCSX2 version:***

development builds v1.5.xxx, manually build from git

***PCSX2 options:***

***Plugins used:***

Controller (PAD): OnePad 0-Dev 2.0.0

***Description of the issue:***

When using OnePad 2.0.0, the gamepad I have, Logitech F310, cannot be recognized. Cannot setup key bindings on configuration page.

But the OnePad 1.3.0 Legacy works fine with the same gamepad.

***How to reproduce the issue:***

1. Plug a USB gamepad to PC.
2. Start PCSX2.
3. In plugins/configuration dialog, choose  OnePad 0-Dev 2.0.0 as PAD option.
4. Configure PAD. Use game pad keys and joysticks as input.

***Last known version to work:***

Not sure.

***PC specifications:***

CPU: Intel Core i7 4710MQ
GPU: Intel HD Graphics 4600
OS: openSUSE Tumbleweed 64bit

**Comment by gregory38** [comment]
Key binding is automatic on new onepad. So you can't change it anymore on the GUI. So what is your issue? Pad isn't configured automatically or is it only the GUI ?

**Comment by guoyunhe** [comment]
Key binding was not automatically set with my game pad. I can still use the GUI to bind keys with mouse or keyboard. But not the game pad.

**Comment by gregory38** [comment]
In this case, we can configure it together (or you can use the legacy plugin) 
Check the PCSX2 terminal or the emulog. It should print you the GUID of the pad. Then you can use anti micro, steam big picture or SDL joystick configuration tool to build a Linux to SDL mapping string.

**Comment by guoyunhe** [comment]
I updated to a new git version 20170524 (before is 20170515 or something), and the gamepad works again with OnePad 2.0. Maybe some recent changes fixed this problem.
