### ISSUE TITLE
[Request] Resize display for fullscreen

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#1956]
***PCSX2 version:***
g49840bb

***Plugins used:***
GSdx

***Description of the issue:***

mirh suggested I post this as an issue. I play on a laptop with a display resolution of 3000:2000. In windowed mode, I can play full speed at native resolution. In fullscreen, I get slowdowns. If I lower my display resolution, the fullscreen slowdowns go away. This all happens without touching the internal resolution setting in PCSX2.

I experience similar issues with GLideN64. But GLideN64 has the option of changing your display size when switching to fullscreen mode, so I'm able to set my display resolution and GLideN64's internal resolution to the same value.

***How to reproduce the issue:***
Own a Surface Book.

***Last known version to work:***
None.

***PC specifications:***
CPU: Intel Core i5-6300u GPU: Gigabyte GTX 940m OS: Windows 10 64 Bit

**Comment by willkuer** [comment]
There is a workound if we talk about native only: Right click on the link to the exe -> Properties -> Compatibility settings -> tick 640×480 screen resolution. Not optimal but should more or less work. Unfortunately like that it will be hard to adjust the settings.

I guess that's exactly the point of exclusive fullscreen?

**Comment by mirh** [comment]
The thing is, I'm not sure how rendering the *same* amount of pixels, just presented on a window of a different size, would be supposed to kill framerate. 

Does a comparable performance hit appear if you use the HD Graphics 520?

**Comment by tony971** [comment]
> Does a comparable performance hit appear if you use the HD Graphics 520?

Both experience a 5-10 fps drop.

**Comment by mirh** [comment]
Both GL and dx?

**Comment by wareya** [comment]
>The thing is, I'm not sure how rendering the same amount of pixels, just presented on a window of a different size, would be supposed to kill framerate.

It's the compositor. The compositor has to composite all those pixels. At a lower resolution, the compositor has to composite less pixels. The monitor upscales the image to display it but it does so on a different processor than the game is being emulated on (it does it on a built-in thing designed for that purpose).

**Comment by mirh** [comment]
AFAIU *we* are handling upscaling (since stretch/fill/whatever options are in our menu)

p.s. seems like this could have been reported [8 years ago](http://forums.pcsx2.net/Thread-Pcsx2-slow-only-on-fullscreen) and on [dolphin](https://forums.dolphin-emu.org/Thread-dolphin-3-0-very-slow-performance-with-full-screen) (where there's an alleged regression range too)

**Comment by wareya** [comment]
What does upscaling have to do with the compositor?

**Comment by mirh** [comment]
Isn't the compositor always compositing the same amount of pixels ?

p.s. @tony971 does it make any difference whether you are playing in a ~700x400 window or ~2900x1900?

**Comment by mirh** [comment]
> Last I checked, pcsx2 stopped supporting exclusive fullscreen ~2010, so you can't open in exclusive fullscreen with a low resolution and avoid compositing unnecessary amounts of pixels

Actually yes, you can. At least AMD (and reportedly Intel) drivers automatically switch to it under OpenGL when a couple of conditions are met. 

> p.p.s. @tony971 does it make any difference whether you are playing in a ~700x400 window or ~2900x1900?

**Comment by tony971** [comment]
> p.p.s. @tony971 does it make any difference whether you are playing in a ~700x400 window or ~2900x1900?

Not that I've noticed. The only thing that makes a difference is the size of the desktop. If I switch the desktop resolution to something lower, that helps. My workaround up to this point has been changing the Windows compatibility settings to run PCSX2 in 640x480 resolution mode.

**Comment by mirh** [comment]
Ok I have really no ideas left then, aside of maybe trying to update drivers. 
Perhaps [tinkering](https://software.intel.com/en-us/gpa) with GPA could reveal something, I dunno. 

p.s. assuming we'd managed to solve this otherwise, nonetheless I guess your feature request could still  make sense in case one had a CRT - given they are not really that common maybe behind an .ini toggle (anyway discussion of that should follow #2059 imo)

**Comment by tony971** [comment]
Exclusive Fullscreen seems to fix the issue in other emulators. If that's ever re-implemented.

**Comment by mirh** [comment]
Uh.. Can you try any combination of rendering api (dx11/opengl), gpu (intel/nvidia), window/fullscreen and `EnableVsyncWindowFlag=` (enabled/disabled) property?
On latest git.

**Comment by willkuer** [comment]
Have you tried disabling all visual effects of windows? You can find it somewhere in the system settings and will make your windows (e.g startmenu) look like win9x. I think your desktop just puts a slight bit too much stress on your system even when idling. Let's assume it always needs around 10% of your gpu resources to show titlebar transparency, shadows, and stuff. Pcsx2 however needs 95% to work properly. If you can push the idle load from the assumed 10% to below 5% you'd be able to play at full speed.

It's just a theory but might work.

**Comment by FlatOutPS2** [comment]
> It's just a theory but might work.

It's not a theory, disabling aero will avoid this issue. It will look bad though.

**Comment by MrCK1** [comment]
I don't recall of disabling Aero is even a possibility in Win10.

**Comment by FlatOutPS2** [comment]
> I don't recall of disabling Aero is even a possibility in Win10.

Aero no longer exists after Win7, but you can turn off (most of) the same features and achieve a similar improvement.

**Comment by mirh** [comment]
Actually.. [yes you can](https://github.com/Phorofor/DWM.ForceSwitch). 
Make sure not to have anything important open though, for safety :x

**Comment by willkuer** [comment]
Maybe it's not needed to disable all of aero. The vsybc stuff you probably want to keep. But transparency and other gimmicks can be turned off.

**Comment by tony971** [comment]
I mean, my surface book is powerful enough to use aero in 99% of regulat usage. It's a bigger inconvenience to disable it whenever I use PCSX2 than it is to run in 640x480 compatibility mode.

**Comment by willkuer** [comment]
I think you can also disable visual effect as part of compatibility mode. You have to check which works better for you. I guess you can also control windows size via a batch/powershell file. It would be a script running like

```@echo off
<Set windows display size to 800x600>
pcsx2.exe
<Set windows display size back to default>```

**Comment by willkuer** [comment]
A shit I hate the huge diversity if markdown languages and I can not edit my answer using my mobile. Well whatever you will probably figure it out by once you google 'display resolution bat' or 'display resolution powershell'.

**Comment by tony971** [comment]
Right. I've used similar things to run programs without a UAC prompt. The compatibility setting works well enough for me. The only reason I'm keeping the issue open is in hopes that exclusive fullscreen gets reimplemented someday.

**Comment by mirh** [comment]
> The compatibility setting works well enough for me

We are trying to understand what in the first place is the issue. DWM? Visual effects? Theme?

**Comment by wareya** [comment]
What is the size of the window you used to run PCSX2 in to make it run faster? As stated in the OP:

>I play on a laptop with a display resolution of 3000:2000. In windowed mode, I can play full speed at native resolution. In fullscreen, I get slowdowns. If I lower my display resolution, the fullscreen slowdowns go away. This all happens without touching the internal resolution setting in PCSX2.

If it was small, this applies: The problem is the number of pixels being updated every frame when the output resolution is high. Yes, that actually has a performance impact. Yes, really. Yes, even though the game itself is rendering at a fixed resolution. No, reducing other stuff isn't going to affect it, they already said that running in a window

**Comment by mirh** [comment]
> Uh.. Can you try any combination of rendering api (dx11/opengl), gpu (intel/nvidia), window/fullscreen and `EnableVsyncWindowFlag=` (enabled/disabled) PCSX2_ui.ini property? On latest git. 
  
So.. While re-inviting to test that, @masterotaku can you post quick tl;dr noob how-to for exclusive fullscreen with specialK ?

**Comment by masterotaku** [comment]
Sure. I have all instructions here, with focus on 3D Vision, mind you: http://helixmod.blogspot.com.es/2018/01/pcsx2-dx11.html

Follow the "Installation" and "Booting games" steps. If you don't play in 3D, you can just extract the "d3d9.dll" and "d3d9.ini" from my fix to the PCSX2 folder and ignore the rest of files. "d3d9.ini" is already configured to make exclusive fullscreen work.

To check if you are truly in exclusive fullscreen after those steps, the easiest ways are:

- If you have a G-Sync monitor and use 144Hz, you shouldn't see any judder.
- If you force vsync in the drivers, you'll see that in non exckusive fullscreen, with the frame limiter disabled you can exceed the fps corresponding to your refresh rate. In exclusive fullscreen, you can't.

**Comment by RedDevilus** [comment]
Is this still an active issue?
