### ISSUE TITLE
Dynasty Warriors 3XL,4XL, Samurai Warriors XL,Samurai Warriors 2 XL cross-disc 100% Working

### ISSUE THREAD

**Issue by cau2babj** [PCSX2/pcsx2#1957]
https://www.youtube.com/watch?v=WwXYhQm6wDM&t=79s
this my way to load original data from dw3 to dw3xl,also i can do it with dw4xl,smxl,sm2xl too,so if you want i can post it in youtube,like and share a video to everybody wait it,tks.

**Comment by bositman** [comment]
We already know about this and it half works, some stages/characters still crash. Anyway the github issues are not the place for this.

**Comment by avih** [comment]
The place to add _new_ information, in _text_ and not video, is at #91 .

**Comment by cau2babj** [comment]
Bositman : Sr but nothing happen to me,i completed game with full characters have 5th weapon and items so i think it's crash cause your pcsx version,i am only trouble with memory card,sometimes when i click save it say no memory card,then i reclick again it's work.
avih : sr i'm newbie here so i will learn experience for next time
