### ISSUE TITLE
Smuggler's Run: Missing HW Shadows/Incorrect GS Dump Playback

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1958]
***PCSX2 version:***
v1.5.0-dev-2104-g49840bb

***PCSX2 options:***
Defaults, Safest

***Plugins used:***
Defaults. Both GSdx plugins used in the emulator and GSDumpGUI are matching versions

***Description of the issue:***
In Smuggler's Run, shadows near the player have never been rendered in any HW renderer. In addition to this however, the GS Dump shows an outline of the shadow in HW mode, where they were missing in-game. In all instances, distant shadows are still rendered normally.

***How to reproduce the issue:***
In-game: Boot game, drive to an area with shadows.

GSDump: Select any HW renderer, find first frame and observe shadows. As a side note, you can see the alpha texture of the trees shadows flicker at the top when stepping to another frame in the GSDump.

GSDump
[SmugglersRun_ShadowsHW.zip](https://github.com/PCSX2/pcsx2/files/1039265/SmugglersRun_ShadowsHW.zip)

***Last known version to work:***
Never

***PC specifications:***
Intel Core i5-6600k, GTX 1070, Windows 10 Home 64-bit

In-Game (HW):
![gsdx_20170530132642](https://cloud.githubusercontent.com/assets/16314399/26597571/67b2840c-4540-11e7-952f-ac7c2ceb9920.png)

GSDump (HW):
![gsdump](https://cloud.githubusercontent.com/assets/16314399/26597618/93a0db0e-4540-11e7-9187-e0eebd37a538.png)

**Comment by MrCK1** [comment]
Forgot to add in the report that both dumps I  captured in SW and HW have the playback issue. The dump that was uploaded was captured in the HW renderer.

**Comment by MrCK1** [comment]
Additional tests on real hardware shows that the game  uses pre-baked shadows at a distance and transitions to stencil shadows when the player gets closer. I believe this is why the shadows are disappearing when the player gets too close in HW renderers.

**Comment by gregory38** [comment]
Technically there is no stencil on GS.

Is SW renderer impacted (in game) ?
Did you try zerogs ?

**Comment by MrCK1** [comment]
SW renderer is not impacted.

I haven't tried zerogs yet, but some tests a while back with older versions of GSdx around 0.9.6; and they didn't have working shadows in HW either.

**Comment by gregory38** [comment]
If sw renderer is fine, it is likely a readback of GS memory by EE which is later transferred again to GS. I added some logs on readback and texture is dumped

**Comment by MrCK1** [comment]
@greogry38 So is there anything else I should get? I had no luck with captured frames from my graphics debugger, it doesn't get trace logs or anything unfortunately.

**Comment by gregory38** [comment]
Enable gsdx hidden dump option. Do you see gl error in your debugger (which is btw)?

**Comment by MrCK1** [comment]
I use RenderDoc: https://renderdoc.org

"Enable API validation" is the option used to get the GL debug logs, that's how I got the logs from Guitar Hero earlier. Unfortunately, this game doesn't print any GL debug, I don't get the individual drawcall frames either. It's a hit or miss depending on the game itself, I use a GSdx-debug plugin too.

I'll post example later frames later.

**Comment by MrCK1** [comment]
For some reason I can't edit my original comment, guess Github is glitching out. 

Anyways, I got a successful frame capture after some tinkering. For some reason, the missing alpha textures are positioned in an odd orientation.


![sr_alpha](https://user-images.githubusercontent.com/16314399/31106533-48c77b42-a7ba-11e7-9816-03fda4af132a.png)

![sr_terrain](https://user-images.githubusercontent.com/16314399/31106535-49a68602-a7ba-11e7-9759-d10ba431bf05.png)

**Comment by gregory38** [comment]
All gl messages are stored in a debug file (should be current dir). It will greatly help you to understand what happen. Debug build is quite verbose because you have all TC information.

The above message is about a texture depth effect. Typically the green channel of depth buffer (bit 8-16) are copyied into the alpha channel of a color buffer. Hint if the detection of the effect doesn't work, it is wrongly replaced by a FBMSK emulation. If you spot those message, there are likely a bug.

You need to check the code of InvalidateLocalMem. This function will transfer code from the GPU to the GS mem which could be send to EE. Check the code there are some GL related messages.

**Comment by MrCK1** [comment]
Here's the log: [SmugglersRun_opengl_debug_hw.txt](https://github.com/PCSX2/pcsx2/files/1360280/GSdx_opengl_debug_hw.txt)

**Comment by gregory38** [comment]
Log analysis. There is a color effect based on channels shuffle (from ba to rg). Around draw call 13. The source is located at 0x1180 and the destination is located at 0x1200. My feeling is that we have some kind of overlapping of color buffers/textures.

**Comment by MrCK1** [comment]
@gregory38 

Here's the context for drawcall 13. If you need 14, ect. let me know ;)

```
FRAME
	FBP (*32):0x1200
	FBW:16
	PSM:0x2
	FBMSK:0x0
```

**Comment by MrCK1** [comment]
New GS Dump: [smugglersrun_badtex.zip](https://github.com/PCSX2/pcsx2/files/1363061/smugglersrun_badtex.zip)

**Comment by gregory38** [comment]
Analysis main issue is about a texture channel implementation.
Input: 0x0/0x1180
Output: 0x80/0x1200
Effect: permutation of RG and BA channels

Tricks are 
* Input and output overlap
* The 0x80 offset will change page/pixel order

Permutation is easy to implement. But overlap/pixel positions will be tricky.

I'm not sure the game rely on overlapping. So I propose that we implement an hle dedicated shader to implement color channel shuffles. I'm afraid that shadow position will require the pixels position update too. But we will see if at least some shadows appear.
