### ISSUE TITLE
Building and bundling microphone usb plugin on the linux build?

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#1959]
The ppa build doesn't have a option for it, and they're the only way to play life line.

I think this is the right one: https://github.com/jackun/USBqemu-wheel, and i suppose i could build it, if i bothered to setup a chroot, but I thought i should mention it as a issue.

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)
