### ISSUE TITLE
Adding topics for the repository

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1960]
Github has recently introduced the idea of adding topics to your repositories : https://github.com/blog/2309-introducing-topics

Topics generally reflect the subject of the repository. As an example, the [Dolphin Emulator](https://github.com/dolphin-emu/dolphin) repository has the topics ``emulation``, ``gamecube``, ``wii``, ``emulator``& ``cpp``. The [PCSX2](https://github.com/PCSX2/pcsx2) repository still doesn't have any topics, I guess it would be useful to add them? Also seems like you need Admin access to the repository to add the topic labels, anyone interested?

**Comment by turtleli** [comment]
I added some. Any other suggestions?

**Comment by ssakash** [comment]
Thanks a lot for adding it so fast! I think these rudimentary ones are enough for the moment.
