### ISSUE TITLE
kung fu panda the game won't load

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1965]
The PCSX2 version that have the issue : 1.5 dev-2099-ge043822-windows-x86

I will describe the problem : the game Kung Fu Panda stuck at This screen
![image](https://user-images.githubusercontent.com/26351275/26899074-45baa0c0-4bce-11e7-9c47-2acba9ce6020.png)

PCSX2 options
![image](https://user-images.githubusercontent.com/26351275/26899176-ac8500f2-4bce-11e7-9172-de2ff4974998.png)
![image](https://user-images.githubusercontent.com/26351275/26899290-f6008a26-4bce-11e7-9ce9-b98352655164.png)
![image](https://user-images.githubusercontent.com/26351275/26899331-18e12b86-4bcf-11e7-8ba0-f8066a93ba59.png)
![image](https://user-images.githubusercontent.com/26351275/26899355-2bf8ceb8-4bcf-11e7-9b36-3809315f1287.png)
![image](https://user-images.githubusercontent.com/26351275/26899372-36585432-4bcf-11e7-86b6-983ef8cb0c9f.png)
Plugins used:
![image](https://user-images.githubusercontent.com/26351275/26899464-76ded94a-4bcf-11e7-9928-c03ac5921429.png)
 Note: This game work with the 1.4.0 version of the emulator but had bad graphics.
How to reproduce the issue: open pcsx2 and start Kung fu panda .
PC spécifications: Windows 10 creators update , AMD Phenom 2 x4 955 , nvidia gtx 560ti.

**Comment by atomic83GitHub** [comment]
I have forget That my screenshot contain 'Vu 0%' ,That meen mtvu is on.But I had tested with the configuration and it is the same result .

**Comment by atomic83GitHub** [comment]
And the avx2 plugin provide to à Another machine (i7)

**Comment by spring568** [comment]
IOP Realtime Kernel Ver. 2.2

    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥IRX¥SIO2MAN.IRX args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥IRX¥MCMAN.IRX args 0 arg 
loadmodule: id 26, ret 2
loadmodule: fname cdrom0:¥IRX¥MCSERV.IRX args 0 arg 
loadmodule: id 27, ret 2
loadmodule: fname cdrom0:¥IRX¥PADMAN.IRX args 0 arg 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥IRX¥MTAPMAN.IRX args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥IRX¥LIBSD.IRX args 0 arg 
loadmodule: id 30, ret 0
loadmodule: fname cdrom0:¥IRX¥SDRDRV.IRX args 0 arg 
SDR driver version 4.0.1 (C) SCEI
 Exit rsd_main 
loadmodule: id 31, ret 2
loadmodule: fname cdrom0:¥IRX¥LIQUID_F.IRX args 0 arg 
loadmodule: id 32, ret 0
Unknown device 'al Error'
Known devices are  mc:(Memory Card)  cdrom:(CD-ROM )  rom:(ROM/Flash)  tty:(CONSOLE) 
Out of IOP memory: 131072 bytes requested, 512 available <--- the game dies right here

 I'm assuming it went poof when it ran out of memory which I highly doubt is supposed to happen

**Comment by NNeto** [comment]
I was trying to play this game today on 1.4.0. Only Half of the screen was being shown with movies and I had those same glitches. Everything worked normally after using the software renderer, and I'm not getting bad graphics at all.

![pcsx2](https://user-images.githubusercontent.com/7104467/27510964-f794faea-58f1-11e7-89ae-48f122b573d2.PNG)

![pcsx2-2](https://user-images.githubusercontent.com/7104467/27510993-8a51507c-58f2-11e7-8fe2-6db68994ddb2.PNG)

![pcsx2-3](https://user-images.githubusercontent.com/7104467/27510994-8cf74c78-58f2-11e7-9229-1db6df52bfa9.PNG)

**Comment by ssakash** [comment]
@atomic83GitHub : It would be useful if you could bisect and find out the first version which introduced this issue.

**Comment by atomic83GitHub** [comment]
It will be longer but i serach imediately

**Comment by atomic83GitHub** [comment]
This is the 1.5.0-dev-1939-gf3a89f5 , probably related to lilypad

**Comment by atomic83GitHub** [comment]
I noticed that since the version 1.5 1939, the X key does not work in KungFuPanda, this is probably the problem.

**Comment by atomic83GitHub** [comment]
But many research are welcome :)

**Comment by ssakash** [comment]
Thanks for looking into it, you found the culprit build in a rather short amount of time. Remarkable testing prowess 👍

By the way, assigned this issue to the relevant members of the team.

**Comment by atomic83GitHub** [comment]
#ssakash Thanks! , Remarkable program and developers :)

**Comment by gregory38** [comment]
Fwiw, this PR trigger a coverity error (I think it is unrelated)

**Comment by turtleli** [comment]
Should be related to issue #1904.

**Comment by turtleli** [comment]
Is "Use Analog mode if possible" enabled (it's a per pad setting)? If so, try disabling it.

**Comment by atomic83GitHub** [comment]
I never enabled it.

**Comment by turtleli** [comment]
Can you test the builds I linked to in #1904?

**Comment by atomic83GitHub** [comment]
I will test later.

**Comment by atomic83GitHub** [comment]
No , it don't work with your version.

**Comment by turtleli** [comment]
Did you try all 3 versions?

**Comment by atomic83GitHub** [comment]
No only the last but i will test the other.

**Comment by atomic83GitHub** [comment]
The second version work.

**Comment by turtleli** [comment]
Does the first version work as well or is that broken?

**Comment by atomic83GitHub** [comment]
The first version don't work

**Comment by turtleli** [comment]
One final test, can you test https://ci.appveyor.com/api/buildjobs/legyjubbwv7rt5e5/artifacts/pcsx2-v1.5.0-dev-2137-g2f1a21b27-584-vs2015-Win32-AppVeyor.7z and tell me if it works or not? It's basically the second version without the commit from the first version.

Thanks for testing.

**Comment by atomic83GitHub** [comment]
I can't test now but if possible , someone can test this version ?

**Comment by atomic83GitHub** [comment]
Sorry but I am not able to test this version today for some reason, I will test this after some days , please wait ☺.

**Comment by atomic83GitHub** [comment]
After some test: yes, your final version work.

**Comment by FlatOutPS2** [comment]
@atomic83GitHub Can you upload a blockdump of this issue?

**Comment by atomic83GitHub** [comment]
Here is the blockdump you request:
https://drive.google.com/file/d/1xrX-AyeAyQpZ-dn7SzF11B1SKb-_kVHR/view?usp=sharing

**Comment by atomic83GitHub** [comment]
Here is the blockdump you request:
https://drive.google.com/file/d/1xrX-AyeAyQpZ-dn7SzF11B1SKb-_kVHR/view?usp=sharing

**Comment by Rafidmuhaiminwafi** [comment]
But I am getting no button detection problem.
