### ISSUE TITLE
Not a issue, but a Question

### ISSUE THREAD

**Issue by sero583** [PCSX2/pcsx2#1969]
Is a Android port ever planned? If such thing would happen would it run well?

**Comment by avih** [comment]
There's no concrete plan currently, maybe it would happen some day, and we can't know how well it will behave.

**Comment by sero583** [comment]
@avih Taking a look to "Play!" which needs still some work to be done to run well, would say me that PCSX2 for android wouldn't run well but I dont really think "Play!" isnt that well like PCSX2 implemented does, so maybe there be still a hope?

**Comment by ssakash** [comment]
>  so maybe there be still a hope?

Maybe there's a hope, but no one from the team seems interested on implementing it. That's the problem. :P

**Comment by sero583** [comment]
Ugh well would it be hard/possible to implement it to android, like Dolphin emulator is?

**Comment by avih** [comment]
Everything (almost) is possible, but it requires a considerable effort, and no current developer is interested in putting this effort. If some day someone starts working on it, we'll know more. For now, no one works or plans (as far as I know) to work on it. That's the situation.

**Comment by ssakash** [comment]
> Ugh well would it be hard/possible to implement it to android, like Dolphin emulator is?

Yes, it's a troublesome task. You have to port the plugins, retarget the recompilers and redo the whole GUI from scratch to have a more cross-platform GUI code.

**Comment by sero583** [comment]
@sskash You could also let the GUI code and make for different platforms different GUI's but the source well should be there. But running just on the native wise is possible as far as I got without all plugins? Just the emulation

**Comment by ssakash** [comment]
> But running just on the native wise is possible as far as I got without all plugins? Just the emulation

The plugins are also a part of the emulation, you can't have any video output without the GS plugin and you can't have any audio output without the SPU2 plugin. So no, you need all the plugins for proper emulation.

**Comment by sero583** [comment]
@ssakash Oh didn't knew anyway do you think PCSX2 would run better than "Play!" if it would be android compataible?

**Comment by willkuer** [comment]
Define 'better' in this context.

It would be awful slow on most mobiles.
It could run okishly slow on some high end tablets and drain their battery within some moments.

**Comment by gregory38** [comment]
IMHO, it would be better to promote PS2 game ported to Android. Experience would be so much better.

Anyway, the main issue is VU emulation. It requires huge float power. ARM devices got often crippled floating point unit (and it will likely throttle). All GPU emulation must be adapted to SoC technologies. The good news is various GS features will be easier to emulate on mobile (no PCIe link, programmable blending...). But upscaling will still be difficult.

PCSX2 is years of work. If you want the same quality on Android, you need to invest the same quantity of times. Yes it is an huge investment
