### ISSUE TITLE
Tokyo Xtreme Racer Drift 2 - Significant Performance Drops with OpenGL

### ISSUE THREAD

**Issue by nhydock** [PCSX2/pcsx2#1970]
***PCSX2 version:***
Most recently tested on v1.5.0-dev-2116-g8b245c1

***PCSX2 options:***
Using Preset 2

***Plugins used:***
GSdx AVX2 - OpenGL HW
GSdx SSE2 - OpenGL HW
Native Resolution, 0x Anisotropic, No HW Hacks

I tried to keep everything as out of the box

***Description of the issue:***
Significant slowdowns occur in menus where the cars are rendered.  Game also dips in performance significantly as soon as a car is on screen during races.  You can improve performance by going into first person view during solo races, but this shouldn't be necessary.

Issue is not present on DX9/DX11 versions of GSdx

***How to reproduce the issue:***
After loading up the game, go to the player's garage.  You will also notice performance dips in races when in bird's eye view.

***Last known version to work:***
This has been going on for a few years

***PC specifications:***
Tested on

Windows 10 64-bit / Manjaro Linux 64-bit
AMD Ryzen 5 1600 / AMD Phenom II X4 945
AMD Rx 470 4GB

I've tested the game on all permutations of the stated hardware and OS.

FPS Dip in races is not noticable on Ryzen builds in Native resolution, but quickly degrades when upscaling.  Both the AMD Phenom II and Ryzen builds suffer from significant performance drops in the menus however, going as low as 25fps on Ryzen.

**Comment by nhydock** [comment]
Just for benchmarking reference, I can run the game at 60fps with 8x native resolution, 16x anisotropic in Windows 10 with the DirectX 11 plugin with the Ryzen 5 1600 and Rx 470 without even breaking 10% cpu load, so that's pretty awesome.  In a race, EE never goes beyond 40% and GS stays around 20%

With the OpenGL plugin with the same pumped up settings, in a race EE stays around 15-18% and GS is constantly maxed out at 99-100%, 'causing the game to run at around 10fps.

I'm guessing this is probably related to
https://github.com/PCSX2/pcsx2/wiki/OpenGL-and-AMD-GPUs---All-you-need-to-know

**Comment by gregory38** [comment]
Option to try
* Disable accurate blending
* Disable accurate date
* Disable depth emulation (hw hack)
* Increase crc level

**Comment by nhydock** [comment]
Accurate Date and Depth emulation were already disabled.  Increasing crc level had no effect.  Decreasing blending unit accuracy to None did increase fps by about 10, but not enough to a playable state.

**Comment by gregory38** [comment]
Is GS thread  still at 100% without blending ?

**Comment by nhydock** [comment]
Even without blending it hovers between 95-98% when I'm not moving.  Jumps up to 100% as soon as the car begins to accelerate and advance through the track.

**Comment by lightningterror** [comment]
> AMD Rx 470 4GB

That's your problem. OpenGL drivers are really bad on AMD.
https://github.com/PCSX2/pcsx2/wiki/OpenGL-and-AMD-GPUs---All-you-need-to-know

**Comment by gregory38** [comment]
I'm not sure that AMD driver explains all the slowness

**Comment by nhydock** [comment]
Here's a GS Dump I did on OpenGL with the cranked up settings if that helps the investigation any
https://mega.nz/#!0FQnlAiB!lLudYRTgM-G-WHutQXEKUOyYkH5r4eyVKSTlyd65KB4

**Comment by nhydock** [comment]
Within the menus,
Blending Unit Accuracy: None
Internal Resolution: Native
GS 73% FPS 60

Blending Unit Accuracy: None
Internal Resolution: 4x
GS 99% FPS 50

Blending Unit Accuracy: None
Internal Resolution: 8x
GS 99% FPS 27

Blending Unit Accuracy: High
Internal Resolution: Native
GS 99% FPS 28

Blending Unit Accuracy: High
Internal Resolution: 4x
GS 99% FPS 23

Blending Unit Accuracy: High
Internal Resolution: 8x
GS 99% FPS 16

Here are 2 GS Dumps from the Menus

Native with Blending Unit Accuracy at None
https://mega.nz/#!BZIByCra!RabL-u311T2DCQv6mjidry0Ija_qTEmFG3KYo2_FUUs

Native with Blending Unit Accuracy at High
https://mega.nz/#!lcoGGY4S!f9Gi_q7LaXhX-RIL02so562UUgT7I_wV1FYEV_jdVS4

**Comment by MrCK1** [comment]
Sounds like a GPU bottleneck. The same thing used to happen with my GTX 750 whenever I exceeded 4x native in GT4.

**Comment by mirh** [comment]
> I'm not sure that AMD driver explains all the slowness

It quite sounds like to me. _Whatever_ the actual bug they have, different scenes can trigger it differently. 
E.g. in AC5, when in-menu the "advantage" of d3d11 is, say 20% at most. 
In-game it's like 500%.

**Comment by MrCK1** [comment]
@nhydock Any status update on this?

**Comment by nhydock** [comment]
I can test this again tonight.  I do not have an nvidia card, though, to see if it's just an amd problem.

**Comment by nhydock** [comment]
Doesn't look like anything has improved.  When I get up in the 4x and higher it still has the same amount of slow down according to the previous tests.  I updated to the build bot version available on windows for today (g49cea778a)

I did find a fun little quirk with how it does its rendering.  It's one of those games that'll have vertical stripes when you do upscaling.  Well, if you turn on the align sprite hack to resolve it, but also have the half-pixel offset hack on, which will cause the lines to return under certain lighting but blurred.  It appears as though the environment is drawn in a separate pass from the car, as the lines will appear bent as part of the reflection mapped onto the car.

![paosidgjaosdfg](https://user-images.githubusercontent.com/316728/33052357-7ba768b2-ce3c-11e7-86a3-606747ab1ea4.PNG)

**Comment by MrCK1** [comment]
If you run it at 3x is there still a slowdown? Most games will see diminishing returns after 4x and it's just more taxing on the emulator.

**Comment by nhydock** [comment]
There's slow downs in menus even at native resolution.  Races are able to play at 60fps when Blending Unit Accuracy is set to None when at 3x resolution.

Btw, this only affects OpenGL HW, slowdown is not present in OpenGL SW.

**Comment by lightningterror** [comment]
I'm 90% sure it's the AMD driver. DBZ BT3 has the same issue even on native resolution. Nvidia doesn't have that issue and the performance is the same between DX and Opengl, or Opengl is slightly faster.

**Comment by lightningterror** [comment]
Close #1552
