### ISSUE TITLE
GameDB improvement and missing patch files

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1976]
![image](https://user-images.githubusercontent.com/26351275/27491972-bac6987e-5844-11e7-8b7f-0d2d705d8b2b.png)

**Comment by MrCK1** [comment]
Is there a valid reason for these improvements? (Ie. Are they documented in the forums, ect.)

**Comment by lightningterror** [comment]
Apparently there is for Max Payne.
http://forums.pcsx2.net/Thread-Max-Payne-SLES-50325-E--29333

As for R&C is he talking about Going Commando?

Anyway here is the modified GameDB. Anyone care to test this out ? Don't wanna make a pr yet.
https://drive.google.com/open?id=0B8cQAq-Ko9-ueWpZOFp0TEVIWWM

**Comment by atomic83GitHub** [comment]
Yes its Ratchet and Clank Going Commando (Ratchet and Clank 2 in my country).

**Comment by atomic83GitHub** [comment]
Your GameDB work and solved these games but missing patch are not also added.

**Comment by lightningterror** [comment]
@MrCK1 I didn't add the VU I bit hack since i don't see it in the dbf file mentioning that it can be added.
Can it still be added with just adding "ScarfaceIbit = 1" ? Or other changes need to be done first before it can be used here?

**Comment by atomic83GitHub** [comment]
Oups , i have forget to added Metal gear solid 3 (all versions): VUs :Clamping mode , extra + preserv sign

**Comment by lightningterror** [comment]
Metal Gear Solid 3 Subsistence or Metal Gear Solid 3 Snake Eater ?

http://forums.pcsx2.net/Thread-Metal-Gear-Solid-3-Snake-Eater-SLES-82013-E--30514
It seems for Snake Eater the values shouldn't be changed since it was tested.

Also are you using the latest dev build ?

**Comment by atomic83GitHub** [comment]
I have used the 1.4.0 and the latest build but in this game , its strange because , if Clamping mode is set to Normal or never , it will cause many artefacts on screen in both versions.

**Comment by ssakash** [comment]
> Can it still be added with just adding "ScarfaceIbit = 1" ? Or other changes need to be done first before it can be used here?

It's actually ``ScarfaceIbitHack`` and yes, it'll work without doing any other internal change in the codebase.

**Comment by atomic83GitHub** [comment]
For MGS3 Screen artefacts is reduce on latest build but still here.

**Comment by lightningterror** [comment]
What about the other games , did you test them with the latest dev build as well?

**Comment by atomic83GitHub** [comment]
for mgs 3 its all version , all games are tested with both versions (1.4.0 and last build) and all games have issues on both versions.

**Comment by atomic83GitHub** [comment]
And Mercenaries 2 World in flames dont have the patch in frensh version

**Comment by atomic83GitHub** [comment]
The frensh version is named :Bratz  - the movie. , the hack is EE timing hack.

**Comment by lightningterror** [comment]
What does the timing hack fix ? Crashes ?

**Comment by atomic83GitHub** [comment]
This is the comment of the patch for Mercenaries 2 ://flickery textures

**Comment by lightningterror** [comment]
Mercenaries 2 seems to have ee timings fixes already.

**Comment by atomic83GitHub** [comment]
Yes but not the frensh version wich is named Bratz - the movie

**Comment by atomic83GitHub** [comment]
To be precise , all version have the hack but the frensh version dont have.

**Comment by lightningterror** [comment]
Can you tell me the serials of MGS3 that you have , also for Mercenaries 2 because "Bratz - the movie" seems to be an entirely different game.

**Comment by atomic83GitHub** [comment]
The serial of mgs 3 is : SLES 82042 - 82043 -82050 (the subsistence frensh version) and Bratz - the movie is probably an error in the GameDB beaucause the real name is Mercenaries 2 L'enfer des favelas.

**Comment by atomic83GitHub** [comment]
For Mercenaries 2 its : SES 54998

**Comment by atomic83GitHub** [comment]
SLES

**Comment by lightningterror** [comment]
Great , just for safety can you tell me the serials for the other games?
Ratchet and Clank 2 (pal)
Rayman revolution (pal)
Max payne (all versions)

**Comment by atomic83GitHub** [comment]
For ratchet and clank 2 its : SCES 51607/p (platinum version)  , for rayman revolution its : SLES 50044 and Max payne is : SLES 50326 (Note: I had say all version for Max Payne because i saw many post That tallk to the issues).

**Comment by lightningterror** [comment]
https://drive.google.com/open?id=0B8cQAq-Ko9-uVEdrV3FPMVRzcFk

Please test this out. Also re test Max Payne , I added the missing Vu I bit hack.

**Comment by atomic83GitHub** [comment]
everything works great ! Its a great improvement.

**Comment by atomic83GitHub** [comment]
Max Payne is now very stable and playable also , we can close the #964 issue

**Comment by lightningterror** [comment]
I wouldn't recommend closing that , this is just a workaround. When the issues are fixed with the emulation itself without needing any gamefixes it can be closed.

**Comment by atomic83GitHub** [comment]
And Mercenaries 2 frensh issue in now corrected!

**Comment by atomic83GitHub** [comment]
Ok

**Comment by lightningterror** [comment]
One final test , can you test again with this version ? Just minor edits and stuff before the pr
https://drive.google.com/open?id=0B8cQAq-Ko9-ueGV3NmZGWDdHVjg

**Comment by atomic83GitHub** [comment]
Everyphing is OK wee can PR

**Comment by mirh** [comment]
> When the issues are fixed with the emulation itself without needing any gamefixes it can be closed.

Mhh not sure there ever was this rule. 
I mean, if any there could be a "master" tracker issue, but anything more is just madness imo. 

---
Anyway, I see hacks actually supported are [17](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Pcsx2Config.cpp)
For some reason gameindex only mentions 15

**Comment by lightningterror** [comment]
> Mhh not sure there ever was this rule.

I'm just recommending since it's not actually fixed. I'm fine with it if it's closed.

> Anyway, I see hacks actually supported are 17
> For some reason gameindex only mentions 15

Maybe they weren't used  , I did add the "ScarfaceIbitHack" tho so that's 16 if we count the PR.

**Comment by lightningterror** [comment]
@atomic83GitHub I forgot to ask but can you tell me what each gamefix does on MaxPayne?
I'd like to add a bit more information as to what each does in the PR.

**Comment by atomic83GitHub** [comment]
Each gamefix avoid randomly crash and stability of the game.
