### ISSUE TITLE
[OnePad] DualShock 4 not recognized over USB

### ISSUE THREAD

**Issue by gourdcaptain** [PCSX2/pcsx2#1978]
***PCSX2 version:***
1.5.0.r2120.07c69ebed-1

OnePAD 2.0.0 plugin on Linux

***Description of the issue:***
When attempting to use a DualShock 4 over USB on Linux (hooked directly into the system), the plugin gives a "No Gamepad Detected" error.
The log has this output: "Controller,GUID:030000004c050000cc09000011810000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database."

***How to reproduce the issue:***
Enter OnePAD's plugin configuration and hit Gamepad Configuration

***PC specifications:***
CPU: Intel Core i7 6800k
GPU: Sapphire AMD Radeon RX 460
OS: Arch Linux

**Comment by gregory38** [comment]
I need to check the SDL2 repository.

**Comment by gregory38** [comment]
What is your kernel version ? 

What happen if you add this line in `inis/OnePAD2.ini`
```
SDL2 = 030000004c050000cc09000011810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,
```

**Comment by gourdcaptain** [comment]
Kernel 4.11.6. Adding that line to the OnePAD2 config lets the controller be detected and autoconfig'd, and worked in a _very_ quick test.

**Comment by gregory38** [comment]
I'm puzzled. I pick the line from onepad internal db. Where did you get the build ?

**Comment by gourdcaptain** [comment]
Self-compiled from the pcsx2 git tree.

On June 29, 2017 5:39:25 AM EDT, Gregory Hainaut <notifications@github.com> wrote:
>I'm puzzled. I pick the line from onepad internal db. Where did you get
>the build ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PCSX2_pcsx2_issues_1978-23issuecomment-2D311915955&d=DwICaQ&c=3buyMx9JlH1z22L_G5pM28wz_Ru6WjhVHwo-vpeS0Gk&r=0zQ8RN820LSg0alBA3zG9VWeCI6KR1FUJkKAfmvCcAs&m=Ij9add3iCqZd7VdrMGO6GKT2UMPQBlsDetYRb4Wf3jw&s=Qy219kfaYcDIlP5xHPQxNCiuySj-VEPefRKlYz0g0bo&e=
>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gregory38** [comment]
Hum, could you tell me the output of this command ? (update the path as needed)
```
strings bin/plugins/libonepad.so | grep 030000004c050000cc09000011810000
```

**Comment by gregory38** [comment]
Actually I think I nailed it. Could you test latest git please. Thanks you.

**Comment by gourdcaptain** [comment]
Compiled pcsx2-git-1.5.0.r2132 and it does work. Thanks. :)
