### ISSUE TITLE
Finding Nemo (The Game) Graphical regression with OpenGL

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1979]
***PCSX2 version:***
Last 1.5 dev build
***PCSX2 options:***

(The options are the same between the 2 versions)

Core:
Default settings 
GSDX
![image](https://user-images.githubusercontent.com/26351275/27515509-fe2f4afa-59a4-11e7-9508-b937763bc042.png)
![image](https://user-images.githubusercontent.com/26351275/27515514-172694be-59a5-11e7-98db-aa22b2b26f86.png)
***Plugins used:***
The last GSDX version of the 2 versions
***Description of the issue:***
Fiding Nemo don't look great with OpenGL in newer versions , look:
1.4.0
![image](https://user-images.githubusercontent.com/26351275/27515529-97158cf2-59a5-11e7-8909-7e04827f6b91.png)
1.5 dev
![image](https://user-images.githubusercontent.com/26351275/27515552-ec8e2748-59a5-11e7-8e67-05df0606318b.png)
***How to reproduce the issue:***
Load PCSX2 set OpenGL Hardware in GSDX and load Fiding Nemo
***Last known version to work:***
1.4.0 Stable version
***PC specifications:***
Intel Core 2 duo E8600 , GTX 780ti

**Comment by ssakash** [comment]
Just to get things straight,

* 1.4 + custom resolution (1920x1080) is good ✔️ 
* 1.5 (Latest development builds) + custom resolution is not good 🚫 

That's the case, right? Is the issue reproducible in native/ native scaling resolutions (2x,3x,4x...etc)? By the way, finding the first working version which caused the issue would always help make the developer's life easier. ;)

**Comment by atomic83GitHub** [comment]
Native resolution do the same error , and it wil be monger to found but i will made it :)

**Comment by atomic83GitHub** [comment]
Longer sorry

**Comment by atomic83GitHub** [comment]
Sorry but I am uncapable to found a working 1.5 version beacause the first 1.5 build on build orphis have the issue!

**Comment by atomic83GitHub** [comment]
I have found a working version wich is the 1.5 dev 31 
The bug is introduced between the 1.5 dev 31 and 1.5 dev 66

**Comment by atomic83GitHub** [comment]
I can confirm the death shader not working as it should look:
1.4
Without the death shader:
![image](https://user-images.githubusercontent.com/26351275/27516827-8fb80cac-59c1-11e7-827c-3f1182938410.png)
With the death shader:
![image](https://user-images.githubusercontent.com/26351275/27516832-ab85aafc-59c1-11e7-807d-8d49e6aa3e8f.png)
1.5
Without the death shader:
![image](https://user-images.githubusercontent.com/26351275/27516807-4e0cde86-59c1-11e7-8138-16dac670f9ae.png)
With the death shader:
![image](https://user-images.githubusercontent.com/26351275/27516796-272fddd6-59c1-11e7-9459-df67db01d9e8.png)

**Comment by lightningterror** [comment]
http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-640-g8ec1461&platform=windows-x86

http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-650-g726b901&platform=windows-x86

Test these as well please.

**Comment by atomic83GitHub** [comment]
The 640 version does not have the issue 
The 650 version have the issue

**Comment by gregory38** [comment]
The game uses depth effect so custom resolution will be broken. Xnative resolutions are oK, isn't it ?

**Comment by atomic83GitHub** [comment]
No they are not , the bug happen also with Xnative (and the native) resolution.

**Comment by ssakash** [comment]
> The game uses depth effect so custom resolution will be broken

Any reason on why the depth effects would be broken on custom resolution?

**Comment by gregory38** [comment]
A gsdump will be nice. Or did I miss it?

```
Do you know why the depth effects would be broken on custom resolutions?
```
Yes. Not implemented. Code needs the scaling factor to compute the absolute coodinate (ranges between [0;size]). It is currently set once at the beggining in m_convert.cb. The old code use relative coordinate (ranges between [0;1])

**Comment by atomic83GitHub** [comment]
Here it is : https://drive.google.com/file/d/0B0Ph0W1NYxIVOXZMTms1UGNZYjA/view?usp=sharing

**Comment by gregory38** [comment]
I don't see the issue in your dump. But I have another one from this game which is definitevely broken....

**Comment by gregory38** [comment]
So the regression is game uses integral float coordinate texture (to sample depth buffer). Whereas current code only support integer coordinate texture. I need to think how to fix it.

**Comment by gregory38** [comment]
I hacked something. So I can confirm the above issue. However there is another regression on the handling of color clamping. My guess is the fix of fbmask + colclip that doesn't support well some fast path. Debug is on-going.

**Comment by gregory38** [comment]
Actually my first hack didn't work so well 😛 Could you test the PR #1994, it should work now.

**Comment by MrCK1** [comment]
@gregory38 Should any regressions be expected from this PR? I'll test later tonight anyways.

**Comment by gregory38** [comment]
It should be fine. Few games should hit those code paths (the regression is quite old). Nemo must be tested ;)

**Comment by gregory38** [comment]
Anyone tested the PR on nemo ?

**Comment by atomic83GitHub** [comment]
The game is fine now : issue resolved
