### ISSUE TITLE
Space Chanel 5 part 2 cinematics DX11 issue

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1980]
***PCSX2 version:***
Last 1.5 build
***PCSX2 options:***

Same for the 2 versions

Core : default settings
GSDX :
![image](https://user-images.githubusercontent.com/26351275/27516002-ba94be7c-59b0-11e7-858d-95e4df7b3a7b.png)
![image](https://user-images.githubusercontent.com/26351275/27516005-d14dc3ca-59b0-11e7-85f9-1b41d5eb7d8a.png)

***Plugins used:***
Last GSDX in the 2 versions

***Description of the issue:***
The cinematics in DX11 mode are corupted for this game
Last 1.5 dev
![image](https://user-images.githubusercontent.com/26351275/27515997-7f5eae9e-59b0-11e7-8e55-d4d45e91b5a5.png)
1.5 2116
![image](https://user-images.githubusercontent.com/26351275/27516116-08617e0e-59b3-11e7-84b1-7af4a0dd32e8.png)

***How to reproduce the issue:***
Load pcsx2 , set DX11 mode in GSDX , enable hardware hack and unscale point and line option , load Space Chanel 5 part 2

***Last known version to work:***
1.5 dev 2116
(1.5 dev 2117 introduced the bug)
***PC specifications:***
Intel Core 2 duo e8600 , gtx 780ti

**Comment by turtleli** [comment]
So is this bug present only when "Unscale Point and Line" is enabled or is it present regardless of setting?

**Comment by atomic83GitHub** [comment]
No , il is present with or without.

**Comment by gregory38** [comment]
Hum, it could be related to the geometry shader stuff. There is a difference between OpenGL and Dx to handle the flat attribute (flat == same value for all vertices of the polygon). You can configure the provoking vertex (vertex that will give the value to others vertices) on OpenGL. So I uses the GS configuration (last vertex of primitives). However Dx uses the first vertex of primitive hence the more complex setup of geometry shaders.

**Comment by turtleli** [comment]
@atomic83GitHub Could you provide a GS dump?

**Comment by atomic83GitHub** [comment]
Yes but how send it to google drive?

**Comment by atomic83GitHub** [comment]
Ok :) .

**Comment by turtleli** [comment]
Well, I think the geometry shader doesn't handle gouraud shading for sprites properly. It only works properly for the flat shading case. I don't know how it's supposed to be handled.

It's been broken since at least v1.4.0.

**Comment by gregory38** [comment]
Is OpenGL good ? Hum, I see 2 draw by frame. First is a clear. And 2nd draw uses alpha testing (ATE/PS_ATST). Might worth to check the alpha test behavior. Maybe compare GPU state (with a GPU debugger) with OpenGL. Alpha test is emulated in 2 steps (GPU draw).
1/ draw the color and mask the depth
2/ draw the depth and mask the color

To answer your question, you just need to output the value and the GPU will interpolate them. The only trick is that flat values are copied to all vertices of the primitives, so the interpolation is a nop. Some parameters are always flat for sprite such as depth, Q, fog.

**Comment by gregory38** [comment]
```
It's been broken since at least v1.4.0.
```
I think ATE change are more recent. Could it be the infamous Nvidia driver bug (which is maybe not an Nvidia bug). @refractionpcsx2 is the expert.

**Comment by atomic83GitHub** [comment]
Note : On OpenGL it's fine.

**Comment by gregory38** [comment]
And DX9 ?

**Comment by atomic83GitHub** [comment]
DX9 is fine also.

**Comment by gregory38** [comment]
So it is definitevely related to the geometry shader.

**Comment by turtleli** [comment]
Hmm, I think DX9 and OpenGL assume all sprites use flat shading (IIP=0)? (unless I misread the code, I kinda skimmed it)

Problem with the DX11 geometry shader for the non-flat shading case is that it sets 3 of the vertices to the same colour and the remaining vertex (top left) is a different colour, which explains the weird triangle bug.

**Comment by gregory38** [comment]
Hum, I vaguely remember some code that always set GS_IIP to 0 for sprite.

**Comment by gregory38** [comment]
Hum. Section 3.2.2 of the manual. Point and sprite always use flat shading.

**Comment by turtleli** [comment]
Oh. In that case, I know how to fix it.

**Comment by gregory38** [comment]
Yeah just remove the ifdef. However I'm not sure it is a regression. It feels like a very old bug.

**Comment by turtleli** [comment]
Yeah, bug is at least 7 years old (didn't look further).
