### ISSUE TITLE
Xenosaga ep 1 - savepoints issue

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#1983]
Description of the issue:
This game can not be played normally, using ingame save-points brake the game and it boots into the firmware (BIOS), obiously workarround could be using save-states. 

I did some researches and it seems to be a long standing bug, surprisingly first save-point on the game tutorial works, but after that, every of them seem to suffer that bug. 

PCSX2 version:
PCSX2 1.5.0-20170513103906 - compiled on May 13 2017

PCSX2 options:
OpenGL Hardware, No hacks

Plugins used:
Bound GS: GSdx32-AVX2.dll [GSdx 20170513103906 (MSVC 19.00 AVX2/AVX2) 1.1.0]
Bound PAD: LilyPad.dll [LilyPad (20170513103906) 0.12.1]
Bound SPU2: Spu2-X.dll [SPU2-X 20170513103906 2.0.0]
Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20170513103906 0.11.0]
Bound USB: USBnull.dll [USBnull Driver 20170513103906 0.7.0]
Bound FW: FWnull.dll [FWnull Driver 20170513103906 0.7.0]
Bound DEV9: DEV9null.dll [DEV9null Driver 20170513103906 0.5.0]

-------------------------------------------------------------------------------------

I know this issue looks quite odd, but it would be great if anyone could have a look and point to the right direction to hopefully know more about what could cause it.

At this time I only know Xenosaga episode one suffers from this, but if you get interested, I can try the others two games on the trilogy.

Thanks in advance.

**Comment by trostboot** [comment]
It's an old issue, yes. It doesn't affect every save point in the game, but a good number of them. Xenosaga Episode II and III are not affected by this.

**Comment by MarcoEstevez** [comment]
Thanks for replay. I just wanted to register a formal defect on github.

**Comment by tadanokojin** [comment]
There is a patch that fixes this issue:
https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?pid=603236#pid603236

It's a bug with the game and not with the emulator. It is explained in the linked post.

**Comment by lightningterror** [comment]
Patch was added to master.
