### ISSUE TITLE
[Core proposition] add an option to auto increase/reduce the EE cyclerate

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1984]
(sorry for bad technical english)
I have a big idea to improve the support of PCSX2 to low-range and hight-range PCs (For the futur core i9 and x series of intel micro-pressesor)
The #1974 PR will improve this request:
The idea is simple:
When the emulator slows down , the EE cyclerate will be reduce to 5 to 5 %
When the processor is not fully used , the EE cyclerate will be increase to 5 to 5 %
This is optional and will can be enebeled by an option.
Do not hesitate to tell me that I'm crazy :)

**Comment by lightningterror** [comment]
I don't think it's a good idea since changing the cyclerate introduces glitches.

If speed alone was the changing factor then It would have been ok

**Comment by atomic83GitHub** [comment]
This is why it can be disabeled , like the speedhacks

**Comment by ramapcsx2** [comment]
It's a bad idea, sorry.
To begin with, it won't even work well. Each time the speedhack changes, it would recompile all EE code, causing lots of stutter.
Then there's the issue with frame rate depended game breakage.
It just won't work.
