### ISSUE TITLE
[Request Improvement] Add PCSX2 online in the master branch

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1985]
This project seems to be crazy but could greatly improve the emulator.
The idea is simple, play coop games (Ratchet Gladiator for example) online with, if possible, compatibility between platforms (linux to Windows etc ...) with a plugin (similar to the online's Project64 plugin).

**Comment by mirh** [comment]
Depends on #1841 I guess?

**Comment by atomic83GitHub** [comment]
Probably . This plugin can help the functionality.

**Comment by atomic83GitHub** [comment]
I will close it because someone do that with 'PCSX2 online', his work is available on the forums and seems to work great.

**Comment by mirh** [comment]
[Well](https://forums.pcsx2.net/Thread-PCSX2-Online-Plus), keeping this for integration wouldn't be bad either.

**Comment by atomic83GitHub** [comment]
Hum, after some thoughts, I will reopen this topic with a different name.

**Comment by lightningterror** [comment]
I'll close this in favor of #772
