### ISSUE TITLE
Adding submodules broke import from GitHub to Launchpad

### ISSUE THREAD

**Issue by helkaluin** [PCSX2/pcsx2#1990]
a26afbe9a1721ad0257074e591df526c68f36643 added submodules to the repo, which broke importing from GitHub to Launchpad, meaning the current latest Ubuntu daily build is stuck at 49840bb621d99b8b5124251b9510366eb9b1db07.

This might get tricky for you down the line as well with your stable builds PPA.

**Comment by mirh** [comment]
My [slightly](https://bugs.launchpad.net/bzr-git/+bug/402814) educated guess is that instead of git-to-bzr importing, git-to-git should be used.

**Comment by helkaluin** [comment]
Interesting... this should be trivial to fix then.  I'll look into it.  Thanks!

**Comment by helkaluin** [comment]
Right, it's all sorted now.  Thanks @mirh for the tip!
