### ISSUE TITLE
Sprint Cars 2: Showdown at Eldora [SLUS_216.01] - Broken vehicles behaviour

### ISSUE THREAD

**Issue by LoStraniero91** [PCSX2/pcsx2#1991]
***PCSX2 version:***
v1.5.0-dev-2125-g6e029fc

***PCSX2 options:***
Default settings: Clamping/Rounding have little to no effect, MTVU hack have no effect.

***Plugins used:***
GSdx OGL HW (no graphical bugs, so default settings are used), SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins.

***Description of the issue:***
During gameplay, player and IA vehicles behaviour is broken: all vehicles start to bounce like they have hydraulic suspensions and will freak out/roll uncontrollably, to the point they will eventually clip through the track. If this happens to the player, the race will "restart", but always with the same broken handling. 

Video of the bug: https://youtu.be/WUjRQCQp-Hg

***How to reproduce the issue:***
Start any race in any game mode.

***Last known version to work:***
No known version.

***PC specifications:***
CPU: Intel i5-3470 3.20GHz
GPU: NVIDIA GeForce GTX 650
RAM: 8 GB
OS: Windows 10 Pro 64 Bit

**Comment by FlatOutPS2** [comment]
@LoStraniero91 Did you try setting (Config -> Emulation Settings -> VUs) VU0 and VU1 to SuperVU?

**Comment by MrCK1** [comment]
Not sure if he's still active anymore - he's dead on the forums. I tested.Sprint Cars 1 a few months ago, it actually goes gets in-gane, but the cars fall through the track IIRC. No settings affected it.

**Comment by LoStraniero91** [comment]
@FlatOutPS2 
Just tried now with **v1.5.0-dev-2246-g36a1c7a26** with both VU0 and VU1 set to SuperVU and nothing has changed, I also get broken texture with SuperVU.

**Comment by FlatOutPS2** [comment]
Oh well, thanks for trying. It was worth checking as the behaviour is similar to something that can happen in Driving Emotion Type-S unless you use SuperVU.

**Comment by MrCK1** [comment]
@FlatOutPS2 according to the report, SuperVU is is required for both VU0 and VU1 

https://forums.pcsx2.net/Thread-Driving-Emotion-Type-S-SLUS-20113-U--28392
