### ISSUE TITLE
Metal Gear Solid 3 Subsistence : strange console error

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1992]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default

***Plugins used:***
All default

***GSDX options***
DX 11 : All default (OpenGL an DX 9 have the same issue)

***Description of the issue:***
A strange error appears in the console when ingame cutscene is play ,this error cause a huge slowdown (performance impact) : 
![image](https://user-images.githubusercontent.com/26351275/27770067-a9c29b90-5f38-11e7-9acd-9274f420ed94.png)

***How to reproduce the issue:***
Load MGS3 subsistence

***Last known version to work:***
Don't exist : all versions have the issue.

***PC specifications:***
Intel Core 2 Duo E8600 , GTX 780Ti , Windows 10 64 Bit

**Comment by MrCK1** [comment]
We've known about this GIF error. However, I'm pretty sure this one is just a warning, so nothing that bad is really happening. The game is very demanding to emulate.

**Comment by atomic83GitHub** [comment]
Sometimes the colors become crazy on the screen for less than a second during the gameplay, this issue is fixed by VUs Clamping Mode to extra + preserv sign .So I thought it was related to these messages :) .

**Comment by MrCK1** [comment]
Can you post a screenshot with the error? I've never  experienced these "crazy colors" before.

It's hard to say with the wiki down, but everything that you need for the game should be set with Automatic Gamefixes - do you have that enabled?

**Comment by atomic83GitHub** [comment]
This is the issue :
![image](https://user-images.githubusercontent.com/26351275/27772622-7db977ca-5f66-11e7-9950-dbebffe17b60.png)
Yes , automatic gamefix is enabled , many days ago , we had added a fix for this game to fix these issues (the wiki Mentioned this issue and the fix)

**Comment by MrCK1** [comment]
Are you using skipdraw, other GSdx hacks or manual gamefixes?

Tell me what dev build you're using, and I'll look at it tonight.

**Comment by atomic83GitHub** [comment]
I found! its Strange but It seems that if we remove the fix, the problem disappears. 
In reality , I had tested the game before integrate The #1977 to the GameDB with a member team and I  Never noticed that cause another bugs
REGRESSION ALERT!
