### ISSUE TITLE
The Suffering Ties That Bind: Graphical artifacts in effect/sprite heavy scenes

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1998]
***PCSX2 version:***
v1.5.0-dev-2133-g45ac69a

***PCSX2 options:***
Defaults, safest preset

***Plugins used:***
GSdx (all SW and HW renderers)

***Description of the issue:***
In scenes where alot of effects are present, pausing the game will cause the screen to flicker with graphical artifacts of some sort. This issue is present in all renderers in SW and HW modes respectively. 

Changing VU/EE/FPU rounding, clamping, or GSdx hacks do not affect the issue.

GSDump: 
[TSTTB_artifacts.zip](https://github.com/PCSX2/pcsx2/files/1118451/TSTTB_artifacts.zip)

***How to reproduce the issue:***
Find any in-game scene that contains many sprites on-screen at once and pause the game. 

***Last known version to work:***
Never, **however enabling the GIF FIFO gamefix removes the artifacting but corrupts alpha textures.**

***PC specifications:***
Intel Core i5-6600k, GTX 1070, Win 10 Home 64-bit

![gsdx_20170703001015](https://user-images.githubusercontent.com/16314399/27778237-3558b8d0-5f87-11e7-8290-df3a08531626.png)

**Comment by MrCK1** [comment]
Still not sure what this is, maybe it's a geometry overflow. The alpha corruption probably has more to do with the remaining TC issues I believe this game has.

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by MrCK1** [comment]
Took a long look at this yesterday. I can say without a doubt that the game requires the GIF FIFO, there's no way around that unfortunately. However, enabling it still causes problems with alpha textures so that will need to be fixed before this fix can be integrated into the GameDB.

**Comment by seta-san** [comment]
i think this one might be fixed.

**Comment by MrCK1** [comment]
No longer an issue, cannot reproduce on latest dev builds
