### ISSUE TITLE
Black : heavy character collision bug

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1999]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default : all speedhacks off (except MTVU)
Automatic Gamefixes : on
***Plugins used:***
All default

***Description of the issue:***
At various points during gameplay, the user's character teleports to a random nearby location. At various points during gameplay, the user's character may become stuck.
![capture](https://user-images.githubusercontent.com/26351275/27835800-d55bff58-60dc-11e7-9b9c-c126008ba10a.JPG)

***How to reproduce the issue:***
Load a level and walk Close to a wall.

***Last known version to work:***
Don't exist

***PC specifications:***
Intel Core 2 Duo E8600 GTX 780Ti Windows 10 64 Bit

***Note***
This bug also happen on backwards compatible ps3 systems.

**Comment by MrCK1** [comment]
Did you make sure it doesn't occur on PS2 hardware?

**Comment by atomic83GitHub** [comment]
There are 2 sort of backwards compatible ps3 the first one didn't had the issue (full ps2 hardware inside) , but the pal version had the GS but not the EE (wich is emulated) , this version have the issue , and the original ps2 didn't have the issue.

**Comment by homembarata** [comment]
This is still happening. Disabling EE speedhacks seem make the it more reliable.

**Comment by refractionpcsx2** [comment]
This is now fixed in master, if you have a version that isn't patched let me know.
