### ISSUE TITLE
Siren [NTSC SCUS-97355] Wall Of Fog Hardware Renderer Bug (DX11 matches OpenGL now)

### ISSUE THREAD

**Issue by 64fanatic** [PCSX2/pcsx2#2004]
***GS Dump***
***Memory Card with 100% game save***
***Save State***
[Siren Mega Folder to download said items - updated Jan 10 2019](https://mega.nz/#F!p50Q2YJA!84qjwcIuZakujnsyRWY8fQ)

***PCSX2 version:***
``(PCSX2 1.5.0-dev-2871-ge0877608a - compiled on Jan 9 2019)``

***PCSX2 options:***
``(Default Settings)``

***Plugins used:***
``(GSdx 20190109200529 (MSVC 19.00 AVX2/AVX2) 1.1.0)``
``(Pokopom XInput Pad Plugin 2.1.0)``
``(Default For Other Plugins)``

***Description of the issue:***
``- Wall of Fog when using Hardware Renderer modes. OpenGL and DirectX (directX backend recently improved to match OpenGL) broken with only half of the screen working correctly.``
``- Software renderer modes work correctly.``

***How to reproduce the issue:***
``- Use any hardware video renderer mode (dx11,opengl)``
``- Using any software video renderer mode works correctly ``

*OpenGL Hardware Mode: Depth Buffer Enabled*
![Depth Enabled](https://i.imgur.com/qVuFY9u.jpg)

*OpenGL Hardware Mode: Depth Buffer Disabled*
![Depth Disabled](https://i.imgur.com/SdIjt21.jpg)

*OpenGL Software Mode*
![Depth Disabled](https://i.imgur.com/nK0tFfG.jpg)

*DX11 Hardware Mode*
![Image of DX11 Hardware Mode](https://i.imgur.com/WOO7Inm.jpg)

*DX11 Software Mode*
![Image of DX11 Software Mode](https://i.imgur.com/ECYPXb0.jpg)

*Link Navigator,  go to Day 8 with Suda for the same level I was on.*
![link nav](http://i.imgur.com/xx664Nl.jpg)

***Last known version to work:***
``No previous version has worked correctly. In version 1.4.0 OpenGL Hardware Mode, enabling depth emulation also fixes half of the screen.``

***PC specifications:***
``(For example: CPU: Intel Core i7 4770k 3.8Ghz GPU: ASUS GTX 1080 8GB VRAM OS: Windows 10 Pro 64 Bit)``

**Comment by lightningterror** [comment]
Try using OpenGL and then as i remember correctly one of the hw hacks fixed the second half.
Turn them on/off one by one to figure out which one was it.

**Comment by 64fanatic** [comment]
None of them fix the second half.

**Comment by lightningterror** [comment]
Nah not that , I know one of them did it , can't check now since I'm not home.

**Comment by 64fanatic** [comment]
http://wiki.pcsx2.net/index.php/Siren

Haha, well if you remember/check later I'll add it to the wiki page!

**Comment by gregory38** [comment]
First, let's forget about Dx. Then I really need to look at the code to implement lookup inside depth buffer.

**Comment by atomic83GitHub** [comment]
Can you test the game with last dev build just for safety.

**Comment by lightningterror** [comment]
Siren has a missing crc for ntsc , added it but no change and I can't seem to figure out what the crc id's are used for, wasn't able to pickup anything on "search".

**Comment by 64fanatic** [comment]
Late as heck response was out of country, back and testing with latest dev build as atomic83GitHub requests:  PCSX2 1.5.0-20170816173532 - compiled on Aug 16 2017

As per gregory38, only worrying about OpenGL for video backend:

![depthopengl](https://user-images.githubusercontent.com/16341748/29615698-2104cde8-87cc-11e7-934f-9732aad75aad.jpg)

No change as of yet.

**Comment by lightningterror** [comment]
Can you try this ? Check if any of the hacks have an effect.
https://drive.google.com/open?id=0B8cQAq-Ko9-uenFwQXo4TTVkQkU

**Comment by 64fanatic** [comment]
Tried it out, no change.

**Comment by ListeningGarden** [comment]
Hey all,

Still seeing this issue on `v1.5.0-dev-2640-g0cbbf2daf`, which is the most recent build available via buildbot as of this post. As with the original post, the bug appears on all hardware rendering modes, though OpenGL's Depth Emulation seems to fix the issue for the left half of the screen, but not the right. Other video settings and hacks do not make a difference.

![gsdx_20181024024336](https://user-images.githubusercontent.com/36242661/47413563-9570b000-d73c-11e8-9985-1ebad330493b.jpg)

Would love to help test any hacks or patches to see if we can finally get this glitch taken care of!

**Comment by 64fanatic** [comment]
PCSX2 1.5.0-20190109200529 - compiled on Jan  9 2019

Directx11 hardware has improved in hardware when it comes to the fog wall bug, now matches OpenGL. Both are still incorrect however.

![untitled](https://user-images.githubusercontent.com/16341748/50961282-86201980-1484-11e9-9f83-8579752240f2.jpg)

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/1341

**Comment by refractionpcsx2** [comment]
[Siren_SCUS-97355_20230405024138.gs.zip](https://github.com/PCSX2/pcsx2/files/11153981/Siren_SCUS-97355_20230405024138.gs.zip)

New dump direct so it shouldn't get lost.
