### ISSUE TITLE
Zombie Hunters 2: misaligned bloom at native resolution with OGL HW

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2007]
***PCSX2 version:***
  v1.5.0-dev-2136-gbab9826

***PCSX2 options:***
  Default

  ***Plugins used:***
  Default

  ***Description of the issue:***
  The bloom on he player character is misaligned when comparing SW to OGL HW at native resolution, applying a TC offset value of x100,y100 seems to make the output of OGL HW more or less match the SW renderer.
Using the left of the motorcycle helmet a a reference. 
SW:
![pcsx2 2017-07-12 05-59-25-60](https://user-images.githubusercontent.com/30066566/28101203-478e96ea-66c7-11e7-9014-e8410dd453b2.png)

HW:
![pcsx2 2017-07-12 05-59-23-54](https://user-images.githubusercontent.com/30066566/28101214-4de0958e-66c7-11e7-9850-ffe8e6490a81.png)

HW w/ TC offset x100,y100:
![pcsx2 2017-07-12 06-01-12-76](https://user-images.githubusercontent.com/30066566/28101253-8f58bf64-66c7-11e7-98ed-a7adf801a6dd.png)

 Furthermore when applying any sort of upscaling the issue grows exponentially worse and isn't fixable 
 without causing other issues
8x native:
![pcsx2 2017-07-12 05-52-43-43](https://user-images.githubusercontent.com/30066566/28101145-ccbf434c-66c6-11e7-8e2e-ed766f7b81f4.png)

[GS dump here](https://mega.nz/#!8jI1xRhB!VwvZneno36RLe6o45xQLkAaKYJkboNJFcIzlCANkCho)

***How to reproduce the issue:***
1.Start a new game
2.Skip to gameplay

***Last known version to work:***
  Unknown

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (376.33)
  Windows 7.

EDIT: added GS dump and changed the screenshots to something that shows the issue a bit better

**Comment by MrCK1** [comment]
@Helium-4 Can you see if using the Auto Flush hack gets rid of the offset?

**Comment by Helium-4** [comment]
@MrCK1 It doesn't affect it at all.

**Comment by lightningterror** [comment]
Looks like Zombie Hunters 2 is Oneechanbara 2 Special in jap so I enabled the crc hack to work on this version as well.

Note: It's best to leave crc level on Automatic.

Anyway I'll close this now since it's an upscaling issue and a workaround has been added.

**Comment by Helium-4** [comment]
The issue at native res is still present though.
And one thing I didn't notice back then and that I'm noticing right now is that the portrait in the bottom left corner is not round in native res HW whereas it is in SW and same as the post FX it is fixed by applying the offset at native res

The workaround for upscaling is greatly appreciated nonetheless.

**Comment by Helium-4** [comment]
![image](https://user-images.githubusercontent.com/30066566/48667684-1fadf900-eadc-11e8-9961-c4093324a2e3.png)

Here's another couple screenshots where the issue I'm referring to might be slightly more visible especially on the left arm
HW Native res
![gsdx_20181118024912](https://user-images.githubusercontent.com/30066566/48667731-078aa980-eadd-11e8-8f31-566c20bc8ffc.png)
SW
![gsdx_20181118025030_ 2](https://user-images.githubusercontent.com/30066566/48667732-078aa980-eadd-11e8-95d8-9b33a0488d90.png)

**Comment by lightningterror** [comment]
I updated my comment from before :)
