### ISSUE TITLE
Onepad: Unable to configure controller

### ISSUE THREAD

**Issue by Lithium64** [PCSX2/pcsx2#2010]
***PCSX2 version:***
Latest 1.5 PPA build

***Plugins used:***
Gsdx, Onepad, SPU-2 X

***Description of the issue:***
Onepad don't recognize Microntec USB joystick and don't let me mapping controllers.

***PC specifications:***
CPU: i3 4150 GPU: Gigabyte R7 260x OS: Ubuntu 17.04 Kernel 4.12.2

**Comment by gregory38** [comment]
Yes the GUI is only for keyboard/mouse now. You can still use the onepad legacy plugin. In the PCSX2 console, some info should be printed. In particular the exact name and the UID of the controller.

It should be something like that
```
        fprintf(stderr, "onepad: Joystick (%s,GUID:%s) isn't yet supported by the SDL2 game controller API\n"
                        "Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick\n"
                        "The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'\n"
                        "Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.",
```

**Comment by xDShot** [comment]
So. Does it mean that Xbox buttons are automatically assigned to PS buttons? If so, what are exact bindings then? What if I want, say, assign LT button to L1? I assume legacy plugin version is to be removed later.

**Comment by gregory38** [comment]
Binding is done with the help of a SDL database. I can't tell you the binding. The DB is [here](https://github.com/PCSX2/pcsx2/blob/master/plugins/onepad/res/game_controller_db.txt)

You can still overload the SDL binding with a manual edit of the ini. (my previous post with SDL2 option). It isn't user friendly but there are external program that allow to generate this configuration string.

There is NO plan to remove the legacy plugin so far.

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/2495
