### ISSUE TITLE
GSDX GUI regression

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2019]
***PCSX2 version:***
Last 1.5 dev

***Description of the issue:***
The GUI (tested on Windows) have a bug in this section:
![image](https://user-images.githubusercontent.com/26351275/28493080-18eddf98-6f10-11e7-9e15-370505d91087.png)
Updating any shade boost value will cause a bug look:

Before updating value:
![image](https://user-images.githubusercontent.com/26351275/28493087-54db7f38-6f10-11e7-93f2-62eeea546cd2.png)

After updating value:
![image](https://user-images.githubusercontent.com/26351275/28493097-70535ae2-6f10-11e7-85b0-d4a1472cb23f.png)

***How to reproduce the issue:***
Load pcsx2 , GSDX and goes to the shader configuration section.

**Comment by MrCK1** [comment]
Technically it's not a regression, it's just bad GUI behavior. I can look into this later and maybe get a PR up for it if necessary 😛

**Comment by atomic83GitHub** [comment]
And by the way its seems there is an issue with the build orphis depo , 404 error everywere.

**Comment by ssakash** [comment]
> Technically it's not a regression

Nah, it's a regression. 😛 

I probably introduced it in #1925. Need to check though.
