### ISSUE TITLE
Widescreen patch for Final Fantasy X International forces English subtitles 

### ISSUE THREAD

**Issue by harlayzhou** [PCSX2/pcsx2#202]
It still display English even I select to Japanese in the option.
I have use the last git version.

**Comment by amnah** [comment]
Just ran into this. Was it added back in intentionally?

**Comment by willkuer** [comment]
Which version do you use? Try latest git release. Otherwise for such questions i highly recommend the forum instead of the git rep to discuss solutions. This problem appears to be easily solvable getting proper suppport (which you can find in the forum)

**Comment by amnah** [comment]
Yes sorry, I am using the latest git version v1.3.1-1461-g21857ec. Not really a problem for me, I just came across this github issue while casually browsing the repo. 

Anyway, wanted to make sure you guys knew that the force ```english patch=1``` was back in the ```658597E2.pnach``` file. If this was intentional, then just ignore these comments.

**Comment by willkuer** [comment]
There was recently an update of the widescreen hacks. Possibly this commit was accidentially reverted. I guess it would be good to inform devina - the current organizer of ws hacks - in the appropriate thread to avoid that in the future. Thanks for the information.

Btw. the correct way to disable cheats is to comment them by '//'. Replacing the one by a zero means that a cheat is only applied once during emulation directly in the beginning. This seems to be sufficient to disable this specific hack but is not the general solution.

**Comment by karasuhebi** [comment]
I went ahead and linked her to @amnah's comment:
http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=491902#pid491902

**Comment by Sarania** [comment]
I had brought this up before but got shot down. Anyway it looks like he's gonna comment it out now.
