### ISSUE TITLE
French language update

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2020]
In the recent dev build , there are some text that are in English look:
![image](https://user-images.githubusercontent.com/26351275/28493462-09f45c4e-6f18-11e7-8faa-7cde51cf48ff.png)
BOOT ISO (fast) must be changed to "Démarrer l'ISO (Rapide)"
BOOT ISO (full) must be changed to "Démarrer l'ISO (Complet)"
![image](https://user-images.githubusercontent.com/26351275/28493468-25405e08-6f18-11e7-8bd0-8ebf2d9d29f7.png)
BOOT BIOS must be changed to "Démarrer le BIOS"
![image](https://user-images.githubusercontent.com/26351275/28493479-47be1344-6f18-11e7-9964-ac089eabe139.png)
avoid constant recompilation must be changed to "Éviter une recompilation constante"
![image](https://user-images.githubusercontent.com/26351275/28493490-63bebf44-6f18-11e7-8d03-638b623b4aa3.png)
Switch to 4.3 aspect ratio when a FMV play must be changed to "Basculer l'écran virtuel en 4:3 quand une cinématique est lue"
![image](https://user-images.githubusercontent.com/26351275/28493500-724b8d26-6f18-11e7-9085-eb73b26bb8f0.png)
Must be changed to "Réduit la fréquence de l'EE à environ 75% de sa vitesse d'origine, accélération légère de l'émulation pour la plupart des jeux avec une compatibilité élevé."
![image](https://user-images.githubusercontent.com/26351275/28493504-7a83fcbc-6f18-11e7-9abf-46abd506a28f.png)
Must be changed to "Fréquence de base (100%). Ceci est à peu près équivalent à la vitesse réel de l'EmotionEngine."
![image](https://user-images.githubusercontent.com/26351275/28493512-874daf92-6f18-11e7-9f51-3f1f729b7cfe.png)
Must be changed to "Améliore la vitesse de l'EE à environ 180% de sa vitesse d'origine, demande plus de ressources matériel, pourrait grandement améliorer la vitesse de certains jeux."
![image](https://user-images.githubusercontent.com/26351275/28493517-94474884-6f18-11e7-823e-2101a8f630ca.png)
Must be changed to "Améliore la vitesse de l'EE à environ 300% de sa vitesse d'origine, demande beaucoup plus de ressources matériel, pourrait énormément améliorer la vitesse de certains jeux.
Ca paramètre pourrait empêcher certains jeux de charger! "
![image](https://user-images.githubusercontent.com/26351275/28493526-a4690770-6f18-11e7-96f0-e4ba95bdced4.png)
Must be changed to "Réduit la fréquence de l'EE à environ 50% de sa vitesse d'origine, grosse accélération de l'émulation mais peut causer des problèmes de latences dans les cinématiques."
![image](https://user-images.githubusercontent.com/26351275/28493531-b09af5f8-6f18-11e7-9206-a786d787c499.png)
Must be changed to "Réduit la fréquence de l'EE à environ 60% de sa vitesse d'origine accélération modéré de l'émulation mais peut causer des problèmes de latences dans les cinématiques."
![image](https://user-images.githubusercontent.com/26351275/28494052-4a638182-6f23-11e7-9c10-0ae2d01a89d8.png)
Must be changed to "Améliore la vitesse de l'EE à environ 130% de sa vitesse d'origine, demande un peu plus de ressources matériel, pourrait sensiblement améliorer la vitesse de certains jeux."
![image](https://user-images.githubusercontent.com/26351275/28501023-5c5cec06-6fd3-11e7-9f97-e68f3c37abf1.png)
Must be changed to "Choisir un iso"
No screenshot:
Always ask when booting must be changed to "Toujours demander au démarrage"
![image](https://user-images.githubusercontent.com/26351275/28684215-dff36d28-7303-11e7-92ab-6fa0bbbe62f9.png)
Boot CDVD (full) must be changed to "Démarrer le CDVD (Complet)"

**Comment by LeCharlatan** [comment]
I'd rather like " l'ISO " instead of " le CDVD " about those lines : 

BOOT ISO (fast) => "Démarrer l'ISO (Rapide)"
BOOT ISO (full) => "Démarrer l'ISO (Complet)"

Since CDVD is usually Physical Disc... here we launch ISO not really Disc or such so, I wonder...

Well, that's not a big matter tho, wanted to bring some idea about it :)

**Comment by atomic83GitHub** [comment]
Yes , it's a good idea , I have update this.

**Comment by LeCharlatan** [comment]
Nice ! I think that sounds really better like this, thank you :)

**Comment by atomic83GitHub** [comment]
The translation are ready if you want.

**Comment by LeCharlatan** [comment]
If translation's ready, need to update it :D

**Comment by lightningterror** [comment]
Can some of you guys update the translations? These are the locations for files that need editing.
https://github.com/PCSX2/pcsx2/tree/master/locales/fr_FR

https://github.com/PCSX2/pcsx2/tree/master/bin/Langs/fr_FR

Side note:  Other languages also need updating as well. Anyway I'll close this since it's not really an issue.

**Comment by atomic83GitHub** [comment]
I have done it but I can't push it, don't have the acces to the respository :(.

**Comment by lightningterror** [comment]
You make the changes on your forked repo , commit on a branch there and they you create a pull request using the changes on your fork to pcsx2 master.

**Comment by MrCK1** [comment]
If he doesn't have access, he's pushing to PCSX2 master instead of origin.

**Comment by lightningterror** [comment]
Do you have the files ready? I can PR them for you if you like.

**Comment by atomic83GitHub** [comment]
Here is the updated files: hope it will work.
https://drive.google.com/file/d/0B0Ph0W1NYxIVZnNnRjRxaWdpLU0/view?usp=sharing
