### ISSUE TITLE
GSdx: Incomplete texture shuffle/ or depth emulation on texture shuffle

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2022]
***PCSX2 version:***
v1.5.0-dev-2143-g1d983a681

***PCSX2 options:***
Default options , no fixes , native resolution

***Description of the issue:***
PAL games that require Depth Emulation are rendered incorrectly compared to their NTSC counterparts.
Only part of the textures are rendered in pal versions leaving the rest untouched or making it worse.
Related issue #1339

***How to reproduce the issue:***
Test pal games that make use of depth emulation and compare them to ntsc counterparts.

***Last known version to work:***
None

***PC specifications:***
i3 4160 , r7 360 amd , windows 7 64 bit

***Additional info:***
Affected games: DBZ BT3 #2001 (pal), Area 51 (pal)
Other games are very likely to be affected.

_Games that also had their crc hacks (depth related) moved to dx only should also be checked as they might experience glitches on opengl pal versions._

For comparison Area 51
Depth off
![gsdx_20170722200837](https://user-images.githubusercontent.com/18107717/28493739-fc376520-6f1b-11e7-90db-c8523d1f14d5.png)

Depth on
![gsdx_20170722200811](https://user-images.githubusercontent.com/18107717/28493742-08129a22-6f1c-11e7-811e-929a2fa75bd2.png)

Area51 GS Dumps
https://drive.google.com/file/d/0B8cQAq-Ko9-uZE1GcWFUbmNlTVU/view?usp=sharing

**Comment by atomic83GitHub** [comment]
Yes , same issue on Rayman revolution and Half life (pal).

**Comment by MrCK1** [comment]
Somebody who owns a PS2 with PAL bios should test these games to make sure it's not just an error related to playing PAL games with NTSC bios. Can't hurt to try I guess.

**Comment by atomic83GitHub** [comment]
I have a pal bios with these games :) .

**Comment by Hirato** [comment]
I wonder if the workaround gregory put in place for FFX-2 ( 247d33a62705cc809321408fa5bd93e577a851c8 )is related to this, since my FFX-2 was also PAL region.

**Comment by lightningterror** [comment]
Nah the issue is present on 1.4 as well so it's not that. That code works for all regions btw so it's not just for pal.

**Comment by Hirato** [comment]
I was more just wondering if that issue shared a common cause,
I didn't mean to imply "I wonder if this caused it."

Much like the showcase here, the game had all manner of rendering oddities
unless you disabled the depth buffer in the userhacks section - until that
workaround was added.

On 26 Jul. 2017 08:03, "lightningterror" <notifications@github.com> wrote:

Nah the issue is present on 1.4 as well so it's not that. That code works
for all regions btw so it's not just for pal.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PCSX2/pcsx2/issues/2022#issuecomment-317907822>, or mute
the thread

**Comment by lightningterror** [comment]
I'll add this to 1.6 milestone as it seems important for pal games while their ntsc counterparts are working fine.

**Comment by MrCK1** [comment]
@LightningTerror If you really want this as a 1.6 milestone, you still need to go further back and see when this was introduced. It's most likely a regression.

**Comment by gregory38** [comment]
For the story, pal games have a higher resolution than ntsc. Therefore there isn't enough room in the GS mem. Game designer avoid this limit with various tricks. The TC doesn't like tricks ;) For example the half bottom depth issue.

**Comment by MrCK1** [comment]
Alright, maybe this needs to be another meta. I don't know how many games this affects currently.

**Comment by lightningterror** [comment]
I'll remove this from the 1.6 milestone as well since this issue is the same/similar as #1339
And all of these issues probably won't be fixed for 1.6 so let's keep a realistic milestone.

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/1318
