### ISSUE TITLE
Update mesa blacklist

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#2025]
https://github.com/PCSX2/pcsx2/blob/6589feaacdff52b0dfcca57bb2107c3fcf70d051/plugins/GSdx/GLLoader.cpp#L275

https://mesamatrix.net/
I'm not sure there's an easy mechanism to distinguish between r600/radeonsi or nv50/nvc0 - but if not any core GL spec could be checked (for say, >4.1 or <4.5)

Fixes [this](https://www.reddit.com/r/linux_gaming/comments/6ox8si/pcsx2_stopped_working_after_upgrade_to_fedora_26/)

**Comment by gregory38** [comment]
You mean in 1.4 branch ? Because it doesn't impact any code.

It could also be a true Mesa bug.

**Comment by mirh** [comment]
> Buggy driver detected. Geometry shaders will be disabled
> Buggy driver detected, GL_ARB_separate_shader_objects will be disabled

That seems some code impact.

**Comment by gregory38** [comment]
I mean in current GIT. And it must work without those extensions (it only impact speed).

**Comment by mirh** [comment]
Also, the comment a bit above

> found_GL_ARB_clear_texture || GL_ARB_draw_buffers_blend

Seems supported by every driver. Not sure if Dx10 class gpu still have it and you want to note (at least 10.1 [does](http://opengl.gpuinfo.org/gl_generatereport.php?reportID=1950))

> GL_ARB_shader_image_load_store

Wired to Fermi+ and GCN+

**Comment by gregory38** [comment]
Those comments are a bit outdated. There were extracted from Mesa code. Anyway, it isn't important.

Oh by the way, I use both Mesa and Nvidia drivers. Maybe I should test a 1.4 build with Mesa.

**Comment by gregory38** [comment]
As posted on the forum, it could be the GCC7 bug.

**Comment by rcaridade145** [comment]
Does this make sense in 2018 considering the advances on Mesa?

**Comment by gregory38** [comment]
@rcaridade145 I don't think there is any blacklist for mesa on "recent" git version.

@mirh Could this bug be closed ? Or do you see a particular blacklist that should be removed ?

**Comment by rcaridade145** [comment]
@gregory38 I think some blacklist so be in use because of this bug  #2144 . A rx460 should be fast enough on mesa or amdgpu by now.

**Comment by gregory38** [comment]
Reality is that
* proprietary driver isn't good perf wise (even on windows)
* Mesa misses some bits to improve threading on texture upload. See #1403

**Comment by mirh** [comment]
I'm a bit left wondering why I opened this, when 885ef7a46ffa7aee92d693563c0f1f30c0917c12 had already happened. 
Sorry?
Closing. 

Though, for the records, you could still improve comments I guess. 
GL_ARB_shader_image_load_store is now supported on every shader5 card
GL_ARB_viewport_array is also supported by SB since https://github.com/mesa3d/mesa/commit/5fc23375e80dd2084f30700bdd3216082f662acc
Last but not least, I guess like leveraging GL_ARB_texture_filter_anisotropic from open drivers might be neater?
