### ISSUE TITLE
Wild Arms 4 PAL (SLES-54239) - Not showing refresh rate choice screen

### ISSUE THREAD

**Issue by LeCharlatan** [PCSX2/pcsx2#2026]
Hello,

Here are basics informations :

***PCSX2 :***

**Build :** Dev PCSX 1.5.0~git201707251955 (PPA PCSX2 Team Daily Builds)

***PCSX2 options :***

**GSDX:** OGL Backend
**Speed hacks :** OFF

***GSDX Options :***

**Texture Filtering :** Bilinear (PS2)
**Large Framebuffer :** ON (Checked)
**Internal Resolution :** 2x Native
**Anisotropic Filtering :** OFF
**Blending Unit Accuracy :** High (Recommended high-end PC)
**Automatic CRC level :** Partial (OpenGL Recommended)
**Mipmapping (Insert) :** Basic (Fast)
**Mipmapping :** ON (Checked)

**Description of the issue:**
PCSX2 isn't showing choice screen about refresh rate monitor in OGL HW (maybe just not showing caracters only, dunno)
![screenshot_20170726_161216](https://user-images.githubusercontent.com/22820335/28629558-12245802-7228-11e7-8fe2-5c84c55fb076.png)

But it does on OGL SW
![screenshot_20170726_161408](https://user-images.githubusercontent.com/22820335/28629568-1ac38762-7228-11e7-9f3f-71fc7e60d1c6.png)

***How to reproduce the issue:***
Just launch the game with OGL HW.
About DirectX 9/11 I've no idea since I'm not able to use it on Linux

***Last known version to work:***
None

***PC specifications :***

**OS :** Kubuntu 16.04 (Xenial)
**CPU :** Intel i5 4690K (Haswell)
**GPU :** Nvidia GTX 1070 + Proprietary drivers 381.22
**RAM :** 32Go DDR3-1600

**Little note :** Since @gregory38 told me to report bugs as soon as I find one, I'm reporting ! :p

**Comment by ssakash** [comment]
Could you provide a [GS Dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue?

**Comment by LeCharlatan** [comment]
Off course, here it is 

Single frame is enough I think... or hope

[gsdx_20170726175900.zip](https://github.com/PCSX2/pcsx2/files/1177239/gsdx_20170726175900.zip)

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by lightningterror** [comment]
Can you retest latest dev with Frame Buffer Conversion on?

**Comment by LeCharlatan** [comment]
> 
> 
> Can you retest latest dev with Frame Buffer Conversion on?

Hi @lightningterror 

I'll compile the latest source then retest it as soon as possible :D

**Comment by refractionpcsx2** [comment]
seems to be fine these days and we have upscaling fixes in the database to deal with the upscaling problems.

**Comment by refractionpcsx2** [comment]
Reopening as this is still an issue.
