### ISSUE TITLE
crash while switching to a badly detected ISO (sly cooper)

### ISSUE THREAD

**Issue by shentino** [PCSX2/pcsx2#2030]
[pcsx2-gdb-backtrace.txt](https://github.com/PCSX2/pcsx2/files/1179435/pcsx2-gdb-backtrace.txt)
***PCSX2 version:***
1.5.0-dev-2104-g49840bb62

***PCSX2 options:***
No speedhacks, I have most of the hacks disabled so I can run Okami

***Plugins used:***
All defaults

***Description of the issue:***
PCSX2 crashed and dumped core

***How to reproduce the issue:***
Play Okami, then use the CDVD menu to switch to the sly cooper ISO and reset

***Last known version to work:***
This ISO has never worked before with PCSX2, but I don't think it should be crashing

***PC specifications:***
i7 4790K.  Gentoo Linux, amd64 arch, kernel version 4.12.3

**Comment by gregory38** [comment]
You're title is misleading. Is the crash related to the switching of ISO or the game itself ?

**Comment by shentino** [comment]
I honestly don't know.

I know that switching to the sly cooper ISO is what triggered the crash, but I don't know if Sly Cooper is related to the crash or not.

**Comment by MrCK1** [comment]
Can you run it directly from the disk and see if the issue still occurs?

**Comment by shentino** [comment]
The disc unfortunately is damaged and unusable which is why I used the ISO file.

**Comment by shentino** [comment]
I am curious though what difference using the disc instead of the iso was supposedt o make

**Comment by gregory38** [comment]
Does it work if you shutdown first ? And then start a new ISO.

**Comment by shentino** [comment]
Starting fresh with the sly cooper 1 ISO doesn't crash, but it DOES give me this error message:

![screenshot from 2017-07-28 02-38-44](https://user-images.githubusercontent.com/50105/28711882-ea0104bc-733d-11e7-813a-d717d9b98b1d.png)

**Comment by shentino** [comment]
I can't reproduce the crash anymore.  I just reinstalled 9999 from gentoo so maybe a recent patch fixed the crash already.  Did my backtrace shed any light on a possible cause?

**Comment by atomic83GitHub** [comment]
CDVD ? You use a DVD emulation software ? If yes , use the internal iso reader in pcsx2.

**Comment by shentino** [comment]
Actually no I don't.  Sly Cooper 1 is the only ISO that triggers that dialog box.  Everything else reads straight from the ISO normally.

CDVD is just the item on the main PCSX2 menu.

**Comment by gregory38** [comment]
We need to understand what trigger the cdvd error. It is likely the root cause of the crash.

**Comment by shentino** [comment]
It's also very annoying not being able to play the game.

Would it help if I gave you a hash of the ISO file?

**Comment by shentino** [comment]
I would be willing to provide some sort of remote desktop/VNC access to a sandbox on my computer if that would help

**Comment by atomic83GitHub** [comment]
For me , I have the issue with some homebrew.

**Comment by shentino** [comment]
Homebrew ISOs?

**Comment by gregory38** [comment]
Link to the hombrew ? 

@shentino could you give us the output of `file sly1.iso`. Maybe the iso format is bad or wrongly detected.

**Comment by shentino** [comment]
...I just found out the file never downloaded properly.  An "empty" zero length file.  I'm a moron, let me get a fresh copy.

**Comment by shentino** [comment]
No more CDVD error, now it just gets stuck on the pre-title credits

**Comment by turtleli** [comment]
> ...I just found out the file never uncompressed properly from the 7z I downloaded.

Can't provide further help.

**Comment by shentino** [comment]
I'd have closed this myself anyway.  Since one of the updates I pulled upstream, the core dump crash seems to have resolved itself anyway.

**Comment by atomic83GitHub** [comment]
These are the Homebrew available on the play! (purei.org) emulator.
