### ISSUE TITLE
Ratchet and Clank 3 (SCES-52456, Original DVD) - Issue with bloom on high resolutions

### ISSUE THREAD

**Issue by Flandyn** [PCSX2/pcsx2#2034]
***PCSX2 version:***
``v1.5.0-dev-2156-g20cc02c90``

***PCSX2 options:***
``Safest preset, Aspect Ratio: Widescreen``

***Plugins used:***
![plugins](https://user-images.githubusercontent.com/15834268/29035056-a0518476-7b9a-11e7-8fdb-2e262284f708.PNG)

***GSDX settings:***
![gsdxsettings](https://user-images.githubusercontent.com/15834268/29034784-aef95162-7b99-11e7-9613-0011a658ad8e.PNG)

***Description of the issue:***
``When running the game in a higher resolution than native, the bloom in the game becomes out of place``

Screenshots+GS dumps:

![gsdx_20170807180917](https://user-images.githubusercontent.com/15834268/29035437-e507b6a2-7b9b-11e7-9282-1a6f6d1f410e.png)

GS dump:
[gsdx_20170807180917.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/1205405/gsdx_20170807180917.gs.xz.zip)

![gsdx_20170807181134](https://user-images.githubusercontent.com/15834268/29035514-2b78b2c6-7b9c-11e7-8756-7e79f3681c8a.png)

GS dump:
[gsdx_20170807181134.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/1205411/gsdx_20170807181134.gs.xz.zip)

![gsdx_20170807180421](https://user-images.githubusercontent.com/15834268/29035616-88564044-7b9c-11e7-9ffd-46baeee4a909.png)

GS dump: 
[gsdx_20170807180421.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/1205416/gsdx_20170807180421.gs.xz.zip)

***How to reproduce the issue:***
``Just run the game with any settings but use a resolution other than native``

***Last known version to work:***
``None, I tested this with older versions AND different settings before posting this``

***PC specifications:***
CPU: Intel Core i9-7900X
GPU: NVIDIA GeForce GTX 1080 (NVIDIA driver version 384.94)
OS: Microsoft Windows 10 Pro (Version	1607 Build 14393)
RAM: 32GB

**Comment by lightningterror** [comment]
Tried the wild arms hack or x , y offsets?

**Comment by atomic83GitHub** [comment]
Half pixel offset to special-texture solve the issue , the wild arms offset have many corruption in this game.

**Comment by Flandyn** [comment]
Thanks,  @atomic83GitHub , this solved my issue:
![solution](https://user-images.githubusercontent.com/15834268/29066574-e28ce5c0-7c2f-11e7-9747-b14d7ec30f67.PNG)
