### ISSUE TITLE
Screen solid white when enabling post-processing: Linux

### ISSUE THREAD

**Issue by hellbringer616** [PCSX2/pcsx2#2037]
**Build:** 1.5.0-Dev Compiled 06082017

**Plugins**
GSDX OGL

**GSDX Settings**
All Defaults except for:
Internal Resolution: 2x
Anisotropic Filtering: 16x
Blending Unit Accuracy: Medium
Mipmapping: Basic

Skipdraw: 1
Trilinier: Trilinier

External Shader checked and path set

***Description of the issue:***
Cannot enable the post processing shader without the screen turning solid white with nothing visible, disabling the shader allows perfect play.

Updating Mesa drivers didn't help. Older Radeon HD so updating the their driver is not an option.

***How to reproduce the issue:***
With an AMD card and using the mesa driver try to enable the shader

***Last known version to work:***
Windows works fine, can't comment on Linux

***PC specifications:***
CPU: Intel Core-i5 7600K
GPU: AMD HD7850 - Mesa driver
OS: Kubuntu 17.04
Mesa: v17.1.2

**Comment by gregory38** [comment]
Could you try to enable the "glsl debug" option. Maybe driver fails to compile the shader. Note it might create a debug file in your current directory. Did you tune the ini configuration or did you keep the default ?

**Comment by hellbringer616** [comment]
i can't find a "GLSL Debug" option, i did find a "GLSL Compilation" and i guessed that was it.

in the emulog with an unmodified ini file i find a line that strikes me as odd, stating 
"0:327(1): error: #extension directive is not allowed in the middle of a shader" 

I'm afraid i don't know where GSDS puts it's dump file on linux, it's not in the .config\pcsx2 directory. 

Could you tell me where else i could look?

**Comment by gregory38** [comment]
The error explains the rendering issue.

**Comment by hellbringer616** [comment]
Forgive my ignorance... But could you elaborate? 

What I get from this error is "your driver and the shader don't work together."

Am I on the right track?

**Comment by gregory38** [comment]
I will fix it.

**Comment by gregory38** [comment]
@hellbringer616 I pushed a fix for the compilation error. But I still have a bug on Nouveau which could be a Mesa bug. Could you test it on your side ?

**Comment by gregory38** [comment]
Note you need both new GSdx binary and new shader files.
