### ISSUE TITLE
Crashes on FreeBSD (GSdx: out-of-memory, texturing temporarily disabled)

### ISSUE THREAD

**Issue by Adrien2002** [PCSX2/pcsx2#2042]
PCSX2 1.5.0-20170814120319 - compiled on Aug 15 2017

ASUS ROG G750JW
Intel Quad Core i7 - 4700HQ. 2.4GHz
12G RAM
GTX 765m

FreeBSD/i386 11.1 (actual stable)
nvidia-driver-375.66

I'm trying to run Baldur's Gate Dark Alliance. I just set the GSdx to Software mode without to change anything else on PCSX2.

What the terminal says me, at the moment when it crashes is :

`GSdx: out-of-memory, texturing temporarily disabled`

Multiple times and I have a window opening and telling me this :

```
/home/Adrien2002/Téléchargements/pcsx2/common/src/Utilities/Linux/LnxHostSys.cpp(70) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t *, void *)
    Thread:    Unknown
    Condition: false
    Message:   Unhandled page fault @ 0x0001045f
```

I also have a lot of :

```
[...]
Gif Path[1] - MTGS Wait! [r=0x7ff2f0]
Gif Path[1] - MTGS Wait! [r=0x3c8e40]
Gif Path[1] - MTGS Wait! [r=0x7ffbc0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ffbe0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff7b0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff2a0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff270]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff140]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7fef40]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[3] - MTGS Wait! [r=0x7fe9c0]
Gif Path[3] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff730]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[3] - MTGS Wait! [r=0x7f86b0]
Gif Path[3] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff080]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff1f0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff240]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ffaa0]
Gif Path[1] - MTGS Wait! [r=0x4e6ee0]
Gif Path[1] - MTGS Wait! [r=0x7fee50]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff7c0]
Gif Path[1] - MTGS Wait! [r=0x403940]
Gif Path[1] - MTGS Wait! [r=0x7ffb60]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff2b0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ffae0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff810]
Gif Path[1] - MTGS Wait! [r=0x568fb0]
Gif Path[1] - MTGS Wait! [r=0x7ff8b0]
Gif Path[1] - MTGS Wait! [r=0x491430]
Gif Path[3] - MTGS Wait! [r=0x7f6ec0]
Gif Path[3] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff7e0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7fedd0]
Gif Path[1] - MTGS Wait! [r=0x0]
Gif Path[1] - MTGS Wait! [r=0x7ff660]
[...]
```

I saw on Internet that people were using a "4G patch" but it's for Windows only. I don't really know what this does but I can not use it. It is all I found on Internet about my problem.

**Comment by willkuer** [comment]
Tried using HW mode?

**Comment by Adrien2002** [comment]
Exactly the same in HW mode

**Comment by willkuer** [comment]
You can enable "Fast Texture Invalidation" to get a speed boost but probably it won't solve your problem. I am actually surprised that this is happening. I thought all BG games do work flawlessly nowadays.

**Comment by Adrien2002** [comment]
They do on GNU/Linux, yes.
UNIX BSD is different on some points :(

I tried but nothing changed, still crashing

**Comment by gregory38** [comment]
The 4GB depends on the kernel configuration (and 64 bits kernel only). It could be as low as 2GB.

Did you try to disable mipmapping ? Otherwise I would suggest to use the HW renderer with 8 bits texture and the fast texture invalidation hack.

**Comment by Adrien2002** [comment]
Ok I tried to set in HW mode, enabling 8 bits texture and enabling the hack. It seems to work now, it didn't crash where it usually crashes. Need to test longer to be sure.
Thank you for your suggestion gregory38.

About my memory... well...

$ dmesg | grep -i memory
real memory  = 12884901888 (12288 MB)
avail memory = 2024976384 (**1931 MB**)

I only have 2 GB usable by FreeBSD.

**Comment by Adrien2002** [comment]
In BG, I spoke with everyone in the tavern and when I tried to go down to the first dungeon, the game closed by itself (not the emulator) and the terminal says this in red :

```
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
(EE pc:0013D430) TLB Miss, addr=0x24 [load]
Too many execution errors.  VM execution has been suspended!
```

Is it still linked to the memory ?

**Comment by willkuer** [comment]
Rather sounds like a broken iso or a wrongly applied patch/cheat. Try to disable widescreen hacks or cheats if they are enabled and redump your iso.

**Comment by Adrien2002** [comment]
Eh... I dont have my PS2 games with me where I live now. I downloaded it from Internet and the MD5 and SHA1 are both corresponding to the website. I'm also not using any cheat/hack except for the "fast texture invalidation" graphical hack.

**Comment by lightningterror** [comment]
> I downloaded it from Internet and the MD5 and SHA1 are both corresponding to the website. 

We don't offer support for piracy sorry.

**Comment by Adrien2002** [comment]
Ok you are right, I'm sorry, it is even illegal to fetch a copy over Internet so let me get back my real copy (I can show you with a picture so then maybe we can re-open this thread or make a new one).
Sorry for that.

**Comment by Adrien2002** [comment]
I ripped my own Baldur's Game Dark Alliance now (+ proof I really have it http://i.imgur.com/eicyp3A.jpg and http://i.imgur.com/Ri3LEzo.jpg )
I simply `dd if=/dev/cd0 of=/root/BGDA.iso` from my NetBSD then I `rsync -c` it to my FreeBSD to play it. Can we re-open this thread please ?

Now, it still crashes but the message is slightly different.

```
(EE pc:0014A290) TLB Miss, addr=0x24020060 [load]
/home/Adrien2002/Téléchargements/pcsx2/pcsx2/vtlb.cpp(485) : assertion failed:
    Function:  mem32_t vtlbDefaultPhyRead32(u32)
    Thread:    EE Core
    Condition: false
    Message:   (VTLB) Attempted read32 from unmapped physical address @ 0x18BB0838.
/home/Adrien2002/Téléchargements/pcsx2/pcsx2/vtlb.cpp(485) : assertion failed:
    Function:  mem32_t vtlbDefaultPhyRead32(u32)
    Thread:    EE Core
    Condition: false
    Message:   (VTLB) Attempted read32 from unmapped physical address @ 0x18BB0838.
```

I succeed to walk in the dungeon but it crashes randomly after a while.

**Comment by Adrien2002** [comment]
I use absolutely NO hack at all, I am using the most default PCSX2 settings possible except for the graphical settings you guys suggested me to set. No cheat, no widescreen hack, nothing at all.

**Comment by gregory38** [comment]
I'm a bit loss. What is your OS, freebsd or netbsd ?

**Comment by willkuer** [comment]
Please upload the full emulog after you observed the issue to a txt share hoster as pastebin.

**Comment by Adrien2002** [comment]
`I'm a bit loss. What is your OS, freebsd or netbsd ?`

I have two computers, one on FreeBSD and the other on NetBSD. This thread is dedicated to FreeBSD's version of PCSX2 (I opened another thread about PCSX2 running on NetBSD but it has nothing to see with this one)

I was playing, no problem when suddently the game window closed by itself, after around 10 minutes, without crash window. Full log here : https://pastebin.com/ecBBCGkm (it seems to crash on different errors, now I had the error where people ask you to redumb the iso but I seriously doubt it will fix the issue).

**Comment by gregory38** [comment]
Could you check your kernel option ? Hopefully there is an option to have 3GB of virtual memory for 32 bits process. It would be nice if we could rule out this memory limit as potential bug.

**Comment by Adrien2002** [comment]
I have 4GB of swap too but maybe PCSX2 doesn't care about swap. I'm going to build my kernel with PAE which is seemingly the solution to the 2GB problem with FreeBSD/i386.

**Comment by gregory38** [comment]
Swap extend your physical memory whereas the limit is virtual memory. 3 GB is doable without pae, but pae will work too. By the way, what is your BG version exactly ?

**Comment by Adrien2002** [comment]
My BG version ? How can you know the version of a PS2 game ? SLES 50672 ? French version ? I don't know :(

I quickly tried FreeBSD/amd64 after having really bad troubles with PAE on FreeBSD/i386 (seems to be dead and not working anymore).

So I chrooted into i386 to build, no problem.
When I run it (from the chroot with X11 forwarding for the moment until I set it correctly), it says I have 12 GB ram which is much better. I wonder now if it acts the same way as FreeBSD/i386 using only 2 GB for 32 bits binaries or if it can use a little bit more like 3 GB for instance (this, I really don't know). Of course, I applied the three graphical options about disabling mipmap, enabling 8 bit texture and enabling that fast texture invalidation hack.

So I played a while, I made the entire first dungeon but when walking back to the stairs to return to the tavern, the game crashed and the terminal output was this :

```
(EE pc:0014A290) TLB Miss, addr=0x12bcb61b [load]
(EE pc:0014A290) TLB Miss, addr=0x8 [load]
/root/pcsx2/pcsx2/vtlb.cpp(485) : assertion failed:
    Function:  mem32_t vtlbDefaultPhyRead32(u32)
    Thread:    EE Core
    Condition: false
    Message:   (VTLB) Attempted read32 from unmapped physical address @ 0x1A95863B.

/root/pcsx2/pcsx2/vtlb.cpp(485) : assertion failed:
    Function:  mem32_t vtlbDefaultPhyRead32(u32)
    Thread:    EE Core
    Condition: false
    Message:   (VTLB) Attempted read32 from unmapped physical address @ 0x1A95863B.
```

I have a Windows 10 installed on a SSD/USB, I can connect it and boot a Windows 10. I did to try PCSX2 with that dumped ISO I made myself to see if the ISO is the problem but no problem at all, I played for three hours without to ever have any issue. My ISO is correct.

**Comment by Adrien2002** [comment]
I have a little more informations.

I just discovered that Core i7 only provide 2 GB of memory to 32 bits applications. It has nothing to see with FreeBSD. I tried on Debian GNU/Linux and it's exactly the same.

Also, I checked the memory on FreeBSD while playing Baldur's Gate and it doesn't even reach 1 GB when it crashes on amd64
When I play Skyrim with Wine, I even go up to 1750 MB of memory without to ever crash so it's not a memory problem because :

1. On Windows, I also have 2 GB of memory and it's **NOT** crashing
2. Wine can use more memory without crashing

I copied my Windows "memory card" to my FreeBSD to continue my game (I'm at the end). I'm in a big place in the marsh and, in FreeBSD, it crashes only a few seconds after I arrived in the game. Still the same messages :

```
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
(EE pc:00140420) TLB Miss, addr=0x2000000 [load]
Too many execution errors.  VM execution has been suspended!
```

My hardware is not the cause of the crashes, neither does my ISO. It is PCSX2.
Now, if you want me to try anything, maybe build with debug or with any option, just tell me

By the way, the original thread is no more, I don't reach the capacity of the memory since I'm not in i386 anymore and don't have the `GSdx: out-of-memory, texturing temporarily disabled` message anymore, everything is fine about this problem now. Maybe it would be better to create a new thread about this issue ?

**Comment by gregory38** [comment]
So windows is fine but both Linux/Freebsd are crashing ? It is strange most of the code is common. Do you use the same iso on all OS ?

**Comment by Adrien2002** [comment]
No no, I didn't try GNU/Linux version of PCSX2, I just booted Debian 32 bits installer to CHECK the memory available of i386 version of Debian on my CPU. I only tried Windows 10 and FreeBSD 11.1

The ISO is the same between Windows and FreeBSD, I didn't dump my BGDA twice.

**Comment by gregory38** [comment]
Plugin are the same ? Ini configuration ?

**Comment by MrCK1** [comment]
@Adrien2002 Is this still an issue for you?

**Comment by lightningterror** [comment]
Closing, no response from OP.
