### ISSUE TITLE
NetBSD → Thread creation error: SysExecutor thread never posted startup semaphore.

### ISSUE THREAD

**Issue by Adrien2002** [PCSX2/pcsx2#2045]
NetBSD/amd64 → chroot userland i386 for compilation, back in amd64 to run.

Core i5 2500K
Intel HD Graphics 3000
4 GB ram

Thanks to you guys, my PCSX2 package for pkgsrc is almost done. It builds perfectly but when I try to run it, I have a red message saying :

`Thread creation error: SysExecutor thread never posted startup semaphore.`

semaphore is slightly different between GNU/Linux and NetBSD

> The problem if Firefox's CrossProcessSemaphore.  On Linux, sem_t is a opaque 
>  structure.  On NetBSD, it is opaque pointer.  The sem_t is shared between two 
>  processes.  This, of course, does not work on NetBSD.

http://netbsd.2816.n7.nabble.com/Re-pkg-51966-td364310.html

Since I'm not expert at all... I have no idea what to do to fix this

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by Mrlinkwii** [comment]
is this still an issue ? :slightly_smiling_face:

**Comment by lightningterror** [comment]
No further info provided.
