### ISSUE TITLE
Metal Gear Solid 3: Subsistence /  Save corruption in a specific spot

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2046]
***PCSX2 version:***
v1.5.0-dev-2175-g420f11161

***PCSX2 options:***
Various, the bug happens with default settings too.

***Plugins used:***
GSdx OGL, DEV9null, USBnull, rest default

***Description of the issue:***
Saving in the prison cell to gain access to the Guy Savage easter egg will create an unloadable save preventing access to the easter egg, saving anywhere else seems unaffected but I have not tested it.
Haven't tried loading an external save made using an actual console yet.

***How to reproduce the issue:***
1. Get to the Prison cell sequence
2. Create a regular save.
3. Load that save

***Last known version to work:***
Unsure, I've seen several posts on the forum claiming they had other issues with that easter egg meaning they managed to access it at the very least which means that bug wasn't always always present or that here is a workaround I'm not aware of.

***PC specifications:***
Intel i7 4770K
Nvidia GTX 1070 (385.28)
Windows 7.

**Comment by Ryudo300** [comment]
I saved and loaded just fine in this section. Multiple times actually.

It could just be coincidence that you ran into the notorious corruption problem. Because MGS3 is pretty prone to corrupting the save files.

**Comment by atomic83GitHub** [comment]
On a backward compatible ps3, the issue can happen rarely, but in pcsx2, it seems fine.

**Comment by Helium-4** [comment]
At the time it didn't seem like a coincidence because I managed to trigger a corrupted save several times in a row doing the same thing with various settings (one with both WS hack and speedhacks on, one with just speedhacks on, one with neither on and one with absolutely everything back to default and SW renderer) but obviously it is a coincidence since doing the exact same thing now works.

**Comment by Ryudo300** [comment]
Yeah there's really not much to do about it. It's basically a game flaw. I've had several corruption issues going on while playing, all in different areas. One thing you may try is using the Folder Memory Card system, I noticed the corruption occurring a lot less for some reason when using this instead of the memory card files. But again, this could just be a coincidence as well.
