### ISSUE TITLE
Burnout 3 - Garage Textures Flickering

### ISSUE THREAD

**Issue by UlsterRose** [PCSX2/pcsx2#2047]
***PCSX2 version:***
1.5.0-2156

***PCSX2 options:***
All defaults.

***Plugins used:***
GSDX OpenGL Software (AVX2)

All default options otherwise.

***Description of the issue:***
If you look at the vents and pipes, you'll see they flicker a white/grey colour.

***How to reproduce the issue:***
1. Start the game, save profile etc.
2. Go to time attack, and select a course/track
3. You'll be in the garage, look at the vents and pipes near the top of the screen.

***Last known version to work:***
Issue has always been present.

***PC specifications:***
CPU: i5-6400
GPU: Intel HD 530 Graphics (I've gotten this same issue using a 7970.)
RAM: 8GB
OS: Windows 10 x64

PCSX2:
![gsdx_20170814154423](https://user-images.githubusercontent.com/8225831/29501803-2c918e6c-8623-11e7-95f3-57f9a0161eb5.png)

Console (Xbox, the garage is the same on both platforms):
![image4](https://user-images.githubusercontent.com/8225831/29501868-9fb38ac6-8623-11e7-9d18-7b27982bda79.png)

GS Dump: [b3.zip](https://github.com/PCSX2/pcsx2/files/1237635/b3.zip)

**Comment by MrCK1** [comment]
You need to remove the template instructions and fill in the missing GSdx information.

**Comment by gregory38** [comment]
Did you test the sw renderer of the SSE2 plugin ? Could you check that bilinear filtering is set on ps2 mode.

**Comment by UlsterRose** [comment]
I tried both settings, but they didn't have any effect on the issue.

**Comment by atomic83GitHub** [comment]
Clamping or round mode do anything?

**Comment by UlsterRose** [comment]
Looks like setting Clamping Mode to None fixes the issue.

**Comment by atomic83GitHub** [comment]
What clanping mode, VUs or EE/IOP ?

**Comment by UlsterRose** [comment]
Sorry, wasn't thinking about that :p

VU clamping mode.
