### ISSUE TITLE
Folder memcards don't work with Freedom Fighters (SLUS-20658)

### ISSUE THREAD

**Issue by Pistachioman** [PCSX2/pcsx2#2048]
***PCSX2 version:***
v1.5.0-dev-2175-g420f11161

***PCSX2 options:***
Safest preset

***Plugins used:***
All default

***Description of the issue:***
When using folder memcards, playing Freedom Fighters and saving works fine. But when rebooting the game and trying to load, the game says the save is corrupted.
Don't know if this is related, but there are a bunch of \_pcsx2\_deleted\_ files in the save folder after closing the emulator.
Everything works when not using folder memcards.

***How to reproduce the issue:***
Start a new game and save using quicksave. Then reboot the game and try to load.

***Last known version to work:***
Never worked, as far as I know.

**Comment by lightningterror** [comment]
What if you uncheck "Automatically manage saves based on running game" ?

**Comment by Pistachioman** [comment]
Still the same.
I have attached a zip with a folder- and a file memcard, both saved at the same location, started from the beginning. Loading from the folder doesn't work, from the file it does. Maybe that helps.
[freedomfighters.zip](https://github.com/PCSX2/pcsx2/files/1241083/freedomfighters.zip)

**Comment by willkuer** [comment]
@AdmiralCurtis Maybe you can have a look?

**Comment by willkuer** [comment]
@AdmiralCurtiss Maybe you can have a look?

**Comment by willkuer** [comment]
Btw you can rename the files by removing the pcsx2_deleted prefix. It might work again to load them.

**Comment by AdmiralCurtiss** [comment]
Oh boy, I haven't looked at this code in forever, but yeah I can take a look when I find the time.

**Comment by willkuer** [comment]
♥

**Comment by lightningterror** [comment]
Might also want to add that it doesn't work with Block Dumps as well.

**Comment by AdmiralCurtiss** [comment]
I looked into this, but so far I can only confirm that it happens, but haven't yet figured out why.

**Comment by Mrlinkwii** [comment]
this should be fixed on master :)
