### ISSUE TITLE
Joystick movement is disabled after load state

### ISSUE THREAD

**Issue by ProfessorKaos64** [PCSX2/pcsx2#205]
Steps to reproduce

1. start game with PCSX2 (Playstation 2)
2. save state
3. move a little and load state, joystick still works
4. exit game
5. start game and load state
6 joystick does not work

Using:

* Ubuntu 14.04 LTS
* Kernel: 3.14.0-031400-generic
* PCSX2 Version:  1.3.0.0 (svn)
* Controller: PS3 Sixaxis (bluetooth)

**Comment by gregory38** [comment]
Could you test the PR #1476

**Comment by ProfessorKaos64** [comment]
2 years in the making :) sure can. I'll do a new build today and test tonight.

**Comment by ProfessorKaos64** [comment]
Can I clone the onepad-input-state branch for this test, or do you prefer I cherry pick the PR?

**Comment by gregory38** [comment]
Tbh, I was thinking the same but I'm a too busy man.

```
Can I clone the onepad-input-state branch for this test, or do you prefer I cherry pick the PR?
```
Do as you wish. If you have the PCSX2 repository, you can just do
```
git fetch
git checkout onepad-input-state
```
Use `git stash` if you have pending change (unlikely but you know)

**Comment by ProfessorKaos64** [comment]
> Tbh, I was thinking the same but I'm a too busy man.

Just a small joke meant no harm, I know how hard folks work on projects. I'll report back tomorrow if I can get this tested tonight. The Vulkan API port of Quake package I made needs some testing too :)

**Comment by gregory38** [comment]
Ok no worry. I'm not in hurry. Just don't take 2 years to give your feedback :stuck_out_tongue:

**Comment by ProfessorKaos64** [comment]
Sorry I didn't get to this fast enough. I was distracted with other issues. I see you committed the fix anyway. I'll retest soon, but i'll assume you are confident with the fix.
