### ISSUE TITLE
GSDX DX11: black screen with vsync set to adaptive 

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2050]
***PCSX2 version:***
Last dev version.

***PCSX2 options:***
Vsync to adaptive and GSDX to DX11 (software or hardware)

***Plugins used:***
All default

***Description of the issue:***
GSDX show a black screen under DX11 if vsync is set to adaptive.

***How to reproduce the issue:***
Set GSDX to DX11 mode and vsync to adaptive.

***Last known version to work:***
Don't exist: the introduction of vsync adaptive introduced the issue

***PC specifications:***
Intel Core 2 Duo E8600 Gigabyte GTX 780Ti  Windows 10 64 Bit

**Comment by lightningterror** [comment]
Same issue on my r7 360.

**Comment by ssakash** [comment]
I think it's due to passing a negative value in D3D11 swapchain present function (https://msdn.microsoft.com/en-us/library/windows/desktop/bb174576(v=vs.85).aspx), not sure though as I haven't tested it yet.

**Comment by turtleli** [comment]
You guessed correct.
