### ISSUE TITLE
OnePad, XBO controller: "1.3.0" doesn't see right analog properly, "2.0.0" doesn't let me map buttons

### ISSUE THREAD

**Issue by kamild1996** [PCSX2/pcsx2#2052]
***PCSX2 version:***
``1.5 git201708161205``

***PCSX2 options:***
Nothing relevant changed

***Plugins used:***
OnePAD 0 1.3.0 and OnePad 0 2.0.0

***Description of the issue:***
Neither version of the OnePad plugin allows me to use my wired Xbox One controller properly under Linux. Version 1.3.0 sees all buttons and lets me map them, but right analog works only in y-axis, regardless of which direction I decide to move the stick on. Version 2.0.0, according to "Gamepad Configuration", can see my controller, but it won't let me map any buttons - it just doesn't react to controller input.
The controller had axes set improperly, and other apps would also fail to use right analog properly. However, I was able to fix that by using the jstest-gtk app and changing the axis order (second and third - ABS_RX and ABS_RY; fourth and fifth - ABS_Z and ABS_RZ). Now the system sees it properly, but OnePad doesn't, even after restarting PCSX2 and replugging the controller back in.

***How to reproduce the issue:***
Pretty self-explanatory, but:
1. Try OnePad version 1.3.0 and go through the "Set All Buttons" setup. Everything will map fine, except right analog.
2. Now switch to OnePad version 2.0.0 and try to map any button. Despite the controller being present in the controller list in "Gamepad Configuration" settings, you won't be able to map anything

***Last known version to work:***
none

***PC specifications:***
Xubuntu 17.04 running on kernel 4.13, wired Xbox One controller

**Comment by gregory38** [comment]
Yes, it is a know issue on 1.3. There are some options (checkbox) that might help to make it work. Unfortunately I don't remember which one.

Onepad 2.0 is plug and play. You can't map the button but if the pad is detected, it will just work. If detection is wrong it should print you an error message in the PCSX2's console.

**Comment by kamild1996** [comment]
Ahh, my fault, sorry :) Some sort of window popped up when I switched to OnePad 2.0 for the first time and I accidentally clicked through it, I bet that's what it tried to tell me...

**Comment by thePalindrome** [comment]
I'd suggest disabling the buttons and leaving a message if auto detection is on

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by lightningterror** [comment]
Closing in favour of #4016
