### ISSUE TITLE
Uncouple v-sync and frame limiter

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#2053]
If #2049 is not the right place for discussing..

**Comment by willkuer** [comment]
The main idea is if you have a >60Hz screen and you play with 60FPS speed you still would like to have vsync, or?

Does PAL (50Hz) or Slowmo (30/25FPS) also play an important role?

What is the desired behaviour on a 120Hz screen with turbo (120/100FPS) enabled? Does it change when going to a 144Hz screen?

**Comment by mirh** [comment]
My hats off for the table. 
But my proposal was just: nothing by default. 

There are so many situations that I cannot think a single one case where I'd exclude something. 

---
Then, I can see some people would like to fast forward their games because whatever. Ok, totally legit. 
But this is no reason for hard-coding. 
The quickest simplest thing that comes to my mind for such necessity (especially since it seems to be all about convenience) is instructing people to set the same hotkey for both FL and v-sync toggling. 
The questions so are: 
* can multiple actions be triggered by the same keyboard button?
* do we have a v-sync toggle?

**Comment by gregory38** [comment]
When you enable Vsync you can control the number of interrupt to wait. So you can display a frame every 2 interrupt on a 120Hz display (i.e. 60 fps).

If people can't manage 120 fps, it will get back to 60 fps (if vsync is enabled).

**Comment by mirh** [comment]
Guess like we could even implement some custom resolution hooking too one day, similar to what [madVR](http://madvr.com/crt/CustomResTutorial.html) does. Nice point. 

That's not the point of this issue though.

**Comment by lightningterror** [comment]
On Qt vsync is disabled if frame limiter is disabled.
