### ISSUE TITLE
Splinter Cell : Audio issue (spu2x)

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2056]
***PCSX2 version:***
Last build version

***PCSX2 options:***
All default, speedhacks disabled

***Plugins used:***
All default, all core audio tested

***Description of the issue:***
This game have a sound issue related to the spu2x plugin, A kind of cracking is heard when any sort of sound is play.
There is no sound in FMV.

***How to reproduce the issue:***
Load PCSX2 with the spu2x plugin and load the Splinter Cell game.

***Last known version to work:***
Don't exist, this issue is also on the 1.4 version

***PC specifications:***
Intel Core 2 Duo E8600 Gigabyte GTX 780Ti Windows 10 64 Bit

**Comment by MrCK1** [comment]
Can you post your SPU2-X settings here and try adjusting latency as well?

**Comment by atomic83GitHub** [comment]
Here it is:
![capture](https://user-images.githubusercontent.com/26351275/31018614-104801fe-a52d-11e7-8baf-917250a7f12d.PNG)
Adjusting latency don't do anything (I had try multiple value)

**Comment by MrCK1** [comment]
What if you use ASync or no synchronization instead of TimeStretch?

**Comment by atomic83GitHub** [comment]
Same issue with ASync or no synchronization

**Comment by MrCK1** [comment]
Can you try older stable builds and see if the issue still exists?

**Comment by atomic83GitHub** [comment]
Tested on 1.4.0, still the same issue.

**Comment by MrCK1** [comment]
@atomic83GitHub I need you to go further back in time. Don't be afraid to test all the stable builds incase the issue disappears. You never know how old a regression can be. 😛

**Comment by atomic83GitHub** [comment]
I had test 0.98 and 0.92, still the issue, I will check more older.

**Comment by atomic83GitHub** [comment]
I had test the 0.8 build, no sound at all.

**Comment by MrCK1** [comment]
OK, thanks for trying anyways. If it was a regression, it would have been easier to track. Oh well.

**Comment by atomic83GitHub** [comment]
And, there is no sound in fmv.

**Comment by atomic83GitHub** [comment]
Blockdump can be usefull on this?

**Comment by FlatOutPS2** [comment]
The game seems to constantly switch between left and right speakers when playing audio.

@atomic83GitHub Is there a mono option in the game?

**Comment by atomic83GitHub** [comment]
@FlatOutPS2, sorry for the late reply, the game don't have any sound option and is stuck at stereo.

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest master?

**Comment by AndreyRGW** [comment]
> Is this still an issue on latest master?

yup

**Comment by refractionpcsx2** [comment]
OK Thanks for letting us know
