### ISSUE TITLE
'High fidelity' v-sync mode

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#2059]
*As tangentially suggested by [gregory](https://github.com/PCSX2/pcsx2/issues/2053#issuecomment-325966462).*
The idea went through a lot of mind work so I'll also describe this. 

At first I was going to just propose a "High Fidelity" mode (aka pcsx2 sets monitor refresh rate to match games one) unconditional to everything else, toggled by an additional checkbox. 

Assuming nobody would want to go down the scary rabbit hole of "[vendors](http://gpuopen.com/gaming-product/amd-gpu-services-ags-library/) [private](https://www.intel.com/content/www/us/en/support/graphics-drivers/000007175.html) [tools](https://developer.nvidia.com/nvapi)*" I realized only a "selection between already available modes" would have been possible with normal Windows functions. 
Which means you'd have to warn users for when "their expectation cannot be met" *and* instruct them for [how to](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) [work around](https://forum.doom9.org/showthread.php?t=173571). 

So this got me thinking about who really is the kind of individual that (putting aside bugs in drivers, please) would find all this tinkering (and the possible nuisance of monitor 'loosing connection' to adjust to newer settings) worth it. 
Because I mean, perhaps it's my lazy eye, but even with PAL games under 60Hz DWM.. I don't really feel stutter. 

On the other hand, this would probably be a big deal breaker if I were to use v-sync (let's put aside the compositing variable for simplicity). It'd be bonkers to sync frame rendering to the wrong clock. 

Which ultimately lead us to my tl;dr:
* v-sync menu gets labeled refresh rate control
* disabled/adaptive stays basically like now
* standard gets named #something# and not only enforce v-sync but also try to instate the right refresh rate

Notes about the later mode:
* query available resolutions before set attempt, and warn+fallback if there's is none multiple of the desired one
* at least on linux possibly we could try ourselves to fix the problem for the user (ask him?)? [th](https://dri.freedesktop.org/docs/drm/gpu/i915.html#display-refresh-rate-switching-drrs)[is](https://lists.freedesktop.org/archives/intel-gfx/2013-November/036648.html)?
* as I were saying somewhere else, test whether we can **always** safely assume late vsync > normal 
(very important for the 'perfection' of the still 3 choices menu)
* maybe delay of some seconds this function on games boot, to allow them to set the right whatevers once?
* on game closure original resolution should restored 

Wonder: should we perhaps even care about interlaced display modes?

*(their abilities *might* come useful one day for 3D, VRR monitors, access to special API extensions or better gpu querying, though)
trivia: g-sync can be used [even](https://pcgamingwiki.com/wiki/Glossary_talk:Vertical_sync_(Vsync)#VRR_requirements_3216) for bordered windows, but there are strict requirements to respect

**Comment by ramapcsx2** [comment]
What is the scope of this "high fidelity v-sync"?
Out of the countless variables that determine "smoothness", we can only work on a few.
We can't, for example, fix game loops taking more or less time, depending on workload.
We will have trouble generating a synchronized output framerate for any monitor timing, no matter what that timing is (see issues with the internal frame limiter).

So if we consider regular TFT displays @ 60Hz, what are you suggesting we do for them?
Or is this more about the new variable rate techs?

**Comment by mirh** [comment]
> So if we consider regular TFT displays @ 60Hz, what are you suggesting we do for them?

None of my considerations are refresh rate specific. 

> If it's just about using a PS2 compatible vertical refresh, then that would be 59.94Hz NTSC and 50.00Hz PAL.

Yes, it is. 
With the added thingy that it's not always going to be that simple, and that even 2x and 3x refresh rates should be accepted.

**Comment by lightningterror** [comment]
Closing, low priority/trivial.
