### ISSUE TITLE
GSdx-hw: Bleach blade blattlers 2 ghostling issue

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2066]
***PCSX2 version:***
1.5.0-dev-2155-g41bfb6e80

***Description of the issue:***
Characters got a HUGE ghostling effect while moving. This can´t be solved with any hack like the Half pixel offset. While in Directx 11 all works like a charm.

All the other settings or hack in the GSDX doesn´t matter for this (Tested changing all settings, crc hack level, IR, etc etc) Only can be solved by changing to Directx 11.

***How to reproduce the issue:***
Start a game (For example a vs battle) 

***PC specifications:***
i7 4790k
16GB DDR3
GTX970
Windows 10 x64

**Comment by lightningterror** [comment]
Does the issue appear on native res?
Did you also try the Wild Arms offset hack ?
What if you set crc to full ?

**Comment by LuismaSP89** [comment]
Yes, i tested with all those settings and more. The only way at the moment is to run with the Directx 11 Backend.

**Comment by gregory38** [comment]
Did you try to disable the depth effect emulation in hardware hack ?

**Comment by LuismaSP89** [comment]
Wow, sorry about that, yes, disabling depth effect works well :P

**Comment by gregory38** [comment]
Screenshot ? By any change, is the bad effect limited to a part of the screen (such as the half-bottom for example)

**Comment by LuismaSP89** [comment]
![disabled depth emulation2](https://user-images.githubusercontent.com/12205048/31342579-7f4de82e-ad0d-11e7-825e-06cce0599ef9.jpg)
![ghosting1](https://user-images.githubusercontent.com/12205048/31342580-7f578d02-ad0d-11e7-9584-4b7161bbc10d.jpg)
![ghosting2](https://user-images.githubusercontent.com/12205048/31342582-7f75f116-ad0d-11e7-8416-4ef7202875f3.jpg)
![disabled depth emulation1](https://user-images.githubusercontent.com/12205048/31342581-7f588f40-ad0d-11e7-9d89-1268b0be7c27.jpg)

Here it is, some screenshots. Btw, disabling depth emulation solves the problem, but the game looks a little fuzzy.

**Comment by gregory38** [comment]
Hum, it feels like that it take a wrong buffer and apply a wrong effects. What happen in native resolution.

**Comment by LuismaSP89** [comment]
The same, in native resolution the ghosting is present too.

**Comment by lightningterror** [comment]
Can you upload a gs dump of the issue ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by lightningterror** [comment]
Preload frame data hw hack solves the issue.
