### ISSUE TITLE
for when a new tag  of v1.5.0 ?

### ISSUE THREAD

**Issue by sergiomb2** [PCSX2/pcsx2#2069]
https://github.com/PCSX2/pcsx2/compare/v1.5.0-dev...master indicates 2203 commits after latest tag. Do you think master is stable enough to publish as package ? , do you plan have for beta versions ? , and when start it do beta you plan a stable release after how much time ? etc 
 
Thanks.

**Comment by willkuer** [comment]
https://github.com/PCSX2/pcsx2/milestone/2

They never publish beforehand when a new release appears. They appear when they are happy. The next stable release probably   is published soon (i.e. within a few months).

The question is just why waiting for a stable release if you can use basically stable up2datw dev/beta versions?

**Comment by sergiomb2** [comment]
ok I will wait , should I close this issue , or wait for news ?

**Comment by MrCK1** [comment]
@sergiomb2 You can close the issue.

**Comment by DRSDavidSoft** [comment]
@sergiomb2 Sorry to post it here, but Orphis has been building nightly PCSX2 Win32 binaries for some time:
https://buildbot.orphis.net/pcsx2/
