### ISSUE TITLE
Feature Request: Clear ISO list cache

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2071]
Would be nice to have a neat feature like this since not many people wanna bother clearing the iso cache or they don't know how to do it.

![iso clear](https://user-images.githubusercontent.com/18107717/30358002-0a8d0d88-9842-11e7-9faf-9e9ffb327218.jpg)

Something like this for example. @ssakash  what do you think ?

**Comment by ssakash** [comment]
Seems like a good idea to me, most of the users are reliant on the INI files for manually removing the ISO entries which is a PITA. This should make removing the entries more user friendly.
