### ISSUE TITLE
Iridium Runners: Stalling in-game, cannot progress

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2072]
***PCSX2 version:***
v1.5.0-dev-2194-gada0d5745

***Settings used:***
Defaults, EE Timing Hack, GIF FIFO gamefix (required workarounds for menu hanging)

***Plugins used:***
Defaults, GSdx HW

***Description of the issue:***
After starting the first race, the game will stall around the same section of track regardless of emulator settings. This is as far as the user can progress in-game currently.

***How to reproduce the issue:***
Select character and begin first race. Start running forward and then game will stall without crashing.

***Last known version to work:***
Never, the game always stalls at the same address/instruction as shown below

***PC specifications:***
Intel Core i5-6600k @4.7GHz, GTX 1070, Windnows 10 Home 64-bit

Debugger address/instruction:
```002213C8       lw	v0,(v1)```

Game hangs on this instruction and continually repeats in log:
```eReg(002213c8 dd6bee32): HwRead32     @ 0x10009000/VIF1_CHCR        -> 0x50000155```

Full Debug Log: https://pastebin.com/6C2s55W5

![gsdx_20170906210426](https://user-images.githubusercontent.com/16314399/30402119-ad4fcd04-98aa-11e7-8569-16668157ad35.png)

**Comment by MrCK1** [comment]
Would somebody be kind enough to add some labels to this issue? I suspect ```Bug``` ```Core``` ```VIF``` and/or ```Vector Units``` would suffice here.

**Comment by ssakash** [comment]
> Also, anything I should add here to make this issue more useful?

A block dump of the issue might be useful I guess.

**Comment by MrCK1** [comment]
Here's a block dump for this game. Hope it helps:


[IriridumRunners_blockdump.zip](https://github.com/PCSX2/pcsx2/files/1341997/IriridumRunners_blockdump.zip)

**Comment by atomic83GitHub** [comment]
Interpreter don't do anything?

**Comment by MrCK1** [comment]
No, the game will always stall regardless.

**Comment by FlatOutPS2** [comment]
@MrCK1 The blockdump you posted does not work.

**Comment by MrCK1** [comment]
@FlatOutPS2 I'll get another one when I get back in a few days.

Btw, I went into a bit more detail about what functions/where the game will stall on here: https://forums.pcsx2.net/Thread-Fixing-unplayable-games?page=30

**Comment by FlatOutPS2** [comment]
@MrCK1 Don't bother until @turtleli fixes #2266 Making blockdumps of bin files doesn't work.

**Comment by MrCK1** [comment]
I can always rip the disk and get another blockdump. I've just been too lazy to. :P

**Comment by FlatOutPS2** [comment]
You have to use the old linuz ISO CDVD plugin that comes with PCSX2 versions from before 1.4.0 to make a working one.

**Comment by MrCK1** [comment]
Game is fixed with a patch, so I'll close this.
