### ISSUE TITLE
Feature Request: GUI: Load/Save state menu should show date of the save

### ISSUE THREAD

**Issue by cmdrkotori** [PCSX2/pcsx2#2073]
***PCSX2 version:***
Development build v1.5.0-dev-2203-gfe2dfdb3b

***PCSX2 options:***
Not Applicable

***Plugins used:***
Not Applicable

***Description of the issue:***
Save/Load State menu does not show which save is the most recent. Users forget which state to use after dropping a game for a period of time.

***How to reproduce the issue:***
1. Boot game
2. Open pcsx2's Load State menu
3. Look for the most recent save slot

***Last known version to work:***
Never

***PC specifications:***
CPU: AMD FX8320; GPU: AMD 270X; OS: Arch Linux

**Comment by MrCK1** [comment]
This would require a bit of work I think. 

Ignoring the GUI portion, the .p2s format would need to be modified to save a timestamp of the user's PC. However, this wouldn't account for timezone changes, ect. if somebody else used the savestate.

Generally speaking, the oldest save is stored in Slot 1 and the newest in the next highest slot, ect.

**Comment by vsub** [comment]
Not that I know how to do it in pcsx2,but at least in my Multi Converter(that have save state preview feature)it also shows the date and I get the date by reading the file modified date.

PCSX2 modifies the iso list during runtime so I don't think it will be that hard to place the date in the list of save states

**Comment by MrCK1** [comment]
I have some ideas that I may start working on soon. Also, a version bump will probably be required as I'll most likely change formst of the saved string. It technically won't break anything - so maybe we can fudge that so we don't have to break savestates again. ;)

**Comment by ssakash** [comment]
@MrCK1 

This label is used for pull requests that require the savestate version to be incremented, not for issues which _might_ potentially require a savestate version bump. The idea is to keep track of all the changes which caused the savestate version to be incremented.

FWIW I don't even think we need to increment the savestate version for this change.

**Comment by lightningterror** [comment]
All of the information can be saved in ini files, you don't even need to add dates, just marking the savestates from newest to oldest should be enough.

You could also make it so that the emu saves the information which slot was selected before closing the emulator and when you resume that same slot is still selected.

The only problem is finding someone willing to code that.

**Comment by vsub** [comment]
Um maybe I didn't understand something but what if you play a game and save to slot 5 and you remembered that your progress is in slot 5 but then start another game and save to slot 2 and close pcsx2

**Comment by vsub** [comment]
Um maybe I didn't understand something but what if you play a game and save to slot 5 and you remembered that your progress is in slot 5 but then start another game and save to slot 2 and close pcsx2

**Comment by lightningterror** [comment]
Ah I forgot about that, then a solution would be to add the save information in the savestate or include 2 files when saving. The information is read the same time when a game is booted.

Example:
```
SCES-51719 (715CF2EC).08.p2s
SCES-51719 (715CF2EC).08.ini
```

**Comment by lightningterror** [comment]
Actually there is no need to save a separate ini for separate save. The info is stored in the ini which slot is newest and which slot was last selected.

It could be done with 1 file. 
```
SCES-51719 (715CF2EC).08.p2s
SCES-51719 (715CF2EC).ini
```

**Comment by willkuer** [comment]
But did you consider just reading the file change date as vsub suggested?

Also ini typically is a settings file extension while you want to track meta info. And even if you want to track meta info why not within the same file as the structure of savestate files just follows pcsx2's own definition.

**Comment by KrossX** [comment]
Just checking the files for the one with the most recent modified date should the enough I think. It's available on Windows, but I don't know if it's also available on linux? If not, then maybe save files would just have to be deleted and created anew. That shouldn't be much of a problem either, create new savestate temp file, if successful, delete target name and rename temp file. That should give files with a nice creation date... right?

**Comment by cmdrkotori** [comment]
On Linux the modification date of a file can be detected by using `stat` function in sys/stat.h. https://linux.die.net/man/2/stat MacOS too has a similar `stat` function. https://www.unix.com/man-page/osx/2/stat/ The equivalent function in the Microsoft UCRT is `_stat` in sys/stat.h
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions These functions return a `stat` structure with the modified time in the `st_mtime` field, which can be passed through to `ctime` et al for printing. This should be a neat fallback for populating the save time when the corresponding ini file is missing.

**Comment by lightningterror** [comment]
Just a heads up for anyone wondering why the feature is not working, it's currently disabled since there are some leftover issues to iron out.

**Comment by chazzy1** [comment]
> Just a heads up for anyone wondering why the feature is not working, it's currently disabled since there are some leftover issues to iron out.

Thanks for the heads up. I've just found out how convenient it was. it's really hard to select ssat slots without dates on it.
