### ISSUE TITLE
Is it possible to control the analog sticks with the keyboard?

### ISSUE THREAD

**Issue by cirosantilli** [PCSX2/pcsx2#2075]
1.4 on Ubuntu 17.04 from PPA.

Or would discretizing the analog on the keyboard keys make games simply unplayable?

**Comment by mirh** [comment]
Check latest git. 
https://launchpad.net/%7Epcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by gregory38** [comment]
You can map the analog stick with the keyboard. However, it will be either 0 or max. We can't transform your digital keyboard on analog button.
