### ISSUE TITLE
[Debugger bug] Mouse click focus is offset by 1 or more lines near functions whose final line contains a branch instruction.

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#2076]
***PCSX2 version:***
v1.5.0-dev-2174-g9c8a48f38 (2017-08-14; 9c8a48f38c46059263607b81217ca87ebc787b70)

***PCSX2 options:***
Defaults.

***Plugins used:***
Defaults (GSdx32-SSE4, LilyPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk).

***Description of the issue:***
In PCSX2's debugger, if a function's final line contains a branch instruction (such as ``jal``, ``j``, ``beq`` or ``beqz``), clicking on the next function's second or later lines will unexpectedly set focus on the line above what was clicked. If the second function also ends with a branch instruction, the offset will grow to be 2 lines off when clicking the third function's third or later lines. This behaviour only occurs when one or more affected branch instructions are visible in the debugger's top-right panel. If they go off-screen, clicking focus will work properly.

I presume what's happening is that if a branch instruction is on-screen, the debugger will put the branch's delay slot (i.e. the instruction that directly follows it) in a special state. But that functionality doesn't work as intended if the first line of a function is the delay slot for a branch instruction situated in the previous function's final line.

On a side side, it's highly unlikely that any game's ELF files would contain any branch instructions on the final line of any of their functions. But that scenario can occur in practice as a result of #2065, pnaches or custom instructions inserted via the debugger.

Would it be possible to modify the debugger to ensure that clicked lines receive focus when clicked on in the aforementioned situation?

***How to reproduce the issue:***
1. Launch PCSX2 and fast boot any game.
2. In the log window, find the game's entrypoint and take note of it.
3. Open the debugger.
4. In the bottom of the debugger window, switch to the "Breakpoints" tab, right click, select "Add new" and create an execute breakpoint based on the entrypoint's address.
5. Fast boot the game again and wait for the breakpoint to be triggered.
6. In the debugger window's top-right panel, the background colour of the MIPS instructions below the breakpoint will be a pale colour. It represents the range of instructions belonging to the entrypoint's function. The debugger visualizes each function with alternating pale background colours.
7. Right click on the before-last line of the entrypoint's function, select "Assemble Opcode", type ``nop`` in the popup that appears, then click "OK".
8. Right click on the final line of the entrypoint's function, select "Assemble Opcode", type ``j 00000000`` in the popup that appears, then click "OK".
9. Make sure the last 2 lines of the entrypoint's function and the first 2 lines of the next function are visible in the top-right panel.
10. Left click on the second function's first line. The line will gain focus.
11. Left click on any of the second function's subsequent lines. The line above the clicked one will gain focus.
12. Scroll down until the end of the entrypoint function is completely off-screen. The second function's first line should be the first instruction listed at the top of the panel.
13. Left click on any of the second function's subsequent lines that are visible. The line will gain focus.
14. Step 11 didn't work as expected. The lines that were clicked on should've gained focus (not the lines above them). Steps 12-13 demonstrated that if the end of the execute function is outside of the panel's viewport, click focus will work properly again.

***Last known version to work:***
* Never worked.
* Oldest tested version: v1.2.1-511-g02b19b7 (2014-08-17; 02b19b7686888539d1ee55e08c5d2dfbb5bd1321).

***PC specifications:***
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; GPU driver: Crimson 16.2.1 Beta; OS: Windows 7 SP1.

***Other comments:***
@Kingcom @NZJenkins @turtleli FYI.

**Comment by rkubes** [comment]
This can be resolved one of two ways, but I'm not sure which is option would be preferred.

First, the root cause of this issue is that **visually**, the function "ends" at that branch/jump that you added; however, **internally** the function is expanded to also includes the delay slot (which is actually the first instruction of the next function in the case above). So when the debugger does the math to see how many lines after the end of the function you've clicked, it's including the delay slot from the **internal** representation - which is misleading, because the user clicks based on the **visual** representation.

Long story short, there are two possible approaches. I can create a patch for either if there's preference to either one.

**Option 1)** What I believe is correct
>In "DisassemblyManager.cpp" in "DisassemblyFunction::load"
> Update the logic so that as Opcode Sequences are added, don't add in the Delay Slot after a branch if the Delay Slot is outside of the bounds of the function. (As in the case described by Aced14)
> 
> The **pros** of this approach are:
> - This would also fix to keep the last lineAddress bounded by the start address + size of the function.
> - This would only impact functions.
> - This would only change one line of code.
>
> The **con** of this approach is: I'm not certain that this wouldn't break anything else.

**Option 2)**
> In "DisassemblyManager.cpp" in "DisassemblyManager::getNthNextAddress"
> Update the logic so instead of relying on "entry->getNumLines()" to be accurate, use logic to find the index of the last line address that's within bounds as determined by entry->address + entry->size
>
> The **pro** of this approach is it should limit the impact to only within determining the "nth next address" - as opposed to omitting a trailing delay slot from a function in a DisassemblyEntry structure.
>
> The **con** of this approach is it feels like a hack, and it would impact all types of DisassemblyEntries - as opposed to being targeted to Functions.

**Comment by Kingcom** [comment]
I think option 1 would be the best way to fix it. It's pretty much an oversight, and normally you would expect the function size to correctly include the  final delay slot. If it's modified at runtime there's not much you can do besides sticking to what you know.

**Comment by Aced14** [comment]
FWIW, earlier today I compared an older build against #2250's Orphis build (v1.5.0-dev-2244-g854246846). Wasn't able to reproduce this issue at all in the newer build.

@rkubes Thanks :)!
