### ISSUE TITLE
Ratchet Gladiator: Broken shadows.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2077]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, speedhacks disabled, OpenGL software mode (Hardware and DX are also broken)

***Plugins used:***
All default.

***Description of the issue:***
The game "Ratchet Gladiator" is unable to display correct shadows and create some visual corruptions.
(screenshot in the comment section)

***How to reproduce the issue:***
Load pcsx2 and Ratchet Gladiator, go ingame.

***Last known version to work:***
Don't exist, was broken before.

***PC specifications:***
 Intel Core 2 Duo E8600  GTX 780Ti  Windows 10 64 Bit

***Note***
Can be a core issue, Software and Hardware have the issue.

**Comment by MrCK1** [comment]
@Atomic83GitHub did you try using Auto Flush hack ect. ?

**Comment by willkuer** [comment]
Possibly a core (i.e. VU) issue.

**Comment by MrCK1** [comment]
Possibly, I just suggested it since it works for Jak.

**Comment by atomic83GitHub** [comment]
Note: this bug can't be avoid by enable Alpha and Alpha stencil Hack, auto flush don't do anything.
Note2: A backward compatible ps3 do the same bug on this game (even the US version)

**Comment by MrCK1** [comment]
And all renderers are broken?

**Comment by atomic83GitHub** [comment]
Yes , all : software include

**Comment by MrCK1** [comment]
Lastly, did you turn off MTVU and try SuperVU/Interpreter?

Also, GS dump and screenshot would be nice.

**Comment by atomic83GitHub** [comment]
Wait, all of this arrive :)

**Comment by atomic83GitHub** [comment]
GSDump https://drive.google.com/drive/folders/0B0Ph0W1NYxIVNDNwY2I0Tk1OMms?usp=sharing

Screenshot with Super vu (one with dx11 hardware, the other with openGL software)
![capture](https://user-images.githubusercontent.com/26351275/31019619-957a6f30-a530-11e7-8705-25e912deedba.PNG)
![capture2](https://user-images.githubusercontent.com/26351275/31019634-9dcb4f42-a530-11e7-84d8-d0d6c19f25a3.PNG)

**Comment by MrCK1** [comment]
What about VU interpreter? BTW, it doesn't matter what renderer you're using.

**Comment by atomic83GitHub** [comment]
There it is:
![image](https://user-images.githubusercontent.com/26351275/31019998-e92bb23c-a531-11e7-93ee-b9642a270afd.png

**Comment by atomic83GitHub** [comment]
Here is the GSDX temp2 info and Blockdump of the issue:

https://drive.google.com/file/d/0B0Ph0W1NYxIVbDVXUzBUNHhUQ1U/view?usp=sharing

**Comment by MrCK1** [comment]
@atomic83Github Can you disable dumping (dump=0) and add this to your GSdx.ini?
`ENABLE_OGL_DEBUG = 1`

You should see a file called `gsdx_ogl_hw_debug.txt` - can you upload that here as well?

**Comment by atomic83GitHub** [comment]
Add this don't made a gsdx_ogl_hw_debug.txt.. strange

**Comment by MrCK1** [comment]
You're using the debug plugin I gave you right?

**Comment by atomic83GitHub** [comment]
No, it don't work.

**Comment by MrCK1** [comment]
The plugin should be working for you, weird. Rename this extension to .exe and add it to your PCSX2 folder.
[pcsx2-dbg.zip](https://github.com/PCSX2/pcsx2/files/1383069/pcsx2-dbg.zip)

**Comment by atomic83GitHub** [comment]
I have an issue with visual studio : msvcp140d.dll and other dll are missing.

**Comment by MrCK1** [comment]
Install the 2014 VC redistributable and others if they throw an error.

**Comment by atomic83GitHub** [comment]
Apparently, it need debug dll, and I can't find them on the Microdoft website.

**Comment by MrCK1** [comment]
Try the regular GSdx dll, I can't remember if it works or not.

**Comment by atomic83GitHub** [comment]
I mean ,The entire PCSX2-dbg won't start I have install vc redist 2017 2015 and 2013, still nothing.

**Comment by atomic83GitHub** [comment]
Seems to be a Windows 10 issue according to some forum.

**Comment by MrCK1** [comment]
I think we're OK for now. We'll have someone look at the blockdump later. Don't worry about the GSdx log :)

**Comment by atomic83GitHub** [comment]
Ok, sorry. But, after more invertigation, d-dll must be shiped with the "non-release#debug" version of the program according to Microsoft and unfortunately,it seems that some dll was remove after Windows 8.1.

**Comment by MonJamp** [comment]
This is a microVU issue. Shadows are fixed when using the interpreter for VU0 and while using a software renderer or the OpenGL hardware renderer with Blending Accuracy set to Basic.
