### ISSUE TITLE
Vampire Night, useless patch

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2084]
This game have the EETimingHack in the GameDB, it is not necessary.

Request: remove the EETimingHack for this game.

**Comment by MrCK1** [comment]
Still could use the standard Info. A test.on 1.4.0 and later would be nice to see if it was fixed recently.

**Comment by atomic83GitHub** [comment]
It work on 1.4.0, the 0.99 don't work.

**Comment by MrCK1** [comment]
I saw that on the wiki. That good enough for me.

@atomic83GitHub I'm going to close this, so can you make a PR for this to remove it?

**Comment by lightningterror** [comment]
There's already an issue opened about gamedb updates. Post there or on the forum topic.
https://github.com/PCSX2/pcsx2/issues/2011
