### ISSUE TITLE
VU ALWAYS at 100% on new rig GTX 1070/Ryzen 7

### ISSUE THREAD

**Issue by AshMain** [PCSX2/pcsx2#2089]
Ok so I just build a BRAND new no expenses desktop rig to replace my old Asus G74sx gaming laptop.

My specs:
Ryzen 7 1700x
GTX Strix 1070 Tri Fan
GSkill Trident Z 16GB RAM
Asus Strix B350-f mother board
Corsair 750W power supply
And 2TB HD

There is NO reason my old G47SX can run this game (NBA Street 2) and have some shutter lag when all 6 players are on the screen. And this brand new rig cant even pass the loading menu before maxing out the VU and crashing.

PLEASE HELP! I have been trying to play this game for years now. This is really dumb my new rig cant run this but my outdated and much slower and more limited laptop at least tried. 

What's the deal?

**Comment by MrCK1** [comment]
This isn't the place for support. I replied to your original post on the forums.
