### ISSUE TITLE
Ratchet Gladiator: EmotionEngine interpreter crash the emulator ingame.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2090]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, EE set to interpreter (with and without the cache), speedhacks disabled

***Plugins used:***
All default

***Description of the issue:***
Set the Emotion Engine to interpreter cause an emulator crash ingame and in loading screen.

***How to reproduce the issue:***
Load "Ratchet Gladiator" with EE set to interpreter and go ingame

***Last known version to work:***
Don't exist, was broken before.

***PC specifications:***
Intel Core i7 4770k  GTX 560Ti  Windows 10 64 Bit

**Comment by MrCK1** [comment]
The EE interpreter is only used for diagnosis and the game already works in the recompiler.. I don't think there's much point in this issue, so I'm going to close it for now.

**Comment by atomic83GitHub** [comment]
And by the way, interpreter crash on the ONI game with a PCSX2 DMA error.
![image](https://user-images.githubusercontent.com/26351275/31314647-bb798f1e-ac05-11e7-95ac-0458abb2bdba.png)

**Comment by atomic83GitHub** [comment]
And by the way, it seems to happen in all Ratchet and Clank games

**Comment by TheTechnician27** [comment]
Can confirm that this is still an issue for me in _Deadlocked_  (tested in 1.7.4110). The game actually doesn't crash during cutscenes or in the menu, but once you're in-game, it immediately crashes. Not only that, but you can't even exit out of the game or X out of PCSX2. The program actually will ask you if you want to exit out of the game (so it's not like it's entirely unresponsive), but if you select 'Yes', it will just sit there doing nothing forever. I had to manually either go to my task manager and kill the program or go to the terminal and run kill -9.

While I wouldn't call "a game runs poorly or not at all with EE recompilation off" necessarily an issue, I would call it an issue when it makes PCSX2 so unresponsive that you need to circumvent PCSX2's UI and personally tell your OS to take it out behind the shed.
