### ISSUE TITLE
PCSX2 for Mac

### ISSUE THREAD

**Issue by COOLIRON2311** [PCSX2/pcsx2#2097]
There is a PCSX2 version for Mac, which is not getting any updates since 2012.
Maybe someone could port current version to Mac? If not is it possible to run current windows version in Wine?

**Comment by ssakash** [comment]
Refer https://github.com/PCSX2/pcsx2/issues/18

**Comment by gregory38** [comment]
Fwiw, I think there are some wineskin for some version. So it depends on various factor (wine/dx.,,, versions) but it could work with wine.
