### ISSUE TITLE
pcx2

### ISSUE THREAD

**Issue by jacki11** [PCSX2/pcsx2#2100]
my pcx2 is not showing full content of the game on screen some things are missing like text.In game star wars the clone wars republic heroes during hacking the console in the game there is a circle in corner of screen showing the console,that circle is also missing.Please someone help me to sort out the problem.

**Comment by jacki11** [comment]
![screenshot 8](https://user-images.githubusercontent.com/32981035/31851831-1698a962-b687-11e7-810c-1cd9df84d8e8.png)
![screenshot 9](https://user-images.githubusercontent.com/32981035/31851832-16d2b3c8-b687-11e7-84f7-e3e2444d1f28.png)

**Comment by jacki11** [comment]
this circle  on the corner is not appearing in my pcx2

**Comment by atomic83GitHub** [comment]
Did you try the Software mode?

**Comment by MrCK1** [comment]
@jacki11 This isn't a place for hemp or support, please use the (forums)[https://forums.pcsx2.net/index.php] for that.

**Comment by jacki11** [comment]
yeah.I tried all modes.
