### ISSUE TITLE
pcx2 graphic problem

### ISSUE THREAD

**Issue by jacki11** [PCSX2/pcsx2#2101]
My pcx2 is not showing full content on the screen.Some text is also missing.In game,star wars the clone wars the health bar and some other things are also missing.
![screenshot 9 - copy](https://user-images.githubusercontent.com/32981035/31858788-c235e27a-b719-11e7-9e0f-733dc2a0a866.png)
![screenshot 8](https://user-images.githubusercontent.com/32981035/31858789-c268fdea-b719-11e7-9996-fa1625ff2ea4.png)
THIS CIRCLE IN THE CORNER OF THE GAME IS MISSING FROM MY GAME.PLEASE HELP TO RESOLVE THE PROBLEM.

**Comment by atomic83GitHub** [comment]
Try the software mode.

**Comment by jacki11** [comment]
i tried every mode

**Comment by MrCK1** [comment]
@jacki11 As I said before, please don't ask for help here. If you post your problem in the [forums](https://forums.pcsx2.net/index.php); we'll be able to respond to you quicker over there ;)

**Comment by MrCK1** [comment]
@jacki11 Just please be patient, we'll respond to your issue as soon as we can but it can take upwards of a few hours for someone to reply ;)
