### ISSUE TITLE
Harry Potter and  Philosopher's Stone screen bug [SLES-52055]

### ISSUE THREAD

**Issue by shikulja** [PCSX2/pcsx2#2103]
***PCSX2 version:***
1.5.0.2207

gsdx hardware 
(in software ok)

right screen 

http://skrinshoter.ru/s/231017/kQHeKy0x?a
http://skrinshoter.ru/s/231017/aGkpoYr2?a

***PC specifications:***
``(i7 7700k GPU: amd r9 380 OS: Windows 7 64 Bit)``

**Comment by MrCK1** [comment]
Is this Chamber of Secrets or Philosopher's Stone? Your screenshots and title don't match.

**Comment by lightningterror** [comment]
Can you try out
https://ci.appveyor.com/api/buildjobs/h2op0uks1y5hjs2q/artifacts/pcsx2-v1.5.0-dev-2213-g64fe773a0-3391-vs2015-Win32-AppVeyor.7z

Enable Frame Buffer Conversion hack in HW Hacks.

**Comment by shikulja** [comment]
no help

**Comment by MrCK1** [comment]
Can you switch to the OpenGL renderer?

**Comment by shikulja** [comment]
not help, 
in opengl the same thing
only software work ok

**Comment by lightningterror** [comment]
Can you provide a GS dump? I'd like to test this out.

**Comment by shikulja** [comment]
https://drive.google.com/file/d/0B6Bbbdpi5BzBTHE5elNwTmM2RFk/view?usp=sharing

**Comment by atomic83GitHub** [comment]
I suspect it's custom resolution, change custom resolution to native or 2xnative.I t should help also, enable gs memory wraping just for accuracy.
Report if it don't work, the TOP SPIN game have also this issue.

**Comment by shikulja** [comment]
x2-4 resolution help
(old custom 1920x1080)

**Comment by lightningterror** [comment]
Custom resolutions tend to cause issues on many other games as well since it's not properly upscaled.
This is why Native upscaling works best.

Anyway I'll close this.
