### ISSUE TITLE
Optional Pitch Shifting with TimeStretch Audio

### ISSUE THREAD

**Issue by UlsterRose** [PCSX2/pcsx2#2105]
Sometimes I record clips of Burnout Revenge in PCSX2 showcasing unused or obscure elements of the game, using a software renderer for accuracy purposes, though my i5-6400 isn't enough to handle it at full speed (Revenge is a demanding enough game in hardware mode, and even then I can only **usually** run the game at full speed), so what I do is set PCSX2 to run at half speed with TimeStretch enabled, record at that, then speed the footage up to full speed in editing.

The problem is when I speed up the video, the audio becomes distorted, as you can see here:
https://www.youtube.com/watch?v=xENEGG673k4

I've tried various settings with TimeStretch, but all of them all seem to result in the audio sounding quite strange. **If the audio only changing in tempo and not in pitch is what's causing this eventual distortion when the video gets sped back up**, the option of having the audio stretch in **speed** in addition to just tempo would be very helpful.

**Comment by MrCK1** [comment]
@UlsterRose For starters, you could try using the build [here](https://ci.appveyor.com/project/gregory38/pcsx2/build/1.3341-master/artifacts) with a newer version of SoundTouch and see if it helps with the audio distortion.

**Comment by UlsterRose** [comment]
I think I've traced the issue to the audio-stretching quality of Magix Vegas, since I tried instead stretching the audio in Audacity and got far better (though still a little tinny) results. Unless there are other benefits to having speed stretching, this can probably be closed.

**Comment by MrCK1** [comment]
Audacity and PCSX2 both use the SoundTouch lib, tweaking the advanced Timestretch SPU2-X settings should help bring it closer to Audacity.
