### ISSUE TITLE
Star Wars Bounty Hunter Graphics Issue

### ISSUE THREAD

**Issue by phil4853** [PCSX2/pcsx2#2107]
***PCSX2 version:***
Latest Dev

- **Notes**:
 

***PCSX2 options:***
See screenshots of settings.

***Plugins used:***
GSD10 Direct 3D11 (Hardware)

***Description of the issue:***
Smearing/blurring at bottom of screen

***How to reproduce the issue:***
Play game using same settings.

***Last known version to work:***
Unknown.

***PC specifications:***

Operating System =  Microsoft Windows 10 Home (build 10586), 64-bit
Physical RAM     =  3529 MB
CPU name         =  AMD A6-6310 APU with AMD Radeon R4 Graphics
Vendor/Model     =  AuthenticAMD (stepping 01)
CPU speed        =  1.795 ghz (4 logical threads)

**Comment by phil4853** [comment]
Guys / Gals

Would really appreciate you help, I have got the game to within inch of perfection except the the bottom of the screen which is blurred, no matter what I do (changing between software/hardware modes etc) I cannot get rid of it!
![31984812-b9abf9ee-b95a-11e7-9f92-58a3c25ff628](https://user-images.githubusercontent.com/33083272/32034895-6c05a65a-ba0d-11e7-935d-79f7340f5d90.png)

**Comment by phil4853** [comment]
Hope this makes sense to you guys...


PCSX2 1.5.0-20171014225440 - compiled on Oct 15 2017
Savestate version: 0x9a0d0000

Host Machine Init:
Operating System =  Microsoft Windows 10 Home (build 10586), 64-bit
Physical RAM     =  3529 MB
CPU name         =  AMD A6-6310 APU with AMD Radeon R4 Graphics
Vendor/Model     =  AuthenticAMD (stepping 01)
CPU speed        =  1.795 ghz (4 logical threads)
x86PType         =  Standard OEM
x86Flags         =  178bfbff 7ed8220b
x86EFlags        =  2fd3fbff

x86 Features Detected:
SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX
SSE4a 

Reserving memory for recompilers...

Loading plugins from C:\Program Files (x86)\PCSX2 1.4.0\Plugins...
Bound   GS: gsdx32-sse2-r5875.dll [GSdx 0 (MSVC 18.00, SSE2) 0.1.16]
Bound  PAD: lilypad.dll [LilyPad (20151231175709) 0.11.0]
Bound SPU2: spu2-x.dll [SPU2-X 20151231175709 2.0.0]
Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz (20151231175709ll) 0.9.0]
Bound  USB: USBnull.dll [USBnull Driver 20151231175709 0.7.0]
Bound   FW: FWnull.dll [FWnull Driver 20151231175709 0.7.0]
Bound DEV9: DEV9null.dll [DEV9null Driver 20151231175709 0.5.0]
Plugins loaded successfully.

(GameDB) 9712 games on record (loaded in 451ms)
HLE Notice: ELF does not have a path.

Initializing plugins...
Init GS
Init PAD
Init SPU2
Init CDVD
Init USB
Init FW
Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
Opening GS
Opening PAD
Opening SPU2
Opening CDVD
isoFile open ok: C:\Users\phili\Videos\Star Wars Games\Star Wars - Bounty Hunter.iso
Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1155424 sectors)
Opening USB
Opening FW
Opening DEV9
McdSlot 0 [File]: C:\Program Files (x86)\pcsx2-v1.5.0-dev-2211-g58f2b6c25-windows-x86\memcards\Mcd001.ps2
McdSlot 1 [File]: C:\Program Files (x86)\pcsx2-v1.5.0-dev-2211-g58f2b6c25-windows-x86\memcards\Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
Bios Found: Europe  v02.00(14/06/2004)  Console
# Initialize memory (rev:3.70, ctm:196Mhz, cpuclk:147Mhz detected)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2004-0614, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20040614-100914,ROMconf,PS20200EC20040614.bin:11696>
# Total accessable memory size: 32 MB (B:2:8:0) (370:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  6 2003 08:38:48
  CPUID=2e20, BoardID=0, ROMGEN=2004-0614, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_508.31;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL
found 0 symbols
ELF (cdrom0:\SLES_508.31;1) Game CRC = 0xA7E91CE8, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_508.31;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 © Sony Computer Entertainment Inc. 
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 ©SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLES_508.31;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_508.31;1
0 00100000 002c2880 .............................................
3 70000000 00000004 .
Loaded, cdrom0:¥SLES_508.31;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
Not found Cheats file: C:\Program Files (x86)\pcsx2-v1.5.0-dev-2211-g58f2b6c25-windows-x86\cheats\A7E91CE8.pnach
Overall 0 Cheats loaded
Overall 0 Widescreen hacks loaded
(Wide Screen Cheats DB) Patches Loaded: 0
KMem::CreateSmallPools: Allocating small pools
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init

IOP Realtime Kernel Ver. 2.2
    Copyright 1999-2002 © Sony Computer Entertainment Inc. 
(UpdateVSyncRate) Mode Changed to NTSC.
(UpdateVSyncRate) FPS Limit Changed : 59.94 fps
Reboot service module.(99/11/10)
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
cdvd driver module version 0.1.1 ©SCEI
open fail name ¥FIREWIRE.TXT;1
loadmodule: fname cdrom0:¥IRX¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥IRX¥PADMAN.IRX;1 args 12 arg thpri=18,28
padman: thread priority: high=18, low=28
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥IRX¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥IRX¥STREAM.IRX;1 args 0 arg 
 Exit MultiStream V5 Thread Load 
loadmodule: id 28, ret 0
--- R2 Video - PAL ---
(UpdateVSyncRate) Mode Changed to PAL.
(UpdateVSyncRate) FPS Limit Changed : 50.00 fps
open fail name ¥DATA¥IFACE¥TEXTDATB.TBN;1
open fail name ¥DATA¥IFACE¥TEXTDATB.TBN;1
loadmodule: fname cdrom0:¥IRX¥CRI_ADXI.IRX;1 args 0 arg 
CRI ADX Driver Ver.8.01(May 17 2002 14:23:41)
CRI ADX Driver : Thread Priority=39
CRI ADX Driver : SPU CORE Number=0
CRI ADX Driver : sceSdInit(SD_INIT_COLD) call.
loadmodule: id 29, ret 0
open fail name ¥DATA¥IFACE¥TEXTDATB.TBN;1
loadmodule: fname cdrom0:¥IRX¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 30, ret 2
loadmodule: fname cdrom0:¥IRX¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 31, ret 2
open fail name ¥MM_ANI_2.VFX;1
open fail name ¥MM_ANI_4.VFX;1
open fail name ¥MM_ANI_2.VFX;1
open fail name ¥MM_ANI_4.VFX;1
searchbyname: module name mcserv
searchbyname: return 31
stopmodule: module id 1f args 0 arg 
stopmodule: return 31, result 1
unloadmodule: module id 1f
unloadmodule: return 31
searchbyname: module name mcman
searchbyname: return 30
stopmodule: module id 1e args 0 arg 
stopmodule: return 30, result 1
unloadmodule: module id 1e
unloadmodule: return 30
open fail name ¥DATA¥IFACE¥TEXTDATB.TBN;1
VM must be rebooted to create a useful block dump.

**Comment by MrCK1** [comment]
@phil4853 You forgot to fill in the info from the template...

**Comment by phil4853** [comment]
Here are my settings...
![screenshot 14](https://user-images.githubusercontent.com/33083272/32037751-b723b562-ba1e-11e7-8dce-c87415159181.png)
![screenshot 15](https://user-images.githubusercontent.com/33083272/32037752-b7446640-ba1e-11e7-8c0d-f20d120b3f16.png)
![screenshot 16](https://user-images.githubusercontent.com/33083272/32037754-b75c070a-ba1e-11e7-8cdb-7db6d8509a56.png)
![screenshot 17](https://user-images.githubusercontent.com/33083272/32037755-b773d04c-ba1e-11e7-8cd5-eae2af0cd532.png)
![screenshot 18](https://user-images.githubusercontent.com/33083272/32037756-b78c7598-ba1e-11e7-98ee-e4ff3dee72bc.png)
![screenshot 19](https://user-images.githubusercontent.com/33083272/32037757-b7a57cf0-ba1e-11e7-89d4-be47c688fa7f.png)
![screenshot 20](https://user-images.githubusercontent.com/33083272/32037758-b7cdf856-ba1e-11e7-872f-f26df91410f8.png)
![screenshot 21](https://user-images.githubusercontent.com/33083272/32037759-b814d53c-ba1e-11e7-9418-98099fec1444.png)
![screenshot 22](https://user-images.githubusercontent.com/33083272/32037761-b8853b10-ba1e-11e7-8aef-7f214f640389.png)
![screenshot 23](https://user-images.githubusercontent.com/33083272/32037762-b907cb84-ba1e-11e7-8f62-b88d643e20a3.png)

**Comment by atomic83GitHub** [comment]
What is this GSDX version?
Use the version packed with PCSX2, if your GPU don't support DX11, use DX9.

**Comment by MrCK1** [comment]
@phil4853 You're using an outdated version of GSdx. Can you check your plugins please?

**Comment by MrCK1** [comment]
@phil4583 Any update for us?

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by FlatOutPS2** [comment]
You used the GSdx graphics plugin from PCSX2 1.2.1. Select a current one to fix the issue.
