### ISSUE TITLE
Guitar Hero : Intro FMV hangs

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2108]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, tested with and without speedhacks

***Plugins used:***
All default. Tried some GSDX and Spu2X value, Nothing change.

***Description of the issue:***
The intro FMV hang at the end before reaching the game menu.

***Workaround***
-Press the "start" key before the FMV's end.

-Enable the Skip MPEG hack.

***How to reproduce the issue:***
Load PCSX2 and Guitar hero, don't skip the intro FMV.

***Last known version to work:***
Don't exist, the game was broken before.

***PC specifications:***
Amd fx 8350, Gainward GTX 780ti, Windows 10 64bit.

***Blockdump to the bios at the end of the intro fmv***

[Guitar hero fmv.zip](https://github.com/PCSX2/pcsx2/files/1418179/Guitar.hero.fmv.zip)

Do not hesitate to tell me if you want the GSDX temp2 folder.

**Comment by MrCK1** [comment]
Can you try 1.4.0, 1.2.1 and 1.0.0 to be sure? There's no report that mentions the videos being broken for this game.

**Comment by atomic83GitHub** [comment]
Yes, the FMV is also broken on these version.

**Comment by MrCK1** [comment]
Did you try EE/IOP interpreter, ect?

**Comment by atomic83GitHub** [comment]
Yes, still the same issue.

**Comment by atomic83GitHub** [comment]
Edit: Set the EEcyclerate to -3 and IOP to interpreter solve the issue.

**Comment by atomic83GitHub** [comment]
Sidenote: set the EEcyclerate to -3 also fix Ratchet and Clank 2 Thug4less crash without the need of the timing hack.

**Comment by atomic83GitHub** [comment]
You are right, EEcyclerate to -3 and IOP to recompiler also work.

**Comment by MrCK1** [comment]
@atomic83GitHub Check if EE Timing Hack will work without -3 EE cyclerate.

**Comment by atomic83GitHub** [comment]
No, EETimingHack don't work here.

**Comment by MrCK1** [comment]
Not sure about this, the intro only hung once out of the multiple trials even on standard EE cyclerate. Basically I can't really reproduce this reliably for it to be a valid issue.

**Comment by ElementUranium** [comment]
same ![image](https://user-images.githubusercontent.com/34288335/33635690-e50df836-da10-11e7-88bd-f2300da6720f.png)

**Comment by FlatOutPS2** [comment]
Did you test the block dump? It does not show the FMV on my end.

**Comment by atomic83GitHub** [comment]
Try with this one:
https://drive.google.com/file/d/1227qow7bGJeX6U46-1Pq3AGKOn1fraZc/view?usp=sharing

**Comment by FlatOutPS2** [comment]
Same result. It shows 2 logo images and then stops at a loading/memory card check screen

**Comment by atomic83GitHub** [comment]
I have a very Strange result, everytime a make a blockdump on it, it throw some tlb misses error:
![image](https://user-images.githubusercontent.com/26351275/34640599-f939ac08-f2f5-11e7-8023-19390149f622.png)

**Comment by refractionpcsx2** [comment]
This was fixed by https://github.com/PCSX2/pcsx2/commit/0f20a22e10fed3c93f05d4976d9c70777531b63e
