### ISSUE TITLE
From Russia with love, blue lines

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2109]
***PCSX2 version:***
1.5.0-dev-2211-g58f2b6c25

- **Notes**:
In the game from Russia with love (PAL) there are a lot of blue lines blue "puddle" this has been tested using DX11 and Opengl, native resolution and 3x native, 4x native, etc. 

Tested with enabled/disabled HW hacks "All tested" different blending unit accuracy, CRC hack level, Accurate date, mipmaping, etc. 

Disabling the anisotropic looks better, but only a bit.

Note: Images attached.
![3](https://user-images.githubusercontent.com/12205048/32130164-36225a88-bb93-11e7-8455-939bdf4b3dcc.jpg)
![1](https://user-images.githubusercontent.com/12205048/32130165-3642e532-bb93-11e7-87d4-43a53b5293a8.jpg)
![2](https://user-images.githubusercontent.com/12205048/32130166-36619342-bb93-11e7-9e34-c37cfe8fb03b.jpg)

***How to reproduce the issue:***
This can be seen specially in the first level with the car. When you need to escape from the others and destroy the tank.

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
i7 4790k
GTX 970 4GB 
16 GB RAM
Windows 10 x64

**Comment by MrCK1** [comment]
Did you check 1.4.0?

**Comment by willkuer** [comment]
Software mode (e.g. by pressing f9) is fine? What happens if you disable mipmap for the sw renderer?

**Comment by LuismaSP89** [comment]
@MrCK1 In 1.4.0 the game freezes after the MGM´s Lion.

@willkuer Yes, software mode is fine. And disabling mipmap when sw renderer is active only causes to active the hardware renderer, if i enter again in software mode (With mipmap disabled) it changes nothing, it looks the same with software mode + mipmap on/off.

**Comment by atomic83GitHub** [comment]
Did you try any Clamp/round mode and/or hacks under the core section?

**Comment by LuismaSP89** [comment]
This is my config for this game:

![3](https://user-images.githubusercontent.com/12205048/32137997-4497caf6-bc2b-11e7-9bee-5915e43a730b.jpg)
![1](https://user-images.githubusercontent.com/12205048/32137998-44b5ad3c-bc2b-11e7-8b41-b106d4d5a8de.jpg)
![2](https://user-images.githubusercontent.com/12205048/32137999-44d201e4-bc2b-11e7-918b-f0f740911914.jpg)

I tested other rounding mode under VU´s and EE/IOP sections. And set by default the speed hack section (VU Cycle Stealing = 0) and (EE Cycle = 0) and the result is the same.

**Comment by LuismaSP89** [comment]
@MrCK1 Ok my apologies, i forgot that this game needs (VU Cycle Stealing = 2) and (EE Cycle = 1) to work, "To avoid the hang after the MGM´s Lion".  Wich is my default setting for this game, i tested now the 1.4.0 with that two settings and this is the result.

![1 4 0](https://user-images.githubusercontent.com/12205048/32138206-ed052a32-bc2e-11e7-914e-efadfd1a352f.jpg)

As you can see it´s even worse, the blue stripes remains, and a red bars appear in the entire screen, this doesn´t happen in 1.5.0

Note: All settings by default in 1.4.0, except the 3x resolution, and the (VU Cycle Stealing = 2) and (EE Cycle = 1)

**Comment by atomic83GitHub** [comment]
Can you set the GSDX render to OpenGL and enable the EETiminghack?

**Comment by LuismaSP89** [comment]
@atomic83GitHub  No changes with EETiminghack activated.

**Comment by RedPanda4552** [comment]
Try enabling the Disable Depth Emulation hack in the OpenGL HW renderer? That's the fix for NFS Carbon, which is suspiciously similar to this.

**Comment by LuismaSP89** [comment]
@Redpanda4552 Nope, as i said in my first comment, all HW hacks has been tested.

**Comment by RedPanda4552** [comment]
Was this on both 1.5.0 and 1.4.0? I was referencing the artifacting from your 1.4.0 screenshot, probably should have mentioned that.

**Comment by LuismaSP89** [comment]
@RedPanda4552 Yes, is in both versions, 1.4.0 and 1.5.0, but in the 1.5.0 the red lines are fixed.

If you open the 1.4.0 image with the red stripes, you can see too the blue things i mentioned (maybe you need to zoom the image if you open it in a mobile phone)

**Comment by MrCK1** [comment]
@LuismaSP89 Can you upload a GS Dump for this issue please?

**Comment by LuismaSP89** [comment]
@MrCK1 Of course, here it is, two GS Dumps : )


[GS DUMP From Russia with love.zip](https://github.com/PCSX2/pcsx2/files/1602337/GS.DUMP.From.Russia.with.love.zip)

**Comment by FlatOutPS2** [comment]
This issue would be resolved in OpenGL, but the game has a half bottom issue (https://github.com/PCSX2/pcsx2/issues/1339) so it's only half-resolved.

**Comment by MrCK1** [comment]
To clarify the previous comment, this is just another side effect of the already present half-bottom issue in this game. All HW renderers are still affected.
