### ISSUE TITLE
PCSX2 application crash on Rogue Galaxy when charge attack is used by Steve

### ISSUE THREAD

**Issue by hellbringer616** [PCSX2/pcsx2#2110]
***PCSX2 version:***
1.5.0-dev-2133-g45ac69a

- **Notes**:
No notes or logs, as Emu crashes and can't generate any

***PCSX2 options:***
Defaults, no speed hacks

***Plugins used:***
Any combination of plugins cause this issue
GSDX settings seem to have no effect.
Hardware/Software, DX9/11/OGL
Native/scaled
etc etc

***Description of the issue:***
When performing a Power attack as Steve PCSX2 crashes.

***How to reproduce the issue:***
While playing as Steve(once you load the game push L3 and select Steve), enter a battle and hold X to charge your power attack and release, PCSX2 will crash.

Memory card file here: https://drive.google.com/file/d/0B1_PuJEKWxWlR1Bnek00MzI4Mms/view?usp=sharing

***Last known version to work:***
None, PCSX2 wiki has had this issue listed since i first tried to play in PCSX2 1.2/1.3
https://wiki.pcsx2.net/Rogue_Galaxy

***PC specifications:***
CPU: Core i5-4690K @4.5ghz
GPU: GTX 1080
OS: Windows 10 x64

**Comment by MrCK1** [comment]
@hellbringer616 Can you post an emulog with the crash?

**Comment by hellbringer616** [comment]
One emulog coming right up
https://drive.google.com/file/d/0B1_PuJEKWxWlQ3VsV09NNFc2UHM/view?usp=sharing

**Comment by atomic83GitHub** [comment]
Can you try to set the EE/IOP and VUs to interpreter when the charge attack is used?

**Comment by hellbringer616** [comment]
At the crazy fast speed of 6.25fps i pushed through and entered a battle:
I performed a charge attack and didn't hit anything without a crash. However when i performed a charge attack and hit the enemy it crashed.

Likely unrelated: The controlled character constantly twitches back and both and runs into invisible walls when using the interpreters.

**Comment by Ryudo300** [comment]
I just tested this, and was able to perform a Charge Attack just fine on enemies. 

It was tested on v1.5.0 dev-2207.

![pcsx2_2017-11-03_21-53-10](https://user-images.githubusercontent.com/10039778/32395480-958d2e28-c0e1-11e7-839a-afb011aafbe9.png)

**Comment by MrCK1** [comment]
Lilypad settings would be nice

**Comment by hellbringer616** [comment]
Will post my Lilypad settings when i get home, i can tell you they are default to whatever PCSX2 has them set to.

@Ryudo300: I will update and let you know my findings.
Are you using PCSX2 default settings when testing? I want to make sure my tests are consistent.

**Comment by Ryudo300** [comment]
Type K requires the shield to be broken first before you can damage it. I did multiple fights with Steve too, no crash occurred. 

PCSX2 Settings:

**Speedhacks:** 
- EE Cyclerate: 0
- VU Cycle Stealing: 0
- mVU Flag: Enabled
- MTVU: Enabled

**GSdx:**
- Renderer: Direct3D11 (Hardware)
- Internal Resolution: 4x Native
- Anisotropic Filtering: 16x
- CRC Hack Level: Automatic
- Mipmapping: Off

**LilyPad:**
![pcsx2_2017-11-03_22-56-37](https://user-images.githubusercontent.com/10039778/32397470-42946840-c0ea-11e7-8abe-4097b561e4b4.png)

![pcsx2_2017-11-03_22-55-46](https://user-images.githubusercontent.com/10039778/32397445-2db96c36-c0ea-11e7-99d8-358f8d3a0daf.png)

**Comment by hellbringer616** [comment]
After testing, Issue happens in OpenGL hardware mode only.
DX11 works fine

**Comment by lightningterror** [comment]
What if you set CRC hacklevel to full while running OpenGL ?

**Comment by hellbringer616** [comment]
When setting the CRC to full it crashes when hitting an enemy requiring break.

**Comment by lightningterror** [comment]
Are you using custom resolution by any chance ?

**Comment by hellbringer616** [comment]
I am, tested at 5x native and the game does not crash!

Any idea why it would crash on custom resolution? I use CR because when taking screenshots its the only way to keep proper aspect ratio when using widescreen hacks. screenshots come out smooshed otherwise.

**Comment by MrCK1** [comment]
Can you check for VRAM spikes in Task Manager/Process Hacker before the crash when using custom resolution?

**Comment by lightningterror** [comment]
Please try this PR and see if it crashes.
https://ci.appveyor.com/api/buildjobs/tjqw0wv1ehxbcj1n/artifacts/pcsx2-v1.5.0-dev-2216-g3b4e719fb-3425-vs2015-Win32-AppVeyor.7z

**Comment by hellbringer616** [comment]
PR did the trick! tested it multiple times, no crash on custom resolution.

closing the issue.

**Comment by lightningterror** [comment]
#2122 well it's not merged yet, will be Soon™.

**Comment by ssakash** [comment]
I'd appreciate if you could test it again :P

**Comment by hellbringer616** [comment]
I've never compiled anything before, if you post a test build i'd be happy to

**Comment by FlatOutPS2** [comment]
> I've never compiled anything before, if you post a test build i'd be happy to

Pull Requests always come with a Windows build(artifact):
https://ci.appveyor.com/api/buildjobs/se0t56qv4tk587xu/artifacts/pcsx2-v1.5.0-dev-2283-g32c12b236-3742-vs2015-Win32-AppVeyor.7z

**Comment by hellbringer616** [comment]
@FlatOutPS2 
I did not know that, i'm new to this whole git thing, I'll give it a go tonight after work/errands :)
@ssakash 
Any other games you'd like tested? Rogue Galaxy is the only game i had crashing issues on; though I own quite the extensive RPG and Action libraries ('m pushing about 100 games i think) so if you happen to know of others, i'd be happy to give them a whirl!

**Comment by lightningterror** [comment]
Persona 4, MGS3, GT4, Silent Hill 2 & 3.
Check #1972 for more info.

**Comment by FlatOutPS2** [comment]
@hellbringer616 Did you manage to test Rogue Galaxy with the PR build yet?

**Comment by hellbringer616** [comment]
@FlatOutPS2
Im sorry I have not; personal issues and commitments are keeping me from any game or testing time.

I could throw in the above build and load it as I'm still in that area; though I feel a proper test is what should be done.

**Comment by FlatOutPS2** [comment]
@hellbringer616 
A proper test is best, but if no one else can test this, a short test is better than nothing for now. ;)

**Comment by lightningterror** [comment]
@bositman and maybe @Ryudo300 have the game so they can also test.

**Comment by hellbringer616** [comment]
Okay! Sorry guys life got super busy for a bit; everything is back to normal (for now)
so far everything is working great, i cannot get the game to crash when using custom resolution

**Comment by FlatOutPS2** [comment]
OK, thanks for testing :+1: . If you're satisfied with the testing and sure enough that it won't crash anymore, please mention it here: https://github.com/PCSX2/pcsx2/pull/2122
