### ISSUE TITLE
The Godfather: Post processing effect remains on screen

### ISSUE THREAD

**Issue by Gfurst** [PCSX2/pcsx2#2111]
***PCSX2 version:***
`v1.5.0-dev (git from aur)`

***PCSX2 options:***
GSdx opengl on hardware mode, blend bff if that matters, and general high quality settings

***Description of the issue:***
Some games where there seems to be an initial post process effect (I'm at a fail for words to describe these) they seem to remain on screen even when supposed to, so far I've seen this happen with The Godfather and GTA San Andreas.

On the Godfather, even on the starting scene, where the title is supposed to appear, the black strip just remains there throughout the scene.   
![screenshot_20171031_114536](https://user-images.githubusercontent.com/12454141/32227597-fa9b7088-be32-11e7-933b-824835d3c105.jpeg)

On GTA there is some sort of raze post fx, which I can only assume goes away shortly after entering the main world map, but it remains on screen too.   
![screenshot_20171031_115514](https://user-images.githubusercontent.com/12454141/32227622-0bfb4376-be33-11e7-9c6a-df139e47d1cd.jpeg)

***How to reproduce the issue:***
Seems that the only parameter for this issue is having GSdx on hardware mode, switching seems to fix them, but on the cost of quality/speed.

***PC specifications:***
Archlinux - AMD FX6300 - Radeon R7 260X - 16GB ram

**Comment by MrCK1** [comment]
Switch to the OpenGL renderer.

**Comment by Gfurst** [comment]
it already **is** the opengl renderer, in case it wasn't clear....

**Comment by MrCK1** [comment]
Oh OK. Enabling the Auto Flush hack should fix San Andreas. Not sure about the Godfather.

**Comment by lightningterror** [comment]
Can you tell me your CRC id? I'd like to check something.

**Comment by Gfurst** [comment]
> Can you tell me your CRC id for San Andreas?

how do you check that?

**Comment by MrCK1** [comment]
It's in the top of the console window.

**Comment by Gfurst** [comment]
oh sorry, forgot to check and will only be back for a few days

**Comment by Gfurst** [comment]
![screenshot_20171108_122415](https://user-images.githubusercontent.com/12454141/32554158-1315e85c-c480-11e7-9746-e1e0ddb4c903.jpeg)

sorry for the lateness, I didn't find what you meant with CRC so here is the shot with the console window

**Comment by lightningterror** [comment]
Misc > Check show console

![image](https://user-images.githubusercontent.com/18107717/32554311-aadb5b40-c499-11e7-8411-e22111ab6a8b.png)

**Comment by lightningterror** [comment]
@Gfurst any update?

**Comment by Gfurst** [comment]
sorry, really didn't see it
`GSdx Lookup CRC:2C6BE434`

**Comment by lightningterror** [comment]
Can you upload a GS dump from the issue ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by FlatOutPS2** [comment]
> Can you upload a GS dump from the issue(s) ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

@Gfurst Can you upload a GS dump of only The Godfather.

GTA: San Andreas is fixed with auto flush hack, despite a minor offset issue (can be improved with TC offset).

**Comment by Gfurst** [comment]
Oh, sorry guys, I don't even have that game anymore.

**Comment by lightningterror** [comment]
[The Godfather.gs.zip](https://github.com/PCSX2/pcsx2/files/1782172/The.Godfather.gs.zip)

**Comment by mehul-dev** [comment]
Hello all i fixed this issue by enabling HW hack and setting **Skipdraw Range** to 1

![image](https://user-images.githubusercontent.com/45088837/62885961-bfd93b80-bd57-11e9-894d-48b07b5ae7a4.png)

Gsdx settings are configured like this

![image](https://user-images.githubusercontent.com/45088837/62886109-1e061e80-bd58-11e9-8f89-6fa870198e9e.png)

It fixes problem in Godfather not sure about GTA San Andreas.

**Comment by gregory38** [comment]
Not fix but hide/remove the post processing effect. We know what happens, it is a case where we fail to emulate some insanities.

**Comment by mehul-dev** [comment]
Oh okay seems to be a hack as of now but game is playable and smooth with above configuration didn't face any issue

**Comment by Gfurst** [comment]
Hello, do you want another GS dump? Or anything else I can do here?
The above workaround at least makes it playable, though there also seems to be a stutter every few seconds.

**Comment by tadanokojin** [comment]
Nope we are good. We know why it is broken.

**Comment by Gfurst** [comment]
Alright, just no way to fix it so far?

**Comment by tadanokojin** [comment]
closing in favor of #3875
