### ISSUE TITLE
More of a request than an issue.

### ISSUE THREAD

**Issue by P8M3** [PCSX2/pcsx2#2112]
No idea where I should post this. I would like to request for future releases an option to switch to 16:9 aspect ratio when an FMV plays. 

Thanks.

**Comment by atomic83GitHub** [comment]
You can already put the emulator's windows to 16/9..

**Comment by lightningterror** [comment]
> You can already put the emulator's windows to 16/9.

Indeed. It does the same function. The reason why 4:3 FMV switch exists is because it can fix issues on FMV playback. 

I'll close this.

**Comment by P8M3** [comment]
The problem is I and others also play in 21:9 but would like to retain the correct aspect ratio for fmv's.

**Comment by MrCK1** [comment]
With a few rare exceptions, most FMVs are 4:3 natively. You can just switch it manually

**Comment by P8M3** [comment]
Correct but not all FMV's. Also switching from 21:9 gameplay to 4:3 fmv seems a bit too much at times. 4:3 stretched to 16:9 is an acceptable tradeoff imo. Really it comes down to personal preference but it would be nice to have a 16:9 fmv feature for the games that do have 16:9 fmv's and for those that can't bare 4:3 on such wide monitors.
