### ISSUE TITLE
Ratchet and Clank 3 : Read error.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2113]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, speedhacks disabled except MTVU

***Plugins used:***
All default

***Description of the issue:***
Ratchet and Clank 3 always have a read error in the 5th Qwark video comic level, it cause the music to stop and a retry impossible.

***Note:***
Set the EEcyclerate to -3 don't solve the issue.

***How to reproduce the issue:***
Load PCSX2 and Ratchet and Clank 3, go to the 5th Qwark video comic level and you will see the error aleatory in it.

***Blockdump:***
https://drive.google.com/file/d/0B0Ph0W1NYxIVQk9pT0xpTGMyTm8/view?usp=sharing

***Last known version to work:***
Not a regression, 1.2.1 and 1.4 are also affected.

***PC specifications:***
AMD fx-8350 GTX 780ti Windows 10 64 Bit

**Comment by MrCK1** [comment]
Savestate please, I'll look tonight.

**Comment by atomic83GitHub** [comment]
Here it is, remember that the read error is random.
https://drive.google.com/file/d/0B0Ph0W1NYxIVbXdpZi1mMlREOUk/view?usp=sharing

**Comment by MrCK1** [comment]
OK, also what kind of read error? Is it something like CDVD read error printed in the console?

**Comment by atomic83GitHub** [comment]
Yes, here is the console when the error happen:
![capture](https://user-images.githubusercontent.com/26351275/32292838-9b0da144-bf41-11e7-9fcd-86c639cb7432.PNG)

**Comment by atomic83GitHub** [comment]
I also have a another game wich have this type of read error, would you want some info on it?

**Comment by MrCK1** [comment]
Are you using a disk or ISO? This error is caused by a disk being so scratched that the sector can't be read anymore, or you have a bad rip.

**Comment by atomic83GitHub** [comment]
It happen in the iso and the disc (wich is scratched).

**Comment by MrCK1** [comment]
Yeah, so that's your problem. The best you can do is buy another disk and/or re-rip the ISO and verify that the data is matching 100%>/.
.

**Comment by atomic83GitHub** [comment]
Ok :) , I will test a another disc and will reopen it if this happen.

**Comment by MrCK1** [comment]
If it happens on other disks, it's the same problem as I mentioned here. It has nothing to do with emilation on our end.;)

**Comment by lightningterror** [comment]
I recommend ripping the disc using slower read speed. It can help.

**Comment by atomic83GitHub** [comment]
This issue is not because of cratched dvd, that PR solve it: https://github.com/PCSX2/pcsx2/pull/3051
