### ISSUE TITLE
broken effects in Need for Speed Most Wanted

### ISSUE THREAD

**Issue by LBPPlayer7** [PCSX2/pcsx2#2115]
The fog and bloom effects are broken in Most Wanted when using the hardware renderer
This issue seems to have been present from the first version of GSdx up to the version in the latest development build. The fog just becomes two transparent planes that are a certain distance away from the camera (around the position of the car in close camera mode) and the bloom gets ridiculously bright in tunnels.

**Comment by MrCK1** [comment]
Please format your bug report according to the original template. Thanks.

**Comment by LBPPlayer7** [comment]
ok

**Comment by MrCK1** [comment]
@LBPPlayer7 Are you going to update your issue? If you don't respond soon, I'm going to close it since there's already a similar one opened.

**Comment by GrandGTA** [comment]
just want to ask, does anybody have a link for the NFSMW Demo??? i need it...
