### ISSUE TITLE
Using ePSXe Plugins in pcsx2?

### ISSUE THREAD

**Issue by AraHaan** [PCSX2/pcsx2#2121]
***PCSX2 version:*** latest

***PCSX2 options:*** Not Configured

***Plugins used:*** default

***Description of the issue:*** I would like to know if PCSX2 can support ePSXe plugins that are open/closed sourced. I know awesome ones that work (some of them opengl) on PSX games.

***How to reproduce the issue:*** None

***Last known version to work:*** Unknown

***PC specifications:*** CPU: Core 2 Duo P8800 (2.66 Ghz GPU: Intel GM 45 OS: Windows 7 SP1 x64 Build 7601

**Comment by willkuer** [comment]
What do you mean? You want to use let's say a pay SPU plugin to emulate the ps2's SPU2 (I.e. 2x SPU)? The chips and architectures are different.

**Comment by AraHaan** [comment]
I was refering to like using any of the PSX plugins in pcsx2 for only PSX games.

**Comment by willkuer** [comment]
Pcsx2 is a playstation2 emulator, it can only emulate the ps2. The ps2 has a psx backward compatibility mode. This mode however exists in the real console and uses the real ps2 components (or a part of it). To use the psx backward compatibility mode in pcsx2 you still need to emulate all components of the ps2. There are some ps2 versions that used the real psx GS chip IIRC (hw emulation) while others used the IOP (?) as GS chip. So in the former case one might be able to reuse a large part of a psx GS plugin as core component of a ps2 plugin but you can not just bind a psx plugin.

**Comment by AraHaan** [comment]
Ah, I see.

**Comment by ssakash** [comment]
>  I would like to know if PCSX2 can support ePSXe plugins that are open/closed sourced.

PCSX2 supports any modules which are compatible with all the plugin APIs present in the core. So if you want any other plugins to work on PCSX2, the work needs to be done on the plugin, not on PCSX2.

Though the thought of using PSX plugins for improving the PSX backward compatibility mode in PCSX2 sounds like an illogical idea to me.
