### ISSUE TITLE
LilyPad config dialog won't open

### ISSUE THREAD

**Issue by majewsky** [PCSX2/pcsx2#2126]
***PCSX2 version:*** v1.5.0-dev-2217-gb31c23b37b on Linux

***Plugins used:*** LilyPad 0.12.1

***Description of the issue:***
I cannot access the LilyPad settings. When I select "Plugin Settings" from the Config menu, or "Configure" in the plugin selector, no dialog appears. The only thing that happens is that, when I try it for the first time, a bunch of diagnostics is printed into the log window about which devices it has detected (see below).

***Last known version to work:*** 
No idea. My distribution has 1.4.0, where it doesn't work either. I also tried to compile the v1.4.0 tag in order to start a bisection, but it's too old; I cannot get it to compile with my current set of system libraries.

***System information:***

```
$ uname -a
Linux arcturus 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
$ pacman -Q $(pacman -Qi pcsx2 | grep 'Depends On' | cut -d: -f2) # versions of dependencies
lib32-glew 2.1.0-1
lib32-libaio 0.3.110-1
lib32-libcanberra 0.30-4
lib32-libjpeg-turbo 1.5.2-1
lib32-nvidia-cg-toolkit 3.1-5
lib32-portaudio 190600_20161030-1
lib32-sdl2 2.0.7-1
lib32-soundtouch 2.0.0-1
lib32-wxgtk 3.0.3-2
```

The gamepad I'm trying to use is a Steam Controller, using the gamepad emulation provided by https://github.com/ynsta/steamcontroller. My desktop is KDE Plasma 5.11.3 running on Xorg 1.19.5 with the only input driver being xf86-input-libinput 0.26.0 using libinput 1.9.1.

The log shows the following when I first try to open the LilyPad config dialog:

```
Found input device => bustype:3, vendor:28de, product:1142, version:1
	Name:Steam Controller Keyboard
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:3, vendor:46d, product:c01d, version:110
	Name:Logitech USB-PS/2 Optical Mouse
Add relative nb 0
Add relative nb 1
Add relative nb 8
New device created. Found axe:0, buttons:8, m_rel:3

Found input device => bustype:3, vendor:4d9, product:132, version:111
	Name:USB Keyboard
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:3, vendor:4d9, product:132, version:111
	Name:USB Keyboard
Add relative nb 0
Add relative nb 1
Add relative nb 8
New device created. Found axe:0, buttons:3, m_rel:3

Found input device => bustype:19, vendor:0, product:1, version:0
	Name:Power Button
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:19, vendor:0, product:1, version:0
	Name:Power Button
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:10, vendor:1f, product:1, version:100
	Name:PC Speaker
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:19, vendor:0, product:0, version:0
	Name:Eee PC WMI hotkeys
New device created. Found axe:0, buttons:7, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=3
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=7
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=8
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=9
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=10
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA ATI HDMI HDMI/DP,pcm=11
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA Intel PCH Front Mic
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA Intel PCH Rear Mic
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA Intel PCH Line
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA Intel PCH Line Out
New device created. Found axe:0, buttons:0, m_rel:0

Found input device => bustype:0, vendor:0, product:0, version:0
	Name:HDA Intel PCH Front Headphone
New device created. Found axe:0, buttons:0, m_rel:0
```

This only appeared after I added my user to the `input` group in order to gain access to `/dev/input/event*`, after seeing in `strace` that LilyPad tried to open these upon initialization.

**Comment by willkuer** [comment]
Lilypad was written for windows and to the present day doesn't have a configuration dialog (I.e. You need to adjust the settings manually in the ini). With other words lilypad on Linux is rather for debugging purposes. Can you just use the other plugin that is shipped?

**Comment by yxmline** [comment]
linux use onepad

**Comment by Azelphur** [comment]
Hope it's ok to reopen this - but using OnePad isn't really a good alternative, it lacks features that Lillypad has, such as multitap, preventing Linux users from playing games with more than two players.

**Comment by MrCK1** [comment]
It would probably be better to make a new report requesting those features in Lilypad.

**Comment by Azelphur** [comment]
@MrCK1 should I create a report requesting that the lillypad GUI be fixed in Linux, or a report requesting that onepad be upgraded to support multitap?
