### ISSUE TITLE
Logitech F310 gamepad stop working in games

### ISSUE THREAD

**Issue by isshininu** [PCSX2/pcsx2#2130]
***PCSX2 version:***
latest git build
- **Notes**:

***Plugins used:***
Lilypad / xpad2 plugins with default settings were used.

***Last known version to work:***
Was tested long before, probably 1.4.0 portable.

***PC specifications:***
Nvidia GeForce840M, Intel HD Graphics 4600 on i-4700M, Windows 10 FCU 64 bit.

![_2017_11_15_20_04_01_61](https://user-images.githubusercontent.com/6324523/32846258-33abf168-ca40-11e7-8eb0-6e16f25e554e.png)
![_2017_11_15_20_04_15_125](https://user-images.githubusercontent.com/6324523/32846259-33d2147e-ca40-11e7-952a-1fbc9ea48bf4.png)
![_2017_11_15_20_04_22_16](https://user-images.githubusercontent.com/6324523/32846260-33f6b7a2-ca40-11e7-8408-57b57696a8e1.png)

**Comment by MrCK1** [comment]
Do you have SCPToolkit installed?

**Comment by isshininu** [comment]
> Do you have SCPToolkit installed?

No.

**Comment by MrCK1** [comment]
Can you disable the 2nd controller and see if that works?

**Comment by isshininu** [comment]
>Can you disable the 2nd controller and see if that works?

Second controller is a device called "Insyde Airplane Hid Mini-Driver" integrated into the motherboard.

Aw, shit. I can't disable it in FCU.

**Comment by MrCK1** [comment]
No, I meant disable it in Lilypad.

**Comment by isshininu** [comment]
How can i do that?

**Comment by MrCK1** [comment]
Right in the settings, where it says 'Pad 2: Dualshock 2' - change that to Disabled.

**Comment by isshininu** [comment]
Sorry pal, it didn't worked too.

I guess Fall Creator's Update might have broke this. But we need a confirmation.

![_2017_11_15_20_33_35_469](https://user-images.githubusercontent.com/6324523/32847870-91cc7e6c-ca44-11e7-8a36-3c1202eb8779.png)

**Comment by MrCK1** [comment]
Pad 1 needs to be Dualshock 2 -to accept your input did you try that?

**Comment by isshininu** [comment]
>  Pad 1 needs to be Dualshock 2 -to accept your input did you try that?

just tried that too. Looks like PCSX2 doesn't see that xinput-gamepad at all. None of the options (xinput/directinput) works now.

**Comment by MrCK1** [comment]
Did you try rebinding your controls? Sometimes the XInput port can change.

**Comment by isshininu** [comment]
>Did you try rebinding your controls? Sometimes the XInput port can change.

Well. Rebinding works.
Controls added in Pad 1 as **Xinput Pad 1**
But when i disable Pad 1 (that is definitely a keyboard), gamepad doesn't start working in PCSX2.

![_2017_11_15_21_33_03_276](https://user-images.githubusercontent.com/6324523/32850848-d0811926-ca4c-11e7-9e3c-8ec330f9984d.png)

![_2017_11_15_21_33_14_776](https://user-images.githubusercontent.com/6324523/32850854-d35439b2-ca4c-11e7-8744-88852339f32e.png)

**Comment by MrCK1** [comment]
I think you're a bit confused. Pad 1 *is* your controller - you can see this because the controls in the Pad 1 tab are bound to XInput Pad 1; which is your controller.

**Comment by isshininu** [comment]
Controls in Pad 1 binded to Xinput 0.
