### ISSUE TITLE
Dynasty Warriors 3 Xtreme Legends: Save corruption

### ISSUE THREAD

**Issue by hggeren** [PCSX2/pcsx2#2135]
***PCSX2 version:***
Latest dev build 1.5.0

***PCSX2 options:***
Everything default, preset set to safest.

***Plugins used:***
Custom resolution set to 1920x1080 using OpenGL Hardware Rendering. Everything else is default

***Description of the issue:***
On initial startup of Dynasty Warriors 3 Xtreme Legends the game tells me my savedata is corrupted and failed to load. 
![initial message](https://user-images.githubusercontent.com/10597256/32922803-34b7f1c6-cb88-11e7-9e9a-f449bb7a9a8e.png)
I ignore this message and go into the main menu to load the original data from the Dynasty Warriors 3 disc (through using a custom iso with both games on it to work around disc swap not working). Once the original data is loaded, I can go into options and load the save data manually.
![works after loading original data then manually reloading save](https://user-images.githubusercontent.com/10597256/32922820-3febfff6-cb88-11e7-9263-e3d0d917d942.png)
Sometimes it still says the data is corrupted, but most of the time it loads successfully. 
![sometimes it fails even after loading original](https://user-images.githubusercontent.com/10597256/32922823-47c975e6-cb88-11e7-941f-cc6ba20a6e32.png)
If it says the data is corrupted, just retry a couple of times and it will eventually load. I also noticed that if I at some point do a save mid-stage, the save file is forever corrupt with no way to load it, even if I finish that stage without quitting the game. I think the anti-cheat measures that Koei added in DW3XL expansion are for some reason triggered by how PCSX2 handles memory card saving.

***How to reproduce the issue:***
Boot up DW3XL, load original data and make a savefile (either manually through options menu or by playing any stage, editing bodyguards etc).
Reboot the game and you should see "save data corrupted, load failed message" on initial load. 
Go into main menu, load original DW3 data
Go to options, load game manually. Loading now works for some reason.

***Last known version to work:***
Works perfectly in 1.2.1, no save corruption issues at all. Game loads save data on initial startup without requiring original data to be loaded and I can even save mid-stage without corrupting the save permanently.

***PC specifications:***
OS: Win 10 Home x64
CPU: i7 7700k at stock
GPU: Asus Rog Strix 1080Ti at 2GHz core, 12GHz memory
RAM: 16GB Corsair LPX at 2800MHz CL14

**Comment by MrCK1** [comment]
What type of memory card are you using?

**Comment by hggeren** [comment]
@MrCK1 the default 8MiB ones that were recommended for compatibility: 
![memory card settings](https://user-images.githubusercontent.com/10597256/32924736-33a55792-cb92-11e7-9b7d-b21f897a0dae.png)
The problem is also present on 1.4.0

**Comment by hggeren** [comment]
I'm assuming something must have changed in the way PCSX2 loads the save files. I can easily load any DW3XL save file in 1.2.1, even the ones that were permanently corrupted in 1.5.0 due to mid-stage saving. The issue persists when I swapped to using 1.5.0 plugins with the 1.2.1 exe as well.

**Comment by lightningterror** [comment]
Can you track down which build introduced the regression ?

[1.3.1.txt](https://github.com/PCSX2/pcsx2/files/2258206/1.3.1.txt)

**Comment by Asgezar** [comment]
The last working build is 1.3.0.5899 (svn). It was taken from here https://buildbot.orphis.net/pcsx2svn/index.php?m=fulllist

**Comment by lightningterror** [comment]
5900 doesn't work ?

**Comment by Evil-Moo** [comment]
I ran into this issue myself and decided to have a look around the code (mostly because I was annoyed about losing progress, having accidentally saved in the middle of a battle).

As far as I can tell the issue is in Counters.cpp in the function `vSyncInfoCalc()`, though I'm not sure how changing V-Sync values would have any effect on loading saves...

Changing the line
`u64 Blank = HalfFrame / 2;`
back to
`u64 Blank = (Frame / scansPerFrame) * 22;`
appears to completely fix the save corruption issue in the latest 1.5.0 codebase (my save containing a mid-battle save now loads, when it was seemingly permanently 'corrupted' before).

From what I've been seeing, this code was changed to stop another game (Legendz Gekitou! Saga Battle) running extremely poorly, so this obviously isn't an ideal fix. Hopefully someone who actually has a better understanding of what they're looking at can figure out a better fix.

**Comment by willkuer** [comment]
Several people reported anti cheat measures for this game. In that sense this vsync dependency might not be so unexpectedly. Could still be helpful to double check whether this really fixes your issue.

**Comment by MrCK1** [comment]
@Evil-Moo Can you test the artifact from #2275 and see if it affects the issue?

**Comment by Evil-Moo** [comment]
The 'Alternative vsync timing' branch appears to fix this issue for me (and just in case, I compared it to the commit immediately prior to it and that one still has the corruption problem).

**Comment by Tanapa1** [comment]
Can anybody tell me how to load original in this game please.
