### ISSUE TITLE
[VPU/VIF] Max Payne : crash issue.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2141]
***PCSX2 version:***
Ladt 1.5 dev

***PCSX2 options:***
All default, speedhacks disabled, this game is not compatible with MTVU (it cause more crashs)

***Plugins used:***
All default

***Description of the issue:***
The game Max Payne always crash at the same point with this error.

![capture](https://user-images.githubusercontent.com/26351275/33090347-f5fa50cc-cef3-11e7-931d-c38df02bd5ee.PNG)

***How to reproduce the issue:***
Load PCSX2 and Max Payne, go to the "Clean up duty" level and enter in the folowing room with 2 ennemies.

***Not a regression***

***PC specifications:***
AMD fx8350 gtx 780Ti  Windows 10 64 Bit

***Game DB workaround should be removed because disabling MTVU do the same effect.***

***Play!***
It seems that the Play! emulator have found 2 fix for this issue, here are the links:
https://github.com/jpd002/Play-/commit/59e49c80ff2f18187eba273df8a0336e8db46923
https://github.com/jpd002/Play-/commit/d95b8359760c37229827037b2761af0423e75170

**Comment by MrCK1** [comment]
@prafullpcsx2 Didn't you make a patch for this game, or was that unrelated?

**Comment by prafullpcsx2** [comment]
@MrCK1 No, I don't remember making any patches for this game.

**Comment by atomic83GitHub** [comment]
Here is a save with all levels unlock:
https://drive.google.com/file/d/1Iid4xlbbRD9_Yt3sDnFpcJL7mSruP-Fq/view?usp=sharing

**Comment by prafullpcsx2** [comment]
I have the US version of the game and this save seems to be for PAL version?

**Comment by atomic83GitHub** [comment]
Yes, it is.

**Comment by prafullpcsx2** [comment]
I managed to find the savegame from gamefaqs. The crash seems random though and seems to be happening only when ee cycle rate is set to zero. Can you recheck and confirm that crash happens even with eecycle rate -1 or -2 or -3?

**Comment by atomic83GitHub** [comment]
The game seems fine when using -1 or lower.

**Comment by MrCK1** [comment]
What if you use EE timing hack instead?

**Comment by atomic83GitHub** [comment]
The EETimingHack can sometimes help, sometimes not.
As a side note disabling MTVU cause less crash.

**Comment by MrCK1** [comment]
@atomic83GitHub What do you mean that disabling MTVU causes less crashing? Doesn't -1 or lower fix the issue completely, or does the game crash in other places?

**Comment by atomic83GitHub** [comment]
Disabling MTVU with EEcyclerate to 0 partialy solve the issue but setting the EEcyclerate to -1 seems to completly solve it.

**Comment by zGodz** [comment]
same issue

**Comment by atomic83GitHub** [comment]
I finaly found the fix, this game need the eeclampmode to full to avoid random hanging.

@lightningterror , can you create a Pull request to remove vu round/clamp and ee round mode?Strangely I can't see the changes in my repo.

I am going to close it.

**Comment by lightningterror** [comment]
Nop, no PRs from me for a month. Christmas/New years vacation so I'll be reviewing only.

**Comment by MrCK1** [comment]
I'll check later, work is closed for me due to snow ;)
