### ISSUE TITLE
[bug][GSdx:OpenGL] Xenosaga 1 - OpenGL Hardware mode slower than Software mode

### ISSUE THREAD

**Issue by frozenMustelid** [PCSX2/pcsx2#2144]
***PCSX2 version:***
1.5.0-0 (whatever the 2017-11-20 version in the PPA is)

***PCSX2 options:***
I had widescreen on when I noticed the bug, but testing with it turned it off had almost no performance improvement

***Plugins used:***
GSdx (GCC 5.4.0 AVX2/AVX2) 1.1.0 [libGSdx-AVX2]
OnePAD 0 1.3.0 [libonepad-legacy]
SPU2-X 2.0.0 [libspu2x-2.0.0]
CDVDnull Driver 0 0.6.0 [libCDVDnull]
USBnull Driver 0 0.7.0 [libUSBnull-0.7.0]
FWnull Driver 0 0.7.0 [libFWnull-0.7.0]
DEV9null Driver 0 0.5.0 [libdev9null-0.5.0]

GSdx settings - default settings

***Description of the issue:***
When playing Xenosaga Episode 1, selecting OpenGL Hardware mode results in inferior performance to OpenGL Software mode. 

***How to reproduce the issue:***
Set the render mode to OpenGL (Hardware). Open Xenosaga 1 - Der Wille Zur Macht (I used the USA version). Skip the cutscenes, which all play at normal speed until the game renders a 3D model over it. Marvel at the poor performance. I was getting about 50%-80% speed. Change the render mode to OpenGL (Software). Close the emulator and reopen. Play Xenosaga. Enjoy 100% speed.

Other games may do this too. I also tested a small amount of Persona 3 FES and noticed no difference. That said, framelimit off on P3 gives 250-280% speed in SW, while frame limit off on Xenosaga SW give 130-150% speed, so it may just be that P3 is light enough that my computer runs it at full speed anyways. P3 in HW render gives 240-260%, so maybe it's not just Xenosaga 1.

Links to GS dumps:
[xenosaga hardware.tar.gz](https://github.com/PCSX2/pcsx2/files/1500264/xenosaga.hardware.tar.gz)
https://www.mediafire.com/file/im5rc9q4r50indr/xenosaga%20software.tar.gz
https://www.mediafire.com/file/7e669ib7b786y34/xenosaga%20software%20framelimit%20off.tar.gz

***Last known version to work:***
???

***PC specifications:***
CPU: Intel Core i5 (Skylake)
GPU: AMD RX 460 (proprietary drivers)
OS: Linux Mint 18.2

**Comment by lightningterror** [comment]
The propriety drivers are known to be bad, however the opensource drivers for OpenGL are the best. They are also better than what amd offers on Windows.

**Comment by frozenMustelid** [comment]
That doesn't gel with my experiences with this particular card. IME, proprietary offers modest (but distinctly noticeable and measurable) improvements over the open source driver when rendering with OpenGL, and only the proprietary driver lets me use Vulkan. In my case, OpenGL vs. Vulkan is the difference between full-speed GC games in Dolphin on native resolution and full speed 1080p on most GC games in Dolphin. Some GC games simply don't run at full speed with the OS drivers.

I use Dolphin enough that switching back to the OS drivers is not an option.

**Comment by mirh** [comment]
Last time I checked vulkan was a thing even for open source drivers. 
Then btw, while you are at it, could you check if AMDGPU-PRO is equally buggy as driver on windows?

`g++ whatever.cpp -o test -lGL - lglut -lGLEW`
Where whatever.cpp is [this](http://pastebin.com/CCC63BWr) (make sure to install freeglut and glew)

**Comment by frozenMustelid** [comment]
Sorry about the late response. The code does compile and run, but it shows a yellow background and that's all. Here's the terminal output:

Supported Opengl version: 3.1.13491 Compatibility Profile/Debug Context 17.30.0
Frag0 index 0
Frag1 index 1

I tried pressing a few keys and clicking and dragging the empty yellow space in the window, but nothing changed in the terminal or the window.

**Comment by mirh** [comment]
> but it shows a yellow background and that's all

Fine, that was all that was needed, thank you.

**Comment by DIKH3D** [comment]
![image](https://user-images.githubusercontent.com/34287698/33634908-c2b8a568-da0d-11e7-9fe7-ac7aee9a7e44.png)

**Comment by gregory38** [comment]
Disable accurate blending. It should improve perf if the driver doesn't crash in a kernel panic.

Some GS effects are much easier/faster to emulate on the CPU rather than on the GPU. Because we need to bypass the fast hardware unit of the GPU. Instead the effect is emulated on the slow shader.

**Comment by mirh** [comment]
Newer AMDGPU-PRO driver came out. 
AFAIU it should even allow you to switch to open GL driver. 
Could you give a check to the performance of that?

**Comment by frozenMustelid** [comment]
I may have to wait a few days to give you an update on the new amdgpu-pro driver. I downloaded the tarball and tried to install it and... error. After looking at the message, I think somebody at AMD forgot what the dkms module was called, and had the script try to install a nonexistent dependency. A combination of AMD derping and apt derping caused what should be a simple uninstall new+reinstall old took awhile for me to figure out.

I'm sure somebody else will notice and politely inform AMD that just because a guy had his pecker bitten off by a penguin doesn't mean he's a good choice for a Linux developer, but just in case they don't, I'll send them a bug report too.

**Comment by mirh** [comment]
Hi again. 
Did you found the time to try 17.50?
I just found out they have a dedicated tracker on freedesktop (for some reason) and I wanted to report them there too.

**Comment by frozenMustelid** [comment]
Between various RL things going on and trying to manage my own software project, I haven't yet had time to mess around with AMDGPU-PRO to see if I can't find some configuration that won't require me to uninstall it and reinstall the old version just to get my desktop environment to function, not to mention all the programs that don't run because the DE is screwy.

The worst part is, AMD's website is so messed up I can't even submit a bug report. It just keeps trying to load it, but all I ever get is a blank page.

**Comment by lightningterror** [comment]
I'll go ahead and close this, people should be using mesa drivers.
