### ISSUE TITLE
Remove CRC hacks for the Simpsons game.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2146]
***Why?***
They are not needed anymore and cause a graphical glitch with black lines in the full level.

![capture](https://user-images.githubusercontent.com/26351275/33233236-d9099280-d212-11e7-971b-05f0a5845b18.PNG)

***PC specifications:***
AMD fx 8350 GTX 780ti Windows 10 64bit

**Comment by lightningterror** [comment]
Block dump please. I'd like to test this out. Then I will update the code.

**Comment by MrCK1** [comment]
Did you test with all renderers, ect? Do you know why the hack was added originally? A little more info is necessary IMO.

**Comment by atomic83GitHub** [comment]
Here is the blockdump:
https://drive.google.com/file/d/1vqe17oWhOdEChufFIXRmVohRWnUV0Cv4/view?usp=sharing

It was made to fix a old Half bottom screen issue (https://github.com/PCSX2/pcsx2/issues/1339). Now it is perfect without any hacks.

**Comment by lightningterror** [comment]
I'll also need a savestate.

**Comment by atomic83GitHub** [comment]
Here it is, also don't forget to enable GS memory wraping, it fix a very little corruption at the copyright screen (again was fix by the CRC hack but not needed anymore).https://drive.google.com/file/d/19NDWkqSZtxyYlQP0l7VsWV-TlyedVPnh/view?usp=sharing

**Comment by lightningterror** [comment]
Never realized how much broken the game was on 1.4.

**Comment by lightningterror** [comment]
@atomic83GitHub test this PR out.
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.3475-master/job/37c9xe38v1xw3wie/artifacts

Shuffle between Automatic and Aggressive.

**Comment by atomic83GitHub** [comment]
So, I made a test in multiples area in the game (The most demanding) and your version work perfectly fine, no issue at all. I have just to enable Hardware hacks for the missaligned blacks border and The GS memory wrapping for the copyright screen. And the agressive level give me a small boost on my amd GPU Under OpenGL.

With auto:
![capture](https://user-images.githubusercontent.com/26351275/33284799-97f56b12-d3b0-11e7-82fd-9075418f22cf.PNG)

With Agressive:
![capture2](https://user-images.githubusercontent.com/26351275/33284828-a80f6e62-d3b0-11e7-94b0-0389c99ca5b6.PNG)

**Comment by lightningterror** [comment]
What about Direct3D?

**Comment by atomic83GitHub** [comment]
Same as OpenGL, The screenshots was made with the DX11 mode.

**Comment by lightningterror** [comment]
Okay great. Looks like the PR can be merged.
