### ISSUE TITLE
GSDX : integrate unscale point and line and GS memory wrapping.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2147]
***Feature request: remove these hacks to directly integrate them in GSDX.***

***Pros:***

-Less configuration for end users
-solve directly some HW/upscalling issue

**Comment by MrCK1** [comment]
They can cause problems for other games and aren't always needed, that's why they're hacks. ;)

**Comment by atomic83GitHub** [comment]
What type of issue can they cause?

**Comment by MrCK1** [comment]
They can cause graphical artifacts and break games as many rely on undocumented GS behavior.

**Comment by atomic83GitHub** [comment]
Ok so, would you want close it?

**Comment by MrCK1** [comment]
Sure, will do.
