### ISSUE TITLE
The [&] letter won't appear on the PCSX2 iso selector gui

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2148]
***What is this issue?***

The issue is that the PCSX2 iso selector don't display the & letter, here is an example:

-The good name of the file:

![capture](https://user-images.githubusercontent.com/26351275/33240701-8f7483e8-d2ba-11e7-9985-94bd1082eb71.PNG)

-The wrong name in the PCSX2 iso selector gui:

Beyond Good   Evil

**Comment by refractionpcsx2** [comment]
It's probably because it is a reserved word and we just aren't modifying the string.  If you label the ISO with && it will probably work :P

**Comment by lightningterror** [comment]
Is this really an issue tho ?
