### ISSUE TITLE
.hack//Infection - Graphical Glitch with Fog(/Shadows?)

### ISSUE THREAD

**Issue by aphirst** [PCSX2/pcsx2#220]
**System**:
* Arch Linux x86_64
* Thinkpad X220, Sandy Bridge (i5-2520m /w Intel HD 3000 graphics)
* Kernel (with and without -ck patches) `3.15.9` and `3.16`
* xf86-video-intel `2.99.914`
* pcsx2-git d247a79 and pcsx2 `1.2.2`, using the GSdx plugin
* no DE or compositing, just Openbox

In the game ".hack//Infection" (`SLUS_202.67`), some fields have a fog/shadow effect applied as of some near-ish distance from the player. Conveniently, the first field location in the game, "Bursting Passed Over Aqua Field", has this effect. 

When using "Hardware Mode" in GSdx, this effect is garbled, and instead appears as large smudgy translucent walls as of 20m or so from the player. This happens with or without any speedhacks enabled.

With GSdx set to "Software Mode", however, the issue is not present.

Screenshots of this effect in Hardware and Software mode can be found at http://postimg.org/gallery/14uvgzdum/

If there is any additional information that would be useful while diagnosing this issue, please do not hesitate to ask.

**Side remarks:**
As the HD 3000 only supports OpenGL 3.1 in hardware, I have set the GSdx option "Separate Shader" to "Force Disabled", as otherwise I get only a black screen instead of game video.

**Comment by gregory38** [comment]
Could you try the build on this thread http://forums.pcsx2.net/Thread-GSdx-2-0 ?
At least the best you can with your limited GPU/drivers.

**Comment by aphirst** [comment]
I can test it thoroughly this evening! But just to check, is this precompiled .so for use with PCSX2 stable, or PCSX2-git-master?

**Comment by gregory38** [comment]
It must work with both.

**Comment by aphirst** [comment]
I tried it with PCSX2 stable, and the plugin cannot be loaded. The following message is printed to the terminal:
```
19:25:22: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
```
I guess this means that the version of wx that you built this against is different to the version that the PCSX2 stable version in the Arch repository is built against. Do you have a version of this .so available compiled against the other wx version?

**Comment by aphirst** [comment]
My initial testing using the GSDX update branch shows that the fog effect now seems to work. However, I only just realised that the shadows also don't work in HW mode (and seem to never have worked). So, later today I'll do some more testing and see if any of the other settings pertaining to this GSDX update have had any effect on this.

**Comment by aphirst** [comment]
I posted in the forum some GS dumps of Software and Hardware rendering of a scene with shadows (ostensibly) visible. http://forums.pcsx2.net/Thread-GSdx-1-0?pid=467744#pid467744

Software: https://d.maxfile.ro/zarsbaiwkp.7z
Hardware: https://d.maxfile.ro/zvhdxgbiel.7z

**Comment by AmbientMalice** [comment]
I have dot hack infection sitting around somewhere. I'll try to see whether the OpenGL backend improvements have made any difference later.

**Comment by AmbientMalice** [comment]
HW OGL Depth fixes the missing shadows.
![gsdx_20150706160721](https://cloud.githubusercontent.com/assets/10704701/8516596/703c8204-23f9-11e5-9749-1066d4a0e526.jpg)

My understanding is the OpenGL backend doesn't work correctly on Intel GPUs and is slow on AMD GPUs, making it only really suitable for Nvidia hardware.

**Comment by gregory38** [comment]
The issue is the intel driver on windows. No issue on linux. Nvidia is faster but AMD isn't slow. Nowadays we can't compare it anymore with the DX remderer. OpenGL is much more accurate.

**Comment by AmbientMalice** [comment]
>The issue is the intel driver on windows. No issue on linux. 

I've heard about that. Interesting state of affairs.

>Nvidia is faster but AMD isn't slow.

Good to hear.

>Nowadays we can't compare it anymore with the DX remderer. OpenGL is much more accurate.

I've noticed as much. Out of curiosity, do you intend to default to GL down the track? Or remove the D3D backends completely?

**Comment by ssakash** [comment]
I don't think removal of Direct3D Renderer was a plan. @refractionpcsx2 is currently working on porting the changes to DX.

**Comment by gregory38** [comment]
OpenGL is already the default on Linux. I don't care about windows ;) Code is cross-platform, so it was enabled on windows too (this way it has more testers).

**Comment by aphirst** [comment]
I think something recently caused this to break again. What happens is that, in HW mode, the shadows render, but not in the right location (and as far as I can tell; are only visible "through" a UI element).

[Dump](https://d.maxfile.ro/oupyhigiyj.xz), [sanity check of settings](https://d.maxfile.ro/lkiiiudppu.png)
[Hardware Rendering](https://d.maxfile.ro/vszflhnjiq.png): note the weird quasi-shadows in the text box
[Software Rendering](https://d.maxfile.ro/izqzrrbjjh.png): shadows in the correct locations

**Comment by karasuhebi** [comment]
If I try to view your screenshots, Chrome screams at me about maxfile.ro not being safe. XD

Would you mind uploading screenshots here on GitHub or maybe another image sharing site like Imgur?

Thanks!

**Comment by aphirst** [comment]
I don't use Imgur, and hate it, but if I have time later tonight I'll reupload these to some other filehost and modify the links accordingly.

**Comment by karasuhebi** [comment]
May I inquire as to why you hate it? Is it just the shitty community of users? Or is there some technical and/or actually valid reason?

**Comment by aphirst** [comment]
On the technical side, I hate how it won't just give you straight WebM links, it always tries to force you through some "gifv" shite that malfunctions if you're disabling javascript, and sometimes even if you aren't. I just want to share direct links to either images or videos, and imgur gets in the way and tries to give you scaled versions and other crap that I simply don't want.

**Comment by karasuhebi** [comment]
I didn't know about the WebM/GIFv thing, I only really put images on Imgur. With Greenshot though, that second point is not an issue. The link it puts in your clipboard is a direct link to the picture, like the one I posted above. If you don't like Greenshot, I can also suggest ShareX, which seems to be more feature-rich and has a similar UI. They're both open source projects.

**Comment by aphirst** [comment]
I'd rather support sites that act in the way(s) I like, by uploading my own things onto such sites.

I'll do the reuploading in a bit, I have some other crap to deal with this evening first.

**Comment by karasuhebi** [comment]
Fair enough. Thanks for participating in this debate BTW. Most people would have blown me off. XD

**Comment by bositman** [comment]
This should probably be fixed by this: https://github.com/PCSX2/pcsx2/commit/37661f3a8669b07c0b956d8919b9dddb60125908
Care to retest?

**Comment by aphirst** [comment]
It definitely seems to be working now. I didn't change any blending settings, but it still looks right regarding what you described, as in this game the HP/Level text (assuming I'm thinking of the right thing) is supposed to be an off-white.

**Comment by refractionpcsx2** [comment]
Glad it's fixed, are we good to close this issue now?

**Comment by aphirst** [comment]
As long as it doesn't reappear! :P

**Comment by refractionpcsx2** [comment]
Well there's no guarantee of that, but unfortunately my crystal  ball is in for its yearly polish and shine :P
