### ISSUE TITLE
Cache mode 3 not impemented error.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2206]
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
EE set to interpreter with cache enable. All other to default configuration.

***Plugins used:***
All default

***Description of the issue:***
One of my .elf file throw an error causing a black screen issue.
Here is the error:

![capture](https://user-images.githubusercontent.com/26351275/33737725-70e8266a-db97-11e7-9932-17b2b5c46887.PNG)

***How to reproduce the issue:***
Load PS2INFONES Under interpreter with cache (will crash the VM with recompiler or interpreter without cache).  

***Not a regression.***

***PC specifications:***
AMD fx8350  GTX 780Ti  Windows 10 64 Bit

***Note***
The build-in blockdump debug option don't seems to work with .elf

**Comment by MrCK1** [comment]
This is the only program that complains about it, and it's a homebrew NES emulator at the least. It's not really a priority or critical to emulation AFAIK.

**Comment by atomic83GitHub** [comment]
Oh ok, I made an issue on this because I thought some games used it :).

**Comment by MrCK1** [comment]
Unless it gets printed in the console, no other game is running into this code.
