### ISSUE TITLE
[GSdx OGL HW Regression] Tomb Raider: The Angel of Darkness - Missing Fog

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2215]
***PCSX2 version:***
1.5.0-dev-2215

***PCSX2 options:***
Defaults

***Plugins used:***
GSdx OGL HW. (DX11/DX9 were never emulated correctly in HW - the fog fills the entire screen)

***Description of the issue:***
Fog in the distance is missing from the game.

***How to reproduce the issue:***
Go in-game, find an alleyway/area with long view distance; observe missing fog.

***Last known version to work:***
https://github.com/PCSX2/pcsx2/commit/4d10eda30821ca3fa049a8d1bb7253f25502ac1d

Regression introduced here: https://github.com/PCSX2/pcsx2/commit/52a2bb55241ffdf3b580f567400fe047c96b56fc

***PC specifications:***
i5-6600k @ 4.7GHz, GTX 1070, Windows 10 Home 64-bit

***Notes***

Debug messages:
```
T:Error	ID:10716	S:Mid	=> FBMASK SW emulated fb_mask:80808080 on 32 bits format
T:Error	ID:10738	S:Mid	=> First vertex is  P: 28800 => 36992    T: 8 => 8200
T:Error	ID:10738	S:Mid	=> Color shuffle R => B
T:Error	ID:10738	S:Mid	=> Color shuffle G => A
T:Error	ID:10738	S:Mid	=> ERROR: RT height is too small only 2048 but require 3584
```
I fixed the issue by flipping the sign in ```m_texture_shuffle = ((v[1].U - v[0].U) < 256);```

However, we need an alternative solution here. Replacing ```256``` with any value up to ```4096``` will also remedy the issue (while the sign is flipped) - I didn't test with values higher then that.
```
	// Shadow_of_memories_Shadow_Flickering
	if (m_texture_shuffle && count < 3 && PRIM->FST) {
		// Avious dubious call to m_texture_shuffle on 16 bits games
		// The pattern is severals column of 8 pixels. A single sprite
		// smell fishy but a big sprite is wrong.
		m_texture_shuffle = ((v[1].U - v[0].U) < 256);
}
```

OGL HW: (see top-left corner)
![gsdx_20171211194518](https://user-images.githubusercontent.com/16314399/33861455-e5d9abc6-deab-11e7-8123-364c6aa0a8ca.png)

OGL SW:
![gsdx_20171211194518_ 2](https://user-images.githubusercontent.com/16314399/33861458-e6b5cd72-deab-11e7-842d-6175ebf94701.png)

**Comment by gregory38** [comment]
@MrCK1 
Do you get those messages
```
T:Error	ID:10716	S:Mid	=> FBMASK SW emulated fb_mask:80808080 on 32 bits format
T:Error	ID:10738	S:Mid	=> First vertex is  P: 28800 => 36992    T: 8 => 8200
T:Error	ID:10738	S:Mid	=> Color shuffle R => B
T:Error	ID:10738	S:Mid	=> Color shuffle G => A
T:Error	ID:10738	S:Mid	=> ERROR: RT height is too small only 2048 but require 3584
```
before or after your "fix" ?

**Comment by gregory38** [comment]
Hum, actually maybe we just need to do `std::abs(v[1].U - v[0].U) < 256` because the purpose is to check the width of the sprite.

**Comment by MrCK1** [comment]
@gregory38 ```std::abs((v[1].U - v[0].U) < 256);``` works fine with additional parenthesis. Should I still check the debug output from before the modification?

**Comment by willkuer** [comment]
`std::abs((v[1].U - v[0].U) < 256);` is not the same as `std::abs(v[1].U - v[0].U) < 256;`

**Comment by gregory38** [comment]
So based on screenshot of the texture in discord. The game does use a channel effect. However it is a slight variation.
`RG => BA`
`BA => RG of next pixels`
Fortunately it seem the game doesn't use the RG part so we only need to emulate the `RG => BA` shuffling.

I propose that we write this kind of code. I let's you improve the comment.
```
// Shadow_of_memories_Shadow_Flickering
	if (m_texture_shuffle && count < 3 && PRIM->FST) {
		// Avious dubious call to m_texture_shuffle on 16 bits games
		// The pattern is severals column of 8 pixels. A single sprite
		// smell fishy but a big sprite is wrong.
                // NOTE: Tomb raider (angel... ) seems to rely on it. In this case, framebuffer and texture are the same.
                GL_INS("WARNING: potential misdetection of texture shuffle effect");
		m_texture_shuffle = (std::abs(v[1].U - v[0].U) < 256) || ((m_context->FRAME.Block() == m_context->TEX0.TBP0);
```
Then we need to check regression on  Shadow_of_memories. Dunno if I have the dump for this one.

**Comment by lightningterror** [comment]
@MrCK1 What's the status on this ?

**Comment by MrCK1** [comment]
I'll get it done in a few days, I'm a bit lazy. :)
