### ISSUE TITLE
DamonPS2 PRO Android ps2 emulator PCSX2 port? Using stolen PCSX2 code?

### ISSUE THREAD

**Issue by blackman91** [PCSX2/pcsx2#2216]
Link to the Android emulator: https://play.google.com/store/apps/details?id=com.damonplay.damonps2.pro.ppsspp

Related issue: https://github.com/hrydgard/ppsspp/issues/10402

Related reddit thread with proof: https://www.reddit.com/r/emulation/comments/7ivii4/damonps2_pro_fastest_ps2_emulator_for_mobile_scam/

Also it is a real emulator here is a quick video of the emulator UI and settings, maybe it can provide some clues to you guys:
https://drive.google.com/file/d/1Bg5ljmEBYtq-Sp2HxKmlWXVWcnSy3CFO/view

Also link to the pcsx2 databases the emulator saves to your internal storage:
https://drive.google.com/file/d/1qnnSI7vaIAIYBySaQqpDX97_s2DE3T-R/view

**Comment by MrCK1** [comment]
Thanks, we already know about it. :)

**Comment by atomic83GitHub** [comment]
PCSX2 is protect by copyright?

**Comment by MrCK1** [comment]
We're protected by GPL ( GNU General Public License) which states that source code must be made available if our project is included. We don't know the details yet.

**Comment by lightningterror** [comment]
I'll be closing this since we know about it, for any further discussions they can be done on the forum.
https://forums.pcsx2.net/

**Comment by refractionpcsx2** [comment]
@willkuer we are discussing it in here https://forums.pcsx2.net/Thread-android-compatability

**Comment by willkuer** [comment]
Thanks for the link

**Comment by jonata2717** [comment]
motorola Z force https://www.youtube.com/watch?v=4qeL2tBhzGM&t=40s
