### ISSUE TITLE
[GSdx HW] Dragon Ball Z Budokai Tenkaichi 2 and 3 - Character reflection textures

### ISSUE THREAD

**Issue by Stickend** [PCSX2/pcsx2#2219]
***PCSX2 version:***
v.1.5.0-dev-2237-g41051f3cf

***PCSX2 options:***
Everything by default.

***Plugins used:***
GSDX, Lilypad, SPU2-X, Rest Default null plugins.

***GSDX configuration:***
Resolution 5x Native
OpenGL Hardware Mode
Accurate Date
Blending Full
CRCHack None
Mipmapping Automatic

***HW Hacks:***
Trilinear
TC Offset X 440
TC Offset Y 420

***Description of the issue:***
With current settings, emulation is almost identical to PS2. But there is a bug with textures which are supposed to reflect light.

![cell mal](https://user-images.githubusercontent.com/34516283/33950323-64e10faa-e02c-11e7-8c1a-7f2e310f94b5.jpg)

If I go into HW Hacks and disable Depth Emulation, these textures get corrected, but ghost effect appears. I try to correct it with Skipdraw at 5. It partially works, but either way disabling Depth Emulation destroys the natural lighting of maps. (It also affects to the "heat" effect of the Desert-Day map, which it's missing)

Without Skipdraw

![cell bien](https://user-images.githubusercontent.com/34516283/33950337-6db2b1ce-e02c-11e7-9f07-9b0b540ccc52.jpg)

With Skipdraw 5

![cell bien 2](https://user-images.githubusercontent.com/34516283/33950349-72abfcda-e02c-11e7-9125-881729faf532.jpg)

Is there any way of correcting these textures without disabling Depth Emulation or sacrificing anything as the natural lighting? Realize that dinamic lighting isn't affected, as it works fine with all of these settings.

***How it should be (SW Mode):***

![cell mal sw](https://user-images.githubusercontent.com/34516283/33950357-78ee7208-e02c-11e7-93cd-9d6b01119ee2.jpg)

***How to reproduce the issue:***
Textures: choosing any character with reflexive textures (Cell, Freezer)
Lighting: Disable Depth Emulation. It affects to every map.

***PC specifications:***
CPU: Intel Core i7-4790 3.60Ghz
GPU: Nvidia GTX 970
OS: Windows 10
RAM: 16GB

I use the ***NTSC*** version of DBZBT3

**Comment by MrCK1** [comment]
Why are you using hardware hacis to begin with? Those are probably causing more issues.

**Comment by Stickend** [comment]
I need those TC Offset values in order to obtain the glow effect in the characters. If not, the effect is spread over the map.

**Comment by lightningterror** [comment]
I didn't know about this up until now. Looks like the textures flicker/move ..etc

**Comment by Stickend** [comment]
Do this have any kind of solution?

**Comment by lightningterror** [comment]
Yeah, update depth emulation code :smile:

**Comment by Stickend** [comment]
How it's that done? Unfortunately, i don't know much about codes :( 

Can you try something?

**Comment by Stickend** [comment]
Or is it going to be fixed in the next build? 😃

**Comment by Stickend** [comment]
Is this still broken?

**Comment by lightningterror** [comment]
This issue is also present in Budokai Tenkaichi 2.

**Comment by Stickend** [comment]
But I actually have a question with this: If you update the Disable Depth Emulation Code, it would correct automatically both games, but it will also affects other games, isn't it?

**Comment by FlatOutPS2** [comment]
You might be able to use the new Skipdraw Offset(currently in pull request, will hopefully be merged soon) to remove the issue with fewer downsides.

**Comment by Stickend** [comment]
Good news then. I've testing a looot with this, and I almost know how every config affects the game. I'll be waiting till then to test it more, so I can communicate all of you how it goes ;)
