### ISSUE TITLE
GSdx: Tales of the Abyss - ghosting/upscaling issue

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2221]
***PCSX2 version:***
1.5.0-dev-2238-g687c0b45e

- Tales of the Abyss has the same problem as Tekken 5 in certain stages. In the latest dev build, this problem was solved by using a hack and the CRC to Aggressive, enabling it too with the Tales of the Abyss can solve the problem with the ghosting and the transparent fence.

**Comment by lightningterror** [comment]
Tales of the Abyss doesn't need crc hacks IIRC but it does rely on the id for certain fixes.
Can you tell me the CRC id and region of your game ?

**Comment by LuismaSP89** [comment]
@lightningterror Here it is:

SLUS_213.86

Game CRC = 0xA616A6C2

Yes, i know that patch for the game, but it is an old version of the Gsdx plugin from 2-3 years ago and overrides the current gsdx plugin. You need to replace all the time you want to play another game.

**Comment by lightningterror** [comment]
@LuismaSP89 can you compile the code ?
https://github.com/PCSX2/pcsx2/blob/3c74f0f9070b6c678bb438badc98026a391ed861/plugins/GSdx/GSTextureCache.cpp#L1434
You can play around with the modx/y values, these should change how the HPO works. Each case represents an upscaled resolution, 0 is custom.

**Comment by LuismaSP89** [comment]
@lightningterror  I´m sorry, but i don´t know how to compile it :S

**Comment by lightningterror** [comment]
The channel effect for Tekken 5 is what adds the color effect on the stage. The CRC hack removes the blur/glow which causes the upsscaling issues. Tho ideally it would be best for Merge Sprite or some other hack to correct the issue without removing the effect.

Adding CRC hacks is not good practice.

Here is a compile guide for Windows.
https://wiki.pcsx2.net/PCSX2_Documentation/Compiling_on_Windows

**Comment by LuismaSP89** [comment]
@lightningterror Yes, maybe the CRC hack is not the perfect solution, i only say that because i see that fixes tekken 5 and the problem is the same. My programming skills are literally = 0

Sorry one more time, i checked that documentation but is too complicated for me, i know nothing about program compiling, codes, etc. I do not think i can do it without going crazy :S

**Comment by lightningterror** [comment]
I actually forgot to check if the crc id was on the list and it looks like it wasn't, I'll update the list as well as remove some hacks since latest master branch should render more effects correctly even on d3d11 now.
