### ISSUE TITLE
Why WideScreen Patches Not working with me? PCSX2

### ISSUE THREAD

**Issue by khekoo** [PCSX2/pcsx2#2222]
hi guys , sorry for my bad english

i have a problem!! in pcsx2 i want to use widescreen patches but it's not working , i try many ways but it's nothing , games are stretched!!

I followed the known steps like choose aspect ratio 16:9 and enable widescreen patches in system tab and i'm put the pnach file in cheats_ws folder and try put pnach file in cheats_ws in documents folder and etc...
i test many games but it's still not working

* my pcsx2 version is 1.4.0 and try many versions like 1.5.0 - 1.2.1 - 0.9.7 and more
* in console is shows me (patches loaded) but it's not working

people says is working but with me nooo , What thing I have sinned in , I do not know !!

now what the solution?? please i need to play games in ws

**Comment by MrCK1** [comment]
Please redirect your question over on the forums: https://forums.pcsx2.net/index.php

It's easier to provide support to you over there. ;)

**Comment by khekoo** [comment]
yes i post a topic in pcsx2 forums but doesn't find solution :|

**Comment by lightningterror** [comment]
As stated before please do this on the forum. Github isn't a support forum, it's for dev purposes.
