### ISSUE TITLE
Issue: Using EE/IOP Recompilers breaks PCSX2

### ISSUE THREAD

**Issue by NWPlayer123** [PCSX2/pcsx2#2224]
***PCSX2 version:***
I've poked at both 1.4.0, the latest commit, and I've even had to download and build this myself.

***Description of the issue:***
If I turn on EmotionEngine Recompiler, Visual Studio tells me:
``Unhandled exception thrown: write access violation. recLutReserve_RAM was 0x1819EAB5000.``
at https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/BaseblockEx.h#L28
If I turn on IOP Recompiler, Visual Studio tells me:
``Unhandled exception at 0x00007FF6C5308005 in pcsx2.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.``
with no source being shown (something at runtime?)
Note: this is with my git build, have both Release|x64 and Release AVX2|x64 built, not that it matters since it's the recompiler and not the graphics plugin.
If I use both on Interpreter it seems to boot BIOS and the game (Ratchet and Clank, verified with redump) just fine.

***PC specifications:***
https://www.asus.com/us/Laptops/ASUS-ZenBook-Pro-UX501VW/specifications/
i7 6700HQ, GTX 960M, Windows 10, clean install as of yesterday (never tried before reinstalling).

**Comment by willkuer** [comment]
x64 is only supported by the interpreters IIRC and only a first step to get a fully functional x64 port. For now only use builds against x86 targets.

**Comment by NWPlayer123** [comment]
@willkuer looks like rebuilding for x86 works fine, I was having problems with pre-built stuff but it seems like that was just Discord's overlay (I only tested those before turning it off after figuring out that broke PCSX2 too), good for now, that's a different issue anyways and no idea who's to blame

**Comment by willkuer** [comment]
Btw you don't need to compile the sources yourself if you don't aim to develop the program yourself. For simple gaming we have at least weekly nightly/beta/dev builds...
