### ISSUE TITLE
pcsx2 only boot .elf from the drive\partition on which pcsx2 is. (Windows)

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2225]
***PCSX2 version:***
Last 1.5dev

***Description of the issue:***
PCSX2 will always fail to read .elf on a other disc than "C" on Windows (throw TLB miss)

***How to reproduce the issue:***
Put a .elf on a usb stick/hard drive or in a 2nd SATA/IDE hard drive device.

***Regression [Incoming]***

***PC specifications:***
AMD fx8350 GTX 780Ti Windows 10 64 Bit

#1930 can be related to that, I need to check if it's this version wich introduce the issue.

**Comment by MrCK1** [comment]
I believe it's intentional for the time being. Is your C: drive the one that has your OS? That would probably be considered the "host" drive in your case, which is what the behavior is aiming for AFAIK.

**Comment by atomic83GitHub** [comment]
Yes, The C: drive is the host in my Windows

**Comment by willkuer** [comment]
Why should it be intentional? Actually restricting the drive but not the remaining part of the fileName appears rather complicated... but I didn't check the source.

**Comment by vsub** [comment]
Hmm I don't remember having such problem and it seems something was changed between 1.4.0 and the latest beta(works fine with 1.4.0)

And to add something....it's not 
"pcsx2 only boot .elf on the "c" drive"
but
 "pcsx2 only boot .elf from the drive\partition on which pcsx2 is"
meaning,if you are running pcsx2 from the C drive,it will boot elf  files only from the C drive
