### ISSUE TITLE
Ps1 NTSC games can't be read on a PAL BIOS (and vice-versa)

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2227]
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
All default, speedhacks disabled

***Plugins used:***
All default

***Description of the issue:***
Ps1 games are region locked on PCSX2, a NTSC game can't be read on a PAL bios (and vice-versa), this will result in a black screen for the import game

***How to reproduce the issue:***
Load a NTSC game on a pal bios or a pal game on a NTSC bios.

***Not a regression***

***PC specifications:***
AMD fx8350 780Ti Windows 10 64 Bit

***Blockdump***
https://drive.google.com/file/d/1bZwGu2uFm90DdDpbqHDsMbRxINcoeo2T/view?usp=sharing

**Comment by ramapcsx2** [comment]
The boot rom doesn't allow imports, so everything is working as it should.
It is inconvenient however and there should be a workaround at some point.

**Comment by Squall-Leonhart** [comment]
Isn't this libcrypt protected titles only, i thought pretty much all psx emulators did that with those.

**Comment by atomic83GitHub** [comment]
Closing this in favor of other issues.
