### ISSUE TITLE
2nd controller

### ISSUE THREAD

**Issue by Ionutman** [PCSX2/pcsx2#2229]
Hi i need help.When i try to configure the 2nd controller settings it deletes the other one configurations can i do something about this?

**Comment by MrCK1** [comment]
This isn't a place for general support. Please redirect your questions to forums.pcsx2.net. Thanks ;)

**Comment by Ionutman** [comment]
can you provide me a link please?i heard they are dead and i don't think i will get a response

**Comment by MrCK1** [comment]
Here: https://forums.pcsx2.net/index.php
