### ISSUE TITLE
Removal of MMX usage

### ISSUE THREAD

**Issue by xsacha** [PCSX2/pcsx2#223]
Fairly self-explanatory. We have SSE2, why are we using MMX? The alloc/free of MMX regs is rather silly. This code needs updating.

Leaving it here as an issue.

Most hide out here: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/ix86-32/iCore-32.cpp
Also, 3DNow instructions.

**Comment by gregory38** [comment]
So as pseudo said, the code is barely used. After a long study, I think we can replace mmx code in the JIT to SSE2. MMX is mostly used in shift operation. 

Note: that I have some major syntax changes pending so don't start anything yet.

**Comment by gregory38** [comment]
Most (if not all) mmx was removed. Therefore I'm closing the issue.
