### ISSUE TITLE
Meta: SPU2-X Delay Cycle

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2233]
***This is a meta topic***

***Description of the issue:***
The SPU2-x plugin have the Delay Cycle option set to 4, this solve some games, but break some other:

-Higurashi no Naku Koro ni Matsuri Kakera Asobi (#918)

-Deus Ex: The Conspiracy (#615)

-Armored Core 2

-Unreal Tournament (#268)

They need the Delay Cycle option set to 1.

***Way to fix this***

-Make a gui option like this:

[Delay Cycle hack: set the Delay Cycle value to 1. Fix some missing/broken voices (Note: Unreal tournament will hang without this hack!)]

***Make this before the 1.6 release would be very nice :)***

**Comment by MrCK1** [comment]
We've already discussed a GUI option for DelayCycles. It's a hack and won't be added to the SPU2-X GUI as such. You'll have to resort to editing the .ini for the small amount of games that are affected by this.

**Comment by MrCK1** [comment]
I'm going to use this because all of the games listed have already their own issues open. There's not enough cases here to warrant a meta issue either.
