### ISSUE TITLE
Wipeout Fusion: GSdx CLUT Regression

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2234]
***PCSX2 version:***
v1.5.0-dev-2240-g13526fc67

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults, OGL HW/SW

***Description of the issue:***
With the default setting of `1`, the `clut_load_before_draw` ini option causes sprite corruption in-game. Setting the ini value to `0` eliminates the issue.

***How to reproduce the issue:***
Boot game and go into a race, make sure `clut_load_before_draw = 1`

***Last known version to work:***
https://github.com/PCSX2/pcsx2/commit/b36dfb356ea5274ea75f2a7edf97a8732589f326

***PC specifications:***
i5-6600K, GTX 1070, Windows 10 Home 64-bit

Off:
![gsdx_20171226163928](https://user-images.githubusercontent.com/16314399/34365184-7531a188-ea5b-11e7-8d13-15c427f03536.png)

On:
![gsdx_20171226163958](https://user-images.githubusercontent.com/16314399/34365187-795af7a0-ea5b-11e7-9aa2-155a04f6c76f.png)

**Comment by gregory38** [comment]
Are you sure the default is 1 not 0 ?

**Comment by MrCK1** [comment]
Yes, it's enabled by default. https://github.com/PCSX2/pcsx2/commit/c66004bbb25bb62ad4cc30a1984eaa98ffb81406

We'll have to add a CRC hack to disable it like Harley Davidson.

**Comment by gregory38** [comment]
Might worth to add a note in the code so we have another testcase for this clut crazyness
