### ISSUE TITLE
GSDX Half-Pixel Offset Causes Texture Corruption in Persona 3 FES

### ISSUE THREAD

**Issue by Enverex** [PCSX2/pcsx2#2236]
***PCSX2 version:***
GIT as of 20 minutes ago. Commit 13526fc679bdfd4760f8809deb5fd49d34547313.

***PCSX2 options:***
Half-Pixel Offset. All other options seem unrelated.

***Plugins used:***
Default. GSDX in OpenGL hardware mode being the only relevant one.

***Description of the issue:***
Textures on the ground around your character become corrupted and show as several large triangles around/near you, which are striped with random bright colours.

***How to reproduce the issue:***
 - Set graphics plugin to GSDX, OpenGL Hardware.
 - Set "Half-Pixel Offset" from "None" to "Normal" (the recommended value)
 - Play Persona 3 PES.
 - Go into Tartarus (seems to happen worst of all).

***Last known version to work:***
Unknown.

***PC specifications:***
Intel i7-5775C, Nvidia GTX 1060 6GB, Linux.

*How it should look....*
![p3-ok](https://user-images.githubusercontent.com/958670/34407967-06d39d5e-ebb9-11e7-8f59-a8b3f3513ed8.png)

*How it looks if Half-Pixel Offset is enabled...*
![p3-bad](https://user-images.githubusercontent.com/958670/34407974-1aa98b7c-ebb9-11e7-9051-e4a6a62f6782.png)

**Comment by MrCK1** [comment]
@Enverex Please modify your issue according to the original template. Thanks! :)

**Comment by Enverex** [comment]
Whoops, lost the main body and posted just the notes instead. 1 sec.

**Comment by MrCK1** [comment]
@Enverex Can you post a picture of what it normally looks like and what you get with half-pixel offset? Just to make sure, you're not using any other speedhacks/HW hacks correct?

**Comment by Enverex** [comment]
Correct, no other hacks/options are enabled. Added the images to the first post.

**Comment by lightningterror** [comment]
What does Half-Pixel Offset fix in the game btw ? Since you are using it.

**Comment by Enverex** [comment]
I don't typically use the option, it showed up when testing - I suspected it may fix the offset character overlay images during dialogue (their blink graphic is misaligned) and suddenly noticed this completely weird side-effect from enabling the option.

I thought it was worth reporting given that this is what happens when it's set to the recommended option of "Normal".

**Comment by lightningterror** [comment]
HW hacks can cause glitches, which is why it's not recommended to use them unless a game specifically needs them. As for Half Pixel offset it can cause glitches in other games so it's not just persona 3. The hack can be improved ofc but that will require some work. 
Off is the recommended option for it and not normal btw.

The wiki has some documentation about what hacks can benefit Persona 3.
https://wiki.pcsx2.net/Shin_Megami_Tensei:_Persona_3_FES

**Comment by Enverex** [comment]
May be worth rewording the tooltip for the option as it implies it should be set to Normal, at least that's how I read it.

![image](https://user-images.githubusercontent.com/958670/34410746-36694ff8-ebca-11e7-9902-8288b9515a9d.png)

**Comment by lightningterror** [comment]
Perhaps renaming the selected option from "**Off**" to "**Off (Default)**" is a good move, could also be done for the sprite and round sprite options.

**Comment by FlatOutPS2** [comment]
> Perhaps renaming the selected option from "Off" to "Off (Default)" is a good move, could also be done for the sprite and round sprite options.

It's even better to add a reset to default option. ;)

**Comment by lightningterror** [comment]
> It's even better to add a reset to default option. ;)

Not if you only want to reset/disable a specific option, this should help users know what the default options are, I'm waiting for your skipdraw PR to get merged before I make any changes.
