### ISSUE TITLE
[lilypad]: Half life don't work if a ps1 mouse or a pop'n music controller is on the port 2

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2238]
***PCSX2 version:***
Last 1.5git

***PCSX2 options:***
All default 

***Lilypad config:***
![image](https://user-images.githubusercontent.com/26351275/34422382-67633600-ec15-11e7-84bd-f7c455b27e5d.png)

![image](https://user-images.githubusercontent.com/26351275/34422394-7f8dd186-ec15-11e7-8425-49e17493cc02.png)

***Plugins used:***
All default

***Description of the issue:***
The game Half life don't like some Lilypad virtual controller. If a ps1 mouse is on the port 2, the game will suffer from heavy stuttering. If a pop'n music controller is on the port 2, the "down" key will be triggered non-stop

***How to reproduce the issue:***
Load Half-life with a pop'n music controller or a ps1 mouse in the virtual controller port 2.

***Don't know yet if it's a regression, I will check ASAP***

***PC specifications:***
Intel Core I5 3230m AMD radeon 7600m Windows 10 64 Bit

**Comment by MrCK1** [comment]
Isn't this completely single player? I don't recall there being co-op options unless I'm wrong.

**Comment by atomic83GitHub** [comment]
No, the decay mode can be play with 2 controller.

**Comment by MrCK1** [comment]
The PS Mouse only works with PS1 modes.

**Comment by atomic83GitHub** [comment]
Nuvee should be good but why the game throw heavu stuttering with a ps1 mouse?

**Comment by FlatOutPS2** [comment]
> Nuvee should be good but why the game throw heavy stuttering with a ps1 mouse?

The same thing should happen when plugging an actual PS1 mouse in port 2 of a PS2 while playing Half-Life. Plugging in controllers that are unsupported by a game can cause the game to react in unsuspected ways (or like the pop'n music controller here in expected, but undesired, ways).
