### ISSUE TITLE
Grand turismo 4/Tourist Trophy: Crash with the EE clamping mode to full

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2240]
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
All default, speedhacks disable

***Plugins used:***
All default

***Description of the issue:***
The game is unable to load a demonstration sequence with the EE clamping mode to normal or preserv-sign, with EE clamping mode to full, the game is unable to load a level and the emulator throw some TLB miss error along with this:

![image](https://user-images.githubusercontent.com/26351275/34453238-ecf71630-ed4e-11e7-8cd4-69b76ea0cac4.png)

Note: If you load a level with Normal Clamping and switch to full once in the ingame menu, when loading a demonstration sequence, the game with throw some TLB miss.

Note 2: If you do the same thing with the Interpreter + cache the console throw this:

![image](https://user-images.githubusercontent.com/26351275/34453319-e575c728-ed51-11e7-8824-7c5b74206f55.png)

***How to reproduce the issue:***
Load a Gran Turismo/Tourist Trophy level with the EE clamping mode set to full

***Not a regression***

***PC specifications:***
Intel Core I5 3230m AMD radeon hd7600m Windows 10 64 Bit

***Blockdump***
https://drive.google.com/file/d/1E2EX4cAkrxA5HYfWfqY5G_3WyPArjx0x/view?usp=sharing

**Comment by lightningterror** [comment]
Someone was looking in to this issue on the forum but I don't know what happened, it's been a while.

**Comment by atomic83GitHub** [comment]
Duplicate of the meta Full ee clamping.
