### ISSUE TITLE
Uchuu Senkan Yamato: Iscandar he no Tsuioku d-pad movement issue

### ISSUE THREAD

**Issue by Zeether** [PCSX2/pcsx2#2241]
***PCSX2 version:***
Development build v1.5.0-dev-2205-gaf2278c3c-windows-x86

***PCSX2 options:***
Default options, no clamping or game fixes/speedhacks

***Plugins used:***
Default plugins, GSDX 11 used, LilyPad (20170917165336) 0.12.1 used for gamepad input

***Description of the issue:***
During the game's tutorial level, you are tasked with pointing the Yamato towards a direction at 45 degrees along the X/Y axis using a Homeworld-style movement disc controlled via the d-pad. The problem is that the d-pad only seems to point in strict 90 degree angles and not towards the 45 degree (approx.) angle that the game expects you to go towards, so the tutorial is impossible to complete. A screenshot has been attached to show this for clarification.

![gsdx_20171128233533](https://user-images.githubusercontent.com/8504728/34463032-8fbd6ade-ee1e-11e7-959f-8a33c65dfffb.png)

***How to reproduce the issue:***
Load up the game, enter the tutorial mission. When you reach the segment where the game prompts you to use the movement disc, try to point the cursor at a 45 degree angle. It only moves in 90 degree "steps" instead of allowing anything outside of that.

***Last known version to work:***
Not known

***PC specifications:***
CPU: Intel Core i5-2410m GPU: NVidia GeForce 525M OS: Windows 7x64

**Comment by atomic83GitHub** [comment]
Have you try differents clamping/rounding under the EE/IOP and VUs tab?

**Comment by Zeether** [comment]
I tried several combinations of clamping/rounding, none of them worked.

**Comment by MrCK1** [comment]
Can you post.your Lilypad settings?

Also, did you try 1.4.0/1.2.1 to see if it exists there?

**Comment by Zeether** [comment]
Lilypad settings are all default, using a DirectInput controller (it happens on XInput too). 

The issue still exists in 1.4.0 as well.

**Comment by atomic83GitHub** [comment]
If a remember, the Dpad on the Dualshock2 have a preasure sensitive function right? If yes it can be the issue.

**Comment by Zeether** [comment]
I don't have a Dualshock 3 on me, but that could be the case if it's detecting a full press. I'm using an old Logitech controller that obviously has no pressure sensitivity.

**Comment by FlatOutPS2** [comment]
> Update: I remapped the d-pad to have low sensitivity left/right and it worked.

Yeah. As atomic83GitHub mentioned even the d-pad is pressure-sensitive, so this issue can sometimes be encountered when using almost any other controller than a fully enabled DS2/DS3. It's not a PCSX2 issue/bug though, so this can be closed.
