### ISSUE TITLE
Still issues on SCES-52412 on the latest dev-build, read for more please.

### ISSUE THREAD

**Issue by TheGITofTeo997** [PCSX2/pcsx2#2243]
Hello guys, for this report and for the complete explanation you have to refer completely to [#1962](https://github.com/PCSX2/pcsx2/issues/1962).
I know this will get closed as soon as possible as a duplicate, since it is. 

****************************************************************************
The game I'm talking about is Jackie Chan Adventures (SCES-52412) from 2004. 
I update almost everyday my dev-build of PCSX2 to see if there are improvements. Well over the time
there have been several improvements but the major issue still exists. 

****************************************************************************
The major issue is that the left part of the screen (vertical divided) as we **all** know has a lot of graphical issues. This happens in Hardware Mode at upscaled resolution, you can get less glitches if you use OpenGL.

****************************************************************************
What i am asking you guys, before this gets closed without further explanations, as will probably be, is
if you are working on this game, or if there's a temporarly workaround for this. Also, i am wondering if you could please add this to the database to get its situation monitored. This is a shame since it is a really good game, and it's bad not being able to play this on the emulator, since this is the only good PS2 emulator out here. I am a YouTuber and i would like to get this game on my channel to do a let's play on 
your emulator.

****************************************************************************
Feel free to close this report, as i am sure you'll do, but at least give me some additional informations as i've said above. Thank You for your work and support, and have a happy new year.

**Comment by MrCK1** [comment]
The answer to your question is no, not actively. The issues are already being tracked in #1838. As long as that issue stays open, the status of the same is unchanged.

Everything you see in the pull requests section is pretty much what's actively being worked on.

These bugs are very hard to track down and require us to dedicate alot of time on the side with other commitments. 

Also, please refrain from making useless reports like this, if you want further support go to the PCSX2 forums instead. This is not the place for providing general support.

**Comment by FlatOutPS2** [comment]
Just check #1838 if you want to know if there are developments on this issue. If you have new information or a pressing question you can respond there too. There's no need to create a new issue everytime you want to ask a question about this bug/game.
