### ISSUE TITLE
[GSDX HW] Syphon Filter series: Sprite Flickering/Corruption

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2249]
***PCSX2 version:***
PCSX2 1.5.0-20171228104611 - compiled on Dec 27 2017

- **Notes**:
Sprites are also visible through walls, autoflush reduces this to a degree (HW hacks were not used in screenshots/testing)

- This issue could be related to #1602 
- Issue is present in Dark Mirror and The Omega Strain (tested so far).
- The map border will flicker in the GS Dump (also occurs at random character angles), I'm not sure if that's a GSdx issue as well, but enabling the GIF FIFO will fix that.

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults, OGL HW, DX11 HW

***Description of the issue:***
While moving around, sprites will flicker/become corrupted and appear as another texture.

***How to reproduce the issue:***
Go into any level, walk around.

***Last known version to work:***
Never

***PC specifications:***
i5-6600K, GTX 1070, Windows 10 64-bit Home

GS Dump: (rename to .7z) [SF_spritecorruption_gsdump.zip](https://github.com/PCSX2/pcsx2/files/1601891/SF_spritecorruption_gsdump.zip)

RAW GSdx dump w/debug log: (rename to .7z)
[syphonfilter_spritecorruption.zip](https://github.com/PCSX2/pcsx2/files/1601877/syphonfilter_spritecorruption.-.Copy.zip)

Normal - HW:
![gsdx_20180103170250](https://user-images.githubusercontent.com/16314399/34541921-31370e70-f0a8-11e7-9e63-f0c97b8686ec.png)

Corrupt - HW:
![gsdx_20180103170309](https://user-images.githubusercontent.com/16314399/34541936-43d81934-f0a8-11e7-93f7-7d9ff61d6995.png)

OGL SW: 
![gsdx_20180103170543](https://user-images.githubusercontent.com/16314399/34541954-5825f6f4-f0a8-11e7-9f10-b272b3f33c82.png)

**Comment by atomic83GitHub** [comment]
Would you want I add the gif fifo gamefix for this one?

**Comment by MrCK1** [comment]
Not yet, it could still be a GSdx issue as well.

**Comment by atomic83GitHub** [comment]
Also, Ace Combat 4 have a very similar issue with the lightning, did you try the preload frame data and the cpu framebuffer hacks?

And what about DirectX?

**Comment by MrCK1** [comment]
DirectX is the same, I made that more clear in the original post :)

**Comment by MrCK1** [comment]
The Omega Strain also contains this issue but to a lesser degree. Sprites will flicker as squares; but are not visible through walls.

**Comment by FoxHand** [comment]
Hi everyone. I solve this issue my way (without GIF FIFO)
![sfdm yes](https://user-images.githubusercontent.com/35567320/35101432-7ef28f88-fc9a-11e7-823b-f4d7dbddd6bc.png)
![sfdm no](https://user-images.githubusercontent.com/35567320/35101447-8890de64-fc9a-11e7-8311-610e10766eb7.png)
And the settings I use:
![settings](https://user-images.githubusercontent.com/35567320/35101648-3ecf23f2-fc9b-11e7-9500-53a236d9e0e7.png)
This work also for **The Omega Strain** and **Logan's Shadow.** Enjoy! :)

I trying to solve the same issue in these games in **PPSSPP** but for now I don't have a luck, maybe you have the solution?

**Comment by FlatOutPS2** [comment]
@FoxHand You've enabled too many options/hacks to see which (combination) actually resolves the issue. Can you check which ones are absolutely necessary?

**Comment by MrCK1** [comment]
I never tried FBC hack, I forgot actually. Auto Flush is the only one that's needed.

**Comment by FoxHand** [comment]
**Auto Flush** and **Preload Frame Data** just needed. Also random combination of **Half-Pixels Offset** and **Round Sprite** options affects visibility of lights. **Widescreen cheats** and **Internal Res** also affects resulst in some way.

**Comment by MrCK1** [comment]
@gregory38 @FlatOutPS2 This is an interesting case actually. Only Auto Flush is needed. The problem is, the fix only works at native resolution. 

Once you start upscaling, you're going to have visible sprites through walls and corruption/flickering. Must be another memory trick :P

The issue stays open for now, because most people aren't going to be playing at native resolution, and it's still technically present.

**Comment by FlatOutPS2** [comment]
I shortly tried Omega Strain and noticed the same thing. Only Auto Flush has a real positive effect on the issue, and only on native resolution. Above that it seems to work only partially and where it does it creates the flickering/corruption.

**Comment by FoxHand** [comment]
@MrCK1 **2x Native** is not that bad you know. :) @FlatOutPS2 In Omega Strain I just use SkipDraw 1.

**Comment by FlatOutPS2** [comment]
@FoxHand What effect has skipdraw 1. AFAIK it doesn't fix anything.

**Comment by FoxHand** [comment]
@FlatOutPS2 It's just removes light sprites at all. You can play in Custom Resolution mode with it instead of Native and AutoFlush.

**Comment by FlatOutPS2** [comment]
@FoxHand Removing the lights is not a solution though. ;) It will be less bothersome than flickering lights, but what we ultimately want to work towards is a solution where the lights are visible and don't flicker/corrupt at any resolution. That's why there an issue on github, rather than just a forum topic on the PCSX2 website.

**Comment by FoxHand** [comment]
@FlatOutPS2 Well, hope you can fix it completely after all. For me, Skipdraw 1 for Omega Strain is the best way. Much better than flickering here and there. I hope someone can handle light problem in Syphon Filter series on PPSSPP.

**Comment by gregory38** [comment]
Hum, this resolution effect is strange. @CK1 if you can reproduce it on a gsdump, I suggest that you dunp all textures in hw mode (native and 2x) to understand what happen.

Hum, I saw 2 diff in upscaling. Texture cache that downscale an old fb. Or the target upload. It could also be linked to the framebuffer resolution. I don't remember if the base resolution depends on the upscaling factor.

**Comment by MrCK1** [comment]
I'll do that in a little bit.

**Comment by MrCK1** [comment]
So it seems the framebuffer scaling is different at native vs 2x native which may be the source of the issue? - I'm just taking a whild guess here. At native res, it's sized at 1280x1024, but 2x native is 2048x2048.

Native
![_00719_f5001_rt0_00000_c_32](https://user-images.githubusercontent.com/16314399/35129776-2abc2708-fc8b-11e7-981b-73177ffcaa8c.png)


2x Native
![_00718_f5001_rt0_00000_c_32](https://user-images.githubusercontent.com/16314399/35129749-0d49c266-fc8b-11e7-8d39-83c595c28cac.png)

Also, it seems this input texture (appears at various addresses, not just 2f20 here) is being scaled at 2x native. Based on the context, these appear what are supposed to be the sprites - these get replaced at resolutions higher than native.

Native (64x64 texture)
![_00695_f5001_itex_02f20_c_32_11_00_00_00_00](https://user-images.githubusercontent.com/16314399/35129844-8693d7f6-fc8b-11e7-99fa-0cccd4d3c867.png)

2x Native (128x128 texture)
![_00694_f5001_itex_02f20_c_32_11_00_00_00_00](https://user-images.githubusercontent.com/16314399/35129802-54615eca-fc8b-11e7-832f-e15938b1a242.png)

**Comment by gregory38** [comment]
Wait I remember some code in gsstate that depends on the upscaling. Could you find it and try to toggle it

**Comment by MrCK1** [comment]
I'll take a look.

**Comment by gregory38** [comment]
Check m_nativeres variable. IIRC it impacts some optimizations in vertex processing.

**Comment by FlatOutPS2** [comment]
@gregory38 It doesn't seem to alter the issue.

**Comment by MrCK1** [comment]
@FlatOutPS2 Did you ever happen to check and see if this issue occurs in custom resolution? (if not I can check later) 

I gave it another look last night, didn't see anything useful. This is probably my next priority for now, but I did manage to get 2 raw dumps (native and 2x native) within 1 drawcall of each other that may help our later.

**Comment by FlatOutPS2** [comment]
No, I never use Custom Resolution (unless I'm specifically testing for CR related issues).

**Comment by MrCK1** [comment]
So I was messing around with GSdx hacks and found a partial solution to this issue. Using the large framebuffer hack removes sprites that were previously visible through objects and reduces the "box-effect" when sprites flicker - you can see still outlines where the boxes are but it's a bit less distracting now. The flickering effect is still there, and some sprites have the wrong depth (they should be behind the light, not in front) haven't found a solution to that.

Large Framebuffer disabled:
![gsdx_20180314154251](https://user-images.githubusercontent.com/16314399/37427131-c0a2acf4-279e-11e8-8841-16bfcab6d4f0.png)
![gsdx_20180314154719](https://user-images.githubusercontent.com/16314399/37427214-09e48be4-279f-11e8-896e-0a76d9967a0e.png)
Large Framebuffer enabled:

![gsdx_20180314154301](https://user-images.githubusercontent.com/16314399/37427127-bed47f92-279e-11e8-943b-32f63c480d0e.png)

![gsdx_20180314154727](https://user-images.githubusercontent.com/16314399/37427218-0b1e6c8c-279f-11e8-8229-722aa0d4e2f0.png)

**Comment by SirCanucklehead** [comment]
> Hi everyone. I solve this issue in my way:
> ![sfdm yes](https://user-images.githubusercontent.com/35567320/35101432-7ef28f88-fc9a-11e7-823b-f4d7dbddd6bc.png)
> ![sfdm no](https://user-images.githubusercontent.com/35567320/35101447-8890de64-fc9a-11e7-8311-610e10766eb7.png)
> And the settings I use:
> ![settings](https://user-images.githubusercontent.com/35567320/35101648-3ecf23f2-fc9b-11e7-9500-53a236d9e0e7.png)
> This work also for **The Omega Strain** and **Logan's Shadow.** Enjoy! :)
> 
> I trying to solve the same issue in these games in **PPSSPP** but for now I don't have a luck, maybe you have the solution?

I know I'm two years late to the party but I've tried these exact settings on 3x native res plus widescreen patch, they completely eliminated the flickering and there are no other issues. This game honestly looks like it was meant to run this way, I played for a few hours and forgot I was using an emulator.

**Comment by refractionpcsx2** [comment]
Is this still a problem?
