### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by pixelherodev** [PCSX2/pcsx2#2253]
***PCSX2 version:***
``2229-gc9abec7cb``

***PCSX2 options:***
AFAICT, any. On Linux, and happens w/ both SW and HW renderers, w/ and w/o MTVU enabled, on presets 1, 2, and 3, and so on and so forth

***Plugins used:***
``All built normally using build.sh in release mode``

***Description of the issue:***
Sometimes when I switch to/from full screen or hit ALT+TAB, PCSX2 crashes, showing an assertion failure. /home/********/Documents/Builds/pcsx2/common/src/Utilities/Linux/LnxHostSys.cpp(70) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    MTGS
    Condition: false
    Message:   Unhandled page fault @ 0x00000004

Stacktrace:
[00] 0x0x569603f3                                
[01] __kernel_rt_sigreturn                       
[02] 0x0xece42c14                                
[03] 0x0xed424d9f                                
[04] 0x0xed425ec8                                
[05] 0x0xed426bdb                                
[06] 0x0xece1427c                                
[07] 0x0xece1473c                                
[08] 0x0xece0fd90                                
[09] 0x0xeca85e27                                
[10] 0x0xefc273c4                                
[11] 0x0xefc27c01                                
[12] 0x0xefc3230c                                
[13] 0x0xefc2579f                                
[14] 0x0xefc34633                                
[15] 0x0xefc2641d                                
[16] 0x0xefc82f56                                
[17] 0x0xefc83562                                
[18] 0x0xefc970f9                                
[19] GSvsync                                     
[20] 0x0x56619e3d                                
[21] 0x0x5697210d                                
[22] 0x0x56973f35                                
[23] 0x0x56974674                                
[24] 0x0xf67d732d                                
[25] clone

***How to reproduce the issue:***
``Launch PCSX2, launch a game, switch to and from full screen a few times.``

***Last known version to work:***
``Unsure, this just started randomly today. I haven't updated the build in a while, but I have run `git pull`, if that helps. I've been using it for a while before w/o this issue, it just seemingly out of nowhere began crashing.``

***PC specifications:***
CPU: Intel® Core™ i5-3470 CPU @ 3.20GHz × 4
GPU: Integrated graphics.
    Graphics Driver:OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Desktop 
    OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.3.1
OS: Debian Linux stable/testing/unstable hybrid

**Comment by pixelherodev** [comment]
Also, if the window is swapped/alt+tab/win key is pressed during a FMV, it works fine but has the same crash immediately after the FMV ends

**Comment by MrCK1** [comment]
Does this happen with any game or a specific one?

**Comment by gregory38** [comment]
Could you install the debug package to get a nicer trace. In particular PCSX2 debug but also the mesa driver debug package.

**Comment by pixelherodev** [comment]
@gregory38 I can build the debug version, yes. You wouldn't happen to know the mesa debug package name for Debian, would you?
@MrCK1 I'll double check, but I'm fairly certain it's any game.

**Comment by pixelherodev** [comment]
Built as debug, the message didn't change.
Only further info I can provide is this (from the command line after hitting Yes/No/Ignore):

``PCSX2-linux.sh: line 75: 16843 Trace/breakpoint trap   GDK_BACKEND=x11 LD_LIBRARY_PATH="$MY_LD_LIBRARY_PATH" __GL_THREADED_OPTIMIZATIONS=1 mesa_glthread=true MESA_NO_ERROR=1 $DIR/PCSX2 "$@"``

**Comment by gregory38** [comment]
Try to install those packages
```
libegl1-mesa-dbg:i386
libgl1-mesa-glx-dbg:i386
libgl1-mesa-dri-dbg:i386
```
Potentially you can try `apt-cache search mesa dbg`

Is the initial report on a self-build PCSX2 ? I don't necessary need a debug build but rather debug symbols. They are often stripped and installed separately on release build. Anyway, are you sure that you selected the debug compiled version ?

**Comment by pixelherodev** [comment]
Huh. Weird. I think it might have something to do with GNOME. I had to remove GNOME in order to build due to conflicting dependencies and my being too lazy to set up a chroot.

After switching to Cinnamon and setting up the debug build, the problem seems to have gone away, though due its random nature I'm not certain yet. I'll try a release build again (Debug is slow as hell) and see if that changes anything.

**Comment by pixelherodev** [comment]
Yeah, its a self-build. I only ever use self-builds for emulators, _especially_ in Debian.

**Comment by pixelherodev** [comment]
Almost certain the bug is GNOME-related, so while it doesn't affect me anymore, it might end up being a problem when 1.5 is released. I'll look into it again later, for now I'll enjoy having a working emulator again :P

**Comment by MrCK1** [comment]
Unless you can reliably duplicate something to report to the GNOME team/on your end, I'll close this for now :)

**Comment by gregory38** [comment]
You can use a release build with debug symbol. It is as fast as a release build except it take more space in your disk.

Otherwise a trace with only mesa debug symbol could be enough.

**Comment by pixelherodev** [comment]
@gregory38 Thanks. Why is debug even an option then? In what scenario is debug better than Relwithdebug?

**Comment by gregory38** [comment]
Who know the guy that lives in a cave, compiles PCSX2 10 times by hour ;)

**Comment by orbea** [comment]
> Why is debug even an option then?
Compiler optimizations can interfere with debugging, but it doesn't always matter.

**Comment by orbea** [comment]
> Why is debug even an option then?

Compiler optimizations can interfere with debugging, but it doesn't always matter.
