### ISSUE TITLE
CDVD: Blockdump writing issues

### ISSUE THREAD

**Issue by turtleli** [PCSX2/pcsx2#2266]
Blockdump reading seems to work fine with PCSX2. However, there seems to be a few issues on the writing side:
 * It uses the old format dump, which creates much larger dumps than necessary (the files compress well, but still).
 * There is code to use the new format dumps, but there is a bug that causes it to crash (easily fixed)
 * CD (.bin) dumps do not work at all (not so easily fixed - I haven't figured out all the issues here yet) - The workaround is to use cdvdlinuz (CDVDiso.dll) to create CD blockdumps until it gets fixed (unfortunately I removed it from the repo a while back, though it should be easy enough to checkout a older git revision and build it or find the dll from an older PCSX2 build).

**Comment by FlatOutPS2** [comment]
See: #2072 (.bin) and #2108

The blockdumps of these games don't work.

**Comment by FlatOutPS2** [comment]
It would be good idea to disable making blockdump when a CDROM is detected for now. I've come accross a handful of non-working blockdumps already, at least two of which are from CDROM games.

**Comment by turtleli** [comment]
Well, I've attached a copy of cdvdlinuz so people can create CD blockdumps - I briefly tested it on one of my PS2 CDROMs so it should work.
[CDVDiso.zip](https://github.com/PCSX2/pcsx2/files/1628863/CDVDiso.zip)
