### ISSUE TITLE
Soul Calibur 3 - Slow Down with OpenGL Hardware

### ISSUE THREAD

**Issue by Papermanzero** [PCSX2/pcsx2#2267]
***PCSX2 version:***
1.5.0-dev2255

***PCSX2 options:***
GSDX Settings ini:
[Settings]
UserHacks_TriFilter=0
UserHacks_round_sprite_offset=1
UserHacks_SpriteHack=0
UserHacks_HalfPixelOffset=1
override_geometry_shader=-1
override_GL_ARB_shader_image_load_store=-1
UserHacks_MSAA=0
UserHacks_AlphaHack=0
UserHacks_SkipDraw=0
UserHacks_WildHack=0
UserHacks_AlphaStencil=0
preload_frame_with_gs_data=0
Userhacks_align_sprite_X=1
UserHacks_DisableDepthSupport=0
UserHacks_DisablePartialInvalidation=0
UserHacks_AutoFlush=0
UserHacks_unscale_point_line=0
wrap_gs_mem=0
UserHacks_merge_pp_sprite=0
UserHacks_TCOffset=0
Adapter=default
Renderer=12
interlace=7
mipmap_hw=1
upscale_multiplier=4
filter=2
accurate_blending_unit=3
crc_hack_level=2
MaxAnisotropy=4
mipmap=1
paltex=0
large_framebuffer=1
logz=0
fba=1
aa1=0
accurate_date=1
UserHacks=1
extrathreads=2
resx=1024
resy=1024
osd_fontsize=32
osd_log_speed=6
osd_max_log_messages=3
osd_log_enabled=0
osd_monitor_enabled=0
osd_indicator_enabled=0
osd_transparency=25
osd_fontname=C:\Windows\Fonts\tahoma.ttf
TVShader=0
ShadeBoost=0
ShadeBoost_Contrast=50
ShadeBoost_Brightness=50
ShadeBoost_Saturation=50
Fxaa=1
linear_present=1
shaderfx=0
shaderfx_glsl=shaders/GSdx.fx
shaderfx_conf=shaders/GSdx_FX_Settings.ini
UserHacks_CPU_FB_Conversion=0

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``
Default Plugins

***Description of the issue:***
If the OpenGL Hardware is selected Soul Calibur 3 has a slow down as soon as the battle starts.
Means if the characters are on screen, the FPS decreased to 50%.
If the user selects DirectX11 or software renderer everything works fine.

***How to reproduce the issue:***
Start a battle in the game.

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Windows 10, i7-5790S, 760GTX, 16GB RAM

**Comment by MrCK1** [comment]
Turn down your Blending Accuracy

**Comment by Papermanzero** [comment]
I did. Even if a have none bleding accuracy, the FPS stays at 80%

**Comment by MrCK1** [comment]
@Papermanzero Alright, let's move this over to the forums where it's easier to support you :)

https://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows

**Comment by Papermanzero** [comment]
Here we are:
https://forums.pcsx2.net/Thread-Soul-Calibur-3-Slow-Down-with-OpenGL-Hardware
