### ISSUE TITLE
Replace `-ansi` with `-std=c++98` for clang compatibility

### ISSUE THREAD

**Issue by raetiacorvus** [PCSX2/pcsx2#2268]
Currently on arch linux the pcsx2-git aur package fails to build with llvm/clang due to the usage of the incompatible `-ansi` flag. According to [gcc documentation](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options) `-std=c++98` is equivalent to `-ansi` for c++ and compatible with llvm/clang.

https://github.com/PCSX2/pcsx2/blob/6e029fc1847addc2f878f89304bb76b017d8b77c/pcsx2/CMakeLists.txt#L714

**Comment by turtleli** [comment]
I don't use the pcsx2-git AUR package, but PCSX2 builds fine for me using clang 5.0.1 on Arch Linux.

What is the exact error message? Have you checked your build settings?

**Comment by raetiacorvus** [comment]
Hi,
the aur package build with the `PACKAGE_MODE` option enabled in cmake.
Specifically it sets the following build options:
```
  cmake .. \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_TOOLCHAIN_FILE='cmake/linux-compiler-i386-multilib.cmake' \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -DCMAKE_LIBRARY_PATH='/usr/lib32' \
    -DPLUGIN_DIR='/usr/lib32/pcsx2' \
    -DGAMEINDEX_DIR='/usr/share/pcsx2' \
    -DEXTRA_PLUGINS='TRUE' \
    -DREBUILD_SHADER='TRUE' \
    -DGLSL_API='TRUE' \
    -DPACKAGE_MODE='TRUE' \
    -DXDG_STD='TRUE'
```

It results in the following error message on compilation wit clang:
```
error: unknown argument: '-ansi'
```

as does the following:
```
clang++ -Wp,-ansi -xc++ - <<< 'int main() {return 0;}'
```

**Comment by gregory38** [comment]
If I memory is right, it was about default defines such as `linux` in plugin dir macro which were wrongly replaced.
Potentially, we can test behavior of the option (ansi vs 98) with `gcc -E` to check the default define.

**Comment by turtleli** [comment]
Actually, couldn't we just use -std=c++11 instead?

**Comment by raetiacorvus** [comment]
@gregory38 is it possible to access the old issues somehow as the commit message only states:

```
* incorporate Micove's patch to allow keyword on PLUGIN_DIR define. (fixed issue 1233)
```

and the code comment is:

```
# Suppress all the system-specific predefined macros outside the reserved namespace.
# Needed when stringifying macros.
# See issue: 1233
```

and I am pretty sure it isn't referring to the github issue 1233 since the commit is 6 years old.

I found the following in [gcc's documentation](https://gcc.gnu.org/onlinedocs/cpp/System-specific-Predefined-Macros.html):
```
When the -ansi option, or any -std option that requests strict conformance,
is given to the compiler, all the system-specific predefined macros outside 
the reserved namespace are suppressed. The parallel macros, inside the 
reserved namespace, remain defined.
```

which sounds a lot like what the fix for issue 1233 wants to do according to it's code comment.

**Comment by gregory38** [comment]
Oh, it is that old.

The issue was for a plugin path like  `/usr/lib/linux/PCSX2_plugin`. The `linux` string was replaced with 1. In short, all default define that doesn't start with `__`

Very old GCC/G++ here
```
g++ -dM -E -ansi  /tmp/dummy.cpp  | g linu                                         
#define __linux 1
#define __linux__ 1
#define __gnu_linux__ 1
```
```
g++ -dM -E  /tmp/dummy.cpp  | g linu                                                              
#define __linux 1
#define __linux__ 1
#define __gnu_linux__ 1
#define linux 1
```
```
g++ -dM -E -std=c++0x  /tmp/dummy.cpp  | g linu      
#define __linux 1
#define __linux__ 1
#define __gnu_linux__ 1
```

So yes, we could use c++11 directly (which is now the default)

**Comment by loathingKernel** [comment]
On a similar note, building with Clang and LTO enabled fails because it can't find liblzma and Clang doesn't accept an argument to -flto.

This is the patch I used to get the build going:

```
diff --git a/cmake/BuildParameters.cmake b/cmake/BuildParameters.cmake
index c9715bebf..5b8fd0faf 100644
--- a/cmake/BuildParameters.cmake
+++ b/cmake/BuildParameters.cmake
@@ -340,11 +340,18 @@ endif()
 if (USE_LTO)
     include(ProcessorCount)
     ProcessorCount(ncpu)
-    set(LTO_FLAGS "-fuse-linker-plugin -flto=${ncpu}")
+    if(USE_CLANG)
+        set(LTO_FLAGS "-flto -flto-jobs=${ncpu}")
+        set(CMAKE_AR /usr/bin/llvm-ar CACHE STRING "Archiver" FORCE)
+        set(CMAKE_RANLIB /usr/bin/llvm-ranlib CACHE STRING "ranlib" FORCE)
+        set(CMAKE_NM /usr/bin/llvm-nm CACHE STRING "nm" FORCE)
+    else()
+        set(LTO_FLAGS "-fuse-linker-plugin -flto=${ncpu}")
+        set(CMAKE_AR /usr/bin/gcc-ar CACHE STRING "Archiver" FORCE)
+        set(CMAKE_RANLIB /usr/bin/gcc-ranlib CACHE STRING "ranlib" FORCE)
+        set(CMAKE_NM /usr/bin/gcc-nm CACHE STRING "nm" FORCE)
+    endif()
     set(DBG "") # not supported with LTO
-    set(CMAKE_AR /usr/bin/gcc-ar CACHE STRING "Archiver" FORCE)
-    set(CMAKE_RANLIB /usr/bin/gcc-ranlib CACHE STRING "ranlib" FORCE)
-    set(CMAKE_NM /usr/bin/gcc-nm CACHE STRING "nm" FORCE)
 else()
     set(LTO_FLAGS "")
 endif()
diff --git a/pcsx2/CMakeLists.txt b/pcsx2/CMakeLists.txt
index a7d959eab..9bae10a0a 100644
--- a/pcsx2/CMakeLists.txt
+++ b/pcsx2/CMakeLists.txt
@@ -711,7 +711,11 @@ endif()
 # Needed when stringifying macros.
 # See issue: 1233
 if(PACKAGE_MODE)
-	SET_SOURCE_FILES_PROPERTIES(gui/AppConfig.cpp PROPERTIES COMPILE_FLAGS "-Wp,-ansi,-U__STRICT_ANSI__")
+    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
+        SET_SOURCE_FILES_PROPERTIES(gui/AppConfig.cpp PROPERTIES COMPILE_FLAGS "-Wp,-std=c++11,-U__STRICT_ANSI__")
+    else()
+	     SET_SOURCE_FILES_PROPERTIES(gui/AppConfig.cpp PROPERTIES COMPILE_FLAGS "-Wp,-ansi,-U__STRICT_ANSI__")
+    endif()
 endif()
 
 add_pcsx2_executable(${Output} "${pcsx2FinalSources}" "${pcsx2FinalLibs}" "${pcsx2FinalFlags}")

```

But it fails at linking the executable in the last stage nevertheless.

**Comment by gregory38** [comment]
Well LTO is mostly a left-over of my previous tentative. I feel that it doesn't worth the hassle.

For the AppConfig.cpp issue, nowadays all files are compiled with `-std=c++11`, so it should be fine to remove all crufts

**Comment by turtleli** [comment]
> But it fails at linking the executable in the last stage nevertheless.

Hmm. LTO used to work with clang, though the last time I experimented with it (about a year ago) the binaries actually increased slightly in size. As a side note, I think the -fuse-linker-plugin and CMAKE_{AR,RANLIB,NM} stuff is only necessary for older gcc versions (I could be wrong, I'm recalling this from info from about a year ago).
