### ISSUE TITLE
F1 2004 : starting lights are black instead of red

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2271]
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
All default, no speedhacks, no hacks can solve this.

***Plugins used:***
All default

***Description of the issue:***
The game don't display starting lights as it should, they are black instead of red, look:

-OpenGL hardware BA full:
![capture](https://user-images.githubusercontent.com/26351275/35245263-db2bdc50-ffba-11e7-9904-7a0b41f0e790.PNG)

-Software render (with a more closer picture):
![capture2](https://user-images.githubusercontent.com/26351275/35245303-fabbfcda-ffba-11e7-958c-21332e31c919.PNG)

-Real PS2:
![20180122_222321](https://user-images.githubusercontent.com/26351275/35245339-1a522f38-ffbb-11e7-87ae-eebe2e2265f4.jpg)

***How to reproduce the issue:***
Load a race in F1 2004 Under PCSX2

***Last version to work: PCSX2 0.94***

***PC specifications:***
AMD fx8350 GTX 1060Ti Windows 7 64 Bit

***Note:***
-Like https://github.com/PCSX2/pcsx2/issues/2108 Blockdump don't even work with the cdvdLinuz plugin.

**Comment by FlatOutPS2** [comment]
Enabling both the **Delay VIF1 Stalls (VIF1 FIFO)** and **Enable the GIF FIFO** gamefixes will corrupt specifically this small window. Could randomly be a hint to the source of the issue...

**Comment by atomic83GitHub** [comment]
Yes, same for me:

![capture](https://user-images.githubusercontent.com/26351275/35246594-25ea86ac-ffbf-11e7-824e-7f8a4f911ec1.PNG)

I also notice that if you enable Delay VIF1 Stalls (VIF1 FIFO) in menus, the car selector will be corrupted and the game will crash at loading.

![capture](https://user-images.githubusercontent.com/26351275/35246750-b3b87c0a-ffbf-11e7-9d68-8269a08afcb7.PNG)

**Comment by MrCK1** [comment]
Did you try Auto Flush or Preload Frame Data?

**Comment by FlatOutPS2** [comment]
> Did you try Auto Flush or Preload Frame Data?

It affects software mode too(likely a core issue). ;)

**Comment by atomic83GitHub** [comment]
This bug is a regression! I retested the game with ZZogl and the red light are presents (I did not notice this in my first try) look:
![capture](https://user-images.githubusercontent.com/26351275/36605756-f81b2d82-18c1-11e8-9b86-4420a62a0d1d.PNG)

**Comment by lightningterror** [comment]
Well I wouldn't say it's a GSdx regression since the fix was never ported from zzogl.

**Comment by MrCK1** [comment]
What about GSdx in 1.40 and earl8er?.

**Comment by FlatOutPS2** [comment]
It is a GSdx regression. It works in 0.9.4, but it it's gone by 0.9.6.

**Comment by lightningterror** [comment]
Can you track down the code that caused it ?

**Comment by FlatOutPS2** [comment]
> Can you track down the code that caused it ?

Not easily. I don't have the source of the GSdx version that was included with 0.9.4.

**Comment by gregory38** [comment]
Hum it Could be a palette issue. There is an option to force the loading of palette before draw, could someone check the rendering with it ?

**Comment by FlatOutPS2** [comment]
Hum it Could be a palette issue. There is an option to force the loading of palette before draw, could someone check the rendering with it ?

`clut_load_before_draw` has no effect.

**Comment by FlatOutPS2** [comment]
The differences between 0.9.4 and 0.9.6. are massive. Might be hard to track down the regression.

**Comment by gregory38** [comment]
Yes. It would be better to analyse the rendering to find the bad draw call and try to understand where data is wrong (bad clut, bad texture, bad sampling, missing draw...). Even if you find the bad commit, it would be useless as there are huge rewrite

**Comment by lightningterror** [comment]
Can you upload a GS dump from the issue ?
