### ISSUE TITLE
Discussion: Changing default language from System Default to English

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2281]
Currently the default language when setting up PCSX2 for the first time or updating to a newer version is System Default which is ok if you're using English already however this can cause some minor issues where the language is another.

1. Missing translations for a specific language.
2. Out of date translations.
3. Console errors show up when a language translation is not available.

PCSX2 changes the translatable strings pretty often as well and many translations become outdated quite fast so it would be better to have English as the default option.

Thoughts ?

**Comment by mirh** [comment]
If you deem a translation not to be "high quality" enough, imo, you should just cancel it out regardless. 
Otherwise if it's just a couple of strings, that we don't consider accessibility-breaking enough for "voluntary users", I guess like that's enough _system default_ too.

**Comment by FlatOutPS2** [comment]
Seeing as many users on the forum have to use translators to even post in English, I'd say that changing the default to English isn't a good idea. We could change it so it selects English when a language isn't available to stop the console warnings. 

Out of date translations should be fixed before 1.6.0. That might need an entry on the website/forum requesting translators to fix those issues. If no translators are available for a language, we should use translator software to at least add some basic translation.

**Comment by mirh** [comment]
I'd already expect english to be a fallback if no language is found. 
Anyway, good points (if we use a software translator though, maybe we should put a comment/warning in the .po files)

**Comment by FlatOutPS2** [comment]
> I'd already expect english to be a fallback if no language is found.

It is, but it still tries to load the system language each timem which fails and creates the console warnings.

> Anyway, good points (if we use a software translator though, maybe we should put a comment/warning in the .po files)

Definitely. 

We could also add a list of all software translated and untranslated strings on the forum and in an issue here and ask people to proof read/help translate. Some users might not be interested in making a translation PR, but would likely be willing to help correct a few single lines.

**Comment by MrCK1** [comment]
See the chart I made here for reference: https://github.com/PCSX2/pcsx2/wiki/PCSX2-Version-Guide-for-Translations

**Comment by mirh** [comment]
Forums and reddit might be good places to advertise this. And it wouldn't hurt if we could do this kinda on the soon® side. 

p.s. at least the "guide" column in that page is quite outdated. I checked italian and chinese, and they both are up-to-date to "latest" 1.2.1

**Comment by MrCK1** [comment]
I'll make an announcement on Reddit sometime this week maybe.

Everything in that chart was imported from the old one - which I nuked. The GUI column is the only one I currently keep up to date.

**Comment by turtleli** [comment]
Maybe just me, but I don't think machine translations are much good right now. Here's an example:
[Google Translate Chinese to English translated recipe](https://translate.google.co.uk/translate?sl=zh-CN&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.pco.gov.hk%2Ftc_chi%2Fresource%2Frecipes%2Frecipes_snacks_05.html&edit-text=&act=url)
[Microsoft Translator Chinese to English translated recipe](http://www.microsofttranslator.com/bv.aspx?to=en&refd=www.bing.com&r=true&a=http%3A%2F%2Fwww.pco.gov.hk%2Ftc_chi%2Fresource%2Frecipes%2Frecipes_snacks_05.html)
[English version of recipe](http://www.pco.gov.hk/english/resource/recipes/recipes_snacks_05.html)

> I checked italian and chinese, and they both are up-to-date to "latest" 1.2.1

Not exactly. Chinese (Simplified) is at 0.9.6. Chinese (Traditional) is at 1.2.1.

> The GUI column is the only one I currently keep up to date.

I'm not sure it's up to date. Chinese (Simplified) was updated in #1915. Thai was updated in #309. There may be others.

**Comment by mirh** [comment]
I found [DeepL](https://www.deepl.com/translator) to really destroy competition tbh
... OTOH it only supports 7 languages though

**Comment by FlatOutPS2** [comment]
> Maybe just me, but I don't think machine translations are much good right now. 

Better it is than it are when there happen no translation be in the Population Center Science eXpo 2 is.

**Comment by turtleli** [comment]
I'd rather have untranslated strings than machine translated strings. That's my opinion.

**Comment by FlatOutPS2** [comment]
> I'd rather have untranslated strings than machine translated strings. That's my opinion.

There are many users that can't read English at all, so they will be better off with a machine translation than no translation at all. If there are too many missing strings, I would not want to add machine translation either. If the translation is too outdated or lacking, it might even be better to remove a language for the stable release.

But if there are just some essential strings missing and no translators can be found, a good machine translation will be better than nothing.

**Comment by MrCK1** [comment]
Our policy for GUI translations is already "no machine translations" - I don't see it being any different for now.

**Comment by FlatOutPS2** [comment]
> Our policy for GUI translations is already "no machine translations" - I don't see it being any different for now.

How do you know there aren't any already? 😛

**Comment by turtleli** [comment]
> But if there are just some essential strings missing and no translators can be found, a good machine translation will be better than nothing.

If you don't know the target language and there are no translators to be found, you won't be able to judge whether it's a good machine translation or not. Like how the machine translation examples I provided translated 粘米粉  as "Sticky rice noodles" instead of "rice flour" because 米粉 can be translated as rice noodles.

**Comment by lightningterror** [comment]
I'll close this since the initial suggestion was discussed.
