### ISSUE TITLE
Unable to run under Windows 10 (1709) x64 due to faulting module ucrtbase.dll

### ISSUE THREAD

**Issue by morphx666** [PCSX2/pcsx2#2287]
***PCSX2 version:***
``stable build v1.4.0``

***PCSX2 options:***
``Default options (as set by the installer)``

***Plugins used:***
``Default plugins provided by the installer``

***Description of the issue:***
```The emulator starts and I can configure everything but as soon as I try to boot an ISO it crashes with the following message appearing in the Event Viewer:```

```Faulting application name: pcsx2.exe, version: 0.0.0.0, time stamp: 0x568bfd0e
Faulting module name: ucrtbase.dll, version: 10.0.16299.125, time stamp: 0x9e3394c7
Exception code: 0xc0000409
Fault offset: 0x000933ab
Faulting process id: 0x1340
Faulting application start time: 0x01d39bd77ea1b12c
Faulting application path: \\server_name\d\Emulators\PS2\pcsx2.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 0d0c128e-7f84-41dc-9d81-69d9b9c7fb2c
Faulting package full name: 
Faulting package-relative application ID: 
```

***How to reproduce the issue:***
``I know ucrtbase.dll is part of the VC++ runtime but I think there's a compatibility problem between the 2015 and 2017 versions``

***Last known version to work:***
``The current stable version works just fine under other systems that have the 2015, instead of the 2017 version of the VC++ runtime.``

***PC specifications:***
``CPU: Intel Core I7 960, GPU: nVidia 1050 Ti, OS: Windows 10 Pro 1709 (16299.192) x64)``

In case it helps, I forked the repo, updated the target Windows SDK version to 10.0.15063.0, recompiled on the same machine where it fails to work and the emulator is now working perfectly.
Spu2-X fails to compile (due to xaudio not being available under Win10), but apart from that, recompiling seems to fix the issue.

**Comment by lightningterror** [comment]
> The current stable version works just fine under other systems that have the 2015, instead of the 2017 version of the VC++ runtime.
> stable build v1.4.0

v1.4.0 is outdated and supports VC 2013 and 2015.
v1.5.0 supports both 2015 and 2017 (depending on which VS version compiled it).

When you forked and compiled the repo it worked because master branch is v1.5.0
Buildbot currently compiles with 2015, Appveyor both 2015 and 2017.
https://buildbot.orphis.net/pcsx2/

As for compiling spu2-x, you will need the DirectX SDK to compile it properly.

Not an issue so I will be closing this one. If you still have issues feel free to post here.
