### ISSUE TITLE
Xinput-compatible gamepad not recognised by PCSX2 when it is not an Xinput Pad #0

### ISSUE THREAD

**Issue by isshininu** [PCSX2/pcsx2#2288]
***PCSX2 version:***
latest git as of today (ab44ebd)

***Plugins used:***
Lilypad plugin with the default settings.

***Description of the issue:***
Sometimes Windows (especially Windows 10 https://github.com/PCSX2/pcsx2/issues/2130) changes ID of gamepad (when connect/reconnect, etc) from Xinput Pad #0 to something like Xinput Pad #1 or #2. Basically this is a follow-up of my previous bug-request, now with explicit explanation of origins of this issue.

***How to reproduce the issue:***
Connect/reconnect, there is a chance that ID will changed.

**Comment by FlatOutPS2** [comment]
When it switches to say, XInput pad 2, can't you reassign the controls in LilyPad with that?

**Comment by isshininu** [comment]
Well, i think this is possible, but what happens when pad returns to #0? It all looks like i will have to reassign all controls again? I'll try to catch this moment.

**Comment by FlatOutPS2** [comment]
> Well, i think this is possible, but what happens when pad returns to #0? It all looks like i will have to reassign all controls again? I'll try to catch this moment.

Yes, it would be annoying. But it does mean that LilyPad recognises the controller as it should and that it is purely a Windows issue. I could add a workaround option that if no Pad 0 is detected, Pad 1 or 2 will act as Pad 0, but that could have negative effect when using multiple XInput controllers if left enabled.

**Comment by isshininu** [comment]
Maybe something like that would help?
![168](https://user-images.githubusercontent.com/6324523/35734177-aa24392c-0839-11e8-8c18-08398315595a.png)
A simple selector.

**Comment by FlatOutPS2** [comment]
A selector wouldn't work well here, as XInput Pad 1-3 might be used by Player 2-4. You can already swap bindings between diferent LilyPad pads by rightclicking the in Pad/Type/Bindins box on the general tab. So if your controller switches to XInput Pad 1, you can just swap the bindings between pad 1 and 2 to use XInput Pad 1 controls for Player 1(assuming you still have XInput Pad 1 controls setup for player 2).

**Comment by isshininu** [comment]
![169](https://user-images.githubusercontent.com/6324523/35735021-99eaf462-083c-11e8-9269-6b1cdf68d3cb.png)

You mean this option?

**Comment by FlatOutPS2** [comment]
Yes, that's the option I meant. You will need to add XInput Pad 2-3 controls to the other pads(temporarily enable Port 1 Multitap) in order resolve it when it changed to XInput Pad 2 or 3, as those are bindings are not there by default.

**Comment by isshininu** [comment]
Ok, i will close this issue, reopen if needed.
