### ISSUE TITLE
Removing XPad

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#2293]
***PCSX2 version:***
Up to the latest PCSX2 build.

Another user who used the XPad plugin and had controller issues popped up on the forum:
https://forums.pcsx2.net/Thread-RE-Need-for-Speed-Underground-2-SLES-52725-E

The XPad plugin is still included with the latest v1.5.0 builds, even though the LilyPad plugin offers the same functionality(out of the box XInput controls) as XPad without these issues. So I suggest removing this plugin from being included in PCSX2 builds.

This was discussed before( https://github.com/PCSX2/pcsx2/pull/1699#issuecomment-269562266 ), but nothing has come of it yet.

**Comment by MrCK1** [comment]
Unrelated to this specifically, but it would be nice to remove/move some of the other older stuff to legacy to prevent it from being included in the Github search.

**Comment by lightningterror** [comment]
If there are no downsides and Lilypad is superior then go for it.
Btw it's been ages since XPad was updated.

**Comment by turtleli** [comment]
Probably can be removed from the solution IMO. Any volunteers?

**Comment by MrCK1** [comment]
I could possibly do it at some point. 🤞 - Hopefully I get no more merge conflicts
