### ISSUE TITLE
Trivial pursuit : Broken up-left part of the screen under hardware mode

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2296]
***PCSX2 version:***
1.5dev 2266

***PCSX2 options:***
All default, speedhacks don't change the issue.

***Plugins used:***
All default

***Description of the issue:***
The upper-left part of the screen is completely broken under any hardware render look:

![capture](https://user-images.githubusercontent.com/26351275/35820298-77f1744c-0aa5-11e8-95f4-003e77b97b22.PNG)

Note: Software mode is fine
Note2: OpenGL and DX backend show the same issue, I try various hacks but nothing succed
Note3: Can be related to this https://github.com/PCSX2/pcsx2/issues/1318

***How to reproduce the issue:***
Load "Trivial pursuit" in a GSDX hardware render.

***Not a regression***

***PC specifications:***
Intel core I5 3230m AMD radeon hd 7600m Windows 10 64bit

***GSDUMP***
https://drive.google.com/file/d/1H7P73kpWmAtibZCOnsssI6ZQG98zXFHK/view?usp=sharing

**Comment by MrCK1** [comment]
@atomic83Github You should really include the specific 1.5.0 revision in your issue for future reference. We could be on 1.5.0 for another year for all we know ;)

**Comment by lightningterror** [comment]
A re upload of the gsdump would be nice, preferably on github.

**Comment by Mrlinkwii** [comment]
a GS Dump of the issue [issue_2296.zip](https://github.com/PCSX2/pcsx2/files/10202282/issue_2296.zip)
