### ISSUE TITLE
X-Men Origins - Wolverine - Audio Looping causes hang

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#2301]
As reported here on the forum: https://forums.pcsx2.net/Thread-X-Men-Origins-Wolverine-SLUS-21880-Crash

Audio loops causing the game to freeze at the end of the level waiting for the audio to finish.

Can be fixed with a hack doing the following 

If I modify the LoopStartA writes in spu2sys.cpp line 1069 and 1076 adding
```
if (thisvoice.ADSR.Value == 0) //Only way I can tell if a voice is stopped currently
                thisvoice.NextA = thisvoice.LoopStartA | 1;
```
So the game is attempting to set the loop start when the voice isn't active (in some way) but it isn't being actioned by the plugin, possibly because it's setting all the looping to off when the voice starts.

Of course this is a hack currently and should probably be looked in to properly, just putting it here so we don't forget.

**Comment by refractionpcsx2** [comment]
This also affects Madagascar 2 https://forums.pcsx2.net/Thread-SPU2-X-compatibility-issue-in-Madagascar-2

**Comment by rcaridade145** [comment]
@refractionpcsx2 any chance its related to this https://github.com/jpd002/Play-/commit/faa076737c632213983d05e232dbcee2241d2528

**Comment by refractionpcsx2** [comment]
No that's something different. This is to do with the handling of the loop position registers while the voice is active u believe

**Comment by refractionpcsx2** [comment]
I believe * I wish they'd let you edit on the mobile version damnit.

**Comment by rcaridade145** [comment]
Was just trying to help by looking for similar issues.

**Comment by mirh** [comment]
SPU throttle if any, seems related to spu2-x delay cycles of #2315?

**Comment by atomic83GitHub** [comment]
As a test case, this hack break ONI voices.

**Comment by refractionpcsx2** [comment]
I think this is possibly fixed on latest master now, can you please test?

**Comment by atomic83GitHub** [comment]
That should be fixed in master, as it is for madagascar 2

**Comment by refractionpcsx2** [comment]
I did try it here and it seemed okay, dunno if the guy on the forum can test it.

**Comment by refractionpcsx2** [comment]
Closing this as I think it's fixed.
