### ISSUE TITLE
- Coded as +

### ISSUE THREAD

**Issue by Huud** [PCSX2/pcsx2#2305]
In "FixedPointTypes.inl" the - and -= operators are coded to function as a + and += ones respectively:

[https://github.com/PCSX2/pcsx2/blob/259521ec3e46fc5ff4598d182bdea86c8b5262b6/common/include/Utilities/FixedPointTypes.inl#L52
](https://github.com/PCSX2/pcsx2/blob/259521ec3e46fc5ff4598d182bdea86c8b5262b6/common/include/Utilities/FixedPointTypes.inl#L52
)

Is this an error, or is the right.Raw sign set elsewhere or something?

**Comment by gregory38** [comment]
It feels like a bug. I guess it isn't used but it should likely be fixed.

**Comment by ramapcsx2** [comment]
100% a bug, yeah.

**Comment by refractionpcsx2** [comment]
Have we actually used them anywhere? I'm surprised there hasn't been huge issues. But yeah, that's a bug..

**Comment by MrCK1** [comment]
Only place the file is used is in is this https://github.com/PCSX2/pcsx2/blob/02861fabc8adc0bd420562708f6499dccee9981f/common/src/Utilities/IniInterface.cpp#L17

Whatever remaining contents are actually used could possibly be moved there as well.

**Comment by Huud** [comment]
No, I do not think it is used. I went through every Fixed100 and none of them had a subtraction operation without being cast into a float first. It does not fix or break anything when fixed from my testing, that's why I didn't report this when I first found it 2 years ago, but I stumbled upon it again and wanted to make sure.

Here's the pull request of the fix if it is a bug:

https://github.com/PCSX2/pcsx2/pull/2313

**Comment by gregory38** [comment]
Trick and tips: comment the minus operator code overload. If code compiles fine, it means it is unused

**Comment by Huud** [comment]
Ah, nice, it's not used then, even the addition is not used.

**Comment by lightningterror** [comment]
I'll close this since #2313 got merged.
