### ISSUE TITLE
Ransomware on the pcsx2.exe file???

### ISSUE THREAD

**Issue by stevenwnt** [PCSX2/pcsx2#2308]
***PCSX2 version:***
PCSX2 1.5.0-20180208155600

***Description***
![from windows defender](https://user-images.githubusercontent.com/36431565/36132023-e59573ac-1042-11e8-9c32-1e0379247a8b.PNG)
I Don't Know if this is a bug from windows defender or if there was Ransomware on the pcsx2.exe file from your emulator but I have used this emulator on a lot of my ps2 games and there is nothing out of the ordinary well until now but I'm going update this emulator now from here on git hub but this version PCSX2 1.5.0-20180208155600 I got from here too I just figure I would let you guys know that's all if there's any other info you guy need to know I'm happy to help

***PC specifications:***
[https://pcpartpicker.com/list/MXGFBm](url)
CPU: Intel - Core i5-4690K 3.5GHz Quad-Core Processor  ($361.74 @ Amazon) 
CPU Cooler: CRYORIG - M9i 48.4 CFM CPU Cooler  ($17.99 @ Newegg Marketplace) 
Motherboard: ASRock - Z97 EXTREME4 ATX LGA1150 Motherboard 
Memory: Mushkin - ECO2 8GB (1 x 8GB) DDR3-1600 Memory  ($68.89 @ OutletPC) 
Storage: Crucial - BX100 250GB 2.5" Solid State Drive  ($139.78 @ OutletPC) 
Storage: Toshiba - 2TB 3.5" 7200RPM Internal Hard Drive  ($73.50 @ Amazon) 
Video Card: Gigabyte - GeForce GTX 960 4GB Video Card 
Case: NZXT - Source 210 Elite (Black) ATX Mid Tower Case 
Power Supply: SeaSonic - S12II 520W 80+ Bronze Certified ATX Power Supply  ($29.99 @ Newegg) 
Optical Drive: Lite-On - iHDS118-04 DVD/CD Drive  ($15.89 @ OutletPC) 
Total: $707.78

**Comment by MrCK1** [comment]
Another user informed us about this earlier today. The PCSX2 exe was submitted to Microsoft and cleared successfully a few hours ago. It should be removed from the Windows Defender database within a week or so when the next batch of Defender definitions are released.

Thanks for the info anyways. I'll close this for now ;)

**Comment by TriHydera** [comment]
Submit to other avs too
