### ISSUE TITLE
SPU2-X: Project Zero II audio stuttering

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#2314]
***PCSX2 version:***
v1.5.0 2286

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Audio stutters or plays too fast when characters speak during gameplay (does not seem to affect cutscenes/FMV). 

***How to reproduce the issue:***
Play the game. In certain locations the voices will stutter and/or play too fast. Also seems to affect Project Zero III/Fatal Frame III based on mention of bug [here](https://wiki.pcsx2.net/PCSX2_Documentation/Google_Code_svn_repository_comments_archive_5000_to_5499).

***Last known version to work:***
PCSX2 v1.1.0 r5403

This is a regression caused by [this](https://github.com/PCSX2/pcsx2/commit/7dc3b25ddf5ae789bc0c897866eaf6af0c35cdef) commit by @sudonim1 

EDIT: Link to SPU2-X plugin build with regression removed: [Custom SPU2-X plugin](https://forums.pcsx2.net/attachment.php?aid=65729)

**Comment by pgert** [comment]
Thanks for you special build of Spu2-X.
It sure simplifies things for PZ2, and PZ3 runs much better with recent versions of pcsx2\GSdx.

May I suggest that you put up a download-link for the plug-in here for the time being?
If nothing else it's useful for comparisons.

**Comment by FlatOutPS2** [comment]
> May I suggest that you put up a download-link for the plug-in here for the time being?
If nothing else it's useful for comparisons.

I've added the link. Hopefully it won't be necessary for long.

**Comment by atomic83GitHub** [comment]
Is it still an issue now?

**Comment by refractionpcsx2** [comment]
yes

**Comment by pgert** [comment]
Yes it is, furthermore g551847411 is the last version of pcsx2 that supports the custom version of the SPU2-X plugin by FlatOutPS2 posted above.

**Comment by Mrlinkwii** [comment]
is this still an issue on lastest 1.7  ?

**Comment by refractionpcsx2** [comment]
yes
