### ISSUE TITLE
CMAKE_BUILD_TYPE=RelWithDebInfo means Devel

### ISSUE THREAD

**Issue by Vogtinator** [PCSX2/pcsx2#2319]
***PCSX2 version:***
git master as of now (c1fd015)

`CMAKE_BUILD_TYPE=RelWithDebInfo` is not treated like `Release`:

`-- BuildType set to Devel by default`

**Comment by gregory38** [comment]
Yes, only debug/devel/release are supported. Maybe we could add others value.

**Comment by lightningterror** [comment]
I'll close this since it's not an issue.

Otherwise it can be opened again.
