### ISSUE TITLE
Blue message in the console won't appear when using when using "full boot"

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2321]
***PCSX2 version:***
PCSX2 1.5 2286

***Description of the issue:***
In the console, when you are playing a game (Oni in this example), using full boot will cause some blue message to disappear, when using fast boot, they appear without any issue, here is an example:

With fast boot:
![capture](https://user-images.githubusercontent.com/26351275/36558663-05c4a032-180c-11e8-9e1d-9582be945de3.PNG)

With full boot:
![capture2](https://user-images.githubusercontent.com/26351275/36558674-0d5faf6c-180c-11e8-99aa-6c507fbbe8e4.PNG)

***How to reproduce the issue:***
Load a game in full boot mode and look the console

***Not a regression***

***PC specifications:***
Intel Core I5 3230m AMD radeon hd7600m Windows 10 64 Bit

**Comment by MrCK1** [comment]
That's just the game's internal debug print. As long as the game work's fine it's really not a problem ;)
