### ISSUE TITLE
PCSX2 Freezing in Heatseeker

### ISSUE THREAD

**Issue by MartinBFFan** [PCSX2/pcsx2#2322]
***PCSX2 version:***
Development build v1.5.0-dev-2292-g10ebe1665 (However it was also present in previous builds)

***PCSX2 options:***
Speedhacks : VU Cycle Stealing -1, MTVU, INTC,mVU, Wait Loop Detection
Automatic Gamefixes
Everything else is on default

***Plugins used:***
GSDX 20180222002054 (OpenGL Hardware)
Settings: 
Resolution: Custom (1366x768)
Hardware hacks enabled: Fast Texture Invalidation, Trillinear Filtering, Half-Pixel Offset (Normal- Vertex)

SPU2-X 2018022002054
Default Settings

***Description of the issue:***
PCSX2 seems to freeze when the player doesn't skip the beginning cutscene of the first mission and it freezes everytime the player approaches the islands in the first mission.

***How to reproduce the issue:***
There are 2 ways of reproducing it:
1. Start the first mission and do not skip the beginning cutscene
2. Start the first mission and play through it normally until you reach the islands.

***PC specifications:***
CPU: Intel Core I5-5200U 
GPU: Nvidia 840M 2GB Overclocked 
OS: Windows 7 32 bit

**Comment by FlatOutPS2** [comment]
Can you make a blockdump of the issue?

Start PCSX2, go to the Debug menu and enable "Create Blockdump", then start the game and play until it freezes at the first mission. Then close PCSX2 and go to the main folder where the PCSX2 exe is. The blockdump file should be there. If you use a zip file you should be able to upload it to github directly.
Make sure to disable "Create Blockdump" afterwards.

**Comment by MartinBFFan** [comment]
I cannot sadly make a blockdump. Enabling "Create Blockdump" caused PCSX2 to stop loading BIOS and and plugins and completely reset my settings. Really strange.

**Comment by MartinBFFan** [comment]
I am loading the game directly from DVD

**Comment by MrCK1** [comment]
Disable speedhacks and boot again.

**Comment by MartinBFFan** [comment]
Alright

**Comment by MartinBFFan** [comment]
It worked! Thank you

**Comment by lightningterror** [comment]
So the freezing was caused by playing the game from the dvd and not from an iso ?

**Comment by MartinBFFan** [comment]
Nah. I dunno what caused it, but it was fixed by simply disabling speedhacks and then reenabling them in-game.

**Comment by MrCK1** [comment]
My guess would be VU Cycle Stealing or MTVU. Try both of those individually.

**Comment by MartinBFFan** [comment]
In case you havent noticed, I fixed it.

**Comment by lightningterror** [comment]
Yes but we'd like to know what caused it precisely. It's useful information.

**Comment by MartinBFFan** [comment]
Ah.  I wish I could make blockdumps.
I will try looking into the console and see what it throws at me.

**Comment by FlatOutPS2** [comment]
Just enable MTVU speedhack again and boot the game. If it freezes again, that was causing the issue(there are many games with MTVU issues).

**Comment by MartinBFFan** [comment]
Understood

**Comment by MartinBFFan** [comment]
Yep
It was caused by MTVU

**Comment by MartinBFFan** [comment]
Thanks for the help

**Comment by lightningterror** [comment]
Thanks, that's the info we needed, added to Meta MTVu compatibility list.
