### ISSUE TITLE
Formula One 04: Flickering background textures

### ISSUE THREAD

**Issue by FlatOutPS2** [PCSX2/pcsx2#2323]
***PCSX2 version:***
v1.5.0-dev-2292

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Some textures flicker in the distance.

***How to reproduce the issue:***
Start a race, drive around a track until you see distant textures flickering.
Changing the VU Round Mode slightly affects the flickering, but no setting fixes it.

***Last known version to work:***
None as far as I could tell.

**Comment by MrCK1** [comment]
Can you post a picture? I own Formula One 2001, but I don't recall observing anything like this. IIRC, the game has corruption if Mipmapping (Full) is used.

**Comment by FlatOutPS2** [comment]
> Can you post a picture? I own Formula One 2001, but I don't recall observing anything like this. IIRC, the game has corruption if Mipmapping (Full) is used.

Different games can be different.

**Comment by Mrlinkwii** [comment]
i checked this on v1.7.4923  , i cant get the flicker to happen in both HW/SW, would appreciate  if this can be rechecked
