### ISSUE TITLE
Echo paths being created on win10 rig, not win7

### ISSUE THREAD

**Issue by klyxmaster** [PCSX2/pcsx2#2325]
***PCSX2 version:***
Stable 1.4

installed on my win10 rig.
having folder issues
my pcsx is in root folder of D drive :

d:\$consoles\pcsx2\pcsx2.exe

when I put that in the config of pcsx2 and hit apply i get this:
d:\$consoles\pcsx2\$consoles\pcsx2 <- notice it is duplicating the path

then it ask to make this folder - which I say no.
it does it in the config for everything that requires a path. I deleted the pcsx2 folder and started over with a fresh install - same issue

**not and issue on my win7 rig.**

example BIOS PATH
I type in d:\$console\pcsx2\BIOS 
hit apply
pcsx does this when I hit apply (or OK if you're old school)
D:\$consoles\pcsx2\$consoles\pcsx2$consoles\pcsx2$consoles\pcsx2$consoles\pcsx2\BIOS

Thanks.

**Comment by klyxmaster** [comment]
still does it, I'm prety confident at this stage it's a win10 thing, and win7 was flawless. 
![pcsx2-path-errors](https://user-images.githubusercontent.com/2178722/36635881-3a58e0de-1982-11e8-8b21-7df2b66b1ae2.jpg)

**Comment by klyxmaster** [comment]
may have it solved, not sure if it is pcsx2 or win10, but renaming the folder (getting rid of the "$") and changing to a "_" seem to have did the trick - testing now

**Comment by klyxmaster** [comment]
works - had to revert back to 1.4, was not reading my memcards in 1.5. So with win10 cannot use special chars in folder naming (not normal for most, i wanted the folder to be on top when sorting - underscore works too)

**Comment by FlatOutPS2** [comment]
>may have it solved, not sure if it is pcsx2 or win10, but renaming the folder (getting rid of the "$") and changing to a "_" seem to have did the trick - testing now

Yeah, the $ character will break it. I can reproduce the error on Windows 7. Using special characters in foldernames is not recommended. It can create errors in other apps as well.

**Comment by klyxmaster** [comment]
Thanks, It worked well in 7 though, my other rig(7) is running fine. but its a good habit to break. Glad it was not a "game changer" :-P We can close this one out - thanks for the speedy replies.
