### ISSUE TITLE
Ratchet & Clank 3 - Glitches in light effects in hardware rendering mode

### ISSUE THREAD

**Issue by Programie** [PCSX2/pcsx2#2333]
***PCSX2 version:*** v1.5.0 (1.5.0~git201803020440~ubuntu17.10.1)

***PCSX2 options:*** Default

***Plugins used:***
* GS: GSdx (GCC 7.2.0 SSE2/AVX) 1.1.0 [libGSdx]
* PAD: OnePAD 0 2.0.0 [libonepad]
* SPU2: SPU2-X 2.0.0 [libspu2x-2.0.0]
* CDVD: cdvdGigaherz 0 0.11.0 [libcdvdGigaherz]
* USB: USBnull Driver 0 0.7.0 [libUSBnull-0.7.0]
* FW: FWnull Driver 0 0.7.0 [libFWnull-0.7.0]
* DEV9: DEV9null Driver 0 0.5.0 [libdev9null-0.5.0]

GSdx Config:

* Renderer: OpenGL (Hardware)
* Interlacing: Auto
* Texture Filtering: Bilinear
* Internal Resolution: 8x Native
* Anisotropic Filtering: 16x
* Blending Unit Accuracy: Full
* Automatic CRC Level: Partial
* Mipmapping: Full

Everything else on default.

***Description of the issue:***

In Ratchet & Clank 3 (Up Your Arsenal), light effects have weird glitches:

![image](https://user-images.githubusercontent.com/1206521/36927317-222e1b96-1e7d-11e8-82a5-9661b19d8982.png)

But it does not exist in software rendering mode:

![image](https://user-images.githubusercontent.com/1206521/36927449-f85f5d38-1e7d-11e8-9078-fd761d24c58f.png)

***How to reproduce the issue:***
Start the game, go to some planet which is using light effects (e.g. on Starship Phoenix).

***Last known version to work:*** Never played the game in PCSX2 before

***PC specifications:***
* CPU: Intel i7 7700K
* GPU: Nvidia Geforce GTX 1080
* RAM: 24 GB
* OS: Ubuntu 17.10 (64 Bit)

**Comment by MrCK1** [comment]
Use half-pixel offset. This is a side effect of upscaling.

**Comment by Programie** [comment]
OK, enabling the user hacks and setting Half-Pixel Offset to "Normal" fixes it. Thanks!
