### ISSUE TITLE
[GSDX Hardware] Ratchet and Clank: Broken ending credits

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2336]
***PCSX2 version:***
1.5 dev2321

***PCSX2 options:***
All default.

***GSDX options:***
<img width="274" alt="capture5" src="https://user-images.githubusercontent.com/26351275/37254373-eba6e6b8-253c-11e8-8994-b6f0ae9bfb0f.PNG">

<img width="238" alt="capture000" src="https://user-images.githubusercontent.com/26351275/37254374-efcdabb4-253c-11e8-8961-226b4985907a.PNG">

***Plugins used:***
All default

***Description of the issue:***
At the end of any Ratchet and Clank game you have a succession of screens (with the name of devs).
They are broken in the Hardware render as you can see:
[Hardware]
<img width="698" alt="capture" src="https://user-images.githubusercontent.com/26351275/37254397-6ce4998c-253d-11e8-8e77-908d01aa7790.PNG">

[Software]
<img width="698" alt="capture2" src="https://user-images.githubusercontent.com/26351275/37254401-813e6c82-253d-11e8-83e8-5f228b984b70.PNG">

***How to reproduce the issue:***
Complete a Ratchet and Clank game and look the issue.

***Last known version to work:***
I am currently trying to know if it's a regression, incoming!

***PC specifications:***
AMD fx8350 Nvidia GTX 1060 Windows 10 64bit

***GSDUMP***
https://drive.google.com/open?id=1Mf32P51VlYY9-STpcHetpHFZMwne3Afq

**Comment by tadanokojin** [comment]
Old link is dead. Perhaps @RedPanda4552 or OP has another I can see?

**Comment by tadanokojin** [comment]
Got a dump from @RedPanda4552. It is an invalidation problem similar to #914. Game does EE write to update the background.

**Comment by Dreadmoth** [comment]
Fast Texture Invalidation seems to fix this.

![Ratchet & Clank Credits](https://user-images.githubusercontent.com/8492684/76963868-7300b780-696d-11ea-9c29-9b68f555ab1f.png)

**Comment by Dreadmoth** [comment]
Fast Texture Invalidation (now Disable Partial Invalidation) no longer fixes this issue (after #5562 / 1.7.2384).

Fortunately, Preload Frame Data seems to fix it.
