### ISSUE TITLE
LilyPad configuration file location

### ISSUE THREAD

**Issue by r9guy** [PCSX2/pcsx2#2337]
![capture](https://user-images.githubusercontent.com/9428627/37272471-1db4fee8-25f0-11e8-8f46-fc15dd2aa7d5.PNG)

***PCSX2 version:***
latest git version 432999f

***Description of the issue:***
LilyPad plugin is creating configuration file in PCSX2.exe directory. in portable mode( portable ini erased)
it behaves the same way, thus if the pcsx2.exe is in a folder with Administrator permissions, it fails to write  configuration. 
instead it must create/ modify configuration file in "%UserProfile%/Documents/PCSX2/inis/LilyPad.ini"
also after failed attempt to write settings Apply button becomes inactive, as if it's been success.
if clicked OK, dialog closes without writing anything.

***How to reproduce the issue:***
put pcsx2 in "c:\program files" folder delete portable.ini.
run and configure lilypad.
then finish press Apply or Ok

**Comment by lightningterror** [comment]
Not a real issue, I'd suggest whitelisting pcsx2 in windows defender or any other av that might falsely flag the executable and it's contents, check file/folder permissions as well.

In the future please use the forum for support discussions.
https://forums.pcsx2.net
