### ISSUE TITLE
SPU2-X: Cannot set Output Latency lower than 15ms on Linux

### ISSUE THREAD

**Issue by andr2535** [PCSX2/pcsx2#2338]
***PCSX2 version:***
PCSX2 1.5.0-0 - compiled on Mar  9 2018
From the PCSX2 Daily Builds PPA.

***PCSX2 options:***

***Plugins used:***
Only the SPU2-X plugin is relevant to this issue

***Description of the issue:***
SPU2-X Output Settings Latency cannot be set lower than 15ms on Linux.

This is an issue for the game Klonoa 2, whose sound is very glitchy without setting the latency value to 3ms, which is lower than the current lower bound of 15ms.
I don't know if any other games require this.

***How to reproduce the issue:***
Run PCSX2 under Linux and try to set the Latency under SPU2-X Config to a value less than 15ms.

***Last known version to work:***
No known working version to my knowledge.

***PC specifications:***
	Operating System =  Linux 4.13.0-36-generic x86_64
	CPU name            =  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by MrCK1** [comment]
I can look at this later if I have time. 

As a side note, maybe the 15ms minimum could be eliminated completely on all platforms. I did some tests a while back and there was no audible artifacts/issues when using a 3ms latency with Async Mix (or was it Timestretch?)

**Comment by avih** [comment]
As far as I know, the 15ms minimum is only for the time-stretch output, and I'm willing to bet you cannot hear a difference between 15ms lag and and 3ms lag.

There's a reason the default is way higher than 15ms, and it's because PCSX2 just cannot maintain stable and click-free audio with a too-small buffer.

My guess is that you make some wrong assumptions or fail to identify the issue.

Smaller buffer can only create more audible clicks and make the audio-speed less stable. The bigger the buffer - the more stable and clean the audio is, albeit with higher latency. That's the tradeoff.

In the highly unlikely case that the timestretcher (or some other mode) produces cleaner audio with smaller buffer - please report it as an issue.

But the fact that you cannot reduce the minimum to 3ms is not a bug nor an issue.

**Comment by MrCK1** [comment]
@andr2535 What Synchronization mode are you using in SPU2-X - Timestretch, Async or None? As avih said, only Timestretch requires a 15ms latency; but the other 2 modes allow you to use 3ms.

**Comment by andr2535** [comment]
I use Async Mix, but I'm not allowed to set it below 15ms.
This only occurs with the Linux binary,
so if you use the Windows executable it is possible to set below 15 ms.

**Comment by lightningterror** [comment]
The way I see it is TS and Async share the min value slider on Linux. Windows has the minimum value separated.

> static const int LATENCY_MIN = 3;
> static const int LATENCY_MIN_TS = 15;

**Comment by mirh** [comment]
Can you try portaudio JACK backend?

Also.. I too had problems in windows with directsound below a certain threshold. 
Will also check later today how low I can get with ASIO.

**Comment by andr2535** [comment]
I think lightningterror is right, when looking in the Linux Config [https://github.com/PCSX2/pcsx2/blob/master/plugins/spu2-x/src/Linux/Config.cpp](https://github.com/PCSX2/pcsx2/blob/master/plugins/spu2-x/src/Linux/Config.cpp) 
a variable is set to "static const int LATENCY_MIN = 15;"
In the Windows version there is two variables with different minimum values.

@avih The issue that the lower latency is supposed to fix is the workaround
"Missing Sound" described here [https://wiki.pcsx2.net/index.php/Klonoa_2:_Lunatea's_Veil](https://wiki.pcsx2.net/index.php/Klonoa_2:_Lunatea's_Veil)
I don't know why this setting fixes the problem, but it most definitely fixes the issue on the Windows version.
I cannot test if it will fix it on the Linux version since I cannot move the slider below 15ms.

@mirh Changing the backend doesn't seem to have any effect on the latency slider.

**Comment by gregory38** [comment]
Yes code is different on linux vs windows which it isn't normal.

**Comment by avih** [comment]
> @avih The issue that the lower latency is supposed to fix is the workaround
> "Missing Sound" described here https://wiki.pcsx2.net/index.php/Klonoa_2:_Lunatea's_Veil
> I don't know why this setting fixes the problem, but it most definitely fixes the issue on the Windows version.

This is weird, and also not very clear what actually fixes the issue. Here's what this page says about this issue:

> Description: Some areas have no music and sound effects are missing completely.
> Workaround: Go to Config > Audio (SPU2) > Plugin Settings, and set latency to 3 ms. This can cause skipping, so set Synchronizing Mode to "TimeStretch"(start the game with "Async Mix", then switch to "TimeStretch" on the title screen).

So it suggests to start with 3ms with async-mix,  and at the title screen change to timestretch. However, the minimum with timestretch is 15ms also on windows. So I don't quite get it.

Regardless though, if async-mix allows 3ms on windows, then it should probably also allow 3ms on linux.

But no way timestretch can work with 3ms - its minimum is 15ms on all systems and 15ms only barely works and only if the stars align and with a decent system.

**Comment by mirh** [comment]
Just realized that we aren't talking about latency in portaudio settings, but the one in the main spu2-x menu. 
Anyway, if I set synchronization to "none" I can get as down as 2ms with very seemingly no issues (with exclusive wasapi and asio, over portaudio). 

In other news, I found out a very funny bug: async-mix was fucking up the cd player functionality I used to do these testings. Should be worth a separate ticket? Or maybe it can be considered related to klonoa.

**Comment by MrCK1** [comment]
You mean the CD player in this BIOS, how so? It works, it just requires EE cyclerate set to -2 and IOP to interpreter - works fine most of the time with a little luck. Only thing I ever noticed was that you have to leave the emulation window alone - clicking on any PCSX2 window seems to trigger an interrupt or something that stops the audio.

**Comment by mirh** [comment]
I didn't have to touch any of the default settings. Speedhacks are even disabled tbh. 
And I found out that when you use async-mix, the player only plays the first few seconds of a song, then skip it. 
I change to none, or time stretch, and everything goes fine.

**Comment by ramapcsx2** [comment]
That description to fix the Klonoa bug probably does the latency steps for no benefit. Latency (should) only affect the output stream that you directly hear, with no effect on the emulation that generates it.
So what probably actually fixes the bug, is use async mixing. That will change internal timings and depending on your setup, may fix stuff or make it worse.

**Comment by andr2535** [comment]
I have just recorded a video on a Windows 7 computer that shows the issue and the fix.
[https://www.youtube.com/watch?v=AcQFlnIzY-U](https://www.youtube.com/watch?v=AcQFlnIzY-U)
I record the 15ms first and the 3ms begins at 2:25
Sometimes it does work using 15ms latency, but usually it does not.
When using 3ms it has never failed for me.

**Comment by mirh** [comment]
> So what probably actually fixes the bug, is use async mixing. 

If that was to be the case, then that'd be quite of a test case given for me it's instead breaking stuff.

**Comment by ramapcsx2** [comment]
That's the nature of async mixing. It mixes with no regards to emulation time, only with real time.
Any kind of bug behaviour will change depending on your CPU load, for example.
That it can work with async tells us just one thing: There is probably a SPU2 timing issue. Not much, I know ;)

**Comment by ramapcsx2** [comment]
In Klonoa's case, it is 99% surely the DMA draining speed that randomly makes it work.
If you use a devel SPU2-X build, you can enable the visual debugger. You can see how the game never stops "DMA'ing" data into SPU2 RAM, far too much data actually, so it overflows and breaks.
If you hack it into working, the DMA period will stop quickly.
It is probably the old SPU2 DMA timing issue, so an issue where the 2 sides get out of sync on what the current state is.
