### ISSUE TITLE
Harry Potter and the Order of the Phoenix Z-Clipping Textures

### ISSUE THREAD

**Issue by Spyro201** [PCSX2/pcsx2#2339]
***PCSX2 version:*** 
v1.5.0-dev-2321-g432999fae

***PCSX2 options:***
-Defaults

***Plugins used:*** 
GSDX, Lilypad, SPU2-x, cdvdGigaherz, USBNull
-All default settings used.

***Description of the issue:*** 
Several textures in Harry Potter and the Order of the Phoenix seem to Z-Clip with other textures. Noticeable examples would be the paintings in the grand staircase, or some papers on the standing mirror in the Room of Requirement.
![gsdx_20180312141514](https://user-images.githubusercontent.com/37311444/37311211-b946006a-2603-11e8-8f41-77a5f0867912.png)
![gsdx_20180312141613](https://user-images.githubusercontent.com/37311444/37311225-c5cc50a0-2603-11e8-9232-edeea8531e57.png)
Another area is a rectangle near the halls heading to the Room of Requirement on the 7th floor.
![gsdx_20180312141454](https://user-images.githubusercontent.com/37311444/37311258-e0bbf262-2603-11e8-9476-690b499c281d.png)

***How to reproduce the issue:*** 
Start up the game, and get to the areas listed in the description. The paintings can be a bit fiddly, and the papers on the mirror can stop clipping when closer to them. The rectangle on the other hand consistently clips unless using the observation mode.

***Last known version to work:*** 
I'm not entirely sure if it's a problem in older versions, but it's been around since at least July of last year.

***PC specifications:*** 
CPU: Intel Pentium G4560 GPU: EVGA GTX 1050 OS: Windows 10 64 Bit

***Other comments***
-I'll also leave this [GS dump](https://drive.google.com/file/d/1pbjbbHNDusCGdLYeEa2v-tOyiSNC7viU/view?usp=sharing) just in case it can help in any way.
-I've tried various different settings and nothing changed at all. I've also tested it on a PS2 using component cables and saw no Z-Clipping at all in said locations.

**Comment by MrCK1** [comment]
"July of last year" is a bit vague, did you also try 1.4.0 to see if the issue is present there?

Also, you didn't mention which GSdx renderer you are using. Try fiddling around with EE/VU rounding to see if it improves at all (it probably won't help much)

**Comment by Redspyro99** [comment]
So I tried version 1.4.0, 1.2.1 and 1.0.0 and they all had the issue. I made sure to keep the settings the same and used the SSE41 GSdx renderer in them. I used the GSdx SSE4.1/SSE41 1.1.0 renderer in the latest release. The EE/VU rounding didn't do anything unless I messed up somewhere with them.

**Comment by lightningterror** [comment]
Did you try with mipmapping turned on ? What about GSdx hw hacks ?

On a side note this issue seems similar to the GT4 advertisements that automatically switch, basically all of the z clip each other.

**Comment by Redspyro99** [comment]
I've been using mipmapping to fix other texture glitches in the game, but has no effect on the z-clipping. I've also tried enabling most of the GSdx hw hacks and they don't do much. One of them even seems to make it worse. Although I could have messed something up somewhere with the hacks.
