### ISSUE TITLE
BIOS detection/selection broken?

### ISSUE THREAD

**Issue by jedcooper** [PCSX2/pcsx2#234]
Hello,

my first entry here on github...
for the last two days master branch i got same issue with bios files recognition. in pcsx2 binaries it's no problem.
compiled with wx2.8 and wx3.0, release and devel 
on linux xubuntu 14.04 latest gcc/libs etc. from distribution 32 bit in a VM 
for linuxmint 17 14.04 64bit (same libs like above installed, 32bit) no problem with libs so far, as i can see
when selecting bios folder and want to refresh the list afterwards it doesn't recognize any bios. with all other binaries it's working. so i just cannot add any bios.
lots of warning though while compiling.

regards
jc

ps: let me know what else information you'd need

**Comment by bositman** [comment]
Is this still occurring? Please test the latest revision and report back

**Comment by gregory38** [comment]
First report is not clear. Maybe a transient issue due to the wx3.0 porting. I will close the bug. If the issue is still here. Please reopen it.
