### ISSUE TITLE
Perfomance on linux

### ISSUE THREAD

**Issue by Isakku** [PCSX2/pcsx2#2340]
***PCSX2 version:***
***Plugins used:***
***PC specifications:***

From PCSX2 Log:
PCSX2 1.4.0-0- compiled on Jan  6 2016
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Linux 4.13.0-32-generic x86_64
	Physical RAM     =  11932 MB
	CPU name         =  Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  2.292 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins...
	Binding   GS: /usr/lib/games/PCSX2/libGSdx-1.0.0.so 
(GameDB) 9693 games on record (loaded in 184ms)
	Binding  PAD: /usr/lib/games/PCSX2/libonepad-1.1.0.so 
	Binding SPU2: /usr/lib/games/PCSX2/libspu2x-2.0.0.so 
	Binding CDVD: /usr/lib/games/PCSX2/libCDVDnull.so 
	Binding  USB: /usr/lib/games/PCSX2/libUSBnull-0.7.0.so 
	Binding   FW: /usr/lib/games/PCSX2/libFWnull-0.7.0.so 
	Binding DEV9: /usr/lib/games/PCSX2/libdev9null-0.5.0.so 
Plugins loaded successfully.

***PCSX2 options:***
Everything is on the "Safest" level.

***Description of the issue:***
``(What's the problem? - It's quite horrible sound, in fact I can't call it a sound output at all.
No matter what options I tweak, the sound is always full of crackle and it doesn't matter what game I try either. On the same machine (I'm dual booting) on Windows 8.1 a somewhat older version of PCSX2 (1.2.1) runs perfectly, I can play and the sound is just fine. 

I have tried adjusting the latency and all available settings.
PortAudio sound quality was worse by far than the SDL Audio.
PortAudio is just crackle and noise, I can't call that a sound output.
On the other hand the cracle in SLD audio is still unbearable.  
moving all the latency settings only changes how delayed a crackle is from another.

The machine is fairly new, so, it's just an issue that only happens to me on linux. but only when installing from PPA. Flatpacked version works almost as good as Windows version (except rom a single game that gets stuttering sound). 
It's just the PPA | downloaded version.

***How to reproduce the issue:***
I simply installed it through PPA (I think I also tested downloading the linux tar.gz available at the official website) 
and tried to play some games on my linux Mint 18.3 Cinnamon (later I installed it using Flatpak on my Linux Mint 18.3 KDE yes I have two versions of that distro besides of Windows 8.1 on this laptop)

***Last known version to work:***
I don't know. even an older version (1.21) does work just fine on Windows. The same version as in Mint Cinnamon but flatpacked also works completely fine on this same laptop on Linux Mint KDE.
All this just indicates me that everything seems fine when flatpaked (except for a little stutter on a single game that is not there on Windows) Then again even if it works much better flatpacked, I think I should report it anyways because other PCSX2 versions (non winodws nor flatpak) have very very bad sound

I had posted about this on the forums too,
https://forums.pcsx2.net/Thread-Perfomance-on-linux-mint
 but I think this is definitely something that should be analyzed by the developers.

**Comment by lightningterror** [comment]
Did you try 1.5 builds ?
https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by lightningterror** [comment]
I'll be closing this since there's already a discussion on the pcsx2 forum and this isn't a real issue.

**Comment by Isakku** [comment]
The fact I had not tested the 1.5 builds doesn't mean this is indeed happening on PCSX2 1.4. Just give me some time I will try to test the 1.5 builds and if this problem is not present there, then you can say this isn't a real issue.

**Comment by gregory38** [comment]
I don't understand of if your issue is performance or sound.
Multiple bugs were fixed in recent version on portaudio and SDL 2

**Comment by lightningterror** [comment]
> Besides 1.4 is supposed to be the "stable" version that anyone would install.

It's quite the opposite, we tell people to install the 1.5 builds because 1.4 is ancient at this point (2 years old).
Check 1.5 and see if it's fixed there, if not then it could be an issue.
