### ISSUE TITLE
Shellshock 'Nam 67: Constantly Filling mVU1 Program Cache

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#2346]
***PCSX2 version:***
v1.5.0-dev-2325-g40f7d6c95 

***PCSX2 options:***
Defaults, OGL HW

***Plugins used:***
GSDX SSE2, Defaults

***Description of the issue:***
The game will constantly fill up the VU program cache until the emulator stops to empty it.

***How to reproduce the issue:***
Go in-game, walk around or spin in circles :P

***Last known version to work:***
Never

***PC specifications:***
Windows 10 64-Bit Home, GTX 1070, i5-6600K

Notes: 
- Scarface I Bit hack does not work here.
- Based on this [commit](https://github.com/PCSX2/pcsx2/commit/a4afe629e58b7876b48affd6ffd9264db15f7f65) message, Killzone may do something similar - as both games are developed by Guerilla Games.

**Comment by MrCK1** [comment]
@refractionpcsx2 Would it be possible to make a hack for the T-Bit that works similar to the Scarface hack?

**Comment by refractionpcsx2** [comment]
Potentially, if it is the same issue. It could be doing something different in the VU program but to the same affect

**Comment by MrCK1** [comment]
@refractionpcsx2 In the meantime, here's a blockdump if you ever get a chance to look at it. (rename to .7z)

[Nam67_Dump (2018-02-26 22-09-23).zip](https://github.com/PCSX2/pcsx2/files/1850131/Nam67.2018-02-26.22-09-23.zip)

The dump worked fine for me, but I'm including this savestate just incase. (rename to .p2s)
[SLUS-20828 (38BD8D2E).00.zip](https://github.com/PCSX2/pcsx2/files/1850137/SLUS-20828.38BD8D2E.00.zip)

**Comment by MrCK1** [comment]
Me and Ref have determined that too many instructions are being changed for a fix to be made for this, it is significantly different from Scarface's situation.
