### ISSUE TITLE
Klonoa 2: Lunatea's Veil - Stuck in an IPU infinite loop

### ISSUE THREAD

**Issue by PSI-Rockin** [PCSX2/pcsx2#2349]
***PCSX2 version:***
``v1.5.0-dev-2230-g0e83b89db``

***PCSX2 options:***
Automatic Gamefixes enabled. Both EE/IOP interpreter and recompiler cause this issue.

***Description of the issue:***
NOTE: This issue only seems to happen on Windows systems.
NOTE2: I do not have the game for testing, someone else reported this issue. I examined the disassembly to determine the cause (and temporary solution) of this issue.

The game hangs on a black screen when loading the level Volkan City Inferno. The cause of this is due to a loop that checks bit 31 of the IPU_CTRL register (`0x10002010`). Bit 31 is a "BUSY" bit that indicates that the IPU is executing a command.

Here is a screenshot of the disassembly:

https://media.discordapp.net/attachments/315544036184293386/427207079162413060/unknown.png?width=972&height=1004

The game remains stuck indefinitely between `0x00305BB8` and `0x00305BCC`. Likely a synchronization issue.

If the `bltz` instruction at `0x00305BCC` is patched with a `nop`, the level loads normally. No other issues seem to occur with this patch.

***How to reproduce the issue:***

The below link provides a save file next to the level for convenience.
https://www.dropbox.com/s/ub3sliycovk2aw2/Volkan%20Inferno.zip?dl=0

Loading the level Volkan City Inferno results in the hang. 

***Last known version to work:***
Unknown, if any. The game works on older versions but still experiences this issue.

***PC specifications:***
Operating System: Microsoft Windows 8.1 (build 9600), 64-bit
Physical RAM: 16366 MB
CPU name: AMD FX-8350 Eight-Core Processor
Vendor/Model: AuthenticAMD (stepping 00)
CPU speed: 4.017 ghz (8 logical threads)
Graphics card: Gigabyte Nvidia GTX 1050Ti WF2 OC 4GB GDDR5

**Comment by ssakash** [comment]
#2363

**Comment by lightningterror** [comment]
Can this be closed since a workaround/patch was added or are we gonna leave it open ?

**Comment by PSI-Rockin** [comment]
I would recommend leaving it open so that a permanent solution can be found in the future. It's the team's call to make, however.

**Comment by ssakash** [comment]
I'd prefer to leave it open till a proper fix is made.

**Comment by turtleli** [comment]
Fixed.
