### ISSUE TITLE
AMD - SSO crash workaround

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2362]
As Gregory requested so we don't forget about it.

Currently Citra added a workaround for the amdfail driver that fixes the crashing caused by SSO.
The commit is located here https://github.com/citra-emu/citra/pull/3499/commits/0cf6793622b01f3941fbc77fe04c3b68476004ca

Reddit post:
https://www.reddit.com/r/emulation/comments/88vva4/citra_on_twitter_new_update_to_the_hardware/

Idea would be for this to be checked out and maybe implemented.

Some useful info

> You unbind everything so you pay extra invalidation
> What we need to do is
> Create a pipeline by shader combination
> So you only bind once stage to a pipeline
> And then we bind and rebind pipeline
> But I'm not sure it will fix the crash
> Potentially citra workaround might not work on ours side.

**Comment by mirh** [comment]
Any gs dump that can trigger this issue?
I don't remember any crash with recent drivers.

**Comment by lightningterror** [comment]
Here you go
https://drive.google.com/open?id=1kuA_B_H3wrG1z88yMQE3qtRor7YPsSHS
Btw I'm on 18.3.3

**Comment by mirh** [comment]
FFS, almost killed my session. 
That's again the "avoid *none* blending accuracy" crash. 
I thought they had ""fixed"" it?? 
Now we have broken SSO, and crashy blending. :|

**Comment by lightningterror** [comment]
It's been like this since March last year.

> Now we have broken SSO, and crashy blending. :|

Just broken SSO in general.

**Comment by mirh** [comment]
> It's been like this since March last year.

17.2.1 fixed it.. Then *???* broke it again?
Why do we have nothing about it?

> Just broken SSO in general that can cause a crash and corrupt graphics.

Broken SSO is the garbled/wrong graphics. Yellow instead of green in the test case. 
The BSOD is separate, for as much as connected, of it.

**Comment by mirh** [comment]
I'm not talking about different pcsx2 versions. 
The "milestones" for me were drivers. 
They are very connected if fixing 1 meant introducing 2... But they can't be the same thing if BSOD happens both with, and without the SSO fix. 
And, I mean, I think I had quite tested `override_GL_ARB_separate_shader_objects` too. 

I guess I'll have bump the TDR thread then... once I find the time to save my stuff and try which driver added back this shite.

**Comment by lightningterror** [comment]
override_GL_ARB_separate_shader_objects is removed on 1.5 
The workaround on 1.5 doesn't disable SSO, it just adds a workaround for it to fix the corrupt graphics.
The workaround on 1.4 completely disabled SSO.

**Comment by lightningterror** [comment]
I'll close this in favor of https://github.com/PCSX2/pcsx2/issues/2362
Added the info in that issue instead.

**Comment by mirh** [comment]
#1552 you'll mean?

**Comment by lightningterror** [comment]
Oops, wrong copy paste.
