### ISSUE TITLE
Crash Twinsanity Model Incorrect on SSE4.1/AVX compared to AVX2/AVX2

### ISSUE THREAD

**Issue by Kristijan1001** [PCSX2/pcsx2#2365]
Tested on PCSX2 v1.5.0-dev-2120-g07c69eb and PCSX2 v1.5.0-dev-2338-g0e39caaad:

If anyone has an idea to fix this please comment !

Plugin used:
AVX2/AVX2

![](https://i.imgur.com/TfpMKOc.png)

![](https://i.imgur.com/7TlQwAf.png)

Plugin used:
SSE4.1/AVX

![](https://i.imgur.com/RxJOCxG.png)

![](https://i.imgur.com/1LBOqhG.png)

Description of the issue:
The Issuse is that the model on AVX2/AVX2 is smooth and good looking, while the one on SSE4.1 has bad shadow glitches. I can't use AVX2/AVX2 because my CPU doesn't support it. Which leaves it to having bugged crash all the time and i can't get of my eyes from it.

PC specifications:
CPU: Intel i5 3330 2.4GHz 
GPU: Nvidia GeForce 1050Ti 
OS: Windows 10 64 Bit

**Comment by gregory38** [comment]
Sw or hw renderer ?

**Comment by willkuer** [comment]
How do you know it works properly with avx2 if your cpu doesn't support it? Do you compare your output with screenshots taken from the web with possibly completely different settings?

**Comment by Kristijan1001** [comment]
It's HW Renderer @gregory38 

@willkuer No i just didn't find random screenshots from the web. I took the screenshot my self from a video. There are multiple videos that use AVX2/AVX2 where their Crash Bandicoot doesn't look glitchy. I have the same exact settings as them only difference mine is SSE4.1/AVX and their is AVX2/AVX2. So i went from that assumption.

**Comment by MrCK1** [comment]
Those plugins are almost a year old. Download the latest git build here and see if you still notice issues with the models: https://buildbot.orphis.net/pcsx2/

**Comment by Kristijan1001** [comment]
@MrCK1 omg i am an idiot, i will test out with them and report back. I downloaded the latest version but forgot to apply on my folders...... And went out to test for hours on the old one Facepalm.

**Comment by lightningterror** [comment]
Did you test OpenGL or Direct3D ?

**Comment by Kristijan1001** [comment]
@lightningterror the issue is present in Direct3D Software and Hardware and OpenGL Software and Hardware (I teseted all 4 on SSE4.1/AVX)
I tested all of the plguins (in Direct3D, i assume issuse is there in OpenGL Too) except AVX2/AVX2, I can't test AVX2/AVX2 since CPU doesn't support it. But from the videos i have seen people on AVX2/AVX2 Doesn't seem to have the issuse.

![](https://i.imgur.com/Ev0InNi.png)

Video of where issuse is not happening:

https://youtu.be/kvqefki3lTc?t=250

**Comment by lightningterror** [comment]
I'm not able to reproduce your issue. They both look the same.

![pcsx2 2018-04-06 21-55-39-13](https://user-images.githubusercontent.com/18107717/38441616-a65dc8f2-39e5-11e8-9352-24d009b94eb0.png)
![pcsx2 2018-04-06 21-55-22-33](https://user-images.githubusercontent.com/18107717/38441617-a67d13f6-39e5-11e8-948c-cd192d598f46.png)

**Comment by Kristijan1001** [comment]
@lightningterror can u take a screenshot of the back of crash ? not the front , the front is fine for me too. Also if u dont mind sharing the settings u had if i can produce it without the bugs ?

**Comment by lightningterror** [comment]
avx2
![pcsx2 2018-04-06 22-03-54-14](https://user-images.githubusercontent.com/18107717/38441884-7f69f378-39e6-11e8-9db1-8d806807d81c.png)
sse4
![pcsx2 2018-04-06 22-04-09-52](https://user-images.githubusercontent.com/18107717/38441890-8217779e-39e6-11e8-87a1-6d17833c24a1.png)

Settings are default, except 3x native , large framebuffer off, accurate date on

**Comment by Kristijan1001** [comment]
@lightningterror are you on OpenGL ? Also why does your game look so bright ? I did open gl default i just downloaded new pscx2 and turned off framebuffer and accurate date on, on x3 i still have the same issue. What could this be :\

**Comment by Kristijan1001** [comment]
@lightningterror this is so weird why would it happen.. What kind of GPU/CPU do u have ? Maybe its related to that or some nvidia drivers on my side ? Also i just checked few youtube videos and its defenetly not only me there are other videos that have the same issue i have:

Example:

![](https://i.imgur.com/Yjl9IrP.jpg)



https://youtu.be/_Rgm8mwxPNA?t=176

**Comment by lightningterror** [comment]
intel i3 4160
amd r7 360

**Comment by Kristijan1001** [comment]
@lightningterror  OK, i went through alot of videos and from the looks of it might be the gpu ? Because i found 4 videos with Crash Twinsanity, 2 of them are on 750ti and they both dont have the glitch while the other two have it, me personally i am on 1050ti and still have it, Or it might end up being the cpu ,but we both have simillar cpus i have i5. And i cant check other cpus since only the gpu info is available in the videos. :(

This guy has Nvidia GPU and it happens on his video

**GTX 760 (2GB Galaxy OC edition)**
https://www.youtube.com/watch?v=3M_3HgK3WRU&t=60s
**Nvidia GTX 960**
https://www.youtube.com/watch?v=JWqH__uv-jo

**GPU GTX Nvidia 750ti Doesn't happen for him**
https://www.youtube.com/watch?v=oLLyE664dt8

**GPU Nvidia 750ti Doesnt happen for him either**
https://www.youtube.om/watch?v=kvqefki3lTc&t=17s

**Comment by lightningterror** [comment]
Maybe it's a driver issue ?

**Comment by MrCK1** [comment]
Can one of you upload a GS dump please? (Hold Shift +F8)

**Comment by MrCK1** [comment]
@Kristijan1001 You need to enable Automatic Gamefixes so that the XGKick Hack is enabled. That will fix the issue.

**Comment by Kristijan1001** [comment]
Automatic fixes is already enabled... @MrCK1

**Comment by MrCK1** [comment]
What if you enable the XGKick hack manually in the manual gamefixes tab?

**Comment by Kristijan1001** [comment]
@MrCK1 Holy SHIT , That fixed it THANKS ALOT , The fix should be automated maybe from now on ?  I dunno maybe its not set for the USA version, and works only on the eu version ?

**Comment by MrCK1** [comment]
Looks like you're right ;)

I'll address the issue soon.
