### ISSUE TITLE
Having Speed hack; "EE Cyclerate Set to -1" Causes FMVs to Stutter in some Crash Bandicoot Games.

### ISSUE THREAD

**Issue by Kristijan1001** [PCSX2/pcsx2#2367]
PCSX2 version:

v1.5.0-dev-2338-g0e39caaad

![](https://i.imgur.com/RW8jMtX.png)

Having Speed hack; "EE Cyclerate Set to -1" Causes **FMVs to stutter** in the following games i have tested:

Crash of the Titans
Crash - Mind Over Mutant
Crash Tag Team Racing

The issue **can be fixed** with setting "EE Cyclerate Set to 0" 

![](https://i.imgur.com/sqMPlgh.png)

Plugins used:

D3D 11 Hardware Mode

![](https://i.imgur.com/BUyF63B.png)

PC specifications:
CPU: Intel i5 3330 2.4GHz
GPU: Nvidia GeForce 1050Ti
OS: Windows 10 64 Bit

**Comment by lightningterror** [comment]
Not a real issue, adjusting the EE Cyclerate can cause issues in some games which is why 0 is the default option.

**Comment by willkuer** [comment]
That's especially true for underclocking (negative values). Just consider how your pc games would suffer from underclocking your cpu/gpu/ram.
