### ISSUE TITLE
LilyPad PSX mode: The plugin is unable to save the settings

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2369]
***ePSXe***

***Plugins used:***
GSDX, LilyPad, ePSXe internal SPU plugin, ePSXe internal CD plugin

***Description of the issue:***
The LilyPad plugin is unable to save the settings, I even try in administrator mode, but this doesn't change anything.

***How to reproduce the issue:***
Load a PSX emu such as ePSXe, select the LilyPad plugin, configure it, save the settings and you will see the issue.

***Last known version to work:***
Don't know yet, incoming.

***PC specifications:***
AMD fx8350 GTX 1060 Windows 10 64bit

**Comment by lightningterror** [comment]
If it works fine on PCSX2 with PSX mode then that's fine.

It's a miracle that GSdx and LilyPad work with ePSXe.

Not an issue anyway.

**Comment by atomic83GitHub** [comment]
Edit, I found a way to solve this, you must create a inis folder in the ePSXe directory and it will save without any issue, and GSDX and LilyPad work wonderfully in ePSXe.
