### ISSUE TITLE
Minor audio glitches in Fatal Fury Battle Archives Vol. 2 (US:NTSC) and possibly Mortal Kombat: Deadly Alliance (PAL)

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#2370]
***PCSX2 version:***

Every build since this commit is affected: https://github.com/PCSX2/pcsx2/commit/f1cffa6f7fd8e85a2d2df35b7c18ca2e4d3606ab#diff-880fcba486dd038bdc85976ae1e9297a

***Plugins used:***

SPU2-X is the only relevant plugin, and it's options have no effect on the issue. No other plugins have any impact and PCSX2's settings also have no effect.

***Description of the issue:***

Minor audio drop outs. In FF Battle Archives 2 certain sounds don't always play, especially on the main menu. This seems to be true in MK:DA too; certain sounds, especially selection sounds, occasionally don't play. This is not the similar effect caused by the audio buffer being set too small.

This problem started years ago with the commit listed above. I've built and tested versions of SPU2-X with that commit reverted and the problem seems to go away (I'm 100% certain for Fatal Fury, 95% for MK).

***How to reproduce the issue:***

Load Fatal Fury Battle Archives 2. At the main menu, rapidly cycle through the games list and before long you'll hear the issue.

MK:DA is similar. If you scroll through the selections at the main menu, the selection sound occasionally doesn't play

**Comment by MrCK1** [comment]
Somewhat related, but what happens if you increase or decrease the DelayCycles value in your SPU2.ini?

**Comment by Silanda** [comment]
Okay, just tested briefly. 

With DelayCycles set to 0 or 1 seems to go away in Fatal Fury. It's not as easy to be sure about MK because it doesn't happen as readily, but 0 or 1 seems to eliminate it there too.

**Comment by MrCK1** [comment]
Thanks for the info, I'm going to close this in favor of #2371 ;)
