### ISSUE TITLE
Crash Twinsanity No Shadows on Direct3D Hardware/Fixing the wall bug infront of you gets rid of the shadows on OpenGL Hardware too !

### ISSUE THREAD

**Issue by Kristijan1001** [PCSX2/pcsx2#2373]
PCSX2 version:

**v1.5.0-dev-2338-g0e39caaad**

**Plugins used:**
![](https://i.imgur.com/4la70Ia.png)

**Description of the issue:**
Issue is present in Crash Twinsanity. The issue is first of all that the game has a wall infront of you, and only disappears if you put SkipDraw to 3. Second issue is that on Direct3D 11 Hardware there are no shadows no matter what. BUT on OpenGL Hardware there are shadows IF you don't put SkipDraw to 3, if you actually do put it on 3 , the wall disappears as along with the shadows.

**How to reproduce the issue:**
1.Load Crash Twinsanity with default settings to reproduce the wall infront of you.

![](https://i.imgur.com/IhbIli6.jpg)

2.Load Crash Twinsanity with Direct3D 11 Hardware to see there are no shadows even with SkipDraw Disabled.

![](https://i.imgur.com/9pd4MKm.png)

3.Load Crash Twinsanity with OpenGL Hardware to see that there are shadows infront of you

![](https://i.imgur.com/qIu08xm.jpg)

4.To fix the wall infront of you you can set SkipDraw on 3, But by doing that you are losing the shadows even on OpenGL Hardware

![](https://i.imgur.com/auygEHC.jpg)

**Last known version to work:**
No known version where this worked...

**PC specifications:**
CPU: Intel i5 3330 2.4GHz
GPU: Nvidia GeForce 1050Ti
OS: Windows 10 64 Bit

**Comment by Kristijan1001** [comment]
@willkuer where is the new skipdraw offset located at ? i cant find it ?

**Comment by willkuer** [comment]
Ah it's not merged so far. Try one build from the artifacts provided by appveyor in the pr by flatout: 

Adds an option called "Skipdraw Offset" to the GSdx Advanced Settings and Hacks submenu.
https://github.com/PCSX2/pcsx2/pull/2290

**Comment by Kristijan1001** [comment]
@willkuer can you like send me complied one i don't know how this really works or where to download that version or how to build one :( ? Also whats the reasoning why the shadows dont show on Direct3D 11 at all even without the skipdraw disabled ? They only show on OpenGL ?

**Comment by MrCK1** [comment]
https://ci.appveyor.com/api/buildjobs/wjfiktn77g2kkou4/artifacts/pcsx2-v1.5.0-dev-2323-g4af22394f-3864-vs2017-Win32-AppVeyor.7z

You don't need to worry about DX11, just use OpenGL because you have an Nvidia card.

**Comment by Kristijan1001** [comment]
I don't think this is working, ive tried setting it 1-3 , 2-3, 3-3 . Shadows are gone in all of them except if both are set to 0 obviously , The only way for the wall bug to be gone is it to be set to 3. I dunno what @willkuer was talking about there are only 2 options for skipdraw there aint a third one.

![](https://i.imgur.com/AuECUl0.png)

**Comment by willkuer** [comment]
I meant exactly what you tried. Basically you need to increase the upper limit of the skipdraw range until you remove all bad artifacts and then increase the lower limit just before they reappear again. If 3->3 does not remove the wall and keep the shadow at the same time both probably originate from the same calculation and thus can not be adjusted independently by skipdraw.

**Comment by gregory38** [comment]
I think the game suffer of the half bottom issue (depth effect on bottom part)

**Comment by legend800** [comment]
So is that a solution to the half bottom issue? Wonder if it fixes Matrix - Path of Neo.

**Comment by MrCK1** [comment]
Skipdraw will generally fix any half-bottom screen issue, but it's a hack and not a permanent solution.

**Comment by legend800** [comment]
Last comment - using the recommended PR (with it set to 4,4) on PoN, half-bottom issue is fixed, but black boxes now appear all over. Changing the range doesn't help. So unfortunately it wasn't able to fully fix the issue, but got closeer. Need actual code changes to address properly and probably the same for Crash Twinsanity.

**Comment by lightningterror** [comment]
> I think the game suffer of the half bottom issue (depth effect on bottom part). Maybe it is related to this issue.

Ah yes it's a half screen bottom issue and I was testing the PAL region.
Perhaps I'll make a crc hack for dx and gl (pal only) ...ugh I don't like crc hacks ...

Closing in favor of #2022 #1339
