### ISSUE TITLE
Mercenaries: Playground of Destruction post-processing issues (SW/HW)

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#2376]
***PCSX2 version:***
1.5.0-20180331005218

***PCSX2 options:***
All defaults. Tested using native and above native resolutions.

***Plugins used:***
GSDX AVX.

GL HW backend.
GL SW backend.

***Description of the issue:***
The GL backend and SW backend both render the game's post-processing incorrectly. The SW backend has horizontal lines through the image.
![gsdx_20180411150121](https://user-images.githubusercontent.com/10704701/38597177-59d5764e-3d99-11e8-8038-7adb5857d991.png)
The GL backend has horizontal banding that changes as the camera moves.
![gsdx_20180411150142](https://user-images.githubusercontent.com/10704701/38597184-6750f528-3d99-11e8-88fb-ee7009d3cc2a.png)

The difference is particularly noticeable in the pause menu:
![gsdx_20180411150602](https://user-images.githubusercontent.com/10704701/38597270-f273b32a-3d99-11e8-8b9c-29bd16ff5404.png)
![gsdx_20180411150608](https://user-images.githubusercontent.com/10704701/38597292-1aae7c4e-3d9a-11e8-86d0-e50e2b4311a1.png)

Enabling the Frame Buffer Conversion hack results in the banding disappearing, but the characteristic post-processing squares appearing at the top-left corner of the screen.
![gsdx_20180411150125](https://user-images.githubusercontent.com/10704701/38597212-a20e4e0e-3d99-11e8-85bc-9d1c0a4e389a.png)
As for the DX backends, they look like this:
![gsdx_20180411150155](https://user-images.githubusercontent.com/10704701/38597220-b461b32a-3d99-11e8-8b3a-414897691955.png)

***How to reproduce the issue:***
The issue is evident during all 3D rendered scenes.

***Last known version to work:***
Unknown.

***PC specifications:***
Haswell i5, GTX 1060, Windows 10.

**Comment by MrCK1** [comment]
@AmbientMalice What GSdx settings did you use?

**Comment by lightningterror** [comment]
Can you upload a gs dump, preferably multiframe.
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by MrCK1** [comment]
I took a look last night anyways, it has a half-bottom issue and depth - so they could be related.

**Comment by gregory38** [comment]
Yes the game suffer of half bottom issue

**Comment by ScharMeister** [comment]
I did some pretty thorough testing for this game. Here are the settings that worked for me:
![mercenaries](https://user-images.githubusercontent.com/38443361/38838039-c81df948-41d4-11e8-9a98-3c13d1732cc3.png)

The screenfix cheat removes the banding, without altering the post processing too much. The fps cheat turns the game into "true" 60 fps instead of "fake" 60 fps with duplicate frames, at the cost of performance. Auto flush helps with the glitchy headlights. Both cheats were tested for the US version. 

Additional settings:
Widescreen patches _OFF_
For audio synchronization either _timesync_ or _nothing_
Enable cheats _ON_

Note that even with all these tweaks, Mercenaries still remains pretty hard to run. That's why I'd recommend turning the 60fps tweak off (with "//") and not putting the resolution too high if you experience slowdowns. 

Let me know if this works for you!

**Comment by FinnYoung** [comment]
I have the same issues with 1.5.0-dev-2242, win10, i7 4790k, gtx980ti
i was trying to use ScharMeister's settings, it didn't help

**Comment by FinnYoung** [comment]
@ScharMeister 
cheat file name: 23510F99.pnach (it has the same content as on provided screenshot)
not sure about region. should be NTSC version, but PS2 ISO MD5 Calculator says its PAL
it's version with RUS subs from Kudos

**Comment by gregory38** [comment]
Pal version will likely suffer of glitches in the half bottom of the screen. Whereas NTSC might be ok.

**Comment by ScharMeister** [comment]
@FinnYoung 
Try renaming the filename to 7ACF7E03.pnach. If that doesn't work, find the proper pnach code by launching the game and searching it in the pcsx2 console.

**Comment by FinnYoung** [comment]
@ScharMeister thank you. Renaming patch to 7ACF7E03 fixed it

**Comment by daninthemix** [comment]
> If anyone wants a workaround for these problems, here are the settings that worked for me:
> ![mercenaries](https://user-images.githubusercontent.com/38443361/38838039-c81df948-41d4-11e8-9a98-3c13d1732cc3.png)
> 
> The screenfix cheat removes the banding, without altering the post processing too much. The fps cheat turns the game into "true" 60 fps instead of "fake" 60 fps with duplicate frames, at the cost of performance. Auto flush helps with the glitchy headlights.
> 
> Additional settings:
> Widescreen patches _OFF_
> For audio synchronization either _timesync_ or _nothing_
> Enable cheats _ON_
> Unlike the screenshot, mipmapping should also be _OFF_
> 
> if you experience slowdowns, it's best to turn off the 60fps tweak and lower the resolution.

These settings do work but I get momentary, second-long pauses on OpenGL, every few seconds which is far from ideal. Direct X is much faster but the only problem remaining on Direct X is shadows have these weird, puppet-like lines connecting them to the object casting them (usually a vehicle).

**Comment by AITUS95** [comment]
> > If anyone wants a workaround for these problems, here are the settings that worked for me:
> > ![mercenaries](https://user-images.githubusercontent.com/38443361/38838039-c81df948-41d4-11e8-9a98-3c13d1732cc3.png)
> > The screenfix cheat removes the banding, without altering the post processing too much. The fps cheat turns the game into "true" 60 fps instead of "fake" 60 fps with duplicate frames, at the cost of performance. Auto flush helps with the glitchy headlights.
> > Additional settings:
> > Widescreen patches _OFF_
> > For audio synchronization either _timesync_ or _nothing_
> > Enable cheats _ON_
> > Unlike the screenshot, mipmapping should also be _OFF_
> > if you experience slowdowns, it's best to turn off the 60fps tweak and lower the resolution.
> 
> These settings do work but I get momentary, second-long pauses on OpenGL, every few seconds which is far from ideal. Direct X is much faster but the only problem remaining on Direct X is shadows have these weird, puppet-like lines connecting them to the object casting them (usually a vehicle).

You must disable anisotropic filtering

**Comment by daninthemix** [comment]
> > > If anyone wants a workaround for these problems, here are the settings that worked for me:
> > > ![mercenaries](https://user-images.githubusercontent.com/38443361/38838039-c81df948-41d4-11e8-9a98-3c13d1732cc3.png)
> > > The screenfix cheat removes the banding, without altering the post processing too much. The fps cheat turns the game into "true" 60 fps instead of "fake" 60 fps with duplicate frames, at the cost of performance. Auto flush helps with the glitchy headlights.
> > > Additional settings:
> > > Widescreen patches _OFF_
> > > For audio synchronization either _timesync_ or _nothing_
> > > Enable cheats _ON_
> > > Unlike the screenshot, mipmapping should also be _OFF_
> > > if you experience slowdowns, it's best to turn off the 60fps tweak and lower the resolution.
> > 
> > 
> > These settings do work but I get momentary, second-long pauses on OpenGL, every few seconds which is far from ideal. Direct X is much faster but the only problem remaining on Direct X is shadows have these weird, puppet-like lines connecting them to the object casting them (usually a vehicle).
> 
> You must disable anisotropic filtering

Thankyou - with AF turned off Direct X is perfect, and much faster than OGL.

**Comment by PoioSeba** [comment]
> 
> 
> If anyone wants a workaround for these problems, here are the settings that worked for me:
> ![mercenaries](https://user-images.githubusercontent.com/38443361/38838039-c81df948-41d4-11e8-9a98-3c13d1732cc3.png)
> 
> The screenfix cheat removes the banding, without altering the post processing too much. The fps cheat turns the game into "true" 60 fps instead of "fake" 60 fps with duplicate frames, at the cost of performance. Auto flush helps with the glitchy headlights.
> 
> Additional settings:
> Widescreen patches _OFF_
> For audio synchronization either _timesync_ or _nothing_
> Enable cheats _ON_
> Unlike the screenshot, mipmapping should also be _OFF_
> 
> if you experience slowdowns, it's best to turn off the 60fps tweak and lower the resolution.

Thanks, the game works great with your config.
The only problem that I have encountered is the videos like in the intro after the character selection. It goes too fast and the audio start to jump/skip to keep the video in sync but If you cap the fps to 30, the video goes without trouble.

**Comment by refractionpcsx2** [comment]
So, about that GS dump we asked for in 2018, any chance we can get that? if it's still an issue

**Comment by RedDevilus** [comment]
The issue is that it needs half screen fix to be force enabled which is added recently.

**Comment by DigitalMajestic** [comment]
No longer an issue, tested on 1.7.4937
