### ISSUE TITLE
GameDB:  Arctic Thunder cannot boot unless 'skipmpeghack=1' is set

### ISSUE THREAD

**Issue by legend800** [PCSX2/pcsx2#2385]
***PCSX2 version:***
PCSX2 1.5.0-20180413164208

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Arctic Thunder cannot boot without 'skipmpeghack=1'. Otherwise, it's just a permanent black screen.

Entry Suggestion:
Serial = SLUS-20217
Name   = Arctic Thunder
Region = NTSC-U
Compat = 5
SkipMPEGHack = 1

***How to reproduce the issue:***
Launch game and observe infinite black screen after the initial splash screen.

***Last known version to work:***
Never

***PC specifications:***
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by MrCK1** [comment]
@legend800 Can you upload a blockdump of the issue by selecting "Create Blockdump: in the Debug menu?

**Comment by legend800** [comment]
Sure, attached.

[Untitled (2018-03-14 21-23-24).zip](https://github.com/PCSX2/pcsx2/files/1911686/Untitled.2018-03-14.21-23-24.zip)
