### ISSUE TITLE
Moire like graphics glitch

### ISSUE THREAD

**Issue by MrLint** [PCSX2/pcsx2#2386]
***PCSX2 version:***
v1.5.0-dev-2345-g230a497a1

***Description of the issue:***
Graphics glitch on Katamari Damacy, a wierd moire line appears in a particular  spot, It appears in 3d space. Took moving to the  right place to capture the picture.

No non normal setup. Vanilla.

***How to reproduce the issue:***
Just played it and came across the issue.

***PC specifications:***
https://valid.x86.fr/dr3kxl

![2018-04-15 11_03_30-slot_ 0 _ speed_ 100 59 71 _ limiter_ normal _ gsdx ogl hw _ 1024x896 _ auto](https://user-images.githubusercontent.com/18565454/38780047-08a435d6-409f-11e8-9992-585a90794886.png)

**Comment by MrLint** [comment]
@MrCK1 Hello yes, i was able to toggle it and it went away.

**Comment by MrCK1** [comment]
OK, and which copy of the game do you have? Can you give me the game serial from the console window?

**Comment by lightningterror** [comment]
That's the crc number, the disc serial is SLUS-21008.

**Comment by MrLint** [comment]
cdrom0:\SLUS_210.08;1

**Comment by MrCK1** [comment]
@MrLint Just a quick test, can you set the Rounding Mode back to normal and change the VU Clamping Mode to Extra + Preserve Sign and see if that fixes the issue or not?

I'm going to make a pull request to get the hack added to the GameDB, so you won't have to set it manually every time ;)

**Comment by MrLint** [comment]
@MrCK1 One moment please SRS option flipping in motion.

**Comment by MrLint** [comment]
Yes extra + preserve sign seems to handle it.

**Comment by MrCK1** [comment]
OK thanks.
