### ISSUE TITLE
RTK IX Wording Are Black Unable To See

### ISSUE THREAD

**Issue by supermario91** [PCSX2/pcsx2#2390]
PCSX2 version:
PCSX2 1.4.0-20160105132032

PCSX2 options:
Defaults, Speedhacks Abled

Plugins used:
GSdx 20160105132032 (MSVC 19.00, AVX) 1.0.0 [gsdx32-avx
LilyPad (20151231175709) 0.11.0 [lilypad]
SPU-2X 20151231175709 2.0.0 [spu2-x]
cdvdGigaherz (20151231175709ll_ 0.9.0 [cdvdGigaherz]
USBnull Driver 20151231175709 0.7.0 [USBull]
FWnull Driver 20151231175709 0.7.0 [FWnull]
DEV9null Driver 20151231175709 0.5.0 [DEV9null]

Description of the issue:
Unable to read the wording of the game as it is in black.

How to reproduce the issue:
When go into the game

Last known version to work:
Don't know

PC specifications:
Operating System =  Microsoft Windows 10 Home (build 16299), 64-bit
Physical RAM     =  8077 MB
CPU name         =  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Graphic = Nvidia GEFORCE GTX 950M

Photos:

![1](https://user-images.githubusercontent.com/38446204/38843432-8be08f2a-4221-11e8-977b-2a61fb6b07fb.jpg)
![2](https://user-images.githubusercontent.com/38446204/38843434-8c5efcde-4221-11e8-82cb-b5ed8a6122aa.jpg)
![3](https://user-images.githubusercontent.com/38446204/38843435-8c92a8b8-4221-11e8-9dd1-ed42e320e9c0.jpg)

These are the example of the issue.

Thank you.

**Comment by MrCK1** [comment]
@supermario91 Download the latest dev build here and see if it fixes the issue: https://buildbot.orphis.net/pcsx2/

**Comment by supermario91** [comment]
Still the same issue. Any ways to solve it?

**Comment by supermario91** [comment]
@MrCK1 Still the same issue. Any ways to solve it?

**Comment by willkuer** [comment]
Have you played with gsdx option? E.g. Increasing blending unit accuracy?

**Comment by supermario91** [comment]
@willkuer My GS is GSdx 20180416162849 (MSVC 19.00 SSE2/AVX) 1.1.0 [GSdx32-SSE2]
So how to sovle this issue?

**Comment by refractionpcsx2** [comment]
Related to #1628

**Comment by refractionpcsx2** [comment]
I wasn't providing a solution, this isn't really a support section, that's what our forums are for, I was merely linking this bug to an existing one we have logged for the same issue.

I think the only thing you can do now is to downgrade to pcsx2 1.0.0, I think it was fine on there.

**Comment by supermario91** [comment]
@refractionpcsx2 Did you know is there any solution for this issue?

**Comment by refractionpcsx2** [comment]
If I did, I wouldn't be linking to an existing issue that's been here for years. I know what caused it, but I don't know how to fix it.
