### ISSUE TITLE
Armored Core 2: Abnormal AI behavior with default EE/FPU clamping mode

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2395]
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
 Default

***Plugins used:***
 Default

***Description of the issue:***
Some enemies will behave completely differently to their console counterpart
The final enemy in the Underground Railway mission will try to fire his primary weapon to no avail only leaving a copy of the muzzle flash effect floating in the air
![gsdx_20180420182832](https://user-images.githubusercontent.com/30066566/39062722-aef8cbb8-44c8-11e8-884e-d0eb679029a1.png)
The helicopters you face during the Escort Submarine mission will often become stationary directly above you.

Both of those can be fixed by setting the  EE/FPU clamping mode to something other than Normal, although setting it to full will cause an issue where sometimes the player AC models will become fullbright and flash back to normal after a while, I have not tested setting it to none but setting it to extra+sign I was able to complete a full play-through with no additional issues.

***How to reproduce the issue:***
1.Start the aforementioned missions
2.Reach aforementioned enemies

***Last known version to work:***
 Never (only tested down to 1.2.1)

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

**Comment by Helium-4** [comment]
As far as I can tell, yes.

**Comment by ramapcsx2** [comment]
"None" is often preferable, could you try that as well? (No idea how much time a playthrough is :p)

**Comment by Helium-4** [comment]
None seems to work just as well, although some AIs seemed dumber than usual in that test playthrough but they didn't do anything that I haven't also seen happen on a real PS2 so I guess it's fine.

**Comment by Helium-4** [comment]
Reopening since something has changed and now none is broken too, extra + preserve sign seems to still fix it without any side effect.

**Comment by refractionpcsx2** [comment]
do the automatic game fixes enable the better clamping?

**Comment by Helium-4** [comment]
No, the automatic fix is set to None

**Comment by refractionpcsx2** [comment]
okay so we need to change the clamping to the other way around, so i'll change them all to that

**Comment by refractionpcsx2** [comment]
Should be fine now. To be honest that should have been done in the first place.
