### ISSUE TITLE
Armored Core 2 Another Age: Garbage graphics when full screen effect is present

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2396]
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
 Default

***Plugins used:***
 Default

***Description of the issue:***

As stated in the title, said issue is present in every renderer and does not seem affected by any of the settings, but it disappears if you start bringing an enemy in your aiming area, this issue is present an unchanged in every renderer
![gsdx_20180420184949](https://user-images.githubusercontent.com/30066566/39063996-1d053836-44cd-11e8-9ea9-6618578c174e.png)
![gsdx_20180420185000](https://user-images.githubusercontent.com/30066566/39064017-2fa4c696-44cd-11e8-9ed7-3eb5291147dd.png)
Here's a before and an after GSdump
[Armored Core 2 - radar garbage with heat distortion.zip](https://github.com/PCSX2/pcsx2/files/1932948/Armored.Core.2.-.radar.garbage.with.heat.distortion.zip)
[Armored Core 2 - radar garbage with heat distortion when aiming at an enemy.zip](https://github.com/PCSX2/pcsx2/files/1932977/Armored.Core.2.-.radar.garbage.with.heat.distortion.when.aiming.at.an.enemy.zip)

***How to reproduce the issue:***
1.Start any mission featuring the full screen heat distortion effect

***Last known version to work:***
 Never

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

**Comment by refractionpcsx2** [comment]
Long shot, but can you try the EE Timing Fix gamefix and see if that helps?

**Comment by Helium-4** [comment]
It doesn't fix  the issue

**Comment by Helium-4** [comment]
I've never actually had to do that, what do I need to do exactly just run the game with the option on load a state where the issue is present and upload the .dump  and corresponding savestate?

**Comment by MrCK1** [comment]
Yes, that's basically it.

**Comment by Helium-4** [comment]
[AC2AA blockdump.zip](https://github.com/PCSX2/pcsx2/files/1933944/AC2AA.blockdump.zip)

**Comment by refractionpcsx2** [comment]
This was fixed by #5475
