### ISSUE TITLE
Armored Core 3:  Erroneous color with HW renderer

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2397]
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
 Default

***Plugins used:***
 GSdx OGL HW

***Description of the issue:***
In one specific level location the water in that drainage sewer is partially the wrong color,it does not seem to be affected by any setting and appears in OGL as well as both DX11 and 9
![gsdx_20180420192105](https://user-images.githubusercontent.com/30066566/39069592-8528a1a6-44e0-11e8-9ebf-7f7fca5b1b74.png)
[Armored core 3 yellow water.zip](https://github.com/PCSX2/pcsx2/files/1933352/Armored.core.3.yellow.water.zip)

***How to reproduce the issue:***
1.Start any mission in that specific level environment

***Last known version to work:***
 Never

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

**Comment by refractionpcsx2** [comment]
Is Software mode ok?

**Comment by lightningterror** [comment]
Preload Frame Data hw hack fixes the issue.

**Comment by MrCK1** [comment]
Preload Fixes any issue on a GS dump... did you try it in-game? 😛

**Comment by lightningterror** [comment]
Uh nope, @Helium-4 can you try that ?

**Comment by Helium-4** [comment]
Just retried to be sure but no it does not fix the issue.

**Comment by R0bro** [comment]
It would appear that for the first rendered frame or 2, the water effect renders as it should, but for every subsequent frame the color issue becomes more apparent.

https://user-images.githubusercontent.com/31576505/208075032-7445bd69-5c5c-4daf-bef8-06c1ca36dc75.mp4

Tested build: nightly 1.7.3717 (Fri Dec 16 08:18:49 2022)
Renderers tested: Direct3D 11, Direct3D 12, OpenGL, and Vulkan
