### ISSUE TITLE
Linux : GSDx "Your computer may have insufficient resources, or incompatable hardware/drivers"

### ISSUE THREAD

**Issue by 7oxicshadow** [PCSX2/pcsx2#2401]
***PCSX2 version:***
PCSX2 c1.5.0-dev-2350-g011cd90fb

- **Notes**:
Long time user of PCSX2 on linux. Latest build will not boot any games with GSDx "Your computer may have insufficient resources, or incompatable hardware/drivers" error.

***PCSX2 options:***
Default

***Plugins used:***
GSDx (FCC 7.3.1 AVX2/AVX2) 1.1.0 [libGSdx]
Default options

***Description of the issue:***
After selecting boot iso the GL window opens with a black screen. 10 seconds later it closes with the error mentioned above.
Additional Errors in log:

> Opening plugins...
> 	Opening GS
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast

***How to reproduce the issue:***
Open PCSX2
Choose any game
Boot iso

***Last known version to work:***
Unknown

***PC specifications:***
Fedora 27
i7 6600k
GTX 1070  [NVIDIA Prop (390.48)]
16GB Ram

**Comment by lightningterror** [comment]
Please use the forum for general support.
https://forums.pcsx2.net/

**Comment by 7oxicshadow** [comment]
Thanks for re-opening this. I realise it sounds more like a support request at first but I am not new to PCSX2 and Linux. I have been using it for years.

At the moment, myself and a number of other users are experiencing issues with RPCS3 hanging when it opens a GL/Vulkan window and now it appears that PCSX2 is doing something very similar.

I will do some more digging over the next few days. If nothing comes of it I will close this issue myself.

**Comment by 7oxicshadow** [comment]
This was trivial in the end, it appears that the 32bit graphics libs had been removed from my machine.

Closing.

**Comment by quequotion** [comment]
I am having exactly the same issue, but nothing appears to be missing.

On the contrary, I think it might be some kind of conflict/mismatch of nvidia, mesa, 32-bit or 64-bit drivers (I have all of these installed).

I haven't used PCSX2 in a couple of years, but it did work on the same hardware in the past.
