### ISSUE TITLE
Silent Line Armored Core: Z-Fighting with every renderer 

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2404]
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
 Default

***Plugins used:***
 Default

***Description of the issue:***
Similar to #2398 some surface will exhibit some Z-fighting at specific angles, it is present in every renderer.
![gsdx_20180423205750](https://user-images.githubusercontent.com/30066566/39147319-923fe3bc-4739-11e8-9607-2fedd4d07348.png)
[Silent Line Armored core Zfighting.zip](https://github.com/PCSX2/pcsx2/files/1939621/Silent.Line.Armored.core.Zfighting.zip)
Setting the EE/FPU Rounding mode Nearest fixes that issue, 

To note that there is at-least one occurrence of that issue that also happens on real hardware and it is not affected by the fix.
https://youtu.be/KROeSTXHF-k

***How to reproduce the issue:***
1.Start any mission in a level environment that exhibits those issues

***Last known version to work:***
 Never

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

**Comment by atomic83GitHub** [comment]
I will add these fixes in my current PR.

**Comment by mirh** [comment]
And next time open issues per-bug (or per-game if really any) rather than duplicating the same over and over again.
