### ISSUE TITLE
WS enabled causes in game to crash with DMA error: 1f933330 (no pnatch)

### ISSUE THREAD

**Issue by IceLancerSR** [PCSX2/pcsx2#2408]
pcsx2-v1.5.0-dev-2352

WS (widescreen) enabled causes in game to crash with DMA error: 1f933330
Final Fantasy XII International: Zodiac Job System (SLPM-66750)

Final Fantasy XII will produce spam and crash ,DMA error: 1f933330 upon entering game with WS on
(not in game menu, that passes, but inside game)
1E7A88A7 pnach file
that is an old file from 2015, it worked fine on older versions of pcsx2, something has changed in ws handling most likely and is in conflict with this patch,most likely there are other games affected.

--
edit
apparently it isnt the patch it self that is causing this error, turning ws ON regardless if patch exist or not will cause the error
I deleted ws patches from zip and from folder just leaving WS option on, and DMA error still happens.

Both OGL and DX
Windows 10.
Nvidia GTX 1060

**Comment by bositman** [comment]
Can you post the full emulog.txt until the crash?

**Comment by IceLancerSR** [comment]
It appears i have found guilty.. i have no clue how can that break ws patches tho..
in my cheats ws folder i had file named 00000000.PNACH
with this inside:
gametitle= PS2 BIOS (USA 2.20)
comment= Widescreen hack

//Background Elements Width
patch=1,EE,0028AB4C,word,3F400000 // 3F800000

//Boot Section and Error Screen Width
patch=1,EE,002C8EB0,word,3F400000 // 3F800000

//Browser Objects Width
patch=1,EE,0029C590,word,44400000 // 44800000

//System Configurication Cubes Width
patch=1,EE,00375940,word,3F400000 // 3F800000
pcsx2 will not find ws cheat but if ws is enabled he will use that??
makes no sense how is it releated, but removing that pnatch makes pcsx2 boot into game without issues

**Comment by lightningterror** [comment]
> 00000000.PNACH

That doesn't look correct. pnach names = game crc id

Anyway closing this since it's an user error.

**Comment by bositman** [comment]
That pnach is the one they made for the PS2 bios, when you full boot it gets that CRC (since there is no elf). IIRC that pnach is in experimental patches but if it isnt this might be  legit.

**Comment by IceLancerSR** [comment]
@lightningterror i resent ur wording !
Please choose words more carefully. It is not "user error" as i clearly know what i am doing and as such ur words are direct insult to my intelligence.
 Anyway i am buzzing off. Thanks for nothing

**Comment by Nobbs66** [comment]
bye

**Comment by refractionpcsx2** [comment]
I've never liked the face there's a patch for the BIOS.  What are the chances that all versions of the BIOS use the same offsets? Seems a bit scary to me.
