### ISSUE TITLE
Chaos Legion - Glitched shadows under summoned legions

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2409]
***PCSX2 version:***
v1.5.0-dev-2354-g1d7cef08a

***PCSX2 options:***
default

***Plugins used:***
default

***Description of the issue:***
The shadows under legions are not rendered correctly in the hardware renderer
![gsdx_20180427201457](https://user-images.githubusercontent.com/25664221/39369529-1645bba6-4a2c-11e8-9d97-bc9a992a03ae.png)
[gsdx_20180427201457.zip](https://github.com/PCSX2/pcsx2/files/1955651/gsdx_20180427201457.zip)

***How to reproduce the issue:***
While ingame press L1 to summon your legion in Hardware renderer.

***Last known version to work:***
none

***PC specifications:***
CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1

**Comment by MrCK1** [comment]
Works fine in OGL/DX11 SW, DX11 HW is totally busted 😛

**Comment by Krusher97** [comment]
It happens only in HW renderers. The screenshot is from the OGL HW renderer.

**Comment by lightningterror** [comment]
None of the hw hacks have an effect ?

**Comment by Krusher97** [comment]
Nope

**Comment by knight-ryu12** [comment]
I have same problem with NTSC-J release of Chaos Legion(SLPM-65249)
CRC = 5E191B9C
https://drive.google.com/open?id=1lhGxr2g1IE2obIDl6fyhImgVzEdqFD9x

**Comment by MrCK1** [comment]
Still exists on latest git

**Comment by Peduls** [comment]
Tested with the latest dev build. Sad to see this issue still exists.

**Comment by refractionpcsx2** [comment]
This is resolved with Tex in Rt enabled, we will need to add this to the GameDB to automatically turn it on once #5593 is merged
