### ISSUE TITLE
there is some way to translate These menus

### ISSUE THREAD

**Issue by killerjn** [PCSX2/pcsx2#2414]
***PCSX2 version:***
``(pcsx2-v1.5.0-dev-2360-g17027c16c-windows-x86``

- **Notes**:
hi good in the previous versions and in the development some menus are in English you could add translations to know what this adjustment is about

there are several menus partially translated

![2018-04-29 15_25_45-](https://user-images.githubusercontent.com/32747059/39410758-b8ca02dc-4bc2-11e8-9255-593e1bae5cbf.png)

![2018-04-29 15_36_29-](https://user-images.githubusercontent.com/32747059/39410781-256c8dba-4bc3-11e8-9266-d070d8452d8a.png)

**Would it be possible to translate these menus into other languages?
would be very helpful thanks**

**Comment by lightningterror** [comment]
Duplicate #1643

**Comment by willkuer** [comment]
Maybe you should read the referenced issue? It is currently not possible.

You can start translating everything but it will not be included as the plugins are not even aware of pcsx2's language. And even if you would allow translation and would transfer the selected language to the plugin you would still need to implement localization of gui strings.

**Comment by killerjn** [comment]
ok please delete this issue
