### ISSUE TITLE
Support the newest version of libaio which is 0.3.111

### ISSUE THREAD

**Issue by SolarAquarion** [PCSX2/pcsx2#2416]
-- AIO not found (miss lib)
-- LIBUDEV found
-- PORTAUDIO found
-- SOUNDTOUCH found
-- SDL2 found
-- Looking for XOpenDisplay in /usr/lib32/libX11.so;/usr/lib32/libXext.so
-- Looking for XOpenDisplay in /usr/lib32/libX11.so;/usr/lib32/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib32/libX11.so
-- Found GTK2_GTK: /usr/lib32/libgtk-x11-2.0.so  
CMake Error at cmake/SelectPcsx2Plugins.cmake:20 (message):
  Skip build of pcsx2 core: miss some dependencies:check these libraries ->
  wxWidgets (>=3.0), gtk2, zlib (>=1.2.4), pcsx2 common libs
Call Stack (most recent call first):
  cmake/SelectPcsx2Plugins.cmake:74 (print_dep)
  CMakeLists.txt:62 (include)

-- Configuring incomplete, errors occurred!
See also "/home/solaraquarion/build/pcsx2-git/src/pcsx2/build/CMakeFiles/CMakeOutput.log".

**Comment by gregory38** [comment]
I guess You didn't install libaio correctly. It should work with any version.

**Comment by SolarAquarion** [comment]
lib32-libaio /usr/
lib32-libaio /usr/lib32/
lib32-libaio /usr/lib32/libaio.so.1
lib32-libaio /usr/lib32/libaio.so.1.0.1

libaio /usr/
libaio /usr/include/
libaio /usr/include/libaio.h
libaio /usr/lib/
libaio /usr/lib/libaio.so
libaio /usr/lib/libaio.so.1
libaio /usr/lib/libaio.so.1.0.1

**Comment by gregory38** [comment]
It doesn't hurt to write some sentences.

Anyway, as I said, you need to install libaio.so 32 bits.

**Comment by SolarAquarion** [comment]
I do have the /use/lib32 bits

**Comment by gregory38** [comment]
You need the .so file. You don't have it in your previous post

**Comment by SolarAquarion** [comment]
So I need to have a symlink for the .so

**Comment by SolarAquarion** [comment]
[  8%] Building CXX object common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/VirtualMemory.cpp.o
In file included from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/Pcsx2Defs.h:36,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/Utilities/Dependencies.h:231,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/src/Utilities/PrecompiledHeader.h:21,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/src/Utilities/VirtualMemory.cpp:16:
/home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/x86emitter/x86_intrin.h:52:69: error: ambiguating new declaration of ‘long long unsigned int _xgetbv(unsigned int)’
 static __inline__ __attribute__((always_inline)) unsigned long long _xgetbv(unsigned int index)
                                                                     ^~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include/x86intrin.h:74,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/x86emitter/x86_intrin.h:24,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/Pcsx2Defs.h:36,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/include/Utilities/Dependencies.h:231,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/src/Utilities/PrecompiledHeader.h:21,
                 from /home/solaraquarion/build/pcsx2-git/src/pcsx2/common/src/Utilities/VirtualMemory.cpp:16:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include/xsaveintrin.h:60:1: note: old declaration ‘long long int _xgetbv(unsigned int)’
 _xgetbv (unsigned int __A)
 ^~~~~~~
make[2]: *** [common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/build.make:63: common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/VirtualMemory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:182: common/src/Utilities/CMakeFiles/Utilities_NO_TLS.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by turtleli** [comment]
It would be useful to know what distro you are using and any other relevant details.

#2419 should fix the compile error.
