### ISSUE TITLE
Compilation under fedora 28

### ISSUE THREAD

**Issue by lucag73** [PCSX2/pcsx2#2417]
***PCSX2 version:***
Git release: 4de2df2865abb3c9fee62875b6f9ce3e9a01ebc9
***Description of the issue:***
Compilation of pcsx2 with gcc8 in Fedora28 fails since _xgetbv is already defined

***How to reproduce the issue:***
1) install fedora 28 (with all of the relevant packages for compiling pcsx2)
2) build with ./build.sh --release --gtk3
3) the compilation fails as soon as common/include/x86emitter/x86_intrin.h is included

The issue can be fixed by adding in the aforementioned file a
 #define _XSAVEINTRIN_H_INCLUDED
which prevents the inclusion of /usr/lib/gcc/x86_64-redhat-linux/8/include/xsaveintrin.h
but this is clearly a hack.

**Comment by gregory38** [comment]
We need to check how _xgetbv is implemented on gcc8 and remove our definition if already defined or if gcc >= 8

**Comment by gregory38** [comment]
Yes we should use gcc implementation by default

**Comment by turtleli** [comment]
#2419 should fix the issue.

**Comment by lucag73** [comment]
I posted in #2419 ... with this fix compilation works, but pcsx2 segfaults on start...
