### ISSUE TITLE
DS3 pressure sensitivity wiki page info seems out of date

### ISSUE THREAD

**Issue by turtleli** [PCSX2/pcsx2#2420]
The info at https://github.com/PCSX2/pcsx2/wiki/Pressure-sensitive-buttons-with-DS3 doesn't seem up to date.

AFAIK the custom Lilypad plugin hasn't been necessary since #1040 was merged. Only the XInput wrapper is. Pressure sensitivity works on my end if the XInput API is ticked. I'm using the original SCP drivers (1.2.2.175), but it should also be fine with the SCPToolkit drivers too.

@mirh Can you check your info and update the page?

**Comment by Ryudo300** [comment]
I still needed the custom one to get it to work for me in v1.5.0 dev builds. It refused to work with the normal Lilypad plugin.

**Comment by turtleli** [comment]
How did you set it up?

If you add the XInput1_3.dll to the PCSX2 directory, select the XInput API in Lilypad, and select the XInput Device corresponding to the DS3 in the Lilypad Device Diagnostics box, does it show it detecting pressure on the buttons or not?

**Comment by mirh** [comment]
> AFAIK the custom Lilypad plugin hasn't been necessary since #1040 was merged

Oh god, I'd have swear to remember something similar, but couldn't find it. 

And you actually seem right indeed. 
The thing is just a bit confusing because there's still the original libusb "dualshock 3 native mode", and you still need the XInput1_3 custom dll. 

I guess like I should also re-test the newer versions of scptoolkit then... But I cannot be bothered. 
Also, the configuration images I have grabbed from nefarius aren't actual anymore (and it wouldn't hurt if somebody could redo them)

**Comment by RinMaru** [comment]
I have SCPToolkit installed though if you don't use the modded lilypad scp gives you then native mode doesn't work. is native mode deprecated in the newest rev?

**Comment by mirh** [comment]
You don't need to tick "native" (if you do what I wrote in the guide) with the pcsx2 *built-in* support. 

Then, I dunno, maybe you have some newer version? Newer ones (as you can see in the changelogs) broke "backwards compatibility". 
As I was saying, I dunno if they are really worth any advantage over what I alreqdy recommend.

**Comment by lightningterror** [comment]
Status ?

**Comment by turtleli** [comment]
The configuration section is still out of date, and I don't know if there are issues preventing the use of pressure sensitivity in the master branch or if it's just that people do not know how to set it up.

**Comment by mirh** [comment]
Uh, right... Images should also be changed.. 
I'll try to fix it now. 

I'd still be waiting for other people that complained of this or that problem to report back though.

**Comment by lightningterror** [comment]
Closing, don't think the page is/will be relevant anymore with Qt.
