### ISSUE TITLE
Kung Fu Panda Slow Gameplay

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [PCSX2/pcsx2#2423]
If I disable framelimiter, in the menu/intro, I am getting around 150fps and 370% speed. But in the ingame the fps is 34-35 and the game is too slow. But it is still playable. But no one will get true gaming performance with it.
(Note: In the forum I also found this issue is very very old)

**Comment by lightningterror** [comment]
Please use the forum for support questions/issues.
https://forums.pcsx2.net/

**Comment by Rafidmuhaiminwafi** [comment]
But why?

**Comment by lightningterror** [comment]
Github is used to discuss actual issues/bug reports, pull requests and so on.

Anyway if you're talking about HW mode it's probably related to #1318

**Comment by Rafidmuhaiminwafi** [comment]
No I'm not talking about HW mode. I have already switched to SW mode. My main issue is the gameplay its too slow. I have tried every options I found but nothing changes. Also its not happening for my pc. I have already played 4 other games at full speed in my pc. So I want that some fix/hacks/updates which will make this game run faster.
