### ISSUE TITLE
[GSDx] Ridge Racer V [SLUS-20002] Missing Shadows - All Renders

### ISSUE THREAD

**Issue by Veritas83** [PCSX2/pcsx2#2427]
***PCSX2 version:***
All Versions

- **Notes**:
All Renders.

***PCSX2 options:***
No options have effect.

- **Note**: 

***Plugins used:***
GSdx32-SSE4.dll [GSdx 20180503003203 (MSVC 19.00 SSE4.1/AVX) 1.1.0]

- **Note**: 
DX11HW/SW

***Description of the issue:***

Car shadows alternate at a steady interval from white to invisible

https://i.gyazo.com/0d1941ba6e881329dbedfc43cff66dc6.png

https://i.gyazo.com/d153d51d23f66e461e695ddc0bcb35ab.png

GS Dumps avail here:
https://forums.pcsx2.net/Thread-Vector-Units-Bug-Report-Ridge-Racer-V-PAL-NTSC

***How to reproduce the issue:***
Start the game. Enter a race. Observe lack of shadows.

***Last known version to work:***
I checked latest annual builds for 2011 thru 2017 (missing a 2015 build)
Car Shadows have 'Never worked' period. All renders. 

***PC specifications:***
CPU: AMD 4.0GHz X4 GPU: R9 270X 2GB OS: Win7 x64

**Comment by atomic83GitHub** [comment]
So this happen in both SW and HW render? Did you tried various Clamping/rounding values in the EE/IOP and VUs tab?

**Comment by Veritas83** [comment]
I've just tried every combination of Clamping/Rounding in the EE/IOP/VU settings.

The issue persists.

**Comment by Veritas83** [comment]
Still Present v1.5.0-dev-2485

**Comment by MrCK1** [comment]
Don't expect it to change soon, no major work is being done in GSdx at the moment.

**Comment by tadanokojin** [comment]
It's caused by the game using `0x11` as a mirror of register `0x01` (RGBAQ).
Thanks to psi and ref.
