### ISSUE TITLE
Superman Returns ps2 explain me why this isnt fixed yet

### ISSUE THREAD

**Issue by toozzb** [PCSX2/pcsx2#2432]
Hello, could you please give time to fix the bug bulding on superman returns Ps2 game

this is the game

i am playing superman on pcsx2 1.5 dev but when i go to the game the glitch thing appears because i am too near of the buildings and that thing appears always and i cannot play in the ground just i have to keep flying and flying which is useless for now, please be aware and work on this kind of issue and update that on pcxc2 i need some assistance how to stop this Building glitch, i am so disappointed how you did not fixed for this game.

please do something developers-

explain i been waiting for years and the game isnt fixed for the emulator

Link https://www.youtube.com/watch?v=EM3J6MoxBqo

as you can see the texture starts to fuck up once i go underground

**Comment by lightningterror** [comment]
Duplicate #934
