### ISSUE TITLE
LilyPad Quick Setup is not working correctly

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#2433]
I am using the latest beta and it happens while trying to set buttons for the gamepad or the keyboard.

First I think it will be easier to find the problem by saying this first.
When you try to test DInput gamepad,there is something strange.Why there is "Z Axis -"(which is right analog up)twice in the list

There is actually Z Axis,Z Axis + and Z Axis - that are twice and only the fist one reacts
The second ones are set to
Z Axis  0.004
Z Axis + 0.000
Z Axis - 0.994

The first ones that are reacting to my gamepad are set to(without moving the analog but I think this is how they are supposed to be)

Z Axis  0.500
Z Axis + 0.000
Z Axis - 0.000

The fist one is ok and it is reacting to my right analog but the second one it stays at 0.992 which is like pushing the right analog up.

So when I press the "Quick Setup" button,lilypad is waiting for "Select" but when I press anything to set that button,I see that it is setting the select button,goes to the next button to set,set it automatically to "Z Axis -" and continues to the next button.

So in the end,out of 24 buttons only 13 are set(I stop when it asks for Analog)
If I choose the keyboard in the "All all devices" drop down list,then I can set the controls and it is also fine if I manually set all buttons to the gamepad

**Comment by willkuer** [comment]
Have you tried recalibrating your controller using the windows controller configuration? If lilypad has problems during the setup I expect that the same happens in-game.

Btw the forum is a better place for support.

**Comment by vsub** [comment]
When I try x360ce(which have a feature to show me at what position the analogs are),both analogs are centered and working fine.
The windows calibrating tool also says that the analogs are fine.

And yes,the forum is better place for support but I think there is actually a bug with LilyPad.
Probably anyone with DInput gamepad is affected because that "Z Axis - 0.994" is not controlled by anything and the quick setup is automatically applying it.

If I set the controls manually and use a homebrew app that tests the controller,the app reacts correctly and the right analog is not pushed up even by 0.001

**Comment by MrCK1** [comment]
@vsub Can this still be reproduced on latest git?

**Comment by vsub** [comment]
The problem is that this happens on my Win7 pc while using my DInput gamepad and both the PC and the gamepad are very far away.

On Win10 laptop with gamepad that support both dinput and xinput and have the L2\R2 analogs(not buttons),there is no problem

From what I see the Z Axis represents the analog L2\R2 which are also visible on the win10 laptop while using the gamepad in dinput mode but on my other gamepad don't have analog L2\R2 buttons but they are still reacting to Z Axis not Button4 and Button5.

If someone else have a DInput or DInput compatible gamepad **WITHOUT** analog L2\R2 buttons(just normal buttons),he\she can check if those are like this
Z Axis 0.500
Z Axis + 0.000
Z Axis - 0.000

and they only change while pressing L2\R2

If it is like that then the problem is solved....you could call it a problematic gamepad.

**Comment by lightningterror** [comment]
So it's only an issue on windows 7?

**Comment by vsub** [comment]
You can close this if you wish
I don't think I will be able to test win7 anytime soon with that gamepad
