### ISSUE TITLE
SRS Street Racing Syndicate v2.0 causes entire system hang

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#2436]
***PCSX2 version:***
``(1.5.0-dev-2376-g171e7f016)``

- **Notes**:

***PCSX2 options:***
``(Safer Preset)``

***Plugins used:***
``(Default Plugins, AVX2 GSDX)``

***Description of the issue:***
``(SRS Street Racing Syndicate v2.0 causes entire system hang. Once the title is booted PCSX2 will become unresponsive as well as the rest of the entire windows system causing all services to restart after waiting for so long )``

***How to reproduce the issue:***
``(Run SRS Street Racing Syndicate v2.0 )``

***Last known version to work:***
``(SRS apparently works on PCSX2 wiki but that might be the v.1.0)``

***PC specifications:***
``(Windows 10 x64/ i5 6402p 8GB DDR4 2.80Ghz/ AMD RX 480 4GB )``

**Comment by MrCK1** [comment]
What GSdx settings are you using?

Did you also try using 1.4.0?

**Comment by RinMaru** [comment]
Ive used DX11 Hardware, x4 IR, x16 AF but no I haven't bothered messing with older versions

**Comment by refractionpcsx2** [comment]
I don't know if have Version 2 (SLUS 20582) but it works absolutely fine here. 

I vaguely remember some setting causes the logo screens to really bring the system to a crawl and I don't know why. Can you try these GSDX settings?

![image](https://user-images.githubusercontent.com/6278726/39991245-caf5225c-5766-11e8-9ab9-6c4875a3ab88.png)

**Comment by RinMaru** [comment]
With those exact settings (besides Large Framebuffer) the game will run but any of them get changed then theres a MASSIVE MEMORY LEAK I tried diff combinations but only those settings seem to allow it to run

**Comment by MrCK1** [comment]
Do you have Large Framebuffer Enabled or Disabled? It should be disabled to.avoid large memory spikes uness the same specifically requires it.

**Comment by lightningterror** [comment]
A blockdump with a savestate could provide useful here.

Can you try out this PR, it may improve things.
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.4038-master/job/w6wa28y57oqxap5y/artifacts

**Comment by RinMaru** [comment]
yes its on my main HDD

**Comment by MrCK1** [comment]
No, I mean running the game from the physical DVD disk in a CD drive

**Comment by RinMaru** [comment]
no its an old dump so I don't have the disc anymore

**Comment by atomic83GitHub** [comment]
This issue seems very similar to something that happen on "ONI", if you enable Anti-aliasing along with huge upscaling, you will have a VRAM spike if your videocard don't have a least 6GB or more.

**Comment by RinMaru** [comment]
Issue is caused by Frame Buffer conversion in HW Hacks
