### ISSUE TITLE
[Feature Request] PCSX2 Updater

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#2439]
Recently Dolphin has implemented a Updater that allows you to choose between Stable Builds, Beta Builds, & Dev Builds. I think something similar would be great for PCSX2

**Comment by bositman** [comment]
'Working on it" :P

**Comment by lightningterror** [comment]
It is a good idea however pcsx2 dev builds are hosted on an external site which generates revenue from ads, the updater would be a huge loss for our hosts so we won't be adding this.

**Comment by TucoPacifico1980** [comment]
> 
> 
> It is a good idea however pcsx2 dev builds are hosted on an external site which generates revenue from ads, the updater would be a huge loss for our hosts so we won't be adding this.

Hey there. How to best update my nightly build from https://buildbot.orphis.net/pcsx2/ manually to preserve my save states and options?

**Comment by CassiusOtho** [comment]
I would love to see this happen! It's a shame the feature won't be implemented. 😔

**Comment by RedDevilus** [comment]
We never said that, it's likely it will be implemented when Qt GUI is here.

**Comment by CassiusOtho** [comment]
Ok, that's great news! I'm sorry I misunderstood, I saw the "Won't Fix" label, and thought that the request wouldn't be implemented.

**Comment by RedDevilus** [comment]
Maybe back then as it was much work and low priority. Anyway let's hope for future improvements and not use this as a discussion area which is what Discord is for.

**Comment by CassiusOtho** [comment]
I'm not a fan of discord. It may be a good idea to remove the "Closed" and "Won't Fix" labels though. They are pretty confusing. It could even be problematic when it comes to prioritizing future tasks since this feature request won't be listed.

**Comment by RedDevilus** [comment]
There is an open issue already, I won't open a duplicate issue, but I can remove the Won't Fix label.

**Comment by CassiusOtho** [comment]
@RedDevilus could you please provide me the link to the open request?

**Comment by RedDevilus** [comment]
I told you on the issue you created:
https://github.com/PCSX2/pcsx2/issues/3054
