### ISSUE TITLE
[Feature Request] PCSX2 Game Compatability DB

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#2440]
I think Being able to quickly see the current status of game compatibility within PCSX2 (along with notes as to what settings should be used) would be a nice thing to have instead of having to navigate the homepage for details.

**Comment by MrCK1** [comment]
I don't see the point in this, it's duplicating info for no reason. Is it really that difficult to navigate through the forums/webpage?

**Comment by RinMaru** [comment]
well I do have allot of games and having to find the game in question can be a bit of a hassle trying to find what page number in the selected letter has your details

**Comment by RinMaru** [comment]
i figured having something like dolphin does where you can highlight a game and check the Wiki Option then it will take you to the page.

**Comment by lightningterror** [comment]
The pcsx2 compatibility list on the main site has all links to whatever version of a game you're looking for: Wiki and forum links.

**Comment by RinMaru** [comment]
Yea I'm just suggesting something a bit more simple for an average user. sure anyone can go to the main site and click the letter then navigate to the corresponding game but it would be easier on the user end to just be able to pick the game within pcsx2 and get a direct link to the source

**Comment by MrCK1** [comment]
There's a search bar on PCSX2.net that allows you to find your game directly by name.

**Comment by RinMaru** [comment]
there is? I never noticed that :P then nvm i feel stupid now

**Comment by TheTechnician27** [comment]
Long-since fixed with the introduction of the GameIndex.yaml. Tagging accordingly.
