### ISSUE TITLE
Futurama Unresponsive input

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#2444]
- **PCSX2 version:**
(1.5.0-dev-2377)
- **PCSX2 options:**
(Safer Preset)
- **Plugins used:**
(Default Plugins)
- **Description of the issue:**
(Futurama doesn't respond to controller input)
- **How to reproduce the issue:**
(Run Futurama with Lillypad Xinput )
- **Last known version to work:**
(1.3.0 r5875 From PCSX2 Wiki)
- **PC specifications:**
(Windows 10 x64/ i5 6402p 8GB DDR4 2.80Ghz/ AMD RX 480 4GB )

**Comment by lightningterror** [comment]
See if this works.

https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-1939-gf3a89f59e&platform=windows-x86

**Comment by RinMaru** [comment]
Nope

**Comment by lightningterror** [comment]
[1.3.1.txt](https://github.com/PCSX2/pcsx2/files/2020687/1.3.1.txt)
[1.5.0.txt](https://github.com/PCSX2/pcsx2/files/2020688/1.5.0.txt)
See if you can narrow down the issue.

**Comment by RinMaru** [comment]
So... Im going to guess I should download and test every build till I hit the error? or just test the Lilypad plugin of that specific build?

**Comment by lightningterror** [comment]
You're gonna have to test every build, you can start wit 1.3.1 1

Then you can skip to 1.3.1 1000, if the error doesn't hit add +500 if it does hit -500 and so on.
If the first 1.3.1 build hits then the regression info could be accurate in the wiki.
You only need to test the lilypad dll tho.

**Comment by RinMaru** [comment]
im not sure how to grab these builds though the links arnt working

**Comment by lightningterror** [comment]
You copy them starting from https.

**Comment by RinMaru** [comment]
ok will do

**Comment by RinMaru** [comment]
even the first build don't work

**Comment by refractionpcsx2** [comment]
It must be something with your setup. Controls work fine for me on Futurama on the latest build.

**Comment by RinMaru** [comment]
well im using SCPtoolkit and DS3 all other games work

**Comment by refractionpcsx2** [comment]
Are you using any speedhacks?

**Comment by RinMaru** [comment]
well switching to safest preset fixed it I was on safer
