### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kwstas86** [PCSX2/pcsx2#2448]
The channel Tech Work Published on Nov 18, 2017 on youtube a video and a link to PCSX2 1.6...

![untitled](https://user-images.githubusercontent.com/12601176/40328830-643f5f7e-5d50-11e8-8fa6-4e069790c6f7.png)

My question is... where can i get 1.6?

**Comment by MrCK1** [comment]
There is no 1.6, it doesn't exist (yet)

Whatever build that is was compiled with a custom version number. Basically it's fake and shouldn't be used...

**Comment by lightningterror** [comment]
It's fake, someone compiled the source code and just renamed 1.5 to 1.6. Anyone can do that.
1.6 will be the next stable version and isn't released yet.

Latest dev versions are 1.5
https://buildbot.orphis.net/pcsx2/

**Comment by kwstas86** [comment]
ok thanks!
