### ISSUE TITLE
Use the native theme and widget styles of GTK2 in Linux version.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2450]
Remember that not everyone is running GNOME or KDE.
Minimal windowing managers still exist.
Please consider.

**Comment by mirh** [comment]
[AFAIK](https://github.com/PCSX2/pcsx2/issues/2312) we were considering to drop GTK2 altogether.

**Comment by turtleli** [comment]
I don't understand the issue. More detail would be helpful.

It works fine for me on Fluxbox.

**Comment by pthfdr-42** [comment]
@mirh GTK3 is not an upgrade from GTK2. It is a bastardization. Also, it depends on D-Bus/`systemd`.
https://igurublog.wordpress.com/2012/11/05/gnome-et-al-rotting-in-threes/

**Comment by mirh** [comment]
It may be bastard, but last time I checked GTK2 and wayland were like water and oil.

**Comment by pthfdr-42** [comment]
Wayland is still experimental.Also there is XWayland.

**Comment by Lithium64** [comment]
Currently i'm have issues with the size of the settings windows on Ubuntu 18.04, it too big if you use lower resolutions.

**Comment by RedDevilus** [comment]
As far as I know GTK2 is not the default and by now things have turned into WX where possible to then finally be dropped in favor for Qt so what's the benefit of this nowadays?

**Comment by lightningterror** [comment]
Most of the gtk remaining gui was ported to wx, alternatively qt is in the works.
