### ISSUE TITLE
[SLES-52418] PowerDrome - Graphical glitch

### ISSUE THREAD

**Issue by LoStraniero91** [PCSX2/pcsx2#2451]
***PCSX2 version:***
``PCSX2 v1.5.0-dev-2388-g48ebfea17``

***PCSX2 options:***
Tried all possible hacks and VU/EE combinations.

***Plugins used:***
GSdx 20180523181054 1.1.0
LilyPad (20180523181054) 0.12.1
SPU-2 X 20180523181054 2.0.0

***Description of the issue:***
This is a bug that plauged this game since it first booted with PCSX2. Both in vehicle/character selection screen and ingame there are weird stripes if HW OGL is used. In HW D3D11, there no stripes but the graphic flickers like crazy or is missing for the most part. SW behaves like HW OGL. In all renders, characters are missing and could be the cause of this issue.
If using "Disable Depth Emulation" in HW OGL, the graphic will behave like HW D3D11.

***How to reproduce the issue:***
Just go to the vehicle selection screen to see it, then ingame for a worst picture.

***Last known version to work:***
None

***PC specifications:***
i5-3470 3.20Ghz
8GB RAM
NVIDIA GeForce GTX 650
Windows 10 Pro

**HW OGL**
![powerdrome hwogl](https://user-images.githubusercontent.com/29802222/40490814-e6924090-5f6c-11e8-980c-42e161ad3da3.jpg)

**HW OGL "Disable Depth Emulation"**
![powerdrome hwogl no depth](https://user-images.githubusercontent.com/29802222/40491328-114b44ac-5f6e-11e8-9a3c-2021255e7af3.jpg)

**HW D3D11**
![powerdrome hwd3d11](https://user-images.githubusercontent.com/29802222/40490823-ebe9a2e0-5f6c-11e8-82c6-fdfbbc09e946.jpg)

**SW**
![powerdrome sw](https://user-images.githubusercontent.com/29802222/40490828-ef2f9720-5f6c-11e8-9870-6a85310fdb57.jpg)

**Comment by LoStraniero91** [comment]
GS Dumps

[PowerDrome Ingame GS Dump.zip](https://github.com/PCSX2/pcsx2/files/2036267/PowerDrome.Ingame.GS.Dump.zip)
[PowerDrome Menu GS Dump.zip](https://github.com/PCSX2/pcsx2/files/2036268/PowerDrome.Menu.GS.Dump.zip)

**Comment by atomic83GitHub** [comment]
Can you put a Blockdump+savestate in the issue tracker so we can help you futher?

**Comment by LoStraniero91** [comment]
Above your post I've already uploaded two GS dump. Aren't those enough?
And why would you need a savestate? You just need to start a race.

**Comment by atomic83GitHub** [comment]
No, I was not talking about Blockdump.

![capture](https://user-images.githubusercontent.com/26351275/40586873-4c353df0-61c8-11e8-86a4-fbfb497ff461.PNG)

And I need a savestate so I can directly goes ingame withot loading te whole game.

**Comment by LoStraniero91** [comment]
https://mega.nz/#!Mi5hkKwb

There you go.

**Comment by atomic83GitHub** [comment]
What is the decryption key?

**Comment by LoStraniero91** [comment]
!iHeJ90Rs38dgP3gLI9CS4n0dOnI3ed-T8MVPukNuFzQ

**Comment by atomic83GitHub** [comment]
Thanks :).

**Comment by tadanokojin** [comment]
dupe #473

**Comment by tuvok2018** [comment]
Hi has anything been updated to make this game work? I cannot see anything obvious as using PCSX2 1.5.0-20200327183028 - compiled on Mar 27 2020 and Powerdrome still has the graphical issues mentioned above.  Game runs at 60fps so no other issues other than it makes playing impossible.  I really hope this gets sorted as every game I have got works apart from The Getaway which is a nightmare constantly changing the settings.

**Comment by refractionpcsx2** [comment]
The fix hasn't been implemented yet, it needs some thinking on how to handle it with the hardware renderers.  Your version will also need a patch in order to see the characters, I think only a PAL patch exits right now.
