### ISSUE TITLE
Rayman Revolution - Game Hangs

### ISSUE THREAD

**Issue by MojoJojoDojo** [PCSX2/pcsx2#2452]
***PCSX2 version:***
version 1.5.0 dev-2388-g48ebfea17

***PCSX2 options:***
Using the safest preset with no changes.
Directx 11 hardware plugin default settings.

***Description of the issue:***
The game gets stuck after Clark running away.
Clark keeps running indefinitely. 

***How to reproduce the issue:***
Just go to where the cutscene triggers in the hub world.

***Last known version to work:***
No idea.
I remember it also happened as early as version 0.9.8.

***PC specifications:***
Windows 10 Dell PC 8 GB RAM.
GPU - AMD Radeon 530
CPU - Intel 8550U.

**Comment by Helium-4** [comment]
Although this can already happen on real hardware this happens with an almost 100% rate in PCSX2, I recall having moderate success into working around that by doing the following

1. Get to the point where Clark is stuck
2. Pause the emulator and change EE+VU to interpreter mode
3. Resume the game and if the screen goes black make a savestate then pause the emulator
4. Put back the EE + VU in recompiler mode
5. Load the savestate
It might crash at step 3 and 5 or it might simply not change anything.

Will confirm latter on when I have some time to test it

**Comment by prafullpcsx2** [comment]
I assume this is a cutscene in the game. Can you post a savetstate right before this cutscene?

**Comment by atomic83GitHub** [comment]
The EETimingHack reduce the chance to get stuck in the clark cutscene but cause graphical glitches with shadows.

**Comment by MojoJojoDojo** [comment]
pressing the camera buttons repetitively also works.
for real this happens on real hardware? so weird.
the game is buggy beyond that point tho

**Comment by prafullpcsx2** [comment]
Waiting for you to upload the savestate. You have PAL version or NTSC?

**Comment by Helium-4** [comment]
[Git.zip](https://github.com/PCSX2/pcsx2/files/2036344/Git.zip)
Here's a blockdump, I can also provide a hard save but that has something like 2 minutes of gameplay before you can reach the buggy spot.
Touching up clamping / rounding modes seems like it might affect the issue but honestly even the safest preset can get stuck 10 times in a row then not get stuck 10 times in a row.
But the latest git build seems far less prone to it compared to older ones.

**Comment by MojoJojoDojo** [comment]
Its USA version.
I accidentally save stated at the moment it happens.
[SLUS-20138 (D2F77DF2).00.zip](https://github.com/PCSX2/pcsx2/files/2036411/SLUS-20138.D2F77DF2.00.zip)
I cant go back because i saved afterwards sorry.
Hope it helps

**Comment by atomic83GitHub** [comment]
VU clamping mode to extra seems to fix the issue.

**Comment by Helium-4** [comment]
Did ten tries, 7 stuck 3 not stuck with VU clamping mode to extra.

**Comment by atomic83GitHub** [comment]
And what about extra+preserv sign? Seems a bit better in my side.

**Comment by Helium-4** [comment]
Seems better, less than half got stuck

**Comment by MojoJojoDojo** [comment]
Smh Ubisoft rushed the game...

**Comment by MrCK1** [comment]
Why did you close this, we're still trying to work out a solution for you...

**Comment by MojoJojoDojo** [comment]
Accident

**Comment by prafullpcsx2** [comment]
My testing suggests setting EE round mode to nearest or negative fixes this hang.

**Comment by atomic83GitHub** [comment]
EE rounding mode to nearest solve completely this issue.
Here is my PR link: https://github.com/PCSX2/pcsx2/pull/2455

**Comment by javelin5150** [comment]
I'm sorry for bumping this but changing round mode to nearest and clamping mode to extra fixed my issue.
![image](https://user-images.githubusercontent.com/35107561/76704282-2b153280-66d8-11ea-8828-c26acaf48cd6.png)
