### ISSUE TITLE
The Lord of the Rings - The Two Towers (USA) Direct3D Rendering Issue

### ISSUE THREAD

**Issue by lukie123** [PCSX2/pcsx2#2453]
PCSX2 version:
v1.5.0-dev-2389-ga6db486af

PCSX2 options:
Safest.

Plugins used:
Default plugins. The issues are only present on the Direct3D9 and Direct3D11 hardware renderers. The software and both OpenGL renderers work fine.

Description of the issue:
The characters on the select screen do not render, or are partially rendered for a brief second before disappearing. On the buy screen, the characters performing their attack moves are also not rendered.

Another issue, not sure if its related though, is that the fourth level, Balin's Tomb, remains completely black, though audio is fine and the level itself is loadable and playable.

![the two towers](https://user-images.githubusercontent.com/39600259/40505879-ee65e898-5f95-11e8-9bed-9536a3d17613.png)

![the two towers 4th level](https://user-images.githubusercontent.com/39600259/40506082-a44e4f1a-5f96-11e8-95a5-94c43c2efe6c.png)

Last known version to work:
Issue is present as far back as stable version 1.0.

PC Specifications:
CPU: Intel i5-2500k, 3.4GHz; GPU: MSI GTX1050Ti; OS: Windows 10 64 Bit

**Comment by lightningterror** [comment]
A gsdump of the issue would be nice.
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by lukie123** [comment]
Dumps:
[The Lord of the Rings - The Two Towers (USA) - Character Selection.zip](https://github.com/PCSX2/pcsx2/files/2036938/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.Character.Selection.zip)
[The Lord of the Rings - The Two Towers (USA) - Fourth Level.zip](https://github.com/PCSX2/pcsx2/files/2036941/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.Fourth.Level.zip)

**Comment by lukie123** [comment]
I am not sure if these are of any help and I apologise if this counts as spamming the post, but these are dumps of other separate issues that I've noticed throughout the game (the zip file titles should be self-explanatory):

[The Lord of the Rings - The Two Towers (USA) - OpenGL Hardware Weird Line - Gates of Moria.zip](https://github.com/PCSX2/pcsx2/files/2039396/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.OpenGL.Hardware.Weird.Line.-.Gates.of.Moria.zip)
[The Lord of the Rings - The Two Towers (USA) - Direct3D9 (Hardware) FMV Half Screen Rendering Issue.zip](https://github.com/PCSX2/pcsx2/files/2039379/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.Direct3D9.Hardware.FMV.Half.Screen.Rendering.Issue.zip)
[The Lord of the Rings - The Two Towers (USA) - Direct3D9 (Hardware) Westfold Level Half Screen Rendering Issue.zip](https://github.com/PCSX2/pcsx2/files/2039383/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.Direct3D9.Hardware.Westfold.Level.Half.Screen.Rendering.Issue.zip)
[The Lord of the Rings - The Two Towers (USA) - Direct3D9+11 Hardware Rendering Issue - Gates of Moria Screen Should Be Like Bottom Part.zip](https://github.com/PCSX2/pcsx2/files/2039399/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.Direct3D9.11.Hardware.Rendering.Issue.-.Gates.of.Moria.Screen.Should.Be.Like.Bottom.Part.zip)
[The Lord of the Rings - The Two Towers (USA) - OpenGL (Hardware) Weird Glow.zip](https://github.com/PCSX2/pcsx2/files/2039388/The.Lord.of.the.Rings.-.The.Two.Towers.USA.-.OpenGL.Hardware.Weird.Glow.zip)

You can compare the OpenGL Gates of Moria png with the Direct3D one to visually be able to see what is wrong with the Direct3D rendering issue that I have uploaded a dump of.

**Comment by lightningterror** [comment]
The game needs depth emulation which D3D lacks.

A brave soul needs to port Depth from GL to D3D.
