### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Chibidaki** [PCSX2/pcsx2#2456]
Is there gonna be a x64 build? If i understand correctly a x64 build wont need the 4gb patch yes?

**Comment by willkuer** [comment]
The 4gb patch is not necessary anymore. By default it is activated in pcsx2. 64bit would be nice for some aspects but it's not that straightforward to convert the recompiler to x64. How performance of such a x64 build would be in comparison to a x86 build is as well unknown.

The best place to ask questions is however the forum and not this bugtracker.

**Comment by kwstas86** [comment]
ah sorry:S

**Comment by gregory38** [comment]
Besides memory usage was greatly reduce in recent build. So 4GB is likely enough
