### ISSUE TITLE
[SLUS-20957] Scaler - Glow Issue

### ISSUE THREAD

**Issue by lukie123** [PCSX2/pcsx2#2460]
PCSX2 version:
v1.5.0-dev-2393-g810bec2d6

PCSX2 options:
Safest.

Plugins used:
Default plugins. Software renderers work fine, the issue is only present on hardware renderers (both Direct3D and OpenGL).

Description of the issue:
All objects and characters in the game have a glow around them to make them look more vibrant, but in the emulator, this glow is misplaced and can be seen as a sort of shadow as evidenced by the png's attached in the dumps. The main character, the fauna, and even the glowing orbs (currency of the game) all have a misplaced afterimage glow.

I attached two GS dumps which exhibit the issue, though in reality, the issue is present in every single part of the game.

Last known version to work:
I did not check.

PC Specifications:
CPU: Intel i5-2500k, 3.4GHz
GPU: MSI GTX1050Ti 4GB
RAM: 4GB
OS: Windows 10 64 Bit

GS Dumps:
[SLUS-20957 - Scaler Glow Issue1.zip](https://github.com/PCSX2/pcsx2/files/2042715/SLUS-20957.-.Scaler.Glow.Issue1.zip)
[SLUS-20957 - Scaler Glow Issue2.zip](https://github.com/PCSX2/pcsx2/files/2042717/SLUS-20957.-.Scaler.Glow.Issue2.zip)

**Comment by lightningterror** [comment]
This is an upscaling issue, did you try out the upscaling hacks ?
Merge sprite, Align sprite, Wild arms offset, tc offset, Half Pixel offset ?

**Comment by lukie123** [comment]
The Half Pixel offset hack fixed the issue, thanks. I was not aware of the hacks, sorry.

**Comment by lukie123** [comment]
The hacks do not actually fix the glow perfectly, but the effect is much better aligned. I assume I should still keep this issue closed right?
