### ISSUE TITLE
SLUS-20957 - Scaler Text Render Issue

### ISSUE THREAD

**Issue by lukie123** [PCSX2/pcsx2#2461]
PCSX2 version:
v1.5.0-dev-2393-g810bec2d6

PCSX2 options:
Safest.

Plugins used:
Default plugins. Issue is present on all renderers (both software and hardware). HW hacks do not fix the issue.

Description of the issue:
In the evolution menu, used to upgrade the main character's abilities, when you select the upgrade you want to buy, the name of the upgrade and its cost are not rendered. The other non-selected upgrades are rendered fine before you select them.

Last known version to work:
I did not check.

PC Specifications:
CPU: Intel i5-2500k, 3.4GHz
GPU: MSI GTX1050Ti 4GB
RAM: 4GB
OS: Windows 10 64 Bit

GS dump:
[SLUS-20957 - Scaler Text Render Issue.zip](https://github.com/PCSX2/pcsx2/files/2042738/SLUS-20957.-.Scaler.Text.Render.Issue.zip)

Save state at evolution menu:
[SLUS-20957 (C3ACD5FA).09.zip](https://github.com/PCSX2/pcsx2/files/2042741/SLUS-20957.C3ACD5FA.09.zip)

**Comment by lightningterror** [comment]
That's a big commit ... anyway most of the changes are for ps1 compatibility, gui and name changing so it shouldn't be too difficult to track down, are you sure it's that commit ?

**Comment by prafullpcsx2** [comment]
On further testing it seems the above reported commit may not be the reason for this bug. Software mode seems to be broken forever. It was working with HW mode for sometime but it may have been working due to incorrect emulation causing other problems.

**Comment by prafullpcsx2** [comment]
The issue still exists. Here is a new savestate if anyone wants to have a look.

[SLUS-20957 - (C3ACD5FA).zip](https://github.com/PCSX2/pcsx2/files/7785212/SLUS-20957.-.C3ACD5FA.zip)

**Comment by prafullpcsx2** [comment]
Fixed with https://github.com/PCSX2/pcsx2/pull/5338
