### ISSUE TITLE
[Feature Request] Option to Export/Import Settings.  

### ISSUE THREAD

**Issue by Chibidaki** [PCSX2/pcsx2#2463]
Option to export/Import settings for Emulation/Plugins to a file, and later upload the file with a link to https://wiki.pcsx2.net/Category:Playable_games 
That should make things easier for both devs & users.

**Comment by lightningterror** [comment]
Seems a bit useless.

* Settings are stored in ini files. If requested users can upload the ini files but we usually ask for emulogs.
* Some games require specific options enabled but usually the default options work the best.

**Comment by Chibidaki** [comment]
- Well then Group all files into to one file. 

-  Add an error message like plugin *.dll not found or version mismatch if there are settings to a specific version of PCSX2.

**Comment by Chibidaki** [comment]
@lightningterror wouldnt .lua be a better format? i mean .ini are sooo old.
