### ISSUE TITLE
Debugger - Assemble Opcode Bug

### ISSUE THREAD

**Issue by PGAnonamous** [PCSX2/pcsx2#2466]
***PCSX2 version:***
stable 1.4 and current development build. 

This is more of an annoyance during debugging. The debugger doesn't allow all the instructions that is displays. For example, it will display the following instruction:

li  t6, 0x1

However while attempting to assemble this opcode you are met with the "Invalid Opcode" error. In order to get this opcode one must assemble the following instruction:

addiu  t6, zero, 0x1

I am aware that the debugger is not a feature that is commonly used but if the assemble opcode can be fixed to take the same opcodes it displays I would greatly appreciate it.

Thank you,
Anonamous

**Comment by gregory38** [comment]
Actually there is a define/global var to select between raw behavior and simplified (as more readable) view

**Comment by PGAnonamous** [comment]
@gregory38  Oh, I didn't notice. Which file is the var in?

**Comment by gregory38** [comment]
I think code is generated in `DisR5900asm.cpp`. However it isn't a global var anymore. Instead it is set by `disR5900Fasm` function. Maybe you could try to force `disSimplify` to false

**Comment by PGAnonamous** [comment]
@gregory38 Ok, thank you.
