### ISSUE TITLE
GSdx: harry potter and the chamber of secrets [Jap version]: multiple issues

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2470]
***PCSX2 version:***
PCSX2 1.5dev 2400

***PCSX2 options:***
All defaults, tested with and without speedhacks.

***Plugins used:***
All defaults

***Description of the issue:***
The game "Harry potter and the chamber of secrets have multiple issues in PCSX2:

-Distant texture flickering with GSDX hardware modes.

-Upscalling issues in some places (Blue lines on the water).

![capture4](https://user-images.githubusercontent.com/26351275/40889044-4de447fc-6760-11e8-8c65-841448091918.PNG)

-Missing fonts in the memorycard screen (do not seems related to GSDX because they are missing even in software). [Widescreen patches]

![capture3](https://user-images.githubusercontent.com/26351275/40889066-84fd9be4-6760-11e8-9cba-3969cf2a7b00.PNG)

-Non-fatal TLB misses and vif1 unknown CMD.

***How to reproduce the issue:***
Load "Harry Potter and the chamber of secrets".

***Not a regression***

***PC specifications:***
AMD fx8350 GTX 1060 Windows 10 64bits

***Blockdump+savestate***
https://drive.google.com/open?id=19d3bjMzsfEY_7MObWubTtb1oGpLwPoG3

**Comment by lightningterror** [comment]
The US and EU versions don't have these issues ?

**Comment by atomic83GitHub** [comment]
I don't know. I haven't these version of that game.

**Comment by lightningterror** [comment]
See if this works. Extract and add it to cheats.

[E90BE9F8.zip](https://github.com/PCSX2/pcsx2/files/2084346/E90BE9F8.zip)

**Comment by atomic83GitHub** [comment]
Your patch don't work.

**Comment by atomic83GitHub** [comment]
Sorry about the missing fonts, they are caused by widescreen patches. And about the blue lines, only the merge sprite hack have a small effect.

As a side note, can you do a PR to automatically add the Mipmapping to basic for this game (and the other version as well)? It is needed to avoids abysmal speed drop throughout the game.

**Comment by MrCK1** [comment]
We usually only add it if there's graphical issues - are there corrupted textures with mipmapping disabled? I don't think I've encountered a case where mipmapping causes a speed issue.

**Comment by atomic83GitHub** [comment]
No, the game don't exibit graphical issues with it disable. But look at the speed I get without and with it:

With it enable:

![capture](https://user-images.githubusercontent.com/26351275/43097064-361e3e5c-8ebb-11e8-89b7-fe46d331d23e.PNG)

With it disable:

![capture2](https://user-images.githubusercontent.com/26351275/43097080-43ef7a78-8ebb-11e8-939d-5dbe8b8c95c6.PNG)

**Comment by lightningterror** [comment]
I added the game to mipmapping basic, as for the ws patch it's best to let Devina know about the issue on the WS patches thread on the forum.

Are you using the Frame Buffer Conversion hack ?

**Comment by atomic83GitHub** [comment]
I will write a post on this topic, and about the Frame Buffer Conversion hack, yeah I use it on this game or the right side of the screen will be a glitchy mess.
