### ISSUE TITLE
Appimage for linux

### ISSUE THREAD

**Issue by henres** [PCSX2/pcsx2#2473]
Hello,

It's not for an issue. But to ask for a feature.

Is it possible to have pcsx2 Bundle as an AppImage ?

**Comment by Ashleyz4** [comment]
Considering not many people use x86 linux much anymore, I'm unsure if they're even going to bother since pcsx2 isn't going to work with linux x64 systems properly. Unless they can compile the depends with it?

**Comment by lightningterror** [comment]
Closing in favor of #2655
Duplicate.
