### ISSUE TITLE
God of War II flashes during Dark Rider fight are blank in HW renderer

### ISSUE THREAD

**Issue by feikname** [PCSX2/pcsx2#2476]
***PCSX2 version:*** PCSX2 1.5.0-20180608225456 - compiled on Jun  8 2018

***PCSX2 options:*** Preset 2 (safe)

***Plugins used:*** Default ones from the build provided by https://buildbot.orphis.net/pcsx2/

GSDX with everything on auto, no hardware hacks and in native resolution.

***Description of the issue:***
What it should look like: (or what it looks like in SW mode at least)
![image](https://user-images.githubusercontent.com/4926869/41189770-617243ee-6ba9-11e8-95a1-d71ddfc6d4c1.png)

How it is rendered in HW mode with Direct3D 11:
![image](https://user-images.githubusercontent.com/4926869/41189799-c44186a6-6ba9-11e8-977d-03fdd6890a27.png)

OpenGL HW renderer seems to get the top part right at least.

Dump: [gsdx_dump_god_of_war_II_black_rider_fight_white_bg.zip](https://github.com/PCSX2/pcsx2/files/2086798/gsdx_dump_god_of_war_II_black_rider_fight_white_bg.zip) ([alternate mirror on GDrive](https://drive.google.com/file/d/138GlCeUIZ3cyfVgzGK5nonXi8bDoTciZ/view?usp=sharing))

***How to reproduce the issue:***

Load God of War II with GSDX HW renderer and play the Dark Rider battle scene.

***Last known version to work:*** Not tested with previous versions

***PC specifications:*** Intel Core i5-8250U; Intel UHD Graphics 620 & AMD Radeon 530; Windows 10 64-bit

**Comment by lightningterror** [comment]
Why did you duplicate the issue ?

**Comment by feikname** [comment]
I split it in two different issues, one for the rendering and another about the state being inverted, since they seem like two different issue to me.

**Comment by Syst3mSh0ck** [comment]
Try the Alpha hw hack.

**Comment by feikname** [comment]
> Try the Alpha hw hack.
No changes, still white.

**Comment by lightningterror** [comment]
Preload frame, auto flush, frame buffer conversion ?

**Comment by feikname** [comment]
@lightningterror Can I enable them all at same time or should I test them one by one?

**Comment by lightningterror** [comment]
One by one

**Comment by feikname** [comment]
None of the HW hacks checkboxes changed anything, background still white.

**Comment by lightningterror** [comment]
Needs high blending, opengl only.
