### ISSUE TITLE
BUZZ: add feature to play this game without buzzer

### ISSUE THREAD

**Issue by legluondunet** [PCSX2/pcsx2#2477]
Hello,
to play the game Buzz:
https://www.youtube.com/watch?v=tYrSzZPOWH8
You need buzzers: 
https://www.priceminister.com/offer/buy/60850401/Buzz-Le-Mega-Quiz-4-Buzzers-Jeu.html?t=180155&gclid=CjwKCAjw9e3YBRBcEiwAzjCJum1A74E1DM7aXb4SRKD14hycMSi6bC_TdyBDqg1b-DVsd8GQJdxUIxoCw_8QAvD_BwE&bbaid=3876089813&sort=0&xtatc=PUB-%5Bggp%5D-%5BJeux-Video-et-Consoles%5D-%5BJeux-Video%5D-%5B60850401%5D-%5Boccasion%5D-%5BTop_Occasion%5D&ptnrid=sFXtfLOyC_dc|pcrid|110445489683|pkw||pmt|

You can not play this game if the game does not detect buzzers, that's the case on PCSX2.
Could it be possible to simulate buzzers so we can play the game? The input will be redirected to a gamepad.

Regards.

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by willkuer** [comment]
Maybe @prafullpcsx2 has the game and an idea?

**Comment by nevespt** [comment]
some kinda of emulate like with the guitar
