### ISSUE TITLE
Moorhuhn Fun Kart 2008/ Characters Always Fall in the Ground At Start Of Race

### ISSUE THREAD

**Issue by kameeol** [PCSX2/pcsx2#2479]
***PCSX2 version:***
PCSX2 v1.5.0-dev-2405-g1c58d5acf = June 8 2018

- **Notes**:
 If Somebody Knows How To Fix This I Will Gladly Appreciate it

***PCSX2 options:***
Default everything

***Plugins used:***
Default everything

***Description of the issue:***
![image](https://user-images.githubusercontent.com/40147490/41204566-eec30886-6c9a-11e8-82a6-e65cd3528f3f.png)                                                                                                                                  
    These errors show up every time the characters fall into the world.                                                    
                       ODE Message 3: LCP internal error, s <= 0 (s=-3.4028e+38)
 
![image](https://user-images.githubusercontent.com/40147490/41204654-2723104e-6c9c-11e8-9863-c4cc9fc742e8.png)
This Is One In Time Trial Mode By My Self Unmoved 
![image](https://user-images.githubusercontent.com/40147490/41204872-0e9ccb70-6c9f-11e8-87b2-2bafd7055ad6.png)
This Is What Happens When I Start To Move  
![image](https://user-images.githubusercontent.com/40147490/41204893-705be0c6-6c9f-11e8-8e9f-0ce614763524.png)
         And it Still Gives Me This Same Error: ODE Message 3: LCP internal error, s <= 0 (s=-3.4028e+38)
***How to reproduce the issue:***
Not Sure

***Last known version to work:***
Not Sure

***PC specifications:***
	Windows 10 Home 64-bit

	AMD Phenom II X4 965	
	Deneb 45nm Technology

	8.00GB Dual-Channel DDR3 
	Gigabyte Technology Co. Ltd. GA-870A-UD3 	
	
	2047MB NVIDIA GeForce GTX 1050

**Comment by willkuer** [comment]
Have you tried different ee clamping and rounding modes?

**Comment by kameeol** [comment]
will try now

**Comment by kameeol** [comment]
thanks it worked fine and i stayed on track

**Comment by lightningterror** [comment]
Which option worked ?

**Comment by kameeol** [comment]
Clamping = positive and Rounding = Full I Used both of those

**Comment by kameeol** [comment]
Sorry meant for the Clamping i used Full And the Rounding I used Positive

**Comment by lightningterror** [comment]
Are both of them needed ? Try to narrow down which actually impacts the game.

**Comment by kameeol** [comment]
I only needed to change clamping from normal to full so only clamping needs to be changed not the rounding

**Comment by kameeol** [comment]
changing clamping from normal to full impacts the game to work correctly

**Comment by MrCK1** [comment]
Which clamping did you change, EE or VU?

**Comment by kameeol** [comment]
EE

**Comment by kameeol** [comment]
hold on

**Comment by kameeol** [comment]
what would the serial be like this?  SLES_551.22;1

**Comment by kameeol** [comment]
was that the serial?

**Comment by lightningterror** [comment]
Latest build should be good.
