### ISSUE TITLE
[Linux] No Mouse Grab When Using Mouse for Joystick

### ISSUE THREAD

**Issue by PistolRcks** [PCSX2/pcsx2#2485]
***PCSX2 version:***
Development build 1.5.0-0 (git) from the Ubuntu nightly build repo

***Plugins used:***
PAD: OnePad 0 2.0.0

***Description of the issue:***
PCSX2 does not grab the mouse when using the mouse for joystick control, requiring the user to move their mouse to the edge of the screen to move it.

***How to reproduce the issue:***
In "Right Joystick Config", select "Use mouse for right analog joystick." 

***PC specifications:***
CPU: Intel i5-4210M
GPU: Nvidia GeForce GTX 860M
OS: Ubuntu Budgie 18.04

**Comment by gregory38** [comment]
hum, try "ctrl-shift F12", it might do the trick

**Comment by PistolRcks** [comment]
@gregory38 That didn't do anything (and I accidentally pressed ctrl-alt-F12 and had to restart my computer in the process)

**Comment by RedDevilus** [comment]
What's the status of your issue?

**Comment by PistolRcks** [comment]
The functionality remains the same. However, I now believe the current functionality (that is, that the mouse is not grabbed and stick inputs are performed when the mouse cursor reaches the edge of the screen) is how it was always meant to be.
Additionally, mousegrab _is_ already a functionality of the LilyPad plugin, and is the reason why stuff like https://github.com/isJuhn/KAMI exists.

This issue will now be closed, as it is no longer applicable.
