### ISSUE TITLE
Jak and Daxter 1/2: Random PCSX2 hang in large open areas.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2489]
***PCSX2 version:***
1.5dev 2425

***PCSX2 options:***
All default

***Plugins used:***
All default

***Description of the issue:***
Randomly throughout the game, PCSX2 can freeze and shut down itself

***How to reproduce the issue:***
Load "Jak1" or "Jak2" and walk in a large area

***Last known version to work:***
It does not happen before as far I know, I will try to find the culprit build

***PC specifications:***
AMD fx8350 GTX 1060 Windows 10 64bits

**Comment by MrCK1** [comment]
Is it a consistent crash or did it only happen once - are you able to reproduce it? 

It's somewhat normal for PCSX2 to crash randomly once in a blue moon during longer sessions.

**Comment by atomic83GitHub** [comment]
It is very inconsistent, sometimes it happen just a couple of seconds after going ingame, sometimes much later. Also, the crash seems to happen only with OpenGL.

**Comment by MrCK1** [comment]
It sounds more like a random GSdx crash. I've had it happen in a few games, so I'll look at Jak 1 later. If this ends up being the case, then it can pretty much be ignored for now.

**Comment by atomic83GitHub** [comment]
Related to https://github.com/PCSX2/pcsx2/issues/2848
