### ISSUE TITLE
Locale files have unclear licensing

### ISSUE THREAD

**Issue by DafabHoid** [PCSX2/pcsx2#2493]
***Description of the issue:***
Two files have missing/unclear copyright and license statements. This makes them strictly speaking not redistributable under the GPL.  
These two files only have a standard template header:
- locales/es_ES/pcsx2_Iconized.po
- locales/es_ES/pcsx2_Main.po

The header is

    # SOME DESCRIPTIVE TITLE.
    # Copyright (C) YEAR PCSX2_Dev_Team
    # This file is distributed under the same license as the PACKAGE package.
    # FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.

which looks like a template, that never got filled with the appropriate information about the author and the license (although PACKAGE can be guessed as PCSX2 by comparing it to the other locales).
Just to be on the safe side, these files should be correctly licensed.

**Comment by lightningterror** [comment]
It's not just Spanish that needs to be fixed.

https://github.com/PCSX2/pcsx2/search?p=1&q=SOME+DESCRIPTIVE+TITLE.&unscoped_q=SOME+DESCRIPTIVE+TITLE.

**Comment by mirh** [comment]
I'm pretty sure header would just matter if "overriding" the default license of the repo..
But it makes 0 sense to say not explicitizing it would make void the same license contributors should have had to agree in the first place to commit.

**Comment by mirh** [comment]
> Did I miss it?

It's *entailed*, just like "standard copyright" applies by default unless otherwise noted (like indeed the license under which the whole emulator is released)

**Comment by lightningterror** [comment]
Closing in favor of #950
