### ISSUE TITLE
Invisible preset slider in v1.5.0-dev-2340-g1fefb4897 with Arch Linux and Xfce DE

### ISSUE THREAD

**Issue by minecraft2048** [PCSX2/pcsx2#2496]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``
v1.5.0-dev-2340-g1fefb4897

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

That space between that preset checkbox and that green preset name is actually a slider to change the presets from safe to unsafe, and for some reason it is invisible in my setup with Xfce DE. 

![invisible](https://user-images.githubusercontent.com/2445636/42192329-85af686c-7eab-11e8-9320-e2add55b54ed.png)

Its supposed to be visible like this:

![pcsx2-speed-hacks2](https://user-images.githubusercontent.com/2445636/42192390-f73cf724-7eab-11e8-86ad-889751e753ae.png)

This is probably related to this issue: 
https://github.com/PCSX2/pcsx2/issues/2450

I installed this by using `pcsx2-git` from AUR

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Arch Linux running Xfce DE

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by F0bes** [comment]
I haven't been able to reproduce this on manjaro xfce, kde, or deepin, can you tell us if this still is a probem?

**Comment by F0bes** [comment]
Closing as I haven't been able to reproduce.
