### ISSUE TITLE
implement auto-detection BIOS pal-ntsc

### ISSUE THREAD

**Issue by mkultimate** [PCSX2/pcsx2#2500]
there will be a possibility to implement a bios auto detection function by means of slus or sles for the versions pal and ntsc would be a very good option because some games need to run fullboot to detect the spanish language example god of war I think it would help ??

**Comment by MrCK1** [comment]
I'm not sure what you're trying to say. If a game requires full boot, then there's no way around that currently

**Comment by mkultimate** [comment]
I think it is possible, because there are players that use game organizers, such as launchbox.

if I want to play a ntsc game, I have to change the bios for the ntsc version, example tony hack.

but if I want to play god of war in the Spanish version I must change the bios to pal and use it in fullboot, just imagine having 200 ps2 games and I want to have them organized without the need to change the bios and let everyone execute in fullboot.

**Comment by kenshen112** [comment]
So you know pcsx2 is region free right? Like you don't have to switch the bios to play those games at all.

**Comment by mkultimate** [comment]
I'm not a programmer but I give an idea that I think is possible, if I were a programmer I would try.

I congratulate you for your great work in this emulator

**Comment by lightningterror** [comment]
It's a bit rare to have multiple consoles with different regions, and given that people usually have 1 bios version this is really low priority.

It will be better to find a solution to improve fast boot so the games work.

I'm closing this one unless someone disagrees.

**Comment by mkultimate** [comment]
@lightningterror It is not a low priority, as mentioned above many of us use game organizers like the launchbox where if we put the god of war 1 game to have the Spanish language it is necessary to enter the bios and place the EUR roms and execute in fullboot and placing a command in the launchbox, but if I want to play an NTFS game, it's time to enter the launchbox again and remove the fullboot command or change the bios to run in NTSC because if it is in fullboot the game will not start

**Comment by mkultimate** [comment]
command fullboot

![image](https://user-images.githubusercontent.com/16367065/42456615-fafb613a-835a-11e8-85f4-ceb6304370db.png)

commando full boot to start the game in Spanish because it only works is executing it that way and it is not the only game many use this tool to have organized the games, to be able to play another game you need to remove the command because the games with ntsc do not start in fullboot because it's time to change the bios for the USA version

**Comment by kenshen112** [comment]
You don't need to do any of that use fast boot and pcsx2 is region free

**Comment by mkultimate** [comment]
any solution?? because it plays to do this for many ps2 games and I'm not the only one who goes through this problem with games that have a language and play them in fullboot to be able to use the language since they do not have a language selector like other games so it's up to do this manual for the 200 games :( enter and change the bios just time Oo

**Comment by mkultimate** [comment]
@kenshen112 
GAME: Tony Hawk NTSC command fullboot bios 
Bios: EUR
in this game there are 2 ways to remove the command full boot or change the bios, just imagine performing an arcade to play all these titles of games

![image](https://user-images.githubusercontent.com/16367065/42457246-935063bc-835c-11e8-8e31-7e8c7a53437a.png)


Note: these games do not have a language selection, so many games do this
GAME: God Of War 1 command fullboot disabled
![image](https://user-images.githubusercontent.com/16367065/42457342-e26e9c0c-835c-11e8-8b29-9a0d5af10762.png)

GAME: God Of War 1 command fullboot enabled
![image](https://user-images.githubusercontent.com/16367065/42457431-12e6e24a-835d-11e8-9585-cd4ad5cf4b0d.png)

GAME: Gradius V command fullboot enabled
![image](https://user-images.githubusercontent.com/16367065/42457522-4fa0bd96-835d-11e8-8ca1-a487f56ab220.png)

GAME: Gradius V command fullboot disabled
![image](https://user-images.githubusercontent.com/16367065/42457629-8ef58f6c-835d-11e8-8209-ce3549c24876.png)

**Comment by willkuer** [comment]
The point is that you request something that is beyond fast boot which is already beyond what your ps2 is able to do.

I'd say it's very uncommon that you have games from different regions as they don't run on the region-locked consoles that are sold where you live. That means you need to import games in order to create this situation which is probably only reasonable for a few asia-only games.

Typically however you can setup frontends in a way that you can adjust the ini they are referring to. In one of the pcsx2 ini's the path to the bios is saved. So you just need to have two different ini versions for two different bios versions and reference the right ini for the right game.

Additionally your feature request is not completely described. How should it work for example if there are no other matching bios versions available? Should pcsx2 switch to ntsc-u for a ntsc-j game if you are currently running on a pal bios and only the ntsc-u bios is available? What happens if you have different versions of the same regionized bios? What happens if you have for one bios only the raw bios file but not the other configuration files?

**Comment by mkultimate** [comment]
about the configurations of ini I already knew, the only option that would be good to add is custom profile as some emulators have the option of placing a unique profile for each game as well as memori cards would be a good alternative

**Comment by lightningterror** [comment]
Spectabs is good for that.

**Comment by mkultimate** [comment]
looking in google I found this plugin for the launchbox https://github.com/roguesaloon/launchbox-plugin_pcsx2-configurator where you can place a unique profile for each game with this add-on solves the problem you had in mind thanks very much for your help and your time for your answers.
