### ISSUE TITLE
About the PCSX2 1.5.0 Best Requirement.

### ISSUE THREAD

**Issue by SonicThePS4** [PCSX2/pcsx2#2506]
I'm sorry. But I was wondering what's best settings for Weak PC's? 'cause Any Hardware Mode & Any Software Mode they both run really slow, unfortunately. And I dunno what's the best settings for the Frameskips. 

My PC Specs-
4GB RAM 
1TB Hard-Drive 
AMD Athlon(tm) II X2 250u 1.60 Ghz Processor.
AMD Vision Brand. ATI Mobility Readon HD 4200

**Comment by bositman** [comment]
This isn't the place for support. Use our forums:
https://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows
