### ISSUE TITLE
[Linux] Segfault when attempting to configure PS3 controller 'Config>Controllers (Pad)>Plugin Settings'

### ISSUE THREAD

**Issue by jdydsco** [PCSX2/pcsx2#2508]
***PCSX2 version:***
Stable build v1.4.0, Fedora 28 (Linux)
OnePAD 0-Dev 1.1.0 (according to Config>Controllers (Pad) menu)

***PCSX2 options:***
Everything on default, new install

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``
N/A, everything on default settings/configuration

***Description of the issue:***
I installed pcsx2 from the Fedora repository (v1.4.0), and am trying to play with my PS3 controller. My controller is recognized by the OS, but when I try to enable it by going into the Gamepad settings (Config>Controllers (Pad)>Plugin Settings) the program crashes (it crashes as soon as you click 'Plugin Settings').

If I run PCSX2 through gdb to debug the issue, [this is the output](https://pastebin.com/kRLNRVgw)

[Here is a core dump that got created](https://transfer.sh/121BuH/core.PCSX2.1000.24bb729a92904b1fafd3c9b4170f5ee9.25756.1531690085000000.lz4)

***Last known version to work:***
N/A

***PC specifications:***
CPU: Intel 8550u, 16GB ram, Fedora 28 Linux (64 bit)

**Comment by turtleli** [comment]
This is probably the same issue as #2157 - wxWidgets is linked to SDL2 but OnePad is linked to SDL1.2. It should be fixed in the master branch since commit 41c49faa81d4970e903e7d85616774c979e103a5.

**Comment by sergiomb2** [comment]
Hello 
TIL , wxWidgets use on SDL , and we should build all PCSX2 with same SDL of wxWidgets . 
Fedora have wxGTK-2.8 and wxGTK-3.x , and wxGTK-3.x compiled with gtk2 and gtk3 i.e
Packages wxGTK-devel, compat-wxGTK3-gtk2-devel and wxGTK3-devel and we should build with SDL according what wxGTK requires .

on Fedora 27  compat-wxGTK3-gtk2 requires SDL1 and on Fedora 28 compat-wxGTK3-gtk2 requires SDL2, wxGTK always requires  SDL1  and wxGTK3 always requires SDL2 (last 2 i guess)

**Comment by orbea** [comment]
@sergiomb2 I would suggest that fedora uses a git snapshot, the last release of pcsx2 is old and a lot of bugs have been fixed since then.

**Comment by sergiomb2** [comment]
I just need a tag , to do that .

**Comment by orbea** [comment]
You can get a tarball from any commit.

https://github.com/PCSX2/pcsx2/archive/1498f53/pcsx2-1498f538dd14667bd6c548560418e16016d92f31.tar.gz

Or you could always clone the repo and make a tarball yourself.

You can also get a useful version with git.
```
$ HEAD="$(git rev-parse --short HEAD)"
$ DATE="$(git show -s --format=%cd --date=format:%Y.%m.%d)"
$ VERSION="${DATE}_$HEAD"
$ echo $VERSION 
2018.08.16_b84a2cfaf
```
It would be nice if there was a new tag, but I'm not sure when that is going to happen and I don't have anymore influence over the process than you.

**Comment by sergiomb2** [comment]
I know that very well , 
but as packager we don't work with commits unless you just commit once per month at most .
you may go to https://github.com/PCSX2/pcsx2/releases and click create a new tag with last commit , and you may call the hyper super pre alpha release , but I may use tag and tag every week I will pick the tags , but I won't pack every time we got a new commit
