### ISSUE TITLE
Deus Ex The Conspiracy - rendering problems in sw/hw modes (bad shadowings?)

### ISSUE THREAD

**Issue by Demos25** [PCSX2/pcsx2#2515]
***PCSX2 version:***
v1.5.0-dev-2445-g4ebdceffd

***PCSX2 options:***
No speedhacks, default EE/EOP settings, default VUs settings, default GS settings + Native resolution ON.

***Plugins used:***
GSdx 20180715220308 (MSVC 19 SSE4.1/AVX) 1.1.0 [GSdx32-SSE4]

Direct3D 11 Software/ Hardware modes. Texture Filtering: Bilinear (PS2) + Native resolition

***Description of the issue:***
Problems in GS SW mode:
![gsdx_20180718211539](https://user-images.githubusercontent.com/26468105/42900034-804e71b6-8ad0-11e8-85f0-037ac81e2788.png)
texture diffusions under different lighting conditions.

Problems in GS HW mode:
![gsdx_20180718211257](https://user-images.githubusercontent.com/26468105/42900089-b36616d0-8ad0-11e8-9af3-e95605e81229.png)
Random texture glitches, black squares

***How to reproduce the issue:***
It's on the first stage

***Last known version to work:***
Have no ideas

***PC specifications:***
Intel Core i5 3330 3.5Ghz; 8192MB DDR3 RAM 1600Mhz DC; GeForce GTX 650 Ti 2048MB GDDR5; Win7 x64

**Comment by MrCK1** [comment]
Try switching to OpenGL?

**Comment by Demos25** [comment]
@MrCK1 same result in OGL SW mode, but the black squares seems fixed in OGL HW

**Comment by willkuer** [comment]
The texture diffusion problem is not just because of low-quality textures? Maybe I am missing something but blurry textures aren't that uncommon on a ps2 (because of the lower native resolution in combination with interlacing).

**Comment by Demos25** [comment]
that's what I had tried to say
![1](https://user-images.githubusercontent.com/26468105/42913413-8c9b976e-8afd-11e8-80f4-ff0b0c0d7ff9.gif)
![2](https://user-images.githubusercontent.com/26468105/42913416-913bfe8a-8afd-11e8-8f7d-72f887de67e0.gif)

**Comment by MrCK1** [comment]
That looks like Z-fighting or it could just be a blending artifact

**Comment by Demos25** [comment]
@MrCK1 I had switched it from auto to anything else - nothing changed

**Comment by MrCK1** [comment]
None of the issues here were present for me, closing.
