### ISSUE TITLE
Visual Studio 2018: Spu2-X (plugin-solution) --> WinConfig.h , SndOut_XAudio2_27.cpp

### ISSUE THREAD

**Issue by d3vv** [PCSX2/pcsx2#2517]
Need to remove or undefine code below for msvc > 2015 :

```
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0600
#endif
```
into WinConfig.h  to escape an error on modern (Microsoft supported) OS:

```
11>SndOut_XAudio2_27.cpp
11>c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\xaudio2.h(20): fatal error C1189: #error:  "This version of XAudio2 is available only in Windows 8 or later. Use the XAudio2 headers and libraries from the DirectX SDK with applications that target Windows 7 and earlier versions."
11>Done building project "Spu2-X.vcxproj" -- FAILED.

```

Moreover need to resolve this "stub" into SndOut_XAudio2_27.cpp which breaks the build:

```
#if _WIN32_WINNT >= 0x602
#error Time to remove this module.
#endif

```

**Comment by refractionpcsx2** [comment]
If you link your dx libraries properly, you don't get that error

**Comment by d3vv** [comment]
I have no libraries for end-line unsupported products

**Comment by lightningterror** [comment]
You need the DirectX SDK to compile SPU2-X.
https://www.microsoft.com/en-us/download/details.aspx?id=6812

Btw you don't need to compile the entire solution if you want to compile GSdx, you can just compile the GSdx plugin on it's own without getting the DX sdk.

Closing this since it's not an actual issue.

**Comment by d3vv** [comment]
Not impossible to install on Window 10 this DirectX SDK properly and moreover to use with visual studio 2017

**Comment by lightningterror** [comment]
To install it properly you gotta remove any previous versions of 2010 Visual C++ Redistributables.

**Comment by d3vv** [comment]
Yes, of course... But sounds like dirty hack... and in any cases you can't choose this SDK in msvc 2017 into Solution... There is no problem to use both legacy and latest SDK into sources… But why we must (not could) to use this one only?

**Comment by lightningterror** [comment]
> There is no problem to use both legacy and latest SDK into sources…

It should work. We managed to remove the requirement on other plugins except spu2-x. #564
It's not ideal but like I said you don't need to compile the entire solution, you can just compile what you need.

**Comment by d3vv** [comment]
you just restricted builds on modern systems via defines

**Comment by d3vv** [comment]
if you remove "define-embargo" against "Invalid Closed Issue", I will try to help you/us resolve something not only for windows..
