### ISSUE TITLE
Over the hedge just freezes whenever it feels like it.

### ISSUE THREAD

**Issue by ZombiePwner1** [PCSX2/pcsx2#2518]
***PCSX2 version:***
1.4.0

***PCSX2 options:***

Speed hacks is on 2 safe (faster)

***Description of the issue:***
The game just randomly freezes when it wants to. I go to start it up and everything is fine once I get to the menu and start a new game the new game will start then after the cutscene I can play the level but then the game will choose to freeze on it's own randomly.

***How to reproduce the issue:***
No known ways to reproduce.

***Last known version to work:***
I don't know about other versions as version 1.4.0 is the first version I've started with.

***PC specifications:***
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz 2.70 GHz

Installed ram 8.00 GB's

System is a 64bit operating system x64-based processor

**Comment by MrCK1** [comment]
Try using a 1.5.0 dev build, I tested it s few months ago and it was fine.

**Comment by ZombiePwner1** [comment]
@MrCK1 Turns out I fixed it an it seems to be a bug with the emulator itself. The MTVU was the problem and I'd recommend to be fixed.
