### ISSUE TITLE
GzipIsoIndexTemplate doesn't seem to work under Linux

### ISSUE THREAD

**Issue by iokzero** [PCSX2/pcsx2#2519]
***PCSX2 version:***
`development builds v1.5.0-20280712010509

***PCSX2 options:***
Default

***How to reproduce the issue:***
Pick an GZ iso file
System > Boot ISO (fast) 

a pindex.tmp file will be generated on the same directory as the GZ iso file, instead of the directory set under GzipIsoIndexTemplate such as:

GzipIsoIndexTemplate=/home/xuser/.config/PSCX2/pindex/$(f).pindex.tmp

$(f).pindex option doesn't seem makes any different, (Also what it mean by - a popular request? Need actual description for such template option) 

***Last known version to work:***
N/A, all the example listed under comments seem only meant for Windows. 

***PC specifications:***
Any Linux OS.

**Comment by avih** [comment]
Can anyone with PCSX2 on linux confirm this? I think it shouldn't be hard to debug (on linux) if confirmed.

**Comment by turtleli** [comment]
Behaviour is different on my end.

I used `GzipIsoIndexTemplate=/home/turtleli/.config/PCSX2/pindex/$(f).pindex.tmp`.

If the directory exists - it works.
If the directory doesn't exist - it fails and no index file is generated.

**Comment by avih** [comment]
> If the directory doesn't exist - it fails

Yeah, even if suboptimal, it's as intended. It uses the template if it ends up as writable file path, but doesn't create the path/dir if it's missing.

**Comment by iokzero** [comment]
Thank you so much for the help, 

I try to delete /.config/PSCX2 folder, and after I restart PSCX2 and reset everything. All sudden everything works as intended. 

Not sure why's that, the Template is exactly the same.

**Comment by avih** [comment]
Feel free to request to re-open if this issue happens again.
