### ISSUE TITLE
.hack//g.u. series

### ISSUE THREAD

**Issue by DigresiveSin** [PCSX2/pcsx2#252]
I'm having an issue where the character alkaid has streams extending off her model. I tried enabling the nvidia hack I changed from software to hardware mode and tried different plug ins. Im using an nvidia geforce gt 610 the gsdx32 sse4 plug in rendering dirext3d11 hardware. Any help?

**Comment by bositman** [comment]
You didn't specify the actual game, build tested, etc. No one else has reported this so I'm closing it.

**Comment by Kosyne** [comment]
Got a similar issue here, PCSX2 1.4.0 (and latest git version as of yesterday), with all three .hack g.u. games concerning the character Alkaid.
The clothes physics on this character is messed up, and looking for similar issues it ranges from streams like DigresiveSin said, to the physics bits not appearing at all. In my case, everything showed up, but was jiggling uncontrollably.

Default settings (It's pushed back a bit, and is constantly wriggling here):
![kgvwu19](https://cloud.githubusercontent.com/assets/356616/15800197/5a69b1fe-2a38-11e6-8abd-439939d669cd.png)

Modified settings (intended look, played this on PS2):
![ehjbi6z](https://cloud.githubusercontent.com/assets/356616/15800199/72152338-2a38-11e6-880c-ca79caeccfc4.png)







The following settings seemed to fix it for the small time I've been able to test it:
![0g2k0km](https://cloud.githubusercontent.com/assets/356616/15800156/d53d3118-2a37-11e6-8169-6264edd16bbc.png)

If you need more information, let me know. I can say that searching around, I've seen at least 4 results of other people having similar issues.

**Comment by bositman** [comment]
Please check which one of the modified default settings in the above screenshot helps (is it clamping,EE FPU rounding or IOP interpreter?)

**Comment by Kosyne** [comment]
All three of them. Just changing any one of those from those specific values causes the problem to reappear.

**Comment by bositman** [comment]
If you change only rounding or only clamping from defaults?

**Comment by Kosyne** [comment]
Then the issue returns. They need to both be at those values.

**Comment by Merik2013** [comment]
It should be noted that this "fix" causes other things to bug out, like Sakaki's hair and Ovan's coat, both at the end of Vol 2. Also very notable is how they bug out Macha's "dress."
