### ISSUE TITLE
nothing option in gs option

### ISSUE THREAD

**Issue by blackinitial** [PCSX2/pcsx2#2520]
***PCSX2 version:***
stable build v1.4.0

***Plugins used:***
default plugins

***Description of the issue:***
i can't choose option GS (graphic setting) when first setting

***How to reproduce the issue:***
i copy all plugin PCSX2 in ``/usr/lib/games/PCSX2/*`` to ``~/.config/PCSX2/plugins/`` and set chmod plugins folder to 777 ``chmod 777 plugins ``. Then uncheck default setting and choose ~/.config/PCSX2/plugins/ folder. but still nothing option in GS option.

***PC specifications:***
OS : Linux MInt 17.3 
Spec: Laptop Lenovo 110-14AST,  AMD A9 4gb ram

**Comment by lightningterror** [comment]
Not an issue, use the forum for support questions.
https://forums.pcsx2.net/
