### ISSUE TITLE
Kenran Butousai Black Screen

### ISSUE THREAD

**Issue by SausageDog** [PCSX2/pcsx2#2522]
***PCSX2 version:***
v1.5.0-dev-2380-g9b8244954

***PCSX2 options:***
PCSX2 set to "safest" preset

***Plugins used:***
I've tried both GSDX Open GL Software and Open GL Hardware with default settings. I've also tried some of the HW Hacks for the Open GL Hardware, but none helped.
Default plugin settings for everything else.

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
The 5:20 minute mark of the below video shows what the scene looks like in PCSX2, i.e. black screen with only text showing properly.
https://youtu.be/iCovXYYNak8?t=318

The 2 minute mark of the below video shows what the scene is meant to look like on actual hardware, i.e. characters and environments showing properly:
https://www.youtube.com/watch?v=vs9meW9G1GY&feature=youtu.be&t=120

***How to reproduce the issue:***
Start the game. Keep accepting default options (see above Youtube video of PCSX2) until you get to the doctor's office. The screen will be black and you can't see what is going on.

***Last known version to work:***
This has never worked in any version I've tried.

***PC specifications:***
Windows 10 Professional, i5-4690, 16GB RAM, GTX 970.

**Comment by prafullpcsx2** [comment]
A savestate few seconds before the problem area may prove useful.

**Comment by lightningterror** [comment]
Software mode should work fine now, OpenGL has some issues, DX hw needs depth emulation to properly render the screen.

**Comment by SausageDog** [comment]
Thanks, lightningterror. Software mode appears to render as expected now. Hardware has lines all over it as per your comment, but you've got it playable now so very much appreciated.

I've attached a savestate as requested so that it's available in future. The save state is for the fixed build [v1.5.0-dev-2456-g0efbd283c](https://github.com/PCSX2/pcsx2/commit/0efbd283c4bca1596569269c699925a63996cdbb).

[SCPS-15085 (4BE2DE91).00.zip](https://github.com/PCSX2/pcsx2/files/2223104/SCPS-15085.4BE2DE91.00.zip)
