### ISSUE TITLE
God of War II : Vertical lines under water and in hell

### ISSUE THREAD

**Issue by ipokampo** [PCSX2/pcsx2#2533]
Hi, this issue is present for me using the PAL version of God of War II which is Interlaced isntead of Progressive, I don't know if this is affecting or not but is the only noticeable difference i can spot. 

It happens when scaling > 1x and also using custom resolution 4k. Native resolution obviously fixes it but is not the point here.

It happens in 1.3.0, 1.4.0 and 1.5.0 latest dev build and old trick CRC-Check 'Aggresive' does NOT fix it, vertical lines are still very present under water.

It happens using dx9, dx11, ogl, no matter what, it happens. Only software version removes it, but it think is due to the fact that it runs the game in native resolution rather than other explanation.

Help would be appreciated

**Comment by lightningterror** [comment]
Can you upload a GS dump ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

Preferably multiple frames.

**Comment by ipokampo** [comment]
Progressive did work as intended so here you have the required gs dump, i hope it could be clarified, and I'm glad that interlaced breaks the fix and we finally found, the cause at least :)

I hope soon i can finally play PAL version (interlaced) with 0 issues, thanks

https://www.dropbox.com/s/neyma5aq9q91n3d/GodOfWar2_VerticalLines_Issue_progressive.7z?dl=0

**Comment by lightningterror** [comment]
Latest build should work.

**Comment by ipokampo** [comment]
@lightningterror I can confirm the fix. Thanks for you're effort it was awesome to work with you to fix the bug.

**Comment by Helium-4** [comment]
Fixable without the CRC hack using the following settings, at-least in the US version in both interlaced and progressive mode.
![image](https://user-images.githubusercontent.com/30066566/53103395-dc758300-352d-11e9-95c2-9a508ae0f965.png)

**Comment by lightningterror** [comment]
Yes you're right.
