### ISSUE TITLE
[BUG] Scarface - Lighting Issues

### ISSUE THREAD

**Issue by georgeli94** [PCSX2/pcsx2#2538]
Sorry, was late last night, so I just wanted to get this issue out as fast as possible to get people to know about it. Here's my properly edited version

***PCSX2 version:***
1.5.0-dev-2464

***PCSX2 options:***
Speedhacks: Used all presets, image is left on speedhack 3.

Game fixes: Used Automatic Game Fixes and VU I Bit Hack dedicated for Scarface

***Plugins used:***
Only relevant is the various GSDX plugins. Swapped between AVX, AVX2, SSE2-4, SSSE3, etc. with every setting for renderer (OpenGL through the two Direct3Ds). EDIT: Adding this because I put it initially and forgot to here, but Software Renderer for any removes this glitch and the game looks fine, but the performance takes a massive hit compared to Hardware Renderer, hence why playing as such was unacceptable to me. However, the issue is present on Hardware only.

GS Dump provided.

***Description of the issue:***
Graphical bug with lighting effect. Immediately noticeable just by booting the game, but is present throughout anywhere that has a significant light source, such as the sun. Tutorial level is the same way.

***How to reproduce the issue:***
Simply boot the game with no pre-existing save file and it will be noticeable. Going to the tutorial is also that way, and it'll likely be present beyond this, though I haven't thoroughly tested.

***Last known version to work:***
None. It was present in every version I tried.

***PC specifications:***
EDIT: Want to be more specific, so I decided to add the exact machine I'm using. I use an ASUS G752JY gaming laptop, with an Intel Core i7-4720HQ 2.6GHz, Nvidia GTX 980M, with the latest update of Windows 10.

GS Dump and Screenshot provided:

[Scarface.zip](https://github.com/PCSX2/pcsx2/files/2258370/Scarface.zip)

**Comment by lightningterror** [comment]
Please format your issue properly using the template issue, thanks.

Same goes for https://github.com/PCSX2/pcsx2/issues/2539

**Comment by georgeli94** [comment]
Sorry, I have updated it.

**Comment by lightningterror** [comment]
Issue is present in both hw and sw renders ?

**Comment by georgeli94** [comment]
Ah, I could've sworn I mentioned that it wasn't present in Software Mode. Probably added it in the initial paragraph and forgot to mention it again here.

So the full context here is the graphical issue isn't there in Software Mode, but the game runs much, much slower in Software Mode than Hardware Mode for whatever reason (usually it'd be the opposite). Switching between Software and Hardware doesn't help either, unlike how switching between them helps add back the proper skyboxes in Black.

**Comment by lightningterror** [comment]
Ok so it's a GSdx Hw issue, SW is slow because it's quite taxing on the cpu.

Could you try the Hardware hacks if any of them fix the issue ?
You could also increase the blending to high or ultra.

Can you also provide a multiframe gs dump, I can hardly see anything from the green screen.

**Comment by georgeli94** [comment]
Here's a multiframe one. Had to double zip it because .7z compresses it far better, but Github only accepts .zip files. I tried every Hardware Hack I could see as well as the blending, and the issue is still present. Recent testing seems to make Auto Flush mitigate the bugs the most, with the major ones being gone, though some smaller ones still remain. Will provide a GS Dump of that once I get it as well.

[Scarface.zip](https://github.com/PCSX2/pcsx2/files/2258453/Scarface.zip)

**Comment by georgeli94** [comment]
Here's a dump of me using Auto Flush, with the weird small bugs going off in the background in the screenshot. It's hard to describe outside of it still being related to lighting somehow, as it's only lights or reflective water that seems to have this "smokey" look. I also have to mention that, as stated in the setting itself, this tanks performance. I recorded this with OpenGL, but Direct3D 9 and 11 also have these issues, with Direct3D 11 even having some shadow bugs (a solid shadow underneath guns).
[Scarface 2.zip](https://github.com/PCSX2/pcsx2/files/2258462/Scarface.2.zip)

One way I did see removing these bugs was through the use of Skipdraw 1, which removed those post-processing effects. However, doing so causes the pause menu and Tony's rage mode to turn green rather than their proper filters. If it isn't one thing, it's another. Skipdraw 2 causes everything to turn red. Skipdraw 3 causes everything to be black and blurry to the point that I can't see everything. There's just constant glitches no matter what I did.
[Scarface 3.zip](https://github.com/PCSX2/pcsx2/files/2258480/Scarface.3.zip)

**Comment by aaguilarc88** [comment]
having the same issue impossible to play this game

**Comment by tadanokojin** [comment]
This appears to be resolved in recent dev builds with half screen fix set to automatic.
If it's still an issue please let us know.

**Comment by tadanokojin** [comment]
Nevermind seems I jumped the gun and confused this with another issue.
Updating accordingly.

**Comment by tadanokojin** [comment]
Lighting bugs initially described are fixed by auto flush as mentioned. It may tank performance but there is only so much you can do with a synchronization problem.

HW + autoflush left
SW right
![000546](https://user-images.githubusercontent.com/26046960/120069631-f4b1a200-c054-11eb-958c-04378ba3d787.png)

> as it's only lights or reflective water that seems to have this "smokey" look.

LGTM.
![000547](https://user-images.githubusercontent.com/26046960/120069833-f0d24f80-c055-11eb-9071-4c993d5cd952.png)

I can't find any of the issues you describe that can be resolved by autoflush even when I went back to dev-2499.
I'm closing this out. If someone can find me a specific issue I can replicate I'll reopen it.
