### ISSUE TITLE
Justice League Heroes extreme slowdown in flying levels

### ISSUE THREAD

**Issue by georgeli94** [PCSX2/pcsx2#2539]
As with the other, apologies for the lack of proper formatting. It was, again, late last night, I was getting tired at trying to fix the issue myself and just quickly threw this in to let people notice it.

***PCSX2 version:***
1.5.0-dev-2464

***PCSX2 options:***
Speedhacks: Used all presets, even the most aggressive speedups. Didn't help. Safest runs even slower.

***Plugins used:***
Only really relevant one is the GSDX plugins, which I fiddled around with everything, from renderer to hacks. Again, nothing worked. Even software mode is still extremely slow. Being what I assume is a Snowblind Engine game (it was made by Snowblind Studios), I tried enabling Fast Texture Validation, which supposedly helps for these types of games, but with no success.

***Description of the issue:***
Flying or Space levels are extremely slow. On foot sections run at 60FPS just fine and play really great, but as soon as any level is mainly flight based, the framerate tanks. This is especially noticeable in the city rooftops level saving civilians from Brainiac's robots with Martian Manhunter and Zatanna, and the space levels fighting White Martians with Superman and Wonder Woman.

***How to reproduce the issue:***
Simply play either of the aforementioned levels. The game might start out at a stable framerate, but fly to certain areas at the framerate will tank.

***Last known version to work:***
Was present on every version of PCSX2 I tested, though I obviously didn't test every single one.

***PC specifications:***
EDIT: Want to be more specific, so I decided to add the exact machine I'm using. I use an ASUS G752JY gaming laptop, with an Intel Core i7-4720HQ 2.6GHz, Nvidia GTX 980M, with the latest update of Windows 10.

GS Dump Provided. I had to compress it twice to get it to upload on Github, as I wanted to provide multiple frames to show speed. Granted, since this isn't a grpahical bug, I'm not entirely sure how well it'll help.
[Justice League Heroes.zip](https://github.com/PCSX2/pcsx2/files/2258425/Justice.League.Heroes.zip)

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by Mrlinkwii** [comment]
is this still an issue on latest 1.7 ? :slightly_smiling_face:

**Comment by georgeli94** [comment]
I just tested with the latest nightly build (pcsx2-v1.7.2672-windows-64bit-AVX2) and it's still present, although much less of an issue now. Framedrops still happen, but not to the same extent. Seems like there's some progress being made.

**Comment by refractionpcsx2** [comment]
The game does an inordinate amount of read backs. You can dramatically increase the performance of the game by going in to the GS.ini and setting HWDisableReadbacks  to 1. However I don't know if this will break the game or not.

**Comment by georgeli94** [comment]
> The game does an inordinate amount of read backs. You can dramatically increase the performance of the game by going in to the GS.ini and setting HWDisableReadbacks to 1. However I don't know if this will break the game or not.

Finally was able to get home and test this, and wow, this setting did work. I was able to play a bit without any slowdown whatsoever.

What exactly does this setting do? Is there a problem with keeping it disabled for every other game? Thanks.

**Comment by stenzek** [comment]
It does what it says, ignores GS downloads. It'll break tons of games, **only** set it per-game.

**Comment by georgeli94** [comment]
> It does what it says, ignores GS downloads. It'll break tons of games, **only** set it per-game.

Is there a way to set it per game like settings in Dolphin or RPCS3?

**Comment by lightningterror** [comment]
> I just tested with the latest nightly build (pcsx2-v1.7.2672-windows-64bit-AVX2) and it's still present, although much less of an issue now. Framedrops still happen, but not to the same extent. Seems like there's some progress being made.

Might be even better on latest master, other than that, hw readbacks can be disabled per config, will have to do for now as that's how the game works.
