### ISSUE TITLE
Menu item descriptions are obscured

### ISSUE THREAD

**Issue by egartley** [PCSX2/pcsx2#2548]
***PCSX2 version:***
``Stable build v1.4.0``

***Description of the issue:***
``The menu items, specifically under "System", have their descriptions obscured by the dropdown, as seen in the screenshot below. The window is not resizable, therefore the full description cannot be seen. In the screenshot, "Shutdown" is being hovered over.``

![2018-08-09](https://user-images.githubusercontent.com/12011240/43928146-d93f7714-9bfd-11e8-8d7a-4acd7f2514fd.png)

***How to reproduce the issue:***
``Open PCSX2, click on "System", and hover over any option that has its description show up at the bottom of the window``

**Comment by MrCK1** [comment]
I mean there's nothing we can really do about it. As long as the console is open, the descriptions are still visible.

**Comment by lightningterror** [comment]
Ah yes this is an issue but nothing major. And one also clips in the ISO text.

A solution would be to disable showing the description in the main window and only let it be active once the console is up.

**Comment by ssakash** [comment]
@refractionpcsx2 @turtleli - Do you guys agree on if these helper texts are pointless?

**Comment by refractionpcsx2** [comment]
They should be mouse over popups really

**Comment by lightningterror** [comment]
> They should be mouse over popups really

It doesn't make sense for a drop down list.

**Comment by refractionpcsx2** [comment]
Having it show in the console makes even less sense.

**Comment by turtleli** [comment]
Some are pointless ("Show about dialog"). Not sure they all are.

**Comment by lightningterror** [comment]
Like I said there's also this which overlaps with the ISO part, the sentence can be reduced but that also leaves other languages which some have longer words which results in longer sentences, another solution would be to add a delayed horizontal scroll.

![image](https://user-images.githubusercontent.com/18107717/44426107-128d7680-a58e-11e8-88b0-d27a71463556.png)

**Comment by turtleli** [comment]
> another solution would be to add a delayed horizontal scroll.

Unless I'm missing something then there's no built-in wx method for that, so I don't think that's really a solution unless you want to implement it yourself. Also, the help text would still be covered up by the menus.

Otherwise I can't say I care much about the help texts. I suppose the main use case for the help texts is to help users who aren't familiar with things and haven't read the documentation (I note that our documentation isn't exactly up to date). Is that a good enough reason to keep them? On the other hand, the strings are translated. Are the strings useful enough that they're worth the additional workload that it gives translators?

**Comment by lightningterror** [comment]
> unless you want to implement it yourself

I'll pass :smile: 

> On the other hand, the strings are translated. Are the strings useful enough that they're worth the additional workload that it gives translators?

Well some are translated not all of them, this could make things easier for translators to translate less strings.

The menu lists are pretty much self explanatory what they do.

Anyway I'm up for purging them.
