### ISSUE TITLE
[SLES_505.56] New York Race: Rendering issues and Intro regression

### ISSUE THREAD

**Issue by smx-smx** [PCSX2/pcsx2#2553]
***PCSX2 version:***
PCSX2 v1.5.0-dev-2484-gd258ef627

- **Notes**:

Intros are not scaled correctly (this is a regression)

3D environments are not refreshed/updated properly, and they get blank as time progresses. Pausing and unpausing emulation seems to cause a refresh.

![intro issue](https://user-images.githubusercontent.com/1978844/44065341-5f6467ae-9f6a-11e8-92f2-26f3dfa7eeb0.png)
![blank](https://user-images.githubusercontent.com/1978844/44065360-76677676-9f6a-11e8-9b45-af67e7e74378.png)
After pause/unpause, some elements of the scene don't get updated as the camera shakes

![after pause/unpause](https://user-images.githubusercontent.com/1978844/44065520-6e434b40-9f6b-11e8-9ac1-b8a966895dad.png)

[gsdx_20180814023945.zip](https://github.com/PCSX2/pcsx2/files/2285129/gsdx_20180814023945.zip)

***PCSX2 options:***
Tried hacks, different renderers, etc. without luck (including setting presets)

***How to reproduce the issue:***
Just boot the game, the issue is visible right in the main menu (because it loads a map for the background).

***Last known version to work:***
Not sure when the intro regression started to appear, but what i can say for sure is that it was working on June 2015 (old bug report that i didn't submit back then - the refresh problem was still there)

***PC specifications:***
i7 7700k, Intel HD 630 (iGPU, no dedicated GPU)

**Comment by lightningterror** [comment]
Duplicate #2458

**Comment by smx-smx** [comment]
@MrCK1 I actually had an older GSdx plugin in the folder and i didn't notice it was being used rather than the newer one, sorry.
Confirming both the intros and depth issues are fixed with the newer plugin, on the OpenGL backend

Thanks :)
