### ISSUE TITLE
[Debugger] Editing read-only memory pages causes access violation

### ISSUE THREAD

**Issue by Souzooka** [PCSX2/pcsx2#2555]
***PCSX2 version:***
PCSX2 v1.5.0-dev-2457

- **Notes**:
The access violation occurs at line 237 of vtlb.cpp, which causes an instant hard crash of PCSX2.

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***
Changing the value of an address at a memory page marked as read-only using the debug window causes an access violation.

***How to reproduce the issue:***
Open the debug window, then attempt to edit memory in a read-only memory page (e.g. in a code section). Editing address 0x100000 should cause this crash for any game.

***Last known version to work:***
N/A

***PC specifications:***
N/A

**Comment by ramapcsx2** [comment]
What do you expect to happen instead?

**Comment by refractionpcsx2** [comment]
The only sensible solution I can think of is make it not editable in the debugger

**Comment by gregory38** [comment]
There is no such thing as read only page for RAM. However lower part of memory isn't mapped in the virtual user space because it is reserved for the kernel.

**Comment by F0bes** [comment]
As of today, writing to code memory and unmapped memory doesn't seem to cause PCSX2 to crash.
I do know that if you end up writing to MMIO FIFOs it may cause serious issues. This is a side effect of the debugger accessing memory through the vtlb without any way to prevent the vtlb of deferring the read/write to something like the IPU or VIF. I think this would be a user issue anyways, if you don't know where you are writing to, don't write there.
