### ISSUE TITLE
[Idea] Add option to print SYSCALL_print (117) strings to console.

### ISSUE THREAD

**Issue by Souzooka** [PCSX2/pcsx2#2558]
This is something I did myself, though nothing along the lines of it being fully integrated into the UI. The concept is simple, just catch SYSCALL 117 and, if sysout messages are enabled for the console, print them to the console. This gives a helpful option for those who want to capture any sort of stubbed logging in games, for game exploration/hacking and the like. It's something that I could likely myself, I just wanted to gauge an opinion on if something like this would be wanted.

As an example:
Using eeConLog and a bit of rewriting of game code, I can print the debug stream for this game:
![img](https://i.imgur.com/p7XKxdf.png)

**Comment by ramapcsx2** [comment]
Oh yeah, this is useful!
It doesn't have to be a UI option. Simply tie it to dev / debug builds.

**Comment by Souzooka** [comment]
Yeah, I can take a stab at it. Probably want to add it to UI anyways since if games don't have a stubbed printf it can be very verbose and would spam logs anyways, the only other thing is that strings have to be formatted by the game itself, but I'll write more about that limitation and potential solutions when I get back to a computer.

**Comment by Souzooka** [comment]
Alright, to elaborate, basically what I was going to touch on before is that this is probably a feature best used for homebrew development, as this feature should hypothetically capture the resulting strings from `(v)printf` calls and print them to the console, making it a great feature for debugging homebrew on PCSX2 (though I haven't explicitly tested that, but I don't see why it wouldn't work).

That being said though, I did want to add it as a UI element for two reasons:
* I did want to be able to use this feature in future release builds,
* it would be useful to shut up printf calls even on debug if it's not stubbed in a retail game, as it can potentially be very verbose and spammy.

And to touch on the string formatting thing, to recover printf calls fully in a retail game would require the user to rewrite printf to jump to another function, have that function set up all potential arguments correctly, then call sprintf with an allocated buffer and then print the result (and is actually what is being done in the example picture). It would be nice if PCSX2 could format the string with the provided arguments itself, but I don't believe there is a very clean way to do this and even if such a feature was implemented, it would assume that all print syscalls went through a formatting function like printf and thus might generate inaccurate results otherwise. Ultimately, I don't think something like that is in the scope of this feature itself though I might open up an issue about that later on down the line.

With all that being said for consideration, the logic for actually interpreting that SYSCALL and printing a string on PCSX2's side exists, leaving only UI/logging changes. I'll take a look at making a unique logging fn for sysout and just adding that option on the UI, probably grouped with PxThread/SysVM Control Events. Unless those prove to be super-confusing a pull-request should be coming soonish.

**Comment by ramapcsx2** [comment]
Ah okay, if it has the potential to spam with pretty much useless information, then it should be optional.

**Comment by ssakash** [comment]
There's already logging done for all the syscalls in the dev/debug builds, maybe you could add this along with that. I don't see a reason on why this should be available at release builds.

**Comment by Souzooka** [comment]
Well, those logs are for the effects of those syscalls and are helpful for debugging PCSX2 specifically. However, `printf` calls made by the game itself (leading to this syscall being invoked) are usually made for debugging the game, not PCSX2 in any capacity (at least not directly). Therefore, it doesn't make much sense to me to tie it to debug builds of *PCSX2* especially when it would be a disabled-by-default optional source.

**Comment by ramapcsx2** [comment]
The coupling of debug capabilities to either PCSX2 or the software under test is loose. It would be fine either way.

If you think an extra option is better and doable, then this is fine.
I'd actually prefer if it worked in full release builds, by the way :)

**Comment by Souzooka** [comment]
Added in as a basic implementation in https://github.com/PCSX2/pcsx2/pull/2563
