### ISSUE TITLE
please make a new release 

### ISSUE THREAD

**Issue by sergiomb2** [PCSX2/pcsx2#2572]
***PCSX2 version:***

v1.5.0-dev have 2534 commits to master since this tag .

As I request I some projects [1], we need tags or releases to pack the code , shouldn't be the packager that follow the code ... 

Thanks 

[1]
https://github.com/niltonvolpato/python-progressbar/issues/56
https://github.com/dottedmag/x2x/issues/26

**Comment by MrCK1** [comment]
This is an issue tracker, not a place to beg for s new release. When we're ready, we will make a new one.

**Comment by sergiomb2** [comment]
well how I do this request ? 

last year https://github.com/PCSX2/pcsx2/issues/2069 
and now @orbea  ( https://github.com/PCSX2/pcsx2/issues/2508#issuecomment-414532493 ) ask me tp update the Fedora package , can someone tag one commit ? please 

Thanks

**Comment by willkuer** [comment]
Why do you not just pack 1.4 and call it a day? If there is not enough material for a release there is just jot enough material. If people want to try nightlies they can compile themselves...

**Comment by orbea** [comment]
The nightlies actually builds here, the last stable doesn't...

**Comment by lightningterror** [comment]
@orbea Last stable might be useless but there are some situations where it can come in handy, you can see if any of these commits fix the issue, it might be a good idea to at least have the compile working for legacy purposes.

https://github.com/PCSX2/pcsx2/search?q=fedora&type=Commits
or
https://github.com/PCSX2/pcsx2/search?q=cmake&unscoped_q=cmake&type=Commits

Keep in mind 2016+

**Comment by sergiomb2** [comment]
@willkuer  we pack 1.4 since 2016 [1] 2579 commits to master since this tag and no new material ?!? 

OK , we will stay on 1.4 until a new tag appear and upstream (you) show willingness to test new versions

Thanks.

[1]
http://koji.rpmfusion.org/koji/packageinfo?packageID=376
