### ISSUE TITLE
[Feature Request] Autosave Memcards

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#2573]
Request an autosave feature be added to update memcards on system disk when ingame saves are made, or at least an autosave interval option to write memcards to disk after specified time.

Currently, memcards are only updated when emulator is closed, which can prove to be problematic when playing a game for an extended timeframe due to possibility of emu or system crash causing data loss, or due to power outage.

Some example code may be found on [Retroarch](https://github.com/libretro/RetroArch) repository if guidance is needed, since there is a functioning implementation there.

**Comment by lightningterror** [comment]
> Currently, memcards are only updated when emulator is closed, which can prove to be problematic when playing a game for an extended timeframe due to possibility of emu or system crash causing data loss, or due to power outage.

@RedPanda4552 tested and verified that memory cards are updated when a new save is made while the emu is running so I'm closing this since it's invalid.

**Comment by RedPanda4552** [comment]
I would make sure there is not some other issue on your system causing the problem.

As an experiment I cleared the first level of Ratchet and Clank: Going Commando and saved to a memcard. I then copied it via File Explorer, swapped the memcard in slot 1 to it, and then tried to load again. If disk writes were not happening until emu shutdown, then this would have reverted me back to a blank save slot. But, my save was there as expected.

**Comment by ichee** [comment]
You're right. I tried copying the memcard after saving in game while emu was still running and save was still updated. For some reason, the last modified date on memcard file is not updated while emu is running. Even the copied memcard has the old last modified date before this test but save is still intact. Is there a possibility that NTFS compression that PCSX2 uses is preventing an update to the last modified time of the memcard until emu is closed? I ask because other emus that autosave internal saves the last modified time is updated immediately upon saving. Otherwise, saves are immediately being written at least.

**Comment by willkuer** [comment]
To my knowledge there was a lengthy discussion about this since internal flushing onto the memory is async from saving. So the flush to disk has to await this flushing which is not detectable. Hence the emulated memory card was flushed to disk after a certain time span (I think around one minute in emulation time or a certain amount of frames later.

Maybe @AdmiralCurtiss can just have a small peek and tell us about flushing to disk?
I think he discussed this together with @ramapcsx2 ...
