### ISSUE TITLE
James Bond 007 Nightfire (NTSC-U) [SLUS-20579] Glitchy textures in game

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#258]
As soon as a new game is started some of the textures look like static n flash a lot.

pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

I have ran in both Hardware and software modes and have tried  all HW hacks but there is no fix.

Game has had other major problems in past revisions

**Comment by gregory38** [comment]
Could you test the SW renderer on latest git ? A couple of bug were fixed so maybe yours.

**Comment by refractionpcsx2** [comment]
Yeah i suspect a similar problem to Lupin 3rd here, I can test this later tonight as I have the game.

**Comment by refractionpcsx2** [comment]
OK this is fixed in software mode :) HW is obviously still broken currently.

There is also some near plane clipping issues on the driving part at the start, seems to be getting rid of the meshes/textures before they have gone off-screen, but that could be a VU issue I guess,.

**Comment by refractionpcsx2** [comment]
As you are updating this @gregory38, I just want to note it is at least fixed in OpenGL, I haven't checked DirectX recently

**Comment by AmbientMalice** [comment]
Nightfire needs VU clamping set to Extra to fix the clipping in vehicle sections, based on my testing. The reason Nightfire needs careful examination is that the game uses two different engines. The vehicle sections are running on a modified Need for Speed engine, and the FPS sections are using a custom Eurocom engine.

The FPS sections suffer from severe texture corruption in HW mode regardless of settings. They seem to be working fine in software mode, however.

**Comment by refractionpcsx2** [comment]
I thought this was fixed in OpenGL (at least) a long while ago? I remember seeing the snow/ground looking perfect which was the major bug it had.

**Comment by AmbientMalice** [comment]
Here's how the first mission looks in HW mode:
![nf_sw](https://cloud.githubusercontent.com/assets/10704701/17456473/042590b8-5c1c-11e6-9f6a-4074cd17880c.png)

Here's how it looks in SW mode:
![nf_hw](https://cloud.githubusercontent.com/assets/10704701/17456481/2ecbc21a-5c1c-11e6-9d0b-c269ba6891a7.png)

There's a chance it was fixed somewhere along the line, but I doubt it. I notice stuff like the thermal goggles are completely broken. Basically, every single texture in the game swaps with other textures as you walk around.

**Comment by refractionpcsx2** [comment]
Strange, it must have gotten broken again, I could have sworn it was fixed at some point.

**Comment by FlatOutPS2** [comment]
@AmbientMalice: Can you make a GS Dump of that scene?

**Comment by AmbientMalice** [comment]
GS dump:
![nightfire_hw](https://cloud.githubusercontent.com/assets/10704701/17515062/8fe73d18-5e79-11e6-9d9f-1d95a0e9dfff.png)
http://s000.tinyupload.com/?file_id=66495253267174599933

**Comment by divinity76** [comment]
for those who want to play Nightfire with awesome graphics, until PCSX2 fix the hardware renderer issues, know that Nightfire can be played on the Dolphin emulator with the PS3 controller.
on my gtx 1070-mobile and i7-6820HK overclocked to 4GHz, a high-end gaming laptop,  i can play in FullHD resolution, 8x antialiasing, 16x anisotropic filtering, and it looks bloddy beautiful. Dolphin can even scale it up to 4K, but my 1070 isn't strong enough for that

**Comment by MrCK1** [comment]
@AmbientMalice Could you retest/upload a new GS Dump - the URL is dead?. I can't access my main PC for another week. Thanks.

**Comment by MrCK1** [comment]
I did a retest of this and DX9 HW had less corruption in 0.9.6 (r890) - the snow was fine and only the boxes on the castle were present. After that point (the next plugin I have is r1600) DX9 HW was broken as the other renderers are on master currently.

**Comment by MrCK1** [comment]
I did a retest of this and DX9 HW had less corruption in 0.9.6 (r890) - the snow was fine and only the boxes on the castle were present. After that point (the next plugin I have is r1600) DX9 HW was broken as the other renderers are on master currently.

![image](https://user-images.githubusercontent.com/16314399/48995520-3379e080-f116-11e8-9e2d-b3adac713e9a.png)

**Comment by AlessandroVetere** [comment]
This might be related to the fix of palette CLUT matching in #2713, which development is still ongoing.

**Comment by MrCK1** [comment]
Forgot to post this a while back but I believe this is the bad commit: https://github.com/PCSX2/pcsx2/commit/95ff8e3a98e2895a96ecb55e8eb6d654c481a7a8
