### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fancymelonub** [PCSX2/pcsx2#2581]
Just asking, but does PCSX2 currently support the PS2 Linux stuff. I really want to try those but I don't have a PS2 nor the discs and stuff the PS2 Linux thing has.

**Comment by PSI-Rockin** [comment]
From what I know, PS2 Linux doesn't boot at all? I haven't tested it myself.

Regardless, PS2 Linux requires full MMU emulation to work, which PCSX2 does not have and probably will not have for a long time.

**Comment by fancymelonub** [comment]
Ok, thank you for the answer.
