### ISSUE TITLE
EE skips loops under certain conditions on real hardware, might be needed for ONI.

### ISSUE THREAD

**Issue by PSI-Rockin** [PCSX2/pcsx2#2582]
A bug on the MIPS core of the EE causes certain branches to not be evaluated. All of the following conditions must be met:

```
a loop consists of less than equal to six instructions(includes branch delay slot).

a loop contains only one conditional branch instruction at the end of the loop.

a loop does not contain any other branch or jump instructions.

a branch delay slot of the loop is not nop. ( EE#2.9 or later )
```

See https://github.com/ps2dev/ps2toolchain/blob/master/patches/binutils-2.14-PS2.patch#L5319

This will never happen in compiled code, as Sony's compiler will pad loops meeting all conditions with nops. However, a game that uses assembly code might run into this issue.

I don't know if anything on the PS2 library is affected by this, but I'm almost certain PCSX2 does not emulate this glitch. It might be worth investigating.

**Comment by refractionpcsx2** [comment]
This was reverted on dobiestation as it caused issues with several games.  After tests were done on a PS2 it was found difficult (if not impossible) to reproduce this bug/quirk on the actual console.
