### ISSUE TITLE
[RFC] Touch UI

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#2587]
@Xirexel I really hope you aren't thinking we are all Wx lovers here /s

Your project looks *dope*. Though.. Since ~~cross-plaform~~ linux is kind of important, is there any possibility you could look into one of the [WPF-like](https://blog.lextudio.com/the-story-about-net-cross-platform-ui-frameworks-dd4a9433d0ea) frameworks out there that aren't windows specific?
https://github.com/AvaloniaUI/Avalonia
https://github.com/picoe/Eto
(or, I mean, people on reddit have mentioned Qt, but I guess that's famous enough if you wanted you'd have already used it)

Thanks.

**Comment by Xirexel** [comment]
I think it is can be possible to port it on WPF-like framework, but it can take too much time. 
In my view, it could be better to spend this time on writing "Cloud" version PCSX2 - "with blackjack and hookers".

**Comment by mirh** [comment]
Well, guess what.. WPF and .NET are going open. 
And possibly even cross-platform (next year with the release of version 5?). 

Did you have a look at that new stuff?

**Comment by refractionpcsx2** [comment]
Qt has big picture, which I feel covers it.
