### ISSUE TITLE
"Super Robot Wars - Alpha 3" when fighting,  some character animation flicker

### ISSUE THREAD

**Issue by kokutoukiritsugu** [PCSX2/pcsx2#2588]
``pcsx2-v1.5.0-dev-2550-gd8e6ba427-windows-x86``
``PCSX2 1.5.0-20180905213838 - compiled on Sep  6 2018``

``Windows 10  17134 64-bit 16339 MB i7-6700K @ 4.5Ghz``

``opengl(HW),any other things set to default``

HW mode, some character animation flicker
tried HW Hacks, no any improvement.
SW mode, works fine. no issues.

![gsdx_20180911194421](https://user-images.githubusercontent.com/5471433/45358208-455de400-b5fb-11e8-8cfd-37aaf876dc06.png)

***How to reproduce the issue:***
load the game, continue with the memcard save.
press many O, end the round, fight start.
will show the animation.

[MCD001.zip](https://github.com/PCSX2/pcsx2/files/2370814/MCD001.zip)
[gsdx_dumps.zip](https://github.com/PCSX2/pcsx2/files/2370816/snaps.zip)

**Comment by kokutoukiritsugu** [comment]
gsdx dumps
animation start to end
[gsdx_dumps2.zip](https://github.com/PCSX2/pcsx2/files/2370869/gsdx_dumps2.zip)

**Comment by refractionpcsx2** [comment]
Works fine on master with every renderer.
