### ISSUE TITLE
[Request] adding this function.

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2591]
Hello.

Lately, I got a china user's mod plugin(GSdx).

This plugin has unique some feature.

The option name is 'HDMode' which makes clearer resolution quality definitely.

I checked as playing tales of symphoina.

comparison screenshot

normal plugin shot

![gsdx_20180913133606](https://user-images.githubusercontent.com/35862336/45468645-38351800-b715-11e8-8278-0cd906d9c69a.png)

mod plugin shot

![gsdx_20180913134046](https://user-images.githubusercontent.com/35862336/45468658-471bca80-b715-11e8-807c-4c494a16436a.png)

It remove Tales of symphonia's blur - maybe bad postprocess .
But game's fps also is knocked out (60fps => 5fps).

It is worth implementing to make clearer resolution.

Mod plugin site
http://blog.xuite.net/xui091113/twblog/121829551-%E7%AB%99%E9%95%B7%E4%BF%AE%E6%94%B9%E7%9A%84Gsdx-Cutie%E6%8F%92%E4%BB%B6%28%E5%8E%9FGsdx-ShadeBoost%E6%8F%92%E4%BB%B6%29+2016%2F05%2F22%E6%9B%B4%E6%96%B0

Mod plugin Source Code
https://github.com/s90110019/Gsdx-cutie

Another screenshot
-God hand-
original plugin
http://photo.xuite.net/xui091113/9057123/123.jpg
mod plugin
http://photo.xuite.net/xui091113/9057123/124.jpg

-Ookami-
original plugin
http://photo.xuite.net/xui091113/9057123/117.jpg
mod plugin
http://photo.xuite.net/xui091113/9057123/118.jpg

Thanks.

P.S
The option name has changed.
FBP => HDfix  => HDMode

And tales of symphonia setting screenshot
![cutie-setting](https://user-images.githubusercontent.com/35862336/45469393-daa2ca80-b718-11e8-9afe-a6331294c940.PNG)

**Comment by lightningterror** [comment]
This is a massive hack honestly. Maybe it can be ported partially without those crc hack inclusions and instead of a drop down menu HDMode would work with a spin button from 1 to 56. The tooltip would show which game what needs instead of the crc stuff.

**Comment by vsub** [comment]
Isn't this something similar to
https://forums.pcsx2.net/Thread-GSdx?pid=590969#pid590969
or
https://forums.pcsx2.net/Thread-No-interlacing-codes

**Comment by lightningterror** [comment]
Perhaps maybe since both get rid of the blur. Anyway the source code on github is outdated so I don't know the current state. On the surface it might look good but it's a massive hack that relies on crc lookup ..etc and we don't need to clutter the gsdx code with that. I also noticed some custom skipdraw hacks as well.

The no interlacing codes are a much better and simpler solution. Anyway closing this.

**Comment by avih** [comment]
> it's a massive hack that relies on crc lookup ..etc and we don't need to clutter the gsdx code with that

That's a bit hypocritical to say. GSdx already relies on a massive database of CRCs and derived custom behavior, and IIRC this repo merely extends it to more CRCs and more custom behaviors.

Assuming this specific feature is useful, and assuming it can be reasonably isolated or generalized, and assuming someone wants to and can actually port it, I don't think it'd be a bad thing to have.

But the reason you gave against it is both quite meh and also not necessarily relevant (though I could be wrong on the latter).

**Comment by lightningterror** [comment]
> Assuming this specific feature is useful, and assuming it can be reasonably isolated or generalized, and assuming someone wants to and can actually port it, I don't think it'd be a bad thing to have.

If that's the case then I don't mind. Currently the code relies on FBP, TBP and other lookups.
https://github.com/s90110019/Gsdx-cutie/blob/385610b1c0c6f1bd227c9f1b98dfc3ab94ba1b70/GSRendererHW.cpp#L584

**Comment by tadanokojin** [comment]
Someone patched this game to essentially do the same thing and I think that's a much better solution than this absolutely disgusting mess of code by cutie

https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=605007#pid605007

Closing.
