### ISSUE TITLE
gamepad not recognized on linux onepad "keyboard/mouse only" but jstest Does

### ISSUE THREAD

**Issue by cnaveiro** [PCSX2/pcsx2#2604]
I dont know if the problem is the plugin or something else. roblem into the images below
thanks in advance.

***PCSX2 version:***
stable build v1.4.0 
no reported  bugs

![captura de pantalla de 2018-09-23 15-15-07](https://user-images.githubusercontent.com/32653507/45931359-7c10f400-bf43-11e8-8dbf-b36ac6afd1ee.png)
***PCSX2 options:***
Default options
![captura de pantalla de 2018-09-23 15-00-25](https://user-images.githubusercontent.com/32653507/45931307-dbbacf80-bf42-11e8-933b-dcda33633b08.png)
![captura de pantalla de 2018-09-23 15-04-36](https://user-images.githubusercontent.com/32653507/45931308-dc536600-bf42-11e8-9d3c-ba1880fdfcd6.png)

Info system

System:    Host: cnav-HP-240-G5-Notebook-PC Kernel: 4.15.0-33-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Cinnamon 3.8.9 (Gtk 3.22.30-1ubuntu1) dm: lightdm Distro: Linux Mint 19 Tara
Machine:   Device: laptop System: HP product: HP 240 G5 Notebook PC v: Type1ProductConfigId serial: N/A
           Mobo: HP model: 81DB v: KBC Version 68.13 serial: N/A UEFI: Insyde v: F.15 date: 07/21/2016
           Chassis: type: 10 serial: N/A
Battery    BAT0: charge: 28.6 Wh 99.7% condition: 28.7/28.7 Wh (100%) volts: 12.6/10.9
           model: Hewlett-Packard Primary serial: <filter>status: Charging
CPU:       Dual core Intel Core i5-6200U (-MT-MCP-) arch: Skylake rev.3 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9600
           clock speeds: min/max: 400/2800 MHz 1: 941 MHz 2: 998 MHz 3: 910 MHz 4: 1087 MHz
Graphics:  Card: Intel HD Graphics 520 bus-ID: 00:02.0 chip-ID: 8086:1916
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           version: 4.5 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes
Audio:     Card Intel Sunrise Point-LP HD Audio driver: snd_hda_intel bus-ID: 00:1f.3 chip-ID: 8086:9d70
           Sound: Advanced Linux Sound Architecture v: k4.15.0-33-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 4000 bus-ID: 01:00.0 chip-ID: 10ec:8168
           IF: enp1s0 state: down mac: <filter>
           Card-2: Realtek RTL8723BE PCIe Wireless Network Adapter
           driver: rtl8723be port: 3000 bus-ID: 02:00.0 chip-ID: 10ec:b723
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 1000.2GB (10.9% used)
           ID-1: /dev/sda model: WDC_WD10JPVX size: 1000.2GB serial: <filter>
Partition: ID-1: / size: 916G used: 102G (12%) fs: ext4 dev: /dev/sda2
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 45.5C mobo: 0.0C
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/git-core-ppa-bionic.list
           deb http: //ppa.launchpad.net/git-core/ppa/ubuntu bionic main
           deb-src http: //ppa.launchpad.net/git-core/ppa/ubuntu bionic main
           Active apt sources in file: /etc/apt/sources.list.d/google-chrome.list
           deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt sources in file: /etc/apt/sources.list.d/gregory-hainaut-pcsx2_official_ppa-bionic.list
           deb http: //ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic main
           deb-src http: //ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http: //mirrors.evowise.com/linuxmint/packages tara main upstream import backport
           deb http: //mirrors.cloud.linets.cl/ubuntu bionic main restricted universe multiverse
           deb http: //mirrors.cloud.linets.cl/ubuntu bionic-updates main restricted universe multiverse
           deb http: //mirrors.cloud.linets.cl/ubuntu bionic-backports main restricted universe multiverse
           deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           deb http: //archive.canonical.com/ubuntu/ bionic partner
           Active apt sources in file: /etc/apt/sources.list.d/pcsx2-team-pcsx2-daily-bionic.list
           deb http: //ppa.launchpad.net/pcsx2-team/pcsx2-daily/ubuntu bionic main
           deb-src http: //ppa.launchpad.net/pcsx2-team/pcsx2-daily/ubuntu bionic main
Info:      Processes: 257 Uptime: 3:28 Memory: 3086.7/7868.8MB
           Init: systemd v: 237 runlevel: 5 Gcc sys: 7.3.0 Client: Unknown python3.6 client inxi: 2.3.56

**Comment by arcum42** [comment]
Considering that currently there are *two* Onepad plugins in current builds, and the odds are one or the other will work, seems likely.

**Comment by arcum42** [comment]
I'm just going to go ahead and close this. If it turns out to be happening on the latest build, we can always reopen it.
