### ISSUE TITLE
Radiata Stories character shadow not displaying

### ISSUE THREAD

**Issue by Dweeblord** [PCSX2/pcsx2#2609]
***PCSX2 version:***
v1.5.0-dev-2571

***Plugins used:***
The default plugins and default settings.

***Description of the issue:***
I've been emulating this game for like 7 years and regardless of settings I don't think the character's shadow ever rendered in hardware mode. I am pretty sure it's the last remaining issue in this emulating this gem.

![pcsx2 2018-09-29 08-10-04-60](https://user-images.githubusercontent.com/43702664/46247111-cc64d780-c3c3-11e8-8f04-ac7885a7949d.jpg)

***PC specifications:***
CPU: 8600k GPU: GTX 1070 OS: Windows 10 64 Bit

**Comment by lightningterror** [comment]
Please update your issue properly following the template.

On a side note are you sure OpenGL with Blending enabled doesn't work ?

**Comment by Dweeblord** [comment]
Sorry about that, I didn't think it was necessary since I really did try everything except the debug/minimum CRC since I knew that would destroy my FPS. It did indeed appear there but I don't think there's a computer on earth that could run the game at full speed with that enabled.

**Comment by Dweeblord** [comment]
This wasn't a duplicate issue orz

**Comment by lightningterror** [comment]
The issue is the slowdowns, which is why shadows can't be enabled atm.

#984 pretty much explains the issue.
