### ISSUE TITLE
Age of Empires 2 (pal-Unk) [SLES-50282]

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#261]
As soon as the game starts it asks you to pick a language but the textures are discolored and you cannot move or pick a language which makes this game unplayable in both hardware and software mode.

I believe there was a revision before that said they had fixed this game but i am sorry i can not remember which one it is.

My pcsx2 version is:
pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

**Comment by bositman** [comment]
Worked fine in my test, some transition effect not rendering correctly in both HW and SW renderers but pretty minor.
