### ISSUE TITLE
Long input delay where pcsx2 is not responding to input right after transitions happen (battle, menus etc.) in Shadow Hearts 2 (prob not SH2 specific)

### ISSUE THREAD

**Issue by thatsage** [PCSX2/pcsx2#2610]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2552-g9cb35a897-windows-x86 **and onwards** (latest as well, as of today **e90c87a**)

***PCSX2 options:***
"Safe" Preset (tested "Safest" as well).

***Plugins used:***
Default selected plugins out the gate. OpenGL Software mode.

***Description of the issue:***
This is very difficult to explain so please bear with me. Game is **Shadow Hearts 2**, I don't know if it happens in other games. After a few battles (about 4-5) the next battle introduces a problem where the game (it seems PCSX2 itself beacuse hotkeys like turbo mode don't work either during the duration of the delay) **isn't responding to inputs** but sort of queues them up slowly, and after 2-3 seconds it goes back to normal for the rest of the battle. This snowballs and becomes worse and after each new battle, the delay is longer and the following cycle repeats itself: after a battle starts, delay. After it ends and at the start of exploration, delay. Opening a menu for the first time after exploration starts, delay. Like I said inptus sort of queue up, so if you keep pressing stuff they will sort of run their course after the delay passes and then everything is normal until the next battle re-triggers the cycle and makes it longer a bit.

***How to reproduce the issue:***
Battle a few times and keep running away to get them over quickly. Eventually you will notice at the start of a battle that PCX2 isn't responding to inputs. From there on keep doing it and shortly you will see that inputs are dealyed and queued up when a battle starts, after it ends and when you open a menu and the delays will become longer.

***Last known version to work:***
pcsx2-v1.5.0-dev-2551-g6e3f41f16-windows-x86 could not reproduce issue. Version right after this one has it.

***PC specifications:***
Windows 10 latest 64bit 
8GB RAM
Nvidia GTX 970 
i5-4690k

**Comment by lightningterror** [comment]
Did you check the latest build ? There were some changes made for the Saveslots after 2552.

**Comment by lightningterror** [comment]
I'll leave this info here as it seems useful. From @RedPanda4552 and @KrossX 

> The savestate slot one caused a hangup in the UI thread for some people, remember

> I don't know which thread polls controllers at a system level but if it is UI, then that may be it.
> Quick hot fix is to empty the savestates folder and see if it persists

> It's getting hung up trying to read the savestates
> In the case of the user that reported it though, it wasn't input lag, it was the entire UI thread maxing and being unresponsive.

**Comment by feikname** [comment]
Similar (same?) problem happens with the Metal Slug Anthology.

**Comment by RedPanda4552** [comment]
**_If my assertion that Lightning quoted above is correct_**, this is not a game specific issue, and will occur no matter what game you play, if there are any savestates in your savestates folder.

**Comment by arcum42** [comment]
See if 2572 helps. I removed a call to update the ui that I don't believe was needed that slipped in.

**Comment by thatsage** [comment]
> See if 2572 helps. I removed a call to update the ui that I don't believe was needed that slipped in.

Thank you, it's still happening.

**Comment by arcum42** [comment]
All right, I've ifdeffed out the new code so the saveslot code should act the way it used to before the changes. Once a new build comes through, let me know if it's still happening at that point.

**Comment by thatsage** [comment]
> Once a new build comes through, let me know if it's still happening at that point.

All good now on 2573, thank you :)

It's a bit ironic the reason I decided to update pcsx2 to begin with was hoping overall input latency might have been reduced heh.

**Comment by arcum42** [comment]
Well, it's the nature of updating from the latest git that things occasionally break, I'm afraid.

Though given I've got no way of reproducing the issue myself, I doubt the saveslots ui improvements are coming back any time soon.

**Comment by lightningterror** [comment]
Can you retest latest build, the saveslot feature has been re enabled again with some changes.
