### ISSUE TITLE
Extremely specific performance issue 

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2611]
***PCSX2 version:***
v1.5.0-dev-2572-g042311a82

***PCSX2 options:***
MTVU speedhack

***Plugins used:***
GSdx OGL HW

***Description of the issue:***
If you happen to have MTVU turned on while using the OGL HW renderer on one specific spot in Metal Gear Solid 3 Subsistence (although I cannot guarantee that it cannot be triggered on other games/areas) and then while playing that game you tab out and do certain things like opening certain programs, disabling desktop composition, loading or reloading certain web pages (ones that are heavy or with loads of images tend to do it) then the GS thread usage indicator will suddenly rise quickly and stay higher despite there being no reason it should and the framerate drops significantly 
While I've tried to find specific things that trigger it on purpose it can and most likely often will trigger on it's own, the number of programs running in he background seems to have some impact on that (the more you have the more likely it is to happen), enabling Vsync seems to make it happen randomly less often but it will still trigger 
Once that behavior has been triggered only a complete restart of PCSX2 will change it back, switching to another game doesn't fix it, using the shutdown function then relaunching the game doesn't fix it, switching MTVU on and off doesn't fix it, switching renderer doesn't fix it.
Additionally once triggered it will negatively affect performance in everything you do after that including other games and again regardless of the renderer (although I'm not fully positive regarding it affecting the SW renderers)
This bug seems extremely specific and I haven't been able to trigger it with any other combination of settings, game or area within said game,

***How to reproduce the issue:***
1.Launch MGS3 and load the provided save [weirdperfbug.zip](https://github.com/PCSX2/pcsx2/files/2431266/weirdperfbug.zip)
2. tab out of PCSX2 and do some of the actions I've described have able to trigger that bug
3. if tirggered correctly the GS usage indicator should rise up suddenly and stay higher than usual

***Last known version to work:***
Unknown

***PC specifications:***
i7 4770k
Win 7x64 Ultimate
GTX 1070 w/ 411.63 drivers

**Comment by RedPanda4552** [comment]
Can confirm another case of this as discussed on Discord. Symptoms matched pretty much 1:1. MTVU seems to be the crutch here, as disabling it magically solves the problem. Some baseless shower thoughts, could the other processes either be starving the MTVU thread, or perhaps the Alt+Tab action causes VU1 to "get behind" somehow?

**Comment by refractionpcsx2** [comment]
Can you try this again? I believe this is solved now on latest development builds

**Comment by Helium-4** [comment]
It seems fixed, although it also seems Win10 by itself seems to make it harder to trigger the issue in older builds for some reason.

**Comment by refractionpcsx2** [comment]
okay well in that case we'll close this for now and revisit it if it crops up again. thanks for getting back to us
