### ISSUE TITLE
Crazy Taxi credits bug

### ISSUE THREAD

**Issue by PrgmrAtHrt** [PCSX2/pcsx2#2612]
***PCSX2 version:***
1.5.0-20180928023358

***PCSX2 options:***
Safest Preset

***Plugins used:***
GSdx 20180928023358

All default settings

***Description of the issue:***
When the credits are playing, the credits display begins to flicker. Also the console is flooded with "Vif1: Unknown VifCmd! [3f]"

***How to reproduce the issue:***
Play the game and earn at least $5000 so the credits begin to play.

**Comment by atomic83GitHub** [comment]
Well, if these errors are not fatal, you should ignore them. If you want to know, the PS2PS4 emu have a setting that hide Unknow CMD errors (for a performance reason). Humm, maybe you can try to change the EE/IOP clamping mode to see if this does anything.

**Comment by PrgmrAtHrt** [comment]
Changing the clamping mode does nothing. Also, I'm not emulating on ps4.

**Comment by orbea** [comment]
Maybe other people could reproduce this if you provided a save state shortly before the issue reproduced and a block dump of the credits.

**Comment by atomic83GitHub** [comment]
If someone have can manage to get to the credits with the PAL version, I would like to have a savestate before please.
