### ISSUE TITLE
UserHacks_SpriteHack review request

### ISSUE THREAD

**Issue by KrossX** [PCSX2/pcsx2#2615]
This hack was made in order to reduce some odd black edge on sprite parts in games like ArTonelico, Mana Khemia and Tales of Destiny DC. This problem appears to have been fixed already so unless there are other games that benefit from this particular hack, it might be time for it to be removed.

Official 1.4.0 release still shows the issue but the oldest automatic build from 2016-11-12 does not. I haven't checked what actually fixed it yet, but it was something in 2016 for sure. (EDIT) Fixed by PR #1538.

[Old forum thread about the issue](https://forums.pcsx2.net/Thread-Some-kinda-texture-bug-Ar-Tonelico-2-Mana-Khemia-2)
[Screenshot comparison gallery](https://imgur.com/a/TM30h9f)

**Comment by lightningterror** [comment]
It was needed for Fatal Frame series but that doesn't seem to be the case anymore (for intel and AMD) since https://github.com/PCSX2/pcsx2/commit/560966c539a9a7180bf60c7a3f6d2ca9a72bdb55
Not sure about other games.

That said Nvidia users might still need it.

**Comment by gregory38** [comment]
Lt you should check my dump database. I'm pretty sure I have a dump for this issue, and it could still be needed.

**Comment by MrCK1** [comment]
@lightningterror status on this?
