### ISSUE TITLE
Hardware issue with Snowblind-based games showing only half a screen

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#262]
When the following games are run in hardware mode only half the screen is operational and the other half becomes frozen. The games also contain graphic glitches in both hardware and software modes saying GSdx out of memory Textures temporarily disabled which is causing the texture glitches to occur possibly due to a memory leak.   

Baldurs Gate Dark Alliance (PAL-M5) [SLES-50672]
Baldurs Gate Dark Alliance 2 (PAL-UnK) [SLES-52188]
Champions Of Norrath (NTSC-U) [SLUS-20565]
Champions - Return to Arms // aka Champions Of Norrath 2 (Pal-UnK) [SLUS-53039]
Fallout Brotherhood of steel (NTSC-U) [SLUS-20539]

No previous version has these games working.

Old bug report link:
http://forums.pcsx2.net/Thread-Bug-Report-Baldur-s-Gate-Dark-Alliance-PAL

pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

**Comment by gregory38** [comment]
For reference there is a dev branch that try to fix the half screen issue.

https://github.com/PCSX2/pcsx2/tree/gsdx-half-screen-snow-engine

You must enable an option manually. It is not stable yet, try toggling native/upscale/opengl/dx.
```
force_1280_width = 1
```

**Comment by justgaming33** [comment]
@gregory38 Hey! I really want to try that out. could you pls explan what exactly i have to do? i just followed your link and downloaded the zip file. Thank you!Greetings!

**Comment by gregory38** [comment]
You need to build the source. If it is too difficult for you, just wait. We're still ironing out some details but hopefully the branch will be merged soon.

**Comment by justgaming33** [comment]
Okay, yeah i guess it is ^^. Thank you for the answer. I hope you will be succesfull.Good luck! Greetings from germany!

**Comment by huntzcom** [comment]
Hello, I have built the dev branch for this but don't know how to do the above, "force_1280_width = 1". Where exactly do I do this?
Also, I see this is set to be included in the 1.4 release, is there any estimations when this will be released?
Thanks

**Comment by gregory38** [comment]
Normally it must work without the option.

I don't know for the release but your test will help to merge it on the master branch.

**Comment by huntzcom** [comment]
Hello,
I downloaded and built the Snowblind fix dev build. I tested the game with all the above suggested option ie hardware/software gx, open gl etc and all other combos but I still have the half screen bug. It also has vertical green lines down the broken right hand side.
Thanks for attempting to fix this problem, I am a big fan of the snowblind games so I'm happy to test for you.
Thanks

**Comment by gregory38** [comment]
Is it working with the sw renderer?
Could you generate me a gs dump of your game?
Shift f8 => snaps directory

**Comment by huntzcom** [comment]
The Sw mode works perfectly.

All hw modes have the half screen bug. Here is the gs file and the image below

http://www.gadgetsfan.com/gsdx_20150529213733.gs

![gsdx_20150529213733](https://cloud.githubusercontent.com/assets/12565486/7892332/6f530104-064b-11e5-8edc-93fa2d767001.jpg)

**Comment by gregory38** [comment]
what is the name of the game?

**Comment by huntzcom** [comment]
Champions Of Norrath

**Comment by huntzcom** [comment]
Hey I have this working now using this https://github.com/PCSX2/pcsx2/pull/545
Very impressed so far, running at two times native res with all graphics enhancements in HW mode and its a smooth 60 fps. Wow

**Comment by huntzcom** [comment]
Testing has went went.
One issue I had was when setting a custom resolution as opposed to using native or scaling. I just get a black screen.
Frame buffer width 20 m_width set to 1920 multiplier 1Frame buffer width on vsync 20 m_width 1920

**Comment by gregory38** [comment]
Yes don't uses custom resolution.

Game fixed by latest git
```
Baldur's Gate: Dark Alliance II (2004) - Developed by Black Isle Studios.
Champions of Norrath (2004) - Developed by Snowblind Studios.
```
Game still broken
```
Champions: Return to Arms (2005) - Developed by Snowblind Studios.
```
Game status unknown (please test them)
```
Baldur's Gate: Dark Alliance (2001) - Developed by Snowblind Studios.
Fallout: Brotherhood of Steel (2004) - Developed by Interplay Entertainment.
The Bard's Tale (2004) - Developed by InXile Entertainment.
Combat Elite: WWII Paratroopers (2005) - Developed by Battlebourne Entertainment.
Justice League Heroes (2006) - Developed by Snowblind Studios.
```

**Comment by gregory38** [comment]
New PR available #575 Please test it. It will fix PAL version and Champions* games.

**Comment by gregory38** [comment]
Code was merged. Half screen issue is fixed on all tested games.

**Comment by justgaming33** [comment]
Congratulations on your success in fixing the problem.Amazing!
Finally some snowblind games WOHOOO!
I guess this fix is gonna be implemented in the next PCSX2 update?
Can a none programmer like me use this fix already? Thank you!

**Comment by jlwollam** [comment]
I was so excited to see this fix, unfortunately the game I was most excited to use this for was Justice League Heroes... which appears to not quite be fixed. Instead of only seeing half screen I see the left half duplicated :/ Is there anything I can do to resolve this or is that a larger problem?

**Comment by karasuhebi** [comment]
@justgaming33 Changes have been merged. You can just download the latest development builds from the buildbot:
http://buildbot.orphis.net/pcsx2/index.php

**Comment by Afrim502** [comment]
Total noob here, Sorry to ask but I had downloaded pcsx2 a while a ago and tried to play Champions Return to Arms but I too had the problem with the half screen but running it on SW mode fixed it, to fix this half screen bug what exactly do I have to do? I honestly don't understand what to do from reading all this. Sorry for the noob question, thanks in advanced

**Comment by willkuer** [comment]
Since the post above yours contained all necessary infirmation helping you might take more than a single post. But this is not a support forum. If you are looking for support please visit http://forums.pcsx2.net/ .
