### ISSUE TITLE
Graphical glitches on Metal Gear Solid: Subsistence

### ISSUE THREAD

**Issue by Lithium64** [PCSX2/pcsx2#2620]
***PCSX2 version:***
Latest ppa dev build 1.5.0~git201810041515~ubuntu18.04.1

***Plugins used:***
Gsdx
OpenGL Hardware
Internal 3X
Allow 8bit textures

***Description of the issue:***
Various graphical glitches on Metal Gear Solid: Subsistence

Screenshots and GS dump
![gsdx_20181005171341](https://user-images.githubusercontent.com/10705488/46558439-7ca27680-c8c3-11e8-9e78-9860c8147da7.png)
[gsdx_20181005171341.zip](https://github.com/PCSX2/pcsx2/files/2452146/gsdx_20181005171341.zip)
![gsdx_20181005171359](https://user-images.githubusercontent.com/10705488/46558440-7d3b0d00-c8c3-11e8-97dc-a601efd1787d.png)
[gsdx_20181005171359.zip](https://github.com/PCSX2/pcsx2/files/2452147/gsdx_20181005171359.zip)
![gsdx_20181005171447](https://user-images.githubusercontent.com/10705488/46558443-7d3b0d00-c8c3-11e8-8f07-b094800a87fe.png)
[gsdx_20181005171447.zip](https://github.com/PCSX2/pcsx2/files/2452148/gsdx_20181005171447.zip)

***How to reproduce the issue:***
Just play the game

***Last known version to work:***
1.4 stable works fine

***PC specifications:***

CPU: Intel i3-4150 
GPU: Gigabyte R7 260X 2GB Driver: Mesa 18.2.1
RAM: 12 GB DDR3
OS: Ubuntu 18.04 LTS Kernel: 4.15 default

**Comment by lightningterror** [comment]
I don't think it's limited to MGS only as I've noticed similar issues with other games that use texture shuffle using the Mesa3D For Windows gl dll.

**Comment by Lithium64** [comment]
> I don't think it's limited to MGS only as I've noticed similar issues with other games that use texture shuffle using the Mesa3D For Windows gl dll.
> 
> Edit: I can't seem to reproduce the issue anymore, maybe it was an error in my settings.
> 
> Anyway mind sharing a ss from your gsdx settings ?

![captura de tela de 2018-10-05 18-02-27](https://user-images.githubusercontent.com/10705488/46560122-ea9d6c80-c8c8-11e8-86e2-80cfc8c78008.png)
Which games use texture shuffle?

**Comment by lightningterror** [comment]
It might actually be the recent wrap uv regression that was introduced but that was fixed yesterday.
Regression was introduced on 2018-09-28 that broke a bunch of games and was fixed 2018-10-04.

Perhaps the daily PPA is not yet updated since the changes are still fresh.

**Comment by lightningterror** [comment]
Can you retest new PPA ?

**Comment by Lithium64** [comment]
> Can you retest new PPA ?

The issue was fixed with the latest build
