### ISSUE TITLE
Tomb Raider: Angel of Darkness PAL - Missing (obscured) notebook illustrations

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#2623]
***PCSX2 version:***

PCSX2 v1.5.0-dev-2584-g940263d49

***PCSX2 options:***

Problem only occurs while using software rendering (any backend) or OpenGL hardware.

***Plugins used:***

Default

***Description of the issue:***

Early in the game Lara obtains a notebook containing various pieces of info. This notebook is accessible through the pause menu (select button in game), and some of the entries in the notebook are accompanied by pictures. At least one of these is needed to solve a puzzle. 

The problem is that the pictures are not usually visible in PCSX2 in software mode or using OpenGL hardware. They are there, but they seem to be being rendered behind the notebook graphic rather than in front of it (setting VU round mode to nearest shrinks the notebook vertically, revealing part of the image behind it) :

![gsdx_20181007215802](https://user-images.githubusercontent.com/4227434/46586842-19a80f80-ca7c-11e8-8155-8c35c481b198.png)

This problem is present when using OpenGL hardware mode, or any software mode. Messing with EE or VU settings achieves nothing other than further graphic problems, however, for some reason the images seem to display just fine when using the DirectX 9 or 11 hardware renderers:  

![gsdx_20181007213004](https://user-images.githubusercontent.com/4227434/46586744-ae117280-ca7a-11e8-9f11-ac4f876b66e7.png)

I haven't found any GSdx settings that have an impact other than changing the backend. Also, while the DX11 renderer is largely fine, it doesn't display the icons when you pick up items, only the dark circle that should be behind the icon. I don't know if that could be related (though on testing I see that the game's missing shadows in DX11 too, so probably not).

GSDump: 

[TombRaiderAOD.zip](https://github.com/PCSX2/pcsx2/files/2454323/TombRaiderAOD.zip)

Incidentally, it's probably unrelated but this game also has issues with garbage polygons sometimes appearing in the viewport. This usually happens when the camera view is looking up towards Lara and a wall, floor, or object would really be blocking the view (the polygons are garbage though, not a properly rendered wall).
 
***PC specifications:***

Intel i5 3570K, Nvidia GTX 1080, Windows 10 1809

**Comment by MrCK1** [comment]
You have to boot in Full Mode.

**Comment by Silanda** [comment]
I'm already booting in full mode.

**Comment by MrCK1** [comment]
I will find which commit fixed DX11 later. I don't have time right now.

**Comment by lightningterror** [comment]
https://github.com/PCSX2/pcsx2/pull/1517 fixed it on dx.

@MrCK1 I leave it to you finding the exact change.

**Comment by lightningterror** [comment]
Commenting out this line seems to fix the issue on GL Hw.
https://github.com/PCSX2/pcsx2/blob/3fe9ff7ac835c2dbdf696cc4aaa476edab549f57/plugins/GSdx/GSRendererOGL.cpp#L207
