### ISSUE TITLE
Arabic Lang Update 

### ISSUE THREAD

**Issue by Omaranwa** [PCSX2/pcsx2#2627]
Hello there, i was going to work on arabic update soon , as arabic lang not updated for a long time.
so is there anything i need to know , like a guide or something like that

**Comment by MrCK1** [comment]
These are the files you're looking for: 

Here's a guide on using PoEdit: https://wiki.pcsx2.net/PCSX2_Documentation/Using_Poedit

Translating the GUI itself: https://wiki.pcsx2.net/PCSX2_Documentation/Translation_Guide

**Comment by lightningterror** [comment]
I'll go ahead and close this since all of the questions asked by the OP were answered, and since this is not actually an issue.

Feel free to ask if you have any other questions.
