### ISSUE TITLE
Add more exports

### ISSUE THREAD

**Issue by ThirteenAG** [PCSX2/pcsx2#2632]
Is it possible to add a couple of exported functions to return CRC of a currently loaded game, window resolution and aspect ratio settings (or perhaps just a pointer to GSWindowOptions struct)?

![](https://i.imgur.com/lzLvn5X.png)

**Comment by mirh** [comment]
Welcome boss. 
That was basically the point of that old question I asked you about scripting languages. 
#1923 and, more practically, #2412 are the trackers for the scaffolding of the feature you request.. 

But better if I'll let actual devs comment on it..

**Comment by stenzek** [comment]
Bad idea. If those variables are exported, someone's going to assume they can write to them, and all the dependencies of said variables won't be updated.

Better to implement a scripting engine in the emulator itself. Or use PINE, which already does half of this...
