### ISSUE TITLE
Silent Hill 3: FMVs are freezing emulator [only D3D11 mode]

### ISSUE THREAD

**Issue by isshininu** [PCSX2/pcsx2#2635]
***PCSX2 version:***
v1.5.0-dev-2615-gaf646895f
Latest dev build.

***PCSX2 options:***
![pcsx2_coresettings_gs-](https://user-images.githubusercontent.com/6324523/46902430-7ff6bd00-ced6-11e8-84ac-4ad105f5ca07.png)
![1395](https://user-images.githubusercontent.com/6324523/46902439-96047d80-ced6-11e8-8776-06f9582513f9.png)

- **Note**: 
Bug only present when DirectX renderers are used. Software renderers affected too.
OpenGL not affected...

***PC specifications:***
Nvidia Geforce 840m, Intel i7-4700mq, Windows 1809 x64.

**Comment by isshininu** [comment]
[snap.zip](https://github.com/PCSX2/pcsx2/files/2475200/snap.zip)

GS dump.

**Comment by lightningterror** [comment]
I can't reproduce the issue. Are all of your settings default ?

**Comment by isshininu** [comment]
hmmmmm

No. Not all my settings were set by default.
I found the reason:

![1396](https://user-images.githubusercontent.com/6324523/46902940-d8ca5380-cede-11e8-8881-514e4c88bc7a.png)
Game crash because of this.

**Comment by lightningterror** [comment]
Still not able to reproduce it tho.

**Comment by MrCK1** [comment]
Do you still have the issue if you switch to Software Mode during an FMV?

**Comment by LuismaSP89** [comment]
I cannot reproduce this issue, maybe you have a corrupted disk image or outdated graphics video drivers?

In the first screen you have a window of 1280x720 and a 4x Internal resolution, you tried with 1920x1080 in the first option and a 2x-3x Internal resolution?

**Comment by lightningterror** [comment]
60hz mode seems to be fine, it's only the 50hz mode that experiences the issue. 60hz mode fmv also looks a bit not properly rendered, there is a slight garbage screen before the fmv begins. Anyway I also reproduced the issue on opengl.

**Comment by lightningterror** [comment]
I'll do more testing in the future, it could be a regression.

**Comment by MrCK1** [comment]
@isshininu What Nvidia driver are you using? Could you do a clean install with DDU and see if the issue still exists?

**Comment by isshininu** [comment]
I am using 416.64 driver from nvidia.

**Comment by lightningterror** [comment]
Latest dev build will work fine now, make to keep "Switch to GSdx software rendering when a FMV plays" Gamefix always **off**.

**Comment by isshininu** [comment]
I did a test on latest 3345 dev build, it works with 50hz mode with enabled FXAA shader.
60hz mode is broken, though.
