### ISSUE TITLE
Silent Hill 3: missing motion trail effect

### ISSUE THREAD

**Issue by isshininu** [PCSX2/pcsx2#2636]
***PCSX2 version:***
v1.5.0-dev-2615-gaf646895f
Latest dev build.

***PCSX2 options:***
Everything by default. But it seems that it really didn't matter.

***Plugins used:***
Everything by default.

***Description of the issue:***

It looks like Silent Hill 3 have missed motion trail on light sources.
When moving, light sources can leave light tracks in PC version and PS2 version of the game, played on real hardware.
PCSX2 missed this effect in both hardware and software modes.

Here is a video of missing effect in PCSX2.
https://www.youtube.com/watch?v=U9cLWhFlc0Q

How it looks on real PS2:
https://youtu.be/BiocpDBNi6c?t=749

How it looks on PC version (basically the same as PS2)
https://youtu.be/QRlrHVn30a8

***Hardware specifications***
Intel Core i7-4700MQ
Nvidia GeForce 840M, driver 416.34.
Windows 1809 x64

**Comment by 60fpshacks** [comment]
It looks fine on my pc. Are you using the Opengl renderer?

![gsdx_20181016182537](https://user-images.githubusercontent.com/37403401/47031872-68cb0000-d160-11e8-8a19-f16d53cdb8ed.png)

**Comment by isshininu** [comment]
What version of emulator you using?

**Comment by 60fpshacks** [comment]
The latest one c92e76b

**Comment by Krusher97** [comment]
Does it have something to do with the PAL version of the game?

**Comment by lightningterror** [comment]
Possibly related to https://github.com/PCSX2/pcsx2/issues/2635

**Comment by isshininu** [comment]
> Does it have something to do with the PAL version of the game?

You want me to check another release of the game?

**Comment by Krusher97** [comment]
It could be possible that the effect is missing from the PAL release itself. Or it could be a bug with only the PAL version of the game.

**Comment by isshininu** [comment]
American version of Silent Hill 3 [SLUS-20622]
does have this effect
https://youtu.be/qboTRhM0Wyg

**Comment by lightningterror** [comment]
Can you test both 50 and 60 hz modes of the pal release ?

**Comment by isshininu** [comment]
Both 50/60 hz are missing that effect.

**Comment by MrCK1** [comment]
Any change on latest git? Maybe try both renderers and/or HW hacks.

**Comment by isshininu** [comment]
No changes.
And at this point I am not sure, if [SLES-51434] Silent Hill 3 (Europe) has this effect when playing on real PS2 console.

**Comment by isshininu** [comment]
![Снимок экрана (217)](https://user-images.githubusercontent.com/6324523/84643337-bdfb7e00-af0e-11ea-86cf-6408e34e5ddb.png)
Need to change **Display mode** from Sharp to Normal, lol
