### ISSUE TITLE
libsdl2 installation issues on xUbuntu 16.04 LTS

### ISSUE THREAD

**Issue by dhruvsus** [PCSX2/pcsx2#2639]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``
both stable build and eev builds from ppa from gregory and pcsx2-daily
- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](http://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
![image](https://user-images.githubusercontent.com/41652974/46916463-f5629c00-cf6f-11e8-9e14-62532e0368c3.png)

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Install Ubuntu 16.04.5 LTS
Install nVidia-410 drivers
Install Steam(might have installed certain i386 libs)
Add ppa for pcsx2
sudo apt-get install pcsx2

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Specs:
i5-6400
GTX 1080
Ubuntu 16.04.5 LTS
16GB DDR4

**Comment by arcum42** [comment]
This is really more of a Debian/Ubuntu multiarch issue than anything. When apt-get says "<x> depends on <y> but it's not going to be installed", it doesn't mean it *can't* be installed, just that it doesn't feel like it. I'd suggest running:
sudo apt-get install lib-sdl2-2.0.0:i386
first, then trying it again. And if that fails, do the same thing for whatever package name it wants. apt-get really does not seem to like installing dependencies for i386, from what I've seen.

**Comment by gregory38** [comment]
Yes it is a multiarch issue and it is debian/Ubuntu related. You should check it with your distribution. And this issue shall be closed.

**Comment by gregory38** [comment]
By the way, it is likely related to EGL/wayland (because I know it wasn't properly multiarch-ied when it was introduced). It should be fixed in recent release.

**Comment by MrCK1** [comment]
@dhruvsus is this issue still present?

**Comment by dhruvsus** [comment]
I haven't used PCSX2 in multiple years at this point and I've moved to 18.04, so I don't know.

**Comment by MrCK1** [comment]
Thanks for the response, I will close this unless the issue comes up again.
