### ISSUE TITLE
[Request] Per-pixel lighting

### ISSUE THREAD

**Issue by Al0ner** [PCSX2/pcsx2#2644]
I think it would be nice to be able to forcibly use per-pixel lighting (for example as in Dolphin), since in many old games used vertex lighting, which is very noticeable and ugly.

PS2 (broken outlines)
![ps2](https://user-images.githubusercontent.com/41343638/47056991-6d76cf00-d1c7-11e8-88cf-dfc794687824.jpg)
![ps2 ff](https://user-images.githubusercontent.com/41343638/47058841-7c617f80-d1cf-11e8-8693-bf3a3d6de54d.png)

PC (smooth outlines)
![pc](https://user-images.githubusercontent.com/41343638/47057018-9a2ae680-d1c7-11e8-920a-3ba28354425b.jpg)

**Comment by MrCK1** [comment]
You can't assume something done on another emulator will be possible on ours. This isn't possible due to the multitude of ways lighting can be calculated...
