### ISSUE TITLE
PCSX2 is using relative paths if the folders are inside the default folder

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#2646]
I don't know if this is a bug but here is a scenario.

I want to set the paths to the bios and memory cards folders by unchecking the "Use Default Settings" and set the paths to where they are so when I want to try some beta,I can just copy the inis folder and portable.ini and everything will be set.

If I do the above and the folders where the bios and the memory cards are happens to be the same as the default location,even if you uncheck the "Use Default Settings",pcsx2 will still set the settings in the ini as if the "Use Default Settings" was enabled.

Even if I manually add the paths,when I run pcsx2 and just go to Config=>Emulation Settings=>Hit ok,pcsx2 will restore the default paths(even tho the "Use Default Settings" is still disabled)

UseDefaultBios=disabled
UseDefaultMemoryCards=disabled
Bios=bios
MemoryCards=memcards

Changing the folders names,does nothing.
If the subfolders are in the default folder,pcsx2 will use relative paths regardless of if "Use Default Settings" is enabled or not

**Comment by avih** [comment]
Can you please give a specific detailed examle, including full folder paths, of what you're doing, what you're expecting to happen, and what happens instead?

**Comment by vsub** [comment]
Umm

1.Run PCSX2 and go to ConFig=>Emulation Settings
2.Uncheck "Use Default Settings"...here the expected behaviour would be pcsx2 to use full paths but he is still using relative paths
If the BIOS folder in inside the default location,unchecking  "Use Default Settings" will only change UseDefaultBios to disabled but the Bios= will be set as relative path since it is in the default location
Renaming the bios folder to Firmware for example will set
Bios=Firmware
Moving the bios folder to any subfolder which is inside the folder where pcsx2.exe,pcsx2 will still use relative paths
Bios=Bios\\Firmware

What I expect from the "Use Default Settings" option is when it is disaled,to use full paths
If I move the folder to any location outside the pcsx2.exe directory,only the pcsx2 will use full paths

**Comment by avih** [comment]
> Moving the bios folder to any subfolder which is inside the folder where pcsx2.exe,pcsx2 will still use relative paths

This is as designed for portable install. It tries to keep paths relative. If you change the path outside of the PCSX2 portable dir then it will become absolute on linux, and absolute but without a drive letter on windows. If you move it to a different drive then it will be absolute including a drive letter.

Can so describe what this behavior prevents you from doing, again, a specific example with actual folder names?

**Comment by vsub** [comment]
Actually,nvm,I understand why it is working that way and it is the correct way when using the portable version.

Also,I know this is an offtopic but after I know that,I can close this issue.
If I delete the portable.ini,can I still set all paths to be in D:\Games\PlayStation 2(where pcsx2 is now)?
Will pcsx2 still writes something outside the pcsx2.exe folder(AppData\Documents\Registry)if you set all of the paths
Bios=
Snapshots=
Savestates=
MemoryCards=
Logs=
Langs=
Cheats=
CheatsWS=
PluginsFolder=

**Comment by avih** [comment]
Not sure I follow your exact question, but if the ini at the pcsx2 portable dir doesn't have any paths in it, then pcsx2 will not come up with random paths names and write things to them...

For the third time, can you please describe an actual thing you're trying to do, with concrete full paths names, and which this behavior prevents you from doing?

**Comment by vsub** [comment]
> Not sure I follow your exact question, but if the ini at the pcsx2 portable dir doesn't have any paths in it, then pcsx2 will not come up with random paths names and write things to them...

I place those ini options just as a way to asking.
If I delete the portable.ini and set all the paths like this

UseDefaultBios=disabled
UseDefaultSnapshots=disabled
UseDefaultSavestates=disabled
UseDefaultMemoryCards=disabled
UseDefaultLogs=disabled
UseDefaultLangs=disabled
UseDefaultPluginsFolder=disabled
UseDefaultCheats=disabled
UseDefaultCheatsWS=disabled
Bios=D:\\Games\\PlayStation\\PlayStation 2\\Bios
Snapshots=D:\\Games\\PlayStation\\PlayStation 2\\snaps
Savestates=D:\\Games\\PlayStation\\PlayStation 2\\sstates
MemoryCards=D:\\Games\\PlayStation\\PlayStation 2\\memcards
Logs=D:\\Games\\PlayStation\\PlayStation 2\\logs
Langs=D:\\Games\\PlayStation\\PlayStation 2\\Langs
Cheats=D:\\Games\\PlayStation\\PlayStation 2\\cheats
CheatsWS=D:\\Games\\PlayStation\\PlayStation 2\\cheats_ws
PluginsFolder=D:\\Games\\PlayStation\\PlayStation 2\\plugins
RunIso=D:\\Games\\PlayStation\\PlayStation 2\\games

Will pcsx2 still write anything somewhere else?

The goal of the issue is to be able to try betas without going through the setting the bios path and memory cards folder every time and also configure pcsx2 and the plugins.

The bios folder is small so I can also copy it but not the memory cards folder(I am using the Folder Memory Card feature and I have almost 1000 files and 250 folders inside it)

And whant prevents me from doing this,is because in portable mode(which I want to use),no matter what you do,pcsx2 will always use relative paths unless the folders are in another drive and since I know that this is the correct behaviour in portable mode,I am asking now if deleting the portable.ini and settings all of the ini options as above,will pcsx2 still write someting somewhere else

**Comment by avih** [comment]
> in portable mode(which I want to use),no matter what you do,pcsx2 will always use relative paths unless the folders are in another drive

As I described earlier, this is NOT correct. Or at least should not be the case. It will use (on windows) absolute path without a drive letter.

There should be no issue to have several portable PCSX2 installations in different folders where all of them use the same common bios/memory-cards/etc folders.

So for the forth and last time, can you describe an actual case with actual folder names where you have whatever pcsx2 portable installation[s] and whatever else you're trying to do, and that this behavior prevents you from doing?

**Comment by lightningterror** [comment]
I have the bios, cheats, logs, snaps, sstates in different locations.
When updating to a newer version you just need to keep the old ini config folder and import settings.

**Comment by avih** [comment]
> can you describe

Here's an example of a useful description which a developer can follow to see your problem:

- Download and extract pcsx2 portable version 1.2.3.4 to folder `c:\pcsx2-1.2.3.4\`.
- Download and extract pcsx2 portable version 6.7.8.9 to folder `c:\pcsx2-6.7.8.9\`
- Run `c:\pcsx2-1.2.3.4\pcsx2.exe`, change this and that config options.
- Run `c:\pcsx2-6.7.8.9\pcsx2.exe`, change whatever configs (exact description).
- Run whatever.

I expect:
- That it will do (whatever you expect it to do).

Instead I get:
- It does (some other thing).

**Comment by vsub** [comment]
Nvm,I give up,I made 4 posts explaining the exact same thing but you are asking me the same question again

**Comment by avih** [comment]
> I made 4 posts explaining the exact same thing

No, you haven't. A developer needs a concrete example which can be followed exactly step by step (download this, run that, click whatever, create this and that folders, etc) to reproduce the issue you're seeing.

Without such exact demonstration of the issue (which you still didn't describe exactly), it's 100 times harder to help you.
