### ISSUE TITLE
Gauntlet Dark Legacy: Possible Texture Issues

### ISSUE THREAD

**Issue by Kidboy17** [PCSX2/pcsx2#2647]
***PCSX2 version:***
v1.5.0-dev-2631-gc92e76b17

***PCSX2 options:***
Everything Default

***Plugins used:***
Default plugins. I use DirectX 11 hardware, default settings.

***Description of the issue:***
Update: The misaligned texts ingame and weird outlines around the text of what Summoner says are completely gone if I use Nearest filter, they appear if you use PS2 bilinear.... which I had enabled from the beginning. Sorry for that.

The background image of the start menus has what it looks like to be artifacts. The cursor at the start menu seems to be the wrong color. The character images in the character select screen are very pixilated. There are misalignment issues or strange outlines with the texts. Seams on the ground and on certain objects that move like flags. I've included screenshots:
Start Menu:
![intro](https://user-images.githubusercontent.com/37382324/47115467-8311e600-d213-11e8-8976-13154a66cfed.png)
![start_menu](https://user-images.githubusercontent.com/37382324/47115471-860cd680-d213-11e8-9377-0d09803f127e.png)
Character Menu:
![gsdx_20181017132043](https://user-images.githubusercontent.com/37382324/47115488-91600200-d213-11e8-88d1-1e8a812d2c4d.png)
![gsdx_20181017132053](https://user-images.githubusercontent.com/37382324/47115492-93c25c00-d213-11e8-8dbe-357d68fc5489.png)
Texts and Seams:
![gsdx_20181014121106](https://user-images.githubusercontent.com/37382324/47115517-a341a500-d213-11e8-94e4-bc025f16f93b.png)
![gsdx_20181014121556](https://user-images.githubusercontent.com/37382324/47115522-a63c9580-d213-11e8-81d4-455195682122.png)
![seams](https://user-images.githubusercontent.com/37382324/47115529-a9d01c80-d213-11e8-95dc-7041de150d4f.png)

I also included a video from youtube that shows you how things should look normally.
https://www.youtube.com/watch?v=Lzu1CHab1b8
***How to reproduce the issue:***
Play the game normally, with default settings.

***PC specifications:***
Intel i5-4670k, Nvidia 780Ti, Windows 7 Ultimate

**Comment by MrCK1** [comment]
Can add your GSdx settings to the issue please?

**Comment by Kidboy17** [comment]
I use DirectX 11 hardware, default settings.

**Comment by MrCK1** [comment]
Can you try OpenGL?

**Comment by Kidboy17** [comment]
Just tried OpenGL software, has the same issues.

**Comment by MrCK1** [comment]
And DX11/OGL Hardware have the same issue?

**Comment by Kidboy17** [comment]
Yes, I just tried the OGL hardware and it has the same issues as well.

**Comment by MrCK1** [comment]
Hmm, I'll check myself later tonight. In the meantime, can you try adjusting texture filtering and/or hardware hacks to see if it fixes the issue?

**Comment by Kidboy17** [comment]
Of course I can. Anything specific you would like me to look at with hacks?

**Comment by MrCK1** [comment]
Not really, just see if any of them affect the visual quality noticable/fix the issue.

**Comment by MrCK1** [comment]
Oh, and also check the various Rounding and Clamping modes in the emulation settings after that.

**Comment by Kidboy17** [comment]
For both 11 and OGL hardwarde?

**Comment by MrCK1** [comment]
Yes.

**Comment by Kidboy17** [comment]
Ah well I made a mistake. I had PS2 bilinear enabled the whole time.... sorry about that. If I have nearest enabled, the misaligned texts do not appear and weird outlines on the texts from Summoner are gone but the other issues are still present, no mater if I use any other filter or hack for 11 and OGL. I tried messing with rounding and clamping but those did not improve anything.

**Comment by MrCK1** [comment]
I'll test it anyways because bilinear is supposed to be like the PS2 anyways. You shouldn't really have to use nearest to solve the problem unless it some sort of edge case.

**Comment by MrCK1** [comment]
I forgot to reply here sorry.

I looked into the issue and didn't really see anything out of the ordinary. Those gaps seem to be normal even at native resolution, that's just the nature of sprite alignment and the devs implementation AFAICS. As such, I'm going to close this.
