### ISSUE TITLE
Multitap

### ISSUE THREAD

**Issue by mccorkled** [PCSX2/pcsx2#2651]
Hello everyone. I did not see this mentioned in closed issues and the forum seems to be a bit dead. 

I am on PCSX2 1.4.0 and using Lilypad 0.10.0and I cannot get multitap to function. I set All pads up under port 1 multitap and enabled multitap under Config > Multitap 1. I just recently got back into messing with my emulators and would really like to play some 4 player games. 

Thank you.

**Comment by lightningterror** [comment]
This is not a support forum, please use https://forums.pcsx2.net/ for any support questions.
