### ISSUE TITLE
"Assertion failed: Vpu/Vif - Invalid Unpack! [11]" when trying to run Harry Potter and the Chamber of Secrets

### ISSUE THREAD

**Issue by capavanni** [PCSX2/pcsx2#2654]
***PCSX2 version:***
v1.5.0-dev-2638-gbb5d120a3

***PCSX2 options:***
All default

***Plugins used:***
All default. BIOS - USA v2.00 14/06/2004

***Description of the issue:***
When I try to run Harry Potter and the Chamber of Secrets it it gets to the part when it says it's checking memory card 1, and then I get a popup window with the following error.

> Assertion failed: Vpu/Vif - Invalid Unpack! [11]
> 
> ..\..\x86\newVif_Dynarec.cpp(196) : assertion failed:
>     Function:  VifUnpackSSE_Dynarec::ModUnpack
>     Thread:    EE Core
>     Condition: false
>     Message:   Vpu/Vif - Invalid Unpack! [11]
> 
> Stacktrace:
> [00] 0x00B282F0                                  
> [01] 0x009548C1                                  
> [02] 0x00953415                                  
> [03] 0x00B119B9                                  
> [04] NvOptimusEnablement                         
> [05] 0x00C0DF00                                  
> [06] 0x00A1ABD1                                  
> [07] 0x00E01645                                  
> [08] 0x00E014F0                                  
> [09] 0x00E01443                                  
> [10] 0x00C60A42                                  
> [11] o____lc_collate_cp_func                     
> [12] BaseThreadInitThunk                         
> [13] RtlValidSecurityDescriptor                  
> [14] RtlValidSecurityDescriptor     

***How to reproduce the issue:***
For me it's simply trying to run Harry Potter and the Chamber of Secrets. I've tried fiddling with some other BIOSes and plugin options but best case scenario I get the same error, worst it just shows a black screen when loading the game and no error.

***PC specifications:***
``OS Name	Microsoft Windows 10 Pro``
``Version	10.0.17134 Build 17134``
``System Type	x64-based PC``
``Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)``
``Installed Physical Memory (RAM)	16.0 GB``

**Comment by lightningterror** [comment]
What is your game serial ?

**Comment by capavanni** [comment]
I'm not sure how to find that.

The MD5 is `73c8df48f15b55400a6c80e4c21b1d02`.

I opened the ISO in 7zip and got the following in `system.cnf`.

```
BOOT2 = cdrom0:\SLUS_205.76;1
VER = 1.00
VMODE = NTSC
```

**Comment by lightningterror** [comment]
Can you test if the EE Timing hack/gamefix helps ?

**Comment by capavanni** [comment]
Just gave it a shot (had to tick off preset lock) and I got the same result.

**Comment by MrCK1** [comment]
Do you have automatic gamefixes enabled?

**Comment by capavanni** [comment]
@MrCK1 Sorry for the slow reply.

The default settings of the emulator (Preset ticked with slider on 2-faster) seems to have it ticked although greyed out.

When I untick preset, but don't change anything else, it is still ticked although not greyed out any more.

I'm happy to do provide other information if it will help.

**Comment by capavanni** [comment]
I didn't notice the Program Log title bar had more information.

    NTSC-U SLUS-20576 C7D5A403

**Comment by LovableGoat** [comment]
@capavanni  Hey. Were you ever able to get this fixed? I'm actually trying to play Harry Potter as well (It's always been one of my favorite PS2 games and I've had so much of an urge to play it lately) and I have the exact same issue you have. Any information would be much appreciated.

**Comment by capavanni** [comment]
I was able to but not with this ISO and I ended up using a different one in the end. For obvious reasons I can't link that but I'd recommend you try a different version of the game, be it a different build number from the same region, or a different region (Europe for example).

**Comment by tadanokojin** [comment]
> For obvious reasons I can't link that

Please do not discuss piracy

**Comment by capavanni** [comment]
> 
> 
> > For obvious reasons I can't link that
> 
> Please do not discuss piracy

That's what I said.

**Comment by willkuer** [comment]
In his shelf in a dvd box
