### ISSUE TITLE
[MacOS] Refusal to boot

### ISSUE THREAD

**Issue by GingkathFox** [PCSX2/pcsx2#2662]
***PCSX2 version:***
0.9.7

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](http://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``
no options
- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
none

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
I decided to download this since my PS2 refuses to read discs. I wanted to play some of my games.
I installed it and ran it, and this error appeared: 
[PCSX2 error.txt](https://github.com/PCSX2/pcsx2/files/2522466/PCSX2.error.txt)
0.9.7 is the latest Mac version on the site, has it not been updated?
EDIT: output in terminal:
```css
dyld: Library not loaded: /usr/local/pcsx2/lib/libwx_baseu-2.8.0.dylib
  Referenced from: /Applications/pcsx2 0.9.7 Alpha.app/Contents/Resources/pcsx2/./pcsx2
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
I dunno how detailed I have to get. Download and run on MacOS.

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
MacOS High Sierra (10.13.6)
CPU: Intel Core i5 (gen unknown, 2017 MacBook Air, 1.8 GHz)
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB

**Comment by RedPanda4552** [comment]
The OSX builds have been unsupported for several years now. We typically recommend running a Windows build inside a compatibility layer such as Wineskin.

**Comment by kenshen112** [comment]
Or using boot camp to install something like Windows or Linux

**Comment by GingkathFox** [comment]
yeah, I have a Ubuntu dual-boot, ima just use that then. thanks!
