### ISSUE TITLE
PCSX2 does not launch games in Mint 19 / Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#2666]
Ever since upgrading a test system to Mint 19 x64, I've discovered PCSX2 no longer launches games at all, let alone compiles (it ran fine under Mint 18 x64 / Ubuntu 16.04 x64 even if it wouldn't compile).  

When I attempt to install the latest nightly using dpkg, I noticed several dependency problems:

_Unpacking pcsx2-unstable:i386 (3:1.5.0-git201810282303-ubuntu18.04.1) ...
dpkg: dependency problems prevent configuration of pcsx2-unstable:i386:
 pcsx2-unstable:i386 depends on libgdk-pixbuf2.0-0 (>= 2.22.0).
 pcsx2-unstable:i386 depends on libgtk2.0-0 (>= 2.24.0).
 pcsx2-unstable:i386 depends on libportaudio2 (>= 19+svn20101113).
 pcsx2-unstable:i386 depends on libsdl2-2.0-0 (>= 2.0.8).
 pcsx2-unstable:i386 depends on libsoundtouch1 (>= 1.9.2).
 pcsx2-unstable:i386 depends on libwxbase3.0-0v5 (>= 3.0.4+dfsg).
 pcsx2-unstable:i386 depends on libwxgtk3.0-0v5 (>= 3.0.4+dfsg).
dpkg: error processing package pcsx2-unstable:i386 (--install):
 dependency problems - leaving unconfigured_

I then switched from dpkg to the gdebi-gtk installer to install the package, and that time it DID install, but upon launching the emulator I am presented with what appears to be a non-gtk set of UI widgets, and then when I attempt to launch a game, pcsx2 throws the exception:

_GS plugin failed to open.  Your computer may have insufficient resources, or incompatible hardware/drivers._

Again this was never an issue with PCSX2 and earlier versions of Mint / Ubuntu.  All drivers are fine and up to date, and all other apps and emulators such as Dolphin run just fine.

One other note, not sure if this is related, but attempting to install one of the dependencies for compilation (libgtk2.0-dev:i386) led to the following:

_The following packages have unmet dependencies:
 libgtk2.0-dev:i386 : Depends: libgdk-pixbuf2.0-dev:i386 (>= 2.21.0) but it is not going to be installed
                      Depends: libpango1.0-dev:i386 (>= 1.20) but it is not going to be installed
E: Unable to correct problems, you have held broken packages._

@gregory38 (or anyone else who may know): is there a way to resolve these issues easily (aside from running in chroot)?  Also, I don't think I should be getting any such dependency problems simply running pcsx2, I had assumed these would all be related to compiling up until now.  

There have been multiple similar reports such as [here](https://forums.pcsx2.net/Thread-Installing-on-Ubuntu-18-04-requires-removing-a-package) and [here](https://forums.pcsx2.net/Thread-Installation-on-Ubuntu-Bionic-18-04) as well.

**Comment by kenshen112** [comment]
So, I'm going to ask what might seem like a dumb question, what versions of those packages did you install? Do you have the X86-64? or X86?

**Comment by Shoegzer** [comment]
Yes I realize that, that's part of the problem and why I opened this issue.  It's not possible or practical for me (or really, anyone) to do that.

**Comment by raelgc** [comment]
I use the daily builds PPA and it works like a charm in 16.04 and 18.04: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by Shoegzer** [comment]
Hmmm.. are you using dpkg or gdebi-gtk to install, or something else?  And have you tried launching a game?  Again, it "works" here too with gdebi-gtk, but then renders menus improperly and throws exceptions before going ingame on anything.

By the way, that's exactly the PPA I used.  That does work with Mint 18.3 though, which is downstream from 16.04  Hopefully someone else with Mint 19 (downstream from 18.04) can confirm the problem.

Also, I just tried again with [the latest PPA build](https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily/+files/pcsx2-unstable_1.5.0~git201811161841~ubuntu18.10.1_i386.deb), and even though it seems a bit better than before, I still get this:
```
$ sudo dpkg -i pcsx2-unstable_1.5.0-git201811161841-ubuntu18.10.1_i386.deb 
Selecting previously unselected package pcsx2-unstable:i386.
(Reading database ... 486883 files and directories currently installed.)
Preparing to unpack pcsx2-unstable_1.5.0-git201811161841-ubuntu18.10.1_i386.deb ...
Unpacking pcsx2-unstable:i386 (3:1.5.0-git201811161841-ubuntu18.10.1) ...
dpkg: dependency problems prevent configuration of pcsx2-unstable:i386:
 pcsx2-unstable:i386 depends on libsoundtouch1 (>= 2.0.0); however:
  Version of libsoundtouch1:i386 on system is 1.9.2-3.
```
...and then when I attempt to get info on libsoundtouch1:i386, I get this:
````
$ sudo apt-get install libsoundtouch1:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsoundtouch1:i386 is already the newest version (1.9.2-3).
libsoundtouch1:i386 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pcsx2-unstable:i386 : Depends: libsoundtouch1:i386 (>= 2.0.0) but 1.9.2-3 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by Shoegzer** [comment]
Thanks, but again - how did you install this?  Should I assume you used apt?  And in any event, can you launch games?

Again I'm not using a 16.04 compatible distro, I'm using Mint 19 which is 18.04, which is why I used the package from the link I provided above.

I tried the apt command you provided above myself but got exactly the same error as with dpkg.

I can try the PPA as a test, but I'm not sure it would resolve anything based on the fact that I got the same error with apt.

**Comment by legluondunet** [comment]
@Shoegzer 
`
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).`

Your packages seems broken
In a terminal do a:
`sudo apt-get install -f` 

Then add the PCSX2 ppa like this:
```
sudo add-apt-repository ppa:pcsx2-team/pcsx2-daily
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install pcsx2-unstable
```

I'm using Ubuntu 18.04 and it works.
What did you obtain now?

**Comment by gregory38** [comment]
Did you install the 32 bits gpu driver ? What is your GPU by the way ?

**Comment by Shoegzer** [comment]
I haven't, come to think of it, although I didn't do that on Mint 18.3 and pcsx2 ran fine then. Given that nvidia-driver-390 is installed, should I just install nvidia-driver-390:i386 and nothing more?  And, would this conflict with anything else?  I've never installed the 32-bit drivers for anything else before hence my questions.

The GPU is an NVIDIA GTX 1070M.  Thanks for your help.

**Comment by gregory38** [comment]
It depends on the distribution so I can tell you. Maybe it will work, maybe you need only the gl libraries.

Based on your log, only a mesa driver (that emulate a GPU) seems to be found.

**Comment by Shoegzer** [comment]
@gregory38 Thanks.  

Here's what I get when I tried to install the 32-bit video driver:
```
$ sudo apt-get install nvidia-driver-390:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-390:i386 : Depends: xserver-xorg-video-nvidia-390:i386 (= 390.77-0ubuntu0.18.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
However, nothing shows up as "broken" in Mint's package manager, and "sudo apt-get install -f" doesn't report any issues nor fix anything.

Next I tried installing the dependency "xserver-xorg-video-nvidia-390:i386" as it seems to need above, but I get similar complaints about many more unmet dependencies.

What else would you suggest?  How would I install just the gl libraries as you mentioned?  I realize your distro may be different but it's bound to be a similar package to Ubuntu by name.

**Comment by gregory38** [comment]
Try to add dependencies on the cmd line. Maybe it will give you a real error msg. A package is likely not multiarch-aware. And should be reported upstream.

**Comment by gregory38** [comment]
Note: I don't use Ubuntu. And I can rebuild package myself, if I need to fix stuff.

**Comment by Shoegzer** [comment]
Thanks @gregory38.  

I tried installing the xserver dependency on the cmd line but I get this:
```
$ sudo apt-get install xserver-xorg-video-nvidia-390:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-nvidia-390:i386 : Depends: xorg-video-abi-24:i386 but it is not installable or
                                               xorg-video-abi-23:i386 or
                                               xorg-video-abi-20:i386 but it is not installable or
                                               xorg-video-abi-19:i386 but it is not installable or
                                               xorg-video-abi-18:i386 but it is not installable or
                                               xorg-video-abi-15:i386 but it is not installable or
                                               xorg-video-abi-14:i386 but it is not installable or
                                               xorg-video-abi-13:i386 but it is not installable or
                                               xorg-video-abi-12:i386 but it is not installable or
                                               xorg-video-abi-11:i386 but it is not installable or
                                               xorg-video-abi-10:i386 but it is not installable or
                                               xorg-video-abi-8:i386 but it is not installable or
                                               xorg-video-abi-6.0:i386 but it is not installable
                                      Depends: xserver-xorg-core:i386 (>= 2:1.19.6-1ubuntu2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm sure continuing this process for the other dependencies would just keep resulting in the same issue.  I do wish installing pcsx2 were easier/possible for Ubuntu and its downstream (Mint etc.) userbase, which are the highest number by far statistically.

In any event, maybe installing the gl library could get around this issue?  Would you have any suggestions for how I might do that?  I'm not sure what the package might be called - is that something mesa-related?

**Comment by Jj0YzL5nvJ** [comment]
First, you must enable the i386 architecture...
`sudo dpkg --add-architecture i386 `

**Comment by Shoegzer** [comment]
Thanks.  I had done that before though.  Just to be sure I tried it again and attempted install of the i386 nvidia and xserver packages as above but got the same results.

**Comment by Shoegzer** [comment]
@gregory38 Assuming what you said is correct and the lack of 32-bit nvidia driver is what causes the UI not to display properly or games not to render, I'm continuing to try ways to get the driver installed.  This time I used Mint 19.1's "Synaptic" package manager to install nvidia-driver-390:i386 but I get this:

![snap2](https://user-images.githubusercontent.com/12475371/51278932-dabb1b80-19d3-11e9-9445-c6e2889d090a.png)

So as someone indicated in the thread above, the x64 driver must be removed first - but that's not possible because many other applications rely on the x64 driver.  Any suggestions or ways around this?  

Also @legluondunet you mentioned pcsx2 works properly for you on Ubuntu 18.04 which is what Mint 19.1 is based off of - so how did you install the 32-bit driver?  Were you okay removing the x64 driver from your system, or do you not use nvidia drivers at all and never saw this issue?

**Comment by gregory38** [comment]
Install the driver from nvidia web site, maybe ?

**Comment by brainthinks** [comment]
I am getting this error too:

```
ATTENTION: default value of option mesa_glthread overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Failed to create the opengl context. Check your drivers support openGL 3.3. Hint: opensource drivers don't
```

Here are some relevant system specs:
* Linux Mint 19 (Ubuntu 18.04)
* Nvidia GTX 1080
* `nvidia-driver-410`

Here are some things I tried that did not work:
* installing all `mesa` packages
* installing `libglew` 
* deleted my `~/.config/PCSX2` directory and started over
* use the nightly channel, which claims to use 1.5.0-0

`glxgears` works fine, so there was no verbose logging I could get any info from.  Not sure what this means other than my "opengl stuff" appears to be working properly.

Also, as some others here have said, PCSX2 worked out of the box for me on Linux Mint 18.3 with the same hardware, with the 390 nvidia drivers (I think...).

Is there any other info I can provide?

**Comment by gregory38** [comment]
Again you need to install the 32 bits Nvidia driver.
Nvidia kernel module will handle both 32 and 64 bits. But you need to install both userspace. Those error messages are from the free driver which can't run with Nvidia module

**Comment by brainthinks** [comment]
From everything I've read, it seems you are correct, I have to install the 32 bit driver.  However, I am trying to avoid that, since I don't know what other impacts that will have on my 64 bit system, currently with the 64 bit driver.  I think it is unreasonable to have to downgrade my video driver to have opengl compatibility with only certain things - for instance, the glxgears demo works, and gzdoom works.  I'm not trying to complain about it, because I'm sure it's not trivial to get these things working with the 64 bit drivers - I know nothing about that.

While I wait for the compatibility issues with the 64 bit drivers to be fixed, since I'm not educated enough to contribute, I'm going to see if I can get this to work in docker or something.

Thanks for confirming that it is in fact the lack of 32 bit drivers.

**Comment by gregory38** [comment]
First 32 bits isn't a downgrade in most case.

Then the only impact to install BOTH gl userspace is few MB on your disk.

**Comment by Shoegzer** [comment]
@brainthinks I've had the same thought regarding libraries in general.  Installing 32-bit versions of libraries continues to impact the 64-bit versions increasingly negatively over time as more and more need to be fully replaced with each distro update.  I'm not sure what your experience has been, but here PCSX2 never compiled effectively, but at least it would run with Mint 18.x and earlier, just a year ago.

In the case of drivers as I mentioned above, nothing seems to help - the 32-bit versions are falling further and further behind the 64-bit versions these days and beyond not wanting to downgrade, I've encountered major issues when I tried non-repo drivers anyway.  We might have better luck with source distros like Arch or Gentoo but I haven't tried that yet.  If you do find a solution though, please post back here because I'm completely out of ideas at this point.

As you said a move to 64-bit would be SO welcome but it certainly isn't trivial and I'm sure needs more resources and effort than the team currently has.  There WAS some discussion about that a few years ago and even some movement towards an x64 emitter from some outside contributers IIRC but I don't know where that stands now.

**Comment by gregory38** [comment]
32 bits has no impact on 64 bits. Imagine that you have books in English (64 bits) and French (32 bits). Every time you compile a program, you do it twice to target the 2 languages. The only issue is that you need to store the books on shelves (HDD MB). Besides it requires 2 shelves (2 directories). 1 for English and 1 for French as the book name is always the same.
Having a French version of a book doesn't have any impact on the English book.

Porting PCSX2 is huge task, only to avoid to create an extra directory on your system

**Comment by Shoegzer** [comment]
Yes of course.  What I'm saying is that some distros like to keep those books cluttered on the same shelf which causes problems.  It's not an inherent issue with 32-bit libraries, but the way such distros like to organize them.  It's probably not the best use time to argue all the merits of a 64-bit PCSX2 beyond resolving this issue ;) so we can leave that be.  Suffice to say though that it would be greatly welcomed, though understood if it can't happen soon.

**Comment by brainthinks** [comment]
I didn't get anywhere with installing the 32 bit drivers, or with using docker.  I won't spell out the details here.  Hopefully once 16.04 is dropped from LTS, steam and others will care enough about this.  To be clear again, I'm not complaining, just stating that I'll have to wait since I don't know how to contribute an architecture update.

**Comment by Jj0YzL5nvJ** [comment]
https://www.reddit.com/r/linux_gaming/comments/cifell/can_anyone_help_me_understand_why_steam_wont/

**Comment by dukenukemx** [comment]
I just installed Linux Mint 19 on an old Athlon 64 X2 with a Nvidia GT 240, and PCSX2 won't work with the Nvidia 340 drivers.  I get "failed to load driver: swrast".  It works fine with Nouveau but those drivers are awful for everything else.  I'm using PCSX2 1.5 the unstable one from the PPA.

**Comment by Jj0YzL5nvJ** [comment]
@dukenukemx, have you tried `lib32-nvidia-utils`?

**Comment by Leopard1907** [comment]
I'm also on Mint with Nvidia binary driver but PCSX2 works just fine.

You're probably missing 32 bit driver.

**Comment by SalimF** [comment]
> Why not install the PPA directly and let it resolve the dependencies for the right version?
I tried and every time I got this message 

```
The following packages have unmet dependencies:
 pcsx2-unstable:i386 : Depends: libopengl0:i386 but it is not going to be installed
                       Depends: libsoundtouch1:i386 (>= 2.0.0) but 1.9.2-3 is to be installed
                       Recommends: libusb-0.1-4:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Shoegzer** [comment]
@SalimF you should be able to compile or install the x64 build now without any issues.

In any event I'm closing this issue as I had forgotten to do so after the x64 builds become possible earlier this year.  This avoids the need to maintain i386 dependencies on such systems.

**Comment by SalimF** [comment]
> I had forgotten to do so after the x64 builds become possible earlier this year

Sorry but all build decrements are talking about [32-bit compile](https://wiki.pcsx2.net/PCSX2_Documentation/Compiling_on_Linux)  and the 64bit [PPA](https://launchpad.net/~beauman/+archive/ubuntu/marley) got me this error 
```
 pcsx2 : Depends: libopengl0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Shoegzer** [comment]
I'd recommend opening a new issue for that then.  You can reference this one from there.
