### ISSUE TITLE
Metal Gear Solid 3 subsistence thermal goggles problem.

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2667]
***PCSX2 version:***
1.5.0-dev-2645-g8f52d82e5

Mgs3 subsistence has a problem when the thermal google is used.
Tried with both hardware opengl and directx 11, using different configs, all the same.

Image attached:
![sin titulo](https://user-images.githubusercontent.com/12205048/47760769-408de600-dcb6-11e8-96cd-40de3decead8.jpg)

***PC specifications:***
i7 4790k
16 GB DDR3
GTX 970
Windows 10 x64

**Comment by lightningterror** [comment]
Can you post a gs dump ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by LuismaSP89** [comment]
@lightningterror Sure, sorry for no provide it before. Here it is:

[snaps.zip](https://github.com/PCSX2/pcsx2/files/2535284/snaps.zip)

**Comment by lightningterror** [comment]
I'm not able to see anything, can you do a multiframe dump ?

**Comment by LuismaSP89** [comment]
@lightningterror Here you go: https://we.tl/t-ivN3kqka8J

Tell me if you need a more long multiframe dump, I recorded only two seconds more or less since it is too big filesize.

PS: The download remains only one week in wetransfer, tell me if you need another one.

**Comment by lightningterror** [comment]
Works fine on opengl. Set crc hack level to automatic.

Closing this in favor of https://github.com/pcsx2/pcsx2/issues/1339, https://github.com/PCSX2/pcsx2/issues/1318
