### ISSUE TITLE
DX 11 Hardware - Silent hill 3 (PAL) flashlight not working properly

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2668]
***PCSX2 version:***
1.5.0-dev-2645-g8f52d82e5

Silent hill 3 (PAL) flashlight not working properly in DX 11 Hardware, since the shadows are not rendered in the back of the objects, like if the light possition is reverted or something.

I don´t know how to explain, but here it is some screenshots in OPENGL and DX 11:

OPENGL:
![opengl](https://user-images.githubusercontent.com/12205048/47760934-dd508380-dcb6-11e8-843d-216428546b13.jpg)

DX 11:
![dx](https://user-images.githubusercontent.com/12205048/47760945-e8a3af00-dcb6-11e8-8b07-5da72d44086e.jpg)

OPENGL:
![opengl2](https://user-images.githubusercontent.com/12205048/47760954-f1948080-dcb6-11e8-8c66-9630e190530f.jpg)

DX 11:
![dx2](https://user-images.githubusercontent.com/12205048/47760963-f9ecbb80-dcb6-11e8-8c8f-38d7fc4807c0.jpg)

***PC specifications:***
i7 4790k
16 GB DDR3
GTX 970
Windows 10 x64

**Comment by lightningterror** [comment]
What if you set blending to None or Disable depth emulation in hw hacks for opengl, are you able to reproduce the issue  on opengl ?

**Comment by LuismaSP89** [comment]
@lightningterror Yes, you´re right, in this case, disabling depth emulation in opengl looks the same issue like the DX 11 backend. Disabling blending has no effects.

Do you need a gs dump? Or it´s enough with that info.

**Comment by lightningterror** [comment]
No it's fine. I'll go ahead and close this in favor of https://github.com/PCSX2/pcsx2/issues/2458
