### ISSUE TITLE
Ghosting in saint seiya - The hades

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2670]
***PCSX2 version:***
1.5.0-dev-2645-g8f52d82e5 (This problem is not new, it happens since ever)

Ghosting problem in saint seiya, specially in some scenarios with some characters (For example in Aries temple with Orpheus) (All characters affected btw)

Tested with both opengl and Dx11 backend, all settings, hacks, blending, IR, anisotropic, etc changed, the issue persist.

Image:

![sin titulo](https://user-images.githubusercontent.com/12205048/47883925-3c390880-de2f-11e8-9e56-4136c77bb998.jpg)

***PC specifications:***
i7 4790k
16 GB DDR3
GTX 970
Windows 10 x64

**Comment by MrCK1** [comment]
Post a picture of native resolution then.

**Comment by LuismaSP89** [comment]
@MrCK1 Here you go:
![sin titulo](https://user-images.githubusercontent.com/12205048/47887825-afe41100-de41-11e8-9e46-5e493dfa91ff.jpg)


It´s harder to see in native res, but it has ghosting too.

**Comment by lightningterror** [comment]
What about sw render ?

**Comment by LuismaSP89** [comment]
In software render is unnoticeable. Perhaps it´s the "aura" of the saints, but with the upscaling shows too much ghosting. 

**Software:**
![sin titulo2](https://user-images.githubusercontent.com/12205048/47922994-9af69480-deb8-11e8-9b04-d1cba250d777.jpg)

**Hardware 3x:**
![sin titulo](https://user-images.githubusercontent.com/12205048/47922995-9b8f2b00-deb8-11e8-833f-08be32d91f45.jpg)

**Comment by lightningterror** [comment]
For the record if you look closely it's there on software mode as well, just less. Increasing Anisotropic Filtering might help but that's about that. The sharper the image looks, the more the aura is visible.

I'll close this since it's not actually an issue.
