### ISSUE TITLE
[Feature Request] Video plugin Settings Hotkey

### ISSUE THREAD

**Issue by mcabel** [PCSX2/pcsx2#2679]
***Description of the issue:***
``
When setting up or configuring a new game, or when doing fine tuning with the resolution and optimizing fps, there is a lot of back and forth between the game and the plugin dialog. Pausing/escaping the game> Config >Video > plugin settings > [changing options]. 

+Instead a hot key could pause and window(or minimize) the emulator and open the plugin settings immediately, making testing of settings a breeze.  

+The key could be a toggle, to go back to the game, but maybe it could be weird going from a dialog to the game window.
-Instead of a toggle hotkey, the GSDX dialog could have an "apply settings and go back to game"-button. Which would return to the game in full screen or maximized window mode (based on user preferences settings)
``

**Comment by MrCK1** [comment]
If you're talking about changing the settings while the core is still running then that's not possible. The core has to be paused to apply the changes and/or write the settings to the GSdx.ini file.

**Comment by willkuer** [comment]
No as far as I understood just a hotkey for:
Running->Hotkey press->Suspending->Open gsdx dialog
And the returning button:
Close Gsdx dialog-> Save settings->Resume->Running

**Comment by lightningterror** [comment]
A hotkey option could be added to directly open the GSdx or any other plugin.

**Comment by lightningterror** [comment]
I will close this as it's really low priority.
