### ISSUE TITLE
Wild Arms Alter Code F (USA) - Wrong Text Presentation

### ISSUE THREAD

**Issue by Klauserus** [PCSX2/pcsx2#2684]
PCSX2 version:
Build v1.5.0-dev-2637-g6dca3656e

PCSX2 options:
Direct3D 11 (Hardware), Interlace Auto, TExture Filtering Nearest, Large Framebuffe, 3x Native, Mipmapping Basic, CRC Hack Level Auto

Note:

<a href="https://www.bilder-upload.eu/bild-b06317-1541969272.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/b06317-1541969272.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

Description of the issue:
the problem can only be seen from a higher resolution than native

How to reproduce the issue:
you can see it at the beginning/starting a game or in the intro.

Last known version to work:
None, I think.

PC specifications:
Phenom X4 955
6GB RAM
Nvidia GTX 650 Ti
Win7

**Comment by MrCK1** [comment]
Enable the Wild Arms hack and it should be fixed.

**Comment by lightningterror** [comment]
@Klauserus any update ?

**Comment by lightningterror** [comment]
I'm gonna close this since the wiki also states the same.
