### ISSUE TITLE
Destroy all Humans HD Crawl

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#2687]
PCSX2 1.5.0-Dev-2653
GsDxAVX2

Windows 10 x64
CPU- i5 6402p 8GB
GPU- AMD RX 480 4GB

Destory all humans will go to a crawl in HD going from 100% to 7% 2 Frame per 3 seconds
The Ram will fill up as windows starts to close other tasks and the CPU goes into 88% Use as the rest of the system becomes nearly unresponsive.
ways to reproduce is set a HD res and start the game then go to load game and watch the game slow down. switching to native res fixes the issue and once your ingame you can go back to HD but if another blue window pops up it will slow down again

**Comment by lightningterror** [comment]
Probably related to https://github.com/PCSX2/pcsx2/issues/1318

Do you have Large Framebuffer enabled ?

**Comment by RinMaru** [comment]
yea and... that fixed it. last time I tried that it didn't should this be left open or just close it?

**Comment by lightningterror** [comment]
Yea disable it if it causes issues.

**Comment by lightningterror** [comment]
See https://github.com/PCSX2/pcsx2/commit/dce6d3f4517615eabc84078e0bf448c29e56e6ee for more info

**Comment by RinMaru** [comment]
shame Street racing syndicate still locks up the entire system due to a similar issue not even large frame buffer disabled keeps it from eating all ram and forcing me to reset the desktop

**Comment by MrCK1** [comment]
Did you turn down your resolution?

**Comment by RinMaru** [comment]
anything higher then native locks up SRS I think I have an issue open on it and it reguires very specific settings to run

**Comment by RinMaru** [comment]
Issue is caused by Frame Buffer conversion in HW Hacks
