### ISSUE TITLE
SpongeBob SquarePants: Battle for Bikini Bottom (PAL/SLES-51988) won't get past splash screen

### ISSUE THREAD

**Issue by turboboy215** [PCSX2/pcsx2#2689]
***PCSX2 version:***
v1.5.0-dev-2662-g292dbbb6a

***PCSX2 options:***
None (I don't know which settings to choose)

***Plugins used:***
Default settings/Hardware renderer

***Description of the issue:***
The game won't advance past the very first screen of the game (the "legal" one). The GameCube version works perfectly in Dolphin but I would like to be able to play the PS2 version.

***How to reproduce the issue:***
Load the game into PCSX2 and wait several minutes and you'll see that the game is still stuck on that screen. No Nick Games, THQ, or Heavy Iron Studios logo or anything.

***Last known version to work:***
This never worked

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
CPU: Intel Core i5-6260U OS: Windows 10 64-bit

**Comment by RedPanda4552** [comment]
Wiki compatibility reports are saying this has been playable since PCSX2 1.0.0, even better so on 1.4.0. Can you confirm you are using default settings? Any console output worth noting? Dark red out of VRAM? Teal hung timeouts? Dark red TLB Miss? Just to name a few.

**Comment by MrCK1** [comment]
I tested it a few months ago, everything worked fine for me.

**Comment by RinMaru** [comment]
NTSC plays perfectly

**Comment by MrCK1** [comment]
I can't remember whether or not this game has a patch. Make sure Automatic Gamefixes is enabled.

**Comment by turboboy215** [comment]
Has anyone specifically tested the PAL version? I tried everything and still stuck at that same screen. Switching to software mode and pressing every button didn't do anything. No error messages at the console. My ISO came directly from Redump, so that shouldn't be the problem.

**Comment by turboboy215** [comment]
Also, the PAL version is listed as "Unknown", so does that mean that people have only tried the US version? And yes, "Automatic gamefixes" is enabled. So am I pretty much stuck?

**Comment by RinMaru** [comment]
dump the game yourself is going to be your next response I think

**Comment by turboboy215** [comment]
Yes, I actually own the game.

**Comment by turboboy215** [comment]
Tried using the DVD directly and had the same issue...

**Comment by RinMaru** [comment]
I don't have the PAL version so I cant do much to confirm

**Comment by MrCK1** [comment]
Did you try 1.4.0 to see if it boots there? @turboboy215

**Comment by turboboy215** [comment]
I remember trying that before I had the latest version and it had that same issue.

**Comment by MrCK1** [comment]
OK then, try 1.2.1 and 1.1.0.

**Comment by turboboy215** [comment]
Tried pretty much every version and still no dice. I feel like it's ONLY the PAL version that's broken, and not the US version, since I don't think anyone has actually tried the PAL version. I think it needs a patch or something. This is one of only two games in my collection that I couldn't get to work.

**Comment by RedPanda4552** [comment]
If it needs a patch, we need to know _why_ it's not booting first. Any console output along the lines of what I specified earlier?

**Comment by lightningterror** [comment]
Did you try without speedhacks ?

**Comment by prafullpcsx2** [comment]
This patch should help you

https://forums.pcsx2.net/attachment.php?aid=67819

**Comment by turboboy215** [comment]
Yes! That fixed the problem. Thank you!
