### ISSUE TITLE
[Request] about exclusive fullscreen

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2698]
Hello.

Pcsx2's latest versions don't have exclusive fullscreen.

I heard pcsx2's very older versions had this feature.

Why did it drop down exclusive fullscreen ?

Although nowadays many users prefer to borderless fullscreen,

We sometimes might need  exclusive fullscreen.

For instance, for graphic card unique functions like a radeon relive or mlaa, and so on.

I don't know this feature's implement is difficult.

But this feature is not a bad function.

Cheer up and Keep up the good job.

**Comment by willkuer** [comment]
There have been already a lot of discussions regarding exclusive fullscreen: https://www.google.com/search?q=exclusive+fullscreen+site:forums.pcsx2.net

**Comment by lightningterror** [comment]
There were a lot of major issues
https://forums.pcsx2.net/Thread-blog-A-new-kind-of-fullscreen

Anyway I don't see this getting implemented because of the same issues, getting it to work properly wound probably require a lot of work and might not be worth it.

I'll close this.

**Comment by TheTechnician27** [comment]
PCSX2 now has Exclusive Fullscreen support with the Qt UI.
