### ISSUE TITLE
cmake: Installation issues.

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#2699]
***PCSX2 version:***
https://github.com/PCSX2/pcsx2/commit/651d287f1da5047cda12ae81de832755c70aaef5

***Description of the issue:***

The following code in `pcsx2/CMakeLists.txt` has the following three problems, the first one is critical and makes it entirely non-working.

https://github.com/PCSX2/pcsx2/blob/651d287f1da5047cda12ae81de832755c70aaef5/pcsx2/CMakeLists.txt#L713

1. It is modifying `${BIN_DIR}/PCSX2` (`/usr/bin/PCSX2`) and not `$DESTDIR/${BIN_DIR}/PCSX2`, if `${BIN_DIR}/PCSX2` is not already installed on the system then it will fail. This results in modifying the old file to be replaced and not the new file to be installed. This can never work because `cmake` does not know the value of `${DESTDIR}` and only `make/ninja/samu/etc.` do. The alternative would be to modify it before its installed, but there doesn't seem to be a good place to do this without modifying `add_pcsx2_executable` in `cmake/Pcsx2Utils.cmake` to not actually install the files which would be messy.
2. Not all users have `/bin/bash`, but it should be entirely safe to use `/bin/sh` here as even with true bourne shells such as `hsh` this should work.
3. Not all users have `sudo` and using `sudo` inside of a cmake installation is a really terrible thing from a package management perspective.

***Last known version to work:***
This was introduced in PR https://github.com/PCSX2/pcsx2/pull/2586.

***PC specifications:***
OS: `Slackware64-current`
`cmake-3.12.4`

**Comment by lowlyocean** [comment]
Does slackware have something similar to debian/postinst? See https://github.com/PCSX2/pcsx2/pull/2638/files

**Comment by orbea** [comment]
For reference here are distros that package pcsx2, it seems most of them are not recent enough versions for this.

**Comment by lowlyocean** [comment]
That is outside my scope of influence. In fact, this Merge is not in a major release so it won't even show up in well-supported distro's (Ubuntu) official repos. It will only show up in daily build PPA

**Comment by orbea** [comment]
I think it will show up for the gentoo 9999 and AUR builds, OpenSuse and slackbuilds.org are also following git checkouts so it will show up there when they are updated. The latter I maintain so this could be potentially soon.

And eventually if and when PCSX2 tags another release other distros will also upgrade.

**Comment by lowlyocean** [comment]
@orbea Regarding  `bash`, yes it could in theory be replaced with `/bin/sh` but `set` is a builtin of bash. What's the equivalent in other shells? `sudo` might be replaced with `su -c` but then user has to know root password, and also it's possible that root account is disabled on the machine. I think managing post installation scripts is responsibility of individual distros not the project itself; at the very least, we might be able to change the CMake install command with something from Wireshark (which also presumably needs to setcap installed executables to allow unprivileged users to capture from network interfaces). Maybe https://github.com/wireshark/wireshark/blob/36d26b38d7cb9b36a525d5431cd45025f36bbbe5/CMakeLists.txt#L1053 is a starting point.

**Comment by lowlyocean** [comment]
Lines surrounding https://github.com/wireshark/wireshark/blob/ad21e3121f3307ee6cc2b4a2b296ef6dd83152ed/CMakeLists.txt#L2569

**Comment by orbea** [comment]
It should be perfectly safe to use `set -x` and `set +x` with `/bin/sh` which are included in the POSIX spec. Additionally `echo` should be safe with any plain text string wrapped in single quotes.
```
-o  option
    This option is supported if the system supports the User Portability Utilities option. It shall set various options, many of which shall be equivalent to the single option letters. The following values of option shall be supported: 
     ...
     xtrace
         Equivalent to -x.
```
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set

To further demonstrate, with `hsh` which is the heirloom shell or in other words a working true bourne shell which is not POSIX `set -x` works just fine.
```
$ hsh
$ set -x
$ echo foo
+ echo foo 
foo
$ set +x
+ set +x 
$ echo foo
foo
```
http://heirloom.sourceforge.net/sh.html

I agree that `setcap` should be the responsibility of the package maintainer and I really am not sure how to handle the root requirement in cmake in a portable manner.

I think the bigger issue is that its potentially using `setcap` on the wrong file.

**Comment by lowlyocean** [comment]
`setcap` in debian/postinst should be working on correct file. For cmake installation, I suspect we can use `${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}` rather than `${BIN_DIR}/${Output}`

**Comment by orbea** [comment]
For what its worth, my currrent workaround in my build script is:

Before cmake.
```
sed -i '/setcap/d' pcsx2/CMakeLists.txt
```
And in doinst.sh (Post-install).
```
if [ -x /sbin/setcap ] && [ -f usr/bin/PCSX2 ]; then
  /sbin/setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' usr/bin/PCSX2
fi
```
This seems satisfactory, the former sed hack is kind of silly though.

**Comment by lowlyocean** [comment]
> I think it should be something like `${DESTDIR}${BIN_DIR}/${Output}`, but that seems not possible when cmake does not know the value of `${DESTDIR}` until `make install DESTDIR=$PKG`.
> 
Could also adjust the build system to lift up DESTDIR into the Cmake realm but that's a high-touch change that - although limited to Linux - affects other plugins and the core

> It would be better if `setcap` was used before the binary was installed to the system, but I am not sure that is worth it especially when considering other issues like `sudo` and that it would require changing `add_pcsx2_executable`.
>
To preserve capabilities during copy, [special considerations](https://www.lesbonscomptes.com/pages/extattrs.html) are required.

**Comment by orbea** [comment]
I wasn't aware of the special considerations, this may cause further problems as `DESTDIR` could be a temporary directory intended for package creation. This is the case in Slackware, but `getcap` reveals the capabilities were preserved upon installing the new package on my system.
```
$ getcap /usr/bin/PCSX2
/usr/bin/PCSX2 = cap_net_admin,cap_net_raw+eip
```
However if someone is using a different file system this may not work? I am also not sure if `pkgtools` explicitly supports this or if it just happened to work... I'll have to investigate.

**Comment by lowlyocean** [comment]
> I think it should be something like `${DESTDIR}${BIN_DIR}/${Output}`, but that seems not possible when cmake does not know the value of `${DESTDIR}` until __`make install DESTDIR=$PKG`__.
> 
Doesn't that last part mean that you could just use something like ${PKG}${BIN_DIR}/${Output}?

**Comment by gregory38** [comment]
I think the dev plugin was moved in extra. So you shouldn't need all this by default.

**Comment by orbea** [comment]
Which plugin in specifically?

**Comment by lowlyocean** [comment]
@gregory38 After my enhancements the dev9ghzdrk was moved out of extras. Can't find exact commit at the moment

**Comment by lowlyocean** [comment]
I think for builds from source, it should be considered extras. But for distro builds (i.e., debian) it should remain core since the post-install script will be executing in elevated environment anyway

**Comment by lightningterror** [comment]
Is this still an issue?

**Comment by orbea** [comment]
Yes. The only thing that was changed was the ability to disable the offending code in the referenced PR.
