### ISSUE TITLE
[Translation] any PO file doesn't have correct English String.

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#2701]
***PCSX2 version:***
``1.5.0-dev-2689-g651d287f1``

***Description of the issue:***
There is couple of texts that doesn't match up with any of translation files.
such as [this](https://github.com/PCSX2/pcsx2/blob/651d287f1da5047cda12ae81de832755c70aaef5/pcsx2/gui/Panels/SpeedhacksPanel.cpp#L29).
This makes some texts that are unable to translate.

**Comment by knight-ryu12** [comment]
Yeah, that does work, but it'll make desync with template .pot file.

Could we update .pot instead?

2018年11月22日(木) 6:23、pgert さん（notifications@github.com）のメッセージ:

**Comment by pgert** [comment]
Yes, the templates could use an update - at least once #2412 & #2695 have been merged.
The pot files is only for new translations however.
If you want to update & improve an already existing one, use the PO-files from the locales folder.

**Comment by knight-ryu12** [comment]
but pot file have wrong English text too.
Could we update that **before** that merge? so we can clean.

What I'm thinking, is fix template,  merge into all po file that exists.

Note: ja_JP .po file is from PCSX2 0.9.9 (!)

**Comment by lightningterror** [comment]
If only the English strings could be in a file that's shared across all languages so if the gui gets updated you only need to update 1 file to change the English strings and not all.

**Comment by knight-ryu12** [comment]
True……
"Update from pot file" could be an option, yes.

**Comment by willkuer** [comment]
Well just add a localization for english. Use the hard coded keys as keys and if you want to change the displayed text just change the english po. This whole ‘changes translatable strings’ stuff is completely unnecessary.

**Comment by knight-ryu12** [comment]
thing is, there is no "English PO file", only pot, which is template
English String only.

Also I'm not meaning "change English string", meant update every po file to
have correct English strings.


2018年11月22日(木) 9:59、willkuer さん（notifications@github.com）のメッセージ:

**Comment by pgert** [comment]
When a translation is to be updated, the translator updates from code as I have descibed, and from this the translator can tell which strings that have been altered or added (POedit points this out). If all PO-files were to be updated just to include all strings, then the translator would have to go through everything to check for alterations.

An "Update from pot file" feature would be nice and dynamic, but it's something for POedit, and not something that can be applied localy for pcsx2.

**Comment by knight-ryu12** [comment]
why?
there's pot file in locale/template.

things I want is, is updating and cause desync with template file may be
bad in future.




2018年11月22日(木) 10:51、pgert さん（notifications@github.com）のメッセージ:

**Comment by knight-ryu12** [comment]
use ja_JP as reference.
