### ISSUE TITLE
Xbox 360 Controller OnePad Not Avaliable

### ISSUE THREAD

**Issue by SenatorPalpaMemes** [PCSX2/pcsx2#2707]
PCSX2 1.4.0-0

	Binding   GS: /usr/lib/i386-linux-gnu/pcsx2/libGSdx-1.0.0.so 
	Binding  PAD: /usr/lib/i386-linux-gnu/pcsx2/libonepad-1.1.0.so 
	Binding SPU2: /usr/lib/i386-linux-gnu/pcsx2/libspu2x-2.0.0.so 
	Binding CDVD: /usr/lib/i386-linux-gnu/pcsx2/libCDVDnull.so 
	Binding  USB: /usr/lib/i386-linux-gnu/pcsx2/libUSBnull-0.7.0.so 
	Binding   FW: /usr/lib/i386-linux-gnu/pcsx2/libFWnull-0.7.0.so 
	Binding DEV9: /usr/lib/i386-linux-gnu/pcsx2/libdev9null-0.5.0.so 

xbox 360 USB controller is not mappable in the GUI on Ubuntu

**Comment by lightningterror** [comment]
Onepad is plug and play, onepad legacy is mappable, also what about 1.5.0 ?

**Comment by trymeouteh** [comment]
My Xbox 360 wired controller is not being picked up in 1.5.0 when I try to map the controls.

**Comment by lightningterror** [comment]
Will close in favor of https://github.com/PCSX2/pcsx2/issues/2495
