### ISSUE TITLE
Midnight Club II - Top left corner issue

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#2708]
***PCSX2 version:***
https://github.com/PCSX2/pcsx2/commit/651d287f1da5047cda12ae81de832755c70aaef5

***PCSX2 options:***
`OpenGL (Hardware)`

***Plugins used:***
`GSdx (GCC 8.2.0 SSE2/AVX) 1.1.0 [libGSdx]`
`GSdx (GCC 8.2.0, SSE2) 1.0.0 [libGSdx-legacy-1.0.0]`

***Description of the issue:***

In `Midnight Club II` during races and arcade mode (Free driving) there will be garbage displayed in the top left corner of the screen. In arcade mode this does not display right away and will only do so when driving around for a little bit. It can also vanish for a short time when changing some settings like the `Automatic CRC Level`.

This only occurs with `OpenGL (Hardware)`.
![1](https://i.imgur.com/RQ8S7dh.png)
GSdump - http://0x0.st/s0bk.xz

The hack `Preload Frame Data` makes it much worse where it will be displayed across the whole screen instead.
![2](https://i.imgur.com/5AslYrc.png)
GSdump - http://0x0.st/s0bd.xz

This may be related to issue https://github.com/PCSX2/pcsx2/issues/1318 where `Midnight Club 3: DUB Edition Remix` is reported to have a similar issue.

***How to reproduce the issue:***

There are two ways.

1. Start `Midnight Club II` with  `OpenGL (Hardware)`.
2. Start career mode.
3. The issue should appear when starting the first race.

Or

1. Start `Midnight Club II` with  `OpenGL (Hardware)`.
2. Start arcade mode.
3. Drive around the city until it appears a short while later.

***Last known version to work:***
This is not a new issue, I can reproduce it with commit https://github.com/PCSX2/pcsx2/commit/61333ecb407984dc658b9d5015d529f8aba87ca3.

***PC specifications:***
OS: `Slackware64-current`
Compiler: `gcc-8.2.0`
mesa: https://github.com/mesa3d/mesa/commit/9367514524f70faad99c721bac92339c8ff8bad9

**Comment by lightningterror** [comment]
Can you run debug gl with `debug_opengl =1` in the gsdx ini and upload the gl debug log here ?

**Comment by orbea** [comment]
I'm not sure how much the gs dumps will help, I can not reproduce the issue with `pcsx2_GSReplayLoader` and either dump...

**Comment by orbea** [comment]
Where is the gl debug log created? I can't find any log with gl info.

**Comment by orbea** [comment]
Here is the multiframe GS dump, I still can not reproduce the issue replaying it. Additionally I can no longer create traces with apitrace while playing a game...

http://0x0.st/s0c-.xz

**Comment by orbea** [comment]
Any ideas on how to further debug this issue? While I can actually create a trace replaying the dumps here, apitrace is not capable of replaying them which recently worked with `Tales of Legendia`...

**Comment by orbea** [comment]
Here is a blockdump and save state, just start it, load the state immediately and then drive straight down the road. It seems to occur pretty consistently for me as I approach an underpass shortly after starting.

Dump - http://0x0.st/sDE2.xz
Save state - http://0x0.st/sDEe.xz

Can anyone else reproduce this? As far as I can tell this is the main issue making this game less enjoyable with PCSX2.

**Comment by MrCK1** [comment]
This has been added to the list in #1318. I will close this issue for now since it's linked there.
