### ISSUE TITLE
Devil May Cry 3 SE - Missing effect in the Pause menu

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2716]
***PCSX2 version:***
 1.5.0 dev 2699

***PCSX2 options:***
OpenGL HW with default settings 

***Plugins used:***
Default

***Description of the issue:***
When you pause the game in hardware renderer, a red filter effect is missing that is present in the software renderers. The pause menu also cuts the performance very heavily, making it drop from 250% in game to 130% in the menu at 2x Native resolution.
In the DX11 renderer the menu isn't even displayed. 
![gsdx_20181126222209](https://user-images.githubusercontent.com/25664221/49029520-d429d800-f1ca-11e8-8207-5361da9a9b05.png)
![gsdx_20181126222206](https://user-images.githubusercontent.com/25664221/49029528-d724c880-f1ca-11e8-869b-b3f2b7533d84.png)
[gsdx_20181126222206.gs.zip](https://github.com/PCSX2/pcsx2/files/2616580/gsdx_20181126222206.gs.zip)
The first screenshot is from the Software renderer and the second one is from the hardware one.

***How to reproduce the issue:***
Get in the game and press the Start button

***Last known version to work:***
None

**Comment by Krusher97** [comment]
That screenshot is from OpenGL. CRC hacks have no effect on it.

**Comment by lightningterror** [comment]
The menu is now properly displayed on dx11 with depth.
