### ISSUE TITLE
Steambot Chronicles - Missing grey filter in tutorial

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2722]
***PCSX2 version:***
 1.5.0 dev 2699

***PCSX2 options:***
OpenGL HW with 3x native resolution and Large Framebuffer disabled

***Plugins used:***
Default
Tested with all hacks

***Description of the issue:***
The grey filter in the tutorial is missing in HW renderers
![gsdx_20181128214652](https://user-images.githubusercontent.com/25664221/49169377-a033eb80-f35f-11e8-8a2b-1b6811016cc2.png)
![gsdx_20181128214714](https://user-images.githubusercontent.com/25664221/49169380-a32edc00-f35f-11e8-8e78-ea8742cfdfd9.png)
[gsdx_20181128214714.gs.zip](https://github.com/PCSX2/pcsx2/files/2625929/gsdx_20181128214714.gs.zip)

***How to reproduce the issue:***
Start the tutorial with the HW renderer

***Last known version to work:***
None

**Comment by lightningterror** [comment]
Can you do a multi frame dump as well ?

**Comment by Krusher97** [comment]
[gsdx_20181205203938.zip](https://github.com/PCSX2/pcsx2/files/2649375/gsdx_20181205203938.zip)

**Comment by lightningterror** [comment]
It's a channel shuffle effect not supported.

```
T:Error	ID:675	S:Mid	=> Channel shuffle effect detected (2nd shot)
T:Error	ID:675	S:Mid	=> Channel not supported
```
Here is a raw dump of the draw call anyone interested looking in to.
[Steambot Chronicles Raw Dump Draw call 675.zip](https://github.com/PCSX2/pcsx2/files/2687593/Steambot.Chronicles.Raw.Dump.Draw.call.675.zip)

Closing in favor of #1318
