### ISSUE TITLE
Partly, the screen appears strange.

### ISSUE THREAD

**Issue by choikiyeon** [PCSX2/pcsx2#2728]
PCSX2 version:
v1.5.0-dev-2709-g9abe96cba

PCSX2 options:
Defaults

Plugins used:
Defaults, OGL HW, DX11 HW

Description of the issue:
Only the last map will display the screen strangely.

PC specifications:
i5-3570, GTX 760, Windows 10 64-bit pro

GS Dump: (rename to .7z) SF_spritecorruption_gsdump.zip

RAW GSdx dump w/debug log: (rename to .7z)
syphonfilter_spritecorruption.zip

Normal - HW:
![32709116_2085387758417477_807899213986791424_n](https://user-images.githubusercontent.com/36502073/49324645-40af2900-f575-11e8-90cc-5ee14f5e94a6.jpg)

initial D ss Partly, the screen appears strange.

Is there a solution?

https://buildbot.orphis.net/pcsx2/index.php

v1.5.0-dev-2709-g9abe96cba <I'm using this.(2018-11-30 09:34:16)

![k-210](https://user-images.githubusercontent.com/36502073/49324728-342bd000-f577-11e8-8f66-2f2d877953f6.jpg)

![pcsx2_coresettings_gs window](https://user-images.githubusercontent.com/36502073/49507532-fbb42b00-f8c3-11e8-9209-6066c88a9100.png)
![pcsx2_coresettings_gs](https://user-images.githubusercontent.com/36502073/49507534-fbb42b00-f8c3-11e8-9264-09324e53fd11.png)
![pcsx2_coresettings_speedhacks](https://user-images.githubusercontent.com/36502073/49507536-fbb42b00-f8c3-11e8-99ae-f86737cc0395.png)
![pcsx2_coresettings_vus](https://user-images.githubusercontent.com/36502073/49507537-fc4cc180-f8c3-11e8-934e-fb0c248b8a44.png)
![pcsx2_coresettings_ee-iop](https://user-images.githubusercontent.com/36502073/49507538-fc4cc180-f8c3-11e8-8e52-15d757411bd3.png)
![pcsx2_coresettings_game fixes](https://user-images.githubusercontent.com/36502073/49507539-fc4cc180-f8c3-11e8-8144-38d8ec60fb78.png)

**Comment by MrCK1** [comment]
Please format your bug report according to the original template.

**Comment by lightningterror** [comment]
I don't see any gs dump.

**Comment by lightningterror** [comment]
Also why so many Gamefixes enabled, they can cause issues.

**Comment by lightningterror** [comment]
Closing, the user didn't provide any feedback.
