### ISSUE TITLE
Strange borders on GTA, Midnight Club, etc. when upscaling (hardware)

### ISSUE THREAD

**Issue by RIDE-2DAY** [PCSX2/pcsx2#2729]
***PCSX2 version:***
v.1.5.0-dev-2709-g9abe96cba

***PCSX2 options:***
Default emulation settings, excepting these in GS Window:
- Aspect Ratio: Widescreen (16:9)
- Custom Window Size: 1280 x 720

***Plugins used:***
[Plugins](http://oi67.tinypic.com/34hf792.jpg)
[Video plugin settings](http://oi66.tinypic.com/2us7pu9.jpg)

***Description of the issue:***
See those strange pixelated zones on the borders in the screenshots below:
[Bugged - Hardware + upscaling](http://oi68.tinypic.com/de661e.jpg)
[Bugged - Hardware + upscaling @ 1920 x 1080](http://oi64.tinypic.com/2f051sp.jpg)
[Not bugged - Software (native resolution)](http://oi66.tinypic.com/2m5j61v.jpg)

***How to reproduce the issue:***
I guess it easy to reproduce when using upscaling and the hardware renderer. They don't appear when using software mode, or hardware and native resolution.

***PC specifications:***
- OS: Windows 10 Pro
- CPU: Intel Core i7-8750H
- GPU: NVIDIA GeForce GTX 1060 6GB VRAM
- RAM: 16GB

**Comment by lightningterror** [comment]
It could be a depth effect that doesn't scale properly.

Closing in favor of https://github.com/PCSX2/pcsx2/issues/2860

**Comment by orbea** [comment]
@lightningterror Can you please explicitly add these games to the OP in the meta issue to help ensure they are not forgotten?

**Comment by lightningterror** [comment]
Added, I kinda forgot about it when I closed the issue, thanks.
