### ISSUE TITLE
Hot pursuit 2 strange overlay

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2738]
PCSX2 1.5.0-20181206123528 - compiled on Dec  6 2018

Hot Pursuit 2 has a strange over layer when using dx11 hardware mode, the software mode i think doesn't has this issue but i'm not sure because of the image quality. 

Using default speed seating 2 (safe) but non of the effect this glitch

Hardware mode dx 11

![pcsx2 2018-12-08 13-15-06-115](https://user-images.githubusercontent.com/5770076/49684313-fa654700-faeb-11e8-86a2-00bfc99b1f3e.jpg)

![pcsx2 2018-12-08 13-15-08-415](https://user-images.githubusercontent.com/5770076/49684314-018c5500-faec-11e8-955a-4c7fc01c3f7d.jpg)

Software mode DX11

![pcsx2 2018-12-08 13-13-48-896](https://user-images.githubusercontent.com/5770076/49684319-10730780-faec-11e8-9773-a932cef6f34f.jpg)
![pcsx2 2018-12-08 13-13-55-644](https://user-images.githubusercontent.com/5770076/49684322-1537bb80-faec-11e8-9895-3d5d12633167.jpg)

**Comment by Levan7** [comment]
@lightningterror 

Exactly same but additional it flickers (has a white flicker)

**Comment by lightningterror** [comment]
Do any of the hw hacks help ?

**Comment by Levan7** [comment]
@lightningterror 
Haven't test it one by one but with all of them enabled i get this (if anything it is worse)
Should i go one by one ?
![pcsx2 2018-12-08 13-39-42-943](https://user-images.githubusercontent.com/5770076/49684580-043c7980-faef-11e8-9c4f-ba2b975df1b8.jpg)

**Comment by lightningterror** [comment]
You shouldn't enable them all, try one by one.

**Comment by Levan7** [comment]
@lightningterror 
Well non of them have any effect well alpha makes it worse the above image is what you get with alpha.

**Comment by lightningterror** [comment]
Can you upload a gs dump ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
I'd prefer multi frame.

**Comment by legend800** [comment]
Needs skipdraw='4,4' to fix fog (breaks arrest cam a little but otherwise fine)

**Comment by lightningterror** [comment]
Latest build should render depth properly on dx11 however the game has a halfscreen issue on depth format on texture shuffle.

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/1339
