### ISSUE TITLE
Right Y axis not being detected with dualshock 3 over bluetooth

### ISSUE THREAD

**Issue by matheusfillipe** [PCSX2/pcsx2#2741]
***PCSX2 version:***
``Tested on PCSX2 stable build v1.4.0 and on beta 1.5``

***Plugins used:***
``OnePAD 2.0 and  1.3.0``

***Description of the issue:***

I am able to set up all other buttons and axis except the one on the right analog on the vertical direction(Y axis). The Axis is called axis 4 on jstest and all the other things I could set up it on, without any problem, but here when I move it is like if no event had happened. This problem happens on both version 1.4 and 1.5 of pcsx2. 

I couldn't  get  OnePAD 2.0 to detect anything from this joystick at all.

![image](https://user-images.githubusercontent.com/24435787/49687310-42826a80-fae8-11e8-8ff1-a0349cbc8333.png)

***How to reproduce the issue:***
``Just connect to a ps3 dualshock 3 joystick using Bluetooth and the  built in kernel drivers (Nos sixad or sixpair used). The joystick works just fine on steam and retroarch, all axis are detected by the system if I look on a tool like jstest-gtk so not a OS/driver issue.``

***PC specifications:***
``Laptop Dell Inspiron i15-7567, inboard bluetooth, Linux Ubuntu 18.04 amd64 with kernel version 4.19.2,  GTX1050ti, i7 7th generation, 16gb RAM, installed on a 256gb SSD``

I wonder if I could somehow manually set the OnePAD.ini configuration file or anything/hack  else to try and get this working?

**Comment by gregory38** [comment]
Latest onepad uses auto detection, so it should work in game but GUI willl be disabled. Better use this one 

Otherwise it used to have ds3 option on the GUI don't remember if there removed or still here.

**Comment by matheusfillipe** [comment]
Well I am not able to test the Latest beta 1.5.0 pcsx2 with libonepad 2.0  because it doesn't load and just stays stuck on a black screen doesn't matter which gs plugin version i use and also tried switching between software opengl and hardware....

But on the 1.4 version, launching a game with the latest onepad there (1.3) the right axis with problems does not move and seems to be not centred.

**Comment by MrCK1** [comment]
@matheusfillipe any update?

**Comment by matheusfillipe** [comment]
@MrCK1  Didn't have the issue anymore. Might have been some updating mess?

**Comment by matheusfillipe** [comment]
Updated to the latest beta (PCSX2 1.5.0-0 - compiled on Apr 23 2019) And it detects my ps3 controller but doesn't assign or let me assign any button. Doesn't detect input from my controller. Also updated version 1.4 and the issue is the same.

**Comment by lightningterror** [comment]
@matheusfillipe is the issue still present?

**Comment by andrybicio** [comment]
For me it is still present, I can't map the Yaxis for the right analog stick
Ubuntu 18.04, lib OnePad 0 - Dev 1.1.0., PCSX2 1.4.0

**Comment by lightningterror** [comment]
Closing in favour of #4016
