### ISSUE TITLE
Socom 3 dropps to snail speed when looking at the sun

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2744]
PCSX2 1.5.0-20181210031134 - compiled on Dec 10 2018

In the first mission the frame rate droops to snail speed when looking at the sun, the system steal shows 100% however the in game speed is clearly slower than it should be.

I'm using the default speed settings (2 safe) and using DX11
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2664145/emuLog.txt)

**Comment by MrCK1** [comment]
@Levan7 Is the game hanging or just slowing down - based on the log you posted it looks like it's hanging. Did you try booting normally without a savestate?

Can you also post your GSdx settings?

**Comment by Levan7** [comment]
@MrCK1 
No it isn't hanging it just slows down and if you look away from the sun the frame rate is normal, if i don't load the save file it still suffers from this issue.

**Comment by MrCK1** [comment]
OK then what about your GSdx settings, can you post them please?

**Comment by Levan7** [comment]
@MrCK1 
Couldn't find the config output so will an image work ? I'm getting (even the graphical glitches) same issues on software mode dx11 as well.

![1](https://user-images.githubusercontent.com/5770076/49814724-ac6a7080-fd83-11e8-8c5e-314727f53791.png)

**Comment by MrCK1** [comment]
Did you try using OpenGL and/or software modes?

**Comment by Levan7** [comment]
@MrCK1 
Yes i'm getting this issue on software mode, the open gl mode adds white blinking and i still get the slow down.

![socom](https://user-images.githubusercontent.com/5770076/49816021-75e22500-fd86-11e8-8f15-cf4cecfd91de.gif)

**Comment by MrCK1** [comment]
OK. You're not using any VU/EE cyclerate hacks right?

Also, you should try using the different EE/VU Clamping and Rounding modes to fix the polygons.

**Comment by Levan7** [comment]
@MrCK1 
Clamping mode **"none"** helped the polygon issue but non of the speed hack presets from 1 (safest) to 6 (mostly harmful) help the frame rate droop when looking at the sun

**Comment by Levan7** [comment]
@MrCK1 
Funny thing i don't get the sun frame rate drop on the PAL version

**Comment by MrCK1** [comment]
Closing in favor of #2748

**Comment by piau9000** [comment]
I think this should be reopened as it seems to be a diferent problem. The slowdown only happens when looking at the sun. In the log the following message keeps popping up when it happens:

sceGsSyncPath: VIF1 does not terminate
	<D1_CHCR=10000045:D1_TADR=001246b0:D1_MADR=001246b0:D1_QWC=00000010>
	<D2_CHCR=70000045:D2_TADR=00b20690:D2_MADR=00b206b0:D2_QWC=00000000>
	<VIF1_STAT=10000043:GIF_STAT=00000004>
