### ISSUE TITLE
[Feature request] Auto adjust 4/3 or 16/9.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2746]
***What is the request?***

The request is to add an option which switch to 4/3 or 16/9 depending on what the game does (like the Dolphin emu).

![capture](https://user-images.githubusercontent.com/26351275/49799007-182ce900-fd44-11e8-9003-9f9de28fd4e0.PNG)

**Comment by lightningterror** [comment]
See https://github.com/PCSX2/pcsx2/pull/1918

**Comment by atomic83GitHub** [comment]
Well it's not exactly that. What I mean is when the game set the ratio to 4/3 then select the 4/3 mode (and vice versa) the PR add an option to preserve the original game resolution which is different.

Take Jak 1 for instance,

This is the image you get when you set the 16/9 mode and set the game ratio to 16/9, as expected it's great.

![capture](https://user-images.githubusercontent.com/26351275/49799595-9fc72780-fd45-11e8-83e4-8380b2b6cd50.PNG)

But when you switch the game ratio to 4/3 you get a stretch 16/9 image.

![capture21](https://user-images.githubusercontent.com/26351275/49799770-0f3d1700-fd46-11e8-9bed-d014a0dd6917.PNG)

The request is to automaticaly set the emu ratio to what the game does like this:

![capture3](https://user-images.githubusercontent.com/26351275/49799819-31369980-fd46-11e8-840b-9462a78e23aa.PNG)

**Comment by lightningterror** [comment]
The PR actually does that, it switches automatically to what it detects the game is using.

**Comment by atomic83GitHub** [comment]
Well if the PR does that it's cool! Also, it's unelated but your commit for Jak 1 and 3 about mipmapping is not effective on Jak 1, I still have the mipmapping set to off.

![capture](https://user-images.githubusercontent.com/26351275/49800794-be7aed80-fd48-11e8-92ef-a1ac4f742280.PNG)

**Comment by lightningterror** [comment]
What is the crc id ?

**Comment by atomic83GitHub** [comment]
Jak and Daxter - The Precursor Legacy [9C712FF0]

**Comment by lightningterror** [comment]
Looks like I added the wrong game.

**Comment by legend800** [comment]
Yeah, half of my games are 4:3 and half are 16:9. I have to keep notes about which uses what and press F6 manually upon loading else I'll have either a squashed or stretched image. Big pain. Hopefully something comes along to solve that direct problem. That PR seems to be doing a lot of other things.

**Comment by lightningterror** [comment]
Do we have some sort of current detection for internal aspect ratio ? If so then we can make an automatic switch based on that, maybe @ssakash can help here.

**Comment by SA-X0** [comment]
Not sure if i can comment on something old, but don't want to open a request this is already opened.
I would love this as well, it's bit of a pain doing that manually for certain games, hopefully this gets added at some point.
Am aware of the widescreen patches, not saying they're bad, they're great but aren't perfect. 
To play the old way without modifying the aspect ratio.
Only emulator i know that has this auto detection is Dolphin, when the game is  4:3 is that, when switched to 16:9 the screen goes wide automatically.
Thank you for your time PCSX2 team, if is not allowed to post / comment on something for sometime like on the forums my apologies, won't happen again.

**Comment by refractionpcsx2** [comment]
There is no way to auto detect this as the game still renders the image in a 4:3 aspect ratio of space, and the resolution is also still only 4:3.  The only thing we can auto switch for really is 1080i since it is a bonafied (well, it's a meme on PS2 but let's roll with it) 16:9 resolution on the PS2.

I just checked Jak to confirm and the only thing that changes is the base pointer and the FIELD in the CSR (which field to render of the frame), but that could be due to me not timing it properly, it's certainly not a method of detection.

![image](https://user-images.githubusercontent.com/6278726/167478457-226ccd0b-a0b7-493a-bc3b-18590b0f9024.png)

So I'm going to say this is a no, sorry.
