### ISSUE TITLE
SOCOM II low framrate 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2748]
PCSX2 1.5.0-20181210031134 

I know i don't have a powerful pc but the performance looks strangely low, might be the pc but kinda don't get this on other games i tried to this extend.

I'm using all default settings only thing i changed is enabled DX11 in the graphics plugin.
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2669146/emuLog.txt)

**Comment by lowlyocean** [comment]
Try pressing F9

**Comment by MrCK1** [comment]
For the record, it's not a graphical slowdown - it's internal to the console. Not sure if there's anything we can really do to fix it.

**Comment by lowlyocean** [comment]
Is this slowdown at the title screen, too? I don't really have any framerate issues with newest builds from source. Using i7-7700k and GTX 1060, for reference

**Comment by Levan7** [comment]
@MrCK1 What does "internal" means ? The game speed clearly slows down and even the speech is slower than it should be.

@lowlyocean 

The F9 helped what does it do ?

**Comment by lowlyocean** [comment]
F9 switches Gsdx graphics plugin between hardware and software render. SW is quicker

**Comment by Levan7** [comment]
@lowlyocean 
Would never believe that using CPU would be faster than a GPU, how is this even happening.

**Comment by lowlyocean** [comment]
CPU usually favors task-parallelism whereas GPU is leveraged in modern graphics engines for data-parallelism. Since the plugin is emulating PS2 graphics hardware, it's likely that there wasn't much data-parallelism back. So, modern GPUs don't really provide any advantage. However, having multiple software threads apparently does

**Comment by atomic83GitHub** [comment]
Did you enable the EE timing hack? It fixes major DMAC timing problems causing abysmal performances. It should be automaticaly apply but maybe your game version is not in the GameDB.

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/3358
