### ISSUE TITLE
[GSDX] Big internal bug (potential game breaker)

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2749]
***PCSX2 version:***

1.5dev 2732

***PCSX2 options:***
All default (except MTVU)

***Plugins used:***
GSDX, all default

***Description of the issue:***
When testing a .elf, I spoted a very strange bug in GSDX Hardware that crash the program with this error:

"MyAssertion failed: next2<maxlev2  file:pixel.cpp , function:addpixel , line:152"
![capture2](https://user-images.githubusercontent.com/26351275/49830044-5fd96200-fd90-11e8-94d0-855c540f8919.PNG)

The bug is completly gone in software mode and the program continue with no errors.
![capture](https://user-images.githubusercontent.com/26351275/49830262-f4dc5b00-fd90-11e8-887b-7a03f4073ed9.PNG)

***How to reproduce the issue:***
Load aura.elf in Hardware mode and wait until the 2nd test.

***Not a regression***

***Here you can download a .elf package with aura inside***
https://drive.google.com/open?id=127FPlm-EEfQ0gD6YW3z7bVUIEyzLhuIY

***PC specifications:***
AMD FX8350 GTX 1060 Windows 10 64bits

**Comment by MrCK1** [comment]
It's a duplicate and the logging you posted is internal to the elf, those files mentioned aren't in PCSX2 they're just compiled into the ELF
