### ISSUE TITLE
[GSdx SW] Zettai Zetsumei Toshi 2 (Raw Danger) Trial A - Rendering Issue

### ISSUE THREAD

**Issue by Souzooka** [PCSX2/pcsx2#2753]
This issue is being posted after being tested on PCSX2 dev-2733 concerning the game serial [SLPM-60254]. This occurs on both the OpenGL and DX11 renderer.

Playing the game on software rendering mode reveals inaccurate emulation of a depth+tonemapping-based postprocessing effect.

Recording: https://gfycat.com/RipeVigilantHart

Images:
SW rendering:
![](https://cdn.discordapp.com/attachments/480478597799346186/523446640527409152/gsdx_20181215002958.png)

HW rendering:
![](https://cdn.discordapp.com/attachments/480478597799346186/523446549003501579/gsdx_20181215002922.png)

This problem does not occur on the retail release. Of course, this version of the game is not readily available to be obtained at this time (unless you get really lucky on JP Ebay or some such), but I would be happy to provide any additional information required upon request.

**Comment by gregory38** [comment]
Hw is wrong too. You can notice a small top left corner rectangle (which contains the post processing).

**Comment by gregory38** [comment]
Could you check sw renderer without extra threads ?

**Comment by Souzooka** [comment]
The same effect still occurs when using 1 rendering thread.

**Comment by atomic83GitHub** [comment]
This problem also happen in the final game  but the hardware render have a crc hack to avoid this glitch (and prevent insanelly vram usage Wen upscaling).

**Comment by tadanokojin** [comment]
I believe @Souzooka confirmed for me this is working on real hw.
This version of the game appears to do this effect without a TS.

**Comment by tadanokojin** [comment]
Part of the issue appears to be that the channel shuffle is using a SCANMSK to mask out the odd y coordinate:
![rd](https://cdn.discordapp.com/attachments/430072460671451137/796845211447590922/006392.png)

**Comment by tadanokojin** [comment]
After further investigation I realized I'd made a goof. Full issue is SCANMSK.
![000533](https://user-images.githubusercontent.com/26046960/119899394-0e49d100-bf11-11eb-8420-bd8fb06ef128.png)

**Comment by refractionpcsx2** [comment]
Okay Confirmed with @Souzooka that it's fixed.
