### ISSUE TITLE
Persona 4 - missing sound effects on newer builds.

### ISSUE THREAD

**Issue by Nikuw** [PCSX2/pcsx2#2757]
***PCSX2 version:***
``1.5.2765 (git)``

***PCSX2 options:***
Default.

***Plugins used:***
GSdx AVX2, LilyPad, SPU2-X (in Async Mix as TimeStretch doesn't fix the issue), cdvdGigaherz, USB/FW/DEV9 null

***Description of the issue:***
Some audio effects don't play or play at a very low volume. This mostly happens in menus, and sometimes when entering a battle.
``1.5.2561 (git)``: https://kozaczka.pro/pcsx2/working.mp4
``1.5.2765 (git)``: https://kozaczka.pro/pcsx2/broken.mp4

***How to reproduce the issue:***
Quickly swap between menu options. Holding L1/R1 on the Persona/Status/S. Link pages always causes this issue.

***Last known version to work:***
``1.4 Stable`` on Arch Linux doesn't have this issue, same with ``1.5.2561 (git)`` on Windows 7.

***PC specifications:***
CPU: AMD Ryzen 5 1600
GPU: AMD Radeon RX 460
OS: Windows 7 64 bit

**Comment by lightningterror** [comment]
I'm not able to reproduce your issue, what are your spu2-x settings ?
Also are you using savestates ? What if you load from a memory card ?

**Comment by Nikuw** [comment]
SPU-X settings are mostly default - Catmull-Rom interpolation, XAudio module, I've tried different latency settings between 40 and 120ms, both Async Mix and TimeStretch, no Audio Expansion.
I've tried restarting the game and reloading from a memory card which seems to have fixed the issue, but I think it might happen again after playing for a while.

**Comment by lightningterror** [comment]
Any update ?

**Comment by Nikuw** [comment]
Not yet, but I'll switch to playing on 2765 as soon as I can and then I'll close the issue if it turns out to be a one-time glitch. I'll let you know if it happens, and if it does then I'll try to find the cause.

**Comment by Nikuw** [comment]
I think it happened due to abusing fast forward during a rainy day, so I'll call this user error. The game seems to always have sound issues if you start it in fast forward mode and skip the intro. From what I've seen, this can happen when as you start fast forwarding and scrolling through menus when it's raining. If you play the game properly, at 100% speed this should never happen. Closing this as user error, sorry for wasting your time.
