### ISSUE TITLE
Manhunt 2 [SLUS_21613] Performance Issues/Graphical Issues

### ISSUE THREAD

**Issue by ZT-1** [PCSX2/pcsx2#2758]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2763-ge87a6b9cc-windows-x86

***PCSX2 options:***
![pcsx2_2018-12-17_13-59-27](https://user-images.githubusercontent.com/11493450/50110017-3c3a6f80-0207-11e9-8c7a-1dc6ee2f2d2d.png)

***Plugins used:***
![pcsx2_2018-12-17_14-00-39](https://user-images.githubusercontent.com/11493450/50110025-4197ba00-0207-11e9-82c8-5a655dc77c76.png)

***Description of the issue:***
![gsdx_20181217141304](https://user-images.githubusercontent.com/11493450/50110048-4bb9b880-0207-11e9-9934-6aac6c9da147.png)
![gsdx_20181217141322](https://user-images.githubusercontent.com/11493450/50110055-4f4d3f80-0207-11e9-88c9-e01919b3f110.png)

Poor performance especially on upscaled internal resolutions. Rectangle artifact in the top left of the screen in hardware mode. Aliasing issues and shadows looking like boxes.
https://youtu.be/7F3O18SrJWs?t=158

***How to reproduce the issue:***
Happens anytime in gameplay.

***Last known version to work:***
1.4.0
The performance is a lot better on 1.4.0, but the graphical issues are still present.

***PC specifications:***
Windows 10 Pro x64 - Intel i7 4790 - 16GB RAM - GTX 1060

**Comment by lightningterror** [comment]
It's a know issue.
Duplicate #1318

**Comment by Bigmac9922** [comment]
duplicated character shadows seem to spiral around the player as well as the additional blue left corner bug it is very annoying however (software mode) does fix both of these problems but this causes the game to be very slow and almost unplayable however even on a real ps2 this game is very laggy.

**Comment by Bigmac9922** [comment]
manhunt 2 might also have a problem with texture preloading being set to full almost as if it runs out of space.

**Comment by ps1freak26** [comment]
It will get fixed when it gets fixed. Harassing the devs to fix it is not good and going to make it take longer. I mentioned manhunt 2 because I tried to fix someones problem and they sent me a gs dump. I couldn't fix it no matter the setting. Frame buffer conversion changed the color of the square but didn't fix the problem.

**Comment by Bigmac9922** [comment]
I'm not dude I just put up the issues it had incase they wanted to look at it when they had the time plus I didn't even know you had even commented or even looked into the issue.

**Comment by ps1freak26** [comment]
I'm sorry but it's been an issue documented for 6 years.

**Comment by ZT-1** [comment]
To add some more info, there's also an issue with rendering effects.
Hardware
![Manhunt 2_SLUS-21613_20230118141227](https://user-images.githubusercontent.com/11493450/213273104-5d21a539-4cb4-4b4e-a6ea-9c22a3f18294.png)
Software
![pcsx2-qtx64-avx2_CILJkEF0L1](https://user-images.githubusercontent.com/11493450/213273156-f50fba13-38f9-4395-866d-20c91170f6d5.jpg)
