### ISSUE TITLE
God of war black box in cutscenes

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2761]
PCSX2 1.5.0-20181219171739 - compiled on Dec 19 2018

When enabling progressive scan in game a black box appears in cut sense when using DX11 
If i press F9 in cut sense the box disperses.
Using default speed seating 2
![pcsx2 2018-12-19 23-42-39-548](https://user-images.githubusercontent.com/5770076/50243863-ca6d4c00-03e7-11e9-85d9-2a0c68448930.jpg)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2696293/emuLog.txt)

**Comment by lightningterror** [comment]
What about opengl ?

**Comment by gregory38** [comment]
It is the memory wrapping. Might need large frame buffer too.

**Comment by Levan7** [comment]
@lightningterror 
Well when i use opengl, when the games starts there is a white transparent over layer on the full screen however when i enable progressive scan from options menu, the full screen becomes white.

**Comment by lightningterror** [comment]
Did you enable Large Framebuffer or Memory Wrapping to see if the issue is still present as suggested by Gregory ?

**Comment by Levan7** [comment]
Well on native resolution i couldn't enable large framebuffer but Memory Wrapping did the track and fixed the issue :)

![pcsx2 2018-12-21 13-02-30-090](https://user-images.githubusercontent.com/5770076/50334154-d3ae0400-0520-11e9-9c14-8dc9a198947d.jpg)
