### ISSUE TITLE
Skybox/lighting does not render correctly in Kingdom Hearts 2

### ISSUE THREAD

**Issue by JustinSpedding** [PCSX2/pcsx2#2765]
***PCSX2 version:***
1.5.26

***Plugins used:***
The bug occurs in GSDx OpenGL Hardware.
I tried multiple resolutions, anisotropic filtering on off/x16, blending unit accuracy on low/high, etc.
The only option that fixes it is switching to Software rendering, but that much slower.

***Description of the issue:***
When playing Kingdom Hearts 2, the skybox does not render, and the lighting does not render properly in some levels.

***How to reproduce the issue:***
Play Kingdom Hearts 2.
Go to the Mulan level (it is very noticeable there).
The sky should have clouds and stuff, but it is a solid gray color instead. When rotating the camera, some angles change the lighting to make it very bright.

***Last known version to work:***
It worked in the 1.4.0 builds, but I have not tried all of the previous 1.5.x builds since then.

***PC specifications:***
Linux Mint 19.1, 4.15.0-43-generic kernel, Nvidia 415.25 driver
i7 6700k, 16GB ram, GTX 1080

**Comment by lightningterror** [comment]
Can you upload a GS dump of the issue ? 
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by lightningterror** [comment]
Also can you specify properly which dev build you're currently using ?

**Comment by JustinSpedding** [comment]
Here is a link to a GS dump: https://drive.google.com/open?id=1D3b-wc-MrOfpPGNQw6FskURcEMPbSskX

I am not sure how to properly specify the build. The one I am using says `PCSX2 1.5.26-0- compiled on Oct 16 2018` and came from a package in https://launchpad.net/~samoilov-lex/+archive/ubuntu/retrogames called `1.5.26~git20181003.152742-1~retrogames`. Is there any other info you need?

**Comment by lightningterror** [comment]
![mpc-hc64 2018-12-21 04-57-21-61](https://user-images.githubusercontent.com/18107717/50324025-1948dd80-04dd-11e9-8640-7a3eb535acd7.png)

This is what I see on the dump both hw and sw so I don't see an issue.

**Comment by JustinSpedding** [comment]
Here is a video of the bug from my computer. Note: I have also encountered this same bug on a friend's computer, so it is not just me. https://drive.google.com/open?id=1pKqvoptq74uSaLbpIZYhmax8KhXjaMRm

**Comment by JustinSpedding** [comment]
I just installed the latest daily build from https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily, and the issue is no longer there. It seems like this was an issue in the October build, but has already been fixed.
