### ISSUE TITLE
Strange DLL makes PCSX2 plugin unresponsive

### ISSUE THREAD

**Issue by DRSDavidSoft** [PCSX2/pcsx2#2768]
***PCSX2 version:***
``pcsx2-1.5.0-dev-2704``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
When the file `AUDIOW32.DLL` is present in the `/plugins` directory and opening Config → Plugin/BIOS Selector menu, PCSX2 becomes unresponsive and crashes on the page with the following message:

    enumerating available plugins

I get **no logs** in the window indication which DLL is being loaded.

***How to reproduce the issue:***
Place the `AUDIOW32.DLL` file (_attached_) in the `/plugins` directory and try to open the Plugins Selector window.  Even though this file is not a PCSX2-plugin, it makes the PCSX2 crash.

📦 **[AUDIOW32.zip](https://github.com/PCSX2/pcsx2/files/2703194/AUDIOW32.zip)**

***Last known version to work:***
``None.``

***Desired fix:***
PCSX2 should not crash on trying to load DLLs like the one attached above, and causing the user to fully wipe the plugins directory.

Instead, it should either just warn the user that PCSX2 could not load the DLL, or just show a DialogBox informing the user of the loaded DLL that causes PCSX to crash.

**Comment by willkuer** [comment]
So you want us to load that dll possibly with elaborated rights? Honestly I‘d say don‘t play with dlls if you don‘t know what you are doing.

**Comment by lightningterror** [comment]
Not really an issue, people shouldn't place random dlls inside the plugins folder. It's for plugin dlls only.

**Comment by DRSDavidSoft** [comment]
@lightningterror Thank you for your quick response.

Is it possible to prevent PCSX2 from crashing if such a thing is loaded?

@willkuer I see that this sounds totally unsafe, but I was actually thinking if the PCSX2 could just analyze it without loading it, maybe it'd worth a try.

In any case, a VM is always the responsible things to use when a strange from the Internet gives you random DLL files :D

Thank you for your responses, in any case.  PCSX2 is a great work of art.

**Comment by DRSDavidSoft** [comment]
@lightningterror Could I ask that PCSX2 display a message with the path to a DLL _before_ it tries to load it, not _after_?  I believe this will be a useful change to have.

**Comment by tadanokojin** [comment]
No point cluttering the logs with plugin paths.
