### ISSUE TITLE
The Nightmare Before Christmas - Oogie's Revenge crashes 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2771]
PCSX2 1.5.0-20181219171739 - compiled on Dec 19 2018

In the beginning of the game when you enter a room the game crashes 

I am using default speed setting (2) however i was using 3x resolution in video plugin setting.

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2705393/emuLog.txt)

**Update**
Ok i figured out the game crashes when **Enable widescreen patch** is on

**Comment by lightningterror** [comment]
> Ok i figured out the game crashes when Enable widescreen patch is on

Not a real issue then, closing.

**Comment by Levan7** [comment]
@lightningterror  Well those widescreen fixes do come out of the box with the pcsx2.

**Comment by lightningterror** [comment]
WS patches are disabled by default and the tooltip does say WS patches can cause issues.
You can post in the forum thread regarding the issue to let people know about the patch.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches
