### ISSUE TITLE
Ratchet and Clank going commando background missing

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2772]
PCSX2 1.5.0-20181222155320 - compiled on Dec 22 2018

I'm using the default settings and i noticed that on the title screen and in the game menu the background is missing and i'm getting information like read write on memory card and enable turbo mode etc on the screen.

![pcsx2 2018-12-22 22-27-30-521](https://user-images.githubusercontent.com/5770076/50377605-c89ac700-0639-11e9-931a-694d7b8f5f72.jpg)
![pcsx2 2018-12-22 22-27-12-221](https://user-images.githubusercontent.com/5770076/50377606-cafd2100-0639-11e9-86cb-e295e0c644c7.jpg)

**Comment by lightningterror** [comment]
Duplicate #1318
