### ISSUE TITLE
Yakuza 1 - Flickering in certain menus and cutscenes

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2774]
***PCSX2 version:***
 1.5.0 dev 2818

***PCSX2 options:***
OpenGL with Default settings

***Plugins used:***
Default

***Description of the issue:***
The bottom right corner of images flickers even in SW renderers.
![gsdx_20181224170547_ 2](https://user-images.githubusercontent.com/25664221/50398663-53490680-079f-11e9-8f7c-26e36cb2e25d.png)
Video of the issue : https://drive.google.com/open?id=1Qh7RexqrLKeG_d2_xfOvNuSuyty3Imd4

***How to reproduce the issue:***
Buy the first Soul upgrade or replay any cutscene with static images.

***Last known version to work:***
None

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by ianfenix** [comment]
I seem to have found a fix for this issue. Just enable Emulation -> Game fixes -> EE timing hack and no more flickering in static images.
