### ISSUE TITLE
Yakuza 1 - Issue with Half Pixel Offset

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2775]
***PCSX2 version:***
 1.5.0 dev 2818

***PCSX2 options:***
OpenGL with 3x Native resolution and Half Pixel Offset set to Normal and Special
Blending Unit Accuracy set to High

***Plugins used:***
Default

***Description of the issue:***
Using the half pixel offset hack causes some lines to appear across the screen. The game needs half pixel offset at higher resolutions to prevent effects from misaligning and to remove a line at the right and bottom of the screen.
At Normal(Vertex):
![gsdx_20181224205920](https://user-images.githubusercontent.com/25664221/50402787-391f2080-07bf-11e9-94dd-d3439ed7a527.png)
At Special(Texture):
![gsdx_20181224205929](https://user-images.githubusercontent.com/25664221/50402789-3de3d480-07bf-11e9-85bf-962e3ad37ca9.png)
[gsdx_20181224205920.gs.zip](https://github.com/PCSX2/pcsx2/files/2707510/gsdx_20181224205920.gs.zip)

***How to reproduce the issue:***
Raise the rendering resolution above native and enable Half pixel offset.

***Last known version to work:***
None

**Comment by lightningterror** [comment]
Half Pixel offset isn't perfect, it can cause issues in games which is why it's a hack.

**Comment by Krusher97** [comment]
@lightningterror its needed by the game to align effects at higher resolutions.
![gsdx_20181224224940](https://user-images.githubusercontent.com/25664221/50404469-35df6100-07ce-11e9-9329-8270d28e667b.png)
