### ISSUE TITLE
Persona 3 Fes and Persona 4 Black Screen

### ISSUE THREAD

**Issue by Vulta93** [PCSX2/pcsx2#2782]
***PCSX2 version:***
stable build v1.4.0 and development builds v1.5.0-dev-2850-ga97bc2309-windows-

***PCSX2 options:***
Emulation Setting set to Safe

***Plugins used:***
https://imgur.com/a/sL5Zfwu

***Description of the issue:***
This are the only games that I have. I launch the game and I get a black screen. I can hear the audio in the background and clicking buttons works too. Using the Direct3D11 Renderer (both software and hardware) with the Nvidia GC gives me the black screen. If I use the Direct3D9 and the same GC it works. The Intel GC works with all the Renderers.

***PC specifications:***
Intel I7-2630QM, Nvidia Geforce GT 550M 2GB, Intel HD Graphics 3000, 10 GB RAM, SSD 480GB + 750GB HDD (PCSX2 is on the SSD, the game in the HDD)

**Comment by lightningterror** [comment]
And OpenGL ?

**Comment by Vulta93** [comment]
OpenGL (Hardware + Software) works with both GC.

**Comment by lightningterror** [comment]
Both Persona 3 and 4 work fine for me, maybe an issue with then dgpu and igpu detection ?

Closing this since it's not actually an issue with the emulator and rather seems an issue on the os/driver/ side. It could also be an user error.
