### ISSUE TITLE
Yanya Caballista: City Skater (JPN/USA) core emulation issues

### ISSUE THREAD

**Issue by tommai78101** [PCSX2/pcsx2#2783]
***PCSX2 version:***

```
PCSX2 1.5.0-20181213014710 - compiled on Dec 13 2018
Savestate version: 0x9a0d0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 17134), 64-bit
	Physical RAM     =  16241 MB
	CPU name         =  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Vendor/Model     =  GenuineIntel (stepping 0A)
	CPU speed        =  2.206 ghz (12 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Plugins shutdown successfully.
Reserving memory for recompilers...

Loading plugins from E:\Personal\desktop\pcsx2_1.5.0\plugins...
	Bound   GS: GSdx32-AVX2.dll [GSdx 20181213014710 (MSVC 19.00 AVX2/AVX2) 1.1.0]
	Bound  PAD: LilyPad.dll [LilyPad (20181213014710) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20181213014710 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20181213014710 0.11.0]
	Bound  USB: USBnull.dll [USBnull Driver 20181213014710 0.7.0]
	Bound   FW: FWnull.dll [FWnull Driver 20181213014710 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20181213014710 0.5.0]
Plugins loaded successfully.

(GameDB) 9768 games on record (loaded in 109ms)
```

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

```
- Default settings enabled. 
- No Clamping.
- No Rounding.
- No speedhacks.
```

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

***Description of the issue:***

Yanya Caballista: City Skater is notorious for its emulation core EE timing issue. And it has been known since 2015.

Refraction once mentioned, "Setting EE to interpreter drastically improves speed. but it won't fix the other problems." Since then, some were able to narrow it down to "core logic issues".

https://forums.pcsx2.net/Thread-Yanya-Caballista-City-Skater-SLUS-20278-U

***How to reproduce the issue:***

- When the game is loaded, stay on the Intro screen.   
- Wait for 30 seconds or when the Intro music fades away.   
- Watch the demo gameplay.

***Last known version to work:***
PCSX2 1.2.1.r5873 - Windows (Playable to In-game)

**Comment by MrCK1** [comment]
It's a very low priority and complex issue, I don't think it's likely that it will get fixed next year.

**Comment by refractionpcsx2** [comment]
Is this still a problem?

**Comment by refractionpcsx2** [comment]
apparently there's a patch for this now, so closing.
