### ISSUE TITLE
NBA Live 07 graphics problem

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2785]
PCSX2 1.5.0-20181226220003 - compiled on Dec 27 2018

Well when using dx11 hardware mode i'm getting graphical issues, however on software mode i'm not getting them.
DX11
![pcsx2 2018-12-29 18-33-40-601](https://user-images.githubusercontent.com/5770076/50539357-c33cff80-0b98-11e9-889a-5b95b94c8d10.jpg)

![pcsx2 2018-12-29 18-32-29-610](https://user-images.githubusercontent.com/5770076/50539355-bb7d5b00-0b98-11e9-9fb1-197eeea9e9e5.jpg)

Software mode
![pcsx2 2018-12-29 18-34-13-367](https://user-images.githubusercontent.com/5770076/50539360-cdf79480-0b98-11e9-812a-c45ecae7bb64.jpg)

**Comment by lightningterror** [comment]
Yes it's a known issue with EA sport games, someone needs to port Frame Buffer masking code from opengl to d3d11.

For now you can use opengl since the feature is only supported on that render.

**Comment by Levan7** [comment]
@lightningterror 
Open gl is a no go i think it has a memory leak or something on my system i"m getting garbage graphics and then pcsx2 crashes.

`Available VRAM is very low (-18173536), a crash is expected ! Disable Larger framebuffer or reduce upscaling!
GSDX OUT OF MEMORY`

![a](https://user-images.githubusercontent.com/5770076/50539734-9a1f6d80-0b9e-11e9-9ad2-ac8301f8fbaa.gif)

**Comment by Levan7** [comment]
Well i tried my best but pcsx2 crashes on opengl.

[snaps.zip](https://github.com/PCSX2/pcsx2/files/2716510/snaps.zip)

**Comment by gregory38** [comment]
It isn't a memory leak but a high memory requirements. Did you try to disable the large frame buffer option and use a smaller upscaling

**Comment by lightningterror** [comment]
I'm not noticing any issues on my end, gl looks perfect, what are your GSdx settings, do you have custom resolution enabled by any chance ?

**Comment by Levan7** [comment]
@gregory38 Well disabling large frame buffer i'm still getting garbage  graphics and  message
```
Available VRAM is very low (-4304096), a crash is expected ! Disable Larger framebuffer or reduce upscaling!
GSDX OUT OF MEMORY
```
However pcsx2 doesn't crashes. note that i'm using 2x native (-720)
if i enable native resolution i don't get memory warning but still get garbage graphics 

![pcsx2 2018-12-29 19-50-54-862](https://user-images.githubusercontent.com/5770076/50540045-ffc22880-0ba3-11e9-88ac-ae379075b3ad.jpg)

@lightningterror 
No only thing that i have changed is 2x native resolution and allow 8 bit textures every thing is default

**Comment by gregory38** [comment]
Out of memory means that we don't enough memory to allocate stuff. So you will get missing texture.

What are your RAM and VRAM setting.

**Comment by gregory38** [comment]
Use 8 bits texture to reduce memory requirements too

**Comment by lightningterror** [comment]
What are your system specs ?

**Comment by Levan7** [comment]
```
Physical RAM     =  4066 MB
	CPU name         =  Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
Amd 6870 1gb
```
I should point out that i'm not getting memory issues on dx11 same settings

**Comment by lightningterror** [comment]
Can you post the emulog when running Opengl ?

**Comment by Levan7** [comment]
Well it crashes and it doesn't record the crash ? it shows only the beginning of the startup

**Comment by lightningterror** [comment]
Can you run it on a different game ? I need the beginning detection of the vendor.

**Comment by Levan7** [comment]
Well if you are talking about graphics card it's xfx
I started gow and on opengl im getting white screen.
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2716569/emuLog.txt)

**Comment by lightningterror** [comment]
Are you using the latest Crimson drivers available to you ? They should be 16.1.2 beta or something.

**Comment by Levan7** [comment]
@lightningterror  Well if you want i will download those drivers but because this is an old video card i stuck with whatever w10 downloaded for me 15.201.1151.1008-151104a-296217E

**Comment by lightningterror** [comment]
Catalyst drivers won't work on pcsx2 gl, Crimsom is required, also make sure you set blending to at least Basic level.

**Comment by Levan7** [comment]
Well you were correct the Crimson drivers helped with the garbage on screen but i still get out of memory issue 
![pcsx2 2018-12-29 22-08-10-715](https://user-images.githubusercontent.com/5770076/50541024-a0214880-0bb6-11e9-99a3-d1d194162cde.jpg)
![pcsx2 2018-12-29 22-08-19-252](https://user-images.githubusercontent.com/5770076/50541026-a3b4cf80-0bb6-11e9-9b5c-504a8d620133.jpg)

**Comment by lightningterror** [comment]
The game is a bit gpu heavy on vram usage even on native res, I can easily hit 800MB on native.
I don't think there's anything that can be done at this point other than upgrading your hardware.

Make sure you're not running any other programs while running pcsx2, that will better allow system memory to be used when the gpu's vram is full. You could increase the pagefile size as that might help some way as well.

Other than that it's time for a system upgrade.

**Comment by Levan7** [comment]
I see but one thing why don't I have vram peoblems when using dx11

**Comment by lightningterror** [comment]
It's lower on dx11 because it emulates less effects. The more accuracy increases, the higher requirements will be. Also as Gregory suggested turn off Large Framebuffer.

**Comment by gregory38** [comment]
Hum, It feels like a channels shuffle effect not detected.

**Comment by lightningterror** [comment]
It does use 8bit shader so it's quite possible.

**Comment by lightningterror** [comment]
Fixed with fbmask port on d3d11 as well.
