### ISSUE TITLE
GSdx: Custom resolution discussion (drop or keep)

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2790]
Currently custom resolution is in a bad state, aside from the improper aliasing it causes because of improper scaling there are some major features that don't work with custom resolution.
Major features being such as Depth, Channel Shuffle, 8bit shader, all of which rely on upscaling multiplier to do the math in the shaders. This was less of an issue in the past because d3d11 was less accurate and we also had d3d9, but with the current fancy new features d3d11 got from gl and the drop of d3d9 this renders custom resolution basically useless. Some games will suffer more while others less from the issues however it's becoming quite an issue.

My proposal is we remove the gui option from Windows just like Gregory did on Linux. We can leave the ini options hoping someone will fix it in the future however I don't want 1.6 to be released with a broken feature like that that causes some major issues.

**Comment by RinMaru** [comment]
you mean custom res or the x2 x3 options?

**Comment by tadanokojin** [comment]
> 
> 
> you mean custom res or the x2 x3 options?

custom res

**Comment by RinMaru** [comment]
dropping it seems like a good idea then

**Comment by gregory38** [comment]
What about MSAA :p

**Comment by gregory38** [comment]
Cr can help to reduce memory requirements.

**Comment by Silanda** [comment]
There are still some cases where it can be useful, e.g. I've found that some 2D games benefit from doubled vertical resolution to help eliminate interlacing artefacts, while the horizontal resolution best remains at 1x to minimise graphical artefacts. These games typically don't seem to require the more accurate rendering features. 

However, if the option is generally problematic it's perhaps best to remove the GUI option and leave it as ini only.

**Comment by willkuer** [comment]
How many lines of code would be affected by a complete removal? Would it be possible to simplify most of the upscaling code and upscaling hacks? One could’ve considered to hide dx9 as well but I think it was a good call to wipe it. Possibly the same with CR?

I think supporting low resource setups shouldn’t be a major concern of pcsx2 nowadays. I don’t think intel atom netbooks and similar systems are relevant target platforms. However IMO improving accuracy and simplifying the code base is a good idea.

**Comment by legend800** [comment]
I'm personally a fan of leaving it in the UI as I have a few games that require 'custom res' to upscale properly like Resident Evil Dead Aim and I do not want to be fussing around in ini files...

How about a compromise and move it to the "hidden-by-default" Hacks area? That would seem appropriate given the issues, should address the main concern here, allow advance users to utilize it without time-consuming ini changes and preserve it in the UI for future updates.

![2018-12-30 09_32_00-d__video games_ps2](https://user-images.githubusercontent.com/20983844/50549679-0093a280-0c16-11e9-8efd-4106aa4938a0.png)

**Comment by RedPanda4552** [comment]
I do think it would be best to remove it for a full release, if it is going to compromise other effects so badly. Honestly, INI hacking is going to have to be the way to do it, cause I don't think breaking it off to its own GUI field is necessarily clean either. It's such an edge case that I just don't see the value in keeping it plainly visible. That said, if there's enough of a push to keep it for said edge cases, we could put a very, very aggressive tool tip on it, but that would still partially defeat the purpose of so many improvements that have been made so far.

**Comment by MrCK1** [comment]
I would either vote to remove it entirely or make it a hidden .ini option. I believe that custom resolution has causes its' own problems and has a tendency to break graphical effects. Basically, it's a larger burden to maintain and I don't think it will ever be perfect to the point where it's free of issues.

If it does get removed from the GUI and left as an "advanced option", then I think it should be left as-is and left out of consideration for future issues on Github.

**Comment by lightningterror** [comment]
Here is an example of Blood will tell displaying garbage screen on custom resolution where 8bit shader is not supported on custom res.

![pcsx2 2018-12-30 18-48-13-16](https://user-images.githubusercontent.com/18107717/50549799-8a1d9180-0c63-11e9-886e-0f470764e6eb.png)

I want to avoid issues like these.

**Comment by kenshen112** [comment]
I mean really at this point it's doing more harm than good if it can break more then the multipliers I'd say kill it with fire

**Comment by legend800** [comment]
It's an option that provides some value. Do NOT kill i, especially with fire. :) Bury it in the ini worst case. 

I look at it no different than the other numerous hacks in the emu, where there's NO substitute for a 'correct fix' at this time, so it's better than nothing, unless we want to say sorry, your games will be broken now or you can't make them better if you know what you're doing, because we want to clean up the UI....

**Comment by tadanokojin** [comment]
> I think supporting low resource setups shouldn’t be a major concern of pcsx2 nowadays. I don’t think intel atom netbooks and similar systems are relevant target platforms. However IMO improving accuracy and simplifying the code base is a good idea.

My thoughts exactly.
If we are going to remove it, let's remove it and not hide it.

Those against should be more specific about what games they are having issues with.

**Comment by legend800** [comment]
The only game for me that needed a custom res was RE Dead Aim (very, VERY fussy title). Just spent the past hour with it and was able to achieve (mostly) the same thing with keeping upscale at 2x, Align Sprite and Offset = normal. 

SO, with that, I'm ok with "killing" I guess. I just worry about other use cases and removing some nice flexibility for users.

**Comment by Silanda** [comment]
> Those against should be more specific about what games they are having issues with.

Phantasy Star Generation: 1 is a game I use it on. Using a doubled vertical resolution sharpens things up and helps to improve the vomit inducing juddering or blurring on the vertical scrolling. 

Running instead at x2 induces vertical tears in some graphics. Pretty minor but annoying. As far as I can tell sprite hacks achieve nothing other than to make the problem worse and/or introduce more serious glitches.

**Comment by legend800** [comment]
Can you try the Align Sprite hack for those games and see if it fixes the lines?

**Comment by mirh** [comment]
Having it moved to the hacks area seems enough for me. 
Too bad I cannot recall from the top of my mind the legit use cases for this I had heard in the past.

**Comment by Silanda** [comment]
> 
> 
> Can you try the Align Sprite hack for those games and see if it fixes the lines?

No it doesn't.

**Comment by Dreadmoth** [comment]
If custom resolution were to be removed entirely rather than just hidden in the .ini, it would be great if someone could resurrect / re-implement #1363. The current image scaling makes high multiples of native resolution look more aliased than custom resolutions that are an exact match or multiple of the display resolution.

**Comment by lightningterror** [comment]
Making it an ini option will kinda break it, every time you open the gui if the value is custom res it will reset to what the gui allows, so every time you want to change some setting after that you gotta change the upscale multiplier to custom res. Moving it to hacks is meh so we can leave the feature for 1.6 release as it is.
