### ISSUE TITLE
Ratchet and Clank 3 - Aquatos graphic issues

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2795]
PCSX2 1.5.0-20181231230234 - compiled on Jan  1 2019

In the Aquatos mission if you enter select menu and exit it you will get this graphical problems.
This happens on DX11 and opengl

![pcsx2 2019-01-02 14-05-42-243](https://user-images.githubusercontent.com/5770076/50587759-a5251700-0e98-11e9-93d9-32368f122810.jpg)

after entering map menu or any other menu

![pcsx2 2019-01-02 14-05-46-252](https://user-images.githubusercontent.com/5770076/50587777-b66e2380-0e98-11e9-9099-39a58018194e.jpg)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2720420/emuLog.txt)

[snaps.zip](https://github.com/PCSX2/pcsx2/files/2720421/snaps.zip)

**Comment by MrCK1** [comment]
Can you also upload a memory card and/or savestate please?

**Comment by MrCK1** [comment]
Thanks for the memcard. Closing in favor of https://github.com/PCSX2/pcsx2/issues/2088
