### ISSUE TITLE
compiling with musl libc fails due to backtrace() being available in glibc only

### ISSUE THREAD

**Issue by Mis012** [PCSX2/pcsx2#2796]
***PCSX2 version:***
``latest git (67a6f31b8828194269aec7ac030e00948200ab20)``

***Description of the issue:***
``the wxStackWalker feature of wxWidgets relies on the gnu extension backtrace(), and as such is not available on systems with libc other than glibc. This makes compilation fail.``

***How to reproduce the issue:***
``try to compile on a linux distribution that utilizes musl libc (e.g Alpine Linux)``

**Comment by mirh** [comment]
~~Wouldn't this be a wx problem first of all?~~
Ok it seems like they have their checks for that...
https://github.com/wxWidgets/wxWidgets/commit/eaff0f0d3f7828c2acd9ebde4979acc0b3fa43b5#diff-3b3a6ec97232deb43dc14319a73872c1R3770

So, did you try to just set `wxUSE_STACKWALKER` to 0?

**Comment by Mis012** [comment]
from  <wx/stackwalk.h> :
```
#if wxUSE_STACKWALKER

class WXDLLIMPEXP_FWD_BASE wxStackFrame;
```
and I get
```
/home/pmos/pcsx2/pcsx2/gui/AppAssert.cpp:43:34: error: 'wxStackFrame' does not name a type; did you mean 'GtkFrame'?
  virtual void OnStackFrame(const wxStackFrame& frame)
```
so wxUSE_STACKWALKER is probably set to 0 because wxWidgets have figured out during compilation that backtrace() isn't a thing

**Comment by Mis012** [comment]
So it seems they expect the app to check wxUSE_STACKWALKER?
would make more sense to name it wxCAN_I_USE_STACKWALKER then

**Comment by mirh** [comment]
Dafaq. Here's where it is defined:
https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/3rdparty/wxwidgets3.0/include/wx/msw/setup.h#L94
https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/3rdparty/wxwidgets3.0/include/wx/setup_inc.h#L90

**Comment by Mis012** [comment]
it's not like setting it to 1 would solve anything

**Comment by Mis012** [comment]
```
/home/pmos/pcsx2/pcsx2/gui/AppAssert.cpp:43:34: error: 'wxStackFrame' does not name a type; did you mean 'GtkFrame'?
```
still.

because of:
```
#if wxUSE_STACKWALKER

class WXDLLIMPEXP_FWD_BASE wxStackFrame;
```
still

**Comment by gregory38** [comment]
Just add the wx macro on our side to skip debugger backtrace.

Otherwise use a real libc ;) PCSX2 isn't designed to run on embedded card. Saving few MB of ram is pointless.

**Comment by avih** [comment]
> Otherwise use a real libc

A proper program doesn't depend on non standard/portable compiler extensions, or at the very least can be configured to not use them.

**Comment by Mis012** [comment]
Also, you have Android (x86) in long-term goals, and bionic libc doesn't support backtrace either

**Comment by Mis012** [comment]
and if this is only dependency on glibc extensions, it's not much hard work for the portability

**Comment by mirh** [comment]
So, does it work if you ifdef in AppAssert or not?

**Comment by Mis012** [comment]
it compiles, I didn't have the opportunity to test it yet

**Comment by gregory38** [comment]
We don't use fpic because it is slower and might clash with som asm code (most of asm code ws ported to intrinsic so it might be fine now). Fpic doesn't provide any gain for us as we won't load multiples plugins. But you're free to add it for your package.

**Comment by pixelherodev** [comment]
uh, you can use backtrace under musl pretty easily. In alpine, just install libexecinfo-dev. It's an extension library done _properly_ - that is, outside the libc.

I use it in my projects, works perfectly fine.

**Comment by pixelherodev** [comment]
The problem here is telling WX that.

**Comment by pixelherodev** [comment]
On my alpine system, adding libexecinfo-dev and adding `#define wxUSE_STACKWALKER 1` before including stackwalker.h in AppAssert.cpp works for me
