### ISSUE TITLE
Soul Calibur 3 Graphic glitch

### ISSUE THREAD

**Issue by Alissonjos** [PCSX2/pcsx2#2799]
PCSX2 version: 
Dev Build v1.5.2867

PCSX2 options:
EE Clamping - full
VUs Clamping - Extra

GS - default
Speedhacks - Multi-Threaded
EE Cyclerate and Cycle Skipping - default 

GSdx Settings - D3D11 Hardware
8-bit textures
2x Native 720p

Plugins used:
Relevant/Non-default settings of DEV9 plugin only

How to reproduce the issue:
just happens when i change the internal resolution to 2x, 3x ,4x .... native resolution

PC specifications:
CPU: Intel Core i5 4440, GPU: Aorus RX 570 4gb, OS: Windows 10 Pro 64 Bit

![640x448](https://user-images.githubusercontent.com/24876699/50697988-ed743e80-102a-11e9-8153-20b2a87f0541.png)
![1280x896](https://user-images.githubusercontent.com/24876699/50698198-70959480-102b-11e9-8a6e-8bea47ff9040.png)
![3840x2688](https://user-images.githubusercontent.com/24876699/50698071-1eed0a00-102b-11e9-97e2-dde1928be35f.png)

**Comment by lightningterror** [comment]
You can use align sprite and Half pixel offset to fix them, not a real issue so closing.
