### ISSUE TITLE
Gregory Horror Show - Voice Stuttering, audio breaks

### ISSUE THREAD

**Issue by Chris2D** [PCSX2/pcsx2#2800]
***PCSX2 version:***
PCSX2 1.4.0-2016 01 05 1.3.203 & PCSX2 1.5.0-20190103195503

***PCSX2 options:***
Defaults, no settings modifications affect the issue

***Plugins used:***
Defaults, no settings modifications affect the issue

***Description of the issue:***
All in-game character voiced dialogue repeats the last word spoken of each character. Items that can be picked up also repeat the last few seconds when picking up as well. In-game BGM seems to have micro-stuttering randomly.
Video of issue on another system, same exact issue: https://youtu.be/EwgL0YDZn1w?t=271

***How to reproduce the issue:***
After entering game and passing the first cutscene, speak to any character and dialogue will repeat. Picking up items in-game will also cause the issue every time. BGM will micro-stutter by itself on occasion by just waiting. 

***Last known version to work:***
None. This is an old known issue, referenced in https://wiki.pcsx2.net/Gregory_Horror_Show & https://youtu.be/bPNZ_7XLCjA

***PC specifications:***
CPU: Intel Core i7-7700k @ 4.20Ghz GPU: ASUS GeForce GTX 1060 6GB OS: Windows 10 Pro 64-bit (build 17763)

***Other Comments:***
The game was originally unplayable and in a joint effort with PCSX2 and Play! it appears that the audio wasn't looked at as referenced: https://github.com/PCSX2/pcsx2/commit/31ee576d6a0f015199d91948602a79bcc64c2d22#commitcomment-13679864 this was brought up in [#643](https://github.com/PCSX2/pcsx2/issues/643)

**Comment by MrCK1** [comment]
Try a dev build first from here: https://buildbot.orphis.net/pcsx2/

**Comment by Chris2D** [comment]
Thank you for the recommendation. I can report that PCSX2 Version 1.5.0-20190103195503 produces the same issues within the first few minutes as well.

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest master?

**Comment by Chris2D** [comment]
Hello,

I've gone ahead and tried running the game on PCSX2 1.6.0-20200506140834. After clearing the initial cutscenes I can confirm that the last word spoken by any character in-game still repeats one time. It still sounds like this video I've timestamped. https://youtu.be/EwgL0YDZn1w?t=285

**Comment by refractionpcsx2** [comment]
Yes, not 1.6.0, that's not what I'm interested in, please try the latest master, you can get a build from here: https://buildbot.orphis.net/pcsx2/

**Comment by Chris2D** [comment]
Right, my mistake. I've gone ahead and tried the game with build PCSX2 1.7.0-20201202230220. I can confirm the issue still occurs in this build.

**Comment by refractionpcsx2** [comment]
Okay thanks for testing

**Comment by refractionpcsx2** [comment]
Now fixed in master
