### ISSUE TITLE
Strawberry Shortcake - Adventures in the Land of Dreams (NTSC-U) [SLUS-21497] Broken stencil shadows on characters

### ISSUE THREAD

**Issue by huckleberrypie** [PCSX2/pcsx2#2801]
***PCSX2 version:***
v1.5.0-dev-2867-gc58acd110

***PCSX2 options:***
GSdx DirectX 11 (Hardware), native resolution, speedhacks disabled.

***Plugins used:***
 GSdx, SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD

***Description of the issue:***
Stencil shadows appear to be broken if GSdx DirectX 11 (Hardware) is used, but is otherwise fully playable. Switching to OpenGL (Hardware) solves the issue, but thought I'd bring this up regardless.

***How to reproduce the issue:***
Just load up the game as usual. The issue can be seen as soon as the opening cutscene starts where Strawberry Shortcake meets Ginger Snap at her home.

***PC specifications:***
CPU: Intel Pentium G4560 GPU: Nvidia GeForce GTX 1050 2GB (inno3D) OS: Windows 10 Pro 64 Bit

![gsdx](https://user-images.githubusercontent.com/5564327/50732902-40322f80-11be-11e9-88b4-bec10f57f90d.png)
![ogl](https://user-images.githubusercontent.com/5564327/50732927-943d1400-11be-11e9-95f7-13b209d27d20.png)

**Comment by gregory38** [comment]
Maybe try the date option

**Comment by huckleberrypie** [comment]
> 
> 
> Maybe try the date option

Not sure if you're trying to make a joke or two, but here's the GS dumps since it's from a game practically no one cares about. I thought I'd report this as it could help with any DirectX accuracy issues or something.

[GS_snaps.zip](https://github.com/PCSX2/pcsx2/files/2730515/GS_snaps.zip)

**Comment by tadanokojin** [comment]
It's a blending issue.

**Comment by huckleberrypie** [comment]
Care to expound on the blending issue? Is it because of that infamous issue regarding D3D lacking support for certain features versus OpenGL?

**Comment by lightningterror** [comment]
> Care to expound on the blending issue? Is it because of that infamous issue regarding D3D lacking support for certain features versus OpenGL?

Pretty much the answer.

I took a quick look, fbmask emulation to display the shadow figure properly(minus the shadow transparency), rest is blending.

**Comment by lightningterror** [comment]
I'll go ahead and close this, someone needs to port the code from opengl to d3d11.

**Comment by lightningterror** [comment]
Shadows should be better now on d3d11 when using high blending option, it still won't match opengl accuracy.

**Comment by huckleberrypie** [comment]
> 
> 
> Shadows should be better now on d3d11 when using high blending option, it still won't match opengl accuracy.

Can confirm that with v1.5.0-dev-3112, though yeah it is indeed slow on my laptop. I guess the performance penalty would be rendered null and void with a faster system though.

**Comment by lightningterror** [comment]
Yes it will be slow with the way the effect is handled compared to opengl. On my end I'm seeing a 3x performance hit. On opengl it's basically free.
