### ISSUE TITLE
Ubuntu Cosmic repository does not have a release file

### ISSUE THREAD

**Issue by illQuo** [PCSX2/pcsx2#2802]
***PCSX2 version:***
I'm trying to download the latest PCSX2 builds from both the daily repo and the official repo

***Description of the issue:***
When following the instructions here: https://launchpad.net/~gregory-hainaut/+archive/ubuntu/pcsx2.official.ppa - after adding the repository, I am returned with the following errors as below:

`E: The repository 'http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu cosmic Release' does not have a Release file.`

`The repository 'http://ppa.launchpad.net/libretro/stable/ubuntu cosmic Release' does not have a Release file.`

***How to reproduce the issue:***
Install Ubuntu 18.10 Cosmic, add repo and you're greeted with the error.

***Last known version to work:***
Since Ubuntu 18.10 is new, I don't believe any previous versions of PCSX2 will work.

***PC specifications:***
Microsoft Surface Pro running Linux VM

**Comment by gregory38** [comment]
I don't plan to add it for multiples reasons
* I don't have any free time
* Some GCC workarounds must be backported to 1.4 branch (back to first point)
* 1.4 is rather outdated

There is another ppa available with latest dev version (check pcsx2.net for the link).

**Comment by illQuo** [comment]
@gregory38 Very well. I'll just install Ubuntu 16.04 32-bit and start over. Thanks anyway.

**Comment by gregory38** [comment]
Why don't you use the dev ppa ? (Automatically generated every day)

**Comment by illQuo** [comment]
I have tried this but I get the exact same error. I don't think PCSX2
supports the newer versions of Ubuntu just yet. I will need to downgrade
for the time being.

**Comment by gregory38** [comment]
Ok sorry. I don't know how we add the new distribution to the dev. You could try to ping the guy that implemented this auto build.

**Comment by tiagoplacido** [comment]
Te dev ppa supports ubuntu 18.10 and 19.04 https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by illQuo** [comment]
Hmm, okay. I'll try again later today and let you know.

**Comment by illQuo** [comment]
@tiagoplacido @gregory38 I added the dev PPA and it's now working. Thanks guys you can close off the issue 👍
