### ISSUE TITLE
Ace Combat 5/Zero: Clouds not rendering correctly in OpenGL hardware mode.

### ISSUE THREAD

**Issue by apemax** [PCSX2/pcsx2#2804]
***PCSX2 version:***
PCSX2 v1.5.0-dev-2867-gc58acd110

***PCSX2 options:***
"Safest", "Safe (faster)" preset tested.

***Plugins used:***
![screenshot from 2019-01-08 17-05-37](https://user-images.githubusercontent.com/2649616/50846700-ac9c6280-1367-11e9-8fc5-97e3ea01e47e.png)
![screenshot from 2019-01-08 17-05-40](https://user-images.githubusercontent.com/2649616/50846701-ad34f900-1367-11e9-817a-e1e10b185509.png)

***Description of the issue:***
The clouds are not rendering correctly in OpenGL Hardware mode, They render fine in software mode. See screenshots:

![gsdx_20190108170245](https://user-images.githubusercontent.com/2649616/50846774-dce40100-1367-11e9-85b5-d4d0a7473737.png)

![gsdx_20190108171149](https://user-images.githubusercontent.com/2649616/50847066-8f1bc880-1368-11e9-94a5-75f4317f4f34.png)

GS Dumps:

[gsdx_20190108170245.zip](https://github.com/PCSX2/pcsx2/files/2737783/gsdx_20190108170245.zip)
[gsdx_20190108171149.zip](https://github.com/PCSX2/pcsx2/files/2737784/gsdx_20190108171149.zip)

***How to reproduce the issue:***
1: Start the game and load into the first mission, Once you get in game you will notice the clouds not rendering correctly.

***Last known version to work:***
Unknown, Looking at the Wiki pages for these games:

https://wiki.pcsx2.net/Ace_Combat_5:_The_Unsung_War

https://wiki.pcsx2.net/Ace_Combat_Zero:_The_Belkan_War

It looks like it might have been introduced after a revision of v1.5.0.

***PC specifications:***
CPU: Intel i5 4670k 3.8GHz
GPU: Zotac GTX 950 AMP! Edition
OS: Arch Linux, Kernel 4.20.0, Nvidia 415.25

**Comment by mirh** [comment]
There is a [problem](1861) with clouds... But nothing like you have. It's all fine here. 

Could you try to "refresh" your inis? I seem to remember some whatever kind of blockiness (while I was testing the [perfect® settings](https://www.reddit.com/r/emulation/comments/56wj30/mipmapping_makes_the_ace_combat_games_run_way/d8osrry/)) with old versions... maybe you have some odd setting sticking.

**Comment by apemax** [comment]
Ok, I deleted my GSdx.ini file and the clouds are not just not rendering in HW Mode now, So looks like this particular issue has been resolved.

Thank you. :)

**Comment by mirh** [comment]
Would have been nice to know the precise setting, but whatevs. userhacks_align_sprite_X maybe

**Comment by apemax** [comment]
Ah, Sorry, Deleted my old GSdx.ini file now. I did reset all the GSdx settings back to the ones in the report but it does not happen any more. I did disable all user hacks before and it didn't change anything.
