### ISSUE TITLE
ELF crc calucate

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#2808]
***Description of the issue:***
``When ELFs launch from directly, GSdx will calculate CRC hashes regardless of anything. 
This would cause problem when making homebrew and used PCSX2 for testing. ``

***How to reproduce the issue:***
``
Run any ELFs.
``

**Comment by knight-ryu12** [comment]
So what I propose, is to either give CRC=0 or disable CRC

**Comment by Souzooka** [comment]
I don't see how this would be a problem unless you're worried about hash collisions, which are unlikely.

**Comment by knight-ryu12** [comment]
It implies CRC hack, (if it matches known game hash.)
so might we wise to set to 0

**Comment by gregory38** [comment]
If you want to test homebrew. You will use sw renderer not hw renderer. Otherwise if you disable crc hack gsdx won't get the crc.

**Comment by knight-ryu12** [comment]
oh I see..., I never thought that way.
