### ISSUE TITLE
[Linux Mint 19 Cinammon] GSdx Settings Dialog UI-Bug

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#2810]
***PCSX2 version:***
dev build 1.5.0, most recent at time from PPA.

***PCSX2 options:***
Default, nothing special set.

***Plugins related:***
libGSdx-SSE4.so [GSdx (GCC 7.3.0 SSE4.1/SSE41) 1.1.0]

***System information***
Linux Mint 19 Cinnamon (64-bit), live OS Boot via USB drive.

***Description of the issue:***
If you switch between HW/SW Renderer or None (Core Benchmark), the options of the other renderers should grey out, but they don't.

***How to reproduce the issue:***
Just install latest dev-build from PPA, start pcsx2 and open GSdx settings, see attached screenshot. For me it's reproducible each time you open the dialog.

![gsdx-settings-mint](https://user-images.githubusercontent.com/30773753/51073263-21bcb000-1666-11e9-82c5-88ccf42f4997.png)

**Comment by lightningterror** [comment]
I don't think anyone actually coded that behavior on linux to work like on windows.

**Comment by gregory38** [comment]
I don't like it. It is annoying to change option

There is an hardware and a software section. People should be smart enough to figure it out.

**Comment by XXXBold** [comment]
> 
> 
> I don't think anyone actually coded that behavior on linux to work like on windows.

Might be true, but other options works without a problem, e.g. if you select/deselect (On the GSdx settings as well) the "Enable User Hacks" Checkbox, the contents of the "Advanced Settings" are shown/greyed properly. I'll have a look into the code, maybe I'll figure it out...

**Comment by lightningterror** [comment]
I prefer if the options grey out, it's less confusing for people, and you shouldn't be able to change settings for a render that isn't select.

**Comment by gregory38** [comment]
Use case you want to use F9 for a scene. Too slow you want to increase thread.

So you need
1/ change renderer because you can't access the option
2/ set the new value
3/ eventually get back to hw renderer

What is confusing about the 2 sections. So far, nobody never reported than an HW (or SW) option doesn't work for the SW (or HW) renderer.

**Comment by gregory38** [comment]
For the hack it is different. Because you need to enable them. And it is confusing.

**Comment by lightningterror** [comment]
Can the tab be hidden when option is off ? That should be better, no ?

**Comment by XXXBold** [comment]
Point is, on Windows, it IS actually working as I described. So I guess there's already some kind of hack somewhere...

**Comment by XXXBold** [comment]
> 
> 
> Can the tab be hidden when option is off ? That should be better, no ?

Yeah, also an idea, but imo it should be consistent to windows as well.

**Comment by gregory38** [comment]
So, Windows isn't the reference. Nothing is shared between the GUI. It is a matter of preference. What is the gain to grey out stuff ? I did 5 year of Linux support, so far nobody mix the option.

What is the point to hide some parts of the GUI ? Biggest issue of users are which hack/blending level to enable.

**Comment by gregory38** [comment]
Well you could make Windows consistent to Linux too ;)

We used to have this code. I deleted it because it was too painful to change renderer to change a renderer option (extra clicks).

You could imagine better stuff to help people. A button to query wiki information. Translation of gsdx tooltip.

**Comment by XXXBold** [comment]
> 
> 
> Well you could make Windows consistent to Linux too ;)
> 
> We used to have this code. I deleted it because it was too painful to change renderer to change a renderer option (extra clicks).
> 
> You could imagine better stuff to help people. A button to query wiki information. Translation of gsdx tooltip.

Alright, I think I could do some translations to German if needed :)

I'll close this one then, maybe I'll check back later. Is there a kind of ToDo List which translations are needed? pcsx2/locales/de_DE/ already looks quite okay (OFC some strings could be improved), could you give me a hint where to start?

**Comment by gregory38** [comment]
Well. Unfortunately it isn't as straightforward as you think. So far plugins aren't translatable.

First step, it to add an infrastructure to be able to do it .
2nd step, upgrade string to wide string
3nd step, do the translation

Translate everything will be painful are GUI are different between Linux and windows. However gsdx tooltips are shared. And it would really help people that don't read English.
