### ISSUE TITLE
Superman: Shadow of Apokolips blue overlayer 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2811]
PCSX2 1.5.0-20190112095928 - compiled on Jan 12 2019

With default speed settings on DX11 superman has blue screen over layer, in software mode it doesn't have this issue, on opengl it is a bit better but still has a screen over layer on the half on the screen 

Dx11

![pcsx2 2019-01-12 16-59-33-571](https://user-images.githubusercontent.com/5770076/51073571-3b70ee00-168c-11e9-8a89-0d9008f4b2cd.jpg)

software mode

![pcsx2 2019-01-12 16-59-38-263](https://user-images.githubusercontent.com/5770076/51073575-462b8300-168c-11e9-80dd-d75286699cd3.jpg)

open gl

![pcsx2 2019-01-12 17-01-50-012](https://user-images.githubusercontent.com/5770076/51073577-4deb2780-168c-11e9-98a5-fd4eeb6dec31.jpg)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2752009/emuLog.txt)

**Comment by lightningterror** [comment]
A gs dump will be helpful here.

**Comment by Levan7** [comment]
Here you go 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/2752020/snaps.zip)

**Comment by lightningterror** [comment]
Darker stage and missing shadow is blending, didn't check the rest.

**Comment by atomic83GitHub** [comment]
Something funny is the size of the blue layer is exactly the same as the "black screen problem" I have with Ratchet EB games demo.

![image](https://user-images.githubusercontent.com/26351275/56079992-d7c99e80-5dfb-11e9-9e74-577f5d0a70f7.png)

**Comment by prafullpcsx2** [comment]
It's half screen problem already listed here

https://github.com/pcsx2/pcsx2/issues/1339

So the size of blue/black layers will be same in many of these games.

**Comment by lightningterror** [comment]
dx should be pretty close now with depth, hdr colclip, fbmask to opengl. It may still need sw blending for some extra minor correction.

Only major issue that remains is the half screen, closing in favor of meta issue.
