### ISSUE TITLE
Armored Core Last Raven goes to half speed in menu after missions and AC Test

### ISSUE THREAD

**Issue by disastranagant** [PCSX2/pcsx2#2813]
***PCSX2 version:***
Several 1.5 builds tested, going back to at least 640, with https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-2867-gc58acd110&platform=windows-x86 being the latest tested

***PCSX2 options:***
All settings default except for the required Preload Frame Data hack selected in GSDX

***Description of the issue:***
The menus drop to 30 fps when returning from any battle screen.  Sometimes it reverts to full speed after a while or after closing the GS window and resuming.

***How to reproduce the issue:***
Start a new game.  Go to garage > VR AC Test and choose any option.   After the battle loads hit start and end the mission.  Enjoy your new 30-32 FPS.  Close GS window and resume to maybe go back to 60+.

***Last known version to work:***
Not sure.  I didn't have this issue when I played a couple years ago but I have no idea version that was on.

***PC specifications:***
CPU: Intel I5-4570, 8 GB DDR3 RAM, GPU: Geforce GTX760, Windows 8.1 64bit

GS Dump: https://mega.nz/#!tBkFUQpa!aaWwwfnUiWi3Mv9BhL4UKYdkaKaC3CanLJ2lm87UNB4

**Comment by MrCK1** [comment]
Was this testing done at native resolution ect? Can you post the entire GSdx settings dialog?

**Comment by disastranagant** [comment]
Yes, the most recent version used was a fresh install with just that one hardware hack enabled that is required to not black screen the game.

![image](https://user-images.githubusercontent.com/3312331/51450301-d48bae80-1cf5-11e9-8d78-afa7598adea2.png)
![image](https://user-images.githubusercontent.com/3312331/51450310-e4a38e00-1cf5-11e9-966c-a2d405e1fa3e.png)

**Comment by lightningterror** [comment]
Large Framebuffer should be disabled when upscaling for this game else the vram spikes will be insanely high.

**Comment by Helium-4** [comment]
I did test with it off.

**Comment by MrCK1** [comment]
@Helium-4 @disastranagant Can you test with a GSdx plugin from #2843 and report whether or not VRAM spikes/performance issues still occur? Thanks.

**Comment by disastranagant** [comment]
I've never built gsdx before but I'll give it a go.

**Comment by lightningterror** [comment]
No need to build it, you can download one of the appveyor artifacts
https://ci.appveyor.com/project/gregory38/pcsx2/builds/22925469/job/98ffue3auqrfcom7/artifacts

Make sure you force enable sparse texture advanced options & hacks.

**Comment by disastranagant** [comment]
I can't even get in-game with that build

**Comment by disastranagant** [comment]
caught an out of vram error in the log this time, so sparse texture appears to make it worse.

**Comment by Helium-4** [comment]
Forcing Sparse Texture on makes the spikes worse (OGL @ native res uses just about 4GB with it force enabled instead of 3.5GB with it force disabled) and makes the emulator crash in case you hit the VRAM limit of your card instead of just noticeably chugging and reducing performance until reset.

**Comment by gregory38** [comment]
Is it a VRAM or a RAM or both spike ?
Could you test again the sparse PR ? Old code was wrong and texture wasn't freed correctly ?

**Comment by Helium-4** [comment]
I'm unsure which build from this PR is supposed to be the most recent if it's not the one I already tested it with.
I've tested with 
https://ci.appveyor.com/project/gregory38/pcsx2/builds/22925469/job/2nejvrr63s6gddks/artifacts

The spike only affects VRAM.

**Comment by lightningterror** [comment]
> I've tested with
> https://ci.appveyor.com/project/gregory38/pcsx2/builds/22925469/job/2nejvrr63s6gddks/artifacts

Yes that's the correct build.

**Comment by MrCK1** [comment]
Is someone able to retest this on master and confirm if it is still an issue or not? Thanks.

**Comment by Helium-4** [comment]
VRAM still spikes heavily even at native resolution , performance doesn't seem affected afterwards but it might simply  be because I have a much better GPU now than back then.

**Comment by disastranagant** [comment]
Same story.  I'm now on a 1650 super and can see it spike about +2700mb used for a couple seconds at boot and when loading any mission or ac test before tapering off to +450mb over about 20 seconds.

**Comment by lightningterror** [comment]
What if you run the game with Sparse Texture force enabled?

**Comment by disastranagant** [comment]
That's the first paragraph there.  Second paragraph is with it force disabled.

**Comment by JordanTheToaster** [comment]
Not an issue as of v1.7.3096.
