### ISSUE TITLE
The light from the flashlight penetrates through the textures. Silent Hill 2 (SLUS 20228 GH and SLES 51156 DC).

### ISSUE THREAD

**Issue by Valeriy32** [PCSX2/pcsx2#2817]
***PCSX2 version:***
1.5.0 (presumably all revisions) and 1.4.0.

***PCSX2 options:***
The problem presumably persists at any settings of OGL (Hardware) and D3D 11 (Hardware) plugins and any emulation settings. But it disappears when switching to software mode.

***Plugins used:***
 
![1](https://user-images.githubusercontent.com/46814979/51388324-1a037c80-1b3a-11e9-8c30-9e4d5cf8685e.PNG)

***Description of the issue:***
Light penetrates the textures.
OGL plugin:
![gsdx_20190118152937](https://user-images.githubusercontent.com/46814979/51388050-5b475c80-1b39-11e9-8cd9-92d995f88791.png)
![gsdx_20190118153806](https://user-images.githubusercontent.com/46814979/51388053-60a4a700-1b39-11e9-94c6-6bc2c3d55d9a.png)
![gsdx_20190118154112](https://user-images.githubusercontent.com/46814979/51388063-6601f180-1b39-11e9-80c3-550361c09488.png)

**Some** parts of locations are not affected (if use OGL plugin):

![gsdx_20190118154734](https://user-images.githubusercontent.com/46814979/51388462-88483f00-1b3a-11e9-8c0a-ee12acb8352c.png)

But it remains, if you use the D3D 11:
![gsdx_20190118163905](https://user-images.githubusercontent.com/46814979/51390471-6ea9f600-1b40-11e9-9c1b-4d0a3d8112eb.png)

***How to reproduce the issue:***

Use save point ( "hospital office" for example).
[memcards.zip](https://github.com/PCSX2/pcsx2/files/2773194/memcards.zip)

***PC specifications:***
CPU: Intel  i7-2600K  GPU: ASUS GTX 580 OS: Windows 7 64 Bit

**Comment by MrCK1** [comment]
Did you try turning up blending accuracy to Ultra to rule that out?

**Comment by Valeriy32** [comment]
> 
> 
> Did you try turning up blending accuracy to Ultra to rule that out?

Yes. This improved the fonts, but nothing else has changed.

**Comment by tadanokojin** [comment]
Try autoflush. If that does work then shoot me a gs dump.
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by levonnn** [comment]
Tried it in dev-3391. Various settings in gsdx and emulation.

In OGL HW the problem is still there:

![](https://i.imgur.com/A4uExKF.png)

In SW mode the light doesn't penetrate objects, but at certain angles (when light hits edge of an object) I see this (this problem is also in Silent Hill 3):

![](https://i.imgur.com/jIBt6b5.png)

snap:
http://s000.tinyupload.com/?file_id=02977730508901860635

**Comment by refractionpcsx2** [comment]
Can we get a new GS Dump please

**Comment by refractionpcsx2** [comment]
Could somebody try this on #7267

**Comment by shinra-electric** [comment]
Doesn't seem to fix it (unless some setting needs to be applied). 

PCSX2-v1.7.3501: 

<img width="1380" alt="Screenshot 2022-10-31 at 14 00 20" src="https://user-images.githubusercontent.com/50119606/199013982-103d4ba8-955d-48cf-a634-3e04da69cf64.png">

**Comment by refractionpcsx2** [comment]
yeah it's unrelated, unfortunately :(

**Comment by dietofworms** [comment]
![image](https://user-images.githubusercontent.com/28944297/199657452-022daddd-a372-44b5-8721-c47d24c852d5.png)

Same issue as @shinra-electric.

I'm on Windows and version 1.6.0.

**Comment by RedDevilus** [comment]
Try using the latest 1.7 development / nightly builds for improvements (besides this issue).

**Comment by refractionpcsx2** [comment]
I doubt this has changed.

**Comment by shinra-electric** [comment]
I just tested this again with 1.7.4515 and it appears to be fixed. 
Flashlight is properly occluded by Maria. 

<img width="1162" alt="Screenshot 2023-05-16 at 16 16 55" src="https://github.com/PCSX2/pcsx2/assets/50119606/78150974-1ab6-43fc-9450-0891e833b5b8">

**Comment by refractionpcsx2** [comment]
Excellent! Thanks for letting us know :)
