### ISSUE TITLE
Timesplitter future perfect - framerate problems

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2819]
PCSX2 1.5.0-20190118155654 - compiled on Jan 18 2019

This game has a very strange problem when it is running default speed 100% the game lags but if i enable turbo mode it is very fast.

every settings is default except resolution 2x

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2773517/emuLog.txt)

Update
If the MTVU isn't enable it runs properly

**Comment by willkuer** [comment]
So this can be closed as this game apparently one of those having troubles with MTVU?

**Comment by Levan7** [comment]
@willkuer  sure looks like it

**Comment by MrCK1** [comment]
Yes this game isn't compatible with MTVU.
