### ISSUE TITLE
Metal Gear Solid 3 Subsistence (NTSC): Very noticeable input lag

### ISSUE THREAD

**Issue by Arthandas** [PCSX2/pcsx2#2822]
***PCSX2 version:***
Development build v1.5.0-2890

***PCSX2 options:***
Everything at default (safe-faster preset).

***Plugins used:***
Everything at default. All four renderers tested.

***Description of the issue:***
There's around 500ms of input lag, hard to say exactly how much but it's very noticeable. No other games I own are affected (including Metal Gear and Metal Gear 2 on the MGS3 disc). I did a test using the padtest file posted here:
https://forums.pcsx2.net/Thread-Input-lag-in-PCSX2?pid=588704#pid588704
and there's no lag in the test itself.

I tried some common workarounds like completely disabling vsync and framelimiter and capping the framerate with RTSS but no change.

***Last known version to work:***
I tried it across many different revisions of pcsx2 since I got the game two years ago but the lag was present in all of them, I finally decided to submit it as an issue since I got no response on the forums.

***PC specifications:***
i3-6100
GTX 1060 6gb
8gb DDR4
Windows 10 Pro 64 bit

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by Dogway** [comment]
Could we extend this issue to the emulator itself? I measured 6 frames (with frame advance) of game input lag in Sengoku Basara X which matches that of the OP in the forum linked. An improvement of 2 frames would be realistic and akin to other modern emulators like Dolphin or Citra with 4 frames of game input lag each.

**Comment by Arthandas** [comment]
No because the input lag is not global, it's only in MGS3 and not in MG or MG2 which are on the same disc. Also it has way more lag that 6 frames, feels like half a second or more.

**Comment by Dogway** [comment]
Ok, I will test MGS3 and other games and make new global issue ticket for input lag.

**Comment by lightningterror** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/3008
