### ISSUE TITLE
Ace Combat 04 - merge sprite causes post-effects to misalign

### ISSUE THREAD

**Issue by m4ti140** [PCSX2/pcsx2#2834]
***PCSX2 version:***
v1.5.0-dev-2928-g1ae48db87-windows-x86

***PCSX2 options:***
speedhacks to safe +MTVU
widescreen hacks to on
cheats on - using no interlacing cheatcodes

***Plugins used:***
default
GSDX settings:
Renderer - d3d11 HW
interlacing: none - using no interlacing cheatcodes
filtering - bilinear(forced excluding sprite)
resolution - 2xnative
AF - 16x
mipmaping - basic
align sprite and merge sprite on
half-pixel offset - special (texture - aggressive)
sprite - full
round sprite -half

***Description of the issue:***
When merge sprite hack is turned on (which is necessary to get rid of vertical lines in this game) - the post-processing effects are misaligned - offset upwards. The misalignment reacts to TC offset hack but would require negative values to fix

***How to reproduce the issue:***
Run AC04
wait for the demo movie/start the campaign with default aircraft/a night mission
disable merge sprite - weird vertical lines are observable
enable merge sprite - lines disappear, but the post processing effects are now offset upwards

***Last known version to work:***
none

***PC specifications:***
MSI GE62 6QC: i7-6700HQ @3.1 GHz, GTX960M 2GB, 16GB RAM

**Comment by lightningterror** [comment]
This isn't really an issue, you'll often find out that upscaling hacks may not work properly or cause different issues altogether.

**Comment by mirh** [comment]
What he said ^

But anyway.. couldn't you try at least to experiment a bit more? 
E.g. this is what I could come up 2 years ago with AC5
```
accurate_blending_unit=3              // fixes some cloud/smoke effect
mipmap=1
UserHacks=1
UserHacks_mipmap=1                    // 1 should be enough. Reports it wasn't?
Userhacks_align_sprite_X=1            // fix vertical black lines, both in menus and in-game
UserHacks_merge_pp_sprite=1           // fixes cut pixel columns from above fix (also vertical black lines, but in-game only)
UserHacks_unscale_point_line=1        // unthin text/menus lines
#UserHacks_SpriteHack=2               // fixes "explosions particles bubbles" (no more needed with sprite_X=0?) --- Actually fixed with other sprite hack. Now this.. why?
UserHacks_AutoFlush=1                 // fixes explosions halo blockiness
UserHacks_round_sprite_offset=1       // 1-fixes HUD white rows 2-would improve a little glitches around plane HUD icon (on higher resolutions) but it fucks up explosions
UserHacks_HalfPixelOffset=3           // 1,3 f
```

**Comment by mirh** [comment]
Ie. report back if tinkering isn't enough. 
Upscaling isn't necessarily always doable, but we try what we can.

**Comment by m4ti140** [comment]
Bumping this, cause I went AWOL for a few years (interesting few years those were, weren't they)

> What he said ^
> 
> But anyway.. couldn't you try at least to experiment a bit more? E.g. this is what I could come up _2 years ago_ with AC5
> 
> ```
> accurate_blending_unit=3              // fixes some cloud/smoke effect
> mipmap=1
> UserHacks=1
> UserHacks_mipmap=1                    // 1 should be enough. Reports it wasn't?
> Userhacks_align_sprite_X=1            // fix vertical black lines, both in menus and in-game
> UserHacks_merge_pp_sprite=1           // fixes cut pixel columns from above fix (also vertical black lines, but in-game only)
> UserHacks_unscale_point_line=1        // unthin text/menus lines
> #UserHacks_SpriteHack=2               // fixes "explosions particles bubbles" (no more needed with sprite_X=0?) --- Actually fixed with other sprite hack. Now this.. why?
> UserHacks_AutoFlush=1                 // fixes explosions halo blockiness
> UserHacks_round_sprite_offset=1       // 1-fixes HUD white rows 2-would improve a little glitches around plane HUD icon (on higher resolutions) but it fucks up explosions
> UserHacks_HalfPixelOffset=3           // 1,3 fixes blurry objects outlines (3 doesn't introduce UI and text misalignments though)
> ```

Tried all of this, nothing seems to help. Half pixel offset to normal(vertex), Round sprite to half and align sprite on are all needed to have the post effects render correctly even without merge sprite, but at the end of day it's either black lines without merge sprite or completely messed up image with it. And no. negative texture offset wouldn't help either. What seems to be happening is that merged post effect frame is stretched. And it's multiple passes, with each subsequent one messed up even more.

Worth noting that hw emulation with Vulkan at native resolution is now perfect. The only lingering issues with this game are with upscaling. Also it's only an issue in in-engine cutscenes - it seems it's specifically depth of field that is messed up like that. I wonder if there is any way to dynamically return to native resolution during cutscenes.

**Comment by mirh** [comment]
Yes, I did eventually figured that was mot. 
I also tried the experimental pre-round sprite hack, to no avail. 
If the project is now accepting upscaling bugs, this could be reopened I guess (even though perhaps, who knows.. maybe it will be sufficient to fix one of [these others](https://github.com/PCSX2/pcsx2/labels/GS%3A%20Upscaling)).
