### ISSUE TITLE
Debugger does not recognize function ends of noreturn functions

### ISSUE THREAD

**Issue by Souzooka** [PCSX2/pcsx2#2836]
***PCSX2 version:***
v1.5.0-dev-2843

- **Issue**:
The debugger cannot recognize the end of noreturn functions and will group said function and the next function into one function label.

Here's an example of a function whose end is not properly recognized:
```mips

MainLoop:
  addiu $sp, -0x10
  sd $ra, 0($sp)
  jal GetThreadId
  nop
  move $a0, $v0
  jal ChangeThreadPriority
  li $a1, 10
.gameloop:
  

  ; some sort of bigly game logic

  b .gameloop
  nop
```

![](https://i.imgur.com/Mh5rpAF.png)

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by Mrlinkwii** [comment]
is this still an issue on latest nightly ? :)

**Comment by Mrlinkwii** [comment]
ive been told this is still an issue
