### ISSUE TITLE
SOCOM: Combined Assault - graphic issues

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2838]
PCSX2 1.5.0-20190202175038 - compiled on Feb  2 2019

Well this game has a lot of graphical issues on default settings (software mode doesn't helps it)
If i select clamping mode to none the lines almost don't appear but the characters still disappear.

![1](https://user-images.githubusercontent.com/5770076/52170630-44268280-2767-11e9-8922-9238c2076ad6.gif)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2825010/emuLog.txt)

[snaps_2.zip](https://github.com/PCSX2/pcsx2/files/2825011/snaps_2.zip)

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by prafullpcsx2** [comment]
It requires VU round mode nearest and VU clamping extra.

**Comment by lightningterror** [comment]
Fixed in #3402
