### ISSUE TITLE
Core Dump trying to boot any ISO

### ISSUE THREAD

**Issue by ask-compu** [PCSX2/pcsx2#2839]
***PCSX2 version:***
1.5.0

***PCSX2 options:***
Default "safe" preset

***Plugins used:***
Default Linux plugins

***Description of the issue:***
Booting with no disc boots the BIOS without issues
[Screenshot](https://i.imgur.com/1PHf26M.png)
Trying to boot ANY ISO file gives a core dump
[Screenshot](https://i.imgur.com/4W8LsIo.png)
The ISOs aren't the issue as I tested them on Windows 10 and they run on there

***How to reproduce the issue:***
Install PCSX2 unstable (1.5.0) from the ppa in Ubuntu 14.04
Try to boot any ISO file

***PC specifications:***
CPU: Intel Core i3 4170
GPU: Zotac Geforce 1050 mini 2 GB
OS: Ubuntu 14.04.5 LTS

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by Mrlinkwii** [comment]
are you still having this issue ?

**Comment by RedDevilus** [comment]
Outdated PCSX2 but doesn't specify which dev build (1.5)+ Outdated Ubuntu version (14.04).
