### ISSUE TITLE
Add Controller Ports #3 and #4

### ISSUE THREAD

**Issue by niko1point0** [PCSX2/pcsx2#2841]
This is going to sound weird, but stay with me for a second.
Normally PlayStation 2 has controller ports #1 and #2, then it has slots 1-4 for a multitap.
I would like you to put in ports #3 and #4, even though they didn't exist on the console.

The reason why, is because many games like Spy Vs Spy were programmed to support 4 controllers on Xbox or Gamecube, but only support 2-player mode on PS2 because the developers never implemented multitap support.

I know this sounds stupid, but I actually hacked the Spy Vs Spy game to fully support 4-player mode on the PCSX2 emulator. The only flaw is that all 4 players have to be controlled by controller port #1 or #2. 100% of all player 3 and 4's features fully work.

I think that more games, such as Crash Tag Team Racing, could become playable if this type of hack were included. I've been editing the source code of LilyPad to try to enable a 3rd and 4th "Port", but I have not had any luck. Could this be a feature in PCSX2?

I am willing to donate money

**Comment by niko1point0** [comment]
![capture](https://user-images.githubusercontent.com/7824443/52247979-287fc100-28ba-11e9-9871-b509a73f3f1b.PNG)

These Addresses can be put into Cheat Engine to enable the 3rd and 4th player, by setting NUM_SCREENS and NUM_PLAYERS to 4, and by setting P1 Port, P2 Port, P3 Port, and P4 Port to either 0 or 1, for controller port 1 or 2. If you try to set it to 2 or 3, it will say "Controller Port 3 (or 4) is unplugged", rather than just crashing, which is why I feel this might be possible

**Comment by niko1point0** [comment]
@MrCK1 Does that make sense?

**Comment by MrCK1** [comment]
I guess so. I haven't looked into the hardware too much.

**Comment by MrCK1** [comment]
Do any multitap games work with the current implementation?

**Comment by PSI-Rockin** [comment]
The code responsible for managing controllers (written by Sony) only knows of two ports, so the game would need to be reprogrammed to take advantage of four ports.

**Comment by niko1point0** [comment]
That’s just the thing, the game was programmed to take advantage of 4 ports. I just changed Player 3 and 4 to look at Controller Port 1 instead of 3 and 4. However, it is definitely programmed in the game to use Port 3 and 4, even though they don’t exist. 

Please believe me, it was first programmed for Xbox, and ported to PS2 later, I saw chunks of the code in Cheat Engine, it is definitely looking for ports 3A and 4A @PSI-Rockin

**Comment by niko1point0** [comment]
There's more, if I don't change Player 3 and Player 4 to look at Controller Port 1, it says it is looking for Controller Port 3 and 4, they are not looking for 1C and 1D. I will have a screenshot in a minute

**Comment by PSI-Rockin** [comment]
The game itself is looking for those ports, but the code that actually manages those ports (which was not programmed by the developers, but by Sony) can only use two. It would have to be completely rewritten as it (rightfully) makes the assumption that only two ports exist.

**Comment by niko1point0** [comment]
The first two screens are controlled by ports 1 and 2, not 1A and 1B. If I unplug the controllers ports 1A and 2A, the same error screen comes up on the top two screens. Therefore, I believe that if there are controller ports for 1A, 2A, 3A, and 4A, then the game will be playable @PSI-Rockin @MrCK1

**Comment by niko1point0** [comment]
Ok, I understand now. Thank you
