### ISSUE TITLE
PCSX2 closes with OpenGL hardware renderer.

### ISSUE THREAD

**Issue by Real-Gecko** [PCSX2/pcsx2#2848]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2955-gca002c56e-windows-x86

***PCSX2 options:***
Everything by default

***Plugins used:***
All default, no settings were changed during setup

<img width="564" alt="2" src="https://user-images.githubusercontent.com/2231969/52577642-bfb1bf00-2e4c-11e9-8cac-9e7700b1b68b.png">
<img width="275" alt="1" src="https://user-images.githubusercontent.com/2231969/52577576-9b55e280-2e4c-11e9-82fb-2aa9675de03d.png">

***Description of the issue:***
Emulator simply closes without any notifications or errors. No error messages in logs too.

***How to reproduce the issue:***
- Download latest PSCX2 build
- Unpack
- Start emulator and ensure that OpenGL Hardware mode enabled in settings
- Run game
- After some time emulator closes
- Time may vary from 2 to 30 seconds
- Games tested with Ace Combat (04, 05, 00)

***Last known version to work:***
I tried different versions ranging from ``pcsx2-v1.5.0-dev-2243-g74282b46f-windows-x86`` up to 2955 with the same result. So I assume problem is somewhere in my system. However I'm not sure what's wrong as Direct3D 11 renderer works, as well any variation of software renderer.

***PC specifications:***
- CPU: Intel Core i7 7700HQ
- GPU: Nvidia GTX 1070
- OS: Windows 10 64 Bit, version 1809
- log here [emuLog.txt](https://github.com/PCSX2/pcsx2/files/2852047/emuLog.txt)

**Comment by lightningterror** [comment]
Maybe an antivirus issue ?

**Comment by Real-Gecko** [comment]
Windows defender only.

**Comment by lightningterror** [comment]
Maybe pause it and see if it changes anything, also worth trying are older/newer drivers.
Does the issue happen on 1.4 as well ?

**Comment by Real-Gecko** [comment]
Hmmm, things are even funnier now. I tried version 1.4 of PCSX2 with default GS plugin and everything worked fine. At least I was able to complete mission one
 of AC04. But then I created a weird mix of 1.4 PCSX2 and latest GS plugin in OpenGL HW mode and it worked too.
<img width="564" alt="3" src="https://user-images.githubusercontent.com/2231969/52588294-4fb03280-2e66-11e9-8b3f-f6d54683f7e4.png">

**Comment by willkuer** [comment]
Emulog.txt after it closes?

**Comment by Real-Gecko** [comment]
Last line of the OP.

**Comment by willkuer** [comment]
Sry, somehow missed it. Interesting last line but but not really telling where it originates from.

**Comment by Real-Gecko** [comment]
I'll try, but it'll take some time. Here are all versions I tested before:
![2](https://user-images.githubusercontent.com/2231969/52653670-a5461700-2f1a-11e9-9aa1-5828c8d11b38.png)

**Comment by Real-Gecko** [comment]
OK, it did not take much time :D
I simply got earliest available build from [here](https://buildbot.orphis.net/pcsx2/index.php?m=fulllist), which is **v1.5.0-dev-1960-ga18d624bc**. And result is the same. Looks like log file does not contain any valuable info, however I'll upload it:
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2856828/emuLog.txt)
PCSX2 1.4 works well with every version of GS plugin I throw at it in OpenGL HW.

**Comment by lightningterror** [comment]
Here is a list of older 1.5 versions that you can download.
[1.5.0.txt](https://github.com/PCSX2/pcsx2/files/2856913/1.5.0.txt)

**Comment by willkuer** [comment]
You triggered the same strange log message in the second emulog.

**Comment by willkuer** [comment]
Can you maybe try to set your language back to english to ensure that this is not just some encoding foo?

**Comment by Real-Gecko** [comment]
So, things are getting weirder now, yesterday build 2955 closed after playing a couple of minutes with Direct3D11 renderer, that never happened before. Is there a way to enable more verbose logging? Maybe something like debug mode?

**Comment by RedPanda4552** [comment]
One thing to check would be RAM and VRAM usage while PCSX2 is up. I had a fun time the other day, due to a separate issue, where PCSX2 and any other 3D application really, was running out of memory for seemingly no reason and just hard stopping. Might be something to just keep an eye on as you poke around.

**Comment by lightningterror** [comment]
So what is the current status ?

**Comment by Real-Gecko** [comment]
I compiled PCSX2 from sources and debug build crashes too. Trying to localize problem now, however I'm currently short on time, so no good progress so far...

**Comment by atomic83GitHub** [comment]
Something to note is this happen in Jak but not instantly, and sometimes PCSX2 just hang and must be forced-close. It's OpenGL only.

**Comment by lightningterror** [comment]
Any update on this?

**Comment by atomic83GitHub** [comment]
Well that's related to this https://github.com/PCSX2/pcsx2/issues/2916 ,you can close this issue.

**Comment by lightningterror** [comment]
Alright will close this one then.
