### ISSUE TITLE
[Feature request] option to mute audio after input is idle

### ISSUE THREAD

**Issue by dgendreau** [PCSX2/pcsx2#2849]
We want to install PCSX2 on an emulator machine in our break room, but we would prefer to have the audio muted when its been idle for a few minutes.

I am an experienced C++ dev, but I'm not up to speed on your code yet.

Could someone recommend how best I should:
1) Add a new command line argument. (I'm assuming this feature is not desired in the settings screen.)
2) Detect when any controller button / stick input changes occur and record the current time
3) mute/unmute the audio.
4) An appropriate place in the code to test every few seconds to mute / unmute the audio when necessary.

Thanks for any suggestions.

**Comment by tadanokojin** [comment]
The problem you are likely to run into is that PCSX2 uses a plugin system. Which means the plugin that handles input and the plugin that handles sound are two different DDLs with two separate codebases.

**Comment by willkuer** [comment]
One could mute the system’s sounds. Not only sounds by pcsx2. That could be handled internally in lilypad but could be rather annoying if you plan to switch from pcsx2 to another program.

In that case I have the feeling this could be handled externally by a tool that de-/activates on in-/activity similar to a screen saver. That would work for all programs (at least in case the gaming screen is not the second screen and you plan to work on the other one).

**Comment by dgendreau** [comment]
willkuer wrote:
> In that case I have the feeling this could be handled externally by a tool that de-/activates on in-/activity similar to a screen saver. That would work for all programs (at least in case the gaming screen is not the second screen and you plan to work on the other one).

I think you may be right. A separate system level app may be the best way to solve the issue overall.
Thanks for the suggestion!

**Comment by gregory38** [comment]
Menu > pause emulation ;) As bonus it will stop your PC fan to spin and will save some power :) What is the gain of this new feature ?

IMHO, it can be detected at core level as all inputs are sent to core to enjoy the game. Then you can send a mute/unmute event to sound plugin.

**Comment by dgendreau** [comment]
> Menu > pause emulation
The use case is a company break room where some users might enjoy playing the occasional game but others are not interested and just want to eat in peace and not be distracted with background music for the majority of the time when nobody is actually playing a game.

However, as @willkuer pointed out, it is actually much simpler to solve this use case by writing a separate system tray icon app that monitors keyboard / mouse / controller input, mutes the system volume after a few minutes of inactivity and restores it when activity is detected. That way it works across all emulators, not just PCSX2.

I can post a github link to the app once its done, but if you think this is getting off topic, feel free to close this issue.

**Comment by 6thsurvivor** [comment]
wouldn't overly long cutscenes be an issue here?

**Comment by lightningterror** [comment]
> wouldn't overly long cutscenes be an issue here?

Maybe not if you set it to mute after 15 minutes, maybe 30 ?

**Comment by pixelherodev** [comment]
Doesn't PCSX2 have a method of detecting FMVs? For those, at least, it should be able to
pause the timer until the FMV is complete, right?

**Comment by willkuer** [comment]
> feel free to close this issue.

**Comment by lightningterror** [comment]
Will close this since it is really one of the lowest priorities to do.
