### ISSUE TITLE
Tales of Destiny problems

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2851]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2928-g1ae48db87-windows-x86

***PCSX2 options:***
default settings

***Plugins used:***
GSDX  :  dx11 hw default settings
other plugin default settings

***Description of the issue:***

1.  no difference of texture filterings (Bilinear - PS2 and Bilinear - forced excluding sprite)
    
     'Bilinear - forced excluding sprite' enable interpolation except for sprites.

      But this bilinear filtering functions including sprites in Tales of Destiny.

      Bilinear - PS2
![gsdx_20190213131644](https://user-images.githubusercontent.com/35862336/52687518-ac5e3b00-2f95-11e9-94eb-e29952e095e1.png)

      Bilinear - forced excluding sprite
![gsdx_20190213131701](https://user-images.githubusercontent.com/35862336/52687527-bd0eb100-2f95-11e9-8fd0-b4fe929341c3.png)

This character must be sprite.  But the sprite character filtered by bilnear.

2.  GSdx HW renderer and vertical blue line

     When it is set HW renderer,  I can see vertical blue lines.
  
      SW renderer does not make blue lines.

     But if I use bilinear filtering  the lines vanish.

      HW renderer - nearest filtering
![gsdx_20190213131420](https://user-images.githubusercontent.com/35862336/52688014-af5a2b00-2f97-11e9-80f9-54958e514bb8.png)

      HW renderer - bilinear filtering
![gsdx_20190213131437](https://user-images.githubusercontent.com/35862336/52688025-bf720a80-2f97-11e9-8cd8-ffb24e789dc7.png)

 pcsx2's savestate (for checking)
[SLPS-25842 (8409FD51).00.zip](https://github.com/PCSX2/pcsx2/files/2858861/SLPS-25842.8409FD51.00.zip)

Dump File
[Dump.zip](https://github.com/PCSX2/pcsx2/files/2858868/Dump.zip)

***PC specifications:***
CPU: Intel Haswell 4690
GPU: amd r9 280
OS: Windows 7 64 Bit

**Comment by MrCK1** [comment]
All 4 of the texture filtering modes function slightly differently, there is no guarantee that all of them will work without causing glitches. Just use the one that works for this specific game and ignore the rest of the modes.

**Comment by gregory38** [comment]
For the GS, a sprite is a 2D flat element. And it mustn't renderer as 2 triangles.
