### ISSUE TITLE
Soul Calibur 2 (JP) intro underline

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2852]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2928-g1ae48db87-windows-x86

***PCSX2 options:***
default settings

***Plugins used:***
GSdx : DX11 HW default setting + align sprite hack + IR x5
other plugins : default settings

***Description of the issue:***
When it is used upscaling  it can see underline in intro fmv.

IR x5
![gsdx_20190212235240](https://user-images.githubusercontent.com/35862336/52689100-580a8980-2f9c-11e9-8db3-750b3fbbc3a9.png)

IR native (PS2)
![gsdx_20190213143248](https://user-images.githubusercontent.com/35862336/52689127-73759480-2f9c-11e9-861e-c8ba14ef162d.png)

Dump File
[Dump'.zip](https://github.com/PCSX2/pcsx2/files/2858928/Dump.zip)

***PC specifications:***
CPU: Intel haswell 4690
GPU: amd r9 280
OS: Windows 7 64 Bit

**Comment by lightningterror** [comment]
It's an upscaling issue, you can use fmv switch to sw mode when a fmv plays.

**Comment by mirh** [comment]
Could you really call it upscaling "issue", if for as much as we know that burnt line may have been there from the beginning?
