### ISSUE TITLE
[Request] Another filters in texture filtering

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2854]
Hello.

Bicubic filter or lanczos filter seems look like similar filter line with bilinear filter. 

Can it implement two filters (lanczos and bicubic) in texture filtering ? 

Thanks.

**Comment by mirh** [comment]
#800 (depending on how much heavy each really is)?

**Comment by lightningterror** [comment]
Don't we already support these ?
https://github.com/PCSX2/pcsx2/pull/739

**Comment by gregory38** [comment]
Issues with complex texture filtering are
* You will get bad interpolation on mega-texture. Big source of upscaling issue
* You need ton of extra memory access. Bilinear is 1 read.  Advanced is 10+ read...

**Comment by mondaychicken** [comment]
@lightningterror 
I know that. But my request is the filters in gsdx texture filtering, not post process.

@gregory38 
Maybe, you are right. 
Playstation2 emulation seems complex than other emulator like ppsspp or dolphin or mame.
But bilinear filtering makes a lot 'blur'.
So it needs like a deblur filter for image quality.

If adding other filters has many issues,
how about implementing multi shaders and rgssaa shader ?
#2595

**Comment by mirh** [comment]
Are you sure filtering is what makes your image blurry and not something else?
Say, interlacing, or upscaling?
For instance, I only figured out after hours and hours of play that AC5 wasn't supposed to look shit blurry like you were drunk (but instead, 3x resolution required half pixel aggressive offset)

**Comment by mondaychicken** [comment]
@mirh 
Thanks, for replying.

Like your opinion, the image quality is not bad in 3d games, ace combat, soul calibur, etc.

But it makes problems in 2d games.

ex)
Tales of Destiny screenshot
Gsdx 
dx11 native x5 bilinear(ps2)
display size
1920x1080

If you don't know well  click images.
![gsdx_20190222155852](https://user-images.githubusercontent.com/35862336/53225954-07421180-36bd-11e9-812a-3ea444e29753.png)

![gsdx_20190222155637](https://user-images.githubusercontent.com/35862336/53225968-11641000-36bd-11e9-877a-fa66db2c118e.png)

P.S
@mirh 
Do you know about shaders ?
I found a good shader for antialiasing from ishiiruka dolphin.
It's a rgssaa(rotate grid ssaa) shader.
Can you port this shader to pcsx2 .
Reference
#2595

**Comment by willkuer** [comment]
There is asmodeans shader suite. Have you checked that out?

**Comment by mirh** [comment]
Ehrm.. I see very bad blurring even on edges of the second image to be honest. 
That would seem like the problem I was talking about. 

And, putting aside SSAA "effects" are already a subset of what increasing resolution does, why couldn't you just force whatever specific variant of it from the gpu control panel?

**Comment by mondaychicken** [comment]
@willkuer 
Yes, checked out.
Asmodeans shader has bicubic and lanzcos scaling filter.
But the two filters are a bit heavy than rgssaa shader.
I saw the difference on dolphin.

@mirh 
It's really blur on 2d games.
So pcsx2 need another filters or deblur funtion.

And, about SSAA effects your thinking is right.
Though, increasing resolution is best way for image quality
it is not enough.
So, it need additional correction like ssaa, msaa, fxaa, rgssaa shader, etc.

About using gpu control panel
It can not force by gpu control panel to pcsx2.
It is impossible all of two vendor nvidia and amd.
Only one way is using built-in msaa.
But latest pcsx2 dropped msaa for a variety issues.

**Comment by mondaychicken** [comment]
On dolphin 
Resident evil 4
1. normal increasing resolution  (like pcsx2) 
![rb4j08-3](https://user-images.githubusercontent.com/35862336/53282481-90b81900-377b-11e9-9cc2-a48a05c5afff.png)

2. normal increasing resolution + bicubic filter (asmodean's dolphinfx)
![rb4j08-5](https://user-images.githubusercontent.com/35862336/53282495-bb09d680-377b-11e9-820f-962d31fabcde.png)

3. normal increasing resolution + rgssaa shader
![rb4j08-7](https://user-images.githubusercontent.com/35862336/53282509-d4128780-377b-11e9-8d22-4027e8a6bd5e.png)

4. normal increasing resolution + ssaa x4
![rb4j08-9](https://user-images.githubusercontent.com/35862336/53282515-e096e000-377b-11e9-9fd7-c631482475b1.png)

Image quality order
4>3=2>1

3 and 2 is almost same quality.
In performance side 3 is faster than 2.

4 is best quality.  
Compare to simple increasing resolution, this way is lighter.
If msaa makes problems how about another SSAA function ?
Maybe, again might be say already SSAA effect be implemented.
But obviously image quality is different.

**Comment by lightningterror** [comment]
Duplicate #3174
