### ISSUE TITLE
nfl street 2 [NTSC] graphical glitch

### ISSUE THREAD

**Issue by dbz345** [PCSX2/pcsx2#2857]
[***PCSX2](url) version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](http://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by dbz345** [comment]
PCSX2 version: pcsx2-v1.5.0-dev-2967-gcc2fda6d6-windows-x86

CPU options: EE/IOP defaults, VUs defaults 

Plugins used: GSdx 20190218051143 1.1.0 AVX2 (hardware and software, dx11 and dx9 with custom and default options), SPU2-X 20181124134036 2.0.0 

Description:

Severe Graphical bug in the newest dev version see screenshot below
https://github.com/PCSX2/pcsx2/issues
![nfl street 2 bug](https://user-images.githubusercontent.com/47800248/53057491-4716b800-3475-11e9-8cbe-006a2b187de2.JPG)

**Comment by dbz345** [comment]
my 
![gsdx11](https://user-images.githubusercontent.com/47800248/53057579-9c52c980-3475-11e9-8d82-0a77fa67b51d.JPG)
gsdx11 settings

**Comment by lightningterror** [comment]
How is OpenGL ?

**Comment by MrCK1** [comment]
It requires FBC hack like Fifa Street 2.

**Comment by lightningterror** [comment]
Are you sure ? 8bit shader and fbmask should emulate the effects properly.

**Comment by dbz345** [comment]
Allow 8bit textures you mean? and how do i turn on fbmask.
Opengl is grayed out under adapter and won't let me add my RTX 2070
![opengl](https://user-images.githubusercontent.com/47800248/53111075-04e78800-3502-11e9-9bac-7fd1cd6ed1f3.JPG)

**Comment by dbz345** [comment]
On dev version I w
![nfl street 2 pcsx2 1 4 0](https://user-images.githubusercontent.com/47800248/53113488-4dee0b00-3507-11e9-8b21-0ec5fc5d2d43.JPG)
ent ahead and tried just to see and no luck OpenGl still looks rough.
Also applied the FBC hack to gsdx11 along with 8bit textures.

The non dev version 1.4.0 has no ground and player graphics issues but you get missing background on both gsdx11 and it does ok on opengl until after a few mins of gameplay then same missing background

Below is the game on non dev 1.4.0 gdsx11 and opengl.

**Comment by dbz345** [comment]
On dev version I went
 ahead and tried just to see and no luck OpenGl still looks rough.
Also applied the FBC hack to gsdx11 along with 8bit textures.

The non dev version 1.4.0 has no ground and player graphics issues but you get missing background on both gsdx11 and it does ok on opengl until after a few mins of gameplay then same missing background

Below is the game on non dev 1.4.0 gdsx11 and opengl.


![nfl street 2 pcsx2 1 4 0](https://user-images.githubusercontent.com/47800248/53113756-ed130280-3507-11e9-8c4d-355864747154.JPG)
![nfl street 2 opengl pcsx 1 4 0](https://user-images.githubusercontent.com/47800248/53113809-03b95980-3508-11e9-8ebc-1c2b1920720b.JPG)

**Comment by lightningterror** [comment]
Can you upload a gs dump ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by dbz345** [comment]
[https://drive.google.com/file/d/1s3LKCHCz9NKqNluaOnFXfdgz3sR3vijJ/view?usp=sharing](url)

**Comment by dbz345** [comment]
You may have to copy that into your browser clicking on the url took me to github
