### ISSUE TITLE
as_const': is not a member of 'std

### ISSUE THREAD

**Issue by bash04** [PCSX2/pcsx2#2858]
I get this error when compiling.

All plugins load less Gsdx

1>------ Build started: Project: GSdx, Configuration: Release Win32 ------
1>  Automatic version detection unavailable.
1>  If you want to have the version string print correctly,
1>  make sure your Git.exe is in the default installation directory,
1>  or in your PATH.
1>  You can safely ignore this message - a dummy string will be printed.
1>  GSTextureFX11.cpp
1>  GSUtil.cpp
1>Renderers\DX11\GSTextureFX11.cpp(102): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(102): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(102): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(102): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(104): error C3536: 'i': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(104): error C2679: binary '==': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=GSVertexShader11
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1340): note: could be 'bool operator ==(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1294): note: or       'bool operator ==(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1129): note: or       'bool operator ==(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(331): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(336): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(341): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(355): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(363): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(371): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(379): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(221): note: or       'bool std::operator ==(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(104): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=GSVertexShader11
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(139): error C2440: '=': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' to 'int'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=GSVertexShader11
1>          ]
1>  Renderers\DX11\GSTextureFX11.cpp(139): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>Renderers\DX11\GSTextureFX11.cpp(149): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(149): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(149): error C2228: left of '.vs' must have class/struct/union
1>Renderers\DX11\GSTextureFX11.cpp(151): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(151): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(151): error C2228: left of '.il' must have class/struct/union
1>Renderers\DX11\GSTextureFX11.cpp(161): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(161): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(161): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(161): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(163): error C3536: 'i': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(163): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11GeometryShader>
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1345): note: could be 'bool operator !=(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1299): note: or       'bool operator !=(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1134): note: or       'bool operator !=(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(197): note: or       'bool operator !=(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(346): note: or       'bool std::operator !=(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(351): note: or       'bool std::operator !=(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(356): note: or       'bool std::operator !=(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(388): note: or       'bool std::operator !=(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(395): note: or       'bool std::operator !=(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(402): note: or       'bool std::operator !=(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(409): note: or       'bool std::operator !=(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(226): note: or       'bool std::operator !=(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(163): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11GeometryShader>
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(165): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(165): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(206): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(206): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(206): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(206): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(208): error C3536: 'i': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(208): error C2679: binary '==': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint64,
1>              _Ty=ATL::CComPtr<ID3D11PixelShader>
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1340): note: could be 'bool operator ==(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1294): note: or       'bool operator ==(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1129): note: or       'bool operator ==(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(331): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(336): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(341): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(355): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(363): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(371): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(379): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(221): note: or       'bool std::operator ==(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(208): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint64,
1>              _Ty=ATL::CComPtr<ID3D11PixelShader>
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(276): error C2440: '=': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' to 'int'
1>          with
1>          [
1>              _Kty=uint64,
1>              _Ty=ATL::CComPtr<ID3D11PixelShader>
1>          ]
1>  Renderers\DX11\GSTextureFX11.cpp(276): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>Renderers\DX11\GSTextureFX11.cpp(295): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(295): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(295): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(295): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(297): error C3536: 'i': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(297): error C2679: binary '!=': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11SamplerState>
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1345): note: could be 'bool operator !=(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1299): note: or       'bool operator !=(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1134): note: or       'bool operator !=(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(197): note: or       'bool operator !=(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(346): note: or       'bool std::operator !=(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(351): note: or       'bool std::operator !=(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(356): note: or       'bool std::operator !=(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(388): note: or       'bool std::operator !=(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(395): note: or       'bool std::operator !=(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(402): note: or       'bool std::operator !=(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(409): note: or       'bool std::operator !=(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(226): note: or       'bool std::operator !=(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(297): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11SamplerState>
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(299): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(299): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(331): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(331): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(336): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(336): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(336): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(336): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(338): error C3536: 'i': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(338): error C2679: binary '==': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11DepthStencilState>
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1340): note: could be 'bool operator ==(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1294): note: or       'bool operator ==(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1129): note: or       'bool operator ==(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(331): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(336): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(341): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(355): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(363): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(371): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(379): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(221): note: or       'bool std::operator ==(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(338): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11DepthStencilState>
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(380): error C2440: '=': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' to 'int'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11DepthStencilState>
1>          ]
1>  Renderers\DX11\GSTextureFX11.cpp(380): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>Renderers\DX11\GSTextureFX11.cpp(383): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(383): note: type is 'int'
1>Renderers\DX11\GSTextureFX11.cpp(385): error C2039: 'as_const': is not a member of 'std'
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\unordered_set(13): note: see declaration of 'std'
1>Renderers\DX11\GSTextureFX11.cpp(385): error C3861: 'as_const': identifier not found
1>Renderers\DX11\GSTextureFX11.cpp(385): error C2228: left of '.find' must have class/struct/union
1>  Renderers\DX11\GSTextureFX11.cpp(385): note: type is 'unknown-type'
1>Renderers\DX11\GSTextureFX11.cpp(387): error C3536: 'j': cannot be used before it is initialized
1>Renderers\DX11\GSTextureFX11.cpp(387): error C2679: binary '==': no operator found which takes a right-hand operand of type 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' (or there is no acceptable conversion)
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11BlendState>
1>          ]
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1340): note: could be 'bool operator ==(const D3D11_BOX &,const D3D11_BOX &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1294): note: or       'bool operator ==(const D3D11_RECT &,const D3D11_RECT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\um\d3d11.h(1129): note: or       'bool operator ==(const D3D11_VIEWPORT &,const D3D11_VIEWPORT &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Windows Kits\8.1\Include\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)' (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(331): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(336): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\exception(341): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(355): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(363): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(371): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\system_error(379): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  C:\Program Files\Microsoft Visual Studio 14.0\VC\include\thread(221): note: or       'bool std::operator ==(std::thread::id,std::thread::id) noexcept' [found using argument-dependent lookup] (compiling source file Renderers\DX11\GSTextureFX11.cpp)
1>  Renderers\DX11\GSTextureFX11.cpp(387): note: while trying to match the argument list '(int, std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>)'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11BlendState>
1>          ]
1>Renderers\DX11\GSTextureFX11.cpp(418): error C2440: '=': cannot convert from 'std::_List_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>' to 'int'
1>          with
1>          [
1>              _Kty=uint32,
1>              _Ty=ATL::CComPtr<ID3D11BlendState>
1>          ]
1>  Renderers\DX11\GSTextureFX11.cpp(418): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>Renderers\DX11\GSTextureFX11.cpp(421): error C2227: left of '->second' must point to class/struct/union/generic type
1>  Renderers\DX11\GSTextureFX11.cpp(421): note: type is 'int'
========== Build: 0 succeeded, 1 failed, 6 up-to-date, 0 skipped ==========

**Comment by lightningterror** [comment]
Maybe a bad VS install ? Win 8.1 SDK issues perhaps.

**Comment by lightningterror** [comment]
I'll go ahead and close this since it's likely a bad VS install, it happens quite often when people are installing it.
