### ISSUE TITLE
Resident evil 4 [NTSC] Line bug

### ISSUE THREAD

**Issue by dbz345** [PCSX2/pcsx2#2864]
PCSX2 version: pcsx2-v1.5.0-dev-2979-gcc2fda6d6-windows-x86

CPU options: EE/IOP defaults, VUs defaults

Plugins used: GSdx 20190218051143 1.1.0 AVX2 (hardware and software, dx11 and dx9 with custom and default options), SPU2-X 20181124134036 2.0.0

Description:
minor lines shading bug 
![gsdx_20190224201724](https://user-images.githubusercontent.com/47800248/53317679-32318e80-3892-11e9-9fd3-abb7078d3ae0.png)

**Comment by dbz345** [comment]
https://drive.google.com/file/d/1hOCRYqMURJ4xEXTZC8kza0UC97GGoS17/view?usp=sharing
lightning here is the gsdump if needed. Opengl helps but you can still see the lighting effect line thingy.

**Comment by lightningterror** [comment]
Yeah we know about it, we didn't find the source yet. One day @tadanokojin will fix it.

**Comment by lightningterror** [comment]
Note: you can disable depth emulation for now until it's fixed.

**Comment by lightningterror** [comment]
D3D11 is now identical with OpenGL, the other lines are an upscaling issue which can be solved with Half pixel offset Normal.
