### ISSUE TITLE
Syscall 0x75 (System Out logging) causes access violation with format specifier "%s"

### ISSUE THREAD

**Issue by Souzooka** [PCSX2/pcsx2#2865]
***PCSX2 version:***
1.5.0 r2843

- **Notes**:
This happens due to PCSX2 attempting to read a string at the address given (e.g. 0x40000) instead of the address that address is mapped to (e.g. 20400000).

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by Quaker762** [comment]
@Souzooka Sorry to necro/hijack this issue, but is this problem still happening? It seems like `syscall 117`, currently, is just crashing the emulator entirely. I'm inserting the following code into SILENT HILL 2's `printf` function:

``asm
li v0, 0x75
syscall
jr ra
nop
```

However it seems that the `jalr k0` in the syscall subroutine is doing something whack that causes PCSX2 to crash entirely. Is there a reason the emulator itself isn't catching this call and just printing out? It seems weird that `$k0` would have a bung address in it.

Related images:

![sh2_wot](https://user-images.githubusercontent.com/4768900/97248238-70483800-1855-11eb-9a23-ebed60fcb093.PNG)

![faulting_address](https://user-images.githubusercontent.com/4768900/97248247-74745580-1855-11eb-80b6-77b80082bafb.PNG)
