### ISSUE TITLE
Reducing the read speed for online games

### ISSUE THREAD

**Issue by haudi** [PCSX2/pcsx2#2866]
Games like MKD are heavily dependent on loading times for online matches. If one player uses PCSX2 with the ISO and the other player the disc, the connection will always fail (sync failure) because the match starts way too fast for people with the ISO. Is there a chance to implement something which emulates the PS2 DVD read speed for an ISO or even disc (4x speed DVD-ROM). I could not find anything suitable for this.

**Comment by Souzooka** [comment]
My understanding is that PCSX2 does emulate 4x speed for DvdRead, and 24x speed for CdRead. You can change this value at \pcsx2\CDVD\CDVD.cpp:1304 if you like.

**Comment by lightningterror** [comment]
An even easier solution would be to just rip the discs.

**Comment by haudi** [comment]
@Souzooka Thanks, I never compiled PCSX2 but I'll try.

It's hard to believe because all games I have are loading instantly (like PS2 games installed on a real PS2 HDD). The FPS are constant between 57 - 60.

**Comment by haudi** [comment]
@lightningterror In my test scenarios with a PS2 the game disconnects 99% of the time because the game on ISO or DVD starts way too fast on PCSX2. Maybe I don't see something in the settings. Thanks any suggestions.

**Comment by haudi** [comment]
Ok, I found a solution (for now): Whenever MKD tries to load the characters screen I've to enable 'slow motion (set at 70%) until the arena appears.

Plus: I tried to play online with PCSX2 against my test PS2 with the original disc. Everything was OK until the DVD drive slows down from time to time (guess PCSX2 don't read the game data continuously) and if the game need some game data (DVD drive speeds up again), the connection is instantly lost (desync problem). Seems like the DVD plugin doesn't behave like the real PS2 drive.

Sorry for my non technical description but maybe it's helpful for others.

**Comment by mirh** [comment]
> Everything was OK until the DVD drive slows down from time to time (guess PCSX2 don't read the game data continuously)
That shouldn't happen tbf. 
https://github.com/PCSX2/pcsx2/blob/83ffbc2d3dcab0db77ca11fa004a5a564937829f/plugins/cdvdGigaherz/src/CDVD.cpp#L116

**Comment by haudi** [comment]
Could my external USB DVD drive be the issue or external USB drives in general? I've two and they speed up to the maximum as soon as my PS2 games start. If I get my hands on an internal drive, I'll try it again with further details.

**Comment by mirh** [comment]
Pcsx2 also uses a fixed speed since ~ever. 
So again, the thing is.. It shouldn't slow down.

**Comment by willkuer** [comment]
But why don‘t you just create an iso out of the dvd? That was kind of the first thing I did. Iso‘s are so much nicer to handle, less noisy then these dvd drives, and they should perform better using pcsx2...

**Comment by mirh** [comment]
That's a practical point of view - still, regardless, it points to some kind of problem with the emulator.

**Comment by haudi** [comment]
@willkuer I'm totally aware of that. I just discovered something while testig my games and MKD is not the only game with this online problem. If the goal is that PCSX2 behave like a PS2 (kind of), well, here is something.

I'm free to test different scenarios in that point and it could be helpful for other PS2 online communities.

**Comment by ramapcsx2** [comment]
Your game seems to require a pre-determined delay. Disc read speed is just one of the factors that are involved.
Tuning the disc read speeds for this game to work would make it far slower than on the actual system.

**Comment by haudi** [comment]
Thanks for the feedback. Finally had the time for testing...and for whatever reason, I can't reproduce it.
