### ISSUE TITLE
[GSdx Opengl HW] Silent Hill 3 Heather Body Texture Distortion/Flickering

### ISSUE THREAD

**Issue by Peduls** [PCSX2/pcsx2#2871]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2991-g811d8781a-windows-x86

***PCSX2 options:***
default settings (any combination of settings using OpenGL)

***Plugins used:***
GSDX: OpenGL (Hardware)
Issue is present regardless of Internal Resolution/CRC Hack Level

***Description of the issue:***
The textures on the player character's body flicker and distort when using OpenGL. Strangely enough, it seems the issue is only present when near the "closer" enemy.

The issue seen below
![capture](https://user-images.githubusercontent.com/34750422/53673809-040fce00-3c47-11e9-8bed-7292e05c1c4f.PNG)

Rendered correctly
![capture2](https://user-images.githubusercontent.com/34750422/53673816-0d009f80-3c47-11e9-9ac0-405620abcc03.PNG)

***How to reproduce the issue:***
Play through the game until you encounter the "closer" enemy for the first time. Walk around and move the camera until the issue becomes apparent.

***Last known version to work:***
Currently working my way backwards to figure out the last known version without the issue.

***PC specifications:***
Operating System
	Windows 10 Enterprise 2016 LTSB 64-bit
CPU
	Intel Core i7 4790K @ 4.00GHz	30 °C
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 799MHz (11-11-11-28)
Motherboard
	ASUSTeK COMPUTER INC. Z97-A (SOCKET 1150)	28 °C
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)	37 °C
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))	34 °C
	2794GB TOSHIBA HDWD130 (SATA )	36 °C
Optical Drives
	ASUS DRW-24B1ST j
Audio
	High Definition Audio Device

**Comment by Peduls** [comment]
It really seems like the texture of the enemy is swapping with the texture for parts of the player character's model as seen in this screenshot.
![capture](https://user-images.githubusercontent.com/34750422/53773048-f906a900-3ea5-11e9-9139-0e175e535e3c.PNG)
I'm still currently trying to pin down the version where the issue is first observed in, but I don't have a lot of free time.

**Comment by Peduls** [comment]
[gsdx_20190305163318.zip](https://github.com/PCSX2/pcsx2/files/2933600/gsdx_20190305163318.zip)

**Comment by Peduls** [comment]
Even stranger, the glitch does not occur when the player is holding a weapon.
![capture](https://user-images.githubusercontent.com/34750422/53848460-a5619180-3f71-11e9-8fd8-f1c061525d65.PNG)
![capture2](https://user-images.githubusercontent.com/34750422/53848468-ad213600-3f71-11e9-8f5c-6b2594f74d39.PNG)

**Comment by lightningterror** [comment]
Does the issue happen on software renderer too?

**Comment by lightningterror** [comment]
I gave it a quick check and it looks like SSE2 plugin is fine, only SSE4 and AVX2 experience the issue, also D3D11 is fine on all of them.

**Comment by lightningterror** [comment]
It is a regression
Last working build:
499206f0ea30bc3835c4e27393f0d573e1e0e78a v1.3.1-1025-g499206f0e https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.3.1-1025-g499206f0e&platform=windows-x86

Regression build:
bfadd884c99935872a773b89b8eb1839754654c0 v1.3.1-1028-gbfadd884c https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.3.1-1028-gbfadd884c&platform=windows-x86

**Comment by lightningterror** [comment]
https://github.com/PCSX2/pcsx2/commit/a46c11b0885719b87f6c1d8455bd88c92caf0a77
https://github.com/PCSX2/pcsx2/commit/7002ff3ec30f1da850d8d2b535705837fca3c30f
should be looked in to.
