### ISSUE TITLE
World series baseball 2k3 [NTSC] Crash upon loading

### ISSUE THREAD

**Issue by dbz345** [PCSX2/pcsx2#2873]
PCSX2 version: pcsx2-v1.5.0-dev-2979-gcc2fda6d6-windows-x86

CPU options: EE/IOP defaults, VUs defaults

Plugins used: GSdx 20190218051143 1.1.0 AVX2 (hardware and software, dx11 and dx9 with custom and default options), SPU2-X 20181124134036 2.0.0

Description: Crashing pcsx2 on loading screen

**Comment by atomic83GitHub** [comment]
@prafullpcsx2 Does your changes to make the game to go ingame affect compatibility in general?

**Comment by lightningterror** [comment]
Game requires a patch to run, what is the game serial and crc ? Also maybe you can upload a savestate before the loading?

**Comment by atomic83GitHub** [comment]
The patch is unstable, the game crash at random intervalls.

**Comment by atomic83GitHub** [comment]
Btw you can add the vector units label

**Comment by refractionpcsx2** [comment]
No longer crashes but m-bit issues are no longer a problem.  The game requires tight sync with VU1 and VU0 and in current master this isn't possible (VU1 is instant), hoping to resolve this down the road a bit...

**Comment by refractionpcsx2** [comment]
#3998 improved the situation here somewhat, the gamespeed is much more normal and there' flickering polys where the players should be, though I suspect this game might never be fully fixed.  We hold out hope though ;)

**Comment by someother1n** [comment]
fwiw, if you enable VU0 kickstart, you can play without flickering polys and just make them invisible instead.

https://user-images.githubusercontent.com/60489087/105938081-d72be780-6024-11eb-9a1c-9b7a30d66d13.mp4

**Comment by atomic83GitHub** [comment]
Closing this in favor of a meta surrounding Blue-Shift games.
