### ISSUE TITLE
"Metal Gear Solid 3: Subsistence" audio missing

### ISSUE THREAD

**Issue by gabriele2000** [PCSX2/pcsx2#2874]
***PCSX2 version:***
Latest build revision v1.5.0-dev-2993-g5c23a9fac

- **Notes**:
The second start of PCSX2 pull out this issue. Reinstalling PCSX2 even with the same dev snapshot resolve the issue

***PCSX2 options:***
Automatic Gamefixes, Enable widescreen patch, every option is default except the one who use 3+ cores

***Plugins used:***
Everything on default, dx11 gpu, custom resolution 1920*1080, everything else on "automatic" (anisotropic and mipmap), no manual hacks activated

***Description of the issue:***
The audio plugin is set on default, audio on 7.1 mode since I have an MSI notebook who give me Nahimic 2+. When I start PCSX2 the second time, the issue appear
![screenshot 4](https://user-images.githubusercontent.com/12186181/53694532-8f58a300-3db0-11e9-9738-383a0c377ae2.png)
![immagine](https://user-images.githubusercontent.com/12186181/53694557-eb232c00-3db0-11e9-9be0-b6802971a3ee.png)

***How to reproduce the issue:***
1: Open PCSX2
2: Start the ps2 emulation
3: Close it
4: Restart the PS2 emulation
5: tadaaa!

***Last known version to work:***
I don't remember but around the revision v1.5.0-dev-2962-g90e38f68d

***PC specifications:***
-Intel core i7-7700HQ
-16GB of RAM DDR4 2400MHz
-SSD 128 GB + 1 TB HDD. PCSX2 is running on SSD, the games are stored on HDD
-Nvidia GTX 1050TI 4GB
The pc is an MSI GP72M 7REX LEOPARD PRO

**Comment by lightningterror** [comment]
Can you post a ss from your spu settings ?

**Comment by willkuer** [comment]
Deleting spu2-x.ini in the ini folder resolves the issue?

**Comment by atomic83GitHub** [comment]
This game should work fine, what is your sound card?

**Comment by gabriele2000** [comment]
> 
> 
> This game should work fine, what is your sound card?

Yeah it's working fine since last two updates... this was a temporary problem
