### ISSUE TITLE
"Metal Gear Solid 3: Subsistence" Memory card always corrupted after every update

### ISSUE THREAD

**Issue by gabriele2000** [PCSX2/pcsx2#2875]
***PCSX2 version:***
Latest build revision v1.5.0-dev-2993-g5c23a9fac

***PCSX2 options:***
Automatic Gamefixes, Enable widescreen patch, every option is default except the one who use 3+ cores

***Plugins used:***
Everything on default, dx11 gpu, custom resolution 1920*1080, everything else on "automatic" (anisotropic and mipmap), no manual hacks activated

***Description of the issue:***
After every update of PCSX2 my memory card got "corrupted" or I can't load saves. Yesterday I "resolved" the issue by converting the memory card to a folder by using the "convert" option. Today I cannot load anything, even if I reconvert it to a normal memory card. I'll try to manage the saves through the ps2 system itself. Maybe I can move the files, don't know.
Here's a demonstration of the problem: https://drive.google.com/open?id=1sluE0uERpZAs4iP0RWRMDcatySMdyIil

***How to reproduce the issue:***
1: Play the game and save it when you want to close it, of course normal saves (in-game)
2: The day after update with the latest revision of PCSX2
3: Open it and try to load your saves
4: Realize that you have to redo everything
5: Desperate

***Last known version to work:***
It simply won't work if you update PCSX2

***PC specifications:***
-Intel core i7-7700HQ
-16GB of RAM DDR4 2400MHz
-SSD 128 GB + 1 TB HDD. PCSX2 is running on SSD, the games are stored on HDD
-Nvidia GTX 1050TI 4GB
The pc is an MSI GP72M 7REX LEOPARD PRO

EDIT: I reconverted the memory card to a normal memory card while using the version with I made the save, I have my save back finally.
EDIT 2: The memory card is being written at every ps2 start... latest revision and I have the problem again.
           I'll try something.
EDIT3: As I expected. I created a new memory card, I copied the save from the "problematic one" (converted from folder to memory card, again) and BANG, savegame loaded. I'll make savestate from now on until the issue is resolved

**Comment by lightningterror** [comment]
@atomic83GitHub can you test this out, I don't think it's an issue.

**Comment by atomic83GitHub** [comment]
@gabriele2000 where did you save the last time you played the game?

**Comment by lightningterror** [comment]
@@gabriele2000 status ?

**Comment by gabriele2000** [comment]
I've been testing everything with the latest builds, seems that the problem just disappear... It solved itself
