### ISSUE TITLE
"Metal Gear Solid 3: Subsistence" strange graphics problem, like a bad SCART cable

### ISSUE THREAD

**Issue by gabriele2000** [PCSX2/pcsx2#2876]
***PCSX2 version:***
Latest build revision v1.5.0-dev-2993-g5c23a9fac

***PCSX2 options:***
Automatic Gamefixes, Enable widescreen patch, every option is default except the one who use 3+ cores

***Plugins used:***
Everything on default, dx11 gpu, custom resolution 1920*1080, everything else on "automatic" (anisotropic and mipmap), no manual hacks activated

***Description of the issue:***
In some areas there is this strange graphic bug... it's like when there is a badly inserted SCART cable on a TV because that's the effect. That's the kind of thing that I wanted to avoid by emulating the ps2 and I have it, no matter what
Here's a demonstration. **look closely at the left border of the screen and at the left of SNAKE** also watch when I switch to software mode and when I open the game menu... snake there is perfect. Must be a lightning problem.
100% problem: https://drive.google.com/file/d/16AxIMTbpW-9AFXzF_Q_2-zHyELr8_vkT/view?usp=sharing
Zone less affected: https://drive.google.com/open?id=1T4ML8AyIiupTM2Ky--a5h-z2Q-MyX-Ym

***How to reproduce the issue:***
I don't know, some areas of the game have it. Example? Start the game, everything is perfect. Go to sokrovjenno and you have that problem. You'll start to have this problem since the point when you are going to rescue Sokolov for the second time, right after you encounter the first landmines and the electric fences

***Last known version to work:***
I don't know, always had this

***PC specifications:***
-Intel core i7-7700HQ
-16GB of RAM DDR4 2400MHz
-SSD 128 GB + 1 TB HDD. PCSX2 is running on SSD, the games are stored on HDD
-Nvidia GTX 1050TI 4GB
The pc is an MSI GP72M 7REX LEOPARD PRO

**Comment by tadanokojin** [comment]
Don't use custom res. Use the resolution multiplier.
If that doesn't work try OGL.

**Comment by gabriele2000** [comment]
> 
> 
> Don't use custom res. Use the resolution multiplier.
> If that doesn't work try OGL.

No differences at all, OpenGL doesn't change anything and resolution scaling just resolve the issue at 5% so no differences

**Comment by lightningterror** [comment]
HPO should be used to fix upscaling issues.
