### ISSUE TITLE
From Russia with love - hangs

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2877]
PCSX2 1.5.0-20190301172113 - compiled on Mar  1 2019

When you start the game at some point of the intro video the game hangs.

I'm using the default speed settings, i tried with mtu enabled or disabled, it still hangs.
I Used software and hardware rendered it still hangs.

There is no error in logs 
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2923157/emuLog.txt)

**Comment by MrCK1** [comment]
Set the EE cyclerate to 2 and it won't hang. 

After that point you won't need it besides some rare cases at random.

**Comment by Levan7** [comment]
@MrCK1 That fixed it, how does that work ?
I'm asking this because i remember i had a broken i7 CPU that used to run like a p4 really had performance issue and it used to start this game with default settings?

How can this happen.

**Comment by lightningterror** [comment]
I'll close this since a workaround is possible.
