### ISSUE TITLE
Dynasty Warriors 3 graphical glitches

### ISSUE THREAD

**Issue by scju** [PCSX2/pcsx2#2880]
***PCSX2 version:***
PCSX2-v1.5.0-dev-2999

***PCSX2 options:***
Tried with default settings.

***Plugins used:***
Everything on default, dx11 gpu, everything else on "automatic", no manual hacks activated

***Description of the issue:***
Dynasty Warriors 3 graphical glitches, similar to this: 
https://www.youtube.com/watch?v=P_9elzhVo7c

***How to reproduce the issue:***
Start the game -> option -> opening. In some cutscenes it happens.

***Last known version to work:***
Not sure.

***PC specifications:***
CPU: Intel I7-2600, 16 GB DDR3 RAM, GPU: Geforce GTX1050, Windows 7 64bit

**Comment by lightningterror** [comment]
Can you upload a GS dump ?

**Comment by scju** [comment]
Here are four GS dumps for your reference:
https://mega.nz/#F!7hRUWawT!X_uZzhOwdrxMYuy773V8dQ

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest master?

**Comment by scju** [comment]
> Is this still an issue on latest master?

I am using PCSX2-v1.7.0-dev-435 and the issue still exists.

**Comment by refractionpcsx2** [comment]
How do you have the "opening" not grey'd out? Do I need a memory card save? if so can you upload a memory card?

**Comment by scju** [comment]
> How do you have the "opening" not grey'd out? Do I need a memory card save? if so can you upload a memory card?

See [https://gamefaqs.gamespot.com/ps2/516690-dynasty-warriors-3/cheats](ur lhttps://gamefaqs.gamespot.com/ps2/516690-dynasty-warriors-3/cheats)

**Comment by refractionpcsx2** [comment]
Okay that worked, thanks.  Are you using the US version of the game?

**Comment by scju** [comment]
Both the US and Chinese version.

**Comment by scju** [comment]
> Okay that worked, thanks. Are you using the US version of the game?

Both the US and Chinese version.

**Comment by refractionpcsx2** [comment]
Okay I've just submitted a patch for the US version, if you want to try it.

As for the Chinese version, it doesn't even seem to be in the Game DB? I would need the ELF file to do that one, unless you can run a development build (I mean build manually in "devel" mode) and you run the intro, you should get a warning about Cop2 instructions

**Comment by scju** [comment]
> Okay I've just submitted a patch for the US version, if you want to try it.
> 
> As for the Chinese version, it doesn't even seem to be in the Game DB? I would need the ELF file to do that one, unless you can run a development build (I mean build manually in "devel" mode) and you run the intro, you should get a warning about Cop2 instructions
Thank you for the update. The issue in the US version has been fixed. 

As for the Chinese version, I hope the following helps:

aHR0cHM6Ly9tZWdhLm56L2ZpbGUvN2xCZ0RUQUEjbmVoam1NWDd0NHlFOWJzaGNjcUl5blNiNmtDUmpBODhTcWQwYjhER1J4QQ==

**Comment by refractionpcsx2** [comment]
a random string of characters isn't overly helpful, no :P

**Comment by scju** [comment]
> a random string of characters isn't overly helpful, no :P
It's a random string of characters which needs to decode:
[https://www.base64decode.org/](https://www.base64decode.org/)

**Comment by scju** [comment]
> > a random string of characters isn't overly helpful, no :P
 It's a random string of characters which needs to decode:
 https://www.base64decode.org/

**Comment by scju** [comment]
> Can you run the game and tell me your CRC and your Serial number for the game please?

How can I see that?

**Comment by refractionpcsx2** [comment]
It'll be listed at the top of the log window, if you don't have that open you can go to Misc (or Window)->Show Console

**Comment by scju** [comment]
> It'll be listed at the top of the log window, if you don't have that open you can go to Misc (or Window)->Show Console

[SLPM-65163][397F3835]

Is there something else I need to offer? :)

**Comment by refractionpcsx2** [comment]
Okay can you try the new master? I just submitted a fix for that version

**Comment by scju** [comment]
> Okay can you try the new master? I just submitted a fix for that version

It has also been fixed. Thank you for the great work! :+1:

**Comment by refractionpcsx2** [comment]
Awesome :) I'll close this for now then, until somebody with the PAL version comes along.

**Comment by scju** [comment]
But now I found that the FMVs flicker in the game in hardware mode.

**Comment by refractionpcsx2** [comment]
That's an issue out of scope of this issue. There is a meta issue for FMV's that don't work in HW mode and require software #3805

**Comment by scju** [comment]
> That's an issue out of scope of this issue. There is a meta issue for FMV's that don't work in HW mode and require software #3805

But the FMVs issue had once been fixed in this game in v1.7.0-dev-435 and before. (Please see Known Issues on [https://wiki.pcsx2.net/Dynasty_Warriors_3](https://wiki.pcsx2.net/Dynasty_Warriors_)3)

In v1.7.0-dev-437 (and maybe in v1.7.0-dev-436), it comes again.

**Comment by refractionpcsx2** [comment]
Yes and that option got removed, which is what that issue I linked is for, so please post your issue there
