### ISSUE TITLE
[Feature request] Freeze the GS Window

### ISSUE THREAD

**Issue by weirdalsuperfan** [PCSX2/pcsx2#2881]
I imagine F11 used to do something like this, but all the excitement I had when I read up on the shortcuts was short lived when I investigated a little more and realized that F11 no longer works.

I'm playing games in Japanese and I'd like to be able to pause games where reading text takes too long, especially in cases where the text will disappear on its own. 

I also take screenshots when I encounter a new word because it gives me the context I heard/read that word in, and being able to freeze/unfreeze the screen would let me time screenshots better and know what the screenshot actually looks like before opening the snaps folder and seeing if I got just the right one.

Digging through all the screenshots after the fact and trying to combine them with words is not pleasant, and pausing the game every time I run across something new and want to make sure I have the right screenshot, etc. before going back to the game takes forever. On the other hand, if I had one solid screenshot per word (instead of multiple iffy ones I spammed to be safe, which I need to look through later to whittle down to one), then I would be able to fully automate the process of searching through my screenshots (because I wouldn't have to confirm if they're good), which would be a lifesaver when creating things with [Anki](https://apps.ankiweb.net/).

Anyway, I don't know if this is possible, or if it's a simple thing I can activate on my own without breaking things, but if this feature or something equivalent existed then it would certainly make me a happy camper!

**Comment by bositman** [comment]
I think you can do it, using the TAS PR: https://github.com/PCSX2/pcsx2/pull/2412
Use a compiled build from that PR and try pressing P while playing, it should have the desired effect. I think you need to press P twice afterwards to unpause

**Comment by avih** [comment]
So you want to pause without closing the GS window? It's been supported for years:

Config -> Emulation Settings -> GS Window -> Uncheck "Hide window while paused".

By default ESC pauses, so simply press ESC once to pause with the window visible, and then ESC again to resume. Isn't that what you want?

**Comment by weirdalsuperfan** [comment]
@avih Wow, it really works! But I can't seem to unpause with a shortcut. For some reason no matter how much I press ESC it won't start again. The focus of the window just shifts to the PSCX2 control panel, away from the GS window.  I tried pressing a few other keys too, with no luck. In order to resume I have to manually click the resume button.

Actually I realized I can maybe use autohotkey for my workflow (if I can text hook), and it'd be a lot easier if I could unpause, although I might not need to pause if I automate everything...but either way it'd be convenient for reading things slowly if I could unpause with a hotkey.

@bositman Thanks for that! I'll try installing that build if I can't get this issue with unpausing sort out.

**Comment by avih** [comment]
> But I can't seem to unpause with a shortcut. For some reason no matter how much I press ESC it won't start again. The focus of the window just shifts to the PSCX2 control panel, away from the GS window

I just tried with a recent PCSX2 and it works for me. If it's fullscreen then it might exit from fullscreen when you pause, but the GS window keeps the focus, and pressing ESC again resumes and restores fullscreen.

I think something in your setup intervenes. It _should_ work out of the box.

**Comment by weirdalsuperfan** [comment]
I guess I can try reinstalling the program (after making note of the settings I remember changing), but honestly I only just installed this over the weekend, so I don't know what setting would have caused this problem, and if there is such a setting, wouldn't it be a bug?

The only maybe out of the ordinary thing I think I did was that when installing I chose to have the installation folder in my D drive. I really do hope that this is caused by something I did, though.

I'm on Windows 10, if that matters.

**Comment by avih** [comment]
Can anyone other than OP and myself test if this works for them please?

**Comment by Dreadmoth** [comment]
@avih ESC pause/resume (with unchecked "Hide window while paused") behaves exactly as you described for me.

**Comment by lightningterror** [comment]
It behaves as avih described for me as well.

**Comment by lightningterror** [comment]
So are there any other issues or can we close this one?

**Comment by avih** [comment]
Closing. Please post here if there are still issues.
