### ISSUE TITLE
Black NTSC random hangs 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2884]
PCSX2 1.5.0-20190308193328 - compiled on Mar  8 2019

The game is running full speed, doesn't drop frames but the game randomly hangs, i'm using the default speed settings  MTVU enabled/disabled doesn't change the outcome.

The game just randomly hangs, 

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2949567/emuLog.txt)

![old](https://user-images.githubusercontent.com/5770076/54086303-bb9c9280-4361-11e9-886a-2bc95b77118c.gif)

[snaps.zip](https://github.com/PCSX2/pcsx2/files/2949589/snaps.zip)

**Comment by MrCK1** [comment]
Don't load from a savestate

**Comment by Levan7** [comment]
@MrCK1 I have tested it and has the same issue

**Comment by willkuer** [comment]
Would still be better to upload an emulog with neither mtvu nor sstates applied. Possibly the log shows something different then.

**Comment by Levan7** [comment]
@willkuer  I think it happens when i get head shots at least that is what i think
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/2952788/emuLog.txt)

**Comment by prafullpcsx2** [comment]
If you can post a savestate right before such hang, it may help.

**Comment by Levan7** [comment]
@prafullpcsx2 Well it happens on every level and it happens randomly when i shoot people in their faces (while running and gunning).

**Comment by atomic83GitHub** [comment]
This can happen when the VU cycle stealing or EE timing hack are in use, are you sure they are disabled?

**Comment by Levan7** [comment]
@atomic83GitHub just download the PCSX2 1.5.0-20190312131301 - compiled on Mar 12 2019 version and using the default speed settings, only thing I've changed is enabled 8 bit textures and 3x resolution.
It hangs

**Comment by Levan7** [comment]
Well running this game in interlace mode i got prompted with this message. 

`..\..\FiFo.cpp(48) : assertion failed:
    Function:  ReadFIFO_VIF1
    Thread:    EE Core
    Condition: vif1Regs.stat.FQC != 0
    Message:   FQC = 0 on VIF FIFO READ!

Stacktrace:
[00] 0x002AC486                                  
[01] 0x001EA5E2                                  
[02] 0x002A71A3                                  
[03] 0x00433F08                                  
[04] 0x002109AD                                  
[05] 0x002109AD                                  
[06] NvOptimusEnablement                         
[07] 0x004DEA70                                  
[08] 0x002EB071                                  
[09] 0x006D4075                                  
[10] 0x006D3F20                                  
[11] 0x006D3E73                                  
[12] 0x00531A42                                  
[13] o____lc_collate_cp_func                     
[14] BaseThreadInitThunk                         
[15] RtlAreBitsSet                               
[16] RtlAreBitsSet                               
`

**Comment by willkuer** [comment]
Try to disable widescreen hacks. Tlb miss is a typical indicator for a broken pnach (the system used to generate widescreen)

**Comment by Levan7** [comment]
@willkuer i don't think it is tied to the widescreen hack, it happens when i have it disabled as well however when i enabled ee timing hack it almost doesn't happens after 2 hours playing time it crashed once however now i noticed different issues, the game sticks to poles and walls and it teleports you to a different place on the map

**Comment by atomic83GitHub** [comment]
The last problem you mentioned never got fixed in any PS2 emulators (possibly related to Mbit), an example of this is the end of the level 4 which is the most broken place in the game.

**Comment by atomic83GitHub** [comment]
@Levan7 Do you have a NTSC copy of the game?

**Comment by Levan7** [comment]
@atomic83GitHub well i would think that i have a NTSC copy of this game

**Comment by refractionpcsx2** [comment]
Is this still an issue on current master builds?

**Comment by Levan7** [comment]
@refractionpcsx2 refractionpcsx2  In mission two this issue was most predominant couldn't reproduce with latest dev build

**Comment by refractionpcsx2** [comment]
Good :) I'll close this then. Thanks for the report!
