### ISSUE TITLE
Wrong conditional to select tex_is_fb

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#2889]
OpenGL HW renderer
Game: Jak/R&C/tri ace shadows

Current condition check if primitives don't overlap. However in case of a single triangle (no overlap), we won't use the tex_is_fb path. Technically input texture is correct but the shader also use a more accurate texture coordinate. Therefore it can cause some glitches in some angles.

Proposed fix: check if primitives are triangles rather than checking overlapping.

**Comment by lightningterror** [comment]
I'll close this now since the pr is merged.
