### ISSUE TITLE
Final Fantasy X Invisible Tidus in Besaid Cloister of Trials

### ISSUE THREAD

**Issue by Mensa41** [PCSX2/pcsx2#2891]
***PCSX2 version:***
v1.5 dev 3007

- **Notes**:
 After completing the Besaid cloister of trials and triggering the cutscene with wakka, tidus turns invisible until the elevator activates

Video displaying the cutscene on real hardware: https://www.youtube.com/watch?v=5S-b5_m0-BM&list=PL0FCB2429F8E60C1B&index=15

Video displaying the cutscene on the emulator: https://www.youtube.com/watch?v=6m_sV5n0kDk&feature=youtu.be&t=1h28m34s

***PCSX2 options:***
Default Settings, no widescreen patches no cheats

**Comment by bositman** [comment]
Try changing rounding modes, but you will have to load from a memory card save and retry and not a saved state. Also maybe EE/VU clamping could affect it

**Comment by Mensa41** [comment]
Setting round mode to nearest in the EE/IOP tab fixed it, gonna test it more, to see if doesn't break anything else

**Comment by atomic83GitHub** [comment]
And what about negative rounding?

**Comment by Mensa41** [comment]
Negative rounding also fixes it

**Comment by atomic83GitHub** [comment]
Well negative rounding should automaticaly be apply to the game, what is your game serial?

**Comment by Mensa41** [comment]
Final Fantasy X International

SLPS-25088 
CRC 658597E2
