### ISSUE TITLE
[REGRESSION] Sega Memorial Collection [SLPM-62709] - crash upon bootup

### ISSUE THREAD

**Issue by LanceBoyle94** [PCSX2/pcsx2#2895]
***PCSX2 version:***
pcsx2-v1.5.0-dev-2242-ge10ac8cbe-windows-x86

***PCSX2 options:***
Default settings

***Plugins used:***
GSDX (DirectX11 HW and SW renderers, default settings), SPU2-X (default settings)

***Description of the issue:***
PCSX2 crashes/hangs when booting the game, with different results; if started from "Boot ISO (full)" it crashes before the "PlayStation 2" logo splash (it still thinks it's on the BIOS) and has to be closed from the Task Manager, while starting it from "Boot ISO (fast)" has it hang at a black screen forever.

On the latter, the log constantly prints the following as well:
![imagen](https://user-images.githubusercontent.com/25116320/54657541-9cf87300-4aa8-11e9-82e1-9cf9e30f8e0e.png)

I tried it on the build mentioned on the top of the page, as well as the latest build available (pcsx2-v1.5.0-dev-3011-g5c7084f8b-windows-x86 as of this writing), and both give the same results. However, just in case, I tried it out in one of the earlier stable versions, specifically 1.0.0-r5350, and the game does boot, so I imagine a regression must've occurred in one of the later versions.

**Comment by MrCK1** [comment]
If you can test the other stable versions (1.2.1 and 1.4.0) and try to narrow down the build that caused this, it would help alot

**Comment by LanceBoyle94** [comment]
Tested it and the same issues happen on the stable 1.2.1 (1.2.1-r5875) and 1.4.0, unfortunately.

**Comment by MrCK1** [comment]
OK. Can you use the list of builds here and try to figure out which one it was?

You'll have to search between November 2012 (1.1.0) and February 2014 (1.2.1). The build dates are listed next each build.

https://buildbot.orphis.net/pcsx2svn/index.php?m=fulllist

**Comment by atomic83GitHub** [comment]
Can you make a blockdump of that game so we can also try to find the bad commit?

**Comment by LanceBoyle94** [comment]
Sorry for the somewhat late post, but I recently got another copy of the game and it turns out that this one does work, with the same settings and all, which is a good sign and means that it likely wasn't a regression after all but some odd issue with the copy I had.

![imagen](https://user-images.githubusercontent.com/25116320/55678276-4921c280-58cd-11e9-95bb-1f57832ad954.png)

It does make me wonder why the older version ran the other copy; perhaps it was some faulty/corrupted sector that got ignored/skipped in that older version. Just in case, here's a blockdump of that copy.

https://drive.google.com/open?id=1Hm2RCn7oYKchoD8AhmtyeSKmLEq3hmWm

Feel free to close this issue if it does turn out to not be a regression.

**Comment by orbea** [comment]
I would guess you had a bad game dump, maybe it was corrupted by some file system issue?

**Comment by atomic83GitHub** [comment]
So, is this issue still valid?

**Comment by atomic83GitHub** [comment]
This issue is invalid as a proper dump of the game works. Closing.
