### ISSUE TITLE
Sega Ages Panzer Dragoon wrong video mode and screen shake

### ISSUE THREAD

**Issue by TheStremon** [PCSX2/pcsx2#2897]
***PCSX2 version:***
development builds v1.5.0-dev-3013

***PCSX2 options:***
Everything is default

***Plugins used:***
Everything is default
Renderer D3D 11 Hardware
Also tested with different renderers, interlaced modes and resolutions

***Description of the issue:***
The game switches to progressive scan in the main menu and ingame, when it should stay in interlaced mode, creating screen shake.
During FMVs the game switches back to interlaced, and there is no screen shake.

I tested the game on a real PS2 (with component cable capable of doing progressive scan), the game stays in interlaced mode at all time, and there is no screen shake.
Is there a way to force the game to stay in interlaced mode?

***How to reproduce the issue:***
Just launch the game.

***Last known version to work:***
The issue was always present

***PC specifications:***
CPU: i7 3770K at 4.0GHz
GPU: Gigabyte GTX 1060 6GB
RAM: 32GB at 1333MHz
OS: Windows 10 64 Bit

**Comment by lightningterror** [comment]
Workaround patch/fix added in https://github.com/PCSX2/pcsx2/pull/2902
