### ISSUE TITLE
Astro Boy screen issue at 1st boss battle or before..

### ISSUE THREAD

**Issue by Mclaneinc** [PCSX2/pcsx2#2898]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3014-g3133221fd-windows-x86

Astro Boy is marked Playable but using the default settings and software mode it does get past the black screen in the Home but when fighting the tentalces of the robot first boss or the Boss itself the screen will go cyan or another pastel shade and you cannot see anything. Tried experimenting with settings but to know effect.

Any idea's please..

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by prafullpcsx2** [comment]
Can you upload a savestate right before this issue?

**Comment by Mclaneinc** [comment]
Here's 2 savestates, slot 1 and 2, the olest one is at the level it happens but not happened yet, it can happen at any time when flying or pulling on the objects legs to rip them off.

The newer on is exactly after the issue has happened...

Both of these are on cleared default settings bar turning the OGL to software rather than hardware, it also happens on the DX version in software mode....Dev PSX2 from yesterday..

[SLUS-20867 (D88FCB86).01.zip](https://github.com/PCSX2/pcsx2/files/3000490/SLUS-20867.D88FCB86.01.zip)

**Comment by prafullpcsx2** [comment]
![image](https://user-images.githubusercontent.com/12788199/54882888-c0defe80-4e84-11e9-9105-81e4e7cef4f0.png)
Nothing happened. Punched the leg few times and reached this part. I need to wait longer?

**Comment by Mclaneinc** [comment]
Yes, its a bit random when it happens, sometimes very early on in that level and in other cases just before you kill the big boss. As you can see by the newer save state it does happen so not a wild goose chase :)

Its happened every time I play that level, if it does not happen to you then perhaps there's a configuration issue here at my end but as I said I reset to default settings and just changed the graphics plugin to OGL software.

**Comment by prafullpcsx2** [comment]
Here is quick tip for you, you can use HW mode too if you enable EE cycle skipping 2 or higher.

**Comment by Mclaneinc** [comment]
Thank you..I'll try that later..

**Comment by prafullpcsx2** [comment]
Enabling pre load frame data hack in gsdx also makes HW mode work.

**Comment by Mclaneinc** [comment]
Tried both and separately and it still happens here...Going to try a complete clean install and remove any data in the My Documents folder, does it store any data anywhere else?

**Comment by Mclaneinc** [comment]
Btw, thanks for the help...Sorry, should have said that initially...

**Comment by Mclaneinc** [comment]
Did all that and found the entry in the registry too..Totally zero'ed, used latest vesion from here 
https://buildbot.orphis.net/pcsx2/

Again tried it as software because that's the known 'it works' from the Wiki and used a US known crc bios.

Same issue mid way through the boss battle when locking on and using the spin attack (as suggested in the game). There was a minor glitck when 'Astro' got far away and then as I was bashing the boss the screen did the same thing BUT I noticed on the visible log window a list of same error but different addresses..

Attaching capture..

![Capture](https://user-images.githubusercontent.com/28862066/54910136-a425e380-4ee3-11e9-97c3-bb6b59c7025a.PNG)

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest master?

**Comment by StoicIndividual** [comment]
Any solution known solution yet? I'm facing the same issue

**Comment by refractionpcsx2** [comment]
@StoicIndividual what version of PCSX2 are you running?

**Comment by StoicIndividual** [comment]
> @StoicIndividual what version of PCSX2 are you running?

1.5.0

**Comment by StoicIndividual** [comment]
> @StoicIndividual what version of PCSX2 are you running?

I did find a simple workaround, and that is to not use spin attack, or fly as often, but mostly to not use spin attack

**Comment by refractionpcsx2** [comment]
1.5.0 is ancient, can you please try the latest development build, you can get it from here: https://buildbot.orphis.net/pcsx2/

**Comment by StoicIndividual** [comment]
> 1.5.0 is ancient, can you please try the latest development build, you can get it from here: https://buildbot.orphis.net/pcsx2/

I tried the same stage with the latest development version, the cyan screen still occurs if I spin attack too much

**Comment by atomic83GitHub** [comment]
I am very sorry, this is my fault if this is not fixed yet on master, you need to set the EE rounding mode to nearest in order for that boss to work.

**Comment by StoicIndividual** [comment]
> I am very sorry, this is my fault if this is not fixed yet on master, you need to set the EE rounding mode to nearest in order for that boss to work.

Thanks for the help, now the cyan screen no longer appears when spin attacking

**Comment by lightningterror** [comment]
EE rounding mode to nearest is present currently for the game in the gamedb so the issue should be resolved.
