### ISSUE TITLE
MTV Music Generator 2 Screen Position Glitch

### ISSUE THREAD

**Issue by Enyalij** [PCSX2/pcsx2#2901]
Running the very latest version 
1.5.0-2019032320462

Game has a black box on the bottom at all times 
no combination of setting effects this or makes it any better.

the native resolution of this game is 640x256

its never displayed properly on any versions of PCSX2

![Annotation 2019-03-24 234813](https://user-images.githubusercontent.com/48612549/54894074-51224100-4e8f-11e9-83cf-2652c0044396.png)

(This game takes advantage of the Singstar USB microphone plugin and actually works surprisingly well in emulation, if the aspect ratio problem was worked out this game would work 100%)

**Comment by lightningterror** [comment]
How is sw renderer ?

**Comment by Enyalij** [comment]
Same results with both software and hardware modes

**Comment by atomic83GitHub** [comment]
It's similar to "The king of fighter 2000" so it's probably a PCRTC problem.

**Comment by ssakash** [comment]
A GSdump of the issue could help.

**Comment by Enyalij** [comment]
sorry for the late response
here is the dump: https://drive.google.com/open?id=1hI1_fJ0oi5DhzmoxjyvDilJ1jhecG6FR

hope it helps

**Comment by HeroponRikiBestest** [comment]
Loop Sequencer: Music Generator also suffers from this issue.
