### ISSUE TITLE
Debugger lacks "go to" option and also no memory search.

### ISSUE THREAD

**Issue by retrobenny** [PCSX2/pcsx2#2906]
PCSX2 v1.5.0dev-3022-g55112938a

**Notes**;

Its unfortunate that entering cheats is a huge pain,you have to convert them into a custom formatted text using a special file type and boot the game then read the log to get the CRC in order to name the file correctly.
That said,I got it working with a test code.
The worst part is not having real-time cheat access to begin with despite debugger seemingly allowing you to overwrite memory manually. (haven't tried to yet)
I know recompiler would prevent ASM stuff from working in real-time but static value changing codes would work fine and you could take advantage of save states to refresh caching so that the game updates the ASM and the freshly enabled code starts working.

**Description**;

There is no quick way to reach specific address locations via a "go to" context option.
It would be excruciating to slowly scroll up/down until reaching a specific address.

I also would like to request that a cheat/memory search option could be added,please.
I was planning to try Cheat Engine but have no quick way to reach the beginning of the memory on debugger in order to find out the first unique value for obtaining the starting point on Cheat Engine so I could later on convert findings to a real address offset for breakpoints.

Then I could search for value changes to potentially breakpoint in order to create something like action mods and other really cool code ideas since I know my way around MIPS assembly for stuff like N64 and PS1 already.

I can't do all that much in a reasonable amount of time when an emulator's debugger lacks essential quality-of-life improving features like these.

**Comment by tadanokojin** [comment]
> There is no quick way to reach specific address locations via a "go to" context option.
It would be excruciating to slowly scroll up/down until reaching a specific address.

Press ctrl+g. Also checkout the ? at the top right of the window for shortcuts.

**Comment by tadanokojin** [comment]
> I was planning to try Cheat Engine but have no quick way to reach the beginning of the memory on debugger in order to find out the first unique value for obtaining the starting point on Cheat Engine so I could later on convert findings to a real address offset for breakpoints.

Also, you shouldn't need to do this. The memory is already virtually mapped in CE.

**Comment by tadanokojin** [comment]
I'm closing this as invalid.
Please in the future direct questions about how to use the emulator here https://forums.pcsx2.net/ before creating an issue.

Thank you

**Comment by retrobenny** [comment]
Thanks for the info,I wish I had known that already,then I would have just bumped an existing cheat search issue instead of having this one for the go to address action.

https://github.com/PCSX2/pcsx2/issues/996

Still don't have direct cheat search built-in though,making things extra difficult.

Not sure if Cheat Engine actually has that on by default to avoid modifying the emulator itself,unless an update made it much smarter.
Cheat search built-in on PCSX2 I feel would be way better and easier than having to use Cheat Engine due to CE's reverse byte order endian annoyance which makes trying to find values almost impossible.

Another thing,I can't seem to find any value/name for the game id in memory with ctrl+g.
00000000-00070000 is ?? as values,I am curious,why does it do that/what is that part of memory used for?
Finding the game id in what is normally supposed to be the first place of some system's memory for games would usually allow me to search a set of values to quickly figure out the start of the memory.
But it seems PS2 doesn't do that,leaving me with the only other option of searching for an early value then calculating the ranges correctly to port Cheat Engine to a real code/breakpoint location.

**Comment by Monkeor** [comment]
I agree. That we can't search RAM for specific values in a running game is a surprising missing feature. Cheat Engine is a bother to use, and evidently some steam games scan for it just being installed and ban based on that.
