### ISSUE TITLE
Modding ASM in-game via debugger crashes despite pausing/using break.

### ISSUE THREAD

**Issue by retrobenny** [PCSX2/pcsx2#2907]
PCSX2 v1.5.0dev-3022-g55112938a

Full issue name;
_Modding ASM in-game via debugger crashes despite pausing or using break/please make a branch with write protection disabled for memory assembly._

Notes; Sorry this is so long.

I found this old thing called pcsx2dis that has access to instant RAW codes for testing,but its old and incompatible with new versions of pcsx2.
This is the main thing I want that pcsx2 lacks aside from built-in search,can't even put in codes without having to stop emulation to regain file access then editing the patch cheats in the not simple way then booting the game back up.

After a few times of this,another bug happens (will post issue soon if not already made) that makes it slow around 67% speed at boot on lighter parts of the game (GTA3) before the area is even loaded,like on the logos,intro video,and the title screen.
Loading can have the fastest performance normally where I can set unlimited speed for up to 400% so its not entirely my computer itself.

If I had real-time cheat access and/or could overwrite existing asm at all,I could just take advantage of save states by making one then loading it,reserving another one for untouched memory in order to test asm codes instantly without needing to use interpreter provided it doesn't forcibly use cache which would make asm changes still not work in real-time from my experience on another console's emulator.

Description;

I can't overwrite asm in real-time,not even when at least paused or in a breakpoint because it crashes,meaning it probably is write protected,much to my annoyance.

To produce the issue; Locate some asm with a static value's breakpoint for a useful code or use this sample code I have for asm for GTA3. ( CRC is 5E115FB6 ,at least on my end )

People Sometimes Drip Blood
201E758C 24020004

(I can confirm the code works in the patch cheat file along with premade codes,but trying to write so much as a single byte in debugger on asm immediately crashes stuff even after clicking break on debugger to pause emulation.)

Get into the game standing idle then open debugger and click the break button in debugger to pause emulation then go to 001E7580 with ctrl+G and try to overwrite the asm at 001E758C like that until every byte is correct then resume the game,only you will get a crash when you attempt to write the first byte/nibble.

**Comment by tadanokojin** [comment]
You're editing code from the memory editor.
Instead, do it in the asm viewer or use cheat engine.

Closing in favor of #2555

**Comment by retrobenny** [comment]
There is a problem with that,editing from the asm part can be a big pain because you have to have precise placement of the text or problems can happen and making typos is easier and worse than just using values.

**Comment by tadanokojin** [comment]
Right Click -> Assemble Opcode

I really suggest you create and account at https://forums.pcsx2.net/ and talk to the many experienced people who can help you use the debugger.

The suggestion I made is a workaround until #2555 is fixed.

**Comment by retrobenny** [comment]
Despite being correct,I keep getting errors when using that Assemble Opcode option,even after editing another one to copy past a carbon copy then changing its register and value to what I want,its being really stubborn.

**Comment by tadanokojin** [comment]
This is not a support forum.
Please direct issues/questions about how to to use the debugger to https://forums.pcsx2.net/
