### ISSUE TITLE
Odd performance bug after a few game shutdowns and booting again.

### ISSUE THREAD

**Issue by retrobenny** [PCSX2/pcsx2#2908]
PCSX2 v1.5.0dev-3022-g55112938a

Notes;

Funny thing is that I can use 50% underclock on GTA3 and it still runs somewhat smooth most of the time and is really difficult to cause the game to lag consistently.
That makes me wish I could figure out and find a 60fps code.
(yes,the game actually runs at 30fps internally even if overclocked from what I can tell after turning off the trails in the game options,rain effects looks like 60fps somehow)

Description;

If you run a game then shut it down and repeat this process a few times (have to do this to edit the cheats patch file with new cheat attempts) you may end up with oddball performance like 67% instead of 100% speed.

To reproduce;

Run a game like GTA3 then shut it down and run it again a couple more times with the final time staying booted.
Now it should have an odd performance like 67% speed regardless of how light the menus are before reaching in-game.

Versions;

I don't have much version history (past computers were too slow for that) so I have no idea if any older versions avoid this issue.

Specs;

CPU: Dual-core Intel i5 6200U (2 cores, 4 threads) at 2.30Ghz (2.80Ghz Turbo)

GPU: Intel HD Graphics 520/Nvidia GeForce GTX 940MX (used by pcsx2)

**Comment by MrCK1** [comment]
I wasn't able to reproduce this, maybe it's an issue with your cheat file.

**Comment by lightningterror** [comment]
This doesn't seem like a real issue so I will close this.
