### ISSUE TITLE
Build fails, complaining about wxwidgets

### ISSUE THREAD

**Issue by johnny-mac** [PCSX2/pcsx2#2912]
```
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building with GNU GCC
-- Enable the building of po files by default in Release build !!!
-- Cross compilation is enabled.
-- Compiling a i386 build on a x86_64 host.
-- Found ALSA: /usr/lib32/libasound.so (found version "1.1.8") 
-- Found PCAP: /usr/lib32/libpcap.so  
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Found LibXml2: /usr/lib32/libxml2.so (found version "2.9.9") 
-- Found Freetype: /usr/lib32/libfreetype.so (found version "2.10.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found Git: /usr/bin/git (found version "2.21.0") 
-- Looking for lzma_auto_decoder in /usr/lib32/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib32/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib32/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib32/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib32/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib32/liblzma.so - found
-- Found LibLZMA: /usr/lib32/liblzma.so (found version "5.2.4") 
-- Found OpenGL: /usr/lib32/libOpenGL.so   
-- Found ZLIB: /usr/lib32/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib32/libpng.so (found version "1.6.36") 
-- Could NOT find Vtune (missing: VTUNE_LIBRARIES VTUNE_INCLUDE_DIRS) 
CMake Error at /usr/share/cmake-3.14/Modules/FindwxWidgets.cmake:954 (message):
  wxWidgets wx/version.h file not found in
  /usr/lib32/wx/include/gtk2-unicode-3.0;/usr/include/wx-3.0.
Call Stack (most recent call first):
  cmake/SearchForStuff.cmake:74 (find_package)
  CMakeLists.txt:27 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kz/Compiles/pcsx2-emu-fresh/src/pcsx2/build/CMakeFiles/CMakeOutput.log".
See also "/home/kz/Compiles/pcsx2-emu-fresh/src/pcsx2/build/CMakeFiles/CMakeError.log".
```

This PKGBUILD I am using worked fine a month or two ago, but is now failing with this error. Has a new dependency been added that I've missed? Checked the AUR package but nothing noticable... This is with the latest commit as of now. I am running Artix Linux, a fork of ArchLinux but with the choice of Runit or OpenRC.

**Comment by kylemiller3** [comment]
Have the same issue on Ubuntu 18.04

**Comment by lightningterror** [comment]
I don't think there were any changes made, anyway I did find this
https://cmake.org/Bug/view.php?id=15928

**Comment by gregory38** [comment]
Could you reports where is located your wx version file
```
find /usr -name "version.h"
```

**Comment by pixelherodev** [comment]
I have the file /usr/include/wx-3.0/wx/version.h under both Alpine and Devuan with bleeding edge releases. 

Furthermore, I have it on Ubuntu MATE, and I'm fairly certain I'm also running 18.04.

**Comment by kylemiller3** [comment]
```
k@k-desktop:/usr/lib/games/PCSX2/mono_i386/usr/lib$ find /usr -name "version.h"
...
/usr/include/wx-3.0/wx/version.h
```

**Comment by kylemiller3** [comment]
Not sure what changed but I was able to successfully build 52da124 today

**Comment by orbea** [comment]
Probably something changed on your end and the missing file is now where its expected.

**Comment by kylemiller3** [comment]
I would assume so but afaik I had that file where it was expected before. Maybe I changed it between the follow up and the initial post though.

**Comment by orbea** [comment]
Did you do any system updates or install/remove any packages between attempts? Since the file is now present and you can build pcsx2 without issues I am not sure there is anything that can be done here.

**Comment by kylemiller3** [comment]
I've been building miscellaneous things so yes and I have no idea what fixed it or when so I can't really help @johnny-mac 's issue

**Comment by yoshi314** [comment]
On one of my systems, i had to specify directly path to wx-config. 

On gentoo it's e.g 

```
-DwxWidgets_CONFIG_EXECUTABLE=/usr/lib64/wx/config/gtk3-unicode-3.0-gtk3 -DGTK3_API=ON
```

**Comment by SimonMaracine** [comment]
I have a similar problem now with wxWidgets 3.1 and Ubuntu 18.04. I installed the dependencies with apt from here **https://repos.codelite.org/wx3.1.4/ubuntu/**. And it's saying that **wx/version.h file not found in /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.1-unofficial3;/usr/include/wx-3.1-unofficial**.

**Comment by yoshi314** [comment]
> I have a similar problem now with wxWidgets 3.1 and Ubuntu 18.04. I installed the dependencies with apt from here https://repos.codelite.org/wx3.1.4/ubuntu/. I use CMake and **find_package** to build. And it's saying that **wx/version.h file not found in /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.1-unofficial3;/usr/include/wx-3.1-unofficial**.
> 
Did you try similar  step as i did? Query the contents of your wxgtk package for the config binary and pass that as an arguemnt to the cmake, like in my example.

**Comment by SimonMaracine** [comment]
> > I have a similar problem now with wxWidgets 3.1 and Ubuntu 18.04. I installed the dependencies with apt from here https://repos.codelite.org/wx3.1.4/ubuntu/. I use CMake and **find_package** to build. And it's saying that **wx/version.h file not found in /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.1-unofficial3;/usr/include/wx-3.1-unofficial**.
> 
> Did you try similar step as i did? Query the contents of your wxgtk package for the config binary and pass that as an arguemnt to the cmake, like in my example.

No. What I ended up doing is install another wxWidgets package from apt that wasn't mentioned in the instructions and I don't know how, but it worked, there doesn't seem to be any problems and **find_package** finds somehow the correct version of wxWidgets, the one that I wanted (the latest one). IIRC, it was **libwxgtk3.1-dev**, but I'm not very sure. This one wasn't in the instructions.
