### ISSUE TITLE
[Feature Request] Auto Detect or Highlight the Newest Save State

### ISSUE THREAD

**Issue by irfantaufiq** [PCSX2/pcsx2#2913]
***The requested feature:***
I want a feature to auto-detect the **most recent save state** in each game, so the _save state slot_ will automatically switch to the most recent save state when the game start/boot (like in PPSSPP).

***The alternative:***
If it's not applicable, maybe highlight the **most recent save state** in **System > Load state** menu, so I don't need to check/compare the date of each save state. What I mean as highlight can be one of these (just example):
- using the bold text
- add asterisk in the end of datetime string

***The related issue:***
maybe related to issue #2073

Thanks in advance.

**Comment by vsub** [comment]
It may be ok for PPSSPP bug pcsx2 crashed plenty of times while trying to load a save state as soon as possible.
From then on,if I want to load a save state after running the game,I wait few seconds before pressing F3

One other probably simple alternative is to add some symbol on the left side or the save sate in the Save\Load menu
Something like this(only on the latest save so you will know what to load)

![2019-04-22_154206](https://user-images.githubusercontent.com/5032540/56506072-536ece00-6515-11e9-999a-809f07a7ab83.jpg)

**Comment by irfantaufiq** [comment]
An attempt to solve "The alternative" part of this issue can be shown in this commit:
https://github.com/irfantaufiq/pcsx2/commit/9901bf7cdb47337fa5da262ecd70db7ef77a90d5

Of course, I know this isn't a good/ideal solution, but, at least it's enough to show what I want.

**Comment by lightningterror** [comment]
> An attempt to solve "The alternative" part of this issue can be shown in this commit:
> irfantaufiq@9901bf7

Seems like a nice addition for 1.8 release, feel free to pr the changes, I would replace  `<==` with `New` maybe.

**Comment by RedDevilus** [comment]
Seems like it's partially fixed by this:
https://github.com/PCSX2/pcsx2/pull/4306

**Comment by refractionpcsx2** [comment]
Qt implements the ability to savestate at shutdown and will offer the option to resume from that savestate once you try to reload the game.

I think this is a sufficient solution to this problem.
