### ISSUE TITLE
GSDX: Mipmapping cause random crash in some games.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2916]
***PCSX2 version:***
1.5dev 3028

***GSDX Mipmapping problem.***

-It happen more frequently with OpenGL but DX is also affected.

-Jak and Daxter games need it but this "crash" issue affect those so...

***Description of the issue:***
Some games randomly crash PCSX2 with hardware Mipmapping causing it to shutdown itself with no visible errors.

Happen with Jak games, I will post more results later.

***How to reproduce the issue:***
Select the OpenGL hardware render and enable "basic mipmapping", load a problematic game and wait until PCSX2 crash.

***Not a regression.***

***PC specifications:***
AMD FX8350 - Nvidia GTX 1060 - Gskill 16gb

**Comment by lightningterror** [comment]
@atomic83GitHub can you upload a blockdump with a savestate?

**Comment by atomic83GitHub** [comment]
https://drive.google.com/open?id=1SEIwWQLm7oHkZBU2tBsHdwPOCTaA_pSb Here is the Jak blockdump you requested, the instruction are: -Put the JAK memorycard in solt 1, lunch the game with fast boot and select load save then wait in this place:

![555](https://user-images.githubusercontent.com/26351275/56360086-be519980-61e3-11e9-87e7-9c751b392059.PNG)

Don't forget to enable basic mipmapping.

**Comment by atomic83GitHub** [comment]
This is an image of how bad it is: my GPU reach 100% for a second then die.

![image](https://user-images.githubusercontent.com/26351275/57971410-f2a8a900-798d-11e9-9f7b-dcf681bc6f89.png)
