### ISSUE TITLE
Formula One 05 (Vif1: Unknown VifCmd! [3f])

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2918]
v1.5.0-dev-3030-g73e307271 

Getting a stutter in game and i kinda noticed that it happens if the internal resolution is set to 3x or higher 

Speed settings is set to third preset 

Getting this in the log when the slow downs or few second hang happen
Vif1: Unknown VifCmd! [3f]
Vif1: Unknown VifCmd! [3f]
Vif1: Unknown VifCmd! [3f]
Vif1: Unknown VifCmd! [3f]
Vif1: Unknown VifCmd! [3f]
Vif1: Unknown VifCmd! [3f]

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/3055502/emuLog.txt)

**Comment by atomic83GitHub** [comment]
Maybe the slowdown comes from the console spamming a ton of VIF unknown cmd error.

**Comment by lightningterror** [comment]
Yes it is possible for console logs to cause slow downs if they are spamming a ton, maybe we can enable the Vif logs on dev builds only.

**Comment by atomic83GitHub** [comment]
Well something strange is SONY don't hide those errors but have a toogle on/off cmd command, maybe those errors are important for an unknow reson as this time, enable them via INI instead?

**Comment by atomic83GitHub** [comment]
@Levan7 Can you say exactly who to reproduce your problem?

**Comment by lightningterror** [comment]
It happens when you enter pitstop. Actual races are fine.

**Comment by atomic83GitHub** [comment]
@lightningterror A meta issue would be better, thta's a common problem with some games, I will loook if the console loggign does indeed slowdown the game.

**Comment by refractionpcsx2** [comment]
Is this still an issue? Does the EE Timing Fix not resolve it?

**Comment by Levan7** [comment]
I couldn't reproduce the issue 
tested on v1.7.0-dev-466-gf1e2a2efb build

**Comment by MrCK1** [comment]
Thanks for testing, I'll close this then.
