### ISSUE TITLE
Devil May Cry rectangular window at top left

### ISSUE THREAD

**Issue by JanithaR** [PCSX2/pcsx2#2922]
***PCSX2 version:***
PCSX2 1.5.0-20190405225206 - compiled on Apr  5 2019

![image](https://user-images.githubusercontent.com/3599872/56034962-80b5c200-5d46-11e9-8a38-c9e8285a04ee.png)

***Description of the issue:***
I'm gonna jump right into the description here since everywhere I looked it is claimed that this issue is fixed including here https://wiki.pcsx2.net/index.php/Devil_May_Cry but for me, it's not.

***How to reproduce the issue:***
Just play Devil May Cry

***Last known version to work:***
I was using 1.4.0 and it had the same issue. When I looked for solutions I came across that this is now resolved in 1.5.0 dev builds.

***PC specifications:***
``Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 17134), 64-bit
	Physical RAM     =  8157 MB
	CPU name         =  Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Vendor/Model     =  GenuineIntel (stepping 09)
	CPU speed        =  3.191 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7fbae3ff
	x86EFlags        =  28100000
``

***Video plugin settings:***
![image](https://user-images.githubusercontent.com/3599872/56035278-59132980-5d47-11e9-99e5-4ad71386f70f.png)

**Comment by lightningterror** [comment]
Are you sure you grabbed and installed the latest build properly? The GSdx gui picture is from 1.4.
https://buildbot.orphis.net/pcsx2/

Anyway closing this since it's resolved in 1.5 builds.

**Comment by JanithaR** [comment]
> Are you sure you grabbed and installed the latest build properly?
Does that process involve anything extra other than replacing existing files in the older version's directory with the new ones?

**Comment by lightningterror** [comment]
You should install it in a new directory.
