### ISSUE TITLE
Feature Request:Add a command line or\and drag drop save states

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#2938]
Now that there is an "File..." option in the Load\Save state menus which allows you to choose any file,wouldn't be nice to add a command line too?

Drag-Drop support is also a really easy way to load the save state you want rather that open a menu and switch to the slot you want and the load it.

I don't know how to do it(don't know that language)but it's doesn't look difficult since you can load any file from the "File..." menu and pcsx2 already support dropping files over the main window(to run an image)

Maybe just check the extension of the file dropped in the main window and if it is a p2s,execute the "File=>select=>load save state" code rather than running it as a game

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by lightningterror** [comment]
Closing, trivial.
