### ISSUE TITLE
Feature request: GUI cleanup

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2940]
***Actual "problems" with the GUI:***

-The hack section contain a SuperVU only hack (which I think can be remove as persona games works on MicroVU).

![InkedCapture_LI](https://user-images.githubusercontent.com/26351275/56674403-46d7aa80-66ba-11e9-924f-8b749631e4b2.jpg)

-GSDX software parameter contain 2 unusefull checkboxes. Mipmapping don't have any problems on software and the edge antialiasing only improve image quality with no downsides.

![Capture](https://user-images.githubusercontent.com/26351275/56674412-4ccd8b80-66ba-11e9-8182-27a9c6159957.PNG)

***Request:***

Move the skipmpeg hack to the system menu as it's more a "feature" rather than a hack (even if it make some games playable).

![Capture3](https://user-images.githubusercontent.com/26351275/56674780-ebf28300-66ba-11e9-8410-f0fda7eda90f.PNG)

**Comment by pgert** [comment]
It really easy to get the GUI in english (which is better in circumstances like these),
 by temporarily moving (in your case) the fr_FR folder from the Langs folder.

Also fr_FR seems to lack a proper translation of "Boot ISO (full)" & "Boot ISO (fast)".
Care to take care of that?

Thumbs up for moving the skip MPEG hack to the system menu,
 even though I never use the feature myself.

**Comment by atomic83GitHub** [comment]
Thanks for the tip, I will update the topic with english menus. But yeah, I will work on frensh translation later.

**Comment by lightningterror** [comment]
It is a good idea to leave mipmapping, it's useful when testing mipmapping between hw/sw renderers.
I don't know for AA1, as for the skip mpeg hack if there are 0 db entries maybe, otherwise I dislike moving/spreading hacks in separate places.

**Comment by lightningterror** [comment]
I will close this as it was discussed that the options don't really need cleanup.
