### ISSUE TITLE
Feature request - keybind or mappable keybind to close/exit

### ISSUE THREAD

**Issue by klepp0906** [PCSX2/pcsx2#2941]
So after scouring the www for about ever, it seems that no clean/simple solution to this exists.

I use steam big picture from the couch, and as much as I love steams overlay - it simply doesnt play nice with emulators.

a solution for most is disabling it and binding an exit key via the emulator itself.  Or for the ones that have a RA core, using RA's menu to close it.

The one emulator thats preventing me from ditching it in its entirety is PCSX2.  I know its been requested before - but it was some time ago.

Figured id let the powers-that-be know that people are still hoping for what I assume is a fairly quick n easy addition relative to the kind of stuff you guys do.

Thanks for your time regardless, words really cant do it justice.

**Comment by arcum42** [comment]
We haven't forgotten about it, but it's not actually a quick and easy addition.

Pcsx2 doesn't actually know you have a game controller. All it knows is there's a plugin there that sends it information as if it was a ps 2 controller. That information could be coming from anything.

The plugin, OTOH, does know about the controller, but the information it sends back is fairly limited, and doesn't include "shut down the program". 

It's a little more complicated then that, in that some hard-coded information gets bounced around between the pad plugin, the gs plugin, and pcsx2 for a few function keys, but essentially the plugin api and the individual plugins and the program would need to be altered, and it's not trivial, or we'd have done it by now...

**Comment by klepp0906** [comment]
ah, thank you for elaborating a bit.   Does the same apply for a hardcoded bind to the keyboard?  This wouldnt cover EVERYONE but as a stopgap, cant you set a keyboard key such as F12 for example to shut down the emulator?

I know in my case (and most others playing from the couch) a means to rebind keys exist.  I can set any key on my controller to register as (for example) F12 which would close the emulator.

if the same explanation regarding plugin detection applies to the keyboard then i apologize.  

I know I do use the hardcoded savestate keys F1 and F3 i believe, mapped straight to my controller to handle states from the couch fwiw :)

either way, glad you havent forgotten.  Cliche but i hope to school my toddlers on the merits of retro gaming via this emulator one day and the couch is going to be paramount in that endeavor lol. (especially considering my age at that point)

**Comment by beefgrits** [comment]
I've been interested in this for a long time, and this is the most detailed answer I've seen on it yet. Seems it might be harder than just allowing the pad plugin to bind a simulated escape keypress to the ps/guide button or DS4 trackpad button?

**Comment by Wintermute0110** [comment]
Batocera Linux folks have implemented this feature in a patch, you can have a look [here](https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/pcsx2_avx2/004-hotkey.patch).

**Comment by RedDevilus** [comment]
Related to: https://github.com/PCSX2/pcsx2/issues/1082

**Comment by refractionpcsx2** [comment]
Qt lets you maps keys to close the emulator/window, so marking this as resolved.
