### ISSUE TITLE
Crash Tag Teams Racing: Character's shadow not displaying correctly

### ISSUE THREAD

**Issue by hibye8313** [PCSX2/pcsx2#2946]
Graphics issue:

Issue title: Crash Tag Team Racing (USA)

-PCSX2 version: v1.5.0-dev-3112 and v1.4.0 stable

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx (Direct3D 11 hardware but not software), SPU2-X, LilyPad, cdvdGigaherz, rest are null

-Plugin settings: All default GSDX settings, Direct3D 11 hardware, native PS2 resolution, CRC hack level automatic.

-Description: In the game when controlling Crash his whole shadow volume is visible as opposed to just the part that is projected onto the ground. (Pic and GS dump attached).

-How to replicate: Just load the game to a part where you are controlling Crash (I don't know if this occurs when you are cart racing or not).

-Last known version to work: Not known. The oldest version tested was PCSX 1.4.0 and it was having the same problem with Direct3D 11 hardware mode but not software.

-PC specifications (just a regular laptop, no upgrades): CPU: Intel Core i5-6200U @ 2.3Ghz, GPU: Intel HD Graphics 520, OS: Windows 10 Home v1803 build 17134 (64-bit)

Other comments: I ran into this issue while debugging a microVU problem with this game (issue #2903). I'm going to try and debug this as well, but I am completely unfamiliar with GSDX code base so it may take some time. Any pointers in the right direct would be very welcome.

Edit: sorry forgot attachments
![gsdx_20190430185626](https://user-images.githubusercontent.com/49872607/56999602-d6c79980-6b7d-11e9-9792-d66a849391a9.png)
[gsdx_20190430185626.gs.zip](https://github.com/PCSX2/pcsx2/files/3133463/gsdx_20190430185626.gs.zip)

**Comment by lightningterror** [comment]
What's the status on opengl?

**Comment by hibye8313** [comment]
Ah, unfortunately opengl does not work on my laptop =(. I just get a bunch of errors saying that features are not supported. I'm going to try updating my drivers to see if this fixes it and update the original post if so.

**Comment by lightningterror** [comment]
Dump doesn't show anything for me but looking at the picture it is accumulation blend like Crash of the titans.
Someone needs to port the feature to d3d11, opengl will render the shadows properly.
https://github.com/PCSX2/pcsx2/issues/1920
