### ISSUE TITLE
Two small cosmetics problems

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#2949]
Latest beta
1.If you try to enable "Recording Tools" but choose cancel,you get a log with what function was set to what key
If you choose Yes on that dialog,you don't get any informative log
If to disable  the option after that,then you get the same log as choosing Cancel

2.I don't know if there should be more menus later but if not...the screenshot menu is in a submenu and that Screenshot menu have only one menu(I don't see the point,it just makes it more difficult)

**Comment by lightningterror** [comment]
I'll take a look at the logs another time.

**Comment by lightningterror** [comment]
Will go ahead and close this since it's only a very minor issue/inconvenience.
