### ISSUE TITLE
SPU2-X can't open or save configuration file to non-default inis directory in Linux.

### ISSUE THREAD

**Issue by y-salnikov** [PCSX2/pcsx2#2950]
***PCSX2 version:***
pcsx2-git-1.5.0 master

***Plugins used:***
SPU2-x

***Description of the issue:***
When PCSX2 launched with --cfgpath option, SPU2-X plugin can't read or write corresponding ini file. Plugin writes error 2 messages to console and start with default settings.

***PC specifications:***
Arch Linux x86_64

**Comment by y-salnikov** [comment]
Update: Bug appear only when --cfgpath= with relative path used.

**Comment by RedPanda4552** [comment]
If I'm not mistaken, this argument _expects_ an absolute path, not relative? So trying to use a relative would be treated as absolute, in which case the directory will not exist and the subsequent read/writes will fail. Is this a request for a mode that allows relative paths instead of absolutes?

**Comment by y-salnikov** [comment]
Well, rest of the plugins and emulator itself understands relative path without problems.  And there is no reason to use only absolute path in command line options.
It is not critical and i just can use absolute path as workaround.

**Comment by RedDevilus** [comment]
Can you check if this is still an active issue? Since then all plugins have been integrated in the core.
