### ISSUE TITLE
Splinter cell chaos theory deson't show first video

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2955]
Splinter cell chaos theory doesn't shows the first new game cutscene you can hear the sound of the cut sense but it is stuck on this menu you can even skip it and the game runs just fine but it shows this screen. Using speed preset 3

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/3168852/emuLog.txt)

![sc](https://user-images.githubusercontent.com/5770076/57567837-49433f80-73f0-11e9-9299-56f51feb7245.gif)

v1.5.0-dev-3121-g079baaed9

**Comment by lightningterror** [comment]
> Bios Found: Europe  v01.60(04/10/2001)  Console
> Bios Found: Europe  v02.00(14/06/2004)  Console
> Bios Found: USA     v02.00(14/06/2004)  Console
> Bios Found: Japan   v01.00(17/01/2000)  Console
> Bios Found: USA     v01.60(07/02/2002)  Console

Sorry, we don't provide support for pirated content.

**Comment by Levan7** [comment]
@lightningterror  don't be a hypocrite

![IMG_20190516_2246349](https://user-images.githubusercontent.com/5770076/57879220-f53fbd00-782c-11e9-9406-3736a940a6bd.jpg)

**Comment by lightningterror** [comment]
People should be aware to use their own ps2 bios.

**Comment by prafullpcsx2** [comment]
Tested the game today with latest master and can't reproduce this issue. The game works fine.
