### ISSUE TITLE
PCSX2-GUI: "Change Language" have a language-flaw

### ISSUE THREAD

**Issue by pgert** [PCSX2/pcsx2#2957]
The dialog box poped up when choosing "Misc" > "Change Language" have a language-flaw.
The title (of the dialog) and the buttons uses the language currently in use,
 while the info-text itself is in english.
This dialog should use english only, yes?

**Comment by vsub** [comment]
It is just that the part of the gui you are looking at is not translated(by the person that did the translation to your language)into your language and everything not translated us using English.

Just for example check Japanese...everything is translated there

**Comment by pgert** [comment]
You don't get it.
NOTHING should be translated - It shoould all be in English, yes?

**Comment by tadanokojin** [comment]
Not according to the language selectors I've used.

**Comment by pgert** [comment]
> 
> 
> Not according to the language selectors I've used.

And that is just the point - The dialog should be all in English.

**Comment by tadanokojin** [comment]
> And that is just the point

What?

That's fine if that's your opinion but you need to provide a reason if you really want to see it done. Simply saying "it should be this way" isn't good enough pgert especially when you're asking to do this when all or nearly all of our contemporaries don't.

**Comment by feikname** [comment]
"And that is just the point - The dialog should be all in English regardless of what language that is currently in use."

All text should be in the selected language, any text that is in english even though you selected another language is a missing translation.

**Comment by pgert** [comment]
> 
> That's fine if that's your opinion but you need to provide a reason if you really want to see it done. Simply saying "it should be this way" isn't good enough pgert especially when you're asking to do this when all or nearly all of our contemporaries don't.

Well, since the menuoption is in English (regarsless of interface-language settings, shouldn't the dialog also be all in English?
The menuoption-string does not enable translation, btw.

**Comment by tadanokojin** [comment]
Do you mean the combo box? Honestly they should probably be in whatever language is represented by the text (For example Japanese should be 日本語) That seems to be what I see in most interfaces I use.

**Comment by lightningterror** [comment]
You could argue that both translating and not translating are correct choices tbh, anyway is this really an issue?

**Comment by tadanokojin** [comment]
>You could argue that both translating and not translating are correct choices tbh

No, I don't think so. The point of UX is that people recognize patterns and when you present them with something that doesn't meet their expectations it becomes confusing.

The window should be in the current interface language and the drop down should include a list of language names in the language they represent (regardless of interface language).

That's what just about everyone else does, I think it's what we should do to.

**Comment by tadanokojin** [comment]
Some examples:

Dolphin
![002884](https://user-images.githubusercontent.com/26046960/57745244-5f742880-769a-11e9-997a-098ed48a2978.png)

Anki
![002885](https://user-images.githubusercontent.com/26046960/57745245-5f742880-769a-11e9-82a7-45ca10e44c31.png)

Chrome appears to translate the language names and FF appears to leave them in English. The interface is pretty consistently in the current language in most applications I use. Can't recall an example where the language selection interface is in English regardless.

For me this isn't an issue as it's consistent with what I see elsewhere.

**Comment by lightningterror** [comment]
Yeah our display is correct.

> The drop down should include a list of language names in the language they represent (regardless of interface language)

Seems like a thirdparty wx issue that we don't really need to worry about
https://github.com/PCSX2/pcsx2/blob/master/3rdparty/wxwidgets3.0/src/common/languageinfo.cpp#L556

**Comment by tadanokojin** [comment]
Yeah I won't worry about it if it's a Wx thing. Seems QT just handles it differently.

**Comment by lightningterror** [comment]
Gonna close this since it's not an issue.
