### ISSUE TITLE
Samurai Warriors 2 Xtreme Legends Keiji's story black screen

### ISSUE THREAD

**Issue by Moondrag** [PCSX2/pcsx2#2958]
development build v1.5.0 3121

Attempting to start Keiji's third stage in PCSX2 (When using either the unlock all story modes code, which has it's own problems, likely do to not having the files on the duel layer since the game only checks for the Serial number file when doing importing) causes the game to freeze on a black screen with the stage's music playing in the background. Apparently this blackscreen happens in some of the Dream stages as well but at the end of them instead, so it might be related to how the emulator handles in engine cutscenes or how the emulator handles reading the second layer since the stage works fine in the original Samurai Warriors 2. 

I have not tested the unlock all story modes code on original hardware, mainly since my PS2 isn't exactly in working order and I don't have the needed cheat device...here is the Unlock all story modes pnach code for anyone who wants to test it themselves.
patch=1,EE,2029C414,extended,24030001

CPU: Intel Core i7-4790 3.60 GHz GPU: NVIDIA GeForce GTX 1060 6GB OS: Windows 10 64 Bit

**Comment by MrCK1** [comment]
@Moondrag can you post a log from when the freeze occurs?

**Comment by Moondrag** [comment]
Here's the log. I turned on all the sources just to be safe (Don't mind the folder names. I'm a little lazy and didn't really change where I put the emulator or the folder's name)
[log.txt](https://github.com/PCSX2/pcsx2/files/4048915/log.txt)

**Comment by lightningterror** [comment]
```
isoFile open ok: C:\Users\w_rey\Downloads\PS2\ISOs\Warriors\Samurai Warriors\Samurai 
Warriros 2 XL USA.iso
```

Sorry, we don't support piracy.
