### ISSUE TITLE
GSdx: Cutscenes overlay on Final Fantasy games

### ISSUE THREAD

**Issue by NTZ1989** [PCSX2/pcsx2#2961]
Windows 10 Pro build 1809 17763.475 + Ryzen 1700 + RAM 24Gb + GTX 980ti driver ver. 418.91

As related previously on thread #2890 FF games display overlays showing elements of the scenery or opacity characters during almost all cutscenes in-game. I've been doing many tests and I was able to find out when exactly the issue has started, from PCSX2 ver. 1.5 2975 until the latest version 3126, playing the game using any version from 2970 or below this issues doesn't happen.

FF xii (USA) SLUS_209.63;1
![FF XII overlay 1](https://user-images.githubusercontent.com/39391129/57828151-e13e8180-7780-11e9-82f1-94d3b9081266.png)

![FF XII overlay 2](https://user-images.githubusercontent.com/39391129/57828156-e7ccf900-7780-11e9-8aeb-a7d0329ad1e6.png)

![FF XII overlay 3](https://user-images.githubusercontent.com/39391129/57828157-eb608000-7780-11e9-84b7-1269e3e1c7cb.png)

FF X (USA) SLUS_203.12;1
![FF X overlay 1](https://user-images.githubusercontent.com/39391129/57828910-88bcb380-7783-11e9-98ef-7fdd23d64536.png)
![FF X overlay 2](https://user-images.githubusercontent.com/39391129/57828914-8ce8d100-7783-11e9-9a6f-9bdfd0fd873b.png)
![FF X overlay 3](https://user-images.githubusercontent.com/39391129/57828921-940fdf00-7783-11e9-9ce6-a7838efb6a5e.png)

**Comment by tadanokojin** [comment]
> As related previously on thread #2890

Why a new issue then? Is there some reason not to update #2890 instead?

**Comment by NTZ1989** [comment]
I dunno, the thread #2890 seemed a bit vague and I did further tests including another FF game, anyway if this thread is considered incorrect to you feel free to close it. Just to update I've finished the Final Fantasy X SLUS_203.12 completely using the version 1.5.0 dev 2970, no overlays or opacity, the cutscenes are displayed correctly, I just noticed some audio delay on some cutscenes but it seems something related to the game.

**Comment by raymonders** [comment]
Hi all. Was redirected here from reddit. Using the 2970 build on FF XII and am still experiencing this graphics bug, soooooo i dunno what it could be.

> https://www.reddit.com/r/PCSX2/comments/bqu40w/help_ffxii_has_some_upscaling_issues_maybe/

**Comment by NTZ1989** [comment]
Hello @raymonders , weird the 1.5.0 dev 2970 worked fine to me, I don't see those ghosts or scenery overlay running the game on this version of the emulator but I'll try to get on the spot that you took the prints and check if it happens with me either. Could you try to run the game using versions below from 1.5 2970?

**Comment by raymonders** [comment]
Hello @NTZ1989 ! I have also had the same cutscene issue as the ones in this thread (taken at the start of the game FF XII), my screenshots were taken during the magicite robbery near the beginning of the game as well. 

So I did some testing, and it seems to be a plug-in issue.
Tests done using builds 2965, 2970 & 3135:

Running 2965 with 2965 plugins = no problems
Running 2965 with 2970 plugins = PROBLEMS
Running 2965 with 3135 plugins = WORSE Problem, the overlay is darker

Running 2970 with 2965 plugins = no problems
Running 2970 with 2970 plugins = PROBLEMS
Running 2970 with 3135 plugins = Darker overlays

Running 3135 with 2965 plugins = no problems
Running 3135 with 3135 plugins = PROBLEM

I don't know how often you update the plugins folder, but it seems to me that that may have something to do with it. In the meantime, I'll be playing using the newer build but with older plugins. Thanks and good luck!

**Comment by NTZ1989** [comment]
I've tested playing the FF XII version SLUS_209.63 on PCSX 1.5.0 dev 2970 until the part you took the prints and I didn't get those overlays or opacity characters, sceneries... I did some records to show how good the game runs on 1.5.0 dev 2970 maybe it is something related to your system, your drivers are updated?  

FF XII Part 1 - https://youtu.be/Q7OU9w8Lrec
FF XII Part 2 - https://youtu.be/SoQEloMYFQI
FF XII Part 3 - https://youtu.be/hXUyax3Nmdg
FF XII Part 4 - https://youtu.be/kMHRoBZxg90
FF XII Part 5 - https://youtu.be/mIluULvsx1U

I don't know if it'll help you but I'll attach the setting that I use on my emulator probably they aren't too different than yours but it can give you a clue of what is happening, my emulator is in portuguese but the position on the menu keeps the same.

![Emulator settings part 1](https://user-images.githubusercontent.com/39391129/58517380-93af1500-8181-11e9-8bfa-710e092b390d.png)
![Emulator settings part 2](https://user-images.githubusercontent.com/39391129/58517385-97db3280-8181-11e9-91b9-e3be1e35fc50.png)
![Emulator settings part 3](https://user-images.githubusercontent.com/39391129/58517392-9c075000-8181-11e9-80ba-be4973aa6473.png)
![Emulator settings part 4](https://user-images.githubusercontent.com/39391129/58517398-9f024080-8181-11e9-8490-39543f6bd603.png)
![Emulator settings part 5](https://user-images.githubusercontent.com/39391129/58517400-a1fd3100-8181-11e9-8378-8ad7cc57fd67.png)
![Emulator settings part 6](https://user-images.githubusercontent.com/39391129/58517402-a4f82180-8181-11e9-9401-a0c28a026b00.png)

**Comment by NTZ1989** [comment]
Nice to know that, thank you to share this information. personally, I don't update the plugins, I just use those that come together with the emulator, I don't use any external plugin either...

**Comment by NTZ1989** [comment]
I can confirm the problem still persist on 1.5.0 dev 3135

**Comment by raymonders** [comment]
>I've tested playing the FF XII version SLUS_209.63 on PCSX 1.5.0 dev 2970 until the part you took the prints and I didn't get those overlays or opacity characters, sceneries... I did some records to show how good the game runs on 1.5.0 dev 2970 maybe it is something related to your system, your drivers are updated?

Thank you for taking the time to play the game and everything! I cannot explain why 2970 is giving me problems. Thankfully I have found a way around it. 

> I just use those that come together with the emulator, I don't use any external plugin either...

That gave me the problems with 2970 unfortunately

> I can confirm the problem still persist on 1.5.0 dev 3135

Yes i noticed that. But if i use the plugins from the dev 2965 plugin folder (overwriting the dev 3135 folder) the problem disappears. So I'm playing like that now.

Thank you again for your time and effort @NTZ1989 !!

**Comment by lightningterror** [comment]
It is a known issue already which is a gsdx regression.

**Comment by MrCK1** [comment]
Does the issue go away if FXAA is disabled?

**Comment by NTZ1989** [comment]
@MrCK1  no, I tried to disable every filter, this issue isn't related to something graphical otherwise disabling everything would prevent it to happen, the user Mensa41 at the thread #2890 said something that I found interesting:

"Bad Screen Overlay in some areas in both Ogl and Dx11.
This issue doesn't happen in **software mode**
PCSX2 options:
Default Settings, no widescreen or cheats enabled."

He also reported the last version that worked fine to him was **1.5 Dev 2656**, while for raymonders only from **1.5 Dev 2965** below and to me, the last version working fine on FF was **1.5 Dev 2970**. So we can assume that not all emulators versions render the cutscenes in the game properly to all users. **This is just an assumption**...

**Comment by NTZ1989** [comment]
I've decided to give a try what @MrCK1  said about disable some filters and I found out a curious thing...

I used the emulator version 1.5.0 Dev 3135 and after many tests, I think was able to find what is causing these issues, just follow my screenshots and I think you'll be able to reproduce the same result as mine:
1- **No screen patch**
![emu 1 5 0 dev 3135 no overlay settings part 1](https://user-images.githubusercontent.com/39391129/58528115-b48c6000-81ab-11e9-81b9-f624974d771a.png)
2 - **Dx11 hardware mode and everything else OFF or under recommended settings**
![emu 1 5 0 dev 3135 no overlay settings part 2](https://user-images.githubusercontent.com/39391129/58528146-cd951100-81ab-11e9-8996-6aaabfcb294b.png)
3 - **Shader config - Everything OFF/Unmarked**
![emu 1 5 0 dev 3135 no overlay settings part 3](https://user-images.githubusercontent.com/39391129/58528260-4ac08600-81ac-11e9-9f4f-3ae1c3b53ea3.png)
4 - **Specs 4:3 | off FMV aspect ratio**
![emu 1 5 0 dev 3135 no overlay settings part 4](https://user-images.githubusercontent.com/39391129/58528488-041f5b80-81ad-11e9-8a62-18f842bb2f91.png)
5 - **First test playing the initial cutscenes in-game, it renders them perfectly, no overlays, opacity(though the graphics look like shit)...**
![emu 1 5 0 dev 3135 no overlay settings part 5](https://user-images.githubusercontent.com/39391129/58528538-42b51600-81ad-11e9-8f92-e7ffeefba5b8.png)
6 - **Exactly the same settings as before, just testing under OGL Hardware mode.**
![emu 1 5 0 dev 3135 no overlay settings part 6 just change OGL](https://user-images.githubusercontent.com/39391129/58528945-23b78380-81af-11e9-9362-48ecac1d09fd.png)
7 - **As you can see the game still renders the cutscenes in-game perfectly fine even under OGL.**
![emu 1 5 0 dev 3135 no overlay settings part 7 testing on OGL](https://user-images.githubusercontent.com/39391129/58528981-4e094100-81af-11e9-841a-dc57acf6fdf9.png)
8 - **I've returned the renderer to Dx11 Hardware Mode but I changed the Internal Resolution, the others settings I kept Default/OFF or under recommended**
![emu 1 5 0 dev 3135 no overlay settings part 8 changing just the resolution under Dx11](https://user-images.githubusercontent.com/39391129/58529185-25357b80-81b0-11e9-81ed-e497cc7a8986.png)
9 - **When you change the value at Internal Resolution to any other than Native option or you set a Custom resolution it causes the emulator starts to overlay sceneries, characters, there is something wrong at the Internal Resolution that when changed from its default value causes this issue on FF games. So keep it to its default value Native makes the emulator workes completely fine and renders the scenes correctly - This issue happens under both OGL and DX hardware Mode when the Internal Resolution is changed its default value or a custom resolution is set.** 
![emu 1 5 0 dev 3135 overlay part 9 something related to internal resolution happens on both OGL and Dx11](https://user-images.githubusercontent.com/39391129/58529228-6594f980-81b0-11e9-886f-433c650c5fc7.png)

**Comment by NTZ1989** [comment]
**Updating** - I could find another way to fix this issue on Internal Resolution, just change the value of Texture Filtering that comes by standard on Bilinear(PS2) to Nearest and all problem are solved, you can turn ON any filter that it won't cause the emulator renders bad scenes but it gonna shut down Anisotropic Filtering - All others different options than Nearest break the cutscenes when an Internal resolution is set.

**Comment by gregory38** [comment]
We are working on it. We understand the issue but it is fairly complex.

**Comment by NTZ1989** [comment]
@gregory38  Thanks! while you re developing a solution, the people who are experiencing those overlays on FF games can use these settings as a palliative:
![save settings for FF games](https://user-images.githubusercontent.com/39391129/58567904-a40ad280-8209-11e9-9ebf-9508b7528b56.png)

**Comment by lightningterror** [comment]
Latest build should be good now.

**Comment by NTZ1989** [comment]
@lightningterror thanks, the problems were completely solved!

**Comment by RenatoMQSantos** [comment]
I'm using the new one, i extracted the emulator in a new folder, same Issue. It only works fine when i set resolution as nativePs2, but the game looks realy bad this way.

**Comment by refractionpcsx2** [comment]
I suggest trying the half pixel offset hw hack then and see if that fixes it. If not please post on our forum or join the discord, Github is not for support.

All links can be found on https://pcsx2.net
