### ISSUE TITLE
GSdx incorrect Line upscaling in OpenGL

### ISSUE THREAD

**Issue by Kazeira** [PCSX2/pcsx2#2964]
***PCSX2 version:***
v1.5.0-dev-3127-g87808fee0

***PCSX2 options:***
All default, Resolution higher than native, Disable Safe Features unchecked

***Description of the issue:***
The line rendering upscaling in OpenGL isn't as good as DX11 and looks "broken".
This is especially noticeable when they are moving, as in the Sly trilogy where black lines are used for cel shading.
Can also be observed in Metal Gear Solid 2's codec.

Sly 3 Sly's outlines and logo:
(Round Sprite: not required for DX11, half for OpenGL, Full is better for both)
![Sly line rendering 1](https://user-images.githubusercontent.com/32652514/57952199-b96c2c80-78ec-11e9-9192-7d361cc5fa67.png)
![Sly line rendering 2](https://user-images.githubusercontent.com/32652514/57952200-b96c2c80-78ec-11e9-8ed1-b0a203f8704a.png)
![Sly line rendering 3](https://user-images.githubusercontent.com/32652514/57952201-ba04c300-78ec-11e9-839b-2ebf795d3974.png)

***How to reproduce the issue:***
Nothing in particular, playing games using lines and compare between OGL and DX11.

***PC specifications:***
CPU: Intel i7 8700k GPU: GTX 1080Ti OS: Windows 10 64 Bit)``

**Comment by gregory38** [comment]
Is it a recen behavior for gl ? Could you try various level of accurate blending

**Comment by Kazeira** [comment]
I've noticed this long ago (years?), since I generally use exclusively OGL for GSdx this is only recently I've seen that DX11 is correct, but I don't know if it's recent.
I've already tried it, no changes noticed.

**Comment by gregory38** [comment]
Did you try blending off ?

My feeling is that I miss some barriers because I was careless for point and line. So you have some  corruption. It is even tricker as unscaling (no safe hack) might overlap pixels that wouldn't in the first place.

**Comment by Kazeira** [comment]
Sorry, none of the values ​​have any effect.
