### ISSUE TITLE
Gsdx Flickering Elements (Software & Hardware) : DDR Games (possibly others)

### ISSUE THREAD

**Issue by kevhensen** [PCSX2/pcsx2#2966]
***PCSX2 version:***
``stable build v1.4.0 and development build v1.5.0-dev-3128 or older``

***PCSX2 options:***
``All defaults.``

***Plugins used:***
GSdx plugin, with following settings :

Renderer : (any)
Interlacing : (any)
Texture Filtering : (any)

**-Hardware Renderer Settings-**
Allow 8-Bit Textures : on/off
Large Framebuffer : on/off
Internal Resolution : (any)
Mpmapping : (any)
CRC Hack Level: (any)
Accurate Date : (any)
Accurate Blending : (any)

**Note**: "(any)" means all possible settings were tried

***Description of the issue:***
``Some graphical elements flickers of all sorts of color (green, white, black, blue and red mostly) and distracts from the gameplay. The exact behaviour differs depending on the element (disappearance, color change, transformation). The problem is similar across multiple games and affects DDR SuperNova, DDR SuperNova 2 and DDR X (DDR Max 2, Extreme and Extreme 2 are not seemingly affected). ``

***How to reproduce the issue:***
``Can be seen on many menus and text during gameplay. Some examples below.``
``DDR SuperNova : Game Mode -> Single -> All Music -> Battle Without Honor Or Humanity (or any other song)``
``DDR SuperNova 2 : Game Mode (issues can already be seen in the menu)``
``DDR X : Game Mode -> Single -> Random/All -> Stardard (issues can already be seen in the menu)``

***Last known version to work:***
``No previous version works.``

***PC specifications:***
``Not host-dependent (tested on multiple PCs : NVIDIA/Intel/AMD, Windows 7/10)``

***GS dump:***
https://drive.google.com/open?id=1wBnoIyIUtxk_1SlTTkWfiQIy_6fKCsf6
**Note**: GS dumps provided for DDR SuperNova game (if more data needed from other games or same game, feel free to ask).

***Screenshots:***
![gsdx_quickSaveMenu_opened_single2](https://user-images.githubusercontent.com/50850536/58065808-eae73100-7b54-11e9-8754-c4a4ed08a967.png)
![gsdx_quickSaveMenu_opened_single3](https://user-images.githubusercontent.com/50850536/58065809-eae73100-7b54-11e9-9cca-8aebdf6793ab.png)
![gsdx_quickSaveMenu_opened_single1](https://user-images.githubusercontent.com/50850536/58065807-eae73100-7b54-11e9-8ee1-c0f9e6085d31.png)
![gsdx__bottomScoreBar_single](https://user-images.githubusercontent.com/50850536/58065806-eae73100-7b54-11e9-8106-6b74f7846f52.png)
![gsdx_resultBar_single](https://user-images.githubusercontent.com/50850536/58065810-eb7fc780-7b54-11e9-82a3-bdb675e10541.png)

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by MrCK1** [comment]
This sounds more like an interlacing setting issue, press F5 or change the interlacing setting in GSdx.

DDR games are very flickery with some of the interlacing modes.

**Comment by kevhensen** [comment]
Hi MrCK1,
I just retried all interlacing modes and unfortunately, the flickering still persists (and on the same elements).

**Comment by MrCK1** [comment]
@kevhensen Can you let us know if this issue is still present in the latest dev build? Thanks.

**Comment by kevhensen** [comment]
The issue was still present at the time you wrote your message and until recently, but I happily confirm it is gone in the latest development build.
Thank you!

**Comment by refractionpcsx2** [comment]
It would be cool if you could check when it was fixed, just so we know in future if it crops up again :)

**Comment by kevhensen** [comment]
@refractionpcsx2
I cannot ensure that all of the display problems in this issue were related, but the first commit that showed none of the problems mentioned in this issue is PR#4726.

**Comment by refractionpcsx2** [comment]
oh cool, so probably PATH3 masking stuff, thanks for checking :)

**Comment by kevhensen** [comment]
No problem, thank you! :)
