### ISSUE TITLE
Shin Megami Tensei - Digital Devil Saga: Player shadows don't render if widescreen patches are enabled

### ISSUE THREAD

**Issue by Sandvichero** [PCSX2/pcsx2#2968]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3128-gc6fcf0aaa

***PCSX2 options:***
Tried many options including all levels of crc hacks and the issue still persists

***Description of the issue:***
If widescreen patches are enabled player shadows don't render in gameplay
Widescreen patches on
![Screenshot (2)](https://user-images.githubusercontent.com/26612410/58129024-dfdce100-7be6-11e9-99e4-7633d727d8e4.png)
Widescreen patches off(Stretched)
![Screenshot (3)](https://user-images.githubusercontent.com/26612410/58129147-19155100-7be7-11e9-8877-709c28093788.png)

***PC specifications:***
CPU: Intel Core i7-8700K GPU: Nvidia GeForce RTX 2080

**Comment by MrCK1** [comment]
If the widescreen patch causes the issue, then it's not our problem (since they're a hack in itself). You'll have to consult the patch thread here: https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=599535#pid599535

**Comment by CrimsondarkFira** [comment]
Heya, if you don't mind could you let me know where can i get the widescreen patch?
