### ISSUE TITLE
LilyPad: add native DualShock 4 support

### ISSUE THREAD

**Issue by 13xforever** [PCSX2/pcsx2#2970]
Currently it is only possible to use DS4 as a DirectInput device (and lose Force Feedback option), or as an XInput device (requires 3rd party wrapper such as DS4Windows or Steam).

There are multiple implementations of native DS4 handler out there (i.e. one from [RPCS3](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/ds4_pad_handler.h)), which are cross-platform, and do not require 3rd party USB drivers (unlike native DS3 handlers).

On the plus side we get: full feature support, including Force Feedback, auto bindings (similar to xinput) and better support than through evdev on Linux.

**Comment by MrCK1** [comment]
In my experience, launching through Steam works fine with a DS4 and allows it to be used as an XInput device. 

I'm not really sure how "native" support is nice different from existing solutions.

**Comment by 13xforever** [comment]
I mentioned Steam :-/
As for the "different", how about you're not depending on Steam with the native handler. Especially with Steam. By default you get an awful Desktop configuration that messes with inputs more than it helps, and most people won't even bother to configure anything.

**Comment by KrossX** [comment]
So the only advantage for this is to have rumble without a third party thing ? Seems like quite the lot of work just for that. Still, someone might be interested in coding it.

That reminds me, there's a ff driver for xinput controllers that give them rumble under DirectInput. It seems there's enough information to do the same for DS4 controllers, if it ain't already done that is.

**Comment by atomic83GitHub** [comment]
This is a Windows only issue, in Linux the controller is already fully supported.

**Comment by arcum42** [comment]
That's implied by it saying "LilyPad" in the title. While LilyPad technically compiles on Linux, everyone uses onepad or onepad-legacy.

**Comment by kenshen112** [comment]
I mean there's other advantages. You get native pass through audio. easier access to the niche features like the Gyro (Not that the PS2 would ever really use that?) and the analogue trigger's which could be used to simulate pressure sensitive buttons in some cases I guess.

**Comment by atomic83GitHub** [comment]
I change my opinion about this, native support would be great but is low priority for now.

**Comment by atomic83GitHub** [comment]
I investigated the RPCS3 native mode and in reality, it's not technicaly native, it use official SONY ps now drivers. Better use DS4Windows at this point.

**Comment by 13xforever** [comment]
Um no? DS4 has native handler. DS3 is using PS Now driver on Windows.

**Comment by atomic83GitHub** [comment]
You are right for the dualshock 4, I was looking for dualshock 3 sorry for the confusion but anyway, DS4Windows allows you to fully use your DS4 potential even with PCSX2 such as sixaxis, touchpad etc... In that way, why do you want native mode.

**Comment by mirh** [comment]
> even with PCSX2 such as sixaxis, touchpad etc...

None of that is really relevant for ps2 emulation though (albeit they are still additional possible controls)

> Dualshock 3 in PCSX2 already support PS now drivers

We don't support the advanced features (that a rpcs3 guy [allegedly](https://github.com/RPCS3/rpcs3/issues/1034#issuecomment-510776189) said were there) from it though. I mean, pressure sensitive buttons are always important. 

Anyway, I guess like none of this would hurt.. Put aside that as soon nefarius releases his incoming ultimate® dualshock driver, that should have priority.

**Comment by mirh** [comment]
Ladies and gentlemen please provide some feedback in here
https://forums.pcsx2.net/Thread-Native-Windows-Bluetooth-drivers-for-PlayStation-3-Peripherals-WIP

**Comment by dezraj** [comment]
I just would like to add that DuckStation is another example of emulator which currently supports the vibration feature of the DS4 with native Windows Direct Input drivers. In DuckStation's inputs configuration the back-end is set to SDL, so perhaps that would have to be implemented first on PCSX2 to get the rumble working on the PS4 controller in Windows?

**Comment by lightningterror** [comment]
Supported in Qt, won't be in wx.

**Comment by dezraj** [comment]
> Supported in Qt, won't be in wx.

That's really great news!

Just out of curiosity, it won't be supported in wx because it is a limitation of this interface or because it would be useless work since the project is moving to Qt?

Anyway, thank you for your work with PCSX2.

**Comment by RedDevilus** [comment]
Partially because WX sucks and other reason would be useless if it gets ripped soon-ish with Qt anyway.
