### ISSUE TITLE
Shift key doesn't registered with numerical keys in Linux

### ISSUE THREAD

**Issue by y-salnikov** [PCSX2/pcsx2#2971]
***PCSX2 version:***
1.5.0-dev git master

***Description of the issue:***
Looks like shift key not registered with numerical ( and maybe other non-special) keys in linux. Shift with tab or F-keys works fine. By default there is no such key combinations. Found bug when tried to add my hotkeys.

***PC specifications:***
OS: Arch Linux 64-bit

**Comment by RhythmLady** [comment]
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by eckso** [comment]
Tested on Windows7 SP1 x64 and Shift-F1 didn't work (but other F-keys did)

Also confirmed Shift-KP_x combinations are not registered.

**Comment by Mrlinkwii** [comment]
is this still an issue on latest  master?

**Comment by lightningterror** [comment]
This was a wx issue, shouldn't be a problem on qt.
