### ISSUE TITLE
Bug or feature? Direct savestates slot access keys available only when recording tools enable.

### ISSUE THREAD

**Issue by y-salnikov** [PCSX2/pcsx2#2972]
***PCSX2 version:***
1.5.0 git-master

***Description of the issue:***
There is block of code in pxsx2/gui/FrameForGS.cpp that assign hotkeys for direct save (SHIFT+NUMPAD\<N\>) and load (NUMPAD\<N\>) savestate to/from corresponding slot. But that code is #ifndef'ed out if recording tools are not set to build. Shouldn't these keys be enabled by default?

**Comment by lightningterror** [comment]
`#ifndef DISABLE_RECORDING` means run code if DISABLE_RECORDING is not defined which isn't currently.

The hotkeys work properly assuming you have Recording Tools enabled.
TAS is still an experimental feature which is why it works like this currently, this includes the hotkey control.
