### ISSUE TITLE
Ratchet: Gladiator: Broken Textures after opening/closing startmenu

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#2978]
***PCSX2 version:***
PCSX2 1.5.0-0 - compiled on May 26 2019

***PCSX2 options:***
MTVU Enabled
Settings: (Safest makes no difference)
![emu_cfg](https://user-images.githubusercontent.com/30773753/58751189-ed1d8980-848a-11e9-8fd7-8ec2145423b6.png)

GSdx:
![gs_window](https://user-images.githubusercontent.com/30773753/58751177-bd6e8180-848a-11e9-8c8a-91cc50eb70a6.png)

***Plugins used:***
See GSdx screenshot

***Description of the issue:***
If the startmenu is opened & closed, some parts of the graphic disappears and the rest also isn't shown properly anymore.
![rc_okay](https://user-images.githubusercontent.com/30773753/58751385-4686b800-848d-11e9-8ebd-76f3d0833c5c.png)
![rc_menu](https://user-images.githubusercontent.com/30773753/58751395-52727a00-848d-11e9-952b-5f96047bd4e6.png)
![rc_bugged](https://user-images.githubusercontent.com/30773753/58751396-569e9780-848d-11e9-831b-efa4c7ccb441.png)

***How to reproduce the issue:***
For me, it's 100% reproducible (with the save-file (=memory card): https://www.file-upload.net/download-13622803/MemCard32MB.ps2.html):
1. Start Game, load save
2. Open Startmenu,
3. Close Startmenu
4. Graphics are broken now.

PCSX2-log:
https://pastebin.com/RH1hKvn2

***Last known version to work:***
Unknown, stable (1.4) has the same issue

***PC specifications:***
- Linux Mint Cinnamon x64
Detailed:
https://gist.github.com/XXXBold/007546b9d2e8020dec84795f09e63a30

**Comment by willkuer** [comment]
Pressing F9 twice fixes the issue?

**Comment by XXXBold** [comment]
If I start the game & enable Software mode directly: I can open & close the menu, the Textures stay fine.

If I start normal (in HW-mode) and make the bug occur, I cannot fix it afterwards with switching to SW mode.

**Comment by Dreadmoth** [comment]
Probably the same issue as #2088.
If so, this may fix it for you:
> Enabling Fast Texture Invalidation hack (preferred option) or Disable Depth Emulation hack seems to prevent this issue from occurring in both games. It won't restore the graphics to normal if the issue has already occurred - rebooting the game or loading a memory card save seems to be necessary in that case. 
> If a save state is made after the issue has occurred, the issue will persist if the save state is loaded (even after changing settings and rebooting) - a memory card save must be loaded to fix it.

I think those options are under the "Advanced Settings" tab. Check "Enable User Hacks".

**Comment by XXXBold** [comment]
> Probably the same issue as #2088.
> If so, this may fix it for you:
> 
> > Enabling Fast Texture Invalidation hack (preferred option) or Disable Depth Emulation hack seems to prevent this issue from occurring in both games. It won't restore the graphics to normal if the issue has already occurred - rebooting the game or loading a memory card save seems to be necessary in that case.
> > If a save state is made after the issue has occurred, the issue will persist if the save state is loaded (even after changing settings and rebooting) - a memory card save must be loaded to fix it.
> 
> I think those options are under the "Advanced Settings" tab. Check "Enable User Hacks".

Indeed, seams it's the same issue as you referenced. I can fix it with both the Fast Texture invalidation or the Disable Depth Emulation (However, the 2nd causes some other (minor) graphical bugs). Probably this should be added as an automatic fix for this specific game (And RC3, as mentioned in the other issue)? I'm not sure how it works technically, but there are "game specific fixes" available, might it belong there?

**Comment by lightningterror** [comment]
Closing as Duplicate.
