### ISSUE TITLE
pcsx2 fails to compile with lto

### ISSUE THREAD

**Issue by javashin** [PCSX2/pcsx2#2979]
https://github.com/InBetweenNames/gentooLTO/issues/339

**Comment by CookiePLMonster** [comment]
Is this still relevant, since the linked issue is closed?

**Comment by javashin** [comment]
i guess not there is a new gcc version probably fixed too we need to test with new gcc closing .

**Comment by javashin** [comment]
seems to be impossible compile pcsx2 with lto on gentoo with cflags=-march=native -O3 -flto=3 -fuse-linker-plugin -pipe
with gcc 9.1.0 and 9.2.0

ICE   /var/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/plugins/GSdx/PSX/GPUDrawScanline.cpp:78:1: internal compiler error: Segmentation fault

**Comment by javashin** [comment]
im going to emerge 8.3.0-r1 just to compile wuth lto

**Comment by arcum42** [comment]
Well, ice and segmentation fault errors in gcc are by definition gcc issues, not issues with our code. The compiler should never segfault, regardless of what code you give it.

I'd test in 9.2, but it came out yesterday. I'm surprised gentoo is already running with it.

**Comment by F0bes** [comment]
Using -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON has worked for me.
Is this still an issue?

**Comment by alucryd** [comment]
> Using -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON has worked for me. Is this still an issue?

Still an issue on Arch Linux without the above flag, it works fine with the flag though.

**Comment by kenshen112** [comment]
@alucryd So, compiling with LTO on works for you?

**Comment by alucryd** [comment]
Using LTO_PCSX2_CORE and the above flag for now. Haven't tried enabling LTO globally but I will give it a go.

**Comment by kenshen112** [comment]
pcsx2-git wasn't having issues with or without LTO so. That's incredibly odd

**Comment by alucryd** [comment]
@kenshen112 It seemed to fail when using just LTO_PCSX2_CORE, and only on recent commits, previous builds worked just fine. Switched to global LTO for the community build.

**Comment by kenshen112** [comment]
Sounds good. I'll test LTO CORE. I actually hadn't tried that

**Comment by Ziemas** [comment]
The LTO failure on with fastjmp should have been fixed by #4938, is it broken on some configurations?

**Comment by kenshen112** [comment]
`/home/musungo/pcsx2-git/PKGBUILD: line 87: -DWAYLAND_API=ON: command not found` I get that if I have the core option enabled

**Comment by kenshen112** [comment]
```
build()
{
  mkdir -p build
  cd build

  cmake ../pcsx2 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_SYSTEM_YAML=TRUE \
    #-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DWAYLAND_API=ON \
    -DLTO_PCSX2_CORE=ON \
    -GNinja \
    -DPACKAGE_MODE=ON \
    -DXDG_STD=TRUE \
    -DDISABLE_SETCAP=ON
  ninja -j$(nproc)
}
```

vs 

```
build()
{
  mkdir -p build
  cd build

  cmake ../pcsx2 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_SYSTEM_YAML=TRUE \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DWAYLAND_API=ON \
    -GNinja \
    -DPACKAGE_MODE=ON \
    -DXDG_STD=TRUE \
    -DDISABLE_SETCAP=ON
  ninja -j$(nproc)
}
```

**Comment by lightningterror** [comment]
Closing as the issue seems to be resolved.
