### ISSUE TITLE
Bluetooth audio device not work spu2-x PortAudio mode with Windows WDM-KS and Windows DirectSound and Windows WASAPI

### ISSUE THREAD

**Issue by yxmline** [PCSX2/pcsx2#2982]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``

All pcsx2 version and latest development builds

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

All options default except using OpenGL (Hardware) setting for GSDX plugin and MTVU for 3+ cores enabled

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

All settings default for plugins, except those noted above

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

Bluetooth audio device not work spu2-x PortAudio mode with Windows WDM-KS and Windows DirectSound and Windows WASAPI
BT Music is Bluetooth Headphone
log messages
* SPU2-X: Enumerating Port Audio devices:
*** Device 0:'Master Voice Driver'(Windows Direct Sound)
*** Device 1:'BT Music Stereo'(Windows Direct Sound)
*** Device 2:'Realtek High Definition Audio'(Windows Direct Sound)
*** Device 3:'BT Music Hands-Free'(Windows Direct Sound)
*** Device 4:'Realtek Digital Output (Realtek High Definition Audio)'(Windows Direct Sound)
*** Device 5:'BT Music Stereo'(Windows WASAPI)
*** Device 6:'Realtek High Definition Audio'(Windows WASAPI)
*** Device 7:'BT Music Hands-Free'(Windows WASAPI)
*** Device 8:'Realtek Digital Output (Realtek High Definition Audio)'(Windows WASAPI)
*** Device 9:'SPDIF Out (Realtek HDA SPDIF Out)'(Windows WDM-KS)
*** Device 10:'Speakers (Realtek HD Audio output)'(Windows WDM-KS)
*** Device 11:'Headphones ()'(Windows WDM-KS)
*** Device 12:'Headphones (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(BT Music))' (Windows WDM-KS)
* SPU2-X: PortAudio error: Invalid device

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

Use Bluetooth Headphone or Bluetooth Speaker

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

only work spu2-x XAudio 2 mode and  DirectSound mode and WavOut mode and PortAudio mode with Unspacified

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
OS:Windows 10 64 Bit
CPU:Intel i7-3770
GPU:Gigabyte GTX 1070 ti

**Comment by mirh** [comment]
And.. does your bluetooth device actually supports WDM-KS?
Because I know portaudio is [super lame](https://github.com/spatialaudio/python-sounddevice/issues/7) into not having any kind of check whatsoever.

**Comment by yxmline** [comment]
Bluetooth devices also need hardware support for WDM-KS??

**Comment by mirh** [comment]
Bluetooth device as in the software driver you have installed.

**Comment by yxmline** [comment]
Thank you. I understand.
