### ISSUE TITLE
Ratchet Gladiator: "Glow effect" misplaced for objects

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#2984]
***PCSX2 version:***
PCSX2 1.5.0-0 - compiled on Jun  6 2019

***PCSX2 options:***
- Preset: Balanced, Multithreaded VU enabled
- Apect Ratio/Aspect Ratio Overwrite: Widescreen 16:9
- Wait for Vsync is disabled

***Plugins used:***
GS:
![gs_window](https://user-images.githubusercontent.com/30773753/59132820-b9000800-8965-11e9-8091-ac0610e08248.png)
![gs_window_2](https://user-images.githubusercontent.com/30773753/59132828-bbfaf880-8965-11e9-8c63-79b3f341ab02.png)

***Description of the issue:***
The "Glow" of objects is placed floating apart from their destination. It doesn't happen on OGL SW Mode.
See the screenshots for clarification:
![rc_lights_bug](https://user-images.githubusercontent.com/30773753/59133546-f1084a80-8967-11e9-8d66-0ebe9d7e57c6.png)
![rc_lights_bug_2](https://user-images.githubusercontent.com/30773753/59133554-f5346800-8967-11e9-84c6-aa45a205cc3f.png)
![rc_lights_bug_3](https://user-images.githubusercontent.com/30773753/59133574-00879380-8968-11e9-83b3-ec3bbc650581.png)
![rc_lights_bug_4](https://user-images.githubusercontent.com/30773753/59133586-07aea180-8968-11e9-914e-07a933c421cc.png)

Blockdump: https://www.file-upload.net/download-13628467/Ratchet_Gladiator2019-05-0722-58-04.dump.html

PCSX2 log: https://www.file-upload.net/download-13628471/log.txt.html

***How to reproduce the issue:***
100% reproducible for me.

1. Load savegame from memory card: https://www.file-upload.net/download-13628464/MemCard32MB.ps2.html on OpenGL HW.

2. See one of the bot's (Your personal helper bots) engine which is also affected by the bug.

***Last known version to work:***
Unknown, 1.4 can't be really used cause graphic is completely broken there.

***PC specifications:***
https://gist.github.com/XXXBold/007546b9d2e8020dec84795f09e63a30

**Comment by Dreadmoth** [comment]
Currently, I think the only way to completely avoid this problem is to play at native resolution (hardware or software renderer). Misaligned bloom is a common upscaling issue (#2860).

You can improve the alignment by using Texture Offsets - at 4x Native, a value of X:360 Y:360 seems to work [reasonably well](https://i.imgur.com/FDw0onk.png) (using PAL version with widescreen hack). Some issues aren't fully fixable - glow effects become smaller at high resolutions, and look "scattered" around fine lines and small or distant objects.

**Comment by XXXBold** [comment]
> Currently, I think the only way to completely avoid this problem is to play at native resolution (hardware or software renderer). Misaligned bloom is a common upscaling issue (#2860).
> 
> You can improve the alignment by using Texture Offsets - at 4x Native, a value of X:360 Y:360 seems to work [reasonably well](https://i.imgur.com/FDw0onk.png) (using PAL version with widescreen hack). Some issues aren't fully fixable - glow effects become smaller at high resolutions, and look "scattered" around fine lines and small or distant objects.

Interesting. Can confirm that the Texture Offset works, looks much better (almost?) original when using it, thanks :)

**Comment by lightningterror** [comment]
Closing in favor of meta https://github.com/PCSX2/pcsx2/issues/2860

**Comment by Miwasak** [comment]
I would just say the problem can be resolve with => enable HW Hacks, adcanced settings, and set Half-pixel offset to normal (Vertex) This option fix all ratchet and clank games :)

**Comment by Tado23** [comment]
These are my settings now and it works pretty good.
![1](https://user-images.githubusercontent.com/101958278/159145349-b3295fa0-5e3f-46df-9975-572f48f53ff3.PNG)
![2](https://user-images.githubusercontent.com/101958278/159145351-cd7e729d-2ddb-42fd-b6c7-086a83d8927b.PNG)
![3](https://user-images.githubusercontent.com/101958278/159145355-849acca3-bee3-41e3-a14d-3a354235aeea.PNG)

**Comment by RedDevilus** [comment]
DATE accuracy off
Credibility gone.

Also Direct3D11 for NVIDIA GPU

To be frank those settings are awful.
