### ISSUE TITLE
PCSX2 Blockdump file write permission issue

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#2985]
***PCSX2 version:***
 PCSX2 1.5.0-0 - compiled on Jun 6 2019

***Description of the issue:***
When trying to create a blockdump as (normal) user on linux, it fails because it can't write to /usr/games/xxx.dump

***How to reproduce the issue:***
Start PCSX2, select Debug->Create Blockdump and start/resume a game. A message will pop up showing that the blockdump has been written to /usr/games/xxx.dump, but it is not due to lack of writing permissions.

Workaround: Start pcsx2 as root...

***Last known version to work:***
Unknown

***PC specifications:***
Linux Mint 19.1 Cinnamon x64

-----------------------------------------------------------------------------------------

Tasks needed to be done: (Modified by Assignee)

- [x] CDVD directory modification from ``getcwd()`` with custom INI vars
- [ ] Add a GUI browse option for making it easier on end user side.

**Comment by XXXBold** [comment]
AFAIK there's also no way to specify a custom destination path for blockdumps. This could be added as an option.

**Comment by XXXBold** [comment]
A suggestion how to implement it:

- Make the path for Blockdumps freely configurable. 
- User's configuration can be stored in the .../PCSX2/inis/PCSX2_ui.ini file under the "Folder" section e.g. as "BlockDumps=/home/<user>/" as a default value.
Option 1: If the user selects the  "[ ] Create Blockdump" for the first time, ask to set up the destination path.
Option 2: Add an additional entry in the main frame (Debug->Blockdump dir) to change the Blockdump directory if needed.

Let me know what you think about it.

**Comment by ssakash** [comment]
Seems like the consensus on the team is that the majority of the users won't be using this option and it isn't worth adding to the user interface, so it'll be staying as a INI customizable path instead.
