### ISSUE TITLE
[Feature Request] Add Support for GOG Galaxy 2.0

### ISSUE THREAD

**Issue by nduriez** [PCSX2/pcsx2#3002]
GOG Galaxy 2.0 is a game launcher which allow to connect all your platform in one place, it would be great to have PCSX2 compatible with it.

The Integration API is open-source and can be found [here](https://github.com/gogcom/galaxy-integrations-python-api)

**Comment by MrCK1** [comment]
This is unlikely to happen as most of the team was against Discord Rich Presence integration (#2359)

**Comment by JigAma** [comment]
From what i've read on #2359 people were skeptical about Discord Rich Presence because it would clutter PCSX2 code, however, the Galaxy 2.0 Integration works with a separate python script so i don't think it would clutter the code and it would be optionnal

> Each integration in GOG Galaxy 2.0 comes as a separate Python script, and is launched as a separate process, that which needs to communicate with main instance of GOG Galaxy 2.0." - [Galaxy 2.0 Integration API ReadMe](https://github.com/gogcom/galaxy-integrations-python-api#features)

**Comment by lightningterror** [comment]
Closing, trivial.
