### ISSUE TITLE
Ghosting effect in Sniper Elite and bad performance on split screen multiplayer

### ISSUE THREAD

**Issue by HomemMacaco** [PCSX2/pcsx2#3005]
***PCSX2 version:***
``(1.5-3179)``

***PCSX2 options:***
``(OpenGl Hardware and Direct3D11 tested all settings default, tried every option on the video plugin menu only skipdraw "fixed" it but made a lot of graphical glitches occur, there's no ghosting effect on software modes but perfomance is terrible)``

***Plugins used:***
Everything default

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
This ghosting effect is the problem:
![image](https://user-images.githubusercontent.com/36904628/60482328-631e3780-9c67-11e9-858f-5e528872249e.png)
![image](https://user-images.githubusercontent.com/36904628/60482361-89dc6e00-9c67-11e9-9784-f09b5fb700f6.png)

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Launch the game with any Hardware mode

***PC specifications:***
CPU: Intel I3 6100 GPU: GTX 950 OS: Windows 7 64 Bit)``

**Comment by bositman** [comment]
Does it happen on native resolution too?

**Comment by HomemMacaco** [comment]
> Does it happen on native resolution too?

Yes, i've tried every single option on video plugin and nothing fixed it

**Comment by tadanokojin** [comment]
gsdump please
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

multiframe less than a second.

**Comment by HomemMacaco** [comment]
I'm getting a 502 Bad Gateway error on that site but i think this is what you're asking for:
[gsdx_20190702105706.zip](https://github.com/PCSX2/pcsx2/files/3350421/gsdx_20190702105706.zip)

**Comment by tadanokojin** [comment]
Cloudflare is having trouble today, I guess.

Post-processing issue. TS effect green to alpha.
Skip draw 1-2 seems to skip it without much issue fort the time being.

**Comment by HomemMacaco** [comment]
Skip draw 1:
![image](https://user-images.githubusercontent.com/36904628/60526883-9abccc00-9cc7-11e9-84ae-4b753d0c8cc4.png)
Skip draw 2:
![image](https://user-images.githubusercontent.com/36904628/60526928-ad370580-9cc7-11e9-8681-69ec285812d4.png)

Ghosting effect still present with skidraw when looking to some areas in the game, with skipdraw 2 the ghosting effect is less noticeable but the game gets too blurry

**Comment by tadanokojin** [comment]
Skip draw 1-2. Put 1 in the first field and 2 in the second.

**Comment by HomemMacaco** [comment]
Oh i see sorry about that haha, with skip draw 1-2 the only visual glitch i'm getting is the trees foliage disapearing, thanks for the help Kojin

**Comment by tadanokojin** [comment]
No worries. Going to look into a less temporary solution when I get a moment.

**Comment by tadanokojin** [comment]
FTR auto flush will resolve but not ideal. SW has this same issue without auto flush.

**Comment by refractionpcsx2** [comment]
Auto Flush fixes this and as of #5580 being merged the performance impact is pretty much negligible/none so it will just require us to add it to the GameDB once #5593 is merged, which won't be long.

v1.7.2413 No Auto Flush: 182fps
v1.7.2413 Auto Flush: 165fps

After #5580 Auto Flush: 180fps
