### ISSUE TITLE
Audio in Windows 10 after sleep/hibernate

### ISSUE THREAD

**Issue by mrstackz** [PCSX2/pcsx2#3006]
***PCSX2 version:***
All, but specifically verified were dev 1.50 and stable 1.40

- **Notes**:
Should (I hope) be easy to replicate, I just don't know if there's a way to fix it

***PCSX2 options:***
Default

***Plugins used:***
Default as installed (it is not a plugin related issue, at least I don't think it is, but it's all default settings on the SPU2-X driver)

***Description of the issue:***
**The Problem**
After Windows goes to full hibernate or 'deep sleep', PCSX2 loses audio unless/until you full relaunch it.

In reviewing the Windows Sound Mixer, it appears that PCSX2 isn't "reattaching" itself to the audio output device in use - so in my case it's a TV. 

Steam occasionally has the same issue with games left running, but it's not constant.  PCSX2 is every time, it seems.  I don't know if this is something that can be corrected.

***How to reproduce the issue:***
1.  Run PCSX2
2.  Run (or don't) a game, verifies audio plays
3.  Hibernate computer (I don't know if there is some period of time before it happens.  In my case I've always left it in hibernate or sleep overnight)
4.  Bring computer out of hibernation, verify audio does not play
5.  Relaunch PCSX2 and game, verify audio plays

***Last known version to work:***
None that I can tell

***PC specifications:***
Intel i7 9700k
32GB Corsair RAM
Windows 10 Education
SanDisk 2TB SSD

**Comment by MrCK1** [comment]
I had no problems with audio resuming in PCSX2 when using sleep and hibernate on Windows 10 Home. It sounds like your audio problem is specific to your configuration, maybe having to do with your TV being used?

My best guess is that the default audio device is being switched after hibernation/sleep and is causing your audio issues. Maybe try disabling all of your audio devices except for the TV output and see if the issue still appears?

**Comment by mrstackz** [comment]
Tried that, no dice.  And again, PCSX2 is the one outlier.

If you weren't able to replicate I would ask: are you using HDMI audio out?

________________________________

**Comment by mirh** [comment]
W10 Education is based Enterprise, which in turn makes me wonder whether you might not be using some old build, which in turn may entail bugs either in the OS or the drivers.

**Comment by mrstackz** [comment]
Latest updates constantly applied to Windows. I don't update pcsx2 constantly due to the risk of other games breaking.

All I do know is that with the exception of a select few PC games from GOG or Steam, pcsx2 is the only app that does it.  I even disabled all other audio devices.

I noticed that I can get it to happen less if Borderless Gaming is being used instead of the emulator controlling full screen. Problem is the dynamic header in pcsx2 makes it difficult to consistently get BG to work right. But it at least tells me that it must be possible to force audio output.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mirh** [comment]
> All I do know is that with the exception of a select few PC games

Oh god, I think I got the problem. 
Basically, we are one of those stupid applications that keep audio streams open/forced. 

Another symptom is that if you change the assigned default output device, that's not going to get applied until you close and reopen the emulation window.

**Comment by mrstackz** [comment]
I work on scientific method. I observe Program A losing audio and isolate the scenario when it happens as best I can, which is overnight hibernate or deep sleep. I test Program B - another emulator, a PC game, a browser stream, a local video, doesn't matter. Can't replicate with Program B except for Steam/GOG Dragon Quest Heroes 1 and only then when it's not running in Borderless Gaming. Which means BG isn't affected.  That it's going to a TV via HDMI might be significant, but doesn't explain why only certain few programs work, so I'm inclined to dismiss it as insignificant.

So then I look for similarities between Program A and the game that doesn't work, in this case the only possible theories are (A) something in the code that isn't handling wake correctly or (B) the code hasn't been rewritten to fully support Windows 10.  As a person certified in the OS, with the exception of 10 S, there's no significant difference between versions of the same OS as far as Microsoft-based programs are concerned. It's not Education edition.

Since both A and B are possible, what I'm asking is if any of the developers can think of something in the code for the audio plug-in, a way to 'reset' it or the use of it without a full relaunch of the program. Then, an option to bind that to a keyboard event.  That way, I can (in theory) hit that key to wake the computer and 'fix' the audio at the same time.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrCK1** [comment]
Any specific backend it happens with, or XAudio vs PortAudio?

**Comment by lightningterror** [comment]
I wasn't able to replicate this either so I'll be closing this.
