### ISSUE TITLE
Spider-man 3 loading issue

### ISSUE THREAD

**Issue by PalTesDak** [PCSX2/pcsx2#3012]
***Game Title***
Spider-man 3
***PCSX2 version:***
PCSX2 v1.5.0-dev-3188-gd0cb0f59d Windows
- **Notes**:
 As of this build, the in-game speed has increased to a maximum of 100 (previously 20-30 fps maximum) and the previous graphical glitches are gone from the previous (PCSX2 1.4.0) version.

***PCSX2 options:***
EE/VU Clamp modes: Normal/Normal 
EE/VU Rounding: Chop/Chop
VU0 and VU1: superVU Recompiler [legacy]
Speedhacks: all default/disabled

***SPU2-X Settings:***
Interpolation: Catmull-Rom
Disable Effects processing:Enabled
Use the de-alias filter:Enabled
Module: DirectSound
Synchronizing mode:Timestretch 

***GSDX***
 GSdx Settings: Default
GSdx HW Hacks: None/Default

***Plugins used:***
GSdx, SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD, the rest are null plugins
***Description of the issue:***
Game stuck after the completition of the first level, responsive but endlessly loading the next level.
The game can freeze during some points unless some settings are changed, while this happens a distorted looping sound can be heard in the background.
With the  above mentioned settings, the random freezing issue doesn't present itself anymore, but the stuck on loading bug remains regardless of settings.
***How to reproduce the issue:***
The game can be played normally until the first level is completed, and then it locks up on the loading screen, but never loads the next level.

***Last known version to work:***
Never worked, always had this issue
***PC specifications:***
Intel I7 4790 3.6 Ghz
Nvidia GE Force 720 2 Gb
Windows 10 Home 64 bit 
RAM 16 GB DDR3
***Screenshot***
This screen remains forever, after the completition of the first mission with the "loading" symbol still moving/responsive.
![gsdx_20190709215637](https://user-images.githubusercontent.com/52718683/60918843-8d3dae00-a294-11e9-8f57-eb5cfe51f9a7.png)

**Comment by Lothar635** [comment]
Does the problem still happen with microVU? I thought that superVU was basically only used as comparison between the two.

**Comment by MrCK1** [comment]
No, it's a core issue. VUs won't affect the issue

**Comment by PalTesDak** [comment]
In this version of PCSX2 that i've tested(PCSX2 v1.5.0-dev-3188-gd0cb0f59d) , the game won't lock up randomly with the SuperVU (legacy) option instead of MicroVU, MicroVu causes the game to have slower speed and freeze at the checkpoints.
