### ISSUE TITLE
Radiata Stories Depth of Field issue

### ISSUE THREAD

**Issue by Dweeblord** [PCSX2/pcsx2#3022]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3199-g2f8932e37-windows-x86

***PCSX2 options:***
Default settingss

***Plugins used:***
Default settings.

***Description of the issue:***
The depth of field in Radiata Stories renders correctly at native resolution, but anything higher will misalign it dramatically causing ghosted models and sometimes it will enable a very pixelated full screen blur. In the older PCSX2 build I've been using there was a HW hack titled "Alpha" in DX10 that just removed the depth of field entirely which I very much liked, but in the newer builds it looks like it's been removed. Also in OpenGL the character shadows now render properly(thanks a lot for that by the way!) so I'd like to use this newer build. 
![pcsx2 2019-07-14 19-51-10-86](https://user-images.githubusercontent.com/43702664/61192355-f0528a80-a670-11e9-93fb-52879b63f19f.png)

I don't think cutscenes past the intro often use the depth of field but it'd be nice to sort this out. I tried every HW hack as well as a b unch of TC and Skipdraw settings with no luck, everything just seemed to make it worse. I guess I'm just asking where that Alpha setting went and if I can reproduce it in the newer PCSX2's OpenGL. 

***Last known version to work:***
pcsx2 1.5.0-20161107000823
Under DX 10 with the "Alpha" HW hack enabled.

***PC specifications:***
CPU: 8600k GPU: GTX 1070 OS: Windows 10 64 Bit

**Comment by tadanokojin** [comment]
Did you try the texture offset hacks?

**Comment by lightningterror** [comment]
Alpha hack was replaced with Accurate Blending.

**Comment by Dweeblord** [comment]
Yes I tried the texture offsets but it just seemed to make it worse Maybe there's a proper combination there, I wouldn't know how to find it though.

And Accurate Blending doesn't fix this, it does affect it though. Can I jump in an .ini and get it to act exactly like the old Alpha hack?

**Comment by lightningterror** [comment]
I believe HPO special fixes the issue, can you upload a gsdump?

**Comment by Dweeblord** [comment]
I've never done this before so hopefully this is what you are asking for.
[gsdx_20190715131709.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/3393819/gsdx_20190715131709.gs.xz.zip)
![gsdx_20190715131709](https://user-images.githubusercontent.com/43702664/61242491-1163bb80-a703-11e9-8aaf-e913e829da85.png)

**Comment by lightningterror** [comment]
Half Pixel Offset Special seems to be working fine as I suggested. This is on 6x native.

![GSDumpGUI 2019-07-15 22-53-39-61](https://user-images.githubusercontent.com/18107717/61248522-82cb5a80-a753-11e9-9bbc-0df06a6f5146.png)

**Comment by Dweeblord** [comment]
I think I had a custom resolution set when I had tried that option before. Previously the other half-pixel offset settings just blew my screen up and yet it doesn't at 6x. Thanks a lot!

**Comment by RupertAvery** [comment]
Here's how I fixed it:

![image](https://user-images.githubusercontent.com/1910659/104410233-dca81d00-55a2-11eb-8a49-bac9e75a06d5.png)

**Before:**
![image](https://user-images.githubusercontent.com/1910659/104410305-095c3480-55a3-11eb-983c-e02fa73ad4c8.png)

**After:**
![image](https://user-images.githubusercontent.com/1910659/104410334-12e59c80-55a3-11eb-9b08-dd6674a30de0.png)

There is still a depth-of-field effect, instead of removing it.
