### ISSUE TITLE
Move GIF arbitration to MTGS

### ISSUE THREAD

**Issue by logikbyran** [PCSX2/pcsx2#3023]
### Background

Today, `TransferGSPacketData` trigger Path 1, 2 and 3 GIF transfers. `TransferGSPacketData` does:

1. Copy the GIF packet to its GIF path's temp buffer in `Gif_Path::CopyGSPacketData`.
This step might block on the MTGS thread: `// Let MTGS run to free up buffer space`.
2. Queue the next GIF packet (from the path with highest priority, 1>2>3) to MTGS' ring buffer in `Gif_Unit::Execute`.
3. Repeat 2. until all GIF paths' bytes are copied over to MTGS's ring buffer or until `gsSIGNAL` (`// 
Stalling Signal`) came. 

**My conclusion**
Anytime we call `TransferGSPacketData` there is a risk EE blocks or busy-spins until MTGS has drained previous GIF packets. 

**Questions**

1. Why not let EE continue executing the game while the DMA transfers take place? (= Let the MTGS thread consume the GIF packet directly from its location in main memory.)

AFAIU, on an actual PS2, the GIF consumes GIF packets directly from main memory, doesn't it?

2. Why use does MTGS need a ring buffer? (Why can't GIF packets be consumed directly from main memory?) Instead of a ring buffer, can't MTGS run an event loop where the producing threads queue up commands such as "drain path 1", "drain path 2" etc?

### Suggestion
It surprised me that pcsx2 does GIF arbitration and "GS feeding" on EE and not on MTGS. On my PC, the EE-thread often reaches 100% CPU so it would be nice to offload it by moving this logic to the less-loaded MTGS-thread. 

**I'd like MTGS to expose a thread safe interface that abstracts the GIF:**

`InitGifDmaPath1()`
`InitGifDmaPath2()`
`InitGifDmaPath3(bool sliced)`
`MaskPath3()`

The GIF interface would should, ideally, behave as the PS2 actual GIF interface. That is, all methods are async. Games are programmed to poll `GIF_STAT` anyway, aren't they? Please correct me if I'm wrong.

**Advantages:**
* Cleaner code.
* Easier to to send GIF packets.
    * The MTVU-thread can simply call `InitGifDmaPath1()`.
* Offloading the EE-thread, hopefully gaining a few extra frames per second.
* Zero-copy if we let MTGS process the GIF packet in-place?
    * Today `CopyGSPacketData` copies the GIF packet from main (or VU1 memory) to the GIF path's packet buffer.
* Will help us implementing a "VIF1-thread".

### Registers to be updated by MTGS

|  DMA transfer  |  DMA channel | Registers | 
| ---- | ------------- | ------------- |
| Path 1 | VU1->GIF | `GIF_*`, ? |
| Path 2 `DIRECT*` | VIF1->GIF | `GIF_*`, ? |
| Path 3 | EE->GIF | `GIF_*`, `D2_`, ? |

**Comment by refractionpcsx2** [comment]
I'm very nervous about how that will work with PATH3 masking, since it relies on register settings on GIF_MODE and VIF_MSKPATH3 which are outside of the MTGS and the packet can be stopped arbitrarily at random points with millisecond accuracy, sticking that across the other side of a thread sounds very sketchy.

**Comment by logikbyran** [comment]
Wouldn't timings be ok if MTGS checked `GIF_MODE` and `VIF_MSKPATH3` before/after each GIF packet?

**Comment by refractionpcsx2** [comment]
No because it can stop mid packet.

**Comment by logikbyran** [comment]
Thanks. I see. I did some research:

> _EE Users Manual, **GIF_MODE** Register : Mode setting register:_ When writing with the M3R field set to 1, PATH3 is masked. When this field is set to 1 during transmission operation, **the mask is enabled after the end of transmission**.

It seems like `GIF_MODE` cannot stop an ongoing Path 3 transfer but `VIF_MSKPATH3` can...

> _EE Users Manual_: Data is transferred in qword (128-bit) units, and should be aligned on this boundary in memory.  

> _EE Users Manual:_ Data is transferred to or from a peripheral processor in 8-qword slices: whenever the transfer of one slice is completed, the channel used for the transfer temporarily releases the bus right. Therefore, two or more data items can be transferred concurrently, in addition to the CPU being able to access main memory during transfer processing.

>_EE Users Manual:_ MSKPATH3 enables/disables transfer processing via the GIF PATH3. The setting of this register **applies to the next data block or later**.

What does "next data block or later" mean? I'd guess the GIF only checks for `MSKPATH3`-masking before/after it drains a DMA slice? We can emulate `VIF_MSKPATH3` with a shared (atomic) variable, written by the thread that runs VIF1 commands and read by the GIF (that, at some day, hopefully runs on the MTGS-thread), so, of course, it would be nice to read it less often.

**Comment by refractionpcsx2** [comment]
What is classed as the "end of transfer" is a little vague, block is more accurate.

PATH3 might send 100QW's but that might contain 20 blocks of data, and the PATH3 mask takes effect on those block boundaries, so if the mask is set while one of these is transferring, the next block will stall.

A block is from the start of a chunk of data to the EOP flag, then the next block starts if there is data left.
