### ISSUE TITLE
Transformers: TS issues

### ISSUE THREAD

**Issue by tadanokojin** [PCSX2/pcsx2#3025]
***PCSX2 version:***
Latest git as of July 13 2019

***PCSX2 options:***
N/A

***Plugins used:***
GSdx latest as of July 13 2019
Issue is present on both OpenGL and DX11

***Description of the issue:***
![gsdx_20190715170306](https://user-images.githubusercontent.com/26046960/61254191-a087c800-a731-11e9-9177-7fa625056167.png)

GS Dump:
https://drive.google.com/open?id=1csP6o4uimj0hDgtxFiNaqzfBZSz1Sg-l
HW log: 
[transformers.zip](https://github.com/PCSX2/pcsx2/files/3394518/transformers.zip)

***Last known version to work:***
Not known. Likely never worked. Issue is present in 1.4.0.

***PC specifications:***
CPU: Intel i5-7600
GPU: GTX 1070
Windows 10

**Comment by kozarovv** [comment]
I have this game, and i can confirm that workaround from wiki work. At least OGL, not tested D11. Tested on some 1.5.0 - 3xxx build. 
> Use Alpha fix with D3D11 to remove stripes. • Use Disable Depth Emulation fix with OpenGL.

**Comment by tadanokojin** [comment]
Issue is TS by page

**Comment by seta-san** [comment]
the vertical lines are gone but the image is constantly flashing. something that only "disable depth emulation" fixes.
