### ISSUE TITLE
Nichibeikan Pro Yakyuu: Final League / World Fantasista Gliches

### ISSUE THREAD

**Issue by razaleighwiseman** [PCSX2/pcsx2#3028]
***PCSX2 version:***
stable build v1.4.0

I'm not able to play this beautiful games as is faces terrible glitches on the graphic.

Please help

**Comment by MrCK1** [comment]
We're going to need more details. First, please upgrade to 1.5.0 through buildbot.orphis.net/pcsx2

**Comment by razaleighwiseman** [comment]
Hi,

I'm using the 1.5.0 version. The problem still persist. The player rendering appear to be out of place. The player model became stretches when I started the match. Below image for further references; 

![image](https://user-images.githubusercontent.com/24619644/61423824-d7cdc300-a943-11e9-8fa0-de815ba842c5.png)

![image](https://user-images.githubusercontent.com/24619644/61423911-33984c00-a944-11e9-8949-753be18615fe.png)

I'm using default setting by the way.

My PC spec;

Hardware: Lenovo Ideapad320
OS: Windows 10 Home
RAM: 12 GB
Architecture: 64 Bit
Processor: Intel Core i5-7200U @ 2.50GHz 2.71 GHz 4CPU
Graphic: NVidia GeForce 940MX 8GB

Game Details;
---------------
Name: World Fantasista
Publisher: Square Enix
Year: 2002
-------------------
All game run smoothly except for this one. 

Thank you.

**Comment by MrCK1** [comment]
Try all of the EE and VU Rounding/Clamping modes then.

**Comment by arcadesfan** [comment]
I had the same issue of players glitches in this game for years, and tried everything in order to fix it but there is no way.
Could you please make an patch for this game like you currently do with other games ? 
This game is a gem and deserves it, one of the best soccer games around along with Football Kingdom, and it´s a pity it has those glitches. Many gamers would be grateful !

**Comment by atomic83GitHub** [comment]
I would like a blockdump and a GSdump of the field with glitched players please, Don't hesitate to ping me if you Don't know how to do.

**Comment by arcadesfan** [comment]
> I would like a blockdump and a GSdump of the field with glitched players please, Don't hesitate to ping me if you Don't know how to do.

I don´t know how to proceed to get a blockdump and GSdump, Can you please explain how to do that ? Many thanks !

**Comment by atomic83GitHub** [comment]
Open PCSX2, go into the debug menu and select, create blockdump, play your game until your problem happen then close PCSX2 and send me the .dump file created into the PCSX2 root directory.

**Comment by razaleighwiseman** [comment]
Hi @atomic83GitHub 

Attached herewith the dump file for your perusal;

[SLPS_201.95.WORLD FANTASISTA (2019-06-20 14-32-38).zip](https://github.com/PCSX2/pcsx2/files/3413286/SLPS_201.95.WORLD.FANTASISTA.2019-06-20.14-32-38.zip)

Thank you

**Comment by atomic83GitHub** [comment]
Unfortunately, your dump is invalid, you must do full boot, eject all the memorycards you have and do the blockdump before launching the game.

**Comment by razaleighwiseman** [comment]
Created a new one. Is this ok?

[SLPS_201.95.WORLD FANTASISTA (2019-06-20 15-51-24).zip](https://github.com/PCSX2/pcsx2/files/3413340/SLPS_201.95.WORLD.FANTASISTA.2019-06-20.15-51-24.zip)

**Comment by atomic83GitHub** [comment]
Still not good, try with that plugin: 
[CDVDiso.zip](https://github.com/PCSX2/pcsx2/files/3413359/CDVDiso.zip)

**Comment by razaleighwiseman** [comment]
Hi,

I ran with the plugin, here is the dump file;

[SLPS_201.95.WORLD FANTASISTA (2019-06-20 18-28-22).zip](https://github.com/PCSX2/pcsx2/files/3413493/SLPS_201.95.WORLD.FANTASISTA.2019-06-20.18-28-22.zip)

**Comment by atomic83GitHub** [comment]
It's a VU problem but yeah, that game is very strange, seems this problem only affect distant players.

**Comment by atomic83GitHub** [comment]
Try that pcsx2 version, put it in the PCSX2 root folder and execute it:
[PCSX2 COP0 fixes.zip](https://github.com/PCSX2/pcsx2/files/3413625/PCSX2.COP0.fixes.zip)

**Comment by razaleighwiseman** [comment]
Hi,

I tried running the exe, result still the same.

> that game is very strange, seems this problem only affect distant players.

Yeah, it is weird. Everything running smoothly except for the player model. As soon as you start the match, the player became stretched out of place. It is only happened if the players moving.

**Comment by atomic83GitHub** [comment]
So it's only when the player move. Interesting.

**Comment by razaleighwiseman** [comment]
Yes, I have found out that similar thing happened to player model in game **Nichibeikan Pro Yakyuu: Final League** which is also from the same publisher and also released in the same year.

Somebody has raised bug report on this;

https://forums.pcsx2.net/Thread-Bug-Report-Nichibeikan-Pro-Yakyuu-Final-League-NTSC-J

Thank you

**Comment by atomic83GitHub** [comment]
Can you run the game with the full emulog output?

**Comment by arcadesfan** [comment]
Hello. How do I proceed to run "World Fantasista" in full emulog output ? Thanks.

**Comment by atomic83GitHub** [comment]
Enable it in the PCSX2 program log window: 
![image](https://user-images.githubusercontent.com/26351275/68135182-8dd51100-ff23-11e9-9515-2d3c651d48e8.png)

**Comment by arcadesfan** [comment]
> Enable it in the PCSX2 program log window:
> ![image](https://user-images.githubusercontent.com/26351275/68135182-8dd51100-ff23-11e9-9515-2d3c651d48e8.png)

I created a blockdump as per your instructions, with all those things you mention in your picture, ticked, don´t know if this was what you were asking for. I ejected the memory cards, but couldn´t boot the game using "full boot", so I used the cdvdiso plugin and "fast boot"( the cdvdGigaherz plugin didn´t work to boot the iso either ). Please see if my dump is of any help. I attach it here:
[SLPS_201.95.WORLD.FANTASISTA-(2019-10-06 01-49-46).zip](https://github.com/PCSX2/pcsx2/files/3812607/SLPS_201.95.WORLD.FANTASISTA-.2019-10-06.01-49-46.zip)
[Uploading SLPS_201.95.WORLD.FANTASISTA-(2019-10-06 01-49-46).zip…]()

**Comment by arcadesfan** [comment]
> Enable it in the PCSX2 program log window:
> ![image](https://user-images.githubusercontent.com/26351275/68135182-8dd51100-ff23-11e9-9515-2d3c651d48e8.png)

I created a blockdump as per your instructions, with all those things you mention in your picture, ticked, don´t know if this was what you were asking for. I ejected the memory cards, but couldn´t boot the game using "full boot", so I used the cdvdiso plugin and "fast boot"( the cdvdGigaherz plugin didn´t work to boot the iso either ). Please see if my dump is of any help. I attach it here:
[SLPS_201.95.WORLD.FANTASISTA-(2019-11-06 01-49-46).zip](https://github.com/PCSX2/pcsx2/files/3812627/SLPS_201.95.WORLD.FANTASISTA-.2019-11-06.01-49-46.zip)

**Comment by atomic83GitHub** [comment]
I will need a savestate ingame please.

**Comment by arcadesfan** [comment]
I created a savestate pressing F1. I attach the sstates folder after the savestate was created. Please let me know if it is OK, otherwise I create other.

[sstates.zip](https://github.com/PCSX2/pcsx2/files/3816697/sstates.zip)

**Comment by arcadesfan** [comment]
Hello. Is there any news about the fix for this issue ? Is it possible to fix ? Thanks

**Comment by arcadesfan** [comment]
> I will need a savestate ingame please.

Hello. Is there any news about the fix for this issue ? Is it possible to fix ? Thanks

**Comment by altiereslima** [comment]
Fix in new versions

![image](https://user-images.githubusercontent.com/18044879/91668050-a54b3f00-eadf-11ea-9251-55562c6895cc.png)

**Comment by altiereslima** [comment]
The bug has resurfaced

**Comment by refractionpcsx2** [comment]
Should be fine once 1.7.4408 is available. (GameDB: Various Fixes)
