### ISSUE TITLE
Investigate and implement a "DMAC-thread"

### ISSUE THREAD

**Issue by logikbyran** [PCSX2/pcsx2#3032]
Spawned from [#3024](https://github.com/PCSX2/pcsx2/issues/3024#issuecomment-512533759).

**Comment by tadanokojin** [comment]
By who?
And why a whole separate issue?

**Comment by logikbyran** [comment]
Implementation-wise, #3024 is about enabling parallel VU1 double buffering (=moving `UNPACK` from the VU1-thread to the EE-thread). I guess that's a smaller task that can be done long before we create a DMAC-thread (= moving *all* DMA transfers away from EE), if we ever manage to.

**Comment by tadanokojin** [comment]
Github Issues are like PCSX2: more threads is not necessarily the solution ;)

I think #3024 describes the problem well enough and I don't think we need an issue for each proposed solution to that problem especially if they're going to be this vague.

**Comment by atomic83GitHub** [comment]
Are you sure it would be usefull, I mean it will potientialy create even more timings problems and with nowdays CPUs, speed should aready be optimal even without MTVU.

**Comment by tadanokojin** [comment]
I agree with atomic. Solution to your problem isn't adding a complex MT architecture and causing hundreds of regressions for the small benefit of supporting a [6 year old laptop CPU with an STR of 1562](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-4500U+%40+1.80GHz&id=1937). Hell [even modern Pentium](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Pentium+Gold+G5400+%40+3.70GHz&id=3248) can meet our [recommended](https://github.com/PCSX2/pcsx2#recommended). Solution is a new PC.

Anyway, closing this as there is already a discussion regarding this issue available in #3024 and any potential remedies for it can be discussed there. No reason to pollute the issue list.

**Comment by logikbyran** [comment]
> I think #3024 describes the problem well enough and I don't think we need an issue for each proposed solution to that problem.

We might solve #3024 by emulating VPU1's double buffering. Moving all DMA to one thread is a bigger task so I thought it deserved to be tracked and discussed independently. I think we need solve #3024 before we ever create a DMAC-thread.

> especially if they're going to be this vague.

I updated the description a bit. 

> Are you sure it would be usefull, 

No.

> I mean it will potientialy create even more timings problems

Yes. We'd need to sit down and think about how to do this.

> and with nowdays CPUs, speed should aready be optimal even without MTVU. 

Yeah, today MTVU doesn't help much but that's a problem with our MT-architecture (#3024, #3023 etc), not with threading as a concept. For threading to be useful, yep, PCSX2 would need a change in architecture. I wanted to use this thread for an open-minded discussion about that.

**Comment by tadanokojin** [comment]
> Moving all DMA to one thread is a bigger task so I thought it deserved to be tracked and discussed independently.

Problem is this: I don't need an issue for every idea you have for the same root problem.

>  Yeah, today MTVU doesn't help much

It helps plenty and [has plenty of issues too](https://forums.pcsx2.net/Thread-LIST-Games-that-may-not-work-well-with-MTVU). You misunderstood what atomic is saying. He's pointing out to you the fact that a recent CPU is plenty performant for PCSX2 even without MTVU.

> not with threading as a concept.

No one disparaged threading as a concept. What I'm disparaging is a huge architectural change for the sake of supporting your old under-powered laptop hw.

From my point of view, the benefit simply isn't worth it.
