### ISSUE TITLE
Add LilyPad on Linux

### ISSUE THREAD

**Issue by trymeouteh** [PCSX2/pcsx2#3034]
Please add LilyPad plugin for Linux version of PCSX2. Or allow OnePad to support multitap to allow 4 players/controllers.

**Comment by pixelherodev** [comment]
Heads up to anyone with triage powers: pretty sure this is done.

```
 noam@new-host-2  ~  ls Documents/Development/pcsx2/bin/plugins|grep Lily
libLilyPad-0.11.0.so
```

**Comment by arcum42** [comment]
Not really as much as that. There was a preliminary start at porting Lilypad done by greg at one point, and it does compile, and it might work, but has no configuration whatsoever, though it might be set up to read an ini file. Can't really recall.

Onepad, now, just basically doesn't have any code in it for multitap, and I'm not the most familiar with implementing it or testing it (I'm not sure if I actually have any games that would use it), so I've been putting off trying to add it. I've also been doing my own rewrite of OnePad off and on, so if I implement it, I might do it there, then backport.

**Comment by pixelherodev** [comment]
```
 There was a preliminary start at porting Lilypad done by greg at one point, and it does compile, and it might work, but has no configuration whatsoever, though it might be set up to read an ini file. Can't really recall.
```

Ah, my bad; thanks for the info!

**Comment by ordovice** [comment]
Would like to add a +1 to this for either the new OnePad or adding to OnePad legacy (or both).

**Comment by MrCK1** [comment]
Closing since PAD is now merged into core. Other feature work for PAD is still ongoing.

**Comment by LevitatingBusinessMan** [comment]
This is closed, but I don't think PAD has the same functionality as LilyPad. I can't seem to be able to change the control scheme at all.
