### ISSUE TITLE
Kaido Racer (Tokyo Xtreme Racer: Drift) No Lighting from Headlights in DX11 HW

### ISSUE THREAD

**Issue by useresuser** [PCSX2/pcsx2#3037]
Dump:

https://www.dropbox.com/s/cmp1bvs8dv96wjj/Kaido%20Racer%20%28Tokyo%20Xtreme%20Racer%20Drift%29%20No%20Lighting%20from%20Headlights%20in%20DX11%20HW.zip?dl=0

[Kaido Racer (Tokyo Xtreme Racer Drift) No Lighting from Headlights in DX11 HW.zip](https://github.com/PCSX2/pcsx2/files/3429004/Kaido.Racer.Tokyo.Xtreme.Racer.Drift.No.Lighting.from.Headlights.in.DX11.HW.zip)

Tested on 1.4 and 1.5 (3210)

OpenGL HW works fine
OpenGL SW works fine
DX11 SW works fine

PCSX2 options:

No hacks
Safest preset

Plugins used:
Default
SSE4

During night races the lighting from headlights don't work on DX11 HW

PC specifications:

i7 2600k
16gb 
R9 270X

Windows 10 64 Bit 1803

**Comment by useresuser** [comment]
![2019 07 24-19 52](https://user-images.githubusercontent.com/37781324/61834108-028caf80-ae4d-11e9-84e2-ab7b2cd216f8.png)
![2019 07 24-19 51](https://user-images.githubusercontent.com/37781324/61834109-028caf80-ae4d-11e9-9983-52618d959f4d.png)

**Comment by lightningterror** [comment]
SW blending, current DX11 can't support the feature because api is limited. It will require 11.3 feature level with hardware ROV support (nvidia maxwell / amd vega or better).
