### ISSUE TITLE
No option to download latest build

### ISSUE THREAD

**Issue by Moltresrider** [PCSX2/pcsx2#3039]
I clicked to download version **b48bc8e** on your official website but it brought me to the "code" page but there is no option to download that version as an exe! It seems to be a fake link with no actual download of that version. I cannot do anything with code, I need the actual emulator

**Comment by KrossX** [comment]
Well, you gotta click the **Download** link and not the revision link. Current development builds for Windows are hosted here: https://buildbot.orphis.net/pcsx2/
