### ISSUE TITLE
Add support for TLS (Thread Local Storage) on OSX

### ISSUE THREAD

**Issue by aktau** [PCSX2/pcsx2#304]
I keep seeing warnings like this:

```
[ 84%] Building CXX object common/src/x86emitter/CMakeFiles/x86emitter.dir/x86emitter.cpp.o
In file included from /Users/Kevin/github/aktau/pcsx2/common/src/x86emitter/x86emitter.cpp:32:
In file included from /Users/Kevin/github/aktau/pcsx2/common/include/x86emitter/internal.h:18:
/Users/Kevin/github/aktau/pcsx2/common/include/x86emitter/x86types.h:45:11: warning: x86emitter: TLS not available, multithreaded emitter disabled. [-W#pragma-messages]
#               pragma message("x86emitter: TLS not available, multithreaded emitter disabled.")
                       ^
1 warning generated.
```

And it's really cluttering up my view. I decided to investigate. This was basically decided in commit https://github.com/pcsx2/pcsx2/commit/9473e69b7f1bd0f923bafbe4cb11656b3c7e7458

Claiming that OSX doesn't natively support TLS. Though I've never looked into TLS all that much, I believe the situation to be different now. See this article: http://www.darlinghq.org/for-developers/thread-local-storage-on-os-x

This is a tracker issue for whomsoever finds time first to take a stab at it.

**Comment by avih** [comment]
@aktau, I see that you've been experimenting with native OS X builds. Care to give a some update on the current status?
- On what system do you compile and which XCode version?
- Any special flags/modifications/etc instructions to get it to build?
- What builds successfully? PCSX2 itself? plugins?
- Does it run? what works and what doesn't?
- Any other info? does it run in reasonable speed? any gotchas?
- Do you have patches you're happy with and can do a PR?

**Comment by aktau** [comment]
I'll answer in the main issue :).

**Comment by tadanokojin** [comment]
Closing in favor of #18.
