### ISSUE TITLE
'Dog of Bay' [SLPS-20057] Corrupted textures unless VU1 is Interpreter

### ISSUE THREAD

**Issue by Zelmarked** [PCSX2/pcsx2#3041]
PCSX2 1.5.0-20190726181055 - compiled on Jul 26 2019

Textures on the character and on some parts of the level look corrupted unless VU1 is set to Interpreter(Laggy). I've tried various setting differences but VU1 on interpreter is the only thing that fixes it.

OGL HW VU1 Interpreter:
![OGLHW Inter](https://user-images.githubusercontent.com/17238967/61990058-a5d0f680-affe-11e9-9d51-46067378c4fc.jpg)
OGL SW:
![OGLSW](https://user-images.githubusercontent.com/17238967/61990059-a6698d00-affe-11e9-8e46-db441629184f.jpg)
OGL HW Recompiler:
![OGLHW](https://user-images.githubusercontent.com/17238967/61990060-a6698d00-affe-11e9-89d0-4951512b2246.jpg)

Vid showing more examples:
https://www.youtube.com/watch?v=KD9Ba2uvo6Y
(Build from 2016 but seems to be the same affliction)

GS Dump: https://drive.google.com/open?id=1NV0MxekjleRIW884m0q3mVRp6dC257fp

Afaik there was no prior build where it would not look glitchy.

I7 7700K - EVGA 980Ti - Win10 64

**Comment by incognitoh** [comment]
bro u dont need interpreter.. just leave VU1 on microVU but also enable the VU XGkick hack in manual fixes.  that should fix it

**Comment by Zelmarked** [comment]
Damn I hate to admit I overlooked that one but that did it. I know I hit up some of the game fixes a while back and on a build that had that option.

[SLPS-20057] NTSC-J

**Comment by lightningterror** [comment]
It should be good now.
