### ISSUE TITLE
about pcsx2's custom shaders tell me !

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#3045]
Hello.

I don't know about shader languages.

But I have a question.

Can custom shaders access pcsx2's upscaling method ?

For example,

After upscaling to 1920x1080(pcsx2's built in IR method) it upscale to 2x2(3840x2160) by custom shader.

Can it make this type's custom shader ?

or

Can it be implemented this feature to pcsx2's code ?

The purpose of my thinking is finding anohter way for experimental upscaling.

Maybe in Pcsx2's roadmap it doesn't have using other filters(bicubic, lanzcos, ...) or other antialiasing for increaseing image quality.

Because directly implemented this way is dangerous for graphical glitch, heavy performance, ...

So I thought it should change direction of the implementaiton  not inside(pcsx2 built in) to outside(custom shader).

If it can do this  we can confirm and know a variety of way for image quality safely with more shader modder. 

How do you think about this ?

**Comment by lightningterror** [comment]
What you're looking for is external shaders in GSdx shader configuration.
You can either edit the existing shaders\GSdx.fx shader or add your own.

For upscaling multiplier see (dx -> PS_SCALE_FACTOR macro, ogl ScalingFactor constant buffer).
Custom resolutions aren't supported.

**Comment by mondaychicken** [comment]
Thank you for reply.
But I don't  know well. What is 'PS_SCALE_FACTOR' ?
IS 'PS_SCALE_FACTOR ' variable ?
Then in shader.fx file if it is like PS_SCALE_FACTOR = 4
do I use this properly ?
or
#define PS_SCALE_FACTOR 4
Sorry, can you explain how to use simply in shader.fx file ?
ex)...

**Comment by lightningterror** [comment]
GSdx.fx shader can be toggled with GSdx_FX_Settings

For using your own shaders you will need to properly set it up.

Anyway closing as this isn't a real issue.
