### ISSUE TITLE
Buzz buzzers wireless (original) ubuntu 18.04

### ISSUE THREAD

**Issue by voicenoise** [PCSX2/pcsx2#3048]
Hi
i there a way to get the original wireless buzzers working on ubuntu with pcsx2 ?

**Comment by Daniel-CA** [comment]
I am also interested to know if they are working on windows. I have tried the controller 
in both systems and even if they are correctly detected in the system they are not working in the calibration.
![calibration](https://user-images.githubusercontent.com/7643575/62147664-44f43780-b2f8-11e9-844c-17e55190cf45.png)

**Comment by voicenoise** [comment]
i try under windows7/32 but is the same... 
i think first we need a driver for linux and windows... 
any solutions are welcome to play buzz with buzzers ;-)

**Comment by Daniel-CA** [comment]
On windows they work fine, I used simpleHIDwriter program  as explained in this page:
[](
http://www.decsoftware.com/wireless_buzzers.htm)
For Linux could be used this library:
[](
https://github.com/signal11/hidapi)

But you will need to code some script to remap buttons, here is an example:

[](https://pimylifeup.com/raspberry-pi-quiz-game-buzz-controllers/)

**Comment by lightningterror** [comment]
I'll close this since it's an external issue and it can be solved.
