### ISSUE TITLE
PCSX2 1.4.0 downloaded from website fails to run on Linux

### ISSUE THREAD

**Issue by berarma** [PCSX2/pcsx2#3062]
***PCSX2 version:***
Stable build v1.4.0

***Description of the issue:***

Running the emulator displays these messages in the console:

> ./PCSX2: Symbol `_ZN12wxTextBuffer6ms_eofE' has different size in shared object, consider re-linking
> ./PCSX2: Symbol `_ZN13wxStackWalker10ms_exepathE' has different size in shared object, consider re-linking
> free(): invalid pointer
> Aborted

***How to reproduce the issue:***

- Download and decompress PCSX2 1.4.0 Linux version from the website.
- Run ./PCSX2-linux.sh

***PC specifications:***

OS: Debian GNU/Linux Buster

**Comment by lightningterror** [comment]
How's 1.5?

**Comment by berarma** [comment]
I've tried the package from Debian and it works, it's 1.5. I couldn't find a package to download in the website.

I wanted to try 1.4.0 because the version in Debian ran terribly slow. I've finally built it from the latest git version and now it works fine. If it's just me having a problem with the 1.4.0 package from the website this issue can be closed.
