### ISSUE TITLE
Linux: GZ File Extensions Not Openong

### ISSUE THREAD

**Issue by trymeouteh** [PCSX2/pcsx2#3065]
***PCSX2 version:***
 v1.4.0

***PCSX2 options:***
All Default

***Plugins used:***
OpenGL (Hardware)

***Description of the issue:***
PCSX2 on Linux does not unpack .gz files. On Windows I remember when you launch a GZ file for the first time it will take a few minutes as it creates a tmp file and then it will load the game. On Linux it will create the tmp file but not finish it and you get stuck with a black screen in PCSX2.

I did try opening an ISO file in PCSX2 and it did work, so I know it is not all games but the file types.

***How to reproduce the issue:***
Pack an ISO game into a GZ file.
Launch the game in PCSX2 on Linux (Ubuntu)

**Comment by tadanokojin** [comment]
did you try 1.5.0?

**Comment by turtleli** [comment]
Probably the same issue as #1820.

**Comment by trymeouteh** [comment]
I am not good at building source code and I am new to linux (about 4 months). If this is an issue that has been fixed and will be added in the next stable release, I can wait until it comes out and in the meanwhile I can uncompressed my games from GZ to ISO files.

**Comment by trymeouteh** [comment]
Can anyone confirm this has been fixed and will be put in the next release?

**Comment by LeCharlatan** [comment]
Isn't time to close this issue ?
By the way, @trymeouteh Welcome to Linux world :D
