### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by niko1point0** [PCSX2/pcsx2#3067]
Hi, I was wondering. What kind of things are being worked on? What is being prioritized? Are members of this project working on improving Multithreaded Vector Units? Is Vulkan a priority? What roadblocks are there in this project? 

Thanks!

**Comment by tadanokojin** [comment]
This sort of thing is more for the forums https://forums.pcsx2.net/

Please create a thread and I'll answer you there.

**Comment by niko1point0** [comment]
How do I create a thread on the forum?

**Comment by bositman** [comment]
https://forums.pcsx2.net/misc.php?action=help&hid=5

**Comment by niko1point0** [comment]
Says I might not have permission to post a new thread

**Comment by willkuer** [comment]
That’s correct. You might fail. Apparently you need to take a risk and give it a try.

**Comment by niko1point0** [comment]
I can't try it, I don't have permission

**Comment by niko1point0** [comment]
Hey guys, I have been thinking about adding a Vulkan backend to PCSX2, but I am still having difficulty with the forums. If there is no way for me to get information about the emulator without going through forums, then I don't know if I can help. Regardless, I am still a huge fan of the PCSX2 project, and I want to help. I have been writing a series of Vulkan tutorials that might be helpful to the PCSX2 team. I hope this is helpful

bit.ly/programgames

Here, you'll find 15 (so far) Vulkan tutorials. This is a University website, but it is free for anyone to use.

**Comment by lightningterror** [comment]
It is better to get in touch with @tadanokojin and @JibbityJobbity regarding Vulkan, well better to join us on discord if you want to contribute :)

**Comment by niko1point0** [comment]
Ok, can you tell me where can I find the discord? Is there a URL?

**Comment by KrossX** [comment]
There you go: https://discord.gg/TCz3t9k

**Comment by JibbityJobbity** [comment]
The jist right now is I'm waiting around for another fix in gui code. You can check out [here](https://github.com/tadanokojin/pcsx2/tree/gsdx-vulkan) for what we've currently got.

**Comment by tadanokojin** [comment]
Yes sorry I'm so slow ;)

**Comment by niko1point0** [comment]
Which discord channel should I use to discuss Vulkan?

**Comment by bositman** [comment]
If you can't figure out how to communicate online i very seriously doubt you can help with a Vulkan backend...in any case you can just DM kojin or JibbityJobbity

**Comment by niko1point0** [comment]
I did figure it out
