### ISSUE TITLE
[Linux] Gui elements of Emulation Settings not visible

### ISSUE THREAD

**Issue by Kastakin** [PCSX2/pcsx2#3069]
**PCSX2 version:** 
1.4.0 Stable and 1.5.0.r2255.43d0bd99c

**PCSX2 options:** 
No settings modifications affect the issue.

**Plugins used:** 
GSdx, SPU2-X, the others are the default one provided with the installation.

**Plugin settings:** 
No settings modifications affect the issue.

**Description:**
The GUI for the emulation options is not completely shown, in particular the checkbox to use the presets and the "apply/cancel/ok" buttons are not visible. It's impossible to resize the window in its height, only the width is resizable.
Both versions I tried had the same issues with minor differences:
The GIT version has the bottom part of the interface completely hidden, in the stable version (1.4.0) the elements are barely visible, it's possible to untick the checkbox and click on the buttons but only few pixels of them are visible.

I'm attaching a screenshot of the stable version where it's possible to see how the GUI elements are barely visible
![Schermata da 2019-08-13 14-45-42](https://user-images.githubusercontent.com/15200602/62942681-1aff4280-bdd9-11e9-81ef-df1a1cd887a4.png)

Here you can see how the GIT version is missing those elements entirely
![Schermata da 2019-08-13 16-39-02](https://user-images.githubusercontent.com/15200602/62950883-3f631b00-bde9-11e9-9f43-6ee0baa0b3c1.png)

I also noticed while looking at the build.log generated during the makepkg execution that I get some warnings, I don't really know if they are related anyhow but here you can find a Pastebin with the content of the log file:
[pcsx2-git-1.5.0.r3242.ed6ac0018-1-x86_64-build.log](https://pastebin.com/jWMkZ1SL)

**How to replicate:**
Install the stable version from the package manager or git clone and build from source the GIT version.

**Last known version to work:**
No idea, first time trying to install PCSX2 on a linux system.

**PC specifications:** 
CPU: Intel i5-5200U @ 2.70GHz 
GPU: Intel® HD 5500
RAM: 8GB
OS: ArchLinux 64bit
KERNEL: 5.2.8-arch1-1-ARCH

**Comment by Kastakin** [comment]
More testing on the issue:
I revived an update for pango on my system, I tried to recompile again but no differences whatsoever.
I also connected a secondary screen of bigger dimension than the one I used when taking the screenshots yesterday so that I could see if it was a problem of the window overflowing the screen. The results are that the buttons are still completely absent in the GIT version but I was wrong evaluating the stable version: the GUI elements are not being cropped by the screen size, they overflow the floating window with no way to resize it (as I previously mentioned in my original post).

**Comment by Kastakin** [comment]
I found out something strange:
If I open the emulation settings from my main monitor (1600x900 resolution) the buttons are not rendered, even if I move the window to my secondary monitor nothing appears.
But... If I start PCSX2 in my secondary monitor (1680x1050 resolution) everything shows up with no further issues, the buttons and all the GUI elements are there.

**Comment by LeCharlatan** [comment]
Hi @Kastakin 

That's really a weird issue :o
What command did you use to build pcsx2, you didn't show it on your log file.
If you built a "portable" version, I may try to launch it on my Linux Arch-based if you upload it x)

**Comment by Kastakin** [comment]
Hey @LeCharlatan 

I got the source files from the corresponding AUR ([Here](https://aur.archlinux.org/packages/pcsx2-git/)) and run a makepkg on the [PKGBUILD that comes with that](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pcsx2-git).

**Comment by LeCharlatan** [comment]
Hi Kastakin,

Yeah that is not a portable version.
Then may you try this portable built version and tell if GUI still weirdo ?

[PCSX2-test.tar.gz](https://github.com/PCSX2/pcsx2/files/3530501/PCSX2-test.tar.gz)

NB: Just extract it and run "PCSX2-linux.sh", you will have to set configurations tho.

**Comment by Kastakin** [comment]
Same behavior for some reason

**Comment by LeCharlatan** [comment]
I wonder if your system isn't missing some GTK themes, fonts or anything like that affect the GUI cause here it's well displayed.

I don't have any other clue, I just think that issue is not PCSX2's blame x)

What's your Desktop environment ?

**Comment by Kastakin** [comment]
I'm using GNOME

**Comment by LeCharlatan** [comment]
Okay, using KDE Plasma here, wonder if Gnome's windows manager send wrong values then the windows is much too high.

I could try Gnome through Live Manjaro when get some free time x)

**Comment by RedPanda4552** [comment]
I fired up PCSX2 in a Manjaro VM with a display resolution of 1920x1440. The Gamefixes tab appears to be occupying around 60-65% of the vertical space. 60% of 1440 is roughly 864, which is conveniently just beyond your monitor resolution. I don't think the issue is that it's "not rendering", I think we just have a case of the window being too large for your display. And the problem with that, is that this window also isn't resizable.

Solutions? Add scrolling and/or resizing to the window. That said, this probably needs to wait until the 1.7 lifecycle and 1.8 milestone.
