### ISSUE TITLE
Memleak: Tennis no Oji-Sama - Smash Hit! 2 (Hang when memory 1,500,000K+)

### ISSUE THREAD

**Issue by willbaird** [PCSX2/pcsx2#307]
When going to "Config > Video(GS)> Plugin Settings... > OK" memory will go down than 220,000K

Memory raises till 1,500,000 over time and then hangs.

Same issue all different plugins / software mode

**Comment by MrCK1** [comment]
@willbaird Can you reformat your bug report according to the template [here](https://github.com/PCSX2/pcsx2/blob/master/ISSUE_TEMPLATE.md)? Thanks!
