### ISSUE TITLE
Onimusha Warlords: intro cinematic failed to play

### ISSUE THREAD

**Issue by legluondunet** [PCSX2/pcsx2#3070]
***PCSX2 version:***
PCSX2 1.5.0-0 - compiled on Aug 10 2019 

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
Hello, intro cinematic does not play correctly, stop after 1 second playing.

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Launch the game and stay at the first screen "PRESS START BUTTON", wait a minute, a cinematic should play but you only playing 1 second, then close.

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Ubuntu 19.04

**Comment by legluondunet** [comment]
I joined you 
[onimusha_log.txt](https://github.com/PCSX2/pcsx2/files/3498278/onimusha_log.txt)
the log file

**Comment by seta-san** [comment]
i'm not sure what to make of this one. the NTSC version plays the video.. but then again the ntsc version is 3.9GB. The PAL version is 2.1GB and looks like it wants to start playing the video but doesn't and skips right to a cinematic closer to in-game.

the opening cinematic is a pretty long video and i just wonder if they didn't just drop it for some reason on the PAL version. anyone with a pal ps2 could test on hardware.

**Comment by refractionpcsx2** [comment]
That video does *NOT* play on the PAL version.

**Comment by Tzerinas** [comment]
> That video does _NOT_ play on the PAL version on PCSX2.

It was in response to seta-san asking if anyone could test if the video is even played on the PAL Version by testing it on hardware. That video, from what I can tell, is the Pal Version on PS2.

**Comment by seta-san** [comment]
Look at the size difference between the two
NTSC version. 
http://redump.org/disc/3769/

PAL
http://redump.org/disc/720/

That video is the pal version and it sort of confirms my suspicions. This issue was likely made based on a bad dump that is probably ubiquitous online because the info on redump seems to be based on the same bad dump. This issue is most likely invalid.

**Comment by refractionpcsx2** [comment]
Buying a fresh copy, so we'll find out

![image](https://user-images.githubusercontent.com/6278726/171870975-4cf78b26-47d4-411a-b36b-a422285fd69d.png)

**Comment by refractionpcsx2** [comment]
It still skips it completely here.... But I will get a new copy of the game in a few days and confirm if it's a dump problem.

It literally flashes up one frame them disappears here.

**Comment by refractionpcsx2** [comment]
Okay that makes more sense, and my video does play with that setting.

**Comment by seta-san** [comment]
Bad dump with a compressed iso leading to cdvd timing issues?

**Comment by refractionpcsx2** [comment]
I did have a quick look at this, at normal cycle rate I'm not quite sure what's going on.... it starts an FDEC command (skip n bits then return the next 32bits of the bitstream) after clearing the input and turning off IPU_TO DMA, but the command never finishes, because the game never starts IPU_TO DMA or sends any data in the FIFO.  So eventually the game just gives up and cancels the movie.

I'm not sure why it's different with a different cycle rate, it's very strange..

**Comment by seta-san** [comment]
What does it do on the ntsc version?

**Comment by refractionpcsx2** [comment]
Not sure, didn't look.  But the size discrepancy is apparently because the NTSC version also contains the japanese FMV's.

**Comment by refractionpcsx2** [comment]
Although it's a moot point now, I can indeed confirm that the disc is 2GB for the EU region, as I just ripped the copy I got in the post

![image](https://user-images.githubusercontent.com/6278726/172650692-48931043-b3d6-479a-9903-6e7bbf30adf8.png)


![image](https://user-images.githubusercontent.com/6278726/172650820-c4085efc-1501-4ffb-9272-f151f1e67757.png)

**Comment by seta-san** [comment]
Well. Insane timing issue it is. How to make the Ipu respond faster?

**Comment by refractionpcsx2** [comment]
I doubt it's as simple as that....

**Comment by refractionpcsx2** [comment]
It's likely expecting more bus contention with IPU and CPU I guess, which of course we can't *really* simulate (apart from having instant DMA's), which is an idea floating around, but need to think how to tackle it well

**Comment by legluondunet** [comment]
when I start a new game, I can see a cinematic:
![image](https://github.com/user-attachments/assets/7335fe4c-0d1e-4f7f-8cca-15016fd0beaa)

![image](https://github.com/user-attachments/assets/639a3747-86cf-4273-aa7f-56e7ed802a89)

**Comment by legluondunet** [comment]
Thank you PCSX2 team! The 2.0 stable version is such a great emulator and available even on Linux!
