### ISSUE TITLE
Directory in the launcher [feature request]

### ISSUE THREAD

**Issue by Kzitold** [PCSX2/pcsx2#3078]
You know how the emulators Dolphin and PJ64 shows the directory in the launcher so you don't have to use the menu buttons at the top? Any chance of doing that here?

The reason being livingroom TV, where you wouldn't want to have to use a mouse.

**Comment by tadanokojin** [comment]
Sorry, not sure I understand can you elaborate?

**Comment by Vyktory** [comment]
Dolphin allows you to set a folder as a point to print a list of game ISOs to the program's front end. It includes some icons and basic information about said games too.

**Comment by refractionpcsx2** [comment]
Already done in Qt
