### ISSUE TITLE
[Jojo no Kimyou na Bouken - Ougon no Kaze] 80-100% GPU usage and slowdown on OpenGL, 10-30% usage and 60 FPS on DirectX 11 (GTX 1070)

### ISSUE THREAD

**Issue by Reonu** [PCSX2/pcsx2#3083]
***PCSX2 version:***
1.5.0-dev-3260-g33571dd

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
Default speedhacks + MTVU and fast CDVD

***Plugins used:***
GSDX AVX
Running at 3X native, everything else default

GSDX dump in OpenGL mode (GPU usage was 99% and there was slowdown):
[OpenGL.zip](https://github.com/PCSX2/pcsx2/files/3513290/OpenGL.zip)
GSDX dump in DX11 mode (GPU usage was 10% and it was 60 FPS):
[DX11.zip](https://github.com/PCSX2/pcsx2/files/3513291/DX11.zip)
***Description of the issue:***
In DX11, the performance is perfect and the GPU usage is very low. In OpenGL, the emulator is suddenly GPU bottlenecked. 

***How to reproduce the issue:***
Play with OpenGL and with DX11, compare performance

***Last known version to work:***
Don't know.

***PC specifications:***
i7 6700k @ 4.2 GHz
16 GB DDR4 2400 MHz 15-15-15-35 RAM
GTX 1070
Windows 10 64 bit

**Comment by lightningterror** [comment]
It might be blending related, I'm seeing `FBMASK SW emulated fb_mask:1 on 16 bits format` used a lot here. Disabling Blending provides quite a high performance boost on my end.

Can you compare both dx and gl with blending disabled, next compare dx blending set to high vs gl blending set to basic.

**Comment by Leon422** [comment]
Note: On DX11, the emulator caps itself to 144 FPS (my refresh rate) no matter what, even though vsync is "disabled". If PCSX2 is not in focus, this limit dissapears. So for the DX11 tests I had Firefox on focus instead of PCSX2.
On the same scene:
GL with blending disabled: ~260 FPS
DX11 with blending disabled: ~350 FPS
DX11 with blending on high:  ~40 FPS
OpenGL with blending on basic: ~58 FPS

Do you need dumps for all these cases?

**Comment by lightningterror** [comment]
Previous dumps are enough to test various settings, thanks.

**Comment by lightningterror** [comment]
The performance issues have been resolved on all renderers now, game will run full speed.
