### ISSUE TITLE
World Rally Championship (SLUS-20419) - Spikey Car Issue

### ISSUE THREAD

**Issue by Yohokaru-96** [PCSX2/pcsx2#3087]
PCSX 2 1.50-dev-3243-gaf6f04020

SETTINGS:

![image](https://user-images.githubusercontent.com/54458215/63628394-900a1d80-c60c-11e9-8513-23b37cc267a9.png)

![image](https://user-images.githubusercontent.com/54458215/63628409-a3b58400-c60c-11e9-88f3-b4ecad0c8470.png)

![image](https://user-images.githubusercontent.com/54458215/63628433-c47dd980-c60c-11e9-9a0b-adf722d09b19.png)

The car does not render properly in NTSC version of the game, settings as above, similar setting work on PAL version.

![image](https://user-images.githubusercontent.com/54458215/63628513-2b02f780-c60d-11e9-9882-509001c250f2.png)

![image](https://user-images.githubusercontent.com/54458215/63628518-31916f00-c60d-11e9-95c1-1a40bde0059a.png)

PC Specs:

Intel i5-7300HQ
Nvidia Geforce GTX 1050
8GB RAM
Windows 10 rev1903

**Comment by lightningterror** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/1624
