### ISSUE TITLE
World Rally Championship (SLUS-20419) - Selecting Subaru Impreza Crashes the Game

### ISSUE THREAD

**Issue by Yohokaru-96** [PCSX2/pcsx2#3088]
PCSX 2 1.50-dev-3243-gaf6f04020

SETTINGS:
![image](https://user-images.githubusercontent.com/54458215/63628631-ca27ef00-c60d-11e9-9c8e-51789fa97ab1.png)

![image](https://user-images.githubusercontent.com/54458215/63628633-d3b15700-c60d-11e9-8317-e93767e6b25e.png)

![image](https://user-images.githubusercontent.com/54458215/63628640-dc099200-c60d-11e9-80e9-8b178ef9afc5.png)

As the title says, selecting Subaru Impreza in any rally crashes the game, issue appears in both PAL and NTSC releases of the game.

![image](https://user-images.githubusercontent.com/54458215/63628700-2b4fc280-c60e-11e9-9b8f-b02f9fc64149.png)

PC Specs:

Intel i5-7300HQ
Nvidia Geforce GTX 1050
8GB RAM
Windows 10 rev1903

**Comment by refractionpcsx2** [comment]
Since it hasn't been mentioned here yet, further testing has shown the crash goes away if you use the EE Interpreter, so flagged this as a recompiler bug.

**Comment by refractionpcsx2** [comment]
This is now fixed in master
