### ISSUE TITLE
Fedora 32 will not support i686

### ISSUE THREAD

**Issue by chemelnucfin** [PCSX2/pcsx2#3089]
***Description of the issue:***
I got word that i686 is a secondary arch in Fedora and will be dropped in F32 and currently the package is retired for F30.  I might be able to install the old packages until that point but not sure what can be done to continue using PCSX2 in Fedora.

***How to reproduce the issue:***
on Fedora 30
`dnf install PCSX2`

***Last known version to work:***
Fedora 29

Might be related to #3021 and #1027

**Comment by arcum42** [comment]
Well, dropping the ability to install on i686 and dropping multilib support are two different things. If multilib is still on there, it should still compile. If multilib is gone, then pcsx2 won't work... and steam, wine, and half your gaming library will stop working as well. Lots of things still need 32-bit support.

**Comment by gregory38** [comment]
Yes don't mix things.

You have pure 32 bits. Kernel 32 bits and 32bits app. Good for very old hw or low mem hw.

And you have multilib. 64 bits kernel and 32 bits app. Kernel will switch CPU to 32 bits mode (it is native, 0 emulation).

**Comment by chemelnucfin** [comment]
> It was retired as it had no active maintainer to fix it, as it been dead for a while it would require a new package review.
> 
> I really doubt it would pass as it doesn't support any primary arch eg: x86_64, armfp or aarch64.
> 
> i686 is a secondary arch which is dropped for f32.

These were the exact words.  So what would be the best way to get the package back into Fedora now and for future cycles?

**Comment by mirh** [comment]
Just follow [the normal guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/)?

**Comment by chemelnucfin** [comment]
Actually got it to load using [flatpak](http://emulation.gametechwiki.com/index.php/Distro-agnostic_emulator_packages_for_Linux)
then
`flatpak --filesystem={bios_directory} run net.pcsx2.PCSX2`

I'll leave it to you guys to determine to close this issue or not for future fedora issues.

**Comment by turtleli** [comment]
Closing:
 * From what I read, only 32-bit kernels and bootable images have been dropped from Fedora 31 onwards - https://fedoraproject.org/wiki/Changes/Stop_Building_i686_Kernels
 * rpmfusion have updated their PCSX2 package.
