### ISSUE TITLE
Transformers PAL-EU (SLES-52388): Cannot move right/backwards at full speed

### ISSUE THREAD

**Issue by sotpapathe** [PCSX2/pcsx2#3093]
***PCSX2 version:***
v1.5.0, commit 014753894aea1db2eb06ad0cbda483099c2e1dda.

***PCSX2 options:***
Both software and hardware mode.
MTVU: Disabled (game does not start otherwise)

***Plugins used:***
- GSdx 1.1.0 AVX2
- SPU2-X 2.0.0
- OnePAD 0 1.3.0 and OnePAD 0 2.0.0

***Description of the issue:***
When pushing the left analog stick all the way to the right/back, the character does not move at full speed. All other movement directions work properly. Changing the joystick sensitivity has no effect. Reversing the axis direction (so that pushing forwards moves backwards) does not change anything. The problem remains when the in-game character moves right/backwards (pushing the stick left, forwards). 

Looks like it's not a problem with reading the controller input but with passing it to the game. Also the fact that it happens in only one direction makes me suspect the issue is the fact that ints in 2's complement can store one extra negative value than they do positive values.

***Last known version to work:***
Confirmed not working since commit 0814690534e585bf4e74da131d439ba2e087080f. Don't know of a working version.

***PC specifications:***
- Solus, Linux kernel 5.2.7
- Intel Core i5-4570 CPU @ 3.20GHz
- NVIDIA GeForce GTX 760 2 GB

**Comment by sotpapathe** [comment]
Also had the same issue in Ratchet & Clank: Size Matters in PCSX2 v1.6.0 again on Linux. In Ratchet & Clank: Size Matters I could move in any direction at full speed with the directional buttons but not right or backwards with the analog stick.

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by sotpapathe** [comment]
Tested nightly v1.7.3341 on Linux on both Transformers and Ratchet & Clank: Size Matters and the issue has been fixed. Thank you!
