### ISSUE TITLE
Growlanser 3: Allies recognized as enemies?

### ISSUE THREAD

**Issue by Ronnie21093** [PCSX2/pcsx2#3098]
PCSX2 version: v1.5.0-dev-3274-gd3ecec5d6
PC Specs: Win7 64-bit, Intel Xeon E5 1620m 16 GB of RAM, GTX 1070
Ran with all options on default

So in my first random battle, I found a new problem. For some reason, the game recognizes party members as enemies you have to defeat (As in, you can select them and attack them)

Additional problems: During a random battle, enemies and allies (other than the main character) refused to move, and enemies randomly took damage (Even dying without the main character attacking)

**Comment by Ronnie21093** [comment]
Update: The issues only seem to occur when I run cheats. No issues occur when no cheats are running.

**Comment by lightningterror** [comment]
Not a valid issue since cheats cause the issue.
