### ISSUE TITLE
Add a tickbox to Enable/Disable Exclusive Fullscreen [Feature Request]

### ISSUE THREAD

**Issue by Jorge9811** [PCSX2/pcsx2#3101]
Setting EnableVsyncWindowFlag to enabled in pcsx2\inis\PCSX2_ui.ini fixes stuttering while playing games on PCSX2.
I noticed an improvement with Dragon Ball Z: Infinite World on my machine. The fights felt slower than they should when I had it set to "disabled" as it is by default.

Why is this not a thing yet? Hiding such an option behind a .ini modification is kinda silly.

**Comment by lightningterror** [comment]
Duplicate:
https://github.com/PCSX2/pcsx2/issues/1956
https://github.com/PCSX2/pcsx2/issues/2307
https://github.com/PCSX2/pcsx2/issues/2058
