### ISSUE TITLE
Midnight Club II - missing car light beams when using OpenGL HW

### ISSUE THREAD

**Issue by madmanxxx** [PCSX2/pcsx2#3102]
***PCSX2 version:***
PCSX2 1.5.0 r3279.f2b402b0c, same happens on 1.4

***PCSX2 options:***
OpenGL HW + defaults, but changing presets / graphics options or hacks does not change this behaviour, unless when using OpenGL software renderer.

***Plugins used:***
GSdx, ZeroGS

***Description of the issue:***
There's no visible light on textures in front of the car when using OpenGL HW, they do show up when using OpenGL SW. I'm on Linux, so unable to use DirectX. 

***How to reproduce the issue:***
Start the game and get into the first race. I use PAL version, but I've seen the same issue on some online gameplay videos (probably NTSC), like this one https://youtu.be/OWcvrHDXlS4?t=125 - the player flashes the beams and the opponent starts driving, except that no flashing is visible... GS dump available here: [gsdx_20190905003518.gs.gz](https://github.com/PCSX2/pcsx2/files/3576759/gsdx_20190905003518.gs.gz)

***PC specifications:***
Intel Core i5-4210, NVidia GeForce 820M, Arch Linux updated today.

**Comment by tadanokojin** [comment]
Issue is a TS on the headlights. Similar to #2327 but it is not a half-screen issue. Will look more when I get a chance.
