### ISSUE TITLE
Harry Potter and the Sorcerer's Stone - Shadow and lighting problems

### ISSUE THREAD

**Issue by ToniBC** [PCSX2/pcsx2#3103]
- PCSX2 1.5.0-dev-3278
- System: Windows 10 64bits
- CPU+GPU: i7-7700k + GTX 970
- Preset: Safe
- Plugin: OpenGL (Hardware) + SPU2-X
- Accurate Blending: Basic
- Game Region: USA

The game has several problems with shadows and lighting, in some areas they are represented incorrectly.

![Harry Potter and the Sorcerer's Stone (USA) (En,Es)](https://user-images.githubusercontent.com/45365478/64417038-a39b9680-d098-11e9-85e7-dbae7d09f7d1.jpg)

**Comment by lightningterror** [comment]
Can you upload a gsdump?

**Comment by ToniBC** [comment]
The lighting error makes the walls have no texture. Here I leave the gsdump.

[HP1 Lighting Error.zip](https://github.com/PCSX2/pcsx2/files/3585969/HP1.Lighting.Error.zip)

**Comment by lightningterror** [comment]
Full Blending is needed on OpenGL to render the effects properly. DX lacks impossible blend so that's a no go.

**Comment by ToniBC** [comment]
Ok, thanks, I just tried to the high level, not the full one. To put it in full, everything is well represented and it seems that the performance does not decline in this game except for some parts that slow down for a few seconds, but then remain normal, as if loading something in memory.
