### ISSUE TITLE
Need for Speed Carbon - slowdowns and lighting errors

### ISSUE THREAD

**Issue by ToniBC** [PCSX2/pcsx2#3104]
PCSX2 1.5.0-dev-3278
System: Windows 10 64bits
CPU+GPU: i7-7700k + GTX 970
Preset: Safe
Plugin: OpenGL (Hardware) + SPU2-X
Accurate Blending: Basic
Game Region: PAL

The game has many serious slowdowns on the menu, losing 10-15% of speed and racing, where it drops to more than 20% at the beginning of them.

It also presents errors in the representation of some textures or colors, where if we put the Accurate Blending in Basic / Medium they look bad, only in High they look correct, but the game works at 10% of its speed.

Accurate Blending Basic/Medium
![1280px-NFS_Carbon_Blending_(Basic-Medium)](https://user-images.githubusercontent.com/45365478/64417723-ead65700-d099-11e9-9607-d2833ecf8faa.jpg)
Accurate Blinding High
![1280px-NFS_Carbon_Blending_(High)](https://user-images.githubusercontent.com/45365478/64417765-f7f34600-d099-11e9-89b5-53138c91c1e2.jpg)

**Comment by lightningterror** [comment]
Lighting is not an issue if High blending solves it, seems this game likes to hammer the gpu quite heavily.

**Comment by ToniBC** [comment]
Yes, the emulator needs a rewrite or reinterpretation to solve these problems that are present in many games. The issue of shaders, transparencies and other things emulators like CEMU use a cache, could be the solution for speed problems in all games. Even Demul or Reicast also use a shader cache for that purpose.

I'm not a programmer, so it may not be the same, but it could be the solution.

**Comment by lightningterror** [comment]
Game will be playable at High Blending with Vulkan now even with upscaling.

**Comment by ToniBC** [comment]
At the moment, even with Vulkan, the game still does not work, too slow.

**Comment by JordanTheToaster** [comment]
> At the moment, even with Vulkan, the game still does not work, too slow.

What GPU do you have?

**Comment by ToniBC** [comment]
It is not a big thing, but it is not that it is little, average level today on PC and you have it in the first post.

The problem is that the Blending implementation is not polished, a new system or other solutions are needed, because with the value of high, the games lower their performance to 10/20 fps. If you need a $ 2,000 system to be able to play NFS or other full-fledged games, something is clearly wrong.

I'm not a programmer, just fond of emulation, but seeing the progress of Switch, Dolphin, PCSX3, etc ... that rethinking systems or doing things differently is the solution to these problems.

Vulkan was only added, when almost all emulators have used it for years. We have a x64 version that is not even listed on the official website, but it can be compiled.

Saying that a problem is solved if you have a NASA PC, for a system like PS2, is not the solution nor is it solved. More than anything, because now that we are talking about the mobile version, what do you need there, a high-end mobile that will be released in 15 years.

And sorry, it's not a criticism or anything. It's just a point of view. I like and use this emulator a lot.

**Comment by lightningterror** [comment]
With the addition of #5452 both opengl and vulkan receive a substantial increase in fps on high blending.

**Comment by ToniBC** [comment]
It is true that performance is increased, going from 22% speed in High Blinding OpenGL to 80% in Vulkan, which still feels insufficient, even in native resolution. But this mode is still very demanding and affects the effects of many games.

It is necessary to optimize the mode or find other ways to replicate the same without increasing resources. Use caches or systems similar to those used by other emulators such as Yuzu, Cemu, Dolphin, etc...

**Comment by JordanTheToaster** [comment]
Your GPU is insufficient for running the most demanding games with higher blending it's honestly that simple.

**Comment by ToniBC** [comment]
Things are not fixed by increasing the power of the machine, rather by optimizing and finding solutions to problems. PCSX2 has existed for years and the performance problems of before, the answer was the same, lack of power, for many games you needed a PC that does not exist yet, so that certain games work at 100%. Now, they just added Vulkan support, increasing performance with the same requirements and with them, being able to run on Android.

So the “Lack of power” excuse is not that simple, it is invalidated when we see things like this just by adding Vulkan.

According to what they say, if the purpose or idea is for the emulator to work on Android or they are interested in that, a lot of optimization is needed and that is not to say, it will work on mobile phones in 10 years.
