### ISSUE TITLE
Linux: ONEPad not reading xbox controller

### ISSUE THREAD

**Issue by trymeouteh** [PCSX2/pcsx2#3108]
***PCSX2 version:***
development builds v1.5

***Plugins used:***
Default Setup

***Description of the issue:***
When I go to Config->Controllers (PAD)->Plugin Settings... and I click on a button I want to program my controller does not get picked up. My controller does works since it is read in other games.

I did try changing the controller plugin to the ONEPad Legacy and I was able to read my controller.

***How to reproduce the issue:***
Plugin a Xbox 360 controller into your computer
Launch PCSX2
Go to Config->Controllers (PAD)->Plugin Settings... and I click on a button I want to program my controller does not get picked up. 

***Last known version to work:***
I think it worked in the stable version 1.4.0

**Comment by Leopard1907** [comment]
I don't think that is an issue. I was also surprised as well and thought that is not picking up my input. I was told that OnePad automatically maps controller if it recognizes it. So i tried on multiple games and controller just worked.

A bit confusing but those mapping options are just there for keyboard mapping. Not for controller.

I suggest you to try it on a game.

**Comment by lightningterror** [comment]
Controller mapping is done automatically on onepad, you can map the controller on onepad legacy.

See https://github.com/PCSX2/pcsx2/issues/2495 for more information.

Closing as duplicate.
