### ISSUE TITLE
[Feature Request] Update PPA build to wxWidgets based on GTK3

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#3113]
PCSX2 version:
1.5.0-dev from official unstable PPA: https://launchpad.net/%7Epcsx2-team/+archive/ubuntu/pcsx2-daily

Description of the issue:
If possible, please update the build process from the PPA to use wxWidgets based on GTK3 instead of GTK2, because GTK2 is deprecated by some distros and others will follow. 

Currently it uses wxWidgets v3.0.4 based on GTK 2.24:
![wx_pcsx2](https://user-images.githubusercontent.com/30773753/65175080-ab1c5180-da41-11e9-98db-d55a2dc34a3c.png)

**Comment by rtentser** [comment]
Can be relevant for debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933441.

**Comment by rikmills** [comment]
GTK2 wxWidgets is being dropped in Ubuntu 20.04 as well. If you want to proved build with that as a base, you will have to switch.

**Comment by guoyunhe** [comment]
I am also looking for this feature! Cannot build it with GTK3 in openSUSE...

**Comment by XXXBold** [comment]
Since at least Ubuntu 20.04, the build now uses GTK3. closing this.
