### ISSUE TITLE
Gitaroo Man (NTSC-U) [SLUS-20294] - Blank/disappearing face in Stage 8

### ISSUE THREAD

**Issue by boringhexi** [PCSX2/pcsx2#3118]
***PCSX2 version:***
v1.5.0-dev-3290-gd92e4343e 	(i.e. 2019-09-22 03:00:52 from the buildbot)

***Description of the issue:***
Gitaroo Man (NTSC-U) SLUS-20294 blank face bug: the opponent's face disappears at a certain moment in Stage 8 (see How to reproduce).

![screenshot blank face](https://user-images.githubusercontent.com/36807140/65392516-c938c900-dd43-11e9-9913-dac4988badf4.png)

***PCSX2 options:***
Default settings with the Safest preset.

In other tests (which all resulted in the same visual bug or just made him explode into polygons), I disabled Automatic game fixes and tried various Clamping/Rounding settings:
- all combinations of the EE/IOP Round/Clamp choices, with VU Round/Clamp set to their Safest defaults.
- all combinations of the VU Round/Clamp choices, with EE/IOP Round/Clamp set to their Safest defaults.

***Plugins used:***
- GSdx SSE2 with Direct3D 11 (Software) renderer
Everything else is default plugins/default settings.

GS dump: [gsdump blank face.zip](https://github.com/PCSX2/pcsx2/files/3640041/gsdump.blank.face.zip)

***How to reproduce the issue:***
Load a complete save game from [Gitaroo Man (NTSC-U) memcard.zip](https://github.com/PCSX2/pcsx2/files/3640043/Gitaroo.Man.NTSC-U.memcard.zip) through the in-game Options menu. Go to Single Play -> Stage 8. Play the stage until the opponent says "Beauty is a sin! Oh God!" and as he throws his arms back dramatically, his face will disappear.

(If you'd rather not actually play the stage, you put `patch=1,EE,0017820c,word,10000026` in 7130C553.pnach to keep from losing, then just wait until it gets to that part.)

***Last known version to work:***
(Despite the SVN numbers, these are three git commits in a row, with no commits in between them.)
- SVN 4282, i.e. https://github.com/PCSX2/pcsx2/commit/e2d36a53a4e3396ade8d008186c1ee2069903d49: last known version to display his face properly.
- SVN 4287, i.e. https://github.com/PCSX2/pcsx2/commit/ca7abd983aed6762efa41d0c51b4bbbfb84134b5: probably introduced the problem, but I couldn't build it until the next commit's VS2008 fix.
- SVN 4288, i.e. https://github.com/PCSX2/pcsx2/commit/77f392edac1806fcba929dd72b7775dd850f8d6c: the first version I was able to build that has the blank face bug.

***PC specifications:***
- CPU: Intel Core i5-2450M
- GPU: Intel HD Graphics 3000
- OS: Windows 10 Pro (64 Bit, Version 1903, build 18362.356)

For what it's worth, I've also seen this problem on recent Linux PPA builds (in Ubuntu 18.04, running on the same hardware with GSdx's OpenGL software renderer). I don't know if the git commits above apply to the Linux version.

***Additional info:***
In Gitaroo Man, it seems face animations work by copying one region of a texture and pasting over to another region. (There may be a little more to it than that.) One particular face is causing this bug, due to the relationship between the copied and pasted coordinates.

In my attempt to figure out why the problem happens, I hacked the coordinates of the copied texture region to make the animation below. The left side shows the visual bug in PCSX2, and the right side is how it should look if the bug were fixed. Below that it shows the texture: the red box is the copied region, and the green box indicates where it's pasted to.

![face demo](https://user-images.githubusercontent.com/36807140/65392569-45331100-dd44-11e9-84c9-82dbc1a11ef6.gif)

As the gif shows, the problem happens when the copied region extends off the left edge of the pasted region, and the problem disappears the moment the left edge of the copied region meets the left edge of the pasted region.

(Unrelated to the gif above) If it would be helpful, I can provide a savestate in which I've tracked down the exact value in memory responsible for the problem just before it becomes visible in normal gameplay. (Unfortunately, when I set a read breakpoint on this value, the debugger acts like the game never reads it back before overwriting it, even though there are obvious changes in-game when I edit that value.)

**Comment by refractionpcsx2** [comment]
Is this still an issue? If it is, can we get a multiframe GS Dump of the whole transition made in software mode?

**Comment by boringhexi** [comment]
@refractionpcsx2 Yes, still an issue as of today's daily Ubuntu build, `3:1.7.0~git202201161154+202201170333~ubuntu20.04.1`. (I hop between Windows and Ubuntu often, and while I haven't checked Windows in a while, historically the issue has been consistent between the two).

> can we get a multiframe GS Dump of the whole transition made in software mode?

Sure thing! Assuming I did it right, [here it is (12.3 MB, 157 MB when uncompressed)](https://drive.google.com/file/d/1__WptGq392ILXchbOd0VYOZg5av__kBr/view?usp=sharing). In this dump, the opponent's face quickly flashes blank and back a couple times before staying blank like in the OP screenshot. Let me know if you need something more precise or different, or dumped on Windows instead of Ubuntu, or anything like that.

**Comment by refractionpcsx2** [comment]
Can you please try #5601? Thanks.  I didn' notice it changing face, but I did stop the face disappearing, maybe I needed more dump to witness that.

**Comment by boringhexi** [comment]
I gave it a try today, and yes it seems to fix the issue.

**Comment by refractionpcsx2** [comment]
excellent :)
