### ISSUE TITLE
Emulation is way slower in general in latest git compared to 1.4.0, EE almost always 100% (Linux)

### ISSUE THREAD

**Issue by rotomdottom** [PCSX2/pcsx2#3128]
**PCSX2 version:**
v1.5.0-dev-3295

**PCSX2 options:**
All default, no settings modifications affect the issue.

**Plugins used:**
Default.
(It runs just as badly even with null plugins)

**Plugin settings:** 
Defaults, no settings modifications affect the issue

**Description of the issue:**
The whole emulation is extremely slow compared to 1.4.0.
This is noticeable as soon as I boot the system, even the first "Sony Computer Entertainment" BIOS screen doesn't run at full speed.
Tested various games but I'll take Katamari Damacy as an example, in the first stage, the game runs at 60-80% speed at most at native render resolution in HW (it does the same in software), by contrast in 1.4.0 the game runs full speed 100% of the time, even at 4x rendering resolution in hardware rendering or in software rendering.
In addition to running way slower in general it also frequently stutters.
I tried using the old SSE2 GS plugin from 1.4.0 and it runs just as badly, in fact, it runs just as badly even with null plugins.

**I've noticed EE seems to be maxing out almost all the time.**

**How to reproduce the issue:**

**Last known version to work:**
1.4.0 is the latest stable one I have access to from the repo, and it works fine there.

**1.4.0**
![Screenshot_20191001_180530](https://user-images.githubusercontent.com/4895173/66001804-a364a000-e478-11e9-82d6-f3805ed5c50d.png)

SW
![Screenshot_20191001_180353](https://user-images.githubusercontent.com/4895173/66001822-b2e3e900-e478-11e9-8b35-ff147f8a44c1.png)

HW 4x
![Screenshot_20191001_180513](https://user-images.githubusercontent.com/4895173/66001841-bd05e780-e478-11e9-8eb7-d1a0d0f5cbad.png)

**1.5.0(git)**
![Screenshot_20191001_180830](https://user-images.githubusercontent.com/4895173/66001875-ce4ef400-e478-11e9-8c53-e2601bb56fc7.png)

SW
![Screenshot_20191001_181037](https://user-images.githubusercontent.com/4895173/66001895-d60e9880-e478-11e9-942c-1e970e7d1380.png)

HW 1x
![Screenshot_20191001_181239](https://user-images.githubusercontent.com/4895173/66001913-e0309700-e478-11e9-834e-d009863b463d.png)

**PC specifications:**
CPU: AMD Ryzen 3400G
GPU: Vega 11 iGPU
RAM: DDR4 16GB 3Ghz
OS: Arch Linux x86_64

**Comment by orbea** [comment]
Are you capable of bisecting this to a specific commit?

**Comment by rotomdottom** [comment]
Ok, apparently I am an idiot, all of this was caused by not purging settings after removing 1.4.0.

Oops, sorry.

**Comment by orbea** [comment]
I wonder what setting was causing this?

**Comment by rotomdottom** [comment]
I can say it was none of the visible settings, they all reset when changing between versions, thinking it was probably just some conflicting old configuration file.
