### ISSUE TITLE
P key does not pause emulation. Is this unusual? 

### ISSUE THREAD

**Issue by DAXMO1** [PCSX2/pcsx2#3140]
***PCSX2 1.4.0***

- I've been using the emulator for a year or two but i'm just now trying out TAS runs. As i've figured out, pressing the P key is supposed to pause the emulation, like freeze frame it. That does not do so for me. I've pressed pretty much every key and could not find a pause button other than just the esc key. I thought there might be a key bind menu in the options but i didn't find one of those either. Am I missing something or is something wrong?

Also just remembered there is no movie tab at the top of my window either like there should be next to debug

***PCSX2 options:***
``Speedhacks``? ``Controls``?

- **Note**: Not exactly sure what to classify this as

***Plugins used:***
``Irrelevant`` Problem persists regardless it seems

***How to reproduce the issue:***
``?``

**Comment by RedPanda4552** [comment]
Looking back at the PR #2412 the keybind to pause while working with TAS is Shift+P.

Let us know if this is what you are looking for.

**Comment by DAXMO1** [comment]
shift+P does not work either
also the movie tab at the top of the window is non existent on mine

**Comment by lightningterror** [comment]
Works fine if you enable Recording Tools first.

![image](https://user-images.githubusercontent.com/18107717/67539271-e0236000-f6e1-11e9-8e5a-776bb5510a45.png)

**Comment by DAXMO1** [comment]
![k](https://user-images.githubusercontent.com/29589863/67539438-265fcb80-f6b0-11e9-9997-7549d8e3243c.PNG)

**Comment by lightningterror** [comment]
You should update then, anyway closing an invalid issue.

**Comment by DAXMO1** [comment]
didn't i state its version 1.4.0 above? I've seen videos of people using 1.4.0 and being able to pause with P and have a tab labeled movie at the top of the window

**Comment by lightningterror** [comment]
If you're using the latest dev builds you can easily pause with Shift + P, we don't support legacy (1.4).

Here is an example emulation being paused.

![image](https://user-images.githubusercontent.com/18107717/67540141-a2740680-f6e4-11e9-8fe1-83ac382a096b.png)

**Comment by RedPanda4552** [comment]
TAS features are a part of the current 1.5.0 development series and not present at all in 1.4.0. The hotkey to pause emulation has always been Esc, not P as well. If you really want to, you can try looking at the PCSX2 hotkeys file that is found next to the PCSX2 exe and making changes in there. However, there is not and has never been support for P being a pause key out of the box without the TAS changes.
