### ISSUE TITLE
SSX Tricky TAS: Glitch causing desyncing

### ISSUE THREAD

**Issue by DAXMO1** [PCSX2/pcsx2#3142]
***This is an SSX Tricky specific issue***
***PCSX2 1.5.0***

***PCSX2 options:***
``Default``

***Plugins used:***
``Default`` ``Direct3D 11(software)``

***Description of the issue:***
***https://youtu.be/-nB50CA87ho***
``At some point during playback, the rider starts teleporting like he hit a death barrier over nothing, just random. This happens just about every playback too. Sometimes a lot, sometimes a few times, but it always desyncs. Check the video link for an example.
Not sure what causes this, the only possibility i can think of is that my gamepad's right stick drifts a bit sometimes, causing the rider to shove. Maybe this causes it? Not sure``

***How to reproduce the issue:***
``Not exactly sure what causes it. If you have an ISO of SSX Tricky, try making an input recording and play it back.``

***PC specifications:***
``(PC specs are certainly not the issue)``
``CPU: Intel Core i7 6700K GPU: Asus GTX 1080 Strix OC edition OS: Windows 10 64 Bit``

**Comment by MrCK1** [comment]
Try the EE/VU Round and Clamping modes to see if it fixes the issue

**Comment by MrCK1** [comment]
@DAXMO1 any updates?

**Comment by MrCK1** [comment]
User isn't active, closing.
