### ISSUE TITLE
Xenosaga III ntsc [GSDX OGL HW mode] has bottom half of screen shaded black in some scenes

### ISSUE THREAD

**Issue by BlackTelomeres** [PCSX2/pcsx2#3147]
***PCSX2 version:***
PCSX2 1.5.0-dev-3308 (20191023012101 - compiled on Oct 23 2019)

***PCSX2 options:***
Default emulation settings (2 - safe)

***Plugins used:***
GSDX OGL, AVX2 and the defaults

Hardware mode OGL
Native resolution and higher
automatic CRC: default
Mipmapping, accurate date and accurate blending all set as the defaults, but changing them up to full does not fix it either. Cannot find a HW hack that fixes it either

Looks correct in software mode

Interestingly, GSDX11 strips out the sepia filter entirely so the scene is in normal color but does not have the black shading error

***Description of the issue:***
Bottom half of the screen in GSDX OGL Hardware mode is shaded black in some scenes, usually scenes which have filters - frequently either grain filters or sepia filters - put over them. 

A similar issue happens in one of the opening cutscenes of the game but that one is somewhat deceptive in that if you close out of the emulation window to pause the emulation and change settings it can sometimes be made to go away by changing the HW hack settings half pixel offset to normal and then resuming (but if you keep those same HW hack settings and play from the beginning it will still be there so the change didn't seem to fix it really), whereas in the scene I am screen capturing and providing the "how to duplicate" info on, no amount of changing HW hacks I tried could remove it - including any half pixel offset change. 

Image of the issue: https://i.ibb.co/QMDMrWb/pcsx2-2019-11-01-20-54-17-856.jpg
Image of it correct in Software mode: https://i.ibb.co/VVtMnqp/pcsx2-2019-11-01-21-49-29-309.jpg

***How to reproduce the issue:***
Load the third XS3 save on the attached memory card at the bottom of this post and once you load the save, walk to the left from the save point and down the slope to a screen transition. The screen will move over to an area with bushes and a little house off in the distance with pc screens in it. Press O to answer the "email" on the pc that is prompting for it. Press Start and then triangle to skip the first dialogue with Allen which has no error to move to the next cutscene where the error happens and then watch the next scene which is in sepia color with the black shading through the bottom half.

***Last known version to work:***
Not sure it ever worked properly in hardware mode; in software mode it is correct. The wiki (https://wiki.pcsx2.net/Xenosaga_Episode_III:_Also_Sprach_Zarathustra) has some mention that "HW hacks round sprite" option fixed issues of a "line going through cutscenes" in OGL. That may be a related presentation of the issue or similar issue that a previous build of the emu had and the presentation has changed slightly in newer builds, because no Round Sprite HW hack option I tried fixed this.

***PC specifications:***
Intel i5 6600, 8GB RAM, GTX 1060 3GB, Windows 8.1pro

[Mcd001 (2).zip](https://github.com/PCSX2/pcsx2/files/3800031/Mcd001.2.zip)

**Comment by tadanokojin** [comment]
memcard isn't that useful to me as I don't own this game
please attach a gsdump: https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by BlackTelomeres** [comment]
Ok I hit shift+F8 for a single frame as the instructions there indicated that being good enough for 99% of issues. The output is an .xz and a png. Here are the files.
[xenosaga 3 half black screen bug.zip](https://github.com/PCSX2/pcsx2/files/3800130/xenosaga.3.half.black.screen.bug.zip)

**Comment by tadanokojin** [comment]
this appears to be a regression introduced by #2934 
for now the workaround is to edit your gsdx.ini to include this line:
```
disable_ts_half_bottom = 1
```

**Comment by BlackTelomeres** [comment]
Thank you so much for the quick response and workaround, much appreciated. That ini line does fix the black shading and also fixes the bottom half shading the opening cutscene as well given its the same issue: https://ibb.co/CH509tv

Just to elaborate on something that seems to potentially be related to this issue as its in the same cutscenes:

I do notice that even with "disable_ts_half_bottom = 1" put in the gsdx ini, in native resolution there will still be a barely noticeable but definitely-there off-color line through the middle of the screen in the affected scenes (which due to it being so faint isn't a problem in native). However, then when upscaling to 2-4x above native it will become a black line which is more noticeable.

Images:
Upscaling 4x on: https://ibb.co/X4v2TB2
Native res: https://ibb.co/9ZQ32jj

HW hack: Half pixel offset seems to change the color of the line across the screen in parts but no option for that setting fixes it. 

I do however see a supposed fix for in the wiki however - it says checking off the HW hack "Round Sprite" will fix it:

"Description: Straight line going across the middle of cut scene
Workaround: *OpenGL ONLY* Fix Enable HW hacks Round Sprite= Check"

However, it does not on this newer build of the emulator I'm using compared to the build the person who made that edit to the wiki was using in the past. It may be due to a change made at some point to the way the Round Sprite hack works. Not sure if it's also possible the round sprite option got broken at some point or whether this regression may be affecting the ability of round sprite to work the same way it had in the past.

**Comment by tadanokojin** [comment]
Hmm I think since the wiki was updated round sprite changed from a checkbox (one option) to a drop down (two options). On my end, it seems to work if you set it to full.

**Comment by BlackTelomeres** [comment]
With no other hacks and Round Sprite Full it does look better at 4x as the line becomes faint like it is at native res (https://ibb.co/0QtMJQ2). The black line then appears to just be a result of a conflict with 2 other hacks I have on due to the game needing them for other areas to avoid glitches or issues.

One of them being "Merge Sprite" - to allow character shadows to appear in towns/dungeons at any res (here it is without Merge Sprite or any HW hacks at all in native, note no shadow: https://ibb.co/8BfDRGP vs with merge sprite and 4x https://ibb.co/kyzbnJm) . The other being "Half Pixel Offset-Special (texture)" - to mitigate a bloom alignment issue when upscaling. It seems when either Merge Sprite or Half Pixel Offset-Special (texture) is on, Round Sprite Full won't mitigate the line.

It's probably an extremely niche and rough issue to work with then since it only looks its worst at the interaction of a bunch of hacks and I know it isn't a gamebreaker or anything so its a relatively minor issue.

Probably the bigger or more relevant issue for accuracy that I noticed as a result of this I guess is actually town/dungeon shadows not working at any res without the Merge Sprite hack in OGL. Its actually kind of weird that Merge Sprite actually fixes an issue in this game that occurs at any resolution when it's supposed to only help with upscaling by its description. If you advise it, I could open a separate issue for town/dungeon shadows not working in native res (or any res without the "Merge sprite" HW hack) and provide a GS Dump for that. If some level of HW hacks being needed is assumed for some games though, it might just be prudent to not gray out the merge sprite hack in the UI when the player is at native res since, at least in this game, it would likely fix the shadows at native res just as it does at upscaled res.

**Comment by lightningterror** [comment]
On latest dev build you will need to enable hw hacks and set Half-screen fix to Force Disabled.
