### ISSUE TITLE
Muppets Party Cruise needs "OPH Flag Hack"

### ISSUE THREAD

**Issue by GrahamLikesGames** [PCSX2/pcsx2#3148]
***PCSX2 version: 1.5.0~git201911031525***

***PCSX2 options:***
- Enabling "OPH Flag Hack" seems to resolve periodic freezes.
- Disabling "mVU Flag Hack" seems to resolve graphics problems.

Can anyone verify that these are the correct solutions?
Can these be added to Automatic Gamefixes?

***Plugins used:***
- GSdx-AVX2 1.1.0. I think settings are mostly defaults. Renderer is OpenGL (Hardware). Internal Resolution is Native (PS2). Auto CRC level is Partial (OpenGL). 

***Description of the issue:***
- Graphics glitch is shown in attached screenshot:
![Screenshot_20191103_211957](https://user-images.githubusercontent.com/46983615/68096605-cd4a2180-fe7f-11e9-9c47-f1a734213ecc.png)

***How to reproduce the issue:***
- Game most commonly freezes when returning to the main menu
- Graphics issue is visible during ship animation between title screen and main menu

***Last known version to work:***
- Both problems are reproducible on PCSX2 1.4.0 on Windows.

***PC specifications:***
- i5-4570, GTX 1060 6GB, Debian Testing

**Comment by MrCK1** [comment]
Is there anywhere specifically you were getting freezes what required OPH Flag Hack? I'm already aware of the MicroVU hack but I didn't encounter freezing in my testing. (Assuming you're also using the default EE cyclerate)

**Comment by GrahamLikesGames** [comment]
Yes, "EE Cyclerate" is set to 0.

I noticed freezes when returning to the main menu after playing games; and while playing the "Slippery When Wet" mini-game.

**Comment by atomic83GitHub** [comment]
Do you have the PAL or NTSC version of the game?

**Comment by ssakash** [comment]
>Do you have the PAL or NTSC version of the game?

 It's running at NTSC video mode, so probably NTSC.

**Comment by GrahamLikesGames** [comment]
Yes, NTSC.

I can reproduce the freezing easily. Is there anything I can do to help debug this?

**Comment by MrCK1** [comment]
I wasn't able to reproduce the freezing on my end. Did you already try running from the original disk and without speedhacks?

**Comment by atomic83GitHub** [comment]
The PAL version have a GameDB issue, EE Timing hack is apply but it hangs the game a the title screen.

**Comment by GrahamLikesGames** [comment]
I updated pcsx2-unstable today (1.5.0~git201911131759) and I'm not having any luck reproducing the issue at the moment. I'll keep trying.

I have not previously tried with speedhacks disabled. If I can make it freeze again, I'll try that.

I can't find my original disk. I made the ISO file a few years ago, then stashed the disk... somewhere. :-(
