### ISSUE TITLE
k1 dynamite 2004 japan

### ISSUE THREAD

**Issue by ihavetubes** [PCSX2/pcsx2#3151]
Game is broken and only works some what in software mode here is some gameplay showing the issues. https://www.youtube.com/watch?v=Ux349rbtLEg.

**Comment by MrCK1** [comment]
Please post the rest of your configuration settings and a GS Dump where the issue appears.

```
How To Create A GS Dump
Single Frame: Shift + F8
Multi Frame: Ctrl + Shift + F8 (hold for x seconds)

Single frame dumps should be suitable for most cases.

NOTE: Your GSdx settings are independent of the dump. Changing your settings will not effect the dump in any way.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
```

**Comment by ihavetubes** [comment]
all configurations are effect so it wont matter what I post. Just wanted to report the issue which has long been effecting this game but since this game is not popular it wont get fixed anytime soon but I just wanted people to know that it all thank you.

**Comment by tadanokojin** [comment]
Well we can't fix it unless we know what is wrong and we can't know what is wrong unless you post a dump.

**Comment by nf6429** [comment]
I was trying out the game , ill give a config and a gsdump
First config i did, games text was jumbled, title didnt load in properly, and the menu was a black screen that you can navigate.
First Config:
emulation settings= default (2)
Plugins= default, direct3d 11, reccomended settings.

Second Config:
 i put emulation settings at safest, video had mipmapping at full, crc hack at full, date accuracy at full,  medium for blending accuracy.
 menu has black screen, fight has sections of red. In the fight can have random blue screens and Black screens, pretty sure this is identical to the first config

Third config: 
changes to software mode.
memory card text displays correctly,correct title screen, Menu displays correctly, fighter select is correct. Fight Intro is correct. Issues start when fighters are on screen, being blue, and the stage and the fighters themselves flickering

took gs dump of first garbled  text, title screen,  and sections of the fight. 
https://drive.google.com/drive/folders/124HYzKu9b214lFHWctP5_cWkGx3Cc849

**Comment by lightningterror** [comment]
@nf6429 It would be nice to have access to the gs dump.

**Comment by nf6429** [comment]
Sorry about that, i thought the settings were enabled by default. They should be available now.

**Comment by someother1n** [comment]
Took a look at this and was able to get it working decent with certain settings. Only got software mode working, it needs the xgkick hack to fix colors and also some adjustments to cyclerate and cycle skip to mostly fix flickering. Only tested a couple arenas but it seems to help most of the glitches. Here is a video to get a better idea: https://www.youtube.com/watch?v=wwENr1EXgOs

**Comment by ihavetubes** [comment]
thanks going to try it out.

**Comment by ihavetubes** [comment]
just beat the game with Ernesto Hoost. Game is very playable now thanks.
