### ISSUE TITLE
Final Fantasy X Tidus Voice Glitch

### ISSUE THREAD

**Issue by emjzero2** [PCSX2/pcsx2#3152]
***PCSX2 version:***
v1.5.0-dev-3311-g3c38087e7

- **Description of the issue**:
  After beating spherimorph in macalania, in the following cutscene when the screen goes white and it cuts to tidus, his voice line is glitched and delayed.

https://youtu.be/ZQReu6-_qf8?t=1h21m40s

***PCSX2 options:***

Default no changes made

***Plugins used:***

Default plugins

***How to reproduce the issue:***

Beat spherimorph boss in macalania and watch the following cutscene

***Last known version to work:***

None known, goes far back as 0.96

**Comment by MrCK1** [comment]
Try  Adjusting DelayCycles in the SPU2 ini

**Comment by emjzero2** [comment]
Doesn't fix the problem, also it messes up the music if i turn it up too high

**Comment by MrCK1** [comment]
@emjzero2 if you're able, please retest on latest master for any changes.

**Comment by emjzero2** [comment]
Its fixed, tested on v1.7.0-dev-829-g0f7044a90

**Comment by tadanokojin** [comment]
cool thanks for letting us know
