### ISSUE TITLE
Jak & Daxter: The Precursor Legacy how to remove BLUR

### ISSUE THREAD

**Issue by leyo96** [PCSX2/pcsx2#3153]
***PCSX2 version:***
Dev version 1.50 (the latest as of yesterday)

***PCSX2 options:***
Emulation settings to Default plus MTVU hack.
Cheats enabled and I'm running a no interlacing code but it didn't fix the problem
GS:
OGL (Hardware), No interlacing, Large framebuffer, anisotropic filtering: 16x, Internal resolution 6x, enable HW hack, Texture filtering of display. Everything else is set to defualt

***Description of the issue:***
The games is terribly blurred, like motion blur, even when everything isn't moving

***How to reproduce the issue:***
Just play the game

***Screenshot of the issue***

<img width="1920" alt="Desktop Screenshot 2019 11 12 - 17 14 51 46" src="https://user-images.githubusercontent.com/57677439/68689086-2268f000-0570-11ea-86e2-4676a67266ed.png">
<img width="1920" alt="Desktop Screenshot 2019 11 12 - 17 14 43 65" src="https://user-images.githubusercontent.com/57677439/68689087-23018680-0570-11ea-93d5-b13b6820fae0.png">

***PC specifications:***
Intel I7 8700k @5.1Ghz -1 avx offset, rtx 2080, 16GB DDR4 3000MHz, Windows 10 home

**Comment by emjzero2** [comment]
Go to config>video>plugin settings, tick enable HW hacks, open advanced settings and hacks, texture offsets set Y to 200

**Comment by leyo96** [comment]
> Go to config>video>plugin settings, tick enable HW hacks, open advanced settings and hacks, texture offsets set Y to 200

Man you are the MVP, wow! Thank you so much!!

P.S. Do you have any other suggestions for this game? Sometimes I can feel some stutters, even if I'm running at a steady 60fps

**Comment by emjzero2** [comment]
Overclock the emotion engine, enabling v-sync could help too

**Comment by tadanokojin** [comment]
If we're all good here I'm going to close this as there is an acceptable workaround.

I'd like to note that this blur effect is actually apart of the game referred to as "depth cue" by the internal debug menu (and can be disabled there). It's not explicitly a bug on our end. However I do understand that this is not a desired effect while upscaling. Maybe in the future we can give our users the tools to remove it if they so desire.

**Comment by kytty00** [comment]
@emjzero2  thank you very much, so many people are waiting for a solution to this.

**Comment by rigopoui** [comment]
In the new Qt version, enabling "Manual Hardware Renderer Fixes" introduces many visual glitches, even without setting the Y offset to 200. So I don't consider this a valid workaround anymore. Maybe we need to be able to keep the automatic game fixes, and apply the rest on top of those? Instead of overriding.
