### ISSUE TITLE
DT Racer: Massive EE Throttling and slow performance

### ISSUE THREAD

**Issue by NewMoonHD** [PCSX2/pcsx2#3154]
PCSX2 version:
1.5.0-dev-3309-g5b6b38670

Description of the issue: DT Racer (SLUS-21095, NTSC-U) suffers a lot of graphical glitches and EE throttling. Any renderer (including HW and SW of both DX11 and OGL) will run at least 14-16 FPS while EE usage is topping out 98-100% of its usage after creating the players profile and asking the player if they want to save the profile. Afterwards, the game will then start to have EE throttling effects.

Here is the screenshots for the game.

D3D11 Hardware: 
![gsdx_20191113092501](https://user-images.githubusercontent.com/52108325/68788401-28a2af00-05f8-11ea-9cb9-790ba2362591.png)
D3D11 Software:
![gsdx_20191113092436](https://user-images.githubusercontent.com/52108325/68788393-24769180-05f8-11ea-8b3f-852e1aa25f98.png)
(Same effects happen on OGL as well)

Last known version to work: Unknown

PC Specs: R7 2700, RX 580 8GB (AMD 19.11.1 Driver installed), 16GB DDR4 @3200mhz, Windows 10 x64

Edit: Here are the files for D3D11 (HW and SW mode)
[DT Racer Snap Files.zip](https://github.com/PCSX2/pcsx2/files/3842936/DT.Racer.Snap.Files.zip)

**Comment by kozarovv** [comment]
EE throttling seems to be IPU/DMA issue, i found it accidentally while messed with "Stolen" game. Hardcoding DMAC_TO_IPU events to happen 128 cycles in future fix speed issues completely. Sadly other issues are still there. 
Here is build with mentioned hack: https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=614010#pid614010

**Comment by refractionpcsx2** [comment]
Throttling has been resolved on master.  Game does crash randomly due to another bug, but that's outside the scope of this issue, we do know about it as I'll probably look in to it at some point.
