### ISSUE TITLE
[GSdx HW] Xenosaga III ntsc Error graphics on surfaces in the last dungeon

### ISSUE THREAD

**Issue by BlackTelomeres** [PCSX2/pcsx2#3155]
***PCSX2 version:***
PCSX2 1.5.0-dev-3302 - 20191023012101 - compiled on Oct 23 2019

***PCSX2 options:***
Default emulation settings (2 - safe)

***Plugins used:***
GSDX OGL, AVX2 and the defaults

Hardware mode OGL
Native res and up
Mipmapping, automatic CRC, accurate date and accurate blending all set as the defaults, but changing them up to full does not fix it either. Cannot find a HW hack that fixes it either.

Game generally needs the hacks disable safe features, merge sprite, preload frame data, and half pixel offset: special (texture) to look its best through most of the game in OGL hardware mode, but those do not fix this, nor does turning them off.

Virtually the same error exists in DX11 HW mode.

***Description of the issue:***
Error garbage graphics present in some surfaces in the last dungeon, most or all of the surfaces being somewhat transparent and "crystalline."
Different but yet similar looking (enough for them to probably all be the same root cause) forms of it are present throughout the last dungeon in the game.
https://ibb.co/LJ2nLC4 - example of the error
https://ibb.co/bvc93WP - what the same place looks like in software mode (correct)

***How to reproduce the issue:***
A GSDump is attached to this post.

A memory card save is also attached if needed.
Load the 36th save in the memory card, go to the right, then south/
backwards (towards the camera) and through the door and keep walking towards the camera and you'll run into one of the walls of it. You can run from any enemy battles encountered with the escape command. There are also more examples further on in the dungeon which can be reached by going backwards through the dungeon from the 37th save.

***Last known version to work:***
Most likely has never worked correctly in dx11 or ogl hardware mode given what I am seeing on the compatibility wiki, works in software mode

***PC specifications:***
Intel i5 6600, 8GB RAM, GTX 1060 3GB, Windows 8.1pro

[xenosaga 3 last dungeon graphics bug gsdump.zip](https://github.com/PCSX2/pcsx2/files/3844061/xenosaga.3.last.dungeon.graphics.bug.gsdump.zip)
[xenosaga 3 mcd001 for last dungeon graphics bug.zip](https://github.com/PCSX2/pcsx2/files/3844063/xenosaga.3.mcd001.for.last.dungeon.graphics.bug.zip)

**Comment by MetrosexualGarbodor** [comment]
Some updated dumps for this issue in case they're needed.

![gs_20220714160115_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179014232-9684b244-4b11-448c-b964-b91a42f7dd48.png)
[gs_20220714160115_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112928/gs_20220714160115_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714160136_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179014396-720bc89e-da48-4865-abec-20c93de3fa01.png)
[gs_20220714160136_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112935/gs_20220714160136_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714160156_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179014432-fd4a9a0e-10cb-478d-96e2-c1c4d5050bd5.png)
[gs_20220714160156_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112936/gs_20220714160156_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714160041_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179014503-3139f710-3477-46b9-9c4e-d4b7c4f94774.png)
[gs_20220714160041_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112939/gs_20220714160041_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714160029_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179014559-275ae9ad-53de-4496-b6f3-2d6b7062533a.png)
[gs_20220714160029_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112943/gs_20220714160029_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714151444_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179006710-c2452f7b-fd9e-4dc4-bad0-e410c90193b2.png)
[gs_20220714151444_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112674/gs_20220714151444_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)


![gs_20220714151506_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179006802-7e1c9038-4628-42b2-82c5-622adf58bed0.png)
[gs_20220714151506_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9112678/gs_20220714151506_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)

**Comment by refractionpcsx2** [comment]
This will be fixed by #8289 if you re-enable Texture in RT, however I don't know about what problems it causes (the menu seems fine, one of the things which was stated as broken).

If it does and there's no errors, then we can re-enable the fix.

![image](https://user-images.githubusercontent.com/6278726/225513267-091bfd4b-7031-42f5-bb25-11f422320f7a.png)
