### ISSUE TITLE
Problem configuring joystick or gamepad

### ISSUE THREAD

**Issue by dariocdj** [PCSX2/pcsx2#3156]
1.5.0-0 git
Controller configuration
 
onepad 1.3.0 legacy 
recognize my controllers, joystick or joypad connected with usb, i can assign buttons correctly (red blink when i press  button) but when i start game nothing works

onepad 2.0.0 
gamepad configuration found correctly all the device connected (joystick, gamepad...) but when i try to assign buttons no one is recognized.

Using debian 10 buster and last pcsx2 1.5.0-0 take from git

In debian 9 it works with pcsx 1.4.0

i5 with 4gb and nvidia

thanks
Dario

**Comment by kenshen112** [comment]
Yup, that's exactly what onepad 2 is supposed to do.

**Comment by dariocdj** [comment]
And what can I do to use my controllers??

**Comment by kenshen112** [comment]
use onepad2 it has an auto detect feature that prevents you from configuring buttons on your own. so just set it then start pcsx2

**Comment by dariocdj** [comment]
Tried but seems that onepad recognize only keyboard.... no joystick and no gamepad working.

**Comment by dariocdj** [comment]
OK Fixed deleting old pcsx2 preferences fo,lder. It works
But now i've seen that Emulator goes reallyt slow comparing at 1.4 under debian 9. Dragon Ball or Sonic Unleashed are unplayable with my i5 4gb ram intel hd. Why?

**Comment by kenshen112** [comment]
Because your HW isn't really capable of emulating the PS2 especially that graphics card

**Comment by lightningterror** [comment]
In the OP he states he has an nvidia gpu, might be issue #2967

**Comment by kenshen112** [comment]
Doubtful, but I wonder which i5 he has in his system

**Comment by kenshen112** [comment]
Because 1.5 is a fair bit more accurate then 1.4, so stuff's getting emulated that didn't before. This increases the system requirements by a fair bit

**Comment by tadanokojin** [comment]
It's not a bad CPU you might be able to get away with native or 2x res and make sure you enable MTVU.

**Comment by dariocdj** [comment]
YES it's not a bad cpu. Performance drop from 100% when run menu and select options to 20/10/5% as some setting KILL cpu... what can i do ? Also uninstall xorg-intel and use firmware non free. Tried to switch from SSE4 to SSE2 Gsdx plugin unsuccessfully. And tried to change  lots of parameters to make emulator running fast.....Hope that someone help me. Thanks in advance

**Comment by tadanokojin** [comment]
For more general help I suggest you create an account here https://forums.pcsx2.net/ or you can try our discord https://discord.gg/6UwJ3Vt

As for this issue I'm closing it.

**Comment by dariocdj** [comment]
Solved recompiling pcsx2 from github
