### ISSUE TITLE
Damon ps2 still

### ISSUE THREAD

**Issue by farouk327** [PCSX2/pcsx2#3164]
Greeting pcsx2 noble developers
I want to know what the hell are doing
The fake damon  ps2 emulator still in the play store
Why don't you make an android port to take them down
You can collaborate with play! Developer 
From now they can't improve the damned damon ps2  and we don't have a proper emulator in the aos
And all people are waiting for your action

**Comment by RedPanda4552** [comment]
Android is not a priority for the team right now, for a variety of reasons, including but not limited to:

- Low experience with Android app development
- Lack of interest in the Android platform
- Lack of interest from the user base

You say that lots of people are waiting for action, however any vocalization about Android has been a very, VERY loud minority, where the majority of users are either silent or content on desktop/laptop PCs.

I wrote a short explanation a while back on Reddit explaining at a high level some of the work that the build would require: https://www.reddit.com/r/emulation/comments/9p1jzf/as_a_followup_to_yesterday_how_can_we_as_a/e802ktm

Closing this issue as invalid, as it is not a proper report of a PCSX2 issue or feature request.
