### ISSUE TITLE
[Regression] Final Fantasy X Glitchy Monitors in Luca

### ISSUE THREAD

**Issue by yrhjtyjtyjydt** [PCSX2/pcsx2#3165]
***PCSX2 version:***
v1.5.0-dev-3319-g2827394f3

- **Description of the issue**:
The videos being displayed in the monitors in Luca are glitched.

### Version 0.9.7 r3878:

![gsdx_20191201235046](https://user-images.githubusercontent.com/57640063/69922645-03d28680-1496-11ea-88ba-60a7741e5a83.png)

![gsdx_20191201235234](https://user-images.githubusercontent.com/57640063/69922649-09c86780-1496-11ea-9361-4ea0bd86d1cb.png)

### Version 0.98 onward:
![gsdx_20191129052209](https://user-images.githubusercontent.com/57640063/69845521-df459700-1268-11ea-9eb0-861001e8b20f.png)

![gsdx_20191129052246](https://user-images.githubusercontent.com/57640063/69845547-f4bac100-1268-11ea-8b03-b76cca81f12f.png)

***PCSX2 options:***

Default no changes made

***Plugins used:***

Default plugins

***Last known version to work:***

Version 0.9.7 r3878

**Comment by Lolibox** [comment]
seems to be fine now. tested both hardware modes and software mode.
![image](https://user-images.githubusercontent.com/49990481/111856714-ffd4ad00-8902-11eb-96c6-d0137ab14c43.png)
1.7.0 dev 1083
