### ISSUE TITLE
Armored Core: Last Raven (NTSC-U - SLUS_213.38) - Blurry graphics during missions (in HW mode).

### ISSUE THREAD

**Issue by Metamoran** [PCSX2/pcsx2#3169]
***PCSX2 version:***
1.7.0 dev 1040 (also tried 1.6.0 and 1.4.0. No difference)

***PCSX2 options:***
Defaults, 'Safe' preset. I've also tried different settings to no effect. Speedhacks were disabled during testing.

***Plugins used:***
GSdx, SPU2-X, LilyPad, cdvdGigaherz, the rest are null plugins.

***Plugin settings:*** 
Tested GSdx in both OpenGL and Direct3D 11 modes, HW and SW. Tried all sort of settings combinations to no effect. "Preload Frame Data" hack enabled to avoid HW mode blackscreen.

GS dump: [gsdx_20191205031754.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/3925432/gsdx_20191205031754.gs.xz.zip)

***Description of the issue:***
The game simply looks wrong during missions in HW mode. The entire screen is a blurry mess. Graphics are perfectly fine while in menus (no blur + proper upscaling). This issue doesn't show up in the previous game in the series (Armored Core: Nexus). Image comparison included, screenshots taken in OpenGL HW mode.

![gsdx_20191204205752](https://user-images.githubusercontent.com/8518358/70209796-ec063700-170f-11ea-83c4-0e0f73d4cc4d.jpg) ![gsdx_20191204204827](https://user-images.githubusercontent.com/8518358/70209812-f58f9f00-170f-11ea-801b-3fd42d721866.jpg)
HW mode upscaling working properly in menus, no blur present:
![gsdx_20210317131417](https://user-images.githubusercontent.com/8518358/111500668-00aee880-8723-11eb-81f1-50ac68b5196c.png)

***How to reproduce the issue:***
Enter any mission, battle or AC Test mode.

***Last known version to work:***
Never worked right, as far as I'm aware.

***PC specifications:***
CPU: AMD Ryzen 5 2600
GPU: Geforce GTX 1060 6GB
OS: Windows 7 Ultimate SP1 x64

**Comment by tadanokojin** [comment]
> This has been reported and discussed on the forums before. Some people believe this is solely caused by the emulator not playing nice with the motion blur effect.

No I don't think so.

Are you by chance referring to [this thread](https://forums.pcsx2.net/Thread-Armored-Core-Last-Raven-Upscaling-not-working-on-Mission-Mode)? If so I believe FO incorrect and was just guessing.

Game renders to `0x700` then performs a move to `0x0` which is the read area for CRTC. The issue with this is how GSdx works internally and how preload frame works.

The move reads the data from video memory and then the preload frame hack reads it out of gs memory. GS memory shouldn't be scaled thus you get native res. It has nothing to do with motion blur.

Here's the frame before the move. Notice the motion blur is there and also that the resolution looks much better. The image is squashed into half height because of interlacing.
![_01600_f5002_rt1_00700_C_32](https://user-images.githubusercontent.com/26046960/70365448-70b39b00-185f-11ea-97ad-ea5c64cf32b5.png)

**Comment by Metamoran** [comment]
I see, thank you for taking the time to explain this to me (I clearly have no technical knowledge when it comes to software). And yes, I was indeed referring to that thread.

So basically, is this a case of "it's unfixable, but the game is otherwise fully playable"? It's not like I'm complaining or feel entitled to a fix, I'm just wondering. It's not like this issue will stop me from enjoying the game like I've been doing for years.

Cheers, and many thanks to you and all those who have contributed to this project.

**Comment by tadanokojin** [comment]
It might be fixable, don't know at this juncture.
First step is knowing what is wrong ;)

I'll add it to my list for after release.

**Comment by Metamoran** [comment]
I feel like I should bring this to your attention: Forum user PsxFan107 (all credit goes to him) has released a .pnach which deals with both the blackscreen and upscaling problems. While I haven't tested it extensively, I haven't run into any issues so far. Here's a screenshot of the results at 3x upscaling:

![gsdx_20200901232942](https://user-images.githubusercontent.com/8518358/91925993-9e255c00-ecac-11ea-9e4c-46ff8c8e044b.jpg)

And here's both the .pnach and a link to the relevant forum post.

[1F34E107.zip](https://github.com/PCSX2/pcsx2/files/5159815/1F34E107.zip)

[Forum Post](https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=609962#pid609962)

**Comment by tadanokojin** [comment]
I wrote a small patch that will resolve the issue in the HW renderer based on refs work with k1 Unfortunately it breaks some other stuff in the process but if someone wants to use it/improve on it in the meantime while we sort out the cache:

```
// fix game not rendering in HW mode
// force display buffer read from backbuffer
patch=1,EE,002b7ce0,word,00000038
patch=1,EE,002b7da0,word,00000038
```
