### ISSUE TITLE
Comparing to Last Stable there is a huge performance regression on latest Dev Builds

### ISSUE THREAD

**Issue by edneyhelene** [PCSX2/pcsx2#3170]
Hello how are you? 
I was using the stable version of PCSX2 for windows, getting like 95~100% speed on almost all games.

I decided to give a try on developer versions that are newer, tried the 3 latest, them all with the same issue.

The speed hacks seems to have no effect at all, i'm getting now 30% of the speed only.

I would like to point this out so we can make sure that on the next stable version it wont happen.

It' s working great with the stable 1.4 version anyways, i tried almost everything on the latest builds but i could not make it even closer to the results i had before .

I have no idea on why there's such a huge difference using the same hardware and system on both.

SYSTEM:
WINDOWS 10 X64 LATEST
Radeon HD5450 1gb ddr3
Xeon E5440
4Gb ram

thank you so much

**Comment by lightningterror** [comment]
Which games are running slower?

**Comment by edneyhelene** [comment]
God of war 2
God Of War 1
Saint Seiya Hades
Need For SPeed Carbon
All Crash Games

Mostly all games i tested are slower on the last dev builds comparing to the 1.4 version.
The higher are the requirements for a game, the slower they are on the dev builds.

**Comment by lightningterror** [comment]
> Mostly all games i tested are slower on the last dev builds comparing to the 1.4 version.
> The higher are the requirements for a game, the slower they are on the dev builds.
> 
> I feel like the speedhacks are not working, but i dont know if thats the reason.
> 
> on 1.4 they run great using d3d11 and some soft speed hack.

It's slower because of the increased accuracy in emulation, especially for d3d11 since it got plenty of accuracy improvements since 1.4 release.
It's probably time for an upgrade, both your cpu and gpu are below the minimum requirements.

**Comment by edneyhelene** [comment]
Hum i see, well i will save the 1.4 version here so i can have it forever till i upgrade.

Maybe you could add an option that makes emulation " less accurate" for lower end machines on the newest builds? #Featurerequest 

Thank you so much for your work i do really like it.

**Comment by lightningterror** [comment]
There are options. Set accurate blending and accurate date to off/none, disable depth emulation.

**Comment by edneyhelene** [comment]
> There are options. Set accurate blending and accurate date to off/none, disable depth emulation.

Looks great, disable blending and accurate date, where do i disable depth emulation?

**Comment by edneyhelene** [comment]
> There are options. Set accurate blending and accurate date to off/none, disable depth emulation.

No worries i found it, yeah it works a lot better,  thank you so much.
soon i will upgrade and then play these games in 1080P with fULL filters hehe

thank you for your work sir
