### ISSUE TITLE
[Request] Alternative Scaling Filters

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#3174]
I know Pcsx2 use bilinear filtering for downscaling and upscaling when it is checked(Texture Filtering of Display).

As bilinear filtering 

add gaussian filtering for up and down scaling.

I heard gaussinan filtering is not so heavy.

So it is used with nvidia's dsr.

 
AndAnd

like a DSR's smoothness, to adjust blur 

add function of blur value(bilinear or gaussian) changing.

**Comment by MrCK1** [comment]
Could you just achieve the same result with downsampling? I don't know anyone that wants to blur the display intentionally....

**Comment by willkuer** [comment]
I think op asks for a way to add SSAA... just for poor gpu‘s. It sounds to me like they assume that the down sampling is the computational expensive part and if one would implement gaussian filtering it would be cheaper gpu-wise as it is natively supported by gpus.

Something like that but I am not sure.

**Comment by tadanokojin** [comment]
We have SSAA. He wants option for gaussian (opposed to bilinear or point we use now) for the down sample.

Issue is there is no native support for gaussian that I am aware of. DSR is NV custom gaussian. But if someone can show me some implementation I'll look at it.

**Comment by mondaychicken** [comment]
Thanks for replying.

@MrCK1  
Strong blur is really problem. But ultra sharp always is not good.
Sometimes we need smoothness visual.

@willkuer 
I don't intend to want adding Another SSAA.
But if it can be implemented  So Good.

@tadanokojin 
Yes, you are right exactly.
If you are interested in gaussian implementation
look at this.
[GaussianShader.zip](https://github.com/PCSX2/pcsx2/files/3991216/GaussianShader.zip)
This is a gaussian shader for ppsspp DSR.
Reference
https://github.com/hrydgard/ppsspp/issues/7242

**Comment by Silanda** [comment]
Since additional features are being discussed, an option I'd like to see is along the lines of the sharp bilinear filter included with Retroarch. I believe that does an integer upscale to something like 5x the original resolution, and then scales that image with a bilinear filter to the output resolution. The result is a sharp image that avoids nearest neighbour scaling artefacts.

**Comment by KrossX** [comment]
I think for that it would be enough to upscale beyond the window size (fullscreen or not) so it downscales with linear filter. I wonder if there would be much of a difference to scale to the nearest below the windows size or beyond the window size. Would also have to keep in mind texture size vs aspect ratio as games could use very weird resolutions for an image that would end up on a blurry 4:3 screen. I guess that means different scale values per axis, also gotta check if ws hacks are enabled... =_="

**Comment by MrCK1** [comment]
When you factor in things like interlacing and other GS effects that don't scale with resolution, I think you will not see the "sharpness" you are envisioning in your head personally. Many PS2 games simply don't play nice with upscaling regardless.

**Comment by lightningterror** [comment]
Closing as trivial, prs are welcome.
