### ISSUE TITLE
Star Wars: The Force Unleashed (SLES 54658) Missing or glitched HUD graphics

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#3175]
***PCSX2 version:***
Current Git build as of this date.

***PCSX2 options:***
No options appear to have any impact on this bug

***Plugins used:***
Bug manifests using GSdx in hardware and software modes. 

***Description of the issue:***
Any status bars in the HUD do not function correctly. More specifically, they are rendered, but only visible in certain circumstances. Based on visual inspection only, the bars seem to be made up of two elements: a grid which overlays the bar to give an indication of how much health etc you have compared to the maximum, and the coloured bars themselves which change length as you lose, for example, health. The grid part displays properly, but the coloured bar does not most of the time. I say "most of the time" because it looks like it is being rendered, but geometry (backgrounds, characters, etc) is being drawn behind the grid overlay but in front of the coloured bar, rendering it invisible most of the time. 

Attached is a screenshot and GSDump showing a partially occluded bar from the opening level. Any geometry except for the far skybox occludes the bars.

![gsdx_20191219150946](https://user-images.githubusercontent.com/4227434/71184614-ef520480-2271-11ea-99ab-72ffa62dc5c7.png)

[gsdx_20191219150946.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/3984227/gsdx_20191219150946.gs.xz.zip)

**Comment by lightningterror** [comment]
I pushed a new commit, recent dev build will work better on hw renderer atm, nothing we can do for sw renderer for now .

**Comment by Silanda** [comment]
Thanks! It seems to look fine using the hardware renderer once the CRC hack level is set to automatic. I'll be honest, I forgot to test with hacks turned on before.

**Comment by kozarovv** [comment]
Here is patch that work for both hw, and sw modes: https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=594813#pid594813

**Comment by Silanda** [comment]
Awesome! Thanks.

**Comment by atomic83GitHub** [comment]
@kozarovv Can you explain a bit what you patched? This would help for any potential fixes.

**Comment by kozarovv** [comment]
> @kozarovv Can you explain a bit what you patched? This would help for any potential fixes.

To be honest i can't explain that. Patch for Spyro that was base for that one, was borrowed from patch used in ps2_gxemu/lopnor on ps3. They patch little bit more, and little bit different, but pcsx2 seems to not need all that (also patch for Spyro used in db was modified by pcsx2 team member). My work here was to figure out that SW: TFU it's the same game engine, find correct function, port patch. Originally issue appeared on PS3/PS4, so i tried it also on pcsx2, and result was ok so i posted it on forum. 

Anyway this seems to be Krome Studio specific thing. Only game that seems to have somehow similar issue is https://wiki.pcsx2.net/Galerians:_Ash , i tried to fix it for PS3 following similar patterns, but without luck.

**Comment by lightningterror** [comment]
It will be nice to port the patches to other regions, then we can remove the crc hack and replace it with gamedb patches.
