### ISSUE TITLE
Evil Dead: Fist Full of Boomstick - Broken Shadows

### ISSUE THREAD

**Issue by tadanokojin** [PCSX2/pcsx2#3176]
***PCSX2 version:***
git

***PCSX2 options:***
default with opengl hw (dx broken as well)

***Description of the issue:***
![evildead](https://user-images.githubusercontent.com/26046960/71239360-615b3580-22d4-11ea-9ae5-3b7e79d9b1a5.png)

***How to reproduce the issue:***
Get in-game using one of the hardware renderers

***Last known version to work:***
Likely never worked

***PC specifications:***
i5 7600
GTX 1070

***Debugging Results***
Game wants to clear a color buffer to a specific color.
Using the following pattern:
- set frame buffer width to 1
- draw 64x2048 quad to clear

Relevant draw in included dump is 165.
https://dumps.pcsx2.net/index.php/s/6gmFTEzojKDixfr

Related issue #3171 (same developer likely same engine)

**Comment by tadanokojin** [comment]
Closing in favor of #3180

**Comment by Peshawa-Gaming** [comment]
Hello dear I have the same problem with tom and jerry wars of the whiskers game and I don't now how to fix it, so can you please help me fixing it as I am not an programing expert.
pcsx2 version 1.6 stable, open GL harware
