### ISSUE TITLE
Jak 2 Texture popping/Broken

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#3177]
PCSX2 1.5.0-20191219195340 - compiled on Dec 19 2019

I noticed that in Jak 2 with default speed (2) settings  and using opengl some textures are broken 

![bt](https://user-images.githubusercontent.com/5770076/71277975-bc8e3600-236f-11ea-8c29-27b810c61d61.gif)

GS dump
[broken textures.zip](https://github.com/PCSX2/pcsx2/files/3989473/broken.textures.zip)

If i set Mipmapping to full i get blurry half loaded textures (however fixes broken textures)

![blurry](https://user-images.githubusercontent.com/5770076/71278445-16433000-2371-11ea-92ad-9974b61cc1f1.gif)

 GS dump

[Blurry.zip](https://github.com/PCSX2/pcsx2/files/3989494/Blurry.zip)

More noticeable here 

![blurry](https://user-images.githubusercontent.com/5770076/71278613-83ef5c00-2371-11ea-8182-a5205140ff03.jpg)

Without Mipmapping (Default)

![default](https://user-images.githubusercontent.com/5770076/71278660-a2555780-2371-11ea-8199-889a852b95ef.jpg)

[emuLog.zip](https://github.com/PCSX2/pcsx2/files/3989504/emuLog.zip)

**Comment by MrCK1** [comment]
I don't see the issue you are referring to in the GIFs but the last 2 images are inherently how mipmapping is supposed to work. 

The further you are away from an object will result in a smaller size (blurrier) texture/LOD. The transitions between these layers in PCSX2 are not perfect, and will sometimes pop in. The Jak series also needs trilinear for some additional textures which is not fully implemented.

**Comment by Levan7** [comment]
@MrCK1 
Well it looks very inaccurate 

![pcsx2_2019_12_20_22_56_22_850 mkv_snapshot_00 26 355](https://user-images.githubusercontent.com/5770076/71284611-8dca8c80-237c-11ea-8415-233bce518467.jpg)
 
That wood has no textures but if you look at this video 
https://youtu.be/ZmkAaQbBnkc?t=46

That wood should have more detailed textures 

[videomaping.zip](https://github.com/PCSX2/pcsx2/files/3989820/videomaping.zip)

**Comment by MrCK1** [comment]
Yes, if you disable mipmapping it will probably be more detailed

**Comment by Levan7** [comment]
@MrCK1 That video is using PS3 with backward compatibility if you want i can start my ps2 but it will take some time and the footage will be recorded with a phone but i'm sure the textures will be more detailed

**Comment by Levan7** [comment]
@MrCK1 
My bad the PS2 looks like that (or my ps2 want senile from age)

![MOV_20191220_2336208 mp4_snapshot_00 28 370](https://user-images.githubusercontent.com/5770076/71287880-ea30aa80-2382-11ea-9978-20ffdae224e2.jpg)

PS2 hardware video phone quality sorry 
[PS2 hardware video.zip](https://github.com/PCSX2/pcsx2/files/3989974/PS2.hardware.video.zip)

**Comment by tadanokojin** [comment]
Yes the mips are not accurate. However, there is an open meta issue for this #1561. As such I'll close this in favor of that issue.
