### ISSUE TITLE
[GSdx HW] Overvolume shadows in Dead or Alive 2: Hardcore (NTSC-J)

### ISSUE THREAD

**Issue by Qwest8K** [PCSX2/pcsx2#3178]
***PCSX2 version:*** 
v1.5.0-dev-3332

***PCSX2 options:***
Presets disabled.
EE/VU Clamp modes: Normal/Normal.
EE/VU Rounding: Chop/Chop.
All Speedhacks and GameFixes are disabled.
Automatic fixes enabled (since game require this for start).

***Plugins used:***
GS - Default settings of OpenGL hard- and software. Resolution in hardware - 4x.
PAD - Unchecked "Game Devices APIs" boxes, except "Monitor when in background". Unplugged second controller. Assigned on keyboard first controller (DualShock 2).
Settings of other plugins are default.

***Description of the issue:***
In hadware mode, dynamic shadow of characters looks like half-transparent black 3D model, when should be 2D picture. In software shadows are normal.

***How to reproduce the issue:***
In hardware mode start any type of fight and (for a more visual effect) make the characters move.

***Last known version to work:*** 
Unknown.

***PC specifications:*** 
CPU: Intel Core i7-4790K @ 4.00 GHz 
GPU: Zotac GeForce GTX 980 4GB
OS: Windows 7 SP1 64 Bit

***Attachments:***
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/3990108/emuLog.txt)
[gsdx_20191220231440.gs.zip](https://github.com/PCSX2/pcsx2/files/3990109/gsdx_20191220231440.gs.zip)
![Correct shadows in software](https://user-images.githubusercontent.com/38340995/71289827-2e21b080-237f-11ea-9c5c-c5d4efb8e4ae.png)
![Incorrect shadows in hardware](https://user-images.githubusercontent.com/38340995/71289828-2eba4700-237f-11ea-8396-4120fd3e7ed4.png)

**Comment by lightningterror** [comment]
Looks like it is an issue with Fast DATE accuracy, you can set it on Full to avoid the issue.

**Comment by Qwest8K** [comment]
Full DATE accuracy helped - shadows became flat. But there is still a problem - at any resolution higher than native (in any rendering mode), gaps appear in the shadows.
![Shadow's gaps (OpenGL, Hardware 4x, Full DATE Accuracy](https://user-images.githubusercontent.com/38340995/71292725-2238ed00-2385-11ea-926e-14bb98a43870.png)

But, shadows became flat only in both OpenGL modes. In hardware Direct3D 11 in any resolution overvolume still exists and even flickering - parts of incorrect 3D shadows appear and disappear.
![Buggy shadows (Direct 3D 11, Hardware 4x, Full DATE Accuracy](https://user-images.githubusercontent.com/38340995/71292718-2238ed00-2385-11ea-8e27-85cf2cc7e594.png)

**Comment by lightningterror** [comment]
D3D11 doesn't have Full accurate date implemented.

**Comment by Qwest8K** [comment]
Okay, and that about gaps?

**Comment by lightningterror** [comment]
The gaps are there on native, same goes for software mode as well, how does it look on ps2?

**Comment by Qwest8K** [comment]
On real PS2, in software OGL and D3D11 dynamic shadows looks like they should - translucent-black filled silhouette of character (though not completely accurate, because game is old). With full DATE accuracy same demonstrate hardware OGL, but only in native resolution. If increase the resolution even twice, shadows will receive gaps between the joints (knees, elbows, neck, etc.). As if they belong articulated puppet.
![Shadows comparsion](https://user-images.githubusercontent.com/38340995/71296287-169ef380-2390-11ea-8dfa-1c32d1a839b7.png)

**Comment by MrCK1** [comment]
Upscaling is a hack, so it is normal to see issues like this. Often the model used for shadows is a lower-poly representation of the in-game character.

**Comment by Silanda** [comment]
While they're far more obvious in hardware mode at higher resolutions, I've noticed that from certain angles the gaps in the shadows appear in software mode too. In the PAL version, which I tested, it was apparent in the second attract mode sequence with characters doing kata. I'll try to get my PS2 hooked up tomorrow and see if the same is true there.

**Comment by Silanda** [comment]
I've had a test on my PS2, and I'm 99% certain that from certain angles there are gaps appearing in the shadows in PCSX2 that do not appear on actual hardware. That's true even in software mode. I half wonder if they're occurring along overlapping edges of the component parts of the shadows. High resolution output exacerbates the problem but it seems to occur at native res too.

Now, I'll reiterate that I tested on the PAL version, because my results with software mode seem different to Qwest8K's: the gaps are obvious in software mode for me, while they're not present in his screenshots.

**Comment by lightningterror** [comment]
This is fully resolved now on all renderers.
