### ISSUE TITLE
EE cant load WS Patches right when booting games in recent builds

### ISSUE THREAD

**Issue by FuxorLuck** [PCSX2/pcsx2#3182]
***PCSX2 version:***
Pcsx2 1.5.0- dev -3332

***PCSX2 options:***
No hacks , software rendering

***Plugins used:***
Gsdx32 AVX-2

***Description of the issue:***
If you boot (Full/Fast) a game with "Enable widescreen patches" the game will crash or suffer from heavy graphical glitch

***How to reproduce the issue:***
I found it in 3 games but there are might be more

Shadow Hearts: Covenant (Disc 1) - boot (Full/Fast) a game with "Enable widescreen patches", Start a new game
Skip all the cutscene, press confirm to go to Apoina Tower, the game crashes,

Shadow Hearts: From the new world  -  Boot (Full/Fast) a game with "Enable widescreen patches", Start a new game, Skip all the cutscene, the game suffer from heavy visual glitch 

https://ibb.co/jzpkzpV

Dual Hearts -  Boot (Full/Fast) a game with "Enable widescreen patches", Go in first time to Toma's dream, beat the Statue Knight, watch the cutscene, the game crashes
( i will upload a save state)

Note: shadow hearts and dual hearts arent from the same series/developers

***How to fix:***

Option 1: before booting the game go to Config --> Emulation settings ---> EE/IOP ---> Emotion Engine set it to interpreter ---> boot the game ----> when you get to the first screen change it to Recompiler again.
Note: this is the reason i believe the problem is with the EE

Option 2: Boot the game without "Enable widescreen patches" than after reaching the first screen activate "Enable widescreen patches"

Option 3: Run OPL elf file ---> Exit ---> Press on the DVD  

***Last known version to work:***
Pcsx2 1.4.0

***PC specifications:***

`(CPU: Intel i7 8700 GPU: Gigabyte GTX 1060 6GB OS: Windows 10 64 Bit)``

**Comment by MrCK1** [comment]
Not a valid issue. It is a problem with Shadow Hearts as the "fix" you have listed there was just an arbitrary solution that was ripped from the forums: https://forums.pcsx2.net/Thread-shadow-hearts-covenant-crashes-pcsx2

**Comment by FuxorLuck** [comment]
I noice the same issue appears in Dual Hearts and Red_Tv allowed me to open this issue in github

**Comment by FuxorLuck** [comment]
In dds2 the player cant intreact with any object
