### ISSUE TITLE
Xiaoji Gamesir-G3w don't work with pcsx2

### ISSUE THREAD

**Issue by JohnDoe44526949** [PCSX2/pcsx2#3188]
***PCSX2 version: 1.5.0-0 (git)

PCSX2 1.5.0-0 
Savestate version: 0x9a0d0000

Host Machine Init:
	Operating System =  Linux 4.19.0-6-amd64 x86_64
	Physical RAM     =  31611 MB
	CPU name         =  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  3.996 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins from /usr/lib/i386-linux-gnu/pcsx2...
	Bound   GS: libGSdx.so [GSdx (GCC 8.2.0 SSE2/AVX) 1.1.0]
	Bound  PAD: libonepad.so [OnePAD 0 2.0.0]
	Bound SPU2: libspu2x-2.0.0.so [SPU2-X 2.0.0]
	Bound CDVD: libCDVDnull.so [CDVDnull Driver 0 0.6.0]
	Bound  USB: libUSBnull-0.7.0.so [USBnull Driver 0 0.7.0]
	Bound   FW: libFWnull-0.7.0.so [FWnull Driver 0 0.7.0]
(GameDB) 9768 games on record (loaded in 146ms)
	Bound DEV9: libdev9null-0.5.0.so [DEV9null Driver 0 0.5.0]
Plugins loaded successfully.

onepad: Joystick (Xiaoji Gamesir-G3w,GUID:03000000ac0500005b05000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (Xiaoji Gamesir-G3w,GUID:03000000ac0500005b05000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

***PCSX2 options: all in default

***PC specifications: CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (3.23GHz) • Memory: Physical: 30.1 GiB Total running on Debian 10.2

**Comment by lightningterror** [comment]
Looks like your controller isn't on the db list, can you use http://www.generalarcade.com/gamepadtool/ to generate a new mapping and paste it here.

**Comment by lightningterror** [comment]
@JohnDoe44526949 any update?

**Comment by JohnDoe44526949** [comment]
Sorry for de delay. The mapping string:

03000000ac0500005b05000000000000,Gamesir-G3w,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,guide:b12,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,

**Comment by JohnDoe44526949** [comment]
Gamepad GUID:

03000000ac0500005b05000000000000

**Comment by lightningterror** [comment]
The mapping is for windows, i need th linux mapping.

**Comment by JohnDoe44526949** [comment]
OK!

Linux mapping:

03000000ac0500005b05000010010000,Xiaoji Gamesir-G3w,a:b2,b:b1,x:b3,y:b0,back:b8,guide:b12,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,

**Comment by lightningterror** [comment]
Thanks, I opened a PR in upstream, will pull/push the changes to our repo once it is merged.
