### ISSUE TITLE
Resident Evil 4 (RE4) - Thick White Lines

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#3190]
Version: v1.5.0-dev-3337-g90b0e7af8

It happens in previous builds. 

CPU: AMD FX-8350 / GPU: NVIDIA GTX 1060 (3 GB) / Windows 10 Pro

![Screenshot_1](https://user-images.githubusercontent.com/19964653/71497726-3fb00000-2838-11ea-81c2-d2968c2a2df2.png)

**Comment by lightningterror** [comment]
Upscaling issue, use half pixel offset.

**Comment by ElTioRata** [comment]
> Upscaling issue, use half pixel offset.

Already tried, it doesn't work.

**Comment by lightningterror** [comment]
Oh I didn't notice the white lines earlier since I was on mobile, can you upload a gs dump of the issue?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by ElTioRata** [comment]
https://drive.google.com/open?id=1NCa37JishHopXEca_Q_MKFL9SzPCvkmK

**Comment by lightningterror** [comment]
I'm unable to reproduce your issue.
![gsdx_20191227225942](https://user-images.githubusercontent.com/18107717/71534100-a7c81a00-28fc-11ea-828f-6d2e8c9e7782.png)

**Comment by ElTioRata** [comment]
> I'm unable to reproduce your issue.
> ![gsdx_20191227225942](https://user-images.githubusercontent.com/18107717/71534100-a7c81a00-28fc-11ea-828f-6d2e8c9e7782.png)

Maybe I have to send multiple frames?

**Comment by lightningterror** [comment]
Perhaps you are using some non default settings?

**Comment by ElTioRata** [comment]
> Perhaps you are using some non default settings?

I'm gonna try a full reset of the configuration. Hold on...

**Comment by ElTioRata** [comment]
Nope, I still have the same issue with default settings.

**Comment by lightningterror** [comment]
What are your gsdx settings?

**Comment by ElTioRata** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/19964653/71537984-badde880-2902-11ea-9252-1155de7853ef.png)
![Screenshot_1](https://user-images.githubusercontent.com/19964653/71537985-badde880-2902-11ea-85f5-75c41bab5bcf.png)
![Screenshot_2](https://user-images.githubusercontent.com/19964653/71537986-bb767f00-2902-11ea-9085-474429d96afa.png)

**Comment by lightningterror** [comment]
Those aren't default settings ...
Your issues are:
1. You're using skipdraw.
2. You disabled Depth Emulation.

**Comment by ElTioRata** [comment]
> Those aren't default settings ...
> Your issues are:
> 
> 1. You're using skipdraw.
> 2. You disabled Depth Emulation.

Well, after disabling skipdraw, the issue is fixed. Btw, at least for me, disabling Depth Emulation improves performance.
