### ISSUE TITLE
[DEV9 bug?] Twisted Metal: Black Online Public Beta v. 1.0 unable to initialize network adapter

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#3192]
***PCSX2 version:***
v1.5.0-dev-3337-g90b0e7af8 (2019-12-23; 90b0e7af8323c915b317fa974b0adbf24b413a16)

***PCSX2 options:***
Defaults

***Plugins used:***
* Defaults (GSdx32-SSE4, LilyPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk)
* DEV9ghzdrk: Ethernet is enabled.

***Description of the issue:***
In PCSX2, Twisted Metal: Black Online (TMBO) Public Beta v. 1.0 stalls while trying to initialize the network adapter. As a result, it's impossible to go in-game. On a real PS2 console, the beta can successfully initialize the network adapter, browse the LAN lobby and go in-game. On real consoles, after the moment the stall occurs on PCSX2, there's a 3 second wait before initialization finishes off.

The public beta is the earliest known build of TMBO. Its ELF file was last modified on March 9, 2002 (retail was July 14). Having said that, it isn't a prototype. It has its own unique SCUS code (SCUS-97860) and appears to have had a small production run.

All subsequent known builds of the game (NTSC retail, PAL beta and PAL retail) are able to successfully initialize the network adapter in PCSX2. Those latter builds go about it in a different manner; they use the EzNetCtl IRX library. I don't know what the beta used in its place.

***Blockdumps:***
* Twisted Metal: Black Online Public Beta v. 1.0 (NTSC-U) [SCUS-97860] [67AA324E]:
  * [Beta blockdump (covers startup, intro FMVs, selecting LAN menu option and network adapter initialization up until stall)](https://aced14.github.io/pcsx2-gs-dumps/tmbo-ntsc-beta_block_lan-network-adaptor-init-bug.7z)
* **For comparison:** Twisted Metal Black - Online (NTSC-U) [SCUS-97196] [C54E5CF2]:
  * [Retail blockdump (can't get it to boot... supposed to cover startup, intro FMVs, "OPTIONS - NETWORK CONFIGURATION" menu option, LAN menu option and network adapter initialization up until entering LAN lobby)](https://aced14.github.io/pcsx2-gs-dumps/tmbo-ntsc-retail_block_lan-network-adaptor-init.7z)

***How to reproduce the issue:***
1. Ensure Ethernet is enabled in the DEV9ghzdrk plugin and that a valid PS2 network configuration is present on your memory card. This game lacks a built-in network configuration utility.
2. Launch PCSX2 and fast boot the game.
3. Select "LAN" in the main menu.
4. Select your network configuration.

***Expected outcome:***
Game successfully initializes the network adapter and enters its LAN lobby. While initializing the network adapter, diagnostics appear on-screen. After the "Linking Libnet to a Device..." step appears, there's a 3 second delay until further steps appear and initialization completes.

***Actual outcome:***
Game stalls while trying to initialize the network adapter. Once on-screen diagnostics reach the "Linking Libnet to a Device..." step, no further steps appear. At this point, menu music continues playing normally.

***Diagnostics data/comparison:***
Here's diagnostics data that appears in the game's menu interface while it initializes the network adapter... Diagnostics appear by default in the beta, but are disabled by default in latter builds (can be enabled by going to "OPTIONS - NETWORK CONFIGURATION").

* **Public Beta v. 1.0 (bolded steps can only be reached on a real PS2 console):**
  > INITIALIZE NETWORK HARDWARE
  >
  > DO NOT REMOVE THE MEMORY CARD (8MB)
  > (FOR PLAYSTATION®2) IN MEMORY CARD SLOT 1
  >
  > Loading...............
  > Loading INet...
  > Loading INetCtl...
  > Loading Dev9...
  > Loading SMAP...
  > Loading MSIFRPC...
  > Loading Libnet...
  > Linking Libnet to a Device...
  > **Initializing the Stack...
  > Initializing DME...
  > Initializing Medius...
  > Hardware Initialization Complete.**
* **NTSC-U retail (for comparison, bolded differences vs beta):**
  > INITIALIZE NETWORK HARDWARE
  >
  > **AUTOMATIC CONNECTION TO THE NETWORK**
  >
  > Loading.....................
  >
  > Network Adaptor (for PlayStation®2)
  >   Loading Network Drivers...
  >   Loading INet...
  >   Loading INetCtl...
  >   Loading Dev9...
  >   Loading SMAP...
  >   Loading MSIFRPC...
  >   Loading Libnet...
  >   **Loading EzNetCtl...
  > Connecting to Network...
  >   Status (Connected)**
  > Initializing DME...
  > Initializing Medius...
  > **Initializing MGCL...**
  > Hardware Initialization Complete.

***Comparison of beta and retail builds' /NET/ folder:***
In case this is of any use, here's an outline of the /NET/ folder's contents in the beta and NTSC-U retail builds of this game. The /NET/ folder is situated at the root of the disc's files and mostly contains IRX files.

* **Public Beta v. 1.0-exclusive files:**
  * ILINK.IRX
  * ILSOCK.IRX
  * LIBNET.IRX
  * LIBNET30.IRX
  * LIBNET48.IRX
  * LIBNET64.IRX
  * NETSTAT.IRX
  * NSCONFIG.IRX
  * NTGUICNF.IRX
  * PING.IRX
  * ROUTE.IRX
  * SPUCODEC.IRX
  * VSSVER.SCC
* **NTSC-U retail-exclusive files:**
  * EZNETCTL.IRX
  * DIAL_CXT.CNF
  * DIAL_SPD.CNF
* **Files that exist in both builds:**
  * AN986.IRX
  * CXTMDM.IRX
  * DEV9.IRX
  * EZNETCNF.IRX
  * ICON.SYS
  * INET.IRX
  * INETCTL.IRX
  * INETLOG.IRX
  * LIBNETB.IRX
  * MSIFRPC.IRX
  * NETCNF.IRX
  * PPP.IRX
  * PPPOE.IRX
  * SMAP.IRX
  * SPDUART.IRX
  * SYS_NET.ICO

***Last known version to work:***
* Never worked
* Oldest tested version: R5719 (2013-08-15; e66f5156059f9c5ce458982c58c5788fa2ea2d5c), uses DEV9ghzdrk 0.3.0

***PC specifications:***
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; GPU driver: Crimson 16.2.1 Beta; OS: Windows 7 SP1

***Other comments:***
* The latest version of the CLR-DEV9 plugin (v0.8.6) doesn't get any further than DEV9ghzdrk.
* If this issue were to be fixed, I don't know if the beta blockdump I provided would contain enough data to actually finish initializing the network adapter and enter the LAN lobby. Not sure if any further data is supposed to be loaded off the disc after the stall point.
* @MrColdbird @lowlyocean @JayFoxRox @gigaherz @TheLastRar FYI.

**Comment by lowlyocean** [comment]
So you only experience the issue when using PCSX2, not a real PS2. And only for SCUS-97860. But SCUS-97196 works. And SCUS-97196 works with both the latest CLR-DEV9 and the latest DEV9ghzdrk.

Since neither plugin works with SCUS-97860, my guess would be there is the IRX files in SCUS-97860 rely on an SMAP implementation detail that's "correct" in real PS2s and that SCUS-97196 works around it by using EZNETCTL.IRX.

**Comment by Aced14** [comment]
> So you only experience the issue when using PCSX2, not a real PS2. And only for SCUS-97860. But SCUS-97196 works. And SCUS-97196 works with both the latest CLR-DEV9 and the latest DEV9ghzdrk.

That's correct.

@lowlyocean Just wondering - are you able to successfully boot the blockdump I provided for SCUS-97196 (NTSC-U retail)? Even though that build works fine for me in PCSX2, I've so far been unable to successfully boot any blockdumps I've created of it. Might open a separate issue about it. Can't really compare the beta/retail blockdumps if only one can boot...

**Comment by lowlyocean** [comment]
Just tried loading both, the retail one gets stuck after printing something like this:
>loadmodule: fname cdrom0:¥MOD¥LGDEV.IRX;1 args 0 arg 
open fail name ¥MOD¥LGDEV.IRX;1
loadmodule: id -203, ret 0


The beta one is a black screen that keeps printing:
>Block 53229 not found in dump
Block 53230 not found in dump
Block 53231 not found in dump

Haven't really worked with blockdumps before. Think this requires someone with more expertise and enough patience & free time to debug at assembly/register level.

**Comment by Aced14** [comment]
Were you trying to boot both blockdumps in PCSX2 v1.5.0-dev-3337-g90b0e7af8? I created and tested both dumps in that build...
* Beta successfully boots up for me and can follow the reproduction steps up until the stall point.
* Retail immediately black screens. The last few lines that appear in the console before that happens are the ones you quoted.

**Comment by lowlyocean** [comment]
That was it, after updating from https://github.com/PCSX2/pcsx2/commit/d7fd3d764893b8f80409609585cab8beb0a156d1 to latest build 80e3e00f9650c308fbbf1c64dc95a2d7e34d3762 I'm able to load the beta blockdump

**Comment by Aced14** [comment]
Thanks for checking :)! Glad we're getting consistent results now. I'll try to open a separate issue for the retail's blockdump problem at some point.

**Comment by MrCK1** [comment]
@Aced14 @lowlyocean Does this still happen to be an issue on the latest dev build?

**Comment by Aced14** [comment]
@MrCK1 Just retried with pcsx2-v1.7.0-dev-762-g6a7648d2b (2020-12-18; 6a7648d2b0c21850fecb1658efd946f85bb992d1)... same result as the OP :(. So this bug is still valid to this day.

**Comment by TheLastRar** [comment]
Can you test this PR? https://github.com/PCSX2/pcsx2/pull/4381
With that PR, I was able to progress past the diagnostics screen with your Public Beta block dump.

**Comment by Aced14** [comment]
@TheLastRar Just wanted to mention that I tried out one of #4381's 32 bit Windows build a few days ago. Managed to get into the LAN lobby, open a room and go in-game. Also got the same results in CLR-DEV9 v0.9.1.

Thanks for resolving this :)!
