### ISSUE TITLE
Dev9 or Memory Card Bug?

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#3195]
PCSX2 version:

Tried all new and old versions. It seems same.

Effected Game:

Motogp4 NTSC version (with online mode). EU version doesn't have online mode.

Description of the issue:

Game gets stuck at accessing memory card.

How to reproduce the issue:

Run MotoGp4 NTSC version. Make sure you have enabled either dev9ghz or clr dev9. Go into multiplayer mode and select Internet. Game starts accessing memory card and remains stuck at that forever. PCSX2 doesn't hang because you can remove the memory card at this point and game will return to earlier screen. 

Last known version to work:
Never worked?`

PC specifications:
Don't matter.

**Comment by someother1ne** [comment]
Looked at this for a few minutes and think I found a workaround. Seems like if you set the EE cyclerate to -1 (or any minus number), it won't get stuck on the "accessing mem card" screen. I don't have a network config on the card so I don't know if that matters or not.

https://www.youtube.com/watch?v=28o49dRdOsQ

![pcsx2](https://user-images.githubusercontent.com/59507554/71767188-86a49200-2ed7-11ea-9e20-07174e5c2ac9.jpg)

This was using a PCSX2 1.5 build from a couple months ago in Oct but I assume it will also work on the newest builds.

**Comment by prafullpcsx2** [comment]
Good catch. Sometimes It doesn't work with -1 but -2 and -3 definitely works.
