### ISSUE TITLE
Can't see health meter in dbbt3

### ISSUE THREAD

**Issue by buckethatboy3** [PCSX2/pcsx2#3196]
***Description of the issue:***
When I play dbbt3 I can't see the health meter. I have tried enabling 8 bit textures, just to see if that did something, and nothing came out of it. Thi problem was also happening long before i tweaked with graphical settings. Ever since I first played it on PCSX2 it has always been like this.

***PC specifications:***
CPU: Intel Core i7 4770 @ 3.40GHz GPU: 2 2047MB NVIDIA GeForce GTX 950's OS: Windows 10 64 Bit

![Capture](https://user-images.githubusercontent.com/59457686/71700407-bfceec00-2d89-11ea-9664-8f063de407c8.JPG)

**Comment by lightningterror** [comment]
Not an issue, it is caused by Alpha Stencil hack which you should never use.
