### ISSUE TITLE
Tr Underworld game stutters (progresive scan)

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#3199]
PCSX2 1.5.0-20191231220942 - compiled on Dec 31 2019

This game stutters from time to time on different levels and in log i get messages like this, doesn't netters if i'm using dx or opengl 

`Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38`

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/4023500/emuLog.txt)

**Comment by MrCK1** [comment]
Unfortunately this is not a valid issue as many details are missing and the template was not followed properly.
