### ISSUE TITLE
Feature Request: Hardware acceleration with option to increase internal resolution for GSDX in PSX Mode.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#32]
I know you are concentrated on PCSX2 and it's a lot to ask but it would be useful.

**Comment by Papermanzero** [comment]
Adding this: http://ngemu.com/threads/pcsxr-pgxp.186369/

It would  be great to have GSDX as PS1 and PS2 graphics plugin.
The benefit of GSDX would be the open source nature, so that several persons can work on that.

**Comment by willkuer** [comment]
gsdx is a ps1 graphics plugin.

The ps1 part is just completely parallel to the ps2 part. And gsdx is currently the best graphics plugin of the ps2 but really not the best for ps1.

To be honest I would just outsource the ps1 part and if somebody wants to work on it he/she can as it is open source. To build everytime the whole ps1 and ps2 plugin is not reasonable.

**Comment by FlatOutPS2** [comment]
GSdx is one of the better software plugins for some 2D games, but it's got numerous glitches and bugs in the code that would need to be solved before adding hardware acceleration. I don't think many people will want to work on it though, as there are numerous good hardware accelerated PS1 plugins already.

**Comment by MrCK1** [comment]
@FlatOutPS2 This issue can probably be closed right?

**Comment by ssakash** [comment]
Yeah, useless at this point as we can use hardware renderer via the PSX backward compatibility mode.

**Comment by FlatOutPS2** [comment]
> Yeah, useless at this point as we can use hardware renderer via the PSX backward compatibility mode.

The PSX support of PCSX2 is very basic, it's not good enough to play any game comfortably from start to finish, and it'll require a lot of work before it gets there(sadly nothing has been done for it in the past few months).

Adding hardware acceleration to the PSX mode of GSdx for use with other, properly functioning PS1 emulators would require far less effort. It just needs someone to do the work.

**Comment by lightningterror** [comment]
I'll close this. Our priority is ps2 emulation so this is a really low priority.
If someone wishes to they can work on it.
