### ISSUE TITLE
Sound hiccups when loading ISO from external drive.

### ISSUE THREAD

**Issue by isshininu** [PCSX2/pcsx2#3201]
Titles I have tested are Silent Hill 2 and 3. Sound can hiccup when loading new area (usually it's sound of a door you are opening), in SH2 random sound effect can be distorted.
I can't remember now for sure, but if place ISO on a same harddisk where PCSX2 is, quality of sound improved.
Can we get around this issue?
I report issue only now.

**Comment by mirh** [comment]
Perhaps usb is slower enough than sata to cause a noticeable delay?

**Comment by Mrlinkwii** [comment]
The external drive may be not    fast enough to read  the files and this is possibly whats effecting you , this may be down to  you using USB external drives and not a drive being plugged   in directly

**Comment by lightningterror** [comment]
As the others said, closing this as invalid.

**Comment by isshininu** [comment]
> this may be down to you using USB external drives and not a drive being plugged in directly

You are right, it was external USB HDD plugged in USB 3.0 port.

**Comment by mirh** [comment]
USB 3.0 is still [somewhat](https://goughlui.com/2013/02/26/am-i-crazy-an-ssd-in-a-usb-3-0-enclosure/) slower than SATA.. But it shouldn't be all that bad though. 

Are you sure the enclosure also is 3.0? Or well, that the disk \*itself\* isn't some super slow 2.5 laptop garbage?

**Comment by isshininu** [comment]
The only thing that come to my mind right now, is that USB ports could sometimes switch to USB 2.0 due to the error
