### ISSUE TITLE
Add message when decommission of host memory for virtual systems is complete

### ISSUE THREAD

**Issue by svidovich** [PCSX2/pcsx2#3202]
***PCSX2 version:***
v1.4.0-0-

- **Notes**:

***Description of the issue:***
Currently after clicking shutdown, a message is displayed which says 'Decommitting host memory for virtual systems...'

User is unsure whether this ever completes. It would be nice to have a message that says 'Complete' or similar after completion of this task.

***How to reproduce the issue:***
Click `file > shutdown`

***Last known version to work:***
1.4.0-0-

**Comment by tadanokojin** [comment]
Any reason in particular you want to know?

**Comment by svidovich** [comment]
Just think it'd be neat!

**Comment by lightningterror** [comment]
I will close this as it's not really a valid issue.
