### ISSUE TITLE
[Debugger] VU disassembly broken?

### ISSUE THREAD

**Issue by Fireboyd78** [PCSX2/pcsx2#3210]
***PCSX2 version:***
``v1.5.0-dev-3345-g96ef80077``

***Description of the issue:***
Debugger doesn't seem to display VU microcode properly. Very few instructions show up correctly.

![](https://i.imgur.com/5BHODty.png)

***How to reproduce the issue:***
View any known address containing VU microcode in the debugger view.

***Last known version to work:***
N/A

---

If anyone has any resources on disassembling these opcodes correctly, please let me know. I'm not sure how many people use PCSX2 for this purpose, but I've yet to find any proper tools/scripts out there. This game has symbols marking the different labels of VU microcode, and I'd like to explore them more.

Thanks!

**Comment by MrCK1** [comment]
Uncomment the define here to dump the microprograms from MicroVU. You will just have to figure out which microprogram the code you're looking for is located in (PCSX2 already shows the microprogram numbers, so you can match it up to that after it gets recompiled) 

https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/pcsx2/x86/microVU.h#L17

**Comment by Fireboyd78** [comment]
@MrCK1 Thank you so much!

**Comment by F0bes** [comment]
Waiting on https://github.com/PCSX2/pcsx2/pull/4039 before looking into this.

**Comment by F0bes** [comment]
There's not really a feasible way to tackle this currently as VU microcode and EE opcodes conflict (that's why you see odd instructions and it's not all ?????)
This would require a proper VU debugger, which is requested here #8043.
I'll close this in favor of #8043.
