### ISSUE TITLE
Halfscreen detection is flawed

### ISSUE THREAD

**Issue by tadanokojin** [PCSX2/pcsx2#3211]
Sometime ago I worked on https://github.com/PCSX2/pcsx2/pull/2934 which was a fix to handle games which split the frame buffer in order to do texture shuffle. Why they do this I am unsure. It may have been an optimization of some kind.

However, at the time I relied on some heuristics which have turned out to be flawed.
See:
https://github.com/PCSX2/pcsx2/pull/3162
https://github.com/PCSX2/pcsx2/pull/3209

Admittedly it is a shortcut and now the chickens have come home to roost.

Instead of this heuristic, what I want to do is handle the issue in the cache. @AlessandroVetere has made great progress in handling mid-texture hits in the cache for the Jak games with his tex_inside_rt work. I believe that this work can also benefit us here too.

TS relies on reading back a previous rt in a different format and mapping the pixels accordingly. Currently the issue with halfscreen is we need to be able to hit mid rt in order to get the other half. The hit will not always be dead center.

See related issues:
https://github.com/PCSX2/pcsx2/issues/2327
https://github.com/PCSX2/pcsx2/issues/1339

**Comment by lightningterror** [comment]
With the addition of https://github.com/PCSX2/pcsx2/pull/5628 this has been greatly improved, real solution will be to fix the cache but this will do for now.
