### ISSUE TITLE
Shift options

### ISSUE THREAD

**Issue by Lothar635** [PCSX2/pcsx2#3212]
Recently I was looking to use the Slow motion option in Pcsx2, and could not remember how to enable it. Well with some googling I found the Forum thread about the "Shift" button options. It would be nice to see theses options listed in the program. i.e. a tooltip stating what key or key combo is associated with it.

Thanks for the Hard Work.

**Comment by lightningterror** [comment]
Shift+Tab iirc, maybe it will be a good idea to add this info on the gui as well.

**Comment by tadanokojin** [comment]
This is all controlled by ini right now right?
Maybe a good solution should be allow mapping from the gui. Then it can be whatever you want.
