### ISSUE TITLE
Dolby Decoding

### ISSUE THREAD

**Issue by bakwas247** [PCSX2/pcsx2#3218]
***PCSX2 version:***
All

***Description of the issue:***
Not an issue per say, but could the emulator ever support Dolby Decoding to upmix into 5.1?
From this thread (https://forums.pcsx2.net/Thread-Dolby-Prologic-II-5-1-Surround-Sound) I gathered that it was not possible, but I have a foobar plugin that seems to do it, and it has source code that might help.
https://hydrogenaud.io/index.php/topic,52235.0.html

EDIT:
And of course, there's AC3Filter if you can allow external filters into pcsx2.

**Comment by bakwas247** [comment]
Just realised there's a dpl-level setting in the ini, will mess around with it, sorry for false issue.

**Comment by Dogway** [comment]
Did it work for you? It didn't make a difference in my case.

**Comment by kenshen112** [comment]
None of that code works right now, the decoder and encoder are either non existent or half baked

**Comment by kenshen112** [comment]
See issue #432

**Comment by ThreeDeeJay** [comment]
Added in https://github.com/PCSX2/pcsx2/pull/11135
