### ISSUE TITLE
OSD Configuration Dis

### ISSUE THREAD

**Issue by jkh0208** [PCSX2/pcsx2#3221]
***PCSX2 version:***
stable build v1.4.0

***PCSX2 options:***
Default settings
OpenGL, Fullscreen 4x native

***Plugins used:***
Defaults

***Description of the issue:***
Recently upgraded to version 1.4.0 of PCSX2, and the OSD Configuration button, which used to be next to Shader Configuration on my GSdx panel, has disappeared.  Has this option been moved elsewhere?  This is one of the most important options for me since I use it to let me know in fullscreen which savestate I'm on.  Random note, also started noticed frequent micro-stuttering every few minutes since updating.
![image](https://user-images.githubusercontent.com/46360615/72694836-40604d00-3aeb-11ea-9585-e4bc043b9905.png)

***How to reproduce the issue:***
Open GSdx configuration.

***Last known version to work:***
Can't remember, no longer have the old version installed

***PC specifications:***
CPU: Intel Core i5-9600K
GPU: EVGA - GeForce GTX 1660 Ti XC Ultra 6GB GDDR6
OS: Windows 10 64 Bit

**Comment by lightningterror** [comment]
OSD is available on 1.5 dev builds, not 1.4. You downgraded instead of upgrading.
https://buildbot.orphis.net/pcsx2/
