### ISSUE TITLE
Onimusha 3 NTSC, green background in the endboss level and missing bloom etc.effects  in opengl hardware mode 

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#3226]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``

pcsx2-v1.5.0-dev-3362-g9af1d3b13-windows-x86

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

default

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

Problem>

https://vimeo.com/388342183

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

unknown

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

doesnt matter what pc hardware you use ive tried

**Comment by MrCK1** [comment]
Please fill out the issue template properly to help us fix this issue, this also means that each of your issues must be submitted separately. 

Also according to your video, you are using Reshade. Please close the program and make sure it is not interfering with PCSX2 and test again. Thanks

**Comment by washingleavesandthensome23-434** [comment]
ok , shall do

**Comment by lightningterror** [comment]
Can you upload a gs dump of the issue?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by washingleavesandthensome23-434** [comment]
ill try to wrap my head around how to do so , since im a epic noob when it comes to pcsx2, should only take me a few days , i hope not..

**Comment by washingleavesandthensome23-434** [comment]
well , here you go , with commendable separate folders one for vfx issues with hardware opengl and one without vfx issues aka using software opengl, gs dumps>       

https://www90.zippyshare.com/v/2j7wdqEQ/file.html

hope this can get sorted out its really game breaking , cant play like this, definitely need this fixed

**Comment by washingleavesandthensome23-434** [comment]
tag is still set to awaiting feedback , well ive done so 9 days ago, just saying

**Comment by washingleavesandthensome23-434** [comment]
any update on this one?

**Comment by lightningterror** [comment]
Can you re upload the gsdump, preferably on github in a zip archive?

**Comment by washingleavesandthensome23-434** [comment]
ive already done so -.-', but sure , ill reup, here then

hardware vfx issues gsdump>   https://www68.zippyshare.com/v/tevNw0CL/file.html

software vfx no issues gsdump>   https://www68.zippyshare.com/v/6xIseJX4/file.html

and no i cant upload them here since i got a 10mb file limit and theyre much bigger, atleast one of em ,lols

**Comment by lightningterror** [comment]
Closing in favor of #3428
