### ISSUE TITLE
Async mix plays sounds before it should

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#3227]
PCSX2 version:
(For example, stable build v1.4.0 (or) development builds v1.5.xxx)

pcsx2-v1.5.0-dev-3362-g9af1d3b13-windows-x86

Notes:
It's preferred to only report bugs which are present on the latest development builds.
The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.
PCSX2 options:
(For example, Clamping/Rounding, Speedhacks, GameFixes)

Note: Generally it's recommended to have settings as default as possible and use the Safest preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

default

Plugins used:
(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)

Note: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like Renderer/Internal resolution/CRC Hack level/Other relevant options which were used to reproduce the issue. Additionally, providing a GS dump of the issue would also be helpful.
Description of the issue:
(What's the problem? - Screenshots showing the issue if applicable)

How to reproduce the issue:
(Detailed step by step guide on how to replicate the issue)

load up any game , but mainly dmc1 and onimusha 3 its noticeable with default audio settings and selecting async in order to take care of distortion whilst fps drops ,  during 3d engine or fmv cutscenes , this is very apparent in dmc1, the audio plays right before the actual actions happen, everything is good while actual gameplay thou, hope theres a fix or tweak for async to fix this

Last known version to work:
(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)

unknown

PC specifications:
(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)

doesnt matter what pc hardware you use ive tried

**Comment by mirh** [comment]
Can you please change the title to the much clearer: "Async mix plays sounds before it should"

**Comment by MrCK1** [comment]
I wasn't able to reproduce this issue in the games listed (I have DMC1). If the sound doesn't match the actions on-screen, the user can increase the latency to compepnsate. In addition, async mix is prone to causing sound issues so it isn't compatible with all games.
