### ISSUE TITLE
Graphical glitches in Gran Turismo 3 demos

### ISSUE THREAD

**Issue by gtgamer468** [PCSX2/pcsx2#3228]
PCSX2 version: 1.5 dev builds

PCSX2 options: All default in emulation settings, speedhacks off, x2 resolution HW

Plugins used: Gsdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

Description of the issue: I was testing various different Gran Turismo 3 demos (Official PlayStation 2 Magazine Demo Volume 5, Store Demo Volume 2, Replay Theater, US demo, EU demo) and they all have some sort of graphical glitch with the drivetrain symbols, car location sprites on the map, the circle that moves across the map in the menu, the speedometer, etc. All of these issues are related to the game's UI.

How to reproduce the issue: Boot into any one of those demos and try selecting a car then do a race and notice the game's UI like the HUD and drivetrain symbols.

Last known version to work: None

I might need to provide various blockdumps and GS dumps as needed and since there are many games, I would focus on one game at a time.

PC specifications: Intel Core i7-8750H, NVidia GTX 1060, 16GB RAM
![gsdx_20200130151112](https://user-images.githubusercontent.com/58159760/73498898-73200600-4373-11ea-8623-8a5e071183dc.png)
![PCSX2](https://user-images.githubusercontent.com/58159760/73498909-7a471400-4373-11ea-90d6-50f1f4c2822f.png)
![gsdx_20190215150624](https://user-images.githubusercontent.com/58159760/73498918-84691280-4373-11ea-966e-ff82b1cc9a08.png)
![gsdx_20190215150510](https://user-images.githubusercontent.com/58159760/73498934-8cc14d80-4373-11ea-9c6c-2ad931ffe21b.png)
![gsdx_20190215150511](https://user-images.githubusercontent.com/58159760/73498935-8cc14d80-4373-11ea-8956-5d15c0bfa2b6.png)

Here's a comparison of how it should look like per real PS2 HW
![Real HW 2](https://user-images.githubusercontent.com/58159760/73498907-7a471400-4373-11ea-8f58-bda852832f12.png)
![Real HW](https://user-images.githubusercontent.com/58159760/73498908-7a471400-4373-11ea-992c-2f37e40b2147.png)

**Comment by mirh** [comment]
Does it work properly with native resolution or sw renderer?

**Comment by gtgamer468** [comment]
I have upgraded to the 1.7 branch and using dev-14 at the moment. So I've tested the OPS2M Demo 5 with both native resolution in OpenGL HW and also tried SW renderer to no avail.

**Comment by FMecha** [comment]
GS dump from US demo (SCUS-97115): [GT3 Demo GS Dump.zip](https://github.com/PCSX2/pcsx2/files/5215544/GT3.Demo.GS.Dump.zip)
