### ISSUE TITLE
Victorious Boxers Ippo's Road to Glory

### ISSUE THREAD

**Issue by ihavetubes** [PCSX2/pcsx2#3229]
Game freezes in the start of round 2 or 3. If you pause the game the game completely freezes.

gsdx file http://s000.tinyupload.com/index.php?file_id=03981870794494068267 

I will also upload a video to show a example thanks for any help. 

Using PCSX2 1.5.0-dev-3360

**Comment by ihavetubes** [comment]
https://www.youtube.com/watch?v=zLeg4fZhOj0

**Comment by ihavetubes** [comment]
anyone have any ideas? I tried the hack time ee fix but still no luck.

https://wiki.pcsx2.net/index.php/Victorious_Boxers:_Ippo's_Road_to_Glory

**Comment by prafullpcsx2** [comment]
Can you try to run the game after enabling "fast cdvd" speed hack and report if it fixes the issue?

**Comment by ihavetubes** [comment]
> Can you try to run the game after enabling "fast cdvd" speed hack and report if it fixes the issue?

That fixed it thanks

**Comment by lightningterror** [comment]
Closing as fast cdvd is a workaround.
