### ISSUE TITLE
Feature Request > Please add a Global no interlace no shake option  + 60FPS Feature so no more 60FPS hacks are needed

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#3231]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``
feature request for the latest build
- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
 
NO Interlacing mode shakes like crazy , please fix this , ive seen no interlacing hacks over here > https://forums.pcsx2.net/Thread-No-interlacing-codes, but i recon it would be best if we could have a permanent solution for all games , same goes for 60FPS global option without hacks > https://forums.pcsx2.net/Thread-60-fps-codes

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
try any game with no interlacing and view the marvel

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``
it never has only with hacks

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by tadanokojin** [comment]
> NO Interlacing mode shakes like crazy , please fix this

Press F5

> but i recon it would be best if we could have a permanent solution for all games

Doesn't quite work like that. Those codes work by patching the SDK, the location and contents of which will vary by game.

> same goes for 60FPS global option without hacks

This one is just impossible. You can't just add a magical button which can know which part of a game engine to patch to make it 60fps. It's completely dependent on how the game engine works.

**Comment by washingleavesandthensome23-434** [comment]
i see , thought there would be a way , thats a shame , guess well have to continue using no interlace and 60 fps hacks then,  thanks for the info
