### ISSUE TITLE
Update to XAudio 2.9

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#3232]
While I was playing with *PreprocessorDefinitions Conditions* to get a graceful fallback in cases you didn't have the DXSDK.. I eventually found out microsoft has silently released 2.9 for W7 and W8.  
https://docs.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-redistributable

I'd even try to make this work myself, but I could never understand [nuget](https://www.nuget.org/packages/Microsoft.XAudio2.Redist/).

**Comment by tadanokojin** [comment]
Closing this as per the conversation in the linked pr.
