### ISSUE TITLE
False trojan positive on Spu2-X.dll

### ISSUE THREAD

**Issue by rpaulucci3** [PCSX2/pcsx2#3238]
***PCSX2 version:***
`v1.5.0-dev-3363-gf54b79c27` and newer

***PCSX2 options:***
N/A (Happens before launch)

***Plugins used:***
Default plugins (offending plugin is `Spu2-X.dll`)

***Description of the issue:***
Windows Defender and Rising detect `Spu2-X.dll` as `Trojan:Win32/Detplock` (probably a false positive, but could be induced by build chain compromise?)

Proof from VirusTotal: https://www.virustotal.com/gui/file/c76debc1d262eab91b16f2e789d0ed3efbf1531fc054883c09c49edc21e25519/detection

***How to reproduce the issue:***
* Unzip any development build of PCSX2 >= `v1.5.0-dev-3363-gf54b79c27`, obtained from the Orphis buildbot
* Open `pcsx2.exe` and run the initial setup wizard
* Windows Defender quarantines `Spu2-X.dll`, identifying it as `Trojan:Win32/Detplock`.

***Last known version to work:***
`v1.5.0-dev-3363-gf54b79c27`

***PC specifications:***
Irrelevant to the issue at hand. Windows 10 build 18363.592, Windows Defender database version 1.309.421.0.

**Comment by MrCK1** [comment]
Thanks for the report but this is not a bug. We've had a few reports of false detection from Windows Defender recently. As long as you're getting the program from the buildbot or compiling by hand, it will not contain malicious code.

**Comment by lightningterror** [comment]
I submitted the file that was triggering windows defender, should be fine now with latest defender definitions.
