### ISSUE TITLE
[Regression] Magna Carta: Tears of Blood. Some effects no longer visible with gsdx HW

### ISSUE THREAD

**Issue by ke5koB** [PCSX2/pcsx2#3239]
Hello!
**PCSX2 version:**
pcsx2-v1.5.0-dev-3365-g8550cb9b

**PCSX2 options:**
All default except x3 scallig

**Description of the issue:**
Black screen instead of blurry backgrounds in dialogs and shops. Also missing prebattle and regular loadscreens.
The problem only appears with HW renderer.
**gs dump**  
[GS dump magna carta background glitch GSDX HW.zip](https://github.com/PCSX2/pcsx2/files/4165257/GS.dump.magna.carta.background.glitch.GSDX.HW.zip)

I found a few old gsdx and did some tests.
**gsdx 20160105.Both DX11 and OGL work fine**
![gsdx_20200206122732](https://user-images.githubusercontent.com/60659806/73939734-27350a00-48fb-11ea-8aaf-8ef39447a359.png)
**gsdx 20170109 OGL has scalling problem,but DX11 still fine**
![gsdx_20200206122704](https://user-images.githubusercontent.com/60659806/73939837-577ca880-48fb-11ea-8b47-3e0de67225b4.png)
**gsdx 20170727 the problem is already present in both OGL and DX11**
![gsdx_20200206122407](https://user-images.githubusercontent.com/60659806/73939887-6ebb9600-48fb-11ea-9441-65c3bd6eecb1.png)

**spec:**  
win7x64
i5 2500k
gtx 1060

**Comment by Mrlinkwii** [comment]
is this still an issues on latest master ?

**Comment by ke5koB** [comment]
Tested with v1.7.3278 and unfortunately the issue is still present with all hardware renders.

**Comment by prafullpcsx2** [comment]
Here is a regression report I made three years ago
[MAGNA CARTA TEARS OF BLOOD REGRESSION REPORT.docx](https://github.com/PCSX2/pcsx2/files/10723736/MAGNA.CARTA.TEARS.OF.BLOOD.REGRESSION.REPORT.docx)

**Comment by JordanTheToaster** [comment]
Updated GS dump from software mode.

[MagnaCarta.zip](https://github.com/PCSX2/pcsx2/files/11049905/MagnaCarta.zip)

**Comment by JordanTheToaster** [comment]
Another thing to add if you boot the game in hardware it will be broken regardless if you switch to software or back you have to boot the game in software and stay in software for the game to function correctly currently.

**Comment by ke5koB** [comment]
I checked the game (NTSC version) with Pcsx2 1.7.4314 and the issue seem to be fixed. The game works well with all HW renderers and different scaling modes. Thank you for your hard work!

**Comment by refractionpcsx2** [comment]
Thanks for checking :)
