### ISSUE TITLE
Neopets: The Darkest Faerie (NTSC-U) [SCUS-97367] Fog, particle effects and shadows broken in hardware mode

### ISSUE THREAD

**Issue by Ember2528** [PCSX2/pcsx2#324]
When played in hardware mode the game will not show shadows, there is a box around all particle effects which is the same colour as the fog, and the fog is like a translucent wall in the distance for lack of a better way to describe it.

pcsx2 version=pcsx2-v1.2.1-639-gfa3db52-windows-x86

Plugins:GSDx 2014004113334(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014004113334
cdvdGigaherzs (2014004113334||) 0.9.0 [cdvdGigaherz]

**Comment by gregory38** [comment]
Could you give a try to the build in this thread http://forums.pcsx2.net/Thread-GSdx-2-0

Note: OpenGL only

**Comment by monster860** [comment]
Enabling accurate framebuffer in opengl mode fixes the shados. Otherwise, software mode looks perfect.

**Comment by Ember2528** [comment]
The particle effects are working with HW opengl depth and I can confirm the shadows working with accurate fb

**Comment by monster860** [comment]
Whoa, keep in mind that DirectX is still broken!

**Comment by monster860** [comment]
I just noticed that standing near a save point causes Tor's shadow to move. As if the light source at the save point is moving up and down.

*Nice job, Idol Minds*

**Comment by gregory38** [comment]
Thanks for the test. There is a dev branch to better control the level of accurate blend maybe you will be able to find a level that work a bit faster. (And I have a dev branch of this dev branch to improve it further)

**Comment by Ember2528** [comment]
Renamed it back to it's original issue, I would try and look at the branch but I'm not really willing to use my remaining drive space on visual studio just to compile a build of pcsx2

**Comment by gregory38** [comment]
The latest branch (https://github.com/PCSX2/pcsx2/pull/688) might support fog correctly. The branch allow to fine tune the blending accuracy level to keep a higher FPS. I think the level high will fix the remaining fog issue. I hope to merge the PR in a couple of days.

**Comment by gregory38** [comment]
A build is provided in the PR thread. Feel free to test it.

**Comment by Ember2528** [comment]
Won't have a pc available to test with till the end of the month, will check then

**Comment by gregory38** [comment]
Branch were merged. You can directly test the latest master.

**Comment by bositman** [comment]
Working great with OpenGL, Depth fixes the vertical lines and blending accuracy basic the fog, no issue found at all.

**Comment by gregory38** [comment]
@bositman I propose to add a 1.4 milestone to the fixed (real) bug. This way it will be easier to generate a changelog in the future.
