### ISSUE TITLE
libonepad-legacy does not recognize axis 4 or above

### ISSUE THREAD

**Issue by EthanWeegee** [PCSX2/pcsx2#3243]
***PCSX2 version:***
pcsx2-1.5.0~git20200123

***PCSX2 options:***
Any controller settings

***Plugins used:***
libonepad-legacy

***Description of the issue:***
When mapping a controller, it is not possible to map axis 4 or greater of the controller. The GIF below demonstrates this.
![libonepad-legacy-axis](https://user-images.githubusercontent.com/22205580/74106986-a9ab0d00-4b39-11ea-9e8d-4164e85db5d0.gif)

***How to reproduce the issue:***
Config > Controllers (PAD) > Plugin Settings...
Attempt to map axis 4+ of a controller

***PC specifications:***
openSUSE Tumbleweed, kernel 5.4.14-2-default

**Comment by lightningterror** [comment]
How's regular onepad btw? It's plug and play so it should work out of the box.

**Comment by EthanWeegee** [comment]
OnePad 2.0.0 works correctly, but does not support remapping which is a necessary feature.

**Comment by lightningterror** [comment]
Closing as onepad legacy won't be merged in to the core.
