### ISSUE TITLE
 Resident Evil 4 Graphical Glitch 

### ISSUE THREAD

**Issue by MetalGearAlex1** [PCSX2/pcsx2#3247]
***PCSX2 version:***
``pcsx2-v1.5.0-dev-3376-ge45fa9b6d-windows-x86`` 

- **Notes**:
  -By v1.5.0-dev-3317-gcc62165e3 | lightningterror | 2019-11-25 08:17:25 removing the RE4 CRC hack, the game DOES NOT properly render in Native x3 or any resolution (blurry) and in Custom Resolution at correct 1920x1080p the image is clear but the weird effect is there.
Resorting to older or any version before v1.5.0-dev-3317-gcc62165e3 fixes that.  
Please RESTORE RE4 CRC hack. I have tried multiple times to adjust everything, only custom works and reverting to old RE4 CRC hack. otherwise, image is blurry with regular x3 etc Resolution
EDIT: I keep hoping newer builds will restore this fix, with no luck.

![RE4 crc hack off (Blurry) x3 Native Resolution](https://user-images.githubusercontent.com/60905632/74204804-abacc300-4c42-11ea-9cb9-17a25fe63f63.png)
![RE4 glitch](https://user-images.githubusercontent.com/60905632/74204806-ad768680-4c42-11ea-9a6d-78b74eea2bd1.png)
![RE4 setup for clear pic with CRC hack](https://user-images.githubusercontent.com/60905632/74204809-aea7b380-4c42-11ea-8742-23bb96b8d81c.png)

 
***Plugins used:***
``default ``
-Everything else works like a charm with emulator.  and other games.
I use Nvidia Geforce 2060, i7-8750H, 16g DDR4, 6g DDR6 Vram

**Comment by lightningterror** [comment]
Your issue is that you're using custom resolution, it even says it's not recommended.
Other than that any misalignment can be fixed with Half Pixel offset special level.

**Comment by MetalGearAlex1** [comment]
Half pixel offset special does not fix it.  And I can show you that x3 resolution or x2 resolution is not actually 1920x1080p which is why I use the custom. for some reason it's at 1536x1344

**Comment by lightningterror** [comment]
Half pixel offset won't work properly with custom resolution.

**Comment by MetalGearAlex1** [comment]
first time I've tried that without Half-Pixel offset. so used to having it on. I thought it was a given. Thank You. :) now I can use the newer builds again! This should be a mandatory note to users. Sorry. and thank you again!  
![Half-Pixel offset off New Build x3 Native Resolution](https://user-images.githubusercontent.com/60905632/74205185-42c64a80-4c44-11ea-8a7d-4f72d3d355ad.png)
