### ISSUE TITLE
Metal Gear Solid 3 Line Issue During Cutscenes

### ISSUE THREAD

**Issue by MetalGearAlex1** [PCSX2/pcsx2#3249]
***PCSX2 version:***
``pcsx2-v1.5.0-dev-3376-ge45fa9b6d-windows-x86``

![Untitled](https://user-images.githubusercontent.com/60905632/74211848-af027780-4c5f-11ea-9bbc-0a051ed42d05.png)
![Untitled2](https://user-images.githubusercontent.com/60905632/74211852-b32e9500-4c5f-11ea-9c75-5965c663b685.png)
![Untitled4](https://user-images.githubusercontent.com/60905632/74211855-b6c21c00-4c5f-11ea-965f-6331cc22641c.png)
![Untitled1](https://user-images.githubusercontent.com/60905632/74211860-bc1f6680-4c5f-11ea-8a11-6a385e3935c1.png)
![Untitled3](https://user-images.githubusercontent.com/60905632/74211862-bde92a00-4c5f-11ea-9b3a-e4d4455687ba.png)
![Untitled5](https://user-images.githubusercontent.com/60905632/74211864-c17cb100-4c5f-11ea-8186-6a3cd7b06677.png)

***Description of the issue:***
``Weird vertical clear lines that can be very obvious.  Does not happen in any other game. Not even MGS2. Other games work fine.  Only happens during cutscenes in MGS3 Subsistence.``

***How to reproduce the issue:***
``Can't figure out what causes it and happens all the time, no matter how many settings I change, including trying DX11`` 

***PC specifications:***
``MSI 6S65 Stealth Nvidia 2060, 144hz, i7-8750H, 16Gb DDR4, 6gb DDR6 vram``

Please Help.  PCSX2 works great.  Except for Snake Skateboarding doesn't even launch at all in MGS2.  but that's another topic for another day.  this is about MGS3.  thank you. :)

**Comment by MrCK1** [comment]
Please disable all of the sprite upscaling hacks and check again

**Comment by MetalGearAlex1** [comment]
Checking it now. 1 min please

**Comment by MetalGearAlex1** [comment]
Turned off all upscaling hacks. Got red snd gree lines on right side off picture. And picture looks slightly garbly now

**Comment by MetalGearAlex1** [comment]
Align sprite off, normal vertex fixed it. No more lines...  crystal clear now. Thank you
