### ISSUE TITLE
Choppy video in Woody Woodpecker

### ISSUE THREAD

**Issue by IceString3** [PCSX2/pcsx2#3252]
***PCSX2 version:***
``1.5.0-dev-3372``

***PCSX2 options:***
``Default settings. No modifications affect the issue``

***Plugins used:***
``Default plugins``

***Description of the issue:***
``Game runs at a really low FPS, despite PCSX2 showing it's full speed.``
https://www.dropbox.com/s/8ku2zdf9k7zbg5l/Woody%20Woodpecker%20issue.mp4?dl=0

***How to reproduce the issue:***
``Start a new game. You can notice the issue right after starting the game. FPS are even lower in certain areas like the first level.``

***Last known version to work:***
``N/A.``

***PC specifications:***
``CPU:  Intel Core i7-8750H, GPU: NVIDIA GeForce RTX 2060, RAM: 16GB, OS: Windows 10 1909 x64``

**Comment by kozarovv** [comment]
This is m-bit issue, and most likely not gonna be fixed soon. 
You can grab m-bit build if you really want to play that game, that should fix it.

**Comment by atomic83GitHub** [comment]
Gift is a Eko Software game :)

**Comment by kozarovv** [comment]
I posted few patches for Eko Software games, including Woody Woodpecker. Probably best what can be done without handling mbit with correct timing. 

https://forums.pcsx2.net/Thread-Fixing-unplayable-games?pid=610320#pid610320
