### ISSUE TITLE
[SLUS-20194] Grandia II - missing textures in battle

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#3258]
***PCSX2 version:***
PCSX2 1.5.0-20200215132420

***PCSX2 options:***
Defaults, no speedhacks

***Description of the issue:***
Textures will intermittently be missing from various floor tiles in battle, usually near the edges of the visible area (and as such will change as the camera changes).
![gsdx_20200216212104](https://user-images.githubusercontent.com/17594477/74612120-bf549f80-5102-11ea-8d98-7fedc69a2899.png)

***How to reproduce the issue:***
Run game, run into monsters.

***Last known version to work:***
By all accounts, this never worked correctly. Software or hardware rendering make no difference, it's the same even in [ZeroGS](https://user-images.githubusercontent.com/17594477/74612189-5f122d80-5103-11ea-8e8d-877b92eb95b0.png).
Making this issue for better visibility and tracking, as it's not currently referenced on the GitHub repository, as far as I can tell.

***PC specifications:***
Ryzen 3900X, GTX 1080, Win10 1909

**Comment by MrCK1** [comment]
That looks more like a rounding/clamping issue. Make sure Automatic Gamefixes are enabled or try the other rounding/clamping modes on EE/VUs

**Comment by trostboot** [comment]
Gamefixes are enabled, patches and cheats are off. Rounding and clamping modes make no differences, neither does running it on EE/VU/IOP interpreters.

**Comment by tadanokojin** [comment]
sw renderer?

**Comment by atomic83GitHub** [comment]
Did you try the fpu neg div hack?

**Comment by trostboot** [comment]
Makes no difference, nor do the other FPU hacks.

**Comment by refractionpcsx2** [comment]
@trostboot Grandia 2 is now fixed in the linked PR and will be fixed in master once merged :)

**Comment by trostboot** [comment]
Can confirm it's fixed in the branch. 
Not like anyone should ever play this version of the game, but fixing incorrect behaviour is always desirable. :)

**Comment by refractionpcsx2** [comment]
> Can confirm it's fixed in the branch.
> Not like anyone should ever play this version of the game, but fixing incorrect behaviour is always desirable. :)

Yes, the Dreamcast version is superior ;) and agreed, getting the behaviour right is important!

**Comment by batabozic** [comment]
Apparently , this problem with missing floor is been resolve. But i don't get it how. " Grandia 2 is now fixed in the linked PR and will be fixed in master once merged :)" can somebody explain lite better this part? Thanks.
