### ISSUE TITLE
[SCUS-97102] GT3 replay audio lag when switching to on-car cameras

### ISSUE THREAD

**Issue by Sevin7** [PCSX2/pcsx2#3260]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3381-g977075588-windows-x86

***PCSX2 options:***
Speedhacks:
- INTC spin detection
- wait loop detection
- mvu flag hack

***Plugins used:***
Using align sprite HW hack.

***Description of the issue:***
During replays when the camera switches to an on-car view (side views, wide angle 3/4 view from the rear, top view), the audio for the car doesn't always play. It's meant to switch to a close-proximity version of the audio, but sometimes it takes several seconds of being in an on-car view for it to begin playing. It can be seen in this replay at ~10:28:
https://youtu.be/ZgBB5B1t0ss?t=625

***How to reproduce the issue:***
View a replay where the camera takes an on-car view. Doesn't always happen, maybe 50% of the time.

***PC specifications:***
CPU: Intel Xeon E3 1231v3 
GPU: Gigabyte GTX 970 
OS: Windows 10 64 Bit)

**Comment by atomic83GitHub** [comment]
Is that issue still valid?

**Comment by Sevin7** [comment]
I think it's good now.

**Comment by atomic83GitHub** [comment]
Ok, then I will close the issue.
