### ISSUE TITLE
[Suggestion] Allow GameIndex.dbf to set the Framelimiter & Split Framelimiter into a FMV & Normal setting

### ISSUE THREAD

**Issue by Black-Seraph** [PCSX2/pcsx2#3266]
I've been looking into all kinds of PS2 emulation speedhacks and found that the best way to reduce the overall emulation requirements of games is to directly mess with the game's internal engine settings.

Taking Wild Arms 5 as an example, I've managed to reduce its overall emulation requirements to a measly 50% of what it normally is for fullspeed emulation by patching the game's engine to run on a 16ms rather than 33ms frametime.

This of course has the side-effect that, at 100% emulation speed in PCSX2, the game now runs twice as fast, which is easy to alleviate by turning the frame limiter down to 50%.

This approach has one big flaw however: FMV playback.
Due to FMV playback being coupled to the sceMpeg decode functions, and those being (more or less), bound to the emulator's emulation speed, these now run at half the speed of what they normally would.

An easy solution to allow merging in speedhacks like this would be to do two things:
* Allow GameIndex.dbf to set the Framelimiter settings
* And furthermore: Split the setting into two separate ones, one for FMV and one for everything else

One could take this idea even further, allowing some kind of plugin setting framework in the future to control plugin settings in addition to just PCSX2 base settings, but this is a bit out of scope for this issue and should be brought up in another one.

**Comment by lightningterror** [comment]
Games can be modified with cheats, GameIndex.dbf is designed to get games working as accurately and without issues as possible and not for cheats.
