### ISSUE TITLE
Breath of Fire Dragon Quarter - Poor performance using OpenGL HW renderer

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#3269]
OpenGL HW at native:
![pcsx2_2020-03-01_04-23-55](https://user-images.githubusercontent.com/25664221/75616290-3f541e00-5b75-11ea-9ebe-ee88ca0afc6c.png)
OpenGL SW:
![pcsx2_2020-03-01_04-24-17](https://user-images.githubusercontent.com/25664221/75616303-5abf2900-5b75-11ea-9eb3-1277f4e87e8d.png)
DX11 HW at 3x native:
![pcsx2_2020-03-01_04-29-02](https://user-images.githubusercontent.com/25664221/75616313-627ecd80-5b75-11ea-95a6-02f98cf573ee.png)

The OpenGL HW renderer runs the game at 50% speed while both DX11 and OpenGL SW ones reach 200% speed when uncapped. Seems like a really bizarre discrepancy. 
I tested it in 1.4.0 and the discrepancy is there too.

The framerate seems to get bad if you open the plugin settings menu while using the OpenGL HW renderer. Before that it runs at 110% even at 3x native resolution.

***PC specifications:***
CPU:i5 6500 3.2Ghz
GPU:Nvidia GeForce 750 Ti
OS:Windows 7 Ultimate 64-bit SP1

**Comment by lightningterror** [comment]
Can you upload a gsdump of the issue?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by Krusher97** [comment]
[gsdx_20200303112629.gs.zip](https://github.com/PCSX2/pcsx2/files/4279485/gsdx_20200303112629.gs.zip)

**Comment by lightningterror** [comment]
I'm not picking up anything unusual and performance is good on my end, what are your gsdx settings?

**Comment by Krusher97** [comment]
It was default with all graphical hacks disabled.

**Comment by HeroponRikiBestest** [comment]
I can't test DX11, but this doesnt seem to exist on my end between SW and HW. If anyone gets drastically different performance with DX11, please say so.
![image](https://user-images.githubusercontent.com/50224630/145464750-ad8bb0a9-25f7-43f7-b8c8-fefe94a7e615.png)
![image](https://user-images.githubusercontent.com/50224630/145464758-0a303a0f-b4dd-41ee-a69d-25bfd48db9d3.png)

**Comment by refractionpcsx2** [comment]
Seems fine these days 
![image](https://user-images.githubusercontent.com/6278726/174496176-ee775969-a013-4f09-b2d3-47fc1c6cf3b7.png)
