### ISSUE TITLE
Latest PCSX2 build gets flagged by Windows Defender (and others)

### ISSUE THREAD

**Issue by vico93** [PCSX2/pcsx2#3271]
Seems like the latest automated build got flagged by Windows Defender (i cant download it no matter what, as soon Chrome finishes defender blocks the file).

Disabling temporally the WD allows me to download the file, so i uploaded it to VirusTotal and besides Microsoft other products flag the build as malicious.

[VirusTotal report of the current automated build](https://www.virustotal.com/gui/file/6765f0e4fdf353804ad03f69d07876a67a40a941104fba095b209a2326478e86/detection) (v1.5.0-dev-3391-g79db01d7e)

**Comment by RedDevilus** [comment]
We know of this issue. The AI detection is affecting the builds. It's a false-positive. We havent found the heuristic fix yet. Builds are being sent to Microsoft already to remedy. Nothing much u can do about it.

You could make a separate folder and exclude that for defender. (Don't disable defender or exclude too much)

**Comment by vico93** [comment]
Okay, thanks for the clarification!
