### ISSUE TITLE
FXAA gather4 alpha is likely broken

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#3275]
Hello,

In theory FXAA, expect to have the luminance in the alpha channel. In order to fake it, `FxaaLuma` is used as an approximation
```
float FxaaLuma(float4 rgba)
{
    rgba.w = AvgLuminance(rgba.xyz);
    return rgba.w;
}
```
This function can only work if data are the RGB channels.
I have some doubt on the following call.
```
    float4 luma4A = FxaaTexAlpha4(tex, posM);
    float4 luma4B = FxaaTexOffAlpha4(tex, posM, int2(-1, -1));
```
Those functions will return 4 random values as alpha doesn't contain luma.

**Comment by gregory38** [comment]
Btw, it could worth to precompute luma in a previous strecthrect. It can optimize away 10-20% of the shader instruction.

**Comment by stenzek** [comment]
Previous copy is gone with #7573, and doing an additional copy just to populate the alpha channel would be slower.
