### ISSUE TITLE
[Feature Request] Change external shader keybind

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3282]
![image](https://user-images.githubusercontent.com/24227051/76269169-e2d9b880-6270-11ea-8e41-8ccd287664d0.png)

Is it possible to disable or change the keybinding from (Home)?

Supposedly for reshade it would be easier for some users.

**Comment by lightningterror** [comment]
Yes it can be removed/changed, I kinda don't think many people would use this hotkey anway.

**Comment by RedDevilus** [comment]
What about all the other keybindings? Besides that one: The global ones and other specific ones?

**Comment by lightningterror** [comment]
I think mipmapping (insert), since it's basically automatic can be removed too.

**Comment by lightningterror** [comment]
Edge AA (Del), TV Shader (F7), FXAA Shader (PgUp) too I guess.

**Comment by mirh** [comment]
Or maybe we could just provide "empty keybinds" for everything and the kitchen sink, and then interested users may do what they want
So even #3283 could be happy

**Comment by RedDevilus** [comment]
Seems to be the same for https://github.com/PCSX2/pcsx2/issues/3214

**Comment by MrCK1** [comment]
Closing since it's a duplicate of #3214
