### ISSUE TITLE
[Feature Request] Change renders on the fly (Possible benchmarking tool)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3283]
I'm not sure this has been requested here before.

1) I want to change render from OpenGL to DX11 and back instead of only SW-HW switching.
Right now u have to go into plugins, freezes the game and change from there.

2) If this is not feasible a sort of timer ( that u can change) where u play a game it changes automatically the modes u selected. Benchmarking tool (?), quick for checking glitches and other problems. 
For example:
You put in 15 Seconds of OpenGL Rendering in HW mode
Then 20 Seconds of OpenGL Rendering in SW mode
Then 30 seconds of Dx11 Rendering in HW mode
Then 10 seconds of Dx11 Rendering in SW mode

This can give u quick overview about the strength of your CPU, The accuracy, etc.

This one could be a stretch though. Glad to hear some idea on the potential on this.

**Comment by mirh** [comment]
OGL and dx11 aren't really meant to be in competition with each other. 
You use the former if you can, otherwise (*AMD*) the latter. 

I'm struggling to see which kind of information "fast switching" would allow to collect.

**Comment by RedDevilus** [comment]
Maybe for comparison to each other but for data collection i see what u mean.
It's perhaps too farfetched and too gimicky for pcsx2. I just thought it as interesting option to have.
More to the normal user than a debugger or developer of testing modes.

**Comment by lightningterror** [comment]
This will be a nightmare to support and will bring a bunch of issues with it.
To check for issues you compare hw vs sw vs real hardware and then debug and attempt to fix the issue.
For benchmarking the CPU use null renderer.

Anyway I'm closing this as it's not feasible to do.
