### ISSUE TITLE
The Document of Metal Gear Solid 2 Vamp texture issue [SLUS-20543]

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3286]
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Any settings. OpenGL HW.

**The problem:**
Naked torso Vamp body texture is too dark in HW mode. SW mode doesn't have it. I haven't tested it, but the issue is most likely present in full versions of Metal Gear Solid 2 too.

**Opengl HW:**
![](https://i.imgur.com/CGh7bhc.png)

**Opengl SW:**
![](https://i.imgur.com/JZ7SXtW.png)

**gsdx snap:**
http://s000.tinyupload.com/?file_id=03431483951684271577

**How to replicate the problem:**
Watch a cutscene with Vamp where he doesn't wear his coat or in the character model viewer.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by thegamingrestoration** [comment]
Set the Blending Accuracy to Full

**Comment by MrCK1** [comment]
Thanks, closing then.
