### ISSUE TITLE
Capcom Classics Collection Vol.1: Black border bottom of display

### ISSUE THREAD

**Issue by io3432iooivzs** [PCSX2/pcsx2#3287]
***PCSX2 version:***
Cloning 2020/3/14 git
and build on Debian 10.3

***PCSX2 options:***
[ EE/IOP,VUs ]
Default

[GS Window]
Aspect Ratio: Standard (4:3)
Custom Window Size: 1280x960
Zoom: 100%

[Speedhacks]
EE Cyclerate 0
EE Cycle Skipping 0
Checked INTC Spin Detection / Wait loop Detection / mVU Flag Hack / MTVU
No checked manual game fixes

[ GSdx ]
Internal Resolusion: Native(PS2)
No Hacks

***Plugins used:***
GSdx  (GCC 8.3.0 AVX/AVX) 1.1.0[libGSdx]

***Description of the issue:***
Hi,
I played

Capcom Classics Collection Capcom Classics Collection Vol.1
SLPM-66317

Gameplay is fine, but displays black boarder in window's bottom.
This game's region is NTSC-J
But PCSX2's window bar displays internal resolution 640x512
 (Please see attachment screenshot image)
It's PAL resolution?

And I wonder if one more point.
I ripped game disk SLPM-66852
But PCSX2 detect disk image as SLPM-66317
SLPM-66852 is SLPM-66317's price down and bug fix version.

***How to reproduce the issue:***
Play Capcom Classics Collection Vol.1(NTSC-J)

***PC specifications:***
APU: AMD A8-7600
GPU: AMD KAVERI (DRM 2.50.0, 4.19.0-8-amd64, LLVM 7.0.1). Vendor: X.Org. Driver: (Core Profile) Mesa 18.3.6
OS: Debian 10.3
![pcsx2-ccc](https://user-images.githubusercontent.com/3388015/76685281-ca451600-6655-11ea-8867-f7e976e70704.jpg)

**Comment by ssakash** [comment]
Yeah, NTSC games shouldn't be using that resolution. I believe there's a saturation hack for such cases to limit them to their native resolution, I guess it isn't being applied here since the game is running in PAL video mode instead of NTSC? can I get an emulog?

**Comment by io3432iooivzs** [comment]
Thanks replay.
I've send emulog.
[ccc-emulog.txt](https://github.com/PCSX2/pcsx2/files/4334039/ccc-emulog.txt)

Add info:
Using BIOS: Japan v01.70(06/02/2003)

Black border appered both HW mode and SW mode.

**Comment by Silanda** [comment]
There are a few PAL releases of SNK games that have this problem in 60Hz mode too (SVC Chaos, for example). I fixed this in my builds by changing the hack in GSState.cpp so that line 443 reads as

`const bool unsupported_output_size = r.height() > 448 && r.width() < 641;`

rather than

`const bool unsupported_output_size = r.height() > 448 && r.width() < 640;`

Also IIRC there are some games that output progressive with a height of 256 that also have to have a hack applied to them so that only 224 lines are displayed. That hack has to be added as it isn't present in the code as is. I did consider adding these changes in a pull request, but I haven't done one so far as I'm not sure if there could be any negative consequences of those changes.

**Comment by ssakash** [comment]
>  but I haven't done one so far as I'm not sure if there could be any negative consequences of those changes.

IIRC some games didn't like it, ``640x512`` and ``640x480`` was used by games which offered both the PAL and NTSC video mode options and saturating at that case would actually crop out some content of the display rectangle.

While standardizing to NTSC/PAL acceptable values does fix the black borders I'm not sure this method is the proper way to deal with this, potentially there's a better way to emulate this like the PS2 does, but that needs some thoughts to put into it. Monitoring scissoring values could also identify cases of the black borders at like 20% of the cases, but doesn't work all the time.

**Comment by ssakash** [comment]
We could go for some heurestic approach with consideration of the DISP registers, but I believe that too would fail to be efficient at this case due to the tons of the different cases we have of this issue.

**Comment by io3432iooivzs** [comment]
> I fixed this in my builds by changing the hack in GSState.cpp so that line 443 reads as

Problem fixed. Thanks!
I seems, ON/OFF optionize width 640 upper or not.

**Comment by Margen67** [comment]
*border

**Comment by HellboundHero** [comment]
> I fixed this in my builds by changing the hack in GSState.cpp so that line 443 reads as

Hi! How do you do this? I don't see any GSState.cpp in my PCSX2 folder. I have the black bar in SVC Chaos. Is there any other fix?

**Comment by refractionpcsx2** [comment]
@HellboundHero just download the latest 1.7 nightly build from the downloads page on pcsx2.net (scroll down the page)

**Comment by HellboundHero** [comment]
@refractionpcsx2 Thanks!
