### ISSUE TITLE
Metal Gear Solid 2-3 screen transition glitch

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3288]
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Tried various settings. OpenGL SW and HW. I took snaps from US version of Snake Eater and US version of Document of Metal Gear Solid 2 (because it allows to view cutscenes), but this is fair for all versions.

**The problem:**
When fade out fade in screen transition effect is used, HW mode glitches. SW shows dithering effect in action, I don't know if it's accurate to the real hardware. In case of MGS2 there's also flickering in both SW and HW modes.

**Screens:**
**HW**
![](https://i.imgur.com/Afm38Qe.png)

**SW**
![](https://i.imgur.com/ljneFM5.png)

**HW**
![](https://i.imgur.com/27YX8Dc.png)

**SW**
![](https://i.imgur.com/ENUww68.png)

**gsdx snap:**
Document (U) - http://s000.tinyupload.com/?file_id=75647134566601285198
MGS3 Snake Eater (U) - http://s000.tinyupload.com/?file_id=03014616804415249129

**How to replicate the problem:**
In MGS3 just viewintro cutscene.
In MGS2 I used Document. First appearance of Fortune.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by coornio** [comment]
I can test this real quick, will update my comment here once done. Do you want single frames?
