### ISSUE TITLE
Metal Gear Solid 2: Sons of Liberty (U) laser sight and radar issues in SW mode.

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3294]
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Tried various settings. Works fine in OGL HW, glitches happen in SW mode.

**Screens:**
**OGL HW:**
![](https://i.imgur.com/6xWpgZf.png)

**OGL SW:**
![](https://i.imgur.com/ZMw4Z6G.png)

It seems to be very similar to PS2 BIOS boot intro in SW mode (in HW mode it's transparent similarly to the laser sight):
![](https://i.imgur.com/a39TPdW.png)

**gsdx snap:**
https://filebin.net/96t4qzbx1e1szaes

**How to replicate the problem:**
Aim with a starting gun in Sons of Liberty. Watch PS2 BIOS intro in SW mode. Also worth checking out the radar. It doesn't look right in SW mode.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by stoniemahonie** [comment]
SW v1.7.3879 Compiled on Jan 10 2023

![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230111154436](https://user-images.githubusercontent.com/13390608/211835851-ddc0a4d9-9630-4162-b432-87d97d4e2101.png)

HW (Vulkan @ 3x Native) v1.7.3879 Compiled on Jan 10 2023

![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230111154441](https://user-images.githubusercontent.com/13390608/211836027-505ed666-caf2-4194-a875-8c24a9350e68.png)

Looks good.
