### ISSUE TITLE
[Feature Request] Keyboard as controller (digital to analog)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3296]
GustavoTCB in discord suggested we should take over a feature from PPSSPP:

What the analog limiter does is, you can bind a separate key (eg. LShift), and for as long as you hold it, it will emulate the analog stick being pushed only half the way instead of all the way.

Basically instead of on and off switch for keyboard (digital). We can do in steps from half to whatever percentage pcsx2 recognizes as pressed in (analog).
We can go for games to have walking and then running with different keybindings (example of analog) There are other examples u can probably think of.

This will make the keyboard feasible as a controller replacement when we need pressure sensitivity. 

(Perhaps also for other controllers that needs analog pressure sensitivity but are only digital)

**Comment by pmerry96** [comment]
This seems like an interesting idea, I may be interested to take on trying to solve this. Is there any existing projects you know of that make use of a similar concept?

Also, to give more freedom to those emulating analog sticks, would it be beneficial to more closely mirror the behavior by allowing a 'ramp up/down' feature with the scroll wheel?
IE:
Holding W - 100% forward movement speed, mimics a fully pushed analog stick
 
Holding Left Shift + W - Defaults to 50% forward movement speed/walking, mimics a half push analog stick
 
 Holding Left Shift + W + Scroll up - Increases the 'degree the stick is pushed', starting at 50% by default,  by some minimum/user assigned granularity. Scroll down would decrease with similar behavior. 

Let me know your thoughts, if my suggestion seems like a good proposal I would be willing to take this on.

**Comment by RedDevilus** [comment]
I do have my own view on this;

Situation 1:
While holding keys are nice if you only have a keyboard but you can assign multiple keybindings with difference in percentage (or just set to fixed percentages).

Situation 2:
Use toggles (press once) instead. Second press on the key is disabling it. You can even use a third key to pick your percentages from presets or ramp up or down like the volume slider. 

Situation 3:
Use situation 2 but combine this with a controller or make it also work for controller via a combo key. This situation is niche i think.

These situations in a way mimic how PC gaming feels like. (Shift to run , Control to crouch). I think the original requester wanted something in this direction but its been sometime ago.

**Comment by pmerry96** [comment]
Now that you mention the PC gaming feel, that makes much more sense. I played PS2 but wasnt old enough at the time to really get into the mechanics of it. Were there any industry standards on when the analog stick would switch to walk/run?

**Comment by RedDevilus** [comment]
Some games like Metal Gear Solid and others basically you slightly pressed the joysticks forwards or other direction to walk instead of run. I'm not familiar of the industry standards though. It depends on the game that goes from 0-255 (X and Y axis) and picked a range example . 0-160 on y axis is walk but 161-255 is running.

Personally i just play games on PCSX2 (with a controller) where it goes to 255 which goes straight to running alone but some games rely on this behavior of pressure sensitivity and those games could be annoying without that aspect.

**Comment by pmerry96** [comment]
Sorry, I was unclear. I'm familiar with the behavior, I just never had dug into how it was handled on a lower level by the controller/analog sticks. Ive had some experience playing with them with respect to Arduino and RasPi programming enough to know the jist of how they work, enough so to emulate them in a somewhat reliable way. 

My next question though would be how one would represent a full push in one direction with a partial in another... In other terms, how would you interpret the key combination Left Shift + W + A, would the analog magnitude reducer apply to both? If not, how would it know which to apply to?

**Comment by RedDevilus** [comment]
I did the issue because A: I havent really looked into it and B: I don't really know. The dev team can give you an extensive explanation probably.

**Comment by Mrlinkwii** [comment]
this can be apparently done with macos ,
