### ISSUE TITLE
Bully (NTSC-J) - Widescreen Patches broken

### ISSUE THREAD

**Issue by SimonBestia** [PCSX2/pcsx2#3300]
***PCSX2 version:***
``1.5.0 - Dev Build 3399``

***PCSX2 options:***
Emulation Settings set on preset 3: Balanced.

***Description of the issue:***
Game appears too stretched.

NTSC-J:
![PCSX2 Screenshot 2020 03 24 - 18 57 54 77](https://user-images.githubusercontent.com/36112411/77460754-d6716600-6e01-11ea-93b0-b529c730233e.png)

NTSC-U/PAL:
(Screenshot shown is from NTSC)
![PCSX2 Screenshot 2020 03 24 - 18 59 00 88](https://user-images.githubusercontent.com/36112411/77460815-ee48ea00-6e01-11ea-86f9-b8b3521afe41.png)

***How to reproduce the issue:***
Select 16:9 in the game's menu and enable Widescreen Patches in PCSX2's settings.

**Comment by lightningterror** [comment]
WS patches aren't perfect and can cause issues in games, it's better if you post in https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches regarding the issue.

Closing this as a non valid issue.
