### ISSUE TITLE
[Bug] Weird flickering bug between movies and the menu interface in Little Britain: The Video Game

### ISSUE THREAD

**Issue by childishbeat** [PCSX2/pcsx2#3301]
***PCSX2 version:***
v1.5.0-dev-3399-g8d3ff9444

- **Notes**:
That is the latest version of PCSX2 as of this issue being submitted.

***PCSX2 options:***
Preset: 2 - Safe (Default)

***Plugins used:***
Settings: N/A (I don't know what the default settings are). Unfortunately, the graphics dump was very big (somewhere around 2.87GB), I can't make a small enough part of where I experience the issue into a graphics dump, and I think screenshots might not be sufficient evidence of the issue described in the next section.

***Description of the issue:***
When any movie included with Little Britain: The Video Game is playing, it flickers between the menu interface and the video. The video plays in the middle of the screen. The menu interface covers most of the top half of the video, albeit it's askew to the left. The game is being played from a real original CD-ROM of the game for the PlayStation 2.

***How to reproduce the issue:***
Run the PlayStation 2 version of Little Britain: The Video Game under PCSX2 (the issue might also occur if not playing the game from a real original CD-ROM of the game for the PlayStation 2, but I haven't tested it yet). When you're doing so, play any movie in Little Britain: The Video Game. It can be played either from a Tour, or the Movies section of the main menu.

***Last known version to work:***
None

***PC specifications:***
CPU: Intel Pentium G620
GPU: GeForce 8400 GS (core bus overclocked to 720MHz and memory bus overclocked to 570MHz under Windows using a mixture of Nvidia nTune and manual .nsu modification)
OS: Windows 7 (32-bit)

**Comment by Mrlinkwii** [comment]
is this still an issue on the  latest 1.7 version ? :slightly_smiling_face:

**Comment by refractionpcsx2** [comment]
Game requires Blend TFF deinterlacing, so you have a choice

1. Live with it
2. We fix it in the gamedb but the game looks a little bit blurry
