### ISSUE TITLE
Gadget Racers(PAL) - Lockup when starting a race

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#3303]
Whenever you start the Two Tone Factory S Race with a B part equipped the game locks up spamming the log with following message.
![pcsx2_2020-03-30_03-23-04](https://user-images.githubusercontent.com/25664221/77862023-72520600-7236-11ea-889b-8a6d045dbf0f.png)
The game did something similar with other tracks but it usually loaded the race after 10 seconds. However this lock up seems to be permanent. The game loads the race fine if you remove B parts from your car but you need the Hot Rod to win the race as every other racer has one. 

I have attached the memory card with the game's save on it. You need to go to select "Go on an Adventure" and then "Continue". After that go to the Race option and select Two Tone Factory from the tracks. 
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/4399856/Mcd001.zip)
[log.txt](https://github.com/PCSX2/pcsx2/files/4399857/log.txt)

EDIT: I tested the game in the latest build of Play! and it does not lock up in that.

**Comment by prafullpcsx2** [comment]
I made a quick patch for this. This may have lots o bugs so I will have a better look later. Unzip the file, put it in your cheats folder. Don't enable cheats yet. Run your game, select your level and then enable cheats before starting the race. After the race is finished make a memory card save and disable cheat for further levels. 
[010a051a.zip](https://github.com/PCSX2/pcsx2/files/4402278/010a051a.zip)

**Comment by Krusher97** [comment]
I found this issue on the forums 
https://forums.pcsx2.net/Thread-Bug-Report-Choro-Q-High-Grade-3-NTSC-J

The japanese release of this game is called Choro Q HG3 so this is probably the same issue.

**Comment by prafullpcsx2** [comment]
Enabling "GIF FIFO" gamefix seems to get rid of this problem.

**Comment by Krusher97** [comment]
It fixes it but it corrupts the menu graphics

![gsdx_20200404183942](https://user-images.githubusercontent.com/25664221/78451551-d6942000-76a3-11ea-842e-1fe61c571372.png)

**Comment by prafullpcsx2** [comment]
You can disable gif fifo after starting the race.

**Comment by atomic83GitHub** [comment]
The game needed the timing hack, closing the issue as such.
