### ISSUE TITLE
Manual gamefixes to automatic

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3305]
It would be nice to have manual gamefixes to the automatic ones. Esspecialy the ones that need software rendering switch for FMV.
(Some games already have been moved like rogue galaxy for autoswitch to SW when there is FMV)
How viable is this?

**Comment by lightningterror** [comment]
I don't understand the suggestion. Can you elaborate?

**Comment by RedDevilus** [comment]
I believe some manual gamefixes should be done with the automatic gamefixes instead of going to gamefix and enabling from there. ( I know its not recommended) in essence reducing the amount of manual gamefixes by choosing them for the users instead and they dont need to enable a manual gamefix. I understand if it doesnt work for every game.

**Comment by tadanokojin** [comment]
Some of those manual gamefixes are auto gamefixes.

**Comment by lightningterror** [comment]
Will go ahead and close this as invalid.
