### ISSUE TITLE
Frame Pacing in OpenGL

### ISSUE THREAD

**Issue by JetSetter1984** [PCSX2/pcsx2#3307]
***PCSX2 version:***
PCSX2 1.5 3396
 

***PCSX2 options:***
All default except for resolution 4x native.

***Plugins used:***
GSDX11 HW

***Description of the issue:***
Using OpenGL on various games introduces frame pacing issues, solved by using DX11 but due to broken graphics with several games this solution is not viable. Have tried various vsync combinations on and off through pcsx2 and driver, still problem persists windowed or fullscreen. EE and VU never above 55% during gameplay, CPU below 45% all times and GPU below 40% all times. Perfect example is Gran Turismo 4. Speed is indicated at a constant 100% yet frame pacing issues occur frequently, roughly every 10-20 seconds, sometimes 30 seconds. If I use the ini and put EnableVsyncWindowFlag=enabled instead of disabled I get screen tearing like mad even with vsync in the emulator. I can enforce vsync via nvidia control panel which solves the frame pacing and I only get a minor stutter once in a while. Still not an ideal situation though. I believe opengl is being shunned by windows, amd and nvidia collectively as new api's are preferred. This is why we have stupid nvidia and amd opengl drivers which do not know how to interact with windows and microsoft are not interested either. How I miss windows xp :(

***How to reproduce the issue:***
Just run Gran Turismo 4 in opengl

***PC specifications:***
CPU: Ryzen 3600X GPU: ROG STRIX 1080Ti RAM: Corsair Vengeance Pro RGB 3600MHZ OS: Windows 10 64 Bit

**Comment by Zdman7** [comment]
Quick one. Can you change your refresh rate by any chance? I found that leaving it window and not messing with any v-sync settings and changing the rate to 74hz (or was it 75) everything went buttery smooth. I actually purchased a 144hz monitor partially because of that improvement (144hz works great 120hz is alright but 100hz was terrible).

**Comment by tadanokojin** [comment]
Closing as it should be sorted now. If it's not let us know.
