### ISSUE TITLE
Build outputing warning "Policy CMP0054 is not set" since CMake 3.17

### ISSUE THREAD

**Issue by rffontenelle** [PCSX2/pcsx2#3310]
***PCSX2 version:***
1.5.0-20200408193126 - compiled on Apr 14 2020

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***
Since CMake 3.17, a deprecation warning message is displayed when "Policy CMP0054 is not set":

```
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPNG.cmake:97 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "Linux" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  cmake/SearchForStuff.cmake:21 (find_package)
  CMakeLists.txt:27 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
See full build log: 
[pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log](https://github.com/PCSX2/pcsx2/files/4476715/pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log)

***How to reproduce the issue:***
Build PCSX2 with cmake>=3.17 (see [CMP0054 in CMake docs](https://cmake.org/cmake/help/v3.17/policy/CMP0054.html))

For instance, build AUR package [pcsx2-git](aur.archlinux.org/packages/pcsx2-git/), as Arch Linux has cmake>3.17

***Last known version to work:***
N/A

***PC specifications:***
Arch Linux (rolling, 64-bit), cmake 3.17.1

**Comment by pixelherodev** [comment]
I'll tackle this one. PR incoming shortly.
