### ISSUE TITLE
Warning on GLib2's GTypeDebugFlags deprecated declarations

### ISSUE THREAD

**Issue by rffontenelle** [PCSX2/pcsx2#3315]
***PCSX2 version:***
1.5.0-20200408193126 - compiled on Apr 14 2020

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***

GTypeDebugFlags is deprecated since GLib 2.36.  Quoting the [API reference](https://developer.gnome.org/gobject/stable/gobject-Type-Information.html#GTypeDebugFlags):
> GTypeDebugFlags has been deprecated since version 2.36 and should not be used in newly-written code.
> g_type_init() is now done automatically

See warning message:

```
In file included from /usr/include/gtk-2.0/gtk/gtk.h:33:
In file included from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32:
In file included from /usr/include/gtk-2.0/gtk/gtkdialog.h:35:
In file included from /usr/include/gtk-2.0/gtk/gtkwindow.h:36:
In file included from /usr/include/gtk-2.0/gtk/gtkbin.h:35:
In file included from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35:
In file included from /usr/include/gtk-2.0/gtk/gtkwidget.h:36:
In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37:
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:34: warning: 'GTypeDebugFlags' is deprecated [-Wdeprecated-declarations]
void            gtk_type_init   (GTypeDebugFlags    debug_flags);
                                 ^
/usr/include/glib-2.0/gobject/gtype.h:685:19: note: 'GTypeDebugFlags' has been explicitly marked deprecated here
} GTypeDebugFlags GLIB_DEPRECATED_TYPE_IN_2_36;
                  ^
/usr/include/glib-2.0/glib/gversionmacros.h:500:49: note: expanded from macro 'GLIB_DEPRECATED_TYPE_IN_2_36'
# define GLIB_DEPRECATED_TYPE_IN_2_36           GLIB_DEPRECATED_TYPE
                                                ^
/usr/include/glib-2.0/glib/gmacros.h:1013:30: note: expanded from macro 'GLIB_DEPRECATED_TYPE'
#define GLIB_DEPRECATED_TYPE G_DEPRECATED
                             ^
/usr/include/glib-2.0/glib/gmacros.h:942:37: note: expanded from macro 'G_DEPRECATED'
#define G_DEPRECATED __attribute__((__deprecated__))
                                    ^
```

See full build log: 
[pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log](https://github.com/PCSX2/pcsx2/files/4476715/pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log)

***How to reproduce the issue:***
Build PCSX2 using glib>2.36

In my case, I built the AUR package [pcsx2-git](aur.archlinux.org/packages/pcsx2-git/)

***Last known version to work:***
N/A

***PC specifications:***
Arch Linux (rolling, 64-bit), [glib2 2.64.2](https://www.archlinux.org/packages/core/x86_64/glib2/)

**Comment by arcum42** [comment]
What you'll note is that the files listed are not pcsx2 files. These warnings are literally GLib complaining that Gtk2 uses depreciated code because pcsx2 uses gtk2. Pcsx2 can be compiled with gtk3, of course, but that's not the default at the moment.

Unfortunately, I haven't found any way to get rid of those warnings as of yet. It does make me feel more like redoing some of the plugin dialog boxes in wxwidgets...

**Comment by Mrlinkwii** [comment]
can be closed wxwidgets is nor longer  used

**Comment by stenzek** [comment]
Invalid after #7610.
