### ISSUE TITLE
[SLUS-21359] Metal Gear Solid 3: Subsistence - Installable camouflage not working.

### ISSUE THREAD

**Issue by TehNewbie** [PCSX2/pcsx2#3318]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3403-g58f5a5b91-windows-x86

***PCSX2 options:***
Safe defaults, with MTVU enabled. 8MB Memory Card, default settings.

***Description of the issue:***
The extra camos that one can download to the MC aren't working. The game says that "The camouflage data on Memory Card is broken." when trying to equip any of them.

***How to reproduce the issue:***
Just try to download any camo to your MC, through the in-game menu. Then try to equip it. 

***Last known version to work:***
I think that everything above 1.0.0 (this one worked just fine) has that bug. I remember trying the same thing with 1.2.1 (if I am not mistaken) and 1.4.0 some time ago, and neither of them saved camo properly.

***PC specifications:***
Intel Core i5-4460, GeForce GTX 750 Ti, Windows 8.1 64-bit

**Comment by atomic83GitHub** [comment]
This is a known issue with SIO2 emulation, I think a member of the team can explain better what is going on with that game.

**Comment by prafullpcsx2** [comment]
Loading camo from memory card seems to work. But I downloaded the save from gamefaqs. I am not sure whether camos downloaded by self will work or not.

![image](https://user-images.githubusercontent.com/12788199/80014678-41d85180-84ee-11ea-86ab-15b3072048cd.png)

**Comment by TehNewbie** [comment]
@prafullpcsx2 
I see that you're wearing the Tuxedo, it's actually unlocked after beating the game, so it should work "out of the box". I actually meant the Grenade, Mummy, etc. camos. These aren't unlocked at the end, and these are the ones that are troublesome (along with the other downloadable ones). But thank you for taking a look anyways!

**Comment by MrCK1** [comment]
For reference, this was broken by r5703 - https://github.com/PCSX2/pcsx2/commit/92487e2618ed1f0b32f937cfe59438b4c437aa63
