### ISSUE TITLE
CART Fury Championship Racing [SLES-50267[

### ISSUE THREAD

**Issue by BroKill** [PCSX2/pcsx2#3322]
PCSX2 version:
v1.5.0-dev-3390-g9711b54a8-135

PCSX2 options:
Any option and any render.

Plugins used:
Default plugins.

PC HW specs :
i7 4790k
GTX 770 2Gb
16 Gb DDR3

Hello guys, when I launch in PCSX2 the game in the title description I get a black screen after PS logo.
I tried any option and any render but nothing change.
Is there a way to run this game in PCSX2?

I noticed on YouTube an user made it run but using the NTSC-U version but I haven't  that version :(

Any help is highly appreciated.

Thanks in advance

CHEERs

**Comment by lightningterror** [comment]
Looks like it needs a patch to work properly, maybe the same patch can work for the pal version too, if not then maybe @prafullpcsx2 can port it.

```
[patches = 116154AD]
	comment=patches by Nachbrenner
	// Skip PSX2_Mpeg_PlayFile__FPc.
	patch=0,EE,00107a00,word,03e00008
	patch=0,EE,00107a04,word,24020001
	// Skip SuperSync__Fi.
	patch=0,EE,00100eb0,word,03e00008
	patch=0,EE,00100eb4,word,24020001
[/patches]
```

What is the crc of the game?

**Comment by BroKill** [comment]
Thanks for the patch but I'm not able to do that, can you do it for me?

For CRC you mean the numbers and letters in the up bar of registry near to SLES code?

This one? [2547FF67]

If it's not what I posted please tell me how to get it and I will post it here.

Thanks a lot

**Comment by lightningterror** [comment]
Place the pnach file in cheats, enable cheats in pcsx2 and see if it works.
[2547FF67.zip](https://github.com/PCSX2/pcsx2/files/4529650/2547FF67.zip)

**Comment by BroKill** [comment]
Thank you very much @lightningterror ,  it works really good, you saved my day  👯‍♂️ 

It's running good also with HW Render  :)

You guys here are awesome, keep up the good work!

CHEERs

**Comment by lightningterror** [comment]
I'd keep this open until we add it to gamedb without the need for meddling with cheats.

**Comment by BroKill** [comment]
Ok, thanks again!

Please do the same for True Crime PAL...I got a cheat here but it's better add it to gamedb ad you said.

CHEERs

**Comment by RedDevilus** [comment]
True crime NYC?

**Comment by BroKill** [comment]
No, Streets of LA PAL...it's in the closed issues because I got a working patch :)

Thanks

**Comment by lightningterror** [comment]
Should be fine now.

**Comment by BroKill** [comment]
Hello,

downloaded the new stable v1.6 and without the .pnach file you did for me it doesn't work.
Same for True Crime Streets of LA, it freezes without .pnach file.

Another thing, since I play Ridge Racer V often I need to use the build made by tadanokojin otherwise white shadows a go-go.

I'm sorry, I don't like to complaint, hope you guys fix everything.

CHEERs
