### ISSUE TITLE
PCSX2 always outputs 8 channels

### ISSUE THREAD

**Issue by Dogway** [PCSX2/pcsx2#3325]
***PCSX2 version:***
pcsx2-v1.5.0-dev-3391

***PCSX2 options:***
BIOS: Digital Output - Disabled
[OUTPUT]
Synch_Mode=0
SpeakerConfiguration=0
DplDecodingLevel=0
Latency=96
Output_Module=xaudio2

***Description of the issue:***
Regardless of audio configuration (stereo in this case) PCSX2 outputs 8 channels as detected by EqualizerAPO. Instead of 2 channels it outputs 2+6 fake channels.

***How to reproduce the issue:***
Use EqualizerAPO or other tool that works in multichannel.

***Last known version to work:***
none

***PC specifications:***
Win7 SP1 x64 4790K GTX1070 16Gb

**Comment by F0bes** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/29295048/25f5baae-4595-4681-a2d9-8663ec184146)
I'm hearing nothing with the XAudio2 or Cubeb back-ends.
Assuming this has been fixed at some point.
