### ISSUE TITLE
Joystick (SZMY-POWER CO.,LTD. PC Gamepad,GUID:03000000457500002211000010010000) isn't yet supported by the SDL2 game controller API.

### ISSUE THREAD

**Issue by V0rt3x667** [PCSX2/pcsx2#3329]
***PCSX2 version:***
v1.6.0-rc

Just reporting the following error regarding an unsupported gamepad. I will create a mapping as advised in the message below. Logged as an FYI. Thanks.

_"onepad: Joystick (SZMY-POWER CO.,LTD. PC Gamepad,GUID:03000000457500002211000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database."_

**Comment by lightningterror** [comment]
Can you post the mapping here so we can add it to the db?

**Comment by V0rt3x667** [comment]
Here is the controller mapping:

03000000457500002211000010010000300214386,SZMY-POWER CO.,platform:Linux,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

**Comment by lightningterror** [comment]
It should work now.
