### ISSUE TITLE
Loading savestate doesn't reset vibration state

### ISSUE THREAD

**Issue by RazielZnot** [PCSX2/pcsx2#3330]
If vibration was in the process before loading savestate, then controller will keep vibrating forever until you pause and unpause emulator or another vibration was issued by the game to the same motor.

Happens always in any game and annoying as hell.

**Comment by MrCK1** [comment]
Are you able to give more details on this issue? Please include your specs, plugin used, ect. Thanks.

**Comment by refractionpcsx2** [comment]
Superseded by issue #6041
