### ISSUE TITLE
visual artifacts around hud elements (gta vice city stories)

### ISSUE THREAD

**Issue by properchopsticks** [PCSX2/pcsx2#3331]
-PCSX2 version: pcsx2-v1.5.0-dev-3401-g49e316e48-windows-x86

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: [screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704448286668619846/unknown.png)

-Plugin settings: Defaults, lower internal resolution fixes the issue, also [screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704447959873617970/unknown.png)

-Description: in gta vcs usa version you can see lines that form a square/rectangle around hud elements, you can see it in [this screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704447166394925136/unknown.png) around money and time

-How to replicate: load gta vcs and set the internal resolution at anything above ~720p and you'll see the lines around the clock/money hud

-Last known version to work: Never worked

-PC specifications:
cpu: intel core i5 7400 3,00 ghz
gpu: nvidia geforce 1050 ti 4 gb
ram: 32 gb ddr4
os: windows 10

Other comments: lowering the internal resolution fixes the artifacts but the quality is poor

thank you

**Comment by MrCK1** [comment]
Those artifacts you're seeing are from using upscaling. You can try one of the sprite hacks to fix the alignment but otherwise it is not something that requires "fixing" on our end.

**Comment by lightningterror** [comment]
Originally PS2 games weren't meant to be upscaled so when users upscale them it can cause issues with many games, to alleviate the issues we have plenty of upscaling hacks to get around them. If you still experience upscaling issues then you will have to be patient and wait for future improvements.

This is a general issue and it will be closed as invalid.

**Comment by properchopsticks** [comment]
got it, thanks for the feedback.
