### ISSUE TITLE
Heavy usage of iGPU in multi-GPU systems

### ISSUE THREAD

**Issue by mradalbert** [PCSX2/pcsx2#3332]
PCSX2 version: 1.5.0-20200123134738

PCSX2 options: Any

Plugins used: Default/Any

Description of the issue:
On systems with switchable graphics (like Nvidia Optimus) integrated graphics is used heavily despite setting dedicated GPU as rendering device (for PCSX2 and system wide). Integrated graphics usage is proportional to display resolution (pixel throughput to be exact). Internal emulated resolution doesn't affect it noticeably. On my system playing Deus Ex: Conspiracy I can achieve 120 fps ingame using 200% turbo, and around 500 fps in menus when PCSX2 is in windowed mode, and window size is small. Using full screen (2560x1440 px display) fps drops to 70, and when using full screen + 4/3 -> 16/9 stretching fps drops to 60. During game play fps can drop further. Link between pixels used on physical display and fps bottleneck can be seen in integrated GPU utilization - frame rate starts to drop when iGPU hits 100% utilization.

How to reproduce the issue:
Use system with switchable graphics and observe iGPU utilization in respect of window size. If it hits 100% fps drop can be seen.

PC specifications:
CPU: Intel Core i7-4720HQ (overclocked by 50%)
GPU: iGPU Intel HD4600 (OC about 80%) + Nvidia 960m
RAM: 16 GB
OS: Current build of Windows 10, power plan set to high performance
Drivers: up to date
![1](https://user-images.githubusercontent.com/26419317/80507067-b25ff200-8976-11ea-9fd8-ff5b9fd9d172.PNG)
![2](https://user-images.githubusercontent.com/26419317/80507071-b3911f00-8976-11ea-9e64-3c1bf9053778.png)

**Comment by lightningterror** [comment]
Did you set pcsx2 on performance mode in nvidia control panel?

**Comment by mradalbert** [comment]
I just did - it doesn't change anything. As you can see on screenshots iGPU is bottleneck.

**Comment by JibbityJobbity** [comment]
You're using the DirectX 11 renderer. Can you confirm you have the Nvidia device selected as your rendering device?
Also the OpenGL renderer is optimal for Nvidia + Windows.

**Comment by mradalbert** [comment]
Yes, checked it again, Rendering device set to Nvidia GPU. You can see it's on in screenshots as well - when iGPU is bottleneck, CPU stays low, and Nvidia is about 15%, when window is small, iGPU doesn't do much (as it should), CPU hits ceiling and Nvidia GPU rises. 

I have checked OpenGL renderer again - performance is the same. Even software renderers reproduce the issue.

**Comment by Mrlinkwii** [comment]
is this still an issue on latest master?

**Comment by NadoPS** [comment]
Testing different screensizes and fullscreen nets no difference in fps. My igpu usage is limited to about 7% when running pcsx2 on the dedicated gpu. Turning off pcsx2 drops the igu usage down to 1-2%. So difference in my case is about 5%. This difference might just be how optimus operates.

System:

8750H
1060 6gb mobile
32gb Ram
