### ISSUE TITLE
Emulator main window is really difficult to see on high res monitor

### ISSUE THREAD

**Issue by VaasKahnGrim** [PCSX2/pcsx2#3333]
So I noticed there is no way to resize the initial window for the emulator. Could we get it where it can be resized for higher res monitors to better display things?
![cgjvhkvhk](https://user-images.githubusercontent.com/29955667/80513338-888dd780-8944-11ea-9e0b-05ca777d6153.PNG)

**Comment by lightningterror** [comment]
Current window is a little bigger, you can use dpi scaling too to improve the size.
Otherwise closing this as invalid.
