### ISSUE TITLE
half pixel offset not working (gta vice city stories)

### ISSUE THREAD

**Issue by properchopsticks** [PCSX2/pcsx2#3334]
-PCSX2 version: pcsx2-v1.5.0-dev-3401-g49e316e48-windows-x86

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: [screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704448286668619846/unknown.png)

-Plugin settings: Defaults, lower internal resolution fixes the issue, also screenshot

-Description: in gta vcs usa version you can see an outline on all elements on the screen giving a ghosting effect. i read online about half pixel offset that solves this issue in some games but for gta vcs doesn't seem to work. increasing the internal resolution makes it slightly better but the glow is still there.

-How to replicate: load gta vcs and you can see it around all 3d objects on screen. as in [this screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704766795567071232/unknown.png), [this screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704765953392508978/unknown.png) and [this screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704454495773392926/unknown.png)

-Last known version to work: Never worked

-PC specifications:
cpu: intel core i5 7400 3,00 ghz
gpu: nvidia geforce 1050 ti 4 gb
ram: 32 gb ddr4
os: windows 10

Other comments: no

thank you

**Comment by MrCK1** [comment]
This isn't a support forum, if you need further help please go to forums.pcsx2.net. Thanks.

**Comment by properchopsticks** [comment]
ow i'm sorry, my bad, i thought the features were supposed to work, i didn't know they were just for looks.

**Comment by refractionpcsx2** [comment]
The hw hacks are very situational and are there to try and combat artifacts caused by upscaling, since PS2 games were never intended to be upscaled in the first place.  Unfortunately they don't help with everything and different hacks are required for different games.  But as MrCK1 said, make a post on the forum and I'm sure somebody will be able to help you out in finding the correct combination of settings which will hopefully make your game look better.

**Comment by properchopsticks** [comment]
i understand, thank you for the reply and sorry if i was too unpleasant.

**Comment by refractionpcsx2** [comment]
You weren't unpleasant, just this isn't the place for your query :)
