### ISSUE TITLE
Incredible Hulk Ultimate Destruction - Broken bloom effect in HW renderer

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#3338]
Theres a fake bloom effect which is broken only in the OpenGL HW renderer even at native resolution.

OpenGL SW:
![gsdx_20200429134505](https://user-images.githubusercontent.com/25664221/80709959-d4d74400-8b0b-11ea-8bb4-e40991276aa4.png)

OpenGL HW:
![gsdx_20200429134507](https://user-images.githubusercontent.com/25664221/80709985-df91d900-8b0b-11ea-825b-ae84af5fb556.png)

DX11 HW:
![gsdx_20200430175034](https://user-images.githubusercontent.com/25664221/80710003-e6b8e700-8b0b-11ea-8e71-6559b4a801d8.png)

I've tried various combination of settings and hardware hacks, nothing seems to do anything.

**Comment by lightningterror** [comment]
A gsdump would be nice.

**Comment by Krusher97** [comment]
[gsdx_20200430192959.gs.zip](https://github.com/PCSX2/pcsx2/files/4558751/gsdx_20200430192959.gs.zip)

**Comment by lightningterror** [comment]
Set blending to none.
