### ISSUE TITLE
Final Fantasy X International - Cactuar Village Sidequest Text Bug

### ISSUE THREAD

**Issue by yrhjtyjtyjydt** [PCSX2/pcsx2#3339]
***PCSX2 version:***
1.5.0-dev-3406

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
 When doing the cactuar village sidequest red light green light minigame on the airship, the boxes display the wrong text and sometimes none at all. This bug only occurs in the International version of the game

PCSX2: 

https://www.youtube.com/watch?v=yp7EBMCstyM

PS2: 

https://youtu.be/I4W85T32UX8?t=472

***Last known version to work:***
none known, goes far back as 0.9.8

**Comment by lightningterror** [comment]
More information, and a gsdump would be nice.

**Comment by emjzero2** [comment]
[ffx.zip](https://github.com/PCSX2/pcsx2/files/4561738/ffx.zip)
Memory card 2 Oasis save file, board the airship after

The minigame is displaying the wrong strings of text, this is the only part of the game where this happens.

**Comment by lightningterror** [comment]
I also want a gs dump for easier testing.
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

Same goes for the other opened issues regarding visuals. Settings used, renreder hw, sw, opengl/d3d11, any options that can may actually fix the issues.

**Comment by emjzero2** [comment]
[gsdx_20200501004836.gs.zip](https://github.com/PCSX2/pcsx2/files/4561895/gsdx_20200501004836.gs.zip)

**Comment by vcx33** [comment]
Happens on real hardware too. This only happens if you do the sidequest BEFORE fighting sin for the first time.

https://youtu.be/X-ZyUkj0sYU?t=1288
