### ISSUE TITLE
Final Fantasy X Glitched Level Meshes

### ISSUE THREAD

**Issue by yrhjtyjtyjydt** [PCSX2/pcsx2#3341]
***PCSX2 version:***
1.5.0-dev-3406

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
Some parts of the "Macalania Woods - Lake Road" location have "holes" in them.
Similar to #983

***PCSX2:*** 

![tsehtrs](https://user-images.githubusercontent.com/57640063/80768812-55656700-8b43-11ea-9a41-868761307f7c.jpg)

***PS2:*** 

![redhg](https://user-images.githubusercontent.com/57640063/80768854-72019f00-8b43-11ea-8935-18a26e27fc44.png)

***Last known version to work:***

none known, goes far back as 0.9.8

**Comment by prafullpcsx2** [comment]
A memory card save or savestate (if save point is too far from problem area) may prove useful.

**Comment by emjzero2** [comment]
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/4562173/Mcd001.zip)
For Final Fantasy X International NTSC-J

**Comment by orbea** [comment]
@lightningterror Does this still need more feedback? Also applies to https://github.com/PCSX2/pcsx2/issues/3340 and https://github.com/PCSX2/pcsx2/issues/3339.

**Comment by lightningterror** [comment]
Probably not, haven't had time to look at it.

**Comment by Lolibox** [comment]
same as #983
![pcsx2_RsckDGfc6E](https://user-images.githubusercontent.com/49990481/112053494-cd0cfd80-8b2a-11eb-87d0-32c53a1c0b83.png)
![image](https://user-images.githubusercontent.com/49990481/112053521-d302de80-8b2a-11eb-867f-5cba94e302fd.png)
software mode edge anti-aliasing closes the gaps
