### ISSUE TITLE
Controller: PDP Kingdom Hearts Controller, not yet supported by new OnePad

### ISSUE THREAD

**Issue by keiichiiownsu12** [PCSX2/pcsx2#3342]
***PCSX2 version:***
1.5.0.r3408.f0d08aa7d

***Plugins used:***
OnePAD 20200501000955 2.0.0 [libonepad]

***Description of the issue:***
My wired controller, Joystick (PDP Kingdom Hearts Controller,GUID:030000006f0e0000c802000012010000), is not supported yet by the current OnePad plugin. Or, more specifically:
<pre><code>onepad: Joystick (PDP Kingdom Hearts Controller,GUID:030000006f0e0000c802000012010000) 
isn't yet supported by the SDL2 game controller API</code></pre>

***Last known version to work:***
Works currently on the older OnePad version, provided in the same dev-build: OnePAD 20200501000955 1.3.0 [libonepad-legacy]

**Comment by lightningterror** [comment]
Can you create the mapping and post it here?
You can use http://www.generalarcade.com/gamepadtool/

**Comment by keiichiiownsu12** [comment]
Here it is:
030000006f0e0000c802000012010000,PDP Kingdom Hearts Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,

**Comment by lightningterror** [comment]
Should be good now.

**Comment by keiichiiownsu12** [comment]
Tested out the controller by trying to configure in OnePad 20200501000955 2.0.0 [libonepad]. The plugin can detect the controller and even activate the haptic (rumple) function. However, I am unable to map/assign buttons and joysticks.

**Comment by lightningterror** [comment]
Onepad is plug and play, you cannot configure mappings. Onepad legacy allows for manual mappings.
