### ISSUE TITLE
Burnout 3: Weird line in the middle of the screen

### ISSUE THREAD

**Issue by MegaDeox** [PCSX2/pcsx2#3344]
***PCSX2 version:***
1.5.0-dev-3305

***PCSX2 options:***
I've tested this using Safest and Direct3D11 with the default options, other than the resolution bump to 1080p.

***Plugins used:***
Direct3D11 

***Description of the issue:***
So I've been playing Burnout 3, and aside a couple of issues the game runs beautifully. 
The first issue is the sun and its camera glare effect going through walls. This happens in Burnout Revenge as well and I know it's an old bug, so never mind that.

My issue is there's a weird line in a fixed poisition that moves with me as I race. Here's a picture:
Direct3D11 
![image](https://user-images.githubusercontent.com/12670485/80801343-b8431680-8bb4-11ea-90a3-179753602496.png)

I highlighted it here:
![image](https://user-images.githubusercontent.com/12670485/80801358-c5600580-8bb4-11ea-9947-a9744da66c77.png)

***How to reproduce the issue:***
Just play Burnout 3. As I played around with the settings I didn't find any setting that affected this, aside from of course software mode.

***Last known version to work:***
I never played this on older revisions.

***PC specifications:***
Gigabyte 1060 6GB, Intel Core i5-3450, 16GB RAM, Windows 10.

Let me know if you need any other settings or if you want me to play around with something. Thanks!

**Comment by lightningterror** [comment]
Did you try Half pixel offset?

**Comment by MegaDeox** [comment]
What do you know, setting it to Texture seems to have solved the issue. That was quick. Thanks!

What does this affect other than this issue? Should I just leave it on for everything?

**Comment by lightningterror** [comment]
Depends on each game, it's for upscaling.

**Comment by MegaDeox** [comment]
Fantastic. Thanks!
