### ISSUE TITLE
Got Crash when set Audio Expansion Mode to surround sound 7.1 or non Stereo mode

### ISSUE THREAD

**Issue by dfr1238** [PCSX2/pcsx2#3348]
***PCSX2 version:***
v1.5.0-dev-3414-g18f772e71

***PCSX2 options:***
default setting on almost any setting,only change only these setting below
int res=2x native
Opengl HW
SPU2-X, Audio Expansion Mode:surround sound 7.1
BIOS: SCPH-90006_BIOS_VX_HK_220

***Plugins used:***
default plugins

***Description of the issue:***
after set on surround sound 7.1,pcsx2 got crash in 10-30 sec

***How to reproduce the issue:***
go to plugins,set plugins to SPU2-X,and set Audio Expansion Mode to non Stereo mode

***Last known version to work:***
1.4.0 stable,or using older SPU2-X plugins

***PC specifications:***
OS:Windows 10
CPU:i5-8300h
RAM:16G RAM
VGA:GTX 1050ti
SOUND CARD:USB,Xonar U7 Mkii,set on 16bit,48khz,connect to 3.5mm headphones
Windows Spatial sound mode:Dolby Atmos for headphones

**Comment by MrCK1** [comment]
Check using 1.5, should be OK - buildbot.orphis.net/pcsx2

**Comment by dfr1238** [comment]
> 
> 
> Edit: sorry I misread. Is there a specific game this occurswoth or can it happen during boot?

seem is in game and also bios menu

**Comment by dfr1238** [comment]
test game:
Devil May Cry 3 - Dante's Awakening (USA) (En,Ja) (Special Edition) - crash
Metal Slug Anthology (USA) SLUS-21550 (1.00) - Crash
BIOS - Crash

**Comment by dfr1238** [comment]
in game mostly time crash before in the main menu
bios menu stay like a 1 min around then crash

**Comment by dfr1238** [comment]
log file seem didn't have any error message

**Comment by dfr1238** [comment]
> 
> 
> Edit: sorry I misread. Is there a specific game this occurswoth or can it happen during boot?

i got weird thing here,after i checked 'Enable Debug Options' in SPU2-X,and select all sub-option in that,didn't get crash now lol
