### ISSUE TITLE
Bug: Widescreen patches setting causing EE Rec boot failure

### ISSUE THREAD

**Issue by FuxorLuck** [PCSX2/pcsx2#3349]
***PCSX2 version:***
``1.7.0 - 116``

Latest known version without this issue
This issue won't appear on PCSX2 1.4.0 and the earliest build I found with this problem is Pcsx2 1.5.0- dev -3332 but it probably happened before this build 
Can someone send a link for all PCSX2 versions in 2019?

***Description of the issue:***
`If you boot (Full/Fast) a game with "Enable widescreen patches" and Set EE to Recompilear the game will crash or suffer from heavy graphical glitch some examples:

Digital Devil Saga 1 - the game won't boot

Digital Devil Saga 2
objects won't appear and you will be stuck in the room
The Bug:
https://ibb.co/kXrTMsL
How It should look:
https://ibb.co/1KHGV3D

Dual Hearts - crashes at a certain point in the game (after beating the Statue Knight boss)
it happens here 10:16
https://www.youtube.com/watch?v=a0KMKZ-Dp9A
I will try to upload a video my self that shows this issue

Shadow Hearts - Covenant - crashes when reaching ingame (Also the rendering is changing from interlacing to progressive for some reason)

Shadow Hearts - From the New World - heavy graphical glitch
https://ibb.co/jzpkzpV

Primal - Game Won't boot (The game doesn't have widescreen patches)

https://vimeo.com/437333792

Note: This also happens if you boot the game from iso format and if you disable GSDX Overrides

Rogue Galaxy

The game crashes after pressing X in a save point

Dark Cloud

In the 5th Floor in Gallery of Time, The Game will Hang

https://vimeo.com/user119307234/review/445166339/5a91f2604a

**Comment by RedPanda4552** [comment]
Please avoid creating duplicate issues when you do not like how the last one turned out.

In this particular case, the inaccuracy in the interpreter is likely executing code modified by the patch differently, and allowing the game to boot. Perhaps the widescreen patch needs to be revisited and modified to work better.

As this is an arbitrary fix to make one game's widescreen patch work, it is not the kind of thing we would like to implement as a feature to the emulator as a whole.

**Comment by FuxorLuck** [comment]
The Widescreen works on PCSX2 1.4.0 whitout those issues and when booting the game using  EE interpreter ( The more accurate mode) the widescreen works fine 
So It's is a problem
Like i said because the first time my issue was closed because i am using widescreen hacks and because It's really annoying to have to sawp to interpreter mode just to boot the game
I opened this feature request.
as for what is the causing of it, no idea

here is the original issue

https://github.com/PCSX2/pcsx2/issues/3182

**Comment by RedPanda4552** [comment]
The EE interpreter is NOT more accurate and should never be relied on for accurate behavior. I would instead suggest that the recompilers in 1.4.0 were not behaving correctly and still allowing this patch to work. 

All this aside, if there is a way to identify what the problem actually is we would be glad to look at it, but we will not inplement a hack of this sort just for a community made patch for a single game. We would be much more interested in looking at what core issue (if as I stated before, one even exists and this is not just a bad patch) is actually causing the problem.

**Comment by FuxorLuck** [comment]
I understand thank you for your answer :)

**Comment by FuxorLuck** [comment]
@RedPanda4552 

Hey, Primal can't boot unless you use EE interpreter mode to boot the game
It is because of the patches Pcsx2 automatically use when it boots the game

Maybe that helps?

**Comment by FuxorLuck** [comment]
Here is a video that is proving it's a problem

https://vimeo.com/user119307234/review/437333792/60a5e5839e

**Comment by refractionpcsx2** [comment]
Okay can you please make a new issue for the Widescreen patches in EE Rec bug please?

**Comment by refractionpcsx2** [comment]
Okay this requires a bug fix, not an option to boot in interpreter mode. I have changed the heading to reflect this

**Comment by washingleavesandthensome23-434** [comment]
cant wait till this is fixed pretty annoying bug i must say ...

**Comment by incognitoh** [comment]
just did multiple tests of Primal, same game version as OP,  on a 1.7 build from about 2 weeks ago, and the game loads perfectly fine with widescreen patches enabled and using default settings.  no tricks needed.  but the op has several patches loading in his console window? why are so many patches loading when he has patches disabled?  something is fishy, but either way, Primal works fine, no issues with the widescreen setting enabled.

**Comment by washingleavesandthensome23-434** [comment]
what? no ... best way to test this is to use something such as a no interlacing patch or such and youll instantly notice this issue , anybody that got onimusha 3 can test this pnach to see the issue at hand
6BF11378.pnach  , contents>

patch=1,EE,2027AD9C,extended,34037900
patch=1,EE,0027B428,word,00000000

**Comment by FuxorLuck** [comment]
> just did multiple tests of Primal (iso), same game version as OP, on a 1.7 build from about 2 weeks ago and using fast boot, and the game loads perfectly fine with widescreen patches enabled and using default settings. no tricks needed. but the op has several patches loading in his console window? why are so many patches loading when he has patches disabled? something is fishy, but either way, Primal works fine, no issues with the widescreen hack setting enabled. on windows 10 btw

Hey when I played Primal on PCSX2 
There was a still a bug In Primal that caused the game to Slowdown to unplayable state
Essperial made a hack in order to fix this 
Now this hack is Auto game fix

https://forums.pcsx2.net/Thread-Fixing-unplayable-games?page=43

**Comment by FuxorLuck** [comment]
Hey, Seems to be fixed in the latest versions
