### ISSUE TITLE
Everybody's / Hot Shot series shadows issues

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#3351]
***PCSX2 version:***
v1.5.0-dev-3389-g6e22efe79

***PCSX2 options:***
Default, tried all GSDX hacks, all rounding/clamping modes. 

***Plugins used:***
Default that came with this version of pcsx2. SSE2, and AVX2 version of GSDX tested

***Description of the issue:***
This issue include 3 games, Hot Shot Tennins, and Hot Shot Golf 3/4 But gs dump came from Everybody's Golf / HST 4

Shadows aren't displayed in hardware mode. Causing major slowdown, making game unplayable in hardware mode at all. Is confirmed that is shadow issue, patch to remove them on EE side, make game work smooth again.

Hardware:
![hardware](https://user-images.githubusercontent.com/15552250/80869414-93c46880-8ca0-11ea-9cfc-7ec9486f6e1a.png)

Software:
![software](https://user-images.githubusercontent.com/15552250/80869420-9a52e000-8ca0-11ea-8a1e-b80b29539ee9.png)

***How to reproduce the issue:***
Go in-game on any court / track

***Last known version to work:***
None, didn't tested below 1.4.0

***PC specifications:***
i5 4570, GTX1060 3GB, 8 GB ram

[snaps.zip](https://github.com/PCSX2/pcsx2/files/4568160/snaps.zip)

**Comment by MrCK1** [comment]
The slowdown issue is related to depth AFAIK.

**Comment by kozarovv** [comment]
Ok, so made few more tests. There is a difference when I disable depth emulation. 

On OGL it came from 5fps to ~20fps, so for sure there is a noticeable change. 
On DX11 disabling depth emulation completely fix slowdown. Game run full speed. 

Just for sure, i use Nvidia card, with latest drivers. So no "radeon OGL issue" here. 

In both cases shadows aren't rendered at all.
I think is worth to mention that disabling shadow thru debug menu, or thru patch that do same thing. We can get full speed also on OGL. 

All this of course for hardware mode only.

**Comment by kozarovv** [comment]
While I made tests for other issue, I retested shadows on  0.94, 0.98, 1.1 (random), 1.3 (random), 1.4, and few 1.5.0 including latest.

Shadows are not rendered in hardware mode on any render, in every tested pcsx2 version. Only difference is that on some early builds there is no slowdown. Maybe those versions not support depth emulation, or something. No idea.

**Comment by benderscruffy** [comment]
still an issue in v1.7.4359
