### ISSUE TITLE
Update wxWidgets to 3.0.5

### ISSUE THREAD

**Issue by arcum42** [PCSX2/pcsx2#3353]
***PCSX2 version:***
All versions

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***
The version of wxWidgets currently in the trunk is 3.0.3. The current stable release of wxWidgets is 3.0.5. While there is a 3.1.x trunk, that is the unstable version. On Linux, it uses the version distributed with the individual distribution, which is normally the latest on the stable 3.0.x line.

Note that the version in trunk has changes from 3.0.3, which would need to be ported over as well.

***How to reproduce the issue:***
Examine the version number in the version header in trunk.

***Last known version to work:***
N/A

***PC specifications:***
N/A

**Comment by lightningterror** [comment]
Closing as wx is on it's last leg.
