### ISSUE TITLE
[Feature Request] SingStar Disc Swap

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3355]
***PCSX2 version:***
1.5.0 3403

All versions of SingStar except the original version and the disney version are supposed to support a disc swap feature where the disc but doesn't work in the emulator.

**Comment by seta-san** [comment]
https://www.youtube.com/watch?v=OCiLoM4YSV4

this is a link of what it does. when trying to do a disc swap it just hangs there unaware you've put in a new disc.

**Comment by seta-san** [comment]
`PCSX2 1.6.0-20200506140834- compiled on May  6 2020
Savestate version: 0x9a0e0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 19041), 64-bit
	Physical RAM     =  32709 MB
	CPU name         =  Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  2.992 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfcbfbff fedaf383
	x86EFlags        =  2c100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Reserving memory for recompilers...

Loading plugins from F:\Emulation\PS2\PCSX2\plugins...
	Bound   GS: gsdx32-avx2.dll [GSdx 20200506140834 (MSVC 19.25 AVX2/AVX2) 1.2.0]
	Bound  PAD: lilypad.dll [LilyPad (20200506140834) 0.12.1]
	Bound SPU2: Spu2-XSetaEdit.dll [SPU2-X 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20200506140834 0.11.0]
(GameDB) 9858 games on record (loaded in 141ms)
	Bound  USB: USBqemu-wheel-0.9.0.dll [Qemu USB Driver (Wheel) (Apr 19 2020) 0.9.0]
	Bound   FW: FWnull.dll [FWnull Driver 20200506140834 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20200506140834 0.5.0]
Plugins loaded successfully.

HLE Notice: ELF does not have a path.

Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
dev9null plugin version 0,5
Initializing dev9null
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
	Opening CDVD
isoFile open ok: E:\SINGSTAR_POP.ISO
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (2222832 sectors)
	Opening USB
	Opening FW
	Opening DEV9
Opening Dev9null.
3.x GL context successfully created
OpenGL information. GPU: GeForce GTX 960/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 445.87
INFO: GL_ARB_sparse_texture is NOT SUPPORTED
INFO: GL_ARB_sparse_texture2 is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_compute_shader is available
INFO: GL_ARB_shader_storage_buffer_object is available
INFO: GL_ARB_texture_view is available
INFO: GL_ARB_vertex_attrib_binding is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_multi_bind is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available
INFO: GL_ARB_get_texture_sub_image is available

Current Renderer: OpenGL (Software renderer)
Available VRAM/RAM:3328MB for textures
GSdx Lookup CRC:0
McdSlot 0 [File]: F:\Emulation\PS2\PCSX2\memcards\Mcd001.ps2
McdSlot 1 [File]: F:\Emulation\PS2\PCSX2\memcards\Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: USA     v01.60(07/02/2002)  Console
	BIOS rom1 module not found, skipping...
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
# Initialize memory (rev:3.63, ctm:196Mhz, cpuclk:147Mhz detected)
*Unknown 8 bit read at address 1f80146e

PlayStation 2 ======== Hard reset boot
 ROMGEN=2002-0207, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20020207-164243,ROMconf,PS20160AC20020207.bin:11552>
# Total accessable memory size: 32 MB (B:2:8:0) (363:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
*Unknown 8 bit read at address 1f80146e
*Unknown 8 bit read at address 1f80146e
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  7 2002 16:41:20
  CPUID=2e20, BoardID=0, ROMGEN=2002-0207, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SCUS_975.80;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
ELF (cdrom0:\SCUS_975.80;1) Game CRC = 0x291D907D, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SCUS_975.80;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SCUS_975.80;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SCUS_975.80;1
0 00100000 002e0598 ...............................................
Loaded, cdrom0:¥SCUS_975.80;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
*Unknown 8 bit read at address 1f80146e
*Unknown 8 bit read at address 1f80146e
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
Get Reboot Request From EE
GSdx Lookup CRC:291D907D
ROM directory not found

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.2

    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥IOP¥LIB¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥IOP¥LIB¥SIO2D.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥IOP¥LIB¥DBCMAN.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥IOP¥LIB¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥IOP¥PAK.IRX;1 args 0 arg 
PFS_Start: Starting!
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥IOP¥SINGSTRM.IRX;1 args 0 arg 
IRX_VERSION_NUMBER = 0
loadmodule: id 30, ret 0

------------------------------------------------
SingStream
built Aug  4 2006 at 13:31:48 
------------------------------------------------

PFS_GetIopIndex: IOPisCD: 1 
PFS_GetIopIndex cdrom0:¥PAK_IOPM.PAK;1 ret: 1 lsn: 18720
(UpdateVSyncRate) Mode Changed to NTSC.
(UpdateVSyncRate) FPS Limit Changed : 59.93 fps
*Unknown 8 bit read at address 1f80146e
*Unknown 8 bit read at address 1f80146e
loadmodule: fname cdrom0:¥IOP¥LIB¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 31, ret 2
loadmodule: fname cdrom0:¥IOP¥LIB¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 32, ret 2
loadmodule: fname cdrom0:¥IOP¥LIB¥VDGCU_D.IRX;1 args 0 arg 
loadmodule: id 33, ret 0
loadmodule: fname cdrom0:¥IOP¥LIB¥USBD.IRX;1 args 59 arg conf=2048
USB Driver (Version 1.1.0)
loadmodule: id 34, ret 2
loadmodule: fname cdrom0:¥IOP¥LIB¥EYETOY.IRX;1 args 31 arg pack=1
usbcam: max usbcams = 1, pack = 1, multi isoc = 8, iopstrip = 0
usbcam: mic sample = 0, mic size = 1024, frame size = 28672
usbcam: DMA thpri = 49, SIFRPC thpri = 50
loadmodule: id 35, ret 2
loadmodule: fname cdrom0:¥IOP¥SCREAM.IRX;1 args 0 arg 

==========================================================
 SCREAM (c)2003        Sony Computer Entertainment America
 by Buzz Burrowes                             v2.0.3
                        (built Jan 16 2004 at 11:08:44)
 (build with sce library rev 2.8.1)
==========================================================
    Thread Priorities:
                         Sound Tick = 9
                           Main RPC = 58
                        Loading RPC = 59
==========================================================

loadmodule: id 36, ret 0
loadmodule: fname cdrom0:¥IOP¥SINGSND.IRX;1 args 0 arg 

------------------------------------------------
SingSnd
built Jun 21 2005 at 13:16:47 
------------------------------------------------

loadmodule: id 37, ret 0
loadmodule: fname cdrom0:¥IOP¥USBMIC.IRX;1 args 0 arg 
loadmodule: id 38, ret 0
loadmodule: fname cdrom0:¥IOP¥MONITOR.IRX;1 args 0 arg 
Mic Monitor-start: ----------------------
Mic Monitor-start: Mic monitor v0.1b
Mic Monitor-start: ----------------------
loadmodule: id 39, ret 0
singstar: ep control cs 1, cn FF, 1 81 data:singstar: ep control cs 1, cn FF, 1 81 data:PFS_GetIopIndex: IOPisCD: 1 
PFS_GetIopIndex cdrom0:¥PAK_IOP0.PAK;1 ret: 1 lsn: 80256
PFS_GetIopIndex: IOPisCD: 1 
PFS_GetIopIndex cdrom0:¥PAK_IOP1.PAK;1 ret: 1 lsn: 1127760
Mic Monitor-MonitorStart: Started ok
singstar: mute 0, lvol   0, rvol 240
singstar: mute 0, lvol   0, rvol   0
time since timer started: 2 [usec] 0 [msec] 0 bars 
	HotSwapping to new ISO src image!
	Closing CDVD
Opening plugins...
	Opening CDVD
isoFile open ok: E:\SINGSTARQUEEN.ISO
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1564160 sectors)
Plugins opened successfully.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SCUS_976.43;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
ELF (cdrom0:\SCUS_976.43;1) Game CRC = 0xA648229F, EntryPoint = 0x00100008
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
Closing Dev9null.
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Delete 0 Shaders, 34 Programs, 28 Pipelines
Plugins closed successfully.
`

**Comment by seta-san** [comment]
i believe this is where the code would have been in AppCoreThread.cpp

`void AppCoreThread::ChangeCdvdSource()
{
	if( !GetSysExecutorThread().IsSelf() )
	{
		GetSysExecutorThread().PostEvent( new SysExecEvent_InvokeCoreThreadMethod(&AppCoreThread::ChangeCdvdSource) );
		return;
	}

	CDVD_SourceType cdvdsrc( g_Conf->CdvdSource );
	if( cdvdsrc == CDVDsys_GetSourceType() ) return;

	// Fast change of the CDVD source only -- a Pause will suffice.

	ScopedCoreThreadPause paused_core;
	GetCorePlugins().Close( PluginId_CDVD );
	CDVDsys_ChangeSource( cdvdsrc );
	paused_core.AllowResume();

	// TODO: Add a listener for CDVDsource changes?  Or should we bother?
}`

**Comment by fldef** [comment]
How does SingStar normally do disc swapping? You start with one SingStar game then swap to another one?

**Comment by seta-san** [comment]
> How does SingStar normally do disc swapping? You start with one SingStar game then swap to another one?

There is an option in each of the games that will allow you to switch to a different singstar disc. It'll load the new songs with the interface you used to boot the ps2

**Comment by seta-san** [comment]
https://m.youtube.com/watch?v=OCiLoM4YSV4
