### ISSUE TITLE
Grand Theft Auto - Vice City Stories, Character Model Ghosting when Upscaled!

### ISSUE THREAD

**Issue by Kristijan1001** [PCSX2/pcsx2#3359]
***PCSX2 version:***
(v1.5.0 dev 3415)

***PCSX2 options:***
Upscaling the game causes the issue

***Plugins used:***
Same on everything that upscales as far as i am aware

***Description of the issue:***
Issue is there is slight ghosting on the character model

![pcsx2_4eBiaRd0wR](https://user-images.githubusercontent.com/24441639/81092007-48a89080-8f00-11ea-854e-5b690d5cdb8d.jpg)

![pcsx2_hMDxP7fIQc](https://user-images.githubusercontent.com/24441639/81092072-5bbb6080-8f00-11ea-8843-206422efb0c3.png)

***How to reproduce the issue:***
Upscale the Internal Resolution

***Last known version to work:***
None that i know of

***PC specifications:***
2070 Super, i9 9900k OS: Windows 10 64 Bit)

**Comment by lightningterror** [comment]
Originally PS2 games weren't meant to be upscaled so when users upscale them it can cause issues with many games, to alleviate the issues we have plenty of upscaling hacks to get around them. If you still experience upscaling issues then you will have to be patient and wait for future improvements.

This is a general issue and it will be closed as invalid.

**Comment by Kristijan1001** [comment]
> Originally PS2 games weren't meant to be upscaled so when users upscale them it can cause issues with many games, to alleviate the issues we have plenty of upscaling hacks to get around them. If you still experience upscaling issues then you will have to be patient and wait for future improvements.
> 
> This is a general issue and it will be closed as invalid.

Mind pointing me out to those upscale hacks. Which option would fix this kind of an issue ? I tried Texture offset, that just make it worse and makes the ghosting move more to the right. If you have an idea of what might fix it , would be apricated. Thank you.

**Comment by lightningterror** [comment]
Please use the forum for support related questions.
