### ISSUE TITLE
"Failed to create a 2.0 context" when using OpenGL

### ISSUE THREAD

**Issue by EmpirixDz** [PCSX2/pcsx2#3365]
PCSX2 1.6.0-20200506140834- compiled on May  6 2020
Savestate version: 0x9a0e0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 18363), 64-bit
	Physical RAM     =  16335 MB
	CPU name         =  AMD Ryzen 5 1500X Quad-Core Processor
	Vendor/Model     =  AuthenticAMD (stepping 01)
	CPU speed        =  3.850 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 7ed8320b
	x86EFlags        =  2fd3fbff

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	SSE4a 

Reserving memory for recompilers...

Loading plugins from Q:\PS2\pcsx2-v1.5.0-dev-2016-g201c9cd-windows-x86\plugins...
	Bound   GS: GSdx32-AVX2.dll [GSdx 20200506140834 (MSVC 19.25 AVX2/AVX2) 1.2.0]
	Bound  PAD: LilyPad.dll [LilyPad (20200506140834) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20200506140834 2.0.0]
(GameDB) 9858 games on record (loaded in 115ms)
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20200506140834 0.11.0]
	Bound  USB: nuvee_ps2_usb.dll [nuvee ps2 usb 0.2.0]
	Bound   FW: FWnull.dll [FWnull Driver 20200506140834 0.7.0]
	Bound DEV9: DEV9ghzdrk.dll [GiGaHeRz's DEV9 Driver 0.4.0]
Plugins loaded successfully.

HLE Notice: ELF does not have a path.

Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
Overriding 'Sys_RenderswitchToggle': assigning Page Up (instead of F9)
	Opening PAD
	Opening SPU2
	Opening CDVD
isoFile open ok: L:\PS2\Killzone (USA)\Killzone (USA).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (2257952 sectors)
	Opening USB
	Opening FW
	Opening DEV9
Failed to GetNetAdapter()
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
(pxActionEvent) GS plugin failed to open!(thread:MTGS)(thread:EE Core)
User-canceled plugin configuration after plugin initialization failure.  Plugins unloaded.

**Comment by lightningterror** [comment]
Can you better format the issue? Thanks.

**Comment by lightningterror** [comment]
Likely an old gpu or a bad driver, I will close this as it's likely invalid.
