### ISSUE TITLE
gta vice city stories 3d objects disappearing when flying

### ISSUE THREAD

**Issue by properchopsticks** [PCSX2/pcsx2#3368]
-PCSX2 version: pcsx2-v1.5.0-dev-3401-g49e316e48-windows-x86

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: [screenshot](https://cdn.discordapp.com/attachments/457543353131597855/704448286668619846/unknown.png)

-Plugin settings: Defaults, [screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708243788463865866/unknown.png). for emulation settings i'm using the default safe preset on all categories.

-Description: in gta vice city stories when flying around in a helicopter you can often see water and ground 3d objects disappearing in the distance. it's especially visible when looking from one island to the other but it also happens when looking around the same island.
i also made a couple of screenshots:
[screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708241427355664384/unknown.png)
[screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708241541562368070/unknown.png)
[screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708242058195763220/unknown.png)
[screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708242237880008734/unknown.png)
[screenshot](https://cdn.discordapp.com/attachments/457543353131597855/708242809576226821/unknown.png) 

-How to replicate: fly around with a plane/helicopter and look in the distance. i tested this on the pal version.

-Last known version to work: Never worked

-PC specifications:
cpu: intel core i5 7400 3,00 ghz
gpu: nvidia geforce 1050 ti 4 gb
ram: 32 gb ddr4
os: windows 10

Other comments: i'm not sure if this is an emulation or hack issue. if it's hack related let me know. i also disabled hw hacks but it didn't make any change.

thank you

**Comment by MrCK1** [comment]
Did you check it on the real console to make sure it isn't part of the game? Many games will hide objects in the distance to increase performance in areas like this.

**Comment by properchopsticks** [comment]
hi,

thanks for the reply. I couldn't test it on original hardware but i found a video of a let's play recorded on the original hardware and it does have some of the glitches but farther into the distance.

you can see it in this [video](https://youtu.be/nA6qA279dqE?t=130) starting at 2:10 and i made a couple of screen shots for comparison: [screenshot 1](https://cdn.discordapp.com/attachments/457543353131597855/708762129263755305/gta_vcs_1_261.png), [screenshot 2](https://cdn.discordapp.com/attachments/457543353131597855/708762135554949140/gta_vcs_2_508.png), [screenshot 3](https://cdn.discordapp.com/attachments/457543353131597855/708762144686211122/gta_vcs_3_542.png), [screenshot 4](https://cdn.discordapp.com/attachments/457543353131597855/708762149098618880/gta_vcs_3.2_574.png), [screenshot 5](https://cdn.discordapp.com/attachments/457543353131597855/708762151598161980/gta_vcs_4_581.png), [screenshot 6](https://cdn.discordapp.com/attachments/457543353131597855/708762152722497597/gta_vcs_6_806.png), [screenshot 7](https://cdn.discordapp.com/attachments/457543353131597855/708762154999742506/gta_vcs_7_889.png). i tried to follow the same path as in the video; it's not very visible from this angle but on the the top right corner you can see the water disappearing. in the later screenshots it's more visible.

this feels like there's some kind of graphics buffer that gets filled out and starts cutting down objects but i'm not sure. also i noticed that when first loading the game it's not as bad if you fly around. also it seems to be worse when flying around the golf course area, i think it's something to do with foliage but i'm not sure. hope this helps.

**Comment by properchopsticks** [comment]
hi,

can we remove the "waiting feedback" label? if there is anything else you need, let me know.

thanks

**Comment by MrCK1** [comment]
Doesn't look like anything wrong with the emulator to me, model fade out and short draw distances are both common traits of games from this era.
