### ISSUE TITLE
unable to find include file on fedora 32

### ISSUE THREAD

**Issue by lucag73** [PCSX2/pcsx2#3369]
***PCSX2 version:***
8bf6ba1440826a3c087b397a210db747cf905614

***Description of the issue:***
PCSX2 fails to compile on Fedora 32

***How to reproduce the issue:***
execute 
./build.sh --gtk3 --release
in the source directory

The compilation fails on fedora 32 when the file hb.h (part of harfbuzz) should have been included.

***Solution***
Add to CMakeLists.txt the path to hb.h ... namely the simplest solution has been to add

SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -I/usr/include/harfbuzz/")

this should be automatically discovered by cmake (but it does not work).

**Comment by lucag73** [comment]
Looking more carefully at the issue the include path is found by
cmake/FindHarfBuzz.cmake
and
 GTK2_HARFBUZZ_INCLUDE_DIR:PATH=/usr/include/harfbuzz
is set, but it appears it is not used if --gtk3 is selected.

**Comment by turtleli** [comment]
Try #3370.
