### ISSUE TITLE
Silent Hill 3 flashlight broken in SW rendering mode

### ISSUE THREAD

**Issue by HelicopterP** [PCSX2/pcsx2#3371]
***Plugins used:***
`Flashlight works fine in HW rendering modes, but broken in SW.

***Description of the issue:***
Halo around flashlight is displayed incorrectly. It's supposed to be round and transparent, instead it's displayed as a bunch of triangles.

***How to reproduce the issue:***
Start the game and skip all cutscenes.

***Last known version to work:***
v1.5.0-dev-3307-gb34338a50
--

***PC specifications:***
`i7 8700+GTX1070+Windows10

I bisected this issue with buildbot's builds and found out that v1.5.0-dev-3308-ge7d1a58a5 broke flashlight rendering in SW mode in Silent Hill 3. I don't understand how this is possible, because this commit seems unrelated to GSDX, but yet it did broke Silent Hill 3. 
v1.5.0-dev-3307-gb34338a50 works fine.
Hardware rendering modes work fine in both versions.

![gsdx_20200509205211](https://user-images.githubusercontent.com/4709459/81482130-6dbd3c00-923d-11ea-99ac-d0de13fec041.png)

[gsdx_20200509205211.zip](https://github.com/PCSX2/pcsx2/files/4604288/gsdx_20200509205211.zip)

**Comment by MrCK1** [comment]
What version were you testing on? This issue should be resolved in one of the recent 1.7 builds (https://github.com/PCSX2/pcsx2/commit/16431653e4d92fda4069031897e24fbe4688d36a)

**Comment by HelicopterP** [comment]
I'm using 1.6 release version from pcsx2 website. (I downloaded archived version, not installer).

**Comment by MrCK1** [comment]
Unfortunately that change won't be found in 1.6, it was merged after due to the possibility of breaking things.

**Comment by HelicopterP** [comment]
Yep, the last version from buildbot is fine.
It is a very strange decision for 1.6 release though. I'd imagine a lot of people downloading "stable" version and finding two of the definig PS2 games broken.

Oh, well... Anyway, this issue is fixed already that's what matters

**Comment by MrCK1** [comment]
Thanks for the response.
