### ISSUE TITLE
Castlevania - Curse of Darkness (Europe) (stays on black screen if the language is Spanish)

### ISSUE THREAD

**Issue by brujo5** [PCSX2/pcsx2#3374]
***PCSX2 version:***
stable build v1.4.0 and stable build v1.6.0

***PCSX2 options:***
default settings

***Plugins used:***
DX11

***Description of the issue:***
if i select spanish language and try to play a new game or load game, the game stays on black screen after the load screen but if i choose to play it in english the game works perfectly.

***How to reproduce the issue:***
just try to play with spanish language and start game

***PC specifications:***
 CPU: i5-8250U GPU: intel uhd 620 OS: Windows 10 64 Bit)``

**Comment by asp0909** [comment]
el problema lo debes tener tu en alguna parte, y doy fe de eso porque justamente lo e comenzado a jugar de echo, recomenzando varias veces la partida probando unos cheats

**Comment by brujo5** [comment]
thanks.
