### ISSUE TITLE
[Urban Reign] Black rain glitch in 480p mode

### ISSUE THREAD

**Issue by JackLupino** [PCSX2/pcsx2#3375]
PCSX version 1.6.0 (1.5.0 and 1.4.0 have that glitch too) Game Urban Reign NTSC (SLUS-21209 (BDD9BAAD)
In progressive scan mode in locations where it rains there is a glitch of black rain which is not in interlaced mode. For example, this is mission 26 "Fist to Fist" fight with Jake.
Please fix GSdx CRC hack for this game. It is Hardware Mode of course. Screenshots in native resolution 
https://i111.fastpic.ru/big/2020/0510/d2/dd3dad171a53f632a1bc9c2d299e59d2.png
https://i111.fastpic.ru/big/2020/0510/55/3da7f8b2d60259b14dec25453a782555.png
https://i111.fastpic.ru/big/2020/0510/c2/f8942564709b8c5e03fc84454fcd0bc2.png
https://i111.fastpic.ru/big/2020/0510/14/18f69219946a4d9c35553c69af243d14.png

**Comment by lightningterror** [comment]
Can you upload a gsdump?

**Comment by JackLupino** [comment]
[Urban Reign (Black Rain in 480p).zip](https://github.com/PCSX2/pcsx2/files/4611301/Urban.Reign.Black.Rain.in.480p.zip)

**Comment by lightningterror** [comment]
Can I have another dump from the same spot on normal mode?

**Comment by JackLupino** [comment]
> Can I have another dump from the same spot on normal mode?

Of course 
[UR Dump  normal mode.zip](https://github.com/PCSX2/pcsx2/files/4614209/UR.Dump.normal.mode.zip)

**Comment by lightningterror** [comment]
It is broken on normal mode too, stage seems darker as well. On normal mode we have a crc hack to remove dark stage draw, rain will remain broken tho. I will adjust the hack to work on progressive.

**Comment by JackLupino** [comment]
I use external gsdx shader with SCENE_TONEMAPPING ON he gives more dark but if turn it off black rain still present. Can you explain me what to do in details, i am not strong in english and the emulator itself((

**Comment by JackLupino** [comment]
Mission 15 "Fury" same problem
[dump.zip](https://github.com/PCSX2/pcsx2/files/4624299/dump.zip)

**Comment by Softernet** [comment]
> It is broken on normal mode too, stage seems darker as well, for the darker stage we have a crc hack in place to skip the draw.

Yes, your CRC hack fixed everything, including black rain in normal mode, but didn’t fix black rain in 480p, only fixed a darker scene.

**Comment by lightningterror** [comment]
The two dumps I have are from progressive mode, can I have one from the rain in normal instead?

**Comment by Softernet** [comment]
> The two dumps I have are from progressive mode, can I have one from the rain in normal instead?

Please take it. But in the GSDump player it looks strange, not like in the game and not like in the screenshot of the dump. It looks like in “normal mode” is still “black rain”, but it is not.
[Urban Reign (Rain in Nornal Mode).zip](https://github.com/PCSX2/pcsx2/files/4627908/Urban.Reign.Rain.in.Nornal.Mode.zip)

**Comment by JackLupino** [comment]
And from me in interlaced mode 
[Urban Reign Black Rain interlaced mode native.zip](https://github.com/PCSX2/pcsx2/files/4627938/Urban.Reign.Black.Rain.interlaced.mode.native.zip)

**Comment by JackLupino** [comment]
> Can I have another dump from the same spot on normal mode?

I am sorry i misunderstood you and uploaded 480p. In last message interlaced mode.

**Comment by prafullpcsx2** [comment]
Texture inside RT seems to fix this issue.

**Comment by kakashi314** [comment]
Gonna add this hardware glitch as well rather than opening a new thread

When you try to leave multiplayer, this will show up on hardware mode. Software is unaffected but the corruption will stay even if you switch to software


Software:

![image](https://user-images.githubusercontent.com/121500889/212747681-ce75c6b2-3961-4e0c-bbff-6d83e0a16c01.png)

Hardware:

![Urban Reign_SLUS-21209_20230116213955](https://user-images.githubusercontent.com/121500889/212747366-fe9b4488-8aa6-4d6d-b265-cdbe7d5996ca.png)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/10428597/snaps.zip)

**Comment by refractionpcsx2** [comment]
Fix was applied to the DB in #6686
