### ISSUE TITLE
Berserk rendering bugs - missing elements

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#3377]
***Info***

PCSX2 1.7.0-20200507203101 - compiled on May  7 2020
Savestate version: 0x9a0e0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 18363), 64-bit
	Physical RAM     =  32720 MB
	CPU name         =  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  4.007 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Reserving memory for recompilers...

Loading plugins from Z:\EMU\BIN\PCSX2\plugins...
	Bound   GS: GSdx32-AVX2.dll [GSdx 20200507203101 (MSVC 19.21 AVX2/AVX2) 1.2.0]
	Bound  PAD: LilyPad.dll [LilyPad (20200507203101) 0.12.1]
	Bound SPU2: Spu2-X.dll [SPU2-X 20200507203101 2.0.0]
	Bound CDVD: cdvdGigaherz.dll [cdvdGigaherz 20200507203101 0.11.0]
	Bound  USB: USBnull.dll [USBnull Driver 20200507203101 0.7.0]
	Bound   FW: FWnull.dll [FWnull Driver 20200507203101 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20200507203101 0.5.0]
Plugins loaded successfully.

(GameDB) 9859 games on record (loaded in 125ms)

***Description of the issue:***

- Software rendering OK.
- Hardware rendering missing elements.

***How to reproduce the issue:***

- Use HW rendering.
- Missing elements.

***Attachments:***

- [snaps.zip](https://github.com/PCSX2/pcsx2/files/4607331/snaps.zip)

**Comment by lightningterror** [comment]
The uploaded gsdumps are corrupt, can you try uploading multiframe dumps instead, less than a second is fine.

**Comment by dante3732** [comment]
Stiil not fixed, if use hardware with native resolution and preload data interface work fine, But if upscaled interface broken.

**Comment by felixthecat1970** [comment]
i manage to workaround/fix this bug (long standing "HW mode missing/corrupt gameplay 2d HUD") more or less explained, i dont know if open new issue with dumps required and values / functions documented for better fix  or document everything here?, some moderator can give a advice?

**Comment by tadanokojin** [comment]
You're more than welcome to document your findings here.

**Comment by felixthecat1970** [comment]
Berserk - Millennium Falcon Hen - Seima Senki no Shou (Japan) SLPM_656.88;1) Game CRC = 0x9685E636

Tested:
PCSX2 1.7 dev 1265
windows 10 20h2
ryzen 3400g 
vega 11
adrenaline 20.12.1 gpu driver

Options used:
Default options - OGL - DX11
"CRC hack level: Automatic\Debug"
"Blending accuracy: Default\Debug"

ISSUES: 
-HW Mode, movie subtitles missed (SW mode subtitles ok)
-HW Mode, gameplay 2d HUD menu missing or corrupted (with preload data option enabled) (SW mode 2d menu ok)
-SW and HW Mode, Game reset VER+ resolution defined 448 to 512 in main menu / videos when back from gameplay black bar below or not extended transparent overlay (PRTC bug?)

Description of the main issue:
in HW Mode 2d hud menu in gameplay is missing, using preload option enabled make appear but corrupted, sometimes correct position but bad colors or raw texture in left screen.

SW mode:
![b1](https://user-images.githubusercontent.com/12580269/119199288-6fc0fa00-ba50-11eb-9cc4-8af227acf83c.jpg)

HW Mode (default options)
![b2](https://user-images.githubusercontent.com/12580269/119199468-b7e01c80-ba50-11eb-9e7a-f099f8ba4e23.jpg)

HW Mode (preload frame data enabled)
![b3](https://user-images.githubusercontent.com/12580269/119199820-5cfaf500-ba51-11eb-9a71-f94c9e369c76.jpg)

Workarounds:
-Movie subtitles appear in HW mode when change GS priviliged register DISPFB2 from 00001080 /10C0 to 1000 (high res ps2  framebuffer?)
-Corrected Ver+ 512 to 448 when main menu / videos is accesed 
-Menu 2d : in gameplay game add new value to DISPFB2 "10c0" traced write function, indentify load value "1080 (80 val)" to another function test passed values 00, FF etc  making menu appear but image has afterimage when post-effects are used, trace  function and breakpoint main game events (movie,gameplay,) indentify original mips values and test +1 differential value for check post-effect influence and happend 2d looks ok HW and SW mode, traced remaining values created pnach file; original values and changed values here:

instruction load new val "10C0" to DISPFB2 in gameplay
00191C88 

Main function Parse store values in memory for above instruction
001B21B0 unknow function
001B21C8 instruction store values readed by next addresses

addresses                         // changed values
00246490 val 24050080 //81
0027E2D0 val 24050080 //81
0027DE30 val 24050080 //81

this code is not fully tested (3 main chapter scenario) a looks ok.
disclaimer: like always this is a lot of guessings how i see this mips coding nothing is granted or truth about it.

Meanwhile for people who want test this, i created a .pnach code for fix almost this issues in the game:
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=619908#pid619908

here is the GS / Blockdump / savestate dumps of game:
https://drive.google.com/file/d/1xiOhy7gzqtsr6o8APc7cpXAcVq3IOplC/view?usp=sharing

**Comment by tadanokojin** [comment]
Thanks felix, I'll review the information and get back with any insights I may have.

**Comment by tadanokojin** [comment]
@felixthecat1970 I took at look at the menus.

Information based on dump:
- 24 bit `Front Buffer A` is located at `0x1000` (`0x80` in DISPFB terms).
- Additional `Front Buffer B` is located at `0x1800` (`0xC0` in DISPFB terms). (triple buffering)
- `Back Buffer` located at `0x0` (also `0x0` for DISPFB)
- Menu mega texture overlaps front buffer at `0x1000` but uses the unused alpha bits (8H format).
- Causes a mess for the cache (thinks data is in GPU memory but really it's on the CPU, so black). 

It is as I expected and is a problem with a lot of Japanese games I've seen. Triple buffering but using the unused alpha channel of one of the front buffers to hide texture data. It's a smart move if you want to save memory.

Indeed the correct thing is to not use the troubled front buffer for now. Typically I move to the backbuffer though as this will usually give some additional benefits (reduced memory, progressive, reduced latency). Just need to change SMODE2 to compensate.

Patch is a good temp solution good job. We will work on a fix for the cache.

> Movie subtitles appear in HW mode when change GS priviliged register DISPFB2 from 00001080 /10C0 to 1000 (high res ps2 framebuffer?)

Based on this description subtitles are likely the same problem. You changed it to point to the back buffer as I suggested above. Just a guess but I say there is a text atlas hidden in the unused 8 bits of `0x1000`.

BTW just a tip, first 8 bits of DISPFB is the address in memory. Left shift it by 5 to get real address.

> Corrected Ver+ 512 to 448 when main menu / videos is accesed

GS has some not well understood behavior when display 512x512 in NTSC. Likely a PCRTC problem as you suggested.

**Comment by felixthecat1970** [comment]
nice, thanks explanation, now i understand more about "what i have made"  (still i dont understand a lot it :) ), also i did some experiments with this game and included in .pnach code i made in forums.

**Comment by MrCK1** [comment]
Game is fine on current master as of 1.7.4944. Not sure if there's any remaining issues

![image](https://github.com/PCSX2/pcsx2/assets/16314399/450923c5-1c6b-4476-8f1f-d8b051d28599)

**Comment by Mrlinkwii** [comment]
as @MrCK1  mentions the gs dumps seem fine ( as of v1.7.5243)
![image](https://github.com/PCSX2/pcsx2/assets/17685135/37319b6a-1b9e-4298-a857-7fafb8fc14f8)
