### ISSUE TITLE
Nitrobike Issues (Freezing and bad widescreen patch)

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#3378]
***PCSX2 version:***
1.6.0

***PCSX2 options:***
Safest

***Plugins used:***
GL Hardware/Software and D3D Hardware/Software
8x AF / Basic Mipmapping / Partial CRC / Fast DATE Accuracy / Basic Blending Accuracy
No Video Hacks

***Description of the issue:***
There are a couple issues with this game currently.

1) The widescreen patch for this game doesn't work correctly. When you hold down boost it will zoom out a very _very_ long distance and the camera will flip completely upside down/inside out. No issues with the patch disabled.

2) The game hangs after a random period of time. You can leave it on the title screen for a while or it will just happen randomly during a race. I tried with both hardware and software rendering on both GL and D3D, fast boot and full boot (the game will say "Loading...Japanese" on start without Full Boot, although it's still in English). The audio will continue to play, but the game just stops.

***How to reproduce the issue:***
1) Enable the widescreen patch, start a race, and hold down turbo (R2)

2) Let the game sit on the title screen for a while or just start a race and play for a while, it'll probably freeze before the race is over.

***Last known version to work:***
Unknown

***PC specifications:***
i7 4770k / GTX 780 / 32GB RAM / W7

**Comment by lightningterror** [comment]
Does it hang without the widescreen patch too?

**Comment by Zombeaver** [comment]
Yes, the hanging is separate from the widescreen patch.

**Comment by Zombeaver** [comment]
I tested 1.4.0 and 1.0.0 and it hangs in both.

**Comment by refractionpcsx2** [comment]
Well the freeze is fixed on master now so have fun with the latest dev build

**Comment by Zombeaver** [comment]
Oh, I see that! Thanks y'all!
