### ISSUE TITLE
GTK2 version of wxGTK is no longer packaged from Ubuntu Focal onwards

### ISSUE THREAD

**Issue by helkaluin** [PCSX2/pcsx2#3379]
Hi, I'm guilty of setting up the daily PPA at https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily. I've recently switched on building for Focal and Groovy, and was greeted with the unpleasant surprise that it seems only the GTK3 version of wxGTK is packaged.

GTK2: https://packages.ubuntu.com/eoan/libwxgtk3.0-dev
GTK3: https://packages.ubuntu.com/eoan/libwxgtk3.0-gtk3-dev

Is the GTK3 UI code mature yet? Can we add -DGTK3_API=TRUE to the Debian package files?

**Comment by helkaluin** [comment]
Relevant bug in Debian land (they've already switched): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933441

**Comment by turtleli** [comment]
The GTK3 UI should be as good as (or as bad as) the GTK2 UI.

I say go ahead.

**Comment by helkaluin** [comment]
Done on the PPA recipe scripts. I'll make a pull request here later. Thanks!

**Comment by tiagoplacido** [comment]
I noticed that the the package is not updating for 18.04, did you drop support for it

**Comment by RedDevilus** [comment]
There are some issues with 18.04 that it doesn't want to update it for some people. Its looked into why its doing that. Support is not dropped for it.

**Comment by helkaluin** [comment]
No no, I disabled the daily builds for Bionic because 5a5dc7f67f0b619541e6a144f0d1e333a3a5b4a9 broke the cmake process on Bionic. I'll re-enable and see if it's still like that. If so I'll open a bug.
