### ISSUE TITLE
Hitman Blood MOney SLUS_211.08;1

### ISSUE THREAD

**Issue by arshamatonyan** [PCSX2/pcsx2#338]
CORE:
Hitman Blood Money SLUS_211.08;1 experiences heavy FPS drop then during intro. 

-Last known version to work: Never worked
-Other comments: heavy frame-rate drop is observed on other titles as well then Streamed Video background is blended with Rendered Foreground e.g Matrix Path of Neo.
Doubt: video decoder performance issue. 
after emulator refuses to close , like some thread locked

Tested with:
        PCSX2 options: Defaults, no settings modifications affect the issue
        PCSX2 1.3.0-20141028103610 - compiled on Oct 28 2014
	Operating System =  Microsoft  (build 9200), 64-bit
	Physical RAM     =  8011 MB
	CPU name         =  Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
	CPU speed        =  1.795 ghz (4 logical threads)
	GS:GSdx32-AVX.dll 
	PAD: LilyPad.dll 
	SPU2: SPU2-X.dll 
	CDVD: CDVDnull.dll

**Comment by bositman** [comment]
Performance issues are not taken into account except if we're talking about 1 FPS. The processor looks weak and that would explain what you describe

**Comment by arshamatonyan** [comment]
the same is on 3.2 Ghz
core i7
i tested and the framerate drops to 5,4,3 fps. only during in game videos,
the gameplay itself if OK

**Comment by ramapcsx2** [comment]
There's going to be some kind of problem there. Did you try this in GSdx software rendering mode?
The issue could be with hardware rendering.

**Comment by arshamatonyan** [comment]
Yes I did try. The benefit is 1 or 2 fps not more. You may try it yourself
to ha e better picture. Cant help more as at this point I'm a user not
pcsx2 developer
Regards Arsham
