### ISSUE TITLE
Slow performances

### ISSUE THREAD

**Issue by faroukabd000** [PCSX2/pcsx2#3380]
Pcsx2  1.7.0 
The emulator really still slow in some os,
i tried dolphin and he is around 46fps bcz of the 64jit i think the slowness is related  to the pcsx2 32jit or something  else
If you need any feedback or screenshots am right here.
Be same pcsx2 team and others.

**Comment by lightningterror** [comment]
Please use the forum for support discussion.

**Comment by refractionpcsx2** [comment]
There will be no performance difference between 32 and 64bit JIT's.

Please make a post on the forum at https://forums.pcsx2.net and soembody will be able to help you

**Comment by faroukabd000** [comment]
Understood 🙆
