### ISSUE TITLE
Everblue 2 Edge Drawing Issues

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#3392]
***PCSX2 version:***
1.6.0

***PCSX2 options:***
Safest / I tried every single EE/IOP Round Mode and Clamping Mode setting and every VU Round Mode and Clamping Mode setting. I tried interpreter and superVU for both as well. I tried both with hardware rendering and software rendering, and the issue is present in all cases.

***Plugins used:***
D3D11 HW / SW and GL HW / SW

***Description of the issue:***
The game doesn't draw the edges of the screen/unloads the edges of the screen earlier than it should. This is not the result of the widescreen patch as the issue persists without it and is present even in software rendering. I started up the game on my real PS2 to make sure I wasn't just misremembering it, and confirmed that the issue is only present in PCSX2.

![Everblue 2](https://user-images.githubusercontent.com/24979172/82095784-c3766600-96cd-11ea-8276-10a18c119167.gif)

***How to reproduce the issue:***
Start the game, proceed through some dialogue between the two characters on the beach, then talk to the girl a couple times to start the first dive. Then just move the camera to the left and right.

***Last known version to work:***
Unknown

***PC specifications:***
i7 4770k / GTX 780 / 32GB RAM / W7 64-bit

**Comment by kozarovv** [comment]
You can use that patch, but only for EU version of game, i never ported US patch.
https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?pid=608112#pid608112

**Comment by Zombeaver** [comment]
That's interesting. Hopefully that will be useful in determining what the underlying issue is.

**Comment by Zombeaver** [comment]
I just tested it by using the same code and simply swapping the CRC and it worked! Thanks for that! Hopefully that'll be informative in fixing it "properly".

**Comment by MrCK1** [comment]
Just to clarify  - when you tested without the widescreen patch, was the game cold booted and not loaded from a savestate? 

I'm asking because patch data will persist in a savestate and/or patch data is not cleared unless the emulator is shutdown and rebooted.

**Comment by RedDevilus** [comment]
Prafull did ask me to add the NTSC and PAL to the GameDB so i assume it's cold booted.

**Comment by Zombeaver** [comment]
@MrCK1 @RedDevilus It was cold booted without the patch yes. I knew not to use a state in that scenario.

**Comment by Zombeaver** [comment]
I thought it might be worth mentioning here - there's a very similar issue in Grandia II when in combat. Also similarly to Everblue 2 it's not fixed by disabling the widescreen hack or by using software rendering. I don't know if the two are actually related, but the problem is aesthetically similar so I figured it might be worth pointing out.

![Grandia II (smaller)](https://user-images.githubusercontent.com/24979172/85235930-218e1b80-b3e7-11ea-83bd-3687074fdc4d.gif)

**Comment by tadanokojin** [comment]
It's over at #3258

**Comment by refractionpcsx2** [comment]
Everblue 2 is now fixed in master for both EU and US regions
