### ISSUE TITLE
Kingdom Hearts II - Final Mix (KH2FM) Z-Fighting(?)

### ISSUE THREAD

**Issue by sgern** [PCSX2/pcsx2#3394]
EDIT: Clarification
EDIT 2: Pictures

***PCSX2 version:***
``Development Build v1.7.0-111.``

***PCSX2 options:***
``Defaults (out-of-the-box fresh install). Worse with HW renderer, but seems to occur in SW to a lesser extent.``

***Plugins used:***
``Defaults.``

***Description of the issue:***
``The mansion in Twilight Town at the beginning of the game, where the first fight against the Dusk is, has what I believe are z-fighting issues. As the camera moves, the textures for the mansion's walls flicker over its windows. It's visible when walking around the area, but most noticeable in the cutscene immediately preceding the fight.``

![kh2fm mansion 1](https://user-images.githubusercontent.com/10506126/86502544-6d8b7980-bd72-11ea-80c8-9a8012756191.png)

![kh2fm mansion 2](https://user-images.githubusercontent.com/10506126/86502545-73815a80-bd72-11ea-9e60-c1ff4762fcf8.png)

![kh2fm mansion 3](https://user-images.githubusercontent.com/10506126/86502551-78460e80-bd72-11ea-90c3-36acf71dd8e2.png)

***How to reproduce the issue:***
``Play the game as normal until you reach the first Dusk fight, then watch the mansion.``

***Last known version to work:***
``Unknown, but the issue is also present in Stable Build v1.6.0.``

***PC specifications:***
``CPU: Intel i7-7700HQ``

``GPU: GTX 1070 Mobile``

``OS: Windows 10 64 Bit``

**Comment by Nicholas-Steel** [comment]
Also happens inside the mansion.

* Stand on the ground floor of the lobby near the door on the left (when facing away from the main Mansion entrance).
* Look towards the space between the 2 staircases.
* The shadow on the wall of the farthest staircase will flicker as the camera moves.
