### ISSUE TITLE
DPI awareness

### ISSUE THREAD

**Issue by BenMcLean** [PCSX2/pcsx2#3395]
***PCSX2 version:***
PCSX2 1.6.0-20200506140834- compiled on May  6 2020

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***
On higher DPI settings on Windows that some visually impaired people need to get larger print text, the "Emulation Settings" dialog is rendered way too huge, so that it goes off screen and some options can't be accessed. This remains true at both 1080p and 720p resolution and there's no workaround by changing DPI settings on the executable.

Windows apps need to be DPI-aware, as discussed in this article from Microsoft. https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx

***How to reproduce the issue:***
Set DPI to 150% and then try running PCSX2 and opening the Emulation Settings dialog.

***Last known version to work:***
Never worked.

***PC specifications:***
Any Windows with high DPI setting.

**Comment by lightningterror** [comment]
Some images would be nice.

**Comment by MrCK1** [comment]
Closing since this has been addressed in Qt and WX will be dropped eventually
