### ISSUE TITLE
Legacy of Kain: Soul Reaver 2 [SLES-50196]

### ISSUE THREAD

**Issue by BroKill** [PCSX2/pcsx2#3404]
***PCSX2 version:***
v1.6 and v1.7 dev

***PCSX2 options:***
Any

***Plugins used:***
Default

***Description of the issue:***
Hello , I have a problem playing this game on PCSX2. It freezes at cutscenes randomly and can't find a permanent solution.
I googled the problem and I found a video on YouTube https://www.youtube.com/watch?v=fCXixJg0zQ8 where the user says to disable the MTVU (Multi-Threaded microVU1) and all Speedhack and also never use the Turbo Mode.
That guy plays the game on PCSX2 without problem and I copied his settings but it doesn't work permanently, it stucks at next cutscene and it's very irritating.
Do you guys know a fix for that?

***How to reproduce the issue:***
Play the game and wait cutscenes, sooner or later it will freeezes/stucks.

***Last known version to work:***
Dunno, never played on PCSX2 until some days ago.

***PC specifications:***
i7 4790k
GTX 770 2Gb
16Gb DDR RAM
WiN10 1909

Thanks in advance

CHEERs

**Comment by RedDevilus** [comment]
Upscaling to 8x will not help you with those specs it can only go max to 4x on that. Try lowering it to atleast that or even better do it natively first.

**Comment by lightningterror** [comment]
> Upscaling to 8x will not help you with those specs it can only go max to 4x on that. Try lowering it to atleast that or even better do it natively first.

Can we stay on topic maybe?

Anyway OP it is a known issue.
https://forums.pcsx2.net/Thread-SPU2-X-Bug-Report-Legacy-of-Kain-Soul-Reaver-2-PAL

**Comment by BroKill** [comment]
I did a test lowering resolution to Native and then I unchecked something as in the screenshot : https://i.imgur.com/oAzqMx3.jpg

I was able to paly it until first saving in game without freeze and stuck, really nice!

If I will get a new freeze or stuck I will report here.

Thanks a lot guys for all your wonderful work!


CHEERs

**Comment by BroKill** [comment]
Ok guys,

after several test I found the real problem.
Here the freeze/stuck come out with Anisotropic Filtering active in the OpenGL Hardware settings with Large Framebuffer and Allow 8-bit Textures both active. 
It's not a matter of upscaling because I set the Internal Resolution to 2x ( 720p ) and it works good.
Settings I'm using to play it with no problem ( tested about 10 times until the first save in game and no freeze/stuck occured ) : 

- Everything you put in the Emulation Settings can't cause the freeze/stuck so you can set what you want ( here Turbo Mode is active and MTVU and all Speedhack are active too ).
- Render : OpenGL HW ( see the screenshot )
https://i.imgur.com/yS03IGT.jpg

With these settings I have no problem anymore.
Please, spread the word in the official PCSX2 Forum so even other users can play it with no problem.

Thanks again for your work, keep it alive!

CHEERs

**Comment by eldervamp** [comment]
I'm still getting freezing at cut-scenes even with suggested options. Only way for me to get pass it is by doing a save state before the scene and just keep reloading save state until I get pass it. But main bug is shifting back from spectral realm to physical realm. The audio get corrupted. No voice audio, just echo sounds, popping. It a 50/50 chance every time you shift back and forth this will happened and your constantly shifting throughout the entire game play. I tried v1.6 and 1.7 and get the same results. Other have reported audio issues too. https://forums.pcsx2.net/Thread-SPU2-X-Bug-Report-Legacy-of-Kain-Soul-Reaver-2-PAL?pid=605364#pid605364

**Comment by refractionpcsx2** [comment]
Just to note this has now been fixed in master
