### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by Danilopereira82** [PCSX2/pcsx2#3413]
XD

**Comment by DragonautMk** [comment]
Can you try different video renders?

**Comment by Danilopereira82** [comment]
Only OpenGL

**Comment by Ryudo300** [comment]
MTVU speedhack will cause Gradius V to boot, disable it. 

I don't have the other games to try, so you'll have to test that yourself.

**Comment by Danilopereira82** [comment]
every configuration is default here
no MTVU hack being used

**Comment by lightningterror** [comment]
Regarding GOW or Blood will tell, can you post the emulog, anything unusual?

**Comment by Danilopereira82** [comment]
i just got a nice CRT TV and a real ps2
i don't need this emulator anymore
![wYHlCW](https://user-images.githubusercontent.com/20802412/85630062-899c6600-b662-11ea-8add-532bc8ea927d.png)

**Comment by refractionpcsx2** [comment]
@Danilopereira82 can you please refrain from shitposting on our github, thanks.

**Comment by refractionpcsx2** [comment]
Alright, if you're just gonna be a dick, I'll just close this.
