### ISSUE TITLE
Super robot taisen alpha2&3 Filter issues

### ISSUE THREAD

**Issue by srw20166** [PCSX2/pcsx2#3415]
stable build v1.6.0 OGL HW 3X Native
I using Bilinear(Forced excluding sprite) 
In game battle animation start robot body was blurred. 
image is Super robot taisen alpha3 
Super robot taisen alpha2 same issue.
![1](https://user-images.githubusercontent.com/65796804/82719655-245df980-9cdf-11ea-9192-7d35f77e430d.JPG)
![2](https://user-images.githubusercontent.com/65796804/82719656-258f2680-9cdf-11ea-811b-7478fefa26ff.jpg)
![3](https://user-images.githubusercontent.com/65796804/82719658-26c05380-9cdf-11ea-9ae3-c464cff5c249.jpg)

**Comment by MrCK1** [comment]
Please try again with native resolution and also post results of software mode with both texture filtering modes.

**Comment by srw20166** [comment]
Robot body edge is smooth but overall game screen is blurred 
native resolution+ software mode
![1](https://user-images.githubusercontent.com/65796804/82978944-6311ed80-a018-11ea-935a-c0ca30b313d0.jpg)

**Comment by srw20166** [comment]
> Please try again with native resolution and also post results of software mode with both texture filtering modes.



> Please try again with native resolution and also post results of software mode with both texture filtering modes.

**Comment by srw20166** [comment]
> Please try again with native resolution and also post results of software mode with both texture filtering modes.

I post results of Bilinear(Forced) Robot body edge is smooth but screen have black line .
![2](https://user-images.githubusercontent.com/65796804/83423010-f43ff480-a45c-11ea-8998-67bd249b971d.jpg)

Best performance is Bilinear(Forced excluding sprite) and robot edge have Mosaic
So I expect smooth Robot body edge on Bilinear(Forced excluding sprite) mode.

**Comment by MrCK1** [comment]
I'm going to close this as it doesn't appear to be a valid issue. Upscaling and other texture filtering modes besides Bilinear(PS2) will cause issues/gaps with sprites as shown above.

**Comment by superrobotwar** [comment]
Hi, any update? I have the same issue. And shader helps to improve the graphic. Finding out any other solution?

**Comment by srw20166** [comment]
> Hi, any update? I have the same issue. And shader helps to improve the graphic. Finding out any other solution?

There is no perfect solution ,Finally I using Bilinear(Forced excluding sprite),3D11,6X Native, That is my best setting.
