### ISSUE TITLE
[Feature request] Simultaneously 2 btn press for one btn emulation (Lilypad)

### ISSUE THREAD

**Issue by Cyberavater** [PCSX2/pcsx2#3422]
Seems like my previous request was misunderstood as I was not as asking for support question rather asking for a feature request.

In many games Using 2 btn press for one ps2 btn feature would be very useful (which is not available in current version Lilypad version: 0.12.1).
ie:
L-Stick Up: W
D-Pad Up: Shift+W(Simultaneously) [This will NOT trigger L-Stick Up]

[This is NOT a support question! Rather it's a feature request!]

**Comment by RedDevilus** [comment]
Basically combo press but register as single one. I wonder if thats feasible.

**Comment by Cyberavater** [comment]
I think it's feasible, as there is already "OR" logic available (in current lilypad) for 2 keyboard btns, Adding a feature with "AND" logic should be able to implement this feature. But sadly I'm no coder.

**Comment by refractionpcsx2** [comment]
We now have macro's so this is considered done
