### ISSUE TITLE
Is it possible to block maximizing of window of PCSX2 by left mouse button double-clicking?

### ISSUE THREAD

**Issue by Qwest8K** [PCSX2/pcsx2#3427]
In group of Windows OS families.

Because I assigned one of the gamepad buttons on left mouse button - specifically for playing in shooters. And therefore it is very uncomfortable to use a weapon that requires a quick pressing of a button (like pistols) - PCSX2 flickerly switches between true full screen and full-screen window.

**Comment by Dreadmoth** [comment]
**Config → Emulation Settings → GS Window → Double-click toggles fullscreen mode** (uncheck)

**Comment by RedPanda4552** [comment]
The above configuration option will do this. Closing issue.

For support requests, please use our forums first: https://forums.pcsx2.net/
