### ISSUE TITLE
[Onimusha 3] [NTSC] Certain shadow effects don't appear in hardware mode

### ISSUE THREAD

**Issue by PolygonSlayer** [PCSX2/pcsx2#3429]
**PCSX2 version:** v1.7.0-dev-18-g5a5dc7f67

PCSX2 options:
Shadow issues occur in hardware mode regardless of any options I tried. In software mode the shadows always appear correctly.

***Description of the issue:***
The game seem to be using at least a couple of ways to create shadows. One method where it's more like "blobs" below the character seem to work fine and this is the shadows that most enemies will use as well as certain scene with the playable characters. However, in some places more advanced shadows (I presume shadow maps) are used and in hardware mode these do not seem to appear at all.
Screenshots attached show one example of the "blob shadow" (a bit hard to see, but it's there and easier to see in motion) and one example where the shadow maps are used. Screenshot examples show both hardware and software:

Blob shadows (these work fine):
![20200529231537](https://user-images.githubusercontent.com/44800819/83310242-4685d900-a203-11ea-9bd3-ad4de653b00b.jpg)
![20200529231542](https://user-images.githubusercontent.com/44800819/83310245-47b70600-a203-11ea-849b-0e92821d7799.jpg)

Shadow maps (are broken in hardware):
![20200529231610](https://user-images.githubusercontent.com/44800819/83310283-63baa780-a203-11ea-87d8-d3cf8b1ac546.jpg)
![20200529231614](https://user-images.githubusercontent.com/44800819/83310285-64533e00-a203-11ea-9b4d-f10bb7c42ec5.jpg)

***How to reproduce the issue:***
The shadows can easily be observed early on in the game. I've highlighted that the game uses two types of shadows in case one see the blob type shadow an assume they all work fine.

**Comment by lightningterror** [comment]
Can you upload a gsdump?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by PolygonSlayer** [comment]
![Onimusha3_NTSC_missingShadowBug](https://user-images.githubusercontent.com/44800819/83310952-9b2a5380-a205-11ea-9ef5-22a28aee9ec2.png)

**Comment by PolygonSlayer** [comment]
I closed it by accident, reopened and attached the gsdump:

[Onimusha3_NTSC_missingShadowBug.zip](https://github.com/PCSX2/pcsx2/files/4704670/Onimusha3_NTSC_missingShadowBug.zip)

**Comment by lightningterror** [comment]
There is a crc hack in place that skips the shadows. Can you set crc hack level to none in gsdx settings and test out the game? If there are no issues I will remove the crc hack that skips the shadows.

**Comment by PolygonSlayer** [comment]
Setting the CRC hack level to none fixes the shadows it seems :)
![Onimusha3_NTSC_noCRCfixesShadows](https://user-images.githubusercontent.com/44800819/83312740-573a4d00-a20b-11ea-9a43-e8b35e5f6cc7.png)

**Comment by lightningterror** [comment]
Yes but I want some longer testing to make sure nothing else got broken.

**Comment by PolygonSlayer** [comment]
That's cool. I'm currently playing through the game so I will try and play with CRC hacks set to none and keep an eye out for anything, then try setting it to Auto etc. to see if it fixes it. Will post here my findings once I've finished the game :)

**Comment by PolygonSlayer** [comment]
Quick update as I've been playing for a few hours now with CRC turned to none and noted down some issues and differences I've found:

1. I found that even though turning CRC off there are still a handful of areas where shadows are not appearing. These almost look like another type of shadow again and not simple shadow maps.
2. There is a very small issue with the left hand side showing some transparent, barely visible artifacts during some ingame cutscenes. Super minor.
3. Some ingame cutscenes do suffer some performance when CRC is turned off. This can cause the audio to de-sync. Switching to software fixes it.
4. I replayed some of the parts from before and I noticed some new effects during a boss fight that were not there before. There is a monster that has a glow effect on it's exposed brain (not present with CRC on), and also when it flies it uses a blur/jet engine type effect that was not visible before either. I can see why these would be turned off with CRCs though since when they trigger the framerate does take quite a big hit.
5. There is a glow ghost effect later on during a cutscene that is way overpowered (too bright) when CRC is off, and with CRC on it is to weak. Software shows the glow effect as it is supposed to.
6. The is a refractive/water type effect used on both water puddles and some "blob" translucent monsters that is missing when CRC is turned on. This effect is present when it is off however with no performance penalty as far as I could see.
7. There is a city area later in the game where you can talk to civilians and explore. It's a heavier scene and with CRC turned off this does drop the performance ever so slightly.
..and that's as far as I've gotten so far. :)

I have taken as many gsdumps as I could during this so let me know if you want me to throw them in here or someplace else/new bug?
Specifically for this bug however, I've attached now the gsdumps of the "new" shadows issue I found here:
[Onimusha3_NTSC_ShadowsMissing_new.zip](https://github.com/PCSX2/pcsx2/files/4706062/Onimusha3_NTSC_ShadowsMissing_new.zip)


I'm not sure what exactly what else the CRC hacks might be disabling. Is there a list or a way for me to check? Overall though the game is perfectly playable with CRC set to none, only one part I found so far was that one boss fight with the effects that caused some bigger slow down and the cutscenes.

Also worth noting that the bug on the wiki page that mentions the keypad lock in the sewer not showing the numbers. I was not able to repro this bug, any settings I tried always showed the numbers just fine.

Let me know if this is useful at all and yeah, if you need the other gsdumps just give me a shout :)

**Comment by lightningterror** [comment]
Dump 2 and 3 are corrupted so I will need new ones, also

> There is a monster that has a glow effect on it's exposed brain (not present with CRC on), and also when it flies it uses a blur/jet engine type effect that was not visible before either. I can see why these would be turned off with CRCs though since when they trigger the framerate does take quite a big hit.

A dump from this section would be nice.

**Comment by PolygonSlayer** [comment]
That's weird. I can grab new ones once I finished the game. There were areas fairly early on that I can replay to get those dumps (don't have saves from there anymore). Also that boss fight is fairly early on so I can get dumps of that as well since I didn't get dumps of that one.
I think I'm about 60-70% done with the game now so shouldn't be too long :)
Overall though there are minimal problems with CRC off, only a few more minor things I noticed that I'll post here once I'm done, and some of those might even be fixable with some tweaks, I've not tried it to fiddle too much since I'm also just trying to play the game :)

**Comment by PolygonSlayer** [comment]
So I've finished the game and this is a summary of the issues I found:
1. Certain types of shadows still don't appear with CRC off (new dump attached).
2. Some cut scenes have a very minor transparent artifact on the left hand side of the screen.
3. Some cut scenes slow down a bit, although this does seem be mainly the beginning of the game. I found later cut scenes to run fine.
4. The issue with the effects and the boss I was not able to repro myself in fact I even had the blur/jet effect. However, the brain glow was still missing. It's a very odd one, maybe it was just that session? or a mixture of me messing with settings?
5. Some glow effects across the game are too overpowering. The ghost scene mentioned above as well as during the end cut scene the glow is super overpowering. (Got dump of this)
6. The water/refractive issue mentioned above is present across the game. Not gameplay breaking, but visually inferior. Turning CRC off fixes this issue as mentioned. (Got dump of this)
7. The city area did have some slow down as mentioned before, but it was minor and the section was not very long. Probably is more my PC than anything.
8. In hardware mode there are some areas where textures are flickering. Minor, but noticeable. (Got dump of this)
9. A couple of areas in the game has some odd white outline that "slides" across the environment in hardware mode. (Got dump of this)
10. In one room of the game here is a black box overlapping everything (even the UI) in the top left corner. Really bizarre one and only appear in this one location. (Got dump of this)
11. There is a castle section/level of the that has very broken green filter across the environment. This also happens during the end boss. Switching to software fixes it. (Got dump of both of these occurances)
12. There is a short section where there is a full screen effect which seems to cause quite severe slowdowns. Playing in hardware mode speeds it up to playable levels, but software is very slow. (Got dump of this)

Should I split any of these into a new bug report?

Attached redump of the shadow bug:
[Onimusha3_NTSC_shadowsMissing_newdump1.zip](https://github.com/PCSX2/pcsx2/files/4719446/Onimusha3_NTSC_shadowsMissing_newdump1.zip)
