### ISSUE TITLE
EyeToy Play(1-3) - the video sent by the USB plugin isn't shown

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#3432]
***PCSX2 version:***
* v1.7.0-dev-60-g802318399

***PCSX2 options:***
* default

***Plugins used:***
- USBqemu-wheel-0.10.0 : https://github.com/jackun/USBqemu-wheel/releases/

***Description of the issue:***
The attached plugin emulates an EyeToy. The following games works:
```
Bob the Builder
Clumsy Shumsy
EyeToy - Kinetic
EyeToy - Kinetic Combat
Nickelodeon SpongeBob SquarePants - Movin' with Friends
Sega Superstars
```
but `EyeToyPlay(1-3)` doesn't. Observation which may be or not related : PCSX2 shows `IPU1 running when IPU1 DMA disabled! CHCR 1 QWC 126`. 

![snap4](https://user-images.githubusercontent.com/2995486/83352324-4d236600-a353-11ea-9be6-c7739251b315.png)

***How to reproduce the issue:***
* Install USBqemu-wheel-0.10.0, configure it to emulate an EyeToy and load EyeToyPlay(1)

**Comment by Florin9doi** [comment]
Nobody? 😞 The EyeToy plugin is ready

**Comment by prafullpcsx2** [comment]
That IPU error is common on many games and so far no solution has been found.

**Comment by MrCK1** [comment]
If there are no on-screen artifacts with the error, then this can be closed. As prafull said, it's very common to see.

**Comment by Florin9doi** [comment]
artefacts? the decoder fails on the spot

**Comment by Florin9doi** [comment]
the ticket was updated to reflect the progress

**Comment by seta-san** [comment]
i'm trying to use the eyetoy functionality on Karaoke Revolution and it gives
IPU1 running when IPU1 DMA disabled! CHCR 1 QWC 227

**Comment by seta-san** [comment]
@Florin9doi Eyetoy Play 1 USA comes with debug symbols if that's helpful

**Comment by seta-san** [comment]
@turtleli i understand that you are an IPU master. would you mind taking a look at this?

**Comment by turtleli** [comment]
I'm not an IPU master. I know almost nothing about it.

**Comment by seta-san** [comment]
> I'm not an IPU master. I know almost nothing about it.

damn. RedDevilus lied to me.

**Comment by Florin9doi** [comment]
@seta-san had the idea to patch EyeToy1 to use ipu_decompressRGB instead of ipu_decompressYCrCb and the game finally displays something : 
```
Serial = SCES-51513
[patches = C0FCD1CE]
	// replace decompressYCrCb with decompressRGB
	patch=0,EE,0015cc80,word,16620033
[/patches]
```
The color issue is expected considering that it uses an incorrect function to decode the frames.
My observations are that:
1. "IPU1 running when IPU1 DMA disabled" isn't observed while the patch is applied.
2. ipu_decompressRGB function is 3 times shorter than ipu_decompressYCrCb : 0x1A8 bytes vs 0x4F4 bytes
3. ipu_decompressRGB contains a single sceIpuSync call, but ipu_decompressYCrCb contains 6 sceIpuSync calls
4. GameIndex.dbf contains a few sceIpuSync patches; sceIpuSync isn't properly emulated??

**Comment by Florin9doi** [comment]
The idea is that ipu_decompressRGB is shorter and it works, unfortunately we need ipu_decompressYCrCb  which is more complex and it fails

**Comment by Florin9doi** [comment]
https://wiki.mariocube.com/index.php/EyeToy
