### ISSUE TITLE
Shadow Hearts: Covenant  - Judgement Ring In HW Rendering

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#3437]
***PCSX2 version:***
1.6.0

***PCSX2 options:***
I've tried all EE/IOP and VU options, OPH Flag Hack, and all HW video hacks. Speedhacks on and off. No change.

***Plugins used:***
GL HW and D3D HW

***Description of the issue:***
I think this is fairly well-known, but I didn't see any existing issues for it.

No issues in software renderers, but in hardware renderers, the judgement ring (the timing-based input part of attacking in combat) will make the entire background turn black while it's on screen. What it's _supposed_ to do is to freeze frame the scene (you can tell that it's basically taking a screenshot because the resolution is lower than normal with upscaling). In prior versions of PCSX2 it used to make about half the screen black, and half of it frozen, in more recent versions it makes the entire background black. The particularly strange part is that it doesn't happen every time, sometimes it does exactly what it's supposed to do. You can use a savestate, start an attack, and sometimes you'll get black, load the state, wait a different amount of time before attacking, and sometimes it'll display correctly. Then, when you attack with a different character, sometimes it'll be black and sometimes it'll show a frozen frame from when the _previous_ character attacked.

The same attack is in both frames below. Hardware rendering in both. It worked correctly, loaded the state, displayed black. Sometimes it'll work, sometimes it won't.

![image](https://user-images.githubusercontent.com/24979172/83702403-9fc28380-a5da-11ea-8549-7eed065b01b2.png)

![image](https://user-images.githubusercontent.com/24979172/83702463-c680ba00-a5da-11ea-98ec-5c394263e8dc.png)

***How to reproduce the issue:***
Use either hardware renderer, get into combat, and start an attack.

***Last known version to work:***
None

***PC specifications:***
i7 4770k / 32GB RAM / GTX 780 / W7 64

**Comment by lightningterror** [comment]
A gsdump will be nice of the issue.

**Comment by Zombeaver** [comment]
Sure, no problem. Here are dumps with a couple seconds of gameplay where [it works correctly](https://drive.google.com/file/d/1PmOZyFQgqmDQXZ4CJV4h-MfnQiQv0BpO/view?usp=sharing), where it [doesn't work correctly](https://drive.google.com/file/d/1c0XBPK11oaUxzecJBXziP0ip9qANcRmV/view?usp=sharing), and a [single frame of it not working correctly](https://drive.google.com/file/d/1K_lfhcyzlPNU3WdcqZA_9O9kEiTKUT5c/view?usp=sharing).

**Comment by divineal** [comment]
did they ever solve this?

**Comment by ISuckGood** [comment]
still open ?

**Comment by RedDevilus** [comment]
It's closed when it's fixed, open when it's still an issue.

**Comment by furopi** [comment]
Will this glich be fixed? Thank you!

**Comment by Mrlinkwii** [comment]
can  new GS dump be made of the  issue  preferably on master  the GS dumps links  in the above comment are dead :slightly_smiling_face:

**Comment by Zombeaver** [comment]
Links are still working here, but yes I can.

**Comment by MistressAshai** [comment]
Those links send me to an access denied page.

**Comment by stenzek** [comment]
If it's doing a GS download, the dumps won't help much, since the bad re-upload will get baked in. I guess you could watch for the RB stat in the OSD, but it might be difficult to catch if it's only a single download.

**Comment by Chetyre** [comment]
[Not OP, but here are 2 GS dumps showing the above using OpenGL](https://mega.nz/folder/2ptyFbIK#h7yTDnvaaoKedSGTwG6CzA).  One working and one taken a few seconds later that had the error.  This is using the latest nightly build (1.7.3284).  These were both taken during a demo video that plays on the title screen and it's very easy to reproduce, so if a multiple frame dump would help I can capture that.  I am not familiar at with the terminology or lingo, but I noticed when I turned on OSD stats for display I saw that RB stat briefly go to 1 on times when the judgement ring worked, and stayed as 0 on times when the screen went to black background.

**Comment by furopi** [comment]
Wow I can't believe the issue is finally solved! Thank so much for the hard work and congrats to the devs! ❤️❤️❤️

**Comment by A7manDC** [comment]
Just updated PCSX2 and the glitch is back. The game look lees colorful as well.

**Comment by refractionpcsx2** [comment]
it's back?? What the hell... I tested it...

**Comment by refractionpcsx2** [comment]
It looks fine here??

![image](https://user-images.githubusercontent.com/6278726/226171399-06d6f951-e000-4f49-a507-e738b748641a.png)

is it only at a certain point it starts breaking? if so I'll need a savestate.

**Comment by refractionpcsx2** [comment]
As for the "Less colourful", can you substantiate this? Comparison with the old version and software mode?

**Comment by Fothsid** [comment]
Can't replicate the issue on 1.7.4949. Can you explain where, when and how it is triggered?

**Comment by Fothsid** [comment]
Okay, it happens in From The New World. but not in Covenant.

**Comment by refractionpcsx2** [comment]
Should be resolved now in v1.7.4254

**Comment by Cikatriz87** [comment]
> Should be resolved now in v1.7.4254

The issue is still present. Using V1.7.5660. Steam Deck

**Comment by Loopin1** [comment]
The only way I could avoid this problem was by setting the Graphics Configuration to Software Renderer. The image quality is lower than in the other options, but it is better for playing without errors. All the others presented the error.
![Captura de tela 2024-08-04 215522](https://github.com/user-attachments/assets/0432e043-75a4-4edf-bf86-6ab63b220da8)

**Comment by Loopin1** [comment]
It's perfect in this version
![Captura de tela 2024-08-04 223807](https://github.com/user-attachments/assets/e693e252-0a04-4900-bdf9-7bc3f34e88bd)
