### ISSUE TITLE
Weird bug with hotkeys not working on a condition

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#3438]
1.CDVD mode doesn't matter but lets set it to No Disc
2.Run any elf file(ulauchELF for example)
3.Try running any elf file again(it can be the same)but without closing the game window first
4.When the window automatically closes and appear again(and become active),all of the hotkeys stop working until you make the game window not active and activate it again

**Comment by RedPanda4552** [comment]
Potentially silly question. Is this limited to just the Run ELF option? No effect on Boot Fast or Boot Full?

**Comment by MrCK1** [comment]
@vsub can you retest this on latest master?

**Comment by vsub** [comment]
@MrCK1 sadly,no change
v1.7.0-dev-765

1.Run an elf
2.F4 works fine
3.Run an elf again without closing the game window
4.F4 does nothing until I make the game window not active and activate it again

Win10

**Comment by RedDevilus** [comment]
I can trigger it on older builds but not on the latest 1.7 dev builds - assumed fixed. Re-open if needed.
