### ISSUE TITLE
Fatal Character Displacement and Translucent Terrain compromise (Treasure Planet)

### ISSUE THREAD

**Issue by Flintastic** [PCSX2/pcsx2#3441]
**PCSX2 version:** PCSX2 1.7.0-20200605205616 - Jun 5 2020

**PCSX2 options:**

- EE Round Mode = "Positive".

- Automatic Gamefixes must be turned off for this setting to be modified as the DBF already has a reservation for it. All other settings may be default.

**Plugins used:** GSdx, SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

**Plugin settings:** Defaults, no settings modifications affect the issue.

**Description:**

An issue that has plagued this title since it began booting is a severe logic (EE) error in which the player character is endlessly displaced (translated) in a seemingly random direction as quickly as the hardware can process it, ignoring collision checks in most cases, resulting in dead play sessions and other adverse effects.

- The issue is triggered when the player character is moved, then comes to a full stop.

- The displacement never occurs if the player never stops moving.

- The character usually travels vertically upwards or horizontally, bypassing any terrain. When this happens, the camera immediately and abruptly orients itself to an awkward viewing angle and tries to catch up endlessly; level terrain continues to load as the camera hopelessly travels at its normal pace.

- Rarely, a "slower" displacement may occur, in which the character can be visibly observed to slide or glide across long horizontal distances very quickly, but comes to a stop very soon after. Collision works in this case. This is usually followed by a "full speed" displacement immediately after.

- Very rarely, the character may be displaced downwards, triggering the level's death-plane, which counts as a death. The character appears to suddenly disappear when this occurs. Camera does not move (as scripted in the game's code when player dies).

- Very extra rarely, the character may just spontaneously die. Health drops to zero. Death animation and sound clip. The character glides slowly for a short distance as this happens.

This issue was falsely reported to be fixed years ago by setting the **EE Round Mode** to "**Nearest**" as it presently is in the DBF, indicating that this game was not tested for more than two minutes of play.

The difference between "**Nearest**" and the default "**Chop/ Zero**" is that the displacement occurs less frequently as opposed to a 100% chance, which is still often enough to occur within zero to ten minutes of play.

Sometimes it happens immediately, sometimes you'll have to play for a few minutes to see it. Nevertheless, it is inevitable.

The only option that permanently fixes the displacement issue is setting the **EE Round Mode** to "**Positive**", however this has a major drawback.

One of the other settings in the DBF is changing the **EE Clamp Mode** to "**Full**", which fixed another error in which some level terrain appears translucent, which seems to occur on surfaces where the game attempts to blend two textures (i.e. diffuse map + environment map).

The problem is that the "**Positive**" setting happens to be the ONLY **EE Round Mode** that permanently resurrects the translucent terrain error, regardless of what the **EE Clamp Mode** is set to.

In fact, after some version before 0.9.8, the terrain loads correctly on all other **Round Modes**, regardless of the **Clamp Mode**, making the DBF setting obsolete.

No manual fixes or plugin settings remedy this.

At the moment, players have the choice to either have the levels render correctly but play an unstable game, or the opposite. Hard to decide which issue is the "main" one or which one to target, as both seem very interwoven.

For reference, here are the differences between all the **EE Round Mode** settings:

- **Nearest:** Displacement occurs **semi-often**. No undesired translucency.

- **Negative:** Displacement occurs **very often**. No undesired translucency.

- **Positive:** Displacement **never** occurs. Resurrects undesired translucency.

- **Chop/ Zero:** Displacement **always** occurs. No undesired translucency.

**How to replicate:**

- Play the first level with the various EE options mentioned above to observe the different behaviors.

- The displacement can be easily provoked by moving the character in short bursts, making frequent stops. Stopping is the trigger. Should take no more than two minutes.

**Last known version to work:** Issue was never truly fixed.

**PC specifications:**

- CPU: i7-7700HQ CPU @ 2.80GHz

- GPU: NVIDIA Geforce GTX 1070 8GB

- RAM: 16 GB

- OS: Windows 10 Home (64-bit)

**Sample of the Translucent Terrain VS Expected:**

![tppcsx2](https://user-images.githubusercontent.com/66497936/83930054-bea05180-a763-11ea-99ab-b3479d92855f.png)

Though it may not look like it, the translucent surfaces seen here are assigned two different texture maps.

**Even though this is a core issue, here's the GS just in case:**

[gsdx_20200605185338.gs.zip](https://github.com/PCSX2/pcsx2/files/4738972/gsdx_20200605185338.gs.zip)

**Comment by prafullpcsx2** [comment]
I tried very hard to recreate the displacement bug at my place but couldn't. I have NTSC version of the game SCUS 97146. When you enable automatic gamefixes how many gamefixes are automatically applied? There should be three. EE timing hack, EE round mode nearest and EE clamping Full.

**Comment by Flintastic** [comment]
Yes, the NTSC version is the one I’m using. Those three settings are correct, and should be able to experience the displacement error.

The error never occurs when EE round mode is set to positive, so make sure that isn’t the case here. Easiest way to tell is the translucency. If you are not seeing translucency, then the displacement should occur. I find that just tapping the dpad in any direction rapidly for a few minutes is enough to see it.

**Comment by Jujumatic** [comment]
@prafullpcsx2 The displacement issue happens especially when the character is standing on certain level geometry, which normally means uneven platforms or generally terrain that is not perfectly flat. It normally happens when the character is moving and then stands still on one of these uneven surfaces. I have been using this part of the 1st level to test out the bug 
![image](https://user-images.githubusercontent.com/34321231/95177646-bb26e080-07be-11eb-8308-1da4e6ffc5cf.png)

I force the bug to happen by moving the character on and off the uneven platform and standing still - I can usually get the bugged movement to happen within 20 seconds. I can confirm that I just tested with EE round mode set to positive and have been unable to get the bugged movement after 5 minutes. But the terrain gets transparent like shown above.

**Comment by refractionpcsx2** [comment]
One of the reports says it's better to use EE/IOP rounding set to "nearest" and enable the EE Timing Hack under Config->Emulator Settings then Gamefixes (you will need to enable it at the top).  Hopefully the character flying off shouldn't be an issue

**Comment by Jujumatic** [comment]
PCSX2 Version 0.9.7 beta is the earliest build I've found that can run Treasure Planet, but the issue also present there. I tried earlier versions like 0.9.6 but could not get Treasure Planet to boot due to no EE Timing Hack being available. So this has been an issue since then

**Comment by refractionpcsx2** [comment]
I did have a quick mess around with this game, it looks like it's a real pig for floating point accuracy, im not sure it's going to be easy to fix.

**Comment by refractionpcsx2** [comment]
Hey can you do me a favour and try PR #3813 ? 

What I want you to do: Disable Automatic Fixes under PCSX2->Game Settings, then manually enable the EE Timing Fix under Config->Emulator Settings then the Gamefixes tab.  Please make sure both your EE and VU rounding is set to Chop/Zero (the default).  Let me know if the terrain looks right or if the camera goes crazy anymore.

**Comment by refractionpcsx2** [comment]
@Jujumatic @Flintastic can either of you guys confirm above?

**Comment by Flintastic** [comment]
@refractionpcsx2 I can confirm that neither the displacement nor the buggy terrain occur in the PR build with the mentioned settings. I tested the SCUS-97146 and SCES-51176 releases, and I think it's safe to assume that the other two releases (SLUS-21054 & SCES-51177) are fine as well.

For the game's entries in the DBF, I also want to recommend adding an automatic fix that changes the VU Clamping Mode to any option other than the default "Normal", as it causes some vertex explosions when the solar surfer's engines are inactive (can be observed in the second level).

**Comment by refractionpcsx2** [comment]
@Flintastic excellent, thanks for testing!

Interesting, has the VU Clamping always been that way? does Extra + Preserve Sign work okay for VU clamping? That would be the preferred option.

**Comment by Flintastic** [comment]
@refractionpcsx2 Yes, strangely the issue was always quietly present (earliest version I tested is 0.9.8). Admittedly, it is only visible when not accelerating the surfer, which is rarely something anyone would do during normal gameplay, so it is only really notable at the start of a level. Also, while the explosions usually cover about half the screen (depends on the viewing angle?), they can be seen through very easily so I wouldn't call it a severe issue.

And yes, Extra + Preserve Sign eliminates it just as well.

Thank you!

**Comment by refractionpcsx2** [comment]
Cool, in that case I'll remove the ee rounding and clamping and add the vu ones, thanks for your feedback! :) I'm glad we could solve this!

**Comment by Jujumatic** [comment]
@refractionpcsx2 sorry, for some reason I am not getting notifications on pings. Thanks for investigating and solving this issue! 👍

**Comment by refractionpcsx2** [comment]
You're welcome :) I didn't intend on fixing this, I was actually fixing another game, but I remember seeing some clues when I tested this and figured it'd be worth testing :P
