### ISSUE TITLE
White line when moving on some games

### ISSUE THREAD

**Issue by backgamon** [PCSX2/pcsx2#3443]
***PCSX2 version:***
PCSX2 v1.7.0-dev63-gca903bb6b1

***PCSX2 options:***
[For God of War II - Video attached]
**EE/IOP**
Round Mode EE/FPU=Chop/Zero
Clamping Mode = Full
**VUs**
Round Mode EE/FPU=Chop/Zero
Clamping Mode = Extra+Sign
**Speedhack**
MTVU=On
**Other**
Patch - N/A

***Plugins used:***
**GSDX**
OGL
Interlacing=None
Texture Filtering=Bilinear(PS2)
Allow 8-Bit Textures=On
6x Native
Anisotropic=16x
Mipmapping=Basic
CRC Hack=Partial
Date Accuracy = Fast
Blending=High
**Hack**
Align Sprite=On
Half Pixel Offset=Special(Texture)
**GSDUMP**

[gsdx_20200606110742.zip](https://github.com/PCSX2/pcsx2/files/4739729/gsdx_20200606110742.zip)

***Description of the issue:***
White line move with the character.
https://youtu.be/vtebybHFUcE

***How to reproduce the issue:***
Just launch incrimined game.

***PC specifications:***
I7 8700K@4.7Ghz
Maximus X Formula
32Gb DDR4 Trident Z RGB 3466Mhz[XMP@3200Mhz]
Gigabyte 2070 RTX 8G OC [446.14]
Windows 10 X64 Pro 1909 [18363.836]

**Comment by tadanokojin** [comment]
It's because you are upscaling
Maybe try with texture offset

But otherwise please use the forum for support with this kind of thing.
https://forums.pcsx2.net/
