### ISSUE TITLE
Discord Rich Presence Not Showing

### ISSUE THREAD

**Issue by GuckTubeYT** [PCSX2/pcsx2#3458]
When i play game Space Harrier, Just Only Showing This
![Capture](https://user-images.githubusercontent.com/56192597/84557728-a0d07f00-ad57-11ea-90f4-fb6b664f20f7.PNG)
Not Showing with the name games

**Comment by RedDevilus** [comment]
That's normal, Discord Rich Presence is not intregrated with main program to display individual games. There is a separate program for that.

**Comment by RedDevilus** [comment]
https://pypi.org/project/discordrp-pcsx2/
https://github.com/AnonGuy/discordrp-pcsx2
Although i don't know what happened to it. Used to be here a month ago.

**Comment by lightningterror** [comment]
Closing as it's not a valid issue.

**Comment by Asriel115** [comment]
> That's normal, Discord Rich Presence is not intregrated with main program to display individual games. There is a separate program for that.

Where or what is this separate program you speak of? Is it in the directory for the nightly build of PCSX2 or is it a separate program that needs to be installed alongside the emulator?

**Comment by Mrlinkwii** [comment]
@Asriel115  please use the discord or forums for help , this is is closed 4 years ago
