### ISSUE TITLE
Superman Returns graphical glitches 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#3459]
PCSX2 1.7.0-20200613042937 - using default speed settings no GS hacks just higher resolution (internal) 

I'm getting graphical glitches on software mode and hardware mode DX11 and openGL
dx 11
![1](https://user-images.githubusercontent.com/5770076/84567867-b0b68600-ad8c-11ea-9bf6-42ca8413ea03.gif)

dx11 software mode
![2](https://user-images.githubusercontent.com/5770076/84567878-c1ff9280-ad8c-11ea-8465-dfc6acfe1736.gif)

log file
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/4774524/emuLog.txt)

GS dump
https://www25.zippyshare.com/v/S2emAxX4/file.html

**Comment by lightningterror** [comment]
Duplicate #934
