### ISSUE TITLE
[Feature Request] Debugger Black theme option or similar for eye care

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#3460]
Good morning gentlement, i want to ask if possible include a dark theme or similar for PCSX2 debugger, because i spend many hours in debugger searching and testing but the white theme burns my eyes (with monitor 0 brigthness and blue ligth enabled), other tools i use has dark theme are easy in my eyes, thanks beforehand.

**Comment by AmFobes** [comment]
I'll look into stealing the theme from https://github.com/PCSX2/pcsx2/pull/3446 and putting it into the debugger and its menus

**Comment by RedDevilus** [comment]
I can do the colors but i can't code well. I have enough PRs to solve first anyway if you are up to the task.

**Comment by AmFobes** [comment]
Yeah I can do it, just figuring out where to put the option for dark mode.

**Comment by RedDevilus** [comment]
The titlebar? 
![image](https://user-images.githubusercontent.com/24227051/84715712-9558a000-af71-11ea-8000-58e95b20f1e7.png)

**Comment by AmFobes** [comment]
I'll probably go with the second option, I think that the help dialog might be windows specific due to the fact that the corresponding code is wrapped in `#ifdef _WIN32`

**Comment by RedDevilus** [comment]
My current plan was to add a context menu option like the second one but ehh gotta research some stuff.

**Comment by lightningterror** [comment]
Maybe better to have an unified option that controls both?

**Comment by RedDevilus** [comment]
While its intresting to have a global dark mode, unless someone can give some insights on WX then i can look for implementation.

**Comment by AmFobes** [comment]
Here, I didn't make that great of an effort to make the dark mode look nice but here is my branch supporting colour schemes.
https://github.com/AmFobes/pcsx2/tree/debug_colorscheme

Change the theme colours here
https://github.com/AmFobes/pcsx2/blob/2e9f47be7e69ad5c54c98d25c000319cf6e3b5b3/pcsx2/gui/Debugger/DisassemblyDialog.cpp#L689-L790

Obviously it isn't polished but should provide an easy way to edit the theme

**Comment by RedDevilus** [comment]
@AmFobes Perhaps make a Pull Request for it?

**Comment by orbea** [comment]
wxGTK3 should support the system theme, why not just change that instead?

**Comment by AmFobes** [comment]
I completely buggered up my fork of pcsx2 accidentally. I'll have to restart from master 🤦‍♂️

**Comment by RedDevilus** [comment]
Potentially fixed in future Qt PR.

**Comment by lightningterror** [comment]
Closing, trivial, once the debugger is added to Qt it will have the dark themes.
