### ISSUE TITLE
IPEGA Gamepad Not Detected

### ISSUE THREAD

**Issue by yogamandayu** [PCSX2/pcsx2#3461]
PCSX2 version 1.6.0
OS Manjaro Linux

I have issue where my gamepad didn't detected in controller setting. I use IPEGA 9099

onepad: Joystick (ShanWan     PC/PS3/Android Gamepad,GUID:03000000632500007505000011010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (ShanWan     PC/PS3/Android Gamepad,GUID:03000000632500007505000011010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

**Comment by lightningterror** [comment]
Can you create and post the mapping so we can add it to db?

**Comment by yogamandayu** [comment]
Mapping string: '03000000632500007505000011010000,IPEGA 9099,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,'
