### ISSUE TITLE
[Butt Ugly Martians - Zoom or Doom] Broken graphics; add automatic gamefix?

### ISSUE THREAD

**Issue by Lordalex-2** [PCSX2/pcsx2#3466]
***PCSX2 version:***
v1.7.0-dev-88-gca9e87624

I recently tested the game "Butt Ugly Martians: Zoom or Doom" [SLUS 20527]
[https://forums.pcsx2.net/Thread-Butt-Ugly-Martians-Zoom-or-Doom-SLUS-20527-U--28422?pid=610543#pid610543](https://forums.pcsx2.net/Thread-Butt-Ugly-Martians-Zoom-or-Doom-SLUS-20527-U--28422?pid=610543#pid610543)

The game had some severe graphical issues, which were fixed by enabling the "VU I bit Hack avoid constant recompilation (Crash Team Racing)" or "VU I bit Hack avoid constant recompilation (Scarface The World Is Yours)" gamefixes. I am unsure of what the diference is between them, however they both seemed to work. I did the most extensive testing on the Crash Team Racing version.

Is it possible to add one of these fixes as an automatic gamefix?

**Comment by RedDevilus** [comment]
Can you provide screenshots before and after you applied the gamefix?

**Comment by Lordalex-2** [comment]
> Are you sure that I bit hack is required? On ps4 no clamping on VU was all that game required to fix all VU issues. PCSX2 is more accurate, so maybe setting None is all that is needed.

After some further testing it appears that no clamping on VU also fixes the issue.

> Can you provide screenshots before and after you applied the gamefix?

Here are some screenshots of before and after, **using no clamping on VU**:

![gsdx_20200618143031](https://user-images.githubusercontent.com/67081936/85020968-6a3c9f00-b171-11ea-97e2-0d89716882d6.png)
![gsdx_20200618143714](https://user-images.githubusercontent.com/67081936/85020971-6b6dcc00-b171-11ea-99e1-f07f4324ba7c.png)
![gsdx_20200618143814](https://user-images.githubusercontent.com/67081936/85020976-6c066280-b171-11ea-9bf2-c3a4a2eb1968.png)
![gsdx_20200618143811](https://user-images.githubusercontent.com/67081936/85020975-6c066280-b171-11ea-849d-d6dab307ddfc.png)
