### ISSUE TITLE
Intallation on Fedora 30 already configurated rpmfusion nonfree

### ISSUE THREAD

**Issue by denn0n** [PCSX2/pcsx2#3467]
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
Last metadata expiration check: 1:25:02 ago on Wed 17 Jun 2020 06:24:21 PM EDT.
Package rpmfusion-free-release-30-1.noarch is already installed.
Package rpmfusion-nonfree-release-30-1.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

dnf search pcsx2
Last metadata expiration check: 1:25:29 ago on Wed 17 Jun 2020 06:24:21 PM EDT.
No matches found.

?? 
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by orbea** [comment]
Wrong repo, no coherent issue... I think you will get better luck asking for help in a fedora community. All I can tell from your logs is that rpmfusion-free and rpmfusion-nonfree are already installed.

**Comment by denn0n** [comment]
Sorry to bother you guys excellent work i was available to install it in a fresh fedora box thank you for all at your work ! there is a way to contribute to the project ? thank you again
