### ISSUE TITLE
[Bug]The King of Fighters 2000 Resolution problem

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#3486]
KOF 2000 has big black bars, it was already signaled here :
https://forums.pcsx2.net/Thread-GSDX-PCRTC-Bug-Report-The-King-of-Fighters-2000-SLPS-251-56
![2015-10-22_00001](https://user-images.githubusercontent.com/47425204/85273476-f0145f00-b47d-11ea-8454-85b4c6ec095c.png)

I'm using latest builds with Software rendering.

**Comment by Silanda** [comment]
It's mentioned in #961 and #3287 is related.

It's fixable with a hack similar to the NTSC_Saturation hack that's already present, though I have no idea if that could bust anything else. Are there any 640x256 Progressive NTSC games that actually fill the screen?

**Comment by Immersion95** [comment]
Unfortunately I can't help you with the list

**Comment by tadanokojin** [comment]
Closing as @Silanda mentioned there is a meta issue already.
