### ISSUE TITLE
Fishing Hook isn't visible - Persona 4 (SLUS-21782)

### ISSUE THREAD

**Issue by LOuroboros** [PCSX2/pcsx2#3488]
***PCSX2 version:***
v1.7.0-dev-97-g297f91ae7

***PCSX2 options:***
**Emulation Settings**:
Preset 3 - Balanced

**Video**:
![pcsx2-2020-06-23_01-06-27](https://user-images.githubusercontent.com/54429803/85359890-ede9e900-b4ed-11ea-9239-4303fa3a8a7d.png)
It's worth noting that the issue is still present even if I change the Renderer to D3D11 SW, OpenGL HW or OpenGL SW.

***Plugins used:***
GSdx aside, the only other changes I did were in the Audio department, but that should be irrelevant to this issue.

***Description of the issue:***
The hook or the water ripples don't show up when I try to play the Fishing minigame.

In this video it can be clearly seen how there's ripples in the water indicating whether a fish is about to bite or not.
https://youtu.be/-19MrjMn83M?t=27

However, PCSX2 does not display them, making the minigame impossible to play correctly without a smart usage of save states and the sound effect that plays at that particular moment.
https://streamable.com/atih76

***How to reproduce the issue:***
Play the game until you unlock access to the minigame at Samegawa Flood Plain's Riverbed, go there and just start it.

***Last known version to work:***
No clue.

***PC specifications:***
**CPU**: Intel Core i3 2120 _(2C/4T)_ running at 3.3GHz
**RAM**: 4 GB DDR3 in Single Channel running at 665 MHz
**GPU**: Gigabyte's NVIDIA GeForce GT 1030 2GB GDDR5 _(Driver Version 446.14)_
**OS**: Windows 8.1 x64

**Comment by kozarovv** [comment]
For me this work fine, only difference is that I own PAL game. Just tested on the same build, with the same settings. Even the same Geforce driver version. I wasn't able to reproduce that no matter how hard i messed emulation settings. 
Do you use any game cheats, patches, etc?

**Comment by LOuroboros** [comment]
> For me this work fine, only difference is that I own PAL game.
I wish I could check it out, but I can't.

> Do you use any game cheats, patches, etc?
Nope, I don't.

> Edit: Does it happen in non rainy days? Because i don't have any savestate close to rainy day to check that.
It happens regardless of the weather. I checked on a cloudy day and I still can't see the ripples.
https://streamable.com/5zbmh8

**Comment by LOuroboros** [comment]
Agh... I'm an idiot. I double checked, and it turns out the issue was being caused by a cheat that I completely forgot I added, to disable the sickening motion blur that the game has.

Sigh... I'm sorry, my bad. I'm closing this no-issue right away.
