### ISSUE TITLE
Gladiator: Sword of Vengeance Freezing FMVs and Shadow Errors

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#3489]
***PCSX2 version:***
1.6.0 and 1.7.0-dev-26

***PCSX2 options:***
Default, tried all manual game fixes, and all EE/IOP and VU Round and Clamping mode options, software and hardware rendering.

***Plugins used:***
D3DHW, GLHW, and GLSW

***Description of the issues:***
1) FMVs in the game freeze after a short period of time. The intro FMV freezes on "Acclaim Studios Manchester". If you skip that FMV and leave the game on the title screen for a few moments a different FMV starts and it also freezes. Interestingly, the software FMV manual fix doesn't get triggered, nor does the skip MPEG hack.

2) There are occasional shadow rendering errors, even in software rendering. They sortof stretch and extend much further than they should. It doesn't always happen, but can be seen early on during the Hoplomachus and proceeding fights.

![image](https://user-images.githubusercontent.com/24979172/85426866-076c4e80-b549-11ea-9efb-8a224396b66c.png)

***How to reproduce the issue:***
1) Start the game and let the FMV play

2) Play through the intro level until you get to the Hopolomachus fight (probably 2 or 3 minutes into the level)

***Last known version to work:***
Unknown

***PC specifications:***
i7 4770k / GTX 780 / 32GB RAM / W7 64

**Comment by lightningterror** [comment]
Does changing Date Accuracy, Blending Accuracy affect the shadows?

**Comment by Zombeaver** [comment]
Nope. I tested the below:

Blending Accuracy: None / Basic / Ultra on GL
Date Accuracy: Off / Fast / Slow on GL

No change. And as I said it happens in SW as well.

**Comment by lightningterror** [comment]
Ah right, forgot about that, did you try changing core settings or gamefixes if any have an effect?

**Comment by tadanokojin** [comment]
He already said he tried all gamefixes and clamping/rounding.

**Comment by Zombeaver** [comment]
Yep, I tried all manual game fixes and EE/IOP and VU clamping settings. No change.

**Comment by MrCK1** [comment]
@Zombeaver Are you able to retest this on the latest dev build? The FMVs probably won't change but there were changes to the VUs recently that might help the stretching shadow issue. Thanks.

**Comment by refractionpcsx2** [comment]
FMV's will be fixed once #5173 merges

**Comment by refractionpcsx2** [comment]
Is this still an issue? I can't seem to reproduce this anymore.

**Comment by lightningterror** [comment]
Let's close it then, if it's still an issue then it can be reopened.
