### ISSUE TITLE
Support running as a libretro core

### ISSUE THREAD

**Issue by rah2501** [PCSX2/pcsx2#3491]
Libretro support would be excellent.

https://docs.libretro.com/development/cores/developing-cores/

**Comment by rah2501** [comment]
I can't seem to assign the "Enhancement / Feature Request" label to this issue :-/

**Comment by avih** [comment]
Why would it be "excellent"? and to whom?

**Comment by rah2501** [comment]
I'll assume your questions are not disingenuous.

> Why would it be "excellent"?

I'm not sure how to answer this really.  It seems self-evident to me.  The only explanation I can think of is to quote the dictionary:

```
  Excellent \Ex"cel*lent\, a. [F. excellent, L. excellens, -entis,
     p. pr. of excellere. See {Excel}.]
     1. Excelling; surpassing others in some good quality or the
        sum of qualities; of great worth; eminent, in a good
        sense; superior; as, an excellent man, artist, citizen,
        husband, discourse, book, song, etc.; excellent breeding,
        principles, aims, action.
        [1913 Webster]
```

> and to whom?

1. Those who like to play retro games in emulators
2. Those who build retro gaming machines
3. Those who like to use a ten-foot interface to their operating system
4. Those who use Lakka
5. Etc., etc.

Are you aware of libretro, RetroArch, etc., what they do and how they work?

**Comment by avih** [comment]
> Are you aware of libretro, RetroArch, etc., what they do and how they work?

I Not before today, but I read about it briefly. I don't see what problem it solves for PCSX2.

**Comment by rah2501** [comment]
> I don't see what problem it solves for PCSX2.

It seems like we have different, conflicting views.  The way I would describe patches that solve problems is to say that the solve them for the *user*, not for the software.  I see the software as inanimate, it doesn't have wants or needs or problems to solve.

Supporting running as a libretro core would solve a number of problems for users, some of which I mentioned in my previous comment.  In particular, the big thing that comes to mind is using a ten-foot interface.

**Comment by RedDevilus** [comment]
Then it's a [Feature Request] or general improvements or alternatives to the UI/UX.

**Comment by rah2501** [comment]
> Then it's a [Feature Request] or general improvements or alternatives to the UI/UX.

[Indeed](https://github.com/PCSX2/pcsx2/issues/3491#issuecomment-648729797).

**Comment by avih** [comment]
> It seems like we have different, conflicting views

I didn't have any view, therefore my first post was a question to understand better how it helps and to whom. It doesn't matter that it's a feature request, it's still supposed to make something better for someone, or else you wouldn't have requested it, right?

All the things you listed in your reply are not unique to libretro as far as I can tell, and you can already do them with PCSX2 currently, can you not?

**Comment by tadanokojin** [comment]
If someone would like to take the time and effort and it's not too intrusive and can be reasonably maintained I suppose it's fine. I don't really think it's a priority for our team though and none of us have expressed any interest in working on it.

I'm not even really sure it will work out given our plugin architecture.

That being said there is already a PS2 core for RA. It's Play!

**Comment by rah2501** [comment]
> All the things you listed in your reply are not unique to libretro as far as I can tell, and you can already do them with PCSX2 currently, can you not?

I don't know.  How can you use PCSX2 with a ten-foot interface?

**Comment by RedDevilus** [comment]
Personally i would use Launchbox (BigBox mode) or steam Big Picture mode or even other frontlaunchers. The annoying part is when you need to use the config then you would need to revert back to the ol' Mouse and Keyboard. I do get you want uniformity and ease of use but this is quite alot of work, perhaps someone somewhere is interested and has the power to make it happen but we will see.

**Comment by rah2501** [comment]
> Launchbox 

Launchbox is Windows-only.  You can't use it for PCSX2 on Linux or Mac.

> steam Big Picture mode

As I understand it, to do that you would need to create individual shortcuts for each rom you wanted to load.

**Comment by RedDevilus** [comment]
Yeah that's why i said other front ends, I'm not going to name them all of course. I understand what you want and it's true the current status is that you need to create individual shortcuts per rom.

**Comment by refractionpcsx2** [comment]
Most of the team has discussed this and we have no desire to do a libretro core. If a 3rd party wants to make one/PR it, i guess we will consider merging it, but we have no desire to do it ourselves.

**Comment by rah2501** [comment]
Just a point of order: I'm wondering why this issue was closed?  In my experience in free software projects, "the team" changes over time.  This issue could act as a note and a holder for information about PCSX2-as-a-libretro-core for anyone who follows.

When I opened this issue, my expectation is that it would remain open for years until someone came along and took it on.  Your closing of the issue shows a different approach to GitHub issues which I don't understand.

**Comment by refractionpcsx2** [comment]
You're not the first person to ask for it, and i doubt you'll be the last. I'm sure it'll get asked again at least 20 times this year, so if you're worried that opinions will be different in the future, don't worry, there will be others in your place making the same request, over and over again.

**Comment by rah2501** [comment]
Why close the issue?

**Comment by refractionpcsx2** [comment]
If we left every issue open that we weren't going to action, the clutter would be even more ridiculous than it currently is.

**Comment by rah2501** [comment]
Odd.  To me, there seems to be a relatively low number of issues in this project and they seem well organised.  Oh well.

**Comment by ameenross** [comment]
>  there will be others in your place making the same request

I think the consensus of the team will possibly change eventually, and then it's pretty much irrelevant that there's already (closed) issues about that on GitHub.

> Odd. To me, there seems to be a relatively low number of issues in this project and they seem well organised. Oh well.

Don't worry and let them manage the issue queue how they think is best. Maybe someday someone will step up and take up the effort.

**Comment by RedDevilus** [comment]
It's just easier to do the high priority stuff first and go lower on the queue list. It's not like they close it , forget about it and don't care about it. Lack of time/developers force them to make hard choices, no point in doing everything and not finishing other stuff. And if anyone wants to do the work themselves (like what is already been told here) it will be reviewed and if good it will be added to the main program. Anyway have a good day.

**Comment by DukeSkinny** [comment]
I'd just like to point out a few trademarks of a libretro core that could actually enhance the user experience of PCSX2:

- Universal shader support that doesn't break compatibility with older shaders (unlike Reshade, which is fiddly & less set&forget)

- Integer scaling which is important for a clear, fullscreen picture

- A robust v-sync implementation & dynamic sync settings which can cater to many setups

Getting satisfying results when running PCSX2 on my VGA would be vastly simplified, for instance

**Comment by BroKill** [comment]
I always chose standalone version to a libretro core. Why? Because libretro cores work bad compared to standalone version. Some example : MAME core, Dolphin core and Citra core.
Only Mednafen ( PS and Saturn ), Kronos and Flycast here have no problem compared to standalone versions ( all cores made by original devs ).

If the core Is developed by libretro guys it will never be as good as the original standalone one.

 This is my experience with RA.

About Play! core...it's so far away  from PCSX2 in terms of stability, compatibility and support.
All games I have don't run on that core.

I'm using LaunchBox as frontend, the best option for those who want to build a cabinet or for those who like to launch all emulators under the same UI ( you can do everything with it and sometimes it adds something to emus ).


CHEERs

**Comment by orbea** [comment]
>  If a 3rd party wants to make one/PR it, i guess we will consider merging it, but we have no desire to do it ourselves.

Take a look at ppsspp, the libretro support was merged years ago and as has been completely broken just as long...

**Comment by IngwiePhoenix** [comment]
Sorry to poke a closed issue; but I did not want to open up a new one for something that is quite unlikely to be "officially" supported.

I took a look at the PPSSPP core implementation and immediately understood *why* it was broken; mainly, because the implementation of `libretro.h` seemed surprisingly sloppy. Like, an external thread is brought up to handle literally everything and most `retro_*` APIs are completely ignored. The environment callbacks are obtained, but only used for the very, most basic instantiation. This could have been better.

Now - rant aside - I think it would be possible to forge a libretro core for PCSX2. I would even consider giving it a shot myself. But I have, so far, not been able to determine two things:

- Why is `wxString` used within the VM implementation?
- Where is the entrypoint to setting up and destroying a VM and applying a rendering context?

It seems as if the actual emulator is very tightly tied to GUI elements. Got some pointers for me?

**Comment by AmFobes** [comment]
> Sorry to poke a closed issue; but I did not want to open up a new one for something that is quite unlikely to be "officially" supported.
> 
> I took a look at the PPSSPP core implementation and immediately understood _why_ it was broken; mainly, because the implementation of `libretro.h` seemed surprisingly sloppy. Like, an external thread is brought up to handle literally everything and most `retro_*` APIs are completely ignored. The environment callbacks are obtained, but only used for the very, most basic instantiation. This could have been better.
> 
> Now - rant aside - I think it would be possible to forge a libretro core for PCSX2. I would even consider giving it a shot myself. But I have, so far, not been able to determine two things:
> 
> * Why is `wxString` used within the VM implementation?
> * Where is the entrypoint to setting up and destroying a VM and applying a rendering context?
> 
> It seems as if the actual emulator is very tightly tied to GUI elements. Got some pointers for me?

I'm not the one to answer those questions but, isn't there an effort by libretro themselves to create a core?
https://github.com/libretro/pcsx2

**Comment by IngwiePhoenix** [comment]
I didn't know about that. Interesting!

Looking at the source, a few basics of rendering, CDVD and other system specifics have been mapped into the libretro API. I'll keep an eye on this. Thanks for the pointer!

First thing that stood out: They are still including the wxWidgets headers. That core is gonna be a big one... oh boy.

**Comment by Kreijstal** [comment]
Has the team changed the opinion on supporting a libretro core :) ?

**Comment by JordanTheToaster** [comment]
> Has the team changed the opinion on supporting a libretro core :) ?

no

**Comment by Kreijstal** [comment]
> Most definitively not.
> 
> https://github.com/libretro/pcsx2/commits/master/ Last commit: 2 years ago.

Yeah I noticed that project is abandoned, which is why I was hoping for maybe a voice from the upstream developers, but maybe I'll ask in another 10 years, maybe they'll change their minds

**Comment by JordanTheToaster** [comment]
> I'll ask in another 10 years, maybe they'll change their minds

still no

**Comment by matheuswillder** [comment]
> > Most definitively not.
> > https://github.com/libretro/pcsx2/commits/master/ Last commit: 2 years ago.
> 
> Yeah I noticed that project is abandoned, which is why I was hoping for maybe a voice from the upstream developers, but maybe I'll ask in another 10 years, maybe they'll change their minds

Their fork to a Libretro core is still active and (relatively) maintained, they just moved to the repository: https://github.com/libretro/ps2

It can be downloaded under the name LRPS2. It's not as performant as PCSX2, but it's no longer the broken mess it was once and works relatively well now, provided you set it up correctly as instructed here: https://docs.libretro.com/library/lrps2/#setup-required, and there's also an announcement about the work done here: https://www.libretro.com/index.php/lrps2-the-new-playstation2-core-with-a-brand-new-lle-renderer/

Just to point to the current repository, at least this way people interested on it can find, use, or even contribute to their fork.

Edit: there is also a new core called PCEE2, it is a work in progress so currently it is not as stable as LRPS2 yet. It also requires following the setup described in the PCEE2 core repository. I posted about it in a new comment but noticed it got deleted (I don't know if there is any rift between the projects, I don't know who maintains each one currently and I'm just an ordinary user).

**Comment by matheuswillder** [comment]
Just a update: there is a new port of PCSX2 for Libretro/RetroArch called PCEE2. And thanks to the work done by the ARMSX2 team, it seems that the Android-related code [has also been ported](https://github.com/WizzardSK/pcee2-libretro/issues/19#issuecomment-5385598455), so this core runs on Android as well:

<img width="2340" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3c245ad3-7ee4-48c2-ba52-da3a9872c4d2" />

Just like with LRPS2 core (which I mentioned in the comment above), you need to follow the setup instructions to get the files required to run this core without issues (including the files/folders currently marked as "optional" there): https://github.com/WizzardSK/pcee2-libretro#setup

You can get it in **Online Updater>Core Downloader**. It was recently released and appears to still be a work in progress, so you can report any issues in their repository: https://github.com/WizzardSK/pcee2-libretro/issues

I'm not involved with either project in any way, I just came across and thought others here might appreciate it.
