### ISSUE TITLE
[BUG] Can not make more threads, then 16

### ISSUE THREAD

**Issue by SlimRG** [PCSX2/pcsx2#3492]
Good night!
I have 2 sockets: Intel Core Xeon 
So, I have 20 real and 40 virtual proccessor cores.
I tried to plase 18 cores.
![image](https://user-images.githubusercontent.com/39348033/85550395-96509800-b629-11ea-918d-139a11b70398.png)
But, when I open plugin windows again - cores are only 16
![image](https://user-images.githubusercontent.com/39348033/85550514-b7b18400-b629-11ea-967a-424ddb52b6dc.png)

**Comment by SlimRG** [comment]
![image](https://user-images.githubusercontent.com/39348033/85550587-ca2bbd80-b629-11ea-91d6-113b0c9de601.png)

**Comment by lightningterror** [comment]
It's not a bug. Maximum allowed value is 16.

**Comment by iMineLink** [comment]
Is this like a hard limit for the GSdx architecture or do you think that more than 16 threads could be supported without much hassle?

**Comment by SlimRG** [comment]
As I think, if GSdx has limit, GUI shuoldn't access me to place value more then 16

**Comment by refractionpcsx2** [comment]
As tadanokojin said, after 4 extra threads, it actually slows you down, so having more than 16 threads will be of zero benefit to you

**Comment by SlimRG** [comment]
I understand.
I tries to say, that I should't have aceess to place wrong value into textbox in GUI.
But I have!

**Comment by SlimRG** [comment]
This situation shouldn't be possible
![image](https://user-images.githubusercontent.com/39348033/85688396-62817b00-b6da-11ea-93f0-a3f304a74dff.png)

**Comment by refractionpcsx2** [comment]
Now *that* is a bug ;) Well, a bug/enhancement, we will probably limit it to something like 32, which isn't very  useful, but yeah you shouldn't be allowed 9999 threads.

Does it actually save 9999 after you click OK and go back in?

**Comment by SlimRG** [comment]
No, it doesn't save.
But GUI button should have hidden style like panels upper.
![image](https://user-images.githubusercontent.com/39348033/85689664-7e395100-b6db-11ea-98da-8f45c5fb7b9f.png)

**Comment by refractionpcsx2** [comment]
Okay well I'll mark this as a UI enhancement to put a limit on that box.

**Comment by kozarovv** [comment]
While this is different place/window, maybe can be fixed at once. Looks like Texture Offsets in upscaling hacks have similar behavior. You can select 99999999 there, after you click ok, and reopen setting value 10000 (max) is saved. 

Skipdraw range is not affected, and when you provide higher value than allowed, it will auto select 10000, and not allow to select anything higher.

**Comment by lightningterror** [comment]
Test https://github.com/PCSX2/pcsx2/pull/3497 should fix the issue for all spin buttons.

**Comment by kozarovv** [comment]
#3497 fix it, osd (size, timeout, max), tc offsets (x, y), rendering threads. At least on Windows 10, because that where i tested.
