### ISSUE TITLE
[BUG] Adapter list behave strangely

### ISSUE THREAD

**Issue by SlimRG** [PCSX2/pcsx2#3495]
I have PC with integrate, discrete videocards (and USB Typ-C videocard, but I will write about it in future).
My device list:
![image](https://user-images.githubusercontent.com/39348033/85691494-3a474b80-b6dd-11ea-8d89-509efd7dfe54.png)
And plugin adapters:
![image](https://user-images.githubusercontent.com/39348033/85690799-99f12700-b6dc-11ea-9ef1-7c9a97375a35.png)
Program uses Intel Adapter, but AMD is more powerfull.
I don't know why, but GS Adapter list after some PCSX2 releases stoped working and become hidden.

**Comment by tadanokojin** [comment]
It never did anything for GL. For GL, driver select the adapter.

**Comment by tadanokojin** [comment]
OpenGL.

**Comment by SlimRG** [comment]
For DirectX I have the same problem

**Comment by tadanokojin** [comment]
DX should let you select the adapter.

**Comment by SlimRG** [comment]
![image](https://user-images.githubusercontent.com/39348033/85694069-77acd880-b6df-11ea-9ecd-e253f9404d9b.png)

**Comment by SlimRG** [comment]
No AMD Radeon HD 8670m

**Comment by refractionpcsx2** [comment]
Looks like you haven't installed your AMD driver, that's the only reason the Basic Render Driver should be there.

**Comment by SlimRG** [comment]
As you can see upper - driver was installed successfully (with Radeon Adrenalin)
I can play with cs go or select this videocard in FureMark
I understand, that this GPU is inclassical, because of old drivers.
BUT! Why it work with another programms?

**Comment by refractionpcsx2** [comment]
I'm not sure, GSdx just asks windows for a list of devices and their names, it doesn't do anything special.

**Comment by SlimRG** [comment]
And in old versions of PCSX2 all works good (only after full instalation, NOT PORTABLE!!!)

**Comment by SlimRG** [comment]
> I'm not sure, GSdx just asks windows for a list of devices and their names, it doesn't do anything special.
> 
> As for OpenGL that will use the default device driver, we can't choose that, so you will need to make a profile for PCSX2 in the AMD Adrenaline driver for that to work with OpenGL

Yes, after adding profile - all starts work correctly
Thanks!

**Comment by refractionpcsx2** [comment]
Just curious, now you've added a profile, does the display adapter list for DirectX 11 show your AMD card?

**Comment by SlimRG** [comment]
Yes, it is

**Comment by SlimRG** [comment]
As I think, this situation was because AMD Adrenaline doesn't initialize PCSX2 as hard graphic application
Maybe, AMD has database with popular hard graphic applications, where was no enthusiast unpopular programms

**Comment by refractionpcsx2** [comment]
Cool, thanks for coming back to me, yes it sounds like a windows thing, possibly specific to laptops which do weird switching of GPU's with games/programs, not really something we can fix unfortunately!

**Comment by SlimRG** [comment]
Thanks for help
![image](https://user-images.githubusercontent.com/39348033/85745718-96769380-b70e-11ea-878b-dc86ebd550bd.png)
AMD profilies in windows are in regedit
I don't know, if this photo can help you, but if it can - it will be fantastic
