### ISSUE TITLE
Gauntlet: Dark Legacy - Magic Shield effects are broken

### ISSUE THREAD

**Issue by autofire372** [PCSX2/pcsx2#3502]
***PCSX2 version:***
1.7.0-dev-107

***PCSX2 options:***
Safest

***Plugins used:***
GSdx 20200627164442 AVX2/AVX2 at 3x Native resolution with 16x anisotropic filtering. Disabling either had no effect on the bug.

***Description of the issue:***
The effects seen when invoking Magic Shield render only as broken polygons on all backends:
![gsdx_20200627230131](https://user-images.githubusercontent.com/8486750/85936868-a5a34000-b8cc-11ea-9a54-19714a39e236.png)

***How to reproduce the issue:***
1. Boot game
2. Obtain a potion
3. Double tap circle to invoke Magic Shield
4. Observe broken graphics

***Last known version to work:***
Tested as far back as 1.4.0 stable; still broken.

***PC specifications:***
CPU: Intel Core i7-9700k
GPU: Nvidia GeForce GTX 1070Ti
OS: Windows 10 64 Bit

**Comment by MrCK1** [comment]
Have you also tried the software backends and/or the alternative clamping or rounding modes?

**Comment by Dreadmoth** [comment]
I can't reproduce this issue.

Same settings, PCSX2 version and GSdx version:
![gsdx_20200628165037](https://user-images.githubusercontent.com/8492684/85944346-6c74d980-b979-11ea-8272-d3a45cab962d.png)

CPU: Intel Core i7-4770
GPU: Nvidia GeForce GTX 1070 Ti
OS: Windows 10 64-bit

**Comment by autofire372** [comment]
> I can't reproduce this issue.
> 
> Same settings, PCSX2 version and GSdx version:
> ![gsdx_20200628165037](https://user-images.githubusercontent.com/8492684/85944346-6c74d980-b979-11ea-8272-d3a45cab962d.png)
> 
> CPU: Intel Core i7-4770
> GPU: Nvidia GeForce GTX 1070 Ti
> OS: Windows 10 64-bit

Starting to think this might be a driver issue, then. What GPU driver version are you running with? I'm on 445.87.

**Comment by Dreadmoth** [comment]
> Starting to think this might be a driver issue, then. What GPU driver version are you running with? I'm on 445.87.

I'm on 451.48.
Windows 10 version 2004.

**Comment by autofire372** [comment]
Nope. Updated my video driver and it's STILL broken:
![gsdx_20200628111839](https://user-images.githubusercontent.com/8486750/85951427-2c8a0400-b931-11ea-90d9-3c1eb6f9b7e7.png)

**Comment by lightningterror** [comment]
Maybe a bad ws patch or cheat, non default settings?

**Comment by autofire372** [comment]
Turning off cheats and widescreen patches did nothing.

**Comment by autofire372** [comment]
Closing; turns out this is just what happens when Magic Shield is invoked while Invulnerability is in effect.
