### ISSUE TITLE
[Feature Request] GUI:Plugins. Autopick the correct plugins if new install (1.6) over old install (1.4).

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3504]
I see alot of users having a 1.4 PCSX2 and then install a 1.6 PCSX2 over it but it picks the 1.4 plugins.
Is there a way to make the First Time Wizard to autopick the newest plugins (and ofcourse the correct plugins from 1.6) either by date or its numbers in its strings.

Hope this is possible or an alternative to this.

**Comment by lightningterror** [comment]
I'd just remove the ability to change plugins location and set a fixed one that is always exe directory instead.
Don't see why we even need to change plugins location anyway, and will cause issues when importing settings from older versions.

**Comment by RedDevilus** [comment]
Hardcoding the exe to its own plugins was an idea i had but i thought this wasn't possible. And i agree having a checkbox to change the plugins path isnt that intuitive for users.

It's also the main reason why i found importing ehh, and always went to overwriting it or just use a dev build. Atleast the PCSX2_Backup folder is very handy from the 1.6 NSIS installer. Thanks :)

Off-topic: Is there also an option to go into the GUI without a BIOS? Then i can quickly check GUI changes (Nitpicky i know).

**Comment by vsub** [comment]
How about changing "UseDefaultPluginsFolder" to false if older version of pcsx2 is installed

**Comment by MrCK1** [comment]
Closing since most of the plugins have been merged already
