### ISSUE TITLE
JoyStick Database Addition Request - Alienware Dual Compatible Game Pad

### ISSUE THREAD

**Issue by Anigai** [PCSX2/pcsx2#3505]
PCSX2 v1.6.0

Program Log Details:
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (Alienware Dual Compatible Game Pad,GUID:030000007c1800000006000010010000) isn't yet supported by the SDL2 game controller API

***PCSX2 options:***
N/A

***Plugins used:***
OnePAD 20200505220805-Dev 2.0.0
Default Settings used

***Description of the issue:***
Pressure sensitive buttons required for Metal Gear Solid 3.
This controller has both a hardwired USB and hardwired standard PS2 connector, pressure sensitive buttons work fine on a standard PS2.

***How to reproduce the issue:***
Message appears in Program Log upon plugging controller into USB 2.0 port.

***Last known version to work:***
N/A

***PC specifications:***
[sean@NEWDESTINY ~]$ inxi -Fxzc0
System:    Host: NEWDESTINY Kernel: 5.4.44-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Xfce 4.14.2 
           Distro: Manjaro Linux 
Machine:   Type: Desktop System: MSI product: MS-7850 v: 1.0 serial: <filter> 
           Mobo: MSI model: Z97 PC Mate(MS-7850) v: 1.0 serial: <filter> UEFI [Legacy]: American Megatrends v: 4.11 
           date: 02/16/2016 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master charge: 55% (should be ignored) 
           status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i7-4790K bits: 64 type: MT MCP arch: Haswell rev: 3 L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 64027 
           Speed: 1000 MHz min/max: 800/4400 MHz Core speeds (MHz): 1: 1000 2: 1000 3: 1000 4: 1000 5: 1002 6: 1002 
           7: 1002 8: 1001 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 430.64 bus ID: 01:00.0 
           Display: x11 server: X.org 1.20.8 driver: nvidia resolution: <xdpyinfo missing> 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 430.64 direct render: Yes 
Audio:     Device-1: Intel 9 Series Family HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Device-3: Kingston HyperX 7.1 Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 2-3:3 
           Sound Server: ALSA v: k5.4.44-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI driver: r8168 
           v: 8.048.03-NAPI port: d000 bus ID: 02:00.0 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad bus ID: 2-2:2 
Drives:    Local Storage: total: 4.88 TiB used: 2.30 TiB (47.1%) 
           ID-1: /dev/sda vendor: SanDisk model: SDSSDA120G size: 111.79 GiB 
           ID-2: /dev/sdb vendor: Seagate model: ST1000DX001-1CM162 size: 931.51 GiB 
           ID-3: /dev/sdc vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB 
           ID-4: /dev/sdd vendor: Seagate model: ST2000DX002-2DV164 size: 1.82 TiB 
           ID-5: /dev/sde vendor: Samsung model: SSD 850 EVO 250GB size: 232.89 GiB 
           ID-6: /dev/sdg type: USB vendor: Western Digital model: WD10EURX-63FH1Y0 size: 931.48 GiB 
Partition: ID-1: / size: 109.53 GiB used: 70.10 GiB (64.0%) fs: ext4 dev: /dev/sda1 
           ID-2: swap-1 size: 16.00 GiB used: 2.0 MiB (0.0%) fs: swap dev: /dev/sdc3 
Sensors:   System Temperatures: cpu: 35.0 C mobo: N/A gpu: nvidia temp: 46 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Info:      Processes: 251 Uptime: 10h 22m Memory: 15.59 GiB used: 3.43 GiB (22.0%) Init: systemd Compilers: gcc: 10.1.0 
           clang: 10.0.0 Shell: bash v: 5.0.17 inxi: 3.0.37

**Comment by RedDevilus** [comment]
What's the mapping in Antimicro? Then it will be added to the dev builds.

Example: 
03000000ff1100003133000010010000,PC Game Controller,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b0,platform:Linux,

**Comment by Anigai** [comment]
I wasn't sure how to get antimicro to output that example text but I found some help from a previous issue by using gamepad tool.
[Linux] OnePad issues #2495
https://github.com/PCSX2/pcsx2/issues/2495

I hope this good enough?

Mapping string: '030000007c1800000006000010010000,Alienware Dual Compatible Game Pad,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a2,lefttrigger:b6,righttrigger:b7,platform:Linux,'
Searching gamepads...
Found 1 gamepad(s):
"Alienware Dual Compatible Game Pad", 030000007c1800000006000010010000 (mapping available)

**Comment by RedDevilus** [comment]
Yeah seems fine, i'll reorder it to have consistency with the others and make a PR.

**Comment by lightningterror** [comment]
@RedDevilus can you also pr the change upstream on source repo?

**Comment by RedDevilus** [comment]
Is that the same what i did the last time?

**Comment by lightningterror** [comment]
https://github.com/gabomdq/SDL_GameControllerDB

**Comment by RedDevilus** [comment]
Ah right the community where you update the controller database from, thanks for reminding.
