### ISSUE TITLE
plugin error, DEV9ghzdrk.dll, error 126: the specified module could not be found

### ISSUE THREAD

**Issue by MelchiorGaspar** [PCSX2/pcsx2#3514]
***PCSX2 version:***
(v1.7.0-r109)(Dev)

***Description of the issue:***
[wx] Failed to load shared library 'F:\EmulatorsRoms\PS2\Plugins\DEV9ghzdrk.dll'
 (error 126: the specified module could not be found.)

why this is the case idk, the file is in the correct folder,
but errors occurs when I go to open the 
CONFIG(menu) --> "Plugin/BIOS Selector"(menu).

***How to reproduce the issue:***
see  above.

***Last known version to work:***
unknown, I did see it happening in v1.7.0-r102 as well.. just didn't get around to reporting it 
not sure how far back it goes..

***PC specifications:***
Windows 10 Pro x64
CPU: AMD Ryzen 9 3900X
GPU: EVGA/Nvidia GTX 1070 Ti 8GB
see my CPUz Report for FULL specs -->   https://valid.x86.fr/h1syvr

ps: if u have any questions or suggestions please ask or specify.

**Comment by yxmline** [comment]
install npcap

**Comment by MelchiorGaspar** [comment]
and why should I install a sketchy program that is "Npcap is the Nmap Project's packet sniffing (and sending) library for Windows. "
I see no reason that should effect this issue...

**Comment by bositman** [comment]
NPcap isn't sketchy you probably don't know what it's used for. The plugin requires it

**Comment by MelchiorGaspar** [comment]
it didn't need it before.... or at least I don't think it need it on Windows 7 because it was working before unless I had installed it...
why does DEV9ghzdrk.dll need it?

**Comment by refractionpcsx2** [comment]
You would have had to installed either Npcap or Winpcap for the plugin to even work.  

DEV9ghzdrk uses it for internet connectivity, it provides a networking layer it can use.

**Comment by MelchiorGaspar** [comment]
ooh ok... so its safe to use without putting my whole system at risk?
what about is this plugin even needed for general use of playing my games via this emulator 
what does DEV9ghzdrk.dll do?

**Comment by refractionpcsx2** [comment]
Correct, it is not dangerous. 

You don't need DEV9ghzdrk unless you plan on going online with games or writing your games to a virtual hard disk. in 99% of cases you can change the plugin to dev9null and everything will work just fine.

**Comment by RedDevilus** [comment]
It's using Layer 2 and Layer 3 to be able to translate MAC devices and IP adresses. It's essentialy a bridge between Client and Server. It's like having no network card nor a router (simplified). So basically Dev9 is for playing online on community servers (in the past official servers)

**Comment by MelchiorGaspar** [comment]
ok so I don't need it then at this time...
I will close this then..
thanks for all the input everyone.
