### ISSUE TITLE
[Feature Request] GUI: Show full path visually to enduser.

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3520]
What i mean:
![image](https://user-images.githubusercontent.com/24227051/86389282-5e36fe00-bc96-11ea-8614-58cad7c544ec.png)

Long path names aren't fully displayed:
![image](https://user-images.githubusercontent.com/24227051/86389029-05fffc00-bc96-11ea-9efb-fded780cf5c2.png)

Having a long list of recently played games:
![image](https://user-images.githubusercontent.com/24227051/86389230-4cedf180-bc96-11ea-810f-ff21145d46a8.png)

I feel this is more like a WX problem when you resize the main emulation window. Maybe a good idea if we go to something like QT?

**Comment by refractionpcsx2** [comment]
This is now in Qt
![image](https://user-images.githubusercontent.com/6278726/170285470-139f757b-59d6-4fba-b6bd-70ae548065ab.png)
