### ISSUE TITLE
Spy Hunter - Parts of the loading screen disappear when going into the GSDx plugin settings

### ISSUE THREAD

**Issue by MonJamp** [PCSX2/pcsx2#3521]
***PCSX2 version:*** v1.7.0-dev-102-g3269c58c8

***PCSX2 options:*** Safest preset

***Plugins used:*** Tested using default GSDx settings

***Description of the issue:*** When loading a level and going into the GSDx plugin settings then exiting the settings, parts of the loading screen disappear.

Before going into plugin settings:
![2020-07-02 19_41_06-Slot_ 0 _ Speed_ 100% (60 03) _ NTSC _ Limiter_ Normal _ GSdx OGL HW _ 1920x1341](https://user-images.githubusercontent.com/7116269/86420815-5b8bd700-bc9d-11ea-9511-56fda4c6e619.png)

After exiting plugin settings:
![2020-07-02 19_40_28-_PAUSED_ Slot_ 0 _ Speed_  88% (52 47) _ NTSC _ Limiter_ Normal _ GSdx OGL HW _ ](https://user-images.githubusercontent.com/7116269/86420817-5d559a80-bc9d-11ea-9a0d-878680097ca6.png)

***How to reproduce the issue:*** Use either OpenGL or Direct3D hardware renderer. When loading a level go into the GSDx plugin settings then hit cancel.

***Last known version to work:*** Unknown, the problem also exists on 1.6 stable

***PC specifications:*** CPU: Ryzen 5 3600 GPU: R9 390 OS: Windows 10

**Comment by MrCK1** [comment]
Do these missing portions return when you exit the dialog? What you're describing is often a common behavior because the plugin state is suspended when the dialog opens.

**Comment by MonJamp** [comment]
While the plugin settings are still open the loading screen looks fine but when I exit the dialog everything disappears and only the loading bar remains.

**Comment by tadanokojin** [comment]
Issue isn't the suspend while dialog is open, it's the reset after it closes.
Cache and everything gets reset.

It's indeed a common issue. Jak has a similar problem in it's pause menu.

I didn't look into it specifically yet but I think it's related to local -> host transfers. Or maybe we don't invalidate rt back into gs memory before the reset (and the draw is only done once).

**Comment by iMineLink** [comment]
We could read back all the targets (in reverse order maybe) before resetting GSdx TC, that is a good catch.

**Comment by refractionpcsx2** [comment]
This is now resolved, however if you adjust any settings it will clear out the screen, unless you enabled the "Preload Frame" renderer fix.

But this would need testing on the game to make sure it doesn't cause any further problems if you want that always enabled. But as far as this issue goes, it's resolved.
