### ISSUE TITLE
[Feature Request] PS2 to PSP connectivity emulation (via PPSSPP/JPCSP emulator)

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#3527]
Also got posted on PPSSPP github (https://github.com/hrydgard/ppsspp/issues/13098) but it would be nice if there was a way to get connectivity between ppsspp/jpcsp and pcsx2 for games that uses this functionality.
A partial list of supported games is here : https://www.reddit.com/r/ps2/comments/atwi34/list_of_ps2_games_with_psp_connectivity/
A similar thing is done on Dolphin to get GC to GBA connectivity by using the VBA-M emulator.

**Comment by mitch03** [comment]
this would be amazing to have!

**Comment by lightningterror** [comment]
Low priority, if someone is willing to implement it they are free to do so.

**Comment by AmyRoxwell** [comment]
Checked this on latest nightly, sadly not plans for something like this to be implemented soon

**Comment by foxsevent** [comment]
It maybe possible that connecting PCSX2 to PPSSPP isn't needed for this, only for PCSX2 to mimick a PSP and it's file structure thru the USB host.

From what I remember how this worked you connected a PSP to the PS2 with a USB cable then you enabled mass storage device in PSP which was used to copy files to a PC, and then on the PS2 the game would check the save data folder on the PSP for specific saves and if found would unlock extras in the PS2 game.
