### ISSUE TITLE
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)

### ISSUE THREAD

**Issue by denn0n** [PCSX2/pcsx2#3542]
PC specifications:
AMD A8-7410 APU with AMD Radeon R5 Graphics 8 GB Ram

Hi In a Fresh Install in Fedora 31 From rpm-fusion repo, I can't run it whit the messages

 `Opening plugins...
	Opening GS
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
Failed to create the opengl context. Check your drivers support openGL 3.3. Hint: opensource drivers don't`

I have Change the Gs to 

GSdx (GCC 9.3.1 SSE4.1/AVX) 1.2.0 [libGSdx-SSE4]
OpenGl (hardware)
OpenGl (Software)
Same result and 
GSdx (GCC 9.3.1 SSE2/AVX) 1.2.0 [libGSdx] 
OpenGl (hardware)
OpenGl (Software)

I was reading about 

libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)

but it is not to much i found something regarding the module was blacklisted 
so  

`grep -H radeon /usr/lib/modprobe.d/*`
`/usr/lib/modprobe.d/dist-blacklist.conf:blacklist radeonfb`

I remove "blacklist radeonfb" from /usr/lib/modprobe.d/dist-blacklist.conf reboot and try again whit same result 

I link /usr/lib64/dri/ where radeonsi_dri.so radeon_dri.so radeonsi_drv_video.so are to /usr/lib/dri same result 

how i could fix this ?

**Comment by tadanokojin** [comment]
Did you try any other GL application?
It doesn't really sound like an issue on our end.

**Comment by denn0n** [comment]
Yes i imagine that was the case any ways a long shot see if some one could help here i will try in fedora forums thank you !
