### ISSUE TITLE
[GSDX-SW] BIOS glitch on Playstation 2 logo

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#3543]
The playstation 2 logo drops off to the bottom of the screen near the end of its display. Issue was fixed in HW renderer about a year or 2 ago, but has been present in SW throughout.

Tested in stable 1.6.0 and dev 1.7.0-dev-120-g715672481

All defaults used except for GSDX-SW renderer. 
Interpreter, recompiler, and all rounding and clamping modes have no effect.

Attached are the emulogs and video recording of both sw and hw renderers, as well as a gs dump.

Windows 10
Intel Haswell CPU
Intel GPU, but also occurs on another system with an nvidia 1080ti gpu.

[gsdx-sw.zip](https://github.com/PCSX2/pcsx2/files/4916280/gsdx-sw.zip)
[gsdx-hw.zip](https://github.com/PCSX2/pcsx2/files/4916281/gsdx-hw.zip)
[gs-dump_sw.zip](https://github.com/PCSX2/pcsx2/files/4916315/gs-dump_sw.zip)
[gs-dump_hw.zip](https://github.com/PCSX2/pcsx2/files/4916316/gs-dump_hw.zip)

**Comment by tadanokojin** [comment]
Duplicate #3485
