### ISSUE TITLE
Rogue Galaxy Vedan out of bounds glitch [possible automatic workarounds]

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#3544]
Wondering how easy it would be to set the EE/IOP clamping to full and the VU clamping to none, as listed in the [wiki](https://wiki.pcsx2.net/Rogue_Galaxy), by default in the gameindex.dbf and switch back to the standard defaults when a cutscene plays to avoid the video and audio glitches caused by the adjusted clamping modes?

Automatic cutscene detection seems to already be possible, and as long as the adjusted clamping modes don’t cause any other issues in the game, would essentially fix the issue with no user interaction required upon reaching that area.

**Comment by kozarovv** [comment]
Which version of game you have (PAL/NTSC - U/J)? Do you have savestate close to place where it happen to test eventual solution?

**Comment by ichee** [comment]
NTSC-U

Disc image CRC-32 is 044F1164.

Clamping settings listed in the wiki link above for fix in that area works to prevent out of bounds jumping glitch, but causes parts of train to occasionally disappear, so I'm not sure if it would cause issues in other areas of the game, aside from cutscenes.

As for your suggestion, I'm not sure if I understand what you mean.

Memory card save is near the train at the entrance to Myna. Just walk near it when the train shows to reproduce.

[memcard.zip](https://github.com/PCSX2/pcsx2/files/4922666/memcard.zip)

**Comment by ichee** [comment]
O.K.

I think I figured out what you meant. Just to be sure, you meant adding that patch to the gameindex.dbf like this:

---------------------------------------------------

Serial = SCUS-97490
Name   = Rogue Galaxy
Region = NTSC-U
Compat = 5
[patches = 0643F90C]
          patch=1,EE,00124898,word,3442fffe
[/patches]

---------------------------------------------------

If so, I've not noticed any glitches in that area for about 20 minutes, and cutscenes appear to be fine.
Only thing I have noticed so far is occasional dropped audio samples in the BGM, though I'm not yet sure if it has anything to do with the patch.

All default settings used, including clamp modes.

Great find with this. If you haven't already, you should consider submitting a PR with this patch for the GameDB.

**Comment by ichee** [comment]
I went ahead and created a PR for this.

If you're able to, please test in case an issue comes up that I missed.

Thanks.

**Comment by ichee** [comment]
Fixed in 543bb22.
