### ISSUE TITLE
Diablo PS1 - Hangs before main menu after recent commit

### ISSUE THREAD

**Issue by brotalnia** [PCSX2/pcsx2#3557]
***PCSX2 version:***
pcsx2-v1.7.0-dev-130

***PCSX2 options:***
All default settings. Using OpenGL Software rendering.

***Description of the issue:***
Diablo hangs a few seconds after loading the iso. The issue seems to have been introduced in either 105478aa6d6759a3eb01ff085774eccca19db7f1 or e04d86ad3995d822a355a911cadaa2ffe0592649 because the commit before that 1e1d455a4d0640b4097ba42ea953c30c9be70980 runs fine.

```
<<<<<<HUNG timeout=0:0:30>>>>>>
PGIF=0010002c STAT=56022000 code=-1(ffffffff)
d1_chcr=70000045 vif1_stat=00000040 gif_stat=00000000
stack_check=76543210|76543210
```

***How to reproduce the issue:***
Try loading Diablo for the PS1. Game will hang before you get to the main menu.

***Last known version to work:***
https://github.com/PCSX2/pcsx2/commit/1e1d455a4d0640b4097ba42ea953c30c9be70980

***PC specifications:***
CPU: I7-6700K GPU: GTX 660 OS: Windows 10

[log.txt](https://github.com/PCSX2/pcsx2/files/4941248/log.txt)
[Diablo (2020-06-18 10-53-16).zip](https://github.com/PCSX2/pcsx2/files/4941249/Diablo.2020-06-18.10-53-16.zip)

**Comment by kenshen112** [comment]
@brotalnia We prefer to keep the git issues surronding ps1 mode to a minimum. If you want to post compatibility changes with it or any issues your experiencing. https://forums.pcsx2.net/Thread-PSX-Mode-Unofficial-Compatibility-List is the place to do it

**Comment by brotalnia** [comment]
Okay, thanks. It seems to be fixed after the latest @refractionpcsx2 commit.

**Comment by refractionpcsx2** [comment]
yeah, sorry about that. I was overthinking it :)
