### ISSUE TITLE
[Interlacing Behavior Issue]KOF Nests

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#3563]
There is an interlacing behavior bug on this game.

PCSX2 normally determines the best interlacing method.

"Auto" is :  
-"None" for the games that report interlace but really are progressive
-"Blend" for games that are field rendered

This game is a compilation, menus are field rendered but the 3 games are progressive (reported as interlaced) : 
-KOF 2000 & KOF 2001 have "Auto" set to "None"
-KOF 99 have "Auto" set to "Blend".

Changing "Auto" to "None" manually solves this but it would be great to check what is wrong in the interlacing behavior.

This was tested on Windows 10.

**Comment by bositman** [comment]
Tried a no interlace code?
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=611209&highlight=kof#pid611209

**Comment by Immersion95** [comment]
The interlace code is not needed here as "None" does the job. The only needed change is how "Auto" behaves in Kof 99

**Comment by tadanokojin** [comment]
You need to properly fill out the issue template (including GS dump) instead of just ignoring it every time.

**Comment by Immersion95** [comment]
Hi, sorry I will do it as soon as I have time. Should I close it and reopen it then ?

**Comment by tadanokojin** [comment]
Nah it's fine. Just fill it out when you have a moment. Really would like the dump.

**Comment by refractionpcsx2** [comment]
You can get a template from here: https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by Immersion95** [comment]
Here are the requested information :

Graphics issue:

Issue title: NeoGeo Online Collection Vol. 7 - The King of Fighters - Nests Hen (Japan) - Interlacing issue in KOF99

-PCSX2 version: PCSX2 1.7.0-0 - compiled on Aug 15 2020

-PCSX2 options: Defaults

-Plugins used: GSdx, SPU2-X, LilyPad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

-Plugin settings: Tested GSdx DX11/GL hardware and software renderers.

-Description: Interlacing for KOF99 problem


[Nouveau dossier.zip](https://github.com/PCSX2/pcsx2/files/5482495/Nouveau.dossier.zip)

**Comment by Immersion95** [comment]
My bad, the problem was me realising that Kof99 is indeed interlaced hmin this compilation
