### ISSUE TITLE
Crash Twinsanity crashes with Assertion Failure in the game

### ISSUE THREAD

**Issue by lasers** [PCSX2/pcsx2#3566]
***PCSX2 version:***
pcsx2-git 1.7.0.r138.d1af8cd-1

***PCSX2 options:***
  Defaults, I think.

***Plugins used:***
  Defaults, I think.

***Description of the issue:***
  PCSX2 crashes with `Assertion Failure` dialog. I have played this game from the start. After being unable to continue with the last state, I downloaded 100% completed gamesave only to find that it does the same thing later. The problem could be with the level itself, but I have already used (saving + loading states) on this level several times up to the defeating boss cutscene... then now again (saving + loading states) with 100% completed gamesave.

```
/tmp/pcsx2-git/src/pcsx2/common/src/Utilities/Linux/LnxHostSys.cpp(70) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    EE Core
    Condition: false
    Message:   Unhandled page fault @ 0x00000000

Stacktrace:
[00] 0x0x5691fb4e                                
[01] __kernel_rt_sigreturn                       
[02] 0x0x56612676                                
[03] 0x0x5661c794                                
[04] 0x0x5661c7fd                                
[05] 0x0x58dd4012                                
[06] 0x0x567602e9                                
[07] 0x0x5686f323                                
```

***How to reproduce the issue:***
1) Visit a link https://gamefaqs.gamespot.com/ps2/920119-crash-twinsanity/saves/26290  
2) Download a gamesave. 
  ```
PlayStation 2 PS3 Virtual Memory Card Save (ZIP) (North America)
100% Complete, All Gems, All Crystals, Everything Unlocked.
```
3) Move the gamesave into the memory card. I used mymc.
4) Load the game. Load `Academy of Evil` gamesave.
5) Start playing. See Cortex cutscene. Try `PCSX2` saving / loading state. 
6) `Assertion Failure` dialog appears. The whole thing crashes.

***Last known version to work:***
Unknown.

***PC specifications:***
Intel Core i5-9400F CPU @ 2.90GHz × 6
GeForce GTX 1660 Ti
Manjaro Linux

**Comment by bositman** [comment]
So you mean that the game crashes when saving a state? It isn't clear from your report

**Comment by lasers** [comment]
I used to think it did with my gamesave from scratch because I was saving it at that time. Getting out _(after completing a boss defeat)_ seems to trigger a same crash with 100% completed gamesave without saving.

I attached `sstates/`[SLUS-20909 (B318AA3C).00.zip](https://github.com/PCSX2/pcsx2/files/4972875/SLUS-20909.B318AA3C.00.zip). Get on a floating platform to get out.

**Comment by MrCK1** [comment]
@lasers just to clarify, could you also check on the latest dev build to see if it's still active? Also does this issue happen if you're only loading from memory card - without loading any savestates?

**Comment by lasers** [comment]
>Crash Twinsanity has a wide range of glitches, and it is known as the glitchiest Crash game ever made, with over four hundred different glitches, ranging from minor, to a game crash. _[[source]](https://crashtopia.fandom.com/wiki/Crash_Twinsanity_Glitches)_

See the video and highlighted comment.
https://www.youtube.com/watch?v=57yzbK6_gl8&lc=UghGGefNNgPOKXgCoAEC

It's definitely an issue with the game and maybe nothing with PCSX2. I wonder if this issue should be closed.
