### ISSUE TITLE
Issues with very large PNACH files (some codes are ignored)

### ISSUE THREAD

**Issue by Nicholas-Steel** [PCSX2/pcsx2#3573]
***PCSX2 version:***
1.5.0 revision 3200
1.6.0
1.7.0 dev-143

***PCSX2 options:***
Irrelevant/changes have no effect on the issue.

***Plugins used:***
Irrelevant/changes have no effect on the issue.

***Description of the issue:***
When working with very large PNACH files (55,000+ cheats), some of the codes are ignored and the codes that are ignored vary depending on the order the codes are loaded in. Multiple people have noticed the issue.

***How to reproduce the issue:***
**1)** Acquire a copy of Kingdom Hearts 2: Final Mix (Japanese exclusive game)
**2)** Follow the setup guide I've written here to apply a Randomizer mod, I use the CrazyCatz translation (On the Valaxor website leave mostly everything on default, turn off Critical Mode): https://bit.ly/KH2FM_Randomizer_Setup_Guide
**3)** Test the game after following the guide.
**4)** You should begin with a choice of a Staff, Sword or Shield. Once you've made a choice you should be taken to the Garden of Assemblage with no AP Boost items in the Inventory > Stock menu. Keyblades you find while playing the game will correctly have Abilities assigned to them.
**5)** Rename the PNACH files to change the order they are loaded in (PCSX2 loads files alphabetically afaik). Now when you enter the Garden of Assemblage you will start with 48 AP Boosts but Keyblades you find in the game won't have any Abilities assigned to them.

***Expected outcome***
All cheats to be applied... and for them to be applied consistently.

***Last known version to work:***
Unknown, 1.50 Revision 3200 is the first to claim support for unlimited cheat codes though. Maybe no one had previously come up with a scenario that involved a lot of cheat codes so it was never fully tested?

***PC specifications:***
 Windows 10 - 2004 x64 | Ryzen 3700X | ASUS Crosshair VIII Hero (WiFi) | MSI 1070Ti | 16GB 3600MHz RAM

**Comment by refractionpcsx2** [comment]
55000 line patch files?? Shouldn't you just patch the ISO when it gets to that size?

We are looking in to this, but that seems like a flagrant abuse of the patching system, it was only meant for fixes and some cheats, up to like 100 lines.

**Comment by Nicholas-Steel** [comment]
Hmmm nevermind and sorry for wasting your time. It turns out multiple files were messing with the same stuff and conflicting.

**Comment by refractionpcsx2** [comment]
okay, thanks for letting us know.
