### ISSUE TITLE
Rez line scalling issue in OpenGL 

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#3574]
https://drive.google.com/file/d/17IeaTul3fF9ndVD8CxpZOC0PaiGCmBsM/view?usp=sharing
here's GSDump
Older one's OGL HW at 3x scaling
Newer one's D3D HW at 3x scaling

Version affected: latest dev build

**Comment by knight-ryu12** [comment]
D3D does not have weird line scaling.

**Comment by KrossX** [comment]
Please try this pull request #3575, and see if it's better.

**Comment by knight-ryu12** [comment]
Looks good to me… it works.
