### ISSUE TITLE
Build v1.7.0-dev-114-g210336d8c breaks DX11 renderer on Windows 7

### ISSUE THREAD

**Issue by OCRBonk** [PCSX2/pcsx2#3581]
I know Windows 7 is officially not supported now  so I don't have much hope. But whatever changes were made in this build now causes the DX11 render to crash on boot. It's not related to any settings as deleting GSDX.ini and letting it auto populate default settings does nothing. The same settings on OpenGL work just fine with no issues.
I tested it in Windows 10 and it works fine(I use Windows 7 because of Scanline Sync), so obviously Windows 7 is old junk and does something that this doesn't like and now doesn't work.

"gsdx-d3d11: Modernize swapchain and device creation Updates the d3d device and swapchain creation to more modern methods. - Use CreateDXGIFactory2 to create the factory and store in member - Use CreateSwapChainForHwnd - Add messages for failures to the console - Some general formatting improvements"

**Comment by refractionpcsx2** [comment]
Yes we know about that and as we have taken the stance to drop Win 7 support, even though fixing that one commit would be simple we decided we aren't going to fix it for Win7 since there are other changes in the works which will further break Win 7 compatibility, so it really would be a waste of time.

We recommend Windows 7 users stick to earlier versions of PCSX2 or upgrade their OS to Windows 8.1 or above (or go to Linux). if you really must use the latest version of PCSX2 you will need to use an older version of GSDX and probably SPU2-X to maintain compatibility for now.

**Comment by OCRBonk** [comment]
This is about what I expected, but it couldn't hurt to ask.  (As for further builds. Would just copying the SPU2/GSDX dlls from an older version over the newer build make it sufficient to work? Just without the improvements to those plugins?)

Honestly using Windows 10 wouldn't be an issue for me if we could disable the compositor so I could use Scanline Sync in games where the reduction in latency is noticeable enough to make a difference for gameplay.  Of course a FSE display mode would accomplish the same thing because then you could use Scanline Sync instead of Vsync. For games where the latency is less of an issue then it's not as important. 

Thanks for taking the time to reply.

**Comment by refractionpcsx2** [comment]
Maybe there is solutions to fix your Win10 situation? IDK, but you could update to 8.1 if Win10 isn't good enough for you, that is enough for PCSX2.

As for the mixing of plugins and emulator, yes, as it stands at the moment, using the older GSDX and SPU2-X plugins will allow you to use the latest development version of the emulator.  How long that will continue I don't know, however there's no core changes outstanding which will break Win7 compatibility further, but that could change in the future.

**Comment by tadanokojin** [comment]
[The DXGI flip model is designed to reduce the latency of the compositor](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-flip-model) and Win10 already detects borderless fullscreen and bypasses the compositor so there is no reason to use FSE.

If you are interested in low latency solutions then you can check out the pr ref mentioned would break win7 further: https://github.com/PCSX2/pcsx2/pull/3549

**Comment by OCRBonk** [comment]
Is there a build with Flip Model enabled yet so I can test this? It definitely could make FSE irrelevant if it works as you say.
As is now, In Windows 10 with PCSX2 in borderless I still see no tearing, but unless either Vsync is enabled in the settings (Or EnableVsyncWindowFlag is turned on) the frame pacing is total garbage and there is constant stuttering. And enabling one or both of those definitely feels like it increases the latency in games that already have somewhat high input lag so they feel even more sluggish. (Such as Dark Cloud 2)

Again though, if it works as suggested then my only real reasons for using PCSX2 with Windows 7 would be entirely irrelevant. (Scanline Sync +Frame limiter disabled in PCSX2 also helps get around the 59.94 intended framerate vs actual PC monitor refresh mismatch that can cause stuttering as well. Being able to use it with the compositor bypassed in W10 would be great)

**Comment by tadanokojin** [comment]
EnableVsyncWindowFlag will cause tearing for GL under the same conditions as my DX pr as it causes the GL driver to enter a pseudo-FSE mode. It's really kind of a hack, though.

For pacing on GL, some people will disable the frame limiter and limit it with RTSS as an alternate solution.

flip model build is here (note it is WIP): https://ci.appveyor.com/project/gregory38/pcsx2/builds/34148496/job/yvyl587h554gw7p2/artifacts

**Comment by OCRBonk** [comment]
Sorry for the late response. But i'll test this soon and write back my results!
