### ISSUE TITLE
Missing TT fonts under Arch

### ISSUE THREAD

**Issue by beaumanvienna** [PCSX2/pcsx2#3592]
Suggested solution

Add to PKGBUILD:

 * `sed -i 's/\/usr\/share\/fonts\/truetype\/freefont\/FreeSerif.ttf/\/usr\/share\/fonts\/gnu-free\/FreeSerif.otf/g' plugins/GSdx/GSdx.cpp`
 * ` gnu-free-fonts` to the dependencies

**Comment by orbea** [comment]
Slackware also has this problem, the build script works around it with this.
```
sed -i \
  's|truetype/freefont/FreeSerif.ttf|TTF/LiberationSerif-Regular.ttf|' \
  plugins/GSdx/GSdx.cpp
```
I would prefer to not depend on `gnu-free-fonts`.

**Comment by beaumanvienna** [comment]
Ok, let me find the corresponding package on Arch and test it again. Thanks!

Do we have defines for Arch and Slackware to change it in the software? It would give people cloning and building directly from Github a better experience.

**Comment by beaumanvienna** [comment]
Yes, your suggestions works. Looks a bit nicer...

package: https://www.archlinux.org/packages/community/any/ttf-liberation/files/

The path is slightly different. The sed command would be:

`sed -i 's|truetype/freefont/FreeSerif.ttf|liberation/LiberationSerif-Regular.ttf|' plugins/GSdx/GSdx.cpp`

**Comment by orbea** [comment]
This could maybe be solved in pcsx2 by either:

* Ship a font with pcsx2 so that its always available.
* Or maintain a list of known font paths and iterate through them until one is found.
