### ISSUE TITLE
DQ8 Running really slow and choppy.  EE hitting at 28% but GS hitting at 94%

### ISSUE THREAD

**Issue by Solverbolt** [PCSX2/pcsx2#3594]
***PCSX2 version:***
Stable Build 1.6.0
- **Notes**:
Trying to play Dragon Quest VIII from PS2.  Just started and already noticing that for some reason the GS is maxing out at 94% and the game gets really sluggish, where the voice dialog is choppy and sounds like someone talking in super slow motion

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)`` No changes currently, tried a few, like disabling MultiCore use and other such changes, like the all else fails. VU0 and 1 from recompiler to legacy and back, and a mix of.  Tried changing slow motion adjust, had no effect. Tried changing EE cyclerate but that did not help.  Also went through and tried multiple settings in the Game Fixes section in manual and also tried Preset, but preset never enabled anything. 

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
Asus Z8PNE-D12x Motherboard.  Xeon E5620 2.4GHz 4 core, 8 Logic Processor, 32 GB Ram. Geforce 750 TI 4 GB Graphics Card (one of the very hard to ones, took me 2 years to find it, only because they started pushing a 2Gb version that sucked)

**Comment by tadanokojin** [comment]
[Your CPU](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+E5620+%40+2.40GHz&id=1249) is below the minimum requirements.
[Please use the forums](https://forums.pcsx2.net/) for support requests.

**Comment by Solverbolt** [comment]
wow. Fuck you too then. now I know why i never bothered to contemplate ever Supporting what you guys were doing.
