### ISSUE TITLE
Tekken 5 stage bug of sun

### ISSUE THREAD

**Issue by Javed-Iqbal-1** [PCSX2/pcsx2#3599]
![gsdx_20200814204052](https://user-images.githubusercontent.com/57389023/90267501-139cca00-de6f-11ea-8e33-614c45ebaa6f.png)

![Capture](https://user-images.githubusercontent.com/57389023/90267958-b81f0c00-de6f-11ea-9de4-0a5b8f231207.PNG)
![23](https://user-images.githubusercontent.com/57389023/90268240-2663ce80-de70-11ea-9806-ff14c5e5acd4.PNG)

Bug appears when character goes in front of sun and fps also drops from 60 to 42

**Comment by lightningterror** [comment]
Duplicate #2766
