### ISSUE TITLE
PCSX2Bonus integration?

### ISSUE THREAD

**Issue by Silentghost14** [PCSX2/pcsx2#36]
I was just wondering if maybe you have considered incorporating PCSX2Bonus into the official build of PCSX2. Similar to PPSSPP to make game organization and navigation more user friendly?

**Comment by lightningterror** [comment]
Going to close this since there has been no progress on PCSX2Bonus for a few years.
Plus there's also what boist said.

Spectabis is tho.
https://forums.pcsx2.net/Thread-Spectabis-Advanced-Game-Launcher-Frontend
