### ISSUE TITLE
Suggestion  (change the gui for Controllers)

### ISSUE THREAD

**Issue by Javed-Iqbal-1** [PCSX2/pcsx2#3600]
![Capture](https://user-images.githubusercontent.com/57389023/90269429-0c2af000-de72-11ea-9616-07ae2c42e19e.PNG)
![gamepad](https://user-images.githubusercontent.com/57389023/90269441-10570d80-de72-11ea-8582-b52cd8fcd9ad.PNG)

Why not PCSX2 Team changing the gui for controllers like this one as shown in RPCS3 Emulator.
Its difficult to configure and irritating.....

**Comment by RedDevilus** [comment]
LilyPad is a plugin, PCSX2 uses WX as a GUI.
RPCS3 uses QT which is more accessible to change stuff and they have more people for UI/UX.

**Comment by Javed-Iqbal-1** [comment]
Nothing is missing  Everything is OK! But I want that the picture of ps2 controller should be there in center and buttons layout should be around there .
PS1 Emulator Epsxe game pad configuration is also better as we compare it to  pcsx2.
I Think Epsxe may not be programmed in advance coding language as compare it to pcsx2, Finally I suggest that gui should be improved so that it should be easy to understand and it looks and feels Good for users.

![ED93Bqn](https://user-images.githubusercontent.com/57389023/90289381-2f1acb80-de95-11ea-9b9a-b1abc810ddf0.jpg)

**Comment by orbea** [comment]
It looks like this on Linux, I guess this problem is lilypad only?

![1](https://i.imgur.com/FQRTWhG.png)

**Comment by tadanokojin** [comment]
yeah just lilypad.

**Comment by MrCK1** [comment]
Given the ongoing work with merging plugins and redesign, I'm going to close this for now since the GUI will possibly get poked at some point in the near future.
