### ISSUE TITLE
Onimusha 3 blood decal and shadows on ground Z Fighting, also Artifacting on right Side of Screen using Special/-Aggressive and HUD Misalignment issue

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#3609]
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``
pcsx2-v1.7.0-dev-161-g850efdc69-windows-x86
- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.
settings at default

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.
all at default
***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
Onimusha 3 NTSC, flickering blood decals and shadows on ground in opengl hardware as well as software mode
heres a gsdump with full video and pic>   
https://www5.zippyshare.com/v/oOqLXUE6/file.html

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
walking around honoji temple in increments back and forth and youll see the shadows flickering or disappearing same goes for the blood decals

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``
none

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
doesnt matter what pc hardware you use ive tried

**Comment by MrCK1** [comment]
@washingleavesandthensome23-434  Please fill out the template properly and link your materials to a place where the URL doesn't expire.

**Comment by washingleavesandthensome23-434** [comment]
ok lets try this again ....thought this was on a roll already damn, dumps with pics here>

http://www.mediafire.com/file/zrv8kjm86l08kk5/gsdx_20200819152844.gs.xz/file
http://www.mediafire.com/view/ipapsur0epvzusx/gsdx_20200819152841.png/file
http://www.mediafire.com/view/czaxxvaq1woj3u1/gsdx_20200819152844.png/file

videoclip showing issue in action..will post in a few its transcoding  >

**Comment by washingleavesandthensome23-434** [comment]
so you got feedback , a update would be neat @MrCK1

**Comment by MrCK1** [comment]
Sorry, there's no additional information I can give at this time.

**Comment by washingleavesandthensome23-434** [comment]
been a while would still love a fix for this...appreciated guys

**Comment by washingleavesandthensome23-434** [comment]
k, so some updated dumps there >

https://www.mediafire.com/file/s0inenhie5vks26/snaps_%2528oni3%2529.zip/file

as one can see theres an odd artifact on the right of the screen now as well ...

**Comment by washingleavesandthensome23-434** [comment]
as said

**Comment by Tzerinas** [comment]
Regarding your question in the PR: Nah, its fine. I trust you. I was mainly interested in it for future GameDB changes. 

Hopefully those vertical lines and shadow problems can be fixed down the line.

**Comment by prafullpcsx2** [comment]
@washingleavesandthensome23-434 Can you upload a savestate using pcsx2 1.6 where the actual flickering issue occurs?

**Comment by washingleavesandthensome23-434** [comment]
sure my man ....heres my memory cards ....just load both of them .....theyre full of saves 

simply select the first save slot , aka the temple level is great for this kind of stuff as you can see in my video 

https://www.mediafire.com/file/r1mg8wmxfml9b5b/memcards.zip/file

**Comment by prafullpcsx2** [comment]
This looks like z fighting. Would be interesting to check if a little bit of this is also present on real ps2 or not,.

**Comment by washingleavesandthensome23-434** [comment]
also , heres a showcase of the game on original ps2   https://www.youtube.com/watch?v=P2Ad3NdDRsg

one can clearly see that the HUD isnt misaligned at about half length of health/magic bar.....hope this also can be fixed 

this can be clearly seen in my most recent 2 screenshots also

**Comment by washingleavesandthensome23-434** [comment]
> This looks like z fighting. Would be interesting to check if a little bit of this is also present on real ps2 or not,.

actually yes it is ....not sure how possible it is to fix

**Comment by washingleavesandthensome23-434** [comment]
heres a good showcase of both 
Z fighting galore and also what happens when not using Special/-Aggressive

https://vimeo.com/707657979

**Comment by washingleavesandthensome23-434** [comment]
Hope issue gets resolved soon , appreciate the team's work for sure

**Comment by lightningterror** [comment]
Closing in favour of meta issue.
