### ISSUE TITLE
Vampire Panic - Graphical distorations with hardware renderer

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#3610]
***PCSX2 version:***
both stable 1.6.0 and the latest dev build 1.7.0

***PCSX2 options:***
default options with both hardware renderers and using the "safest" preset

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
default plugins

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like 
I have provided a GS dump of the issue 
[gsdx_20200819232917.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/5099122/gsdx_20200819232917.gs.xz.zip)

***Description of the issue:***
distorations of the graphics.
Screenshot : 
![gsdx_20200819232917](https://user-images.githubusercontent.com/33392696/90686566-33b7f900-e274-11ea-9cc6-dd262001d6fc.png)
Also this is using the recently released english fan translation patch.
***How to reproduce the issue:***
Just play the game by using any of the hardware renderers.
The game works fine with the software renderer.

***Last known version to work:***
no idea but it happens in both 1.6.0 and latest dev build.

***PC specifications:***
CPU: Intel i7 8550U
GPU: Radeon 530.
(yeah its a laptop but it runs pretty well with it).

**Comment by tadanokojin** [comment]
Ouch, looks like the game is decoding the result of a shuffle with sprites to deswizzle it.

**Comment by FuxorLuck** [comment]
Here is a hack that removes this Effect

//Remove Broken Effect
patch=1,EE,203FC3E4,word,00400000

**Comment by Mrlinkwii** [comment]
still an issue as of v1.7.4508
![image](https://github.com/PCSX2/pcsx2/assets/17685135/5d020ba6-465f-4c85-b35f-e7c66c020f9d)

**Comment by Mrlinkwii** [comment]
is a bit changed on v1.7.4867 

![image](https://github.com/PCSX2/pcsx2/assets/17685135/4c05cc91-48b7-4409-a0ac-6f3af455bf4d)

**Comment by Mrlinkwii** [comment]
still broken on v1.7.4993


![image](https://github.com/PCSX2/pcsx2/assets/17685135/4412c7c7-85c2-48fb-ae3f-6625ef3d841f)
