### ISSUE TITLE
Feature Request > 8K Internal upscaling aka 12x instead of only 8x Support 

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#3612]
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``
latest dev build
- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
currently theres only 8x internal upscaling support please add support for 12x aka 8k , thanks

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
as said above

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``
never has been available 

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
dont matter

**Comment by tadanokojin** [comment]
You can do higher than 8x by modifying GSdx.ini yourself. I don't recommend it and do it at your own risk.

**Comment by washingleavesandthensome23-434** [comment]
nah tried that ...am getting vfx flickering on certain effects if i do custom aka set preset to 0

**Comment by lightningterror** [comment]
We had 10x and 12x for a short period but decided to remove it as having textures of that size can/will cause issues.

**Comment by washingleavesandthensome23-434** [comment]
ok? even with enough vram? dont understand but ok im no expert either lols

**Comment by tadanokojin** [comment]
Not vram issue, API has limit on texture size.

**Comment by washingleavesandthensome23-434** [comment]
would it be too much of an issue just to increase in API? or use alternative API?

**Comment by tadanokojin** [comment]
We pick the maximum it based on user feedback and other things so where it is is where it is for now. Maybe when we drop dx10 we can look at raising it again. Or maybe in the future we can have a config gui that's responsive to the current api/gpu selection. Both are kind of out of scope here.

But as I said, all the gui does is save a value to the ini. You can modify it yourself. `upscale_multiplier` I think it is.
