### ISSUE TITLE
[REQUEST] Support for Namco Arcade systems based on PS2

### ISSUE THREAD

**Issue by BroKill** [PCSX2/pcsx2#3613]
As the title says, would be nice to play the Arcade games based on Namco System 246/256 with PCSX2.

Someone loaded the Namco bios in PCSX2 and this is a sign that maybe is possibile :) 
It needs work from you devs and I can help with bios, roms and something else if you want.

Hope you guys will consider this because there are many great games for that Arcade system and there are millions of people who will die for that ( not joking, Arcade universe is so vast ).

PCSX2 got a great status...please, keep on rocking guys!!!

CHEERs

**Comment by FerocityVine** [comment]
I do support this PR, but it may already be possible.

The dongles from 246/256 are encrypted. Once they are decrypted, the BIOS may boot the inserted CHDs.
The only thing that needs to be done is CHD implementation.

Alas, it may never be. Although System 246 is just a fancy PS2, this is a PS2 specific emulator. So this feature may never get into official versions.

**Comment by kenshen112** [comment]
It's quite a bit more complicated than that. The dongles / security system as a whole uses a modified MagicGate system that prevents them from being read unless MagicGate is in some form or fashion decrypted or cracked. We're really not down with the legal implications around that since MagicGate is sony's propietary security system that's still in use in their consoles today afaik.

**Comment by FerocityVine** [comment]
I see. But as far as I am aware, MAME can already use System 246/256 dongles with any game from that platform that works. Perhaps it's not such a big deal? And if it is, it would be the best to stir away from it.

**Comment by kenshen112** [comment]
If they are they're probably cracking it. That said the legal implications of that are. MMMMMM

**Comment by kenshen112** [comment]
Also, you look like a pretty handy guy ;)

**Comment by FerocityVine** [comment]
> If they are they're probably cracking it. That said the legal implications of that are. MMMMMM
I mean, most companies do not mind but, eek regardless.

> Also, you look like a pretty handy guy ;)
Thanks? I suppose.

**Comment by BroKill** [comment]
> System 246 is just a fancy PS2, this is a PS2 specific emulator. So this feature may never get into official versions.

Devs here can start a specific build for the Arcade side, this is an idea to keep things separate I think.

Hope it will happen sooner than later.

CHEERs

**Comment by IamLegend447** [comment]
Is this still active, are the developers actually considering doing this?? Sorry, I'm new to this.

**Comment by IamLegend447** [comment]
> > System 246 is just a fancy PS2, this is a PS2 specific emulator. So this feature may never get into official versions.
> 
> Devs here can start a specific build for the Arcade side, this is an idea to keep things separate I think.
> 
> Hope it will happen sooner than later.
> 
> CHEERs

Is this still active, are the developers actually considering doing this?? Sorry, I'm new to this.

**Comment by F0bes** [comment]
> Is this still active, are the developers actually considering doing this?? Sorry, I'm new to this.

Relies on magic gate, as stated above. We don't know the legal implications about implementing magic gate, so no, I wouldn't consider this issue as being actively worked on.

**Comment by IamLegend447** [comment]
> > Is this still active, are the developers actually considering doing this?? Sorry, I'm new to this.
> 
> Relies on magic gate, as stated above. We don't know the legal implications about implementing magic gate, so no, I wouldn't consider this issue as being actively worked on.

I thought so.

**Comment by AnthonyRyuki** [comment]
After tinkering with the dongle files that the MAME team made, I noticed that they aren't actually MagicGate encrypted like the physical dongles are.

In fact, if you take one of those 8448 KB file dumps (not the 2-file dumps), rename its extension to .ps2, assign it to a Memory Card slot in PCSX2 and convert it, PCSX2 is able to dissect all of its files.

One of them's name ends with "LOAD", and it's the game's ELF.

**Comment by TheLostNinja** [comment]
> After tinkering with the dongle files that the MAME team made, I noticed that they aren't actually MagicGate encrypted like the physical dongles are.
> 
> In fact, if you take one of those 8448 KB file dumps (not the 2-file dumps), rename its extension to .ps2, assign it to a Memory Card slot in PCSX2 and convert it, PCSX2 is able to dissect all of its files, just like a regular PS2 Memory Card image.
> 
> One of them's name ends with "LOAD", and it's the game's ELF.

Is it possible to fuse splitted dongle files into the single?

**Comment by AnthonyRyuki** [comment]
It is, but I don't know exactly how to do that. From my understanding, a byte from the smaller file should be inserted between every unknown number of bytes from the bigger file.

That's no longer necessary though. Another PS2 emulator called Play! is implementing Namco System 2x6 emulation. Check it out :)

**Comment by lorizzuoso** [comment]
> > After tinkering with the dongle files that the MAME team made, I noticed that they aren't actually MagicGate encrypted like the physical dongles are.
> > In fact, if you take one of those 8448 KB file dumps (not the 2-file dumps), rename its extension to .ps2, assign it to a Memory Card slot in PCSX2 and convert it, PCSX2 is able to dissect all of its files, just like a regular PS2 Memory Card image.
> > One of them's name ends with "LOAD", and it's the game's ELF.
> 
> Is it possible to fuse splitted dongle files into the single?

It is possible but you would get "Boot file is not right" so you would get stuck either way

**Comment by lorizzuoso** [comment]
> It is, but I don't know exactly how to do that. From my understanding, a byte from the smaller file should be inserted between every unknown number of bytes from the bigger file.
> 
> That's no longer necessary though. Another PS2 emulator called Play! is implementing Namco System 2x6 emulation. Check it out :)

Play! is working on it but performance wise is far behind PCSX2,but people could fork it and add it of course not to master but in their own builds

**Comment by RedDevilus** [comment]
> > It is, but I don't know exactly how to do that. From my understanding, a byte from the smaller file should be inserted between every unknown number of bytes from the bigger file.
> > That's no longer necessary though. Another PS2 emulator called Play! is implementing Namco System 2x6 emulation. Check it out :)
> 
> Play! is working on it but performance wise is far behind PCSX2,but people could fork it and add it of course not to master but in their own builds

Play / Purei has it's own codestyle which has a different base, so might not be that easy to port stuff. Several items can't be ported to each other. Not impossible to achieve but we will see.

**Comment by lorizzuoso** [comment]
> > > It is, but I don't know exactly how to do that. From my understanding, a byte from the smaller file should be inserted between every unknown number of bytes from the bigger file.
> > > That's no longer necessary though. Another PS2 emulator called Play! is implementing Namco System 2x6 emulation. Check it out :)
> > 
> > 
> > Play! is working on it but performance wise is far behind PCSX2,but people could fork it and add it of course not to master but in their own builds
> 
> Play / Purei has it's own codestyle which has a different base, so might not be that easy to port stuff. Several items can't be ported to each other. Not impossible to achieve but we will see.

Right,Play is done all through HLE so that could be an issue but if someone is open to do it than it would be cool

**Comment by refractionpcsx2** [comment]
As stated above, magicgate is required, and this is something we aren't going to go near for potential legal reasons. I'm sure somebody will fork it and do it, and they are welcome to do so.
