### ISSUE TITLE
[Feature Request] Add UI for configuring Hotkeys

### ISSUE THREAD

**Issue by Nicholas-Steel** [PCSX2/pcsx2#3631]
It would be greatly appreciated if we could get a UI for viewing/configuring hotkeys.

**Comment by IngwiePhoenix** [comment]
Would love that too as well as being able to remap them to a controller button (i.e. fast-forward directly on the controller)

**Comment by TomTurbine** [comment]
Will gladly give a +1 vote for this.

Setting up an emulationstation setup using a PS5 controller and trying to bind the Playstation button to exit back to the frontend.

Looking and can't find an option to close it.

**Comment by lightningterror** [comment]
Done on Qt, won't be done on wx.
