### ISSUE TITLE
PS2 VM Cannot Initialize -- SIB Target Issue

### ISSUE THREAD

**Issue by FerocityVine** [PCSX2/pcsx2#3643]
***PCSX2 version:***
v1.7.0-dev-56f2d30 [Latest - Only in 64-bit]

***PCSX2 options:***
Irrevelant

***Plugins used:***
Irrevelant

***Description of the issue:***
PS2 Virtual Machine can't be initialized. SIB Target is too far away.
[Screenshot](https://media.discordapp.net/attachments/734541652617854986/749482182271303706/unknown.png)

***How to reproduce the issue:***
Compile and run the x64 version of PCSX2
Try to boot a game

***Last known version to work:***
Ever since x64 was implemented, the bug exists.

***PC specifications:***
Irrevelant. As this was tested in 3 builds with extremely different configurations.
But I can write them down if necessary.

**Comment by tellowkrinkle** [comment]
Is this before or after ecebaca3f0f3dd0ed69704e71b832f7b03932fcc?

**Comment by refractionpcsx2** [comment]
Can you make sure you're definitely up to date? This was tested on windows, mac and Linux and it was already fixed

**Comment by FerocityVine** [comment]
I downloaded the source one hour after ecebaca.

**Comment by tellowkrinkle** [comment]
The screenshot looks like a build from our CI

**Comment by FerocityVine** [comment]
Redownloaded the latest code. Compiling, going to test again.
And I am building it as a Debug build.

**Comment by FerocityVine** [comment]
The emulator now instead stops responding.
![image](https://user-images.githubusercontent.com/67128920/91651774-537fc600-ea99-11ea-9165-06fba8b53789.png)

**Comment by refractionpcsx2** [comment]
Are you running gsdx in software mode? I mean you're game is now booting happily and has already run all the code that was changed recently. Gsdx software mode isn't 64bit ready though, so you need to stay on hardware

**Comment by FerocityVine** [comment]
I am running GSGL Hardware. GSDX 11 Hardware doesn't even let the game boot.

**Comment by FerocityVine** [comment]
And before you say anything, the issue is presistent on Windows 10.

**Comment by refractionpcsx2** [comment]
Okay, something you can try back in opengl. Go to config->emulator settings then to the game fixes tab at the bottom, enable them and tick the vu0 kickstart option at the bottom, see if that solves the hang

**Comment by FerocityVine** [comment]
![image](https://user-images.githubusercontent.com/67128920/91651841-40b9c100-ea9a-11ea-9470-4dbeabfb35e6.png)
No, it doesn't.

**Comment by tellowkrinkle** [comment]
Uhh has anyone tested the SSE2 GSdx on x64?

**Comment by refractionpcsx2** [comment]
Don't think so, we've only been using avx2

**Comment by FerocityVine** [comment]
Well, that is a bad thing to do isn't it? A lot of people still use SSE2 architecture machines and cannot afford another one.
Valve, plz fix.

**Comment by refractionpcsx2** [comment]
Also is the arcade edition a ps2 game or a Namco arcade game? Pcsx2 doesn't support Namco games

**Comment by FerocityVine** [comment]
It is a PS2 port of the Arcade Edition that I made. However, the issue presists on:

- Soulcalibur 3 USA
- Soulcalibur 2 USA

**Comment by refractionpcsx2** [comment]
Hmm okay, we'll need to look into it then I guess, see what's going on

**Comment by FerocityVine** [comment]
Please do. Thanks for the quick responses.

**Comment by kozarovv** [comment]
Can you try build compiled here: https://ci.appveyor.com/project/gregory38/pcsx2/builds/34925757/job/twxhkkmn44dekxnb/artifacts

And if it work then later try build that will be compiled here: https://ci.appveyor.com/project/gregory38/pcsx2/builds/34925835/job/aj86m2v1mnrsf2b5

I can reproduce your issue, but for some reason x64 build compiled by appveyor work fine for me.

**Comment by refractionpcsx2** [comment]
I had a quick look in to this this morniing and it only happens if you run Soul Calibur 3 in a debug build with the EE Recompiler enabled (EE Interpreter is fine).  Can you confirm if it works in a devel/release build for you?

**Comment by FerocityVine** [comment]
The issue seems to be fixed with the latest master. Closing issue.
