### ISSUE TITLE
Jak II: Graphics issues

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#3656]
As of commit 6f0011ac9c2058e317cbd357e337239311d1e8ce, I noticed a rainbow-like pattern in the main menu, and very pronounced spiky-polygon syndrome with the Jak character ingame:

![1](https://user-images.githubusercontent.com/12475371/91775123-51605900-ebb8-11ea-848b-152a1bce920c.png)
![2](https://user-images.githubusercontent.com/12475371/91775127-51f8ef80-ebb8-11ea-9572-3e14ef34a58a.png)

I tried changing many settings such as with/without hacks, HW, SW etc. but nothing helped (though willing to try again with specific settings as requested).

Note that this did not occur with build 60e075d6c902818b6cc979ab4ee8bc590fc58852, so the regression is somewhere in between although I have not been able to bisect for the cause.  Also this last working build was x86 so perhaps the cause is with the x64 build itself (@beaumanvienna can you confirm?)

Using pcsx2 x64 build with gsdx 1.2.0 x64.  Test system is linux mint 20, kernel 5.4 and gcc 9.3.0, i7-7820HK cpu with nvidia gtx-1070 and driver 440.100.

**Comment by refractionpcsx2** [comment]
Can you go in to Config->Emulator Settings->Gamefixes and enable the VU Kickstart hack at the bottom and see if that helps? We did add as many as we can but we might have missed yours

**Comment by Shoegzer** [comment]
@refractionpcsx2 Thanks, that fixed the issue.  Do you need any info from me?  I can keep this open and retest once the hack is added.

**Comment by refractionpcsx2** [comment]
Yes can you tell me the serial number (SLES,  SLUS, SCEJ or something like that followed by a number) and we can add it to the database :)

**Comment by Shoegzer** [comment]
Sure thing!  It's SCUS_972.65.

**Comment by RedDevilus** [comment]
Already has the hack implemented.

![image](https://user-images.githubusercontent.com/24227051/91779527-23016e80-ebf6-11ea-82ef-61138f59f20f.png)

**Comment by refractionpcsx2** [comment]
Thanks, I will add that to the gameDB tomorrow if it isn't there and report back :)

Just to double check have you got automatic game fixes enabled? It's under the first menu about half way down, if it isn't, can you enable it then disable the game fix you turned on before to see if it works automatically? Thanks :)

**Comment by Shoegzer** [comment]
Hey thanks.  Actually yes, automatic gamefixes has been enabled the entire time I've been testing, which is why I'm puzzled the manual hack has a positive effect in light of the fact that it's apparently already in the gameDB as @RedDevilus mentioned.  I just tested again to be sure:

* Automatic gamefixes ON, manual gamefixes OFF: Graphics problem
* Automatic gamefixes ON, manual gamefixes ON: No graphics problem

**Comment by refractionpcsx2** [comment]
Okay have you got the console window open when you run pcsx2? If so what does it say along the title bar? Does it recognise your game and say if any fixes are applied?

**Comment by Shoegzer** [comment]
Okay, I found and fixed the problem: the gameDB file was missing from /usr/local/games/PCSX2, which I had deleted in the move to x64 but had forgotten to restore.  Great.

I'll close this, but with a question: is there a way to specify an alternate path for the gamedb file as you can with all other assets (bios, memcard, plugins etc.)?  I have a much better directory for it but couldn't find a way to configure the location either through the UI or the .ini files.

**Comment by refractionpcsx2** [comment]
Maybe @kenshen112 or @arcum42 can answer that one, I'm not a Linux guy so I can't help you there
