### ISSUE TITLE
Ridge Racer V - Unable to accelerate during a race

### ISSUE THREAD

**Issue by OmegaPhil** [PCSX2/pcsx2#366]
I'm testing out pcsx2 again to see how things have improved - while Ridge Racer 5 (NTSC) works with some slowdown and graphical glitches, I found that pressing X in the race didn't accelerate the car... hence the game is pretty bricked!

In the menus, X works fine. Could it be not-working analog buttons? Since this was an early PS2 game, I vaguelly remember them testing this out as a new DualShock 2 feature.

System: Debian Testing (Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-2 (2014-11-06) x86_64 GNU/Linux)
pcsx2 1.2.1 (stable) and latest git (276e3d9d1bb63f0ddc3a3cce4757896af5d138ba, Fri Nov 14 11:43:42 2014 +0100)
In both cases compiled with -march=native -O3 (although cmake seems to nuke the -O parameter)

I'm using a genuine DualShock 2 controller via [this adaptor](http://www.amazon.co.uk/BLUE-CONTROLLER-ADAPTER-CONVERTER-Playstation/dp/B004YNIOL6/ref=cm_cr_pr_product_top), however counting against my theory is the fact that jstest-gtk does not show the buttons as analog. I would appreciate someone doing a sanity test on the game all the same.

Originally [reported in the forum](http://forums.pcsx2.net/Thread-Ridge-Racer-V-Unable-to-accelerate-during-a-race?pid=416996#pid416996).

**Comment by gregory38** [comment]
Could you test the PR #1476 maybe it is better

**Comment by OmegaPhil** [comment]
No difference - is there any way to prove in OnePad that the buttons are actually treated as analog?

**Comment by gregory38** [comment]
I added a print of the current mode.

I tried the game on my side (PAL version) and I manage to use 'x' to accelerate. I don't remember do you need to configure something in the menu to set the pad in analog mode ? It seems the game use only a digital mode.

**Comment by gregory38** [comment]
Sorry, I forgot to push my change. Could you retest latest version of the branch to see the current detected mode of the game. Thanks.

**Comment by OmegaPhil** [comment]
Firstly, poking around Ridge Racer V's internal options allows you to test the analog buttons, and they definitely weren't working (literally dpad left pressure registration was almost nothing, right was dead, similar for other buttons).

I didn't notice any difference with your changes, so I looked around the plugins - and I found that your code was in onepad v1.3, however v1.2 was configured to be used. So, after setting that... I can suddenly race!

Graphics are arse with lots of slowdown, but I can actually race, lol. Thanks for doing the change (would be nice if this game worked with hardware rendering).

**Comment by gregory38** [comment]
Ok. So issue could be closed when I merge the branch.

**Comment by OmegaPhil** [comment]
On 26/07/16 08:03, Gregory Hainaut wrote:
> Ok. So issue could be closed when I merge the branch.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PCSX2/pcsx2/issues/366#issuecomment-235180118


Happy to retest when needed.

**Comment by gregory38** [comment]
In this case, may I ask you a favor. Did you manage to make rumble work ? If yes, could you test if it's still working on the branch.

**Comment by OmegaPhil** [comment]
On 26/07/16 08:59, Gregory Hainaut wrote:
> In this case, may I ask you a favor. Did you manage to make rumble
> work ? If yes, could you test if it's still working on the branch.
> 
> --- You are receiving this because you authored the thread. Reply to
> this email directly or view it on GitHub: 
> https://github.com/PCSX2/pcsx2/issues/366#issuecomment-235190800
> 


Sure - there wasnt force feedback in last night's play, I'll do a
specific test tonight (force feedback does work in general for the
dongle + pad since it works with the Dolphin emulator).

**Comment by OmegaPhil** [comment]
Right, I can see why Ridge Racer V suddenly works - it thinks the joypad is the standard digital joypad (e.g. I don't have access to force feedback there). 

Testing GTA3, I do indeed have force feedback :) It doesn't seem to confuse the pad (you have to turn force feedback on first in the game options).

For anyone else reading: Onepad basically turns force feedback off by default, get to the plugin configuration dialog then go into Gamepad Configuration button bottom left, tick Enable rumble and set the Rumble intensity to a sensible value.

**Comment by gregory38** [comment]
Ok. Thanks you for the test. I will merge the branch once I got some feedback on the save/load state.
