### ISSUE TITLE
Driv3r excessive GPU load causing low performance.

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#3661]
**Game:**
Driv3r (SLUS-20587)

***PCSX2 version:***
v1.7.0 (dev-204)

***PCSX2 options:***
_Speedhacks:_
EE Cyclerate: 0, EE Cycleskipping: 0, mVU Flag Hack : Enabled, MTVU: Enabled

***Plugins used:***
GSdx (OpenGL Hardware)

***Description of the issue:***
After the initial loading of the game and various cutscenes, and the level loads up, the GPU starts being utilized 100%. VRAM usage actually remains somewhat stable at around 1.1GB ~ 1.3GB. But because the GPU is being stressed so hard, the performance under OpenGL Hardware is dreadful at best. This performance continues to decline the higher you go with your resolution. On a GeForce GTX 1660 Super I was able to get 55-60 FPS (Mostly below 60 FPS though after further testing) on Native resolution. Going to 2x Native resulted in a massive drop of performance already to about 45-48 FPS.

It seems that Direct3D11 Hardware also has somewhat high load, (48~50+% on 2x Native), but it's not as bad as on OpenGL where it jumps to 100% right away no matter what.

***How to reproduce the issue:***
Simply play the game.

***Last known version to work:***
N/A

***PC specifications:***
CPU: AMD Ryzen 5 3600
GPU: MSI GeForce GTX 1660 SUPER VENTUS XS OC
OS: Windows 10 64-bit (build 2004)

**Comment by lightningterror** [comment]
A gs dump would be nice.

**Comment by Ryudo300** [comment]
[gsdx_20200909171726.zip](https://github.com/PCSX2/pcsx2/files/5196168/gsdx_20200909171726.zip)

**Comment by Mrlinkwii** [comment]
how is this performance wise on latest nightly ?

**Comment by JordanTheToaster** [comment]
Performance is fine as of latest nightly the game overall is just heavy.

![image](https://user-images.githubusercontent.com/80843560/227019996-54533e33-d0bd-4533-bbcb-654597e98a69.png)
