### ISSUE TITLE
[BUG] Linux DS3 right analog stick not registering Up / Down

### ISSUE THREAD

**Issue by dener3id** [PCSX2/pcsx2#3665]
***PCSX2 version: 1.5 and 1.7 regression issue works prefectly in 1.4***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``

***PCSX2 options:N/A***

***Plugins used:libonepad or libonepad-legacy.***

***Description of the issue: ps3 right joystick won't register up or down.***

***How to reproduce the issue: use USB for ds3 controller blue tooth is untested as I don't have blue tooth on my PC.***

***Last known version to work: is unknown 1.4 works at 1.5 or earlyer the right joy stick dosen't work with or without libonepad (dosen't work at all) or libonepad-legacy(everything but up or down for right joystick tested on more then one controller), with and without the hacks enabled (Hack: sixaxis/ds3 plugged into to usb used to fix it on older versions).***

***PC specifications:`Linux mint 20 otherwise should matter should be reproducible on all Linux systems for 1.5 and 1.7 and later.***

Someone should confirm on mac windows and other to see if this is an issue there as well.

**Comment by Mrlinkwii** [comment]
works fine here using latest release  PPA on ubuntu 20.04 ,  with the DS3 controller  ,

**Comment by dener3id** [comment]
> works fine here using latest release PPA on ubuntu 20.04 , with the DS3 controller ,

up and down on right joystick?

**Comment by Mrlinkwii** [comment]
yes , up and down on right joystick , it may be a thing your controller may be damaged

**Comment by dener3id** [comment]
> works fine here using latest release PPA on ubuntu 20.04 , with the DS3 controller ,

and daily build or stable? 1.5 is stable 1.7 is daily.

**Comment by Mrlinkwii** [comment]
daily

**Comment by dener3id** [comment]
> daily

I will purge my config files cause it updated today and still didn't work.

**Comment by dener3id** [comment]
> yes , up and down on right joystick , it may be a thing your controller may be damaged

no tested with two controllers while there not in great shape up and down worked in pcsxr for ps1 games. this is weird. motherboard usb controller failure?

**Comment by RedDevilus** [comment]
#3666 Idem

Onepad works by default without configuring, either something is wrong with your configuration or the controllers don't work properly.
You can test on : https://gamepad-tester.com/

**Comment by dener3id** [comment]
> #3666 Idem
> 
> Onepad works by default without configuring, either something is wrong with your computer or the controllers don't work properly.
> You can test on : https://gamepad-tester.com/

doesn't show up there. but again pcsx2 detects everything else. and in previous versions I had to enable to hack for it to work. and pcsx2 detects it just not up and down. but pcsxr detects up and down just fine so it's not the controller.

**Comment by dener3id** [comment]
> #3666 Idem
> 
> Onepad works by default without configuring, either something is wrong with your computer or the controllers don't work properly.
> You can test on : https://gamepad-tester.com/

works fine in 1.4 by the way.

**Comment by dener3id** [comment]
> #3666 Idem
> 
> Onepad works by default without configuring, either something is wrong with your computer or the controllers don't work properly.
> You can test on : https://gamepad-tester.com/

to be clear it works correctly in 1.4.

**Comment by dener3id** [comment]
> daily

is your system fully up to date? and intel or amd? I'm on amd ryzen 2700x, like maybe it's something to do with the kernal ps3 driver and the usb driver for the the mobo.

**Comment by dukenukemx** [comment]
I'm using PCSX2 1.7 on Mint 20 with two Xbox Original gamepads and none are working properly or at all in PCSX2.  With the OnePAD 2.0.0 it doesn't detect any input from the gamepads no matter what I do.  With OnePAD 1.3.0 it does detect the input and I can setup the controller but it won't work in game unless I use the second gamepad.  This also happens in PCSX 1.5.

**Comment by lightningterror** [comment]
Should be fine on qt, if not then this can be re opened.
