### ISSUE TITLE
K-1 World Grand Prix 2006 - Black Screen

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3668]
***PCSX2 version:***
``( v1.7.0-dev-213)``

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
black screen in the menus on hardware renderer 
![gsdx_20200904015915](https://user-images.githubusercontent.com/8851653/92209362-7a9c1600-ee52-11ea-8340-5907e4ddbc19.png)

then red when in the fight

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

***Last known version to work:***
none

***PC specifications:***
CPU: Intel Core i5 4430 GPU: Geforce 960 OS: Windows 10 64 Bit)``

**Comment by seta-san** [comment]
[gsdx_20200904015915.gs.zip](https://github.com/PCSX2/pcsx2/files/5176570/gsdx_20200904015915.gs.zip)

**Comment by seta-san** [comment]
https://www.youtube.com/watch?v=Jpe5bEBFFRw

**Comment by tadanokojin** [comment]
Debugged it and had @refractionpcsx2 write me a patch:
```
// Fixes game not working in hardware mode
patch=1,EE,004574B0,word,0000948c
patch=1,EE,004574D8,word,0000948c
```

Basically the issue is the game is doing a BLIT to one of two front buffers (one of which is a temporarily repurposed depth buffer).
It BLITs c32 data as z24, I can hack this to be c32 but then the BLIT requires preload frame and you lose scaling.

Need cache rework to solve it.

related: #3169
