### ISSUE TITLE
[Enhancement] De-Interlacing improvements

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#3673]
Was wondering if anyone has ever tried to apply a DeCombing filter or shader to the Weave de-interlacing already present, to get rid of the 'saw-toothed' artifacts that it creates?

Also, with regard to blur caused by some de-interlacing, how viable would frame doubling be when applied before de-interlacing?

**Comment by lightningterror** [comment]
Closing, trivial.
