### ISSUE TITLE
Slow/lagging Linux mint 20

### ISSUE THREAD

**Issue by tome9111991** [PCSX2/pcsx2#3674]
***PCSX2 version:***
 v1.7.0-dev-xxx)``
Hello.
On my linux mint 20 i cant play any games.
The intro works well with 50fps but when i ingame i just have 5-10 fps.

With linux mint 19.2 works better not perfect but to play was well.
Maybe 20-30 fps.

Any idea what the problem is with mint 20?
It is based on ubuntu 20.04

**Comment by Mrlinkwii** [comment]
what are your specs and what game ?

**Comment by tome9111991** [comment]
I have Gigabyte Brix Bcle-4105
Intel Celeron j4105
8gb ram

Wwe smackdown here come the pain works well on mint 19.2 but on mint 20 is not playable.

**Comment by tadanokojin** [comment]
Read our minimum requirements before posting and use the forums for support.
