### ISSUE TITLE
[Feature Request] Enable upscaling gamefixes

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3681]
This will reduce the need for changing settings (like automatic gamefixes).
However this one is going to involve loads of prep work and verifying. And should not be used automatically by default to avoid problems. Perhaps as a different file or an expansion within the gamedb. 

Example of how it could look:
![image](https://user-images.githubusercontent.com/24227051/92621466-21097080-f2c4-11ea-8bcd-6b415539fb47.png)

**Comment by atomic83GitHub** [comment]
It is going to be difficult but I agrea that idea would be nice.

**Comment by seta-san** [comment]
i agree too. the less configuring the end user needs to do the better.

**Comment by tadanokojin** [comment]
There's some things to consider for this request:

The biggest issue is how difficult it would be to implement given the current infrastructure. GSdx and Core are functionally two separate things right now with two separate methods of configuration. So communicating anything from Core requires either going through MTGS and the plugin interface, or Core writing directly to GSdx.ini... neither would be very good. The first would require changes to the interface and would be a threading nightmare. The second sucks for obvious reasons.

The other thing I want people to consider about these things is that while it does make things easier on end users, it also means we rely on upscaling hacks. If all you have to do is click a checkbox to turn on a cocktail of hacks to make your problems go away there's no incentive to fix these problems. It's also pretty much guaranteed not to be a good long term solution. I can't write upscaling hacks for every game in existence, no one can. The hacks we have aren't without their problems either.

One way you could implement this: you could patch the game out of the draws that are the cause of upscaling problems. Namely post-processing. Then you could implement it similar to the gamedb system. I would prefer that solution to any automatic GSdx configuration.

**Comment by seta-san** [comment]
are up scale hacks actually hacks that fixes an error of emulation or are they fixing a natural consequence of upscaling something?

**Comment by tadanokojin** [comment]
They're hacks to fix the hack that is called upscaling.

**Comment by seta-san** [comment]
> They're hacks to fix the hack that is called upscaling.
so the breaks and lines in geometry and menus and fonts are a natural consequence of upscaling?

**Comment by tadanokojin** [comment]
Yes.

**Comment by RedDevilus** [comment]
Handled in the GameDB where more and more entries will be added.
Fixed by: https://github.com/PCSX2/pcsx2/pull/5593
