### ISSUE TITLE
Graphical and Functional Glitches with Soulcalibur 3

### ISSUE THREAD

**Issue by Topaz-Reality** [PCSX2/pcsx2#3682]
***PCSX2 version:***
PCSX2 1.7.0-dev-217-g27598fecc

***PCSX2 options:***
All Settings

***Plugins used:***
GSdx MSVC 19.25 (All Arcitechtures)
All settings affected. All modes affected.

***Description of the issue:***
Half-Transparent textures (Most notably bangs of female characters) are bugged and glitched.
SSE2 Performance took a heavy hit. The game is now unplayable slow on an SSE2 GT710 build even with speedhacks while in 1.6.0 it was a consistent 60/30FPS.

Screenshots for the first issue (Above is 1.6.0, Below is 1.7.0):
![image](https://user-images.githubusercontent.com/28973970/92675344-d4f01780-f327-11ea-9c4e-5744a835b20e.png)
![image](https://user-images.githubusercontent.com/28973970/92675354-dc172580-f327-11ea-9299-14cb9321f2a3.png)

![image](https://user-images.githubusercontent.com/28973970/92675393-f224e600-f327-11ea-8069-fbf24a4a04f8.png)
![image](https://user-images.githubusercontent.com/28973970/92675396-f81ac700-f327-11ea-9c84-c8cf0d234263.png)

![image](https://user-images.githubusercontent.com/28973970/92675423-0963d380-f328-11ea-98b2-54cbe921a0da.png)
![image](https://user-images.githubusercontent.com/28973970/92675405-fea93e80-f327-11ea-9c4f-1064add7f02a.png)

***How to reproduce the issue:***
Choose a character that has a semi-transparent texture. First Issue
Play the game on an SSE2 machine. Second Issue

***Last known version to work:***
All pre-1.7.0 builds are impervious to this issue.

***PC specifications:***
Tested on: Intel Pentium E6800 - nVidia GT 710 - 4GB RAM
Intel Core i7-8750H - nVidia GTX 1060 - 16GB RAM

**Comment by tellowkrinkle** [comment]
Chances are this is from an accuracy improvement, in which case there isn't much we can do (though you're welcome to maintain your own SSE2 fork), but if you want to be sure you should either use `git bisect` or manually bisect with appveyor builds to find out which commit caused the regression.  "Sometime between 1.6.0 and now" is a lot of changes

**Comment by Topaz-Reality** [comment]
I mean, performance loss on SSE2 I can understand. But these graphical glitches persisting through all CPU architectures is a little annoying and would go into as being "not accurate". We could look into this a little more, eh?

I will count performance loss on SSE2 being made for the sake of accuracy but the graphical glitches like this are, what do you call them, irritating at best.

I will test all 1.7.0 builds that are available to pinpoint the graphical issues.

**Comment by tellowkrinkle** [comment]
Somehow didn't realize you were reporting two issues here, do the graphical issues happen on the software renderer as well?

**Comment by Topaz-Reality** [comment]
All Renderers, All Settings.

**Comment by tellowkrinkle** [comment]
It was a VU issue, we found it

**Comment by refractionpcsx2** [comment]
Okay I found the bug, it should be fixed when build 218 comes out (or if you compile master now)

Fun fact: This never worked on VU0 interpreter for a very similar reason, but I've now fixed it there too
