### ISSUE TITLE
Cannot build with GTK3 on openSUSE

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#3685]
***PCSX2 version:***
development builds v1.7.0-dev-xxx

***Description of the issue:***
I have installed `wxGTK3-3_2-devel` and enabled `-DGTK3_API=ON`. But CMake throws errors:
```
[   10s] CMake Error at cmake/SelectPcsx2Plugins.cmake:14 (message):
[   10s]   Skip build of common libraries: missing dependencies:check these libraries
[   10s]   -> wxWidgets (>=3.0), aio
[   10s] Call Stack (most recent call first):
[   10s]   cmake/SelectPcsx2Plugins.cmake:50 (print_dep)
[   10s]   CMakeLists.txt:31 (include)
```

***PC specifications:***
openSUSE Tumbleweed

**Comment by v-fox** [comment]
Yeah, it newer worked. Doesn't like wxWidgets-3.2 with GTK2 too. Maybe https://github.com/PCSX2/pcsx2/pull/3686 will fix all that.
Maybe we can even replace GTK with Qt now.

**Comment by beaumanvienna** [comment]
I have a question for you OpenSUSE users. Do you happen to know how close OpenSUSE is to Fedora? Is it like with Mint/PopOS/Ubuntu/Elementary or Arch/Manjaro "same thing", or would the packages to compile it be different? Could you compare the packages you need for OpenSUSE to  the packages mentioned in these [compile instructions for Fedora](https://github.com/PCSX2/pcsx2/pull/3451#issuecomment-654006105)? I wanted to install Fedora again some time soon and was wondering if a compile test there would cover OpenSUSE as well.

**Comment by guoyunhe** [comment]
Fedora and openSUSE are totally different. Package names are often different. But many application RPM works on both system.

**Comment by Mrlinkwii** [comment]
Is this still an issue on latest nightly build?

**Comment by refractionpcsx2** [comment]
No longer an issue, I believe, all GTK screens have gone.
