### ISSUE TITLE
[Feature request] additional cheats_xx folders (not urgent)

### ISSUE THREAD

**Issue by genova447** [PCSX2/pcsx2#3689]
Hello, please excuse me, I am not so great at being concise - and don't want to sound imposing with my 'thought' either.
There likely are reasons why my 'request' would be undesirable, so I understand if it will be closed with no further notice.

Similar to the *cheats_ws* folder and *cheats_ws.zip* collection, I was thinking that it could be neat to have folders for 60/50/xx fps patches, no interlacing, general fixes/improvements and maybe more 'depending on your hardware' such as 'draw distance' or other ways to improve the look of the game.
You could have *cheats_fps* (or *cheats_60*), *cheats_fixes*, *cheats_ni* and *cheats_dd* respectively as folders that PCSX2 checks for to add cheats from. And of course additional toggles in the interface of PCSX2 as in the image found here https://github.com/PCSX2/pcsx2/issues/3681

Of course I'm aware that you can already add these 'hacks' into either regular "cheats" or "cheats_ws" - but I thought it might be nice to split them up, so you can just toggle from pcsx2 "enable no interlacing patches", instead of going into the text files and comment out the codes you don't want. (and personally I keep the patches I made, separate, as I find it more convenient to go back to and look at like that in the future)

This is also to coincide with the forum threads here: https://forums.pcsx2.net/Thread-60-fps-codes here: https://forums.pcsx2.net/Thread-No-interlacing-codes and here: https://forums.pcsx2.net/Thread-Fixing-unplayable-games
(The mention of draw distance higher up is just because I happened to come across that value myself in 2 games while trying to make widescreen patches, and thought it could cool if one day some people would want to start a forum thread with a collection of draw distance patches - currently there is no forum thread.)

Of course I figure that long-term it might be more desirable to change how cheats work in PCSX2 entirely (**edit**: https://github.com/PCSX2/pcsx2/issues/3900), rather than add bulk to a system that might not stay as-is forever. (Like just the ability for PCSX2 to be able to 'edit' the cheats via a toggle-system how RPCS3 does it) But sorry, I am sure I saw a github issue about 'revamping' the cheats/patches system at one point, but I can't seem to find it *(was a different one than the one I edited in now)*.

(**Edit**: https://github.com/PCSX2/pcsx2/issues/3900 seems that it might invalidate my 'issue here' - so going that way, I could close this one (will wait a little bit and see how things pan out))

**Conclusion (an attempt to be more concise)**

Currently PCSX2 looks for *cheats*, *cheats_ws* and *cheats_ws.zip*.

I am requesting, if possible and easy, that PCSX2 would also look for "*cheats_60*", "*cheats_ni*", "*cheats_fixes*" and "*cheats_dd*" - as well as their zipped variants. (and prioritizing folders over ZIP, but defaulting to ZIP if there's no folder; like how cheats_ws/.zip works currently)
The reason for adding support for the zipped folder variants as well, would be if ever the compiled list of patches for each of those, would be built with PCSX2, as cheats_ws.zip is now.

**Comment by lightningterror** [comment]
No interlacing patches have been added, no plans for the others currently.
