### ISSUE TITLE
Unnecessary hardcoding in cmake breaks distro packages and prevents valid builds

### ISSUE THREAD

**Issue by v-fox** [PCSX2/pcsx2#3691]
***PCSX2 version:***
`1.7.0~dev+233~git20200912T145909`

***Description of the issue:***

So, I've been trying making packages for new, x86_64-capable build and found some nasty hurdles:
* it forces `-march=native` when `DISABLE_ADVANCE_SIMD=0` which hardcodes binaries for CPU of build-server or packager and leads to segfaults on other instruction sets.
* it forces `-msse2` but has bug https://github.com/PCSX2/pcsx2/issues/3096 which requires `DISABLE_ADVANCE_SIMD=1` and, therefore, both states are broken. That is being worked around by forcing avx over sse2. But that cuts off CPUs before 2012 while forcing avx2 cuts off CPUs before 2017 when current desktop CPUs from both AMD and Intel got it.
* gcc-specific LTO options are hardcoded which breaks builds on clang when used. It doesn't seem that it filters LTO flags when USE_LTO=0 but I removed that part just in case.
* https://github.com/PCSX2/pcsx2/issues/3637 is being worked around on x86_64 because it forces -fPIC which is generally good but I'm not sure about its repercussions on emulators due to things like https://github.com/PCSX2/pcsx2/issues/3638

So, to [work around that I did](https://build.opensuse.org/package/show/home:X0F:branches:Emulators/pcsx2-git):
```
# even on x86_32, otherwise -mfpmath=sse is unavailable with -mtune=generic
# with DISABLE_ADVANCE_SIMD=0 that forces AVX but not AVX2
CFLAGS="-D_GNU_SOURCE -march=x86-64 -mtune=generic -mssse3 -msse4 -msse4.1 -msse4.2 -mavx -maes -mpclmul"
sed -i -e 's:-march=native::g' \
    -i -e 's:-msse -msse2:-mssse3 -msse4 -msse4.1 -msse4.2 -mavx -maes -mpclmul:g' \
	cmake/BuildParameters.cmake
```
and
```
diff --git a/cmake/BuildParameters.cmake b/cmake/BuildParameters.cmake
index f5af7ce8a..a206c245d 100644
--- a/cmake/BuildParameters.cmake
+++ b/cmake/BuildParameters.cmake
@@ -316,23 +316,6 @@ endif()
 if (USE_CLANG)
     # -Wno-deprecated-register: glib issue...
     set(DEFAULT_WARNINGS "${DEFAULT_WARNINGS}  -Wno-deprecated-register -Wno-c++14-extensions")
-    set(DBG "-g -fno-omit-frame-pointer")
-elseif (USE_ICC)
-    set(DBG "-g -fno-omit-frame-pointer")
-elseif (USE_GCC)
-    set(DBG "-ggdb3 -fno-omit-frame-pointer")
-endif()
-
-if (USE_LTO)
-    include(ProcessorCount)
-    ProcessorCount(ncpu)
-    set(LTO_FLAGS "-fuse-linker-plugin -flto=${ncpu}")
-    set(DBG "") # not supported with LTO
-    set(CMAKE_AR /usr/bin/gcc-ar CACHE STRING "Archiver" FORCE)
-    set(CMAKE_RANLIB /usr/bin/gcc-ranlib CACHE STRING "ranlib" FORCE)
-    set(CMAKE_NM /usr/bin/gcc-nm CACHE STRING "nm" FORCE)
-else()
-    set(LTO_FLAGS "")
 endif()
```

**Comment by tellowkrinkle** [comment]
You can specify `-DARCH_FLAG=...` to override the `-march=native` for now
Ideally you should be compiling with `-DDISABLE_ADVANCE_SIMD=ON` for distribution, the whole point of ADVANCE_SIMD is to specify `-march=native`

You should be able to enable LTO directly in cmake by passing `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`, though I haven't tested this

`-fPIC` is and always will be on for x86-64, there are no plans to turn it off, we don't have the ability to choose a single static address to allocate things at and there's no reason to try to get closer to something we can never reach.

**Comment by F0bes** [comment]
> You should be able to enable LTO directly in cmake by passing -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON, though I haven't tested this

It's how I use LTO, so it's tested and works.

Is there any update on this? Are the problems resolved?

**Comment by kenshen112** [comment]
Can also confirm it's enabled in pcsx2-git and works just fine

**Comment by F0bes** [comment]
There has been no response from the OP. Assuming their concern has been answered.
