### ISSUE TITLE
Linux UI goes over the screen edge

### ISSUE THREAD

**Issue by treymerkley** [PCSX2/pcsx2#3693]
I'm trying to set the BIOS through the UI, but the button is cut off at the bottom edge. Similarly, alerts and popups get cut off, and I can neither scroll to them or move them around the screen to get access. 

I do love your work though, and thank you so much. What do you need from me?

**Comment by lightningterror** [comment]
Can you post screenshots of the issue?

**Comment by treymerkley** [comment]
Okay, so the original issue I posted about is fixed. I'm still getting a weird issue with trying to set controller configuration, but it's a problem with my window manager scaling, so I'm willing to close this.
![Screenshot_20200927_090252](https://user-images.githubusercontent.com/28458492/94368405-13643100-00a1-11eb-94f3-bae320854b05.png)

**Comment by umbynos** [comment]
I think I have the same problem 
![image](https://user-images.githubusercontent.com/34278123/95070446-6a54b080-0708-11eb-901d-1861f35c4e66.png)

**Comment by Mrlinkwii** [comment]
is this still an issue ?

**Comment by umbynos** [comment]
yepp still an issue for me, I downloaded the version from retropie experimetal packages and it's still versioned as 1.7.0-0 (git)

**Comment by lightningterror** [comment]
Closing, legacy wx issue.
