### ISSUE TITLE
Harry Potter and the Chamber of Secrets (US) Linux

### ISSUE THREAD

**Issue by treymerkley** [PCSX2/pcsx2#3695]
This is probably the same issue as every harry potter game, just Linux flavored so the fixes aren't working. 

I'm on a March build. What do you need from me?

**Comment by refractionpcsx2** [comment]
What issue are you referring to sorry?

**Comment by treymerkley** [comment]
Sure, I should have been more specific. On the first loading screen the game crashes out. All I get is the chocolate frogs box in the corner.

**Comment by refractionpcsx2** [comment]
That's been fixed on master for about 3 months now, i think? Can you make sure you're using a recent build and your gamedb is updated also?

**Comment by treymerkley** [comment]
So it does look like my build was from maybe four or so months ago, so I built from master. Now though, PCSX2 crashes when it reaches loading the plugins. Do you need anything from that, and should I open a separate issue for it?

**Comment by RedDevilus** [comment]
Can you first update to the latest build and test on default settings and then go from there? It can be a different folder and keep the older one for comparison/backup purposes.

**Comment by treymerkley** [comment]
You mean the latest release, 1.6? Just want to double check, I think that's what my distribution is on and I think I misunderstood this as being on a develop branch.

**Comment by refractionpcsx2** [comment]
The fix is on the development branch. I'm not sure what Red was asking as that's what I'd already asked you to do.

Can you post a log after the crash?

**Comment by treymerkley** [comment]
I got it fixed. It looks like the upgrade borked my config, so I just replaced it and now it's running fine, so I'll close this out.

**Comment by refractionpcsx2** [comment]
Okay, thanks for letting us know
