### ISSUE TITLE
Singstar broken graphics in hardware renderer.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3697]
***PCSX2 version:***
``v1.7.0-dev-237``

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``usbqemu 0.10.0``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``mangeled graphics in hardware renderer
[gsdx_20200916145406.gs.zip](https://github.com/PCSX2/pcsx2/files/5234657/gsdx_20200916145406.gs.zip)
![gsdx_20200916145406](https://user-images.githubusercontent.com/8851653/93386275-12273e80-f82d-11ea-8654-6edb0fc0b0de.png)

``

***How to reproduce the issue:***
``play any singstar game in hardware mode.``

***PC specifications:***
``(For example: CPU: Intel i5 4430 GPU: Geforce 960 OS: Windows 10 64 Bit)``

**Comment by tadanokojin** [comment]
Closing in favor of #3180
