### ISSUE TITLE
Kaiketsu Zorro Mezase! SIF0 and  SIF1 stall control

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3700]
***PCSX2 version:***
`` v1.7.0-dev-237``

***Plugins used:***
``usbqemu 0.10.0``
[log.txt](https://github.com/PCSX2/pcsx2/files/5238143/log.txt)

**Comment by seta-san** [comment]
``SIF1 stall control Not Implemented
SIF0 stall control not properly implemented
SIF0 stall control not properly implemented
SIF0 stall control not properly implemented
SIF0 stall control not properly implemented
SIF0 stall control not properly implemented
IPU1 running when IPU1 DMA disabled! CHCR 1 QWC d9
IPU error.  Stopped DMA.``

**Comment by refractionpcsx2** [comment]
Do you want to try it with PR #3701

I suspect it won't fix the IPU error, but it will get rid of the warnings
