### ISSUE TITLE
Switch to a server-based translation process

### ISSUE THREAD

**Issue by GovanifY** [PCSX2/pcsx2#3712]
The current translation process we have is a bit cumbersome, requires manual editing and we need to manually ping translators. The process isn't really user friendly either and we don't have good ways to visualize what's done from what isn't and/or batch process translations.

For this reason @RedDevilus and I implemented a weblate based translation server at https://translate.govanify.com/projects/pcsx2 which does all the heavy lifting for us, automatically ping translators and allows them to have a user friendly UI with auto updated translatable strings from git and pushes translation with correct credits.

You can see sample translation commits here https://github.com/RedDevilus/PCSX2-Translators which is linked to test-main in the weblate proces. po and mo files are automatically generated for changes, comments updated, etc as you can see.

I figured we should probably open an issue at this point to discuss the next steps to go from there, how we would want to integrate weblate changes into the GitHub tree(eg periodic commits or PRs) and get reviews from translators to have more input on this whole thing.

**Comment by refractionpcsx2** [comment]
Translations being controlled by https://crowdin.com/project/pcsx2-emulator
