### ISSUE TITLE
Black sky on burnout 3

### ISSUE THREAD

**Issue by chaos4455** [PCSX2/pcsx2#3717]
Sorry but i dont have many information at the moment, but when i arrive at home, ill post all information about my specs but in resume, in butnout 3, the sky is black.

![maxresdefault (1)](https://user-images.githubusercontent.com/30844283/93669874-22c5f780-fa6d-11ea-8c6f-7a42c7cf524d.jpg)
![maxresdefault](https://user-images.githubusercontent.com/30844283/93669875-235e8e00-fa6d-11ea-9ccc-49cc0f3c2dcb.jpg)

**Comment by lightningterror** [comment]
Dupe #563
