### ISSUE TITLE
Custom hotkeys

### ISSUE THREAD

**Issue by InfamousKnight** [PCSX2/pcsx2#3718]
From what I can tell, there's no way to configure the hotkeys for things like save states and frame advance. Would be nice if this was possible.

**Comment by RedDevilus** [comment]
Similar to #3214

**Comment by sonicfind** [comment]
While it not possible to do so in emulator, you can do so with a custom PCSX2_keys.ini file in the ini folder.
There should be a default version included with any public/dev build. Copy it in the ini folder and change whatever keybindings you want to.

**Comment by InfamousKnight** [comment]
I dont see this file on Linux

**Comment by avih** [comment]
It's this file https://github.com/PCSX2/pcsx2/blob/master/bin/PCSX2_keys.ini.default and you can just copy it from here.

Depending on where you got your PCSX2 copy from, they might or might not have included it, so you should contact whoever packaged it.
