### ISSUE TITLE
Changing framelimit while the game is running causes issues

### ISSUE THREAD

**Issue by SuperSamus** [PCSX2/pcsx2#3725]
***PCSX2 version:***
 v1.7.0-dev-312 (happens in both 32 and 64 bit)

***PCSX2 options:***
Tested with safest preset.

***Plugins used:***
Default.

***Description of the issue:***
Changing framelimit during the execution of a game (by pressing F4 or TAB) causes problems, especially during loading times.
Example of issues are the music stopping, scenes not loading correctly, or freezing the game. A log of Persona 3 FES where I froze the game with this method is attached here: [emuLog.txt](https://github.com/PCSX2/pcsx2/files/5252218/emuLog.txt).

***How to reproduce the issue:***
Just press TAB or F4 while any game is running. Pressing them multiple times during a loading screen will likely cause the game to freeze.

***Last known version to work:***
I tested 1.7.0-dev-260 (32 bit): during loading times doesn't cause issues on the game.
EDIT: Same for dev-172.

***PC specifications:***
CPU: AMD A10-9700 GPU: AMD RX460 OS: Windows 10 64 Bit

EDIT: There is also another issue where quickly mashing the button/s to change the framelimit crashes PCSX2, but that's a separate issue so I removed it from here.

**Comment by MrCK1** [comment]
If the game freezes then it's not really our problem, many games will break when disabling the framelimiter during loading screens. They're not designed to be run at those speeds.

**Comment by SuperSamus** [comment]
With framelimiter I'm referring to PCSX2's (the entire game is sped up), I'm not altering the game with any cheat code.
Also, it's changing the framelimiter that causes the problem: setting it as unlimited and then never changing it doesn't cause any problem.
And this didn't happen on previous versions of PCSX2, so it's definitely an issue.

**Comment by FMecha** [comment]
Even in BIOS, I've having this problem, sometimes even accompanied with "GSDX OUT OF MEMORY" spam in console.
```
Get Reboot Request From EE
ROM directory not found

PlayStation 2 ======== Update rebooting..
ROM directory not found

PlayStation 2 ======== Update reboot complete
cdvdman Init
rmreset start
rmreset end
clearspu: completed
Pad Driver for OSD (2000/12/05 18:05) 392, 128


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
read/write allocate memory 4000
open name rom0:ROMVER flag 1 data 48a78
open fd = 2
loadmodule: fname rom0:ATAD args 0 arg 
ATA: DEV9C version 0x0: unknown device detected
loadmodule: id 31, ret 1
loadmodule: fname rom0:HDDLOAD args 28 arg -osd
loadmodule: id -200, ret 1
open name rom0:FONTM flag 1 data 48a78
open fd = 2
open name rom0:FNTIMAGE flag 1 data 48a78
open fd = 2
open name rom0:SNDIMAGE flag 1 data 48a78
open fd = 2
open name rom0:TEXIMAGE flag 1 data 48a78
open fd = 2
open name rom0:ICOIMAGE flag 1 data 48a78
open fd = 2
open name rom0:TZLIST flag 1 data 48a78
open fd = 2
_spu_rev_offsetaddr 1f9021
### addr = 1034255  size = 28640
_spu_rev_offsetaddr 1d9021
### addr = 968719  size = 28640
open name rom0:ROMVER flag 1 data 48a78
open fd = 2
open name rom1:DVDID flag 1 data 48a78
open fd = -6
(UpdateVSyncRate) Mode Changed to DVD NTSC.
(UpdateVSyncRate) FPS Limit Changed : 59.93 fps
(FrameLimiter) Turbo ENABLED.
Patches: No CRC found, using 00000000 instead.
(UpdateVSyncRate) FPS Limit Changed : 119.87 fps
Closing plugins... [BIOS hangs at this point - this was an attempt to regain control]
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
Current Renderer: Direct3D 11 (Hardware renderer)
	Opening CDVD
	Opening USB
	Opening FW
	Opening DEV9
GSdx Lookup CRC:00000000
GSdx Lookup CRC:00000000
McdSlot 0 [File]: [path to memory card]
McdSlot 1 [File]: [path to memory card]
Plugins opened successfully.
(FrameLimiter) Turbo DISABLED.
Patches: No CRC found, using 00000000 instead.
(UpdateVSyncRate) FPS Limit Changed : 59.93 fps
Closing plugins... [BIOS hangs at this point - this was an attempt to regain control]
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
```

**Comment by sonicfind** [comment]
I have a theory: try testing this out with build dev-272. It's before the CDVD merge to core: https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.0-dev-272-g0c67dc99f&platform=windows-x86

If it works there... then that adds another issue onto the pile.

**Comment by SuperSamus** [comment]
Build dev-272 **doesn't** have the problem.

**Comment by refractionpcsx2** [comment]
This and #3721 are related

**Comment by refractionpcsx2** [comment]
Can you try this again on the most recent CDVD commit I just made?

**Comment by SuperSamus** [comment]
Build dev-321 **doesn't** have the problem.

**Comment by refractionpcsx2** [comment]
Good to hear :) will mark this as resolved then

**Comment by Geniusssmit** [comment]
I just downloaded dev 420 and I have the same issue, though it's only present in gsd11 mode, opengl and sw works fine.

**Comment by tadanokojin** [comment]
yeah there was a bug, unrelated to this.
shall be fixed in latest master.
