### ISSUE TITLE
[Linux] screenrecorder option does nothing

### ISSUE THREAD

**Issue by InfamousKnight** [PCSX2/pcsx2#3729]

**Comment by sonicfind** [comment]
Please refer to these guidelines for creating an issue post on here: https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by InfamousKnight** [comment]
To be more specific, when I press start screen recorder, play the game a bit, look to end recording, that option is still disabled as if I never clicked start.

**Comment by sonicfind** [comment]
Which means it may have been trying to use a function that actually doesn't exist with the parameter set. Once the artifacts in the PR are done, see if their changes fix that issue.

**Comment by sonicfind** [comment]
https://github.com/PCSX2/pcsx2/pull/3731 Test the builds here to see if that fixes it.

**Comment by InfamousKnight** [comment]
And how do I do that with PR?

**Comment by sonicfind** [comment]
Go to the bottom where it says "4 checks complete" and click "show details." Select the build you need.

**Comment by InfamousKnight** [comment]
I tried running this command in terminal gh pr checkout 3731 and this outputs:

Welcome to GitHub CLI!

To authenticate, please run `gh auth login`.
You can also set the GITHUB_TOKEN environment variable, if preferred.

Do I log in with my credentials?
