### ISSUE TITLE
Frame advance doesn't release held buttons

### ISSUE THREAD

**Issue by InfamousKnight** [PCSX2/pcsx2#3735]
***PCSX2 version:***

79f2468

If you hold frame advance and a key like left and then let go, it will keep pressing left even though you're not physically touching it.

To work around it, let go of frame advance, press some random key(preferable one that doesn't do anything for the time), and press frame advance once. This is pretty annoying to work with. Thankfully I figured out the real issue.

**Comment by MrCK1** [comment]
Closing due to no response
