### ISSUE TITLE
Remove this Scroll Bar

### ISSUE THREAD

**Issue by Javed-Iqbal-1** [PCSX2/pcsx2#3736]
Remove this scroll bar so that the window is stretch and items shows clearly..........
![scroll bar](https://user-images.githubusercontent.com/57389023/93867582-ae948980-fce2-11ea-88e7-41ac652f99f9.PNG)

**Comment by tadanokojin** [comment]
Please properly fill out the issue template with relevant information like your OS and PCSX2 version instead of just deleting it entirely and showing us a screenshot.

**Comment by Javed-Iqbal-1** [comment]
PCSX2 = 1.6.0
Windows 7 SP1 64-Bit

This is simple Gui problem you can correct it easily by increasing the size of this window in  your program Code.... I think so...

**Comment by tadanokojin** [comment]
What is your screen resolution?

Also, for the record we don't support win7 post 1.6.0 so even if we fix this it'll be in a version that doesn't officially support your OS,

**Comment by Javed-Iqbal-1** [comment]
Resolution = 1280x720

**Comment by tadanokojin** [comment]
Yeah it's because your resolution is low then. I'm not 1080p monitor it looks fine. Might be able to sort it out if anyone wants to look into it.

**Comment by Javed-Iqbal-1** [comment]
> Yeah it's because your resolution is low then. On my 1080p monitor it looks fine. Might be able to sort it out if anyone wants to look into it.

Thanks for Help. When I changed my desktop resolution it looks fine , Now I know that it is the resolution problem. but one question is in my mind that 1280x720 is also HD resolution then why PCSX@ is not Fit in it...........

**Comment by refractionpcsx2** [comment]
Being a HD (ready) resolution doesn't make 720 pixels very tall. We have a lot of information to fit on the screen and must people are using 1080 or higher these days which is enough.

**Comment by Javed-Iqbal-1** [comment]
Thanks for clarification.............. Now I understand..
