### ISSUE TITLE
[Feature Request] Switch physical media.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3737]
***PCSX2 version:***
``v1.7.0-dev-327``

so this dialog only comes up with disc images, not physic media
![Untitled2](https://user-images.githubusercontent.com/8851653/93868847-aa3f8080-fc90-11ea-9e09-0699a6ba1e83.jpg)

Needs something like this.
![Untitled](https://user-images.githubusercontent.com/8851653/93868967-cd6a3000-fc90-11ea-9a97-c3d468fc651c.jpg)

**Comment by Mrlinkwii** [comment]
can be done in qt

**Comment by seta-san** [comment]
finally got around to getting to storage to getting physical discs. it does indeed work.
