### ISSUE TITLE
Gran Turismo 4: Flickering car reflections with OGL HW

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#3738]
***PCSX2 version:***
v1.7.0-dev-328-g284977605

***PCSX2 options:***
Default except EE clamping to Full and VU clamping to Extra + Preserve Sign 

***Description of the issue:***
Reflective surfaces on car tend to flicker at random, even the player car hood if using the hood camera.
Reflective surfaces on buildings don't seem affected.
The issue also happens at native resolution.

Of all the settings I tried the following affects the issue:
-Blending Accuracy to High-Ultra coupled with Accurate DATE set to Fast or Off, Full Accurate DATE will cause the issue to reappear regardless of blending accuracy level and High blending accuracy causes severe performance issues at various point of the game (sub 20fps with GPU pegged at 100% usage)
-Turning GIF FIFO on , which instead breaks some GUI elements by flashing random garbage textures in their place
-Using the EE Timing Hack, which doesn't seem to break anything obvious.

Here's two multiframe GS dump taken while the issue was happening, one while paused the other while in a race.

[gsdx_20200922134636.gs.zip](https://github.com/PCSX2/pcsx2/files/5261416/gsdx_20200922134636.gs.zip)
[gsdx_20200922135629.gs.zip](https://github.com/PCSX2/pcsx2/files/5261425/gsdx_20200922135629.gs.zip)

***How to reproduce the issue:***
Start any race with a rolling start while using the OGL HW renderer and blending set to basic or higher.
Different cars tend to have varying degree of said issue

***Last known version to work:***
None that I could find that didn't have other issues masking that one

***PC specifications:***
Windows 10 1909 64bit
Ryzen 7 3800X
Nvidia GTX 1080Ti w/ 451.85 drivers

**Comment by lightningterror** [comment]
Try https://github.com/PCSX2/pcsx2/pull/3739

**Comment by Helium-4** [comment]
Fixes Full accurate Date + High-Ultra Blending.
Doesn't fix the issue otherwise

**Comment by lightningterror** [comment]
Yes you will still need high+ blending to fix the reflections.

**Comment by Helium-4** [comment]
Hopefully EE timing hack + basic blending doesn't break anything as a workaround because High blending has too much performance issues to be worth using.
