### ISSUE TITLE
[GSDX/GS] Star Ocean 3 - missing shadows

### ISSUE THREAD

**Issue by Kein** [PCSX2/pcsx2#374]
Software:
http://i.imgur.com/3hKtVB5.png

Hardware:
http://i.imgur.com/JOz8VAK.png

Indifferent to D3D version or any GS/VU settings.

**Comment by gregory38** [comment]
Could you generate me a gs dump of the issue?
1/ Install latest git version
2/ hit shift-F8 on the bad rendering image
3/ file will be generated in snaps directory

**Comment by Kein** [comment]
Sure:
https://www.dropbox.com/s/7sm39sjhd7ygmh6/SO3_dump.rar?dl=0

**Comment by gregory38** [comment]
I have implemented a fix on the HW openGL renderer.

However you need to disable the full bilinear filtering.

**Comment by Kein** [comment]
Is backport to D3D remderer possible?

**Comment by gregory38** [comment]
Not by me ;)

Maybe @refractionpcsx2 can give it a look.

**Comment by refractionpcsx2** [comment]
Aww man, is this doing impossible blend in d3d? :p

**Comment by refractionpcsx2** [comment]
Ooh is this the linear filtering thing? I would have thought your change would affect both..

**Comment by gregory38** [comment]
Check the commit before ;)

**Comment by refractionpcsx2** [comment]
Ooh shade mods, that's gonna be fun..  :p

**Comment by refractionpcsx2** [comment]
Shader*

**Comment by Kein** [comment]
@gregory38
I disabled the filtering in GSdx and used HW OGL but there are still no shadows.

Sucks, though, either way, since it is a questionable trade off - bilinear filtering vs main character shadow.

**Comment by gregory38** [comment]
Hum strange, it works on the gs dump. Maybe it depends on others options, I need to check it.

The trade off is not questionable. It is mandatory with current arch. However it is possible to reduce it to only a limited number of calls.

**Comment by gregory38** [comment]
Yes you're right. I need to disable CRC hack. I'm afraid it will break others parts of the game, sigh...
```
UserHacks = 1
UserHacks_DisableCrcHacks = 1
```

**Comment by gregory38** [comment]
I updated a new git version, that work with any filtering method. I only disabled it for palette RT. By the way, you will notice upscaling issues on shadows.

The only way to fix that is to detect the emulated stencil of the game and to replace it with a real stencil buffer. However it is a hack and likely not easy to implement, however it could boost the game.

**Comment by gregory38** [comment]
Hum the CRC hack was added by Gabest in 2009 (see 5a292d202d0dc6728c320da278e4aad3326a59cc)

The purpose is to skip the pseudo stencil, and therefore it removes the shadow rendering.

**Comment by Kein** [comment]
Tested with latest git version on OpenGL without CRC hacks enabled:
![gsdx_20150701204345](https://cloud.githubusercontent.com/assets/623756/8461060/5892ceda-2032-11e5-9770-15ecc7467cab.jpg)

Yeah, I see what you mean now. But besides that, biggest issue is 40FPS tops on my GTX670. Never was the case on DX11 even in 4x-5x upscale.

**Comment by bositman** [comment]
Works fine now in OpenGL. The only issue is that if you disable CRC hacks (thus stop skipping the rendering of the shadow) I get about 12 FPS on native with both DX11 and OpenGL. Not sure if gregory wants to investigate or if it's known

**Comment by gregory38** [comment]
The game uses the alpha channel of the RT as a stencil buffer. Therefore every draw call we must copy the RT to a new texture. Potentially we need to scale down the RT before the copy.

I want to redo the full filtering code to use absolute coordinate. It will avoid the extra scaling but it would cost extra computing on the GPU (likely around 10%). It will help this game that is CPU limited but it would hurt others that are GPU limited. I also hope that it will improve the quality of the shadow.

If it isn't enough, we need to find a way to avoid the extra copy. Potentially with a hack to uses a real stencil buffer instead of a cheap (and costly) emulation. It is the core of the SW/HW renderer, so it won't be easy.

**Comment by Kein** [comment]
No, it does not work "fine" on OpenGL, the shadows still have weird artifacts as on the screenshot above. Depending on the scene they could be more or less pronounced.

Well, Gregory explained it anyway. Should be put into backburner, tho.

**Comment by refractionpcsx2** [comment]
That's probably because you are using upscaling, most bugs still exist with upscaling because upscaling is a hack.  Try in native resolution, if the bugs still exist, then we can look in to it.

**Comment by bositman** [comment]
I didn't notice ANY shadow bug and tested several scenes, so maybe you should retest. Even with scaling everything looked fine.

**Comment by Kein** [comment]
@refractionpcsx2 
Yes, the whole point of the issue is in the context of upscaling, just like the FF12 one (issues#630). Gregory explained  why it happens and why priority for this low so I suggested to put it into backburner.

It is still a valid issue in the end.

**Comment by gregory38** [comment]
I confirm some shadows are a bit broken with upscaling. The issue is that upscaling interpolates everything. However depth or stencil value can't be interpolated. Potentially if we can reduce the number of upscaling/downscaling step, it might work a bit better.

**Comment by Kein** [comment]
https://github.com/PCSX2/pcsx2/pull/763#issuecomment-132214953

**Comment by Kein** [comment]
gregory38, any particular reason why SO3 hit such slowdown in latest revisions on OpenGL HW? I tried it on v1.5.0-dev-709-g055b9c5 with pretty tame settings and got maximum 20-30 FPS when 1.4.0-20160105132032 I can run it pretty much fullspeed on way more aggressive GSdx settings.

Any particular changes that affected the performance in GSdx? Visually nothing was fixed in SO3 and even if I disable most of the exclusive OGL stuff (accur. date/blending/etc) the slowdown is still here.

**Comment by vsub** [comment]
Are you using Partial or Full crc level...with Partial it's extremely slow
https://github.com/PCSX2/pcsx2/issues/984

**Comment by gregory38** [comment]
Normally perf must be the same for same setting. If you have a speed regression please find the first bad commit (note try to disable hw support in hw hack first)

**Comment by gregory38** [comment]
Maybe I have a clue. Could you test the version 615 and 607 of the build bot.

I increased the size of the RT buffer, I'm afraid it slow down the texture cache resizing.

**Comment by Kein** [comment]
**vsub**
Irrelevant since D3D11 has no performance hits.

**gregory38** 
>Maybe I have a clue. Could you test the version 615 and 607 of the build bot.

You are right, the difference happened between these revisions. Wanna me find exact one or you already know it?

**Comment by gregory38** [comment]
No, I don't know because Dx isn't impacted. Most of the code (if not all) apply to Dx too.

If you can find the exact revision it could help a lot.

**Comment by Kein** [comment]
I'd love to find out but there are no compiled revisions inbetween 607<->615 by buildbot and I don't have required environment to build these myself.

**Comment by gregory38** [comment]
Please test those builds
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.723-master
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.643-master
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.612-master

Thanks you,

**Comment by Kein** [comment]
As I mentioned before I don't have means to compile these revisions.

**Comment by gregory38** [comment]
Click on the above link. Select vs2013 or vs2015 then artefact. You will be able to dl the build

**Comment by FlatOutPS2** [comment]
I tried standing in the hallway at the very start of the game, and saw no performance drop. Does it only affect demanding scenes?

**Comment by Kein** [comment]
Environment: core i3770k/GTX670/464.72
GSdx settings: OGL HW, Accurate Date, 2x native, HW Depth, Blending High
PCSX2 settings: default

1.723: performance hit, speed ~62%
1.643: performance hit, speed ~62%
1.723:  performance hit, speed ~62%

>Could you test the version 615 and 607 of the build bot.  

607: everything is fine, performance ok
615: performance hit, speed ~62%

**Comment by vsub** [comment]
Maybe I miss something....are we trying to find which rev make SO3 run so slow while using Partial CRC or?

Btw at the beginning of the game(in the hallway)while using Partial,the speed is also really low

**Comment by Kein** [comment]
All these were tested with Partial, yes. Was there some difference in CRC hacks set between 607 and 615?

**Comment by refractionpcsx2** [comment]
> 1.723: performance hit, speed ~62%
> 1.643: performance hit, speed ~62%
> 1.723: performance hit, speed ~62%

Was the bottom one supposed to be 1.612 ?

**Comment by vsub** [comment]
Tri-Ace games need Full not partual
I just tried those GSdx revs while using your settings and Full CRC and the speed was always 155fps
581,607,615,633,650,669,684,690,695,701,705,709

**Comment by FlatOutPS2** [comment]
> And yes,while using Partial,607 is fine but 615 runs slower

Were shadows enabled in 607 with Partial?

**Comment by vsub** [comment]
Partial is maxing out my gpu core.
Between 607 and 615 there is no difference while using native but with 2x,the speed goes from 25 to 10
2x Scaling,Bilinear(PS2),AFx16,partial,Hardware Depth and Accurate Date disabled,and BUA is set to none.

**Comment by Kein** [comment]
**refractionpcsx2**  
Oops, fixed.

**vsub**  
>Tri-Ace games need Full not partual

I've been running SO3 a lot, it never really was dependable on CRC sets, only tri-ace hack. At least not until latest 709 build:
>Between 607 and 615 there is no difference while using native but with 2x,the speed goes from 25 to 10
Yeah, exactly.

Just to make it clear this particular issue was about the, um, issue under the conditions of non-native res. I wanted to retest it after few months later.

**Comment by vsub** [comment]
Well your gpu is more powerful than mine and I have almost half the speed while using Partial
And because of some change between 607 and 615,Partial became even slower to be used on Tri-Ace games and probably that's why you notest now the performance hit.

Just switch to Full...the speed gain is huge

**Comment by gregory38** [comment]
I think there is potentially a regression. I increased the size of the RT. Texture Cache will do some rescaling which could impact the speed. Bigger RT means more pixels to rescale. It could explain also why people found CR faster.

@Kein could you test with a custom resolution equivalent to your scaling Nx.

**Comment by Kein** [comment]
**@gregory38 **
>could you test with a custom resolution equivalent to your scaling Nx.

Elaborate? You want me to set native custom resolution as SO3 native res multiplied by xN modifier I used?

**Comment by vsub** [comment]
Now this is something unexpected
v1.5.0-dev-721-g265ea82

Partial + Native = 25fps in the hallway
Partial + Custom Res set to native(640x448) = 75fps
Partial + 2x = 10fps in the hallway
Partial + Custom Res set to 2x(1280x896) = 30fps

There is no difference between scaling and custom res(set to the same res as the multiplier)while using Full CRC

**Comment by gregory38** [comment]
Thanks. So it confirms my guess. The issue is the rescaling of the framebuffer. I think it can be improved but it requires massive changes. So it will take some times

**Comment by MrCK1** [comment]
@vsub Are you able to retest this on latest git?

**Comment by Kein** [comment]
Were there any relevant changes?

**Comment by MrCK1** [comment]
I don't own the game, that's why I'm asking somebody to test it and see if anything has changed 😛

**Comment by gregory38** [comment]
Status should be the same. (Same perf issue due to silly framebuffer rescaling).

**Comment by gregory38** [comment]
And also the way the effect is done, sampling fb every draw isn't nice.

**Comment by vsub** [comment]
Well I don't know how helpful this will be but I am not on the PC I used to make those tests(for a while)
I am now on laptop with Win10,i7 6700HQ,GTX1060,16GB ram(PC Win7,i7 4771,GTX750TI,16GB ram)

Also,I am testing the second disk(SO3),not in the hallway from disk 1
Latest beta pcsx2-v1.5.0-dev-2334,settings preset 2 and nothing changed in GSdx except the settings needed to check

Using OGL with Auto\Partual\Full CRC with native\2x\custom set to native\custom set to native 2x....no change at all,the speed is way above full speed

VP2 is also the same....no change in the speed no matter what settings combination I use
