### ISSUE TITLE
Switch Pro Controller not detected

### ISSUE THREAD

**Issue by Snowbola** [PCSX2/pcsx2#3747]
Switch Pro Controller connected via Bluetooth to my Solus computer isn't detected by my PCSX2 emulator. My emulator is running version Stable Build v1.6.0, and I've tried with both OnePAD 0 1.3.0 (Legacy) and OnePAD 0 2.0.0 as Controller Plugins. It works just fine in other emulators such as Dolphin, but it does not here.

**Comment by RedDevilus** [comment]
It's possible that controller has not been added (1.7 dev builds got several new entries).
https://github.com/gabomdq/SDL_GameControllerDB if you need help/examples.

**Comment by lightningterror** [comment]
Status?

**Comment by lightningterror** [comment]
Closing as the user hasn't responded for a while.
