### ISSUE TITLE
Linux PCSX2 Twisted metal Black VU0 Kickstart Autofix

### ISSUE THREAD

**Issue by ImpactKaizer** [PCSX2/pcsx2#3748]
Twisted metal black requires VU0 kickstart to load properly.

![Screenshot_from_2020-09-24_20-59-23.png](https://user-images.githubusercontent.com/71709607/94178871-bacc4280-feac-11ea-8297-9ce26ae7c366.png)

**Comment by refractionpcsx2** [comment]
Does it look right with the VU0 kickstart?

**Comment by ImpactKaizer** [comment]
> Does it look right with the VU0 kickstart?

@refractionpcsx2 it loads fine after enabling it from the testing I've done with it so far.

**Comment by refractionpcsx2** [comment]
Okay cool, I'll add them to the game DB :) Thanks!

**Comment by ImpactKaizer** [comment]
> Okay cool, I'll add them to the game DB :) Thanks!

No problem I'll let you know if anything changes.
