### ISSUE TITLE
Missing widescreen patches in "master" branch

### ISSUE THREAD

**Issue by battletoast** [PCSX2/pcsx2#376]
Currently there are 10 missing widescreen patches in the "master" branch.
But the "cheats_ws" branch contains additionally these patches:
1D2818AF, 08995DEE, B338676A, BB70FFB9, BFB0DFBE, C71A6146, DA6D80ED, E349C1D4, EA1BFC51, F22C1E3B.

I already posted one patch in the forum but I then I realised that there are a few more missing.
Forum link:  (http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=418351#pid418351) 

But I'm not sure if this deviation is on purpose since a patch might "break" a game...

**Comment by mirhl** [comment]
Should be closed after [b07aeb8](https://github.com/PCSX2/pcsx2/commit/b07aeb892afb824b0c8732645adaad1416a9613b)
