### ISSUE TITLE
Honestly pretty cool texture problems on all games

### ISSUE THREAD

**Issue by treymerkley** [PCSX2/pcsx2#3760]
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``
1.7.0.r296.ad1cdc912 (per my package manager, I'm not sure what PCSX2 reports)

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``
I really have no idea what would be relevant for this, other than toggling increased resolution doesn't solve the issue.

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
![gsdx_20200927090501](https://user-images.githubusercontent.com/28458492/94368545-c765bc00-00a1-11eb-823b-0b243f8da50b.png)
![gsdx_20200927090711](https://user-images.githubusercontent.com/28458492/94368547-c896e900-00a1-11eb-81b4-3938a1e418f0.png)

There's a strange blend of textures overlaid on all textures on every game I play. It reminds me of the cells used to compose images in magazines, interesting geometric shapes. I kind of like it myself, but I would prefer to instead have it as an option instead of the only way I play.

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
I just run any given game.

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Intel i5 4690k, Nvidia 1660 GTX, 16Gb memory, Manjaro KDE 64 Bit

**Comment by refractionpcsx2** [comment]
Get the latest dev build and disable "Dithering" in GSdx.

**Comment by treymerkley** [comment]
Figured it was something like that. Leaving it on unscaled works too. Thanks!

**Comment by refractionpcsx2** [comment]
No problem! Yeah unscales basically makes the dithering effect tiny when you upscale, it gets bigger as the resolution goes down, which is "technically" the most correct when upscaling. Choice is yours :)
