### ISSUE TITLE
EE Overclock slider revamp? (Set to any value inbetween current values and support higher OCs)

### ISSUE THREAD

**Issue by Shooting-Starr** [PCSX2/pcsx2#3769]
This is something that's always mildly bothered me with PCSX2, is that the EE overclock slider, rather than being able to be adjusted to any value, only has three defined presets for overclocking, 130%, 180% and 300%. Usually other emulators with overclock settings will allow you to set the value to anything inbetween those, and usually higher than 300%, up to 800% in one particular emulator, BSNES with SuperFX overclocking.

I propose that PCSX2 revamps the EE overclock slider to be more dynamic and support higher values, perhaps up to 800%, which would be more of a joke setting if anything (Perhaps not even exposed in the UI for the user's safety and only achievable by editing PCSX2_VM.ini?), but hey, more power to the user I suppose.

**Comment by lightningterror** [comment]
See https://github.com/PCSX2/pcsx2/pull/1974

**Comment by MrCK1** [comment]
Closing since there was already a discussion regarding this feature.
