### ISSUE TITLE
Plugin names too long to read (First Time Configuration)

### ISSUE THREAD

**Issue by Nicholas-Steel** [PCSX2/pcsx2#3774]
***PCSX2 version:***
v1.7.0-dev-350-g00cc4362e

***Description of the issue:***
Can't fully make out the brackets portion at the end of the names. Only affects "First Time Configuration" UI.
![image](https://user-images.githubusercontent.com/11567846/94831223-d1940b80-044f-11eb-8f5b-df19dbaf6053.png)

***How to reproduce the issue:***
Start PCSX2 with no configuration file.

***PC specifications:***
Windows 10 (2004)
1920x1080
100% DPI

**Comment by RedDevilus** [comment]
Monitor resolution and DPI scaling level?

**Comment by Nicholas-Steel** [comment]
1920x1080, I believe 100% DPI scale.

**Comment by Dreadmoth** [comment]
Plugin names fit correctly when using DPI scaling (at least with the preset values, will test custom scaling in a bit).

Text scaling (Settings → Ease of Access → Display → Make text bigger) can cause this issue, although I couldn't find a value that matches your result exactly.

**Comment by Nicholas-Steel** [comment]
Ah, in that case I  have that set to 120%. When asked about DPI I was thinking of the Scale and Layout settings which is set to 100%.

![image](https://user-images.githubusercontent.com/11567846/94840896-8f24fb80-045c-11eb-9181-6b06158c4c25.png)
