### ISSUE TITLE
Emulation Settings UI horizontally shrinks when applying Speedhacks

### ISSUE THREAD

**Issue by Nicholas-Steel** [PCSX2/pcsx2#3775]
***PCSX2 version:***
 v1.7.0-dev-350-g00cc4362e

***Description of the issue:***
Window size horizontally shrinks slightly. Must close UI and re-open it to get original width again.

***How to reproduce the issue:***
Emulation Settings UI > Speedhacks > Change something and click Apply.

***PC specifications:***
Windows 10 (2004)

**Comment by RedDevilus** [comment]
Yeah that's a known issue, probably fixed when it's ported to QT or there is a cleaner solution for WX.

**Comment by RedDevilus** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/4007
