### ISSUE TITLE
Harry Potter and the Chamber of Secrets/Prisoner of azkaban graphics issue

### ISSUE THREAD

**Issue by DaveR27** [PCSX2/pcsx2#3786]
***PCSX2 version:***
v1.6.0

***PCSX2 options:***
On safest

***Plugins used:***
None

***Description of the issue:***
Right 1/4 of the screen is not rendering properly, which I think could be similar to an old graphics corruption bug found on the wiki. The same thing happens in both games.
https://wiki.pcsx2.net/index.php/Harry_Potter_and_the_Chamber_of_Secrets

When the game starts the console prints out the following about 50 times.
Vif1: Unknown VifCmd! [40]
Vif1: Unknown VifCmd! [3c]

![Capture](https://user-images.githubusercontent.com/30149018/95014368-b57bae80-0689-11eb-9d7a-2e2e6ce17973.PNG)

This is the log of what happened:
[log.txt](https://github.com/PCSX2/pcsx2/files/5323115/log.txt)

***How to reproduce the issue:***
Just load into a new harry potter and the chamber of secrets or prisoner of azkaban

***PC specifications:***
CPU: Ryzen 1800X 
GPU: Asus Rog Strix 1080ti 
RAM: 32GB Trident DDR4
OS: Windows 10 64 Bit)``

**Comment by seta-san** [comment]
try in the latest pcsx2 development build

**Comment by refractionpcsx2** [comment]
yes, this is fixed on the latest development builds (the vifcmd problems), the corruption can be fixed with one of the hw hacks, Either Preload Frame Data, Fast Texture Invalidation or Auto Flush, I forget which.

but definitely get the latest master for stability in that game.

**Comment by lightningterror** [comment]
Frame Buffer Conversion, anyway closing.
