### ISSUE TITLE
Persona 3 Fes invisible cards

### ISSUE THREAD

**Issue by Geniusssmit** [PCSX2/pcsx2#3802]
***PCSX2 version:***
v1.7.0-dev-420

***PCSX2 options:***
Safest preset

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
Cards on "shuffle time" after battles are invisible, therefor it's not possible to choose them correctly.
![pcsx2_VOgk3bRYyK](https://user-images.githubusercontent.com/24941285/95189805-08af4780-07d7-11eb-90d7-bae7eda877e7.jpg)
![pcsx2_OdCu9m6Jo8](https://user-images.githubusercontent.com/24941285/95189810-0b11a180-07d7-11eb-99b5-3c7e4f101908.jpg)

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
After first 2-3 battles "shuffle time" appears, win the battle.

***PC specifications:***
ryzen 2600, rtx 2080, windows 10 1809

**Comment by Geniusssmit** [comment]
same with sw, gsdx11 and opengl.

**Comment by Geniusssmit** [comment]
Savestate
[SLPM-66690 (232C7D72).00.zip](https://github.com/PCSX2/pcsx2/files/5333138/SLPM-66690.232C7D72.00.zip)

**Comment by tadanokojin** [comment]
Did you try any clamping/rounding?

**Comment by Geniusssmit** [comment]
That didn't help

**Comment by Geniusssmit** [comment]
turns out it was widescreen patch. without it everything is fine

**Comment by tadanokojin** [comment]
No problem, thanks for letting us know.
