### ISSUE TITLE
DYNASTY WARRIORS Lines the screen in the gameplay

### ISSUE THREAD

**Issue by Maximus9876** [PCSX2/pcsx2#3810]
when i play the screen spliting in half and when i walk Flattened lines appear
please i want a solution 

My device specifications
RTX 2060 SUPER
i5-9600K

**Comment by tadanokojin** [comment]
Please properly fill out the included [Issue Template](https://github.com/PCSX2/pcsx2/blob/master/ISSUE_TEMPLATE.md).

**Comment by refractionpcsx2** [comment]
Failed to fill out the template or provide any useful details.
