### ISSUE TITLE
Spu2-X.dll (from stable build v1.6.0) no longer works with v1.7.0-dev-435 on Win7

### ISSUE THREAD

**Issue by scju** [PCSX2/pcsx2#3814]
***PCSX2 version:***

v1.7.0-dev-435

***PCSX2 options:***
Tried with default settings.

***Plugins used:***
Spu2-X.dll (from stable build v1.6.0) 

PS - I have seen [https://github.com/PCSX2/pcsx2/pull/3244](https://github.com/PCSX2/pcsx2/pull/3244)

***Description of the issue:***
When I launch a game, a message shows "Could't load xaudio_2.8.dll Error code: 126", so I have to change the Module in SPU2 Settings to "WaveOut (Laggy)". 

This wouldn't happen with pcsx2-v1.7.0-dev-116.

***PC specifications:***
CPU: Intel i7 9700f 
GPU: Asus GTX 1660 
OS: Windows 7 64 Bit

**Comment by tadanokojin** [comment]
Please read our [System Requirements](https://github.com/PCSX2/pcsx2#system-requirements).

We no longer support Windows 7 as of 1.7.0. You are welcome to continue using it but you will likely run into issues such as these.
