### ISSUE TITLE
Texture missing on SSX

### ISSUE THREAD

**Issue by luismglvieira** [PCSX2/pcsx2#3817]
Hello. SSX has missing textures after I reinstalled my OS. I kept all my settings from before and installed the same PCSX2 version and same plugins. This game was working before, but now all maps are like shown on the image.

I've tried different bios and different isos for this game (USA and EU). Also tried to mess around with some settings, but I think it shouldn't matter if these settings worked before? The emulator didn't complain at all when I use a --cfgpath="" script. Still I tried to fool around and nothing worked. All other games are working just like before with my scripts and configs!

Since I've reinstalled my whole OS I wonder if I'm missing anything?? But other games that I've tried so far are working just right they were before. Games that I've tried: Devil May Cry, Gran Turismo 4, SSX3, FIFA Street 2, We Love katamari, Def Jam FFNY and NBA Street V3 (obviously some of them are from EA Big) and they all worked perfectly, even tho I only played a few seconds of each to see what's going on.

I've also tried Burnout 2 and I noticed some texture flickering but I can't tell 100% sure if it was there before. I'll longplay these games a bit more during the week, just wanted to get this out there in hope for an easy fix.

Settings:
PCSX2 v1.7.0-dev (installed from AUR) 
Safe preset 3 or 2 with nearest EE/FPU and nearest VU0/VU1
AVX2 with OpenGL
Computer with Manjaro Linux XFCE, I7 7700, RX580 8G

If you wonder why I'm using 1.7 it's because that's the only one that worked for me... and this game was working perfectly before. All of them were.

![ssx](https://user-images.githubusercontent.com/64651331/95701977-e7b97d00-0c42-11eb-8037-b244c50d80aa.png)
![Screenshot_2020-10-12_05-45-00](https://user-images.githubusercontent.com/64651331/95702977-ce660000-0c45-11eb-949e-3d11b3fa907f.png)
![ssxconfig](https://user-images.githubusercontent.com/64651331/95701978-e8eaaa00-0c42-11eb-910f-04ec796ec4da.png)

**Comment by refractionpcsx2** [comment]
Why have you changed all your rounding to nearest? It should be on Chop/zero unless you specifically need to change it for a game.

Also as you're on an AMD graphics card, I'd recommend using Direct3D11 over OpenGL as the OpenGL driver for AMD is pretty poor.

**Comment by luismglvieira** [comment]
Yes this game requires that because otherwise the character disappears

**Comment by refractionpcsx2** [comment]
Does it need both? 🤔 didn't know that was an issue

**Comment by luismglvieira** [comment]
Actually don't know if it needs both, but turning them to default didn't change anything :(

**Comment by lightningterror** [comment]
So do we know which setting is needed, make sure you restart the emu so changes are applied properly.

**Comment by refractionpcsx2** [comment]
We've located a regression, if you can use a GSDX from build 385 or lower, the holes in the ground should be gone

**Comment by luismglvieira** [comment]
> We've located a regression, if you can use a GSDX from build 385 or lower, the holes in the ground should be gone

Yes using a different GSDX worked and fixed the issue! Thank you. 

pcsx2-git from the AUR only comes with one gsdx plugin, and the pcsx2 package comes with some more options. So I had to uninstall pcsx2-git and install pcsx2 from the official pacman repository which now includes 1.7 and not 1.6! So I think every game is running perfectly now, but I should do some more testing.

I have a question tho, I had to uninstall and re-install because I don't know where to find plugins for linux... sorry for a dumb and offtopic question, but I've looked around for 2 hours and couldn't find anything! The tutorials here on github also don't mention how to add new plugins, but it might be my mistake!

If this is offtopic feel free to close this issue, but I don't think it's very straightforward to add new plugins.

Thanks a lot for the help and the great work on this fantastic software

**Comment by tadanokojin** [comment]
This should be sorted on new builds as I reverted the offending commit.
Can you please try #3858 to make sure I don't regress this again?

**Comment by luismglvieira** [comment]
> This should be sorted on new builds as I reverted the offending commit.
> Can you please try #3858 to make sure I don't regress this again?

Hey, I'm down to help out, but I don't understand what I'm supposed to do

**Comment by refractionpcsx2** [comment]
Just grab this build and try it https://github.com/PCSX2/pcsx2/suites/1386616504/artifacts/22874293

**Comment by luismglvieira** [comment]
> Just grab this build and try it https://github.com/PCSX2/pcsx2/suites/1386616504/artifacts/22874293

Uhh I don't use Windows tho is that an .exe?

**Comment by refractionpcsx2** [comment]
Oh, I can't help you then :( You'd need to grab the code for the PR and compile it yourself, I can't help with linux

**Comment by luismglvieira** [comment]
Ok, so I forked it, change the 2 files, cloned it and tried to build it following these instructions https://wiki.pcsx2.net/PCSX2_Documentation/Compiling_on_Linux

But it didn't work at all, gave me some errors. I installed all dependencies from wiki but still get a lot of errors... Sorry if this is already out of the initial post's spectrum. But really never done this type of building from source myself.

`-- Skip build of common libraries: missing dependencies:check these libraries -> wxWidgets (>=3.0), aio
-- Skip build of pcsx2 core: missing dependencies:check these libraries -> wxWidgets (>=3.0), gtk2, zlib (>=1.2.4), pcsx2 common libs
-- Skip build of dev9ghzdrk: missing dependencies:check these libraries -> gtk2, pcap, libxml2
-- Skip build of GSdx: missing dependencies:check these libraries -> opengl, png (>=1.2), zlib (>=1.2.4), X11, liblzma
-- Skip build of onepad: missing dependencies:check these libraries -> sdl2, X11, gtk2
-- Skip build of onepad_legacy: missing dependencies:check these libraries -> sdl2, X11, gtk2
CMake Error at CMakeLists.txt:46 (add_subdirectory):
  The source directory

    ~/Software/AUR/pcsx2/3rdparty/fmt/fmt

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "~/Software/AUR/pcsx2/build/CMakeFiles/CMakeOutput.log".
See also "~/Software/AUR/pcsx2/build/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory
ninja: error: loading 'build.ninja': No such file or directory
`

**Comment by refractionpcsx2** [comment]
You need to do a git update of submodules

**Comment by luismglvieira** [comment]
> You need to do a git update of submodules

Ok now it worked, but I can't find the binary file mentioned on the wiki:

` ./bin/pcsx2-dev`

**Comment by kenshen112** [comment]
Maintainer of the pcsx2-git package here   try building with -DGTK3_API=TRUE

**Comment by refractionpcsx2** [comment]
This is now fixed in master
