### ISSUE TITLE
SDL2 issues with the plugins

### ISSUE THREAD

**Issue by micove** [PCSX2/pcsx2#382]
PCSX2 version: 1.3.0 GIT 9e8b0b5

Issue:
A simple test using GSdx with the (null) (null) renderer, booting with no disc, using SDL audio in SPU2-X and the rest of the values default (basically deleted the config folder).

SDL-1.2 the booting sound is heard "ok"
SDL-2 the booting sound is pure garbage and LOUD

Possible cause:
SDL is not really good or is very simplistic with audio. In other applications that use it for sound I have seen that for example if you set the frequency to 48000 (as done by SPU2-X) and the input has a different frequency then SDL tries some very simple linear resampling which is basically
- 12000, 24000, 48000, 96000, 192000 work (basically x2/x4 up and down)
- Any other value is forced to play at the wrong frequency

I mention this because SDL2 tends to play really loud static garbage when given a "wrong" frequency similarly to what I experienced while SDL-1.2 tends to speed it up a bit in the cases I have seen. Both are wrong but the SDL-1.2 issue is easy to miss.

From what I remember the PS2 upsampled everything to 48000 but the input did not have to be at that frequency. If the frequency is not a multiple then both SDL version do the wrong thing but SDL2 is the most obvious one since it's pure garbage. 

This issue could be caused by something else since I have not read the plugin code that much therefore this is just a hypothesis.

Also as a Note:
https://bugs.archlinux.org/task/38960
Seems to suggest there is an issue with SDL2 and onepad too but I'm not sure if this was already reported/fixed.

**Comment by OrdinaryMagician** [comment]
I'd like to bump this a bit with saying that onepad does work now with SDL2, although every time force feedback kicks in, the gamepad will be stuck vibrating forever. SDL2 audio is still just a garbled mess, which sucks because portaudio randomly decides to go silent for me until I reload the plugin.
