### ISSUE TITLE
[wx] dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by micove** [PCSX2/pcsx2#384]
PCSX2 version: 1.3.0 GIT 9e8b0b5

Okay last issue.

Issue:
If I remove the configure folder to setup a clean 1st time configuration on in general change plugins.

I tend to get a lot of
[wx] dlopen: cannot load any more object with static TLS
(p) (L) The configured SPU2 plugin file is not a valid dynamic library(LoadCorePlugins) 

Checking the plugins I see
$ readelf -W -a libzzogl-0.4.0.so | grep STATIC_TLS
 0x0000001e (FLAGS)                      TEXTREL STATIC_TLS
$ readelf -W -a libspu2x-2.0.0.so | grep STATIC_TLS
 0x0000001e (FLAGS)                      TEXTREL STATIC_TLS

Since we are using a global resource it gets exhausted and fails to load the plugins with dlopen. 

More info in
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1124987
[2]https://www.cygwin.com/ml/libc-help/2013-11/msg00033.html

In [2] there are some suggestions to solve this and I'm not sure asking to bump DTV_SURPLUS in glibc is going to work. Not sure how feasible is to dynamically link to them instead of dlopen or to just pack the plugins inside the binary like dolphin-emu does now.

This is kind of minor issue since with a little fiddling the plugins get loaded.

**Comment by gregory38** [comment]
zzogl support is dropped so no way to toggle the GS plugin anymore. Therefore no more issue :)

I will close the bug report. If you aren't happy with current situation, please reopen it.
