### ISSUE TITLE
[Windows] Allow different aspect ratio to be detected as Hybrid Full Screen by Windows -->Less lag

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#3842]
As of today, PCSX2 with 'EnableVsyncWindowFlag=enabled' has to be stretched to be promoted to exclusive fullscreen by Windows. This allows to have less stuttering/lag as there is no buffering.

This [PR](https://github.com/PCSX2/pcsx2/pull/3588) tried to solve this (and worked for me) but was then abandoned.

**Comment by RedDevilus** [comment]
I believe several PRs helped while this been the final piece: https://github.com/PCSX2/pcsx2/pull/5485

**Comment by Immersion95** [comment]
Yes you're right :)
