### ISSUE TITLE
Support for BZ2 (from Old CDVD plugin).

### ISSUE THREAD

**Issue by backgamon** [PCSX2/pcsx2#3851]
Can you add the support, for running iso, of the BZ2.
I compressed many of my games on this format.
The newer version of PCSX2 doesn't recognize any of my files.

**Comment by orbea** [comment]
While this is not what you are asking I suspect you will get better results by using maxcso instead which will losslessly compress ps2 (And psp) games.

https://github.com/unknownbrackets/maxcso

**Comment by backgamon** [comment]
I dumped almost all my PS2 games, and for gain size i used since some years the compress option from linus plugin.
I don't want to redump all again x_x
http://backgamon.free.fr/collec/ps2c.JPG
http://backgamon.free.fr/collec/ps2cb.JPG

**Comment by refractionpcsx2** [comment]
Could you not extract your games with a tool such as 7-zip,  then recompress them in to another format such as CSO using a tool such as maxcso?

**Comment by backgamon** [comment]
> 
> 
> Could you not extract your games with a tool such as 7-zip, then recompress them in to another format such as CSO using a tool such as maxcso?

All are possible....it just take manyyy times xD

**Comment by refractionpcsx2** [comment]
Well i can guarantee that'll be quicker for you than waiting for us to implement bz2 on the internal ISO reader ;)

**Comment by lightningterror** [comment]
Closing as low priority as other formats exist.
