### ISSUE TITLE
Gitaroo Man: Incorrect layering of gui elements in OpenGL

### ISSUE THREAD

**Issue by sonicfind** [PCSX2/pcsx2#3856]
***PCSX2 version: v1.7.0-dev-475-xxx***

***Plugins used:***
Default settings with OpenGL

***Description of the issue:***
The layering/z-position of the on-screen gui elements are out of place. During certain moments, elements may disappear off the screen.
_(Note: the screenshots looked squished as pcsx2 didn't apply widescreen settings to them)_
How it should look:
![gsdx_20201022161248](https://user-images.githubusercontent.com/52436993/96933470-1f67c680-1486-11eb-9070-df14c5958bfb.png)
How it looks:
![gsdx_20201022161006](https://user-images.githubusercontent.com/52436993/96933522-39090e00-1486-11eb-889b-5aedb3941d51.png)

***How to reproduce the issue:***
Play any stage with OpenGL. Other renderers are unaffected.

***Last known version to work:***
v1.7.0-dev-464-xxx

***PC specifications:***
CPU: i5-8250U
GPU: UHD 630
OS: Windows 10 Pro 64 Bit)``

**Commit in question:** https://github.com/PCSX2/pcsx2/commit/2608673ca7f78ccacb16ac9ef5cd89f379f65f93

**Comment by sonicfind** [comment]
**New, and probably more useful, GS Dump:** https://drive.google.com/file/d/1sMBZPK1p2XOfxzMq6tKSk6tGQ96I6HA4/view?usp=sharing

**Comment by sonicfind** [comment]
Fix provided by @refractionpcsx2

**Comment by refractionpcsx2** [comment]
I haven't fixed it yet :P The build I sent you was incorrect behaviour.

Did you check your dump before you sent it, because I tried your dump and the UI doesn't flicker at all?
![gitaroo](https://user-images.githubusercontent.com/6278726/96970425-95624100-150b-11eb-91b4-33540575cdd0.gif)

**Comment by refractionpcsx2** [comment]
I just played it myself on master and it seems fine? So I dunno how you got it to flicker, I suspect you've accidentally left some hack enabled.

**Comment by refractionpcsx2** [comment]
Okay seemed to be some jankyness with the Geometry Shader setting on intel integrated graphics
