### ISSUE TITLE
Superman Returns PS2 Still Buggy on 1.7 PCSX2 #3857

### ISSUE THREAD

**Issue by princepart** [PCSX2/pcsx2#3859]
![ffefe](https://user-images.githubusercontent.com/73346536/97005826-e3406e80-1536-11eb-867a-9c1f92c5e816.png)
a 32bit OS in 2020 in my opinion is stupid, unless you have old hardware with 4gb ram or less but then you wont be able to use 1.6 or 1.7 (low speeds due to low specs) versions which is what the requirements are based on. So no, it doesn't need adjusting. Using 32 bit programs like PCSX2 is fine though.

Originally posted by @RedDevilus in #934 (comment)

I been tested this and when i go to the sky it is bugged as hell after this update but on below is still not like before.
![gttggtgt](https://user-images.githubusercontent.com/73346536/97006386-b0e34100-1537-11eb-8fe9-e659cc1185c1.png)
![jnn](https://user-images.githubusercontent.com/73346536/97006578-facc2700-1537-11eb-9715-00e68af32399.png)
![GGRGRGR](https://user-images.githubusercontent.com/73346536/97012949-59959e80-1540-11eb-82c9-76dadd4a0292.png)

**Comment by RedDevilus** [comment]
Requires preload frame data and crc hack atleast at minimum for GSDX HW.

**Comment by princepart** [comment]
Would you contact me please give me your discord or Telegram we can both talk about this.
my discord is 

Cek#9852

**Comment by princepart** [comment]
Would you contact me please give me your discord or Telegram we can both talk about this.
my discord is 

Cek#9852

This is what i use

![dfgdf](https://user-images.githubusercontent.com/73346536/97007683-ade95000-1539-11eb-86cb-beafbdd0fe8a.png)
I use RX 580 8Gb

**Comment by MrCK1** [comment]
Please use the [PCSX2 forums](https://forums.pcsx2.net/) to receive support. This is not the place to discuss.
