### ISSUE TITLE
a message for RedDevilus about Superman Returns Patch not accurate fix

### ISSUE THREAD

**Issue by princepart** [PCSX2/pcsx2#3861]
I have a good graphic card and this still not fixed you just changed something there but now i am not able see buildings in the sky

dont close my thread i just want tell facts

![gtgtgtgtgtgtgtgtg](https://user-images.githubusercontent.com/73346536/97065852-58985780-15a8-11eb-9bb8-7e6ce23b942e.png)

![gtgtgtiiiiiiiii](https://user-images.githubusercontent.com/73346536/97065811-2b4ba980-15a8-11eb-80cc-71cb3b7c8862.png)

**Comment by MrCK1** [comment]
Again, please use the [PCSX2 forums](forums.pcsx2.net) to receive support
