### ISSUE TITLE
CMake failing

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#3867]
As of commit 3dc44bafb33a7291491de5642c8043fa68b8d3fd, CMake fails with the following message:
```
CMake Error at CMakeLists.txt:46 (add_subdirectory):
  The source directory

    /home/shoegzer/Desktop/pcsx2/pcsx2/3rdparty/fmt/fmt

  does not contain a CMakeLists.txt file.
```
Full CMakeError.log: [here](https://pastebin.com/0EL4KdCt)

The last working build tested was against commit 92171ddbaa8a90bed7e0228337bd0dbecd0ed03e, though I suspect it was a4b307a3bd499c9ebbadd268cb06bfdb4b0d056e that caused this issue (haven't had time to bisect).  

@xTVaser or @refractionpcsx2 any ideas here?

Compiled with Linux Mint 20 x64, kernel 5.4 with gcc 9.3.0

**Comment by kenshen112** [comment]
fmt is a submodule that needs to be initalized and cloned run `git submodule update --init --recursive` in the pcsx2 folder before compiling again

**Comment by Shoegzer** [comment]
Thanks @kenshen112, you're right I missed that and I'll close this issue.  Actually couldn't you also just do a `git clone --recursive`?  I don't think the `--recursive` flag is needed in the step you mentioned above.

**Comment by kenshen112** [comment]
Sure either works
