### ISSUE TITLE
PCSX2 crashes upon mouse cursor movement inside game window 

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#3868]
To encounter this issue, load a game,and play for a few minutes (for some reason this issue does not occur immediately).  Move mouse cursor inside game window.  PCSX2 will crash.

Encountered on Linux Mint 20 x64, kernel 5.4, Nvidia GTX 1070M with 450.80 drivers, compiled with gcc 9.3.0 using the following CMake params:

`cmake -DCMAKE_BUILD_TYPE=Release -DGTK3_API=TRUE -DPACKAGE_MODE=TRUE -DXDG_STD=TRUE ..
`

Encountered with commit 3dc44bafb33a7291491de5642c8043fa68b8d3fd,

**Comment by MrCK1** [comment]
Are you using the mouse to control part of the game or just hovering over it? 

Also, do you have your settings enabled to hide cursor over the window, ect?

**Comment by Shoegzer** [comment]
Just hovering over the game window, not controlling any part of the game itself.  Interestingly though, disabling the mouse cursor  seems to stop PCSX2 from crashing (so far anyway, I'll report more if I encounter a crash).  That shouldn't happening either way though, of course.

**Comment by kenshen112** [comment]
What's your graphics card and the driver your using?

**Comment by Shoegzer** [comment]
Updated my OP to include graphics card/driver details.

**Comment by kenshen112** [comment]
And we're sure it doesn't happen on prior commits? Are you building pcsx2 with 32bit or 64bit packages and options?

**Comment by Shoegzer** [comment]
It does happen on prior commits.  I'm building 64-bit.  This started happening soon after the 64-bit builds were introduced, though I was building/using the flatpak distro before then so for all I know the standard package might have had the problem before then.

Also, update: it is still crashing even after turning off the mouse cursor, so there's currently no known workaround for this issue.  Users just have to be extremely careful when using PCSX2.

**Comment by kenshen112** [comment]
Are you using a bluetooth connected mouse perchance?

**Comment by Shoegzer** [comment]
Yes, it's a bluetooth keyboard/mousepad combo.  Also even if I use the connected controller's mousepad (the ds4 has one), I can move the cursor around and it too crashes.  That's also bluetooth-connected.

**Comment by kenshen112** [comment]
This issue is related to #3426 If you know anything about debugging. Could you attempt to post a backtrace of the issue for us?

**Comment by Shoegzer** [comment]
Interesting, that must be it exactly.  So the delay needed to trigger the crash is simply needed for the bluetooth device to lose connection.  Still, that doesn't explain why I can trigger the crash by moving the mouse cursor using the touchpad of the same ds4 controller that stays connected (since I'm using it to actually play the game).    

Also yes, I'm certainly happy to help you debug this.  However, I tried a gdb trace but I get the following message in terminal before the game runs at all (nothing to do with the above crash):
```
Thread 10 "EE Core" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1d4f700 (LWP 22292)]
``` 
Also, I can close this issue and report any further results there if you'd like, just to keep everything in one place.

**Comment by beaumanvienna** [comment]
It will run in gdb when you set EE to 'interpreter'

**Comment by kenshen112** [comment]
That's not actually true. You can run it with the recompiler. But yeah the other thread would be best

**Comment by Shoegzer** [comment]
Well I set the EE to interpreter and ran the gdb, didn't crash until I woke up the bluetooth keyboard.

[Results](https://pastebin.com/DNp8P1Hy)

**Comment by kenshen112** [comment]
Can you type the work backtrace in there then print the results of that?

**Comment by Shoegzer** [comment]
Sure thing, results are [here](https://pastebin.com/yNqMdNgx) (assuming you mean the "word" backtrace and not something else?)

**Comment by beaumanvienna** [comment]
It happens deep in the belly of GTK3.  GTK3 is highly experimental, you probably saw that message during the cmake run. 

I tried installing GTK2 on Ubuntu 20.04 before with no luck. On Mint/Ubuntu 20 I believe you're stuck with GTK3. Do you happen to have an old Mint/Ubuntu 18 install? There you can compile against GTK2. Arch and Manjaro support both GTK2 and GTK3 at the same time. Maybe give that a try? You can compile and run PCSX2 on a Manjaro live CD. (I'm personally quite a sucker for Manajaro as it has all the out-of-the-box luxury Ubuntu gives you plus pacman and AUR access. There is even a Manjaro Cinnamon version ...)
I'm just suggesting to try with a different GTK2 version (or more recent GTK3 version under Arch/Manajaro) to pinpoint the location of this bug to either PCSX2 or the libs.

Just to make sure I understood you correctly in your initial post, you did play around with the "Always hide cursor option", right?

**Comment by Shoegzer** [comment]
Thanks for the detailed explanation, and you're right that I'm stuck with GTK3 on Mint 20 (no downgrade path or alternate system here in the immediate term unfortunately).  Funny you mention, I've actually been planning to use Arch or Manjaro myself at some point in the future but haven't found time to set it up yet - perhaps then I'll try GTK2 (even though I assume the other benefits of GTK3 may outweight this annoyance) just don't know when.

Also, from what you said about pinpointing the error, I assume we still don't quite know if this issue exists in PCSX2 itself or the GTK3 libraries?  I wonder if the GTK team knows of this issue; I use other GKT3 applications and have never encountered this before in case it matters.  In either case I'm happy to report it there.

Finally yes, I did try the "Always hide cursor" option to no avail, sorry for any confusion.

**Comment by beaumanvienna** [comment]
Arch takes a bit longer to install (still easy compared to Gentoo IMO), but Manjaro is just like Mint: But from a USB stick and you get a full-fledged desktop with all services running. I use it as a clean environment for testing PCSX2. OpenGL, Bluetooth, Internet runs out-of-the-box on the live system. 

I did a quick grep for where PCSX2 is manipulating the cursor:
```
~/dev >>> grep -r -n -i "SetCursor" pcsx2/common pcsx2/common pcsx2/pcsx2 pcsx2/plugins                                                                                        
pcsx2/common/src/Utilities/wxGuiTools.cpp:565:            wxSetCursor(wxNullCursor);
pcsx2/common/src/Utilities/wxGuiTools.cpp:568:            wxSetCursor(StockCursors.GetArrowWait());
pcsx2/common/src/Utilities/wxGuiTools.cpp:571:            wxSetCursor(*wxHOURGLASS_CURSOR);
pcsx2/common/src/Utilities/wxGuiTools.cpp:565:            wxSetCursor(wxNullCursor);
pcsx2/common/src/Utilities/wxGuiTools.cpp:568:            wxSetCursor(StockCursors.GetArrowWait());
pcsx2/common/src/Utilities/wxGuiTools.cpp:571:            wxSetCursor(*wxHOURGLASS_CURSOR);
pcsx2/pcsx2/gui/FrameForGS.cpp:182:		SetCursor( wxCursor(wxCURSOR_BLANK) );
pcsx2/pcsx2/gui/FrameForGS.cpp:224:		SetCursor( wxCursor( wxCURSOR_DEFAULT ) );
pcsx2/pcsx2/gui/FrameForGS.cpp:365:	SetCursor( wxCursor( wxCURSOR_BLANK ) );
pcsx2/pcsx2/gui/FrameForGS.cpp:457:		SetCursor( wxCursor(wxCURSOR_BLANK) );
pcsx2/plugins/LilyPad/WindowsMessaging.cpp:156:                SetCursorPos(wmm->center.x, wmm->center.y);
pcsx2/plugins/LilyPad/WindowsMouse.cpp:78:    SetCursorPos(center.x, center.y);
pcsx2/plugins/LilyPad/WindowsMouse.cpp:93:    SetCursorPos(center.x, center.y);
pcsx2/plugins/LilyPad/WindowsMouse.cpp:101:    SetCursorPos(origCursorPos.x, origCursorPos.y);
```
LilyPad you can exclude right away if you're using onepad. wxGuiTool I'd say is also unlikely to cause it. Then it comes down to the four calls in FrameForGS. I would put `printf("(182) before\n");` and `printf("(182) after\n");` around each call (replace 182 with the other line numbers). If it crashes inside you won't get the 'after' message.

**Comment by beaumanvienna** [comment]
There are more contenders in FrameForGS:
`void GSPanel::DoShowMouse()`
`void GSPanel::OnMouseEvent( wxMouseEvent& evt )`
'void GSPanel::OnHideMouseTimeout( wxTimerEvent& evt )'
I would put a similar `printf` at the very beginning and very end of each function to check if it crashes in some of those.

In `GSPanel::GSPanel( wxWindow* parent )` you could also disconnect the mouse events. Comment this out:
```
/*
       // Any and all events which should result in the mouse cursor being made visible
	// are connected here.  If I missed one, feel free to add it in! --air
	Bind(wxEVT_LEFT_DOWN, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_LEFT_UP, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_MIDDLE_DOWN, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_MIDDLE_UP, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_RIGHT_DOWN, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_RIGHT_UP, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_MOTION, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_LEFT_DCLICK, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_MIDDLE_DCLICK, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_RIGHT_DCLICK, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_MOUSEWHEEL, &GSPanel::OnMouseEvent, this);
	Bind(wxEVT_LEFT_DCLICK, &GSPanel::OnLeftDclick, this);
*/
```

**Comment by beaumanvienna** [comment]
> That's not actually true. You can run it with the recompiler. [..]

@kenshen112 is there a trick to do this? Do you have to mask certain signals or something like that? I know to debug dolphin, you have to set "Fastmem" to "False" in its ini.

**Comment by beaumanvienna** [comment]
Sorry, @kenshen112 you were talking about the 32-bit version, right? I usually get the segfault in gdb with the 64-bit version. My bad.

**Comment by beaumanvienna** [comment]
@Shoegzer Maybe try the 32-bit version? Just to see if it has an impact?

**Comment by Shoegzer** [comment]
@beaumanvienna I'd be up for trying that, but I had serious challenges setting up 32-bit in my environment, eventually I abandoned the chroot option and just compiled and installed the flatpak.  I assume the flatpak install defaults to 64-bit now though and I'm not quite sure how you'd force a flatpak to 32-bit in a 64-bit environment unless you do?

**Comment by beaumanvienna** [comment]
https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by Shoegzer** [comment]
Thanks, I've tried the PPA binaries in the past but encountered issues due to the terrible way in which Ubuntu/Mint handles 32-bit runtime libs.  Specifically, the binaries required 32-bit deps that would subsequently force me to uninstall their 64-bit counterparts which I needed on the system.

**Comment by Shoegzer** [comment]
Almost forgot: I tried the printf's in source to trap/ID the issue but I get errors like this upon compiling:
```
FrameForGS.cpp:219:7: error: expected constructor, destructor, or type conversion before ‘(’ token
  219 | printf("(220) before\n");
```
That should have been fine though, it's just a standard printf.  Is there something compiler-specific/sensitive I should be aware of?

**Comment by beaumanvienna** [comment]
Does this work?
```
void GSPanel::DoShowMouse()
{
printf("(220) before\n");
	if( g_Conf->GSWindow.AlwaysHideMouse ) return;

	if( !m_CursorShown )
	{
		SetCursor( wxCursor( wxCURSOR_DEFAULT ) );
		m_CursorShown = true;
	}
	m_HideMouseTimer.Start( 1750, true );
printf("(220) after\n");
}
```

**Comment by Shoegzer** [comment]
Thanks @beaumanvienna, that worked and it now compiles with all the printfs as you recommended above.  However, I see no difference in the terminal or in the gdb results from what I reported earlier - in other words, nothing is printed.

Another observation in case it helps:

Start pcsx2 with ds4 pad and keyboard bt-connected, disconnect/reconnect bt keyboard > crash
Start pcsx2 with only keyboard bt-connected, disconnect/reconnect bt keyboard > no crash

**Comment by beaumanvienna** [comment]
And if you comment out the bindings from [this line](https://github.com/PCSX2/pcsx2/blob/7a2c94f6e1497a254484ae2ccbb9258903c75fa7/pcsx2/gui/FrameForGS.cpp#L197) on downwards?

**Comment by Shoegzer** [comment]
Ah yes, forgot to mention: I did that too, but it had no effect (still crashed).

**Comment by beaumanvienna** [comment]
> [..] I tried a gdb trace but I get the following message in terminal before the game runs at all (nothing to do with the above crash):
> 
> ```
> Thread 10 "EE Core" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffe1d4f700 (LWP 22292)]
> ```

@Shoegzer @kenshen112 

Only for the record, when debugging the x64 version, instead of setting the EE to interpreter, this is how to tell gdb to ignore the segmentation fault:
```
handle SIGSEGV nostop noprint
```

**Comment by tdeeb** [comment]
Any updates on this issue @Shoegzer ?

**Comment by Shoegzer** [comment]
@tdeeb Nope, in fact I inadvertently triggered the issue again today.

**Comment by Mrlinkwii** [comment]
is this still an on master ?

**Comment by Shoegzer** [comment]
Thanks for the reminder - and no, this doesn't occur with the Qt UI on master so I'll close this now.
