### ISSUE TITLE
Godfather and 007: From Russia with Love Texture Shuffle

### ISSUE THREAD

**Issue by tadanokojin** [PCSX2/pcsx2#3875]
Both games have the same issue: insane half-screen texture shuffle with draw recursion where input is 32 bit and framebuffer is 16 bit. So I am rolling the issue into one.

Dumps:
![image](https://user-images.githubusercontent.com/26046960/97780566-cf5ec300-1b5b-11eb-88b0-38dc34d0c19f.png)
[Godfather](https://dumps.pcsx2.net/index.php/s/i4y5N6jGmPMx4sW)

![gsdx_20201031144334](https://user-images.githubusercontent.com/26046960/97780537-ab02e680-1b5b-11eb-9af3-a749ea6fb8a3.png)
[007](https://dumps.pcsx2.net/index.php/s/S4pNFRiwLwWz7mM)

RIP Sean Connery :(

**Comment by Oymat** [comment]
Sadly still happening,
Adding my own gs dump for the godfather:

[Godfather, The_SLUS-21385_20230123031856.gs.zip](https://github.com/PCSX2/pcsx2/files/10475894/Godfather.The_SLUS-21385_20230123031856.gs.zip)

**Comment by web1018** [comment]
This issue in 007 - From Russia with Love still persists unfortunately in the latest nightly build v1.7.4187 in HW - Vulkan mode.  Every time there is some form of explosion in the game, the screen becomes orange. Its consistent pretty much at every part as I'm playing through each level and there are tons of explosions. SW does fix this issue but the framerate just tanks non stop making the game difficult to play. 
 
![103427](https://user-images.githubusercontent.com/51851411/222914968-399bf4f4-76b9-42d8-88fa-634fe5f966a5.jpg)
