### ISSUE TITLE
GSdx regression, both HW and SW, after 16.09.2014

### ISSUE THREAD

**Issue by ramapcsx2** [PCSX2/pcsx2#388]
http://forums.pcsx2.net/Thread-Rogue-Galaxy-Director-s-Cut-gray-squares

**Comment by bositman** [comment]
User reported as fixed can anyone confirm?

**Comment by gregory38** [comment]
Let's close it. If the issue is still here. People can reopen the bug or open a new one

**Comment by ramapcsx2** [comment]
Agreed.
