### ISSUE TITLE
add an mtvu toggle to GameDB options

### ISSUE THREAD

**Issue by GovanifY** [PCSX2/pcsx2#3883]
As mtVU is a speedhack it doesn't work in all possible cases. It might be interesting to add a toggle to the GameDB to disable it on a per-game basis so that we can keep a smooth out of the box experience with the speedhack enabled.

Here is a list of potential games to disable it for:

https://forums.pcsx2.net/Thread-LIST-Games-that-may-not-work-well-with-MTVU?highlight=MTVU

**Comment by GovanifY** [comment]
An initial implementation can be found at https://github.com/RedDevilus/pcsx2/commit/9a4277babaf0e6aa540bf4dd5e72d170eb0f24be

**Comment by GovanifY** [comment]
https://github.com/PCSX2/pcsx2/pull/2235 < is a more advanced implementation, both of them have tricky bugs to fix tho

**Comment by lightningterror** [comment]
Closing as mtvu compatibility has greatly improved.
