### ISSUE TITLE
Kya - Dark Lineage

### ISSUE THREAD

**Issue by nevespt** [PCSX2/pcsx2#3887]
***PCSX2 version:*** development build v1.7.0-dev-490

***Description of the issue:***
Kya - Dark Lineage visual bugs and low fps

***PC specifications:***
Intel Core i7 7700hq; GTX 1060 6Gb; 16gb Ram; Windows 10 64bits

**Comment by refractionpcsx2** [comment]
could you provide screenshots of the visual bugs, maybe a GS Dump too?

How To Create A GS Dump
Single Frame: Shift + F8
Multi Frame: Ctrl + Shift + F8 (hold for x seconds)

Single frame dumps should be suitable for most cases.

**Comment by nevespt** [comment]
Video:
https://cld.pt/dl/download/c8ab2d35-9dd0-43a7-b902-e9ad986b8ca4/kya.avi

Dump:
[gsdx_20201103224831.gs.zip](https://github.com/PCSX2/pcsx2/files/5484490/gsdx_20201103224831.gs.zip)
![gsdx_20201103224831](https://user-images.githubusercontent.com/50218490/98049149-09171e80-1e27-11eb-9d4f-9234f422c34c.png)

**Comment by refractionpcsx2** [comment]
Which visual bugs can you see and what are your GSDX settings?  I get a wall of fog if I use Direct3D 11 or OpenGL with Blending accuracy set to None (although with blending accuracy it leaves an outline)

as for the speed, the only thing I could do to make it go slow was enabling the MTVU speedhack, this game doesn't like that so I recommend you disable it.

**Comment by nevespt** [comment]
just test the game and see

**Comment by nevespt** [comment]
the game i hope can get some software fixes by devs

**Comment by tadanokojin** [comment]
> the game i hope can get some software fixes by devs

Please use the forums for support issues. You failed to post any settings or useful information and you aren't addressing the feedback you are being given. I'm not convinced the issue you are having is the result of a bug as much as it is your settings as I'm unable to reproduce the problem in your 47 minute long video that took an hour to download from whatever that terrible host is.

**Comment by nevespt** [comment]
just search no youtube or teste the game?

**Comment by JetSetter1984** [comment]
Just discovered that INTC Spin Detection is the reason the performance on this game is bad. It must be disabled otherwise the frame rate will constantly fluctuate. Hope you guys can add this to game fixes. Cheers!
