### ISSUE TITLE
[Folder Memory Card] Can't load GTA Vice City Stories save

### ISSUE THREAD

**Issue by sotpapathe** [PCSX2/pcsx2#3888]
***PCSX2 version:***
v1.6.0 from [flatpak](https://flathub.org/apps/details/net.pcsx2.PCSX2).

***PCSX2 options:***
- MTVU: Yes
- All other emulation options at recommended values

***Plugins used:***
- GSdx 1.2.0 AVX2
    - Renderer: OpenGL Hardware
    - All other options at recommended values
- SPU2-X 2.0.0
- OnePAD 0 2.0.0

***Description of the issue:***
In GTA Vice City Stories (PAL), when saving to a folder memory card, the saves are no longer visible from within the game after PCSX2 is restarted. Loading works as long as PCSX2 is not closed between saving and loading. Using a normal 8 MB memory card works as expected. Saves for both folder and 8 MB memory cards attached. Similar to issue #1136 but it seems closed and not getting any attention.

[GTAVCS_folder.ps2.zip](https://github.com/PCSX2/pcsx2/files/5475869/GTAVCS_folder.ps2.zip)
[GTAVCS.ps2.zip](https://github.com/PCSX2/pcsx2/files/5475868/GTAVCS.ps2.zip)

***How to reproduce the issue:***
1. Save a game
2. Close PCSX2
3. Restart PCSX2
4. The game will start from the beginning and no saves will be visible in the load game screen.

***Last known version to work:***
None

***PC specifications:***
OS: Debian 10	
CPU: Intel Core i5-4570 CPU @ 3.20 GHz
GPU: NVIDIA GeForce GTX 760 2 GB
RAM: 8 GB

**Comment by RedPanda4552** [comment]
@MrCK1 Can you merge this into your list in the meta issue?

**Comment by CookiePLMonster** [comment]
Reproduced on Windows 10 with the newest development version - PCSX2 1.7.0-20201117183041.

**Comment by CookiePLMonster** [comment]
GTA Liberty City Stories (PAL) is also affected.

**Comment by CookiePLMonster** [comment]
Correction: This seems to affect every GTA game. After an initial investigation, it seems like the game makes assumptions about the order of files within its own directory structure on the memory card - most likely assumes files are in order of creation, and folder memory cards likely don't preserve that. Further investigation is needed.
