### ISSUE TITLE
fast cdvd

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3890]
move "fast cdvd" from speedhacks to to gamefixes and allow it be activated for automatic gamefixes.

**Comment by MrCK1** [comment]
I don't believe it's planned right now. We're not adding it for Silent Hill because it has the potential to cause problems, and we'd like to try and figure out the real problem if we can.

**Comment by seta-san** [comment]
it's also for victorious boxers

**Comment by ichee** [comment]
#3877 fixes some CDVD related issues with access time.

Could be related. I don't have any of the affected games to test though.
