### ISSUE TITLE
[Feature Request] Patch manager

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3900]
PCSX2 could benefit from having an extra setting specifically for no interlacing. The forum already has a multitude of them like widescreen patches that are already included with the widescreen zip. I don't see why not also include other patches besides widescreen patches like 60 FPS (quality of the patch is very variable though). 

Maybe a comparable method to pack them into a separate zip. Perhaps a way to click a button to fetch them and download them into a location of choice.
Also removes the need for end users to scourge for the patches.

**Comment by tadanokojin** [comment]
I mean, I'm going to say the same thing I have said for a while now. Don't we feel this is sort of working around the obvious better solution? A patch manager that allows users to enable and disable patched individually.

**Comment by RedDevilus** [comment]
Fair enough, i had patch manager in mind for longterm. It for sure is much better on frontend and backend.

**Comment by refractionpcsx2** [comment]
This is now in Qt (though no 60fps patches yet, but that can come later, if we want to)

**Comment by OdinVex** [comment]
> I mean, I'm going to say the same thing I have said for a while now. Don't we feel this is sort of working around the obvious better solution? A patch manager that allows users to enable and disable patches individually.

Possibly even a suggested ranking of patch-entries that could be voted on as best-fit, too, with configuration-area allow/block listing. Such as “I might want all GS patches but no EE patches”, et cetera, handled locally.
