### ISSUE TITLE
GS plugin crash -- "EGL: failed to get a window surface"

### ISSUE THREAD

**Issue by 0phoff** [PCSX2/pcsx2#3903]
***PCSX2 version:***
``v1.7.0`` daily build from 05/11/2020.

***Description of the issue:***
PCSX crashes with the notification: _"GS plugin failed to open"_.
By googling around the most common fix is  to change the version of the GS plugin (AVX, SSE, etc.), but none of them worked in my case. The weirdest thing is that PCSX2 v1.7.0 used to work before updating (had an older build version from +- 6 months ago).
Looking at the log file, it says: _"EGL: failed to get a window surface"_, and then closes all plugins and crashes.

***How to reproduce the issue:***
I guess this is pretty machine specific? I am on Ubuntu (with OpenBox, no stock configuration).

***Last known version to work:***
I know I had a 1.7.0-git version working, but cannot remember when exactly I got it from the PPA.
I got it about 6 months ago I think, but not quite sure (sorry this is vague, I am a user and not a developer).
Right now I downgraded to using the normal version of the PPA (as opposed to daily), and that one is version 1.4.0 and works.

I don't know what changed, but 1.4.0 does not seem as fluid as 1.7.0 was, so I would love to be able to go back to using the daily builds! :)

***PC specifications:***
CPU: Intel i7-7700HQ (8) @ 3.800GHz  
GPU: NVIDIA GeForce GTX 1050 Mobile  
OS: Ubuntu 18.04.5 LTS x86_64  
Host: XPS 15 9560  
Kernel: 4.15.0-122-generic  
WM: Openbox  

Thanks for your awesome work with this project!!

**Comment by Moggers** [comment]
> I guess this is pretty machine specific? I am on Ubuntu (with OpenBox, no stock configuration).
I suspect not, I have a 5700XT, and a Ryzen 9 3900X, running open source AMD drivers and currently experiencing the same behavior. It's been a long time since I last used PCSX2 so I'll try changing obscure settings and rolling back packages until I can narrow it down or find a regression.
Window manager is sway which is probably the only unconventional part of my setup. I was suspecting xwayland issues until I stumbled across this issue, which suggests its present on X11 and wayland.

**Comment by Moggers** [comment]
I was able to work around my issue by forcing GDK_BACKEND=x11 mentioned in #1629  on `PCSX2 1.7.0-20201111220716` using any of the available graphics plugins (`GSdx 64-bit (GCC 10.2.0 SSE2/AVX) 1.2.0 [libGSdx]`, `GSdx 64-bit (GCC 10.2.0 AVX/AVX) 1.2.0 [libGSdx-AVX2]`, `GSdx 64-bit (GCC 10.2.0 SSE4.1/AVX) 1.2.0 [libGSdx-SSE4]`), this is the version installed via the package `pcsx2` from the community repository of Arch Linux.

If I use the pcsx2-git package present in the AUR (resulting in `PCSX2 1.7.0-20201121102932 - compiled on Nov 22 2020`) I only end up with the `GSdx (GCC 10.2.0 AVX2/AVX2) 1.2.0 [libGSdx]` graphics plugin, this is when I observe the above behavior without `GDK_BACKEND=x11`, and with `GDK_BACKEND=x11` I get an assert here: https://github.com/PCSX2/pcsx2/blob/c25ae58c6f08ae59d5a010644be9613b89cbe5ce/common/src/Utilities/Linux/LnxHostSys.cpp#L69-L71
If it helps I can build with debug symbols and get a backtrace but as is I've found a way to make it Just Work.

**Comment by lightningterror** [comment]
What's the status on this with latest master?

**Comment by lightningterror** [comment]
No response, closing as assuming solved.
