### ISSUE TITLE
SSX On Tour - Flickering depth buffer causing heavy stuttering (it's even in a fixed timing)

### ISSUE THREAD

**Issue by gabriele2000** [PCSX2/pcsx2#3909]
***PCSX2 version:***
Development build 1.7.0 - 534

***PCSX2 options:***
![immagine](https://user-images.githubusercontent.com/12186181/98462494-10d31c00-21b5-11eb-9116-d931de2c7def.png)
![immagine](https://user-images.githubusercontent.com/12186181/98462506-1df00b00-21b5-11eb-9693-453173c2ff07.png)
![immagine](https://user-images.githubusercontent.com/12186181/98462508-22b4bf00-21b5-11eb-90a4-e1cb49de7a2f.png)
![immagine](https://user-images.githubusercontent.com/12186181/98462531-4841c880-21b5-11eb-91ea-a4bceea56f3d.png)
![immagine](https://user-images.githubusercontent.com/12186181/98462537-4d9f1300-21b5-11eb-99dd-0a1a15cfc8d4.png)

***Plugins used:***
![immagine](https://user-images.githubusercontent.com/12186181/98462513-2c3e2700-21b5-11eb-80c0-5218760f3b2a.png)

***Description of the issue:***
Depth buffer flickers constantly and it makes the game laggy even if it's running at 100%...
Further tests (with reshade) revealed that there's a constant spike of frametime.
Normal buffer flickers every 5/10 ms and I think it's releated

***How to reproduce the issue:***
-Play the game
-Observe that even if the game speed is perfect there's a annoying lag, even in software mode, if not worse

***Last known version to work:***
Youtube videos shows that PCSX2 1.4.0 used to work fine with that game...
never tested though, 1.4.0 was slow and buggy as hell, that game needed so much hacks to work properly, now it's fine even without hacks, because the project has come a long way since then

***PC specifications:***
-Intel core i7-7700HQ
-16GB RAM DDR4
-SSD 128GB and SSD 500GB samsung 850EVO - PCSX2 is installed on the first one, NVMe M.2 port
-Nvidia 1050TI 4GB

**Comment by tadanokojin** [comment]
What do you mean the depth/normal buffer is flicking? Are you trying to use reshade?

**Comment by gabriele2000** [comment]
> 
> 
> What do you mean the depth/normal buffer is flicking? Are you trying to use reshade?

I was trying to then I noticed that this strange stuttering is somehow linked to the stuttering.
I'll do a video and I'll send it

**Comment by gabriele2000** [comment]
> 
> 
> What do you mean the depth/normal buffer is flicking? Are you trying to use reshade?

[Pcsx2 2020.11.08 - 20.28.38.19.Dvr.mp4.zip](https://github.com/PCSX2/pcsx2/files/5507044/Pcsx2.2020.11.08.-.20.28.38.19.Dvr.mp4.zip)
NO RESHADE INSTALLED WHILE MAKING THIS VIDEO
There you go, see that annoying stuttering?
Especially in turbo mode?

That's the annoying stuttering that happens only in this game and may be linked to a depth buffer problem...
Reshade helps in the process of throubleshooting because there's one depth buffer (the correct one) that constantly flickers: vertex numbers are constantly switching from a few (from 0 to 10) to numbers like 4935893345 (correct), so empty, full, empty, full...

**Comment by tadanokojin** [comment]
That doesn't really sound all that strange to me. If depth was flickering as you say you'd have much more problems than just stuttering. Honestly it probably tells you more about how the game is performing the post-processing that's evident in the video.

You're welcome to provide a GS dump of a couple of frames for me to look at.

**Comment by gabriele2000** [comment]
> 
> 
> That doesn't really sound all that strange to me. If depth was flickering as you say you'd have much more problems than just stuttering. Honestly it probably tells you more about how the game is performing the post-processing that's evident in the video.
> 
> You're welcome to provide a GS dump of a couple of frames for me to look at.

Got it.
I'll upload a GS dump as soon as possible, thanks again for your help

**Comment by gabriele2000** [comment]
> 
> 
> That doesn't really sound all that strange to me. If depth was flickering as you say you'd have much more problems than just stuttering. Honestly it probably tells you more about how the game is performing the post-processing that's evident in the video.
> 
> You're welcome to provide a GS dump of a couple of frames for me to look at.

[SSX On Tour (2020-10-08 23-52-38).zip](https://github.com/PCSX2/pcsx2/files/5507326/SSX.On.Tour.2020-10-08.23-52-38.zip)

There you go

**Comment by tadanokojin** [comment]
That's a block dump not a GS dump but no matter, I have a tester with the game.

So nothing particularly out of order here, the game renders to a draw buffer and then copies that over to the display buffer. It presents the previous frame and then immediately the new frame. Basically, frame doubling. It's only presenting 30 unique frames a second.

**Comment by gabriele2000** [comment]
> 
> 
> That's a block dump not a GS dump but no matter, I have a tester with the game.
> 
> So nothing particularly out of order here, the game renders to a draw buffer and then copies that over to the display buffer. It presents the previous frame and then immediately the new frame. Basically, frame doubling. It's only presenting 30 unique frames a second.

Whops, sorry for the inconvenience...
For future reference, how can I do make a GS dump?

**Comment by tadanokojin** [comment]
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by tadanokojin** [comment]
Closing since OPs issue appears to be a support request rather than anything related to an issue with the emulator.
OP: Please feel free to create a thread on the forums for further assistance.
