### ISSUE TITLE
Feature Request: Ability to swap controller port on the fly

### ISSUE THREAD

**Issue by Earnestly** [PCSX2/pcsx2#3911]
I only have a single controller, a dualshock3, hooked up via USB that I would like to switch between "controller ports" so that in effect I can swap between Player 1 control and Player 2 control.

This would be useful to me for co-op games where I can alternate control across two playable characters.

I've looked for documentation on how this might be done but I've not been able to find anything so if there is already a way of achieving this I'd be glad to know.

**Comment by RedDevilus** [comment]
You could use a keyboard as a second controller, use same keybindings on both ports but then you don't have alternate control.
Effectively you are looking for switch keybindings hotkey between two pads. There is no hotkey for that unless you want to go constantly in the settings.
![image](https://user-images.githubusercontent.com/24227051/98602911-7cb2a300-22e1-11eb-9d19-e95981305cc3.png)

Would be easier to get a second controller, it doesn't even need to be an official Sony one as long as it supports Xinput (or Dinput or via steam).

**Comment by Earnestly** [comment]
Ah balls, I should have mentioned that this is on Linux (1.7.0-545-g12c21de66).  I can't seem to find anything in the settings to "swap" controller bindings.  (I have come across this suggestion through my googling before making an issue here.)

My current solution is to use keyboard bindings and it works, mostly, but is awkward.  The alternating input is wanted, if both controlled at the same time it would cause problems as the roles taken are different.

**Comment by RedDevilus** [comment]
Onepad is missing features compared to Lilypad on Windows. Onepad legacy does allow you to remap where-as normal onepad is just a preset per controllerade by people.

**Comment by lightningterror** [comment]
Already done on Qt.

**Comment by Vidikron** [comment]
Can someone help me with this?  This was closed as “done”, but I’m not seeing the option.  I’m playing PCSX2 on my Steam Deck.  When I try to use a controller the Steam Deck controls get assigned to Port 1 and any BT controller gets Port 2.  But if the game being played doesn’t support being played via Port 2 then you can’t use the BT controller.  This is especially problematic when trying to play docked when they built in controls are not accessible.  

I’ve looked through the controller settings and don’t see any way to quickly swap the ports or change the controller assigned to the each port.  Am I missing something?

**Comment by RedPanda4552** [comment]
Please use the Discord or Forums for support. GitHub is an issue tracker for technical issues.
