### ISSUE TITLE
Toggle software emulation on macOS (F9)

### ISSUE THREAD

**Issue by Rastafabisch** [PCSX2/pcsx2#3914]
***PCSX2 version:***
``v1.7.0-dev-243, macOS``

***Description of the issue:***
``On the macOS build toggling via F9 does not work. (Other F-keys neither, though I do not know wether they are supposed to do anything.) – Nor there appears to be a menu option to achieve the same or any way to customise managing keyboard shortcuts, though the macOS built-in capabilities work for this (I mapped cmd+W to shutdown, and cmd+R to Boot ISO (full))``

***How to reproduce the issue:***
``always``

***Last known version to work:***
``non``

**Comment by tadanokojin** [comment]
You should probably post your issue [here](https://forums.pcsx2.net/Thread-Native-Mac-Testing-Build) so @tellowkrinkle can have a look at it. The emulator in it's current state doesn't support macOS but we're working towards that goal.

**Comment by tellowkrinkle** [comment]
Fixed by #5792
