### ISSUE TITLE
Slow gameplay on Shin Bakusou Dekotora Densetsu: Tenkatou Icchojou Kessen

### ISSUE THREAD

**Issue by Dark-Magician-S62** [PCSX2/pcsx2#3916]
**PCSX2 version:** v1.7.0-dev-140-gb28382632-windows-x86

**PCSX2 options:**
![Screenshot_77](https://user-images.githubusercontent.com/74263295/98719449-8afad080-236e-11eb-814f-72819a63a8d7.png)
![Screenshot_78](https://user-images.githubusercontent.com/74263295/98719473-90f0b180-236e-11eb-90e0-b9c06c3cbce3.png)
![Screenshot_79](https://user-images.githubusercontent.com/74263295/98719499-98b05600-236e-11eb-8d93-7e6e50c68b17.png)
![Screenshot_80](https://user-images.githubusercontent.com/74263295/98719551-a8c83580-236e-11eb-802e-e31a02c2e8c2.png)
![Screenshot_81](https://user-images.githubusercontent.com/74263295/98719563-ae258000-236e-11eb-84a5-186f66df98f6.png)
![Screenshot_82](https://user-images.githubusercontent.com/74263295/98719578-b382ca80-236e-11eb-9f71-0d588674d340.png)

**Plugins used:**
Default plugins
![Screenshot_88](https://user-images.githubusercontent.com/74263295/98720351-3efc5b80-236f-11eb-8a92-9eb1ac765fa8.png)

**Plugin settings:**
![Screenshot_83](https://user-images.githubusercontent.com/74263295/98719632-c5646d80-236e-11eb-8a66-804a8f0ba6dd.png)
![Screenshot_84](https://user-images.githubusercontent.com/74263295/98719636-c6959a80-236e-11eb-91c6-55b20c1b64ab.png)
![Screenshot_85](https://user-images.githubusercontent.com/74263295/98719650-c8f7f480-236e-11eb-8c87-13cdf2cead72.png)

**Description of the issue:**
The game slow down (from 59.97 to 25-40 fps) when a race starts

**How to reproduce the issue:**
Just start a race (does not matter day or night time) and the game will drastically slow down to around 25-40fps

**PC specifications:**
CPU: AMD FX-6300 3.5GHz: Gigabyte GTX 750Ti 2GB OS: Windows 10 64 Bit, RAM: 16GB (2x4GB+1x8GB)

**Comment by refractionpcsx2** [comment]
Support requests go to the forum please: http://forums.pcsx2.net/
