### ISSUE TITLE
Daily Build PPA

### ISSUE THREAD

**Issue by tiagoplacido** [PCSX2/pcsx2#3919]
The daily build ppa is broken, for several weaks now, https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily/+builds?build_state=built
 pinging @helkaluin.
Thanks

**Comment by helkaluin** [comment]
Can't be fixed for the moment, I'm afraid.
It's the submodules. https://github.com/PCSX2/pcsx2/commit/a4b307a3bd499c9ebbadd268cb06bfdb4b0d056e made the fmt pinned to a specific commit as a submodule, but automatic build recipes on Launchpad don't initiate submodules (they just do a git pull).
Before that, submodules aren't really needed for the Linux compile, now they are.
It's a [known bug](https://github.com/PCSX2/pcsx2/commit/a4b307a3bd499c9ebbadd268cb06bfdb4b0d056e), and one workaround is to manually nest the fmt git repo inside the pcsx2 repo when describing the build on Launchpad, but that only works for fetching the latest commit, not a specific one as it the case here.
I think I'll disable builds for now...

**Comment by tadanokojin** [comment]
What about #3838 ?

**Comment by helkaluin** [comment]
Won't work. Even on the yet-to-be-released Hirsute libfmt-dev is still on 6.1.2. Same for the Latest LTS Focal.

Matoro specifically requested at least 7.0.3 in the bug report you linked.

**Comment by helkaluin** [comment]
@tadanokojin I've finally got it building. Can you try now? Focal is done and the others are in-progress.

**Comment by fighuass** [comment]
The PPA is back again!

**Comment by RedPanda4552** [comment]
Closing for now as the PPA is back in working order.
