### ISSUE TITLE
[BUG] Eyetoy support is broken

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#3921]
**Describe the bug**

EyeToy emulation isn't working. It worked at one point while the PR was open, but it's broken now. 

**To Reproduce**

Open PCSX2, USB Settings, select a compatible webcam. (OK)
Boot EyeToy Kinetic. Observe no video. (NOK)
Open USB Settings. Try to open EyeToy Config window. (NOK)

**Expected behavior**

EyeToy Kinetic should work.
EyeToy Config window should open while a game is booted.

**System Info (please complete the following information):**
 - PCSX2 Revision: HEAD
 - Windows 10

**Patch:**
```diff
diff --git a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
index 2e134a633..7ad7fd665 100644
--- a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
+++ b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
@@ -504,7 +504,9 @@ namespace usb_eyetoy
                VideoDevice* videodev = nullptr;
                std::string varApi;
 #ifdef _WIN32
-               LoadSetting(nullptr, port, TypeName(), N_DEVICE_API, str_to_wstr(varApi));
+               std::wstring varApi2;
+               LoadSetting(nullptr, port, TypeName(), N_DEVICE_API, varApi2);
+               varApi = wstr_to_str(varApi2);
 #else
                LoadSetting(nullptr, port, TypeName(), N_DEVICE_API, varApi);
 #endif
```
Probably the same issue is observed for other devices too because the same code is used

**Comment by GovanifY** [comment]
Oh! Found the issues, will PR a more exhaustive patch
