### ISSUE TITLE
[Feature Request] [USB]  Support the DJ Hero turntable dongle

### ISSUE THREAD

**Issue by Crafty-The-Fox** [PCSX2/pcsx2#3924]
**Description**
Implement DJ hero turntable support

**Reason**
It will probably make DJ Hero fully playable, and make me/others able to get past the "cant find compatible controller" menu 

**Examples**
RPCS3 has it using libusb, and you need libusb to make the crossfader work. Or, you can take a look at this github project:

https://github.com/shockdude/gcn-usb-adapter

**Comment by Crafty-The-Fox** [comment]
Assign USB label if possible please

**Comment by lightningterror** [comment]
Added in #9129
