### ISSUE TITLE
[Regression] Sound issue  on The Simpsons

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3937]
Game: https://wiki.pcsx2.net/The_Simpsons_Game

**Describe the bug**
This title is suffering from sound issues (skipping)

**To Reproduce**
Use any recent build (1.6 or any 1.7 dev build) on defaults.

**Expected behavior**
No skipping aka smooth audio.

**When did it last work (Regression)**
Any with SPU2-X with version 1.2 from 2009.

**Comment by Blackbird88** [comment]
Not related to #1393?
