### ISSUE TITLE
[BUG] V-Rally 3 Graphical Issues

### ISSUE THREAD

**Issue by ribolovac510** [PCSX2/pcsx2#3938]
**Describe the bug**
Sun glare and car headlight effects are rendered incorrectly on hardware renderers.

**To Reproduce**
Select any car and track in the time attack quick race mode.

**Expected behavior**
See the screenshots below.

**GS Settings**
Default.

**Emulation Settings**
Default.

**GS Window Screenshots**
Car headlights are missing in the car selection screen. In-game they are rendered incorrectly.
HW:
![gsdx_20201118114819](https://user-images.githubusercontent.com/74596991/99529058-869e6b00-299f-11eb-8f36-d8dd4e6fb010.png)

SW:
![gsdx_20201118114834](https://user-images.githubusercontent.com/74596991/99529071-8b631f00-299f-11eb-9f9d-680d0678f33e.png)

After looking directly at the broken sun glare effects, aborting the race and going back to the car selection screen the headlights are present but rendered incorrectly (the same as in-game):
![gsdx_20201118115456](https://user-images.githubusercontent.com/74596991/99529084-8dc57900-299f-11eb-9a3d-fda940f29821.png)

In-game sun glare effect
HW:
![gsdx_20201118120212](https://user-images.githubusercontent.com/74596991/99529118-9d44c200-299f-11eb-8061-892f25bdeccd.png)
SW:
![gsdx_20201118120216](https://user-images.githubusercontent.com/74596991/99529136-a170df80-299f-11eb-9bcd-591c7ebc0ad1.png)

HW:
![gsdx_20201118115052](https://user-images.githubusercontent.com/74596991/99529092-91590000-299f-11eb-8325-1601398e8253.png)

SW:
![gsdx_20201118115056](https://user-images.githubusercontent.com/74596991/99529100-93bb5a00-299f-11eb-9de7-44b89a7aab45.png)

**System Info**
 - PCSX2 Revision: v1.7.0-dev-605
 - OS: Windows 10 1909
 - CPU: Ryzen 5 2400G
 - GPU: GTX 1660 SUPER

**Logs and Dumps**
[vrally3_headlights.zip](https://github.com/PCSX2/pcsx2/files/5559946/vrally3_headlights.zip)
[vrally3_sunglare.zip](https://github.com/PCSX2/pcsx2/files/5559947/vrally3_sunglare.zip)

**Comment by lightningterror** [comment]
Can you see if preload frame data hw hack helps?

**Comment by ribolovac510** [comment]
Looks like it pretty much solved all of the issues. Thank you!
