### ISSUE TITLE
please add this crc god of war us

### ISSUE THREAD

**Issue by logan83** [PCSX2/pcsx2#395]
sir,,,please just add this crc of gow game,,F2A8D307.. I 'm give up to compile gsdx.dll...its confusing..

**Comment by bositman** [comment]
What region and language of the game is that CRC from? We already have all US versions.

**Comment by Ryudo300** [comment]
In an earlier issue posted by the OP he mentioned his Region ID was SCUS 97399 with that CRC. Looks to be a bad rip, because the correct CRC for the US region is D6385328

**Comment by gregory38** [comment]
No news. I close the bug report.

**Comment by gregory38** [comment]
For the history, future openGL renderer will be compatible with GoW without any CRC (see branch gow-depth-support)
