### ISSUE TITLE
scarface the world is yours - Black screen when switching to progressive scan

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#3954]
PCSX2 1.7.0-20201127075728 - compiled on Nov 27 2020

When switching the display to progressive scan in game I get black screen and that is it nothing happens after it doesn't reverts back to interlaced even.
Using default speed settings 2
happens on dx11 and open gl
even in software mode 

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/5611103/emuLog.txt)

**Comment by tadanokojin** [comment]
Can you test #3957? It should be sorted now.

And in the future would be kindly fill out the issue template, it wasn't much of a hindrance here but it's good to have a consistent way of reporting issues, which is why it exists.

**Comment by Levan7** [comment]
@tadanokojin 
Sorry don't know how to test that, tested the latest dev build though didn't work

**Comment by refractionpcsx2** [comment]
Yes it isn't in master yet, here's the build you need https://github.com/PCSX2/pcsx2/suites/1576891636/artifacts/28494114

**Comment by Levan7** [comment]
Thank you for the link it sort of worked well yes the progressive scan is enabled and i get the picture but it looks like a negative film image. in hardware mode (dx, open gl) software mode works.

![tony](https://user-images.githubusercontent.com/5770076/100608997-bbf37300-3326-11eb-9eaa-a55f6bb53aca.gif)
gs dump
[snaps.zip](https://github.com/PCSX2/pcsx2/files/5615825/snaps.zip)

**Comment by refractionpcsx2** [comment]
That's just because GSDX has some bugs, if you press F9 twice, that will swap to software mode then back to hardware and will probably solve it temporarily. I think the game is best experienced in software mode (press F9 once)

**Comment by Levan7** [comment]
@refractionpcsx2 
it didn't test it few time

**Comment by refractionpcsx2** [comment]
Then leave it in software mode, it looks fine in that (I checked with your GS dump)

**Comment by Levan7** [comment]
@refractionpcsx2 
Yes the software mode is fine, 
Might do a different bug report on hardware mode but as far as i can see the thing fixed the progressive scan switcher

**Comment by refractionpcsx2** [comment]
Sounds like a good plan :)

I'll close this issue when I merge those changes
