### ISSUE TITLE
SMT Nocturne Visuals freeze as audio plays after 1st Battle

### ISSUE THREAD

**Issue by KickAsphalt** [PCSX2/pcsx2#3956]
**Describe the bug**
When Playing SMT Nocturne, at the end of the first battle between the last hit and the results screen, the game or at least the visuals will freeze while the audio continues

**To Reproduce**
To reproduce, literally just enter the first battle and proceed with regular gameplay. I dont have a clue whether or not this bug occurs with other battles or encounters as I haven't been able to pass the first one

**Expected behavior**
 Expected behavior is that the fight after landing the last hit brings up a result screen and continues as normal.

**GS Settings**

The GS settings are all completely at default
![image](https://user-images.githubusercontent.com/68578450/100530045-d9073500-31b2-11eb-9265-4954e2a61215.png)

![image](https://user-images.githubusercontent.com/68578450/100530052-e4f2f700-31b2-11eb-890c-20bb18725c19.png)

![image](https://user-images.githubusercontent.com/68578450/100530054-ed4b3200-31b2-11eb-8fc6-0232e2ade3bb.png)

**Emulation Settings**

**GS Window Screenshots**

![image](https://user-images.githubusercontent.com/68578450/100530348-79128d80-31b6-11eb-88b4-889e99566840.png)
Note that audio is still playing the battle theme, not sure if thats useful info or not

**System Info (please complete the following information):**
 - PCSX2 Revision: Most Recent PCSX2 as I installed it today
 - OS: Microsoft Windows 10 Home (64-bit)
 - CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
 - GPU: NVIDIA GeForce GTX 1050Ti
GPU Driver Version 27.21.14.5671

**Logs and Dumps**

I would attach GS dump here but there is no "snap" folder anywhere in the pscx2 files nor anything with the .gs or .bmp

**Comment by tadanokojin** [comment]
Tested dev-635 can't reproduce.

Also that's 1.6.0 and we only accept reports for 1.7.0.
Please use the forums for further support https://forums.pcsx2.net/index.php

**Comment by KickAsphalt** [comment]
Where can I get the 1.7.0 version then? I mean, I just downloaded the recommended most recent release on pcsx2.net

**Comment by tadanokojin** [comment]
When I gave you a link to the forums that wasn't an invitation to just go ahead ask me here.
When you pressed the "new issue" button you were given other links for ways to get support.

The issue tracker is for issues and feature requests and not for providing support to the emulator.
