### ISSUE TITLE
syphon filter omega strain pal bug in the textures, corrupted textures 

### ISSUE THREAD

**Issue by oppfl** [PCSX2/pcsx2#3963]
i have a laptop acer nitro 5 , 16gb ram , gtx 1050ti , intel core i7 7700hq 2.8ghrz up to 3.8ghrz , ssd 237 gb, and this what happen in syphon filter omega strain (i am playing the pal version because there is italian dub but i assume it would happen even in the other versions) when in go in that specific part of the level of the mission in tokyo: https://imgur.com/0fi4tki , currently i am using the latest beta version of pcsx2 1.7.0 developed and uploaded from the page of the automated updates , i tried various settings but nothing seem to work , if the image from the link doesn't appear immediately then just reload the page various times

**Comment by MrCK1** [comment]
Please use https://forums.pcsx2.net for general support. Thank you.

**Comment by oppfl** [comment]
> 
> 
> Please use https://forums.pcsx2.net for general support. Thank you.

is ok to post here since it is the section of the bugs ,besides my post in the general support of that forum would just end up with posting the problem here so don't bother me , fuck you

**Comment by RedDevilus** [comment]
Finding a problem + issue with emulation = bug
Being rude + wrong settings/weak settings/outdated OS = user error aka general support

**Comment by tadanokojin** [comment]
You didn't properly fill out the template and it's generally better to escalate though the forums before you create an issue.
