### ISSUE TITLE
syphon filter omega strain

### ISSUE THREAD

**Issue by oppfl** [PCSX2/pcsx2#3965]
i have a laptop acer nitro 5 , 16gb ram , gtx 1050ti , intel core i7 7700hq 2.8ghrz up to 3.8ghrz , ssd 237 gb, and this what happen in syphon filter omega strain (i am playing the pal version because there is italian dub but i assume it would happen even in the other versions) when in go in that specific part of the level of the mission in tokyo: https://imgur.com/0fi4tki , currently i am using the latest beta version of pcsx2 1.7.0 developed and uploaded from the page of the automated updates , i tried various settings but nothing seem to work , if the image from the link doesn't appear immediately then just reload the page various times , and whoever have something to say about how i described the problem can just go fucking kill itself, just fucking solve the problem instead of bitch at insignificant details, this damn bug exist since the 1.5.0 version and no is not because of an outdated operative system , i have windows 10 updated to the latest updates ,andthat damn MrCK1 and PCSX2  can go fucking kill themselves

**Comment by AmFobes** [comment]
You've been reported, get a hint. You aren't getting help here.

**Comment by oppfl** [comment]
> 
> 
> You've been reported, get a hint. You aren't getting help here.

that's because you handicapped shit heads just go nuts for those stupid things instead of fucking care about solve the damn problem, and i was calm initially but then my post got blocked because of such stupid concerns and so you asked for it , also it is a problem of the emulator so it is a problem of fuking everyone

**Comment by oppfl** [comment]
> 
> 
> You've been reported, get a hint. You aren't getting help here.

oh right and go fucking kill yourself you retarded shit
