### ISSUE TITLE
CDVD/Debugger: Debugger Null Pointer Reference

### ISSUE THREAD

**Issue by Nobbs66** [PCSX2/pcsx2#3967]
**Issue:** 
Pressing run in the debugger without having previously done either a full boot or fast boot causes a null pointer reference and crashes the emu. 

**How to reproduce**

- Open PCSX2
- Open the debugger
- Click run

**Build Tested**
pcsx2-v1.7.0-dev-643-gbe85c568a

**Specs**
i7 5820k
RX 5700
Win10 -1909

**Comment by iMineLink** [comment]
Issue persists on pcsx2-v1.7.0-dev-1074-gbe89e2303-windows-x86 build.
