### ISSUE TITLE
[BUG] Joystick not supported (Padix Co. Ltd. PSX/USB converter) 

### ISSUE THREAD

**Issue by AriaMoradi** [PCSX2/pcsx2#3970]
Originally from @Robository:

> Hello! I using my old psx1 controler with a psx usb converter.
>
> onepad: Joystick (Padix Co. Ltd. PSX/USB converter ,GUID:03000000830500005f20000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.
 
*Note:* Bouncing the issue from https://github.com/AntiMicroX/antimicrox/issues/113
Also Antimicro was abandoned years ago and now our fork is continuing the work. You might want to update your link(s). 
Thanks.

**Comment by lightningterror** [comment]
Can you create and post the controller mapping here?

**Comment by lightningterror** [comment]
@AriaMoradi Status?

**Comment by AriaMoradi** [comment]
I just reported the issue. Ask @Robository

**Comment by lightningterror** [comment]
Like I said you need to create a mapping using AntiMicro or [SDL2 Gamepad Tool](https://www.generalarcade.com/gamepadtool/)
then you can submit the mapping here and we'll PR it upstream, or you can submit the mapping yourself at https://github.com/gabomdq/SDL_GameControllerDB which is where we pull controller db from.

**Comment by lightningterror** [comment]
Any update?

**Comment by AriaMoradi** [comment]
@Robository Is not responsive...

**Comment by lightningterror** [comment]
I'll just close this.
