### ISSUE TITLE
Video stuttering while getting constant 60fps

### ISSUE THREAD

**Issue by belmont1990** [PCSX2/pcsx2#398]
2) What steps will reproduce the problem?

Turn on any ISO in pcsx2.

3) What exactly happens when you experience this issue?

Gameplay video is stuttering while maintaining constant 60fps all the time, no drops at all, no sound distortion. ONLY fix so far is enabling vsync thru pcsx2 settings.
Standard settings give this problem, disabling/enabling speedhacks don't help.
Seems to be some issue with aero/ double buffering/ vsync.

4) What version of PCSX2 are you using? On what operating system? Plugins?

PCSX 2 v1.2.1
Windows 7 x64 AERO ON
Standard plugins from this latest build

Specs:
Pentium G3420 @3.2ghz
GTX 750 1GB DDR5
4GB RAM DDR3

**Comment by belmont1990** [comment]
Could this be solved somehow? Some users actually have this issue, some don't. It is really mysterious why is this stuttering occuring.

**Comment by avih** [comment]
> ONLY fix so far is enabling vsync thru pcsx2 settings.

So why don't you just enable it? Isn't it a good enough solution?

**Comment by belmont1990** [comment]
It is good, but hits performance quite hevily, while 90% of tested games works like a charm without it, vsync gives me actual fps drops quite frequently in some games.

**Comment by avih** [comment]
Correct, because displaying each and every frame on time means more work per frame. Without vsync it may occasionally delay a frame or two but catch up quickly - which is this stuttering.

If you want PCSX2 to manage EVERY frame on time, you probably need a faster CPU that you currently have.

**Comment by belmont1990** [comment]
I can deal with this slight stuttering, it isn't ruining gameplay and still some titles have this almost non visible. This is especially annoying in devil summoner games (static background) and some fast scrolling games (castlevanias, panning camera in dragon quest VIII)

My Pentium G3420 can handle most pcsx2 games well, but without vsync.

**Comment by avih** [comment]
And yet it's too slow to handle most games with vsync. This is not a contradiction, like I explained above. Get a faster CPU or turn on vsync only on games which your CPU is fast enough for.
