### ISSUE TITLE
[Shifted Graphics] Galaxy Angel

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#3982]
**Describe the bug**
graphics are shifted in game

**To Reproduce**
play game. 

**Expected behavior**

**GS Settings**
does it on both hardware and software renderer

**GS Window Screenshots**
![gsdx_20201207005807](https://user-images.githubusercontent.com/8851653/101320007-91268480-3828-11eb-813f-667f275d3b98.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-670
 - OS: Windows 10
 - CPU: i5-4430
 - GPU: GTX 960

**Logs and Dumps**
[gsdx_20201207005807.gs.zip](https://github.com/PCSX2/pcsx2/files/5650968/gsdx_20201207005807.gs.zip)

**Comment by seta-san** [comment]
BLOCK DUMP
https://ufile.io/o01esnf6

**Comment by refractionpcsx2** [comment]
![galaxy](https://user-images.githubusercontent.com/6278726/101332783-ae317680-386d-11eb-8a20-614af485cb98.png)

**Comment by refractionpcsx2** [comment]
Okay so I've looked in to this, it looks like the game tries to access a texture format PSMT8 with a buffer width of 448, however the storage format specifies the width has to be multiples of 128.

GSDX has a hack/fix for this when reading a texture to force it to read with a with restricted to multiples of 128 (Geomon fix) but this game screws up if you don't allow the misaligned width.  I'm not sure if this is correct, it's possible the game can read in multiples of 64 but the entire texture has to be stored in multiples of 128, that I don't know.  This is going to need some investigation.
