### ISSUE TITLE
[BUG] The Getaway - shadows broken due to InvalidateVideoMemType

### ISSUE THREAD

**Issue by CookiePLMonster** [PCSX2/pcsx2#3986]
**Describe the bug**
In **The Getaway** when using a OGL HW mode, dynamic shadows either don't display or render as corrupted/black squares.
Currently, the issue can be worked around by using a **Disable Depth Emulation** hack, but I looked around the code a bit more and figured out that it's not needed to disable the entire depth emulation - it is enough to disable the `InvalidateVideoMemType` function only. The remaining changes introduced by the depth emulation hack are irrelevant to the issue and can introduce additional artifacts.

**To Reproduce**
Boot the game in OGL HW mode and observe the player's dynamic shadow (or rather, lack thereof). For comparison, switch to the Software mode and observe.

**GS Window Screenshots**

One of the possible ways the shadow can look in OGL HW mode with no hacks:
![image](https://user-images.githubusercontent.com/7947461/101538345-411cfe80-399d-11eb-9e1f-cff1c6796dad.png)

The way it looks with `InvalidateVideoMemType` function removed:
![image](https://user-images.githubusercontent.com/7947461/101538384-509c4780-399d-11eb-9355-44004b88c44f.png)

**Logs and Dumps**
GSdump: [gsdx_20201208213747.zip](https://github.com/PCSX2/pcsx2/files/5661798/gsdx_20201208213747.zip)

**Comment by coornio** [comment]
This bug appears to be fixed if one enables **CPU Sprite Render Size** to **2 (128 Max Width)** while also setting the mode to **Blended Sprites/Triangles**.

![image](https://github.com/PCSX2/pcsx2/assets/11655762/95b8a1fc-917f-46d6-9b9f-15553b87f3ba)

**Comment by refractionpcsx2** [comment]
Cool, make sure crc hacks are disabled while you check it as I believe it automatically disables depth support in order to fix that problem

**Comment by coornio** [comment]
> Cool, make sure crc hacks are disabled while you check it as I believe it automatically disables depth support in order to fix that problem

Please excuse my potential blindness but where even is that option regarding CRC hacks? I thought those got purged, or at the very least moved to some different part of the settings but I can't seem to find them anywhere.

**Comment by refractionpcsx2** [comment]
It's on the per game manual hw fixes now :)

**Comment by coornio** [comment]
Oh is it the "Disable Render Fixes" checkbox in the "Hardware Fixes" tab? I tried things out with it both on and off, no behaviors changed in vulkan or DX, and the shadow fix through CPU sprite render continued to work. Fog layer still glitchy in DX as before.

**Comment by refractionpcsx2** [comment]
Sorry I'm am idiot, yes that's it. 

The fog is probably too complex blending for direct x, it might be fine with ROV, though
