### ISSUE TITLE
[BUG] Sun flares shine through walls in hardware renderer.

### ISSUE THREAD

**Issue by y0nd0** [PCSX2/pcsx2#3993]
**Bug Description**
In hardware renderer the sun flares shine through walls. Tested in Need for Speed Most Wanted.

**To Reproduce**
Play the game and make sure the sun is in front of you. Then you drive under a bridge.
You'll see that the sun is hidden in sofware renderer mode, but still visible in hardware mode. 

**Expected behavior**
The sun should be behind the objects. As in the software renderer.

**Settings**
I tried all possible settings in the GS plugin. Including hacks. It occurs in the default settings. It only disappears when switching to software mode. This means, it does not matter if using OpenGL or Direct3D. 
I just enabled the Half-pixel Offset to Normal (Vertex) to remove lines around the textures. But this has no effect to this issue.
Let me know if you would like any specific settings. However, I'm sure there is only software / hardware settings to work around this issue. No special settings here.

Maybe you can explain the reason for this issue. That would be interesting. Hopefully we can find a solution.
Using the Skipdraw Range hack should not be a solution. At that moment I found no value for it. 
Maybe we can reorder the layers. But maybe it's another issue. Not about the layers. Because when the sun is at the edge of the bridge, it is not only covered by the wall. It's a transition. Maybe a missing feature. Like raycast. See:
![pcsx2-nfsmw-issue-sun-sw-edge](https://user-images.githubusercontent.com/68586847/101856595-e682ce80-3b65-11eb-8479-4dfecdc0852c.gif)
<sub>(Software Renderer. This is what is expected in hardware mode. But in HW mode, the sun is not covered.)</sub>

**GS Window Screenshots**

| Actual (HW) | Expected for HW (SW) |
| --- | --- |
| ![pcsx2-nfsmw-issue-sun-hw](https://user-images.githubusercontent.com/68586847/101856857-758fe680-3b66-11eb-8aee-e864e2fb9204.gif) | ![pcsx2-nfsmw-issue-sun-sw](https://user-images.githubusercontent.com/68586847/101856863-7759aa00-3b66-11eb-95fd-091a32f28678.gif) |

[videos-webm](https://github.com/PCSX2/pcsx2/files/5676866/videos-webm.zip) (Videos with more frames. GitHub does not yet support videos (no audio) ... Use e.g. VLC to view it. Or just the browser by drag'n'drop.)

**System Info**
 - PCSX2 Revision: v1.7.0-dev-675-g85c3ee823
 - OS: Windows 10 Pro 64-bit (v2004)
 - CPU: AMD Ryzen 5 3600 (6/12 Cores)
 - GPU: Nvidia GeForce RTX 2070 Super
 - RAM: 32GB
 - SSD: Yes

**Comment by lightningterror** [comment]
Can you provide a gs dump?

**Comment by y0nd0** [comment]
Here is the GS dump: [gsdump-frame-nfsmw-bug-sun-flare.zip](https://github.com/PCSX2/pcsx2/files/5679712/gsdump-frame-nfsmw-bug-sun-flare.zip)
Let me know if you need more stuff.

**Comment by tadanokojin** [comment]
This game renders into the clut to update the alpha channel of the sun texture to decide if it's visible or not.

**Comment by iMineLink** [comment]
Could the SwSpriteRenderer be of any help here?

**Comment by tadanokojin** [comment]
It's complicated.
Clut is drawn sampling and rendering into a previous RT then copied.

So you need data from GPU.

**Comment by iMineLink** [comment]
Nice. Btw the function already reads back from gpu memory by default. Obv, the data should be there and not cluttered in TC garbage.

**Comment by twoco** [comment]
Tested in latest (nightly) version `1.7.3137`. This bug still exists.

**Comment by refractionpcsx2** [comment]
Yup, not quite sure at the moment what this game does to occlude light. This bug appears in many games, but they all do it differently.
