### ISSUE TITLE
[BUG] SLUS-21273 - Matrix - The Path of Neo (USA): Graphical issues in textures in HW mode

### ISSUE THREAD

**Issue by Shideravan** [PCSX2/pcsx2#4002]
**Describe the bug**
Graphical errors in hardware mode. The issue happens even with internal resolution in "native", the screenshot was taken using upscaled graphics just to help see the graphical errors.
Blooming graphics in surfaces even with _"Merge Sprite" and set Half-pixel Offset to "Special Texture"_ being used as recommended in wiki.
I can provide the memory card file or savestate if is needed (just not posted because i'm not sure regarding copyright issues)

**To Reproduce**
Most of levels has the wrong light effect in textures. This screenshot was taken in "The Security Guard" and "The Librarian" levels. Just enter in the stage with any of the hardware renderer on and will see the errors.

**Expected behavior**
The textures with a normal bright. Take a look in a full game capture using the real hardware: https://www.youtube.com/watch?v=A2IlvwncaK4&ab_channel=Longplay

**GS Settings**
In the following screenshot, all the settings are in the default on, except for using "Enable HW Hacks->Merge Sprite and the Half-pixel aspect to Special Texture" as recommended in Wiki (https://wiki.pcsx2.net/The_Matrix:_Path_of_Neo). Anyway, the graphical issue happens even with the option deselected.

**Emulation Settings**
Default for "3- Balanced" predefinition.

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/12163923/102017684-23f28200-3d47-11eb-9d61-b67161b31612.png)
![image](https://user-images.githubusercontent.com/12163923/102018316-5605e300-3d4b-11eb-9248-0d63a51357b0.png)
![image](https://user-images.githubusercontent.com/12163923/102018351-83eb2780-3d4b-11eb-9467-cb5367b61aea.png)

Using softwaremode (very slow, unplayable)
![image](https://user-images.githubusercontent.com/12163923/102018371-a7ae6d80-3d4b-11eb-9f2f-b6b4458b89c6.png)

**System Info:**
 - PCSX2 Revision: 1.7.0-dev-680-g083380297
 - OS: Windows 10 x64
 - CPU: Intel i7-4790
 - GPU: GTX 1070

**Comment by tadanokojin** [comment]
Not a valid issue https://raw.githubusercontent.com/PCSX2/pcsx2/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Shideravan** [comment]
> Not a valid issue https://raw.githubusercontent.com/PCSX2/pcsx2/master/.github/ISSUE_TEMPLATE/bug_report.md

Sorry, edited the issue.

**Comment by tadanokojin** [comment]
Can you provide a GS dump where the issue is most present?
 https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by Shideravan** [comment]
[gsdx_20201213140755.zip](https://github.com/PCSX2/pcsx2/files/5685021/gsdx_20201213140755.zip)

**Comment by legend800** [comment]
Confirmed. No settings I've found address the glossy surfaces/white seams or the bloom issue on cutscenes. Not the best comparison but you can see the seems are white/flickering here (with/without all possible filtering):

HW:
![2020-12-13 14_42_46-Slot_ 0 _ Speed_ 100% (59 94) _ Limiter_ Normal _ OGL _ 2560x2240 _ None _ ${omo](https://user-images.githubusercontent.com/20983844/102026306-fbbc5080-3d51-11eb-8ffb-62a0b741b36c.png)

Software:
![2020-12-13 14_34_08-Slot_ 0 _ Speed_ 100% (59 94) _ Limiter_ Normal _ SW _ 512x448 _ None _ ${omodec](https://user-images.githubusercontent.com/20983844/102026309-ff4fd780-3d51-11eb-8ef7-5a9d93f7f0e0.png)

**Comment by Shideravan** [comment]
Issue no longer reproducible in https://github.com/PCSX2/pcsx2/commit/631ed8c0fd4bf95dc1560f565360aaa6b203f476
Seems to be fixed at any point as any improvement side effect.
Good job, PCSX2 devs!

**Comment by legend800** [comment]
Yes this original issue is resolved. Not the game still needs:

- Merge sprite(fixes ghosting but removes some lighting) - NOT IN GAMEDB
- Half Pixel Offset=Special texture aggressive (fixes glossy textures & reduces white lines from upresing). - IN GAMEDB

**Comment by RedDevilus** [comment]
Likely to be from:
https://github.com/PCSX2/pcsx2/pull/5678

**Comment by RedDevilus** [comment]
> Yes this original issue is resolved. Note the game still needs:
> 
>     * Merge sprite(fixes ghosting but may remove some lighting?) - NOT IN GAMEDB
> 
>     * Half Pixel Offset=Special texture aggressive (fixes glossy textures & reduces white lines from upresing). - IN GAMEDB

![pcsx2treasuregob2](https://user-images.githubusercontent.com/24227051/167273272-6e491b27-f6e3-40fb-b325-0b1e39b328cc.gif)

**Comment by legend800** [comment]
Correct, so only thing left to add is Merge Sprite if it does more good than harm (I'm confident it does)
