### ISSUE TITLE
Tekken 1 Arcade History via Tekken 5: Character Select animation is missing.

### ISSUE THREAD

**Issue by Jitterdoomer** [PCSX2/pcsx2#4004]
**Describe the bug**
While MAME has proper select screen animation for Tekken 1's character select screen. On PCSX2, the emulated version via Tekken 5 lacks a select screen animation m after you pick a character and the question mark box itself.

**To Reproduce**
Select Tekken 1 from Arcade History menu and then hit start after you boot the game.

**Expected behavior**
It happens always no matter what.

**System Info**:
 - PCSX2 Revision: PCSX2 1.7.0-20201216140454
 - OS: Windows 10 Home
 - CPU: i7-8700k
 - GPU: GTX 1080

**Comment by lightningterror** [comment]
Please fill in the entire issue properly following the template.

**Comment by Jitterdoomer** [comment]
I edited it but I'm very new to this type of bug reporting.

**Comment by JordanTheToaster** [comment]
Works correctly on latest master.

![image](https://user-images.githubusercontent.com/80843560/214326595-cbaa2bcd-1160-469d-b71f-e27a81303971.png)
