### ISSUE TITLE
[BUG - CDVD]  "pause" command non-supported by PCSX2

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4015]
**Describe the bug**

In PCSX2, when a game send the "pause" command to the cdvd, PCSX2 just ignore said command instead of properly set the "pause" status.

- This causes the game "Yoake no Mariko 2nd Act" to not boot without a patch.
- This causes ICO china version not to boot without a patch.

**To Reproduce**

Load the game "Yoake no Mariko 2nd Act" and with a debug build, you will see the game endlessly waiting the cdvd to pause.

**Expected behavior**

The game should continue after a sound emmited by a character before the intro.

**Emulation Settings**

All default.

**System Info (please complete the following information):**
- PCSX2 revision: pcsx2-v1.7.0-dev-487-g6ad8563c1-windows-x86
- OS: Windows 10
- CPU: I9 9900K
- GPU: GTX 1080

**Comment by refractionpcsx2** [comment]
I will need blockdumps of these games in order to test this.

**Comment by atomic83GitHub** [comment]
Here is the Yoake one https://drive.google.com/file/d/1DII9Xw9LAhZ_1LOuU54548KW2IM9Oe08/view?usp=sharing
I don't have ICO china but it should be the exact same issue anyway.

**Comment by refractionpcsx2** [comment]
Yoake was due to pause not being implemented. ICO was due to the handling of the status register incorrectly removing the pause state from the cdvd.
