### ISSUE TITLE
[BUG] Difficulties assigning multiple controllers

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#4017]
In pcsx2's "Gamepad Configuration", assigning multiple controllers doesn't work properly.  First, since both controllers are listed as "Wireless Controller" it is difficult to know which one is actually being configured.  You can sort-of tell by turning "Rumble" on, which is supposed to rumble a given controller, but then only the second controller actually rumbles.  

~~Update: Tried many ways to get the second controller to register but it won't, and ingame (tested with Contra: Shattered Soldier), directional inputs on the second controller cause both players to move.  So for now, pcsx2 seems to be broken with more than one controller.  Realizing there are efforts underway to get manual button assignments back via onepad-legacy (thanks again @GovanifY), perhaps this issue can be worked around?~~

By blindly selecting controllers in "Gamepad Configuration" I finally stumbled on the right combination, so it does work with user persistence.  However, this would be much easier if pcsx2 could report connected controllers more specifically than both as "Wireless Controller".  :)

Tested with two DS4 pads via bluetooth.

System Info

-    PCSX2 Revision: 10afd0b
-    OS: Linux Mint 20, kernel 5.8
-    CPU: Core i7-7820HK
-    GPU:Nvidia GTX 1070
-    Compiler: gcc-10.2.0

**Comment by Mrlinkwii** [comment]
can this be checked again on latest master :slightly_smiling_face: ?

**Comment by Shoegzer** [comment]
It sure can. :) Just checked and this issue seems to be resolved so I'll close it.

While I'm thinking of it, two related features that would be nice to have at some future point:
1. Simple visual feedback of buttons pressed and sticks pushed in the controller settings window 
2. Controller settings window appearing in the "Settings" applet as it currently does in the drop-down menu (guessing this is only due to Qt interface being so new).
