### ISSUE TITLE
King Kong vertwx explosion?

### ISSUE THREAD

**Issue by AireagoirSteam** [PCSX2/pcsx2#4020]
**Describe the bug**

After the fmv's in Peter Jacksons king Kong the main characters hands have stretching explosions. So does another character and background characters

**To Reproduce**

Wait for fmv's to finish or skip them
**Expected behavior**

Characters to look normal
**GS Settings**

![gs settings](https://user-images.githubusercontent.com/22620774/102663731-518d6000-4179-11eb-899d-b0e1a8fcae70.PNG)

**Emulation Settings**

![pcsx2_CoreSettings_Speedhacks](https://user-images.githubusercontent.com/22620774/102663757-610ca900-4179-11eb-9046-267146b8ccf9.png)

**GS Window Screenshots**

![pcsx2_CoreSettings_GS Window](https://user-images.githubusercontent.com/22620774/102663793-71bd1f00-4179-11eb-9e16-a18f2ac4e6e5.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 
 - OS: windows 10 pro
 - CPU: I7-8750H
 - GPU: GTX 1060

**Logs and Dumps**

**Comment by MrCK1** [comment]
@AireagoirSteam Can you provide a blockdump for us by enabling System>Create Blockdump? Just make sure you reboot the game after enabling that and run a few seconds when the bad graphics appear. Thanks

**Comment by refractionpcsx2** [comment]
Please also let the movie run for a couple of seconds, to give us time to skip it, otherwise it will just hang if it runs out of data.

**Comment by refractionpcsx2** [comment]
This now fixed in master
