### ISSUE TITLE
Warriors of Might and Magic - gamepad not functioning properly

### ISSUE THREAD

**Issue by ZandigSlaytanic** [PCSX2/pcsx2#4026]
This has been an issue for quite some time using the LilyPad plugin. The game's controls do not function as expected.
The only remedy for controlling the game properly was to use the Pokopom gamepad plugin.

I was using build: pcsx2-v1.7.0-dev-685-g678829a5b-windows-x86 where the gamepad was set to use the Pokopom plugin for Warriors of Might and Magic and everything was fine. Today, after updating to: pcsx2-v1.7.0-dev-765-g3143a46e4-windows-x86 I noticed the option to set the gamepad plugin was removed and naturally the controls for this game no longer work as expected.

**Comment by bositman** [comment]
A description of the actual problem would be helpful, 'not working as expected' is very vague. Do none of the controls work? Do buttons work but not directionals? Does it happen with keyboard and a pad too? Please be more specific.

**Comment by ZandigSlaytanic** [comment]
I use an Xbox wired game controller for the PC. Not sure about the keyboard as I don't use it for a controller.

The controls do work in the menu/options screen before loading a game. However once in game and controlling the character the Left Analog stick and Right Analog stick function as the D-Pad. Using Pokopom the game controls properly.

**Comment by ZandigSlaytanic** [comment]
I tested using the keyboard with the latest dev release: v1.7.0-dev-873-gade09b063 (2021-01-14 16:30:43)
and the same thing happens using the keyboard as I noted above using the gamepad.

**Comment by ZandigSlaytanic** [comment]
Tested it with the new commit - still not working properly.
There is progress however...if you continue to move the Left and Right sticks it will alternate between incorrectly functioning as the D-Pad, and then functioning as intended. The cycle repeats.

A bit hard to explain unless you see it in action.

**Comment by KrossX** [comment]
Could you test #4331 please? If the automatic builds are ready, please do try those.

**Comment by ZandigSlaytanic** [comment]
Thanks for looking into this KrossX,

Finally some good news.
YES ! **pcsx2.exe build: pcsx2_1164_pad4F.zip** fixes the issue !
