### ISSUE TITLE
[Feature Request] Organize the .ini files (settings) with some kind of "set in stone" layout/order?

### ISSUE THREAD

**Issue by ImSpecial** [PCSX2/pcsx2#4029]
[Feature Request] Organize the .ini files (settings) with some kind of "set in stone" layout/order?

So this is a feature request sorta (ha! get it?), a little hard to explain so bear with me. Anyways, I like to backup my .ini files ie. GSdx.ini, and when I do updates for PCSX2 every once in a while by grabbing the latest dev build, I like to check the differences between the new and old to make sure I got my settings correct, but this is harder then it should be because the new .ini files are created in what seems to be the order you configured things in PCSX2, so [MemoryCards] might be near the top one time if it was the first thing you configured, while it might be at the bottom before previously if it was one of the last things you did.

Could these be generated with some kind of "set in stone" order? Alphabetically maybe, or groupings that just make sense, so that everyone's .ini file layouts are the same but with just different values.

That's basically it, hopefully one of the hundred people here will know what I mean by this. Thanks for reading/wasting you time. :P

---

Oh, and also a bonus, maybe "bug" report but I don't feel like it requires its own post for such a minor thing.

I noticed that there are spaces between the names and values in only the GSdx.ini file and not the others, this doesn't hurt anything but I find it kinda strange and maybe is just an oversight.

https://i.imgur.com/fMusZ4f.png
https://i.imgur.com/i6la5ve.png
https://i.imgur.com/RoHcQgl.png

**Comment by xTVaser** [comment]
Hey there.  There is some work being done around the config file generation so we can definitely keep this in mind.  I can't say for certain off hand but the order _may_ be out of our control.  The majority of these settings are handled by the GUI framework's tools (wxWidgets in this case) so it will largely be up to them if we can fulfill this.  I suspect atleast consistently ordered groups should be achievable, and alphabetical makes sense to me as you suggested.  fyi @kenshen112 

As for the spaces issue in GS's config, it's likely just an outlier due to the inconsistency config-wise across the code-base.  As the plugins are merged and things are cleaned up I suspect that issue will be resolved one-way-or-another.

**Comment by kenshen112** [comment]
Yeah order should be pretty achievable. It just depends on when you call the save functions

**Comment by ImSpecial** [comment]
I'm glad I had good timing with this request, and glad someone here understood what I meant by it as well : ), and a big thanks for "keeping these in mind" for when you pull up those sleeves to get your hands dirty. Good luck.

**Comment by RedDevilus** [comment]
They aren't consistent that's true, i haven't really looked at them much but now i can't stop thinking about it.
Some more categories would really help that reflect how it is laid out in the GUI.
[Settings] for the GSdx is a bit barebones.

[Shader]
ShadeBoost = 0
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
TVShader = 0
[HW Hacks and Advanced Settings]
UserHacks = 0

+ more like [Hardware Renderer Settings] [Software Renderer Settings] 

The more i think about it, i've become quite used for the GUI itself. Feels like the inis have many different styles to them just like the code itself is. Maybe also an option to force re-order the lines in the ini or an easy way to do it manually, just some ideas but we will see how that be achieved.

**Comment by stenzek** [comment]
Semi irrelevant since everything is merged into one ini in Qt, and the order that variables are written should be consistent with when they're initialized on first startup.
