### ISSUE TITLE
[Feature Request] Copy Depth Buffer 

### ISSUE THREAD

**Issue by FuxorLuck** [PCSX2/pcsx2#4030]
**Description**
An on/off option for pcsx2 to copy the depth buffer of games so other programs can use the copied frame buffer. 

**Reason**
Many ps2 treats 3d area in a bizzare way that make it impossible for other programs to read. 
The best example is that you cant use reshade ambient occlusion shader on games like digital devil saga, Metal Gear Solid 2, Eternal Poison ect.. 
Another benefit is that will Allow us to learn more about the games, we can see all the polygons and the vetrex in the scene. 

**Examples**
Project 64 has this feature and it helps to reshade to with games that reshade is having a trouble to detect their depth buffer

Thanks for reading and have a nice day

**Comment by tadanokojin** [comment]
It should be possible to add a button which enables/disables moving depth into the window buffer.

However, it may not work as well as you want it to. Many games will abuse the depth buffer and draw junk into it making it not so great for reshade. There's not really much I can do about it either. Burnout revenge is an example of this where the game will draw the ui in depth.

Greg already addressed this partially in https://github.com/PCSX2/pcsx2/issues/2311#issuecomment-506953924 as well.

Personally, I advise against reshade if you are trying to learn about the PS2 . If you already know about how GSdx works and can account for that while using it I guess it's not so bad. But if you can't it will probably mislead you.

**Comment by FuxorLuck** [comment]
Thank you

sorry for the late respond
since this was already being discussed, I close this issue
