### ISSUE TITLE
[BUG] Taxi 3 (SLES-51377) fails to load on current build (767) and has been broken since build 683 - loads on build 680

### ISSUE THREAD

**Issue by Rallymen007** [PCSX2/pcsx2#4034]
Hello!

**Describe the bug**
Since build 683, Taxi 3 fails to load into the game. It hangs at the end of the loading screen. Went back and tested various versions and it loads fine up to and including build 680.

**To Reproduce**
Try to load Taxi 3 (SLES-51377) in PCSX2, and start the first race of the first menu item.

**Expected behavior**
Game loads and works.

**GS Settings**
3x Native but I think the rest is untouched.

**Emulation Settings**
Everything to default, turned off speedhacks. 
I tried to fiddle with VU settings and game hacks as it looks like the incriminated build changed something with VU behaviour and the log stops showing the VU trace but no dice.

**System Info (please complete the following information):**
PCSX2 1.7.0-20201219235753 - compiled on Dec 20 2020
Microsoft Windows 10 Pro (build 19042), 64-bit
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Nvidia GTX 1070 Notebook

**Logs and Dumps**
Log from build 680 (loads) [log-taxi-loading-680.txt](https://github.com/PCSX2/pcsx2/files/5727067/log-taxi-loading-680.txt)
Log from build 767 (doesn't load) [log-taxi-notloading-767.txt](https://github.com/PCSX2/pcsx2/files/5727069/log-taxi-notloading-767.txt)

If you need any more info or to run various tests please let me know!
Thanks a lot!
Rally

**Comment by MrCK1** [comment]
Unfortunately we don't provide support for piracy.
`isoFile open ok: C:\Users\Franck\Downloads\games\SLES_513.77.Taxi 3.iso`

**Comment by Rallymen007** [comment]
Hello @MrCK1 

There seems to have been a misunderstanding I am using a legitimate backup copy of a game I own because this laptop has no disc drive.
Here's a picture of me holding up the copy in front of the github issue and showing I am logged in.
![IMG_20201222_121222](https://user-images.githubusercontent.com/6065450/102883368-34de7a00-4450-11eb-847e-cc622579be2b.jpg)

No piracy was involved. This is legal.

**Comment by refractionpcsx2** [comment]
It matters not, I've fixed it on Master anyway, enjoy your strange game :P

**Comment by Rallymen007** [comment]
Okay thanks!

**Comment by tadanokojin** [comment]
I suggest moving it out of your downloads folder for future issues/support requests.
