### ISSUE TITLE
[Feature Request] Texture Dump

### ISSUE THREAD

**Issue by fuhuan416** [PCSX2/pcsx2#4038]
**Description**

The original map of the game is replaced by the one with HD or mod map

You can refer to this RR: https://github.com/hrydgard/ppsspp/pull/8715

**Reason**

Of course, when the user makes his HD texture or mod texture, it can be shared with other users, which is very interesting!

To achieve the above two functions, whether it is the production process or sharing results, it is full of fun!

Of course, the difference from the existing function is that it is a fundamental solution to the problem of map blur

Users do not need to unpack game resource files to replace textures

**Examples**

![01](https://user-images.githubusercontent.com/6281757/102965703-58c1be80-4529-11eb-95a5-031c981b730e.png)
![02](https://user-images.githubusercontent.com/6281757/102965707-5a8b8200-4529-11eb-8c14-6fb4c60eff06.png)
This is the texture dump function of the 3DS emulator. I think i don't need to explain which picture is replaced : )

![QQ图片20201223140653](https://user-images.githubusercontent.com/6281757/102965821-97f00f80-4529-11eb-83b2-b76958c3d866.png)
It's easy to ues.

**Comment by Calinou** [comment]
This should be implemented by https://github.com/PCSX2/pcsx2/pull/5547 now, so this issue can be closed.
