### ISSUE TITLE
[BUG] Super Robot Wars MX [SLPS-25345] Character voices do not play correctly

### ISSUE THREAD

**Issue by User9013** [PCSX2/pcsx2#4040]
**Describe the bug**
Character voices do not play properly in "Super Robot Wars MX".
This will occur whenever a character's voice is played.
This bug was not remedied by changing the audio plug-in to a different kind.

**To Reproduce**
Turn on the battle animation(戦闘デモ) and play the battle animation.

**GS Settings**
N/A

**Emulation Settings**
N/A

**GS Window Screenshots**
N/A

**System Info:**
 - PCSX2 Revision: v1.7.0-20201223010426, As far as I know, it happens in all versions.
 - OS: Windows10
 - CPU: Core i5 10400F
 - GPU: Radeon RX580

**Logs and Dumps**

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/5735011/emuLog.txt)

The following video is different from the one in the log.
I added it so that the symptoms can be easily understood.
https://user-images.githubusercontent.com/65251154/102994981-790e6f00-4563-11eb-99f7-b8df6dc83b00.mp4

**Comment by prafullpcsx2** [comment]
Can you retest latest dev build with this? There have been some spu2 fixes which may fix the problem. Also if possible post a savestate right before the problem using latest dev build.

**Comment by refractionpcsx2** [comment]
Sounds very much the same issue I fixed with Gregory Horrow Show, the latest dev build should fix that, hopefully

**Comment by seta-san** [comment]
@User9013 can you confirm if it's been fixed in version 1.7.0-dev-817 ?
https://buildbot.orphis.net/pcsx2/index.php

**Comment by GuestMK3** [comment]
@seta-san is working good now, I´m using the latest build of PCSX2 and the audio problem is gone.

**Comment by MrCK1** [comment]
Thanks for testing

**Comment by User9013** [comment]
> @User9013 can you confirm if it's been fixed in version 1.7.0-dev-817 ?
> https://buildbot.orphis.net/pcsx2/index.php

It is working good now.
Thank you very much for fixing the bug.
