### ISSUE TITLE
[Feature Request] USB - Sega Seamic Custom Controller Setup Screen

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4041]
**Description**
The sega seamic is a unique controller that doesn't exactly follow a standard ps2 controller and it has a built in microphone. The current setup screen was designed for steering wheels

Controller images and explainations are here
https://github.com/jackun/USBqemu-wheel/issues/44

**Comment by RedDevilus** [comment]
https://github.com/PCSX2/pcsx2/pull/3889
Has been added on this pull request, is it still missing something?

**Comment by jackun** [comment]
Proper configuration and other weirdness of Seamic controller.
