### ISSUE TITLE
[BUG] Neo contra: Hang before start of Mission 2

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#4065]
**Describe the bug**

Neo Contra hangs right before the start of Mission 2 with debugger showing this:-

![image](https://user-images.githubusercontent.com/12788199/103405578-9d7ad480-4b7d-11eb-852a-d7200349fd99.png)

**To Reproduce**
Run Neo Contra and try to start mission 2. The game will hang. There is a patch in the gamedb which nops the IPU command and fixes the hang but also corrupts the graphics. Skipmpeg hack doesn't fix the hang.

**Expected behavior**
Mission 2 should start with correct IPU being played without glitches.

**GS Settings**
Any (Don't matter)

**Emulation Settings**
Any (Don't matter)

**Logs and Dumps**
Block dump from NTSC version of the game can be downloaded here:-
http://www.filedropper.com/neocontrausa2020-11-3115-41-39

**Additional info**
Dobiestation also used to hang at exact same spot until PSI commited this fix:-

https://github.com/PSI-Rockin/DobieStation/commit/348ef93c3f48a45223ea3b95f11829eb77b26da9#diff-ecf6b6e779536fd565cd6dfe5b5ad842

**Comment by atomic83GitHub** [comment]
The mission 2 hanging issue have been fixed but a nother issue related to the FPU is still remaining.

**Comment by refractionpcsx2** [comment]
Can you detail the floating point bug please? You have no information at all on it in your OP

**Comment by refractionpcsx2** [comment]
This IPU problem was fixed in #4066

The Float issues mentioned seem to (at least in the Mission 4 instance) be fixed by using Nearest rounding on the EE, maybe in combination with Extra+Sign EE clamping, but another Issue can be opened for that if need be.
