### ISSUE TITLE
[BUG] Need For Speed - Underground Misaligned Lights

### ISSUE THREAD

**Issue by PawTM** [PCSX2/pcsx2#4068]
**Describe the bug**
Lights get misaligned from their light sources when the camera moves and stay that way after the camera stops turning.
![grafik](https://user-images.githubusercontent.com/62476228/103412633-710f8a00-4b76-11eb-9ea4-ba30deb73699.png)
This happens both in SW and HW Modes, but not on RealHW.

**To Reproduce**
This issue is easiest to find in the Terminal Circuit Race, where there are lights at the starting line, but is reproducable with every street lantern looking like in the picture above.

**Expected behavior**
In my Testing on a real PS2, the light gets blurred to the side when turning the camera, however never actually moves away from it's source as it does on PCSX2, and returns to it's origin position afterwards. This can be found in quite a few Youtube videos.

**GS/Emulation Settings**
This appears on Default Settings/Preset 2, but almost nothing seems to affect it. EE Interpreter makes the light disappear completely, not sure if this is any relevant.

**GS Window Screenshots**
[Street Lantern on the right]
![grafik](https://user-images.githubusercontent.com/62476228/103413098-6b1aa880-4b78-11eb-84af-65e7c677c6e3.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7 dev-817
 - OS: Windows 10
 - CPU: i5-8400
 - GPU: GTX 1060

**Logs and Dumps**
[GS-Dump.zip](https://github.com/PCSX2/pcsx2/files/5757425/gsdx_20201231145846.gs.zip)

**Comment by tadanokojin** [comment]
Any change with rounding/clamping on EE/VU?

**Comment by PawTM** [comment]
No, neither seems to affect it.

**Comment by kozarovv** [comment]
It's broken widescreen patch.

**Comment by refractionpcsx2** [comment]
Please report it to the community thread for widescreen patches: https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches
