### ISSUE TITLE
[BUG] True Crime: Streets of LA - NTSC AND PAL - Assert Errors

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4070]
no known steps to reproduce. happens while in-game randomly.  

"C:\BuildAgent\work\76cd4fe97f2b8d5a\pcsx2\x86\newVif_Dynarec.cpp(197) : assertion failed:
    Function:  VifUnpackSSE_Dynarec::ModUnpack
    Thread:    EE Core
    Condition: false
    Message:   Vpu/Vif - Invalid Unpack! [3]
"

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-817
 - OS: Windows 10
 - CPU: i5-9600
 - GPU: GTX 960

**Comment by atomic83GitHub** [comment]
I would sugest testing the DMAC busy hack.

**Comment by atomic83GitHub** [comment]
Also, I would like to have a blockdump of the issue. I know it's tricky but what you can do is playing normaly, doing savestates on a regular basis until you enconter the bug.

**Comment by seta-san** [comment]
https://easyupload.io/80upf2

**Comment by atomic83GitHub** [comment]
Thanks, but what should I do to trigger the bug?

**Comment by seta-san** [comment]
who knows? it just happens.

**Comment by atomic83GitHub** [comment]
Thing is, for the dump to work i need at leist one savestate in the area that happen

**Comment by seta-san** [comment]
i don't know what to tell you. it happens completely random. it happens no particular place while doing no particular thing. it might only happen when in a car. i've never had it happen when i was walking around.

**Comment by atomic83GitHub** [comment]
Excuse me, what I mean is just take a savestate in the game so I can load it

**Comment by seta-san** [comment]
[SLES-51754 (6B9AEA0D).00.zip](https://github.com/PCSX2/pcsx2/files/5760754/SLES-51754.6B9AEA0D.00.zip)

**Comment by atomic83GitHub** [comment]
Thanks for the save-state, anyway I think I will buy the game regardless.

**Comment by ca5dx** [comment]
Yet another log with 2 crashes
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6829480/emuLog.txt)
Interesting to note after reloading a savestate after it hangs there's an odd chance the audio will be pitched down a few octaves or the graphics will be completely broken.

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by seta-san** [comment]
i'll test it when i get time. i'm afraid though any testing might be pointless until all of stenzek's memory reworking and fastmem stuff is in place.

**Comment by seta-san** [comment]
![crash](https://user-images.githubusercontent.com/8851653/196525872-6a6f3206-d1cd-4db5-8998-776cc02fd8e1.jpg)
yup. it's still an issue. tested on 1.7.3454

**Comment by refractionpcsx2** [comment]
I'm hoping it's improved now the SIF changes are done avoiding TLB misses and such.

**Comment by seta-san** [comment]
I’ll test when I get back in town. This is a notoriously difficult one to trigger

**Comment by Mrlinkwii** [comment]
nearly finished the  pal version with no crashes so i assume this is fixed
