### ISSUE TITLE
[BUG] True Crime - Streets of LA - NTSC and PAL - Graphics issue

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4071]
**Describe the bug**
persistent double image and wrong textures on street signs and license plates

**To Reproduce**
play the game

**Expected behavior**
no double image or double textures on signs and license plates

**GS Settings**
OpenGL hardware mode. All other standard settings

**Emulation Settings**
standard settings

**GS Window Screenshots**
![gsdx_20201231090332](https://user-images.githubusercontent.com/8851653/103415445-be283780-4b47-11eb-8832-f090ce03287e.png)
![gsdx_20201231090402](https://user-images.githubusercontent.com/8851653/103415467-cf714400-4b47-11eb-8c03-81f43b1fc771.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-817
 - OS:  Windows 10 
 - CPU:  i5-9600 
 - GPU: GTX 960

**Logs and Dumps**
[gsdx_20201231090411.zip](https://github.com/PCSX2/pcsx2/files/5757564/gsdx_20201231090411.zip)

**Comment by tadanokojin** [comment]
Please fill the issue out proper.

**Comment by refractionpcsx2** [comment]
This needs preload frame enabled. But the game doesn't work at the moment for slightly unknown reasons (apparently PAD 2 showing as disconnected causes it to not work)
