### ISSUE TITLE
[BUG] Final Fantasy X - Tidus clipping through 2D textures

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#4072]
**Describe the bug**
In Final Fantasy the main playable character Tidus appears to be clipping through the textures in scenes where the background is 2D. This happens in either HW or SW so upscaling isn't the cause.

**To Reproduce**
Enter a scene where the background is 2D. You'll see Tidus's hair start to clip to black

**Expected behavior**
His blond should stay blond

**GS Settings**
All settings default.

**Emulation Settings**
All Settings default. Instant VU1 enabled no MTVU 

**GS Window Screenshots**
[In Wakka's house you can see the clip](https://imgur.com/a/OYeU6KO)
[Outside you don't](https://imgur.com/a/n9nPIg4)

**System Info:**
- Latest Dev Build
 - OS: Windows 10 & Arch Linux
 - CPU: Ryzen 7 3700x
 - GPU: Nvidia 2070

**Logs and Dumps**
[gsdx_20201231090140.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/5757670/gsdx_20201231090140.gs.xz.zip)

**Comment by emjzero2** [comment]
This also happens on real hardware, but not on every pre-rendered background, wakka's house is one of them though

https://youtu.be/pTNfwUTOpmI?t=1436
https://youtu.be/3h_tiR5Ux9o?t=3452

**Comment by tadanokojin** [comment]
closing as issue is present on real hw
