### ISSUE TITLE
[BUG] From Software First Preview: Evergrace demo hard crash the emulator.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4077]
**Describe the bug**
When starting the evergrace demo, you can choose between 2 characters before starting the level, when loading the level, the emulator hard crash to the desktop.

**To Reproduce**
Just load and play the evergrace demo.

**Expected behavior**
The level should load properly.

- Note: The emulator play! doesn't have the issue.

**Emulation Settings**
Everything tried, no success.

**System Info**

PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**

[From software first preview, demo hard crash.zip](https://github.com/PCSX2/pcsx2/files/5758998/From.software.first.preview.demo.hard.crash.zip)

**Comment by kozarovv** [comment]
Game pass 0 as sectors to read in sceCdRead, which apparently underflow value later in function itself. 
Wrong data is from EE 0x23BB84 - lh $a3, 4($v0), but correct data seems to be 2 bytes later so replacing that to lh $a3, 6($v0) make game happy, and everything load as it should.

**Comment by refractionpcsx2** [comment]
Apparently fixed by https://github.com/PCSX2/pcsx2/commit/bb494af6b0bb5bfcaa26cbec6b0b9cf2a853e373
