### ISSUE TITLE
[BUG] Winning Eleven 8: crashes on a black screen at boot.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4079]
**Describe the bug**
The game crashes at boot, not a single screen can be seen.

In the console, there is a few time out logs on the cdvd side of things:
![image](https://user-images.githubusercontent.com/26351275/103442107-8b6b6580-4c53-11eb-959f-2405627238cb.png)

**To Reproduce**
Load the game.

**Expected behavior**
The game should boot.

**Emulation Settings**
Everything default.

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
[Wining elevel 8 black screen.zip](https://github.com/PCSX2/pcsx2/files/5759144/Wining.elevel.8.black.screen.zip)

**Comment by refractionpcsx2** [comment]
Okay I had a brief look in to this, and I can successfully hack it to work (or at least not time out) by setting the "Data ready" IRQ reason, although that doesn't make a lot of sense on the commands it's doing it on.

**Comment by refractionpcsx2** [comment]
it's not an interrupt flag, it's a status register of what the drive is doing.

And it's a combination of well known information and my own determination, since I presume each bit stands for something, but when you look up "Pause" and "Read" they are all combinations of other bits.
