### ISSUE TITLE
PCSX2 crashes when modifying GSDX settings, on first run wizard, on Windows

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#408]
Caused by #405.
It is irrelevant if the default settings are altered or not, just click OK and it crashes.
Workaround: 
-In first run wizard adjust all the other settings without touching GSDX;
-After first run wizard closes, it is possible to adjust the GSDX settings as well.

![crash](https://cloud.githubusercontent.com/assets/1138235/5548225/103de2b2-8b74-11e4-9e44-2a0984a1d9e4.png)

**Comment by uyjulian** [comment]
i can confirmed this happens on Linux too...

**Comment by gregory38** [comment]
Hum, I failed to reproduce it on my side...

Could you check this version is ok? (it is the first commit of #405)
```
https://github.com/PCSX2/pcsx2/commit/767b841fea2d19296e571730a40e3154395a39fa
```

**Comment by avih** [comment]
Guys, we find it hard to reproduce. Could you please describe the steps as follows:

1. delete the `inis' folder.
2. do stuff (describe in details).
3. crash.

**Comment by uyjulian** [comment]
https://gist.github.com/uyjulian/f63af1585e3773706145
I clock OK in the GSDX settings, the program just closes.

**Comment by pal1000** [comment]
Uploaded a video with this issue reproducing scenarios here:
http://pal1000.3x.ro/shared/bugreports/pcsx2/issue-408/pcsx2-GSDX-crash.mp4

**Comment by avih** [comment]
@pal1000, thanks, though I still can't reproduce this.

1. I see that you can compile PCSX2 yourself. At this case, would you be able to build in "DEVEL" mode, then run with F5 (not ctrl-F5), and once it crashes, click "Break" and post a screenshot of the Call Stack window (like you have in your first screenshot)?

2. Is this recent? the first comment mentions that it's due to the fix of issue #405, what's the last build which doesn't crash like this? you can get pre-compiled recent builds from http://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by pal1000** [comment]
@avih, I didn't not compile PCSX2 from source. too many dependencies to install, too complex and badly documented compiling procedure. I always rely on Orphis buildbot.
-v1.2.1-803-g 59847c9 is unaffected;
-v1.2.1-807-g d4793cc and newer are affected.
.

**Comment by pal1000** [comment]
Finally managed to build PCSX2 from source. Project level path settings are really annoying.
Here is the full crash data:
![temp](https://cloud.githubusercontent.com/assets/1138235/5611300/acf3f8e6-94cd-11e4-97e7-077396fe67be.png)
![temp2](https://cloud.githubusercontent.com/assets/1138235/5611298/acf14e98-94cd-11e4-99c2-60eed3789970.png)
![temp3](https://cloud.githubusercontent.com/assets/1138235/5611299/acf3c934-94cd-11e4-8a6a-b84275faa4b3.png)

**Comment by pal1000** [comment]
Built it using

**Comment by pal1000** [comment]
Reverting #405 767b841 works around this issue. The other commit does not affect it.

**Comment by avih** [comment]
Thanks for the stack trace. It seems that when OpenCL was disabled at #405, the section which contains the line which crashes wasn't disabled too.

I can't compile PCSX2 right now but it should be easily fixable.

**Comment by gregory38** [comment]
Test the PR. It will likely fix the crash (windows only).

**Comment by pal1000** [comment]
I confirm it fixes it for me.

**Comment by uyjulian** [comment]
👍 on windows!
