### ISSUE TITLE
[BUG] Pilot down behind ennemy lines: crash at boot.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4083]
**Describe the bug**
The game crash at boot with PS2 sdk errors.

![image](https://user-images.githubusercontent.com/26351275/103448628-69e29c00-4c9c-11eb-884b-fa8407725be2.png)

**To Reproduce**
Load the game.

**Expected behavior**
The game should work and display graphics ingame.

**behavior before the regression**
The game used to boot but never showed anything when going ingame due to a VU1 mpg cmd never beeing send.

This was the issue that the patch used to solve.

**To sum up the report, the game was already broken but the vif fix for batman makes it worse than before.**

**Emulation Settings**
DMAC busy hack, have an effect on the hang but doesn't solve the ingame blank graphics issue.

![image](https://user-images.githubusercontent.com/26351275/103448634-8b438800-4c9c-11eb-88c5-521c90cc4c3a.png)

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**

[Pilot down behind ennemy lines regression.zip](https://github.com/PCSX2/pcsx2/files/5759605/Pilot.down.behind.ennemy.lines.regression.zip)

**Regression commit**

https://github.com/PCSX2/pcsx2/commit/ab0d785ab5ff30de47d424ce4b83d9f65e3961e4

**Comment by refractionpcsx2** [comment]
Either it just worked for me, or you didn't make the block big enough.

**Comment by refractionpcsx2** [comment]
I tested all the way back to 1.6.0 and the game is still a broken mess spamming DMA errors and Ingame is just a blue screen (although worse now, if I make it so the DMA's don't screw up)

**Comment by refractionpcsx2** [comment]
Okay I made it work without the patch by making VIF1 start instantly when it's called, but the game is very very slow and possibly broken.

**Comment by prafullpcsx2** [comment]
It is a regression introduced in https://github.com/PCSX2/pcsx2/commit/25887c62eee45f9ad2480ef3c2e14b24c8df6f53 if it helps.

**Comment by refractionpcsx2** [comment]
Not really, I know why that older version works, because it runs VIF instantly, the point is the game starts a VIF1 transfer off, waits like, 100 cycles then overwrites the memory address and QWC amount without checking if VIF1 is running, the game is stupid.

**Comment by Chern40pcsx2** [comment]
I checked this game earlier in my build of the dev-1907 emulator, you need to use speedhacks there so that the game doesn’t slow down, and it’s not broken at all, I interrogated exactly half of it, and I didn’t notice any bugs, I didn’t go any further, because the game is all complicated  after all.
