### ISSUE TITLE
[BUG] X2 Wolverine's Revenge : Black Screen In gsdx HW mode

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#4086]
**Describe the bug**
X2:Wolverine's Revenge game doesn't display ingame graphics (and some menus) in HW mode.

**To Reproduce**
Run the game in gsdx HW mode and notice black screen.

**Expected behavior**
SW mode displays everything just fine and similar thing is expected in HW mode.  The issue is more or less same as primal game.

**GS Settings**
Game should be run in HW mode to display the black  screen. Enabling preload frame data will display the correct frame for one second but remains stuck there. So running the single frame gsdump with preload frame data enabled may give false indication that all is well.

**Emulation Settings**
Any (don't matter)

**Logs and Dumps**
GS dump:-
[x2 wolverine revenge.zip](https://github.com/PCSX2/pcsx2/files/5760257/x2.wolverine.revenge.zip)

Multiframe dump:-
[x2 wolverine multiframe dump.zip](https://github.com/PCSX2/pcsx2/files/5760268/x2.wolverine.multiframe.dump.zip)

Block dump (can be useful, run with skipmpeg hack):-
http://www.filedropper.com/x2-wolverinesrevengeusa2021-00-0122-33-35

**Comment by Oymat** [comment]
update: Still happening on the latest nightly.

**Comment by Mrlinkwii** [comment]
hows this on latest nighlty ?

**Comment by refractionpcsx2** [comment]
Weirdly almost works?

![image](https://user-images.githubusercontent.com/6278726/218076948-61b375d3-0fa0-4925-b61c-99a49194cfed.png)

**Comment by Mrlinkwii** [comment]
nice

**Comment by prafullpcsx2** [comment]
Fixed by https://github.com/PCSX2/pcsx2/commit/4a3f0ccf96e498de758d6d5b22824700535fc007

**Comment by refractionpcsx2** [comment]
*Mostly fixed :D
