### ISSUE TITLE
[BUG] Fuuun Super Combo: broken introduction screens.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4088]
**Describe the bug**
When starting the game, you will see the upper part of various copyright screens beeing else corrupted or cut of.

<img width="886" alt="Capture" src="https://user-images.githubusercontent.com/26351275/103459893-70abf600-4d12-11eb-9467-2532dec227ed.PNG">

Note: The issue changes a bit between software and Hardware but the main problem remain.

**To Reproduce**
Just load the game.

**Expected behavior**
The copyright screen should be properly displayed from top to bottom.

**GS Settings**
Everything tried, no success.

**Emulation Settings**
Everything default.

**System Info (please complete the following information):**
PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
GS Dump comming soon

**Comment by prafullpcsx2** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/4348
