### ISSUE TITLE
[BUG] Official U.S. PlayStation Magazine Demo Disc 57: Missing water effects.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4090]
**Describe the bug**
When starting the demo, you will be in a water environnement in which, you can move to access various content, the water effect in that area is broken in hardware mode (mostly missing) no matter which settings.

<img width="891" alt="Capture" src="https://user-images.githubusercontent.com/26351275/103460616-fa11f700-4d17-11eb-97d4-1292182f083d.PNG">

**To Reproduce**
Load the issue 57 of the PS2 magazine US edition.

**Expected behavior**
The water effect should be represented like software:

<img width="893" alt="Capture2" src="https://user-images.githubusercontent.com/26351275/103460637-14e46b80-4d18-11eb-9b3c-140c9b3f1a5f.PNG">

**GS Settings**
Everything default.

**System Info (please complete the following information):**
PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
[PS2 magazine 57 watr issue.zip](https://github.com/PCSX2/pcsx2/files/5760450/PS2.magazine.57.watr.issue.zip)

**Comment by Mrlinkwii** [comment]
[issue_4090.zip](https://github.com/PCSX2/pcsx2/files/12443860/issue_4090.zip)
updated GS dump
