### ISSUE TITLE
[BUG] Zone of the Enders the 2nd runner: missing text with default cyclerate.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4091]
**Describe the bug**
In Zone of the Enders the 2nd runner, the options menu have some missing text with the default cyclerate (only ON is present under SORTIE):

<img width="891" alt="Capture" src="https://user-images.githubusercontent.com/26351275/103462186-d785db00-4d23-11eb-859c-8852f039bdcb.PNG">

Note: EE Cyclerate to +3 solve the issue (timing hack or lower cyclerate doesn't do anything).

**To Reproduce**
Load the game, go to the options menu.

**Expected behavior**
The text should have no display issues:

<img width="889" alt="Capture2" src="https://user-images.githubusercontent.com/26351275/103462222-0439f280-4d24-11eb-9fbf-ef50749a69ba.PNG">

**Emulation Settings**
EE Cyclerate to +3

**System Info (please complete the following information):**
PCSX2 Revision: pcsx2-v1.7.0-dev-817-gc998a51f7-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Logs and Dumps**
[ZOE 2 text bug.zip](https://github.com/PCSX2/pcsx2/files/5760555/ZOE.2.text.bug.zip)

**Comment by JordanTheToaster** [comment]
Works fine on latest master v1.7.4363.

![image](https://user-images.githubusercontent.com/80843560/230786393-8596efc0-564b-4e20-9e07-4f056571fda1.png)
