### ISSUE TITLE
[BUG] Multiple games can no longer read back folder memory cards 

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#4098]
**Describe the bug**
When playing Ratchet and Clank: Going Commando or Ratchet and Clank: Up your Arsenal, folder memory cards can be used to create a new save file and successfully save throughout the game session. However, upon rebooting the game, it will not be able to see its save data and instead try to create new empty save files, overwriting those which already exist on disk.

Update: Add to the list of affected games:
- Gran Turismo 4
- Lego Star Wars 2

**To Reproduce**
Start the first level of either game. Simply starting the level will create the save file. Reboot the game and attempt to load. The game will prompt that no saves exist. Using this same folder memcard in an older build, the save will be found and is perfectly loadable, suggesting there is no damage done to the data, just an inability to read it back.

**Expected behavior**
The game should present the list of save files, not say that none are present.

**GS Settings**
Not a GS issue, but upscaling at 6x.

**Emulation Settings**
All defaults (EE/VU rounding/clamping, MTVU/Instant VU1 disabled, no EE cyclerate changes). EE and IOP interpreters do not help.

**GS Window Screenshots**
Nothing graphical to show.

**System Info (please complete the following information):**
 - Last Working PCSX2 Revision: 1.7.0-dev-686
 - First Failing PCSX2 Revision: 1.7.0-dev-701 (commits in between are all no-builds, same PR? Looks like the major GameDB overhaul)
 - OS: Windows 10
 - CPU: Intel i7-8700K
 - GPU: Nvidia GTX 1070 Ti

**Logs and Dumps**
Emulog attached for Ratchet and Clank: Up your Arsenal, though it is rather uneventful.
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/5767768/emuLog.txt)

**Comment by AmFobes** [comment]
Can verify this problem exists on dev-797.
Shutting down GTA: LCS after saving then starting back up will lead to no saves being found by the game.

**Comment by refractionpcsx2** [comment]
Does this persist with #3941 ?

**Comment by RedPanda4552** [comment]
Issue persists on that PR, yes.

**Comment by PawTM** [comment]
Tested on Gran Turismo 4, this issue only seems to appear when having the "Automatically manage saves based on running game" option enabled.
![grafik](https://user-images.githubusercontent.com/62476228/103671729-9982f400-4f7b-11eb-84b6-001e6bab44d9.png)
Without it, the game loads my saves just fine.

**Comment by RedPanda4552** [comment]
A little digging, the common factor between these games is that they all use memcard filters in gamedb. Games without any filters seem to work fine, games with filters will fail. Disabling filtering completely (and thus generating a FAT for all of the folder memcard's contents all at once) won't have this problem, as paw noted.

**Comment by RedPanda4552** [comment]
Resolved by #4105
