### ISSUE TITLE
Sniper Elite - game drows to snale speed in a second mission 

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#4111]
PCSX2 1.7.0-20210105231959 - compiled on Jan  6 2021

Using default speed settings 2 and dx1 same issue in software mode

the game drops to slide show in the second mission here
However the system shows that it is 60 fps and 100%

https://user-images.githubusercontent.com/5770076/103815843-6759bb00-507d-11eb-8041-c097c41b0c4b.mp4

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/5777991/emuLog.txt)

memory card (load for that spot)

[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/5777999/Mcd001.zip)

**Comment by tadanokojin** [comment]
Please properly fill out the issue template.

**Comment by Levan7** [comment]
@tadanokojin 
 I will definitely keep that in mind but i think i provided with all necessary information.

**Comment by tadanokojin** [comment]
I'll reopen the issue when you fill out the template as I requested.
