### ISSUE TITLE
[Feature Request] Add 64-bit builds to the buildbot

### ISSUE THREAD

**Issue by extherian** [PCSX2/pcsx2#4114]
Now that 64-bit support has been merged, I'd appreciate it if a 'Windows 64bit' column was added to the buildbot next to the 'Windows 32bit' column. This would mean that anyone else interested in the 64-bit version wouldn't have to deal with the hassle of trying to compile it by themselves. My computer uses a 64-bit processor and I'm interested in testing how performance differs, if at all, from the 32-bit version. I'm also interested in seeing how being 64-bit affects the size of the binary as well as RAM and VRAM usage.

**Comment by refractionpcsx2** [comment]
We do plan to bring 64bit builds, but they are not currently ready, there is an issue with memcard folders (which there is a PR to fix) but also the software renderer needs to be rewritten for 64bit to work without crashing.

Once this is done, we will happily move to 64bit.

**Comment by tadanokojin** [comment]
They'll be added when they are ready for public use. If you want to test, please do so through official channels.
