### ISSUE TITLE
[BUG] Ar Tonelico (SLUS-21445) Flickering textures in ground

### ISSUE THREAD

**Issue by darkxex** [PCSX2/pcsx2#4116]
**Describe the bug**
dirt floor flickers when I move.

**To Reproduce**
get to the part of there is a dirt road, even in the youtube gameplay with pcsx2 the bug is present, so it is easy to reproduce.

**Expected behavior**
the terrain does not blink.

**GS Settings**
the bug is reproducible in any GS configuration.

**Emulation Settings**

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/17991404/103966525-c7fcfc80-513e-11eb-92b9-62a6f7bdad51.png)
![image](https://user-images.githubusercontent.com/17991404/103966627-ff6ba900-513e-11eb-931f-bfe5065a529c.png)
![image](https://user-images.githubusercontent.com/17991404/103966696-24f8b280-513f-11eb-80e3-f27a7f2cc53a.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 843
 - OS: 
 - CPU: i9 10900k
 - GPU: GTX 1080TI

**Logs and Dumps**
[gsdump](https://github.com/PCSX2/pcsx2/files/5787252/snaps.zip)
[memcard](https://github.com/PCSX2/pcsx2/files/5787280/memcards.zip)

**Comment by refractionpcsx2** [comment]
> tested in vulkan
we don't have a vulkan renderer.

**Comment by darkxex** [comment]
Sorry, is d11 and software. I should have written vulkan out of habit.

**Comment by tadanokojin** [comment]
I'd like it if you could please follow the issue template we provide:
```
**Describe the bug**
<!-- A clear and concise description of what the bug is. -->

**To Reproduce**
<!-- Steps to reproduce the behavior. -->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**GS Settings**
<!-- Any non-default settings for GS. -->
<!-- If you don't want to list them out, please provide screenshots of your configuration window (including hw hacks if enabled). -->

**Emulation Settings**
<!-- Any non-default core settings. -->
<!-- If you don't want to list them out, please provide screenshots of your configuration window. -->
<!-- Please note that the safe preset works for most games. -->
<!-- MTVU can have some compatibility issues so please disable it before making a report. -->
<!-- If you need to modify the settings manually because a game requires you to do so to work, please state that explicitly. -->

**GS Window Screenshots**
<!-- If your issue is graphical in nature and you think screenshots will help illustrate your issue, you may do that here. -->

**System Info (please complete the following information):**
 - PCSX2 Revision: <!-- e.g. dev-525 -->
 - OS: <!-- e.g. Windows 10 -->
 - CPU: <!-- e.g. i5-7600 -->
 - GPU: <!-- e.g. GTX 1070 -->

**Logs and Dumps**
<!-- Please feel free to attach any logs, block dumps, GSdump, etc here. -->
<!-- If your problem is graphical in nature it is highly recommended that you provide a GSdump. -->
<!-- GSdump Guide: https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump -->
```

The `<!-- -->` are comments you can delete and place your information
I'd also like it if you could provide a gsdump, you can see in the template there is a link to a guide that tells you how create one. I suggest using a program like 7zip to compress it down.

Also is this issue present on real hardware?

**Comment by darkxex** [comment]
**GS DUMPS**
[snaps.zip](https://github.com/PCSX2/pcsx2/files/5787252/snaps.zip)

**GS Settings**
the bug is reproducible in any GS configuration.

**issue present on real hardware?**
no.

**Comment by darkxex** [comment]
**Memcard with save in the position of screenshot**
[memcards.zip](https://github.com/PCSX2/pcsx2/files/5787280/memcards.zip)

**Comment by orbea** [comment]
Are you sure this doesn't happen on real hardware?

**Comment by darkxex** [comment]
it seems like it does happen on real hardware, but I'm not sure.

**Comment by darkxex** [comment]
https://www.youtube.com/watch?v=H6UDFqXXUHM if this video is captured on a real ps2 and not an emulator, then it should be a hardware error.

**Comment by refractionpcsx2** [comment]
hmm, I can't see it happening in that video.  I guess it could be a Z fighting issue on the emulator, that's possible.

**Comment by darkxex** [comment]
Look carefully at the first 5 seconds, I can see it but not as strong as in the emulator.

**Comment by refractionpcsx2** [comment]
Where abouts am I looking? I tried looking around the scene and couldn't see any flickering.

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/104126462-72da0a00-533b-11eb-8f68-0523abffe4c3.png)
![image](https://user-images.githubusercontent.com/17991404/104126489-9f8e2180-533b-11eb-9408-f69dec14e03b.png)
friend, you only need to focus your vision on a single point, and not look at the whole scene.

**Comment by darkxex** [comment]
I will leave the subject open, because I still don't know if that video is captured on a real ps2 or not.

**Comment by refractionpcsx2** [comment]
> friend, you only need to focus your vision on a single point, and not look at the whole scene.

yes, my problem was I didn't know which single point to focus on exactly.

As for if the video is from the PS2 or not, I'm edging on not because of how crisp it is (for 480p anyway) and videos from a real console tend to be a little smudged and blurry.

But I see you left a comment on the video so maybe we'll see what the author says.

**Comment by Mrlinkwii** [comment]
can this be checked again on latest :)

**Comment by darkxex** [comment]
> can this be checked again on latest :)

Friend, I don't think it's necessary, I contacted a youtuber who had a real Ps2, and the problem is hardware. You can watch the YouTube video that I posted a long time ago and you will see that the owner of the video responded. I'll leave the topic closed because the error is replicated on a real Ps2.
