### ISSUE TITLE
[Regression] Disc swapping is more broken with CDVD merge in 1.7

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4119]
**Describe the bug**
The disc doesn't appear when in the browser (BIOS) when you disc-swap, other disc-swapping features are not working as intended.

**To Reproduce**
Go into BIOS with No ISO and while in browser switch to ISO.

Result:

1.7
![image](https://user-images.githubusercontent.com/24227051/104071959-77eb6c00-520a-11eb-91e0-d58d9aa10c70.png)

**Expected behavior**
The disc should pop-up after a moment to say it sees a disk.

1.6
![image](https://user-images.githubusercontent.com/24227051/104072292-3dce9a00-520b-11eb-86e5-70418398dda9.png)

**System Info (please complete the following information):**
 - PCSX2 Revision:  dev-844
 - OS: W10 Pro 20H2
 - CPU: i7-9750H
 - GPU: 2060M 6GB

**Comment by RedPanda4552** [comment]
Chipping in my tests on this, disc swap behavior ingame is still consistent with that of a physical PS2. The running game will (probably) have audio cut out, but still run until it has to read from disc again, at which point it will lock up. Test I ran was Ratchet 3, disc swapping at the start of the Veldin level to Ratchet 2. Was able to complete the level but hit a trap exception right where the ending FMV would have started.

**Comment by RedPanda4552** [comment]
@GovanifY Narrowed down the regression to 1.7.0-dev-321: https://github.com/PCSX2/pcsx2/commit/551847411f99a98c94777176472c61b99b76549c

**Comment by piorrro33** [comment]
I think I found a workaround, pausing the emulator then unpausing (double-tapping ESC) seems to effectively swap discs.

**Comment by TheLastRar** [comment]
Can you try this pr #4122
