### ISSUE TITLE
[Regression] Defocused window on boot - Hotkeys don't respond anymore

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4120]
**Describe the bug**
While testing i like to use F4 , tab and other hotkeys. I have a laptop screen with is lid closed and an external monitor which is my actual main screen. But i need to always click on the screen or alt-enter to make my hotkeys work on the emulation. (It acts like 1.6 correctly on rare occasions)

**To Reproduce**
Get new devbuild
Unzip and go through first-time-wizard
Change no settings
Start a random PS2 game, full or fast boot
You boot in windowed mode
Try any hotkey (F4, Tab , etc)

**Expected behavior**
In 1.6 it will make the emulation correctly an active window, no matter if its fullscreen or windowed mode.
![image](https://user-images.githubusercontent.com/24227051/104073481-10cfb680-520e-11eb-8773-42606f7acbc8.png)

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/24227051/104073304-a1f25d80-520d-11eb-892e-70c677e5de85.png)
Using this option on the devbuild seems to fix this issue on first-booting on devbuild in windowed mode.

**System Info (please complete the following information):**
 - PCSX2 Revision:  dev-844
 - OS: W10 Pro 20H2
 - CPU: i7-9750H
 - GPU: 2060M 6GB

**Comment by lightningterror** [comment]
Regression build needs to be identified.

**Comment by lightningterror** [comment]
Status?

**Comment by RedDevilus** [comment]
Triggers even on 1.6, sometimes it fixes by clicking outside the emulator and back on emulation window. Other times it works out of the box and rest i need to alt+enter to make it work.

**Comment by RedDevilus** [comment]
Fixed on PR 4404.
