### ISSUE TITLE
[BUG] Bakufuu Slash!! Kizna Arashi 

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4125]
**Describe the bug**
corrupted video from the camera. i can confirm that at least some of the video stream is from the camera because it reacts to the brightness in the room.

**To Reproduce**
~~just run the game and it comes to a screen asking you to plugin the eyetoy. you can press start and music will start/stop playing~~
corrupted video from camera

**Expected behavior**
~~the game shouldn't even show a screen asking for the eyetoy to be plugged in because it is~~
clear mpeg2 video from camera

**GS Settings**
default: software renderer

**Emulation Settings**
all defaults

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-873
 - OS: windows 10
 - CPU: i5-9600kf
 - GPU: gtx 960
**Logs and Dumps**
[KIZNA (2021-00-10 12-32-35).zip](https://github.com/PCSX2/pcsx2/files/5793151/KIZNA.2021-00-10.12-32-35.zip)

**Comment by Florin9doi** [comment]
```diff
diff --git a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
index 32a1ff8a7..b79cb6d3c 100644
--- a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
+++ b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
@@ -338,6 +338,8 @@ namespace usb_eyetoy

                switch (request)
                {
+                       case InterfaceOutRequest | USB_REQ_SET_INTERFACE:
+                               return;
                        case VendorDeviceRequest | 0x1: //Read register
                                data[0] = s->regs[index & 0xFF];
                                p->actual_length = 1;
```

**Comment by jackun** [comment]
Hmm, `usb_desc_handle_control` ->`usb_desc_set_interface` should do it already

**Comment by Florin9doi** [comment]
The request is made for an invalid interface (0xff??) and usb_desc_set_interface returns error

**Comment by seta-san** [comment]
after struggling to get the freemcboot and opl loaded on my ps2 i've found that having music play when you press the start button on the "please plugin the eyetoy screen" is totally normal behavior. 

unfortunately i can't get past it because the game doesn't like having to compete being loaded on a usb drive and reading from the usb camera.

**Comment by seta-san** [comment]
> First issue is that pcsx2 sends stall for a set interface request. The attached patch avoid this issue, however the game isn't playable due to video corruption
> 
> ```diff
> diff --git a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
> index 32a1ff8a7..b79cb6d3c 100644
> --- a/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
> +++ b/pcsx2/USB/usb-eyetoy/usb-eyetoy-webcam.cpp
> @@ -338,6 +338,8 @@ namespace usb_eyetoy
> 
>                 switch (request)
>                 {
> +                       case InterfaceOutRequest | USB_REQ_SET_INTERFACE:
> +                               return;
>                         case VendorDeviceRequest | 0x1: //Read register
>                                 data[0] = s->regs[index & 0xFF];
>                                 p->actual_length = 1;
> ```

i wanted to see this. it actually does something really interesting. if you make the room dark the bottom half of the screen gets steady but the top half remains freaking out.

**Comment by Florin9doi** [comment]
#3953

**Comment by seta-san** [comment]
Fuck. I forgot i made one a while ago

**Comment by Florin9doi** [comment]
The invalid set_interface request is no longer received if we respond with a correct config descriptor : https://github.com/jackun/USBqemu-wheel/issues/30#issuecomment-634974769 
This should be better than sending a bad descriptor and then ignoring a bad request.

**Comment by jackun** [comment]
Uh, oops. Maybe enough to fix this

```
diff --git a/pcsx2/USB/qemu-usb/desc.cpp b/pcsx2/USB/qemu-usb/desc.cpp
index c72254abb..c1ff13a48 100644
--- a/pcsx2/USB/qemu-usb/desc.cpp
+++ b/pcsx2/USB/qemu-usb/desc.cpp
@@ -491,6 +491,7 @@ int usb_desc_parse_config(const uint8_t* data, int len, USBDescDevice& dev)
                                        ep.bRefresh = d->u.endpoint.bRefresh;
                                        ep.bSynchAddress = d->u.endpoint.bSynchAddress;
                                        ep.extra = data + pos + d->bLength;
+                                       pos += *ep.extra;
                                }
                                iface->eps.push_back(ep);
                        }

```

**Comment by refractionpcsx2** [comment]
Can we retest with master please, see if this is resolved now?

**Comment by Florin9doi** [comment]
It progressed from «Intro» to «Menus», but the video is still corrupted

**Comment by Florin9doi** [comment]
First I suspected that this game uses a different format but after I configured the hardware camera for this game, I captured some packets and I injected them into PCSX2, nothing was changed. 
After more tests, I observed the following pattern: the EyeToy games that use DMA_MODE_NORMAL works, but the EyeToy games that use DMA_MODE_CHAIN doesn't works. This issue may be similar to #3432.

**Comment by refractionpcsx2** [comment]
I honestly doubt it's much of an issue with chain mode, it's probably just down to the IPU library it uses, the broken one happens to chain things in.  Lots of games send video the IPU via chain mode (and even pause/resume it mid transfer) and they work absolutely fine.

**Comment by seta-san** [comment]
Was https://github.com/jackun/USBqemu-wheel/issues/55 ever figured out?

**Comment by refractionpcsx2** [comment]
> Was [jackun/USBqemu-wheel#55](https://github.com/jackun/USBqemu-wheel/issues/55) ever figured out?

does it have an impact on this issue?

**Comment by seta-san** [comment]
> > Was [jackun/USBqemu-wheel#55](https://github.com/jackun/USBqemu-wheel/issues/55) ever figured out?
> 
> does it have an impact on this issue?

That's what I was wondering
