### ISSUE TITLE
texmod loading support   very important 

### ISSUE THREAD

**Issue by kurdischerjapane** [PCSX2/pcsx2#4132]
it will be very cool if we have the opurtunity to remastered our own favourite  ps2 games  i tried but  the custom textures going away during a short  time but if i pause it and continue again the textures loaded it its therer any hope? and also the texture mod is only available for direct x 9. i used pcsx2 1.4.0 
![bandicam 2021-01-12 19-23-31-310](https://user-images.githubusercontent.com/33580065/104356576-6658db80-550c-11eb-8d99-dbf6e70d88c7.jpg)

**Comment by refractionpcsx2** [comment]
if texmod requires DX9, then there's no chance of it coming back, DX9 is depreciated.  You would need to ask the texmod people to support a newer version of DX, or OpenGL

**Comment by kurdischerjapane** [comment]
but why dophin and psp emulator support custom textures but not the best console ever? i think if we can make something like render doc in pcsx2 capture the frame with it and make a texture folder  and replace it we are really far its this possible?

**Comment by kurdischerjapane** [comment]
i finally found the error the modtool only reconise the emulator by Capturing  not the game inside thats why the custom  textures transfer erverywere. from the beginning  thats why just have to clearfy the location

**Comment by RedDevilus** [comment]
Textures injection is per-game basis  , it's not the same as other emulators. It's not like there is a true GPU in PCSX2 as well.

**Comment by kurdischerjapane** [comment]
but therer must be a way textrung custom textures completely

**Comment by Mrlinkwii** [comment]
Tth

**Comment by AmFobes** [comment]
> but therer must be a way textrung custom textures completely

Sorry but no, there isn't a way currently. As said above, there is no single way to inject textures into every single game, games run on different engines.

**Comment by kurdischerjapane** [comment]
i got a other question is it possible play ps2 games with extracted iso file?

**Comment by AmFobes** [comment]
Again, depends on the ps2 game. Some games have hidden assets in the ISO that you won't be able to extract with generic tools.

Also, for general support please use the pcsx2 forums or pcsx2 discord.
Thank you.

**Comment by tadanokojin** [comment]
This issue isn't valid.
