### ISSUE TITLE
pcsx2 emulator support 

### ISSUE THREAD

**Issue by kurdischerjapane** [PCSX2/pcsx2#4133]
it will be very cool if we have the opurtunity to remastered our own favourite ps2 games i tried but the custom textures going away during a short time but if i pause it and continue again the textures loaded it its therer any hope? and also the texture mod is only available for direct x 9. i used pcsx2 1.4.0. ui mod crashed the emulation, ps2 console is the best console ever need support custom textrues. and any hope for that? 
![bandicam 2021-01-12 19-23-31-310](https://user-images.githubusercontent.com/33580065/104374230-da51ae80-5521-11eb-9cf1-6255b97e8aef.jpg) 
**Description**

**Reason**

**Examples**

**Comment by MrCK1** [comment]
You already have an issue open for texture replacement, this is a duplicate. If you need general support please use https://forums.pcsx2.net instead.
