### ISSUE TITLE
[BUG] Hot Wheels Velocity X - Underworld splash graphical issue

### ISSUE THREAD

**Issue by i0brendan0** [PCSX2/pcsx2#4139]
**Describe the bug**
In the Underworld track, the green water/slime splashes into the camera. The splashes cause green artifacts pop up all over the screen

**To Reproduce**
Pick the Underworld track and drive forward through the green liquid.

**Expected behavior**
Not to have the screen full of flashing green artifacts.

**GS Settings**
It doesn't seem to matter what basic settings are chosen for it, but I provided a screenshot in the archive below.

**Emulation Settings**
Almost everything was default except for EE/FPU Advance Recompiler Options. That I set to nearest for the bug in SSX Tricky. Even

**GS Window Screenshots**
Included in the archive

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.6.0
 - OS: Windows 10
 - CPU: Ryzen 5 3600
 - GPU: GTX 1660 Super

**Logs and Dumps**
https://mega.nz/file/bp5EnKTb#BbYlDStMrOXZBa4YKhFePvMIbvzTkYqLc8mQRO4HMU0

Reply if the link doesn't work.

**Comment by refractionpcsx2** [comment]
Did you revert the FPU changes you made for SSX? since that could break other games.

**Comment by i0brendan0** [comment]
I did. It did nothing that I could tell. I will check with the latest build.

**Comment by refractionpcsx2** [comment]
Thanks

**Comment by i0brendan0** [comment]
Nope. The v1.7.0-dev-869-g618940d78 build does not do anything to fix it.

**Comment by refractionpcsx2** [comment]
okay thanks for trying
