### ISSUE TITLE
[BUG] severe graphic corruption in Jak 2, when playing Onin's minigame

### ISSUE THREAD

**Issue by Sgtbomber91** [PCSX2/pcsx2#4141]
**Describe the bug**

severe graphic corruption in Jak 2 (SCUS-97265), when playing Onin's minigame
![jak2_minigame_corrupted](https://user-images.githubusercontent.com/40438332/104622736-eceaf580-5691-11eb-8da9-19ebd6d34907.jpg)

**To Reproduce**

Start play Onin's symbol popping minigame. After some time, severe graphic corruption will happen (visual garbage, missing textures, flickering stuff)
Switching from DirectX11 to OpenGL doesn't resolve the issue.
Software mode works fine.

**Expected behavior**

No graphic corruption, as the minigame plays on
![jak2_minigame_ok](https://user-images.githubusercontent.com/40438332/104622742-ef4d4f80-5691-11eb-8f1c-5f10dfbd3150.jpg)

**GS Settings**

**Emulation Settings**

none, since even the safest GS preset possibile and/or everything at Default for the Graphic plugin causes the issue

**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-869
 - OS: Win10
 - CPU: Amd Ryzen 1700
 - GPU: AMD radeon RX Vega56

**Logs and Dumps**
https://www.dropbox.com/s/ei78bm00iwb8n8p/jak2_minigame_corrupted.gs.7z?dl=0

**Comment by MrCK1** [comment]
Closing since there's another one open

**Comment by refractionpcsx2** [comment]
software mode and hardware mode look the same in that GS Dump, they both look like the top picture.
