### ISSUE TITLE
[BUG] Old CDVD regression from 1.5 - Physical disc mode

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4143]
**Describe the bug**
Inedicabilis has an odd edge-case with running via a disc reader on plugin/disc mode of CDVD (not ISO). Games won't run on newer versions of PCSX2.
1.4 = works
1.6 = broken
1.7 = broken

---1.5 2227 functional
---1.5 2229 non functional

PR 2095 seems to be the regression
https://github.com/PCSX2/pcsx2/pull/2095

![RegressionCDVD](https://user-images.githubusercontent.com/24227051/104672404-074bc000-56e0-11eb-9bd7-b85012f4c8ee.png)

**To Reproduce**
Lots of users can't reproduce this
I assume the process is:
1. Use a specific DVD-reader
2. CDVD set to Disc
3. Run a random PS2 game

**Expected behavior**
It has to boot the game as normally.

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.6 + v1.7.0-dev-868
 - OS: Windows 10
 - CPU: i5 9400F
 - GPU: RTX 2060

**Logs and Dumps**
[CDVD_RegressionTesting.txt](https://github.com/PCSX2/pcsx2/files/5818012/CDVD_RegressionTesting.txt)
[emuLog-EdgeCaseCDVD.txt](https://github.com/PCSX2/pcsx2/files/5818013/emuLog-EdgeCaseCDVD.txt)

**Comment by turtleli** [comment]
From the attached log:
```
Track 1 start sector: 0
 * CDVD: Disk Type: CD-ROM
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1773296 sectors)
```
The log is a bit strange because it recognises the disk as a CD when it's actually a DVD. Perhaps the ioctl that probes DVD info is failing.
https://github.com/PCSX2/pcsx2/blob/ade09b06302606266fdd86aab4ddce1ec27e73f9/pcsx2/CDVD/Windows/IOCtlSrc.cpp#L217-L218

From the nearby comment, increasing the size of `buffer` might potentially solve the issue.

Side note: IIRC the nearby comment is a little wrong, I think I did some testing quite a while back and it's not actually Windows requiring 18+ bytes from the layer descriptor to be read.

**Comment by refractionpcsx2** [comment]
You're right about windows not needing 18 bytes, simply using sizeof(DVD_LAYER_DESCRIPTOR) works, at least on my machine.  On the guys machine we were testing with however it seems to still hate it, I tried reporting the size of DVD_LAYER_DESCRIPTOR on his PC, but I'm guessing that gets compiled in to the program, so couldn't really check it.  I'm not sure what size it does expect, but it's happy with 32 bytes, even if that's too much, at least we have a bit of buffer.

**Comment by turtleli** [comment]
Yeah, `sizeof(DVD_LAYER_DESCRIPTOR)` isn't machine dependent. I think the actual size of the descriptor is 2048 bytes, it's just that byte 17 onwards is "Media Specific" data and probably isn't useful. IIRC my drive requires the buffer to be at least 22 bytes (4 byte header + 18 bytes of the descriptor) for that command to work successfully.

**Comment by refractionpcsx2** [comment]
Yeah, it's very weird, i dunno what size that guys drive requires but it hates 22 bytes (and 23 bytes, I was hopeful lol), but 32 bytes seems fine. No harm in it being too big, better than being too small :)
