### ISSUE TITLE
[BUG] Arch Linux build.sh "'build.ninja': No such file or directory"

### ISSUE THREAD

**Issue by TechieAndroid** [PCSX2/pcsx2#4144]
- PCSX2 Revision: master
 - OS: Arch Linux

[CMakeOutput.log](https://github.com/PCSX2/pcsx2/files/5818941/CMakeOutput.log)
[CMakeError.log](https://github.com/PCSX2/pcsx2/files/5818942/CMakeError.log)

**Comment by AmFobes** [comment]
Line #1 of CMakeError.log
    /usr/share/cmake-3.19/Modules/CheckFunctionExists.c:17: undefined reference to `pcap_get_pfring_id'
Try installing `libpcap` by doing `sudo pacman -S libpcap`

**Comment by refractionpcsx2** [comment]
No support for retroarch, you need to ask Libretro for help there.
