### ISSUE TITLE
shadow man 2 gameplay issue

### ISSUE THREAD

**Issue by kurdischerjapane** [PCSX2/pcsx2#4147]
if iam in combat with a enemy  i get texture errors i dont know why 
![bandicam 2021-01-15 23-21-01-578](https://user-images.githubusercontent.com/33580065/104784522-c3f95c00-5788-11eb-95e9-49ba0122ab1c.jpg)

![bandicam 2021-01-15 23-21-01-578](https://user-images.githubusercontent.com/33580065/104784408-7bda3980-5788-11eb-8f38-ca2173fb4c36.jpg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**GS Settings**

**Emulation Settings**

**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision: 
 - OS: 
 - CPU: 
 - GPU: 

**Logs and Dumps**

**Comment by refractionpcsx2** [comment]
Disable MTVU
