### ISSUE TITLE
[BUG] Frequent stutter caused by cdvd streaming.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4150]
**Describe the bug**
In PCSX2, very often the emulation will pause for a millisecond then resume straight during gameplay (usually when a background music changes or a dialogue cutscene is triggered).

The slower the storage on which the games are on is, the worse the issue gets. This also happens when using the Windows 10 software raid 0 which *should* improves disc latencies over a single hard drive.

This problem is very major as it seriously impact the playability of games even on very powerfull computers.

This is an exemple of this (sorry for the audio glitches, this is because of a bug with my capturing software), when the music switches, the emulation pauses for a short amount of time:

https://user-images.githubusercontent.com/26351275/104845882-01203400-58d8-11eb-9b94-b9abcff1ff83.mp4

**To Reproduce**
Play a game on a 5400rpm drive or a software raid 0 and expect a bunch of stutters when the game reads the dvd sequentially during gameplay

**Expected behavior**
The emulator should never stutter at any point during gameplay when reading the disc.

System Info (please complete the following information):
PCSX2 Revision: pcsx2-v1.7.0-dev-877-g6c81bb54f-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Comment by refractionpcsx2** [comment]
I dunno what you expect us to do :P Get better storage lol

**Comment by atomic83GitHub** [comment]
Well, on a variety of storages I have, this happens, even on some 7200rpm drives.

**Comment by lightningterror** [comment]
As refraction said, also if the drive is under load even a higher rpm one will stutter.

**Comment by tellowkrinkle** [comment]
You can try compressing to a CSO, as the reader for those attempts to cache ~128k of data ahead of the current read position
You would expect the operating system to do it for the basic file reader but maybe it's doing a bad job
