### ISSUE TITLE
[BUG] Regression: Ratchet Deadlocked NETGUI tool crashing.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4153]
**Describe the bug**
The NETGUI tool in the game "Ratchet Deadlocked" crashes on loading.

![image](https://user-images.githubusercontent.com/26351275/104852797-37bc7580-58fd-11eb-956d-479e6f362cd5.png)

**To Reproduce**
Load Ratchet Deadlocked, load multiplayer then online, and select configure network settings.

**Expected behavior**
The tool should work.

**Regression commit**

This regression was introduced between builds 648 and 651, likely by this commit: 

https://github.com/PCSX2/pcsx2/commit/32f14f48b0484f56d14b453d6237d6b0a6e9d500

**Emulation Settings**
All default.

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-877-g6c81bb54f-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Comment by refractionpcsx2** [comment]
It was this commit https://github.com/PCSX2/pcsx2/commit/3d43293a5d9115c45f12e3c3f6447be70b56fee5

Game does toSPR transfers in normal mode with a QWC of 0 and it doesn't seem to like the changes I made. Will investigate
