### ISSUE TITLE
[BUG] Perfect Ace 2: missing field view when selecting a tennis court.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4157]
**Describe the bug**
In the game "Perfect Ace 2", when selecting a tennis court, the preview of the selected court doesn't appear no matter which settings:

![image](https://user-images.githubusercontent.com/26351275/104855814-3bf18e80-590f-11eb-9374-f3237d2ca833.png)

**To Reproduce**
Load the game, select single player and choose a tennis court.

**Expected behavior**
The preview of the tennis court should appear in the window:

<img width="674" alt="Capture" src="https://user-images.githubusercontent.com/26351275/104855856-8c68ec00-590f-11eb-9c95-c2ad6b9288d5.PNG">

**GS Settings**
All default.

**Emulation Settings**
All default.

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-877-g6c81bb54f-windows-x86
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**GS Dump and Blockdump**

GS Dump : https://drive.google.com/file/d/1l_QAMkCuOSQnveLe4KolCH5mH4e2025X/view?usp=sharing

Blockdump : https://drive.google.com/file/d/1UdbI0Q4hf2SYvuNezkX3Kv3z6TN9Nfry/view?usp=sharing

**Comment by kozarovv** [comment]
Seems to work fine now. Most likely fixed in https://github.com/PCSX2/pcsx2/commit/cd33a17584fadb7aed29262dc7a1a1109c6ff4de , but i didn't went back to test where it was really fixed, i know it was IPU bug tho. 
![image](https://user-images.githubusercontent.com/15552250/129455239-e52429c7-7142-416c-b9e8-08fff17156f3.png)

**Comment by prafullpcsx2** [comment]
Yes it's https://github.com/PCSX2/pcsx2/commit/cd33a17584fadb7aed29262dc7a1a1109c6ff4de that fixed it. Good job.
