### ISSUE TITLE
MOCUTE-050X-M54-PC isn't yet supported

### ISSUE THREAD

**Issue by devsydungo** [PCSX2/pcsx2#4163]
This is what the program log says
onepad: Joystick (MOCUTE-050X-M54-PC,GUID:050000004d4f435554452d3035305800) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.
![Screenshot from 2021-01-19 11-15-08](https://user-images.githubusercontent.com/29827612/104983400-aa396c80-5a47-11eb-86cd-b005f0030b57.png)

**Comment by lightningterror** [comment]
Can you create and post the mapping here?

**Comment by devsydungo** [comment]
> Can you create and post the mapping here?

I used AntiMicro here:
`M54-PC,platform:Linux,a:b0,b:b1,x:b3,y:b4,back:b10,start:b11,leftshoulder:b6,rightshoulder:b7,leftstick:b13,rightstick:b14,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,`

**Comment by lightningterror** [comment]
Mapping has been submitted upstream.
