### ISSUE TITLE
[BUG] Shinseiki Evangelion 2 (SLPS 25299): Missing graphics with the software renderer

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#4164]
**Describe the bug**

Some graphics are missing when using the software renderer. Most critically, all of the overlays (health bar, etc) are missing during battle scenes, and conveniently for demonstration purposes graphics are missing on the load game screen too. The game works fine with the OpenGL renderer, and DX11 is probably fine too as far as I can see. GS Dump attached.

EDIT: I just noticed this so I'll add it as it's possibly relevant. As you can see in the software renderer screenshot, the arrow in the bottom right corner is being obscured by the black area where a save slot should be. That arrow bounces up and down and should be on top of the save slot graphics, not behind them. Some kind of layering priority problem? Could it be related to #3662?

**To Reproduce**

Go to the load game screen or play through the game until you reach a battle.

**Expected behavior**

All graphics should be present, as when using the hardware renderers

**GS Settings**

No software renderer settings have any effect. 

**Emulation Settings**

No emulation settings have any effect as far as I can tell.

**GS Window Screenshots**

Software renderer:

![gsdx_20210119134440](https://user-images.githubusercontent.com/4227434/105042756-87fe1980-5a5c-11eb-9cda-2b5ffbfdb4c6.png)

OpenGL renderer:

![gsdx_20210119134443](https://user-images.githubusercontent.com/4227434/105042788-94827200-5a5c-11eb-9f70-cf9b1fd891b0.png)

**System Info (please complete the following information):**
 - PCSX2 Revision:  1.7.0-dev-903-gcf33fb3ca
 - OS: Windows 10 20H2
 - CPU: Ryzen 7 3700X
 - GPU: Nvidia RTX 3070

**Logs and Dumps**

[Evangelion2Missing.zip](https://github.com/PCSX2/pcsx2/files/5836234/Evangelion2Missing.zip)

**Comment by prafullpcsx2** [comment]
It was broken here:-

https://github.com/PCSX2/pcsx2/commit/f68f007f008be8bd6ae9aa8264b3b17a44e9ba69

Seems like a pretty major update.
