### ISSUE TITLE
USB Nyx Joy-Con (Nintendo Switch as gamepad via Hekate) not supported

### ISSUE THREAD

**Issue by flarn2006** [PCSX2/pcsx2#4166]
**System Info (please complete the following information):**
 - PCSX2 Revision:  1.7.0-20201215202641
 - OS:  Linux 5.10.7-arch1-1 x86_64
 - CPU:  Intel(R) Core(TM) i7-4930K CPU @ 3.40 GHz
 - GPU:  GTX 1050 Ti

**Logs and Dumps**
    onepad: Joystick (USB Nyx Joy-Con, GUID:03000000ec110000e1a7000010010000) isn't yet supported by the SDL2 game controller API
    Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
    The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
    Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

**Comment by AmFobes** [comment]
Please generate a mapping using this tool
https://www.generalarcade.com/gamepadtool/

Then pr your new mapping here:
https://github.com/gabomdq/SDL_GameControllerDB

**Comment by flarn2006** [comment]
That tool isn't working for me; I'm getting the following error in the
terminal when I try to run it:

Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37:
_dl_call_libc_early_init: Assertion `sym != NULL' failed!

**Comment by lightningterror** [comment]
You can try https://www.generalarcade.com/gamepadtool/ as an alternative.

**Comment by lightningterror** [comment]
Closing as mappings need to be submitted upstream https://github.com/gabomdq/SDL_GameControllerDB.
