### ISSUE TITLE
[Feature Request] Konami ON-SAY Microphone for Japanese Karaoke Revolution Games.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4167]
**Description**
This descriptor has been updated because i obtained the correct microphone for japanese karaoke revolution games.
I've got a descriptor for a konami branded E-UR040 microphone.

**Reason**
make Japanese Karaoke Revolution games work

Information for device AK5370           (VID=0x0556 PID=0x0001):

*** ERROR: Descriptor has errors! ***

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x002C
Current configuration value: 0x00
Number of open pipes: 0

------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0110	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x0556	idVendor
0x0001	idProduct
0x0001	bcdDevice
0x01	iManufacturer
0x02	iProduct     
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x10 0x01 0x00 0x00 0x00 0x08 0x56 0x05 
0x01 0x00 0x01 0x00 0x01 0x02 0x00 0x01 

-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0076	wTotalLength   (118 bytes)
0x02	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x2D	bMaxPower      (90 mA)
Hex dump: 
0x09 0x02 0x76 0x00 0x02 0x01 0x00 0x80 0x2D 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x01	bInterfaceSubClass   (Audio Control Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x00 0x01 0x01 0x00 0x00 

AC Interface Header Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x0100	bcdADC
0x0026	wTotalLength   (38 bytes)
0x01	bInCollection
0x01	baInterfaceNr(1)
Hex dump: 
0x09 0x24 0x01 0x00 0x01 0x26 0x00 0x01 0x01 

AC Input Terminal Descriptor:
------------------------------
0x0C	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bTerminalID
0x0201	wTerminalType   (Microphone)
0x02	bAssocTerminal
0x01	bNrChannels   (1 channels)
0x0000	wChannelConfig
0x00	iChannelNames
0x00	iTerminal
Hex dump: 
0x0C 0x24 0x02 0x01 0x01 0x02 0x02 0x01 0x00 0x00 
0x00 0x00 

AC Output Terminal Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x03	bDescriptorSubtype
0x02	bTerminalID
0x0101	wTerminalType   (USB Streaming)
0x01	bAssocTerminal
0x03	bSourceID
0x00	iTerminal
Hex dump: 
0x09 0x24 0x03 0x02 0x01 0x01 0x01 0x03 0x00 

AC Feature Unit Descriptor:
------------------------------
0x08	bLength
0x24	bDescriptorType
0x06	bDescriptorSubtype
0x03	bUnitID
0x01	bSourceID
0x01	bControlSize
bmaControls: 
 0x43	Channel(0) - Mute / Volume / Automatic Gain
0x00	iFeature

Hex dump: 
0x08 0x24 0x06 0x03 0x01 0x01 0x43 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x00 0x00 0x01 0x02 0x00 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x01	bAlternateSetting
0x01	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x01 0x01 0x01 0x02 0x00 0x00 

AS Interface Descriptor:
------------------------------
0x07	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x02	bTerminalLink
0x01	bDelay
0x0001	wFormatTag   (PCM)
Hex dump: 
0x07 0x24 0x01 0x02 0x01 0x01 0x00 

AS Format Type 1 Descriptor:
------------------------------
0x17	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bFormatType   (FORMAT_TYPE_1)
0x01	bNrChannels   (1 channels)
0x02	bSubframeSize
0x10	bBitResolution   (16 bits per sample)
0x05	bSamFreqType   (Discrete sampling frequencies)
0x001F40 	tSamFreq(1)   (8000 Hz)
0x002B11 	tSamFreq(2)   (11025 Hz)
0x005622 	tSamFreq(3)   (22050 Hz)
0x00AC44 	tSamFreq(4)   (44100 Hz)
0x00BB80 	tSamFreq(5)   (48000 Hz)
Hex dump: 
0x17 0x24 0x02 0x01 0x01 0x02 0x10 0x05 0x40 0x1F 
0x00 0x11 0x2B 0x00 0x22 0x56 0x00 0x44 0xAC 0x00 
0x80 0xBB 0x00 

Endpoint Descriptor (Audio/MIDI 1.0):
------------------------------
0x07	bLength
0x05	bDescriptorType
*** ERROR: Invalid descriptor length 0x07 for Audio/MIDI 1.0 endpoint (9 bytes expected)
Hex dump: 
0x07 0x05 0x81 0x01 0x64 0x00 0x01 

AS Isochronous Data Endpoint Descriptor:
------------------------------
0x07	bLength
0x25	bDescriptorType
0x01	bDescriptorSubtype
0x01	bmAttributes   (Sampling Frequency)
0x00	bLockDelayUnits   (undefined)
0x0000	wLockDelay
Hex dump: 
0x07 0x25 0x01 0x01 0x00 0x00 0x00 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  
Hex dump: 

0x01   0x0000  "AKM             "
Hex dump: 
0x22 0x03 0x41 0x00 0x4B 0x00 0x4D 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 

0x02   0x0000  "AK5370          "
Hex dump: 
0x22 0x03 0x41 0x00 0x4B 0x00 0x35 0x00 0x33 0x00 
0x37 0x00 0x30 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 0x20 0x00 
0x20 0x00 0x20 0x00 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x10, 0x01, 0x00, 0x00, 0x00, 0x08, 0x56, 0x05, 
0x01, 0x00, 0x01, 0x00, 0x01, 0x02, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x76, 0x00, 0x02, 0x01, 0x00, 0x80, 0x2D, 0x09, 
0x04, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x09, 0x24, 
0x01, 0x00, 0x01, 0x26, 0x00, 0x01, 0x01, 0x0C, 0x24, 0x02, 
0x01, 0x01, 0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x09, 
0x24, 0x03, 0x02, 0x01, 0x01, 0x01, 0x03, 0x00, 0x08, 0x24, 
0x06, 0x03, 0x01, 0x01, 0x43, 0x00, 0x09, 0x04, 0x01, 0x00, 
0x00, 0x01, 0x02, 0x00, 0x00, 0x09, 0x04, 0x01, 0x01, 0x01, 
0x01, 0x02, 0x00, 0x00, 0x07, 0x24, 0x01, 0x02, 0x01, 0x01, 
0x00, 0x17, 0x24, 0x02, 0x01, 0x01, 0x02, 0x10, 0x05, 0x40, 
0x1F, 0x00, 0x11, 0x2B, 0x00, 0x22, 0x56, 0x00, 0x44, 0xAC, 
0x00, 0x80, 0xBB, 0x00, 0x07, 0x05, 0x81, 0x01, 0x64, 0x00, 
0x01, 0x07, 0x25, 0x01, 0x01, 0x00, 0x00, 0x00

------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
AK5370           (VID=0x0556 PID=0x0001) Port: 10

Running on: Windows 10 or greater (Build Version 22623)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

**Comment by jackun** [comment]
Inb4 game just checks vid/pid, dump it as hex, easier to copy/paste. Iirc  tdd had the ability.

**Comment by seta-san** [comment]
Information for device Logitech USB Microphone (VID=0x046D PID=0x0A03):

Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x001B
Current configuration value: 0x01
Number of open pipes: 0

Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0200	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x046D	idVendor
0x0A03	idProduct
0x0102	bcdDevice
0x01	iManufacturer   "Logitech"
0x02	iProduct        "Logitech USB Microphone"
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x00 0x02 0x00 0x00 0x00 0x08 0x6D 0x04 
0x03 0x0A 0x02 0x01 0x01 0x02 0x00 0x01 

Configuration Descriptor:
------------------------------
0x09	bLength
0x02	bDescriptorType
0x0079	wTotalLength   (121 bytes)
0x02	bNumInterfaces
0x01	bConfigurationValue
0x03	iConfiguration   "G10 v2.0.0.0"
0x80	bmAttributes   (Bus-powered Device)
0x1E	bMaxPower      (60 mA)
Hex dump: 
0x09 0x02 0x79 0x00 0x02 0x01 0x03 0x80 0x1E 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x01	bInterfaceSubClass   (Audio Control Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x00 0x01 0x01 0x00 0x00 

AC Interface Header Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x0100	bcdADC
0x0027	wTotalLength   (39 bytes)
0x01	bInCollection
0x01	baInterfaceNr(1)
Hex dump: 
0x09 0x24 0x01 0x00 0x01 0x27 0x00 0x01 0x01 

AC Input Terminal Descriptor:
------------------------------
0x0C	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x0D	bTerminalID
0x0201	wTerminalType   (Microphone)
0x00	bAssocTerminal
0x01	bNrChannels   (1 channels)
0x0000	wChannelConfig
0x00	iChannelNames
0x00	iTerminal
Hex dump: 
0x0C 0x24 0x02 0x0D 0x01 0x02 0x00 0x01 0x00 0x00 
0x00 0x00 

AC Feature Unit Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x06	bDescriptorSubtype
0x02	bUnitID
0x0D	bSourceID
0x01	bControlSize
bmaControls: 
 0x03	Channel(0) - Mute / Volume
 0x00	Channel(1)
0x00	iFeature

Hex dump: 
0x09 0x24 0x06 0x02 0x0D 0x01 0x03 0x00 0x00 

AC Output Terminal Descriptor:
------------------------------
0x09	bLength
0x24	bDescriptorType
0x03	bDescriptorSubtype
0x0A	bTerminalID
0x0101	wTerminalType   (USB Streaming)
0x00	bAssocTerminal
0x02	bSourceID
0x00	iTerminal
Hex dump: 
0x09 0x24 0x03 0x0A 0x01 0x01 0x00 0x02 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x00	bAlternateSetting
0x00	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x00 0x00 0x01 0x02 0x00 0x00 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x01	bInterfaceNumber
0x01	bAlternateSetting
0x01	bNumEndPoints
0x01	bInterfaceClass      (Audio Device Class)
0x02	bInterfaceSubClass   (Audio Streaming Interface)
0x00	bInterfaceProtocol   (Audio Protocol undefined)
0x00	iInterface
Hex dump: 
0x09 0x04 0x01 0x01 0x01 0x01 0x02 0x00 0x00 

AS Interface Descriptor:
------------------------------
0x07	bLength
0x24	bDescriptorType
0x01	bDescriptorSubtype
0x0A	bTerminalLink
0x00	bDelay
0x0001	wFormatTag   (PCM)
Hex dump: 
0x07 0x24 0x01 0x0A 0x00 0x01 0x00 

AS Format Type 1 Descriptor:
------------------------------
0x17	bLength
0x24	bDescriptorType
0x02	bDescriptorSubtype
0x01	bFormatType   (FORMAT_TYPE_1)
0x01	bNrChannels   (1 channels)
0x02	bSubframeSize
0x10	bBitResolution   (16 bits per sample)
0x05	bSamFreqType   (Discrete sampling frequencies)
0x001F40 	tSamFreq(1)   (8000 Hz)
0x002B11 	tSamFreq(2)   (11025 Hz)
0x005622 	tSamFreq(3)   (22050 Hz)
0x00AC44 	tSamFreq(4)   (44100 Hz)
0x00BB80 	tSamFreq(5)   (48000 Hz)
Hex dump: 
0x17 0x24 0x02 0x01 0x01 0x02 0x10 0x05 0x40 0x1F 
0x00 0x11 0x2B 0x00 0x22 0x56 0x00 0x44 0xAC 0x00 
0x80 0xBB 0x00 

Endpoint Descriptor (Audio/MIDI 1.0):
------------------------------
0x09	bLength
0x05	bDescriptorType
0x84	bEndpointAddress  (IN endpoint 4)
0x0D	bmAttributes      (Transfer: Isochronous / Synch: Synchronous / Usage: Data)
0x0060	wMaxPacketSize    (1 x 96 bytes)
0x01	bInterval         (1 frames)
0x00	bRefresh
0x00	bSynchAddress
Hex dump: 
0x09 0x05 0x84 0x0D 0x60 0x00 0x01 0x00 0x00 

AS Isochronous Data Endpoint Descriptor:
------------------------------
0x07	bLength
0x25	bDescriptorType
0x01	bDescriptorSubtype
0x01	bmAttributes   (Sampling Frequency)
0x02	bLockDelayUnits   (decoded PCM samples)
0x0001	wLockDelay
Hex dump: 
0x07 0x25 0x01 0x01 0x02 0x01 0x00 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
Hex dump: 
0x04 0x03 0x09 0x04 

0x01   0x0409  "Logitech"
Hex dump: 
0x12 0x03 0x4C 0x00 0x6F 0x00 0x67 0x00 0x69 0x00 
0x74 0x00 0x65 0x00 0x63 0x00 0x68 0x00 

0x02   0x0409  "Logitech USB Microphone"
Hex dump: 
0x30 0x03 0x4C 0x00 0x6F 0x00 0x67 0x00 0x69 0x00 
0x74 0x00 0x65 0x00 0x63 0x00 0x68 0x00 0x20 0x00 
0x55 0x00 0x53 0x00 0x42 0x00 0x20 0x00 0x4D 0x00 
0x69 0x00 0x63 0x00 0x72 0x00 0x6F 0x00 0x70 0x00 
0x68 0x00 0x6F 0x00 0x6E 0x00 0x65 0x00 

0x03   0x0409  "G10 v2.0.0.0"
Hex dump: 
0x1A 0x03 0x47 0x00 0x31 0x00 0x30 0x00 0x20 0x00 
0x76 0x00 0x32 0x00 0x2E 0x00 0x30 0x00 0x2E 0x00 
0x30 0x00 0x2E 0x00 0x30 0x00 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x08, 0x6D, 0x04, 
0x03, 0x0A, 0x02, 0x01, 0x01, 0x02, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x79, 0x00, 0x02, 0x01, 0x03, 0x80, 0x1E, 0x09, 
0x04, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x09, 0x24, 
0x01, 0x00, 0x01, 0x27, 0x00, 0x01, 0x01, 0x0C, 0x24, 0x02, 
0x0D, 0x01, 0x02, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x09, 
0x24, 0x06, 0x02, 0x0D, 0x01, 0x03, 0x00, 0x00, 0x09, 0x24, 
0x03, 0x0A, 0x01, 0x01, 0x00, 0x02, 0x00, 0x09, 0x04, 0x01, 
0x00, 0x00, 0x01, 0x02, 0x00, 0x00, 0x09, 0x04, 0x01, 0x01, 
0x01, 0x01, 0x02, 0x00, 0x00, 0x07, 0x24, 0x01, 0x0A, 0x00, 
0x01, 0x00, 0x17, 0x24, 0x02, 0x01, 0x01, 0x02, 0x10, 0x05, 
0x40, 0x1F, 0x00, 0x11, 0x2B, 0x00, 0x22, 0x56, 0x00, 0x44, 
0xAC, 0x00, 0x80, 0xBB, 0x00, 0x09, 0x05, 0x84, 0x0D, 0x60, 
0x00, 0x01, 0x00, 0x00, 0x07, 0x25, 0x01, 0x01, 0x02, 0x01, 
0x00


------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
Logitech USB Microphone (VID=0x046D PID=0x0A03) Port: 3

Running on: Windows 10 or greater (Build Version 19042)

Brought to you by TDD v2.15.0, Jun  8 2020, 17:18:07

**Comment by seta-san** [comment]
the last time this was worked on was https://github.com/PCSX2/pcsx2/tree/usb-subtypes back in febuary 2021

**Comment by MMatiasMG** [comment]
:(

**Comment by Florin9doi** [comment]
Please add a list of compatible titles

**Comment by seta-san** [comment]
[Karaoke Revolution Special Limited Pack Blue Edition](https://wiki.pcsx2.net/Karaoke_Revolution_Special_Limited_Pack_Blue_Edition)
[Karaoke Revolution Special Limited Pack Green Edition](https://wiki.pcsx2.net/Karaoke_Revolution_Special_Limited_Pack_Green_Edition)
[Karaoke Revolution Special Limited Pack Red Edition](https://wiki.pcsx2.net/Karaoke_Revolution_Special_Limited_Pack_Red_Edition)
[Karaoke Revolution: Anime Song Collection](https://wiki.pcsx2.net/Karaoke_Revolution:_Anime_Song_Collection)
[Karaoke Revolution: Dreams & Memories](https://wiki.pcsx2.net/Karaoke_Revolution:_Dreams_%26_Memories)
[Karaoke Revolution: J-Pop Best Vol. 1](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._1)
[Karaoke Revolution: J-Pop Best Vol. 2](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._2)
[Karaoke Revolution: J-Pop Best Vol. 3](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._3)
[Karaoke Revolution: J-Pop Best Vol. 4](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._4)
[Karaoke Revolution: J-Pop Best Vol. 5](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._5)
[Karaoke Revolution: J-Pop Best Vol. 6](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._6)
[Karaoke Revolution: J-Pop Best Vol. 7](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._7)
[Karaoke Revolution: J-Pop Best Vol. 8](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._8)
[Karaoke Revolution: J-Pop Best Vol. 9](https://wiki.pcsx2.net/Karaoke_Revolution:_J-Pop_Best_Vol._9)
[Karaoke Revolution: Kazoku Idol Sengen](https://wiki.pcsx2.net/Karaoke_Revolution:_Kazoku_Idol_Sengen)
[Karaoke Revolution: Kissing Selection](https://wiki.pcsx2.net/Karaoke_Revolution:_Kissing_Selection)
[Karaoke Revolution: Love & Ballad](https://wiki.pcsx2.net/Karaoke_Revolution:_Love_%26_Ballad)
[Karaoke Revolution: Night Selection 2003](https://wiki.pcsx2.net/Karaoke_Revolution:_Night_Selection_2003)
[Karaoke Revolution: Snow & Party](https://wiki.pcsx2.net/Karaoke_Revolution:_Snow_%26_Party)

**Comment by Florin9doi** [comment]
Jaleco Mic Converter (JALE-20003) uses the same audio controller. The following games should works as well:
- https://wiki.pcsx2.net/Super_Micchan
- https://wiki.pcsx2.net/Dream_Audition
- https://wiki.pcsx2.net/Dream_Audition_2
- https://wiki.pcsx2.net/Dream_Audition_3
- https://wiki.pcsx2.net/Dream_Audition_Super_Hit_Disc_1
- https://wiki.pcsx2.net/Dream_Audition_Super_Hit_Disc_2
![image](https://github.com/user-attachments/assets/00cf9639-7dbd-43db-a7b1-0e93c29abec8)

**Comment by Florin9doi** [comment]
Jaleco Mic Converter (JALE-20003) uses the same audio controller. The following games should works as well:
- https://wiki.pcsx2.net/Dream_Audition
- https://wiki.pcsx2.net/Dream_Audition_2
- https://wiki.pcsx2.net/Dream_Audition_3
- https://wiki.pcsx2.net/Dream_Audition_Super_Hit_Disc_1
- https://wiki.pcsx2.net/Dream_Audition_Super_Hit_Disc_2
- https://wiki.pcsx2.net/Super_Micchan
![image](https://github.com/user-attachments/assets/03f1fd41-91ec-440d-bdf4-fc6ee1f80db9)

**Comment by seta-san** [comment]
i don't have any of those games. i'll order one or two to test. the microphone looks nothing like the on-say though.

**Comment by Florin9doi** [comment]
The same audio controller is also used by [MTV Music Generator 2](https://wiki.pcsx2.net/MTV_Music_Generator_2) Sampler Kit, but this game accepts any microphone.
![image](https://github.com/user-attachments/assets/e9a9c0e2-077c-477a-bb8c-146e3b845085)
