### ISSUE TITLE
[BUG] The King of Fighter nests collection: Broken sound effects/music.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4174]
**Describe the bug**
In the game "King of fighter nests collection", the sound is massively distored compared to what it should be.

https://user-images.githubusercontent.com/26351275/105613292-e7905800-5dc1-11eb-8f06-fce1bb56ebaa.mp4

**To Reproduce**
Load King of Fighter 2000 in the collection and listen to the music.

**Expected behavior**
The game should have proper sound effects and music like on a real console.

**Emulation Settings**
Everything default.

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-pr[4171]
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Dumps**
https://drive.google.com/file/d/10V34mENfWm-gppNJ_oP96r6oqTk0g2Ha/view?usp=sharing

**Comment by Silanda** [comment]
It sounds rather thin compared to the Neo Geo version IMO, but it doesn't sound like that on my system. There's no crackling distortion, and the sound effects are fine. This is on a current 32-bit build.

**Comment by Silanda** [comment]
Ah. PR #4171. Didn't notice that.

**Comment by refractionpcsx2** [comment]
@Silanda I don't believe this is new to the PR, maybe @atomic83GitHub could clarify, but pretty sure he sad it was an existing problem for him.

**Comment by atomic83GitHub** [comment]
This effectively is a long standing bug which never got fixed. The standalone KOF 2000 game works fine but it's the dreamcast version on the collection which does that.

**Comment by refractionpcsx2** [comment]
Tried the dump on my end (couldn't load the savestate) and it worked absolutely fine, sounded normal as I think it can be, didn't sound anywhere near as horrible as your sample, or as low quality.

**Comment by refractionpcsx2** [comment]
I won't label it cannot reproduce actually, because the audio quality is still pretty terrible.

**Comment by atomic83GitHub** [comment]
It's a bit of a placebo for that issue unfortunately.
