### ISSUE TITLE
[BUG] [GTK3] [Linux] can't select GS plugin (libs) in settings

### ISSUE THREAD

**Issue by SupervisedThinking** [PCSX2/pcsx2#4177]
First thing first: I'm building PCSX2 from scratch with this package https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/pcsx2/package.mk & use the LibreELEC toolchain.

Toolkits:
GTK3 3.24.24 https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/toolkit/gtk/gtk3-system/package.mk
wxWidgets 3.0.5.1 https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/toolkit/wxWidgets/package.mk

I've read that GTK3 support is the default but still a bit in experimental stage? Also the preferred wxWidgets version is the dated `v3.0.3`? Are there any special build flags & requirements for wx & gtk3 or pcsx2 which I've overlooked?

**Describe the bug**
I can't select the GS plugins in settings although the path to the libs is correct:

```
phoenix:/usr/lib/PCSX2 # ls -l
total 5148
-rwxr-xr-x    1 root     root       1718680 Jan 24 12:07 libGSdx-AVX2.so
-rwxr-xr-x    1 root     root       1726872 Jan 24 12:07 libGSdx-SSE4.so
-rwxr-xr-x    1 root     root       1718680 Jan 24 12:07 libGSdx.so
-rwxr-xr-x    1 root     root        106376 Jan 24 12:07 libGSnull.so

```
When I manually set the path in PCSX2_ui.ini
```
[Filenames]
GS=/usr/lib/PCSX2/libGSdx-AVX2.so
```
it loads fine & you can also configure GS in PCSX2. Also the bios selector works fine & lists all bios files.

**Expected behavior**
one of the GS libs should be selectable

**GS Window Screenshots**
https://i.imgur.com/HUwmVrO.png
https://i.imgur.com/zfI6nkZ.png

**System Info (please complete the following information):**
 - PCSX2 Revision: https://github.com/PCSX2/pcsx2/commit/2ffc6b3acddc9500106da73175a2604f98476493
 - OS: https://github.com/SupervisedThinking/LibreELEC-RR/tree/master-rr
 - CPU: i3-6100
 - GPU: IGP

**Logs and Dumps**
pcsx2 log
https://pastebin.com/hjnFU9BW

buildconfig log
https://pastebin.com/2pUN79kT

**Comment by SupervisedThinking** [comment]
The problem persists when I've switched to GTK2 which is broken after this commit btw. `gtk_builder_add_from_resource` & `gtk_builder_add_callback_symbols` was not declared
https://github.com/PCSX2/pcsx2/commit/dc3bd53f7be0c7232fb7abd8e02e9653baccba8a#diff-2098ec81393fa98b4c0c6fd087a5bafadaa6176eba4af35b638e6994090925bcR192-R196

**Comment by tadanokojin** [comment]
Does PCSX2 have execute permissions for `/usr/lib/PCSX2`? You showed the permissions of it's contents, but not the directory itself.

**Comment by SupervisedThinking** [comment]
I guess this should be fine, the libs were missing the executable bit after build bit I've already fixed that
```
phoenix:/usr/lib # ls -l
total 353397
drwxrwxr-x    2 root     root            79 Jan 26 02:05 PCSX2
```

**Comment by SupervisedThinking** [comment]
Well anyone got a clue if this strace output is correct?
```
stat("/usr/lib/PCSX2", {st_mode=S_IFDIR|0775, st_size=79, ...}) = 0
openat(AT_FDCWD, "/usr/lib/PCSX2", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 13
fstat(13, {st_mode=S_IFDIR|0775, st_size=79, ...}) = 0
lseek(13, 0, SEEK_SET)                  = 0
getdents64(13, 0xe0d3030 /* 5 entries */, 32768) = 160
stat("/usr/lib/PCSX2/libGSdx-AVX2.so", {st_mode=S_IFREG|0755, st_size=1718680, ...}) = 0
stat("/usr/lib/PCSX2/libGSdx-SSE4.so", {st_mode=S_IFREG|0755, st_size=1726872, ...}) = 0
stat("/usr/lib/PCSX2/libGSdx.so", {st_mode=S_IFREG|0755, st_size=1718680, ...}) = 0
getdents64(13, 0xe0d3030 /* 0 entries */, 32768) = 0
close(13)                               = 0
```

**Comment by lightningterror** [comment]
GS plugin has been merged in to core so this shouldn't be an issue anymore.
