### ISSUE TITLE
[BUG - BIOS] Audio CDs doesn't work anymore.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4178]
**Describe the bug**
Audio CDs won't play any music anymore in the BIOS.

Note: Now when playing a audio CD, the PCSX2 console spams: NCMD Unknown 7

**To Reproduce**
Load the BIOS with a standard audio CD in the virtual tray.

**Expected behavior**
The various tracks on the disc should play fine.

**Emulation Settings**
Everything default.

**Regression pull request:**
https://github.com/PCSX2/pcsx2/pull/1583

**System Info**
PCSX2 Revision: pcsx2-v1.7.0-dev-pr[4171]
OS: Windows 10
CPU: I9 9900k
GPU: RTX 3070

**Comment by turtleli** [comment]
That regression pull request isn't correct.

> Note: Now when playing a audio CD, the PCSX2 console spams: NCMD Unknown 7

#3899 is responsible for that, re-adding the large section of deleted code makes it play though the playback is pretty bugged - it repeats itself a lot and the time increments slowly. So there is another regression somewhere.

**Comment by turtleli** [comment]
The faulty playback was caused by #3877.

**Comment by maxdlpee** [comment]
I don't think this is really of much priority tho, given that you can use your PC to play those Audio CDs, and not bother with PCSX2 at all.

**Comment by refractionpcsx2** [comment]
> The faulty playback was caused by #3877.

wait, what? how?

**Comment by turtleli** [comment]
I think there's a misunderstanding. #3899 made audio unplayable, whereas #3877 made audio sound buggy because the CD read speed is too slow.

**Comment by refractionpcsx2** [comment]
I see, I'm not sure how it's too slow, unless it's not CAV when it's doing CD Audio reads, which makes sense I suppose.

**Comment by turtleli** [comment]
Here's some amusing playback with the deleted code put back in.
"10s"

https://user-images.githubusercontent.com/10976277/120988512-8bc5da80-c776-11eb-8211-0fd99ad1de08.mp4

10s with CD speed change reverted (it's not perfect, but yeah)

https://user-images.githubusercontent.com/10976277/120988682-b2841100-c776-11eb-894d-e2cca9a648ff.mp4

**Comment by seta-san** [comment]
If this is a cd read speed issue couldn't this bug help dial into the ps2s exact read speed and maybe help fix other games with cdvd issues?

**Comment by refractionpcsx2** [comment]
I suspect audio cd's velocity changes so the speed matches wherever on the cd you are, it's only PS2 games where it uses CAV.

**Comment by gilderoylockhart01** [comment]
Thanks to the various CDVD timing changes, this is not an issue anymore, the only remaining gremlin is this log: 
![image](https://user-images.githubusercontent.com/90222976/141694137-f0ff261a-6f91-4d7c-b8a2-f8cf3ae7287d.png)

**Comment by refractionpcsx2** [comment]
Apparently 0x2009 is the mode for the "where" registers 0x200c-0x200e (sec/min/hrs?)

0 = audio cd
1 = cd/dvd or something
2 = dvd

The reason it doesn't matter that we don't emulate it currently is because we're basically in permanent audio cd mode.
