### ISSUE TITLE
[BUG] Cartoon Network Racing: Improper character shading in HW renderers

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#4181]
**Describe the bug**
In all HW renderers, the characters are missing dark areas that make them look less flat

**To Reproduce**
Boot game, start race

**Expected behavior**
Characters should have some dark shaded areas as seen in the SW renderer

**GS Settings**
Defaults

**Emulation Settings**
Defaults

**GS Window Screenshots**
SW:
![cn_racing](https://user-images.githubusercontent.com/16314399/105764879-9305ed80-5f25-11eb-8c16-cc5be2e0ff74.png)

HW:
![image](https://user-images.githubusercontent.com/16314399/105764919-a022dc80-5f25-11eb-9979-3f16c0bc8b1c.png)

**System Info (please complete the following information):**
PCSX2 1.7-910
Windows 10 Home 64-bit
i5-6600k
GTX 1070

**Logs and Dumps**
GSDump:
[cn_racing.zip](https://github.com/PCSX2/pcsx2/files/5869618/cn_racing.zip)

**Comment by prafullpcsx2** [comment]
Bug doesn't seem to happen with blending accuracy none.

**Comment by tadanokojin** [comment]
It's wrong with blending accuracy set to none.
The game needs per pixel blending.
