### ISSUE TITLE
[BUG] Vsync setting tethered to Preset, but also not disabled.

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#4183]
**Describe the bug**
Enabling a preset forces Vsync to Disabled, indicating that Vsync is among the settings which are flushed whenever a preset is enabled. However, the control in the UI is never disabled so it can still be modified. Restarting the emulator, enabling or disabling presets, or changing the preset will then wipe the Vsync setting back to Disabled regardless of what it is set to.

**To Reproduce**
Set Vsync to any mode other than Disabled, then enable, disable or change presets. Or, if presets are enabled, close and open the program. Vsync will be flushed back to Disabled.

**Expected behavior**
Either the Vsync UI control needs to be disabled when presets are active, or Vsync needs to be removed from the group of settings flushed by presets. Option 2 seems like the more sensible, as presets mainly serve to flush FPU modes back to the default safe options and otherwise only manipulate speedhacks.

**GS Settings**
Arbitrary to the issue, UI only.

**Emulation Settings**
Arbitrary to the issue, UI only. Preset and Vsync options as described above.

**GS Window Screenshots**
Nothing to screenshot.

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-910
 - OS: Windows 10
 - CPU: i7-8700K
 - GPU: GTX 1070 Ti

**Logs and Dumps**
No logs to show, UI only.

**Comment by lightningterror** [comment]
I agree, it should be excluded from the Preset slider.
