### ISSUE TITLE
[BUG] Ratchet and Clank 1 and 2

### ISSUE THREAD

**Issue by IGCIT** [PCSX2/pcsx2#4189]
**Describe the bug**

**Ratchet and clank 2**

* Performance issue in Tabora

no matter the hardware, that specific point causes a major slowdown, from full speed to ~30
move away from that building and pcsx2 will run full speed again
tested on multiple pcs with different hw
![scr](https://user-images.githubusercontent.com/76787191/106266308-8e448080-6228-11eb-8c08-83a85475ddac.png)

* Softlock in Maktar Nebula mission "Destroy the signal transponders"

when you complete this mission, pcsx2 will show a black screen with the game running in background

you must restart pcsx2 but this game has no auto-save feature so your progress is lost.

this is a required mission, you can unlock next planet but you cant unlock the next one after that, so you cant progress further

this softlock happens with OGL, DX11 and SW

**Ratchet and clank 1**

* cpu usage in Veldin planet is insane, i dont know if this is expected :\ , and low fps ofc
i didnt test other planets

**GS Settings**

**Emulation Settings**
DX11 or OGL or SW (tested all of them)
safe preset
accurate date
gpu palette conversion
hw hacks: preload frame data

**System Info (please complete the following information):**
 - PCSX2 Revision: v1.7.0-dev-923-g541dfdfc7 (https://buildbot.orphis.net/pcsx2/)
 - OS: windows 10 20h2
 - CPU: i5-1035g7, i7-7700HQ, a third one, i7, that i dont remember
 - GPU: iris plus, nvidia gtx 1050 ti, nvidia gtx 970m

**Comment by refractionpcsx2** [comment]
What versions of PCSX2 did you try? Can you please fill out the template.

**Comment by IGCIT** [comment]
updated
sorry i first opened the issue and then logged in to github so i didnt show me the templates

**Comment by refractionpcsx2** [comment]
Okay thanks, we'll focus on the black screen issue because performance issues aren't really bugs, the game is very demanding and the hardware you posted isn't the most powerful out there, so i would expect some lagging, but the black screen should be an issue.

Have you tried enabling the EE Timing Hack under Config->Emulation Settings->Gamefixes?

**Comment by IGCIT** [comment]
> Have you tried enabling the EE Timing Hack under Config->Emulation Settings->Gamefixes?

no

**Comment by refractionpcsx2** [comment]
Can you? :P

**Comment by IGCIT** [comment]
timing hack fixed the lock

**Comment by refractionpcsx2** [comment]
Cool, probably not a lot we can do about that then, I'll put forward adding the timing fix to the game database in future
