### ISSUE TITLE
[BUG] Ghost effect on moving models in cutscenes.

### ISSUE THREAD

**Issue by Softernet** [PCSX2/pcsx2#4194]
**Describe the bug**
Ghost effect on moving models in cutscenes (is not present during gameplay). 
![gsdx_20210130172344](https://user-images.githubusercontent.com/31589009/106360482-4bb29f00-6321-11eb-9cdb-7647101a898c.png)
![gsdx_20210130172417](https://user-images.githubusercontent.com/31589009/106360484-4ce3cc00-6321-11eb-9407-fdaed03e9992.png)

**To Reproduce**
Just watch the cutscenes. 

**Expected behavior**
Models witout ghost effect. 

**GS Settings**
None 

**Emulation Settings**
![pcsx2_CoreSettings_EE-IOP](https://user-images.githubusercontent.com/31589009/106360334-941d8d00-6320-11eb-8e1f-3d1fd6c5f5be.png)
![pcsx2_CoreSettings_Game Fixes](https://user-images.githubusercontent.com/31589009/106360336-94b62380-6320-11eb-9d20-57273c9d41f5.png)
![pcsx2_CoreSettings_GS Window](https://user-images.githubusercontent.com/31589009/106360337-954eba00-6320-11eb-8473-2ccbf027af32.png)
![pcsx2_CoreSettings_GS](https://user-images.githubusercontent.com/31589009/106360338-954eba00-6320-11eb-8da0-85c3838ea9c5.png)
![pcsx2_CoreSettings_Speedhacks](https://user-images.githubusercontent.com/31589009/106360339-954eba00-6320-11eb-985e-69965c6503bc.png)
![pcsx2_CoreSettings_VUs](https://user-images.githubusercontent.com/31589009/106360340-95e75080-6320-11eb-87e9-829146f28c4c.png)

**GS Window Screenshots**
![Снимок экрана 2021-01-30 172034](https://user-images.githubusercontent.com/31589009/106360369-b7483c80-6320-11eb-9495-f7fb982a182e.png)

**System Info:**
 - PCSX2 Revision: v1.7.0-r925 
 - OS: Windows 10 
 - CPU: i5-4690K 
 - GPU: GTX660 

**Logs and Dumps**
[snaps.zip](https://github.com/PCSX2/pcsx2/files/5898234/snaps.zip)

**Comment by tadanokojin** [comment]
Did you try checking if the issue is present on real hw?
Because it looks like a standard motion blur typical of games of this era.

Here's the same scene from a review from 2012
![006552](https://user-images.githubusercontent.com/26046960/106361205-b399c300-62ea-11eb-9b8a-45678e3b422c.png)

**Comment by Softernet** [comment]
> Did you try checking if the issue is present on real hw?
> Because it looks like a standard motion blur typical of games of this era.
> 
> Here's the same scene from a review from 2012
> ![006552](https://user-images.githubusercontent.com/26046960/106361205-b399c300-62ea-11eb-9b8a-45678e3b422c.png)

No, I have not tried testing this problem on real hardware, because I have no such option. If it is confirmed that this is a normal effect and not an emulation error, then close the problem.

**Comment by refractionpcsx2** [comment]
If you don't own a PS2 we can't help you.
