### ISSUE TITLE
[BUG] Sphinx and the Cursed Mummy sound distortion

### ISSUE THREAD

**Issue by HelicopterP** [PCSX2/pcsx2#4197]
**Describe the bug**
Sound during the intro sequence for Sphinx and the Cursed Mummy is distorted and clicky from time to time. The distortion is in higher frequencies and quiet, so headphones are recomended, but the bug is audible on external speakers too.  The distortion appears during random moments of intro sequence on each run, but it is always there.

**To Reproduce**
Start a new game, watch an intro sequence and listen.

**Expected behavior**
Clean sound without any distortion.

**GS Settings**
Doesn't matter.

**Emulation Settings**
Defualt settings with only Instant VU hack enabled. Without it I can't get fullspeed emulation, which means that results with all speedhacks disabled can't be trusted in this case.
I tried Timestretch and no synchronization in audio settings - the result is the same. I also used Catmull interpolation.

**System Info (please complete the following information):**
 - PCSX2 Revision: latest build from buildbot.
 - OS: Windows 10 64 bit
 - CPU: i7 8700
 - GPU: GTX 1070

**Logs and Dumps**
Blockdump https://mega.nz/file/E9B1yAyC#K0V6_4ADO0fZczyc8ZMHQWlYfH1jZh_aNSbvM6V92gU

**Comment by refractionpcsx2** [comment]
Could you prove an audio sample from your PC too please? so we have something to compare to

**Comment by HelicopterP** [comment]
[Sphinx.zip](https://github.com/PCSX2/pcsx2/files/5900021/Sphinx.zip)
Sure, here is a recording from audacity. In this session the distortion is best heard during the end of the file (after the sound of magic but before the lava fountain sound). Sorry, I wish i could be more specific, but I'm a total noob when it comes to working with audio.

**Comment by refractionpcsx2** [comment]
yeah I can hear them, they all seem to be in the right channel, from what I can tell

**Comment by refractionpcsx2** [comment]
Hmm, i thought the issue was after you started a new game? your blockdump runs out by then

**Comment by HelicopterP** [comment]
The issue is during intro sequence which begins after you select a new game. The gameplay itself is fine as far as I can see.
My blockdump definitely have the intro sequence.

**Comment by refractionpcsx2** [comment]
Well I clicked new game, then chose to continue without saving, it loaded a bit then it ran out of blocks and crashed at that point.

**Comment by HelicopterP** [comment]
Hm, I tried it with saving for the first time and overwriting existing save. Maybe it doesn't work without saving...

**Comment by refractionpcsx2** [comment]
It's okay, our tester made a new blockdump which is fine

**Comment by HelicopterP** [comment]
Eh, i screwed up, and thought that I was testing my dump, while in reality the game was runing from ISO. Stupid me.

It s good that you have a good blockdump now

**Comment by refractionpcsx2** [comment]
Okay I've done some testing and the game seems to be sensitive to CDVD timings, though I'm not 100% sure why or by how much.  I can make it sound much better by speeding up seek times, but this breaks Shadowman, so I'm reluctant to that (plus I'm basically hacking it).

So I'm going to leave this for now and maybe revisit it at a later date.

**Comment by HelicopterP** [comment]
Hm, a lot of games have short bursts of distorted sound while going to a loading screen or something similar. From a top of my head Silent Hill 4 does it, maybe SH2 (need to check this) too... This issue is very subtle and kind of fleeting - some times its on one loading screen, the other time it's on the other. You can't really hear it on speakers too well though, maybe in a completely soundproof room...

**Comment by kenshen112** [comment]
Where does Silent Hill 4 do it?

**Comment by refractionpcsx2** [comment]
SH2 is also very sensitive to CDVD timings, though I've never noticed weird noises.

**Comment by HelicopterP** [comment]
Well, I never reported the issue properly, because it is so fleeting. I wasn't even sure that my headphones or motherboard audio were not causing it.
SH4 does it for sure - just walk into another room, trigger a cinematic, etc. and listen closely during a screen blackout (loading). Some times there is a very short static noise, some times everything is fine. But sooner or later it will show up.
I think SH2 is the same. Don't quote me on that though. I haven't played it in a while, but i remember the same very short sound distortions during loadings - i.e. just at the moment when a black screen with foot marks appear or when triggering a FMV.
The again, according to this https://www.rtings.com/headphones/reviews/superlux/hd-681 my headphones have an exaggerated treble range, so maybe this is why I can hear the distortion very clearly. I am also very sensitive to higher frequencies in general.

**Comment by refractionpcsx2** [comment]
[pcsx2-spu2cache.zip](https://github.com/PCSX2/pcsx2/files/5917798/pcsx2-spu2cache.zip)

@HelicopterP can you give this build a go? I think it completely solves Sphinx, not sure if it'll help SH4 or not, SH2 seems okay but then I didn't really notice it before.

**Comment by HelicopterP** [comment]
Great job! Not only Sphinx is fixed but so are remaining blips in Vexx! As far as I can tell these two games are perfect now.

I think there is something not right about SH2... Kinda... I'm not sure... SH4 though definitely has some distorted sound. I think if there is really something wrong with SH2 it's the same thing that is happenning with SH4. SH4 is easilly reproduceable so I'll open a new issue for it.

**Comment by refractionpcsx2** [comment]
oh cool, at least I can mark this as fixed :) Thanks for testing!
