### ISSUE TITLE
[BUG] Silent Hill 4 - sound distortion

### ISSUE THREAD

**Issue by HelicopterP** [PCSX2/pcsx2#4204]
**Describe the bug**
Silent Hill 4 has distorted sound when a player presses start to skip a FMVs or in-engine cutscenes. It manifests itself as a short barelly distinguishable static noise. This static can also be heard at various other points in the game, but skipping a cutscene is the easiest way to trigger it.

**To Reproduce**
Start the game and skip some cutscenes or FMVs. As always headphones are recomended but you can hear a distorion on external speakers too.

**Expected behavior**
Clear sound

**Emulation Settings**
All speedhacks disabled with the exception of instant VU.

**System Info (please complete the following information):**
 - PCSX2 Revision: any build including latest master
 - OS: Windows 10 64bt
 - CPU: i7 8700
 - GPU: GTX 1070

**Logs and Dumps**
Here is a block dump and a WAV recording from my PC. I tried to capture a bit more of FMVs but you are supposed to skip them. The distortion is best heard at 39 second and 1 minute and 5 second of my adio recording.
https://mega.nz/file/whwESCzS#6_D23_SkTCuy8pLkx2PN0ZizYK6I6VRNT--oLp_ph8k

**Comment by refractionpcsx2** [comment]
Is there any chance you can get an audio capture from the actual PS2? I checked the PS4 (via youtube) and it does it on there too.  The game doesn't adjust audio or anything on the SPU's it is all done through streamed audio, so either something is going on in the core or the game just *does* that.

**Comment by refractionpcsx2** [comment]
Just to explain it further from an SPU2 perspective.

The game sends the audio through DMA7 in an "AutoDMA" configuration, this means the audio is already in PCM format and is streamed to a "Sound Input" area of memory which is read in a buffered fashion and output directly to your speakers, the only modification being the "input volume" gets set to the data once the audio is read.

In these videos, no volume is changed and the audio continues to stream, the SPU2 does absolutely nothing with the data, so the volume is adjusted artificially by the IOP as the audio fades out.

**Comment by HelicopterP** [comment]
I'll try to do it in the evening, but I fear that recording quality will be far from perfect as the only way to record it for me is through motherboard audio. I tried this game recently on a real PS2 and didn't hear discribed distortion, but then again - noise floor in my setup is pretty high.

I will also connect a PS2 to an AV-reciever via optical cable and try to listen closely. There is no way for me to record that, but at least it will be a definite answer.

I would add that PS2 emulation on PS5 is awful. Somehow the PS5 version of emulator is worse than a PS3 version and also worse than PCSX2 aswell.

**Comment by refractionpcsx2** [comment]
I assume you mean the PS4? :P It's just interesting how it has the same problem. The reason I asked for a PS2 recording is because at normal volumes, you can't hear that distortion at all, I had to turn my volume up to an uncomfortable level to hear the crackling/distortion, so I'm just wondering if it's actually already there, just not very audible at sensible volumes.

Thank you for your efforts btw, they are appreciated.

**Comment by HelicopterP** [comment]
Yeah, I ment PS4, sure.
My test with AV receiver and a real PS2 showed that this game indeed has distorted sound when skipping cutscenes. Apparently it is quite and short enough to be unnoticed by most people.

So this issue is not a PCSX2 bug and should be closed. Sorry for false alarm.

**Comment by refractionpcsx2** [comment]
No problem, at least we know now :)
