### ISSUE TITLE
[Feature Request] Mac ARM64 native build

### ISSUE THREAD

**Issue by ibrahimk157** [PCSX2/pcsx2#4213]
**Description**

It would be lovely getting a Mac version of PCSX2 compiled for ARM64 (for the new M1 macs) so we can run it natively. 

**Reason**

Running it through emulation made the game extremely laggy no matter what settings i tried to change. Even running it on a Windows on ARM VM using Microsoft’s emulation yielded the same awful results.

**Examples**

No examples needed

**Comment by tellowkrinkle** [comment]
There have been plenty of issues on this, https://github.com/PCSX2/pcsx2/issues/2915 is one if you'd like to read it

Everyone knows that it's a wanted feature and I don't think anyone is going to forget it anytime soon, so there isn't much point in making issues for it
