### ISSUE TITLE
Add controller profile please

### ISSUE THREAD

**Issue by the-LONS-network** [PCSX2/pcsx2#4218]
Yeah thanks for the "auto" config... I was pulling my hair out at why it wasn't working.

I tried putting this in OnePAD2.ini but it didnt work.

`03000000c01100000355000011010000454421763,ACRUX USB GAME PAD,platform:Linux,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2, `

**Comment by RedDevilus** [comment]
https://github.com/gabomdq/SDL_GameControllerDB

Upstream repo + ,platform:Linux should be at the end of the string

**Comment by the-LONS-network** [comment]
.Its what came out of antimicroX so I'm not sure what happened

It says "`database.onepad: Joystick (ACRUX USB GAME PAD,GUID:03000000c01100000355000011010000) isn't yet supported by the SDL2 game controller API`" in the pcsx2 program log

**Comment by RedDevilus** [comment]
03000000c01100000355000011010000 has the correct size now
454421763 where did this come from though?

**Comment by the-LONS-network** [comment]
Its what I got from antimicroX [http://imgur.com/SSQENy4l.png](http://imgur.com/SSQENy4l.png)

**Comment by the-LONS-network** [comment]
Thank you for the fast response btw. its been much faster than other projects :-)
