### ISSUE TITLE
[Feature Request] store saves in PSU format with Folder memcards

### ISSUE THREAD

**Issue by eadmaster** [PCSX2/pcsx2#4221]
**Description**
Store saves in PSU format with Folder memcards instead of the current RAW format.

(Setup Folder memcards as usual.)

**Reason**
1. This should prevent filename encoding and other issues related to the host filesystem, possibly [improving compatibility of Folder memcards](https://github.com/PCSX2/pcsx2/issues/3918).
2. saves are easier to manage and backup as single files.
3. still possible to [restore the saves in this format with uLaunchELF](https://www.reddit.com/r/ps2/comments/4v92x8/freemcboot_backup_and_restore_game_saves/) without losing any fs metadata.
4. PSU saves can be imported directly with [mymc](https://github.com/thestr4ng3r/mymcplus) into memcard images, while RAW saves require an additional conversion step.

**Examples**
An [open source reader for PSU files is here](https://github.com/root670/PS2SaveUtility).

**Comment by refractionpcsx2** [comment]
In regards to 1, we already have a PR open to improve the compatibility as some games require the date/time of files to be correct.

Can you explain how this would be better? with raw memory cards it makes it easy to back up from your PS2 and copy them in to PCSX2 and visa versa, I'm not sure how using PSU format would make it any easier.

**Comment by eadmaster** [comment]
The PSU  format is [recommended over RAW/folder in uLaunchELF due to better compatibility](https://forums.pcsx2.net/Thread-raw-save-export?pid=181099#pid181099).
I guess the same applies here, as there may be some Japanese games using weird filenames that are not supported by the host filesystem and other edge-cases.

Since some users may still prefer the current RAW format for easier savegames hacking this could be implemented as a configurable option.



Having these infos stored in a PSU would

(I know some japanese games use filenames encoding that

**Comment by refractionpcsx2** [comment]
Yes what that post is referring to is the time/date information, which is what the above linked PR solves, as far as I'm aware there's no problems with the host file system beyond that.

**Comment by eadmaster** [comment]
Other problems may arise when you performs automatic backups via a cloud service or a storage media using a different filesystem.
