### ISSUE TITLE
[Feature Request] Add dualsense support

### ISSUE THREAD

**Issue by kytty00** [PCSX2/pcsx2#4224]
I tried to setup dualsense with no success. As I understand, PCSX2 does not support this controller, please add support, if possible

Sorry if it might not be a valid issue.

Edit: OS Windows

**Comment by MrCK1** [comment]
The DualSense can be used with PCSX2 through DS4Windows. Closing since this is more of a general support issue.

**Comment by kytty00** [comment]
Sorry, i was talking about native support.
RPCS3 added native dualsense support, it would be nice not to have to depend on a third party app to use dualsense with PCSX2.

https://github.com/RPCS3/rpcs3/pull/9308

**Comment by qurious-pixel** [comment]
Make sure to update your gamecontrollerdb to the latest if you are compiling your own. Main repo had an update a few days ago, and [GamecontollerDB](https://github.com/gabomdq/SDL_GameControllerDB) was updated yesterday.

I have native support with DualSense.

**Comment by RedDevilus** [comment]
That's only for Linux users, on windows there is no native support. There is the Xinput method which is a general-purpose method for now.

**Comment by RedDevilus** [comment]
https://github.com/PCSX2/pcsx2/pull/3894

Actually it was also for Mac

**Comment by halotroop2288** [comment]
"open the issue. stop having it be closed." - said the Windows users.

**Comment by RedDevilus** [comment]
![P_20210914_023608](https://user-images.githubusercontent.com/24227051/133174879-1b6b6585-f735-4a86-8ba2-4dd130cb66d2.jpg)
 Working fine here.

**Comment by halotroop2288** [comment]
??? Anyway, strange unrelated images aside, please work on native support for the DualSense controller, without the use of third-party programs or drivers.

**Comment by RedDevilus** [comment]
Oh like native HID support? Thought there was an issue open for it.

**Comment by halotroop2288** [comment]
> Thought there was an issue open for it.
This issue *is* asking for HID support. And it's the first one that shows up in a DuckDuckGo search. It's a really bad look to have closed this issue seemingly without reading it at all.

**Comment by RedDevilus** [comment]
Relax, seems there is no issue open for it, nor i don't know why this one is closed when we don't have native HID support.

**Comment by MrCK1** [comment]
> 
> 
> > Thought there was an issue open for it.
> 
> This issue _is_ asking for HID support. And it's the first one that shows up in a DuckDuckGo search. It's a really bad look to have closed this issue seemingly without reading it at all. The **least** you could do is reference another open issue about it.

You're right, it looks like there isn't any issue asking about it. I'll just go ahead and re-open this for now. Keep in mind that there's no immediate work planned on this for the near future.

**Comment by RedDevilus** [comment]
In the future this should be natively supported via SDL2 without losing remapping benefit.
