### ISSUE TITLE
[Feature Request] Support fo Gamepad "Trust GXT 540 Wired Gamepad | Yula"

### ISSUE THREAD

**Issue by mixpc** [PCSX2/pcsx2#4237]
Hi,
Could you please add support for "Trust GXT 540 Wired Gamepad | Yula" ?

Link to vendor website: [https://www.trust.com/en/product/20712-gxt-540-yula-wired-gamepad](https://www.trust.com/en/product/20712-gxt-540-yula-wired-gamepad)

This gamepad has an X-Input/ DirectInput switch but in any of the two positions, PCSX2 will not detect it. I'm running PCSX2 v.1.7.0 on Ubuntu 20.10 and the gamepad is not detected. I'm pasting the log below.

Installed via Retropie latest script which adds:
[http://ppa.launchpad.net/pcsx2-team/pcsx2-daily/ubuntu/](http://ppa.launchpad.net/pcsx2-team/pcsx2-daily/ubuntu/)
from which PCSX2 1.7.0 is installed.

LOG:
```
PCSX2 1.7.0-0 - compiled on Oct 16 2020
Savestate version: 0x9a0f0000

Host Machine Init:
	Operating System =  Linux 5.8.0-43-generic x86_64
	Physical RAM     =  5378 MB
	CPU name         =  AMD A6-5200 APU with Radeon(TM) HD Graphics
	Vendor/Model     =  AuthenticAMD (stepping 01)
	CPU speed        =  1.994 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 3ed8220b
	x86EFlags        =  2fd3fbff

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX
	SSE4a 

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins from /usr/lib/games/PCSX2...
	Bound   GS: libGSdx-SSE4.so [GSdx (GCC 10.2.0 SSE4.1/AVX) 1.2.0]
	Bound  PAD: libonepad.so [OnePAD 0 2.0.0]
	Bound  USB: libUSBnull-0.7.0.so [USBnull Driver 0 0.7.0]
	Bound DEV9: libdev9null-0.5.0.so [DEV9null Driver 0 0.5.0]
Plugins loaded successfully.

(GameDB) 9870 games on record (loaded in 482ms)
onepad: Joystick (SHANWAN Trust Gamepad,GUID:030000005f140000c501000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (SHANWAN Trust Gamepad,GUID:030000005f140000c501000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.
```

Before trying the AntiMicro option, please, kindly let me know any other data you may need to make this gamepad work.

Thank you for your attention in advance!

**Comment by RedDevilus** [comment]
Should be done at upstream: https://github.com/gabomdq/SDL_GameControllerDB

They list different ways of getting the mapping of the controller.

**Comment by mixpc** [comment]
Thank you for your prompt feedback.

gamecontrollerdb.txt in [https://github.com/gabomdq/SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) lists two Trust gamepads. Whether they are my model "Trust GXT 540 Wired Gamepad | Yula" I don't know at this stage.

I'm using "SDL2 Gamepad Tool" to do the mapping. "SDL2 Gamepad Tool" detects the gamepad as X360 Controller (mapping available) as per screenshot below:

![image](https://user-images.githubusercontent.com/22727058/108765967-ceabcb80-7554-11eb-95fe-8d679f6b3f23.png)

Please, kindly confirm which action/s you would need from me to help you support my gamepad in PCSX2. Is it the first approach "Set Mapping As Environment Variable"? Or the second approach "Second approches is to find mappings database file in the game folder, usualy it's called gamecontrollerdb.txt and add mapping string to the end of the file"? Both mentioned [here](https://www.generalarcade.com/gamepadtool/).

Any piece of advice is welcome. Thank you in advance

**Comment by RedDevilus** [comment]
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

There it's categorised for Windows/Linux/Mac and per platform it's ordered alphabetically for the gamepad name which isn't that critical to be correct , you can compare with the other gamepads there.

You could even add it yourself on there:
![image](https://user-images.githubusercontent.com/24227051/108766757-d61fa480-7555-11eb-8e29-80d6e0faf8a0.png)
Example:
03000000c82d00000090000011010000,8BitDo FC30 Pro,a:b1,b:b0,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b13,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a5,rightx:a2,righty:a3,start:b11,x:b4,y:b3,platform:Linux,

Make sure it ends with ,platform:Linux,  and starts with those numbers 0300000.....

**Comment by mixpc** [comment]
Thank you. I can see. The two existing "Trust Gamepad" in the file show
`,platform:Windows,`

So I have tried with antimicrox 1.3.4 (mind it is not antimicro but the new current fork) so here is the code and a screenshot: (kindly mind the gamepad is named as "SHANWAN Trust Gamepad")

![image](https://user-images.githubusercontent.com/22727058/108768298-c903b500-7557-11eb-894b-e49eed8c3f8f.png)

And then click on Controller Mapping:

![image](https://user-images.githubusercontent.com/22727058/108769123-d8cfc900-7558-11eb-82c9-ccdf06811c58.png)

`030000005f140000c501000010010000,SHANWAN Trust Gamepad,platform:Linux,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
`

You can see
,platform:Linux,
in the code (3rd parameter) and it does start with the 03000000 numbering.

Please, let me know if there is anything else I can test or provide you additional information. I will be glad to do it.

Thank you once more,

**Comment by RedDevilus** [comment]
`030000005f140000c501000010010000,SHANWAN Trust Gamepad,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,guide:b12,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,platform:Linux,`
, linux thing has to be at the end

Adding it will be like this: 
![image](https://user-images.githubusercontent.com/24227051/108769970-09643280-755a-11eb-8404-f7db75ee02c7.png)

**Comment by mixpc** [comment]
Thank you for your support. I should add that I did the mapping with the D-Input switch selected in the gamepad.

Just one doubt, what are the options now to make use of this mapping in PCSX2? Having AntiMicroX open with the new mapping and launching PCSX2 does not work. Wait for a new release in [https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily](https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily) with latest version so far dating from 2020-11-10?

By the way, when the X-Input switch is selected the name is X360 Controller:

![image](https://user-images.githubusercontent.com/22727058/108785357-88189a00-7571-11eb-8592-18d8e3602dc9.png)

but the mapping in Controller Mapping does not seem responsive.

**Comment by lightningterror** [comment]
Mapping is added to master, you will need to pull latest changes and compile it again.
