### ISSUE TITLE
[BUG] Black Screen - Eyetoy Antigrav

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4240]
**Describe the bug**
black screen where you would expect to find a video stream from the eyetoy

**To Reproduce**
start antigrav with the eyetoy

**Expected behavior**
a video stream from the eyetoy should appear

**GS Settings**
standard software mode

**Emulation Settings**
usb set to eyetoy

**GS Window Screenshots**
![gsdx_20210223021018](https://user-images.githubusercontent.com/8851653/108816776-696bd080-757c-11eb-9851-48745aabdb75.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-1003
 - OS: Windows 10 
 - CPU: i5-9600
 - GPU: GTX 960

**Logs and Dumps**
[gsdx_20210223021018.gs.zip](https://github.com/PCSX2/pcsx2/files/6027466/gsdx_20210223021018.gs.zip)

**Comment by Florin9doi** [comment]
Eyetoy Antigrav asks for a 160x112 video.

**Comment by gil938271** [comment]
Wait can i use the PlayStation eye? It have the same resolution as the eye toy

**Comment by atomic83GitHub** [comment]
You can use any camera with pcsx2 as an eyetoy.

**Comment by gil938271** [comment]
it have the same components of the eyetoy someone should make a direct driver (CL EYE runs at 0.5fps)

**Comment by gil938271** [comment]
also apparently mine can run just fine at that resolution and its a generic Microsoft web cam

**Comment by gil938271** [comment]
it still doesn't work

**Comment by gil938271** [comment]
![image](https://user-images.githubusercontent.com/84280265/118414184-d9858080-b6ab-11eb-8e20-d89ed5bf2a34.png)

**Comment by gil938271** [comment]
![image](https://user-images.githubusercontent.com/84280265/118414211-f91ca900-b6ab-11eb-8448-1098c4088bea.png)

**Comment by gil938271** [comment]
![image](https://user-images.githubusercontent.com/84280265/118414224-06399800-b6ac-11eb-9809-ed63f2e5e9bb.png)

**Comment by seta-san** [comment]
Antigrav doesn't work yet. Try with eyetoy play

**Comment by gil938271** [comment]
play 3 works like a charm. thank you for your time. just out of curiosity do you have a time estimate for that game? i really like it.

**Comment by seta-san** [comment]
I know someone is working on it. No time table.

**Comment by gil938271** [comment]
ok thanks

**Comment by gil938271** [comment]
quick question can you lower the resolution of the camera by simply cutting out the video feed? simply hacking off 1280 pixels from the width of the picture?

**Comment by seta-san** [comment]
> quick question can you lower the resolution of the camera by simply cutting out the video feed? simply hacking off 1280 pixels from the width of the picture?

Its being worked on

**Comment by gil938271** [comment]
ok

**Comment by gil938271** [comment]
when will the new fix be released?

**Comment by gil938271** [comment]
and its solve.......

**Comment by seta-san** [comment]
partially... in a way.

**Comment by RedDevilus** [comment]
Use the forums instead please if you have no extra information about the issue.

**Comment by seta-san** [comment]
I'm closing this issue for the longer term issue of newer model webcams increasingly dropping native support for lower resolutions and the need to be able to descale high resolution video feeds.

https://github.com/PCSX2/pcsx2/issues/4635
