### ISSUE TITLE
[BUG] No Video Steam from Eyetoy - Singstar Series.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4241]
**Describe the bug**
clearly displaying something wrong.

**To Reproduce**
get ingame with eyetoy on 

**Expected behavior**
the video stream from the eyetoy should start

**GS Settings**
standard software

**Emulation Settings**
usb enable both singstar mic and eyetoy

**GS Window Screenshots**
![gsdx_20210223021821](https://user-images.githubusercontent.com/8851653/108817385-7210d680-757d-11eb-8066-e41e7616428d.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-1003
 - OS: Windows 10
 - CPU: i5-7600
 - GPU: GTX 1070

**Logs and Dumps**
[gsdx_20210223021821.gs.zip](https://github.com/PCSX2/pcsx2/files/6027499/gsdx_20210223021821.gs.zip)

**Comment by prafullpcsx2** [comment]
@Florin9doi Have you taken a look into this? Any idea what's wrong? This problem still exists.

**Comment by seta-san** [comment]
sorry. i hardly have a chance to post or test anymore since my days are now spent wrestling a 1-year-old. i thought i should mention that the American Karaoke Revolution games have a similar issue with eyetoy video not showing but rather than showing random garbage from memory it just gives a black screen.
