### ISSUE TITLE
[Bug] A bunch of Gran Turismo 4 Bugs

### ISSUE THREAD

**Issue by Back2Life888** [PCSX2/pcsx2#4248]
**Describe the bug**
![Baa](https://user-images.githubusercontent.com/76780043/108984487-f0c75a00-76ca-11eb-8eb6-1bf091fff2bb.png)
![GG](https://user-images.githubusercontent.com/76780043/108984518-f755d180-76ca-11eb-8e4b-749d2403032d.png)
![ggadhf](https://user-images.githubusercontent.com/76780043/108984523-f91f9500-76ca-11eb-9d44-9e0614806a60.png)
![gggg](https://user-images.githubusercontent.com/76780043/108984534-fc1a8580-76ca-11eb-8fa2-563a357ac404.png)

**To Reproduce**
GS:
Renderer: D3D11
Interlacing: Automatic
TF: PS2 Bilinear

Allow 8-Bit Textures /
3x Native
x16 Anisotropic Filtering
Mipmap: Basic
CRC: Automatic
DATE: Fast
Blending: Basic
HW Hacks /
Texture Offsets: X 365 Y 187

Emulation:
Screen Resolution: 1920x1080
Zoom: 100.00
PCSX2 Aspect Ratio: 16:9
Game Aspect Ratio: 16:9

Launch the game, and go to any race and done..

**Expected behavior**
For the duplicate car, I think it is a ghost feature and it will emulate on how you raced last time..
For the twitching objects, It should not twitch weirdly.. Somehow, some people doesn't have this problem..
For the messed up text, It should look like its positioned correctly.
For the weird bug below the screen, it shouldn't be there.. It can be fixed by messing with the zoom at the cost of the game being way too zoomed..

**GS Settings**
Listed above

**Emulation Settings**
Safe Preset
The rest is also listed above

**GS Window Screenshots**
Already listed above

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-237
 - OS: Windows 10
 - CPU: i7-6700
 - GPU: GTX 1650 Palit (Not OC)

**Logs and Dumps**
Cannot share because its 14 GB

**Comment by tadanokojin** [comment]
2/4 are upscaling problems. We don't accept issues for those.
Twitching is maybe z fighting or mipmapping but hard to tell based on your description.
Donno about the ghost car.

**Comment by Squall-Leonhart** [comment]
For ghost  car, see https://forums.pcsx2.net/Thread-Gran-Turismo-4-License-Test-Ghosts-Bugged

**Comment by Back2Life888** [comment]
> 2/4 are upscaling problems. We don't accept issues for those.
> Twitching is maybe z fighting or mipmapping but hard to tell based on your description.
> Donno about the ghost car.

The twitching objects from far away occurs if you:

1. Look at far away objects like cones
2. Accelerate and notice far away object twitching in a way

**Comment by tadanokojin** [comment]
Doesn't happen in SW rendering I take it right?

**Comment by Back2Life888** [comment]
wait a minute.. Imma do that now

**Comment by Back2Life888** [comment]
I upgraded to dev-1008 and all of these bugs still occur.. In SW rendering, yes the twitching objects still happen.. All I know is that it also happens on normal PS2 hardware but not too twitchy to the point it disturbs the gameplay.. Here is some footage https://www.youtube.com/watch?v=F6lZIxk_h9g&ab_channel=GamePlayStation.. The twitching is still present but at least its still OK..

**Comment by Back2Life888** [comment]
> For ghost car, see https://forums.pcsx2.net/Thread-Gran-Turismo-4-License-Test-Ghosts-Bugged
> 
> Also: #1563

it doesn't help since the new dev-1008 has revamped settings..

**Comment by refractionpcsx2** [comment]
> > For ghost car, see https://forums.pcsx2.net/Thread-Gran-Turismo-4-License-Test-Ghosts-Bugged
> > Also: #1563
> 
> it doesn't help since the new dev-1008 has revamped settings..

What does that matter? You can still set that clamping (EE full clamping) manually.  I'm not sure what revamp you're referring to though.

**Comment by Back2Life888** [comment]
9:07 is the timestamp you can notice it.. With the forum thing with the ghost bug, it just crashes the game.. So the ghost workaround is utter bullshit with the dev-1008..

**Comment by Back2Life888** [comment]
And of course, do not forget the FULL THROTTLE and the GET READY TO DRIVE text not disappearing in a Rolling Start race type..

**Comment by RedPanda4552** [comment]
> 
> 
> And of course, do not forget the FULL THROTTLE and the GET READY TO DRIVE text not disappearing in a Rolling Start race type..

This is due to EE clamping. Most of the game requires it be set to Full, but license tests and some driving missions require it be set to Normal. Not a valid emulation bug. The same also applies to the car ghosts, but these may remain broken in license tests due to the requirement of Normal clamping.

As for the "screen twitching", it is generally accepted that GT4's interlacing technique is pretty awful, and even the best deinterlacing methods in PCSX2 have problems with it, either causing screen shake, screen blur, or both. It is generally accepted that switching the game to its Progressive Scan mode in the in-game settings is a must to prevent this.

> 
> 
> > 2/4 are upscaling problems. We don't accept issues for those.
> > Twitching is maybe z fighting or mipmapping but hard to tell based on your description.
> > Donno about the ghost car.
> 
> The twitching objects from far away occurs if you:
> 
>     1. Look at far away objects like cones
> 
>     2. Accelerate and notice far away object twitching in a way

The twitching on ground textures is most likely mipmapping, which GT4 uses only in a few spots in the entire game but has flickering problems when it does. This is really the only valid item I can find in this list, and it is already tracked in our mipmapping meta issue: https://github.com/PCSX2/pcsx2/issues/1561

**Comment by refractionpcsx2** [comment]
As above, only valid issue is being tracked in issue linked above
