### ISSUE TITLE
[BUG] Ridge Racer V - missing lens flare

### ISSUE THREAD

**Issue by themanwiththeplan911** [PCSX2/pcsx2#4256]
**Describe the bug**

Lens flares don't show up when they should.
**To Reproduce**

Play Grand Prix stage 2
**Expected behavior**

a lens flare is supposed to show up when the sun is visible 
https://youtu.be/pEmTtuqgya4?t=598 (PS2)
https://youtu.be/TGTR0G2xC1E?t=133 (PS2)
https://youtu.be/IxUxDfW1EvM?t=553 (PS2) 
https://youtu.be/XBQ_PulLAYI?t=46 (PCSX2) (this is just for example since i cant really upload a video or anything its easier to demonstrate in motion)
**GS Settings**

Software
Autoflush ON
Mipmapping ON
**Emulation Settings**

VUs -> Clamping Mode -> Extra + Preserve Sign
MTVU ON (tried with OFF as well)
InstantVU ON (tried with OFF as well)
It's worth noting that having MTVU or Instant VU set to ON causes graphical issues on certain stages, nighttime ones to be specific, but here it doesn't seem to be the case.
**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-1016-gf42befadf
 - OS: W10
 - CPU:  Ryzen CPU
 - GPU:  Nvidia CARD
**Logs and Dumps**

**Comment by Mrlinkwii** [comment]
Is this still an issue on latest nightly?

**Comment by refractionpcsx2** [comment]
No response in over 6 months, no other reports of this issue so closing for now, if it's still a problem we can reopen.

**Comment by TeddyRuxpin22** [comment]
Issue still present in software renderer with nightly build v2.7.106 (Sun Feb 8 14:28:05 2026)

**Comment by SK91no** [comment]
This issue doesn't appear in software as of the latest nightly, however it doesn't work in hardware at all, even at 1x
