### ISSUE TITLE
[BUG] Tooltips in the GSdx Settings window are using the wrong language

### ISSUE THREAD

**Issue by TraceBullet** [PCSX2/pcsx2#4264]
**Describe the bug**

Tooltips in the GSdx Settings window are displayed using a different language instead of the selected language

**To Reproduce**

- In the menu, click Config > Video (GS) > Plugin Settings...
- Hover over any of the Hardware Renderer settings to display the tooltip

**Expected behavior**

Tooltips should appear in the selected language.

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/784102/109517825-abfb4480-7a77-11eb-8362-59f864d246d1.png)
![image](https://user-images.githubusercontent.com/784102/109517737-9423c080-7a77-11eb-9b6d-868426f532a9.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: v1.7.0-dev-1030
 - OS: Windows 10

**Comment by RedDevilus** [comment]
We know, https://github.com/PCSX2/pcsx2/pull/4261 will fix this. Thanks for mentioning it as issue however 👍

**Comment by tadanokojin** [comment]
resolved
