### ISSUE TITLE
Character "$" when part of a file path on Windows causes weird issues. 

### ISSUE THREAD

**Issue by Apocalypse612** [PCSX2/pcsx2#4266]
**Describe the bug**
If you have a "$" character as part of your file path to the PSX2 Binaries install folder, it will completely fuck everything up and make a new folder tree inside of PSX2. This doesn't allow config files to ever be saved correctly. 

**To Reproduce**
My example path:
D:\$\Emulators & Tools\PlayStation 2\pcsx2\PCSX2

**Expected behavior**

**GS Settings**

**Emulation Settings**

**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision: pcsx2-v1.7.0-dev-1040-gb6246a7ba-windows-x86
 - OS: Windows 10
 - CPU: X2 Xeon E5-2690v2s
 - GPU: GTX 1080 TI

**Logs and Dumps**

**Comment by kenshen112** [comment]
https://github.com/PCSX2/pcsx2/pull/4005 can you test if this fixes the issue?

**Comment by Apocalypse612** [comment]
> 
> 
> #4005 can you test if this fixes the issue?

It does not fix the issue. My dev version is the latest as of today, so it should include that fix. (updated my info, sorry for excluding)

**Comment by Apocalypse612** [comment]
It keeps trying to double up my path
![image](https://user-images.githubusercontent.com/6374154/109887847-5f5e6780-7c37-11eb-87a7-15caaf91e43e.png)

**Comment by refractionpcsx2** [comment]
> > #4005 can you test if this fixes the issue?
> 
> It does not fix the issue. My dev version is the latest as of today, so it should include that fix. (updated my info, sorry for excluding)

That PR is not included in the latest dev build, please try the PR.

**Comment by Apocalypse612** [comment]
Well then, looks like I'm forced to build this myself. I'll get back to you in a few days after this huge visual studio download completes with my slow net.

**Comment by tadanokojin** [comment]
https://github.com/PCSX2/pcsx2/pull/4005/checks?check_run_id=1999227981

click artifacts dropdown and select 32 bit artifact.

**Comment by Apocalypse612** [comment]
> 
> 
> https://github.com/PCSX2/pcsx2/pull/4005/checks?check_run_id=1999227981
> 
> click artifacts dropdown and select 32 bit artifact.

Aha, thanks for that. 

To answer your question, the issue still persists. Also, I couldn't get this build to run more than once after setting the plugin / bios path manually (it's still failing to find both automatically). After I did this, it simply self terminates the .exe after I try to run it.

**Comment by tadanokojin** [comment]
Actually how is this even supposed to work anyway.

`D:$\Emulators & Tools\PlayStation 2\pcsx2\PCSX2`

How is this path legal? You can have a folder named `$` but you can't rename your device that afaik. What is the expected path? Is it supposed to be `D:\$\Emulators & Tools\PlayStation 2\pcsx2\PCSX2` or are you expecting the `$` to do some sort of replacement or something?

**Comment by Apocalypse612** [comment]
This is a github issue. The platform automatically renames it, it's correct. I forgot Github did this. The link you pasted above is the one that I was using.

**Comment by Squall-Leonhart** [comment]
Mm... $ are traditionally used by ntfs to designate folders as hidden, i'm not sure how applications would treat it as the sole character in a directory name since its a modifier character.

\$Name\ is the same as \Name\, so you're more or less passing an illegal path,  now whether this works for some cases is really those cases behaving outside of the windows intended usage of the character.

**Comment by lightningterror** [comment]
Closing as Leon had pointed out some things, and overall it is an extremely niche to none use case.

**Comment by Apocalypse612** [comment]
Alright, so basically I'm screwed because that's how I orignize my entire operating system. It's not fixed by the way. Oh well.
