### ISSUE TITLE
[BUG] Flickering water texture in Ghosthunter (PAL)

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#4275]
Right at the beginning of the game the water texture flickers

**To Reproduce**
Just start a new game, reach the section with the water 

**Expected behavior**
No flickering

**GS Settings**
Default settings. The issue is there even with native resolution, tried with opengl, dx11 and software renderers.

**Emulation Settings**
All default, even with MTVU disabled still happens.

**GS Window Screenshots**
![FormatFactoryghosthunter](https://user-images.githubusercontent.com/38129260/110401157-5b887600-8079-11eb-9184-fdc182d985e4.gif)

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0 dev 1053
 - OS: Windows 10
 - CPU: G4560
 - GPU: GT 1030

**Comment by RedDevilus** [comment]
Can you test with  automatic settings off?

![image](https://user-images.githubusercontent.com/24227051/110401498-f5e8b980-8079-11eb-9135-a588807c2f3f.png)

**Comment by bigol83** [comment]
I tested it with automatic gamefixes off, it still flickers and it also has some missing graphics, like the ladders.

**Comment by refractionpcsx2** [comment]
Can you try the EE Timing fix or enabling GIF FIFO, see if either of those make a difference?

**Comment by bigol83** [comment]
I think i found what setting breaks the graphics. It's GPU Palette conversion. When i have it enabled water texture flickers, with it off there are no flickers anymore.

**Comment by refractionpcsx2** [comment]
One of the graphics devs say that should be avoidable so it needs looking in to, so I'll leave this open

**Comment by refractionpcsx2** [comment]
IS this issue still present?

**Comment by lightningterror** [comment]
Can no longer reproduce it on latest master.

Dump:
[ghosthunter.zip](https://github.com/PCSX2/pcsx2/files/8654400/ghosthunter.zip)

**Comment by bigol83** [comment]
No, there is no issue anymore.
