### ISSUE TITLE
[BUG] Performance regression (Need for Speed: Most Wanted/Carbon)

### ISSUE THREAD

**Issue by bamq** [PCSX2/pcsx2#4286]
**Describe the bug**
It seems there is a severe performance hit after https://github.com/PCSX2/pcsx2/commit/862518e7da5dd50f1f3990324ad8960f2371a020 testing the games Need for Speed: Most Wanted and Need for Speed: Carbon. Before, the games ran perfectly at 60fps, now they run about 45fps or lower. Revert back to 1.7.0-dev-1050 (build before that commit) and the issue is not there.

**To Reproduce**
Load up the game to at least the main menu.

**Expected behavior**
Game runs smoothly as it used to.

**Emulation Settings**
Turning off speed hacks seems to make some sort of difference, but they used to work fine with no problems.

**GS Window Screenshots**
![image](https://user-images.githubusercontent.com/6969348/110995779-848e5c80-8340-11eb-9fd3-4c2fcf5dffd1.png)

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-1072
 - OS: Windows 10 64bit
 - CPU: AMD Ryzen 7 3700X
 - GPU: NVIDIA GeForce RTX 2070 Super

**Comment by lightningterror** [comment]
A gsdump would be nice for testing.

**Comment by bamq** [comment]
Does this work? Will gladly provide more info if needed

[gsdx_20210312145754.gs.zip](https://github.com/PCSX2/pcsx2/files/6132905/gsdx_20210312145754.gs.zip)

**Comment by bamq** [comment]
I have noticed another strange thing. After running the game to the main menu, trying to shutdown the game causes the console log to get stuck on this line:
`Decommitting host memory for virtual systems...`

and PCSX2 will not close or boot any game, has to be killed through task manager.

**Comment by tellowkrinkle** [comment]
@bamq Can you verify with the above PR?

**Comment by bamq** [comment]
I've downloaded the artifact from your pull request. The issue is still there. The performance actually has improved somewhat, though it still struggles with maintaining full speed emulation and there are dramatic slowdowns in some areas of the game where there were none before. The issue I mentioned above with shutting down the emulator while in the game's menu also persists.

**Comment by bamq** [comment]
I've recorded a video comparing the old build without the issues and your pr build if this is at all useful: https://youtu.be/8vp32Azd7Hw

**Comment by refractionpcsx2** [comment]
Thanks for the video, one bit of information which you omitted from the video (because the window was too small), what were the before/after percentages for the GS in the output window title? just so we can gauge how close to the limit you were before

**Comment by refractionpcsx2** [comment]
Just to add my Results:

Master-1078:
![image](https://user-images.githubusercontent.com/6278726/111129845-7756b500-856e-11eb-9581-dc482a9995ba.png)

PR #4288 
![image](https://user-images.githubusercontent.com/6278726/111129890-82a9e080-856e-11eb-8ad4-8d53699afdd1.png)

Master-1050 for prosperity:
![image](https://user-images.githubusercontent.com/6278726/111130174-cdc3f380-856e-11eb-8734-fefa775e11c4.png)

So yeah, performance is still pretty terrible to what it used to be, nearly a 40% performance drop from the old master.

**Comment by bamq** [comment]
>what were the before/after percentages for the GS in the output window title? just so we can gauge how close to the limit you were before

Here's the full window for both games

1050:
![pcsx2_4KU81ECZqZ](https://user-images.githubusercontent.com/6969348/111172068-812ee700-8573-11eb-891b-3178798f07df.png)

![pcsx2_fLNyQNuszG](https://user-images.githubusercontent.com/6969348/111172084-855b0480-8573-11eb-967d-24d29471db6f.png)

PR:
![pcsx2_bD2rLn42BS](https://user-images.githubusercontent.com/6969348/111172118-8d1aa900-8573-11eb-84dd-e6a6a66e16f8.png)

![pcsx2_gmoG3NkwJ1](https://user-images.githubusercontent.com/6969348/111172140-9146c680-8573-11eb-8b01-61f9c1646179.png)

Here's also a gsdump for the Carbon main menu
[gsdx_20210315095033.gs.zip](https://github.com/PCSX2/pcsx2/files/6142219/gsdx_20210315095033.gs.zip)

**Comment by tellowkrinkle** [comment]
@bamq can you try with the latest version of that PR?

**Comment by refractionpcsx2** [comment]
Performance seems to be back where it was in master 1050, though the GS usage seems to be 30% higher still
![image](https://user-images.githubusercontent.com/6278726/111285114-b3564c80-8638-11eb-8474-51f94b9e9d78.png)

**Comment by bamq** [comment]
Here are my results with the latest PR build:

![pcsx2_Ljbk8k2v3P](https://user-images.githubusercontent.com/6969348/111397365-212d6300-868f-11eb-86e0-8380d805c7c7.png)

![pcsx2_bKstOmlmdE](https://user-images.githubusercontent.com/6969348/111397379-27234400-868f-11eb-9dae-6485268982f8.png)

Judging from the main menu alone, performance seems to be about where it used to be. I'll have to do some more testing in game

**Comment by ISuckGood** [comment]
I reported this issue on forums with 0 positive feedback 

https://forums.pcsx2.net/Thread-terrible-performance-version-1-7-0

**Comment by refractionpcsx2** [comment]
> I reported this issue on forums with 0 positive feedback
> 
> https://forums.pcsx2.net/Thread-terrible-performance-version-1-7-0

and you were told it could be this.

**Comment by ISuckGood** [comment]
I was told No hacks slider in 1.6.0 is different than the no hacks slider in 1.7.0

**Comment by refractionpcsx2** [comment]
> I was told No hacks slider in 1.6.0 is different than the no hacks slider in 1.7.0

yes because it is slightly different, though if you keep it on defaults you won't notice a difference.

**Comment by RedDevilus** [comment]
I suggest rereading the thread to avoid confusion.

**Comment by ISuckGood** [comment]
Then this bug report shall be closed as no issue

**Comment by tadanokojin** [comment]
You also said this started way earlier than this did
```
HAS THE MASSIVE SLOWDOWNS
pcsx2-v1.7.0-dev-686-g03445d0b5-windows-x86
```

where as the offending build is 1051

**Comment by refractionpcsx2** [comment]
> Then this bug report shall be closed as no issue

this is nothing to do with your slider differences.

**Comment by ISuckGood** [comment]
yep it does . see the responses in that thread from the developers. If it has nothing to do with the sliders then the developers/moderators  purposely lied to me since i gave them exactly the git version when the massive slowdown occured

**Comment by tadanokojin** [comment]
Then it's not this issue and you're wasting our time.

**Comment by bamq** [comment]
I've played both games for a few hours now and the performance seems to be back to normal! I really appreciate your work on this issue. I'm not experiencing the 100% GS usage that @refractionpcsx2 showed in his screenshot so maybe there's still something there if he wants to keep testing as well.

**Comment by refractionpcsx2** [comment]
> I've played both games for a few hours now and the performance seems to be back to normal! I really appreciate your work on this issue. I'm not experiencing the 100% GS usage that @refractionpcsx2 showed in his screenshot so maybe there's still something there if he wants to keep testing as well.

It's fine, it seems to be temporary but yes everything seems to be back where it was :)

**Comment by ISuckGood** [comment]
thank god
