### ISSUE TITLE
fmt error when building on Linux

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#4294]
version https://github.com/PCSX2/pcsx2/commit/be89e23030767301cdbff4a6f25e3c71c4e69351

```
[  297s] In file included from /home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20210313/pcsx2/GameDatabase.cpp:20:
[  297s] /usr/include/fmt/core.h: In instantiation of 'int fmt::v7::detail::check(fmt::v7::detail::unformattable) [with T = wxString]':
[  297s] /usr/include/fmt/core.h:1438:18:   required from 'fmt::v7::detail::value<Context> fmt::v7::detail::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; fmt::v7::detail::type <anonymous> = fmt::v7::detail::type::custom_type; T = wxString; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
[  297s] /usr/include/fmt/core.h:1589:64:   required from 'fmt::v7::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; Args = {wxString}]'
[  297s] /usr/include/fmt/core.h:1626:18:   required from 'fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<Char>, Char>, fmt::v7::remove_reference_t<Args>...> fmt::v7::make_args_checked(const S&, fmt::v7::remove_reference_t<Args>& ...) [with Args = {wxString}; S = char [7]; Char = char]'
[  297s] /usr/include/fmt/core.h:2075:54:   required from 'std::__cxx11::basic_string<Char> fmt::v7::format(const S&, Args&& ...) [with S = char [7]; Args = {wxString}; Char = char]'
[  297s] /home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20210313/pcsx2/GameDatabase.cpp:106:76:   required from here
[  297s] /usr/include/fmt/core.h:1423:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
[  297s]  1423 |       formattable<T>(),
[  297s]       |       ^~~~~~~~~~~~~~~~
[  297s] make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:413: pcsx2/CMakeFiles/PCSX2.dir/GameDatabase.cpp.o] Error 1
```
Operating System: openSUSE Tumbleweed 20210311
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa DRI Intel® UHD Graphics 620

**Comment by refractionpcsx2** [comment]
Can you provide details of your distro and dev environment etc to help us diagnose the problem?  It works for everybody else including our Github Actions CI and your fix evidently broke everything.

**Comment by guoyunhe** [comment]
Operating System: openSUSE Tumbleweed 20210311
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa DRI Intel® UHD Graphics 620

**Comment by Vogtinator** [comment]
I see the same issue, indicentially also on Tumbleweed.

How is it supposed to work? Neither fmt, wxWidgets nor PCSX2 provide the necessary formatter specialization, and I don't think implicit conversion is done.

Maybe it's because GCC 11 is the default compiler?

**Comment by F0bes** [comment]
Is this still an issue?

**Comment by joder666** [comment]
This one is not an issue anymore on master and tumbleweed. I just did a compile with both gcc and clang.
Wayland and pgo/lto are fobar though.

**Comment by kenshen112** [comment]
#5077 is on that track to fix it. Fobar is an issue? What error's are those packages giving

**Comment by tellowkrinkle** [comment]
> Is this still an issue?

Should have been fixed by #4140

**Comment by joder666** [comment]
> #5077 is on that track to fix it. Fobar is an issue? What error's are those packages giving

"fobar" is an acronym, look it up (;
On tumbleweed can't build with wayland supoprt it fails due to missing "wayland-egl.h" which #5077 may help with.

The lto/pgo issue looks like to be due to libchr. I get a bunch of "undefined reference to `__gcov_" and "collect2: error: ld returned 1 exit status" around it.

**Comment by kenshen112** [comment]
Sorry I thought you meant media player package 🤣 I'm very tired
