### ISSUE TITLE
Issue creation was blocked

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#4297]
If you click the new issue button, you will see three links:

![图片](https://user-images.githubusercontent.com/5836790/111153939-87ea4800-85cd-11eb-9ccc-f7aca0606a5c.png)

None of them allow you to create issue. You have go to https://github.com/PCSX2/pcsx2/issues/new manually to create an issue. This is not friendly for users.

The issue was introduced by https://github.com/PCSX2/pcsx2/pull/3917

**Comment by lightningterror** [comment]
That's weird, it should be something like this
![image](https://user-images.githubusercontent.com/18107717/111154499-93208200-8593-11eb-9999-a6774399c8ff.png)

I believe https://github.com/PCSX2/pcsx2/commit/4840d1db93b3f6c51c29c0d6f820608453d36e4e introduced the regression.

**Comment by refractionpcsx2** [comment]
Should be fixed now
