### ISSUE TITLE
[Feature Request] Use system yaml-cpp on Linux

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#4303]
**Description**

When building PCSX2, use system yaml-cpp when it is available.

**Reason**

Some Linux distros, like openSUSE and Arch Linux, have system yaml-cpp package. Using system yaml-cpp can:
1. reduce the binary size
2. reduce build time
3. probably save some memory
4. probably good for performance

**Examples**

**Comment by kenshen112** [comment]
https://github.com/PCSX2/pcsx2/blob/789c6191691a42444a7ccca89e392f8674c4240f/cmake/SearchForStuff.cmake#L272 

We already do. And my arch package requires it and builds pcsx2 with said requirement. That said we are considering changing it for the sake of easier control over package version and how it's compiled which depending on distro can be different and can yield some... Odd results with pcsx2

**Comment by xTVaser** [comment]
Keep in mind that yaml-cpp has not officially cut a release since September 2019, despite there being many bug fixes since then.  I expect that distros would pin to the latest release though, so your mileage may vary when using the system's library.

**Comment by xTVaser** [comment]
We no longer use yaml-cpp, we have switched to rapidyaml, which will use your system library if it can find it.

https://github.com/PCSX2/pcsx2/blob/ea051c6d5fcc2eddbf749664340f283c88d058e3/cmake/SearchForStuff.cmake#L215
