### ISSUE TITLE
[BUG] Klonoa 2 - Lunatea's Veil (NTSC/US): Major bug, cannot complete first level 

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#4308]
During the first level of this game ("Sea of Tears"), after smashing a box and going through a tunnel, you reach a cliff you cannot scale.  The reason is that the balls you are meant to bounce from are located in the wrong position, far from the cliff, making progress impossible.  

This issue seems to have been documented and then erroneously reported as fixed under "Required Objects Missing" [here](https://wiki.pcsx2.net/Klonoa_2:_Lunatea%27s_Veil).  However, setting EE/FPU to any option including "Chop/Zero" (default), ""Nearest" or "Negative" does not fix the issue, and automatic gamefixes are on.

Test system:

* OS: Linux Mint 20.1 / kernel 5.8
* Compiler: gcc 10.2.0
* CPU: Intel i7-7820hk
* GPU: Nvidia GTX 1070 / driver: 460.39
* PCSX2 Version: f2525acedf488dd3615ad9908148c5345b0fe69c
* Tested software and OGL modes

**Comment by kenshen112** [comment]
I've completed most of the game in pcsx2. Unless that was newly reintroduced there could be a configuration issue on your end

**Comment by Shoegzer** [comment]
It must have been reintroduced then, or perhaps this is a linux-only issue (assuming you used Windows).  There's no configuration issue on my end.

**Comment by kenshen112** [comment]
On arch. I just completed the level

**Comment by refractionpcsx2** [comment]
Make sure you have auto fixes enabled probably before you get to the broken part.

**Comment by Shoegzer** [comment]
@kenshen112 What are your settings?
@refractionpcsx2 Thanks but I did, please see above.

**Comment by kenshen112** [comment]
Defaults

**Comment by Shoegzer** [comment]
NTSC/US version?  Which dump?

**Comment by kenshen112** [comment]
Yeah NTSC U

**Comment by Shoegzer** [comment]
I don't know what to say. I used default settings, tried with hacks on (EE cyclerate at -3) and off, software mode, hardware mode, makes no difference. When i pass through the tunnel there are aquamarine balls that are supposed to be near the cliff to allow you to jump from them onto the cliff top (this is on a real ps2), but in pcsx2 they are at the entrance to the tunnel instead and one is even half buried in the ground.  That's obviously not correct.

**Comment by kenshen112** [comment]
I even updated the PCSX2 package and was able to complete the level with all green elevators in their proper place. Since this is more of a support issue at this point can you post on the forums or in our discord?

**Comment by Shoegzer** [comment]
I just updated to the latest myself and still getting the issue.  This isn't a "support issue", it's a real bug.  Out of curiosity can you post your dump hash?  Maybe mine isn't in the db.

**Comment by Shoegzer** [comment]
Update: it doesn't appear to be a permissions problem, though I wonder if PCSX2 is simply not reading GameIndex.yaml.  Mine is in /usr/local/share/games/PCSX2.  Also, under "PCSX2 > Game Settings" I have "Automatic Gamefixes" and nothing else checked, then under "Config > Game Fixes" the "manual" box at the top is not checked.  I assume these are the proper settings to enable reading of GameIndex.yaml?

**Comment by Shoegzer** [comment]
Nevermind, this was a path issue which I've fixed.  Closing this.
