### ISSUE TITLE
[BUG] WRC 4 Fog rendered incorrectly in HW mode

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4316]
**To Reproduce**
Start first Monte Carlo stage in time trial mode. Go to Time trial then ---> x --> x --> x...

**Expected behavior**
Same behavior as SW render

**GS Settings**
Default, tested HW hacks won't help. Excluding skipdraw, but that cause other issues.
Tested both OGL/DX11.

**Emulation Settings**
Default

**GS Window Screenshots**
HW mode
![pcsx2 2021-03-22 09-39-23](https://user-images.githubusercontent.com/15552250/112034915-4f072180-8b3f-11eb-94e3-a977592c57a0.png)
SW mode
![pcsx2 2021-03-22 18-41-47](https://user-images.githubusercontent.com/15552250/112034969-60502e00-8b3f-11eb-9479-e56a8b8f6b96.png)

**System Info (please complete the following information):**
 -   PCSX2 Revision: PCSX2 1.7.0-20210319114116 - compiled on Mar 19 2021
 -   OS: Windows 10
 -   CPU: i5-4570
 -   GPU: GTX 1060

**Logs and Dumps**
Remove .ZIP
[gsdx_20210322185154.gs.xz.ZIP](https://github.com/PCSX2/pcsx2/files/6184299/gsdx_20210322185154.gs.xz.ZIP)

**Comment by snckrz** [comment]
The fog gets rendered this way in WRC3 WRC Rally Evolved (Avec Sebastian Loeb FR version) aswell.

**Comment by lightningterror** [comment]
I gave it a look and seems like a TC miss.
