### ISSUE TITLE
[BUG] Video Settings/Shader Configuration Unexpected Program Shutdown Bug

### ISSUE THREAD

**Issue by Peduls** [PCSX2/pcsx2#4317]
**Describe the bug**
Upon opening the video settings/shader configuration window there's a chance the entire PCSX2 program just closes. Happens with or without a game running. Looks like the issue is not present in version v1.7.0-dev-1017-g7512c01ca and the issue is first present in version v1.7.0-dev-1022-gd8f65dc42

**To Reproduce**
Attempt to make changes to the video settings/shader configuration. May take a few tries to see the bug.

**Expected behavior**
Should be able to open the video settings/shader configuration window without any risk of having the program close.

**GS Settings**
All default

**Emulation Settings**
All default

**GS Window Screenshots**
https://cdn.discordapp.com/attachments/315544036184293386/821604745600303104/2021-03-16_22-38-50.webm

**System Info (please complete the following information):**
 -   PCSX2 Revision: v1.7.0-dev-1022-gd8f65dc42 and up
 -   Speccy: Operating System
    Windows 10 Enterprise 64-bit
CPU
    Intel Core i7 9700K @ 3.60GHz
    Coffee Lake 14nm Technology
RAM
    32.0GB
Motherboard
    Micro-Star International Co. Ltd. Z390-A PRO (MS-7B98) (U3E1)
Graphics
    VG248 (1920x1080@144Hz)
    4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
    465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
    465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
    2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
    ASUS DRW-24B1ST j
Audio
    Realtek High Definition Audio

**Comment by RedDevilus** [comment]
I have had this issue at random but i wasn't sure what was going on and couldn't reproduce it consistently. Higher chance with changing the upscaling and any adjustment in the shader option.

**Comment by RedDevilus** [comment]
Issues:

![image](https://user-images.githubusercontent.com/24227051/112091558-ec8d4000-8b95-11eb-9585-276c60c52c09.png)

![image](https://user-images.githubusercontent.com/24227051/112091601-02026a00-8b96-11eb-97b1-1b32bf966c05.png)


Could be unrelated issue when booting:

![image](https://user-images.githubusercontent.com/24227051/112091664-2bbb9100-8b96-11eb-889a-f81d44b06477.png)


Seems to trigger when you drag and move on the sliders though it could be coincidence when i triggered it:
![image](https://user-images.githubusercontent.com/24227051/112091856-94a30900-8b96-11eb-9b8e-15e91c072e05.png)

**Comment by RedDevilus** [comment]
Above was whilst emulating a game....

Without emulating the game:


![image](https://user-images.githubusercontent.com/24227051/112092693-5575b780-8b98-11eb-9be3-9bb0eb7da219.png)

Stacktrace:
![image](https://user-images.githubusercontent.com/24227051/112092783-7fc77500-8b98-11eb-8d11-b2367c42e9ef.png)
![image](https://user-images.githubusercontent.com/24227051/112092758-73431c80-8b98-11eb-9698-39e5fed77fac.png)
![image](https://user-images.githubusercontent.com/24227051/112092827-9d94da00-8b98-11eb-99c7-45b2178f0daf.png)

**Comment by GovanifY** [comment]
Can repro, enable external shader and keep pressing OK until it crashes.
This crash is absolutely bonkers though.
