### ISSUE TITLE
See data in the GS primitive

### ISSUE THREAD

**Issue by ijacquez** [PCSX2/pcsx2#4323]
If I understand the output correctly (when debug mode is enabled), we can only see the _GIFtag_, but we can't actually see the data inside the GS packet? Is this correct?

For example, it would be ideal to see the actual vertex and color values.

**Comment by lightningterror** [comment]
Transferred this issue as GS debugging has been integrated in to the core and gsdumpgui will be a legacy tool for older versions.

**Comment by F0bes** [comment]
If you enable `Show Advanced Settings` under `Tools` and then go to `Settings`->`Interface`, click on the `Debug` option on the left hand list, you can configure PCSX2 to dump all of the draw information to disc.
