### ISSUE TITLE
[BUG] Dumper tool breaking region (SLIM ONLY)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4325]
**Describe the bug**

DUMPBIOS-MASS.ELF on certain slims will be recognised as Japanese region even if it's USA or Europe.
The old dumper incorrectly handles the ROMVER module. This behaviour makes X and O reversed because it think it's a Japanese console.
(PS2dumper doesn't work locally, only via network)
**To Reproduce**
Downloading the dumper utility - Hosted on the PCSX2 website: https://pcsx2.net/download/releases/tools.html - Select the 'Binary' option. Extract the .7z archive on to a flash drive.

Dumping the BIOS - Insert your USB flash drive with the BIOS dumper on it. - Navigate uLaunchELF to the device named mass: and open it. - Locate and run DUMPBIOS-MASS.ELF.

Then from USB flash drive to your PC and in the bios folder.

**Expected behavior**

Correct region for dumped slim.
**GS Settings**

N/A
**Emulation Settings**

N/A
**GS Window Screenshots**

N/A
**System Info (please complete the following information):**
 -   PCSX2 Revision: dev1.7-1054
 -   OS: W10
 -   CPU: i7-9750H
 -   GPU: 2060M 

**Logs and Dumps**

N/A

**Comment by lightningterror** [comment]
We only host the bios dumper binaries, the tool is closed source.
