### ISSUE TITLE
Windows build messed up pretty bad

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#433]
Since #419 merge, as @gregory38 feared.
Release AVX|Win32
![build-fail](https://cloud.githubusercontent.com/assets/1138235/5788959/0e792678-9e5f-11e4-82be-07e49a3f5d65.png)
![build-fail](https://cloud.githubusercontent.com/assets/1138235/5788964/7b29299e-9e5f-11e4-88a3-4dbbd80065a1.png)
![build-fail](https://cloud.githubusercontent.com/assets/1138235/5788970/a5302918-9e5f-11e4-99e0-a6f8128c51c4.png)
Release AVX|x64 follow-up (I know it's not ready for prime time, just a sample of current status)
![build-fail](https://cloud.githubusercontent.com/assets/1138235/5788974/f322cf36-9e5f-11e4-8c4f-a4ca4b266cef.png)
![build-fail](https://cloud.githubusercontent.com/assets/1138235/5788983/58f89a7a-9e60-11e4-812f-b9e2fa4ef112.png)

**Comment by avih** [comment]
Note that while it now compiles, GSdx seems to hang PCSX2, so we're not out of the woods yet with this mess-up.
