### ISSUE TITLE
Devil May Cry Black screen

### ISSUE THREAD

**Issue by tuermana** [PCSX2/pcsx2#4330]
Hello, I have a problem with DMC 1 where after the first cinematic the game doesn´t work and just get a Black Screen.
I'm using **Windows 10**  with **Intel core i7** and **8GB Ram**

I did something wrong? :(

**Comment by F0bes** [comment]
Hi there, sorry for your troubles.
The Github issue page is usually for pcsx2 related bugs. 
For general support, I recommended going to our discord [here](https://discord.com/invite/TCz3t9k) or to the pcsx2 forums :)

**Comment by tuermana** [comment]
> Hi there, sorry for your troubles.
> The Github issue page is usually for pcsx2 related bugs.
> For general support, I recommended going to our discord [here](https://discord.com/invite/TCz3t9k) or to the pcsx2 forums :)

Thank you :)
