### ISSUE TITLE
[BUG] Monster House - Graphics ghosting

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#4334]
**Describe the bug**
Well the game has ghosting issue on 3D objects.

**To Reproduce**
Change internal resolution doesn't happen on native

**Expected behavior**
Not having ghosting

**GS Settings**
Changing internal resolution

**Emulation Settings**
default

**GS Window Screenshots**
![1](https://user-images.githubusercontent.com/5770076/112755036-01cbf980-8ff0-11eb-8d3f-2194b36a7b6c.gif)

**System Info (please complete the following information):**
PCSX2 1.7.0-20210327185117 - compiled on Mar 27 2021
 -   OS: w10 x64
 -   CPU: 
 -   GPU: 1050ti

**Logs and Dumps**
[snaps.zip](https://github.com/PCSX2/pcsx2/files/6217451/snaps.zip)

**Comment by refractionpcsx2** [comment]
as it says in the template

We do not accept upscaling bugs at this time
If your bug is the result of upscaling please use the forums or discord for assistance with various upscaling workarounds.

**Comment by pablo4209** [comment]
Just set the Half-Pixel Offset to Normal (vertex), Texture offsets leave at 0 and turn the renderer to Direct3D 12.

**Comment by refractionpcsx2** [comment]
It's already been dealt with.
