### ISSUE TITLE
[BUG] Debugger not display correctly HEX values for GS privileged registers

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#4336]
**Describe the bug**

Pcsx2 dev v1.7 - 1163 x86 (offical buildbot), in debugger, going to memory panel  to address 12000000 GS privileged register showing random hex values, in pcx2 v1.6 stable this address show correct hex values; i was testing pcsx2 1.7 dev builds around july 2020 working ok, now lastest builds tested all have this problem.

**GS Settings**
Default options

**Emulation Settings**
Default Options

**GS Window Screenshots**

**System Info (please complete the following information):**
 -   PCSX2 Revision: PCSX2 v1.7.0-dev-1163
 -   OS: Windows 10 x64 official 20H2
 -   CPU: Ryzen 3400g
 -   GPU: Gpu integrated vega 11

**Logs and Dumps**

**Comment by refractionpcsx2** [comment]
This is accurate behaviour, kind of. on the PS2 you can only read the GS_CSR and SIGBLD registers from the EE, so attempting to read any others would result in reading the CSR value.

Now for our debugging purposes, this is probably not so good, so we might have to think of a way to do that.

**Comment by felixthecat1970** [comment]
ok, meanwhile i traced last build working before change (v1.7.0-dev-786-gd78de3237) for people need to see this hex values.

**Comment by refractionpcsx2** [comment]
> ok, meanwhile i traced last build working before change (v1.7.0-dev-786-gd78de3237) for people need to see this hex values.

yep, 787 is the build where I made those changes.  This might not get fixed for a while, we might wait until the GS is merged then do something nicer with it

**Comment by F0bes** [comment]
I've made it so you can view them in the register window.
If you can, build #4338 and test it out or wait until it is merged into master.

**Comment by felixthecat1970** [comment]
look nice F0bes, i going to try build it in linux, it make more easy to quick look in this values.
