### ISSUE TITLE
[Feature Request] Updates to the brazilian portuguese translation

### ISSUE THREAD

**Issue by Felipefpl** [PCSX2/pcsx2#4342]
[Brazilian Portuguese Pcsx2 1.6.0.zip](https://github.com/PCSX2/pcsx2/files/6232256/Brazilian.Portuguese.Pcsx2.1.6.0.zip)
I read the main page but i dont know about how to make a pull request, posting here is easier.

**Comment by RedDevilus** [comment]
Hello there, nice of you to make an issue for update on the translations. As of this moment i am waiting for the opportunity to have weblate (cloud translations) instead of the current system of Poedit which can be quite taxing for some translators with less confidence in their computer knowledge. Somewhere in the feature freeze in the coming months should normally be implemented and so a spree of translation can happen.

**Comment by Felipefpl** [comment]
Hi, i dont think of Poedit as a bad thing, regarding a translation'S site i believe that transifex is the best system (crowdin sucks A LOT) as long as it doesnt allow to use of the "Reviewed" status that blocks your attempts to fix a translation because of a tyrant's behaviour from the coordinator. ;)

I dont have/use discord, sorry about that. But i'm on irc channel on freenode as aztec2.

**Comment by Felipefpl** [comment]
I understand, are you one of the main devs that deal with translations? :)

**Comment by RedDevilus** [comment]
I try to be :P, i'd like to think i have some better experience with handling translations.

**Comment by Felipefpl** [comment]
Does my translation have any problem? I see it was submitted yet. :/

**Comment by RedDevilus** [comment]
The problem as already stated is that your translations target parts which do not exist or are moved since 1.6 , so they are already unmergeable at this moment, this is why we wait till weblate is here so you can transfer your work to there.

**Comment by Felipefpl** [comment]
i see, good to know, although it kinda worries me that i cant send files to weblate, at least not the one where i'm a translator.

**Comment by RedDevilus** [comment]
Because it's not available yet for translators, hence translators wait.
