### ISSUE TITLE
Valkyrie Profile 2: Silmeria warp animation

### ISSUE THREAD

**Issue by seuvah** [PCSX2/pcsx2#4349]
**Describe the bug**
Broken transition effect when entering a battle

**To Reproduce**
Boot game and enter a battle. Top left corner of screen will appear lightly colored.

**Expected behavior**
A battle transition effect typical of many JRPGs of this era. 

**GS Settings**
Default

**Emulation Settings**
Default

**GS Window Screenshots**

**System Info (please complete the following information):**

Windows 7
AMD FX8350 
GTX 1050 TI

**Logs and Dumps**

**Comment by F0bes** [comment]
My apologies but it seems like you haven't filled in the template. If you could, could you edit your original post. Thanks.

**Comment by seuvah** [comment]
> My apologies but it seems like you haven't filled in the template. If you could, could you edit your original post. Thanks.

first time posting i am sorry

**Comment by seuvah** [comment]
With https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=609103#pid609103 after deleting actual cheats game runs perfect and looks NICE, only that warp effect is incorrect. Not big deal, but if anyone can fix it that will be nice. After hours reading and watching videos all builds have that issue.

**Comment by tadanokojin** [comment]
Are you saying the game is broken with or without the deinterlace patch or both.
Which renderer?

**Comment by seuvah** [comment]
> Are you saying the game is broken with or without the deinterlace patch or both.
> Which renderer?

Oops forgot https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?page=345 this one fixes many stuff
+  https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=609103#pid609103
GSDX 19.25 SSE4.1/AVX 1.2.0

**Comment by seuvah** [comment]
https://youtu.be/jhaEMaBG5wQ?t=407 --- video describe the issue
https://youtu.be/cmuHprgHvKQ?t=927 -- this is how warp should look

**Comment by tadanokojin** [comment]
There's a lot going on here.

> https://youtu.be/jhaEMaBG5wQ?t=407 --- video describe the issue

This video is clearly using a hacked or old version of GSdx which removes the post processing. So obviously that effect isn't going to work properly. Notice how the forest isn't red like it's supposed to be either.

> Oops forgot https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?page=345 this one fixes many stuff
with https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=609103#pid609103

Does it work without the patches?

> GSDX 19.25 SSE4.1/AVX 1.2.0

This doesn't really tell me anything. I take it this works in SW mode based on the video you posted but is an issue in HW mode? Is this 1.6.0?

**Comment by seuvah** [comment]
Does it work without the patches?
No

This doesn't really tell me anything. I take it this works in SW mode based on the video you posted but is an issue in HW mode? Is this PCSX2 1.6.0?
Yes 1.6.0 
In SW mode works fine, in HW no

**Comment by tadanokojin** [comment]
Okay thanks for bringing it to my attention. I took a look at it and it appears to be a legitimate bug, unfortunately it's one that's going to be a pig to fix.

**Comment by seuvah** [comment]
Also effect bugged while entering battle - Silmeria <---> Alicia transictions, i think they are same effects because i checked on my old ps2 =) looks same blur scatter . I read someone mentioned that "potentially the issue comes from the internal resolution of the RT (128x64 or maybe smaller). So upscaling can generate really big glitches."). Sry for bad english ...

Thanks everyone who made this emulator. Currently playing 3 games VP: Silmeria(only one bug), Wild arms 5 (0 BUGS) =) looks GREAT and sounds GREAT and Breath of Fire: Dragon Quarter also 0 BUGS sounds and looks GREAT.

**Comment by trostboot** [comment]
Probably won't make any difference for looking into it, but if you trigger the photon warp effect in SW mode and switch to HW mode, the framebuffer copy produced in SW mode will be applied the next time you trigger it in HW mode. It will be wrong as it's not updated, but the effect itself seems to mostly work in HW.

**Comment by seuvah** [comment]
> Probably won't make any difference for looking into it, but if you trigger the photon warp effect in SW mode and switch to HW mode, the framebuffer copy produced in SW mode will be applied the next time you trigger it in HW mode. It will be wrong as it's not updated, but the effect itself seems to mostly work in HW.

Done that, it makes  whole screen with artifacts when warping or entering battle

**Comment by seuvah** [comment]
In Radiata strories game similar effect emulates normally when entering battle.

**Comment by BParks21** [comment]
Teleporting when hitting an enemy twice with the photon crystals dims the screen in HW mode as well. The screen does not dim when teleporting with the photons in SW mode. Might be a separate  issue though.

**Comment by stenzek** [comment]
Should've been fixed by #8114. If it's still happening, we can reopen.
