### ISSUE TITLE
Build failure on Arch Linux, wx related

### ISSUE THREAD

**Issue by alucryd** [PCSX2/pcsx2#435]
Hi guys,

pcsx2 has failed to build for a couple of days on Arch Linux, seems to be wx related. Build log here: https://paste.xinu.at/mB6hH/

Can you make something of it?

Cheers.

**Comment by gregory38** [comment]
Did you use this option:
-DCMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake

**Comment by alucryd** [comment]
No, I'm exporting CC='gcc -m32' and CXX='g++ -m32', is "-DCMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake" the right way to do it?

FTR, my PKGBUILD is here: https://aur.archlinux.org/packages/pc/pcsx2-git/PKGBUILD

**Comment by gregory38** [comment]
I think you must replace the export with the new cmake option. The -m32 option don't tell cmake where to look for 32 bits header.

**Comment by alucryd** [comment]
Dropping all the exports and adding the toolchain line did the trick, thx a lot! Also thx for the heads up about WX28_API.
