### ISSUE TITLE
Xbox 360 Wireless Controller doesn't work on PCSX2 v.1.7.0-dev-1170 on Linux

### ISSUE THREAD

**Issue by barfin** [PCSX2/pcsx2#4354]
I always used to change the PAD plugin to a legacy one to make it work, but now I see no plugin selector, it only lets me choose the GS plugin and there is no way to make my gamepad work again
it doesn't remap in PAD configuration at all

**Comment by lightningterror** [comment]
What is the issue with the current controller, does it not pick it up at all, can you post the console log?
It should automatically pick up the controller without any configuring since it's plug and play, with that said in the future we will bring the and unify the missing features between linux and windows.

**Comment by barfin** [comment]
> What is the issue with the current controller, does it not pick it up at all, can you post the console log?
> It should automatically pick up the controller without any configuring since it's plug and play, with that said in the future we will bring the and unify the missing features between linux and windows.

can't you just bring back the old plugins and old plugin selector menu? i used to change the PAD plugin and it worked perfectly
why would devs fix something that's not broken?

`PCSX2 1.7.0-20210405044504 
Savestate version: 0x9a1e0000

Host Machine Init:
	Operating System =  Linux 5.11.11-zen1-1-zen x86_64
	Physical RAM     =  11915 MB
	CPU name         =  Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  3.488 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbff
	x86EFlags        =  2c100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	Pcsx2 was compiled as 64-bits.

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins from /usr/lib/PCSX2...
	Bound   GS: libGSdx-AVX2.so [GSdx 64-bit (GCC 10.2.0 AVX/AVX) 1.2.0]
Plugins loaded successfully.

[GameDB] 10363 games on record (loaded in 228ms)
`

**Comment by kenshen112** [comment]
How are you connecting the 360n controller. Are you doing it wirelessly or is it one of the ones that can be plugged in? And the controls don't respond when you're in-game? Doesn't matter if the OnePad configurator sees them or responds

**Comment by barfin** [comment]
> How are you connecting the 360n controller. Are you doing it wirelessly or is it one of the ones that can be plugged in? And the controls don't respond when you're in-game? Doesn't matter if the OnePad configurator sees them or responds

I use it wirelessly with a receiver 
`Bus 002 Device 002: ID 045e:0291 Microsoft Corp. Xbox 360 Wireless Receiver for Windows`
and now that i tried it in game it works but lack of keymapping still bothers me and i need it, check out this video to see how it used to work in older version (1.6.0)
https://www.youtube.com/watch?v=F7t1wGCKsZc

**Comment by kenshen112** [comment]
We know :) It's a feature that was taken away by nonlegacy OnePad in favor of automapping like you just experienced for the sake of ease of use in that it's just pick up and go. That being said we also understand there's been concerns and desires for it to be restored. And it may be in the future.

**Comment by Squall-Leonhart** [comment]
sounds more like the linux support for 360 controllers is lacking, is the receiver supported properly by xpad?

**Comment by Neirda24** [comment]
Can this be re-opened ? I have the same issue with the mac version. My pad is not auto-mapped and I cannot manually do it. Plus it crashes when I try to do the manual mapping. Using 1.7.0-dev on mac with xbox serie wireless

**Comment by lightningterror** [comment]
> Can this be re-opened ? I have the same issue with the mac version. My pad is not auto-mapped and I cannot manually do it. Plus it crashes when I try to do the manual mapping. Using 1.7.0-dev on mac with xbox serie wireless

What does the log say, that a mapping isn't present?

**Comment by Neirda24** [comment]
I'm actually trying to generate an error log but it stays muted... To reproduce : I install it through Romstation  with the basic configuration it provides. I just tried to mapped my wireless controller (which work without any problem through dolphin for example) to PCSX2 but it's not detected. What's weird is that when I click on Gamepad Configuration it is found and says : `Xbox One Serie X Controller`.

If you can provide me with a path to follow to generate the logs I'll provide them gladly.

**Comment by Neirda24** [comment]
When I press any button to configure it waits for my input. Which I provide on the controller but is not detected by PCSX2... So because it is waiting for my input the fan goes wild and mac ask if it should kill PCSX2 because it seems stuck. As soon as I click with the mouse it goes as the input for whatever mapping I was trying to set and restore PCSX2 to be "working" again... So I don't have any logs because it's like it isn't even detected... (software of the controller is up to date from today)

**Comment by lightningterror** [comment]
I'd fist recommend using the latest build provided by Tellow which is a week or two old, yours is a year old already.

**Comment by Neirda24** [comment]
> I'd fist recommend using the latest build provided by Tellow which is a week or two old, yours is a year old already.

Can you point me to the mac download ? Because I can't see any package to download for mac in Releases (github) and on pcsx2.net it seems even older...

**Comment by lightningterror** [comment]
https://forums.pcsx2.net/Thread-Native-Mac-Testing-Build

**Comment by Neirda24** [comment]
Ok thanks I had to extract all bios / plugins from the romstation install but it seems to work now. Awesome ;)
