### ISSUE TITLE
[BUG] Alone in the Dark 4 (SLES-50185) PCSX2 parse wrong screen values

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#4356]
**Describe the bug**

PCSX parse wrong screen values for this game, checking debugger 1.7 dev 1171 looks like smode2 and display2 values
have wrong values (PAL -NTSC gs register values as guide); meanwhile i corrected the values and create a .PNACH file documented with addresses changed Here: 
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=618873#pid618873
**To Reproduce**
run game, check PCSX2 tab for resolution, frame value tab, or check debugger > registers > GS (smode2 and display2)
**Expected behavior**
PAL 640x512i or NTSC 640x448i values

**GS Settings**
Default

**Emulation Settings**
Default

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7 dev 1171
 -   OS: windows 10 20H2
 -   CPU: Ryzen 5 3400g
 -   GPU: vega 11

**Logs and Dumps**

GS DUMP PALMODE https://drive.google.com/file/d/116YLci5NtSWOAAf6EwKdtfC5Vd8m2znE/view?usp=sharing
GS DUMP NTSCMODE https://drive.google.com/file/d/15UWI5l3OKeqFopYdpCdzKoBifc_ZkGzN/view?usp=sharing

**Comment by tadanokojin** [comment]
You sure it's the wrong setting?

It's not completely unheard of to use non-standard resolution for the display registers. The PCRTC usually can figure out how to stretch it into the screen.

Can you send a screenshot of the values? I'll confirm it with a test later.

**Comment by felixthecat1970** [comment]
i think (still learning about GS), this game selecting NTSC 60HZ  main menu game screen misplaced above, videos misplaced below PAL50 mode videos too,  on my test PAL games not activate progressive mode on play that was my concern looking PCSX2 window tab (resolution also seems weird but i see this in couple of titles with similar odd resolutions with correct image ) , looking values of GS register i see this game SMODE2 and DISPLAY2  looks diferent comparing PAL common values in general of SMODE1, SRFSH, SYNCH1, SYNCH2 (using GSM source code and official games values ) here this are the values i think game look ok, like others titles; 

![image](https://user-images.githubusercontent.com/12580269/114224719-0e791780-9937-11eb-8479-f8df7b1356b8.png)

**Comment by tadanokojin** [comment]
Okay, well I appreciate you patching the game to make it look okay but I'd like to understand what the game is doing.
I don't think the values are wrong so to speak as much as I think the way GSdx is interpreting those values is wrong. It may be true that the values are strange but I'm willing to bet it works on a real PS2 and I can test that it does.

We make a lot of assumptions about the way PCRTC works (most are incorrect in [edge cases such as these](https://github.com/PCSX2/pcsx2/discussions/4107)) so when I see an abnormal case like this, I want to know what the values are.

So I'm asking you to give me the values the game uses (not the ones you patched into the game). I can get them myself from the dumps but it's easier just to ask.

I hope you can understand me friend.

**Comment by felixthecat1970** [comment]
yes, of course, i making a lot of guessings using patterns with values of many games, homebrew source code for grasp some logic, this game take my attention because SMODE2 value is "2" nor "1 or 3 common values" modify this value and DISPLAY2 to common values fix this game screen problems, thinking maybe i make assumptions how PS2 work internally;  i find another PAL game "Gunbird special edition" have same value SMODE2 "2" (enable progressive mode) running in PAL, but screen looks ok; i change  to "common" values and game look same; so, for no extend more, this is the addreses with original values i find to fix screen values: 

2064C778 00000002 //SMODE2
2064C7A0 00000002 

204AC608 02048290 //DISPLAY2
204AC60C 001BF9FF   
204AC630 02048290   
204AC634 001BF9FF   
2064C788 01824290   
2064C78C 0011F9FF   
2064C7B0 01824290   
2064C7B4 0011F9FF
