### ISSUE TITLE
Remote Control Dandy SF Open GL Hardware Graphics Bug

### ISSUE THREAD

**Issue by ThatDudeYouMetThatOneTime** [PCSX2/pcsx2#4357]
**Describe the bug**

Character models and mech models have significant missing chunks, become ghost-like, or can even disappear entirely, when using Open GL Hardware. Setting Blending Accuracy to "none" only seems to make the issue worse. Reducing the resolution to native does not fix the issue without switching to software mode. Also falsely displays all characters in vs mode as being unlocked even if you haven't beaten the game. Hovering over any of the icons for not yet unlocked characters will just make a question mark appear rather than having the model load.
**To Reproduce**

In any mode, versus, story, etc., make sure to have the renderer set to Open GL and leave it in Hardware mode to see the behavior.
**Expected behavior**
 I expected the character models to display normally with no missing parts. 

**GS Settings**
 3x native resolution (1080p), anisotropic filtering x16, enable hw hacks (align sprite, preload frame data)

**Emulation Settings**

**GS Window Screenshots**

![Remote Control Dandy SF (running in Open GL Hardware)](https://user-images.githubusercontent.com/81947301/113938457-a3113780-97c8-11eb-9dfe-68024466cc42.png)
![Remote Control Dandy SF (running in Direct 3D11 Hardware)](https://user-images.githubusercontent.com/81947301/113938473-a99faf00-97c8-11eb-81fd-74e5e32de095.png)
![gsdx_20210406121647 (Remote Control Dandy SF running in Open GL, blending accuracy set to none)](https://user-images.githubusercontent.com/81947301/113938492-b15f5380-97c8-11eb-9839-2065dab7d0bb.png)
![gsdx_20210406121632 (Remote Control Dandy SF running in Open GL Hardware)](https://user-images.githubusercontent.com/81947301/113938503-b58b7100-97c8-11eb-9999-6834259b578b.png)
![gsdx_20210406121621 (Remote Control Dandy SF running in Direct 3D11 Hardware)](https://user-images.githubusercontent.com/81947301/113938514-b91ef800-97c8-11eb-97d7-c4b3ba47465e.png)
![gsdx_20210406121042 (Remote Control Dandy SF running in Open GL Hardware)](https://user-images.githubusercontent.com/81947301/113938716-f8e5df80-97c8-11eb-84aa-60272a36a45d.png)
![gsdx_20210406120733 (Remote Control Dandy SF running in Open GL Hardware)](https://user-images.githubusercontent.com/81947301/113938738-fedbc080-97c8-11eb-8fc9-75b824490938.png)
![gsdx_20210406120801 (Remote Control Dandy SF running in Direct 3D11 Hardware)](https://user-images.githubusercontent.com/81947301/113938745-0307de00-97c9-11eb-8dc5-cb3ac6028539.png)

**System Info (please complete the following information):**
 -   PCSX2 Revision:  PCSX2 1.7.0-20210403224923 (git)
 -   OS:  Windows 10
 -   CPU:  i5-7400T
 -   GPU:  integrated GPU (not quite sure about specifics)

**Logs and Dumps**
 

[Remote Control Dandy SF Open GL Hardware Graphics Bug GS Dump.zip](https://github.com/PCSX2/pcsx2/files/6287510/Remote.Control.Dandy.SF.Open.GL.Hardware.Graphics.Bug.GS.Dump.zip)

**Comment by lightningterror** [comment]
Can this be retested, I am unable to reproduce the issues on the provided dumps.

**Comment by ThatDudeYouMetThatOneTime** [comment]
I just booted the game up in 1.7.0 version 2105. The issues seems to fixed now. It was actually fixed a fair while ago, I was just too lazy to report it, so sorry about that. I'm on Linux now, as my Windows install died since my original post, so I can not confirm this is fixed on Windows unless that's the OS you were using when trying to reproduce this. Here's some screenshots to show it looks like it is fine now:

![Screenshot from 2021-12-08 22-10-28](https://user-images.githubusercontent.com/81947301/145327963-02fb9973-2a55-4d5f-9ffb-99de90fd7033.png)
![Screenshot from 2021-12-08 22-15-03](https://user-images.githubusercontent.com/81947301/145328102-6359969c-d3c9-4fba-a385-62f1912a1855.png)
