### ISSUE TITLE
Question: Are Menu Icons Now Removed?

### ISSUE THREAD

**Issue by moulei** [PCSX2/pcsx2#436]
Hi,

In 1.2.2 there are two menu icons; ```System - Exit & Misc - About``` Last month when I compiled from git I noticed these were gone, have they been removed?

Also something I might of mentioned before, but the icons will not appear unless I have an ```icon-theme.cache``` file present in my icon folders.

I've only know of the ```icon-theme.cache``` file as something to increase performance and caching, not something that should be needed in order for icons to load.

thanks

**Comment by gregory38** [comment]
Well, I don't think it depends on us. We uses special wx id for those 2 entries. It is a bug/configuration of wx/theme. 

If wx only search icon in the cache, you are screw. I'm afraid nothing we can do.

**Comment by moulei** [comment]
Hi gregory38,

Sorry you lost me, so the 2 icons are still present in the latest git?

Also the icons should not need the  ```icon-theme.cache``` to load?

thanks

**Comment by gregory38** [comment]
PCSX2 doesn't ask for icon but for special wx entry. It is the job of wx to provide icon or not. Honestly I don't know, but wx might need icon-theme.cache. If it works with it, just provide it ;)

**Comment by moulei** [comment]
Ok...

I get two icons then, ```Exit``` & ```About```

Oh I made a mistake before updating gdk-pixbuf, this is why it was needing a icon-theme.cache.

Before I was running;
```gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache```

Then I realized I need to make it; (Since I'm on multilib)
```gdk-pixbuf-query-loaders-32 > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache```

So icon-theme.cache is not needed if anyone asks.
