### ISSUE TITLE
[BUG] Flipnic : Ultimate Pinball (SLUS-21157) hangs when starting the ufo shootdown mission

### ISSUE THREAD

**Issue by 77x5ghost** [PCSX2/pcsx2#4360]
**Describe the bug**
The game hangs when trying to start the UFO shootdown mission in the metallurgy stage
the FMV for the mission intro plays and then the entire game freezes

**To Reproduce**
go on metallurgy A or B and shoot the ball into the area where the arrow is pointing to start the said mission
![image](https://user-images.githubusercontent.com/20196206/114288932-ededb200-9a49-11eb-8372-5c1aa51754c2.png)

**Expected behavior**
after the FMV ends, the mission should start and the game should resume like normal

**GS Settings**
![image](https://user-images.githubusercontent.com/20196206/114288976-85530500-9a4a-11eb-8d7a-6c793692b7d8.png)

**Emulation Settings**
Safe preset

**System Info (please complete the following information):**
 -   PCSX2 1.7.0-dev-1187-g6cc969a89
 -   OS: Windows 10 x64
 -   CPU: Intel Core i3-6300
 -   GPU: AMD RX 560

**Logs and Dumps**

https://drive.google.com/file/d/1irBC8q3VN1rxYJJIZ1whpjynbvkzwKCU/view?usp=sharing

**Comment by MrCK1** [comment]
Can reproduce on my end. 1.7 savestate for testing as well (rename to .p2s)
[SLUS-21157 (EADDB48E).00.zip](https://github.com/PCSX2/pcsx2/files/6291049/SLUS-21157.EADDB48E.00.zip)

**Comment by atomic83GitHub** [comment]
I suggest testing various clamping/rounding values as well as trying individually every hacks presents in the hack section before going further in the report.

**Comment by 77x5ghost** [comment]
> 
> 
> I suggest testing various clamping/rounding values as well as trying individually every hacks presents in the hack section before going further in the report.

i've tried what you've said and the issue still persists

**Comment by kozarovv** [comment]
First game hang on IPU_FROM CHCR check loop. Expecting STR to be 0, which never happen. 
After noping that, game loop again checking IPU_CTRL to be not less than zero (so check busy bit if i understand correctly) which also don't happen (0x81703F00).
Nop on that check bring us to another IPU_CTRL check like before. Finally nop on that check allow game to proceed. 

Probably the same thing that affected JPN version of game.

**Comment by prafullpcsx2** [comment]
@77x5ghost 

Can you try this patch file and report if the problem is fixed? Unzip the file in cheats folder and make sure you have cheats enabled.

[Flipnic - Ultimate Pinball [SLUS 21157] (U).zip](https://github.com/PCSX2/pcsx2/files/6292696/Flipnic.-.Ultimate.Pinball.SLUS.21157.U.zip)

Also if possible check game for possible other bugs due to this patch.

**Comment by 77x5ghost** [comment]
> 
> 
> @77x5ghost
> 
> Can you try this patch file and report if the problem is fixed? Unzip the file in cheats folder and make sure you have cheats enabled.
> 
> [Flipnic - Ultimate Pinball [SLUS 21157] (U).zip](https://github.com/PCSX2/pcsx2/files/6292696/Flipnic.-.Ultimate.Pinball.SLUS.21157.U.zip)
> 
> Also if possible check game for possible other bugs due to this patch.

the patch has fixed the issue
the only quirk i've noticed is that sound effects seems to randomly cut off after destroying the big ufo (flippers, bumpers etc)
but the quirk stops after the big ufo respawns back into the stage
other than that i haven't seen any other new bugs yet
