### ISSUE TITLE
[BUG] título Plugins Gsdx 64bits software mode crach

### ISSUE THREAD

**Issue by BinhoKof99** [PCSX2/pcsx2#4368]
When using PCSX2-x64 GSDX in Software mode, the application ends up closing when starting a title

Os: Windows 10 64bits
CPU: I5 9400F
GPU: Geforce GTX 1060 3gb
RAM: 16gb 2666 kingston

**Comment by F0bes** [comment]
Hi there, unfortunately, it seems like you haven't filled in the issue template. If you could edit your message with the request information that'd be greatly appreciated :).

**Comment by BinhoKof99** [comment]
When using PCSX2-x64 GSDX in Software mode, the application ends up closing when starting a title

Os: Windows 10 64bits
CPU: I5 9400F
GPU: Geforce GTX 1060 3gb
RAM: 16gb 2666 kingston

**Comment by F0bes** [comment]
Currently the software renderer does not work on Windows when pcsx2 is 64 bit.

If you need SW mode rendering I would build 32 bit instead or wait until it is fixed.

**Comment by tellowkrinkle** [comment]
64-bit status is at #4102, if you still have issues after that page indicates that 64-bit is ready for public use, please make a new issue
