### ISSUE TITLE
[BUG] Castlevania: Lament of Innocence frequent crashing

### ISSUE THREAD

**Issue by MikeChunko** [PCSX2/pcsx2#4375]
**Describe the bug**
Castlevania: Lament of Innocence will frequently crash, locking up the whole system with it and requiring a restart. The game becomes frozen on the most recent frame and my OS stops responding completely, not even being able to switch TTYs. Background audio from the game continues playing as normal despite this.

**To Reproduce**
Simply play the game for a short period of time. Crashes occurred at all stages of the game for me and anywhere from within 5 minutes of loading a save to 30 minutes at the upper end.

**Expected behavior**
The game should never crash.

**GS Settings**
All settings are set to "Preset 2 - Safe (Default)"
![image](https://user-images.githubusercontent.com/34099159/115168915-90311980-a08a-11eb-80a6-34ac3b5b5dce.png)

**Emulation Settings**
All settings are set to "Preset 2 - Safe (Default)"

**GS Window Screenshots**

**System Info (please complete the following information):**
 -   PCSX2 Revision: 256afa8b9dfa6b76845267e47314466b1f65a891
 -   OS: Manjaro Linux 5.11.6
 -   CPU: i7-8750h
 -   GPU: Intel integrated graphics

**Logs and Dumps**

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6332641/emuLog.txt)

**Comment by Ziemas** [comment]
This sounds more like a crash in the graphics driver, if game audio continues to play then PCSX2 is still running.

I'd suggest checking your system logs for errors or seeing if you can read `dmesg` output over SSH or something after the crash has occured and reporting a bug with Mesa/Intel.

**Comment by refractionpcsx2** [comment]
The github is not a support platform, please either visit the forums or the discord for help. Thanks
