### ISSUE TITLE
[BUG] Hardware registers filled with garbage

### ISSUE THREAD

**Issue by PrgmrAtHrt** [PCSX2/pcsx2#4379]
**Describe the bug**

The hardware registers are filled with a value (0x551B600C) and many zeros instead of the framebuffer information etc.

**To Reproduce**

Start a game. Open the debugger and go to 0x12000000 in the memory editor.

**Expected behavior**

The framebuffer and other register information should appear correctly. (See images)

**System Info (please complete the following information):**
 -   PCSX2 Revision: dev-1198
 -   OS: Windows 10

**Logs and Dumps**

Correct registers:

![Debugger 4_19_2021 2_57_39 PM](https://user-images.githubusercontent.com/38510213/115309763-91f9ec00-a121-11eb-95ef-97945786dd59.png)
Garbage registers:

![Debugger 4_19_2021 3_31_46 PM](https://user-images.githubusercontent.com/38510213/115311407-76dcab80-a124-11eb-9c81-507c98ff1578.png)

This is working fine for every build before commit https://github.com/PCSX2/pcsx2/commit/fa18568d62e5a3db4fabbb191845d8a85ffcedb9

**Comment by tadanokojin** [comment]
1198 should have a new tab under "registers"
![000265](https://user-images.githubusercontent.com/26046960/115311045-eb234900-a13c-11eb-85e6-0c13b9ebc532.png)

**Comment by PrgmrAtHrt** [comment]
Sorry, I took the image using an older build.

**Comment by tadanokojin** [comment]
The registers mapped at `0x12000000` are the registers in the new GS tab. So I don't really understand the issue. On the real EE if you tried to read anything other than CSR or IMR you'd get CSR so the memory being filled there with CSR is accurate behavior.

**Comment by PrgmrAtHrt** [comment]
I guess I was just confused by the change then.

**Comment by tadanokojin** [comment]
before:
GS priv registers are mapped to `0x12000000`
the registers mapped there return their respective values

fa18568:
GS priv registers are still mapped to `0x12000000` but almost all of them mirror reads to a single register (CSR)
this was done for accuracy reasons

later:
the registers are in the GS tab which bypasses this functionality so they can still be read
the registers are now labeled too

I hope this clears up any confusion.
