### ISSUE TITLE
[BUG] Enthusia Professional Racing (Japan) (SLPM_659.48) Freeze starting race

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#4386]
**Describe the bug**
Game crash / freeze starting race, tested default options and safe mode (safe mode random crash)

**To Reproduce**
start game > free race > try start race = freeze; other observations using BIOS full, cars has colored textures

**GS Settings**
Default

**Emulation Settings**
Default - Safe Mode

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7-1201 / 1.7-786 / 1.6 stable
 -   OS: Windows 10 20H2
 -   CPU: Ryzen 5 3400g
 -   GPU: vega 11

**Logs and Dumps**
GS dump and Blockdump here [https://drive.google.com/file/d/1DGRtZLjMloRzh0Vi5BtEGLVxzjVJEGuf/view?usp=sharing](url)

**Comment by atomic83GitHub** [comment]
I would like a savestate taken just before the issue happens please.

Don't forget to do it with the very latest dev build of pcsx2.

**Comment by felixthecat1970** [comment]
hello, here [https://drive.google.com/file/d/1r_Cmys7dzSwOWmBvuOmyuNtYZ_dg3dv8/view?usp=sharing](url)
apart a question, i made some .pnach files for games think is not neccesary anymore to have in crc hacks list, in "fixing unplayable games" thread in forums, developers look there or is neccesary do a "pull request" here? thanks, good day.

**Comment by prafullpcsx2** [comment]
Can you try setting VU Clamping to extra or higher to confirm that the game works correctly?

**Comment by felixthecat1970** [comment]
Tested againg with pcsx2 1.7 dev 1283 with option VUs>Clamping Mode>"Extra":
Game works ok, tested OGL/DX11/ software, main gameplay / free races play ok
looks like this version need this option enabled in "GameIndex.yaml"

SLPM-65948:
  name: "Enthusia Professional Racing"
  region: "NTSC-J"
  clampModes:
    eeClampMode: 3
    vuClampMode: 3 #required too
i consider this issue can be closed. (still doign some testing)
