### ISSUE TITLE
NetPlay Pugin Warped read bug?

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#439]
In the code for dev9ghzdrk, there is this section of code in tx_process() (at line 203 in smap.cpp)

```
if(base+pbd->length > 16384)
{
    u32 was=16384-base;
    memcpy(pk.buffer,dev9.txfifo+base,was);
    memcpy(pk.buffer,dev9.txfifo,pbd->length-was);
    printf("Warped read, was=%u, sz=%u, sz-was=%u\n", was, pbd->length, pbd->length-was);
}
```
which seems to be writing into the same area of pk.buffer twice.

I suspect that second memcpy is supposed to be `memcpy(pk.buffer+was,dev9.txfifo,pbd->length-was);`

**Comment by skmp** [comment]
Hum, yes, I'd say so. I remember writing that code and that it never quite
worked right, that would make sense.

On Mon, Jan 26, 2015 at 5:52 PM, TheLastRar <notifications@github.com>
wrote:

> In the code for dev9ghzdrk, there is this section of code in tx_process()
> (at line 203 in smap.cpp)
>
> if(base+pbd->length > 16384)
> {
>     u32 was=16384-base;
>     memcpy(pk.buffer,dev9.txfifo+base,was);
>     memcpy(pk.buffer,dev9.txfifo,pbd->length-was);
>     printf("Warped read, was=%u, sz=%u, sz-was=%u\n", was, pbd->length, pbd->length-was);
> }
>
> which seems to be writing into the same area of pk.buffer twice.
>
> I suspect that second memcpy is supposed to be
> memcpy(pk.buffer+was,dev9.txfifo,pbd->length-was);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PCSX2/pcsx2/issues/439>.
>



-- 
~skmp

**Comment by ramapcsx2** [comment]
Could just test the suggested fix, I suppose :p

**Comment by TheLastRar** [comment]
My test game was .hack//fragment
With the unmodified version the game would often disconnect.
With the modified version, after some brief testing I haven't experience any connection issues, so it seems the fix was an improvement.

If you want, I could post a build for other members of the fragment community to test.

**Comment by TheLastRar** [comment]
Without the fix, for 4 test runs, the time I stayed connected to a given area server was as follows
00:11:04
00:03:06
00:12:15
00:04:07
With the fix, 
The game did not disconnect, even after 1 hour and 20mins.

**Comment by ramapcsx2** [comment]
Thanks for testing a fix yourself! I meant to check this after exam time is over but this way is better :)
Closing the issue, we can use your PR for this.
