### ISSUE TITLE
[BUG] The History Channel: Battle for the Pacific - Graphical glitch

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#4396]
**Describe the bug**
The weapon has a broken texture on it or at least i think so

**To Reproduce**
Just start the game happens on DX11, open gl and software mode 

**Expected behavior**
no graphical glitch

**GS Settings**
Default

**Emulation Settings**
Default speed 2

**GS Window Screenshots**

![video](https://user-images.githubusercontent.com/5770076/115974563-b82eea00-a56e-11eb-8c3f-5a09d9a4c3f3.gif)

**System Info (please complete the following information):**
PCSX2 1.7.0-20210424200746 - compiled on Apr 24 2021
	Operating System =  Microsoft Windows 10 Pro (build 19042), 64-bit
	Physical RAM     =  10210 MB
	CPU name         =  Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
	Vendor/Model     =  1050 ti
	CPU speed        =  3.092 ghz (4 logical threads)

**Logs and Dumps**
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6370872/emuLog.txt)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/6370873/snaps.zip)

**Comment by prafullpcsx2** [comment]
You can fix this by opening gsdx.ini file and then changing this setting from 0 to 1 like given below:

clut_load_before_draw = 1

**Comment by atomic83GitHub** [comment]
Ouch, that shouldn't happen on the very latest master release. Please test it on latest dev-build and see if the issue is still there.

**Comment by Levan7** [comment]
@prafullpcsx2 
The clut_load_before_draw = 1 actually did the trick with the weapon texture 

@atomic83GitHub 
About testing if you want I can test it
