### ISSUE TITLE
Music dissapearing bug on Persona 3 FES

### ISSUE THREAD

**Issue by PrismWolfPup** [PCSX2/pcsx2#4398]
Sometimes the music just cuts out, like every other sound is still there, like footsteps and voiceacting but there is just no music. It only reappears when the music changes, like restarting the game doesnt even fix it, from what ive seen.

**Comment by refractionpcsx2** [comment]
Please fill out the template.

**Comment by lightningterror** [comment]
Closing as the template hasn't been properly filled out.
