### ISSUE TITLE
[BUG] Broken Hardware Graphics in Ford Racing 2 (Both D3D11 and OpenGL HW Mode)

### ISSUE THREAD

**Issue by NewMoonHD** [PCSX2/pcsx2#4400]
Describe the bug:
To simply put, when using hardware mode on DX11 or OpenGL in Hardware mode, broken shadows (excepted) and other weird glitches start to happen (when restarting the event as shown in Log and Dump) when playing the game (this also includes running at native res). Luckily, Software Rendering is safe from this mess. Note: 1.6.0 is also affected. Earlier versions of PCSX2 were even worse.

To Reproduce:
Simply Play Ford Racing 2 in Hardware Mode (for more glitches, restart the same event),

GS Settings:
![GSDx settings](https://user-images.githubusercontent.com/52108325/115999010-e0ced800-a59e-11eb-8e28-8b5c69a16851.png)

Emulation Settings
Safe (Default Settings)

System Info:
 -   PCSX2 Revision: 1.7.0 dev 1211
 -   OS: Windows 10 20H2
 -   CPU: AMD R7 2700
 -  GPU: AMD RX 580 (21.4.1)

Logs and Dumps:
[gsdx_20210425081358.gs.zip](https://github.com/PCSX2/pcsx2/files/6372302/gsdx_20210425081358.gs.zip)
![gsdx_20210425081358](https://user-images.githubusercontent.com/52108325/115999258-f690cd00-a59f-11eb-92d9-d5d95f3accae.png)

**Comment by lightningterror** [comment]
Duplicate #1982
