### ISSUE TITLE
[Feature Request] Relocate GameIndex.yaml to home directory by default or setting

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#4408]
Currently, `GameIndex.yaml` is installed to a system-wide directory by default; for example in Linux it is placed in `/usr/local/share/PCSX2` and referenced from there within the pcsx2 binary with no option to change it in `Config > Plugin/BIOS Selector > Folders`.

I'm guessing this was likely due to the static nature of the file, which seems logical enough - if the user is not expected to change it, why not make it system-wide?  However it is more easily referenced and managed from within the user's home directory as many other emulators do with such files, and is small enough that it shouldn't be an issue.  For example, RPCS3 stores its patch file in `~/.config/rpcs3/patches` by default.   At least, an option could be exposed to allow the user to put it there as are other similar files within the above settings menu.

**Comment by kenshen112** [comment]
GameIndex is kind of an enigma in this particular situation because it's supposed to be where the executable is in our portable builds meaning it's not a separate folder or anything like that. Because XDG Standard doesn't fully account for files like that we end up with them in this limbo folder like that. Namely, as you've mentioned GameIndex and cheats_ws on my end. It shouldn't be too difficult a fix though

**Comment by tadanokojin** [comment]
> However it is more easily referenced and managed from within the user's home directory

It's not meant to be referenced and managed from the user. It's not meant to be touched by the user at all. It's meant to be updated along with the application.

> For example, RPCS3 stores its patch file in ~/.config/rpcs3/patches by default

Different thing. [That's for custom patches not shipped with the emulator](https://wiki.rpcs3.net/index.php?title=Help:Game_Patches). PCSX2 has a equivalent of this with the cheats folder which is already configurable.

**Comment by Shoegzer** [comment]
Fair enough I guess.  I'm at least hoping for a method of relocating the file by option exposed to the user, such as to ease maintenance of portable installs.

**Comment by RedDevilus** [comment]
I'm not sure how the changed location of the GameIndex improves maintenance. You mean visually cleaner / looks more orderly?

**Comment by kenshen112** [comment]
Well we're never really going to do that persay because as kojin mentioned it's a file that's not really meant to be touched. When I mentioned earlier it was "an easy fix" I just meant making sure those file are being copied to a more correct folder rather than just dumped where they are currently

**Comment by tadanokojin** [comment]
> such as to ease maintenance of portable installs.

Could you expand on this please? Not a linux user myself but I don't see how being able to configure the location of this improves maintenance. Like for example PCSX2 has a number of resources that ship with the executable and are meant for that particular executable. If we say add or remove an option from the gamedb as it stores more than just patches then it might cause compatibility issues with a newer or older executable.

Is there some reason why you wouldn't just update the whole thing along with it? Or is this more you don't want the thing to be in a system directory and you want it jailed to a single user?

**Comment by Shoegzer** [comment]
@RedDevilus That too, but also there are certain circumstances such as portable installs where having all related files in one place is necessary.  

@tadanokojin Sure thing, portable installs allow for all application-specific files in a self-contained directory, so that for example you can launch pcsx2 from external storage such as removable media or network drive; or have multiple installs on one system for testing purposes.  Other emulators such as Dolphin support such methods, such as noted [here](https://github.com/dolphin-emu/dolphin#linux-portable-build-steps).  I hope that helps.  

In any event it can remain system-wide by default if the team feels strongly enough about keeping it that way (and I do see the reasons for that), but could the option at least be exposed to the user?

**Comment by tadanokojin** [comment]
I see, yeah Dolphin has something more akin to gamedb in it's `Sys/GameSettings` directory which is what I assume the copy of `Sys` is for in their instructions. We might be able to expose a compile flag which allows some of our resources to be referenced from the executable location exposed by a compile flag similar to what they have done.

I think more broadly you're asking for a way to do portable installs for linux which (feel free for linux people to correct me) is not a workflow we really handle right now.

**Comment by Mrlinkwii** [comment]
if you compile master  the `GameIndex.yaml` should be in the bin folder of the pcsx2 repo  , not `/usr/local/share/PCSX2`
![image](https://user-images.githubusercontent.com/17685135/116632598-737cc780-a94f-11eb-8f90-d66c556c4636.png)

**Comment by GovanifY** [comment]
So, according to our own codebase:

https://github.com/PCSX2/pcsx2/blob/7b9c8634f4544f6dda63a154b89745681ecbb98c/pcsx2/gui/AppConfig.cpp#L181

```
		// Each linux distributions have his rules for path so we give them the possibility to
		// change it with compilation flags. -- 
```

macro which is defined here:

```
cmake/BuildParameters.cmake:48:        -DGAMEINDEX_DIR_COMPILATION=${CMAKE_INSTALL_FULL_DATADIR}/PCSX2
```

and, in case that's not defined, it defaults to the path of the executable, eg in portable mode:

```
#elif !defined(GAMEINDEX_DIR_COMPILATION)
		return AppRoot();
#else
```

So either compile time flag, which works for packaging in distributions, or if not defined the application path, isn't that what you wanted? @Shoegzer

**Comment by kenshen112** [comment]
Shoe, are you using arch perchance?

**Comment by Shoegzer** [comment]
@GovanifY Actually yes that's exactly it.  More generally it seems leaving `PACKAGE_MODE` undefined will avoid full `LIBDIR`, `DATADIR` and `DOCDIR` paths, and GameIndex is therefore referenced in the binary path.  I'll close this issue as the feature I originally posted about was basically there all along.  Honestly I should have caught this sooner myself - sorry for wasting anyone's time.

That said, what is needed to build a truly portable instance that also includes other user generated files (e.g. memcards) in the binary path?  Currently if `XDG_STD` is undefined, it defaults to ~/PCSX2, otherwise it defaults to ~/.config/PCSX2.  

@kenshen112 I do most testing with Linux Mint.

**Comment by GovanifY** [comment]
> That said, what is needed to build a truly portable instance that also includes other user generated files (e.g. memcards) in the binary path? Currently if `XDG_STD` is undefined, it defaults to ~/PCSX2, otherwise it defaults to ~/.config/PCSX2.

Can't you just run `XDG_CONFIG_HOME=/my/folder PCSX2` ?

**Comment by kenshen112** [comment]
So, by default if you just don't provide any extra flags when compiling pcsx2 will build in portable mode. You'll find in in the bin folder with the entire folder structure

**Comment by Shoegzer** [comment]
@GovanifY ah right, I didn't see that option earlier but that sounds like it should work, thanks.

@kenshen112 I just built pcsx2 with only `CMAKE_BUILD_TYPE=Release` (which doesn't have to do with portable mode right?) and the resulting binary looks for config files in ~/PCSX2.  What am I missing?

**Comment by kenshen112** [comment]
In the resulting bin folder. Is there a portable.ini file?

**Comment by Shoegzer** [comment]
Ah, right.  There isn't one by default but you can create it, and that does cause the binary to look for the config files in its path.  Dolphin does the same thing with `portable.txt`.  What triggers the build process to be create the file automatically though?

**Comment by kenshen112** [comment]
https://github.com/PCSX2/pcsx2/blob/master/bin/portable.ini - The file always exists in bin. If it doesn't you somehow deleted it

**Comment by Shoegzer** [comment]
Thanks, you're right, I was looking in the wrong bin folder.
