### ISSUE TITLE
[BUG] Dualsense controller not recognized (Linux)

### ISSUE THREAD

**Issue by kamkamkamkamkamkamkamkam** [PCSX2/pcsx2#4420]
when I open OnePad configuration, I get this in the logs
![image](https://user-images.githubusercontent.com/65249472/117172186-8e10cf80-ad99-11eb-85b6-a2933c26cebe.png)
and when I click GamePad Configuration, it tells me "No gamepad detected"
![image](https://user-images.githubusercontent.com/65249472/117172332-b8fb2380-ad99-11eb-8636-58b24bf3a60b.png)

**Comment by qurious-pixel** [comment]
DualSense is in the gamepad list. [Your ID](https://github.com/PCSX2/pcsx2/blob/8760214817c24a9f01932f08970f6ae9339b5171/pcsx2/PAD/Linux/res/game_controller_db.txt#L456) 
Check to make sure you are using SDL2 version 2.0.14 (the first version with DualSense support on Linux). 
[SDL2 Download Page](https://www.libsdl.org/download-2.0.php)

**Comment by kamkamkamkamkamkamkamkam** [comment]
It turns out the version I was using was outdated even though I downloaded it a week ago, apparently the (official?) flatpak version of pcsx2 is out of date. https://flathub.org/apps/details/net.pcsx2.PCSX2 I installed a more recent version from my distro's repository and it works fine now.
