### ISSUE TITLE
[Feature Request] Automated sorter and inserting new serials into GameDB

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4434]
**Description**

A way to type in a serial in a box: ex. `SCUS-12345` which then checks if the serial already exists.
It looks on redump if it's a valid entry and gives a pop-up that it's possible not valid.
Finally it will place the serial in the correct location (being chronologically) and appends the correct prefixes/arguments like the name and region
Valid:
```
SLES-50562:
  name: "Super Bust-A-Move 2"
  region: "PAL-M5"
```
**Reason**

Less triple or quadruple checking if the entry is valid and not make mistakes if it's SLES/SCES, or put in wrong location or even the wrong indentations. It's very labor-intensive and you got to keep sustained focus. Basically you got to be a monke to do lots of new entries.
**Examples**

I made a google form for DobieStation to let people insert serials even if they don't have write access, it pipes what they gave information about in a seperate tab.
![image](https://user-images.githubusercontent.com/24227051/117987368-b456e200-b33a-11eb-8d56-04278b6edb9f.png)

![image](https://user-images.githubusercontent.com/24227051/117987275-9db08b00-b33a-11eb-9ec5-606f346da25b.png)

For example just browsing the dobie compatability, i already found an entry not on the list:
![image](https://user-images.githubusercontent.com/24227051/117987764-157eb580-b33b-11eb-95e4-13e8bf94a421.png)

https://docs.google.com/forms/d/e/1FAIpQLSe0F1i-1jJtdpyN7nVSCwnhsQz8rDtlr_F06fPBRZWw_7YwoQ/viewform

It could go nicely with https://github.com/PCSX2/pcsx2/pull/4418

**Comment by RedDevilus** [comment]
Qt will show serials that have no region, effectively making it easier to scan all your games and see which ones haven't been added. So it's better than launching per-game and checking program log/console and seeing only this:
![image](https://user-images.githubusercontent.com/24227051/152259377-59e374ba-a3af-43c8-8fd5-ac352f333845.png)



Example (look at the question marks for region flag):
https://github.com/PCSX2/pcsx2/pull/5460
![image](https://user-images.githubusercontent.com/24227051/152259450-d341a9a2-edc7-4958-b6e1-a7b7f9232008.png)

So whilst it's not something like a redump or other database inserter, it does partial fix this issue.

**Comment by Florin9doi** [comment]
[14_PS2.txt](https://github.com/PCSX2/pcsx2/files/8062096/14_PS2.txt)

**Comment by RedDevilus** [comment]
Might be a good idea to think about an automated process for new entries (or even wrong entries) just like how it's handled on the SDL side:
https://github.com/PCSX2/pcsx2/pull/5526

**Comment by Mrlinkwii** [comment]
as mentioned this is kinda sorted with QT ,  the User will see the unknown disc either prompting themselfs to fix it in the gamedb or going to the likes of the forums/discord letting people know

**Comment by lightningterror** [comment]
> Might be a good idea to think about an automated process for new entries (or even wrong entries) just like how it's handled on the SDL side: #5526

It works for sdl because it's not maintaining the controller db and we just fetch it, you still need someone modifying db entries, current state is fine as it is.

**Comment by RedDevilus** [comment]
Relevant PR incoming
