### ISSUE TITLE
[Feature Request] Automatic BIOS selection depending the game's region.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4441]
**Description**

Currently, in PCSX2 you can only select one bios at time to play your collection of PS1/PS2 games regardless of if they are NTSC or PAL.

While fast boot "could" be considered a solution, this have it's subset of issues including, PS1 compatiblity.

**Reason**

It's impossible to play PS1 games from 2 different regions without changing the bios consistently, same thing applies to the PS2 games running with full boot.

This feature request can be seen as a "Quality of Life" improvement.

**Examples**

In duckstation the feature is fully implemented, the emulator ask you 3 different bios for each regions.

When starting a game, it will automatically select the correct BIOS to use depending the game's region, this might seems trivial, but it can be considered as a end user improvement.

![image](https://user-images.githubusercontent.com/26351275/118402746-8f7caa80-b66b-11eb-8a99-35f7973cb3c3.png)

**Comment by lightningterror** [comment]
Closing as majority of users will have one bios anyway, idea is niche and it's for ps1 mode which is experimental.

**Comment by checktext00** [comment]
I also would like to see this implemented, for some games I have a European version and for some games a US version, so I have to manually switch BIOS in the settings unless I use `Fast Boot` (which I don't like to use)
