### ISSUE TITLE
[Feature Request] HDD fixed 100% allocation

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4443]
**Description**

Dynamically allocation of HDD file or compress unused space. Not allocate all specified HDD space at creation.
**Reason**

There is an active PR that will increase the minimum of HDD size from 8 GiB to 40 GiB. Some games expect atleast this amount but for normal endusers this is wasted space if you only use to about 10 GiB. So if the enduser only uses about 9 GiB then it should grow from 8 GiB to 12 GiB , if the user uses 10.5 Gig it grows to 16 GiB, etc. Another method could be to change existing HDD files manually if needed.

In essence:
- Game won't nag about not enough space.
- End-users doesn't need to make more space on their OS and/or create new HDD file.
- Almost no wasted space.

**Examples**

VMWare method (dynamically allocation or the growth by certain amount):
![image](https://user-images.githubusercontent.com/24227051/118415203-5d8a3900-b6a9-11eb-8a9b-4e6a0ed7709a.png)

**Comment by tadanokojin** [comment]
I think it might be a better idea to use sparse files:
https://docs.microsoft.com/en-us/windows/win32/fileio/sparse-files

I think linux supports it too. Only issue is you interface with an OS api.

**Comment by qurious-pixel** [comment]
Linux does support sparse files, but there are some filesystems that do not, such as FAT, i.e. ExFat.

**Comment by tellowkrinkle** [comment]
AFAIK linux and macOS will make a sparse file if your filesystem supports it if you resize with `ftruncate`, no need to do anything special

Alternatively, you can seek to the end and write a byte (something we already do... before writing zeros over the middle section)

**Comment by RedDevilus** [comment]
Maybe something similar to how provisioning works in virtualisation?

```
Thin: Allocate and zero on first write
Thick Lazy: Allocate in advance and zero on first write
Thick Eager: Allocate and zero in advance
```

**Comment by TheLastRar** [comment]
I didn't actually know about the OS api's for sparse files.

Windows doesn't automatically deallocate when zeros are written (and will allocate when zero is written normally), you have to use the ``FSCTL_SET_ZERO_DATA IOCTL`` instead.
Does linux have a similar requirement?
And do we even need to care about that? as erased files probably won't be zeroed anyway.

Is is possible to determine if the filesystem supports sparse files on linux (windows has ``GetVolumeInformation()``)
I note that ``ftruncate`` states that the extended part of the file is nulled. https://man7.org/linux/man-pages/man3/ftruncate.3p.html. What happens on filesystems that don't support sparse files, does this cause the OS to zero-write the file?

**Comment by tellowkrinkle** [comment]
> Does linux have a similar requirement?

Yes.  [On Linux that's an fallocate with `FALLOC_FL_PUNCH_HOLE`](https://www.man7.org/linux/man-pages/man2/fallocate.2.html), on macOS, it's `fcntl` with `F_PUNCHHOLE`.  FreeBSD does not currently support this [but it may support it soon](https://reviews.freebsd.org/D28347).

> What happens on filesystems that don't support sparse files, does this cause the OS to zero-write the file?

It does on macOS, and I assume it does on Linux as well.  The hole punching operations fail on unsupported filesystems.

**Comment by AKuHAK** [comment]
It is also possible to add ps3 Virtual HDD image support (IMAGE.DAT)
https://www.psdevwiki.com/ps3/PS2_Emulation#Virtual_PS2_HDD
This is a ps2 HDD 1-to-1 copy except for one fake partition (`__extended`) which is placed after all partitions, fills the whole disk, and is cut just after the header. This allows using smaller images. E.g. Nobunanga Online Image.dat is only 8Gb in size.

This type of disks can be adopted into the current HDD implementation.
The disk size should return for games `40Gb` even if the HDD image is smaller than 40Gb (or real size if the image size is larger).
If a new game is installed, virtual size is extended, then `__extended` partition is removed, a new partition is installed, `__extended` partition returned.

**Comment by TheLastRar** [comment]
> It is also possible to add ps3 Virtual HDD image support (IMAGE.DAT)

At this point in time, I'm not planning on adding the necessary infrastructure to inspect/manipulate partitions, as seems to be needed for the MAGE.DAT format.

> Yes. [On Linux that's an fallocate with `FALLOC_FL_PUNCH_HOLE`](https://www.man7.org/linux/man-pages/man2/fallocate.2.html), on macOS, it's `fcntl` with `F_PUNCHHOLE`. FreeBSD does not currently support this [but it may support it soon](https://reviews.freebsd.org/D28347).

Where is the documentation for F_PUNCHHOLE? I've been unable to find any.

**Comment by tellowkrinkle** [comment]
> Where is the documentation for F_PUNCHHOLE? I've been unable to find any.

It's in the macOS manpage but I can't find it online (and don't know what version it was added in)

> `F_PUNCHHOLE` Deallocate a region and replace it with a hole. Subsequent reads of the affected region will return bytes of zeros that are usually not backed by physical blocks. This will not change the actual file size. Holes must be aligned to file system block boundaries. This will fail on file systems that do not support this interface.
> 
>  The `F_PUNCHHOLE` command operates on the following structure:
> ```
> typedef struct fpunchhole {
> 	u_int32_t fp_flags;     /* unused */
> 	u_int32_t reserved;     /* (to maintain 8-byte alignment) */
> 	off_t     fp_offset;    /* IN: start of the region */
> 	off_t     fp_length;    /* IN: size of the region */
> } fpunchhole_t;
> ```

**Comment by TheLastRar** [comment]
I did manage to find a copy of the relevant header, but I thank you for giving me the manpage entry
