### ISSUE TITLE
Black NTSC - SLUS-21376 - black sky/no sky texture

### ISSUE THREAD

**Issue by Tarkin22** [PCSX2/pcsx2#4447]
**Describe the bug**
There is problem with sky texture rendering, because it isn't working as it should and whole sky is just black.
![image](https://user-images.githubusercontent.com/84533020/119021104-501dc900-b99f-11eb-85ff-fcb39bb78c0b.png)

**To Reproduce**
Simply start the game, this bug effects all levels in the game

**Expected behavior**
Sky shouldn't be black, even with game title like this (seriously, I thought it's feature and intendent effect). Screenshot from gameplay video from YouTube.
![image](https://user-images.githubusercontent.com/84533020/119021163-5f047b80-b99f-11eb-8fe4-4d6bb756e36f.png)

**GS Settings**
![direct3d11](https://user-images.githubusercontent.com/84533020/119021416-b3a7f680-b99f-11eb-92c9-7711ce22aa47.jpg)
![opengl](https://user-images.githubusercontent.com/84533020/119021419-b4408d00-b99f-11eb-8112-ad92bae0911d.jpg)
![pcsx2_CoreSettings_GS](https://user-images.githubusercontent.com/84533020/119021424-b4d92380-b99f-11eb-9a3a-b9e46945216f.png)
I also tried disabling internal resolution to default, but problem is still here. Both OpenGL and Direct3D11 are causing problem.

**Emulation Settings**
Default

**GS Window Screenshots**
![pcsx2_CoreSettings_GS Window](https://user-images.githubusercontent.com/84533020/119021422-b4408d00-b99f-11eb-8b50-c25b22764fd9.png)

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7.0-dev-1262
 -   OS: Windows 10 20H2
 -   CPU: AMD Ryzen 5 2600
 -   GPU: GTX 1080

**Logs and Dumps**

**Comment by refractionpcsx2** [comment]
This is already being tracked in #563
