### ISSUE TITLE
Rare bug causing pcsx2_ui.ini or pcsx2_vm.ini writes to fail

### ISSUE THREAD

**Issue by ramapcsx2** [PCSX2/pcsx2#445]
Very rarely the rename step when updating these 2 files will fail, leaving configuration changes uncommitted and producing half renamed .tmp files like "PCS2EDA.tmp" and "PCS8462.tmp" in the ini folder.

After trying for a while, I got the bug once. This is the PCSX2 error message:

```
[wx] can't remove file 'F:\bin\inis\PCSX2_ui.ini' (error 5: access denied)
[wx] Failed to update user configuration file.
```

The process leaves the orphaned .tmp file in the ini folder.
We could at least handle that better. (Delete it?)

**Comment by avih** [comment]
What's this "rename"? when does this rename happen? anything remotely close to steps to reproduce?

**Comment by gregory38** [comment]
Was it on 2.8 or 3.0?

**Comment by gregory38** [comment]
@turtleli if you want to look at it (but it is really low priority)

**Comment by turtleli** [comment]
That stuff happens from within the wx code - wxTempFile::Commit() fails and doesn't delete the file (which is generally a good thing).

Could probably be solved by deriving from the wxFileConfig class, overriding the flush method and deleting/prompting/doing something about the files (if anyone wants to do it).

**Comment by atomic83GitHub** [comment]
Is it still active? I never had this problem with 1.5dev builds.

**Comment by lightningterror** [comment]
It should be an issue and I don't think anyone looked at it yet.

**Comment by seta-san** [comment]
Is this still wx code?

**Comment by refractionpcsx2** [comment]
No reply in ages, no other reports.
