### ISSUE TITLE
Dai-2-Ji Super Robot Taisen Alpha [NTSC-J] [SLPS-25228] rumble doesn't work

### ISSUE THREAD

**Issue by yyhhrr** [PCSX2/pcsx2#4463]
When I click on test in the add force feed back function in the gamepad setting, the gamepad can rumble, but when I enter the game, the gamepad does not rumble.Anyone can reproduce this problem?

**Comment by RedPanda4552** [comment]
Please update your issue to follow the appropriate issue template. If you need a reference, you can hit "New Issue", copy the text from the appropriate template, and then add that to this issue. Thanks.
