### ISSUE TITLE
[Feature Request] Anisotropic Filtering in GSdx's OpenGL renderer

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#447]
Hi there! I'd just like to humbly request from any developer who has the skills (@Asmodean-) and interest to implement AF into GSdx's OGL renderer. The D3D11 renderer already has it so it might be easy to port it over, although I have no clue whatsoever.

Thanks in advance and good luck!

**Comment by gregory38** [comment]
Could you generate a gs dump where this parameter have an impact so I can test it.

**Comment by karasuhebi** [comment]
Sure no problem. Here's a .7z file with a gs dump, gs snap and two screenshots (AF off and AF 16x) I took with MSI Afterburner:
https://dl.dropboxusercontent.com/u/6425650/ffx_gs_dump_and_screenshots.7z

And here's the gs dump by itself:
https://dl.dropboxusercontent.com/u/6425650/gsdx_20150501143125.gs

**Comment by gregory38** [comment]
well you need to explain me the difference between the 2 screenshots :)

**Comment by Bigpet** [comment]
Same as all anisotrophic filtering. This screenshot doesn't do a very good job of showing it but if you look at the surfaces at an extreme angle to the camera you can still see it:

![af-noaf](https://cloud.githubusercontent.com/assets/465677/7439576/4fc2fe1e-f081-11e4-8ab3-babc21f5b645.gif)

This is a lot more visible in racing games, flight sims, etc

**Comment by gregory38** [comment]
Thanks for the info. It seems to work. 

I pushed the change, please give a shot and update this issue accordingly.

**Comment by gregory38** [comment]
@Bigpet I didn't see the animation the first time. It is really a good job to show the difference.
