### ISSUE TITLE
[Feature Request] Dark Mode for PCSX2 UI

### ISSUE THREAD

**Issue by Hartwelg** [PCSX2/pcsx2#4473]
**Description**

Dark mode for the PCSX2 UI. 

Dark mode would work over the whole UI. Every program window could be included in this change (options menus, console windows, main program window, configuration windows, etc.)
**Reason**

This is a feature that seems to be missing from the PCSX2 UI. Dark mode would be great for those of us who like to use Dark mode UI features in other programs, and it would be helpful for those who do not want to use a bright UI that could be harsh on the eyes.

This feature would make the PCSX2 UI easier on the eyes for many users.

Dark mode currently does not seem to be implemented in the PCSX2 UI, and it is a common feature in other pieces of software.

**Examples**

Dark mode is included in the Windows Explorer UI, Microsoft's Visual Studio IDE's, and even the Android UI.

**Comment by RedDevilus** [comment]
This will likely have to wait till PCSX2 goes from WX/Winapi/GTK etc to QT.
Dark mode is currently only limited to the console/program log.

**Comment by Squall-Leonhart** [comment]
> This will likely have to wait till PCSX2 goes from WX/Winapi/GTK etc to QT.
> Dark mode is currently limited only to the console/program log.

Dark mode can be implemented on Wx in a few lines of code.

**Comment by F0bes** [comment]
> > This will likely have to wait till PCSX2 goes from WX/Winapi/GTK etc to QT.
> > Dark mode is currently limited only to the console/program log.
> 
> Dark mode can be implemented on Wx in a few lines of code.

Could you pr this then?
