### ISSUE TITLE
[BUG] No support for SHANWAN Android Gamepad,GUID:03000000632500002605000010010000

### ISSUE THREAD

**Issue by silvasilas99** [PCSX2/pcsx2#4477]
Hello friends. I recently bought a multilaser gamer joypad , model theJS091, thinking about playing ps2 games with the emulator. I was super anxious with its arrival, and when I plugged it into the computer, opened the emulator, and it was already running GTA: SA, while I was going to configure the joystick, I realized that there was no support.
Note: I did some tests on jstest-gtk, and the joystick is really running smoothly, there's just no emulator support

That was the bug message:
```
onepad: Joystick (SHANWAN Android Gamepad,GUID:03000000632500002605000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (SHANWAN Android Gamepad,GUID:03000000632500002605000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.
```

![image_2021-06-03_132742](https://user-images.githubusercontent.com/49960425/120679371-79465b00-c46f-11eb-965c-3374b78cc1f4.png)

![image](https://user-images.githubusercontent.com/49960425/120679901-130e0800-c470-11eb-8676-0c9dbee09e08.png)

**Comment by RedDevilus** [comment]
I see this ID already on current file:
`03000000632500002605000010010000,HJD-X,a:b0,b:b1,back:b10,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b13,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b14,righttrigger:a5,rightx:a2,righty:a3,start:b11,x:b3,y:b4,platform:Linux,`

Could you try compiling from source?

**Comment by lightningterror** [comment]
It won't work on 1.6, needs 1.7 dev.
