### ISSUE TITLE
NBA 07 The Life: Vol 2 glitched crowd graphics

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4479]
**Describe the bug**
Crowd graphic are glitched. Visible when in the actual match, but the game work perfect ortherwise (no other graphical bugs seen)

**To reproduce**
Start a match in any mode

**Expected behavior**
Crowd is visible and glitch free on a real PS2

**GS Settings**
Default GS Settings

**Emulation Settings**
Default settings

**GS Window Screenshots**
![nba07](https://user-images.githubusercontent.com/24578279/120735389-89365d00-c4b8-11eb-9dc9-1d35f4f76426.PNG)

**System Info (please complete the following information):**
 -   PCSX2 Revision:  dev-1283
 -   OS: Windows 10 (lastest update)
 -   CPU:  i7-8700K 
 -   GPU:  NVIDIA GeForce RTX 2060 Super

**Logs and Dumps**

[gsdx_20210603221338.gs.zip](https://github.com/PCSX2/pcsx2/files/6595324/gsdx_20210603221338.gs.zip)

**Other information**

My personnal dump of the USA version

**Comment by F0bes** [comment]
I can't test the gsdump right now but does this happen in software mode? (Press F9 or change it in the gsdx settings dialog)

**Comment by Glitcholog** [comment]
Software mode (Direct X11) of PCSX2 doesn't have this problem. The crowd appear correctly like on the real PS2.

**Comment by atomic83GitHub** [comment]
It is worth mentioning that this is a bug that affects every "NBA the life" games.

**Comment by tadanokojin** [comment]
It's indeed a texture cache bug.

**Comment by prafullpcsx2** [comment]
It seems to be fixed on latest master by enabling Texture inside RT

![image](https://user-images.githubusercontent.com/12788199/221434323-8c4f8b13-2d9a-480e-9cbb-350269f81ce2.png)
