### ISSUE TITLE
[BUG] KimiKiss ebkore+ version

### ISSUE THREAD

**Issue by Mafu0567** [PCSX2/pcsx2#4480]
**Describe the bug**
Topic bubble rendering is incorrect in D3D11 hardware.

**To Reproduce**
Use hardware renderer in conversation with a girl.

**Expected behavior**
Topics should look like thought bubbles

**GS Settings**
![pcsx software](https://user-images.githubusercontent.com/29714181/120784474-69d91780-c52c-11eb-9caf-970b5d8a080d.png)
![pcsx hardware](https://user-images.githubusercontent.com/29714181/120784464-6776bd80-c52c-11eb-90a8-fe90f6483574.png)

**Emulation Settings**
Safe preset with no speedhacks
![pcsx2_CoreSettings_Speedhacks](https://user-images.githubusercontent.com/29714181/120783705-9476a080-c52b-11eb-864a-4fc6462b3272.png)

**GS Window Screenshots**
Software mode or OpenGL (correct)
![correct rendering](https://user-images.githubusercontent.com/29714181/120783326-347ffa00-c52b-11eb-9ad1-a32f55a7b555.png)
D3D11 mode (incorrect)
![d3d11_render](https://user-images.githubusercontent.com/29714181/120783387-45c90680-c52b-11eb-9596-9ec63e17ab46.png)

**System Info:**
 -   PCSX2 Revision: dev-1283
 -   OS: Windows 10
 -   CPU: Ryzen 5 3600
 -   GPU: GTX 1660 SUPER

**Logs and Dumps**
[correct rendering.xz.gz](https://github.com/PCSX2/pcsx2/files/6597516/correct.rendering.xz.gz)
[d3d11_render.xz.gz](https://github.com/PCSX2/pcsx2/files/6597517/d3d11_render.xz.gz)

**Comment by tadanokojin** [comment]
Looks like amagami DATE issues. I take it it's fine in GL?

**Comment by FaulPern** [comment]
Yeah!

**Comment by tadanokojin** [comment]
Okay, I have local code that fixes it but it won't be ready for a while yet.
In the meantime you should use GL. Shouldn't be an issue with an NV GPU.
