### ISSUE TITLE
[BUG] Ultimate Spider-Man - Crashes with "GDSX: out of memory"

### ISSUE THREAD

**Issue by JMC47** [PCSX2/pcsx2#4481]
**Describe the bug**

When playing Ultimate Spider-Man for extended periods (30 - 45 minutes?) the game eventually crashes due to"

GSdx: out-of-memory, texturing temporarily disabled

**To Reproduce**

Play the game for a while, do a couple of missions, swing around the city.  Sometimes you'll start to get flickering graphics before it eventually crashes.  Other times it'll just suddenly crash.

I hate giving open-ended reproduction steps like this, but there's not any better instructions I can give.  Usually by the end of the 2nd story mission starting from a new game, the game will crash.  One time I made it into the third mission.

**Expected behavior**

After careful examination of "Let's Play" footage, I do believe the correct behavior would be for the game not to crash.

**GS Settings**

I'm using whatever the defaults are; this is a fresh PCSX2 dev build.  I just hit F9 right when the game starts because this game is not compatible with the hardware backends.

**Emulation Settings**

I am using the default settings.

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7.0-dev-1286-gd988e8d76
 -   OS: Windows 10
 -   CPU: Core i7-6700K
 -   GPU: GTX 1070

**Logs and Dumps**

The log suddenly dies mid-log message which is kind of interesting I guess.

[Errors.txt](https://github.com/PCSX2/pcsx2/files/6604894/Errors.txt)

**Comment by JMC47** [comment]
GSdump + Screenshot.

[gsdx_20210606165933.gs.zip](https://github.com/PCSX2/pcsx2/files/6604917/gsdx_20210606165933.gs.zip)
![gsdx_20210606165933](https://user-images.githubusercontent.com/6598209/120939987-d3058a00-c6e8-11eb-8736-1d9a8dc0bfe4.png)

**Comment by tellowkrinkle** [comment]
Can you test and see if it still crashes with #4348

**Comment by tadanokojin** [comment]
#4348 seems like it should address it, yeah.

**Comment by JMC47** [comment]
I was able to play through a couple of missions without crashing.  I have to assume it's fixed.

The game did have a lot of hard stutters.  Like, it'd go to pop something up and it'd freeze for a second or two.  I don't remember that being on dev, but I'll take that over crashing any day.

**Comment by refractionpcsx2** [comment]
Should be fixed now #4348 has been merged
