### ISSUE TITLE
[BUG] Blue-Shift Engine: severe timing issues when going ingame.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#4484]
**Describe the bug**
A game engine named "Blue-Shift" (Used in Marvel Nemesis Rize of the Imperfect, WSB 2K3 and ESPN MLB 2K4) refuse to work properly on PCSX2 and pretty much any PS2 emulators.

**To Reproduce**
Load one of the former games mentioned more upper and go ingame.

**Expected behavior**
The games should exhibit no issues when going ingame.

**Emulation Settings**
[JIT]
EE - +3 cyclerate to stay in sync with the VUs.
VU1 - InstantVU1 and MTVU disabled to avoids running too much ahead of the VU0.
VU0 - *VU0Kickstart* To avoids some desync with the VU1 in some very rare cases.

**System Info:**
 -   pcsx2-v1.7.0-dev-1163-ga6fac1e00-windows-x86
 -   OS: Windows 10
 -   CPU:  i9 9900k
 -   GPU: RTX 3070

**Test results and research:**

- There are 2 versions of the engine which we will call V0 and V1.

**World Series Baseball 2K3 runs on the V0 engine which have a couple of differences compared to the later revision.**

- The engine is less broken on PCSX2 in general. The game environement is displaying correctly, however, the characters are most deffinitely not.

- Changing the cyclerate will change the SPS and how bad it is. +3 cyclerate can even shows up some geometry.

*Normal cyclerate*
<img width="974" alt="1" src="https://user-images.githubusercontent.com/26351275/121013760-88901600-c799-11eb-8118-20a4ac39db96.PNG">

*+3 cyclerate*
<img width="971" alt="2" src="https://user-images.githubusercontent.com/26351275/121013778-90e85100-c799-11eb-8815-da73d7c68537.PNG">

- Uses a cache mode not implemented in PCSX2 (unsure if it really needs it).

<img width="174" alt="3" src="https://user-images.githubusercontent.com/26351275/121013930-b5dcc400-c799-11eb-90df-bb4d5e78cbc5.PNG">

- The engine will crash immediately if the EE is set to interpreter

**ESPN Major League Baseball and Marvel Nemesis Rize of the Imperfect booth runs on the V1 engine.**

- Unlike V0, V1 fails to render pretty much any geometry in PCSX2.

- +3 cyclerate appears to be a requirement for V1 to run.

- It doesn't use the cache mode not implemented unlike V0.

- If the VU0 and VU1 interpreters are synced together with a specific build, booth games are displaying most of the geometry fine but, they will booth crash a bit later (around 7 seconds).

[Blue-Shift V1 build.zip](https://github.com/PCSX2/pcsx2/files/6608711/Blue-Shift.V1.build.zip)

*ESPN Major League Baseball*

![unknown](https://user-images.githubusercontent.com/26351275/121014551-66e35e80-c79a-11eb-8796-c60f92e91c61.png)

*Marvel Nemesis Rize of the Imperfect*

![unknown (1)](https://user-images.githubusercontent.com/26351275/121014625-78c50180-c79a-11eb-9156-cbaf4dc9c6bc.png)

- The engine will crash immediately if the EE is set to interpreter

**Logs and Dumps**
Soon.

**Comment by refractionpcsx2** [comment]
I've marked as "Wont fix" because it's so unfeasible to fix it, it's not even worth considering for at least the next 10 years.

**Comment by lightningterror** [comment]
I will close this since it is marked as unfeasible to fix by ref.
