### ISSUE TITLE
[BUG] Keyboard input buttons "stick" under Linux

### ISSUE THREAD

**Issue by Prism019** [PCSX2/pcsx2#4492]
**Describe the bug**

Under Linux, sometimes when playing games using the keyboard for pad input, a button will stay pressed when I release the key until I press and release the key again. I'm using FCITX 4.2.9.8 for text input.

**To Reproduce**

Play a game for a while; eventually a button will stay pressed after you release it. This happens in every game I play.

**Expected behavior**

Buttons are pressed and released when the corresponding keys are.

**GS Settings**

GS settings are default. I'm using the SSE4.1 plugin.

**Emulation Settings**

All settings are default, preset 2.

**GS Window Screenshots**

N/A

**System Info (please complete the following information):**
 -   PCSX2 Revision:  1.7.0-dev-1232
 -   OS:  Arch Linux x64, MATE DE
 -   CPU:  i7-3520m
 -   GPU:  Intel HD 4000

**Logs and Dumps**

None. Feel free to ask me to provide any additional information that may be helpful.

**Comment by JPTIZ** [comment]
Can confirm this happens here as well.

- PCSX2 Revision: 1.7.0.r1292.982ef4181-1
- OS: Arch Linux x64, i3-wm
- CPU: i5-7300HQ
- GPU: NVIDIA GeForce FTX 1050 Mobile

Specifically I know this happens in every SMT game I play.

**Comment by RedDevilus** [comment]
Can you retest this, please?

**Comment by JPTIZ** [comment]
> Can you retest this, please?

Just tested, still happens on 1.7.2243-3 randomly, even without switching between windows or anything.

**Comment by HeroponRikiBestest** [comment]
I can second this, I've experienced this constantly for the last few months.

**Comment by Mrlinkwii** [comment]
is this still an issue on master

**Comment by Prism019** [comment]
After switching from building the wxwidgets version of pcsx2 to building pcsx2-qt, the input issue is resolved. I think as long as the wxwidgets build is being distributed and used by people, this issue is relevant.

**Comment by stenzek** [comment]
wx build is deprecated, it's only kept around on life support for people who can't live without the debugger/usb features.

No point keeping it open, because nobody is going to be fixing it.
