### ISSUE TITLE
[BUG] Missing text box in Sakura Wars: So Long, My Love

### ISSUE THREAD

**Issue by shakeyjake33** [PCSX2/pcsx2#4494]
**Describe the bug**

Text box appears for split second before disappearing

**To Reproduce**

Start a new game and play until the first dialogue scene after the post-title FMV. Should take roughly one minute

**Expected behavior**

Text box appearing

**GS Settings**

Default, clean install

**Emulation Settings**

Default, clean install

**GS Window Screenshots**

N/A

**System Info (please complete the following information):**
 -   PCSX2 Revision: dev 1228
 -   OS: Windows 10 64-bit
 -   CPU: AMD Ryzen 5 5600X
 -   GPU: Nvidia GeForce RTX  2060

**Logs and Dumps**

https://www.dropbox.com/s/4ultkwu95kbgejk/emuLog.txt?dl=0

**Comment by Mrlinkwii** [comment]
Does the  Missing text box issue  happen in SW mode (F9)

**Comment by shakeyjake33** [comment]
Just checked, issue persists in SW mode. Happy to provide more information if needed.
