### ISSUE TITLE
[BUG] Just Cause [U] now crashes on start

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#4497]
This game now crashes immediately after the PS2 BIOS load screen, throwing the following exception:

![screen2](https://user-images.githubusercontent.com/12475371/122288842-0782fe00-cec0-11eb-8164-741e230af1c6.png)

This occurs whether software or OpenGL is used.  This game has always worked in testing before, though it is currently unknown what commit caused this.  Willing to bisect if necessary, time permitting.

Supporting info:

OS: Linux Mint 20.1 / kernel 5.11
CPU: i7-10870H 
GPU: Nvidia GTX 3070 / driver 460.80
Compiler: gcc-11.1.0
Commit tested: a6193b0a514b8514e8ef921b3d0b4f1ed4ec3b66

**Comment by lightningterror** [comment]
Yes, it would be nice to bisect which commit caused the issue.

**Comment by Shoegzer** [comment]
Trying to bisect now but finding that the issue persists at least as far back as 5e6cb22eebb0de4a85ce4091aff9ad47d0222446, and I'm pretty sure the game tested successfully after that point.  That said, the test system was different (i7-7820HK and GTX 1070) at the time with different drivers, compiled against a different compiler and likely other libraries have changed.  Could this issue be related to those changes?

Willing to provide anything else you may need, including logs etc.  I noticed though that the PCSX2 logfile window locks up when the game crashes, so not sure how I can get that one.

**Comment by Shoegzer** [comment]
Update: Setting EmotionEngine to Interpreter avoids the crash, and once the title screen loads, setting it back to Recompiler permits progress to game.  Again though, this was never necessary before recently.  If someone could confirm this issue also occurs on a Windows system that would help.

**Comment by refractionpcsx2** [comment]
It works fine for me, are you sure you haven't messed with your rounding/clamping settings? as they only affect the recompilers, but as I say, it works fine here.

**Comment by Shoegzer** [comment]
Thanks @refractionpcsx2 .  Interesting, perhaps it's a linux/x64 issue then?  All mine are set to default:

![pic1](https://user-images.githubusercontent.com/12475371/122317259-3a8eb700-ceeb-11eb-9dd1-3ef832b01f8c.png)
![pic2](https://user-images.githubusercontent.com/12475371/122317260-3b274d80-ceeb-11eb-9a49-fd52dd48251e.png)

I also tested with a fresh config/new memcard etc., and used a different PS2 bios etc., but to no avail.

**Comment by refractionpcsx2** [comment]
What about speedhacks and gamefixes?

I'll ask our linux testers to give it a try

**Comment by Shoegzer** [comment]
Hey thanks.  I tested with "Enable Speedhacks" checked and unchecked, and also with "Automatic Gamefixes" checked and unchecked, but it still crashes.  Also in case the timing matters, pcsx2 crashes right when the green Just Cause splash screen appears (you can see it for about half a second before the exception window is drawn).

**Comment by refractionpcsx2** [comment]
I meant more the gamefixes tab than the auto gamefixes, the auto ones should be on in the menu although this game doesn't have any.

yeah as I say that's fine here, I tried a couple of versions and couldn't notice a problem, but I guess it could be a weird linux problem.

**Comment by Shoegzer** [comment]
Ah, I see.  The only EE-related gamefix I saw was the "EE Timing Hack" which I tried to no avail.  I also tried the VU Recompilation hacks, also to no avail.  The others don't look like they'd be relevant at all.  I never needed gamefixes when the game was working properly so not sure why they'd matter now, but it was a good call to try at least.  This seems more and more like a linux x64-specific issue, at least to me.

**Comment by refractionpcsx2** [comment]
Wait, you're using a 64bit version of pcsx2 or just 64bit Linux?

**Comment by Shoegzer** [comment]
64bit pcsx2 with 64bit linux.

**Comment by refractionpcsx2** [comment]
Okay can you try 32bit pcsx2, 64bit isn't ready for production.

**Comment by Shoegzer** [comment]
I can't try 32bit pcsx2 because it doesn't work on ubuntu distros without going into dependency hell.  I'm confused though, I'm just compiling off master with no special options, why is that not supported?

**Comment by refractionpcsx2** [comment]
Because we haven't finished doing /testing the 64bit build and a lot of memory and recompiler stuff needed changing for 64bit. If it was ready we'd distribute 64bit builds. It's very much testing only.

**Comment by Shoegzer** [comment]
Gotcha, I didn't even realize.  I don't even know how you would try the 32bit pcsx2 anymore since master is just 64bit now, though even if I could, it wouldn't work as I said.  I'll revisit once 64bit becomes more official.  Thanks again!

**Comment by refractionpcsx2** [comment]
No problem, I'll keep this game in mind when it comes to 64bit testing, I might even try it myself soon to see if Windows crashes too (though I suspect it will)

**Comment by tellowkrinkle** [comment]
> master is just 64bit now

Master is *not* 64-bit only, it works just fine on 32-bit

**Comment by Shoegzer** [comment]
@tellowkrinkle I didn't realize there was still a 32-bit option, but then again I've been compiling ffor 64-bit ever since it was possible so I lost track of that side of things.

Also, I tested your PR #4498 and it works, Just Cause does not crash for me.  Thanks!
