### ISSUE TITLE
Notes desync from background track (Beatmania IIDX 3rd-8th Style)

### ISSUE THREAD

**Issue by Prism019** [PCSX2/pcsx2#450]
-PCSX2 version: 1.3.1 GIT 4-2-2015
-PCSX2 options: Defaults
-Plugins used: GSdx, LilyPad, SPU2-X, cdvdGigaherz, rest null plugins.
-Plugin settings: Defaults
-Description: When playing any song in Beatmania IIDX 3rd-8th Style, the notes' tempo is slightly faster than the background song's tempo, resulting in the notes moving out of sync.
-How to replicate: Start up and Beatmania IIDX game from 3rd to 8th style, select "Game start" or "Arcade Mode", select a difficulty, then select a song.
-Last known version to work: Never worked
-PC specifications: CPU: AMD FX-8320 GPU: MSI GeForce GT 630 OS: Windows 7 SP1
-Other comments: Started a forum post in http://forums.pcsx2.net/Thread-Bug-Report-Beatmania-IIDX-6th-Style-New-Songs-Collection-NTSC-J . The bug is shown in my video here: https://www.youtube.com/watch?v=rZGg0UnSlDg . Hope this helps!

**Comment by TheCubeMaster019** [comment]
Issue still present in latest build.

**Comment by TheCubeMaster019** [comment]
Issue still present in latest build.

**Comment by ssakash** [comment]
Yeah, no one has found a way yet for the sync issue. Maybe @refracionpcsx2 can take a look ?

**Comment by karasuhebi** [comment]
@refractionpcsx2

**Comment by refractionpcsx2** [comment]
Yeah I've seen it,  had other things going on :p also I don't have the game so i can't check

**Comment by karasuhebi** [comment]
Would it help if @TheCubeMaster019 provided a GS dump?

**Comment by refractionpcsx2** [comment]
No 'cause it's not a GS issue.

**Comment by karasuhebi** [comment]
Oh gotcha. So are your timer tweaks already in the latest nightly so that @TheCubeMaster019 (or someone else who has the game) can test?

**Comment by refractionpcsx2** [comment]
Yep, have been for a few weeks now :) I'm not expecting dramatic changes though

**Comment by karasuhebi** [comment]
You heard the man, @TheCubeMaster019. Try the newest build out and report back please. Don't hold your breath though. XD

**Comment by TheCubeMaster019** [comment]
Tested 4th style and 6th style, and it still desyncs. :/

**Comment by refractionpcsx2** [comment]
ok thanks for getting back to me. I couldn't replicate it with the beatmania i have here, which i think is the first on. 6th style is hard to come by

**Comment by TheCubeMaster019** [comment]
If it's this beatmania https://upload.wikimedia.org/wikipedia/en/7/7f/Beatmania_%28North_America%29_Coverart.png then the issue isn't in that one. it's just the NTSC-J ones.

**Comment by refractionpcsx2** [comment]
oh so it's inclusive? That's good to know, might make life a little easier.

**Comment by hoholee12** [comment]
i noticed that only 3rd - 8th style run in progressive mode by default.
and the other 9th - 16th style run in interlaced and do not have this problem.

maybe there is a problem in the progressive mode portion of the emulator??

**Comment by refractionpcsx2** [comment]
Hmm does the 3rd-8th style run at 25-30 fps then i wonder?? Maybe it's just the gates firing too often then due to the lower framerate as it does half the actual vsyncs, that would explain a lot.
Can somebody make a blockdump of one of the affected games with a set song to test with?

**Comment by hoholee12** [comment]
@refractionpcsx2 i wish i could,
but i dont know how to..:/

**Comment by hoholee12** [comment]
[SLPM-65156 (88433B3F).00.zip](https://github.com/PCSX2/pcsx2/files/160306/SLPM-65156.88433B3F.00.zip)
its a savestate file, this might help?

**Comment by refractionpcsx2** [comment]
Savestate is no good to me without the game (or a blockdump of the game) 
and the gsdump is absolutely no good for timing issues. Thanks though :)

**Comment by hoholee12** [comment]
well i think this game doesnt need a disc, it will continue playing till the end even when there is no disc..

and i dont know how to make a block dump...xD

**Comment by refractionpcsx2** [comment]
You need to use the ISO with linuziso plugin (available in older versions, cant remember which) and there is a button on there to make a blockdump, you then have to run the game, making sure there is enough of videos for us to skip and go in to a set song, not a random one (it only records what you play), then when you're done, quit the emulator gracefully and there you will have a blockdump with the same name as your ISO, but .dump on the end :)

**Comment by hoholee12** [comment]
hmm what site should i use to upload a 65mb dump?

**Comment by hoholee12** [comment]
https://www.dropbox.com/s/g7r486fzn0e6k1g/Beatmania%20IIDX%206th%20Style.dump?dl=0

https://www.youtube.com/watch?v=cv6QhgHYs1Y&feature=youtu.be

**Comment by refractionpcsx2** [comment]
Cool thanks, I'll grab that later :) you could have 7zipped the file to make it smaller but that's fine :) 

Can you give instructions of that modes  and song  you chose  as I have to do the same

**Comment by hoholee12** [comment]
i reuploaded everything, and edited my post
sorry for the confusion

**Comment by refractionpcsx2** [comment]
Oops didn't mean to click that lol. 

What song am I picking?

**Comment by hoholee12** [comment]
yesterday

**Comment by hoholee12** [comment]
doigts de fatima

**Comment by refractionpcsx2** [comment]
Cool thanks :) I'll check it out later :)

**Comment by atomic83GitHub** [comment]
Can you test this with the folowing PR? https://github.com/PCSX2/pcsx2/pull/2275

**Comment by TheCubeMaster019** [comment]
This issue persists with PR 2275.
Issue also persist with latest commit.

**Comment by ramapcsx2** [comment]
So to summarize thus far:
The issue shows up in Beatmania games that default (or run) in progressive mode. Interlaced, there is no problem. Is that right?

**Comment by TheCubeMaster019** [comment]
No. The issue is present in both Interlaced and Progressive mode.

**Comment by Prism019** [comment]
This issue is still present on latest master (aa03c83126225f92ec98569646b0d2aeffc45360).

**Comment by MrCK1** [comment]
@Prism019 are you able to retest this on latest master? The improved frametimes might've had an effect on this, thanks.

**Comment by refractionpcsx2** [comment]
Can you guys try one of the PR builds on #3862 and see if the audio stays in sync ?

**Comment by Prism019** [comment]
Works perfectly! That fixes the issue!

**Comment by refractionpcsx2** [comment]
Excellent! :)
