### ISSUE TITLE
Romance of the Three Kingdoms VII, VIII, IX, X visual bugs

### ISSUE THREAD

**Issue by NathanielRH** [PCSX2/pcsx2#4500]
**Description**
A contributor solved every visual problem with these games in GSdx 5334 (MSVC 16.00) 0.1.16 shipped with PCSX2 public 1.0 build.
The fix was accidentally scrapped in all later releases.

**To Reproduce**
Load any version of PCSX2 after 1.0 and play the games without changing any settings at all. They will look as so (with RTK VII main menu screen for the example):
https://imgur.com/jRhaNsO.png
Please note this is a SMALL example. Much of the text everywhere else in the game is distorted as well.

**How it should have looked and how it looks on the PS2, with GSdx 5334 copied over to PCSX2 1.6 or 1.7 for PCSX2-EX users**
https://i.imgur.com/fMbWdof.png

**GS Settings**
Default. 100% default. Any attempt to change default settings makes 0% impact on the problem. The problem lies with GSdx scrapping the proper method of emulating certain and therefore all ps2 games that was previously figured out but somehow scrapped under everyone's noses.

**Emulation Settings**
All default.

**GS Window Screenshots**
Another comparison:
Correct: https://i.imgur.com/wfFmGr0.png
Incorrect: https://i.imgur.com/LEgd3Eb.png

**System Info (please complete the following information):**
 -   PCSX2 Revision: All
 -   OS: All
 -   CPU: All
 -   GPU: All

**Logs and Dumps**
fully Flushed

**Comment by refractionpcsx2** [comment]
Duplicate, being tracked here #1628  (It mentions less versions but it is the same problem)

We also already have a fix in the works, it used to work because CLUT was broken perfectly for it to work.
