### ISSUE TITLE
[BUG] PCSX2 install on Debian 10.10 Buster requires adding of testing branch.

### ISSUE THREAD

**Issue by RandamuMaki** [PCSX2/pcsx2#4502]
**Describe the bug**

The Debian installation instructions for PCSX2 as listed here https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux requires the "testing" branch instead of "buster"/"stable" or "buster-backports", making it an unfeasible thing for most people. Note that the system requirements as listed here https://github.com/PCSX2/pcsx2#system-requirements simply list "Debian" and do not specify the requirement for Debian 11, Testing, or Bullseye. The current stable release of Debian is Debian 10.10 Buster and would be what most people are running right now.

**To Reproduce**

Go through the Debian installation procedure without adding "-t testing" to the apt install command when installing the 32-bits libraries required and it will fail. Finding out the correct command is $sudo apt install -t testing <list of packages> necessitates adding the "testing" branch to the /etc/apt/sources.list which is undesirable for most people due to potential instability of the system at large. I have added a log showing both instances as terminal output.

**Expected behavior**

Following the instructions on a stable or backports installation of Debian 10.x should work without forcing the user to upgrade their entire system to a potentially unstable version.

**GS Settings**

None. Did not install.

**Emulation Settings**

None. Did not install.

**GS Window Screenshots**

None. Did not install.

**System Info (please complete the following information):**
 -   PCSX2 Revision: Latest
 -   OS: Linux Debian Buster 10.10 
 -   CPU: AMD Ryzen 7 3700X 
 -   GPU: Nvidia GeForce GTX 1650 

**Logs and Dumps**

[pcsx2_apt_testing.txt](https://github.com/PCSX2/pcsx2/files/6720020/pcsx2_apt_testing.txt)

**Comment by F0bes** [comment]
Is this still a problem? Looks like it's a dependency issue that isn't our fault.

**Comment by lightningterror** [comment]
Closing, no further information was provided.
