### ISSUE TITLE
[Request] Remove Linux builds and PPA's from official page Download section

### ISSUE THREAD

**Issue by Leopard1907** [PCSX2/pcsx2#4507]
**Description**

As said in the title, removal of those would be very good.

**Reason**

They are not maintained. Linux Stable binary is from 2016 where as Windows one is from 2020.

Such as daily builds, latest Windows build is 1 day old while latest Linux build ( PPA) is 45 weeks old.

At this point those are just misleading and removal is probably way to go since if those were abandoned so long probably no one will maintain them.

**Comment by KAMiKAZOW** [comment]
Link could be changed to https://flathub.org/apps/details/net.pcsx2.PCSX2 which is a cross-distribution package of the still-current stable release.

**Comment by GovanifY** [comment]
We will switch on an appimage based distribution, which we will probably update for our 1.8 release. 
See https://github.com/PCSX2/pcsx2/pull/4103 for an ETA

**Comment by lightningterror** [comment]
New dev/nightly page has been added.
