### ISSUE TITLE
Driver Parallel Lines GSdx DX11/OpenGL SW Cars randomly changing color - HW garbage textures

### ISSUE THREAD

**Issue by joder666** [PCSX2/pcsx2#451]
I am using **pcsx2-v1.3.1-8-gf88bea5-windows-x86** from orphis buildbot.
Default settings (2-safe) except for:
GSdx10 software +2 rendering threads
SPU-X set to async mix and interpolation to cubic.

To reproduce just start a new game. While driving around you'll notice how your vehicle changes color randomly (red,white,black,blue) as well as other cars at sight, except for Taxis and Cops.

There are not known revisions of pcsx2 that previously worked OK with this game iirc. Last time i tested it was with svn r5559, unplayable using GSdx hardware mode due to graphics errors, while too slow with software mode.

BTW, i am using the igpu from processor HD Graphics 2000 with latest drivers installed 9.17.10.4101.  

**Log:**

PCSX2 1.3.1-20150201194910 - compiled on Feb  1 2015
Savestate version: 0x9a0a0000

Host Machine Init:
    Operating System =  Microsoft Windows 7 Enterprise Edition Service Pack 1 (build 
7601), 64-bit
    Physical RAM     =  7882 MB
    CPU name         =  Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
    Vendor/Model     =  GenuineIntel (stepping 07)
    CPU speed        =  3.299 ghz (4 logical threads)
    x86PType         =  Standard OEM
    x86Flags         =  bfebfbff 1fbae3ff
    x86EFlags        =  28100000

x86 Features Detected:
    SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Reserving memory for recompilers...

Loading plugins...
    Binding   GS: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins\GSdx32-
AVX.dll 
Windows 6.1.7601 (Service Pack 1 1.0)
    Binding  PAD: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\LilyPad.dll 
    Binding SPU2: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins\SPU2-
X.dll 
    Binding CDVD: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\cdvdGigaherz.dll 
    Binding  USB: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\USBnull.dll 
    Binding   FW: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\FWnull.dll 
    Binding DEV9: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\plugins
\DEV9null.dll 
Plugins loaded successfully.

(GameDB) 9677 games on record (loaded in 161ms)
HLE Notice: ELF does not have a path.

Initializing plugins...
    Init GS
Windows 6.1.7601 (Service Pack 1 1.0)
    Init PAD
    Init SPU2
    Init CDVD
    Init USB
    Init FW
    Init DEV9
Plugins initialized successfully.

Opening plugins...
    Opening GS
    Opening PAD
    Opening SPU2
- SPU2-X: Enumerating PortAudio devices:
  **\* Device 0: 'Primary Sound Driver' (Windows DirectSound)
  **\* Device 1: 'Realtek HD Audio 2nd output (Realtek High Definition Audio)' (Windows 
  DirectSound)
  **\* Device 2: 'Speakers (Realtek High Definition Audio)' (Windows DirectSound)
  **\* Device 3: 'Speakers (Realtek High Definition Audio)' (Windows WASAPI)
  **\* Device 4: 'Realtek HD Audio 2nd output (Realtek High Definition Audio)' (Windows 
  WASAPI)
  **\* Device 5: 'Speakers (Realtek HDA Primary output)' (Windows WDM-KS)
  **\* Device 6: 'Headphones (Realtek HD Audio 2nd output)' (Windows WDM-KS)
    Opening CDVD
  - CDVD: Opening drive '\.\F:'...
  - CDVD: setSpindleSpeed success (11080KB/s)
  - CDVD: IO thread started...
  - CDVD: KeepAlive thread started...
  - CDVD: Disk Type: Double-Layer DVD
  - CDVD Disk Open: DVD, Single layer or unknown:
  - \* Track 1: Data (Mode 2) (1890800 sectors)
    Opening USB
    Opening FW
    Opening DEV9
    McdSlot 0: D:\BC\Juegos\Emus\Memcards\Main.ps2
    McdSlot 1: [disabled]
    Plugins opened successfully.
    EE/iR5900-32 Recompiler Reset
    Bios Found: USA     v02.20(10/02/2006)  Console
    BIOS rom1 module not found, skipping...
    BIOS rom2 module not found, skipping...
    BIOS erom module not found, skipping...
    (UpdateVSyncRate) Mode Changed to NTSC.
    (UpdateVSyncRate) FPS Limit Changed : 59.94 fps
    (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.71;1
    (SYSTEM.CNF) Software version = 1.01
    (SYSTEM.CNF) Disc region type = NTSC
    ELF (cdrom0:\SLUS_212.71;1) Game CRC = 0xD720770D, EntryPoint = 0x001001A8
    (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.71;1
    (SYSTEM.CNF) Software version = 1.01
    (SYSTEM.CNF) Disc region type = NTSC
    Not found Cheats file: D:\BC\Juegos\Emus\pcsx2-v1.3.1-8-gf88bea5-windows-x86\cheats

**Comment by joder666** [comment]
I bet this has something to do with this: https://github.com/PCSX2/pcsx2/issues/345

**Comment by bositman** [comment]
I can confirm the bug:

PCSX2 version: 1.3.1 GIT 976-ga4f8c6d

-PCSX2 options: Defaults

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, tested with native, scaling, opengl depth, all accurate options, accurate date, nothing affected the issue.

-Description: 
When using GSdx OpenGL or DX11 Hardware backends, the car and people textures are pretty much completely messed up. No option seemed to affect the issue.

When using GSdx OpenGL or DX11 Software backends the textures look fine, but your car and other cars keep changing color every so often ( i presume a lightning effect gone wrong)

-How to replicate: Enter ingame

Software renderer:
![pcsx2 2015-08-19 02-04-35-21](https://cloud.githubusercontent.com/assets/1621174/9345239/8f5f5dba-4617-11e5-8893-de726b44add2.jpg)
Hardware renderer:
![pcsx2 2015-08-19 02-04-37-47](https://cloud.githubusercontent.com/assets/1621174/9345240/8f627e96-4617-11e5-93b6-2f2b07cd9075.jpg)

-Last known version to work: -

-PC specifications: CPU: Intel Core i5 2500K @ 4.3Ghz GPU: Gigabyte Geforce GTX660 Windforce OC 2 GB OS: Windows 7 SP1

Had to make the GS dump large until a car changed color, so this is 962mb uncompressed, 150mb compressed: http://bositman.pcsx2.net/dumps/driver-parallel-lines-garbage-textures.rar

**Comment by FlatOutPS2** [comment]
This game runs on the same engine as Driv3r, which also has these issues. The following Driv3r issue also applies to this game: #923

**Comment by FlatOutPS2** [comment]
It did some testing with Driv3r, and the change of color of the cars is not random. The car color changes if another car of the same type(but in a different color) shows up on the screen. As soon as that car is out of view, the color changes back to the normal color. If you turn the camera around to look at the other car again, your car changes back to that color again too.

**Comment by gregory38** [comment]
How behave zerogs ?

**Comment by FlatOutPS2** [comment]
It looks even worse than GSdx hardware renderers.

**Comment by FlatOutPS2** [comment]
This issue has recently been solved for software mode thanks to https://github.com/PCSX2/pcsx2/commit/a123e6518521f3d59c628678c11031a4d2d8358c

Still garbage textures on the cars in HW modes though.

**Comment by FlatOutPS2** [comment]
Based on previous commit, this game might need it too: https://github.com/PCSX2/pcsx2/issues/883

**Comment by MrCK1** [comment]
@joder666 Has the status of this changed on latest git?

**Comment by joder666** [comment]
I'll give it  test along the week and report back.

**Comment by joder666** [comment]
Same settings as before, using pcsx2-v1.5.0-dev-2330-g0e83b89db.
Software render seems better now, no random color changes anymore, as far as i could noticed. I roamed around a bit to see if it triggers did not happen, still too slow though.

Software render d3d11
![Software render d3d11](https://i.imgur.com/1UoJQ1s.png)
Hardware render d3d11, still many rendering errors.
![Hardware render d3d11](https://i.imgur.com/FDdz1yP.png)

**Comment by MrCK1** [comment]
Can you test OpenGL again. With Blending Accuracy and Mipmapping enabled?

**Comment by joder666** [comment]
opengl hardware mipmapping full bleeding unit accuracy medium
![mipmapping full bleeding unit accuracy medium](https://user-images.githubusercontent.com/8714385/37846889-d0f6a0fe-2ead-11e8-860c-8ff5a2963648.png)

mipmapping Full Bleeding unit accuracy high
![mipmapping full bleeding unit accuracy high-1 can trigger original bug](https://user-images.githubusercontent.com/8714385/37846949-022941c2-2eae-11e8-840d-a7c6ef9a3e4d.png)

![mipmapping full bleeding unit accuracy high-2 can trigger original bug](https://user-images.githubusercontent.com/8714385/37846989-21530812-2eae-11e8-9885-db74ffd23a8d.png)

Setting bleeding unit accuracy to Full or Ultra makes no difference but make the game run slower (no surprises here).
opengl software is the same as with d3d11 software, a tiny bit faster for me though.

**Comment by tadanokojin** [comment]
Issue needs to be updated. GS dump is a dead link.

**Comment by bositman** [comment]
I've uploaded a new dump on our dump repo as per lightning's request some days ago

**Comment by lightningterror** [comment]
Here's a gs dump: [driver-parallel-lines.zip](https://github.com/PCSX2/pcsx2/files/3771771/driver-parallel-lines.zip)

**Comment by tadanokojin** [comment]
Link to dump site would have been fine but that works thanks.

**Comment by Fireboyd78** [comment]
Hey guys, I would really like to help get this sorted out. There's an early demo version of this game that came with a symbols map, which allows you to see all the different function names as well as global variable names.

I have quite a bit of research done on their rendering engine, and would really like to get this all sorted out once and for all.

Here's a snippet of the different texture-related functions they have:

```cpp
Texture::addPixmaps(DmaBuffer *, unsigned int, unsigned int, AddPixmapInfo *, DmaEntry *)
Texture::fillDecompressTexture32(DecompressTexture *, unsigned char *, unsigned int, Substance *, unsigned int, unsigned int)
Texture::fillDecompressTexture8(DecompressTexture *, unsigned char *, unsigned int, Substance *, unsigned int, unsigned int)
Texture::fillDecompressTexture4(DecompressTexture *, unsigned char *, unsigned int, Substance *, unsigned int, unsigned int)
Texture::fillDecompressHeader(DecompressHeader *, unsigned char, unsigned int)
Texture::add32Bit(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addPAL8(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addPAL4(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addVQ2(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addVQ4(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addHY2(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addVQ4f(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *, unsigned int, unsigned int, unsigned int)
Texture::addNormalTexture(DmaBuffer *, DmaEntry *, unsigned int, unsigned int, Substance *)
Texture::addBlendedTextureClut(DmaBuffer *, unsigned int, unsigned int, unsigned int, DmaEntry *)
```
The cars use VQ4 and VQ4f, IIRC. They also install custom interrupts and patches to the GS. Plenty of information available in here, please let me know what I can do to help get things figured out.

Thanks!

**Comment by qamichele594** [comment]
[How caused this GBARunner2 issue from SA1 and SA2 Copyprotection locked out in GBARunner2?](https://github.com/Gericom/GBARunner2/issues/247)

**Comment by Danondso** [comment]
I know this has been quiet for a couple years, but has there been any under-the-radar progress on this? I'm a full stack dev and not much of a game dev but hot dang if I don't want to help contribute in some way to getting this sorted.
