### ISSUE TITLE
[BUG] Graphical glitches in King of Fighters 2003

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#4515]
**Describe the bug**

There are some graphical glitches in the game. I've tested the European and Japanese releases and both present graphical glitches in the 3D backgrounds, but only the European presents a glitch in the pause menu, as seen below:

![kof2k3-01](https://user-images.githubusercontent.com/27839354/124491058-371f7a80-dd89-11eb-92c9-f951bbe7bde5.jpg)
As you can see, the menu option "Button settings" is cut.

In the next screenshot the snake face is broken:

![kof2k3-02](https://user-images.githubusercontent.com/27839354/124491347-8c5b8c00-dd89-11eb-8881-d5f513ec9da0.jpg)
This issue doesn't happen in the real hardware, as you can see in this video (go to 16:10): https://youtu.be/YsyuR8Eied8

There's also a weird flashing glitch in the text area in the story demos, as seen below:
![gs_20210705125657](https://user-images.githubusercontent.com/27839354/124497428-34c11e80-dd91-11eb-92e3-d12aeef5b57d.png)

And here's a good one for comparison:
![gs_20210705125656](https://user-images.githubusercontent.com/27839354/124497733-b022d000-dd91-11eb-8197-3b35d8caa06d.png)

**To Reproduce**

For the pause menu glitch, play in arcade, team play or single play and when the match starts just press start to pause the game and see the glitch.
For the broken snake face, please use this save state to quickly reach the boss fight:
[SLES-53382 (B967F21F).04.zip](https://github.com/PCSX2/pcsx2/files/6765184/SLES-53382.B967F21F.04.zip)
For the text glitch in the story demos, use this state:
[SLES-53382 (B967F21F).06.zip](https://github.com/PCSX2/pcsx2/files/6765421/SLES-53382.B967F21F.06.zip)

**Expected behavior**

Just as mentioned above, some broken graphical elements in the game.

**GS Settings**

All defaults. Glitch happens with and without up-scaled resolutions.

**Emulation Settings**

Everything default, except that I changed v sync to "standard".

**GS Window Screenshots**

Screenshots provided above.

**System Info (please complete the following information):**
 -   PCSX2 Revision: pcsx2-v1.7.0-dev-1429-g1630805fd-windows-x86
 -   OS: Win 10
 -   CPU: i5-10400
 -   GPU: UHD graphics 630 with latest intel drivers.

**Logs and Dumps**

[kof2k3 euro broken snake face glitch.zip](https://github.com/PCSX2/pcsx2/files/6765440/kof2k3.euro.broken.snake.face.glitch.zip)
[kof2k3 euro pause menu glitch.zip](https://github.com/PCSX2/pcsx2/files/6765441/kof2k3.euro.pause.menu.glitch.zip)
[kof2k3 text glitch story demo.zip](https://github.com/PCSX2/pcsx2/files/6765443/kof2k3.text.glitch.story.demo.zip)

**Comment by refractionpcsx2** [comment]
This is already kinda being tracked in #3496 

The KoF games are very annoying and they will all need patches.  We have already done some of the earlier games.
