### ISSUE TITLE
[BUG] Never7 (SLPS-25256) - Missing graphics in hardware mode

### ISSUE THREAD

**Issue by MKCAMK** [PCSX2/pcsx2#4528]
**Describe the bug**
When using a hardware renderer, when the game is showing a screen with the in-story date, the background image is missing.

**To Reproduce**
Use either OpenGL or DirectX renderer, and get to any of the date transition screens. (One happens right after the beginning.)

**Expected behavior**
Missing graphics should be present, as is the case when using software mode.

**GS Settings**
The bug occurs with OpenGL and Direct3D renderers. 
The bug does not occur with the software renderer.

**Emulation Settings**
Preset - Safest

**GS Window Screenshots**
Software - How it should look
![Never7_Software_Correct (1)](https://user-images.githubusercontent.com/86579342/124956456-4e27cc00-e018-11eb-89d4-c40b70d3912d.png)
![Never7_Software_Correct (2)](https://user-images.githubusercontent.com/86579342/124956480-541dad00-e018-11eb-9172-7546fc456165.png)

Direct3D 11
![Never7_Direct3D11_MissingGraphic (1)](https://user-images.githubusercontent.com/86579342/124956383-38b2a200-e018-11eb-847d-095e79921868.png)
![Never7_Direct3D11_MissingGraphic (2)](https://user-images.githubusercontent.com/86579342/124956400-3e0fec80-e018-11eb-9b21-2d601de5e845.png)

OpenGL
![Never7_OpenGL_MissingGraphic (1)](https://user-images.githubusercontent.com/86579342/124956273-1de02d80-e018-11eb-8a39-9fdbc36c618b.png)
![Never7_OpenGL_MissingGraphic (2)](https://user-images.githubusercontent.com/86579342/124956301-23d60e80-e018-11eb-950e-da6c8653b7f0.png)

**System Info :**
 -   PCSX2 Revision: v1.7.0-dev-1434-g811f9c52c
 -   OS: Windows 10
 -   CPU: Intel Core i7-7700 @ 3.6Ghz
 -   GPU: Nvidia Geforce GTX 1060 6GB

**Logs and Dumps**
[Never7_MissingGraphics_GSdumps.zip](https://github.com/PCSX2/pcsx2/files/6785931/Never7_MissingGraphics_GSdumps.zip)

**Comment by lightningterror** [comment]
Does preload frame data hw hack help?

**Comment by MKCAMK** [comment]
Yes!
Preload Frame Data fixes this issue.

Direct3D 11 - Preload Frame Data enabled
![Never7_Direct3D11_PreloadFrameData (1)](https://user-images.githubusercontent.com/86579342/125003697-0aed4d80-e058-11eb-97f9-d51c1325efa5.png)
![Never7_Direct3D11_PreloadFrameData (2)](https://user-images.githubusercontent.com/86579342/125003702-10e32e80-e058-11eb-8f3a-a65a99dfaa9b.png)

OpenGL - Preload Frame Data enabled
![Never7_OpenGL_PreloadFrameData (1)](https://user-images.githubusercontent.com/86579342/125003715-18a2d300-e058-11eb-8624-48219bc06b4e.png)
![Never7_OpenGL_PreloadFrameData (2)](https://user-images.githubusercontent.com/86579342/125003720-1ccef080-e058-11eb-9db9-2ef5569968fa.png)

**Comment by lightningterror** [comment]
Might be worth mentioning this on the wiki or making a compatibility post with the mention.
