### ISSUE TITLE
(Suggestion) GSDX Hardware using RAM instead of VRAM?

### ISSUE THREAD

**Issue by SerialHacker** [PCSX2/pcsx2#453]
Currently GSDX Hardware uses mainly VRAM. 

Could we have an option to use RAM instead? (like GSDX Software)

 is that possible ?

**Comment by karasuhebi** [comment]
Why do you want this? RAM is so slow. This is a horrible idea. :-\

**Comment by SerialHacker** [comment]
Cause there are cases where your VRAM is not enough.

**Comment by ramapcsx2** [comment]
Hey, this suggestion wouldn't do anything good, I'm afraid.
Your video card needs to use its own memory to get any speed at all.
Using system memory would slow everything down to a crawl.
