### ISSUE TITLE
[BUG] Syphon Filter: The Omega Strain - Flashlight/Night vision not working

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#4531]
![ass](https://user-images.githubusercontent.com/5770076/125135069-7814e780-e119-11eb-93d0-b011c814edc0.gif)

**Describe the bug**
The night vision and flashlight don't work as they should according to pcsx2 wiki this has been fixed with game fixes but even though game fixes were enabled the bug still appeared in PCSX2 1.7.0-20210709190042 version

**To Reproduce**
Just use flashlight or night vision they don't work 

**Expected behavior**
illuminate the room

**GS Settings**
Up scaled just but software rendering has the same issue 

**Emulation Settings**
Emulator speed settings set to 3

**GS Window Screenshots**
[snaps.zip](https://github.com/PCSX2/pcsx2/files/6793888/snaps.zip)

**System Info (please complete the following information):**
PCSX2 1.7.0-20210709190042
OS: W10 x64
 -   CPU: 3570
 -   GPU: 1050ti

**Comment by Mewtwo5555** [comment]
G

**Comment by MrCK1** [comment]
What region of the game do you have? Can you please also upload your memory card

**Comment by Levan7** [comment]
@MrCK1 
I re tested it and I found the problem I had code braker codes on they must have interfered with flash light.
Without it on the flashlight works. It is the NTSC version if you are still interested I can share MC

**Comment by refractionpcsx2** [comment]
okay if cheats broke the game then we're not really interested, that's not our issue to fix, the cheats need to be cleared up.

But thanks for letting us know.
