### ISSUE TITLE
[Feature Request] Port for UWP for Xbox Series Consoles Dev Mode

### ISSUE THREAD

**Issue by danprice142** [PCSX2/pcsx2#4536]
**Description**
Port for UWP for Xbox Series Consoles Dev Mode

**Reason**
Would be way better than the pcsx2 libretro core using RetroArch and would bring many features thats not available in the core such as 4k, Mouse and keyboard support and the many features PCSX2 offers

**Examples**
https://github.com/libretro/RetroArch/blob/master/uwp/uwp_main.cpp
https://github.com/stenzek/duckstation/runs/3039970836?check_suite_focus=true
https://buildbot.orphis.net/ppsspp/index.php

**Comment by wvnative** [comment]
This would be amazing

**Comment by F0bes** [comment]
Hi there, thanks for the feature request.

First if all we don't have any affiliation with libretro and their core and we are not interested in directory providing features for said core. You are free to make a request on their repository.

Secondly, 
Implementing UWP would be a significant change to our codebase and let me tell you, there is a long list of higher priority tasks such as the QT GUI overhaul for example.

I don't really know what else to say but unfortunately there isn't enough people to make this happen soon. 

Have a good one, Ty.

**Comment by wvnative** [comment]
> 
> 
> Hi there, thanks for the feature request.
> 
> First if all we don't have any affiliation with libretro and their core and we are not interested in directory providing features for said core. You are free to make a request on their repository.
> 
> Secondly,
> Implementing UWP would be a significant change to our codebase and let me tell you, there is a long list of higher priority tasks such as the QT GUI overhaul for example.
> 
> I don't really know what else to say but unfortunately there isn't enough people to make this happen soon.
> 
> Have a good one, Ty.


Disappointing but happy to hear an open and honest response.

There is just a strong desire out there to turn the xbox into the ultimate emulation box with the convenience of a console, and retroarch is often jank with outdated and buggy cores. But I understand if the resources are too limited for now to tackle such a project. 

Good day

**Comment by lightningterror** [comment]
Closing as invalid, reasons stated by F0bes.
