### ISSUE TITLE
Why was Windows 7 support dropped?

### ISSUE THREAD

**Issue by 60fpshacksrock** [PCSX2/pcsx2#4538]
I am not trying to start anything, but to me, it makes no sense. Windows 7 is perfectly capable of emulating the PS2 and at full speed with this emulator. It is really a sad time for those who still use 7 like me.

https://www.theverge.com/2021/1/6/22217052/microsoft-windows-7-109-million-pcs-usage-stats-analytics

**Comment by tadanokojin** [comment]
It makes perfect sense. There's no reason for us to support and OS no one has any business running anyway and I don't really care if you think it's capable or not. Numbers reported like this are often inflated.

**Comment by refractionpcsx2** [comment]
We made the changes to drastically improve our workflow and move forward with the emulator, supporting old unsupported OS's going forward made no sense to us since it was hindering progress.

Good news for you though is that older versions (1.6 and below) will continue to work on Windows 7.
