### ISSUE TITLE
GSDX regression-crash on konami games (Goemon)

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#454]
Test was done on Goemon but an user suggest that it impacts all konami games. Note it requires 15-30 minutes of games to trigger the crash.

Discussion can be found here:
http://forums.pcsx2.net/Thread-Bouken-Jidai-Katsugeki-Goemon-SLPM-65014-J

GSdx 1286 => OK
GSdx f2657ae4507d23f31153e222461a2947a357ce7d => KO

Goemon hits 2 assertions in GSdx, potentially crash could be related. Otherwise without a backtrace is impossible to spot the issue.

**Comment by gregory38** [comment]
If someone have time to test this patch. If the crash is not solved, please generate a backtrace
```
diff --git a/plugins/GSdx/GSState.cpp b/plugins/GSdx/GSState.cpp
index c09eb8c..ea1f1d9 100644
--- a/plugins/GSdx/GSState.cpp
+++ b/plugins/GSdx/GSState.cpp
@@ -852,6 +852,8 @@ template<int i> void GSState::GIFRegHandlerTEX0(const GIFReg* RESTRICT r)
        if((TEX0.TBW & 1) && (TEX0.PSM == PSM_PSMT8 || TEX0.PSM == PSM_PSMT4))
        {
                ASSERT(TEX0.TBW == 1); // TODO // Bouken Jidai Katsugeki Goemon
+               if (TEX0.TBW == 1)
+                       TEX0.TBW = 2;
 
                TEX0.TBW &= ~1; // GS User 2.6
        }
```

**Comment by gregory38** [comment]
Note: apply the patch manually (add the line that begin with a +) until I found a way to post clean patch

**Comment by ramapcsx2** [comment]
The suggested fix didn't work for me. The game still makes GSdx allocate more and more memory, up until the process limit and crash.
GSdx 1286 works but it is ancient, unfortunately (build date 2009).
A stack trace probably won't help here. It'd be better to find the GSdx revision that introduces the problem.

**Comment by gregory38** [comment]
Hum so it is a memory issue. Could it be linked to texture cache management?

**Comment by atomic83GitHub** [comment]
The GoemonTLBhack was made for this issue?
If yes, it can be close right?

**Comment by willkuer** [comment]
No. The hack is for the EE/TLB issue. The memory allocation error seems to be related to the gs plugin.

**Comment by gregory38** [comment]
Yes. The hack is for the EE. GSdx is a separate issue and likely a memory issue.

**Comment by refractionpcsx2** [comment]
Now being tracked here: #2686

**Comment by refractionpcsx2** [comment]
This has been resolved in master. But the crashing is due to memleaking in GSOffset, being tracked here: #2686
