### ISSUE TITLE
[BUG] Linux: PCSX2 won't launch after the 'fmt' library is upgraded to version 8.x.x

### ISSUE THREAD

**Issue by gfelipe099** [PCSX2/pcsx2#4542]
**Describe the bug**
Recently the `fmt` library has been upgraded to version 8.x.x, making PCSX2 to stop working.

**To Reproduce**
Upgrade the 'fmt' library on any distro to version 8.x.x if available and then try to launch PCSX2.

On the terminal it will throw the error below:
`PCSX2: error while loading shared libraries: libfmt.so.7: cannot open shared object file: No such file or directory`.

On the GUI nothing will happen.

**Expected behavior**
The execution of the program showing the main window.

**GS Settings**
N/A

**Emulation Settings**
N/A

**GS Window Screenshots**
N/A

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7.0-r1450.d9bd63fcb-1
 -   OS: Arch Linux
 -   CPU: i5-8400
 -   GPU: Intel UHD Graphics 630 | NVIDIA GeForce GT 710 (the last one is used by vfio-pci only)

**Logs and Dumps**
N/A

**Comment by refractionpcsx2** [comment]
did you update your submodules and rebuild them?

**Comment by gfelipe099** [comment]
Yes, I use pcsx2-git package from the AUR

**Comment by gfelipe099** [comment]
Nevermind, sorry for bothering, I rebuilt PCSX2 once more just now and revision r1464-g45c1579a1 was available.
