### ISSUE TITLE
[BUG] Internal recorder freezing PCSX2

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4544]
**Describe the bug**

If the internal video recorder is open and you close the PCSX2 window or right click all windows it will freeze PCSX2 and you are forced to close it.
**To Reproduce**

1. Start a game 
2. F12 or Capture --> Video --> Videocapture/recording
3. Close PCSX2 window of the game  or close all windows via right click menu.

**Expected behavior**

Change the window focus so user can't close it that way or auto-close internal video recorder.
**GS Settings**

Default
**Emulation Settings**

Default
**GS Window Screenshots**

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1458
 -   OS: Windows 10
 -   CPU: i7-9750H
 -   GPU: RTX 2060M 6GB

**Logs and Dumps**

**Comment by sonicfind** [comment]
Before the capture PR merge or after? Honestly hoping for the latter.

**Comment by RedDevilus** [comment]
Does the same in 1.6 version:
![image](https://user-images.githubusercontent.com/24227051/125545215-9772d915-665b-4563-bccf-aba0278baa4c.png)
Settings is open , i don't adjust anything and i just close the viewport.

**Comment by sonicfind** [comment]
Ohhhhhhhh I see. hmm

**Comment by Squall-Leonhart** [comment]
its waiting for a destruction message that'll never arrive.

**Comment by RedDevilus** [comment]
Can't seem to trigger this anymore. Don't remember what fixed it either.
