### ISSUE TITLE
[BUG] Star Ocean 3: CDVD read timouts causing audio stutter/hang

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#4550]
**Describe the bug**
This bus was supposed to be fixed on 1.5.0, still crawls in.

**To Reproduce**
Play first cutscene.

**Expected behavior**
Voice would be hearable in this entire cutscene.

**Emulation Settings**
Only with Tri-Ace hacks that's automatically enabled.

**System Info (please complete the following information):**
 -   PCSX2 Revision: latest dev
 -   OS: Windows 11
 -   CPU: Intel i7-9750H
 -   GPU: GTX 1660 Ti

**Comment by Squall-Leonhart** [comment]
adjust the time-stretching

**Comment by knight-ryu12** [comment]
this bug seems only exists in V1.1 of SO3; (SLPM-65209).

**Comment by refractionpcsx2** [comment]
> adjust the time-stretching

It's not time stretching, the CDVD times out

**Comment by knight-ryu12** [comment]
sounds like IOP is STILL expecting to send over but CDVD DMA is over.
I am not sure why this only happens on V1.1 of game.

**Comment by refractionpcsx2** [comment]
> sounds like IOP is STILL expecting to send over but CDVD DMA is over.
> I am not sure why this only happens on V1.1 of game.

It's possibly using an older/buggier CDVD driver.
