### ISSUE TITLE
[Feature Request] Automatic selection for special controllers

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#4555]
**Description**
Implement a method which select automatically a special controller. GameIndex.yaml will have new tags which will be used to configure a proper controller for every game who needs something special. A new controller type "Auto" is added to Gamepad and USB menus, keeping this way the possibility to select a different controller manually. 

![Untitled2](https://user-images.githubusercontent.com/2995486/125860302-b2ebe778-fb51-4a93-a8a1-cbd8307cf0c4.png)
![Untitled](https://user-images.githubusercontent.com/2995486/125860298-419ffe01-0e50-4a52-abcc-c1d62b7cb0a7.png)

**Comment by refractionpcsx2** [comment]
would it not be better to have "controller_pad" and "controller_usb" instead of an interface and type? It'd probably be easier logic.

**Comment by Florin9doi** [comment]
I agree that this idea can be improved.

**Comment by RedDevilus** [comment]
Not only automatic selection based on serials, but this can be expanded upon with presets for wheels/mic/buzz et cetera. So not only do people need to configure a lot manually with that in mind they have automation but can still adjust it manually if needed and they have an idea what corresponds to what keybinding as what is seen as normal and can do their own variants on that.

**Comment by refractionpcsx2** [comment]
yeah that's the other problem, the user needs to configure which device each of the options is connecting to also.

**Comment by kenshen112** [comment]
Well, thus actually should be incredibly easy in Linux with evdev. A good example is the rpcs3 implementation which has giant lists of key codes and has a default binding for each. Something similar could be done with device id and keycodes since they'll differ per device

**Comment by refractionpcsx2** [comment]
> Well, this actually should be incredibly easy in Linux with evdev. A good example is the rpcs3 implementation which has giant lists of key codes and has a default binding for each. Something similar could be done with device id and keycodes since they'll differ per device

does evdev do USB like microphones and webcams?

**Comment by RedDevilus** [comment]
To me evdev is the linux equivalent where-as HID is the Windows equivalent, i don't think it's impossible for both but requires quite a rehaul of existing code.

**Comment by kenshen112** [comment]
> > Well, this actually should be incredibly easy in Linux with evdev. A good example is the rpcs3 implementation which has giant lists of key codes and has a default binding for each. Something similar could be done with device id and keycodes since they'll differ per device
> 
> does evdev do USB like microphones and webcams?

It does yeah. It's what our current USB uses.
