### ISSUE TITLE
[BUG] Tales of the Abyss : Guy's artes sidequest cannot be completed due to broken NPC

### ISSUE THREAD

**Issue by ZxSol** [PCSX2/pcsx2#4575]
**Describe the bug**
During the 2nd part of Guy's artes sidequest in the Desert Oasis, the old man npc in the back of the Grocer that you need to speak to in order to continue the sidequest is broken, when you attempt to speak to him, his character model twitches and nothing happens after.

**To Reproduce**
do the first part of the sidequest by talking to Pere in Baticul after meeting with the king, then go to the Desert Oasis Grocer building and attempt to speak to old man npc near the back of the room. Its about ten hours ingame on a new playthrough, so I'll attach a save file with the first step already completed for you and it should load you into the Desert Oasis.
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/6846166/Mcd001.zip)

**Expected behavior**
A short cutscene with Guy should play, where the old man gives him an item. 
https://www.youtube.com/watch?v=202dGpcCjBE video showcasing how it supposed to play out

**System Info (please complete the following information):**
 -   PCSX2 Revision: occurs on both 1.6.0 stable and 1.7.0 dev 1458-g14be2649c
 -   OS: Windows 10
 -   CPU: I5-7400
 -   GPU: GTX 1060

**Comment by combo-pizzaroll** [comment]
That quest is for tempest. Since it's your second playthrough (indicated by the star) your artes carried over from the first so no it's not broken.

**Comment by orbea** [comment]
Can you try older pcsx2 versions to see if it ever worked?

**Comment by JMC47** [comment]
Tales of Symphonia has sidequest bugs that crash as well, especially when doing side quests in a specific order.  You may need to test this exact savefile on a retail console to make sure it crashes.

**Comment by Mrlinkwii** [comment]
is this still an issue on  latest nightly ?

**Comment by Mrlinkwii** [comment]
can the save  be checked  on real hardware /  latest nightly?

**Comment by Ryudo300** [comment]
> is this still an issue on latest nightly ?

I was replaying the game recently. 

On PCSX2 v1.7.5557 this quest proceeds correctly while talking to the NPC, and the item is received at the end of the dialog.
![pcsx2-qtx64-avx2_2024-02-16_23-13-20](https://github.com/PCSX2/pcsx2/assets/10039778/dea18628-3af0-4b26-9a12-66f6162ab4ff)

![pcsx2-qtx64-avx2_2024-02-16_23-13-35](https://github.com/PCSX2/pcsx2/assets/10039778/a10f2e99-df75-4cc2-aa8a-621d213e2fe9)

Doesn't look like it's an issue anymore.

**Comment by refractionpcsx2** [comment]
Thanks for testing @Ryudo300 !
