### ISSUE TITLE
[BUG] Unhandled Page Fault with Toro to Ippai

### ISSUE THREAD

**Issue by leafyeevee** [PCSX2/pcsx2#4577]
**Describe the bug**
After the splash screens, it gives you an Unhandled Page Fault error

**To Reproduce**
You load up _Doko Demo Issyo - Toro to Ippai_ on the Linux builds 
wait for a couple of seconds after starting up and it should give you an error

**Expected behavior**
The game is supposed to boot into the title screen where you can choose from going into the options or starting a new game.

**GS Settings**
All of the GS Settings are Default

**Emulation Settings**
The emulation settings are default (Safe)

**System Info (please complete the following information):**
 -   PCSX2 Revision: v1.7.0-dev-1292-g982ef4181
 -   OS: Manjaro Linux
 -   CPU: i7-3770
 -   GPU: Intel HD Intergated Graphics

**Logs and Dumps**
```
/build/pcsx2/src/pcsx2/common/src/Utilities/Linux/LnxHostSys.cpp(70) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    EE Core
    Condition: false
    Message:   Unhandled page fault @ 0x00000018

Stacktrace:
[00] 0x0x5573f2ea2d04                            
[01] 0x0x7fd2d74f6870                            
[02] 0x0x5573f2e3087e                            
[03] 0x0x5573ff2ac013                            
```

**Comment by Mrlinkwii** [comment]
dose the unhandled page fault happen on   latest dev version  :slightly_smiling_face: ?

**Comment by leafyeevee** [comment]
It doesn't give the unhandled page fault on dev-1524-g080ba94ed

**Comment by refractionpcsx2** [comment]
Thanks for letting us know.
