### ISSUE TITLE
Dev9 Rewrite

### ISSUE THREAD

**Issue by Ben0mega** [PCSX2/pcsx2#459]
I am interested in doing a rewrite of the Dev9 plugin for portability, but I am having some trouble getting started.

Could someone help me get a feel for the control flow of the existing plugin/what the ideal plugin does?

The disk system seems to compile/work as is, and I understand the icmp stuff enough to implement it in a cross platform way (not that I know why it is there), but I do not understand the entry points for the system (I am hindered by a few compilation issues that VisualStudio ignores but standards compliant compilers flag).  The PCAP & TAP stuff is also a little difficult for me to reverse engineer - if I understood what it does, I could probably add in a Linux version (and maybe other OS versions).

**Comment by TheLastRar** [comment]
icmp and socket_io are excluded from the build in the VisualStudio project.

The PCAP / TAP class takes an Ethernet frame produced by the ps2 and sends it off (pretending to be a separate device on the network) and read any received packets back.

I've poked around the code in the past and I may be able answer more specific questions.

**Comment by trader5896** [comment]
@Ben0mega how is the process actually?

**Comment by Ben0mega** [comment]
The progress is non-existent for all practical purposes.  I have some code sketched out, but I was bogged down in understanding the meaning of the existing code and then classes/research attacked me and left my free time in tatters.
