### ISSUE TITLE
Travis CI ?

### ISSUE THREAD

**Issue by GoldWind** [PCSX2/pcsx2#46]
It would help in testing if pull-requests build correctly.

**Comment by ssakash** [comment]
Integrating TravisCI and Appveyor might be good for reviewing patches and stuffs, what do you think @turtleli @gregory38  ?

**Comment by turtleli** [comment]
Well, I am working on it, just rather slowly. I have two branches in my repository that I'm using to investigate stuff:

1. travisci_appveyor
 * Appveyor - compiles release builds with VS2013/VS2015 with downloadable builds for testing.
 * Travis CI Ubuntu Precise(12.04) - compiles gcc-4.9 and clang-3.7 release builds with Travis CI. Requires minor gsdx changes (mesa is ancient), and I need to search for an sdl2 ppa.

2. travisci
 * Travis CI Ubuntu Trusty (14.04) beta - compiles gcc-4.9 and clang-3.7 release builds, seems slower than the Precise environment, but doesn't require gsdx changes and does have sdl2.

After I'm done and I have things documented, I can send a PR, have discussions on what specifically needs built, and then someone with owner access can ~~suffer~~ enjoy doing the final set up :)

**Comment by turtleli** [comment]
Done as of commit 31e80c132115afd85e73f2238c9b6b4de9bde642.
