### ISSUE TITLE
Rogue Galaxy (U) - bugged water effects in GSdx HW renderers

### ISSUE THREAD

**Issue by rammsteks** [PCSX2/pcsx2#462]
Game: Rogue Galaxy (SCUS-97490)

Emulator version tested with: 1.2.1, 1.0.0, 1.3.0, 0.9.8

Emulator Config Options:
DX11\DX9
All possible combinations in video plugins GSDX.

My system: Core I5 2500k@4Ghz, 16Gb RAM, GTX770, Win 8.1 64bit
VS2013r installed.

All water have a glitch with textures in HW mode(in software mode no problem with water) 

http://imgur.com/1P3TjCz
http://imgur.com/W1bkR7W

**Comment by gregory38** [comment]
Please try the build from this thread http://forums.pcsx2.net/Thread-GSdx-2-0
Note: OpenGL only

**Comment by bositman** [comment]
Water still has issues in HW modes, even with all new accurate OpenGL options

**Comment by gregory38** [comment]
Did you try also accurate_fbmask?

**Comment by bositman** [comment]
New hidden option? Will try and report back :P

**Comment by gregory38** [comment]
Not really hidden but Windows dev are lagging behind :p If it doesn't work, please generate me  a gs dump.

**Comment by ssakash** [comment]
The GSdx plugin settings on Windows is getting a lot and lot of options , will add accurate_fbmask if you want ? ;)

**Comment by gregory38** [comment]
Well the issue is that Windows support 2 renderers. On linux, I remove half of the hack. Currently options are mandatory for testing.

**Comment by bositman** [comment]
fbmask didn't help, I think the water has more than 1 issue. Made a dump where you can see some rainbow colored squares in the water, not sure if it's in your scope or not (afaik no CRC hacks for this game) http://bositman.pcsx2.net/dumps/rogue_galaxy_water.rar

**Comment by gregory38** [comment]
I don't see the issue on the dump. It could be an init bug. Is it working if you start with the SW renderer (and then switch to HW later)

**Comment by bositman** [comment]
Tried it, still there...maybe a longer GS dump would help? The visual bug looks different depending on the camera angle (and some angles don't show it at all)

**Comment by gregory38** [comment]
Maybe

**Comment by karasuhebi** [comment]
@gregory38 Were you provided with a longer GS dump? If not, I can provide it.

**Comment by bositman** [comment]
Larger GS dump (330mb uncompressed):
http://bositman.pcsx2.net/dumps/rogue-galaxy-water-long-dump.rar

**Comment by gregory38** [comment]
@bositman could you test latest git (and/or the new PR). I suspect the game need depth reading.

**Comment by bositman** [comment]
It still happens with the new PR (https://github.com/PCSX2/pcsx2/pull/1306)

**Comment by gregory38** [comment]
Could you confirm it is the same issue discussed in #1333  and that preload data "hack" fix the issue.

**Comment by MrCK1** [comment]
Preload Data hack fixes the issue in OGL. D3D still broken.
