### ISSUE TITLE
[BUG] Restore defaults button gets cut off in the Speedhacks panel 

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#4622]
With the latest beta
![2021-07-25_100933](https://user-images.githubusercontent.com/5032540/126893998-3f0564ae-759f-41e6-a8fb-76b510d563f8.jpg)

**Comment by RedDevilus** [comment]
https://github.com/PCSX2/pcsx2/pull/4580
Which is then changed into
https://github.com/PCSX2/pcsx2/pull/4620

**Comment by RedDevilus** [comment]
Speedhacks is just a pain in the arse.
