### ISSUE TITLE
[BUG] Castlevania: Lament of Innocence crash on pcsx2 x64

### ISSUE THREAD

**Issue by yxmline** [PCSX2/pcsx2#4623]
**Describe the bug**

Castlevania: Lament of Innocence crash on pcsx2 x64
**To Reproduce**

start game
**Expected behavior**

32bit is ok
64 bit temporary method EE set interpreter and enable EE cache to KONAMI logo to switch recompiler again.
Savestate also crashed in this game on pcsx2 x64
**GS Settings**

**Emulation Settings**

**GS Window Screenshots**

**System Info (please complete the following information):**
 -   PCSX2 Revision: all x64
 -   OS: Windows 10
 -   CPU: i3-7700
 -   GPU: GTX 1070 ti

**Logs and Dumps**

The crash log should be incomplete

**Comment by yxmline** [comment]
https://www.mediafire.com/file/kxpsyhnqk71bvkn/Castlevania_%255BNTSC-J%255D_%255BSLPM-65444%255D_%25282021-06-25_20-46-41%2529.dump/file

**Comment by MrCK1** [comment]
I am unable to reproduce this, is it supposed to crash on/before the Konami logo? I was able to go into the first FMV without an issue.

Can you post the rest of your PCSX2 settings as well please?

**Comment by Silanda** [comment]
This is curious. I can reproduce with the Japanese version of the game (the only one I've got), but only with the 64-bit Release builds I'm building. Devel and Debug work fine (apart from Debug's speed).

In release builds it crashes the emulator before anything's displayed on screen. 32-bit Release builds work fine.

**Comment by lightningterror** [comment]
> https://www.mediafire.com/file/kxpsyhnqk71bvkn/Castlevania_%255BNTSC-J%255D_%255BSLPM-65444%255D_%25282021-06-25_20-46-41%2529.dump/file

Can you upload a newer dump as the link is not working?

**Comment by Silanda** [comment]
Not the OP, but I just checked and this is booting for me just fine in a current release build.

**Comment by yxmline** [comment]
@lightningterror
The download address is only valid for 14 days
https://www.mediafire.com/file/vpe2bq4c38arim8/Castlevania_%255BNTSC-J%255D_%255BSLPM-65444%255D_%25282021-10-30_09-15-44%2529.7z/file

**Comment by yxmline** [comment]
PCSX2 Nightly - v1.7.2083 is fix
