### ISSUE TITLE
Online multiplayer capabilities

### ISSUE THREAD

**Issue by Tyler4God** [PCSX2/pcsx2#4639]
PS2 online features
Basically play online multiplayer maps with other people

**Reason**
To play in multiplayer parties with my friends.
This will give me extra content to show on youtube

**Examples**
https://www.youtube.com/watch?v=2_EKgBMYrMI

**Comment by F0bes** [comment]
duplicate https://github.com/PCSX2/pcsx2/issues/772
Also, networking is implemented into pcsx2, look into dnas.

**Comment by Tyler4God** [comment]
I thought that just included 2-player modes, not like 8-12 player mode and messaging system?

**Comment by F0bes** [comment]
SOCOM 3 for example supports multiplayer with many people.
You have to check the status of whatever game you want to play.

**Comment by Tyler4God** [comment]
ok. is the game list being improved though? i imagine it iis.

**Comment by F0bes** [comment]
There's a list here.
https://docs.google.com/spreadsheets/d/1bbxOGm4dPxZ4Vbzyu3XxBnZmuPx3Ue-cPqBeTxtnvkQ/edit#gid=0
Anyways, the github issue page isn't for general support. Please considering joining the discord or forums.
Thanks

**Comment by Blueshawk** [comment]
> There are lists available online regarding game online status. Anyways, the github issue page isn't for general support. Please considering joining the discord or forums. Thanks

Hi, I've been going down the trail hoping to get gt4 network play going and found this feature request and explanation. 
 I just chimed in to say that i think this would be a good place to put a link to the discord channel and whatever dnas is so folks can sort things a little easier. Keep up the great work You guys rock! :D
