### ISSUE TITLE
[BUG] Automatic deinterlacing fails with Crimson Tears PAL (SLES-52534)

### ISSUE THREAD

**Issue by IlDucci** [PCSX2/pcsx2#4641]
**Describe the bug**
Using the automatic deinterlacer in Crimson Tears, PAL version (game code SLES-52534) will select an incorrect deinterlacer.

**To Reproduce**
Simply boot the game, it doesn't matter if Fast Mode is used or not.

**Expected behavior**
PCSX2 should choose for this game either Weave or blend TFF. Seems like the automatic mode is choosing BFF.

**GS Settings**
OpenGL renderer, native resolution, everything else uses default values.

**Emulation Settings**
Default values from v1.7.0-dev-1564-g958e27c78.

**GS Window Screenshots**
![Captura de pantalla 2021-08-02 154835](https://user-images.githubusercontent.com/5641681/127874849-25298b1c-90b6-4252-982b-470a0c8a4c44.png)
![Captura de pantalla 2021-08-02 154851](https://user-images.githubusercontent.com/5641681/127874854-da483e50-69b4-4ebe-a952-dbf9ab8a0ee7.png)
![Captura de pantalla 2021-08-02 154906](https://user-images.githubusercontent.com/5641681/127874855-5cca2a9f-4f72-420f-b2b4-e776dfa31bad.png)

**System Info (please complete the following information):**
 -   PCSX2 Revision: v1.7.0-dev-1564-g958e27c78
 -   OS: Windows 10 Pro 1909
 -   CPU: Intel Core i7-9700K 8-Core at 3.60 GHz
 -   GPU: RTX 2070

**Logs and Dumps**
[gs_20210802161326.zip](https://github.com/PCSX2/pcsx2/files/6917560/gs_20210802161326.zip)
[emuLog.zip](https://github.com/PCSX2/pcsx2/files/6917561/emuLog.zip)

**Comment by refractionpcsx2** [comment]
Yep, it's a game where the field order is incorrect, probably due to the game being stupid.

**Comment by IlDucci** [comment]
I think the field order is not just being incorrect, but actually SWAPPED dynamically whenever you change from ingame to the menus.

**Comment by lightningterror** [comment]
@IlDucci Are both 50hz and 60hz modes good with Weave Bottom Field First? Maybe we can add it to gamedb so it uses it instead.

**Comment by IlDucci** [comment]
Nope, right now, with today's latest version, it seems that actual ingame segments look more adequare with Top Field First (both Weave and Adaptive). Yet some logo screens (in 60 Hz) and transitions seem to change the fielding to Bottom First.

**Comment by Mrlinkwii** [comment]
Can this be checked on latest nightly ? :)

**Comment by IlDucci** [comment]
> Can this be checked on latest nightly ? :)

Hey! I just tested the PAL version quickly over as many screens as I could on v1.7.4531 and everything is now deinterlacing properly. Great job! I think this Issue can be closed now.

**Comment by refractionpcsx2** [comment]
ok thanks :)
