### ISSUE TITLE
[BUG] Ratchet and Clank Crashing on When Loading Quartu

### ISSUE THREAD

**Issue by Smellbringer** [PCSX2/pcsx2#4650]
I load the game, the loading cutscene plays, then right as the starship approaches the Planet the game stops, the sounds of the landing play, and then the game crashes. Only happens in 1.7.0, downloaded the latest version.

**Comment by refractionpcsx2** [comment]
Can you try the EE Timing hack

**Comment by atomic83GitHub** [comment]
Make sure all your speedhacks and widescreen patches are disabled, put the cyclerate values back to normal, keep the frame-limitter active and test again.

**Comment by Smellbringer** [comment]
> 
> 
> Make sure all your speedhacks and widescreen patches are disabled, put the cyclerate values back to normal, keep the frame-limitter active and test again.

Nope, still broken.

**Comment by refractionpcsx2** [comment]
Did you try what I susggested?

**Comment by Smellbringer** [comment]
> 
> 
> Did you try what I suggested?

That appeared to do the trick. Weird, could have sworn I had automatic game fixes on.

**Comment by refractionpcsx2** [comment]
Yeah it's not actually an automatic gamefix at the moment but there is a PR #4629 which adds it

You are using the US NTSC version, right?

**Comment by atomic83GitHub** [comment]
Can you also try with a 130% cyclerate?

**Comment by Smellbringer** [comment]
> 
> 
> Yeah it's not actually an automatic gamefix at the moment but there is a PR #4629 which adds it
> 
> You are using the US NTSC version, right? if you could post an emulog here, that'd be useful

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6957737/emuLog.txt)

You mean this I take it?

**Comment by refractionpcsx2** [comment]
That's it, thanks :)
