### ISSUE TITLE
[BUG] Shadow Effect in Corvette (USA) (SLUS_208.58;1)

### ISSUE THREAD

**Issue by momoids** [PCSX2/pcsx2#4655]
Some shadows are visible in the outline of cars and objects! (I'm not native English language)
![Corvette](https://user-images.githubusercontent.com/70231770/128954689-721eb0b7-80c1-49d6-be5e-8ed1b5420b59.jpg)
![Corvette 2](https://user-images.githubusercontent.com/70231770/128954709-dd091d72-ff72-496c-9258-d511fb7f1f14.jpg)

pcsx2-v1.7.0-dev-1565
CPU: RYZEN 1600x
GPU: GTX 1060 6GB
RAM: 32GB
SO: Windows 10 Pro x64 (20H2)

**Comment by MrCK1** [comment]
It is a glitch caused by upscaling (which we do not accept at this time). 

You will need to use the half pixel offset options in the Advanced GS settings. Please use the PCSX2 forums or Discord if you need further assistance.
