### ISSUE TITLE
[BUG] SLUS-20724 Firefighter FD18

### ISSUE THREAD

**Issue by manintain** [PCSX2/pcsx2#4661]
**Describe the bug**
Graphical glitching in game while playing.  Assets seem to vanish such as the fire, or other in game assets for example in the parking garage the cars will vanish too at times.  This was tested on multiple machines exhibiting the same bug in the same place.  Hitting f9 resolves the issue.

**To Reproduce**
This bug is repeatable by using the following steps on two different stages:

1.  Stage 3-2 play to mission 3 Parking Garage (There is no way to legit start at stage 3-2 mission 3 without using a save state). 
  a. Player will enter the parking garage at start of mission.
  b.  Spray the hose around and move camera and graphical glitches are visible.

2. Stage 4-2 Mission 2 Boss Battle
  a.  During the boss fight the boss vanishes
  b.  The fire vanishes as well.

**Expected behavior**
Have assets visible and not invisible or be missing.

**GS Settings**
Default settings

**Emulation Settings**
Default Settings

**GS Window Screenshots**
![gsdx_20210812111938](https://user-images.githubusercontent.com/88847578/129232716-5efb40c6-9a1c-4cea-9e66-f40a232e4832.png)

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.6.0
 -   OS: Windows 10 
 -   CPU:   i7-9700 CPU   
 -   GPU:   Nvidia GeForce RTX 2070

**Logs and Dumps**
GSdump:    http://www.filedropper.com/gsdumpfirefighterfd18
MemCard:  [Mcd001_FirefighterFD18_SLUS-20724.zip](https://github.com/PCSX2/pcsx2/files/6977025/Mcd001_FirefighterFD18_SLUS-20724.zip)
sstate:        [sstate_FirefighterFD18_SLUS-20724.zip](https://github.com/PCSX2/pcsx2/files/6977027/sstate_FirefighterFD18_SLUS-20724.zip)

**Comment by refractionpcsx2** [comment]
okay now we have a PR which fixes this, it will require the Half Screen fix also.
