### ISSUE TITLE
[Feature Request]: Local NetPlay

### ISSUE THREAD

**Issue by ProhorovIlja** [PCSX2/pcsx2#4669]
### Description

A local netplay option to play games, that do not have a proper online (LAN support) through any vpn service (Radmin VPN for example).

### Reason

There are many PS2 games, that do not have a LAN multiplayer, like Tekken 4, Tag Tournament, 5, Def Jam Fight for NY, Mortal Kombat Shaolin Monks, SSX 3, etc.

### Examples

Mednafen, NullDC.BEAR by RossenX and Fightcade 2 did implement a local netplay through the radmin vpn or online.
Fightcade 2 even added a GGPO (Rollback netcode) for some old games like street fighter III 3rd strike.

**Comment by Mrlinkwii** [comment]
hello :wave:  thanks  for the feature request  , but theirs an  feature request already on this topic #772 :slightly_smiling_face:

**Comment by BevP90** [comment]
Excellent feature request, the GGPO SDK is available for anyone to use too and save states in the recent builds are alot faster so that's promising for rollback
