### ISSUE TITLE
[BUG]: Doko Demo Issho - Toro to Ippai (Japan) and Toro to Kyuujitsu (Japan) - Wireframe issues on OGL

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#4674]
### Describe the Bug

In Doko Demo Issho - Toro to Ippai (Japan); all Toros are rendered with their wireframe missing on OGL. Additionally, even in software mode, the black Toros seem to have texture issues with their eyes.
In Toro to Kyuujitsu (Japan); Toro is rendered with only his wireframe on OGL, as well as the 3d model of a hand that acts as your mouse. As far as I know, there are no black Toros in this game to check.

### Reproduction Steps

Doko Demo Issho - Toro to Ippai (Japan): Wait until the title screen appears
Toro to Kyuujitsu (Japan): Start a new game, get past the character customization menu.

### Expected Behavior

Models of Toro (and in the case of Toro to Kyuujitsu, the mouse/hand icon as well) should appear whole, with both the wireframe and the rest of the model intact. Additionally, the black toros should not have eye texture issues.

### PCSX2 Revision

PCSX2 1.7.0-20210817085737 - compiled on Aug 17 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Uses an iGPU, see cpu

### GS Window Screenshots

Doko Demo Issho - Toro to Ippai (Japan): Software mode (Eye texture issues visible)
![image](https://user-images.githubusercontent.com/50224630/129793592-b7f8aac3-6c61-4ce0-8621-f0f00d04a765.png)
Doko Demo Issho - Toro to Ippai (Japan): Hardware mode
![image](https://user-images.githubusercontent.com/50224630/129793635-d8668dfb-80f8-468b-a5c9-bc1258d0daa1.png)

Toro to Kyuujitsu (Japan): Software mode 
![image](https://user-images.githubusercontent.com/50224630/129793417-830e9eac-bbcf-49fe-a43c-5c507799d972.png)
Toro to Kyuujitsu (Japan): Hardware/OGL mode 
![image](https://user-images.githubusercontent.com/50224630/129793448-3b67c001-c2be-4d11-b8e9-2e66af6de1f4.png)

### Logs & Dumps

In Doko Demo Issho - Toro to Ippai (Japan), when you reach the title screen (the first place where the Toro models show up) the following displays in the log:
```
microVU0: Cached Prog = [000] [PC=02c8] [List=01] (Cache=0.000%) [0.0mb]
microVU0: Cached Prog = [001] [PC=02d8] [List=01] (Cache=0.000%) [0.0mb]
microVU0: Cached Prog = [002] [PC=0140] [List=01] (Cache=0.005%) [0.0mb]
microVU0: Cached Prog = [003] [PC=0150] [List=01] (Cache=0.005%) [0.0mb]
microVU0: Cached Prog = [004] [PC=0160] [List=01] (Cache=0.009%) [0.0mb]
microVU0: Cached Prog = [005] [PC=0170] [List=01] (Cache=0.009%) [0.0mb]
microVU0: Cached Prog = [006] [PC=06a0] [List=01] (Cache=0.013%) [0.0mb]
microVU0: Cached Prog = [007] [PC=06b0] [List=01] (Cache=0.013%) [0.0mb]
microVU0: Cached Prog = [008] [PC=06e0] [List=01] (Cache=0.032%) [0.0mb]
microVU0: Cached Prog = [009] [PC=0708] [List=01] (Cache=0.032%) [0.0mb]
microVU0: Cached Prog = [010] [PC=0738] [List=01] (Cache=0.032%) [0.0mb]
microVU0: Cached Prog = [011] [PC=0768] [List=01] (Cache=0.032%) [0.0mb]
microVU1: Cached Prog = [000] [PC=0000] [List=01] (Cache=0.000%) [0.0mb]
microVU1: Cached Prog = [001] [PC=0490] [List=01] (Cache=0.000%) [0.0mb]
microVU1: Cached Prog = [002] [PC=04a0] [List=01] (Cache=0.060%) [0.0mb]
microVU1: Cached Prog = [003] [PC=0ed8] [List=01] (Cache=0.060%) [0.0mb]
microVU0: Cached Prog = [012] [PC=0530] [List=01] (Cache=0.074%) [0.0mb]
microVU0: Cached Prog = [013] [PC=0568] [List=01] (Cache=0.074%) [0.0mb]
microVU0: Cached Prog = [014] [PC=0588] [List=01] (Cache=0.074%) [0.0mb]
microVU1: Cached Prog = [004] [PC=2da8] [List=01] (Cache=0.148%) [0.1mb]
recVifUnpk: Bucket 0x1905 has 4 micro-programs
microVU1: Cached Prog = [005] [PC=1800] [List=01] (Cache=0.171%) [0.1mb]
recVifUnpk: Bucket 0x1902 has 4 micro-programs
microVU1: Cached Prog = [006] [PC=20e0] [List=01] (Cache=0.197%) [0.1mb]
microVU1: Cached Prog = [007] [PC=1258] [List=01] (Cache=0.207%) [0.1mb]
microVU1: Cached Prog = [008] [PC=0a60] [List=01] (Cache=0.230%) [0.1mb]
microVU1: Cached Prog = [009] [PC=05a0] [List=01] (Cache=0.247%) [0.2mb]
microVU1: Cached Prog = [010] [PC=05b0] [List=01] (Cache=0.248%) [0.2mb]
microVU1: 1 cycle stall on branch instruction [06f8]
recVifUnpk: Bucket 0x1903 has 4 micro-programs
recVifUnpk: Bucket 0x1907 has 4 micro-programs
recVifUnpk: Bucket 0x1908 has 4 micro-programs
recVifUnpk: Bucket 0x1904 has 4 micro-programs
recVifUnpk: Bucket 0x1909 has 4 micro-programs
recVifUnpk: Bucket 0x190d has 4 micro-programs
recVifUnpk: Bucket 0x1906 has 4 micro-programs
recVifUnpk: Bucket 0x1918 has 4 micro-programs
recVifUnpk: Bucket 0x190a has 4 micro-programs
recVifUnpk: Bucket 0x190c has 4 micro-programs
```

In Toro to Kyuujitsu (Japan), just when Toro starts talking, the following displays. However, this is after his model has already been onscreen for a second, so it's possibly unrelated to the issue.
```
ADPCM : volume = 0.
ADPCM : Intr delete.
ADPCM : delete sema ok.
ADPCM : ### Main thread sleep.  ###
CDVD : init = 1
Stream Buffer 1Bank 32768byte 5banks 163840byte used
load:              TOROQ¥CHR¥TORO.DIC   0.00sec 0.12sec
load:               TOROQ¥CHR¥JUN.DIC   0.00sec 0.12sec
load:            TOROQ¥CHR¥SUZUKI.DIC   0.00sec 0.13sec
load:             TOROQ¥CHR¥RICKY.DIC   0.00sec 0.05sec
load:            TOROQ¥CHR¥PIERRE.DIC   0.00sec 0.05sec
load:            TOROQ¥CHR¥TORO02.MBF   0.00sec 0.82sec
load:     TOROQ¥SCENE¥SCRIPT¥KEEP.MBF   0.00sec 0.20sec
load:TOROQ¥COMMON¥A_MENU¥MENUBACK.TM2   0.00sec 0.10sec
load:    TOROQ¥COMMON¥A_MENU¥FONT.TM2   0.00sec 0.05sec
load:    TOROQ¥COMMON¥A_MENU¥MENU.TM2   0.00sec 0.00sec
load:         TOROQ¥CHR¥TORO¥IDLE.BPK   0.00sec 0.90sec
load:     TOROQ¥SCENE¥TV¥FRAME336.TM2   0.00sec 0.10sec
load:     TOROQ¥SCENE¥TV¥FRAME311.TM2   0.00sec 0.00sec
load:          TOROQ¥SCENE¥TV¥336.TM2   0.00sec 0.02sec
load:          TOROQ¥SCENE¥TV¥311.TM2   0.00sec 0.02sec
load:       TOROQ¥SCENE¥TV¥TV_SCH.BIN   0.00sec 0.03sec
load:        TOROQ¥COMMON¥POLYCUR.BND   0.00sec 0.17sec
load:    TOROQ¥SCENE¥SCRIPT¥SC000.MBF   0.00sec 0.18sec
> Key: Right (Code: 316)
load: TOROQ¥SCENE¥SCEN336¥SCEN336.SDF   0.00sec 0.10sec
load:         TOROQ¥SCENE¥BLOCK40.BND   0.00sec 0.63sec
load:    TOROQ¥SCENE¥SCRIPT¥SC336.MBF   0.00sec 0.23sec
'TOROQ¥CHR¥TORO¥336M.DAT' loaded from BLOCK-PACKING file.
PokepBufferFree 1560272
load:     TOROQ¥SOUND¥DAT¥SNDB40A.BND   0.00sec 0.32sec
sound : It transfers 'BlockSE' data to SPU.
>>
FBCTRL.C:not found a file 'T0.BD'.
FBCTRL.C:not found a file 'T0.HD'.
sound : It is OK even if there is not 'Bird' at this block.
sound : It transfers 'BaseEnv' data to SPU.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
FBCTRL.C:not found a file 'TOROQ¥SCENE¥SCEN336¥SPR33601.ETM'.
TV:ゲーム時間1日目　テレビリストの曜日1の 9時のデータを使用します。
今回のテレビ番組ファイルは TOROQ¥SCENE¥TV¥NHKnews.BINです。
load:      TOROQ¥SCENE¥TV¥NHKnews.BIN   0.00sec 0.17sec
>>>>>>>>>
'TOROQ¥SCENE¥SCEN336¥MAC.DAT' loaded from BLOCK-PACKING file.
env_snd : The environment sound of this scene is 'A40336A.SQ'
info : Sound data every scene was normally set.
microVU1: Cached Prog = [000] [PC=0000] [List=01] (Cache=0.000%) [0.0mb]
microVU1: Cached Prog = [001] [PC=0af0] [List=01] (Cache=0.000%) [0.0mb]
microVU1: Cached Prog = [002] [PC=0b00] [List=01] (Cache=0.043%) [0.0mb]
microVU1: Cached Prog = [003] [PC=0ef0] [List=01] (Cache=0.043%) [0.0mb]
microVU1: Cached Prog = [004] [PC=0b20] [List=01] (Cache=0.043%) [0.0mb]
microVU1: Cached Prog = [005] [PC=0b30] [List=01] (Cache=0.061%) [0.0mb]
microVU1: Cached Prog = [006] [PC=0b40] [List=01] (Cache=0.062%) [0.0mb]
microVU1: Cached Prog = [007] [PC=1020] [List=01] (Cache=0.062%) [0.0mb]
microVU1: Cached Prog = [008] [PC=0b60] [List=01] (Cache=0.062%) [0.0mb]
microVU1: Cached Prog = [009] [PC=0a30] [List=01] (Cache=0.090%) [0.1mb]
microVU1: Cached Prog = [010] [PC=0a40] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [011] [PC=0d70] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [012] [PC=15e8] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [013] [PC=0d88] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [014] [PC=1828] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [015] [PC=0da0] [List=01] (Cache=0.091%) [0.1mb]
microVU1: Cached Prog = [016] [PC=0e00] [List=01] (Cache=0.091%) [0.1mb]
recVifUnpk: Bucket 0x0c02 has 4 micro-programs
microVU1: Cached Prog = [017] [PC=08b0] [List=01] (Cache=0.178%) [0.1mb]
microVU1: Cached Prog = [018] [PC=08c0] [List=01] (Cache=0.179%) [0.1mb]
microVU1: Cached Prog = [019] [PC=0bf0] [List=01] (Cache=0.179%) [0.1mb]
microVU1: Cached Prog = [020] [PC=0c08] [List=01] (Cache=0.179%) [0.1mb]
microVU1: Cached Prog = [021] [PC=0c20] [List=01] (Cache=0.179%) [0.1mb]
microVU1: Cached Prog = [022] [PC=0c80] [List=01] (Cache=0.179%) [0.1mb]
Available VRAM is very low (-3717024), a crash is expected! Enable conservative buffer allocation or reduce upscaling!
GS OUT OF MEMORY
microVU1: Cached Prog = [023] [PC=03a8] [List=01] (Cache=0.205%) [0.1mb]
microVU1: Cached Prog = [024] [PC=03b8] [List=01] (Cache=0.206%) [0.1mb]
microVU1: 1 cycle stall on branch instruction [04d8]
microVU1: 1 cycle stall on branch instruction [0530]
microVU1: Cached Prog = [025] [PC=0b08] [List=01] (Cache=0.206%) [0.1mb]
recVifUnpk: Bucket 0x0c0e has 4 micro-programs
recVifUnpk: Bucket 0x0c0a has 4 micro-programs
recVifUnpk: Bucket 0x0c08 has 4 micro-programs
recVifUnpk: Bucket 0x0c08 has 5 micro-programs
recVifUnpk: Bucket 0x0c06 has 4 micro-programs
microVU1: Cached Prog = [026] [PC=0a48] [List=01] (Cache=0.239%) [0.1mb]
recVifUnpk: Bucket 0x0c12 has 4 micro-programs
recVifUnpk: Bucket 0x0c0c has 4 micro-programs
recVifUnpk: Bucket 0x0c04 has 4 micro-programs
recVifUnpk: Bucket 0x0c04 has 5 micro-programs
microVU1: Cached Prog = [027] [PC=08c8] [List=01] (Cache=0.289%) [0.2mb]
recVifUnpk: Bucket 0x0c16 has 4 micro-programs
recVifUnpk: Bucket 0x0c14 has 4 micro-programs
recVifUnpk: Bucket 0x0c10 has 4 micro-programs
Read Time Out 5000(msec)
```

**Comment by refractionpcsx2** [comment]
Interesting observation, if you enable the "Preload Frame" hack, when you OK to go back the model will look perfect (albeit in the wrong stance) for about 5 frames then it'll go back to looking broken, but will be in the right frame of animation

**Comment by refractionpcsx2** [comment]
In software mode as long as you have Edge AA enabled, it looks perfect, no wireframe visible at all.

That said, I don't know what it needs in  HW mode to not look completely wireframe, though I expect the closest we'll get is like Software without Edge AA

**Comment by refractionpcsx2** [comment]
Fixed in #4682 for SW Mode
Hardware mode will have to come much later, if it ever happens.

**Comment by lightningterror** [comment]
Latest master improves the handling of these games.

**Comment by HeroponRikiBestest** [comment]
> Latest master improves the handling of these games.

Just curious, how has handling of these games improved? They look identical to me.

**Comment by refractionpcsx2** [comment]
> > Latest master improves the handling of these games.
> 
> Just curious, how has handling of these games improved? They look identical to me.

Master modified the handling of AA lines in hardware mode so hardware mode doesn't look terrible. Software mode didn't change.

**Comment by lightningterror** [comment]
> > Latest master improves the handling of these games.
> 
> Just curious, how has handling of these games improved? They look identical to me.

![image](https://user-images.githubusercontent.com/18107717/145715054-e6f5f96b-ae81-4e45-a855-dfb98b3f861c.png)

**Comment by HeroponRikiBestest** [comment]
Ohh, ok, I see. I was just looking at Toro to Kyuujitsu, it seems the changes only effected Toro to Ippai. My bad.
![image](https://user-images.githubusercontent.com/50224630/145715189-00ede519-868d-4b72-9129-f1a8924c8812.png)

**Comment by refractionpcsx2** [comment]
was kinda hoping it would affect both, that's a shame :(

**Comment by lightningterror** [comment]
> Ohh, ok, I see. I was just looking at Toro to Kyuujitsu, it seems the changes only effected Toro to Ippai. My bad. ![image](https://user-images.githubusercontent.com/50224630/145715189-00ede519-868d-4b72-9129-f1a8924c8812.png)

You need to disable depth emulation for this one in hw hacks.

**Comment by HeroponRikiBestest** [comment]
Ah, ok. Toro definitely still looks a big bugged, but yeah, definitely a huge improvement.
![image](https://user-images.githubusercontent.com/50224630/145715540-9b1a767c-6ca2-482a-80d0-4cc77058ca65.png)


Worth noting:
Toro to Ippai suffers from mipmapping issues on HW, visible immediately with the plant on (your) right of the opening door. On SW, it stays nice and blurry the whole time. On hardware with Mipmapping set to automatic, the plant is far sharper than it's supposed to be. On hardware with Mipmapping set to Basic or Fast, the plant keeps jumping between being sharp and being blurry depending on where the camera is. I didn't include any pictures because I'd need a bunch to show absolutely everything, and I did the gsdump on Hardware with mipmapping set to automatic. Please lmk if you need more.
[gs_20211212090941.gs.zip](https://github.com/PCSX2/pcsx2/files/7698879/gs_20211212090941.gs.zip)
Toro to Ippai suffers from issues with the ground texture on HW.
![image](https://user-images.githubusercontent.com/50224630/145715571-10ba1b15-671d-43a5-b14a-ab20f2d656cf.png)
![image](https://user-images.githubusercontent.com/50224630/145715575-5ba3cd0b-6eb1-4ef8-afef-9328e9edaa1a.png)
[gs_20211212090616.gs.zip](https://github.com/PCSX2/pcsx2/files/7698874/gs_20211212090616.gs.zip)
