### ISSUE TITLE
[BUG]: Ghosthunter PAL Fast boot not working, Fullboot does work

### ISSUE THREAD

**Issue by stoniemahonie** [PCSX2/pcsx2#4698]
### Describe the Bug

Fast Boot hangs after booting with a black screen. Fullboot works. I think this game worked a few weeks before with fast boot enabled.

VUKickstarthack is automatically applied. I tried to enable/disable fastboot in conjuction with MTVU on/off.

I don't think it is a bug at all if it works with fullboot, but i read that fastboot is the preferred way to boot games in the emulator.

### Reproduction Steps

Fastboot the game. Black screen without any progression.

### Expected Behavior

boot works, first screen is the screen options 50/60/progressive.

### PCSX2 Revision

PCSX2 1.7.0-20210830134228 - compiled on Aug 30 2021

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3700x

### GPU

Nvidia 1060

### GS Settings

no hacks / all default besides 3x native and 16x af in gs settings.

### Emulation Settings

no hacks / all default besides 3x native and 16x af in gs settings.

Safe preset in emulation settings.

**Comment by refractionpcsx2** [comment]
Can you please provide a blockdump from a working version.

To do this enable "Create Blockdump" under the debug menu then boot the game normally (on a version which works please) then once you get past the hang , lets say, to the main menu, exit the emulator gracefully, there should be a dump file with the same name as your iso in the PCSX2 folder, 7zip that up and upload it somewhere.

Oh and don't forget to turn Create Blockdump back off :)

**Comment by refractionpcsx2** [comment]
Just for further information, I just checked the US version, which was fine.

**Comment by refractionpcsx2** [comment]
Okay I worked through this with some of the testers. if you set your EE cycle rate to -1 in the Speedhacks setting, it'll work.

But it gets more weird, if you set it back to normal and boot again, it boots fine.  Setting the IOP to interpreter also lets it work.  This is so weird

**Comment by stoniemahonie** [comment]
Okay, do you still need a blockdump ? Seems like you figured it out already. It was working a few weeks earlier. I often download the newest version of pcsx2, so i can't tell when it broke.

**Comment by refractionpcsx2** [comment]
> Okay, do you still need a blockdump ? Seems like you figured it out already. It was working a few weeks earlier. I often download the newest version of pcsx2, so i can't tell when it broke.

It hasn't worked since build 831 which was released on the 1st January, if it worked since then you must have had a weird setting, OR you ran another game first, that also seems to resolve it.  It's a bit voodoo, but I have PR'd some changes which seem to get around it at the very least.

**Comment by refractionpcsx2** [comment]
Should be fine on master now

**Comment by stoniemahonie** [comment]
It works now with fast boot without problems. Awesome :)
