### ISSUE TITLE
[BUG]: NTSC Framerate is set to 0 FPS if not using Preset Settings

### ISSUE THREAD

**Issue by bonbonman** [PCSX2/pcsx2#4713]
### Describe the Bug

NTSC Framerate always gets set to 0.00 FPS after closing PCSX2 if not using a settings Preset and using a manually entered value for it (even the default 59.94 FPS), making games pretty much not run at all unless you go change the NTSC Framerate setting every time you launch PCSX2.

### Reproduction Steps

Untick "Preset" in General Settings, set NTSC Framerate manually to default value (59.94 FPS). Apply and exit settings. Close PCSX2 and relaunch it, open General Settings and now NTSC Framerate is set to 0.00 FPS for some reason. Tested on dev-1678 and dev-1680.

### Expected Behavior

NTSC Framerate should stay at the manually set value after closing and relaunching PCSX2.

### PCSX2 Revision

dev-1680

### Operating System

Windows 10 (64bit)

### CPU

i7-6700k

### GPU

GTX 1070

### GS Settings

![GS](https://user-images.githubusercontent.com/66077876/132095782-e8f6cd93-5cee-492f-af05-470f5f29de12.png)

**Comment by tadanokojin** [comment]
unable to repro with provided steps on 1680.

**Comment by bonbonman** [comment]
Upon further inspection, this bug seems to happen for me when the PCSX2 language is set to one that splits the FPS decimals with a period sign (e.g. 59.94 in English (U.S.) and Japanese)
When I set PCSX2 to a language that separates the decimals with a comma (e.g. 59,94 in Finnish and Danish), the bug does NOT occur and the manually set value persists even after relaunching PCSX2.

**Comment by tadanokojin** [comment]
Yeah it's locale aware, so if you tried to enter `59,94` on an English locale it's going to say "idk what that is" and just reset it. But I use English US and it works fine if you enter `59.94`.

**Comment by bonbonman** [comment]
> Yeah it's locale aware, so if you tried to enter `59,94` on an English locale it's going to say "idk what that is" and just reset it. But I use English US and it works fine if you enter `59.94`.

Seems so. With PCSX2 language set to English US while my PC locale is Finnish, setting it to `59,94` will change it to `0.00` instantly after I hit apply, like it should. But `59.94` it accepts and I can start a game normally at that speed, but it will still change to `0.00` by itself after closing and restarting.

**Comment by tadanokojin** [comment]
Ah, might be related to you using a different locale than your system then.

**Comment by RedDevilus** [comment]
Seems that it doesn't affect PAL atleast.

My country denotation with decimal seperator `,` :
![image](https://user-images.githubusercontent.com/24227051/132097761-5d7a43b9-7eac-4841-817c-4a50bdbdfb91.png)

English version which has decimal seperator `.` :

![image](https://user-images.githubusercontent.com/24227051/132097795-47154233-dd55-45da-a0dd-5a51a3802699.png)

I wonder what's happening on your end.

**Comment by bonbonman** [comment]
> Seems that it doesn't affect PAL atleast.

Actually seems to affect PAL as well, if there's anything after the decimal separator other than 00. Set it to `50.00`, no problem, still `50.00` after restarting. Set it to `50.01`, now it's `0.00` after restarting.

**Comment by RedDevilus** [comment]
Changing the PAL and NTSC framerate is not much different than using baseframerate instead of percentages of a value you just change the base value. But i'm not surprised there are some bugs with it changing while in the past it was immutable in the GUI.

**Comment by RedDevilus** [comment]
Ok i can repro it



1. Change any value from NTSC or PAL
2. Press OK
3. Restart PCSX2
4. Check general settings and see `0,00` or `0.00`

**Comment by tadanokojin** [comment]
Can someone check the ini value and let me know if it is zero or has the `,` in it?

**Comment by RedDevilus** [comment]
It does apply it to the ini as for example putting 54
```
FramerateNTSC=54
FrameratePAL=54
```
So it dies when you do 54,1, but can be fine with 54 and 54,10. Weird indeed

**Comment by RedDevilus** [comment]
```
FramerateNTSC=0
FrameratePAL=11
```
I wonder if it needs to enforce the decimal and 2 numbers which it only does with apply in GUI.

**Comment by bonbonman** [comment]
> Can someone check the ini value and let me know if it is zero or has the `,` in it?

After closing PCSX2, the ini shows
```
FramerateNTSC=59.94
FrameratePAL=50
```
It changes to this upon start
```
FramerateNTSC=0
FrameratePAL=50
```

**Comment by kenshen112** [comment]
Kind of on a side note but this sounds like an interesting case for me to test on my PR

**Comment by RedDevilus** [comment]
My OS locale= English (UK)
PCSX2 WX locale= Dutch

Results: Fails 

My OS locale= English (UK)
PCSX2 WX locale= English

Results: Works

So after some internal investigation with the team it would seem that the FPS is looking for a valid float based on your OS which would be `.` however you want to use `,` which will fail because there is a locale conversion and do a double on `59,94` it doesn't see it correctly will think it's a non-valid float and will give a false result in turn giving you 0. So if this thought process is correct that would mean that if you change your OS locale to your PCSX2 locale it should work the same as English WX locale without issues.

**Comment by Squall-Leonhart** [comment]
The application should always read in and write out the System Locale format whether it be for numbers or paths, the user language on the UI should have no impact on this behavior and i consider it doing so the wrong one.

**Comment by RedDevilus** [comment]
In the past this was always grayed out, as you could use base framerate instead but opening it up do reveal some issues.

**Comment by tadanokojin** [comment]
I'll look into it after <https://github.com/PCSX2/pcsx2/pull/4720> is merged.

**Comment by RedDevilus** [comment]
Not to forget: It affects Zoom levels too.

**Comment by tadanokojin** [comment]
should be sorted in https://github.com/PCSX2/pcsx2/commit/30e5731f14d731682fbb05d7e5b1b25036eee6e1 let me know if you have any more issues.

**Comment by bonbonman** [comment]
> should be sorted in [30e5731](https://github.com/PCSX2/pcsx2/commit/30e5731f14d731682fbb05d7e5b1b25036eee6e1) let me know if you have any more issues.

Can confirm, framerate values no longer reset to 0 on launch when using different locales as of dev-1706. Thanks for the fix.
