### ISSUE TITLE
[BUG]: Can't Rebind Controller

### ISSUE THREAD

**Issue by TheDiscordian** [PCSX2/pcsx2#4714]
### Describe the Bug

Switch controller defaults to having X and O swapped, as well as Triangle and Square are also swapped. Following other issues on here, I read I should be editing either `PAD.ini` or `OnePAD2.ini`, it's *extremely* unclear what these 2 files do, as they're identical. I noticed PAD.ini has a `mouse_sensitivity` param which is definitely getting r/w from as the emulator runs. I decided to edit both with this line:

`SDL2 = 03000000000000000000000000006800,Nintendo Switch Pro Controller,platform:Linux,a:b1,b:b0,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,`

Should clearly swap the A/B and X/Y buttons, fixing my issue. However this edit in reality actually does nothing.

### Reproduction Steps

Try to use a Nintendo Switch Pro Controller with PCSX2.

### Expected Behavior

Bottom button is X, right button is O, top button is Triangle, left button is Square. I expected the line I added to my configs to achieve that.

### PCSX2 Revision

dev-1632

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Manjaro

### CPU

Ryzen 7 1700x

### GPU

RX 580

### Logs & Dumps

`PAD: controller (Nintendo Switch Pro Controller) detected, GUID:03000000000000000000000000006800`

**Comment by Mrlinkwii** [comment]
:wave:  atm you cant rebind the gamepad on linux , see #4414  , in terms of defaults, you need to go upstream for the SDL   (gabomdq /SDL_GameControllerDB ) and put an issue their :slightly_smiling_face:

**Comment by TheDiscordian** [comment]
Thank you for the quick response! I'm not sure if it'd be appropriate to rebind all the Switch controllers for an SDL database, as some people like A to be the right side button. I believe the issue is specific to PCSX2 as with this software people will be aiming for a Playstation layout (perhaps even a "Swap A/B X/Y" option would resolve this across the board). 

As for the rebinding, that linked issue is related to GUI, which other commentators stress that the new plugin removed the ability to rebind via the GUI. I'm fine without being able to rebind via the GUI, but you're suggesting there's not even a config option to rebind? Recompilation is the only option? If so I apologise, I opened a new issue as I'm comfortable using the INI config, which I thought was still supported.

**Comment by RedDevilus** [comment]
Only the windows side has this ability and we do want feature parity with it but that will take time and work.

I'll just sum up the situation

Linux;
Older onepad-legacy (removed due to merge):
Keybinding remapping 
onepad (merged):
Uses a file as a database, kinda a pain to adjust but will work as the GUI will only do keyboard remapping

Windows;
LilyPad:
Can do everything linux does without a database like it (it does have a xinput standard list but not every controller has xinput but can have dinput which does not have a database here)

Either way the issue is known and we sit in a position where the choice is limited at this time. Merging the features of the 2 old linux plugins wouldve been well appreciated but alas.

**Comment by tadanokojin** [comment]
Guys I think they understand it. They're trying to edit the controller setting via the database and it's not changing. I think that's the issue.

**Comment by tadanokojin** [comment]
OP I think you'd be better off going through our support channels instead since it's not entirely clear this is a bug.

**Comment by RedDevilus** [comment]
There are some inconsistencies with the lines to the database.
`SDL2 = 03000000000000000000000000006800,Nintendo Switch Pro Controller,platform:Linux,a:b1,b:b0,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,`

`SDL2 =` is never used in the db
`,platform:Linux` should always be at the end of the config as well.

**Comment by TheDiscordian** [comment]
> Guys I think they understand it. They're trying to edit the controller setting via the database and it's not changing. I think that's the issue.

I actually don't know where the database file is located, but I'd happily do that. I've been adding exactly this line to bot `PAD.ini` and `OnePad2.ini`:

`SDL2 = 03000000000000000000000000006800,Nintendo Switch Pro Controller,platform:Linux,a:b1,b:b0,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,`

I did find the database on this repo, and it doesn't appear to contain a line for `03000000000000000000000000006800`, but I'd happily add it and adjust if I knew where the DB is located. I was just under the impression that I can add new configs temporarily to `PAD.ini` / `OnePad2.ini`.

> onepad (merged):
> Uses a file as a database, kinda a pain to adjust but will work as the GUI will only do keyboard remapping

I don't mind editing the database, I just don't know where it's located.

>  There are some inconsistencies with the lines to the database.

I was following the instructions here: https://github.com/PCSX2/pcsx2/issues/2495 to come up with that line. Again, edited `PAD.ini` and `OnePad2.ini` as I don't know where the DB is located, and until now, I assumed it was compiled in.

**Comment by RedDevilus** [comment]
Pcsx2 codebase: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/PAD/Linux/res/game_controller_db.txt
Upstream where we get the database and where we refer to:
https://github.com/gabomdq/SDL_GameControllerDB

**Comment by TheDiscordian** [comment]
> OP I think you'd be better off going through our support channels instead since it's not entirely clear this is a bug.

Alright, I was just trying to use a feature referenced in the other issue. (#2495) so I assumed the INI param was supported.

**Comment by TheDiscordian** [comment]
> Pcsx2 codebase: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/PAD/Linux/res/game_controller_db.txt
> Upstream where we get the database and where we refer to:
> https://github.com/gabomdq/SDL_GameControllerDB

Thank you, but I still don't know how it's loaded in (dynamically? If so, where is it looking for this file?). I'll close this issue as there doesn't seem to be interest in it.

**Comment by Ziemas** [comment]
If noting else, I know for a fact that one thing that does work is setting the `SDL_GAMECONTROLLERCONFIG` environement variable.

Either exporting it before running PCSX2 or launching it like this should work provided your config string is correct.

`SDL_GAMECONTROLLERCONFIG="03000000000000000000000000006800,Nintendo Switch Pro Controller,platform:Linux,a:b1,b:b0,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b2,%" PCSX2`

**Comment by TheDiscordian** [comment]
@Ziemas I cannot thank you enough! No idea why the SDL option doesn't work in the INI files (it's either a bug, or the feature was removed and most people here didn't even know it ever existed), but your method works like a charm. Would be infinitely useful to users looking to rebind to have this written down somewhere.

**Comment by tadanokojin** [comment]
> Alright, I was just trying to use a feature referenced in the other issue. (#2495) so I assumed the INI param was supported.

No worries, I just wanna make sure someone can help you. Sounds like zei got you covered.

> I'll close this issue as there doesn't seem to be interest in it.

I wouldn't say that. I think people here are just expecting a bug/feature request (in particular, one that's already being tracked) and it's mucking things up with getting you an answer.

Anyways hope you sorted it.

**Comment by TheDiscordian** [comment]
> I wouldn't say that. I think people here are just expecting a bug/feature request (in particular, one that's already being tracked) and it's mucking things up with getting you an answer.

I think it is a bug though as @gregory38 clearly  points out in several issues like [here](https://github.com/PCSX2/pcsx2/issues/2010) that the configuration I'm attempting should in fact work, so I came here to report the bug. Instead no one's even acknowledging the INI files lol. Thanks for the help, but this is either a bug or a  removed feature, and I feel like my words are mostly falling on deaf ears. At the very least it's a docs issue as there are no docs about this, and two identical INI files again with no docs about the differences.

**Comment by tadanokojin** [comment]
I'll pass it along and see what the others say. I'm not on linux and we don't use SDL on windows. That's why I was saying it might be a better idea to go through the support channels since someone who does know these answers could help you and escalate to a bug if it indeed turns out to be. There's certain gotchas with editing the ini (gotta close pcsx2 before you do it, multiple ini files for things like you pointed out, sometimes it gets overwritten when the emulator loads, etc) that make it kind of unintuitive and seem like it doesn't work.

You're not falling on deaf ears I'm just trying to give you a better experience getting an answer.

**Comment by TheDiscordian** [comment]
> That's why I was saying it might be a better idea to go through the support channels since someone who does know these answers could help you and escalate to a bug if it indeed turns out to be.

Ah I misunderstood then, thank you for that. I thought you were redirecting me away to close this issue, and have me get support for rebinding the controller in general, rather than fix the underlying issue. I'll leave it to your discretion whether to re-open it. If I get free time for development, I'll instead submit a PR now that I have more of an understand of the issues surrounding the feature.

**Comment by samermurad** [comment]
@Ziemas I tried setting the env var the same way for macos but it didn't seem to work, any suggestion on how I can get this fix for macos?
