### ISSUE TITLE
BIOS extraction link broken in README

### ISSUE THREAD

**Issue by Piruzzolo** [PCSX2/pcsx2#4723]
### Description

As of title

### Reason

Well, yes

### Examples

Indeed

**Comment by tadanokojin** [comment]
it used to point to a config guide that's not there anymore, not directly to the tools page.
the equivalent now would probably be this: https://github.com/PCSX2/pcsx2/blob/master/pcsx2/Docs/PCSX2_FAQ.md#question-13-where-do-i-get-a-ps2-bios
