### ISSUE TITLE
[Feature Request] Consolidate Multitap (needing 2 activations)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4732]
### Description

1 global option for multitap instead of 2

Master;
1. Enable multitap in config:
![image](https://user-images.githubusercontent.com/24227051/132256631-ff2d17b5-3e8f-4340-bada-58fa8e37bb68.png)
2. Enable multitap in GamePad / LilyPad:
![image](https://user-images.githubusercontent.com/24227051/132256672-26bda9e7-f6e8-4ab9-8ffc-c9be1a20392c.png)
3. Configure correct controller to correct port
![image](https://user-images.githubusercontent.com/24227051/132256704-1813d10e-7262-41ff-82ad-468a34d88056.png)

### Reason

Less confusion, less technical debt, remnant of plugins

### Examples

Either always enable it permanently but hide the configuration behind the option:
![image](https://user-images.githubusercontent.com/24227051/132256762-2cac2487-15bc-46e4-aa92-706e3048e859.png)
And let it exist like this:
![image](https://user-images.githubusercontent.com/24227051/132256778-2640ca16-a405-4510-80fe-ff73932120cd.png)

Or make a cleaner way to enable it with the Port 1 Multitap in Gamepad.

**Comment by refractionpcsx2** [comment]
No longer an issue in Qt.
