### ISSUE TITLE
[Feature Request]: Automatically Configure Pad in Windows like Linux

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4734]
### Description

On the linux build there is a controller database that allowes the emulator to automatically configure many popular controllers reducing the need for user configuration. I'm asking for this for windows

### Reason

Jealousy of linux's automatic features

### Examples

it's all so tiring.

![so tiring](https://user-images.githubusercontent.com/8851653/132280664-d2ae9f0e-2df7-4542-9b15-37251e8a568e.jpg)

**Comment by vsub** [comment]
It is automatically configured on window too
I delete the LilyPad.ini,run pcsx2 and went to the settings and I saw that the XInput Pad 0 was configured
Even if you never go to the settings,pcsx2 will still use those settings

**Comment by lightningterror** [comment]
Xinput controllers are auto configured, others are on the Qt side.
