### ISSUE TITLE
[BUG]: ONI: Race condition between the VU1 and the CDVD subsystem.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4737]
### Describe the Bug

I can say with confidence, this is the weirdest bug I had the occasion of dealing with in PCSX2.

In the game "ONI", there is a race condition that happens between the VU1 and the CDVD subsystem causing an audio glitch in one area of the game under some cases.

**This deserve an explaination about how to reproduce it and what can fix that problem.**

This bug is random depending how the game reads data on the disc.

There are 2 cases here, loading a level before the TCTF HQ or just loading the TCTF HQ level.

If you load the TCTF HQ level after having played though a level, the bug will manifest with instant VU1

However, if you load the TCTF HQ level directly instead, now it's instant VU1 or fast CDVD wich will solve the glitch.

**This is indeed very very bad. The only real fix that does work in booth cases is instant DMA.**

**Real hardware was tested several dozens of time with every scenario possible, all of them doesn't produce the glitch so this is not a game bug**

### Reproduction Steps

Loads the 2 savestates provided with the blockdump and observe the issue.

### Expected Behavior

The first audio file should not play again after the memcard screen disapears.

### PCSX2 Revision

dev-1705-g18311d6a4-windows-x86

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

- Instant VU1 disabled - proper CDVD timings savestate 1:

https://user-images.githubusercontent.com/90222976/132364167-5788f8a4-8322-46f3-a6f9-ddba7356ddfb.mp4

- Instant VU1 enabled or fast CDVD checked savestate 1:

https://user-images.githubusercontent.com/90222976/132364326-524edd63-cfee-43f8-aece-72d3625abfef.mp4

- Savestate 2 will do the exact opposite.

### Logs & Dumps

https://drive.google.com/file/d/1U7ZF00iBarDMkzyPRFsxsSVwqVb4pX0C/view?usp=sharing

**Comment by gilderoylockhart01** [comment]
Ok so it appears the game needs the VIF FIFO to solve that problem.

**Comment by gilderoylockhart01** [comment]
Ok so the game is bad, really really bad, this is by far the weirdest bug I experienced in PCSX2.

It appears the race condition changes depending what level you played before. I explained in details the problem in the first post.

I tested real hardware during the whole day, and it's always fine no matter what.

It is also worth mentioning instant DMA will always work here. So yeah, extreme voodoo case here and really, this drove me nuts to say the *least*.

I think you guys will have a chance to really understand what's going on in that mess. I included everything that you need in the first post, the 2 savestates, blockdump and the memcard.

**Comment by gilderoylockhart01** [comment]
Good news. This PR solve the problem https://github.com/PCSX2/pcsx2/pull/4767. Yeah, crazy right? XGkick solving audio issues....

The game will need booth sync XGkick and instantVU1 disabled to work properly now.

**Comment by refractionpcsx2** [comment]
What? That sounds a bit random behaviour, I'm not sure I trust that.

**Comment by gilderoylockhart01** [comment]
I have a savestate to prove you that, I will send you it, you will see that in action.

**Comment by gilderoylockhart01** [comment]
There it is, I picked a different ingame FMV to better illustrate the point:
[ONI xgkick audio problem.zip](https://github.com/PCSX2/pcsx2/files/7179833/ONI.xgkick.audio.problem.zip)

Make sure to use your XGkick PR or the VU1 interpreter + instant VU1 disabled, in fact, it's the jaws unleashed changes that made that to work.

Also, the reason all the testing I did showed weird results is because of the BIOS issue when loading savestate during the boot sequence (instant DMA remain enabled). 

PS: sorry for the micro slowdowns, it's because I am running topaz ai in the background.

With sync XGkick + sync VU1 (take attention to the little sound comming from the ninja when he breaks glasses):

https://user-images.githubusercontent.com/90222976/133657539-6bef9d38-fc06-467b-99ed-e61f45c32509.mp4

Sync VU1 + instant XGkick (missing ninja sound)

https://user-images.githubusercontent.com/90222976/133657691-9733db9e-b43a-402f-ae6e-7f29d511f2e5.mp4

**Comment by refractionpcsx2** [comment]
well,  the only thing I can think of is the VU changes manipulate the timing of it.

**Comment by gilderoylockhart01** [comment]
Well, the good news is we will just have to put the XGkick fix into the DB and it will be fine because even instantVU1 also behave fine with the proper XGkick engaged.

**Comment by refractionpcsx2** [comment]
I don't get that at all

**Comment by gilderoylockhart01** [comment]
You mean you can't reproduce the problem?

**Comment by refractionpcsx2** [comment]
No I meanI can't understand why XGKick timing would affect sound playback, especially if instantvu1 is on it still fixes it.

**Comment by gilderoylockhart01** [comment]
Well, I will explain better, I think you got lost with my explaination and yeah, I badly explained it.

With syncVU1 you will need sync XGkick for the sound to work properly, but with instantVU1 you don't need it at all, but having it on doesn't change the behaviour for instantVU1.

**Comment by refractionpcsx2** [comment]
So the game is fine with Instant VU on? regardless of anything else?

**Comment by gilderoylockhart01** [comment]
Yes exactly.

**Comment by refractionpcsx2** [comment]
Strange.... but yes, sounds like things just change the timing enough to change the behaviour

**Comment by gilderoylockhart01** [comment]
In fact there is multiples ways of fixing that, setting the ee cyclerate to +1 will also fixes the problem, as does instant DMA

**Comment by refractionpcsx2** [comment]
That confirms what I was saying then.

**Comment by gilderoylockhart01** [comment]
Yup, but now at least we could easily fix it with the GameDB.

**Comment by gilderoylockhart01** [comment]
I will actually do a mega testing with pretty much any audio will game will produce to see which fix is the most effective timing wise

**Comment by gilderoylockhart01** [comment]
Ok so, I did test all the game's ingame FMV and the results are clear, only sync XGkick in tendem with the KeyOn PR can fix 99% of the audio glitches (the one in the other issue thread still persist).

The various EE timings doesn't always help in all scenarios and the closest to PS2 EE setting will behave exactly like stock cyclerate so yeah, EE timing doesn't seem to be the main problem.

So long story short, the Jaws Unleashed XGkick timing changes completely fix the problem. This issue can be closed once booth PRs are merged to master.

**Comment by gilderoylockhart01** [comment]
Ok, so it turns out the history will have a happy ending without any GameDB entry, this commit fixes the problem completely.

https://github.com/PCSX2/pcsx2/commit/8fe00617511c644e793c5adbe994bdf17e25ff15

**Comment by gilderoylockhart01** [comment]
Bad news, the bug was re-introduced by this commit: https://github.com/PCSX2/pcsx2/commit/b8f4a8ffb37e5e60bea76241a6b862d225c9c1a2

Now the only way to get rid of it is to disable instantVU1 as well as the INTC spin detection.

**Comment by refractionpcsx2** [comment]
as I told you, it's a random timing issue. it is not one specific thing, changing timings randomly will fix the issue. that commit did *not* break it, it just changed the behaviour, again.

**Comment by gilderoylockhart01** [comment]
Yeah, I do agree the "broken" word is not exactly correct as you said. However, I will open an other thread because it introduced a bug which makes the game unplayable now.

**Comment by refractionpcsx2** [comment]
Did you try FastCDVD and turning off Instant VU?

**Comment by gilderoylockhart01** [comment]
I opened a thread for this, in fact, MTVU was the bad boy of the story but, the non-mtvu behaviour is still strange.

**Comment by gilderoylockhart01** [comment]
Closing this thread again, this commit made the game far less carefull about VU timings in general https://github.com/PCSX2/pcsx2/commit/54d10d21ecc752a7452402a299836903002dd2db.

I will test the other issues on the other threads to conclude.
