### ISSUE TITLE
MTVU crash after a shutdown

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#474]
On linux, SysMainMemory::DecommitAll is called without stopping the MTVU thread.

Decommit will deallocate the VU memory therefore any access to vuRegs.Mem will crash (VU_Thread::ExecuteRingBuffer)

* Does it work on windows?
* How to fix it properly?
This kind of patch seems to do the trick but I'm not sure it is the correct way. Maybe we miss a synchro somewhere.
```
diff --git a/pcsx2/System.cpp b/pcsx2/System.cpp
index 25d1561..cbefe98 100644
--- a/pcsx2/System.cpp
+++ b/pcsx2/System.cpp
@@ -18,6 +18,7 @@
 #include "IopCommon.h"
 #include "VUmicro.h"
 #include "newVif.h"
+#include "MTVU.h"
 
 #include "SamplProf.h"
 
@@ -418,6 +419,8 @@ void SysMainMemory::DecommitAll()
        Console.WriteLn( Color_Blue, "Decommitting host memory for virtual systems..." );
        ConsoleIndentScope indent(1);
 
+       vu1Thread.Reset(); // Stop MTVU before we destroy the memory
+
        m_ee.Decommit();
        m_iop.Decommit();
        m_vu.Decommit();
```

**Comment by gregory38** [comment]
@sudonim1 
I need your opinion.

**Comment by sudonim1** [comment]
Reset() may be insufficient, it may be executing right then and no lock is acquired.

**Comment by gregory38** [comment]
Ok. I think the sync will be enough. The EE thread must surely be stopped before the removal of the EE memory. So no new command will be written in the MTVU ring.
