### ISSUE TITLE
[BUG]:  g_GameStarted not set to true when loading a savestate

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#4744]
### Describe the Bug

Noticed when testing another PR that if I loaded a savestate while it was going through the BIOS, it would continue to try to use instant DMA's (which only happen if g_GameStarted is false), however if you're loading a state, it can be assumed you're going past the BIOS screen (unless the CRC for your savestate is 00000000 of course).

### Reproduction Steps

disable fast boot and load a state for your game while the BIOS swirly lights and boxes screen is up.  Noticed when playing WRC where VIF DMA got stuck on a flush waiting for another DMA to finish.

### Expected Behavior

Flag is set when savestating in to a game and normal DMA timing resumes

### PCSX2 Revision

Any

### Operating System

Windows 10 (32bit)

### CPU

Ryzen 3900X

### GPU

2080TI

**Comment by MrCK1** [comment]
Fixed by https://github.com/PCSX2/pcsx2/commit/880107e72be757496d3b3be9647871df1d2abac8
