### ISSUE TITLE
[BUG]: Framelimiter broken in recent builds (super low fps)

### ISSUE THREAD

**Issue by Squall-Leonhart** [PCSX2/pcsx2#4749]
### Describe the Bug

Recent  builds of PCSX2 from both my own Windows 7 fork and upstream are demonstrating extremely low framerates when the Frame limiter is enabled.

I'll provide screens from the your latest Actions (a8a5064) build on 10 since thats what you guys support.

The issue manifests under D3D11, OpenGL and Soft.

### Reproduction Steps

1. Run PCSX2.exe (AVX2 is not supported on my 1680v2)
2. Load Kingdom Hearts 2 PAL
3. Toggle on Framelimiter

Notice that the game runs at less than 10% or less performance 

![image](https://user-images.githubusercontent.com/1098176/132655813-e0ee8cc0-8ed5-44cc-8ca1-f5ea3ce5f815.png)

Toggle Off Frame Limiter
Game runs turbo as expected
![Uploading image.png…]()

### Expected Behavior

The frame limiter should work properly.

### PCSX2 Revision

 a8a5064

### Operating System

Windows 10 (32bit)

### CPU

Xeon 1680v2

### GPU

GTX 1060

### GS Settings

![image](https://user-images.githubusercontent.com/1098176/132656219-0a3c2de6-e398-46e4-811c-315a1f94e791.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/1098176/132656340-13c5f66c-7775-4f40-968a-b90af1633f68.png)

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/1098176/132656404-5ddb7edc-ff84-40f6-a360-13ac390eb663.png)

![image](https://user-images.githubusercontent.com/1098176/132656423-995e0c0c-eaee-4127-a44f-3aef6c3ed146.png)

**Comment by refractionpcsx2** [comment]
You need to delete your ini files. you upgraded over an older dev build which isn't advised, since we changed the frame limiter value calculations you will only be set to 10% of what you used to be

**Comment by Squall-Leonhart** [comment]
> You need to delete your ini files. you upgraded over an older dev build which isn't advised, since we changed the frame limiter value calculations you will only be set to 10% of what you used to be

I considered that factor, but changing the value in the GS config didn't fix it either

**Comment by refractionpcsx2** [comment]
just delete your pcsx2_ui.ini

**Comment by Squall-Leonhart** [comment]
I see, its the base framerate adjust value, i didn't see a change to that in the commit messages.

**Comment by refractionpcsx2** [comment]
we're discussing ways to make it more user friendly in future, not sure what's being done though, I kinda stayed out of the conversion :P

**Comment by Squall-Leonhart** [comment]
makes sense for the UI to reflect the 100% in the same factor in all areas though :p

**Comment by Squall-Leonhart** [comment]
ok, so that was in bda80fc , easy to miss with all the changes
