### ISSUE TITLE
[Feature Request]: PCSX2 Daily Builds PPA - x64 Request

### ISSUE THREAD

**Issue by OdinVex** [PCSX2/pcsx2#4752]
### Description

Any chance of an x64 build for the PCSX2 Daily Builds PPA? Not all of us are stuck on archaic x86 rigs. Just asking for the *addition* of x64 builds.

### Reason

Not everyone wishes to taint their installations with x86 libraries and manage yet another architecture, some installations can't even tolerate it (compatibility issues or dependency issues).

It'd be nice to just install from the PPA and not have to manually recompile every time, especially if some issue were to show up, needing to debug whether it is coming from PCSX2 or from Mesa/GPU/...

**Comment by OdinVex** [comment]
I'm assuming x64 isn't supported as the PPA still states the following:

> ==HOWTO INSTALL==
> $ sudo dpkg --add-architecture i386

**Comment by F0bes** [comment]
x64 works, it's what I use for Manjaro (I think arch killed an i386 dependency we needed for 32 bit).
There are some issues though, notably with the SW renderer. I'm sure this request will be fulfilled once 1.8 release happens and x64 is actually tested for release.

**Comment by OdinVex** [comment]
> x64 works, it's what I use for Manjaro (I think arch killed an i386 dependency we needed for 32 bit).
> There are some issues though, notably with the SW renderer. I'm sure this request will be fulfilled once 1.8 release happens and x64 is actually tested for release.

I'm unfortunately stuck on an Ubuntu-like distro for laptop (runs almost all games full speed, Ryzen and such), so any Arch-like is out for me there.

**Comment by RedDevilus** [comment]
What about using the AppImages from actions?

**Comment by OdinVex** [comment]
> What about using the AppImages from actions?

I've never been a fan at all of AppImages or FlatPak or Snap. They were created to solve “dll-hell” but many contend they've failed.

**Comment by tadanokojin** [comment]
If you go to this page: https://github.com/PCSX2/pcsx2/wiki/Installing-PCSX2

Take note of this section:
> Note: The packages here are not maintained officially by the pcsx2 team. Any bugs or issues using the package need to be submitted through their respective package maintainers.

With regards to the PPA, it's located here: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily

While we used to maintain the PPA ourselves, that hasn't been the case in a long time and until recently it was broken entirely and fixed without our involvement.

Information about who runs the PPA is here:
https://launchpad.net/~pcsx2-team/+members#active

Note that both micove and greg have not been involved with the project for years now. My suggestion would be to get in contact with Jonathan Yip. Otherwise maybe wait for 1.8 as the plans right now are to drop 32 bit support entirely before then and I presume they will follow suite.

The only packages we officially maintain for linux are the AppImage binary distributions.

**Comment by OdinVex** [comment]
I was hoping for an official method. Ah well.

**Comment by tellowkrinkle** [comment]
At the moment we don't really consider x64 builds stable, things may change when we get the remaining x64 bugs fixed

**Comment by OdinVex** [comment]
> At the moment we don't really consider x64 builds stable, things may change when we get the remaining x64 bugs fixed

Isn't that what “unstable” means? pcsx2-_unstable_? A simple “this may be broken, but here's a try” would be enough, I'd think.

**Comment by F0bes** [comment]
> > At the moment we don't really consider x64 builds stable, things may change when we get the remaining x64 bugs fixed
> 
> Isn't that what “unstable” means? pcsx2-_unstable_? A simple “this may be broken, but here's a try” would be enough, I'd think.

If you think people are going to read the "this may be broken, but here's a try” before making an issue request or asking for support on forums / discord, you'd be incorrect.

I feel like we would be shooting ourselves in the foot if we allow users to easily download a broken and quite frankly untested build, if you want x64, just build it. 

Idk

**Comment by OdinVex** [comment]
> > > At the moment we don't really consider x64 builds stable, things may change when we get the remaining x64 bugs fixed
> > 
> > 
> > Isn't that what “unstable” means? pcsx2-_unstable_? A simple “this may be broken, but here's a try” would be enough, I'd think.
> 
> If you think people are going to read the "this may be broken, but here's a try” before making an issue request or asking for support on forums / discord, you'd be incorrect.
> 
> I feel like we would be shooting ourselves in the foot if we allow users to easily download a broken and quite frankly untested build, if you want x64, just build it.
> 
> Idk

I already do build x64, I have almost no issues (the GS plugin change goofed things for a while as did fmt and something else I forgot). “unstable” ... I get that can mean broken and frankly untested. In fact, that's exactly what I can take away from "unstable". Or does PCSX2 only release stable-only builds in the unstable? >_>

**Comment by tadanokojin** [comment]
We release stuff that might break (dev series) but in general we avoid things we know are broken. Tellow is referring to the latter when he says "not really stable". If you put something out and there's a bug in it that you didn't catch that's one thing, if you put something out you know is broken that's another. We know for example the x64 software renderer is broken, there are PRs to fix it but it's not ready yet. Either way, this is getting off topic. This has nothing to do with the PPA has x64 or x86 or whatever. That decision is up to the maintainer (or whoever decides to PR that change to them) and for all I care they can call it pcsx2-super-unstable-edition-with-blackjack.

**Comment by OdinVex** [comment]
> We release stuff that might break (dev series) but in general we avoid things we know are broken. Tellow is referring to the latter when he says "not really stable". If you put something out and there's a bug in it that you didn't catch that's one thing, if you put something out you know is broken that's another. We know for example the x64 software renderer is broken, there are PRs to fix it but it's not ready yet. Either way, this is getting off topic. This has nothing to do with if the PPA has x64 or x86 or whatever. That decision is up to the maintainer (or whoever decides to PR that change to them) and for all I care they can call it pcsx2-super-unstable-edition-with-blackjack.

Working fine for me, using hardware-renderer. I'll just keep compiling on my own. I was just hoping for a more official PPA with x64 support. Everyone's slowly moving away from x86, *especially* Linux distros.

**Comment by helkaluin** [comment]
I just want to add to this closed issue that the daily PPA actually has 64 bit builds for a while now. Just install `pcsx2-unstable` instead of `pcsx2-unstable:i386`.
