### ISSUE TITLE
[Feature Request] translation generation 

### ISSUE THREAD

**Issue by shikulja** [PCSX2/pcsx2#4753]
### Description

1. Update translation template .pot, add new lines to .po (xgettext\msgmerge)
2. Add automatic updating of translations to buildbot (msgfmt)
3. Add .sh and .cmd scripts to generate translations (in case # 1 # 2 is difficult to accept)

### Reason

- This will make it easier to update translations
(the template was last updated more than two years ago)
- Simplifies the work of translators, even if the template is not updated, it is enough to use scripts, instead of wasting time looking for the correct commands and preparing the script
- Users will be able to receive always up-to-date translation on the latest builds

### Examples

I haven't translated projects like this with gettext yet
so I had to spend time reading, downloading the gettext assembly on windows.
It's been 2 hours, I haven't even created a script to create a .pot yet. I do not think that I will want to create as I understood several separate .pot templates,
without any information about which source code files belong to which template.
Something like this)

**Comment by RedDevilus** [comment]
Related to: https://github.com/PCSX2/pcsx2/issues/3712

**Comment by refractionpcsx2** [comment]
Translations are being handled by crowdin, so this request is kinda moot.

**Comment by RedDevilus** [comment]
https://crowdin.com/project/pcsx2-emulator
