### ISSUE TITLE
[BUG]: Cannot save gamepad setting in 1.7-dev

### ISSUE THREAD

**Issue by drehren** [PCSX2/pcsx2#4764]
### Describe the Bug

Cannot save (or load) gamepad settings when path has special character

### Reproduction Steps

Have a "special" character in path, like á or ó and this error will pop up. Only happens to gamepad settings, other settings work fine.
![imagen](https://user-images.githubusercontent.com/2888452/133021104-cc386b78-a346-4b66-80ee-78d530b7d6cb.png)

### Expected Behavior

Be able to load and save gamepad settings

### PCSX2 Revision

dev-1719

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

GTX 960 2GB

**Comment by kenshen112** [comment]
https://github.com/PCSX2/pcsx2/pull/4005 - This PR should help that somewhat.

**Comment by drehren** [comment]
Hi, just tested it and it does indeed fix the issue, thanks.

**Comment by kenshen112** [comment]
Good to hear

**Comment by lightningterror** [comment]
Shouldn't be an issue on Qt.
