### ISSUE TITLE
[Feature Request] Add Hotkey for Resetting emulated system

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#4770]
### Description

See Title.

### Reason

Easily restart system without breaking immersion.

### Examples

N/A

**Comment by RedDevilus** [comment]
Soft reset like a Nintendo DS would be intresting.

**Comment by gilderoylockhart01** [comment]
The PS2 does support that natively with the power button, I wonder what PCSX2 does with that.

**Comment by refractionpcsx2** [comment]
PCSX2 doesn't emulate the power button, not sure how easy it would be, I know CDVD takes an interrupt from the power button, but I don't know if that will "turn off" or just reset

**Comment by RedDevilus** [comment]
Linking full boot/fast boot from thr GUI to a hotkey will have a similar effect that might be feasible for completing this feature request.

**Comment by gilderoylockhart01** [comment]
well, when the PS2 reset it also reset the CDVD with it so I assume this is what this interrupt is for.

**Comment by refractionpcsx2** [comment]
Well the reset signal goes from the power switch in to the Syscon and it only goes out to the Mechacon, which then passes it to the CDVD subsystem.

So I think it's pretty responsible for it.

**Comment by tadanokojin** [comment]
Is there really any benefit to LLEing the soft reset on the ps2 when you can just shutdown the emulation and start it again with the same settings?

**Comment by refractionpcsx2** [comment]
not particularly, I'd be more inclined to link it up to the PCSX2 reset :P

**Comment by RedDevilus** [comment]
Perhaps a candidate for when Qt is available where you just press a single button (or combo) and it automatically restarts the state (instead of going into the GUI to get a prompt to reset / swap disc).

**Comment by RedDevilus** [comment]
Fixed by: https://github.com/PCSX2/pcsx2/pull/5757
