### ISSUE TITLE
[Feature Request]: Overhaul GameDB serial system

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4771]
### Description

In it's current state, the GameDB is something i tried to make more consistent, fix typos and more. However as far as language goes it can have different interpretations or opinions about it. You can't just go with the correct naming and call it a day. 

So i've thought about it and talked about with others, the better middle-ground could be something like:

Original title in it's native tongue and alternative names:
![image](https://user-images.githubusercontent.com/24227051/133442926-d1de7df5-b7c9-48bb-aba8-cf7d9bd494ca.png)
Especially Japanese which have endless ways to present it.

```
Tl;dr
Original Name
English Name
Alternative Names

People can pick what they want to display in the Program Log.
```

### Reason

Everybody has to compromise in correctness, presentation or consistency for adding gamefixes and patches. GameDB is pretty annoying thing to work on as the issue is multiple people won't be happy when you do drastic changes even with good intentions and i understand why too:
https://github.com/PCSX2/pcsx2/pull/4768

### Examples

Let's take Japanese further into examples
Everyday can be presented as;
Romaji styles:
Nichijō 
Nichijou

Hiragana:
にちじょう

Katakana:
ニチジョウ 

Kanji:
日常
-----
Personally i prefer Hepburn with(out) umlauts.
![image](https://user-images.githubusercontent.com/24227051/133443915-dc16892c-0371-4c51-be92-ae3a259fe258.png)
![image](https://user-images.githubusercontent.com/24227051/133443993-85608fb4-f3fa-463a-97d1-41afaf2efe86.png)

----
Then again you can present Japan as Nihon and Nippon and the use of Kami (God in this context) turns into Gami with combination of other words.

**Comment by RedDevilus** [comment]
Romaji systems:
- Hepburn (Traditional)
- Hepburn (Revised)
- Nihon-Shiki / Nippon-Shiki
- Kunrei-Shiki (Revision of Nihon-Shiki)
- JSL
- Waapuro (More for typing romaji to Japanese)
- JWA
- Combining of styles / other variations
Katakana system
Hiragana system
Kanji system
Mixed style of katakana/hiragana/kanji/...

This won't be an easy task. - Hepburn (Revised) without special symbols is globally the most used though mix and match is still possible.

**Comment by lightningterror** [comment]
> People can pick what they want to display in the Program Log.

Is it really useful tho? Very low probability someone will change that, as for special symbols just write the name using English chars.
