### ISSUE TITLE
[Feature Request]: Have an additional keyboard hotkeys reference within the emulator itself

### ISSUE THREAD

**Issue by IlDucci** [PCSX2/pcsx2#4772]
### Description

Right now, there seems to be two ways of finding out what are the hotkeys for each element:
 - By going to the respective submenu (some would be easy to find, like the ones in the main window, but in other cases you would have to go to additional windows or options).
 - By googling them online.

I would like to suggest adding an additional offline, complete hotkey sheet. For example, in the Windows version it could be located within the Help section, like Help -> Keyboard Shortcuts.

The contents of the hotkey references are already written in here: https://wiki.pcsx2.net/Hotkeys

### Reason

This feature could make it easier to browse for specific hotkeys either while being offline or without having to delve too much inside the emulator's settings and windows (Specially the General Settings).

### Examples

Here's some screenshots of a texture viewer tool with a rather large amount of shortcuts called TiledGGD.
![imagen](https://user-images.githubusercontent.com/5641681/133496306-d207719b-8229-46a6-b6a3-c4ba6557de6f.png)
![imagen](https://user-images.githubusercontent.com/5641681/133496338-efd07fe8-f1a9-461c-b099-00120d7a639b.png)

**Comment by RedDevilus** [comment]
Relevant:
https://github.com/PCSX2/pcsx2/issues/3631
https://github.com/PCSX2/pcsx2/issues/4514

**Comment by lightningterror** [comment]
Already done on Qt.
