### ISSUE TITLE
[BUG]: Forbidden Siren 2's FMV Archive files get a black background, hiding the subtitles

### ISSUE THREAD

**Issue by IlDucci** [PCSX2/pcsx2#4773]
### Describe the Bug

Using the latest versions of the emulator (tested in pcsx2-v1.7.0-dev-1705 as well as v1.7.0-dev-1564) with the PAL version of Forbidden Siren 2, whenever an Archive item that contains a FMV is played, the background is turned into a black screen, hiding the subtitles, while the FMV is still being played and properly displayed.

This is a bug that could be missed as something "that is normal" simply because the next installment, Siren: Blood Curse for the PS3, actually covers the screen with black color while playing back FMV Archives... but it also displays subtitles.

This is not the case for Siren 2, as a matter of fact, this is a regression: playing an FMV Archive item in 1.6.0 stable displays everything correctly.

### Reproduction Steps

 - Play the game until you find/unlock an Archive item that contains an FMV (Here's a savegame that contains two of those, go to Archive No. 003 for reference: [SIREN2EXAMPLE.zip](https://github.com/PCSX2/pcsx2/files/7172802/SIREN2EXAMPLE.zip)
 - While not playing a mission, go to the Archive, then go into an item that has a camera icon at the title (top area of the screen).
 - Press X to play the video.

### Expected Behavior

The background elements and the subtitles should be visible alongside the FMV.

### PCSX2 Revision

pcsx2-v1.7.0-dev-1705

### Operating System

Windows 10 (64bit)

### CPU

Tested in both an i7-9700K @ 3.60 GHz (8 cores) and an i5-6600K @ 3.50 GHz (4 cores).

### GPU

Tested in both a RTX 2070 with 8 GB of RAM and an RTX 2060 with 6 GB of RAM.

### GS Settings

All settings are the default ones. Playing at native resolution.

### Emulation Settings

All settings should be the default ones.

### GS Window Screenshots

Screenshot taken in 1.6.0:
![Captura de pantalla 2021-09-15 215015](https://user-images.githubusercontent.com/5641681/133499934-2dad523a-0bfc-478a-906d-e268b5a4c3c3.png)

As you can see, the background elements and the subtitles are visible.

Screenshot taken in the 1.7.0 dev version:
![Captura de pantalla 2021-09-15 214829](https://user-images.githubusercontent.com/5641681/133499947-d2883fc1-cefd-4f0b-a317-41be939cf3ca.png)

### Logs & Dumps

[gs_20210915214657.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/7172825/gs_20210915214657.gs.xz.zip)

**Comment by IlDucci** [comment]
Status update: the bug actually occurs only while playing in GS's HW mode, both in 1.6.0 stable and in the 1.7.0 dev versions. The current workaround is playing in software mode.

**Comment by refractionpcsx2** [comment]
Can this be checked on the latest master? I suspect it might be ok now.

**Comment by IlDucci** [comment]
Somewhat:

When playing a video file in Vulkan, there's a brief flash of what seems to be a previous frame before the actual video starts, after that, everything plays back fine.

However, if you switch between renderers, the black screen effect reappears.

Software:
https://user-images.githubusercontent.com/5641681/221355680-24645c67-11d5-45b2-a807-9d3ce6ba9fa0.mp4

Vulkan (not counting renderer switching):
https://user-images.githubusercontent.com/5641681/221355699-fa7f7105-5a10-4c15-9f3b-36d8d5066159.mp4

**Comment by refractionpcsx2** [comment]
so mostly but there's a glitch frame? :D

**Comment by IlDucci** [comment]
> so mostly but there's a glitch frame? :D nice

Only if you do not switch renderers on the fly. Switch from HW to SW and then back and the black screen will reappear.

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/bef76e39-a85f-4812-8ccb-3bf73aedcca6)
its seems fine with teh gs dump provided @IlDucci  can you check if/when you get time

**Comment by IlDucci** [comment]
I can confirm that it works correctly now, and that switching renderers on the fly no longer displays anything off.
