### ISSUE TITLE
[BUG]: Numbers not displaying - Windows - Internal Shader: Shade boost

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4775]
### Describe the Bug

![image](https://user-images.githubusercontent.com/24227051/133615358-28fe6388-f8a0-4aa6-b5ad-9b81131f9335.png)

Linux seems to be unaffected.

### Reproduction Steps

1. Config > Graphics Settings > Shader Configuration >Shade Boost

### Expected Behavior

![image](https://user-images.githubusercontent.com/24227051/133615636-0cddb03e-fd26-49a5-bdcd-f2cd5c124f8a.png)

### PCSX2 Revision

1.7.0- dev1727

### Operating System

Windows 10 (64bit)

### CPU

i7-9750H

### GPU

RTX 2060M

### GS Settings

/

### Emulation Settings

/

### GS Window Screenshots

/

### Logs & Dumps

/

**Comment by lightningterror** [comment]
OSD config too, regression pr https://github.com/PCSX2/pcsx2/pull/4188
