### ISSUE TITLE
[BUG]: Single core shoots to 100% when trying to map a controller

### ISSUE THREAD

**Issue by ranzar** [PCSX2/pcsx2#4776]
### Describe the Bug

When I try to map a controller, I click for example on BUTTON L2, a CPU core (random) shoots up to 100% and pressing buttons on the controller does nothing. Core stays at 100% until I press ESC.

### Reproduction Steps

- Install the emulator, go to Config -> Gamepad Settings.
- Click on any button to remap.

### Expected Behavior

I don't mind having a core at 100% for a brief moment, but the emulator not getting the input is what weirds me out. This controller works perfectly fine with other emulators and games.

### PCSX2 Revision

dev-1744-gac87484ac

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

AMD Ryzen 9 5950x

### GPU

AMD RX 6900 XT

**Comment by F0bes** [comment]
Unsure what could be causing the core spike, but on Linux you can only map keyboard keys to the controller through that menu. Your controller should be plug and play.
