### ISSUE TITLE
[BUG]: Crash bug in SPU Reset (OK or Cancel from Config) [XAudio Only]

### ISSUE THREAD

**Issue by Squall-Leonhart** [PCSX2/pcsx2#4785]
### Describe the Bug

When leaving the SPU Configuration screen while a game is active, the emulator locks up then crashes.

### Reproduction Steps

Start a game (any game) using any of the windows builds
Open the SPU settings
Cancel or Ok out of the settings (changes not necessary)

Window goes unresponsive, fades out, hangs a moment and then finally closes.

### Expected Behavior

It probably shouldn't do that.

### PCSX2 Revision

a546cb8

### Operating System

Windows 10 (64bit)

### CPU

Xeon 1680v2

### GPU

GTX 1060

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7188662/emuLog.txt)

**Comment by Squall-Leonhart** [comment]
left the settings stuff blank beacause i literally reproduced this with the Ini's folder gone and just a  bios selected

weird stuff.

**Comment by refractionpcsx2** [comment]
yep, we're aware of the issue and looking in to it, it only happens when you're using XAudio currently.

**Comment by Squall-Leonhart** [comment]
It looks like Xaudio is being unloaded, the library is not a loaded module in the dump file.

**Comment by refractionpcsx2** [comment]
it crashes when it unloads, and the new WIL library does a fail fast on it. The old ATL just ignored it.

**Comment by Squall-Leonhart** [comment]
According to the microsoft docs thats more or less expected behavior of unloading the dll xD, there should be a way to fix it by shutting down the mastering voice and contexts.

**Comment by Squall-Leonhart** [comment]
I've shot a message to Chuck Walbourn, he might have a clue.

If someone figures out a solution in the meantime, then feel free to close :)

**Comment by Squall-Leonhart** [comment]
I think i see an issue with the code that would cause this, i commented it on the commit

**Comment by Squall-Leonhart** [comment]
spinning up a build to test now

**Comment by Squall-Leonhart** [comment]
Confirmed fixed

**Comment by Squall-Leonhart** [comment]
I believe the entire block here can be removed

```	{
		// Clean up?
		// All XAudio2 interfaces are released when the engine is destroyed,
		// but being tidy never hurt.

		// Actually it can hurt.  As of DXSDK Aug 2008, doing a full cleanup causes
		// XA2 on Vista to crash.  Even if you copy/paste code directly from Microsoft.
		// But doing no cleanup at all causes XA2 under XP to crash.  So after much trial
		// and error we found a happy compromise as follows:

		m_voiceContext = nullptr;

		if (pMasteringVoice != nullptr)
			pMasteringVoice->DestroyVoice();

		pMasteringVoice = nullptr;

		pXAudio2.reset();
		xAudio2DLL.reset();
	}```
	
this was relevant to Xaudio 2.7.

**Comment by Squall-Leonhart** [comment]
Here is my changes

https://github.com/Squall-Leonhart/pcsx2/commit/52d5aa5dd477e8542b72b7cdeaf0eb1a064a9aa3

I've confirmed the Xaudio thread and DLL is unloaded when the SPU settings are opened.
I've confirmed the Xaudio thread and DLL are reloaded when the SPU settings are closed either via cancel or ok.
There are no crashes on exit
Changing to/from Xaudio works.
There are no performance losses/gains.

**Comment by Squall-Leonhart** [comment]
Alternatively, there is a line casting a com_ptr that is entirely unnecessary for Xaudio 2.8+ that may be the culprit on line 252

https://github.com/PCSX2/pcsx2/blob/1ee0e23617414cfa86eb6e9ce2b5f44b644b03a8/pcsx2/SPU2/Windows/SndOut_XAudio2.cpp#L252

**Comment by seta-san** [comment]
is there really a reason to have an output module other than xaudio on windows at this point? No Sound seems like it's purely a debug option but refraction has so incredibly nailed down spu emulation i'm not even sure that's necessary anymore.

**Comment by refractionpcsx2** [comment]
I use portaudio, because the latency is < 30ms, unlike xaudios ~80ms

**Comment by Squall-Leonhart** [comment]
WASAPI ftw.
