### ISSUE TITLE
Feature Request: Save/Load BIOS settings from (CFG) file

### ISSUE THREAD

**Issue by escape209** [PCSX2/pcsx2#480]
So I was wondering if it would be possible to implement a feature that would let you save the current BIOS settings to a file and then be able to edit it as needed. 

The main reason I want to see this feature implemented is because (at least in Burnout 3: Takedown) Boot (Fast) seems to use the default BIOS settings/doesn't load the current BIOS settings (since it skips it), whereas Boot (Full) does. A personal gripe I have is with games that set 16:9 Widescreen mode based on the BIOS settings.

By having the BIOS settings be loaded from a file (or maybe even be editable within PCSX2's menu interface), things would be a good bit more convenient, even if not all games have this 'problem.'

Thanks in advance.

PS. While I would be very happy to see this feature implemented, I wouldn't mind at all if it isn't possible to add in.

**Comment by avih** [comment]
I'm not sure I understand the request.

Let's say you save/edit this cfg file. When will it be used? I.e. at which scenario will it get applied automatically?

**Comment by adamd10d** [comment]
I was thinking on Boot (Full)/(Fast) clicked. And by settings, I mean the settings in "System Configuration" in the PS2's BIOS.

**Comment by avih** [comment]
oh, you mean to boot full, somehow save the settings which the bios has, then save the settings, then boot fast - and it will use those saved bios settings while still skipping the whole (full) bios boot section?

Interesting. Probably non trivial. We're accepting patches ;)

**Comment by mirhl** [comment]
Another annoyance this would solve is that unless I use full boot, pcsx2 always defaults to English

**Comment by sudonim1** [comment]
Okay about this, there are issues.  I'm going from memory here so I might get some of this wrong:
There are different versions of the syscall to get this information depending on the BIOS version which use a different structure.  The structure and location of the setting in SRAM is also BIOS version dependent, although iirc there were only two locations.

**Comment by avih** [comment]
Worth stating, however, is that as far as I can tell the only improvement such feature brings is that we can do fast boot instead of full boot for games which depend on bios setting.

Considering that the bios can run quite fast when not frame limited, then we're talking about saving about 5s. TBH, I'm not sure it's worth the time which needs to be spent in order to make it work correctly. But then again, it's not completely useless either.

**Comment by sudonim1** [comment]
Well changing SRAM based on the settings is almost exactly as viable.

**Comment by CookiePLMonster** [comment]
This was brought up on Discord recently again. DobieStation "solves" this by HLEing the system calls responsible for obtaining this sort of data.

Given how many widescreen hacks are forcing games to take widescreen code paths to allow for Fast Boot, an introduction of this feature could cut down on the amount of required widescreen hacks.

Another idea related to that was to tie these settings to existing emulator options:
* BIOS language - PCSX2 language
* Wide/Normal option - Aspect Ratio option in PCSX2
