### ISSUE TITLE
[BUG]: Sega Ages - Virtual On, shadows rendering issue.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4806]
### Describe the Bug

In the game "Sega Ages - Virtual On", the shadows are rendered in white while they should be black.

None of the existing hacks/settings can fix the problem.

Note: Dobiestation displays the shadows fine.

### Reproduction Steps

Load any level in the game "Sega Ages - Virtual On" and see the shadows color being wrong.

### Expected Behavior

The shadows should be black like on real hardware.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

PCSX2:

<img width="900" alt="Capture" src="https://user-images.githubusercontent.com/90222976/134330536-3ee742f4-e11c-4ce8-b746-78e5940f4c21.PNG">

Real hardware (taken from a youtube gameplay):

<img width="438" alt="Capture2" src="https://user-images.githubusercontent.com/90222976/134330590-35c79ce1-81f3-4e67-ba69-4bfbf0b0ef48.PNG">

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1z8odfLqaa3-elMdVvMWo8ZkHFcYElOqf/view?usp=sharing

Don't hesitate to ask the GSdump if needed.

**Comment by prafullpcsx2** [comment]
This was probably broken between r4289 and r4310 because r4288 gives correct shadow. But it may have worked due to luck/ some other mistake in the code.

**Comment by prafullpcsx2** [comment]
I was testing this game again today and realized that EE clamping Full makes the shadows black. Other glitches are still present.

**Comment by gilderoylockhart01** [comment]
Thanks a lot to have test that, I feel dumb not to have test that.

**Comment by gilderoylockhart01** [comment]
Sorry, we will have to reopen this. The game still have problems with the life bar for exemple, it is now black instead of the intended colors:

![image](https://user-images.githubusercontent.com/90222976/134768861-b527aaa3-fc77-47a3-aeea-6310854a25df.png)

**Comment by refractionpcsx2** [comment]
Is it only black after the clamping change? Or was it already like that?

**Comment by gilderoylockhart01** [comment]
It is black even with the clamping change. Btw, clamping to none it preferable in this game but I will wait a gameDB pr before asking for the changes.

**Comment by refractionpcsx2** [comment]
why is none preferred?

**Comment by gilderoylockhart01** [comment]
It is slighty faster, but by a very small margin.

**Comment by refractionpcsx2** [comment]
I'm not keen on floats going wildly unclamped.

**Comment by gilderoylockhart01** [comment]
Ok then, but should I open a other thread for that secondary problem?

**Comment by refractionpcsx2** [comment]
can do, sure

**Comment by gilderoylockhart01** [comment]
Well, in a way I prefer waiting a bit before doing it, if it's just a clut issue again, that will make one more useless thread.

**Comment by refractionpcsx2** [comment]
CLUT doesn't do anything scary, and the colour of the health bar seems to follow the shadow colour. 

I also checked my local CLUT changes and it was still broken (but as I said, this game does nothing that would break even the current implementation)

**Comment by gilderoylockhart01** [comment]
Ok then, thanls for having test that, I will open a new thread when I have some free time.
