### ISSUE TITLE
[Feature Request]:Option to still load dev9 and input plugins

### ISSUE THREAD

**Issue by strikersix23** [PCSX2/pcsx2#4807]
### Description

Should be able to load input or dev9 plugins on nightlys

### Reason

I have issues with builtin input and dev9 settings I would still like the ability to load these plugins if at all possible as alternative source rather than full plugins

### Examples

N/a

**Comment by Mrlinkwii** [comment]
The capability of loading plugins are gone and aren't coming back .Please open an issue for the specific issue you are having :slightly_smiling_face:
