### ISSUE TITLE
[BUG - Voodoo]: Max Payne, FMV stuttering issue.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4808]
### Describe the Bug

In the game "Max Payne", the intro FMV will exhibit a sound lag issue especially near the end of the cutsceen (the 3d realm logo is a good test for that).

Note: +1 cyclerate helps getting rid of that problem.

### Reproduction Steps

Load the savestate provided with the dump at stock emulation settings, look the FMV in it's entirety and notice the sound problem when the 3D realm logo is displayed as well as some crackling when displaying the prior Max Payne logo.

### Expected Behavior

The FMV should not have any audio problems.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

+1 cyclerate to fix the FMV problem.

### GS Window Screenshots

The bug in action:

Stock cyclerate (pay attention to the 3D realm sound bug):

https://user-images.githubusercontent.com/90222976/134373711-ee0207bb-e7ac-4f9e-84fa-046d3a816f2d.mp4

+1 cyclerate:

https://user-images.githubusercontent.com/90222976/134373758-592520b0-6cde-46a0-828c-1df0d358c3a6.mp4

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/124KsFoH4dCvO_y3IjMao-u-dveUBDKLt/view?usp=sharing

**Comment by MrCK1** [comment]
Tested dump on 1.7 2954 and could not reproduce the issue anymore
