### ISSUE TITLE
[Feature Request]: Implement Dobiestation's automatic clamping.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4810]
### Description

In the Dobiestation emulator, clamping is handled automatically depending what the game needs on booth the EE and VU parts. This massively simplify testing, reduces the amount of GameDB PRs/entries, as well as better multi-demo disc handling. 

The only con to this approach is the fact zero clamping is not supported in the process.

In PCSX2 I would imagine a GUI option to force zero clamping can be a thing and would be way cleaner than our current design.

### Reason

This would eliminate the need of chassing clamping related bugs in the whole PS2 librairy as well as better compatibility consistency, the team wouldn't have to have a specific game if it only needs a clamping fix.

It would also simplify the UI design by regrouping VU fixes together instead of the split VU/hack window settup we currently have.

### Examples

The UI how I see it with my feature request:

<img width="689" alt="Capture" src="https://user-images.githubusercontent.com/90222976/134388702-b506441e-340c-4483-b0e2-876b1ecae033.PNG">

**Comment by refractionpcsx2** [comment]
Dobistation doesn't have automatic clamping, it's always on full, all the time, and that breaks some games.

**Comment by gilderoylockhart01** [comment]
Ah ok, well, should I close the feature request then?
