### ISSUE TITLE
[BUG - GS Hardware]: TimeSplitters Future Perfect - Garbled screen when using crane/etc

### ISSUE THREAD

**Issue by solstice0** [PCSX2/pcsx2#4814]
### Describe the Bug

In the game there are times when you can control a crane, security cameras and other devices that take you out of the normal first person view and display the view of the device. Currently when using these, the screen displays junk, although the general colors look correct (see screenshot). This bug is present in HW mode but not SW mode.

Interestingly, but probably not relevant, a very similar bug is present in this game when using the PS2 classics emulator on a homebrew enabled PS3.

### Reproduction Steps

In the second level, play thru it until in the castle. in the center of the 2nd story is a control panel for a crane. Activate the crane to see the bug.

### Expected Behavior

Non-garbled view from the crane/etc

### PCSX2 Revision

1.7.0~git202109211732+202109212352~ubuntu20.04.1

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 20.04

### CPU

i7-3770

### GPU

GT 1030

### GS Settings

All default

### Emulation Settings

All default

### GS Window Screenshots

HW:
![image](https://user-images.githubusercontent.com/11930112/134431363-fd3eb4a6-e295-4788-a05f-ed6d60fb90b9.png)

SW:
![image](https://user-images.githubusercontent.com/11930112/134431554-6ee5e58e-c6d8-42bc-afea-2cfb780ee496.png)

### Logs & Dumps

Can't find PCSX2 snap folder.

**Comment by tadanokojin** [comment]
Config->General Settings->Folders
Look at the one labeled "Snapshots".

Would appreciate a gs dump.

**Comment by RedDevilus** [comment]
How to create a GS Dump
Single Frame: Shift + F8
Multi Frame: Ctrl + Shift + F8 (hold for x seconds)

Single frame dumps should be suitable for most cases.

NOTE: Your GSdx settings are independent of the dump. Changing your settings will not effect the dump in any way.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by solstice0** [comment]
@tadanokojin gs dump 
[gs_timesplitters_future_perfect_crane_bug.zip](https://github.com/PCSX2/pcsx2/files/7214436/gs_timesplitters_future_perfect_crane_bug.zip)

**Comment by tadanokojin** [comment]
In HW hacks enable autoflush.

**Comment by solstice0** [comment]
thanks, its slow but I can see now. if my rig cost more than $150 it would probably play fine

**Comment by RedDevilus** [comment]
Try 700+ USD. Emulation tends to require good specs, perhaps even more than for regular PC games.

**Comment by tadanokojin** [comment]
Let's not get off-topic.

**Comment by murtisoft** [comment]
I was using Bilinear (Forced) texture filtering, and that still causes this to happen (v2.7.523)
Any other texture filtering option fixes it, in case anyone ends up searching this issue.

**Comment by refractionpcsx2** [comment]
Then don't use that filtering? That's a hack anyways, it should be on the (PS2) setting.
