### ISSUE TITLE
[BUG]: Lego Racers 2 screen fails to update GS HW

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#4816]
### Describe the Bug

In HW mode the GS fails to update the screen properly.

### Reproduction Steps

load the GS Dump (or if you have the game just load the game in hardware mode)

### Expected Behavior

The screen updates

### PCSX2 Revision

Any

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3900X

### GPU

2080TI

### GS Settings

Irrelevant beyond HW mode (DX or OGL), no hw hacks do anything.  ZeroGS had a hack called "Tex in Target" which I think was basically an overlapping draw hack.

### Logs & Dumps
[legoracers.zip](https://github.com/PCSX2/pcsx2/files/7220089/legoracers.zip)

**Comment by JimScript** [comment]
I have played the game ,and through a closer look at some screenshots, I noticed a pattern. The game's render seems to use a 10x7 grid of 64x64 rending tiles, and when in hardware mode it only properly renders the first tile. The tiles scale with the the internal resolution, so at 8x the only properly rendering part is the 512x512 tile in the top left corner.

**Comment by tadanokojin** [comment]
yes it's the size of a gs page, the game is updating by incrementing the base pointer which is a problem for our cache.
