### ISSUE TITLE
[BUG]: Pressing ESC then Resuming Causes Black Window

### ISSUE THREAD

**Issue by ThisNekoGuy** [PCSX2/pcsx2#4817]
### Describe the Bug

Pressing the ESC key then attempting to resume the game returns to the game with everything rendered as a black window (occurs with every game I've tried, personally)

Shutting down the game and reloading it entirely in the same session will still reproduce the issue

### Reproduction Steps

1) Load any game (in hardware mode)
2) Get to the main menu, though not required
3) Press the ESC key
4) Navigate to `System > Resume` in PCSX2 -or- shutdown the game and reload it
5) Witness the game rendered as a black screen

### Expected Behavior

The game should resume normally
(Having upscaling enabled can cause the game to additionally drop in speed at an accelerating rate but this isn't responsible for the black screen issue itself.)

### PCSX2 Revision

1.7.0-dev-1745-g0a7b72534

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 7 3700X @ 3.6GHz

### GPU

RTX 2080 Ti (Driver: 470.63.01)

### GS Settings

![image](https://user-images.githubusercontent.com/28468662/134585912-3671f5fa-9b96-47ed-8cf4-ba9615a12741.png)
![image](https://user-images.githubusercontent.com/28468662/134585942-c41eec46-b34f-4eb8-8633-05798003400a.png)

### Emulation Settings

As per [this page](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues) I have the preset set to 1, and the issue is reproducible in this state, but I initially encountered this issue in preset 2. These are the only non-default settings I have:

![image](https://user-images.githubusercontent.com/28468662/134586315-9e6f5f0b-43dd-4baa-98a7-0da7fbee49d4.png)

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/28468662/134587981-249d70d6-94f2-45f9-959f-840cf9356274.png)

### Logs & Dumps

[log.txt](https://github.com/PCSX2/pcsx2/files/7220941/log.txt)
[FFX-GS-Dump.zip](https://github.com/PCSX2/pcsx2/files/7220933/FFX-GS-Dump.zip)

The screenshot included with the dump doesn't show the black screen for some reason I don't know though

**Comment by RedDevilus** [comment]
` /mnt/bigStorage/Gaming/Lutris/Emulation/PS2 Emulation/Final Fantasy X.iso`

Is this running on physical DVD?
Why do you use Safest?

Besides this seems more for support in Discord.

**Comment by ThisNekoGuy** [comment]
It's not running on a physical dvd and I'm using safest, as I already mentioned, because [this page says to do so](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues)

**Comment by tadanokojin** [comment]
Can you test default settings and see if you can reproduce?

Config -> Clear All Settings

**Comment by ThisNekoGuy** [comment]
This stops the black-screen resume

**Comment by RedDevilus** [comment]
Can't (seemingly) reproduced on Linux - assumed fixed. Re-open if needed.
