### ISSUE TITLE
[BUG]: Outrun 2006 - HW graphics in menu

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#4823]
### Describe the Bug

overlays an improper graphic
![hw](https://user-images.githubusercontent.com/8851653/134758024-663736f7-36d7-42fd-8583-363d57da6094.png)

### Reproduction Steps

occurs when choosing your car

### Expected Behavior

![sw](https://user-images.githubusercontent.com/8851653/134758031-2e6711ba-5a75-4a25-aef4-e51bf23e3d18.png)

### PCSX2 Revision

dev-1801

### Operating System

Windows 10 (32bit)

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

round sprite - full 

### Logs & Dumps

[gs_20210924233415.gs.zip](https://github.com/PCSX2/pcsx2/files/7229149/gs_20210924233415.gs.zip)

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
Looks like it improved as of latest. There's still junk shown for a split frame when you first enter the car select screen and cycle through cars but otherwise works well.
![ot2](https://user-images.githubusercontent.com/92535412/220822583-f437e1ac-e36b-4372-8570-4f93f1d30c45.png)

**Comment by seta-san** [comment]
nice catch. it is fixed. also the fps are much more stable in alot of areas. i call this a win.

**Comment by prafullpcsx2** [comment]
Just want to add that Car models in Car Select screen seem to be in Native resolution and scaling isn't working there.

**Comment by seta-san** [comment]
> Just want to add that Car models in Car Select screen seem to be in Native resolution and scaling isn't working there.

i noticed that too. i've just never seen a 3d model not upscale like that so i assumed that it wasn't really a 3d model... or it was some sort of internal software renderer.

**Comment by refractionpcsx2** [comment]
it must be doing something funky with the car like downloading the graphics then reuploading it and using that version or something, the only reason anything would not upscale is if it gets forcefully removed from the hardware renderer.

**Comment by seta-san** [comment]
We found out it’s not really a 3d model but a sort of video of one

**Comment by refractionpcsx2** [comment]
If that's true, can you explain why there's 94 VU1 programs for that screen alone and it crawls to 4fps if you disable VU1?

**Comment by seta-san** [comment]
![7864f2f6c1044ced-00005a80](https://user-images.githubusercontent.com/8851653/221275589-c7938574-8f93-4d0a-bd7c-85d26b48e937.png)
![7865b9691375d1f3-00005a80](https://user-images.githubusercontent.com/8851653/221275591-042efb12-c973-4440-a172-04f5f9cd73b6.png)
![7868fe4adac8944d-00005a80](https://user-images.githubusercontent.com/8851653/221275593-dfff07cf-0415-4443-8d97-8b743279da5a.png)

i tried to look at the textures and i got a bunch of these for every frame of animation. they don't look like textures for a 3d model. they look like a slice of images of a 3d model.
