### ISSUE TITLE
[BUG]: Spiderman 3, texture problems with the software render.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4825]
### Describe the Bug

The game "Spiderman 3" have issues with the software render where distant buildings shows corrupted textures.

### Reproduction Steps

Load the multi-frame GSdump and see the problem.

### Expected Behavior

The textures should display just fine.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

PCSX2 (pay attention to the textures of the building in front of spiderman):

![gs_20210925140347](https://user-images.githubusercontent.com/90222976/134770961-ffefca5d-d890-4f51-b6dc-b9612e7f276f.png)

### Logs & Dumps

Multi-frame GSdump: https://drive.google.com/file/d/14wNA1z3ES8V8PnPNH9PgBM5_cVLgEp26/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Have you got mip mapping disabled in your software mode settings?

**Comment by gilderoylockhart01** [comment]
Nope, everything is at stock settings, including mipmapping.

**Comment by prafullpcsx2** [comment]
Do you have a memory card save leading to this area?

**Comment by gilderoylockhart01** [comment]
[Spiderman 3 save.zip](https://github.com/PCSX2/pcsx2/files/7229918/Spiderman.3.save.zip)

Just fly around, you will see the glitch is very obvious. If you want a savestate in the place I can do it but it shouldn't be necessary.

**Comment by prafullpcsx2** [comment]
Disabling mipmapping in SW mode seems to fix the issue?

**Comment by refractionpcsx2** [comment]
> Disabling mipmapping in SW mode seems to fix the issue?

yeah it does, I had a quick look but I'm not sure if the problem is the selection of MIP level or if it's a clamp/repeat problem with the selected MIP level.

**Comment by refractionpcsx2** [comment]
Just to give some more information which I discovered during investigating another issue.  If you disable the JIT Rasterizer, this problem doesn't happen, it all looks normal.

**Comment by lightningterror** [comment]
Is this still an issue?

**Comment by refractionpcsx2** [comment]
yes

**Comment by F0bes** [comment]
Looked into this, this is the draw setup that breaks the mipmapping texture.
```
007590053FC4904E Y fpsm:2 zpsm:3 ztst:0 ztest:0 atst:1 afail:0 iip:0 rfb:1 fb:1 zb:0 zw:0 tfx:1 tcc:1 fst:0 ltf:0 tlu:1 wms:0 wmt:0 mmin:1 lcm:1 tw:5 fba:0 cclamp:1 date:0 datm:0 prim:3 abe:0 3333 fge:0 dthe:0 notest:0 pabe:0 aa1:0 fwrite:1 ftest:0 zoverflow:0 zequal:0 zclamp:0 edge:0
```

I tried to look into it but I don't know how to compare the JIT and C rasterizer in order to debug. :sweat_smile:
