### ISSUE TITLE
[BUG]: DEV9 - Automatic Gateway address doesn't work

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#4828]
### Describe the Bug

The **Auto** option next to the Gateway Address of the DEV9 configuration doesn't work. You have to manually input it.
Example:
Works
![image](https://user-images.githubusercontent.com/4414625/134785190-528efde5-bd80-4a9e-b12b-46caa54342f1.png)
Doesn't work
![image](https://user-images.githubusercontent.com/4414625/134785195-6b99fb2d-6e00-4f99-be14-3548fbcc3a2b.png)

### Reproduction Steps

I have tried **Gran Turismo 4: Online Public Beta** myself, but reproducing this should be easy.
Ingame network settings
![image](https://user-images.githubusercontent.com/4414625/134785236-f913dd8b-8536-44e1-adba-4ea60041e808.png)
DEV9 settings
![image](https://user-images.githubusercontent.com/4414625/134785243-1fa68bf4-0099-45af-afd3-678302028b0e.png)

If you try to connect with the Gateway Address set to **Auto**, the game will throw this error (ignore the IP it's not my screen)
![image](https://user-images.githubusercontent.com/4414625/134785262-2b143bf4-b999-4a85-b70c-a9761cc5b7ae.png)

However if you set Gateway Adress manually to the one your network adapter uses (in my case it's 192.168.0.1)
![image](https://user-images.githubusercontent.com/4414625/134785190-528efde5-bd80-4a9e-b12b-46caa54342f1.png)
then the game will successfully connect
![image](https://user-images.githubusercontent.com/4414625/134785294-62336558-f2ac-4bef-8611-0ce8011bdd86.png)

### Expected Behavior

The **Auto** option of the **Gateway Address** should actually do what it says and use the one defined by my PC network.

### PCSX2 Revision

dev-1768

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i7-10700K 3.8 GHz

### GPU

Nvidia GeForce RTX 3070

### Logs & Dumps

https://gist.github.com/Blackbird88/5ec556dd468757dc3066da74714573a0

**Comment by refractionpcsx2** [comment]
pinging TheLastRar

**Comment by TheLastRar** [comment]
Can you test this PR to see if it resolves your issue? https://github.com/PCSX2/pcsx2/pull/4834 to see if it fixes your issue
