### ISSUE TITLE
Static Analysis of PVS-Studio

### ISSUE THREAD

**Issue by RebelliousX** [PCSX2/pcsx2#483]
Hello,

I had the chance to examine PCSX2 project with PVS-Studio Static Analyzer. 
Github doesn't support attaching Excel files, but here is a link from my Dropbox:
https://www.dropbox.com/s/sswkcfqj9g1x6vq/pcsx2_suite_2013.xlsx?dl=0
Again the report of the analysis is in Excel format. It is definitely worth looking at!! Even if some of 
the reported code mistakes could be false positive, or something that the devs of PCSX2 overlooked.

You can get get more information and a detailed explanation about a specific error Codes using the online documentation:
http://www.viva64.com/en/Vxxxx
replacing "xxxx" with the code number.

The good thing about the report, it gives you the file name, line number and a brief message explaining the error, visit viva64 to get the full explanation.

I have seen some possible memory leaks in the report or dangerous bit shifting.

Note: I didn't do the whole solution of PCSX2 suite, only PCSX2 project. If anybody interested, I could
upload that too.

There is another static analysis which is free and also good called CppCheck, Again, if anybody is
interested, I could upload a report of that too.

I hope this will help.
Regards, Rebel_X

**Comment by uyjulian** [comment]
Other tools:
Coverity
Cppcheck

I know there are other static analysis tools out there (they have been used often in wine)

**Comment by gregory38** [comment]
Could you add the git hash of the version tested? (to keep line number useful).

**Comment by RebelliousX** [comment]
@gregory38 Sorry, I didn't mention anything about which version was analyzed. I downloaded the master as zip file, two days ago, so it should be current.

I use mercurial for my projects, but I installed git to clone and get the hash file.

I used: "git rev-parse master"
SHA: 5ed3f5f1a4e7fd6a2180a855b4ca59004fb6c160
Titled: "Fix title from 1.0.0 to 1.2.0"

But, I am not really sure why the built PCSX2-dbg.exe shows 1.3.1-0 (git) instead of 1.3.1-5ed3f5f (git).

**Comment by gregory38** [comment]
Thanks for the hash.

**Comment by RebelliousX** [comment]
Hi @gregory38 I just did a re-analysis of pcsx2 project only and removed the 64 bit analysis to reduce the amount of false positives. The generated analysis is an HTML table, which you can put the HTML file into PCSX2 solution directory to allow you to open source files from the generated links. Also, the error codes are linked to viva64 website which gives a further explanation and examples/implications of the erroneous code.

This is based on the latest commit as of writing this SHA: cbd2417833104d3de42f3ca69ce038a1ffc52fb6 
of the master branch.

Have a look at it if you would please and if you have time :) You might find something interesting.

Here is a link to the HTML file from my Dropbox:
https://www.dropbox.com/s/pnih39v78p91fl8/pcsx2_project.html?dl=0

If you are interested about the other projects in PCSX2 solution, let me know.

**Comment by avih** [comment]
Thanks for the analysis.

Few slightly off topic comments:

- It looks like the links to the files ended up as absolute `file:///pcsx2/` paths, which requires placing the pcsx2 folder on a specific absolute location on the filesystem in order for the links to work. Global replace of `file:///pcsx2/` with `` (i.e. removing that prefix) and then placing the file at the root pcsx2 dir makes the links relative and working regardless of where pcsx2 is located.
- The list of issues is long (which is great), and while the message includes the line number, the link to open the file doesn't include it (I don't think it can TBH). It would have been nice if it could expand the offending line together with some context inside the html file itself. With syntax highlighting :p . I'll see if I can do something about it.

**Comment by RebelliousX** [comment]
Yeah, sorry about that, the absolute path was worse than that, I had to edit the HTML file and find-cut-replace to convert from absolute to relative path. But I guess I didn't cut enough :p I did cut the file://pcsx2 part again, now it works, at least in Firefox when the html file is placed next to `PCSX2_suite.sln`.

About the second issue, It can only be done using the original non converted xml-plog file using the PVS-Studio Standalone or its Visual Studio extension, which opens the file and points to culprit line of code. At least something better than nothing :)

**Comment by avih** [comment]
> ... Global replace of file:///pcsx2/ with `` (i.e. removing that prefix) and then placing the file at the root pcsx2 dir makes the links relative and working regardless of where pcsx2 is located.

So I did that, and added a small quick and dirty script at the end of the file to expand the source inline at the same page. It's really much easier to examine the messages this way.

https://0x0.st/zg-.7z - extract it and place the html file at the root of the PCSX2 repo.

The number of context lines and colors are configurable (at the source at the end of the file).

Works in Firefox, doesn't work in Chrome since it doesn't allow reading local files even if the main file is local and all the other files are at the same dir.

**Comment by RebelliousX** [comment]
Hi @avih that is superb! I didn't do any java script in the past 10 years. Can I use your script in the future? Thanks :)

**Comment by avih** [comment]
Feel free to use it. Also. @gregory38 said that the files/links at the report are all lower case, but the actual dirs in PCSX2 are mixed case, so while the report/links work on windows which is case insensitive, it doesn't work on other OSs such as Linux.

**Comment by F0bes** [comment]
We have codacy now. https://github.com/PCSX2/pcsx2/pull/4175
Everyone can view the results [here](https://app.codacy.com/gh/PCSX2/pcsx2/dashboard)
