### ISSUE TITLE
[BUG]: The Chronicles of Narnia - Prince Caspian (PAL): The second level cannot currently be completed using the EE recompiler.

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#4841]
### Describe the Bug

This is a regression that appears to have started with f9d96f5 

Basically there are a pile of rocks in the second level that need to be picked up and moved. However, the rocks keep resetting to their original positions when you put them down, meaning that they can never be cleared. There is also an example in the first level of what I think the same problem where a giant cog that you need to pick up is dropped from above, but if you don't pick it up immediately its falling animation repeats. That one's not game breaking as the cog can be picked up and used still, but the rock pile problem is.

The problem only manifests while using the EE recompiler. Using the interpreter fixes the issue but it's slow.

To test if that was the commit that broke it, I built a current dev build with that commit's changes reverted and it does seem to fix it.

### Reproduction Steps

Play until the second level. Try to move the pile of rocks blocking the cave.

### Expected Behavior

You can move the pile of rocks and their positions won't reset.

### PCSX2 Revision

v1.7.0-dev-1828

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3700X

### GPU

RTX 3070

### GS Settings

Not applicable to this problem.

### Emulation Settings

Except for using the EE interpreter, none of the hacks, rounding, or clamping settings make any difference as far as I can tell.

### Logs & Dumps

Not sure what to provide here. Let me know if anything can be useful.

**Comment by refractionpcsx2** [comment]
Can you provide a blockdump and a savestate just before the issue please, don't really have time to play through a game :P

**Comment by Silanda** [comment]
Here you go. Savestate is right at the spot. Background audio screws up immediately but the problem can be tested.

https://mega.nz/file/0CIk3L4C#WL2TMTRISa9orDRK7G9RSce1GMnIUqae7J4WdcISr4s

**Comment by refractionpcsx2** [comment]
That's fine, that's just a typical thing with savestates

**Comment by refractionpcsx2** [comment]
I have made a PR to resolve the problem, bit of a shame I had to do what I had to do, but not much I could do about it.
