### ISSUE TITLE
[BUG]: Guitar Hero III: Legends of Rock corruption in lower-half of background (PAL-M4 only)

### ISSUE THREAD

**Issue by Anuskuss** [PCSX2/pcsx2#4842]
### Describe the Bug

The lower-half of the background (band, fans, etc.) is mostly black with occasional sprite corruptions peaking through. This bug seems to be exclusive to the *PAL-M4* version (EUR:Fr,De,Es,It), but possibly happens on the other PAL version as well (EUR+AUS:En). Probably unlikely since I'm the first person to encounter this, but I have only tested the *PAL-M4* and *NTSC* version.

### Reproduction Steps

Start a game.

### Expected Behavior

The only bug that *should* happen at this time is the sprite corruption. The lower-half of the background should not be black.

### PCSX2 Revision

dev-1829

### Operating System

Windows 10 (64bit)

### CPU

i5-7260U

### GPU

Intel Iris Plus Graphics 640

### GS Window Screenshots

![ingame](https://cdn.discordapp.com/attachments/309643527816609793/892626148826177556/gsdx_20210929061716.png)
![menu](https://cdn.discordapp.com/attachments/309643527816609793/892632283796893716/gsdx_20210929064116.png)

### Logs & Dumps

[GS Dump](https://cdn.discordapp.com/attachments/309643527816609793/892629294210220092/gsdx_20210929062802.gs.xz)

**Comment by MrCK1** [comment]
User from Discord does not own a physical copy of the game. No support will be provided.
