### ISSUE TITLE
[Feature Request]: Check user configs + Easier management of configs (Modular restore defaults)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4847]
### Description

Easy way to check if something has changed from the defaults configs + maybe the ability to restore defaults per window

### Reason

- Ease in fixing user configs from importing or forgetting you left settings enabled.
- You don't want to nuke the whole config and redo First Time Wizard.

### Examples

![image](https://user-images.githubusercontent.com/24227051/135312164-c60dda77-85ee-4588-9f97-7c9937dfe028.png)

![image](https://user-images.githubusercontent.com/24227051/135313567-1df7a9ed-dae5-4dbd-9254-8c1f5448ac51.png)
( I'm not going to win an art award for this :P )

**Comment by RedDevilus** [comment]
Some other ideas that were discussed:
- User Generated Report for config changes
- Button that will zips inis and uploaded in discord (hifumi bot checks it)
- Append config changes in the emulog

- RPCS3 method which seems to rely on wiki + compares to user config with some general and specific notes
![image](https://user-images.githubusercontent.com/24227051/135317127-ed0f72dc-1901-402b-b7ee-c0e464a7febe.png)
However in the current state of PCSX2, the wiki has outdated/wrong information and the PCSX2 bot can't process it either (for now).

**Comment by refractionpcsx2** [comment]
My opinion is we do the following: 

1. make sure each page has its own restore defaults button (each General Settings page and GS, SPU, etc)
2. let the "clear settings" menu option let you choose just general settings, general + gs or everything.
3. we have a single light to say if the options are non-default (if we even do this)
4. we have a button for "compile support package" which gets all their configs and emulog, bungs them in to a zip file which the folder opens infront of the user with the file in so they can easily drag it in to support locations like discord, then we can get pandubz to modify the bot to extract it and analyse the configs.

**Comment by yxmline** [comment]
The BIOS selector always selects the first BIOS by default, not the one selected by the user

**Comment by refractionpcsx2** [comment]
> The BIOS selector always selects the first BIOS by default, not the one selected by the user

Do you mean it never remembers the BIOS you have selected? or do you mean on a fresh setup you choose a different BIOS and it ignores what you chose? if the latter, can you change it afterwards and it remembers it?

**Comment by refractionpcsx2** [comment]
I just deleted my inis and ran the wizard, it highlighted the top one in the list and I selected a different one and went through the wizard and it remembered it when I went in to check, and the right one loaded when I booted a game.

What are you experiencing that's different to that?

**Comment by yxmline** [comment]
> 
> 
> > The BIOS selector always selects the first BIOS by default, not the one selected by the user
> 
> Do you mean it never remembers the BIOS you have selected? or do you mean on a fresh setup you choose a different BIOS and it ignores what you chose? if the latter, can you change it afterwards and it remembers it?
not it cannot 
 As long as you modify other settings of the simulator, the BIOS selector will restore the first one in the default selection list, not the one I selected

**Comment by refractionpcsx2** [comment]
Hmm, I can't replicate that, it remembers my BIOS selection.

**Comment by yxmline** [comment]
> 
> 
> Hmm, I can't replicate that, it remembers my BIOS selection.

You need to click apply
Problems will arise

**Comment by refractionpcsx2** [comment]
I've tried clicking apply then closing the window, I tried clicking apply, changing a different setting after applying the bios change then pressing OK, I tried just clicking okay, they all worked.

**Comment by yxmline** [comment]
> 
> 
> I've tried clicking apply then closing the window, I tried clicking apply, changing a different setting after applying the bios change then pressing OK, I tried just clicking OK, they all worked.

There will be no problem at runtime
But pcsx2_ ui.ini
BIOS=
There are changes

**Comment by refractionpcsx2** [comment]
huh, sorry what? What exactly are you doing? 

my BIOS= has the selected BIOS after it. are you telling me you're clearing it then wondering why it's going back to the first one in the list? Because it will.

**Comment by yxmline** [comment]
> 
> 
> huh, sorry what? What exactly are you doing?
> 
> my BIOS= has the selected BIOS after it. are you telling me you're clearing it then wondering why it's going back to the first one in the list? Because it will.
> 
> Edit: Also deleted my inis so it created new ones, selected a bios, clicked apply then closed the window instead of clicking OK, closed PCSX2, opened it, my selected bios (which isn't the top one) was still chosen. So cannot replicate.

if UseDefaultBios is enabled 
This happens every time you start the simulator, the BIOS selector selects the first BIOS

**Comment by refractionpcsx2** [comment]
You're complaining the option called usedefaultbios is working? Well that's a new one. What did you expect? If you enable it, it's going to use the default.

**Comment by MrCK1** [comment]
Closing since per-game configs are implemented in Qt.
