### ISSUE TITLE
This is not a support channel.

### ISSUE THREAD

**Issue by Crsarmv7l** [PCSX2/pcsx2#4852]
This is not a support channel.

_Originally posted by @tadanokojin in https://github.com/PCSX2/pcsx2/issues/268#issuecomment-931847250_

Since the issue is closed, but not effective in the Stable build (a hint, most issues are closed when fixed in a stable build as developmental builds are unstable) maybe you should answer a simple question....Like where the dev builds are.

K thx

**Comment by RedDevilus** [comment]
Google

**Comment by tadanokojin** [comment]
Create another useless issue and you'll be banned from the repo. There all links all over the github to the support forums, discord, etc. When you created this very issue it presented you with them:

![image](https://user-images.githubusercontent.com/26046960/135557119-5dfbf26f-dfcd-471c-89d9-8c5401799a7e.png)
