### ISSUE TITLE
[BUG]: Black: Graphics errors in HW & SW

### ISSUE THREAD

**Issue by solstice0** [PCSX2/pcsx2#4857]
### Describe the Bug

The screenshots should explain it but basically, going in game the graphics are broken in both HW and SW renderers. Textured triangles shooting out of the level geometry. 

### Reproduction Steps

Go thru the menus until in-game.

### Expected Behavior

The game should render properly.

### PCSX2 Revision

1.7.0 ubuntu 20.04.1 (updated from daily build ppa last night)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 20.04

### CPU

i7-3770

### GPU

GT 1030

### GS Settings

All default.  tried playing around with hacks, nothing fixed it.

### Emulation Settings

all default.

### GS Window Screenshots

HW:
![image](https://user-images.githubusercontent.com/11930112/135685449-d70d7862-fc27-41cf-9370-00c8e12ec9a1.png)
SW:
![image](https://user-images.githubusercontent.com/11930112/135685614-0ec0177c-08ae-4823-b094-c6d89d91bbd2.png)
![image](https://user-images.githubusercontent.com/11930112/135685770-6e7aa04b-8101-410a-a39a-66f374b8a30c.png)

### Logs & Dumps

[black_broken_graphics_bug.zip](https://github.com/PCSX2/pcsx2/files/7270140/black_broken_graphics_bug.zip)

**Comment by refractionpcsx2** [comment]
I think your build is an old development build. You can fix it temporarily by enabling the VU Kickstart gamefix.

**Comment by gilderoylockhart01** [comment]
The game needs else vu clamping to none or extra+preserv sign.

**Comment by solstice0** [comment]
Thanks everyone. Strangely, messing with the game fixes menu presets fixed the issue, even after turning off all game fixes and presets and reapplying. ill mess around with this stuff before creating more issues.

Also if [this PPA](https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily) is out of date then ill start building from source.

**Comment by refractionpcsx2** [comment]
Also make sure your automatic gamefixes are enabled please.
