### ISSUE TITLE
[BUG]: Folder based Memory Cards not detected properly

### ISSUE THREAD

**Issue by maxcb97** [PCSX2/pcsx2#4862]
### Describe the Bug

Folder based memory cards are no longer detected by games anymore. Worked fine in 1852, but does not work in 1881.

### Reproduction Steps

Have a folder based memory card, with managing saves based on running game enabled, and try to load an existing save file.

### Expected Behavior

Game should remember earlier saves.

### PCSX2 Revision

dev-1881

### Operating System

Windows 10 (64bit)

### CPU

AMD 3900X

### GPU

AMD 5700 XT

### GS Settings

D3D11, Bilinear filtering, Accurate DATE, Conservative Buffer, 6x resolution, 16x Anisotropic, basic mipmap.

### Logs & Dumps

McdSlot 0 [File]: [is not memcard file]
McdSlot 1 [File]: J:\Games - Emulator\PCSX2\memcards\Mcd002.ps2
McdSlot 0: [Folder] J:\Games - Emulator\PCSX2\memcards\savesinfolders.ps2
(FolderMcd) Indexing slot 0 with filter "".
EE/iR5900-32 Recompiler Reset
	Bios Found: USA     v02.30(20/02/2008)  Console
	BIOS rom1 module not found, skipping...
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
Frame buffer size set to  512x512 (3072x3072)
Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_506.49;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = PAL
ELF (cdrom0:\SLES_506.49;1) Game CRC = 0xDF96CC28, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_506.49;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = PAL
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Searching for 'sles-50649' in GameDB
[GameDB] Found 'sles-50649' in GameDB
[GameDB] Searching for patch with CRC 'df96cc28'
[GameDB] No CRC-specific patch or default patch found
McdSlot 0: [Folder] J:\Games - Emulator\PCSX2\memcards\savesinfolders.ps2
(FolderMcd) Indexing slot 0 with filter "SLES-50649".
[GameDB] Searching for 'sles-50649' in GameDB
[GameDB] Found 'sles-50649' in GameDB
[GameDB] Searching for patch with CRC 'df96cc28'
[GameDB] No CRC-specific patch or default patch found
GS Lookup CRC:DF96CC28
(FrameLimiter) DISABLED.
[GameDB] Searching for 'sles-50649' in GameDB
[GameDB] Found 'sles-50649' in GameDB
[GameDB] Searching for patch with CRC 'df96cc28'
[GameDB] No CRC-specific patch or default patch found
(UpdateVSyncRate) Mode Changed to PAL.
Frame buffer size set to  640x512 (3840x3072)
(FrameLimiter) ENABLED.
[GameDB] Searching for 'sles-50649' in GameDB
[GameDB] Found 'sles-50649' in GameDB
[GameDB] Searching for patch with CRC 'df96cc28'
[GameDB] No CRC-specific patch or default patch found
(GameDB) Unloading...

**Comment by refractionpcsx2** [comment]
It's already been fixed in #4861

Just waiting on some issues to be resolved.
