### ISSUE TITLE
[BUG]: Debugger - Go to in Disasm menu option kills the program

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#4864]
### Describe the Bug

Any use of the Go to in Disasm option in the PCSX2 debugger instantly locks up the program. Emulation can continue if you do not supply any additional mouse or keyboard input to the UI. If input is supplied, eventually the GS Window will lock up too. Emulation appears to continue running but the emulator is by this point fully unresponsive otherwise.

### Reproduction Steps

Launch a game, open the debugger, right click an address in the memory view, hit Go to in Disasm. Poof, unresponsive.

### Expected Behavior

Disassembly panel should jump to the address right clicked in the memory view.

### PCSX2 Revision

1.7.0-1882

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800X

### GPU

RTX 3080 Ti

### GS Settings

Defaults on a freshly unpacked dev build

### Emulation Settings

Defaults on a freshly unpacked dev build

**Comment by F0bes** [comment]
Can someone assign this to me so I can feel important :blush: 
Are you doing this _while_ the VM is running. If so, does it happen wen you're running on the interpreters?

**Comment by F0bes** [comment]
Nevermind, I can reproduce it. Looking into it...
