### ISSUE TITLE
[BUG]: Tracking memcard filters (Folder Memcards)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4870]
### Describe the Bug

While folder memcards can improve user experience in that you can go beyond the 8-64MB limit of file memcards without having issues in games, however it's strength is also it's weakness it only reveals the running game as seen when you try to look at your saves in the BIOS. There is an override called the memcard filter which exposes other games. Some games have functions to unlock extra stuff (similar to the modern DLC), continue the game from that point, etc

An easy test to see if a game needs a memcard filter is to run it in a file memcard and import data from other saves then convert to folder memcard and if it fails to read it , it needs that serial.

Example:
SCES-51719:
  name: "Gran Turismo 4"
  region: "PAL-M5"
  compat: 5
  clampModes:
    vuClampMode: 2  # Text in GT mode works.
  memcardFilters:
    - "SCES-51719"
    - "SCES-52438"
    - "SCES-50294"

GT4 has 3 separate discs it can see but are there more? Possibly, you can't really automate this nor do the developers tell us about it.

- [ ] Find games with missing memcardfilters

**Comment by RedDevilus** [comment]
I've had a bit to think about this issue. Pandubz managed to make a 2GB memcard work (Sure it's still WIP atm) but if we add as many saves from as many games as possible (can just be imported from gameFAQs or other people personal saves)

Otherwise it's going to be impossible to find new filters for the folder memcards as the developers never mention it but could've implemented it.

**Comment by lightningterror** [comment]
Closing as trivial, missing discs can just be added as well as the filters in the db.

**Comment by RedDevilus** [comment]
To be fair, the easier solution would be just to open all the serials when the game is running, BIOS alone global filtering would help see all your saves and move them, but for actual usage you need it for all the games just like how file memcard operate. Missing discs adding is impossible to find 100% because developers don't state what disc works with what, you might easier find a real treasure chest in real life than find all the missing discs.
