### ISSUE TITLE
[Feature Request]: Debugger: Edit multiple lines of code

### ISSUE THREAD

**Issue by michaelx333** [PCSX2/pcsx2#4889]
### Description

Ability to edit multiple lines of code at the same time. For example, sometimes I need to NOP multiple lines of code and it has to be done manually for each one. An ability to NOP all of them would save a lot of time in my opinion.

The debugger seems to already support selecting/highliting multiple lines by holding Shift when clicking. So I guess you could use that and allow editing multiple lines with this instead of just one.

### Reason

It will save a lot of time when editing the debugger assembly code.

It helps to create patches for games (at least in my case).

Non related question: I have more feature ideas for debugger, should I make each a new "issue" or put them all in one?

### Examples

I don't have any examples

**Comment by F0bes** [comment]
In the meantime, instead of noping everything why not just branch.

**Comment by michaelx333** [comment]
Well for example in Cheat engine disassembler you can do this (NOP multiple opcodes). The way I imagine it in pcsx2 debugger is you highlight the opcodes with either shift (which is already supported) or ctrl and then choose "assemble" like usual but typing a single "nop" would overwrite all of the highlighted opcodes. It sounds pretty simple to do but Im not a programmer.

About your branch method I might try that but it sounds like way more work than needs to be in my opinion.

**Comment by refractionpcsx2** [comment]
Added in #4926
