### ISSUE TITLE
[BUG]: God of War (NTSC-U) [SCUS-97399] Fog issue.

### ISSUE THREAD

**Issue by 5d-0** [PCSX2/pcsx2#4894]
### Describe the Bug

The fog is missing.

### Reproduction Steps

Just boot up the game via any hardware mode\api, default settings.

### Expected Behavior

You can get correct behavior via software mode, fog working properly there, just like on real hardware. 

### PCSX2 Revision

dev-1915

### Operating System

Windows 10 (64bit)

### CPU

i5-4570

### GPU

GTX 1080 Ti

### GS Settings

![bandicam 2021-10-10 03-49-57-622](https://user-images.githubusercontent.com/60811674/136677387-1f3a3014-613a-4435-b617-a67e095fc3ac.png)
![bandicam 2021-10-10 03-50-12-036](https://user-images.githubusercontent.com/60811674/136677388-b99da13d-e8b7-4fe6-aa94-672754883b7d.png)

### Emulation Settings

MTVU is on but has no affect on the bug. Been checked with MTVU - off. 

### GS Window Screenshots

Hardware (OGL): 
![pcsx2-avx2 2021-10-09 09-21-28-358](https://user-images.githubusercontent.com/60811674/136677575-0ac8c0f8-f502-4943-8208-3cbb67e28543.png)
Software: 
![pcsx2-avx2 2021-10-09 09-21-40-722](https://user-images.githubusercontent.com/60811674/136677577-7ec1aaed-8a85-495a-b7c5-029180f0fbdd.png)

**Comment by refractionpcsx2** [comment]
Is this new? When did it last work if you know?

Could you please provide a GS dump? To do this press Ctrl+Shift+F8 for about a second, then it'll put a gs file in the "snaps" folder and a picture, zip them up (not 7zip cos github hates them :( ) and pop it here for us to look at.

Thanks

**Comment by 5d-0** [comment]
>Is this new? When did it last work if you know? 

This is not new and never worked the way it should iirc. 

Dump file: 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/7316695/snaps.zip)

**Comment by refractionpcsx2** [comment]
Set your Blending Accuracy to High

**Comment by 5d-0** [comment]
Blending Accuracy (Basic): 
![pcsx2-avx2 2021-10-10 05-02-54-246](https://user-images.githubusercontent.com/60811674/136678678-49409abd-96f3-4e75-8190-5da6ce86bbe8.png)
Blending Accuracy (High): 
![pcsx2-avx2 2021-10-10 05-03-09-122](https://user-images.githubusercontent.com/60811674/136678682-d19e2354-9e5e-4762-9a75-b983ab282703.png)

It seems to me that problem is resolved, thx.

**Comment by refractionpcsx2** [comment]
Thanks
