### ISSUE TITLE
[BUG]: VTLB address error after running wizard (32-bit)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#4895]
### Describe the Bug

After running the First TIme Wizard and attempting to boot a game, a memory error and/or TLB miss will occur.

Assert:
https://media.discordapp.net/attachments/754530082634072165/896618474087022662/unknown.png

### Reproduction Steps

(32-bit PCSX2)
Run Config > Clear All Settings (if applicable)
Start PCSX2, select Import in First Time Wizard, boot game

### Expected Behavior

Error should not occur

### PCSX2 Revision

1.7-dev-1915

### Operating System

Windows 10 (64bit)

### CPU

i5-6600k

### GPU

GTX 1070

### GS Settings

Defaults

### Emulation Settings

Defaults

### GS Window Screenshots

N/A

### Logs & Dumps

Log file:
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7316887/emuLog.txt)

**Comment by refractionpcsx2** [comment]
32bit is gone, so is this issue.
