### ISSUE TITLE
Gran Turismo 4[BUG]:Black screen while starting the game  

### ISSUE THREAD

**Issue by UngofaGamer** [PCSX2/pcsx2#4897]
### Describe the Bug

So when i start GT4, the intro screen is black it sounds the selected sound but i cant click the x button on my keyboard it stays on black. With GT3 the intro starts great and its playable

### Reproduction Steps

https://user-images.githubusercontent.com/88444471/136706235-13793399-27a7-467d-baf2-60c523970a8c.mp4

### Expected Behavior

Idk if its PCSX2 problem or its my pc

### PCSX2 Revision

dev-526

### Operating System

Windows 10 (64bit)

### CPU

i7-8750H

### GPU

GTX 2670

**Comment by refractionpcsx2** [comment]
Press X.

**Comment by UngofaGamer** [comment]
> can you please try the latest dev build please 🙂

pass me the link pls

**Comment by UngofaGamer** [comment]
> well I used to have that issue too and it was a bad dump, but pressing either X or Start would skip past it.

i'll try with start

**Comment by UngofaGamer** [comment]
> well I used to have that issue too and it was a bad dump, but pressing either X or Start would skip past it.

nope

**Comment by UngofaGamer** [comment]
> Then I recomment you redump your disc with imgburn, here is the ninite link (so installer without adware) if you don't have it https://ninite.com/imgburn

got it but how do i redump it?

**Comment by refractionpcsx2** [comment]
Put the disc in the dvd drive
open the program
choose "Create image from disc"
![image](https://user-images.githubusercontent.com/6278726/136706784-6dbc44db-ef50-4fe9-89fd-c84e251df5c2.png)

You can press the litle bolder with the magnifying glass on it in the middle to change the location/name,
then click the big button at the bottom and it'll make the iso
![image](https://user-images.githubusercontent.com/6278726/136706821-5cd65862-48c3-469a-a31d-e54dd9c592b1.png)

Then you're done

**Comment by UngofaGamer** [comment]
> Put the disc in the dvd drive open the program choose "Create image from disc" ![image](https://user-images.githubusercontent.com/6278726/136706784-6dbc44db-ef50-4fe9-89fd-c84e251df5c2.png)
> 
> You can press the little folder with the magnifying glass on it in the middle to change the location/name, then click the big button at the bottom and it'll make the iso ![image](https://user-images.githubusercontent.com/6278726/136706863-d5d38026-5640-44d1-9f7b-3c6df80091fb.png)
> 
> Then you're done

I don't have a disc drive, how am i gonna get a free copy of it?

**Comment by refractionpcsx2** [comment]
you can buy a USB external DVD drive from Amazon for around $20, or you can make the image on somebody elses computer and copy it back over with a USB stick.. The choice is yours.

If you want further help, please use the Discord or the forum, this is not a support forum.
