### ISSUE TITLE
PCSX2 problem that only detects USA games instead of europe

### ISSUE THREAD

**Issue by UngofaGamer** [PCSX2/pcsx2#4898]
### Describe the Bug

So i was with my old pc that had a DVD drive and my PCSX2 Bios is europe. I putted the game in the i hit Start CDVD (fast) the game was at the perfect condition when (read reprodutction steps for more)

### Reproduction Steps

The game started to freezed, i cant press any keybinds to make it work perfectly, it was like my old pc was broken. I went to check the bios and it was in europe, then i puted the Game back in and the same thing.

### Expected Behavior

I hoped it was gonna work

### PCSX2 Revision

dev-1917

### Operating System

Windows 10 (64bit)

### CPU

i5-7590

### GPU

GTX 1789

**Comment by refractionpcsx2** [comment]
Sounds like you need support, not a bug report. Please visit our forums or Discord, both are linked on https://www.pcsx2.net
