### ISSUE TITLE
Ratchet & Clank Series - Texture corruption

### ISSUE THREAD

**Issue by LasagnaPie** [PCSX2/pcsx2#49]
There is texture corruption in Both DX/GL Hardware backend 

![ratchet](https://cloud.githubusercontent.com/assets/7449866/3015881/8497a814-df67-11e3-9a20-f36621fb12fb.jpg)

**Comment by refractionpcsx2** [comment]
Now fixed in the repo.

**Comment by TheLQ** [comment]
To clarify, was this fixed in hardware or software mode? Still experiencing this issue on latest release PCSX2 in HW DX11 but works ok in SW DX11.

**Comment by FlatOutPS2** [comment]
There was no issue on the SW side (quote from first post: `There is texture corruption in Both DX/GL **Hardware backend**`)

It can be fixed for Hardware mode by going to Config > Video (GS) > Plugin Settings, and setting mipmapping to "Basic".

**Comment by TheLQ** [comment]
Ah sorry I needed to try the git build not the 1.4 release, now I can see that option. Thanks, it works great!
