### ISSUE TITLE
[BUG]: PCSX2 can't properly swap discs on the fly

### ISSUE THREAD

**Issue by HowlingWolfHWC** [PCSX2/pcsx2#4903]
### Describe the Bug

As the title says, PCSX2 can't properly swap discs on the fly.
If you do that, the contents of the new disc will not read properly.
This problem is cause because PCSX2 skips the checking stage when swapping discs, but real hardware has a checking stage.

### Reproduction Steps

Run this on the emulator:
https://github.com/HowlingWolfHWC/Swap-Disc-Test
Insert a PS2 or PS1 game and it will display the game ID (it will read it from the SYSTEM.CNF)
Swap to another game and it will read the SYSTEM.CNF again in order to read the game ID.
Instead of reading the new file, it will read the old one. That's the bug and it is caused due to the lack of the said checking stage.

### Expected Behavior

On real hardware, it reads the new SYSTEM.CNF file and gets the proper game ID.

### PCSX2 Revision

dev-1564, partially fixed in dev-1921, details: https://github.com/PCSX2/pcsx2/issues/4903#issuecomment-943107226

### Operating System

Windows 10 (64bit)

### CPU

i3-6100

### GPU

GT 720

**Comment by prafullpcsx2** [comment]
Did you try latest Dev build? We have recently fixed disc swapping. I tried using your elf and it's working as intended on current pcsx2.

**Comment by HowlingWolfHWC** [comment]
By the way, there should be something wrong with the disc reading behavior...
In dev-1921, it keeps reading the SYSTEM.CNF over and over:
![image](https://user-images.githubusercontent.com/58843152/137276433-5282efe3-8ebe-403b-a6d1-b7e019d6351c.png)
But on dev-1564 it just reads it once:
![image](https://user-images.githubusercontent.com/58843152/137276719-b573ec0e-d122-4767-b2c8-92bf17c0ed14.png)

On my code, it only reads the SYSTEM.CNF if any of these is different from the previous state:
1-Disc tray state (open / closed)
2-ESR validity
3-Type of disc

So Huston, we got a problem...

**Comment by HowlingWolfHWC** [comment]
OK. I will do that as soon as I get back home. Please, run the ELF on real hardware so you can look at the real behavior.

**Comment by refractionpcsx2** [comment]
> OK. I will do that as soon as I get back home. Please, run the ELF on real hardware so you can look at the real behavior.

The real console doesn't repeatedly print "reading sector 15" and it probably buffers it so you can't hear it doing so either.  If PCSX2 is reporting something incorrectly, that's fair enough, but yeah, I'll need that debug information in order to see why your ELF things the disc keeps changing and re-reading the SYSTEM.CNF

**Comment by HowlingWolfHWC** [comment]
[luasystem.zip](https://github.com/PCSX2/pcsx2/files/7348650/luasystem.zip)
Enjoy the spaghetti! That should help you understand everything better.

**Comment by refractionpcsx2** [comment]
I was planning on chinese for dinner,  but I guess spaghetti will do!

**Comment by refractionpcsx2** [comment]
Thanks, unfortunately doesn't really give much more information on why it's loop reading :(

> Please wait, pad(0,0) is in state EXECCMD
> Pad OK!
> Creating luaVM... 
> Loading libs... done !
> open name rom0:FONTM flag 1 data 41378
> open fd = 2
> open name rom0:ROMVER flag 1 data 41378
> open fd = 2
> 
> Graphics: created video surface of (640, 512)
> Set GS CRTC configuration. PAL  640x512 @ 50.000 (49.76) Interlaced (FIELD)
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> open name cdfs:¥SYSTEM.CNF flag 1 data 41378
> CDRead: Reading Sector 0000016 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000017 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000018 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000261 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> open fd = 2
> open name cdfs:¥SYSTEM.CNF flag 1 data 41378
> open fd = 2
> CDRead: Reading Sector 0000970 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
>

**Comment by HowlingWolfHWC** [comment]
Just add:
printf("Show this: %d\n",this);
Example at line 610.

**Comment by refractionpcsx2** [comment]
phew, at least I didn't screw up doing printf's :D

**Comment by HowlingWolfHWC** [comment]
I added some LUA funcitions to print strings and numbers too:
[luasystem.zip](https://github.com/PCSX2/pcsx2/files/7349215/luasystem.zip)

Used in the new build:
https://github.com/HowlingWolfHWC/Swap-Disc-Test/commit/b3468f8db4eb76886d6791d917e0a1a82f88b89e

**Comment by refractionpcsx2** [comment]
uhh, a few, there's a patch file (generated by winmerge, so it may suck
[luachangespatch.zip](https://github.com/PCSX2/pcsx2/files/7349223/luachangespatch.zip)
)

**Comment by refractionpcsx2** [comment]
Darn, well that didn't help much, still not printing anything :/

> Reading cdfs:¥SYSTEM.CNF
> open name cdfs:¥SYSTEM.CNF flag 1 data 41378
> CDRead: Reading Sector 0000016 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000017 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000018 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> CDRead: Reading Sector 0000261 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> open fd = 2
> File Exists
> open name cdfs:¥SYSTEM.CNF flag 1 data 41378
> open fd = 2
> CDRead: Reading Sector 0000970 (001 Blocks of Size 2048) at Speed=4x(CAV) Spindle=83
> BOOT2 = cdrom0:¥SLUS_210.44;1
> SLUS_210.44
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
> DvdRead: Reading Sector 0000014 (001 Blocks of Size 2064) at Speed=4x(CAV) SpindleCtrl=83
> Test ESR: 0
> getDiscType: 11
>

**Comment by refractionpcsx2** [comment]
oh it does? hmm, okay let me look in to that

**Comment by HowlingWolfHWC** [comment]
Good for me!

**Comment by refractionpcsx2** [comment]
Cool, there you go, added the generic detect step.
