### ISSUE TITLE
[Feature Request]: Forced Original Resolution

### ISSUE THREAD

**Issue by HowlingWolfHWC** [PCSX2/pcsx2#4904]
### Description

PS: This is NOT an issue, but a "cosmetic" feature request:
When a game is patched with Y-FIX, the new versions of the emulator shows it similar to how it appears in a PS2 (x448).
On older versions it maintained the original x512 resolution, which is the correct one to use in the game:
Left =1.1.0, Right = 1.7.0 dev-1920-fullosd:
![image](https://user-images.githubusercontent.com/58843152/137398411-295174db-bde8-40f3-8db2-41cb8fa0d707.png)
It will be nice to have an option on the graphic plugin that allows us to decide if use the original resolution (like in previous versions) or the patched resolution (like in the actual ones and on real hardware).

### Reason

Will allow to easily switch between patched and unpatched versions of the game without the need to unpatch the file.

**Comment by refractionpcsx2** [comment]
I did it with Resident Evil 4 and it's certainly doing something weird there.

![image](https://user-images.githubusercontent.com/6278726/137408476-e9bf2d32-29ee-4a11-ac1a-6b54f096e490.png)

**Comment by HowlingWolfHWC** [comment]
In PCSX2 1.1.0 it always shows x512...
Just add an option to decide if use the new mode (from newer versions) or the old one (from 1.1.0)

**Comment by HowlingWolfHWC** [comment]
Let me know if you guys need more info in order to make this...

**Comment by MrCK1** [comment]
I'd say that the overscan, aspect ratio and screen offset options in 1.7 are enough to satisfy what is requested here.

**Comment by Xorathmion** [comment]
What I don't understand about that Adrenalin_patcher_0.5 is that it changes the Y-Positioning from PAL to NTSC, despite the label saying "No Y-Pos fix".

Guess what they mean, is that the process of changing the signal and changing the format from 50Hz to 60Hz... already changes the positioning automatically as part of the process, but then it doesn't correct it... if it was probably correct.

Wish there was an actual option that DOES not actually move the Y-Position at all.
