### ISSUE TITLE
[Feature Request]: Official Sony DualShock 3 driver support

### ISSUE THREAD

**Issue by NicknineTheEagle** [PCSX2/pcsx2#4918]
### Description

There's an official DualShock 3 driver made by Sony, I believe it originally comes with PS Now client. It can be found here:
https://mega.nz/#!dSYlTapS!NQqQAEVvvgkcKMCsUhCaoLYk8xVPT8womz62tabgm6o
Source:
https://darkcloud.forumcommunity.net/?t=56241030

It would be nice if PAD code supported it.

### Reason

This will allow users to make use of pressure sensitive buttons in games that support them (e.g. Metal Gear Solid 3). Unlike DsHidMini, Sony's driver is non-intrusive and simple to install. If you have Sony's driver installed, you can currently use DS3 with PCSX2 via DirectInput handler but that won't get you pressure sensitive button support.

### Examples

RPCS3 has implemented support for Sony's DS3 driver, you can check their code for reference: https://github.com/RPCS3/rpcs3

**Comment by gilderoylockhart01** [comment]
Yes that's a nice idea of enhancement, if I am not wrong DS3 and DS4 does work with the same driver on other projects is that right?

**Comment by NicknineTheEagle** [comment]
> 
> 
> Yes that's a nice idea of enhancement, if I am not wrong DS3 and DS4 does work with the same driver on other projects is that right?

Please, read my post again, I've mentioned that RPCS3 has implemented support for this driver.

**Comment by mirh** [comment]
Wasn't this fixed with #7099?

**Comment by NicknineTheEagle** [comment]
Yeah, was apparently only added for legacy wx interface and not for Qt interface.

**Comment by RedDevilus** [comment]
Last, they said that they didnt know how to do it for Qt.

**Comment by NicknineTheEagle** [comment]
https://github.com/PCSX2/pcsx2/issues/7189 mentions there are no plans to add support in Qt.

**Comment by RedDevilus** [comment]
It's still a valid issue imo. If there is a clean method by someone in future.

**Comment by eVenent** [comment]
Ehh, not good. One controller and we have to jump with drivers between support for PCSX2 and RPCS3. I hope someday SXS mode in dshidmini will work properly with PCSX2, to stop this driver jumping.

Official Sony driver works already great with RPCS3, reWASD (and their virtual controller), Steam and DS4Windows apps.

DsHidMini in SXS mode works with RPCS3, Steam, gInput and DS4Windows apps.

We are close to have one standard for everything.

**Comment by stenzek** [comment]
PCSX2 works in SXS mode with the XInput wrapper. If you want something else, feel free to implement it, but we have no plans to support anything else.

**Comment by TheLastRar** [comment]
> I personally have **zero** interest in supporting rewasd and their commercial rubbish.

Isn't this issue about the official driver, and not reWASD?

**Comment by LeoGidev** [comment]
link Down :(
