### ISSUE TITLE
Lilypad does not allow simultaneous same axis dpad button press

### ISSUE THREAD

**Issue by ekans-** [PCSX2/pcsx2#492]
pcsx2 1.3.1 20150329154106 git
Windows 7 x64

Games tested:
DDRMAX 2 
DDR Supernova

Lilypad does not allow the simultaneous presses of Up/Down or Left/Right dpad buttons in game.
This is an issue in DDR games which need simultaneous opposite direction button presses.
The issue is the same whether i map keyboard keys to the dpad, or use a usb dance mat controller.

**Comment by ssakash** [comment]
The simultaneous presses works for me on using techniques on Naruto ultimate ninja 5. Maybe this problem is exclusive for the game you're mentioning.

**Comment by ekans-** [comment]
Can you confirm you are simultaneously pressing the buttons on the same axis? ie left + right at the same time? 

I have found a number of threads describing similar issues:
http://forums.pcsx2.net/Thread-PLUGIN-need-pad-plugin-to-allow-d-pad-left-and-right-simultaneously
http://forums.pcsx2.net/Thread-Is-it-possible-to-register-up-and-down-simultaneously
http://forums.pcsx2.net/Thread-Input-problem-with-Lilypad-and-DDR
http://forums.pcsx2.net/Thread-LilyPad-0-10-0?page=83
http://forums.pcsx2.net/Thread-Allowing-for-left-and-right-d-pad-simultaneously

Workarounds were described, but this issue still seems valid as it is a limitation of Lilypad, and not of the console itself

**Comment by ssakash** [comment]
actually , the combination which works for me is Down + Down, UP+UP , Down+ Right etc... I have never tried left + right.

**Comment by srwaggon** [comment]
Is this actually fixed? I'm using PCSX2 version 1.4.0 and I'm still seeing this issue with DDR Max 2.

**Comment by tadanokojin** [comment]
Try the dev builds
https://buildbot.orphis.net/pcsx2/index.php

**Comment by srwaggon** [comment]
@tadanokojin ♥
Thank you. It is fixed in the newer updates!

-- Do you all do test driven development by chance?

**Comment by willkuer** [comment]
No. Unfortunately no unit tests in this project. There are some integration tests but they are not automatically validated. All testing is done by manual QA.

Why do you ask?

**Comment by srwaggon** [comment]
I prodded because I happen to be skilled in TDD/BDD and am an enthusiast and advocate for the quality and confidence they generate. I'm always looking where I can assist groups improve their quality and reduce regressions (if you weren't already doing TDD).

Unfortunately, I'm not skilled in your stack, so my testing contributions would be deeply limited. 😅
And it sounds like you all are already on top of it. :)
