### ISSUE TITLE
[BUG]: Disappearing text in Mana Khemia: Alchemists of Al-Revis

### ISSUE THREAD

**Issue by Sarania** [PCSX2/pcsx2#4928]
### Describe the Bug

In GSDX hardware mode(with literally any settings... I tried them all lol and both OGL and D3D11) the text in the game is prone to disappearing. It seems random when it happens. In software mode things work fine - although if you trigger the bug in HW mode and switch to software it's not immediately fixed, it's only fixed once something (appears to) reload the font. 

Update: Prafull figured out the bug was absent in 1913, present in 1914 so this should be the commit that regressed on this issue: https://github.com/PCSX2/pcsx2/commit/ef2c7ac4806f804bc03d859d546408e16f6a5082

### Reproduction Steps

It's a bit random in it's nature but for instance if you repeatedly open the menu and go to items, then exit completely back out of the menu, and repeat, it will eventually trigger.

### PCSX2 Revision

1.7.0 dev 1921 (Update: working in dev 1913, broken in dev 1914)

### Operating System

Windows 10 (64bit)

### CPU

i7-8750h

### GPU

GTX 1070

### GS Window Screenshots

![Mana Khemia Missing Text](https://user-images.githubusercontent.com/7574269/138506337-5fc5cec5-7079-437f-b7a5-4953988e30f4.png)

### Logs & Dumps

GSddump and block dump as requested. In the block dump you should mash start or X when the FMV starts(you'll see a magic circle thing) because i skipped it when making the dump! Also in the block dump you can reproduce the issue by selecting load game and then exiting to main menu - eventually the font will disappear!
[Dumps - Mana Khemia Missing Text.zip](https://github.com/PCSX2/pcsx2/files/7400683/Dumps.-.Mana.Khemia.Missing.Text.zip)

**Comment by darkxex** [comment]
Still waiting for fix this

**Comment by refractionpcsx2** [comment]
Use an older version, if you're waiting. It'll get fixed when it gets fixed.

**Comment by darkxex** [comment]
Sorry, my comment was quite unpleasant.

**Comment by refractionpcsx2** [comment]
I'm just waiting on some other stuff to get out of the way, then I might look at it later, I need some more information/game dumps before I can work on it.
