### ISSUE TITLE
[BUG]: Maken Shao - Demon Sword: Environmental Glitches On Hardware And Software Rendering

### ISSUE THREAD

**Issue by ThatDudeYouMetThatOneTime** [PCSX2/pcsx2#4937]
### Describe the Bug

NOTE: I tested this on both a *32-bit and 64-bit* 1.7.0 dev-build of PCSX2

On hardware rendering, OpenGL since I'm on Linux, during gameplay, the environments become a mostly white void while the character and enemy models render properly. However, the models have a large shadow present on the lower halves of their bodies. Thankfully, the HUD is still fully visible and colored as it should be.

On software rendering, during gameplay, the environments are rendered as they should be. However, while moving, the environmental geometry flickers rapidly and you can see through various walls, objects, etc. The HUD is perfectly fine here as well, fortunately. 

### Reproduction Steps

1.) Open PCSX2 (1.7.0, 32-bit or 64-bit, it happens in both).
2.) Load up your ISO of Maken Shao - Demon Sword.
3.) Start a new game, skipping past the intro cutscenes, and select the 1st mission.
4.) Observe the lack of any visible level geometry in hardware rendering and the rapid flickering of the environment in software rendering.

### Expected Behavior

- Hardware rendering: The environments should be fully visible, and there should not be any large shadows in front of the character and enemy models.
- Software rendering: The environments should not be rapidly flickering while you move around. 

### PCSX2 Revision

1.7.0 

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 20.04.3 LTS

### CPU

i5-7400T @2.40GHz

### GPU

Mesa Intel HD Graphics 630 (KBL GT2)

### GS Settings

![Screenshot from 2021-10-24 15-40-33](https://user-images.githubusercontent.com/81947301/138610122-fd767dac-204e-47c0-a56a-9f33ac6863b3.png)
![Screenshot from 2021-10-24 15-40-37](https://user-images.githubusercontent.com/81947301/138610128-245c349c-7f22-4383-9ffa-e30797800e10.png)

### Emulation Settings

![Screenshot from 2021-10-24 15-42-36](https://user-images.githubusercontent.com/81947301/138610178-2d8ca048-1dba-4bce-872b-7e15d9dc05c1.png)
![Screenshot from 2021-10-24 15-42-53](https://user-images.githubusercontent.com/81947301/138610180-dfba5abc-5c01-4212-8148-8e66f909e28b.png)
![Screenshot from 2021-10-24 15-43-00](https://user-images.githubusercontent.com/81947301/138610181-c1bcffeb-02a8-4f2d-bdc4-af70a2a7636b.png)
![Screenshot from 2021-10-24 15-43-04](https://user-images.githubusercontent.com/81947301/138610183-ee8c427b-c143-466c-a3ce-16b6b1610891.png)

### GS Window Screenshots

![gs_20211024210356_(5)](https://user-images.githubusercontent.com/81947301/138620589-3b75d973-e475-4ffd-9609-20ad55ad0cb0.png)
![gs_20211024210431](https://user-images.githubusercontent.com/81947301/138620605-b369d8d0-6355-4115-a9d8-8ca2007e9aa4.png)

**Comment by Yui12** [comment]
Yes also  Disabling mVU Flag Hack also stops the flickering, so yeah something is busted. Looks like this currently in Hardware mode with blending set to Minimum. Also, this only works in OpenGL backend as it doesn't work with D3D11.

![test](https://user-images.githubusercontent.com/13986398/147863702-2be101e9-9b1f-4113-9fad-a0e4e4a80113.png)

**Comment by refractionpcsx2** [comment]
I believe this is resolved on master?

**Comment by Yui12** [comment]
I recently tested out this game again since PCSX2 lately has really been killing it with the improvements and all I have to say is that I never thought I would see the day that this issue would ever get fixed as it was around for years. I thank the people involved for fixing this.
