### ISSUE TITLE
[BUG]: No Controller rumble on linux

### ISSUE THREAD

**Issue by CrezyDud** [PCSX2/pcsx2#4942]
### Describe the Bug

No rumble on my ps4 controller connected via USB on Arch Linux.
It only works when i run PCSX2 via WINE, native version doesn't work with rumble.
Dolphin and https://gamepad-tester.com/
don't detect it ether, but WINE does.
So there must be a solution.

### Reproduction Steps

plsme

### PCSX2 Revision

v1.7.0.-dev-1965-gd70631477

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

Intel i5-8300H (8) @ 2.300GHz

### GPU

NVIDIA GeForce GTX 1050 Mobile

**Comment by Mrlinkwii** [comment]
Is this still an issue on master?

**Comment by lightningterror** [comment]
Should be fine on qt, if not then this can be re opened.
