### ISSUE TITLE
Star Ocean battle transition effect broken with all renderers 

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#4948]
### Describe the Bug

The battle transition effect when encountering an enemy on the filed is not rendered correctly in the latest builds, even in software mode. Not sure when this bug started.

### Reproduction Steps

Boot the game and run into an enemy on the field. 

### Expected Behavior

The effect to be rendered correctly especially in software mode. 

### PCSX2 Revision

v1.7.0-dev-1977-g23283b7f0a

### Operating System

Windows 10 (64bit)

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

I've tried software mode as well as default hardware mode settings. 

### Emulation Settings

I've tried various speedhack combinations and the defaults as well as all of them off. 

### GS Window Screenshots

The first image is how it currently renders and the second is how it used to render except my standard screenshot did not capture the ripple effect for some reason

![Screenshot (13)](https://user-images.githubusercontent.com/12180630/139188303-98850160-4cae-4b65-bf4c-f7023877754c.png)
![Screenshot (17)](https://user-images.githubusercontent.com/12180630/139188306-0349d951-35b9-4095-9053-6b5835869dcc.png)
. 

### Logs & Dumps

https://drive.google.com/file/d/1Qfb2bCurPM2ytnl7n-Na9kgALWTzPlWc/view?usp=sharing

**Comment by BParks21** [comment]
> Can you also upload a blockdump of the issue?

How do I do that exactly?

**Comment by RedDevilus** [comment]
![Screenshot_20211029-233314082 (1)](https://user-images.githubusercontent.com/24227051/139504228-8fa05d31-b03c-4dc3-9016-d03dee2ee637.jpg)
 Then just upload it here along with a corresponding savestate.

**Comment by BParks21** [comment]
> ![Screenshot_20211029-233314082 (1)](https://user-images.githubusercontent.com/24227051/139504228-8fa05d31-b03c-4dc3-9016-d03dee2ee637.jpg) Then just upload it here along with a corresponding savestate.

Here ya go.

https://drive.google.com/file/d/1_KLEtOHdZ6QIHJgJBX89EUDm5I3xTZCz/view?usp=sharing

**Comment by refractionpcsx2** [comment]
This should be fixed once #4965 gets merged, you are free to test it, if you wish :)

**Comment by BParks21** [comment]
Thanks.
