### ISSUE TITLE
[Feature Request]: Overhaul structure of patches

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#4949]
### Description

Current situation:

It looks if the user enabled the GUI buttons:
![image](https://user-images.githubusercontent.com/24227051/139271906-6fac0466-b66a-447a-ace7-6fa1a96b9351.png)
It will look at the cheats folder if 'Enable cheats' is enabled.
For 'Enable Widescreen' Patches cheats_ws.zip is looked at first (no need to unzip as PCSX2 handles it for the end-user) and then it will look at the cheat_ws folder.

Keep in mind that for PCXS2 they are all 'the same' thing called patches.

### Reason

First of all:

cheats and cheats_ws is not the correct naming and undermines the potential power of the patches system.

You could even do CRC_nointerlacing.pnach or CRC-60fps.pnach as it only looks at the CRC and you could even batch them together but there should be an easier way to handle without doing it that way (but keep that behaviour if you prefer that).

Instead of naming cheats replace all with the name patches and subfolders to make it more modular and structured.

### Examples

![image](https://user-images.githubusercontent.com/24227051/139271783-446e83e2-3658-486b-84c7-4f87893df244.png)

![image](https://user-images.githubusercontent.com/24227051/139272586-13d7b281-1d6f-4988-9858-ee79ef6877b8.png)

Technically we could make a subfolder with pre-included for the included widescreen patches and add a text file saying not to unzip

**Comment by lightningterror** [comment]
Closing as trivial.
