### ISSUE TITLE
[BUG - Regression]: Hasbro Familly Game Night: "Draw Skipped due to invalid guest framebuffer format" problem.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4951]
### Describe the Bug

The game "Hasbro Familly Game Night" started to show various errors in the emulog (Draw Skipped due to invalid guest framebuffer format) and stopped displaying properly as a result.

### Reproduction Steps

Load the game.

### Expected Behavior

The game should display fine at booth the right and left sides of the screen.

### PCSX2 Revision

pcsx2-v1.7.0-dev-1966-gbfbe86a3d5-windows-x86

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Settings

Software render.

### Emulation Settings

VUkickstart (not in the DB but needed for booth this game and Trivial Pursuit).

### GS Window Screenshots

The bug in action:

Emulog:

![Capture d’écran 2021-10-28 205037](https://user-images.githubusercontent.com/90222976/139318041-82d5983f-9182-41bf-94b9-e3e7b977dff4.png)

Software render:

![Capture d’écran 2021-10-28 205023](https://user-images.githubusercontent.com/90222976/139318070-48c990f5-d625-4fdb-ace0-4d0f61589783.png)

### Logs & Dumps

GSdump:
[Hasbro GS problem.zip](https://github.com/PCSX2/pcsx2/files/7436708/Hasbro.GS.problem.zip)

**Comment by prafullpcsx2** [comment]
It is another one of the games broken by commits between 1962-1965. I was wondering what benefits/fixes does this change provide and if possible whether this can be reverted especially since it breaks compatibility with gsdumps.

**Comment by refractionpcsx2** [comment]
Does this still happen by the way? might be fixed by 2003 (on github releases) or 2000 on buildbot builds

**Comment by lightningterror** [comment]
Seems that it looks good on the dump? HW renderer is busted tho.
![image](https://user-images.githubusercontent.com/18107717/144732400-7675a944-159c-470d-ba3f-bfab85af633f.png)

**Comment by refractionpcsx2** [comment]
yeah it should be fine now. HW has the massive framebuffer and supersampling thing going on so the TC doesn't like it, but software should be good.

**Comment by gilderoylockhart01** [comment]
The game is fine now. Yup, hardware will likely need a TC update but software is fine for now.
