### ISSUE TITLE
[BUG SPU2 - Regression]: Samurai Shodown 6, music only playing on the right speaker.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4955]
### Describe the Bug

The game "Samurai Shodown 6" have an issue where most of the BGMs only plays on the right speaker. This is a regression but I haven't had the time to dig the regression build yet, I will try to find the time to do that as soon as I can.

### Reproduction Steps

Load the blockdump, play the intro.

### Expected Behavior

The BGM should play on booth left and right speakers.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

(the FMV is slow, that's because of my capture software, not an actual problem):

https://user-images.githubusercontent.com/90222976/139423661-05559821-9ff8-401a-913b-f7c76e11befb.mp4

### Logs & Dumps

Blockdump: https://drive.google.com/file/d/16fHLuEK3ZQJGJzCsciVxuXlkwBsJijm8/view?usp=sharing

**Comment by gilderoylockhart01** [comment]
The regression commit is this one https://github.com/PCSX2/pcsx2/commit/465aa00fc7b095f03619595a5dbbd1cba916af49

**Comment by refractionpcsx2** [comment]
A lot has happened since then, delay cycles has been reintroduced (to an extent), but sure, I'll take a look.

**Comment by refractionpcsx2** [comment]
Hmm, I'm not sure how you came to this conclusion about that commit breaking it, it has nothing to do with that. I even tested all the way back to 1.6 and it was still an issue, the only thing that commit does differently is it makes a "click" noise before crapping out.

The issue is the data it's trying to read from is blank, if I force the start address for the voice to equal the right channel, you get sound from both sides.

**Comment by refractionpcsx2** [comment]
okay the problem is for me the information is missing from the dump, I'm guessing you made it with a broken version.

**Comment by gilderoylockhart01** [comment]
Yes, sorry for that error, I will take a blockdump with a working commit.

**Comment by gilderoylockhart01** [comment]
There it is: https://drive.google.com/file/d/1tPiHlQQfubU8CRe1GRBT8paVrtBWFhIT/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Thanks

**Comment by refractionpcsx2** [comment]
Wasn't that at all, it was CDVD timing stuff
