### ISSUE TITLE
[BUG - GS Hardware]: PSX Mode, Star Wars Dark Force rendering problem.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4956]
### Describe the Bug

I know PSX games are not valid as a bug report, but Kojin was tracking this type of problem so I still think it's worth the report.

In the game Star Wars Dark Force, the GS hardware render does produce some weird glitches which becomes even worse when upscaling (pay attention to the radar at the lower left side of the screen plus the walls of the map). Switching to the software render will solve the problem.

### Reproduction Steps

Load the GSdump.

### Expected Behavior

The game should look exactly like the software render.

### PCSX2 Revision

v1.7.0-dev-1980-g52eab49359

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Settings

Native resolution / upscaling at 8x.

### GS Window Screenshots

The bug in action:

Hardware native resolution:

![3](https://user-images.githubusercontent.com/90222976/139427728-e5bb4e78-9b1f-4c1d-a9dd-a98f8962836e.png)

Software render:

![1](https://user-images.githubusercontent.com/90222976/139427749-2175d757-1692-45f7-b7c5-4b71ce77996d.png)

Hardware at 8x:

![2](https://user-images.githubusercontent.com/90222976/139427813-b84ff3e3-05be-411f-80cb-b40f5b3473f1.png)

### Logs & Dumps

GSdump:
[PS1 - Star Wars Dark Force.zip](https://github.com/PCSX2/pcsx2/files/7441538/PS1.-.Star.Wars.Dark.Force.zip)

**Comment by lightningterror** [comment]
Closing as it's a ps1 issue.
