### ISSUE TITLE
[BUG]: Super Monkey Ball Deluxe, speed problem in Monkey bowling DX minigame.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4958]
### Describe the Bug

In the game "Super Monkey Ball Deluxe" there is a problem where selecting the bowling ball angle in the "Monkey bowling DX" minigame will cause the cursor to be way too fast except if you select the baby character ( yeah, makes no sense but it is what it is ;) ).

Note: Every emulators are having that same problem.

### Reproduction Steps

Load the blockdump and savestate.

### Expected Behavior

The angle selection should not be too fast and on par with the baby character.

### PCSX2 Revision

v1.7.0-dev-1980-g52eab49359

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

VU rounding to nearest by GameDB.

### GS Window Screenshots

The bug in action:

Non-baby characters:

https://user-images.githubusercontent.com/90222976/139442255-cff944b0-3ab6-41eb-8ffe-14d288a859ec.mp4

Baby character:

https://user-images.githubusercontent.com/90222976/139442318-e1f27fbd-29c5-494b-9232-3be254fabe50.mp4

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/14rhUnqBPuu_QwAkAZ0svKKvzLS_KX4eu/view?usp=sharing

**Comment by Mrlinkwii** [comment]
can this be check on latest mater ?

**Comment by bslenul** [comment]
Maybe not even a bug?

> Baby: Baby has slower speed and lower spin but has an easier time aiming.

https://supermonkeyball.fandom.com/wiki/Monkey_Bowling_DX#Statistics

**Comment by refractionpcsx2** [comment]
Thanks for the info @bslenul :)
