### ISSUE TITLE
[BUG - GameDB]: Incorrect/missing entries.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4959]
### Describe the Bug

There are various entries to else, modify or add.

- Super Monkey Ball Deluxe requires the EE rounding to negative in order to not break booth the target minigame while still fixing the billiards minigame.

The gameDB apply nearest which is wrong, the correct setting is EE rounding to negative.

- Spiderman 3 needs the EE rounding set to nearest to fix idle camera behaviour.

- Mercenaries 2 currently have the EE Timing hack set to avoid distant flickering, the correct fix is no MTVU + instantVU1 disabled, it's a VU1 timing bug and using the timing hack will completely break the game later on.

- Virtual On games, only the "SLPM-62767" entry need the EE clamping fix, every other ones must be removed as this could cause problems.

- GTA San Andreas needs the VU clamping to be set to Extra + Preserve Sign to fix the "Reuniting The Families" ingame cutscene freeze.

### Reproduction Steps

Load any of the mentioned games and see by yourself how it's like, I already tested all of these so it should be fine.

### PCSX2 Revision

v1.7.0-dev-1980-g52eab49359

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

**Comment by refractionpcsx2** [comment]
> Mercenaries 2 currently have the EE Timing hack set to avoid distant flickering, the correct fix is no MTVU + instantVU1 disabled, it's a VU1 timing bug and using the timing hack will completely break the game later on.


I'm not replacing gamefixes with MTVU, MTVU is not a timing fix and how it acts will be different on different computers, where gamefixes are not.

**Comment by gilderoylockhart01** [comment]
Ok for Mercenaries then, but the other games are valid anyway, + for monkeyball that's a high priority because the actual setting does break the game pretty hard in some cases.
