### ISSUE TITLE
[BUG - Debugger]: Running after an execute breakpoint is triggered prevents it from getting re-triggered when loading a save state.

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#4961]
### Describe the Bug

In PCSX2's debugger, if an execute breakpoint is triggered once, followed by the user resuming to run and subsequently loading a save state from an earlier point in time, the aforementioned breakpoint won't be re-triggered.

This is very similar to #2306 (resolved by @turtleli). It's the exact same issue, except it occurs when loading save states as opposed to fast booting.

### Reproduction Steps

1. Launch PCSX2 and fast boot any game.
2. In the log window, find the game's entrypoint and take note of it.
3. Open the debugger.
4. In the bottom of the debugger window, switch to the "Breakpoints" tab, right click, select "Add new" and create an execute breakpoint based on the entrypoint's address.
5. Fast boot the game and wait for the breakpoint to be triggered.
6. Create a save state.
7. In the debugger window, press the "Run" button. The game will resume running.
8. Load the save state.

### Expected Behavior

The breakpoint should be re-triggered.

### Actual Behavior
The game will start without interruption.

**Note:**
The bug can be worked around (i.e. inducing expected behaviour) by doing either of the following:
* Pressing any of the debugger's step buttons before pressing "Run" in step 7.
* Pressing the debugger's "Break" button between steps 7-8.

### PCSX2 Revision

dev-1992

### Operating System

Windows 10 (64bit)

### CPU

i7-8705G

### GPU

Radeon RX Vega M GL

**Comment by F0bes** [comment]
Please test #4997

**Comment by Aced14** [comment]
@F0bes Thanks :)!

Just tried out one of the Windows AVX2 build artifacts and got the expected behaviour in all of my attempts. Tried out two games I had been using as guinea pigs for this bug and both triggered breakpoints every time I expected them to when loading/reloading save states.

Btw could a repo maintainer add a "Debugger" label to this issue and #4997?
