### ISSUE TITLE
[BUG]: God Of war 1 Music Problem

### ISSUE THREAD

**Issue by emanuelect** [PCSX2/pcsx2#4962]
### Describe the Bug

 continuous interruption and re-starting of music inside the Pandora Temple.

### Reproduction Steps

Enter the temple

### PCSX2 Revision

dev-1995-g20ab4dbf20

### Operating System

Windows 10 (64bit)

### CPU

intel(R) Core(TM) I7 3770 CPU @ 3.40 Ghz

### GPU

nvidia Geforce gtx 1050 Ti

### Emulation Settings

![image](https://user-images.githubusercontent.com/43710721/139556192-9aa383e4-ba0c-4691-88e2-b6bdb85318b2.png)

**Comment by refractionpcsx2** [comment]
Regressed in 1906 because of insane rotational delay times (waiting like 700ms to rotate, very off! xD)
