### ISSUE TITLE
[Feature Request]: Change "Clear ISO list" with "Delete ISO list" and add a "Clean ISO list" option at the ISO Selector

### ISSUE THREAD

**Issue by IlDucci** [PCSX2/pcsx2#4963]
### Description

Add an aditional option at CDVD -> ISO Selection -> ISO list, do the following additions:
 - Replace "Clear ISO list" with "Delete ISO list" or some other naming that makes it clear that the list itself will be emptied in its entirety.
 - Add a new option called "Clean ISO list", to be used to remove only any ISO files that are no longer available at their original location.

### Reason

This feature somewhat came to me because I mistranslated "Clear ISO list" as "Clean ISO list", and when I actually went to use it, I thought I would clean up all the ISOs I had moved from one place to another. Right now, having only the option to hit the nuclear button and redo the ISO gathering can be a bit tedious for people with multiple folders. A happy accident, I suppose.

### Examples

Cannot think on any examples here.

**Comment by lightningterror** [comment]
Addressed in the linked pr.
