### ISSUE TITLE
[BUG]: Build error when CFLAGS "-DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by io3432iooivzs** [PCSX2/pcsx2#4967]
### Describe the Bug

I build pcsx2 on Debian/Bullseye, I've got these Meesage.
Source is cloning git at 10/31/2021

=== Message from here ===

/x86/iR3000A.cpp:743:6: internal compiler error: in gimple_build_call, at gimple.c:264
  743 | void recResetIOP()
      |      ^~~~~~~~~~~
0x7f50113b6d09 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
[ 51%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/x86/iR5900Misc.cpp.o
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:1735: pcsx2/CMakeFiles/PCSX2.dir/x86/iR3000A.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1486: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

=== Message End ===

I've got this message, add "-DCMAKE_BUILD_TYPE=Release" CFLAGS.
When no CFLAGS set, No error message and build successed.

### Reproduction Steps

git clone https://github.com/PCSX2/pcsx2.git
cd pcsx2
mkdir build
cd build
git submodule init
git submodule update
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j3

### Expected Behavior

Make release build.

### PCSX2 Revision

git cloning 10/31/2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Debian 11.1

### CPU

A8-7600

### GPU

Radeon R7 Graphics (iGPU)

### Logs & Dumps

/x86/iR3000A.cpp:743:6: internal compiler error: in gimple_build_call, at gimple.c:264
  743 | void recResetIOP()
      |      ^~~~~~~~~~~
0x7f50113b6d09 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
[ 51%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/x86/iR5900Misc.cpp.o
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:1735: pcsx2/CMakeFiles/PCSX2.dir/x86/iR3000A.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1486: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by kenshen112** [comment]
Does clang error out any differently? Try making sure it's installed and setting the cMake option from there

**Comment by F0bes** [comment]
Please use a different GCC version or use Clang.

This is a compiler bug, not related to PCSX2, as indicated by the emitted message GCC gave you.

```
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See file:///usr/share/doc/gcc-10/README.Bugs for instructions.
```
