### ISSUE TITLE
RFE: A hack to disable motion blur in Nocturne

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#497]
I may be being arrogant just leaving this request here cluttering the bug reports when it's not a bug, and it's even game engine specific, but i really think it would increase playability in that title.
And maybe Digital Devil Saga 1 & 2.

Feel free to close if it's never going to happen.

**Comment by gregory38** [comment]
Can we close it?

**Comment by i30817** [comment]
I'm just waiting for the autobuild to see how it went, but in principle, yes :)
