### ISSUE TITLE
[Feature Request]: Which one to download?

### ISSUE THREAD

**Issue by Geniusssmit** [PCSX2/pcsx2#4977]
### Description

There are a few versions, which one I should download?
Windows 10 64 bit, Ryzen 2600, Geforce RTX 2080.
![image](https://user-images.githubusercontent.com/24941285/140300326-5b15a4f3-2eb0-4991-b2c8-d08cbb1eadc1.png)

### Reason

not clear

### Examples

?

**Comment by refractionpcsx2** [comment]
Get the 32bit AVX2 one for now, don't touch 64bit yet.

Anyway this isn't a support forum, for support please visit the forums or the discord, both are linked on https://www.pcsx2.net
