### ISSUE TITLE
Optimization flags overriding

### ISSUE THREAD

**Issue by nE0sIghT** [PCSX2/pcsx2#498]
It was originally reported in Gentoo vortex overlay: https://github.com/nE0sIghT/vortex-overlay/issues/4

Is there any reason for -O flag to be overriden while building pcsx2 plugins?
If there are no reasons, i will prepare a PR to strip them.

pcsx2-1.3.1# grep --include=CMakeLists.txt -r "\-O2" .
./tools/bin2cpp/CMakeLists.txt:		-O2 -s -Wall -fexceptions
./tools/bin2cpp/CMakeLists.txt:		-O2 -s -Wall -fexceptions
./tools/bin2cpp/CMakeLists.txt:		-O2 -s -Wall -fexceptions
./plugins/zzogl-pg/opengl/ZeroGSShaders/CMakeLists.txt:    -O2
./plugins/zzogl-pg/opengl/CMakeLists.txt:    -O2
./plugins/zerospu2/CMakeLists.txt:    -O2
./plugins/zerogs/opengl/CMakeLists.txt:    -O2
./plugins/zerogs/dx/CMakeLists.txt:	set(CMAKE_C_FLAGS_DEVEL "-Wall -fPIC -m32 -O2")
./plugins/zerogs/dx/CMakeLists.txt:	set(CMAKE_CXX_FLAGS_DEVEL "-Wall -fPIC -m32 -O2")
./plugins/zerogs/dx/CMakeLists.txt:	set(CMAKE_C_FLAGS_RELEASE "-Wall -fPIC -m32 -O2 -s")
./plugins/zerogs/dx/CMakeLists.txt:	set(CMAKE_CXX_FLAGS_RELEASE "-Wall -fPIC -m32 -O2 -s")
./plugins/spu2-x/src/CMakeLists.txt:    -O2
./plugins/onepad/CMakeLists.txt:    -O2
./plugins/dev9null/CMakeLists.txt:    -O2
./plugins/USBnull/CMakeLists.txt:    -O2
./plugins/SPU2null/CMakeLists.txt:    -O2
./plugins/PadNull/CMakeLists.txt:    -O2
./plugins/GSnull/CMakeLists.txt:    -O2
./plugins/GSdx/CMakeLists.txt:    -O2
./plugins/FWnull/CMakeLists.txt:    -O2
./plugins/CDVDnull/CMakeLists.txt:    -O2
./plugins/CDVDlinuz/Src/CMakeLists.txt:    -O2
./plugins/CDVDiso/src/CMakeLists.txt:    -O2

**Comment by gregory38** [comment]
To avoid silly cmake default option, values were cleared. Currently the core doesn't use O2. It crashed on the past but I think it must be good with latest gcc. (see #457 ). Anyway it means O2 need to be set manually on every plugins (GSdx use O3).
```
set(CMAKE_C_FLAGS_DEBUG "")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_C_FLAGS_DEVEL "")
set(CMAKE_CXX_FLAGS_DEVEL "")
set(CMAKE_C_FLAGS_RELEASE "")
set(CMAKE_CXX_FLAGS_RELEASE "")
```

**Comment by nE0sIghT** [comment]
Thanks for explanation
