### ISSUE TITLE
RFE: make a autobuilt recipe for the pcsx2.snapshot package

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#499]
It hasn't been built since 11 weeks ago, kinda late for a 'unstable' ppa package.
Launchpad packages can be made to be autobuilt, usually by making a mirror of the code repository (which autoupadates, github is supported), then another personal launchpad repository with the debian dir and then merging those two in a recipe to build a package (in this case pcsx2.snapshot) with a unique autoupdated name that resolves to a 'newer' one (date - if daily only - or github revision number works) and dumping that on a ppa. The only restriction is that all libraries either must be on the main archives or must be built with the source (by for example, pulling other repositories) - no binary dependencies that can't be resolved into a chain of trust.

There is no reason at all for waiting until someone decides to update the unstable package to get the new version... unless you're doing it on purpose for some reason.

**Comment by gregory38** [comment]
```
There is no reason at all for waiting until someone decides to update the unstable package to get the new version... unless you're doing it on purpose for some reason.
```
I will be honest I miss time to update it. 

However, in order to ensure some stabilities, I'm not sure it is a good idea to update it right away.  Progress remains slow on linux so 11 weeks isn't that much.

Why not, but there is no resources available here.

**Comment by i30817** [comment]
can you share the debian dir/repository you're using? I can try to make a autobuild for myself on a personal repository, and then if you'd like you can lift and tweak the recipe yourself (if you end up wanting to autobuild).

**Comment by gregory38** [comment]
everything can be found on git (or likely launchpad ppa).

https://github.com/PCSX2/pcsx2/tree/master/debian-packager

**Comment by gregory38** [comment]
There is another report for the same issue. So I close this one.
