### ISSUE TITLE
[BUG - Regression]: Ratchet and Clank Up Your Arsenal: SPS in combat arena.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4998]
### Describe the Bug

In the game "Ratchet and Clank Up your Arsenal", there is an SPS problem in combat arena sequences. They are mostly triggered when a new wave of enemy spawn. Some COP2 timing changes made the game better in that regard but it is still very bad sometimes.

Note: Ratchet Going Comando also have the glitch.

Note 2: This bug was introduced after PCSX2 1.2.1 according to my testing.

Note 3: This bug is not a savestate problem, it happens despite using any of them, my video clip just shows how it can manifest during gameplay right before the glitch happens.

### Reproduction Steps

Load the provided savestate and see the SPS at the upper right side of the screen.

### Expected Behavior

The game should not produce this kind of SPS.

### PCSX2 Revision

GITHUB action PR build: https://github.com/PCSX2/pcsx2/pull/4966

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

EETiminghack + VUkickstart (applied with GameDB).

### GS Window Screenshots

The bug in action:

PCSX2:

https://user-images.githubusercontent.com/90222976/140657694-41aa18f3-1b23-4746-a03d-2d2f118cc41f.mp4

### Logs & Dumps

Savestate (ask blockdump if needed):
[Ratchet UYA - arena combat sps.zip](https://github.com/PCSX2/pcsx2/files/7492875/Ratchet.UYA.-.arena.combat.sps.zip)

**Comment by lightningterror** [comment]
Would be nice to track down the build that caused the regression.

**Comment by gilderoylockhart01** [comment]
gilderoylockhart01 is very dumb, because he forgot to test real hardware which, as surprising as it seems, also does have the problem ;).

**Comment by refractionpcsx2** [comment]
Good job ;) Sounds like another twitter post, if you can record real hardware for me?

**Comment by gilderoylockhart01** [comment]
Here is the best I can do, the quality is horrible but you will see the glitch just before the next round triggers, I did it on going comando which btw appears to also glitch in a similar fashion.

https://user-images.githubusercontent.com/90222976/141654438-3bd6d392-d96a-4589-9481-76de3f5ae84b.mp4

**Comment by refractionpcsx2** [comment]
Thanks for confirming :)

I'll hold off on posting it for now, I've only just posted the last one :D

**Comment by gilderoylockhart01** [comment]
What do you mean? Posting where?

**Comment by refractionpcsx2** [comment]
Twitter

**Comment by gilderoylockhart01** [comment]
Ahhhhhh! Thanks for the explaination, I was doing a Blue Screen of Death to be honest ^^. But yeah, we do emulate the (PAL only? maybe?) glitch of booth games, crazy right?

**Comment by refractionpcsx2** [comment]
It's pretty crazy! We've been getting a few games with bugs people are reporting, It's kinda nice we're at a point where people are  pointing out bugs that happen on the real console, means we've gotten to a good point.

**Comment by gilderoylockhart01** [comment]
To be fair, Ratchet runs very well in PCSX2 dev builds, if that wasn't for that weird turret bug it would have been perfect.

And if something like an "MTVU0" would be possible someday it would be the cherry on top for mid-range CPUs but even in it's current state, shouldn't be hard for modern machines to run this.

**Comment by refractionpcsx2** [comment]
MTVU0 would never work for Ratchet & Clank because the EE constantly reads from VU0, so performance would tank waiting for the thread.

**Comment by gilderoylockhart01** [comment]
Ah crap. Well, it runs well enough already anyway.
