### ISSUE TITLE
[Feature Request]: Integrate the "GS" and "GS Window" options that are currently in the general settings into the Graphics settings 

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5015]
### Description

Integrate the "GS" and "GS Window" options that are currently in the general settings into the Graphics settings..

### Reason

when the plugins were integrated they were integrated in the most direct way possible without changing the overall interface for the users. It would be good if all the settings and dialogs would eventually work their way into a configuration that would make sense for a single unified app.

### Examples

not really any pictures.

**Comment by stenzek** [comment]
They are already merged in the Qt UI (or rather, Display, OSD, and Graphics settings, in the one dialog).

**Comment by lightningterror** [comment]
As Sten said, already done on Qt, won't be done on wx.
