### ISSUE TITLE
[BUG]: Evolution Snowboarding - Extreme Slowdown

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5017]
### Describe the Bug

in hardware renderer during the opening opening level of the game when it goes into cut scenes the emulator  and my computer basically freezes. 

### Reproduction Steps

hardware renderer
start a new save 

### Expected Behavior

full fps

### PCSX2 Revision

1.7.2038

### Operating System

Windows 10 (64bit)

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

hardware renderer - slow
software renderer - fast

**Comment by refractionpcsx2** [comment]
yep the game memleaks to death going ingame, dunno why right now.

**Comment by prafullpcsx2** [comment]
Changed GS: Hardware to GS: Opengl as the bug doesn't happen in Direcr3D 11 Mode.

**Comment by refractionpcsx2** [comment]
In that case, what if you disable blending?

**Comment by prafullpcsx2** [comment]
> In that case, what if you disable blending?

Slowdown happens with or without blending so it's something else.

**Comment by refractionpcsx2** [comment]
Is this all on Nvidia by chance? I had a weird memleak in OpenGL with Everblue 2, but I couldn't make it rehappen or do it with a gsdump

**Comment by Squall-Leonhart** [comment]
Is there any chance its related to gl_interval?

nvidia has started to enforce gl_ name reservation and i can't see any khronos or nv extension for gl_interval, ignore me if its recast elsewhere, its just a gl_ name i've never seen before.

**Comment by prafullpcsx2** [comment]
This is a regression happened between 31st July 2015 - 1st August 2015. There were lots of blending related changes at that time. I am able to compile those gsdx builds but for some reason they aren't working with PCSX2 so I can't pinpoint which is the exact change that makes it slow. https://github.com/PCSX2/pcsx2/commits/1.4.x?after=21012a8ec368d3e88a5f3d00030d061e21fcc9a7+740&branch=1.4.x

**Comment by seta-san** [comment]
I’m not home to try it but does disabling depth emulation help?

**Comment by lightningterror** [comment]
It seems to be a weird interaction with accumulation blend on clamp 0 and MTVU, disabling MTVU or accumulation blend seems to avoid the issue, needs to be investigated.

**Comment by Squall-Leonhart** [comment]
Might be https://github.com/PCSX2/pcsx2/commit/e026f1bac69230940fe22f8c7b2b7f82ed620927#diff-d805226dbff36e421cc223767577c835b98048ffe6fc1f6eb7750170b4c17131L505
