### ISSUE TITLE
[BUG]: Using the "Shutdown" option while frame advancing just restarts emulation

### ISSUE THREAD

**Issue by sonicfind** [PCSX2/pcsx2#5018]
### Describe the Bug

If you select the "Shutdown" option in the "System" drop-down menu while in a paused state from frame advancing, instead of shutting down, emulation will just restart. This only applies when an input recording is _**not**_ being run, or in other words, we get the intended behavior of the shutdown if a recording is active.

### Reproduction Steps

See Description

### PCSX2 Revision

dev-1.7.2039

### Operating System

Windows 10 (64bit)

### CPU

i5-8250u

### GPU

intel uhd 620

**Comment by Mrlinkwii** [comment]
is this still an issue?
