### ISSUE TITLE
[BUG]: x64 texture problems in Barnyard SW mode

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#5025]
### Describe the Bug

64bit seems to have serious texture problems on Barnyard, it's not great on x86 either to be fair since the cow is trippy, but the rest of the scene is normally fine. Also the UI appears to be missing in x64 also.

Best guess: Mipmapping is broken on 64bit somewhere. however mipmapping has problem in the software JIT anyway (see #4825 )

### Reproduction Steps

Load the gsdump in an x64 version of PCSX2

### Expected Behavior

The trees in the background aren't missing and the floor doesn't look broken

### PCSX2 Revision

v1.7.2047

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 3900x

### GPU

RTX 2080Ti

### GS Settings

Software mode, all options ticked 5 threads

### GS Window Screenshots

32 Bit: 
![image](https://user-images.githubusercontent.com/6278726/142072361-faa3b6e1-fd77-4280-abd2-0045c68560d7.png)

64bit:
![image](https://user-images.githubusercontent.com/6278726/142072426-76bb63d9-9f64-4c27-81ef-4b7f69757276.png)

### Logs & Dumps

[gsdump_barnyard_textures.zip](https://github.com/PCSX2/pcsx2/files/7550103/gsdump_barnyard_textures.zip)

**Comment by HeroponRikiBestest** [comment]
This bug also heavily affects Jurassic Park: Operation Genesis

**Comment by refractionpcsx2** [comment]
The freaky coloured cow is now fixed in #5569

Floor issue in x64 remains

**Comment by and468860** [comment]
hi to me, bad game in full hd or original screen all are using nvidia 1050 and old intel 7 windows 10
[Nickelodeon Barnyard (USA) (2022-01-27 07-41-09).zip](https://github.com/PCSX2/pcsx2/files/8148332/Nickelodeon.Barnyard.USA.2022-01-27.07-41-09.zip)


[gs_20220227074152](https://user-images.githubusercontent.com/61087055/155874601-24e05df8-5cdd-48af-830f-95fb6c200f5d.png)
![gs_20220227074236](https://user-images.githubusercontent.com/61087055/155874605-4de2535d-77d6-40c1-9e22-81dbf79a65be.png)
![gs_20220227074319](https://user-images.githubusercontent.com/61087055/155874609-ad41b2df-638f-4ba2-9f4a-1df8f1981821.png)
![gs_20220227074324](https://user-images.githubusercontent.com/61087055/155874611-6deec294-6b4c-4550-960f-fd93fcf0c71e.png)

**Comment by F0bes** [comment]
Here is a pretty basic example of broken mipmapping.
[mipmapping.zip](https://github.com/PCSX2/pcsx2/files/8191746/mipmapping.zip)

64 bit
![image](https://user-images.githubusercontent.com/29295048/156904582-dbcb32ca-99e9-4800-9a37-87354c2fa53f.png)

32 bit
![image](https://user-images.githubusercontent.com/29295048/156904628-51ea3369-7dbd-4c4e-99e1-88860a1d5807.png)
