### ISSUE TITLE
[BUG]: Appimages not contained plugins

### ISSUE THREAD

**Issue by varlesh** [PCSX2/pcsx2#5034]
### Describe the Bug

No plugins

### Reproduction Steps

- download appimage
- extract for example:
`./pcsx2-v1.7.2051-linux-AppImage-64bit.AppImage --appimage-extract`
- find any plugin:
`find . -name libGSdx.so`

### PCSX2 Revision

1.7.2051

### Operating System

Linux (64bit)

**Comment by kenshen112** [comment]
This is correct behaviour as pcsx2 itself has done away with plugin files entirely

**Comment by varlesh** [comment]
ok
