### ISSUE TITLE
[BUG]: Slowdown Justice League [SLUS_213.04]

### ISSUE THREAD

**Issue by JimiMonkey** [PCSX2/pcsx2#5036]
### Describe the Bug

Hello there, starting from build pcsx2-v1.7.0-dev-1915-g6ed00107cf-windows-x86 the game Justice League Heroes NTSC-U is running in very low fps, 5fps or ~10% game speed in HARDWARE renderers, in SOFTWARE this does not occour. I tested every single build until v1.7.2052 and it is still there, all of them on clean setups, native res. In pause screen, though, there is no slowdown.
I run a core i5-3570 non k, 16GB RAM, GTX 1060 3GB, Driver GeForce Game Ready WHQL 472.12, windows 11 but tested on W10 and happens there too

In game
![2021-11-20](https://user-images.githubusercontent.com/31172426/142730365-95a02464-8cde-4d2e-b32b-360e658d8aaa.png)
Character pause menu (select button)
![2021-11-20 (2)](https://user-images.githubusercontent.com/31172426/142730963-7212d7d9-fae1-4b76-b889-b9428c4bcf50.png)

### Reproduction Steps

Start a new game in any build starting from 1.7.0-1915, once in game the game struggles really hard.

### Expected Behavior

The game runs fine at 60fps in build 1.7.0-1914 and lower in hardware renderers, I play this game since 1.6.0 once in a while.

### PCSX2 Revision

1.7.0-dev-2052

### Operating System

Windows 10 (64bit)

### CPU

i5-3570

### GPU

GTX 1060 3GB

### GS Settings

all default for the sake of this test, normally I run at preset 3 which activates MTVU, 3x resolution, cheats, panoramic and interlacing codes enable and still happens there.

### Emulation Settings

![2021-11-20 (4)](https://user-images.githubusercontent.com/31172426/142730766-7d432302-6d24-42d4-8efe-b0bddc6e4bf2.png)

### GS Window Screenshots

![2021-11-20 (5)](https://user-images.githubusercontent.com/31172426/142730778-5f4de858-080c-49ff-8309-3d3530eb426b.png)

### Logs & Dumps

[gs_20211120115156.gs.zip](https://github.com/PCSX2/pcsx2/files/7574700/gs_20211120115156.gs.zip)

**Comment by lightningterror** [comment]
Can you try a build from https://github.com/PCSX2/pcsx2/actions/runs/1455260473 and see if the issue persists?

**Comment by refractionpcsx2** [comment]
I don't think you updated correctly, since none of your pictures are a new version and I tried 1920 and that was slow, but master is very fast.

**Comment by JimiMonkey** [comment]
> 
this build runs fine as used to be
![2021-11-20 (6)](https://user-images.githubusercontent.com/31172426/142736984-75c84b8d-4f17-4eb2-ba70-5d33bd220523.png)
e

**Comment by refractionpcsx2** [comment]
okay but can you recheck the latest master? as far as I can tell that also works fine.

**Comment by JimiMonkey** [comment]
Latest master runs very slow, as you can see I'm showing different sections of the game and it persists in every scenario

![2021-11-20 (7)](https://user-images.githubusercontent.com/31172426/142737208-c12b9dc1-841f-4327-9e8a-ec135abc02e6.png)

**Comment by refractionpcsx2** [comment]
Very strange, latest master does not run slowly for me.

**Comment by Squall-Leonhart** [comment]
Did you turn off Threaded Optimization in the nvcp?

**Comment by JimiMonkey** [comment]
Directx GPU Palette Conversion on
![2021-11-21 (6)](https://user-images.githubusercontent.com/31172426/142760815-ceec9483-6804-4647-af76-5df44df78f67.png)

Directx GPU Palette Conversion on, after a few seconds something happens and everything goes back as before
![2021-11-21 (7)](https://user-images.githubusercontent.com/31172426/142760817-05a88675-c8c9-4369-91c9-1e1e176b9b6b.png)

Different section
Directx GPU Palette Conversion off
![2021-11-21 (8)](https://user-images.githubusercontent.com/31172426/142761008-dacb0ca2-29c3-4e6b-8046-114916958be7.png)

Directx GPU Palette Conversion on
![2021-11-21 (9)](https://user-images.githubusercontent.com/31172426/142761010-a629e557-23da-4e3e-9772-02d45ada1fd1.png)

**Comment by Squall-Leonhart** [comment]
Your CPU is throttling, check the power profile and thermals.

**Comment by JimiMonkey** [comment]
Power profile  set to high performance 
current build
![2021-11-21 (10)](https://user-images.githubusercontent.com/31172426/142761391-dadd463a-6136-4d15-811f-42d3373f9777.png)

build 1914, last stable for this game for me
![2021-11-21 (11)](https://user-images.githubusercontent.com/31172426/142761399-529b5347-c586-4101-9461-8842f70626d4.png)

**Comment by Squall-Leonhart** [comment]
I'm seeing it now, my cpu clocks are keeping it above 60% though, 

1915 removed an optimization that it would appear this game took advantage of.

@tadanokojin you might get your chance to look at that buggy optimization after all.

**Comment by Squall-Leonhart** [comment]
@JimiMonkey subscribe to https://github.com/PCSX2/pcsx2/pull/4971 and test the nightly when it lands.

**Comment by Squall-Leonhart** [comment]
It just occurred to be to check the bus interface, and this game has it at around 30-35%, 

The gpu could be choking on texture uploads, which iirc maxwell and pascal both had an issue with if they were being slammed with them - in comparison, Xenosaga or KH2 are 2-4%, when run unlimited - your 2080(ti?) could be having no issues with it @refractionpcsx2

**Comment by JimiMonkey** [comment]
latest master seem to have fixed the issue, i'll assume it was build 2059, thank you very much everyone
![2021-11-21 (12)](https://user-images.githubusercontent.com/31172426/142779529-fab11ff8-d23e-4d15-9360-9e2b6b95f6ba.png)

**Comment by refractionpcsx2** [comment]
Glad it's fixed :)

**Comment by Squall-Leonhart** [comment]
Yep, Bus interface performance has dropped from 30% (PCIE2) to 4% or 9% depending on the palette conversion setting, 100% speed attained.
