### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by libetu** [PCSX2/pcsx2#5038]
### Describe the Bug

graphics glitches happen in this game when playing kof94 rebout, also faces doesn't appear on the power circle next to the life bar. that be great if can fix all that.

### Reproduction Steps

graphical improvement to play the game

### PCSX2 Revision

1.6.0

### Operating System

Windows 10 (64bit)

### CPU

i7 3770

### GPU

gtx 1050ti

**Comment by refractionpcsx2** [comment]
Closing as it's basically the same issue as this: https://github.com/PCSX2/pcsx2/issues/3496
