### ISSUE TITLE
[BUG]: Problems opening ELFs with involving unicode paths

### ISSUE THREAD

**Issue by xTVaser** [PCSX2/pcsx2#5042]
### Describe the Bug

Attempting to run an ELF that otherwise works in a path that involves unicode characters causes issues atleast on Windows.

Found when testing - https://github.com/PCSX2/pcsx2/pull/4747

### Reproduction Steps

Either modify the name of the ELF to include a unicode character like `Д` or modify the directory that contains the ELF in a similar manner.

### Expected Behavior

The ELF should boot in the same manner as when these characters are not in the path

### PCSX2 Revision

v1.7.2054

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

Radeon 5700 XT

**Comment by Mrlinkwii** [comment]
is this still an issue on nightly ?

**Comment by CookiePLMonster** [comment]
No longer an issue, verified in v1.7.4927. A test case with a path `"H:\ŻąłóРстуぬねのはen\🍪⟑η∏☉ⴤℹ︎∩₲ ₱⟑♰⫳🐱\Roa Ming\pąd tęśt\ｐａｄｔｅｓｔ_ｐｓ２.elf"` worked fine in all these cases:
1. Running from the Game List.
2. Running via `Start File...`.
3. Dragging and dropping the ELF file on PCSX2 window.
4. Running the ELF via `Open with...` in Windows.
