### ISSUE TITLE
[Feature Request]: Enable analog button in PS3 controllers (digital pad to left analog)

### ISSUE THREAD

**Issue by Augusto7743** [PCSX2/pcsx2#5045]
### Description

In Linux PCSX2 use own controller plugin being possible use PS3 controller.
PS3 controller works correctly.
The PS3 controller PS menu button maybe assigned to PS2 controller analog button thus allowing to change digital pad to left analog for some games.
Unhappily PS3 controller digital pad not is exactly good to use than PS1 and PS2.
PS3 controller digital pad is good for menu or select item and using to controll player character is terrible.

### Reason

Thus users will use better the PS3 controller.

### Examples

I not known other emulator that enable analog using a controller button.

**Comment by FMA606** [comment]
Cv 
**

- [ ] Ok **

**Comment by FMA606** [comment]
#

**Comment by Mrlinkwii** [comment]
is this still an issue on latest master ?

**Comment by refractionpcsx2** [comment]
Qt auto maps the PS button to the analog button, so this should be resolved.
