### ISSUE TITLE
[Feature Request]:  Texture Replacement/ Texture Dumping

### ISSUE THREAD

**Issue by fbievan** [PCSX2/pcsx2#5046]
### Description

This was talked about before, and has been implemented, but kind of got sidetracked. This issue is to try and get this to actually be implemented. Topaz's implementation works great, at least for most peoples usage and should be based off that. 

All i want is atleast something experimental. 

### Reason

Alot of projects can benefit from this, Like 2K5 Resurrected.
This would make this emulator just a whole lot better for modders in general. 

Actually being able to bring in player models and custom textures on Linux, the only build that works of the original implementation is the Windows binary 

Just a general feature that I think an emulator  should have

Replacing the PlayStation buttons with Xbox buttons (i mean its just nice to have, I have already learned how to use the PlayStation buttons on an Xbox one controller) 

https://github.com/PCSX2/pcsx2/issues/4038

Would just be fun
### Examples

https://github.com/PCSX2/pcsx2/pull/4199 (This is old and does not work, and is outdated)
https://www.youtube.com/watch?v=v-mNOzGiXM4
https://www.youtube.com/watch?v=IZBy5Dtu3rw (Really all you need is a checkbox)

**Comment by gilderoylockhart01** [comment]
Yup, nice idea. This is especially relevant with today's AI upscaler softwares such as gigapixel and the fast that quite a bit PS2 games ran with low resolution textures.

**Comment by fbievan** [comment]
> Yup, nice idea. This is especially relevant with today's AI upscaler softwares such as gigapixel and the fact that quite a bit of PS2 games ran with low resolution textures.

I feel like the primary usage of texture replacement would be something like this. Or even changing most of the game. Insane with what you could do with this one feature.

**Comment by fbievan** [comment]
Hopefully this will eventually by some person be implemented. I can only hope. I'm going quiet on this thread for now.

**Comment by PipoCrazy** [comment]
For real, I have just mentioned this. I would love to make it happen. Aren´t there any working versions of his modified gsdx plugin?

**Comment by fbievan** [comment]
Not any, that I've found. None that would build on Linux so.

**Comment by Mrlinkwii** [comment]
> For real, I have just mentioned this. I would love to make it happen. Aren´t there any working versions of his modified gsdx plugin?

plugin system has been gone for a long while now ,

**Comment by fbievan** [comment]
Yeah

**Comment by fbievan** [comment]
> > For real, I have just mentioned this. I would love to make it happen. Aren´t there any working versions of his modified gsdx plugin?
> 
> 
> 
> plugin system has been gone for a long while now , 

Yeah.

**Comment by F0bes** [comment]
I don't believe any productive discussion can happen on this feature request. Locking but keeping open because at the end of the day it is a request.
