### ISSUE TITLE
[BUG]: Crisis Zone: Sync XGKICK causing SPS and game crashing.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5047]
### Describe the Bug

In the game "Crisis Zone", enabling Sync XGKICK will break the game graphics and causes the whole emulator to crash to the desktop.

Edit: same goes for the VU1 interpreter.

### Reproduction Steps

Load the blockdump and savestate.

### Expected Behavior

The game should render properly.

### PCSX2 Revision

v1.7.2058

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

Sync XGKICK. (not needed but more accurate to real hardware)

### Logs & Dumps

Blockdump+savestate: https://drive.google.com/file/d/1je-Dfmt9JCJQYMcIZ80jNDl6qQ7T0H_k/view?usp=sharing

**Comment by gilderoylockhart01** [comment]
I will write that here not to create 2 distinct threads, but this is also the case for Ridge Racer on the namcollection.

With sync XGKICK:

![1](https://user-images.githubusercontent.com/90222976/142767610-d284b61f-cf2f-4869-8459-09b50962d630.png)

Without sync XGKICK:

![2](https://user-images.githubusercontent.com/90222976/142767618-9b2fb59c-5421-438f-b9e2-a74efb783131.png)

https://drive.google.com/file/d/1vH1PkWeXbvN2wqnXn1Hq0Ob5Ym98b6f4/view?usp=sharing

**Comment by refractionpcsx2** [comment]
is the interpreter the same?

**Comment by gilderoylockhart01** [comment]
Mmm, not on that one, the interpreter is fine.

**Comment by gilderoylockhart01** [comment]
The game crashing bug was introduced with this commit: https://github.com/PCSX2/pcsx2/commit/b8a2cd1b064ed598b95c9b9e5601142ffbc4da3d

**Comment by refractionpcsx2** [comment]
Can you provide a new dump/state please? savestate version changed recently. I tried crisis zone myself and it's not crashing.

**Comment by refractionpcsx2** [comment]
How do you get the crash to happen? it works fine for me.

**Comment by gilderoylockhart01** [comment]
This is with the lastest fresh build from buildbot:

https://user-images.githubusercontent.com/90222976/142772991-34f3d377-906b-480c-b2ea-b5636496d880.mp4

As you can see the whole emu crashes after I blow up the glass.

**Comment by refractionpcsx2** [comment]
Didn't mean to close this issue, silly auto thing.

okay are you doing anything specific that makes it crash?

**Comment by gilderoylockhart01** [comment]
Yeah, pressing r1 + x to fire on the glasses to shoot the enemy behind.

**Comment by refractionpcsx2** [comment]
hmm okay, that didn't crash for me, i guess I'll keep trying

**Comment by gilderoylockhart01** [comment]
I will try with visual studio when I have the time to do so.

**Comment by refractionpcsx2** [comment]
if you're building yourself can you run it through the debugger to catch the crash and see what it doesn't like?

**Comment by gilderoylockhart01** [comment]
What a weird thing, a build compiled with visual studio based on master is fine.

**Comment by refractionpcsx2** [comment]
So what did you build with before?

**Comment by gilderoylockhart01** [comment]
I didn't build anything, I just used the latest build from buildbot.

**Comment by refractionpcsx2** [comment]
which version did you use?

**Comment by refractionpcsx2** [comment]
Maybe @arcum42 has some insight maybe?

**Comment by gilderoylockhart01** [comment]
I used the very latest version with the xgkick fixes.

**Comment by refractionpcsx2** [comment]
No I mean was it the AVX2 or SSE4, or was it CMake?

**Comment by gilderoylockhart01** [comment]
Ah, it was AVX2

**Comment by refractionpcsx2** [comment]
hmm weird, is it still doing it on the latest builds? or can I pretend it never happened? 😎

**Comment by gilderoylockhart01** [comment]
I will test again on the latest one when I will be back home

**Comment by gilderoylockhart01** [comment]
Ok, you can pretend it never happened ;).

**Comment by and468860** [comment]
the game is again broke after i blow the glass

hi test Time Crisis Crisis Zone how to rederer vulcan dx11 it to read it depends on opengl da well

I'm using nvida 1050 ati drives 441.87

**Comment by and468860** [comment]
the game is again broke after i blow the glass

hi test Time Crisis Crisis Zone how to rederer vulcan dx11 it to read it depends on opengl da well

I'm using nvida 1050 ati drives 441.87

**Comment by and468860** [comment]
the game is again broke after i blow the glass

hi test Time Crisis Crisis Zone how to rederer vulcan dx11 it to read it depends on opengl da well

I'm using nvida 1050 ati drives 441.87
