### ISSUE TITLE
[Feature Request]: Use game serial number instead of CRC for appying GS hacks

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#5062]
### Description

The GS currently identifies games based on CRC, it should instead identify games based on the serial number instead.

### Reason

This would bring the GS CRC hacks system more inline with the core gamefixes system, which applies fixes based on serial numbers.

This would allow GS fixes to apply to undubs, fan translations or games patched for resurrected servers without the need for unofficial CRCs.

### Examples

An example would be Project Metafalica, an Ar Tonelico II relocalization.

The game (and the relocalization) suffered from incorrect rendering of the world map (https://github.com/PCSX2/pcsx2/issues/1762) but was fixed with a GS CRC hack,
As only the CRCs of official releases are included, the relocalization remains broken.
Also see https://github.com/PCSX2/pcsx2/pull/5053 for recent discussions

Other example games include;
- Wild Arms 5 undub (Removed https://github.com/PCSX2/pcsx2/pull/4082)
- - Unknown, CRC hack for Wild Arms 4 & 5 has existed for a long time
- Tales Of Abyss undub (Removed https://github.com/PCSX2/pcsx2/pull/4082)
- - I think this is an upscaling fix
- Star Ocean 3 undub (Removed https://github.com/PCSX2/pcsx2/pull/4082)
- - Emulates a stencil buffer with the alpha channel of the RT, done to improve speed
- Nightshade undub (Rejected PR https://github.com/PCSX2/pcsx2/pull/4687)
-  - Removes (or fixes?) bugged shadows (https://github.com/PCSX2/pcsx2/issues/3988)

**Comment by orbea** [comment]
Are there any cases where only one version of the game needs a crc hack?

What issues are solved by the crc hacks in the other examples?

**Comment by refractionpcsx2** [comment]
With the GameDB/Patches, we did it from CRC because the chance of collision from serial is higher than that of CRC (surprisingly), but in the case of GS CRC hacks, that might be doable without being too invasive since it generally needs to be specific scenarios on top of the CRC (or serial, in this case)

**Comment by TransparentBlue** [comment]
Wouldn't the ability to manually override CRC be enough to cover that issue?

**Comment by refractionpcsx2** [comment]
how would it know to manually override with the CRC? the core would have to know via gamedb or something, but that defeats the point in this request which is supposed to make it generic so things like fan translations work.

**Comment by TheLastRar** [comment]
I've updated the issue with a brief description of what I think the CRC hacks for the other games are doing

As for figuring out if only some versions of the same serial need the a CRC hack, you might be able to check the number of entries for a given game and compare with the number of entries on Redump (as they list different versions/re-releases separately if the contents of the disc is different)

**Comment by TransparentBlue** [comment]
>how would it know to manually override with the CRC? 
What I meant by manually is that you manually specify that you want PCSX2 to treat a specific .iso as if it were another  CRC you yourself have specified or maybe treat a CRC as an alias of another.

**Comment by RedDevilus** [comment]
No need for an alias if it has the same CRC. And if you need something less strict than CRC (ex. AAAA1234) you can just use the serial (ex. SLUS-12345)

**Comment by refractionpcsx2** [comment]
> > how would it know to manually override with the CRC?
> 
> What I meant by manually is that you manually specify that you want PCSX2 to treat a specific .iso as if it were another CRC you yourself have specified or maybe treat a CRC as an alias of another.

Hmm not sure I like the UX of that and I can envision people who don't know what they're doing messing with it.  I might be overly paranoid since entries in the GS for hacks are rarely used, so it might be uncommonly used enough to be fine.

**Comment by RedDevilus** [comment]
10.000 Serials has lots of CRC collisions.
Let's exaggerate with potential GS CRC hacks to number 500 in total for the future which will almost be impossible to have a CRC collision.

**Comment by TransparentBlue** [comment]
>Hmm not sure I like the UX of that and I can envision people who don't know what they're doing messing with it.

I see your point, maybe allowing to override CRC via pnach could work and not have those issues?

**Comment by refractionpcsx2** [comment]
It would be nice to move the CRC hack stuff to the gamedb, but that's really a future job, lots of stuff going on at the moment so priority is a little low on that :P

**Comment by RedDevilus** [comment]
Reason why this exists:
https://github.com/PCSX2/pcsx2/issues/3568

**Comment by IlDucci** [comment]
Hold on, are these hacks available for use within the GUI or out of reach from it? Because if it's the latter case, maybe you could have an external configuration file, kinda like the PNACH system.

**Comment by RedDevilus** [comment]
It's this option:
![image](https://user-images.githubusercontent.com/24227051/143131806-67fe9a9d-2d8e-49f5-a9b3-1cee175cf498.png)

The CRC system is pretty scuffed anyway. Hence why it should be ported as a patch (pnach) or fixed.

**Comment by orbea** [comment]
> That way modders and fantranslators could include the file with their patches, or the community could do this as well.

Maybe its a minor point, but I feel it would be better to have the hacks tied directly to the emulator than the content so that when they are accurately fixed the hacks can be removed entirely from all future versions of the emulator.

**Comment by refractionpcsx2** [comment]
> > That way modders and fantranslators could include the file with their patches, or the community could do this as well.
> 
> Maybe its a minor point, but I feel it would be better to have the hacks tied directly to the emulator rather than the content so that when they are accurately fixed the hacks can be removed entirely from all future versions of the emulator.

What?

**Comment by orbea** [comment]
Can you elaborate on what needs to be clarified?

**Comment by refractionpcsx2** [comment]
Everything. I don't knew what you're asking us to do. Sounds like you want us to make them magically work without knowing what game it is

**Comment by orbea** [comment]
I'm not saying that and I'm not sure how you arrived at that conclusion...

I was replying to a comment that suggested having an external configuration file to tell pcsx2 what hacks to enable that would be shipped with the game patches that needed them or from a community project. I thought it would be better to not do that so that pcsx2 developers can entirely remove the hacks when appropriate (i.e. The bug gets fixed).

**Comment by refractionpcsx2** [comment]
Okay that makes more sense. We'll the extremal file (like the gamedb) would have to be maintained by us too and updates with newer versions of the emulator, so they will be removed as we fix the problems

**Comment by RedDevilus** [comment]
> I'm not saying that and I'm not sure how you arrived at that conclusion...
> 
> I was replying to a comment that suggested having an external configuration file to tell pcsx2 what hacks to enable that would be shipped with the game patches that needed them or from a community project. I thought it would be better to not do that so that pcsx2 developers can entirely remove the hacks when appropriate (i.e. The bug gets fixed).

That's basically the GameIndex.yaml, the GameDB we use for automatic game fixes and patches which creators should convert their CRC Hacks to, to avoid all this mess.

**Comment by orbea** [comment]
Since @refractionpcsx2 rather censor than have a conversation lets try again here... https://github.com/PCSX2/pcsx2/pull/5082#event-5681905382

@RedPanda4552 

> Supporting unofficial CRCs sets the standard that all romhacks must be supported, which means making code modifications for all romhacks on this planet which might use CRC hacks. We want to avoid that at all costs.

I am not making that argument, but regardless these are specific CRC hacks all apply to official versions of the game as well and have real value for users.

> Removing CRC hacks for unofficial CRCs will in turn create pressure for problems to actually be solved instead of CRC hacked.

I doubt this issue will be solved anytime soon regardless if the hacks are added back or not, but please prove me wrong! :+1: 

I don't think its harmful to keep these hacks as a stop gap.

> If you really need these CRC's in PCSX2 to play your rom hack, feel free to use an old version of the emulator. These aren't going back in, end of story.

Already done, but what about the other users? You are only hurting your user base for no gain.

**Comment by refractionpcsx2** [comment]
I said drop it, it's not happening.

**Comment by RedDevilus** [comment]
PCSX2 in the past gets labeled as hacky, PCSX2 doesn't want to go hacky again. Can't have it all.

**Comment by orbea** [comment]
@refractionpcsx2 Why are you so resistant to having a conversation? What was wrong with what @gregory38 said when the CRC was originally added? Again you are hurting your user base for no gain.

> PCSX2 in the past gets labeled as hacky, PCSX2 doesn't want to go hacky again. Can't have it all.

Removing these CRCs did nothing to solve that, you still have the hacks for other versions of the same game.

**Comment by refractionpcsx2** [comment]
I told you to stop, goodbye
