### ISSUE TITLE
[Feature Request]: [Github Meta]: Can pre-release builds not get notified for people who "watch" this repository for "releases"?

### ISSUE THREAD

**Issue by ImSpecial** [PCSX2/pcsx2#5063]
### Description

Maybe not the best title, I dunno how to word it better... anyway, what I mean is not to long ago something changed and I've been getting a TON of notifications about every single "per-release" build that comes out, so much so that I had to stop watching this hub all together. Can something be tweaked to not have this happen for all the the per-releases? (maybe this is desired or wanted behavior? If so I guess you can disregard this.) 

This is what I mean for "watching" releases;
https://i.imgur.com/cqRBVW7.png

### Reason

annoyance, not necessary?

### Examples

.

**Comment by refractionpcsx2** [comment]
Not sure if #5059 is related but possibly something @xTVaser could look in to, maybe.,

**Comment by ImSpecial** [comment]
That does sound eerily similar, could be what I'm asking for even, I dunno how all this stuff works tbh. But I figure it's better to ask here in the Issue side of things and not hijack his pull request which could be for something different.

**Comment by orbea** [comment]
I think its tied to the creation of git tags, I had to turn off the notifications in this repo because of this as well.

**Comment by xTVaser** [comment]
This is determined by your default notification settings in your GitHub account I believe, and is unfortunately out of our control as far as I'm aware.  I'd love to disable notifications on releases as a maintainer, but as I said -- not aware of a way to do so.  If I'm wrong though (or this changes in the future), happy to make the change.

My PR linked above only pertains to announcing releases in the discord, so it won't solve this.

The workaround is each individual has to configure their notification defaults accordingly / change it on a per repo basis
![image](https://user-images.githubusercontent.com/13153231/143148777-bf104dcd-b8de-4261-8651-0c2d290e9d03.png)
More docs - https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications

Making a new discussion (or jumping on board an existing one) here https://github.com/github/feedback/discussions may be your best bet.  Sorry for the inconvenience!

**Comment by orbea** [comment]
@xTVaser The github notifications doesn't allow a setting of following only some git tags as a far as I am aware. When enabling `Releases` as shown in your image it will alert for every single git tag made for the repo which pcsx2 does every day now.

I think either people will have to not subscribe to releases or the pcsx2 devs will have to use git tags more sparingly.

**Comment by xTVaser** [comment]
Yes that is my point, people will have to unsubscribe to releases if it is bothering them at this time.
