### ISSUE TITLE
[BUG]: Hot Wheels World Race have some disappearing textures on the map Cloud 9

### ISSUE THREAD

**Issue by MajBoss** [PCSX2/pcsx2#5066]
### Describe the Bug

In Hot Wheels World Race, on the map Cloud 9. When exiting the starting tunnel, the textures do not stay loaded in regardless if you use OpenGL or Direct 3D 11. The textures are loaded in as you are exiting the tunnel, but once you cross into the outside of part of the track, the textures disappear.
![Screenshot (1000)](https://user-images.githubusercontent.com/84467605/143171735-cbbbbb23-bfbc-4ea6-89b0-c815a6c2e00a.png)

### Reproduction Steps

Boot Hot Wheels World Race, go to the Cloud 9 map. And once you exit the tunnel all the textures should disappear.

### Expected Behavior

The textures shouldn't be disappearing.
![Uploading Screenshot (999).png…]()
(If the image above doesn't work, try this image link underneath.)
(It's what the map looks like right before exiting the tunnel.)
https://ibb.co/VMCKGKv

### PCSX2 Revision

dev-v1.7-2077

### Operating System

Windows 10 (64bit)

### CPU

i5 10600k

### GPU

GTX 1050TI

### GS Settings

All GS settings are default.

### Emulation Settings

All Emulation Settings settings are default.

### GS Window Screenshots

![Screenshot (1000)](https://user-images.githubusercontent.com/84467605/143171811-7ffb6ea9-a276-4686-9346-15d3e71daaf3.png)

### Logs & Dumps

(My memcard file from Documents folder)
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/7605236/Mcd001.zip)

**Comment by refractionpcsx2** [comment]
That memcard was no use as it's unformatted, however somebody using Nightly 2077 version with the US version of this game shows that it's fine for them.

**Comment by MajBoss** [comment]
Newest dev build (2078) of PCSX2 fixed this issue for me.
