### ISSUE TITLE
[GameDB]: 2K sports games, replace patches with syncVU1.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5079]
### Describe the Bug

Now that we have proper CDVD timings, the 2K games sports titles can now be fixed with instantVU1 disabled.

This is great news as this will allow the removal of all the patches concerning 2k games sports titles such as NBA, NHL ect..

The safest option would be to apply instantVU1 = 0 as well as MTVU off to all the NBA,NHL,NFL and MLB games starting with the 2004 entries (except MLB which uses that engine only with the 2005 entry and up) all the way up to the latest (which can go up to 2012 if I remember).

I am sorry in advance for the peoples that will do that, yeah, a pain for sure but what an achievement.

### Reproduction Steps

Play the 2K games sports titles with instantVU1 off and see how everything (incuding HDD suport) is now fully working.

Please note some entries will need the I-BIT gamefix.

### PCSX2 Revision

v1.7.2082

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

**Comment by prafullpcsx2** [comment]
I tried latest master and none of the games work. We need some pr or specific settings for this?

**Comment by gilderoylockhart01** [comment]
Make sure the cyclerate is at default and that you are running a PCSX2 version with at least this commit: https://github.com/PCSX2/pcsx2/commit/afacc47f33341bfdbe9972078c339262745c6cfa

So far I tested NHL 2K5, MLB 2K10 and College Hoops 2K6 and all 3 are working just fine.

**Comment by prafullpcsx2** [comment]
> Make sure the cyclerate is at default and that you are running a PCSX2 version with at least this commit: [afacc47](https://github.com/PCSX2/pcsx2/commit/afacc47f33341bfdbe9972078c339262745c6cfa)
> 
> So far I tested NHL 2K5, MLB 2K10 and College Hoops 2K6 and all 3 are working just fine.
> 
> Edit: yeah, the game will not work with any other cyclerate changes and this must be done at runtime.

At runtime? What's the meaning of this? I have speedhacks totally disabled and it still doesn't work.

**Comment by gilderoylockhart01** [comment]
I mean that you must do the changes before starting the game, unlike the patch you can't apply the changes on the fly.

Edit: apparently, you seems to be right, I just tried a brand new build, and the game doesn't work anymore "unless" I put the HDD image I had in the dev9 plugin, then it works again. Super weird.

I guess I will close that for now until I find a reliable setting.

**Comment by gilderoylockhart01** [comment]
Okay, now I can reproduce it again with the very latest build.

**Comment by refractionpcsx2** [comment]
This is one of those games which is a random timing thing, there's no specific fix that we know, just stuff that alters the timing of it. Even booting it then booting it again gives different results.

There's no specific change we've done or will do that will change it until somebody works out exactly what's going on.
