### ISSUE TITLE
[BUG]: Gamepad missing Ry axis

### ISSUE THREAD

**Issue by hugleo** [PCSX2/pcsx2#5080]
### Describe the Bug

One of the axis of the right joystick is not being recognized. Just RX is working (inverted though).

Both axis are recognized and working using the jtest-gtk tool. Images attached.

![axis-pcsx2-padtest](https://user-images.githubusercontent.com/4573505/143775107-ecfddfc4-e8e2-4a27-b848-bfcbf98d5e35.png)

![gamepad-jtest](https://user-images.githubusercontent.com/4573505/143775110-9093f173-f179-4934-a869-630506f5092d.png)

### Reproduction Steps

Tested with games and padtest.elf

### PCSX2 Revision

1.7.2040

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

i3-4130

### GPU

Intel Integrated Graphics Controller

**Comment by kenshen112** [comment]
This is a support question more than a github issue. Please use our forms or the official discord server for even faster support
