### ISSUE TITLE
[BUG]: Kensetsu Juuki Kenka Battle - Buchigire Kongou!! (Japan) - HW Renderer - Minor corruption around edges of screen during and just before FMVs

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5094]
### Describe the Bug

When using Hardware rendering; when FMVs play, minor corruption appears around the edges of the screen, specifically the bottom and right edges. Additionally, more corruption is briefly visible just before the new game FMV plays.

Additionally, this bug only appears to happen in the Japanese version. The European version has no such corruption.

### Reproduction Steps

Boot the game with the HW renderer. Skip the artdink/opening FMV or keep watching. Once the title screen appears, press circle twice to see the next FMV.

### Expected Behavior

I expected not to see any corruption on or before the FMVs when using the HW renderer.

### PCSX2 Revision

PCSX2 1.7.0-0 - compiled on Dec 2 2021 (daily ppa doesnt show git number)

### Operating System

Linux (32bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Window Screenshots

![gs_20211202142015](https://user-images.githubusercontent.com/50224630/144490112-552e0785-106a-49fd-b930-8d6517fb62f3.png)
![gs_20211202142213](https://user-images.githubusercontent.com/50224630/144490115-884bb62e-039b-4858-bb73-7e1dd820f175.png)

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7644624/emuLog.txt)
[gs_20211202142213.gs.zip](https://github.com/PCSX2/pcsx2/files/7644629/gs_20211202142213.gs.zip)

**Comment by Mrlinkwii** [comment]
this seems fixed on v1.7.5006  ? when running the game 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/d839220c-48ea-45d6-ab4b-de3559b21013)

the GS dump is broken tho

**Comment by refractionpcsx2** [comment]
> this seems fixed on v1.7.5006 ? when running the game ![image](https://user-images.githubusercontent.com/17685135/267792579-d839220c-48ea-45d6-ab4b-de3559b21013.png)
> 
> the GS dump is broken tho

Did you check upscaling as well?

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/ea589bf7-efe3-42cb-a58b-9ed603c00c6d)
looks fine at 4x upscaling

**Comment by refractionpcsx2** [comment]
Cool, considering it done then
