### ISSUE TITLE
[BUG]: My controller isn't working (Ubuntu)

### ISSUE THREAD

**Issue by Omega469** [PCSX2/pcsx2#5095]
### Describe the Bug

So I downloaded Ubuntu recently and I tried downloading some emulators and my controller worked with all of them except PCSX2. It recognizes that it's connected and the rumble works, but when I try to configure it, it doesn't change the keys at all.
![image](https://user-images.githubusercontent.com/95447298/144504971-24fc4bfa-5cf1-4465-9a6a-d340d37e0584.png)
![image](https://user-images.githubusercontent.com/95447298/144505027-7537a566-571e-4099-adfd-d443d3f60380.png)
I'm using a third party controller from acme

### Reproduction Steps

I don't know how to reproduce this problem because I just connected the controller and it worked on other emulators, but not on pcsx2

### PCSX2 Revision

1.7.0-o

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 21.10

### CPU

Intel® Core™ i7-3540M CPU @ 3.00GHz

### GPU

NVS 5200M

**Comment by F0bes** [comment]
You ignored the messagebox it shows when you first opened that window.
That window is for controlling _keyboard keys_ as controller inputs.
Your controller should already be mapped and working.

**Comment by Omega469** [comment]
> You ignored the messagebox it shows when you first opened that window
I didn't see any message, but I was talking to someone while opening it's possible that I closed it without thinking and the controller works fine, sorry for the inconvenience.
