### ISSUE TITLE
[BUG]: Blood+ - One Night Kiss (Japan) - HW Renderer renders top left text during dialog without color. 

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5102]
### Describe the Bug

When talking to others ingame during dialog sequences, the top left text is supposed to be colored with blue squares, but instead remains grey in the HW renderer.

### Reproduction Steps

Mash through new game, the opening cutscenes and movies, etc, until you're in gameplay, then talk to anyone.

### Expected Behavior

I expected the text on the top left to display currently during dialog on the hardware renderer.

### PCSX2 Revision

PCSX2 1.7.0-0 - compiled on Dec 5 2021 (daily ppa doesnt show git number)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/50224630/144734081-dd31f667-d3f1-4725-86e2-240300010aa1.png)
![image](https://user-images.githubusercontent.com/50224630/144734090-65602aaf-d230-4d85-b741-28ce0738544f.png)

### Logs & Dumps

[gs_20211204043940.gs.zip](https://github.com/PCSX2/pcsx2/files/7655250/gs_20211204043940.gs.zip)
[gs_20211204043948.gs.zip](https://github.com/PCSX2/pcsx2/files/7655251/gs_20211204043948.gs.zip)

**Comment by lightningterror** [comment]
Needs Full blending, gl only.
