### ISSUE TITLE
[BUG]: Gunparade Orchestra: Midori no Shou: Ookami to Kare no Shounen & Shiro no Shou: Aomori Penguin Densetsu - HW renderer results in flashing background during dialog

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5104]
### Describe the Bug

On these two gunparade games, the HW renderer causes the background to flash whenever you are engaged in dialog. For some reason, the third game, Ao no Shou: Hikari no Umi kara Tegami o Okuri masu, does not suffer from this issue. 

### Reproduction Steps

Mash through the new game setup (Midori requires you to say no to importing your Shiro save file if you don't have a Shiro save file) and through the opening movies, then talk to anyone once character models are visible onscreen (the game will likely do this for you anyways).

### Expected Behavior

I expected the background not to flash during dialog.

### PCSX2 Revision

PCSX2 1.7.0-0 - compiled on Dec 5 2021 (daily ppa doesnt show git number)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### Logs & Dumps

[gs_20211205022905.gs.zip](https://github.com/PCSX2/pcsx2/files/7655431/gs_20211205022905.gs.zip)

**Comment by refractionpcsx2** [comment]
Disable Safe Features seems to stop the flashing, though I haven't looked in to why yet. Just posting this as I was looking at briefly it in passing.

**Comment by Mrlinkwii** [comment]
seems fine as of v1.7.4866

![image](https://github.com/PCSX2/pcsx2/assets/17685135/8a3c9340-e400-46f0-a026-0e10350a07da)


@HeroponRikiBestest  can you double check :)

**Comment by lightningterror** [comment]
Dump seems fine.
