### ISSUE TITLE
[BUG]: Kenran Butou Sai: The Mars Daybreak - HW Renderer has large amounts of graphical corruption, missing shadows

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5105]
### Describe the Bug

On the HW renderer, there are large amounts of graphical corruption and missing shadows present throughout the game.

### Reproduction Steps

Mash through the character creation and intro.

### Expected Behavior

I expected not to see the mentioned graphical issues on the hardware renderer.

### PCSX2 Revision

PCSX2 1.7.0-0 - compiled on Dec 5 2021 (daily ppa doesnt show git number)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Window Screenshots
SW renderer
![gs_20211205004810](https://user-images.githubusercontent.com/50224630/144749944-5d27bebb-29a0-4030-9073-ea8bfaec98f3.png)
HW renderer
![gs_20211205004805](https://user-images.githubusercontent.com/50224630/144749947-c50d4340-a9cf-44b5-a301-101c018409a8.png)

### Logs & Dumps
SW renderer
[gs_20211205004810.gs.zip](https://github.com/PCSX2/pcsx2/files/7656024/gs_20211205004810.gs.zip)
HW renderer
[gs_20211205004805.gs.zip](https://github.com/PCSX2/pcsx2/files/7656023/gs_20211205004805.gs.zip)

**Comment by lightningterror** [comment]
Fixed in recent dev builds, maybe someone can track down which build fixed it for the report.
