### ISSUE TITLE
[BUG]: Biohazard Outbreak - Sync XGKICK causing SPS/missing graphics.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5107]
### Describe the Bug

I have the feeling my bug reports starts to feel like an horror show worse than Amityville at this point, you think it's over, but nope it's not, it's only the beginning ^^.

Yup, I found the only game in the world that is still bad with syncXGKICK, this time the price is given to "Biohazard Outbreak" which *still* doesn't like syncXGKICK.

And this time booth microVU and the interpreters are bad, I told you, horror show it is.

### Reproduction Steps

Load the blockdump and the savestate with the latest build.

### Expected Behavior

The game should not display any kind of SPS like it does with instant XGKICK.

### PCSX2 Revision

pcsx2-v1.7.2101-windows-x86

### Operating System

Windows 11

### CPU

I9 9900k

### GPU

RTX 3070

### Emulation Settings

SyncXGKICK on for the testing. InstantVU1 on or off doesn't matter.

### GS Window Screenshots

The bug in action:

Instant XGKICK:
![2](https://user-images.githubusercontent.com/90222976/144764078-6c9663f3-95f9-4b42-bc6a-2e54ac8c3ba4.png)

SyncXGKICK:
![Capture d’écran 2021-12-05 220314](https://user-images.githubusercontent.com/90222976/144764084-6ff6f62a-16f4-4ccb-95d3-fe11687c0c7e.png)

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1jBHnBuf_gNh0zjwnB9tw7dsXQkedchII/view?usp=sharing

**Comment by refractionpcsx2** [comment]
> And this time booth microVU and the interpreters are bad

It's bad on interpreters too because the interpreters are bad on this game, regardless of XGKick setting

**Comment by gilderoylockhart01** [comment]
Interesting. I wonder what the devs cooked up with the VU1 this time.

**Comment by refractionpcsx2** [comment]
Not sure, I'll take a look, get microVU1 working with sync at least. probably some situation I haven't considered.
