### ISSUE TITLE
GSdx: mesa separate shader object support

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#511]
Currently if separate shader object is force enabled, only a small corner of the screen is drawn.

I will try to generate a trace to reduce the debug scope.

**Comment by gregory38** [comment]
Potentially not a PCS2 bug but I want to give it a look.

**Comment by gregory38** [comment]
Actually just found by chance a report on Mesa.
https://bugs.freedesktop.org/show_bug.cgi?id=79783

**Comment by gregory38** [comment]
I need to reenable the code once my patches are merged on Mesa

**Comment by maximu** [comment]
Actually mesa 25-10-2015 returned  for me error 0:86(1): error: the "binding" qualifier only applies to uniform blocks, opaque variables, or arrays thereof when this extension are enabled.

**Comment by gregory38** [comment]
OoO maybe a regression. It used to work a couple of weeks ago (with my 4 pending patches). Which version of mesa exactly?

**Comment by gregory38** [comment]
Could you post the message around the error message so I know which shader is wrong.

**Comment by maximu** [comment]
Mesa 11.1.0-devel (git-a305d59 2015-10-25 wily-oibaf-ppa)

Where is full opengl output file in linux? I enabled Print GL error and GLSL compilation.
Now something strange happens now I am not able to reproduce this line error but partially working now? 
![captura de pantalla de 2015-10-26 12-38-41](https://cloud.githubusercontent.com/assets/1274014/10728027/aa5d705a-7bde-11e5-96e1-732b3674196a.png)

**Comment by gregory38** [comment]
The file is GSdx_opengl_debug.txt but maybe in debug/dev build. Anyway GLSL errors are only printed on terminal.

It isn't important if you don't manage to reproduce it. It could be a temporary regression or linked to the others bugs.
I propose that we wait the integration of my pending patches in Mesa. Normally it will work.

![screenshot - 10262015 - 01 36 51 pm](https://cloud.githubusercontent.com/assets/1569559/10729103/62bcfbcc-7be7-11e5-9d44-3ee7fe198ab4.png)

**Comment by maximu** [comment]
Well hopefully these patches that look great progress  :)

**Comment by gregory38** [comment]
Yes. However it won't improve performance so it isn't that critical. I need to benchmark Nvidia driver to see if there is any impact with this extension.

**Comment by gregory38** [comment]
Patchs integrate into mesa ^^ Separate Shader object can be used on the future Mesa 11.1
