### ISSUE TITLE
[BUG]: regaining focus, slows down emulation

### ISSUE THREAD

**Issue by fantesykikachu** [PCSX2/pcsx2#5111]
### Describe the Bug

When regaining focus, rendering performance drops for about half a second. This is not a hardware issue; as with the regular frame-limiter for me performance drops from 100% to 95% but in turbo mode I drop from 200% to 175%, but still well above 100%. 

Also this happens on all graphics backends including software rendering, also this happens even when both windows are initially visible with no windows overlapping.

### Reproduction Steps

Run a game with PCSX2 in windowed mode, then interact with a different window, then click back on the emulation window and watch the performance counter drop.

### Expected Behavior

Performance shouldn't drop when the frame-limiter is the bottleneck.

### PCSX2 Revision

v1.7.2103

### Operating System

Windows 10 (64bit)

**Comment by Squall-Leonhart** [comment]
more than likely MPO behavior.

**Comment by JordanTheToaster** [comment]
Not an issue with Qt 1.7.3345.
