### ISSUE TITLE
[BUG]: Zero Shikikan Josentoki Ni (Japan) [SLPM-66299] [CRC32-66791693]

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5119]
### Describe the Bug

Half screen in vertical

![gs_20211208154810](https://user-images.githubusercontent.com/7451522/145236795-72b874a7-a2ce-4344-aaa1-ad9deb8bc9ee.png)

Same problem on the game : Georama Sensen Ijou Nashi - Stalingrad e no Michi (Japan) [SLPM-66038] [CRC32-317b272e]

Blockdump 
[dump Zero Shikikan Josentoki Ni (Japan) [SLPM-66299] [CRC32-66791693] (2021-11-08 16-33-38).zip](https://github.com/PCSX2/pcsx2/files/7677160/dump.Zero.Shikikan.Josentoki.Ni.Japan.SLPM-66299.CRC32-66791693.2021-11-08.16-33-38.zip)
: 

### Reproduction Steps

Just launch the game

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by refractionpcsx2** [comment]
Game uses a height of 896 instead of 448.
