### ISSUE TITLE
[BUG]: StarTRain - Your Past Makes Your Future (J) [SLPM-66879] [CRC32-30f93a4a]

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5120]
### Describe the Bug

Stuck at the title with push start but can't go further

![gs_20211207214841](https://user-images.githubusercontent.com/7451522/145239530-e48c6559-ea10-48af-b21e-10812c2c9ef0.png)

### Reproduction Steps

Just launch the game

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by gilderoylockhart01** [comment]
I am pretty sure this is a regression. Please make a blockdump of the game with a savestate in the title screen.

**Comment by prafullpcsx2** [comment]
It seems t work fine for me. Can't reproduce the bug.

**Comment by seta-san** [comment]
Is your start button mapped properly?

**Comment by spacemul** [comment]
seems a problem with my pad with this game, i succeed to play the game now !

**Comment by seta-san** [comment]
> seems a problem with my pad with this game, i succeed to play the game now !

glad to here that. could you make sure you weren't just having the same problem with the start button on the taiko drum game?
