### ISSUE TITLE
[BUG]: Taiko no Tatsujin - Doka! to Oomori Nanadaime (Japan) [SLPS-20486] [CRC32-7e31dd40] 

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5123]
### Describe the Bug

Stuck at title

![gs_20211207220721](https://user-images.githubusercontent.com/7451522/145240123-b7b293b1-8061-4ca2-8df6-0d4aa9b29de8.png)

### Reproduction Steps

Just launch the game

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by seta-san** [comment]
I think this game requires a usb drum. https://youtu.be/78l848FqO7A

**Comment by seta-san** [comment]
okay. this game plays just fine for me.

**Comment by seta-san** [comment]
https://www.youtube.com/watch?v=ApzXPIFaWBc
