### ISSUE TITLE
[BUG]: Some "Jikkyou Powerful Pro Yakyuu" games - 3D rendering issues in certain screen

### ISSUE THREAD

**Issue by Tokman5** [PCSX2/pcsx2#5125]
### Describe the Bug

In ``Jikkyou Powerful Pro Yakyuu 11 Chou Ketteiban``(SLPM-65825) and ``12 Ketteiban``(SLPM-66217), 3D character model rendering is weird in certain screens.
In the baseball game, every 3D models seems to be fine, but when in some 2D screen, the character model is covered with pink almost entirely (See screenshots below).

Both of SW and HW mode have this problem.
Team select screens in ``Jikkyou Powerful Pro Yakyuu 9`` and ``10`` don't have the similar issue.

### Reproduction Steps

Run ``Jikkyou Powerful Pro Yakyuu 11 Chou Ketteiban`` or ``12 Ketteiban``, and go to:

- Team select screen in ``Game`` mode.
- Batting/Pitching form select screen in ``Success`` mode.
- Uniform edit screen in ``Arrange/Edit`` mode.

Maybe ``Jikkyou Powerful Pro Yakyuu 11`` and ``12`` have the same issue.

### Expected Behavior

Rendering correctly.

### PCSX2 Revision

v1.7.2112

### Operating System

Windows 10 (64bit)

### CPU

i7-8700

### GPU

GTX 1070

### GS Settings

Default settings.
Changing mipmapping and blending accuracy setting made nothing.

### Emulation Settings

Preset: 2

### GS Window Screenshots

``Jikkyou Powerful Pro Yakyuu 12 Ketteiban``, SW mode.
Team Select:
![powerpros12](https://user-images.githubusercontent.com/84766523/145353604-8e7a22f9-a677-4d18-bd66-9cde9869984a.png)
 
Team Edit / Uniform Edit:
![powerpros12uniform](https://user-images.githubusercontent.com/84766523/145355912-234e38cc-416b-4f17-9b12-48e643053026.png)

Form Select:
![powerpros12formselect](https://user-images.githubusercontent.com/84766523/145356009-a262aec6-54c1-433d-9882-6a32090eee0c.png)

### Logs & Dumps

GSDumps:
[PowerProsRenderingIssue.zip](https://github.com/PCSX2/pcsx2/files/7683432/PowerProsRenderingIssue.zip)

**Comment by gilderoylockhart01** [comment]
I sugest you try various clamping/rounding values for booth the EE and VUs. If that doesn't work you can try each hacks one by one to see what happens. By the looks of it this (in BIG quotes) """sounds like an XGkick bug""".

**Comment by Tokman5** [comment]
I tried all clamping/rounding modes of EE and VU, recompiler/interpreter mode of EE, IOP and VU, and every gamefix. However none of them fix this problem.

**Comment by gilderoylockhart01** [comment]
Olay, then I would like you to male a blocldump of the game + a savestate in the area where the glitj happens.

**Comment by Tokman5** [comment]
[Pawa12KetteiBlockDumpAndSState.zip](https://github.com/PCSX2/pcsx2/files/7710024/Pawa12KetteiBlockDumpAndSState.zip)
v1.7.0-2112(github)
No save data is needed
Going to team select screen

**Comment by refractionpcsx2** [comment]
Did this ever work?

**Comment by Tokman5** [comment]
I tried in v1.0.0 and the same result came up.

**Comment by refractionpcsx2** [comment]
I was thinking more recently than that, like 1.6 or 1.4 :P

**Comment by Tokman5** [comment]
in v1.6.0, the same result.

**Comment by refractionpcsx2** [comment]
OK thanks :) Just wanted to be sure it wasn't a new problem
