### ISSUE TITLE
[Feature Request]: GSdump UI helper

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5129]
### Description

Add an option/toggle for single big multiframe or multiple gs frames, or how long you want it to dump for, etc. 

### Reason

At the moment, the Linux builds of PCSX2 handle this feature differently, in a way that linux users are unable to perform longer multi frame dumps. This feature would hopefully help achieve feature parity between OSes.

### Examples

I don't know of any other software that has functionality similar to GSdumps to begin with.

**Comment by Mrlinkwii** [comment]
QT atm  has an UI  option for single frame GS dumps  and  the multi-frame gsdump  hotkey can also be changed
