### ISSUE TITLE
Ys - The Ark of Napishtim NTSC-U

### ISSUE THREAD

**Issue by IceLancerSR** [PCSX2/pcsx2#513]
Sound Error>>>>>Unknown sound command: 0x360
###  Voice Total Num = 4172   ###

Sound Error>>>>>Unknown sound command: 0x360
###  Voice Total Num = 4172   ###

Sound Error>>>>>Unknown sound command: 0x360
###  Voice Total Num = 4216   ###

kssBGM_Pause( 1 )

kssBGM_Resume( 3 )

kssBGM_Pause( 1 )

kssBGM_Resume( 3 )
>>>>>Unknown spu2 inter! core: 3

Resulting in emulator loop and black screen.
Always happens during talk to npc's but not every time.
Requires few npc talk's

Using SPU2-X PortAudio

*** Device 11: 'Speakers (ASUS Xonar DG Audio)' (Windows WDM-KS) (selected)
Win7x64 Intel 2500k

Japan audio+english subtitles selected as default game choice.

--
P.S
Not using any kind of cheats or hacks Except : (GameDB) Enabled Gamefix: EETimingHack
v1.3.1-187-g0ab0c6c 	Gregory Hainaut 	2015-04-27 19:30:03

**Comment by ramapcsx2** [comment]
First disable that timing hack. It could affect this.
We worked on this problem before and I thought we had it fixed.
The "Unknown sound command: 0x360" doesn't have to be a real issue but "Unknown spu2 inter! core: 3" is new and sounds like an actual problem.

**Comment by IceLancerSR** [comment]
It doesn't happen with xaudio.
But it does happen with PortAudio

**Comment by ramapcsx2** [comment]
This is a core emulation issue so the output module should have no effect on it.
It's likely that it just randomly worked better on xaudio.

What we need here is a test on real hardware, see which errors are normal and which are our fault.

**Comment by bositman** [comment]
I tested this without the EE timing hack (anyone knows why that is on?), portaudio and both english and japanese voices (took me forever to find out you needed 'cheats' to switch to jap voices wtf...). Talked to everyone in the first town twice, no crash and everything played out fine. Maybe the latest portaudio update we did fixed this somehow.  I also tested the case from here and it worked fine: http://forums.pcsx2.net/Thread-Ys-ark-of-napishtim?pid=132206#pid132206
If this occurs only at a specific point in the game, please provide a memory card, Closing this for now.
