### ISSUE TITLE
[Bug]: Silent hill shattered memories - flashlight broken

### ISSUE THREAD

**Issue by spa100** [PCSX2/pcsx2#5131]
### Description

Whatever was done with v1.7.2111 finally fixed the flashlight in silent hill shattered memories but when I tried it in 1.7.2113 it was broken again. I'm not sure what was done but it did fix the flashlight maybe you might want to look into it. 

### Reason

It makes the game playable at high resolutions. 

### Examples

![gs_20211210004508](https://user-images.githubusercontent.com/95900899/145523572-04105eea-5705-401b-af08-677daf3411cc.png)

**Comment by MrCK1** [comment]
@spa100 Can you fill in the rest of the issue with your PC info and settings used please. 

Also, would be helpful for you to add a GS dump (hold shift + F8 and upload the file from snaps folder)

**Comment by refractionpcsx2** [comment]
Shattered memories has been fixed for a while now, can you show how it's broken as well?

**Comment by refractionpcsx2** [comment]
I just tried it, it looks fine like the picture above? I don't see the issue?

**Comment by spa100** [comment]
Sorry I meant to say that it works in software but in dx11 it’s broken

**Comment by refractionpcsx2** [comment]
well, it's fixed now

**Comment by spa100** [comment]
Thank you. 👍
