### ISSUE TITLE
[BUG]: Happy! Happy!! Boarders in Hokkaidou Rusutsu Resort (Japan) SLPS-20050

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5136]
### Describe the Bug

graphic glitch ingame

i try Clamping extra and extra + => not work
seems VU1 interpreter fix it but 6 fps

![gs_20211210155628](https://user-images.githubusercontent.com/7451522/145597442-11c4bcfa-c762-4724-8e64-5081ae616a00.png)

![gs_20211210155634](https://user-images.githubusercontent.com/7451522/145597496-1d132fa2-9c2b-4acd-9fd8-5db2e10a222e.png)

### Reproduction Steps

select the ski lift

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

### Logs & Dumps

Blockdump : https://drive.google.com/file/d/1UvdvxE0xAedYxAXJvWkLe4slzo7-g12K/view?usp=sharing

**Comment by HeroponRikiBestest** [comment]
@spacemul You forgot to make the link public, it asks me for permission

**Comment by refractionpcsx2** [comment]
Not a bug, disable the mVU Flag Hack speedhack.
