### ISSUE TITLE
[BUG]: Netchuu! Pro Yakyuu 2003 - Aki no Nighter Matsuri (Japan) SLPS-20322

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5144]
### Describe the Bug

Freeze before ingame play, then if I try SW mode, black screen

Blockdump : https://1fichier.com/?wqopvggkbe165loxf9ur

### Reproduction Steps

Need to launch a preseason, choose team, validate all 

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by prafullpcsx2** [comment]
Can you test https://github.com/PCSX2/pcsx2/pull/5145 with automatic gamefixes enabled to confirm it works fine?

**Comment by gilderoylockhart01** [comment]
Absolutely no gamefix helps with this game now?

**Comment by HeroponRikiBestest** [comment]
It appears to work now.
![image](https://user-images.githubusercontent.com/50224630/145720846-31ed11e8-687b-419a-a4e1-600567006f80.png)
![image](https://user-images.githubusercontent.com/50224630/145720848-fb9d7208-b757-4f28-94c6-930d62aeb37a.png)

**Comment by gilderoylockhart01** [comment]
I would like if you can capture a blockdump of the game with a savestate before going ingame please.

**Comment by HeroponRikiBestest** [comment]
I can do the blockdump, but, won't any savestate I make not work for you?

**Comment by spacemul** [comment]
nice work, i tried and the game work good
