### ISSUE TITLE
[BUG]: PCSX2 now crashes on linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#5149]
### Describe the Bug

In linux, starting any game now results in:

![pic](https://user-images.githubusercontent.com/12475371/145729919-655766dd-f6f5-470b-8c3a-6bc23944a25a.png)

Information not asked below:
* Compiler: gcc-11.1.0
* Bad commit: 13b19b35c030d27a568fda51414bbe624f528111
* Last good commit: 6beac267279cdd1b7a4ee808cfefd3551bcf464d

### Reproduction Steps

1. Compile pcsx2
2. Copy the pcsx2 binary to the desired path (Note: a "resources" subdirectory must now be created and contain GameIndex.yaml or pcsx2 will complain). 
3. Start PCSX2, start any game (using SW or HW, speedhacks on or off), observe immediate crash.

### Expected Behavior

Games should run normally.

### PCSX2 Revision

1.7.2121 (See above for specific commit)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2 / kernel 5.13

### CPU

Intel i7-10870H

### GPU

Nvidia 3070 / driver 470.86

### Logs & Dumps

Can provide a bisect if needed.  As noted above, this issue occurred only a few commits from the last good commit.

**Comment by refractionpcsx2** [comment]
I doubt a gamedb commit is causing a crash, a more in depth bisect would be good, possibly if you could show the crash with symbols may also help.

**Comment by arcum42** [comment]
The resources subdirectory should have considerably more than GameIndex.yaml in it...

**Comment by Shoegzer** [comment]
@refractionpcsx2 Yeah I suspected as much.  I can get a bisect going here.
@arcum42 Thanks, what other files should be copied in there?

**Comment by Shoegzer** [comment]
Update: When I copied the entire `bin/resources` directory to the directory containing the binary, PCSX2 no longer crashes.  I suspect the issue/crash was related to an inability to find a path to shaders but either way, it's fixed now.

Thanks both of you for your help.

**Comment by tellowkrinkle** [comment]
The main issue was that GS was noticing missing shaders and failing to init
We do a terrible job of handling when GS fails to init and crash instead of giving a more obvious error

If you want to make an issue for that, that might be a good idea

**Comment by tellowkrinkle** [comment]
For future reference, we recommend installing PCSX2 with `make install` on Linux instead of manually copying things around.  If you have a specific place you want it to end up, specify it to cmake with `-DCMAKE_INSTALL_PREFIX=`

**Comment by Shoegzer** [comment]
@tellowkrinkle You're right, better handling is always a good idea.  Done, and thanks.

Also, I sometimes do use `-DCMAKE_INSTALL_PREFIX` for tailored installs where supported, just hadn't done that yet here.  In certain cases where projects are subject to frequent changes, it's nice to force direct involvement / observation over project files, but you're right that such a thing eases the process.  Thanks for the reminder.
