### ISSUE TITLE
[Question] Should we not export the Issues from old Issue Tracker here?

### ISSUE THREAD

**Issue by trader5896** [PCSX2/pcsx2#515]
Hi,

Should we not export the Issues from old Issue Tracker here from Google SVN. (https://code.google.com/p/pcsx2/issues/list)

Because the informations we collected will be lost, if SVN will be closed perhaps, we don't know Google intentions.

Bositman could use the export function and the devolopers could delete the "backburner" Issues.

But I could export it manually without problems, if this should not be possible.

Therefore: Any ideas, what we should do?

**Comment by trader5896** [comment]
By the way, If I should do, I will copy and paste it here and attach a PDF of the old website with Chrome printed to PDF.

**Comment by mirhl** [comment]
Are you going to export even closed issues?

I mean, just asking. Some may have still relevant information for posterity

**Comment by trader5896** [comment]
I'm sorry that I write so lately, because I had problems with signing in. Whatever : 
I will not add the closed issues to here, because this will not help improving this project. What I'll do is to help the developers to have bright sight of project and the bugs and the improvements which can be made. 

The next step after this will be to add the games in the online gamedatabase, which don't work. 

The step after this to add all games Games, which just work with the local gamedatabase or by Crc based, because if they get fixed, the emulation will work more better. 

Last and least should is to add all todos which you can find if you search in the source code. The issues will grow to about 600-700, but this will be all. If one issue gets fixed, this will most probably fix 50-60 games.

**Comment by trader5896** [comment]
There are a lot of things, which the forum member and long year developer know like the 2D problems realeated to Onimusha 4 - Dawn of Dreams, but mostly other programmer don't know. But there are certain things, if they get fixed, this will improve things for more games...

**Comment by ssakash** [comment]
How are you going to export the issues ? Manually ?

**Comment by trader5896** [comment]
Yes, unless Bositman is not able to do, I'll slowly start.

**Comment by trader5896** [comment]
It will look like this:

https://github.com/PCSX2/pcsx2/issues/521

**Comment by trader5896** [comment]
And here the first problem starts: 

Is this absolutly legal, because the pdf printed site is property SVN? And what about the emails?

Could somebody tell, if this is allowed?

**Comment by mirhl** [comment]
I mean: it's not only the issue header itself that's important, but even all the rest of the discussion. That's why every one seemed important to me. 

If you are going to export them manually though, I understand the difficulties and I won't have anything else to say. 

Still, aren't automatic exporters working? https://code.google.com/p/support-tools/wiki/IssueExporterTool
https://code.google.com/export-to-github/

**Comment by trader5896** [comment]
To be honest, I don't know if this is possible to export, but I don't think, that you can export your issues, because the guys of Dolphin Emu didn't do this for unknown reason, perhaps this is the reason.

I will export them manually, which is not that bad, because it's just opening 350 tabs and then just CTRL+Shift....and so on.:D

But this might be illegal, therefore I need to know, if this allowed?

But we should contact Bositman, because he manages all these things. Afterwards delete all would be cool from SVN.

I mean, if the Devs have a overall overview of PCSX2 Issues, this might give them sight, what problems are worst and fixing them, will most oftenly help further improvement.

**Comment by trader5896** [comment]
@ssakash

I see that you own a PCSX2 directory too. And there are another directorys if you search in Github for "PCSX2" . May I ask, what is that? Isn't there just one PCSX2?

And what does the PCSX2 Beta stands for? 
I thought, that this is already Beta?

**Comment by mirhl** [comment]
**If you are migrating** a project **to** Bitbucket or **GitHub, the Issue Exporter tool can help you migrate your Google Code issue tracker items** to your project’s new home. 

 Wlcome to the Google Code project exporter. This tool will export a project's source repository, its **issues**, and its wikis to GitHub. 

Perhaps there's a catch, but for how wording stands, it seems pretty clear what these do

**Comment by trader5896** [comment]
Yes these words are clear for sure, but I do t get it, why PCSX2 hasn't done it so far, because these tools were made before svn would close. Therefore I'm awaiting the devs to give an answer, before doing something...

**Comment by trader5896** [comment]
@mirhl 
It would be great, if the devs could export it to Github. But this would not be all, there are about 100 Bugs written in the wiki or forum, which are known to longyear members, but instead of being in the forum, this should all be in Issuelist I think.

From the Pcsx2 Projects Todo's (which you can find in the commentary with searching for "To-do or To do" and the Gamefixes in the local database and GSDX's CRC Database we will find a few more probably.

**Comment by mirhl** [comment]
Ok, the second tool is going to have [some problems](https://code.google.com/p/support-tools/wiki/GitHubExporterFAQ#Are_all_projects_available_to_be_exported_to_GitHub_?) with pcsx2, given there are more than 1000 issues. 

Still, as you can see there's the other tool that's linked and that should work (and page seems up to date if you look at the top)

**Comment by trader5896** [comment]
@mirhl 
Can you contact the devs to that? Because here in Github there's no option to write a PM.

**Comment by ssakash** [comment]
@trader5896 
It's one of my forks on pcsx2 for implementation of some stuffs. it's not officialy related to the PCSX2 project. by the way, you could also contact the devs on either the IRC channel (or) on the forums.

**Comment by trader5896** [comment]
@ssakash

In my opinion the best thing is, if all project unite

**Comment by trader5896** [comment]
Sorry, I've pushed the button but I'd didn't want to so. 

Whatever in one Union you could reach more in the emulation, if you add a little bit and the others then being apart. 

Whatever, it would be cool if the developers could look for this exportion thing.

**Comment by ssakash** [comment]
I still haven't completed the implementations then, it's pointless to merge it. By the way, did you try contacting the devs ?

**Comment by trader5896** [comment]
No I didn't but I'll try...

**Comment by ssakash** [comment]
the issue has been notified in the bug squad forums. some devs might notice it, it would be better if you could wait for the devs response on exporting the issues. :)

**Comment by trader5896** [comment]
I don't know this Bug Squad. But I tried Irc of Pcsx2, but it didn't work. The devs should do this, this is true

**Comment by trader5896** [comment]
I've seen the Bug squad team, but the way they do isn't very good perhaps. 

For example it's good to first add the bugs to Github with the export tool. 

But the point, which I think will bring efficiency to this project is to add a Github Thread for the same bug. 

Maybe you have noticed, that Eyetoy games don't work, because the cam isn't emulated till now and there's no plugin for that. 

I would open a Thread with [Camera Plugin]  within are all of these games which should be around 8-16 games which require this. After that if you solve this problem for just one game, this will solve the whole problem. 


Whatever I download the latest Pcsx2 Master Folder and try to open a thread on Github with games, which don't work without patches, then I check pcsx2 wikia too... 

The export of the old bugs from Github should be done by bug squad team or the export tool. 

But the bug squad team is good. 

:d

**Comment by ssakash** [comment]
The old issues could be exported by bositman to github using the export tool. The bug squad is in charge for exporting the bug reports from the forum to github.

**Comment by mirhl** [comment]
@bositman 

And +1 for the eyetoy thing

**Comment by trader5896** [comment]
Okay I'm doing now the Game index.dbf first. Then I'll look for the todos in Source which I'm loading. After that I'm searching for the gsdx crc bugs. 

Bug Squad will solve the forum. 

Bositman will export the old issues here. 

Then this will solved hopefully...

**Comment by trader5896** [comment]
I'll look for For another glitch of game from which I have a dvd, if it will work with pcsx2 actually and post it...

**Comment by trader5896** [comment]
I'll look today, if I can manage it, but I'll try to list from PCSX2 wikia and Gameindex.dbf, which don't work.

**Comment by trader5896** [comment]
Okay 
@ssakash and all members, it was a very good time. I wanted to help you, but I realised, that I now have not this time anymore. I really doubt, that I will have time in future. 

But here is the todo list.

**Comment by trader5896** [comment]
Export the Patches entries from Game index.dbf to here. 
Export the Pcsx2 wikias broken games to here. 
Make the compatibility list and Pcsx2 up to date. 

Whatever. I wish a good time. This project is one of the best.

**Comment by ssakash** [comment]
Thanks for your contributions, we will be sure to keep the pcsx2 wiki and the compatibility list in sync. :)
