### ISSUE TITLE
[BUG]: Armored Core 3: Abnormally long blackscren after some loading screens, read timeout in log

### ISSUE THREAD

**Issue by TransparentBlue** [PCSX2/pcsx2#5155]
### Describe the Bug

Whenever you load in the Arena level (potentially others), after the loading screen there is a very long black screen and after a while the game resumes as normal.
The log contains " Read Time Out 15000(msec) " whenever this occurs

### Reproduction Steps

Go to Arena menu
Start a fight and select Arena as the level

### Expected Behavior

Gameplay should happen almost immediately after the loading screen animation is done.

### PCSX2 Revision

1.7.2128

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

GTX 1080ti w/ 472.12 drivers

### GS Settings

None

### Emulation Settings

Safe Preset

Additionally i did test #5142 which doesn't change anything with this specific issue.

**Comment by refractionpcsx2** [comment]
Can you try https://github.com/PCSX2/pcsx2/pull/5142

**Comment by TransparentBlue** [comment]
Already did and it didn't affect that issue.

**Comment by refractionpcsx2** [comment]
Ugh this is one of those games with a really early CDVD library, when was this released? 2002? Surprising, but yeah Star Ocean 3 has a similar problem with the CDVD driver just crapping itself for no reason, Gonna have to do a bunch of hardware tests to see how to handle this properly.

**Comment by TransparentBlue** [comment]
After a bit more testing, I can say it only specifically affects Arena and Special Arena, regardless of what location you chose and the standalone expansion for it is entirely unaffected seemingly.
It also seems like 1.6 didn't have that issue, I haven't narrowed down what revision broke it exactly yet though.
