### ISSUE TITLE
[Feature Request]: Better GS exception handling

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#5156]
### Description

In cases where GS fails to init, PCSX2 unceremoniously crashes rather than throwing a proper exception to the user.  This can be seen in recent issue reports such as #5149.

### Reason

Proper exception handling in cases such as these should not only reduce confusion but also lead to better issue reporting.

### Examples

A popup exception with more useful and formatted information should suffice.

**Comment by lightningterror** [comment]
Did a quick test and it seems that only D3D12 crashes now when shaders are missing.

**Comment by stenzek** [comment]
Has been better for some time now, most known failure points will raise a specific error message.
