### ISSUE TITLE
[BUG]: Issues with Mesa

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#5160]
### Describe the Bug

When PCSX2 is compiled on release and only release. And the user is running any AMD HW for sure but possibly intel-based HW. The program will spontaneously crash if the user attempts to move the window or adjust the window size. It seems entirely dependant on the game running and whether the game is in a certain scene. Going full screen can cause this issue but doesn't seem to all of the time. Moving and adjusting the game window is the most volatile cause of this issue. 

This could be related to: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5286

This is known now to happen across distros, Arch / Manjaro and Ubuntu / Mint

### Reproduction Steps

With mesa, drivers enabled on AMD or intel and pcsx2 compiled as a release build. Play Jak and Daxter (On the title screen animation), rumble racing (if you wait into the first demo, save state, load state, then mess with the window is a guaranteed crash) or the BIOS even can cause this issue and attempt to move the window to see the game crash

### Expected Behavior

The window should move or change size with little issues.

### PCSX2 Revision

Most of the recent builds seem to have the issue

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch, Ubuntu

**Comment by Mrlinkwii** [comment]
it must be on specific hardware and mesa versions :thinking:  , i havent had any crashes   , tho im on a low end machine and not latest mesa  (Mesa 21.0.3)

**Comment by kenshen112** [comment]
Were you playing those specific games?

**Comment by Mrlinkwii** [comment]
i checked by booting the BIOS and moving the window   as you described , i assume  it may be on specific hardware and mesa versions

**Comment by HeroponRikiBestest** [comment]
@Mrlinkwii I'd try all of them, I don't get the BIOS one but I do get the Rumble Racing one.

**Comment by Elserjo** [comment]
I use PCSX2 1.7.0-20210527160718 and can confirm this problem. For example, i set on OpenGL render, launch bios, then switch to another window and it crashes. When i switch to software render it run without any crashes. 

My videocard: Radeon RX6700.

**Comment by HeroponRikiBestest** [comment]
I run the latest master as well, and I can confirm the problem with Rumble Racing, CPU/iGPU is AMD Ryzen 7 PRO 4750U with Radeon Graphics.

**Comment by F0bes** [comment]
> This could be related to: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5286

(Note: I created said issue) 
I was using Mesa 21.1.6 at the time of the problem (~4 months ago now?) and sometime between then and now (Mesa 21.2.5) the issue is resolved and I can no longer reproduce the crash.
