### ISSUE TITLE
[BUG]: Titeuf Mega-compet' (France) - sles-52711 - 958E5086

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5167]
### Describe the Bug

Graphics issues ingame

![gs_20211215145748](https://user-images.githubusercontent.com/7451522/146221998-8f7a876e-d691-4aa6-87b2-ef9c9db709ca.png)

### Reproduction Steps

Just launch the game, speak then go in the school

### PCSX2 Revision

1.7.2120

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by refractionpcsx2** [comment]
Just gonna go ahead and mark this as a PATH3 masking problem, cos it probably is...
