### ISSUE TITLE
[BUG]: Top Trumps Adventures Vol. 2 - Dogs & Dinosaurs (Europe) - sles-54635 - BF31747C

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5168]
### Describe the Bug

Freeze just before go ingame

Freeze on the screen : 
![capture_15122021_171601](https://user-images.githubusercontent.com/7451522/146223602-3c90ff9d-1f8b-4e6c-a456-04066220d84d.png)

### Reproduction Steps

Just launch the game, start a character, 3 types of cards then freeze

### PCSX2 Revision

1.7.2120

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by gilderoylockhart01** [comment]
Please make a blocldump of the game until it frezze so we can see what is wrong with it.

**Comment by refractionpcsx2** [comment]
Interestingly, the game "works" on dobiestation. I say works, it plays the video and the game proceeds, but it does corrupt
