### ISSUE TITLE
"Feature" Request - Don't let timestretched audio be >100% speed while emulation is <=100% speed

### ISSUE THREAD

**Issue by yorkiesandskittles** [PCSX2/pcsx2#517]
If the extremely squashed title left you confused, then I should probably explain:

What I mean is that when the FPS briefly dips to say, 48 for a split-second and then immediately goes back to 60, you may hear the audio playing more slowly during the dip as it should, but when it climbs to 60, the audio plays extremely fast for a very short time. This happens very often, and so it can become quite distracting, irritating even. My suggestion is to have the audio gradually speed up until 100% emulation speed is reached, where it will return to 100% audio speed.

Hopefully this makes sense.

**Comment by avih** [comment]
It can't "gradually speed up" without using a bigger buffer and adding more latency, and you control this parameter using the "latency" slider of the time stretcher.

The solution for this specific problem is to increase the time stretcher latency or to use async mix (i.e. don't use time stretcher).

The time stretcher latency defines how big the buffer is and determines how quickly the algorithm must react to speed changes before it starts losing/dropping audio packets. If the latency is low, the algorithm has nothing "to play with" and must react very quickly by stretching/shrinking very fast. But if you increase the latency then it has more time and can adapt to speed changed in less extreme way.

It already works the best we can make it work - which already includes behaving the best we could make it behave in extreme and/or quick speed changes.

So your options are:
1. Get a faster computer which will be better at keeping the speed exactly at 60.
2. Increase the time stretcher latency - but this will add bigger audio delay.
3. Don't use the time stretcher and instead use async-mix. On some games it's very good.
4. Look at the source code and try to improve it.

**Comment by karasuhebi** [comment]
Thanks for describing what the time stretch latency slider does @avih. I was always curious about that but never looked into it.
