### ISSUE TITLE
[BUG]: GuitarFreaks & DrumMania V3 (SLPM-66822) - HW renderer graphical glitches

### ISSUE THREAD

**Issue by 987123879113** [PCSX2/pcsx2#5177]
### Describe the Bug

The hardware renderer (both D3D11 and OGL) causes videos to glitch outside of the video frame. Software renderer works as expected.

![gs_20211217015748](https://user-images.githubusercontent.com/63495610/146416080-8093acac-fb57-4cde-8ba2-18a8aea847c2.png)

This glitch affects the following games:
- SLPM-66313 GuitarFreaksV ＆ DrumManiaV (CRC: D583F68C)
- SLPM-66575 GuitarFreaksV2 ＆ DrumManiaV2 (CRC: 93E22F7E)
- SLPM-66822 GuitarFreaksV3 ＆ DrumManiaV3 (CRC: C846235F)
- SLPM-66484 GuitarFreaks & DrumMania MASTERPIECE SILVER (CRC: 7E3C2B9C)
- SLPM-66686 GuitarFreaks & DrumMania MASTERPIECE GOLD (CRC: 50091A06)

The degree to which the graphics glitch out depends on the game. The above listed games all share the same game engine so I am grouping this all as one issue unless asked to make separate issues.

### Reproduction Steps

1. Select Guitar Freaks mode
2. Start any song
3. The area surrounding the video frame should glitch out when in any hardware renderer mode

### Expected Behavior

Graphics to not glitch around video frame as shown in software renderer mode:
![gs_20211217015756](https://user-images.githubusercontent.com/63495610/146416052-42715bb5-2a22-4bbb-9db5-f14c850ba8af.png)

### PCSX2 Revision

v1.7.2137

### Operating System

Windows 11

### CPU

AMD Ryzen 5 3600

### GPU

NVIDIA GeForce RTX 2060

### Logs & Dumps

[SLPM-66822 - (C846235F).zip](https://github.com/PCSX2/pcsx2/files/7729178/SLPM-66822.-.C846235F.zip)

**Comment by prafullpcsx2** [comment]
These games were broken in https://github.com/PCSX2/pcsx2/commit/7bb9a3cc2555d3bcaf4120d2c249e1a0448db3f3

Pretty big update so it may be hard to track down and fix.

**Comment by Mrlinkwii** [comment]
can this be rechecked  if possible on latest nightly

**Comment by 987123879113** [comment]
@Mrlinkwii I gave it a go with DX11, DX12, Vulkan, OpenGL and it is looking fine in all of those using [v1.7.4331](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4331) so I will close this issue now. Thank you!

**Comment by 987123879113** [comment]
Some more information for the devs in case it's of any interest: I did some testing with nightlys to try to pinpoint when this was fixed exactly.

Bug happens in [v1.7.4244](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4244) and appears to have been fixed by [v1.7.4245](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4245) which was [GS-HW: Improvements to tex in rt + invalidation #8289](https://github.com/PCSX2/pcsx2/pull/8289).

**Comment by refractionpcsx2** [comment]
awesome :) Thanks for testing. I have a feeling I know what line fixed it, as we were forcing the invalidation to happen on memory pages, but that wasn't always the case, and there's no real advantage to this in hardware mode, so it was over-invalidating, making thin or misaligned objects get surrounded by black.
