### ISSUE TITLE
Linux Multilib build fails

### ISSUE THREAD

**Issue by kaminary** [PCSX2/pcsx2#518]
Tyring to compile on linux is failing.
Details:
Architecture: AMD64
Distro: Debian 8 Jessie
Compiler tryed: clang and GCC
Output of clang try: http://pastebin.com/NN806kHr

Maybe I'm missing any dependency?

**Comment by gregory38** [comment]
Could you post the GCC log first. The easy case first ;)

**Comment by kaminary** [comment]
OK, I was missing gcc-multilib package.
Installed it and the problem was solved.
I have found many warnings during compile time, should I report them?

**Comment by gregory38** [comment]
No thanks. I can see the warning on my computer.
