### ISSUE TITLE
[BUG]: Ultimate Spider-Man Limited Edition - Spider-Man's eyes are either blue or yellow instead of white

### ISSUE THREAD

**Issue by GoodWall533** [PCSX2/pcsx2#5186]
### Describe the Bug

Spider-man's eyes keeps switching color between blue or yellow
![2021-11-03_2](https://user-images.githubusercontent.com/73701483/146688662-0d7fd23c-fc29-4bf9-8b12-8ebbc2249a46.png)
![2021-12-19 (5)](https://user-images.githubusercontent.com/73701483/146688718-fc40595c-fef9-4291-b15e-50127851e8b3.png)

### Reproduction Steps

This happens anytime you play as Spider-Man in any mission with him or in free-roam and his eyes will constantly switch between blue and yellow. This happens in both software mode and hardware mode.

### Expected Behavior

As you can also see beside his health bar, his eyes are supposed to be white as shown in this other image:
![8979465341321](https://user-images.githubusercontent.com/73701483/146688838-d2beb9e8-c611-4b22-8447-13a5c7ea38c6.jpg)

### PCSX2 Revision

PCSX2 Nightly - v1.7.2144

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3500x

### GPU

GTX 750Ti

### GS Settings

![2021-12-19 (8)](https://user-images.githubusercontent.com/73701483/146689081-46d182ef-5c92-4444-bd8e-6c0a537a8bac.png)

### Emulation Settings

![2021-12-19 (9)](https://user-images.githubusercontent.com/73701483/146689090-ada55f54-fe71-4b4b-8668-d282d07e406c.png)

### GS Window Screenshots

![2021-12-19 (11)](https://user-images.githubusercontent.com/73701483/146689103-466e59eb-066f-4b26-9020-3fada11e1c9b.png)

**Comment by gilderoylockhart01** [comment]
Can you try the various clamping/rounding options in booth the EE/IOP and VUs sections?

**Comment by GoodWall533** [comment]
Yep, switching the clampling mode in the VU section to none instead of normal fixes the issue. it fixes the issue in both software and hardware mode.

**Comment by refractionpcsx2** [comment]
Does only "none" work? I'd prefer Extra + Sign over "none", if it worked.

**Comment by GoodWall533** [comment]
Tried all of them. both the clamping and rounding options in both VU and EE/IOP sections. Only the "none" option in the VU section works, the rest either does nothing or stuff like this happens:
![2021-12-19 (12)](https://user-images.githubusercontent.com/73701483/146690607-624f3e0a-1d99-4f1c-8698-91772cf7c724.png)

**Comment by refractionpcsx2** [comment]
damn, alright, thanks for testing :)

**Comment by iamthelaw2041** [comment]
@GoodWall533 Looks like Mysterio's at it again.
