### ISSUE TITLE
[Feature Request]: Per-component Rounding/Clamping setting.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5188]
### Description

Currently, in PCSX2 we have 2 grouped categories, EE/IOP and VUs. When applying a rounding or clamping fix, this will affect all the components inside that group.

This approach is fine for the vast majority of games, but, a very few cases will break that approach.

Kung Fu Panda and Hardware Online Arena are 2 very good exemple of this. They will booth require 2 different settings on each VU. Which means PCSX2 will never be able to play those games properly in it's current form.

The request is pretty straight forward, being able to adjust clamping and rounding on a per-component basis so we can cover every cases.

I guess this is more of a 2.0 release request since I would imagine having QT would massively simplify such a request.

Could also do per address settings for specific parts of a program which require clamping/rounding.

### Reason

Increasing compatibility. In the current state of PCSX2 this can represent one important factor.

### Examples

Official Sony's emulator.

**Comment by Gunlaus** [comment]
This would also benefit Tales of Abyss overworld performance

**Comment by Scalerize** [comment]
This can fix #7241 . i really think this should be the focus of The pcsx2 team these days. a very big boulder that prevents Accuracy imo
