### ISSUE TITLE
[BUG]: MGS2 skin textures and blending accuracy

### ISSUE THREAD

**Issue by nobleflame** [PCSX2/pcsx2#5193]
This is a fairly well documented issue and if one sets the blending accuracy at anything less than full, several of the skin textures in MGS2 do not render correctly.

The skin looks darker - 

I’m wondering what is causing this issue and if anything can be done to improve this effect in MGS2.

Thank you for your time and for all of the work you guys put into this!

### Reproduction Steps

Set blending accuracy to anything under full.
Simply play the game up until any of the following moments

1) Tanker - Liquid Ocelot is revealed cutscene. His arm and face will be brown.
2) Big Shell - Fat Man’s face during cutscenes and gameplay
3) Big Shell - Vamps skin when topless during cutscenes or gameplay

### Expected Behavior

Simply, the skin tones should render correctly.

### PCSX2 Revision

v1.7.2146

### Operating System

Windows 10 (64bit)

### CPU

I7-9700

### GPU

RTX 3070

### GS Settings

No hacks enabled

### Emulation Settings

Default

**Comment by nobleflame** [comment]
Apologies if this has been incorrectly labelled. Not sure how to change / which labels would be most appropriate.

**Comment by refractionpcsx2** [comment]
Just to elaborate, with the blending accuracy on full, is the bug still present or does that resolve it?  If it resolves it, there isn't much we can do since it's already working, the reason lower levels of Blending accuracy exist is to make things lighter to emulate, but some effects don't work on the lower levels (like the one for example).

If it's still an issue with the higher levels then we will possibly need to do something about that.

As for labels, I'll add the GS one, but no need to be more specific than that right now.

**Comment by nobleflame** [comment]
Thanks for the input.

Yes the full blending accuracy does indeed fix the issue. This is why it’s not a ‘bug’ per se. The issue is that full blending accuracy makes the game run very poorly in terms of speed (even with speed hacks applied).

So not a bug but still an issue.

**Comment by lightningterror** [comment]
Can you post a gsdump?

**Comment by nobleflame** [comment]
> Can you post a gsdump?

Hi, sadly I’m away for the holidays so can’t at the moment. 

This issue is reproducible in any version of PCSX2 and copy of MGS2 (SOL, Substance, PAL, NTSC, etc).

Apologies.

**Comment by TransparentBlue** [comment]
[gs_20211220160211.gs.zip](https://github.com/PCSX2/pcsx2/files/7746155/gs_20211220160211.gs.zip)
![gs_20211220160211](https://user-images.githubusercontent.com/16150597/146788454-f8c53ce8-45b4-40f5-873c-6690f00e325c.png)

**Comment by nobleflame** [comment]
> [gs_20211220160211.gs.zip](https://github.com/PCSX2/pcsx2/files/7746155/gs_20211220160211.gs.zip)
> ![gs_20211220160211](https://user-images.githubusercontent.com/16150597/146788454-f8c53ce8-45b4-40f5-873c-6690f00e325c.png)

Thank you so much! You’ve saved me a lot of time :)

**Comment by lightningterror** [comment]
Basically what ref said, this needs sw blending, nothing else can be done for now, other than manually compiling and enabling the specific blend equation on lower level of blending.

Blend info.
```
	A:1
	B:0
	C:2
	D:2
	FIX:255
	=> (Cd - Cs) * Af + 0 ==>Cs*F - Cd*F
```

**Comment by nobleflame** [comment]
Thanks for checking this for me. 

How would I use the code above to enable this type of blending on lower levels?

**Comment by tellowkrinkle** [comment]
You can't.  It requires the ability to multiply destination colors by 2, which PC graphics hardware doesn't have.  Which means it needs full emulation of blending in the shader, which is expensive.  If you enable it on lower levels, they'll perform like full blending because that's what full blending is.

**Comment by tellowkrinkle** [comment]
Can you test that (with blending set to High) and see how performance is?
Though tbh I don't think you're going to get the effect any faster than that PR on High

**Comment by nobleflame** [comment]
Blending set to high doesn’t fix the issue and also causes a lot of slow down (although not as much as full blending obviously).

Using software mode is also problematic with MGS2 as explosions and alpha effects tank the frame rate, even on my i7-9700 and 3070 (not the highest specs, but still high nonetheless).

I guess it’s a no go for this texture correction.

Again, thank you for looking at this for me. It very sad that playing MGS2 and 3 is so challenging these days (without original hardware of course). There literally no definitive way of playing them and Konami doesn’t appear to care.

**Comment by tellowkrinkle** [comment]
Then 1022 was not the draw that was doing the skin color if you want to look at that again @lightningterror

**Comment by lightningterror** [comment]
> Then 1022 was not the draw that was doing the skin color if you want to look at that again @lightningterror

Blending high
![image](https://user-images.githubusercontent.com/18107717/146839653-71ac4fd0-fbe2-43bf-828c-4d99b849a65a.png)

**Comment by nobleflame** [comment]
My apologies, I wasn’t able to test the above. Sorry if my comment above was confusing. I meant that blending to high still causes performance issues. 

Still, nice to know what is causing the texture issues though. 

Is this potentially fixable in the future?

**Comment by nobleflame** [comment]
> > Then 1022 was not the draw that was doing the skin color if you want to look at that again @lightningterror
> 
> Blending high ![image](https://user-images.githubusercontent.com/18107717/146839653-71ac4fd0-fbe2-43bf-828c-4d99b849a65a.png)

Apologies, I seem to have been mistaken in my previous posts. Blending set to high does correct the issue with the above patch. It also doesn't appear to create any noticeable slow down. I was using a much older build that had performance issues.

So, my next question is how could we get this patch placed into a new dev build so that we can make use of the corrected textures?

**Comment by tellowkrinkle** [comment]
Wait for people to test it on other games and then it'll get merged
Merging it will close this issue so you should get a notification when that happens.

**Comment by nobleflame** [comment]
> Wait for people to test it on other games and then it'll get merged Merging it will close this issue so you should get a notification when that happens.

Thanks so much. There's been quite a bit of progress with MGS2 today. The transparent water texture issue is close to being fixed (https://github.com/PCSX2/pcsx2/pull/4385#discussion_r772032786) and now the possibility that the incorrect textures above will also be fixed. 

If this happens, PCSX2 will be the definitive way to play MGS2 on PC. Thanks!

**Comment by Sergeanur** [comment]
In case of MGS2 forcing one barrier instead of full barrier gives a great performance boost with no issues noticed. Ocelot, Fatman, Vamp and broken mirrors look as they should.

**Comment by nobleflame** [comment]
> In case of MGS2 forcing one barrier instead of full barrier gives a great performance boost with no issues noticed. Ocelot, Fatman, Vamp and broken mirrors look as they should.

That’s great to know. 

Hey, with your work on the scanmask thing we’re very close to a flawless MGS2 PS2 experience on PC. Thanks for you work mate 😃

**Comment by nobleflame** [comment]
Hey, thanks everyone! This is now the way to play MGS2 on PC.

**Comment by nobleflame** [comment]
> In case of MGS2 forcing one barrier instead of full barrier gives a great performance boost with no issues noticed. Ocelot, Fatman, Vamp and broken mirrors look as they should.

I’ve been playing around with the latest dev build and setting the blend accuracy to high still produces slow down in busy areas. 

Are you using specific settings to mitigate performance issues with high blend accuracy?
