### ISSUE TITLE
[Feature Request]: huge ui update looking Aethersx2 emulator 

### ISSUE THREAD

**Issue by Yoshi20004** [PCSX2/pcsx2#5195]
### Description

Pcsx2 ui so start old and should update look like Aethersx2 or rpcs3 emulator 

### Reason

If ui updates add things per game settings would really need for this emulator and do need use of 3rd party software. Thier is batter they use be on pcsx2 1.7.0 dev build.

### Examples

Just probably best ui based update on for app called Spectabis which 3rd party games launcher for pcsx2 which adds per game settings to the emulator. Thier does work batter new dev build because just click and load in first time it  batter if pcsx2 ui look this more so. 
![Screenshot_20211220-112320](https://user-images.githubusercontent.com/96413420/146799965-bbf45029-a9e2-46fa-b203-37e7c65c9172.jpg)

**Comment by Yoshi20004** [comment]
Should be by pcsx2 2.0 ver.

**Comment by RedDevilus** [comment]
https://www.youtube.com/watch?v=0ybUyKxHWxY

![image](https://user-images.githubusercontent.com/24227051/146800300-71c67c84-6936-4bf5-ab5d-b2120fe6b002.png)

Always been the goal.

**Comment by Mrlinkwii** [comment]
i think this is a copy of https://github.com/PCSX2/pcsx2/issues/2551

**Comment by Yoshi20004** [comment]
Ok so things are but fact ui should be updated to look like newer emulators.

**Comment by RedDevilus** [comment]
Yeah, no need for duplicate issues. We have far too many otherwise. Qt is what other emulators use and PCSX2 will have that in the future.

**Comment by Yoshi20004** [comment]
So going look like Aethersx2 once get ui updates with per game settings.

**Comment by refractionpcsx2** [comment]
Not going to be exactly the same, no, we aren't on a mobile phone.
