### ISSUE TITLE
[BUG]: Klonoa 2 Monster shadow effect missing in HW mode

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#5200]
### Describe the Bug

In Volk Underground Factory an Ow-Gow bars the path ahead that's supposed to have a shadow darkeneing effect. In HW mode this effect is not present. 

What it's supposed to look like: https://youtu.be/vDbeu5tosT4?t=4239

What HW mode renders: ![gs_20211221165858](https://user-images.githubusercontent.com/22896793/147013313-e62994a8-0aa3-4c7f-b763-76bea8af247a.png)

### Reproduction Steps

Play Underground Factory on HW mode

### Expected Behavior

The Ow-Gow is supposed to render black

### PCSX2 Revision

1.7.2146

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 3700X

### GPU

GForce 2070

### GS Settings

All defaults.

### Emulation Settings

All Defaults

### Logs & Dumps

https://www.dropbox.com/s/z4mbuuefavuiih3/gs_20211221165858.gs.xz?dl=0

**Comment by coornio** [comment]
@kenshen112 any chance you might drop a savestate (latest dev) or a memcard save so that I may test as well? I don't want to play through a third of the game just to get there :P

Thanks!

**Comment by kenshen112** [comment]
That dump file will allow you to play it but. https://www.dropbox.com/s/f2e5pa2ybeh4abx/klonoacard.ps2?dl=0b has all stages unlocked

**Comment by coornio** [comment]
Confirmed that nothing makes this effect budge in any way. The only thing I accomplished was discovering that things get freaky when MTVU/Instant VU1 are turned off lol.

![gs_20220111161143](https://user-images.githubusercontent.com/11655762/148959947-71e9f332-e99c-462b-a3c0-45b68482b293.png)

Now we just wait for the pros to tackle it eventually.

**Comment by Igetin** [comment]
I can reproduce this on v1.7.3069. Also, it happens on any level where this monster appears, not just Underground Factory. La-Lakoosha and Noxious La-Lakoosha have the issue as well.
