### ISSUE TITLE
[Feature Request]: Enable Edge Anti-Aliasing as a setting in Hardware mode 

### ISSUE THREAD

**Issue by Anileojr** [PCSX2/pcsx2#5203]
### Description

So as of now Enable Software Edge Anti-Aliasing is only in software mode should be added to hardware mode.

### Reason

Because added this fix a fair bit game bug in ffx weird line and few outher games.

### Examples

You know if use Enable Software Edge Anti-Aliasing so called enable hardware edge auti aliasing.

**Comment by lightningterror** [comment]
Edge AA1 isn't supported on hw mode yet, also duplicate.
https://github.com/PCSX2/pcsx2/issues/5069

**Comment by RedDevilus** [comment]
It is recently added for lines in hardware mode but not for triangles like FFX as of this moment. Hopefully it will be in the future.

**Comment by RedDevilus** [comment]
Duplicate from: https://github.com/PCSX2/pcsx2/issues/5069
