### ISSUE TITLE
[BUG]: Hype the Time Quest: Full boot causing weird logs in the PCSX2 console.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5204]
### Describe the Bug

In the game "Hype The Time Quest", there is a very strange bug where it will show some logs which doesn't appears with fast boot.

They relate to an "Unknown device"? I don't know what this is.

### Reproduction Steps

Load the blockdump with booth fast and full boot, skip the fmvs, and start a new game or "nouvelle partie". See the logs.

### Expected Behavior

The game should not throw weird logs when doing a full boot.

### PCSX2 Revision

PCSX2 PR 5173

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

Full Boot:
![Capture d’écran 2021-12-22 231528](https://user-images.githubusercontent.com/90222976/147161544-0fa6ceb7-7b5f-483e-bf07-1e6d07852de5.png)

Fast Boot:
![Capture d’écran 2021-12-22 231707](https://user-images.githubusercontent.com/90222976/147161557-0b608c4c-4dc3-4c83-adc2-ee27c33cb2e4.png)

### Logs & Dumps

Blockdump: https://drive.google.com/file/d/18S7xEshamWq0zc4GZb3bKH7GoeDRnx8M/view?usp=sharing

**Comment by MrCK1** [comment]
Those logs are internal to the game, I don't think it matters terribly much

**Comment by refractionpcsx2** [comment]
If you can confirm the console doesn't do this if you rig up a serial output, I'll get right on it ;)

but if it doesn't cause any problems, then I'll go ahead and close this.

**Comment by gilderoylockhart01** [comment]
False positive. Happens on real hardware. Ooops ^^

**Comment by Carnage8750** [comment]
G
