### ISSUE TITLE
[BUG - Regression]: Call of Duty World at War Final Fronts: TLB misses on the memorycard screen causing game hanging at boot.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5205]
### Describe the Bug

In the game "Call of duty World at War Final Fronts", there is a bug where PCSX2 will throw many TLB misses errors in the memorycard screen, causing the game to die at boot.

This is a regression which happened in the 1.5 dev build era. But I have lost the access to said build so I am not able to test that properly yet. If you know an area where I can get these, that would be nice and would make things easier.

### Reproduction Steps

Load the blockdump, see the PCSX2 console.

### Expected Behavior

The game should not die at this point.

### PCSX2 Revision

v1.7.2151

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### Logs & Dumps

Blockdump:
[COD WOW FF crashing.zip](https://github.com/PCSX2/pcsx2/files/7768888/COD.WOW.FF.crashing.zip)

**Comment by Anileojr** [comment]
Oh yeah will known bug it is on pcsx2 wiki to.

**Comment by prafullpcsx2** [comment]
Works fine here. Try dumping your iso again?

**Comment by gilderoylockhart01** [comment]
Okay, I can't seem to reproduce that on master, it was the refraction's IPU PR which was having problems with that game.

I re-ripped the game, made sure the MD5 match, but I still have a problem where the game will not respond to user input, I have the PAL version of the game if that matters.

**Comment by refractionpcsx2** [comment]
I can rebase my pr if you want to make sure that's not causing causing it, though would be weird, more likely fixed by the gsoffset stuff

**Comment by prafullpcsx2** [comment]
I am using PAL version with Ref's IPU PR. Neither the game suffers from TLB miss nor it has any input problems.

**Comment by refractionpcsx2** [comment]
well, I've rebased, if you wanna check it on the off chance. 

Also if you're using 64bit or 32bit might be important.

**Comment by gilderoylockhart01** [comment]
Ok I will test on your PR, until now I have only used 32bit versions of the emu.

Prafull, does your disc MD5 match the redump database too?

**Comment by gilderoylockhart01** [comment]
Okay, it was the FMV which was crashing the whole game, with the new rebase, it's fine.

**Comment by prafullpcsx2** [comment]
Yes my md5 matches redump. And master works fine on this too so closing this as invalid.

**Comment by refractionpcsx2** [comment]
It's not invalid, the TLB misses were irrelivant to the original issue, no?

**Comment by gilderoylockhart01** [comment]
Yeah, remove it from the PR, I don't know why, but it seems that testing individual builds in the same folder as a dev build mess up the whole emu and creates weird problems, solve others in a mystery way.

**Comment by gilderoylockhart01** [comment]
Okay, this is an actual bug, but a game one. Having a memorycard bigger than 8mb in the slot1 will frezze the game at the memcard check..... Okay Activision, good job on that.

**Comment by refractionpcsx2** [comment]
well then the TLB miss problem on the Wiki, is that actually an issue or people with a bad dump? If it was a genuine problem, it would be interesting to know when it was fixed.

**Comment by gilderoylockhart01** [comment]
I think it's just a bad dump, the game will just frezze with no errors if the memcard is more than 8mb.

**Comment by Fgr-35** [comment]
Is there a way to fix that? I have a 128mb memory card and i have found a way around it but is it really annoying, as i have to insert and remove the memory card at specific times during the memory card check in order to make the game work with it and i have a 90% success rate but i want to play the game without doing that, is there a way to mess with any settings or something in the code in order to fix that issue?

**Comment by Mrlinkwii** [comment]
@Fgr-35  use a 8mb memory card , this is a game bug not a pcsx2 bug ,  make a per game setting with only a 8mb memcard

**Comment by Fgr-35** [comment]
Ok, thanks. I thought it was really weird for the game to just hang on the loading screen, i have a different memory card with 8mb, i just prefer to use the 128mb one so i don't need to create new memory cards every so often because i have a really big library of games and i cannot keep all of the saves in just a single 8mb one

**Comment by mzy1996** [comment]
I‘m using the latest version of pcsx2 nightly version, but I still have this freeze problem on the memory screen even I use the 8MB memory card file,
Log still says TLB Misses:
[   15.6417] TLB Miss, pc=0x425f5c addr=0x33353285 [load]
[   15.6428] TLB Miss, pc=0x425f5c addr=0x33353305 [load]
[   15.6431] TLB Miss, pc=0x425f88 addr=0x33353230 [load]
[   15.6434] TLB Miss, pc=0x425f88 addr=0x33353228 [load]
[   15.6436] TLB Miss, pc=0x425f88 addr=0x33353238 [load]
[   15.6438] TLB Miss, pc=0x425f88 addr=0x33353230 [load]
[   15.6440] TLB Miss, pc=0x425f88 addr=0x33353240 [load]
[   15.6441] TLB Miss, pc=0x425f88 addr=0x33353238 [load]
[   15.6443] TLB Miss, pc=0x425f88 addr=0x33353248 [load]
[   15.6445] TLB Miss, pc=0x425f88 addr=0x33353240 [load]
[   15.6447] TLB Miss, pc=0x425f88 addr=0x33353250 [load]
[   15.6449] TLB Miss, pc=0x425f88 addr=0x33353248 [load]
[   15.6450] TLB Miss, pc=0x425f88 addr=0x33353258 [load]
[   15.6452] TLB Miss, pc=0x425f88 addr=0x33353250 [load]
[   15.6454] TLB Miss, pc=0x425f88 addr=0x33353260 [load]
[   15.6459] TLB Miss, pc=0x425f88 addr=0x33353258 [load]
[   15.6463] TLB Miss, pc=0x425f88 addr=0x33353268 [load]
[   15.6467] TLB Miss, pc=0x425f88 addr=0x33353260 [load]
[   15.6471] TLB Miss, pc=0x425f88 addr=0x33353270 [load]
[   15.6474] TLB Miss, pc=0x425f88 addr=0x33353268 [load]
[   15.6476] TLB Miss, pc=0x425f88 addr=0x33353278 [load]
[   15.6478] TLB Miss, pc=0x425f88 addr=0x33353270 [load]
[   15.6480] TLB Miss, pc=0x425f88 addr=0x33353280 [load]
[   15.6482] TLB Miss, pc=0x425f88 addr=0x33353278 [load]
[   15.6486] TLB Miss, pc=0x425f88 addr=0x33353288 [load]
[   15.6487] TLB Miss, pc=0x425f88 addr=0x33353280 [load]
[   15.6489] TLB Miss, pc=0x425f88 addr=0x33353290 [load]
[   15.6491] TLB Miss, pc=0x425f88 addr=0x33353288 [load]
[   15.6493] TLB Miss, pc=0x425f88 addr=0x33353298 [load]
[   15.6495] TLB Miss, pc=0x425f88 addr=0x33353290 [load]
[   15.6497] TLB Miss, pc=0x425f88 addr=0x333532a0 [load]
[   15.6499] TLB Miss, pc=0x425f88 addr=0x33353298 [load]
[   15.6501] TLB Miss, pc=0x425f88 addr=0x333532a8 [load]
[   15.6502] TLB Miss, pc=0x425f88 addr=0x333532a0 [load]
[   15.6504] TLB Miss, pc=0x425f5c addr=0x33353285 [load]
[   15.6506] TLB Miss, pc=0x425f5c addr=0x33353305 [load]
[   15.6508] TLB Miss, pc=0x425f88 addr=0x33353230 [load]
[   15.6510] TLB Miss, pc=0x425f88 addr=0x33353228 [load]
[   15.6512] TLB Miss, pc=0x425f88 addr=0x33353238 [load]
[   15.6513] TLB Miss, pc=0x425f88 addr=0x33353230 [load]
[   15.6515] TLB Miss, pc=0x425f88 addr=0x33353240 [load]
[   15.6517] TLB Miss, pc=0x425f88 addr=0x33353238 [load]
[   15.6519] TLB Miss, pc=0x425f88 addr=0x33353248 [load]
[   15.6521] TLB Miss, pc=0x425f88 addr=0x33353240 [load]
[   15.6522] TLB Miss, pc=0x425f88 addr=0x33353250 [load]
[   15.6524] TLB Miss, pc=0x425f88 addr=0x33353248 [load]
[   15.6526] TLB Miss, pc=0x425f88 addr=0x33353258 [load]
[   15.6528] TLB Miss, pc=0x425f88 addr=0x33353250 [load]
[   15.6530] TLB Miss, pc=0x425f88 addr=0x33353260 [load]
[   15.6532] TLB Miss, pc=0x425f88 addr=0x33353258 [load]
