### ISSUE TITLE
[BUG]: It won't run recognize game paths via script. 

### ISSUE THREAD

**Issue by anchounio** [PCSX2/pcsx2#5206]
### Describe the Bug

I cannot run anygame using scripts (bat files of autohotkeys files). For example, if I put this into a bat file:

pcsx2 ".\roms\Tekken 5 (USA).iso" --fullboot --fullscreen

pcsx2 will load the console bios instead.

If I manually type the same line in a cmd window, the game will run with no problems.

### Reproduction Steps

Create a bat file trying to run a game, for example with this content:

pcsx2 ".\roms\Tekken 5 (USA).iso" --fullboot --fullscreen

make sure the command line used works manually. 
The bat file will not load the game, it will run the BIOS instead.

### Expected Behavior

Bat file should open the game.

### PCSX2 Revision

1.7.0-dev-1567-g21c13a850

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
Can you try absolute paths

**Comment by anchounio** [comment]
Same problem with absolute paths.

**Comment by anchounio** [comment]
pcsx2 just doesn't like scripts.

**Comment by ribolovac510** [comment]
Can't reproduce this issue on 1.7.2144, both absolute and relative paths work

https://user-images.githubusercontent.com/74596991/147278328-5671d9c6-367a-4182-9d54-9a401d3bf616.mp4

**Comment by anchounio** [comment]
It is working. This bug can be closed.

**Comment by anchounio** [comment]
It is working. This bug can be closed.
