### ISSUE TITLE
[BUG]: crash bandicoot the wrath of cortex broken fog on hardware mode

### ISSUE THREAD

**Issue by Anileojr** [PCSX2/pcsx2#5207]
### Describe the Bug

When play crash bandicoot the wrath of cortex on hardware you get broken fog. in fact turn off CRC hack level and Mipmapping just see fog on hardware mode but still broken.

### Reproduction Steps

Go to settings turn off CRC hack level and Mipmapping and see fog in game Gitch out.

### Expected Behavior

what look like in software mod
![Screenshot (6)](https://user-images.githubusercontent.com/96551378/147257041-b7f9e888-278d-40b3-9f61-e29151cefbe0.png)

and not look like in hardware mod
![Screenshot (5)](https://user-images.githubusercontent.com/96551378/147257118-cb502ff8-a163-4b46-b38d-3dea673c0859.png)

### PCSX2 Revision

PCSX2 Nightly - v1.7.2151

### Operating System

Windows 11

### CPU

Ryzen 9 4900hs 

### GPU

Rtx 2060 max q

### GS Settings

![Screenshot (7)](https://user-images.githubusercontent.com/96551378/147258225-15467624-10c5-41c9-83be-a2f8733427b5.png)

### Emulation Settings

no Emulation Settings are changed here at all

### Logs & Dumps

Save shot- [SLUS-20238 (103B5706).00.p2s.zip](https://github.com/PCSX2/pcsx2/files/7770003/SLUS-20238.103B5706.00.p2s.zip)
Block damp- [Uploading Crash Bandicoot The Wrath of Cortex (2021-11-23 10-00-36).zip…]()

**Comment by Anileojr** [comment]
@ramapcsx2 how long bug take be fixed because game breaking on Hardware mode because fog should work but does not on Hardware mode. Will bug never be fixed.

**Comment by gilderoylockhart01** [comment]
Pinging staff members isn't going to help for sure. You provided the GSdump, that's good, but the team will look at it when they can.
