### ISSUE TITLE
[BUG]: 120 yen stories- absolute garbage graphics in hardware

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5211]
### Describe the Bug

https://wiki.pcsx2.net/120-en_no_Haru

i can't describe it hardware mode is totally fucked.

### Reproduction Steps

just play

### PCSX2 Revision

1.70.2152

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

hardware renderer

### GS Window Screenshots

![gs_20211223213556](https://user-images.githubusercontent.com/8851653/147313260-08e4d3a7-2d76-4963-8ab7-982f39f24cea.png)
![gs_20211223213416](https://user-images.githubusercontent.com/8851653/147313280-590c484c-feea-4df5-9157-30130456d334.png)

### Logs & Dumps

[gs_20211223213416.gs.zip](https://github.com/PCSX2/pcsx2/files/7772471/gs_20211223213416.gs.zip)
this contains 4 gs dumps

**Comment by refractionpcsx2** [comment]
This is now fixed in master, though if there's more CRC's for this game they will need to be added
