### ISSUE TITLE
[BUG]: Blacksreen in games after version v1.7.2161-gb0a0d714c4

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#5217]
### Describe the Bug

Blackscreen in some games (Shadow of the colossus PAL, MGS3 snake eater PAL, etc) some games works as expected, like Kingdom hearts 1 PAL and Dragon quest 8 PAL.

This started after v1.7.2161-gb0a0d714c4, I assume this is something related with the new shader cache option. "the latest working version for me is the v1.7.2161 "GameDB: Fix Round/Clamp nodes"

Specs: 

W11 pro x64
16 GB DDR3
GTX 970
i7 4790k

### Reproduction Steps

Use any build after v1.7.2161, and open a game like shadow of the colossus or metal gear solid 3 snake eater. Blackscreen with background sound, even in the BIOS screen.

### PCSX2 Revision

v1.7.2161-gb0a0d714c4

### Operating System

Windows 11

### CPU

i7 4790k

### GPU

GTX 970

**Comment by refractionpcsx2** [comment]
did you update all your resources and shader folders also or just pull the exe out? because that would be your mistake.

**Comment by LuismaSP89** [comment]
On the latest build I had from the beginning of december, I didn't had the "resources" folder, so this one is totally new. I overwrited all the files and folders of my pcsx2 portable folder. Not working here.

If I download the v1.7.2161 version "wich has the resources folder" and overwrite everything again, then it works. So, at least from my side there's somehow some problems starting after this v1.7.2161 version.

**Comment by refractionpcsx2** [comment]
okay the resources have updated since 2161 so make sure you extract everything from the new version.

if it's still not working can you please post the emulog.txt from your logs folder after running the game so we can see the problem.

**Comment by seta-san** [comment]
yes. it's the resources folder. the autoupdater might be more important now that the resources aren't being baked into the binary.

**Comment by LuismaSP89** [comment]
Ok, forget about this, I deleted all the .ini files, restarted the computer, replaced again all the files from the newer version, and now it's working properly. Sorry for the inconvenience.

**Comment by refractionpcsx2** [comment]
No problem, glad you worked it out
