### ISSUE TITLE
[Feature Request]: NSIS - DEV9 needed components (+ mention USB image)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5225]
### Description

By default, you don't see any adapters when you want to play online. 
TAP + PCAP both require 3rdparty software for this (later there is winsocks as 3rd method which doesn't need other software)

You also can't auto-create blank images for USB like HDD image can, so you need to get it from here:
https://github.com/jackun/USBqemu-wheel/tree/master/dist

So it doesn't only encompass those situations but those are the main issues for the installer.

### Reason

Less confusing to users, this isn't the age of plugin hunting and extensive tutorials for something that can be more built-in.

### Examples

What's in bold is what is needed:
**https://nmap.org/npcap/dist/npcap-1.60.exe (NPCAP recommended)**
 (source also contains other variants such as zip and older versions: https://nmap.org/npcap/dist/ )

https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe (PCAP) (Older and kinda legacy)

https://openvpn.net/community-downloads/ (TAP driver + OpenVPN installer) (Bulkier but easy to install)
**https://build.openvpn.net/downloads/releases/latest/tap-windows-latest-stable.exe (TAP driver Recommended)**

**Comment by MrCK1** [comment]
Closing since NSIS is gone from the repo
