### ISSUE TITLE
[SPU2-X][Bug]Eternal Ring sound looping sound issue

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#523]
This is a report from the forum and I just added here:
-----------------------------------------------------------------------------------------------------
http://forums.pcsx2.net/Thread-Eternal-Ring-sound-looping-sound-issue
------------------------------------------------------------------------------------------------------
I'll start with system specs, windows 7 professional 64 bit, 12GB RAM, nvidia GT 620. PCSX2 version, 1.3.1 20150503164648. Basically in short i'm currently at the Magic Lab area of the game. The sound effect for doors opening closing(basically a short rumbling sound) will occasionally at random begin to loop and once it does the only way to get rid of it seems to be to save the game, quit the emulator and load everything back up. The problem is entirely random and can happen either the first time a door is opened or the 30th time. I've tried playing with the sound settings and haven't found anything that seems to stop the issue.

EDIT
oops forgot to mention, i'm running the NTSC-U version of the game. Oops forgot to include cpu in the original text, its an i7-3770.

**Comment by trader5896** [comment]
Please provide a Emulog..

**Comment by trader5896** [comment]
As seen, there is something looping, which could actually be a misfunction, that will always loop and loop again.

**Comment by bositman** [comment]
Why are you making 3 posts instead of editing the first? Again, follow the guidelines for proper issue reporting.
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by refractionpcsx2** [comment]
Considering this guy was trolling us with spam PR's and got banned from github and failed to follow the guidelines, I have little desire to help him.

**Comment by ssakash** [comment]
@refractionpcsx2 

all the deleted users are titled as "Ghost" , this is a different guy. :p

**Comment by refractionpcsx2** [comment]
Either way, he got deleted, was obviously a douche :P
