### ISSUE TITLE
[BUG]: DEV9

### ISSUE THREAD

**Issue by RodneyHawk** [PCSX2/pcsx2#5237]
### Describe the Bug

What does it mean?
![bandicam 2021-12-31 00-35-36-746](https://user-images.githubusercontent.com/16501739/147783206-acf54116-2129-4cb4-9cfe-407b7389bb32.jpg)

### Reproduction Steps

I go in and there is nothing

### PCSX2 Revision

v1.7.2183

### Operating System

Windows 10 (64bit)

**Comment by Dnawrkshp** [comment]
You need to install npcap: https://nmap.org/npcap/

**Comment by Blackbird88** [comment]
Related to #5225

**Comment by RodneyHawk** [comment]
> You need to install npcap: https://nmap.org/npcap/



> Related to #5225

I need Winsock!

**Comment by RodneyHawk** [comment]
NPCAP and TAP does not work!

**Comment by Blackbird88** [comment]
Winsock backend wasn't merged yet. See #4944
PCAP works fine for me.

**Comment by RodneyHawk** [comment]
> Winsock backend wasn't merged yet. See #4944 PCAP works fine for me.

The fact of the matter is that it is not! TAP and NCAP did not help me with any settings, the emulator does not see the Network Adapter. How did I find out? In Biohazard Outbreak in the connection setup menu. Hanging occurs, but does not hang, and there is simply nothing happening.
![bandicam 2021-12-31 19-23-43-745](https://user-images.githubusercontent.com/16501739/147828065-3619b158-4acb-40db-8103-400effd858ed.jpg)

**Comment by RedDevilus** [comment]
There is a seperate config inside PS2 games too.

**Comment by RedDevilus** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/4944
