### ISSUE TITLE
[Bug] [GIFdma] Onimusha 4 - Dawn Of Dreams - 2D Stages displays garbage and the emulog is growing endless 

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#524]
Onimusha 4 - Dawn of Dreams 

This games requires a patch (provided by Shadow Lady) to start, if you don't start with the patch,
it won't start, but it will produce the endless bug:
"libdma: sync timeout (a few times)
IPU Invalid Intra DC Precision, switching to 9 bits"

As known, the 2D Graphics in this Game are not processed, because of the 
shortcoming of GIFdma implentation. This is still as for 05. May 2015 existent and it doesn't matter,
if you select HW or SW and has nothing to with these both.

As said by the old Forum, this is how signal is processed:

"The game performs SIGNAL in the GIF and then performs another SIGNAL before the first is processed.
GS manual claims that GS should halt (what does this word mean???) in these situations. If I'm not mistaken,
PCSX2 doesn't. Might be mistaken, though."

And I think, what I understand from this Emulog (which is growing just on 2D stages to few GB in minutes, 
because of this bug) and what the user in the old forum said is:

: "�IMAGE�IMAGE.AFS;1" --> It send to IPU.cpp (which is corrupeted) --> Corrupted picture on 2D stages.

Source-Code\pcsx2\Ipu\IPU.cpp
...
"
{
	// Note: It's assumed that mem's input value is always in the 0x10002000 page
	// of memory (if not, it's probably bad code).

	pxAssert((mem & ~0xfff) == 0x10002000);
	mem &= 0xfff;

	switch (mem)
	{
		ipucase(IPU_CMD): // IPU_CMD
			IPU_LOG("write32: IPU_CMD=0x%08X", value);
			IPUCMD_WRITE(value);
			IPUProcessInterrupt();
		return false;

		ipucase(IPU_CTRL): // IPU_CTRL
            // CTRL = the first 16 bits of ctrl [0x8000ffff], + value for the next 16 bits,
            // minus the reserved bits. (18-19; 27-29) [0x47f30000]
			ipuRegs.ctrl.write(value);
			if (ipuRegs.ctrl.IDP == 3)
			{
				Console.WriteLn("IPU Invalid Intra DC Precision, switching to 9 bits");
				ipuRegs.ctrl.IDP = 1;
			}

			if (ipuRegs.ctrl.RST) ipuSoftReset(); // RESET

			IPU_LOG("write32: IPU_CTRL=0x%08X", value);
		return false;
	}
	return true;
}

// returns FALSE when the writeback is handled, TRUE if the caller should do the
// writeback itself.
__fi bool ipuWrite64(u32 mem, u64 value)
{
	// Note: It's assumed that mem's input value is always in the 0x10002000 page
	// of memory (if not, it's probably bad code).

	pxAssert((mem & ~0xfff) == 0x10002000);
	mem &= 0xfff;

	switch (mem)
	{
		ipucase(IPU_CMD):
			IPU_LOG("write64: IPU_CMD=0x%08X", value);
			IPUCMD_WRITE((u32)value);
			IPUProcessInterrupt();
		return false;
	}

	return true;
"

As this bug exists, the emulog will grow to a few GB's as long you are in 2D Menu's. If you leave, it will end growing.

For more info, please provide informations...

Please rename the jpg to zip to look for the file.
![emulog](https://cloud.githubusercontent.com/assets/12198979/7483137/d42215de-f37c-11e4-96bd-ab83458e8995.jpg)

**Comment by bositman** [comment]
Please follow the guidelines for posting proper issues.
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues
