### ISSUE TITLE
[BUG]: Snoopy vs. the Red Baron - Z-Fighting issues, various HW rendering issues

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5240]
### Describe the Bug

Both renderers exhibit Z-Fighting issues as shown in this video (skip ahead about 18 seconds, then watch the top screen).
https://user-images.githubusercontent.com/50224630/147812151-39034eea-667f-4edf-80fa-04201b6d6657.mp4
I have tried my best to get GSdumps of the issue. Holding ctrl + shift + f8 doesn't work on linux at the moment, so I simply made as many individual gsdumps as I could. EE/VU clamping options did not fix the issue.
[zfighting.zip](https://github.com/PCSX2/pcsx2/files/7795672/zfighting.zip)

Beyond that, several HW renderer issues are present.
- Top and bottom of the screen aren't turned black when the opening FMV starts
![gs_20211230163327](https://user-images.githubusercontent.com/50224630/147812261-c23ea742-6b0b-44c0-92bf-4039eb373524.png)
[gs_20211230163327.gs.zip](https://github.com/PCSX2/pcsx2/files/7795673/gs_20211230163327.gs.zip)
- Black vertical bars appear over the screen during some transitions in the main menu
![gs_20211230164057](https://user-images.githubusercontent.com/50224630/147812486-6c8a32fe-270d-4dd3-88d0-6658f0b84c6f.png)
[gs_20211230164057.gs.zip](https://github.com/PCSX2/pcsx2/files/7795682/gs_20211230164057.gs.zip)
- The skybox is too dark/faded 
SW (Correct):
![gs_20211230222626](https://user-images.githubusercontent.com/50224630/147812577-e20b4302-3937-474b-a475-3a5a10d13a37.png)
[gs_20211230222626.gs.zip](https://github.com/PCSX2/pcsx2/files/7795688/gs_20211230222626.gs.zip)
HW (Incorrect):
![gs_20211230222704](https://user-images.githubusercontent.com/50224630/147812627-e10e07b7-0ccc-48a2-a9ec-e65787c5a770.png)
[gs_20211230222704.gs.zip](https://github.com/PCSX2/pcsx2/files/7795689/gs_20211230222704.gs.zip)
- Garbage appears on the bottom and middle of the screen during 2 player
SW (Correct): 
![gs_20211230223245](https://user-images.githubusercontent.com/50224630/147812680-1ea0ff2d-6653-40bf-8b73-d381b1093fa2.png)
[gs_20211230223245.gs.zip](https://github.com/PCSX2/pcsx2/files/7795697/gs_20211230223245.gs.zip)
HW (Incorrect):
![gs_20211230223238](https://user-images.githubusercontent.com/50224630/147812876-cebe2ac5-b834-4eb0-b711-f767086da35a.png)
[gs_20211230223238.gs.zip](https://github.com/PCSX2/pcsx2/files/7795698/gs_20211230223238.gs.zip)

Additionally, the game needs mipmapping set to at least Basic (Fast) . CRC is 213DCAC9.

Furthermore, the opening few screens (the initial black screen, the memory card check screen, and the logo screens) run extremely poorly, especially considering very little is going on. This is especially painful on software, where I hit 22% speed, far less than the rest of the game, which already runs very poorly, as the game seems to be somewhat intensive in general. According to Tellow,
> Game looks to be running at 900fps internally
> They must have forgotten to cap fps
> Combined with our lack of GS backpressure (PCSX2 doesn't emulate the amount of time it takes the PS2's GS to process large triangles) results in ridiculously high amounts of work
> You can get it going fairly fast if you throw enough cores at it

Regardless, I figured that they were worth noting here, along with the rest of the game's extremely poor performance. Attached are GSdumps and a blockdump. 

[Screens.zip](https://github.com/PCSX2/pcsx2/files/7795721/Screens.zip)

### Reproduction Steps

Start the game and play.

### Expected Behavior

Expected behavior was outlined in the first section.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2183 Compiled on Dec 30 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

**Comment by refractionpcsx2** [comment]
Above linked PR fixes the bad stripes, the wrong coloured sky is fixed by enabling Mipmapping (Basic).  In future we could make this automatic.

**Comment by refractionpcsx2** [comment]
I was incorrect, mipmapping doesn't fix the sky, whoops.

**Comment by JordanTheToaster** [comment]
Disable depth conversion seems to make the sky closer to software so whatever it is it's depth related.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/36b049a7-21e9-444f-8d25-b0fe009afb1a)
