### ISSUE TITLE
[BUG]: Happy! Happy!! Boarders in Hokkaidou Rusutsu Resort- HW Renderer issues

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5246]
### Describe the Bug

- Shadows are nearly invisible on HW.
SW:
![gs_20220101014940](https://user-images.githubusercontent.com/50224630/147852706-71522f40-327d-42fe-a248-28c186d2dacf.png)
[gs_20220101014940.gs.zip](https://github.com/PCSX2/pcsx2/files/7797770/gs_20220101014940.gs.zip)
HW:
![gs_20220101015025](https://user-images.githubusercontent.com/50224630/147852737-b0faef9c-5c78-4c6d-b913-02ca9c6ced71.png)
[gs_20220101015025.gs.zip](https://github.com/PCSX2/pcsx2/files/7797773/gs_20220101015025.gs.zip)
- Some textures (in this case, windows on a building in the distance) experience extreme flicker on HW.
SW:
![gs_20220101015706](https://user-images.githubusercontent.com/50224630/147852760-07fc9cb3-a1b7-4e9e-b8e1-99f88b0a962f.png)
[gs_20220101015706.gs.zip](https://github.com/PCSX2/pcsx2/files/7797775/gs_20220101015706.gs.zip)
HW:
![gs_20220101015711](https://user-images.githubusercontent.com/50224630/147852765-30719452-a3ba-4230-92e3-ce67ffb529bc.png)
[Uploading gs_20220101015711.gs.zip…]()

### Reproduction Steps

Start a new game, go down the first slope.

### Expected Behavior

Expected behavior outlined in original post.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2183 Compiled on Dec 30 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

**Comment by MrCK1** [comment]
Checked on master (1.7.4781). Shadows are fine on GL/Vulkan with max blending.

The windows issue in HW seems to be the usual z-fighting.

**Comment by lightningterror** [comment]
Shadows are fine with basic blending now, as for the z-fighting there is a meta issue https://github.com/PCSX2/pcsx2/issues/3692
