### ISSUE TITLE
[BUG]: missing resources handling

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5253]
### Describe the Bug

when i did my daily build of the emulator i didn't transfer over the new font resources and got an assert error. right away i know what was wrong but the average user might not. the emulator needs to be able to handle missing resources in a way that will make sense to common user and maybe even download missing files for them.

### Reproduction Steps

run the emulator with missing resources.

### PCSX2 Revision

1.7.2187

### Operating System

Windows 11

**Comment by gilderoylockhart01** [comment]
Well, I would say that is a bit of a side effect of the current massive redesign of the whole emu and likely something that will go away soon enough. As long as the 1.8 stable build is working out of box that's a non-issue really.

**Comment by MrCK1** [comment]
> Well, I would say that is a bit of a side effect of the current massive redesign of the whole emu and likely something that will go away soon enough. As long as the 1.8 stable build is working out of box that's a non-issue really.

Sure but it's still something that should be addressed as much as possible.

From my quick tests, it looks like you will only get an error if the  ```resources``` folder is missing. Anything inside the folder doesn't appear to be validated as part of the check.

**Comment by refractionpcsx2** [comment]
This was WX which is now gone, though to be honest if you're missing half the files the program needs, then you should expect it to not work, the same would happen with any other program.
