### ISSUE TITLE
[Feature Request]: Removing the MVU flag hack.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5254]
### Description

MVU flag hack existed for years and was mostly effective on Ratchet and Clank, but on today's versions of the emulator this hack basically bring 0 speed improvement of any kind.

### Reason

Compatibility + cleanup.

### Examples

Does this need an example ^^?

**Comment by refractionpcsx2** [comment]
It still brings a huge speedup in some games, it's not going anywhere.
