### ISSUE TITLE
[BUG]: Dark Cloud 2 (SCUS-97213) regression: Flickering shadows

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#5260]
### Describe the Bug

Character shadows exhibit major flickering. If dev/verbose log is enabled, minor slowdown is caused due to excessive log spam.
`Gif Unit - GS packet size exceeded VU memory size!`

### Reproduction Steps

Load game, enter any area on affected builds with speedhacks disabled.

### PCSX2 Revision

1.7.0-dev-684 and later

### Operating System

Windows 11

### CPU

Ryzen R9 3900X

### GPU

GTX 1080

### GS Settings

SW rendering, but GS settings do not seem to affect it.

### Emulation Settings

MTVU and Instant VU1 disabled. Either of these speedhacks fixes the issue (as 713876918227367f8e8f336b84e5db1c4e3d52ee changes the previously working behavior and relegates the old one to a speedhack).

### GS Window Screenshots

https://user-images.githubusercontent.com/17594477/147964467-377d32d5-969a-4ab6-b8ec-fd2a98040f3e.mp4

### Logs & Dumps

[Memory card](https://github.com/PCSX2/pcsx2/files/7803300/darkcloud2shadowflicker.zip)
[Savestate](https://github.com/PCSX2/pcsx2/files/7803687/SCUS-97213.1DF41F33.00.p2s.zip)

Simply load and enter the selected area.

**Comment by refractionpcsx2** [comment]
Using synchronised VU1 doesn't work with everything, i guess we'll have to add a gamefix to stop people turning it off.

**Comment by trostboot** [comment]
Sounds like a good idea. Since it's under speedhacks, it kinda implies you're potentially sacrificing accuracy by turning it on, not the other way around.

**Comment by refractionpcsx2** [comment]
well the PS2 is such a mess of timing problem.  The other thing to check would be the VU Kickstart gamefix, as that also helps with timing problems depending on how games handle the VU's.

**Comment by trostboot** [comment]
Good call. Manual VU Kickstart gamefix also works, should probably be added to the DB. I can test it some more tomorrow if you expect any potential other issues arising from it.

**Comment by trostboot** [comment]
Did some testing with both the US and EU version across a slice of the game (cutscene, dungeon, city building, spheda and fishing minigames), didn't notice anything out of the ordinary. Works with both synchronized and InstantVU1/MTVU, so should be good.
