### ISSUE TITLE
[BUG]: NBA Jam (USA) - slus-20648 - f51b2328

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5262]
### Describe the Bug

Stuck at the intro

### Reproduction Steps

Launch the game

### PCSX2 Revision

1.7.2190

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

### Logs & Dumps

[NBA Jam (USA) (2022-00-04 11-20-39).zip](https://github.com/PCSX2/pcsx2/files/7806898/NBA.Jam.USA.2022-00-04.11-20-39.zip)

**Comment by refractionpcsx2** [comment]
I ran out of blocks, which suggests you're doing something wrong. Did you just not wait long enough?

**Comment by spacemul** [comment]
can go ingame but no menus

**Comment by refractionpcsx2** [comment]
Menus have some sort of ordering problem, if you load the game with ZeroGS the background appears to be missing and you can see the menu options and the basketball player, will need some investigation, may need patching, not sure yet.

I did make a patch for a COP2 problem the game has but it doesn't seem to make any difference to the menus

// Fixes COP2 DIV Q ordering
patch=1,EE,003DBC7C,word,4BE0105C
patch=1,EE,003DBC80,word,4A6103BC

**Comment by refractionpcsx2** [comment]
okay so the game kinda double buffers how it draws the screen, alternating how it adds the background and draws over it, this relies on the CSR FIELD which apparently needs to be the opposite to what it's currently coming out as, this could be a timing thing, not sure....

![image](https://user-images.githubusercontent.com/6278726/148055869-8d8b8682-47c1-466d-9d65-1669d59d7a28.png)
