### ISSUE TITLE
[BUG]: Hotkey doesn't work after switching HW renderer

### ISSUE THREAD

**Issue by Tokman5** [PCSX2/pcsx2#5267]
### Describe the Bug

When you switch the game while running a game, and change the renderer to another HW one in Graphics Settings, any hotkey does not work anymore.
If you shut down the game and load another one, this bug doesn't seem to be occurred.

This bug does not happen in v1.7.2186.
It started to happen since v1.7.2187 ( #5221 ).

### Reproduction Steps

- Set D3D11 or OGL renderer in Graphics Settings.
- Run a game.
- while running the game, load another game and reset the system.
- Switch the renderer to another HW one in Graphics Settings.

### Expected Behavior

Hotkey should work well.

### PCSX2 Revision

v1.7.2197 - it's still existed in this version

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Yep, can confirm that the hotkeys become unresponsive, including escape.

**Comment by Tokman5** [comment]
I can't reproduce with your easier steps. Changing HW renderer is still needed.

**Comment by refractionpcsx2** [comment]
weird, works here, are you starting in a hw renderer?

**Comment by Tokman5** [comment]
yes

**Comment by refractionpcsx2** [comment]
oh I see why, you have to be in DX11, doesn't work if you're on OGL

**Comment by Tokman5** [comment]
I still need to change Adapter settings, but I can reproduce without changing HW renderer.
