### ISSUE TITLE
[Documentation] Problematic games with no entry or stub entry on PCSX2-wikia

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#527]
To Bositman or the bug squad team,

these games have no PCSX2 Wikia entry:

http://forums.pcsx2.net/Thread-Victorious-Boxers-Ippo-s-Road-to-Victory-SLUS-20282-U--29721
http://forums.pcsx2.net/Thread-Urban-Chaos-Riot-Response-SLUS-21390-U--28449
http://forums.pcsx2.net/Thread-Sims-The-Bustin-Out-SLUS-20842-U--29837
http://forums.pcsx2.net/Thread-Star-Wars-The-Force-Unleashed-SLUS-21614-U--28913
http://forums.pcsx2.net/Thread-Superman-Shadow-of-Apokolips-SLUS-20235-U--29776
http://forums.pcsx2.net/Thread-Taxi-Rider-SLES-53402-E
http://forums.pcsx2.net/Thread-Sakura-Taisen-3-Remake-SLPM-65900-J
http://forums.pcsx2.net/Thread-Pac-Man-World-2-SLUS-20224-U--29404
http://forums.pcsx2.net/Thread-NHL-2K5-SLUS-20921-U--28693
http://forums.pcsx2.net/Thread-Lifeline-SLUS-20848-U--29110
http://forums.pcsx2.net/Thread-NASCAR-2009-SLUS-21744-U
http://forums.pcsx2.net/Thread-Headhunter-SLUS-20416-U
http://forums.pcsx2.net/Thread-Ruff-Trigger-The-Vanocore-Conspiracy-SLUS-21314-U--28733
http://forums.pcsx2.net/Thread-Silent-Hill-Origins-SLKA-25422-K

Stub, which seem not to work on Compatibility list and their articles on the wikia are stubs:

http://wiki.pcsx2.net/index.php/TD_Overdrive
http://wiki.pcsx2.net/index.php/Simple_2000_Series_Vol._8:_The_Tennis (SMASH Court Tennis???)
http://wiki.pcsx2.net/index.php/Hype:_The_Time_Quest

**Comment by ssakash** [comment]
what do you mean by no wiki entry ?  check the wikiurl= link in the first post. that redirects you to wiki page of the game.

**Comment by ssakash** [comment]
what do you mean by no wiki entry ?  check the wikiurl= link in the first post. that redirects you to wiki page of the game.

**Comment by trader5896** [comment]
Yes, where you mention this, this is right, but their are problems regarding the compatbility list and the wiki uRL. 
For example:
http://forums.pcsx2.net/Thread-NASCAR-2009-SLUS-21744-U (nothing)
http://wiki.pcsx2.net/index.php/NASCAR_09 (playable)

That's the main problem.

**Comment by ssakash** [comment]
it could have been a regression (or) a Invalid test. someone on the wiki should look into it.

**Comment by trader5896** [comment]
All of these entries seem to have such a problem. Bositman will hopefully look for it. 

:D

**Comment by joder666** [comment]
This entries were missing from the wiki:
http://forums.pcsx2.net/Thread-Sakura-Taisen-3-Remake-SLPM-65900-J
http://wiki.pcsx2.net/index.php/The_Sims_Bustin%27_Out

Not anymore. All others have its respective page on the wiki.

As for the discrepancies in compatibility between the forum and the wiki, i'll say give it time till a new test can be done on newer builds of pcsx2, so the status gets updated to a more accurate one. This goes for the goes for the "stubs" as well.

**Comment by bositman** [comment]
We already have a script that does this automatically. Gets the data from the compatibility list and mirrors it on the wiki. We don't run it daily obviously.

**Comment by karasuhebi** [comment]
@ghost: Just wanted to say that it's the PCSX2 wiki, not Wikia. Wikia is a hosting service/network for wikis, which we are not a part of. We host our own wiki.
