### ISSUE TITLE
[BUG]:  LOONEY TUNES - ACME ARSENAL (SLUS 21636) will not boot properly

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5275]
### Describe the Bug

This ticket is created on behalf of "James-Devil" from discord, as it appears he cannot start a new issue while having a new account on GitHub. 

The game appears to freeze during its boot. Works fine in 1.6, broken in 1.7. More specifically:

r680 works, and in r683 it won't. "VIF: Don't start transfer if VIF1/0 is stalled Fix missing VIF status check on MFIFO" (r681) is the suspected culprit.

User should be able to reply to this with any further info if needed.

### Reproduction Steps

Simply launch it.

### Expected Behavior

The game should boot.

### PCSX2 Revision

r2024

### Operating System

Windows 10 (64bit)

### CPU

i7-6700K

### GPU

GTX 1070

### Logs & Dumps

[log.txt](https://github.com/PCSX2/pcsx2/files/7829579/log.txt)

**Comment by prafullpcsx2** [comment]
[looney.zip](https://github.com/PCSX2/pcsx2/files/7829764/looney.zip)

Here is the blockdump.

**Comment by refractionpcsx2** [comment]
Fixed now in master

**Comment by gilderoylockhart01** [comment]
What an unfortunate case, the PAL version does a vif force break but not a reset at the same time which means it had 0 issues.

**Comment by refractionpcsx2** [comment]
It only worked on 1.6 because we ignored the fact that VIF was stalled (due to the break happening after the reset when it was at the same time)
