### ISSUE TITLE
[BUG - Regression]: Silent Hill 2 black ribbon demo: Invalid sector error causing softlock.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5280]
### Describe the Bug

In the video demo "Silent Hill 2 black ribbon", there are 2 trailers playing continuously.

Before the problematic commit, the demo did a bunch of out of bound sector errors when reading the second trailer but did continue regardless.

On master, the software simply dies when doing so with the emulator constantly spamming invalid sector read.

### Reproduction Steps

Load the blockdump + savestate.

### Expected Behavior

The video demo should not crash when reading the second trailer.

### PCSX2 Revision

pcsx2-v1.7.2210-windows-x86

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Window Screenshots

The console log:
![Capture d’écran 2022-01-08 110826](https://user-images.githubusercontent.com/90222976/148640387-f304518f-ccaa-46b8-b925-1f061ffe60fc.png)

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1LsXSmonY7hYjQCrBDytCD6KYGPWAs48K/view?usp=sharing

**Comment by refractionpcsx2** [comment]
The more important error is

isoFile error: Block index is past the end of file! (1421888 >= 1421888).
isoFile error: Block index is past the end of file! (1421889 >= 1421888).
Read past end of disc Sector 1421889 Max Sector 1421888


you sure your ISO isn't broken?

**Comment by combo-pizza** [comment]
I know it's not the same game, but I have a similar error in the intro to mace griffin (U)
isoFile error: Block index is past the end of file! (1279904 >= 1279904).
isoFile error: Block index is past the end of file! (1279905 >= 1279904).

Does that then locks up at the warthog logo while playing the video unless you skip it. (I verified it on redump.org too)

**Comment by refractionpcsx2** [comment]
> I know it's not the same game, but I have a similar error in the intro to mace griffin (U) isoFile error: Block index is past the end of file! (1279904 >= 1279904). isoFile error: Block index is past the end of file! (1279905 >= 1279904).
> 
> Does that then locks up at the warthog logo while playing the video unless you skip it. (I verified it on redump.org too)

intro's are easier to debug, if you could make a blockdump from an older version of the emulator, that could be useful,. but please make another thread for it.

**Comment by gilderoylockhart01** [comment]
The CRC32 is 092ebeb6.

**Comment by refractionpcsx2** [comment]
okay, can you please try this on a real PS2 and confirm for me how the video is supposed to end? I have gotten it to work but the video no longer fades, but I suspect the PS2 will do the same (not that they intended that), but I would like to have real hardware confirm what it does.

**Comment by gilderoylockhart01** [comment]
On real hardware, the first video does fade away when it finishes. Then a few seconds after that, the second trailer also starts with a fade effect.

**Comment by refractionpcsx2** [comment]
Well, that's confused, I don't know how the hell they're managing that.

**Comment by gilderoylockhart01** [comment]
That is worth mentioning OPL doesn't play this demo properly too. I had to play the actual disc on the console for that to work.

**Comment by refractionpcsx2** [comment]
I don't understand how this works on the console... it makes no sense.

**Comment by refractionpcsx2** [comment]
The only way I can replicate the PS2 behaviour is to not throw an error, but surely it should throw a sector error if it tries to access a sector past the end of the disc
