### ISSUE TITLE
[Feature Request]: Namco GunCon2 USB Descriptors 

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5287]
### Description

Information for device USB\Vendor_0B9A_Product_016A:

Connection Information:
------------------------------
Device current bus speed: LowSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x000D
Current configuration value: 0x00
Number of open pipes: 0

Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0100	bcdUSB
0xFF	bDeviceClass      (Vendor specific)
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x0B9A	idVendor
0x016A	idProduct
0x0100	bcdDevice
0x00	iManufacturer
0x00	iProduct     
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x00 0x01 0xFF 0x00 0x00 0x08 0x9A 0x0B 
0x6A 0x01 0x00 0x01 0x00 0x00 0x00 0x01 

Configuration Descriptor:
------------------------------
0x09	bLength
0x02	bDescriptorType
0x0019	wTotalLength   (25 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x19	bMaxPower      (50 mA)
Hex dump: 
0x09 0x02 0x19 0x00 0x01 0x01 0x00 0x80 0x19 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0xFF	bInterfaceClass      (Vendor specific)
0x6A	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x01 0xFF 0x6A 0x00 0x00 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x08	bInterval         (8 frames)
Hex dump: 
0x07 0x05 0x81 0x03 0x08 0x00 0x08 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  
Hex dump: 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x00, 0x01, 0xFF, 0x00, 0x00, 0x08, 0x9A, 0x0B, 
0x6A, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x19, 0x00, 0x01, 0x01, 0x00, 0x80, 0x19, 0x09, 
0x04, 0x00, 0x00, 0x01, 0xFF, 0x6A, 0x00, 0x00, 0x07, 0x05, 
0x81, 0x03, 0x08, 0x00, 0x08

------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
USB\Vendor_0B9A_Product_016A Port: 9

Running on: Windows 10 or greater (Build Version 22526)

Brought to you by TDD v2.15.0, Jun  8 2020, 17:18:07

### Reason

needed for 
https://github.com/PCSX2/pcsx2/issues/3931
https://github.com/PCSX2/pcsx2/issues/4763

### Examples

no examples.

**Comment by IlDucci** [comment]
I'm adding logs of third-party lightguns here, as they're all in GunCon 2 mode.

# Thrustmaster Desert Eagle:

Information for device USB\Vendor_0B9A_Product_016A:

------------------------------
Connection Information:
------------------------------
Device current bus speed: LowSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x000E
Current configuration value: 0x00
Number of open pipes: 0


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0100	bcdUSB
0xFF	bDeviceClass      (Vendor specific)
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x0B9A	idVendor
0x016A	idProduct
0x0100	bcdDevice
0x00	iManufacturer
0x00	iProduct     
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x00 0x01 0xFF 0x00 0x00 0x08 0x9A 0x0B 
0x6A 0x01 0x00 0x01 0x00 0x00 0x00 0x01 


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0019	wTotalLength   (25 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x19	bMaxPower      (50 mA)
Hex dump: 
0x09 0x02 0x19 0x00 0x01 0x01 0x00 0x80 0x19 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0xFF	bInterfaceClass      (Vendor specific)
0x6A	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x01 0xFF 0x6A 0x00 0x00 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x08	bInterval         (8 frames)
Hex dump: 
0x07 0x05 0x81 0x03 0x08 0x00 0x08 

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
Hex dump: 
0x04 0x03 0x09 0x04 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x00, 0x01, 0xFF, 0x00, 0x00, 0x08, 0x9A, 0x0B, 
0x6A, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x19, 0x00, 0x01, 0x01, 0x00, 0x80, 0x19, 0x09, 
0x04, 0x00, 0x00, 0x01, 0xFF, 0x6A, 0x00, 0x00, 0x07, 0x05, 
0x81, 0x03, 0x08, 0x00, 0x08


------------------------------

Connection path for device: 
Controladora de host USB genérico compatible con xHCI
Root Hub
USB\Vendor_0B9A_Product_016A Port: 1

Running on: Windows 10 or greater (Build Version 19041)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

# Logic3 MP5k with blowback:

Information for device USB\Vendor_0B9A_Product_016A:

------------------------------
Connection Information:
------------------------------
Device current bus speed: LowSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0029
Current configuration value: 0x00
Number of open pipes: 0


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0100	bcdUSB
0xFF	bDeviceClass      (Vendor specific)
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x0B9A	idVendor
0x016A	idProduct
0x0100	bcdDevice
0x00	iManufacturer
0x00	iProduct     
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x00 0x01 0xFF 0x00 0x00 0x08 0x9A 0x0B 
0x6A 0x01 0x00 0x01 0x00 0x00 0x00 0x01 


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0019	wTotalLength   (25 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x19	bMaxPower      (50 mA)
Hex dump: 
0x09 0x02 0x19 0x00 0x01 0x01 0x00 0x80 0x19 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0xFF	bInterfaceClass      (Vendor specific)
0x6A	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x01 0xFF 0x6A 0x00 0x00 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x08	bInterval         (8 frames)
Hex dump: 
0x07 0x05 0x81 0x03 0x08 0x00 0x08 

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
Hex dump: 
0x04 0x03 0x09 0x04 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x00, 0x01, 0xFF, 0x00, 0x00, 0x08, 0x9A, 0x0B, 
0x6A, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x19, 0x00, 0x01, 0x01, 0x00, 0x80, 0x19, 0x09, 
0x04, 0x00, 0x00, 0x01, 0xFF, 0x6A, 0x00, 0x00, 0x07, 0x05, 
0x81, 0x03, 0x08, 0x00, 0x08


------------------------------

Connection path for device: 
Controladora de host USB genérico compatible con xHCI
Root Hub
USB\Vendor_0B9A_Product_016A Port: 9

Running on: Windows 10 or greater (Build Version 19041)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

# Thrustmaster Beretta 92FS

This one's not being recognised by Windows. The lightgun still works (I just double checked it in a CRT with my PAL console), but Windows just blurts a "device not recognized" message and the TDD app just shows this:

Information for device USB\Vendor_0000_Product_0000:

------------------------------
Connection Information:
------------------------------
Device current bus speed: LowSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0000
Current configuration value: 0x00
Number of open pipes: 0

Microsoft OS Descriptor is not available. Error code: 0x000001B1


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
------------------------------

Whole unknown Descriptor as hex dump: 


------------------------------

Connection path for device: 
Controladora de host USB genérico compatible con xHCI
Root Hub
USB\Vendor_0000_Product_0000 Port: 9

Running on: Windows 10 or greater (Build Version 19041)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

**Comment by seta-san** [comment]
![20220109_094501](https://user-images.githubusercontent.com/8851653/148690068-334a2206-8196-4256-b33d-43cd9f23cecb.jpg)
![20220109_094544](https://user-images.githubusercontent.com/8851653/148690070-b3b16481-41c9-4270-b517-be65b751c016.jpg)
![20220109_094622](https://user-images.githubusercontent.com/8851653/148690071-47f39aa4-1c15-4f4d-b849-c61d3e20fe7b.jpg)
![20220109_094649](https://user-images.githubusercontent.com/8851653/148690073-7cc90da6-dd39-43d7-8819-02bcb16aac0e.jpg)
![20220109_094659](https://user-images.githubusercontent.com/8851653/148690076-228c68a5-75d8-4cb8-b27a-7cc81a0411a4.jpg)

**Comment by seta-san** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/7534
