### ISSUE TITLE
[Feature Request]: DJ Hero Turntable USB Descriptors

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5288]
### Description

Information for device Guitar Hero5 for PlayStation (R) 3 (VID=0x12BA PID=0x0140):

Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x0010
Current configuration value: 0x01
Number of open pipes: 2

Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0100	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x40	bMaxPacketSize0   (64 bytes)
0x12BA	idVendor
0x0140	idProduct
0x0005	bcdDevice
0x01	iManufacturer   "RedOctane DJ"
0x02	iProduct        "Guitar Hero5 for PlayStation (R) 3"
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x00 0x01 0x00 0x00 0x00 0x40 0xBA 0x12 
0x40 0x01 0x05 0x00 0x01 0x02 0x00 0x01 

Configuration Descriptor:
------------------------------
0x09	bLength
0x02	bDescriptorType
0x0029	wTotalLength   (41 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x19	bMaxPower      (50 mA)
Hex dump: 
0x09 0x02 0x29 0x00 0x01 0x01 0x00 0x80 0x19 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x02	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x02 0x03 0x00 0x00 0x00 

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0110	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0089	bDescriptorLength
Hex dump: 
0x09 0x21 0x10 0x01 0x00 0x01 0x22 0x89 0x00 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)
Hex dump: 
0x07 0x05 0x81 0x03 0x40 0x00 0x0A 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x02	bEndpointAddress  (OUT endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)
Hex dump: 
0x07 0x05 0x02 0x03 0x40 0x00 0x0A 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
Hex dump: 
0x04 0x03 0x09 0x04 

0x01   0x0409  "RedOctane DJ"
Hex dump: 
0x1A 0x03 0x52 0x00 0x65 0x00 0x64 0x00 0x4F 0x00 
0x63 0x00 0x74 0x00 0x61 0x00 0x6E 0x00 0x65 0x00 
0x20 0x00 0x44 0x00 0x4A 0x00 

0x02   0x0409  "Guitar Hero5 for PlayStation (R) 3"
Hex dump: 
0x46 0x03 0x47 0x00 0x75 0x00 0x69 0x00 0x74 0x00 
0x61 0x00 0x72 0x00 0x20 0x00 0x48 0x00 0x65 0x00 
0x72 0x00 0x6F 0x00 0x35 0x00 0x20 0x00 0x66 0x00 
0x6F 0x00 0x72 0x00 0x20 0x00 0x50 0x00 0x6C 0x00 
0x61 0x00 0x79 0x00 0x53 0x00 0x74 0x00 0x61 0x00 
0x74 0x00 0x69 0x00 0x6F 0x00 0x6E 0x00 0x20 0x00 
0x28 0x00 0x52 0x00 0x29 0x00 0x20 0x00 0x33 0x00 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x40, 0xBA, 0x12, 
0x40, 0x01, 0x05, 0x00, 0x01, 0x02, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x29, 0x00, 0x01, 0x01, 0x00, 0x80, 0x19, 0x09, 
0x04, 0x00, 0x00, 0x02, 0x03, 0x00, 0x00, 0x00, 0x09, 0x21, 
0x10, 0x01, 0x00, 0x01, 0x22, 0x89, 0x00, 0x07, 0x05, 0x81, 
0x03, 0x40, 0x00, 0x0A, 0x07, 0x05, 0x02, 0x03, 0x40, 0x00, 
0x0A

------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
Guitar Hero5 for PlayStation (R) 3 (VID=0x12BA PID=0x0140) Port: 9

Running on: Windows 10 or greater (Build Version 22526)

Brought to you by TDD v2.15.0, Jun  8 2020, 17:18:07

### Reason

needed for 
https://forums.pcsx2.net/Thread-DJ-Hero-SLUS-21909-U?pid=623244#pid623244
https://github.com/PCSX2/pcsx2/issues/4763
https://github.com/PCSX2/pcsx2/issues/3924

### Examples

no example

**Comment by seta-san** [comment]
![20220109_094402](https://user-images.githubusercontent.com/8851653/148690143-f6780463-8197-4838-84fa-7f97ca7e0abe.jpg)
![20220109_092555](https://user-images.githubusercontent.com/8851653/148690144-fed194ac-3b9b-4d13-bb23-6fd03a9ba087.jpg)
![20220109_092605](https://user-images.githubusercontent.com/8851653/148690146-8e87f80c-b1d8-4c75-b609-fe9ca73c2f9f.jpg)
![20220109_094325](https://user-images.githubusercontent.com/8851653/148690147-da9953bb-0d6e-48a0-a92b-fa46b6ba03a7.jpg)
![20220109_094350](https://user-images.githubusercontent.com/8851653/148690150-ed2cabdd-d93e-4318-a0a3-11c733e54f73.jpg)

**Comment by lightningterror** [comment]
Added in #9129
