### ISSUE TITLE
[BUG]: Vulkan causes strange flickering issue in most games

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#5296]
### Describe the Bug

In most games I've been able to test, Vulkan causes a strange issue where certain game elements will suffer from large black flickering boxes.  There doesn't seem to be anything in particular it affects, as in Sly 2 it only affects shadows and light sources, while in Katamari Damacy it affects sprites and some 3D models.  Strangely, increasing the internal resolution makes it less noticeable, and increasing Blending Unit makes it more noticeable.  I've tested every setting and nothing fixes this.  It's an issue unique to Vulkan.  No one else I've talked to can reproduce the issue so it might be a hardware or driver difference.

### Reproduction Steps

1.  Switch to Vulkan.

2.  Load any game.

3.  The weird effect will appear the same time every time, but won't affect the same thing in each game.

### Expected Behavior

The effects/sprites/shadows/etc should render properly, or at least as good as they do when using Direct3D11 or OpenGL.

### PCSX2 Revision

v1.7.2212

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 Super

### GS Settings

All settings are default, but the issue gets worse as you increase Blending Unit but also less noticeable as you increase internal resolution.  The attatched logs and visuals used default settings.  Game patches were also disabled.

### Emulation Settings

I used every speedhack except for EE Cyclerate and EE Cycle Skipping which I left default.  I've tried without any speedhacks and the issue persists.

### GS Window Screenshots

It affects shadows and lighting in Sly 2:

https://imgur.com/a/qsHVQIE

It also affects sprites, text, and the Katamari model in Katamari Damacy:

https://imgur.com/a/umxsjrP

It's not as noticeable in MX Unleased but the loading bar kinda flickers which it didn't before:

https://imgur.com/a/GTtK3NV

### Logs & Dumps

emuLog for Sly 2 example:

[emuLogSly2.txt](https://github.com/PCSX2/pcsx2/files/7835347/emuLogSly2.txt)

emuLog for MX Unleased example:

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7835348/emuLog.txt)

emuLog for Katamari Damacy example:

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7835349/emuLog.txt)

I tried to take GSDumps of all these but neither Ctrl + Shift + F8 nor Ctrl + F8 does anything for me.  No, I didn't unbind or rebind anything.

**Comment by refractionpcsx2** [comment]
Please update your Nvidia drivers.

**Comment by SlyCooperReloadCoded** [comment]
Well I'll be.  That actually fixed it!  I thought I had updated them recently, I guess not.
