### ISSUE TITLE
[BUG]: Closing the game window freezes it instead of closing it

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#5298]
### Describe the Bug

Previously, when closing only the game window, it would close properly and the Resume option would become available.  Now whenever I close the game window, it pauses it and the only way I've found to get out of it is to close the entire emulator.  I believe this is unintentional because this often creates a dump file in the main PCSX2 install directory, making me think it's an error dump.

This is how it behaved on 1.6.0 and every 1.7.0 build up until this one:

https://imgur.com/a/A9GIPkh

Here's the issue I'm experiencing:

https://imgur.com/a/RFI1XsI

### Reproduction Steps

1.  Open the emulator.

2.  Launch any game.

3.  Try to close the game window.

### Expected Behavior

The game window should close.

### PCSX2 Revision

v1.7.2212

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
If I press escape once it pauses correctly and if I do it again it resumes. But I've seen it say not responding at times.

**Comment by SlyCooperReloadCoded** [comment]
Well I'm not trying to pause it, plus trying to resume it after this happens doesn't work.

**Comment by refractionpcsx2** [comment]
hmm yeah, it normally functions as you are expecting, but sometimes it seems to hang, not sure what I did but after about 10 seconds it came back to life, I  might have clicked it again, not sure.

**Comment by SlyCooperReloadCoded** [comment]
I've left it there for minutes without it doing anything.  Good to hear this one isn't user error.

**Comment by seta-san** [comment]
Same issue on my end

**Comment by MrCK1** [comment]
@SlyCooperReloadCoded is this still valid, you've deleted your images...

**Comment by SlyCooperReloadCoded** [comment]
Oh sorry about that!  I went on an Imgur cleaning spree, I thought I didn't delete those!  The visuals look exactly like you'd think they would, the issue is still completely described without them.

**Comment by Mrlinkwii** [comment]
Is this still an issue on latest 1.7?

**Comment by SlyCooperReloadCoded** [comment]
I use Qt builds now which of course don't have this issue, but I also keep 1.6.0 up and it doesn't do this, so I can't really say.  If wx isn't staying around forever then does it matter?

**Comment by refractionpcsx2** [comment]
if it's only a wx issue then marking as a wontfix fix WX is being deprecated
