### ISSUE TITLE
justice league

### ISSUE THREAD

**Issue by Infinity-420** [PCSX2/pcsx2#53]
when using the normal plugin setting only half the screen will show during hardware setting but if you use software the full screen will show , using both dx9 and dx 11 ,,, trouble with software setting is it's to slow, tryied playing aroumd w the setting but now success

**Comment by gregory38** [comment]
See PR #545

**Comment by gregory38** [comment]
Please test latest GIT version

**Comment by gregory38** [comment]
Could someone test either the git version or the new PR #545 ?

**Comment by gregory38** [comment]
Nobody tested the game but it must be fixed with latest GIT (snow engine game)

**Comment by karasuhebi** [comment]
I'll see if I can test it tonight.

**Comment by karasuhebi** [comment]
The game loads fine now. The text looks pretty shitty at 6x though.
HW: http://i.imgur.com/H3907xB.png
SW: http://i.imgur.com/MIVtKJ5.png

**Comment by refractionpcsx2** [comment]
is that usinig OpenGL or DX?

**Comment by karasuhebi** [comment]
D3D11. Did you need me to try OGL?

**Comment by refractionpcsx2** [comment]
No i just wondered as the bilinear filtering was a bit weird in OpenGL, figured that could have had impact on the text :p
