### ISSUE TITLE
[BUG]: Auto Modellista hangs when selecting different BGM

### ISSUE THREAD

**Issue by ribolovac510** [PCSX2/pcsx2#5301]
### Describe the Bug

After #5230 Auto Modellista (SLUS-20642) hangs completely when changing BGM tracks in Arcade mode. The music stops and then after a couple of seconds "Read Time Out 15000(msec)" message appears in Program Log. This happens especially if you scroll through tracks fast. It can be somewhat avoided if you switch tracks slowly, let them play for a couple of seconds first before switching, but it's still unreliable and it can hang randomly anyway. This did not happen on older builds.

### Reproduction Steps

Arcade -> Single Race -> Select any race track -> Try changing different BGM tracks

### Expected Behavior

No hangs, being able to change tracks like in the builds before the mentioned PR.

### PCSX2 Revision

v1.7.2218

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7835745/emuLog.txt)

**Comment by refractionpcsx2** [comment]
Will be working again in 1.7.2219

**Comment by ribolovac510** [comment]
Tested it, works nicely again. Thanks a lot! :)
