### ISSUE TITLE
[BUG]: RTSS and PCSX2 x64 frame limiter problem on all backend

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#5303]
### Describe the Bug

I'm using RTSS Scanline Sync with pcsx2 x86 and it's perfect, smooth and almost lagless.

Problem is that it the frame limiter only works correctly with x86.

When launched with x64 builds, it starts detecting the game at a random moment into the game and not from the start.

Is it my config ? I'll gladly open a ticket on their forums if you think it's not related with pcsx2.

### Reproduction Steps

Launch RTSS (whichever detection level) with pcsx2 x64 internal frame limiter disabled

### Expected Behavior

RTSS frame limiter works from the start

### PCSX2 Revision

Every x64 builds

### Operating System

Windows 11

**Comment by Squall-Leonhart** [comment]
Cannot reproduce.

**Comment by Immersion95** [comment]
I forgot to mention that pcsx2 is launched through Steam.

Launching pcsx2x64 normally doesn't produce any bug.

**Comment by Squall-Leonhart** [comment]
RTSS is intentionally delayed for compatibility reasons when the overlay servers of other software are detected.

reshade introduces the same behavior, with the scanline sync not applied until subsequent click into the renderer window.

**Comment by Immersion95** [comment]
You're right, the fix was easy. I only had to change InjectionDelay=0 in the pcsx2 config file inside RTSS.
