### ISSUE TITLE
[BUG]: Kidou Senshi Gundam Seed - Rengou vs. Z.A.F.T- Flickering ground polygon on SW renderer.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5307]
### Describe the Bug

A ground polygon flickers on the first level spawn in the SW renderer. HW renderer handles it correctly.

### Reproduction Steps

Play the first level.

### Expected Behavior

I expected the polygon not to flicker on the SW renderer.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2219 Compiled on Jan 10 2022

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Window Screenshots

SW (incorrect)
![gs_20220106182025](https://user-images.githubusercontent.com/50224630/148765462-2559b3b8-567c-4728-a7f4-512a9918b7cf.png)
HW (correct)
![gs_20220110071939](https://user-images.githubusercontent.com/50224630/148765496-cefd1255-bbc1-4ff1-bdaa-26da0b46ad81.png)

### Logs & Dumps

[gs_20220110072713.gs.zip](https://github.com/PCSX2/pcsx2/files/7838799/gs_20220110072713.gs.zip)

**Comment by refractionpcsx2** [comment]
This was fixed in 1.7.2271 #5377
