### ISSUE TITLE
[BUG]: (Potential?) FpuNegDivHack removals in gamedb

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5308]
### Describe the Bug

I went through and tested the 6 games with the FpuNegDiv gamefix set in the gamedb. It still appears to be necessary for Dakar 2 and The Simpons Hit and Run, but doesn't appear to be necessary for Crazy Frog Racer 2, Gihren's ambition 5, or either gundam seed rengou vs zaft game. However, I say possible here because the two games that still seem to need it are also the only two with clear descriptions of what goes wrong. Crazy Frog 2 just says that it fixes fade to black transitions and menu text, gundam seed just mentions some target loss issue, and gihren 5 doesn't even have a reason listed as for why it's there. So, if it turns out these games do still experience issues, or any developers know more extensively why these hacks were added, please let me know.

Additionally, the eeroundmode for the 2 gundam games can be removed. However, the explanation here is also vague, as it just says "fixes camera issue", so I don't really know what I'm looking for.
The EETimingHack can definitely be removed from Dakar 2, as the videos don't flicker at all.

### Reproduction Steps

Play through games.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2219 Compiled on Jan 10 2022

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

**Comment by refractionpcsx2** [comment]
We just added this hack for Cocoto Funfair #5297 as it is needed for that.

However in future it can be replaced potentially by allowing the FPU rounding to be chop/zero for all (currently DIV/SQRT etc are forced to Nearest, expect with that hack)

**Comment by HeroponRikiBestest** [comment]
Got it. Do you happen to know of any more extensive explanations as to exactly what it's supposed to fix in the 4 aforementioned games, or has it been too long since any of these were added?

**Comment by refractionpcsx2** [comment]
Not a clue, sorry. I'm surprised they no longer require the hack, honestly.

**Comment by HeroponRikiBestest** [comment]
Well, the issue is the opposite, that they don't *seem* to, but I also don't really know what to look for

**Comment by lightningterror** [comment]
Closing as it's still used.
