### ISSUE TITLE
[BUG]: Outrun 2 and Outrun 2006  - Vulkan FPS issues

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5311]
### Describe the Bug

noticable lower FPS in vulkan than opengl.. lower by usually 5-10 and maybe even sometimes 15 fps

### Reproduction Steps

just play the game.

### PCSX2 Revision

1.7.2219

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960 - latest drivers

### GS Settings

![outrunsettings](https://user-images.githubusercontent.com/8851653/148817843-5fc06ed9-e308-4a18-9137-07128343647d.jpg)

Accurate Destination Alpha Test is always off because it's always caused fps issues in this game.

### Emulation Settings

aspect ratio: Widescreen
widescreen hacks on.

**Comment by RedDevilus** [comment]
Same thing for Burnout Dominator. 8x is Vulkan in low 40s and OpenGL has low 50s.

**Comment by F0bes** [comment]
I don't believe that a graphics API performing a **little** worse than another graphics API is an issue. We don't do it for Direct3d and OpenGL.
