### ISSUE TITLE
[BUG]: [Radiata Stories] No character shadows in D3D11 (or Vulcan), framepacing issues in OpenGL

### ISSUE THREAD

**Issue by Arthandas** [PCSX2/pcsx2#5312]
### Describe the Bug

As in the title, the character shadows are displayed only in OpenGL (and software mode). I tried raising the blending accuracy but it changes nothing.

Normally, I wouldn't use anything other than OpenGL but for some reason it exhibits very noticeable framepacing issues. There is small constant microstutter when moving around, despite the fact the game is sitting on rock solid 100% speed. The stutter is gone after switching to D3D11.

Both issues persist even on default settings without changing anything.

### Reproduction Steps

Self explanatory

### PCSX2 Revision

v1.7.2218

### Operating System

Windows 10 (64bit)

### CPU

i5-7500

### GPU

RTX 3060

**Comment by lightningterror** [comment]
If you want to enable shadows on dx11 you need to drop crc hack level to None.

**Comment by lightningterror** [comment]
Vulkan should be good now on auto crc with basic blending, once the new build is up, for frame pacing, there's an issue open already.

**Comment by Arthandas** [comment]
The new build allows shadows only after setting crc to none. Sadly, Vulkan has the same microstutter as OpenGL, so I'm still staying with D3D11 for now.

As for D3D11, setting crc to none brings the game to a crawl without even rendering the shadows properly, there's just a black glitched mass that goes from characters' heads to feet.
