### ISSUE TITLE
[BUG]: Crash when using Cyborg Frieza's Missile Launcher attack in Super Dragon Ball Z.

### ISSUE THREAD

**Issue by jacobv0** [PCSX2/pcsx2#5314]
### Describe the Bug

The emulator will error and crash when using Cyborg Frieza's Missile Launcher attack in Super Dragon Ball Z.

### Reproduction Steps

1. Unlock Cyborg Frieza
2. Create a character card for Cyborg Frieza
3. Level up the character card until you can equip the missile launcher skill
4. Enter Training Mode or any battle and use the Missile Launcher special attack (Forward, Down, Down-Forward + Heavy Attack) until the missile splits.

### Expected Behavior

The emulator will error and crash.

### PCSX2 Revision

pcxs2-git v 1.7.2222

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Manjaro Linux(Based on Arch)

### CPU

Ryzen 3 3200G

### GPU

Radeon RX570

**Comment by kenshen112** [comment]
He's using pcsx2-git so the symbols were scrubbed

**Comment by HeroponRikiBestest** [comment]
Can you please post a memory card save file?

**Comment by jacobv0** [comment]
Sorry for the late reply, here is the [memory card file](https://drive.google.com/file/d/1Y7cdROpvXq35vl9CHnQSzH8iM6q-rCbi/view?usp=sharing).

**Comment by HeroponRikiBestest** [comment]
@jacobv0 I don't have access. Could you please zip the memory card file and post it here, or make the google drive link public?

**Comment by HeroponRikiBestest** [comment]
https://user-images.githubusercontent.com/50224630/149052334-8b4f3072-d4d0-48dd-ae71-22d86807f330.mp4
@jacobv0 the game did not crash for me, is there anything I'm doing differently than you?

**Comment by jacobv0** [comment]
> freezer-2022-01-11_21.20.03.mp4 
> @jacobv0 the game did not crash for me, is there anything I'm doing differently than you?

I think it might have something to do with my gpu strength or something then. I honestly have no idea.

**Comment by HeroponRikiBestest** [comment]
@jacobv0 that shouldn't matter. Press f9 to switch to software mode. Does it still crash?

**Comment by jacobv0** [comment]
> @jacobv0 that shouldn't matter. Press f9 to switch to software mode. Does it still crash?

Yes, it still crashes. this is what the log put out:

# Syscall: undefined (134217728)
GS Lookup CRC:DE2DF62D

**Comment by HeroponRikiBestest** [comment]
@jacobv0 If you put your ISO into https://www.romhacking.net/hash/, what are the results in the `all hashes` section?

**Comment by jacobv0** [comment]
@HeroponRikiBestest 

File SHA1	D0244A34B02E9A93EACCDA25D8173FF935C9BCC6
ROM SHA1	D0244A34B02E9A93EACCDA25D8173FF935C9BCC6
File MD5	306DDAE11236675F2866A2D6761CD494
ROM MD5	306DDAE11236675F2866A2D6761CD494
File CRC32	35855406
ROM CRC32	35855406

**Comment by HeroponRikiBestest** [comment]
Hmm, that's correct. I'm not sure why it's crashing. What stages have you tried it on, and against which character?
Additionally, what non-default settings do you have enabled?

**Comment by jacobv0** [comment]
I've tried it against vegeta and cyborg frieza on the world tournament stage. I have the multicore setting enabled and the graphics settings are all set to fastest but I've tried it multiple times on default presets also.

**Comment by Mrlinkwii** [comment]
Is this still an issue on latest 1.7?

**Comment by jacobv0** [comment]
No, this is no longer an issue, but the game still lags horribly during fights so I may need to upgrade my CPU to play.
