### ISSUE TITLE
[BUG]: Bouken Jidai Katsugeki - Goemon: Wrong resolution, HW renderer renders opening cutscene sky incorrectly.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5315]
### Describe the Bug

On a real PS2, Goemon will constantly switch between 480i and 240p throughout the game, using 240p for outdoor areas, and 480i for indoor areas and menus. (I'm not sure what the first ingame cutscene is supposed to use). However, PCSX2 incorrectly renders the entire game in 240p, with the exception of the opening FMV. Additionally, the sky in the first ingame cutscene is rendered too dark in HW renderers.

### Reproduction Steps

Play the game.

### Expected Behavior

Expected behavior was outlined.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2222 Compiled on Jan 10 2022

### Operating System

Linux (64bit) - Specify Distro Below

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### GS Window Screenshots

Since there isn't really a way to visually show the resolution issue, I'll just post the pictures of the opening cutscene sky.
SW (Correct)
![gs_20220110202831](https://user-images.githubusercontent.com/50224630/148868797-a32ce721-79f1-4632-89ff-d215436cea3d.png)
HW (Incorrect)
![gs_20220110202844](https://user-images.githubusercontent.com/50224630/148868824-213a42f6-1e50-4971-82e7-dd1e1f6bd5c0.png)

### Logs & Dumps

[gooey.zip](https://github.com/PCSX2/pcsx2/files/7843136/gooey.zip)

**Comment by lightningterror** [comment]
This requires maximum blending, also closing in favor of #6755
