### ISSUE TITLE
[BUG]: Intro video not playing in Tony Hawk Project 8

### ISSUE THREAD

**Issue by PipoCrazy** [PCSX2/pcsx2#5318]
### Describe the Bug

The intro videos are not played at all. The screen looks black, but there´s audio.

You can press X several times to jump directly to the menu and it will work. What´s weird, is that the video that plays in the menu after 10 secs of not touching the joystick plays ok.

### Reproduction Steps

Play the game and there will be a black screen until the menu appears.

### Expected Behavior

It should show the video. PCSX 1.6.0 plays it perfectly.

### PCSX2 Revision

v1.7.2222

### Operating System

Windows 10 (64bit)

### CPU

I5-4570

### GPU

AMD RX 580 4GB

### GS Settings

![GSSETTINGS](https://user-images.githubusercontent.com/56910468/148884437-28a48c7b-e42f-4868-a98e-b399f7b50172.jpg)

### Logs & Dumps

https://1drv.ms/u/s!AsU5boCkoC5ehmvt-lWTduoB1PaZ?e=fdIiWH

Program Log:  https://file.io/hcPFV6jUjkhZ

"--- MOVIES¥bsky256.STM not found in PRE
--- MOVIES¥bsky256.STM not found in PRE
--- MOVIES¥bsky256.STM not found in PRE" Probably this?

**Comment by Mrlinkwii** [comment]
Do you happen to know what 1.7 version this issue started to happen on @PipoCrazy ?

**Comment by refractionpcsx2** [comment]
as far as I'm aware, it does play, you just can't see it in hardware mode. press F9 and it will appear

**Comment by PipoCrazy** [comment]
> Do you happen to know what 1.7 version this issue started to happen on @PipoCrazy ?

No, I have tested only two versions of 1.7, since I recently came back to  play PCSX2.

@refractionpcsx2 Sorry, I think I´ve just fixed it.

**Comment by coornio** [comment]
More specifically, something isn't triggering right. You can switch to software mode to get the videos to appear, then immediately switch back to hardware mode and they'll all continue playing without problems. Seems like a minor regression happened somewhere.

**Comment by liamharper2453** [comment]
This issue seems to have been introduced in c41cf6c444daa779e35bb207e4c01a7904648b6c. Removing default init allows cutscene to work again. Out of my depth on actually doing proper fix though!

**Comment by F0bes** [comment]
So it's relying on whatever random junk m_end_block will be 🥴

**Comment by liamharper2453** [comment]
> So it's relying on whatever random junk m_end_block will be 🥴

m_end_block = 3452816845 to be exact, lol.

**Comment by liamharper2453** [comment]
> More specifically, something isn't triggering right. You can switch to software mode to get the videos to appear, then immediately switch back to hardware mode and they'll all continue playing without problems. Seems like a minor regression happened somewhere.

Don't even need to go hardware -> software. Changing hardware renderer to something else will fix it, remains fixed when you go back to hardware renderer you started with

**Comment by PipoCrazy** [comment]
> This issue seems to have been introduced in [c41cf6c](https://github.com/PCSX2/pcsx2/commit/c41cf6c444daa779e35bb207e4c01a7904648b6c). Removing default init allows cutscene to work again. Out of my depth on actually doing proper fix though!

Even though I know the basics of C#, I have no idea about how to fix the issue. I know practically nothing about C++, and even much less about the way the emulator is built.

Is it fixable without screwing up other games? Should it be released as a patch and applied specifically to this game?

**Comment by F0bes** [comment]
> > This issue seems to have been introduced in [c41cf6c](https://github.com/PCSX2/pcsx2/commit/c41cf6c444daa779e35bb207e4c01a7904648b6c). Removing default init allows cutscene to work again. Out of my depth on actually doing proper fix though!
> 
> Even though I know the basics of C#, I have no idea about how to fix the issue. I know practically nothing about C++, and even much less about the way the emulator is built.
> 
> Is it fixable without screwing up other games? Should it be released as a patch and applied specifically to this game?

A more thorough investigation as to why that commit breaks this game would necessary. Adding a patch that sets it to some random number is not going to be accepted.

**Comment by liamharper2453** [comment]
> > > This issue seems to have been introduced in [c41cf6c](https://github.com/PCSX2/pcsx2/commit/c41cf6c444daa779e35bb207e4c01a7904648b6c). Removing default init allows cutscene to work again. Out of my depth on actually doing proper fix though!
> > 
> > 
> > Even though I know the basics of C#, I have no idea about how to fix the issue. I know practically nothing about C++, and even much less about the way the emulator is built.
> > Is it fixable without screwing up other games? Should it be released as a patch and applied specifically to this game?
> 
> A more thorough investigation as to why that commit breaks this game would necessary. Adding a patch that sets it to some random number is not going to be accepted.

From what I can see so far its because this returns false when it shouldn't:

bool GSTextureCache::Surface::Inside(u32 bp, u32 bw, u32 psm, const GSVector4i& rect)
{
	// Valid only for color formats.
	u32 const end_block = GSLocalMemory::m_psm[psm].info.bn(rect.z - 1, rect.w - 1, bp, bw);
	return bp >= m_TEX0.TBP0 && end_block <= m_end_block;
}

Which in turn means the below doesn't run:

// FIXME: this code "fixes" black FMV issue with rule of rose.
#if 1
				// Greg: I'm not sure the 'bw' equality is required but it won't hurt too much
				//
				// Ben 10 Alien Force : Vilgax Attacks uses a small temporary target for multiple textures (different bw)
				// It is too complex to handle, and purpose of the code was to handle FMV (large bw). So let's skip small
				// (128 pixels) target
				if (bw > 2 && t->m_TEX0.TBW == bw && t->Inside(bp, bw, psm, rect) && GSUtil::HasCompatibleBits(psm, t->m_TEX0.PSM))

For the end_block <= m_end_block check at the end of Inside, as the FMV starts to play end_block is populated with a value of over 0 (seems to be consistent. can't remember off hand but was something like 56xx and 67xx) so as we now init as 0 and that hasn't changed still the function returns false. You can arbitrarily init m_end_block as 7000 or something dumb and this function will return true, the FMV code fix will run and FMV will show ok. Would make sense it worked before as uninitialised variable probably had value that was > end_block and passed this check.

**Comment by iMineLink** [comment]
Seems to work in #5419, can you confirm?

**Comment by refractionpcsx2** [comment]
sorry @iMineLink , no dice.

**Comment by lightningterror** [comment]
Maybe worth adding Preload Frame as an alternative workaround for now?
