### ISSUE TITLE
[BUG]: Boxing Champions/Simple 2000 Vol 7 The Boxing - Character Texture Bug

### ISSUE THREAD

**Issue by kim-sama** [PCSX2/pcsx2#5319]
### Describe the Bug

Characters have issues with some textures. One character Legend is chrome but he's completely black

### Reproduction Steps

![gs_20220111150427](https://user-images.githubusercontent.com/40289574/148891963-9cdc691e-440a-460c-a6e1-3b1574de519e.png)
![gs_20220111151754](https://user-images.githubusercontent.com/40289574/148891975-9bee5e4b-b5ed-468e-b469-93d6830ef187.png)
![gs_20220111152246](https://user-images.githubusercontent.com/40289574/148891983-f5bb118e-ac71-4d40-a0ee-d323b7f00722.png)

### Expected Behavior

Screenshots from real hardware
![bc1](https://user-images.githubusercontent.com/40289574/148892495-23bd65f9-d4f9-4cb4-b00a-c82cea55e82d.jpg)
![bc2](https://user-images.githubusercontent.com/40289574/148892504-dea8bae3-9e9b-43d0-9f47-d5173c809cdb.jpg)
![bc3](https://user-images.githubusercontent.com/40289574/148892506-a8f9adcf-f68e-4905-8592-e7d1e17fff25.jpg)

### PCSX2 Revision

1.7.2212

### Operating System

Windows 10 (64bit)

### CPU

i7 10th Gen

### GPU

RTX 2060

### GS Settings

Default settings

### Emulation Settings

Speed hacks off, no game fixes. EE/IOP and VU's are default. Vulkan render with no hacks.

**Comment by PipoCrazy** [comment]
Are the left figher´s nipples green in the original game?

**Comment by kim-sama** [comment]
Nope

**Comment by gilderoylockhart01** [comment]
This is one situation where producing a blockdump of the game would help us finding what the problem is.

**Comment by kim-sama** [comment]
What's that?

**Comment by Mrlinkwii** [comment]
@kim-sama  when #5378 builds can you check it :slightly_smiling_face:
