### ISSUE TITLE
[BUG]: Graphical issues in Ape Escape 2 [SLUS-20685] when full mipmapping is enabled

### ISSUE THREAD

**Issue by liamharper2453** [PCSX2/pcsx2#5320]
### Describe the Bug

Graphical issues occur in Ape Escape 2 on both DX11 and Vulcan when mipmapping is set to full.

### Reproduction Steps

1. Start new game of Ape Escape 2 and enter first level
2. Observe behaviour in below video

### Expected Behavior

The below graphical issues should not occur when full mipmapping is enabled.

### PCSX2 Revision

v1.7.2224

### Operating System

Windows 11

### CPU

i7-7700k

### GPU

GTX 1080ti

### GS Settings

Mipmapping set to full.

### GS Window Screenshots

Vulkan:

https://user-images.githubusercontent.com/25060863/148950938-08cebda2-aa3a-4ec1-9daf-4fc4113dd4e2.mp4

DX11:

https://user-images.githubusercontent.com/25060863/148953147-802362e9-9759-48a9-8cd8-d59af9d5ee3d.mp4

### Logs & Dumps

[Ape Escape 2 issue #5320.gs.zip](https://github.com/PCSX2/pcsx2/files/7847322/Ape.Escape.2.issue.5320.gs.zip)

**Comment by and468860** [comment]
well test game version v1.7.22 24 dx11 and vulkan as my graphics card nvida 1050 drivers 441.87 already old and not game graphics bug

**Comment by liamharper2453** [comment]
> well test game version v1.7.22 24 dx11 and vulkan as my graphics card nvida 1050 drivers 441.87 already old and not game graphics bug


Your drivers are 2 years old. Latest is 497.29.

**Comment by Venom3500** [comment]
G

**Comment by TransparentBlue** [comment]
Try, 
https://github.com/PCSX2/pcsx2/issues/869#issuecomment-1009769628

I just went through the whole game and besides the underwater / Lost Valley full screen effect it's basically the same as software.

**Comment by jeremybris** [comment]
I think #5290 is the regression. You can test this build slightly before https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.2218&platform=windows-x86 to confirm, maybe?

**Comment by liamharper2453** [comment]
> I think #5290 is the regression. You can test this build slightly before https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.2218&platform=windows-x86 to confirm, maybe?

Yeah looks like it to me
