### ISSUE TITLE
[BUG]: Super Dragon Ball Z - HW Mode far more intensive than SW 

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5325]
### Describe the Bug

On a very empty arena, both OpenGL and Vulkan run about ~50fps for me, wheras Software runs ~135fps with the standard 2 additional rendering threads.

### Reproduction Steps

Play the game.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2225 Compiled on Jan 11 2022

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Integrated graphics, see above

### Logs & Dumps

[gs_20220112054351.gs.zip](https://github.com/PCSX2/pcsx2/files/7853896/gs_20220112054351.gs.zip)

**Comment by refractionpcsx2** [comment]
lightning terror looked in to this, and the game does a stupid thing which is pointless, but it wrecks the emulation speed.

The only real solution is to create a patch for performance, I don't really want to modify the code, but to do so, I'll need a blockdump of the game to work from.

**Comment by lightningterror** [comment]
Alternatively you can set Blending to Minimum for the game.

**Comment by lightningterror** [comment]
Related #3183
I'll close this as it seems there's nothing we can do, also Vulkan will run much faster.
