### ISSUE TITLE
[Feature Request]: Logitech Netplay Keyboard USB Descriptors

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5329]
### Description

Information for device NetPlay Keyboard (VID=0x046D PID=0xC30B):

------------------------------
Connection Information:
------------------------------
Device current bus speed: LowSpeed
Device supports USB 1.1 specification
Device supports USB 2.0 specification
Device address: 0x001C
Current configuration value: 0x01
Number of open pipes: 1

------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0110	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x046D	idVendor
0xC30B	idProduct
0x0133	bcdDevice
0x01	iManufacturer   "Logitech"
0x02	iProduct        "NetPlay Keyboard"
0x00	iSerialNumber
0x01	bNumConfigurations
Hex dump: 
0x12 0x01 0x10 0x01 0x00 0x00 0x00 0x08 0x6D 0x04 
0x0B 0xC3 0x33 0x01 0x01 0x02 0x00 0x01 

-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0022	wTotalLength   (34 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0xA0	bmAttributes   (Bus-powered Device, Remote-Wakeup)
0x32	bMaxPower      (100 mA)
Hex dump: 
0x09 0x02 0x22 0x00 0x01 0x01 0x00 0xA0 0x32 

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x01	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x01	bInterfaceSubClass   
0x01	bInterfaceProtocol   
0x00	iInterface
Hex dump: 
0x09 0x04 0x00 0x00 0x01 0x03 0x01 0x01 0x00 

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0110	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0041	bDescriptorLength
Hex dump: 
0x09 0x21 0x10 0x01 0x00 0x01 0x22 0x41 0x00 

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0008	wMaxPacketSize    (1 x 8 bytes)
0x18	bInterval         (24 frames)
Hex dump: 
0x07 0x05 0x81 0x03 0x08 0x00 0x18 

Microsoft OS Descriptor is not available. Error code: 0x0000001F

--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
Hex dump: 
0x04 0x03 0x09 0x04 

0x01   0x0409  "Logitech"
Hex dump: 
0x12 0x03 0x4C 0x00 0x6F 0x00 0x67 0x00 0x69 0x00 
0x74 0x00 0x65 0x00 0x63 0x00 0x68 0x00 

0x02   0x0409  "NetPlay Keyboard"
Hex dump: 
0x22 0x03 0x4E 0x00 0x65 0x00 0x74 0x00 0x50 0x00 
0x6C 0x00 0x61 0x00 0x79 0x00 0x20 0x00 0x4B 0x00 
0x65 0x00 0x79 0x00 0x62 0x00 0x6F 0x00 0x61 0x00 
0x72 0x00 0x64 0x00 

------------------------------

Whole Device Descriptor as hex dump: 
0x12, 0x01, 0x10, 0x01, 0x00, 0x00, 0x00, 0x08, 0x6D, 0x04, 
0x0B, 0xC3, 0x33, 0x01, 0x01, 0x02, 0x00, 0x01

Whole Configuration Descriptor as hex dump: 
0x09, 0x02, 0x22, 0x00, 0x01, 0x01, 0x00, 0xA0, 0x32, 0x09, 
0x04, 0x00, 0x00, 0x01, 0x03, 0x01, 0x01, 0x00, 0x09, 0x21, 
0x10, 0x01, 0x00, 0x01, 0x22, 0x41, 0x00, 0x07, 0x05, 0x81, 
0x03, 0x08, 0x00, 0x18

------------------------------

Connection path for device: 
USB xHCI Compliant Host Controller
Root Hub
NetPlay Keyboard (VID=0x046D PID=0xC30B) Port: 9

Running on: Windows 10 or greater (Build Version 22526)

Brought to you by TDD v2.17.0, Feb 23 2021, 14:04:02

### Reason

needed for
https://github.com/PCSX2/pcsx2/issues/4763#

### Examples

none

**Comment by seta-san** [comment]
![s-l1600 (6)](https://user-images.githubusercontent.com/8851653/149222703-1cbfdc41-1c25-4413-abc8-6833fa9e2181.jpg)
![s-l1600 (3)](https://user-images.githubusercontent.com/8851653/149222707-ec811beb-6c31-441a-8842-e306e64bbfaf.jpg)
![s-l1600 (4)](https://user-images.githubusercontent.com/8851653/149222708-2b56e31c-f64b-404a-a863-867118bbff4d.jpg)
![s-l1600 (5)](https://user-images.githubusercontent.com/8851653/149222712-8d9aa3ca-898c-4fd5-a6d1-5c440eee1c6c.jpg)

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/149223293-8c00056f-f764-445c-9c06-372f9bbf7ff9.png)
Seems they can slot in a weird controller.

**Comment by seta-san** [comment]
Yes. But the controller is just a pad device.

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/149229355-fddcfd61-a88c-45d0-9906-7badc9b02d20.png)

**Comment by Florin9doi** [comment]
These details are easily accessible for common devices : https://github.com/linuxhw/LsUSB/blob/ce17f82eb772b89e87bbd6b45202932bf64bb2cc/Desktop/ASUSTek%20Computer/PRIME/PRIME%20B350-PLUS/5568100AC20D/UBUNTU-18.04/4.15.0-34-GENERIC/X86_64/E2D2B150A5#L97

**Comment by seta-san** [comment]
Yeah. It is really just a common pad and keyboard device locked into a novel physical configuration

**Comment by seta-san** [comment]
i'm okay with this being closed too with a won't fix. the USB device is nothing but a standard keyboard. we already emulate keyboards. it's just here for completeness and documentation.
