### ISSUE TITLE
[BUG]: Harry Potter and the Chamber of Secrets - Visual Artefacts on Vulkan

### ISSUE THREAD

**Issue by deepdive93** [PCSX2/pcsx2#5331]
### Describe the Bug

Visual artefacts appear on certain textures according to the camera angle and/or when Harry casts a spell.

![Immagine 2022-01-13 005515](https://user-images.githubusercontent.com/88136779/149243553-a4697c48-fd4d-40c5-90fa-a56af36a3209.png)
![Immagine 2022-01-13 004555](https://user-images.githubusercontent.com/88136779/149243576-7f43fe7f-0b20-4739-ba83-2c2e1354f00c.png)

Please look at the black spots on the right side:

![Immagine 2022-01-13 004733](https://user-images.githubusercontent.com/88136779/149243591-3a7e770e-81df-4dcc-8421-b85fda744bbc.png)

### Reproduction Steps

Set the renderer on Vulkan and play the game. You'll start noticing the issue a few seconds after going ingame.
Here's the settings I used:
![Immagine 2022-01-13 010146](https://user-images.githubusercontent.com/88136779/149243867-4fc41f6b-9b8f-478e-8c2a-a74be5bbea3e.jpg)
![Immagine 2022-01-13 010216](https://user-images.githubusercontent.com/88136779/149243873-3774b670-7ce4-433f-9605-9c85a74965ef.jpg)

### Expected Behavior

The artefacts should not appear under any circumstance.

### PCSX2 Revision

v1.7.2225

### Operating System

Windows 10 (64bit)

### CPU

i5-9300H

### GPU

GTX 1650

### GS Settings

![Immagine 2022-01-13 012708](https://user-images.githubusercontent.com/88136779/149245045-8dd21fd4-d66e-428b-a443-d798136fe5a9.jpg)

### Emulation Settings

![Uploading Immagine 2022-01-13 012752.jpg…]()

### GS Window Screenshots

![Immagine 2022-01-13 012809](https://user-images.githubusercontent.com/88136779/149245071-355470e1-2e8d-43ac-b59e-f34c0edfa157.jpg)

**Comment by lightningterror** [comment]
Can you post a gsdump?

**Comment by Squall-Leonhart** [comment]
These require a adjustment to some vk fences to fix iirc

Cemu was plagued by the same issue under waterfalls
![unknown 1](https://user-images.githubusercontent.com/1098176/149631941-a796ae91-5c5f-40ea-831c-a09d6e3e17e8.png)

**Comment by coornio** [comment]
I am unable to replicate this behavior in any way no matter what settings I try, or even when I follow the exact setup deepdive93 posted. I'm on the NTSC version of this title, but I'm not sure if it should make any difference here. 

I tested using r.2243 so perhaps one of the updates took care of whatever caused this. @deepdive93 if you could possibly re-check, just to be sure? If it's still present, can you clarify whether you're on a 32bit or 64bit build, and whether it's the SSE4 or AVX2 one? In theory they should all be the same but I'd like to double-check on my side.

**Comment by deepdive93** [comment]
@coornio I still experience the issue using r.2243 AVX2 64bit, same settings as above.

**Comment by coornio** [comment]
@deepdive93 Can you also confirm whether you're on the latest NVIDIA driver? IIRC anything beneath 497 is buggy with Vulkan.

**Comment by deepdive93** [comment]
@coornio You were right, updating the Nvidia driver fixed the issue! I'm still using r.2243 AVX2 64bit.

**Comment by refractionpcsx2** [comment]
So this is resolved?

**Comment by deepdive93** [comment]
By the looks of it, I guess it is resolved.

![Immagine 2022-01-16 163250](https://user-images.githubusercontent.com/88136779/149666605-1e9aac46-902c-4184-a488-16aded5c82d3.png)

**Comment by refractionpcsx2** [comment]
Enjoy
