### ISSUE TITLE
[BUG]: Some games produce constant low audio tone when there's no game audio

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#5337]
### Describe the Bug

For some time now, starting well before 1.6.0 stable, some games like SSX 3 and Midnight Club 3 will produce a constant, low tone in places where there is no game audio whatsoever.  It's one of those sounds that's almost not there but still hurts your ears.  Windows 10's Volume Mixer will show a constant sound in these cases, and recording software like OBS and Bandicam will also pick it up and record it.  This tone can get louder over time.

Me and some friends have tried this on countless computers and it always happens, so it's probably not a hardware issue or a driver-specific issue.  Only some games do it though, that's what's so problematic about it.

### Reproduction Steps

1.  Launch any of the affected games (I've only found SSX 3 and Midnight Club 3 to do this).

2.  Go to a point in the game where there's no game audio, the pause menus for example.

3.  The constant tone will start to come out of PCSX2.

### Expected Behavior

In places where there is no game audio, there should be no game audio.

### PCSX2 Revision

v1.7.2233

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 Super

### GS Settings

This issue is independent of GS or emulation settings, it will happen regardless, the only fix being disabling audio which isn't a real fix.

### GS Window Screenshots

![1](https://user-images.githubusercontent.com/58268914/149435325-711696bf-aa68-4ffc-8ca9-fc2786e26b83.PNG)
![2](https://user-images.githubusercontent.com/58268914/149435342-abd49448-8a4f-467b-a3cf-1c9f4ae8d183.PNG)
![3](https://user-images.githubusercontent.com/58268914/149435346-6e2ceac6-e0f1-467f-a4b2-d15fab2d1740.PNG)

**Comment by Ziemas** [comment]
![2022-01-14-15:22:23](https://user-images.githubusercontent.com/5276694/149532118-f99c543c-708b-4d3c-92b8-d0c945a1d025.png)
Seems to be DC offset in the SSX case at least, didn't look into why yet.

**Comment by Ziemas** [comment]
When opening the pause menu SSX pauses a few voices by setting their pitch to 0 which means they'll constantly output the same value. And since they volume is still turned up it will pass through to the output.

IDK if the SPU does anything the prevent this from resulting in offset in the output, this might possibly happen on hardware as well.

**Comment by refractionpcsx2** [comment]
> When opening the pause menu SSX pauses a few voices by setting their pitch to 0 which means they'll constantly output the same value. And since their volume is still turned up it will pass through to the output.
> 
> IDK if the SPU does anything the prevent this from resulting in offset in the output, this might possibly happen on hardware as well.

is it not possible the sample is cleared when it is output and because the pitch is 0 a new sample is not added?

**Comment by Ziemas** [comment]
Yeah, I intend to test this at some point.

**Comment by RedDevilus** [comment]
Phoenix game Myth Makers Super Kart GP also does weird sounds on the pause screen like car sounds.

**Comment by SlyCooperReloadCoded** [comment]
Bit of an update to this - it extends to other emulators.  All SSX games do this, period, emulator-independent.  Both SSX Tricky and SSX 3 do this on Dolphin too.  Basically what's going on is a poor implementation of muting.  Instead of stopping audio playback, it sets the hardware volume of the muted channels to 0.  This info is coming from someone who's reverse-engineering the SSX games.  Real hardware does this too but handles it a lot better.

I hope this is a substantial lead.

**Comment by Mrlinkwii** [comment]
can this be check on latest mater ?

**Comment by SlyCooperReloadCoded** [comment]
Yes, this is still an issue for all games that do this.
