### ISSUE TITLE
Linux cheat folder doesn't have a home dir fallback like cheat_ws

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#534]
The Cheats folder ('/usr/games/cheats') is inaccessible. Skipping...
Not found Cheats file: /usr/games/cheats/E8FCF8EC.pnach
Overall 0 Cheats loaded
Found Widescreen hacks file: 'E8FCF8EC.pnach'
Loaded 5 Widescreen hacks from 'E8FCF8EC.pnach' at '/home/i30817/.config/PCSX2/cheats_ws'
Overall 5 Widescreen hacks loaded

It still tries to look exclusively on /usr, but it should also look in ~/.config like the widescreen hacks.

Well anyway, this can be worked around easily by ~~2~~ 1 way, using ~~$HOME/.local or~~ adding the cheat we want to the widescreen hack file, but just letting you know.

**Comment by gregory38** [comment]
Feel free to have a look

**Comment by avih** [comment]
While this seems like a Linux directories issue and I'm not familiar with the PCSX2 folders on Linux, `cheats_ws` doesn't really have a "fallback".

Since these are wide screen cheats, and PCSX2 is distributed of a bunch of those, then if widescrreen cheats are enabled and no user ws patch exists, then it tries to look for a ws cheat which was distributed together with PCSX2 (cheats_ws.zip).

So it's really a matter of reverting to use an internal patch rather than fallback location which the user could use (though it can be abused by modifying this zip).

**Comment by turtleli** [comment]
I guess it should only look in $HOME, so I agree with what's been said at http://forums.pcsx2.net/Thread-Cheats-on-linux . There shouldn't be fallback behaviour.

**Comment by tiagoplacido** [comment]
FYI the file cheats_ws.zip that avih mentioned is located on another system folder with the gameindex.dbf on "/usr/share/games/PCSX2/"

**Comment by gregory38** [comment]
I think it just a wrong call to GetUserLocalDataDir/GetUserDataDir/GetDataDir (or others similar name) (another likely hypothesis is that I put the wrong dir on purpose, don't use cheat here).

**Comment by i30817** [comment]
The trouble with the idea of not having a fallback/merging is that the install folders are (rightfully) not user writable. You need root permissions to even use cheats with pcsx2 in linux!

**Comment by turtleli** [comment]
My suggestion was to search for cheats only in home, not in /usr.

**Comment by gregory38** [comment]
The trick is you can't install directly the default cheats. (Well I'm not sure default cheats are useful anyway).

**Comment by avih** [comment]
For historic reasons, on Windows, there's a cheats folder at the installation folder of PCSX2, however, in general, the `cheats` and `cheats_ws` folders belong to the user, where she could put any cheats she wants without affecting other users. The `cheats_ws.zip` file is to be considered part of PCSX2 itself and thus not user modifiable.

@gregory38 there are no default cheats. There are only default widescreen cheats at the `cheats_ws.zip` file. There is one _sample_ cheat at the default cheats folder - `DE37E046.pnach`, but it's there only to be used as a sample and nothing more.

**Comment by avih** [comment]
So the location of the cheats folder should be analogous to the location of the ws_cheats folder, and both should be under the user's control. On top of that, for widescreen patches, PCSX2 also looks at its builtin set of patches at the zip file.

**Comment by turtleli** [comment]
Hmm. They're currently different on the non-portable version for Windows.

**Comment by avih** [comment]
Are you sure they're different? or only that cheats has an extra folder at the PCSX2 install dir (with that sample patch)?

**Comment by turtleli** [comment]
They're different, at Documents/PCSX2 there's a cheats_ws folder but not a cheats folder.

**Comment by avih** [comment]
It's a bit of a mess, since in order to install that sample patch, for historic reasons, the cheats folder with this sample patch is included with the pcsx2 distribution, so it ends at the installation folder, but there should be a cheats folder also at the user docs folder.

Maybe there's a bug there, but the PCSX2 folders management in general is quite a mess, due to the different install modes (portable/install), importing previous configs, etc.

I don't use cheats (I do use the distributed widescreen patches though), and I always use the portable installation, so maybe we have a bug with the cheats folder also on windows.

**Comment by avih** [comment]
What if you manually create a cheats folder at the documents folder? Does PCSX2 looks for patches there?

**Comment by turtleli** [comment]
I suspect it doesn't from the Linux behaviour, but I'll have to find out for sure later.

**Comment by tiagoplacido** [comment]
creating a cheats folder at ~/.config/PCSX2 doesn't work
It still looks for them on /usr/games

**Comment by avih** [comment]
Assuming there's a bug, IMO a good approach to handle it would be:
1. Remove the cheats folder from the repo and keep the sample patch asside.
2. Make the cheats path resolution (and dir creation) identical to cheats_ws except the zip fallback.
3. create an extra subfolder at the repo, maybe `data` and put the sample cheat file in that dir to be installed with PCSX2 (like the langs and docs folders + content).
4. On installation, or when creating (but only once) the cheats folder, copy the sample patch from the built-in data dir.

**Comment by i30817** [comment]
That works, and the work can be built on to allow to select on a GUI unselected cheat_ws cheats in the future (like the mentioned blur removal patches), or to distribute a canonical cheat.zip if you want to..

**Comment by turtleli** [comment]
It's definitely looking at the wrong directory for both Windows and Linux.

On 4 - On Linux, I think placing it in /usr/share/games/PCSX2/, same as cheats_ws.zip or wherever the distro wants it is probably sufficient. Not sure about Windows.

I'll do 2 first since that's an immediate usage issue.

**Comment by i30817** [comment]
/usr/share is not world writable. Really all the stuff not in $HOME should be assumed read only, which means that files the user is expected to manipulate should only go there as backups or defaults. That's why i proposed shadowing, which is already happening with cheats_ws anyway.

**Comment by gregory38** [comment]
Yes, On linux it must be placed on $HOME config data. ($XDG_CONFIG/PCSX2 or $HOME/.PCSX2)

**Comment by turtleli** [comment]
I wasn't very clear. I meant the sample cheat should be put there as part of the package like cheats_ws.zip if it's the install version. I should type more. A lot more.

**Comment by avih** [comment]
I don't it helps is the sample cheat is inside a zip. The goal is (was?) to be a sample file at a location which the user can edit it and expect it to take effect.

I think that for the sake of this bug, we should ignore the existence of the sample cheat, and get back to think if we still want it once the other issues are resolved.

The sample cheat just adds noise to the discussion (even if initially it added some info on why it's there).

**Comment by turtleli** [comment]
The cheats path resolution should work fine on the latest git for both install and portable mode (same as cheats_ws directory minus the zip fallback).

I'm not sure how useful the sample cheat is but I don't really use cheats myself, so perhaps someone who does use cheats could tell me how useful it is.

**Comment by willkuer** [comment]
I use it regularly to create pnachs for the forum since I never remember the correct order, address and value length and how comments work. But possibly I have a malfunctioning brain...

**Comment by gregory38** [comment]
What is the current status of this issue?

**Comment by avih** [comment]
Unless someone has a plan to add the sample cheat file and choose a folder to place it at, IMO we can close this.

**Comment by turtleli** [comment]
I think it can be closed too. The cheat path was fixed, and the fallback idea can't be considered unless someone adds functionality to enable/disable cheats on an individual basis (without writing to the files).

**Comment by gsingh93** [comment]
I'm a little confused reading over this issue. The current cheat directory for me is `/usr/bin/cheats`, am I actually expected to put my cheats there?

**Comment by turtleli** [comment]
@gsingh93 It should not be looking there. I assume PCSX2 isn't configured correctly on your system since the cheats folder path should have been correct since 55eebb5, and there's no indication that it's broken. If you need support, it's better to ask at the forums (make sure to provide how you compiled/where you obtained PCSX2 from).
