### ISSUE TITLE
[BUG]: SNK vs. Capcom - SVC Chaos (Japan) - Wrong interlacing behavior

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#5344]
### Describe the Bug

SVC Chaos has weird artefacts that weren't there in older builds (months ago).

It is even there when the interlacing method is set to none.

Previously is was displaying as progressive without doing anything (same behavior as Neo-Geo Battle Coliseum for example).

For now, the solution is to launch the progressive mode inside the game - X + Triangle at startup (the game doesn't have any confirmation menu).

### Reproduction Steps

Launch game with the newest build - Interlacing set to auto or none and in Software renderer (this game doesn't have menus is HW).

### Expected Behavior

Displays as progressive

### PCSX2 Revision

1.7.2237

### Operating System

Windows 11

### CPU

Ryzen 5600x

### GPU

AMD 6800

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![gs_20220116115945_(2)](https://user-images.githubusercontent.com/47425204/149657356-b1f56bfb-ddce-4556-99f9-92d58fbd70f9.png)

**Comment by MrCK1** [comment]
Please post a GS dump of the issue.

**Comment by Immersion95** [comment]
Sorry, here it is.
[gs_20220116142155.zip](https://github.com/PCSX2/pcsx2/files/7877020/gs_20220116142155.zip)

**Comment by refractionpcsx2** [comment]
is it resolved?

**Comment by Immersion95** [comment]
There is no artefact anymore but it is still interlaced though. I need to force progressive inside the game at startup.
