### ISSUE TITLE
[BUG]: Ratchet and Clank Up your Arsenal: Aquatos underwater effect not rendering properly in the hardware render.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5348]
### Describe the Bug

In the game "Ratchet and Clank Up your arsenal", there is a bug with the hardware render causing the underwater effects in aquatos to not be rendered properly.

### Reproduction Steps

Load the GSdump and see the problem.

### Expected Behavior

The hardware render should not have strange graphics problems in that portion of the game.

### PCSX2 Revision

v1.7.2242-1-g8db0b5282

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

Fast texture invalidation to avoid bizzare problems with disapearing graphics in that same level when using the pause menu.

### GS Window Screenshots

The bug in action:

Hardware render:
![ratchet](https://user-images.githubusercontent.com/90222976/149664796-e8f10da0-dc63-4b69-b7af-d03e37431c47.png)

Software render:

![ratchet2](https://user-images.githubusercontent.com/90222976/149664800-2855df80-3a0b-4f9b-9c4c-977926219033.png)

### Logs & Dumps

GSdump:
[Ratchet 3 aquatos graphics problem with hw render.zip](https://github.com/PCSX2/pcsx2/files/7877154/Ratchet.3.aquatos.graphics.problem.with.hw.render.zip)

**Comment by Dreadmoth** [comment]
Curiously, the effect looks more accurate (or, less broken?) with Blending Accuracy set to Minimum:

![R&C3 Minimum Blending Accuracy](https://user-images.githubusercontent.com/8492684/149669129-17861b75-a0b2-466b-a7e7-89de0aa8b7bc.png)

You can fix the effect not rendering at the bottom (~1/14th) of the screen by setting Half Screen Fix to Force-Enabled:

![R&C3 Half Screen Fix Force Enabled](https://user-images.githubusercontent.com/8492684/149669186-9efad79e-6f99-4889-b8a1-89966e0db76a.png)

**Comment by MrCK1** [comment]
Closing in favor of https://github.com/PCSX2/pcsx2/issues/2088 -  a bunch of planets have HW issues. It will be easier to track in one issue
