### ISSUE TITLE
Rule of Rose stuck in chapter 2

### ISSUE THREAD

**Issue by Talantyyr** [PCSX2/pcsx2#535]
In version "pcsx2-v1.3.1-214-g7bfee7e-windows-x86" downloaded from the daily builds, rule of rose gets stuck when the second chapter "APRIL" (Unlucky Cloverfield) is loaded. 

The culprit is the "Game fix" "Switch to GSdx software rendering when an FMV plays". When it's enabled, all videos so far are working, but in chapter 2 there's just a blackscreen an when i click anywhere the "program is not responding" dialog appears and windows force quits PCSX2. When it's disabled, no video is shown but the game is working and chapter 2 can be played.

Video Plugin is set to DirectX 11 HARDWARE @1080p 

Here is my memory card folder zipped with a direct savestate of chapter 2. When the savestate is loaded, PCSX2 gets stuck with a black screen and won't respond anymore.
http://workupload.com/file/PIWcj5Pg

**Comment by bositman** [comment]
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues
If it's a regressions, the best help would be to mention when it worked last.

**Comment by Talantyyr** [comment]
It's not a regression, it's the same issue in the oldest available build and the feature "Switch to GSdx software rendering when an FMV plays" is not available in the official release.  At least i couldn't find it yesterday in the latest stable version... 

I've also tested it with  a older revision (from february) but it's exactly the same behaviour. Stuck / crash when loading chapter 2 with "Switch to GSdx software rendering when an FMV plays" enabled.

When it's disabled it works on all builds but no video is shown at all. 

Here's the thread about this feature when it was implemented as a workaround:
http://forums.pcsx2.net/Thread-Black-screen-Rule-of-Rose

**Comment by bositman** [comment]
Then why do you have regression on the issue title....?
Please edit your issue to follow the guidelines if you want this fixed. We don't know what region the game is, you haven't provided any PCSX2 version tested (a build from February won't do, give us a build number) and save states tend to record bugs in them, so not a good way to test, you should load from memory card saves for debugging. Also that option does exist in the stable 1.2.1.

**Comment by bositman** [comment]
Tested with DX11 HW and the game fix on, game loaded fine, showed the video after switching to SW and switched back to HW when it was done.
