### ISSUE TITLE
[BUG]: Control lock up on racing games

### ISSUE THREAD

**Issue by Aya-Komichi** [PCSX2/pcsx2#5352]
### Describe the Bug

The controls lock up at random while playing on keyboard. Pressing the locked up control and releasing stops the locking.

### Reproduction Steps

This happens on Linux with the kernels 5.10, 5.15 and 5.16, most likely happens on other kernel versions (but that's just me guessing).

Doing any events on racing games such as Burnout games or NFS games, for example, will sometimes get controls locked up, wether they are the steering, accelerator or brakes. On Enthusia this lock up happens much more often, which renders this game in particular kinda unplayable. Not sure if it is limited to racing games only.

I tested with the balanced preset and the native preset (no speedhacks), the bug persists regardless. More aggressive presets do not prevent it either.

### Expected Behavior

No lock up.

### PCSX2 Revision

v1.7.2243-2

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

EndeavourOS (Arch based)

**Comment by F0bes** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/4492
