### ISSUE TITLE
[BUG]: Cannot load ISO (assertion failutre)

### ISSUE THREAD

**Issue by rempas** [PCSX2/pcsx2#5354]
### Describe the Bug

When I'm trying to boot the ISO, I'm getting the assertion failure error and then I can choose to close the program or ignore to make the other assertion but no matter what I press, the emulator will close. The error message is the following:

```
/home/runner/work/pcsx2/pcsx2/common/Linux/LnxHostSys.cpp(69) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    MTGS
    Condition: false
    Message:   Unhandled page fault @ 0x00000000

Stacktrace:
[00] 0x0x5648418f729f                            
[01] 0x0x7fcb38e68870                            
[02] 0x0x56484122348b                            
[03] 0x0x564841595bc5                            
[04] 0x0x5648418e67aa                            
[05] 0x0x5648418e7a04                            
[06] 0x0x7fcb38e5e259                            
[07] clone                                         
```

Also the following text is printed in the terminal after the assertion happens:
```
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
/tmp/.mount_pcsx2-sAqH7P/AppRun.wrapped: line 5: 18930 Trace/breakpoint trap   (core dumped) $APPDIR/AppRun-patched
```

### Reproduction Steps

1. Open PCSX2
2. Select the ISO
3. Boot the ISO (with and without fast boot enabled)
4. BOOM!!!

### Expected Behavior

I was expecting to not crash.

### PCSX2 Revision

v1.7.2246

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch btw

**Comment by F0bes** [comment]
Try reinstalling `libdbusmenu-glib` and (aur)`gconf`

**Comment by rempas** [comment]
> Try reinstalling libdbusmenu-glib and (aur)gconf

Did it. Now the output in the terminal changes to only the last line:
```/tmp/.mount_pcsx2-nvKkcN/AppRun.wrapped: line 5: 24282 Trace/breakpoint trap   (core dumped) $APPDIR/AppRun-patched```

The problem remains

**Comment by SupervisedThinking** [comment]
maybe the same as https://github.com/PCSX2/pcsx2/issues/5226 ?

**Comment by seta-san** [comment]
Have you updated the resources folder?

**Comment by rempas** [comment]
> maybe the same as #5226 ?

The function that fails is the same but they do fail in different lines.

**Comment by rempas** [comment]
> Have you updated the resources folder?

What's this directory? How can I update it?

**Comment by seta-san** [comment]
In recent builds they stopped baking a lot of things into the .exe.  They moved it all to a folder called resources.

**Comment by F0bes** [comment]
I think you're using an AppImage?

https://github.com/PCSX2/pcsx2/wiki/Using-GDB-with-Linux-AppImages
Can you follow this guide?

- Attach GDB before the fault.
- Once GDB is attached enter `r` if PCSX2 isn't running.
- Cause the crash, if prompted with an assertion dialog box press `Yes` to terminate the application.
- Now you should see some information in GDB. Type in `bt` and give us the output of that here.

**Comment by rempas** [comment]
> In recent builds they stopped baking a lot of things into the .exe. They moved it all to a folder called resources.

I can't find the folder. Is there a chance that it is a windows specific thing?

**Comment by rempas** [comment]
> I think you're using an AppImage?

Yes!

> https://github.com/PCSX2/pcsx2/wiki/Using-GDB-with-Linux-AppImages Can you follow this guide?
> 
>     * Attach GDB before the fault.
> 
>     * Once GDB is attached enter `r` if PCSX2 isn't running.
> 
>     * Cause the crash, if prompted with an assertion dialog box press `Yes` to terminate the application.
> 
>     * Now you should see some information in GDB. Type in `bt` and give us the output of that here.

Thanks, I don't understand what you mean by "attach GDB" (never used a debugger before). So what I tried to do was the following:

- I opened GDB
- I used `file pcsx2-v1.7.2246-linux-AppImage-64bit.AppImage`
- I used `r` to run the file like you said
- Produced the crash (and then pressed "Yes" in the dialog)
- After the emulator crashed, I pressed `bt`

However, I got "No stack." as a result. Also, when loading the file, GDB says that there are no debug symbols for the appimage. Is there something I did wrong?

**Comment by F0bes** [comment]
I'm not familiar with that...
Can you try getting pcsx2 from the Aur?
It's called pcsx2-git.

**Comment by rempas** [comment]
It works when used through AUR! Thanks a lot!
