### ISSUE TITLE
PCSX2 In-Built recorder not functioning.

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#536]
at the recent development builds, the GSDX internal recorder function is not working. 

The following error pops up in the log.
> (Pcsx2AppMethodEvent) STL Runtime Error: device or resource busy: device or resource busy

you can manually reproduce it by trying the latest development build and initiating the capture by pressing F12.

**Comment by bositman** [comment]
You above all people should follow the bug report format...
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues
