### ISSUE TITLE
[BUG]: AppImage fails to launch with mktemp error (Ubuntu 21.10)

### ISSUE THREAD

**Issue by fmillion** [PCSX2/pcsx2#5362]
### Describe the Bug

When attempting to launch a nightly AppImage build (tested version 1.7.2248), the following error occurs:

    mktemp: too few X's in template ‘/tmp/.mount_pcsx2-GetxTX.ld-p-gtk-tmp’

Some investigating led me to determine this might be an issue with a dependency being pulled in for the AppImage build from https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh. This block of code in that script seems to be the issue:

    if [ "$APPDIR" != "" ]; then
        tempdir_template="$APPDIR".ld-p-gtk-tmp
    else
        tempdir_template=/tmp/.ld-p-gtk-tmp-XXXXXX
    fi

    CACHEDIR="$(mktemp -d "$tempdir_template")"

Within an AppImage, the `$APPDIR` variable would be set. However, it appears `mktemp` demands there be a running set of X's in the string given on its command line, and the `$APPDIR` variable would not contain those expected X's (but as you can see, the default value given if `$APPDIR` is not set *does* contain the X's). 

This appears to be a frustrating inconsistency between BSD and GNU `mktemp` as well as different coreutils versions' implementation of `mktemp`, as discussed [here](https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x). More discussion of the idiosyncrasies of `mktemp` across coreutils versions and platforms appears [here](https://lists.gnu.org/archive/html/help-gnu-utils/2010-03/msg00003.html) and [here](https://stackoverflow.com/questions/31396985/why-is-mktemp-on-os-x-broken-with-a-command-that-worked-on-linux) and [here](https://stackoverflow.com/questions/2792675/how-portable-is-mktemp1). It appears this requirement was added around coreutils 8.1, and some distros are still running coreutils in the 7.x series, which might be why this problem is appearing on newer distros (but I can't confirm any of this to be sure, this is just from my cursory evaluation of the problem).

The version of `mktemp` on this Ubuntu install is part of coreutils 8.32.
 

### Reproduction Steps

1. Install a current release of Ubuntu 21.10 and update with latest patches.
2. Try to run one of the nightly AppImage builds.

### Expected Behavior

The PCSX2 application should start.

### PCSX2 Revision

v1.7.2248

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 21.10

**Comment by F0bes** [comment]
![image](https://user-images.githubusercontent.com/29295048/150275990-2080869c-e906-43a9-943d-9fea82f31c20.png)
Issue is known and has been reported upstream by @qurious-pixel 
Waiting for them to fix.

**Comment by poVoq** [comment]
Same on Manjaro. Thanks for looking into it.

**Comment by r2rX** [comment]
Can confirm the same on Fedora 35. Looking forward to the fix & cheers! :)

**Comment by jksemacio** [comment]
can't try newer builds because of this, i have manjaro kde.

**Comment by F0bes** [comment]
Understood. You can always build from source too. Or extract the appimage and run pcsx2 from there.

**Comment by kenshen112** [comment]
> can't try newer builds because of this, i have manjaro kde.

You can use the AUR package pcsx2-git @jksemacio just type `yah -S pcsx2-git` in your terminal. I just updated it today.

You'll also get auto updates if you use it

**Comment by F0bes** [comment]
I've been told upstream has fixed this.
