### ISSUE TITLE
Have to resume emulation manually after savestate on the linux port

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#537]
Just a minor bug. Or maybe it is on purpose since we have to exit fullscreen emulation or alt+tab to quicksave due to missing shortcuts, but the game window popping up frozen after the save tells me it's probably not.

**Comment by gregory38** [comment]
Could you describe presicely your issue? It is not clear for me.

**Comment by karasuhebi** [comment]
Emulation gets paused/frozen when he saves a state.

**Comment by gregory38** [comment]
First there is no fullscreen mode in PCSX2 linux. It just a bordless window. Could you share the emulog when the freeze happen.

I just test it, no issue here.

**Comment by i30817** [comment]
Starting from cleared log window, paused game, i savestate and then the (bordeless, as you say) window appears 'frozen' and then i must return to the main application by alt tab and click resume:
https://gist.github.com/i30817/fd3ed647b226c03e0bf4

aspect ratio 4:3
custom window size 1024x555 (which now that i think about it's not my native 1366x768 resolution, funny how it fills the whole screen instead)
Zoom 100.00
Disable window resize border is OFF
Always hide mouse cursor/hide window when paused/default to fullscreen mode on open/double click toggles fullscreen mode are ON

**Comment by gregory38** [comment]
Did you enable mtvu? Could you check with clean configuration (backup the ini file first)

**Comment by gregory38** [comment]
I don't remember if PCSX2 supports an auto-pause feature when focus is lost.

**Comment by i30817** [comment]
I think this is because due to the other bug (the Fkeys being unreliable) i got conditioned to use ESC (pause), and naturally when the window poped up again after saving from the menu paused, it keeps being paused.

I might have imagined it happening with alt+tab, cant really reproduce now.

**Comment by karasuhebi** [comment]
>custom window size 1024x555 (which now that i think about it's not my native 1366x768 resolution, funny how it fills the whole screen instead)

Custom Window Size is to tell PCSX2 the size of the gameplay window (GS Window) when it is not in 'full screen'. That value is not too important because you should be able to just adjust the size of the Window on the fly by dragging the corners.

**Comment by gregory38** [comment]
I'm lost. Is it good or not for you. If yes, please close the issue. Thanks.

**Comment by i30817** [comment]
Err, what is happening is that i pressed esc and then savestated, and the game window gets focus in fullscreen, but the emulation is still paused.

Which is a bug surely.

**Comment by gregory38** [comment]
if you press esc, emulation is stopped correct? I try to do it but I got a crash (if I do the savestate in the menu)

**Comment by gregory38** [comment]
So afer discussion the behavior is normal.
1/ It isn't allowed to savestate during the pause
2/ that why it reopen the GS plugin. Which gain the focus
3/ but it keeps it suspended because you pause the emulator

Can I close the bug?

**Comment by i30817** [comment]
It isn't intuitive, for myself, i'd prefer that 2/ unpaused if fullscreen and paused.

**Comment by gregory38** [comment]
I don't understand you. Which behavior do you want exactly? Honestly use alt-tab instead of ESC.

**Comment by FlatOutPS2** [comment]
Note that behaviour is still the same. Pause in fullscreen, then doing a save sate will reopen the focussed fullscreen, but still remain paused.

**Comment by i30817** [comment]
I actually don't really understand how this *can't* be considered a interface bug. So the user presses 'esc' to 'pause' the game, ok i buy it. But what the user wants is to is interact with the menu, savestate, loadstate etc.

If one of those options then helpfully maximizes the game window (ie: savestate) then the user wants it *running* not paused. Otherwise it might as well not have been 'helpful', because the user will just press esc again, find the unpause button and maximize.
