### ISSUE TITLE
[BUG]: Pac-Man World Rally: Graphical rendering artifacts.

### ISSUE THREAD

**Issue by Hemporus01** [PCSX2/pcsx2#5372]
### Describe the Bug

The bug seems to be a bunch of graphical artifacts appearing on an off screen from various different racers, npcs, and some shadows on some objects during rendering transitions. 

### Reproduction Steps

To reproduce the behavior, just pick any track an any character and get ingame. To really notice it, you'll want to specifically pick the track Arctic Iceberg or Retro Maze as they both produce a major amount of graphical artifacts than any of the other tracks I've tested.

### Expected Behavior

I expected to not be able to see any artifacts when shadows on certain objects for example or passing by npcs or other racers render on or off screen.

### PCSX2 Revision

v1.7.2248

### Operating System

Windows 10 (64bit)

### CPU

i5-11600

### GPU

GTX 1080 Ti

### GS Settings

<img width="268" alt="GS Settings 1" src="https://user-images.githubusercontent.com/97992262/150609737-cdc2e14b-ac4c-406c-90d8-f7bda6c7e561.PNG">
<img width="265" alt="GS Settings 2" src="https://user-images.githubusercontent.com/97992262/150609754-88904dca-cdca-479a-9e25-77cfc9906046.PNG">

Everything that is highlighted are the non-defaults.

### Emulation Settings

Only defaults were used.

### GS Window Screenshots

![InkedPMWR Character Select_LI](https://user-images.githubusercontent.com/97992262/150615971-fc4b8378-4797-48eb-8a5d-8f1f52cb9839.jpg)
When entering the character select screen, this microVU1 code always appears. I don't know whats causing the code, but i know it has something to do with those graphical artifacts ingame.
![Inkedgs_20220121174225_LI](https://user-images.githubusercontent.com/97992262/150616613-992b682f-5a9b-485b-8dcc-09927466175b.png)
Arctic Iceberg track.
![gs_20220121174342](https://user-images.githubusercontent.com/97992262/150616767-a9880f39-a82a-48bf-abb6-4fe7f74e042b.png)
![gs_20220121174357](https://user-images.githubusercontent.com/97992262/150616781-3a4953f6-71cb-4681-9b6e-0492c6a145c4.png)
![Inkedgs_20220121174434_LI](https://user-images.githubusercontent.com/97992262/150616912-993bfaa8-2c27-4fbb-b9fe-4bb04a2fdd6b.png)
![Inkedgs_20220121174440_LI](https://user-images.githubusercontent.com/97992262/150617199-034a1a02-f531-425f-a6cb-8bc95cff89ae.png)
![gs_20220121174458](https://user-images.githubusercontent.com/97992262/150617297-bb02d265-38a4-4811-b1d5-788f62bc09d5.png)
![Inkedgs_20220121174614_LI](https://user-images.githubusercontent.com/97992262/150617617-9a9ada2d-f62d-4bd1-9903-5b81599c07c1.png)
![gs_20220121174635](https://user-images.githubusercontent.com/97992262/150617637-b1d84e26-d5c5-48fa-929f-c36940271f3f.png)
![gs_20220121174651](https://user-images.githubusercontent.com/97992262/150617685-1672641c-ae91-47ae-9a8d-c1a125ab0e1b.png)
![gs_20220121174654](https://user-images.githubusercontent.com/97992262/150617720-6c2e438d-08d9-46c6-a6ca-d5e73379e952.png)
![Inkedgs_20220121174910_LI](https://user-images.githubusercontent.com/97992262/150617928-f6c41eaf-a43e-4db1-bfa5-682d1f7d38e0.png)
Retro Maze track.
![gs_20220121174850](https://user-images.githubusercontent.com/97992262/150618052-7332e258-f394-4ba2-8e8f-38d208b9fcb3.png)
![gs_20220121174853](https://user-images.githubusercontent.com/97992262/150618057-b16d1587-514d-4d2b-9257-8e1cca8c8074.png)
![gs_20220121174857](https://user-images.githubusercontent.com/97992262/150618059-3708469d-0036-4efe-82c9-8445c9e7015e.png)
![Inkedgs_20220121174920_LI](https://user-images.githubusercontent.com/97992262/150618160-75061490-9b19-4ca4-939f-96b7517b2396.png)
![gs_20220121174805](https://user-images.githubusercontent.com/97992262/150618215-6e7fdc5b-0b56-4623-a482-9c8019ae3398.png)
![gs_20220121174804](https://user-images.githubusercontent.com/97992262/150618225-7c5e4c3c-6a0e-4b23-b197-25ca6a04465e.png)
![gs_20220121174807](https://user-images.githubusercontent.com/97992262/150618232-5b31b7fa-75e9-41bf-b12b-5ec5b209aa21.png)

### Logs & Dumps

[PMWR Graphical Rendering Bug GS dump.zip](https://github.com/PCSX2/pcsx2/files/7917350/PMWR.Graphical.Rendering.Bug.GS.dump.zip)

**Comment by refractionpcsx2** [comment]
Do you even get the artifacts in software mode?

**Comment by Hemporus01** [comment]
They appear in both SW and HW.

**Comment by refractionpcsx2** [comment]
can you check Automatic Gamefixes is enabled under System->Game Settings

Also when you upgraded, did you make sure to extract the resources folder?

This game has an automatic fix for the geometry already, so one of the above two should fix it.

**Comment by Hemporus01** [comment]
Manual Gamefixes is disabled and  i do have the resources folder so I'm all good.

**Comment by RedDevilus** [comment]
He meant this should be enabled:
![image](https://user-images.githubusercontent.com/24227051/150620307-a0d51dcc-c305-4647-ae9e-bef11b5f4947.png)

**Comment by Hemporus01** [comment]
![pcsx2_CoreSettings_Game Fixes](https://user-images.githubusercontent.com/97992262/150620379-5a571a28-28bb-4662-aaea-7759a391be91.png)

**Comment by Hemporus01** [comment]
That's all that I see on that screen. I don't see Automatic Gamefixes.

**Comment by RedDevilus** [comment]
Please follow the instructions correctly:
![image](https://user-images.githubusercontent.com/24227051/150620562-f617a0d6-04e0-43ba-a539-0f343ffe0f37.png)

**Comment by Hemporus01** [comment]
nvm found it it is enabled.

**Comment by RedDevilus** [comment]
I don't see why it's failing when there is already this:

![image](https://user-images.githubusercontent.com/24227051/150620650-ceea5383-a384-46eb-aefd-4177b97da16c.png)

Can you test with VuKickStart and EETiming separately?

**Comment by Hemporus01** [comment]
Ill try it.

**Comment by refractionpcsx2** [comment]
Guys, I'm already on it.  The game is going to need a patch but there is also a microVU problem.

**Comment by Hemporus01** [comment]
Nope VuKickStart and EETiming didnt work.

**Comment by refractionpcsx2** [comment]
I have a PR (linked above) which improves the game a bunch, but there's still some glitching when you're in a huge pack of players, and I'm not sure right now how to fix that...

**Comment by and468860** [comment]
![gs_20220122070713](https://user-images.githubusercontent.com/61087055/150631509-cae04658-877a-4413-ba61-e5bc209711a2.png)
![gs_20220122070743](https://user-images.githubusercontent.com/61087055/150631512-00c757e9-e655-4fb2-9452-8272dfcf0b50.png)

**Comment by Hemporus01** [comment]
To get rid of that line in the first screenshot you need to use Half-Pixel Offset: Special (Texture).
