### ISSUE TITLE
[BUG]: Suikoden IV - Tiling in the water over 2xPS2 Resolution

### ISSUE THREAD

**Issue by Klauserus** [PCSX2/pcsx2#5376]
### Describe the Bug

Hi

In Suikoden IV PAL - In first minute of playing, i have tiling at the Water. See Screenshot. Only at 3x PS2 Resolution and above.
Unter this Resolution all Fine. OpenGl or Vulkan the same.

![gs_20220122150641](https://user-images.githubusercontent.com/26491758/150642322-28953bd6-342b-480c-a0c8-a98f7ce2d8d1.png)

The black lines near the blue one

### Reproduction Steps

Boot Game
Give the Hero a Name. After that 3 Dialogs and now you can see the battlefield with the error i descripe.

### PCSX2 Revision

1.7.2246 AVX2 64 bit

### Operating System

Windows 10 (64bit)

### CPU

5600G

### GPU

5600G

### GS Settings

All Default
Anistr. Filter 16x
no hacks
Default Setting Level 2

### GS Window Screenshots

![pcsx2_CoreSettings_GS Fenster](https://user-images.githubusercontent.com/26491758/150642613-82020167-1d65-490f-9be1-21c315674b42.png)

**Comment by Klauserus** [comment]
Another strange occurrence is (maybe this is related) I have USA and EUROPE bios in the folder. Rigth hashes. I play NTSC Games and the FPS are stubbornly on 50 like PAL

**Comment by refractionpcsx2** [comment]
FPS has nothing to do with the BIOS. not sure what you're doing there.

**Comment by AndreAuth** [comment]
I checked this bug with 1.7.2562.

The black squares are fixed with the GameDB entry:

SLES-52913:
  name: "Suikoden IV"
  region: "PAL-M5"
  compat: 5
  gsHWFixes:
    halfPixelOffset: 1 # Fixes black squares in water.

Just update to the new Version and everything is fine.

**Comment by RedDevilus** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/5664
