### ISSUE TITLE
[BUG]: Final Fantasy XII crash on Vulkan

### ISSUE THREAD

**Issue by l-gthb** [PCSX2/pcsx2#5379]
### Describe the Bug

the emulation randomly freezes when using Vulkan renderer, sometimes i have to force close it and sometimes it just closes itself.

### Reproduction Steps

Boot ISO, play for a while (it changes) until crash.

### Expected Behavior

the expected behavior should be, obviously, no crashes at all. however it must be noted that on my hardware (and many others from Intel) there have been similar random freezes using OpenGL and not only in PCSX2, but also many other games.

this behaviour has changed many times in the past two years (more or less).
the whole system used to freezes at first, forcing me to shutdown the machine. recently the applications were just crashing leaving the rest of the system running as it should and in the latest tests i have done lately the whole screen freezes, the game and any other application seems to keep running, but i have to switch to another tty and restart to fix it.

i switched to Vulkan because there were occasions last year, where some games crashed on OpenGL but not on Vulkan, so i gave it a try.
overall with Vulkan the game runs very smooth with 3x native res, while i could only reach 2x on OpenGL.
there are slowdowns, but i'm pretty sure they are expected since it's just too early and the fact that i can use higher resolution already tells me that Vulkan runs much better on my system and i will keep using it for now since it gives me longer "gameplay frames" between one crash and the other and it never freezed everything, so i have to just restart PCSX2.

i'm sure the hardware is fine, i can stream on Firefox, play videos and do similar stuff that (i think) should show at least some kind of graphical issues if the hardware was faulty.
in addition, if you chheck mesa issue tracker you'll find an infinite amount of issues presenting the usual "GPU hang" messages, that to my knowledge have been confirmed to be bugs, but never solved yet.

i have obviously tried to report crashes on OpenGL to them, but i have never received an answer, exactly like other report from other users.

i'm at a complete loss... i haven't been able to do what i want on my laptop for a LONG time, so i'm sorry for the ranting here, but i'm really really tired of it and i hope that this issue here with Vulkan isn't related and can actually be solved to finally have a little alternative and being able to use the hardware i paid for...

thank you in advance.

### PCSX2 Revision

v1.7.2243

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

i3-6006U

### GPU

Intel HD Graphics 520

### GS Settings

![Screenshot from 2022-01-22 17-23-40](https://user-images.githubusercontent.com/77892355/150646981-df144d1d-4c57-437b-9613-930d1ff7c7a2.png)

### Emulation Settings

![Screenshot from 2022-01-22 17-24-06](https://user-images.githubusercontent.com/77892355/150646977-3a505737-d752-4ceb-abf9-3be8721c891a.png)

### Logs & Dumps

/startdir/src/pcsx2/common/Vulkan/Context.cpp(1026) : assertion failed:
    Function:  void Vulkan::Context::DoSubmitCommandBuffer(u32, VkSemaphore, VkSemaphore)
    Thread:    MTGS
    Condition: false
    Message:   Failed to submit command buffer.

Stacktrace:
[00] 0x0x7f978d49a699                            
[01] 0x0x7f978d3102de                            
[02] 0x0x7f978d34472b                            
[03] 0x0x7f978d2774de                            
[04] 0x0x7f978d2861f8                            
[05] 0x0x7f978d2213c4                            
[06] 0x0x7f978d021acd                            
[07] 0x0x7f978d5ff00e                            
[08] 0x0x7f978d47d85d                            
[09] 0x0x7f978c87b259                            
[10] clone

**Comment by stenzek** [comment]
Run with the validation layers on and check for error reports, and/or check dmesg for the reason of the GPU hang.

May be a driver bug.

**Comment by l-gthb** [comment]
@stenzek thanks a lot for your reply. i think i've made a little mistake.
i went to install vulkan-validation-layers and i installed vulkan-tool too, for no reason in particular. when i ran "vulkaninfo" the first line had a warning and there was mention about lavapipe.
so i tried to override the loaded driver to use Intel's. the warning wasn't there anymore, so i started PCSX2 and started playing FFXII.
it's still running and it's been going for half an hour, it's a record and i think it means that as expected anything that happens with OpenGL on Intel's hardware isn't happening on Vulkan.

i'll obviously keep it running for the next hours and report back if i'm wrong and i get other problems, but for now it should be safe to close this.

Sorry, i should've checked the driver was correct first, i didn't think it could happen.

Thanks a lot for your help and for the work of every developer involved in PCSX2 and the Vulkan renderer. much much love! <3
