### ISSUE TITLE
[Feature Request]: Output desired resolution to the driver when in fullscreen mode.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5381]
### Description

Let's say you have a 1440p screen and a GPU that can run most games at very high resolution, let's say, 4K.

Currently in GSDX, running a game at 6x (around 4k) will effectively run at 4k internally but will not take advantage of driver's optimizations such as DLDSR as the PCSX2 window in fullscreen doesn't seem to display a 3840 by 2160 image, but rather a direct 2160 by 1440 one.

The request here would be to introduce a "Pixel output mode" option where fixed resolutions such as 1440p and 4K will actually output a true 3840 by 2160 and 2160 by 1440 image respectively which will allow the driver to enables it's downscaling technologies and as such, using GPUs tensor cores to their best.

### Reason

Improve image quality in various scenarios, taking advantage of downscaling technologies.

### Examples

Any PC games running in fullscreen exclusive mode.

**Comment by refractionpcsx2** [comment]
PCSX2 will never use a PC style resolution, that's why we got rid of Custom Resolution, because it causes problems with scaling and breaks the emulation,  as far as I'm aware we can't decouple the emulation from the output resolution.

**Comment by gilderoylockhart01** [comment]
Ok that's fine. I will close the thread if that is not possible, I guess that can still be done by the driver itself by forcing desktop resolution.
