### ISSUE TITLE
[Feature Request]: Moving the COP2 bad div/q detection system to retail builds.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5388]
### Description

In PCSX2, there is a detection system that allows devs to spot a couple of specific COP2 errors due to bad div or q timings (excuse me if that's a terrible term ^^) and will print those to the console log.

This is very useful in case a game will have issues with the COP2 even if the issue is not obvious or even apparent.

Currently, you need a devel build or upper for that to work, this is a bit inconvenient as the dev builds are compiled with the release flag, and it's not exactly slower or anything.

### Reason

Makes testing *a lot* easier and allows the end users to knows if the game is running badly.

+ this will ease the work of bug squad and testers members, the user would just have to post the emulog, and they will already know where the problem might come from if it's related to that.

And yeah, this can have false positive but the persons who will write the patch will likely know how to separate those from the real ones.

### Examples

Devil May Cry has a COP2 problem which is *impossible* to notice with a release build, the patch was created for that thanks to that detection system, so why not the end users could take advantage of that?

**Comment by F0bes** [comment]
I don't think I have enough time between now and work to make up a pr but I'd like benchmarks to be made.
Considering during recompilation [this](https://github.com/PCSX2/pcsx2/blob/4ccb922d1ab10b95f7ee391f2bcd2bedacaecdec/pcsx2/x86/ix86-32/iR5900-32.cpp#L1596-L1659) is going to be run now. And it's a lot of loops and branches. Maybe a game that likes to do self modifying code would be a good test.
