### ISSUE TITLE
[BUG - GS: Hardware render]: Black: Full Blending causing massive slowdowns.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5390]
### Describe the Bug

In the game "Black", there is a problem where the game will need full blending in order to look right, but actually using it is impossible because it tanks the performance too hard. Even using high blending will not be enough to fix the graphics.

Using native resolution leads to a playable frame-rate but with a 3070, it's kind of weird to have this performance anyway, despite using OpenGL,Vulkan or DX11.

### Reproduction Steps

Load the GSdump with high or full blending.

### Expected Behavior

The game should look like the software render without being super slow.

### PCSX2 Revision

v1.7.2261

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

Half pixel offset to special-texture, round sprite to half. Full blending.

### Emulation Settings

VU clamping mode to extra + preserv sign.

### GS Window Screenshots

The bug in action:

High blending:
![black high blend](https://user-images.githubusercontent.com/90222976/150682150-a8e59275-1d43-4ee1-9e1e-10116dc16304.png)

Full blending:

![black full blend](https://user-images.githubusercontent.com/90222976/150682159-4ebcb7c2-65a1-4620-8de4-b6947c4616f9.png)

### Logs & Dumps

The GSdump:
[Black expensive blending problem.zip](https://github.com/PCSX2/pcsx2/files/7920632/Black.expensive.blending.problem.zip)

**Comment by lightningterror** [comment]
It's to be expected, high blending modes will be taxing.

**Comment by JordanTheToaster** [comment]
Full speed here at 8x with Full blending.

![image](https://user-images.githubusercontent.com/80843560/152634916-1c49a632-52ef-4a5f-946f-62c9aa10b986.png)

**Comment by TransparentBlue** [comment]
That very much looks like it's missing a lot of effects, even compared to the high blending screenshot above.

**Comment by JordanTheToaster** [comment]
It seems to be broken in some way in more recent versions but here's the dump in 2261 I'm still getting 70 fps.

![image](https://user-images.githubusercontent.com/80843560/152636182-5ef1ac07-8984-4080-b73d-ba0d57d8e982.png)

**Comment by lightningterror** [comment]
It's all fine here, going back to performance, the game will be much faster on latest dev build with all the recent blending optimizations.

**Comment by lightningterror** [comment]
Closing as blending handling has been greatly improved, if still slow lower the resolution or blending level.
