### ISSUE TITLE
[BUG]: Quake III Revolution: flickering black textures

### ISSUE THREAD

**Issue by Matthaiks** [PCSX2/pcsx2#5394]
### Describe the Bug

See the video:
https://user-images.githubusercontent.com/3577122/150688455-14214639-b35a-4eb7-af3f-619dd6861413.mp4

### Reproduction Steps

Run the game and the map "Arena Gate".  All renderers are affected.

### PCSX2 Revision

v1.7.2262

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3 2200G

### GPU

Radeon Vega 8

### Logs & Dumps

[Q3R.zip](https://github.com/PCSX2/pcsx2/files/7920889/Q3R.zip)

**Comment by refractionpcsx2** [comment]
Yep, that is Z fighting, might not get fixed any time super soon, I'd also be interested to know how badly the console does it.

**Comment by Matthaiks** [comment]
It looks fine here: https://youtu.be/YCCpgZVJt1g?t=398

**Comment by refractionpcsx2** [comment]
There looks to be a tiny bit on the edge, but yeah nowhere near as bad.

**Comment by lightningterror** [comment]
Closing in favor of meta issue.
