### ISSUE TITLE
[BUG]: MS compile script doesn't work with visual Studio 2022.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5396]
### Describe the Bug

The MScompile script which allows to compile PCSX2 fast is not working when using Visual Studio 2022 as your main IDE.

### Reproduction Steps

Try to start MScompile with Visual Studio 2022 installed.

### Expected Behavior

The script should work.

### PCSX2 Revision

v1.7.2261

### Operating System

Windows 11

**Comment by Squall-Leonhart** [comment]
Works if you select the the 142 toolset.
