### ISSUE TITLE
[Feature Request]: [DEV9] [Nightly] Remove the minimum hard disk size and add the ability to specify the hard disk size. 

### ISSUE THREAD

**Issue by Danik2343** [PCSX2/pcsx2#5398]
### Description

Yes, I think that 40 GB is too much by default, better remove the 40 GB limit so that you can put 8 GB like DEV9 plugins on PCSX2 release versions, that will be fine, good luck with development! You have created the best PS2 emulator! 

### Reason

Less space will be occupied by the size of the hard disk if I set it to 8 gigabytes for example. 

### Examples

CLR_DEV9 plugin has the ability to set 1 GB for HDD

**Comment by RedDevilus** [comment]
It used to be 8-120GB but people were picking too low sizes for games that wanted more. Though there is a PR in the works that does not occupy 40GB directly but dynamically what it needs (like 5000MB used but the file will be 6000MB).

So there are workarounds for it, but yeah it's fair to say 40GB allocated directly is a bit much.

**Comment by Danik2343** [comment]
At the same time, you can add a dynamic disk check mark to the settings themselves.

**Comment by marcoluc97** [comment]
There is a possibility for dynamic allocation? Meaning only used space is count from FS PoV and not the file creation size? Just a profane comment

**Comment by Florin9doi** [comment]
> There is a possibility for dynamic allocation? Meaning only used space is count from FS PoV and not the file creation size? Just a profane comment

Yes: #4446

**Comment by marcoluc97** [comment]
Thanks @Florin9doi didn't notice the PR sorry

**Comment by F0bes** [comment]
Closing as lowering the minimum is not in our interest. For those of you who stumbled upon here, keep track of the linked pr in the above comment.

**Comment by refractionpcsx2** [comment]
You can also NTFS compress the file if you're on windows, and it will bring the 40gb empty file down to a whopping...0 bytes

**Comment by Pobega** [comment]
The sparse files change does not seem to work on Steam Deck. On my Windows machine it is using the 1.2GB properly but on Deck it uses the entire whopping 40GB.

Is there any possibility for an override setting to allow us to create a smaller disk? Perhaps with a 'use at your own risk' warning or something. (or alternatively is there a third party tool that would allow me to create a smaller disk image? Would a raw image created with `qemu-img` be compatible?)

**Comment by TheLastRar** [comment]
The code on Linux & Mac expects the OS to create the file as sparse, 
I would expect this to be the case on the steam deck as it's Arch based.

What file system is it using?
is the tool you are to verify the size capable of determining the difference between file size and (allocated) size on disk?

As for using smaller images
Looking at the documentation for `qemu-img`, it should be able to produce a compatible image with `format=raw`
While the settings UI will still set the minimum size to 40GiB, PCSX2 _shouldn't_ crash with a smaller image, but games may not work as sectors beyond the actual file are treated as un-readable/un-writable.

The minimum size is currently only enforced by the Ui, you can hand edit the config file to a smaller value (the setting would be `HddSizeSectors`) but touching the size settings or selecting an existing file in the HDD Ui would reset this value to 40-120GiB.

Beware that using a smaller image is an unsupported use-case, you'll probably be on your own if you encounter issues and the behaviour described above may be subject to change.

**Comment by Pobega** [comment]
So it seems to be a little more interesting than I initially thought. I was using an image transferred from Windows which seems to work as a sparse file on my Linux desktop (Fedora 37) but not my Steam Deck. I then created a new HDD using PCSX2 on the Steam Deck and it _appears_ to be sparse. I'm installing some games while I type this so it remains to be seen what the results look like, but I think that's all good.

Is the creation of the raw image different between Linux and Windows? Perhaps it's my fault for assuming that I can transfer the file between operating systems.

Also with regards to `qemu-img` it initially appeared to work but interestingly no matter the size of the raw image I created `wLaunchELF` would always see it as a 4GB hard drive and Resident Evil Outbreak complained that there wasn't 1.1GB of HDD space to install to. I did also try writing a raw file with 0's using `dd` but that had the same results as `qemu-img`.

Thanks for the tip on `HddSizeSectors`, I understand it's unsupported behavior but may come in handy.

**Comment by TheLastRar** [comment]
Sparse files is a feature of the filesystem (`NTFS`, `ReFS`, `ext` (any version), `Btfs`, `APFS` all support sparse files, but `HFS+`, `FAT32` and `exFAT` don't).

Creating sparse files do require platform specific code, but the file contents are (mostly) the same.

Copying sparse files requires that any storage medium used, and the transfer method used, supports sparse files, otherwise the file may become non-sparse and grow to its full size,

I suspect in your case, the file became non-sparse as you transferred it to the Steam Deck.

Interesting about `qemu-img` and `dd`, not sure what would cause the issue.
