### ISSUE TITLE
[Feature Request]: PC ip settings in PS2 IP TextBox (Network Settings)

### ISSUE THREAD

**Issue by Danik2343** [PCSX2/pcsx2#5405]
### Description

Please add the PC IP checkbox to the PS 2 IP settings so that you don’t have to insert IP yourself, it doesn’t work without it

### Reason

Without PS2 ip, couldn't connect to internet

### Examples

CLR dev9 has checkbox, named "PC IP"

**Comment by TheLastRar** [comment]
To clarify the purpose of CLR_DEV9's PC IP checkbox does

The setting is only usable with winsock, and had no effect in PCAP of TAP mode

With PC IP disabled. the winsock assigns the PS2 the IP 192.0.2.100 and effectively performs NAT to the correct address

For LAN games, I had assumed that some games might send their own IP outward, which in the case of 192.0.2.100, would not be valid
So PC IP was introduced to handle such situations, which, along with a few other internal changes, sets the PS2 IP to that of the local PC

This, in combination with the ability to open UDP ports, allowed LAN games to be played (either as the host or the client)

With respect to PCSX2 Nightly, we only have TAP and PCAP

With PCAP, using your PC's IP is not often not suggested, but specific cases can require it

With TAP, PC's IP should not use be used.

Note that while a PR for sockets support (based on CLR_DEV9's winsock mode) exists, it currently also lacks the PC IP option, as I assumed that LAN games would be better served by TAP or PCAP

**Comment by RedDevilus** [comment]
Perhaps expand the auto checkbox to look  if its PCAP/TAP/winsocks and use the best method.

**Comment by TheLastRar** [comment]
> Perhaps expand the auto checkbox to look if its PCAP/TAP/winsocks and use the best method.

Can you elaborate?

**Comment by RedDevilus** [comment]
When people want/need PCSX2 to have the same IP as the PC (bridged) or just on the network (switched) which normal users won't know the difference to what type or what IP address is one of the examples.

**Comment by MrCK1** [comment]
Has this feature been completed as of 2.0?

**Comment by RedDevilus** [comment]
> Has this feature been completed as of 2.0?

DHCP works better with it atleast, if you go into netconfig and pipes good enough to GUI of PCSX2 netplay.

**Comment by F0bes** [comment]
As mentioned above, you shouldn't need to put your PC IP in the PS2 IP textbox.
