### ISSUE TITLE
in game ridge racer 5 model cars texture is Not seeing the image

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5407]
### Describe the Bug

ridge racer 5 model cars texture is Not seeing the image

### Reproduction Steps

in game ridge racer 5 model cars texture is Not seeing the image

### Expected Behavior

cars texture is render image ok

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx 950m

### GS Settings

basic 1x 

### Emulation Settings

basic

### Logs & Dumps

no

**Comment by refractionpcsx2** [comment]
Duplicate #3639
