### ISSUE TITLE
[BUG]: DragonBall Z - Budokai (USA) (background draw dark)

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5408]
### Describe the Bug

DragonBall Z - Budokai (USA) (En,Ja)
all background in game is dark
![screenshot 6](https://user-images.githubusercontent.com/48321898/151012513-84ffcc2a-87eb-455c-a190-3797faa75eda.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/151012585-c7b91f5d-e02f-4725-881e-a7920551727c.jpg)
![screenshot 1](https://user-images.githubusercontent.com/48321898/151012613-8fdb113c-5b05-4813-8281-2bb9016c9af4.jpg)
![screenshot 3](https://user-images.githubusercontent.com/48321898/151012665-f666c7fe-d6d9-4ae2-a344-3797a03b2ef2.jpg)

### Reproduction Steps

all background in game is dark

### Expected Behavior

background is ok

### PCSX2 Revision

v1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx950m

### GS Settings

basic

### Emulation Settings

basic

### GS Window Screenshots

basic

**Comment by refractionpcsx2** [comment]
Did it ever work?

**Comment by tee4341** [comment]
not ever work (it vulkan render)

**Comment by Squall-Leonhart** [comment]
> Did it ever work?

Only in opengl and software.

**Comment by lightningterror** [comment]
A gsdump of the issue would be nice.

**Comment by lightningterror** [comment]
DX11 needs high blending, every other renderer basic.
