### ISSUE TITLE
[BUG]: Prince of Persia - The Sands of Time Boom shader not in the correct position

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5410]
### Describe the Bug

in game Prince of Persia - The Sands of Time scale 3X Boom shader not in the correct position
![screenshot 1](https://user-images.githubusercontent.com/48321898/151074026-9c8add5d-67ad-4947-9387-7a8f1c24c2b2.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/151074057-56e79528-4428-452c-8b4b-e1b391d7bbf0.jpg)
![screenshot 3](https://user-images.githubusercontent.com/48321898/151074061-eac8ae77-6a22-4747-9dda-45a63b0b5969.jpg)
![screenshot 4](https://user-images.githubusercontent.com/48321898/151074064-17c59359-830c-46c8-b206-118ec7d7859e.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/151074065-3fc43db9-512b-4b17-bbf4-a991a7eda2dc.jpg)

### Reproduction Steps

after scale 1x position is ok
![screenshot 6](https://user-images.githubusercontent.com/48321898/151074268-4043bdc4-c9fd-45a1-81fe-4e1dcec829ae.jpg)

### Expected Behavior

position ok

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx 950m

**Comment by lightningterror** [comment]
Use pscaling hw backs.

**Comment by kenshen112** [comment]
https://wiki.pcsx2.net/Prince_of_Persia:_The_Sands_of_Time More specifically
