### ISSUE TITLE
[BUG]: Call of Duty 2 - Big Red One texture bug

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5414]
### Describe the Bug

Call of Duty 2 - Big Red One - Collector's Edition (USA) texture bug
![screenshot 1](https://user-images.githubusercontent.com/48321898/151180743-466606a8-752e-49ff-80d2-58a3d70c027f.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/151180744-64455c20-ecb4-4b21-aed0-c924bd314270.jpg)
![screenshot 3](https://user-images.githubusercontent.com/48321898/151180745-0768cde3-11a6-4896-971e-68bc34c2e927.jpg)
![screenshot 4](https://user-images.githubusercontent.com/48321898/151180746-9e58fb3c-2a67-44a7-8768-27ca8063280c.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/151180748-e5ae9abe-6c02-4202-91e7-4c6e309927b9.jpg)

![screenshot 6](https://user-images.githubusercontent.com/48321898/151180725-cb5e8cc0-1e1c-4e54-8567-aa3c358b56d1.jpg)
![screenshot 7](https://user-images.githubusercontent.com/48321898/151180733-4e8804b5-48ae-4ada-a840-9b7baa234915.jpg)
![screenshot 8](https://user-images.githubusercontent.com/48321898/151180735-dcac82da-8087-4515-9b4a-05f4e3c4b354.jpg)
![screenshot 9](https://user-images.githubusercontent.com/48321898/151180736-c3cb7ecf-472b-4d17-8bc6-9d406685631b.jpg)
![screenshot 10](https://user-images.githubusercontent.com/48321898/151180738-d523c422-5f88-4e0c-a601-4447209fd49e.jpg)
![screenshot 11](https://user-images.githubusercontent.com/48321898/151180740-dae917f1-8ab9-43d8-a15c-6c9e3fc1c386.jpg)
g

### Reproduction Steps

all bug DirectX 11 opengl vulkan  
but software render is ok(very slow) 
DirectX11 is best speed

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx 950m

**Comment by JordanTheToaster** [comment]
Already known currently only playable in software.

**Comment by lightningterror** [comment]
#3138
