### ISSUE TITLE
[BUG]: Skipdraw not disabled when hacks are disabled.

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5416]
### Describe the Bug

Title says it all

### Reproduction Steps

Enable GS hacks, apply some skipdraw values that are easy to tell ingame if they're in effect, then disable GS hacks. Skipdraw acts like that didn't just happen.

### Expected Behavior

Should respect the master switch for hacks and be disabled when the hacks checkbox is off.

### PCSX2 Revision

r2279

### Operating System

Windows 11 but most likely agnostic.

**Comment by lightningterror** [comment]
Try #5417 and see if it's fixed.

**Comment by coornio** [comment]
Works as intended, you may merge and also close this issue. :)
