### ISSUE TITLE
[BUG]: Buzz Mega Quiz emulated buzzers broken key press

### ISSUE THREAD

**Issue by Chupa4542** [PCSX2/pcsx2#5418]
### Describe the Bug

There is a known issue in the add-in used for USB devices that has been merged to the PCSX2 core, however the issue remains.

When launching the game the blue button is pressed constantly without player input and this causes the game to be unplayable as it keeps pressing it, this also appears to be the only Buzz game with this issue.

The issue was reported here a bit over a year ago: https://github.com/jackun/USBqemu-wheel/issues/37

I was unable to find a tracker for it so creating this to have it logged properly under PCSX2.

### Reproduction Steps

1. launch game and see breakage

### Expected Behavior

Button input should only happen when you press them.

### PCSX2 Revision

v.1.7.2281

### Operating System

Windows 10 (64bit)

### CPU

i5-10400f

### GPU

R9 290

**Comment by Chupa4542** [comment]
The issue doesn't seem to always happen either, started the game once after updating PCSX2 and it worked, then after a reboot it broke again.

**Comment by Florin9doi** [comment]
#4990

**Comment by Chupa4542** [comment]
Thank you very much, seems it was difficult for me use the search bar properly!
