### ISSUE TITLE
[BUG]: Jak 3 broken textures

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#5429]
### Describe the Bug

I updated emulator to v1.7.2282 and noticed black squares on textures in Jak 3. Nothing can fix it.

### Reproduction Steps

Just boot the game in HW mode.

### Expected Behavior

Textures without black squares.

### PCSX2 Revision

After v1.7.2281

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-01-30 23-07-20](https://user-images.githubusercontent.com/90133207/151715788-fb08493e-2bf6-44d9-b9df-2fccaecab753.png)

### Emulation Settings

![Screenshot 2022-01-30 23-07-48](https://user-images.githubusercontent.com/90133207/151715785-3c1d87e7-a48e-49af-8f9f-e23d51253c03.png)

### GS Window Screenshots

![Screenshot 2022-01-30 22-56-02](https://user-images.githubusercontent.com/90133207/151715730-f43afdcc-eae8-4535-8bb5-42291e1ef3b1.png)

**Comment by refractionpcsx2** [comment]
#5433 fixes this
