### ISSUE TITLE
[BUG]: Rally Fusion - Race of Champions (USA) car texture bug

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5431]
### Describe the Bug

Rally Fusion - Race of Champions (USA) SLUS-20361 (1.02) car texture bug (game run is slow)

![screenshot 1](https://user-images.githubusercontent.com/48321898/151719532-43f30232-ed4d-424c-9d1f-626fa2432940.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/151719535-934b8deb-bd4e-44a2-b8d4-b772ed3c6513.jpg)

### Reproduction Steps

in game play only

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx 950m

**Comment by Mrlinkwii** [comment]
can you post a GS  Dump for me :)

**Comment by F0bes** [comment]
[Rally Fusion (USA).zip](https://github.com/PCSX2/pcsx2/files/8008394/Rally.Fusion.USA.zip)

Here are a couple of GS Dumps.

Software mode fixes it, I'm guessing texture cache.
