### ISSUE TITLE
[BUG]: Driver 4 - Parallel Lines (JP) still loading times?

### ISSUE THREAD

**Issue by qamichele594** [PCSX2/pcsx2#5434]
### Describe the Bug

The game has huge frameskips while playing for a few minutes, and has graphic glitches on screen.

### Reproduction Steps

Just launch the game

### Expected Behavior

No response

### PCSX2 Revision

v1.7.2120

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

No response

### CPU

Both

### GPU

Both

### GS Settings

No response

### Emulation Settings

No response

### GS Window Screenshots

No response

### Logs & Dumps

No response

**Comment by qamichele594** [comment]
[How caused this GBARunner2 issue from SA1 and SA2 Copyprotection locked out in GBARunner2? The USA version boots indefinitely, but the Japanese version does.](https://github.com/Gericom/GBARunner2/issues/247)

**Comment by refractionpcsx2** [comment]
Duplicate #451
