### ISSUE TITLE
[BUG]: Corvette: Ghosting effect on buildings and car models + Broken building and object textures

### ISSUE THREAD

**Issue by Hemporus01** [PCSX2/pcsx2#5435]
### Describe the Bug

There seems to be some kind of ghosting effect happening on the buildings and car models as well as some broken textures on some buildings and objects in HW mode. SW mode does fix the ghosting effect, but not the broken building and object textures.

### Reproduction Steps

Make sure your in hw mode and go to the career mode car select screen. There you should see the ghosting surrounding the car model. To see the ghosting + broken textures on the buildings and objects, select the first track in the career mode and get ingame.

### Expected Behavior

I expected to not be able to see this ghosting effect or the broken building textures.

### PCSX2 Revision

v1.7.2290

### Operating System

Windows 10 (64bit)

### CPU

i5-11600

### GPU

GTX 1080 Ti

### GS Settings

<img width="264" alt="Capture 1" src="https://user-images.githubusercontent.com/97992262/151752743-5ca31b7e-6739-4586-bb90-19e650604373.PNG">
<img width="263" alt="Capture 2" src="https://user-images.githubusercontent.com/97992262/151752763-cbcd1af9-fd66-403b-9502-e08e153efcf6.PNG">
All that is highlighted are the non-defaults.

### Emulation Settings

Defaults were used.

### GS Window Screenshots
![Inkedgs_20220204111108_LI](https://user-images.githubusercontent.com/97992262/152574076-f5e1fc60-02c8-44f0-8c11-01822163c3bb.jpg)
![Inkedgs_20220131005031_LI](https://user-images.githubusercontent.com/97992262/151754437-27afe217-dcaf-4739-a901-5ecbb9f806a4.jpg)
![Inkedgs_20220131005109_LI](https://user-images.githubusercontent.com/97992262/151755036-45b52ec2-dd2b-46c8-83dd-7211b0ad797d.jpg)
![Inkedgs_20220131005122_LI](https://user-images.githubusercontent.com/97992262/151755104-151f42fd-aed1-423d-b8c4-ab98c852a90f.jpg)
![gs_20220131005234](https://user-images.githubusercontent.com/97992262/151755162-69a1b16d-f4af-485b-9ad3-fcad2b6fe452.png)
SW mode fixes the ghosting, but the broken textures still appear.
![Inkedgs_20220131011726_LI](https://user-images.githubusercontent.com/97992262/151755854-eb0eb620-36d7-476f-803a-4e4ef57bfaf1.jpg)
![Inkedgs_20220131011646_LI](https://user-images.githubusercontent.com/97992262/151755868-07889b48-96c7-47ac-8e1f-9d4809469e7f.jpg)

### Logs & Dumps

[Corvette Ghosting + Broken building and object textures GSdump.zip](https://github.com/PCSX2/pcsx2/files/7968952/Corvette.Ghosting.%2B.Broken.building.and.object.textures.GSdump.zip)

**Comment by refractionpcsx2** [comment]
can you try enabling the EE timing hack or Force Path3 FIFO under the Config->General Settings then Gamefixes.  Doesn't look like this is a GS issue (since it's broken in the same way in SW)

**Comment by Hemporus01** [comment]
I'll try

**Comment by Hemporus01** [comment]
Didn't work still the same result

**Comment by refractionpcsx2** [comment]
Damn, okay, I tried this myself and it is indeed weird, nothing seems to fix it.. annoying.

**Comment by refractionpcsx2** [comment]
I think it is a GS problem, possibly CLUT related, but if affects both renderers, so it *might* not be too terrible to fix, hopefully...

I texted 1.6 with ZeroGS and the problem doesn't happen.

**Comment by refractionpcsx2** [comment]
#5475 will fix this, spent the evening debugging it, found the problem :)

**Comment by Hemporus01** [comment]
Its all fixed.
![gs_20220204215537](https://user-images.githubusercontent.com/97992262/152627905-24a38c46-361d-4a40-83e0-bb6b97ad7ba0.png)
