### ISSUE TITLE
[Core issue] DBZ Budokai Tenkaichi 2 and 3 [NTSC&PAL]

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#544]
**Core issue**:

-Issue title: flickering stripes while battling in stages. 
-PCSX2 version: latest stable version (1.2.1) & Development build (v1.3.1-58-g5ed3f5f)
-PCSX2 options: Defaults, no settings modifications affect the issue.
-Plugins used: GSdx & ZeroGS , SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins
-Plugin settings: Defaults, no settings modifications affect the issue

-Description: buggy landscape/ground with flashing flikering stripes and polygons especially when flying, varies in intensity from stage to stage, more noticeable when the player is present in higher altitudes, This is more likely to be a core issue since, The Issue was also present in ZeroGS.

-How to replicate: Start a duel with namek as the fighting location. (it's more noticeable on the specific location) then, Take a look at the ground and the green water of the location it will usually be filled with flickering black stripes. 

-Last known version to work: Never worked.

[References] 
GIF: https://gfycat.com/AdorableInsistentGoa
Video: https://www.youtube.com/watch?v=0vr7rXBEI8A&hd=1  (At 0:12 you can see the Issue. And at 0:29 it's even more apparent.)
GS dump: http://lastfencer.net/gsdx_20150511204417.gs

**Comment by mirhl** [comment]
Mhh... that definitively reminds me of the mipmapping issue in Ace Combat. 

Does it also happen in software mode?

**Comment by ssakash** [comment]
yes, all the renderers have this issue. maybe @gregory38 can take a look at this ?

**Comment by refractionpcsx2** [comment]
That looks like a z-fighting issue.  So software renderer does it also?

**Comment by ssakash** [comment]
what's a z-fighting issue ? answering your initial question yes, the issue is actually less noticeable in software mode because of it's native resolution but the issue is still present.

**Comment by refractionpcsx2** [comment]
z-fighting is when 2 textures end up flickering on top of each other because they share the same depth/position and the gpu isn't sure which one goes on top, so you get that flickering effect

Here's a static example in Unity: https://youtu.be/f7zDKlsyu6s?t=145

As you can see when he moved the object/camera the textures flicker as they "fight" to be on top, thats what the game is doing

**Comment by ssakash** [comment]
Nice Information. How could we set a specific texture as a preference to end up on top ?

**Comment by refractionpcsx2** [comment]
We don't specifically, that was down to the dev, our problem is probably z-depth precision. Does it also do it in OGL?

**Comment by gregory38** [comment]
Depth is provided by the primitives (triangle, quad ...). GS accuracy is 32 bits integer. Best GPUs are 32 bits float roughly equivalent to 24 bits integer. So from the GPU point of view 0xF7654321 == (0xF7654321 + 0x10) !

There  is some option to control depth in opengl
* ```override_GL_ARB_clip_control == 1 ``` behave like DX
* ```override_GL_ARB_clip_control == 0 ``` behave like old OGL (lost 1 bit of accuracy for small depth value). In this mode you can then tune the way depth is computed
  1. ```logz = 1``` use log2(z) help in some case to restore the accuracy but break some games that need correct depth value
  2. ```logz = 0``` linear z, in theory more z fighting (again for small depth)

Potentially it would be interesting to invert the depth Zi = 1 - Z. This way it would be more accurate in the far plan instead of the near plan. But it might break the near plan.

On openGL, it is possible to generate a depth texture of 32 bits integer
* No more stencil possible (used for date effect)
* I think the shader still output a float position anyway so I'm not sure it would be better.

**Comment by ssakash** [comment]
@refractionpcsx2 
> yes, all the renderers have this issue. 

@gregory38 
I'll try changing those variables and check out.

**Comment by gregory38** [comment]
If the SW renderer has the issue
1/ either isn't a depth fighting issue
2/ Or values generated by the VU are wrong

**Comment by refractionpcsx2** [comment]
That is also possible. You could try putting full clamping on the vu or change the rounding mode to see if it resolves it.

**Comment by ssakash** [comment]
tried all the combination of clamping/rounding modes and it doesn't help. @ryudo also confirmed this.

**Comment by ssakash** [comment]
tried all the combination of clamping/rounding modes and it doesn't help. @ryudo also confirmed this.

**Comment by ssakash** [comment]
tried all the combination of clamping/rounding modes and it doesn't help. @ryudo also confirmed this.

**Comment by refractionpcsx2** [comment]
Have you tried the different VU's like superVU and interpreters? also try EE interpreter just in case.  I wouldn't do them all at the same time :P

**Comment by ssakash** [comment]
I might try using the superVU recompiler later, though seriously it would take years to enter the battle on interpreters. :p

**Comment by refractionpcsx2** [comment]
That's fine, enter the battle first then switch to interpreters :P should be able to do it on the fly

**Comment by ssakash** [comment]
I checked using superVU recompiler and the issue still persists, @Ryudo confirmed that interpreters also had the issue.

**Comment by ssakash** [comment]
@refractionpcsx2 

If the problem it isn't on the VU side then, what would cause this problem ? should I check any older versions and try locating where it was triggered ?

**Comment by refractionpcsx2** [comment]
If it's not the vu's then there is an internal emulation error in the gs plugins

**Comment by ssakash** [comment]
could you provide some examples ? I have never encountered such issues.

**Comment by refractionpcsx2** [comment]
Not off hand no, issues like this are rare these days,  it could be some weird draw ordering thing or trying to draw textures which shouldn't be textures,  or bad shadows, could be anything

**Comment by ssakash** [comment]
Thanks for the information. Maybe Bositman (or) psuedonym wil look into it.

**Comment by gregory38** [comment]
@ssakash do you still have the gs dump on your PC? The link is dead.

**Comment by ssakash** [comment]
Nope, don't have a GS dump of it right now.

**Comment by lightningterror** [comment]
Will this do ?
https://drive.google.com/open?id=0B8cQAq-Ko9-uVFo3d0dMdTlaOVU

**Comment by gregory38** [comment]
@refractionpcsx2 
Fwiw, the SW renderer uses float for the rasterization. So it won't work if the game uses the full 32 bits integer range (such as Arc The Lad). However I don't understand how the hardware manage to implement the rasterization of integer.

I gave a look at the dump. I don't know what is the issue but it is maybe not related to depth actually.

**Comment by lightningterror** [comment]
Both hardware and software seem to have the issue. Software far less tho so it's not much visible.

**Comment by lightningterror** [comment]
Budokai Tenkaichi 2 also experiences the same issue. Safe to assume the first one is also affected.
