### ISSUE TITLE
[BUG]: SLUS 21127 (Brave: The Search for Spirit Dancer) showing green lines along geometry

### ISSUE THREAD

**Issue by FinishedFragment** [PCSX2/pcsx2#5444]
### Describe the Bug

![ps2 brave](https://user-images.githubusercontent.com/44732327/151893908-551920d3-8b01-4e66-b185-7bae4eb8a23d.png)

As you can see, there are green lines along the geometry in a specific distance, travelling with the camera. This is a regression as it did not happen in older builds, but I did not bisect or check which version works again.

I would rate the severity as minor. It does not harm gameplay but it is annoying to look at.

![ps2 brave sun 2](https://user-images.githubusercontent.com/44732327/151894021-608311c7-7ac4-4cee-bf98-e688e2d532da.png)

Sometimes, you can also see the sun through solid rock, which is also a regression and may or may not be related, but it appears green-ish in color at certain angles, too which is why I am also putting these screenshots here, just to be safe.

![ps2 brave sun](https://user-images.githubusercontent.com/44732327/151894524-bb7d0ad4-9025-4648-b55d-429b4c060564.png)

Sun without the green skeleton-thingy. It was super hard to capture the sun doing that.

### Reproduction Steps

These issues are all reproducible in the very first stage of the game. Just escape from the bear (trivial) and run and jump around a bit. Especially if you jump near the cave leading to the first cave painting, you will see the sun for a fraction for a second which almost looked like some indicator but it is not.

You can also face the cave entry and just move the camera a bit.

The green lines are also reproducible in the opening scene where you can see the squirrel.

### PCSX2 Revision

1.7.2300-1 (git master)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 1600af

### GPU

AMD rx 570 (OC version with 8 GB of VRAM)

### GS Settings

Config files taken from `~/.config/PCSX2/inis`, I had to change the extension to txt because github does not like ini files apparently.

[GSdx.txt](https://github.com/PCSX2/pcsx2/files/7975082/GSdx.txt)
[GS.txt](https://github.com/PCSX2/pcsx2/files/7975083/GS.txt)

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7975070/emuLog.txt)

The repeated GTK warnings are me opening the graphics settings and playing around, also switching to Vulkan and back because it did not change anything except lower the framerate dramatically. Also tried changing blending accuracy (even if it is set to Full) because Jak II had very similar issues with stretched shadows, but it did not change anything.

![gs_20220201015939](https://user-images.githubusercontent.com/44732327/151897883-67546704-eb9c-4f5a-b8f5-f1fc70ed2bf6.png)
[gs_20220201015939.gs.gz](https://github.com/PCSX2/pcsx2/files/7975200/gs_20220201015939.gs.gz)

For the green line thing only, not the sun. I had to unxz the gs dump and gzip it instead because github also dislikes xz

**Comment by prafullpcsx2** [comment]
Using Half pixel offset : Special (texture) and Round Sprite Full seems to fix the issue without causing additional bugs.
