### ISSUE TITLE
[BUG]: FFX Regression Opening Video

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5445]
### Describe the Bug

in the opening video around the camp fire there are supposed be fade-in transitions between camera angles but instead of the fade-in it goes black

### Reproduction Steps

start the game and watch the intro video.

### PCSX2 Revision

1.7.2301

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

**Comment by F0bes** [comment]
Can you try and figure out what commit caused the regression.

**Comment by seta-san** [comment]
so i'm getting different results between what i build myself and what is on the website. in my eithercase it's 2301 that shit the bed. i'm also seeing broken textures.
![gs_20220131205021](https://user-images.githubusercontent.com/8851653/151906304-2cc6bebb-69d1-4a6d-866c-4428e81fef7c.png)

**Comment by seta-san** [comment]
https://www.youtube.com/watch?v=zz0WS4iny48&ab_channel=Seta-San

fade to black in video.

**Comment by lightningterror** [comment]
Should be fixed in #5446
