### ISSUE TITLE
[BUG]: USB wheel device setting causes emulator to crash

### ISSUE THREAD

**Issue by cdf83** [PCSX2/pcsx2#5458]
### Describe the Bug

The emulator fails to start if any "wheel device" is selected under USB Setting _and_ a wheel device is plugged in to the computers USB port.

### Reproduction Steps

- plug in physical wheel device (tested with a Thrustmaster TS-XW)
- Open pcsx2
- Under Config / USB Settings, change port 1 to "Wheel Device" (note Emulated device can be any wheel type)
- Boot ISO
- Emulator will black screen and exit immediately with no error message
- the emulator is now "borked" until you manually delete the USB.ini file, change the USB setting or unplug the USB wheel

Note the issue can be worked around if you launch the ISO _then_ configure the USB device afterwards.

### Expected Behavior

Expect the emulator to start as normal.

### PCSX2 Revision

1.7.2316

### Operating System

Windows 11

**Comment by atomic76** [comment]
I'm experiencing the same problem.
If I boot up with the USB wheel set up, it will be forced to end.
I'm using the Thrustmaster wheel.

<iframe width="1280" height="720" src="https://www.youtube.com/embed/pWQCzn5bRYo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by Unix0815** [comment]
It seems to be the fault of the XAudio 2 SPU2 output module. If you choose Cubeb instead, the emulator doesn't crash.

**Comment by Shogun38** [comment]
> It seems to be the fault of the XAudio 2 SPU2 output module. If you choose Cubeb instead, the emulator doesn't crash.

Thanks I can confirm that workaround did the trick in nightly version 1.7.2995 (wxwidgets). 

Now I have two issues to iron out - The steering wheel misalignment as the race progresses (goes off center). Also mapping buttons isn't working right. I hit O on my wheel to map O and its triangle. Triangle is O. Left paddle ends up being left even though it was mapped to L2, etc.
