### ISSUE TITLE
[BUG]: Ghost Rider: Upscaling issue/Ghosting on Player Burning Skull and Other Bloom Effects (Works Fine in Native Res)

### ISSUE THREAD

**Issue by Mrblubb** [PCSX2/pcsx2#5467]
### Describe the Bug

There seems to be a ghosting/shifting issue on Ghost Rider himself when upscaling. The firey skull and other bloom effects gets misplaced and gets more apparent in higher resolutions in HW mode. Happens will all HW backend when using Non-Native resolution. Can't be resolved by any upscaling alignment hacks or manually entering Texture Offsets.

### Reproduction Steps

Run the game with default settings with Any Non-Native Resolution. (Any HW graphics backend)

### Expected Behavior

Should work fine on upscaling or at least get corrected with alignment Hacks.

### PCSX2 Revision

pcsx2-v1.7.2325-windows-64bit-SSE4

### Operating System

Windows 10 (64bit)

### CPU

FX 8350

### GPU

GTX 1060 6GB

### GS Settings

![Screenshot (218)](https://user-images.githubusercontent.com/88938655/152517426-e7821dc6-0d75-4127-9994-de131baa74af.png)
![Screenshot (219)](https://user-images.githubusercontent.com/88938655/152517432-1d41ab88-321c-416e-a14a-a8ba19374659.png)

### Emulation Settings

![Screenshot (221)](https://user-images.githubusercontent.com/88938655/152517484-7f030caa-b8bb-4242-b1b6-0c8a751eb7ac.png)

### GS Window Screenshots

![Screenshot (215)](https://user-images.githubusercontent.com/88938655/152517529-ec6f7235-1b0b-4f82-812c-f3ca176d7a2b.png)
![Screenshot (216)](https://user-images.githubusercontent.com/88938655/152517534-e8a143f2-917d-465b-ac14-1a2462ec301b.png)
![Screenshot (217)](https://user-images.githubusercontent.com/88938655/152517535-7c8a716f-f322-49aa-b9e7-a54b411ef5a3.png)
![Screenshot (220)](https://user-images.githubusercontent.com/88938655/152517541-47e86517-6549-44d9-bc91-c01f002043fc.png)
![Screenshot (222)](https://user-images.githubusercontent.com/88938655/152518374-86e530b7-60ea-48a0-8d90-5d07f9bf7278.png)

### Logs & Dumps

[Ghost Rider Upscaling issue Dump.zip](https://github.com/PCSX2/pcsx2/files/8002538/Ghost.Rider.Upscaling.issue.Dump.zip)

**Comment by lightningterror** [comment]
If it's upscaling then it's not an issue, try using upscaling hacks.

**Comment by Mrblubb** [comment]
> If it's upscaling then it's not an issue, try using upscaling hacks.

That's the exact problem. None of the upscaling hacks works. I already did mentioned in the issue description.

**Comment by refractionpcsx2** [comment]
The game makes heavy use of bilinearing and upscaling sprites which doesn't translate well while upscaling. the Wild Arms Offset hack seems to position things mostly correctly but some sprites are bigger than they should be and such, there's not, much that can be done about it in a hurry, unfortunately.

**Comment by Mrblubb** [comment]
> The game makes heavy use of bilinearing and upscaling sprites which doesn't translate well while upscaling. the Wild Arms Offset hack seems to position things mostly correctly but some sprites are bigger than they should be and such, there's not, much that can be done about it in a hurry, unfortunately.

That explains the weird issue. Thanks for the detailed explanation. I love this game so just wanted to highlight this issue that's all. Not in a hurry or so. But I wish future updates will eventually fix everything. Greetings to whole pcsx2 team :)
