### ISSUE TITLE
[BUG]: Jak 3 broken again

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#5470]
### Describe the Bug

Broken lava textures in volcano.

### Reproduction Steps

Boot the game in HW mode.

### Expected Behavior

Correctly rendered textures.

### PCSX2 Revision

v1.7.2326

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-02-04 19-42-07](https://user-images.githubusercontent.com/90133207/152567813-9847041f-4100-40cd-88e3-105ce20c4ca0.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/90133207/152565771-dbd114d0-0857-4a73-b3da-fc44d11d35d1.png)

### GS Window Screenshots

![Screenshot 2022-02-04 19-24-26](https://user-images.githubusercontent.com/90133207/152567882-4a2603eb-f38d-43a5-a1b4-e3b6aa2f5997.png)

**Comment by refractionpcsx2** [comment]
can you post a GSDump please.

**Comment by EvilPlayer1** [comment]
> can you post a GSDump please.

[Jak 3 bug.zip](https://github.com/PCSX2/pcsx2/files/8005063/Jak.3.bug.zip)

**Comment by TheTechnician27** [comment]
For the sake of redundancy, I tested this as well and got the same results. It's broken in all three hardware renderers. No graphics setting other than just switching to the software renderer fixes this.

**Comment by refractionpcsx2** [comment]
yeah I'm guessing it's going to be some sort of mipmapping issue, if you could trace when it broke, that would be really useful.

also a GS dump of it with broken textures would also be good!

**Comment by TheTechnician27** [comment]
@refractionpcsx2 I used Shift+F8 three times (one each for those aforementioned distances from the lava), and in my 'snaps' folder, there are three .gs.xz files; I take it those are the GS dumps? If so, then here they are. Hope this helps.
[gs_20220205113227.gs.zip](https://github.com/PCSX2/pcsx2/files/8008499/gs_20220205113227.gs.zip)
[gs_20220205113233.gs.zip](https://github.com/PCSX2/pcsx2/files/8008500/gs_20220205113233.gs.zip)
[gs_20220205113249.gs.zip](https://github.com/PCSX2/pcsx2/files/8008501/gs_20220205113249.gs.zip)

**Comment by FinishedFragment** [comment]
didnt #5387 introduce a mipmapping regression? this could be the cause

**Comment by refractionpcsx2** [comment]
> didnt #5387 introduce a mipmapping regression? this could be the cause

It did but it got resolved.

@TheTechnician27 thanks fort eh dumps

**Comment by TheTechnician27** [comment]
@refractionpcsx2 No problem! Let me know if you want any dumps from Jak X. So far, I've seen the same regression twice there. I might try out Jak II or TPL next.

**Comment by refractionpcsx2** [comment]
This was broken by #3895 

So probably some funny problem with tex in RT handling
