### ISSUE TITLE
[Feature Request]: Add Joystick to DB

### ISSUE THREAD

**Issue by buuf** [PCSX2/pcsx2#5481]
### Description

(GameDB) 9768 games on record (loaded in 142ms)
onepad: Joystick (MY-POWER CO.,LTD. USB Gamepad,GUID:030000005f1400003102000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.onepad: Joystick (MY-POWER CO.,LTD. USB Gamepad,GUID:030000005f1400003102000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

### Reason

I can use the gamepad I purchased to play pcsx2

### Examples

Other emulators have no issue using gamepad in question

**Comment by RedDevilus** [comment]
Can you check the latest 1.7 version? You are using a 1.5 version which is outdated.

**Comment by buuf** [comment]
> Can you check the latest 1.7 version? You are using a 1.5 version which is outdated.

Same message

PCSX2 Nightly - v1.7.2283 Compiled on Jan 30 2022

> PAD: Joystick (MY-POWER CO.,LTD. USB Gamepad,GUID:030000005f1400003102000010010000) isn't yet supported by the SDL2 game controller API
You can use SDL2 Gamepad Tool (https://www.generalarcade.com/gamepadtool/) or Steam to configure your joystick
The mapping can be stored in PAD.ini as 'SDL2 = <...mapping description...>'
Please post the new generated mapping to (https://github.com/gabomdq/SDL_GameControllerDB) so it can be added to the database.
PAD: Joystick (MY-POWER CO.,LTD. USB Gamepad,GUID:030000005f1400003102000010010000) isn't yet supported by the SDL2 game controller API
You can use SDL2 Gamepad Tool (https://www.generalarcade.com/gamepadtool/) or Steam to configure your joystick
The mapping can be stored in PAD.ini as 'SDL2 = <...mapping description...>'
Please post the new generated mapping to (https://github.com/gabomdq/SDL_GameControllerDB) so it can be added to the database.

**Comment by refractionpcsx2** [comment]
Then I suggest you follow the instructions :)

**Comment by buuf** [comment]
> Then I suggest you follow the instructions :)

Used to work in older builds tho... instructions will be followed nonetheless

**Comment by refractionpcsx2** [comment]
okay, well it might have been your profile was removed, but we don't maintain them, so if you want it to work again either add it manually for now or submit it to the links above so it can get readded, and every week we automatically update our database.

Complaining to us isn't going to fix it., it needs to be dealt with upstream.
