### ISSUE TITLE
[BUG]: Jak 3 - Jak's eyes bug when using preload frame

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#5486]
### Describe the Bug

If "preload frame data" hack is enabled, Jak's eyes will be glitched. This hack fixes sky in haven city, so that's why I use it.

### Reproduction Steps

Boot the game in HW mode with "preload frame data" hack.

### Expected Behavior

Jak's eyes mustn't be glitched with that hack.

### PCSX2 Revision

v1.7.2339

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![image](https://user-images.githubusercontent.com/90133207/152677486-41870d99-efce-4097-b871-720bfd70c15c.png)
![Screenshot 2022-02-06 13-43-29](https://user-images.githubusercontent.com/90133207/152677497-8f8ed2ec-d4d3-463d-aa12-ad4caab7ea05.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/90133207/152677520-dcfce31d-6709-4a85-b2d4-c77d641b5be4.png)

### GS Window Screenshots

Preload frame data on:
![Screenshot 2022-02-06 13-42-35](https://user-images.githubusercontent.com/90133207/152677540-9a87732b-14c1-47b7-a1e4-b01837b51b1a.png)
Preload frame data off:
![Screenshot 2022-02-06 13-42-50](https://user-images.githubusercontent.com/90133207/152677554-8ee0817e-516a-417a-9a9f-767383b97789.png)

**Comment by gilderoylockhart01** [comment]
I plan on doing a meta for this, because yeah, preload frame data is a nice option but it still have problems.
