### ISSUE TITLE
GSdx Windows GUI misses various check box

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#549]
Namely:
* A new hack ```UserHacks_AutoSkipDrawDepth```

* 2 openGL option ```accurate_blend```, ```accurate_date```

**Comment by gregory38** [comment]
@ssakash 
The job is for you ;)

**Comment by ssakash** [comment]
sure, I will add them. 

by the way, I have enabled anisotropic filtering for opengl hardware mode [windows GUI] in a PR but, it's still not merged,

**Comment by refractionpcsx2** [comment]
Yes it was https://github.com/PCSX2/pcsx2/commit/ac38ebbf29b4a6de61c5bc62d550d8109bb5c205

**Comment by tsunami2311** [comment]
Dont forget to put info what the hack 2 opengl options use

**Comment by refractionpcsx2** [comment]
What do you mean?

**Comment by karasuhebi** [comment]
I think he means to not forget to add in the info on what the two hacks do.

**Comment by refractionpcsx2** [comment]
Ooh I see

**Comment by tsunami2311** [comment]
I mean what the hack is for and what the 2 opengl things do / are for, I mostly talking about opengl options cause i have no clue what they far

**Comment by ssakash** [comment]
https://github.com/PCSX2/pcsx2/compare/master...ssakash:patch-5

Could anyone compile and check the following commits ? you should test whether a new option called Auto-skip draw depth is present in the HW hacks settings in a neat order and confirm whether it is working using the gsdx.ini file as a reference comparing the UserHacks_AutoSkipDrawDepth variable.

@gregory38 
about the other two options, I guess they should be present at the video plugin settings. should I make a separate tab for Opengl settings like how it is for software mode settings (or) just directly combine it with the hardware mode settings ?

**Comment by ssakash** [comment]
> Dont forget to put info what the hack 2 opengl options use 

where should I add the information for it ? no other option has information related to it in the video plugin settings.

**Comment by gregory38** [comment]
Please open PR it is easier to review code.

On linux I added the 2 options in the HW panel (same as paltex (filtering?)). I already created some descriptions for thoses options.

By the way, I added a third option: ```accurate_colclip``` I wanted to keep it as a debug feature but it seems to fix castlevania games.

**Comment by ssakash** [comment]
I'll make a PR for the AutoSkipDrawDepth (GUI) option , I guess accurate_colclip should also be added with the other two opengl options then.

**Comment by gregory38** [comment]
```
I guess accurate_colclip should also be added with the other two opengl options then.
```
Exactly :+1:

**Comment by ssakash** [comment]
the PR for the three options have been made. https://github.com/PCSX2/pcsx2/pull/570

I guess that finishes the issue then.
