### ISSUE TITLE
[Feature Request]: Discussions about the benefits of having the "DirectX 12" API?

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5492]
### Description

Yeah I know, this is not an especially relevant feature request topic, especially from a non-developper standpoint. But I still think this is worth debating about.

With the DirectX11 backend receiving massive bug fixes and QOL improvements, it's fair to say the progresses made on this API are *gigantic* in every sense of the word.

However, according to what I see in the code and various infos I can get here and there, we are facing some technical difficulties which are hurting the limits of what DirectX11 can support.

Blending and auto-flush are 2 good examples of this, DirectX12, thanks to it's more modern architecture, would allow for better/faster blending support again, according to the infos I get here and there and reading the docs of the API. But Again, I am not a dev so this info will have to be confirmed by someone who actually knows this stuff.

As a end user point of view, DirectX12 brings a fair chunk of extra speed and efficiency in the games that support it, I see no reasons why PCSX2 would not behave the same, and this is confirmed by the vulkan API, which brings serious improvements in that regard.

About UWP, DX11 is indeed supported (thanks stenzek for this info ^^), but we would be loosing efficiency and speed on the Xbox consoles.

Again, I perfectly know this is *paper* stuff as integrating a new API is extremly difficult and again, this topic is just here to discuss about that eventuality, it is NOT a direct "please integrate it" request like we often see.

### Reason

Better support of newer GPUs.

More efficient/faster rendering path.

Better use of the Xbox GPUs.

Taking advantage of the excellent DirectX 12 support that both AMD and Nvidia offers.

Future proofing.

### Examples

Duckstation does have a DirectX12 render which works really well and allows the UWP port to work beautifully on Xbox consoles.

**Comment by refractionpcsx2** [comment]
You realise if we do DX12 and improve the compatibility to match the other renderers, it'll likely be as slow as, if not slower than vulkan?

**Comment by lightningterror** [comment]
And let's not forget it will suck on AMD (rov precisely as it was tested on dx11.3 anyway by kojin), only one to benefit would be nvidia on fermi architecture, seems useless as they can still use opengl which has been quite optimized lately, or dx11 anyway.

**Comment by gilderoylockhart01** [comment]
Ok. Didn't know DX12 brings that little to the mix. Thankfully UWP is also DX11 friendly.
