### ISSUE TITLE
[Feature Request]: Replace POPS emulation with emulation of PS1 hardware built-in to PS2 board

### ISSUE THREAD

**Issue by jdoexbox360** [PCSX2/pcsx2#5494]
### Description

The PS2 has used a PS1 chip even when it is not booting up ps1 games and allows for tasks to be distributed among the co-processors. Since early models up until slim models SCPH-700XX had real hardware, there was no emulation. They help reduce glitchy textures.

### Reason

[This video](https://www.youtube.com/watch?v=eL31ojJUgCU&t=711s) mentions how PS1 hardware is incorporated with PS2 hardware in PS2 games even when PS1 is not used. They state a Power PC processor replaced the PS2 chip and emulated PS1. It was not entirely accurate. This does not mean that PCSX2 should have a seperate PS1 emulator along with it but should rather emulate the PS1 hardware on the board of a "fat PS2" model.

### Examples

I have  never seen other PS2 emulators use this feature and I am not a skilled programmer so I was just hoping this feature would at least be considered by the PCSX2 community.

**Comment by F0bes** [comment]
We don't have POPS emulation. We emulate psxmode. The "real hardware" is the IOP.

**Comment by refractionpcsx2** [comment]
What? Why do you think we'd be emulating the PowerPC version? because we use emulation? Are you expecting us to distribute real PS1 hardware? I don't get what you're asking, I'm not sure you do either.

**Comment by kenshen112** [comment]
The only "real ps1 hw" the ps2 had that isn't emulated in some form by pcsx2 due to it not existing on the ps2 is the ps1's GPU otherwise. What was on the ps2 is in pcsx2 at least to some degree.

**Comment by seta-san** [comment]
> What? Why do you think we'd be emulating the PowerPC version? because we use emulation? Are you expecting us to distribute real PS1 hardware? I don't get what you're asking, I'm not sure you do either.

i think he's accusing you of emulating thin ps2 instead of a fat ps2

**Comment by gilderoylockhart01** [comment]
We actually emulate the "real IOP" and it's been since mid-1.5 dev builds that we support the PS1 mode. It have issues, but it's likely to get better over time.
