### ISSUE TITLE
[BUG]: Qt build doesn't respect XDG_STD compile flag

### ISSUE THREAD

**Issue by bsdf** [PCSX2/pcsx2#5496]
### Describe the Bug

The Qt build appears to have a [hardcoded reference](https://github.com/PCSX2/pcsx2/blob/master/pcsx2-qt/QtHost.cpp#L88) to `$HOME/PCSX2` for its data even if the `XDG_STD` build flag is present. With this build flag, the proper behavior would be to check `~/.config/PCSX2` instead.

Personally, I think getting rid of `XDG_STD` and the hardcoded home dir and using [`QStandardPaths`](https://doc.qt.io/qt-6/qstandardpaths.html) for config and data locations would be the best solution

### Reproduction Steps

- `cmake -DXDG_STD=1 -DQT_BUILD=1 -DPACKAGE_MODE=1 -DCMAKE_INSTALL_PREFIX=/usr/local/stow/pcsx2 ..`
- `make && make install`
- `/usr/local/stow/pcsx2/bin/pcsx2-qt`
- observe error "Resources directory is missing"

### Expected Behavior

All needed files are present and installed paths in accordance with XDG standard dirs, no error is received

### PCSX2 Revision

061fff6f17efa28654bdf5c61121c78a3d65cf42

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

debian sid

**Comment by RedDevilus** [comment]
Linux doesn't even have a working Qt version at this time.

**Comment by F0bes** [comment]
Qt isn't ready yet and as said above, the Linux side of things hasn't even been worked out.

**Comment by bsdf** [comment]
Hello, I wanted to start dipping my toes into contributing to the project and thought opening a ticket to discuss the behavior, intended behavior, and potentially the proposed change would be better than a PR out of nowhere. I'm not sure what you two mean by not having a working linux version since I'm playing games over here in the Qt version just fine-- certainly working well enough to hack on.

**Comment by RedDevilus** [comment]
That's fine but it's just that we don't accept any Qt issues at the moment as it's in big flux for missing features/screens and other issues and then the issues count would bloat as it's not intended for main usage yet. Besides there is too much other works happening to even track the WIP Qt issues. Qt PRs are a different matter in this context however.

Hopefully you can understand this reasoning.

**Comment by bsdf** [comment]
Makes sense, thanks for the explanation

**Comment by RedDevilus** [comment]
If you still want to discuss Linux issues such as the Qt build then you could join the Discord as there is a development channel that is more appropriate than GitHub and people (contributors, fans, etc) are more open for discussion there.
