### ISSUE TITLE
Formula One 2003 - Graphics Issue!

### ISSUE THREAD

**Issue by SySy233** [PCSX2/pcsx2#5497]
### Describe the Bug

Glitching, polygons everywhere but runs fast and smooth.

### Reproduction Steps

Just starting the game produces weird issues on the menu, gameplay

### Expected Behavior

Running perfectly & accurate graphics

### PCSX2 Revision

v1.7.2345

### Operating System

Windows 10 (64bit)

### CPU

FX 6300 Black Edition

### GPU

AMD Radeon HD 7700

### GS Settings

Native resolution, safe settings

### GS Window Screenshots

![gs_20220206234710](https://user-images.githubusercontent.com/91321762/152707133-fb05f6eb-ecf9-47ff-8dc1-3f9fdd2d88f4.png)
![gs_20220206234716](https://user-images.githubusercontent.com/91321762/152707135-82818f22-ffc3-46fe-b6ae-e8b04673567a.png)
![gs_20220206234720](https://user-images.githubusercontent.com/91321762/152707136-cd8be7aa-a497-43a2-9d78-d737c73016f0.png)
![gs_20220206234747](https://user-images.githubusercontent.com/91321762/152707138-76bba6ac-0348-4b8e-977c-0e7ee85832d0.png)
![gs_20220206234752](https://user-images.githubusercontent.com/91321762/152707139-1cd6c23b-5aa2-48fc-86f2-7d8afe76f843.png)
![gs_20220206234754](https://user-images.githubusercontent.com/91321762/152707141-15b589ec-1960-464b-bc30-2725a0858c37.png)
![gs_20220206234755](https://user-images.githubusercontent.com/91321762/152707144-b36fc6eb-cb47-4229-af76-bffc6cc31776.png)
![gs_20220206234758](https://user-images.githubusercontent.com/91321762/152707146-4b6c37e8-d8e5-47fa-856d-de7cbf439cb9.png)
![gs_20220206234800](https://user-images.githubusercontent.com/91321762/152707147-fe87f9a5-4350-41fe-98ed-019183f81719.png)

**Comment by refractionpcsx2** [comment]
Enable the XGKick gamefix.

**Comment by SySy233** [comment]
![gs_20220207001224](https://user-images.githubusercontent.com/91321762/152707724-487f7dfd-b432-45c0-90d4-65a68c691739.png)
![gs_20220207001243](https://user-images.githubusercontent.com/91321762/152707726-a9af50fe-1e2e-4b85-85d8-dfdfa3af06be.png)
![gs_20220207001252](https://user-images.githubusercontent.com/91321762/152707727-71024931-9505-463b-bfb2-087c3e0ae1f6.png)

The VU XGKick Sync fix has resolved the issue but it now runs between 30-50FPS.
PS: Automatic Fixes is ticked & all my folders were extracted already (minus the cheats_ws zip file)

Thanks :-)

**Comment by refractionpcsx2** [comment]
if you need further assistance please join our discord

**Comment by SySy233** [comment]
I will do, thank you for the fix
