### ISSUE TITLE
[BUG]: PS2 Linux Disc 2 (PAL) is not properly recognized as a PS2 disc.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5500]
### Describe the Bug

When running the disc 2 of the Linux package released in the PAL region, PCSX2 will behave strangely and lead directly to the BIOS at the "insert a PS1/2 disc screen".

### Reproduction Steps

Load PS2 Linux disc 2 in PCSX2.

### Expected Behavior

The emulator should recognize the disc as a PS2 software.

### PCSX2 Revision

v1.7.2350

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

**Comment by refractionpcsx2** [comment]
It's a pain because our disc detection doesn't like the second disc, so we kind of have to cheat..

does the disc not have a file called P2L_0100.02 in the root? does it have something similar?

**Comment by gilderoylockhart01** [comment]
Here is the file structure of the disc:

![image](https://user-images.githubusercontent.com/90222976/152872306-32da265a-9abd-4b5a-91e6-bbf0220f0847.png)

**Comment by refractionpcsx2** [comment]
hmm then that should properly get picked up by the latest dev builds, since that file is there.

**Comment by gilderoylockhart01** [comment]
Nope... the BIOS doesn't like it still.

![image](https://user-images.githubusercontent.com/90222976/152873367-b8759c02-9a95-48a1-ab51-40ab1e89197d.png)

**Comment by refractionpcsx2** [comment]
why are you trying to boot from it? it's not bootable.

**Comment by refractionpcsx2** [comment]
> Can confirm the bug with the NTSC version, but only on 64 bit, 32 bit works fine.

can you show me the contents of the disc? Again you cannot boot it from the BIOS, you never should be able to, you boot disc 1 then swap to it, but i you can't do that, I need to see the content of the disc so I can add the file reference.

**Comment by gilderoylockhart01** [comment]
My bad, sorry, we can close this non-sense. I tested the 2 discs on my real console and yup, it's the same, the disc 2 can't boot in bios, and PCSX2 properly matc what the console does.

Actually, it partially boot Linux but stops here because of what I guess, VTLB? If I recal?

![image](https://user-images.githubusercontent.com/90222976/152874910-19bb7627-cbe2-41ad-a8f4-cea969918f52.png)

**Comment by fantesykikachu** [comment]
> yes we don't emulate enough of the TLB to boot/install linux.
> 
> FYI the second disc doesn't have an ELF file or a SYSTEM.CNF, that's why it isn't bootable.

Well there is still a difference between 64 bit and 32 bit versions.

**Comment by refractionpcsx2** [comment]
yeah, I got that, I'm testing it.

**Comment by gilderoylockhart01** [comment]
I only tested live mode, oops.

**Comment by refractionpcsx2** [comment]
@fantesykikachu I just tried the EU version on both 32bit and 64bit and there was no problem at all.

As a bonus I even tested it with the new Qt interface on 64bit and that was also fine.

**Comment by fantesykikachu** [comment]
yup sorry your right, tried with a clean configuration and 64 bit works.

**Comment by gilderoylockhart01** [comment]
Be careful with the texture cache in hardware mode [fantesykikachu](https://github.com/fantesykikachu) because PS2 Linux *just* got fixed by one of the recent tex cache commits.

**Comment by gilderoylockhart01** [comment]
Btw QT doesn't like recognize it properly in the game list:

![image](https://user-images.githubusercontent.com/90222976/152877132-5575c440-d9fc-4851-a1c5-e669b4b8f39a.png)

**Comment by refractionpcsx2** [comment]
Well yeah, it's looking for a SYSTEM.CNF and ELF file, which doesn't exist.  But at least it's there, and you can pick it.
