### ISSUE TITLE
[BUG]: Jak II and 3: 'SCEA presents' splash screen cut in half on hardware renderer

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#5502]
### Describe the Bug

When booting the games Jak II and Jak 3, the right half of the splash screen that reads "Sony Computer Entertainment America presents" etc. is completely blacked out.

![SCEA presents glitched](https://user-images.githubusercontent.com/12673964/153042242-241d4aaa-ec92-4c6c-b523-0ab17f83502e.png)

### Reproduction Steps

Boot Jak II or Jak 3 on any hardware renderer (fast and normal boot both do this) with default settings (increasing or decreasing resolution does nothing).

### Expected Behavior

When booting up Jak II and Jak 3, a splash screen appears which reads "Sony Computer Entertainment America presents" followed by some smaller legal statements.

![SCEA presents](https://user-images.githubusercontent.com/12673964/153041738-233d83a2-5944-4871-ba20-9fa8dcbf1120.png)

### PCSX2 Revision

1.7.2351

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 1700

### GPU

GTX 1070

### GS Settings

* D3D11, OpenGL, and Vulkan renderers
* Attempted with and without memory wrapping
* 'Show Speed' enabled in OSD
* Software rendering "works" but provides its own issue with the boot screen that says "PlayStation 2" (the words start in the right position but then warp to the bottom of the screen about 2/3 of the way through; see image). Note that this issue does not occur on hardware renderer.

![PlayStation 2 splash screen](https://user-images.githubusercontent.com/12673964/153042822-4004d457-e494-4580-ad10-57ea56f94ec5.png)

### Emulation Settings

* Attempted with and without MTVU.

### Logs & Dumps

GS dump for the SCEA screen (Jak 3): [gs_20220208113809.gs.zip](https://github.com/PCSX2/pcsx2/files/8026179/gs_20220208113809.gs.zip)

GS dump for the SCEA screen (Jak II): [gs_20220208113533.gs.zip](https://github.com/PCSX2/pcsx2/files/8026173/gs_20220208113533.gs.zip)

GS dump for the PS2 text (taken on Jak II): [gs_20220208113404.gs.zip](https://github.com/PCSX2/pcsx2/files/8026171/gs_20220208113404.gs.zip)

**Comment by refractionpcsx2** [comment]
does the "Preload Frame" hack option fix it?

**Comment by TheTechnician27** [comment]
Looks like it does!

**Comment by TheTechnician27** [comment]
I'll go ahead and add it to the Wiki pages. Thankfully, this doesn't affect The Precursor Legacy or Jak X, since those don't have the screen in question.

**Comment by refractionpcsx2** [comment]
they do have a similar screen, which doesn't show without preload, at least on Precursor

**Comment by TheTechnician27** [comment]
Oh, wow. I grew up with TPL and totally forgot that screen was there since PCSX2 never shows it. I'll check Jak X in software mode and see if anything's missing there too, then.
