### ISSUE TITLE
[BUG]: The Cat in the Hat – a few minor graphical bugs

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#5507]
###Update:
It looks like Bug 3 was actually a problem with Software mipmapping. Hardware mode correctly emulates the intended behavior. Moreover, Software mipmapping causes blurry background textures, e.g. a large sock in Wishy Washy.

### Describe the Bug

**Bug 1:** What should be solid grass textures have conspicuous tears in them on the level Venus Cat Trap. This is present in all hardware renderers, but it's more pronounced if you upscale it.

**Bug 2:** What should be dithering on grass is instead a solid, flickering texture. In the screenshot below, look at the very upper right patch of grass and look for yellow-ish pixels in software mode. That's the dithering.

**Bug 3:** This one actually seems like it should be the other way around. Water droplets in certain areas (namely ones that cross white fog) create these black streaks across the screen in software mode but fail to do so in hardware mode.

**Bug 4:** ~~Sun doesn't show up in the background of Musical Madness.~~ Issue fixed; tested on the latest 1.7.4118.

~~**Bug 5:** Heat shimmer doesn't render in the furnace on Boiler Bonanza.~~ Not technically a bug; this is fixed by enabling Auto Flush.

### Reproduction Steps

**Bugs 1 and 2:** Enter Venus Cat Trap. Get to where the Cat is in the screenshots (it's right at the beginning) and move around a bit until you hit the right spot with the hardware renderer active. It's easier to see with upscaling, but it's still present at native resolution.

**Bug 3:** This is most pronounced near the end of Venus Cat Trap near the goldfish statues (see below).

**Bug 4:** ~~Go where I am near the end of the Musical Madness stage with hardware renderer active. That, or go to the first area of the level Freezer Burn.~~ Issue fixed; tested on 1.7.4118.

~~**Bug 5:** Look at the in-level furnace on hardware renderer and without Auto Flush enabled.~~ Not technically a bug; this is fixed by enabling Auto Flush.

### Expected Behavior

**Bug 1:** The grass texture should be solid.

**Bug 2:** The grass in the upper right corner should have some sort of dithering effect. Instead, the texture flickers every couple seconds.

**Bug 3:** Certain water droplets should create ugly, black lines over white fog.

**Bug 4:** The Sun should show up and have a glare as well. This same glitch occurs in the level Freezer Burn. The glare can be re-added by using the 'Preload Frame Data' hack, but the Sun itself remains absent.

~~**Bug 5:** There should be a wavy heat shimmer effect.~~ Not technically a bug; this is fixed by enabling Auto Flush.

### PCSX2 Revision

1.7.2351

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 1700

### GPU

GTX 1070

### GS Settings

Default settings. Tried on all hardware renderers.

### Emulation Settings

* MTVU enabled

### Bug 1:
##Software mode
![Software](https://user-images.githubusercontent.com/12673964/153264273-f7020b59-ca25-45dc-a5f7-2d0e43b598e4.png)

##Hardware mode (native)
![OpenGL native](https://user-images.githubusercontent.com/12673964/153264289-5c8ee420-8915-4736-b9bf-017b85f91360.png)

##Hardware mode (4x native)
![Vulkan 4x](https://user-images.githubusercontent.com/12673964/153264243-ba2ab1bd-6d6a-4d5f-b4a3-700f9107283c.png)

### Bug 2:
##Software mode
![gs_20220209115401](https://user-images.githubusercontent.com/12673964/153263899-ddb4fb82-aecf-4a24-9326-406b214e3160.png)

##Hardware mode
![gs_20220209115349](https://user-images.githubusercontent.com/12673964/153264028-8d649115-e40a-432d-8f6b-bc7e76645557.png)

### Bug 3:
##Software mode
![Black lines software](https://user-images.githubusercontent.com/12673964/153277822-02858529-0e65-48d9-a460-454ee3ff4f4e.png)

##Hardware mode (upscaled, but still present in native)
![Hardware no lines](https://user-images.githubusercontent.com/12673964/153277850-d5fe9002-f765-42d4-b0f8-ea8bcbb4e48b.png)

### Bug 4:
##Software mode
![Musical Madness software](https://user-images.githubusercontent.com/12673964/153282003-6bbc56c2-5f8d-405a-89c5-e2c27df35e56.png)

##Hardware mode
![Musical Madness hardware](https://user-images.githubusercontent.com/12673964/153282013-b13e86ce-fda9-4849-a9c5-13ec485ae594.png)

###Bug 5: (Note: not technically a bug; this is fixed by enabling Auto Flush.)
The differences are pretty small when viewed in an image; it's in motion where it becomes most apparent something's wrong.

##Software Mode
![Heat Shimmer](https://user-images.githubusercontent.com/12673964/153318082-127262f2-9d71-4510-9c82-5199ec60e877.png)

##Hardware mode
![No Heat Shimmer](https://user-images.githubusercontent.com/12673964/153318105-8ec9689b-e243-49d2-b22f-d674af83caa8.png)

### Logs & Dumps

**Bug 1 and 2:** [gs_20220209115349.gs.zip](https://github.com/PCSX2/pcsx2/files/8035173/gs_20220209115349.gs.zip)

Both bugs were present in the area where these GS dumps were made, so it should contain information for both.

**Bug 3:** [gs_20220209134000.gs.zip](https://github.com/PCSX2/pcsx2/files/8035700/gs_20220209134000.gs.zip)

**Bug 4:** [gs_20220209140832.gs.zip](https://github.com/PCSX2/pcsx2/files/8035877/gs_20220209140832.gs.zip)

**Bug 5:** [gs_20220209191559.gs.zip](https://github.com/PCSX2/pcsx2/files/8037270/gs_20220209191559.gs.zip) (Note: not technically a bug; this is fixed by enabling Auto Flush.)

**Comment by tee4341** [comment]
how to make gs dump

**Comment by TheTechnician27** [comment]
You can use Shift + F8 for a single-frame dump or Ctrl + Shift + F8 for multiple frames, but you should be fine with Shift + F8 in most cases.

**Comment by lightningterror** [comment]
Can this be re tested, unable to reproduce issues 1,2,3.
For issue 4 Preload Frame Data hack helps a bit.

**Comment by TheTechnician27** [comment]
> Can this be re tested on latest dev, unable to reproduce issues 1,2,3. For issue 4 Preload Frame Data hack helps a bit so it should be added in gamedb.

I'm going to be retesting soon, so hopefully some of these will have worked themselves out or already be in the gameDB.

**Comment by refractionpcsx2** [comment]
Hopefully you don't need the preload hack anymore, it should be automatic if it's actually needed.

**Comment by TheTechnician27** [comment]
The game does indeed now render the Sun correctly on that level! I wonder if that issue with the heat shimmer is fixed automatically as well! If it is, then not only is this game 100% definitively better on default hardware settings than it is on software, but in fact there shouldn't exist _any_ perceptible issues on hardware mode, and the game could be categorized as Perfect. I seriously scoured this entire game from top to bottom last year looking for issues, and these five were all I could find. The first three seem to actually be issues with software rendering, the fourth one is fixed, and then we'll see about the fifth one!

**Comment by lightningterror** [comment]
> Bad news: the heat shimmer works correctly now, which would've made this game literally flawless on hardware mode. However, #6784 (release 3176) introduces a graphical regression.

You can set blending to Full in the meantime.

**Comment by lightningterror** [comment]
@TheTechnician27 any other remaining issues here?

**Comment by TheTechnician27** [comment]
@lightningterror Yes, I've found that (for example, see bug 1) software's mipmapping dramatically decreases the quality of textures in this game. I was able to show this last year, and I could get back to that level and show it again once I have some spare time. It's visible in other levels too, but there's one part where it's so undeniably obvious that it's the best place for a screenshot.

**Comment by MrCK1** [comment]
If the quality of textures is decreased in SW, then mipmapping should be set in the GameDB to match SW behavior (hardware accuracy).

**Comment by TheTechnician27** [comment]
@MrCK1 I went ahead and checked, and the issue is still there. Here is a single-frame GS dump showing the issue for context (look specifically at the sock in the back left).
[Dr. Seuss' The Cat in the Hat_SLUS-20797_20230806172342.zip](https://github.com/PCSX2/pcsx2/files/12270630/Dr.Seuss.The.Cat.in.the.Hat_SLUS-20797_20230806172342.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/786a64b2-6a95-4ac3-aca5-5e77489d48b2)
mipmapping basic matches  SW 

im gonna bet SW matches real hardware

**Comment by refractionpcsx2** [comment]
This is how it looks on real hardware

![Screenshot 2023-08-07 11-46-43](https://github.com/PCSX2/pcsx2/assets/6278726/6ffd6ecf-9bd0-4be0-99ad-2e12ef7129e2)

**Comment by TheTechnician27** [comment]
Thanks for confirming, @refractionpcsx2. I'll cross out Bug 1 and Bug 2. I wonder if this is a LoD thing, since I've noticed HW mode often has a very slightly higher LoD than SW, maybe owing to some sort of floating point issue where the camera is just slightly closer in HW(?). For Bug 3, I'll go ahead and get a GS dump so I can hopefully close out this issue. Otherwise, having tested it pretty extensively on and off over the last couple years, I can say with a good deal of confidence that the game is emulated perfectly.

**Comment by refractionpcsx2** [comment]
It's possible it's a mipmap bug in software, as it isn't without problems, but yeah I would need a GS dump which does show this to confirm it.

**Comment by TheTechnician27** [comment]
Happy coincidence @refractionpcsx2: I'm no longer seeing this issue, and in fact the rain on SW looks fuller than HW
[Dr. Seuss' The Cat in the Hat_SLUS-20797_202308070.zip](https://github.com/PCSX2/pcsx2/files/12278992/Dr.Seuss.The.Cat.in.the.Hat_SLUS-20797_202308070.zip)
(in a good way) and no longer creates those weird black lines seen in the screenshot. I'll leave a few single-frame GS dumps to show this. At the very least, I'm convinced SW mode runs this game 100% perfectly now, and HW mode is so close to perfect that it may as well be (the only issues I can see are: a select few textures are slightly better on HW mode, and the rain might be slightly different, but I might be seeing it wrong).

**Comment by Mrlinkwii** [comment]
@TheTechnician27  i/you can add mipmapp though the game for HW mode ro fix some/all of the remining HW issues

**Comment by Mrlinkwii** [comment]
@TheTechnician27  any compat is done though the forums ,  your free to make a compat report on the forum and it will be updated then in the gamedb/website

**Comment by TheTechnician27** [comment]
Interestingly, I just noticed a specific case where the SW renderer does considerably better with long-distance texture rendering compared to HW.

If you take a look at the house farthest in the background (near the hat in the hand), the siding is much cleaner with SW mode than HW.

[Dr. Seuss' The Cat in the Hat_SLUS-20797_20230807064043.zip](https://github.com/PCSX2/pcsx2/files/12279216/Dr.Seuss.The.Cat.in.the.Hat_SLUS-20797_20230807064043.zip)

**Comment by TheTechnician27** [comment]
@refractionpcsx2 I think the SW renderer and HW renderer might actually be rendering the background polygons at slightly different distances (ironically, though, I think HW is simultaneously rendering them farther and in greater detail). If you look at the top left sign with the striped hat (as well as the "GAS" sign), you can see the polygons clipping differently depending on which renderer is used.

[Dr. Seuss' The Cat in the Hat_SLUS-20797_20230807065024.zip](https://github.com/PCSX2/pcsx2/files/12279300/Dr.Seuss.The.Cat.in.the.Hat_SLUS-20797_20230807065024.zip)

**Comment by refractionpcsx2** [comment]
the last two dumps look identical in hw and sw with mipmaps full + trilinear (which is what SW uses) the slight differences in geometry is just the difference in how the GPU renders polys
