### ISSUE TITLE
[BUG]: Non-PAD Error

### ISSUE THREAD

**Issue by Scordem** [PCSX2/pcsx2#5517]
### Describe the Bug

Non-PAD Error window appears when executing Boot ISO and force-quits PCSX2.

![pad](https://user-images.githubusercontent.com/56701141/153697034-baf8e897-1511-498a-afc0-55f40e122bdd.png)

This happens regardless of whether the pad is connected or not.
I'm using XBOX One Control Pad.

This problem occurs in v1.7.2357.
It does not occur in v1.7.2316.

### Reproduction Steps

Start pcsx2x64-avx2.exe.
Select chd from the ISO selector.
Run the Boot ISO.
The Non-PAD Error window will appear.

### PCSX2 Revision

v1.7.2357

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Has it created a "bad_shader" file in your PCSX2 folder?

**Comment by Scordem** [comment]
Thanks for the quick reply.
I checked and the bad_shader folder is not created.

**Comment by refractionpcsx2** [comment]
it's not a folder, it'll be a text file.
if there isn't one you need to have your emulog looked at.  Anyway this is more of a support issue so please join our discord, there is an invite link down the left side of https://www.pcsx2.net

Thanks.
