### ISSUE TITLE
Dev9ghzdrk unique MAC not so unique?

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#552]
A while back there was this comment claimed to add a unique MAC address for PCSX2
https://github.com/PCSX2/pcsx2/commit/cf8912eb2cf4f24f972254c751d605dbbb12aa1d

However, virtual_mac seems to be overwritten for every sent packet, making the change seemingly useless https://github.com/PCSX2/pcsx2/blob/master/plugins/dev9ghzdrk/pcap_io.cpp#L160

**Comment by refractionpcsx2** [comment]
I'll look in to this, I must have missed something..

**Comment by TheLastRar** [comment]
On another forum it was found that PCSX2 was getting the MAC address from here https://github.com/PCSX2/pcsx2/blob/master/plugins/dev9ghzdrk/DEV9.cpp#L45, along with a 2 byte checksum of some form.

**Comment by refractionpcsx2** [comment]
That would explain it,  the mac is usually stored in the bios files,  I always forget where :p

**Comment by bositman** [comment]
@refractionpcsx2 Checked it?

**Comment by refractionpcsx2** [comment]
I've been too busy helping with the GSdx stuff to look yet :P I'll take a look over the weekend

**Comment by refractionpcsx2** [comment]
Fixed now, it bases the number off your real MAC and jiggles it about a bit, data according to my router doing the network setup test:

	(The emulator) 192.168.0.12	BC:5F:F4:F4:D6:B8	Ethernet 1
	Reffy-PC	192.168.0.6	BC:5F:F4:FD:B8:D6	Ethernet 1
