### ISSUE TITLE
[BUG]: Ratchet and Clank Going Commando: Glitchy shadows in some specific scenarios.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5524]
### Describe the Bug

In the game "Ratchet and Clank going commando", there is a bug with the shadows where they will produces glitches in some very specific cases.

One of these case is when driving the mining vehicle on Grelbin, when in close proximity with the camera, the shadows will start glitching out by showing missing polygons/holes in geometry.

### Reproduction Steps

Load the GSdump and see the problem, or, take the mining vehicle on Grelbin and drive around those small dunes in the desert, you will see the shadows glitching out when the camera is near the vehicle.

### Expected Behavior

The shadows should not glitch out when in close proximity to the camera (verified on real hardware).

### PCSX2 Revision

v1.7.2360-1-g6ab77be8f	

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

Half pixel offset to special texture to fix some upscaling glitches.

### Emulation Settings

EE Timing hack, VU kickstart hack.

### GS Window Screenshots

The bug in action:

PCSX2 (not very obvious because it is hard to notice when camera is close, look for the missing shadow geometry under the vehicle):

![Capture d’écran 2022-02-14 150835](https://user-images.githubusercontent.com/90222976/153881245-69edc675-71ec-44a8-86d4-198218ba2bc3.png)

### Logs & Dumps

GSdump:
[Ratchet going commando shadow glitch.zip](https://github.com/PCSX2/pcsx2/files/8061430/Ratchet.going.commando.shadow.glitch.zip)

Emulog:
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/8061432/emuLog.txt)

**Comment by gilderoylockhart01** [comment]
You will find the emulog in the logs folder in the root of your PCSX2 installation.

As for GSdump, you will find these in the snaps folder if you have done it right.

**Comment by Dreadmoth** [comment]
#5580 enables the use of auto flush in D3D11, OpenGL and Vulkan HW without introducing shadow glitches, and fixes glitches in SW.
