### ISSUE TITLE
[BUG - SPU2]: Spiderman 3, missing character sounds ingame.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5525]
### Describe the Bug

In the game "Spiderman 3", there is a glitch where the characters ingame will have no sound at all when they are supposed to talk.

### Reproduction Steps

Load the blockdump and save state on the latest build and there will be no sound coming from the police officer.

### Expected Behavior

The police officer should not be silent.

### PCSX2 Revision

v1.7.2360-1-g6ab77be8f	

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Settings

Software rendering.

### Emulation Settings

EE rounding mode to negative.

TODO: I have to fix the GameDB because there is a problem with it and that game.

### GS Window Screenshots

The bug in action:

PCSX2:

https://user-images.githubusercontent.com/90222976/153898170-c1b4b123-4b68-4f80-b52f-e9a47bb699a3.mp4

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1G562ECRh5pDVUmlAG6_9aRSuYQ-afslb/view?usp=sharing

**Comment by Mrlinkwii** [comment]
can this be check on latest mater ?

**Comment by Mrlinkwii** [comment]
can this be checked on latest master ?

**Comment by kamfretoz** [comment]
Works fine as of v1.7.5397


https://github.com/PCSX2/pcsx2/assets/14798312/bdd4aeb7-86d7-4c69-ae89-03a15fd89740
