### ISSUE TITLE
[BUG]: Ratchet and Clank: Very tiny SPS in some corner cases.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#5528]
### Describe the Bug

In the game "Ratchet and Clank", there is a very slight bug which existed for years where there can be some very slight SPS in certain scenarios.

No settings actually fixes that bug.

### Reproduction Steps

Load the blockdump, then the savestate with a recent build, and walk on the button then on corridor, you will see some very strange "white-ish sps" when walking in the corridor.

### Expected Behavior

The game should not produce any SPS in that section (tested on real hardware).

### PCSX2 Revision

v1.7.2360-1-g6ab77be8f	

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### Emulation Settings

EE Timing Hack + VU kickstart hack

### GS Window Screenshots

The bug in action:

PCSX2 (hard to notice on this video):

https://user-images.githubusercontent.com/90222976/153928799-126db707-55cb-4126-b812-ba10d878d765.mp4

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1kc0oXoanCw_Q9Nst5DKDFZPpkf6v7m3C/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Where exactly am I looking? I notice something on his neck before you move, but that's it

**Comment by refractionpcsx2** [comment]
wow, that? okay... and you've checked this doesn't happen on real hardware? You are dominating the "reproduced on real hardware" category right now.

**Comment by gilderoylockhart01** [comment]
Hey, don't blame me because games are doing npn-stop fuckery ^^.

This time yup, I checked *several* times over on real hardware, and I didn't managed to reproduce that problem.

**Comment by gilderoylockhart01** [comment]
Yes, I already tried every of these including applying them before the loading screen. The VU rounding to nearest will make it worse however.

**Comment by refractionpcsx2** [comment]
no COP2 things coming up?

**Comment by gilderoylockhart01** [comment]
Quite a lot, but I suspect those are all false positives?

[cop2 logs.txt](https://github.com/PCSX2/pcsx2/files/8063629/cop2.logs.txt)

Btw, I found out that every of those "water distribution tubes" produces that SPS problem, there is one area where it's much easier to reproduce it.

**Comment by gilderoylockhart01** [comment]
I think I will just stop making issue report, this is starting to be a meme at this point, as you would expect, you know the outcome, reproduced on real hardware...
