### ISSUE TITLE
[BUG]: 1.7.2338 breaks the 'Jak X' logo and the course preview videos in Jak X

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#5530]
### Describe the Bug

Jak X logo and course previews appear either as completely black or as a series of blue rectangles.

I'm not 100% sure on this, but on 1.7.2338, the blue rectangles seem to be created by using a resolution higher than native, whereas they're just black when using native resolution. However, I've seen it have blue rectangles on native resolution from this image by Ziemas.

![Ziemas](https://user-images.githubusercontent.com/12673964/153977106-0bfb6028-e7fc-470a-838b-6185d8a628f6.png)

Moreover, I've seen complete blackness on resolutions higher than native.

What's important, however, is that @iMineLink's #5482, which fixed mipmapping regressions for Jak games, also seems to have created this issue.
 

### Reproduction Steps

Boot the game while using 1.7.2338 or up. Do not change graphics settings while playing the game, or the glitch disappears.

### Expected Behavior

Logo and course previews should display normally.

### PCSX2 Revision

1.7.2338–present

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 1700

### GPU

GTX 1070

### GS Settings

Renderer: Vulkan
Resolution: native and 4x
Mipmapping: basic.

### Emulation Settings

MTVU enabled.

### GS Window Screenshots

Logo on 2338:
![Jak X black](https://user-images.githubusercontent.com/12673964/153976058-dc393106-043c-43fa-a9e9-c57b727c8e2e.png)

Logo on 2337:
![Jak X normal](https://user-images.githubusercontent.com/12673964/153975996-8a899f79-e6c9-4395-9738-e7bbfadec546.png)

Course preview video on 2338:
![Screen mode 2338](https://user-images.githubusercontent.com/12673964/153975841-ac45cc08-4273-4f36-bd10-ef5c1f06634a.png)

Course preview video on 2337:
![Screen mode 2337](https://user-images.githubusercontent.com/12673964/153976243-a607b79f-5c35-47ef-b890-f7c11a2f95ac.png)

Blue rectangle logo:
![Jak X logo](https://user-images.githubusercontent.com/12673964/153976475-f561304d-bb4c-4352-8091-de2ae4433a96.png)

Blue rectangle course preview:
![Blue rectangles](https://user-images.githubusercontent.com/12673964/153976652-49f1a204-675b-42cf-aa74-ab7992d10abf.png)

### Logs & Dumps

[gs_20220214194956.gs.zip](https://github.com/PCSX2/pcsx2/files/8065131/gs_20220214194956.gs.zip)

**Comment by andutrache** [comment]
Did some testing on this and found out that the issues described are caused by the Texture Inside RT option being activated either by the automatic gamefixes or by manually enabling it.
Disabling Texture Inside RT will fix the issue of the corrupt X and previews.
Mipmapping setting has no effect on this issue.
Tested with v1.7.2755

**Comment by refractionpcsx2** [comment]
Yes, we know, there is already a PR (linked above) which attempts to fix it, but it causes other problems. We're fully aware of what causes this.

**Comment by refractionpcsx2** [comment]
Can't get this to happen anymore, so I guess it's fixed. Floor textures seemed to be corrupt as there was no mipmapping enabled, which there should have been, so I've added it in #8016
