### ISSUE TITLE
[Feature Request]: Port Skipdraw setting to Software mode (why not?)

### ISSUE THREAD

**Issue by mick-p1982** [PCSX2/pcsx2#5536]
### Description

Per this https://github.com/PCSX2/pcsx2/issues/3811 issue some games have showstoppers in Hardware modes (z-fighting is the main culprit in this one) but this game also has a full-screen post-processing effect (probably Brightness) that isn't emulated faithfully, which Skipdraw can disable. But Skipdraw isn't in the Software menu, so it can't use it. (Hardware glitches are worse, so it's damned if you do, damned if you don't without better compatibility between the software and hardware modes--why do they even diverge so much seems questionable?)

### Reason

To be able to use it.

### Examples

See description text.

**Comment by refractionpcsx2** [comment]
No.  The idea of software mode is to be accurate in emulation, if it's wrong, it needs fixing, Skipdraw is not a solution.  Software mode is supposed to be a hack free environment.

**Comment by mick-p1982** [comment]
Okay, well your emulator sucks (thanks for instantly Closing my issue) and won't get better like this. (People actually use Software mode to play their games when the Hardware mode fails... which is probably almost always.)

P.S. For the record, what the post-processing effect appears to fail out is compositing the fullscreen image accurately, resulting in a jello jiggle effect formed out of jiggling rectilinear lines superimposed over the game's picture.
