### ISSUE TITLE
[Feature Request]: Game Plugins

### ISSUE THREAD

**Issue by ermaccer** [PCSX2/pcsx2#5539]
### Description

Would it be possible to make .irx modules work like .prx plugins for PSP? 

PPSSPP has this feature implemented, while .prx plugins are a thing on hardware too - PS2 itself has no simple way of loading .irx modules for specific games.

User could store them in plugins folder which would be located in user files location.

### Reason

Game specific modules would greatly decrease the hassle of editing code as they could be written in C and compiled instead of manually writing asm code.

Possible use cases:
- Widescreen fixes
- More advanced game mods
- Translation patches

### Examples

PPSSPP Reference:
https://github.com/hrydgard/ppsspp/pull/13335

**Comment by Ziemas** [comment]
Maybe you could elaborate on how you would use this feature to accomplish your possible use cases?

IRX modules run on the IOP, so beyond handling various IO tasks for the game (which runs on the EE) there isn't much you can do with them to modify game play.

There is a corresponding ERX module system for the EE, but I don't know of any games that actually used it.

**Comment by ermaccer** [comment]
> Maybe you could elaborate on how you would use this feature to accomplish your possible use cases?
> 
For example, I would like to port my Mortal Kombat Unchained PSP mod  (https://github.com/ermaccer/MKUHook) to MK Deception PS2 since both games use exact codebases. It needs to call an internal screen refresh function to update the screen in certain situations. Use cases can be anything really, it depends what you want to do - for example, make some custom texture/text draws in game.

> IRX modules run on the IOP, so beyond handling various IO tasks for the game (which runs on the EE) there isn't much you can do with them to modify game play.
> 
You're right here but I've mentioned IRX due to how more "popular" it is. The idea here is simply to have any kind of MIPS related plugin system instead of manual asm patches.

**Comment by ThirteenAG** [comment]
Can anyone comment on the matter? Whether it's possible, not possible, explain why and all that?

**Comment by lightningterror** [comment]
Closing as trivial, pr's welcome if someone is interested adding it.
