### ISSUE TITLE
Any future plan to bring it to ios? 

### ISSUE THREAD

**Issue by ansinerd** [PCSX2/pcsx2#5556]
### Description

IOS Has second largest user base in the world, many are in desperate need to have quality emulators on iOS. We currently have dolphin port which works amazing and Ppsspp which is perhaps the best emulator out there. It would be great if we could get ps2 emu for iOS in future. We currently have play emulator which just doesn’t work and the updates are too slow. 

### Reason

It would bring happiness to thousands of ios users

### Examples

Dolphin ios is port of dolphin project
Ppsspp has both android and ios porta

**Comment by seta-san** [comment]
That might be a much better question for aether

**Comment by tudor07** [comment]
Play! already works on iOS but I think PCSX2 would be even faster

**Comment by lightningterror** [comment]
Closing as low priority, if anyone wants to tackle this they are free to do so.
