### ISSUE TITLE
[BUG]: Command line options are not working with the Appimage

### ISSUE THREAD

**Issue by Ka-hu** [PCSX2/pcsx2#5558]
### Describe the Bug

I'm using **pcsx2-v1.7.2357-linux-AppImage-64bit.AppImage** but it seems the command line options are not working with the Appimage format. I tried to launch an ISO directly from command line, but it just opens the GUI. Also, I tried other options (--nogui for example) but they don't work either. Every time only the GUI opens and I have to launch the game from there. I'm using Arch Linux. I tried earlier Appimage versions but had the same problem.

### Reproduction Steps

1. Download an Appimage
2. Launch a game from command line with the full path to the ISO file
3. It opens the GUI instead of running the game

### Expected Behavior

It should launch the game (and parse other command line options too).

### PCSX2 Revision

v1.7.2357

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by qurious-pixel** [comment]
replacing https://github.com/PCSX2/pcsx2/blob/4e7ade8612b921c7fac22a8771bc3da4f8a6e159/.github/workflows/scripts/linux/AppRun#L3

with `$APPDIR/AppRun-patched "$@"` will pass the arguments.

**Comment by 7oxicshadow** [comment]
I have also confirmed that modifying AppRun-patched to add "$@" so that the parameters are passed though works well for me. Would be good if we could get a fix for this in the future

**Comment by brooksytech** [comment]
Hello, I am also having this issue.

**Comment by Mrlinkwii** [comment]
is this still an issue on latest master?

**Comment by qurious-pixel** [comment]
Qt AppRun passes the commandline arguments
