### ISSUE TITLE
[Feature Request]: Bezel Art 

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5559]
### Description

What is Bezel Art? If you play PCSX2 in it's default parameters you get:
![image](https://user-images.githubusercontent.com/24227051/155173847-d7c16103-502e-4da3-b172-d6333e1a1943.png)
This is on my 21:9 monitor in windowed mode. 

When fit to window for aspect ratio you will get stretched output (unless you use widescreen patches or in-game option) without these black sides.

### Reason

It's mostly a visual preference, for some it will be too distracting or it can elevate a certain experience (theater, arcade, etc)

### Examples

As in the description this could look something like:
![image](https://user-images.githubusercontent.com/24227051/155174567-01ba2027-cbc1-4e2c-9973-190e73323b6c.png)

**Comment by coornio** [comment]
![155174567-01ba2027-cbc1-4e2c-9973-190e73323b6c](https://user-images.githubusercontent.com/11655762/155383635-28451016-adf4-411f-93db-fc9e7155b229.png)
![01b](https://user-images.githubusercontent.com/11655762/155383641-68f8a614-8b06-4999-b9e9-1e6620dd0126.png)

Fixed. Also interesting idea, but let's go a step further and allow videos too :p

**Comment by TransparentBlue** [comment]
It could also help with hiding garbage graphics at the edge of some games (provided it can go over the game output if desired) since using the zoom has limitations when it comes to doing that when the output doesn't match your screen aspect ration.

**Comment by RedDevilus** [comment]
If you have garbage best to just use the zoom setting:
![image](https://user-images.githubusercontent.com/24227051/155432246-d660d9ca-0030-45ba-98dd-fe901e9ccdca.png)

**Comment by TransparentBlue** [comment]
As stated it doesn't help if the game output doesn't match your screen aspect ratio.

**Comment by refractionpcsx2** [comment]
It wouldn't hide it.

**Comment by lightningterror** [comment]
Seems pointless and work for little to no gain.

**Comment by Thigoron** [comment]
Ah too bad it was closed (was searching for a way to add them and found this thread). I'd have loved to make some cool bezels for my games in order to get rid of the black bars on the sides/stretching the aspect ratio. :(
