### ISSUE TITLE
QT: Better GUI icon scaling with windows scaling/high dpi displays.

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#5564]
### Description

Testing out the QT builds for PCSX2 I've noticed that the new GUI suffers from the poor scaling that Duckstation does when using windows scaling for higher dpi displays. I'm just making this now so that it's at least something that everyone is aware of. It would be nice if the GUI could adjust to the windows scaling properly like other QT GUI's, for instance dolphin has no issue with this. Not sure if it is overlook but Duckstation is the same way. It's only certain icons in the GUI not every element. I know the QT version is incomplete. Anyway thanks. 

### Reason

Aesthetics 

### Examples

Dolphin, Yuzu, Citra

**Comment by RedDevilus** [comment]
If you have 125% DPI scaling it's normal to have blurry icons, that is a Qt bug.

125% DPI:
![image](https://user-images.githubusercontent.com/24227051/155425604-8fbc93ce-65d3-47c6-9b29-97d4244ad0ff.png)

150% DPI:
![image](https://user-images.githubusercontent.com/24227051/155425682-8181bb8e-2b62-487c-85ac-c954365e7f32.png)

And atm we don't accept GitHub issues for Qt anyway. Have a good day.

**Comment by BParks21** [comment]
> If you have 125% DPI scaling it's normal to have blurry icons, that is a Qt bug.
> 
> 125% DPI: ![image](https://user-images.githubusercontent.com/24227051/155425604-8fbc93ce-65d3-47c6-9b29-97d4244ad0ff.png)
> 
> 150% DPI: ![image](https://user-images.githubusercontent.com/24227051/155425682-8181bb8e-2b62-487c-85ac-c954365e7f32.png)
> 
> And atm we don't accept GitHub issues for Qt anyway. Have a good day. It will be looked at it for another time.

Ok I see.
