### ISSUE TITLE
[Feature Request]: keep osd in letter boxing 

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5568]
### Description

When playing in 4x3 resolutions keep the osd in the black letter boxing if possible to remove distraction from the play area

### Reason

Text in game play area is 
A. Hard to read
B. Distracting

### Examples

Not sure about examples. Just asking for text to be kept more off to the side

**Comment by refractionpcsx2** [comment]
It already does that

![image](https://user-images.githubusercontent.com/6278726/174797909-b6980e33-5142-46f3-aba3-321afea8725c.png)
