### ISSUE TITLE
[BUG]: Power Drome - missing character model from vehicles.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5570]
### Describe the Bug

the vehicles are driving without a pilot. only noticed the issue when testing https://github.com/PCSX2/pcsx2/pull/5569 

### Reproduction Steps

play the game

### PCSX2 Revision

1.7.2390

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

both software and hardware renderer

### GS Window Screenshots

![gs_20220226010002](https://user-images.githubusercontent.com/8851653/155833491-e8f3ddc6-08c3-4ef1-80c9-197d5371a8b2.png)

**Comment by refractionpcsx2** [comment]
Enable automatic fixes, there should be a patch for that.  if it's not working, then I need to know what version of the game and what CRC your game is to see if there's a patch for it.

**Comment by seta-san** [comment]
SLUS-20978
CRC 42E15DEF

**Comment by refractionpcsx2** [comment]
Because it has a patch...

**Comment by seta-san** [comment]
SLES-54418 will probably also need a patch

**Comment by refractionpcsx2** [comment]
Added the patch for your version to the PR
