### ISSUE TITLE
[Texture Replacement]: Hash cache has used (xxx) MB of VRAM, disabling.

### ISSUE THREAD

**Issue by Yumeris** [PCSX2/pcsx2#5578]
### Describe the Bug

a huge amount of Texture replacement may cause a crazy amount of preload into Vram, the emulator would just spam this messages if i had the OSD "Show Messages" enabled:
![hashcache](https://user-images.githubusercontent.com/70304827/156084867-d387b5f5-65f0-49ff-b1c6-ddd735d2d163.png)
also trying to emulate the game in Higher Resolution than 5x native (like 6x native 4K) would just make it crash.

the game in Question are Mobile Suit Gundam: Gundam vs. Zeta Gundam (SLUS-20821) and here some screenshot of the emulator running with replaced textures (it work fine, with exception of Loading Screen which for some reason kinda glitched if its replaced and hashcache messages spam)
![remaster](https://user-images.githubusercontent.com/70304827/156085086-2fa412b4-1dbc-4cd5-bb1d-2442fd56d666.jpg)
![gs_20220301094754](https://user-images.githubusercontent.com/70304827/156085252-51d20ced-bdbb-4f15-b2a5-a78eaae022b9.jpg)

### Reproduction Steps

have 1638 texture replacement (DDS BC5 format ,mostly 1024x1024 for half of it and the rest are 512x512 or 256x256)
Texture Preloading: None/Partial/Full
Renderer : OpenGL/Vulkan
Advanced: Asynch Texture Loading + Load Textures + Precache Texture (disabling precache wouldn't make the emulator replace the texture at all)
Internal Resolution Tested: Native 3X,4X,5X (6X would just make it crash)

### Expected Behavior

dynamically load only needed texture or texture replacement working without precache texture

### PCSX2 Revision

v.1.7.2401-64-bits AVX2 build

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
I'll quote Stenzek himself.
"The games that blow up in size have tiny changes in the textures themselves every frame, increasing the [vram] limit would not be beneficial as it's uploading new textures every frame anyway."

From my understand you're stuck in a situation where only the loading screen is uploading the textures. This isn't a bug, it's a feature.

**Comment by Yumeris** [comment]
> I'll quote Stenzek himself. "The games that blow up in size have tiny changes in the textures themselves every frame, increasing the [vram] limit would not be beneficial as it's uploading new textures every frame anyway."
> 
> From my understand you're stuck in a situation where only the loading screen is uploading the textures. This isn't a bug, it's a feature.

the loading screen texture are excluded from replacements, i've just mentioned that not all texture are replaceable xD (the game overlay the art then a 256x256 "loading" text in corner of it, for some reason the only texture that glitching are the art while loading texture load fine with proper alpha transparency)

**Comment by Yumeris** [comment]
> > I'll quote Stenzek himself. "The games that blow up in size have tiny changes in the textures themselves every frame, increasing the [vram] limit would not be beneficial as it's uploading new textures every frame anyway."
> > From my understand you're stuck in a situation where only the loading screen is uploading the textures. This isn't a bug, it's a feature.
> 
> the loading screen texture are excluded from replacements, i've just mentioned that not all texture are replaceable xD (the game overlay the loading art with a 256x256 "loading" text in corner of it, for some reason the only texture that glitching are the art while "loading text" texture load fine with proper alpha transparency). the glitch visual is that the loading art texture would overlay itself with other random textures. (presumably issue with the way the game handle loading art texture and texture replacement features)
about the loading art glitch, i've put them back into the replacement folders and re-tested it.. apparently its fixed by [[GS/TextureReplacements: Disable generated mipmaps on compressed textures](https://github.com/PCSX2/pcsx2/commit/866e5bd92941dffbce26aa442d4b63d8c56b19a3)](https://github.com/PCSX2/pcsx2/commit/866e5bd92941dffbce26aa442d4b63d8c56b19a3)

**Comment by Yumeris** [comment]
![issue](https://user-images.githubusercontent.com/70304827/156108257-30db380a-030d-4878-b9fe-07285886cc59.png)
the issue also occurs even when the texture replacement totals are 187 files (DDS BC3, 259MB), i've re-tested it with older builds of commit 8aaeb1c7ce895ddc2ac0800e6ecde2625b984cad and it work fine and would report correct number of vram if i am going over what my gpu vram could do for hashcache.

**Comment by stenzek** [comment]
#5582 should hopefully fix this.

As an aside, you really don't want to use preloading unless the pop in becomes noticeable (possibly from slow disks). Replacement texture loading is 100% asynchronous in PCSX2, and won't cause stutter like it does in other emus.
