### ISSUE TITLE
[Textures Replacement]: on some games the replaced texture would be too bright 

### ISSUE THREAD

**Issue by Yumeris** [PCSX2/pcsx2#5581]
### Describe the Bug

trying to replace some Textures in A.C.E.: Another Century's Episode 3: The Final (SLPS-25784)
![gs_20220301135748](https://user-images.githubusercontent.com/70304827/156108019-b299742e-ea98-46ce-88ba-1cbd0db176f7.jpg)

### Reproduction Steps

Replace Textures

### Expected Behavior

Replaced texture match the original instead of being too bright (possibly something whacky happening with the game)

### PCSX2 Revision

v.1.7.2401-64-bits AVX2 build

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
This is invalid. You're probably preserving the texture's alpha, see https://github.com/PCSX2/pcsx2/blob/master/tools/texture_dump_alpha_scaler.py

**Comment by Yumeris** [comment]
> This is invalid. You're probably not preserving the texture's alpha, see https://github.com/PCSX2/pcsx2/blob/master/tools/texture_dump_alpha_scaler.py

use scale command right?, i have done that.. most likely just the game
