### ISSUE TITLE
[BUG]: PSI-OPS - Double Image D3D11

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5583]
### Describe the Bug

A double image causes a blurriness but only in the d3d11 renderer

### Reproduction Steps

play in d3d11

### Expected Behavior

no double image

### PCSX2 Revision

1.7.2401

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

d3d11 renderer. 

### GS Window Screenshots

this is d3d11
![gs_20220301015041](https://user-images.githubusercontent.com/8851653/156127493-c5b581ae-c83f-4ee6-9560-21d81601882a.png)

ogl
![gs_20220301015126](https://user-images.githubusercontent.com/8851653/156127578-eb56fbf5-d924-494a-be54-15a5c7af55fb.png)

**Comment by lightningterror** [comment]
Upload a gsdump.

**Comment by seta-san** [comment]
[gs_20220315212555_Psi-Ops - The Mindgate Conspiracy _NTSC-U__SLUS-20688.gs.zip](https://github.com/PCSX2/pcsx2/files/8258442/gs_20220315212555_Psi-Ops.-.The.Mindgate.Conspiracy._NTSC-U__SLUS-20688.gs.zip)

**Comment by lightningterror** [comment]
Needs medium blending on dx11.
