### ISSUE TITLE
[BUG]: PSI-OPS Lockup during game play

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5584]
### Describe the Bug

the screen locks up. vertical bars run down the screen. it does eventually unlock.

### Reproduction Steps

playing the game. i tend to get this to happen when taking damage

### Expected Behavior

not lock up

### PCSX2 Revision

1.7.2401

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

### GS Window Screenshots

![gs_20220228130307](https://user-images.githubusercontent.com/8851653/156127966-6f739d13-8303-451a-b19c-2655ea38ec0f.png)

### Logs & Dumps

[gs_20220228130307.gs.zip](https://github.com/PCSX2/pcsx2/files/8159764/gs_20220228130307.gs.zip)

**Comment by seta-san** [comment]
https://youtu.be/lGvdKh51Jo8

**Comment by Mrlinkwii** [comment]
Is this still an issue on master ?

**Comment by seta-san** [comment]
I’ll test as soon as I can. Baby occupies my life now.

**Comment by seta-san** [comment]
yes. it's still an issue

**Comment by Mrlinkwii** [comment]
can this be rechecked if possible :)

**Comment by seta-san** [comment]
I’ll check it when I get home in about 10 hours

**Comment by seta-san** [comment]
i can't get the bug to activate. it's a random to activate but i've tried for the last couple days and can't get it to.

**Comment by Mrlinkwii** [comment]
cool then , im gonna assume it fixed :)  , if it comes back the issue can always be reopened
