### ISSUE TITLE
[BUG]: Graphic corruption on the character select screen of Ultimate Mortal Kombat 3 included with Mortal Kombat Armageddon - Premium Edition

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#5591]
### Describe the Bug

This is a regression, seemingly from #4739 based on the last build which worked correctly. Specifically, I believe it's the LDR instruction that's causing the issue.

An emulated version of Ultimate Mortal Kombat 3 is included with Mortal Kombat Armageddon Premium Edition. In current builds of PCSX2, the character portraits on the select screen have numerous coloured dots in them that should not be there. This only occurs when using the EE Recompiler, and does not occur prior to build 1.7.0-dev-1762. The game works correctly using the EE interpreter but is too slow to be playable.

### Reproduction Steps

Load the game, start UMK3.

### Expected Behavior

No dots in the character portraits.

### PCSX2 Revision

v1.7.2409

### Operating System

Windows 11

### CPU

Ryzen 3700X

### GPU

RTX 3070

### GS Settings

GS settings have no effect on this bug.

### Emulation Settings

The only setting that has an effect on this bug is switching between EE Recompiler and interpreter.

### GS Window Screenshots

How it looks by default:

![gs_20220303120519](https://user-images.githubusercontent.com/4227434/156564161-232fb40d-5d80-406b-8731-be683cad0690.png)

How it looks using EE Interpreter or if the JIT code for the LDR instruction is disabled:

![gs_20220303151123](https://user-images.githubusercontent.com/4227434/156594997-1b5ee72d-671a-4744-b350-3b66d680cbdd.png)

### Logs & Dumps

Block dump: https://mega.nz/file/FLhwQYYK#mzel-xnFjB_N5nz3lYiPiALS-QihVJCWkyn46LOd9v8

Save state to get straight to UMK3:
[SLUS-21543 (EFCFAEBB).00.zip](https://github.com/PCSX2/pcsx2/files/8177817/SLUS-21543.EFCFAEBB.00.zip)

**Comment by Silanda** [comment]
Yes. That was my first thought too, but 32 and 64 bit are exactly the same.

**Comment by refractionpcsx2** [comment]
Should be fixed in the above linked PR, if you could give it a try once it's built to confirm, that'd be great :)

**Comment by Silanda** [comment]
Looks good to me!
