### ISSUE TITLE
[BUG]: SMT Nocturne lines across certain surfaces

### ISSUE THREAD

**Issue by Comitant** [PCSX2/pcsx2#5592]
### Describe the Bug

As of v1.7.2365 ( https://github.com/PCSX2/pcsx2/commit/dfe4bc199fb8bf6974cd48334c333cd6c1a2826f ) there are lines in certain areas of the game. There was no glitch before that update. This is fixed by using native resolution, although I figure since I know the exact version which created this glitch I might as well mention it.

### Reproduction Steps

Using v1.7.2365 or later, start and go through the intro of the game. Go to the Medical Center (it can also be seen in the subway but it's most noticeable here)

### PCSX2 Revision

v1.7.2415

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800x

### GPU

RTX 3080

### GS Settings

Resolution 2x or more

### GS Window Screenshots

![123456](https://user-images.githubusercontent.com/63033061/156581946-3dea2366-005e-4af1-b27c-0730e205d2e5.png)

### Logs & Dumps
Snap: [SMT3Glitch.zip](https://github.com/PCSX2/pcsx2/files/8197768/SMT3Glitch.zip)
Sstate: [SLUS-20911 - (E8FCF8EC).zip](https://github.com/PCSX2/pcsx2/files/8197774/SLUS-20911.-.E8FCF8EC.zip)

**Comment by coornio** [comment]
Can you confirm if this issue is present only when upscaling or if it's also present at native resolution? If it only happens when upscaling, then this would not be a valid bug report.

**Comment by Comitant** [comment]
> Can you confirm if this issue is present only when upscaling or if it's also present at native resolution? If it only happens when upscaling, then this would not be a valid bug report.

I tested it and it does only happen with upscaling, but as I explained in the post I found the exact update which causes this glitch. This was not a glitch before v1.7.2365 ( https://github.com/PCSX2/pcsx2/commit/dfe4bc199fb8bf6974cd48334c333cd6c1a2826f )

**Comment by MrCK1** [comment]
As stated in the template, we are not accepting bug reports for upscaling at this time. You can try the usual mitigation tricks (TC offsets, texture filtering, half pixel offset).
