### ISSUE TITLE
[BUG]: Jak 3 - Jak looks sick and dirty (also missing sleeves) in software rendering.

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5595]
### Describe the Bug

Noticed this while playtesting the character drift bugs. I'm surprised no one caught it. 

Here's how it looks in software rendering:
![asdfaf](https://user-images.githubusercontent.com/11655762/156650029-204bc67d-bdd1-4495-a508-f93c247e11a4.png)

Whereas in hardware he looks correct:
![dgsdfgg](https://user-images.githubusercontent.com/11655762/156650067-678a9f66-f382-45d2-93e6-cab8a3c3404c.png)

I checked in all renderers with the same results.

### Reproduction Steps

Simply enter software rendering.

### PCSX2 Revision

1.7.2410

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

### Logs & Dumps

[gs_20220303224300.gs.zip](https://github.com/PCSX2/pcsx2/files/8181022/gs_20220303224300.gs.zip)

**Comment by F0bes** [comment]
For the record, it happens on 32 bit as well.

**Comment by refractionpcsx2** [comment]
This was original fixed here  https://github.com/PCSX2/pcsx2/pull/1843
but the code was removed/replaced here https://github.com/PCSX2/pcsx2/pull/3940 and likely reintroduced the bug (though I haven't backtraced)

**Comment by coornio** [comment]
This was resolved at some point so it's no longer an issue. The GS dump still showcases the bug, thus it is fubar as reference material.
