### ISSUE TITLE
[BUG]: Jak 3 -- Difference(s?) between 64bit and 32bit in rendering.

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5596]
### Describe the Bug

I am not sure what the bug is or where it lies in the code, but some difference is surely there. The below picture features 64 bits instance on the left side, and a 32 bits instance on the right side. Notice the sun in particular:

![image](https://user-images.githubusercontent.com/11655762/156652122-379a8637-e5b2-4d05-af1a-552c8128b5ea.png)

The right instance is much closer to the legitimate PS2 bloom for the sun. It is unclear if there are any other differences to be found. It is not easy to run two instances of the emulator at the same time and keep them in sync in such a way so that minute differences might pop out.

### PCSX2 Revision

1.7.2410

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

### Logs & Dumps

This dump belongs to the 64 bits instance:
[gs_20220303230155.gs.zip](https://github.com/PCSX2/pcsx2/files/8181121/gs_20220303230155.gs.zip)

This dump is for the 32 bits instance instead:
[gs_20220303230201.gs.zip](https://github.com/PCSX2/pcsx2/files/8181123/gs_20220303230201.gs.zip)

**Comment by refractionpcsx2** [comment]
I can actually get the same result as the right side on master 32bit but my Auto Flush for PR matches the 64bit build.

Are you sure you didn't miss builds up? and That could be an issue with my PR, which would be annoying :(

**Comment by Dreadmoth** [comment]
I can't reproduce the appearance on the right when running the game on master, 32-bit or 64-bit. Any renderer. Auto Flush on or off.

If I load **either** of your dumps, on 32-bit or 64-bit master:
Any HW renderer, Auto Flush disabled: matches left-side appearance
Any HW renderer, Auto Flush enabled: matches right-side appearance
SW renderer: always matches left-side appearance

If I make a dump and load it myself it always matches the left-side appearance 😕

If I load either of your dumps or run the game with #5580 :
Any renderer: always matches left-side appearance

PCSX2 Revision: 1.7.2412 (and #5580 0fab49a)
Operating System: Windows 10 21H2
CPU: i7-4770
GPU: GTX 1070 Ti, driver 511.79

**Comment by refractionpcsx2** [comment]
To get the one on the left to happen, you had to use an old version of my PR, with upscaling, without using any sort of HPO, plus Auto Flush, then it happened.

It doesn't happen now on the recent builds of my PR (and I'm not sure it was supposed to).  In native they all looked the same, so I suspect it was a half pixel offset issue which my old version of the PR kind of broke, somehow...

**Comment by Dreadmoth** [comment]
Yeah, I just checked the current commit, it was added while I was typing up my previous comment.

#5580 behaviour now matches master, other points in my last comment still apply.

**Comment by coornio** [comment]
My bad for using the PR to test the x64 version but hey, at least I helped locate an issue with it :P 

That said, there's still a bit of a difference when comparing. It's much subtler. 32 bits on the left, 64 bits on the right.

![image](https://user-images.githubusercontent.com/11655762/156841082-ac4ec097-3547-47f1-baca-641e8684e3e8.png)

**Comment by Dreadmoth** [comment]
After testing a bit more, I think there is run to run variation in the size of the sun, which is saved in dumps and savestates.

**Comment by lightningterror** [comment]
32bit has been dropped, if there are still any remaining 64bit issues then they will be looked over.
