### ISSUE TITLE
[BUG]: Bloom trails not rendering in HW mode - Burnout 3: Takedown

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#5602]
### Describe the Bug

Bloom trails left behind by various light sources in Burnout 3 aren't being rendered in HW mode.

### Reproduction Steps

Use hardware mode on any API.

### Expected Behavior

Bloom trails should appear in both modes.

### PCSX2 Revision

v1.7.2415

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GeForce GTX 1060

### GS Window Screenshots

**SOFTWARE MODE**
![software](https://user-images.githubusercontent.com/19964653/156946437-26975bd3-4ae2-41b0-8936-cbe17d4e8738.png)

**HARDWARE MODE**
![hardware](https://user-images.githubusercontent.com/19964653/156946443-869f6feb-ba57-40d6-ac31-c61afaf2485a.png)

### Logs & Dumps

https://drive.google.com/file/d/1uGQe2zCiv7KOwet16RWBM3vg2XwEwiy9/view?usp=sharing

**Comment by MrCK1** [comment]
It is a known issue. The effect is skipped due to the CRC hack that is required for the game.

**Comment by ElTioRata** [comment]
Then I guess this is related to #1415

**Comment by refractionpcsx2** [comment]
Can we get a GSDump anyway? Would be helpful

**Comment by ElTioRata** [comment]
https://drive.google.com/file/d/1_pC-nbJZjLSZTU5LLh2niUysk4d8aMQP/view

**Comment by refractionpcsx2** [comment]
That says "File does not exist"

**Comment by refractionpcsx2** [comment]
yeah it's definitely the CRC, if you disable it you get it kind of trying to work, but as you can see it causes errors on the screen also.

![image](https://user-images.githubusercontent.com/6278726/157928375-26f99ce2-5469-4e9a-bc5f-d8f709a51556.png)
