### ISSUE TITLE
[BUG]: PCSX2 hangs when selecting "apply/ok" in general settings menu

### ISSUE THREAD

**Issue by Jigoku** [PCSX2/pcsx2#5615]
### Describe the Bug

Using the app image version of [v1.7.2420](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2420).
Pressing the Apply or OK button in the general settings menu, causes the whole application to hang.
Can only be recovered by manually killing all relevant processes.

### Reproduction Steps

Click Apply or OK in general settings menu. 

### Expected Behavior

Settings should be saved and stored, the application shouldn't freeze/hang.

### PCSX2 Revision

v1.7.2420

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Slackware (-current)

**Comment by Jigoku** [comment]
I should add that this is only specific to the general settings menu. All the others from graphics / controllers etc, these ones are working fine when making changes.

**Comment by refractionpcsx2** [comment]
The temporary solution to this seems to be to rename the appimage to not have the version number in it? so call it "pcsx2" or something, then it seems to work from a couple of cases we've seen now.

**Comment by qurious-pixel** [comment]
Possible fix is to exclude `libgmodule-2.0.so`

https://github.com/AppImage/pkg2appimage/blob/565a56d208a8f3025c438c68da276e717a4ed0ac/excludelist#L86-L95

https://github.com/AppImage/pkg2appimage/pull/500#issuecomment-997183221
