### ISSUE TITLE
[Feature Request]: "Apply" button in Graphics Settings window

### ISSUE THREAD

**Issue by tealsuki** [PCSX2/pcsx2#5619]
### Description

Adding a button to apply settings without closing the Graphics Settings window (ie: [OK | Cancel | Apply])

### Reason

Ease of tweaking settings live, as the Graphics Settings window no longer behaves modally (read: interrupting the rendering while open) in the Master branch (unknown when this behaviour was changed)

### Examples

A similar function is already on the grouped "General Settings" window

**Comment by coornio** [comment]
This will soon not be a requirement. We're basically waiting for the massive Qt interface drop, then settings will apply in real-time rather than having to press a button.

**Comment by lightningterror** [comment]
As coornio said.
Done on Qt, won't be done on wx.
