### ISSUE TITLE
[Feature Request] - Auto save stating

### ISSUE THREAD

**Issue by Sarania** [PCSX2/pcsx2#562]
A thread on the forum gave me this idea. The feature would basically just automatically save state every X minutes/seconds. It could be useful for quite a few reason I can think of(well practically anything normal save states are, but without having to have the user remembering to save). Also possibly a new save state slot could be implemented named "Auto" for this purpose.

I might could implement some of it myself. But actually I kind of just wanted people's opinion on whether it would be useful enough to bother with or not. If so, I'll tinker with it.

 Just making the auto stating should be as simple as some UI option to control it(enable/disable, and frequency) and having some timer event trigger it at the right point. I'm pretty sure I can do that. Adding a new save state slot to go with it might be a bit above me, not sure until I look at code.

**Comment by karasuhebi** [comment]
I think this would be a great feature, actually. I would add that it would be a good idea to make with some redundancy though. So if the last saved state is fucked, you can go back to a previous one. So maybe make it so it listens to the 'Backup before save' setting? Or maybe you could have it where it saves a backup state every x amount of minutes offset from the user setting?

**Comment by Sarania** [comment]
I think it would just obey the backup setting.

**Comment by ssakash** [comment]
yes, it's quite a nice feature. I would actually prefer a separate save state for this auto-save method.

**Comment by ssakash** [comment]
yes, it's quite a nice feature. I would actually prefer a separate save state for this auto-save method.

**Comment by refractionpcsx2** [comment]
an auto savestate could be a pain for 2 reasons i can think of.

1. it could make people lazy in making their own savestates
2. as a result of 1, it could auto savestate less than a second before you die, meaning you have to go back to whatever savestate/point you have from probably ages ago.

**Comment by Sarania** [comment]
@refractionpcsx2 

1. Uh... I don't see how that's an issue? It's there choice to turn it on/off
2. Yeah that's a valid point, but remember it will obey the backup save state command so the "go back" point would be the time interval between auto save states

Regardless, we constantly tell people not to rely only on save states anyway. This is not meant to be used like "Oh I'll just turn this on, and never save in game or make my own states" because that would be kind of dumb.

**Comment by refractionpcsx2** [comment]
If this is something people want then it could be worth persuing in that case.  The only other bugger i can think of is the pause you get when a state is being saved, that could be annoying :P

**Comment by ssakash** [comment]
yeah, if the frequency is set to something like 1 minute then the pause will be quite annoying.

**Comment by Sarania** [comment]
Yeah that's the issue most people have brought up when I asked them about this. I manually save state about every 30 seconds lol so it doesn't really bother me.

**Comment by refractionpcsx2** [comment]
Yeah lol. If there was a way around that, i'd say yes, definitely a nice idea, but i don't think there is a way around it, simply because it has to pause everything to get a true snapshot, so it's not like we can just thread it or anything :P

**Comment by karasuhebi** [comment]
Well if the people who want the option enabled are willing to put up with the momentary pauses, I don't see a problem with it. Thoughts?

**Comment by Sarania** [comment]
Well I've been gathering thoughts elsewhere too and most people aren't TOO excited about it. I think it's worth keeping as a feature to eventually have, but mark it low priority maybe.

**Comment by tsunami2311** [comment]
I dont think it good idea seeing save states from build to build general are compatible or has this changed?

that and save states arent recommended, so why would want to add auto function to something that recommended.

I have used them before but it very very rare i have use in very specific instances

**Comment by Sarania** [comment]
Save states aren't recommended as your ONLY method of saving. But most people use them pretty often, and it's rare that they encounter an issue.

**Comment by tsunami2311** [comment]
true, but if there is autosaved state how much you want to bet people wont actual bother to save to the mem card then will complain when there save state breaks something or dont work when the update pcsx2

**Comment by Sarania** [comment]
Well if people do that they are pretty dumb, as I said above..

**Comment by tsunami2311** [comment]
you ment the people on the the forums yes? the ones that dont read and do the stupid? i pessimist/realest  so i see the "bad" things first likes I said big pop up warning when enabling so there no excuse.

**Comment by Sarania** [comment]
If we had big giant warnings for every possible stupid thing someone might do then we'd just have an emulator full of big giant warnings.

The only real issue I see is the one I stated above: the emulation pause when we save.

**Comment by leilei-** [comment]
Can't you save it into memory and then stream-save the state over to disk after that to avoid the pause?

If not, then autosaving while there's no input for a certain amount of time? (assuming cutscene or afk)

**Comment by Sarania** [comment]
@leilei- The reason it freezes is not the writing to disk(as I understand). Emulation is purposefully paused during save state so everything is in sync in the state. If we didn't, then it would like save the core at one point, the GS 200ms later, the pad another 100ms and so on. And so it would be out of sync. At least that is how I understand it.

**Comment by tsunami2311** [comment]
please dont get me wrong i not say is bad idea, cause it has it uses saves states, it would just promote people to use that such feature over actually memory saves. ( i know i would rather use auto save function over manual saves and others would too) just not as save states

What I would intrested more in IF it possible to do the saves states without the pause, cause as far as i can tell all the emulators I ever used have pauses in there saves states (during  saves) for the  reason you stated.

If you can solve that , I would also attempt to have  on screen message show when save state is saved. it one thing to do the save states manual and know where you saving it, but if it automatic and there is no pause one would have random saves done with out them know were it saved, cause there would be no indication with out the pause.

Some times i  wish i went learned programing instead of the hw end of things.

**Comment by Nobbs66** [comment]
There really isn't a way to solve it

**Comment by refractionpcsx2** [comment]
The pause is mainly due to gsdx having to write everything back from the gpu (super  slow) to the gs memory due  to how the texture cache works,  so there's no way to avoid this

**Comment by Flavescent** [comment]
If this is implemented, I recommend making it so that the saves occur after the set interval has elapsed and no buttons have been pressed for a few seconds. This reduces the likelihood that the pause disrupts gameplay.

**Comment by AdmiralCurtiss** [comment]
I'll also throw in a suggestion that, if such a thing is implemented, you should make sure that savestates aren't created while Memory Card IO operations are active.

**Comment by refractionpcsx2** [comment]
Thats a very valid suggestion :)

**Comment by Mikekeke** [comment]
It could lower peoples motivation, but from the other side, PCSX2 just crushed during playing Persona 3 FES after set of long dialogs and actions, where you can't save game. So autisaved state will be really handy in cases like that.

**Comment by willkuer** [comment]
If emulation crashes auto saves will highly possible not save you since the bug is probably saved in the autosave. Auto save is handy if either you have a fixable hw error (as accidentally hit power button and pc turned off) or you made something stupid ingame that you want to fix by reload (aka cheating). I don't really see the purpose of this feature but rather the problems it creates (as already mentioned in this thread)

**Comment by Mikekeke** [comment]
That was some random crash.

**Comment by ramapcsx2** [comment]
PCSX2 side, savestates are already threaded. The slowdown when creating them is probably on the GS side (as ref suggested) + whatever time it takes to flush the MTGS ring buffer. It's also simply a lot of data to process, at 32MB of memory in the machine that needs to be compressed.
We could keep the auto save states uncompressed and in RAM but then they get lost on a crash, so there's no point :p 

Overal, this needs some cleverness to get around these problems.

**Comment by njradford** [comment]
Why don't we allow the user to set the interval of an automatic save state event and alert the user to the performance considerations of frequent save states. The ideal use case in my mind would be having my progress saved every 10 minutes or so.

**Comment by lightningterror** [comment]
I'll be closing this then.
