### ISSUE TITLE
[Feature Request]: External Shaders INI editor (OR) bringing some shader settings in-menu

### ISSUE THREAD

**Issue by tealsuki** [PCSX2/pcsx2#5620]
### Description

Expansion of the Shaders panel to edit/include advanced settings exposed by the GS.fx shader file, which are controlled by the GS_FX_Settings.ini file

### Reason

There are advanced filtering, upscaling, and antialiasing shader functions available in the external shader INI, which are currently enable-able wholesale through the shaders tab, however these have to be changed in a text editor manually, and cannot be tweaked fully live. This feature would make tweaking games to tease out a higher fidelity (at screen resolution without going fully into the realm of supersampling) a bit easier.

Ultimately it would be a "nice to have", not something that ruins the experience of PCSX2 by being a little more difficult to find as it is, but hopefully it's a future consideration!

### Examples

ZSNES is a classic example of an emulator whose games with exclusively 2D elements greatly benefit from the advanced upscaling filters like 2xSaI and others which are available in PCSX2's external shader file, which may translate to PS2 games that are heavy on spritework and 2D interfaces. Tonemapping is also exposed in the shader, a common effect in modern 3D games, which may help colour correct/boost games that were meant for standard definition NTSC/PAL TV-colourspace, or suffer from mid-2000s design decisions.

**Comment by BinhoKof99** [comment]
the snes9x, ppsspp , flaycast, mame, they all have it give a life to the 2d titles i have been waiting for this function in pcsx2 for a long time it would be great to see all the ps2 collections using filters like xbrz for example

**Comment by Unix0815** [comment]
A hotkey to reload the shader would be a good start

**Comment by lightningterror** [comment]
External shader support has been removed, there are plans to bring in reshade support.
Also related, see #7647
