### ISSUE TITLE
[BUG]: Intel's Broken Vulkan Drivers

### ISSUE THREAD

**Issue by NewMoonHD** [PCSX2/pcsx2#5631]
### Describe the Bug

Note: Hardware Renderer Specific

When using Vulkan on Intel's drivers, they have graphical glitches and error spams in a consistent manner. The most common I got from the spam is this:

From using SW renderer on any other ones (this includes Vulkan in SW rendering), none of them have the issues. I did test it out on AMD's side (RX 580 with 22.2.1 drivers), but so far, it doesn't have that issue (and probably the same result from Nvidia as well not affected from this).

### Reproduction Steps

Run Intel based gpus with the lastest drivers and run it specifically on Vulkan HW mode.

### Expected Behavior

Expect graphical glitches, vulkan device error spam and/or a fatal error causing the application to kill it (pop-up or not).

### PCSX2 Revision

v1.7.2428

### Operating System

Windows 11

### CPU

Intel Core i7-1195G7

### GPU

Iris Xe Graphics

### GS Settings

![Screenshot 2022-03-11 111045](https://user-images.githubusercontent.com/52108325/157954363-d7bbbdf4-66c7-4936-b596-6b37f95b6ac7.png)

### GS Window Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/52108325/157954724-d79cec75-468c-4440-a45b-46974e608f94.png)

**Comment by lightningterror** [comment]
It's not really up to us, rather intel needs to sort out their driver issues.

**Comment by stenzek** [comment]
It's also not a hardware issue; it's fine on Linux.

Intel's (closed source) drivers have historically sucked ass, and continue to do so.

**Comment by NewMoonHD** [comment]
> It's also not a hardware issue; it's fine on Linux.
> 
> Intel's (closed source) drivers have historically sucked ass, and continue to do so.

On intel's closed drivers on Windows, it's unfortunately a problem. But, the only workaround I did find from this was only to use Vulkan SW only and not accidentally use HW mode in it. Although I can use OpenGL or DX 11 as much as I please, it still hurts to see its current condition with its drivers. And when Intel Arc does come, it's gonna be a massive problem for potential Intel users if it does continue this level of pace. So, do be warned.

**Comment by stenzek** [comment]
> And when Intel Arc does come, it's gonna be a massive problem for potential Intel users if it does continue this level of pace. So, do be warned.

Then Intel should fix their drivers. We're not doing anything wrong, it's a scenario specifically covered in the spec: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#renderpass-feedbackloop

#5630 does add an option to disable texture barriers, which would probably work around the issues on Intel drivers, but it means that Vulkan will only have D3D-levels of blending accuracy.

**Comment by NewMoonHD** [comment]
Hello, I think I've found the problem. From the texture barriers being forced enabled causes the graphical artifacts and also causes the emulator itself to crash in general (same goes to when it's disabled). I don't know if this can give you a lead for making a report to Intel's driver forum problems, but it's something to say at least to where it might be the source of the problem of Intel's drivers being broken on Vulkan. Maybe the drivers still supported don't have to suffer it once they're EOL. Here's also the video to support it (from the video, I used beta 30.101.1934, then later upgraded to 30.101.1960 drivers afterwards).

https://user-images.githubusercontent.com/52108325/168172260-6ed7abf5-33dc-417d-a2fc-cf6f44a37017.mp4

**Comment by JordanTheToaster** [comment]
> Hello, I think I've found the problem. From the texture barriers being forced enabled causes the graphical artifacts and also causes the emulator itself to crash in general (same goes to when it's disabled). I don't know if this can give you a lead for making a report to Intel's driver forum problems, but it's something to say at least to where it might be the source of the problem of Intel's drivers being broken on Vulkan. Maybe the drivers still supported don't have to suffer it once they're EOL. Here's also the video to support it (from the video, I used beta 30.101.1934, then later upgraded to 30.101.1960 drivers afterwards).
> 
>  Broken.Drivers.mp4

It's already known that Intel's Vulkan drivers have broken barriers on Windows.
