### ISSUE TITLE
[BUG]: Forever Kingdom (NTSC-U) - Textures and upscaling Issues

### ISSUE THREAD

**Issue by xiriby** [PCSX2/pcsx2#5647]
### Describe the Bug

Affects all hardware modes

The Sky, the Water have texture issues to present the texture correctly.
Enabling Preload Frame Data solves this.

Some Doors/Floors in the game doesn't have texture at all and instead shows a shadow of one of the objects in the area.
If you set mipmapping to basic/full more textures has this issue
Enabling Frame buffer conversion solves the shadow issue but the texture is still not loaded, also the higher the mipmapping level more objects disappear happens even if mipmapping is set to off.

When the game is upscaled some black tiny lines are being added
Changing Round sprite to full solves that.

### Reproduction Steps

open a new game and skips all the cutscenes

### Expected Behavior

The textures should appear correctly.

Also it isn't an emulation bug but the game suffers from heavy screen tearing due to it interlacing system. 
luckily there is a code to remove it 

//Interlacing Fix
patch=1,EE,00104DA8,word,00000000
patch=1,EE,00202E94,word,00000000

so it should be added to auto game fix.

### PCSX2 Revision

1.7-2444

### Operating System

Windows 10 (64bit)

### CPU

i7-8700

### GPU

gtx 1060 

### GS Settings

![forever kingdom settings](https://user-images.githubusercontent.com/101547056/158125493-3538da04-f768-4e07-b35d-77242f81aa13.jpg)

### Emulation Settings

![forever kingdom settings 2](https://user-images.githubusercontent.com/101547056/158125539-dfb14e37-6e00-4155-a0e0-9364275ee2ef.jpg)

### GS Window Screenshots

pcsx2 software mode
![pcsx2x64-avx2 2022-03-14 08-32-30](https://user-images.githubusercontent.com/101547056/158118832-31c7b41f-a572-48b7-b2c2-a629bbb35648.png)

pcsx2 Hardware Mode 
![gs_20220314083111_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158120803-ba433c91-cfb7-4da0-a83f-68f50b7d8cbb.png)

pcsx2 Hardware Mode + Preload Frame Data
![pcsx2x64-avx2 2022-03-14 08-59-52](https://user-images.githubusercontent.com/101547056/158127247-a89e50e8-64e3-4980-a2b1-b411fbcdd3b5.png)

pcsx2 Hardware Mode + Preload Frame Data + Frame buffer conversion 
![pcsx2x64-avx2 2022-03-14 09-01-08](https://user-images.githubusercontent.com/101547056/158121406-eae571cb-1484-4bb2-8baf-28343b76c437.png)

pcsx2 Hardware Mode + Preload Frame Data + Frame buffer conversion + Full mipmapping
![pcsx2x64-avx2 2022-03-14 09-02-09](https://user-images.githubusercontent.com/101547056/158121630-d47552f4-3616-499f-bb5f-f9187b1d95a3.png)

pcsx2 Hardware Mode + Frame buffer conversion + no mipmapping (First Image)
![pcsx2x64-avx2 2022-03-14 09-03-14](https://user-images.githubusercontent.com/101547056/158121713-0f1a55eb-01dc-4730-b76f-d08ad15f0c2d.png)

Framebuffer Conversion Isn't Enabled (How it supposed to look) 
![pcsx2x64-avx2 2022-03-14 09-03-23](https://user-images.githubusercontent.com/101547056/158121739-9c7fe2a1-cbad-4e78-a856-c22937e9df8d.png)

Upscaling Issue
![forever kingdom Upscaling issue](https://user-images.githubusercontent.com/101547056/158126590-496e3add-13f7-45fd-9b76-4e9e1fd0f3ec.jpg)

Heavy Screen Tearing
![pcsx2x64-avx2 2022-03-14 09-12-43](https://user-images.githubusercontent.com/101547056/158127814-1243be68-04ef-4b64-b672-c073e32c7ab7.png)

### Logs & Dumps

[gs_20220314083111_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8242666/gs_20220314083111_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by refractionpcsx2** [comment]
instead of Full Mipmapping, how does "Basic" look?

**Comment by xiriby** [comment]
> instead of Full Mipmapping, how does "Basic" look?

If Frame buffer conversion is enabled they look the same.

If Frame buffer conversion isn't enabled, the shadow starts to change colors

Basic
![pcsx2x64-avx2 2022-03-14 09-57-30](https://user-images.githubusercontent.com/101547056/158129665-0dce3768-22b6-49e0-9af1-9c903728906f.png)

Full
![pcsx2x64-avx2 2022-03-14 09-57-46](https://user-images.githubusercontent.com/101547056/158129702-5d34eb18-2410-4388-8641-9e556f931233.png)

**Comment by refractionpcsx2** [comment]
and presumably the water is broken with Preload Frame off and Framebuffer Conversion on?

**Comment by xiriby** [comment]
> and presumably the water is broken with Preload Frame off and Framebuffer Conversion on?

Correct

**Comment by refractionpcsx2** [comment]
okay, in the "correct" Screenshot, how did you get the building to appear?

**Comment by xiriby** [comment]
Later in the game there is a texture that can't be fixed with either Preload Frame and Framebuffer Conversion
![gs_20220314102359_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158133417-15ed0376-8b95-4651-bdd8-300998553565.png)
[gs_20220314102359_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8243022/gs_20220314102359_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

In the same area enabling  Framebuffer Conversion will give the same results even if mipmapping is set to off

![pcsx2x64-avx2 2022-03-14 10-28-32](https://user-images.githubusercontent.com/101547056/158133950-1ee1be30-cc8c-4efb-b35e-d333f9346ed2.png)

**Comment by refractionpcsx2** [comment]
can we get a GS dump of that one too please?

**Comment by xiriby** [comment]
> can we get a GS dump of that one too please?

I shouldn't place it between the photos, so it would be more visible 

https://github.com/PCSX2/pcsx2/files/8243022/gs_20220314102359_Forever.Kingdom._NTSC-U__SLUS-20343.zip

**Comment by refractionpcsx2** [comment]
Thanks.

Wow framebuffer conversion really does break that scene, that shouldn't happen :/ This game seems very broken

**Comment by xiriby** [comment]
> Thanks.
> 
> Wow framebuffer conversion really does break that scene, that shouldn't happen :/ This game seems very broken

It's a FromSoftware game, even today they release broken games (Elden Ring for pc :/ ) 

Actually if you enable Framebuffer Conversion and go into first person mode (Hold R2) The texture is fixed (depending on the camera posse)  
![pcsx2x64-avx2 2022-03-14 10-45-06](https://user-images.githubusercontent.com/101547056/158136971-db376b99-bdd1-4c06-b514-8a0fdd100b94.png)

**Comment by refractionpcsx2** [comment]
man it's screwed, can you post your emulog.txt just to rule out core things that the SW renderer just happens to handle. Thanks :)

**Comment by xiriby** [comment]
Let me just add one more bug first

broken Light texture

Hardware

![gs_20220314105450_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158138346-fcf3b994-0ed3-42e3-b102-831272c15973.png)

Software

![pcsx2x64-avx2 2022-03-14 10-58-30](https://user-images.githubusercontent.com/101547056/158138600-c1fab549-54c1-4264-9ee4-4a9e1f60617b.png)

GS dump
[gs_20220314105450_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8243292/gs_20220314105450_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by xiriby** [comment]
> man it's screwed, can you post your emulog.txt after running the game and seeing the glitches, just to rule out core things that the SW renderer just happens to handle. Thanks :)

Do you want me to do it while being on hardware of software render?

**Comment by xiriby** [comment]
> it honestly doesn't matter, GS mode is inconsequential to the core :)

[emuLog_opening_scene.txt](https://github.com/PCSX2/pcsx2/files/8243402/emuLog_opening_scene.txt)

[emuLog_Shrine_Courtyard.txt](https://github.com/PCSX2/pcsx2/files/8243422/emuLog_Shrine_Courtyard.txt)

**Comment by xiriby** [comment]
> Let me just add one more bug first
> 
> in the Shrine Courtyard there are broken Light texture
> 
> Hardware
> 
> ![gs_20220314105450_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158138346-fcf3b994-0ed3-42e3-b102-831272c15973.png)
> 
> Software
> 
> ![pcsx2x64-avx2 2022-03-14 10-58-30](https://user-images.githubusercontent.com/101547056/158138600-c1fab549-54c1-4264-9ee4-4a9e1f60617b.png)
> 
> GS dump [gs_20220314105450_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8243292/gs_20220314105450_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by refractionpcsx2** [comment]
well nothing scary there.

**Comment by xiriby** [comment]
> okay, in the "how it's supposed to look" Screenshot, how did you get the building to appear?

 Framebuffer Conversion Isn't Enabled

**Comment by refractionpcsx2** [comment]
The heck.. I guess the plot thickens

**Comment by xiriby** [comment]
This Texture requires to switch to software mode and then switch back to hardware mode in order for the texture to work.
The texture works on software mode

How it looks on hardware mode
![gs_20220315193858_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158438963-63d309ca-55ee-4645-b83b-163789f9ad4d.png)

After Pressing F9 twice
![pcsx2x64-avx2 2022-03-15 19-40-01](https://user-images.githubusercontent.com/101547056/158439047-a831b2ed-a80d-4b55-8991-1db9911553f4.png)

gs dump
[gs_20220315193858_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8255916/gs_20220315193858_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by xiriby** [comment]
The Dress of the lady is completely black 
only Software mode can fix it

Hardware
![gs_20220316133416_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158581831-94b5cdc9-709f-4d0e-aff5-40a0058779df.png)


Software
![pcsx2x64-avx2 2022-03-16 13-34-35](https://user-images.githubusercontent.com/101547056/158581930-e2838d37-7d4b-49fd-b34c-7316b0fad496.png)


gs dump
[gs_20220316133416_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8261724/gs_20220316133416_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by xiriby** [comment]
Another sky issue but this one can't be fixed with Preload Frame Data

Hardware
![gs_20220316135948_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158585593-0571f325-ee4c-42fb-92b9-35e1da132b6b.png)

Software
![gs_20220316140213_Forever Kingdom _NTSC-U__SLUS-20343](https://user-images.githubusercontent.com/101547056/158585745-d11d9f06-0955-4504-8ad4-5aa05b0c2a39.png)

gs dump
[gs_20220316135948_Forever Kingdom _NTSC-U__SLUS-20343.zip](https://github.com/PCSX2/pcsx2/files/8261875/gs_20220316135948_Forever.Kingdom._NTSC-U__SLUS-20343.zip)

**Comment by refractionpcsx2** [comment]
Can this be retested? I think it's all fine these days.

**Comment by refractionpcsx2** [comment]
No response for 2 weeks, if this issue still persists, please post an update (and new GS Dumps) and we can reopen.

**Comment by xiriby** [comment]
> No response for 2 weeks, if this issue still persists, please post an update (and new GS Dumps) and we can reopen.

Sorry for the late response, 
all the issues were fixed but there is now a new issue

some textures on the ground are broken
setting ps2 mipmapping to basic fixes it

![Forever Kingdom_SLUS-20343_20230318100609](https://user-images.githubusercontent.com/101547056/226093697-90092094-4ace-42b8-87d7-df9c64789fbf.png)

**Comment by refractionpcsx2** [comment]
Can you try a build from #8289 first to see if that's any better?

**Comment by xiriby** [comment]
> Can you try a build from #8289 first to see if that's any better?

How do I download this version of pcsx2?

**Comment by Mrlinkwii** [comment]
how is this on latest nightly :)

**Comment by refractionpcsx2** [comment]
I think this is fine now from my limited testing, so closing for now, we can reopen if it's still broken.

**Comment by Red-tv141** [comment]
I retested this game, you fixed all the issues, but I found a new one

PCSX2 Ver 2.7.157

Hardware

<img width="1732" height="974" alt="Image" src="https://github.com/user-attachments/assets/221b9306-968f-49db-bc65-10cd3e0a56c9" />

Software

<img width="1732" height="974" alt="Image" src="https://github.com/user-attachments/assets/4390ad56-ff1a-48ce-a55d-d369c0d827f4" />

gs dump

[Forever Kingdom_SLUS-20343_20260305134310.zip](https://github.com/user-attachments/files/25766937/Forever.Kingdom_SLUS-20343_20260305134310.zip)

> I think this is fine now from my limited testing, so closing for now, we can reopen if it's still broken.
