### ISSUE TITLE
[BUG]:  Executable is giving error

### ISSUE THREAD

**Issue by ATSxp** [PCSX2/pcsx2#5656]
### Describe the Bug

Hello, I'm trying to install the latest version of PCSX2, 1.7.2452, when I run the file my computer tells me this:
![error_ps2](https://user-images.githubusercontent.com/92697714/158261167-07645fac-217c-43d0-b3b7-6edeb0a5bd64.png)
(detail, my OS is windows 7).

### Reproduction Steps

I installed the file [pcsx2-v1.7.2452-windows-32bit-AVX2.7z], extracted it and then ran it, it gave the error mentioned above.
Then I installed the file [pcsx2-v1.7.2452-windows-32bit-SSE4.7z], extracted it and ran the file and it also gave an error.

### Expected Behavior

I wish it worked =)

### PCSX2 Revision

1.7.2452

### Operating System

Windows 8.1 (32bit)

**Comment by kenshen112** [comment]
Pcsx2 doesn't support windows 7 anymore and will cease to work on it.

**Comment by lightningterror** [comment]
You can either upgrade your OS or stick with 1.6, we don't support w7.
