### ISSUE TITLE
[BUG]: 33% FPS reduction in Fullscreen, all games, all renderers

### ISSUE THREAD

**Issue by tealsuki** [PCSX2/pcsx2#5661]
### Describe the Bug

As title says, when switching to fullscreen mode, FPS is capped at approx 40fps, rather than approx 60fps. Occurs on all games, all available renderers (aka DX and SW). Occurs in both 32-bit and 64-bit SSE4 builds.

Has also occurred since I started using PCSX2 nightlies again (Jan 2022), can't remember if this was a problem with this machine when using 2020 builds.

Additional information:
winver 21H2 (OS Build 19044.1586)

![image](https://user-images.githubusercontent.com/1473126/158323762-616b566b-2caa-459f-9576-5db1065e7f6e.png)

### Reproduction Steps

Unknown. May be driver/iGPU/Windows quirk.

### PCSX2 Revision

v1.7.2455 (64-bit SSE4)

### Operating System

Windows 10 (64bit)

### CPU

Intel i7 3630QM (4C8T@2.4Ghz)

### GPU

Intel(R) HD Graphics 4000 (Driver Version: 10.18.10.5161, HP whitelist)

### GS Settings

Default, but tested with just about every combination of speedhacks and bare-minimums I could think of.

### Emulation Settings

Ditto, ran in Safe, and ran with all speedhacks enabled, including combinations of MTVU or Instant VU

**Comment by JordanTheToaster** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/80843560/158325300-53507765-b05b-48a4-a68c-84aeb2a563e9.png)

**Comment by tealsuki** [comment]
@JordanTheToaster Well for one, you have a completely different hardware configuration, which takes advantage of exclusive fullscreen mode.

**Comment by stenzek** [comment]
Invalid.

![image](https://user-images.githubusercontent.com/11288319/158325986-dcaa298d-630e-4bd1-bdb1-95598c880768.png)

Your display is running at 40hz... VSync on will not be able to present above this frequency.

**Comment by tealsuki** [comment]
![image](https://user-images.githubusercontent.com/1473126/158326321-1ad25f4f-8202-4b0b-8710-fad72a55d9d6.png)
Well, there you go!
