### ISSUE TITLE
[BUG]: pcsx2-qt not properly terminating in linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#5668]
### Describe the Bug

When exiting pcsx2-qt in linux, the process remains in the process list and must be manually terminated.

### Reproduction Steps

1. Launch pcsx2-qt
2. From menu: System > Exit
3. $ ps -ef |grep pcsx2-qt
4. Observe process not terminated

### Expected Behavior

pcsx2-qt properly terminates

### PCSX2 Revision

Commit 13cc0caed7719316cf3c1631d2cd296f38c7c34a

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.3 / kernel 5.13

**Comment by F0bes** [comment]
Unless it's a pull request. We aren't accepting issues for pvsx2-qt. No where does it say it's officially released and supported.

**Comment by Shoegzer** [comment]
Understood and it's fine to disregard, just thought this might be useful as it transitions to a supported binary.
