### ISSUE TITLE
[BUG]: PCSX2 Steam Deck Error When Booting ISO: Failed to open NVM File {path} for writing

### ISSUE THREAD

**Issue by AnthonyUccello** [PCSX2/pcsx2#5669]
### Describe the Bug

With a valid bios and a valid rom, booting the ISO causes a bunch of errors on steam deck in desktop mode

**Failed to open NVM File {path} for writing (many times)**

**Failed to read/write NVM/MEC file. Check your BIOS setup/permissions**

![19](https://user-images.githubusercontent.com/3809669/158489605-e47a8817-a1dd-447a-85eb-e37739d54775.png)

The bio itself is setup and valid and at the path specified. Pictured below:

![18](https://user-images.githubusercontent.com/3809669/158489441-c1a3673b-604f-42af-8617-e776f48b2527.png)

I am more than happy to help debug/troubleshoot further, will just need instructions on what to do. If I can provide more debug logs please just ask.

### Reproduction Steps

Unsure exactly why this suddenly started happening, it was working the first 2 times I booted a rom. However after a couple restarts these errors prevent any ISO from booting.

### Expected Behavior

ISO boots and game runs normally.

### PCSX2 Revision

v1.7.2436

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by refractionpcsx2** [comment]
We don't support pirates.

**Comment by AnthonyUccello** [comment]
Using my ps2 extracted bios in the root dir works.
