### ISSUE TITLE
Valkyrie Profile 2 [SLUS-21452] Parts of Bifrost are rendered in black in Hardware Mode

### ISSUE THREAD

**Issue by NetSysFire** [PCSX2/pcsx2#5670]
### Describe the Bug

Only happens in Hardware Mode.

![vp2 bifrost](https://user-images.githubusercontent.com/59517351/158493919-ff7c0b43-2e86-46a5-9842-82318b6c5752.png)

Software mode (how it is supposed to look):

![vp2 bifrost sw](https://user-images.githubusercontent.com/59517351/158493912-2e0975ed-eb12-4d56-bac8-3c132b0e6727.png)

### Reproduction Steps

1. Enter Bifrost (Go through the Forest of Spirits and exit Ravine Caverns)
2. Walk on it.
3. Notice that the center where you walk renders correctly but the edge (towards the right of the screen) is black.

I'd rate this issue as minor. So far, I have only seen this once (On Bifrost) and it does not impact gameplay at all. I do not know if this is a regression or not and since the issue is very minor, it might not be the effort to go through old versions.

### Expected Behavior

The black surface is transparent, as seen in Software Mode. Ignore the artifact at the right side of the screen. It goes away when auto flush is enabled.

I already tried playing with the blending accuracy and mipmapping levels to no avail.

### PCSX2 Revision

v.1.7.2436-1

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 1600af

### GPU

rx 570 OC version

### GS Settings

3x native

### Logs & Dumps

![gs_20220316013915_Valkyrie Profile 2 - Silmeria _NTSC-U__SLUS-21452](https://user-images.githubusercontent.com/59517351/158494693-93120548-5db5-4489-9038-ed550569b83f.png)
[gs_20220316013915_Valkyrie Profile 2 - Silmeria _NTSC-U__SLUS-21452.gs.gz](https://github.com/PCSX2/pcsx2/files/8258087/gs_20220316013915_Valkyrie.Profile.2.-.Silmeria._NTSC-U__SLUS-21452.gs.gz)

**Comment by RedDevilus** [comment]
Can you test the latest build or use Normal (Vertex) Half Pixel mode?

**Comment by NetSysFire** [comment]
I am compiling the latest build as we speak but the setting you mentioned fixed it

**Comment by RedDevilus** [comment]
Then I'll close this, we also don't really accept upscaling issues. In the future it should be handled automatically.
