### ISSUE TITLE
[BUG]: Xenosaga Episode III texture errors

### ISSUE THREAD

**Issue by Rimalogo** [PCSX2/pcsx2#5674]
### Describe the Bug

Xenosaga Episode III is having multiple texture errors on both hardware modes and software modes, OpenGL has the least issues but it is not recommended either as it has issues during cutscenes

### Reproduction Steps

Occurs during gameplay

### Expected Behavior

Textures to load properly

### PCSX2 Revision

1.7.2443

### Operating System

Windows 10 (64bit)

### CPU

Intel i7 8700k

### GPU

Nvidia GTX 1060 GB

### GS Settings

![GS Settings](https://user-images.githubusercontent.com/101501395/158504941-d12d340b-c849-4d03-965b-9ab5063da414.PNG)

### Emulation Settings

![OpenGL Mode](https://user-images.githubusercontent.com/101501395/158505040-b3564677-5f81-4a15-beb8-1dd3e187df3d.PNG)
![Software Mode Advanced](https://user-images.githubusercontent.com/101501395/158505042-a316e8a2-affb-4d6e-bdb5-f3ddc544975f.PNG)
![Software Mode Hacks](https://user-images.githubusercontent.com/101501395/158505043-a5f0d73d-6160-47ad-a4b6-ad74665e6366.PNG)
![Software Mode OSD](https://user-images.githubusercontent.com/101501395/158505045-a909a90c-1303-4306-b9b7-d663bdd5e6cb.PNG)
![Software Mode Settings](https://user-images.githubusercontent.com/101501395/158505046-3ad6e528-fa7f-4a28-aa13-184649b660e0.PNG)
![Software Mode Shader](https://user-images.githubusercontent.com/101501395/158505048-3997665f-2b45-4bb2-b8a2-0c3722dc7686.PNG)
![Vulkan Mode](https://user-images.githubusercontent.com/101501395/158505061-cfc6fabe-e31e-49a9-bacd-72709d8aecba.PNG)

### GS Window Screenshots

![gs_20220315192209_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389](https://user-images.githubusercontent.com/101501395/158505079-ef32d5ee-eb73-43e2-ac6f-2aacb2cfec18.png)
![gs_20220315192411_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389](https://user-images.githubusercontent.com/101501395/158505080-ba086ce0-127e-4a96-b085-272cb9615550.png)
![gs_20220315192553_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389](https://user-images.githubusercontent.com/101501395/158505081-95d5af2c-81e3-4dee-910b-f86fd3031c21.png)
![gs_20220315192708_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389](https://user-images.githubusercontent.com/101501395/158505083-deb4c10d-4e8b-4fbb-b761-da9a1f42f100.png)

### Logs & Dumps

Here is a link to the dumps
https://drive.google.com/file/d/1uf0GDTAVHCUrDgVyEzYirP30YngWJScx/view?usp=sharing

**Comment by refractionpcsx2** [comment]
dude, there's no need for such huge gsdumps, a single frame would have been fine.

**Comment by Rimalogo** [comment]
I thought it would have been best to have it be multi frame to show the issue better.

How do I give you my emulog? Where would it be located?

**Comment by Rimalogo** [comment]
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/8274280/emuLog.txt)
found it, here is my emulog

**Comment by F0bes** [comment]
```
Bios Found: Europe  v01.60(04/10/2001)  Console
Bios Found: Europe  v02.00(14/06/2004)  Console
Bios Found: Japan   v01.00(17/01/2000)  Console
Bios Found: USA     v01.60(07/02/2002)  Console
```
Sorry, we can't offer support to those who pirate. Please considering dumping from your own PS2 console.

**Comment by Rimalogo** [comment]
so...does this mean the issues are gonna be ignored or are they gonna be added to a log of things that need to be fixed? Piracy or not these are legit issues that are happening with the game that should be addressed.
