### ISSUE TITLE
[Feature Request]: Ability to have subfolders in Replacements Folder

### ISSUE THREAD

**Issue by xflamexofxhopex** [PCSX2/pcsx2#5677]
### Description

Not sure if this is possible, but is there a way to make it where we can have things stored in subfolders, to better organize textures in our replacements folder, but the emulator read them all as if they are in one folder, like they are now?

### Reason

It will make custom texture replacement more organized for all. You could have things organized in subfolders, to differentiate what is what, but not have duplicate textures. 

### Examples

I think Dolphin's allows this, but I could be wrong. Essentially make it where it can read textures in the base replacements folder and in whatever name folder you put within said directory.

**Comment by refractionpcsx2** [comment]
Organise them how? Are you basically asking we ignore any folders inside the replacement folder so you can organise them in some manner?

Out of curiosity what example would you need to organise them like this? surely this will promote duplication, not reduce it because you could put the same texture in multiple folders, then which one do we pick?

**Comment by xflamexofxhopex** [comment]
> Organise them how? Are you basically asking we ignore any folders inside the replacement folder so you can organise them in some manner?
> 
> Out of curiosity what example would you need to organise them like this? surely this will promote duplication because you could put the same texture in multiple folders, then which one do we pick?

That I'm not 100% sure. That's why I brought it up. Not asking to ignore folders in replacement though, just read them all at once? I figured someone would bring this up eventually when people have more and more textures they replace, so I wanted to get the ball rolling on seeing if it is possible.

**Comment by xflamexofxhopex** [comment]
I mean I notice that when we have a png and dds of the same hash in the replacements folder as is, it generally reads the png and ignores the dds that's there, but it will read the dds if no png is there. So technically there already is duplication. I don't understand this stuff like you guys do and will not act like I do, but wanted to see if it is possible. Maybe if you have the same texture in the multiple folders, it reads the one that is first in alphabetical structure wise? I mean if this was a thing, I would think people would avoid trying to do duplicate textures as is. I think it works this way with dolphin's texture replacement. I do know theirs also will not dump textures that are being replaced, so that would be cool as an option too. 
Again, not saying I understand this, but wanted to see if possible. I guess texture packs would be an alternate solution, maybe.

**Comment by xflamexofxhopex** [comment]
Also I noticed dds textures do not read when they're compressed, for me. I can try to save as any compression setting in PS (using intel texture works plugin) and the emulator won't read them as replacements, but if I leave them uncompressed, they do read. PNG work fine (although they flicker a bit in hardware mode, not sure about software)

**Comment by RedDevilus** [comment]
I don't see how this will make it more organised. Instead of one big folder you have multiple folders which means more clicks and you have less overview.

**Comment by xflamexofxhopex** [comment]
Again, my point is that you can read either from the folder you set and that's it, or you can read from that folder and any folders that are within the folder you set. Not outside of it. Not saying read from multiple locations outside of the folder you set, just the option to read from the subfolders placed within the main folder it reads from, and not force it, just give us an option.

**Comment by stenzek** [comment]
It should scan recursively already.

**Comment by xflamexofxhopex** [comment]
> It should scan recursively already.

I did not know this. We had someone in our team who had the issue, but I will check myself and confirm. Also is the flickering with replacement PNG files a known issue? What compression methods are currently allowed with replacement when using DDS? Only uncompressed dds files work in hardware mode.

**Comment by stenzek** [comment]
Compressed textures worked fine in my testing.

**Comment by xflamexofxhopex** [comment]
> Compressed textures worked fine in my testing.

Could it be my textures were too large in scale? Is there a maximum to scale we are allowed to do when upscaling images?

**Comment by xflamexofxhopex** [comment]
Can confirm this. Closing.
