### ISSUE TITLE
[Feature Request] Visual feedback for selecting, loading and saving savestates

### ISSUE THREAD

**Issue by Flavescent** [PCSX2/pcsx2#568]
When selecting, loading and saving savestates via F1 - F3, the emulator should give the user visual feedback, such as by briefly displaying the text "Saved in slot 0", "Restored from slot 0" or "Slot 1 selected", as appropriate.

As it is, if one presses F1 - F3, nothing visible happens, except that the emulator very briefly pauses when saving, and the state changes when loading. However, there's no way for players to see (on-screen) which slot is selected for saving and loading, or whether the state has been correctly saved.

**Comment by karasuhebi** [comment]
I second this.

**Comment by ssakash** [comment]
why would anyone press the key without knowing it's use ? anyway, I think this would still be a useful feature.

**Comment by vsub** [comment]
I second this too,I'm almost never sure if I actually created the save state.
It would be nice to have message after you successfully saved the save state(I have experience of loosing game progress because the save state was not created(even tho I press the hotkey)...this was not on pcsx2)

**Comment by ssakash** [comment]
I will take a look at it when I have a free time, I have to look at the GUI side for now.

**Comment by refractionpcsx2** [comment]
I take it none of you have the console turned on then? :P

**Comment by ssakash** [comment]
I think he wants it to be displayed on the game window rather than the console log since, the log could be easily missed when using the border-less fullscreen mode.

**Comment by refractionpcsx2** [comment]
I believe ZeroGS does this in the top left corner

**Comment by ssakash** [comment]
thanks for the example. I might try implementing it similar to that :)

**Comment by bositman** [comment]
vsub has already done this a long time ago, check it out: http://forums.pcsx2.net/Thread-Multi-Converter-Cheats-decrypter-converter-editor-and-much-more

**Comment by vsub** [comment]
Well,yes,I did but I always prefer build in features rather than using something external(and I often forget to start the program :p )
I get the message from the console and display in the window with the save state preview

**Comment by Flavescent** [comment]
Refractionpcsx2, yes, this feature would be useful for those who play fullscreen and don't see the console. For me, it's a bit of a bother to have to alt-tab to the console whenever I want to save or load in order to check which savestate is currently active.

Displaying timestamp information would also be useful, such as: "Slot 0 selected. Last save: YYYY-MM-TT HH:MM:SS".

**Comment by gregory38** [comment]
There is a very old branch to add an OSD to GSdx. Maybe I could restore it.

**Comment by karasuhebi** [comment]
>I take it none of you have the console turned on then? :P

I do but I play in fullscreen and barely ever remember to move the console to one of my other monitors to keep an eye on it.

**Comment by refractionpcsx2** [comment]
I vaguely remember lilypad hacking a hack to show the savestate slot in the gs window as well, unless your fullscreen doesn't have the title bar (though i didn't think you could do this any more)

**Comment by avih** [comment]
I interpret the request as to have some OSD-like functionality (inside the actual GS window and not at the title bar), to be used for some important messages while playing full screen, like save state slot change, save state success, turbo mode change, maybe FPS, deinterlace mode change, etc.

It's not the first time this has been requested, and it would _probably_ mean that the GS plugin should expose some API for that and then PCSX2 would use it to display messages.

Another option is that PCSX2 overlays text over the GS window regardless of the GS plugin.

API suggestion 1:
`OSD(text, x, y, fontSize, color, duration, id)`
- x/y/fontSize are relative to the window height and not tied to any specific internal or external resolution.
- x/y can be negative (meaning counting backwards from the end).
- id removes from screen any previous message used with the same id regardless if its duration has not passed yet.
- everything except for `text` is optional, with reasonable defaults.

API suggestion 2:
`OSD(text)` where a few lines of teminal-like buffer is maintained and scrolled up out of view at a rate of 1 line per NN seconds. Or, a simpler implementation - each OSD message replaces the previous one and disappears after NN seconds.

@gabest11 , thoughts?

**Comment by karasuhebi** [comment]
>I vaguely remember lilypad having a hack to show the savestate slot in the gs window as well, 

According to what I see in the plugin settings window for Lilypad, it shows it in the title bar, not inside the window itself.

>unless your fullscreen doesn't have the title bar (though i didn't think you could do this any more)

I'm not sure what you mean here. Are you saying it's not possible to go fullscreen anymore while hiding the title bar? I'm confused. The whole point of full screen is not to have any UI showing.

**Comment by gabest11** [comment]
My dream is to have a whole visual debugger of the GS state. Why not aim higher!

**Comment by ramapcsx2** [comment]
Avih's OSD(text) sounds like a good start. It's not as involved as the first api alternative but still totally sufficient to display important information.

**Comment by karasuhebi** [comment]
@Flavescent You can see the current state slot number in the title bar.

**Comment by avih** [comment]
> You can see the current state slot number in the title bar and as of 9b988ee

The slot number has always been at the title bar (since 2011) at the end of it as e.g. `State: 2`. The commit you mentioned didn't change anything in how the title bar looks by default,  and slightly before that the slot number was moved to the beginning of the title as e.g. `Slot: 2`. That whole paragraph is incorrect, misleading and off topic.

**Comment by karasuhebi** [comment]
Sorry if I gave the impression that the slot number in the title bar is a new development, that's not what I meant to do. I know the slot number in the title bar has been around forever, I just didn't see it mentioned anywhere in this thread so I wanted to make sure @Flavescent knew about it. Quotes like these make me think he didn't know:
>For me, it's a bit of a bother to have to alt-tab to the console whenever I want to save or load in order to check which savestate is currently active.

And I know the commit I mentioned didn't change the default look of the title bar, that's the commit for the template system you implemented, which is exactly what I said in the post:
>and as of 9b988ee, there's a template system in place so that you can rearrange all the information in the title bar any way you want. 

___
>It's already the first thing at the bar, and has been so before you posted your message.

You are correct; I forgot that that was there by default as of recent build. It's still nice to mention it to him though so he can see how useful it can be. I was basically just giving an example.
