### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by leonSDG** [PCSX2/pcsx2#5690]
### Description

Add internal frame rate detection and skip duplicate frames option 

### Reason

this feature removes internal duplicate frames from games to improve performance

### Examples

to render 1 frame per second the PlayStation 2 needs two images, in the video processing it has 1 frame heavier and the other one lighter, in this case the gpu renders first the heaviest frame then the lightest, but in the rendering process the lighter frame the hardware understands that it doesn't need a lot of processing causing inconsistencies during the game, removing one of these frames allows greater performance showing the real fps of the game

**Comment by refractionpcsx2** [comment]
We already have an internal framerate counter on screen if you enable the FPS in OSD

![image](https://user-images.githubusercontent.com/6278726/158997141-e67b4173-d54f-48d8-8e4d-20159da1b887.png)

I believe the skip duplicate frames actually was tested and didn't make any difference in performance or anything so there wasn't really much point.
