### ISSUE TITLE
[BUG]: The 1.7 nightlies aren't applying the Norwegian .po translation files properly

### ISSUE THREAD

**Issue by DandelionSprout** [PCSX2/pcsx2#5693]
### Describe the Bug

I've noticed that in the 1.7 nightly builds, a lot of lines from https://github.com/PCSX2/pcsx2/blob/master/locales/nb_NO/pcsx2_Main.po seemingly aren't being applied in the PCSX2 menus: 
![image](https://user-images.githubusercontent.com/22780683/159022938-bcb4a7cb-4cae-4d26-b38e-dda337238ab2.png)

This is in contrast to 1.6 stable, where they are applied correctly: 
![image](https://user-images.githubusercontent.com/22780683/159023463-552cf8de-1ecd-4ec4-a760-6dc1769d5b87.png)

This applies both to `pcsx2-v1.7.2480-windows-64bit-AVX2.7z` and `pcsx2-v1.7.2480-windows-64bit-SSE4.7z` from https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2480; and also applies to [lines that have been translated in the .po files for some years already](https://github.com/PCSX2/pcsx2/blob/47cfbcb3fbd4c7eeb6acd213e9c4568b2a97f6b1/locales/nb_NO/pcsx2_Main.po#L1576_L1578).

To my surprise, however, generating a `pcsx2_Main.mo` file from https://github.com/PCSX2/pcsx2/blob/master/locales/nb_NO/pcsx2_Main.po and copying it into `C:\Users\[redacted]\Downloads\pcsx2-v1.7.2480-windows-64bit-SSE4\resources\locale` on my PC, did not change the situation in any way; so it seems to be a file implementation problem rather than a file/translation sync problem.

### Reproduction Steps

1) Download a `windows-64bit-AVX2.7z` nightly from https://github.com/PCSX2/pcsx2/releases
2) Go to Setup → Change Language → Norwegian (Bokmal).
3) Restart PCSX2.
4) Click on "Oppsett" in the top bar and notice that none of the submenu lines are currently being translated, e.g. "Memory Cards".

### Expected Behavior

That the Nightly version utilises considerably more lines from the .po files.

Alternately, that the files at https://github.com/PCSX2/pcsx2/tree/master/locales are updated to reflect changes in the source strings.

### PCSX2 Revision

1.7.2480

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
The UI has been changed since 1.6 and the translations files haven't been updated , with WX going away their  no point to update them since QT is being introduced  :slightly_smiling_face:

**Comment by lightningterror** [comment]
Translations will be looked in to feature freeze before release as well.
