### ISSUE TITLE
[BUG]: Gran Turismo 4 - Bad Edges on Split Time Vehicle Icons

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#5695]
### Describe the Bug

On any race, with any vehicle, the vehicle icon which appears while showing split times will have a line on the bottom and right edges. The icon is not supposed to have any boundaries, and is supposed to be transparent except for the vehicle picture on it.

Bug was introduced by 1.7.2126 and present up to latest master as of writing.

### Reproduction Steps

Boot the game, no memory card required, no adjustments to rounding/clamping required. Game must be launched with hardware rendering and upscaling, issue will not occur if the split time first appears on software rendering or native resolution hardware rendering. Go to arcade mode, pick single race. Pick any track, pick any car. Start the race and progress until a split time appears.

### Expected Behavior

Split time icon should appear without any lines on its edges.

### PCSX2 Revision

1.7.2126 to 1.7.2480

### Operating System

Windows 10 (64bit)

### CPU

R7 5800X

### GPU

RX 6900 XT

### GS Settings

4x Native

### Emulation Settings

Preset 3

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/6377490/159072083-d1321791-b54a-4b9b-b625-cc8fde8e3f6d.png)

### Logs & Dumps

[gs_20220318210426.zip](https://github.com/PCSX2/pcsx2/files/8307167/gs_20220318210426.zip)

**Comment by refractionpcsx2** [comment]
Tagging @iMineLink

**Comment by iMineLink** [comment]
Does the issue persist?

**Comment by JordanTheToaster** [comment]
Still an issue in Nightly 1.7.2944

![image](https://user-images.githubusercontent.com/80843560/173793266-a43c05d9-60f2-4baf-af2d-fdf164b69d5d.png)

**Comment by JordanTheToaster** [comment]
Correction this is fixed as of 1.7.2944

![image](https://user-images.githubusercontent.com/80843560/173794311-7eca5687-6cc6-47d5-9ae7-9ea6782191c4.png)
