### ISSUE TITLE
[BUG]: Mercenaries - Playground of Destruction - Missing triangle prompt

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5698]
### Describe the Bug

Software mode display it correctly:
![MercenariesSW](https://user-images.githubusercontent.com/24227051/159100295-cc90cbfa-a8f3-4813-a44d-b7b03e0b8a75.png)

Hardware mode doesn't:
![MercenariesHW](https://user-images.githubusercontent.com/24227051/159100374-f990f0e7-f3f2-4e28-8d12-e28a154d67eb.png)

### Reproduction Steps

Press X several times and wait till the plane FMV plays a bit and switches you to that location.

### Expected Behavior

Show triangle prompt

### PCSX2 Revision

1.7.2481

### Operating System

Windows 10 (64bit)

### CPU

i7-9750H

### GPU

2060M

### Logs & Dumps

[gs_20220318173246_Mercenaries_-_Playground_of_Destruction__NTSC-U__SLUS-20932.zip](https://github.com/PCSX2/pcsx2/files/8308321/gs_20220318173246_Mercenaries_-_Playground_of_Destruction__NTSC-U__SLUS-20932.zip)

**Comment by Mrlinkwii** [comment]
seems fixed as of v1.7.4489 atleast in the gs dump 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/68cbab78-d5a8-4ce6-8bb9-f9e6becc4d64)
