### ISSUE TITLE
[BUG]: I can't replace the texture of character in game ultraman fe3

### ISSUE THREAD

**Issue by duongvinhthai00** [PCSX2/pcsx2#5703]
### Describe the Bug

I can replace everything but when I replace the texture of the character it doesn't work and I note when I dump the seri of texture of character is random other texture  is not

### Reproduction Steps

When I load texture

### PCSX2 Revision

Latest

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
This isn't a support site, please visit our discord or the forums if you're having trouble doing something.
