### ISSUE TITLE
[Feature Request]: Automatically deinterlacing screenshots while you're on deinterlacing mode NONE

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [PCSX2/pcsx2#5708]
### Description

PCSX2 screen capturer should de-interlace the captured frame correctly to get a image similar to what you're seeing in the emulator window, even if you're playing without de-interlacing.

### Reason

If you take a screenshot of a 480i game on de-interlacing mode NONE, the image will have half the vertical resolution and an abnormally wide aspect ratio.

No Deinterlacing:
![gs_20220320005043_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937](https://user-images.githubusercontent.com/16591467/159142447-c6b0306e-2cce-4e13-9410-59d62e2941d7.png)

Deinterlacing auto:
![gs_20220320005057_Wild ARMs - Alter Code F _NTSC-U__SLUS-20937](https://user-images.githubusercontent.com/16591467/159142448-0eb825a8-22ca-41fa-a5f9-bf2263a75351.png)

Although this is technically correct (as I understand, a 480i frame will only contains 240 lines), these halved images have little representative value. Plus, generating screenshots so different from what the users are seeing is counterintuitive and confusing.

PCSX2 should allow to automatically de-interlacing screenshots in NONE mode, at least as an OPT-IN option. It would benefit the players that regularly play in that mode (it is recommended for [non-interlacing patches](https://forums.pcsx2.net/Thread-No-interlacing-codes)) so they don't have to switch modes before and after capturing the screen.

### Examples

I can't provide examples. I don't know other emulators with de-interlacing.

**Comment by RedDevilus** [comment]
De-interlacing is applied upon the output, so either you do progressive or deinterlacing patches, I don't think you can do much else.

**Comment by refractionpcsx2** [comment]
That's how deinterlacing works. On the PS2 one of the options (which this game uses) is to render the picture from 2 half pictures.  if you turn deinterlacing off, you only get half the picture.

So no, there's nothing we can/will do about this. You turn something off, it'll be off.
