### ISSUE TITLE
[BUG]: Knockout Kings 2001 missing graphics (Regression)

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#5709]
### Describe the Bug

Most of the graphics are missing ingame if you load the game using the HW renderer, starting in SW and changing once ingame is fine, was broken by #4094

Tagging @iMineLink 

### Reproduction Steps

Load the blockdump, keep hammering X and Start to skip videos and go ingame with HW mode active, witness missing everything :P

### Expected Behavior

It doesn't break :P

### PCSX2 Revision

Anything post 1.7.2125

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3900X

### GPU

RTX 2080 TI

### GS Settings

Any hardware mode, everything else irrelevant (afaik)

### GS Window Screenshots

![unknown](https://user-images.githubusercontent.com/6278726/159143016-af082ad7-c435-496f-b4eb-896792c67b77.png)

### Logs & Dumps

https://drive.google.com/file/d/11f_QhaqJ-aWuFFIY1d7hRIN2QLqntfdK/view?usp=sharing

**Comment by RedDevilus** [comment]
So this game worked by accident and needs Disable Partial Invalidation (Older name was Fast Texture Invalidation)
