### ISSUE TITLE
[BUG]: The Aspect Ratio preferences crops the image to fit in the window/fullscreen instead of using black padding

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [PCSX2/pcsx2#5710]
### Describe the Bug

While playing a 4:3 game in 4:3 mode (or 16:9 game and AR mode), if you resize the window to a different aspect PCSX2 will crop the frame vertically or horizontally to fit the screen instead of preserve the aspect ratio of the frame and fill the extra space with black .

Example:
4:3 on a 4:3-ish window
![redimensionar0](https://user-images.githubusercontent.com/16591467/159143147-eec517b9-0e67-4775-bffe-7d5e7f1b97ed.jpg)

4:3 on a narrow window, crops horizontally
![redimensionar1](https://user-images.githubusercontent.com/16591467/159143149-f87a5d90-ae73-4593-946c-8d44cfa49dbc.jpg)

4:3 in a wider window, crops vertically
![redimensionar2](https://user-images.githubusercontent.com/16591467/159143151-0355a6de-a2f7-4c86-868c-e8ac3fb6b5e4.jpg)

The same happens in Fullscreen, to play a 4:3 game in a 16:9 screen I'm forced to choose between a stretched image or a cropped one.

### Reproduction Steps

Resize the game rendering window with 4:3 or 16:9 aspect ratios.

### Expected Behavior

Specifying an aspect ratio should keep the entire frame in that aspect ratio, filling any unused space in the window or monitor with blackness

Simulation:
![redimensionar1 copia](https://user-images.githubusercontent.com/16591467/159143401-57d561e4-be6e-4fa6-9c5f-2951f3187072.jpg)
![redimensionar2 copia](https://user-images.githubusercontent.com/16591467/159143402-440c1d10-b2e9-44d0-be92-bad7c0f5fb66.jpg)
.

### PCSX2 Revision

1.7.2485

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
It works correctly for me, are you doing anything weird to get it to happen?

**Comment by refractionpcsx2** [comment]
![image](https://user-images.githubusercontent.com/6278726/159143486-7586a0e8-4123-45d0-b572-7d9af6316f4e.png)

![image](https://user-images.githubusercontent.com/6278726/159143493-f3184de1-eac5-46b4-989f-0a13a563283e.png)

**Comment by Tokman5** [comment]
try this:
Ctrl + numpad * | Resets the zoom on the GS window and otherwise toggles between automatic cropping of black borders and not cropping.
-- | --

**Comment by refractionpcsx2** [comment]
hmm those controls do nothing for me.

**Comment by refractionpcsx2** [comment]
Pressing it again re-fixes it, more like it's going to a preset zoom, then unsetting it.

**Comment by refractionpcsx2** [comment]
Closing, it's doing exactly what it's being told to do.
