### ISSUE TITLE
GSdx OpenGL Hardware depth breaks Digital Devil Saga (1) (U)

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#572]
-PCSX2 version: 1.3.0 GIT 425-g2cbde89 but using GSdx from GIT 426-g4914620

-PCSX2 options: Defaults

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, tested with native and scaling

-Description: When using accurate_date = 1 with the OpenGL backend and you have NOT disabled the CRC hack, almost the whole main character is missing.

-**NOTE: The game has a CRC hack that addresses a different issue (see-though walls/objects). If the CRC hack is OFF and accurate date=1, the character appears properly but you get see-through walls/objects. If the CRC hack is ON and accurate date=1, you get the missing character but proper wall/objects**

-How to replicate: Boot the game, skip all cutscenes and when you gain control the glitch will be visuble (your playable character is mostly missing)

-Last known version to work: -

-PC specifications: CPU: Intel Core i5 2500K @ 4.3Ghz GPU: Gigabyte Geforce GTX660 Windforce OC 2 GB OS: Windows 7 SP1

GS dump: http://bositman.pcsx2.net/dumps/Digital_Devil_Saga_1_accurate_date.rar  (contains screenshots of how it looks and how it's supposed to look)

**Comment by refractionpcsx2** [comment]
I'd be more inclined to point at the CRC hack for refinement than the Date option.  How did the character look previous to accurate date with CRC hacks off?

**Comment by bositman** [comment]
If you mean accurate date off and CRC hacks off, you get proper character and see through walls

**Comment by refractionpcsx2** [comment]
ok just wanted to clarify that Date is not helping at all in this instance :) However i suspect still the CRC is just to vague with its check on what to skip

**Comment by gregory38** [comment]
What is the sw renderer status?

**Comment by bositman** [comment]
SW looks perfect with date on or off

**Comment by bositman** [comment]
Damn it I mixed it up. Edited the report, if CRC hacks are on (ie disable CRCs off) and date is ON, then you get missing character. If CRC hacks are off and date is ON, you get proper character but see though walls

**Comment by refractionpcsx2** [comment]
Digital_Devil_Saga_1_accurate_date.bmp looks quite accurate to how i'd expect things to be, is that accurate date on and crc off?

**Comment by bositman** [comment]
That's from SW mode, it got generated from the GS dump process (I used the SW renderer to take the snap)

**Comment by refractionpcsx2** [comment]
oooh okay :) Thought it looked good haha

**Comment by gregory38** [comment]
Date is "destination alpha testing". If destination is wrong, date will be wrong. I suspect that previous rendering is wrong.

**Comment by AltimorTASDK** [comment]
SMT games in general have issues with depth because they try to back up and restore the depth buffer before/after drawing shadows. This issue, as well as the shadow issue, would probably be fixed if direct depth buffer access were supported.

**Comment by gregory38** [comment]
Seem to work on my side http://imgur.com/fUCGHrI ;)

**Comment by refractionpcsx2** [comment]
Mine looks like that too :p

**Comment by gregory38** [comment]
What is the status on GSdx 2.0. I think that it must work now.

**Comment by bositman** [comment]
Retested. If I disable CRC hacks I still get the see through wall problem. If I leave CRC hacks to full, the problem is ALSO there when HW OGL depth is on, works as expected when it's off (skips the effect and no see through walls).
Accurate date doesn't affect it anymore

**Comment by gregory38** [comment]
Hum, previous gs dump seem to work on my side. Could you give me another dump?

**Comment by bositman** [comment]
Yeah, made a new one: http://bositman.pcsx2.net/dumps/digital_devil_saga.rar

**Comment by karasuhebi** [comment]
Does it appear fix in the newest builds @bositman?

Off-topic: .rar files? Are you on WinRAR? O_O

**Comment by bositman** [comment]
Yes I'm using winrar. Nope the issue persists, if HW OpenGL depth is on, even if you have CRC hacks full, walls are see through. If you have depth off and CRC hacks full, walls are ok

**Comment by karasuhebi** [comment]
7-Zip please. WinRAR is closed-source shareware whilst 7-Zip is open-source goodness. :D

**Comment by gregory38** [comment]
I think I know the issue. Don't have time to implement and check it.

**Comment by bositman** [comment]
I don't see what the problem is with me using a closed source shareware to compress stuff. I like it much more than 7zip.

**Comment by refractionpcsx2** [comment]
Does Linux support rar? I know 7zip format is very similar to xz format so it's technically compatible. Compression is generally slightly better in 7z for me

**Comment by gregory38** [comment]
Dont't worry for me I'm a big boy. I can extract rar file on linux. Anyway, please it isn't a forum. My mailbox is already filled with enough junk.

**Comment by bositman** [comment]
Does this need testing with something else than https://github.com/PCSX2/pcsx2/pull/893 ? I just tested with that build and nothing changed since my comment above:
Nope the issue persists, if HW OpenGL depth is on, even if you have CRC hacks full, walls are see through. If you have depth off and CRC hacks full, walls are ok
Accurate date doesn't affect it anymore.

Also updated title to reflect the new status

**Comment by gregory38** [comment]
For the record, I think the issue is related to this kind of depth transfer GPU=>GS=>EE. Currently the code in ```GSTextureCache::InvalidateLocalMem``` start by 
```
	// No depth handling please.
	if (psm == PSM_PSMZ32 || psm == PSM_PSMZ24 || psm == PSM_PSMZ16 || psm == PSM_PSMZ16S)
		return;
```
It need to be updated to properly transfer the correct value. The good news is that HW depth support the reverse transfer i.e. EE=>GS=>GPU (that why it is more broken than DX).

Those transfers aren't well supported by the GS dump. So it need to be done on the real game which is 100x times more complex

**Comment by gregory38** [comment]
Could someone check the PR #1278  ? (it is a stab on the dark)
