### ISSUE TITLE
[BUG]: Virtua Quest NTSC-U - Issue with the map

### ISSUE THREAD

**Issue by xiriby** [PCSX2/pcsx2#5721]
### Describe the Bug

Some of the lines inside the map are invisible on native resolution.

Upscaling can make some of the invisible lines visible but they are too thick 
 
None of the upscaling hacks affect them.

### Reproduction Steps

Start the game

### Expected Behavior

the lines should be wider

### PCSX2 Revision

1.7-2496

### Operating System

Windows 10 (64bit)

### CPU

i7-8700

### GPU

gtx 1060 

### GS Settings

![158125493-3538da04-f768-4e07-b35d-77242f81aa13](https://user-images.githubusercontent.com/101547056/159173841-7391061e-b8f9-4142-b724-eb5261a820c2.jpg)

### Emulation Settings

![158125539-dfb14e37-6e00-4155-a0e0-9364275ee2ef](https://user-images.githubusercontent.com/101547056/159173846-1d49cd49-df1d-4f82-bb59-177e58dc82d4.jpg)

### GS Window Screenshots

Software Mode
![gs_20220320184225_Virtua Quest _NTSC-U__SLUS-20977](https://user-images.githubusercontent.com/101547056/159173895-6d6e6156-daaa-4a83-8c39-45908d19f13f.png)

Hardware Mode - Native
![gs_20220320184423_Virtua Quest _NTSC-U__SLUS-20977](https://user-images.githubusercontent.com/101547056/159173908-354e6972-8b92-4cd5-b424-5e1023ad2ccb.png)

Hardware Mode - 2x
![gs_20220320184450_Virtua Quest _NTSC-U__SLUS-20977](https://user-images.githubusercontent.com/101547056/159173926-df5a9a74-3bdc-484a-9596-eb5e7a74e48b.png)

Hardware Mode - 3x and above
![gs_20220320184523_Virtua Quest _NTSC-U__SLUS-20977](https://user-images.githubusercontent.com/101547056/159174014-483abac7-8d93-42f6-91c7-4cfe3dff7293.png)

### Logs & Dumps

[gs_20220320184423_Virtua Quest _NTSC-U__SLUS-20977.zip](https://github.com/PCSX2/pcsx2/files/8311764/gs_20220320184423_Virtua.Quest._NTSC-U__SLUS-20977.zip)

**Comment by refractionpcsx2** [comment]
How does it look in hardware mode with Native resolution?

**Comment by refractionpcsx2** [comment]
It's an Anti-Aliasing problem (or lack thereof in hardware mode)

**Comment by lightningterror** [comment]
Closing in favour of meta issue.
