### ISSUE TITLE
GSdx OpenGL HW crashes Dirge of Cerberus - FFVII (U)

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#573]
PCSX2 version: 1.3.0 GIT 425-g2cbde89 but using GSdx from GIT 426-g4914620

-PCSX2 options: Defaults

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, tested with native and scaling. Tested with an older GSdx as well ( https://github.com/PCSX2/pcsx2/commit/ae70344fbcf9d950848912b7d11bb32d5a5ac111 ) to make sure, I presume this has been always broken.

-Description: When using GSdx OpenGL backend in HW mode (with native res too), the game crashes PCSX2 before the first intro FMV is played. 
-OpenGL SW works fine
-DX9/11 show the video properly in SW modes and in HW native. On HW non-native, you get messed up lines in the video

-How to replicate: Boot the game and wait a few seconds after the first logos until it reaches the intro video

-Last known version to work: -

-PC specifications: CPU: Intel Core i5 2500K @ 4.3Ghz GPU: Gigabyte Geforce GTX660 Windforce OC 2 GB OS: Windows 7 SP1

Linuz ISO blockdump: http://bositman.pcsx2.net/dumps/DirgeofCerberus-FinalFantasyVII(U)-crashing_vid_opengl_hw.rar

**Comment by refractionpcsx2** [comment]
So has it never worked on OGL?

**Comment by bositman** [comment]
Well the old rev I tested was quite some time ago so I presume yes

**Comment by gregory38** [comment]
No crash here. However I agree with you, there is something bad in the fmv rendering.

Could you post your GSdx.ini file

@refractionpcsx2 do you have the crash too ?

**Comment by bositman** [comment]
Here it is: 
[Settings]
Adapter=10DE:11C0:354E1458:A1
Renderer=12
Interlace=7
AspectRatio=0
upscale_multiplier=4
filter=2
paltex=0
logz=1
fba=1
aa1=0
nativeres=0
resx=1024
resy=1024
extrathreads=3
AnisotropicFiltering=0
ShadeBoost=0
Fxaa=0
shaderfx=0
shaderfx_conf=shaders/GSdx_FX_Settings.ini
shaderfx_glsl=shaders/GSdx.fx
accurate_blend=1
accurate_colclip=1
accurate_date=1
UserHacks=0
UserHacks_AutoSkipDrawDepth=0
Userhacks_stretch_sprite=0
UserHacks_MSAA=0
UserHacks_AlphaHack=0
UserHacks_HalfPixelOffset=0
UserHacks_SpriteHack=0
UserHacks_SkipDraw=0
UserHacks_WildHack=0
UserHacks_AggressiveCRC=0
UserHacks_AlphaStencil=0
UserHacks_DisableCrcHacks=0
UserHacks_round_sprite_offset=0
Userhacks_align_sprite_X=0
UserHacks_TCOffset=0

**Comment by refractionpcsx2** [comment]
I'll try tonight, not noticed a crash  on any other games

**Comment by gregory38** [comment]
I know that openGL used to crash during read fifo access from the core. Code wasn't multi-thread safe and it was fixed. KH does this kind of read around FMV too. It is really strange.

**Comment by karasuhebi** [comment]
@bositman Just out of curiosity, why did you include a block dump?

**Comment by bositman** [comment]
Because it crashes, a GS dump might not have been enough

**Comment by refractionpcsx2** [comment]
Crash confirmed,  i ran it in debug and got this

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...\ps2\gitrepo\pcsx2\bin\plugins\GSdx32-AVX2-dbg.dll
File: g:\programming\ps2\gitrepo\pcsx2\pl...\GSVerte...ayOGL.h
Line: 136

Expression: m_count < m_limit

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by gregory38** [comment]
Just to confirm the bug, try to disable buffer storage extension
```
override_GL_ARB_buffer_storage = 0
```

**Comment by gregory38** [comment]
By the way, the game uses tons of vertices to draw the screen that why the crash (assertion) appears. We around 40K of triangles for a single draw, I let you imagine the number of upscaling issue. Maybe they use point primitives actually to emulate the particle effect.

**Comment by bositman** [comment]
Works now, OpenGL HW doesn't crash, looks just like DX11 (with the same bugs when upscaling)
Good job ;)

**Comment by gregory38** [comment]
Thanks. 1 less :+1: 

Maybe it is possible to improve quality with upscaling. My guess is that the game uses point rendering of size 0. With upscaling is remain 0. If we increase the size of the point to 1. It will become bigger with upscaling. But I'm really too busy with others task and it might not help.

**Comment by bositman** [comment]
Yeah this game is a bug fest, it has CRC hacks too and they're not enough :P Leave it for another time
