### ISSUE TITLE
[BUG]: ICO opening FMV is broken

### ISSUE THREAD

**Issue by Tzerinas** [PCSX2/pcsx2#5730]
### Describe the Bug

ICO plays an Opening FMV straight after the Logo/Start screen appears. The best way to describe it is that only part of the FMV becomes visible. Even in Software mode this Issue doesn't completely go away. 

I don't know if its helpful note: Raising the internal resolution changes how much of the FMV is visible.

### Reproduction Steps

Start ICO, skip Intro (In-Engine), the Title-Screen appears and then you have to wait for a few seconds.

### Expected Behavior

FMV is played in full.

### PCSX2 Revision

v1.7.2505-windows-64bit-AVX2

### Operating System

Windows 11

### CPU

I5 4690k

### GPU

GTX 980

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![gs_20220321172900_Ico _NTSC-U__SCUS-97113](https://user-images.githubusercontent.com/98034944/159315678-e473910d-f162-48cb-811b-bf0aa8487d93.png)

### Logs & Dumps

https://we.tl/t-NuCZXmQYai

**Comment by Tzerinas** [comment]
Not sure if this is just the same thing as #961 . In which case I will close this.

**Comment by refractionpcsx2** [comment]
If I use the SW switch on FMV it works for me? Though it is offset weirdly, it works. Tbh I thought somebody recently added that to the GameDB, if that works for you, then we can go ahead and do that, mine was the US version, if that makes a difference.

![image](https://user-images.githubusercontent.com/6278726/159339291-690e99c0-0c39-427c-b358-950c37cbf81d.png)

**Comment by Tzerinas** [comment]
Yeah, but I wanted to add it as an issue since its not correct even in software. And I vaguely remember it as correctly centered. :)

Fake Edit: **I was wrong.** Software seems to be the correct PS2 behaviour. Footage used for reference:

https://www.youtube.com/watch?v=4VMrmdAfKW8 

(Mention of capture card in description, so I assume its straight from the PS2)

Why in the world is it offset to the left and slightly upwards? Nobody knows, because the actual video file is centered.

**Comment by refractionpcsx2** [comment]
Well it's offset incorrectly, should be moore to the right, but yeah it's in that weird box. Can you add this game to #3805
