### ISSUE TITLE
[BUG]: PCSX2 Help Menu Dead End Links

### ISSUE THREAD

**Issue by BerBerOnGithub** [PCSX2/pcsx2#5734]
### Describe the Bug

When you open any help menu options like "Compatibility", it uses "https://pcsx2.net/compatibility-list.html" instead of "https://pcsx2.net/compat/". The URL has been updated, so the websites just go to a dead end.

### Reproduction Steps

1. Start PCSX2.
2. Go to help tab.
3. Click "Compatibility" link.

### Expected Behavior

It opens the compatibility website in the browser.

### PCSX2 Revision

1.7.2514

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Can't be helped for older versions, we're going to write a redirect rule to handle those for now..

We will need to update it going forward, of course.

**Comment by seapancake** [comment]
I have implemented a page redirect to fix this for now although we'll need to update the emulator to use the new URL.

**Comment by coornio** [comment]
> Can't be helped for older versions, we're going to write a redirect rule to handle those for now..

Once 1.8 drops, that redirect should instead point to a page that says "Hey dum dum, get off this old-ass version and grab the latest stable here, will ya?"
