### ISSUE TITLE
[BUG]: Installer fails to properly install in silent mode

### ISSUE THREAD

**Issue by DanTheMan827** [PCSX2/pcsx2#5741]
### Describe the Bug

When installing in silent mode, the start menu shortcut is created, but no files are installed except for a single portable.ini file in the `PCSX 1.6.0` folder in Documents.

### Reproduction Steps

Run the installer in silent mode.

### Expected Behavior

The installer should install as a normal install but without any dialogs.

### PCSX2 Revision

1.6.0

### Operating System

Windows 11

**Comment by MrCK1** [comment]
Closing since NSIS is no longer part of the repo
