### ISSUE TITLE
[BUG]: Nicktoons Unite! Texture Cache Broken

### ISSUE THREAD

**Issue by JimScript** [PCSX2/pcsx2#5743]
### Describe the Bug

When in Hardware mode, the games textures mess up, but at a certain distance they are fine.

### Reproduction Steps

Go in game with any hardware rendering method.

### PCSX2 Revision

v1.7.2504

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 2070 Super

### GS Settings

Other than accurate destination alpha test and gpu palette conversion, it is default settings, but turning them off doesn't fix it.

### Emulation Settings

It is on safe with mtvu, but turning it off doesn't change anything.

### GS Window Screenshots

![gs_20220322132951_Nicktoons Unite_ _NTSC-U__SLUS-21284](https://user-images.githubusercontent.com/66685584/159575662-e60d8ad2-5b16-4658-8a59-24828afb3618.png)

### Logs & Dumps

GSdump: [Nicktoons Unite_MipmapBroken.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8327879/Nicktoons.Unite_MipmapBroken.gs.xz.zip)

**Comment by refractionpcsx2** [comment]
Just tried it with the texture cache disabled, and

![image](https://user-images.githubusercontent.com/6278726/159577897-0017e901-1b3c-45d8-8928-737a39d81dc3.png)

So the mipmapping is fine but the texture cache is pretty broken.

**Comment by RedDevilus** [comment]
It also needs normal (vertex) but it doesn't look that much better to the sides.

**Comment by Mike-and-Ikes** [comment]
Last time I checked I believe that the auto flush setting in HW hacks fixes this issue but it is very costly on performance for some gpus. If that doesn't work then software mode is definitely your best bet.

**Comment by JimScript** [comment]
The Auto Flush setting does not fix this issue or change it in any way.

**Comment by Mike-and-Ikes** [comment]
That's odd, I could've sworn that it worked in older versions. Maybe it's a regression issue? I believe it was a valid fix in pcsx2 1.4.0, but I'm not at my computer to check though. :(

Apologies in advance if that doesn't work either.

**Comment by Mike-and-Ikes** [comment]
I just checked on my computer to see why I thought auto flush would fix it and I found out why. Back in 1.5.0 the auto flush would fix some of the purple lines that are now fixed with the vertex offset setting, which is really strange but it proves auto flush used to do something at least.

Apologies for saying it would work completely though.
