### ISSUE TITLE
[REQUEST]: call when the game switches elf ApplyLoadedPatches(PPT_ONCE_ON_LOAD)

### ISSUE THREAD

**Issue by ThirteenAG** [PCSX2/pcsx2#5748]
### Describe the Bug

https://github.com/PCSX2/pcsx2/blob/a12ad1f627481d97e2856f86e627aea69ce57ae4/pcsx2/System/SysCoreThread.cpp#L286

I think it makes sense to call that function when the game loads another elf. E.g., in splinter cell double agent, there's three:
`SLUS_213.56`, `SC4_OFF.ELF`, `SC4_ON.ELF`, and this function is only called when starting `SLUS_213.56`, despite the main game being in SC4_OFF.ELF, which is likely the one that would need patches. 

### Reproduction Steps

Start Splinter Cell Double Agent for example.
Select singleplayer game(`SC4_OFF.ELF`) in the menu, which is `SLUS_213.56` elf.
Internal memory layout will be replaced with new elf, but `PPT_ONCE_ON_LOAD` patches will not be written after this change.

### Expected Behavior

I think it makes sense that PCSX2 should 'detect' an event of loading new elf by the game and execute `ApplyLoadedPatches(PPT_ONCE_ON_LOAD)` at that point.

### PCSX2 Revision

pcsx2-v1.7.2521

### Operating System

Windows 11

**Comment by stenzek** [comment]
This was implemented in #8902.

**Comment by CookiePLMonster** [comment]
For future readers - not all games switch ELFs via a syscall, and this is a prerequisite for this feature to work. If the system log doesn't print messages like `ELF changed, active CRC xxxxxxxx (cdrom0:\SOMETHING.ELF;1)` then the game is switching ELFs manually and this feature **won't** work. Therefore, your mileage may vary.
