### ISSUE TITLE
[BUG]: Shadow Hearts 2 Covenant - flickering screen when pausing cutscenes

### ISSUE THREAD

**Issue by roxas0zero** [PCSX2/pcsx2#5750]
### Describe the Bug

When starting the game Shadow Hearts 2 Covenant and pressing "Start" button to pause the first cutscene in the game the screen keeps flickering between a black filter and no filter.

### Reproduction Steps

1 - run the game with default emulator settings
2 - start a new game
3 - when the first cutscene plays press "Start"

### Expected Behavior

the screen should not flicker, it should stay with the black filter.

### PCSX2 Revision

v1.7.2520 (AVX2)

### Operating System

Windows 10 (64bit)

### CPU

i7-4770K

### GPU

AMD RX 580

### GS Settings

default settings.

### Emulation Settings

default settings.

### GS Window Screenshots

![gs_20220323223622_Shadow Hearts - Covenant _Disc1of2_ _NTSC-U__SLUS-21041](https://user-images.githubusercontent.com/6898829/159781726-31cbb776-c708-43cf-9ae7-9de3a80f8081.png)
![gs_20220323223629_Shadow Hearts - Covenant _Disc1of2_ _NTSC-U__SLUS-21041](https://user-images.githubusercontent.com/6898829/159781736-5a099ffc-c5ff-428a-a3df-ac7844969168.png)

### Logs & Dumps

[GS_LOGS_Shadow Hearts - Covenant _Disc1of2_ _NTSC-U__SLUS-21041.zip](https://github.com/PCSX2/pcsx2/files/8336018/GS_LOGS_Shadow.Hearts.-.Covenant._Disc1of2_._NTSC-U__SLUS-21041.zip)

**Comment by Mrlinkwii** [comment]
can this be check on latest mater ?
