### ISSUE TITLE
[Feature Request]: Don't dump every texture

### ISSUE THREAD

**Issue by CelestePolo** [PCSX2/pcsx2#5765]
### Description

I don't like the term "request" it is more suggestions for improvement.

 1) Allow to not dump textures with resolution lower than 16x16 or 8x8 for example. (already in Duckstation)
 2) Allow to not dump textures with only two hex numbers (instead of three).
 3) Allow to "blacklist" a texture by the first hex number.

### Reason

-Reduce the quantity of textures which can't be upscaled anyway
-Automatic upscaling
-Less writing on drive

### Examples

 I tried this (great :) ) feature on three games:

1) Allow to not dump textures with resolution lower than 16x16 or 8x8.
-> Example Jak and Daxter, a lot of small textures that can not be upscaled.

 2) Allow to not dump textures with only two hex numbers (instead of three).
-> On SotC, the texture is not replaced, on Crash bandicoot, there are too many times the same textures.

 3) Allow to "blacklist" a texture by the first hex number.
-> SotC : +22 000 times the same texture with different effects

**Comment by lextra2** [comment]
over 22k textures from sotc?! jeez...

**Comment by stenzek** [comment]
These requests are getting silly. Stop expecting perfection from something which is basically a giant hack (the idea of dumping/replacing textures in the first place).

Any replacements are going to require manual work. You can't just expect to throw it all at an upscaler and get away with zero effort. If it was that easy, we'd just do the upscaling in the emu itself..
