### ISSUE TITLE
[BUG]: Corrupted FMV in Yu-Gi-Oh: Capsule Monster Coliseum

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5770]
### Describe the Bug

The intro FMV cinematic is heavily corrupted in hardware rendering, regardless of settings. It has been like so since 1.6, probably way before that too.

Here is a small recording of this corruption:

https://user-images.githubusercontent.com/11655762/160299865-eb0d7c9c-6fb0-4b8d-b4fa-e334962b77ba.mp4

I would attach a dump or something here for people, but regardless of what I try, there is absolutely no way to trigger this corruption when viewed through GS dumps, be they single or multi-frame. 

This corruption occurs so long as the game runs in hardware mode prior to the FMV starting (upscaling is irrelevant). It works fine in software rendering. If during the corruption you switch to software rendering *or* reset the hardware rendering by means of some settings change, the corruption will be gone for good.

I suspect relation to the following bug: https://github.com/PCSX2/pcsx2/issues/5318

### PCSX2 Revision

1.7.2532

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by coornio** [comment]
Not sure how but on 1.7.2731 the multi-frame dump worked. Here: 

https://www.mediafire.com/file/vgdpfki211993g4/gs_20220511134153_Yu-Gi-Oh__-_Capsule_Monster_Colisee__PAL-M5__SLES-52576.7z/file

**Comment by refractionpcsx2** [comment]
Fixed by above linked PR

**Comment by MrSlimbrowser** [comment]
That's not something that needs to be activated somewhere, right?
Just tried on current nightly build 1.7.4476 and the game is still flickering during fmv videos (SLES-52576)

**Comment by coornio** [comment]
> That's not something that needs to be activated somewhere, right? Just tried on current nightly build 1.7.4476 and the game is still flickering during FMVs (SLES-52576)

Tested it myself just now, it appears to be working fine as-is. Did you notice this on the dump itself or the game directly? What are your circumstances?

**Comment by MrSlimbrowser** [comment]
What circumstances exactly do you need?
I took the latest nightly from pcsx2.net changed nothing but controller settings, added my european bios and started up an .iso dump I made years ago. I checked iso hashes on redump, the dump is fine (matching this version http://redump.org/disc/17841/).
Tested on a Windows 10 22H2 PC with a Ryzen 5800X and an RTX 2080 Super.

Same issue occured when I tried few days ago on SteamDeck and a fresh pcsx2 install as well (using EmuDeck to install pcsx2, nightly 1.7.4451)

**Comment by coornio** [comment]
My setup is similar, except I'm on Windows 11 and with an Intel CPU, both should be inconsequential. I tested different renderers, but again not facing any issues on my side with it.

May wanna put up a small multi-frame dump, I can't think of anything which might be causing this for you.

**Comment by MrSlimbrowser** [comment]
There you go
https://1drv.ms/f/s!AnyGIPJKyfV9vFD3OvlEUZtkQBSQ?e=q5oBC3

**Comment by coornio** [comment]
> There you go https://1drv.ms/f/s!AnyGIPJKyfV9vFD3OvlEUZtkQBSQ?e=q5oBC3

Just tested it, that segment of the FMV is playing fine through the multi-frame dump, so whatever is happening to you is either limited to your system in particular, or can't be captured through a dump. 

What about other renderers? Does it persist with them? I assume software's fine right? What about your GPU driver, which version are you on at the moment?

**Comment by MrSlimbrowser** [comment]
Very weird, especially since it happens on two systems (as mentioned earlier, PC and SteamDeck) and those two have almost nothing in common.
Software Renderer works fine right away. Interestingly though, I can switch to any renderer (and back) while the fmv is playing to fix it until the next fmv starts. Same seems to happen when I change some rendering settings, e.g. Trilinear Filtering.

GPU driver on the PC is at GameReadyDriver 531.26 at the moment, I could update that to 531.79 (or latest StudioDriver) if you want. SteamDeck is updated so should be using latest drivers.

**Comment by coornio** [comment]
Hold on for now, I'm on 528.24 so let me try updating first, see if that makes a difference on my side.

**Comment by Mrlinkwii** [comment]
> Very weird, especially since it happens on two systems (as mentioned earlier, PC and SteamDeck) and those two have almost nothing in common. Software Renderer works fine right away. Interestingly though, I can switch to any renderer (and back) while the fmv is playing to fix it until the next fmv starts. Same seems to happen when I change some rendering settings, e.g. Trilinear Filtering.
> 
> GPU driver on the PC is at GameReadyDriver 531.26 at the moment, I could update that to 531.79 (or latest StudioDriver) if you want. SteamDeck is updated so should be using latest drivers.

![image](https://user-images.githubusercontent.com/17685135/236670318-870d43ed-7ebf-434a-a687-359eeddf5cd3.png)
 works here on  530.164.192

**Comment by DanielQL116** [comment]
Hello, i have the same issue with the FMVs of the game.
I already downloaded the .gs file (multi-frame dump), but i dont know how to use it.
