### ISSUE TITLE
[BUG]: Tony Hawk games suffer from artifacts in SW mode (64 bit only)

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#5780]
### Describe the Bug

Looks like All Tony Hawk Pro Skater series games ( I tested American Wasteland, Tony Hawk 4 and Downhill Domination) suffer from some weird artifacts. These look like Z Fighting but I assume this is something else since the issue doesn't happen in HW mode. The issue was also absent on 32 bit builds (before they became redundant).

### Reproduction Steps

Run the game and you will notice some textures missing and other flickering. GS dump attached.

### Expected Behavior

No graphical errors.

### PCSX2 Revision

All 64 bit builds

### Operating System

Windows 10 (64bit)

### CPU

i3-9100f

### GPU

750Ti

### Logs & Dumps

[gs_20220328214317_Tony Hawk_s American Wasteland_.zip](https://github.com/PCSX2/pcsx2/files/8374243/gs_20220328214317_Tony.Hawk_s.American.Wasteland_.zip)

**Comment by prafullpcsx2** [comment]
This bug still happens as of current Master.

**Comment by prafullpcsx2** [comment]
Fixed by https://github.com/PCSX2/pcsx2/pull/6033

**Comment by refractionpcsx2** [comment]
#6033 has now merged
