### ISSUE TITLE
[BUG]: Fatal Frame (SLUS-20388) Final Boss Softlock

### ISSUE THREAD

**Issue by Dartz150** [PCSX2/pcsx2#5781]
### Describe the Bug

The game softlocks (the image freezes, controls are irresponsive, music and sfx keeps playing) when entering in finder mode at the final boss room (Kirie). This happens in both Software and Hardware modes.

### Reproduction Steps

-Reach the final boss room.
-Wait for the first cutscene to end.
-Enter finder mode.

### Expected Behavior

Game should progress normally with no freezes, is important to mention that this happens randomly as some times the game does not freeze.

### PCSX2 Revision

1.7.2540

### Operating System

Windows 11

### CPU

i7-9700K

### GPU

RTX 2070 Super

### GS Settings

![image](https://user-images.githubusercontent.com/42103728/160700721-43e0b5ec-818b-4454-a779-a8e5a7c5b4b4.png)

### Emulation Settings

None

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/42103728/160701020-d672b0f7-e75e-4de9-87db-0f4333619350.png)

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/8374815/emuLog.txt)

**Comment by Dartz150** [comment]
Full performance stats:

![image](https://user-images.githubusercontent.com/42103728/160702909-ab61b1f4-d565-4282-ab76-39cd8bedf9a0.png)

**Comment by darkxex** [comment]
dude, that bug has been around since 2015, it's well known in the fatal frame community. there I send you a link in case you want to finish the game yet.
https://forums.pcsx2.net/Thread-Fatal-Frame-freezes-at-final-boss-Kirie

**Comment by Dartz150** [comment]
> dude, that bug has been around since 2015, it's well known in the fatal frame community. there I send you a link in case you want to finish the game yet. https://forums.pcsx2.net/Thread-Fatal-Frame-freezes-at-final-boss-Kirie

Still a bug that needs to be fixed, and according to the staff at the Discord server, someone reported (wrongly) that this bug was already squashed in the latest dev builds.

**Comment by TiredTeddybear** [comment]
Stopping by to say that as someone in the Fatal Frame community, I would greatly appreciate it if this bug were fixed. Especially since we now have a proper undub patch (with subtitles and all) for the game. Thank you to the dev team for your continued improvements on PCSX2.

**Comment by PolygonSlayer** [comment]
I would be extremely happy about this getting fixed as well. Along with the other couple of issues in the game listed on the wiki that at least can be temporary fixed by switching to and from software mode. I'm sure those are different reasons though, but yeah, absolutely in love with the new GUI and per-game configs etc. so hats off to the PCSX2 team, you guys rock :)

**Comment by TiredTeddybear** [comment]
Oh, for the record, this bug also exists in the PAL version, Project Zero (SLES-50821) and the NTSC-J version, Zero (SLPS-25074).

**Comment by Dartz150** [comment]
I should also leave this here: This bug also happens on real hardware, with the original NTSC Disc, the only difference being that it hangs randomly before the cutscene that leads to the Kirie fight, and of course in the Kirie fight.

![image](https://user-images.githubusercontent.com/42103728/171053001-d67b4d7d-612f-47dd-866e-0cbaa99337d1.png)

**Comment by kenshen112** [comment]
Footage of it occuring on real ps2 HW, https://youtu.be/PAAtwXRSTik happens at 13:00 this isn't an issue with pcsx2 as much as it is a Xenosaga esc situation in that the game glitch happens worse when emulating. 

This will need a PNACH fix, I'll probably look into it at some point with me cheese's reversing project

**Comment by F0bes** [comment]
Due to this occurring on hardware, I'm closing this issue.

**Comment by piau9000** [comment]
> Footage of it occuring on real ps2 HW, https://youtu.be/PAAtwXRSTik happens at 13:00 this isn't an issue with pcsx2 as much as it is a Xenosaga esc situation in that the game glitch happens worse when emulating.
> 
> This will need a PNACH fix, I'll probably look into it at some point with me cheese's reversing project

It seems that the original japanese version does not have this bug. Maybe something introduced by the localization team back in the day.
