### ISSUE TITLE
[BUG]: Radiata Stories upscaling issues: Artifacting, white/rainbow lines

### ISSUE THREAD

**Issue by scoot404** [PCSX2/pcsx2#5786]
### Describe the Bug

In this little stretch of the hallway in the quarters, there are these white/rainbow lines that go up on the top and the left of the screen while upscaling is on. There is some other artifacts too, such as in the intro logos and other parts of the game. This is just what I've observed from the beginning of the game. This occurs with any backend, tried OpenGL/DX11/Vulkan.

### Reproduction Steps

1. Turn on upscaling.
2. Most parts of the game may have artifacting on the left, the main issue this report is pertaining to is these white/rainbow lines.
3. Go through the intro, make it to the part where the quarters are.
4. Opening menus may make the lines appear, though it seems arbitrary as to what makes them appear.

### Expected Behavior

1. No white lines, rainbow lines, or artifacting.

### PCSX2 Revision

1.7.2540

### Operating System

Windows 10 (64bit)

### CPU

i7-4770

### GPU

GeForce GTX 1050 Ti

### GS Window Screenshots

![pcsx2x64-avx2_D9xGI6up5K](https://user-images.githubusercontent.com/1747240/160743136-864f5eed-e4fa-4c72-8bff-93f720633999.png)

### Logs & Dumps

![Rainbow Lines](https://user-images.githubusercontent.com/1747240/160743536-848d2993-6864-4b2e-991f-bd809d39d40e.png)
![White Lines](https://user-images.githubusercontent.com/1747240/160743542-a9af6b35-7ae6-4fae-8127-1a424d315b96.png)
[Screenshots/GSdumps](https://files.catbox.moe/nkw5un.zip)

**Comment by RedDevilus** [comment]
Might be the automatic upscaling fix: HalfPixelOffset: Normal (Vertex)

**Comment by Tzerinas** [comment]
Yeah, game needs Special (Texture) + Align Sprite for the best compromise. Can you add that on your PR @RedDevilus?
