### ISSUE TITLE
[BUG]: Silent Hill Origins - Map is Garbled with latest auto GS HW fix, manual mode works fine.

### ISSUE THREAD

**Issue by Dartz150** [PCSX2/pcsx2#5789]
### Describe the Bug

This [commit](https://github.com/PCSX2/pcsx2/pull/5785) added automatic HW fixes for Silent Hill Origins, which now works completely fine with no manual fixes except for the maps:

![image](https://user-images.githubusercontent.com/42103728/160947555-6f1e0ca8-691e-450c-9654-c2a1b4d43b48.png)

This is how it looks with Manual settings
![image](https://user-images.githubusercontent.com/42103728/160947663-8e652847-ee8a-46e8-8800-d379f0d1849c.png)

Testing out various scenarios, it seems that the culprit is the "Wild Arms Hack" setting.
![image](https://user-images.githubusercontent.com/42103728/160947706-2fbaee50-0869-4e86-b82a-f09c7e9257e2.png)

### Reproduction Steps

Disable manual HW hacks and run the game in any HW render mode, then check the map.

### Expected Behavior

Map should be cristal clear like this: 

![image](https://user-images.githubusercontent.com/42103728/160948007-ee190f07-2b9b-48e9-9f99-b0450e7d15a1.png)

### PCSX2 Revision

1.7.2544

### Operating System

Windows 11

### CPU

i7-9700K

### GPU

RTX 2070 Super

### GS Settings

Included above.

### GS Window Screenshots

Included above.

### Logs & Dumps

![gs_20220330173950_Silent Hill - Origins _NTSC-U__SLUS-21731](https://user-images.githubusercontent.com/42103728/160948251-7ddf9900-0036-4251-979e-2338c5b86183.png)

**Comment by RedDevilus** [comment]
Wild Arms Hack fixed some misalignment but I didn't look at the maps. I'll check again.

**Comment by refractionpcsx2** [comment]
can you test the linked PR please @Dartz150 ? Thanks

**Comment by Dartz150** [comment]
> 

![image](https://user-images.githubusercontent.com/42103728/161014291-9197d0c3-de97-49b4-8409-d8f15f9ed9ca.png)

Fixed!!

**Comment by refractionpcsx2** [comment]
How is the ghosting when upscaled? (not the map)

**Comment by Dartz150** [comment]
> How is the ghosting when upscaled? (not the map)

![image](https://user-images.githubusercontent.com/42103728/161040517-98293c2e-27cf-4e6e-a9e9-1ab4871f4bbe.png)

![image](https://user-images.githubusercontent.com/42103728/161040568-d4482cb5-7a0d-4cbf-a80b-06c185b19582.png)

No ghosting so far, everything looks fine.

**Comment by refractionpcsx2** [comment]
cool :) LGM then, I don't know why Wild Arms was said to be required, it looks fine.
