### ISSUE TITLE
[BUG]:  Street Fighter EX3 [NTSC] - D Dark bomb explosion texture load failure 

### ISSUE THREAD

**Issue by f00tf00t** [PCSX2/pcsx2#5797]
### Describe the Bug

Hi,

I noticed a bug with Street fighter EX3 with the D Dark bomb explosion texture load failure

Here it is in software working
-------------------------------------
[img]https://i.imgur.com/3jL2RHx.gif[/img]

and here it is in OGL/DX11/Vulkan failure to load
-------------------------------------
[img]https://i.imgur.com/NLGrQSr.gif[/img]

No hacks, just pcsx2 default settings; I've also uploaded the GS dump

When you execute the move this message flags up at the exact moment when the texture fails to load

"Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38"

### Reproduction Steps

Use any version of PCSX2

 - Do not change all settings leave as stock
 - Load ISO (Street fighter EX3 NTSC USA)
 - Select D Dark as playable character
 - Execute Ex-Plosive move

Software renderer  - Texture loads correctly
-------------------
<a href="https://imgur.com/3jL2RHx"><img src="https://i.imgur.com/3jL2RHx.gif" title="source: imgur.com" /></a>
 

Hardware renderer (DX11/OGL/VLKN) - Texture fails to load
-------------------
<a href="https://imgur.com/NLGrQSr"><img src="https://i.imgur.com/NLGrQSr.gif" title="source: imgur.com" /></a>

### Expected Behavior

The explosion texture is meant to load as normal

### PCSX2 Revision

v1.7.2475

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 2400G

### GPU

NVIDIA GeForce GTX 950

### GS Settings

All stock, no settings adjusted

### Emulation Settings

All stock, no settings adjusted

### Logs & Dumps

PCSX2 Nightly - v1.7.2475 Compiled on Mar 17 2022
Savestate version: 0x9a2c0000

Host Machine Init:
Operating System =  Microsoft Windows 10, 64-bit
Physical RAM    =  32690 MB
CPU name        =  AMD Ryzen 5 2400G with Radeon Vega Graphics
Vendor/Model    =  AuthenticAMD (stepping 00)
CPU speed        =  4.042 ghz (8 logical threads)
x86PType        =  Standard OEM
x86Flags        =  178bfbff 7ed8320b
x86EFlags        =  2fd3fbff

x86 Features Detected:
SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
SSE4a
Pcsx2 was compiled as 64-bits.

The current power profile is 'High performance'.
The current min / max processor states
AC: 100% / 100%
Battery: 5% / 100%

Reserving memory for recompilers...
HLE Host: Set 'host:' root path to: \

Patches: No CRC found, using 00000000 instead.
isoFile open ok: F:\roms\ps2\Street Fighter EX3 (USA).bin
Image type  = CD
* CDVD Disk Open: CD, 1 tracks (1 to 1):
* * Track 1: Data (Mode 1) (298390 sectors)
Vsync is OFF
No adapter selected, using first.
D3D Adapter: NVIDIA GeForce GTX 950
Creating a 1242x861 flip-discard windowed swap chain
D3D11 Graphics Driver Info:
D3D_FEATURE_LEVEL_11_0
VID: 0x10DE PID: 0x1402
NVIDIA GeForce GTX 950
Driver Version: 30.0.15.1179
Vsync is OFF
GS Lookup CRC:00000000
48000 SampleRate:
McdSlot 0 [File]: F:\saves\ps2\pcsx2\Mcd001.ps2
McdSlot 1 [File]: F:\saves\ps2\pcsx2\Mcd002.ps2
EE/iR5900-32 Recompiler Reset
Bios Found: Japan  v01.00(17/01/2000)  Console
BIOS rom1 module not found, skipping...
BIOS rom2 module not found, skipping...
BIOS erom module not found, skipping...
# Initialize memory (rev:3.17, ctm:393Mhz, cpuclk:295Mhz )
Frame buffer size set to  512x512 (512x512)

PlayStation 2 ======== Hard reset boot
ROMGEN=2000-0117, IOP info (CPUID=1f, CACH_CONFIG=ffffffff, 2MB, IOP mode)
<20000117-050310,ROMconf,:11232>
# Total accessable memory size: 32 MB (B:2:8:0)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
Frame buffer size set to  512x512 (512x512)
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Dec 10 1999 17:48:37
  CPUID=2e20, BoardID=0, ROMGEN=2000-0117, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
found 15776 symbols
ELF (cdrom0:\SLUS_201.30;1) Game CRC = 0x72B3802A, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 © Sony Computer Entertainment Inc.
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 ©SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15)
iop heap service (99/11/03)
loadelf: fname rom0OhmySDSYS secname all
loadelf version 3.30
Input ELF format filename = rom0OhmySDSYS
0 00200000 0008d1ec .........
Loaded, rom0OhmySDSYS
start address 0x200008
gp address 00000000
# Loader 'rom0OhmySDSYS'Tongue2c=00200008
loadmodule: fname rom0:CLEARSPU args 0 arg
clearspu: completed
loadmodule: id 25, ret 1
loadmodule: fname rom0WackoIO2MAN args 0 arg
loadmodule: id 26, ret 0
loadmodule: fname rom0:MCMAN args 0 arg
loadmodule: id 27, ret 0
loadmodule: fname rom0:MCSERV args 0 arg
loadmodule: id 28, ret 0
loadmodule: fname rom0TongueADMAN args 0 arg
Pad driver. (99/11/22)
loadmodule: id 29, ret 0
loadmodule: fname rom0OhmySDSND args 0 arg
loadmodule: id 30, ret 0
_spu_rev_offsetaddr 1f9021
### addr = 1034255  size = 28640
_spu_rev_offsetaddr 1d9021
### addr = 968719  size = 28640
read/write allocate memory 4000
open name rom0OhmySOPEN flag 1 data 41278
open fd = 2
open name rom0OhmySCLOCK flag 1 data 41278
open fd = 2
open name rom0OhmySBROWS flag 1 data 41278
open fd = 2
open name mc1:/BIEXEC-SYSTEM/OSBROWS flag 1 data 41278
open fd = -2
open name mc0:/BIEXEC-SYSTEM/OSBROWS flag 1 data 41278
open fd = -4
open name rom0OhmySFONTM flag 1 data 41278
open fd = 2
open name rom0OhmySFONTS flag 1 data 41278
open fd = 2
open name rom0:MOPEN flag 1 data 41278
open fd = 2
open name rom0:MCLOCK flag 1 data 41278
open fd = 2
open name rom0:MBROWS flag 1 data 41278
open fd = 2
open name rom0:FONTM flag 1 data 41278
open fd = 2
open name rom0:FONTS flag 1 data 41278
open fd = 2
(UpdateVSyncRate) Mode Changed to DVD NTSC.
... with user configured refresh rate: 59.93 Hz
Frame buffer size set to  640x512 (640x512)
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
50e688  D8E80000 lqc2 vf08, 0x  0(a3)
50e68c  D8C40000 lqc2 vf04, 0x  0(a2)
50e690  D8C50010 lqc2 vf05, 0x  10(a2)
50e694  D8C60020 lqc2 vf06, 0x  20(a2)
50e698  D8C70030 lqc2 vf07, 0x  30(a2)
50e69c  D8890000 lqc2 vf09, 0x  0(a0)
50e6a0  D8AA0000 lqc2 vf10, 0x  0(a1)
50e6a4  D88B0000 lqc2 vf11, 0x  0(a0)
50e6a8  D8AC0000 lqc2 vf12, 0x  0(a1)
50e6ac  4BE821BC vmulax.xyzw ACC,vf04,vf08x
50e6b0  4BE828BD vmadday.xyzw ACC,vf05,vf08y
50e6b4  4BE830BE vmaddaz.xyzw ACC,vf06,vf08z
50e6b8  4BE83A0B vmaddw.xyzw vf08, vf07, vf08w
50e6bc  4BC84ADB vmulw.xyz vf11,vf09,vf08w
50e6c0  4BC8531B vmulw.xyz vf12,vf10,vf08w
50e6c4  4A0002FF vnop
50e6c8  4A0002FF vnop
50e6cc  48C08000 ctc2 zero, Status
50e6d0  4BAB42EC vsub.xyw vf11, vf08, vf11
50e6d4 *4BA8632C vsub.xyw vf12, vf12, vf08
50e6d8  4A2B4B3C vmove.w, vf11, vf09
50e6dc  4A2C533C vmove.w, vf12, vf10
50e6e0  4A0002FF vnop
50e6e4  20E70010 addi a3, a3, 0x0010
50e6e8  D8E80000 lqc2 vf08, 0x  0(a3)
50e6ec  2108FFFF addi t0, t0, 0xFFFF
50e6f0 =48428000 cfc2 v0, Status
50e6f4  304200C0 andi v0,v0, 0x00C0
50e6f8  10400004 beq v0, zero, ->$0x0050E70C
50e6fc  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
50e6ac  4BE821BC vmulax.xyzw ACC,vf04,vf08x
50e6b0  4BE828BD vmadday.xyzw ACC,vf05,vf08y
50e6b4  4BE830BE vmaddaz.xyzw ACC,vf06,vf08z
50e6b8  4BE83A0B vmaddw.xyzw vf08, vf07, vf08w
50e6bc  4BC84ADB vmulw.xyz vf11,vf09,vf08w
50e6c0  4BC8531B vmulw.xyz vf12,vf10,vf08w
50e6c4  4A0002FF vnop
50e6c8  4A0002FF vnop
50e6cc  48C08000 ctc2 zero, Status
50e6d0  4BAB42EC vsub.xyw vf11, vf08, vf11
50e6d4 *4BA8632C vsub.xyw vf12, vf12, vf08
50e6d8  4A2B4B3C vmove.w, vf11, vf09
50e6dc  4A2C533C vmove.w, vf12, vf10
50e6e0  4A0002FF vnop
50e6e4  20E70010 addi a3, a3, 0x0010
50e6e8  D8E80000 lqc2 vf08, 0x  0(a3)
50e6ec  2108FFFF addi t0, t0, 0xFFFF
50e6f0 =48428000 cfc2 v0, Status
50e6f4  304200C0 andi v0,v0, 0x00C0
50e6f8  10400004 beq v0, zero, ->$0x0050E70C
50e6fc  00000000 nop
ExecutePs2GameDisk
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
open name cdrom0:¥SYSTEM.CNF;1 flag 1 data 41278
open fd = 2
Program name = cdrom0:¥SLUS_201.30;1
# Restart.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
Frame buffer size set to  640x512 (640x512)
# Initialize Scratch Pad ...
# Restart Done.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
Get Reboot Request From EE

PlayStation 2 ======== Soft reboot

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 © Sony Computer Entertainment Inc.
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 ©SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15)
iop heap service (99/11/03)
loadelf: fname rom0TongueS2LOGO secname all
loadelf version 3.30
Input ELF format filename = rom0TongueS2LOGO
0 00200000 0001afe4 ..
1 0021b000 0000f068 ..
Loaded, rom0TongueS2LOGO
start address 0x200008
gp address 00000000
# LoadExec 'rom0TongueS2LOGO'Tongue2c=00200008
init rpc
OSDSND
loadmodule: fname rom0OhmySDSND args 0 arg
loadmodule: id 25, ret 0
_spu_rev_offsetaddr 1dfff1
### addr = 2097120  size = 32
_spu_rev_offsetaddr 1f9021
### addr = 1034255  size = 28640
(UpdateVSyncRate) Mode Changed to NTSC.
... with user configured refresh rate: 59.93 Hz
CD Init
CD Disk Ready
Frame buffer size set to  640x512 (640x512)
# Restart.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
Frame buffer size set to  640x512 (640x512)
# Initialize Scratch Pad ...
# Restart Done.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.30;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
Get Reboot Request From EE

PlayStation 2 ======== Soft reboot

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 © Sony Computer Entertainment Inc.
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 ©SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15)
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLUS_201.30;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLUS_201.30;1
0 00100000 003e5498 ...............................................................
Loaded, cdrom0:¥SLUS_201.30;1
start address 0x100008
gp address 00000000
# LoadExec 'cdrom0:¥SLUS_201.30;1'Tongue2c=00100008
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Has not been initialized yet, initializing...
[GameDB] 10837 games on record (loaded in 82.32ms)
[GameDB] Searching for 'slus-20130' in GameDB
[GameDB] Found 'slus-20130' in GameDB
[GameDB] Searching for patch with CRC '72b3802a'
[GameDB] No CRC-specific patch or default patch found
Not found Cheats file: F:\emulators\pcsx2\cheats\72B3802A.pnach
Overall 0 Cheats loaded
Overall 0 Widescreen hacks loaded
Loading patch '72B3802A.pnach' from archive 'F:\emulators\pcsx2\resources\cheats_ws.zip'
comment: Widescreen hack by nemesis2000 (pnach by paul_met)
(Wide Screen Cheats DB) Patches Loaded: 3
[GameDB] Searching for 'slus-20130' in GameDB
[GameDB] Found 'slus-20130' in GameDB
[GameDB] Searching for patch with CRC '72b3802a'
[GameDB] No CRC-specific patch or default patch found
GS Lookup CRC:72B3802A
Get Reboot Request From EE
Frame buffer size set to  1024x1024 (1024x1024)

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 © Sony Computer Entertainment Inc.
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 ©SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15)
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥SIO2MAN.IRX;1 args 0 arg
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥MTAPMAN.IRX;1 args 0 arg
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥PADMAN.IRX;1 args 0 arg
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥MCMAN.IRX;1 args 0 arg
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥MCSERV.IRX;1 args 0 arg
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥LIBSD.IRX;1 args 0 arg
loadmodule: id 30, ret 0
loadmodule: fname cdrom0:¥IOPCTRL.IRX;1  args 0 arg
loadmodule: id 31, ret 0
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2da540  8C830000 lw v1, 0x  0(a0)
2da544  3C0C0038 lui t4, 0x0038
2da548  258C0360 addiu t4,t4, 0x360
2da54c  D9840000 lqc2 vf04, 0x  0(t4)
2da550  D9850010 lqc2 vf05, 0x  10(t4)
2da554  D8A60000 lqc2 vf06, 0x  0(a1)
2da558  D8A70010 lqc2 vf07, 0x  10(a1)
2da55c  D8A80020 lqc2 vf08, 0x  20(a1)
2da560  D8A90030 lqc2 vf09, 0x  30(a1)
2da564  D8CA0000 lqc2 vf10, 0x  0(a2)
2da568  4BEA31BC vmulax.xyzw ACC,vf06,vf10x
2da56c  4BEA38BD vmadday.xyzw ACC,vf07,vf10y
2da570  4BEA40BE vmaddaz.xyzw ACC,vf08,vf10z
2da574  4BEA4B0B vmaddw.xyzw vf12, vf09, vf10w
2da578  4BEC03BC vdiv Q, vf00w, vf12w
2da57c  00094840 sll t1, t1, 0x01
2da580  D8EB0000 lqc2 vf11, 0x  0(a3)
2da584  33AC000F andi t4,sp, 0x000F
2da588  218C0010 addi t4, t4, 0x0010
2da58c  03AC6022 sub t4,sp, t4
2da590  4A0003BF vwaitq
2da594  4BC0631C vmulq.xyz vf12,vf12,Q
2da598  4B8A617D vftoi4.xy vf10, vf12
2da59c  4A6A617C vftoi0.zw vf10, vf12
2da5a0  48C08000 ctc2 zero, Status
2da5a4  4BA4602C vsub.xyw vf00, vf12, vf04
2da5a8  4BAC282C vsub.xyw vf00, vf05, vf12
2da5ac *4A20031C vmulq.w vf12,vf00,Q
2da5b0  4A0002FF vnop
2da5b4  4A0002FF vnop
2da5b8  4A0002FF vnop
2da5bc =484D8000 cfc2 t5, Status
2da5c0  00000000 nop
2da5c4  31AD0080 andi t5,t5, 0x0080
2da5c8  012D4825 or t1,t1, t5
2da5cc  4B8C5B1B vmulw.xy vf12,vf11,vf12w
2da5d0  F98C0000 sqc2 vf12, 0x  0(t4)
2da5d4  DD8D0000 ld t5, 0x  0(t4)
2da5d8  FC6D0000 sd t5, 0x  0(v1)
2da5dc  640D0002 daddiu t5,zero, 0x0002
2da5e0  FC6D0008 sd t5, 0x  8(v1)
2da5e4  8D8D000C lw t5, 0x  C(t4)
2da5e8  AC680010 sw t0, 0x  10(v1)
2da5ec  AC6D0014 sw t5, 0x  14(v1)
2da5f0  640D0001 daddiu t5,zero, 0x0001
2da5f4  FC6D0018 sd t5, 0x  18(v1)
2da5f8  00096827 nor t5,zero, t1
2da5fc  31AD0380 andi t5,t5, 0x0380
2da600  640E0005 daddiu t6,zero, 0x0005
2da604  15A00002 bne t5, zero, ->$0x002DA610
2da608  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2dac3c  8C830000 lw v1, 0x  0(a0)
2dac40  D8A60000 lqc2 vf06, 0x  0(a1)
2dac44  D8A70010 lqc2 vf07, 0x  10(a1)
2dac48  D8A80020 lqc2 vf08, 0x  20(a1)
2dac4c  D8A90030 lqc2 vf09, 0x  30(a1)
2dac50  D8CA0000 lqc2 vf10, 0x  0(a2)
2dac54  4B8A02AC vsub.xy vf10, vf00, vf10
2dac58  4BEA31BC vmulax.xyzw ACC,vf06,vf10x
2dac5c  4BEA38BD vmadday.xyzw ACC,vf07,vf10y
2dac60  4A4A40BE vmaddaz.z ACC,vf08,vf10z
2dac64  4BE04B0B vmaddw.xyzw vf12, vf09, vf00w
2dac68  4BEC03BC vdiv Q, vf00w, vf12w
2dac6c  3C0C0038 lui t4, 0x0038
2dac70  258C0360 addiu t4,t4, 0x360
2dac74  D9840000 lqc2 vf04, 0x  0(t4)
2dac78  D9850010 lqc2 vf05, 0x  10(t4)
2dac7c  4B8A02AC vsub.xy vf10, vf00, vf10
2dac80  4BEA31BC vmulax.xyzw ACC,vf06,vf10x
2dac84  4BEA38BD vmadday.xyzw ACC,vf07,vf10y
2dac88  4A4A40BE vmaddaz.z ACC,vf08,vf10z
2dac8c  0000502D daddu t2, zero, zero
2dac90  4A0003BF vwaitq
2dac94  4BC0631C vmulq.xyz vf12,vf12,Q
2dac98  4BED633C vmove.xyzw, vf13, vf12
2dac9c  4BE04B0B vmaddw.xyzw vf12, vf09, vf00w
2daca0  48C08000 ctc2 zero, Status
2daca4  4BA4682C vsub.xyw vf00, vf13, vf04
2daca8  4BAD282C vsub.xyw vf00, vf05, vf13
2dacac  4A20035C vmulq.w vf13,vf00,Q
2dacb0  4BEC03BC vdiv Q, vf00w, vf12w
2dacb4  4A0002FF vnop
2dacb8  4A0002FF vnop
2dacbc  484D8000 cfc2 t5, Status
2dacc0  00000000 nop
2dacc4  31AD0080 andi t5,t5, 0x0080
2dacc8  014D5025 or t2,t2, t5
2daccc  000A5040 sll t2, t2, 0x01
2dacd0  4A0003BF vwaitq
2dacd4  4BC0631C vmulq.xyz vf12,vf12,Q
2dacd8  48C08000 ctc2 zero, Status
2dacdc  4BA4602C vsub.xyw vf00, vf12, vf04
2dace0  4BAC282C vsub.xyw vf00, vf05, vf12
2dace4 *4A20031C vmulq.w vf12,vf00,Q
2dace8  4A0002FF vnop
2dacec  4A0002FF vnop
2dacf0  4A0002FF vnop
2dacf4 =484D8000 cfc2 t5, Status
2dacf8  00000000 nop
2dacfc  31AD0080 andi t5,t5, 0x0080
2dad00  014D5025 or t2,t2, t5
2dad04  340D0180 ori t5,zero, 0x180
2dad08  11AA001B beq t5, t2, ->$0x002DAD78
2dad0c  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2da4d0  D8A60000 lqc2 vf06, 0x  0(a1)
2da4d4  D8A70010 lqc2 vf07, 0x  10(a1)
2da4d8  D8A80020 lqc2 vf08, 0x  20(a1)
2da4dc  D8A90030 lqc2 vf09, 0x  30(a1)
2da4e0  D8CA0000 lqc2 vf10, 0x  0(a2)
2da4e4  4BEA31BC vmulax.xyzw ACC,vf06,vf10x
2da4e8  4BEA38BD vmadday.xyzw ACC,vf07,vf10y
2da4ec  4BEA40BE vmaddaz.xyzw ACC,vf08,vf10z
2da4f0  4BEA4ACB vmaddw.xyzw vf11, vf09, vf10w
2da4f4  4BEB03BC vdiv Q, vf00w, vf11w
2da4f8  4A0003BF vwaitq
2da4fc  4BC05ADC vmulq.xyz vf11,vf11,Q
2da500  4B8A597D vftoi4.xy vf10, vf11
2da504  4A6A597C vftoi0.zw vf10, vf11
2da508  48C08000 ctc2 zero, Status
2da50c  4BA4582C vsub.xyw vf00, vf11, vf04
2da510 *4BAB282C vsub.xyw vf00, vf05, vf11
2da514  F88A0000 sqc2 vf10, 0x  0(a0)
2da518  4A0002FF vnop
2da51c  4A0002FF vnop
2da520  4A0002FF vnop
2da524 =48428000 cfc2 v0, Status
2da528  00000000 nop
2da52c  30420080 andi v0,v0, 0x0080
2da530  000211C2 srl v0,v0, 0x07
2da534  03E00008 jr ->ra
2da538  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2da734  8C830000 lw v1, 0x  0(a0)
2da738  3C0C0038 lui t4, 0x0038
2da73c  258C0360 addiu t4,t4, 0x360
2da740  D9840000 lqc2 vf04, 0x  0(t4)
2da744  D9850010 lqc2 vf05, 0x  10(t4)
2da748  D8A60000 lqc2 vf06, 0x  0(a1)
2da74c  D8A70010 lqc2 vf07, 0x  10(a1)
2da750  D8A80020 lqc2 vf08, 0x  20(a1)
2da754  D8A90030 lqc2 vf09, 0x  30(a1)
2da758  D8CA0000 lqc2 vf10, 0x  0(a2)
2da75c  4BEA31BC vmulax.xyzw ACC,vf06,vf10x
2da760  4BEA38BD vmadday.xyzw ACC,vf07,vf10y
2da764  4BEA40BE vmaddaz.xyzw ACC,vf08,vf10z
2da768  4BEA4B0B vmaddw.xyzw vf12, vf09, vf10w
2da76c  4BEC03BC vdiv Q, vf00w, vf12w
2da770  00094840 sll t1, t1, 0x01
2da774  D8EB0000 lqc2 vf11, 0x  0(a3)
2da778  33AC000F andi t4,sp, 0x000F
2da77c  218C0010 addi t4, t4, 0x0010
2da780  03AC6022 sub t4,sp, t4
2da784  4A0003BF vwaitq
2da788  4BC0631C vmulq.xyz vf12,vf12,Q
2da78c  4A4B632A vmul.z vf12, vf12, vf11
2da790  4B8A617D vftoi4.xy vf10, vf12
2da794  4A6A617C vftoi0.zw vf10, vf12
2da798  48C08000 ctc2 zero, Status
2da79c  4BA4602C vsub.xyw vf00, vf12, vf04
2da7a0  4BAC282C vsub.xyw vf00, vf05, vf12
2da7a4 *4A20031C vmulq.w vf12,vf00,Q
2da7a8  4A0002FF vnop
2da7ac  4A0002FF vnop
2da7b0  4A0002FF vnop
2da7b4 =484D8000 cfc2 t5, Status
2da7b8  00000000 nop
2da7bc  31AD0080 andi t5,t5, 0x0080
2da7c0  012D4825 or t1,t1, t5
2da7c4  4B8C5B1B vmulw.xy vf12,vf11,vf12w
2da7c8  F98C0000 sqc2 vf12, 0x  0(t4)
2da7cc  DD8D0000 ld t5, 0x  0(t4)
2da7d0  FC6D0000 sd t5, 0x  0(v1)
2da7d4  640D0002 daddiu t5,zero, 0x0002
2da7d8  FC6D0008 sd t5, 0x  8(v1)
2da7dc  8D8D000C lw t5, 0x  C(t4)
2da7e0  AC680010 sw t0, 0x  10(v1)
2da7e4  AC6D0014 sw t5, 0x  14(v1)
2da7e8  640D0001 daddiu t5,zero, 0x0001
2da7ec  FC6D0018 sd t5, 0x  18(v1)
2da7f0  00096827 nor t5,zero, t1
2da7f4  31AD0380 andi t5,t5, 0x0380
2da7f8  640E0005 daddiu t6,zero, 0x0005
2da7fc  15A00002 bne t5, zero, ->$0x002DA808
2da800  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2e38b8  D8E80000 lqc2 vf08, 0x  0(a3)
2e38bc  D8C40000 lqc2 vf04, 0x  0(a2)
2e38c0  D8C50010 lqc2 vf05, 0x  10(a2)
2e38c4  D8C60020 lqc2 vf06, 0x  20(a2)
2e38c8  D8C70030 lqc2 vf07, 0x  30(a2)
2e38cc  D8890000 lqc2 vf09, 0x  0(a0)
2e38d0  D8AA0000 lqc2 vf10, 0x  0(a1)
2e38d4  D88B0000 lqc2 vf11, 0x  0(a0)
2e38d8  D8AC0000 lqc2 vf12, 0x  0(a1)
2e38dc  4BE821BC vmulax.xyzw ACC,vf04,vf08x
2e38e0  4BE828BD vmadday.xyzw ACC,vf05,vf08y
2e38e4  4BE830BE vmaddaz.xyzw ACC,vf06,vf08z
2e38e8  4BE83A0B vmaddw.xyzw vf08, vf07, vf08w
2e38ec  4BC84ADB vmulw.xyz vf11,vf09,vf08w
2e38f0  4BC8531B vmulw.xyz vf12,vf10,vf08w
2e38f4  4A0002FF vnop
2e38f8  4A0002FF vnop
2e38fc  48C08000 ctc2 zero, Status
2e3900  4BAB42EC vsub.xyw vf11, vf08, vf11
2e3904 *4BA8632C vsub.xyw vf12, vf12, vf08
2e3908  4A2B4B3C vmove.w, vf11, vf09
2e390c  4A2C533C vmove.w, vf12, vf10
2e3910  4A0002FF vnop
2e3914  20E70010 addi a3, a3, 0x0010
2e3918  D8E80000 lqc2 vf08, 0x  0(a3)
2e391c  2108FFFF addi t0, t0, 0xFFFF
2e3920 =48428000 cfc2 v0, Status
2e3924  304200C0 andi v0,v0, 0x00C0
2e3928  10400004 beq v0, zero, ->$0x002E393C
2e392c  00000000 nop
Possible old value used in COP2 code. If the game is broken, please report to ** removed URL **
2e38dc  4BE821BC vmulax.xyzw ACC,vf04,vf08x
2e38e0  4BE828BD vmadday.xyzw ACC,vf05,vf08y
2e38e4  4BE830BE vmaddaz.xyzw ACC,vf06,vf08z
2e38e8  4BE83A0B vmaddw.xyzw vf08, vf07, vf08w
2e38ec  4BC84ADB vmulw.xyz vf11,vf09,vf08w
2e38f0  4BC8531B vmulw.xyz vf12,vf10,vf08w
2e38f4  4A0002FF vnop
2e38f8  4A0002FF vnop
2e38fc  48C08000 ctc2 zero, Status
2e3900  4BAB42EC vsub.xyw vf11, vf08, vf11
2e3904 *4BA8632C vsub.xyw vf12, vf12, vf08
2e3908  4A2B4B3C vmove.w, vf11, vf09
2e390c  4A2C533C vmove.w, vf12, vf10
2e3910  4A0002FF vnop
2e3914  20E70010 addi a3, a3, 0x0010
2e3918  D8E80000 lqc2 vf08, 0x  0(a3)
2e391c  2108FFFF addi t0, t0, 0xFFFF
2e3920 =48428000 cfc2 v0, Status
2e3924  304200C0 andi v0,v0, 0x00C0
2e3928  10400004 beq v0, zero, ->$0x002E393C
2e392c  00000000 nop
Vertex Trace: float overflow detected ! min 3.402823e+38 max 3.402823e+38
Snapshot taken
Snapshot taken
Snapshot taken
Snapshot taken
Snapshot taken

**Comment by Mrlinkwii** [comment]
how is this on latest nightly ?

**Comment by Goatman13** [comment]
Its part of meta https://github.com/PCSX2/pcsx2/issues/5137 , so nothing changed.  Patches are available on forum as a workaround. 

Btw. This affect many more effects than D Dark bomb. Mostly in "EX" special moves.

**Comment by Mrlinkwii** [comment]
Thanks for the update :)
