### ISSUE TITLE
[Feature Request]: Reading game files from folder

### ISSUE THREAD

**Issue by Leafdomain** [PCSX2/pcsx2#5799]
### Description

It would be nice if the emulator could read the extracted files of a game from a folder instead of a rom, i.e., run the game from a folder instead of a iso.

### Reason

The reason for this would be easy modding, being able to access and switch files fast etc.

### Examples

I know the iso has the files in a certain order and it needs to be like that in order to be read by the emulator. But maybe there can be a way to generate a file list or something for the emulator to read.

For the Gamecube, the files also need to be like that, but yet Dolphin can read game files from a folder and run the game.

So I would hope that maybe PCSX2 can do it as well.

**Comment by F0bes** [comment]
I don't think there is a good solution to LBA, and I'm against ignoring games that do use LBA.
Apache3 has worked fine for me when I've used it.

**Comment by lightningterror** [comment]
Closing, niche/low priority, the user can re create the iso again.
