### ISSUE TITLE
[BUG]: PCSX2 Qt Game Covers get errors when trying to select manually

### ISSUE THREAD

**Issue by MuskettDev** [PCSX2/pcsx2#5815]
### Describe the Bug

![Screenshot (2)](https://user-images.githubusercontent.com/63559796/161447513-cd22aae3-7ef7-432d-95a4-b56be6b610c0.png)

![Screenshot (3)](https://user-images.githubusercontent.com/63559796/161447933-7aba5e69-1515-4b47-8216-0f8ff2a4f3f8.png)

The screenshot is of a recent pcsx2 qt build whereas some games such as Shin Megami Tensei: Persona 3 FES or Jak and Daxter: The Precursor Legacy have trouble setting cover images manually.

### Reproduction Steps

I was placing the cover art images on a recent pcsx2 self-compiled build on my Windows 10, AMD Ryzen 5 5600H, Nvidia Geforce RTX 3050ti system; It worked for previous games but multiple attempts for these two games proved wrong.

I then tried placing the cover images in use into the "covers" folder in the pcsx2 directory. It worked for Persona 3 FES but not for Jak and Daxter.

### Expected Behavior

I expected the games to get the cover art.

### PCSX2 Revision

v1.7.2559 (Qt)

### Operating System

Windows 10 (64bit)

**Comment by MrCK1** [comment]
Sorry, bug reports for Qt are not being accepted at this time.

**Comment by refractionpcsx2** [comment]
You need to update. colons are not allowed in game names, as they are used for the file structure and windows doesn't let you use colon, but we recently replaced them all in the gamedb with hyphens.

**Comment by MuskettDev** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/63559796/161448093-74cd384d-4b3a-4914-94e2-9ffc30061c3e.png)

Thanks bro! So it did act like that, I needed to remove the hyphen from the game's name since it was being translated as a colon into PCSX2 and it worked. 

> You need to update. colons are not allowed in game names, as they are used for the file structure and windows doesn't let you use colon, but we recently replaced them all in the gamedb with hyphens.
> 
> So update, maybe rescan.
