### ISSUE TITLE
[BUG]: Crash accessing memory cards

### ISSUE THREAD

**Issue by OdinVex** [PCSX2/pcsx2#5818]
### Describe the Bug

I hadn't pulled the source from pcsx2 for a few weeks, but somewhere between this month and last month something has broken memory cards (folders). I get a crash, log below:

```
McdSlot 0 [File]: [is not memcard file]
McdSlot 1 [File]: /.../PCSX2/memcards/Mcd002.ps2
McdSlot 0: [Folder] /.../PCSX2/memcards/Mcd001.ps2
(FolderMcd) Indexing slot 0 without filter.
free(): double free detected in tcache 2
```

### Reproduction Steps

Memory Card folder, inserted into first controller, try to play a game.

### PCSX2 Revision

v1.7.2560

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Mint Cinnamon

**Comment by OdinVex** [comment]
I checked the last 30 days of commits, there are some definite memory-card code changes happening. Whether it's cleanup or anything else, I don't know, I haven't had time to delve into it.

**Comment by OdinVex** [comment]
Okay, it seems any kind of folder-based memory card functionality will cause a crash. Unable to convert, crashes if attempted.

**Comment by RedPanda4552** [comment]
Can you upload your folder memcard as a zip? I will try to inspect it tomorrow. In the meantime, something to experiment with is move one serial at a time out of the folder memcard (temporarily store them in some other location) and see if at any point removing one serial fixes the card. If so, please point out which serial it is. Likely case just by guessing, one of your saves was created during a short time where a big in folder memcards would generate a busted _pcsx2_index file.

**Comment by OdinVex** [comment]
> Can you upload your folder memcard as a zip? I will try to inspect it tomorrow. In the meantime, something to experiment with is move one serial at a time out of the folder memcard (temporarily store them in some other location) and see if at any point removing one serial fixes the card. If so, please point out which serial it is. Likely case just by guessing, one of your saves was created during a short time where a bug in folder memcards would generate a busted _pcsx2_index file.

@RedPanda4552, It happens even with _brand-new folder-based memory-cards_ for me. I already tried the typical debug stuff, including debug-prints. I mentioned it above. The values being handed off to `rapidyaml` are alright, `rapidyaml` just needs to crap on return. I didn't bother delving deeper into `rapidyaml` function `parse_in_arena`.

**Comment by RedPanda4552** [comment]
This is definitely a problem with the index files then. Can you upload your folder memcard with all data inside so I can inspect it? A zip archive should do.

**Comment by OdinVex** [comment]
> This is definitely a problem with the index files then. Can you upload your folder memcard with all data inside so I can inspect it? A zip archive should do.

I'll try to explain again. Create a brand new, non-formatted folder-based memory-card and insert into a player slot. Boot a game, let it format the card. Crash. An index gets created during that format, but is empty. There's nothing to upload.

**Comment by RedPanda4552** [comment]
Odd question, does the path leading to the memcard contain any non-ASCII text? Any UTF-8 or UTF-16 in there?

**Comment by OdinVex** [comment]
> I can create, format, and save a game on the latest nightly, which is why I was asking for the memcard you originally noticed the issue on. Thanks for uploading, I'll have a look.

Linux? I do a whole git clone with submodules too, all updated to the latest of their branches.

**Comment by OdinVex** [comment]
I downgraded `rapidyaml` to `v0.4.0` and reverted `MemoryCardFolder.cpp` to version from commit cae8e6ae79f78e4fd1377f6682fbda6b0a3f8673, then patched `GameDatabase.cpp` to use `parse` instead of `parse_in_arena`, essentially reverting and it works fine now.

**Comment by RedPanda4552** [comment]
Funny enough, the most recent modifications to MemoryCardFolder.cpp were intended to repair index files which were broken by an older PCSX2 version. I don't think reverting the library is gonna fly, but if your patch still works on the latest library, it might be acceptable. If you'd like, you could PR it and a few others could review.

**Comment by Mrlinkwii** [comment]
@OdinVex  can you try https://github.com/PCSX2/pcsx2/pull/5751?

**Comment by OdinVex** [comment]
My second post here already explained that didn't fix it.

**Comment by OdinVex** [comment]
I found it. The line `std::fclose(file.get());`. Edit: A quick look at the Filesystem API shows it's managed, may not need cleaning up, such as seen in `GameList.cpp`. The line isn't necessary, I believe.

**Comment by OdinVex** [comment]
Adding more info:

The routine calls `OpenManagedCFile`, which consists of:
```
FileSystem::ManagedCFilePtr FileSystem::OpenManagedCFile(const char* filename, const char* mode)
{
	return ManagedCFilePtr(OpenCFile(filename, mode), [](std::FILE* fp) { std::fclose(fp); });
}
```

Notice that it frees up things at the end already. The call to `std::close` is redundant and erroneous.

**Comment by OdinVex** [comment]
Adding more info:

The routine calls `OpenManagedCFile`, which consists of:
```
FileSystem::ManagedCFilePtr FileSystem::OpenManagedCFile(const char* filename, const char* mode)
{
	return ManagedCFilePtr(OpenCFile(filename, mode), [](std::FILE* fp) { std::fclose(fp); });
}
```

Notice that it frees up things at the end already. The call to `std::fclose` is redundant and erroneous.

**Comment by OdinVex** [comment]
I've created `Pull Request` #5826 to fix this issue.
