### ISSUE TITLE
[BUG]: God of War. Missing sunflare issue.

### ISSUE THREAD

**Issue by 5d-0** [PCSX2/pcsx2#5824]
### Describe the Bug

Sunflare effect is missing in HW mode no matter what api is being used. 

### Reproduction Steps

Just get to this place in the game.

### Expected Behavior

You can get correct behaviour via SW mode. 

### PCSX2 Revision

v1.7.2559

### Operating System

Windows 10 (64bit)

### CPU

i5-4570

### GPU

GTX 1080 Ti

### GS Settings

![bandicam 2022-04-05 04-36-22-561](https://user-images.githubusercontent.com/60811674/161662205-88f8a99e-352a-4861-bc2b-81ec4f06dee1.png)
![bandicam 2022-04-05 04-36-25-236](https://user-images.githubusercontent.com/60811674/161662213-a7a3c9b4-6355-48f6-b42f-295d6264bc6d.png)

### Emulation Settings

MTVU is on but has no affect on the bug. Been checked with MTVU - off.

### GS Window Screenshots

Hardware (Any): 
![bandicam 2022-04-04 13-17-41-333](https://user-images.githubusercontent.com/60811674/161662574-a6781535-99db-48fe-b8a0-05bee8ca436a.png)
Software: 
![bandicam 2022-04-04 13-17-19-001](https://user-images.githubusercontent.com/60811674/161662595-2c9a3d97-786a-4861-af38-8d5f87b35ff9.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8416013/snaps.zip)

**Comment by prafullpcsx2** [comment]
You need to post the gsdump

**Comment by 5d-0** [comment]
> You need to post the gsdump

Done.

**Comment by prafullpcsx2** [comment]
Enable autoflush and it works fine.
