### ISSUE TITLE
[BUG]: PCSX2 doesn't enter full screen after resume

### ISSUE THREAD

**Issue by robxnano** [PCSX2/pcsx2#5833]
### Describe the Bug

In older versions, PCSX2 would resume in full screen mode if it was paused while in full screen. Now it always resumes in windowed mode regardless of the previous mode, and also regardless of the 'Start in full screen mode' setting. Bisection reveals that this behaviour started with [v1.7.2187](https://github.com/PCSX2/pcsx2/commits/v1.7.2187), and is still present in the latest build.

### Reproduction Steps

1. Go to General Settings -> GS Window and check 'Start in full screen mode by default'.
2. Boot a game (it will enter full screen mode).
3. Press Esc to pause. 
4. Press Esc again and the game will resume in windowed mode.

### Expected Behavior

The game should resume in full screen mode.

### PCSX2 Revision

v1.7.2574

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
Duplicate issue: https://github.com/PCSX2/pcsx2/issues/1734

**Comment by robxnano** [comment]
This is a different bug to the one you mentioned. That's about the game window closing on pause and automatically going back to full screen on resume. This is about it not going back to full screen at all. It's also a regression from v1.7.2186.

**Comment by RedDevilus** [comment]
So it's different to:
- Boot in Windowed
- Alt+Enter or other method to go fullscreen
- Pause
- Resume 
- Boots in Windowed 

?

**Comment by tellowkrinkle** [comment]
If you read the original post, that was originally about a different problem.  Only your post at the end is describing the new problem.  I'd prefer keeping it separate, instead of throwing it on the bottom of a separate issue.  Especially if this was bisected to be introduced in January (not 2017)
