### ISSUE TITLE
[BUG]: Taiko no tatsujin: doka! to oomari nanadaime - lines on screen + double image

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#5835]
### Describe the Bug

lines come across in one screen in the opening that i can't get rid of with hardware upscales.. also there is a weird double image like one layer is the color and the other is a sort of stencil. 
![gs_20220406140908_Taiko no Tatsujin Bang Tap_ Toomori 7 Daimei _NTSC-J__SLPS-20486](https://user-images.githubusercontent.com/8851653/162052368-53a86ff2-0395-441f-8d78-e6632aaef1f1.png)

### Reproduction Steps

get to the christmas themed screens in the opening that isn't an fmv. while vertical lines are present through the whole game those ones are easily fixed with align sprite. i can't find any upscale hack that fixes this.

### Expected Behavior

![gs_20220406141045_Taiko no Tatsujin Bang Tap_ Toomori 7 Daimei _NTSC-J__SLPS-20486](https://user-images.githubusercontent.com/8851653/162052279-bf9d19b7-8684-473d-90f9-a8fd0b08632a.png)

### PCSX2 Revision

1.7.2575

### Operating System

Windows 11

### CPU

i5-9600

### GPU

gtx 960

### GS Settings

hw renderer. 3x

### Logs & Dumps

[gs_20220406140908_Taiko no Tatsujin Bang Tap_ Toomori 7 Daimei _NTSC-J__SLPS-20486.gs.zip](https://github.com/PCSX2/pcsx2/files/8429901/gs_20220406140908_Taiko.no.Tatsujin.Bang.Tap_.Toomori.7.Daimei._NTSC-J__SLPS-20486.gs.zip)

**Comment by refractionpcsx2** [comment]
Unfortunately it just looks like one of those games that doesn't upscale easily or well. Only solution might be to patch out the blur, which I'm not putting in the gamedb since it affects sw mode too.

I'll leave this open if anybody else has a good idea, but rn it's a "Won't fix"
