### ISSUE TITLE
Pause=>Resume=>colored screen\missing textures(GSDX)

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#584]
Since this change https://github.com/PCSX2/pcsx2/commit/6c8f7a01477375de00fda8a6f76ad7300af488d8 when I pause the emulation(close the game window)and then resume the game,I'll get either colored screen covering the while screen or textures(mainly text...I think it's only text)will be missing.

Tested games Atelier Iris 3 and Ar Tonelico 2.
Switching settings,renderer or sw\hw mode don't fix the problem
i7 4771,GTX750TI,16gb ram on Win7 ultimate sp1 x64
![2015-06-05_212618](https://cloud.githubusercontent.com/assets/5032540/8012392/d125861c-0bc9-11e5-90d7-0d10d95647a5.jpg)
![2015-06-05_212902](https://cloud.githubusercontent.com/assets/5032540/8012426/13c50bb4-0bca-11e5-8392-6b74277b4613.jpg)
![2015-06-05_212918](https://cloud.githubusercontent.com/assets/5032540/8012427/13c64c54-0bca-11e5-8646-59ff7d82f0cc.jpg)

**Comment by gregory38** [comment]
Ah. It was too nice...

**Comment by gregory38** [comment]
I revert the change. I will do somethings better in a short future.

**Comment by gregory38** [comment]
Is it legal to change gsdx option during the pause?

**Comment by gregory38** [comment]
Could you test lates GIT?

**Comment by vsub** [comment]
The problem I mention is fixed but I think the main problem(loading the settings)is not.
Aterlier Iris 3 in the menus(triangle)

1.Start the game with OpenGL(or any other renderer...I don't know if it's just me but I think OGL is starting to work faster than DX :) )HW already selected and with native resolution
2.Switch to 6x scaling and the gpu and vram usage goes up
3.Press F9 to switch to software mode(the gpu\vram usage goes down)
4.Switch to any hardware renderer(I didn't close the game window)
5.It will continie to act as if software mode is selected(the gpu\vram usage is the same)
6.Press F9 to supposedly switch to software renderer...and the result is higher gpu\vram usage and no texture filtering is applied(the characters models don't look as smooth as even native resolution)

After all that I have no idea how to revert it to work the correct way

**Comment by bositman** [comment]
So you're saying after switching to software via F9, if you change renderer in the GUI it doesn't take effect?

**Comment by refractionpcsx2** [comment]
Sounds like the texture cache isn't initialising again so it leaves the render  size at native not software though (it sounds)

**Comment by gregory38** [comment]
Or f9 miss a set config call

**Comment by gregory38** [comment]
Actually I think there are 2 bugs.
1/ we don't set the render variable so the gui is lost
```
			theApp.SetConfig("renderer", renderer);
```
2/ Then either the print is wrong or the toggling doesn't always work
```
(gsFrame) Invoking command: Sys_RenderswitchToggle
Suspending single plugin: GS
	Saving GS
	Closing GS
Recovering single plugin: GS
	Opening GS
		Toggling GSdx Hardware/Software renderer
	Loading GS
(gsFrame) Invoking command: Sys_RenderswitchToggle
Suspending single plugin: GS
	Saving GS
	Closing GS
Recovering single plugin: GS
	Opening GS
	Loading GS
```

**Comment by gregory38** [comment]
Tell me if #588 is better.

**Comment by vsub** [comment]
If I understand this change correctly,GSdx is supposed to write in GSdx.ini in Renderer= when you hit F9.
If that's what it supposed to do then does,then no,it's not working.
1.Notepad++ doesn't detect that the file is updated(because it's not)when you press F9
2.Pressing F9 does not make GSdx to auto select the current renderer from the Renderer drop down menu.

Here is an idea
1.Pressing F9 will set a variable telling which renderer is selected

0 - DX9 HW
1 - DX9 SW
2 - DX9 Null
3 - DX11 HW
4 - DX11 SW
5 - DX11 Null
10 - Null SW
16 - Null OCL
11 - Null Null
12 - OGL HW
13 - OGL SW
14 - DX9 OCL
15 - DX11 OCL
17 - OGL OCL

This is what GSdx writes to the "Renderer=" when you select it from the drop down menu and hit ok

2.When you open the settings,GSdx will load the settings from the ini but only set the renderer from the variable,not from what the  "Renderer=" say(that way the the renderer selected will be temporary)

3.Changing settings from the GSdx settings window will write to the ini and update the variable telling which mode is selected.

Currently it's like I said above in my previous post:
1.F9=>SW
2.GSdx settings says some HW mode
3.Choosing any other hw renderer either changes to that renderer but in sw mode or it does nothing(I can't be sure about the second one but it's definitely still on sw mode)
Or choosing any sw mode(gsdx settings stays hw while sw is actually active(from F9)),will make GSDX to work in hw mode

And about what I said above about the texture filtering,I was probably wrong...the higher the scaling mode(Atelier Iris 3 characters)the more the characters will look like no texture filtering is enabled.It's set to half enabled but if it's checked(force on),they will look fine but then other things start to appear.

**Comment by gregory38** [comment]
Hum, on linux the file is updated but it isn't important. Someone gives me the solution for the issue number2 which is I think the main issue (sometime the renderer didn't really toggle)
