### ISSUE TITLE
Notify the user when recording is not started due to it being disabled

### ISSUE THREAD

**Issue by NetSysFire** [PCSX2/pcsx2#5840]
### Describe the Bug

Trying to capture a video of the emulation does nothing. The window which would ask me where to save the file to and other parameters does not appear and there is no OSD message. The only thing that happens are some log messages which only appear tangentially related.

### Reproduction Steps

1. Start any game.
2. Either press F12 or go into the main window and click *Capture* > *Video*, it does not matter which one you use here because the result is the same.
3. Nothing happens.

Every time I try to record I do get the following addition to the log, regardless if I just started up the game or idled hours in it:

```
(gsFrame) Invoking command: Sys_RecordingToggle
[GameDB] Searching for 'slus-21452' in GameDB
[GameDB] Found 'slus-21452' in GameDB
[GameDB] Searching for patch with CRC 'cc96ce93'
[GameDB] No CRC-specific patch or default patch found
(GameDB) Enabled Gamefix: VuAddSub
[GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=1]
[GameDB] Enabled GS Hardware Fix: roundSprite to [mode=1]
```

The window title of the emulator window in which the game is running does not change. Usually a "Recording..." would be appended but this is not happening. There is also nothing in the stdout/stderr.

Since I never tried recording before I can not say if this is a regression or not. I also tried with an empty `~/.config/PCSX2` but this changed nothing, so I assume it is not a misconfiguration since these are the default configs. It also does not matter if I am in software mode or not.
Unchecking the "Include audio" option does not change this behavior either.

For reference: this is ffmpeg 5.0 if this is relevant. Nothing gets added to the `snaps` directory either. Capturing a simple screenshot via the menu works perfectly.

### Expected Behavior

A window would open and ask me where to save the file to. After that, the recording starts.

### PCSX2 Revision

v1.7.2581 (As of writing I literally just freshly compiled the new version)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by Mrlinkwii** [comment]
>Nothing gets added to the snaps directory either. Capturing a simple screenshot via the menu works perfectly.

by default it gose to /tmp/ if no directory is selected in the graphics settings   also did you enable it in graphics settings ?

**Comment by NetSysFire** [comment]
No, recording was not enabled. After enabling and configuring it to my liking it worked. There should be a OSD message or some other hint when you try to record but it is not enabled, especially when doing that from the main window itself.

**Comment by NetSysFire** [comment]
I had a short discussion on IRC about this UX fail. I can imagine the main reason for it being need to be explicitely enabled is so the user does not accidentally hit F12 and ends up with both a huge file and severely degraded performance in some cases. Here are some suggestions on how to resolve this issue so I am not only whining but also contributing in the form of constructive criticism:

- Repurpose the "enable recording" checkbox into "Enable F12 recording hotkey" so you can still manually record via *Capture* > *Video* from the main window. This is what really confused me.
- When trying to record but the user has never touched the recording options before, ask the user if they want to configure it now and if so open the settings for it. This will probably require another option in the config and is the most complex suggestion out of these four.
- Add an OSD notification when recording starts and stops so even if you do accidentally hit F12 you know what just happened.
- Add a "manual" and "automatic" setting to the recorded resolution. Automatic means it will use the effective resolution if you use a higher than native one via the HW renderer and manual means it is exactly what you configure so it does not matter if you use 8x native resolution or the default one.

This *might* be a good first issue. This is something for the maintainers to decide but to me it looks simple enough on the first glance.
