### ISSUE TITLE
[Feature Request]: Hotkeys to toggle loading and dumping textures/ only dumping non-loaded textures

### ISSUE THREAD

**Issue by kaunch** [PCSX2/pcsx2#5843]
### Description

i make texture packs. (remasters etc.)
if you could make it so that when dumping it doesn't dump already loaded textures. im tryin to dump things other than things ive already changed/replaced?  its already moved into the replacement folder
or else its too hard to look through. for example, lots of dumped textures may look the exact same so i go to dump again and it gets kinda annoying for it to dump the same textures ive already changed if im onto another area

### Reason

It make things easier for me by speeding up the process of dumping and reloading textures. Makes it simpler instead of every time going to Config>Graphic Settings>Advanced toggle it and click apply it'd be easier to just press a key. 

### Examples

dolphin has hotkeys X to toggle dump and C to toggle load.
![Screen Shot 2022-04-10 at 6 33 25 PM](https://user-images.githubusercontent.com/103395553/162650691-033ccc2e-9397-4c8e-8f74-79a89d48acd4.png)

**Comment by RedDevilus** [comment]
Should be fixed by https://github.com/PCSX2/pcsx2/pull/6060

But GitHub has an issue and not producing the build as of this moment. So best be patient when it arrives.
