### ISSUE TITLE
[Feature Request] Features To Improve PCSX2

### ISSUE THREAD

**Issue by F0bes** [PCSX2/pcsx2#5866]
Moved to an issue instead of a discussion.

<div type='discussions-op-text'>

<sup>Originally posted by **danteblackmetal** April 13, 2022</sup>
I'd like to suggest a couple features that could help improving emulation itself, so:

A way to change color channels individually on shaders, like, increasing/decreasing Red, Green and Blue;
A way to pause the emulator (ESC should pause but it closes instead of pausing, so, I guess another key for pausing)
A way to cycle through the rendered textures in real time and save it with a slightly different name, like a letter or a word in the name of the texture, and then the actual name, which would make defining some of them easily (it's not very obvious to spot what texture represent what in the actual game).</div>

**Comment by grimpunch** [comment]
Just FYI, Spacebar pauses emulation by default in Qt build at least

**Comment by Mrlinkwii** [comment]
also in QT OSD section you can do shader boost

**Comment by F0bes** [comment]
Closing due to the following:
- We do have shade boost. But not for certain colour channels. I'm confident that this can be done through third party applications.
- Space pauses the emulator
- Stopping every texture draw so you can name it is not really reasonable. Nor do we get enough information at that point in emulation to give you easy to digest names.
