### ISSUE TITLE
[BUG]: Black Eyes glitch is back in Jak and Daxter The Precursor Legacy

### ISSUE THREAD

**Issue by 3D8bitGamer** [PCSX2/pcsx2#5869]
### Describe the Bug

Jak and Daxter has lost their eyes again after two years in the latest version of pcsx2-v1.7.2589-windows-64bit-AVX2. Water effects in far background is also completely broken this time. There is just a layer of dark black colour but not water. For support I am enclosing a snap.

### Reproduction Steps

![gs_20220414232846_Jak and Daxter - The Precursor Legacy _NTSC-U__SCUS-97124](https://user-images.githubusercontent.com/103628597/163526539-ab86e81b-3a72-4129-9407-caed4128bfc2.png)

### PCSX2 Revision

v1.7.2589

### Operating System

Windows 10 (64bit)

### CPU

i9 8950HK

### GPU

GTX 1060 6B VRAM

**Comment by refractionpcsx2** [comment]
You've enabled manual GS fixes, which overrides the gamedb setting. You shouldn't need to enable manual fixes with Jak as all the upscaling is handled in the GameDB now, turn that off and let the automatic fixes handle it and it shouldn't be a problem.

**Comment by 3D8bitGamer** [comment]
Thank you, that fixed the issue. Sorry for late reply.
