### ISSUE TITLE
[BUG]: pcsx2-v1.7.2605 Graphics Settings and Direct3D12 need fix

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5878]
### Describe the Bug

Describe the Bug
Several damages were found.
IN Graphics Settings 
1. Change renderer while playing games is error
![screenshot 4](https://user-images.githubusercontent.com/48321898/163591936-aea45740-db4b-4bee-b67b-4a0f94c3a7e1.jpg)
2. Change adapter  while playing games is error
![ScreenRecorderProject3](https://user-images.githubusercontent.com/48321898/163592026-4b385ffe-8a92-4de3-a894-a31d22f64c6f.gif)
![screenshot 4](https://user-images.githubusercontent.com/48321898/163592050-ed49acc6-a082-466a-971e-3529172b9a82.jpg)
3. Direct3D12 afer change the resolution size while playing games is error
![ScreenRecorderProject1](https://user-images.githubusercontent.com/48321898/163592560-21a621fb-000b-400f-ad77-e6187533d893.gif)
![screenshot 1](https://user-images.githubusercontent.com/48321898/163592176-c464643b-0482-46d9-b42c-75179718c253.jpg)
4. Direct3D12 not read External Shader (is no benefit to use Direct3D)
![screenshot 6](https://user-images.githubusercontent.com/48321898/163593000-a8319c86-6667-4625-bbb2-46f7f031264a.jpg)

### Reproduction Steps

pcsx2-v1.7.2604 All Renderer work fine

### PCSX2 Revision

v1.7.2605

### Operating System

Windows 11

**Comment by tee4341** [comment]
pcsx2-v1.7.2606-It's still damaged. unchanged
![screenshot 1](https://user-images.githubusercontent.com/48321898/163596365-3864a36c-5f1d-43c2-8bf6-d67a65872ead.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/163596375-dcde9e33-a79b-4571-a07f-e884067cb4b6.jpg)
![screenshot 3](https://user-images.githubusercontent.com/48321898/163596388-084a21d4-1674-485d-94ef-0aa30afc0678.jpg)

**Comment by stenzek** [comment]
Already fixed with https://github.com/PCSX2/pcsx2/pull/5874

**Comment by refractionpcsx2** [comment]
Merged
