### ISSUE TITLE
[Feature Request]: Separate auto HW hacks from manual ones

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#5885]
### Description

At least from what I know of, there are some hacks that aren't automatically managed by the "Auto HW hacks", like Texture Offset and Skipdraw Range, and there are also some hacks that in my opinion don't belong there too, like Trilinear Filtering which is more of an enhancement kinda thing, can we have those options separate from the HW hacks so you can have the auto hacks + these optional ones? so you dont lose the ability of having auto hacks on when wanting to mess with those options.

### Reason

It will make my experience better by having the nicety of auto hacks while also tinkering with the ones that are not touched by the auto hack process.

### Examples

Most other emulators

**Comment by stenzek** [comment]
IMO, this can be closed, as it's a WONTFIX for Wx, and already done in Qt.

Trilinear is already separate, and as for the others, you can just use per-game settings to override the hw fixes flag for the one game which needs skipdraw.
