### ISSUE TITLE
[BUG]: KOF Orochi Collection & KOF NESTS - Japanese versions - Broken FMV when using HW

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#5899]
### Describe the Bug

The FMV have black frames when upscaled. It is solved when SoftwareRendererFMVHack is enabled, this thus can be added to GameDB.

Here are all the versions that are affected :

SLPS-25535: NeoGeo Online Collection Vol.3 - The King of Fighters - Orochi Collection [Special Pack]
SLPS-25605: NeoGeo Online Collection Vol.3 - The King of Fighters - Orochi Collection
SLPS-25661: King of Fighters, The - Nests
SLPS-25791: King of Fighters, The - Orochi Collection [NeoGeo Online Collection the Best]
SLPS-25865: King of Fighters, The - Nests [SNK the Best]

### Reproduction Steps

Render with Vulkan/DX11/DX12 even with native.

### Expected Behavior

Correct FMV

### PCSX2 Revision

53bb0c5

### Operating System

Windows 11

### CPU

5600x

### GPU

6800

### GS Settings

Hardware renderer - DX/Vulkan

**Comment by Mrlinkwii** [comment]
id assume if fine at native?

**Comment by Immersion95** [comment]
> id assume if fine at native?

Yes even in native.

I corrected the issue as I wrongly put Last Blade instead of KOF NESTS.
