### ISSUE TITLE
[BUG]: PCSX2 Nightly isn't working as of version 1.7.2622.

### ISSUE THREAD

**Issue by Flannels** [PCSX2/pcsx2#5924]
### Describe the Bug

PCSX2 Nightly 1.7.2622, the version of PCSX2 currently available on Steam Deck's Discover store, seems to be broken or bugged. Upon attempting to load a game, the whole program just... crashes. Which is kind of a problem for people who feel an intense need to play as some anime kid smacking dark monsters with an oversized key alongside a cartoon duck and a cartoon dog whose voice sounds like a backed up sink.

I'm one of those people.

### Reproduction Steps

1. Try to load a game
2. Reality sets in

### Expected Behavior

1. PCSX2 crashes
2. Internal screaming
3. External screaming

### PCSX2 Revision

PCSX2 Nightly v1.7.2622

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

I don't know what that means, so... Arch

**Comment by seta-san** [comment]
Are you looking chuthulu in the eyes? Your issue makes it sound like you are having existential dread. 😂

**Comment by Flannels** [comment]
> Are you looking chuthulu in the eyes? Your issue makes it sound like you are having existential dread. joy

Nah, I added that serious sounding stuff as hyperbole for comedic effect lol.
In all seriousness though, PCSX2 Nightly v1.7.2622 on Steam Deck actually is crashing every time I attempt to boot up a game, and I'm far from the only one having this issue. If this could be looked into and potentially fixed, that would be highly appreciated. Thanks!

**Comment by F0bes** [comment]
I'm told https://github.com/PCSX2/pcsx2/pull/5908 should fix the issue.

**Comment by Flannels** [comment]
> I'm told #5908 should fix the issue.

I don't know what any of this means. Could you walk me through all of this, please? (I'm sorry, Linux is still pretty new to me)

**Comment by F0bes** [comment]
To keep it short, there is a fix waiting to be merged into our codebase.
If you want to test it now you can download the appimage here:
https://github.com/PCSX2/pcsx2/suites/6157016399/artifacts/215365316
Otherwise you'll have to wait until it's merged.

**Comment by SamRH** [comment]
Duplicate of https://github.com/PCSX2/pcsx2/issues/5904 - issue already fixed just the Flatpak/Steam Discover PCSX2 version needs to be updated (this is not maintained by PCSX2). PR 5908 is only relevant if using the AppImage rather than the version available via FlatHub / steam deck discover.

**Comment by Flannels** [comment]
So... i-is the PCSX2 update for Steam Deck on the way? I feel like I missed something here

**Comment by F0bes** [comment]
You have to wait for the build provided on the steam deck to update. If you want to play around with an app image _right now_ you have to use the link I've sent you.

**Comment by RedDevilus** [comment]
The version on the steam deck is not handled by us, it seems to only update weekly for all the changes.

**Comment by Flannels** [comment]
Oh. Well, thanks!

**Comment by Flannels** [comment]
Is there any way I can add that version of PCSX2 you gave me to my steam deck desktop so I don't have to reinstall it every time I want to play?

**Comment by kenshen112** [comment]
You could try the AUR package and see if that helps. My understanding is that you can unlock the filesystem and install packages right?

**Comment by RedDevilus** [comment]
Or wait till it updates on steam itself.

**Comment by Flannels** [comment]
Does it update on any sort of regular basis or is it just random?

**Comment by RedDevilus** [comment]
I already told you it is handled unofficialy by 3rdparty maintainer and updates every week.

**Comment by Flannels** [comment]
I forgot about that, my bad

**Comment by Harenabs21** [comment]
Hello everyone, can you help me guys to figure out what's wrong with my app, I just installed PCSX2 in my pc for windows 10 because that's my OS, and this is the latest version v1.7.5095. Well, my problem is that when I want to run a game or do something in settings it just stop running and instantly, there are 2 crash files who appear in the main file of PCSX2, I notice that I already have download the bios, so what should I do?

**Comment by refractionpcsx2** [comment]
The github is not for support, if you want help, please use the forum or our discord. 

Also we don't support piracy. (Downloading the BIOS is illegal)

**Comment by F0bes** [comment]
We don't support downloading firmware (bios) or games as that is considered piracy.

**Comment by cappy0274** [comment]
im installing pcsx2 stable version but theres a bug is turning into nightly built
