### ISSUE TITLE
[Feature Request]: Change deadzone in DualSense controls.

### ISSUE THREAD

**Issue by SoloBackup** [PCSX2/pcsx2#5926]
### Description

Hello good afternoon!
I use DualSense on Enhanced Mode on PCSX2 QT Windows 11 (I always use the latest builds and this problem has occurred in all). I'm having problems with the analog stick, when i try to change direction in most 3D games, it feels like the sensitivity is too high, and the character move slowly when i abruptly or normally change direction on analog. I would like to report this, and if it is possible that in the future they will change and increase the dead zone of the analog, because in the way it is, it is very difficult to change direction, which hinders the gameplay.

Here's a video of how it's going:
https://user-images.githubusercontent.com/84431888/164300445-7358902e-8293-4ae7-b43e-05e04b9aaad1.mp4

And the behavior that was expected:
https://user-images.githubusercontent.com/84431888/164300691-20c6bb7d-ddbc-40d9-bc57-a7c8c8ee44e2.mp4

### Reason

This would make the gameplay better, and it would be possible in games to pass levels that require agility.

### Examples

One idea would be the adjustment of the dead zone by the user as it exists in other projects.

**Comment by stenzek** [comment]
I'm not sure if a deadzone is the best idea, but there is an axis scale already (it's just not hooked up in the UI yet). `[PadN]` and `AxisScale`.

**Comment by SoloBackup** [comment]
Thanks for the reply and for the support. I will wait for this implementation.
