### ISSUE TITLE
[BUG]: C++ Runtime Error on Time Crisis 3, Stage 3-3 (Chinese version)

### ISSUE THREAD

**Issue by Gomam0n-afk** [PCSX2/pcsx2#5929]
### Describe the Bug

Complete crash of the emulator in Stage 3 - 3 of Time Crisis 3 (Note: Chinese version of the game was used, but i don't think an ISO/weird hack issue could end up in a total C++ Redistributable error ,as i've never seen it happen due to a bad ROM.

Name: Time Crisis 3 (Chinese).ISO
Size: 1626800128 bytes (1551 MiB)
SHA1: 6e8324c8789f9a80ef6dd18298f899e6001c127f

ISO seems to be based off the Japanese version of the game (since there's subtitles, and english voices.
![pcsx2x64-avx2_x2i6tiAKQD](https://user-images.githubusercontent.com/59240947/164455590-2e61ead0-d224-4ad9-80a8-08f91013e11b.png)

### Reproduction Steps

Play the game until that point.

### PCSX2 Revision

v1.7.2643

### Operating System

Windows 10 (64bit)

### CPU

i7-7700

### GPU

GTX 1060 Ti (OCd)

### GS Settings

![pcsx2x64-avx2_1Fyg1lEpe5](https://user-images.githubusercontent.com/59240947/164456121-955c7f05-9748-4bfd-9b16-2a547327673c.png)
![pcsx2x64-avx2_E7TfOLBCHp](https://user-images.githubusercontent.com/59240947/164456125-ab78b838-a907-4464-973f-b8bb62806c53.png)
![pcsx2x64-avx2_rtLMrxzADS](https://user-images.githubusercontent.com/59240947/164456128-23c6cc9e-d11d-4e18-80c7-079573788d42.png)

### Emulation Settings

![pcsx2x64-avx2_SP7sprOff1](https://user-images.githubusercontent.com/59240947/164456153-bfb25cad-af57-404f-a644-d68206e2b895.png)

**Comment by stenzek** [comment]
> but i don't think an ISO/weird hack issue could end up in a total C++ Redistributable error ,as i've never seen it happen due to a bad ROM.

It absolutely can and does. The dynarecs aren't very robust when it comes to invalid/corrupted code; jumping to unaligned or out of range PCs can make everything go boom.

Without the game, you'd need to get a backtrace for us to have any idea of what's going on.

**Comment by Gomam0n-afk** [comment]
> > but i don't think an ISO/weird hack issue could end up in a total C++ Redistributable error ,as i've never seen it happen due to a bad ROM.
> 
> It absolutely can and does. The dynarecs aren't very robust when it comes to invalid/corrupted code; jumping to unaligned or out of range PCs can make everything go boom.
> 
> Without the game, you'd need to get a backtrace for us to have any idea of what's going on.

I'll be happy to give you one, just tell me how i need to proceed to get one

**Comment by stenzek** [comment]
You can build from source and run under a debugger, or since the Qt interface has a crash dumper now, run that and upload the .dmp file (download from here: https://github.com/PCSX2/pcsx2/actions/runs/2202081657)

**Comment by lightningterror** [comment]
This to me looks like a out of vram issue,c try lower upscaling.
Can you post a gsdump of the scene?

**Comment by lightningterror** [comment]
@Gomam0n-afk Any update?

**Comment by lightningterror** [comment]
This should be resolved, if not lower upscaling.
