### ISSUE TITLE
[BUG]: Steam Deck crashes on iso launch

### ISSUE THREAD

**Issue by Matsmad7** [PCSX2/pcsx2#5931]
### Describe the Bug

launches but when loading game it crashes and closes app

### Reproduction Steps

launching any game

### Expected Behavior

app doesn't work

### PCSX2 Revision

1.7.2622

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

steam deck

**Comment by refractionpcsx2** [comment]
Yes we know, it's already working, but we don't control the distribution so you will need to wait for them to update it.
