### ISSUE TITLE
[BUG]: Wrong timezone while in game

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#5934]
### Describe the Bug

The timezone aren't correct for those 2 games : Capcom vs. SNK 2 and Marvel vs. Capcom 2. I could only verify it in those 2 games as the exact time is precised in the Save/Load options. This means that it could affect other games too.

The emulator adds 7 hours while in game (I'm in France btw) .

What I gathered : 

- The bios shows the correct time/timezone in the Memory Card section
- Every versions of those games have the same problem (JAP/EUR/USA) which is weird
- Tried Fullboot/Fastboot and it's the same problem
- Tried EUR/USA/JAP bios and it's the same problem
- Tried to delete the bios saves and it's the same problem
- It seems that the game always shows the japanese timezone

### Reproduction Steps

Windows 11 + Latest build + CVS2/MVC2 --> Go to Save/Load and save, now just check the time again in the same screen.

I'm in Paris timezone and the game adds 7 hours.

Example : My time is 10am, the game will display 5pm.

### Expected Behavior

The hours should reflect the time of the computer.

Marvel vs. Capcom 2 is famous for having a background with the clock showing the current time.

![Clock_Tower_1](https://user-images.githubusercontent.com/47425204/164718908-60789500-811d-4e5a-ae78-d1eed416ad87.jpg)

### PCSX2 Revision

v1.7.2641

### Operating System

Windows 11

### CPU

Ryzen 5600x

### GPU

AMD 6800

**Comment by refractionpcsx2** [comment]
Can you try it on the actual console to confirm it's not an issue there?

Did you check both full boot and fast boot?

**Comment by Immersion95** [comment]
> Can you try it on the actual console to confirm it's not an issue there?
> 
> On full boot it reads it exactly the same way as the real console does, so that's very strange if that doesn't work.

I will try as soon as I can but I'm 100% sure that it works that way, I played this game my whole life on a real PS2 as this is the only version that have 3P and 3K buttons.

**Comment by refractionpcsx2** [comment]
it looks to me like the game is completely ignoring the timezone and is always in Japan Timezone. Like the game says 22:00 for me now (which is the time in Japan, maybe without DST) and that's what the bIOS reports in Japanese Timezone.  But all that is being set correctly, so idk why the game isn't reading it.

**Comment by coornio** [comment]
What are the chances this time feature got popular IN Japan at the time, then word of mouth spread to others who also liked it but never cared all that much to notice that the game, while it read's the console's time, is adjusting the time to match Japan? :P

**Comment by Immersion95** [comment]
This is a possibility, I will try my best to check it as soon as I can.

I do think that there is a problem with the emulation of MVC2 (Japan), the save isn't auto loaded in the start screen whereas it works with MVC2 (USA & EUR). I then need to go to option to load the save.

I also tried with Dobbiestation and the the Memory card screen works at the start if no memory card is inserted, if one exists it is the same as PCSX2.

**Comment by refractionpcsx2** [comment]
well, honestly, the default timezone for the PS2 IS Japan, it actually does -0:00 if you're set to japan timezone, the others are all offsets (only Sony could fuck up timezones, right?)

**Comment by refractionpcsx2** [comment]
Also @Immersion95 please don't link to that website, we don't consider it legal.

**Comment by Immersion95** [comment]
> Also @Immersion95 please don't link to that website, we don't consider it legal.

Done, I replaced the link with the redump database.

**Comment by refractionpcsx2** [comment]
Thanks

**Comment by Immersion95** [comment]
I'm flabbergasted, the timezone is wrong on a real ps2 too. The memcard issue is also there. What a port from the DC version 🤐.

**Comment by Immersion95** [comment]
I'm really sorry for losing you time though, thanks a lot for this wonderful emulator.

**Comment by refractionpcsx2** [comment]
It's fine, the default is to blame us for getting it wrong, people forget the PS2 had bugs too :P

I guess it's a better bet to assume it's us.

**Comment by RedDevilus** [comment]
They might have hardcoded the timezone and forgotten about it when porting that the earth is round with more 1 timezone :P

**Comment by refractionpcsx2** [comment]
Nice work :) Yeah we found the same issue (I vaguely recall kr_ps2 looking at it)
