### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#5937]
### Discussed in https://github.com/PCSX2/pcsx2/discussions/5936

<div type='discussions-op-text'>

<sup>Originally posted by **trymeouteh** April 23, 2022</sup>
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/</div>

**Comment by kenshen112** [comment]
I can look into it later
