### ISSUE TITLE
[BUG]: PCSX2-Qt not building on Linux since introduction of CrashHandler

### ISSUE THREAD

**Issue by Zekromaster** [PCSX2/pcsx2#5938]
### Describe the Bug

`CrashHandler.cpp` (and the files it depends on) is not part of the build unless building on Windows. Still, `CrashHandler.h` is included by `Main.cpp`, creating an error at the moment of linking that makes the build fail.

By reverting to v1.7.2643, it builds correctly.

(I do realize the QT version is heavily WIP, especially on Linux, but this doesn't just break features or require workarounds on the user side, it actually makes the build completely fail, so I thought it might be worth it to report it anyway)

### Reproduction Steps

1. Try building with `-DQT_BUILD=TRUE`
2. Fail

### Expected Behavior

1. Try building with `-DQT_BUILD=TRUE`
2. Get a working executable

### PCSX2 Revision

v1.7.2647

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Gentoo

**Comment by refractionpcsx2** [comment]
Okay, telling us the error would be the minimum of what I would consider useful, saying "it doesn't work, need to revert it" doesn't really help us proceed.

If you could tell us the error, or if you want bonus points, you could fix it and PR it, that would be even better!

**Comment by Zekromaster** [comment]
I explained the specific error on literally the first paragraph.

> CrashHandler.cpp (and the files it depends on) is not part of the build unless building on Windows. Still, CrashHandler.h is included by Main.cpp, creating an error at the moment of linking that makes the build fail.

It's not actually solvable by just adding the file to the common makefiles - in fact, that would make the build fail because `CrashHandler.cpp` currently requires multiple Windows-only headers (which I assume is not the long term plan), but nothing is done to ensure it doesn't get called or included on other platforms.

I could easily make a quick and crude PR to "fix" that by putting an `#ifdef _WIN32` around the two inclusions and one call that make the build fail, which would at least temporarily make it build on Linux, if that's ok.
