### ISSUE TITLE
Metal Gear Solid 3 GPU glitches

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#594]
These are already known, but it's worth posting anyway IMO as I didn't find any other issue posted here.
D3D9/11 suffers the most. OGL is partly fixed. See below.

Missing effects in regular gameplay
**Hardware**
![mgs3hw](https://cloud.githubusercontent.com/assets/4414625/8035553/cc17537e-0df1-11e5-8b56-b110981a125e.png)
**Software**
![mgs3sw](https://cloud.githubusercontent.com/assets/4414625/8035560/db7a16b2-0df1-11e5-91e0-591a7eb3dd1b.png)

Missing overlay effect in codec conversations.
**Hardware**
![mgs3hw_codec](https://cloud.githubusercontent.com/assets/4414625/8035580/17172250-0df2-11e5-9187-555705ecd4e7.png)
**Software**
![mgs3sw_codec](https://cloud.githubusercontent.com/assets/4414625/8035585/1e08354a-0df2-11e5-9e51-e4060f420d2a.png)

**Comment by ssakash** [comment]
try checking the accurate blend option in GSdx plugin settings at the latest development build and check the status of the first issue. remember, the option could only be used on Opengl renderer.

**Comment by Blackbird88** [comment]
Oh right I forgot about it. I already compiled it myself just didn't try it yet with MGS3 :)

**Comment by ssakash** [comment]
the sun effect might comeback by disabling autodepth skip hack but, that might cause more problems.

**Comment by refractionpcsx2** [comment]
try setting accurate_blend to 2 in the gsdx.ini.  The sun is stronger in software mode. Although tbh i prefer the opengl mode :P

**Comment by Blackbird88** [comment]
Will give it a try. I'm honestly excited about the OGL's acurracy fixes. It's what PCSX2 was missing for so long.

**Comment by refractionpcsx2** [comment]
Likewise :) I'm quite looking forward to the idea of making OpenGL mode the default, which is slightly ironic in a plugin named gs"DX"

**Comment by ssakash** [comment]
(or) change the plugin name to GSOGL

**Comment by Blackbird88** [comment]
Or some generic name like SPU2ghz was changed to SPU2-X.
*derailed* :D

**Comment by ssakash** [comment]
by the way, does disabling autodepth skip hack bring back the sun effect ? GTA:SA also needed that for a specific sun effect.

**Comment by refractionpcsx2** [comment]
any game that uses any sort of depth for any post processing will have their effects returned by turning that off, however GSDX doesn't properly support depth yet, which is what gregory is trying to achieve :P

**Comment by Blackbird88** [comment]
I am actually going to try that now. It takes some time since I avoid using savestates to be 100% sure.

**Comment by refractionpcsx2** [comment]
Savestates will have no effect on skipping depth, you can also use GSDump's to check it as well.

**Comment by Blackbird88** [comment]
I enabled that hack in Gsdx Hacks section and it still looks same sadly.

**Comment by ssakash** [comment]
try checking whether ZeroGS has the codec overlay effect. actually, I meant to disable the Auto depth skip hack. if it still caused the lack of sun effect even while disable then, the source of problem might be elsewhere.

**Comment by Blackbird88** [comment]
Yeah I never had it enabled in the first place unless some CRC hack is overriding it.
Will check ZeroGS.

**Comment by gregory38** [comment]
generally  games uses tons of not emulated correctly effects. I suggest to wait my implementation of depth + the correction framebuffer mask.

**Comment by Blackbird88** [comment]
Literally can't wait! Thank you for those fixes.

**Comment by karasuhebi** [comment]
>Likewise :) I'm quite looking forward to the idea of making OpenGL mode the default, which is slightly ironic in a plugin named gs"DX"

>(or) change the plugin name to GSOGL

>Or some generic name like SPU2ghz was changed to SPU2-X.
derailed :D

I don't think GSOGL is a good name, specially since the plugin is still using both D3D and OGL, not OGL exclusively. I do think changing the name might be a good idea though, specially if the idea of splitting it into two plugins (one for PS1 and one for PS2) comes into play.

Maybe GS-X? I don't think that's a bad name. Looks close enough to GSdx and looks also like SPU2-X. The 'X' could be looked at as a variable. It could mean D3D or it could mean OGL. :D

**Comment by ssakash** [comment]
GS-GG ( one G stands for gabest and the other one for Gregory). though honestly, I think GSdx is quite fine.

**Comment by bositman** [comment]
Stop polluting the issue with chatter, kthx.

**Comment by Ryudo300** [comment]
It's not even a 'sun effect' really on the codec. It's basically an entire missing layer in the graphics. 

If you look closely you're supposed to have the Foxhound logo as well in there, but even that is missing.

**Comment by Blackbird88** [comment]
I didn't call it sun effect. I mean the sun effect on gameplay. It looks weaker. Codec is some overlay missing yeah.

**Comment by gregory38** [comment]
The game has CRC hacks that disable some rendering effects. I give a quick look and it is outside of my current scope.
On the color level, I saw also a small differences on God of War. Either a blending equation is bad or all of them have a small accuracy issue. Anyway I need to debug it but it is a lower priority.

**Comment by gregory38** [comment]
Latest dev branch improve the rendering (support of 8 bits textures) but due to texture cache issue only the top-left corner is correct.

**Comment by Blackbird88** [comment]
I've been following the Gsdx 2.0 thread and you're doing some amazing work! Hopefully MGS3 will be fully fixed one day :)

**Comment by lp200** [comment]
Sub RT support is possible?

**Comment by Blackbird88** [comment]
MGS3 gameplay seems fixed to me. Only Native is perfect for obvious reasons.
![image](https://cloud.githubusercontent.com/assets/4414625/14912793/dcd52f02-0dfe-11e6-9fff-ff810599279d.png)

**Comment by gregory38** [comment]
```
Codec still looks wrong.
```
It also explain the huge memory requirement. I think it is the same effect but my first implementation doesn't detect it properly. I have some on-going/pending code that could improve the situation.

**Comment by Blackbird88** [comment]
I assume you read my comments on @cb19451 right? It seems to have happened earlier.

**Comment by gregory38** [comment]
@Blackbird88 could you try the new PR #1322 . It must be good now.

**Comment by MrCK1** [comment]
Hope this is what you're looking for. I'll be off for a few hours, so don't expect a reply very soon :P

Native
![mgs3native](https://cloud.githubusercontent.com/assets/16314399/14926783/e5d58dd2-0e1b-11e6-9b2b-715699465f3a.png)

3x Native
![mgs33xnative](https://cloud.githubusercontent.com/assets/16314399/14926796/05ca94de-0e1c-11e6-9378-c05d67052db6.png)

**Comment by Blackbird88** [comment]
I already reported that. It's fixed in the PR above.

**Comment by MrCK1** [comment]
Actually those screenshots are from the new PR. No worries

**Comment by Blackbird88** [comment]
Gameplay effects fixed in @cb19451
Codec fixed in @9cacfee
Both in OpenGL backend.

**Comment by Tajnymag** [comment]
Codec is fixed for me only with CRC Hack Level set to partial and use of OpenGL. There would be nothing wrong with that, but when I do so, the game looks like this: 
![OpenGL (hardware) with CRC HL on partial](https://cloud.githubusercontent.com/assets/3985946/15476684/c920a868-2110-11e6-9d33-850d3193fddf.jpg)

![OpenGL (software)](https://cloud.githubusercontent.com/assets/3985946/15476702/f5dd9316-2110-11e6-98b7-3059b2cc7b87.jpg)

![OpenGL and Direct3d11 (hardware) with CRC HL on Full (the default one)](https://cloud.githubusercontent.com/assets/3985946/15476720/1e767aea-2111-11e6-9414-e1f40e99b7c2.jpg)

**Comment by Blackbird88** [comment]
AMD GPU?

**Comment by Tajnymag** [comment]
@Blackbird88 
1) No. GTX 660 TI with i7 3770
2) I'll try that.

**Comment by Blackbird88** [comment]
It's called **Half-Pixel Offset**
I forgot.

**Comment by Tajnymag** [comment]
Oh, thank you very much! Now, the emulation is nearly perfect. But there's a new glitch now :smiley:

Look at the borders of the screen. There are small dots all around
![20160523182455_1](https://cloud.githubusercontent.com/assets/3985946/15477314/210ba9bc-2114-11e6-941d-efc1accf1af2.jpg)

**Comment by Blackbird88** [comment]
Are you using some AA? IDK otherwise.

**Comment by Tajnymag** [comment]
Unfortunately I don't :-/ but this state is still better than the previous ones -> thank you very much :)
