### ISSUE TITLE
[BUG]: PCSX 2 doesn't start because of vulkan-1.dll

### ISSUE THREAD

**Issue by rashvash** [PCSX2/pcsx2#5940]
### Describe the Bug

PCSX 2 doesn't start because of vulkan-1.dll giving the message (see screenshot). happens BOTH in Win 10 x64 and Win 7 x64. 

Addition: Well, guys, it seems this is where I stop testing PSCX 2. Today after I reported the vulkan-1.dll bug in Discord. Stenzek (who is very resentful and sensitive guy as we know from the story with Duckstation and Retroarch with childish grudges of Stenzek at some guys (I'm not among them) answered with loads of foul language and insults to my adress and instead of helping to solve the problem and of looking into it he simply band me in both PSCX 2 and Duckstation discord channels (even though I didn't write anything on Duckskstaion discord channel today) . After I critized hos work a little (and vulkan-1.dll problem appeared only in 1.7 build after vulkan implementation, which is actually Stenzek's work) he got furios again and ban me to cover his mistakes.(yeah that's how he solves the problems usually). Maybe because guys like Stenzek solve porblems and bugs of PSCX 2 like that we still got 1,15 % perfect and many games unplayable, partially playable, partially playable with millions of fixed games after 20 years of development. I can only add today I also tested Duckstation a lot. And send lotsa bug reports to DS discord channel. With screenshots and detailed descriptions of bugs and none of them were ever solved. I asked for Konami justifier support in Duckstation YEARS ago. Stenzek promised to implement it. As you've already guessed it was never done. I'm not amongst the guys who mocked him in this retroacrh-DS situation (though I think his grudges are childish and he constantly acts like a child). I know he's very resentful and nervous guy. Today he started  insulting me out of blue and ended by banning me out of blue.

### Reproduction Steps

1.use videocard w/o vulkan support.
2.use devbuilds after Stenzek's vulkan implementation
3.run PCSX 2.exe
4,Get the error message (see screenshot)

![1](https://user-images.githubusercontent.com/28275367/164891532-327314e0-5a04-4f28-9322-3c62e54c9c55.jpg)

### Expected Behavior

1.Run PCSX 2 normally on videocards w/o vulkan support and then let users to select the renderer
2.Fix the problem like bring it to the point 1 above or make verions w/o Stenzek's shitty implemented Vulkan.

### PCSX2 Revision

1.7.2647

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
I'd suggest getting your own house in order before attacking other people. I even demonstrated how PCSX2 runs fine if you remove the vulkan dll. **You're most likely using a wrapper library, or something else, which depends on Vulkan, and that's what's requiring it, not PCSX2**.

More proof you're lying:

Result of running current builds on Windows 7:
![image](https://user-images.githubusercontent.com/11288319/164891617-2b87f8f9-8645-4c7b-872e-7e1681644433.png)

Result of running current builds on Windows 7 with the DX11 and DX12 renderers disabled:
![image](https://user-images.githubusercontent.com/11288319/164891637-c6515089-21cc-4c9b-a709-09142d173a7c.png)

**Comment by stenzek** [comment]
Also, I didn't ban you, I don't even have moderation rights on PCSX2's server ;)

**Comment by rashvash** [comment]
Note*: In PCSX 2 discord channel there were also loonies like Stenzek who said: "you're setup is no good, it's broken, change the rig, don't criticize Stenzek he's our god and he's saint". But as soon as I change videocard in the same setup with the Win 7(sic!) to a videocard WITH vulkan supports which is not latest and not new and not top-notch (ATI HD 7870)  everything starts fine. I stress this especially for Stenzek and likes - ON WINDOWS 7 even.  So it seems Stenzek and likes are the ones who should go and fix their hands, rigs vulkan-implementation and broken conscience.

**Comment by rashvash** [comment]
> Also, I didn't ban you, I don't even have moderation rights on PCSX2's server ;)
> 
> I'd appreciate it you apologised for all the stuff you're wrongly accusing me of, but I won't hold my breath :)

Yeah, I just suddenly disappeared at the same moment from PCSX 2 and Duckstation  chanells. You didn;t ban me of course.

**Comment by stenzek** [comment]
Sigh. You're not reading what anyone's saying. For the second time, you're probably using some wrapper, or other third-party library, maybe to work around the DXGI requirement, and **that** is what's requiring vulkan, **not** PCSX2. Otherwise it wouldn't have started in my VM, because that definitely doesn't have Vulkan.

> Note*: In PCSX 2 discord channel there were also loonies like Stenzek who said: "you're setup is no good, it's broken, change the rig, don't criticize Stenzek he's our god and he's saint"

Nobody said anything like that. I even told you that if there was a hard dependency on Vulkan, regardless of the OS, that it's an issue. So I looked into it, checked the imports, tried running without the dll, and it worked fine.

> Yeah, I just suddenly disappeared at the same moment from PCSX 2 and Duckstation chanells. You didn;t ban me of course.

I banned you from the DuckStation server. Someone else (not me) banned you from PCSX2. I wonder why....

**Comment by rashvash** [comment]
> I'd suggest getting your own house in order before attacking other people. I even demonstrated how PCSX2 runs fine if you remove the vulkan dll. **You're most likely using a wrapper library, or something else, which depends on Vulkan, and that's what's requiring it, not PCSX2**.
> 
> More proof you're lying:
> 
> Result of running current builds on Windows 7: ![image](https://user-images.githubusercontent.com/11288319/164891617-2b87f8f9-8645-4c7b-872e-7e1681644433.png) ![image](https://user-images.githubusercontent.com/11288319/164891664-747776df-687a-47d7-86a2-a9268d47f607.png)
> 
> Result of running current builds on Windows 7 with the DX11 and DX12 renderers disabled: ![image](https://user-images.githubusercontent.com/11288319/164891658-29e3dc4d-aeae-420a-bd6b-065f76046b42.png)

First, learn to run 1.7 build on Win 7. I'll tell you a secret there's a way (shame that a developer of so many emulators doesn't know this). Second, go to discord and see who attacked who (a tip: some guy who told many "good" things about arrogant (that's not the worst word you used I just censor the others like arses and others) win 7 users and stuff. Third: Don't just vulkan.dll, try to test it on a videocard w/o vulkan support. I've already told you that before you got angry and suddenly ban me. It's not the same stuff.

**Comment by stenzek** [comment]
> First, learn to run 1.7 build on Win 7. I'll tell you a secret there's a way (shame that a developer of so many emulators doesn't know this). 

Did you even look at my screenshot? It's clearly opened on Win7 (albeit without the DX11/12 renderers, since I disabled them).

> Third: Don't just vulkan.dll, try to test it on a videocard w/o vulkan support. I've already told you that before you got angry and suddenly ban me. It's not the same stuff.

Are you saying my virtual machine has vulkan support? Because it doesn't even have vulkan-1.dll, let alone a GPU driver that implements Vulkan...

**Comment by rashvash** [comment]
> I banned you from the DuckStation server. Someone else (not me) banned you from PCSX2. I wonder why....

At least you consider that. Though I don't believe in coincidences and random synchronicity. 

I wonder what's your next step. Considering you've never fixed none of my millions bug reports to DS discord server? Or that you're no able to implement Konami justifier to DS?


> Are you saying my virtual machine has vulkan support? Because it doesn't even have vulkan-1.dll, let alone a GPU driver that implements Vulkan...

I'm saying you're not testing it on real hardware. And I do. That's the difference and I got real, not emulated on VM results.

**Comment by rashvash** [comment]
> > First, learn to run 1.7 build on Win 7.
> 

> > I'll tell you a secret there's a way (shame that a developer of so many emulators doesn't know this).
> 

Then how you comment that when I change to HD 7870 with vulkan support in the very same WIN 7 it starts even with wrapper?

**Comment by stenzek** [comment]
> Then how you comment that when I change to HD 7870 with vulkan support in the very same WIN 7 it starts even with wrapper?

So you are using a wrapper? Maybe dxvk? Why won't you accept that the wrapper is the reason you're having this issue in the first place then? (and using that other gpu probably installs the vulkan loader. it makes perfect sense now)

> I wonder what's your next step. 

Working on whatever I feel like ;) It's a fun hobby, I work on fun things, not what people demand me to do. Couldn't care less what you think or want.

**Comment by rashvash** [comment]
> I banned you from the DuckStation server. Someone else (not me) banned you from PCSX2. I wonder why....

Such a great guy are. You appear today on PCSX 2 discord channel and start with insulting me with all the fgul word you know. Then you band me from DS discord server where I've never written anything bad and even wasn't present today. "Working on whatever I like, band anybody I don't like for any random reason or without it" That's seems to be your motto.

**Comment by stenzek** [comment]
So, I think we can consider this issue invalid then? If you remove the wrapper, the vulkan dependency would disappear.

I never insulted you personally. I made a general remark about the arrogance of Windows 7 users, and you're proving my point correct by the way you're acting.

**Comment by rashvash** [comment]
> place then? (and using that other gpu probably installs the vulkan loader. it makes perfect sense now)

It doesn't. Because with the first GPU it doesn't start even with vulkan loader. I did tell you that too before you ban me

> Working on whatever I feel like ;)

Or on whatever you CAN do. It doesn't hurt to consider you cant' do some things. It's normal. No all people like you and your likes on PCSX 2 discord. Nobody will kill you for that.



> So, I think we can consider this issue invalid then? If you remove the wrapper, the vulkan dependency would disappear.
> 
> I never insulted you personally. I made a general remark about the arrogance of Windows 7 users, and you're proving my point correct by the way you're acting.

I should write something "good"  about not Stenzek but about certain Duckstation developer who implemented vulkan in PCSX 2 to not insult you personally. 

No, we can't the problem is with vulkan implementation which switch of VC's show.

**Comment by CookiePLMonster** [comment]
> No, we can't the problem is with vulkan implementation which switch of VC's show.

> First, learn to run 1.7 build on Win 7. I'll tell you a secret there's a way (shame that a developer of so many emulators doesn't know this).

Pick one

**Comment by stenzek** [comment]
> No, we can't the problem is with vulkan implementation which switch of VC's show.

Then compile PCSX2 without the Vulkan renderer. If you use CMake, you can disable it in the options. `-DUSE_VULKAN=OFF`. 

But the net result will be the same, because **PCSX2 IS NOT THE ONE IMPORTING VULKAN. YOUR WAPPER IS.`

**Comment by rashvash** [comment]
> > No, we can't the problem is with vulkan implementation which switch of VC's show.
> 
> > First, learn to run 1.7 build on Win 7. I'll tell you a secret there's a way (shame that a developer of so many emulators doesn't know this).
> 
> Pick one

Sorry, google it or ask Stenzek. I'm testing DS and PCSX 2 for free (anfdfor Stenzeks' bans) not giving lessons.

**Comment by CookiePLMonster** [comment]
> Sorry, google it or ask Stenzek. I'm testing DS and PCSX 2 for free (anfdfor Stenzeks' bans) not giving lessons.

No, you are posting incomplete issue reports from an outdated OS and refuse to acknowledge the error might lie in whatever hack you are using to run it on Win7, but you do you.
