### ISSUE TITLE
[BUG]: Virtua Tennis 2 : "GIF Unit - GS packet size exceeded VU memory size" error at boot.

### ISSUE THREAD

**Issue by gitpro03** [PCSX2/pcsx2#5959]
### Describe the Bug

When booting "Virtua Tennis 2" in PCSX2, the game does work, but the console print this error before entering the video mode selector:

"GIF Unit - GS packet size exceeded VU memory size".

Given how badly the recompilated code went, I am surprised the game works. Even still, it still shouldn't happen.

I tried pretty much every settings possible, that log is still there.

### Reproduction Steps

Load the blockdump given with the bug report. The log will appear in a short amount of time.

### Expected Behavior

The game code probably doesn't behave like this on real hardware. (if it does... well...)

### PCSX2 Revision

pcsx2-v1.7.2656-windows-x86

### Operating System

Windows 11

### CPU

Intel core I9 9900K

### GPU

Nvidia Gefore RTX 3070

### Logs & Dumps

Blockdump of Virtua Tennis 2:

[Virtua Tennis 2 - GIF Packet error.zip](https://github.com/PCSX2/pcsx2/files/8557333/Virtua.Tennis.2.-.GIF.Packet.error.zip)

MD5 of the bin file: 74a31eda1d75cbba28a23a6770fdc102 (matches the redump entry so the bin file is correct - http://redump.org/disc/1221/).

**Comment by refractionpcsx2** [comment]
Okay this looks to be a bug in the game, it starts a VU program off and a GS transfer from that program before it's set up the packet it needs to send, so on a real console that will loop indefinitely.

However after that program it does fill in the memory it needs, then it would continue happily.

So yeah, it's a non fatal game bug, so I'm afraid this is a won't fix, just ignore it :)

**Comment by gitpro03** [comment]
Thanks for the quick response and the dive-in into the game code!

I guess that's an "Oops" moment from Sega ;).

Btw, the game does have other problems, but, that's for an other bug report.

**Comment by refractionpcsx2** [comment]
Yeah no problem, will happily look in to them :) They probably never noticed this because it would work fine :P
