### ISSUE TITLE
[Idea] Enable Large Address Aware by default

### ISSUE THREAD

**Issue by Sarania** [PCSX2/pcsx2#596]
I may be wrong on this, but according to the info on the page for NTcore's 4GB patch and some other info I found, it should be possible to make a 32 bit app Large Address Aware from the dev end, instead of needing the patch. I'm not sure on the specifics of it but I'm doing some research.

Anyway - if this is indeed possible, I think we should do it (barring any issues that I don't know about). If it's not possible, I propose we prepatch our release versions to be LAA. I know not a huge number of games need it, but I don't think it causes any harm so it just makes things easier for the user.

~~Edit: Okay more research says it may not be possible from within the source code (Microsoft keeps it out of Visual Studio because they'd rather you make 64 bit app than use LAA, IDK about the situation on Linux). So that may be out. But still the prepatch idea is an idea.~~

Edit: __Even more research (thanks @Evolution0 ) suggests it IS possible after all.__

**Comment by Evolution0** [comment]
You can't [enable it](https://msdn.microsoft.com/en-us/library/wz223b1z(v=vs.120).aspx)?

**Comment by Sarania** [comment]
Maybe you can! I'll look into that and if so make a PR.

**Comment by refractionpcsx2** [comment]
I was going to do it ages ago, pseudonym had a freakout about potential pointer issues.  I personally don't see what the issue would be so might do it at some point.

**Comment by Sarania** [comment]
@refractionpcsx2 Well I will just enable it locally and make some tests. I have lots of games ripped so I can do that.

Is there any situation I should specifically look for that might be broken by it?

**Comment by refractionpcsx2** [comment]
Crashes in high memory situations possibly,  snowblind games and games with high scaling would be good candidates

**Comment by Sarania** [comment]
@refractionpcsx2 Alright then. The next time I have a fat chunk of free time (probably within a few days) I will make some tests of it. Since I am on 64 bit and have 8GB of RAM I can make good tests. Once I have tested stuff, I will report back here.

I remember there is some other game aside from Snowblind ones that needs 4GB patch, I can't remember it though. If anyone knows of specific, non Snowblind games that need 4GB patch then please report it here so that I may test it!

**Comment by Evolution0** [comment]
Dark Cloud 2 and Grandia III needed it as well I believe.

Though there are probably a few more.

**Comment by Sarania** [comment]
@Evolution0 Granda III shouldn't, I think. I played it in PCSX2 this year(not to completion, but most of the first disc) and didn't need it.

DC2 IDK about. But I do have it, so I'll give it a test. Thanks.

**Comment by Evolution0** [comment]
Yeah Grandia III needed it *ages* ago, due to optimizations since then its most likely just not needed anymore.

**Comment by TheLastRar** [comment]
Possible relevant to testing

http://stackoverflow.com/a/22745579

**Comment by Sarania** [comment]
Thanks. I read that earlier actually and is why I decide to do thorough testing.

**Comment by bositman** [comment]
https://www.google.gr/search?q=4gb+patch&sitesearch=forums.pcsx2.net&gws_rd=cr,ssl&ei=hBF4Va_HHIfmywPR14DwBw
Simple but effective :P

**Comment by karasuhebi** [comment]
@bositman lol I came on here to do precisely that. XD

**Comment by Sarania** [comment]
@bositman @karasuhebi 

I feel like a derp. The simplest stuff always eludes me.

Anyway later depending on how my day goes I plan to make a branch locally, compile it, and ask for several testers on the forum. The stuff that @TheLastRar posted makes me a bit skittish on implementing it without very thorough testing.

**Comment by gregory38** [comment]
Globally it seems that the memory hog is GSdx. It is likely related to the texture cache that goes bold. In my opinion it might be a better idea to improve it. This way it can trash useless data instead to keep them in memory.

**Comment by refractionpcsx2** [comment]
Any further news on this? Could be a solution/workaround for the mean time, until GSDX gets its memory allocation improved.

**Comment by gregory38** [comment]
status?

**Comment by karasuhebi** [comment]
@Sarania Let's get going on this. I'll help you test if you want. :D

**Comment by Sarania** [comment]
Err well I've been using an LAA build pretty much exclusively for a few months if that counts as testing. Honestly I forgot I had it built that way rofl. So yeah. If there are some specific games to test we can have at it.

**Comment by willkuer** [comment]
So the thread linked by TheLastRar suggested (if i understood correctly) to enable some compilation flag to invert memory alignment (or something else). And this would instantly show if there is some bad memory management.

One post contained the info that even if the whole memory consumption can be larger than 2gb a single block always needs to be smaller. Additionally it was said that comparing two pointers that are more far away than 2gb from each other on an int base and not size_t will leed to crashes as well. Unsigned and signed comparisons could yield similar crashes.

But as a lot of people already use this patch i think we can assume that either such scenarios are not relevant for popular games or that there is none of the mentioned issues in gsdx.

As these are nightly builts i would just suggest to merge it and let the whole community force-test this so that we know for sure if it works before 1.4 release.

**Comment by Sarania** [comment]
I'm installing VS at the moment and once it's done I will make a PR and we'll see where it goes. As I said I've been using it pretty much constantly with no issues, though I don't play any games that I know require the patch either,

**Comment by willkuer** [comment]
But i guess thats also the point.
The games that require the patch are already intensely tested with the patch. If there would be a lot of issues with those games we would probably know.

All other games dont require it and therefore probably dont see a difference.

**Comment by Sarania** [comment]
I agree, well we'll have a PR in an hour or two, the devs can decide then if they agree, if not I'll post a tester build to the forums,

**Comment by Sarania** [comment]
I swear to God github is the worst developer tool I've ever used in my life. Every single time I go to do something like this it takes hours of fiddling.

I'm ready to PR but I need to squash and it won't let me, it just freezes after issuing git rebase -i HEAD~2

**Comment by willkuer** [comment]
Git rebase -i pcsx2/master

**Comment by Sarania** [comment]
"fatal: Needed a single revision
invalid upstream origin"

Screw it, I just deleted and recreated my fork. https://github.com/PCSX2/pcsx2/pull/982 whew that took forever -.-

**Comment by karasuhebi** [comment]
>I swear to God github is the worst developer tool I've ever used in my life. Every single time I go to do something like this it takes hours of fiddling.

git gud <.<

**Comment by Sarania** [comment]
#982 is merged so this is a thing now. :)
