### ISSUE TITLE
[BUG]: MX vs ATV Extreme Limite : Weird COP2 behaviour when going ingame.

### ISSUE THREAD

**Issue by gitpro03** [PCSX2/pcsx2#5960]
### Describe the Bug

When going ingame in the game "MX vs ATV Extreme Limite", there is an extremly weird code which is generated on the COP2 side:

1a9c08 *4BDBD9FF vclip vf27xyz, vf27w
1a9c0c =484E9000 cfc2	t6, ClipFlag

This should "never" happen on a real PS2 (if you want your code to work at leist).

A solution would be to hotfix this with a patch like this:

(CRC: 590C682E) (Serial: SLES-55051)

patch=1,EE,001a9c08,word,484E9000
patch=1,EE,001a9c0c,word,4BDBD9FF

### Reproduction Steps

There is nothing to reproduce, that is the only bad COP2 code I saw when running the game.

### Expected Behavior

The generated COP2 code should not end up inverted.

### PCSX2 Revision

pcsx2-v1.7.2656-windows-x86

### Operating System

Windows 11

### CPU

Intel core I9 9900K

### GPU

Nvidia Gefore RTX 3070

**Comment by refractionpcsx2** [comment]
Oh I didn't think about the other versions like that. Thanks for the patch :)

**Comment by gitpro03** [comment]
Ok. Thanks for the explaination about COP2, I was confused when reading about it in the PCSX2 code.

Effectively, the SPS is very subtle, but it is there.

By the way, if I follow what you said:

142320 *4B0320CA vmaddz.x vf03, vf04, vf03z
142324  4A6303BE vrsqrt Q, vf00w, vf03x
142328 =48438800 cfc2	v1, MACflag

This should not be a problem because the vrsqrt is in the middle, so that mitigate the need of the delay, is that right?

**Comment by refractionpcsx2** [comment]
it's not a problem because VF03 is read just after it's written, and since the delay for any instruction (that isn't vdiv, vrsqrt or vsqrt) is 4 cycles (which is why the CLIP works on the console), it will actually delay it, so by the time the cfc2 happens, the flags are updated.

However to make the whole thing even more awkward, cfc2 has to be technically 5 slots away from the instruction (if there was no stall) because its pipeline is actually shorter.

COP2 is annoying :P

**Comment by gitpro03** [comment]
Wtf... how could you emulate that behaviour without being super slow?

If I understand, you almost need to keep track of the whole pipeline to check each individual ops and determine which one is going to be executed before the other... And you have CFC2 to adds more juice to the mix.

I imagine the absolute mess that can result of that COP2.

**Comment by refractionpcsx2** [comment]
> Wtf... how could you emulate that behaviour without being super slow?

And that's why we don't :D

> If I understand, you almost need to keep track of the whole pipeline to check each individual ops and determine which one is going to be executed before the other... And you have the CFC2 to adds more juice to the mix.
> 
> I imagine the absolute mess that can result of that COP2.

Yeah it can get messy, which is why we report any potential errors. We don't do proper pipeline checks as that'd be slow.
