### ISSUE TITLE
[BUG]: Ninja Assault: Intro Captions Error

### ISSUE THREAD

**Issue by waspennator** [PCSX2/pcsx2#5965]
### Describe the Bug

For some reason, the intro captions that show up only display correctly on the software renderer. They fail to show up at all on Vulkan and OpenGL, and on DX11 and DX12, they show up, but heavily glitched.

### Reproduction Steps

Just start the game up with each renderer and watch the intro, software should get you the text, Vulkan and OpenGL should get you no text, and DX11 and DX12 should get you glitched text.

### Expected Behavior

The intro text should display correctly on all renderers, not just the software renderer.

### PCSX2 Revision

v1.7.2658

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Window Screenshots

Software Renderer:
![Ninja Assault software](https://user-images.githubusercontent.com/78768499/165194748-cc0ff499-bef3-4190-8adb-c18cd98ccc8d.png)

Vulkan and OpenGL Renderers:
![Ninja Assault Vulkan and OpenGL](https://user-images.githubusercontent.com/78768499/165194769-0e6fbc3e-a1bb-4676-b856-773d92a5c316.png)

DX11 and DX12 Renderers:
![Ninja Assault DX12 and DX11](https://user-images.githubusercontent.com/78768499/165194800-af8c30f7-0091-4080-a6ab-808f950ef5a6.png)

### Logs & Dumps

[Ninja Assault - Broken Text DX12.zip](https://github.com/PCSX2/pcsx2/files/8558731/Ninja.Assault.-.Broken.Text.DX12.zip)
[Ninja Assault - Broken Text Vulkan.gs.zip](https://github.com/PCSX2/pcsx2/files/8558732/Ninja.Assault.-.Broken.Text.Vulkan.gs.zip)

Two GSdumps tested with Vulkan and DX12 since OpenGL and DX11 both produce the same result.

**Comment by RedDevilus** [comment]
Seems to need Preload Frame Data:

![image](https://user-images.githubusercontent.com/24227051/165199448-31ece223-02a2-4099-aaa4-80aa5fbf3a7d.png)

**Comment by waspennator** [comment]
Tested that out and can confirm that fixes the issue on Vulkan and OpenGL. DX11 and DX12 still has the glitchy text though, even with the hack.

**Comment by RedDevilus** [comment]
Hmmm not sure if that is a GS Download problem on DX11 and DX12. I do see it flicker for a moment when I change my settings so the data is there.

**Comment by lightningterror** [comment]
DX11/12 in addition to needing Preload frame data will need Medium blending.
