### ISSUE TITLE
[BUG]: Time Crisis 2: Visual bugs

### ISSUE THREAD

**Issue by waspennator** [PCSX2/pcsx2#5966]
### Describe the Bug

For some reason, this game seems to have slight visual glitches across all of the backends. The Vulkan and OpenGL renderers have a noticeable white square that seems to stick around in the top left corner of the screen. DX11 and DX12 renderers have that, as well as the screen being a brighter white then usual. Software Renderer doesn't have either of the issues, but the demo play text looks garbled and warped.

### Reproduction Steps

Skip the intro and let the game go to demo play and it should be noticeable right away.

Use Vulkan and OpenGL for the white square at the top left.

Use DX11 and DX12 for the white square and a strangely brighter screen.

Use Software to see the demo play text garbled.

### Expected Behavior

There should be no white square at the top left of the screen during gameplay, weird white bright filter, or garbled demo play text.

### PCSX2 Revision

v1.7.2658

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Window Screenshots

Vulkan and OpenGL Renderers:
![Time Crisis Vulkan screen bug](https://user-images.githubusercontent.com/78768499/165215009-fde66d41-570b-4f04-8c96-b40996efb077.png)

DX11 and DX12 Renderers:
![Time Crisis 2 DX12 screen bug](https://user-images.githubusercontent.com/78768499/165215066-3e635d37-4aa9-4254-8560-e2849e50c56e.png)

Software Renderer:
![Time Crisis 2 Software screen bug](https://user-images.githubusercontent.com/78768499/165215284-b81a9628-e4c0-4fd7-8a8d-7e6d4c0ca841.png)

### Logs & Dumps

[Time Crisis 2 - Visual Bugs DX12.zip](https://github.com/PCSX2/pcsx2/files/8559616/Time.Crisis.2.-.Visual.Bugs.DX12.zip)
[Time Crisis 2 - Visual Bugs Software.zip](https://github.com/PCSX2/pcsx2/files/8559617/Time.Crisis.2.-.Visual.Bugs.Software.zip)
[Time Crisis 2 - Visual Bugs Vulkan.zip](https://github.com/PCSX2/pcsx2/files/8559619/Time.Crisis.2.-.Visual.Bugs.Vulkan.zip)

Tested with Vulkan, DX12, and Software renderers.

**Comment by lightningterror** [comment]
For dx11/12 they will need High blending for the brighter screen.

**Comment by F0xH0L3** [comment]
This issue started at v1.7.2301, earlier 1.7 versions have had different graphical glitches, but not this one.
V1.6 didn't have any graphical glitches.
Anyways, to get around this issue, turn on "Disable Depth Emulation" hack.
Just note that this isn't the only graphical glitch, there's another one that seems to happen very randomly at stage 1 just after you go out the window. Basically it gives the impression of something that looks like an image retention, for the lack of a better description.

**Comment by refractionpcsx2** [comment]
2301? then maybe @tellowkrinkle can have a look, or @iMineLink  since they kind of worked on that code (the resizing stuff) together.

**Comment by F0xH0L3** [comment]
If i can be of any help, feel free. Though i'm not a coder, but i am a very diligent tester.

**Comment by refractionpcsx2** [comment]
The GS dumps in the original post should be enough for now, thanks.

**Comment by dudesh34** [comment]
Time crisis 3 has the same white square on the left upper screen on vulkan and opengl now. didnt have thiseon old versions.

**Comment by F0xH0L3** [comment]
> Time crisis 3 has the same white square on the left upper screen on vulkan and opengl now. didnt have thiseon old versions.

Same fix applies, turn on "Disable Depth Emulation" hack.

**Comment by dudesh34** [comment]
> 

i cant find the "Disable Depth Emulation"...where is it?

**Comment by dudesh34** [comment]
found it...now the only problem are the huge stuttering and slowdowns...which i dont have in older versions from 2 years ago.

**Comment by Comfarol** [comment]
This issue still persists. At first these settings help the issue at the beginning of the game, "Disable Depth Emulation" and "High Blending" enabled. But the problems show up again later in the game. Only now with USB merge have I been able to progress and test it.

![image](https://user-images.githubusercontent.com/27315987/208324796-62ff33c1-b62a-473b-8cf0-a8baebf122a0.png)

PCSX2 Nightly - v1.7.3732
SCES-50300

**Comment by RedDevilus** [comment]
Can you make a gs-dump on the moment(s) of when the issue happens?

How To Create A GS Dump
What is a GS dump?
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

Where do I make the dump?
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

How do I make the dump?
Stable 1.6.0 and Nightly 1.7 wxWidgets:
Use the key combination Shift + F8

Nightly 1.7 Qt:
Tools > Save Single Frame GS Dump

Where does the GS dump save to?
GS dumps are saved to the /snaps folder.
- If you used the PCSX2 installer, you will find it in Documents/PCSX2.
- If you are using a nightly build, you will find it next to the PCSX2 executable.

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by Comfarol** [comment]
I have some more info as i test. It seems to be remnants from or related to the FMV. Skipping the FMV sometimes results in no artifacts, but letting it play almost always leaves the issue.

I'll get a dump in a moment

![image](https://user-images.githubusercontent.com/27315987/208326692-f0ec1da6-09bc-4e35-9be7-b4bb3ab6cf7b.png)

**Comment by Comfarol** [comment]
Do you want the gs.zst file? It says it doesnt support that file type

**Comment by RedDevilus** [comment]
> Do you want the gs.zst file? It says it doesnt support that file type

Just zip it (or might to extract and put in a zip format)

It's just github limiting certain extensions.

**Comment by Comfarol** [comment]
[Time Crisis 2_SCES-50300_20221219101239.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10255007/Time.Crisis.2_SCES-50300_20221219101239.gs.zst.zip)

**Comment by Comfarol** [comment]
> Just note that this isn't the only graphical glitch, there's another one that seems to happen very randomly at stage 1 just after you go out the window. Basically it gives the impression of something that looks like an image retention, for the lack of a better description.

Should this issue have its own topic, as it is more related to foxholes description and not OP

**Comment by dudesh34** [comment]
yes, time crisis 2 has regressed for sure in the 1.7 builds in terms of gfx...wonder why.

**Comment by RedDevilus** [comment]
> > Just note that this isn't the only graphical glitch, there's another one that seems to happen very randomly at stage 1 just after you go out the window. Basically it gives the impression of something that looks like an image retention, for the lack of a better description.
> 
> Should this issue have its own topic, as it is more related to foxholes description and not OP

Whatever fits the best to you.


It gets cleared by pressing F9 twice (changing to software and back):

![image](https://user-images.githubusercontent.com/24227051/208328764-ad6eeb32-192a-41b9-afa1-50ff600feb7f.png)

Can't do much with a texture cache issue which is unfortunate. Needs more research.

**Comment by Comfarol** [comment]
It doesn't happen in 1.6 though, so something has caused it?

**Comment by RedDevilus** [comment]
Changes happen all the time and not always for the better, called a regression.

**Comment by Comfarol** [comment]
Sometimes it doesn't show up though, which is odd. Watching or skipping FMV.

**Comment by lightningterror** [comment]
> This issue still persists. At first these settings help the issue at the beginning of the game, "Disable Depth Emulation" and "High Blending" enabled. But the problems show up again later in the game. Only now with USB merge have I been able to progress and test it.
> 
> ![image](https://user-images.githubusercontent.com/27315987/208324796-62ff33c1-b62a-473b-8cf0-a8baebf122a0.png)
> 
> PCSX2 Nightly - v1.7.3732 SCES-50300

Can you create that exact dump on build v1.7.2300
https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.7.2300&platform=windows-x86

**Comment by Comfarol** [comment]
It's pretty difficult to play with the pad, you run out of time alot and lose health. I'll try get to that train area.

**Comment by Comfarol** [comment]
[gs_20221219121444.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/10255382/gs_20221219121444.gs.xz.zip)
![gs_20221219121444](https://user-images.githubusercontent.com/27315987/208334866-58fdfe96-82af-4f74-bfe5-b684036d48ca.png)

Is this right? I haven't noticed any of the above so far with v1.7.2300, ive let cinematics end/skipped and started a few times.

**Comment by lightningterror** [comment]
With a bit of investigation the commit that caused the regression is https://github.com/PCSX2/pcsx2/commit/eca5eced63d216941b60ea907697143dd2c9c4e9

**Comment by Comfarol** [comment]
Not sure what any of that means, but that's good to find?

**Comment by waspennator** [comment]
Testing out the other 2 Time Crisis games, like dudesh said. Opengl and Vulkan have the white square on the top left and dx11 and 12 have that whitish screen filter for 3 which can be fixed with disable depth buffer and high blending. (though no noticeable issues from first glance on software) Crisis Zone doesn't seem to have any noticeable issues at all visually or audio cutscene wise at first glance.

**Comment by Comfarol** [comment]
Played so much of the US copy of TC2 today and been unable to produce the error. If anyone else could test the two versions to confirm that it's just the PAL copy? (with disable depth buffer and high blending enabled)

**Comment by RedDevilus** [comment]
> Played so much of the US copy of TC2 today and been unable to produce the error. If anyone else could test the two versions to confirm that it's just the PAL copy? (with disable depth buffer and high blending enabled)

At that point shouldn't the Software Renderer be a better test to not be distracted with texture cache or other issues?

**Comment by Comfarol** [comment]
Its just the visual errors, software mode runs it perfectly from what i've observed.

**Comment by Comfarol** [comment]
I noticed this issue again on newer version 1.7.4446
last version i tried doesn't seem to have it 1.7.4379

![Time Crisis II_SLUS-20219_20230501132032](https://user-images.githubusercontent.com/27315987/235398646-d9bf4317-3d90-47c6-a709-86386f4d3456.png)


[Time Crisis II_SLUS-20219_20230501132032.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11363281/Time.Crisis.II_SLUS-20219_20230501132032.gs.zst.zip)
