### ISSUE TITLE
[BUG]: Time Crisis 2/3/Crisis Zone Inaccurate Cursor

### ISSUE THREAD

**Issue by K6TPg6g9f** [PCSX2/pcsx2#5967]
### Describe the Bug

When going through the aiming calibration, the aim doesnt follow the device the farther from the center the aim is. It's accurate in the center but drifts as the aiming device moves which also reflects into gameplay.

I understand that the wiki states that this is fixed, however this doesnt seem to be the case. The issue persists even after the recommended steps to disable widescreen hacks and play in 4:3.

Could be related to the window scale, the issue doesnt seem to persist while the window is the small size of 640x480

### Reproduction Steps

Run the game in 4:3
Enable mouse calibration hack in nuvee
Start Time Crisis 2 and start the calibration
Click the middle of the screen
Move the aiming device and check the accuracy of the reticle

### Expected Behavior

The aiming device and game reticle to be 1:1 and accurate

### PCSX2 Revision

v1.7.440

### Operating System

Windows 10 (64bit)

### CPU

i7-8700k

### GPU

RTX 2080ti

### GS Settings

Default, using OpenGL, didnt touch anything

### Emulation Settings

Default

### GS Window Screenshots

Here is a video of the issue in action

https://webmshare.com/play/PbdrL

### Logs & Dumps

[tc2 reticle issue.zip](https://github.com/PCSX2/pcsx2/files/8559973/tc2.reticle.issue.zip)

**Comment by refractionpcsx2** [comment]
Is it any more accurate if you enable "screen offsets" in the settings?
