### ISSUE TITLE
How would we go about addiing some hacks to cheat_ws.zip?

### ISSUE THREAD

**Issue by i30817** [PCSX2/pcsx2#597]
I want to add some disabled memory hacks (with permission) to Nocturne, DDS1 and DDS2.
One was created by  [Ninto55 on reddit/megaten](http://www.reddit.com/r/Megaten/comments/36ex0m/ps2_smt_emulator_shadow_patches/), it's a adaption of the same (commented) hacks already there by Altimor that fix or disable (i can't remember which, i only know that leaving as it is introduces artifacts in cutscenes) the player shadow in Nocturne and DDS1;  but for DDS2.

The others are slightly more interesting. They're by [Altimor again also on reddit/megaten](http://www.reddit.com/r/Megaten/comments/35ixub/pcsx2_progressive_scan_mode_patches_for_nocturne/), and they're progressive mode patches for all 3 games (versus the interlaced mode). This makes image quality better in pcsx2 because slightly less aliasing ([you really have to zoom in to see it though](https://dl.dropboxusercontent.com/s/gjdk548m8k8chmk/Screenshot-2015-05-10-18.27.gif)). On the other hand, i think the videos looks crisper with it - at least the conception video in Nocturne - probably because the interlacing shader i used doesn't like them.

What was i wondering is how is it going to be reviewed in the pull request? cheats_ws.zip is a binary file. Is there any other repository with the actual files where i should open pull request? Or would you prefer i just show you gists with the original and the modified? It's just adding stuff to the end of the files anyway, not modifying.

**Comment by gregory38** [comment]
Just post them here or in the forum. And someone will include them.

**Comment by i30817** [comment]
They're all linked in this report. Just copy them over then.

**Comment by i30817** [comment]
Ok, this this is the new (not already there) hack for DDS2 US version (D382C164.pnach)
```
//Optional shadow alpha hack
//comment=Shadow Override (Krisan Thyme & Ninto55)
//patch=1,EE,20387C60,extended,00000000
//patch=1,EE,20387C64,extended,00000000
//patch=1,EE,20387C68,extended,00000000
//patch=1,EE,20387C6C,extended,00000000
//patch=1,EE,20387C70,extended,00000000
//patch=1,EE,20387C74,extended,00000000
//patch=1,EE,20387C78,extended,00000000
//patch=1,EE,20387C7C,extended,00000000
//patch=1,EE,20387C80,extended,00000000
//patch=1,EE,20387C84,extended,00000000
//patch=1,EE,20387C88,extended,00000000
//patch=1,EE,20387C8C,extended,00000000
//patch=1,EE,20387C90,extended,00000000
//patch=1,EE,20387C94,extended,00000000
//patch=1,EE,20387C98,extended,00000000
//patch=1,EE,20387C9C,extended,00000000
//patch=1,EE,20387CA0,extended,00000000
//patch=1,EE,20387CA4,extended,00000000
//patch=1,EE,20387CA8,extended,00000000
//patch=1,EE,20387CAC,extended,00000000
//patch=1,EE,20387CB0,extended,00000000
//patch=1,EE,20387CB4,extended,00000000
//patch=1,EE,20387CB8,extended,00000000
//patch=1,EE,20387CBC,extended,00000000
//patch=1,EE,20387CC0,extended,00000000
//patch=1,EE,20387CC4,extended,00000000
//patch=1,EE,20387CC8,extended,00000000
//patch=1,EE,20387CCC,extended,00000000
//patch=1,EE,20387CD0,extended,00000000
//patch=1,EE,20387CD4,extended,00000000
//patch=1,EE,20387CD8,extended,00000000
//patch=1,EE,20387CDC,extended,00000000
```
These are the progressive mode patches:
Nocturne (E8FCF8EC.pnach)
```
//comment=Progressive Mode (Altimor)
//patch=1,EE,002AA1B4,word,00000000 // NOP out old interlaced field switch
//patch=1,EE,002ADBE0,word,00000000 //prevent effects from getting misaligned when entering menus
//patch=1,EE,002C81D4,word,24110000 // addiu $s1, 0, 0x00 Patch sceGsResetGraph arguments to set 480p
//patch=1,EE,002C81D8,word,24120050 // addiu $s2, 0, 0x50
//patch=1,EE,002C81DC,word,24020001 // addiu $s3, 0, 0x01
```

DDS1 (D7273511.pnach)
```
//comment=Progressive Mode (Altimor)
//patch=1,EE,002D1558,word,00000000 // NOP out old interlaced field switch
//patch=1,EE,002D5060,word,00000000 //prevent effects from getting misaligned when entering menus
//patch=1,EE,002EFD7C,word,24110000 // addiu $s1, 0, 0x00 Patch sceGsResetGraph arguments to set 480p
//patch=1,EE,002EFD80,word,24120050 // addiu $s2, 0, 0x50
//patch=1,EE,002EFD84,word,24020001 // addiu $s3, 0, 0x01
```

DDS2 (D382C164.pnach)
```
//comment=Progressive Mode (Altimor)
//patch=1,EE,0032A408,word,00000000 // NOP out old interlaced field switch
//patch=1,EE,0032DF10,word,00000000 //prevent effects from getting misaligned when entering menus
//patch=1,EE,00348C24,word,24110000 // addiu $s1, 0, 0x00 Patch sceGsResetGraph arguments to set 480p
//patch=1,EE,00348C28,word,24120050 // addiu $s2, 0, 0x50
//patch=1,EE,00348C2C,word,24020001 // addiu $s3, 0, 0x01
```

**Comment by avih** [comment]
devina40 manages and moderates these patches and archive at this forum thread: http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches and we update the repo with a new archive once in a while.

Please post the patches to that thread, and they'll get to the repo at the next archive update.

**Comment by i30817** [comment]
I don't have a account and i'm not planning on getting one. Could you just drop a link there for this bug?

**Comment by avih** [comment]
Posted to the forum: http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=463230#pid463230

Please follow up on your own, and register to the forum if you need to have further conversation with Devina.

Thanks.
