### ISSUE TITLE
[BUG]: Futurama -- Black rectangles in Software mode

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#5976]
### Describe the Bug

When in Software mode, the player is followed by black rectangles that extend all the way across the world in all 4 directions. The same does not occur in Hardware mode.

Picture and GS dump:
[gs_20220426231954_Futurama _NTSC-U__SLUS-20439.zip](https://github.com/PCSX2/pcsx2/files/8566709/gs_20220426231954_Futurama._NTSC-U__SLUS-20439.zip)
![gs_20220426231954_Futurama _NTSC-U__SLUS-20439](https://user-images.githubusercontent.com/11655762/165386992-c926965b-0f59-47d2-b67d-c5d09e72e56d.png)
 
For those trying this dump out, you'll notice that the player is also flashing black in both Software and Hardware rendering. This **does not** occur inside the actual game. No idea why it does this.

This issue has likely been there since forever, just unobserved all this time. It persists on 1.6 and 1.4 as well.

### Reproduction Steps

Just play the game in Software mode.

### PCSX2 Revision

1.7.2664

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by refractionpcsx2** [comment]
I checked back to 1.7.2447 and even 32bit and it was still busted, if that narrows it down any lol

**Comment by RedDevilus** [comment]
Had to add the .gs extension back but that's beside the point. It kinda looks like Hardware mode that needs Disable Partial Invalidation but here it is in software mode, quite baffling.

**Comment by refractionpcsx2** [comment]
HW mode is fine, it's just the dump glitching.

**Comment by coornio** [comment]
Added note that this same software mode bug can be reproduced in hardware mode by enabling the Preload Frame Data hack. Seems like there's some relationship here.

**Comment by prafullpcsx2** [comment]
Tried very hard but failed to replicate this. You either have broken disc, broken drivers or using some settings that break pcsx2.

**Comment by refractionpcsx2** [comment]
Yeah absolutely nobody has been able to reproduce it, except you, coornio :P

**Comment by coornio** [comment]
Well I don't know what to say then. I even went ahead and checked the CRC32 and SHA-1 to redump and it matches, so it's not a bad dump. I've tried all the clamping/rounding modes, even interpreter and EE cache, still no differences.

What do you suggest I try that might provide some clues into this issue?

**Comment by coornio** [comment]
Alright, screw this. I tested this yesterday by first doing a clean install of the latest nvidia driver (was on 511 something) AND a clean qt build, just in case. The issue was there. Fast forward, I put the computer to sleep, and as I happen to talk to Prafull on discord about it and offer to stream it, it no longer happens.

I might just be cursed?
