### ISSUE TITLE
[BUG]: GDK assertion failure and hang when opening general settings

### ISSUE THREAD

**Issue by jclc** [PCSX2/pcsx2#5977]
### Describe the Bug

Process has to be killed externally for it to close.

![image](https://user-images.githubusercontent.com/10243558/165441038-88ec2376-49ba-43b1-b04f-7ccabec67e74.png)

### Reproduction Steps

Click on "General Settings".

### Expected Behavior

General settings opened.

### PCSX2 Revision

1.7.2648 Flatpak build

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Pop_OS 22.04

**Comment by tellowkrinkle** [comment]
We don't maintain flatpak builds.  Does our appimage have the same issue?

**Comment by kenshen112** [comment]
Or the PPA since you mentioned you were on pop?

**Comment by tellowkrinkle** [comment]
PPA should work too, though I'd like to confirm this issue is fixed on the appimage
(Since it definitely *was* an issue with the appimage at some point)

**Comment by jclc** [comment]
Works with Appimage and the PPA, both the latest and version 1.7.2648. Thanks! It could also be an issue with the Flatpak runtime being used.

Much prefer to use Flatpak over Appimage, but the PPA will do for now.
