### ISSUE TITLE
GAMEDB: Problem with the SoftwareRendererFMVHack setting 

### ISSUE THREAD

**Issue by abogard** [PCSX2/pcsx2#5998]
### Describe the Bug

I was trying today the game Rygar. This game has the SoftwareRendererFMVHack setting enabled. When the game switches to SW renderer it never goes back to HW renderer after the FMV. I tried another game that uses the setting (Silent Hill 3 NTSC) and the same happens. I searched the github but didn't find any report of this, I don't know if it's me doing something wrong. If you press F9 the game goes into HW mode again but it never goes back to SW when an FMV plays. I used the OpenGL renderer in case that is relevant and I have the latest nightly release

### Reproduction Steps

Just play any game that has this setting enabled in the GameDB and confirm this behavior 

### Expected Behavior

Switch to software when an FMV plays and then go back to HW when the actual game starts or continues

### PCSX2 Revision

1.7.2684

### Operating System

Windows 10 (64bit)

### CPU

i5-4690

### GPU

NVIDIA GeForce GTX 1070

### GS Settings

3x internal resolution

### Emulation Settings

All defaults

**Comment by refractionpcsx2** [comment]
I have added some stuff to fix up the behaviour in the above linked PR, if you could test it once built, that'd be good.
