### ISSUE TITLE
[GSdx] San Andreas radiosity bug

### ISSUE THREAD

**Issue by aap** [PCSX2/pcsx2#600]
GTA San Andreas uses a post processing effect called radiosity that has always been buggy in pcsx2. This is a description of the effect and why the bug happens.
Currently the game looks like this:
In d3d9 hw (disabled via CRC my default):
![bug d3d9 hw](http://i.imgur.com/YjTti8l.png)
and sw:
![bug sw](http://i.imgur.com/3Muji9o.png).
As you can see the upper left quarter of the frame is streched and blended somehow onto the current frame. Why is this?

First of all, for those who want to play with the effect (if you don't, skip this paragraph) the function that renders the effect is called `CPostEffects::Radiosity(int intensityLimit, int filterPasses, int renderPasses, int intensity)` and can be found in the PAL version (SLES_525.41) at `0x517B80`. It is called from three different places inside `CPostEffects::Render()` namely `0x515698`, `0x515990` and `0x5159AC`, but normally from `0x515990`. Some global variables that control the effect are four ints starting at `0x668664` named `CPostEffects::m_RadiosityFilterPasses`, `CPostEffects::m_RadiosityRenderPasses`, `CPostEffects::m_RadiosityIntensityLimit`, `CPostEffects::m_RadiosityIntensity`. These (except `IntensityLimit`) are passed to `Radiosity()` at the call at `0x515990`.

Now a description of the effect. It is drawn in three steps:
1. Render a downsampled version of the current frame onto a texture (this is where the bug happens, see below)
2. Darken this downsampled frame with the impossible blend mode Dst = 2*Dst - Src, where Src is a monochrome gray (the first argument, `intensityLimit`). The blend mode is of course the reason it looks different in hw and sw mode.
3. Draw (add) this darkened frame `renderPasses` times onto the current frame with `intensity` as a multiplier.

Now an explanation of the first step where the bug happens.
The argument `filterPasses` says how often the dimensions of frame will be halved to get the downsampled frame. This is done by drawing quads (sprites) in the upper left corner where each one has half the dimensions of the last. BUT, not only are the vertex coordinates halved but also the texture coordinates. That would of course only redraw part of the last quad and not make any visible difference, UNLESS the texture changes between quads. But this can only happen if the same raster data is used as both current draw target and texture. That's precisely what happens and what GSdx can't handle at the moment.

Some pictures to explain what's happening at the moment and what should be happening (on the left I have the framebuffer and in red is the quad that is drawn, on the right is the texture used and in green the part of it that's used as a texture for the red quad):
First a quad with halved dimensions is drawn onto the framebuffer/texture:
![first filter pass](http://i.imgur.com/vQ7n4j2.png)
Now on the real hardware the texture changes of course and another downsampled frame is drawn:
![second filter pass correct](http://i.imgur.com/VeyQwFb.png)
In pcsx2 however the texture does *not* change so the left frame is wrong.
![second filter pass bug](http://i.imgur.com/hcV0dZy.png)
The section in red is the part of the texture that's blended onto the frame in the end, so you clearly see how the bug in pcsx2 happens.

Note that those downsampling quads are all in one GS packet so for the hw renderer you probably have to split up the geometry and update the texture between calls or something like that.
I'm very glad the bug is finally found and I hope you guys can fix it.

**Comment by gregory38** [comment]
Could you test the latest hack `UserHacks_AutoFlush = 1`. It will impact badly but maybe not too much.

**Comment by aap** [comment]
Perfect! upscaling works and performance doesn't seem to be too different on my machine either. I think this can be closed now.

**Comment by FlatOutPS2** [comment]
![gta sa auto flush](https://cloud.githubusercontent.com/assets/15942346/18609197/74d6166a-7cfc-11e6-9464-420569f9899f.png)

Auto Flush improves the situation, but it's still a little off to the up and left. It's not very noticeable on SW mode, but it's very clear when using higher than native scaling in HW mode.

The old CRC hack for HW mode is still active, so it probably won't get noticed by many users.

**Comment by gregory38** [comment]
Hum need to check HPO. And potentially the new HPO implementation.

**Comment by FlatOutPS2** [comment]
Sorry, forgot to mention HPO didn't have any effect on it.

**Comment by aap** [comment]
It looks accurate to me. Of course upscaling may increase the offset/scaling of the radiosity pass.
