### ISSUE TITLE
BUG: Flicker on Crash Bandicoot: WoC  using GL/VK (NVIDIA)

### ISSUE THREAD

**Issue by JordanTheToaster** [PCSX2/pcsx2#6006]
### Describe the Bug

In Crash Bandicoot WoC you can observe flickering squares across the screen using an Nvidia graphics card with Vulkan OpenGL and DirectX12, DirectX11 seems to behave normally.

https://youtu.be/yyw0DXFnFHw

### Reproduction Steps

Load up either GS dump provided and enable Frame Buffer Conversion and Preload Frame Data with CRC set to none at native using DX12 Vulkan or OpenGL and observe the flickering on screen.

[CBWoCFlickering.zip](https://github.com/PCSX2/pcsx2/files/8607859/CBWoCFlickering.zip)

[CBWoCFlickering2.zip](https://github.com/PCSX2/pcsx2/files/8607955/CBWoCFlickering2.zip)

### Expected Behavior

The game not to flicker and look correct

### PCSX2 Revision

v1.7.2689

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

RTX 2060 Super

**Comment by coornio** [comment]
Correction. Reproduction requires the following.

Native resolution.
Vulkan/OpenGL/D3D12 renderer. D3D11 doesn't blend well enough to get the fog working in the first place. 
CRC Hack Level: None.
Manual Hack: Frame Buffer Conversion.

Preload Frame Data has some sort of effect on where the fog line starts but doesn't seem to be related to the bug itself. 

https://user-images.githubusercontent.com/11655762/166444426-a5332651-14af-4927-b658-439970c1ba82.mp4

**Comment by dio-gh** [comment]
I cannot reproduce this on my laptop GTX 1060, using an older driver (497.29).

**Comment by dio-gh** [comment]
@coornio could you tell your GPU model?

**Comment by tellowkrinkle** [comment]
Metal / Radeon Pro 5600M
<img width="976" alt="image" src="https://user-images.githubusercontent.com/3315070/166562153-0bffaaf2-b6c0-4d0b-8ab4-c1755e3c4a03.png">
Metal / Intel UHD 630
<img width="976" alt="image" src="https://user-images.githubusercontent.com/3315070/166562205-09115f79-e730-4bc3-9cac-1d90cf60b260.png">
