### ISSUE TITLE
[BUG]: Graphic bug in Guiter Hero's (USA) score after gain the X2 multiplier

### ISSUE THREAD

**Issue by Shideravan** [PCSX2/pcsx2#6019]
### Describe the Bug

After you gain the X2, the score graphics broken up.

### Reproduction Steps

Play some song. After hitting some notes and gaining the x2 multiplier, the score brokes

### Expected Behavior

The score doesn't broke and remain like this 
![image](https://user-images.githubusercontent.com/12163923/167035440-a8314b39-7d02-4cf4-a050-41800b0bd11c.png)
![image](https://user-images.githubusercontent.com/12163923/167034168-f0aae2b4-9017-4fcc-8142-3ff4e48a8349.png)

### PCSX2 Revision

v.1.7.2696

### Operating System

Windows 10 (64bit)

### CPU

i7-4790

### GPU

GTX 2070

### GS Settings

Hack is off, no osd, no recording
![image](https://user-images.githubusercontent.com/12163923/167034738-8b9e0be2-bc89-4985-87a5-6b30367be6fc.png)
![image](https://user-images.githubusercontent.com/12163923/167034779-36c3f597-4ede-486d-9df9-ea50999c3b34.png)
![image](https://user-images.githubusercontent.com/12163923/167034826-3c0ef7c7-5d56-474b-bd95-69f6e3ed38ee.png)

### Emulation Settings

2 - Secure (default) preset, with <TVU on

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/12163923/167034570-7b794a06-b688-4577-8de5-fbbae478ebb9.png)

### Logs & Dumps

[Uploading snaps.zip…]()

**Comment by F0bes** [comment]
Does it happen with the internal resolution set to native?

**Comment by refractionpcsx2** [comment]
Already reported here https://github.com/PCSX2/pcsx2/issues/3692#issuecomment-729682717

we're keeping track of it in the z-fighting thread there. Thanks for the report
