### ISSUE TITLE
[BUG]: Pixbuf Installation Broken. (Crashes)

### ISSUE THREAD

**Issue by IgLocoXD** [PCSX2/pcsx2#6024]
### Describe the Bug

`(pcsx2:14507): GdkPixbuf-WARNING **: 22:42:05.329: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.`

### Reproduction Steps

1. Extract the Appimage with `PCSX2.AppImage --appimage-extract`
2. Open the `AppRun-patched`

### Expected Behavior

I was extracting the PCSX2 Appimage because of some Python Discord Rich Precense for PCSX2. When i do so and open the "AppRun-patched"
Even trying running the command happens this;
`bash: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache: No such file or directory `
This thing triggers a bug that make every thing that i open (including starting emulation) a crash.

### PCSX2 Revision

v1.7.2705

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

OpenSuse Tumbleweed

**Comment by refractionpcsx2** [comment]
Does the app image work without you trying to patch it for discord rich presence?

**Comment by IgLocoXD** [comment]
> Does the app image work without you trying to patch it for discord rich presence?

Yep, but i need to extract the AppImage because the Discord Rich Presence doesnt work, also, even without patching the bug happens.

**Comment by refractionpcsx2** [comment]
Okay, I'm just trying to work out how this is our problem? What we provide works, but your attempts to used a 3rd party patch doesn't work.  

I would suggest you go to the author of the patch and get them to fix it.

**Comment by IgLocoXD** [comment]
> Okay, I'm just trying to work out how this is our problem? What we provide works, but your attempts to used a 3rd party patch doesn't work.
> 
> I would suggest you go to the author of the patch and get them to fix it.

Eeeh, actually, the "AppImage-Patched" is not from that Python btw. Is from the original extracted AppImage.

**Comment by F0bes** [comment]
The point of the AppImage is to provide a working environment for the application to run. As shown here, if your environment isn't set up correctly, taking it out of the AppImage wont work. Please use the PCSX2 from your package manager (if applicable) or compile from source and patch it then.

**Comment by IgLocoXD** [comment]
> The point of the AppImage is to provide a working environment for the application to run. As shown here, if your environment isn't set up correctly, taking it out of the AppImage wont work. Please use the PCSX2 from your package manager (if applicable) or compile from source and patch it then.

I could compile from source, but how i do that?

**Comment by kenshen112** [comment]
What distro are you on?

**Comment by kenshen112** [comment]
This is a bit specific towards Ubuntu and Apt. But should give the right idea https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#how-to-compile-pcsx2-in-2021-ubuntu-2004-64bit

**Comment by IgLocoXD** [comment]
> This is a bit specific towards Ubuntu and Apt. But should give the right idea https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#how-to-compile-pcsx2-in-2021-ubuntu-2004-64bit

Im gonna try it, but i hope someone have the zypper ones.
