### ISSUE TITLE
[BUG/SW]: Regression - Hokuto no Ken/Guilty Gear XX ACP/Sengoku Basara X - Bottom is blurry

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#6026]
### Describe the Bug

Arc System Works 2D games need the "Screen offset" option in order to display the bottom of the screen.  Since [v1.7.2673](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2673), a regression appears and the bottom is extra blurry. [v1.7.2672](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2672) works perfectly so I think the [PR 5981](https://github.com/PCSX2/pcsx2/pull/5981) is the cause.

All of the Arc System 2D games I tried exhibit this issue - HNK/Guilty Gear XX ACP/Sengoku Basara X

HW works great though.

### Reproduction Steps

Launch it, check the main menu or ingame.

### Expected Behavior

No blurry bottom

### PCSX2 Revision

v1.7.2711

### Operating System

Windows 11

### CPU

Ryzen 5600x

### GPU

AMD 6800

### GS Window Screenshots

Software without the "Screen Offset" option : 

![gs_20220507142052_Hokuto no Ken _NTSC-J__SLPM-66660](https://user-images.githubusercontent.com/47425204/167254621-d8dd9f06-c259-4710-9e47-b75bef3e3bb4.png)

Software with the "Screen Offset" option : 

![gs_20220507142041_Hokuto no Ken _NTSC-J__SLPM-66660](https://user-images.githubusercontent.com/47425204/167254651-767fade7-a912-4145-8188-06693ed9901f.png)

Hardware with the "Screen offset" option : 

![gs_20220507142023_Hokuto no Ken _NTSC-J__SLPM-66660](https://user-images.githubusercontent.com/47425204/167254659-823dfad3-04b0-4402-ad5a-fa1928f9fec6.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8645154/snaps.zip)

**Comment by refractionpcsx2** [comment]
#6027 will fix this, I also made it so you no longer require to use screen offsets (even though too much of the picture is now showing)

**Comment by Immersion95** [comment]
It now happens again in Guilty Gear XX ACP only, it was solved then. Only appears in SW, not in HW.

**Comment by Immersion95** [comment]
It now works
