### ISSUE TITLE
[BUG]: AppImage fails to launch BIOS or ISO 

### ISSUE THREAD

**Issue by AlfredoRodda** [PCSX2/pcsx2#6030]
### Describe the Bug

PCSX2 AppImage launches successfully. Upon attempting to launch the BIOS or any Game results in the error. 

`(p) STL Runtime Error: GS failed to open.(thread:EE Core)`

Setting the renderer as OpenGL, Vulkan, or Software makes no difference and results in the same error.  I am able to launch other apps/games such as RPCS3 AppImage using both the OpenGL or Vulkan renderer.

Below is the PCSX2 emuLog.

```
PCSX2 Nightly - v1.7.2717 Compiled on May  7 2022
Savestate version: 0x9a2c0000

Host Machine Init:
	Operating System =  
	Physical RAM     =  15911 MB
	CPU name         =  AMD Ryzen 7 1700 Eight-Core Processor
	Vendor/Model     =  AuthenticAMD (stepping 01)
	CPU speed        =  3.900 ghz (16 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 7ed8320b
	x86EFlags        =  2fd3fbff

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	SSE4a 

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...
	(CdvdSource) HotSwapping CDVD source types from ISO to NoDisc.
HLE Host: Set 'host:' root path to: /

Patches: No CRC found, using 00000000 instead.
Vsync is ON
eglGetDisplay() failed: 12288
Failed to create any GL context
Failed to acquire host display
GS failed to open.
(p) STL Runtime Error: GS failed to open.(thread:EE Core)
```

### Reproduction Steps

Launch the PCSX2 AppImage

Attempt to launch the BIOS or an ISO.

### Expected Behavior

Ability to launch BIOS or ISO

### PCSX2 Revision

v1.7.2717

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

openSUSE Tumbleweed

**Comment by refractionpcsx2** [comment]
I'm not a linux person so I might be barking up the wrong tree, but do you have EGL installed? we recently removed it from the appimage in favour of the system package so resolve some compatibility issues between distro versions.

**Comment by AlfredoRodda** [comment]
No worries! Are you referring to the package Mesa-libEGL1? If so, then yes it is installed.

Package description

```
Mesa-libEGL1 - EGL API implementation

This package contains the EGL native platform graphics interface library. EGL provides a platform-agnostic mechanism for creating rendering surfaces for use with other graphics libraries, such as OpenGL|ES and OpenVG.
This package contains modules to interface with the existing system GLX or DRI2 drivers to provide OpenGL via EGL. The Mesa main package provides drivers to provide hardware-accelerated OpenGL|ES and OpenVG support.
```

**Comment by refractionpcsx2** [comment]
Funny enough I just looked up the EGL error and found this

>  12288 is decimal for hex 0x3000 which is equal to EGL_SUCCESS. 

so it's very strange.

**Comment by RedDevilus** [comment]
> Funny enough I just looked up the EGL error and found this
> 
> > 12288 is decimal for hex 0x3000 which is equal to EGL_SUCCESS.
> 
> so it's very strange.

Task failed successfully. 🤧

**Comment by ukbeast** [comment]
looking into `journalctl -b -r`

```
at-spi-bus-launcher[2115]: dbus-daemon[2115]: Activating service name='org.a11y.atspi.Registry' requested by ':1.51' (uid=1000 pid=26750 comm="pcsx2")

at-spi2-registr[26796]: AT-SPI: Cannot open default display

 at-spi-bus-launcher[26796]: Invalid MIT-MAGIC-COOKIE-1 key

```
Not sure if this helps or not.

**Comment by ukbeast** [comment]
Just tried the unofficial https://github.com/flathub/net.pcsx2.PCSX2 version and I have no issue.

**Comment by ukbeast** [comment]
@AlfredoRodda @refractionpcsx2 

Solved the issue with a workaround.
`apprun-hooks/app-variables.sh` line `if [[ $(ldconfig -p | grep libwayland-client | wc -l) -lt 1 ]]; then
`
`ldconfig` requires absolute path `/usr/sbin/ldconfig` for user. (ldconfig is not found error)

export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin in bash and run appimage in terminal to solve this, or add to .bashrc

**Comment by AlfredoRodda** [comment]
@ukbeast @refractionpcsx2 

Thanks, I can confirm this workaround does allow for the BIOS or an ISO to launch without error.

**Comment by refractionpcsx2** [comment]
Tagging all our linuxy folks @xTVaser @arcum42 @tellowkrinkle and @stenzek since you've done a lot of messing with wayland.

**Comment by AlfredoRodda** [comment]
Just a small update as of PCSX2 v1.7.3058. 
Qt AppImage - No error.
wxWidgets AppImage - Original error is still present but workaround still works.

**Comment by refractionpcsx2** [comment]
Thanks, we're not concerned about WX as it's being dropped.

**Comment by AlfredoRodda** [comment]
Your welcome, should this issue be closed then?
