### ISSUE TITLE
[BUG]: .hack//INFECTION - Minimap flickering and loading wrong sprite(s)

### ISSUE THREAD

**Issue by hasnogame** [PCSX2/pcsx2#6034]
### Describe the Bug

While in a dungeon after moving from the first room to the second and onward the minimap will flicker rapidly. As you traverse the dungeon it will eventually load in an incorrect and whole spritesheet(s) in the place of the minimap's sprite.

This issue first occurs in build [v1.7.2687](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2687). I could not reproduce this issue in the builds prior to it ([v1.7.2682](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2682) - [v1.7.2686](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2686)). This issue exists in the current build which at the time of writing is [v1.7.2721](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2721).

All builds tested were tested using default settings.

### Reproduction Steps

- Run game using default settings
- Start new file
- Proceed through intro tutorial, the visual glitches should occur once you log into The World and the minimap is displayed in the top right
- If not, proceed with the tutorial until you reach the dungeon. After proceeding through to the second room the bug should occur.

### Expected Behavior

The minimap does not flicker while in a dungeon and it fully loads the correct sprite.

### PCSX2 Revision

v1.7.2721

### Operating System

Windows 11

### CPU

Intel Core i5 2310 @ 2.90GHz

### GPU

XFX Radeon RX 580 8GB

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/42306887/167285590-d74aae1f-bb1a-4cb9-9427-4d997e7a4380.png)

https://user-images.githubusercontent.com/42306887/167286517-338376a7-1da9-4bff-9774-9ad744480082.mp4

https://user-images.githubusercontent.com/42306887/167286870-d8c7bc13-ddae-4f16-9b32-9b8bf9d516d2.mp4

### Logs & Dumps

Here is a save state which demonstrates the issue. Walk forward into the next room and watch the bottom end of the minimap.

[v1.7.2787sstate.zip](https://github.com/PCSX2/pcsx2/files/8646529/v1.7.2787sstate.zip)

**Comment by refractionpcsx2** [comment]
Can you please make a GS Dump (Shift + F8, then the file will be in your "snaps" folder) and upload it here or somewhere, it'll be easier for us to look at as we don't need to own the game in or der to see it.

Thanks.

**Comment by hasnogame** [comment]
Here you go:

[gs_20220508035611_.hack__Infection Part 1 _NTSC-U__SLUS-20267.gs.zip](https://github.com/PCSX2/pcsx2/files/8646565/gs_20220508035611_.hack__Infection.Part.1._NTSC-U__SLUS-20267.gs.zip)

**Comment by refractionpcsx2** [comment]
Thanks, I'll take a look in a couple of hours.

Just to confirm, you could see the error when you did the shift + f8 yes?

**Comment by hasnogame** [comment]
That's right, error was visible on-screen.

**Comment by refractionpcsx2** [comment]
Perfect

**Comment by refractionpcsx2** [comment]
Should be fixed in the linked PR
