### ISSUE TITLE
[BUG]: Some ingame/menu entries in compatibility list are wrong

### ISSUE THREAD

**Issue by Shideravan** [PCSX2/pcsx2#6038]
### Describe the Bug

I'm not sure the best form to report them, but some games marked as ingame/menu in compatibility list, are now *playable* in the most recent dev build. They include:

   * Spider-Man 3	🇺🇸   SLUS-21552   
![image](https://user-images.githubusercontent.com/12163923/167304688-f48862f9-6946-4569-954d-ae93400101d1.png)

   * Spider-Man 3	🇪🇺   SLES-54723
![image](https://user-images.githubusercontent.com/12163923/167304659-bda70935-5699-418a-87df-32df32265092.png)

   * True Crime - Streets of L.A.	🇺🇸   SLUS-20550   
![image](https://user-images.githubusercontent.com/12163923/167304750-fedf0dde-7c49-43e0-b5c9-8c526285ea1b.png)

   * True Crime - Streets of L.A.	🇪🇺   SLES-51754
![image](https://user-images.githubusercontent.com/12163923/167304723-4f617f57-fabb-4dae-bf73-4d8ed9e6ca08.png)

   * Zone of the Enders - The 2nd Runner	🇪🇺   SLES-51113
![image](https://user-images.githubusercontent.com/12163923/167304775-ff74a5cb-1889-4742-a46e-595e2f0b12b5.png)

All these games are now in *playable/perfect* status in the most recent dev builds.

### Reproduction Steps

Just run these games

### Expected Behavior

The compatibily list in the official website reflects the true status of these entries

### PCSX2 Revision

v.1.7.2721

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
True Crime - Streets of L.A.  isnt playable , it still has the possibility to crash see issue #4070

**Comment by Mrlinkwii** [comment]
if you want to update the compat rating  please post on the forum in the related  section :)

**Comment by James-Devil** [comment]
Spider-Man 3 is utterly broken in Hardware and 50% Speed in Software after the first stage.
