### ISSUE TITLE
[BUG]: PCSX2 crashes on socket use in network configuration with flatpak

### ISSUE THREAD

**Issue by Kevman95** [PCSX2/pcsx2#6039]
### Describe the Bug

https://kevman95.com/i/2022-05-07_09-12-25_6bd13bd6-51bc-4c9a-af61-ed6ccecda582.mp4 

Upon setting the network configuration to "socket" and attempting to boot the ISO file for the game ratchet & clank: up your arsenal (doesn't matter which is selected honestly, tested with another) the application just closes.

### Reproduction Steps

Use the flatpak version of PCSX2
Configure the network settings to use "socket".
Boot any game ISO

### Expected Behavior

I expected it to work and boot into the game to configure network settings for online play.

### PCSX2 Revision

PCSX2 1.7.2678

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux/SteamOS

**Comment by Kevman95** [comment]
Providing a update, booting the games ELF file allows for any game to continue booting as normal. The process seems to only crash when you are booting a ISO. So this does seem like a bug.

**Comment by TheLastRar** [comment]
Thanks for the report, this should be fixed by https://github.com/PCSX2/pcsx2/pull/6051

if you want to test the fix, you should be able to use the appimage action build (found in the checks tab in the linked PR).
