### ISSUE TITLE
[REGRESSION]: Corrupted menu screen in Dark Cloud

### ISSUE THREAD

**Issue by janitor-raus** [PCSX2/pcsx2#6043]
### Describe the Bug

The ingame menu screen in Dark Cloud done got messed up:

![gs_20220509160224_Dark Cloud _NTSC-U__SCUS-97111](https://user-images.githubusercontent.com/11655762/167418508-c92e407d-1158-4bd9-8784-04e8bd0cee4c.png)
 
This regression is caused by the following PR: #5955 and can be observed in 1.7.2682 and up. Multi-frame dump below. Held a bit longer than I wanted :P 

[gs_20220509162341_Dark Cloud _NTSC-U__SCUS-97111.zip](https://github.com/PCSX2/pcsx2/files/8652095/gs_20220509162341_Dark.Cloud._NTSC-U__SCUS-97111.zip)

### Reproduction Steps

Boot the game up and go to the ingame menu. 

### PCSX2 Revision

1.7.2724

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by stenzek** [comment]
Thanks for the bisect. Bit of a nasty one, it was an edge case I didn't consider with the HW moves. https://github.com/PCSX2/pcsx2/pull/6045 should fix it.
