### ISSUE TITLE
[BUG]: Naruto Uzumaki Chronicles 2

### ISSUE THREAD

**Issue by WilliamVaz** [PCSX2/pcsx2#6053]
### Describe the Bug

Hi
The game "naruto uzumaki chronicles 2" (maybe 1 as well) worked perfectly on emulator 1.6 and some versions 1.7
But in newer versions of the emulator, the game freezes at various times.
Where can I report this error to get it resolved?
Interestingly it's a similar problem when the game is played on PS3 via emulation (no fix)

### Reproduction Steps

Play the game → In "mission mode" → select a mission (functional example: MISSION RANK A "gathering intelligence") → The game will freeze at the Loading screen

Another bug: sometimes the game freezes when I'm playing with characters that make the camera move fast. example: playing with Guy Sensei, when aiming at the enemy (L1) and using the R1 jutsu, the game may freeze

----
remembering that this did not happen in previous versions of the emulator, only in the most recent ones (I hope it doesn't happen in version 1.8)

### PCSX2 Revision

Any version of the latest

### Operating System

Windows 10 (64bit)

### CPU

ryzen 3600

### GPU

gtx 1650

**Comment by refractionpcsx2** [comment]
Can you put an actual version number? "Latest" doesn't help me if I look at this in 3 years time or whenever we look at it. Also can you put in any non-default settings to your graphics or emulator config.

Would also be good if you could post an emulog.txt from your PCSX2/logs folder after the hang occurs.

Thanks

**Comment by WilliamVaz** [comment]
1.7.2702

**Comment by refractionpcsx2** [comment]
I'm glad I said now, because that isnt even "latest" as of now.

**Comment by refractionpcsx2** [comment]
hmm can you try the OPH Flag Hack gamefix? Bleach Blade Battlers (which may have something in common? idk) has hangs and requires that.

**Comment by WilliamVaz** [comment]
Thank you very much. I activated the "OPH Flag Hack" and the game is working normally (it seems)
curiosity: this Naruto, Bleach and Wizardry are from the same developer.
