### ISSUE TITLE
Star Ocean, conservative buffer allocation off causes black screen on initial load file screen. 

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#6054]
### Describe the Bug

When conservative buffer allocation is unchecked when pressing continue to load your save file the screen is black, It's functional and working you just can't see anything. Unchecking it instantly fixes the issue. This also happens at native resolution when the setting is grayed out. I use to run this game always with it unchecked and it was fine because now having it enabled causes this weird graphical bugs randomly. See screenshot. 

### Reproduction Steps

Run the game at native res or at a higher res with the option unchecked

### Expected Behavior

No black screen when loading the save file.

### PCSX2 Revision

Nightly v1.7.2731

### Operating System

Windows 10 (64bit)

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Opengl default. 

### Emulation Settings

Default

### GS Window Screenshots

![Screenshot (17)_LI](https://user-images.githubusercontent.com/12180630/167696201-7e0d8136-3d62-4ada-bf0e-5edff53b4807.jpg)

**Comment by lightningterror** [comment]
Can you post a gsdump?

**Comment by BParks21** [comment]
I always forget is there a hotkey for that?

**Comment by BParks21** [comment]
Also real quick note here, something I just discovered. It only happens at native resolution if conservative buffer allocation is unchecked before enabling native resolution. Which is strange to me. If it's left checked and then native res is enabled and the game is started the black screen does not occur. Also this game has a progressive screen mode so triangle and X are required to be held down on boot to enable it otherwise the game looks blurry. If you guys are unaware.

**Comment by lightningterror** [comment]
> I always forget is there a hotkey for that?

https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by BParks21** [comment]
> > I always forget is there a hotkey for that?
> 
> https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
[Desktop.zip](https://github.com/PCSX2/pcsx2/files/8664109/Desktop.zip)

**Comment by lightningterror** [comment]
Can you take another dump from the actual scene that has the issue?

**Comment by BParks21** [comment]
Oh well I took the dump where the screen is black. I can take a dump where the graphical bug occurs.

**Comment by BParks21** [comment]
Here is the new dump
[snaps.zip](https://github.com/PCSX2/pcsx2/files/8664334/snaps.zip)

**Comment by lightningterror** [comment]
Can you post all your gs settings?

**Comment by BParks21** [comment]
Here ya go. The other tabs have not been touched. Heres another dump I took at native res. It's less severe at native. But yeah this bug doesn't occur with the conservative unchecked but then you get that initial black screen on the first save file selection screen. 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/8664429/snaps.zip)
![Screenshot (19)](https://user-images.githubusercontent.com/12180630/167706304-44b689ac-3815-407e-a203-4a2e6d305fcf.png)

**Comment by Mrlinkwii** [comment]
@BParks21  may i ask what nvidia driver are you on

**Comment by BParks21** [comment]
I'm on 511.23, It's a bit old. I could try updating and clean installing with DDU later and report back.

**Comment by BParks21** [comment]
@lightningterror I can confirm that I can't reproduce it on Vulkan or D3D12. I did however figure out how to trigger it every time with Opengl. So I'll update my drivers with a fresh install using DDU. If it still occurs would you be willing to follow my exact steps to reproduce it?

**Comment by lightningterror** [comment]
What are the steps, also I'm only playing back the gsdump.

**Comment by BParks21** [comment]
@lightningterror So I completely wiped the Nvidia driver with ddu and updated to the latest. I'm still able to reproduce this every time. I will record a video with the exact steps to reproduce it.

**Comment by BParks21** [comment]
Here is the video and a save state. Remember this was reproduced with opengl, and conservative buffer checked.  Disc 2. The graphical bug is reproducible at native res but is less noticeable and severe.  
https://drive.google.com/file/d/1PnW-1hShtEUqGAeBXKDcOXYE-qDgJYva/view?usp=sharing

**Comment by Ryudo300** [comment]
Was able to reproduce the graphic artifacts on OpenGL following the steps of the video and using the provided save state. 

All the other renderers don't seem to have the issue. Switching to Software mode temporarily fixes the issue until you go back down in that dark room and then up.

**Comment by BParks21** [comment]
> Was able to reproduce the graphic artifacts on OpenGL following the steps of the video and using the provided save state.
> 
> All the other renderers don't seem to have the issue. Switching to Software mode temporarily fixes the issue until you go back down in that dark room and then up.
> 
> (OGL Driver version is 511.65 at the time of testing)

Yeah something with the dark room triggers the bug.

**Comment by lightningterror** [comment]
Can this be retested on latest dev?

**Comment by BParks21** [comment]
I'll test it.

**Comment by BParks21** [comment]
> Can this be retested on latest dev?

Still able to reproduce in the latest wx build.

**Comment by lightningterror** [comment]
Can this be re tested again as improvements were made and the option was removed?

**Comment by BParks21** [comment]
I'll test it.
