### ISSUE TITLE
[Feature Request]: support for ZSO compressed files.

### ISSUE THREAD

**Issue by JoseAaronLopezGarcia** [PCSX2/pcsx2#6055]
### Description

I've recently implemented support for ZSO compressed files in Open PS2 Loader (https://github.com/JoseAaronLopezGarcia/Open-PS2-Loader-ZSO/).

While the format is still being tested and improved on real PS2, the results are so far extremely positive, with many games reaching full speed on USB devices.

It would be ideal for the emulator to also support this format for users to have their files working on both systems.

The ZSO file format is exactly the same as CSO, which is already supported by PCSX2, so adding support for ZSO would be trivial; the only difference is in the magic number and that blocks are compressed with LZ4 instead of DEFLATE.

For sample source code of ZSO readers:

https://github.com/JoseAaronLopezGarcia/Open-PS2-Loader-ZSO/blob/master/modules/isofs/zso.c
https://github.com/PSP-Archive/ARK-4/blob/main/core/inferno/isoread.c
https://github.com/MrColdbird/procfw/blob/master/ISODrivers/Inferno/isoread.c

### Reason

It's already working really well on original hardware.

### Examples

Difference between plain ISO and ZSO on USB devices:

ISO: https://drive.google.com/file/d/1O7EGH1cO09SexxgyfadjHJrUvIR0kkAu/view

ZSO: https://drive.google.com/file/d/15E_9sWO_eNHl52XDjOpBIueADcZ9_ZwY/view

**Comment by F0bes** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/6050
