### ISSUE TITLE
[BUG]: Berwick Saga Title Screen Visible During Intro Cutscene

### ISSUE THREAD

**Issue by RobertTheSable** [PCSX2/pcsx2#6057]
### Describe the Bug

The title screen for Berwick Saga (English Translation Patch) can be partially seen while the intro cutscene plays.

I think this is a regression because I don't recall having this issue when I last played the game in PCSX2, but I don't remember the exact version

### Reproduction Steps

Open the game and watch the intro cutscene.

### Expected Behavior

The intro cutscene should be displayed correctly without the title screen elements visible.

### PCSX2 Revision

v1.7.2718

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Flatpack on Kubuntu 22.04

### CPU

i5-6600K

### GPU

AMD RX 480

### GS Settings

All settings are the default as far as I'm aware. I tried the OpenGL HW, SW, and Vulkan renderers and got the same results.

### Emulation Settings

Window size set to 1280x960.

### GS Window Screenshots

Screenshots of the cutscene in PCSX2:
![pcsx-1](https://user-images.githubusercontent.com/11481364/167737553-2b36422c-3e31-4368-8046-7097e8d9809b.png)
![pcsx-2](https://user-images.githubusercontent.com/11481364/167737554-71a75fb4-a4ff-4f24-855c-142dc5331f38.png)
Compared to the same cutscene captured on a real console:
![console1](https://user-images.githubusercontent.com/11481364/167737555-1ae73cf2-b225-4ae1-a12d-701901e1c8c2.jpeg)
![console2](https://user-images.githubusercontent.com/11481364/167737556-0ab72e49-e789-4b30-a4d9-43ec54abe8aa.jpeg)

### Logs & Dumps

[gs_20220510175427_Berwick Saga - Tear Ring Saga Series _NTSC-J__SLPS-25497.tar.gz](https://github.com/PCSX2/pcsx2/files/8665428/gs_20220510175427_Berwick.Saga.-.Tear.Ring.Saga.Series._NTSC-J__SLPS-25497.tar.gz)

**Comment by refractionpcsx2** [comment]
Does it work correctly without the translation patch?

**Comment by RobertTheSable** [comment]
It does not.
![gs_20220510182105_Berwick Saga - Tear Ring Saga Series _NTSC-J__SLPS-25497](https://user-images.githubusercontent.com/11481364/167740271-0494a344-49c5-4498-85de-29f9ba3f8f2b.png)

**Comment by refractionpcsx2** [comment]
I find it suspicious that the video has a screen which is perfectly alpha blended with the video, which you don't see before this point as a "bug"....

I'm getting it confirmed with real PS2 hardware, since YouTube is just full of PCSX2 videos.

**Comment by RobertTheSable** [comment]
[Here's a PV/Trailer](https://www.youtube.com/watch?v=tOQWP0tmM0s) for the game which has clips from the intro in it. Which probably indicates what it's supposed to look like, if you think my screenshots captured from a real console don't  indicate that.

**Comment by refractionpcsx2** [comment]
Okay I have confirmed on a ps2 with help of a friend that you are indeed correct, so I'll go bug hunting tomorrow.

![unknown](https://user-images.githubusercontent.com/6278726/167751283-2eb507f8-9e4d-4c51-9dd3-87c7c29334e6.png)

**Comment by refractionpcsx2** [comment]
Initial investigation is weird, the game is drawing the menu background in every frame, but the further weird thing is this.

The game sets the Translucent (half transparent) threshold to 256, which is impossible, because by that point the value is clamped from 0-255, so it makes everything translucent.

There must be some strange behaviour here we're not accounting for... the question is just what....

**Comment by guidodi** [comment]
I can confirm this used to work correctly, with and without the patch at some point in the past (cant really tell you the version)

**Comment by refractionpcsx2** [comment]
I know it used to work, becasue we didn't save the threshold values correctly for the alpha blending (we accidentally cut a bit off the top) but us fixing that, which did fix a game, has introduced this issue, so we have to work out why.

**Comment by Goatman13** [comment]
I tested this in other ps2 emulators too, and result is surprising. Hype Time Quest is mentioned here because this game rely on 0x100 translucency threshold to work correctly. Another game that need 0x100 is Perfect Ace2, but game have other issues that won't allow to test it on other emus.

PCSX2: 
Berwick Saga - broken
Hype Time Quest - works

Dobiestation:
Berwick Saga - broken (you need to nop unsupported tlbp opcode to allow game to start)
Hype Time Quest - works

Play!:
Berwick Saga - works
Hype Time Quest - works

Dobie, and PCSX2 handle alpha in the same way, so result is not surprise. What play do seems to not follow PS2 hw manual or anything else, and imo is wrong. But it works...

```
uint32 alphaTh0 = (m_TH0 & 0xFF) | ((m_TH0 & 0xFF) << 8) | ((m_TH0 & 0xFF) << 16);
uint32 alphaTh1 = (m_TH1 & 0xFF) | ((m_TH1 & 0xFF) << 8) | ((m_TH1 & 0xFF) << 16);

	uint8 a = 0;
	uint32 rgb = (static_cast<uint8>(nB) << 16) | (static_cast<uint8>(nG) << 8) | (static_cast<uint8>(nR) << 0);
	if(rgb < alphaTh0)
	{
		a = 0;
	}
	else if(rgb < alphaTh1)
	{
		a = 0x40;
	}
	else
	{
		a = 0x80;
	}
```

**Comment by F0bes** [comment]
What Play! does is wrong, I ended up creating an elf that tests the thresholds a little while ago by putting RAW8 directly into the IPU and running CSC.

I was wondering though, CSC takes in RAW8, IDCT outputs RAW16, what does the PS2 do to convert RAW16 -> RAW8?
I can't wrap my head around the IPU enough to provide IDCT with some proper test data to figure that out 🤷

**Comment by refractionpcsx2** [comment]
yeah we looked at play, and it is wrong, so that's not the answer, I'd rather know what's going on, if I was going to suggest a fix for the meantime, I'd say patch the SETTH command to not set 0x100.
