### ISSUE TITLE
[BUG]: Iffy texture replacement in Secret Agent Clank

### ISSUE THREAD

**Issue by ZwipZwapZapony** [PCSX2/pcsx2#6062]
### Describe the Bug

When using PCSX2's texture dump/replacement feature, Secret Agent Clank (SCES-55496) still manages to load some original/unmodified textures.

Not all textures can be replaced (some can't even be dumped!), and for those that can, they may revert to the original texture after some time (and may return to the replaced texture after some more time).

\
Related to (and may have the same root cause as?) #5862.

### Reproduction Steps

- Play through a level three times while dumping textures (while rebooting PCSX2 between each attempt).
- Rename the game's textures' "dumps" folder to "replacements".
- Make a 64x64 PNG image, with RGB colour 64,192,64 and 127 alpha, and save it as "green.png" in the replacements folder.
- Use `FOR %A IN (*) DO COPY /B /Y "green.png" "%~A"` in a command prompt within the replacements folder, to replace every dumped texture with the flat, green texture.
- Delete "green.png", to ensure that it doesn't affect PCSX2.
- Launch PCSX2, enable loading textures, and play through the level again.

\
Many textures will now be flat green, but some will also be unmodified (either immediately or after some time).

### Expected Behavior

All textures should have been flat green permanently.

### PCSX2 Revision

v1.7.2735

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8300H @ 2.3GHz

### GPU

NVIDIA GeForce GTX 1050

### GS Settings

![image](https://user-images.githubusercontent.com/14360666/167878891-3c261492-f9d7-4a9e-9b4e-f8c9b1c72f17.png)

### GS Window Screenshots

|Description|Screenshot|
|---|---|
|Staring into a corner, loading a cutscene, and skipping it (to reload textures):|![image](https://user-images.githubusercontent.com/14360666/167879208-4798f5c1-2b28-442e-8d58-16e51595f5cb.png)|
|Turning 180 degrees, which loads more content (and reverts some of the changed textures in the process):|![image](https://user-images.githubusercontent.com/14360666/167879307-ea87db98-d85e-4ef0-8558-44e6163f9725.png)|
|Turning 180 degrees again, back to the corner. Compare it to the first screenshot.|![image](https://user-images.githubusercontent.com/14360666/167879677-e6199853-cfd8-4062-abc9-4e281aa58faa.png)|

**Comment by refractionpcsx2** [comment]
It'd be worth waiting for the texture replacement fixes to go live, since they aren't yet and Github has broken, so it might be a while.

**Comment by stenzek** [comment]
Pretty sure this is just different hashes. Doesn't really make much sense that it would randomly change, the replacement texture persists in the hash cache.

**Comment by ZwipZwapZapony** [comment]
> @ refractionpcsx2 - *It'd be worth waiting for the texture replacement fixes to go live, [...]*

I'll report back when the next build is live. 👍

> @ stenzek - *Pretty sure this is just different hashes. [...] Edit: easy enough to confirm this, leave dumping enabled and look for new files*

De-confirmed. There are up to 5-10 new files per level playthrough, but they're not duplicates of things that reverted; there's no duplicate crate texture or weapon icons, and replacing the new files with the flat green texture doesn't avoid some things reverting.

**Comment by stenzek** [comment]
Then provide the replacement textures, and a save state, and I'll try to take a look at what's going on. I'm not going to spend ages playing through games, only to find this is user error again, like the other thread.

**Comment by stenzek** [comment]
Okay, figured out what was going on here, it only bugged out when preloading wasn't set to full (see #6071). I always run full preloading, which is why I wasn't able to reproduce any issues.

**Comment by ZwipZwapZapony** [comment]
This still happens in v1.7.2745.

The language select screen has the same behaviour as before. It only dumps up to and including the first non-replaced flag. If I replace flag 1, 2, and 4, but not 3, then flags 1 and 2 are only replaced for one frame, and flag 4 is never replaced.

The in-game behaviour is the same, too; if I stare into that corner, reload textures by watching a cinematic, and spin around, they can revert. Like the language select screen, not all textures are dumped in the first playthrough.

I can confirm that setting Texture Preloading to Full (Hash Cache) fixes all of this. This is still an issue with the default settings, though.

**Comment by stenzek** [comment]
> The language select screen has the same behaviour as before. It only dumps up to and including the first non-replaced flag. If I replace flag 1, 2, and 4, but not 3, then flags 1 and 2 are only replaced for one frame, and flag 4 is never replaced.

You'll need to provide a zip with the exact replacement set which causes it then. Because even with preloading off, following your instructions from before works correctly for me now.

**Comment by ZwipZwapZapony** [comment]
Here's a zip with the "flag 1, 2, and 4, but not 3" setup: [Secret Agent Clank (SCES-55496) Flag texture bug 2.zip](https://github.com/PCSX2/pcsx2/files/8688465/Secret.Agent.Clank.SCES-55496.Flag.texture.bug.2.zip)

**Comment by stenzek** [comment]
Looks fine to me, with preloading set to none:

![image](https://user-images.githubusercontent.com/11288319/168409697-b7307386-05b3-4c84-886a-786214900d5c.png)

**Comment by ZwipZwapZapony** [comment]
It still happens for me in v1.7.2746. Either it only happens in the wx version (you use Qt), the AVX2 build (I don't know which you use), or a "non-development" build (I use a nightly build from https://pcsx2.net/downloads/), all of which are very unlikely, or else some other configuration impacts it.
To see if it's the latter, here's a zip of my "inis" folder: [Secret Agent Clank inis.zip](https://github.com/PCSX2/pcsx2/files/8692711/Secret.Agent.Clank.inis.zip)

**Comment by stenzek** [comment]
GPU palette conversion is the issue. But it's a bit complex, will sort out a fix tomorrow.

**Comment by stenzek** [comment]
https://github.com/PCSX2/pcsx2/pull/6080 should fix it with your configuration, it's not ideal, but I don't see how it's possible to handle any other way.
