### ISSUE TITLE
[BUG]: Crash in Linux when using 'Dump Textures'

### ISSUE THREAD

**Issue by tomporter518** [PCSX2/pcsx2#6063]
### Describe the Bug

While attempting to use 'Dump Textures' (up through commit: 0bb7cc0 on a self built version), at least two games crash (Baldur's Gate II and Ratchet & Clank). Some/many files are created before the crash.

### Reproduction Steps

Enable Dump Textures and for:
- BG II: attempt to start a new game or a load a saved one
- R&C: just attempt to load the game

### Expected Behavior

If textures cannot be created in the appropriate folder, that the game would continue to run/load.
Using Vulkan on a 1080Ti. While the log file shows the failure occurs on: GSLocalMemory::ReadTexture4, I have also seen it on: GSLocalMemory::ReadTexture32.
Log file: [emuLog.txt](https://github.com/PCSX2/pcsx2/files/8672139/emuLog.txt)

### PCSX2 Revision

v1.7.2736

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 35

**Comment by SirFancyBacon** [comment]
I can confirm this also happens for Ubuntu 21.10

**Comment by stenzek** [comment]
Not a regression, this would've been an issue from the beginning if you used AVX2. Fixed by https://github.com/PCSX2/pcsx2/pull/6065
