### ISSUE TITLE
[BUG]: Turok Evolution wrong image underwater in hardware mode

### ISSUE THREAD

**Issue by Shideravan** [PCSX2/pcsx2#6064]
### Describe the Bug

When underwater, the image become wrong when in hardware mode. The following snaps was taken in Vulkan and OpenGL modes
![image](https://user-images.githubusercontent.com/12163923/167921731-cb409e19-5763-4a3c-8cc0-f7c5dccf2718.png)
![image](https://user-images.githubusercontent.com/12163923/167921883-a5a61ff4-fee8-4c0c-8b0c-a33cd6adda0b.png)

### Reproduction Steps

You need to set the graphics settings to any hardware renderer. Then ingame, just go to any body of water and dive.

### Expected Behavior

To show correct image as is in the software mode

### PCSX2 Revision

v.1.7.2735

### Operating System

Windows 10 (64bit)

### CPU

i7-4790

### GPU

GTX 1070

### GS Settings

![image](https://user-images.githubusercontent.com/12163923/167922742-b7c01c1b-29cb-42e0-8c29-a3b1b4575662.png)

### Emulation Settings

Everything on default of preset 2 (safe)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8672639/snaps.zip)

**Comment by lightningterror** [comment]
Can you try Texture inside RT hw hack?

**Comment by Shideravan** [comment]
Yes, using Texture inside RT fixes the problem
![image](https://user-images.githubusercontent.com/12163923/167996679-e33126d1-3ad4-45fe-b30a-f9feae325a55.png)

**Comment by ps1freak26** [comment]
There is a line on the bottom that looks like the issue with Crash Twinsanity can you try half pixel offset set to special (texture) to see if it gets rid of it.

**Comment by Bigmac9922** [comment]
Using half pixel offset special (texture) does get rid of the line.
