### ISSUE TITLE
doesn't work in vulkan 

### ISSUE THREAD

**Issue by lucasmz1** [PCSX2/pcsx2#6077]
### Describe the Bug

failed to creat context log:

PCSX2 Nightly - v1.7.2746 Compiled on May 13 2022
Savestate version: 0x9a2c0000

Host Machine Init:
	Operating System =  Ubuntu 18.04.6 LTS
	Physical RAM     =  7739 MB
	CPU name         =  Intel(R) Core(TM) i7 CPU       L 640  @ 2.13GHz
	Vendor/Model     =  GenuineIntel (stepping 05)
	CPU speed        =  2.127 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 029ae3ff
	x86EFlags        =  28100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...
(EnumerateGPUNames) vkEnumeratePhysicalDevices failed:  (-3: VK_ERROR_INITIALIZATION_FAILED)
Patches: No CRC found, using 00000000 instead.
	HotSwapping to new ISO src image!
HLE Host: Set 'host:' root path to: /

PAD: failed to load ini /home/lucas/Downloads/pcsx2-v1.7.2746-linux-AppImage-64bit.AppImage.config/PCSX2/inis/PAD.ini
Patches: No CRC found, using 00000000 instead.
isoFile open ok: /media/lucas/Lucas1000GB/pc/Software/jogos/ps2 games/Resident Evil - Code - Veronica X (USA).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (919920 sectors)
Vsync is OFF
(EnumerateGPUs) vkEnumeratePhysicalDevices failed:  (-3: VK_ERROR_INITIALIZATION_FAILED)
Failed to create Vulkan context
Failed to acquire host display
GS failed to open.
(p) STL Runtime Error: GS failed to open.(thread:EE Core)

### Reproduction Steps

I did everything as usual

### Expected Behavior

working fine due to the expected behavior

### PCSX2 Revision

v1.6

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

ubuntu 18.04

**Comment by JordanTheToaster** [comment]
Your GPU is way too old to support OpenGL this is not a PCSX2 bug.
