### ISSUE TITLE
[BUG]: (VfW) codecs are unlisted as of 3/19/22.

### ISSUE THREAD

**Issue by AsmodeanBreaggAI** [PCSX2/pcsx2#6082]
### Describe the Bug

When attempting to use PCSX2's built-in recorder on the latest version, it does not bring up a list of all the VfW codecs installed on the user's computer anymore. I spent some time tracking it down and narrowed the issue down to anything after [v1.7.2485](https://github.com/PCSX2/pcsx2/commit/6977323d88c2d79a3e039c87898cedfb5a7b363b). This was the last version all codecs showed up on. I couldn't test v.1.7.2485-1, 2, or 3 due to those builds not being linked, but it's somewhere in that region. I originally brought it up here before investigating more: https://github.com/PCSX2/pcsx2/pull/4523#issuecomment-1126802093

### Reproduction Steps

Start a game and press F12 to bring up the recording menu, then look through the list of codecs to select. Anything with the (VfW) prefix is missing.
![image](https://user-images.githubusercontent.com/31236007/168489539-c13a1fad-b879-494d-ae25-4c382ae57324.png)

### Expected Behavior

On versions before v1.7.2486, bringing up this recording menu would give a list of the (VfW) codecs, allowing me to select the one I normally use.
![image](https://user-images.githubusercontent.com/31236007/168489803-6dac4580-482c-4200-a43e-ec132e823d35.png)

### PCSX2 Revision

v1.7.2746

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
That's normal as most codecs simply didn't work (correctly) and are even older than I am. Needs more modern codecs but you can use uncompressed and use avi converter to reduce size for example.

**Comment by Mrlinkwii** [comment]
>I couldn't test v.1.7.2485-1, 2, or 3 due to those builds not being linked,

all the previous nightly builds should be listed on https://pcsx2.net/downloads/

**Comment by RedDevilus** [comment]
But yeah we really need to have working modern codecs, so it's still a valid issue.

**Comment by dio-gh** [comment]
Sorry, but for me not even 1.7.2485 shows VfW codecs. Are you sure this is the correct version?

**Comment by dio-gh** [comment]
Update: seems to be an architecture issue. 32 bit builds work, even from the 1.7 series.

**Comment by RedDevilus** [comment]
Related to: https://github.com/PCSX2/pcsx2/issues/4032

**Comment by AsmodeanBreaggAI** [comment]
> Sorry, but for me not even 1.7.2485 shows VfW codecs. Are you sure this is the correct version?

Here's raw footage of me downloading the different PCSX2 versions I mentioned and attempting to use x264vfw codec. Might want to do 2x speed. Also, my internet was in the middle of dying while I was recording this, so the downloads are slow.
https://www.youtube.com/watch?v=d-Hh0vceD1A

**Comment by RedDevilus** [comment]
> > Sorry, but for me not even 1.7.2485 shows VfW codecs. Are you sure this is the correct version?
> 
> Here's raw footage of me downloading the different PCSX2 versions I mentioned and attempting to use x264vfw codec. Might want to do 2x speed. Also, my internet was in the middle of dying while I was recording this, so the downloads are slow. [youtube.com/watch?v=d-Hh0vceD1A](https://www.youtube.com/watch?v=d-Hh0vceD1A)

He is on Linux and VfW are ancient Windows codecs so makes sense.

**Comment by GovanifY** [comment]
So, I went to take a look at it (yes, I know) and it seems like Windows simply doesn't expose the VFW codecs anymore through CLSID_VideoCompressorCategory, which is a bit weird as it is very much [the documented way to get your codec listed](https://docs.microsoft.com/en-us/windows/win32/directshow/choosing-a-compression-filter).

Looking at this a little more in depth, it looks like the x264vfw developers are aware of this problem and that the 64 bit version, even native, [isn't picked up on by programs](https://sourceforge.net/p/x264vfw/bugs/19/).

Why? Well the documented wrapper used to expose Vfw codecs has been removed from DirectShow 64 bit altogether, obviously!

Apparently the codecs are _still_ exposed through the registry, so we might want to take a look at this and see if we can fix this.

**Comment by GovanifY** [comment]
Well, VFW is very much deprecated and Windows removed all the official ways to retrieve codec lists that I could find.
This is probably going to end up as a WONTFIX on the end of Microsoft being its funny self until someone wants to add proper codec support to pcsx2...

**Comment by dio-gh** [comment]
> Here's raw footage of me downloading the different PCSX2 versions I mentioned and attempting to use x264vfw codec.

Yeah, as you can see in your footage, the first build you download is an x86 build, and the latter is an x64 build. So that further confirms my findings.

> He is on Linux and VfW are ancient Windows codecs so makes sense.

No.
