### ISSUE TITLE
Last Blade 1 + 2 cause the emulator to crash

### ISSUE THREAD

**Issue by mkwong98** [PCSX2/pcsx2#609]
Last Blade 1 + 2 does not load even with the safest setting. I haven't tested this game for a long time so I'm not sure which commit broke it.

**Comment by bositman** [comment]
You should follow the issue posting guidelines, since this is pretty much useless atm...
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by mkwong98** [comment]
Sorry about that, I'm close this for now

**Comment by karasuhebi** [comment]
Are you making a new issue for this or...?

**Comment by NelsonRosenberg** [comment]
Just ran into this problem, does this still occurs for anyone else?
