### ISSUE TITLE
[Feature Request]: Carousel testing (GS)

### ISSUE THREAD

**Issue by dio-gh** [PCSX2/pcsx2#6092]
### Description

When it comes to graphics, the emulator currently offers a sizable list of intentional inaccuracies and workarounds. Through these, users can attempt to correct any rendering bugs that happen due to or regardless of the various enhancements that are on. 

While a good bit of this is automated these days, said automation relies on **someone discovering the correct set of settings first**, and then introducing them to the GameDB. Furthermore, not all graphical problems are the same. Some issues are regressions, or stem from the alteration of the aforementioned options, **sometimes requiring a drill-down** through the applied graphics settings.

To help both of these cases, I came up with, what I believe is, a novel idea called carousel testing. This would involve a hotkey, which when pressed, would start an iteration cycle through the various combinations of graphics settings.

Users could **keep** or **ditch** the given collection of settings, based on the visuals they're seeing, using two other keys. The process would be instrumented through OSD messages.

The order of these combinations would be predetermined, but the keeping of a setting should influence the combinations presented after. So say I find `Frame Buffer Conversion` helps the visuals, combinations involving this setting should follow it first.

### Reason

I believe this would significantly speed up iteration times and lessen friction. Not only that, but I feel it'd be so accessible, that moving forward, it could be offered as a general troubleshooting step within the various guides and on Discord, hopefully leading to a more up to date, more correct, and more expansive GameDB.

It'd also simplify the process of people trying to find the right settings, as it cuts out the interaction with the GS settings completely.

### Examples

I'm fairly sure this is a novel idea, so I can't provide any example implementations,

**Comment by dio-gh** [comment]
Forgot to mention, but it'd also need various other (obvious) components, like a counter for showing which combination someone is on (e.g. `17/78`), and an Undo and Exit button, to do exactly that. But yeah, this is the idea.

**Comment by lightningterror** [comment]
This sounds like a nightmare to maintain, there will be hundreds of combinations.

**Comment by coornio** [comment]
While novel indeed, I agree that it sounds like a maintenance nightmare due to the potential combinations. Ultimately it will be more confusing that way, especially since when Qt is launched officially we'll be able to have the settings panel open on the side and change desired hacks in *real-time* as opposed to what we do now: navigating dropdown menus, opening a gui, switching tabs, changing settings, hitting OK, watch if anything changed, repeat ad-nauseam.

**Comment by dio-gh** [comment]
The number of combinations is exactly the same as people are normally able to go through. Unless there's a programming challenge involved, I fail to necessarily see the complexity.

Settings are not any more real time on Qt now, keeping the window open should be perfectly achievable on Wx as well, just wasn't done.

**Comment by coornio** [comment]
I shall let someone else more familiar with the code base explain why a lot of things that sound intuitive would be an absolute pain to try and implement in Wx in the past and why they were all ignored and postponed until now where the switch to Qt is happening :p 

That aside, the number of combinations is rather stupendous. Leaving aside the likes of texture offsets, skipdraw, and trilinear.. you will have exactly 2^16 possible combinations of hacks. That's 65.536 of them.

**Comment by dio-gh** [comment]
A pain one would code in once, then everyone would benefit, is the idea. The patterns are not obvious for a layman, but pressing yes/no, then bailing after a while takes ~0 braincells.

That being said, if it's difficult to set up programmatically, then that's the end of that.

**Comment by lightningterror** [comment]
I'll close this then.
