### ISSUE TITLE
[BUG]: call of duty 3 graphical issues on HW mode.

### ISSUE THREAD

**Issue by labib2002** [PCSX2/pcsx2#6093]
### Describe the Bug

call of duty 3 exhibits graphical issues on hardware mode that aren't happening on the software renderer.
software:

![gs_20220517162405_Call of Duty 3 _PAL-E__SLES-54166](https://user-images.githubusercontent.com/84257269/168835530-4a9ae7db-473f-4ddc-bacc-0575967e9035.png)

software:

![gs_20220517162152_Call of Duty 3 _PAL-E__SLES-54166](https://user-images.githubusercontent.com/84257269/168835550-d87a9ce3-e444-4c73-b9ba-4e759d53779e.png)

Hardware(auto and all renderes same issue):

![gs_20220517162204_Call of Duty 3 _PAL-E__SLES-54166](https://user-images.githubusercontent.com/84257269/168835574-75e159d0-3662-479a-89e4-f0317290d238.png)

Hardware(auto and all renderes same issue):

![gs_20220517162354_Call of Duty 3 _PAL-E__SLES-54166](https://user-images.githubusercontent.com/84257269/168835588-f8a25740-0b7f-4b57-aebe-9f5b32ad1e38.png)

### Reproduction Steps

run call of duty 3 on any hardware renderer, the issue is available on the main screen and soon as you begin playing.

### Expected Behavior

it's expected to look like in the software renderer screenshots

### PCSX2 Revision

v1.7.2755

### Operating System

Windows 10 (64bit)

### CPU

i7-8750h

### GPU

GTX 1060m

### GS Settings

all default. 

### Emulation Settings

all default.

### GS Window Screenshots

default no need.

**Comment by refractionpcsx2** [comment]
Already being tracked as part of #3138

**Comment by labib2002** [comment]
> Already being tracked as part of #3138

Okay thank you,
Is there anything I can do to help?

**Comment by refractionpcsx2** [comment]
Probably not, as we have a reasonable idea of what it is, but thank you.
