### ISSUE TITLE
[BUG]: Game is more performant when the frame limiter is off

### ISSUE THREAD

**Issue by dio-gh** [PCSX2/pcsx2#6103]
### Describe the Bug

I have bouts of dips to 80% speed in NFS Underground 2 sometimes, but I noticed that if I uncap the speed limiter, it will shoot up closer to 100%, and sometimes even significantly beyond.

![image](https://user-images.githubusercontent.com/10439488/169396036-eda62a7f-0c1d-41a5-9337-2a23cd02acd4.png)

In this scene specifically, I get roughly 100% speed on Vulkan in windowed mode, but it drops to about 80% in full screen. When uncapped however, the speed shoots up all the way to 140%.

I can replicate this on all backends, even software, though in this specific scene I couldn't get DX11 to display this, as DX11 is too performant. I'm on the high performance energy profile, and have cross referenced HWinfo to verify that my CPU isn't downclocking or thermal/energy throttling.

**Edit:** Oh yeah, this is on an Intel i5 4440. OpenGL and Vulkan seem to have a tendency to trigger some AMD driver hack that enables exclusive full screen, but even on DX11 SW mode I can repro this issue, so it doesn't seem to be that.

### Reproduction Steps

Pull up NFSU 2 and give it a whirl as described.

### Expected Behavior

Consistent emulation speed that sticks to 100% if the hardware is capable of it (which it clearly is, as can be seen when uncapped).

### PCSX2 Revision

v1.7.2746

### Operating System

Windows 8.1 (64bit)

**Comment by dio-gh** [comment]
Update: seems to be a "Sync to host refresh (Vsync)" related issue. If I turn that off, the issue disappears. I'll leave this open until it's confirmed whether that's expected behavior.

**Comment by stenzek** [comment]
Working as expected, imo. If *any* frame takes longer than 16ms (assuming you're using full, not hybrid vsync/tear-if-late), the present call with block until the next vsync period (usually your monitor refresh, so 16ms). Which will manifest as a speed drop, since the MTGS will block CPU emulation until that present finishes.

**Comment by dio-gh** [comment]
And is the sync not present when in windowed mode? Cause in windowed mode I'm fullspeed, and afaik the compositor should force vsync. Or does that not care/know if the host has finished swapping frames yet, and as a result it's all happy?

Would explain DX11 HW cause it seems to be borderless fs, not exclusive, DX11 SW remains a question though.

**Comment by stenzek** [comment]
It can change between windowed and fullscreen, yes. In fullscreen mode, the present can be blocked by the hardware/display page flipping, if the driver/OS decided to scan the application's backbuffer out directly without composition.

> Either way, pretty hardcore caveat for PAL games on VRR-incapable configurations, wasn't familiar with this before.

Absolutely. That's why I wanted to add a "switch the host to 50hz mode if possible", i.e. sync host refresh to guest refresh option.

**Comment by dio-gh** [comment]
I see, thanks. This checks out enough that

**Comment by dio-gh** [comment]
You gave me an idea; I noticed days ago that Windows offers me 50 Hz as a selectable refresh rate for my monitor :p Brb, testing.

**Comment by dio-gh** [comment]
So I set my monitor's refresh rate to 50 Hz (although my monitor's OSD is incapable of reporting refresh rate sadly, so can't verify it), and now it becomes locked to 67%.

Which is oddly specifically 2/3rds. WTF is going on, I haven't got a clue.

**Comment by stenzek** [comment]
It could just be out of phase. That's what https://github.com/PCSX2/pcsx2/pull/5488 was designed to fix.

**Comment by dio-gh** [comment]
As found yesterday, it's fixed by "skip duplicate frames". Waiting for a PR to make it official. Those experiencing this issue should try turning off `Sync to host refresh (Vsync)` in the meantime and pray for no tearing.
