### ISSUE TITLE
[BUG]: Sega Ages 2500 Series Vol. 19 - Fighting Vipers: Black and White bug

### ISSUE THREAD

**Issue by waspennator** [PCSX2/pcsx2#6105]
### Describe the Bug

On all renderers except for software, the game seems to render in black and white instead of in actual color.

### Reproduction Steps

Just start the game up while using any renderer except for software and let it sit on the title until it goes through the attract mode intro, it should be noticeable right away.

### Expected Behavior

The game should be in regular color like the software renderer.

### PCSX2 Revision

v1.7.2746

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Window Screenshots

Software Renderer:

![Fighting Vipers color bug Software](https://user-images.githubusercontent.com/78768499/169443816-a30a871f-34f4-4170-9b0b-777be87973c0.png)

OpenGL, Vulkan, DX11/DX12 Renderers:

![Fighting Vipers color bug other renderers](https://user-images.githubusercontent.com/78768499/169443865-2215a432-925d-4c31-99b9-20a3964f36bc.png)

### Logs & Dumps

[Sega Ages 2500 Series Vol. 19 - Fighting Vipers Black and White bug Vulkan.zip](https://github.com/PCSX2/pcsx2/files/8735665/Sega.Ages.2500.Series.Vol.19.-.Fighting.Vipers.Black.and.White.bug.Vulkan.zip)

Dump was made while using Vulkan, but it is replicable while using any of the hardware renderers.

**Comment by refractionpcsx2** [comment]
this is kind of a "we know" since this affects pretty much all the Sega games of that era such as Sonic Fighters and Virtua Fighter (possibly Sega Rally 95 as well, I forget)

**Comment by waspennator** [comment]
Checking the wiki again, yeah, apparently Sega Rally 95 has the same issue judging from it. Didn't know this was such a reoccurring trend with these games.

**Comment by superblobster** [comment]
Last Bronx from the same collection is also affected.

**Comment by nimtz** [comment]
Adding a bit more info after some investigation of the issue (thanks to refraction for the help).

This happens for all the Sega Model 2 hardware games on ps2 (seems Sega used the same base engine for all of them), They are:
Virtua Fighter 2
Last Bronx
Fighting Vipers
Sega Rally Championship 1995
Sonic the Fighters
Cyber Troopers Virtual-On

As for the issue(s), these games are building palettes on the GS, then building color look up tables on the GS and finally drawing normally with those CLUTs for color. The hardware renderer fails at both of the "preparatory" tasks, 

1. The palettes do not get generated properly as the games use some of the generated palettes as input textures to generate the more palettes (some improper invalidation of texture cache). 

2. The CLUTs do not get generated properly as the game uses the generated palettes as input textures for the CLUTs. (no invalidation of texture cache is implemented for the CLUT case currently)

Both of these issues can be fixed (resulting in a correct final render) by forcing many texture cache reads, but this tanks the performance to about 1 frame per second.

This is my current (limited) understanding of the issue, please correct me if you find anything wrong with it.

**Comment by waspennator** [comment]
Tested it out on my end, can confirm Fighting Vipers is rendering in color on all hw backends, thanks.
