### ISSUE TITLE
[BUG]: Arc the Lad: End of Darkness For Print Preview Only 1-28-2005

### ISSUE THREAD

**Issue by Jump-Suit** [PCSX2/pcsx2#6108]
### Describe the Bug

When going online on a emulated private server, upon retrieving the Server list, the emulator gives out FIFO errors it "Shouldn't have".
 

### Reproduction Steps

Ensure your using a private server or forked one of your own if your aim to reproduce this yourself. I suggest Horizon's server repo if this is to be followed through.
Additionally you'll need to have completed the game's singleplayer storyline to have reached "hunter", then Online will open to you to engage with. On top of this a DNAS Bypass will be requried.
Attempting to connect and retrieve server list will make the game go black and emulator toss out logs.

### Expected Behavior

Expected the game should return a Server List similar to production/retail version.
Able to retrieve Server list upon connecting:
Note: RETAIL/PROD shown in screenshot here
![image](https://user-images.githubusercontent.com/26616362/169635098-3833307a-2ceb-4296-a81b-6c1421b2e968.png)

### PCSX2 Revision

V1.7.2589

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

None

### CPU

Ryzen 7 5800x

### GPU

ASUS ROG STRIX GTX 1060 6gb

### GS Settings

None.

### Emulation Settings

None other than changing DNS locally to communicate with the game.

### GS Window Screenshots

Not really graphical.

### Logs & Dumps

[Arc the Lad - End of Darkness (Jan 11, 2005 prototype) Crash Emu.txt](https://github.com/PCSX2/pcsx2/files/8746945/Arc.the.Lad.-.End.of.Darkness.Jan.11.2005.prototype.Crash.Emu.txt)

**Comment by Mrlinkwii** [comment]
can this be checked on latest nightly

**Comment by refractionpcsx2** [comment]
No response from OP, we have no way of testing this since they were limited in numbers. if the problem persists, post here and we can reopen.
