### ISSUE TITLE
build error: cannot convert 'const wxString' to 'const wxChar*'

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#6115]
### Describe the Bug

When build on openSUSE Tumbleweed, it throws error:

```
pcsx2/DEV9/ConfigUI.cpp:399:31: error: cannot convert 'const wxString' to 'const wxChar*' {aka 'const wchar_t*'} in assignment
   399 |                         msg = _("Please select an ethernet adapter or disable ethernet");
       |                               ^
       |                               |
       |                               const wxString
```

### Reproduction Steps

Install required dependencies on Linux and run:

```
mkdir build
cd build
cmake .. \
  -DUSE_SYSTEM_YAML=ON \
  -DXDG_STD=ON \
  -DPACKAGE_MODE=ON \
  -DDISABLE_ADVANCE_SIMD=ON \
  -DGTK3_API=ON \
  -DSDL2_API=ON \
  -DUSE_VTUNE=OFF \
  -DUSE_VULKAN=ON
```

### PCSX2 Revision

v1.7.2760

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

openSUSE Tumbleweed

**Comment by refractionpcsx2** [comment]
@TheLastRar you might also wanna look at this?

**Comment by TheLastRar** [comment]
After a quick look i see that the macro `_()` is defined in two files;
Here:
https://github.com/PCSX2/pcsx2/blob/ea051c6d5fcc2eddbf749664340f283c88d058e3/pcsx2/gui/StringHelpers.h#L194 And here:
https://github.com/PCSX2/pcsx2/blob/6f7890b709d5e3f7f5b824781e493455efc92339/3rdparty/wxwidgets3.0/include/wx/translation.h#L38

`wxGetTranslation()` returns a wxString, while pxGetTranslation returns a wxChar*, see;
https://github.com/PCSX2/pcsx2/blob/ea051c6d5fcc2eddbf749664340f283c88d058e3/pcsx2/gui/pxTranslate.cpp#L32-L35

It seems your compiler picks the wx macro, rather than the px macro?
I'm not knowledgable in wx, nor did I write the DEV9 wx Ui, so I dunno why it goes wrong

**Comment by TheLastRar** [comment]
Alternatively, it could be that we where relying on an implicit conversion, which isn't being found

**Comment by 987123879113** [comment]
I'm also using OpenSUSE Tumbleweed and having the same problem. Based on some regression testing, it appears that this problem began with 893b3c629d00386b9b4b8483b78e9d3659229bf9. 

`common/Dependencies.h` was deleted in that PR which included the macros required for the `_` macro. `common/Dependencies.h` was included in `pcsx2/PrecompiledHeader.h` but was replaced with `#include "common/Pcsx2Defs.h"`. `common/Pcsx2Defs.h` includes some of the code from `common/Dependencies.h` but obvious leaves out the px macros.

Additionally, the `_` px macro code was moved to `pcsx2/gui/StringHelpers.h` in that commit.

This fixes the issue but also pulls in more code than previous into the precompiled header which I don't know how you guys would feel about. The macros need to be defined before wx imports (as per the comments attached with the macros) so this looks like the best spot from what I can tell.

`pcsx2/PrecompiledHeader.h`:
```cpp
#if !defined(PCSX2_CORE)
#include "gui/StringHelpers.h"

#include <wx/gdicmn.h>
#include <wx/gdiobj.h>
#include <wx/string.h>
#include <wx/tokenzr.h>
#include <wx/intl.h>
#include <wx/log.h>
#include <wx/filename.h>

// pthreadsw32 is not needed when compiling PCSX2-Qt.
#include <pthread.h>
#endif
```

**Comment by OdinVex** [comment]
To chime in, works fine with Ubuntu-derivatives.

**Comment by Mrlinkwii** [comment]
can be closed wx is dead

**Comment by TheLastRar** [comment]
> > can be closed wx is dead
> 
> ??? WxWidgets last released 3 months ago, none of their news states anything to that effect.

They mean the Wx version of PCSX2

**Comment by JordanTheToaster** [comment]
> > can be closed wx is dead
> 
> ??? WxWidgets last released 3 months ago, none of their news states anything to that effect.

In the official releases WX was purged on Christmas day.
