### ISSUE TITLE
Failure to compile in linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#6117]
### Describe the Bug

Attempting to compile PCSX2 (Qt build) fails with the following:
```
/home/testing/Desktop/pcsx2/pcsx2/pcsx2/Linux/LnxFlatFileReader.cpp: In member function ‘virtual void FlatFileReader::Close()’:
/home/testing/Desktop/pcsx2/pcsx2/pcsx2/Linux/LnxFlatFileReader.cpp:94:17: error: ‘close’ was not declared in this scope; did you mean ‘Close’?
   94 |                 close(m_fd);
      |                 ^~~~~
      |                 Close
[ 94%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/USB/USBNull.cpp.o
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:4509: pcsx2/CMakeFiles/PCSX2.dir/Linux/LnxFlatFileReader.cpp.o] Error 1
```
Additional information:
* Compiler: gcc-11.1.0
* Last successful compile: 1b2d9f0c5d37b4a57e15f4f9cfeb3f685d03b7fe

### Reproduction Steps

Attempt to compile PCSX2

### Expected Behavior

PCSX2 compiles

### PCSX2 Revision

Commit e283831841f6934d26a02d39e1784f420c5573f4

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.3 / kernel 5.13

**Comment by TheLastRar** [comment]
Are you compiling the Qt build, or the wx build?

**Comment by Shoegzer** [comment]
Sorry, the Qt build.  I updated the issue.

**Comment by TheLastRar** [comment]
Can you try and see if this builds for you? PR https://github.com/PCSX2/pcsx2/pull/6119

**Comment by Shoegzer** [comment]
That worked, thanks!
