### ISSUE TITLE
[BUG]: (QT) The cheat button and submenu don't work

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [PCSX2/pcsx2#6120]
### Describe the Bug

When you boot a game, the Cheats submenu (in System) and the Cheat button don't work properly.
The first one shows an empty submenu, while the button don't open anything.

![imagen](https://user-images.githubusercontent.com/16591467/169712362-2e859549-1ec8-4e9c-99ce-2eec64c08e0b.png)

I tested two games (Wild Arms and Haunting Ground), before and after enabling the widescreen and cheat files. Neither situation worked.

### Reproduction Steps

1. Open any game
2. Click on the Cheats button / go to System->Cheats

### Expected Behavior

The Button should open a cheat menu (with a list of loaded codes, I guess? I hadn't a chance of seeing how it looks like), the menu should show dialogs.

If those options can't be used at that point (for whatever reason), the button and menu should be disabled.

### PCSX2 Revision

 v1.7.2764 (QT AVX2)

### Operating System

Windows 10 (64bit)

**Comment by dio-gh** [comment]
Yup, known, not yet implemented. Valid ticket now though, I suppose.

**Comment by RedDevilus** [comment]
Related to: https://github.com/PCSX2/pcsx2/discussions/5947

**Comment by lightningterror** [comment]
Fixed in #6130
