### ISSUE TITLE
[BUG]: PCSX2 Crash via Windows Shell

### ISSUE THREAD

**Issue by Sythacc** [PCSX2/pcsx2#6126]
### Describe the Bug

Upon opening the program, if I try to add a directory to the Qt interface (via 'Add Game Directory...'), or attempt to search for a file at all, PCSX2 will crash. The crash occurs every time without fail.

This issue occurs in every 64bit build since the final 32bit build was released on 3/19/2022, at least all the ones I tested, and 64bit builds before that point are also affected. I don't know how far back though.

I am having to use the final 32bit build (pcsx2-v1.7.2484-windows-32bit-AVX2) to use the emulator. Which is a bummer since the new Qt interface and the updater just came out but I am unable to use the program due to this issue.

I have inquired about this on the Discord previously, about a month ago, and I was told it might have something to do with the fact that my Windows 10 interface/theme is modified. No error is shown, the program just becomes completely unresponsive, hangs, and will eventually crash itself or needs to be stopped through task manager. When looking at the crash logs they only contain the same one line message.

Exception 0xC0000005 at 0x00007FFF4B142B26

All dependencies are up to date and running PCSX2 as an administrator does not fix the problem.

Oddly enough the same exact problem occurs in Duckstation. I have only encountered this issue with Duckstation and PCSX2, as far back as I can remember.

### PCSX2 Revision

pcsx2-v1.7.2769-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

**Comment by Sythacc** [comment]
Oddly enough the same exact problem occurs in Duckstation. I have only had this issue with Duckstation and PCSX2.

**Comment by coornio** [comment]
Considering the Qt part is done by the same developer, it's not really surprising the same issue would span two different emulators :P 

That said, when I tried it myself to add a game directory, it scanned a few games then crashed silently. No error whatsoever. There's a bugs to iron out still it seems.

**Comment by stenzek** [comment]
Likely invalid and because of some broken shell extension (e.g oldnewexplorer)

**Comment by Sythacc** [comment]
> Likely invalid and because of some broken shell extension (e.g oldnewexplorer)

Though dismissive, your suggestion did work. Disabling OldNewExplorer worked. I completely forgot to consider that. PCSX2, and Duckstation, now works as expected.

Thanks.

**Comment by stenzek** [comment]
Not sure how it's "dismissive" when it's something 100% out of our control, and likely affects many Qt applications. I'd suggest filing a report with said extension, as it's been broken for years, and given we keep seeing reports on this (in both DS and PCSX2), they're either unaware, or don't care.

**Comment by Sythacc** [comment]
My apologies, I was unaware it has been such a problem. I've been searching for months intermittently to find a solution. So I am happy to have both programs work finally. As for OldNewExplorer, at this point, it seems to have been abandoned. But it's not all that important anyway.

Thanks again and have a good one.
