### ISSUE TITLE
[BUG]: Update.7z isn't removed after updating.

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6127]
### Describe the Bug

Idk if it's intended but upon using the built in updater, the emulator creates a file named "update.7z" inside the main directory. This file doesn't get removed even after the updating process is finished and just stays in the folder.

### Reproduction Steps

Use the built in updater.

### Expected Behavior

The file "update.7z" won't be removed.

### PCSX2 Revision

1.7.2770

### Operating System

Windows 10 (64bit)

**Comment by coornio** [comment]
Confirmed here too.
