### ISSUE TITLE
[BUG]: Texture dumping system not working correctly.

### ISSUE THREAD

**Issue by Raffaco** [PCSX2/pcsx2#6128]
### Describe the Bug

When you enable the texture dumping system it gives strange results.
Almost every texture has a transparent effect applied to it, and have light colors also, witch makes it unusable.

### Reproduction Steps

Settings > Graphics > Advanced > Dump textures

### Expected Behavior

Normal looking textures.

### PCSX2 Revision

v1.7.2770

### Operating System

Windows 10 (64bit)

**Comment by coornio** [comment]
Semi transparent textures (alpha of 127) is what you're supposed to get because that's how the PS2 itself works. Ask on discord for some guides on this topic to get you started. Not an issue otherwise.
