### ISSUE TITLE
DT Racer craches with GSdx: out-of-memory error

### ISSUE THREAD

**Issue by joder666** [PCSX2/pcsx2#613]
Issue: Running DT Racer with gsdx software mode will spam the log with "GSdx: out-of-memory error texturing temporarily disabled"  and eventually crashing the emu.

To reproduce just run the game with gsdx either 9 or 11 software.

Build used: pcsx2-v1.3.1-556-g819133e, default options.

Plugins settings: SPU2-X, interpolation 1; module xaudio2; synchronization async. 
Every other plugin set to default settings.

Log:
https://www.mediafire.com/?g2np954hhmvby3c

My PC: i5 2500, Zotac Gtx 560 ti AMP, 8gb ddr3, windows 7 x64

**Comment by gregory38** [comment]
Note for the future. Maybe we can adapt GL code to monitor texture RAM in SW renderer too. And from time to time purge the texture cache.

**Comment by refractionpcsx2** [comment]
Is this still happening on new builds?

**Comment by joder666** [comment]
I did another test using a diferrent PC, Core2Duo E7400, 4gb memory, GTX 560 TI.
It seems fixed with this one https://github.com/PCSX2/pcsx2/commit/9f291a6666e6f6401a8acf6aa8caa92269e34bb7.

Now i noticed another issue, probably unrelated or known, which i don't recall happen before. 

Wrong shadows and blur:
http://www.mediafire.com/view/41avziuy9m20d75/gsdx_20150820143504.bmp
http://www.mediafire.com/view/jtlv1ae2hyh20tx/gsdx_20150820143614.bmp
http://www.mediafire.com/view/98psx2y3xgm5zhp/gsdx_20150820143741.bmp

**Comment by gregory38** [comment]
You mean in SW mode? @gabest11 it seems it is a new regression for you.

**Comment by joder666** [comment]
Yes, SW mode both dx9/11.

**Comment by gregory38** [comment]
If you can find when the behavior happened, it will greatly help.

**Comment by joder666** [comment]
I made a mistake, shadow and blur problem is not a regression, it is present in every build i've tested this game since i knew it became playable with https://github.com/PCSX2/pcsx2/commit/2f20e6da655408431407df7e0a27ba8ee9facde2

Just now i tried with https://github.com/PCSX2/pcsx2/commit/4211d51f0709facbfbf5d7c9deda7d01ab345bb1 https://github.com/PCSX2/pcsx2/commit/e17ba1c143da1efc0ad0d36c8e33ebd774f01b76 https://github.com/PCSX2/pcsx2/commit/93168069db026e216f6dd9c4dfec29517a8b6203 https://github.com/PCSX2/pcsx2/commit/819133ee45834548bd5e4f248c0234584cb0ebb5 https://github.com/PCSX2/pcsx2/commit/80b24f80555d21bbf31d6a78a016898a9e3f798e https://github.com/PCSX2/pcsx2/commit/b2576cd8bbf5ecbb8914560f8f435f59fa08546e, the oldest one available in orphis bot, plus old svn revision 1.2.1-r5873 and 1.0.0-r5350, this last one does not get past the "press start" screen.

I tested each one twice. One with both VU set to "superVU recompiler" and another with defaults settings.

**Comment by gregory38** [comment]
Ok. Hum, I potentially know the issue for the shadow (JAK game). And I suspect it is also related to the blur.

**Comment by lightningterror** [comment]
Is this still an issue ?

**Comment by MrCK1** [comment]
I ran the game not too long ago and didn't run into this issue. Closing for now unless a user reports otherwise.
