### ISSUE TITLE
[BUG]: Widescreen patches not being applied when file extension .pnach is in caps

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#6139]
### Describe the Bug

Widescreen patches are not being applied when file extension .pnach is in caps, changing them to lowercase seems to fix the issue. Occurs with QT and wxWidget nightly. 

### Reproduction Steps

Load Gauntlet Dark Legacy USA with widescreen patches enabled. It won't be applied. Change the file extension for the game in the zip folder to lower case. It will then be loaded.  

### Expected Behavior

NA

### PCSX2 Revision

v1.7.2775

### Operating System

Windows 10 (64bit)

**Comment by BParks21** [comment]
I've already went through the zip and corrected all the .pnach files that had the extension in caps. So if it's as simple as uploading it I can do that.

**Comment by BParks21** [comment]
Anyone :(

**Comment by refractionpcsx2** [comment]
I'm not  having any issue loading a pnach with upper case, I have 

6E8BAF03.PNACH

Are you sure your patch works?

**Comment by BParks21** [comment]
Yes. First screenshot is with 15030637.PNACH left the way it's included with pcsx2 in the zip and the second is after renaming the file extension in lower case. When it's in caps there is no notification that it's being loaded and applied and it isn't but when it's corrected the notification appears and it  is clearly active. 
![gs_20220527195833_Gauntlet - Dark Legacy_SLUS-20047](https://user-images.githubusercontent.com/12180630/170801613-a15f6c80-aef1-4de3-950c-e8a8cba6f2af.png)
![gs_20220527195636_Gauntlet - Dark Legacy_SLUS-20047](https://user-images.githubusercontent.com/12180630/170801621-0e6f1a2a-9d4d-4661-b21f-0a99f26370bf.png)

**Comment by refractionpcsx2** [comment]
Should be fixed in https://github.com/PCSX2/pcsx2/pull/6227

**Comment by BParks21** [comment]
> Should be fixed in #6227

Thank you very much. I was keeping a backup of my ws zip and was having to copy it over each time pcsx2 updated.

**Comment by refractionpcsx2** [comment]
If you could test the PR once the builds are built and confirm it fixes it for me, that'd be great :)

**Comment by BParks21** [comment]
Sure np.

**Comment by refractionpcsx2** [comment]
I'll close it with the PR :P but thanks for checking
