### ISSUE TITLE
[BUG]: (Qt) Frame pacing settings resets on every launch

### ISSUE THREAD

**Issue by rhobiusvoid** [PCSX2/pcsx2#6147]
### Describe the Bug

One of the better options that came with the update, the frame pacing configuration, seems to reset on every boot-up in an unusual manner.
![image](https://user-images.githubusercontent.com/22803374/169812852-368c1cef-fe13-41f4-b90d-76e255a13550.png)
When setting MFL to 0, closing and opening the emulator will cause it to automatically enable 'Optimal Frame Pacing' regardless of whether or not I ever wanted the option enabled. The "Adjust To Host Refresh Rate" keeps getting disabled as well, despite how smooth it makes gameplay on higher refresh rate monitors.

None of the other settings seem to be getting reverted, so what's with this one? A good explanation for why this happens would also be nice.

### Reproduction Steps

1. Open "Settings" and go into "Emulation."
2. Disable "Optimal Frame Pacing" and set "Maximum Frame Latency" to 0. Also enable "Adjust to Host Refresh Rate."
3. Close the emulator.
4. Re-open the emulator, and repeat Step 1.
5. The settings should then have gotten reverted back.

### Expected Behavior

Well, the expected behavior is that they should obviously keep themselves configured without resetting.

### PCSX2 Revision

1.7.2775

### Operating System

Windows 10 (64bit)

**Comment by Tzerinas** [comment]
As far as I understand it activating Optimal Frame Pacing is pretty much the same thing as setting MFL to 0.

**Comment by rhobiusvoid** [comment]
Really? Kinda counter-intuitive that it sets MFL to 2. There's not really any documentation or info I saw about how it actually works and generally whenever I hear 'frame pacing' I just switch it off (plenty of experience with Moonlight GameStream to know that I don't want that).
