### ISSUE TITLE
Deus Ex: The Conspiracy - Skipping audio issue

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#615]
Basically the spoken dialog skips at certain moments as if the audio file is played from half-way instead of beginning.
Most obvious in the first level.
https://www.youtube.com/watch?v=BnHZoO8HOxU

Tried all options in SPU2-X.
And yes ZeroSPU2 has same issue.

**Comment by refractionpcsx2** [comment]
When you say you tried all options, does that include time stretch? Did you have your framelimiter on to lock it at 50/60 fps? are you using any speedhacks?

Need much more detail please.

**Comment by Blackbird88** [comment]
Yup time stretch too.

**Comment by karasuhebi** [comment]
So is this a core issue or an issue with both SPU plugins?

**Comment by Blackbird88** [comment]
Well I don't know if it's core issue, but both SPU plugins suffer from it if you read my post :)

**Comment by karasuhebi** [comment]
Yeah that's why I was asking, since you had mentioned that you tried both SPU plugins and the issue was still there.

**Comment by Blackbird88** [comment]
Hmm now that I think about it I didn't try messing with superVU or the clamping modes for the hell of it.

**Comment by atomic83GitHub** [comment]
There is a meta for that problem, it can be close I think.

**Comment by MrCK1** [comment]
@Blackbird88 Can you retest on latest master please?

**Comment by Blackbird88** [comment]
Test with 3d43293 and it's finally fixed!
