### ISSUE TITLE
[BUG]: Games Unlaunchable on XAudio2

### ISSUE THREAD

**Issue by defski** [PCSX2/pcsx2#6150]
### Describe the Bug

When the audio output module is set to XAudio2, PCSX2 crashes when launching any game.

### Reproduction Steps

- Set audio output module to XAudio2
- Launch iso

### PCSX2 Revision

v1.7.2773

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Confirmed, it's not a happy bunny
