### ISSUE TITLE
[BUG]: Spyro: Enter the Dragonfly TLB MISS / CRASH

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6158]
### Describe the Bug

This is an old, known issue. The game does stupid things that the emulator doesn't like with its reads. A gamedb patch was written long ago to do away with the brunt of it (afaik), leaving only a minor part that could be seemingly safely ignored:

```...
LOAD AUDIO ASSETS
(EE pc:002C7D20) TLB Miss, addr=0x8 [load]
(EE pc:002C7E00) TLB Miss, addr=0x8 [load]
(EE pc:002C7E24) TLB Miss, addr=0x0 [load]
Out of load.
...
```
Up until 1.7.2759 these weren't an issue and the game would boot normally despite them. Past that point however, TLB misses are no longer forgiving and outright let the emulator crash, hard. 

I have created this issue so that the problem stays up in the air until a new patch can be made, or until some changes in emulation allow the program to safely ignore the bad juju that's thrown its way like the console did.

### Reproduction Steps

Start the game, speed through the company logos, then await the crash at the loading screen.

**Comment by refractionpcsx2** [comment]
Although there is a bug in the TLB misses happening (which has a fix incoming soon), the game is broken, the patch doesn't really help on the PAL version, as a TLB Miss *should* be fatal.
