### ISSUE TITLE
[BUG]: Qt Copying cover already in /covers/ folder

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#6159]
### Describe the Bug

If you try to add a cover which you've put in the covers folder already, it still tries to copy on to itself causing it to crash

### Reproduction Steps

put an image in the /covers/ folder, then try to assign it to a game.

### Expected Behavior

ignores the copy and just assigns the picture

### PCSX2 Revision

1.7.2788-Qt

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Results in an error instead of crashing as of v1.7.3994.

![image](https://user-images.githubusercontent.com/80843560/216150007-b3afbdf5-a2b3-49d8-ba6e-0024ca3f22b0.png)
