### ISSUE TITLE
[BUG]: (Qt) Can't change language and check "hide cursor"

### ISSUE THREAD

**Issue by Dark9715** [PCSX2/pcsx2#6167]
### Describe the Bug

Can't change language and check "hide cursor"

### Reproduction Steps

Click Language do nothing
![Immagine 2022-05-24 155715](https://user-images.githubusercontent.com/106165398/170053353-e3ce727e-e3ef-4d95-abe3-9913c549d52c.jpg)

### PCSX2 Revision

v.1.7.2790

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Invalid. Neither of these are implemented yet, and are on the TODO list here: https://github.com/PCSX2/pcsx2/discussions/5947
