### ISSUE TITLE
[BUG]: Rock Band Track Pack - AC/DC Live has a slash in the name so covers don't work

### ISSUE THREAD

**Issue by taneofpain** [PCSX2/pcsx2#6170]
### Describe the Bug

Unable to create a cover file in Windows for this disc because Windows doesn't support \ within filenames

### Reproduction Steps

Select cover image and get Failed to copy cover.png to pcsx2\covers\Rock Band Track Pack - AC\DC Live.png

### Expected Behavior

Able to add a new cover. I assume the fix is to rename the entry so it doesn't have a slash in it?

### PCSX2 Revision

v1.7.2790

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
Already addressed in https://github.com/PCSX2/pcsx2/pull/6157
