### ISSUE TITLE
[Feature Request]: Per-game controller settings

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6171]
### Description

Per-game controller settings would be a very handy feature.

### Reason

I just noticed that there isn't any option to have personalized controller settings for each individual game. This is very important since every game has it's own controller scheme and one global setting is not quite suitable for every game.

### Examples

-

**Comment by refractionpcsx2** [comment]
Per game profiles are now available in the Qt interface

**Comment by Rex000** [comment]
But this isn't about per-game profiles, it's about per-game controller settings.

**Comment by Rex000** [comment]
But this isn't about per-game profiles, it's about per-game controller settings. I just checked but there is no option for that.

**Comment by auriana-schissler** [comment]
He was asking specifically about per-game controller settings, which don't seem to have any presence in the game-specific settings.

**Comment by Mrlinkwii** [comment]
@auriana-schissler it dose 
![image](https://user-images.githubusercontent.com/17685135/203068317-6f110e8b-ba8b-4648-828b-a3b382f7f33b.png)

**Comment by auriana-schissler** [comment]
So it does. Thank you.
