### ISSUE TITLE
[BUG]: Bluetooth controller input not recognised on M1 MacBook Pro

### ISSUE THREAD

**Issue by Nodgers** [PCSX2/pcsx2#6172]
### Describe the Bug

I am using a 2020 M1 MacBook Pro to run the nightly MacOS (20220410) build of PCSX2. I have an Xbox Series X Bluetooth controller connected, but when I go to configure the joypad none of my inputs are registered. The controller works in other applications on the machine, such as Steam.

### Reproduction Steps

1. Connect an Xbox Bluetooth controller to an M1 MacBook Pro running Mac OS 12.4
2. Open PCSX2
3. Go to Config > Gamepad Settings
4. Select any button mapping on the interface
5. Press any button on the Xbox controller
6. No inputs are recognised and eventually the cursor will pinwheel until you press a keyboard key

### Expected Behavior

Controller input should be recognised by the Gamepad Settings

### PCSX2 Revision

Nightly - macOS - 20220410

### Operating System

macOS (Monteray)

**Comment by Mrlinkwii** [comment]
mac PAD  is auto mapped  , theirs no manual mapping
