### ISSUE TITLE
[BUG]: Shadow Hearts Covenant shadow issue

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#6175]
### Describe the Bug

Shadows are broken on hw mode.

### Reproduction Steps

Open the game, start the game. it can be fixed by going into software mode and into hw mode again, but it breaks again after a while.

### Expected Behavior

Normal shadows

### PCSX2 Revision

v1.7.2794

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

RTX 3060ti

### Emulation Settings

![image](https://user-images.githubusercontent.com/72826232/170118119-042fdadd-42c6-48a8-a957-9e3e5f47327f.png)
![image](https://user-images.githubusercontent.com/72826232/170118141-b8d860e8-c491-4cda-97b5-76cc2fed3c69.png)
![image](https://user-images.githubusercontent.com/72826232/170118177-1de1b2ca-69b1-4e8c-a7c2-9af59c67ebf1.png)

### GS Window Screenshots

![gs_20220524213302_Shadow Hearts - Covenant _Disc1of2__SLUS-21041](https://user-images.githubusercontent.com/72826232/170118221-28740940-56f5-4534-a2d2-7bede1e29e9f.png)
![gs_20220524213309_Shadow Hearts - Covenant _Disc1of2__SLUS-21041](https://user-images.githubusercontent.com/72826232/170118225-58144c27-4992-43fb-ab14-47df172a8a2a.png)

### Logs & Dumps

[gs_20220524213302_Shadow Hearts - Covenant _Disc1of2__SLUS-21041.zip](https://github.com/PCSX2/pcsx2/files/8765721/gs_20220524213302_Shadow.Hearts.-.Covenant._Disc1of2__SLUS-21041.zip)

[gs_20220524213309_Shadow Hearts - Covenant _Disc1of2__SLUS-21041.zip](https://github.com/PCSX2/pcsx2/files/8765717/gs_20220524213309_Shadow.Hearts.-.Covenant._Disc1of2__SLUS-21041.zip)

**Comment by refractionpcsx2** [comment]
IF you enable manual hardware renderer fixes, then go to the renderer fixes tab and tick "Disable Partial Invalidation" does it fix it?

**Comment by NineKain** [comment]
Yes!, it seems like it, ill test it further to be sure

**Comment by NineKain** [comment]
Seems it didnt fix it fully, at least with Half Pixel Offset on

**Comment by refractionpcsx2** [comment]
As I'm sure I said earlier, Half Pixel Offset Normal (Vertex) breaks it. So it needs to either be off or hope Special (Texture) works.

**Comment by NineKain** [comment]
Oh, my bad, sorry Refraction

**Comment by refractionpcsx2** [comment]
sooo, does Half Pixel Offset fix anything when it's on? is it required? did special fix it? or was "off" fine?

**Comment by NineKain** [comment]
Normal makes the game much sharper, and I dont notice any difference between off and Special/Special Agressive

**Comment by BParks21** [comment]
Wait so was this supposed to fix the shadow issues in the game even with manual hardware fixes unchecked?

**Comment by refractionpcsx2** [comment]
Can you provide GS dumps for those games where it breaks in a new issue please? then we can look in to it.  Half Pixel Offset was enabled in them to reduce ghosting, I guess we need an alternative solution.

**Comment by BParks21** [comment]
> Can you provide GS dumps for those games where it breaks in a new issue please? then we can look in to it. Half Pixel Offset was enabled in them to reduce ghosting, I guess we need an alternative solution.

Yes because Disable Partial Invalidation has no effect when on or off for fixing these shadows when Half Pixel Offset Normal (Vertex) is forced on by default for these games. Shadow hearts seems fine when using both TC Offset axis to 350. Gets rid of the blurriness without breaking shadows.

**Comment by NineKain** [comment]
Shadow Hearts works fine with Texture Offsets 350, the thing that breaks shadows is Half Pixel Offset in my testing, but since you can't use texture offset on a game by game basis for now, I haven't been able to test much, I don't really know if partial invalidation does anything, but it seems to help.
