### ISSUE TITLE
[Feature Request]: Bios select at per-game settings

### ISSUE THREAD

**Issue by stoniemahonie** [PCSX2/pcsx2#6182]
### Description

Should be able to select a specific bios when using per-game settings.

In an optimal case, the user would be able to have multiple configurations per bios. The generated .nvm file is where the changes are stored i guess.

I think there could be two ways to implement this. Either by having to copy yourself the same bios with a different name in the root bios directory and/or allowing recursive bios folders with a folder per bios.

Or having the option to create per bios settings and include a comment in the configuration (BIOS Selection screen inside pcsx2 qt has "Filename" and "Version", maybe add "Comment/Custom".

### Reason

- How will it make things easier for you?

In germany we had/have censored content in a lot of games. Some of those censored contents (no blood for instance in the game the warriors) could be circumvented by setting the language to english in the bios menu. In wx builds, i copied the bios into a different folder and changed the language accordingly and then set the bios in the corresponding ini configuration file. Also, many games just play better in english bc of not liking the german dubbed voices and in PAL regions alot of games have multiple languages included.

Secondly, some games use the aspect ratio information set in the bios to automatically set the game, for example, to widescreen. Maybe some games even have to boot with the bios set to widescreen to have this option at all.

So i had another copy of the bios for this purpose.

How does this feature help your enjoyment of the emulator?

Im using a frontend for pcsx2 with a lot of configuration files for the various different settings many games require. Per-Game Settings already makes many configuration files obsolete, wich is amazing of course. With having an option for a specific bios config for a specific game this would be perfect in terms of setting up even those edge cases.

### Examples

I dont have examples. Maybe rpcs3 with its "custom configuration" but it is like per-game settings.

**Comment by stenzek** [comment]
Not really possible. Per game settings are applied after the ELF is loaded, which is well after BIOS code runs.

The "best" thing you could do is change the BIOS and reset the console after the game is loaded, and do the whole thing again, which feels a bit hacky.

**Comment by stenzek** [comment]
Could probably leave it open since I did propose a solution, it's just not ideal :)

**Comment by RedDevilus** [comment]
Not sure why you would even want to change BIOS esspecialy when you can do the patch region along with correctly giving language with fastboot which also skips region checks.

**Comment by stoniemahonie** [comment]
Good morning. First, thanks for the replys. Maybe i explained it not good enough.

I use custom configurations for alot of games that have problems and/or need the widescreen option inside the "internal ps2 menu" mentioned in the wiki. Through a frontend i use cmd lines like:

Example 1:
pcsx2 "game" --cfgpath="C:\Users\stoni\Documents\PCSX2\custom inis\Software - Bios EN" --nogui
Corresponding PCSX2_ui.ini bios line:
Bios=\\Users\\username\\Documents\\PCSX2\\bios\\PAL ENG

Esample 2:
pcsx2 "game" --cfgpath="C:\Users\username\Documents\PCSX2\custom inis\Widescreen" --nogui
Corresponding PCSX2_ui.ini bios line:
Bios=\\Users\\username\\Documents\\PCSX2\\bios\\PAL WIDE

And for other games it just uses the bios without aspect ratio or language changed in the root bios folder. The patch region in the qt branch is globally applied if i see this right, so i would have to manually change it, if needed. That would be just handy to have this option inside the per game settings configurable.

**Comment by checktext00** [comment]
> Not sure why you would even want to change BIOS esspecialy when you can do the patch region along with correctly giving language with fastboot which also skips region checks.

what does "do the patch region" mean? how do you do that? Is it just changing the the region in the game properties Region drop-down? What does that change when the game boots?

----

> Not really possible. Per game settings are applied after the ELF is loaded, which is well after BIOS code runs.

DuckStation has a "BIOS" section in its per-game settings window. If it works differently on PCSX2, maybe the BIOS could just be chosen when the PS2 is started with a game already selected. So if I launch a game by double-clicking it (or command line argument) and it has a per-game BIOS, PCSX2 sets that specific BIOS file as the BIOS before launching the emulated PS2

**Comment by F0bes** [comment]
> what does "do the patch region" mean? how do you do that? Is it just changing the the region in the game properties Region drop-down? What does that change when the game boots?

Before I wrote Biosdrain, the old BIOS dumper would read the BIOS from the EE side mapping. On deckard units that would improperly dump firmware with the region as Japan, despite the console being US/EU/etc. I implemented a dropdown that let you change the region of the BIOS to fix this. Once Biosdrain was written it was removed because it was no longer necessary.

**Comment by F0bes** [comment]
If I'm not mistaken, that's just visual. If you have a game that isn't tracked by our game index you can manually set the region.

**Comment by checktext00** [comment]
Oh ok. And again, just out of curiosity, wouldn't the BIOS region have been set based on the hash/checksum of the BIOS that is checked against PCSX2's BIOS database?

**Comment by F0bes** [comment]
There is a specific byte in the BIOS that determines the region.
