### ISSUE TITLE
[Feature Request]: Custom Configuration Boot in the game properties

### ISSUE THREAD

**Issue by Malice27** [PCSX2/pcsx2#6183]
### Description

Every time booting the game, there's a doubt about whether the custom settings work or not working just by double-clicking the game in order to boot in custom settings. 

### Reason

Custom Configuration Boot or whatever the names that lead to booting in customs settings of the game.

### Examples

![Untitled-4](https://user-images.githubusercontent.com/86934784/170236649-c4976bf2-9be9-45c7-a8d4-62d6e21044a5.jpg)

**Comment by refractionpcsx2** [comment]
If you've set custom settings for a game, it'll use them.

**Comment by xproflipscarab** [comment]
I'm guessing what this guy is getting at is having a easy way to quickly boot up the game either with global settings or its per-game config for troubleshooting purposes?

Maybe just having saveable/nameable configs would be a better way to go about it? Like how controller and Hotkey configs are done?

**Comment by refractionpcsx2** [comment]
Untick this?

![image](https://user-images.githubusercontent.com/6278726/182820044-389fd305-fe0e-4c8f-bbdd-1a45d6aaf099.png)

**Comment by stenzek** [comment]
In theory, we could have another config overlay which disables the "enable per-game settings" option, enabled by the menu option.

But personally, I think such a menu option would be confusing. Once you start a game with it, if you forget you did, you'd find that changing settings in game properties had no effect, despite the global "enable per-game settings" option being checked.
