### ISSUE TITLE
[BUG]: (Qt)Emulated controller detected as PS1 digital pad in Ridge Racer V

### ISSUE THREAD

**Issue by stuken** [PCSX2/pcsx2#6185]
### Describe the Bug

Using the Qt interface Ridge Racer V detects the emulated controller as a PS1 digital pad and no analogue controls are useable.
wxWidgets does not have this issue and the game will detect the controller as a Dualshock2.

Happens under both xinput or sdl input, with default out of box keyboard input and after binding controls.

### Reproduction Steps

Automatically bind controller inputs using xinput or sdl as the input source, boot game and navigate to options.
Controller options will display a ps1 contoller and analogue input is not useable.

### Expected Behavior

Parity with wxWidgets where game detects emulated controller as a Dualshock2 and analogue input is available.

### PCSX2 Revision

v1.7.2800

### Operating System

Windows 10 (64bit)

**Comment by stuken** [comment]
Found the inconsistency between qt and wx. wx maps the stick to dpad inputs here:
https://github.com/PCSX2/pcsx2/blob/a26b91291ca4bcdb1a4357863683b4af3a6205c8/pcsx2/PAD/Windows/PAD.cpp#L668-L681

Ridge Racer V is one of those weird edge cases that will forcibly disable analogue so Qt still needs the analogue button exposed through the controller mapping like wx does.

**Comment by stuken** [comment]
I messed around with the default pad state on reset to be analogue and ds2 and the game will send a change mode command with a to digital payload if it finds the pad in either of those states. I dont have access to my old ps2 to 100% verify the behaviour but this lines up with some forum and old gamefaqs posts asking how to enable analogue controls implying that they didnt work out of the box. So it seems to follow from there that the emulation behaviour is correct.

As for the wx side it to isnt setting it to ds2 on boot, I simply didnt notice the difference in control sensitivity from the true analogue mode and the dpad mapping and it does need to be explicitly enabled with the mapped analogue mode button.

This probably isnt a bug, but a feature request for exposing the analogue mode button.

**Comment by RedPanda4552** [comment]
Makes sense. This behavior is in line with what I observed from the PS2 BIOS as well, if you program a controller to report that it is already working as an analog controller, the BIOS will send a request for it to revert to digital, something it will not do if the controller is already reporting digital.

I'm not entirely convinced that this is the full story, but for now I think it's enough to justify a feature request exposing the button. I don't know if I will be the one to do it, but I am watching this issue so if no one beats me to it I may eventually try my hand at this.
