### ISSUE TITLE
[BUG]: King of Fighters XI (Japan) texture bug in Software Mode (HW also with Preloading = none)

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#6192]
### Describe the Bug

Error manifests in the character select screen on the left hand portait.  If you look at the screenshot below there's a slice missing, sometimes displays garbage. All fine in the HW renderers

### Reproduction Steps

Run the GS Dump provided in SW mode, settings don't matter

### Expected Behavior

nice round portrait

### PCSX2 Revision

v1.7.2804

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

Nvidia RTX 2080Ti

### GS Settings

Defaults (doesn't matter)

### Emulation Settings

Irrelivant

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/6278726/170345961-b854d745-0698-4dc7-a8af-18713e746e83.png)

### Logs & Dumps

[KoF11-SWMode Issue.zip](https://github.com/PCSX2/pcsx2/files/8773817/KoF11-SWMode.Issue.zip)

**Comment by Immersion95** [comment]
Are u sure that it works in HW, I have garble graphics in latest nightlies.

**Comment by refractionpcsx2** [comment]
seemed fine for me?

**Comment by Immersion95** [comment]
> seemed fine for me?

I just tried DX12 & Vulkan HW in latest QT and there's garbage instead of that black space.

**Comment by refractionpcsx2** [comment]
![image](https://user-images.githubusercontent.com/6278726/170774579-3daf2206-1605-4679-bb40-a41450e6d056.png)

Looks fine here? I'd check your settings

**Comment by Immersion95** [comment]
> ![image](https://user-images.githubusercontent.com/6278726/170774579-3daf2206-1605-4679-bb40-a41450e6d056.png)
> 
> Looks fine here? I'd check your settings

Found the culprit and it's texture preloading.

**Comment by refractionpcsx2** [comment]
Does it need to be "none" or something? cos mine is set to Full

**Comment by Immersion95** [comment]
"None" is breaking it, everything else is working.

**Comment by refractionpcsx2** [comment]
Yep, can confirm that's busted too, hmm wonder what's happening, might be a caching thing (since we don't cache)

**Comment by refractionpcsx2** [comment]
looks like it was broken by the scissor optimisation in #5930, but it's still broke, i guess it'll need looking in to.

**Comment by refractionpcsx2** [comment]
#6229 Fixes this
