### ISSUE TITLE
[Feature Request]: (Qt) being able to configure Guitar Hero controllers (like the Xbox 360 X-plorer)

### ISSUE THREAD

**Issue by Gagert** [PCSX2/pcsx2#6193]
### Description

It seems like even though my Guitar Hero X-plorer controller is detected in the PCSX2 Controller Settings under the new Qt UI, I can't select a Guitar Hero controller under either Controller 1 or Controller 2 in the Controller Type section. I can as of now only select None or DualShock2 there, unlike while using an older version of PCSX2 without the nice new Qt UI. In the old UI of PCSX2 I can perfectly map the Guitar Hero controllers buttons to PCSX2.

### Reason

It would make it easier to use Guitar Hero controllers with PCSX2 under the Qt UI.

### Examples

Have an option for Guitar Hero controller under Controller Type in PCSX2 Controller Settings in the Qt UI.

**Comment by refractionpcsx2** [comment]
Already tracking here: https://github.com/PCSX2/pcsx2/discussions/5947

We realise Qt isn't feature complete to WX, but we'll get there, it's not finished.
