### ISSUE TITLE
[BUG]: Qt Gamelist incorrect information in properties on duplicate disc

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#6194]
### Describe the Bug

If you have  the same thing in two separate places (for example you have a DVD and CD version of a game) may need to be in different folders, not sure, it gets confused when you right click-> properties on it in the gamelist

According to both entries it is:
Network Access Disc & Hardware - Online Arena ::: E:\PS2\PS2 DVD Games\PS - Network Access Disc v2.0 [SCES 52677] (E).cso ::: D859B1B4 ::: 396.82MB
Network Access Disc & Hardware - Online Arena ::: E:\PS2\PS2 DVD Games\PS - Network Access Disc v2.0 [SCES 52677] (E).cso ::: D859B1B4 ::: 204.43MB

but one is actually E:\PS2\PS2 CD Games\Europe PS2 Network Setup Disc [SCES 52677] (E).cso presumably the smaller one since that's my CD folder.

### Reproduction Steps

Have 2 copies of a the same disc, have it in separate folders (but both scanned folders), let it scan, check the properties on both.

### Expected Behavior

Shows both disc properties separate (I don't expect per-game settings to be separate)

### PCSX2 Revision

1.7.2804

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
as an aside, I was actually trying to reproduce an issue on the forum where there was apparently a Dark Cloud entry showing as Dead or Alive, all the information seems to show as Dead or alive (Some SLPS number I think) but when you run it you do get dark cloud, however I'm unable to reproduce.

**Comment by RedDevilus** [comment]
I have had that before where it showed up as that serial, but I had a broken dump and redumping worked.

**Comment by refractionpcsx2** [comment]
Well I have a dump which is broken and it doesn't show up, as I'd expect, but that's separate. I actually have 4 examples of this

The other 3 are

Zombie Hunters ::: E:\PS2\PS2 CD Games\Zombie Zone - Other Side [SLES 54461] (E).chd
Zombie Hunters ::: E:\PS2\PS2 CD Games\Zombie Hunters [SLES 54461] (E).chd ::: SLES-54461 ::: 3F73B727 :: both 304.21MB
(I should probably delete my duplicate rip lol)

Mobile Suit Gundam - One Year War ::: E:\PS2\PS2 DVD Games\Kidou Senshi Gundam - Ichinen Sensou [SLPS 25478] (J).cso ::: SLPS-25478 ::: 8AD46A5B ::: 2820.70MB
Mobile Suit Gundam - One Year War ::: E:\PS2\PS2 DVD Games\E:\PS2\PS2 DVD Games\Kidou Senshi Gundam Ichinen Sensou [SLPS 25478] (J).cso ::: SLPS-25478 ::: 8AD46A5B ::: 2821.36MB

Tribes - Aerial Assault :: E:\PS2\PS2 CD Games\Tribes - Aerial Assault [SLUS 20149] (U).cso :: SLUS-20149 :: 2B58234D :: 309.29MB
Tribes - Aerial Assault :: E:\PS2\PS2 CD Games\Tribes - Aerial Assault [SLUS 21122] (U).cso :: SLUS-20149 :: 2B58234D :: 329.78MB (might be mislabeled, but yeah, same game)

**Comment by brad86m** [comment]
This happens when using a lot of beta/prototyope releases along with their retail counterpart. The game title entries are the exact same within PCSX2. This is a nuisance when wanting to use separate cover art, too, as it will always use the same art for both.

**Comment by stenzek** [comment]
> This is a nuisance when wanting to use separate cover art, too, as it will always use the same art for both.

Not really. It uses covers in the order of serial -> file title -> game title. If you use different names for the cover filenames for either of the first two, they'll take precedence over the latter.

**Comment by brad86m** [comment]
Would it be possible to change the title of a game within the UI.

**Comment by stenzek** [comment]
No. The title comes from the gamedb. But you can right click in the column list and show the file title instead.

Honestly though, it's not something we're going to care about, because prototypes are usually legally questionable and we have no interest in supporting them/putting ourselves at risk.

**Comment by brad86m** [comment]
Understandable. Thanks for the explanation.

**Comment by refractionpcsx2** [comment]
Apparently doesn't matter anymore so closing.
