### ISSUE TITLE
[BUG]: Lego Racers 2 ocean disappears at certain angles

### ISSUE THREAD

**Issue by JimScript** [PCSX2/pcsx2#6197]
### Describe the Bug

In Lego Racers 2, at certain angles, the ocean will completely disappear in any renderer.

### Reproduction Steps

Go to the dig-a-brick arcade course in sandy bay and at the first turn go straight and see the beach. Alternate left and forward to see it disappear and reappear.

### Expected Behavior

The ocean to stay rendering at all times.

### PCSX2 Revision

AVX2-Qt-v1.7.2810

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 2070 Super

### GS Settings

Software default as this game can't render fully in hardware mode.

### Emulation Settings

+2 EE cycle rate for higher ingame FPS and MTVU hack, but neither of these affect the ocean.

### GS Window Screenshots

Ocean there:
![gs_20220525225833_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/170428465-0eb27aa7-ae86-430d-ba79-2c88a21b2015.png)

Ocean gone:
![gs_20220525225846_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/170428492-dffbcd18-1ec3-44f9-9294-0bf95eaf01f7.png)

### Logs & Dumps

Ocean there:
[gs_20220525225833_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/8776707/gs_20220525225833_LEGO.Racers.2_SLUS-20042.zip)

Ocean gone:
[gs_20220525225846_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/8776710/gs_20220525225846_LEGO.Racers.2_SLUS-20042.zip)

**Comment by coornio** [comment]
I would like to add that this game appears to have more issues than that. It doesn't seem to upscale at all. In fact, I think it only does so in a square on the top left corner, not the whole screen. See example image and **zoom in**, it's hard to spot.

![gs_20220526122056](https://user-images.githubusercontent.com/11655762/170459138-79a77a74-43fc-413a-a73d-06b9581288d0.png)

**Comment by refractionpcsx2** [comment]
can you enable file logging, then make that happen in the game again, then close the emu and find the emulog.txt in the logs folder and upload it here, please.

I'm not sure a GS Dump is much use here.

**Comment by JimScript** [comment]
Yes, sorry, here is a log of it happening:
[emulog.txt](https://github.com/PCSX2/pcsx2/files/8777982/emulog.txt)
Also I noticed that the car's shadow disappears with the ocean.

**Comment by refractionpcsx2** [comment]
damn no messages I was hoping for.

okay if you can get in to a position where the bit of ocean disappears, then try playing with the VU and EE clamping modes, if that doesn't do much try the same with the Rounding modes (do VU first), see if anything helps.

**Comment by JimScript** [comment]
Sorry, but I tried all of the rounding and clamping modes and didn't see any difference.

**Comment by refractionpcsx2** [comment]
RIP.  I dunno where the error is coming from then...

**Comment by JimScript** [comment]
I notice when I am driving around the beach in circles it stays gone, but when I drive away from the beach it comes back. Away from the beach the ocean stays in place, so maybe an object is conflicting with the ocean and car shadows that is on the beach.

**Comment by refractionpcsx2** [comment]
Yeah there's some sort of calculation error or something, I don't know what. I tried messing with all our available gamefixes, rounding, speedhacks etc and nothing even phases it.

**Comment by JimScript** [comment]
I think the cave might be messing up the ocean in some way, because when it is out of render distance the ocean is fine, but otherwise it is gone.

**Comment by prafullpcsx2** [comment]
Does this happen at the start of the game? Can you upload a memory card save where this happens?

**Comment by refractionpcsx2** [comment]
yeah if you start the game in adventure mode, turn literally like 100 degrees to the right once you gain control and just drive forward, you'll come across a cliff where the water is disappearing below the sand.

**Comment by prafullpcsx2** [comment]
Yeah, did some good testing with this. Seems to be happening forever. Even tried real ps2 and ps3 and the bug doesn't happen on them.

**Comment by JimScript** [comment]
I think the conflicting effect is either the alpha test vines on the arch, or more likely the heightmap hole necessary for the cave to exist.

**Comment by JimScript** [comment]
Well it wasn't the alpha test thing:
![gs_20220529175823_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/170900105-5c91d6a9-d7fe-45db-87a8-4d1cabaaf8ff.png)

But I think there might be a culling portal problem with the caves, here are some other examples of it breaking down:
![gs_20220529180650_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/170900164-287b3b68-41ae-4e9d-959c-40171a88b4b7.png)


![gs_20220529180709_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/170900171-46ea8636-5970-41ba-ba3b-26523c309ff7.png)

**Comment by JimScript** [comment]
I don't know when exactly this was fixed, but recently it is fine:
![LEGO Racers 2_SLUS-20042_20221122180653](https://user-images.githubusercontent.com/66685584/203456739-6849aac3-2128-4c5d-bd15-3361493c2108.png)

**Comment by JimScript** [comment]
I did a little testing and found that #7383 was the pull that solved this issue, so now I can close it(unless there is something else I'm missing).

**Comment by refractionpcsx2** [comment]
Neat! Thanks :)
