### ISSUE TITLE
[BUG]: Z-fighting in Digimon World Data Squad

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6200]
### Describe the Bug

As the title implies. When the game does a flyover of the area in the main menu, certain parts of the terrain and models have certain triangles of their mesh flash due to Z-fighting taking place. The same does not occur in software, even prior to the #6033 PR being merged.

Here's a dump, and a quick vid.

https://www.mediafire.com/file/n5gxiyv1qdmh22t/gs_20220525201344_Digimon_World_-_Data_Squad__NTSC-U__SLUS-21598.gs.zst/file

https://user-images.githubusercontent.com/11655762/170464890-29b43210-0fb3-486c-a0be-729c2397bd56.mp4

### Reproduction Steps

Boot up the game, then wait out the main menu till it goes into intro cutscene again. Every time it does so, it will do a flyover of a different ingame area. The issue was noticed in the 2nd area (forest) but may show itself in other areas too.

### PCSX2 Revision

1.7.2812

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by stenzek** [comment]
The GSdump does not appear to be from the same scene as the video.

**Comment by coornio** [comment]
> The GSdump does not appear to be from the same scene as the video.

ref pointed out and was fixed, you just caught it at an inopportune time, refresh :P

**Comment by stenzek** [comment]
Looks like bog standard z-fighting:

Draw before:
![image](https://user-images.githubusercontent.com/11288319/170472198-edd6bc2a-85c3-4a69-96b7-27f3d6ba88ee.png)
and after:
![image](https://user-images.githubusercontent.com/11288319/170472217-90cc7100-b3f3-469f-84a5-5e28bdc521e4.png)
where the depth test is failing:
![image](https://user-images.githubusercontent.com/11288319/170472238-a2baee41-0fc5-4618-b3d1-1cd69fbdeb3b.png)

**Comment by coornio** [comment]
Aw shoot, this will remain unfixed until the future somehow brings double precision to hardware rendering like in software then :P

**Comment by lightningterror** [comment]
Closing in favor of meta issue.
