### ISSUE TITLE
[BUG]: Flickering cyan line in TAZ WANTED (software only)

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6201]
### Describe the Bug

As the title describes, software mode results in me, personally, witnessing a column of cyan pixels flickering on the leftmost edge of the screen. See crop of video:

https://user-images.githubusercontent.com/11655762/170484668-01f1b01c-241e-4f2f-a9c1-56644329b97b.mp4

Static image along with dump:
[gs_20220526144647_Taz Wanted _NTSC-U__SLUS-20236.gs.zip](https://github.com/PCSX2/pcsx2/files/8778797/gs_20220526144647_Taz.Wanted._NTSC-U__SLUS-20236.gs.zip)

![gs_20220526144647_Taz Wanted _NTSC-U__SLUS-20236](https://user-images.githubusercontent.com/11655762/170484767-a7bd8de3-c0ff-440a-8b19-dcdd59bb0345.png)

Both link and jordan have been unable to reproduce this on their end. I am not certain what's going on with this. It *can* be hidden away with Screen Offsets enabled as it shifts the image a pixel to the left.

### PCSX2 Revision

1.7.2812

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by refractionpcsx2** [comment]
The flickering line could possible be related to #3658

**Comment by coornio** [comment]
> The flickering line could possible be related to #3658

That looks identical and it might well be that PR you isolated in your reply there. What I find odd is that at least two other people who tested the dump were unable to reproduce the bug, implying that there's some variable that's gone unnoticed.

**Comment by coornio** [comment]
Added note that I figured out why there's a difference in the dithering pattern. The game requires MAXIMUM BLENDING to get it right. Wow.

**Comment by Mrlinkwii** [comment]
Dose this still happen on latest nightly :) ?

**Comment by coornio** [comment]
It appears to have been rectified at some point, so we're all good on this now :)
