### ISSUE TITLE
[Feature Request]: (Qt) download widescreen and interlacing patches from within the launcher

### ISSUE THREAD

**Issue by powerpuffboysz** [PCSX2/pcsx2#6203]
### Description

would it be possible to add a setting that would download and update the databases for widescreen and interlacing patches?

### Reason

being able to download widescreen and interlacing patches from within the emulator would save a lot of headache for those who don't know where to look for the patches on the pcsx2 forums

### Examples

similar to rpcs3's (cheat/hack) patching system where it automatically downloads and/or updates the existing database of patches

**Comment by refractionpcsx2** [comment]
We will periodically update the databases that come with the emulator, so you will get the new patches then, there's no real need for a separate option.

**Comment by powerpuffboysz** [comment]
> 

yeah, i'm an idiot and found them in the resource folder. in my defense though they used to be in the root of a pcsx2 installation

**Comment by RedDevilus** [comment]
Because they aren't meant to be tampered with, you should use the folder variants if you want to deviate from the pre-included zips.

It's just that users can't seem to not stop touching it. So the less people know where it is the better.
