### ISSUE TITLE
[BUG]: Visual glitch grid F1 06

### ISSUE THREAD

**Issue by JCMir98** [PCSX2/pcsx2#6204]
### Describe the Bug

When running F1 '06 (Europe) in v1.7.2812 (and now also in v1.7.2813), the background of the table showing the starting grid turns red/pink, when it should be white (as is the case in v1.6).

As far I could tell, that is the only bug when running F1 '06 in PCSX2.

### Reproduction Steps

Load F1 '06,  start a Quick Race and when the race loads it will show the starting grid.

### Expected Behavior

The background for the graphic showing the starting grid should be white.

### PCSX2 Revision

v1.7.2813

### Operating System

Windows 11

### CPU

Ryzen 7 5080

### GPU

RTX 3060

### GS Settings

Only non-default graphic settings I'm running is 6x native resolution. I did, however, try to fix the problem by changing the resolution (first to 3x and then to native) and the problem persisted.

### Emulation Settings

All default.

### GS Window Screenshots

Screenshot in v1.6:
![f1 06 in pcsx2 v1 6](https://user-images.githubusercontent.com/106349704/170573128-d2f519a2-c85f-487e-8d03-1504ccb2f599.png)

Screenshot in v1.7.2813:
![f1 06 in pcsx2 v1 7](https://user-images.githubusercontent.com/106349704/170573159-5651eba6-25b8-440a-aa86-edfe1f930ffd.png)

### Logs & Dumps

![gs_20220526212921_F1 _06_SCES-53950](https://user-images.githubusercontent.com/106349704/170575043-c10e59d9-a9bf-42f6-9ece-90c2b3544d19.png)

**Comment by Mrlinkwii** [comment]
can you post a GS dump :) , if your using QT its debug> single frame GS dump

**Comment by prafullpcsx2** [comment]
Don't use forced bilinear filtering

**Comment by MrCK1** [comment]
Closing as invalid, see solution above
