### ISSUE TITLE
[BUG]: "IR Screenshots" option doesn't seem to do anything

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6205]
### Describe the Bug

1. Enabling or disabling the option doesn't make any difference in the output of screenshots taken.

IR Screenshots Disabled:
![gs_20220527010938_WWE SmackDown_ vs  RAW_SLUS-21060](https://user-images.githubusercontent.com/28770012/170572511-48347cfb-98c3-4281-974c-c733a2e41f5c.png)

IR Screenshots Enabled:
![gs_20220527011000_WWE SmackDown_ vs  RAW_SLUS-21060](https://user-images.githubusercontent.com/28770012/170572534-df9f0b26-a1d9-49d4-9e3a-9b2c456a310f.png)

2. Same case with 16:9 aspect ratio. Also, when Widescreen Patches are enabled along with a 16:9 aspect ratio, the screenshot output is still yielded in a 4:3 aspect ratio.

IR Screenshots Disabled:
![gs_20220527010505_WWE SmackDown_ vs  RAW_SLUS-21060](https://user-images.githubusercontent.com/28770012/170572867-53f6c020-60ff-4db5-bc05-0c1c6791ff48.png)

IR Screenshots Enabled:
![gs_20220527010545_WWE SmackDown_ vs  RAW_SLUS-21060](https://user-images.githubusercontent.com/28770012/170573035-59ba965f-12b0-4d94-b9e6-c4191b87de82.png)

### Reproduction Steps

Try taking screenshots with "IR Screenshots" enabled and disabled, in both regular aspect ratio as well as with widescreen. Also try with Widescreen Patches enabled and disabled.

### Expected Behavior

Screenshots should have the correct aspect ratio and internal resolution set by the user, and should also take into account any widescreen patches applied.

### PCSX2 Revision

v1.7.2813

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
Is this still an issue ?

**Comment by stenzek** [comment]
Nope. Implemented in https://github.com/PCSX2/pcsx2/pull/7564.
