### ISSUE TITLE
[BUG]: (Qt) Mouse cursor doesn't hide itself

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6207]
### Describe the Bug

In the non-Qt build it auto-hides itself after 2 secs of inactivity, but in the Qt build it doesn't.

### Reproduction Steps

Notice the mouse pointer in any game.

### Expected Behavior

The mouse pointer will not hide itself.

### PCSX2 Revision

v1.7.2813

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Yes we know, we have a menu option disable for it because it's not implemented yet.

Being tracked here #5947
