### ISSUE TITLE
[BUG]: Mana Khemia - Artifacts (Regression?)

### ISSUE THREAD

**Issue by darkxex** [PCSX2/pcsx2#6210]
### Describe the Bug

Hi, this game was previously working fine, so I'm guessing it's a regression issue.

here a video:
https://user-images.githubusercontent.com/17991404/170619114-504db4de-7bd7-4fca-a773-2d704c58885b.mp4

### Reproduction Steps

The bug is appreciated as soon as you begin to control the protagonist. It's just walking around and seeing the artifacts.

### Expected Behavior

No artifacts.
In old versions, this didn't happen, I think you can compare with the last time the game was fixed which was last year, I think...

### PCSX2 Revision

v1.7.2813

### Operating System

Windows 10 (64bit)

### CPU

i7 10800h

### GPU

RTX 3060

### GS Settings

all default

### GS Window Screenshots

![gs_20220526224501_Mana Khemia - Alchemists of Al-Revis_SLUS-21735](https://user-images.githubusercontent.com/17991404/170619788-de0ecb5f-fa4c-48d7-b84a-0f6e66ae9681.png)

### Logs & Dumps

this is a gs dump.
[gs_20220526224501_Mana Khemia - Alchemists of Al-Revis_SLUS-21735.zip](https://github.com/PCSX2/pcsx2/files/8783631/gs_20220526224501_Mana.Khemia.-.Alchemists.of.Al-Revis_SLUS-21735.zip)

**Comment by refractionpcsx2** [comment]
Can you point out the artifact on the picture? are you upscaling? does it happen if you don't upscale?

**Comment by coornio** [comment]
> Can you point out the artifact on the picture? are you upscaling? does it happen if you don't upscale?

![image](https://user-images.githubusercontent.com/11655762/170675820-470b95e9-508c-49bb-82f7-1ea0890de102.png)

Also note how occasionally in the video, sprites (characters) appear to flicker in and out of existence.

**Comment by refractionpcsx2** [comment]
yeah, Prafull pointed it out after I posted this. Some weird things going on.

**Comment by darkxex** [comment]
Original resolution (not upscale) the image despicted the girl arm not exist. (sorry bad english)

**Comment by darkxex** [comment]
https://github.com/PCSX2/pcsx2/pull/6320 this pull fix the game. 
I already tested it.

**Comment by refractionpcsx2** [comment]
There's no need to close the issue, the PR will close it once it gets merged, it's still an issue until that happens.

**Comment by darkxex** [comment]
Lol
