### ISSUE TITLE
[BUG]: Covers separation per Region or Serial Number

### ISSUE THREAD

**Issue by metalslayer** [PCSX2/pcsx2#6212]
### Describe the Bug

I think covers must be separated for every variation of same game using serial number or region.
![2022-05-27_12-39-32](https://user-images.githubusercontent.com/19173199/170674375-f91dd0fa-3293-470b-8a06-ba26c94fad4b.png)
 

### Reproduction Steps

I have all variation of Bloody Roar 3. If I change cover for one of them, they all will change too.

### Expected Behavior

I change cover only for one variation of game, not for all of them

### PCSX2 Revision

v.1.7.2813

### Operating System

Windows 10 (64bit)

**Comment by shikulja** [comment]
https://github.com/PCSX2/pcsx2/discussions/5947#discussioncomment-2800703

As I wrote, it's better to use CRCgame instead of NAMEgame and higher priority than IDgame. it would solve all problems

Identifying covers and hacks by name is very impractical

**Comment by refractionpcsx2** [comment]
well it's prioritising the Serial now. the CRC could have collisions on its own, so not a great solution

but now in order of priority it looks for covers is:

Serial
ISO name
game name

**Comment by metalslayer** [comment]
Rename files to serial numbers fixed my issue, but still...
![2022-05-27_17-13-48](https://user-images.githubusercontent.com/19173199/170718072-53ffa173-dd9d-4c54-87bd-c8c46c395ed6.png)
![2022-05-27_17-16-23](https://user-images.githubusercontent.com/19173199/170718080-1cb7f8c7-2771-434b-8d82-4266a41f5219.png)

**Comment by refractionpcsx2** [comment]
but still what? you have 2 easy ways to make it specific, or you can have 1 generic way. What but is there?

**Comment by refractionpcsx2** [comment]
why is the fix not sufficient for the masses? it seems fine for me?

What do you suggest? CRC? That's even worse than serial.
