### ISSUE TITLE
[BUG]: QT No Command Line support

### ISSUE THREAD

**Issue by RedZombieHD** [PCSX2/pcsx2#6215]
### Describe the Bug

Using Command Lines work in the none QT version, but not the QT Version, anything like "--no-gui" or "--fullscreen" closes the emulator on opening.
Doesn't work as a desktop shortcut, or in a program like LaunchBox

### Reproduction Steps

Desktop shortcut with D:\{emulator location}\pcsx2.exe "D:\{game location}\Who Wants to Be a Millionaire - 2nd Edition (Europe).iso" -nogui -fullboot

### Expected Behavior

Game starts with command line options executed

### PCSX2 Revision

v1.7.2815

### Operating System

Windows 11

**Comment by stenzek** [comment]
Invalid. Qt has command line support, you're just using the wrong parameters.

Start it with -help in a cmd window to see.

**Comment by CookiePLMonster** [comment]
![image](https://user-images.githubusercontent.com/7947461/170692332-770d92d7-116c-44bb-80d5-0b35a37dfe41.png)

Works fine.

**Comment by RedZombieHD** [comment]
Ah I see, I was using the information from the wiki article
