### ISSUE TITLE
[BUG]: Patch Regression, Crashes emulator if '0x' is used

### ISSUE THREAD

**Issue by Tupelov** [PCSX2/pcsx2#6220]
### Describe the Bug

Emulator crashes when loading a pnach.

### Reproduction Steps

1) Add patch to cheats folder
2) Enable cheats
3) Run the corresponding game

### Expected Behavior

Pcsx2 does not crash

### PCSX2 Revision

v.1.7.2815

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
what is the patch?

**Comment by Tupelov** [comment]
Nope its actually a different issue altogether, for some reason pcsx2 wont read the patch correctly if it uses 0x infront of the numbers.
Ive shortened a patch and now it just changes where the heap starts, the game is persona 3

`//
// Expand executable memory size (default: 0x9ACC80)
//
patch=0,EE,0077F494,word,0xAACC80`

**Comment by refractionpcsx2** [comment]
why would it read that? you've created it completely wrong.

please use our forum or discord to help you write a proper patch.
