### ISSUE TITLE
[BUG]: Failed to acquire exclusive fullscreen

### ISSUE THREAD

**Issue by pedroF6** [PCSX2/pcsx2#6222]
### Describe the Bug

Using Command Line when "Fullscreen Mode" is not set to "Borderless Fulscreen", game is not launched in fullscreen and the following error occurs: "Failed to acquire exclusive fullscreen". But if the "Fullscreen Mode" setting is set to "Borderless Fullscreen", the game launch in fullscreen normally 

### Reproduction Steps

pcsx2-qtx64-avx2.exe -fullscreen -- "PathToGame"

### Expected Behavior

Game starts in exclusive fullscreen mode

### PCSX2 Revision

v1.7.2816

### Operating System

Windows 11

**Comment by Immersion95** [comment]
I can confirm this issue but it's not "exclusive" to command line, it produces the same bug if Start Fullscreen" is checked.

After failing, it does work though if I try again to go fullscreen while the game is already started.

DX11/DX12 Borderless with QT doesn't mesh well with Steam Overlay + Vsync and I don't know why, the only solution is Vulkan or DX11/DX12 in Exclusive fullscreen.

**Comment by F0xH0L3** [comment]
Same here, won't work automatically on startup, but will acquire fullscreen manually.
