### ISSUE TITLE
[BUG]: Qt: The "Remove Disc" button does not work.

### ISSUE THREAD

**Issue by SlimDread** [PCSX2/pcsx2#6223]
### Describe the Bug

Launching any disc and attempting to remove said disc from the emulator does nothing.

### Reproduction Steps

Launch any disc, head to the toolbar, press the "Change Disc" button then "Remove Disc."

### Expected Behavior

For the disc to be removed.

### PCSX2 Revision

v1.7.2815

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
I haven't checked this, but you shouldn't need to remove disc, just double click on the one you wanna put in and it will switch.

**Comment by SlimDread** [comment]
You're right, but it's still an issue that needs to be fixed.😛

**Comment by refractionpcsx2** [comment]
oh , of course, it was just a "by the way you should probably do it this way" but yes it's still a bug :P

**Comment by coornio** [comment]
The whole "virtual disc tray" thing is a bit all over the place honestly, it needs a bit of rethinking.
