### ISSUE TITLE
[Feature Request] Display Progressive or Interlaced in Qt

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#6225]
### Description

In the old UI, at the top of the screen it would show "Progressive" or "Interlaced" depending on the game, this can be very useful for testing new no-interlacing patches on Qt

### Reason

I am creating no-interlacing patches and this is way faster than just eyeballing

### Examples

The one in the old ui

**Comment by Mrlinkwii** [comment]
the OSD should tell you :)

**Comment by NineKain** [comment]
Yes! But it wouldnt hurt just a simple "480p" or something just next to the resolution in the bottom right just to be sure :D

**Comment by stuken** [comment]
Enable View->Enable Verbose status and will show it.
