### ISSUE TITLE
[BUG?]: SPS in TAZ WANTED start menu sign

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6226]
### Describe the Bug

When pressing START in the game, the sign breaks into pieces that fall out of view. Sometimes, these sharps appear afflicted with SPS. The reason this is a "BUG?" is because this might have happened on the PS2 as well, I can't be certain. It certainly is tricky to make the sign break in a way so that the pieces trigger this.

To clarify, this occurs in both hardware and software. Upscaling is irrelevant. I attempted all clamping/rounding modes to no success. Turning speedhacks off did nothing. I also attempted all the manual game fixes but still nothing.

Here's a quick recording:

https://user-images.githubusercontent.com/11655762/170798468-a800d4fc-3071-4f35-9c1d-d11c2235e7d0.mp4

And here's the dump. Ignore the weirdly yellow water. It doesn't happen in the game, only in the dump for some reason: https://www.mediafire.com/file/vp5k2laipjq330d/gs_20220528014308_Taz+Wanted_SLUS-20236.gs.zst/file

### PCSX2 Revision

1.7.2815

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by Oymat** [comment]
I know this is an old bug, but i wanna jump into it.
@coornio Can you set vu0 to interpreter and EE clock to +3 and see if there's any change to the sps ?

**Comment by coornio** [comment]
I think I might have tried that combination, but I'm not sure either. I have noticed though that the EE/VU0 settings and rounding/clamping settings appear to have been either removed or hidden in the latest versions' emulation settings so aside from emulation speed, I'm not quite sure how to adjust the rest.

**Comment by Oymat** [comment]
EE clock can be found in --> Settings ---> Emulation ---> EE cycle rate
VU0 Interpreter can be enabled by going into ---> Tools ---> Enabled advanced settings, then after that ---> Settings ---> Advanced ---> untick enable vu0 recompiler

**Comment by MrCK1** [comment]
@coornio are you able to retest this?

**Comment by coornio** [comment]
I imagine you want me to re-attempt it from scratch? For the dump itself still exhibits the issue in there.

**Comment by MrCK1** [comment]
Yeah I think that would be best. If it's a core issue then a GS dump likely won't be affected

**Comment by coornio** [comment]
It seems that it still happens.

Just in case, I'll clarify once more that I'm not even sure if this situation is reproducible on the real hardware. I imagine it isn't, considering at least one other game that I'm aware of where geometry points get cooky at certain camera angles..

**Comment by bigol83** [comment]
I checked with @F0bes gsdump on Ps2 hardware and that "sps" is still there. Also, i checked on Youtube and this videos clearly recorded on Ps2 hardware shows the exact behaviour. I think it can be closed as reproduced on hardware 

https://youtu.be/wUkrnL3XT88?t=2048

![Cattura](https://github.com/user-attachments/assets/92d91862-d83d-4fe7-988c-e2270c4e11ba)

**Comment by Mrlinkwii** [comment]
cool , im gonna close the issue then , thanks for investigating  :)
