### ISSUE TITLE
[BUG]: Dr Muto Texture Cache bug

### ISSUE THREAD

**Issue by simpman** [PCSX2/pcsx2#6228]
### Describe the Bug

I reported this texture cache bug to the awesome PCSX2 discord and they found the source as coming from this commit https://github.com/PCSX2/pcsx2/pull/5930 

It causes a strange texture to overlap the transformation effect when transforming between characters. Occurs even in software mode.

### Reproduction Steps

1. Use recent version after https://github.com/PCSX2/pcsx2/pull/5930
2. Go to part where transformation occurs (~10 minutes) or use save
3. Transform, after enough time the effect will occur
[BASLUS-20458-DrMuto.zip](https://github.com/PCSX2/pcsx2/files/8790261/BASLUS-20458-DrMuto.zip)
r

### PCSX2 Revision

v1.7.2816

### Operating System

Windows 10 (64bit)

### CPU

i7-6700

### GPU

GTX 1660 Ti

### GS Window Screenshots

![gs_20220527183910_Dr  Muto_SLUS-20458](https://user-images.githubusercontent.com/3312809/170804331-5d9c9ca7-88d1-4110-960c-75b272607f2e.png)

### Logs & Dumps

[gs_20220527183910_Dr. Muto_SLUS-20458.zip](https://github.com/PCSX2/pcsx2/files/8790256/gs_20220527183910_Dr.Muto_SLUS-20458.zip)

**Comment by refractionpcsx2** [comment]
#6229 Fixes this
