### ISSUE TITLE
Remove all the old *GPU files which are not needed.

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#623]
Remove the old *GPU files which are currently not needed since the current *GS files do the same thing and the GPU files are probably not useful anymore.

@turtleli 

could you mention the files which are still needed for the PSX emulators to remember the saved settings ? I guess it would be okay to remove all the other *GPU files which are not related to that task then.

**Comment by turtleli** [comment]
The GPU* files are used by the PSX part of GSdx, so they're not removable.

P.S. I think you mean GPU* and GS*, not *GPU and *GS ;)

**Comment by ssakash** [comment]
yeah, you're right. does the PSX part use all of those GPU* files (or) just a specific ones ?

**Comment by turtleli** [comment]
All of them.

**Comment by ssakash** [comment]
I see, @refractionpcsx2 did mention something about splitting them, I guess that would help. :)

**Comment by turtleli** [comment]
Probably #593, where I initially attempted to rip it out.

I did say I was going to investigate splitting it up, but I haven't looked into it and I don't mind if someone else looks into it. Probably best to investigate whether it should be split up or whether more code can be shared before making a decision.

**Comment by ssakash** [comment]
Could this be closed ? PSX code was moved to a different directory on #1369

**Comment by turtleli** [comment]
Didn't you open the issue?

**Comment by ssakash** [comment]
> Didn't you open the issue?

Yes and I personally think it could be closed. but I was waiting for feedback from others ;)

Either way, closing this right now. If anyone has any other issues with the recent split of PSX and PS2 code , please mention and it'll be reopened.

**Comment by MrCK1** [comment]
I know it's not GSdx, but there's some IOP code in `PCSX2/PCSX2` that might be able to be moved to a separate folder.

For example, `IopGte.cpp`? PCSX2 doesn't use it correct? All I know is that the GTE was the PS1's Geometry Transformation Engine.

**Comment by refractionpcsx2** [comment]
> For example, IopGte.cpp? PCSX2 doesn't use it correct? All I know is that the GTE was the PS1's Geometry Transformation Engine.

PCSX2 does use it for PS1 emulation.
