### ISSUE TITLE
[BUG]: .hack//INFECTION - Minimap flickers and loads the wrong texture/sprite issue persists.

### ISSUE THREAD

**Issue by carothersmarx** [PCSX2/pcsx2#6239]
### Describe the Bug

This is the same bug as #6034 and was declared as completed, but the bug still can be reproduced in build [v1.7.2822](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2822)

In a dungeon, the minimap will flicker rapidly and uses the wrong sprite in place of the minimap's sprite. In GSdx software mode, the minimap does not flicker but it loads the wrong texture. The minimap loads the wrong texture and flickers in hardware rendering mode both on OpenGL and Vulkan. This bug only occurs on the dungeon, as the city area minimap and field area minimap renders perfectly.

Tested with default settings, preset is set to Safe (2).

### Reproduction Steps

- Load the game with default settings
- Skip through the intro tutorial and the bug should occur inside the tutorial dungeon. The minimap should be displayed in the top right of the screen. The bug can also be reproduced in other dungeons.
- Alternatively, load the attached save state and the bug should occur immediately
[SLUS-20267 - (38A894C6).zip](https://github.com/PCSX2/pcsx2/files/8791227/SLUS-20267.-.38A894C6.zip)

### Expected Behavior

The minimap loads the correct texture/sprite and does not flicker.

### PCSX2 Revision

v1.7.2822

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux  5.17.9

### CPU

i5-5200u

### GPU

Nvidia GeForce 930m

### GS Window Screenshots

![hardware](https://user-images.githubusercontent.com/70326408/170828251-bd71e9c9-8aac-48e5-bfc3-200e325c2b1c.png)
![software](https://user-images.githubusercontent.com/70326408/170828253-296156fd-860d-4385-9572-9dd161ba216c.png)

### Logs & Dumps

[dot hack infection gs snap.zip](https://github.com/PCSX2/pcsx2/files/8791236/dot.hack.infection.gs.snap.zip)

**Comment by refractionpcsx2** [comment]
Already fixed in 1.7.2823

Can you try it and confirm please.

**Comment by carothersmarx** [comment]
just checked a couple dungeons. it renders as intended now.
