### ISSUE TITLE
[Feature Request]: Creating a Patch Manager.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#6244]
### Description

Currently, PCSX2 has 3 different sources of patches:

- Compatibility (via the GamesDB)
- Widescreen
- No-Interlacing

This approach, while handy, has various problems which gets in the way of the feature:

** 1 - Clobbered git history **

Currently, the GamesDB entries are manually updated through git. With the frequency of such updates (often minor updates which requires a whole pull request), it can get in the way of the repository history reading.

Perhaps creating a separate repository for that would be a solution to this "inconvenience" (not an issue per-say).

** 2 - Compatibility confusions for the end user and testers**

The GameDB stores some patches in order for some titles to work, this approach was "okay" in the past due to a quite large number of games requiring such patches, but now, it's not as much of a big deal, except for COP2 problematic or edge cases titles. 

Those same games sometimes has a " playable" mark associated with them which is ... well, not technically true ^^. The game in question doesn't work with stock settings, I guess this should be taken into account in the compatibility metric.

A better way to handle this, would be to use the patch manager, with a section called "compatibility patches" similar to what RPCS3 does, and letting the user enabling the compatibility patch instead.

Note: this request will only take into account the "patches", not the gamefixes which are fine, given how the PS2's CPU works in regards to rounding/clamping.

** 3 - No auto updating **

Currently, there is no way to update the current patch list without downloading again the whole dev build.

** 4 - Missed Opportunity **

Having a proper patch manager would have an immense benefit, having the ability to have custom cheats, enhancement patches distributed by the PCSX2 team, which would benefit the end-user side of the experience.

A clear example of this are the CookiePLMonster Gran Turismo patches, many peoples could use those just by updating the cheat manager.

### Reason

** 1 - Improving the end-user experience regarding emulation**

Such a feature would allow the end user to benefit from cheats or hencements directly in the emulator frontend, this can represent a serious advantage over playing on real hardware.

Not every users have the ability, nor even wants, to search online for various cheats corresponding to their favorite titles, hence why action replay did exist in the first place.

** 2 - Making comptibility metric more accurate **

Applying a patch at stock settings, in my opinion, can't be considered valid. Those remain patches which modifies how the game works internally, using a cheat manager for these would allow more transparency regarding compatibility, for both the end-users and the testers.

If a game doesn't work properly, the user should ideally be informed of that before (with a proper compat status). It would be up to him to select the patch to get around the compatibility problem, if this is done correctly, it won't be against the end user, far from that actually.

** 3 - Going further on improving the games rendering / performance **

Having a general cheat based database could allow for more specific optional patches, aim to improve the user's experience.

An example of this would be frame-cap patches. I see 3 examples that could benefit from that (amongst others):

- 30 fps cap for Ratchet games. Targeted for low-end CPUs

- A frame cap for the loading screens of Indigo-prophecy

- Removal of post-processing effects in various games (will help regarding this "CRC-hack" situation)

### Examples

In RPCS3, there is a dedicated cheat manager with a continuously evolving online database. This takes into account every aspects of patching, from hencement, to "proper" cheats like you would find on an action replay.

![image](https://user-images.githubusercontent.com/105116470/170837487-940c85cf-ef55-43b6-b943-f925c83eddc5.png)

**Comment by RedDevilus** [comment]
Related to: https://github.com/PCSX2/pcsx2/issues/3900

**Comment by lightningterror** [comment]
> Having a proper patch manager would have an immense benefit, having the ability to have custom cheats, enhancement patches distributed by the PCSX2 team, which would benefit the end-user side of the experience.

The more patches we bundle the more issues they bring and it's a nightmare to maintain.

> Removal of post-processing effects in various games (will help regarding this "CRC-hack" situation).

The patches also remove post processing effects on sw renderers which is not what we want.

Closing, trivial.

**Comment by jeremybris** [comment]
I, as well as many others ([that liked the original post](https://github.com/PCSX2/pcsx2/issues/6244#issue-1251691341)), would've liked to have seen this feature.

In my opinion, "It's too hard" is not a good reason to forgo doing anything. It didn't stop the [RPCS3](https://github.com/RPCS3/rpcs3/pull/8335) or [Cemu](https://github.com/cemu-project/cemu_graphic_packs) developers from creating a maintained patch manager. Removing post processing effects may not be what you want, but at least 6 other people did want this feature. It shouldn't be too hard to have logs say "This patch is enabled" to help with maintenance.

The alternative to a patch manager is going through [480+ pages to find the patch you want](https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here). This is very inconvenient.  The longer this feature is put off, the more patches may be lost to history, should they ever be removed or buried in the internet. So, it is not trivial at all.

**Comment by refractionpcsx2** [comment]
But we already provide patches with pcsx2  and you can enable/disable them per game, what are you talking about?

**Comment by jeremybris** [comment]
[60 F.P.S. patches](https://github.com/PCSX2/pcsx2/issues/3900#issuecomment-1140310604) ? Are those included? For example, recently, I found some patches that increase draw distance in the [Dynasty Warriors](https://gbatemp.net/threads/dynasty-warriors-the-complete-hd-collection.645746/) games. It would just be great, if patches like that were included or could be easily found with PCSX2, so I don't have to scour the internet. (That was my understanding of this original post, with the example of RPCS3 patch manager, described above.) Just my opinion though.

**Comment by stenzek** [comment]
For some games, yes. You can always add your own, if they're not shipped, or PR it to the patches repo.

**Comment by refractionpcsx2** [comment]
60fps, no interlacing, widescreen, all included.  The community is curating them and making sure they work before submitting them, but there's already a lot.

**Comment by jeremybris** [comment]
Ok, forgive my ignorance. I had 60 F.P.S. patches from before when they are included, so I didn't know. I would just love a singular location to find extra patches, like no [motion blur patch of MIdnight club 3](https://forums.pcsx2.net/Thread-MID-NIGHT-CLUB-3-HELP-MOTION-BLUR), but I will settle for the PCSX2 discord and forum, until then. I appreciate all of your guys's hard work.

**Comment by refractionpcsx2** [comment]
if somebody wants to include it and it isn't already in there, then they are welcome to submit it to the pcsx2_patches repo and then it will come with future releases.

As long as there's some utility to the patches, I'm happy for them to be included.
