### ISSUE TITLE
[Feature Request]: updating the Growlanser Generations SLUS-20758 and 20759 names in the game database.

### ISSUE THREAD

**Issue by MelchiorGaspar** [PCSX2/pcsx2#6245]
### Description

for the two PS2 game(s), as English USA releases of Growlanser Generations
---
SLUS-20758:
  name: "Growlanser Generations [Disc1of2]"
  region: "NTSC-U"

and 

SLUS-20759:
  name: "Growlanser Generations [Disc2of2]"
  region: "NTSC-U"
---
they are fully named
Growlanser Generations (Disc 1)(Growlanser II - The Sense of Justice)(USA)(NTSC)(SLUS20758)(v1.03)
Growlanser Generations (Disc 2)(Growlanser III - The Dual Darkness)(USA)(NTSC)(SLUS20759)(v1.03)

so I would suggest they be updated to reflect there full names as the new Qt build displays the database name and not the file name... which is fine.

SLUS-20758:
  name: "Growlanser Generations [Disc1of2] -- Growlanser II - The Sense of Justice"
  
SLUS-20759:
  name: "Growlanser Generations [Disc2of2] -- Growlanser III - The Dual Darkness"

### Reason

Updating these two game names in the PCSX2 game database file
GameIndex.yaml
will make it so they read better and let people better know what they are playing...

### Examples

![image](https://user-images.githubusercontent.com/1712842/170836953-08f76078-0cc1-4ce2-9e74-19d2a51f5745.png)
this it the way it currently is..

**Comment by MelchiorGaspar** [comment]
Thank you for committing my update request.
wow that was fast.. 
You guys are awesome!
^_^

**Comment by refractionpcsx2** [comment]
No problem, we have one of the best guys in the market for updating the gameDB :D

**Comment by MelchiorGaspar** [comment]
> No problem, we have one of the best guys in the market for updating the gameDB :D

nice lol.

**Comment by MelchiorGaspar** [comment]
I just grabbed v1.7.0.2828 and noticed that the Growlanser Generations entries did not update for some reason? :(

![image](https://user-images.githubusercontent.com/1712842/170846199-0b93426c-bc9f-4d65-b18e-1bb9bff4de91.png)

I wonder why.. I even removed the game list settings entry and redid it..
it found all my games but for Growlanser Generations were still only showing the disk game name and disk dumber(s)
but not the game name for each disc like above that I reported for an update...
I'm not sure whats going on...

**Comment by Mrlinkwii** [comment]
@MelchiorGaspar  you have to re-scan for it to update

**Comment by MelchiorGaspar** [comment]
I did that... a re-scan... by removing the game list directory where my game DVD images are located.. and re-added it...
I may have to try deleting the cache file then... brb

is there another way to refresh the cache?

**Comment by refractionpcsx2** [comment]
you could close PCSX2 and delete the gamelist.cache file from the cache folder then rerun the emu

**Comment by MelchiorGaspar** [comment]
> you could close PCSX2 and delete the gamelist.cache file from the cache folder then rerun the emu

lol just did that... and it worked lol

can I make a feature request...?
can we add a feature either in the GameList settings or view drop down menu...
to add a game cache refresh option?
do you need me to start a new issue ticket?

**Comment by MelchiorGaspar** [comment]
ok gamedb.cache too?
I will look for it..

**Comment by refractionpcsx2** [comment]
well no need to do the gamedb.cache one if removing the other one first.

Anyway the rescan should have worked. you did do rescan game directories from Settings->GameList, and not View->Refresh Covers? because they are not the same thing.

**Comment by MelchiorGaspar** [comment]
I could not find gamedb.cache in the cache folder.. just gamelist.cache

ooh duh there is a re-scan option already there....
![image](https://user-images.githubusercontent.com/1712842/170846596-e84fc6a4-bc7d-4386-99df-42dda877c610.png)

so nvm my new feature request lol ;)
