### ISSUE TITLE
[Feature Request]: Option for auto-load state without confirmation

### ISSUE THREAD

**Issue by alondero** [PCSX2/pcsx2#6252]
### Description

In the latest QT build, when starting a game which has an auto save state available a dialog box asks the user whether they want to auto load it or not. I'd rather an option for it to remember my choice or have a default selection so I don't need to use mouse/keyboard (as I'm using it from the couch). An alternative would be to use a dialog box that could be controlled via a gamepad.
It also doesn't seem to prompt for this when starting a game from the command line (for example through an external launcher).

### Reason

Makes PCSX2 more couch friendly

### Examples

Retroarch provides an auto-load state option which works well (yes updates break compatibility but in this case an on screen notification saying it failed to load would be good enough)

**Comment by refractionpcsx2** [comment]
Do you want it to automatically make a state when exiting too? since that's a user choice also.

**Comment by alondero** [comment]
There's already that option in the latest QT build, which is why I think the reciprocal makes sense 👍

**Comment by RedDevilus** [comment]
I remember it used to be an option to not say anything and did savestate on shutdown and load without saying anything, seems that behaviour has been changed

**Comment by stenzek** [comment]
I disagree. There's many reasons you wouldn't want to auto load a state, e.g. if the state was corrupted, state version got bumped, etc.

If you want something navigable by a controller, wait for the big picture UI.

**Comment by alondero** [comment]
> I disagree. There's many reasons you wouldn't want to auto load a state, e.g. if the state was corrupted, state version got bumped, etc.
> 
> If you want something navigable by a controller, wait for the big picture UI.

I understand that there can be problems with save states, but there are already built in checks if the state is corrupted or incompatible with the current version (current a dialog box pops up, which arguably could be an on screen notification instead). 
I think we could still give the user an option for auto load: ask (default), yes, no. 
Another use case for this are portable windows devices (Steam Deck, Aya Neo etc) where people may play for a few minutes at a time, having the quick ability to dive in and jump out without needing to accept a dialog box each time would be handy

**Comment by stenzek** [comment]
The controller argument is kinda void since you're already using the mouse to select the game in the first place.

Like I said, wait for the fullscreen/big picture UI.

**Comment by alondero** [comment]
I actually boot games from the command line via Launchbox. Saying that though, interested by the big picture UI, that sounds like another great improvement for PCSX2. Is there an issue/branch to follow for that?

**Comment by stenzek** [comment]
Again, moot point, if you're using launching via the command line you're not going to get the popup (it autoboots straight to the emucore).

**Comment by Naworm** [comment]
> 

How to do it please

**Comment by refractionpcsx2** [comment]
The github is not for support, if you want help, please use the forum or our Discord.

**Comment by Naworm** [comment]
> The github is not for support, if you want help, please use the forum or our Discord.

Sorry but no conclusion has been given before ticket closure
