### ISSUE TITLE
[BUG]: Mega Man/Rockman X7 doesn't work in HW - Black screen

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#6253]
### Describe the Bug

As soon as the opening plays, everything becomes black. Pressing start goes to the menu but it's still black. Bypassing the menu while in SW works though.

### Reproduction Steps

Wait after the logo appear

### Expected Behavior

Opening should display and the menu should appear when pressing start.

### PCSX2 Revision

Latest

### Operating System

Windows 11

### CPU

Ryzen 5600x

### GPU

AMD 6800

### GS Settings

D3D12/Vulkan HW

### GS Window Screenshots

The GS screenshot was taken while in the menu (blackscreen). It's impossible to take one during the opening.

[GS.zip](https://github.com/PCSX2/pcsx2/files/8792230/GS.zip)

**Comment by Mrlinkwii** [comment]
>PCSX2 Revision
>Latest

what version
