### ISSUE TITLE
[BUG]: Qt UI icons are pixelated when using fractional scaling

### ISSUE THREAD

**Issue by LeetPanda1337** [PCSX2/pcsx2#6255]
### Describe the Bug

UI icons looks pixelated and distorted while using 125% scaling in Windows.  With any higher scaling options everything looks fine

![2022-05-29_04-09-46](https://user-images.githubusercontent.com/88889860/170847945-9905800e-7616-4872-af17-8484744141cc.png)

### Reproduction Steps

Set screen scaling to 125% in Windows display settings and open pcsx2-qtx64-avx2.exe

### PCSX2 Revision

v1.72828 (AVX2 - Qt)

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment]
Windows bug (in how calculations happen) and Qt not taking account of it:
https://bugreports.qt.io/browse/QTBUG-97731

But it can supposedly work via this:
![image](https://user-images.githubusercontent.com/24227051/170848039-6f07da09-0f7d-4f4b-9d07-5437d6badde1.png)

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/170848239-bf38cbf6-6802-4e52-8edc-812f92810617.png)
And getting rid of this memery.
