### ISSUE TITLE
[BUG]: Dualsense Sticks not Full range

### ISSUE THREAD

**Issue by RinMaru** [PCSX2/pcsx2#6259]
### Describe the Bug

PCSX2 does not always read the dualsense analogs as full range. causing direct or diagonal input to be read as half pushed

### Reproduction Steps

use dualsense via bt or usb and automap buttons

### Expected Behavior

all directions should be read at full range when pressed all the way in any direction

### PCSX2 Revision

v1.7.2828 

### Operating System

Windows 11

**Comment by stenzek** [comment]
Invalid. That's what the axis scale options are for, and there's no "one" value across all pads.
