### ISSUE TITLE
Does not quit when issuing SIGTERM

### ISSUE THREAD

**Issue by sigboe** [PCSX2/pcsx2#626]
PCSX2 does not quit when issuing SIGTERM, I need to issue SIGABRT. 

The reason this is major for me personally is because I do not have a keyboard connected to the computer I use PCSX2 on. I only use HDMI-CEC and PS3 controller and Wii mote. When I try to shut down PCSX2 using Steam Big Picture overlay nothing happens.

My workaround is that I SSH into the computer from my laptop and run Killalll -9 PCSX2

**Comment by karasuhebi** [comment]
Has anyone looked into this? This would be a pretty cool addition IMO.

**Comment by gregory38** [comment]
For me it is working. Could you retry on latest git? Was SDL2 enabled?

**Comment by gregory38** [comment]
Ping.

**Comment by gregory38** [comment]
Some signal event handling were fixed. Without any news I'm closing the bug as likely fixed.
