### ISSUE TITLE
[BUG]: Failure to compile qt build in linux

### ISSUE THREAD

**Issue by Nenderus** [PCSX2/pcsx2#6261]
### Describe the Bug

Attempting to compile PCSX2 (Qt build) fails with the following:

`In file included from /usr/src/RPM/BUILD/pcsx2-1.7.2828/pcsx2/DEV9/InternalServers/DHCP_Server.h:20,
                 from /usr/src/RPM/BUILD/pcsx2-1.7.2828/pcsx2/DEV9/net.h:37,
                 from /usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/O2BZNLJYKV/../../../../pcsx2-qt/Settings/DEV9SettingsWidget.h:24,
                 from /usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/O2BZNLJYKV/moc_DEV9SettingsWidget.cpp:10,
                 from /usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/mocs_compilation.cpp:17:
/usr/src/RPM/BUILD/pcsx2-1.7.2828/pcsx2/DEV9/SimpleQueue.h: In destructor 'SimpleQueue<T>::~SimpleQueue()':
/usr/src/RPM/BUILD/pcsx2-1.7.2828/pcsx2/DEV9/SimpleQueue.h:101:25: error: 'Console' was not declared in this scope
  101 |                         Console.Error("DEV9: Queue not empty");
      |                         ^~~~~~~
In file included from /usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/O2BZNLJYKV/moc_DEV9SettingsWidget.cpp:10,
                 from /usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/mocs_compilation.cpp:17:
/usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/O2BZNLJYKV/../../../../pcsx2-qt/Settings/DEV9SettingsWidget.h: At global scope:
/usr/src/RPM/BUILD/pcsx2-1.7.2828/x86_64-alt-linux/pcsx2-qt/pcsx2-qt_autogen/O2BZNLJYKV/../../../../pcsx2-qt/Settings/DEV9SettingsWidget.h:108:9: error: 'QSortFilterProxyModel' does not name a type
  108 |         QSortFilterProxyModel* m_ethHosts_proxy;
      |         ^~~~~~~~~~~~~~~~~~~~~
`

### Reproduction Steps

Attempt to compile PCSX2

### Expected Behavior

PCSX2 compiles

### PCSX2 Revision

v.1.7.2828

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

ALT Linux Sisyphus

**Comment by stenzek** [comment]
We don't support packages. Build from source yourself.

**Comment by Nenderus** [comment]
I'm just trying to compile pcsx2 from the source code myself

**Comment by stenzek** [comment]
The path in your output-without-newlines would suggest otherwise. And I know for a fact that it builds fine on Ubuntu, because I only did it a few days ago (unless something changed very recently).

**Comment by Nenderus** [comment]
I get source from https://github.com/PCSX2/pcsx2/archive/refs/tags/v1.7.2828.tar.gz and relevant 3rdpaty sources.

Please tell me the cmake options with which you had a successful build on Ubuntu

**Comment by stenzek** [comment]
Grabbing tarballs from github definitely isn't going to work, there's submodules which need to be cloned.

```
cmake -DCMAKE_BUILD_TYPE=Release -DQT_BUILD=ON -DQt6_DIR=/usr/local/Qt-6.3.0/lib/cmake/Qt6 -DQt6DBusTools_DIR=/usr/local/Qt-6.3.0/lib/cmake/Qt6DBusTools ..
```

worked fine for me.

**Comment by Nenderus** [comment]
Thanks. On Qt 6.3 worked.
