### ISSUE TITLE
[BUG]: Star Ocean regression, black screen on progressive

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#6272]
### Describe the Bug

Star Ocean has a black screen on progressive scan mode, v1.7.2816 is the last version i remember it working.

### Reproduction Steps

Boot game, hold x and triangle and select progressive scan (16:9)

### Expected Behavior

Not a black screen

### PCSX2 Revision

v1.7.2834

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

RTX 3060ti

### GS Settings

![Uploading image.png…]()

### Emulation Settings

![Uploading image.png…]()

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8794223/snaps.zip)

**Comment by refractionpcsx2** [comment]
Should be fixed now on Master (once 1.7.2835 is released)

**Comment by refractionpcsx2** [comment]
Confirmed fixed
