### ISSUE TITLE
[BUG - COP2]: Harry Potter the Half Blood Prince - COP2 patching required.

### ISSUE THREAD

**Issue by githubribbon45** [PCSX2/pcsx2#6273]
### Describe the Bug

In the game Harry Potter the Half Blood Prince, there are 2 COP2 code paths which can lead to serious problems.

Those are not an issue in the previous game: Harry Potter and the Order of Phoenix.

As a side note, it seems PCSX2 mis-detect some bad COP2 code, look inside the red rectangle, the same code is repeated twice, but the second iteration does not trigger a warning:

![image](https://user-images.githubusercontent.com/105116470/170890389-54a76316-effd-44c9-b824-e5238a55ea25.png)

I wrote a patch for the game, but I would like to have an explanation as to why the same bad operation does not produce the warning at all the time in this code path.

### Reproduction Steps

Play the game Harry Potter the Half Blood Prince and pay attention to the console log.

### Expected Behavior

The code should be rearranged like it would behave on a real console.

### PCSX2 Revision

v1.7.2834

### Operating System

Windows 11

### CPU

Intel I9 9900k

### GPU

Nvidia RTX 3070

### GS Window Screenshots

The 2 code paths which are problematic:

![1](https://user-images.githubusercontent.com/105116470/170890323-9302c39e-52a4-490a-9ff3-b424653edf20.png)

![2](https://user-images.githubusercontent.com/105116470/170890327-046e2bcb-65eb-4653-b27c-6025ed213d84.png)

**Comment by refractionpcsx2** [comment]
yes that should probably be patched, however the way the code detection works is to only point out one warning per block of code, which is why it prints it twice, pointing out different ones each time.

**Comment by refractionpcsx2** [comment]
Thanks for that, but you haven't told us which region this is for.
