### ISSUE TITLE
[BUG - GS Software rendering]: Harry Potter the Half Blood Prince - small line at the upper-left portion of the screen.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#6274]
### Describe the Bug

In the game Harry Potter the Half Blood Prince, there is a small issue when using the GS software rendering.

A small line at the upper left portion of the screen can be seen. Which is not the case when using the hardware rendering mode, or playing the game on real hardware.

### Reproduction Steps

Play Harry Potter the Half Blood Prince in the emulator, and use the software rendering.

### Expected Behavior

The game should not have a visible line at the upper left portion of the screen.

### PCSX2 Revision

v1.7.2834

### Operating System

Windows 11

### CPU

Intel I9 9900k

### GPU

Nvidia RTX 3070

### GS Settings

![10](https://user-images.githubusercontent.com/105116470/170890787-decd6e75-01e8-40c3-9882-206ba87bc0f7.png)

### GS Window Screenshots

Those are 2 screenshots, one with the software rendering, and the other, with the hardware one:

The software rendering:
![Capture d’écran 2022-05-29 224043](https://user-images.githubusercontent.com/105116470/170890831-c7661ccb-5282-4d44-8155-be99d5a178ce.png)

![image](https://user-images.githubusercontent.com/105116470/170890898-2bbe74b5-bcc2-46af-b069-bb5ed5284707.png)

And the hardware rendering:
![Capture d’écran 2022-05-29 224057](https://user-images.githubusercontent.com/105116470/170890849-ebc2c805-2d69-469a-a054-6ac4470abf65.png)

### Logs & Dumps

A GS-Dump to help regarding debugging:
[Harry Potter and the Half-Blood Prince - Line with the software rendering.zip](https://github.com/PCSX2/pcsx2/files/8794268/Harry.Potter.and.the.Half-Blood.Prince.-.Line.with.the.software.rendering.zip)

**Comment by refractionpcsx2** [comment]
Cannot reproduce with the provided GS dump
