### ISSUE TITLE
[BUG]: Very choppy scrolling in grid view

### ISSUE THREAD

**Issue by munt-kaicho** [PCSX2/pcsx2#6277]
### Describe the Bug

A smoother scrolling feature for grid view would be nice to have. The current way it scrolls is very choppy and doesn't seem to take into account the number of lines that the Windows mouse setting is set to. It just jumps by an entire window size on a single scroll which makes it hard to track things.

### Reproduction Steps

Set view to Grid Mode and scroll.

### PCSX2 Revision

1.7.2835

### Operating System

Windows 11

**Comment by coornio** [comment]
I literally made an issue for this already here #6237 so this may be closed as a duplicate.

**Comment by munt-kaicho** [comment]
coo
