### ISSUE TITLE
[BUG]: Ape Escape 2 broken mipmaps/pop-in issue

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#6280]
### Describe the Bug

Weird pop-in on textures and corruption happening on the game

https://user-images.githubusercontent.com/72826232/170894932-224c4def-84af-4b29-bf4e-1a5c3b775b7f.mp4

https://user-images.githubusercontent.com/72826232/170894934-99d2002a-5989-4406-9b0e-dcf665cd078d.mp4

### Reproduction Steps

Open the game, play it and you'll start seeing textures pop in and weird out

### PCSX2 Revision

v1.7.2835

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

RTX 3060ti

### GS Settings

![image](https://user-images.githubusercontent.com/72826232/170894944-9ba76c0b-150e-47bb-9378-0f416d1e61dc.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/72826232/170894912-a21cd29f-8454-4555-80e4-51f97ff3a3e6.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8794451/snaps.zip)

**Comment by ps1freak26** [comment]
This looks different from the other issues for mipmaps but setting trilinear to forced fixed the graphics issues for me.

**Comment by NineKain** [comment]
Can confirm it fixes them for me too

**Comment by marcoluc97** [comment]
https://github.com/PCSX2/pcsx2/issues/5320 and https://github.com/PCSX2/pcsx2/issues/869 are related?

**Comment by NineKain** [comment]
Yes, but maybe less severe

**Comment by asp0909** [comment]
I confirm the same problem! trying different configurations the problem persists! seems to be directly related to mipmapping

**Comment by stenzek** [comment]
Can you try https://github.com/PCSX2/pcsx2/pull/7095 with mipmapping set to full, bilinear set to PS2, and trilinear set to PS2 as well?

**Comment by stenzek** [comment]
Great, thanks for checking!
