### ISSUE TITLE
[Feature Request]: Console log window, remembering position and size? can it be done please?

### ISSUE THREAD

**Issue by MelchiorGaspar** [PCSX2/pcsx2#6281]
### Description

My feature request is to have the Console logger windows remember its position and size between reboots of PCSX2..
please.
I hope it can be implemented. other wise I tried doing the root-menu and saving the move option but didn't help.

I am currently using for a display
* 24" DELL Gaming Monitor - G2422HS - DisplayPort used
* 1920x1080p at 165Hz (16:9 Aspect Ratio)
so I have room to spare to put the main window/gamelist and the console logger window side by side..

### Reason

I am asking for this because it resets to the behind the main window every load of PCSX2.

### Examples

![image](https://user-images.githubusercontent.com/1712842/170895742-349079bd-456d-4638-beee-e9a12de80dc0.png)

**Comment by lightningterror** [comment]
Closing as trivial, otherwise someone interested in it can look in to it.

**Comment by MelchiorGaspar** [comment]
> Closing as trivial, otherwise someone interested in it can look in to it.

that is too bad...  why is my feature request so trivial? :-(
what about making it so it to docks to the right of the main window just as it does in the WxWidgets build??

**Comment by stenzek** [comment]
It's technically possible, but personally I don't really see the value, as it's not going to be cross platform, and I've been using it for months with the normal console host without issue. Just because the old UI does something doesn't mean it's a good fit in the new UI (e.g. using a docked window may be a better fit).

Of course you're welcome to implement it yourself, but we have to have a realistic scope otherwise we're never going to ship the new interface.

**Comment by MelchiorGaspar** [comment]
hi @stenzek,
aah ok.. I guess  I will have to just deal with it as is..
I know a little C from college 2001-2002 and figured out a bit of C++myself..
I only have one program I made for myself.. a simple console app temperature converter..  converts °F, °C, and K
its simple and gets the job down...
aside from C, Adv. C and data-structures(which I was not able to finish) 

I am not qualified to help you guys out sadly..  ;-) :-(

I really do like the new GUI its so much better as it has a CD/DVD image-browser..  so thx for that..
