### ISSUE TITLE
[BUG]: Multitude of issues on Vexx (hardware+software)

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6288]
### Describe the Bug

This is a comprehensive list of known issues discovered thanks to DrLegit from discord, welcome him to being a tester against his will and no I am not sorry :D

First issue, hardware mode only. When the camera is underwater, the screen renders an old, still frame instead. For example:

[camera-in-out-water.zip](https://github.com/PCSX2/pcsx2/files/8800906/camera-in-out-water.zip)

![gs_20220531014913_Vexx_SLUS-20383](https://user-images.githubusercontent.com/11655762/171065739-fb8e311b-e5b8-474e-a7f4-dafe7b32b565.png)

For the observant, the top left corner renders part of the actual frame. it's a top-left issue similar to the problem we have with Ratchet & Clank menus. Can be fixed by enabling **Texture inside RT** hack only.
The downside of this is that the hack causes the main character's shadow to flicker forever. Perhaps that of enemies as well. Appears unfixable. Example dump to test for shadow flicker here:

[shadowflicker-texinrt.zip](https://github.com/PCSX2/pcsx2/files/8800908/shadowflicker-texinrt.zip)

We tested removing the effect that caused this, with *some* success. The most "forgiving" range of skipdraw for it is 145-149. Unfortunately the effect shares the same draws as some of the HUD elements, which includes health, abilities/items, and even the letterboxing during cutscenes. The range is such specifically so that movement in water won't introduce the still frame, but it can happen anyway in cutscenes, and very rarely when standing still and for an instant when the camera leaves the water.
Any lower on the range doesn't help, and any higher directly causes HUD elements to disappear. Weirdly enough, the health bar is mostly gone in this range but moving underwater makes it appear again so long as you keep moving. We gave up trying for something better, it's a decent enough alternative to the hack. You may use the dump below to do a quick test on skipdraw if you want to experiment, but it's a short one, not very comprehensive:

[underwater-boostmove.zip](https://github.com/PCSX2/pcsx2/files/8800918/underwater-boostmove.zip)

-----

Second issue, happens in software as well, seems unfixable. When swinging your claws over a water surface, it's supposed to light up but rather than doing so smoothly, it lights it up in huge rectangles instead. 

[water-weapon-lighting.zip](https://github.com/PCSX2/pcsx2/files/8800927/water-weapon-lighting.zip)

![gs_20220531020029_(2)_Vexx_SLUS-20383](https://user-images.githubusercontent.com/11655762/171066399-74b4d7c8-3744-4ede-b1b3-bd79f5dc9c34.png)

Fairly straightforward, and quite ugly.

-----

Third issue, happens in software, also unfixable. There appears to be a permanent "curtain" inside certain water bodies that is half opaque and follows the player around, its angle changing with the camera too. We're not sure what it is, but definitely not meant to happen.

[water-curtain.zip](https://github.com/PCSX2/pcsx2/files/8800931/water-curtain.zip)

![gs_20220531020345_Vexx_SLUS-20383](https://user-images.githubusercontent.com/11655762/171066564-79013214-75f5-4b34-954e-40456f34011a.png)

Nothing we tried had an effect on it.

### PCSX2 Revision

1.7.2846

### Operating System

Windows 11

### CPU

i7-8700K

### GPU

RTX 2080

**Comment by Mrlinkwii** [comment]
whats the  status of the bugs as of latest nightly ?

**Comment by coornio** [comment]
The flickering shadow with TexInRT, and broken frames when underwater have all been taken care of.

The issues that persist still are the last two ones -- the square lighting on the water surface after claw attacks and the fog curtain underwater.

**Comment by refractionpcsx2** [comment]
If they happen in software they are likely core bugs, I would need a savestate (ideally) to mess with to see if I can find a fix

**Comment by refractionpcsx2** [comment]
Just ran the GS dumps on my PS2, which pretty much confirms this is a core problem

![Screenshot 2023-10-02 20-20-57](https://github.com/PCSX2/pcsx2/assets/6278726/4ea88e25-f8df-4974-a3fd-25f802b07593)
![Screenshot 2023-10-02 20-21-19](https://github.com/PCSX2/pcsx2/assets/6278726/bb004a9c-0288-4459-b9f0-bf1d35df1be6)

**Comment by refractionpcsx2** [comment]
I can also confirm that "Weapon lighting" happens on real hardware, so not our issue.

Can you please check the other thing on real hardware, or at least give an easy way to get there.

![Screenshot 2023-10-02 20-43-29](https://github.com/PCSX2/pcsx2/assets/6278726/2ded24b3-8076-4a53-a375-a288af47bbbc)

**Comment by refractionpcsx2** [comment]
Found it myself on a real PS2, I'm now closing this issue

![Screenshot 2023-10-02 22-02-53](https://github.com/PCSX2/pcsx2/assets/6278726/98149e65-6012-4df4-bd59-c97644a6b27f)
