### ISSUE TITLE
[Lilypad] "Local volume control" option broken and cannot be disabled

### ISSUE THREAD

**Issue by Kein** [PCSX2/pcsx2#629]
Found this one by mistake (PCSX2 kept starting with default to system sound level). Basically, the "Local volume control" option in Lilypad cannot be disabled, when you uncheck the option and save, it just sets directive **Vista Volume=1** to **Vista Volume=100**  and option is still checked. Manually setting to 0 *disables it in GUI*.

Altho, I'm not sure if it still works as intended and not redundant anymore. Setting it to 1/0 has no difference and effect.

**Comment by gregory38** [comment]
I think it was fixed

**Comment by gregory38** [comment]
Could you test a recent version and update the report

**Comment by turtleli** [comment]
Turning the option on and off is fixed.

However, the option itself is still broken - When on, you have to adjust the volume via the INI. When off, Windows remembers the volume instead, and you actually have more functionality.

**Comment by turtleli** [comment]
Well, I think I might remove the option since it's non-functional and Windows (at least since Vista) remembers app-specific volume settings anyway.

**Comment by mirh** [comment]
A proper method to handle the thing was explained [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd316791.aspx).
