### ISSUE TITLE
[BUG]: Regression - Guilty Gear XX ACPR - Freeze at the logo

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#6290]
### Describe the Bug

The game freezes at the Arc System Works logo before the opening starts.

It does that in SW/HW since [v1.7.2838](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2838)

### Reproduction Steps

Start the game

### Expected Behavior

Opening should starts

### PCSX2 Revision

v1.7.2847

### Operating System

Windows 11

### CPU

Ryzen 5600x

### GPU

AMD 6800

### GS Window Screenshots

![gs_20220531093347_Guilty Gear XX - Accent Core Plus_SLPM-66965](https://user-images.githubusercontent.com/47425204/171119777-1e441c41-303a-46e3-89b4-ee31068ea40f.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/8803106/snaps.zip)

**Comment by refractionpcsx2** [comment]
Can you create a blockdump of the game using v1.7.2837 or older to get past the hang (doesn't have to be too far past), then upload that? Then it can be looked at.

Maybe @Goatman13 might be interested in looking at it.

**Comment by Immersion95** [comment]
> Can you create a blockdump of the game using v1.7.2837 or older to get past the hang (doesn't have to be too far past), then upload that? Then it can be looked at.
> 
> Maybe @Goatman13 might be interested in looking at it.

Of course, here it is : 

[Guilty Gear XX Accent Core Plus (Japan) (2022-05-31 10-21-11).zip](https://github.com/PCSX2/pcsx2/files/8803422/Guilty.Gear.XX.Accent.Core.Plus.Japan.2022-05-31.10-21-11.zip)

**Comment by refractionpcsx2** [comment]
This should be fixed with #6313
