### ISSUE TITLE
[BUG]: Memcards menu bugged while in-game

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#6299]
### Describe the Bug

Memcard menu is bugged when in game

### Reproduction Steps

Open pcsx2, open a game, open memcard option and refresh

### Expected Behavior

Memcards recognized lol

### PCSX2 Revision

v.1.7.2855

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

RTX 3060ti

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/72826232/171223291-ceaf2bc8-4147-475c-99af-9251aaa1d4c3.png)
this is ar tonelico

**Comment by NineKain** [comment]
Update: i couldnt save because some corrupted data somehow appeared on my memcard, everything is fine now BUT the UI still shows memcards missing and unformated when hitting refresh

**Comment by NineKain** [comment]
Update 2: 
![image](https://user-images.githubusercontent.com/72826232/171228769-abbeba94-9b11-42ef-8d5a-77dfafed5aa5.png)
folder memcards dont show as missing, and unplugged memcards dont either

**Comment by stenzek** [comment]
It's a known issue, specific to windows and only happens when a game is running/the card is in use. The data is fine, it just shows missing in the UI.

**Comment by NineKain** [comment]
Yes, the data was corrupted on my end for an unknown reason, I thought it was because of this bug, leaving open the issue for visibility

**Comment by refractionpcsx2** [comment]
> Yes, the data was corrupted on my end for an unknown reason, I thought it was because of this bug, leaving open the issue for visibility

probably cos you were messing around ejecting your memory cards while it was accessing it :P

**Comment by NineKain** [comment]
> > Yes, the data was corrupted on my end for an unknown reason, I thought it was because of this bug, leaving open the issue for visibility
> 
> probably cos you were messing around ejecting your memory cards while it was accessing it :P

No, not really, i havent opened the memcard menu ever, maybe last night i closed the emu by accident or something

**Comment by NineKain** [comment]
Fixed

**Comment by NineKain** [comment]
Not fixed (yet)
