### ISSUE TITLE
Are PCSX2's interpreters platform independent?

### ISSUE THREAD

**Issue by haagens** [PCSX2/pcsx2#63]
Might want to read the following before the main body:
I would normally ask this on the forums, but I am banned from 9 different IP addresses, and I am tired of wasting time circumventing to be banned continously. So if it's okay, I'll kindly consider this a small "issue" question here and I will be fine with the closing of this issue once resolved to some acceptable degree.

Obviously PCSX2's dynamic binary translators are fixed for Intel processors, but I was wondering how platform independent the interpreters are. Say, couldn't I dissect the interpreter files and hook them to an Android GUI library and run them on an ARM processor as an Android DEX? Or would I need to rewrite some stuff for that (stuff the interpreter may depend on that's x86)? 

From my experience, all interpreters are mostly platform independent in the sense that they take no advantage of targeting CPU assembly directly. PCSX2 has an interpreter for both the Emotion Engine core and the graphics processor, correct? That means the interpreters are "easy to go" for other architectures.

I just want to know, since common sense and experience tells me that getting the interpreters to run on varying CPUs should be very, very easy compared to the dynamic binary translators.

**Comment by XiaomiRedmi9** [comment]
Any news updates about this??
