### ISSUE TITLE
[BUG]: Eyes bug in Jak games is back

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6301]
### Describe the Bug

If you enable HW hacks, all characters's eyes will be broken.

### Reproduction Steps

Start the game and enable "Manual HW hacks" in graphics settings. Bug can be caused without any changes in that menu.

### Expected Behavior

No bug with enabled HW hacks.

### PCSX2 Revision

v1.7.2851

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-05-31 22-15-10](https://user-images.githubusercontent.com/90133207/171267152-67899f68-15bc-4c1b-b76f-62ea5f854869.png)

### Emulation Settings

![Screenshot 2022-05-31 22-16-02](https://user-images.githubusercontent.com/90133207/171267276-9b66959b-5a77-4498-96e4-24d1bf295ef3.png)

### GS Window Screenshots

HW hacks enabled:
![Screenshot 2022-05-31 22-19-22](https://user-images.githubusercontent.com/90133207/171268149-634d524f-bde1-4a0f-ac18-7bcda3503a73.png)

HW hacks disabled:
![Screenshot 2022-05-31 22-21-28](https://user-images.githubusercontent.com/90133207/171268359-53d99646-004f-4654-b3cf-c26d15720f21.png)

**Comment by refractionpcsx2** [comment]
Enabling manual hacks overrides the automatic fixes, which fix the eyes.

Either disable manual fixes (since you shouldn't need them anyway) or tick "tex in rt".

**Comment by EvilPlayer1** [comment]
> Enabling manual hacks overrides the automatic fixes, which fix the eyes.
> 
> Either disable manual fixes (since you shouldn't need them anyway) or tick "tex in rt".

Did you hear about "line" on the sky?
![Screenshot 2022-05-31 22-41-54](https://user-images.githubusercontent.com/90133207/171271708-cbdc947d-00c5-4e42-adf6-e9469062314b.png)
Round sprite hack must be set to "half" to fix it.
![Screenshot 2022-05-31 22-42-06](https://user-images.githubusercontent.com/90133207/171271954-66ad9345-d26b-48d6-bd95-f99d5b9afa06.png)
Without hacks there is no fix. But thanks for workaround. "texture inside rt" fixes eyes
