### ISSUE TITLE
[BUG]:  Crash Mind Over Mutant

### ISSUE THREAD

**Issue by BenHilling** [PCSX2/pcsx2#6308]
### Describe the Bug

Hello, recently I started playing Crash Mind Over Mutant on PCSX2 and on both versions of 1.6 and 1.7 upon getting past the loading screen the audio slows down
Here is what it sounds like being slowed down https://youtu.be/Net9UOUFEJc
and this is what it should sound like https://youtube.com/clip/Ugkxc9VA0ejWj6RQR0d0Thxepzk_aYDN5SsQ I have full 50FPS too.

### Reproduction Steps

I am not sure if this is just on my system but you just load into the game and it slows down the audio.

### Expected Behavior

Supposed to sound like this https://youtube.com/clip/Ugkxc9VA0ejWj6RQR0d0Thxepzk_aYDN5SsQ

### PCSX2 Revision

v1.7.2861

### Operating System

Windows 10 (64bit)

### CPU

i5-11400f

### GPU

GTX 1660 SUPER

### Emulation Settings

![image](https://user-images.githubusercontent.com/50081336/171435518-3e1bdf40-c592-4c48-99cd-fa8e629c0e32.png)
![image](https://user-images.githubusercontent.com/50081336/171435570-94fee907-c9ff-481c-9b52-86a298a32c3f.png)
![image](https://user-images.githubusercontent.com/50081336/171435604-aa1df5a3-cd33-4305-a0f6-863b71fbada5.png)
![image](https://user-images.githubusercontent.com/50081336/171435620-64cb628f-1e0c-4165-9dca-6c466f5ea8d4.png)
![image](https://user-images.githubusercontent.com/50081336/171435631-f0bdb8d5-8f14-45c6-b906-cf71132b3e84.png)
![image](https://user-images.githubusercontent.com/50081336/171435637-36af05bd-532f-49b3-9b84-0130e8f700fc.png)
![image](https://user-images.githubusercontent.com/50081336/171435652-66ab1d1c-ab0c-4625-b482-fbde182c5c82.png)
![image](https://user-images.githubusercontent.com/50081336/171435664-65103f36-0a2a-4dd8-9741-327ecd9b43c3.png)
![image](https://user-images.githubusercontent.com/50081336/171435683-3a41f57e-2db2-4dba-8dd1-5c7138b7c560.png)
![image](https://user-images.githubusercontent.com/50081336/171435697-ab3d0e71-26dc-4775-8f1a-6b8cc07862ff.png)

**Comment by coornio** [comment]
Appears to have been caused by some cheat shenanigans.
