### ISSUE TITLE
[BUG]: Atelier Marie + Sophie - Salburg no Renkinjutsushi 1&2 - misalignment of textures in native resolution.

### ISSUE THREAD

**Issue by darkxex** [PCSX2/pcsx2#6324]
### Describe the Bug

This is a bug that has been around for as long as I can remember but it never really bothered me, but today I decided to report it, this game has misaligned textures when playing at native resolution.

There are 2 temporary fixes with which I have avoided it so far:
1. Move the Texture Offset X and Y by 3 pixels for native resolution.
2. the other option is to use is to use Upscale and use Round Sprite in Full option.

### Reproduction Steps

Run the game in Native resolution (All default in config), Without Upscale.  all textbox and other textures is misaligned.

### Expected Behavior

aligned textures in native resolution, without having to apply Texture Offset X and Y.
I really don't know if the behavior of the textures is correct, I just record the bug.

### PCSX2 Revision

v1.7.2875

### Operating System

Windows 10 (64bit)

### CPU

i7 10800h

### GPU

RTX 3060

### GS Settings

All default settings.

### Emulation Settings

all default.

### GS Window Screenshots

![native2](https://user-images.githubusercontent.com/17991404/171983851-ea94fc9a-79c5-4130-bae6-7af0f1bbee2e.png)
![native](https://user-images.githubusercontent.com/17991404/171983852-c56936e9-a2e8-4fba-b7f6-497d24a2ea05.png)

### Logs & Dumps

[gs_20220604010154_Atelier Marie _ Elie - Salburg no Renkinjutsushi 1_2_SLPM-66140.zip](https://github.com/PCSX2/pcsx2/files/8837055/gs_20220604010154_Atelier.Marie._.Elie.-.Salburg.no.Renkinjutsushi.1_2_SLPM-66140.zip)
gs dump adjunted.

**Comment by refractionpcsx2** [comment]
Duplicate #2374
