### ISSUE TITLE
[BUG]: Jak 3 eye bug after #6302

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6327]
### Describe the Bug

"Squares" in characters' eyes after #6302. Same as in #5486. Looks like auto settings don't use "texture inside rt". I tried to use HW hacks and with "texture inside rt" set on and "round sprite" set to "half" game works fine.

### Reproduction Steps

Boot the game without HW hacks.

### Expected Behavior

Rendering without bug.

### PCSX2 Revision

v1.7.2875

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-06-04 15-55-52](https://user-images.githubusercontent.com/90133207/172000011-e2c2ce81-ce63-4db1-acd3-fb95e12efa41.png)
To fix bug: 
![Screenshot 2022-06-04 15-56-45](https://user-images.githubusercontent.com/90133207/172000044-c8f38c26-cf5b-47d4-b031-1c39c442bd1a.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/90133207/172000059-d9e5d27e-8387-4c1a-ba08-57eca9184e35.png)

**Comment by refractionpcsx2** [comment]
Already known and there's a PR for the fix here #5534

**Comment by refractionpcsx2** [comment]
This won't be an issue anymore.
