### ISSUE TITLE
[BUG]: Call of Duty - Finest Hour - COP2 patching required.

### ISSUE THREAD

**Issue by githubribbon45** [PCSX2/pcsx2#6333]
### Describe the Bug

In the game Call of Duty - Finest Hour, there is 1 COP2 code path which can lead to serious problems.

I wrote a patch for it:

SLES-52783

30AE5279:
    content: |-
        comment=COP2 Patch
        // Avoids bad COP2 errors due to the instant nature of the PCSX2's COP2 handling.
        patch=1,EE,001ab900,word,48488800
        patch=1,EE,001ab904,word,4A252942

As a side note, the GameDB title has a typo mistake, the game is titled "Call of Duty - Le Jour de Gloire".

I am also sorry for the lack of response related to the previous fix, but yeah, it is working as intended for Harry Potter.

### Reproduction Steps

Play the game Call of Duty - Finest Hour and pay attention to the console log.

### Expected Behavior

The code should be rearranged like it would behave on a real console.

### PCSX2 Revision

v1.7.2878

### Operating System

Windows 11

### CPU

Intel I9 9900k

### GPU

Nvidia RTX 3070

**Comment by refractionpcsx2** [comment]
you need to move it up 1, all of those will stall for the length of time it takes for the macs to write back, so cfc2 needs to go just before the last vaddz.w, but make sure it works still (and check it if fixes anything)
