### ISSUE TITLE
[BUG]: Rumble Roses (SLPM-65885; CRC: C1C91715) - No Interlacing patch appears to be broken

### ISSUE THREAD

**Issue by SaltyBet** [PCSX2/pcsx2#6338]
### Describe the Bug

Rumble Roses SLPM-65885 No Interlacing patch appears to be broken.

Below the contents of the patch (C1C91715.pnach), as it appears inside the cheats_ni.zip file:

```
gametitle=Rumble Roses SLPM_658.85;1) Game CRC = 0xC1C91715
comment=Enhancement test

//Widescreen hack 16:9 (widescreen archive)
patch=1,EE,20104084,extended,3C013F40
patch=1,EE,20104088,extended,44810000
patch=1,EE,20104090,extended,4600C602

//Framebuffer Display and no interleacing
patch=1,EE,E0041100,extended,01D4ADA0
patch=1,EE,21D4AD98,extended,00000002
patch=1,EE,21D4ADC0,extended,00000002
patch=1,EE,21D4ADA0,extended,00001000
patch=1,EE,21D4ADC8,extended,00001000

patch=1,EE,E0041400,extended,01D4ADA0
patch=1,EE,21D4ADA0,extended,00001400
patch=1,EE,21D4ADC8,extended,00001446
patch=1,EE,21D4AD98,extended,00000003
patch=1,EE,21D4ADC0,extended,00000003

patch=1,EE,201029FC,extended,64420000
patch=1,EE,20102C64,extended,64420000

//Font Fix (widescreen archive)
patch=1,EE,2030F1DC,extended,3C033F53
patch=1,EE,2030F1E0,extended,34633333
```

Screenshots:

![A](https://user-images.githubusercontent.com/66281060/172027769-eb943c2b-b255-4c4a-9c25-40284af390da.jpg)

![B](https://user-images.githubusercontent.com/66281060/172027775-250834a4-2ee7-44b5-9c6f-0d0160ffcafd.jpg)

### Reproduction Steps

Settings > Emulation > Enable No-Interlacing Patches

### Expected Behavior

Image should not appear broken.

### PCSX2 Revision

v1.7.2889

### Operating System

Windows 10 (64bit)

**Comment by SaltyBet** [comment]
Tested the NI patch for Rumble Roses SLUS-20970 (CRC = B95C635E) on SLPM-65885, and it seems to work:

```
gametitle=Rumble Roses SLUS_209.70;1) Game CRC = 0xB95C635E
comment=no interlace

// no interlace
patch=1,EE,2010291C,extended,00000000
patch=1,EE,20102B84,extended,00000000
patch=1,EE,E0041100,extended,01D4ADA0
patch=1,EE,21D4AD98,extended,00000001
patch=1,EE,21D4ADA0,extended,00001000
patch=1,EE,21D4ADC0,extended,00000001
patch=1,EE,21D4ADC8,extended,00001000
```

Not sure if I should submit a PR, or if someone else might want to update the patch?

Cheers.

**Comment by refractionpcsx2** [comment]
are you sure it works? Usually you can't transfer patches between regions that simply.

**Comment by SaltyBet** [comment]
Upon closer inspection, it does not seem to work, sorry for the noise.

Not really sure what is missing in the original patch, it seems to stretch/cut the rendered frame.

**Comment by refractionpcsx2** [comment]
I've sorted this for you, the patch is not great for how PCSX2 works now, so I've made an allowance for no interlacing patches.  Advantages of being an emulator I guess....

**Comment by SaltyBet** [comment]
Tested some more by:

1. Removing all patch files except "C1C91715.pnach" with the contents of "B95C635E.pnach", and placed it in PCSX2\cheats.
2. Unchecking "Settings > Emulation > Enable No-Interlacing Patches"

What the patch seems to do is change "NTSC Interlaced (Frame)" to "NTSC Interlaced (Field)" during matches.

"NTSC Interlaced (Frame)" is a complete blur-fest.

"NTSC Interlaced (Field)" looks way better/cleaner in comparison.

Also tested "B95C635E.pnach"; it does exactly the same for that region.

Some key points:
- The updated "C1C91715.pnach" file does not provide a progressive image, but it does improve the visuals (by reducing blurring).
- The "C1C91715.pnach" file currently included in cheats_ni.zip does provide a progressive image, but it gets cut in half, making the patch effectively broken.
- If i put the "C1C91715.pnach" file PCSX2\cheats_ni or inside the zip file, the screen shakes uncontrollably and "NTSC Interlaced (Frame)" does not change to "NTSC Interlaced (Field)" during matches.

Not sure how to proceed here.

**Comment by refractionpcsx2** [comment]
You don't need to remove any patches, my PR deals with it.

**Comment by SaltyBet** [comment]
Whoops, hadn't seen your previous comment, for whatever reason.

Cheers.
