### ISSUE TITLE
[BUG]: Some widescreen patches missing

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6349]
### Describe the Bug

Widescreen patches missing for:
- WWF Smackdown Just Bring It (SLUS-20316)
- WWE SmackDown! vs. Raw (SLUS-21060)

The .PNACH files for these were shared some time ago on the PCSX2 forum so I had to search, download, and then manually add them.

### Reproduction Steps

--

### Expected Behavior

--

### PCSX2 Revision

v1.7.2893

### Operating System

Windows 10 (64bit)

**Comment by lightningterror** [comment]
Maybe they caused issues and were removed, who knows, anyway not actually an issue.

**Comment by Rex000** [comment]
> Maybe they caused issues and were removed, who knows, anyway not actually an issue.

Where do I post about this then?

I've been using them, no issues so far. Same as other WWE games patches that are included in the emulator.

**Comment by Rex000** [comment]
> Maybe they caused issues and were removed, who knows, anyway not actually an issue.

Where to post it then? Shouldn't this be kept open until someone has an explanation as to why they were removed or not added?

I've been using those downloaded ones, no issues so far. Same as other WWE games patches that are included in the emulator.

**Comment by F0bes** [comment]
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

**Comment by Rex000** [comment]
> https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

This is actually where I got them from.

**Comment by refractionpcsx2** [comment]
We get all our patches from there also, we will update them eventually.

**Comment by Rex000** [comment]
> We get all our patches from there also, we will update them eventually.

Hmm ok thanks!
