### ISSUE TITLE
[BUG]: Rendering artifacts in Jak and Daxter opening cutscene

### ISSUE THREAD

**Issue by roy-stewart** [PCSX2/pcsx2#6350]
### Describe the Bug

When watching the opening cutscene of *Jak and Daxter: The Precursor Legacy* there are redering artifacts. These artifacts appear almost like shdows that are being cast off of the characters.

https://user-images.githubusercontent.com/16023378/172066668-46eb5829-d33d-4ae1-b88e-81085513f654.mp4

### Reproduction Steps

1. Open *Jak and Daxter: The Precursor Legacy* in PCSX2
2. Start a new game
3. Watch the cutscene that plays when starting a new game

### PCSX2 Revision

1.7.2893

### Operating System

Windows 11

### CPU

i7-9700k

### GPU

RX 580

**Comment by refractionpcsx2** [comment]
This is a DX limitation, if you want to fix it please use Vulkan or OpenGL (Vulkan is probably better for you since AMD), but there's nothing we can do about it right now. Sorry.
