### ISSUE TITLE
[BUG]: "Pause On Focus Loss" not working

### ISSUE THREAD

**Issue by LOuroboros** [PCSX2/pcsx2#6353]
### Describe the Bug

I have the "Pause On Focus Loss" option checked in the emulator's Interface settings *(it appears grey for some reason, but I have it set to 1 in `inis\PCSX2.ini` basically)*, yet, if I move to my web browser, PCSX2 and the game it's running don't get paused at all.

### Reproduction Steps

1) Go to Settings -> Interface, and enable the "Pause On Focus Loss" checkbox in the Behaviour section. If it appears on grey, open `inis\PCSX2.ini` and set `PauseOnFocusLoss = true` under the `[UI]` section of the file.
2) Click somewhere outside of PCSX2's own window(s).

### Expected Behavior

I expected PCSX2 to pause the game completely until I clicked back into its window(s).

### PCSX2 Revision

v1.7.2895

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
It's grey because it isn't wired up.

**Comment by LOuroboros** [comment]
I thought it was a good idea to have an Issue ticket to keep that tracked, but well, at least it won't just get abandoned or dropped off the settings, yeah? It's just a matter of time until it comes back?

**Comment by stenzek** [comment]
It's already being tracked here https://github.com/PCSX2/pcsx2/discussions/5947
