### ISSUE TITLE
[BUG]: Unable to load and save controller binding profiles

### ISSUE THREAD

**Issue by KVBAMusic** [PCSX2/pcsx2#6355]
### Describe the Bug

I am unable to load and save controller binding profiles from the settings
I am using the newest Nightly build (1.7.2900), the bug was also present in earlier version (1.7.2889)

Folder "inputprofiles", where I assume normally the profiles would have been saved, is empty, even after multiple attempts of saving.

### Reproduction Steps

- open controller settings
- select one of the controllers
- click the "Save profile" and "Load profile" buttons
- check the "inputprofiles" folder

### PCSX2 Revision

v1.7.2900

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
It has not been implemented yet, we do know about it.
