### ISSUE TITLE
[BUG]: No Memory Card Found

### ISSUE THREAD

**Issue by inc0der** [PCSX2/pcsx2#6376]
### Describe the Bug

Memory cards are not being detected in the latest development version today (2022/06/07). Works fine in the latest version from yesterday ([v1.7.2906](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2906)).

### Reproduction Steps

Update to latest version and try loading a game that has saves on your memory card from any version prior to the June 7th version.

### Expected Behavior

For games to read and load data from the memory card(s).

### PCSX2 Revision

v1.7.2913

### Operating System

Windows 10 (64bit)

**Comment by inc0der** [comment]
Sorry if I'm a bit slow and not the most detailed, I'm reporting this bug for my brother who recently had this issue and is kind of PC illiterate.

Ok so both memcards are in the list but you were correct that they are not setup properly, since the memcards themselves are not inside the ports. Upon further testing (loading them into ports) it would also appear the memcard files do not have the correct saves (very outdated or not existing at all).
![image](https://user-images.githubusercontent.com/14813394/172488850-463bedba-c5dd-432a-945a-a6775d11548a.png)

What would the previous version be doing if no memcards were in the ports? Because the games were saving and loading when using v1.7.2906. 

The memcard directory looks like this. 
![image](https://user-images.githubusercontent.com/14813394/172490164-575ed532-f8af-410b-b350-18eacc700581.png)

I'm going to assume that prior to the latest version things were being saved to those directories, which leads me to my last question, how would I go about using those saves?

This is what it looks like inside one of those directories.
![image](https://user-images.githubusercontent.com/14813394/172490603-a214d556-b679-489d-abfb-b80a86e1261b.png)

**Comment by refractionpcsx2** [comment]
Okay, it looks like he's messed up somehow and installed memcards inside a folder memcard, instead of being able to select the folder memcard itself (the superblock and the BASLUS type stuff should all be in a folder called like folder.ps2, or something)

**Comment by refractionpcsx2** [comment]
Anyway, this looks like user error, if you need further help please use our forum or discord, the github is meant for actual bug tracking, rather than providing support.

Thanks
