### ISSUE TITLE
[BUG]: Missing lighting in Jak X

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6383]
### Describe the Bug

I noticed that some lighting doesn't render with auto settings. HW hacks will fix it.

### Reproduction Steps

Boot the game without HW hacks.

### Expected Behavior

All lighting renders without problems.

### PCSX2 Revision

v1.7.2916

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-06-09 21-44-49](https://user-images.githubusercontent.com/90133207/172922422-b7fce48c-c7b0-44ec-a9c9-b07f70226a7c.png)
![Screenshot 2022-06-09 21-45-04](https://user-images.githubusercontent.com/90133207/172922432-8f28a8c4-1176-4908-ad10-938907899f9f.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/90133207/172922515-205e2e5d-819a-49f4-81fe-d7c4604fdff5.png)

### GS Window Screenshots

HW mode without HW hacks:
![Screenshot 2022-06-09 21-43-46](https://user-images.githubusercontent.com/90133207/172922768-4c07aff4-49f5-44ac-8fe7-7816ecd01ec8.png)
HW hacks enabled:
![Screenshot 2022-06-09 21-43-32](https://user-images.githubusercontent.com/90133207/172922886-55819458-e905-4b0f-9fd3-dd407b797264.png)
Software:
![Screenshot 2022-06-09 21-44-02](https://user-images.githubusercontent.com/90133207/172922995-05a3249e-1e23-4ef5-9cd3-2eb9220f25d1.png)

**Comment by lightningterror** [comment]
Jak games need auto flush, might be worth adding them to gamedb if the penalty is small now.

**Comment by lightningterror** [comment]
Fixed in https://github.com/PCSX2/pcsx2/commit/c975a78ed7bd53172b14b508924591284c04962e
