### ISSUE TITLE
[BUG]: Ratchet & Clank boots, but locks up PCSX2 at the copyright notice

### ISSUE THREAD

**Issue by RenegadeScooter** [PCSX2/pcsx2#6388]
### Describe the Bug

When booting Ratchet & Clank with the latest nightly at the time of this issue, the Insomniac logo FMV plays as usual, but at the copyright notice before the title screen the emulator locks up. At that point, PCSX2 cannot continue to the title screen or reset or shutdown the virtual machine, which means I have to kill the process with Task Manager. This issue is preventing me from playing Ratchet & Clank on the latest nightly.

### Reproduction Steps

1. Open PCSX2 Nightly v1.7.2917
2. Boot a copy of Ratchet & Clank

### PCSX2 Revision

v1.7.2917

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Emulation Settings

![emusettings](https://user-images.githubusercontent.com/69838290/173005256-bb91a878-018c-49e7-b102-e2dac1f4919c.png)
![syssettings](https://user-images.githubusercontent.com/69838290/173005280-8f4acb1c-d738-41ac-9575-4abad1faa450.png)
![advsyssettings](https://user-images.githubusercontent.com/69838290/173005296-400ac3a4-d1cc-45ee-a0db-140335b37aa2.png)
![dispsettings](https://user-images.githubusercontent.com/69838290/173005319-c4f10e7e-288e-4541-830a-9a24fbebe3f1.png)
![rendsettings](https://user-images.githubusercontent.com/69838290/173005339-324948dd-9bdb-4bd1-aae0-8dfc37b50949.png)
![osdsettings](https://user-images.githubusercontent.com/69838290/173005365-f22345ee-0c82-438b-9497-ff087d9ac769.png)
![advgraphsettings](https://user-images.githubusercontent.com/69838290/173005377-40ccec55-ebf9-4f49-91bb-90bee09cf22d.png)
![audiosettings](https://user-images.githubusercontent.com/69838290/173005387-191570e6-6c6d-4360-9294-3aa8516535c3.png)

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/8876052/emulog.txt)

**Comment by refractionpcsx2** [comment]
Don't be so violent with cycle rate and you won't have a problem. In future please use our discord or forum for support. Thanks.
