### ISSUE TITLE
DEV9ghzdrk plugin crash

### ISSUE THREAD

**Issue by Volkanite** [PCSX2/pcsx2#639]
-PCSX2 version: [3debd3ae12](https://github.com/PCSX2/pcsx2/tree/3debd3ae12c94b89741a3d19c87c1e8b3d1379de)

-How to replicate: Open the plugin configuration then press "OK" without selecting any Ethernet device

-Other comments: Crash happens at dev9ghzdrk/Win32/Win32.cpp, line 81. Caused by ComboBox_GetItemData (line 80) failing because no option was selected which passes a bad pointer to a strcpy

**Comment by bositman** [comment]
@TheLastRar to the rescue! :P

**Comment by TheLastRar** [comment]
Rescue has arrived! https://github.com/PCSX2/pcsx2/pull/654

**Comment by bositman** [comment]
That was fast, thanks :)
