### ISSUE TITLE
[BUG]: PlayStation 2 logo small bug

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#6393]
### Describe the Bug

The logo of PlayStation 2 is not on the center of the screen but a bit lower, when starting a game. Works the same with hardware and software renderer.

### Reproduction Steps

Load an iso-file and wait for PlayStation logo to appear.

### Expected Behavior

The logo must be in the center of the screen.

### PCSX2 Revision

v1.7.2889

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

LMDE 5

### CPU

Intel Core i5-4430 3GHz (4 cores)

### GPU

GTX 760

### GS Settings

Adapter = NVIDIA GeForce GTX 760
CaptureHeight = 480
CaptureWidth = 640
DisableDualSourceBlend = 0
DisableFramebufferFetch = 0
DumpDirectTextures = 1
DumpPaletteTextures = 1
DumpReplaceableMipmaps = 0
DumpReplaceableTextures = 0
DumpTexturesWithFMVActive = 0
GSDumpCompression = 0
HWDisableReadbacks = 0
IntegerScaling = 0
LoadTextureReplacements = 0
LoadTextureReplacementsAsync = 0
MaxAnisotropy = 0
OsdScale = 100
OsdShowCPU = 0
OsdShowFPS = 0
OsdShowGPU = 0
OsdShowGSStats = 0
OsdShowIndicators = 0
OsdShowMessages = 0
OsdShowResolution = 0
OsdShowSpeed = 0
OverrideGeometryShaders = -1
OverrideTextureBarriers = -1
PrecacheTextureReplacements = 0
Renderer = 14
ShadeBoost = 0
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
SkipDuplicateFrames = 0
TVShader = 1
ThreadedPresentation = 0
UseBlitSwapChain = 0
UseDebugDevice = 0
UserHacks = 0
UserHacks_AutoFlush = 0
UserHacks_CPU_FB_Conversion = 0
UserHacks_DisableDepthSupport = 0
UserHacks_DisablePartialInvalidation = 0
UserHacks_Disable_Safe_Features = 0
UserHacks_HalfPixelOffset = 0
UserHacks_Half_Bottom_Override = -1
UserHacks_SkipDraw_End = 0
UserHacks_SkipDraw_Start = 0
UserHacks_TCOffsetX = 0
UserHacks_TCOffsetY = 0
UserHacks_TextureInsideRt = 0
UserHacks_TriFilter = -1
UserHacks_WildHack = 0
UserHacks_align_sprite_X = 0
UserHacks_merge_pp_sprite = 0
UserHacks_round_sprite_offset = 0
aa1 = 1
accurate_blending_unit = 1
accurate_date = 1
autoflush_sw = 1
capture_enabled = 0
capture_out_dir = /tmp/GS_Capture
capture_threads = 4
conservative_framebuffer = 1
crc_hack_level = -1
deinterlace = 7
disable_interlace_offset = 0
disable_shader_cache = 0
dithering_ps2 = 2
dump = 0
extrathreads = 3
extrathreads_height = 4
filter = 2
fxaa = 0
linear_present = 1
mipmap = 1
mipmap_hw = -1
override_GL_ARB_shader_image_load_store = -1
override_GL_ARB_sparse_texture = -1
paltex = 0
pcrtc_offsets = 0
png_compression_level = 1
preload_frame_with_gs_data = 0
save = 0
savef = 0
savel = 5000
saven = 0
savet = 0
savez = 0
shaderfx = 0
shaderfx_conf = shaders/GS_FX_Settings.ini
shaderfx_glsl = shaders/GS.fx
texture_preloading = 0
upscale_multiplier = 1
wrap_gs_mem = 0

### Emulation Settings

[EmuCore]
CdvdVerboseReads=disabled
CdvdDumpBlocks=disabled
CdvdShareWrite=disabled
EnablePatches=enabled
EnableCheats=disabled
EnablePINE=disabled
EnableWideScreenPatches=disabled
EnableNoInterlacingPatches=disabled
EnableRecordingTools=enabled
ConsoleToStdio=disabled
HostFs=disabled
PatchBios=disabled
PatchRegion=
BackupSavestate=enabled
SavestateZstdCompression=enabled
McdEnableEjection=enabled
McdFolderAutoManage=enabled
MultitapPort0_Enabled=disabled
MultitapPort1_Enabled=disabled
GzipIsoIndexTemplate=$(f).pindex.tmp
[EmuCore/Speedhacks]
EECycleRate=0
EECycleSkip=0
fastCDVD=disabled
IntcStat=enabled
WaitLoop=enabled
vuFlagHack=enabled
vuThread=disabled
vu1Instant=enabled
[EmuCore/CPU]
FPU.DenormalsAreZero=enabled
FPU.FlushToZero=enabled
FPU.Roundmode=3
VU.DenormalsAreZero=enabled
VU.FlushToZero=enabled
VU.Roundmode=3
[EmuCore/CPU/Recompiler]
EnableEE=enabled
EnableIOP=enabled
EnableEECache=disabled
EnableVU0=enabled
EnableVU1=enabled
vuOverflow=enabled
vuExtraOverflow=disabled
vuSignOverflow=disabled
vuUnderflow=disabled
fpuOverflow=enabled
fpuExtraOverflow=disabled
fpuFullMode=disabled
StackFrameChecks=disabled
PreBlockCheckEE=disabled
PreBlockCheckIOP=disabled
[EmuCore/GS]
VsyncQueueSize=2
FrameLimitEnable=enabled
FrameSkipEnable=disabled
VsyncEnable=0
FramerateNTSC=59.94
FrameratePAL=50
FramesToDraw=2
FramesToSkip=2
[EmuCore/Gamefixes]
VuAddSubHack=disabled
FpuMulHack=disabled
FpuNegDivHack=disabled
XgKickHack=disabled
EETimingHack=disabled
SoftwareRendererFMVHack=disabled
SkipMPEGHack=disabled
OPHFlagHack=disabled
DMABusyHack=disabled
VIFFIFOHack=disabled
VIF1StallHack=disabled
GIFFIFOHack=disabled
GoemonTlbHack=disabled
IbitHack=disabled
VUSyncHack=disabled
VUOverflowHack=disabled
[EmuCore/Profiler]
Enabled=disabled
RecBlocks_EE=enabled
RecBlocks_IOP=enabled
RecBlocks_VU0=enabled
RecBlocks_VU1=enabled
[EmuCore/Debugger]
ShowDebuggerOnStart=disabled
AlignMemoryWindowStart=enabled
FontWidth=8
FontHeight=12
WindowWidth=1000
WindowHeight=728
MemoryViewBytesPerRow=16
[EmuCore/TraceLog]
Enabled=disabled
EE.bitset=0
IOP.bitset=0
[DEV9]
[DEV9/Eth]
EthEnable=disabled
EthApi=Unset
EthDevice=
EthLogDNS=disabled
InterceptDHCP=disabled
PS2IP=0.0.0.0
Mask=0.0.0.0
Gateway=0.0.0.0
DNS1=0.0.0.0
DNS2=0.0.0.0
AutoMask=enabled
AutoGateway=enabled
ModeDNS1=Auto
ModeDNS2=Auto
[DEV9/Hdd]
HddEnable=disabled
HddFile=DEV9hdd.raw
HddSizeSectors=83886080

### GS Window Screenshots

![gs_20220610195647_Booting PS2 BIOS  ](https://user-images.githubusercontent.com/96921167/173116343-1358443c-a78a-48b6-96a7-a742a4e744ab.png)

**Comment by refractionpcsx2** [comment]
*sigh* this keeps coming up...

If you want it in the centre enable the "screen offsets" option, otherwise live with it. The logo gets offset by the BIOS on the screen and by default we ignore this, screen offsets doesn't.

![image](https://user-images.githubusercontent.com/6278726/173118624-daa3ff6e-e136-46a1-8afa-1ad4f02de344.png)
