### ISSUE TITLE
[Feature Request]: Add “Folder” and “Floppy Disk” icons to each Save Slot

### ISSUE THREAD

**Issue by ivadham** [PCSX2/pcsx2#6395]
### Description

Add “Folder” and “Floppy Disk” icons to each Save Slot in order to give the user another chance and lessen the odds of choosing the wrong button.

### Reason

Load State and Save State buttons are just next to each other which means you might choose the wrong one if you're not careful enough.

### Examples

![PCSX2LoadState](https://user-images.githubusercontent.com/11696957/173204126-a1b18886-776d-4938-ae65-a6e975f84e0e.png)
![PCSX2SaveState](https://user-images.githubusercontent.com/11696957/173204131-3a69d596-cb2f-45cb-8038-21eec6f4942f.png)

**Comment by refractionpcsx2** [comment]
tbh I'd rather change the wording so the load state list said "Load Slot 1", "Load Slot 2" etc, that would make more sense.

**Comment by ivadham** [comment]
Exactly! To be honest, I had done that too, but I changed my mind and reversed it as “Save Slot” is more of a technical term rather than just **Save [verb] Slot [object]**.

Overall, your point is valid and “Load Slot” makes more sense.

**Comment by refractionpcsx2** [comment]
Well technically the term for them is "savestate" so it would be Save Savestate Slot 1 and Load Savestate Slot 1, but that's wordy, so the only real important part here is the Slot, so I don't see any issue in saying Load Slot 1 and Save Slot .
