### ISSUE TITLE
[BUG]: Weird lines in Onimusha 3 and Onimusha Dawn of Dreams

### ISSUE THREAD

**Issue by abogard** [PCSX2/pcsx2#6396]
### Describe the Bug

Ever since the fix for Onimusha Dawn of Dreams was incorporated in Master I get some strange colored lines on the right hand of the screen making the experience of playing a lot less pleasant. This also happens in Onimusha 3. I really don't know if it's only me because I would think somebody would have already reported this but I couldn't find any such report.

### Reproduction Steps

Just play the game. One thing to notice is that this only happens in-game. It doesn't happen in movies, intros or menus

### Expected Behavior

Correct graphical emulation

### PCSX2 Revision

1.7.2924

### Operating System

Windows 10 (64bit)

### CPU

i5-4690

### GPU

GTX 1070

### GS Settings

![Captura de pantalla 2022-06-11 144814](https://user-images.githubusercontent.com/59800992/173204409-2c8de044-053a-4fff-9ad0-36da4520c069.png)
![Captura de pantalla 2022-06-11 144842](https://user-images.githubusercontent.com/59800992/173204410-71290a57-01c2-4240-9d1a-5a55897e7e2c.png)

### Emulation Settings

![Captura de pantalla 2022-06-11 144857](https://user-images.githubusercontent.com/59800992/173204419-4067a4ed-8204-48a3-9e19-208d42bb15e2.png)

### GS Window Screenshots

![gs_20220611142957_Onimusha 3 - Demon Siege_SLUS-20694](https://user-images.githubusercontent.com/59800992/173204325-260c8f88-2d99-45d1-a478-0c7827329a8c.png)
![gs_20220611143228_Onimusha - Dawn of Dreams _Disc1of2__SLUS-21180](https://user-images.githubusercontent.com/59800992/173204328-3c014117-0841-40aa-bb3a-acee0eaca48f.png)

**Comment by refractionpcsx2** [comment]
They aren't new to the onimusha patch, it's been doing that for months. The only fix currently is to not upscale or use software mode.

**Comment by refractionpcsx2** [comment]
Anyway, already being tracked here: https://github.com/PCSX2/pcsx2/issues/5851
