### ISSUE TITLE
[BUG]: Revenge of the Sith cutscenes

### ISSUE THREAD

**Issue by yuval4436** [PCSX2/pcsx2#6402]
### Describe the Bug

When I play Star Wars Revenge of the Sith, when the Cinematics are playing, the screen is black until someone talks

### Reproduction Steps

Playing the game and when a cutscene plays the screen is black until someone is talking

### PCSX2 Revision

1.7.2900

### Operating System

Windows 10 (64bit)

### CPU

i5-7600

### GPU

gtx1070

**Comment by James-Devil** [comment]
Yeah I just Checked and I have this too on Sten's Pre-PR HW-SW Build...

**Comment by James-Devil** [comment]
Also Checked on Latest Nightly (1.7.2933) and it's there too.
