### ISSUE TITLE
[BUG]: Double input on menu screens for DOA2H (USA & JPN)

### ISSUE THREAD

**Issue by OppaiLuver** [PCSX2/pcsx2#6403]
### Describe the Bug

Every time I start up the game and get to the main menu and hit right on the d-pad, the game skips an input. I end up on the option after the last one and it keeps doing this for no reason at all. 

### Reproduction Steps

Just boot the game and try to move around on the main menu

### Expected Behavior

The game skipping over options that you were trying to select.

### PCSX2 Revision

v1.7.2932

### Operating System

Windows 10 (64bit)

### CPU

i7-9700K

### GPU

RTX 2070 Super

### GS Settings

![Screenshot (136)](https://user-images.githubusercontent.com/107367887/173250168-14377a46-1f26-4c99-bce0-b2c9ea2f738b.png)
![Screenshot (137)](https://user-images.githubusercontent.com/107367887/173250176-507179d3-95d2-4c88-98a4-6663ddb64193.png)
![Screenshot (138)](https://user-images.githubusercontent.com/107367887/173250181-3c57b9a2-ad47-4ddb-94ba-bc7fce3c86e1.png)
![Screenshot (140)](https://user-ima
![Screenshot (141)](https://user-images.githubusercontent.com/107367887/173250210-2d4400a8-6291-4dee-a321-ecb7abc04c9f.png)
ges.githubusercontent.com/107367887/173250209-9122ca2c-50e6-42fb-a8d0-75eef4e29f09.png)

![Screenshot (139)](https://user-images.githubusercontent.com/107367887/173250185-541507a7-0ddf-47c9-81c5-8d78bfd6da88.png)

### Emulation Settings

![Screenshot (142)](https://user-images.githubusercontent.com/107367887/173250219-b1ddc7ff-bfde-4024-811c-a039c547df58.png)
![Screenshot (143)](https://user-images.githubusercontent.com/107367887/173250223-ab2ce805-33fa-406e-bd4f-a92fe0a173a3.png)
![Screenshot (144)](https://user-images.githubusercontent.com/107367887/173250225-8bc577ef-0e41-4004-bceb-f9fbb816e75f.png)

**Comment by coornio** [comment]
Due to an experience a day or two ago, please try to disable SDL in the controller settings and enable xinput instead, then attempt to bind your controller manually (supposing it isn't a dualshock, in which case it might require the old methods of steam and whatnot to test this). Please let me know if that's made any difference.

**Comment by refractionpcsx2** [comment]
Can't reproduce this, sounds like a user/controller error.  Seems to work fine on this end.

Can you check if this is still a problem? maybe configure your keyboard to see if it still happens?

**Comment by refractionpcsx2** [comment]
No response for 2 months and nobody else has reproduced it, assuming it's fine.
