### ISSUE TITLE
[BUG]: Metal Gear Solid 2 possible regression; Interlaced blur after throwing punch/starting a Codec call

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6411]
### Describe the Bug

Possible regression from this:  https://github.com/PCSX2/pcsx2/pull/4385 .

Blur, looks like an interlaced frame, Happens in Metal Gear Solid 2 (PAL and NTSC) after throwing a punch or making a Codec call (it will appear when the faces show up, after the ringing noise). This blur remains until you load a quick save or restart the game.

I found the two builds where the difference started (using https://buildbot.orphis.net/pcsx2/index.php?m=fulllist ) :

Working:
BEFORE (and incl.) v1.7.2159    refractionpcsx2    2021-12-26 11:37:43    Download    VS: Fix filters

Broken:
AFTER (And incl.) v1.7.2160    Sergeanur    2021-12-22 11:56:38    Download    GS: Simulate scan mask

I tested quite a few builds before and after these, showing the same difference (meaning it probably started here). To test I used the normal pcsx2.exe, changed from opengl to software and turned off Texture Filtering of Display. It also happens in HW mode. No deinterlacing modes change anything.

### Reproduction Steps

Anywhere in the game, create a quick save, then load it. This will reset the image to "sharp". Throw a punch or start a Codec call (when the faces appear), and the blur will appear, remaining until you quick load again. No Texture Filtering of Display will help to see it more clearly.

### Expected Behavior

The punch should not introduce any blur of either 2D or 3D/fullscreen elements. The older builds don't have this issue.

### PCSX2 Revision

v1.7.2908

### Operating System

Windows 10 (64bit)

### CPU

i7-9700

### GPU

RTX 2080

### GS Settings

Default, but disable Texture Filtering of Display to more clearly see the issue.

### GS Window Screenshots

![BEFORE](https://user-images.githubusercontent.com/88314420/173575542-9babfc9f-74bb-4398-988e-89ca622cfda8.png)
![AFTER](https://user-images.githubusercontent.com/88314420/173575560-ca6a6548-1812-415d-bfd3-b210a7727f5b.png)

### Logs & Dumps

The snaps/dumps are too big to upload, hopefully I am allowed to link it here: https://drive.google.com/file/d/1KEBpaVVNt62UmhDr-bVn1x73Rph7SGRe/view?usp=sharing 

They show before and after the punch, and also a multi where the punch button is pressed.

**Comment by refractionpcsx2** [comment]
Can you make a GS Dump at the exact moment it changes? because the GS Dumps you did give, I can't reproduce it at all.

**Comment by refractionpcsx2** [comment]
I have made some changes so it won't stay blurry until you reset, but it will remain blurry on sections with Octagon or the Communicator calls, or anywhere with water. But everywhere else shouldn't be blurry.

I've explained why this is the case on the linked above PR.

**Comment by jonasos3** [comment]
Great, thanks a lot for your work and time!

Just to be extra annoying if you have the time to respond, if someone is mainly focused on accuracy; is there a way to make the blur effect be permanent, meaning it won't go away when using a quick load? I was unaware that this was actually the intended way for the game to be displayed.

**Comment by refractionpcsx2** [comment]
Not at the moment there isn't, no.  It is an idea we've toyed with adding an option for, but it certainly wouldn't be permanent because most people would complain.

But maybe I could add a "Disable Anti-Blur" option.

**Comment by jonasos3** [comment]
Such an option would be very appreciated! But, thanks a lot again for resolving the original issue in a smart way

**Comment by refractionpcsx2** [comment]
You can try #6417 if you like

**Comment by jonasos3** [comment]
> i

I would love to, but I can't figure out how to download/build from anything other than the official nightly releases... I'm sorry, I'm new to GitHub etc. I don't expect you to help me with this, but I am thankful for you including this and look forward to using it!

**Comment by refractionpcsx2** [comment]
go to the "checks" box at the bottom, click the "Show all checks" on the right of that box, then click the "Details" button on the top "Windows" line, that'll take you to another page, click summary on the left, then the builds will be down the middle :)
