### ISSUE TITLE
pcsx2 eats all vram

### ISSUE THREAD

**Issue by lordmedo** [PCSX2/pcsx2#642]
v1.3.1-667-g3debd3a revision eats all of my vram in Onimusha - Warlords [NTSC] [SLUS-20018] by only watching the intro cinematics. This leads to crash on my desktop (512MB vram) and on my laptop (1024MB vram) its still playable but I haven't tested it for long. Both of them have 4gb of ram.

**Comment by gregory38** [comment]
What config? Dx? Msaa?

**Comment by ssakash** [comment]
providing the GSdx,ini file would make the work easier. ;)

**Comment by lordmedo** [comment]
Out of memory while allocating 'StateCopy_SinglePlugin':
Called from 'SafeArray::ExactAlloc' [oldsize=4] [newsize=4194780](SaveSinglePlugin) is shown 
when I try to change settings while the game is running

GSdx.ini
[Settings]
Adapter=1002:9501:395218BC:00
Renderer=3
Interlace=1
AspectRatio=0
upscale_multiplier=2
filter=1
paltex=0
logz=1
fba=1
aa1=0
nativeres=0
resx=1024
resy=1024
extrathreads=0
AnisotropicFiltering=0
accurate_blend=0
accurate_date=0
accurate_colclip=0
texture_cache_depth=0
ShadeBoost=0
Fxaa=0
shaderfx=0
shaderfx_conf=shaders/GSdx_FX_Settings.ini
shaderfx_glsl=shaders/GSdx.fx
UserHacks=0
UserHacks_MSAA=0
crc_hack_level=3
UserHacks_AlphaHack=0
UserHacks_HalfPixelOffset=1
UserHacks_SpriteHack=0
UserHacks_SkipDraw=0
UserHacks_WildHack=0
UserHacks_AlphaStencil=0
UserHacks_round_sprite_offset=2
Userhacks_align_sprite_X=0
UserHacks_TCOffset=0
accurate_fbmask=0
MaxAnisotropy=8
windows 7 x64, ati radeon 3800 series (dx9& dx10) 
I've tried the old GSdx32-SSE4 from r5240 and it is working fine, maxing out at 190 vram. 
Same thing is happening with onimusha 2.

**Comment by gregory38** [comment]
Hum it is not clear for me. Does the issue appear recently? Did you try older (1/2/3 months) git build?

**Comment by lordmedo** [comment]
EmuCR-Pcsx2-Git-20150624
pcsx2-v1.3.1-556-g819133e-windows-x86
don't have this issue

**Comment by mirhl** [comment]
Use official builds, or somebody'll kill you.

**Comment by gregory38** [comment]
Here the GSdx texture memory consumption in the intro of Onimusha - Warlords (4x upscaling)
```
Type:Perf	ID:39738	Severity:Info	Message:MEM: RO Tex 6MB. RW Tex 20MB. Target 40MB. Depth 40MB
```
Dx code was barely updated. Could you find the revision that introduce the issue (the latest that was fine).

**Comment by lordmedo** [comment]
pcsx2-v1.3.1-641-gde644c5-windows-x86 has the issue  - game eats vram continuously as soon as it starts...
pcsx2-v1.3.1-590-gcd8e31d-windows-x86 has normal vram usage

**Comment by refractionpcsx2** [comment]
You're gonna have to narrow it down more than that. there are plenty of builds available here: http://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by gregory38** [comment]
it comes from my 1.0 branch. Branch doesn't have any build unfortunately.

**Comment by turtleli** [comment]
Over the internet bisect fun? I've compiled GSdx from the 1.0 branch.
Can you try http://turtleli.unospace.net/GSdx32-SSE4-77e718c.7z

Does it crash?
 * Yes - Try http://turtleli.unospace.net/GSdx32-SSE4-7ee3dbd.7z and report whether it crashes or not.
 * No - Try http://turtleli.unospace.net/GSdx32-SSE4-d29e375.7z and report whether it crashes or not.

**Comment by lordmedo** [comment]
All of the 3 ultimately lead to a crash, as they all eat the whole vram, and then the OS compensates with system ram

**Comment by gregory38** [comment]
Do you have the issue in openGL? Do you mean this intro movie http://imgur.com/UsGJ3ON ?

**Comment by lordmedo** [comment]
the issue is not present in the software modes(opengl &dx) while every hardware mode is affected. the movie itself is not responsible as the vram gets eaten as soon the game is started, it just happens to crash around that movie, because the resources are gone by that time

**Comment by turtleli** [comment]
More builds to try.

First try http://turtleli.unospace.net/GSdx32-SSE4-2d812de.7z

If it crashes, try http://turtleli.unospace.net/GSdx32-SSE4-b59a347.7z
If it doesn't crash, try http://turtleli.unospace.net/GSdx32-SSE4-c925b1d.7z

**Comment by lordmedo** [comment]
2d812de & b59a347 are fine, c925b1d is a glutton

**Comment by turtleli** [comment]
Ok. Final 2 builds to test.

http://turtleli.unospace.net/GSdx32-SSE4-4bc8bfc.7z
http://turtleli.unospace.net/GSdx32-SSE4-58ce7d4.7z

Thanks for testing.

**Comment by lordmedo** [comment]
both are fine

**Comment by turtleli** [comment]
Ok, so it's probably c925b1d

@gregory38 - perhaps missing m_renderer->m_dev->Recycle(t); at early return path?
```
	// No handling please
	if ((m_type == DepthStencil) && !m_depth_supported) {
		// do the most likely thing a direct write would do, clear it
		GL_INS("ERROR: Update DepthStencil dummy");

		if((m_renderer->m_game.flags & CRC::ZWriteMustNotClear) == 0)
			m_renderer->m_dev->ClearDepth(m_texture, 0);

		return;
	}
```

**Comment by gregory38** [comment]
Thanks very much for the test :+1: 

It must be fixed now.

**Comment by tsunami2311** [comment]
I was right there was memory leak, Cause i had this exact issue when watching cut scene videos, watch my commit from 1gb to 7gb over coarse of 2 min video, then reset,  if this fix even better, cause i pretty sure at one point this hardlock the pc, with opengl ran out of memory event, which crash DWM.exe and locked the system.

**Comment by gregory38** [comment]
Yes but does it work now?

**Comment by tsunami2311** [comment]
short answer yes?  slightly less short, I think this memory leak was happening in random  specific situation like i original hinted at in the  http://forums.pcsx2.net/Thread-GSdx-1-0?pid=467339#pid467339.

I have not seen any huge commits though.

**Comment by gregory38** [comment]
memory leak appears when depth support was disabled and when there is a direct write in the depth buffer (so yes specific case)

**Comment by gregory38** [comment]
No new so I expect the bug can be closed.

**Comment by refractionpcsx2** [comment]
Is this not related? http://forums.pcsx2.net/Thread-Tekken-5-with-Distorted-Garbage-Graphics-on-Latest-Build?pid=470085#pid470085
