### ISSUE TITLE
[BUG]: Error in Windows version when trying to load state saved in Linux version

### ISSUE THREAD

**Issue by kmicki** [PCSX2/pcsx2#6424]
### Describe the Bug

In Windows version of PCSX2, when trying to load save state that was saved in the Linux version (the same version number), following error occurs:

![image](https://user-images.githubusercontent.com/1463619/173942003-91b147e1-38f7-470a-b845-5bdbba5ce39d.png)

It works the other way around. Linux version does not have any problems loading state saved in Windows.

### Reproduction Steps

1. Start a game in Linux version of PCSX2.
2. Save state.
3. Copy the contents of savestate folder to Windows version of PCSX2.
4. Start a game in Windows version of PCSX2.
5. Load state saved in step 2.
6. The error occurs.

### PCSX2 Revision

v1.7.2948

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
The windows WXWidgets and Linux WXWidgets versions use different pad plugins, so they are incompatible, you might have better luck with Qt.

But Wx is going to be a "won't fix" since we're dropping it at some point soon.

**Comment by kmicki** [comment]
@refractionpcsx2 

Thank you for info. As far as I see for Linux only WxWidgets version is available, isn't it?

I found out that padding `PAD.bin` file inside a state with any data so that length is 232 (as is in Windows state file) makes it work.

So `PAD.bin` loading fails when data in the state is shorter than expected, because of the first codition in [here](https://github.com/PCSX2/pcsx2/blob/04681babf198c0757e1dd5d7960e163d2408ab97/pcsx2/SaveState.cpp#L421):

    zip_fread(zf, data.get(), fP.size) != static_cast<zip_int64_t>(fP.size)

When `fP.size` (expected size) is lower than actual file size then it works because `zip_fread` returns the size from the argument. 

Then loading is called and in Linux it will not load anything and return 0 because sizes do not match ([link](https://github.com/PCSX2/pcsx2/blob/04681babf198c0757e1dd5d7960e163d2408ab97/pcsx2/PAD/Linux/PAD.cpp#L139-L141)). Windows has a [similar check](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/PAD/Linux/PAD.cpp#L1538-L1541).

To make it work in my build I will add padding of 8 bytes to `PadFullFreezeData` in Linux version so that sizes match between Windows and Linux and states should work cross-platform.

Would that solution be acceptable for a PR?
