### ISSUE TITLE
[BUG]: Wont map mouse buttons

### ISSUE THREAD

**Issue by Daedliy** [PCSX2/pcsx2#6431]
### Describe the Bug

In older versions of PCSX2 you where able to use about any input, including the mouse keys + movement, ever since the change to QT it has been impossible to use any mouse inputs as it detects it but doesn't save them.

### Reproduction Steps

Go to PCSX2 Controller Settings > Click to bind a button and move or click the mouse

### Expected Behavior

Mouse keys and movement are detected as input 

### PCSX2 Revision

v1.7.2949

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
This has already been completed, I just haven't PR'ed it yet.
