### ISSUE TITLE
[Feature Request]: Add a "Power Off System" hotkey

### ISSUE THREAD

**Issue by aorin1** [PCSX2/pcsx2#6436]
### Description

As of now, only reset and power off virtual machine hotkeys are available, the latter brings the user back to the games list.
Adding a Power Off System hotkey to close the emulator entirely is useful for users who use frontends and other launchers.

### Reason

This is useful specially for users which launch games from a launcher/frontend, which are controlled mainly by a gamepad other than a keyboard/mouse.

### Examples

Examples of this functionality can be found in emulators such as Duckstation and Dolphin, shown in the screenshots below.

![1](https://user-images.githubusercontent.com/32167620/174222280-5a8f96fc-9426-4d7a-8d5b-fe5e0edecc06.jpg)
![2](https://user-images.githubusercontent.com/32167620/174222286-67d8318d-df7f-4c76-8618-cc6e5588a0fb.jpg)

**Comment by refractionpcsx2** [comment]
This doesn't make any sense. It would be better to improve the "no gui" option for people with launchers/frontends, which I believe is something being worked on, so when you hit "Shutdown" it exits the emulator, since there will be no GUI to go back to.

**Comment by aorin1** [comment]
Yes, after your comment I realized I can add the -nogui argument and the shut down machine hotkey worked as intended, I'm closing this request as this functionality seems to be working.
Thanks

**Comment by stenzek** [comment]
fwiw, in qt, it's `-batch`, not -`nogui`

**Comment by aorin1** [comment]
yes, I just fixed that, thanks again!
