### ISSUE TITLE
[BUG]: Weird error loading save state

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#6437]
### Describe the Bug

Hello! I got the following error while I was playing KOF Nests Hen Collection and tried to load a state:

![image](https://user-images.githubusercontent.com/27839354/174227431-194b4f98-164b-4897-ae35-1e8077b1cfbd.png)

### Reproduction Steps

Just hit F3 key to load the saved state and couldn't.

I don't know if it matters but I converted my ISOs to CHD to save space. Aren't save states supported with CHD files?

### Expected Behavior

It was supposed to load normally I guess.

Thank you for your time and work.

### PCSX2 Revision

v.1.7.2950

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Invalid, save states got bumped a few versions back. The error explains exactly what's going on.

**Comment by dezraj** [comment]
Hello! I noticed that for some reason the state wasn't even created, that's why it wasn't loading and showing this message. Maybe I didn't hit the key with enough pressure?

Anyway, I'm sorry for the misunderstanding. Next time I'll be sure to check whether a save state file was created.

Thank you for the fast reply.

**Comment by stenzek** [comment]
If there wasn't a state in that slot, we probably should display a better error message.

**Comment by dezraj** [comment]
> 

Yes, that was indeed the case. I just deleted my save state file and tried to load it to confirm that the same error message shows.

So a better error message would have probably helped me better to understand what was happening in my case (no save file found). Opening this issue wasn't so useless in the end.

Thank you again for your hard work. 🙏
