### ISSUE TITLE
[Feature Request]: iLink Cable support (LAN Play)

### ISSUE THREAD

**Issue by modakuku** [PCSX2/pcsx2#6445]
### Description

Add iLink Cable support for link play in games like Time crisis 2 & 3

### Reason

A few games will benefit from this.

### Examples

![Screenshot_1](https://user-images.githubusercontent.com/107746432/174427851-b36e431d-7ccf-4248-acef-4808025a1608.png)

**Comment by Mrlinkwii** [comment]
duplicate of #4472
