### ISSUE TITLE
[BUG]: Crashes When Changing Internal Resolutions From 8x to 6x while Sync To Host Is Enabled

### ISSUE THREAD

**Issue by mrchrismania** [PCSX2/pcsx2#6447]
### Describe the Bug

The Emulator itself even when theres no game booted up it Crashes When Changing Internal Resolutions From 8x to 6x while Sync To Host Is Enabled its a bug with the Application itself

### Reproduction Steps

General Settings >> GS Window If I Have Sync To Host Ticked

Then i go to Graphics Settings >> If I then Switch to 8x Native Resolution Then Switch it to 6x Internal Resolution It causes the Emulator to crash. i have spent a while testing this and it only happens when Sync to host refresh rate is ticked inside the GS Window

I was able to reproduce this error on both my Desktop PC and Laptop

### Expected Behavior

was trying to play with sync to host enabled and i needed to change the resolution from 8x down to 6x when Playing GTA Vice City Stories which caused it to crash since i had the sync to host setting enabled.

### PCSX2 Revision

v1.7.2954

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
No crash for me, even in VCS when changing resolutions.

Can't really do much unless you provide the crash dump (use Qt).

**Comment by mrchrismania** [comment]
> No crash for me, even in VCS when changing resolutions.
> 
> Can't really do much unless you provide the crash dump (use Qt).

did you also have wait for vsync on refresh on standard and Sync To Host Refresh Rate Ticked?

Heres the crash dump i had a few of them in my crash dump folder.

[Crash Dump.zip](https://github.com/PCSX2/pcsx2/files/8933805/Crash.Dump.zip)

**Comment by stenzek** [comment]
That's not a Qt minidump.

**Comment by stenzek** [comment]
Closing since https://github.com/PCSX2/pcsx2/commit/c86e82039a0a4f4063a87d60455b37f328474376 was merged, this feature no longer exists in wx. If you're still getting crashes, disable it in the ini file, or switch to Qt.
