### ISSUE TITLE
[Feature Reimplementation Request]: Guitar Mapping

### ISSUE THREAD

**Issue by thardwardy** [PCSX2/pcsx2#6450]
### Description

I recently updated to the latest nightly from a fairly old build and noticed that you can no longer set the controller type to guitar in the new mapper. This causes the Guitar Hero and Rock Band games to be unplayable.

### Reason

As stated before, the GH and RB games are unplayable without guitar mapping.

### Examples

Exactly how it was before it was removed.

**Comment by stenzek** [comment]
If this is for qt, we know, see https://github.com/PCSX2/pcsx2/discussions/5947
