### ISSUE TITLE
[BUG]: Rumble Roses (SLPM-65885; CRC: C1C91715) - A few textures appear to be dumped more than once with different IDs

### ISSUE THREAD

**Issue by SaltyBet** [PCSX2/pcsx2#6451]
### Describe the Bug

When enabling texture dumping, most textures get dumped once.

But a few get dumped every single match.

### Reproduction Steps

1. Enable Texture Dumping.
2. Play a match.
3. Textures get dumped.
4. Play another match.
5. Some textures get dumped again, with a different ID.

### Expected Behavior

From what I understand, all textures should only be dumped once.

### PCSX2 Revision

v1.7.2954

### Operating System

Windows 10 (64bit)

**Comment by SaltyBet** [comment]
[emulog.zip](https://github.com/PCSX2/pcsx2/files/8934331/emulog.zip)

[dumps.zip](https://github.com/PCSX2/pcsx2/files/8934332/dumps.zip)

**Comment by stenzek** [comment]
Looks like it's using PSMT4HH, which should be fixed by https://github.com/PCSX2/pcsx2/pull/6494 (but I don't have this game to test).
