### ISSUE TITLE
[BUG - Oni]: Coding practice leading to emulation breakage.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#6452]
### Describe the Bug

PCSX2 (nor any PS2 emulators) never handled "Oni" correctly right from the beginning. It always required a patch to work.

Given that situation, I decided to take a look at the game code, with the help of a debug build in order to have the symbols name applied to the retail build. And the results are..... interesting.

The emulation issue is directly caused by the "DMA_TransferBuffer' function, or rather, improper coding from the developer when updating the said function.

Here is the beta code:

![Beta Oni](https://user-images.githubusercontent.com/105116470/174456202-9f91d4f2-bb5f-4da7-844e-df39f3e60eae.png)

And the retail one:

![Retail Oni](https://user-images.githubusercontent.com/105116470/174456216-6ddb644e-b495-421f-8b46-c88a3a11b9dc.png)
![Retail Oni 2](https://user-images.githubusercontent.com/105116470/174456219-f9649333-42a6-4c19-8a37-9c9297636645.png)

As you can see, there is a quite large difference between the 2.

But let's focus on the part that PCSX2 doesn't handle well on the retail build:

![image](https://user-images.githubusercontent.com/105116470/174456343-40aebe21-9800-4c3c-9ba2-52a39811b6e1.png)

As you can see, they pass in the function parameter through a PCR write. And then does what seems to me like a sanity check to ensure the COP is not busy? (sorry if that's absolutely not accurate, I does not know a lot from the PS2 itself).

But the question is.... why doing this check after the fact??? We just made a PCR write before it, so by this moment, we already fucked up the previous DMA if it was still busy.

Now let's take a look at the beta code:

![image](https://user-images.githubusercontent.com/105116470/174456566-ae7df55b-ab0d-4a74-aa94-9849deaf8076.png)

Now the PCR write is after the fact... I have not seen very often a beta which have better error checking than the retail build ^^.

And as expected, PCSX2 handles that version very well, without a single patch.

**But, if I am correct... How can the retail build not fucked up massively on real hardware!??**

The only reason I would think of, is if the DMA was fast enough to complete the previous write before the game writes the new one on top of it.

What the patch does is it reverts the PCR Write and the BC0F check inside that do - while function. The question is, wouldn't be safer to replicate the beta behavior and put the PCR write after the do-while?

Again, this might be a complete blob of non-sense, I am just trying to understand how that function works, and I have a very limited knowledge of the PS2 hardware/software.

I am just trying to point out the difference between the 2 builds, if a developer can explain to me what the "getCopCondition" function is, that would be awesome!

Also, as a side note, enabling the ee cache will produce a DMA error within PCSX2 itself when the game access that function:

![image](https://user-images.githubusercontent.com/105116470/174457640-8fb2e1d7-c144-458f-93da-adabefb8c47f.png)

### Reproduction Steps

Load Oni, and see how it behave with the PCSX2 debugger. (Sorry ^^, I don't know what to say really)

### Expected Behavior

Technically, the retail build should """work?""" like it does on real hardware. But let's be honest, I think PCSX2 just expose a massive race condition.

### PCSX2 Revision

v1.7.2955

### Operating System

Windows 11

### CPU

Intel I9 9900k

### GPU

Nvidia RTX 3070

### Logs & Dumps

I will capture a blockdump of both version, for proper debugging.

**Comment by F0bes** [comment]
I'd need to see the disassembly or decompiled  getCopCondition() to tell you what it's doing.

**Comment by refractionpcsx2** [comment]
The code which you're talking about that we patched, it's because the write is delayed on real hardware so the read happens before the write (if I remember the code correctly) so on real hardware it's fine, but we need to patch it.

**Comment by refractionpcsx2** [comment]
We do not emulate the delay, no, that's adding a bunch of complexity for a small thing we can fix by just patching the order of that and the next instruction (if they relate to each other)

**Comment by lightningterror** [comment]
Closing as not planned, workaround possible.
