### ISSUE TITLE
[Feature Request]: Possibility to change the Memory Card folder in qt

### ISSUE THREAD

**Issue by thejdss** [PCSX2/pcsx2#6455]
### Description

-PCSX2 version: 1.7.2961

-Description: An option to choose a directory that has memory cards, the same way it was before qt.

### Reason

My memory cards are stored in a hd while the pcsx2 is in a ssd and i share the same folder for other versions of the pcsx2 too.

### Examples

![Capturar](https://user-images.githubusercontent.com/41564548/174466176-e132ae0e-edd3-4656-899b-06a52e9748b3.PNG)

**Comment by stenzek** [comment]
Already done in https://github.com/PCSX2/pcsx2/pull/6453
