### ISSUE TITLE
[Feature Request]: Video/audio dump

### ISSUE THREAD

**Issue by kamijoan** [PCSX2/pcsx2#6456]
### Description

I know reworking the whole thing is a goal but right now the old one would still be useful, and as far as I've seen and been told, it's currently not in the most recent builds.

### Reason

Want to extract audio and video from the emulation, screen capture does not account for the variable speed in emulation and the dump function did. Also screen capture can't get output bigger than window resolution but video dump could get me 8k video if I wanted it to.

Please, thank you.

### Examples

PCSX2 1.6 stable has it, some 1.7 builds had it hidden under a toggle, not sure when it got removed/hidden, probably on the big GUI changes?

**Comment by RedDevilus** [comment]
It was never removed, it's just that 1.7 Qt builds don't have it yet, WX builds do.

**Comment by kamijoan** [comment]
Still valid feature request, I guess, but it solves my issue right now. Thank you.

**Comment by stenzek** [comment]
Already tracking in https://github.com/PCSX2/pcsx2/discussions/5947
