### ISSUE TITLE
[BUG]: Texture Dumper has new naming convention

### ISSUE THREAD

**Issue by takozhang1** [PCSX2/pcsx2#6458]
### Describe the Bug

The Texture Dumper new naming convention 

### Reproduction Steps

turn on texture dumping

### Expected Behavior

It used to dump textures with a textureHashValue-hexResolutionValue.png which let me write a script that replaced the mipmaps in ratchet and clank with all high-resolution textures using load custom textures something that cannot be achieved any other way.  The very next day broken.

### PCSX2 Revision

v1.7.2961

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Going to need a lot more detail here. Texture dumping works fine for me, and nothing has changed recently.

**Comment by takozhang1** [comment]
The bug was incorrect.  The mipmapping full ps2 emulation has to be toggled or it exports the mipmaps with different names in texture dump.  If anyone wants the python script that auto replaces mipmaps let me know.  It works on ratchet 1 and maybe the rest did not test.  Works on Shrek 2 but Shrek does not need it (just set mipmaps to off for same effect).  Could work on other games also.

**Comment by F0bes** [comment]
Closing then.
