### ISSUE TITLE
just for record at the moment gsdx in directx mode don`t work in windows 10 

### ISSUE THREAD

**Issue by annahana** [PCSX2/pcsx2#646]
operating system windows 10

problem 
if gsdx plugin is run in direct x 9/10/11 on start of a game the emulator will crash 

Setitngs ar on default
![crash](https://cloud.githubusercontent.com/assets/13276505/8624769/a94a5294-273a-11e5-8c96-b90bc1b2c036.PNG)
![pcsx2](https://cloud.githubusercontent.com/assets/13276505/8624770/a94c1f7a-273a-11e5-8bea-f2eb06d8dcde.PNG)

edit: as expected of me its missing directx 9c extensions in the new windows 10 installation

**Comment by refractionpcsx2** [comment]
You still need to install the directx libraries from the websetup the same as you would in older versions of windows.

**Comment by ssakash** [comment]
it worked well for me when I had tried the technical preview months ago.

**Comment by refractionpcsx2** [comment]
Yeah I would say this is more of a support issue. Until Windows 10 is out and this is confirmed not to be working (it works in Windows 8 so I see no reason why 10 shouldn't work) then I would assume any issues people have are because they haven't done something they should be.

**Comment by karasuhebi** [comment]
It might be an issue:
https://www.reddit.com/r/PCSX2/comments/3fe0wj/pcsx2_on_windows_10/

**Comment by refractionpcsx2** [comment]
It's not an issue, people think cos you have DX12 you don't need to get the DX Libraries, which you do.

I'm using windows 10 and having no issues at all.

**Comment by karasuhebi** [comment]
The guy on reddit is saying this:
"The DirectX libraries seems to have fixed things, except there's still a crash if I enter the configuration of LilyPad-SCP. Good enough."

Can you guys confirm the crash?

**Comment by caohothang** [comment]
hi, all
i found problem windows 10, because windows 10 using dx 12, we should change config like this image below, change to open GL instead of DX
![image](https://user-images.githubusercontent.com/7334495/36364575-70cb0520-1577-11e8-9eee-1730095708ac.png)
