### ISSUE TITLE
[BUG]: Qt versions after #6441 crash to desktop on esc press when fullscreen

### ISSUE THREAD

**Issue by noigeaR** [PCSX2/pcsx2#6462]
### Describe the Bug

In every build since #6441 PCSX2 crashes when pressing the esc key in fullscreen mode.

### Reproduction Steps

Fresh install of 1.7.2960 Qt or later.
Start any game, go fullscreen, press the esc key.
The "confirm shutdown" dialog shows for a second and without any action from the user PCSX2 crashes to desktop.
If PCSX2 is not in fullscreen, everything works as expected.

### Expected Behavior

PCSX2 should not crash to desktop.

### PCSX2 Revision

1.7.2964 AVX Qt

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Could be related to the emu also reporting MTGS died when messing with the GS settings also.

**Comment by noigeaR** [comment]
[crash-2022-06-19-19-12-08-661.txt](https://github.com/PCSX2/pcsx2/files/8936031/crash-2022-06-19-19-12-08-661.txt)
[crash-2022-06-19-19-12-08-661.zip](https://github.com/PCSX2/pcsx2/files/8936034/crash-2022-06-19-19-12-08-661.zip)

**Comment by dezraj** [comment]
Hello! I'm experiencing the same issue. I also have a crash dump if needed.

**Comment by alexey318** [comment]
got crash dump too. if needed.
