### ISSUE TITLE
[BUG]: QT interface does not accept virtual mouse imput

### ISSUE THREAD

**Issue by DNDEBUG** [PCSX2/pcsx2#6464]
### Describe the Bug

I am using https://github.com/rvaiya/warpd to have a virtual pointer
Nothing clickable works except the two buttons at the center **Add Game Directory** and **Scan For New Games**
other QT programs work
i am on wayland

### Reproduction Steps

Run PCSX2
Try to use Virtual Pointer
It does not work like it should
Day ruined

### Expected Behavior

Work just like a normal mouse would

### PCSX2 Revision

v1.7.2954

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Artix Linux

**Comment by stenzek** [comment]
Definitely not something I'm going to bother looking into. Especially since it's likely something to do with this program, or as issue with qt itself.
