### ISSUE TITLE
[Feature Request]: (Qt) Cheats and WS cheats menu

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#6465]
### Description

Cheats menus are currently missing from Qt build, I created this issue for tracking since #5947 discussion doesn't include it.

### Reason

· Achieve more progress parity with WX.
· Very crucial feature for playing games with limited widescreen support/no widescreen support at all and disabling in-game graphics features for more 'brr' on heavy CPU/GPU dependant games.
· Cheats are fun 😀

### Examples

Cheats menu on WX
![cheats](https://user-images.githubusercontent.com/19964653/174498808-d5ddc243-6750-43c3-a121-34123cda0572.png)

**Comment by dio-gh** [comment]
- that is not a "cheats menu"
- that is not missing (see Settings > Emulation > Enable Cheats)
- it is known, but i indeed can't see it being tracked. there's supposed to be a proper widget added for it that lists them, _that_ is missing

**Comment by refractionpcsx2** [comment]
cheat management is covered by #6244 and #1162

as pointed out, if you looked for it, you'd find the "Enable cheats" option.

**Comment by ElTioRata** [comment]
Alright. Thanks for clearing up!
