### ISSUE TITLE
[BUG]: Commit 4ee92fc63790d806b9c4639e5a3975d24a53258c breaks Turbo

### ISSUE THREAD

**Issue by pwilkin** [PCSX2/pcsx2#6472]
### Describe the Bug

Since commit 4ee92fc63790d806b9c4639e5a3975d24a53258c, the Toggle Turbo button doesn't work. The Hold Turbo option doesn't appear in the hotkeys menu and the Toggle Turbo hotkey behaves like the Hold Turbo hotkey. Running Windows nightly QT version.

### Reproduction Steps

Run build after commit 4ee92fc63790d806b9c4639e5a3975d24a53258c, try to use old Toggle Turbo hotkey, it uses the "Hold Turbo" functionality instead, doesn't work as a toggle.

### Expected Behavior

"Toggle Turbo" should toggle the turbo mode, not require it to hold down the key.

### PCSX2 Revision

1.7.2975

### Operating System

Windows 10 (64bit)

**Comment by grimpunch** [comment]
Ah I see the issue,
when I was correcting the bad merge before I put the hold logic into Toggle (basically breaking toggle)
I'll make a new branch with a bug fix to merge in to resolve against this 👍

**Comment by grimpunch** [comment]
Bugfix is here: 
https://github.com/PCSX2/pcsx2/pull/6475

@lightningterror 
@stenzek

**Comment by grimpunch** [comment]
https://github.com/PCSX2/pcsx2/pull/6475 has been merged, @pwilkin can you retest on a subsequent build?

**Comment by pwilkin** [comment]
Can confirm it's fixed.
