### ISSUE TITLE
[Feature Request]: Qt; Allow mapping the same action to several different inputs (across controller, keyboard etc).

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6477]
### Description

For feature parity with Wx, and also as an addition to this issue https://github.com/PCSX2/pcsx2/issues/6198 , there should be a way of mapping an action/hotkey to several different inputs. This will be important when/if https://github.com/PCSX2/pcsx2/issues/6198 does get added to Qt.

### Reason

This allows for a wide variety of customization and solves some key problems (some combined with the addition of pressure sensitive mapping).

### Examples

In Metal Gear Solid 2/3 (on Wx/LilyPad) I have Square on my DualShock 4 controller bound as Square:0.129 sensitivity, and the touchpad on the controller bound as Square:1.000 sensitivity. This allows me to raise a rifle with Square, and only start firing when rolling my thumb over to the touchpad. This maintains (in a way) crucial functionality for certain games, and also futureproofs the emulator in terms of preservation (not many new controllers support physical pressure sensitive face buttons).

**Comment by stenzek** [comment]
This is already a thing. Hold shift while clicking the binding (same as duckstation).

**Comment by nobleflame** [comment]
> This is already a thing. Hold shift while clicking the binding (same as duckstation).
> 
> For the inverse (multiple actions for a single button), it's also already possible, just bind it as expected.
> 
> As for pressure, I was planning on making a "pressure modifier" button. I don't see the point in overcomplicating the binding system with per-bind pressures for the sake of one game.

So, with the pressure modifier (and the SHIFT remapping mentioned above) will I be able to remap buttons and change their sensitivity? For example: in some games that rely on pressure sensitive face buttons, I often remap them to the triggers on my XBOX controller. I then tune the sensitivity of the triggers.  

Cheers, Stenzek for all of your work!
