### ISSUE TITLE
[BUG]: Qt; DsHidMidi + DualShock 3, up/down on analog sticks is auto-mapped the opposite way.

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6479]
### Describe the Bug

DualShock 3 controller connected with USB, through DsHidMini (with the new fixed .dll). Seen as XInput source in Qt. Automatic binding binds everything correctly EXCEPT the two analog sticks; up/down is reversed.
It is mapped correctly when the controller is seen as a DS3 by Qt, but that makes the pressure-sensitive buttons behave as digital, defeating the purpose.

### Reproduction Steps

.

### Expected Behavior

Easy to bind manually of course, but still a small bug. Works fine by default in RPCS3 for example.

### PCSX2 Revision

v1.7.2978

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
As in #6480 this is not an issue on our end.

**Comment by stenzek** [comment]
Reopening and tagging @CookiePLMonster as I didn't realize SCP went through a different function (needs to be inverted to match base XInput).

**Comment by CookiePLMonster** [comment]
Fixed in https://github.com/PCSX2/pcsx2/pull/6481
