### ISSUE TITLE
IOCTL_CDROM_RAW_READ fails for CD-ROM games in many drives

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#648]
I wouldn't know if "many" is really the right determiner. 
My narrow experience though [tell](http://web.archive.org/web/20021206183205/http://www.btceurope.nl/product_home.html) me [that](https://web.archive.org/web/20030213004916/http://www.lge.com/c_product/catalog/product_information.jsp?mdl_pfx=4CDWS&mdl_cod=GCE-8400B&mdl_mak=1) out [of](https://web.archive.org/web/20090411041856/http://www.liteonit.com/global/index.php?option=com_content&task=view&id=251&Itemid=67) 9 [readers](https://web.archive.org/web/20120604031008/http://www.samsung.com/my/consumer/pc-peripherals-printer/optical-disc-drive/dvd-rom/SH-D162D/RSBP) I [tried](https://web.archive.org/web/20120613182714/http://www.samsung.com/ca/consumer/office/optical-disk-drives/optical-disk-drives/SH-S223C/BEBE) only [four](http://web.archive.org/web/20070402110200/http://www.sonynec-optiarc.eu/en/exhibits/hh-drives/ad-7170a.html) [could](http://web.archive.org/web/20150906164550/http://hlds.co.kr/product/e_dvd_series.php#GT34N) [handle](http://club.myce.com/f44/dh-16a6s-crossflashing-304838/#post2469234) [CDs](http://www.lg.com/us/burners-drives/lg-GUB0N). 

When pcsx2 enters "2340" mode (which has to be read with either XAForm2 or YellowMode2) I can see in Process Monitor that device says *Control: 0x2403e (Device:0x2 Function:15 Method: 2)* is an invalid request. 

Emulogs (if required) are [here](http://forums.pcsx2.net/Thread-Bug-Report-Tom-Jerry-s-War-of-the-Wiskers-PAL). 

One way to workaround this would be using SPTI as ripper softwares do (as gigaherz suggested), but there must be a simpler way to make stupid drive understand the normal command. 

Given I can workaround this with ISOs I won't offend if somebody put a *Low Priority* or *longterm* label.

**Comment by karasuhebi** [comment]
@gigaherz Fix it :P

**Comment by gigaherz** [comment]
Nope. If your optical drive sucks, either fix it yourself, of get a new optical drive. ;P

**Comment by gigaherz** [comment]
Gave it the Enhancement label because it isn't a bug with the plugin itself (as far as I can tell), but instead of with the drive not supporting the reading mode.

**Comment by mirhl** [comment]
Ok, so.. from the bottom of my inferior knowledge
I found only two things potentially.. odd. 
One, is that every NULL parameter is ![reported](https://cloud.githubusercontent.com/assets/9366725/8638109/a3ce595c-28af-11e5-8fd1-44fdf8594904.jpg) to be a bad pointer (even with other IOCTL functions and in the working drive). 
Then, are we getting the [handle](http://microsoft.public.win32.programmer.kernel.narkive.com/P3iChoNp/data-stored-on-cds-in-raw-mode#post2) of drives right?

**Comment by ramapcsx2** [comment]
Hey, I ran into this issue as well once. Thanks to your research I now know it was the hardware not supporting a particular read mode. Trying substitutes didn't really work either.
So is there a desktop pc drive that works?

**Comment by mirhl** [comment]
Well, I guess gigaherz has one, considering he seems to never have experience this. 
Still, I'd like to know what actual detail all these devices have in common to not work

**Comment by gigaherz** [comment]
Back in the day I tested a bunch of CD games, and even CDDA, and they worked. I don't have that same optical drive anymore, though. ;P

**Comment by mirh** [comment]
OMG, THIS IS SORCERY
http://ixbtlabs.com/articles2/magia-chisel/

**Comment by ramapcsx2** [comment]
The essence of that article is something like: Many drives misinterpret data for something called a sync header (which may be the code @mirh linked to). It's a firmware bug. Or our "header pattern" isn't 100% right and triggers wrongly.

**Comment by turtleli** [comment]
Can you successfully rip BIN images from the affected drives?

I could possibly look at the SPTI stuff while I mess about with the code (well, really I'm investigating what needs to be done to port it to Linux).

**Comment by FlatOutPS2** [comment]
Of all CD-ROM games I had issues with, none had issues ripping to BIN images,

**Comment by turtleli** [comment]
> Of all CD-ROM games I had issues with

So you only had issues playing some games from CD and not all of them?

I'll probably need to write some tools to look at the disc info and stuff.

**Comment by FlatOutPS2** [comment]
Yes, like @mirh says in the OP, I believe it only happens with games which change read mode to XAForm2 or Yellowmode2.

**Comment by mirh** [comment]
I have no problems ripping them, even if it's just into plain iso with imgburn. 

The problem just manifests when booting games. And the hypothesis was that mindblowing article above.

**Comment by ssakash** [comment]
FWIW, Let's close this issue when #1545 is merged to master branch.
