### ISSUE TITLE
[BUG]: Qt; DsHidMidi + DualShock 3. Vibration is not working, "No devices with vibration motors were detected."

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6480]
### Describe the Bug

DualShock 3 controller connected with USB, through DsHidMini (with the new fixed .dll). Seen as XInput source in Qt. When trying to set the vibration motors the error message above shows up. No vibration in-game.

(The reason it is being set to be seen as XInput is because that's the only way to get the pressure-sensitivte buttons to work). Vibration is not working when seen as a DS3 either.

### Reproduction Steps

.

### Expected Behavior

When using a DualShock 4 through DS4Windows (seen as XInput) the vibration works as intended. When using a DualShock 3 with DsHidMini on RPCS3 the vibration is picked up and mappable by default.

### PCSX2 Revision

v1.7.2978

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Works fine with an xbox one pad. This means that it's almost guaranteed to not an issue on our end, as the XInput API is *very* simple and doesn't leave much room for error.

DsHidMini might not be filling in `XINPUT_VIBRATION` in the capabilities query.

**Comment by nefarius** [comment]
> DsHidMini might not be filling in `XINPUT_VIBRATION` in the capabilities query.

Looking into it 👍

**Comment by refractionpcsx2** [comment]
Thanks @nefarius :)

**Comment by nefarius** [comment]
[Test-Build](https://buildbot.vigem.org/builds/DsHidMini/master/3.0.371.0/bin/x64/XInput1_3.dll).

**Comment by CookiePLMonster** [comment]
I can confirm that vibration works fine with this build of the DLL.

**Comment by jonasos3** [comment]
Great! Works perfectly now, thanks a lot :)
