### ISSUE TITLE
[BUG]: controller double clicking d-pad & analog (Def Jam Fight For NY)

### ISSUE THREAD

**Issue by xFaHaDz** [PCSX2/pcsx2#6482]
### Describe the Bug

Issue: controller double clicking d-pad & analog (Def Jam Fight For NY).

-PCSX2 Nightly: v1.7.2979 (QT).

-PCSX2 options: Defaults.

-Description: basically when lunching the game (Def Jam - Fight For NY) in The Nightly version 1.7.2979 (QT), the controller will start double clicking (D-pad & Analog sticks).
and when you want to choose anything from game dashboard it'll start skipping each selection and off. (sorry for my bad English but hope the pics i'll attach will help understanding)..
Note: The stable PCSX2 1.6 version don't have this issue and everything works fine there.

![Screenshot 2022-06-20 182055](https://user-images.githubusercontent.com/107939483/174848358-b76bb8dd-3d9d-41f2-8ce9-fcc2fc91f1d2.png)
![Screenshot 2022-06-20 182320](https://user-images.githubusercontent.com/107939483/174848369-4c737caa-9a6f-4184-be52-7c16fd5284a9.png)

-How to replicate: just lunch the game normally on the latest Nightly version QT, and try moving in the game dashboard with the D-pad & analog sticks.

-Controllers: i tried: DS4, Xbox 360 and Xbox one controllers. and the issue was still on all of them.

-PC specifications:
CPU: Intel Core i7-4790K @ 4.00GHz.
GPU: Gigabyte Geforce GTX 980 Windforce 4GB.
OS: Windows 10 Pro (64-bit).

### Reproduction Steps

just lunch the game normally on the latest Nightly version QT, and try moving in the game dashboard with the D-pad & analog sticks.

### Expected Behavior

as i mentioned above.. when moving on the dashboard menu or typing with the controller D-pad or analog sticks.. it'll start skipping selections and do like a (double clicks)
### PCSX2 Revision

v1.7.2979

### Operating System

Windows 10 (64bit)

### CPU

i7-4790K @ 4.00GHz

### GPU

GTX 980

**Comment by coornio** [comment]
Can't account for the DS4, but due to an experience a day or two ago, please try to disable SDL in the controller settings and enable xinput instead, then bind your xbox controller manually. Please let me know if that's made any difference.

**Comment by xFaHaDz** [comment]
> Can't account for the DS4, but due to an experience a day or two ago, please try to disable SDL in the controller settings and enable xinput instead, then bind your xbox controller manually. Please let me know if that's made any difference.

Thanks for the tip, i disabled SDL and enabled Xinput instead and bind it with my xbox controller automatically and it worked and fixed the issue, but sadly not for the DS4. but thank u.

**Comment by coornio** [comment]
> > Can't account for the DS4, but due to an experience a day or two ago, please try to disable SDL in the controller settings and enable xinput instead, then bind your xbox controller manually. Please let me know if that's made any difference.
> 
> Thanks for the tip, i disabled SDL and enabled Xinput instead and bind it with my xbox controller automatically and it worked and fixed the issue, but sadly not for the DS4. but thank u.

Thanks for the followup. While we're at it, do you perhaps have DS4Windows installed? In addition, is perhaps Controller 2 in the emulator bound to anything or are its buttons blank?

**Comment by Dakitoss** [comment]
for those who have a ps4 controller, didn't test it to be sure, but i think it works if you just mark the 2° as not connected in the controller configs
