### ISSUE TITLE
[Feature Request]: USB Support for Qt

### ISSUE THREAD

**Issue by kookycake** [PCSX2/pcsx2#6489]
### Description

I want USB support to be added to Qt, so that way we can play more games like Eyetoy games, Singstar games, etc.

### Reason

It would bring more compatibility to the games available to be used on the Qt version (examples include the Eyetoy games). Plus, it would be more convenient rather than switching back in forth from playing the normal games on Qt, then going to Wx for the USB supported games.

### Examples

Just like Wx does it.

**Comment by RedDevilus** [comment]
Tracked on https://github.com/PCSX2/pcsx2/discussions/5947

Keep in mind that this will be a humongous task where it needs a total rewrite as the WX side is awful and would be incompatible either way on Qt.

As an example LilyPad was awful as well and got dropped in favor for more easy tinkering and better inherent stability with OnePad. 

This situation isn't happening with the USB side as it's a free for all on plugins and a bit neglected on code quality. I hope this answers your request but this doesn't mean it won't happen.

You can use the WX side for now if needed. Have a good day.
