### ISSUE TITLE
Spider-Man 2  texture bugs

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#649]
It looks like this https://www.youtube.com/watch?v=QDb50qtisqI probably a texture cache issue.

**Comment by prafullpcsx2** [comment]
Nice coincidence, I was posting about it in the forums but just noticed your report here. i will rather continue here now.

Here is the GS dump.

http://www.filedropper.com/spiderman2

**Comment by karasuhebi** [comment]
@ADormant Are you having that issue in the latest dev builds? The PCSX2 build the uploader used in that video is very old.

**Comment by bositman** [comment]
Since no one bothered to make an actual proper bug report, I'll do it and close this.

**Comment by FlatOutPS2** [comment]
Also Duplicate of #775
