### ISSUE TITLE
[BUG]: The game grid scrolling performance is heavily degraded by setting the covers

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#6490]
### Describe the Bug

The game grid scrolling performance is heavily degraded by setting the covers, especially when the grid is zoomed out to fit more items on every page

### Reproduction Steps

* Set the view to game grid
* Set covers for more than a page of homebrew/apps/games
* Zoom all the way out
* Scroll a page down
```
📦📦📦🗕🗖 ❎ 〰️ 🕛
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦 〰️ ⬇
📦💽💽💽💽📦 〰️ ⬇
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The GUI thread freezes for a few seconds (2-10s) until a page of covers is loaded
```
📦📦📦🗕🗖 ❎ 〰️ 🕐
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
  ⌛ ⌛ ⌛ ⌛
  ⌛ ⌛ ⌛ ⌛
  ⌛ ⌛ ⌛ ⌛
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The second page is loaded
```
📦📦📦🗕🗖 ❎ 〰️ 🕑
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The second page is focused and the GUI is unblocked
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕒
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```

### Expected Behavior

* Scroll a page down
```
📦📦📦🗕🗖 ❎ 〰️ 🕛
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦 〰️ ⬇
📦💽💽💽💽📦 〰️ ⬇
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
* The grid should scroll to the next page immediately and display temporarily placeholders
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕐
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦⌛ ⌛ ⌛ ⌛📦 〰️ 🖲️
📦⌛ ⌛ ⌛ ⌛📦
📦⌛ ⌛ ⌛ ⌛📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```
*  The covers should be loaded in background from the disk
```
  💽💽💽💽
  💽💽💽💽
  💽💽💽💽
📦📦📦🗕🗖 ❎ 〰️ 🕑
📦📦📦📦📦📦
📦💽💽💽💽📦 
📦💽💽💽💽📦 〰️ 🖲️
📦💽💽💽💽📦
📦💽💽💽💽📦
📦📦📦📦📦📦
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
   ❓ ❓ ❓ ❓
```

### PCSX2 Revision

PCSX2 Nightly - v1.7.2991

### Operating System

Windows 10 (64bit)

**Comment by wefalltomorrow** [comment]
Can confirm, happening to me as well. A bit annoying, hopefully it gets fixed soon :)
