### ISSUE TITLE
[Feature Request]: (Qt) Game banners

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6491]
### Description

Game banners in the game list.

### Reason

QoL feature.

### Examples

None

**Comment by refractionpcsx2** [comment]
What do you mean by game banners? This is the PS2 not the arcade, and we already have game covers.

**Comment by ichee** [comment]
I think they’re referring to banners as they are presented in Dolphin in list view.

![772BD1E6-5838-41B5-ABA5-B352AF4E90F0](https://user-images.githubusercontent.com/22252639/175119391-7949b100-429c-40a8-befb-5b4aebb3040c.jpeg)


Maybe replacing the disc icon in Pcsx2 with something similar, or a place where users can add their own.

![218A4AC4-0B99-4C5C-8380-4FF69F517617](https://user-images.githubusercontent.com/22252639/175119704-5d61c607-51c2-4a28-9ac6-8d42b63086e9.jpeg)

**Comment by stenzek** [comment]
-1 from me for this. This works for Wii games because they have banner art on the disc, PS2 games have no such banner. The closet thing is the memory card save icon, and there's no direct correlation between memory card filenames and disc serials.

**Comment by Rex000** [comment]
Makes sense. I didn't know about this. I'll close it then.
