### ISSUE TITLE
[BUG]: Renderer information on top-bar broken ( shows ${gsdx} ) on Wx.

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6496]
### Describe the Bug

The top-bar usually shows information reg. what renderer is being used. On latest nightly Wx shows this instead
![Desktop Screenshot 2022 06 23 - 20 25 03 58](https://user-images.githubusercontent.com/88314420/175369305-6897244b-df8c-4614-81ad-61cc36bd355c.png)

### Reproduction Steps

Happens on any renderer.

### Expected Behavior

Should display correct information.

### PCSX2 Revision

v1.7.2991

### Operating System

Windows 10 (64bit)

**Comment by lightningterror** [comment]
It's not broken, you're using an old config.

**Comment by wefalltomorrow** [comment]
> It's not broken, you're using an old config.

How does one update nightly builds and keep their configs without this occurring?

**Comment by refractionpcsx2** [comment]
edit the pcsx2_ui.ini and delete the line that starts `TitleTemplate=`

**Comment by wefalltomorrow** [comment]
> edit the pcsx2_ui.ini and delete the line that starts `TitleTemplate=`

Thanks, worked perfectly!
