### ISSUE TITLE
Spider-Man 3 freezes

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#650]
Game is unplayable because it freezes after the first level. It never worked correctly on PCSX2.

**Comment by yorkiesandskittles** [comment]
I'm pretty certain the PAL version has worked for most PCSX2 versions. Not
sure about the NTSC version.

**Comment by refractionpcsx2** [comment]
and can you please follow these guidelines? https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

Thanks
