### ISSUE TITLE
[BUG]: Spongebob Squarepants featuring Nicktoons: Globs of doom character icons do not look like what was intended (Spongebob, Jimmy, Danny, and Tak only)

### ISSUE THREAD

**Issue by kookycake** [PCSX2/pcsx2#6501]
### Describe the Bug

I have noticed that in all the renderers (except for Software), the character icons for Spongebob, Jimmy, Danny, and Tak do not look as it is intended to be as shown here: ![2022-06-23 (11)](https://user-images.githubusercontent.com/106796925/175434533-8e09b990-7970-4d20-be93-3ca5c3d191a8.png) Miraculously, the other character icons are unaffected by the change in renderers as shown here:
![2022-06-23 (14)](https://user-images.githubusercontent.com/106796925/175434591-b3e73bae-1097-4f43-bf3a-b70542a71f00.png)
![2022-06-23 (13)](https://user-images.githubusercontent.com/106796925/175434593-4154422c-eb64-45e9-9f81-536ef2145437.png)
 

### Reproduction Steps

I honestly have no idea on how to fix this.

### Expected Behavior

Spongebob, Tak, Danny, and Jimmy's character icons should look like this:
![2022-06-23 (12)](https://user-images.githubusercontent.com/106796925/175434467-797c2010-77fe-436a-b8b7-1329a53dc514.png)
![2022-06-23 (15)](https://user-images.githubusercontent.com/106796925/175434481-ba6dc3cc-b7d1-414a-919f-7de43a02a5fc.png)
![2022-06-23 (17)](https://user-images.githubusercontent.com/106796925/175434488-1b687259-24ac-49ea-a9aa-bb6d52bfdfd2.png)

![2022-06-23 (16)](https://user-images.githubusercontent.com/106796925/175434484-05672ad3-1e84-4dc1-9fe4-a927686439d6.png)
 

### PCSX2 Revision

v1.7.2994

### Operating System

Windows 11

### CPU

AMD Ryzen 5 4600h

### GPU

GTX 1650 TI

### GS Settings

![2022-06-23 (18)](https://user-images.githubusercontent.com/106796925/175434375-d275a591-aa15-4cd1-8a7c-ea36fa57b52b.png)
![2022-06-23 (19)](https://user-images.githubusercontent.com/106796925/175434380-4746476e-062c-4975-986e-8c2823620278.png)
![2022-06-23 (20)](https://user-images.githubusercontent.com/106796925/175434383-bb10a31b-ebc6-4fef-9928-7f1e957cbd16.png)
![2022-06-23 (21)](https://user-images.githubusercontent.com/106796925/175434385-39f6bbbf-4988-46a8-9963-af309d70508f.png)
![2022-06-23 (22)](https://user-images.githubusercontent.com/106796925/175434387-95c98267-284c-4eb7-bcff-6ade42d0c91a.png)
![2022-06-23 (23)](https://user-images.githubusercontent.com/106796925/175434392-252f2b18-634e-4336-9c5e-ebbfec761b20.png)
![2022-06-23 (24)](https://user-images.githubusercontent.com/106796925/175434393-0725b402-af45-471d-9be9-1ab9ed9d73f1.png)
![2022-06-23 (25)](https://user-images.githubusercontent.com/106796925/175434394-9f6c0d41-aac7-4223-9889-d31c790daa52.png)
![2022-06-23 (26)](https://user-images.githubusercontent.com/106796925/175434397-daac5814-1b63-44d1-a8f0-88ba1bb79bdd.png)
![2022-06-23 (27)](https://user-images.githubusercontent.com/106796925/175434400-ced8ec2b-acba-4a41-aa04-eace89126a2e.png)
![2022-06-23 (28)](https://user-images.githubusercontent.com/106796925/175434403-2fa4f84d-659b-44d9-aa09-ec80b5fb4cbf.png)

**Comment by Saif1YT** [comment]
There's also a weird animation when u boot the game but thats minior

**Comment by Limo6699** [comment]
oh yes, I finally fixed it, you just need to select the OpenGL (Hardware) render type in the plugin settings, that's all!

**Comment by refractionpcsx2** [comment]
Okay, we can add that automatically for 1.7, thanks :)

**Comment by Saif1YT** [comment]
Or turn on mipmapping that also works
