### ISSUE TITLE
[Feature Request]: (Qt) Per-game controller settings in the right-click menu

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6505]
### Description

Custom controller config option in each game's right-click menu.

### Reason

Ease of use

### Examples

-

**Comment by F0bes** [comment]
For future reference, you should've been able to re-open your issue.

**Comment by Rex000** [comment]
I couldn't. It was only possible if I closed it myself.

**Comment by F0bes** [comment]
Ah I see.

Create a new profile (at the bottom)
![image](https://user-images.githubusercontent.com/29295048/175597129-4f45ac23-ff8b-4552-905a-7fd862384b13.png)


Select the new profile
![image](https://user-images.githubusercontent.com/29295048/175598679-b6b5195a-b923-4e2e-ab76-54984326a068.png)

**Comment by Rex000** [comment]
Yes I know about this but I want to request the ability to have the config option in the right click menu for better convenience.

**Comment by F0bes** [comment]
I see, you wish for a context menu action that allows you to check what profile you'd like to use.

**Comment by Rex000** [comment]
No, I mean the entire controller settings dialogue. We should be able to access it from the right click menu of each game and set custom inputs. The input config then should be saved by the game's serial+crc, similar to how game settings are saved.

**Comment by stenzek** [comment]
No. You can already set an input profile per game in properties.

I considered doing per game inputs but decided against it because generally you'll have overlap between games and it makes sense to share those profiles.

If you *really* want to set it per game you can manually do it in the ini. But that's not the intended workflow.

**Comment by Rex000** [comment]
You're quite right. I actually want to keep the current option too as it comes in handy. But I also found that in case you had remove the emulator for whatever reason and install a fresh copy, it can get quite confusing to remember which games shared the same profile.

**Comment by stenzek** [comment]
Then don't remove it? It's no different to having to rebind everything for every game again, except the profile saves time.
