### ISSUE TITLE
Unplayable Harry Potter games

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#651]
Some Harry Potter games like ''Harry Potter and the Chamber of Secrets , ''Harry Potter and the Prisoner of Azbakan'' and ''Harry Potter and the Half-Blood Prince'' are unplayable. They don't boot at all or just showing some letters. It's plausible they've something in common.

**Comment by karasuhebi** [comment]
Do they boot in Play!?

**Comment by refractionpcsx2** [comment]
Failed to provde necessary information.

**Comment by karasuhebi** [comment]
Someone should have at least told him he needed to provide more info. :-\

@ADormant if you're still around, please do this:
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by refractionpcsx2** [comment]
we did, in the other one he put up at the same time, he failed to provide information on that one as well, only Prafull saved that issue from being closed.
