### ISSUE TITLE
[Feature Request]:(Qt) hotkey to open the settings menu

### ISSUE THREAD

**Issue by DNDEBUG** [PCSX2/pcsx2#6515]
### Description

hit keys
menu opens
:)

### Reason

There is none

### Examples

F7 isn't being used i think

**Comment by refractionpcsx2** [comment]
why? You have to go back to using normal keys/mouse once you get in to the settings anyway, so what's the point in having a hotkey for it?

The hotkeys are designed for swapping settings on the fly, like turbo, or full screen, or software render switching, or aspect, not opening menus, you can do that manually.

**Comment by DNDEBUG** [comment]
most of Qt supports keyboard only except that menu thing
also there are people who can't use a mouse for some reason

**Comment by refractionpcsx2** [comment]
I've never seen anybody not able to use a mouse, but there's no reason to need a hotkey to go diving in to the settings. Hotkeys are for quick access to things, messing with the settings is not quick access, you will pause your game to do that.

**Comment by DNDEBUG** [comment]
the make that damn options menu clickable with a virtual mouse
i can't use it

**Comment by refractionpcsx2** [comment]
As far as I'm aware, that's a Qt problem, not ours. so complain to them, then we can update.

**Comment by refractionpcsx2** [comment]
Better solution, buy a mouse, they're like a couple of bucks for a shit one.

**Comment by refractionpcsx2** [comment]
okay we've worked out a hotkey for you

F11
then Alt + E
