### ISSUE TITLE
[Feature Request]: Consider Move, Rename or Remove "Enable No-Interleacing" Patches"

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#6516]
### Description

Remove patches / resources related to No interleacing, because many are old, not work, anymore due to hacky nature this codes and new advancements in PCSX2 accuracy many codes do nothing now, crash in video play or can slow the PCSX2 deveplopment trying to making compactible this codes.

Consider take same aproach as yuzu emulator has a link webpage for "graphic mods" link the user to special "wiki" with lastest mods with image enhacement related leaving in charge of comunity,

in PCSX2 example can be:
--Image enhacement mods (instead no interleacing)  (link to designated forum)

this offload "mods codes to" forums community with the lastest code mods updates etc and support to each section also make visible forum easily in emulator for new people (yes still people dont know where the PCSX2 forums are, or if exist ...what lazy times...),  also this can be solution for the news codes in 60fps and widescreen section.

-for the OLD no interleaced codes not working and really do something to image can be reworked in better / improved codes  in forums and maintained like any CHEATS file (instead if updating the resource file) leaving user with desicion if combine codes other codes like 60fps codes and keeping as CHEAT code  not as feature requirement option.

### Reason

-doign codes as passtime  for "no interleacing thread forums mainly" keep testing updating codes etc, now with PCSX2 new corrections, new features like (antiblur) or accuracy can match image quality so many this "no interleacing codes" codes are not needed anymore or others codes can be updated reworked to be compactible with new features, fixes, the no interlacing option in emulator can confuse users if enable, disable or use codes from "no interlacing section" in cheats folders or update the .zip in resources (some people can enable all options and enable cheats too with same updated codes) 

-codes with new image enhacements are scattered combined in "no iterleacing forum mainly, widescreen section, 60 fps section, cheats", 

-in the "No interleacing" thread patches can be difficult to track or update in resourses pack PCSX2.

-Many games not require this codes (the progresive compactible ones, the full frame type, other looks ok with deinterlacing automatic) confuse users "no interleacing" as " image quality" requirement, like i said many codes do same as default deinterleacing "automatic" + antiblur enabled or enabling default game progressive modes, so giving user a "placebo effect".

in the end too much options variables if enable cheats, if no interleacing options if widescreen codes or put other codes i which section leads many files to confusion, i think this should be keeping simple and accesible, all custom codes need to be treated as hacks in CHEATS folder and "maybe seasonal tested" codes as resource pack (like widescreen) i think this way will have a clean tracking code for users and leave developers peace of mind for implementing bunch of CHEATS subsections in emulator,  if something not work after some future update and game work as inteded the cheat code will be 99% the culprit.

### Examples

![image](https://user-images.githubusercontent.com/12580269/175793688-5e33c281-8b9b-44dd-a71a-ff53b841d07c.png)

option in yuzu emulator, something similar for PCSX2 can lead full usage the forums instead keeping update the resource files in emualtor,  i think as example: that resource files should be considered for fully tested seasonal codes only by the PCSX2 comunity forums or discord for animate fans of each game to demostrate best codes to be included (only thinking possibilities....)

**Comment by JordanTheToaster** [comment]
Even with fixes in place interlacing in games will still make them noticeably worse compared to using no interlace patches in games such as GT3 or GT4 there is no reason to remove no interlace patches as it stands.

**Comment by JordanTheToaster** [comment]
Here is a pretty simple example of why no interlace codes are needed.

No patch
![image](https://user-images.githubusercontent.com/80843560/175794102-6d40e2ac-4bd6-438a-a9ca-4ef9f5e947f6.png)

With patch
![image](https://user-images.githubusercontent.com/80843560/175794110-dc5f3505-6307-48e4-b7b1-403fc446fb9f.png)

**Comment by felixthecat1970** [comment]
that games not rely in scegshalfoffset function so it works as intended also i did las year custom patch for gt4 (usa) in some part forums not remember now, and read some weeks ago someone improve something in this code too in somewhere in thread, but my preocupation is other patches (mainly the one who relies in scegshaloffset) not work anymore a need to be ported to better hack instead start asking developers for support it, maybe my intention is not give to developers the necesity to implement something who lead to slow development, maybe this resource pack no to be improved or maintained for someone

**Comment by JordanTheToaster** [comment]
Widescreen patches also aren't guaranteed to work and have been in the emulator since before 1.4 should we remove them too? Patches are always updated just before a stable release as has happened with 1.6 so maintaining them isn't an issue either.

**Comment by felixthecat1970** [comment]
:) maybe i taking too seriusly.... or trying to give a better solution because each section forums  widescreen, no intelreacing other codes are improved but changes or news are not available for end users till new copilation ... (and thinking in person who start to download each file for stable releases. is a hard work) still, my intention is with no interleacing, widescreen works ok and people who know go to forum widescreen a start looking for news each game (not using the resource pack)

**Comment by felixthecat1970** [comment]
or maybe for no do much fuzz about it, led know people use the no interleacing forum thread for know what games not work and start looking for better codes,... anyway thanks for comment i remember last year that granturismo 4  code make me think very hard.....

**Comment by F0bes** [comment]
I'm not against hosting widescreen and no-interlacing patches on Github instead of the forum. That would allow removing, modifying and creation there in the form of pull requests. Firstly, this has the benefit of being able to be automatically pulled into CI or local PCSX2 builds, therefore it is up to date. Secondly, there would be proper version control.

**Comment by felixthecat1970** [comment]
MIPS, number,s letters, read post and no sleep led me to write bunch things withow think better, sorry  by that, rest some hours and think clearly now,  my intention was write something about better system to sync advancements in codes from no -interleacing, 60-fps, widescreen, fixes sections other similar from forums related to = "graphic mods" in emulator, testing couple of weeks github i see the possibilities like Fobes said a keep offload from PCSX2 deveplopment using the pcsx2 users comunity in forums or discord in form like Fobes said pull-request leaving to fans/users many games focusing in test, make better "graphic codes - mods codes" and sync with main pcsx2 and led the user decide sync "this codes" form custom folder example "graphic mods" something similar to CEMU emulator graphic packs are in sync in custom repo and people can sync wherever they like with new advancements, the test can be no-interleacing codes (because many not work, need to be reworked etc) and after "beta test" can be extrapolated to widescreen, 60 fps or graphics codes related, i would like to said i can take the responsibility but now my life is hard (no jobs, almost no money) keep me worried and code making is my passtime till find some job or solution for money, i will close this a leave the ideas if someone can materialize, have the skill, time, energy and make better PCSX2, thanks.
