### ISSUE TITLE
[BUG]: Accelerator key underlines don't auto-disappear on themes other than Native

### ISSUE THREAD

**Issue by Daisouji** [PCSX2/pcsx2#6517]
### Describe the Bug

ALT+E Does not toggle the underline keyboard accessiblity feature.

### Reproduction Steps

1) Try the ALT+E /ALT  shortcut on non-native theme
2) Menu does the usual underline accessibility feature, underlining the first letter of each menu label
3) Now click ALT again, the feature is not turned off

### Expected Behavior

 Menu does the usual underline accessibility feature, underlining the first letter of each menu label and then ALT+ whatever letter is underlined. And then you can toggle it off or on w/ ALT, (IdK if that is QT6 related (Duckstation is sharing the same behavior) and dolphin is doing everything properly.

### PCSX2 Revision

Nightly 1.7.3006

### Operating System

Windows 10 (64bit)

**Comment by dio-gh** [comment]
![image](https://user-images.githubusercontent.com/10439488/175794962-f262c7b7-9a08-4337-9614-5a2ffed086aa.png)

- works on a non-native theme
- underlines are present
- ALT is a keyboard button, not sure how you click it

**Comment by Daisouji** [comment]
> ![image](https://user-images.githubusercontent.com/10439488/175794962-f262c7b7-9a08-4337-9614-5a2ffed086aa.png)
> 
> * works on a non-native theme
> * underlines are present
> * ALT is a keyboard button, not sure how you click it

Press it again

**Comment by dio-gh** [comment]
Nothing happens?

**Comment by Daisouji** [comment]
> Nothing happens?

That's the point, ALT is a toggle for that feature.

**Comment by dio-gh** [comment]
No, the feature is ever-present. ALT is simply the modifier key to tell the program that you want to use an accelerator key.

Or could you show me any documentation saying otherwise? I don't see what you claim on either the [Qt docs](https://doc.qt.io/qt-6/accelerators.html) or on [MSDN](https://docs.microsoft.com/en-us/windows/apps/design/input/keyboard-accelerators)

**Comment by Daisouji** [comment]
> No, the feature is ever-present. ALT is simply the modifier key to tell the program that you're to use an accelerator key.
> 
> Or could you show me any documentation saying otherwise? I don't see what you claim on either the [Qt docs](https://doc.qt.io/qt-6/accelerators.html) or on [MSDN](https://docs.microsoft.com/en-us/windows/apps/design/input/keyboard-accelerators)

I might not be clear, 
U press ALT -> Underline Menu Labels (One Letter) -> you press ALT again -> Underline Gone. Dolphin works this way.

on QT: U press ALT -> Underline Menu Labels (One Letter) -> you press ALT again -> Underline still there.

**Comment by dio-gh** [comment]
Ah, I see what you mean, custom themes miss the fancy GUI trick that disables the underlining unless you're holding Alt, when not on the Native theme.

Makes sense, was just confused about the scope of the issue. It's a minor visual blemish then, but valid. Thanks for the heads up.

**Comment by Daisouji** [comment]
> Ah, I see what you mean, custom themes miss the fancy GUI trick that disables the underlining unless you're holding Alt, when not on the Native theme.
> 
> Makes sense, was just confused about the scope of the issue. It's a minor visual blemish then, but valid. Thanks for the heads up.
> 
> Might want to edit the issue title accordingly, it's pretty misleading as it stands. I'd suggest `Accelerator key underlines don't auto-disappear on themes other than Native` or similar.

Thanks for your input, its appreciated.

**Comment by stenzek** [comment]
Then use the native theme. This is clearly not an issue on our end.

**Comment by dio-gh** [comment]
It's not very clear at all. Is this the same kind of deal as the misbehaving dropdowns are I reported a month ago internally? As in, it'd need custom controls to fix?

**Comment by Daisouji** [comment]
> Then use the native theme. This is clearly not an issue on our end.

I'd use that if it wasn't just light.

**Comment by stenzek** [comment]
Likely an issue with Qt, or the fusion theme. You're welcome to create your own theme, but it's not something we're going to investigate as it's more than likely out of our control.

**Comment by Daisouji** [comment]
> Likely an issue with Qt, or the fusion theme. You're welcome to create your own theme, but it's not something we're going to investigate as it's more than likely out of our control.

Aight, I'll make the attempt.
