### ISSUE TITLE
[Feature Request]: A "change back to default settings" button.

### ISSUE THREAD

**Issue by kookycake** [PCSX2/pcsx2#6518]
### Description

I think there should be a "change back to default settings" button in every category in the game settings (except for game list, BIOS, Memory Cards, Network & HDD, and Folders).

### Reason

This will help anyone who falls too deep into the rabbit hole in terms of settings, as they might change too much stuff, resulting in the emulator not working for them, and they might need to go back to default settings.

### Examples

I don't know any examples (sorry).

**Comment by refractionpcsx2** [comment]
Qt now has a reset button on each page.
