### ISSUE TITLE
IOCTL_DVD_START_SESSION is used even for CD disks

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#652]
While I was investigating for #648, I noticed in my cd-rom only drive that this request failed. 
_0x335000 (Device:0x33 Function:1024 Method: 0)_

It's not like this seemed to have any particular consequence.. still I guess using a simplest, more essential call would be more elegant.

**Comment by turtleli** [comment]
Well, it can be reduced to once per disc/pause and resume/other situations that I can't currently think of instead of n times per second which it currently does (at least for my drive).

The code only requires IOCTL_DVD_START_SESSION to recognise that a DVD is in the drive and to obtain the DVD's physical format information. A DVD session doesn't have to be open to read sectors from the DVD.

**Comment by mirh** [comment]
I see, but my suggestion was more about using another control code for CD-ROMs.

**Comment by turtleli** [comment]
The call is needed for DVD detection, the alternatives are to
 * use SPTI with a READ DISC STRUCTURE command;
 * read the disc contents to determine whether it's a CD or DVD.

Both methods are probably more complicated than the current disk detection method.

**Comment by mirh** [comment]
Mhh.. Well, SPTI support is already there after all.. 
So I guess this (and the second option ofc) should just apply to the fallback path?

Your time to spend anyway, your choice d:

**Comment by turtleli** [comment]
I don't think it's worth doing. In the SPTI case. it'd only change the call that fails.

My only issue with IOCTL_DVD_START_SESSION in the plugin is that it's called unnecessarily (which I'll take care of at some point).

**Comment by turtleli** [comment]
Closing - I've minimised the use of the ioctl, and I don't think there's anything more that can really be done.

**Comment by mirh** [comment]
I wouldn't really know if that's what I was "complaining"

..anyway, too bad I haven't any cd-rom-only reader available anymore to test the calls.

**Comment by turtleli** [comment]
I quote myself:

>The call is needed for DVD detection,

And the ioctl fails on DVD drives too if the DVD isn't inserted. And on the alternatives:

> I don't think it's worth doing. In the SPTI case. it'd only change the call that fails.

So there really is nothing that can be done.

**Comment by mirh** [comment]
> the alternatives are to [...]: read the disc contents to determine whether it's a CD or DVD.

I thought this was what this issue was about. How does the ps2 behave in this case?
Or is this just one of the many mysteries of the player firmware?

**Comment by turtleli** [comment]
Honestly I have no idea what you're trying to ask. My guess is "Implement an alternative disk detection algorithm based on guesswork instead of using info that the drive can provide you with".

If a drive is able to read the disc contents, then it already knows whether a CD or DVD is in the drive since different wavelengths are used in the first place...

**Comment by mirh** [comment]
It has nothing to do with that tbh. 
I'm just saying using a DVD-specific call even for CDs is for as much as probably *not wrong* (I mean, it still works in the end) at least inelegant.

**Comment by turtleli** [comment]
It's called being practical.

An `ArtThouACDorDVD()`  ioctl/function doesn't seem to exist, so the only way I know of that can tell whether a DVD or CD is in the drive is to use a DVD or CD specific call.

While CD TOC ioctls don't work on DVDs on Windows, they do work on Linux, and the SCSI MMC specs do state that a drive should fabricate a TOC for DVDs if a CD TOC ioctl is used. Which eliminates using the CD specific call as a solution, leaving only "use a DVD-specific call".

If you still think it's inelegant, then do come up with a better solution.

**Comment by mirh** [comment]
This educate explanation says it all. 
Thanks for the comprehensive clarification.
