### ISSUE TITLE
[BUG]: Ultraman Fighting Evolution2/3/Rebirth Texture extraction and replacement problems request to fix them!

### ISSUE THREAD

**Issue by xianyi233** [PCSX2/pcsx2#6523]
### Description

请求修复这个奥特曼系列的纹理提取和替换功能！
Request to fix the texture extraction and replacement function of this Ultraman series!

### Reason

EN: Ultraman fighting evolution there are many mistakes in the texture replacement function of the three games (ufe2/ufe3/ufer) in the PS2 series. If I extract the texture of 1p seven and 2p Gaia fighting in ufe3, their character body textures are almost more than 200, which is an exaggerated number! In addition, when 2p Gaia is replaced with ACE, seven's texture will be invalid. If seven and Gaia are not in the map from which the texture is extracted, their character texture will also be invalid. Nearly 100 or 1000 textures only work in the same place and character. Please repair!
CN：奥特曼格斗进化这个PS2系列三个游戏(奥特曼格斗进化2/奥特曼格斗进化3/奥特曼格斗进化：重生)的纹理替换功能有很多错误，假如：我提取奥特曼格斗进化3的1P 赛文与2P 盖亚战斗的纹理，它们的的人物身体纹理几乎有200多张，这真是个夸张的数目！而且将2P 盖亚替换角色为艾斯时，赛文替换的纹理将失效，如果赛文与盖亚不是在提取纹理的那张地图中，它们的人物纹理同样会失效，近百张或近千张纹理只在同一地点和人物中起到作用，请修复！
提取的近百张各人物纹理修复为一张即可！

### Examples

Texture extraction and replacement problems request to fix them!
![QQ图片20220627002604](https://user-images.githubusercontent.com/107028194/175824055-7e5060c2-8e98-43ca-b8be-1e44539346f5.png)

![QQ图片20220627002604](https://user-images.githubusercontent.com/107028194/175824085-8ab4b7d5-b209-44cc-b6eb-fa82b7c1176e.png)
![QQ图片20220627003033](https://user-images.githubusercontent.com/107028194/175824263-45a8f9ba-2c16-4131-b05e-7b2c561241e3.png)
![QQ图片20220627003030](https://user-images.githubusercontent.com/107028194/175824274-64ac8fe0-8eea-4708-bca9-f665bc40e870.png)

**Comment by refractionpcsx2** [comment]
Please upgrade, texture replacement/dumping has been modified since 2949 and probably already fixes it.

**Comment by xianyi233** [comment]
> 请升级，纹理替换/转储自2949年以来（3007年）已被修改，并且可能已经修复了它。

Unfortunately, I tried from the original 2389 version to the 3008 version. It has never been changed or repaired, or no one has paid attention to it!

**Comment by refractionpcsx2** [comment]
Can you stop with the accusatory/demanding tone, it's not winning you any favours.

**Comment by xianyi233** [comment]
> 你能停止指责/苛刻的语气吗，它不会为你赢得任何好处。



> 你能停止指责/苛刻的语气吗，它不会为你赢得任何好处。

抱歉，您不必过于紧张或生气。我只是情绪过于激动（很开心您能回复我的问题）很感谢你们的付出和努力！我并没有使用责问的语气，我很尊重你们！

Sorry, you don't have to be too nervous or angry. I'm just too excited (I'm glad you can answer my question) thank you for your efforts! I didn't use the tone of censure. I respect you very much!

希望你们能够修复它，再次感谢！

I hope you can fix it. Thanks again!

**Comment by xianyi233** [comment]
2949

> Please upgrade, texture replacement/dumping has been modified since 2949 (in 3007) and probably already fixes it.

2949是之前的文件夹名称，但是里面的PCSX2已是最新的3008 QT版本哦，由于太过懒惰，所以就懒得更换文件夹名称了，哈哈

2949 is the previous folder name, but pcsx2 in it is the latest 3008 QT version. It is too lazy to change the folder name, ha ha

**Comment by MrCK1** [comment]
No response, closing
