### ISSUE TITLE
[BUG]: Right Analog don't recognizes the "Left" Action

### ISSUE THREAD

**Issue by Gianlucas94** [PCSX2/pcsx2#6539]
### Describe the Bug

The right analog don't move to the left. Tried to configure the "Left" on "Right Analog" in a keyboard button and don't worked too.

### Reproduction Steps

Try to move the right analog to the left but only the others side works.

### Expected Behavior

The game recognizes it. For example in a Third Person game, the camera goes left.

### PCSX2 Revision

v1.7.3028

### Operating System

Windows 11

**Comment by stenzek** [comment]
Likely a support/misconfiguration issue; please use the discord server for support, not the issue tracker.

**Comment by Gianlucas94** [comment]
Sorry but it happened after the latest update.
In my vision my input configurations are ok

<img width="954" alt="image" src="https://user-images.githubusercontent.com/38408614/176339607-969d81a1-797a-4dac-946e-24b48bab8db7.png">

Thanks for the answer

**Comment by BrutalEddie** [comment]
I'm experiencing the exact same issue. Going through discord support for it too, however there's a considerable group of people with the same issue after the latest update so perhaps it's not just a misconfiguration issue.

**Comment by MetisC** [comment]
Same issue here since last update.

**Comment by stenzek** [comment]
Already fixed in #6540.
