### ISSUE TITLE
[BUG]: Sonic Riders - Zero Gravity: Gravity Dive Transparency Bug

### ISSUE THREAD

**Issue by waspennator** [PCSX2/pcsx2#6547]
### Describe the Bug

When playing through the game and performing a gravity dive, the screen goes completely solid grey-ish white on all hardware renderers instead of being slightly transparent, whereas on software rendering, this issue does not exist.

### Reproduction Steps

Start up a free race and pick any stage, character, gear, etc, it doesn't matter. (I just tested it on Megalo Station with Sonic) Race through the map until the game prompts you to do a gravity dive by pressing r1 (Happens a bit after the second big jump). Press it and notice how the screen reacts.

### Expected Behavior

It should be similar to how it is on software rendering. (Not completely solid and unable to see.)

### PCSX2 Revision

v1.7.3033

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Window Screenshots

Pause menu is only there cause it's goes by kinda quick to get a proper dump.

Hardware rendering: (Tested on Vulkan, happens on all the other HW renderers)
![Sonic Riders - Zero Gravity Hardware bug](https://user-images.githubusercontent.com/78768499/176569447-f079c370-6944-455a-be02-6e1db4ffa7b6.png)

Software rendering:
![Sonic Riders - Zero Gravity Software bug](https://user-images.githubusercontent.com/78768499/176569495-7f9e8165-0dbf-4438-a984-577a7a7f9269.png)

### Logs & Dumps

[Sonic Riders - Zero Gravity - Gravity Dive Software bug.zip](https://github.com/PCSX2/pcsx2/files/9015502/Sonic.Riders.-.Zero.Gravity.-.Gravity.Dive.Software.bug.zip)
[Sonic Riders - Zero Gravity - Gravity Dive Vulkan bug.zip](https://github.com/PCSX2/pcsx2/files/9015503/Sonic.Riders.-.Zero.Gravity.-.Gravity.Dive.Vulkan.bug.zip)

**Comment by Mrlinkwii** [comment]
can this be check on latest master

**Comment by waspennator** [comment]
Retested on latest master, can no longer reproduce the issue on hardware rendering, guess something must have fixed it cause the gravity dive effect on hardware now appears transparently like it does on software.

**Comment by refractionpcsx2** [comment]
Okay cool, so is this case closed now then?

**Comment by waspennator** [comment]
Seems like it for now.

**Comment by refractionpcsx2** [comment]
Alright, thanks!
