### ISSUE TITLE
[Feature Request]: Map analog trigger values (like L2/R2) to pressure-sensitivity when L2/R2 are used as face buttons

### ISSUE THREAD

**Issue by auwsmit** [PCSX2/pcsx2#6548]
### Description

If the user has a controller with analog triggers like the Xbox or PS4 controller, and if they set-up the controls so that L2 or R2 on their controller are mapped to any face buttons like Square or Circle, then there should be an option to map the analog value of the trigger to the sensitivity of that face button.

Currently the default behavior is that L2 mapped to Square would always press Square at 100%. But if this new option was active, then L2 being lightly pressed to 10% would press the Square button at 10% button pressure.

### Reason

The recent addition of a button pressure modifier (#6527) is awesome and makes games like MGS3 way more playable because you can now interrogate guards (before they would get insta-knifed by 100% pressure on the circle button), and you can now properly lower your weapon without firing or unequipping. However there are still some small issues because of the lack of fine-control over button pressure:

In MGS3, every gun will aim when you hold Square at 7% button pressure or higher. However, some guns will fire under different circumstances. The pistols and revolver will fire _only_ if you quickly release the button while aiming. So to lower a pistol without firing, you must go from 7%+ (aiming) to 1%-6% (not aiming) for a few frames before fully depressing the Square button. Other guns will always fire automatically whenever the pressure is around 50% or higher.

This means that you can _**either**_ use 6% as your pressure modifier in order to properly aim/lower pistols without firing, but then bigger guns will always fire because 6% isn't enough to aim them at all. **Or** use 7% as your modifier in order to properly aim bigger guns without firing, but then you can't lower pistols without firing. Either way is a compromise, but the latter choice is better because you can silently stop aiming pistols by unequipping them.

If this feature were added, you could swap L2/R2 with Square/Circle, and then get fine-tuned button pressure via the triggers. You could fully operate every gun without awkwardly unequipping them. I'm not sure if other games require such precise control over button pressure, but it could help for those games as well.

### Examples

I'm thinking there would be either a checkbox at the bottom of the "Face Buttons" section of the controller settings page to enable this feature, or a check box within each submenu of the face buttons (opened by shift-clicking). I think the latter is probably better since it offers more control and is out of the way.

Here's two images roughly depicting how this could look:
![image](https://user-images.githubusercontent.com/6760531/176634780-f43ce2e0-f43e-4f22-bd2a-4169c64d8419.png)
or
![image](https://user-images.githubusercontent.com/6760531/176633399-43725639-eb33-471a-8293-9527867640f2.png)

**Comment by stenzek** [comment]
Not possible. The PAD side doesn't know anything about what triggered the event, whether it was analog or digital. All it gets is a value.

PAD-side L2/R2 is already excluded from pressure modifiers.

**Comment by auwsmit** [comment]
Oh wow, I didn't know it was already translating the values to pressure... I sure have egg on my face now. I swear I tried this in the past and it wasn't working as I expected, but no I'm totally wrong. 😅

Sorry for the mistake and thanks for all your great work on this emulator, as well as just in general

**Comment by nobleflame** [comment]
Just to add to this: I've been messing around with the QT branch and, for the MGS games at least, I also have my controller set up the same way as you, @auwsmit (i.e. triggers mapped to square and circle). I've found that the pressure sensitivity works for the MGS games as it did in the WX branch. For instance, in MGS3 you have to depress the trigger all the way to cut a guard's throat; holding it lightly will only grab then, whereby you can either interrogate or move them.

**Comment by auwsmit** [comment]
@nobleflame yeah, that's partly what I was saying in that last comment. I was mistaken in thinking that it didn't work like it did in lilypad. Apparently it's a pretty standard practice (or at least a common idea) to do that because RPCS3 does the same, which is useful for the MGS HD collection.
