### ISSUE TITLE
[Feature Request]: Multiple pressure modifiers in controller settings

### ISSUE THREAD

**Issue by auwsmit** [PCSX2/pcsx2#6549]
### Description

There should be more than one Pressure Modifier (as added in #6527) to allow more than one pressure value to be specified and used. If more than one pressure modifier is pressed at once, the last one pressed should take priority.

### Reason

(FYI Much of this reason is copied from a related feature request: #6548)

The recent addition of a button pressure modifier (#6527) is awesome and makes games like MGS3 way more playable because you can now interrogate guards (before they would get insta-knifed by 100% pressure on the circle button), and you can lower your weapon without firing or unequipping. However there are still some small issues because of the lack of fine-control over button pressure:

In MGS3, every gun will aim when you hold Square at 7% button pressure or higher. However, some guns will fire under different circumstances. The pistols and revolver will fire _only_ if you quickly release the button while aiming. So to lower a pistol without firing, you must go from 7%+ (aiming) to 1%-6% (not aiming) for a few frames before fully depressing the Square button. Other guns will always fire automatically whenever the pressure is around 50% or higher.

This means that you can _**either**_ use 6% as your pressure modifier in order to properly aim/lower pistols without firing, but then bigger guns will always fire because 6% isn't enough to aim them at all. **Or** use 7% as your modifier in order to properly aim bigger guns without firing, but then you can't lower pistols without firing. Either way is a compromise, but the latter choice is better because you can silently stop aiming pistols by unequipping them.

If this feature were added, you could use one pressure modifier for the pistols, and another for the other guns that auto-fire. This would also be a small benefit to keyboard users as well.

### Examples

I think it would look the same as it does now, but with at least two more modifiers (I can't imagine too many games need more than 3 specific pressure values).

Here's an image roughly depicting how this could look:
![image](https://user-images.githubusercontent.com/6760531/176632987-afc4ae9a-2ccb-4cbf-882c-495b89917d32.png)

**Comment by auwsmit** [comment]
related feature request: #6548

**Comment by stenzek** [comment]
No. I'm over justifying how I designed things, if you don't like it, you're welcome to change it yourself.

**Comment by auwsmit** [comment]
Very understandable. Keeping things clean and streamlined is important. Thanks for the response!

**Comment by stenzek** [comment]
PCSX2 can do macro/stick combinations internally too, we just haven't hooked up the UI for it yet.

https://github.com/PCSX2/pcsx2/blob/2a980d9fc07585587759892055b6a97daa51e260/pcsx2/PAD/Host/PAD.cpp#L554-L592
