### ISSUE TITLE
Directx 12 Compatibility

### ISSUE THREAD

**Issue by Dokman** [PCSX2/pcsx2#655]
You will make anew driver for Directx12? it will be a good improvement and give a lot of perfomance to the cpu and gpu

What you will think about it?
I know it's really difficult to use, but it can be a good achivement

**Comment by Meowmel** [comment]
You could have at least tried the search function for just 1 second.
http://forums.pcsx2.net/Thread-Windows-10-Directx-12-and-GSDX
http://forums.pcsx2.net/Thread-Directx-12-theory-and-emulation
http://forums.pcsx2.net/Thread-DirectX-12-GDC-Presentation-Coverage-link-discussion
http://forums.pcsx2.net/Thread-Waiting-for-Gabest-s-revival-DX-12-Support

**Comment by Dokman** [comment]
Sorry hahahaha
