### ISSUE TITLE
[BUG]: Windows - mouse captured by PCSX2 window, cannot be used 

### ISSUE THREAD

**Issue by sharicov** [PCSX2/pcsx2#6550]
### Describe the Bug

When emulation is running, mouse cursor disappears and mouse cannot be used until emulation had stopped (or escape button pressed).
Cannot change PCSX2 settings while playing the game (mouse is not working in settings menu and settings menu doesn't support keyboard shortcuts).

### Reproduction Steps

Run the emulation

### Expected Behavior

Mouse cursor is showing in windows mode and allows using mouse.

### PCSX2 Revision

1.7.3031

### Operating System

Windows 11

**Comment by stenzek** [comment]
Gonna preemptively close this as it's likely a support issue - because you've bound the mouse to a controller or hotkey. The mouse cursor is hidden/switched to relative mode when one of these binds are present.
