### ISSUE TITLE
[BUG]: QT interface incompatible with older version of windows 7/8.1

### ISSUE THREAD

**Issue by WolfMad** [PCSX2/pcsx2#6563]
### Describe the Bug

the version of the Qt library that PCSX2 Qt uses is incompatible with windows 8.1 when i try to run the PCSX2 qt I get the error 
this application failed to start because no qt platform plugin could be initialized i tride to run the qt-6.3.0-x64-tools.7z from https://github.com/PCSX2/pcsx2-windows-dependencies/releases and I got the same error then I tried [qt-6.2.2-x64-tools.7z] and it ran with no errors 

### Reproduction Steps

start PCSX2 Qt

### PCSX2 Revision

1.7.3043

### Operating System

Windows 8.1 (64bit)

**Comment by Mrlinkwii** [comment]
QT6 dont support these OS's , upgrade

**Comment by dio-gh** [comment]
This is not a bug, support for Windows 7/8.x has been deprecated in Qt 6.x upstream. It kept working unofficially until 6.2.2 at least, but then legitimately broke.

If you want to get the Qt build running, you can try [my fork](https://github.com/dio-gh/pcsx2), but do read the readme about the limitations and support scope.

**Comment by stenzek** [comment]
All emus moving to qt6 (and there's several now) only support win10+. Aside from Qt, pcsx2 is now using win10 only apis. Upgrade your OS. It won't receive security updates after January anyway
