### ISSUE TITLE
[BUG]: BULLY's Blending Effect Transparency

### ISSUE THREAD

**Issue by SimonBestia** [PCSX2/pcsx2#6564]
### Describe the Bug

The blending effect is no longer transparent since #5452 was merged in v1.7.2320.

In versions older than that, the issue could be reproduced by setting the Blending Accuracy to at least "Medium".
In later versions, the transparency issue can be fixed by setting Blending Accuracy to "Minimum", which will, however, cause another issue with the fade-out effect when moving to other areas. (The screen won't fade entirely to black)

### Reproduction Steps

Simply run **BULLY** in Hardware Mode. The transparency issue happens out of the box.

### Expected Behavior

Screenshot in Software Mode, where the effect is working as intended:
(Notice the left side of Jimmy's head and the school building)
![gs_20220703194651_Canis Canem Edit_SLES-53561](https://user-images.githubusercontent.com/36112411/177051373-39dad8ad-b34c-46d8-82bc-774b022bb8dc.png)

### PCSX2 Revision

v1.7.3043

### Operating System

Windows 11

### CPU

i3-8100

### GPU

GTX 1660

### GS Window Screenshots

Screenshots of what it looks like in Hardware Mode, both at native resolution and at 6x, for clarity.

Native resolution:
![gs_20220703194619_Canis Canem Edit_SLES-53561](https://user-images.githubusercontent.com/36112411/177051389-32e1342e-2efd-439b-bc81-4a5e6638280a.png)

6x:
![gs_20220703194537_Canis Canem Edit_SLES-53561](https://user-images.githubusercontent.com/36112411/177051396-ac332e37-2894-4e4e-b7d3-9f8ddf900c61.png)

**Comment by refractionpcsx2** [comment]
This was because a CRC hack was removed, you will need to rely on upscaling fixes to counter it, but bully wasn't really intended to run in a high resolution.  If you're dissatisfied with how it looks, I recommend you find somebody to patch it out.
