### ISSUE TITLE
[BUG]: Astro Boy: Robot Jet Flame Transperancy

### ISSUE THREAD

**Issue by waspennator** [PCSX2/pcsx2#6565]
### Describe the Bug

When using hardware rendering (I used the vulkan backend) and you encounter the first group of robots via cutscene, their jet boost flames are visible through their bodies, whereas they should be mostly hidden in software rendering.

### Reproduction Steps

Just start the game and go through the tutorial until you go up the elevator, move around for a few seconds and then a cutscene should initiate, the issue should be visible then.

### Expected Behavior

The robots jet flames should not be visible through the robots themselves.

### PCSX2 Revision

v1.7.3043

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

### GS Window Screenshots

Software Rendering:
![Astro Boy Robot Jet Flame Software Bug](https://user-images.githubusercontent.com/78768499/177063589-c059e678-829d-43d7-b794-eb75dd4bd9ff.png)

Hardware rendering (Tested on Vulkan):
![Astro Boy Robot Jet Flame Vulkan Bug](https://user-images.githubusercontent.com/78768499/177063602-b5afe4f8-dc86-4bb7-955e-af01d87598a5.png)

### Logs & Dumps

[Astro Boy Robot Jet Flame Software Bug.zip](https://github.com/PCSX2/pcsx2/files/9035759/Astro.Boy.Robot.Jet.Flame.Software.Bug.zip)
[Astro Boy Robot Jet Flame Vulkan Bug.zip](https://github.com/PCSX2/pcsx2/files/9035760/Astro.Boy.Robot.Jet.Flame.Vulkan.Bug.zip)

**Comment by JordanTheToaster** [comment]
Preload frame data seems to kind of make it almost work.

![image](https://user-images.githubusercontent.com/80843560/177064559-b4aaf82b-13ec-47e2-988d-dafe50c42feb.png)

**Comment by waspennator** [comment]
Testing it out on my end, it looks alright to me with PFD on, maybe cause it's specifically when the dump is loaded, compared to playing to that point.
