### ISSUE TITLE
[BUG]: File browsing freezes application in Qt release (Windows 10)

### ISSUE THREAD

**Issue by MarissaBlackwing** [PCSX2/pcsx2#6566]
### Describe the Bug

When choosing to browse or generally open the folder explorer from anywhere in the app, it freezes up and becomes unresponsive, and must be manually closed. This happens in both the AVX2 and SSE4 Qt releases, but does **not** happen in the wxWidgets AVX2 release of the same version. (I did not test the SSE4 wxWidgets release.)

This occurred consistently every time I tried the Qt release. I also tried 'run as administrator' but the results were the same. The crash txt file lists a 0xC0000005 exception.
The option in Settings>Folders to open the assigned folder directly without opening the explorer window works normally.

### Reproduction Steps

1. Run PCSX2 Nightly (windows 64bit AVX2 Qt or SSE4 Qt)
2. Click 'Add Game Directory...' or any 'Browse...' option in Settings

### PCSX2 Revision

v1.7.3043

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
If you have newoldexplorer or some other windows explorer/start menu modification application, please uninstall it and try again, this conflicts with qt.

I use openshell which is compatible with it

**Comment by MarissaBlackwing** [comment]
THAT'S what was causing it? That's really weird. I haven't had that sort of problem before with other stuff, at least not that I've noticed.

I actually use OpenShell too, but I was using it for the start menu. I used OldNewExplorer because I really hate Win10 explorer's layout, and OpenShell's 'classic explorer'...doesn't even come close to changing it back the way OldNew does. Real shame there's no up-to-date, non-conflicting equivalent to OldNew instead.

**Comment by Lv44EnderShaman** [comment]
> THAT'S what was causing it? That's really weird. I haven't had that sort of problem before with other stuff, at least not that I've noticed.
> 
> I actually use OpenShell too, but I was using it for the start menu. I used OldNewExplorer because I really hate Win10 explorer's layout, and OpenShell's 'classic explorer'...doesn't even come close to changing it back the way OldNew does. Real shame there's no up-to-date, non-conflicting equivalent to OldNew instead.

There's Valinet's ExplorerPatcher, which retrofits a lot of the older Win7/8.1/10 mechanics into Windows 10/11, but I've experienced this same bug with it as well. I'm very disappointed, if I have to say, that it conflicts with the Qt builds of the emulator, but the wxWidgets builds work servicably for my needs. Hopefully in the future, whatever conflict in the way the UI is assembled by the Qt framework is able to be diagnosed... but I'm sadly not holding my breath.
