### ISSUE TITLE
[BUG]: Glitch and Slow Speed in Tokimeki Memorial 3

### ISSUE THREAD

**Issue by PrincessFujisaki** [PCSX2/pcsx2#6567]
### Describe the Bug

Greetings! Today, i have several problems with Tokimeki Memorial 3 when i try to emulate this game on PCSX2.

1st Problem: The slow FPS at the opening and normal events.
2nd Problem: The models are rendering halfly 

I need solutions for this and an effectively configuration for this game.

### Reproduction Steps

I try to emulate the game normally and this occurs.

### Expected Behavior

The opening and cutscenes run effectively and the textures render correctly.

### PCSX2 Revision

v.1.7.3043

### Operating System

Windows 10 (64bit)

### CPU

AMD Radeon R5

### GPU

AMD Radeon R5 

### GS Window Screenshots

![Captura de pantalla (1164)](https://user-images.githubusercontent.com/108638646/177064647-7844538d-7c37-461b-b64e-05569dcd440c.png)
![Captura de pantalla (1165)](https://user-images.githubusercontent.com/108638646/177064651-4d101675-e126-4029-bdb4-3887c8baedf0.png)
![Captura de pantalla (1167)](https://user-images.githubusercontent.com/108638646/177064661-af0c5cc7-f525-445f-bd59-24e7a6266534.png)

**Comment by seta-san** [comment]
Tokimeki memorial 3 is already reported on right half screen and speed issues aren’t reported

**Comment by nfinite-recursion** [comment]
"AMD Radeon R5" is not a CPU. It's an iGPU. Looking up some info on the R5 reveals that it was paired with AMD Bristol Ridge CPUs which use the old Excavator cores. IPC is poor and clockspeeds are low compared to the newer Ryzen series, as well as Intel CPUs from Sandy Bridge and newer generations. In short, the low performance issues are normal.

I tested on my laptop with an AMD 4800H (AMD Zen2) and nVidia RTX 2060. Game runs at a solid 60fps even in software mode.

As for the graphical glitches, I initially thought it was some kind of blending issue, but I think it's related to how this game utilizes the interlaced fields to render the 3D models. With a hardware renderer in use, you can cycle through the various deinterlacing modes and the rendering of the 3D models will improve or worsen based on the mode. Some models, for instance, will briefly display correctly with no see-through sections when deinterlacing is disabled.

As for a fix, there currently seems to be no complete fix, but running the game with the software renderer gives the most accurate recreation with the 3D models being rendered properly.

**Comment by Mrlinkwii** [comment]
can someone  post a gs dump of the issue ?

**Comment by seta-san** [comment]
Here. https://github.com/PCSX2/pcsx2/issues/1341

**Comment by Mrlinkwii** [comment]
with #10093 the models should be fixed

**Comment by seta-san** [comment]
I’m also unaware of any slow speeds in this game.
