### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by terramar13** [PCSX2/pcsx2#6570]
### Description

Is possible to select texture offsets X/Y per game in game properties?

### Reason

You can select texture offsets X=0 and Y=0 in general, but in some games you can see ghosting that you could solve using texture offset just per that game.

### Examples

For example ICO is ok with texture offset X=0 Y=0 but in indiana Jones and the Staff of Kings I woukd need to change those values but just in this game or in some games but not in general.

**Comment by F0bes** [comment]
https://github.com/PCSX2/pcsx2/discussions/5947
Tracked there.
