### ISSUE TITLE
[BUG]: Game List does not update after stopping emulation (Linux-QT)

### ISSUE THREAD

**Issue by nfinite-recursion** [PCSX2/pcsx2#6579]
### Describe the Bug

Upon stopping the emulation of a game or BIOS, game list does not update when scrolling within its respective frame.

Games can still be selected, and that is reflected on the status bar at the bottom of the window. Note that the scroll bar still moves.

Tested on PopOS 22.04 using the PCSX2 v1.7.3052(QT) Nightly Build AppImage.

Also, great work getting the QT build on Linux! Looking forward to per-game settings!

### Reproduction Steps

1. Start emulation of a game (any game) or BIOS (any BIOS).
2. Stop emulation.
3. Attempt to scroll the game list.
4. Scroll bar moves, but game list will not update.
5. Clicking a game may result in selecting the incorrect game. Status bar DOES reflect which game you are selecting.

### Expected Behavior

Game list should update when scrolled.

### PCSX2 Revision

1.7.3052 (QT)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

PopOS 22.04

**Comment by stenzek** [comment]
It's just typical Wayland stupidity I think. I've had enough frustration dealing with broken compositors that I don't really care.

Rendering to separate window probably is a workaround.

**Comment by nfinite-recursion** [comment]
Ah, sorry. Forgot to mention that I'm still using X11. Ran into unrelated issues with Wayland when I last tried to force it.

I'll try rendering to a separate window and report back in a bit.
