### ISSUE TITLE
[BUG]: (SLUS 21452) Valkyrie Profile 2 - regression problems in new builds

### ISSUE THREAD

**Issue by Arthandas** [PCSX2/pcsx2#6580]
### Describe the Bug

Bug 1: Garbled text while talking to NPCs. This bug was not present in earlier versions. It happens even in native res.
<img width="1280" alt="01" src="https://user-images.githubusercontent.com/41027064/177604630-66e3b379-4e38-4db2-9be4-1f4565c15c29.png">
<img width="1280" alt="02" src="https://user-images.githubusercontent.com/41027064/177604640-0285532e-77dc-48f0-b317-d3aeac1ca140.png">

Bug 2: Much lower performance compared to previous version and the OSD shows wrong GPU usage.
Screenshot 1 - Rock solid 100% speed, OSD shows accurate GPU usage, version 1.7.2465
Screenshot 2 - Around 90% speed with the same settings, OSD shows 88% GPU usage, while in reality it's only around 45% as shown by performance tab in Windows task manager, newest version 1.7.3055
<img width="1280" alt="03" src="https://user-images.githubusercontent.com/41027064/177606596-b2440225-bbd7-4f66-92e8-0a0fa9b08f12.png">
<img width="1280" alt="04" src="https://user-images.githubusercontent.com/41027064/177606607-46264534-a976-480a-b1c9-3233f19cf3c2.png">

Bug 3: Massive ghosting. Yes, I know it's a common upscaling issue but the wiki says the issue can be fixed since 1.7.1190 by setting half-pixel offset to normal vertex, which fixes the garbled edge of the screen but has no impact on ghosting.

### Reproduction Steps

-

### PCSX2 Revision

1.7.3055

### Operating System

Windows 10 (64bit)

### CPU

i5-7500

### GPU

RTX 3060

### GS Settings

Default settings in both tested PCSX2 versions. The only thing changed for testing was native/upscaled resolution and vulkan/open gl renderers, nothing else touched.

### Emulation Settings

All default.

**Comment by Mrlinkwii** [comment]
can you post a gs dump

**Comment by Arthandas** [comment]
Here you go
[GSDump.zip](https://github.com/PCSX2/pcsx2/files/9056942/GSDump.zip)
.

**Comment by Arthandas** [comment]
Done.
[GSDump - text issue.zip](https://github.com/PCSX2/pcsx2/files/9057019/GSDump.-.text.issue.zip)

**Comment by refractionpcsx2** [comment]
Can we see your graphics settings? (The Rendering tab specifically)

**Comment by refractionpcsx2** [comment]
well this game has always been heavy, but idk why your GPU usage is so high, my 2080Ti can do 80fps on a development version of the very latest build at 8x.  Unless it's the 3000 series blending sucking hard problem, which I can't do much about that.

**Comment by Arthandas** [comment]
Except
a) the gpu usage is not actually high, task manager shows mid 40%, the OSD is wrong
b) I can run the game fine on 1.7.2465

**Comment by Arthandas** [comment]
Yes, OSD is wrong,
And as I said before, Vulkan has the same performance as OpenGL, except the GPU usage is much lower.

Whether it's Vulkan or OpenGL, PCSX2 is using at most only half of my cpu/gpu power and has the audacity to not run at 100% speed.
<img width="1280" alt="vulkan" src="https://user-images.githubusercontent.com/41027064/177627621-87a7c5d0-4780-43f8-86ac-eb650f692f57.png">
<img width="1280" alt="OpenGL" src="https://user-images.githubusercontent.com/41027064/177627628-29ff7558-9cb0-42ef-97ef-225716b9a11d.png">

**Comment by Arthandas** [comment]
Here's 1.7.2465 for comparison, the same settings and 100% speed with no problems. Clearly the newest build is a big downgrade performance wise.
<img width="1280" alt="old - opengl" src="https://user-images.githubusercontent.com/41027064/177629510-19480ca3-5390-4f2a-8f25-e99225a31744.png">
<img width="1280" alt="old - vulkan" src="https://user-images.githubusercontent.com/41027064/177629520-ff50f3c5-be67-4f7e-97d5-46ee7288bfda.png">

**Comment by refractionpcsx2** [comment]
okay there's a heck of a gulf between 2465 and 3055. Could you narrow down to where it seriously slowed down? That would be helpful.

**Comment by Arthandas** [comment]
How am I supposed to narrow it down? I was using 2465 and today I decided to update and check the new GUI.

**Comment by refractionpcsx2** [comment]
a binary search of builds (you can get them from the "releases" tab, probably easier to go back in), so download say, 1.7.2750, if that's still ok, try 2900, if not, try 2650, and keep going until you narrow it down. It'd be appreciated if you could work out where it broke

**Comment by refractionpcsx2** [comment]
Thanks

**Comment by Arthandas** [comment]
I tested 2500, 2600 and 2700. Seems like performance drops with subsequent releases. I used default settings except renderer changed to Vulkan, resolution changed to 6x and MTVU enabled - everything else is untouched.
2500 already starts to show signs of degrading performance. The speed drops to 98-99%
2600 and 2700 perform the same and the speed drops to 94-95%.
I'm assuming the trend will continue up to 3055 (where it drops to 89%).

**Comment by tellowkrinkle** [comment]
Ranges of 100 builds aren't going to help.  If you want any chance of this getting fixed, the difference has to be 1 build.

It seems you've found multiple regressions.
For the first, test a build halfway between 2465 and 2500.  How about 2482?  If that's slow, try 2473, otherwise try 2491, etc.

For the second, test 2550, then 2525 or 2575 depending on whether 2550 is slow or fast, etc.

**Comment by refractionpcsx2** [comment]
That's interesting, because 1.6 is about the same speed for me, maybe like 5fps faster, but not anything notable (both are over 100fps for me)

**Comment by Arthandas** [comment]
> Can you try DX12 in the new build? I want to rule out the 3000 series' lousy blending performance.

I already did, it runs full speed but there are no shadows.

**Comment by Arthandas** [comment]
Maybe "full speed" was too optimistic. I disabled the framelimiter and it just runs around 60. It goes up to 64 in native res...
For comparison, 1.6.0 ran at around 65 with the same settings in OpenGL. What's the earliest build with Vulkan?

**Comment by nshchetinin** [comment]
I am not sure if this helps any, but I have just stumbled upon this issue and tested the game myself with no limiter at a native resolution on 1.6 (OpenGL and MTVU enabled, everything else is at default) and 1.7.3057 (Vulkan with everything at default, which appears to include MTVU enabled out of the box).

I got 110 FPS on 1.6 and 120 FPS on 1.7.3057 at the same specific place OP showed on the screenshots, so I do not observe any performance improvement by going back reported by two people here and, in fact, the latest version offers a consistent 9% speed improvement for me.

That's on i9-11900K and RTX 3090 running Windows 10.

**Comment by stenzek** [comment]
> Yes, OSD is wrong

Tbh, I doubt this. Task manager completely misreads my NVIDIA GPUs in some games (when they're maxed out, it says 8-10%).

It's also dependent on the clock speed. The percentage is just `gpu_time / wall_time`. The average gpu timestamp is the one which matters, and there's not really any way that can go wrong in vulkan.

**Comment by Arthandas** [comment]
> > Yes, OSD is wrong
> Tbh, I doubt this. Task manager completely misreads my NVIDIA GPUs in some games (when they're maxed out, it says 8-10%).
Ok, let's say it's right. How the hell am I getting 80% gpu usage in OpenGL at native resolution?
<img width="1280" alt="Untitled" src="https://user-images.githubusercontent.com/41027064/177735629-867ec0a4-4d60-4432-b276-1736c81c4770.png">

Vulkan shows around 45% usage in x6 resolution which I guess **could** be correct. Still doesn't explain why I'm getting 90% speed if the game is using half my gpu at most.

**Comment by stenzek** [comment]
> Ok, let's say it's right. How the hell am I getting 80% gpu usage in OpenGL at native resolution?
> Vulkan shows around 45% usage in x6 resolution which I guess could be correct. 

This is correct, and makes perfect sense. GL uses texture barriers, Vulkan uses framebuffer-local/pixel barriers. Therefore when using software blending, only one polygon can be shaded at once using GL, but in Vulkan, multiple non-overlapping polygons can be shaded. NVIDIA schedules this in hardware, AMD doesn't (which is why it's so slow there).

> Still doesn't explain why I'm getting 90% speed if the game is using half my gpu at most.

Could be something else. Frame time spikes if you're using vsync will drop frames, audio output can stall emulation if misconfigured, etc.

**Comment by Arthandas** [comment]
Ok, check this out, I changed my power management mode in NVIDIA control panel from "normal" to "prefer maximum performance" and:
* in 1.7.2465 (Vulkan, x6 resolution, MTVU) I went from 62 to 73 fps
* in 1.7.3055 (Vulkan, x6 resolution, MTVU) I went from 53 to 61 fps
This proves PCSX2 is underutilizing my gpu, still doesn't explain why there's such a performance gap between 2465 and 3055.

The OSD in 1.7.3055 showed 45% gpu usage with "normal" power setting, and around 31% in "prefer maximum performance". So I gain 10fps while lowering gpu usage by 15%? OSD can't be right.

**Comment by stenzek** [comment]
> The OSD in 1.7.3055 showed 45% gpu usage with "normal" power setting, and around 31% in "prefer maximum performance". So I gain 10fps while lowering gpu usage by 15%? OSD can't be right.

You're incorrect, again. Like I said above, it is dependent on the clock speed. The utilization is just "how much time in the last 16ms period the GPU was busy for". When running at a lower clock speed, it takes a shorter amount of time to complete the same amount of work. Therefore, less time in the 16ms period, therefore, lower "GPU usage". That's why it's not a great metric when DVFS is in effect.

> The OSD in 1.7.3055 showed 45% gpu usage with "normal" power setting, and around 31% in "prefer maximum performance".

The performance difference is typical for readback scenarios. Because the readback forces all outstanding work to complete, the GPU might sit idle for up to 16ms, in which time the driver might decide to clock it down (16ms is a long time). By the time the next frame gets kicked to the GPU, the clocks are too low to complete it by the next vsync deadline, so it drops a frame.
