### ISSUE TITLE
[BUG]: Jak 2 Japanese subtitles occasionally wrong texture mapping

### ISSUE THREAD

**Issue by ManDude** [PCSX2/pcsx2#6581]
### Describe the Bug

Specific lines of the Japanese language subtitles in Jak 2 (Japanese is available in all versions of the game) have this tilted looks with the wrong textures on the edges. I haven't figured out exactly what determines the direction of the tilting, though I'm not sure if it matters.

I have tried software renderer, hw renderers, with hacks, without hacks, with speedhacks, without speedhacks, various rounding modes, interpreter mode, gs hacks, gs settings, etc. Nothing seems to fix this.

### Reproduction Steps

The lines with this issue are always the same ones, so it's very easy to reproduce. Just set the subtitle language to Japanese and watch a cutscene with a bad line.

### Expected Behavior

These lines should not be tilted at all, there's no italics in the game. Here's a PS2 playthrough on nicovideo of the whole game, showing this. https://www.nicovideo.jp/watch/sm10232389?ref=search_key_video&playlist=eyJ0eXBlIjoic2VhcmNoIiwiY29udGV4dCI6eyJrZXl3b3JkIjoiXHUzMGI4XHUzMGUzXHUzMGMzXHUzMGFmXHVmZjM4XHUzMGMwXHUzMGFmXHUzMGI5XHUzMGJmXHUzMGZjMiIsInNvcnRLZXkiOiJob3QiLCJzb3J0T3JkZXIiOiJub25lIiwicGFnZSI6MSwicGFnZVNpemUiOjMyfX0&ss_pos=15&ss_id=f8f29a86-61a6-4918-8f80-9325391cb552

### PCSX2 Revision

v1.7.3057, and also some really old April version too

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3500U

### GPU

Radeon Vega 8 Graphics

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/7569514/177690202-cbf4fb99-2138-4de2-98c5-534242ef31db.png)

### Logs & Dumps

GS dump: [gs_20220707052615_Jak II - Renegade_SCES-51608.zip](https://github.com/PCSX2/pcsx2/files/9060398/gs_20220707052615_Jak.II.-.Renegade_SCES-51608.zip)

**Comment by ManDude** [comment]
Adding to this, it appears the color is wrong too. On actual PS2 footage, the text is quite flat, but on emulator it appears shaded, darker at the bottom. This happens on all lines.

![image](https://user-images.githubusercontent.com/7569514/177898330-5461757f-d974-4dfd-bc2d-9f1c9615ecef.png)

**Comment by FMecha** [comment]
I noticed it's the same tilting as in #3228 (GT3 demos).
