### ISSUE TITLE
[BUG]: (SLUS 21452) Valkyrie Profile 2 - red tint in the forest

### ISSUE THREAD

**Issue by Arthandas** [PCSX2/pcsx2#6583]
### Describe the Bug

The whole area is covered in red tint, it should be green.

<img width="1280" alt="01" src="https://user-images.githubusercontent.com/41027064/177800117-f45e9b61-883f-4600-a065-f130b574c61a.png">

### Reproduction Steps

Just start the game, exit the town and enter the forest.

### PCSX2 Revision

1.7.3058

### Operating System

Windows 10 (64bit)

### CPU

i5-7500

### GPU

RTX 3060

### GS Settings

Default settings.

### Emulation Settings

Default settings.

### Logs & Dumps

[VP2 - Red Tint.zip](https://github.com/PCSX2/pcsx2/files/9064687/VP2.-.Red.Tint.zip)

**Comment by refractionpcsx2** [comment]
Go play it on a PS2. It's supposed to look like that.
