### ISSUE TITLE
[Feature Request]:  ZSO Build request

### ISSUE THREAD

**Issue by orcutt989** [PCSX2/pcsx2#6585]
### Description

Per this comment I was hoping to request a build of PCSX2 for Windows 10 with ZSO support
https://www.psx-place.com/threads/testers-needed-open-ps2-loader-with-zso-support-compressed-iso.37223/page-7#post-334057

### Reason

See above

### Examples

See above

**Comment by refractionpcsx2** [comment]
There isn't such a thing, and this is a duplicate request of #6050

**Comment by refractionpcsx2** [comment]
because we closed it for a reason.
