### ISSUE TITLE
Weird ghosting in Kingdom Hearts 2

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#6586]
Ghosting is appearing around objects, like a shadow. None of the hardware fixes seem to solve the issue. Happens with HW rendering even at native res.
![Screenshot (31)](https://user-images.githubusercontent.com/12180630/177874053-054d1f3d-e220-42d9-8220-eae0843193eb.png)
![Screenshot (32)](https://user-images.githubusercontent.com/12180630/177874054-02ed55bc-a0b7-4106-87df-327593051b07.png)
![Screenshot (33)](https://user-images.githubusercontent.com/12180630/177874057-3c859e48-622d-445c-968a-fe543ee654a6.png)
![Screenshot (36)](https://user-images.githubusercontent.com/12180630/177874061-f68568df-d300-47b6-8361-f3a848155694.png)
 

### Reproduction Steps

Just run the game. 

### Expected Behavior

No ghosting around objects. 

### PCSX2 Revision

v.1.7.3058

### Operating System

Windows 10 (64bit)

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

default

**Comment by Mrlinkwii** [comment]
can you post a gs dump?

**Comment by BParks21** [comment]
[KH 2.zip](https://github.com/PCSX2/pcsx2/files/9067525/KH.2.zip)

**Comment by MarioSonic2987** [comment]
Enable Auto Flush in Hacks tab to fix ghosting.

**Comment by refractionpcsx2** [comment]
KH 2 needs autoflush? 👀

**Comment by refractionpcsx2** [comment]
I guess something changed. I mean it's not a problem if it does need that, I'm just surprised lol.

Is software mode the same? if you disable autoflush for software? (you need to switch the config to software mode in Qt to see it)

**Comment by BParks21** [comment]
Swear I tested autoflush. Guess I'll have to test again later today.

**Comment by refractionpcsx2** [comment]
Thanks :) I mean if that's the case, we can add it to the gamedb. I doubt Autoflush is gonna be heavy in Kingdom Hearts 2 (compared to Jak 2/3 lol)

**Comment by refractionpcsx2** [comment]
Okay so this was introduced by 1.7.2937 (PR #6338 ), I guess the reason for that is before it just happened to be autoflushing by chance due to over-flushing the GS state, so now it's needed :P
