### ISSUE TITLE
Bad interaction between GSdx-OGL and Optimus/Amd equivalent

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#659]
Current code misses a way to select the GPU correctly. The only solution so far is to select the GPU in the driver.

Details on this thread http://forums.pcsx2.net/Thread-Cannot-Play-PCSX2-with-OpenGL

On Windows, there are 2 extensions so support it
[quote]
https://www.opengl.org/registry/specs/NV/gpu_affinity.txt
https://www.opengl.org/registry/specs/AMD/wgl_gpu_association.txt
[/quote]

However I only found the Linux equivalent for AMD not Nvidia. IIRC, there are 3rdparty SW to disable optimus (or work-around it).
[quote]
https://www.opengl.org/registry/specs/AMD/glx_gpu_association.txt
[/quote]

**Comment by gendouhydeist** [comment]
Weird never have this problem I'm currently using eGPU GTX 970 on my laptop with optimus enabled and didn't have any problems with it.

I'm also using OpenGL renderer and it's awesome than DX11 renderer.

Of course you have to force to use eGPU through NVIDIA Control Panel.
[img]http://i.imgur.com/A0JfxBB.png[/img]

**Comment by gregory38** [comment]
```
Of course you have to force to use eGPU through NVIDIA Control Panel.
```
Of course that the issue, you need to select manually the Nvidia GPU

**Comment by turtleli** [comment]
I did some investigating on the NVIDIA side of things.

Windows - WGL_NV_gpu_affinity doesn't seem to exist on consumer cards (I checked my 970GTX). It's probably for workstation/professional cards. So the only option is probably to set the NVIDIA card as the default device, or set the device in the NVIDIA control panel for PCSX2.

Linux - bumblebee is what is used for optimus laptops,. When someone wants to use the NVIDIA card, they launch the application using optirun or primusrun. So it might be okay on Linux, but those who have an optimus laptop will know better than I do.

No idea on the AMD side of things, and I'm very unlikely to investigate it.

**Comment by charliebruce** [comment]
This issue can be resolved on Windows, for versions 302 and above of the nVidia drivers. 
I have tested the following fix on my machine, with Intel HD 4600/nVidia 765M - I can use GSdx with OpenGL without any changes in the nVidia control panel, and without using the "Run with dedicated graphics processor" option. 

Feel free to pull if it helps: 
https://github.com/charliebruce/pcsx2/commit/7020a695001635751deddb7062898bd537493974

It might have an impact on battery life for laptops with Optimus (when PCSX2 is running, the higher-power nVidia graphics card will always be powered on). I doubt that many people will be using the low-power Intel graphics chip for emulating games though, so I don't think this is an issue.

**Comment by gregory38** [comment]
@charliebruce 
Good jobs. Could you do a pull request, this way win users can test it.

**Comment by charliebruce** [comment]
I wasn't sure where to best locate that Optimus.cpp file, the directory structure is unclear to me. Where should it be located?

**Comment by gregory38** [comment]
Put the code in this file instead:
GSdx/stdafx.cpp

**Comment by charliebruce** [comment]
I tried that, but it needs to be in the core executable, not in the DLL (the nVidia driver checks for that export when the executable is first loaded, not when the DLL is loaded. If the lowest bit of that export is set, it will force the use of the high-performance graphics chip).

**Comment by charliebruce** [comment]
Just tidied a couple of things up, and created a pull request for people to inspect. As mentioned before, it has to add the export to the main executable not the plugin.
