### ISSUE TITLE
Resident Evil Outbreak File 2 (Japenese version) Freeze glitch while playing online

### ISSUE THREAD

**Issue by JakeWade** [PCSX2/pcsx2#66]
1) Did the game ever work correctly (i.e. not have this problem) on the
Official PCSX2 build or an earlier version of PCSX2 playground?
(If so, please specify the latest pcsx2-playground or Official revision
that last worked.)

For me and others it had always freeze glitches

2) What steps will reproduce the problem?

1.Totally random freezings

3) What exactly happens when you experience this issue (listing any console
errors or screen output you receive)?

Sometimes the game freezes while playing online.I cant do anything but i still can hear the sound

4) What version of PCSX2 are you using? On what operating system? Plugins?

PCSX2 1.2.1

Windows XP

Plugins: http://kepfeltoltes.hu/140215/4_www.kepfeltoltes.hu_.jpg

5) Please provide any additional information below.

All users get these freeze glitches while playing online.It happens random times.I get freeze glitches usually 3 times per day.Sometimes i can finish 3 scenarios online without getting freeze glitch,but sometimes i get freezed more times on the same scenario

It's important that emulator users had these freeze glitches on the official servers too not just in the fanmade server ( http://obsrv.org/ )

6) Attachments.  *IMPORTANT!*  We have a limited storage quota on
GoogleCode, so please keep attachments to UNDER 200k!  Do not upload
blockdumps!  Do not upload MP3 dumps or screenshots in BMP format.  Try to
use 3rd party image hosts for screenshots when possible.

Emulog when the freeze glitch happens: http://www.mediafire.com/view/6n5q4ynxn27bcc0/emuLog.txt

Packetlog when the freeze glitch happens: http://www.mediafire.com/view/tdb6435o8bzbtof/packet.log

**Comment by TheLastRar** [comment]
can you test the dev9 plug-in attached here http://forum.coldbird.net/viewtopic.php?f=31&t=1851

It contains the changes mentioned here https://github.com/PCSX2/pcsx2/issues/439

**Comment by JakeWade** [comment]
Sorry for the late reply but i did not play OB for a while but now that i play it again i will test this plugin.Thank you

**Comment by bositman** [comment]
This is most probably fixed by Thelastrar's commits, closing
