### ISSUE TITLE
[BUG]: Namco Museum & Namco Museum 50th Anniversary serial number collision?

### ISSUE THREAD

**Issue by InDizgize** [PCSX2/pcsx2#6603]
### Describe the Bug

Namco Museum and Namco Museum 50th Anniversary share the same serial number and because of that the 50th Anniversary version gets misnamed.   

### Reproduction Steps

Have both games in your library

### PCSX2 Revision

1.7.3065

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
This isn't our fault, the game is *actually* using the same serial for both.
