### ISSUE TITLE
[BUG]: Front Mission 4 broken shadows using any hardware renderer 

### ISSUE THREAD

**Issue by ajs91** [PCSX2/pcsx2#6604]
### Describe the Bug

When using any of the hardware rendering options the shadows in Front Mission 4 are opaque and much larger than they should be. Happens on both my Nvidia and AMD graphics. 
![pcsx2-qtx64-avx2_3Q5cJev8NZ](https://user-images.githubusercontent.com/47402539/178156397-5cb33a08-c0a1-499f-a58c-eb759e457105.png)
 

### Reproduction Steps

Can be found in the opening in engine cutscene but is present throughout the entire game. 

### Expected Behavior

Shadows should be much smaller with a "softer" and transparent appearance like they are when using the software renderer. 
![pcsx2-qtx64-avx2_nodWG0RjCt](https://user-images.githubusercontent.com/47402539/178156515-448fc0fc-4067-4454-b50d-98b064bf9ae7.png)
 

### PCSX2 Revision

1.7.3066

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5900HX

### GPU

3060 Mobile

**Comment by lightningterror** [comment]
Can you post a gsdump?

**Comment by refractionpcsx2** [comment]
[Front_Mission_4__NTSC-U__SLUS-20888-shadow.gs.zip](https://github.com/PCSX2/pcsx2/files/9102584/Front_Mission_4__NTSC-U__SLUS-20888-shadow.gs.zip)

**Comment by lightningterror** [comment]
Shadows look good to me?
![image](https://user-images.githubusercontent.com/18107717/178768728-a713e4c5-b4fd-4499-aee7-5bb690cade0b.png)

**Comment by refractionpcsx2** [comment]
where did you get that dump? doesn't look that good to me 
![image](https://user-images.githubusercontent.com/6278726/178769641-f4ef63c2-aaec-4992-a6e9-7ae309d74a69.png)

**Comment by lightningterror** [comment]
I see, I was playing back the wrong dump, named similar.

**Comment by Glumduk** [comment]
Changing CPU Sprite Render Size to 4 + Blending fixes the shadows. I've played through the tutorial stage & it doesn't look like anything weird is happening so far. Might need some fine tuning on other recommended default settings - I think it was only using Preload Frame Data before, so I haven't messed with it. 
![Capture](https://user-images.githubusercontent.com/114959650/233268214-ab98e0eb-5a12-4f95-bcf8-a1a50df2dc8a.JPG)
