### ISSUE TITLE
[BUG]: Lego Racers 2 lens flare visible through terrain in Hardware

### ISSUE THREAD

**Issue by JimScript** [PCSX2/pcsx2#6605]
### Describe the Bug

In Hardware Mode, the lens flare will be visible though the terrain, strangely though switching between hardware mode and software mode doesn't change it in a GS Dump.

### Reproduction Steps

Load up Lego Racers 2 in software mode and start adventure mode. Then switch to hardware mode with skipdraw range of 0-70(it doesn't affect the lens flare, you can see it through the glitchy post-process). Then look at the sun through the terrain, switching back and forth between software and hardware, and see how the lens flare disappears with the software mode.

### Expected Behavior

What is seen in software mode.

### PCSX2 Revision

v1.7.3065

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 2070 Super

### GS Settings

8x rendering and skipdraw range of 0-70, neither of which affect the lens flare.

### Emulation Settings

Cycle rate: 300%(for higher fps)
MTVU: Yes

### GS Window Screenshots

Hardware:
![gs_20220710100117_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/178154563-b2fb94fe-8c31-441e-9fe2-d0ac29ba7b90.png)
Software:
![gs_20220710100711_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/178154782-bc0a02aa-a380-42b7-b701-12cc02638b49.png)

### Logs & Dumps

Hardware:
[gs_20220710095656_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/9079493/gs_20220710095656_LEGO.Racers.2_SLUS-20042.zip)
Software:
[gs_20220710100711_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/9079512/gs_20220710100711_LEGO.Racers.2_SLUS-20042.zip)

**Comment by Mrlinkwii** [comment]
using the SW gsdump , this seems to be fixed  in HW as of v1.7.4141

![image](https://user-images.githubusercontent.com/17685135/221376138-3558fd90-4d09-4857-9d4d-c97ccad315f8.png)

**Comment by JimScript** [comment]
It's still leaks occasionally when you move around, but it mostly works. I don't know if the game is just like that or what, so I don't know if it can be closed just yet.

**Comment by JimScript** [comment]
Nope, I just put on software mode and it's the same, so software parity is enough for me.
