### ISSUE TITLE
[Feature Request]: Flush VRAM of unused data if a memory leak occurs

### ISSUE THREAD

**Issue by Hedwig7s** [PCSX2/pcsx2#6607]
### Description

Basically flush the VRAM of any unused data if a memory leak is to occur. Nothing else really

### Reason

It fixes alot of issues with things like menus and stuff taking up alot of VRAM unnecessarily and causing memory leaks

### Examples

Example:

In GT4 if I load into Laguna Seca in Arcade mode with Native x3 with any car, a memory leak occurs when it loads into the game (I have 4gb VRAM). However, when I force the rendering engine to reload (I do it by changing to software and back to vulkan), the game has no issues. I also see this when loading from a save state

**Comment by refractionpcsx2** [comment]
I think you're misunderstanding what goes on behind the scenes.  The problem is the game uploads a LOT of textures which get set to a minimum size, but the whole reason it's as fast as it is, is because it caches what it's converted in to upscaled textures/something the GPU can use.  Having to constantly convert it from GS memory is super slow.

The only real solution for now is for you to lower your resolution, maybe turn Texture Preloading to "None", try GPU Palette conversion, see if that helps.

**Comment by Hedwig7s** [comment]
> I think you're misunderstanding what goes on behind the scenes. The problem is the game uploads a LOT of textures which get set to a minimum size, but the whole reason it's as fast as it is, is because it caches what it's converted in to upscaled textures/something the GPU can use. Having to constantly convert it from GS memory is super slow.
> 
> The only real solution for now is for you to lower your resolution, maybe turn Texture Preloading to "None", try GPU Palette conversion, see if that helps.

I specifically said in the case of a memory leak
A lag spike and slower loading time is preferable to a crash

**Comment by Hedwig7s** [comment]
Could also be toggleable

**Comment by refractionpcsx2** [comment]
There's no "leak" that I'm aware of. There's a spike in GT4, is that what you're referring to?

**Comment by Hedwig7s** [comment]
> > > There's no "leak" that I'm aware of. There's a spike in GT4, is that what you're referring to? Usually brought about by the transitions.
> > 
> > 
> > Spike? [It memory leaked for me and never recovered](https://youtu.be/DSI1NM5MwSg)
> > Anyway videos of using save states and changing rendering engine [Save State](https://youtu.be/GLFGALOu4aY) [Changing rendering engine](https://youtu.be/xE8GeEm_NBo)
> > Only issue was the pause menu taking a while to load
> 
> Yes that is not a leak that is the spike that you can fix by lowering your upscale and as you get into a race switching to and from software.

That shouldn't be necessary though
Surely it can do it automatically
