### ISSUE TITLE
[BUG]: Final Fantasy X-2 (PAL) - Bad, interlaced looking appearance with Screen Offsets turned on

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#6608]
### Describe the Bug

This game requires screen offsets to be enabled in order for the gameplay graphics to display at the correct aspect ratio, and for the FMV sequences to display at the correct position. However, with offsets enabled most in-game screens look like they've been badly deinterlaced. The problem appears independent of the interlacing settings though; they do nothing.

There is one PCSX2 setting other than Screen Offsets that has an effect on this issue: Anti-Blur. With Anti-Blur turned off the issues extends to affecting the title screen and most menus rather than just in-game 3D.

There is an in-game setting that mitigates the problem, but you can't set this before starting a game: in the settings panel adjust the screen position up or down one line.

### Reproduction Steps

Either start the game and let the intro play until the first battle, or start the game with Anti-Blur turned off and look at the title screen.

### Expected Behavior

The graphics should display clearly as they do on actual hardware.

### PCSX2 Revision

v1.7.3066

### Operating System

Windows 11

### CPU

Ryzen 3700X

### GPU

RTX 3070

### GS Settings

Software mode. Auto Flush, Mip-Mapping, and Edge Anti-Aliasing on. They don't appear to have any effect on this issue. 

### Emulation Settings

MTVU on. Doesn't appear to change anything if turned off.

### GS Window Screenshots

![gs_20220711130429_Final Fantasy X-2 _PAL-E__SLES-51815](https://user-images.githubusercontent.com/4227434/178268817-044e8083-6aa3-41d4-bbfa-93cf4ebc667d.png)

### Logs & Dumps

[Final Fantasy X2 Offset.zip](https://github.com/PCSX2/pcsx2/files/9084152/Final.Fantasy.X2.Offset.zip)

**Comment by refractionpcsx2** [comment]
Linked PR should fix it up

**Comment by coornio** [comment]
I should mention that Screen Offsets doesn't seem to "fix" the aspect ratio of the gameplay portion, it squishes it to an odd 16:9-like ratio, and also offsets it slightly to the left, cutting off part of the image.

**Comment by Silanda** [comment]
Didn't check the left offset, but the 16:9 squeeze is how it looks on actual hardware.

**Comment by refractionpcsx2** [comment]
The screen offsets just displays it how it tells it to display it.  The picture is 415 pixels high (the resolution is 512 since it's PAL) so the picture will be squished.  Turning off screen offsets stretches the picture to fit the window.
