### ISSUE TITLE
[BUG]: (SLUS-21621) Shin Megami Tensei - Persona 3 FES: lines displayed on FMVs

### ISSUE THREAD

**Issue by KawaiiDinosaur** [PCSX2/pcsx2#6615]
### Describe the Bug

Using any hardware renderer, lines appears on the bottom and right borders of FMV cutscenes. The issue isn't present using the software renderer.
![gs_20220712150207_Shin Megami Tensei - Persona 3 FES_SLUS-21621](https://user-images.githubusercontent.com/36821201/178568395-cc93e33a-2811-4c81-a366-ab6c9eb33f76.png)

### Reproduction Steps

Boot the game

### Expected Behavior

![gs_20220712150557_Shin Megami Tensei - Persona 3 FES_SLUS-21621](https://user-images.githubusercontent.com/36821201/178568455-2eb9eb59-b747-4bf1-9810-06605e80bdc6.png)

### PCSX2 Revision

v1.7.3070

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 7 3700X

### GPU

RX 5700 XT

### Logs & Dumps

[gs_20220712153519_Shin Megami Tensei - Persona 3 FES_SLUS-21621.zip](https://github.com/PCSX2/pcsx2/files/9095921/gs_20220712153519_Shin.Megami.Tensei.-.Persona.3.FES_SLUS-21621.zip)

[gs_20220712153525_Shin Megami Tensei - Persona 3 FES_SLUS-21621.zip](https://github.com/PCSX2/pcsx2/files/9095924/gs_20220712153525_Shin.Megami.Tensei.-.Persona.3.FES_SLUS-21621.zip)

**Comment by refractionpcsx2** [comment]
Can you run it in "native" resolution, I suspect this is an upscaling problem ,and the only way around it is to zoom 101

**Comment by KawaiiDinosaur** [comment]
Sorry, I forgot to specify. I'm running the game on native res. Although, changing the IR didn't affect the lines.

**Comment by refractionpcsx2** [comment]
okay last thing to check, does this happen in the WX version of pcsx2?

**Comment by SlimDread** [comment]
Can confirm on Qt Windows 10 OpenGL on an Intel GPU. The lines strangely only appear on the Persona 3 intro and not the FES one.

**Comment by SlimDread** [comment]
> okay last thing to check, does this happen in the WX version of pcsx2?

No.

**Comment by refractionpcsx2** [comment]
okay cool, so this is the common issue with Qt then which some people seem to be getting, I'll mark it as such, thanks.

**Comment by nfinite-recursion** [comment]
Not a bug.

The problem is with P3's FMVs themselves. They're interlaced videos but hard encoded as progressive. This results in a lot of strange artifacts.

Most likely the guy encoding the videos at Atlus had no idea what he (she?) was doing.

![Screenshot (108)](https://user-images.githubusercontent.com/97854528/179424154-e4d20756-3e56-4269-a92e-ce81839789af.png)

**Comment by KawaiiDinosaur** [comment]
@nfinite-recursion the issue is the pixelated line under the fmv, not the interlacing artifacts within the video.

**Comment by nfinite-recursion** [comment]
Ah, I see. I thought this was just the same old issue that was raised multiple times on NGEmu back in its heyday.

**Comment by Mrlinkwii** [comment]
is this still an issue on nightly ?

**Comment by KawaiiDinosaur** [comment]
It's still the same.
The only fixes I found are switching to software renderer during FMVs, using the widescreen patches that stretch the FMVs (I don't think it looks good) or cropping the image.

**Comment by lightningterror** [comment]
Seems fine now on native res.
![image](https://github.com/PCSX2/pcsx2/assets/18107717/f2623df8-3e09-4f63-bf11-c461c2093629)
