### ISSUE TITLE
[BUG]: Dualshock 1 PS1 controller no force feedback vibration (Regression from 1.6.0) 

### ISSUE THREAD

**Issue by mogarithm** [PCSX2/pcsx2#6617]
### Describe the Bug

Original PS1 Dualshock controller, connected via "blue triangle" USB adapter ( using drivers found at https://github.com/aitte2/dualshock_driver ), to Windows 10 64-bit. 

With PCSX2 1.6.0 (current "stable"): after controller configuration, controller is fully functional in-game and vibrates at the appropriate times. Can test in Final Fantasy XII: allow party leader to be hit by enemies. Controller rumbles OK. 

With latest "nightly build" (pcsx2-v1.7.3072-windows-64bit-SSE4-Qt): after controller configuration, controller is fully functional in-game but will NOT rumble. 

(Note: this controller+adapter works fine, including rumble, in Dolphin and Project64 as well as stable PCSX2. It does NOT rumble in Duckstation).

### Reproduction Steps

Launch Final Fantasy XII.
In in-game settings, switch on controller vibration.
Enter a battle, allow the party leader to be hit by an enemy.

### Expected Behavior

Controller should rumble.

### PCSX2 Revision

1.7.3072

### Operating System

Windows 10 (64bit)

**Comment by lightningterror** [comment]
@mogarithm Is this still an issue?

**Comment by mogarithm** [comment]
Yes still an issue with PCSX2 Nightly - v1.7.5095

**Comment by stenzek** [comment]
Not really our bug. It's likely not supported by SDL's game controller/haptic system, which we rely on.

DInput is an absolute nightmare to work with, and the new DInput backend doesn't support force feedback for that reason. PRs are welcome to add it, but it's a deprecated API, so there's little appeal, as SDL covers all our requirements.
