### ISSUE TITLE
[BUG]: Growlanser 5 & 6 - Upscaling causes misaligned character pictures and textboxes

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#6619]
### Describe the Bug

Upscaling the games Growlanser 5 and 6 causes the character pictures and textboxes to have lines. None of the HW Hacks seem to fix the issue. The bug is present in all renderers. As far as i can tell upscaling increases the distance of the textures by 1 pixel.

### Reproduction Steps

Start either Growlanser 5 or 6 and enable upscaling.

### Expected Behavior

Upscaling should not affect the character pictures and the textboxes.

### PCSX2 Revision

pcsx2-v1.7.3072-windows-64bit-AVX2-wxWidgets

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 2700X

### GPU

RTX 2070

### GS Settings

![1](https://user-images.githubusercontent.com/37260321/178821783-f89cb602-f3ee-40d6-90ce-4b99dd50a470.PNG)
![2](https://user-images.githubusercontent.com/37260321/178821789-8fe30278-cc19-440d-b17e-2fe6e65e6d3b.PNG)

### GS Window Screenshots

![11](https://user-images.githubusercontent.com/37260321/178821179-fa7e2716-4c94-494e-90ef-9a9b8f83c213.png)

### Logs & Dumps

[gs_20220713215708_Growlanser VI _NTSC-J__SLPM-66716.zip](https://github.com/PCSX2/pcsx2/files/9105530/gs_20220713215708_Growlanser.VI._NTSC-J__SLPM-66716.zip)

**Comment by coornio** [comment]
Confirmed that nothing can fix this, not even the Pre-Round Sprite PR has an effect. Texture Offsets exacerbate the issue instead.

**Comment by refractionpcsx2** [comment]
The preround PR doesn't address upscaling bugs, only ones which appear in native/software.

**Comment by lightningterror** [comment]
It's an upscaling issues nothing can be done atm, only option is to use native res for now.
