### ISSUE TITLE
[BUG]: [Linux] Can't show ${gsdx} properly in the window title

### ISSUE THREAD

**Issue by gary-ts** [PCSX2/pcsx2#6620]
### Describe the Bug

pcsx2-1.7.3073 can't show ${gsdx} properly in the window title.
![pcsx2_window](https://user-images.githubusercontent.com/7479902/178831868-e26f8493-6a98-4880-9a46-b65fc57bd16d.png)

pcsx2-1.7.2678 is OK.
![pcsx2_window_old](https://user-images.githubusercontent.com/7479902/178832063-cb3b56d9-512e-43f9-aa91-d9f2c3a57530.png)

Thank you for developing PCSX2!

### Reproduction Steps

cmake -S pcsx2 -B build -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
  -DCUBEB_API=ON \
  -DDISABLE_ADVANCE_SIMD=OFF \
  -DDISABLE_BUILD_DATE=ON \
  -DDISABLE_PCSX2_WRAPPER=ON \
  -DDISABLE_SETCAP=ON \
  -DENABLE_TESTS=OFF \
  -DPACKAGE_MODE=ON \
  -DUSE_VTUNE=OFF \
  -DUSE_OPENGL=ON \
  -DUSE_VULKAN=ON \
  -DXDG_STD=ON \
  -Wno-dev

cmake --build build

sudo ninja -C build install

pcsx2

### PCSX2 Revision

v1.7.3073

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

**Comment by lightningterror** [comment]
Delete your old inis.

**Comment by gary-ts** [comment]
Thanks!
