### ISSUE TITLE
[BUG]: Software rendering issue on GTA: San Andreas

### ISSUE THREAD

**Issue by BeyondThe5D** [PCSX2/pcsx2#6621]
### Describe the Bug

There's a bug with software rendering where the right of the screen is kind of corrupted and has weird glitchy lines appearing, I can't find anybody who has reported this bug, I would assume people have though since it's quite obvious, but I have the game on my PS2 and there are no glitches on it.

Vulkan rendering: https://imgur.com/a/v3M6Vun

Software rendering: https://imgur.com/a/nlhx7zD

It is actually flashing as well in the bottom right corner, but obviously it won't show up since those are images not videos.

### Reproduction Steps

1. Load up GTA: San Andreas (I'm using SLUS-20946)
2. Switch to software rendering mode
3. Look to the right of ur screen, it's most noticeable at the bottom but you'll see the textures are constantly flashing

### Expected Behavior

There should be nothing there

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

### GPU

NVIDIA GeForce GTX 1660

### GS Settings

https://imgur.com/a/1hg9HhF

### Emulation Settings

https://imgur.com/a/WU52uGr

### GS Window Screenshots

[Provided in the description]

**Comment by Mrlinkwii** [comment]
Can you post a gs dump?

**Comment by xianyi233** [comment]
There must be a lot of dumped textures. Haven't you finished replacing them?

**Comment by coornio** [comment]
You can embed pictures from imgur if you convert the link to `../i/img-id.png` style. You can also directly embed pictures in GitHub if you just drag them into the text box.

**Comment by BeyondThe5D** [comment]
> Can you post a gs dump?

I've tried this on multiple computers and multiple configurations I don't think I need to do it in this case


> There must be a lot of dumped textures. Haven't you finished replacing them?

What do you mean by that?


> You can embed pictures from imgur if you convert the link to `../i/img-id.png` style. You can also directly embed pictures in GitHub if you just drag them into the text box.
> 
> That said, seems like a valid SW bug in this case. As for workarounds, you can employ a 101% zoom, it should hide most such situations in any games where such a thing occurs, in software or otherwise.

Guess that could work as a temporary solution

Btw sorry for the late responses guys, I'm new to Github don't know how to enable notifications for this

**Comment by Mrlinkwii** [comment]
@BeyondThe5D  please can you post a gs dump  :)

**Comment by BeyondThe5D** [comment]
> @BeyondThe5D please can you post a gs dump :)

no lol

**Comment by refractionpcsx2** [comment]
why not?

**Comment by BeyondThe5D** [comment]
> why not?

Has nothing to do with it

**Comment by refractionpcsx2** [comment]
So you don't want help then, alright, thanks

**Comment by BeyondThe5D** [comment]
> So you don't want help then, alright, thanks

Didn't ask for help, I was telling you about the issue dumbass

**Comment by BeyondThe5D** [comment]
I actually forgot how brainless PCSX2 admins were lmao
