### ISSUE TITLE
[BUG]: Abysmally low performance using hardware renderer on certain scenes in Xenosaga Episode III

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [PCSX2/pcsx2#6624]
### Describe the Bug

This room here drops down to as low as 18fps on native resolution using OpenGL:

https://user-images.githubusercontent.com/79612681/178898933-357f8cc3-145e-4c0d-b9af-0af883831fdd.mp4

Vulkan runs worse (16fps) and even has a shadow bug to boot:

https://user-images.githubusercontent.com/79612681/178899230-f1d0b656-1c67-4532-ba96-100abb6d5f64.mp4

There's also this part here which runs similarly:

https://user-images.githubusercontent.com/79612681/178900070-a07a3c4c-ac29-4a98-b5e2-829e05c228c2.mp4

These run at full speed on software rendering.

### Reproduction Steps

Use this save file, load Xenosaga III disc 2, scroll down to slot number 16, load it, walk forward into the next room and then walk forward. It'll get slower the closer you are to the end. To get to the location in the second video, walk back instead.
[memcards.zip](https://github.com/PCSX2/pcsx2/files/9108299/memcards.zip)

### Expected Behavior

I expected to be able to run a PS2 game at a constant full speed, but was humbled by PCSX2's insane requirements.

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

i7-10700k

### GPU

RTX 3070

**Comment by MetrosexualGarbodor** [comment]
Oh and I went to close it on this screen and got this, and my RTX 3070 got to 99% usage for some reason. 
![image](https://user-images.githubusercontent.com/79612681/179004627-258da237-6696-4c41-8230-78db7e2e8b0d.png)

**Comment by JordanTheToaster** [comment]
Set texture preloading to Partial from Full.

![image](https://user-images.githubusercontent.com/80843560/179007040-3f193eae-d22c-458f-afa2-596995c922bd.png)

**Comment by coornio** [comment]
Rather than the GameDB, you can instead set this on a per-game basis. Either right-click the game from your list before it's launched and open Properties, or do so through the View menu after it's launched.

**Comment by JordanTheToaster** [comment]
> Rather than the GameDB, you can instead set this on a per-game basis. Either right-click the game from your list before it's launched and open Properties, or do so through the View menu after it's launched.

No it needs to be in the DB as people may not know and wonder why the game is running so poorly.
