### ISSUE TITLE
[BUG]: Explosions in Ace Combat 5 requires dual source blending off in hardware mode

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#6626]
### Describe the Bug

After toggling every option ever, the only way I found to get explosions not look like blocks is checking "disable dual source blending" in OpenGL (and even then I'm not really sure the light reflections/hues are right). 

### Reproduction Steps

Go to mission 5 or 13 (the ones with the submarine-launched burst missiles)
Get some kills here and there. 
Wait for the big explosions. 

### Expected Behavior

I can't swear software is 100% good (it's so hard to find videos that you are certain come from an actual PS2), but at least it looks believable. 

### PCSX2 Revision

v1.7.3073

### GPU

RTX 3060

### GS Settings

Blending accuracy has to be set on maximum.

### GS Window Screenshots

This is with default settings
![gs_20220715111242_Ace Combat - Squadron Leader_SCES-52424](https://user-images.githubusercontent.com/9366725/179193568-ac4584c8-e2cd-4d7f-8c64-56fa3eb49382.png)

This is with dual source blending disabled
![gs_20220715111247_Ace Combat - Squadron Leader_SCES-52424](https://user-images.githubusercontent.com/9366725/179193643-81430faf-7e8b-4a2c-8721-2b606ac8a6fc.png)

This is software
![gs_20220715111308_Ace Combat - Squadron Leader_SCES-52424](https://user-images.githubusercontent.com/9366725/179193691-70f0a53b-3d00-4d58-b264-717578c33503.png)

### Logs & Dumps

[GSdump](https://github.com/PCSX2/pcsx2/files/9113454/gs_20220714174926_Ace.Combat.-.Squadron.Leader_SCES-52424.zip)

**Comment by JordanTheToaster** [comment]
Doesn't do anything for me on OpenGL or Vulkan.

**Comment by mirh** [comment]
Meaning that they are already fine without?

**Comment by Azekthi** [comment]
Look at the top burst explosion in your second screenshot, "with dual source blending disabled". The block is still there.

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by mirh** [comment]
Yup.

**Comment by lightningterror** [comment]
The dumps don't work for me, can you upload different ones?

**Comment by lightningterror** [comment]
Seems it's an issue with texture shuffling, it's hitting the assert `ASSERT(!m_texture_shuffle || (context->CLAMP.WMS < 3 && context->CLAMP.WMT < 3));`

Here's how it looks without texture shuffling.
![image](https://user-images.githubusercontent.com/18107717/223504559-e6ee2219-f966-4741-8027-9744938981f9.png)

**Comment by mirh** [comment]
Maybe it should remain open until somebody (🥹) sends a `recommendedBlendingLevel=3` PR?

**Comment by PositronCannon** [comment]
For me on the latest v1.7.4500 the burst missile effect is fine in both this and AC Zero without touching any relevant (as far as I know) settings. Using Vulkan with blending accuracy set to the default Basic, and Dual Source Blending is also at the default (ie, not disabled).

![imagen](https://github.com/PCSX2/pcsx2/assets/65429992/c5885282-7aef-4469-b2e3-d78c695a4bb7)

I only have issues when upscaling, but that's a different issue to the blocks you're seeing (and can be fixed by using Round Sprite: Half for that matter).

**Comment by mirh** [comment]
That doesn't look right, indeed. 
The burst halo should have a fairly strong orange hue. Yours are quite pale instead.

**Comment by JordanTheToaster** [comment]
> That doesn't look right, indeed. The burst halo should have a fairly strong orange hue. Yours are quite pale instead.

You need high blending I'll be putting other fixes at some other point.

**Comment by PositronCannon** [comment]
> That doesn't look right, indeed. The burst halo should have a fairly strong orange hue. Yours are quite pale instead.

Hmm, I was just looking at the lack of squares around the effect, but you're right. I'll play around with it some more later.

**Comment by mirh** [comment]
Squares were never a problem (insofar as I'm not sure you can even report upscaling problems here yet). 
I did try to lobby for them anyway in https://github.com/PCSX2/pcsx2/pull/6600, but I suppose OP just wanted to eat their own cake.

**Comment by JordanTheToaster** [comment]
> Squares were never a problem (insofar as I'm not sure you can even report upscaling problems here yet). I did try to lobby for them anyway in #6600, but I suppose OP just wanted to eat their own cake.

If you would kindly read what I said I will be fixing that soon.
