### ISSUE TITLE
Cursor graphic glitch on latest git.

### ISSUE THREAD

**Issue by gendouhydeist** [PCSX2/pcsx2#663]
Works fine v1.3.1-719-g36e83b4.

![1](https://cloud.githubusercontent.com/assets/3938139/8761961/b14ae494-2d7b-11e5-80a5-1eae03786758.png)

**Comment by ramapcsx2** [comment]
This glitch comes and goes even with the same build. It's been in the game for as long as it runs on PCSX2. So this isn't a regression but it is buggy in GL and DX.

**Comment by bositman** [comment]
Works fine with 8539805691ed4319595895cbc8f238a8fecf132f tested.
