### ISSUE TITLE
[BUG]: Align Sprite unapplies uncleanly 

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#6631]
### Describe the Bug

Untoggling Align Sprite, doesn't give you the same image that you had before using it in the first place. 
Only changing the renderer altogether can remove it. 

### Reproduction Steps

Take for instance the scene in #6626 (title screen menus seem)
Check "Align Sprite"
Uncheck "Align Sprite"
Until you switch Renderers, the thing never unapplies completely (in the right scene, it may even seem the thing is still 100% enabled to a quick look)

### Expected Behavior

The renderer is actually expected to return to a pristine reproducible state, even without full cycling. 
Namco games are famous for their vertical black lines getting fixed by "Align Sprite", but god knows what kinds of sneaky glitches may come out in other cases. 

### PCSX2 Revision

v1.7.3073

### GS Window Screenshots

Notice for instance the artefacts in the middle of the VELOC and ALTIT indicators. 
![gs_20220715112311_Ace Combat - Squadron Leader_SCES-52424](https://user-images.githubusercontent.com/9366725/179195776-12eaa1a7-c375-4b61-94d9-782b41ef79e1.png)

**Comment by lightningterror** [comment]
If the image moves then you will notice the lines again, they just aren't black.

**Comment by mirh** [comment]
Uh, wow. 
What makes them *absorb* some of the previous surrounding color, as opposed to just stick to full nothingness?
