### ISSUE TITLE
[Feature Request]: Add a shortcut to increase and decrease volume level

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#6633]
### Description

Hello devs. I would like to share the idea of adding the possibility to have a shortcut to increase and decrease the volume of PCSX2.

### Reason

With this addition it will be possible to increase and decrease the volume without having to minimize or pause the emulation.

### Examples

As Dolphin and other projects. Volume 0-100.

**Comment by lightningterror** [comment]
Dupe of #6427
