### ISSUE TITLE
[BUG]: [Regression] Character shadow broke in Xenosaga Episode III between 1.7.3073 and 1.7.3079

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [PCSX2/pcsx2#6641]
### Describe the Bug

Left is 1.7.3073, right is 1.7.3079. Same exact manual settings.
![image](https://user-images.githubusercontent.com/79612681/179327625-9b18bebb-a23c-4274-916b-997db8b3efbb.png)
![image](https://user-images.githubusercontent.com/79612681/179328012-57785bc6-cfda-4294-a8b4-b3c3ad8907bc.png)
![image](https://user-images.githubusercontent.com/79612681/179328002-371a6a0c-1555-4839-a1e0-9dd1584b40af.png)

If I change 1.7.3079 to automatic settings, the broken shadow goes to the opposite side of the character.
![image](https://user-images.githubusercontent.com/79612681/179328441-e2073743-d644-489d-96e5-e490e5fd25bb.png)

### Reproduction Steps

Just start a new game and skip all cutscenes really. 
![image](https://user-images.githubusercontent.com/79612681/179328084-95df9e84-3e8f-4e65-8c44-3bdf9acd3880.png)
Walk a bit further to see the opposite, manual settings shadow.
![image](https://user-images.githubusercontent.com/79612681/179328123-5865cdb7-b67d-45a8-a419-01ea226ff881.png)

### PCSX2 Revision

v1.7.3079

### Operating System

Windows 10 (64bit)

### CPU

i7-10700k

### GPU

RTX 3070

### Logs & Dumps

Both shadows should be visible in this dump.
![gs_20220716020022_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417](https://user-images.githubusercontent.com/79612681/179328205-2ef78d22-39ae-4fb9-864d-cac50f6d98ec.png)
![image](https://user-images.githubusercontent.com/79612681/179328230-17361977-4485-4b70-99fb-2b7f318ec063.png)

[gs_20220716020022_Xenosaga Episode III - Also Sprach Zarathustra _Disc2of2__SLUS-21417.zip](https://github.com/PCSX2/pcsx2/files/9124829/gs_20220716020022_Xenosaga.Episode.III.-.Also.Sprach.Zarathustra._Disc2of2__SLUS-21417.zip)

**Comment by refractionpcsx2** [comment]
hmm, can you enable "disable safe features" I suspect the problem is that unscaling of lines was broken and thus "fixed" xenosaga, because for ages OpenGL was the only one to work with these shadows.

**Comment by MetrosexualGarbodor** [comment]
That seems to fix it. So it should be enabled from now on?

**Comment by refractionpcsx2** [comment]
eh, I mean you can enable it locally if you want :P I don't think it's really a solution, try some of the upscaling fixes also, see if any of them help, also be sure to check "Native"

**Comment by refractionpcsx2** [comment]
Also it should be fine if your manual fixes are disabled, since the automatic fixes sort the shadows out for all renderers, as far as I can tell

![image](https://user-images.githubusercontent.com/6278726/179328763-b71b8d43-993a-435e-a452-92542b6d2a07.png)

**Comment by MetrosexualGarbodor** [comment]
The upscaling fixes don't really do anything with "disable safe features" off, they just shift the shadow around. With it on, Half-Pixel Offset on Normal (Vertex) makes it reappear even bigger. 
![image](https://user-images.githubusercontent.com/79612681/179328733-a7243f46-7274-4805-838e-71846ac3bb1f.png)

All the other upscaling fixes don't do anything with it on.


On native resolution or on software rendering, the shadow is not there.
![image](https://user-images.githubusercontent.com/79612681/179328838-769f5248-5a8a-4cbf-b135-e0fe18746882.png)


And yes, your picture still has it, just less opaque.

**Comment by refractionpcsx2** [comment]
I mean if you disable manual gs fixes altogether (untick the box under the renderer tab) it should look mostly fine.  The problem is there's no perfect solution for this game, but the automatic settings that are there give the result I posted above, which isn't awful.

**Comment by MetrosexualGarbodor** [comment]
It's not the automatic fixes, it's the CRC hack level that makes mine look solid black and yours more transparent. "Aggresive" makes it opaque, the rest make it look like on your screenshot.
![image](https://user-images.githubusercontent.com/79612681/179329344-94c58078-6013-42ee-844a-7322dc86832d.png)

The automatic fixes don't really change it as I said previously, they just shift it around.

**Comment by refractionpcsx2** [comment]
My CRC level is actually automatic

![image](https://user-images.githubusercontent.com/6278726/179329455-4c199ba2-8d5a-4c39-bd32-959aff661673.png)

**Comment by MetrosexualGarbodor** [comment]
2/3 of the issues in the wiki list "Aggresive" as a solution (I know, one is for D3D and the other one doesn't have a solution), that's why I had it on. 
![image](https://user-images.githubusercontent.com/79612681/179330311-f4888587-a955-45a9-ae19-874321d9cdbe.png)

I suppose I'll text everything with it on automatic.

**Comment by refractionpcsx2** [comment]
I don't think any of them are relevant anymore, we've fixed them all, afaik. so the Wiki should be updated by somebody.

As for the issues left, there's not much we can do about it, as things are (with auto crc's) it's as good as it'll likely get when upscaling.
