### ISSUE TITLE
[Feature Request]: Choice of which corner to show OSD

### ISSUE THREAD

**Issue by brad86m** [PCSX2/pcsx2#6642]
### Description

Choose which corner to show OSD information.

### Reason

Flexibility is good. 

### Examples

.

**Comment by jjw410** [comment]
I think in general, options to customise the OSD further is always useful.

**Comment by RedDevilus** [comment]
Probably the same as https://github.com/PCSX2/pcsx2/issues/3622

**Comment by grimpunch** [comment]
For what it's worth, I made some progress on this if anyone wanted to pick it up but issue to consider is:
![image](https://user-images.githubusercontent.com/1707054/195901587-ffb7ccc8-3783-4db0-a286-5debd629f47e.png)
this is fine. but enabling OSD info in GS settings:
![image](https://user-images.githubusercontent.com/1707054/195901649-5b92fb4a-512c-4f90-8257-c7d74ea4082b.png)
![image](https://user-images.githubusercontent.com/1707054/195901669-e299a14c-21d1-494b-b8a0-26785dd716b6.png)
causes overlaps, something to figure out best solution to before pursuing this further.

**Comment by F0bes** [comment]
I'll consider this resolved by #11638
