### ISSUE TITLE
[BUG]: Gran Turismo 4 is now broken

### ISSUE THREAD

**Issue by mrkenhoo** [PCSX2/pcsx2#6645]
### Describe the Bug

After this copyright warning, the game hangs. No introduction movie is played, making the game borked.
![](https://user-images.githubusercontent.com/60463234/179351314-0854d472-93dc-476c-9449-08f23463dd4e.png)

### Reproduction Steps

Boot from a Gran Turismo 4 ISO image.

### PCSX2 Revision

v1.7.0-dev-3913-gf77c66cc2

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

i7-9700K

### GPU

Intel UHD Graphics 630

### GS Settings

- Graphics > Display settings
![graphics-display-settings](https://user-images.githubusercontent.com/60463234/179351164-50018889-2fcc-451b-9066-03d1311aa92b.png)
- Graphics > Rendering settings
![2](https://user-images.githubusercontent.com/60463234/179351166-47bfb643-3de1-49d3-addf-85a846f60a9b.png)
- Graphics > 
![3](https://user-images.githubusercontent.com/60463234/179351167-9f4214c8-dc13-433a-b9df-f7004df9ce5f.png)
![4](https://user-images.githubusercontent.com/60463234/179351169-c53f775f-6079-44ba-9e3a-e1821009ce08.png)

### Emulation Settings

- System settings
![01](https://user-images.githubusercontent.com/60463234/179351514-fbfaf3e3-8be1-4a3d-8791-a75a0ac35e60.png)

> Tried disabling MTVU but it gives the same behaviour.

### GS Window Screenshots

https://user-images.githubusercontent.com/60463234/179351795-4eb7f047-7629-44ca-873d-d746751b39d6.mov

### Logs & Dumps

Here's the verbose log when Gran Turismo 4 launches: [emulog.txt](https://github.com/PCSX2/pcsx2/files/9125591/emulog.txt)

**Comment by refractionpcsx2** [comment]
Can you post a log after running the game? That one is just you loading PCSX2.

Thanks.

**Comment by refractionpcsx2** [comment]
I just tried both the PAL and NTSC versions and they both work fine. Gonna definitely need more details.

**Comment by Mrlinkwii** [comment]
Curious question @mrkenhoo  can you try the appaimge for me , because you mentioned your on arch to im assuming your using the aur

**Comment by mrkenhoo** [comment]
> Can you post a log after running the game? That one is just you loading PCSX2.
> 
> Thanks.

How do I do so? I don't see such option on the debug menu in the QT version

> Curious question @mrkenhoo can you try the appaimge for me , because you mentioned your on arch to im assuming your using the aur

The AppImage gives the same behaviour.

**Comment by refractionpcsx2** [comment]
> > Can you post a log after running the game? That one is just you loading PCSX2.
> > Thanks.
> 
> How do I do so? I don't see such option on the debug menu in the QT version
> 

Enable File logging from the debug menu (enable the EE and IOP and CDVD logs too, if you can), then start the game until the hang, then close the emulator, then upload the emulog.txt.

**Comment by mrkenhoo** [comment]
I just did. Here's the file [emulog.txt](https://github.com/PCSX2/pcsx2/files/9126115/emulog.txt) again.

Reading beforehand, I noticed this message:
```
Possible old value used in COP2 code. If the game is broken, please report to http://github.com/pcsx2/pcsx2.
```

**Comment by refractionpcsx2** [comment]
That'd do it.

This is now a support issue, if you need further help, please visit our forums or discord, links are all on pcsx2.net

Thanks.

**Comment by mrkenhoo** [comment]
I didn't see that. Some ISOs got corrupted on my server it seems. Thanks for the help.
