### ISSUE TITLE
[BUG]: Software rendering issue on GTA: San Andreas

### ISSUE THREAD

**Issue by GitHubUser3827** [PCSX2/pcsx2#6646]
### Describe the Bug

There's a bug with software rendering where the right of the screen is kind of corrupted and has weird glitchy lines appearing, I can't find anybody who has reported this bug, I would assume people have though since it's quite obvious, but I have the game on my PS2 and there are no glitches on it.

Vulkan rendering:
![image](https://user-images.githubusercontent.com/92761598/179357970-004c31c1-c369-488c-a78a-2f4f3712de55.png)

Software rendering:
![image](https://user-images.githubusercontent.com/92761598/179357965-6c5dd451-3bf2-4be8-9446-8e80a1d80381.png)

It is actually flashing as well in the bottom right corner, but obviously it won't show up since those are images not videos.

Reuploading this because unlike some of the mods in this forum I actually care about emulation and wanna see it improve, and for those who don't know some crippled admin shut down my bug report post despite the fact they never said it was going to be fixed or looked into. Also the admin got so offended by being called stupid they banned my other account lmao.

### Reproduction Steps

1. Load up GTA: San Andreas (I'm using SLUS-20946)
2. Switch to software rendering mode
3. Look to the right of ur screen, it's most noticeable at the bottom but you'll see the textures are constantly flashing

### Expected Behavior

Should appear how it appears in the Vulkan renderer

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

### GPU

NVIDIA GeForce GTX 1660

### GS Settings

https://imgur.com/a/1hg9HhF

### Emulation Settings

https://imgur.com/a/WU52uGr

### GS Window Screenshots

[Provided in the description]

### Logs & Dumps

https://www.mediafire.com/file/bzjlo9xaagp8g13/gs_20220716033623_Grand_Theft_Auto_-_San_Andreas_SLUS-20946.gs/file

**Comment by refractionpcsx2** [comment]
If you care that much, why did you decide to cop an attitude with us when we asked for the relevant stuff to fix it? Your head is so far up your own arse you think you know better than everyone else, then you call us morons when you refuse to cooperate.

We asked you for a GS Dump so we could SEE the issue, but you went "no, it's not relevant" like you know best, you don't, if you do, fix it yourself, otherwise stop being an entitled, bigheaded asshole.

If you simply did what we asedk, we'd never have a problem.

**Comment by GitHubUser3827** [comment]
> If you care that much, why did you decide to cop an attitude with us when we asked for the relevant stuff to fix it? Your head is so far up your own arse you think you know better than everyone else, then you call us morons when you refuse to cooperate.
> 
> We asked you for a GS Dump so we could SEE the issue, but you went "no, it's not relevant" like you know best, you don't, if you do, fix it yourself, otherwise stop being an entitled, bigheaded asshole.
> 
> If you simply did what we asked, we'd never have a problem.

If I told you, you'd call me a capper

**Comment by refractionpcsx2** [comment]
What are you talking about?

**Comment by GitHubUser3827** [comment]
> What are you talking about?

I'm just here to report a bug

**Comment by refractionpcsx2** [comment]
That's fine, Just don't cop an attitude with us in future and we won't have any issues. (Yes, I know you're that Beyond guy, just so we're clear)

**Comment by GitHubUser3827** [comment]
> That's fine, Just don't cop an attitude with us in future and we won't have any issues. (Yes, I know you're that Beyond guy, just so we're clear)

I wouldn't have an issue if you didn't just aimlessly close the post with little regard to what the post was actually saying

**Comment by refractionpcsx2** [comment]
I closed it because you were being all knowing and talking back to us when we asked you to provide information, outright refusing, so why should I waste my time? 

We're not a business, we don't have to tolerate you being an asshole to us, we owe you nothing, you pay us nothing, if you're not going to be helpful and provide the things we ask for to look in to the bug YOU reported, I'm not going to hang around and play games.

**Comment by GitHubUser3827** [comment]
> I closed it because you were being all knowing and talking back to us when we asked you to provide information, outright refusing to cooperate, so why should I waste my time?
> 
> We're not a business, we don't have to tolerate you being an asshole to us, we owe you nothing, you pay us nothing, if you're not going to be helpful and provide the things we ask for to look in to the bug YOU reported, I'm not going to hang around and play games.

Good to know if somebody reports a bug and doesn't send basic information even though you can easily reproduce the steps urself because it literally says at the top that you just pretend the bug doesn't exist

**Comment by GitHubUser3827** [comment]
> That's fine, Just don't cop an attitude with us in future and we won't have any issues. (Yes, I know you're that Beyond guy, just so we're clear)

Also good job, you cracked the case, I am indeed Beyond, you should be a detective god knows how you figured me out, not like I literally made this account today, have the default profile picture, and posted the exact same issue word-for-word and have the same computer specs

**Comment by refractionpcsx2** [comment]
Alright so you're going to continue to be a sarcastic asshole, nevermind then. I gave you a chance, you chose to blow it.
