### ISSUE TITLE
Warship Gunner 2 VIF issues, gamefix needed

### ISSUE THREAD

**Issue by disastranagant** [PCSX2/pcsx2#665]
Game's still has missing geometry and hasn't worked properly since r5403 

http://i.imgur.com/qp8W2Hh.jpg
http://imgur.com/a/FmxvK

**Comment by refractionpcsx2** [comment]
I thought I fixed this once??

**Comment by gregory38** [comment]
Status?

**Comment by refractionpcsx2** [comment]
I looked once, couldn't get it to a position where I could see the error, I'll probably have another go at some point.

**Comment by refractionpcsx2** [comment]
Fixed now, seems okay on my end now. stupid commit didn't link >.<

**Comment by gregory38** [comment]
You need to add a '#' before number and to remove issue (yes silly)

**Comment by refractionpcsx2** [comment]
Yeh I wasn't sure, got confused which was around it was, so i had a 50/50 chance of getting it right lol
