### ISSUE TITLE
[BUG]: Fullscreen Hotkey doesn't work after the latest updates

### ISSUE THREAD

**Issue by Zorklis** [PCSX2/pcsx2#6664]
### Describe the Bug

The hotkey to fullscreen doesn't work anymore.
Normally I set it to F11 or F12, even returning it to default setting yielded nothing

### Reproduction Steps

set the hotkey to any key (F11 or F12) and see if it works

### PCSX2 Revision

v1.7.3091

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
You're right, it doesn't. probably an oversight since some of the toggle fullscreen behaviour was changed :)

**Comment by refractionpcsx2** [comment]
Fixed in https://github.com/PCSX2/pcsx2/commit/395f4e904c1baa347cbb5d0d5d951c974fb1812b
