### ISSUE TITLE
[Feature Request]: Game properties hotkey/Game properties toolbar

### ISSUE THREAD

**Issue by Zorklis** [PCSX2/pcsx2#6665]
### Description

A quicker way to access the per game properties.

### Reason

Having a quicker way to access and change the game properties is a nice ease of life feature in case you want to change the game resolution or fix a setting to your liking.
Also having a per game settings would make more sense than having a universal settings in the toolbar or at least both options.

### Examples

PCSX2 already has something similar but not quite right

**Comment by stenzek** [comment]
Settings button has opened a popup menu to select between Game Properties or Global Settings when a game is running for some time now.
