### ISSUE TITLE
[BUG]: Chaotic Build (aur) wont stop triggering gnome software centre for restart and update

### ISSUE THREAD

**Issue by LethalManBoob** [PCSX2/pcsx2#6672]
### Describe the Bug

Chaotic Build (aur) wont stop triggering gnome software centre for restart and update

### Reproduction Steps

install chaotic build via aur with gnome and visit gnome software centre

### PCSX2 Revision

v1.7.0.dev.r3913.gf77c66cc2-1

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

**Comment by refractionpcsx2** [comment]
This doesn't sound like anything to do with PCSX2? plus it's an unofficial build, I suggest you take it up with the packager.
