### ISSUE TITLE
[Feature Request]: Rapid Fire toggle for individual buttons

### ISSUE THREAD

**Issue by Veelkyn** [PCSX2/pcsx2#6679]
### Description

The older PCSX2 builds, as part of the control customization, allowed a button to have a 'Rapid Fire' function that, if held, rapidly activates that button multiple times. Many games have a "Mash O" gameplay sequence, and this will let people simply hold O to get this done. 

### Reason

It's a great Quality of Life feature that further allows you to play your own way with certain games. Nowadays, it's basically a common accessibility feature for any game that has such "mash button to proceed" by letting people just hold it instead. So, it seems sensible to include it here, so users can have a workable way of creating this feature. 

### Examples

![Rapid fire](https://user-images.githubusercontent.com/109709622/180118485-17dc32db-b970-4253-a162-ae0f8aab40f0.jpg)

That's a screenshot of the controller options of the PCSX2 1.7.2503 build. It feels like a shame to lose such a useful feature.

**Comment by auwsmit** [comment]
LilyPad may have been a bit of an overly complex abomination when it came to the interface, but it sure was packed with useful features and options, allowing it to be among the most useful and flexible input methods available. It's only rivaled by something like Dolphin's input method which has an [absurdly flexible input syntax.](https://wiki.dolphin-emu.org/index.php?title=Input_Syntax)
