### ISSUE TITLE
[BUG]: Freeze on start with Vulkan renderer

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#6682]
### Describe the Bug

PCSX2 freezes on starting any title (and even just the BIOS) the Vulkan renderer is selected.  No freezing occurs with Software or OpenGL renderers.  Tested against default settings.

System info:
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 515.48

### Reproduction Steps

Start any title or BIOS with Vulkan renderer selected.

### Expected Behavior

Titles or BIOS should launch.

### PCSX2 Revision

1.7.3107

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.3 / kernel 5.15

**Comment by refractionpcsx2** [comment]
Is this a regression?
are you starting PCSX2 with any parameters?
do you have it so it launches in a separate window or fullscreen on boot?

**Comment by Shoegzer** [comment]
This may be a regression, it's run on Vulkan when support was first added but I'm not certain something else such as the Nvidia drivers (which I've updated since) aren't a contributing factor.  Confirmation from another tester would help here.  I tested the latest build I still have, which is from commit 6532dbced4338a496bbee02efac1e0108e8dd06e (version not shown in titlebar), and also 1.7,2857, but I get a GS popup message "Failed to compile utility pipelines" when attempting to start something with Vulkan.  Testing with 1.7.3033 and 1.7.3107 as posted above, it freezes.

I'm launching pcsx2-qt with no parameters.  And default settings are used so it renders to the main window with no fullscreen on boot (though I've tested those and encounter the same issue unfortunately).

**Comment by refractionpcsx2** [comment]
hmm I would try updating your nvidia drivers again, if there's a newer one, there was one around that release which didn't work super great on vulkan (kept having graphical errors).

Our tester on Ubuntu 21.xx (idk the exact version) with an intel iGPU says it runs fine.

**Comment by tellowkrinkle** [comment]
Check the log console or emulog.txt for more detailed info

**Comment by refractionpcsx2** [comment]
I've just been informed if you're using Wayland that might be why, apparently there's a bad interaction between Nvidia drivers + Vulkan + Wayland (with AMD being fine)

**Comment by Shoegzer** [comment]
Thanks guys. Unfortunately there's no new Nvidia driver beyond 5.15, but I'll test as soon as one's available.  In case it helps, other emulators such as Dolphin and RPCS3 aren't having any issues with the Vulkan renderer and this driver.  Also for comparison, my distro (Linux Mint 20.3) is based on Ubuntu 20.04.5 LTS.  I'm using X11, not Wayland.

Here are the logs you asked for:

[bad_shader_1.txt](https://github.com/PCSX2/pcsx2/files/9162666/bad_shader_1.txt)
[emulog.txt](https://github.com/PCSX2/pcsx2/files/9162710/emulog.txt)

I had to enable verbose logging for the emulog or nothing was logged.  Also, is it just me or is it trying to use my Intel GPU rather than the discrete Nvidia card for some reason?  I was surprised to see this without a reference to my Nvidia 3070:
```
[   11.5898] 	Intel open-source Mesa driver
[   11.5898] 	Intel(R) UHD Graphics (CML GT2)
```

**Comment by refractionpcsx2** [comment]
hmm, so it's not even using your nvidia card? can you manually select your Nvidia card under Settings->Graphics?

**Comment by Shoegzer** [comment]
Thanks, and sure enough, I didn't even realize I *could* select the card, as I've been so used to using software and opengl which don't permit that for some reason.  When I selected the Nvidia card everything worked fine, so I'll close this issue.  Sorry for any inconcenience!
