### ISSUE TITLE
[BUG]: "Reset Defaults" in Audio settings doesn't do anything

### ISSUE THREAD

**Issue by Zorklis** [PCSX2/pcsx2#6693]
### Describe the Bug

I tried changing latency and timestrech settings but then decided to just use the defaults ones and then found out it doesn't reset for me at all.

### Reproduction Steps

Move audio sliders in the audio settings and then try resetting them and see if it works?

### Expected Behavior

Reset Defaults button to reset settings to their default placement.

### PCSX2 Revision

v1.7.3114

### Operating System

Windows 10 (64bit)

**Comment by EdHerdman** [comment]
I just encountered this while setting up Audio - Mixing Settings. Neither Output Settings -> Latency nor Timestretch Settings -> Sequence Length return to the default values when pressing "Reset Defaults."

Version: pcsx2-v1.7.3345-windows-64bit-AVX2-Qt, Windows 11 64-bit

**Comment by refractionpcsx2** [comment]
It's about to be fixed, but please be aware it only resets the timestretcher settings (when it works), hence it being in the box with those settings.
