### ISSUE TITLE
[BUG]: Folder Memory Card saves dissapear/wiped in BIOS once ejected and reinserted again.

### ISSUE THREAD

**Issue by Zorklis** [PCSX2/pcsx2#6694]
### Describe the Bug

Game saves from Folder Memory Card dissapear (might be hidden) once Folder MC is ejeced from the "Console Ports" slots/port and inserting it back again it shows up empty with only a message "There is no data."
8MB Memory card does not have this issue.

### Reproduction Steps

Get a game save in a 8MB memory card, copy the save to the Folder Memory card and then eject the Folder memory card and insert it again. It should show no save icons and only show ""There is no data." message.

### Expected Behavior

Expected behavior should be that game save icons appear (are they wiped?) and game saves are transferable to the 8MB or any other game card despite ejecting and inserting it again.

### PCSX2 Revision

v1.7.3114

### Operating System

Windows 10 (64bit)

### CPU

i3 3770

### GPU

GTX 1060

**Comment by refractionpcsx2** [comment]
Because of how folder memcards work, you can't really view them in the BIOS, I'm actually surprised you saw anything at all to be honest.

**Comment by refractionpcsx2** [comment]
Update on this, you can actually view that games memcard contents by going in to the memcard browser, changing disc to the game you want to view, then it will swap out the memcards to the data you want, now that memcard swapping is more reliable, that'll work for you.
