### ISSUE TITLE
[BUG]: PCSX2 RetroArch version doesn't show options of changing the dev9 plugin (to CLR_DEV9.dll) to allow internet adapter and etc.

### ISSUE THREAD

**Issue by Phoenix1205555** [PCSX2/pcsx2#6704]
### Describe the Bug

The emulator works great in retroarch and certain ui menus work and appear properly but doesn't allow the user to change the plugins or certain settings. This issue prevents to use of network adapters and etc. I'm unable to play online on certain games like Resident evil outbreak online. I can use the regular emulator but the network setup ui is bugged and doesn't properly show even with program mode (f9) on.

### Reproduction Steps

1. Download required files for retroarch and retroarch itself (website or steam)
2. Insert the files in their proper location
3. Launch RetroArch

### Expected Behavior

More settings

### PCSX2 Revision

v1.6.0 (RetroArch)

### Operating System

Windows 11

### CPU

AMD Ryzen 5 2600 Six-Core Processor

### GPU

NVIDIA GeForce GTX 1650 SUPER

### GS Window Screenshots

![Screenshot 2022-07-24 173025](https://user-images.githubusercontent.com/47672935/180666682-861ed407-f3c6-4195-aad3-b51c77f2455f.png)

**Comment by MrCK1** [comment]
Retroarch bugs are not accepted here, you'll need to open an issue with them to try and address the issue. Sorry
