### ISSUE TITLE
[BUG]: Per-game settings checkbox in per-game settings window + bad per-game ini creation?

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6705]
### Describe the Bug

The first issue here is the following:

![unknown](https://user-images.githubusercontent.com/11655762/180667805-b7ba6125-9113-456e-aba2-a7243b89df96.png)

Pretty sure that checkbox on the right should not exist as part of the per-game settings window. 

The second issue (?) has to do with per-game ini creation. It only applies to GS dumps. If you were to open a GS dump from an old emulator version (1.6) and adjust the per-game settings for it, the emulator doesn't appear to handle the lookup fully/properly. As a result, the ini is created without the serial code that it needs, like so:

![image](https://user-images.githubusercontent.com/11655762/180667867-6790c36f-72e1-471c-b8a4-f2598a32c9d9.png)

You might ask -- what does it matter? Well, this ini is basically *invisible* to the emulator outside of that GS dump. If you were to actually start the game this ini concerns and go to its per-game settings, they'll be pristine, and a new file with the same crc will be created that INCLUDES that serial. Minor, but should probably be rectified. 

### PCSX2 Revision

1.7.3123

### Operating System

Windows 11

**Comment by stenzek** [comment]
Second part is working as intended, old GS dumps don't include the serial.

**Comment by coornio** [comment]
> Second part is working as intended, old GS dumps don't include the serial.

I reckoned that was the case, but wouldn't it be more desirable to not have such an outlier? Unless a reverse lookup of CRC to serial isn't possible in this situation, which is what my gut tells me -- in which case, nevermind, case closed indeed on that part :D

I do have a theory on how all of that would work out process-wise but it's too much work to be worth it for such a small subset of GS dumps.

**Comment by refractionpcsx2** [comment]
CRC lookup isn't possible for 98% of games because it relies on them having a compatibility patch, since we don't store CRC's otherwise, that's the whole reason we added the serial to GSDumps, unfortunately there's nothing we can do retroactively, it's better just to make new GSDumps, or live with it :P
