### ISSUE TITLE
[BUG]: GS-SW: Ratchet and Clank Going Commando probable mipmap issue

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#6710]
### Describe the Bug

Some areas of Ratchet and Clank Going Commando glitch out as you approach before returning to normal.

NTSC-U

### Reproduction Steps

Load the provided state or memard save and proceed a short ways from the ship

### Expected Behavior

Software to not glitch like hardware.

### PCSX2 Revision

1.7.3124

### Operating System

Windows 11

### CPU

Intel i9 10900X

### GPU

Nvidia RTX 3090

### GS Settings

All defaults except for Software Renderer and enabled Screen Offsets (though disabled doesn't effect glitch).

### Emulation Settings

All defaults.

### GS Window Screenshots

Software (center box):
![gs_20220725090137_Ratchet _ Clank 2 - Going Commando_SCUS-97268](https://user-images.githubusercontent.com/22252639/180785540-79f9017f-f924-4ee7-9c4e-f1744a963a0f.png)

Hardware:
![gs_20220725090149_Ratchet _ Clank 2 - Going Commando_SCUS-97268](https://user-images.githubusercontent.com/22252639/180785579-5ceaff50-280e-4106-a26d-d545345d12ea.png)

### Logs & Dumps

Memcard:
[memcard1.zip](https://github.com/PCSX2/pcsx2/files/9181504/memcard1.zip)

Savestate:
[SCUS-97268 (38996035).01.zip](https://github.com/PCSX2/pcsx2/files/9181492/SCUS-97268.38996035.01.zip)

GS dump:
[multi-frame_gs_dump.zip](https://github.com/PCSX2/pcsx2/files/9181453/multi-frame_gs_dump.zip)

**Comment by refractionpcsx2** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/5008
