### ISSUE TITLE
[BUG]: Dual Hearts image offset during FMV

### ISSUE THREAD

**Issue by ichee** [PCSX2/pcsx2#6715]
### Describe the Bug

In Dual Hearts during an FMV, the image appears offset the same as some interlaced games appear when de-interlacing is disabled.

Setting de-interlacing to bob-tff fixes the FMVs, but the rest of the game doesn't appear to need de-interlacing, though bob-tff doean't appear to have a significant effect on how the rest of the game appears, barring being harsh on the eyes.

Issue appears to be either the Automatic setting is not picking up on the changes during the FMV (assuming it detects anything beyond game startup), or FMVs for this game are offset and needs correcting somehow.

Otherwise, this may simply amount to a feature request for a setting to change the de-interlacing state during FMVs, similar to the switch to software setting already present.

NTSC-U

### Reproduction Steps

Start game with default settings. Wait till FMV starts before the title screen.

### Expected Behavior

FMVs to not appear offset.

### PCSX2 Revision

1.7.3124

### Operating System

Windows 11

### CPU

Intel i9 10900X

### GPU

Nvidia RTX 3090

### GS Window Screenshots

Default settings:
![automatc-none](https://user-images.githubusercontent.com/22252639/180954027-a539f4be-5f23-4e87-83d8-cd0e264bc8cb.png)

De-interlacing set to Bob-TFF:
![bob_tff](https://user-images.githubusercontent.com/22252639/180954144-24d7ea21-ada8-42c4-97a4-c8f9c1a2dda9.jpg)

**Comment by refractionpcsx2** [comment]
why is the second picture taken with your phone? It's very difficult to see the finer details when taken like that (especially with the overblown lighting)

A screenshot would be better, thanks.

**Comment by ichee** [comment]
The second was taken with the phone because the GS screenshot doesn't capture the de-interlace, and ends up looking like the first.

**Comment by ichee** [comment]
Actually, it wasn't taking screenshots properly with bob.
Here's one taken with weave-tff:
![gs_20220726121008_Dual Hearts_SLUS-20475](https://user-images.githubusercontent.com/22252639/181057171-e19b340a-8d29-4029-8cef-24c58388b90f.png)

**Comment by refractionpcsx2** [comment]
can you please post a GS Dump? Thanks

**Comment by ichee** [comment]
Here you go.
[gs_20220726121649_Dual Hearts_SLUS-20475.zip](https://github.com/PCSX2/pcsx2/files/9191546/gs_20220726121649_Dual.Hearts_SLUS-20475.zip)

**Comment by refractionpcsx2** [comment]
Okay so the deal is that in some cases PCSX2 doesn't deinterlace properly by itself, it tries to cheat to avoid it, but looks like this game does need Blend TFF, which would need setting in the GameDB.

Would you agree that this works?

**Comment by ichee** [comment]
Outside of FMVs, the game itself looks fine with no de-interlacing, plus there is some heavy motion blur in some areas which would be exacerbated by blend.
I guess if there is no other easy way to apply de-interlacing to only the FMV, then do what you think is best.

For a comparison, here are a couple of screenshots of an area with the worst motion blur in the game.

None:
![gs_20220726123848_Dual Hearts_SLUS-20475](https://user-images.githubusercontent.com/22252639/181063389-d4ed1e6c-7ef5-41e4-a1e9-d124acb51fe0.png)
 
Blend:
![gs_20220726123834_Dual Hearts_SLUS-20475](https://user-images.githubusercontent.com/22252639/181063439-7ea33076-0398-41ab-9cf8-505ee4336403.png)


None (in motion):
![gs_20220726124736_Dual Hearts_SLUS-20475](https://user-images.githubusercontent.com/22252639/181064266-ac66b25c-03ce-4420-863c-b77c27c34162.png)


Blend (in motion):
![gs_20220726124758_Dual Hearts_SLUS-20475](https://user-images.githubusercontent.com/22252639/181064350-2fa96455-1b09-4b9a-aa9a-77f1d05601a9.png)

**Comment by refractionpcsx2** [comment]
I mean, the games are *supposed* to be deinterlaced, the fact they work sometimes without is really just luck. So it's either you live with it on videos or we force it to blend so everything looks correct (which will cause ghosting ingame when moving)

**Comment by ichee** [comment]
What I was trying to suggest as an alternative was something like the game fix `Use Software Renderer For FMVs`, but instead
`Use 'X' Deinterlace Mode for FMVs`.

Since that game fix is changing a value that is in the GS already, and deinterlace modes are also in GS, it could simply be a duplicate setting pointing to a specific deinterlace mode instead of a renderer.

I wouldn't think it would be too difficult since both would effectively be the same code, only pointing to a different target setting.

**Comment by ichee** [comment]
On further examination, there may be more to this than just the FMV.

There's a small section at the bottom of the screen during transitions that bleeds out a little during loading of the next area.

A dream level for a character named Meg that looks like a pop-up book drawn in crayon that, when stationary, appears to vibrate a little.

None of the above occur with blend-tff.

So forcing blend may actually be needed.

Never really noticed the above issues since deinterlacing was not in use.
