### ISSUE TITLE
[BUG] Klonoa 2: miscolored objects/enemies in HW mode

### ISSUE THREAD

**Issue by Igetin** [PCSX2/pcsx2#6720]
### Describe the Bug

In Klonoa 2: Lunatea’s Veil, when using the OpenGL or Vulkan renderer, multiple types of enemies/objects appear miscolored, which can be confusing to the player. I am filing these under the same issue as they very likely stem from the same underlying problem.

### Reproduction Steps

1. Run the game using the OpenGL or Vulkan renderer.
2. Steps depend on the enemy/object:
  - moving [Goomi](https://klonoa.fandom.com/wiki/Goomi):
    1. go to any stage where the object appears, e.g. Kingdom of Sorrow
    2. the moving Goomi incorrectly appears as regular green Goomi (which are normally stationary)
  - a long-lasting [Kiton](https://klonoa.fandom.com/wiki/Kiton)
    1. go to Kingdom of Sorrow (the only stage where this variant appears) and progress to the end of the 8th area until you encounter a wall and a Kiton 
    2. the enemy appears incorrectly as a regular Kiton with a blue body and yellow legs (which normally have a shorter use)
- [Likuri](https://klonoa.fandom.com/wiki/Likuri)
  1. go to any stage where the enemy appears, e.g. Ishras Ark
  2. grab a Likuri and merge it with two or three enemies
  3. the Likuri appears incorrectly as yellow (which should only be the case when merged with **only one** enemy)
- color-coded crystal boulders
  1. go to any stage where the object appears, e.g. Ishras Ark
  2. crystals that emit blue or red smoke are incorrectly rendered as yellow
- short-fuse [Boomie](https://klonoa.fandom.com/wiki/Boomie)
  1. go to any stage where the enemy appears, e.g. The Ark Revisited
  2. the enemy incorrectly appears as regular red Boomie (which normally explode after being captured, not when approached)

### Expected Behavior

 - moving [Goomi](https://klonoa.fandom.com/wiki/Goomi) should appear red
 - long-lasting [Kiton](https://klonoa.fandom.com/wiki/Kiton) should have a yellow body with black legs
 - [Likuri](https://klonoa.fandom.com/wiki/Likuri) should appear blue after merging with two enemies, and red after merging with three enemies
 - color-coded crystal boulders should be blue if they emit blue smoke, and red if they emit red smoke
 - short-fuse [Boomie](https://klonoa.fandom.com/wiki/Boomie) should appear pink on spawning and then alternate between black and white until blown up

### PCSX2 Revision

v1.7.3130

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 35

### CPU

AMD Ryzen 3700X

### GPU

AMD Radeon RX 6800 XT

### GS Window Screenshots

| Enemy/object | Hardware (incorrect) | Software (correct) |
| ------------- | ------------- | ------------- |
| moving Goomi | <img src="https://user-images.githubusercontent.com/14016863/181248712-e76788e9-b390-405a-967d-c9903dbf1af2.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181248724-e5058c50-39c0-4ead-9011-f10e80fb5e52.png" width="300">  |
| long-lasting Kiton | <img src="https://user-images.githubusercontent.com/14016863/181250303-b165900e-b58d-419a-9dde-eb569fcfe215.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181250308-5c6c7707-c236-455f-8786-ebee541ef028.png" width="300">  |
| Blue crystal and Likuri merged with two enemies | <img src="https://user-images.githubusercontent.com/14016863/181250731-370d1c30-864b-40c1-b9ed-e0a88ad89e8a.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181250738-0346cc7b-cbfd-477a-bc9d-f8d79d1b8925.png" width="300">  |
| Red crystal and Likuri merged with three enemies | <img src="https://user-images.githubusercontent.com/14016863/181251050-f224cee2-16e8-486c-bea7-2ab43c8702fa.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181251058-0cb5ec56-21f5-4309-8bfb-5764baecc69d.png" width="300">  |
| Short-fuse Boomie spawning | <img src="https://user-images.githubusercontent.com/14016863/181251374-bf42271c-096e-4f7a-bcce-e8d615fe0a1a.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181251383-d83f3ca8-c509-40f1-93f0-6f24a7b9f45b.png" width="300">  |
| Short-fuse Boomies idling (with one regular Boomie in the middle)  | <img src="https://user-images.githubusercontent.com/14016863/181251707-49d95912-68e8-4841-9b0d-ad2d1bff4269.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181251712-13031dd1-8934-4cf0-8cc8-5fea77cbf2a9.png" width="300">  |

### Logs & Dumps

[GS dumps on Google Drive](https://drive.google.com/drive/folders/1IzIL6t7AAZkSrKpOWEYTB9ev_5i_18iK?usp=sharing)

**Comment by refractionpcsx2** [comment]
Thanks for the detailed report, do you know if this is a regression or not?

**Comment by Igetin** [comment]
No idea, but user Daemyn already [reported the issue on the wiki](https://wiki.pcsx2.net/index.php?title=Klonoa_2%3A_Lunatea%27s_Veil&type=revision&diff=87129&oldid=87128) in 2016 using PCSX2 version 1.5.0-dev-1720-g5a63a62.

**Comment by refractionpcsx2** [comment]
okay probably not a regression then, thanks :)
