### ISSUE TITLE
[BUG]: Autosettings in GameDB don't fully fix graphics in Ratchet & Clank 3 and 4

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6722]
### Describe the Bug

Lighting is still broken, lf play without HW hacks.

### Reproduction Steps

Boot "Ratchet: Deadlocked" without HW hacks and go the first dread challenge, for example. R&C 3 has the same graphical issue.

### Expected Behavior

Fixed lighting as possibly as it can be.

### PCSX2 Revision

v1.7.3131

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-07-27 16-48-15](https://user-images.githubusercontent.com/90133207/181263338-c3881461-6309-4463-b903-10ed159f42a3.png)

### Emulation Settings

![Screenshot 2022-07-27 16-48-58](https://user-images.githubusercontent.com/90133207/181263572-9c1eaf91-12ac-4a1a-8792-069505109b47.png)

### GS Window Screenshots

With autosettings:
![Screenshot 2022-07-27 16-12-58](https://user-images.githubusercontent.com/90133207/181263658-27691b60-6f22-460c-8676-a2874fec7d3d.png)
With HW hacks:
![Screenshot 2022-07-27 16-16-37](https://user-images.githubusercontent.com/90133207/181263884-f061eaf8-1097-4101-b08f-bd11f351ee9e.png)

I set "Half Pixel Offset" to "Special (Texture - Aggressive)" and enabled "Merge Sprite". Only these settings can fully fix lighting.

**Comment by EvilPlayer1** [comment]
> Can you try without the widescreen patch and any cheats etc please?

![Screenshot 2022-07-27 17-08-34](https://user-images.githubusercontent.com/90133207/181268365-3fbea759-c5e9-4e8d-a81f-62080283cb79.png)
Same. Turned off everything.

**Comment by refractionpcsx2** [comment]
Hmm, did you load the game with a savestate? because that will put the widescreen patch back on, you need to boot the game normally with them disabled then load a save game from the memorycard.  Savestates retain the widescreen patch and will reapply it, regardless of if you turn it off.

**Comment by EvilPlayer1** [comment]
> Hmm, did you load the game with a savestate? because that will put the widescreen patch back on, you need to boot the game normally with them disabled then load a save game from the memorycard. Savestates retain the widescreen patch and will reapply it, regardless of if you turn it off.
> 
> I say this, because none of the dimensions etc changed.

No, I disabled savestates. I turned off settings, closed and opened again the emulator and booted the game with full boot.

**Comment by refractionpcsx2** [comment]
Okay no problem, just wanted to be sure.

Can you provide a GS Dump of that area please?

**Comment by EvilPlayer1** [comment]
> Okay no problem, just wanted to be sure.
> 
> Can you provide a GS Dump of that area please?

[Ratchet - Deadlocked lighting bug.zip](https://github.com/PCSX2/pcsx2/files/9200428/Ratchet.-.Deadlocked.lighting.bug.zip)

**Comment by refractionpcsx2** [comment]
I'm sorry, I'm not seeing the problem? Your hardware hacks *removed* the lighting, it didn't fix it.

Auto fixes: 
![image](https://user-images.githubusercontent.com/6278726/181287251-7fcce5ed-0b30-4206-a517-bfa19d7944a7.png)

Software (which is what I take as the source of truth here):
![image](https://user-images.githubusercontent.com/6278726/181287320-c6bfdad3-2adf-4375-adcd-d00d49f3bdd0.png)

Possible modification, Autoflush + HPO Special(Texture) + Round Sprite (Half) - seems to remove some gaps in the lighting
![image](https://user-images.githubusercontent.com/6278726/181287462-94ca5eb6-d42f-46db-962d-c552ad313cc8.png)


That's probably the best upscaling is going to get, but your version with all those hw hacks doesn't fix anything, it removes the lighting compeletely.

**Comment by EvilPlayer1** [comment]
Looks like with far textures it works different. I think with autosettings this looks worse than with HW hacks:
![Screenshot 2022-07-27 18-41-12](https://user-images.githubusercontent.com/90133207/181291546-aab9aaf0-bd0a-418e-b3a9-7b415f1c990a.png)
![Screenshot 2022-07-27 18-41-57](https://user-images.githubusercontent.com/90133207/181291742-3788bd92-61a6-4c04-9748-4bae01ada72f.png)
In 1080p it looks not bad, but in 5K impossible to fix lighting. The only way is to disable it to get the best image.

**Comment by refractionpcsx2** [comment]
Sorry but that's just the nature of upscaling. You're free to use custom settings to kill off the lighting, but that's not very faithful to the original, and I don't have any better solution at the moment, so it's best to stay as it is.

Thanks for the report.

**Comment by refractionpcsx2** [comment]
Some effects break down when upscaling, unfortunately, not much you can do about it at the moment.

**Comment by EvilPlayer1** [comment]
OK. I'll be waiting for next emulator updates
