### ISSUE TITLE
[BUG] newer PCSX2 Nightly Builds "Skipdraw Range and Texture Offsets" dont work anymore!: 

### ISSUE THREAD

**Issue by Snake356** [PCSX2/pcsx2#6726]
### Describe the Bug

You can no longer adjust "Skipdraw Range and Texture Offsets" under "Graphics", it is completely greyed out.

### Reproduction Steps

Go to "Hardware Fixes" and "Upsacling Fixes" and then you will see these fields are greyed out!

### Expected Behavior

I think this has been the case for a long time and these functions no longer work in the newer builds!

### PCSX2 Revision

v.1.7.3131

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Not a bug they can only be adjusted per game now.

**Comment by Snake356** [comment]
ok, but where can i change and save these settings per game?

**Comment by JordanTheToaster** [comment]
Right click a game and go to properties you can adjust settings there. In future use the Discord for support.

**Comment by Snake356** [comment]
Oh ok all right, I didn't know that, thanks for the info, I'll use Discord next time if I have a problem again. Thanks
