### ISSUE TITLE
[BUG]: Puzzle Quest - Challenge of the Warlords

### ISSUE THREAD

**Issue by SeventySixx** [PCSX2/pcsx2#6733]
### Describe the Bug

Flashing and corrupted graphic, here's a video of the issue:

**(WARNING FOR SENSIBLE PEOPLE:  FLASHING VIDEO)**

https://user-images.githubusercontent.com/83183868/181617246-6e1e4323-9f9d-4235-868c-a308cd292799.mp4

### Reproduction Steps

It used to work perfectly on 1.6, and on 1.7.0-dev-1292-g9822ef4181. No matter what settings  applied, the problem is present on latest builds. 
FMV not affected.

### PCSX2 Revision

visible on latest builds (es: PCSX2 Nightly - v1.7.3133)

### Operating System

Windows 10 (64bit)

### CPU

both Intel i7-4870 and AMD 5900x

### GPU

RTX2070

### GS DUMP
[gs_20220728213900_Puzzle Quest - Challenge of the Warlords_SLES-54995.zip](https://github.com/PCSX2/pcsx2/files/9213657/gs_20220728213900_Puzzle.Quest.-.Challenge.of.the.Warlords_SLES-54995.zip)

**Comment by Mrlinkwii** [comment]
dose it happen in SW mode and can you post a GS dump?

**Comment by refractionpcsx2** [comment]
Game is a timing nightmare.  Enabling GIF FIFO drastically reduces the flashing, but the "Press X to continue" on the start menu still flickers like crazy.

**Comment by SeventySixx** [comment]
> dose it happen in SW mode and can you post a GS dump?

Yeah, it happens on all rendering modes, no differences. I'm going to post the GS dump in a while

**Comment by refractionpcsx2** [comment]
A GS Dump is useless, it's a core timing problem.

**Comment by SeventySixx** [comment]
> A GS Dump is useless, it's a core timing problem.

ok, GS Dump posted above

**Comment by Goatman13** [comment]
Game is timing nightmare only if we care about timings. Here are patches to make game work until it is fixed properly. 

**SLUS_216.92**
crc = F5AF6C2E

> //Don't enable Intermittent GIF Mode.
> patch=0,EE,001F7E08,word,00000000

**SLES_549.95**
crc = DEEC6787

> //Don't enable Intermittent GIF Mode.
> patch=0,EE,001F9500,word,00000000

Patch don't work with old savestates.

**Comment by refractionpcsx2** [comment]
It impacts speed kinda greatly, but we might be able to split it up more than it currently does since that could be 1280-64

**Comment by SeventySixx** [comment]
@Goatman13 I confirm, with the patch it works great. Thanks!

**Comment by Meerkov** [comment]
> **SLUS_216.92** crc = F5AF6C2E
> 
> > //Don't enable Intermittent GIF Mode.
> > patch=0,EE,001F7E08,word,00000000

This doesn't work for me. I'm pretty sure I set the .pnach file up correctly, but it still flickers. I confirmed the CRC is correct.
Can someone add some additional instructions for this workaround?

**Comment by Goatman13** [comment]
Don't use old savestates. Patch affect code that is running very early in game. After patch is applied successfully you can create/load new savestates just fine.

**Comment by Meerkov** [comment]
No save states are involved. This is from fresh power on. Please provide the patch file you used and exact instructions of where to put it. This did not work for me.
