### ISSUE TITLE
[BUG]: (Persona 3 FES) Hashes with "xxxx-xxxx" instead of "xxxx-xxxx-xxxx" have trouble loading the texture

### ISSUE THREAD

**Issue by ACViper** [PCSX2/pcsx2#6736]
### Describe the Bug

Example: "f331606d5d604a5b-00006640.dds" won't load, but "531bb5f705944073-3b07777cc9cb6b9-00006654.dds" will.

This is because "f331606d5d604a5b-00006640" only has 2 sets of numbers, instead of 3 like in "531bb5f705944073-3b07777cc9cb6b9-00006654"

I already have tried enabling "GPU Palette Conversion" and setting "Texture Preloading" to None

### Reproduction Steps

d41fb8bd4eb48742-00005a00.dds and f331606d5d604a5b-00006640.dds have the same issue.

### Expected Behavior

Both textures to load successfully.

### PCSX2 Revision

1.7.3131.0

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 2700x

### GPU

RTX 3060

### GS Settings

![pcsx2-qtx64-avx2_i2QPleOuhh](https://user-images.githubusercontent.com/20104297/181658542-f4d48d6e-00b4-497f-a75d-f4f7311d0228.png)
![pcsx2-qtx64-avx2_RAjrVCPpLX](https://user-images.githubusercontent.com/20104297/181658552-1c6c433e-da1a-4180-850a-c384b02a4d97.png)

### Emulation Settings

![pcsx2-qtx64-avx2_AsHN9JAtbm](https://user-images.githubusercontent.com/20104297/181658575-0e8a7f46-364d-4d40-95e8-feeea8814634.png)
![image](https://user-images.githubusercontent.com/20104297/181658606-dea2f6fd-4757-4c46-874c-f5ac3cc8cb77.png)
![image](https://user-images.githubusercontent.com/20104297/181658632-2d4ccbb0-e371-4c4f-a4da-0a797f37636f.png)

### Logs & Dumps

![pcsx2-qtx64-avx2_j0b29ryE9B](https://user-images.githubusercontent.com/20104297/181658658-9c8280bd-4cac-4b2b-a0cd-74cb9bf0f95b.png)

**Comment by ACViper** [comment]
Solved the issue with textures generating bad hashes and not loading. If a .tmx file (original texture from p3fes) has "UsesPalette" set to "False" and "PaletteCount" set to "0," PCSX2 will generate a hash with "xxxx-xxxx," instead of "xxxx-xxxx-xxxx." So, I just modified the .tmx file and now it generated a proper new hash with "xxxx-xxxx-xxxx."

**Comment by ACViper** [comment]
This only fixe Persona 3 FES issue with getting bad hashes, which involves modding the actual game. This could be affecting other games that can't be easily modded.

**Comment by ACViper** [comment]
This only fixe Persona 3 FES issue with getting bad hashes, which involves modding the actual game. This could be affecting other games that can't be easily modded.

**Comment by The-Modding-Calculator** [comment]
A better description would be textures with a CLUT hash are not being replaced in Persona 3 FES. I am unaware if this issue affects other games but as @ACViper said it is a possibility. The texture f331606d5d604a5b-00006640 @ACViper spoke about can be found in the Velvet Room's fuse menu. I have attached a memcard with a save file and the replacement so anyone wishing to help can reproduce the issue.

To reach the fuse menu select the Journey. Then load the 2nd save file it should say 1/31 (Su) Tartarus. From there you should be able to spot a blue door on the left of the screen, interact with it. Now navigate though the menu with these options Fuse Personas->Normal Spread->Select any 2 personas. Now you should should see the L and R prompts at the top of the screen. To view the status text go back to the Normal Spread menu and press triangle on any of the personas you should see the Status text at the top of the screen.

![PERSONA 3 Screen SHOT](https://user-images.githubusercontent.com/103147643/181939624-d227d69d-1e8e-4392-a692-f4491fcf1db9.png)

![PERSONA 3 Screen SHOT 2](https://user-images.githubusercontent.com/103147643/181939963-461c2e58-57f1-4ff0-8ac1-1134399628d3.png)

![d41fb8bd4eb48742-00005a00](https://user-images.githubusercontent.com/103147643/181937466-baf921b6-9916-49f2-8668-54219d56097c.png)
[Primo.zip](https://github.com/PCSX2/pcsx2/files/9227122/Primo.zip)

**Comment by Gunlaus** [comment]
> Solved the issue with textures generating bad hashes and not loading. If a .tmx file (original texture from p3fes) has "UsesPalette" set to "False" and "PaletteCount" set to "0," PCSX2 will generate a hash with "xxxx-xxxx," instead of "xxxx-xxxx-xxxx." So, I just modified the .tmx file and now it generated a proper new hash with "xxxx-xxxx-xxxx."

How did you modify it?

**Comment by Kupo91** [comment]
Hi, I might have the same issue in Dragon Quest 8.

I colored all textures in this room. On this screenshot you can see that some of the textures do not load.

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230219213805](https://user-images.githubusercontent.com/41426906/219974413-5a1712af-db56-412f-a227-105115154d9d.png)

At first sight, it's related to textures which have a shorter hash name:

![Unbenannt](https://user-images.githubusercontent.com/41426906/219974422-3382fed5-cc3d-4763-bc5b-988d0e3dc186.PNG)

Here is a save state of this room:
[SLES-53974 (945FBF31).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/10777937/SLES-53974.945FBF31.01.p2s.zip)

(rev 4118)

**Comment by stenzek** [comment]
If it's using region textures, the filename/hash will have changed, and you'll need to re-dump.

Pretty sure the original issue here doesn't occur anymore, but if it does we can reopen.

**Comment by Kupo91** [comment]
What are region textures? The texture dumps are from last night though and I used the latest build

**Comment by SlyCooperReloadCoded** [comment]
I'm having this same issue again with Jonny Moseley Mad Trix.  The textures used for the loading screen are "3df1013021285ba6-80005e42" and "5c16b729152736ff-80005e42", only two hashes, and refuse to load.  These specific texture actually loading properly has been quite spotty.  Some updates they won't load, then I'll install an update and they'll load sometimes, I'll reboot and they'll load all the time, the next day an update is released and they no longer loads.  I'm currently on v1.7.4274 and they does not load, but did work before an update this morning.

All other texture dumps from this game have three hashes, like "74a1d520d52e95dd-bdd6134a24757e16-00005dd3", and have never ever had any issues.  It's just these two that have seen massive on-and-off difficulties loading.
