### ISSUE TITLE
[BUG]: Summoner Audio Bug (Regression)

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#6737]
### Describe the Bug

There is a bug with the audio emulation in the game Summoner that was not present in 1.6.0. It's as if something is going wrong with stereo separation where audio in the left or right channels continually pops in and out. It's difficult to describe but when you hear it it's very obvious that something is wrong, especially with headphones. There's no such problem in 1.6.0.

### Reproduction Steps

Start the game and listen to the music on the title screen. The issue creates various pops and audio artifacts during play as well.

### Expected Behavior

For the audio to play correctly, not cut out and pop, like it did in 1.6.0.

### PCSX2 Revision

v1.7.3137

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

RTX 3080

**Comment by Daxiel1992** [comment]
The THQ and Volition logos don't appear for me either. The instruments in songs will take turns cutting in and out randomly along with the left track for every sound cutting out for half a second in 5 second intervals.

**Comment by lightningterror** [comment]
@Zombeaver Can you narrow/track down which build introduced the issue?

**Comment by platyhooks** [comment]
The audio starts stuttering at the title screen in 1.7.2015. 
Works properly in 1.7.2014.

**Comment by refractionpcsx2** [comment]
Thanks for coming back to us @platyhooks I have implemented a fix, which you can try in #7258 once it has built.

You should be able to go in to the details of the windows (or linux if you're on that) checks at the bottom of the PR, then go to summary for download links :)
