### ISSUE TITLE
[BUG]: Broken fusion effect in Shadow Hearts

### ISSUE THREAD

**Issue by SilentHeII** [PCSX2/pcsx2#6742]
### Describe the Bug

When Yuri fuses into a demon, an after image effect is used to create an effect of intense stress. On Hardware mode, this effect is absent and the screen gets darker instead.

### Reproduction Steps

Enter a battle and fuse into any monster. This can be done as soon as the first enemy encounter by fusing into the Death Emporer.

### Expected Behavior

Expected effect:
![gs_20220730022253_Shadow Hearts_SLUS-20347](https://user-images.githubusercontent.com/29898818/181879942-671b6cf0-9f87-451e-a6dc-168da4deb242.png)

Broken effect:
![gs_20220730022449_Shadow Hearts_SLUS-20347](https://user-images.githubusercontent.com/29898818/181879956-21d9d1ab-2ffe-4611-b24e-d74410df2de9.png)

### PCSX2 Revision

Latest as of this post (1.7.3137)

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5900X

### GPU

GTX 1080ti

### GS Settings

![image](https://user-images.githubusercontent.com/29898818/181880013-a1e4b31a-a698-4456-b7b0-afc7ae38c1c0.png)
![image](https://user-images.githubusercontent.com/29898818/181880019-727b9143-aad1-4527-afde-1ac506aa7d76.png)

**Comment by Tyestor** [comment]
reset your rendering settings to the recommended settings and try again

**Comment by SilentHeII** [comment]
![image](https://user-images.githubusercontent.com/29898818/182008660-14752816-d3b9-460e-bdfb-458dacf64b7a.png)
![Shadow Hearts_SLUS-20347_20220730223516](https://user-images.githubusercontent.com/29898818/182008746-cd600f2f-6969-4a1a-8ff6-b96afb7192ef.png)

**Comment by Tyestor** [comment]
cycle renderers using debug > switch renderer. see if its only vulkan causing the issue. more importantly, see if it shows up in software renderer.

**Comment by SilentHeII** [comment]
As stated in the original post, this is a hardware mode issue regardless of renderer. The working screenshot was taken in software mode. The effect works as intended only in software
![Shadow Hearts_SLUS-20347_20220731030725](https://user-images.githubusercontent.com/29898818/182016265-8ffa88f1-3c26-4272-96a2-877881509003.png)
[Shadow Hearts_SLUS-20347_20220731030725.zip](https://github.com/PCSX2/pcsx2/files/9228272/Shadow.Hearts_SLUS-20347_20220731030725.zip)

.

**Comment by Tyestor** [comment]
Confirming issue is present in that GS dump. I've tried every game fix, hardware fix and upscaling fix and a bunch of different clamping and rounding settings in combination with your GS Dump and the only setting that has any effect is disable safe features, which gets some of the effect to appear in D3D11/OGL. Will probably need a dev to look into this.
