### ISSUE TITLE
[BUG]: "Hide Cursor in Fullscreen" no Hide on Mac

### ISSUE THREAD

**Issue by darkuser89** [PCSX2/pcsx2#6744]
### Describe the Bug

The mouse pointer does not disappear on full screen

Tested with Vulkan and Metal 

### Reproduction Steps

Select "Hide Cursor in Fullscreen" 
Start a Game 
Start Fullscreen
Wait Cursor no Hide

### PCSX2 Revision

v1.7.3140

### Operating System

macOS (Monteray)

**Comment by Mrlinkwii** [comment]
is this still an issue on latest nightly?

**Comment by refractionpcsx2** [comment]
No response and this was a Qt thing where this didn't exist, so closing.
