### ISSUE TITLE
[BUG]: FMV Bug with Bloody Roar 3 (Regression)

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#6751]
### Describe the Bug

There's an issue with FMVs in Bloody Roar 3 that was not present in 1.6.0. It's as if the video is being squashed into the upper half of the screen with the lower half corrupted. If HW rendering is used the bottom half is a flickering mirrored version of the top half. It's still wrong with Software FMVs, just corrupted rather than duplicated.

### Reproduction Steps

Start the game and watch the intro FMV. The issue is present both in HW and SW.

### Expected Behavior

For the FMVs to display normally like they did in 1.6.0.

### PCSX2 Revision

1.7.3146

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

RTX 3080

### GS Window Screenshots

1.7.3:

![image](https://user-images.githubusercontent.com/24979172/182033124-8bdd71e0-3c3b-4f8b-8105-1310b3ae8993.png)

1.6.0:

![image](https://user-images.githubusercontent.com/24979172/182033134-005c5d84-3295-4e21-aaaf-adff819c77ad.png)

**Comment by ps1freak26** [comment]
Try turning screen offsets on.

**Comment by Zombeaver** [comment]
Oh that actually worked! I'm not sure if this needs to be closed or not, but that does fix the issue here.

**Comment by refractionpcsx2** [comment]
What is your deinterlacing set to?

**Comment by Zombeaver** [comment]
With the patch, none.
