### ISSUE TITLE
[BUG]: Controller, switching L2/R2 with right analog stick UP/DOWN not working properly.

### ISSUE THREAD

**Issue by stoniemahonie** [PCSX2/pcsx2#6754]
### Describe the Bug

Im using a Dualshock 4 and play Need for Speed Hot Pursuit 2. Switching R2 with right Analog up and L2 with right analog down results in both functions of L2/R2 getting triggered ingame when moving right analog down. When moving right analog up, nothing happens (with my xbox controller the oppsite happens bc the right analog has no perfect deadzone anymore and in its natural stance, it is a little bit on the downside, so i move the analog stick up and both things get triggered and moving down does nothing. The following is all based on my Dualshock 4 controller. This is the control layout for this game:

![switch](https://user-images.githubusercontent.com/13390608/182039166-7c68d604-143f-4649-a47a-04719e124c4e.png)

That way, i can use the triggers as gas/brake in this game. And the Analog UP/DOWN becomes the functions that are on R2/L2. Just to explain it, you drive a car as a cop and can call with R2 a helicopter and with L2 a roadblock/spike strips. When i pull the Analog stick up, nothing happens. And if pull it down, both gets activated/triggered. I tried two different controllers (Dualshock 4 and xbox one) and exerimented with the "analog deadzone" setting to no avail. Furhtermore, i looked at "padtest.elf" to look if there is something suspicous with this configuration but all looked ok "to me". Deadzones where perfectly fine. Only thing i noticed is the following, with the controls switched, see the red circle and the value next to it:

 
![padtest](https://user-images.githubusercontent.com/13390608/182040625-a4e80efa-195c-44b4-9ee0-e0b57f5947ec.png)
The R2 has this "highlight icon" when something is pressed to highlight that it is pressed. So when i move the right analog down, the highlight goes over to L2 and when i let it go it goes back to R2 without moving it, as u can see the value is zero. When you start padtest fresh the highlight is also not there, but as soon as you use the right analog stick the highlight will always be at R2 when released, even with the value "0".

And here is a screenshot with the default controls:

The Highlight goes completely away on R2/L2 when released.
![padtest_default_controller_layout](https://user-images.githubusercontent.com/13390608/182040871-85aff2ee-74ae-48fd-8911-14ee9ff02fc4.png)

### Reproduction Steps

Configure the control pad as in the pcsx2 screenshot with only the red marked positions switched. Start Need for Speed Hot Pursuit 2. Use the "You're the cop mode" in 1 or 2 Player mode and start. Follow the speeding cars immediatly and use circle to target one. Then move the right Analog Stick up to call a helicopter for assistance or right analog down to call a roadblock/spike strips. You can see in the top right corner what has been activated.

If you move the right analog stick up and hold it, you can see that the spike strips/roadblock is activated, but when you release the analog stick, the helicopter will also get activated or vice versa. In a natural motion u just move the analog stick quick up or down, and when the stick comes back in the natural position, it will activate the other function as well. It just happens so fast, that it looks like both got triggered at the same time. And i guess the reason why it does, is kinda explained above. Maybe more deadzone control options could work around this problem or i'm maybe lucky and this is fixable.

### Expected Behavior

Correct execution of the mapped inputs without triggering other mapped inputs.

### PCSX2 Revision

1.7.3140

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3700X

### GPU

GTX 1060

**Comment by Mrlinkwii** [comment]
Can this be rechecked on latest nightly?

**Comment by JordanTheToaster** [comment]
Unable to reproduce with the given steps.
