### ISSUE TITLE
Disable PCSX2 First Time Configuration if existing installation is detected?

### ISSUE THREAD

**Issue by Trevonn** [PCSX2/pcsx2#676]

**Comment by ssakash** [comment]
What existing installation ? Please try to be a little informative.

**Comment by Trevonn** [comment]
If for example you download the latest git build and then overwrite that with a newer git build the First Time Configuration will appear when you open PCSX2

**Comment by ssakash** [comment]
Then don't replace the portable.ini file in the pcsx2 directory and problem solved.

**Comment by Trevonn** [comment]
That works thanks
