### ISSUE TITLE
[BUG]: Vulkan errors in games

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6768]
### Describe the Bug

When I play games, I can suddenly get Vulkan error after 15-30 minutes. I never got these errors before. Maybe it's new Nvidia driver, which broke everything, because I have broken graphics on rpcs3 and in other games.

### Reproduction Steps

Boot Ratchet or Jak game on latest Nvidia driver 516.59 (?)

### Expected Behavior

No Vulkan errors during gameplay.

### PCSX2 Revision

v1.7.3153

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-08-02 16-47-14](https://user-images.githubusercontent.com/90133207/182390508-d4743fbb-ebc5-448d-9fed-cc62802d50dd.png)
![Screenshot 2022-08-02 16-47-24](https://user-images.githubusercontent.com/90133207/182390524-192e51ac-62ec-4493-b07a-b6aece59c07e.png)

### Emulation Settings

![Screenshot 2022-08-02 16-49-18](https://user-images.githubusercontent.com/90133207/182390950-b5d5330e-cf37-421f-8fab-7d0cdcbaeadd.png)
![Screenshot 2022-08-02 16-49-25](https://user-images.githubusercontent.com/90133207/182390968-e27d2d89-72c3-4bf9-8ad0-3b9ded54f331.png)
![Screenshot 2022-08-02 16-49-30](https://user-images.githubusercontent.com/90133207/182390971-d3e0b550-c15d-499a-9406-af5f1bf1a0be.png)

### GS Window Screenshots

![Screenshot 2022-08-02 16-28-06](https://user-images.githubusercontent.com/90133207/182391073-71d6770b-9916-42b7-bf6d-fc3e8859a93e.png)

**Comment by lightningterror** [comment]
What if you lower upscaling?

**Comment by EvilPlayer1** [comment]
I tried to change to 4K. Played for about an hour without with no errors. When I changed back to 5K, I also played without errors. Looks like this error is random. But the most interesting fact is, that I played without errors earlier.

**Comment by EvilPlayer1** [comment]
@lightningterror in GS settings disappeared "conservative buffer allocation". this option has always given me problems. Should I turn it off in .ini file?

**Comment by refractionpcsx2** [comment]
There is no such option anymore.

**Comment by EvilPlayer1** [comment]
I see "conservative_framebuffer = true". Is that not it?

**Comment by refractionpcsx2** [comment]
It isn't doing anything.

**Comment by EvilPlayer1** [comment]
So, I must buy new videocard? This situation is same as with "conservative buffer allocation" turned on. I remember how I got random 1 sec microfreezes or even full emulator crash just like "alt+f4" with this option. Now it's all the same. But before I could disable it and play without problems.

**Comment by refractionpcsx2** [comment]
The new system should use less memory than conservative buffer did, so it should be even better off. However doing 8x Native on your 1660 is asking a lot... you should be around 3x or 4x.

**Comment by EvilPlayer1** [comment]
I don't know how I can get errors, if max GPU usage in 5K is 72% and memory usage usually less than 2 GB. Again tested R&C 2
