### ISSUE TITLE
[BUG]: 18 Wheeler: American Pro Trucker Audio Bug (Regression)

### ISSUE THREAD

**Issue by Zombeaver** [PCSX2/pcsx2#6769]
### Describe the Bug

I don't know if this bug is related to #6737 or not, but it seems somewhat similar. The audio periodically cuts out, or will play a super high pitch noise, and sometimes the character voices will shift way up in pitch. This didn't happen in 1.6.0. I would actually say the issue is more severe here than it is in Summoner (if it's the same issue) rendering the game basically unplayable.

### Reproduction Steps

Start the game, sit on the character selection for a brief amount of time or start playing and play briefly and the bug should appear.

### Expected Behavior

For the audio to play normally, like it did in 1.6.0.

### PCSX2 Revision

v1.7.3153

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

RTX 3080

**Comment by refractionpcsx2** [comment]
I know about this bug, not sure how to fix it right now, game does stupid stuff..

**Comment by Zombeaver** [comment]
Do you think it has any relation to #6737 ? I didn't experience the awful high pitch noise in that one but it was similar in that occasionally only a single left or right channel will drop out.

**Comment by refractionpcsx2** [comment]
probably not. Not beyond being an SPU2 problem, anyways.

**Comment by Mrlinkwii** [comment]
How is this on nightly :)

**Comment by refractionpcsx2** [comment]
Still broken

**Comment by Meerkov** [comment]
+1 Almost all audio dropped out within a few seconds of starting the first level.
