### ISSUE TITLE
Lily pad glitch/oversight

### ISSUE THREAD

**Issue by tsunami2311** [PCSX2/pcsx2#677]
So I recently made config file to load for lilypad instead of doing it all over and over. which each update

 Files are saved as "Lilypad config files" by defualt, but when one goes to load the config file there is no "lilypad config files" one has to switch type to "all files" to see the save.

So the save dont actual save it as "lilypad config files" cause according to windows it is saved as .file, and i thinking it been like for quiet while cause i think i reported this once before year 2 ago in the thread too, might sound like irrelevant issue, but it should be simple fix no?

Test with current git and 1.21 stable build, they all save "lilpad config files" as .files and no amount of switch from "all files" or "lilypad config files" file types make it save it as correct file type, the saves can be loaded, but there all .files and "all files" must be selected

**Comment by bositman** [comment]
Tested latest GIT, lilypad saves files as LilyPad.lily by default without needing to switch to all files (save as by default is on lilypad config files), also load bindings also looks for a LilyPad.lily file by default and file type is also by default on 'lilypad config files' ).

**Comment by tsunami2311** [comment]
load binds do look for lilypad config files by default, thing is  save binds defaults to saving as lilypad config files too, but when I actual it saves a .file is created which results in the default load binds finding nothing  (lilypad config files). the actual save can be loaded as .file it just saved in wrong format.

with what u said i tested a build on computer that never had pcsx2 put on it and it saves a correct format. so how are what is wrong then

**Comment by tsunami2311** [comment]
I guess this can be closed, I went to save config file, changed type to all files and put .lily  at end of the  and it see it as .lily files but still wont save incorrect format with "lilypad config files" selected

**Comment by Pistachioman** [comment]
I think it's a bug, because you shouldn't have to add the extension manually.

**Comment by tsunami2311** [comment]
that is the after what bositman said i tested it on another pc that never had pcsx2 on it and it saved the binds as .lily and not .file so if it bug it is  random bug

**Comment by ramapcsx2** [comment]
Sounds a lot like an old ini entry. It's okay to keep it closed.

**Comment by tsunami2311** [comment]
that is the thing every time i download new git build i delete all files/folders in pcsx2 dir

I have 2 directory for pcsx2
PCSX2 Stable
PCSX2 Git

Both have content deleted any time i  update them, short of maybe shader dir if i using shader build that isnt in the gits/stable build

**Comment by bositman** [comment]
Can you replicate it in any other PC? It sounds to me like some kinda windows file association mess up that happens some times

**Comment by tsunami2311** [comment]
that is the other pc i tried it on work correct, amnd there is no file assication for said .lily under windows 7 or in the regsitry that i can find

**Comment by tsunami2311** [comment]
ok i just did more tests, IF you  defualt name  for the save which is LilyPad and dont change it it saves as .lily, but once you change the name it no longer saves as .lily

Even if you go back to the defualt name is LilyPad it remains broke

Pistachioman is right is is bug

**Comment by bositman** [comment]
Let me phrase this correctly because your report is confusing.

How to trigger the bug:
1) On the save bindings dialogue, type a filename and delete the .lily extension
2) A file with no extension will be created
3) When trying to load bindings, the file will not show up since by default the plugin is looking for files with the .lily extension. If you select all files you can load it fine.

So the solution would be to force apply the .lily extension even when the user deleted it while on the save bindings screen.

**Comment by Pistachioman** [comment]
Yes, that's the gist of it.

**Comment by bositman** [comment]
Fixed by #681, thanks @Pistachioman

**Comment by tsunami2311** [comment]
@bositman 
Yah i am not the best person to explain things, But i am glad you understood it
