### ISSUE TITLE
[BUG]: Graphics are broken on the second stage of Biker Mice from Mars (USA) 

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6773]
### Describe the Bug

Halfway through the second stage you get to a beat em up section. The screen is full of graphical garbage and the enemy health bars are grey instead of red. 

![Biker Mice from Mars_SLUS-21578_20220803220102](https://user-images.githubusercontent.com/96800307/182603826-bdedbd70-6e36-4620-974c-74b4f59eaeb4.png)

### Reproduction Steps

Play stage 2 of the game until you get to the beat em up section.

### Expected Behavior

The screen shouldn't be full of garbage. The health bars should be red instead of grey.

### PCSX2 Revision

pcsx2-v1.7.3137-windows-64bit-AVX2-

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

All settings default. 

### Emulation Settings

All settings default

### GS Window Screenshots

![Biker Mice from Mars_SLUS-21578_20220803220102](https://user-images.githubusercontent.com/96800307/182604484-1b6d1ebc-ad0e-4df1-a583-013983f130db.png)

![Biker Mice from Mars_SLUS-21578_20220803220106](https://user-images.githubusercontent.com/96800307/182604493-98add741-3d69-4b41-be0f-2f9bc565a794.png)

![Biker Mice from Mars_SLUS-21578_20220803220111](https://user-images.githubusercontent.com/96800307/182604502-f87ef470-18eb-44a6-8d8f-adab8222a13c.png)

**Comment by Mrlinkwii** [comment]
Can you post a gs dump?

**Comment by drachenschanze** [comment]
Is this correct?

[Biker Mice from Mars_SLUS-21578_20220803222806.zip](https://github.com/PCSX2/pcsx2/files/9251295/Biker.Mice.from.Mars_SLUS-21578_20220803222806.zip)
