### ISSUE TITLE
[BUG]: Corrupted Textures in .hack//fragment

### ISSUE THREAD

**Issue by Tellilum** [PCSX2/pcsx2#6778]
### Describe the Bug

Corrupted textures appear when the camera is completely zoomed out
![Screenshot (57)](https://user-images.githubusercontent.com/59491721/182949665-5aa79f32-8f0d-4060-860b-2374e87c520a.png)

### Reproduction Steps

1. Configure settings as shown in attached image, (Gpu does not matter)
2. Head to Δ 脈動する  過越しの  碧野 in-game (Bursting Passed Over Aqua Field), alternatively create a new character as the tutorial will take you to this area
3. Once control has been given to you, zoom the camera out with the Right-Stick completely and walk around, eventually the textures will appear
![image](https://user-images.githubusercontent.com/59491721/182949804-d5367575-9817-4a09-96e5-ee9de0b9d452.png)

### Expected Behavior

Uncorrupted textures are expected, the issue seems to only occur when full mipmaps are turned on when upscaling.

### PCSX2 Revision

v1.7.3161

### Operating System

Windows 10 (64bit)

### CPU

i5-9400

### GPU

RX 570

### Emulation Settings

![image](https://user-images.githubusercontent.com/59491721/182950128-0d94b785-92db-46b3-a6a6-7c136b98bb4c.png)

### GS Window Screenshots

![Screenshot (57)](https://user-images.githubusercontent.com/59491721/182950188-a95b6d84-63eb-4135-9a2b-0e1f0559db4c.png)

### Logs & Dumps

[dot hack - Fragment_SLPS-25527_20220804135132.zip](https://github.com/PCSX2/pcsx2/files/9263292/dot.hack.-.Fragment_SLPS-25527_20220804135132.zip)

**Comment by Tellilum** [comment]
if you happen to have a translated version of Fragment (Tellipatch or Coldbird) the issue occurs there as well. I used a clean copy of the game to verify it wasn't an issue with the translation patch.

**Comment by Oymat** [comment]
No longer exists, i just tested it on latest pcsx2

**Comment by Oymat** [comment]
Vulkan: 
![image](https://user-images.githubusercontent.com/122278577/213885355-77f8b803-768f-41ae-bb15-190db1a09e1b.png)

**Comment by refractionpcsx2** [comment]
confirmed, thanks for retesting.
