### ISSUE TITLE
[Feature Request]: Which PCSX2 version for Linux has DualShock 4, and DualSense support, respectively

### ISSUE THREAD

**Issue by stanlane** [PCSX2/pcsx2#6795]
### Description
* Big PCSX2 emulator update: Dark Theme, DualShock 4 and DualSense Support, Improved UI - https://game-news24.com/2022/05/23/big-pcsx2-emulator-update-dark-theme-dualshock-4-and-dualsense-support-improved-ui/
* Sony Publishes An Official Linux Driver For PlayStation 5 DualSense Controllers - https://www.phoronix.com/news/Sony-HID-PlayStation-PS5

Which https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily build support the DualShock 4, and the DualSense controller, respectively?

### Reason

Please give me a link to the version history.

### Examples

.

**Comment by stenzek** [comment]
We have nothing to do with those packages. Talk to the packager instead, or use the appimage provided on pcsx2.net.

**Comment by stanlane** [comment]
> We have nothing to do with those packages. Talk to the packager instead, or use the appimage provided on pcsx2.net.

Thanks.
