### ISSUE TITLE
[Feature Request]: Processor independence

### ISSUE THREAD

**Issue by noabody** [PCSX2/pcsx2#6798]
### Description

```cmake/BuildParameters.cmake``` has parameter: ```set(ARCH_FLAG "-march=native")``` in which GCC/other? will not generate processor independent code.

Recommend use ```-march=x86-64-v2``` for SSE4.1 requirement or possibly ```-march=nano-3000```

### Reason

Will allow compiled program to work on multiple platforms with SSE4.1 but not cause ```Illegal Instruction: Core Dump```

### Examples

```set(ARCH_FLAG "-march=x86-64-v2")```

**Comment by noabody** [comment]
[x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3 ](https://www.phoronix.com/news/GCC-11-x86-64-Feature-Levels)
[‘nano-1000’: VIA Nano 1xxx CPU with x86-64, MMX, SSE, SSE2, SSE3 and SSSE3 instruction set support. (No scheduling is implemented for this chip.)](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)

**Comment by noabody** [comment]
Thank you.  Since compilation fails without minimum SSE4.1, I use this to modify:
```
perl -pi -e 's/-march=native/-msse4.1/gi' cmake/BuildParameters.cmake
```

**Comment by tellowkrinkle** [comment]
`-DDISABLE_ADVANCE_SIMD=ON` is the flag you're looking for, and what the CI uses
