### ISSUE TITLE
[Feature Request]: Quiet Volume on a number of games compared to hardware

### ISSUE THREAD

**Issue by kanjieater** [PCSX2/pcsx2#6802]
### Description

Try out Ayakashibito or Phantom of Inferno, Japanese Visual novels. Even at max volume they are 10 to 20db quieter than hardware. 

One solution would be to just raise the available gain limit to some higher arbitrary number setting that as the 100%. However, given that even some games on hardware run quieter, Phantom of Inferno for instance is pretty quiet, you could allow for ~200% on a per game configuration.

### Reason

This way even if a game is unnaturally quiet it could be corrected. This would fix the "bug", if you will, and also be a nice enhancement over hardware.

### Examples

VLC has this feature, various audio apps like Castbox, Voice (android audiobooks), etc.

**Comment by jjw410** [comment]
I'll add, I think having a toggle to make sure "boosted audio" is checked before being able to increase it would be a good way to make sure no one accidentally blows their eardrums out the side of their head.

**Comment by stenzek** [comment]
It's still dependent on the system/overall volume. So all you'd get in such a case would be a ton of clipping ;)

**Comment by kanjieater** [comment]
> It's still dependent on the system/overall volume. So all you'd get in such a case would be a ton of clipping ;)

In general this is true - if you boost, a source that's already at peak volume level, you'd have this issue.

However if the audio is under volume, like in it is currently in the case of PCSX2, you won't get clipping even if you were to boost. I know this because currently I'm feeding PCSX2 into Voice MEETER Banana with a 7.5 decibel boost on input AND a 12 db boost on output and it's never clipped once. This is due to the app itself being under what the original games volume was at. 

Then there are apps like VLC that generally allow you to boost, and you unless your listening to a consistently loud audio source that's constantly peaking you won't get clipping from some boosting. Though naturally it opens up the possibility to clip. This can be avoided by using compression too (though that also changes the original source balance levels and is probably out of scope for this)

**Comment by stenzek** [comment]
There isn't any normalization or post-processing going on in our audio output. It's just signed 16-bit samples, all it takes is a single frame to be near max amplitude and it'll clip with a volume boost.

For very quiet games, I can see the potential advantages, but that's assuming that **everything** in the game isn't anywhere near max volume. Since the SPU is additive mixing, if you have a bunch of effects running at once, it's easy for it to get up there.

**Comment by kanjieater** [comment]
> There isn't any normalization or post-processing going on in our audio output. It's just signed 16-bit samples, all it takes is a single frame to be near max amplitude and it'll clip with a volume boost.
> 
> For very quiet games, I can see the potential advantages, but that's assuming that **everything** in the game isn't anywhere near max volume. Since the SPU is additive mixing, if you have a bunch of effects running at once, it's easy for it to get up there.

Interesting. Have you tried comparing it to a physcial ps2? As I mentioned, i'm finding the volume to be around 20db lower. Some others had mentioned it here, though I'm not sure if anyone there was using hardware as reference : https://forums.pcsx2.net/Thread-Anyone-notice-PCSX2-1-7-0-sound-is-quieter

**Comment by stenzek** [comment]
You can't really compare it directly, unless your PC is set to 100% volume.

If the SPU generated, say, +32600, raising the volume by 1.25x would clamp to 32767. Even though that amplitude gets lowered when the PC's volume is applied and the actual value sent to the DAC isn't 32767, you've still clipped, because it's clamped when it comes out of PCSX2, well before the main mixer adjusts it.

**Comment by kanjieater** [comment]
> You can't really compare it directly, unless your PC is set to 100% volume.
> 
> If the SPU generated, say, +32600, raising the volume by 1.25x would clamp to 32767. Even though that amplitude gets lowered when the PC's volume is applied and the actual value sent to the DAC isn't 32767, you've still clipped, because it's clamped when it comes out of PCSX2, well before the main mixer adjusts it.

For the record, that is what I did. Both my PC with Pcsx2 as well as my physical PS2, went through the same audio interface at maximum volume when I tested this.

**Comment by refractionpcsx2** [comment]
It also depends on the game, same games (like burnout 3) are just slightly clipping (in 1.6 it was a clipping nightmare) and other games are far too quiet. I'm not sure what we've done wrong to cause such a variation, unless we're doing volume linearly and it shouldn't be linear, or something.

**Comment by Mrlinkwii** [comment]
how is this on latest nightly :)

**Comment by Ziemas** [comment]
I looked at these games while working on #10084 and they don't seem to be any quieter than other games (neither before nor after my changes)

I obviously didn't compare to hardware, but I don't see why it would be very different.

**Comment by Ziemas** [comment]
My point was that at this point the lower output is a choice that affects all games equally rather than a bug. And the example games in this issue do not seem to exhibit any unusual behavior.

**Comment by mirh** [comment]
But could this quirk (is it the things discussed in #3787?) be responsible for the reported bug here?
I guess "on a number of  games" may imply that only a specific selection of games is troubled.. but that may also just have meant that OP has only two games in their hands to test.
