### ISSUE TITLE
[BUG]: Madden player portrait textures keep dumping new textures of the same texture

### ISSUE THREAD

**Issue by msweeets** [PCSX2/pcsx2#6805]
### Describe the Bug

in all PS2 versions of Madden anytime you try to replace a player portrait texture the game keeps dumping new versions of the same texture anytime you back out into the main menu and go back into the view rosters section thus rendering your replacements useless.

### Reproduction Steps

go to any player portait in the "view rosters" section and dump then replace it with whatever you want to replace it with
after backing out to the main menu go back to view rosters and you'll see the game then creates a new texture dump of the same texture you just replaced.

### Expected Behavior

for the replaced textures to remain intact after replacing the dumped texture

### PCSX2 Revision

v1.7.3185

### Operating System

Windows 11

### CPU

Ryzen 5 5600H

### GPU

GTX 1650

**Comment by MrCK1** [comment]
This is part of the normal behavior of texture dumping. Duplicates are common in most games.

You will need to sort out the textures you are looking for manually.
