### ISSUE TITLE
[BUG]: Crashing while playing Just Cause 1, Europe region.

### ISSUE THREAD

**Issue by KianmehrKM** [PCSX2/pcsx2#6811]
### Describe the Bug

Hi, I was playing Just Cause 1 in PCSX2 Nightly v1.7.3187, the game in intensive actions (like shootings with lots of police, you get the idea), crashes and the console shows GS Memory Allocation Failure.
A screenshot is here, while I literally loaded in the game, pressed X to start the mission and it crashed.
(Sorry I couldn't attach it here weirdly, it failed so here's a MEGA link instead):
https://mega.nz/file/HYIiFaJR#xusqCdE-aZVvJ2D_kD379t97HyDqpSFL02c6bDdOfoY

### Reproduction Steps

For reproducing the behavior, you may have to be in a mission, mostly in shooting scenes, and while cruising around and shooting people, the emulator simply crashes.
Sometimes while even not doing anything, while being on the motorcycle only also crashes the game (sometimes).
Even so by walking around the game, it causes it to crash.

### Expected Behavior

I expected the game to run okay and normal, but while it happens, it crashes and the audio and everything goes away.

### PCSX2 Revision

PCSX2 Nightly v1.7.3187

### Operating System

Windows 11

### CPU

Intel Core i5 10210U

### GPU

Intel UHD Graphics for 10th Generation Processors

### GS Settings

![image](https://user-images.githubusercontent.com/85435062/183650390-41ab192f-39ab-4780-a65d-a96289714d45.png)
![image](https://user-images.githubusercontent.com/85435062/183650448-4c09a4ac-505a-44ef-998a-361224c52a33.png)
![image](https://user-images.githubusercontent.com/85435062/183650541-16703fe9-7288-417e-89a0-1e764d7e75e7.png)
![image](https://user-images.githubusercontent.com/85435062/183650588-998d3a51-ad71-45f1-bbd6-47ca00213364.png)
I also use D3D12.

### Emulation Settings

![image](https://user-images.githubusercontent.com/85435062/183650642-cd62c6ec-dbdb-4483-bbf7-148c0ba8dcd7.png)

### Logs & Dumps

[crash-2022-08-09-17-50-07-802.zip](https://github.com/PCSX2/pcsx2/files/9291008/crash-2022-08-09-17-50-07-802.zip)

**Comment by JordanTheToaster** [comment]
I'd suggest trying to update your graphics drivers as the game is fine for me.

![image](https://user-images.githubusercontent.com/80843560/183673535-523a5bda-1f18-44e2-ace2-8bfe4dc9ef33.png)

**Comment by KianmehrKM** [comment]
As per checking my Intel NUC10i5FNK's GPU driver, it is indeed up to date. I've also checked it with Windows Update and Intel's Driver & Support Assistance application.

**Comment by JordanTheToaster** [comment]
Only other suggestion I can make for you is use the DX11 Renderer otherwise this might just be Intels iGPUs being funny.

**Comment by KianmehrKM** [comment]
I will try and will report in a bit.

**Comment by KianmehrKM** [comment]
So I hit "New Game", just for fun and it decided to die, without any error whatsoever.
LOG:
[crash-2022-08-09-19-23-11-561.zip](https://github.com/PCSX2/pcsx2/files/9291904/crash-2022-08-09-19-23-11-561.zip)

**Comment by refractionpcsx2** [comment]
That crash happened somewhere in d3d11, rather than the emulator.

**Comment by KianmehrKM** [comment]
So, is D3D corrupted?

**Comment by refractionpcsx2** [comment]
I dunno about that, could be your GPU drivers are.

**Comment by KianmehrKM** [comment]
I will reinstall my GPU drivers, redo everything again with the same D3D12, but I might do it tomorrow due to private reasons.
Thanks for now.

**Comment by refractionpcsx2** [comment]
If you need further help, please visit our discord, thanks.
