### ISSUE TITLE
[BUG]: Cutscenes are broken with hardware rendering in The Sniper 2 (Europe)

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6813]
### Describe the Bug

All cutscenes have graphical garbage on the right side of the screen with hardware renderers. Software looks fine.

![Sniper 2_ The_SLES-51623_20220810072820](https://user-images.githubusercontent.com/96800307/183765313-7d125e07-a974-4aae-ae7b-f129faf943a8.png)

![Sniper 2_ The_SLES-51623_20220810072933](https://user-images.githubusercontent.com/96800307/183765341-ccf0e038-da90-4f3e-9cfa-06cbf5db54e5.png)

### Reproduction Steps

Play the game with any hardware renderer and watch the opening cutscene.

### Expected Behavior

The cutscene shouldn't be broken. 

### PCSX2 Revision

pcsx2-v1.7.3137-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

All settings default

### Emulation Settings

All settings default

### Logs & Dumps

[Sniper 2_ The_SLES-51623_20220810072933.zip](https://github.com/PCSX2/pcsx2/files/9294777/Sniper.2_.The_SLES-51623_20220810072933.zip)

**Comment by drachenschanze** [comment]
Chaos Field - New Order (Japan) has the same problem.

![Capture](https://user-images.githubusercontent.com/96800307/185999913-e6eb2b4e-b103-4603-96ef-543af94679ac.PNG)

[Chaos Field - New Order_SLPM-66176_20220823050727.zip](https://github.com/PCSX2/pcsx2/files/9396970/Chaos.Field.-.New.Order_SLPM-66176_20220823050727.zip)

**Comment by drachenschanze** [comment]
Disney's Chicken Little - Ace in Action (USA) has the same problem.

![Disney_s Chicken Little - Ace in Action_SLUS-21420_20220826055736](https://user-images.githubusercontent.com/96800307/186757339-b1a9d4c7-c403-40b7-bbe4-6839a777fff5.png)

**Comment by Mrlinkwii** [comment]
@drachenschanze  can you try Chicken Little on #6894 ?
