### ISSUE TITLE
[BUG]: [wxWidgets][Crash] The emulator crashes on booting ISO when Thrustmaster T300RS is plugged in

### ISSUE THREAD

**Issue by Recuch** [PCSX2/pcsx2#6819]
### Describe the Bug

When the user tries to boot the ISO file while the Thrustmaster T300RS steering wheel is plugged in, the emulator crashes and shuts down without any prompt message. The issue occurred on the wxWidgets version. Reproduction rate 5/5
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/9304120/emuLog.txt)

### Reproduction Steps

1. Plug in Thrustmaster T300RS to your computer
2. Launch the PCSX2 emulator
3. Configure the Thrustmaster T300RS via Config>USB Settings
4. Select ISO with any game via CDVD>ISO Selector>Browse
5. Boot ISO with System>Boot ISO
6. Observe

### Expected Behavior

The emulator boots up without crashing.

### PCSX2 Revision

v1.7.3192

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Duplicate #5458
