### ISSUE TITLE
[BUG]: Falling through the floor in Michigan: Report from Hell

### ISSUE THREAD

**Issue by macmmm81** [PCSX2/pcsx2#6821]
### Describe the Bug

The player falls through the floor on the second level in the Library. This is a regression - the same bug does not occur in v1.6.0.

### Reproduction Steps

Progress through the game until Library and go to the second floor using stairs.

### Expected Behavior

Player should not fall through the floor.

### PCSX2 Revision

v.1.7.3191

### Operating System

Windows 10 (64bit)

### CPU

i7-6700k

### GPU

GTX 970

### GS Settings

3x native + widescreen patches, no hw hacks

### Emulation Settings

All the defaults

### GS Window Screenshots

v1.6.0
https://user-images.githubusercontent.com/39221755/184174521-c59f1097-ade2-4851-8e04-3ef2e9ffdc32.mp4

v1.7.3191
https://user-images.githubusercontent.com/39221755/184173344-759f1688-8464-44d9-a91d-f77d7b1479f6.mp4

### Logs & Dumps

Advise if any logs / savestates needed.

**Comment by refractionpcsx2** [comment]
There's no video with that video.

anyway, does enabling the VU Sync gamefix resolve it?

**Comment by macmmm81** [comment]
> There's no video with that video.
uh, sorry

Anyways, no, the hack doesn't seem to do anything.

**Comment by macmmm81** [comment]
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/9310108/emuLog.txt)

Here you are

**Comment by refractionpcsx2** [comment]
hmm nothing exciting there. Okay can you upload a savestate please, or preferrably a memcard if it's easy to get there

**Comment by macmmm81** [comment]
[Mcd002.zip](https://github.com/PCSX2/pcsx2/files/9310139/Mcd002.zip)
[savestate.zip](https://github.com/PCSX2/pcsx2/files/9310144/savestate.zip)

**Comment by refractionpcsx2** [comment]
okay thanks how do I get to the bug spot from the memcard?

**Comment by refractionpcsx2** [comment]
okay I found it.

So if you set your EE Cycle rate to 75% it fixes it, for some reason.

**Comment by macmmm81** [comment]
Thanks.
You can't put that fix in GameIndex, can you?

**Comment by refractionpcsx2** [comment]
Nope, I can't. But you're welcome to put it on the wiki. In the mean time I'm seeing if there's a way I can fix it.  The reason it worked in 1.6 is because the VU timing was instant (a massive hack which broke a lot of games), and now it's timed, and I'm guessing it's checking if it's done somehow and it thinks it's done too early.

**Comment by Goatman13** [comment]
It seems that game grab vf30 result too early. 

```
0015D61C        sqc2    vf30, 0($v0)             <---
0015D620        addiu   $a0, $sp, 0xF0+var_C0
0015D624        mtc1    $v1, $f0
0015D628        lwc1    $f2, 0xF0+var_A4($sp)
0015D62C        cfc2.i  $t0, vi2, 1              <---
```

Microprogram that is running on VU0 side modify vf30 2 times. One time in first cycle by` mul.xyzw      vf30, vf0, vf0` and second time right before e bit by `move.xyzw     vf30, vf22`. So sqc2 before program ends doesn't make sense, you always end up with the same result. 

Patch rearrange code to wait for program end before sqc2. Fixes falling thru the floor in library. Patch for SLES-53073.
```
patch=1,EE,0015d1f8,word,48481001
patch=1,EE,0015d208,word,f85e0000
patch=1,EE,0015d61c,word,48481001
patch=1,EE,0015d62c,word,f85e0000
```

**Comment by refractionpcsx2** [comment]
hang on, but it's interlocked, so it should get it on program end :/

**Comment by Goatman13** [comment]
Interlock is 4 opcodes after sqc2. You can set breakpoint ingame on any opcode between
`sqc2    vf30, 0($v0) ` and `cfc2.i t0,vi02` and click run few times. Sometimes VPU-STAT shows that VU0 is still running, so program still doing something and most likely vf30 at the time this happen is not the one that game expected. Developer just was lucky with timing on real ps2.

![image](https://user-images.githubusercontent.com/101417270/230893404-1854aca7-66b5-409d-86a9-d5e98bf21647.png)

Btw this is microprogram triggered from vif mscal/mscnt, not the one from vcallms (to not confuse, because all vcallms ops have interlock right after in this game).

**Comment by refractionpcsx2** [comment]
I guess it depends what the VF30 register is being used for by the game, the two ops you posted it was just writing to vf30, not reading it, so maybe COP2 is clearing it and waiting until VU0 has set it? idk there.  But of course the interlock could be 1 cycle after the SQC2, it doesn't really matter, it still won't populate t0 until the program ends or has the interlock bit set.

**Comment by Goatman13** [comment]
Sqc2 read from vf30 that microprogram potentially didn't modified yet, and store it on address from v0. That is issue, they interlocked program later, didn't expecting that bad result can show up in vf30 if program is still running. 

Like i mentioned VU0 program modify it in first cycle by `mul.xyzw      vf30, vf0, vf0` and second time right before e bit by `move.xyzw     vf30, vf22`. So if you read it from COP2 by sqc2 while VU0 is still running, you can end up with constant result from `mul.xyzw      vf30, vf0, vf0` instead.

**Comment by Goatman13** [comment]
No problem. :D

**Comment by refractionpcsx2** [comment]
So I expect there's gonna be no real fix except your patch, so if you wanna go ahead and PR it, I won't be upset :D
