### ISSUE TITLE
[Feature Request]: (NOT FULFILLED) Smooth scrolling for mouse wheel in the game list and game grid

### ISSUE THREAD

**Issue by Rex000** [PCSX2/pcsx2#6822]
### Description

Something similar to what modern browsers have.

### Reason

This will be a nice QoL change, and will surely make scrolling through the list/grid super comfortable.

### Examples

.

**Comment by Rex000** [comment]
#6971 did not implement smooth scrolling.

**Comment by Rex000** [comment]
#6971 did not implement smooth scrolling, therefore this request should not be closed.

**Comment by stenzek** [comment]
I don't even know what you're asking for here. You didn't provide any detail.

**Comment by refractionpcsx2** [comment]
My best guess is having a bit of "inertia" like browsers do (since they have the coveted smooth scrolling)

**Comment by neonoxd** [comment]
yes I think Rex000 means scroll steps with ease in/out, my PR didn't implement that exactly. However the issue should be updated because what is described in the "Reason" part is pretty much solved.

**Comment by stenzek** [comment]
If it's the "smooth scrolling" setting similar to what Firefox has, this isn't something which is possible with Qt or native widgets. You'd have to implement it manually, which personally I don't have any interest in doing. PRs welcome of course.

**Comment by Rex000** [comment]
> yes I think Rex000 means scroll steps with ease in/out, my PR didn't implement that exactly. However the issue description should be updated because what is described in the "Reason" part is pretty much solved.

I've updated it. In the reason part I only mentioned the game grid as an example. But yes, your update has made the game grid much easier to scroll now than before.

**Comment by Rex000** [comment]
> If it's the "smooth scrolling" setting similar to what Firefox has, this isn't something which is possible with Qt or native widgets. You'd have to implement it manually, which personally I don't have any interest in doing. PRs welcome of course.

I read somewhere the QTimeLine could do it. I'm not an expert though so I can't say more.

**Comment by Rex000** [comment]
> If it's the "smooth scrolling" setting similar to what Firefox has, this isn't something which is possible with Qt or native widgets. You'd have to implement it manually, which personally I don't have any interest in doing. PRs welcome of course.

I read somewhere that either a timer or alternatively QTimeLine could do it. I'm not an expert though so I can't say more.

**Comment by Rex000** [comment]
> If it's the "smooth scrolling" setting similar to what Firefox has, this isn't something which is possible with Qt or native widgets. You'd have to implement it manually, which personally I don't have any interest in doing. PRs welcome of course.

Well that's exactly why the request should be kept open, so that anyone who feels like attempting it could try. I read somewhere that either a timer or alternatively, QTimeLine could do it. I'm not an expert though so I can't say more.

**Comment by stenzek** [comment]
> Well that's exactly why the request should be kept open, so that anyone who feels like attempting it could try. 

Nope. That's not how this works. You have the right to request features, just like we have the right to reject them. We're all volunteers and you're not a customer after all.

In this case, nobody is going to do it, so it's rejected. Good day.

**Comment by Rex000** [comment]
> > Well that's exactly why the request should be kept open, so that anyone who feels like attempting it could try.
> 
> Nope. That's not how this works. You have the right to request features, just like we have the right to reject them. We're all volunteers and you're not a customer after all.
> 
> In this case, nobody is going to do it, so it's rejected. Good day.

If I were a customer, I would demand it, not request it. 

The request wasn't closed until this PR #6971, in which even the person who made the PR never claimed that they fulfilled it. And not to mention. this person is new, which means there are constantly new programmers coming here and attempting things, which is exactly why a request should stay, especially if it's something that's not impossible.

Anyway, if it's so extremely necessary to close it, then it should at least be closed properly as "Not planned", not as "Completed".

Good day to you as well.

**Comment by stenzek** [comment]
If you're obsessed with the close reason, there you go then. But it doesn't change anything really.

Drop the entitled attitude, and remember we're volunteers giving up our free time. In fact, the way you're acting here has ensured that this request will basically *never* be actioned by any of us.

**Comment by Rex000** [comment]
> If you're obsessed with the close reason, there you go then. But it doesn't change anything really.

No, I'm not obsessed with anything, just don't like it when things aren't done in a proper manner. I expect the volunteers here to understand this better than me.

One thing I see that's constantly being ignored here is that not every request is an actual "request". Many of these including mine are **suggestions** to make the PCSX2 better overall. Of course I can absolutely use the emulator without this one small thing. I didn't ask this exclusively for myself, I asked this to make the further emulator better for everyone.

>Drop the entitled attitude, and remember we're volunteers giving up our free time. In fact, the way you're acting here has ensured that this request will basically never be actioned by any of us.
Relevant: https://boyter.org/posts/the-three-f-s-of-open-source/

Like I said before, if I were entitled I would absolutely _demand_ it, not request it. Another thing I don't expect from owners and especially volunteers of a project is a stubborn attitude, which is also reflected in your linked post whoever wrote it. There are surely other ways to say no. I have done that myself many a times.

Regardless, I thank and appreciate the time and effort of every volunteer on this project and all their contributions that made PCSX2 a great emulator.

**Comment by Rex000** [comment]
> If you're obsessed with the close reason, there you go then. But it doesn't change anything really.

No, I'm not obsessed with anything, just don't like it when things aren't done in a proper manner. I expect the volunteers here to understand this better than me.

One thing I see that's constantly being ignored here is that not every request is an actual "request". Many of these including mine are in fact **suggestions** to make the PCSX2 better overall. Of course I can absolutely use the emulator without this one small thing. I didn't ask this exclusively for myself, I asked this to make the emulator further better for everyone.

>Drop the entitled attitude, and remember we're volunteers giving up our free time. In fact, the way you're acting here has ensured that this request will basically never be actioned by any of us.
Relevant: https://boyter.org/posts/the-three-f-s-of-open-source/

Like I said before, if I were entitled I would absolutely _demand_ it, not request it. Another thing I don't expect from owners and especially volunteers of a project is a stubborn attitude, which is also reflected in your linked post whoever wrote it. There are surely other ways to say no. I have done that myself many a times.

Regardless, I thank and appreciate the time and effort of every volunteer on this project and all their contributions that made PCSX2 a great emulator.

**Comment by Rex000** [comment]
> If you're obsessed with the close reason, there you go then. But it doesn't change anything really.

No, I'm not obsessed with anything, just don't like it when things aren't done in a proper manner. I expect the volunteers here to understand this better than me.

One thing I see that's constantly being ignored here is that not every request is an actual "request". Many of these including mine are in fact "suggestions" to make PCSX2 better overall. Of course I can absolutely use the emulator without this one small thing. I didn't ask this exclusively for myself, I only asked this to make the emulator further better for everyone.

>Drop the entitled attitude, and remember we're volunteers giving up our free time. In fact, the way you're acting here has ensured that this request will basically never be actioned by any of us.
Relevant: https://boyter.org/posts/the-three-f-s-of-open-source/

Like I said before, if I were entitled I would absolutely _demand_ it, not request it. Another thing I don't expect from owners and especially volunteers of a project is a stubborn attitude, which is also reflected in your linked post whoever wrote it. There are surely other better ways to say no. I have done that myself many a times.

Regardless, I thank and appreciate the time and effort of every volunteer on this project and all their contributions that made PCSX2 a great emulator.
