### ISSUE TITLE
[BUG]: Graphics are broken with Vulkan in the Ratchet & Clank - Up Your Arsenal demo on PlayStation Underground Holiday 2004 [T-Rated]

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6827]
### Describe the Bug

Various textures are broken with the vulkan renderer. The pause menu graphics are also broken.

### Reproduction Steps

Start the demo with the vulkan renderer.

### Expected Behavior

The graphics should not be broken.

### PCSX2 Revision

pcsx2-v1.7.3198-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

All settings default

### Emulation Settings

All settings default

### GS Window Screenshots

![PlayStation Underground Holiday 2004 _T-Rated__SCUS-97456_20220813101356](https://user-images.githubusercontent.com/96800307/184460089-4e5bc1e5-c07f-4f79-be2d-152212b9d6fa.png)

![PlayStation Underground Holiday 2004 _T-Rated__SCUS-97456_20220813101414](https://user-images.githubusercontent.com/96800307/184460095-ed963231-6835-4ac6-98c8-f8a1d151b12a.png)

![PlayStation Underground Holiday 2004 _T-Rated__SCUS-97456_20220813101425](https://user-images.githubusercontent.com/96800307/184460112-8f2a4187-a621-4b5e-8093-6cc67ec2350c.png)

![PlayStation Underground Holiday 2004 _T-Rated__SCUS-97456_20220813101929](https://user-images.githubusercontent.com/96800307/184460194-a9ae8b3f-cb13-4055-8567-cce44e22ff81.png)

### Logs & Dumps

[Uploading PlayStation Underground Holiday 2004 _T-Rated__SCUS-97456_20220813101432.zip…]()

**Comment by MrCK1** [comment]
You're seeing that because mipmapping isn't turned off, set it to basic. Normally this would be doen automatically but this is a demo disk containing many games.

**Comment by drachenschanze** [comment]
@MrCK1 Is it not possible to make the demo disc do it automatically?

**Comment by RedPanda4552** [comment]
> @MrCK1 Is it not possible to make the demo disc do it automatically?

No. The fix would have to be applied to everything on the demo disc, or nothing at all. It would not be correct for everything, therefore the best course of action is to leave it as a manual option for the user.

**Comment by drachenschanze** [comment]
@RedPanda4552 What is the underlying problem that requires per game mipmapping? Is that not fixable?

**Comment by RedPanda4552** [comment]
> @RedPanda4552 What is the underlying problem that requires per game mipmapping? Is that not fixable?

It's one disc. So all the fixes apply to the entire disc.

**Comment by drachenschanze** [comment]
@RedPanda4552 No, I'm asking why mipmapping isn't on by default for all games. Why does that cause a problem?

**Comment by refractionpcsx2** [comment]
mipmapping in hardware mode is a hack, it's very difficult to do properly (not sure if possible to do properly for PS2, not my wheelhouse), plus a lot of users want the best textures, which are usually in the largest mipmap, turning on mipmapping will cause the game to use lower quality textures. so it's off by default in hardware mode, software mode is always on (unless you turn it off)

It's just unfortunate that Ratchet & Clank and Jak games rely on mipmapping.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Thanks for the explanation.

**Comment by kazuya-555** [comment]
Wouldnt using the best mipmaps create extra slowdown within a game though, because it still thinks it is being played by a real PS2, that includes the original ram limits ?  Or are virtual ram limits not a factor with emulation or something...

And turning off mipmaps creates texture corruption for me, or are certain games fine with that setting then.
