### ISSUE TITLE
[BUG]: Broken shadows in God of War 2 with DX12

### ISSUE THREAD

**Issue by resadent** [PCSX2/pcsx2#6828]
### Describe the Bug

The shadows in GoW 2 are broken with DX 12. In Vulkan and SW, they look just fine.

I am using latest legacy driver for my gfx card, dont know if that is the culprit here.
DX12:
![broken](https://user-images.githubusercontent.com/34896462/184476589-e281b51d-ebcf-41d5-aa64-75c82331f91d.png)
Vulkan:
![good](https://user-images.githubusercontent.com/34896462/184476588-db90e1f4-b194-410c-bd49-523f888818cf.png)

### Reproduction Steps

Open God of War 2, come ingame, see broken shadows.

### Expected Behavior

The shadows should look just like Vulkan. In software it runs good also.

### PCSX2 Revision

v1.7.3198

### Operating System

Windows 10 (64bit)

### CPU

i7 7790k

### GPU

Radeon HD 7870 2G

### Emulation Settings

Optimal frame pacing on.

### Logs & Dumps

[gsdump_bad_dx12.zip](https://github.com/PCSX2/pcsx2/files/9331137/gsdump_bad_dx12.zip)
[gsdump_good_vulkan.zip](https://github.com/PCSX2/pcsx2/files/9331138/gsdump_good_vulkan.zip)

**Comment by JordanTheToaster** [comment]
Looks correct here.

![image](https://user-images.githubusercontent.com/80843560/184477028-5d34aa02-d312-4f31-a68d-bbcd73feec88.png)

**Comment by Mrlinkwii** [comment]
@resadent  what driver number  version are you on?

**Comment by resadent** [comment]
I am using legacy 22.6.1 driver. Probably that is the issue here. My card is supposedly no longer supported under windows by amd.
