### ISSUE TITLE
[Feature Request]: Better handling of truncated files

### ISSUE THREAD

**Issue by NetSysFire** [PCSX2/pcsx2#6830]
### Description

Repeated errors while reading the disc, namely related to the end of the file, should be displayed as an error popup.

This is more of an edge case, so you may want to assign this feature request a lower priority.

### Reason

I messed up while dumping this disc, resulting in a truncated file. I tried to play it in the emulator and it successfully displayed the game name in the window title but I only got a black screen. It did not help that verbose logging was disabled and once I enabled it, I discovered an endless stream of this error message:

```
Error reading past end of disc
```

### Examples

After a big volume of the error I described appears in a short amount of time, display an error that the file may be corrupt. Pause emulation when displaying the popup.

**Comment by Mrlinkwii** [comment]
Are you sure its a valid disc dump?

**Comment by refractionpcsx2** [comment]
We can't magically make broken dumps work. Correct your dump, I recommend using Imgburn if you're on windows.  Also we can't just assume the disc is broken if it hits that error, some games do it on purpose. I suggest checking your dump if you have a problem and if that fails, visit our discord.

**Comment by refractionpcsx2** [comment]
As I said, that error doesn't always mean your dump is bad.

Anyway if you have issues in the future please visit our forums or discord, we'll be happy to help.
