### ISSUE TITLE
[BUG]:  I tried to extract textures for Ncaa football 11 and i tried changing settings but the textures don't dump into my folder. :(

### ISSUE THREAD

**Issue by HeinzBeanz23** [PCSX2/pcsx2#6833]
### Describe the Bug

I want to edit jerseys on ncaa football 11 and i tried to dump textures, fmv, mipmaps, nothing. I dont know if its the graphics software because i use 3x native on direct3d 12. I really dont know why my textures wont dump into the folder i chose. i have gs compression on uncompressed to see if that helped but nope. 

### Reproduction Steps

boot ncaa football 11 then go into a game then pause the game. Make sure dumping textures is on and the textures should have been extracted to the folder but no.

### Expected Behavior

i want to be able to dump textures into my folder.

### PCSX2 Revision

1.7.3200

### Operating System

Windows 11

### CPU

amd ryzen 3500u

### GPU

amd radeon vega 8

**Comment by JordanTheToaster** [comment]
Do you have texture preloading set to Full (Hash Cache)?

**Comment by HeinzBeanz23** [comment]
where do you find that?

**Comment by JordanTheToaster** [comment]
Settings Graphics Rendering Texture Preloading.

**Comment by HeinzBeanz23** [comment]
yes i have it at full

**Comment by JordanTheToaster** [comment]
Then it's likely just the game if nothing is dumping.

**Comment by HeinzBeanz23** [comment]
i tried dumping on ncaa 06 which usually dumps and it didn't dump

**Comment by HeinzBeanz23** [comment]
ok whats the link

**Comment by HeinzBeanz23** [comment]
nvm
