### ISSUE TITLE
[Feature Request]: Implement DPL2 decoder from dolphin

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#6837]
### Description

We've talked about this, but we found FreeSurround Library in Dolphin.
Maybe we could implement this into PCSX2?
[FreeSurround](https://github.com/dolphin-emu/dolphin/tree/master/Externals/FreeSurround) 

### Reason

Dolphin Pro-Logic II is not implemented in SPU2 so many surround enabled game does not use surround capabilities in advantage.

### Examples

See Dolphin.

**Comment by kenshen112** [comment]
To add to this, could also use any FOSS implementations of other codecs like what MGS or Klonoa use if there are any
