### ISSUE TITLE
[BUG]: Can't configure L2/R2 deadzone from Qt GUI

### ISSUE THREAD

**Issue by pmarks-net** [PCSX2/pcsx2#6848]
### Describe the Bug

When I use PCSX2 with my Xbox360 controller, it often thinks I'm holding down the L2 trigger, because the analog value is not quite 0 when released.

Using the wxWidgets GUI, I was able to fix the problem by configuring a deadzone for the L2 binding, but this option doesn't seem to exist in the new Qt GUI.  I tried the "Analog Deadzone" setting, but it only affects the analog sticks.

![screenshot](https://user-images.githubusercontent.com/4578188/184661385-647cfa5f-d03e-4752-bcea-11a9354d6cdb.png)

(Also note that the bottom of the controller window is cut off, because I can't resize it any smaller.)

### Reproduction Steps

- Connect a USB Xbox360 controller
- Run padtest.elf` by jbit
- Press the L2/R2 triggers slightly

### Expected Behavior

- L2/R2 triggers should not activate with very small values, or at least this should be configurable.

### PCSX2 Revision

v1.7.3210

### Operating System

Windows 10 (64bit)

**Comment by pmarks-net** [comment]
FWIW, I found a utility named [Xinput Plus](https://sites.google.com/site/0dd14lab/xinput-plus) that lets me configure the deadzones, but it seems to only be compatible with the wxWidgets version of PCSX2; the Qt version doesn't see the new Xinput device.

**Comment by stenzek** [comment]
Is this needed? I wouldn't have thought games would be that sensitive to a 1/255 pressure value on the triggers, but I've never looked that closely.

**Comment by pmarks-net** [comment]
> Is this needed? I wouldn't have thought games would be that sensitive to a 1/255 pressure value on the triggers

I noticed this bug because it causes Katamari Damacy to spin between planets nonstop.  It's rather annoying because you have to play through the tutorial, first level, and cutscene for ~10 minutes before reaching this point, and then it prevents you from saving.
