### ISSUE TITLE
Why isn't Edge Anti-Aliasing (AA1) turned on by default?

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#685]
As I understand it (@gregory38 can correct me if I'm wrong), this option only affects games played in software mode and it only gets applied when the game itself calls for it. Why wouldn't we want this option on by default?

**Comment by ssakash** [comment]
removing the edge aliasing of lines and triangles is also done by the GS (drawing process) , I think it would be better if it's enabled by default. 

@karasuhebi 
did you record the performance impact values of Edge antialiasing ?

**Comment by karasuhebi** [comment]
From what I can tell there basically isn't one. At least not with my hardware. Again from what I understand AA1 is only applied when the game calls for it so I'd have to find a scene in a game where it gets called. I know it is used in Final Fantasy X when you're close to the D'jose Temple, so I'll have to test it there to see if there's any performance impact. I seriously doubt they will be though. Let me get back to you.

**Comment by ramapcsx2** [comment]
Only because of performance. Would be nice if you could produce some benchmarks :)
The BIOS cubes also use it!

**Comment by gabest11** [comment]
Also the trails of those flying things. The fps hit is not much, but measurable. I can't really comment on it with a i7-4770.

**Comment by ssakash** [comment]
@karasuhebi 

any progress on recording the impact on performance ? If it's very low then I think it would be better being enabled by default for accuracy,

**Comment by karasuhebi** [comment]
I honestly forgot all about it, sorry. I'll do it today and report back. Thanks for the reminder @ssakash!

**Comment by karasuhebi** [comment]
Holy shit, it's a big difference in performance. ~162-165 FPS with AA1 on, and ~246-248 FPS with it off. I performed the test using Direct3D11 in the path leading up to Djose Temple, around here:
http://img2.wikia.nocookie.net/__cb20140101184207/finalfantasy/images/8/8b/Djose_bridge.jpg

**Comment by ssakash** [comment]
I guess it's a no then :p

**Comment by karasuhebi** [comment]
Yeah definitely O_O

**Comment by gabest11** [comment]
That screenshot is not from sw rendering. AA1 only applies to that.

**Comment by ssakash** [comment]
@karasuhebi 

You didn't test it on Software mode ? XD

**Comment by karasuhebi** [comment]
@gabest11 @ssakash Uh...that screenshot is from HD Remaster. There's no way the PS2 textures look like that. I was just showing the general area where I performed the test.

**Comment by ssakash** [comment]
ohh, that high flashy textures made me think that it might have been from upscaled hardware mode. I'm dumb :p
