### ISSUE TITLE
[BUG]: right stick issue and trigger issue

### ISSUE THREAD

**Issue by Sonic1paRadise** [PCSX2/pcsx2#6851]
### Describe the Bug

on linux right stick on x360 controller maps incorrectly( x axis maps as y axis and y axis maps properly)
triggers do not map correctly as well(axis full but when you push it it does not respond)

### Reproduction Steps

try playing with your trusty Xbox 360 controller on linux with `libonepad-legacy`

### PCSX2 Revision

v1.5.0-0(git) from sudo apt-get install pcsx2

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

elementary 6.1 (based on ubuntu 21.10 likely)

**Comment by stenzek** [comment]
We don't support 1.5 anymore, and onepad is deprecated in favor of the unified pad subsystem in the Qt builds.

As you installed from a package, any issues should be discussed with the packager. Or alternatively, use the AppImages we provide.
