### ISSUE TITLE
[BUG]: Direct3D12 crash, out of fixed descriptors

### ISSUE THREAD

**Issue by TheRhysWyrill** [PCSX2/pcsx2#6853]
### Describe the Bug

Using the D3D12 HW Renderer, playing any of the Spider-Man games and swinging around the city for a couple minutes results in the game hard crashing with the following error:
![unknown](https://user-images.githubusercontent.com/27123572/184850343-11a9a04d-f901-4d33-a88c-f8ef2a4796b8.jpg)

Upon further testing this issue only seems to occur with both VSync and GPU Palette Conversion enabled but as I say this only seems to be a problem on D3D12 for 3 games from what I can tell: Spider-Man, Spider-Man 2 and Ultimate Spider-Man.

### Reproduction Steps

1. Change Renderer to D3D12.
2. Enable both VSync and GPU Palette Conversion.
3. Start a new game on any of the 3 games mentioned above and start swing around the city
4. After just a couple minutes you'll get a hard crash with the above error message.

### Expected Behavior

For the games to not hard crash and continue as normal.

### PCSX2 Revision

v1.7.3210

### Operating System

Windows 11

### CPU

Ryzen 5 3550H

### GPU

GTX 1650

**Comment by junglechief87** [comment]
I actually ran into a similar issue with Tales of Destiny Director's Cut. Same error message and function but the game doesn't hard crash, I can hit ignore and it will keep going but it's popping up the error a lot.

**Comment by stenzek** [comment]
WONTFIX,

You shouldn't be using paltex in the first place.

**Comment by TellowKrinkle** [comment]
To clarify, paltex is GPU Palette Conversion

Turn it off.

**Comment by lightningterror** [comment]
I wouldn't call this an invalid issue as it causes a crash which is a bad thing to have, plus the option is on the rendering tab so people are more likely to use it.

**Comment by stenzek** [comment]
We display a warning when it's enabled. If people can't read, that's their problem.

**Comment by ghost** [comment]
idk why this was locked like this, i have the same problem with unreal tournament and i dont have any palette thing on or whatever u guys call it, this is the only result i found on google, i even reset the game settings and idk what keeps triggering this, can i just force the error to be ignored at all times cuz the game works fine anyway and i don really care, the shadows are super buggy tho

> I actually ran into a similar issue with Tales of Destiny Director's Cut. Same error message and function but the game doesn't hard crash, I can hit ignore and it will keep going but it's popping up the error a lot.

yeh it makes DX12 useless, vulkan stutters like ass with vsync on its unplayable and the framerate in DX11 is super bleh, DX12 works great but, the error pop up is SOOO ANNOYING, like i dont get why this wont get fixed??? it just seems kinda silly to me

at least give me an option to just ignore the error, i just want to play my game
like whats with one developer having this whole "nO uR dUmB, wE wOnT FiX, lEarn 2 rEad DuRR" like bruh what is this xD

> We display a warning when it's enabled. If people can't read, that's their problem.

thats so toxic bruh

**Comment by TellowKrinkle** [comment]
> idk why this was locked like this, i have the same problem with unreal tournament and i dont have any palette thing on

Please open a separate bug for it then.  This one was closed specifically because it was only possible to trigger by messing with the GPU Palette Conversion setting.
