### ISSUE TITLE
[Feature Request]: Separate Cover art for NTSC and PAL Games

### ISSUE THREAD

**Issue by azer95** [PCSX2/pcsx2#6854]
### Description

I absolutely in love with PCSX2 new GUI and per game settings.. Maybe this has been an oversight, but I am unable to have separate cover arts for games with the same name but different region. For example in my case, I have both NTSC and PAL versions of Silent Hill 3. I would like to have their own separate box arts. But when I  try and change one of them, I encounter
![pcsx2 example 1](https://user-images.githubusercontent.com/23059858/184863945-d4b40de5-67e0-4cc4-bd3a-9fbc7846e0f7.PNG)
![pcsx2 example 2](https://user-images.githubusercontent.com/23059858/184863996-20c36c53-5ec3-470d-ab3b-4126e45ff636.PNG)
If I press no, nothing changes. But if press yes, both versions get updated to a new cover art which is not ideal.
![pcsx2 example 3](https://user-images.githubusercontent.com/23059858/184864300-331a9b3c-8711-436e-8a4c-de4683700ba9.PNG)

### Reason

I would like this feature so that my library isn't confusing at a glance. And in cover art grid mode, it only displays Game Title and not file name.

### Examples

This is how I would like my library to look when a game with both PAL and NTSC exists.
![pcsx2 example 4](https://user-images.githubusercontent.com/23059858/184869078-d572b0d2-7f53-4bae-9b43-97c32b36115e.jpg)

**Comment by refractionpcsx2** [comment]
Not an oversight, by default PCSX2 will use the game name, as we don't expect the majority of users to have multiple regions of the same game.

if you need to make them unique, you can use the Serial as a name, or if you need it even more specific, use the ISO name for the cover file, and that will override the generically named one.

**Comment by azer95** [comment]
Thanks that worked perfectly, I have my games in this naming convention {GameTitle] [[Serial]].chd.
I renamed the covers exactly the same name as the file
![Capture](https://user-images.githubusercontent.com/23059858/184881753-81ab2ea5-9c10-4bcc-a0c1-cec1e7b79b43.PNG)
.
