### ISSUE TITLE
[BUG]: Messy, crackling voice of 2 characters during 1st chapter of Tokobot Plus [SLUS-21471]

### ISSUE THREAD

**Issue by CrazyMage72** [PCSX2/pcsx2#6858]
### Describe the Bug

Messy, crackling Voice during dialogue between 2 characters after previous scene with 1 character talking continuously(without lags) . Intro FMV plays fine. Sound becomes normal after background changed to 3d with visible MC and a female NPC starts talking. FPS doesn't change from normal. HW/SW mode doesn't matter, bug doesn't disappear

### Reproduction Steps

Launch game, click new game.

### Expected Behavior

Voice of characters should sound normal and not without any lag,

### PCSX2 Revision

V1.7.3217

### Operating System

Windows 10 (64bit)

### CPU

Intel core I7 7700K

### GPU

GTX 1080

### Logs & Dumps

[Tokobot Plus - Mysteries of the Karakuri_SLUS-21471_20220817025610.zip](https://github.com/PCSX2/pcsx2/files/9354919/Tokobot.Plus.-.Mysteries.of.the.Karakuri_SLUS-21471_20220817025610.zip)
![image](https://user-images.githubusercontent.com/110813477/184992741-3922a354-324d-464f-8711-d7e22edc3ad2.png)

**Comment by Mrlinkwii** [comment]
is this still an issue on latest nightly ?

**Comment by seta-san** [comment]
I don't hear any crackling. there's been a couple instances of frame dips but barely noticeable. I also noticed that this game really tries to stick to 60fps. it doesn't even try to go to 59.94

**Comment by Mrlinkwii** [comment]
cool, Thanks for checking @seta-san , im gonna assume  what ever was the issue is fixed :)
