### ISSUE TITLE
Sound but no sound effect

### ISSUE THREAD

**Issue by ladansemacabre** [PCSX2/pcsx2#686]
hello, I have a problem :

When I play with my headphone i have the music of the game, the voices but no sound effect ! And it's only with PCSX 2. And when I play in normal condition i have sound, voices and little sound effect. And when I begin to play yesterday I didn't have problem ! Please !

Sorry for my English, I'm French !

**Comment by refractionpcsx2** [comment]
This is not the support section, please go to http://forums.pcsx2.net
