### ISSUE TITLE
[BUG]: Right Analog -> UP and DOWN input not detected

### ISSUE THREAD

**Issue by Mounir-Bouaiche** [PCSX2/pcsx2#6864]
### Describe the Bug

When configuring controller bindings settings, I face an issue: I can't map Right Analog -> Up and Down because the input is not detected.
Note: I'm using a USB controller with AB/XY buttons. All inputs are detected when using lilypad plugin in v1.6.0.
Note: Input is not detected for only these two keys/buttons: right analog 🔼 🔽 .

### Reproduction Steps

Setting Menu -> Controllers -> Controller Port1
Click on Up, and then controller's right analog 🔼 -> input is not detected.
Same for controller's right analog 🔽 

### Expected Behavior

All keys/buttons mapped.

### PCSX2 Revision

v1.7.3218

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Sounds like a support issue, please use our forums or discord. Thanks.

**Comment by Mounir-Bouaiche** [comment]
Hi @refractionpcsx2 , I think that input is not detected means input is not handled in code, I don't think that forum could help me !

**Comment by Mounir-Bouaiche** [comment]
Okey, thanks.
