### ISSUE TITLE
[BUG]: Graphical garbage after cutscenes in Bad Boys - Miami Takedown (USA) with Vulkan renderer

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6869]
### Describe the Bug

After every logo and cutscene there's a screen of garbage when using the Vulkan renderer. It doesn't seem to happen with software. I haven't tested the other hardware renderers. 

![Capture](https://user-images.githubusercontent.com/96800307/185420854-929764c5-19d6-4734-b54f-3df118836be0.PNG)

![Capture2](https://user-images.githubusercontent.com/96800307/185420864-279e0cf4-2772-4209-b1db-1148bbf4a33c.PNG)

### Reproduction Steps

Play the game and watch the opening logos and cutscenes. 

### Expected Behavior

This garbage shouldn't be there.

### PCSX2 Revision

pcsx2-v1.7.3221-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Bad Boys - Miami Takedown_SLUS-20982_20220819002901.zip](https://github.com/PCSX2/pcsx2/files/9374747/Bad.Boys.-.Miami.Takedown_SLUS-20982_20220819002901.zip)

**Comment by drachenschanze** [comment]
Barbie Horse Adventures - Wild Horse Rescue (USA) seems to have the same problem.

![Barbie Horse Adventures - Wild Horse Rescue_SLUS-20664_20220822070935](https://user-images.githubusercontent.com/96800307/185811071-b305a61c-5ae8-4dd9-90fa-bea845425fe9.png)

[Barbie Horse Adventures - Wild Horse Rescue_SLUS-20664_20220822070935.zip](https://github.com/PCSX2/pcsx2/files/9389955/Barbie.Horse.Adventures.-.Wild.Horse.Rescue_SLUS-20664_20220822070935.zip)

**Comment by Oymat** [comment]
> Barbie Horse Adventures - Wild Horse Rescue (USA) seems to have the same problem.
> 
> ![Barbie Horse Adventures - Wild Horse Rescue_SLUS-20664_20220822070935](https://user-images.githubusercontent.com/96800307/185811071-b305a61c-5ae8-4dd9-90fa-bea845425fe9.png)
> 
> [Barbie Horse Adventures - Wild Horse Rescue_SLUS-20664_20220822070935.zip](https://github.com/PCSX2/pcsx2/files/9389955/Barbie.Horse.Adventures.-.Wild.Horse.Rescue_SLUS-20664_20220822070935.zip)

it looks like software is the only one being affected by this bug on my end.

**Comment by refractionpcsx2** [comment]
is this still happening? our testers just tried Bad Boys and it seems to be fine. Haven't checked Barbie.

**Comment by refractionpcsx2** [comment]
No response, so closing, if it comes up again feel free to reopen.
