### ISSUE TITLE
[Feature Request]: [QT] Full on theming feature

### ISSUE THREAD

**Issue by gtgamer468** [PCSX2/pcsx2#6871]
### Description

Simply put, I would want a new theming feature created within QT that allows the user to customize the emulator's GUI with any colors that they desire and also maybe background images too. 

### Reason

This would simplify theming in the sense that users can create their own themes as they wish without having to make separate feature requests and PRs.

### Examples

Examples of how I would want this feature could be found within Windows itself for instance with how theming works within the OS.

**Comment by stenzek** [comment]
This already exists (custom qss): https://github.com/PCSX2/pcsx2/pull/6675

**Comment by refractionpcsx2** [comment]
That's not what they meant. They want like an interface for doing it so they don't need to know how to design a qss.  so a tab or whatever with a bunch of sliders and whatnot on it.

Though I suggested making a separate app for generating qss files.

**Comment by stenzek** [comment]
Well, qss does provide the functionality requested ;)

An interface for tweaking every property in the UI style sounds like (1) a massive effort, and (2) outside of the scope of the project, since it's more of a general Qt thing.
