### ISSUE TITLE
[BUG]: Large parts of the floor and walls disappear in Driving Emotion Type-S (Japan)

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6873]
### Describe the Bug

As you drive along parts of the road, walls and background scenery will disappear. Tested with software.

### Reproduction Steps

Start the game and play a race.

### PCSX2 Revision

pcsx2-v1.7.3223-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![Capture2](https://user-images.githubusercontent.com/96800307/185507105-39967593-7f17-4bef-8960-0bc5fc7006b8.PNG)

![Capture](https://user-images.githubusercontent.com/96800307/185507293-f451c0cc-28b8-4d30-a677-76462c38ca60.PNG)

### Logs & Dumps

[wall.zip](https://github.com/PCSX2/pcsx2/files/9378065/wall.zip)

**Comment by refractionpcsx2** [comment]
Can you try enabling the VU Sync gamefix (under view->properties on Qt, Gamefixes tab on WX) and also setting the VU Clamping mode to Extra + Sign, then restart the game (without using savestates) and let me know if that's any better.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Yes that does fix it.

**Comment by refractionpcsx2** [comment]
Cool, unfortunately the AI in the replays/demos is still dumb as rocks, but not much I can do about that, unfortunately. I did try!

We'll get those fixes added to the GameDB
