### ISSUE TITLE
[Feature Request]: Qt: Esc key leaves full-screen mode

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#6876]
### Description

Currently if we hit Esc to leave full-screen mode the program prompts us if we want to end the emulation and if we hit "No" it doesn't switch to windowed mode.

### Reason

In most emulators such as Dolphin, Cemu, Yuzu and even PCSX2 WxWidgets hitting Esc takes us to windowed mode, which is easier and quicker than hitting Alt+Enter for that.

If you agree with this change and if @stenzek  reads this this could also be implemented in Duckstation (currently not opened for new issues or feature requests there unfortunately).

### Examples

Sometimes we don't want to stop the emulation, we want it to stay running while we just do another task in desktop such as replying to a message in Telegram, checking a website for a tip in a game, or just playing with the programs' settings.

Thank you for your time and work.

**Comment by refractionpcsx2** [comment]
you could map escape to "toggle full screen" and unregister it from "Shut down virtual machine"

The power is already there for you to do it yourself.

**Comment by stenzek** [comment]
Yep. Easy enough to remap.

> Sometimes we don't want to stop the emulation, we want it to stay running while we just do another task in desktop such as replying to a message in Telegram, checking a website for a tip in a game, or just playing with the programs' settings.

I'd recommend using borderless fullscreen (the default), and alt-tabbing.

**Comment by dezraj** [comment]
Hello and thank you for the fast replies!

So I went to the Hotkey settings to proceed with the changes you have suggested but it doesn't seem to be possible to have both the Alt+Enter keys and the Esc key for the same function ("Toggle full-screen"), is it? I think this would be ideal to me to work-around this difference in PCSX2 Qt (and Duckstation), considering my experience with the other emulators.

Also, if we hit "Restore defaults" while showing the Hotkeys tab it will also restore all the controller bindings, not only the hotkeys configuration, which I think isn't the best in terms of user-friendliness.

But anyway, thank you so much for your attention and for your work once again.

**Comment by refractionpcsx2** [comment]
yes it is, if you shift + left click the binding you want 2 keys for, you can add additional bindings.

**Comment by refractionpcsx2** [comment]
The separation of resetting hotkeys and controllers isn't a terrible idea, that is something we could action, but probably low priority at the moment.

**Comment by dezraj** [comment]
> The separation of resetting hotkeys and controllers isn't a terrible idea, that is something we could action, but probably low priority at the moment.

Thank you for considering this. I found the need for that when playing with the bindings and trying to revert them to the default values, but I didn't expect it to act in the controllers either.

Anyway, I'm glad opening this issue wasn't so pointless at all. 👍
