### ISSUE TITLE
[BUG]: Masters of the Universe - He-Man - Defender of Grayskull (Europe) has garbage on the title screen

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6886]
### Describe the Bug

There's a garbage line on the right side of the screen. Tested with software.

Here's a video of the game being played on real hardware and the line isn't there.

https://www.youtube.com/watch?v=lQsT1N2X2yM&t=9s

### Reproduction Steps

Start the game and get to the title screen.

### PCSX2 Revision

pcsx2-v1.7.3229-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![Capture](https://user-images.githubusercontent.com/96800307/185787337-8283abe4-9bb1-4875-8f84-94b850917214.PNG)

### Logs & Dumps

[Masters of the Universe - He-Man - Defender of Greyskull_SLES-53035_20220821204322.zip](https://github.com/PCSX2/pcsx2/files/9388909/Masters.of.the.Universe.-.He-Man.-.Defender.of.Greyskull_SLES-53035_20220821204322.zip)

**Comment by refractionpcsx2** [comment]
Either
1. This gets broken earlier in the render
2. It's just like that
3.. It's a core problem

Because it looks the same when running my dump on the PS2

![image](https://user-images.githubusercontent.com/6278726/185787744-b2304ce4-150f-4b7d-aec5-fe5d19b3fd48.png)


Can you try booting the game on #6553 ? But please make sure you have it in software mode and tick the "pre-round sprites" under settings->graphics before booting. 

Thanks.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Sure, how do I download it?

**Comment by refractionpcsx2** [comment]
The builds are here https://github.com/PCSX2/pcsx2/actions/runs/2778174198

**Comment by drachenschanze** [comment]
@refractionpcsx2 That didn't fix it. I guess it's possible the guy in the video is lying and he isn't actually playing on real hardware but that seems unlikely. 

![Capture](https://user-images.githubusercontent.com/96800307/185788570-a8720bb1-3e1f-492a-82d2-445265f1d280.PNG)

**Comment by refractionpcsx2** [comment]
Uhh, it's *my* picture, I took it' with my PS2. We have our own GS Dump runner for PS2

![image](https://user-images.githubusercontent.com/6278726/185788647-f908c390-8e89-45d8-a362-2f781ff8a512.png)

**Comment by drachenschanze** [comment]
@refractionpcsx2 No I mean the guy in the video I linked. The one that shows the title screen without the line. 

![Capture](https://user-images.githubusercontent.com/96800307/185788816-a0f2f5c2-4403-41b3-ad78-3ac1232a4e09.PNG)

**Comment by refractionpcsx2** [comment]
oh right... Well I'm about to test the game properly on PS2, to see what the deal is.

**Comment by refractionpcsx2** [comment]
Okay, I booted up the actual game, aaaaaaaaaand it's there. So I dunno how that guy hid it, probably the potato quality of his capture

![image](https://user-images.githubusercontent.com/6278726/185789323-95d2127c-7f36-4296-8853-56c8e01e629f.png)

So, sorry, marking this one down as "replicated on real hw"

**Comment by drachenschanze** [comment]
@refractionpcsx2 Sorry about that. I see what looks like a bug in the emulator, look up a video of supposed real footage and it's not there, I assume it's an emulation bug.

**Comment by refractionpcsx2** [comment]
Just for prosperity, here's a version of PCSX2 with preround in software

![image](https://user-images.githubusercontent.com/6278726/185789516-b3de7cbd-1eab-4c27-9c7e-95ec9bc58fb8.png)


same soft picture and about the same amount of "Line"
