### ISSUE TITLE
[Feature Request]: Include video mode in status bar resolution

### ISSUE THREAD

**Issue by InterClaw** [PCSX2/pcsx2#6887]
### Description

In the OSD, the resolution might read something like:
"3200x2240 SDTV 480p Progressive"

In the status bar, the resolution is only:
"3200x2240"

I propose that the resolution in the status bar also includes the full set of information as it does in the OSD, i.e. includes the video mode.

### Reason

This way, I don't really feel the need to have any fixed information in the OSD at all, but can just quickly exit fullscreen to verify that I'm in the right video mode.

### Examples

![image](https://user-images.githubusercontent.com/48981208/185813133-c81b5fe2-e324-475e-9c0e-23afc4731f7f.png)

**Comment by stenzek** [comment]
The info in the status bar is deliberately kept short as to not overcrowd it.

If you want the full details, enable Verbose Status in the View menu.
