### ISSUE TITLE
[Feature Request]: Per-Game Controller Profiles

### ISSUE THREAD

**Issue by jjw410** [PCSX2/pcsx2#6888]
### Description

Much like Duckstation, RPCS3 or Steam. The ability to launch games with customised configurations. Having it exclusively as a global setting nullifies pretty much all utility as it requires changing settings for every game.

### Reason

Improve playability in games with antiquated controls. Classically inverted PS2-era camera controls could be easily circumvented with this feature. Allowing for per-game customised profiles gives users a sleek, set-it-and-forget-it solution that does not involve extra fiddling around in menus after the first configuration.

### Examples

Many programs have this feature but RPCS3 or Steam's controller API are the best examples as they allow button-by-button adjustment for each game. Whereas something like Duckstation has the ability to create custom controller profiles that have to be selected per profile, this reduced visibility can make remembering specific adjustments made more difficult to remember.

![rpcs3_UolATNA7ws](https://user-images.githubusercontent.com/44265824/185812958-0322210a-8f7a-400b-a853-da44f4157c26.png) 
`RPCS3 gamepad settings, both global and per-game settings are identical making the feature less confusing to use.`

![duckstation-qt-x64-ReleaseLTCG_pbHqTK7Zip](https://user-images.githubusercontent.com/44265824/185813015-a0e929f9-634f-4da1-bf69-142cff143395.png) 
`Duckstation controller customisation in the global interface.`

![duckstation-qt-x64-ReleaseLTCG_B9iYVwCWZK](https://user-images.githubusercontent.com/44265824/185813052-abea5139-1ff0-4b47-bd49-4fcd4dd3fa64.png) 
`Duckstation controller customisation in the per-game interface.`

RPCS3 and Steam also have the ability to create controller profiles that can be quickly selected per game, like Duckstation. But the more parity between global and per-game settings, the less confusion for the average user.

**Comment by ElTioRata** [comment]
PCSX2 already has that feature in Qt. Close.

**Comment by JordanTheToaster** [comment]
> PCSX2 already has that feature in Qt. So uhh... close?

Qt does not allow profiles to be loaded per game which is the point of this request.

**Comment by stenzek** [comment]
> Qt does not allow profiles to be loaded per game which is the point of this request.

It does (game properties -> set the profile).

I've already specific per-game bindings in the core (for the big picture UI), but just haven't come up with a way to make it look nice in the UI yet.

**Comment by stenzek** [comment]
Having a whole tab for a single option seems a bit silly. Like I said, I want to have profiles *or* per-game bindings as options, which will mean expanding game properties out to the full controller settings size.
