### ISSUE TITLE
[BUG]: Strange graphical issue in Barbie Horse Adventures - Wild Horse Rescue when using fullscreen with hardware renderer

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6890]
### Describe the Bug

When using fullscreen with the Vulkan renderer an ugly grid pattern appears on the screen. This happens at native resolution. I don't know if it's a bug or what's going on but It'd be nice if there was a way to fix it.

Windowed mode with vulkan at native res

![Capture2](https://user-images.githubusercontent.com/96800307/185913193-f595520e-4c5b-4952-85bb-1cb6becad1b4.PNG)

Borderless fullscreen with vulkan at native res

![Capture](https://user-images.githubusercontent.com/96800307/185913286-a7683a23-c161-4872-9913-65cb26cad032.PNG)

### Reproduction Steps

Play the game with a hardware renderer at native resolution in fullscreen

### PCSX2 Revision

pcsx2-v1.7.3229-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[windowed.zip](https://github.com/PCSX2/pcsx2/files/9393976/windowed.zip)

[fullscreen.zip](https://github.com/PCSX2/pcsx2/files/9393977/fullscreen.zip)

**Comment by refractionpcsx2** [comment]
Did you disable "Bilinear Filtering" on the first page of the graphics settings? That's the only way I can reproduce that.

You can probably also get around it by turning dithering off. sometimes dithering effects don't upscale well.

Out of curiosity what is your Dithering set to as well?

**Comment by drachenschanze** [comment]
@refractionpcsx2 Bilinear filtering is on, dithering is set to unscaled which is the default.

**Comment by refractionpcsx2** [comment]
yes, it's likely the dithering pattern interaction with window scaling messing it up, It must be trying to space out the pixels correctly from a direct screenshot than a stretched to fit image of the screen with the snipping tool, or something? I don't know....

I imagine if you disable dithering, the issue will disappoear.

**Comment by drachenschanze** [comment]
yeah, dithering off looks infinitely better. 

![Barbie Horse Adventures - Wild Horse Rescue_SLUS-20664_20220822232318](https://user-images.githubusercontent.com/96800307/185931924-f34569ee-e912-442c-99a9-b3a11ec74d60.png)

**Comment by refractionpcsx2** [comment]
soooo yeah, sorry not much we can do about that, either use scaled dithering or turn it off, that's your options :)

**Comment by drachenschanze** [comment]
@refractionpcsx2 What about dithering being off by default?

**Comment by refractionpcsx2** [comment]
No, because that will cause serious banding in a lot of games.

**Comment by refractionpcsx2** [comment]
Anyway, not much we can do here, it's a combination of the size of your window with your screen res, the upscaling resolution on pcsx2 and the setting you have dithering set to.

You can disable dithering on a per-game basis for yourself if you're suffering from the perfect storm of conditions.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Fair enough.
