### ISSUE TITLE
doesn't work in fedora 36 

### ISSUE THREAD

**Issue by lucasmz1** [PCSX2/pcsx2#6893]
### Describe the Bug

hello I request support for fedora 36, the appimage version doesn't work in fedora the both versions, the wxwidgets and qt version... there says when debugged into the terminal segmentation fault core image recorded.

### Reproduction Steps

./pcsx2-v1.7.3231-linux-AppImage-64bit-wxWidgets.AppImage

### Expected Behavior

the expected behavior for the application is for it work, in this case it doesn't.

### PCSX2 Revision

1.7.3231

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

fedora 36

**Comment by Mrlinkwii** [comment]
Whats your pc specs?

**Comment by lucasmz1** [comment]
hello fedora 36
gtx 1060
8gb ram
i5-2400
motherborad asus p8-h61m lx3 r2.0

**Comment by stenzek** [comment]
Try the Qt AppImage (SSE4, your CPU doesn't support AVX2). I specifically tested Fedora and it seemed fine.

**Comment by lucasmz1** [comment]
for me didn't work well the app clashes all the time it even start it. anyway tank you for your support.
