### ISSUE TITLE
[BUG]: Xbox One Controller Recognized When Binding But Not In-Game

### ISSUE THREAD

**Issue by WednesdayMWS** [PCSX2/pcsx2#6896]
### Describe the Bug

**UPDATE You can't have SDL and X-input checked at the same time for the xbox one controller**
![image](https://user-images.githubusercontent.com/104041602/186232666-f61757c3-0b36-4ee6-9163-4fc87ed41b21.png)

Basically, when using the controller settings to map my controller, it maps fine. Of course this means the checkbox for allowing xinput is checked. The controller is connected via bluetooth.

But no matter the game, it doesn't recognize the controller. Pressing start to start the game does nothing. Even weirder still, before disabling "double click to enter full screen", my controller's ABXY would count as those double clicks. I do not have steam or any other software emulating the controller as a mouse and keyboard so that cannot be the issue.

![Attached is my mapping, if it helps at all](https://user-images.githubusercontent.com/104041602/186046690-0085e7db-a18e-4668-91ae-afc0495b5b8b.png)

### Reproduction Steps

Simply start up PCSX2 latest nightly 1.7.3231
connect an xbox one controller with bluetooth
**have SDL and x-input checked under the controller settings**
bind said xbox one controller to its appropriate buttons
restart the program (optional)
Run a game and attempt to play it with the xbox one controller

### Expected Behavior

I am sure this field is redundant but I want to fill in all the fields for you guys. I expected the controller to use its mappings appropriately.

### PCSX2 Revision

v1.7.3231

### Operating System

Windows 10 (64bit)

**Comment by ddzzhen** [comment]
The best way is to add the pcsx2 game from steam and open it from there, the compatibility is very good, it can ignore almost all handle problems.

**Comment by WednesdayMWS** [comment]
> The best way is to add the pcsx2 game from steam and open it from there, the compatibility is very good, it can ignore almost all handle problems.

I already figured it out but wanted it brought to the developers' attention. If you have x-input and SDL checked at the same time in the controller settings, it messes with Xbox One and Xbox One S controllers. Probably series controllers too.

It isn't a steam issue. Thanks though

**Comment by refractionpcsx2** [comment]
Your mapping looks a mess, I would suggest you run through support if you're still having problems.

**Comment by H-lover** [comment]
Actually i have the same issue. The conroller works perfectly on 1.6.0 but in new version it won't respond, even though i can map it in config tab. Can i just use LilyPad plugin in 1.7.x versions?

![image](https://user-images.githubusercontent.com/132934878/236887496-77b8fdd3-8d94-4d5a-a5e5-c919891ab0e9.png)

**Comment by kamfretoz** [comment]
@H-lover head over to our Discord if you need help or support.
