### ISSUE TITLE
[Feature Request]: Install Disc based Games to Library Storage

### ISSUE THREAD

**Issue by SpaceAgeHero** [PCSX2/pcsx2#6910]
### Description

I'd like to request a disc installartion feature.

It should work like this:
Whenever a physical game disc is inserted an option should be available to "install" it to library.
Running this action will then dump the disc to the library directory with a matching file name if recognized in GameDB.
Ideally it will even be compressed to chd. 

### Reason

I'd like to setup a mini pc with an internal DVD drive (yeah, I'm from the past).
This will basically be a standalone, modern PS2 emulation console (with both DuckStation and PCSX2). 

It is already possible to run games directly from disc, I know.
But this has a couple of disadvantages:
- potential wear and damage to disc
- slow read speeds
- noise
- no neat, digital library

### Examples

[Polymega](https://polymega.com/) does exactly what I want:
[How To Install Your Disc Based Games On Polymega](https://www.youtube.com/watch?v=ZvngBCvamK4)

But it is a commercial product which lacks PS2 emulation and more powerful PS1 emulation features like resolution upscaling.

**Comment by stenzek** [comment]
PCSX2 is not a disc dumper. That's a job for another application.

Not gonna close this without getting input from others, but as far as I'm concerned this is scope creep and it's not something I ever intended the new UI to have. Pull requests are welcome of course.

**Comment by refractionpcsx2** [comment]
Yeah we're not a disc dumper, I don't think we could ever do as good of a job as Imgburn, while we could possibly make ISO's without much effort (I think the block dumper supports making ISO's, so it could be fiddled to do that), I imagine that a proper disc dumper would be faster and better at it.

I'll see if anybody else wants to give feedback on this too, that's my 2c in case it's technically easier to do both than I thought.

**Comment by stenzek** [comment]
Dumping DVDs probably isn't *too* bad since you're only concerned with the userdata area (after all, you can dump them with a simple `dd if=/dev/cd of=game.iso` command. But CDs are a completely different ball game, just look at the complexity of DiscImageCreator for example.

**Comment by refractionpcsx2** [comment]
Yeah, CD's is what I'm nervous about!

**Comment by SpaceAgeHero** [comment]
[Retroarch can dump CD's](https://www.libretro.com/index.php/retroarch-disc-project-disc-dumping-to-internal-storage-now-possible/) to CUE / Multi-BIN but with a rather unpleasent end result. DVD not supported.

**Comment by refractionpcsx2** [comment]
That kinda proves the point that emulators and frontends probably shouldn't try to do a job that dedicated software has spent years perfecting :)

**Comment by stenzek** [comment]
Agreed. IMO this should be closed as out of scope then.
