### ISSUE TITLE
[BUG]: The opening video of Disney's Kim Possible - What's the Switch (USA) runs in slow motion

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6911]
### Describe the Bug

After a few seconds of running at normal speed, the cutscene suddenly starts running in slow motion. Always at the exact same moment. Tested with the software renderer using 3 and 4 cores, and with Vulkan at native res and x5.

### Reproduction Steps

Start the game and watch the opening video.

### PCSX2 Revision

pcsx2-v1.7.3241-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

![Capture](https://user-images.githubusercontent.com/96800307/186593360-7ad58ed2-b178-4bef-8190-a978bd957727.PNG)

**Comment by Mrlinkwii** [comment]
is this still an issue on latest nightly  , which recent improvements ?

**Comment by tellowkrinkle** [comment]
Looks VU-bound, and I think most of the recent improvements were on the EE side of things
But who knows, maybe it'll help anyways
