### ISSUE TITLE
[BUG]: Graphics in Futurama (USA) are severely broken with software rendering and slighly broken with hardware

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6918]
### Describe the Bug

Using the software renderer, large black shadows follow the player around and the icon of Fry's face is corrupted. Switching to hardware rendering fixes the black shadows but not the corrupted icon. 

### Reproduction Steps

Start the game and play using the software renderer. 

### PCSX2 Revision

pcsx2-v1.7.3244-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Software

![Futurama_SLUS-20439_20220826163243](https://user-images.githubusercontent.com/96800307/186838085-fc1cff32-94f1-4401-bb3a-b6aa126b1187.png)

Vulkan at native resolution

![Futurama_SLUS-20439_20220826163356](https://user-images.githubusercontent.com/96800307/186838136-c32b56d1-0196-43fa-bb3f-2ef92cbd7bf6.png)

### Logs & Dumps

[Futurama_SLUS-20439_20220826163243.zip](https://github.com/PCSX2/pcsx2/files/9430454/Futurama_SLUS-20439_20220826163243.zip)

**Comment by refractionpcsx2** [comment]
Linking in #5976 because we could never reproduce it ourselves.

**Comment by refractionpcsx2** [comment]
can you try again with #8189 ? but please load the game, using a savestate or gs dump won't show it.

**Comment by web1018** [comment]
> can you try again with #8189 ? but please load the game, using a savestate or gs dump won't show it.

Hello refractionpcsx2. I tested the #8189 in the Futurama game. This issue still persists as you load a save state. When you do a save state, and load that save state during gameplay, the black shadows begin to occur. Im using Vulkan and not a Software Renderer. 
![Screenshot 2023-02-18 103244](https://user-images.githubusercontent.com/51851411/219947840-ce2ba482-da97-4c9b-b4d7-3a1526df4d7f.jpg)

**Comment by Mrlinkwii** [comment]
Dose it happen when you don't use savestates?

**Comment by web1018** [comment]
> Dose it happen when you don't use savestates?

No, it doesnt appear if I dont use the save state and just go with the ingame saving option.

**Comment by refractionpcsx2** [comment]
Yeah I didn't fix savestates, just swapping renderers, which is what you posted as the issue.

I know we have to add savestates to this, I might do it later in the week.

**Comment by web1018** [comment]
> Yeah I didn't fix savestates, just swapping renderers, which is what you posted as the issue.
> 
> I know we have to add savestates to this, I might do it later in the week.

Alright. Thanks for wanting to take a look at this issue. Oh, I didn't post the render swapping issue as I was only having the issue with savestates. Someone else was having the render swapping issue. Should I also create a new github issue for the corrupted face on characters face at the top left?
