### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Hunk4TH** [PCSX2/pcsx2#6926]
### Describe the Bug

Steam overlay not showing up in Linux Kde and Gnome etc 

### Reproduction Steps

Using Manjaro Kde and Gnome the Steam overlay doesn't showbuo. 

### Expected Behavior

Overlay doesn't appear at all desktop nor Big picture.

### PCSX2 Revision

Any. 

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Manjaro

**Comment by stenzek** [comment]
Not sure how this is a PCSX2 issue...
