### ISSUE TITLE
[BUG]: Some icons are missing in Gran Turismo 4 while using Disable Hardware Readbacks. 

### ISSUE THREAD

**Issue by GtafanWRLD** [PCSX2/pcsx2#6928]
### Describe the Bug

Missing icons appear when you decide to use Disable Hardware Reads in advanced graphics settings. I've noticed it says it can break some graphics. However this option fixes lag on night tracks caused by any source of light such as sun or lamps on night tracks. With the setting checked the track "George V Paris" that's normally unplayable can be run in full speed without any fps drops.

How missing icons look like: https://imgur.com/a/udmhagA
### Reproduction Steps

1. Go to per game settings -> Advanced graphics settings -> check Disable Hardware Readbacks
2. Run Gran Turismo 4 and go to any track.
3. Either finish the race to see final scoreboard or drive through the sector to see time diffrence between you and an opponent behind

### Expected Behavior

Icons are not missing

https://imgur.com/a/sLLaC17

### PCSX2 Revision

v1.7.3254

### Operating System

Windows 11

### CPU

I7 8700k

### GPU

GTX 1080

### GS Settings

Clamping mode set to Full and Extra + Preserve Sign to fix text glitches.
MTVU and Instant VU1 are used together for the best performance

### GS Window Screenshots

https://imgur.com/a/8yIn3iM

**Comment by JordanTheToaster** [comment]
Not a bug it's going to happen when you use disable hardware readbacks.

**Comment by GtafanWRLD** [comment]
So it's pretty much a trade between performance and graphics glitch?

**Comment by Mrlinkwii** [comment]
correct

**Comment by refractionpcsx2** [comment]
Hacks cause bugs, that's the nature of them.
