### ISSUE TITLE
Wrong DATE test on SW for 16 bits RT

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#693]
I hit the issue on haunting ground. The game does a first draw in a 32bits RT and then do a 2nd draw with DATE = 1, DATM = 1 but RT is now 16 bits.

I think the code expect the 16 bits of MSB to be 0 which is not always true.

Standard code (non JIT)
```
test |= fd.srl32(15) == GSVector4i::zero();
```

JIT code
```
vpxor(ymm0, ymm0);
vpsrld(ymm1, ymm2, 15);
vpcmpeqd(ymm1, ymm0);
```

However DATM = 0 seems to be use 2 shifts to mask the MSB.
```
test |= fd.sll32(16).sra32(31);				
```

**Comment by gregory38** [comment]
@gabest11 do you agree with me?

**Comment by gabest11** [comment]
Have to dig up the code. I can hardly remember anything. Do you have a dump to test?

**Comment by gabest11** [comment]
The two shifts spread the 16 MSB to 32-bit 0xFFFFFFFFs with the second arithmetic shift. 

gsuser.pdf says  1/0 pixels with 0 MSB pass, 1/1 pixels with 1 MSB pass. I think the code is correct.

**Comment by gabest11** [comment]
test=0 => pass

**Comment by gregory38** [comment]
Here the dump. Around draw call 660:
https://www.sendspace.com/file/qvg5d9

By the way you will notice that I change a bit the dump to force a 32 bits format on 16 bits RT (otherwise you only see useless vertical stripes)

Bad case is DATM 1. If I understand the code correctly, you load pixels in 32 bits "register".
Here some basic printf of the 2 first pixels. As you can see the 16 bits pixels got noise on msb, so the equal zero comparaison is bad because you compare 17 bits instead of the single alpha bit.
```
659: DATE p1:0x11110014, p2:0x17170011
After the shift
659: DATE p1:2222, p2:2e2e
```

**Comment by gregory38** [comment]
Some info on the dump/draw call. 

The standard effect without date just copy the green channel (of 32 bits) to the alpha channel (of 32 bits). The copy is emulated with the help of the 16 bits format.

It seems that the alpha bit is 0 but hard to tell with those silly 16/32 bits conversions. On openGL HW all pixels are failed. Whereas on SW all (at least most) pixels are OK. On the final frame, it change a bit the lighting effect (of hole) on the bottom left. Hw is bit darker.

**Comment by gabest11** [comment]
I'm scratching my head. That fd.srl32(15) == GSVector4i::zero() really looks wrong now. The "noise" is just the pixels from the previous or next row, depending on the even-odd line, because that's how 16 bit formats are packed. Maybe in the past I read them individually, before realizing it can be done with two movqs. As I see nothing else depends on the upper 16-bits of fd, only these rare date/datm condition, we could correct it with a (fd & 0xffff) before the shift.

**Comment by gabest11** [comment]
Or the two shift solution would better, needs no extra register.

**Comment by gabest11** [comment]
Did a push to master. Can someone explain why I see two entries in the commit list? First one in time is mine, but the latest has files that I did not modify.

**Comment by gabest11** [comment]
I can see this:

@gabest11
Merge branch 'master' of https://github.com/pcsx2/pcsx2
gabest11 authored 4 minutes ago
542dd33  

@gabest11
gsdx: date/datm fix for 16-bit frame buffer in sw rendering mode
gabest11 authored 10 minutes ago
a1a842b

**Comment by gabest11** [comment]
I'm using tortoisegit and did a pull before push with the default options, if that helps. There are countless google hits about this extra commit message, still trying to understand why this may happen and how to avoid it.

**Comment by gregory38** [comment]
It is normal. Let's me explain it to you. When you do a local commit, you do it on a local master branch (fork). Here the current situation.
```
Master => my commit ( the new master)
     |----=> your commit
```

when you did a git pull, my commit was merged into your commit. And then you push your branch which contains your commit + the merge of my commit with yours.

If you want to avoid it you need to rebase your work. Or use git pull -r (-r means rebase instead of merge).

Still on git trick, you can do a partial commit (git add -p). For example if you want to separate your openCL changes with the date stuff. It is much easier to spot regression and review code.

By the way, I debugged a bit the gs dump this afternoon. And the remaining issue is related to the texture cache. The game clears a target at address 0x3000. And then reuse an input texure at 0x3300 which means a subpart of the previous target. However the texture cache see a separate texture (with wrong content)

Have you ever tried to improve it? Or was it too slow?

**Comment by gregory38** [comment]
@prafullpcsx2 
Could you test the SW renderer? With luck some games might be fixed.

**Comment by gabest11** [comment]
Partial texture addressing is always a problem in hw mode. There is not much to do about it other then a read back. If we can catch it. Or adding a hack.

**Comment by gabest11** [comment]
I read about the -rebase switch, will use it in the future and see what happens :)

**Comment by gabest11** [comment]
Do you happen to know which silent hill has a problem with Q? (Origins, Shattered Memories) 

I'm thinking of the isnan test, those handlers can add a lot of execution time for high vertex count, and it is bad to lose some fps because of one game. There is a simple replacement for isnan, if(x != x), but I want to test it first.

Was there a discussion about moving to vs2015 yet? It's basically free, but by opening the project files it modifies them. I could create a copy of each, if that's okay.

**Comment by gregory38** [comment]
For partial addressing maybe some offset can do the trick. Honestly I postpone those change for laters.

Maybe SH 3 or 4. I don't know. Otherwise I can provide you a dump tomorrow. Yes I was afraid of the performance impact that why I added only an assertion for others handlers. Maybe the compiler optimize the test already.

Afaik VS2015 upgrade is on-going. It requires a couple of small update.

**Comment by gregory38** [comment]
The silent hill GS dump: https://www.sendspace.com/file/v8wrns

**Comment by gabest11** [comment]
This one should be closed I think.

**Comment by gregory38** [comment]
Let's me fix a potential corner case on openGL (which support this pseudo 16 bits format).
