### ISSUE TITLE
[BUG]: No audio / sound (Qt Appimage)

### ISSUE THREAD

**Issue by Ka-hu** [PCSX2/pcsx2#6933]
### Describe the Bug

All settings are default, the volume is 100%, and there is no sound with _pcsx2-v1.7.3256-linux-AppImage-64bit-SSE4-Qt.AppImage_

![screenshot](https://i.imgur.com/rSKch5K.png)

I tried an earlier version of a Qt Appimage, no sound either. (I wanted to test the wxWidgets Appimage version, but I couldn't, it crashed with _Error: Unable to initialize GTK+, is DISPLAY set properly?_)

I used an older, non-Qt version before (pcsx2-v1.7.2357-linux-AppImage-64bit.AppImage), and the sound worked with it (and works now, too). The sound is okay in other applications, so it's not an issue with my system.

### Reproduction Steps

Use a Qt Appimage
Lauch a game
No sound

### PCSX2 Revision

v1.7.3256-linux-AppImage-64bit-SSE4-Qt.AppImage

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by Mrlinkwii** [comment]
odd , Audio works here with the appimage  , can you post a log?

**Comment by Ka-hu** [comment]
Log: https://pastebin.com/raw/LUDY0zi6
I tried the lastest (as of now) Appimage ([v1.7.3256](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.3256)), as I stated in my report.

**Comment by Mrlinkwii** [comment]
may i ask whats your pc specs?

**Comment by Ka-hu** [comment]
i5-2400
Nvidia Quadro K600
ALSA for audio in Arch Linux

**Comment by DonutWrecker** [comment]
I've had a similar problem in Ubuntu a while ago. Make sure you have all the dependencies installed.

**Comment by Ka-hu** [comment]
I figured it out. I needed to install pulseaudio (and start with pulseaudio -D). Although the Appimage should work without any installed dependencies, that's the point of the Appimage, or am I wrong?

**Comment by Mrlinkwii** [comment]
audio works here with the appimage idk what your doing :confused:

**Comment by Ka-hu** [comment]
Do you have pulseaudio installed on your system? If you have, then try to remove it, and check if you have sound with the Appimage. With only ALSA, I didn't have sound, I needed to install Pulseaudio.

**Comment by DonutWrecker** [comment]
> I figured it out. I needed to install pulseaudio (and start with pulseaudio -D). Although the Appimage should work without any installed dependencies, that's the point of the Appimage, or am I wrong?

Yes, it should. I don't have an exact answer for your problem. It didn't work for me as well, but someone else didn't have any issues. In those cases, checking whether you have the dependencies installed on your machine, and if it doesn't work, compiling from the source is the best way to ensure maximum compatibility with your system.

**Comment by stenzek** [comment]
I think the CI is missing some dev packages which are needed to enable the other cubeb drivers. Looking into this and adding a driver dropdown is on my todo list.

**Comment by Mrlinkwii** [comment]
can this be checked on master ?

**Comment by kamfretoz** [comment]
Tested with AppImage v1.7.4160 running on Arch Linux (KDE Plasma with PipeWire).
Audio works fine and flawlessly.

Recording:
https://user-images.githubusercontent.com/14798312/221894588-7e558a92-3202-4f69-927a-4436b8ba608c.mp4

Audio Setting:
![Screenshot_20230228_220209](https://user-images.githubusercontent.com/14798312/221894710-71c0fc4e-2403-43d7-9aae-0d87bc1631c6.png)

**Comment by stenzek** [comment]
For the record, this was probably because the alsa dev package wasn't being installed on the CI, which meant cubeb only had pulse support.
