### ISSUE TITLE
[BUG]: Several options in ui do not say what they do when hovered over with mouse

### ISSUE THREAD

**Issue by JetSetter1984** [PCSX2/pcsx2#6937]
### Describe the Bug

There are several options in the ui graphics section which have no explanation. All other options do. These are easily found in the tabs for advanced and texture replacement within the graphics section. All other check boxes have a description of the option. 

### Reproduction Steps

Hover mouse over certain options in the described sections of the ui.

### PCSX2 Revision

1.7.3256

### Operating System

Windows 11

**Comment by Daisouji** [comment]
It's not a bug, we haven't done those descriptions yet, they will get done when they get done tho
