### ISSUE TITLE
Devil May Cry scaling issue

### ISSUE THREAD

**Issue by gab** [PCSX2/pcsx2#694]
As entered in the old bugtracker with screenshots: https://code.google.com/p/pcsx2/issues/detail?id=1319

I reproduced the bug with pcsx2 1.2.1 r5875 and gsdx32-avx2-r5875 under Windows 7.
Here is the GS dump: https://dl.dropboxusercontent.com/u/22764021/Devil%20May%20Cry%20scaling%20bug%20-%20gsdx%20r5875.7z

Whenever you set a resolution higher than native (multiplier or custom res) in Devil May Cry 1:
1- A small box containing part of the screen appears at the upper left
2- **Text renders in this small box instead of appearing at its normal place on the screen** (wasn't mentioned in the original bug report)
3- None of the HW hacks fix it (only thing I haven't tried is the layers hack)
4- The bug is present in all modes, HW or SW, DirectX 9/11 or OpenGL

It's a pity since the game assets are actually very nice, and look beautiful in high resolution.

The reason I'm adding this back here is that I tested with an **older Gsdx** (r890, 0.1.14), scaled it up to 1920x1200, and **the problem is not present**. Of course running that very old plugin has many inconvenients including worse speed and little configurability. But if it scales fine with that old code, there's gotta be a way to bring back the same behavior in current Gsdx trunk with a hack!

**Comment by ssakash** [comment]
please also provide a GS dump along with the report for the developers to look into it.

**Comment by gab** [comment]
GS Dump uploading to Dropbox, it's gonna be available in 1 min - link already edited into the description.

**Comment by Jozman** [comment]
I know how to solve that issue. You need to press "select", than go to "Options", after that select controller settings and stay in it for 5-7 seconds, at the end return to game bu pressing ▲ triangle at the medium speed and wallah, you have the health and DT box recovered, but it's still low resolution which is not that of a problem. :)

**Comment by MrCK1** [comment]
Issue still active as of latest git

**Comment by FlatOutPS2** [comment]
The box should be stretched to full screen, but is instead stuck in the top left corner. The box is for text messages that should be placed in the bottom middle of the screen.

**Comment by gab** [comment]
Unfortunately it seems that the old issue disappeared from Google Code Archive along with the screenshots. Have those issues been archived somewhere else?
My description should be accurate enough to identify the bug without screenshots, though.

**Comment by FlatOutPS2** [comment]
Here's a clear screenshot:
![dmc](https://cloud.githubusercontent.com/assets/15942346/18446170/64b382a6-7921-11e6-9f3c-67cfbf037206.jpg)

**Comment by MrCK1** [comment]
Health bar issue still exists as well, disabling WS patch didn't affect anything. Setting custom resolution to 512x448 fixed it; but of course that's useless when we want to be upscaling

**Comment by ramapcsx2** [comment]
Fixed! :D

**Comment by FlatOutPS2** [comment]
> Fixed! :D

Well, in a PR. People rushing out checking the latest master will end up disappointed for now. :D

**Comment by FlatOutPS2** [comment]
It's been merged, so I'm closing this.

**Comment by gregory38** [comment]
@FlatOutPS2 when you close bug (not regression) try to mark them as 1.6 milestone release. It could help to generate a nice changelog.

**Comment by gab** [comment]
Awesome, thanks for fixing this long-standing issue. I'm glad I reported it instead of just using dumb workarounds.
