### ISSUE TITLE
[BUG]: Opening logos and video of Ide Yousuke no Mahjong Kazoku 2 (Japan) are a black screen with hardware renderers

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6941]
### Describe the Bug

Using Vulkan, the opening logos and video are a black screen. I can hear them playing but not see them. They work fine with software.

### Reproduction Steps

Start the game with a hardware renderer and listen for when the video starts playing.

### PCSX2 Revision

pcsx2-v1.7.3257-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Software

![Capture](https://user-images.githubusercontent.com/96800307/187159436-65cefd2a-366b-487d-bb86-a890147ecc05.PNG)

Hardware

![Capture2](https://user-images.githubusercontent.com/96800307/187159481-b7d6e13d-7de7-47ae-9c9c-81313f09e585.PNG)

### Logs & Dumps

[Ide Yousuke no Mahjong Kazoku 2_SLPS-20039_20220829183058.zip](https://github.com/PCSX2/pcsx2/files/9442964/Ide.Yousuke.no.Mahjong.Kazoku.2_SLPS-20039_20220829183058.zip)

**Comment by lightningterror** [comment]
The dump is different than the screenshots, try taking a new one.
![image](https://user-images.githubusercontent.com/18107717/187737412-23676686-e091-4191-98c0-3d7f8b6ba523.png)

**Comment by drachenschanze** [comment]
@lightningterror 

['.zip](https://github.com/PCSX2/pcsx2/files/9466007/default.zip)

**Comment by Mrlinkwii** [comment]
can this be double checked on lastest nightly ?

**Comment by lightningterror** [comment]
@drachenschanze I don't see anything wrong on the provided dump, however it's still not the same scene as on the screenshot you posted
![image](https://user-images.githubusercontent.com/18107717/213924666-98843673-97ca-409e-a13f-9b3009c40668.png)

**Comment by refractionpcsx2** [comment]
Game seems to be fine now 
![image](https://user-images.githubusercontent.com/6278726/213925012-3fd7429d-f430-4130-b030-4a06d902fba1.png)
