### ISSUE TITLE
[BUG/HW]: Street Fighter III - 3rd/Third Strike - Sprite problem at higher res

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#6942]
### Describe the Bug

This game works perfectly on SW, unfortunately the sprites were made for the CPS3 and the PS2 resolution/ratio isn't the same. That's why it's not pixel perfect and the sprites are kinda weird at native res.

![Street Fighter III - 3rd Strike_SLPM-65621_20220827100458](https://user-images.githubusercontent.com/47425204/187165077-889b5b94-87c1-4c7c-acc2-ad2805469f5a.png)

Fortunately emulators can increase the internal res and solve this issue (Capcom Fighting Jam/MVC2, etc...).

The sprites have problems on higher res as stripes appear but x3 and x5 are almost perfect. There is only 1 problem (which I hope can be solved).

As you can see, the stripes are appearing only on the player facing right and not on the one facing left even if you change position, Here are the screenshots :
![Street Fighter III - 3rd Strike_SLPM-65621_20220827100351](https://user-images.githubusercontent.com/47425204/187165239-c92f88fd-b850-4205-839f-32b0c817e983.png)
![Street Fighter III - 3rd Strike_SLPM-65621_20220827100410](https://user-images.githubusercontent.com/47425204/187165254-12d9d1da-01f5-41b8-b769-e44e6dbeeda7.png)
![Street Fighter III - 3rd Strike_SLPM-65621_20220827100419](https://user-images.githubusercontent.com/47425204/187165259-0861799b-68c0-4fdd-8cf4-0a310c1efbb5.png)

### Reproduction Steps

Go the the character select screen or start a fight

### PCSX2 Revision

v1.7.3256

### Operating System

Windows 11

### CPU

5600x

### GPU

AMD 6800

### Logs & Dumps

I attached 3 snaps at HW/Res x3 and 1 in SW.

[snaps.zip](https://github.com/PCSX2/pcsx2/files/9443238/snaps.zip)

**Comment by JordanTheToaster** [comment]
The only options you have is play at native 2x internal or 4x internal otherwise it will be misaligned.

**Comment by Immersion95** [comment]
> The only options you have is play at native 2x internal or 4x internal otherwise it will be misaligned.

2x or 4x are worse offenders, only 3x is near great.

**Comment by JordanTheToaster** [comment]
4x looks fine to me

![image](https://user-images.githubusercontent.com/80843560/187703799-3cde60c6-e39e-4ee0-819e-52ed6fb6734a.png)

**Comment by Immersion95** [comment]
> 4x looks fine to me
> 
> ![image](https://user-images.githubusercontent.com/80843560/187703799-3cde60c6-e39e-4ee0-819e-52ed6fb6734a.png)

Thanks a lot ! I thought I tested it, let me try and close this issue then.

**Comment by Immersion95** [comment]
So I tested it and OpenGL/Vulkan are almost perfect in Res x2 & x4 but the bottom right is messed up.

![Street Fighter III - 3rd Strike_SLPM-65621_20220831202536](https://user-images.githubusercontent.com/47425204/187753330-b9ebd4e1-79be-492a-b697-d356ff5924d1.png)

**Comment by refractionpcsx2** [comment]
Gonna close this now, as it is mostly worked around and we don't accept upscaling bug reports.  If we can use hacks to fix it, fine, but otherwise we don't accept them, and unfortunately this falls under the latter.

Thanks for the report.

**Comment by Immersion95** [comment]
No problem, I understand the matter. Just wanted to add that there is no workaround atm for anyone stumbling into this github issue.

**Comment by refractionpcsx2** [comment]
The workaround isn't perfect, but using 2x or 4x is better than nothing, and it's pretty close.

**Comment by Immersion95** [comment]
This game became horrible in HW + latest build. Lines are all over the place and are now present in all renderers at every resolutions. Is there a specific setting that I missed ?

**Comment by refractionpcsx2** [comment]
even native resolution?

**Comment by Immersion95** [comment]
> 

Native works, sorry for the lack of precision.

Here is an example : 

![Street Fighter III - 3rd Strike_SLPM-65621_20230226191820](https://user-images.githubusercontent.com/47425204/221429018-7808718a-acf3-461d-80f9-1c94ed9b1432.png)

I didn't reopen the issue as I'm unsure if it's an accepted case

**Comment by refractionpcsx2** [comment]
I mean, there's absolutely no need to upscale in this game anyways since it's sprites, nothing will change, and you can override the resolution in the per game settings for this if you want to keep an upscale globally.

**Comment by Immersion95** [comment]
> 

Native works, sorry for the lack of precision.

Here is an example : 

![Street Fighter III - 3rd Strike_SLPM-65621_20230226191820](https://user-images.githubusercontent.com/47425204/221429018-7808718a-acf3-461d-80f9-1c94ed9b1432.png)

I didn't reopen the issue as I'm unsure if it's an accepted case

> I mean, there's absolutely no need to upscale in this game anyways since it's sprites, nothing will change, and you can override the resolution in the per game settings for this if you want to keep an upscale globally.

Unfortunately it's needed as the native resolution of the ps2 port isn't the same as the CPS3 arcade game, pixels are horrendous. Thanks anyway :).

**Comment by RedDevilus** [comment]
Making a texture pack for it might be better, but sprites dump them in weird orders if you want to adjust them.

**Comment by RandomGuyHere12** [comment]
For 2D games/fighters try using the shaders because its a 2d game meaning it wouldnt make sense to increase the internal res

**Comment by Immersion95** [comment]
I’ve made a patch for the japanese version that outputs the game at 384×448, which results in pixel-perfect native resolution, since upscaling is broken for this game :).

It should be in the official patches repo soon when my [PR](https://github.com/PCSX2/pcsx2_patches/pull/714) is accepted :).
