### ISSUE TITLE
[BUG]: Big Picture doesn't return after going back to game list

### ISSUE THREAD

**Issue by Zorklis** [PCSX2/pcsx2#6943]
### Describe the Bug

Currently as far as I can tell there's no real way to go back to the normal view. The one I found is broken.

### Reproduction Steps

Big Picture > View in the toolbar >> Game list/Game Grid.  

### Expected Behavior

Big Picture >> Normal view/Desktop view >> Big Picture ,etc.

### PCSX2 Revision

v1.7.3260

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Not a bug it's called system display.

**Comment by Zorklis** [comment]
Steam literally let's you switch back and forth, it's outdated concept if you have to close and turn on the program again

**Comment by stenzek** [comment]
Good for steam. Feel free to submit a patch/pull request if you don't like the way I set things up.

> If you can switch back to the game list view, you should at least get the option to turn the BP mode back on

Except you can? View -> System Display, as Jordan said above.

**Comment by Zorklis** [comment]
So if you can do it on the toolbar, that makes no sense why the button is not clickable 😅
