### ISSUE TITLE
[BUG]: Final Fantasy X Bugged Ifrit's Overdrive Rock

### ISSUE THREAD

**Issue by zelgodis** [PCSX2/pcsx2#6947]
### Describe the Bug

When the aeon ifrit performs its overdrive the rock he throws at the end is either invisible if setting aeon sequences to short in the game's settings, or black with artifacts if using default sequences.
### Short Sequence
![01](https://user-images.githubusercontent.com/99540953/187273861-26ced430-e823-4032-a224-30d933655c52.png)
![02](https://user-images.githubusercontent.com/99540953/187273870-ca9c0a5e-f97f-48ac-b8ba-295a0f8faf7d.png)
![03](https://user-images.githubusercontent.com/99540953/187273880-e56d59b8-5f2e-4254-b93e-6b95ace6ca77.png)
### Default Sequence
![04](https://user-images.githubusercontent.com/99540953/187274019-8488f556-775c-400d-a8cb-5bf1302c4fc0.png)
![05](https://user-images.githubusercontent.com/99540953/187274029-84829582-7104-4661-9e0c-f32104dc0417.png)
![06](https://user-images.githubusercontent.com/99540953/187274041-5e784ebd-b910-4e74-8ee4-1a9a876d0c52.png)
### Video
https://youtu.be/R1F3pXqdogM?t=639

### Reproduction Steps

Fill up the overdrive meter and use it.

### Expected Behavior

https://youtu.be/WVrkRbaiU8Y?t=816

### PCSX2 Revision

1.7.3260

### Operating System

Windows 10 (64bit)

### CPU

i5-7800

### GPU

GTX 1080

**Comment by Mrlinkwii** [comment]
Can you post a gs dump?

**Comment by zelgodis** [comment]
[Final Fantasy X International_SLPS-25088_20221001223841.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/9691249/Final.Fantasy.X.International_SLPS-25088_20221001223841.gs.xz.zip)
remove the .zip extension

**Comment by refractionpcsx2** [comment]
Your GS dump is broken, can you please try again, also please be sure you are on the latest version.

**Comment by zelgodis** [comment]
[Final Fantasy X International (Japan).dump.zip](https://github.com/PCSX2/pcsx2/files/9694020/Final.Fantasy.X.International.Japan.dump.zip)
this might not work since battles are random, and all of them weren't dumped, also after the ffx logo quickly press start, the intro sequence wasn't dumped either

**Comment by refractionpcsx2** [comment]
can you not just make a GS Dump? random stuff and blockdumps do not mix well.

**Comment by RedDevilus** [comment]
GSdumps
[IfritRock6947.zip](https://github.com/PCSX2/pcsx2/files/9711290/IfritRock6947.zip)

Screenshots
![Final Fantasy X_SCES-50490_20221005003419](https://user-images.githubusercontent.com/24227051/193942748-51f76904-66de-4ea6-bfbe-9b4a5ae94662.png)
![Final Fantasy X_SCES-50490_20221005003457](https://user-images.githubusercontent.com/24227051/193942782-36a948d2-ad0b-40b3-b4f3-e8865ee36965.png)

**Comment by RedDevilus** [comment]
Did you change the CRC level perhaps or the CRC itself? Might also be missing entry.

**Comment by RedDevilus** [comment]
Memcard saves
[SCES50490-FFX.zip](https://github.com/PCSX2/pcsx2/files/9711432/SCES50490-FFX.zip)

**Comment by zelgodis** [comment]
> Did you change the CRC level perhaps or the CRC itself? Might also be missing entry.
no

**Comment by Jakey757** [comment]
reproduced it on NTSC-U, i am unable to produce a working GS dump, much like everybody else here :x
![Final Fantasy X_SLUS-20312_20221119200208](https://user-images.githubusercontent.com/49990481/202877915-8f38a240-fd87-41e7-ba2e-96602b589b31.png)

**Comment by vcx33** [comment]
As of at least version 1.7.4550, this issue has been fixed

![Final Fantasy X International_SLPS-25088_20230604172014](https://github.com/PCSX2/pcsx2/assets/118646244/01da8173-e7a2-4af7-bf92-47251dffa312)
![Final Fantasy X International_SLPS-25088_20230604172015](https://github.com/PCSX2/pcsx2/assets/118646244/6b5cb0a9-e13d-4dd9-baa3-ae7995d7d29d)
