### ISSUE TITLE
[Feature Request]: Qt; Add "Ignore Pressure Modifier button" to controller mapping settings.

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#6948]
### Description

Strange request I know, as you could just simply NOT hold down the PressureMod button to make 100% the active sensitivity. BUT, there is a specific use case for this;

In MGS2 and 3, to raise/aim your rifle without firing you press Square at ~20%, and press it harder (say 100%) to fire.
If given the option to bind Ignore PresMod to a certain button, one could map Square as Square+PresMod(20%), and Triangle as Square+IgnorePresMod(100% when Triangle is held).  This would go back to the 20% when releasing Triangle, and still holding Square the entire time, allowing for aim-fire-keep aiming etc. without ever lowering the gun.
This would allow simply rolling your thumb over from Square to Triangle to actually fire (while still holding down Square), lessening the need for finger-gymnastics... It's a bit hard to explain, I'm sorry, but it would be a very welcome feature in Qt for the Metal Gear games at least for me. The final thing still keeping Wx as a preferred way to play.

### Reason

An alternative to this specific button/mapping would be to prehaps allow for several Pressure Modifier states/%'s bound to different inputs?

/ 

- "Ignore Pressure Modifier button" could instead be called "Force 100% pressure sensitivity when *(mapped input) is held".

### Examples

Explained (as best I could)

**Comment by stenzek** [comment]
I don't really understand this. What you're proposing sounds like you'd lose the ability to actually use the Triangle button. The intent of the modifier is to bind it to an additional button, in which case when you released the pmod button, square would go from 20% back to 100%.

> An alternative to this specific button/mapping would be to prehaps allow for several Pressure Modifier states/%'s bound to different inputs?

Which controller actually has enough free buttons to support this? I can't really think of any, except maybe the Elite Xbox controllers with the paddle buttons.

**Comment by jonasos3** [comment]
Yes, in this case one would lose the ability to use the Triangle button. Then triangle could be bound to touchpad, or a keyboard button, as it is not used much in the game.

More pmod buttons/mappings/%'s would allow for example to bind Square on the controller as Square+Pmod1(20%), and Triangle on the controller as Square+Pmod2(100%). This would allow aim-fire-aim etc in a much more intuitive way than having to release a button (pmod) to actually fire :)

An alternative would be adding "Pressure at 100%" to the macro settings, allowing it to override the Pmod button if they are both held at the same time I guess.

**Comment by stenzek** [comment]
> Yes, in this case one would lose the ability to use the Triangle button. Then triangle could be bound to touchpad, or a keyboard button, as it is not used much in the game.

**Comment by stenzek** [comment]
> Yes, in this case one would lose the ability to use the Triangle button. Then triangle could be bound to touchpad, or a keyboard button, as it is not used much in the game.

And this is the crux of the issue. You're only thinking about one game. We have to find a general solution which works for thousands of games. And losing one of the face buttons/making it inconvenient is not a good general solution.

**Comment by jonasos3** [comment]
Yes, I understand :) More Pmod buttons could be mapped to different buttons of course, and I'm sure more people would find a use for this. But yes, my issue mainly concerns the mgs games.

**Comment by jonasos3** [comment]
More mapping options would somewhat bring back the functionality from Wx, where each button could be mapped with pressure % individually. Say you want Circle to only be at 20% for a certain game, you could have Pmod 3 as 20%, and map circle as Circle+Pmod3. In a round-about way.. Per-game controller configs are available, so it wouldn't affect other games. But yeah, I know it's niche :)

**Comment by stenzek** [comment]
I'm going to close this as not planned since it's too niche, and because I don't have any intentions on changing the current pressure mod system (aside from adding a different "initial" pressure value). 

You're welcome to implement it yourself, but it's silly to keep issues around that we're not planning on changing.

**Comment by refractionpcsx2** [comment]
If you really need specific pressure control like that, I would recommend you get a DS3 controller and use DSHidMini, which allows you to use proper pressure in PCSX2.

**Comment by jonasos3** [comment]
Yeah thanks, that's a good solution as well :) Can also use some creative mapping in reWASD to simulate a kind-of solution.. Or just use Wx of course, for a while longer. But anyway, thanks for the time both of you, I really appreciate all your work!
