### ISSUE TITLE
[BUG]: Pausing breaks the screen in Waga Ryuu o Miyo - Pride of the Dragon Peace (Japan) with hardware rendering

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6950]
### Describe the Bug

Using hardware rendering, pausing turns the screen into a very small square. Tested with vulkan at native resolution. Software works fine.

### Reproduction Steps

Get to gameplay and pause while using a hardware renderer. After a few seconds the graphics will break.

### PCSX2 Revision

pcsx2-v1.7.3261-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Software

![Capture](https://user-images.githubusercontent.com/96800307/187347718-7f0fb9dd-9f49-4462-8aa1-c423e6bf5cd3.PNG)

Hardware

![Capture2](https://user-images.githubusercontent.com/96800307/187347729-6dbe4bf2-fcfe-4a70-994e-f1d5ecae61f1.PNG)

### Logs & Dumps

[Waga Ryuomiyo - Pride of the Dragon Peace_SCPS-15080_20220830140831.zip](https://github.com/PCSX2/pcsx2/files/9449516/Waga.Ryuomiyo.-.Pride.of.the.Dragon.Peace_SCPS-15080_20220830140831.zip)

**Comment by Mrlinkwii** [comment]
on v1.7.4977 its a bit different 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/2adb79b3-6707-45ea-b4c5-90dea51a07d3)
 , just to note you have to run the game
