### ISSUE TITLE
[BUG]: Graphics in Keiei Simulation - Jurassic Park (Japan) are severely broken with hardware rendering

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6953]
### Describe the Bug

![_SLPM-62346_20220830180430](https://user-images.githubusercontent.com/96800307/187384093-19a86741-459b-44ce-b0a7-9b5365f2fb72.png)

![_SLPM-62346_20220830180434](https://user-images.githubusercontent.com/96800307/187384158-7fbee4d8-56ae-4f67-b5f3-5f6a895fc51e.png)

### Reproduction Steps

Start a mission in the game with a hardware renderer

### PCSX2 Revision

pcsx2-v1.7.3261-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[_SLPM-62346_20220830180434.zip](https://github.com/PCSX2/pcsx2/files/9450998/_SLPM-62346_20220830180434.zip)

**Comment by marcoluc97** [comment]
US and EU ver too. I think it was related to mipmapping... in SW works fine but so much slower.
