### ISSUE TITLE
[BUG]: Launched game exits to Big Picture in windowed mode

### ISSUE THREAD

**Issue by Immersion95** [PCSX2/pcsx2#6956]
### Describe the Bug

I launch pcsx2 fullscreen with the -bigpicture command. When I start a game and then exit, it returns to the menu but goes to windowed mode instead of staying in fullscreen mode. I then have to go to fullscreen mode again.

### Reproduction Steps

- Start PCSX2 with Big picture in DX11/12 Exclusive Fullscreen
- Launch a game
- Exit with the Big Picture menu
- Big Picture goes to windowed mode instead of staying in fullscreen mode

### Expected Behavior

Exits to Big Picture - Fullscreen

### PCSX2 Revision

v1.7.3262

### Operating System

Windows 11

**Comment by Immersion95** [comment]
> * I launched FS Big Picture
> 
>     * Ran a game & exited thru BP
> 
>     * The main window showed up (this only happens when you don''t put on nogui)
> 
>     * Big Picture is still Fullscreen

Sorry I totally forgot to mention that it's happening in Exclusive fullscreen - DX11/DX12

**Comment by JordanTheToaster** [comment]
Works correctly here and returns in fullscreen as expected on current master.
