### ISSUE TITLE
[BUG]: Gradius V cutscene graphical glitch

### ISSUE THREAD

**Issue by pjagiello** [PCSX2/pcsx2#6958]
### Describe the Bug

Note: I'm pretty sure this is the same bug as #2070, but this one was closed because of lack of feedback of the original reporter, so I created a new one, hopefully that's fine.

In Gradius V, there are pretty noticeable glitches in the small cutscene in stage 2, after the couple first waves of enemies (some kind of texture flashing in the background).

I'm using PCSX2 on linux, built from the master branch, renderer OpenGL (the glitch does not happen in the software renderer).

In the previous ticket a GS dump and a screenshot was requested, so I attached it here.

### Reproduction Steps

Just play the game until a bit into stage 2, and wait for the "space anomaly forming" cutscene.

### Expected Behavior

No graphical glitches in the background.

### PCSX2 Revision

~~v1.7.0.4188~~ v1.7.3260 (not sure why the About window is showing the former, but it's the commit "[CMake: Throw error when building Qt with PACKAGE_MODE]")

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Intel i5-4200M

### GPU

Intel(R) HD Graphics 4600

### GS Window Screenshots

![Gradius V_SLUS-20712_20220830220750](https://user-images.githubusercontent.com/8558288/187534405-31f061fa-8517-41a4-b964-2cce946fc4b5.png)

### Logs & Dumps

[Gradius V_SLUS-20712_20220830220750.gs.gz](https://github.com/PCSX2/pcsx2/files/9456401/Gradius.V_SLUS-20712_20220830220750.gs.gz)

**Comment by omega-tuna** [comment]
Here's a savestate right before it happens with 77ea599. Not sure if it'd be helpful at all
[SLUS-20712 (E939D95E).04.p2s.zip](https://github.com/PCSX2/pcsx2/files/10047000/SLUS-20712.E939D95E.04.p2s.zip)

**Comment by pjagiello** [comment]
This is fixed for me after #8225 was merged - funnily enough GSdump does show garbage for a moment but it "fixes" itself immediately, in the actual game as of newest nightly the cutscene looks perfectly fine for me.
