### ISSUE TITLE
PCSX2 fails to launch game on archlinux 64 bit

### ISSUE THREAD

**Issue by Xenphor** [PCSX2/pcsx2#696]
Here's a screenshot of what it says:

http://imgur.com/rhoSQ8o

**Comment by gregory38** [comment]
Install pcsx2 debug package or ask the maintainer to keep the debugging symbol. Without info it is just a bunch of random number.

**Comment by Xenphor** [comment]
I built it again replacing
    -DCMAKE_BUILD_TYPE='Release'
with
    -DCMAKE_BUILD_TYPE='Debug'
in the PKGBUILD and I can get a debug window but when I press 'run' I get the same error and everything closes. Is there a way I can save the output? I have an emulog.txt file but that seems to contain most of the same stuff.

**Comment by gregory38** [comment]
I think you need to remove this option CMAKE_BUILD_STRIP

**Comment by gregory38** [comment]
See http://forums.pcsx2.net/Thread-PCSX2-Assertion-Failed-on-Archlinux

**Comment by gregory38** [comment]
Several fixed were done. Without any new, I close the issue.
