### ISSUE TITLE
[BUG]: The opening Capcom logo is a black screen in Snowboard Heaven (Japan) with hardware renderers 

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6965]
### Describe the Bug

The opening Capcom logo is a black screen when using hardware renderers. Tested with Vulkan at native resolution. Software works fine.

Software

![Capture](https://user-images.githubusercontent.com/96800307/187620521-e8becfc1-6e74-4ee4-8930-af57b5c072f7.PNG)

Hardware

![Capture2](https://user-images.githubusercontent.com/96800307/187620538-b50cbe06-849f-4174-90df-84837f0641f7.PNG)

### Reproduction Steps

Start the game with a hardware renderer and watch the opening logo.

### PCSX2 Revision

pcsx2-v1.7.3264-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Snowboard Heaven_SLPM-62027_20220831173010.zip](https://github.com/PCSX2/pcsx2/files/9459556/Snowboard.Heaven_SLPM-62027_20220831173010.zip)

**Comment by drachenschanze** [comment]
Gift (Europe) has the same problem.

Software

![Capture](https://user-images.githubusercontent.com/96800307/188908764-69583be1-7f60-4597-ba8d-68b42bf93c26.PNG)

Hardware

![Capture2](https://user-images.githubusercontent.com/96800307/188908801-4647c9af-52e3-497f-9e50-73df36da2ebb.PNG)

[Gift_ The_SLES-50276_20220908004801.zip](https://github.com/PCSX2/pcsx2/files/9507202/Gift_.The_SLES-50276_20220908004801.zip)

**Comment by Oymat** [comment]
None of the dumps seem to be having an issue on my end

**Comment by refractionpcsx2** [comment]
Tex in RT seems to fix Snowboard Heaven.  The Gift doesn't have a problem..

![image](https://user-images.githubusercontent.com/6278726/213880769-9894657c-093f-45c4-8325-e154e31eb824.png)
