### ISSUE TITLE
[BUG]: Yumeria (Japan) has graphical garbage all over the screen with hardware rendering

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6966]
### Describe the Bug

Using hardware there's red and green garbage all over the screen. Tested with Vulkan at native resolution. Software looks fine.

Software

![Capture2](https://user-images.githubusercontent.com/96800307/187644945-15e96eff-93dd-48f7-bc2e-c28a436ec41a.PNG)

Hardware

![Capture](https://user-images.githubusercontent.com/96800307/187645040-a4333692-8673-47bb-be16-c695b146e4c1.PNG)

### Reproduction Steps

Get to gameplay and use a hardware renderer.

### PCSX2 Revision

pcsx2-v1.7.3264-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Yumeria_SLPS-25235_20220831191904.zip](https://github.com/PCSX2/pcsx2/files/9460290/Yumeria_SLPS-25235_20220831191904.zip)

**Comment by refractionpcsx2** [comment]
Game just needs autoflush enabling.

![image](https://user-images.githubusercontent.com/6278726/187645944-6138cacf-6ebe-4bc6-84ff-7aaad8a34bab.png)

**Comment by drachenschanze** [comment]
@refractionpcsx2 Good to know. But I noticed another problem. There's a faint garbage line at the bottom of the screen that's only there with software.

Software

![Capture](https://user-images.githubusercontent.com/96800307/187648211-ab763085-1515-48b9-b8cc-c78d33967216.PNG)

[Yumeria_SLPS-25235_20220831193842.zip](https://github.com/PCSX2/pcsx2/files/9460388/Yumeria_SLPS-25235_20220831193842.zip)



Vulkan at native

![Capture2](https://user-images.githubusercontent.com/96800307/187648499-2eae979c-e49f-44fe-8cd6-53ffbad8fe41.PNG)
