### ISSUE TITLE
[start emulator big picture mode

### ISSUE THREAD

**Issue by asp0909** [PCSX2/pcsx2#6972]
### Description

the big picture mode is designed to control the emulator with a gamepad... but it must by obligation start in qt mode... the duckstation emulator has nogui mode and this one does give the emulator that function... I hope you understand me. ..and thanks for all that has been achieved guys!

### Reason

this feature makes it easy for the user to start the emulator without using the keyboard and mouse...very practical when using a frontend

### Examples

duckstation nogui

**Comment by Mrlinkwii** [comment]
launch with -bigpicture on the command line.
