### ISSUE TITLE
[BUG]: [Achievements 2.0 PR] new build crashing on launch with "Entry Point Not Found" error

### ISSUE THREAD

**Issue by malasdairm** [PCSX2/pcsx2#6975]
### Describe the Bug

Attempting to run pr6883 - d8037fc gives this error:

pcsx2-qtx64-avx2.exe - Entry Point Not Found

The procedure entry point MapViewOfFile3 could not be located in the dynamic link library D:\[PCSX2 directory]]pcsx2-qtx64-avx2.exe.

Same/similar error with SSE4 version. Tried to solve through Microsoft Visual C++ repairs, uninstalls, reinstalls - nothing. Attempted to install "over" a previous, functioning installation - same error. Could not find other solutions to get around this. All previous builds worked A-OK out of the box and continue to work.

PC Specs:
CPU: Intel Core i5-4440 @ 3.10 GHz
GPU: Intel HD Graphics 4600
RAM: 8 GB
OS: Windows 10 Enterprise 2016 LTSB 64-bit

Tried all possible combinations of installing MS VC++ 12, 13, and 15-22.

### Reproduction Steps

- running pcsx2 executable on this config.

### PCSX2 Revision

1.7.0.0 - Achievements 2.0 #6883 - d8037fc

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
post this on the pr not here

**Comment by JordanTheToaster** [comment]
Your OS is out of date for the Qt builds.
