### ISSUE TITLE
[BUG]: Urban Freestyle Soccer (Europe) has garbage all over the screen with hardware renderers

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6984]
### Describe the Bug

Graphical garbage all over the screen with hardware. Tested with Vulkan at native resolution. Might need the same fix as Yumeria (Japan).

Software

![Capture2](https://user-images.githubusercontent.com/96800307/188055628-1d54b7e3-dfb6-4783-aba5-d46aa2a16ae0.PNG)

Vulkan

![Capture](https://user-images.githubusercontent.com/96800307/188055642-d814745d-b03f-44bf-869c-a7a073629a7f.PNG)

### Reproduction Steps

Start the game with a hardware renderer. 

### PCSX2 Revision

pcsx2-v1.7.3273-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Urban Freestyle Soccer_SLES-50849_20220902134645.zip](https://github.com/PCSX2/pcsx2/files/9474757/Urban.Freestyle.Soccer_SLES-50849_20220902134645.zip)

**Comment by Mrlinkwii** [comment]
seesm still an issue of  v1.7.4517


![image](https://github.com/PCSX2/pcsx2/assets/17685135/55695696-5699-4bfd-a208-76958bc2b509)

**Comment by refractionpcsx2** [comment]
a really gross temporary fix... CPU Sprite BW 8 (512) with sprites + triangles
but yeah BW 8 is gross :P
![image](https://github.com/PCSX2/pcsx2/assets/6278726/79de8368-a1fa-4f42-aeed-f45d9543fc4f)

**Comment by refractionpcsx2** [comment]
Can this be rechecked? I think it's okay on master now.

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/a8d09793-65ec-4c2f-9ce2-75255ab98416)
it seems ok on master

**Comment by refractionpcsx2** [comment]
Cool, thanks :)
