### ISSUE TITLE
[BUG]: More assorted database errors

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6988]
### Describe the Bug

<details>
  <summary>Games addressed in #7055</summary>
  

Kanokon Esuii (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188461657-8239457c-cd9a-4c36-9a34-ce8397780fb2.PNG)

http://redump.org/disc/38279/
  
Harukaze P. S. - Plus Situation (Japan)

![image](https://user-images.githubusercontent.com/96800307/188374008-98e0016a-298c-4a68-986f-a2bcd5c90ac2.png)

http://redump.org/disc/33781/

Yukinko Daisenpuu - Sayuki to Koyuki no Hie Hie Daisoudou (Japan)

http://redump.org/disc/68820/

I.Q Remix+ - Intelligent Qube (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188324112-bf0000d4-c900-4057-88ad-182e7d6d9b9f.PNG)

http://redump.org/disc/15925/

Kikou Souhei Armodyne (Japan)

![Capture5](https://user-images.githubusercontent.com/96800307/188554267-9e3b6db2-1f76-4374-9e01-123969d6dfa7.PNG)

http://redump.org/disc/32433/

Ikuze! Onsen Takkyuu!! (Japan)

![Capture2](https://user-images.githubusercontent.com/96800307/188374200-9909ea25-2a9f-47f9-991d-aaf8ece2db8b.PNG)

http://redump.org/disc/26089/

Buile Baku (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188321925-87f4afe4-4190-4353-9eab-d540b5c8c5ac.PNG)

http://redump.org/disc/20889/

Hametsu no Mars (Japan)

http://redump.org/disc/28583/

![Capture](https://user-images.githubusercontent.com/96800307/188297806-157c99fa-940f-42dc-87f6-cc0cdf126204.PNG)

La Pucelle - Hikari no Seijo Densetsu (Japan) (Genteiban)

![Capture](https://user-images.githubusercontent.com/96800307/188500815-4e89efcd-35c9-415c-be79-7c49a7b28ed7.PNG)

http://redump.org/disc/29258/

Gintama Gin-san to Issho! Boku no Kabuki-chou Nikki (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188443188-ad9b6f2f-3ad7-4fa8-9dff-74c43f858404.PNG)

http://redump.org/disc/39894/

George of the Jungle and the Search for the Secret (USA)

![Capture](https://user-images.githubusercontent.com/96800307/189063269-9123939f-e977-4067-9bd4-2658ff21cc0a.PNG)

http://redump.org/disc/32931/
</details>

----

## Games yet to be addressed

K-1 Premium 2004 Dynamite!! (Japan)

http://redump.org/disc/38079/

Sanyo Pachinko Paradise 10 - Gen-san Okaeri! (Japan)

http://redump.org/disc/43842/

School Rumble - Neru Musume wa Sodatsu. (Japan)

http://redump.org/disc/29859/

XI5 - Aqui Ohyeongje (Korea)

http://redump.org/disc/74234/

Zeonic Front - Kidou Senshi Gundam 0079 (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188131982-fe9e00ec-a9fc-4bda-b0ad-34e4cd033b59.PNG)

http://redump.org/disc/31935/

Crescent Suzuki Racing (Europe)

![Capture2](https://user-images.githubusercontent.com/96800307/188297836-3b9f155e-4935-431b-87ed-26957a5a6161.PNG)

http://redump.org/disc/15480/

FIVB Volleyball World Cup - Venus Evolution (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188320764-44872a39-95ca-4910-9c2a-91117e697229.PNG)

http://redump.org/disc/30259/

Giant Robo - The Animation - Chikyuu ga Seishi suru Hi (Japan)

![Capture2](https://user-images.githubusercontent.com/96800307/188443362-57f66cbe-09a0-4739-bcaa-06b5106067c3.PNG)

http://redump.org/disc/60140/

Kikou Busou G-Breaker - Legend of Cloudia (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188478810-f68b790f-d7f7-422d-9d3b-694e90be6797.PNG)

http://redump.org/disc/40940/

KOF - Maximum Impact Regulation A (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188491838-00cc6c05-84f5-4ed3-8dc2-60c00fa37b04.PNG)

http://redump.org/disc/9455/

KeyboardMania (Japan) shouldn't be all capitalized. 

![Capture2](https://user-images.githubusercontent.com/96800307/188492000-55878fab-104a-4757-aeab-3096061d5842.PNG)

http://redump.org/disc/33532/

_summer Double Sharp (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188604505-4f65370d-6992-4443-9142-faf6a3773010.PNG)

http://redump.org/disc/38485/

Artlist Collection - The Dog Island - Hitotsu no Hana no Monogatari (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/188851730-4df84c5d-4ebf-41cf-adf5-a8c8695aacdb.PNG)

http://redump.org/disc/59021/

Assault Suits Valken (Japan)

![Capture2](https://user-images.githubusercontent.com/96800307/188851958-c12a9233-6d39-4ef2-afc7-065172fe9710.PNG)

http://redump.org/disc/24392/

Yoshitsune Eiyuuden Shura - The Story of Hero Yoshitsune Shura (Asia)

![Capture](https://user-images.githubusercontent.com/96800307/188945129-1f0ace22-e49b-4e77-b130-96eb95ac2c5e.PNG)

http://redump.org/disc/68882/

Jim Henson's Muppets Party Cruise (USA)

![Capture](https://user-images.githubusercontent.com/96800307/188957467-d1b7f181-4557-4cb0-9e23-9d02614c81d6.PNG)

http://redump.org/disc/32895/

### Reproduction Steps

Look at the game list

### PCSX2 Revision

pcsx2-v1.7.3274-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

**Comment by F0bes** [comment]
I've gone ahead and edited the original post, hiding the games which have be fixed by #7055

**Comment by kevin98761234** [comment]
SLPM-55122" is now "Sengoku Musou 2".
The correct name is "Gundam Musou 2".
Also, there is no need for "Sengoku Musou 2" related memorycardFilters.
http://redump.org/disc/39944/
