### ISSUE TITLE
[BUG]: Final Fantasy X Baaj Temple crash, Vulkan

### ISSUE THREAD

**Issue by GetBucked** [PCSX2/pcsx2#6992]
### Describe the Bug

The game crashed upon entering the fight with the sahagins after the Zanarkand tutorial when using Vulkan.

### Reproduction Steps

Enter the fight with the sahagins as normal while using the Vulkan renderer.

### PCSX2 Revision

v1.7.3275

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 2500u

### GPU

RX 560X

### Logs & Dumps

[crash-2022-09-04-09-46-33-791.txt](https://github.com/PCSX2/pcsx2/files/9484901/crash-2022-09-04-09-46-33-791.txt)

**Comment by stenzek** [comment]
Have you verified the hash of your dump? Corrupted dumps are often causes of such issues.

**Comment by GetBucked** [comment]
Yeah, hash checks out.

**Comment by stenzek** [comment]
Working fine here. Could be a config issue or something else.

**Comment by GetBucked** [comment]
Might have been ReShade
