### ISSUE TITLE
[BUG]: Skipping the opening logo screen breaks the graphics in Giant Robo - The Animation - Chikyuu ga Seishi suru Hi (Japan) with hardware

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6994]
### Describe the Bug

Skipping the opening logo while using a hardware renderer causes half of the screen to disappear. Tested with Vulkan at native resolution. Doesn't happen with software.

![Capture](https://user-images.githubusercontent.com/96800307/188445965-755bbcf5-80b6-4414-98a7-8a33ac620517.PNG)

### Reproduction Steps

Start the game with a hardware renderer and press start to skip the opening logo screen. 

### PCSX2 Revision

pcsx2-v1.7.3277-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Giant Robo - The Animation_SLPM-62526_20220905220400.zip](https://github.com/PCSX2/pcsx2/files/9489638/Giant.Robo.-.The.Animation_SLPM-62526_20220905220400.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/e1f8148f-3fb7-4ffa-8f77-5c4a522bfafe)

seems fine on v1.7.4688 when you run the  game , the gs dump is broken on both HW/SW
