### ISSUE TITLE
[BUG]: Memory card info is a black screen in Giant Robo - The Animation - Chikyuu ga Seishi suru Hi (Japan) with hardware

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6995]
### Describe the Bug

When you start the game a screen comes up with memory card information. With hardware this screen is just black. Tested with Vulkan at native resolution. Doesn't happen with software.

Software

![Capture](https://user-images.githubusercontent.com/96800307/188446916-11ef0e6b-7b41-4e9b-99f3-506b992951ae.PNG)

Vulkan

![Capture2](https://user-images.githubusercontent.com/96800307/188446935-07d1cd31-67d7-4eeb-bbf3-43a67b1d13ee.PNG)

### Reproduction Steps

Start the game with a hardware renderer. 

### PCSX2 Revision

pcsx2-v1.7.3277-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Giant Robo - The Animation_SLPM-62526_20220905221208.zip](https://github.com/PCSX2/pcsx2/files/9489678/Giant.Robo.-.The.Animation_SLPM-62526_20220905221208.zip)

**Comment by refractionpcsx2** [comment]
Seems to be fine these days.
