### ISSUE TITLE
[BUG]: EverBlue 2 Causing MTGS Thread Died Error

### ISSUE THREAD

**Issue by thespieler11** [PCSX2/pcsx2#6997]
### Describe the Bug

PanDubz requested that I make this Bug report

This bug causes a hard crash of PCSX2 with an error popup window that states "MTGS Thread Died" I must close out of that window for me to regain control of my computer. This only happens when taking photos with the ingame underwater camera mechanic. It seems to happen more often when im exploring an underwater wreck rather than the open water. There are other graphical issues, such as Album photo thumbnails showing up red, or when picking up an item inside of a wreck, a Silhouette of the item is visible on the screen even after you move on from picking up that item. Not sure if either of those other issues are relevant.  

** with PanDubs I tested running Software mode rendering and Vulkan with native resolution. The issue with the same error persists.**

### Reproduction Steps

1. Complete the photographer quest or at least get to that part of the game where she gives you a camera. (first or second quest)
2. Go and take photos with the camera. You can do this whenever you are underwater or in a wreck. When in the open water sometimes I can take 20 photos straight with no issue but sometimes it will crash. it seems the frequency of the crash is higher when taking photos inside of a wreck, such as the airplane or ferry. The game will completely lock up or go to black screen when it freezes. Alt-tabbing or launching task manager are the only ways to get to the error pop up so that you can close it out and continue using your computer.

### Expected Behavior

Taking photos in the game is instant. Pulling left trigger half way on xbox one controller should show the camera frame outline and allow you to aim your shot. Fully pulling the left trigger will snap the photo. There is no prompt, no loading, no saving occurring. It just takes the photo when you fully pull left trigger when swimming in the ocean.

### PCSX2 Revision

1.7.3278

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5700G

### GPU

Ryzen 7 5700G

### GS Settings

All Default outside of testing with Software/Vulkan

### Emulation Settings

Tested MTVU On/Off but issue persists with both settings

### Logs & Dumps

[crash-2022-09-05-18-37-17-133.zip](https://github.com/PCSX2/pcsx2/files/9492375/crash-2022-09-05-18-37-17-133.zip)

**Comment by thespieler11** [comment]
Same error, MTGS Thread Died error is occuring Outside of 3D Gameplay. Was at town square talking to NPC's and received the error. I will test this same spot again tomorrow to see if its possible that the game can be completed or if its a hard crash in the same spot.

**Comment by Mrlinkwii** [comment]
can this be checked on lastest nightly ?

**Comment by refractionpcsx2** [comment]
No response, closing. If this continues we can reopen it.
