### ISSUE TITLE
[BUG]: Water is broken in Jim Henson's Muppets Party Cruise (USA) with both software and hardware

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#7008]
### Describe the Bug

Water in the opening is broken. Tested with software and Vulkan at native resolution and happens with both. 

![Capture](https://user-images.githubusercontent.com/96800307/188958598-3ce851db-b133-4509-afff-05625664f9af.PNG)

### Reproduction Steps

Start the game and watch the opening cutscene of the boat. 

### PCSX2 Revision

pcsx2-v1.7.3284-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Muppets Party Cruise_ Jim Henson_s_SLUS-20635_20220908051030.zip](https://github.com/PCSX2/pcsx2/files/9508976/Muppets.Party.Cruise_.Jim.Henson_s_SLUS-20635_20220908051030.zip)

**Comment by drachenschanze** [comment]
@refractionpcsx2 Someone apparently found the solution 2 years ago. So I don't know why it's still broken. Some hack needs to be turned off or something. 

https://github.com/PCSX2/pcsx2/issues/3148

**Comment by refractionpcsx2** [comment]
try disabling the mVU Flag hack.

**Comment by drachenschanze** [comment]
@refractionpcsx2 Yeah that fixed it. From now on whenever I find a game with horribly broken graphics I'll try turning that off first.

![Capture](https://user-images.githubusercontent.com/96800307/188961807-381e3d68-3c12-49d0-ab2a-fb2d1c1a3e98.PNG)
