### ISSUE TITLE
[Feature Request]: Add More Macros

### ISSUE THREAD

**Issue by Brunokenway07** [PCSX2/pcsx2#7009]
### Description

Macros work great, but it only lets set 4. Is it possible to add more?

### Reason

It's an important tool and it'd be nice to be able to use it more

### Examples

I've been able to bind a button to more than one key in the .ini file but writing a new "macro5" doesn't work

**Comment by stenzek** [comment]
Is there actually a tangible benefit to more than 4? It's not like you have enough buttons on the controller to map them..

**Comment by Brunokenway07** [comment]
I guess it pretty much benefits keyboard users
