### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Skeezo6o** [PCSX2/pcsx2#7011]
### Describe the Bug

hi since the new pcsx2 update a few days ago i havent been able to get audio in the emulator only happens while using pcsx2 and no th app is not muted please help

### Reproduction Steps

running pcsx2

### PCSX2 Revision

v1.7.3275

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

steam deck

### CPU

four-core/eight-thread Zen 2

### GPU

AMD RADV VANGOGH

**Comment by stenzek** [comment]
Nothing has changed recently with audio. Are you using the appimage? Wx or qt?

**Comment by Skeezo6o** [comment]
the appimage i guess i know its the one in discover. tried deleting and reinstalling tried restarting nothing. probably would work again if i restore but i would lose everything

**Comment by stenzek** [comment]
Then it's probably the flatpak. We don't have anything to do with that, so we can't fix any issues, or provide any support. Speak with your packager instead.
