### ISSUE TITLE
[BUG]: Dithering doesn't seem to work in Agassi Tennis Generation (USA) with hardware rendering

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#7012]
### Describe the Bug

The game is meant to have a dithering effect in the background to color in the boxes. Using hardware this effect is completely missing. Tested with Vulkan at native resolution and x5. Tested with dithering off, scaled and unscaled. 

Software

![Capture2](https://user-images.githubusercontent.com/96800307/189040953-def1c842-821d-4d44-b8cb-2c87de2c831f.PNG)

Vulkan at native resolution with dithering on.

![Capture](https://user-images.githubusercontent.com/96800307/189041014-2a398403-2785-4082-adc6-57908790c2c3.PNG)

### Reproduction Steps

Start the game and get to the match configuration screen.

### Expected Behavior

There should be a dithering effect on the screen. 

### PCSX2 Revision

pcsx2-v1.7.3286-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[Agassi Tennis Generation_SLUS-20446_20220908151838.zip](https://github.com/PCSX2/pcsx2/files/9523798/Agassi.Tennis.Generation_SLUS-20446_20220908151838.zip)

**Comment by lightningterror** [comment]
Needs maximum blending, will only work on opengl/vulkan as it requires sw blending.
