### ISSUE TITLE
[BUG]: Hardware rendering breaks distant objects in Barbie Horse Adventures - Riding Camp (USA)

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#7013]
### Describe the Bug

Hardware rendering breaks distant objects like bushes and mountains. Tested with Vulkan at native resolution. 

Software

![Capture4](https://user-images.githubusercontent.com/96800307/189069127-c12ef95d-6d28-4ae1-a8bd-3deda965bbbc.PNG)

Hardware

![Capture](https://user-images.githubusercontent.com/96800307/189069175-2a2fe9d4-feb6-4dae-9fff-43a510ab8819.PNG)

Software

![Capture3](https://user-images.githubusercontent.com/96800307/189069229-ae1cde84-f50f-4d2c-a3d2-ed5b0cc9c83a.PNG)

Hardware

![Capture2](https://user-images.githubusercontent.com/96800307/189069279-f58a8471-e7a2-47ee-ad56-ef124e9781e2.PNG)

### Reproduction Steps

Start the game and turn towards the mountain or bushes with a hardware renderer. 

### PCSX2 Revision

pcsx2-v1.7.3287-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[bush.zip](https://github.com/PCSX2/pcsx2/files/9524938/bush.zip)

[rocks.zip](https://github.com/PCSX2/pcsx2/files/9524940/rocks.zip)

**Comment by drachenschanze** [comment]
Also I'm not sure if this is a bug or not but nearest texture filtering makes the game look like this. 

![Capture](https://user-images.githubusercontent.com/96800307/189071783-0d20e8f4-e59a-495a-bcd1-796e90eec332.PNG)

**Comment by refractionpcsx2** [comment]
Does enabling mip mapping help? (set filleting back to bilinear ps2)

**Comment by drachenschanze** [comment]
@refractionpcsx2 Full causes it, automatic fixes it.

**Comment by refractionpcsx2** [comment]
Then, don't change it from automatic?
