### ISSUE TITLE
[BUG]: PCSX2 QTX64-AVX2 version with Gran Turismo 4 crashes in software rendering mode on game launch

### ISSUE THREAD

**Issue by JetSetter1984** [PCSX2/pcsx2#7015]
### Describe the Bug

Game boots fine in Standard PCSX2 latest version, but crashes in QT64 version as soon as launched. I have this crash log attached.
[crash-2022-09-08-14-59-32-420.txt](https://github.com/PCSX2/pcsx2/files/9527459/crash-2022-09-08-14-59-32-420.txt)

### Reproduction Steps

Launch Gran Turismo 4 ISO in software mode, latest PCSX2 QT build.

### Expected Behavior

Game was running fine before. I have not used the emulator for a while so would not know when it was good last, but was around 2 months ago with this game.

### PCSX2 Revision

v1.7.2949-windows-64bit-AVX2-Qt

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
>v1.7.2949-windows-64bit-AVX2-Qt

please check  latest master

**Comment by stenzek** [comment]
Working fine here. Maybe invalid.

**Comment by JetSetter1984** [comment]
I have it working in the other launchers, just not the qt build. Does the log not show anything of interest?

**Comment by JetSetter1984** [comment]
OK so strangely it does boot with vulkan but not in software mode. I like to use software to get around the visual bugs.

**Comment by refractionpcsx2** [comment]
What version are you running now?

**Comment by stenzek** [comment]
> Does the log not show anything of interest?

No, not unless you drop the symbol file/pdb next to it. Or upload the actual crash dump file.

**Comment by JetSetter1984** [comment]
1.7.2949

**Comment by refractionpcsx2** [comment]
We asked you to update, because we know it had problem at one point. Please update. We don't support old builds.

We don't want a dump.

**Comment by stenzek** [comment]
*except if it still crashes on the latest build :)

**Comment by refractionpcsx2** [comment]
it is not. you're about 250 behind.

**Comment by stenzek** [comment]
No, it's not. You're ~300 commits behind.

**Comment by JetSetter1984** [comment]
Damn it is the latest on the auto updater... not on buildbot. I will try

**Comment by JetSetter1984** [comment]
I just tried latest qt 64 build, it is the same in software mode...

**Comment by stenzek** [comment]
Then upload the crash dump (zip it). But I feel like this is going to be a support issue, not an actual bug.

**Comment by refractionpcsx2** [comment]
I just tried the latest build with both the EU and US versions of the game, in software mode, and neither crashed.

So either
1. You're not being completely honest with us about your setup/version
2. something else is interfering
3. you ISO is broken.

**Comment by JetSetter1984** [comment]
I'm being honest, I can boot in vulkan then switch to software but if boot in software I crash to desktop. Never mind I will just use f9 to switch after booting... I feel like it has something to do with applying cheats/patches toggle as that is the message displayed on screen just before the crash. It tells me none are available then crashed. Then I uncheck the boxes and it still says no patches available etc. If I click boot default it does load... Wierd.

**Comment by stenzek** [comment]
If you're not going to provide what's requested, then this is now a support issue and not a bug report.
