### ISSUE TITLE
[BUG]: Shin Megami Tensei: Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon - Broken font texture dumping

### ISSUE THREAD

**Issue by xtremegat** [PCSX2/pcsx2#7034]
### Describe the Bug

Dumping the font texture will result in several images with the letters altering their positions as you pass to the next dialogue.
I've seen the same happen in Digital Devil Saga and Shin Megami Tensei: Nocturne.

![Shin Megami Tensei - Devil Summoner 2 - Raidou Kuzunoha vs  King Abaddon_SLUS-21845_20220911014029](https://user-images.githubusercontent.com/80413419/189513715-486d5785-adf7-41ba-a121-5732a262326c.png)
![Shin Megami Tensei - Devil Summoner 2 - Raidou Kuzunoha vs  King Abaddon_SLUS-21845_20220911014722](https://user-images.githubusercontent.com/80413419/189513716-b5fbcad1-ab70-4c18-bf72-9d0465f5d310.png)

![25f292bd1da21fe1-da441b40f63f0670-00006654](https://user-images.githubusercontent.com/80413419/189513556-90eaff91-0a24-4305-b32a-b2e81ece318f.png)
![639051c339cacb45-da441b40f63f0670-00006654](https://user-images.githubusercontent.com/80413419/189513558-084c3d5d-df82-4015-946b-67d9d2e92c26.png)

### Reproduction Steps

1. Open any dialogue and dump texture.

### PCSX2 Revision

v1.7.3301

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800x

### GPU

GTX 1070 ti

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/9541806/emulog.txt)

**Comment by lightningterror** [comment]
I don't see how that's an issue, means it uses a different texture.

**Comment by xtremegat** [comment]
As I said there it's not 1 or 2 texture images but **every** new text on the game is a different texture font unlike in the game's files that has 3 fonts, replacing one of them will only work until you pass to the next text resulting in hundreds of images just for one dialogue scene for example.
