### ISSUE TITLE
[BUG]: First input is ignored after Saving/Loading savestate or taking a screenshot (Pause Menu)

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#7040]
### Describe the Bug

After saving/loading savestate or taking a screenshot in the PCSX2 Pause Menu it will ignore the first input if it's opened again. Happens with both SDL and Xinput.

### Reproduction Steps

1. Save/load savestate or take a screenshot in the PCSX2's Pause Menu
2. Open it again
3. First input will be ignored, you will have to press a button twice to confirm

### Expected Behavior

It shouldn't ignore the input. This bug doesn't exist in DuckStation so it's odd.

### PCSX2 Revision

1.7.3303

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
can this be re-checked on latest nightly ?

**Comment by Blackbird88** [comment]
Still happens to me. Might be something to do with me having 240 Hz monitor and thus timing is off, dunno.

**Comment by DigitalMajestic** [comment]
Can't reproduce on latest master. 1.7.4370, macOS Ventura. I suggest visiting the discord for support.
