### ISSUE TITLE
[BUG]: GS: Memory allocation failure. on more games.

### ISSUE THREAD

**Issue by Nerboruto** [PCSX2/pcsx2#7048]
### Describe the Bug

some games give this error when playing a cutscene es.. metal slug 3 or Ace Combat: The Belkan War, ecc...
Ace Combat: Squadron Leader works perfectly without this error.
I have tried various backends graphics api and both the qt and vx version.
on qt a few times I managed to get out of the error by pressing esc and switching to the overlay and returning to the game.
on wx I think it can not be done.
resolution is irrelevant it also does the native one.
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/9565434/emuLog.txt)

### Reproduction Steps

Ace Combat: The Belkan War black screen or video freeze during cutscene audio is ok.
on qt a few times I managed to get out of the error by pressing esc and switching to the overlay and returning to the game.
overlay text corrupted.

### PCSX2 Revision

v1.7.3305

### Operating System

Windows 10 (64bit)

### CPU

xeon e3-1230v3

### GPU

quadro k620 2gb (gtx745)

### GS Settings

all to default setting or resolution scaling 2x nothing changes.
vulkan dx11 dx12 nothing changes.

### Logs & Dumps

[Uploading emuLog.txt…]()

**Comment by Nerboruto** [comment]
2gb vram is not enough to run the game at native resolution?
switching to the overlay with corrupted text and going back the game works perfectly ... in my opinion it's a bug.

**Comment by Mrlinkwii** [comment]
@Nerboruto this is a user support issue , please use the forum/discord :slightly_smiling_face:

**Comment by stenzek** [comment]
Not when you have many other programs running at the same time, also using VRAM.

DX11 generally shouldn't fail to allocate either - it'll fall back to system memory (and be very slow as a result). DX12 and Vulkan won't overcommit and will fail the allocation.

**Comment by Nerboruto** [comment]
> Not when you have many other programs running at the same time, also using VRAM.
> 
> DX11 generally shouldn't fail to allocate either - it'll fall back to system memory (and be very slow as a result). DX12 and Vulkan won't overcommit and will fail the allocation.

I closed all the software the vram is free.

**Comment by Nerboruto** [comment]
This sounds like 

> This sounds like a support issue, perhaps you're running out of VRAM (especially with only 2GB), you can post on the forums or Discord.
> 
> Please don't repost the same thing repeatedly in multiple issues.

This sounds like a support issue, but it is not. it is a bug in vram allocation. metal slug 3 is 2d neogeo game ... problem occurs when playing a cutscene movie. please reopen..

**Comment by JordanTheToaster** [comment]
There is no "allocation bug" this is a support issue simply due to your system it's that simple. You can see here even at native PCSX2 barley uses 410MB of VRAM.

![image](https://user-images.githubusercontent.com/80843560/190150236-b69a0711-e069-4f40-9be5-86919ad32ac2.png)

**Comment by Nerboruto** [comment]
> There is no "allocation bug" this is a support issue simply due to your system it's that simple. You can see here even at native PCSX2 barley uses 410MB of VRAM.
> 
> ![image](https://user-images.githubusercontent.com/80843560/190150236-b69a0711-e069-4f40-9be5-86919ad32ac2.png)

a simple question why if i switch to the overlay with the esc key afterwards everything works fine and i can play as much as i want? 
I also monitored the vram and I have a lot of free ...to throw away
moreover, it does not do it only on this machine ...

**Comment by Nerboruto** [comment]
I tried texture preloading to partial and problem is solved. I noticed that leaving the option as before when the video starts, the vram goes up to 1.7gb and freezes the video ...
apologies to all and thanks
