### ISSUE TITLE
[BUG]: Qt version use command line cannot start an image with a Chinese character filename

### ISSUE THREAD

**Issue by crashGG** [PCSX2/pcsx2#7054]
### Describe the Bug

QT version use command line cannot start an image with a Chinese character filename, but it's ok in wxWidgets version.

<img width="591" alt="2022-09-15_220923" src="https://user-images.githubusercontent.com/80488411/190493018-63f1cc6c-1f24-49cf-ab73-bcd7d29a24e6.png">

### Reproduction Steps

use command line:
start pcsx2x64-avx2.exe "伊苏4：太阳的假面.chd"

### PCSX2 Revision

v1.7.3312

### Operating System

Windows 10 (64bit)

**Comment by CookiePLMonster** [comment]
Fixed in #7061
