### ISSUE TITLE
[BUG]: Folder Memory Cards No Longer Detected

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#7062]
### Describe the Bug

Any game or BIOS boot, folder memcards are not detected by the game. Reported to have worked on 3316, reported broken on 3317, confirmed broken on 3320.

### Reproduction Steps

Update to 3320, boot any game with a folder memcard, try to access it, game will report no memcard present.

### Expected Behavior

Memcard should be detected and game able to process it normally

### PCSX2 Revision

v1.7.3321

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Are you sure? 3317 is a GameDB update..

**Comment by BParks21** [comment]
If it's broken on 3320 why would it stop reading the folder format on 3317 for me? I'm confused?

**Comment by RedPanda4552** [comment]
Couldn't reproduce the issue on 3317. Something else is wrong with your folder memcard if it is not working on that build as well.

**Comment by BParks21** [comment]
> Couldn't reproduce the issue on 3317. Something else is wrong with your folder memcard if it is not working on that build as well.

Hmmm strange.

**Comment by BParks21** [comment]
Ok I fixed the folder format not working in 3317. I downloaded the wx build took my folder formatted card converted to a 32mb single card then converted it back to the folder format. After I did that the folder format started working in 3317, but doesn't work in the 3320 build.

**Comment by RedPanda4552** [comment]
Per a chance encounter in #help-windows, I got a lead that ejecting and reinserting the folder memcard will get the game to recognize it. Sure enough, that's exactly what happens. Eject the card, reinsert it, game works normally. Funny enough, this is the inverse of a prior behavior where a folder memcard would work on boot, but after ejecting and reinserting, it would no longer be detected. Mildly interesting.

From my digging so far it seems the root cause is the config **does** properly set EmuConfig.Mcd[0].Type when the card is opened, but something else switches it back to File afterwards which I have not yet been able to pin down. Still digging but I suspect some of the config changes may have created a little weirdness.
