### ISSUE TITLE
[BUG]: [Linux] PCSX2 Qt: NTSC framerate stays at 59,00 hz

### ISSUE THREAD

**Issue by DCMVM** [PCSX2/pcsx2#7072]
### Describe the Bug

NTSC framerate stays at 59,00 hz; no change in the settings, restoring to defaults or setting to 59,94 on the ini files work. Because of this, all NTSC games have stutter, making them annoying to play. May be caused by a rounding error? The ini files list the default as 59,939999. PAL games are not affected.

### Reproduction Steps

Fresh install of PCSX2 Qt version through any means (flatpak, appimage...). Does not happen on any WxWidgets version, or Windows. Unknown if happens on macOS.

### Expected Behavior

The default framerate should be listed at 59,94, and the games should then run smoothly.

### PCSX2 Revision

v1.7.3327 (appimage)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 21; based on Ubuntu 22.04

**Comment by stenzek** [comment]
This smells like locale issues, since the comma....

What does `export | grep LANG` give you?

**Comment by DCMVM** [comment]
`declare -x GDM_LANG="en_GB"
declare -x LANG="en_GB.UTF-8"
declare -x LANGUAGE="en_GB"`
This is the output of the command.
On a side note, thanks for responding so quickly!

**Comment by Mrlinkwii** [comment]
@DCMVM  can you reset defaults for me

**Comment by DCMVM** [comment]
@Mrlinkwii If you mean pcsx2 defaults, the issue still persists, and if you mean locale, I don't really know if that is even possible, but I'm somewhat new to linux, so I wouldn't know, and google isn't much help

**Comment by stenzek** [comment]
Does running PCSX2 with `LC_ALL=en_US.UTF-8 /path/to/appimage` change anything?

**Comment by stenzek** [comment]
Okay. We'll leave this open then, I'm redoing the conversion routines to use non-locale-specific functions... it's just proving a little painful, since std::{from,to}_chars doesn't support float types in older versions of the standard library on Linux, including the 20.04 version :(

**Comment by DCMVM** [comment]
Well, then thank you for your help and good luck with the project, it's amazing!

**Comment by stenzek** [comment]
Try https://github.com/PCSX2/pcsx2/pull/7083, hopefully should sort it out.

**Comment by DCMVM** [comment]
The ini is now generated with 59.94 and qt seems to read it just fine, and modifications done in settings are properly reflected in the ini file, everything now works perfectly, no other issues (so far) to be seen!
I'm a bit new to github, should I close the issue?

**Comment by Mrlinkwii** [comment]
@DCMVM  leave it open and when the pr is merged the issue will be closed

**Comment by stenzek** [comment]
Great, thanks for checking!
