### ISSUE TITLE
[Feature Request]: PCSX2 Team I'm not reporting a bug

### ISSUE THREAD

**Issue by visious25** [PCSX2/pcsx2#7075]
### Description

Hi, can you convince RPCS3 Team to split the package to RPCS3-SSE4 and RPCS3-AVX2 like you did?
https://github.com/RPCS3/rpcs3/issues/12495

### Reason

My laptop is a little bit old.

### Examples

![CPU-X-CPU](https://user-images.githubusercontent.com/81131095/191359705-fe00f634-1f50-4d31-a93a-6ffdb233e076.png)

![CPU-X-Graphics](https://user-images.githubusercontent.com/81131095/191359801-1e8c599c-eae1-45fd-9a36-39feec8d4d13.png)

**Comment by JordanTheToaster** [comment]
no

**Comment by clienthax** [comment]
no
