### ISSUE TITLE
[BUG]: Automatic Updater Dont Working

### ISSUE THREAD

**Issue by marcelinhoshow** [PCSX2/pcsx2#7076]
### Describe the Bug

![image](https://user-images.githubusercontent.com/44094119/191498485-1bca3128-996f-4fb5-84e7-9d420082bd00.png)
![image](https://user-images.githubusercontent.com/44094119/191498564-e4bc634b-ba6b-4b41-95fd-484572a4cc2f.png)
![image](https://user-images.githubusercontent.com/44094119/191498635-370aa1ec-ad9c-4c0e-af42-c80c1b01c695.png)

When trying to install updates through launcher update, it loads to download the files to update but it goes back to launcher update without performing the update!

### Reproduction Steps

1. Open PCSX2 version v1.7.3327 on Windows 11 with updated drivers and windows update
2. Click the launcher update download and install button

### Expected Behavior

It would update and reopen PCSX2 with the update performed and the new version showing next to the name in the program header

### PCSX2 Revision

v1.7.3327

### Operating System

Windows 11

**Comment by stenzek** [comment]
You'll need to post the emulog. Debug -> Enable File Logging, and restart and repeat. Disable afterwards. Log is in the `logs` directory.

**Comment by stenzek** [comment]
Closing due to lack of response, if you provide the required log we can reopen.
