### ISSUE TITLE
[BUG]: Severe Graphical Issues in EverBlue 1 PAL

### ISSUE THREAD

**Issue by thespieler11** [PCSX2/pcsx2#7077]
### Describe the Bug

Rainbow graphics over almost all textures in addition to Fuzzy 2D Screens, like a halo effect around text.

https://user-images.githubusercontent.com/27299034/191517147-41686cc9-6936-417f-9eb7-228e789c8725.MOV

![IMG_1659](https://user-images.githubusercontent.com/27299034/191517154-dbf47b8e-2e87-49b0-b464-c95537de7e2e.jpg)

### Reproduction Steps

Start the game

### Expected Behavior

Clear graphics

### PCSX2 Revision

1.7.3278

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5700G

### GPU

Ryzen 7 5700G

### Emulation Settings

Vulkan 3x internal res

**Comment by refractionpcsx2** [comment]
Can you do the following:

1. Update your PCSX2, 3278 is not the most recent
2. Reset your graphics settings, it's fine here

![image](https://user-images.githubusercontent.com/6278726/191517793-090c00d8-00ef-4ec0-91cd-ffe6264f1351.png)


Going to go ahead and assume this is a support issue, please use our forum or discord if you require help.
