### ISSUE TITLE
[Feature Request]: [Linux] Add native PipeWire support

### ISSUE THREAD

**Issue by SopaDeMacaco-UmaDelicia** [PCSX2/pcsx2#7078]
### Description

Add native PipeWire support for sound output.

### Reason

PipeWire is a modern audio server used in many distributives. And since many distros are ditching pulseaudio in favor of PW it kinda makes sense to make a native support.

### Examples

Basically any app that uses SDL2 for audio output with "SDL_AUDIODRIVER=pipewire" environment variable.

**Comment by stenzek** [comment]
This would better be directed to cubeb, as that's what we use for cross-platform audio output.

**Comment by SopaDeMacaco-UmaDelicia** [comment]
Got it.
