### ISSUE TITLE
[BUG]: Bugged graphics when using dGPU

### ISSUE THREAD

**Issue by nesper8** [PCSX2/pcsx2#7094]
### Describe the Bug

My system has an Intel HD 520 and AMD R5 M330 on Hybrid mode 
The Graphics is glitched when I select the dedicated AMD GPU

For Example
![image](https://user-images.githubusercontent.com/57890520/192696253-168f91ce-a51a-41c6-aa01-b9ac8372c3e0.png)

While it works as intended on my iGPU
![image](https://user-images.githubusercontent.com/57890520/192696455-c64c9a9e-4138-4bff-a945-8c6eba99f196.png)

This issue is present on both OpenGL and Vulkan

### Reproduction Steps

1. Set Adapter to AMD Radeon R5 M330 (RADV HAINAN)
2. Launch any game or BIOS 

### PCSX2 Revision

v1.7.3341

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Nobara 36; 5.19.11-201.fsync.fc36.x86_64

**Comment by stenzek** [comment]
Going to say this is probably a driver issue, not on our side, and thus invalid.

**Comment by nesper8** [comment]
I dont have this issue when i run any other apps on my dpgu
tried rpcs3, retroarch, even some games (both native and through wine) too

**Comment by stenzek** [comment]
I don't know what you expect us to do, really, when none of us have a setup like this where we can reproduce the issue.

It's a bit questionable to be honest, especially since GL has no concept of adapter selection.

**Comment by nesper8** [comment]
Launched with the prefix DRI_PRIME=1 for launching OpenGL apps with dGPU

**Comment by nesper8** [comment]
Looking more into it this does feel more like a driver issue
I dont have any problem with using my iGPU so imma gonna close it
