### ISSUE TITLE
[BUG]: flatpak version does not launch

### ISSUE THREAD

**Issue by Sonic1paRadise** [PCSX2/pcsx2#7098]
### Describe the Bug

the command `flatpak run --branch=stable --arch=x86_64 --command=pcsx2-qt net.pcsx2.PCSX2`
gives out 
```
Unhandled page fault @ 0x00000017/run/build/pcsx2-qt/common/Linux/LnxHostSys.cpp:73: assertion failed in function void SysPageFaultSignalFilter(int, siginfo_t*, void*): Unhandled page fault
```
for some reason

### Reproduction Steps

idk???????

### Expected Behavior

pcsx2 must launch

### PCSX2 Revision

v1.7.3333

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 22.04

**Comment by refractionpcsx2** [comment]
We do not control/run the flatpak. Can you try the appimage please, if that works then you need to speak to the packager.

**Comment by Sonic1paRadise** [comment]
i cannot link net adapter without sound loss on appimage

чт, 29 вер. 2022 р. о 11:26 refractionpcsx2 ***@***.***> пише:

**Comment by stenzek** [comment]
We have nothing to do with the flatpak, and even if we knew what the issue here was (we didn't, since you didn't provide a backtrace), we couldn't fix it.

And I'm definitely not messing around installing a flatpak runtime to debug it for them.
