### ISSUE TITLE
[Feature Request]: Parameter "-Resume"

### ISSUE THREAD

**Issue by CristobalManga** [PCSX2/pcsx2#7105]
### Description

Good afternoon friends.
I am using PCSX2 GUI with a PC connected to a TV.
So I control the emulator from a remote from the couch.
      I wanted to know if it is possible to put the parameter -resume, automatically when opening the game. Without the need for notification.

Since I have the option "save state on shutdown" enabled

### Reason

I think it makes it much easier for people who don't want to control the PC with a keyboard and mouse.
They want to use the sofa remote

### Examples

Have the game grab the save state by the "save state on shutdown" option and resume it automatically without any prompts.

**Comment by RedDevilus** [comment]
Instead of having this:
![image](https://user-images.githubusercontent.com/24227051/193280075-1ccd5032-1024-490a-ad38-57d85ed75be5.png)

It might be possible to have a forced option to have `Resume last resume state without prompting` for a Couch set-up with only controllers would be a good addition

**Comment by stenzek** [comment]
If you want to resume, which game would you resume?

If you know which game you want to resume, you can probably just use `pcsx2 -state -1 -- /path/to/game`.

**Comment by CristobalManga** [comment]
> If you want to resume, which game would you resume?
> 
> If you know which game you want to resume, you can probably just use `pcsx2 -state -1 -- /path/to/game`.

Thank you very much, this worked perfectly.
