### ISSUE TITLE
[Feature Request]: Qt - ability to manually rename games in the GUI instead of using GameDB name

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#7119]
### Description

The ability to manually set what display name is used for each ISO/CHD would eliminate so many annoyances and design flaws in the GUI, mainly differentiating between different releases with the same name, games with no GameDB entries, or for modding/preservation communities which run slightly different builds of the same game.

### Reason

When using Qt builds, the names of the games are displayed using their GameDB entries.  This is usually fine, however in some cases it can be completely wrong.  Take the Sly Cooper games, where there's not only different releases (USA, PAL, Korean, Japanese) but also prototypes with unfitting internal names, a Sly 2 prototype that reports as Sly 1, for example.

Lots of GameDB entries also have grammatical errors too, like multiple Sly 1 entries being called "Sly Racoon" instead of "Sly Raccoon".  On top of all that, it can be incredibly hard to find which release you want to play when you have 5 of every Sly Cooper game and you haven't assigned covers for them, or aren't using the display mode that uses covers.  Screenshot:

![just why](https://user-images.githubusercontent.com/58268914/193437090-ce352a16-36a7-4acd-8402-87960e63606e.PNG)

This also means that unless you do some jank ISO/CHD file renaming, updating the cover for one of these updates it to be the same for all of them, further increasing the confusion.  Additionally, ELF based games obviously don't have GameDB entries so you're just stuck with the filename of the ELF as the display name.

This is more important now than ever since Discord Presence has been implemented and the display name is fed into that system.  I'd hate to be playing a game and other users on Discord wondering why it's displaying the wrong name.

The "Summary" menu already has a text box for the game's name, just make this editable and saveable.  Make a new section in PCSX2.ini called "GameTitle" which stores the CRC and the manually assigned name, like:

77ECAAA0 = "Freekstyle"
07652DD9 = "Sly 2 custom name 1"
FDA1CBF6 = "Sly 2 custom name 2"
130421A6 = "EyeToy - Antigrav"
518DD841 = "Sly 2 custom name 3"

### Examples

An example showing a hypthetical rename of two wildly different Sly 3 image files to what they actually are, rather than their GameDB name.

![Untitled](https://user-images.githubusercontent.com/58268914/193437324-a6559b1c-f4f7-4822-b660-96aa8f665960.png)

**Comment by stenzek** [comment]
We don't support prototypes, and personally I am very against clogging up the ini with "custom names" that a trivial fraction of the userbase will use. If anything, it would have to be a separate file.

If you want a different name in the game list, right click in the columns and select file title instead, which won't use the game db.

If anyone else wants to work on this, feel free to reopen, or submit a pull request, but it's not something I am interested in.

**Comment by refractionpcsx2** [comment]
You could also make custom concerts for each version and label the cover the iso name.

**Comment by stenzek** [comment]
Probably should also mention that if there's errors in the game db titles, then those can easily be fixed too.

**Comment by SlyCooperReloadCoded** [comment]
Covers idea won't work if it's not in covers view.  Plus whether you support prototypes or not, there's no way to tell the region of the game without right-clicking on each one and heading to its summary page.  Perhaps taking a page from Dolphin's book and displaying the flag of the region next to the name?

**Comment by stenzek** [comment]
It's not a problem if you do what refraction suggested and create a cover for the file name, that will take precedence over the gamedb name.

There's columns to toggle for the captions and adding even more menu options/user confusion for such a niche use case is not worthwhile.

**Comment by SlyCooperReloadCoded** [comment]
Question.

"I am very against clogging up the ini with "custom names" that a trivial fraction of the userbase will use"

GameIndex.yaml is exactly this, every CRC, name, region, serial, and game-specific fix in one config file.  Why not create a local copy of GameIndex.yaml that's structured the same way but only with names and serials, and acts as an override for those things?  You're right, no need to clog up the ini.

**Comment by Mrlinkwii** [comment]
The gameindex dosent have every CRC

**Comment by SlyCooperReloadCoded** [comment]
So gameindex and gamedb aren't the same, I see.  Why are games with no automatic gamefixes even in there then?

**Comment by stenzek** [comment]
Because it's not needed? Gamedb is a resource, and we're still contemplating embedding it in the executable itself for easier bisecting.

You can override anything set in the gamedb with per-game settings.

**Comment by SlyCooperReloadCoded** [comment]
Speaking of which, how do you report games with missing automatic hardware fixes?  All regions of Sly 2 and Sly 3 are in gameindex.yaml but only NTSC-U releases have the required Half-Pixel Offset setting listed.  I'm not all too familiar with that kind of a GitHub operation.

**Comment by stenzek** [comment]
Edit the file and open a pull request. Anyone can do it.

**Comment by SlyCooperReloadCoded** [comment]
I've never done that before on GitHub, I hope I don't mess something up.
