### ISSUE TITLE
[BUG]: ELF-based games have "Properties" grayed out despite supporting custom configs

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#7120]
### Describe the Bug

If there's an ELF-based game in your library, right-clicking on it reveals that "Properties" is grayed out.  Despite this, if you manually create a custom config ini, change its filename to the CRC displayed the System Log when you boot the game, and place it in the gamesettings folder, it's loaded and used just fine as if it was created using the properties menu.

Screenshot of Properties being unselectable:

![Capture](https://user-images.githubusercontent.com/58268914/193441693-2573118a-63a5-48e9-bc6b-b55375ea0ccf.PNG)

Screenshot of the System Console displaying its CRC and loading its custom config:

![Capture2](https://user-images.githubusercontent.com/58268914/193441725-278f1f5b-370e-456e-a8c7-23eec0aa6f8e.PNG)

Screenshot of its custom config sitting in the gamesettings folder:

![Capture3](https://user-images.githubusercontent.com/58268914/193441734-efff8399-9a3e-436b-a3a9-93ab44c86d5e.PNG)

ELF-based games are supported as they have their own category and icon when you click on "All Types", and custom configs do work for them, so this seems like a bug or something similar.  I couldn't find any open or closed reports describing this nor any PRs regarding it so maybe this is just a bug on my end?

### Reproduction Steps

- Add any ELF-based game into your library.
- Right-click on it.

### Expected Behavior

The Properties option should be selectable, opening up the same menu as for image-based games.

### PCSX2 Revision

v1.7.3358

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by SlyCooperReloadCoded** [comment]
I completely forgot about this, holy crap yes it's fixed, I only now checked.  This is huge, thank you to whoever fixed it.
