### ISSUE TITLE
[Feature Request]: specific extension for only ps2

### ISSUE THREAD

**Issue by geno1000** [PCSX2/pcsx2#7145]
### Description

playstation rom file dont have specific rom extension.
( CSO is not dividied name by machine )

machine based rom file extension is to make user can be easy to identify rom machine.

i hope pcsx2 make new extension for playstation2
( this is not make new rom partition. i am telling you fake extension )

important thing : if user rename rom file ( xxx.iso > xxx.prs ), emulator can load that like ISO file

and i asked this to PPSPP also
- https://github.com/hrydgard/ppsspp/issues/16171

### Reason

almost game rom support specific rom file extension.
user can use that rom file by 'only' renaming file name 

this is to make easy to find rom by person when he have many different machine rom file.

N-VB        : xxx.vb ( = xxx.bin )
N-GB        : xxx.gb ( = xxx.bin )
N-GBC     : xxx.gbc ( = xxx.bin )
N-GBA     : xxx.gba ( = xxx.bin )
SG-1000  : xxx.sg ( = xxx.bin )
SC-3000  : xxx.sc ( = xxx.bin )
GameCube : xxx.gcm ( = xxx.iso )

### Examples

[ for example ]
playstation1 : xxx.prf ( = xxx.iso )
playstation2 : xxx.prs ( = xxx.iso ) < this
playstation3 : xxx.prt ( = xxx.iso )
psp : xxx.prp ( = xxx.iso )

**Comment by kenshen112** [comment]
W... Why? There's no benifit to that. PS2 games are literally just standard dvd's you can rip in imburn. If you're having trouble with organizing it you could always compress it to CSO or a similar format? Otherwise there's literally no point. Thos other "file types" are designed around the types of games and console they're representing. Think INes format for NES and other similar standards.

Bin just means that, you're working with a CD based format with differing track types and ISO a file DVD-based one there's no need for a special standard for a ps2 game when it's just a DVD... With files

**Comment by geno1000** [comment]
i know [this is just standard ISO by DVD]
what i am telling you is [fake extension] like xxx.gcm of GameCube

**Comment by kenshen112** [comment]
N... No. Dog, format's like that are designed for the console's they're representing. gcm is an iso type format that's designed for whatever oddities the GameCube games have which admitdally isn't much and its mostly for compression to my understanding but it's designed for GameCube games.

The point is, you're asking for a useless feature given ps2's with no variance whatsoever are just standard DVD format that you want a cute label. You can already do that by compressing it to CSO, CHD or whatever other supported formats you want

**Comment by geno1000** [comment]
ok~

**Comment by RedDevilus** [comment]
Why do you want to rename .iso format to just do the same?

Like I will call CHD non-standard and CSO what Sony uses as their official alternative that is compressed.
But atleast those are nice extras like reduced storage used.

This isn't niche, it's just dumb and even if that was allowed it is going to cause many problems for users. The game list is going to have any extension, so it's going to be endless and overflow and not going to work.

I have had my fair share of feature requests and seen others, but this takes the cake as the worst in my opinion. Besides, if you can't filter fine on ISOs, then make a folder made for their respective use cases.

Emulators
----- PCSX2
----- PPSSPP
----- Dolphin
----- ....


Like Feature Requests should cross certain checkboxes:

- Improve user experience (GUI design)
- Automation (Patches/ Automatic game settings)
- Expand functionality either new or existing ones (Improving the emulation itself)
- Preference thing (Shaders, dithering)
- Performance (Smart code design to have more FPS or less drops)
- ....


If you really want it, make a fork and implement it there and change the filter (probably crashes if only done that). Or convince me or the PCSX2 team that it actually makes sense for other people. Perhaps I'm just too dumb to get the benefits.

People can do thumbs up or thumbs down if agree or disagree as well.

**Comment by stenzek** [comment]
... no, and the reasons this is silly have already been stated above.

PCSX2's game list scanner is already intelligent enough to recognise which iso files are PS2 and games and which aren't. If yours isn't, that's not our problem.
