### ISSUE TITLE
How about a built-in time tracker stat for each game

### ISSUE THREAD

**Issue by Triramama** [PCSX2/pcsx2#7164]
### Description

Every modern emulator has it, time count column you know

### Reason

very convenient in fact

### Examples

Rpcs3, cemu, ryujinx

**Comment by lightningterror** [comment]
Trivial, if someone wishes they can implement it.

**Comment by Jakey757** [comment]
Session time and total time played is shown in real-time in the pause menu now .
![image](https://user-images.githubusercontent.com/49990481/199505137-a5e65505-c942-49b4-8347-08779a6dae8e.png)
It's saved to a playtime.dat file in the ini directory.
