### ISSUE TITLE
Is it true that this is what Greek pedophiles are interested in?

### ISSUE THREAD

**Issue by GreekPedophileBosit** [PCSX2/pcsx2#717]
https://i.imgur.com/xh4kmGU.jpg

Just fresh and how those sickos like it!

I bet Ryudo would want to have a threesome just to bang that Greek pussy (not referring to the girl)!

If Aeris dies, we all know it's because a Greek man killed her. Greek men are all pedophiles. Simple?

Also, "Ressan" or whatever his name is ... I can assure you that he's been raped by a Greek man.

**Comment by bositman** [comment]
Didn't get your meds today? :(
