### ISSUE TITLE
[BUG]: SLES 54230 (Brian Lara 2007) glitchy text

### ISSUE THREAD

**Issue by CelestialRyuneko** [PCSX2/pcsx2#7174]
### Describe the Bug

in all hardware modes, text becomes extremly blocky and glitched, no matter if upscaled or not. works fine in software. usually happens if there's a lot on screen.

solution is to enable frame buffer conversion, it fixes it all. I suggest a GameDB entry for now, I'd do it myself if I had time.

### Reproduction Steps

go in game and text will glitch on occasion, especially in pause menu.

### Expected Behavior

readable text

### PCSX2 Revision

v1.7.3405

### Operating System

Windows 10 (64bit)

### CPU

i5-4460

### GPU

GTX 1050

### GS Settings

![image](https://user-images.githubusercontent.com/99709368/195080238-d09060af-3997-449a-9435-5f991f673968.png)
![image](https://user-images.githubusercontent.com/99709368/195080951-e81ad76a-d158-4418-a117-d31be9b07176.png)
for the actual game, only manual hardware fixes and force frame buffer conversion is active

### Emulation Settings

![image](https://user-images.githubusercontent.com/99709368/195080343-068dfaa8-a7d8-4bc8-a906-eaa06b54e644.png)
MTVU is not the issue

### GS Window Screenshots

**Before**
![image](https://user-images.githubusercontent.com/99709368/195081063-6ba120f4-eaf1-4bd5-abe0-a9ac7f467b71.png)

**After**
![image](https://user-images.githubusercontent.com/99709368/195081288-440a1360-c803-47f0-a804-afee9dd1d549.png)

### Logs & Dumps
[Brian Lara International Cricket 2007_SLES-54230_20221011214419.zip](https://github.com/PCSX2/pcsx2/files/9754762/Brian.Lara.International.Cricket.2007_SLES-54230_20221011214419.zip)

_No response_

**Comment by refractionpcsx2** [comment]
Your images didn't work (of the game)

also instead of framebuffer conversion, could you try the CPU Sprite Render option? if it's gonna work it'll usually be between 1-4 BW

**Comment by KitsuDrake** [comment]
> Your images didn't work (of the game), I guess you didn't wait for them to upload :)
> 
> also instead of framebuffer conversion, could you try the CPU Sprite Render option? if it's gonna work it'll usually be between 1-4 BW

fixed by reuploading (forgot to submit edits).

it works with a minimum of 2 on CPU Sprite Render

**Comment by KitsuDrake** [comment]
> You uploaded the same picture for before and after :P
> 
> Anyway the sprite render thing is preferred as Frame Buffer Conversion tends to be slow, maybe @Mrlinkwii could do a GameDB PR for this :)

aw man that figures.
![pcsx2-qtx64-avx2_sBejnEo6Q7](https://user-images.githubusercontent.com/99709368/195088955-5eb8f841-170d-4597-b34d-099eadbf64bb.png)
here we go

**Comment by refractionpcsx2** [comment]
There we go! :D yes that certainly looks busted.

**Comment by KitsuDrake** [comment]
> There we go! :D yes that certainly looks busted.

![image](https://user-images.githubusercontent.com/99709368/195098702-5ce93895-2f1e-45c6-86e4-f07f36ed4130.png)
menus are worse unless I set the max width to 4... 😒

**Comment by refractionpcsx2** [comment]
ooof, how well did Frame Buffer Conversion work again? lol

**Comment by KitsuDrake** [comment]
It was slow haha.

**Comment by refractionpcsx2** [comment]
damn, that's annoying! I guess check the rest of the game, make sure it's okay with BW 4 on the CPU Sprite Render, we will have to use that I guess!
