### ISSUE TITLE
[BUG]: Primal PS2 Black Screen In-game

### ISSUE THREAD

**Issue by Kneesnap** [PCSX2/pcsx2#7175]
### Describe the Bug

I'm looking to release a new prototype of Primal PS2 on Hidden Palace.
However, this prototype renders a black screen ingame in PCSX2 Nightly v1.7.2994, unless Software Rendering is chosen, which is too slow.

Related Issues: https://github.com/pcsx2/pcsx2/issues/909
Why I created a new issue instead of bumping the old one: Because this is a prototype build which may require a separate fix. I tried applying a patch I found, and the code in this prototype seems to vary significantly from the final version.

There are massive amounts of debug symbols in this prototype, so it should be easy to debug.

### Reproduction Steps

Not sure if I can post a prototype iso here. If you need this one, contact me. Otherwise, other versions of the game seem to have this issue too, see the issue I linked above.
Open the prototype.
Enter in-game into the first level in the level select.

### Expected Behavior

The game should render correctly.

### PCSX2 Revision

Nightly v1.7.2994

### Operating System

Windows 10 (64bit)

### CPU

AMD FX 8350

### GPU

GTX 1060

### GS Settings

Using default settings

**Comment by MrCK1** [comment]
We do not provide support for prototype builds for any reason due to legal restrictions.

**Comment by Kneesnap** [comment]
> Unless you can prove that you own a physical copy of this game, we do not provide support for prototype builds due to legal restrictions.

Are you asking for a photo of the prototype disc, or of the retail copy? Or is this stating that no matter what, PCSX2 will not work on the prototype, but if I provide a photo of the retail disc you can work on the retail version? I'm confused what photo to give.

**Comment by Kneesnap** [comment]
Do we have any examples of what this is? I can take a photo with my username written on a piece of paper with the disc later if that works?

**Comment by MrCK1** [comment]
> I can take a photo with my username written on a piece of paper with the disc later if that works?

Yes, please.

**Comment by stenzek** [comment]
I'm not a lawyer, but if it was a disc which was not officially released, then it may fall under NDA, and we should steer as far away from it as possible. Even if it was a demo for e.g. the press, it may still have had restrictions.
