### ISSUE TITLE
[BUG]: Integer upscaling disables bilinear filtering, but bilinear filtering can still be used.

### ISSUE THREAD

**Issue by GitHubUser6721** [PCSX2/pcsx2#7180]
### Describe the Bug

Whenever you enable "Integer Upscaling" in the "Graphics" options it will grey out the "Bilinear Filtering" option, however it doesn't turn off BF itself it just greys it out.

Also I would just recommend not greying it out in general because I actually like using IU + BF and I've had no issues with it, I know DuckStation does it for whatever reason as well but I just don't see a point in it.

### Reproduction Steps

- Disable IU (If enabled)
- Toggle BF
- Enable IU

### Expected Behavior

Since DuckStation does the same I assume that it would be trying to disable the option but I would personally just recommend making it so it doesn't grey out the option because like I said above it doesn't cause issues and allows for more accuracy for those who prefer that.

### PCSX2 Revision

v1.7.3411

### Operating System

Windows 10 (64bit)

**Comment by Jakey757** [comment]
If you're using display filtering you are kinda defeating the point of integer scaling which is to keep pixels their original sizes and positions, the image doesn't get less blurry after it is already interpolated, those details are gone. it should actually behave like Duckstation and disable integer scaling if filtering is turned on. The lack of a 1:1 mode in PCSX2 works against IS as whatever is output never has square pixels anyway.

**Comment by GitHubUser6721** [comment]
So what ur saying is PCSX2 is more accurate when IU is disabled and BF is enabled?

**Comment by Jakey757** [comment]
No that is entirely preference. I'm saying that integer scaling loses its value if bilinear filtering is enabled, you could just use the zoom feature <100% scaling if all you wanted was tighter pixel density. These features don't really have anything to do with accuracy or emulation just user experience. But i do agree its weird to disable changing filtering when you can just bypass it anyway.

**Comment by GitHubUser6721** [comment]
Accuracy isn't a preference tf u on about?

**Comment by Jakey757** [comment]
You arent really reading anything im typing so im just gunna avoid uncessary conflict.

**Comment by GitHubUser6721** [comment]
Not my fault you have shit English

**Comment by refractionpcsx2** [comment]
Behave yourself otherwise you won't be welcome here any longer @GitHubUser6721

**Comment by GitHubUser6721** [comment]
Lol dude has the memory of a gold fish, let me guess ur gonna close this issue now right? Yeah because that will really show me "I know ur trying to help us but I'm going to close ur issue so that we can't fix the bug!"

**Comment by F0bes** [comment]
Issues can be fixed with or without your poor attitude.
