### ISSUE TITLE
[BUG]: Klonoa 2 crashes PCSX2 upon loading

### ISSUE THREAD

**Issue by AkiraTak97** [PCSX2/pcsx2#7182]
### Describe the Bug

When opening up "Klonoa 2: Lunatea's Veil" on PCSX2 1.7.3411, the application crashes.
I have tried everything, such as changing the renderer.
Please consider getting to the bottom of this.

My settings are default.

My build is
Windows 10
Intel Core i5 7300HQ
Nvidia GTX 1050
16 GB RAM

### Reproduction Steps

Open PCSX2, open ROM file for Klonoa 2, wait for the game to load, program crashes.

### Expected Behavior

The game should load fully.

### PCSX2 Revision

v.1.7.3411

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i7 7300HQ

### GPU

Nvidia GTX 1050

### Logs & Dumps

[Klonoa 2 emuLog Oct 12 2022.txt](https://github.com/PCSX2/pcsx2/files/9769511/Klonoa.2.emuLog.Oct.12.2022.txt)

**Comment by refractionpcsx2** [comment]
Sounds like you enabled the fast cdvd speed hack, which doesn't work with this game. Please make sure it is off

**Comment by stenzek** [comment]
Probably still shouldn't crash pcsx2 though - would need the crash dump.
