### ISSUE TITLE
[Feature Request]: (Qt) Native DualShock 3 support in Windows using the official Sony Sixaxis driver

### ISSUE THREAD

**Issue by ricky65** [PCSX2/pcsx2#7189]
### Description

Thanks to #7099 we now have native DualShock 3 support in Windows using the official Sony Sixaxis driver. Currently this is only available for the old wx interface and missing in the Qt interface. It would be very useful if this were available in the Qt version.

### Reason

When using a DualShock 3 controller and the official Sony Sixaxis driver, rumble support is unavailable when using Qt SDL input but works with wx DualShock 3 Native mode added in #7099.

### Examples

![pcsx2 qt](https://user-images.githubusercontent.com/1148919/195929657-22d69ae8-5bbf-4d1d-b19b-532fe7b85d1e.png)
![pcsx2 wx](https://user-images.githubusercontent.com/1148919/195929660-59d1bcac-4222-46b0-b280-a6ad6b7b63b8.png)

**Comment by stenzek** [comment]
No plans to add this to Qt, especially since SDL provides some degree of DS3 support.

PRs welcome, of course. As I said in the other PR thread, you'd want to create a new `InputSource` and implement it there.
