### ISSUE TITLE
[BUG]: Crimson Tears SLES-52534 - Ghost characters when increasing the internal resolution

### ISSUE THREAD

**Issue by PauloMaximus** [PCSX2/pcsx2#7190]
### Describe the Bug

When increasing the internal resolution, the ghost of the characters appears. Tested with DX11 OpenGL and Vulkan.

### Reproduction Steps

Just increase the internal resolution.

### Expected Behavior

The ghost does not appear.

### PCSX2 Revision

Nightly 1.7.3419

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5 7500K @ 3.4Ghz 

### GPU

NVIDIA Geforce GTX 960 4GB 

### GS Settings

Default.

### Emulation Settings

Default, I just increased the internal resolution.

### GS Window Screenshots

![Crimson Tears_SLES-52534_20221014185457](https://user-images.githubusercontent.com/113481760/195953118-1594d272-164b-491f-8874-311548735487.png)

**Comment by Mrlinkwii** [comment]
Can you post a gs dump?

**Comment by stenzek** [comment]
See this note which is displayed when creating an issue.
> We do not accept issues relating to upscaling at this time
> We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling
> Please try your game at native resolution before creating an issue
> If your bug is the result of upscaling please use the forums or discord for assistance with various upscaling workarounds.
> Additionally, the unofficial PCSX2 [Wiki](https://wiki.pcsx2.net/Main_Page) often lists various fixes for upscaling issues
