### ISSUE TITLE
[Feature Request]: Implement screensaver inhibit for Wayland

### ISSUE THREAD

**Issue by GreyXor** [PCSX2/pcsx2#7199]
### Description

This prevents screensaver/standbye when PCSX2 is running under Wayland.
https://wayland.app/protocols/idle-inhibit-unstable-v1

### Reason

That's already exist for X11, we definitely want the same for Wayland (Thanks @stenzek)
https://github.com/PCSX2/pcsx2/commit/c379c833e4ce9876a7d9fb1e8e6ded8475a23b0e

### Examples

https://github.com/mpv-player/mpv/commit/68f9ee7e0b3fdddfa42fa11a15d9ae84460d5e19

**Comment by stenzek** [comment]
PRs welcome, but I'm not doing this, wayland has already driven me nuts enough.

And since there's no actual Linux maintainer, nobody on the team will either, so closing.
