### ISSUE TITLE
[BUG]: Crash in Gran Turismo 4 - Prologue

### ISSUE THREAD

**Issue by Jonas1999** [PCSX2/pcsx2#7200]
### Describe the Bug

It happens somewhat randomly when starting a new race, either when loading the race or right before starting it.
It happens with the vulkan api but others might also be affected.

### Reproduction Steps

Start a race in Fuji Speedway (might also work on other tracks) and the game will crash about 50% of the time.

### Expected Behavior

Game not crashing

### PCSX2 Revision

v1.7.3419

### Operating System

Windows 10 (64bit)

### CPU

i7-4770k

### GPU

3070 Ti

### GS Settings

![bild](https://user-images.githubusercontent.com/15720835/195983246-cdbecb8d-5003-4c57-880e-2d29aed6f8e7.png)
![bild](https://user-images.githubusercontent.com/15720835/195983258-230ffc9d-1ff1-4d8f-9f85-b8699f59d5f7.png)
![bild](https://user-images.githubusercontent.com/15720835/195983324-2afff03c-4ba8-4aae-b20c-c95334a51735.png)

### GS Window Screenshots

![bild](https://user-images.githubusercontent.com/15720835/195983119-fa6b6c30-ecdb-4948-be45-2ca26f74f380.png)

### Logs & Dumps

[crash-2022-10-15-12-14-03-335.zip](https://github.com/PCSX2/pcsx2/files/9791873/crash-2022-10-15-12-14-03-335.zip)

**Comment by Mrlinkwii** [comment]
can you lower the upscale :) , i think it a combination of high upscaling and texture replacements , also this seems more of a support issue

**Comment by stenzek** [comment]
If it happens at default settings I'll look into it. But not with those.

**Comment by SySy233** [comment]
No crashes whatsoever on default settings.

**Comment by stenzek** [comment]
Maybe you're running out of vram. Granted, we probably should handle it better, but that requires a larger refactor.

Regardless, we don't accept upscaling reports as separate issues here, as it states when you open an issue.

**Comment by stenzek** [comment]
https://github.com/PCSX2/pcsx2/pull/7203 might be related, as I did get this validation error when starting a race, but it didn't crash my GPU at all. Could just be a coincidence though, especially if it's fine at 1x.
