### ISSUE TITLE
[Feature Request]: Mac Launchpad Game Category

### ISSUE THREAD

**Issue by darkuser89** [PCSX2/pcsx2#7204]
### Description

can you add this to the info.plist so that pcsx2 is recognized as a game in the launchpad? `<key>LSApplicationCategoryType</key> <string>public.app-category.games</string>`

### Reason

Games with this apps are marked as automatically in the category

### Examples

<img width="431" alt="Bildschirmfoto 2022-10-15 um 19 15 06" src="https://user-images.githubusercontent.com/29849893/195999942-71971c38-4a8d-49e0-94c7-d57395de6c8d.png">

**Comment by Mrlinkwii** [comment]
>can you add this to the info.plist so that mgba is recognized as a game in the launchpad
i assume you mean pcsx2 not mgba ?
