### ISSUE TITLE
[BUG]: Silent Hill - Origins - Freeze at load screen

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#7207]
### Describe the Bug

This game freezes at loading screen.

Note that this is a recent regression - freezing occurs with build f836fe2056a6189728b25c6a90c0273d6b93c3e4 but did not occur with build 7433cec2c426bf7e3f07c5e0803e99c535d83d9a.  Can bisect if it isn't obvious which commit is the root cause.

### Reproduction Steps

Start game, wait for game to reach "loading" screen, observe game freezing 

### Expected Behavior

Game does not freeze at loading screen.

### PCSX2 Revision

f836fe2056a6189728b25c6a90c0273d6b93c3e4

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 21 / kernel 5.15

### CPU

Intel i7-10870H

### GPU

Nvidia 3070

### GS Settings

N/A

### Emulation Settings

N/A

### GS Window Screenshots

N/A

### Logs & Dumps

Can provide as needed.

**Comment by refractionpcsx2** [comment]
Can you provide the memcard please? Thanks.

**Comment by Shoegzer** [comment]
Sorry I misspoke, the game freezes even without a save.  I just tried with a fresh memcard and it still freezes.

**Comment by refractionpcsx2** [comment]
okay so where does it freeze? just starting a new game?

**Comment by Shoegzer** [comment]
It freezes at the first game screen past the BIOS ("loading" is displayed in the middle of the screen)

**Comment by refractionpcsx2** [comment]
Can't reproduce, full or fast booting works fine and I can get ingame.

Can you post your graphics settings, specifically the "Rendering" tab (maybe both the per game and global ones

**Comment by stenzek** [comment]
Your bisect is way too wide - need to know the exact commit it apparently broke on.

**Comment by Shoegzer** [comment]
Okay, I found time to perform the bisect.  Apparently commit 00bcb4cf020395cebfbe30b854739a093e5090aa is the root cause.

Rendering settings are the same between global and per-game as follows:

![pic](https://user-images.githubusercontent.com/12475371/196019560-1617cb74-7b1d-48b7-bff4-da25ef87e3dc.png)

**Comment by stenzek** [comment]
Okay, reproduced, it's linux-specific. I'll look into it later.

**Comment by Shoegzer** [comment]
Indeed tested and working fine now.  Interesting linux-specific register handling.  Thanks for the fix @stenzek.
