### ISSUE TITLE
[BUG]: SLUS 20015 Eternal Ring texture glitches during play.

### ISSUE THREAD

**Issue by malasdairm** [PCSX2/pcsx2#7208]
### Describe the Bug

Not experienced firsthand but reports from multiple players of Eternal Ring that exiting menus and casting spells can cause all environment textures to glitch out, resulting in visuals such as these:

![ering bug 1](https://user-images.githubusercontent.com/105080856/196014036-307c60fb-cab9-4907-a34b-3c90734c486a.png)
![ering bug 2](https://user-images.githubusercontent.com/105080856/196014037-72869c42-d353-4c15-a8dc-a8ac0f9359c8.png)

You can see on the left side of the first image that it does not appear to affect all textures, possible that object textures are left alone and only environmental textures are affected.

### Reproduction Steps

I have been unable to reproduce this on the D3D 11 renderer under default settings. It seems to activate only sometimes when exiting a menu, especially the save menu, during play, and occasionally when casting a spell.

### PCSX2 Revision

1.7.3428

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-4440

### GPU

Intel HD Graphics 4600

**Comment by refractionpcsx2** [comment]
can you ask somebody who reported it to try enabling "Disable Partial Invalidation" in the hw renderer fixes before it breaks, then see if it breaks coming out of the menu, please?

Thanks :)

**Comment by malasdairm** [comment]
Reporter played through the first chunk of the game and attempted to trigger the bug with that enabled and says that seems to have fixed it!

**Comment by refractionpcsx2** [comment]
Awesome :) we'll get that put in to the gamedb!
