### ISSUE TITLE
[Feature Request]: Adding dead zone sliders for both sticks into the "Gamepad configuration" section

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#7242]
### Description

I suggest this option should be added as a default integral option of any emulator. It seams the Qt-version has it, so how come Linux Wx-version doesn't? (Don't know if Windows version has it).

### Reason

By default, the stick sensitivity is too high and there is no possibility of changing it; it is really irritating when stick responds even the smallest tilt (not to mention the old gamepads with cranky sticks - in this case, they seem to be living on their own, providing sudden and unnecessary tilting at the most inopportune moment).

### Examples

The same feature in Dolphin emulator.

![Screenshot from 2022-10-19 20-37-27](https://user-images.githubusercontent.com/96921167/196765424-09b58eeb-2ef7-4b66-a8a7-5cfb1043c4ff.png)

**Comment by Mrlinkwii** [comment]
WX  is on life support is why is not added to WX  , probably never will be

**Comment by VladimirVSC** [comment]
> 



> WX is on life support is why its not added to WX , probably never will be

It's a shame, that a handy and pretty Wx must be force out with bulky and rather ugly Qt.

**Comment by refractionpcsx2** [comment]
Thanks for your opinion :)
