### ISSUE TITLE
Blood Omen 2 mist ability hardware bug

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#7245]
### Describe the Bug

When using the mist ability in hardware mode facing Kain in certain directions corrupts the mist effect on his body resulting in the rainbow colorful bug. I have provide a gs dump and a screenshot down below.

### Reproduction Steps

Use the mist ability in hardware mode and turn Kain until the bug is visible.

### Expected Behavior

Should look like software mode at all angles. 

### PCSX2 Revision

Nightly v1.7.3461

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Any in hardware mode. No hacks seem to fix it that I'm aware of. 

### Emulation Settings

default

### GS Window Screenshots

![Screenshot (6)](https://user-images.githubusercontent.com/12180630/196783724-7fa475c2-6f19-4912-a1c4-e57b4d8975ee.png)
[Mist Bug.zip](https://github.com/PCSX2/pcsx2/files/9823564/Mist.Bug.zip)

**Comment by refractionpcsx2** [comment]
The mist seems to be fixed in recent builds (at least with the GS dump), can you confirm this is fixed for you?

![image](https://user-images.githubusercontent.com/6278726/221433634-be3a6454-87f1-4dcd-94b3-1e996ac68cc5.png)

**Comment by BParks21** [comment]
Yeah it does seem to be fixed.

**Comment by refractionpcsx2** [comment]
awesome :) I'll close this then, thanks!
