### ISSUE TITLE
[Feature Request]: Textures offset X and Y for pcsx2 Qt

### ISSUE THREAD

**Issue by elessar38** [PCSX2/pcsx2#7246]
### Description

If possible, please add options for pcsx2 Qt
Textures offset X and Y

### Reason

required for proper emulation of God of War 2.
https://wiki.pcsx2.net/God_of_War_II
issue: "Shifted, ghost-like image"
Game need textures offset X20, Y20

### Examples

available in pcsx2 wx, but not in Qt

**Comment by Mrlinkwii** [comment]
their already in QT , use a per game setting

**Comment by RedDevilus** [comment]
2 methods to access them
```
View > Game Properties
Right clicking a game in the list > Properties
```
Then doing the check for manual gamefixes and going to upscaling fixes and you will see it there.

**Comment by elessar38** [comment]
I was looking for this option for a long time and I forgot about game properties.
My mistake. Thank you for your help.
