### ISSUE TITLE
[BUG]: UX issue cover downloader () vs {}

### ISSUE THREAD

**Issue by Getn67** [PCSX2/pcsx2#7248]
### Describe the Bug

Parenthesis after a $ are accepted as valid inputs but do not return results. E.G. https://psxdatacenter.com/psx2/images2/covers/$(serial).jpg vs https://psxdatacenter.com/psx2/images2/covers/${serial}.jpg

### Reproduction Steps

In the URL section of the cover downloader, use parenthesis instead of curly brackets to reproduce the (lack of an) error.

### Expected Behavior

An error should be thrown when () is used, or a better way of highlighting the curly brackets.

### PCSX2 Revision

v1.7.3462

### Operating System

Windows 11

**Comment by stenzek** [comment]
Not sure why this is a bug. It's not an expression which is evaluated, just a simple template string with search&replace.

Also removed the links from the OP, covers are artwork and thus likely protected by copyright.

**Comment by Getn67** [comment]
Thank you for redacting the websites. Bug might be a bit strong of a word, but an adjustment might keep others from making the same mistake that I did.
