### ISSUE TITLE
[BUG]: Max Payne Flickering, No sound weapon

### ISSUE THREAD

**Issue by tunsay** [PCSX2/pcsx2#7260]
### Describe the Bug

When I start walking, the screen starts flickering for some unknown reason, no settings seem to interfere with the problem, plus it's a problem that wasn't there before. Then, the sound of the weapons does not trigger, and the enemies seem to have a hazardous hitbox.

### Reproduction Steps

Run or walk. Shoot with a gun. (Test in the tutorial)

### Expected Behavior

No flickering, have sound weapons, hitbox enemy not hazardous.

### PCSX2 Revision

v1.7.3473

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800X 8-Core Pro

### GPU

RTX 2070 Super

### GS Settings

![image](https://user-images.githubusercontent.com/40166667/197225053-5364fa24-e0b6-4527-98e8-f1431fff9a24.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/40166667/197225143-a9dc9ade-191e-4bda-8983-88b8014e755e.png)

### GS Window Screenshots

![Max Payne_SLES-50326_20221021164907](https://user-images.githubusercontent.com/40166667/197225346-1d5d3907-f4f0-494d-bd35-12ee39c12fc0.png)
![Max Payne_SLES-50326_20221021164904](https://user-images.githubusercontent.com/40166667/197225359-56a200f1-16b0-4fc2-aef8-f0fa43e25163.png)

**Comment by Mrlinkwii** [comment]
gs dump?

**Comment by F0bes** [comment]
Rename the file extension to .jpg or something github will allow.

**Comment by refractionpcsx2** [comment]
Don't worry, GS Dump is useless here.

I know where it was caused, it was https://github.com/PCSX2/pcsx2/pull/7179

Investigating now..

**Comment by refractionpcsx2** [comment]
#7262 will fix the problem once it merges :)
