### ISSUE TITLE
[BUG]: Persona 3 FES new fps drop on certain enemies

### ISSUE THREAD

**Issue by truehd24** [PCSX2/pcsx2#7261]
### Describe the Bug

All Tartarus fights used to run smooth on my system with the same settings to the point were I play that section with fast forward enabled at 150%. After one of the nightly updates, however, fights with most enemies on the top levels and in Monad dip the fps below what is even normal at 100% speed. I am not sure what changed.

### Reproduction Steps

Fight most shadow enemy types on the top levels of Tartarus or in Monad. Whenever the enemies are being rendered on screen there's a slowdown. If the camera moves off of them or they die then the fps returns to normal.

### Expected Behavior

The fps should be consistently smooth at all times.

### PCSX2 Revision

v1.7.3473

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA RTX 3060

### GS Settings

<img width="1202" alt="Display" src="https://user-images.githubusercontent.com/85703379/197257525-2e047bee-0267-4dd6-b2d1-d21bc44d9ba7.png">
<img width="1202" alt="Rendering" src="https://user-images.githubusercontent.com/85703379/197257529-974fe6d7-4184-4353-9db5-adc4c4b9dc8c.png">
<img width="1201" alt="Textures" src="https://user-images.githubusercontent.com/85703379/197257530-c6e6ecb7-df9b-4293-a903-52b108000b72.png">

### Emulation Settings

<img width="1204" alt="Emulation" src="https://user-images.githubusercontent.com/85703379/197257806-c124268a-be6a-42f4-be95-b843bae5cea6.png">

### Logs & Dumps

[Persona 3 FES fps drop.zip](https://github.com/PCSX2/pcsx2/files/9841328/Persona.3.FES.fps.drop.zip)

**Comment by Mrlinkwii** [comment]
try lowering the upscale :)

**Comment by truehd24** [comment]
It still slows down at native res although it is to a lesser degree. I will concede, but I still think it's an odd anomaly.
