### ISSUE TITLE
[Feature Request]: Allow Achievement Login via Scripting

### ISSUE THREAD

**Issue by WingofaGriffin** [PCSX2/pcsx2#7263]
### Description

For authentication with cheevos/retro achievements, I would like to see it possible to integrate compatibility to automate the process where a user is able to input their credentials in one setup script, and copy them over to all platforms with cheevo support (PCSX2, RetroArch, etc). I do see security concerns with not wanting to store credentials in plain text, though if there is a way in the scripting process to run the authentication, then scrub the password, that may be a possibility

### Reason

This allows multi-emulator setup tools like EmuDeck to use one singular user+password input to apply Cheevo authentication for a user one time, and persist over updates. This makes the achievement integration more accessible and usable by the average user who may not know to even input it in the first place, or become frustrated that their credentials are wiped after re-installations.

While this works as intended in RetroArch cores, for standalone PCSX2-qt there is currently not a way to do this as intended.

### Examples

Retroarch does this in a .cfg file which can be modified easily via scripts. Emudeck uses that feature in its setup via the following script:

https://github.com/dragoonDorise/EmuDeck/blob/155dbfb951b86e4d61b55966ed4a4222ca73a2c3/functions/EmuScripts/emuDeckRetroArch.sh#L1886

**Comment by stenzek** [comment]
I completely fail to see how any of this is our responsibility.

1. We have nothing to do with emudeck.
2. Why would we want to anything to facilitate interoperability with a project (ra) that has threatened and tries to create drama for us?
