### ISSUE TITLE
[Feature Request]: Nightly Flathub Builds

### ISSUE THREAD

**Issue by mak448a** [PCSX2/pcsx2#7271]
### Description

There is already a stable version of PCSX2 on [Flathub](https://flathub.org/apps/details/net.pcsx2.PCSX2), but it would be nice if we could have the nightly version.

### Reason

This feature will make things easier for me and other Linux users, because they can update PCSX2 without having to go to the downloads page every single time.

### Examples

A good example of this feature being implemented by other software is [Google Chrome](https://flathub.org/apps/details/com.google.ChromeDev). They have a dev channel on Flathub.

**Comment by RedDevilus** [comment]
We don't control the Flathub, so we can't influence what happens there as it's not official as far as I know.

**Comment by refractionpcsx2** [comment]
We provide app images, whatever other packagers provide is up to them.

**Comment by refractionpcsx2** [comment]
Also the appimage has an auto updater now.

**Comment by mak448a** [comment]
I did not know that the AppImage had an updater, thanks!
