### ISSUE TITLE
[BUG]: Xenosaga ep 1 increased banding in HW mode

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2#7272]
### Describe the Bug

Banding is amplified using HW renderers compared to software mode.

SW mode
![image](https://user-images.githubusercontent.com/49990481/197427920-c148b8b3-44dc-4957-92fe-2faf9b96e0d4.png)

Vulkan HW at native res and default graphics settings
![image](https://user-images.githubusercontent.com/49990481/197427972-4ca05828-0337-4d2a-ba31-c013393f5f5b.png)

The game doesn't seem to use dithering as none of the options do anything, and none of the blending levels affect it either.

### Reproduction Steps

Load the GS dump and toggle between SW and HW

### PCSX2 Revision

1.7.3474

### Operating System

Windows 10 (64bit)

### CPU

i7 4790

### GPU

AMD RX 570

### Logs & Dumps

https://cdn.discordapp.com/attachments/923492653788692480/1033897944778289213/Xenosaga_-_Episode_I_-_Der_Wille_zur_Macht_SLUS-20469_20221023201905.gs.xz

**Comment by Jakey757** [comment]
Similar case in Sly Cooper and the Thevious Racoonus too, noticable in snow. Settings dont affect it.
SW
![Sly Cooper and the Thievius Raccoonus_SCUS-97198_20230608094546](https://github.com/PCSX2/pcsx2/assets/49990481/a0ebcdbb-24b7-4bab-998c-90296dd9ba98)
HW
![Sly Cooper and the Thievius Raccoonus_SCUS-97198_20230608094413](https://github.com/PCSX2/pcsx2/assets/49990481/7286c519-046a-4bb1-b8b3-42b64077ba5e)

**Comment by Mrlinkwii** [comment]
@Jakey757  do you have  an nvidia  gpu , because i vaguely remember something with nvidia and banding

**Comment by Jakey757** [comment]
AMD as specified in first post RX 570
