### ISSUE TITLE
[BUG]: Bleach Blade Battlers 2nd - Severe fps drops when using Ichigo's mask ability 

### ISSUE THREAD

**Issue by AkiyoSSJ** [PCSX2/pcsx2#7284]
### Describe the Bug

The game gets severe frame drops when using the special ability/Hollow mask of the character Ichigo during his Bankai/awakening. The issue persists in all render modes and even on the software renderer.

### Reproduction Steps

Play as Ichigo then use his Bankai/awakening/transformation after filling the awakening energy and then use his special ability with full ability energy by pressing circle, he will use a Hollow mask that produces a lot of screen effects, significantly affecting the framerate. 

### Expected Behavior

Game working normally with stable framerate.

### PCSX2 Revision

v1.7.3490

### Operating System

Windows 10 (64bit)

### CPU

Xeon E3-1271 v3

### GPU

RX 580

**Comment by stenzek** [comment]
This is a support issue as discussed on discord - lower upscaling, or use a faster cpu for software mode.
