### ISSUE TITLE
[BUG]: Scale to host refresh rate ON and VSYNC ON crashes Dragon Quest 8 on PCSX2 AppImage (Steam Deck)

### ISSUE THREAD

**Issue by DaniRainbow** [PCSX2/pcsx2#7289]
### Describe the Bug

While playing Dragon Quest VIII with Scale To Host Refresh Rate and VSYNC turned on, if the menu was opened for the purpose of using/transferring/discarding an item or using a magic spell, the emulator would crash at the next random battle.  For my full log tracking and documenting the bug, please see this Google Doc https://docs.google.com/document/d/1GbYnN22814qjx52R8sF7V9ZC8PT8-TK8EOYuo22pI1I/edit?usp=sharing

### Reproduction Steps

1) Turn on Scale To Host Refresh Rate and VSYNC then load the game.
2) Go to an area that has monsters.
3) Use an item or spell from any character or bag inventory. 
4) Exit menu.
5) Walk around till the next random battle starts. The game will crash.

### Expected Behavior

After interacting with an item or spell in the menu, enter the next random battle successfully instead of crash.

### PCSX2 Revision

 v1.7.3490

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch / SteamOS 3.3

### CPU

AMD "Aerith"

### GPU

AMD VANGOGH

### GS Settings

Graphics> Renderer> Vulkan
Graphics> Adapter> AMD VANGOGH
Graphics> Display> VSYNC ON
Graphics> Rendering> Internal Resolution> 2x Native
Graphics> Advanced> GS Dump Compression> Uncompressed

### Emulation Settings

Emulation> Scale To Host Refresh Rate ON

### Logs & Dumps

https://docs.google.com/document/d/1GbYnN22814qjx52R8sF7V9ZC8PT8-TK8EOYuo22pI1I/edit?usp=sharing

**Comment by stenzek** [comment]
I'm gonna say this is likely invalid.

Sync to refresh rate works fine on my Ubuntu install. Changing the GS dump compression type won't have any effect on normal VM behaviour unless you're creating GS dumps.

**Comment by DaniRainbow** [comment]
> I'm gonna say this is likely invalid.
> 
> Sync to refresh rate works fine on my Ubuntu install. Changing the GS dump compression type won't have any effect on normal VM behaviour unless you're creating GS dumps.

Well, you'd definitely know better than me. I was just advised by someone in the support channel on discord to post it here. Perhaps it is Steam Deck specific. Thanks for your time.

**Comment by stenzek** [comment]
FWIW, if you can get a backtrace, I can try to guess at what's going on. But without any information, your guess is as good as mine.

**Comment by DaniRainbow** [comment]
> FWIW, if you can get a backtrace, I can try to guess at what's going on. But without any information, your guess is as good as mine.

If you have some advice or a guide towards setting up my system so I can get you a backtrace I would happily do so. I'm a bit of a novice when it comes to all this stuff, sorry.
