### ISSUE TITLE
[BUG]: Signifcant screen tearing when using OGL/Vulkan in full-screen

### ISSUE THREAD

**Issue by romatthe** [PCSX2/pcsx2#7290]
### Describe the Bug

Whenever either the OpenGL or Vulkan renderer are used, games seem to suffer from very serious screen tearing whenever in full-screen mode. This issue does NOT occur when using the DX11/12 or software renderers or while outside of full-screen. Therefore, I suspect it might be related to how borderless full-screen is set up in OpenGL/Vulkan.

I don't have access to my Linux desktop or my Steam Deck at the moment, so I've only been able to test this on Windows. I would include a video to show this but obviously tearing can't be captured.

### Reproduction Steps

Select the Vulkan render, switch to full-screen and play any sufficiently dense scene to see the heavy tearing line scrolling up and down the screen.

I stumbled upon this while playing my first game on the new Qt build: `Okage: Shadow King [SCUS-97129]`.  As soon as the opening dialogue with your mother is finished, you can go to the central hall of your home. Start running in circles in this area to see tons of screen tearing.

### Expected Behavior

No tearing (as with DX11/12).

### PCSX2 Revision

v1.7.3491 (Qt/AVX2)

### Operating System

Windows 10 (64bit)

### CPU

i7-10750H

### GPU

RTX 2060 (Mobile)

### GS Settings

![Vulkan1](https://user-images.githubusercontent.com/8373222/198419533-497c2bbf-935f-43f9-a105-9dd114228b75.JPG)
![Vulkan2](https://user-images.githubusercontent.com/8373222/198419534-63c039ba-bbfe-4200-8473-63ddc7ed5d6c.JPG)

None of these settings are changed when switching from Vulkan to DX12.

### Emulation Settings

No non-default settings, as the game runs perfectly fine otherwise.

### GS Window Screenshots

Cannot be captured.

### Logs & Dumps

Please let me know if I can provide relevant logs. I don't think GSdump is useful here, and if it, I'm not 100% sure how to use it in the new Qt interface.

**Comment by stenzek** [comment]
Need an emulog, it will tell you if vsync is enabled.

Wild guess, you're overriding it in the driver or something.

**Comment by refractionpcsx2** [comment]
No response, if you r issue is continuing, please visit our discord.
