### ISSUE TITLE
[BUG]: Cheat Engine is not longer able to find values

### ISSUE THREAD

**Issue by kleingulo** [PCSX2/pcsx2#7291]
### Describe the Bug

Cheat Engine Version 7.3

Cheat Engine is not able to find values in newer versions of PCSX2. Even if I know the exact value (because I already have a valid pointer to it with EEMem+Offset) and search specifically for it CE is not able to find it. 

On v1.7.3000 it works. I can't tell which update broke it.

![doesntwork](https://user-images.githubusercontent.com/59097069/198620898-2d4b0560-c855-4345-934a-88a74e77e343.PNG)
![works](https://user-images.githubusercontent.com/59097069/198620977-fe82eaf8-f191-4e7e-97d7-f31ba64332d7.PNG)

### Reproduction Steps

1. Attach Cheat Engine to PCSX2
2. Run a game
3. Search for a known value in Cheat Engine

### PCSX2 Revision

v1.7.3491

### Operating System

Windows 11

**Comment by Tokman5** [comment]
you selected `4 Bytes` for scan type instead of `2 Bytes`

**Comment by kleingulo** [comment]
Thank you for your reply.
> you selected `4 Bytes` for scan type instead of `2 Bytes`

 That's true but the screenshots are only to show what the problem is and are not from real tests. But I prepared a new screenshot with proper settings.

![doesntwork2](https://user-images.githubusercontent.com/59097069/198653602-764e56d8-cd05-4f8d-9dc8-c24e692cc107.PNG)

**Comment by stenzek** [comment]
EE memory is now an anonymous/pagefile-backed memory-mapped file. We need this for fastmem (coming soon).

If cheat engine can't handle it, that's cheat engine's problem. The EEmem export should point to the main mapping of this file. You can also read it by opening the file named `pcsx2_<pid>`, where `<pid>` is PCSX2's process ID.

**Comment by CookiePLMonster** [comment]
It's an option in Cheat Engine, disabled by default:
![image](https://user-images.githubusercontent.com/7947461/198683038-e49ea04b-18fd-454a-8c3f-47d074577ff1.png)

**Comment by kleingulo** [comment]
> It's an option in Cheat Engine, disabled by default: ![image](https://user-images.githubusercontent.com/7947461/198683038-e49ea04b-18fd-454a-8c3f-47d074577ff1.png)

Yes, thank you. With the help of stenzek's comment I was able to figure that out and tested it already. It works.
