### ISSUE TITLE
[BUG]: Grand Prix Challenge: Graphical Fog on the tracks

### ISSUE THREAD

**Issue by mikewwm8** [PCSX2/pcsx2#7292]
### Describe the Bug

During a race, there's some gray-blue fog that covers the front of the screen. Happens on every resolution, with the only fix being Software mode.

### Reproduction Steps

Pick any driver and select any circuit.

### Expected Behavior

The track should be clear of the fog.

### PCSX2 Revision

1.7.3493

### Operating System

Windows 10 (64bit)

### CPU

i9-11900k

### GPU

RTX 3080

### GS Window Screenshots

![Grand Prix Challenge_SLES-51296_20221028010528](https://user-images.githubusercontent.com/97572341/198737272-6b28ce5f-2a3a-4798-bfce-285037156969.png)
![Grand Prix Challenge_SLES-51296_20221028010018](https://user-images.githubusercontent.com/97572341/198737289-fd10a555-8745-4e4a-8835-4ad30cc4d967.png)
![Grand Prix Challenge_SLES-51296_20221028010531](https://user-images.githubusercontent.com/97572341/198737303-c12c9c8d-928d-41c0-9797-74e2694b5682.png)

### Logs & Dumps

[Grand Prix Challenge_SLES-51296_20221028010531.zip](https://github.com/PCSX2/pcsx2/files/9892111/Grand.Prix.Challenge_SLES-51296_20221028010531.zip)

**Comment by Oymat** [comment]
Disabling depth emulation fixes it.

**Comment by refractionpcsx2** [comment]
yes, I had told the user that, but it's not really a fix.

**Comment by JordanTheToaster** [comment]
May need align sprite or HPO Special to fix misaligned effects.

**Comment by MrCK1** [comment]
Still broken as of v1.7.4933
