### ISSUE TITLE
[BUG]: Dragon Ball Infinite World: Vertical Lines Error in Loading 3x Native

### ISSUE THREAD

**Issue by MatheusVini98** [PCSX2/pcsx2#7293]
### Describe the Bug

When I start the game at 3x Native resolution with Wild Arms Hack, the loading screen has vertical lines bugs in Vulkan.

Note: In version 1.6 with the direct3d11 renderer and with the ps2 bilinear texture filter together with the GPU Pallet Conversion the error was fixed, but in the current dev versions the error returned.

Note2: When I start with the same settings in version dev 1.7 or with the nearest texture filter , the bug disappears, but for me the game has worse textures.

Note3: I've already tested it with other renderers (DirectX and OpenGL) in dev 1.7 versions but the bug remains.

Note4: I chose to activate the hacks manually, in particular the Wild Arms Hack because it improves the graphic quality in the game.

### Reproduction Steps

Start the game in 3x Native with Wild Arms Hack

### Expected Behavior

Loading screens do not have vertical lines on the side.

### PCSX2 Revision

1.7.3494

### Operating System

Windows 10 (64bit)

### CPU

I5-3330K

### GPU

GT 1030

### GS Settings

![image](https://user-images.githubusercontent.com/84043205/198813576-78437e32-c239-4c5d-b3b0-35ec326b8ba2.png)

![image](https://user-images.githubusercontent.com/84043205/198813582-93c8fedb-5302-45a6-8dd4-568c885b293b.png)

![image](https://user-images.githubusercontent.com/84043205/198813589-f3f0f84e-3002-42a5-b7ec-d14a58d29ea2.png)

![image](https://user-images.githubusercontent.com/84043205/198813789-e0d6f75e-a389-4206-b90d-bfda1a9d4ec9.png)

![image](https://user-images.githubusercontent.com/84043205/198813593-5330b77e-5566-4e81-b210-b1518d09bbcd.png)

### Emulation Settings

With almost everything in default.

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/84043205/198813647-6c02a0bc-3aed-4287-8a0c-c1eaed0145d9.png)

**Comment by RedDevilus** [comment]
`With almost everything in default.`

`Sees a lot of changed settings` 

How does default look? Or even better a gsdump.

**Comment by MatheusVini98** [comment]
Sorry I described it wrong, but what I changed the most was the graphics part .

An example of standard graphics:
![Dragon Ball Z Infinite World_SLUS-21842_20221029015341](https://user-images.githubusercontent.com/84043205/198814880-e546b503-fc5b-448d-9af9-b7eae804931c.png)

Dump Textures:
![3e4e869ada2414c4-f4d5e5be81704fcb-00005d94](https://user-images.githubusercontent.com/84043205/198814905-227a9de9-1fc3-427b-b1d9-8c290e61d52b.png)
![5ec73055849857a9-b3fcd91ae3d26037-00005954](https://user-images.githubusercontent.com/84043205/198814907-10c8d971-b25f-45a8-8750-1a9c3c9d9926.png)
![9bfc8b6d9f92586-c7b4a5e9c3788f9f-00005d94](https://user-images.githubusercontent.com/84043205/198814909-901efe11-fedf-47e4-a934-a2a7754ddda9.png)
![769550731aaffcef-1b1326a98872585e-00005d94](https://user-images.githubusercontent.com/84043205/198814910-f2d74396-ceed-4433-aae6-93e68e8c304f.png)

Thanks !

**Comment by MatheusVini98** [comment]
Sorry I was trying to attach the gs.file!
[Dragon Ball Z Infinite World_SLUS-TexturesError.zip](https://github.com/PCSX2/pcsx2/files/9893121/Dragon.Ball.Z.Infinite.World_SLUS-TexturesError.zip)

**Comment by MatheusVini98** [comment]
It's probably error in Allow 8 bit texture, ... in version 1.6 with directx11 it works fine, but when it's in version 1.7 with GPU Pallet Conversion and in other renderers it doesn't work!

**Comment by RedDevilus** [comment]
To be fair you can use texture offset X:300 when you upscale at 3x or just don't upscale as they are 2D sprites that won't upscale either way.

**Comment by MatheusVini98** [comment]
Thanks for the answer, I tried with texture offset X:300 but it didn't work, it's possible that because it's 2D I can't upscale it.

**Comment by RedDevilus** [comment]
Try different numbers between 100-500 but yeah kinda silly to not use software mode, besides this is just an upscaling bug.

Hence I shall close it for now as this is more a support level issue than an emulator / game issue itself.

**Comment by MatheusVini98** [comment]
![gsdx_20221031013752](https://user-images.githubusercontent.com/84043205/198932314-2a5a14b7-f4bd-4ea8-a031-ebdac73f2e9e.png)
This is version 1.6 with Wild Arms Hack and upscale 3x Native.
Thanks bro for the help, I'm done for today.

**Comment by MatheusVini98** [comment]
[SLUS-21842.zip](https://github.com/PCSX2/pcsx2/files/9916749/SLUS-21842.zip)

>>>Textures fixed in other filters in 2xNative and 4xNative ! just load and replace!<<<
