### ISSUE TITLE
[BUG]: Linux/KDE - some settings controls are invisible 

### ISSUE THREAD

**Issue by Grief** [PCSX2/pcsx2#7297]
### Describe the Bug

Controls are there, there are tooltips and they seem to work, but they are invisible:
![image](https://user-images.githubusercontent.com/7239315/198850922-77d29b65-b602-42ab-8627-7bfe7bef1ee3.png)

### Reproduction Steps

Just open general settings settings >VUs for example

### PCSX2 Revision

1.7.0~git202210282204+202210291909~ubuntu22.04.1

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

KDE neon

**Comment by RedDevilus** [comment]
Reminds me how the Arabic WX has troubles with drawing the elements for the options.

Can you try Qt instead? As WX is going to be deprecated in the future.

**Comment by Grief** [comment]
@RedDevilus thanks for pointing me to this. version Didn't find any issues after a hour of testing

**Comment by lightningterror** [comment]
Closing as it's a wx issue/legacy.
