### ISSUE TITLE
Sims 2 Castaway PAL/NTSC - SLES-54903 - Not properly rendered parts in GSdx HW Mode

### ISSUE THREAD

**Issue by o0castaway0o** [PCSX2/pcsx2#73]
-PCSX2 version: 1.3.0.5889 (svn) Feb 9 2014, 1.2.1 2014-2-2 (stable)

-PCSX2 options: Default except there were no speed hacks used.

-Plugins used: GSdx, SPU2-X, Lilypad, Gigaherz CDVD, rest null plugins

-Plugin settings: Tested GSdx DX9/11 and Open GL hardware and software renderers. The issue is fixed with a DX9/11 and Open GL software renderer of GSdx

-Description: Some parts of the "samples" and all command fonts (for example "pick up an item on the ground as and character option") aren't rendered properly.

-How to replicate: Use Sims 2 Castaway (PAL or NTSC doesn't matter) and run the game in HW Mode

-Last known version to work: Unknown, probably never worked

-PC specifications: CPU: AMD Athlon X4 750K @ 4.20Ghz, GPU: ASUS Radeon R9 270X 2 GB, OS: Windows 8.1 SP1, SSD : Samsung 840 EVO 250GB

-Other comments: -

![Image 1](https://www.dropbox.com/s/wbpp1xxgwgvok98/sles-54903_hw_00.png?dl=1)
![Image 2](https://www.dropbox.com/s/p4muitc88wsb2p7/sles-54903_hw_01.png?dl=1)
![Image 3](https://www.dropbox.com/s/yjgzyow4q20wvv0/sles-54903_sw_00.png?dl=1)
![Image 4](https://www.dropbox.com/s/5yk00vh3dogjgzj/sles-54903_sw_01.png?dl=1)

Also in the game' .iso there are 2 files that may be causing this problem - 
SAMPLES.ARC and FONTS.ARC these are of course assumptions and something else could be the source of the problem but these files stood out because the problem are the samples of in-game items and the action text fonts.

**Comment by bositman** [comment]
This is now fixed with OpenGL HW using blending unit accuracy basic or higher.
Has some upscaling issues and got a random crash but this is definitively fixed. Tested NTSC version but this is 99% fixed for PAL too.

**Comment by o0castaway0o** [comment]
Thanks so much, worked like a charm!!!

**Comment by gregory38** [comment]
Oh great. Cool
