### ISSUE TITLE
Shadow Hearts From The New World Light seen through walls (Vulkan & DX12)

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#7303]
### Describe the Bug

When using Vulkan or DX12 light and rays can be seen through walls in certain areas. This doesn't happen with Opengl, DX11 or Software mode. Positive that this has been an issue since vulkan and dx12 became available. 

### Reproduction Steps

Start the game get to the room with the first save point using vulkan or dx12 and see the light from the windows shine through the staircase and wall. 

### Expected Behavior

Light shouldn't be visible through objects. 

### PCSX2 Revision

Nightly v1.7.3501

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default

### Emulation Settings

default

### GS Window Screenshots

![Screenshot (14)](https://user-images.githubusercontent.com/12180630/199048258-b28db5dd-357e-44b9-936d-08e0ff6e72f6.png)
![Screenshot (15)](https://user-images.githubusercontent.com/12180630/199048266-55e5d91e-1aab-4e6f-80c1-c139cc7589fa.png)

### Logs & Dumps

GS dump
[Shadow Hearts 3.zip](https://github.com/PCSX2/pcsx2/files/9902577/Shadow.Hearts.3.zip)

**Comment by refractionpcsx2** [comment]
Funny enough Bositman brought this to my attention earlier today. I'm not sure of the source of it, but it doesn't look to be a CLUT thing like was previously fixed.

Here's another GS Dump with a volcano/mountain in view.
[Shadow Hearts - From the New World_SLUS-21326_see-thru-light.gs.zip](https://github.com/PCSX2/pcsx2/files/9902612/Shadow.Hearts.-.From.the.New.World_SLUS-21326_see-thru-light.gs.zip)

**Comment by refractionpcsx2** [comment]
I guess everybody is hyped up for light occlusion issues right now because of the recent fixes :P

**Comment by BParks21** [comment]
Yeah that's why I decided to report it. I've known about the issue in this game for a while now before the recent fixes so was hoping it was fixed.

**Comment by refractionpcsx2** [comment]
Nope, sorry, different problem! However if you have bugs, please report them, it might be good to come on our discord and see if there's any fix (we also have a #public-testing channel) before posting issues for games on github, but they are easier to fix when we know about them :P

**Comment by BParks21** [comment]
Yeah I'm aware. I'm just lazy sometimes also I report a lot if issues so sometimes I feel like I'm over reporting lololol.

**Comment by refractionpcsx2** [comment]
You've been pretty quiet compared to some :P

anyway, should probably stop spamming the issue, thanks for the report!
