### ISSUE TITLE
[BUG]: Lego Star Wars Audio stuters randomly

### ISSUE THREAD

**Issue by tottoszsolt** [PCSX2/pcsx2#7309]
### Describe the Bug

While playing the game Lego Star Wars, after like 5-6 minutes of playing starts the audio to suddenly stuter, and after that does it randomly.

### Reproduction Steps

Play the game for like 5 minutes upscaled to 1080p default settings

### Expected Behavior

No audio stuters 

### PCSX2 Revision

v1.7.3508

### Operating System

Windows 11

### CPU

i5-9400f

### GPU

GTX 1060 6GB

### GS Settings

Upscaled to 3x 1080p

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by JordanTheToaster** [comment]
Sound is fine on v1.7.3994.
