### ISSUE TITLE
[BUG]: VP2 artifacting along the bottom edge in HW

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2#7310]
### Describe the Bug

HW renderer shows artifacts along the bottom of the image
![image](https://user-images.githubusercontent.com/49990481/199282734-d05f6b59-c428-4d58-b823-21b774002ac7.png)
SW
![image](https://user-images.githubusercontent.com/49990481/199283988-19d39320-7709-4c53-9af5-17fa1360845c.png)

seems to be a regression from https://github.com/PCSX2/pcsx2/pull/6659. Artifact doesnt appear before v1.7.3140 (pic below is 1.7.3139)
![image](https://user-images.githubusercontent.com/49990481/199296996-6f3c830c-5426-4d18-9c2f-97b726899de2.png)

### PCSX2 Revision

1.7.3508

### Operating System

Windows 10 (64bit)

### CPU

i7 4790

### GPU

rx 570

### Logs & Dumps

https://cdn.discordapp.com/attachments/963262918491799572/1037038665077108837/Valkyrie_Profile_2_-_Silmeria_SLUS-21452_20221101121629.gs.xz

**Comment by Scalerize** [comment]
Setting round sprite to: Full
And half-pixel offset to: Special (Texture)

Seems to Cover most of the artifacts.

**Comment by Mrlinkwii** [comment]
@Scalerize  it happens at native HW , so that dosent slove the issue

**Comment by Scalerize** [comment]
> @Scalerize it happens at native HW , so that dosent slove the issue , also that will break the game further down the line if up-scaling

Just a temporary fix, I know the team hates adding these to the gameindex. but it can be a temporary fix until the team is ready to make changes to #6659

**Comment by Mrlinkwii** [comment]
@Scalerize  it wont be a temporary fix, the game hates up-scaling and adding up-scaling fixes will break other places in game such as the red forest etc  ( you can get around most of the up-scaling issues  at x1.75)  but otherwise its a non fix

**Comment by Scalerize** [comment]
> @Scalerize it wont be a temporary fix, the game hates up-scaling and adding up-scaling fixes will break other places in game such as the red forest etc ( you can get around most of the up-scaling issues at x1.75) but otherwise its a non fix

also note that the ps4 suffers the same issue https://www.psdevwiki.com/ps4/Talk:PS2_Classics_Emulator_Compatibility_List#Valkyrie_Profile_2:_Silmeria

**Comment by refractionpcsx2** [comment]
Messing with the upscaling fixes cause problems with other parts of the game, especially the red forest, and Round Sprite Full has a habit of being quite destructive.
