### ISSUE TITLE
Primal Black Screen Bug In Hardware.

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#7315]
### Describe the Bug

Using Vulkan backend, after it loads, you can hear the characters speaking but no visuals. The Pause Screen works fine.
Switching to software works fine.

### Reproduction Steps

Press 'New Game', wait until it loads. 

### Expected Behavior

Both visuals & sound work.

### PCSX2 Revision

V1.7.3511

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Native settings.

### GS Window Screenshots

Gameplay:
![Primal_SCES-51135_20221101223647](https://user-images.githubusercontent.com/116039192/199358740-5f3b3551-58ab-4097-8f63-544536e4b3b3.png)
Pause Menu:
![Primal_SCES-51135_20221101223735](https://user-images.githubusercontent.com/116039192/199358791-706c8cc0-f780-424c-9ff7-82e11dfaaa4a.png)
Software Mode:
![Primal_SCES-51135_20221101224112](https://user-images.githubusercontent.com/116039192/199359242-b87679bb-92d3-46ed-8ce9-39e52ed6b644.png)

### Logs & Dumps

[Gameplay (Black Screen Dump).zip](https://github.com/PCSX2/pcsx2/files/9914569/Gameplay.Black.Screen.Dump.zip)
[Pause Menu Dump.zip](https://github.com/PCSX2/pcsx2/files/9914570/Pause.Menu.Dump.zip)

2 GS dumps included at different stages.

**Comment by refractionpcsx2** [comment]
Duplicate #909
