### ISSUE TITLE
Why the community of PCSX2 is absolute shit...

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#732]
1.Abuse other users and the community exchanges laughs.

2.No punishment given to community members who are sickly rude to others, if they've been around.

3.Community members and mods never get banned, but any user who talks back does. Sounds and operates just like the American police system -- brothers in arms, and fuck those who don't obey.

4.Extreme bias in the community and self-righteousness.

5.People who should all die a painful, long death.

**Comment by Ryudo300** [comment]
Seek some help for that built up anger inside of you ButterNiffe.

**Comment by ssakash** [comment]
He's been banned , just wasting his time. better to ignore him ;)

**Comment by ghostfo** [comment]
I am banned but I can keep posting you Indian with a little dick. ;)

**Comment by ghostpro** [comment]
" "B-BUT YOU DIDN'T RATE MY VIDEO YOU IDIOTS STOP TAKING OVER MY THREAD" "

Yeah, like I said that ... stop misappropriating things -- you were all assholes to me and won't admit it.

Nothing will change my mind because I was treated rudely and poorly. I am getting help for nothing, because the people who need help are right here beside me in this thread, among many others.

**Comment by Ryudo300** [comment]
Actually we were never assholes to you. We gave you advice on improving your video. It was an annoyance to watch with the slowdowns. And that was -before- you even edited your original post to edit in that you were suffering from slowdowns. 

When a video is an annoyance to watch, it obviously means that it was not amusing.

Here's my response to your video:

- It was bad.
- Your deaths were lame.
- It was unfunny.
- You're unfunny.

There. You got your answer. :)

**Comment by ghostsherlock** [comment]
Finally, after two days, Ryudo actually answers the main question! Congrats!

Thanks for the honesty. I'll never bother you guys again. :)

Cheers for PCSX2! I've been playing MGS2 all day and although I thought my video was funny, it's realistic to believe someone will find it unfunny. It's reality ... an answer is all I wanted.

I love you all and hope you can fix GSDX trilinear mipmapping in hardware mode 100%. :+1:

**Comment by robertybob** [comment]
What a twat.
