### ISSUE TITLE
[BUG]: [SLPM-62581] K-1 Premium 2004 Dynamite!! | Geometry flashing in and out + bad deinterlacing

### ISSUE THREAD

**Issue by Gomam0n-afk** [PCSX2/pcsx2#7324]
### Describe the Bug

Geometry for characters, the ring, and some 3D GUI stuff flashes in and out, seemingly depending on the camera position
This bug happen in both Software and Hardware mode (Tested with DX12)

The deinterlacing in this game seems to be also wrong as the image is quite blurry, and jumpy (look at the projectors, or logos on the ring in the fight intro)

Video of this bug : https://www.youtube.com/watch?v=-_6ueLu3fhQ

### Reproduction Steps

Play the game with any character.
Get a seizure
???
Profit.

### Expected Behavior

Sharp image and no geometry flashing.

### PCSX2 Revision

v1.7.3516

### Operating System

Windows 10 (64bit)

### CPU

i7-7700

### GPU

GTX 1060 6GB

### GS Settings

Render mode set to DirectX 12, Interger upscaling and Anti-Blur hacks are turned on. Everything else is as default.

### Logs & Dumps

I was not able to take a proper GS Dump, as the issue happens too fast.

**Comment by prafullpcsx2** [comment]
Disabling instant vu1 should fix the flashing

**Comment by refractionpcsx2** [comment]
The de-interlacing looks normal to me, but yeah try turning off instant-vu to solve the flashing.

**Comment by Gomam0n-afk** [comment]
> The de-interlacing looks normal to me, but yeah try turning off instant-vu to solve the flashing.

Game completely crashes before showing the main menu after i disabled Instant VU1. Music still runs in the background, no error message in console
![image](https://user-images.githubusercontent.com/59240947/199789877-0f200153-4580-4957-9f4d-47f483f6b41c.png)

**Comment by prafullpcsx2** [comment]
Why you enabled mtvu? That will cause the crash

**Comment by Gomam0n-afk** [comment]
> Why you enabled mtvu? That will cause the crash

The game works with both turned on at the same time.
I disabled both and it fixed the geometry issue, only issue left is the deinterlacing that doesn't look good.

**Comment by Gomam0n-afk** [comment]
Ok i did a little testing, and Bob (Top field first) looks a lot sharper on this game.
![image](https://user-images.githubusercontent.com/59240947/199875109-3c4e85b3-379b-4ee1-a13c-c263bc938fc6.png)

**Comment by refractionpcsx2** [comment]
It will, yeah, because that's basically cheating out of deinterlacing

**Comment by refractionpcsx2** [comment]
I think this is fixed now, can somebody recheck?
