### ISSUE TITLE
[BUG]: Underwater shadow is broken in Ape Escape 2

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#7330]
### Describe the Bug

The character shadow in underwater environments is not reflected correctly, as the screenshot below shows:

![Ape Escape 2_SLUS-20685_20221103215140](https://user-images.githubusercontent.com/27839354/199863022-8a0fe35e-1bd7-4fc8-8119-8a32e9c3453c.png)

### Reproduction Steps

- Go to water environments such as the Water Net gadget training stage.
- Dive into the water with the Water Net gadget using right analog stick up to see the broken shadow in the deep of the water.

Save state:
[SLUS-20685 (BDD9F5E1).01.zip](https://github.com/PCSX2/pcsx2/files/9934126/SLUS-20685.BDD9F5E1.01.zip)

### Expected Behavior

I suppose it wasn't suppose to look that way.

### PCSX2 Revision

1.7.3521

### Operating System

Windows 10 (64bit)

### CPU

i5-10400

### GPU

GTX 1660 Ti

### GS Settings

All default settings as far as I remember.

### Emulation Settings

All default settings as far as I remember.

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/27839354/199864028-370e0b95-721a-4806-b2ab-04876699fe73.png)
![image](https://user-images.githubusercontent.com/27839354/199864052-3389e800-6033-42bb-a229-f25822ec86dc.png)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/9934116/snaps.zip)

**Comment by refractionpcsx2** [comment]
Duplicate #5342

**Comment by MGS290** [comment]
I have this issue with NetherSX2 emulator in Android device, how i can solve this issue of the shadow under water? Because it's appearing in both graphic Renderer settings : OpenGL and Vulkan

**Comment by JordanTheToaster** [comment]
> I have this issue with NetherSX2 emulator in Android device, how i can solve this issue of the shadow under water? Because it's appearing in both graphic Renderer settings : OpenGL and Vulkan

This is not the place to ask for support nor do we provide support for anything that isn't PCSX2.
