### ISSUE TITLE
[BUG]: Silent Hill Origins broken inventory screen

### ISSUE THREAD

**Issue by Jakey757** [PCSX2/pcsx2#7332]
### Describe the Bug

Examining an item for a short time, then going back to the inventory causes the status picture to break (if done quickly it does not happen).

https://user-images.githubusercontent.com/49990481/199870713-0d0bc6d2-e98f-44c5-987a-afc53efe0ee2.mp4

Changing graphics settings or switching between SW/HW while the inventory screen is open additionally causes the windows containing the item icons to turn green.

![Silent Hill - Origins_SLUS-21731_20221103203004](https://user-images.githubusercontent.com/49990481/199871129-3a723d65-c15d-4762-ae7f-d747b67a2eb1.png)

Any GS dumps taken regardless of how the screen currently looks, end up broken like the above image. SW works properly, only affects HW renderers. Screen returns to normal after exiting and reopening. None of the hardware fixes prevent it from happening or change it after it has already happened.

Reportedly (respective wiki's and a user) happens in Silent Hill 2+3 as well, but no issue exists for those games either.

### PCSX2 Revision

1.7.3521

### Operating System

Windows 10 (64bit)

### CPU

i7 4790

### GPU

rx 570

### Logs & Dumps

https://cdn.discordapp.com/attachments/963262918491799572/1037915723030335578/Silent_Hill_-_Origins_SLUS-21731_20221103221218.gs.xz

**Comment by refractionpcsx2** [comment]
Can't really use a GS dump for this, unfortunately, it's already broken by this point :(

**Comment by Jakey757** [comment]
figured, just provided it just in case. if there's anything else i can do just lmk.

**Comment by BenoitAdam94** [comment]
I think I have similar issue with the inventory not always showing the weapons/items on the PSP emulator PPSSPP.

Guess this has been coded with the feet.

**Comment by Mrlinkwii** [comment]
can this be rechecked on latest nightly :)

**Comment by Jakey757** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/49990481/e2e400ad-19da-499b-8ddd-f6767dfcbb90)
still happening.

**Comment by AmyRoxwell** [comment]
Hey, maybe try this pr?
https://github.com/PCSX2/pcsx2/pull/11028
