### ISSUE TITLE
[BUG]: Saves sometimes register as corrupt

### ISSUE THREAD

**Issue by ajdelguidice** [PCSX2/pcsx2#7347]
### Describe the Bug

Sometimes save games register as corrupt even though they aren't. Closing PCSX2 and reopening it fixes the corrupt data messages. This was only happening when I use PCSX2 on a flash drive.

### Reproduction Steps

Use PCSX2 on a slow flash drive.

### PCSX2 Revision

1.7.3532

### Operating System

Windows 10 (64bit)

**Comment by RedPanda4552** [comment]
What specific games are affected? What type of memory card are you using? By "corrupt" do you mean appearing as corrupted data blocks in the BIOS? Is there any reason you are attempting to use PCSX2 on a USB device?

**Comment by ajdelguidice** [comment]
All of the games that I've tried playing will randomly have this issue. By corrupt I meant inside the games the data is read as corrupt and the game either or asks to write over it depending on what data is read as corrupt. I was using PCSX2 on a flash drive because I use it on multiple computers (one when I'm at home and one when I'm not).

**Comment by RedPanda4552** [comment]
What specific games are affected?

**Comment by ajdelguidice** [comment]
So far I've only tried a couple of games. The ones that I've tried that are affected are Jak II, Lego Batman, and Pacman World(1, 2, and 3)

**Comment by RedPanda4552** [comment]
Does the issue occur when not playing on a USB device? Most likely your USB device is doing weird things and not handling PCSX2's requests to modify the files.

**Comment by ajdelguidice** [comment]
I haven't encountered this while using PCSX2 off of a flash drive but I tried it on a different flash drive and it still does it.

**Comment by ajdelguidice** [comment]
It's not written as corrupted data, the data is fine it's just read as corrupted until I restart PCSX2

**Comment by RedPanda4552** [comment]
I think that says even more about the USB device than it does PCSX2. Memcards are always read from disk, never cached in memory.

**Comment by ajdelguidice** [comment]
I actually think it might be the game game giving up if it does read it fast enough.

**Comment by RedPanda4552** [comment]
Memory card reads have large timeouts and multiple retry loops baked in, it is very hard to accomplish that. Furthermore in order for a USB device to be slow enough to somehow be seen as a failed read or write, you would have to be *below* USB 2.0 speeds, I think actually USB 1.1 might still be faster than a PS2 memory card. Lastly, a failed read or write due to unresponsiveness would make the game report the memory card as missing, or a read/write failure, not as corrupted data.

**Comment by ajdelguidice** [comment]
Just got an ssd to use instead of a flash drive and the issue seems to be fixed.
