### ISSUE TITLE
[BUG]: Cannot load this savestate. The state is an unsupported version.

### ISSUE THREAD

**Issue by DonutWrecker** [PCSX2/pcsx2#7351]
### Describe the Bug

<img width="1920" alt="ss" src="https://user-images.githubusercontent.com/67188697/200410978-804e9561-e24e-4d24-8cf9-9b583344b32f.PNG">

"Cannot load this savestate. The state is an unsupported version."

This is the error I get when I try to load my savestate that I've saved 22 hours ago. I update my PCSX2 regularly, once in a day. Yesterday, the savestates I've saved was working as expected, but after updating today, there were like 5 or 6 commits, I couldn't load the savestates anymore.

The game I'm currently playing is Silent Hill - Shattered Memories (USA). Here are my latest savestates:
[SLUS-21899 (61A7E622).01.zip](https://github.com/PCSX2/pcsx2/files/9955233/SLUS-21899.61A7E622.01.zip)
[SLUS-21899 (61A7E622).03.p2s.zip](https://github.com/PCSX2/pcsx2/files/9955238/SLUS-21899.61A7E622.03.p2s.zip)
[SLUS-21899 (61A7E622).02.zip](https://github.com/PCSX2/pcsx2/files/9955244/SLUS-21899.61A7E622.02.zip)

### Reproduction Steps

1. Load one of the savestates.
2. Get the mentioned error.
3. Revert the last 5 or 6 commits (maybe a little more).
4. Load one of the savestates, again.

### Expected Behavior

You'll get the error window "Cannot load this savestate. The state is an unsupported version." when you try to load the attached savestates.

### PCSX2 Revision

v1.7.3536

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
You were warned when the update came in, if you want to use old states go back to an older version.
