### ISSUE TITLE
[BUG]: Low performance on The Punisher

### ISSUE THREAD

**Issue by 15Cyber** [PCSX2/pcsx2#7352]
### Describe the Bug

The emulator presents low performance in the game The Punisher, in certain moments of the gameplay where there is the presence of smoke and lens flare the fps drops to 30-45, when we return to areas without smoke or lens flare we return to 60fps. This happens even at native resolution in all render modes, even in software mode.

### Reproduction Steps

The problem always happens when there is smoke, lights or other effects like lens flare on the screen.
Renderers: Direct3D 11, Direct3D 12, OpenGL, Vulkan (in native and upscaled resolution)
![punisher](https://user-images.githubusercontent.com/114396894/200440406-17679068-e3af-4943-a3d9-1bebf5d20415.PNG)

### PCSX2 Revision

v1.7.3538

### Operating System

Windows 10 (64bit)

### CPU

Ryzen  7 2700

### GPU

GTX 1060

### GS Settings

Default GS settings with and without upscaling on any renderer.

### Emulation Settings

Default

**Comment by F0bes** [comment]
Can you provide a GS dump when the low performance happens?

```
How To Create A GS Dump
What is a GS dump?
A GS dump is an export of instructions sent from the PS2 core to the "Graphics Synthesizer" (aka "GS"). The instructions can be replayed in PCSX2 to quickly reproduce, inspect, and resolve graphics errors. This allows helpers to figure out what's wrong with a game, and developers to fix the emulator.

For wxWidgets Builds:
Use the key combination Shift + F8

For Qt Builds:
Debug > Save Single Frame GS Dump

Where does the GS dump save to?
GS dumps are saved to the /snaps folder.
- If you used the PCSX2 installer, you will find it in Documents/PCSX2.
- If you are using a nightly build, you will find it next to the PCSX2 executable.

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
```

Also, enable all the OSD stats in the graphics settings, and provide a screenshot of them when the slowdown happens.
Example:
![image](https://user-images.githubusercontent.com/29295048/200637515-9e5f6d60-afae-4b36-8468-fb845ca372f6.png)

**Comment by refractionpcsx2** [comment]
GS Dump won't help, the VU's get destroyed.

**Comment by refractionpcsx2** [comment]
anyway, this is a support issue, not a bug. If you want help with this, I suggest joining our discord or forums. Links on pcsx2.net
