### ISSUE TITLE
[Feature Request]: automatic game cover searcher

### ISSUE THREAD

**Issue by alighamdan** [PCSX2/pcsx2#7353]
### Description

I suggest adding a un/checked button in the settings which allows searching for a cover for all games that don't have one on the internet and setting a cover for every game

I was searching for covers by the game name most of the games were in Wikipedia and I got their cover from the wiki

### Reason

it will be good to know the games faster

### Examples

![image](https://user-images.githubusercontent.com/73795044/200472011-c8e4abd0-b482-4ea8-80db-cea43ccd78c3.png)

**Comment by stenzek** [comment]
There is already a cover downloader. But as covers are copyrighted, the builtin tool is only intended to be used with your own hosted files, and you must provide URLs yourself.
