### ISSUE TITLE
[BUG]:  Clannad/Tomoyo After's graphics are distorted with hardware rendering

### ISSUE THREAD

**Issue by msksk** [PCSX2/pcsx2#7356]
### Describe the Bug

Graphics of the games listed below are distorted.
This bug does not happen with software rendering mode or v1.6.0, so I think this is peculiar to v1.7.x's HW rendering.

### Clannad (SLPM-66302)
Software:
![Clannad_SLPM-66302_20221109031616](https://user-images.githubusercontent.com/53204975/200646026-15bf97c5-e1eb-4cdb-a5ce-0918e20a9afe.png)

Hardware:
![Clannad_SLPM-66302_20221109031552](https://user-images.githubusercontent.com/53204975/200646034-16a1cf30-e53e-44c3-8c45-74dc0d1376b2.png)

### Tomoyo After (SLPM-66611)
Software:
![Tomoyo After - It's Wonderful Life  CS Edition _SLPM-66611_20221109030937](https://user-images.githubusercontent.com/53204975/200646250-844f38b5-bb4b-44ee-9bc2-a0f013391599.png)
Hardware Pattern 1:
![Tomoyo After - It's Wonderful Life  CS Edition _SLPM-66611_20221109031315](https://user-images.githubusercontent.com/53204975/200646263-a18ee75d-67a9-4f73-b561-3dd9cc633ca5.png)
Hardware Pattern 2:
![Tomoyo After - It's Wonderful Life  CS Edition _SLPM-66611_20221109030921](https://user-images.githubusercontent.com/53204975/200646274-d733be3a-9abe-4d71-9803-1f5016967a53.png)

Both of them have some internal movies, which they can play with no problem like this:
![Tomoyo After - It's Wonderful Life  CS Edition _SLPM-66611_20221109031411](https://user-images.githubusercontent.com/53204975/200645893-abcdb879-2589-4965-b6fc-3565511a300e.png)

### Reproduction Steps

1. Launch PCSX2.
2. Set the renderer to any of Direct3D 11, Direct3D 12, OpenGL, and Vulkan.
3. Boot the game.

### Expected Behavior

Bad graphics.

### PCSX2 Revision

pcsx2-v1.7.3540 (I could see also in v1.7.2203)

### Operating System

Windows 10 (64bit)

### CPU

i5

### GPU

gtx-1650

### GS Settings

Set the renderer to any of Direct3D 11, Direct3D 12, OpenGL, and Vulkan.

### Emulation Settings

Default settings.

### GS Window Screenshots

see Describe the Bug.

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/9964178/snaps.zip)

**Comment by refractionpcsx2** [comment]
When it builds, can you try #7357 ? do you know how to access action builds (not normal releases)?

**Comment by refractionpcsx2** [comment]
Since you didn't provide a GS Dump for Tomoyo After, I've just assumed the PR will fix it, so if you could check that for me, and if it doesn't, I'll need a GS Dump. Thanks.

**Comment by msksk** [comment]
I tested with your https://github.com/PCSX2/pcsx2/actions/runs/3422831550 and checked the bug is fixed.

Thank you so much!
![image](https://user-images.githubusercontent.com/53204975/200805313-87cec476-207d-4778-b137-5d8790041e85.png)

![image](https://user-images.githubusercontent.com/53204975/200804820-7d83d96a-7385-43f5-b79b-89f1a240a8ed.png)

**Comment by refractionpcsx2** [comment]
alright, thanks :) In future please don't close the issue, it will auto close and link to the PR when I merge it :)

**Comment by msksk** [comment]
Okay, I'll keep in my mind.
