### ISSUE TITLE
[Feature Request]: Notify when RetroAchievements not synced correctly

### ISSUE THREAD

**Issue by IggniFyre** [PCSX2/pcsx2#7361]
### Description

I often notice that RetroAchievements aren't being synced properly, with games not listing or unlocking achievements. Then I log out of my RA account and log back in, and it works fine again, but I noticed too late the achievements weren't working. You do get notified when a game does or doesn't have achievements, but it's easy to miss when you DIDN'T get a notification to indicate they're not working, so that would be nice and an immediate warning if you're looking to get achievements.

### Reason

Quality of life

### Examples

I don't know the cause of when RetroAchievements aren't being synced.

**Comment by stenzek** [comment]
If achievements aren't loaded, you won't see the notification/summary on startup.

**Comment by IggniFyre** [comment]
Yes, but it's easy to miss the fact that you didn't get notified. If you get a notification, you'll know right away something is off.

**Comment by DenowRammy** [comment]
It'd be nice if there was an achievements notice as an available column in the games list

**Comment by stenzek** [comment]
> It'd be nice if there was an achievements notice as an available column in the games list

Not possible. We don't know until game load time.

This issue is resolved with the switch to `rc_client`, you'll be notified if an achievement unlock request fails, and it'll automatically retry. Failed logins due to access tokens being invalidated will also pop up a re-authentication prompt.
