### ISSUE TITLE
[BUG]: Internet connection fails and never comes back without restarting PCSX2 if you open the settings menu ingame.

### ISSUE THREAD

**Issue by Gomam0n-afk** [PCSX2/pcsx2#7368]
### Describe the Bug

If you start playing, and open the settings menu while the game is running, the network emulation will stop working correctly until you restart PCSX2.

Note: I'm using PCAP Switched mode, over ethernet, the emulator has it's own local IP address.

### Reproduction Steps

Open any game with online capabilities.
Open the settings menu for a moment, then close it
Connect to the online mode, before or after opening the settings menu
Ethernet emulation will stop working and never come back until the emulator is restarted.

### Expected Behavior

The network emulation should still work regardless if the settings menu is open or not, or at least come back after closing it

### PCSX2 Revision

v1.7.3547

### Operating System

Windows 10 (64bit)

**Comment by TheLastRar** [comment]
Are you using the wxWidgets builds or Qt builds?

**Comment by Mrlinkwii** [comment]
can this be checked on master ?
