### ISSUE TITLE
[BUG]: Shadow Tower Abyss - Possible Interlacing-related issues (Regression?)

### ISSUE THREAD

**Issue by forrvalhalla** [PCSX2/pcsx2#7369]
### Describe the Bug

Shadow Tower Abyss appears to run de-interlaced on stable PCSX2, but has massive interlacing artifacts with dev PCSX2.

For some reason when running this game on stable PCSX2 (v1.6), the game visually appears to run in 480p. There is no screen-shake or interlacing artifacts of any kind when running the game with Auto and None de-interlacing.
![gsdx_20221108221211](https://user-images.githubusercontent.com/53349573/200987993-215816fc-dbdd-4c11-a78c-b60c65ff959e.png)

However with the dev builds of PCSX2, the game appears to run interlaced. Strangely though, there isn't any screen-shaking of any kind when setting it to None like most interlaced games do, but there are massive interlacing artifacts present when moving the camera around in any way.
![Shadow Tower Abyss_SLPS-25217_20221108220955](https://user-images.githubusercontent.com/53349573/200988505-f36dd458-8e70-47e8-8951-445924cb4b27.png)

Here's an example video to describe what I'm talking about. 

https://user-images.githubusercontent.com/53349573/200990715-af64e9a2-5ba4-421e-8623-abcb94b13dd6.mp4

I'm not the best at describing things, so I can gladly try and clarify any of this if asked. 
I apologize in advance for making a thread over what is probably an inconsequential issue, but the game looks way better on stable than dev so I figured I'd make a post about it.

### Reproduction Steps

Start new game
Look around

### PCSX2 Revision

v1.7.3547

### Operating System

Windows 10 (64bit)

### CPU

i5-7600k

### GPU

GTX 1050ti

### GS Settings

De-interlacing on None and Bilinear Filtering on Off to showcase the bug more clearly, but these options aren't required to see the bug.

### Emulation Settings

All cheats disabled, ran on fresh installs of both v1.6 and v1.7.3457 builds.

### Logs & Dumps

Multi-frame GSdump
https://cdn.discordapp.com/attachments/675471889501519922/1040101945077157908/Shadow_Tower_Abyss_SLPS-25217_20221109211041.gs.xz

**Comment by refractionpcsx2** [comment]
It if is supposed to be interlaced, you probably need to manually choose bob(I think BFF), we made it use blend more as some games weren't happy.

If it's actually 480p mode then I don't know what's happened,because interlacing code is disabled when using a progressive signal

**Comment by RedDevilus** [comment]
It's the same creator (FromSoftware) that did Kingsfield IV.

**Comment by refractionpcsx2** [comment]
Oh then it might be scanmsk, which wasn't implemented in 1.6. You're gonna need to wait for a better deinterlacing method. Sorry

**Comment by forrvalhalla** [comment]
> It if is supposed to be interlaced, you probably need to manually choose bob(I think BFF), we made it use blend more as some games weren't happy.
> 
> If it's actually 480p mode then I don't know what's happened,because interlacing code is disabled when using a progressive signal

Bob shakes with both TFF and BFF sadly with this game, on both Stable and Dev builds.



> Oh then it might be scanmsk, which wasn't implemented in 1.6. You're gonna need to wait for a better deinterlacing method. Sorry

Oh alright! That's a bummer then :( , should I close the thread? I'm really inexperienced with this kinda stuff so lemme know haha

**Comment by RedDevilus** [comment]
I couldn't figure out why the game was fine in 1.6 but looks broken in 1.7 version. But it makes sense that scanmask is actually an intended effect of the game but we can't handle it well on certain titles like this, it's still a valid issue though.

**Comment by forrvalhalla** [comment]
I went and tested some old builds to better narrow down when the issue started and yup, it seems to be related to scanmask.

The issue starts with version v1.7.2160 of PCSX2. All earlier versions (2159 and earlier) visually look fine, aside from some ghosting on a few pixels to the far right of the screen that started somewhere between v1.6 and now.

**Comment by refractionpcsx2** [comment]
if it is the same thing, this is the latest build with scanmsk disabled, that should hold you over for the moment. I have disabled updates on this build so hopefully you won't accidentally kill it :P but if we update our shaders, it's going to not work anymore (unless you make a separate folder with a version that matches this one)

[pcsx2-qtx64-avx2-fs.zip](https://github.com/PCSX2/pcsx2/files/9979405/pcsx2-qtx64-avx2-fs.zip)

**Comment by RedDevilus** [comment]
Should be fixed now with the new automatic deinterlacing method `Motion Adaptive Deinterlacing` when you update to latest (minimum 1.7.3574) version

**Comment by forrvalhalla** [comment]
MAD deinterlacing did not help with this issue, however using @refractionpcsx2's KF4 scanmask blur removal patch, I made one for STA and it works great. I'll add this to the patch repo since the KF4 one is in there, posting it here for any random people that stumble across this thread.

[Remove Scanmask Blur]
author=val
description=Disables scanmask usage to reduce blur when turning.
patch=1,EE,00158CA8,extended,24050004

**Comment by forrvalhalla** [comment]
MAD deinterlacing did not help with this issue, however using @refractionpcsx2's KF4 scanmask blur removal patch, I made one for STA and it works great. I'll add this to the patch repo since the KF4 one is in there, posting it here for any random people that stumble across this thread.

[Remove Scanmask Blur]
author=val
description=Disables scanmask usage to reduce blur when turning.
patch=1,EE,20158CA8,extended,24050004

https://github.com/PCSX2/pcsx2/assets/53349573/4fa97c07-9870-4895-9ad0-548efce42ac4

**Comment by refractionpcsx2** [comment]
There is an edit button, just for future reference :)

**Comment by forrvalhalla** [comment]
Yeah, I edited it before (goofed the patch) but I wasn't sure if I could edit a video into the post so I just went and re-upped the whole thing haha. Sorry!

**Comment by refractionpcsx2** [comment]
no problem lol, yeah I think you can change anything you like.
