### ISSUE TITLE
[Feature Request]: Hotkeys - being able to map hotkeys to a combination of controller buttons

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#7370]
### Description

As title says, as it is now you can only map a function to one keyboard, mouse or controller button, and that is great, but controllers buttons are quite limited so it would be just great to being able to use a combination of two controller buttons instead as just one, so for instance home button (XInput) that is not used by games itself could be used in junction with other buttons to perform more actions.

![image](https://user-images.githubusercontent.com/3447089/201079994-fcf7c19a-7de2-415e-8821-9622f02994bb.png)

Personally I have assigned Fullscreen toggle to Home (Xinput Guide), but I would like to have available "toggle software rendering" also via controller.

### Reason

Improves user experience/usability

### Examples

yuzu has this feature as reference...
![image](https://user-images.githubusercontent.com/3447089/201080727-d6ff3243-5a44-4b8d-abc0-860d5b8025cf.png)

**Comment by stenzek** [comment]
Already possible, except we don't have some silly "hotkey + controller hotkey" split, you can bind as many things as you want to it. Shift-click the binding - same for normal controller binds, they're all the same.

**Comment by MarcoEstevez** [comment]
Thanks for the information, I didn't know that :-)

**Comment by IlDucci** [comment]
> Shift-click the binding - same for normal controller binds, they're all the same.

Maybe this needs a hint written somewhere so people know that.

**Comment by RedDevilus** [comment]
300% DPI meme
