### ISSUE TITLE
[BUG]: Fatal Frame 1 camera flash issues

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#7371]
### Describe the Bug

The camera flash will not render a full fade in fade out effect instead will flicker like its flashing twice, stark interlacing lines may appear over the resulting photo,

https://user-images.githubusercontent.com/22896793/201156372-cde458df-1b83-4307-b114-e80c369e7fa2.mp4

### Reproduction Steps

Use any other interlacing method then the current faked blend which will cover the issue up

### Expected Behavior

One solid fade in fade out flash effect

### PCSX2 Revision

Any

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 3700x

### GPU

GTX 2070

### GS Settings

Defaults

### Emulation Settings

Defaults

**Comment by refractionpcsx2** [comment]
Just to note, toggling renderer will "fix" the issue (probably TC target mismatching).
Tex-In-RT also solves it, but will break the download, meaning the taken picture is wrong.
