### ISSUE TITLE
[BUG]: vulkan specific crash

### ISSUE THREAD

**Issue by aass0** [PCSX2/pcsx2#7372]
### Describe the Bug

I am not familiar with English, so I use machine translation. I ask for your understand.

Crashes occur at a certain point in the game with vulkan renderer, dx11, dx12 with same other GS settings does not crash, so it seems to be a problem of vulkan. The same crash occurs even if you use the intergrated and dedicated graphics cards individually, and the same result is obtained when applying native resolution.

I attach crash dump and GS dump.

### Reproduction Steps

playing certain point in the game with vulkan renderer

### PCSX2 Revision

v.1.7.3550

### Operating System

Windows 10 (64bit)

### CPU

i7-7700hq

### GPU

intel_hd630, gtx_1050_ti(M)

### Logs & Dumps

https://drive.google.com/file/d/1p7wOMAjoUe_0e3a-yReaaHkEf9VpTOXj/view?usp=share_link

**Comment by refractionpcsx2** [comment]
What are your GS settings? The most likely cause is you are running out of Video memory.  Do you get any error when it crashes?

**Comment by refractionpcsx2** [comment]
The dump works fine here, and the crash was from in your GPU drivers. the Intel I can understand, what version of Nvidia drivers are you on?

**Comment by aass0** [comment]
nvidia 526.86 and 31.0.101.2114 for intel

Whether using Intel or Nvidia, a crash occurs when using valkan.

setting ini
https://pastebin.com/raw/dt2Ffyad

**Comment by stenzek** [comment]
Intel Vulkan drivers are broken, either with DSB on newer GPUs, or barriers on older GPUs.

Going to say this is invalid, I see no crash either on NVIDIA nor AMD.

**Comment by aass0** [comment]
When using nvidia, I checked that there is no problem if I play a certain point again after resetting pcsx2.
Because of this, I think the problem is the intel driver or vga.

Thank you for your interest in solving the problem.
