### ISSUE TITLE
[BUG]: Simpsons Road Rage - Environment is black in DirectX11

### ISSUE THREAD

**Issue by BenoitAdam94** [PCSX2/pcsx2#7373]
### Describe the Bug

Environnement in "Evergreen Terrace" level is black (probably for other levels too)

![pcsx2_RwxJjQua2O](https://user-images.githubusercontent.com/45485644/201239506-99cf2826-c615-453e-9ddc-5286a25248ce.png)

### Reproduction Steps

Launch Game => Sunday Morning => Homer

D11 = Problem
OpenGL = No Problem 
D11 SW = No Problem
OpenGL SW = No Problem

### PCSX2 Revision

1.6

### Operating System

Windows 10 (64bit)

### CPU

i5-3570

### GPU

AMD ATI R200 Series

**Comment by refractionpcsx2** [comment]
the ATi R200 card is a directx 8 card, are you joking?

**Comment by stenzek** [comment]
I think we can just close this because it's probably not happening in 1.7, and given OP is using Win7, they won't be able to verify anyway.

If you post a GS dump and it occurs in 1.7 we can reopen.

**Comment by BenoitAdam94** [comment]
> [refractionpcsx2](https://github.com/refractionpcsx2)
I meant R9 200 series, my bad.

**Comment by refractionpcsx2** [comment]
okay, can you provide a GS dump? You can make one by pressing Shift + F8 at the point where you see the problem, it'll make a  gsdx_########.gs file in the "snaps" folder, if you could zip it up and upload it.

However if it's a bug in 1.6, then you're kind of on your own as the newest builds are not compatible with windows 7.

**Comment by BenoitAdam94** [comment]
Okay it's done, see attachment.

Also it's not a specific bug for my card or Win7, see "Countchokula" update on the Wiki, he uses Windows 11, Nvidia and say the same thing : 
https://wiki.pcsx2.net/index.php/The_Simpsons_Road_Rage

[snaps_simpsons_road_rage.zip](https://github.com/PCSX2/pcsx2/files/9990192/snaps_simpsons_road_rage.zip)

**Comment by refractionpcsx2** [comment]
looks fine here, I suggest maybe updating your AMD drivers

![image](https://user-images.githubusercontent.com/6278726/201343371-1c563da8-5a7c-4569-a155-5213fda9681c.png)

**Comment by refractionpcsx2** [comment]
Okay so I went back and checked it on 1.6, it is broken

![image](https://user-images.githubusercontent.com/6278726/201343630-699109aa-537d-44af-b814-6f13e9eca5a9.png)


I suggest either you don't use DX 11, or you upgrade to Windows 10 so you can run the latest 1.7

**Comment by BenoitAdam94** [comment]
Where can 1.7 be downloaded ? I can't see any release !

**Comment by BenoitAdam94** [comment]
Yeah great.

I think it's time for a proper 1.7 release... already 2 years for PCSX 1.6...

**Comment by refractionpcsx2** [comment]
Thanks for your opinion :)

**Comment by RedDevilus** [comment]
> Yeah great.
> 
> I think it's time for a proper 1.7 release... already 2 years for PCSX 1.6...

This is not Dolphin where the odd numbers are proper releases. I understand that you want a proper stable but there are still tons of work to do. 

You can just as easily use the nightly/dev cycle without issue and just ignore the version number.

**Comment by BenoitAdam94** [comment]
You're welcome refractionpcsx2 ;)

> Red Devilus
I know the dev for Emulator is complicated, but nowadays we live in a very instant world. Altough 1.7 seems a major changement version, it may be time to get out from it's shell.


For most users like me, it seems 1.6 has been released and no other versions is available since then : 

![Capture](https://user-images.githubusercontent.com/45485644/201351908-4f9c5231-7fa1-4254-840e-758f2ed1d4a1.JPG)

![aCapture](https://user-images.githubusercontent.com/45485644/201352320-5750039b-3dc9-4f08-a9f7-98c28b99671a.JPG)


Best move would be to provide an "alpha" or "beta" of 1.7 to show people that 1/ it exists 2/ main big differences that will happen .


Also, all these version for Windows... even me who has notions of SSE4/AVX and of Qt/wxWidget, I'm lost...

![psx2 versionsCapture](https://user-images.githubusercontent.com/45485644/201352687-e7ec35f3-3906-440e-b768-087bfe897058.JPG)

**Comment by RedDevilus** [comment]
https://pcsx2.net/downloads/

Less confusing here and there are talks about doing one last stable release and then doing monthly releases but there is no confirmation on that end.

I know it's annoying but it won't help anyone and not like 1.6 is unusable it's just outdated.
