### ISSUE TITLE
Error(?) message in console on PCSX2 startup: Reserving memory for recompilers... [wx] iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#738]
Is anyone else having this show up in the latest nightlies?

[wx] iCCP: known incorrect sRGB profile

**Comment by turtleli** [comment]
It's harmless. It's related to the wx3.0 transition and newer version of libpng used.

The fix would be either to strip the iCCP header from the offending PNG. Or perhaps replace the image.

**Comment by karasuhebi** [comment]
OK thanks for the info. :)
