### ISSUE TITLE
[BUG]: Qt version of PCSX2 doesn't work in fullscreen mode

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#7397]
### Describe the Bug

Switching to fullscreen mode (Qt version of PCSX2) results in black screen hanging and crashing to desktop some time later. Widget version works fine. (Geforce gtx 760; 470.141.03 driver)

[PCSX2.ini.zip](https://github.com/PCSX2/pcsx2/files/10025068/PCSX2.ini.zip)

### Reproduction Steps

1) Running bios, any game or big picture mode.
2) Switching to fullscreen mode.

### Expected Behavior

Games working fine with both window and fullscreen mode.

### PCSX2 Revision

v1.7.3563

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint Debian Edition 5

**Comment by stenzek** [comment]
Going to say this is likely an issue or incompatibility with your setup, since it doesn't happen for anyone else.

Without a backtrace I can't even guess what's going on.

**Comment by VladimirVSC** [comment]
> Going to say this is likely an issue or incompatibility with your setup, since it doesn't happen for anyone else.
> 
> Without a backtrace I can't even guess what's going on.

Alright, how to do this "backtrace"?
