### ISSUE TITLE
Onimusha 1 & 2 : objects and characters show through walls

### ISSUE THREAD

**Issue by Freestate2nd** [PCSX2/pcsx2#74]
1) Did the game ever work correctly : NO

2) What steps will reproduce the problem?
1. Simply playing the game

3) What exactly happens when you experience this issue (listing any console errors or screen output you receive)? You see objects and people through walls always

4) What version of PCSX2 are you using? On what operating system? 1.2.0 windows x64

**Comment by tapcio** [comment]
This issue is fixed in OpenGL mode with "Hardware Depth" enabled.
