### ISSUE TITLE
Hanuman:Boy warrior -  GSDX HW Regression

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#740]
Ground textures are all black. Broken in r1439

https://code.google.com/p/pcsx2/source/detail?r=1439

![hani](https://cloud.githubusercontent.com/assets/12788199/9093972/f919ad82-3bcc-11e5-9a7b-625a7a4dc8b8.jpg)

![han2](https://cloud.githubusercontent.com/assets/12788199/9093991/0f960e0c-3bcd-11e5-8d48-42636c1f72a2.jpg)

Gsdump : http://forums.pcsx2.net/attachment.php?aid=56164

**Comment by prafullpcsx2** [comment]
@gabest11 : Can you please have a look at this? List of changes in r1439 was huge and it was expected to have new bugs after that revision anyway. :P

**Comment by gabest11** [comment]
Yes, planing to look at it.

**Comment by prafullpcsx2** [comment]
@gabest11 : Did you had a look at this?

**Comment by gabest11** [comment]
Not yet.

**Comment by ADormant** [comment]
https://github.com/PCSX2/pcsx2/commit/f68f007f008be8bd6ae9aa8264b3b17a44e9ba69

**Comment by ssakash** [comment]
@prafullpcsx2 

You had mentioned on https://github.com/PCSX2/pcsx2/pull/1222#issuecomment-198985461 that the issue was fixed , so I assume this could be closed ?

**Comment by FlatOutPS2** [comment]
The GS dump is definitely fixed.
