### ISSUE TITLE
[BUG]: RetroAchievements: .hack//infection loads both core set and subset simultaneously.

### ISSUE THREAD

**Issue by CobaltZeroni** [PCSX2/pcsx2#7415]
### Describe the Bug

RetroAchievements user "Kiutgh" has discovered that PCSX2 nightly version 1.7.3589 is somehow loading both the normal achieve set and the "Book of 1000" subset for .hack//infection, displaying the achievements from both sets as a combined list.
The sets in question:
https://retroachievements.org/game/19021
https://retroachievements.org/game/20344
![Screenshot showing both sets loaded.](https://user-images.githubusercontent.com/111001608/202874724-8d4efd8f-62ea-4d45-8be9-0f808ae47d46.png) Note that the emulator is displaying the normal game name (no [Book of 1000] tag), but achievements from the subset are listed, and the total achievement count is the combined total of 83.

### Reproduction Steps

Attempt to load the regular set by launching .hack//infection's USA version, verified by Redump. Another user has attempted to reproduce the issue with this method, but the emulator behaved as normal and loaded only the regular set.
You may also want to try loading the subset. The patch to do so can be found here:
https://github.com/RetroAchievements/RAPatches/blob/main/PS2/Subset/20344-DotHackPart1-Infection-Subset-Bookof1000.zip

### Expected Behavior

Normally, the subset would have to be played separately, using a patched version of the game that changes just a byte or two to create a new RA game hash. Playing multiple sets at the same time is not something that RetroAchievements' current system is capable of.

### PCSX2 Revision

v1.7.3589

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Are you sure the hash is different? Check the PCSX2 log, it'll write the hash of the game out.

Note that you need to patch the executable itself to create a different hash.

**Comment by Noxillio** [comment]
Uncheck the "Test Unofficial Achievements" option in your Achievements settings.

These achievements are part of the core set in a testing manner because the subset is (or was at one point) planned to be merged.

**Comment by stenzek** [comment]
No longer relevant since we don't manage which achievements/sets are active ourselves anymore - it's handled by rcheevos/rc_client.
