### ISSUE TITLE
[BUG]: Oni [SLES 50177] Game hanging after the Intro

### ISSUE THREAD

**Issue by ByteRaper** [PCSX2/pcsx2#7417]
### Describe the Bug

Game hangs after the intro even with "Enable game fixes" ticked.

Solution is to create a cheatfile named 32629F36.pnach with the following content:

gametitle=Oni [SLES 50177] (G)
comment=patches by Nachbrenner
//skip "branch if copro 0 condition false"
patch=0,EE,001cef7c,word,00000000 // bc0f $001cef7c
//skip sceGsExecStoreImage
patch=0,EE,001d4454,word,00000000

### Reproduction Steps

Start the game with the current version of PCSX2.

### PCSX2 Revision

v1.7.3589

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 9 5950x

### GPU

RTX 3080 10G

**Comment by refractionpcsx2** [comment]
This is a bug with the new EE JIT which slipped through, that original patch is not the solution.
