### ISSUE TITLE
[BUG]: Burnout 3: Takedown, save-state creation crash the application after several times

### ISSUE THREAD

**Issue by Anas15gh** [PCSX2/pcsx2#7433]
### Describe the Bug

When I boot "Burnout 3: Takedown" and load state first time then begin saving states several times, and one of the "saving state" times will crashing the application.
I do not know if it only in "Burnout 3: Takedown" game or not I will try for other games.
I do not remember this problem came before the past several updates on save state feature.
Also, I recorded two videos for this problem. But I got one "emulog.txt".

YouTube Video: [PCSX2's save state is crashing, after several updates on save state feature. (Nightly v1.7.3603)](https://youtu.be/pqYMfJLOY98)
YouTube Video: [PCSX2's save state is crashing long video. (Nightly v1.7.3603)](https://youtu.be/dkb5nb_rLd0)

### Reproduction Steps

Boot a game then try "save state" several times, then the application will crash in one of "saving state" time.

### Expected Behavior

I think there is a variable getting out of range, maybe because something accumulation on some variable inside "save-state" feature or any variable related with it.

### PCSX2 Revision

v1.7.3603

### Operating System

Windows 10 (64bit)

### CPU

i7-6700

### GPU

GTX 1070 8GB

### GS Settings

![image](https://user-images.githubusercontent.com/97405670/203038300-6d1ddb52-51cf-419d-8f61-68bcbd6e14af.png)
![image](https://user-images.githubusercontent.com/97405670/203036936-e3567c19-f3a0-4239-a2a9-f1973967d364.png)
![image](https://user-images.githubusercontent.com/97405670/203037049-9c77bdf7-2306-45ad-85c3-8672e01f1fb7.png)
![image](https://user-images.githubusercontent.com/97405670/203037170-d600382a-a39d-45ec-aae0-e330201de673.png)
![image](https://user-images.githubusercontent.com/97405670/203037254-950a2b0c-fd09-45eb-8f1d-695b88b8e283.png)
![image](https://user-images.githubusercontent.com/97405670/203037305-b6cbba76-b424-40cf-a0e8-29c50c5c501a.png)
![image](https://user-images.githubusercontent.com/97405670/203037368-600191a1-f3d2-49cf-85ae-1aa3968f44bf.png)

### Logs & Dumps

[emulog1.txt](https://github.com/PCSX2/pcsx2/files/10055992/emulog1.txt)
[PCSX20.zip](https://github.com/PCSX2/pcsx2/files/10056001/PCSX20.zip)

**Comment by refractionpcsx2** [comment]
Will be fixed when the next update is available, but it will invalidate any savestates you have, so make sure you make in-game saves before upgrading.

**Comment by Anas15gh** [comment]
Thank you so much @refractionpcsx2
