### ISSUE TITLE
[Feature Request]: Screenshots in 16:9/Widescreen format and not in 4:3

### ISSUE THREAD

**Issue by madruded** [PCSX2/pcsx2#7435]
### Description

Native screenshots of games in 16:9/Widescreen and not the current method which is 4:3

### Reason

When clicking on the app screenshot icon, it takes it in 4:3 and not 16:9/Widescreen.

Even with the Widescreen option active, it would be great if the screenshots came in this format.

I'm using the Vulkan renderer.

### Examples

On the Duckstation PS1 emulator, 16:9 is already the default format for screenshots.

![SLUS-00821_2022-11-11_14-05-04](https://user-images.githubusercontent.com/61566730/203095711-0dec6bf2-f67d-47f8-8320-9b46c952ec0e.png)
![SLUS-01503_2022-09-11_11-25-28](https://user-images.githubusercontent.com/61566730/203096535-d71db8b3-4d49-4dde-9d97-f2d5a7663486.png)

**Comment by Mrlinkwii** [comment]
use , the "internal resolution  screenshot" option 
![image](https://user-images.githubusercontent.com/17685135/203097570-810f15f8-6675-419d-9f7f-ec227fd3199b.png)

**Comment by madruded** [comment]
> use , the "internal resolution screenshot" option ![image](https://user-images.githubusercontent.com/17685135/203097570-810f15f8-6675-419d-9f7f-ec227fd3199b.png)

It doesn't work, the problem persists...captures in 4:3

**Comment by JimScript** [comment]
Say, what resolution are your internal resolution screenshots? Because most widescreen options I see don't actually change the internal resolution, they just refit the camera/UI to a 16:9 shape to stretch over a 16:9 screen, it is still internally 4:3. Progressive Scan seems to change the resolution to be more 16:9 though, at least in my experience with Ratchet & Clank.

**Comment by Mrlinkwii** [comment]
can this be checked on master ?

**Comment by CookiePLMonster** [comment]
Unless this issue is now specific to this game, it's not the case anymore - all my screenshots done with the "Internal Resolution" options are 16:9.
