### ISSUE TITLE
too much was reverted

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#745]
The  commit 72b828ef0de764aeb35a213eb3067b7041ef19e7 did a big revert of code. But it seems that it drops a valid commit 5287de930bf34acc135e922681eb75b0ec7a87d4

It looks like a bad git command.

**Comment by mirhl** [comment]
You mentioned two times the same commit

**Comment by refractionpcsx2** [comment]
Yeah git hated me,  thought I'd sorted it out :(

**Comment by gregory38** [comment]
You just need to revert your revert commit and add back the math.h file. Good luck ;)

**Comment by micove** [comment]
This should revert the revert + add the file with 1 command. 
```
git cherry-pick 5287de9
```

I don't know if what was intended to be reverted was actually reverted or not.

**Comment by gregory38** [comment]
Well the purpose was to train Ref with GIT ;) If you give it the solution, it is too easy.

**Comment by refractionpcsx2** [comment]
I'd rather have a solution, I hate git,  I don't want to use it ;)

**Comment by micove** [comment]
I just wanted brownie points for my PR that he is assigned to. ;)

More realistically, fixing this will break that PR for the 7th or so time therefore I want to get it over with so I can redo it again. I'm not sure how pistachioman has managed to keep fixing his PR for almost a year w/o going nuts.

**Comment by refractionpcsx2** [comment]
You are welcome to fix it for me :p

**Comment by micove** [comment]
There #753

**Comment by refractionpcsx2** [comment]
Thanks,  merged :)
