### ISSUE TITLE
[BUG]: The controller is disconnected when a strong rumble occurs

### ISSUE THREAD

**Issue by zerosetedn** [PCSX2/pcsx2#7459]
### Describe the Bug

When an in-game event occurs that triggers a strong rumble, the controller disconnects and the rumble does not stop. My controller is a DUALSHOCK 3. For now, I tested only two games: METAL GEAR SOLID 3 - SNAKER and METAL GEAR SOLID 3 - SUBSISTENCE. The error persists in both games.

### Reproduction Steps

Just play a game, using the original DUALSHOCK 3, and wait for some game event that triggers a strong rumble.

### Expected Behavior

The controller should remain connected and rumble should stop according to the game event.

### PCSX2 Revision

v.1.7.3626

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### Logs & Debbugs

I enabled all logging and debugging options, but did not generate any files in `~/.config/PCSX2/logs/`, just an `emulog.txt`, which did not register anything about my issue.

**Comment by F0bes** [comment]
Sounds a lot like a hardware issue. Can you test it with other applications? Can you test it wirelessly if you aren't already.

**Comment by zerosetedn** [comment]
> Sounds a lot like a hardware issue. Can you test it with other applications? Can you test it wirelessly if you aren't already.

I tested it on DuckStation and this bug did not occur. There's no way I can do this wirelessly, because my computer doesn't have Bluetooth and I don't have an dongle.
