### ISSUE TITLE
[BUG]: Upscaling glitch in Yu-gi-oh Duelists of the roses, Lines underneath font

### ISSUE THREAD

**Issue by Scalerize** [PCSX2/pcsx2#7460]
### Describe the Bug

I know that you are not accepting upscaling glitches, but im not asking you to find the workaround, i'm merely asking you to add the workaround to the gameindex if it's possible since  you can't expect me to add this workaround everytime i switch games, The Fix is to set both x and y Texture offsets to 4 in manual hacks to remove lines underneath the font, you can also fix this issue by setting texture filtering to forced excluding sprite. Please zoom in on the fonts to understand the issue

What it should like:
![loading4](https://user-images.githubusercontent.com/98698811/203870205-15ddb22f-0c53-4311-bbb4-45789e8c24b5.PNG)
, 
![4](https://user-images.githubusercontent.com/98698811/203870198-1728d3b0-5af6-4ce1-bbc5-7af3729c42ae.PNG)

What it looks like now, please zoom in on the font, also note that in the image it looks less worse than it actually is.

![loading0](https://user-images.githubusercontent.com/98698811/203870203-258b62ff-8e08-44d9-b29b-4026282b9577.PNG)

![0](https://user-images.githubusercontent.com/98698811/203870196-e983a579-54e0-428e-9376-ba7fe02de2a4.PNG)

### Reproduction Steps

-

### Expected Behavior

for the font not to have lines underneath it

### PCSX2 Revision

1.7.3582

### Operating System

Windows 11

### CPU

I7 7600

### GPU

GTX 1050 TI

### GS Settings

![Graphics settings](https://user-images.githubusercontent.com/98698811/203870356-7c62f9b4-b73a-4f1b-b924-5e128032e148.PNG)

**Comment by refractionpcsx2** [comment]
can you make a GS Dump on the screen with the lines under the fonts, we can see if we can add any fixes.

Beyond that we don't really support upscaling problems.

**Comment by Scalerize** [comment]
> can you make a GS Dump on the screen with the lines under the fonts, we can see if we can add any fixes.
> 
> Beyond that we don't really support upscaling problems.
Not fixed:
https://anonfiles.com/a0ufp4Jeyf/Yu-Gi-Oh_The_Duelists_of_the_Roses_NTSC-U_SLUS-20515_20221125013817_gs

Fixed:
https://anonfiles.com/Ueu4p7J1y9/Yu-Gi-Oh_The_Duelists_of_the_Roses_NTSC-U_SLUS-20515_20221125013953_gs

Thanks for taking this seriously :D

**Comment by refractionpcsx2** [comment]
Oh, it looks like we've already done what we can for this game.

Your best alternative to the preset ones is if you go in to the per game fixes (right click the game in your list and properties, or View->properties if the game is running), then go to Graphics, then the "Rendering" tab, tick "Manual hw fixes" then go to the Upscaling tab and set the "Texture Offsets" to X: 500 and Y: 400

Can't really do much more than that, so I hope it helps. if it's still a problem, please visit our Discord.

**Comment by Scalerize** [comment]
> Oh, it looks like we've already done what we can for this game.
> 
> Your best alternative to the preset ones is if you go in to the per game fixes (right click the game in your list and properties, or View->properties if the game is running), then go to Graphics, then the "Rendering" tab, tick "Manual hw fixes" then go to the Upscaling tab and set the "Texture Offsets" to X: 500 and Y: 400
> 
> Can't really do much more than that, so I hope it helps. if it's still a problem, please visit our Discord.

:( that's really sad, 
Anyways here's the fixed dump just in case since i already uploaded it 
https://anonfiles.com/Key9peJ7y5/Yu-Gi-Oh_The_Duelists_of_the_Roses_NTSC-U_SLUS-20515_20221125014920_gs

**Comment by refractionpcsx2** [comment]
You don't need to make a dump for each setting, the dump stores the instructions from the EE core, not the output, so settings don't really matter.

**Comment by Scalerize** [comment]
> You don't need to make a dump for each setting, the dump stores the instructions from the EE core, not the output, so settings don't really matter.

Understood :D, this is my first time contributing and fully understanding github so take it easy on me :D

**Comment by refractionpcsx2** [comment]
It's all good, just letting you know :) For stuff like this it's best discussing it in our #public-testing channel on Discord :)
