### ISSUE TITLE
[BUG]: Parappa the Rapper 2 - Top left of screen has wavey lines

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#7469]
### Describe the Bug

The top left 1/4th of the screen has wavey lines/ black rectangle graphical corruption.

### Reproduction Steps

Start the game, and enter a song. During the first level, it will be apparent.

### PCSX2 Revision

1.6.0

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by Mrlinkwii** [comment]
use 1.7 , its fixed their

**Comment by refractionpcsx2** [comment]
This is already fixed in newer versions, please upgrade.
