### ISSUE TITLE
[BUG]: Using the scroll wheel or arrow keys in the "Graphics" section of settings reveals hidden tabs

### ISSUE THREAD

**Issue by ANK-dev** [PCSX2/pcsx2#7472]
### Describe the Bug

When using the scroll wheel or arrow keys to switch between tabs in the "Graphics" section of the settings menu or per-game settings, it's possible to access hidden tabs such as "Hardware Fixes" and "Upscaling Fixes" even when the "Manual Hardware Renderer Fixes" checkbox is unchecked.

When checking the checkbox, it's still possible to access a third hidden tab with an off-screen name, which doesn't seem related to the previous two.

https://user-images.githubusercontent.com/40664661/204067380-cd165dac-cdb5-4bb8-bffc-2e29e79c881f.mp4

### Reproduction Steps

1. Open the global settings or per-game settings
2. Click on the "Graphics" section
3. Either:
   - Use the mouse wheel to switch between tabs
   - Use the **\<TAB\>** key to focus on the tab row and use the arrow keys to switch tabs
5. Go past the "Rendering" tab and the hidden tabs will be accessible.

### Expected Behavior

- The "Hardware Fixes" and "Upscaling Fixes" tabs should not be accessible unless the "Manual Hardware Render Fixes" checkbox is checked
- The third hidden tab whose name is off-screen should always be accessible.

### PCSX2 Revision

v1.7.3634

### Operating System

Windows 11

**Comment by RedDevilus** [comment]
Seems to be a regression from auto-hiding the tabs from Qt instead of having them grayed out visually before and skipping over them.
