### ISSUE TITLE
inefficient CLUT read

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#748]
I found that m_mem.m_clut.Read32 is executed a lots of time in the HW renderer. The valid bit is always cleared to false.

The clut is read 2 times by frame on the HW renderer with different setting.

Start of GSTextureCache::LookupSource
```		
GIFRegTEXA plainTEXA;
memset(&plainTEXA, 0, sizeof(GIFRegTEXA));

plainTEXA.AEM = 1;
plainTEXA.TA0 = 0;
plainTEXA.TA1 = 0x80;
m_renderer->m_mem.m_clut.Read32(TEX0, plainTEXA);
```

After the texture lookup in the rendererHW
```
if(GSLocalMemory::m_psm[context->TEX0.PSM].pal > 0)
{
	m_mem.m_clut.Read32(context->TEX0, env.TEXA);
}
```

Here a list of improvement
* It misses a ```memset(&plainTEXA, 0, sizeof(GIFRegTEXA))``` otherwise uninitialized data are compared
* First block could only be executed if psm.pal > 0
* Ultimately plainTEXA must be replaced with normal TEXA. and the 2nd clut read must be removed. I don't understand why we need a special TEXA here. Neither why we do a conversion in the GPU for palette?

**Comment by gregory38** [comment]
@sudonim1 @gabest11 if any of you have any info, feel free to share.

**Comment by gregory38** [comment]
Hum it seems 16 bits palette are alpha expanded with the function ```Expand16``` But why 24 bits palettes aren't alpha expanded too?

**Comment by gabest11** [comment]
https://code.google.com/p/pcsx2/source/detail?spec=svn5329&r=5329

**Comment by gabest11** [comment]
https://code.google.com/p/pcsx2/source/detail?spec=svn5309&r=5309

**Comment by gabest11** [comment]
I'm still not sure what the purpose of these changes were.

**Comment by gabest11** [comment]
We need to save those comments ASAP.

**Comment by gregory38** [comment]
Me too I don't understand the change. Do you know how work AEM on 24 bits for the SW renderer? I don't see any code to do it on GSClut.

**Comment by gabest11** [comment]
I don't think there is a palette format other than 16 and 32 bit.

**Comment by gregory38** [comment]
Oh yes you're right. I didn't think about this possibility!

**Comment by gabest11** [comment]
Saving the comments from googlecode. I have already backed up the svn dump before.

**Comment by gregory38** [comment]
@gigaherz did you do backup the google comment? Or did you only keep the log message in GIT?

**Comment by gregory38** [comment]
Hum I think I begin to understand the issue:
The clut will be converted to do the alpha expansion (Expand16)

It is potentially done during the upload of the texture (GSTextureCache::Source::Flush) through rtx function pointer.
```
(mem.*rtx)(off, r, buff, pitch, plainTEXA);
```

And finally it is done in the shader.
```
	for (int i = 0; i < 4; i++)
	{
#if ((PS_FMT & ~FMT_PAL) == FMT_24)
		c[i].a = ( (PS_AEM == 0) || any(bvec3(c[i].rgb))  ) ? TA.x : 0.0f;
#elif ((PS_FMT & ~FMT_PAL) == FMT_16)
		c[i].a = c[i].a >= 0.5 ? TA.y : ( (PS_AEM == 0) || any(bvec3(c[i].rgb)) ) ? TA.x : 0.0f;
#endif
	}
```

**Comment by gregory38** [comment]
Hum old code only do AE for pure 24/16 bits RGBA texture. However it seems GSLocalMemory will do it also. It really seems that shader doesn't need to do it.

**Comment by gregory38** [comment]
Ok. I get it. AE must be done if the texture was an old target and therefore CPU never has the opportunity to do the conversion.
However if the conversion is done on the CPU, we must check the content of TEXA to select a source texture in the cache.

Then I suspect that any fix of the old revision comes from the change of bilinear interpolation. Old code uses the HW unit (faster but less accurate), new code does the interpolation in shader (more often). The condition to select the bilinear interpolation is rather complex but it explains the rise of GPU load. As you might know, some game really requires an accurate interpolation factor.

**Comment by gigaherz** [comment]
All I did was convert the repository into Git, I decided not to do anything with wiki and issue tracker.

**Comment by gabest11** [comment]
I will create a nice wiki page for the comments

**Comment by gabest11** [comment]
That was a bit optimistic, I can't seem to upload 6mb text in a page.

**Comment by gigaherz** [comment]
Yeah, probably not the optimal way to import comments XD

**Comment by gabest11** [comment]
That's the most I could do.
http://wiki.pcsx2.net/index.php/PCSX2_Documentation/Google_Code_svn_repository_comments_archive

**Comment by ramapcsx2** [comment]
Thanks gabest, you rock!

**Comment by mirh** [comment]
Ehrm, not that I like necro stuff, but shouldn't somebody also save comments from the [playground repo](https://code.google.com/archive/p/pcsx2-playground/issues)?
