### ISSUE TITLE
Unable to use Windows 11 AutoHDR with DX11/DX12 renderers

### ISSUE THREAD

**Issue by shinobiz** [PCSX2/pcsx2#7489]
### Description

Hope to add support for Windows 11 AutoHDR in PCSX2-QT

### Reason

If I remember correctly, AutoHDR can be turned on when using the DX11 renderer in version 1.6.0. I hope that AutoHDR can be added to PCSX2-QT, which will result in a more gorgeous picture. Thanks!

### Examples

.......

**Comment by stenzek** [comment]
I thought the whole point of it being automatic is nothing is required on the application side?

We're not doing anything to specifically forbid it.

**Comment by shinobiz** [comment]
> I thought the whole point of it being automatic is nothing is required on the application side?
> 
> We're not doing anything to specifically forbid it.

That's weird, when you start the game with the DX11 or DX12 renderer in RetroArch, PPSSPP, Dolphin and other emulators, Windows 11 will have an AutoHDR pop-up prompt in the lower right corner of the screen, and the HDR picture will be enhanced. But PCSX-QT doesn't prompt and doesn't get HDR picture enhancement
