### ISSUE TITLE
[Feature Request]: OBS game capture option setting

### ISSUE THREAD

**Issue by Laezor** [PCSX2/pcsx2#7490]
### Description

A tick box that would enable this launch option **OBS_VKCAPTURE=1 %command%** for all games. 

OBS Linux Vulkan/OpenGL game capture 
https://github.com/nowrep/obs-vkcapture

### Reason

- Would make life easier to set this for all games instead of setting it individually plus have to use steam in order to set it right now.
- Be able to capture games automatically without setting a window capture.
- cant capture with game capture otherwise, have to set it via steam for every game.

### Examples

![example](https://user-images.githubusercontent.com/32393101/204143142-980e9834-6596-48d8-bcaa-689b3f8ffa64.png)

**Comment by refractionpcsx2** [comment]
Didn't even know this was a thing,  is it just because we don't go full screen that we act differently from games? very strange.

Alright we'll look in to it at some point possibly.

**Comment by stenzek** [comment]
Uh, what? PCSX2 has nothing to do with "launch options"...

**Comment by refractionpcsx2** [comment]
I think they mean it's an identifier that OBS picks up on for window capture, by default (unless you do separate window), trying to get OBS to behave on PCSX2 is... troublesome.

**Comment by stenzek** [comment]
Then use `-nogui`?

**Comment by refractionpcsx2** [comment]
I've not tried that to see if it's any better, but it still isn't automatic with the game capture, you have to select the window every time, I think the idea of this is if you have game capture selected in OBS, you don't have to mess about, it just auto captures.

**Comment by stenzek** [comment]
If their heuristic isn't picking up PCSX2, sounds like a "not us" problem.

**Comment by refractionpcsx2** [comment]
I honestly couldn't say how it works with OBS, if they do it heuristically like discord, or they're expecting something specific, I dunno. I did just take a quick look at their guide, and it looks like OBS basically has a "Capture any full screen application" setting, so it might be better to use that.

for the specific window, it might be better to enable the "Render to separate window" option, as that tends to be more reliable.

**Comment by Laezor** [comment]
Game capture auto picks up any game that is launched with this parameter 

![image](https://user-images.githubusercontent.com/32393101/204143820-06fb1649-c565-468f-b0d6-5fa337e76e6e.png)


![image](https://user-images.githubusercontent.com/32393101/204143865-22d3d9b5-bbed-4214-9868-ce79a85dd582.png)

![image](https://user-images.githubusercontent.com/32393101/204143930-df15c5fd-8a3c-400e-b840-6f378909afe5.png)

I know its not that important feature, but a life improvement one. No need to hurry for this.

**Comment by refractionpcsx2** [comment]
Sure but the launching point is too late on PCSX2, because you've already launched the application before the game is picked, unless you make every game run via commandline and use like -nogui and -fullscreen for every game you wanna launch.

So that probably won't work.  Can you try my suggestions above? I know render to separate window works pretty well in VK, but the full screen option make make game capture happy.

**Comment by Laezor** [comment]
> Sure but the launching point is too late on PCSX2, because you've already launched the application before the game is picked, unless you make every game run via commandline and use like -nogui and -fullscreen for every game you wanna launch.
> 
> So that probably won't work. Can you try my suggestions above? I know render to separate window works pretty well in VK, but the full screen option make make game capture happy.
> 
> Edit: -nogui -bigpicture -fullscreen might be the ultimate set of options, then you can add your OBS command :P

I can capture the game via steam even if i do not use -nogui -fullscreen -bigpicture. The only thing that needs to be set is the OBS_VKCAPTURE thing. It would be just easier if this option was within pcsx2.

![image](https://user-images.githubusercontent.com/32393101/204144364-09d3705b-eca4-4f54-b0e5-ca6d85c63880.png)

**Comment by refractionpcsx2** [comment]
I dunno, it feels like a bit of a hack, especially when we have a method there which you can also do by command line to never need to touch again and it just works.

Not sure how I feel about the idea if we already provide a way for it to capture like a game would, plus I need to see how simple it is to add, as that project you linked has a load of stuff along with it, I'm not sure if they're doing anything else or only throwing that commandline, and how cross platform is it? does linux need something diferent? what about MacOS? We need to answer these questoins also..  Maybe I'll look in to it in the future.

**Comment by Laezor** [comment]
Yeah understandable, its just a quality of life improvement. So I am trying to do the way you are suggesting via terminal.

`./pcsx2_bff03a27b4dff7da2278569eae029011.AppImage -nogui -fullscreen -bigpicture  OBS_VKCAPTURE=1 %command%
`

But I get this error. Probably I am doing something wrong or it cant work this way?

![image](https://user-images.githubusercontent.com/32393101/204145067-ca9b4533-7a55-4714-9192-5a93c6cb1bf7.png)

**Comment by refractionpcsx2** [comment]
oh yeah, sorry, yeah that's a command which needs putting to OBS not PCSX2, my bad, yeah that won't work at the moment. Sorry.

**Comment by Laezor** [comment]
No worries! Keep up the good work, the emulator rocks anyways!

**Comment by refractionpcsx2** [comment]
Thanks :)

**Comment by RainbowCookie32** [comment]
> So I am trying to do the way you are suggesting via terminal.
> 
> `./pcsx2_bff03a27b4dff7da2278569eae029011.AppImage -nogui -fullscreen -bigpicture OBS_VKCAPTURE=1 %command% `
> 
> But I get this error. Probably I am doing something wrong or it cant work this way?

What you are doing with `OBS_VKCAPTURE=1 %command%` on Steam is setting an environment variable, it's not an argument for the program.
The `%command%` part is Steam-specific as far as I know, so If you want to do it outside of it I think you should run `OBS_VKCAPTURE=1 ./pcsx2_bff03a27b4dff7da2278569eae029011.AppImage -nogui -fullscreen -bigpicture` instead.

**Comment by Laezor** [comment]
> > So I am trying to do the way you are suggesting via terminal.
> > `./pcsx2_bff03a27b4dff7da2278569eae029011.AppImage -nogui -fullscreen -bigpicture OBS_VKCAPTURE=1 %command% `
> > But I get this error. Probably I am doing something wrong or it cant work this way?
> 
> What you are doing with `OBS_VKCAPTURE=1 %command%` on Steam is setting an environment variable, it's not an argument for the program. The `%command%` part is Steam-specific as far as I know, so If you want to do it outside of it I think you should run `OBS_VKCAPTURE=1 ./pcsx2_bff03a27b4dff7da2278569eae029011.AppImage -nogui -fullscreen -bigpicture` instead.

You are absolutely right. It did work this way! I can also see the output this way in the terminal.

```
[obs-vkcapture] Init Vulkan 1.2.1
[obs-vkcapture] DRM format modifier support not available
GS Lookup CRC:00000000
[obs-vkcapture] Texture VK_FORMAT_B8G8R8A8_UNORM 1920x1080
[obs-vkcapture] ------------------ vulkan capture started ------------------
```

**Comment by stenzek** [comment]
So what does this have to do with pcsx2 again? Steam nor OBS command line parameters have anything to do with us, nor can we control it.

**Comment by refractionpcsx2** [comment]
yeah it doesn't sound like this is really an us thing, it sounds like it's all commandline stuff related directly to OBS, not sure what exactly we're supposed to do about that.

I'll close it for now, but I'll keep it in the back of my mind to look in to if I get bored :P
