### ISSUE TITLE
[BUG]: Impossible to save DMC NTSC-UC on latest pcsx2 sse 1.7.3641 with Vulkan

### ISSUE THREAD

**Issue by Retroland** [PCSX2/pcsx2#7491]
### Describe the Bug

Hello, in fact it's Impossible to save DMC NTSC-UC on latest pcsx2 sse 1.7.3641 with Vulkan but with Direct3D 12 it works but on the PAL release you can do it easily. You can savestate however, sorry for my poor English I'm not from an English country. 

### Reproduction Steps

Just play the game, save after the first mission, you can savestate but not save. 

### Expected Behavior

You should be able to save into the memory card but with Vulkan enabled you can't !

### PCSX2 Revision

1.7.3641

### Operating System

Windows 10 (64bit)

### CPU

i5-10600KF

### GPU

Radeon RX 6600 Powercolor

**Comment by Mrlinkwii** [comment]
what do you mean by  Vulkan stops you from saving?

**Comment by stenzek** [comment]
Renderer has nothing to do with saving.

**Comment by Retroland** [comment]
I know it's crazy but it is what it is.

**Comment by Mrlinkwii** [comment]
i suspect this may a user config issue :thinking:

**Comment by Retroland** [comment]
My memory card was full but it works on PAL release but I don't care it works with Direct3d 12, I play Ratchet and Clank games all the time and saves always work. Vulkan is sometimes slow I tought it would be the culprit since D3D12 is better but I have issues with some shadows in some games.

**Comment by refractionpcsx2** [comment]
Okay so user error.

**Comment by Jakey757** [comment]
ah dangit, i literally just finished checking this. nothing wrong with the game. 
![image](https://user-images.githubusercontent.com/49990481/204144442-1dce2591-fa4a-47b5-8d76-b5407b99076f.png)

**Comment by Retroland** [comment]
> ah dangit, i literally just finished checking this. nothing wrong with the game. ![image](https://user-images.githubusercontent.com/49990481/204144442-1dce2591-fa4a-47b5-8d76-b5407b99076f.png)

Can you tell me what is the problem on my pc and what must I do ?
