### ISSUE TITLE
[BUG]: GT4  Interior Object Outlines drawn over glass textures

### ISSUE THREAD

**Issue by keylimesoda** [PCSX2/pcsx2#7495]
### Describe the Bug

The edges of objects on the interior of vehicles (seats, rear-view mirrors, player helmets) appear to be drawn after the transparent glass texture.

For some reason it appears to be more visible in some cars than others.

Two very noticeable examples are:
Mercedes SL 500
Camaro SS 00

The issue does not repro in software mode.  It does repro on all hardware renderers, regardless of resolution scaling.

### Reproduction Steps

PCSX2 default settings
Enable anisotropic filtering (any level)

Load GT4

Select one of the cars from the above list.  Notice strange overdraw effect through the windows.

### Expected Behavior

The outlines of the interior objects should be filtered through the glass texture just like the rest of the interior.

### PCSX2 Revision

PCSX2 Nightly - v1.7.3651

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5800X

### GPU

Nvidia 4090

### GS Settings

Default

### Emulation Settings

Default

### GS Window Screenshots

Software mode (correct)
![image](https://user-images.githubusercontent.com/7773610/204227450-e240b956-2a35-4d01-b417-77ea23a20f3f.png)

Native resolution (less noticeable, but still present)
![image](https://user-images.githubusercontent.com/7773610/204227692-303742cc-9dc2-42d9-9d89-aca6ff425257.png)

High resolution (more obvious)
![image](https://user-images.githubusercontent.com/7773610/204227183-714cfc5d-08f3-412c-8f88-7a27b3e5932e.png)

Additional screenshot (very noticeable on Camaro)
![image](https://user-images.githubusercontent.com/7773610/204229674-8790e30e-d216-4ac8-b95f-36a3d6ff1416.png)

Front quarter angle showing full issue
![image](https://user-images.githubusercontent.com/7773610/204233760-7464b9c3-c264-44d7-972c-3b7de451679c.png)

**Comment by Mrlinkwii** [comment]
can you post a GSdump of the issue ? https://github.com/PCSX2/pcsx2/wiki/How-to-Create-a-GS-Dump

**Comment by keylimesoda** [comment]
![Gran Turismo 4_SCUS-97328_20221128133334](https://user-images.githubusercontent.com/7773610/204385736-dfd10b0f-1cd4-482d-babb-d1c6b4fc0ad9.png)

[Interior Object Outlines Drawn Over Glass bug (Gran Turismo 4_SCUS-97328).gs.zip](https://github.com/PCSX2/pcsx2/files/10107704/Interior.Object.Outlines.Drawn.Over.Glass.bug.Gran.Turismo.4_SCUS-97328.gs.zip)

**Comment by keylimesoda** [comment]
During further research, I found this only happens when anisotropic filtering is enabled.

I've updated the repro above.

**Comment by ps1freak26** [comment]
I've found that directx11 and directx12 cause outlines with anisotropic filtering enabled. OpenGL and vulkan don't have this issue.
