### ISSUE TITLE
[BUG]: Dragon quest 8 save state crash While streaming In discord

### ISSUE THREAD

**Issue by ozoomaroo** [PCSX2/pcsx2#7500]
### Describe the Bug

During combat Anytime you Save Via save state the game crashes.  Ive have had this happen Twice once while doing the monster arena and Now once again During a boss fight that I now have to Do over again. 

### Reproduction Steps

 begin streaming to a discord channel .enter Combat. try to save your game Via save states. If it doesn't work in standard combat Do it at a boss encounter in the main story progression Or inside the game monster arena. 

### Expected Behavior

The emulator to be able to save in mid-combat without crashing while streaming to discord.

### PCSX2 Revision

v1.7.3654

### Operating System

Windows 10 (64bit)

### CPU

I7-10700K

### GPU

RTX 3070

### Logs & Dumps

on 11-23, this is the crash log From the Monster arena. the following one on 11-28 is the crash log for the combat fight I just had.
[crashlogs.zip](https://github.com/PCSX2/pcsx2/files/10109796/crashlogs.zip)

**Comment by ozoomaroo** [comment]
After looking at the Issue myself This is a bug with PCSX2 interacting With discord while streaming on discord.

**Comment by ozoomaroo** [comment]
received a new Crash this time Outside of combat. it is included into the ZIp under 2022-11-29 
[crashlogs.zip](https://github.com/PCSX2/pcsx2/files/10118265/crashlogs.zip)

**Comment by labib2002** [comment]
2.0 can't release soon enough!

**Comment by Mrlinkwii** [comment]
can this be checked on  master?

**Comment by refractionpcsx2** [comment]
![image](https://user-images.githubusercontent.com/6278726/217232181-739de0fa-a151-434e-b563-4fe322aee9ca.png)
