### ISSUE TITLE
[BUG]: Assertion failed in SharedMemoryMappingArea when booting an ISO, crashes

### ISSUE THREAD

**Issue by gooseberry12** [PCSX2/pcsx2#7504]
### Describe the Bug

After updating to 1.7.3656, I received the following error when trying to start a game:

Assertion failed in function SharedMemoryMappingArea::Map
([drive:\path for PCSX2\common\Windows\WinHostSys.cpp:239):

Failed to left split placeholder for map

This error did not occur on the first time I booted a game, but on subsequent boots it happened every time I tried to boot an ISO. Any ISO. A clean installation of the PCSX2 on the same revision does not resolve the problem. Reverting to 1.7.3655, however, stopped the problem, so whatever's causing it might be localized to 3656. Updating from 3655 to 3656 using the internal updater immediately causes the problem to occur again.

I have attached the crash logs within this report.

[crash-2022-11-29-17-06-20-614.txt](https://github.com/PCSX2/pcsx2/files/10111932/crash-2022-11-29-17-06-20-614.txt)
[crash-2022-11-29-17-06-20-614.dmp.zip](https://github.com/PCSX2/pcsx2/files/10111936/crash-2022-11-29-17-06-20-614.dmp.zip)

### Reproduction Steps

While I know that the problem occurred on the second time I booted an ISO, I cannot reproduce the steps I took there because afterwards, even clean installs of PCSX2 will reliably show this error on the first boot of any ISO at all. This is reliably reproduced on my end.

### Expected Behavior

The expected behaviour is to be able to boot an ISO and go into a game.

### PCSX2 Revision

v1.7.3656

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
update your windows10 install and disable the deep behavioural Inspection in ESET if you use that anti-virus
