### ISSUE TITLE
[BUG]: Wild ARMs Alter Code F doesn't save state on exit

### ISSUE THREAD

**Issue by NineKain** [PCSX2/pcsx2#7507]
### Describe the Bug

Wild ARMs Alter Code F doesn't save state on exit, every other game I played does, manual state saving and loading works

### Reproduction Steps

Open game, close game, tick the box that saves on exit, reopen

### PCSX2 Revision

PCSX2 Nightly - v1.7.3659

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
can this be checked on master ?

**Comment by refractionpcsx2** [comment]
No reply in 4 months, probably user error and unticked the save on exit for savestates or something, that code is not game dependent (but can probably be turned off per-game.
