### ISSUE TITLE
[BUG]: Keyboard repeat rate reset upon application launch

### ISSUE THREAD

**Issue by Lenny003** [PCSX2/pcsx2#7514]
### Describe the Bug

Resets keyboard repeat rate on application start, usually to whatever Xorg's default is in my case I have it to "xset r rate 200 60"

### Reproduction Steps

Open pcsx2-qt on Arch Linux

### Expected Behavior

To not change my repeat rate

### PCSX2 Revision

PCSX2 Nightly - v1.7.3546

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by kenshen112** [comment]
And just to be sure. Does this occur in the AppImage? It's sorta the test platform for Linux related issues

**Comment by stenzek** [comment]
Going to say this is unlikely to have anything directly to do with PCSX2. We don't change the repeat rate at all. So it's either a package specific issue, or a Qt bug.

**Comment by Lenny003** [comment]
Downloaded the appimages from the site, doesnt seem to reset the repeat rate with eithor AVX or SSE appimages however, when I try to start an ISO I keep getting
`Unhandled page fault @ 0x00000000../common/Linux/LnxHostSys.cpp:97: assertion failed in function`
`void SysPageFaultSignalFilter(int, siginfo_t *, void *): Unhandled page fault` 
version is `PCSX2 Nightly - v1.7.3662`

**Comment by kenshen112** [comment]
It's probably not resetting since it's crashed

**Comment by Lenny003** [comment]
Yes, but its crashing after I try to start a game, in my case initially it was resetting it after I start the program.

**Comment by stenzek** [comment]
Without a backtrace we can't say what the issue is. But if this particular problem isn't happening with the AppImage, then it's definitely not a PCSX2 issue - speak to your packager.
