### ISSUE TITLE
[Feature Request]: Add two new "Map execution" and "Break on execution map" checkboxes to PCSX2 Debugger window interface

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7520]
### Description

These two new checkboxes can be useful to find codes that are executed but only when something happens like pressing Cross, Square, Triangle or Circle button on the DualShock gamepad controller for example or instance.

While the "Map execution" is checked the PC (Program Counter) register is logged and whenever the PC leaves a conditional branch instruction (like `beq`, `bne`, `beqz`, `bnez`, `beql`, `bnel` and etc) the value of the PC as 32-bit integer is both saved and added to any data structure that represents a set of items without repetitions like hash table binary search tree, like AVL tree or red black tree or trie for examples or instances.

While the "Break on execution map" is checked then whenever a new 32-bit integer is added to the set described above then the game is paused and the
<s>code that the PC reached</s>
last conditional branch instruction that the PC both visited and left before break/pause
is viewed in the debugger window of PCSX2.

At last the "Clear maps" button should make the set described above empty.

The set is always initially empty, stored and maintained in the heap memory of PCSX2.

### Reason

This can be very easy to find patches that change the executable and logic of any PS2 rom to be even more fun than how the PS2 developers originally made it, like making the character unable to jump or making a character without health invulnerable to enemy deadly attacks that instantly kill your character on hit and without this new feature, finding such patches can be very hard even with memory read and write breakpoints.

### Examples

For example or instance if the Cross button causes the playing character to jump upwards and I want to hack the PS2 rom to make the character unable to jump upwards at all and make the Cross button do nothing on press then tick the "Map execution" checkbox then continue playing for a while but make sure that the character doesn't jump upwards in this period.

At last tick the "Break on execution map" checkbox and then press the Cross button to jump upwards.

If the game pauses at the moment the "Break on execution map" checkbox is ticked then this means that you ticked the "Break on execution map" checkbox too early and you didn't play the PS2 rom enough time.

In this case untick the "Break on execution map" checkbox, click on the Resume button, continue playing the game more time without jumping upwards, tick again the "Break on execution map" checkbox and then press the Cross button to jump upwards.

Then the game should pause before the jump upwards code is executed and the conditional branch instruction that let the PC reach the jump upwards code is viewed in the debugger window of PCSX2 which prevented the PC from reaching the jump upwards code until the Cross button was pressed.

At last <s>find the conditional branch instruction that prevented the PC from reaching the jump upwards code until the Cross button was pressed and</s> assemble it to either unconditional branch instruction without changing the target address of course or a nop instruction and that's it!

Another option is to click on the "Step Out" button instead to view the `jal` or `jalr` instruction that invokes the function that causes your character to jump upwards and assemble that instruction to a `nop` instruction so the function that causes your character to jump upwards is no longer invoked and this means that thus as a result your character no longer jumps upwards even if you press the button that should do it.

Note that this sometimes may work and sometimes make your PS2 rom unstable, even unplayable or even cause PCSX2 to crash so this option is not so recommended, especially if the original instruction is `jalr` and not `jal` which is mainly used for function pointers and polymorphism and `jalr` may invoke more than one function. Assembling `jalr` to `nop` may cause all these functions not invoked and bring your PS2 rom to a very bad state as a result.

If you used the new feature properly and did everything right then the character can't jump and he or she doesn't jump even if the Cross button was pressed!

At last don't forget to untick the "Break on execution map" checkbox so the game won't pause again and also untick the "Map execution" checkbox to stop logging the PC that might degrade the performance of PCSX2 and consume more unused system memory.

At last don't forget to click on the "Clear maps" button to both free unused system memory and before trying to find a new code with this new feature!

Another example or instance is when you play a PS2 rom where the character that you control with your gamepad, dies after 1 hit and you as a hacker want to make this character invulnerable to all enemy attacks.

After beginning a new game, tick the "Map execution" checkbox, then with your gamepad move the character forward until you see an enemy on the screen or window.

Then stop moving forward and wait for the enemy to attack.

If the enemy launched a fire ball towards your character then wait for the fire ball to reach your character.

Before the fire ball kills your character quickly tick the "Break on execution map" checkbox.

When the fire ball hits your character the game pauses before your character dies by this enemy fire ball and the conditional branch instruction that let the PC to reach the code that kills your character is viewed in the debugger window of PCSX2.

At last assemble this instruction to either unconditional branch without changing the target address of course or nop, untick the "Break on execution map" checkbox so the game won't pause again, untick the "Map execution" checkbox so the PC is not logged, the performance of PCSX2 is not hurt and more unused system memory is consumed as a result, click on the "Clear maps" button to free unused system memory, right click the instruction that you assembled before and then click on the "Jump to Cursor" in the context menu that appears to bring back the PC to this address so your character doesn't die by the enemy fire ball after resuming the game, click on the Resume button to continue playing the PS2 rom and now your character is invincible to all enemy attacks! Enjoy playing the PS2 rom where your character dies after 1 hit with this cheat that you just made!

Another option is to click on the "Step Out" button to view the `jal` or `jalr` instruction that invokes the function that kills your character, then assemble it to a `nop` instruction so the function that kills your character is no longer invoked and this means that thus your character can no longer die by any enemy attacks as a result and then right click the `nop` instruction, that was either `jal` or `jalr`, to bring the context menu of PCSX2 debugger and there click on the "Jump to Cursor" option to get the PC outside of the function that kills your character so your character doesn't die by the enemy fire ball after resuming the game.

But as said earlier on the jumping upwards first example or instance assembling a `jal` or even `jalr` instruction to a `nop` instruction may sometimes make your cheat working, making your character invulnerable to all enemy attacks in this example or instance, and sometimes make the game unstable if not unplayable or even make PCSX2 crash especially if the instruction that you assembled to `nop` was `jalr` because `jalr` is mainly used for function pointers and polymorphism and `jalr` may invoke more than one function. Assembling `jalr` to `nop` may cause all these functions not invoked and bring your PS2 rom to a very bad state as a result.

At last don't forget to click on the "Clear maps" button both to free unused system memory and before finding a new code!

Note that the "Jump to Cursor" context menu option of PCSX2 debugger can be both prevented and unnecessary if the break is done before the PC leaves the conditional branch instruction and not after or even before the PC visits the conditional branch instruction but a prediction method has to be used to make it working, a prediction method that predicts where the PC will be after some steps without actually doing these steps at all.

A possible prediction method can be to automatically save the current state of the PS2 rom, then do some "Step Into" or "Step Over", remember the address of the instruction that the PC reached and then load the state that was saved on the beginning. If during the "Step Into" or "Step Over" the PC visited and left a conditional branch instruction and if the address that was remembered after leaving the conditional branch instruction and before the load state is not in the set of addresses that the PC was at then add it to the set and then break (pause the game) and show the conditional branch instruction that the PC is going to visit and leave.

I believe that this is not the best prediction method and there can be better prediction methods in terms of efficiency and system memory consumption.

Note that the prediction method is used only while both "Map execution" and "Break on execution map" are checked to not let the performance of PCSX2 to suffer too much time.

**Comment by stenzek** [comment]
Duplicate of #7453. The debugger is also getting re-done for Qt anyway.

**Comment by buruto** [comment]
> Duplicate of #7453. The debugger is also getting re-done for Qt anyway.

[RedDevilus](https://github.com/RedDevilus) asked me to submit feature requests in the Issues tab and not in the Discussions tab [here](https://github.com/PCSX2/pcsx2/discussions/7511) and I will quote what she said to me:

> Could you please keep the requests in issues and not make 3 of them in discussions, especially when WX debugger is on track to be purged and be replaced in Qt?

So I just did what she asked me to do and decided to migrate this feature request from the Discussions tab to the Issues tab.

Also the Issue tab version has better description, examples and explanation than the Discussion tab version.
