### ISSUE TITLE
[BUG]: (Qt) Unable to map Mouse Movements (but can map mouse buttons fine)

### ISSUE THREAD

**Issue by ArhumMK** [PCSX2/pcsx2#7521]
### Describe the Bug

Hello I'm trying to play a game with the right sticked mapped to the mouse. I have 'Mouse Mapping' enabled in Global Settings tab of the controller settings but It seems the program does not detect mouse movements to map the four directions of the Right Stick to the mouse. But I am able to map LMB and RMB just fine. This issue is present in the QtGUI builds exclusively.

And for some bizarre reason, when in-game, Only Mouse-right works as Right Stick-left even though it was not mapped to do so.

### Reproduction Steps

Enable Mouse Mapping then try to map mouse movements in the controller settings window. For eg: Select Right stick up and move your mouse upwards.

### Expected Behavior

Mouse movements should be able to mapped to the respective sticks as seen in prior versions. And the mouse-right issue shouldn't occur consequently.

### PCSX2 Revision

v1.7.3668

### Operating System

Windows 10 (64bit)

**Comment by ArhumMK** [comment]
Update on this bug, running PCSX2 as administrator lets me finally map mouse movements to the sticks which is strange. 
Duckstation, which uses a similar UI does not need this. Hope this helps!

**Comment by Mrlinkwii** [comment]
> P.S. How do you use Keyboard/Mouse controls on games that natively support it such as Dirge of Cerberus, on the old UI builds there was a seperate "USB Settings" tab but what bout QtGUI versions?


USB emulation  is not in QT yet

**Comment by XploreInfinity** [comment]
Hi!
This bug also seems to exist on Linux(Tested on the AppImage  v1.7.3858).

**Comment by stenzek** [comment]
Works fine here in both X11 and Wayland on Ubuntu 22.10/Plasma Desktop.

**Comment by XploreInfinity** [comment]
Oops. My bad.
It works fine. (I forgot to enable mouse mapping under global settings)

**Comment by DigitalMajestic** [comment]
Unable to reproduce on 1.7.4937.
