### ISSUE TITLE
[BUG]: Glitch in Arc the Lad - Twilight of the Spirits 

### ISSUE THREAD

**Issue by thecom** [PCSX2/pcsx2#7528]
### Describe the Bug

There's a weird overlay glitch in the intro of Arc the Lad. In software rendering everything looks fine and I think the background gets blurred instead.

### Reproduction Steps

Watch the intro.

### Expected Behavior

Blurred background like in software renderer and no visual glitch.

### PCSX2 Revision

v1.7.3669

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

AMD Ryzen 5 2600X Six-Core Processor

### GPU

Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)

### GS Settings

Sharp bilinear filtering

### Emulation Settings

Defaults

### GS Window Screenshots

![Arc the Lad - Twilight of the Spirits_SCUS-97231_20221204081629](https://user-images.githubusercontent.com/1708214/205479222-e705f6cf-8588-47ae-aa03-78b670efc28b.png)

### Logs & Dumps

[Arc the Lad - Twilight of the Spirits_SCUS-97231_20221204081629.gs.gz](https://github.com/PCSX2/pcsx2/files/10148051/Arc.the.Lad.-.Twilight.of.the.Spirits_SCUS-97231_20221204081629.gs.gz)

**Comment by Scalerize** [comment]
Looks very similar to Wrath of cortex's fixed glitch

**Comment by LeCharlatan** [comment]
Hi, the bug is showing here too, using version 1.7.3851 AVX2 Appimage.
Computer specs are Manjaro Linux, intel i5-8259U Graphics iGPU Iris Plus 655.
Plus note that happens on both NTSC-U and PAL-E version of the game.

**Comment by Mrlinkwii** [comment]
use software  mode

**Comment by Mrlinkwii** [comment]
still an isssue as of v1.7.4508

![image](https://github.com/PCSX2/pcsx2/assets/17685135/0db13706-02d9-4d19-9d84-a6d93805dfa3)

**Comment by seta-san** [comment]
still 1.7.4920

**Comment by piau9000** [comment]
Also happens in Arc the Lad: End of Darkness, as it seems they are using the same engine.
