### ISSUE TITLE
[BUG]: Kingdom Hearts geometry glitch

### ISSUE THREAD

**Issue by thecom** [PCSX2/pcsx2#7529]
### Describe the Bug

Geometry gets misrendered in both vulkan and software renderer.

### Reproduction Steps

Issue appears on first playable scene.

### Expected Behavior

No geometry misrenderings. Also black lines of the floor texture are thicker in software rendering than in vulkan, this is probably unrelated though.

### PCSX2 Revision

v1.7.3669

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

AMD Ryzen 5 2600X Six-Core Processor

### GPU

Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)

### GS Settings

Sharp bilinear filter

### Emulation Settings

Defaults

### GS Window Screenshots

![Kingdom Hearts_SLUS-20370_20221204081355](https://user-images.githubusercontent.com/1708214/205479435-806d6bcc-7d01-42ee-aa9a-0bc06567223b.png)

### Logs & Dumps

[Kingdom Hearts_SLUS-20370_20221204081355.gs.gz](https://github.com/PCSX2/pcsx2/files/10148056/Kingdom.Hearts_SLUS-20370_20221204081355.gs.gz)

**Comment by Mrlinkwii** [comment]
Can you please check the latest pcsx2 version,

**Comment by refractionpcsx2** [comment]
Cannot reproduce, neither can anybody else on the team. Assuming the user has a patch or some really dumb settings.

![image](https://user-images.githubusercontent.com/6278726/205497407-67193b4f-548c-4a9c-84f2-2af5764087c0.png)

**Comment by thecom** [comment]
You are right, I recompiled from git and issue is gone. I don't know what happened. Sorry for the noise.

**Comment by refractionpcsx2** [comment]
It's fine, better safe that sorry.

**Comment by Daniel6372** [comment]
I know it's not managed by you, but this seems to happen in the current Flatpak (Flathub) version of PCSX2 (v1.7.3695). I'm guessing that's what he used too. Will use the AppImage for the time being.
![Screenshot from 2022-12-11 21-17-09](https://user-images.githubusercontent.com/47946277/206927005-539561ab-ed1b-4f8e-a2f8-31c786699104.png)
