### ISSUE TITLE
[BUG]: The default value of "Bilinear Filtering" is wrong?

### ISSUE THREAD

**Issue by gary-ts** [PCSX2/pcsx2#7538]
### Describe the Bug

pcsx2-qt shows "Recommended Value: Bilinear (Sharp)", but the default value is "Bilinear (Smooth)".

[pcsx2/GS/GS.cpp
](https://github.com/PCSX2/pcsx2/blob/1cb10eb88917d9646bde82053ec056cde34e9ced/pcsx2/GS/GS.cpp)
```
	m_default_configuration["linear_present_mode"]                        = std::to_string(static_cast<s8>(GSPostBilinearMode::BilinearSmooth));
```

I tested [pcsx2-v1.7.3676-linux-AppImage-64bit-AVX2-Qt.AppImage](https://github.com/PCSX2/pcsx2/releases/download/v1.7.3676/pcsx2-v1.7.3676-linux-AppImage-64bit-AVX2-Qt.AppImage) on Arch Linux.

Thank you for the great work!

### Reproduction Steps

Run "pcsx2-v1.7.3676-linux-AppImage-64bit-AVX2-Qt.AppImage" and choose "Settings" -> "Graphics".
Check the value of "Bilinear Filtering:".

### Expected Behavior

The recommended value is "Bilinear (Sharp)", but the default value is "Bilinear (Smooth)".

### PCSX2 Revision

v1.7.3676

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

**Comment by refractionpcsx2** [comment]
Yep, my bad, I was going to make Sharp the default, then we decided against it, and I forgot to set the tooltip back.
