### ISSUE TITLE
[BUG]: Compilation failure since 1.7.3669

### ISSUE THREAD

**Issue by alucryd** [PCSX2/pcsx2#7543]
### Describe the Bug

Pcsx2 has stopped building since 1.7.3669 with multiple undefined references, see log: https://paste.xinu.at/k26mTd0wZCwFKjyz/
Disabling LTO didn't help.

### Reproduction Steps

* using the cmake command from the following build recipe: https://github.com/archlinux/svntogit-community/blob/packages/pcsx2/trunk/PKGBUILD
* observe link failures from the above logs

### PCSX2 Revision

v1.7.3669

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

**Comment by stenzek** [comment]
Sorry, we have nothing to do with arch packaging, speak to whomever maintains it.

CMake builds themselves are fine, our CI uses it to produce the appimage.

**Comment by kenshen112** [comment]
Though as the arch AUR packager. There's been no issue on my end either.

**Comment by kenshen112** [comment]
Yeah. That's most likely the case, https://github.com/PCSX2/pcsx2/commit/d47c9b0773a5c502e545f68dd0e7f59c3061bb2f
https://github.com/PCSX2/pcsx2/commit/a8382ceb5073e41e9d1958dcd3b8721d5510be29

**Comment by alucryd** [comment]
Unfortunately, despite the commit name it would seem that fix is not enough.

**Comment by alucryd** [comment]
I'm not sure how breaking a cmake flag and having control over a package are related, especially since our build recipes are open source and there for everyone to see and improve so control hardly means anything, but if the official stance is that breaking `DISABLE_ADVANCE_SIMD` is fine, a feature over which you have full control, might as well get rid of it altogether.

**Comment by refractionpcsx2** [comment]
I'm unclear what the flag is even there for anymore

> The reason advanced SIMD is set to be disabled is to support really old CPUs with only SSE2 support.

We don't support SSE2 anymore, haven't for ages, and all versions are now compiled in to one exe, so there's no need to set any flags to get different extensions out. 

I'm not a linux person so I don't know if there's another reason, but if that's the only one, maybe it shouldn't exist anymore.

**Comment by alucryd** [comment]
@refractionpcsx2 Thanks for the clarification. Traditionally most linux distros target vanilla x86_64 to support old CPUs indeed, there are a few outliers, and Arch is actually working on an additional repository supporting x86_64 v3 (ie AVX2), but the majority of packages are SSE2 max at best.

That flag seemed to imply SSE2 was supported, and it worked fine albeit with less performance. If it's officially no longer the case (which is perfectly fine and understandable), I'll just drop the package until we add support for x86_64-v3.

**Comment by TellowKrinkle** [comment]
Currently, using `-DDISABLE_ADVANCE_SIMD=ON` will compile a build that supports SSE4 with accelerated code for AVX and AVX2
Not using it will default to `-march=native` and compile for whatever CPU the build computer has

Can you test changing [this](https://github.com/PCSX2/pcsx2/blob/bdb1fd517b4c13e314813d06033fcd333a7a7a47/pcsx2/CMakeLists.txt#L1025) to `if (0)`?

**Comment by TellowKrinkle** [comment]
Never mind, got someone else to test, it looks like the issue only occurs with `ld`, so while you wait for a full fix, you can use `lld` to avoid the issue.

**Comment by helkaluin** [comment]
For what it's worth, the same issue popped up after the same set of commits 3 days ago over at the Ubuntu daily PPA. Strangely enough, it only occurs for the 20.04 and 22.04 build targets, and the 22.10 and later build targets were fine.

The issue was resolved after I changed the CMAKE flags to remove -DLTO_PCSX2_CORE=ON and add -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON.

If you want the full build logs of the failed compiles:

* 20.04: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily/+build/24903075/+files/buildlog_ubuntu-focal-amd64.pcsx2_3%3A1.7.0~git202212052135+202212060126~ubuntu20.04.1_BUILDING.txt.gz
* 22.04: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily/+build/24903074/+files/buildlog_ubuntu-jammy-amd64.pcsx2_3%3A1.7.0~git202212052135+202212060126~ubuntu22.04.1_BUILDING.txt.gz

**Comment by F0bes** [comment]
I can reproduce the issue with both `LD` and `LLD` when `CMAKE_INTERPRODECURAL_OPTIMIZATION=ON`
I was wrong when I thought LLD fixed the issue last night.
Looks like LTO on the core is failing (which makes sense looking at the linker errors), what I think you've effectively done is only LTO the frontend.

**Comment by j8r** [comment]
There is a similar issue for the Flatpak package.

**Comment by stenzek** [comment]
Imo the lto core option can be dropped, we don't use it in the CI. GCC LTO is way too slow anyway, clang is fine with lto'ing everything (the cmake interprocedural option).

Again, if you follow the build scripts from the CI, it'll work fine.

**Comment by kenshen112** [comment]
Decided to experiment with the SIMD option. I was able to get it to compile if I enabled Clang. Not GCC even with LDD enabled. Though Clang + LTO is incredibly deadly with the AUR, https://aur.archlinux.org/packages/pcsx2-git

```
[1/527] Linking C static library 3rdparty/rcheevos/librcheevos.a
FAILED: 3rdparty/rcheevos/librcheevos.a 
: && /usr/bin/cmake -E rm -f 3rdparty/rcheevos/librcheevos.a && "CMAKE_C_COMPILER_AR-NOTFOUND" cr 3rdparty/rcheevos/librcheevos.a [...]
/bin/sh: line 1: CMAKE_C_COMPILER_AR-NOTFOUND: command not found
[2/527] Linking CXX static library 3rdparty/discord-rpc/libdiscord-rpc.a
FAILED: 3rdparty/discord-rpc/libdiscord-rpc.a 
: && /usr/bin/cmake -E rm -f 3rdparty/discord-rpc/libdiscord-rpc.a && "CMAKE_CXX_COMPILER_AR-NOTFOUND" cr 3rdparty/discord-rpc/libdiscord-rpc.a [...]
/bin/sh: line 1: CMAKE_CXX_COMPILER_AR-NOTFOUND: command not found
ninja: build stopped: subcommand failed.
```

**Comment by stenzek** [comment]
Sounds like aur's problem then. The toolchain file the CI generates works fine everywhere else.

**Comment by F0bes** [comment]
The toolchain file does not work for me with clang or gcc. LTO is the offending flag.

**Comment by stenzek** [comment]
With LTO core or `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`?

**Comment by F0bes** [comment]
> With LTO core or `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`?

Either.


> Anyone want to test that PR and see if it helps for them?

Doing that right now.

**Comment by helkaluin** [comment]
> FWIW, I'd recommend following what the CI has to the letter anyway. LTO particularly (and to some extent the compiler/clang) has a significant impact on PCSX2, and having performance differences between different packages just creates even more of a headache for us. Especially when they go to us first for help, instead of the packager.

That was the reason I changed the cmake flags for the daily PPA to fit https://github.com/PCSX2/pcsx2/commit/a8382ceb5073e41e9d1958dcd3b8721d5510be29. I try to follow you guys' compilation decisions.

And this is a bit off-topic, but since you brought up the whole packaging headache thing --- when you guys deem the Qt port mature enough, it'll have a self-updater built-in, yes? By then I think it'll be prime time to close down the daily PPA (and the AUR and the Flatpak and other distro's own daily builds) since the official AppImage could satisfy the main draw of using those (i.e. easy updates).

**Comment by kenshen112** [comment]
It already has auto updates. But that's no reason to close a package. More options the better. Plus AppImage will always have issues with things like libpcap where a native package wouldn't

**Comment by stenzek** [comment]
Yes, the appimage auto updates itself since some time ago. Doesn't need to use external daemons, it's self contained.
