### ISSUE TITLE
[BUG]: NFS Underground 2 coloring inaccuracies on HW renderers

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#7549]
I noticed an odd offset tint on HW mode, so far I play around with different graphic settings and it seems to be related somehow to GS Blending emulation, but since ones could expect get better results as accuracy level goes up, actually is rather opposite, the bias color deviation gets worse as blending goes higher.

Here some examples

BA - Minimum
![image](https://user-images.githubusercontent.com/3447089/205953027-3a81a070-9a09-4683-8c40-cb44c4676a9d.png)

BA - Medium
![image](https://user-images.githubusercontent.com/3447089/205953254-a35648d0-1658-4ce0-9cc3-4bb07889fdaf.png)

BA - Maximum
![image](https://user-images.githubusercontent.com/3447089/205953460-fa682eb1-dcbe-4136-ac1e-890ee14af1d9.png)

### Reproduction Steps

Boot NFS UG2 - effect is shown while racing, any mode

### Expected Behavior

Here is how it renders using software for reference
![image](https://user-images.githubusercontent.com/3447089/205954283-82a14693-c226-4aee-8d09-a06150baee1c.png)

### PCSX2 Revision

PCSX2 Nightly - v1.7.3681

### Operating System

Windows 11

**Comment by JordanTheToaster** [comment]
It's known nothing fixes it currently.

**Comment by MarcoEstevez** [comment]
@stenzek amazing job, it works like a charm!

![image](https://user-images.githubusercontent.com/3447089/218803326-bd65a42a-51c8-419d-8880-2201bb9446df.png)
