### ISSUE TITLE
[Feature Request]: Per range clamping

### ISSUE THREAD

**Issue by Scalerize** [PCSX2/pcsx2#7552]
### Description

Title says it all, I'd like to request Per range clamping for VU1/VU0/COP2/FPU

### Reason

Some addresses are happy with Clamping, Others are not, Some adresses are happy with one clamping mode, others require a different clamping mode, Implementing this will increase the Emulator's Accuracy
#7241

### Examples

-

**Comment by refractionpcsx2** [comment]
Duplicate of #5188

**Comment by Scalerize** [comment]
#5188 Asks for Per-component rouning/clamping mode, i'm asking for per address per component Clamping/rounding mode, i can see how similar they are, but they are most definitely NOT the same thing.

**Comment by refractionpcsx2** [comment]
Now it does.
