### ISSUE TITLE
[BUG]: Kurogane no Houkou - Warship Gunner 2 The hull appears to be transparent.

### ISSUE THREAD

**Issue by ykazuma00** [PCSX2/pcsx2#7553]
### Describe the Bug

Kurogane no Houkou - Warship Gunner 2
Serial;SLPM-66321

In HW mode, the hull appears translucent and the shadow is transparent.
Or, perhaps there is a problem with the order in which the hull, shadow, and sea are displayed.

In addition, "Disable Depth Emulation" is checked in "Hardware Fixes". Otherwise, the background crane and horizon line will be displayed in front of the ship on the dock screen.
The problem with the hull and shadow display occurs regardless of whether "Disable Depth Emulation" is checked or unchecked.

### Reproduction Steps

Can be reproduced with normal game startup.

### Expected Behavior

Shadows appear normally as they did before version 1.6

### PCSX2 Revision

v1.7.3687

### Operating System

Windows 10 (64bit)

### CPU

I5 6600

### GPU

GTX 1060

### GS Settings

Settings Graphics
Rendering
 Internal Resolution:3x  Native(~1080p)
 Manual Hardware Renderer Fixes

Hardware Fixes
 Disable Depth Emulation

### Emulation Settings

default

### GS Window Screenshots

Below is a normal screen with normal Pcsx2 1.6 and above with 1.7.3687

Normal dock screen Pcsx2 1.6
![Ver1 6_dock](https://user-images.githubusercontent.com/119956501/206186021-5327ca02-aa13-4d6a-8324-a84455e44c5f.jpg)

Dock screen with unusual depiction of shadows Pcsx2 1.7.3687
![Ver1 7_Dock1](https://user-images.githubusercontent.com/119956501/206186089-5cb9deea-a696-4ea5-b518-c905a537d93a.jpg)
![Ver1 7_Dock2](https://user-images.githubusercontent.com/119956501/206186113-fa3f9327-964b-4b68-a79e-357bfbead98f.jpg)

Screen during normal mission Pcsx2 1.6
![Ver1 6_Mission](https://user-images.githubusercontent.com/119956501/206186156-65c47ab3-1f2f-41ba-a15b-4abb4993338c.jpg)

Screen during mission with unusual depiction of shadows Pcsx2 1.7.3687
![Ver1 7_Mission1](https://user-images.githubusercontent.com/119956501/206186263-99898039-92c8-4625-bde7-d714178cb57e.jpg)
![Ver1 7_Mission2](https://user-images.githubusercontent.com/119956501/206186276-1781f871-a491-4ee7-bf93-667778101e80.jpg)

**Comment by Mrlinkwii** [comment]
dose the issue happen at native? also , can you post a gs dump for me https://github.com/PCSX2/pcsx2/wiki/How-to-Create-a-GS-Dump ?

**Comment by ykazuma00** [comment]
Yes, it occurs in native.
Does not occur in SW mode.

[SLPM-66321_GS_DUMP.zip](https://github.com/PCSX2/pcsx2/files/10176737/SLPM-66321_GS_DUMP.zip)

I am using the QT version and could not figure out how to do the following at the URL you provided, so I am attaching a file that was output to the "snaps" folder by pressing "shift+F8".

For Qt Builds:
Debug > Save Single Frame GS Dump

native
![V1 7_native](https://user-images.githubusercontent.com/119956501/206199301-f78b988a-f378-48e0-b2e6-e300f942ec94.jpg)

SWmode
![V1 7_SWmode](https://user-images.githubusercontent.com/119956501/206199339-635179e1-67ff-424e-9ebe-b711ea4c392e.jpg)
