### ISSUE TITLE
[BUG]: Per-game EE Cycle Stealing Setting Not Applying

### ISSUE THREAD

**Issue by Bubblegum3390** [PCSX2/pcsx2#7557]
### Describe the Bug

When using the qt ui, if you adjust a game's per game setting for EE Cycle Skipping and then load the game, the global setting will be used instead.

### Reproduction Steps

With the global setting as Disabled, set a per game setting to a value other than Disabled and launch the game. The game will have no EE Cycle Skipping.

### PCSX2 Revision

v1.7.3687

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Does not happen on v1.7.3985.

![image](https://user-images.githubusercontent.com/80843560/215619979-9e382006-a7b7-411f-a192-f34f533dc165.png)

**Comment by refractionpcsx2** [comment]
You might have per game fixes disabled in the global settings, that'd do it

anyway, closing as user error. if you're still having trouble, please visit our discord or forums.
