### ISSUE TITLE
[BUG]: Clannad/Tomoyo After Transparent Portrait with HW graphics

### ISSUE THREAD

**Issue by msksk** [PCSX2/pcsx2#7579]
### Describe the Bug

In these games, character's body (layer) becomes transparent when hardware graphics are set, as you can see in attached samples.
- Clannad (NTSC-J)_SLPM-66302
![Clannad (NTSC-J)_SLPM-66302_20221213041530](https://user-images.githubusercontent.com/53204975/207137208-dac39202-8748-440e-8702-b2bbc13e369d.png)
![Clannad (NTSC-J)_SLPM-66302_20221213041511](https://user-images.githubusercontent.com/53204975/207137205-4f9f7436-a603-483c-b40f-b9ead542704b.png)
- Tomoyo After - It's Wonderful Life  CS Edition  (NTSC-J)_SLPM-66611
![Tomoyo After - It's Wonderful Life  CS Edition  (NTSC-J)_SLPM-66611_20221213035652](https://user-images.githubusercontent.com/53204975/207137130-30639e8c-aa87-43cf-b39f-95ea3fb5b091.png)
![Tomoyo After - It's Wonderful Life  CS Edition  (NTSC-J)_SLPM-66611_20221213035639](https://user-images.githubusercontent.com/53204975/207137139-37995b89-f2af-4429-b85c-ee5cb11efefc.png)

The bug does not occur on the software rendering.

### Reproduction Steps

Boot the game with HW rendering.

### Expected Behavior

Specific layer becomes transparent

### PCSX2 Revision

v1.7.3709

### Operating System

Windows 10 (64bit)

### CPU

i5

### GPU

gtx-1650

### GS Settings

Other than SW renderer.

### GS Window Screenshots

See Describe the Bug.

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/10211456/snaps.zip)

**Comment by refractionpcsx2** [comment]
Set your blending accuracy to high
