### ISSUE TITLE
Would IOCTL_STORAGE_CHECK_VERIFY2 speed up things?

### ISSUE THREAD

**Issue by mirhl** [PCSX2/pcsx2#758]
https://msdn.microsoft.com/en-us/library/aa363404%28v=vs.85%29.aspx#CommunityComments

Gigaherz said he's not sure whether
a) this would work because it's checking the device itself, and not the filesystem 
b) FILE_READ_ATTRIBUTES wouldn't be enough for using raw mode

**Comment by ramapcsx2** [comment]
You could investigate, if you want to know the impact :)

**Comment by mirhl** [comment]
Sorry, too stupid :see_no_evil:

**Comment by ramapcsx2** [comment]
Then I'll close this issue. :)
