### ISSUE TITLE
[BUG]: Emulation Settings - Speed Control section not displaying value from per-game settings after PCSX2 close/open

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#7582]
### Describe the Bug

Setting the Normal, Fast Forward or Slow Motion speeds in per-game settings is fully functional. However, the value displayed on the UI only persists through the lifecycle of the emulator, and will revert to defaults after closing and reopening PCSX2. The underlying value used is actually correct, and after closing and reopening PCSX2 you will still find the speeds working as they were modified. In other words, the UI is desynced with the actual gamesettings ini file.

### Reproduction Steps

Edit Normal Speed, Fast Forward Speed, or Slow Motion Speed in per-game settings. Check in-game to verify it works as modified.

Close and open PCSX2. Check the speeds again in per-game settings, and they will appear to be defaulted again. Check in-game to verify that the speeds are still working as modified.

### Expected Behavior

Speeds reported in per-game settings should match those which are stored in the ini file.

### PCSX2 Revision

v1.7.3712

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment]
Still an issue as of v1.7.3986.

**Comment by DigitalMajestic** [comment]
Still an issue on 1.7.4929.

**Comment by kamfretoz** [comment]
No longer an issue when checked on v1.7.5080.

**Comment by F0bes** [comment]
Can't reproduce either.
