### ISSUE TITLE
[Feature Request]: Selecting Audio Output Device

### ISSUE THREAD

**Issue by MikuAuahDark** [PCSX2/pcsx2#7585]
### Description

Hello, I'm using PCSX2 nightly 1.7.3714 (555b8efcadd14a1111dc1b784653ab67452c6624) with Qt backend. Emulation works great. Now I want to change the audio output device to my HDMI monitor, but I don't see the options in Audio Settings.

Having option to change output device allows users to change the sound output from the default device (e.g. laptop speakers) to other devices (e.g. HDMI monitor or 3.5mm speakers/headphones) without changing the default output device.

### Reason

Having option to change PCSX2 audio output devices makes switching sound outputs easier. For example, I can route the PCSX2 audio output to HDMI or external speakers while keeping system notification sound and music player at the internal laptop speaker (which is the default device).

### Examples

I use an FL Studio ASIO as an example. this is how their output device selection looks like.

![gambar](https://user-images.githubusercontent.com/7500438/207521733-9c2de4a6-1fe6-4e21-8a5e-563d1ad3fb32.png)

**Comment by stenzek** [comment]
Actually discussed this on discord only a couple of days ago - it's on my todo list, but it has to wait until after we remove WX completely. SPU2 config is a mess at the moment (any config changes completely reopen everything), and it's silly to clean that up, only to have to wrap it in grossness from the way the old WX inis are handled.
