### ISSUE TITLE
[BUG]: SLUS-21452 Valkyrie Profile 2 - Silmeria Crash after first cutsceen

### ISSUE THREAD

**Issue by nameless1** [PCSX2/pcsx2#7586]
### Describe the Bug

Game crashes after first cutsceen plays in a new game.

### Reproduction Steps

1.Start new game. 
2.Either skip cutsceen or watch it play.
3.Pcsx2 crashes

### Expected Behavior

Second cutsceen or gain control of character.

### PCSX2 Revision

v1.7.3712

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Kubuntu 22.10

### CPU

i9-11900H

### GPU

RTX-3070

### GS Settings

All setting are default

### Emulation Settings

All settings are default

**Comment by stenzek** [comment]
Works fine here, even tried on Linux. Please use the discord server for support, not the issue tracker.
