### ISSUE TITLE
[Feature Request]: (Qt) Reverse the pause menu type color for better readability

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#7588]
### Description

When using the dark theme of interface the type color of pause menu looks fine, but for the light theme it is almost unreadable, unless you point a cursor on the line. The revision is 1.7.3693. (Maybe it is just a bug, i don't know)

### Reason

Better text legibility for those using the light interface theme. It would be better to do the light type color the same as the dark type one.

Dark theme:

![Dark theme](https://user-images.githubusercontent.com/96921167/207599923-4cdd2a64-85e4-4152-bf18-ff3da728f7ac.png)

And this is for light theme...

![Light theme](https://user-images.githubusercontent.com/96921167/207599972-30ca35e0-4b1c-4855-8339-a51c0263e42b.png)

### Examples

The screenshots are above.

**Comment by DigitalMajestic** [comment]
No longer an issue, tested on 1.7.4929 (macOS 13).

**Comment by RedDevilus** [comment]
Likely fixed from this: https://github.com/PCSX2/pcsx2/pull/9257
