### ISSUE TITLE
[BUG]: Can't adjust per-game audio settings that use a slider

### ISSUE THREAD

**Issue by bslenul** [PCSX2/pcsx2#7600]
### Describe the Bug

Hey!

While trying to adjust the volume on a per-game basis I noticed that all the settings that use a slider in the "Audio" tab are locked and set to their minimum value (but it uses the global settings, like even if it shows 0% volume, I still have sounds in-game):

![image](https://user-images.githubusercontent.com/33353403/208235387-9a7ef49e-f71e-4f4f-bfb4-040c786753c0.png)

Clicking "Reset Defaults" properly resets the "Timestretch Settings" to 30/20/10, but the sliders are still locked.

Not sure if it's really a bug or if it's just the per-game sliders not being properly "hooked up" yet.

### Reproduction Steps

In the Qt version, right click a game > Properties then go to the "Audio" tab.

### PCSX2 Revision

1.7.3726

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
can you check #7742?

**Comment by bslenul** [comment]
Sure, so this is now the default settings when going to a game properties (+ the new "Target Latency" setting):

![image](https://user-images.githubusercontent.com/33353403/210134148-595311b8-c69d-4cdd-b4d1-136a04c0a926.png)

* Volume is now correct and the slider can be moved 👍 
* However, the volume value is written to the game .ini even if it matches global setting. So just opening a game properties will create an .ini for it, even if you don't change anything.
* All the other sliders are still at their minimal position.
* The "Output Latency" isn't locked anymore.
* The new "Target Latency" and the "Timestretch Settings" sliders are still locked.
