### ISSUE TITLE
[BUG]: Sly 2 and Sly 3 have missing audio when "Logitech USB Headset" emulation is used

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#7606]
### Describe the Bug

Sly 2 and Sly 3 are compatible with the Logitech USB Headset accessory, forcing you to be quiet in real life or else enemies will be drawn to your location.  When enabling "Logitech USB Headset" emulation, all voice lines that would normally play through the USB headset are completely silent, even when the output device is set to the same device as all the other audio uses.

### Reproduction Steps

- Enable "Logitech USB Headset" emulation
- Set Input Device to your microphone and Output Device to your PC's normal audio output
- Launch Sly 2 or Sly 3
- Pause the game and enable the USB Headset option

All audio that would play through the USB Headset's earphones will not play at all, but audio that normally plays through the display's speakers works fine.

### Expected Behavior

Audio that is supposed to be played from the USB Headset's headphones is output from the Output Device you set in the settings.

### PCSX2 Revision

v1.7.3729

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 SUPER

### Emulation Settings

USB Port 1 set to "Logitech USB Headset", input device is my microphone, output device is Default Output Device, selecting the specific output device was also tried

### GS Window Screenshots

Logitech USB Headset emulation enabled:
https://user-images.githubusercontent.com/58268914/208283114-5e39bc46-cd47-41cf-8950-63f7327a9e93.mp4

Logitech USB Headset emulation disabled:
https://user-images.githubusercontent.com/58268914/208283120-9b73efcf-bf0e-489d-be4b-b70d7702e173.mp4

Same game and USB Headset settings as the first video, but on PCSX2 1.6.0:
https://user-images.githubusercontent.com/58268914/208283127-7c2e2fc4-3743-4c22-a007-b80661fbf6b0.mp4

**Comment by Mrlinkwii** [comment]
Can this be checked on latest nightly :)

**Comment by SlyCooperReloadCoded** [comment]
I'm actually unable to download the latest update, it always fails to rename a controller file.  If I download it straight from GitHub, extract it, and replace files, the auto-updater still thinks I haven't updated.  I'd love to try this because I see the new commit but I can't and I don't know why.

**Comment by SlyCooperReloadCoded** [comment]
Tried it on latest nightly because I saw the commit, but unfortunately it's now even more broken - Sly 3 actually no longer detects that a headset is plugged in... at all.  Sly 2 is unaffected.

**Comment by SlyCooperReloadCoded** [comment]
Can confirm, works with Sly 2 and Sly 3.
