### ISSUE TITLE
[BUG]: Major framerate bug in Parappa The Rapper 2

### ISSUE THREAD

**Issue by ashfelix** [PCSX2/pcsx2#7608]
### Describe the Bug

In Parappa The Rapper 2, during some sections of the game, the visible framerate (not the reported framerate) appears to be reduced to half (or is significantly choppy) and breaks animations, but only for those sections. The reduction of framerate does not seem to affect player input.

I was not able to discover all areas of the game this occurs, but the bug can be consistently reproduced near the beginning of the game.

Expected behavior on real hardware:
https://www.youtube.com/watch?v=7lrFVPv0kVU

Behavior in PCSX2 1.7.3729 64-Bit AVX2 Qt:
https://youtu.be/ISVrF1oqKJI

----

As of right now, I am stuck on the 1.7.0-dev-159-g4f56db9f1 build, where the game runs flawlessly. We're trying to gain the ability to use the latest nightly build's more powerful texture dumping and replacement utility, but the game is not in its most playable state on the latest. Also, the latest build caps the minimum audio latency at 15ms, which makes the game much more challenging to play vs the 4ms minimum on the 1.7.0 build.

Please let me know if there's any more information you might need, or if I can help directly in some way. Thanks!

### Reproduction Steps

- Launch the game
- Enter "Stage 1"
- Enter "COOL Mode"
- Exit "COOL Mode" to return to normal FPS

### Expected Behavior

The game should remain at a visible (not reported) 60 fps with no slowed animations or animation breaks.

### PCSX2 Revision

v1.7.3729

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5600x (no overclock)

### GPU

NVIDIA Geforce RTX 3800

### GS Settings

**On the 1.7.0-dev build:**
![image](https://user-images.githubusercontent.com/35163546/208287350-7953211d-5b49-4e03-af9f-cc4beed25064.png)
![image](https://user-images.githubusercontent.com/35163546/208287367-33abfa44-02e5-4c38-ba1d-8518c198ea62.png)
![image](https://user-images.githubusercontent.com/35163546/208287380-0fab9bc1-4681-4724-a42f-dc37d5d3cf3a.png)
![image](https://user-images.githubusercontent.com/35163546/208287385-e0f0c886-4a23-4602-bf52-4498c835677c.png)

**On v1.7.3729:**
![image](https://user-images.githubusercontent.com/35163546/208287169-c4c8cba8-94a8-44a7-b415-8492ab65f51c.png)
![image](https://user-images.githubusercontent.com/35163546/208287171-87c3b2ea-9771-4f95-812d-9d4659c2d068.png)
![image](https://user-images.githubusercontent.com/35163546/208287175-5d6b847d-f10f-4543-b0ce-0773d5d90148.png)
![image](https://user-images.githubusercontent.com/35163546/208287179-f75cf72f-2412-487d-ba6b-c1770422f4f2.png)
![image](https://user-images.githubusercontent.com/35163546/208287185-f1cf4c3a-fc0c-4cf8-aea5-d7382b3b4b55.png)
![image](https://user-images.githubusercontent.com/35163546/208287187-efbebfb8-bcbc-442d-8150-3addc4f4de9b.png)

### Audio Settings (ref: RedDevilus)
**On the 1.7.0-dev build:**
![image](https://user-images.githubusercontent.com/35163546/208288407-c3a0909d-4e02-4ba6-857d-1d45581fddca.png)

**On v1.7.3729:**
![image](https://user-images.githubusercontent.com/35163546/208288427-e7944713-6350-4ce2-8eb9-4278ffbd0191.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/35163546/208287304-55cf3942-075a-4821-ab70-2876990f0782.png)

### GS Window Screenshots

Expected behavior on real hardware:
https://www.youtube.com/watch?v=7lrFVPv0kVU

Behavior in PCSX2 1.7.3729 64-Bit AVX2 Qt:
https://youtu.be/ISVrF1oqKJI

### Logs & Dumps

[gsdump.zip](https://github.com/PCSX2/pcsx2/files/10253370/gsdump.zip)

**Comment by lightningterror** [comment]
Do you have a build number where the issue started to occur?

**Comment by ashfelix** [comment]
> Do you have a build number where the issue started to occur?

I do not. I only just attempted to update from 1.7.0-dev just yesterday. I can confirm that the bug occurs on PCSX2 Nightly v1.7.2484 AVX2, though. I hope this helps.

**Comment by RedDevilus** [comment]
Best that you regression test where the previous build was fixed and the next build was broken exactly. As saying one build number could still mean the broken build can be lower or higher by hundreds if not more.

**Comment by ashfelix** [comment]
I was told that this was not a regression by Link. 

If you can confirm that this is indeed a regression, I can help find the build where this occurs.

**Comment by oddMLan** [comment]
I had to go digging in [Archive.org](https://web.archive.org/web/20211122181935/https://buildbot.orphis.net/pcsx2/index.php?m=fulllist) to bisect it

![image](https://user-images.githubusercontent.com/7278372/209841659-de2b6750-2428-434f-9cee-ff66e502612b.png)

I tracked it down to 03445d0b553fc5a8275e5df91fe004a5e10607a2 or 678829a5b2b8ca7a3e42d8edc9ab201bf00b0fe9
(couldn't find a download for the latter commit)

Build 713876918227367f8e8f336b84e5db1c4e3d52ee works same as HW (60 FPS)

@refractionpcsx2

**Comment by refractionpcsx2** [comment]
okay, then you make a choice, either you have the horrible black mess on the screen in the top left, of the framerate throttles down a bit, make your choice :P

Have we got recordings from hardware showing the full 60fps in places where PCSX2 does 30?

**Comment by oddMLan** [comment]
Uh, what? Build 713876918227367f8e8f336b84e5db1c4e3d52ee doesn't have the noodle issue, in fact it's the build that fixed it. The issue with the frame drop was introduced by one of those two latter commits.

**Comment by ashfelix** [comment]
hi @refractionpcsx2, there are example videos in the original post of 30 vs 60 on real hardware: 

Expected behavior on real hardware:
https://www.youtube.com/watch?v=7lrFVPv0kVU

Behavior in PCSX2 1.7.3729 64-Bit AVX2 Qt:
https://youtu.be/ISVrF1oqKJI

**Comment by refractionpcsx2** [comment]
I am a little confused, I just did that entire scenario, all lessons, and not once did it drop below 59.90.... :/

Is this an intermittent problem? Have you changed any of your settings? It's very difficult for me to fix unless I can reproduce it.

**Comment by oddMLan** [comment]
The FPS in the title bar still appear as 59.9-60.0 FPS, but you can notice a degradation of performance in the game. It's a bit disguised by deinterlacing interpolation. Set it to None and then the choppiness is clear as day.

**Comment by refractionpcsx2** [comment]
okay so I did work out a problem and I think I've mitigated it.  At least in my test scene (where he gets given noodle burgers), it now sticks at 59.94 not 29.97.

So if you can try #7715 once it's built, that'd be cool.

**Comment by oddMLan** [comment]
Gotcha. I will test when it's done building. In the meantime I prepared a savestate that will trigger the issue 100% of the time.
For NTSC-U.

[Parappa 2 Frame Drop Issue in Cool Mode.zip](https://github.com/PCSX2/pcsx2/files/10315620/Parappa.2.Frame.Drop.Issue.in.Cool.Mode.zip)

**Comment by refractionpcsx2** [comment]
Well it seems fine on my PR

![image](https://user-images.githubusercontent.com/6278726/209853541-e3ed0e2f-81f7-4584-9186-d214e5a2e58a.png)

**Comment by refractionpcsx2** [comment]
In other news, it has built, so you can get it from here: https://github.com/PCSX2/pcsx2/actions/runs/3795648141

**Comment by oddMLan** [comment]
Confirmed fixed from my end!

**Comment by refractionpcsx2** [comment]
excellent!

@ashfelix can you also confirm this?

**Comment by ashfelix** [comment]
@refractionpcsx2 **it seems to be fixed on that build!!** here's a video i recorded as a comparison (any slowdowns are due to the video and not the emulator): https://youtu.be/lVPrsc-K884

thank you for your patience in addressing this bug! it's sick how smoothly it was fixed; hugely appreciate your help here. 

little request before closing: could you tell Link to be a little bit less condescending to people who are encountering problems that could be potential bugs like this? i almost didn't report it or open an issue because he firmly communicated that this bug did not exist, even when multiple members of our community reaffirmed (and then confirmed) the expected behavior on a real hardware, where almost all of us are coming from. i would hate to see more cases like this fall through the cracks. i wanted to formally address it because it seems to be a hush-hush situation on the PCSX2 discord.

major props to the parappa community coming together on identifying this (especially @oddMLan in this thread) despite the roadblock!!!

**Comment by refractionpcsx2** [comment]
I will mention it, but it's quite frequent we get people saying the framerate is low, when it varies a lot on the PS2 as well, it's quite normal behaviour, just maybe not so much in this case, but it's usually the case, hence his confidence in the matter.  My apologies if that caused any tension.

Anyway I will link this to the PR so it closes when I merge it.

Thanks for testing :)
