### ISSUE TITLE
Shin Megami Tensei Lucifer's Call, half white background in some battles - OpenGL only

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#762]
PCSX2 version: 1.3.1 GIT 952-g84744d4

-PCSX2 options: Defaults

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, tested with native, scaling, opengl depth, all accurate options, accurate date, nothing affected the issue.
 OpenGL SW, D3D11 HW and SW all show it fine

-Description: When using GSdx OpenGL Hardware backend some battle backgrounds appear half white.
DX11 hardware and software and OpenGL software do not have the issue.

-How to replicate: Enter a battle at a certain area (only found one yet but I just started playing)

-Last known version to work: -

-PC specifications: CPU: Intel Core i5 2500K @ 4.3Ghz GPU: Gigabyte Geforce GTX660 Windforce OC 2 GB OS: Windows 7 SP1

GS dump: http://bositman.pcsx2.net/dumps/shin-megami-tensei-lucifers-call.rar

**Comment by bositman** [comment]
Bonus issue: Having accurate blending to anything higher than None, causes flickering lines on the battle menu options :P

**Comment by gregory38** [comment]
I didn't look at your dump yet but you could you retest it. I fix a blending regression in normal mode. And turtleli fixes an issue in accurate blending.

**Comment by bositman** [comment]
Nope, both issues persist even with the August 16 fixes

**Comment by gregory38** [comment]
Well then, today isn't a lucky day :p

**Comment by bositman** [comment]
Both issues still persist as of https://github.com/PCSX2/pcsx2/commit/5f78644bb6284f4ba438a7dcd7cfc32cd8339927 , posting pics of the second issue caused by accurate blend > none, check the command menu (bugged is with accurate blend higher than none, correct is with accurate blend none and/or SW mode)
![pcsx2 2015-10-20 23-38-06-53](https://cloud.githubusercontent.com/assets/1621174/10620492/0c03f4a0-7784-11e5-8ee3-237b3805b347.jpg)
![pcsx2 2015-10-20 23-38-14-60](https://cloud.githubusercontent.com/assets/1621174/10620491/0bfe7d40-7784-11e5-9aa0-e8ac5436baef.jpg)

**Comment by gregory38** [comment]
Could you check the PR? It must fix the accurate blending issue.

**Comment by bositman** [comment]
Indeed it fixes the bugged text. Don't have the time to do a regression test, someone else will have to do it. Half white background issue is unchanged

**Comment by gregory38** [comment]
Yeah. I was on it. I pushed a new version with a strange fix but it seems to work ^^

**Comment by gregory38** [comment]
@bositman could you check latest git and update the issue accordingly. Thanks

**Comment by bositman** [comment]
Tested on 1,4 RC, seems to be fixed good job :)
