### ISSUE TITLE
[BUG]: nogui argument doesn't seem to work on QT frontend

### ISSUE THREAD

**Issue by Lutzx** [PCSX2/pcsx2#7620]
### Describe the Bug

When I try to run PCSX2 (qt) in no gui mode I get this error:

"Unhandled page fault @ 0x00000008../common/Linux/LnxHostSys.cpp:97: assertion failed in function void SysPageFaultSignalFilter(int, siginfo_t *, void *): Unhandled page fault

Aborting application."

Interestingly enough, using batch mode works so I'm using that as a workaround.

### Reproduction Steps

./pcsx2-v1.7.3736-linux-AppImage-64bit-AVX2-Qt.AppImage -nogui "iso_location"

### Expected Behavior

Emulator would launch normally with no gui

### PCSX2 Revision

v.1.7.3736

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

OpenSUSE Tumbleweed

**Comment by RedDevilus** [comment]
nogui was replaced by batch (kinda similar) if you went from WX version to Qt version.

**Comment by RedDevilus** [comment]
Oh it seems it changed to -nogui instead of --nogui (the PCSX2 wiki seems to be wrong then)

**Comment by Lutzx** [comment]
Yeah I did use -nogui, it's on reproduction steps. But yeah -batch works for my use case so no issues there. Just thought about reporting since -help is a bit ambiguous about their difference:
  -batch: Enables batch mode (exits after shutting down).
  -nogui: Hides main window while running (implies batch mode).
