### ISSUE TITLE
[GameDB] Matrx - Path of Neo (SLUS-21273) needs Merge Sprite on for correct rendering

### ISSUE THREAD

**Issue by legend800** [PCSX2/pcsx2#7621]
### Describe the Bug

Just like the Half Pixel Offset (which fixes glossy/white textures), Merge Sprite is also needed to fix char/object haloing and over brightness. See pics. 

### Reproduction Steps

Go to any level and compare with / without Merge Sprite on

### Expected Behavior

Merge Sprite should be enabled in game db

### PCSX2 Revision

v1.7.3736

### Operating System

Windows 11

### CPU

AMD 5900x@ 4.8ghz

### GPU

GeForce GTX 3070

### GS Window Screenshots

Merge Sprite off:
![Merge sprite off](https://user-images.githubusercontent.com/20983844/208335677-3b65d4f9-4a96-494a-9dda-5364ffaa8785.png)

Merge Sprite on:
![merge sprite](https://user-images.githubusercontent.com/20983844/208335673-36655a8a-9459-4c6a-8d9b-acb2a2473427.png)

**Comment by lightningterror** [comment]
How does sw renderer look?

**Comment by legend800** [comment]
Here's some comparisons:

**Sewer:**
Merge Sprite Off:
![Merge sprite off sewer](https://user-images.githubusercontent.com/20983844/208341067-36a5ceaf-e791-46e7-9bc3-13828a3b108b.png)

Software:
![software sewer](https://user-images.githubusercontent.com/20983844/208341076-4dbd3d7a-ba20-4a19-85dc-7258a2a75534.png)

Merge Sprite On:
![merge sprite on sewer](https://user-images.githubusercontent.com/20983844/208341078-cfdfbe57-7d78-444d-9cc8-964277c0ea4d.png)

------------------

**Powers screen:** (you can see the haloing with merge sprite off + too bright)
Merge Sprite Off:
![merge off0](https://user-images.githubusercontent.com/20983844/208341227-40eff2cd-ccca-4155-a619-ed259dac1eb7.png)

Software:
![software0](https://user-images.githubusercontent.com/20983844/208341230-39aacd05-f048-4baa-9d28-1c1679918238.png)

Merge Sprite On:
![merge on0](https://user-images.githubusercontent.com/20983844/208341240-6238b6b9-5416-41f6-9e85-83e02c94bc0d.png)

-------------------

**Roof 1:** ( you can see some haloing on the sides of screen with merge sprite off, hard to capture the haloing on both sides of char))
Merge Sprite Off: 
![merge off1](https://user-images.githubusercontent.com/20983844/208341265-d0ad5135-71e6-41ef-b00f-57a7f540d333.png)

Software:
![software 1](https://user-images.githubusercontent.com/20983844/208341277-eb5556af-21c9-4e8f-909d-691d05e49671.png)

Merge Sprite On:
![merge on1](https://user-images.githubusercontent.com/20983844/208341281-ae972c84-0075-41c6-b363-9968c276130f.png)

--------------------

**Roof 2:**
Merge Sprite Off:
![mergeoff2](https://user-images.githubusercontent.com/20983844/208341315-387eb33a-7461-4ed2-b136-b55feaf0f44d.png)

Software:
![software2](https://user-images.githubusercontent.com/20983844/208341319-602c4d21-ff0c-46e4-81f3-d64839757c35.png)

Merge Sprite On:
![merge on2](https://user-images.githubusercontent.com/20983844/208341322-99ce054e-8d41-4bc5-86f9-ea98cc66ba96.png)

**Comment by lightningterror** [comment]
Merge sprite isn't the correct hw hack it needs, seems that it breaks the effect.

**Comment by legend800** [comment]
Which effect exactly? Any other settings to experiment with?
