### ISSUE TITLE
[BUG]: Cannot map kb/mouse to pad input

### ISSUE THREAD

**Issue by legend800** [PCSX2/pcsx2#7624]
### Describe the Bug

Despite being able to map kb/mouse input to ps2 pad in the menus, nothing works in game. Only input from my xinput controller will ever work. Used to work fine on non-qt versions (I just upgraded). 

![1](https://user-images.githubusercontent.com/20983844/208342799-324afb89-f5f6-4388-850f-ce9d5fc52350.png)

 Tried enabling/disabling all these settings. 
![2022-12-18 19_42_14-PCSX2 Controller Settings](https://user-images.githubusercontent.com/20983844/208343292-ea586e89-c977-4dfa-9536-756149d163ac.png)

### Reproduction Steps

Map kb or mouse input to pad and attempt to play game

### Expected Behavior

KB and Mouse can be mapped to input.

### PCSX2 Revision

v1.7.3736

### Operating System

Windows 11

### CPU

AMD 5900x@ 4.8ghz

### GPU

GeForce GTX 3070

**Comment by stenzek** [comment]
Sounds like a support issue. Works fine for everyone else - in fact keyboard mappings are the default configuration.
