### ISSUE TITLE
[BUG]: EyeToy - Play [PAL] (SCES_515.13) - No audio and broken capture window in Video Message

### ISSUE THREAD

**Issue by GitHub-Khi** [PCSX2/pcsx2#7626]
### Describe the Bug

In EyeToy - Play [PAL] (SCES_515.13) when you want to record video messages or load and watch a saved video message, you hear and see that no audio is recording and the capture screen is always broken. The recording device used for this game series was the official [camera](https://en.wikipedia.org/wiki/EyeToy).

### Reproduction Steps

1.) Start the game normally

2.) Hit Start in the opening screen to access the main menu (you can also use the controller to navigate)

3.) Move to Video Messaging and select it to enter the Messages menu

4.) Hit Record Message and then you can reproduce the bug

### Expected Behavior

The recorded audio must be there when a recorded message is playing and the capture window must be shown in the same way as in the rest of the game.

### PCSX2 Revision

v1.7.3738

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz

### GPU

NVIDIA GeForce RTX 2070

### GS Settings

1.) I use Skip MPEG Hack (Skips Videos/FMVs) to skip the introduction video, which you can not skip with the controller - all the rest is disabled
![2](https://user-images.githubusercontent.com/96371271/208369100-84d44bb6-9c8e-470e-a6a0-24c2521420bd.png)

2.) ![3a](https://user-images.githubusercontent.com/96371271/208369113-22eac626-524c-4a68-934f-c919ed51a081.png)

3.) Auto Flush and Mipmapping are enabled in global settings - does not matter for this game if these two options are enabled or disabled![3b](https://user-images.githubusercontent.com/96371271/208369133-8d8ff0b1-5691-4a14-b453-0eefb11a49d6.png)

4.) ![3c](https://user-images.githubusercontent.com/96371271/208369165-3803fa10-31e7-43b0-af9c-30d6de153171.png)

5.) Use Blit Swap Chain is enabled in global settings - does not matter for this game if this option is enabled or disabled![3d](https://user-images.githubusercontent.com/96371271/208369178-22305f2c-d0f8-4ca7-a612-d16f5bc9ce32.png)

### Emulation Settings

1.)
![1](https://user-images.githubusercontent.com/96371271/208369069-7e16cffb-0305-4906-b24d-70657012e004.png)

2.) Frame Rate Control is set to default![5](https://user-images.githubusercontent.com/96371271/208369201-bde5b80f-3f57-4e01-b9e8-893f73194885.png)

3.) ![4](https://user-images.githubusercontent.com/96371271/208369192-7a4f36dd-d0a2-4f4e-989a-71dfb7183254.png)

4.) Little side question: Is it possible in the future to add certain special options, for example to flip the image horizontally, camera audio recording and so on?![6](https://user-images.githubusercontent.com/96371271/208369213-bacd93da-1bc5-4786-b7db-b480dfe3c307.png)

### GS Window Screenshots

No screenshots, but a video for download:
<a href="https://www.file-upload.net/download-15061435/2022-12-1906-36-04_EyeToy-Play.mp4.html">2022-12-1906-36-04_EyeToy-Play.mp4</a>

### Logs & Dumps

Emulog:
[emulog.txt](https://github.com/PCSX2/pcsx2/files/10257052/emulog.txt)

Single Frame GS-Dump:
<a href="https://www.file-upload.net/download-15061438/SingleFrameGS-Dump.rar.html">SingleFrameGS-Dump.rar</a>

Multi Frame GS-Dump:
<a href="https://www.file-upload.net/download-15061439/MultiFrameGS-Dump.rar.html">MultiFrameGS-Dump.rar</a>

I do not think the dumps will be of much use in this particular case. Let us see. :)

**Comment by seta-san** [comment]
Eyetoy streams video on mpeg2. I can’t help to think the skipmpeg hack would have a narrative effect on eyetoy games.

**Comment by refractionpcsx2** [comment]
It probably would. Can you turn that hack off and try again please?

**Comment by GitHub-Khi** [comment]
I have tested it, respectively tested all possible settings before creating this bug report. That means: Even deactivated this graphical bug unfortunately persists. I just hope that the effort to find and fix the bug is not too big. Otherwise, if i can be of any assistance with certain information, i will try to get it to you as soon as possible. :)

**Comment by refractionpcsx2** [comment]
Do keep in mind, the drivers you can get for Win10 are *very* broken these days. It worked fine in Win7, but since 10 and 64bit, getting any of the eyetoy features to work is kind of a nightmare.

**Comment by GitHub-Khi** [comment]
In Windows 7 this problem does not exist and because of a missing or faulty driver in Windows 10 it does not work? Oh my, in other words, I need to look for a solution, right? Or is there another workaround for Windows 10 users? I once „installed” the camera with the appropriate driver on my system with a trick to see if it works as a normal webcam - and it works fine, even with sound, etc., but maybe this driver is not good for the emulator. Can i post the driver i used for my SLEH-00030 camera here to show you?

**Comment by refractionpcsx2** [comment]
I mean if the camera isn't working properly in windows, then it's never going to work in PCSX2, and that's not our place to fix, you will need to find a better driver, or buy a new camera.

If windows works fine however and all the audio/video works perfectly, then it can be considered a PCSX2 fault.

**Comment by GitHub-Khi** [comment]
Yes, on my system it works as expected very well and without problems. The funny thing is that it has no other graphical issues in the game with the emulator. But okay. The best thing to do for me is to wait and see how the emulation will still develop. :D

**Comment by seta-san** [comment]
Another issue to consider is that eyetoy emulation on windows relies on directshow to get video in the mpeg 2 format. The issue is that direct show is deprecated and being replaced by windows media foundation that doesn’t support mpeg2. Sooner or later it’ll be necessary to intercept high res mpeg4 videos and downscale them and convert them to mpeg2

**Comment by mirh** [comment]
Directshow [isn't](https://alax.info/blog/1632) deprecated, it's still [somewhat](https://learn.microsoft.com/en-us/windows-hardware/design/compatibility/whcp-specifications-policies) part of the mandatory Windows specification, and there is even [contention](https://alax.info/blog/1626) it could be considered a replacement at all. 
With this said, of course if games expect a very specific pixel format and/or resolution, the emulator should provide as much interoperability as possible. And this is something regardless of the multimedia framework, or even the OS.. what codecs are available is actually dependent on the "compression engine" the ships inside the hardware (and hopefully in the future you should be able to even use your [doorknob](https://www.esper.io/blog/android-14-adds-support-for-using-your-smartphone-as-a-webcam) as a camera).

> I mean if the camera isn't working properly in windows, then it's never going to work in PCSX2

To be fair, I was wondering if a pass-through mode (via libusb perhaps?) couldn't be possible. 
This way, the OS could be even on fire, but it would still be up to the original(?) PS2 `libeyetoy.a` driver to control the device.

**Comment by refractionpcsx2** [comment]
https://learn.microsoft.com/en-us/windows/win32/directshow/directshow-reference

`[The feature associated with this page, DirectShow, is a legacy feature. It has been superseded by MediaPlayer, IMFMediaEngine, and Audio/Video Capture in Media Foundation.  `

Sounds pretty deprecated to me.

**Comment by mirh** [comment]
https://learn.microsoft.com/en-us/windows/win32/medfound/audio-video-capture-in-media-foundation

`Microsoft Media Foundation supports audio and video capture. Video capture devices are supported through the UVC class driver and must be compatible with UVC 1.1.`

Eyetoy is older than even the first UVC spec, so there's not even a question here. 
(of course nothing is impossible if you are willing to write enough low-level drivers, but the fact still is the camera api depends on its software.. not the OS version)

*It is* true then that when it comes to general "media matters" MF is truly preferred (for instance, out of the box Windows only comes with a MF H264 decoder, and even when it comes to cameras it would be cool if that step could be hardware accelerated), but AFAICT camera access isn't one.
