### ISSUE TITLE
[Feature Request]: Language selector per game based on bios settings

### ISSUE THREAD

**Issue by Gomam0n-afk** [PCSX2/pcsx2#7634]
### Description

Some games select their language by using the bios' language settings, i think it would be nice to be able to override this setting in a case by case basis if wanted or needed

### Reason

- I have some games that i prefer playing in other languages than my main setting, and going to the bios to change it everytime is a bit annoying and could be faster.
- Some hacked discs/homebrew really dislike having their language set to anything but english and will show no text or crashes.

### Examples

I have none i could think of.

**Comment by refractionpcsx2** [comment]
okay but if you don't speak English, why would you get an English hack? doesn't make much sense.

Keep in mind, we don't support hacked roms, if they crash because they're poorly made, that's not for us to fix.

**Comment by Gomam0n-afk** [comment]
> okay but if you don't speak English, why would you get an English hack? doesn't make much sense.
> 
> Keep in mind, we don't support hacked roms, if they crash because they're poorly made, that's not for us to fix. But you can always keep a second copy of PCSX2 with a different setup (move your bios roms) with the language that does work.

I do speak english perfectly, it's just that some non english dubs were better than the english one (die hard vendetta is a good example), or for nostalgia's sake.
i just think selecting different bios settings per games might be a good thing to add.

**Comment by lightningterror** [comment]
This is very niche, closing as low priority, if someone wishes to implement it they are free to do so.
