### ISSUE TITLE
VP2 Graphics Glitch

### ISSUE THREAD

**Issue by gendouhydeist** [PCSX2/pcsx2#764]
Happens on this pull request #749
v1.3.1-938-g68de522 left side (basic accuracy)
v1.3.1-946-g6046d6c right side (high accuracy) (needs full BA to fix)

![image](https://cloud.githubusercontent.com/assets/3938139/9283737/f44a8b5c-42e6-11e5-92f5-1cae6a662f82.png)

v1.3.1-946-g6046d6c (basic accuracy)
![image](https://cloud.githubusercontent.com/assets/3938139/9283599/04fdbb96-42e6-11e5-9f1b-122655ef221c.png)

v1.3.1-938-g68de522 (basic accuracy)
and yeah the forest graphic glitch is almost fix
![2](https://cloud.githubusercontent.com/assets/3938139/9283470/3b6f4d08-42e5-11e5-9304-169e93d7f177.png)

**Comment by gregory38** [comment]
Could you post me a gs dump of the forest.

**Comment by gendouhydeist** [comment]
I'm at work right now, will do after 7 hours.
and yeah the last screenshot is still slow as hell I'm getting only 15-30fps.
