### ISSUE TITLE
[BUG]: Outrun 2 SP/2006 C2C shadows are incorrect

### ISSUE THREAD

**Issue by RIKLAVIEGASINTRODUCTION** [PCSX2/pcsx2#7644]
### Describe the Bug

Shadows in hardware mode are there but they render incorrectly when compared to software mode even at maximum blending.
HW:
![Hardware](https://user-images.githubusercontent.com/92535412/208902881-697a8c60-de57-429d-ae14-0e71857603af.png)
SW:
![Software](https://user-images.githubusercontent.com/92535412/208902909-b1512c5a-eaa5-4225-abfa-ae2d5f2a613a.png)

### Reproduction Steps

Play any race.

### PCSX2 Revision

v1.7.3753

### Operating System

Windows 10 (64bit)

### CPU

2200G

### GPU

1050ti

### Logs & Dumps

[Outrun 2006 shadow bug.zip](https://github.com/PCSX2/pcsx2/files/10277582/Outrun.2006.shadow.bug.zip)

**Comment by Mrlinkwii** [comment]
can this be check on latest master :)

**Comment by JordanTheToaster** [comment]
Not an issue as of v1.7.4542.
