### ISSUE TITLE
[BUG][HW] Fatal Frame II - Broken Text

### ISSUE THREAD

**Issue by FahrentH8t** [PCSX2/pcsx2#7656]
### Describe the Bug

Fatal Frame II (US) [SLUS-20766] on PCSX2 Nightly - v1.7.3761

First Problem - In chapter 8, When you have to visit the boy's house, after cutscene you have to take a picture of a map in first floor, after taking picture, all texts in HW renders will go from white to purple and it's hard to figure out what is written in-game.

~~Second Problem - Unlike v1.7.3675 which I was playing on, v1.7.3761 (Latest) suffers from audio issues. If you close emulation or try to reset and change render, all in-game sounds go silent and game becomes mute and you get program error while closing PCSX2.
I'm not talking about characters voice stutter. This one seems new.~~

### Reproduction Steps

First Problem:

1. Go to boy's house in chapter 8.
2. Take a picture of map in first floor.
(Uploaded memory card so it should be easy to reproduce - It's the first save in-game)

~~Second Problem:~~

~~Try to reset emulation or change renders.~~

### Expected Behavior

To work.

### PCSX2 Revision

v1.7.3675 and v1.7.3761

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 2400G

### GPU

RX6600XT

### GS Settings

Default AF bro.

### Emulation Settings

Default.

### GS Window Screenshots

![2spxsa](https://user-images.githubusercontent.com/28109940/209177210-2e1ba2cd-8ba0-4b66-a55d-49e54340554b.jpg)

![adzcxed](https://user-images.githubusercontent.com/28109940/209177174-9858cd30-a603-4a03-8215-c18108dd6016.jpg)

### Logs & Dumps

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/10288497/emuLog.txt)

[dump.zip](https://github.com/PCSX2/pcsx2/files/10288520/dump.zip)
[memcards.zip](https://github.com/PCSX2/pcsx2/files/10288560/memcards.zip)

**Comment by FahrentH8t** [comment]
Ok so I went and checked and found the guilty version.
PCSX2 Nightly - v1.7.3601 (Text is fine)
PCSX2 Nightly - v1.7.3602 (Text is broken) - [#7414](https://github.com/PCSX2/pcsx2/pull/7414)

Still looking for second problem. I update this post when I found it.

**Comment by refractionpcsx2** [comment]
Bummer :( annoyingly the broken text is baked in to your GS dump, so we can't use that unfortunately, so the memcards will be useful, thanks.

**Comment by refractionpcsx2** [comment]
You said "all texts in all renders will go from white to purple and it's hard to figure out what is written in-game" but then pointed to a PR which only affects the hardware renderers.  Can you clarify if this happens in software?

**Comment by FahrentH8t** [comment]
After testing again. seems like SW is fine. My bad.

(It happened because I thought after taking picture (bug happening) I can change and see difference between renders. I didn't thought I've to start from scratch. I just changed renders after bug to see which one is fine and all had problem this way.)

**Comment by lightningterror** [comment]
I can't seem to reproduce the issue?
![image](https://user-images.githubusercontent.com/18107717/209347745-caedace8-2c7d-4679-91e9-f5dc77dc728e.png)

**Comment by FahrentH8t** [comment]
https://user-images.githubusercontent.com/28109940/209349685-e0b91221-daae-4885-983f-531923377404.mp4
![132132Untitled](https://user-images.githubusercontent.com/28109940/209349735-85c8b6d0-7593-47b0-92f9-c35da30d1fbf.png)

**Comment by kenshen112** [comment]
Another detail about "broken audio" if you're talking about their voices sounding scrambled or jumbled when they speak that's a normal issue for every pcsx2 build. It just, happens at random sometimes you can go through a playthrough and not have it, some times it'll happen everytime they speak.

**Comment by refractionpcsx2** [comment]
@FahrentH8t did you have anything ticked under the "hacks" tab by chance?

**Comment by FahrentH8t** [comment]
No sir. (Shouldn't emulog show this stuff?)
Btw, could this be an AMD only issue? I'm on 22.11.2 driver.
![image](https://user-images.githubusercontent.com/28109940/209432501-64c053ed-f7a6-4186-806f-0ba454ef2a41.png)

**Comment by FahrentH8t** [comment]
I'm not seeing 2nd problem after switching to QT.
Only first one remains.

**Comment by FahrentH8t** [comment]
First problem is now fixed by #7855.
All done. Closing.
