### ISSUE TITLE
[Feature Request]: Exit After Game Exits

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [PCSX2/pcsx2#7657]
### Description

Before I started using the nightly release there was an option to quit out of PCSX2 after the current game exists. This was useful for people such as myself who use Playnite to launch games and have scripts that automatically toggle Playnite's fullscreen when launching or exiting a game; however, currently I have to manually close the PCSX2 window after a game exits in order to have Playnite's fullscreen toggle back into focus. Additionally, though unrelated, could you make the "Open Pause Menu" hotkey toggle the pause menu instead of only opening it? Thank you for your time.

### Reason

This would make using PCSX2 easier for me because it would no longer require me to manually kill PCSX2 after a game exits.

### Examples

RPCS3 has a feature called "Exit RPCS3 when process finishes" that cause RPCS3 to exit after I quit my game. This was also available in an older version of PCSX2, though I do not know the name.

**Comment by refractionpcsx2** [comment]
add  `-nogui -bigpicture -fullscreen` to a shortcut to it.
