### ISSUE TITLE
[BUG]: PCSX2 crashes when trying to go into fullscreen on Linux with certain renders.

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#7665]
### Describe the Bug

If you set the emulator to OpenGl or Software and then try to open a game in full-screen the emulator crashes.
This also happens with OpenGL on version v1.7.3761 and it seems that this doesnt affect vulkan.

### Reproduction Steps

1. Open the Linux appimage.
2. Choose any game.
3. Go to settings < graphics.
4. Change to OpenGL or software render.
5. Press enter, double click the screen or go to "view < full screen" .

### Expected Behavior

Open any game while using OpenGL or software mode as render mode and 
then double click the screen, press enter or  go to "view then select Fullscreen, 
the emulator should go into fullscreen mode without crashing.

### PCSX2 Revision

v1.7.3768

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

EndeavourOS/Archlinux

**Comment by F0bes** [comment]
Can you test with the app-image we provide. Or are you already using it?

**Comment by AmyRoxwell** [comment]
I'm already using the app-image provided in PCSX2 website.
Just in caae, my pc hardware is:
1. RX 6600
2. Ryzen 5 5600

**Comment by F0bes** [comment]
Good to hear.
