### ISSUE TITLE
[BUG]: Broken GFX in Juiced [SLES-53044] when using HW mode

### ISSUE THREAD

**Issue by Florinel787** [PCSX2/pcsx2#7673]
### Describe the Bug

When racing during any of the daytime settings (morning, afternoon, evening), the game gets overly bright and the prebaked road shadows disappear.
![image](https://user-images.githubusercontent.com/20014896/209439626-41cd0a17-cae6-4439-b2fc-e50462949305.png)
Additionally, lens flare/glare is broken and it manifests by:
-missing effect on taillights and headlights
-missing street lights but their lens flare is still visible
![image](https://user-images.githubusercontent.com/20014896/209441109-a3820c94-fc2c-4287-8f02-4ffb669d12e0.png)
![image](https://user-images.githubusercontent.com/20014896/209441120-6612c1ff-0856-41c2-b903-e4d79a5147f4.png)
Weirdly enough, the overbright issue is temporarily fixed by restarting the race and is brought back the moment you pause and unpause in game. Additionally, the game renders correctly (sans lens flare) when the race is paused (the pause menu is transparent by design and allows you to see the road and cars).
![image](https://user-images.githubusercontent.com/20014896/209441291-a143918c-68f9-4b11-8671-96f7de17292d.png)

### Reproduction Steps

There are 3 ways of reproducing this bug:

1. Simply running the game with default emulation and GS settings.
2. Using HW rendering mode (Tested on Vulkan, DX11, DX12 and OpenGL): 
    - Not using any manual HW fixes.
    - Trying to use manual HW fixes:
       - Enabling Auto Flush fixes overbright.
       - Enabling Preload Frame Data fixes lens flare but brings back overbright.
       - Any upscaling setting above native brings back overbright as well if not already using Preload Frame Data.
3. Using SW rendering mode, set texture filtering to nearest.

Additional notes: This bug and these steps are also valid for the Steam Deck on SteamOS 3.3 and 3.4 as well as the Ryzen 7 4700U on Windows 10 64bit. I think it's safe to assume that this isssue isn't tied to any PC variables.

### Expected Behavior

Using the SW renderer with default settings, we can get the correct image.

Screenshot of a day time race, with the brakes pressed:
![image](https://user-images.githubusercontent.com/20014896/209440817-b9cf929a-4e09-44a4-a241-1c4e77f2abb8.png)

Screenshot of a night time race, with the brakes pressed and visible street lights:
![image](https://user-images.githubusercontent.com/20014896/209440998-792dab43-d6c7-4f8d-9408-473e01f5fb7f.png)
![image](https://user-images.githubusercontent.com/20014896/209441081-ee7c47ed-43bd-4815-9a37-d88a268b554f.png)

### PCSX2 Revision

Nightly v1.7.3777

### Operating System

Windows 10 (64bit)

### CPU

i5-7400

### GPU

RX 5600XT

### GS Settings

Auto Flush and Preload Frame Data (from Hardware Fixes) are the only settings I've been fiddling around with. 
![image](https://user-images.githubusercontent.com/20014896/209441501-d43e9834-bd2a-47f6-ae9e-e058b7b53d77.png)
![image](https://user-images.githubusercontent.com/20014896/209441508-ec28489a-cb83-4639-8f7a-5f53ca071a1b.png)

### GS Window Screenshots

Just stretching the image to 16:9 and disabling Anti-Blur
![image](https://user-images.githubusercontent.com/20014896/209441487-2e0254dd-2fa7-44e7-86eb-5df7c8005235.png)

**Comment by refractionpcsx2** [comment]
Can you provide a GS Dump from a point where the problem occurs please?

You can find this by going to Tools->Single Frame GS Dump, then zip up the two files it puts in your /snaps folder.

**Comment by Florinel787** [comment]
[Juiced GS Dump1.zip](https://github.com/PCSX2/pcsx2/files/10298912/Juiced.GS.Dump1.zip)
Dump taken with default emulation settings, on the first arcade race of the game, with the brakes on so it includes both overbright and lens flare issues

**Comment by refractionpcsx2** [comment]
Thanks for that.  Does the problem also appear in software mode? if not can you also take a GS Dump in software mode? It looks like it might be a GS Download/Readback issue if software is okay, which sucks, they are more of a pain to diagnose.

**Comment by Florinel787** [comment]
[juiced gs dump2.zip](https://github.com/PCSX2/pcsx2/files/10298939/juiced.gs.dump2.zip)

Yes, Software is indeed okay when using default settings
![image](https://user-images.githubusercontent.com/20014896/209445395-26c2a797-a228-4a5b-ada1-2818eaf869a5.png)

The SW dump was taken under the same circumstances (same race, brakes pressed, same exact other settings) as the previous one

**Comment by refractionpcsx2** [comment]
awesome :) Thanks!

**Comment by Florinel787** [comment]
Thank you, too, for your dedication to solve these issues. It's unfortunate that the diagnosis is going to be a pain. I hope it turns out to be an easy fix :D
Happy holidays!

**Comment by Florinel787** [comment]
I'm sorry if this is necroposting, but I've made an additional discovery related to the overbright bug.
It seems that, after restarting a race (which I've said in the initial post that it temporarily fixes the overbright issue), a lot of stress is lifted off the EE.
I've noticed this when I was experimenting around on my Steam Deck with default emulation and GS settings. As a side note, the Steam Deck suffers of EE starvation when the overbright bug is occurring and I was shocked when I saw the performance greatly improve after restarting the race. I was no longer needing to enable mild cycle skipping!

I'll be providing a GS HW dump of that same first arcade race _**after**_ having restarted it. I don't know why I haven't thought of providing a dump like this in the first place, my bad.

[juiced gs dump3.zip](https://github.com/PCSX2/pcsx2/files/10699263/juiced.gs.dump3.zip)

Since I'd last posted on this thread, I've upgraded to windows 11 on my desktop and steam os 3.4.2 on my steam deck, but I don't think there is any influence on that.

**Comment by Florinel787** [comment]
The gameDB fixes have improved gameplay A LOT and I can't thank you enough for your effort, but there are still some problems that need fixing.
Firstly, the daytime lens flare on taillights is still weak (in comparison to SW mode) or even missing.
Secondly, the weird performance issue is still present. (The one that is fixed by restarting the race but unfixed by pausing and unpausing the same race afterwards).
I'm attaching 4 dumps in the following order: lens flare issue, pre-restart performance, post-restart performance and post-unpause performance
[Juiced_SLES-53044_20230505184712.gs.zip](https://github.com/PCSX2/pcsx2/files/11407992/Juiced_SLES-53044_20230505184712.gs.zip)

[Juiced_SLES-53044_20230505184824.gs.zip](https://github.com/PCSX2/pcsx2/files/11407999/Juiced_SLES-53044_20230505184824.gs.zip)

[Juiced_SLES-53044_20230505184837.gs.zip](https://github.com/PCSX2/pcsx2/files/11408004/Juiced_SLES-53044_20230505184837.gs.zip)

[Juiced_SLES-53044_20230505184845.gs.zip](https://github.com/PCSX2/pcsx2/files/11408009/Juiced_SLES-53044_20230505184845.gs.zip)

**Comment by refractionpcsx2** [comment]
can you try it in native resolution to see if the lens flare and tail lights are ok?

Also can you make a dump for the tail lights?

**Comment by Florinel787** [comment]
this was all in native resolution...
