### ISSUE TITLE
[BUG]: Switching from ISO to ELF and back doesn't work

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#7681]
### Describe the Bug

Switching from ISO to ELF and back doesn't work

### Reproduction Steps

1. ISO to ELF
   - Drag and drop an ISO file over the window
   - Wait to start
   - Drag and drop an ELF file over the window
   - Press «Reset» button
![image](https://user-images.githubusercontent.com/2995486/209463515-3baba395-5190-4ce9-9494-cad62043e13e.png)
   - It doesn't work, swap disc option is engaged instead of reset
2. ELF to ISO
   - Drag and drop an ELF file over the window
   - Wait to start
   - Drag and drop an ISO file over the window
   - Press «Reset» button

### Expected Behavior

Reset button should reset the console and load the proper file

### PCSX2 Revision

v1.7.3783

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
can this be check on latest mater ?

**Comment by JordanTheToaster** [comment]
Still happens on v1.7.4560.
