### ISSUE TITLE
SSX 3 Red bars

### ISSUE THREAD

**Issue by pete3k** [PCSX2/pcsx2#769]
When you start a race any race. You notice on the screen rows of red bars going up and down. Very distracting.

**Comment by refractionpcsx2** [comment]
Are you still using unofficial builds as you were here: http://forums.pcsx2.net/Thread-SSX-3-red-lines ?

You never actually responded on there and can't say its not a support issue until options have been exhausted.

**Comment by pete3k** [comment]
I down loaded the latest version of pcsx2 from emucr 1.3.1-20150816181234(git). When setting it up I left the default settings. Here is are some images I was talking about

![pic 1](https://cloud.githubusercontent.com/assets/7675206/9320191/f6212aa4-4524-11e5-9928-fe16b355d989.png)

![pic 2](https://cloud.githubusercontent.com/assets/7675206/9320197/fb67dab2-4524-11e5-9a3b-93c70ed3302e.png)

I tried multiple graphic setting including D3D9 (Hardware) D3D11 Hardware and Open GL (Hardware)

Is there any other tests you want me do?

**Comment by pete3k** [comment]
I can also tell you that this was happen for over a couple of months

**Comment by pete3k** [comment]
The same issue also effects SSX On Tour

**Comment by refractionpcsx2** [comment]
and you have ticked Enable HW hacks, gone in to that section and set the CRC Level to Full yes?

**Comment by gregory38** [comment]
Disable all core hack (VU cycle stealing / MTVU too) and retry the GL renderer.

**Comment by pete3k** [comment]
Yes to the both of you... no changes!!!

**Comment by refractionpcsx2** [comment]
So the opengl renderer doesn't work either? Even with hw ogl depth ticked and the accurate blend option on full?

**Comment by tiagoplacido** [comment]
OS: linux mint 64-bit cpu: i7-2860qm gpu: gtx 560m
Settings: OGL renderer, depth ON, acurate blend  High, crc level PARTIAL
Status: no red bars game doesn't show graghical bugs

**Comment by refractionpcsx2** [comment]
What about with CRC level None, try lowering the other settings until you find what stops the red bars.

But im chalking this down as DX renderer, Which we kind of expected.

**Comment by tiagoplacido** [comment]
the game works with depth ON crc NONE blending NONE
it is a depth issue

**Comment by refractionpcsx2** [comment]
Yeah that defo won't work on DX then :P

**Comment by gregory38** [comment]
Hum, maybe we can move the hw depth support check box as "disable depth support" in user hack section.

**Comment by refractionpcsx2** [comment]
Is it worth even having if there are no drawbacks? Is it much of a suck on perfomrance?

**Comment by gregory38** [comment]
Prafull found a couple of issues without depth support. So far I manage to fix them but the option was useful (at least on the ini). I don't have any number on the performance but there is an impact for sure. Several depth conversion shader were in the top 5 on GoW. It really needs some perf numbers.

**Comment by refractionpcsx2** [comment]
Would be good to know the impact

**Comment by gregory38** [comment]
Yes. Besides depth isn't yet fully implemented. It misses a part to support the read of depth from the EE (nocturne). GPU->CPU transfers are slow by definition.

**Comment by refractionpcsx2** [comment]
Yeh, Fatal Frame and a few other games read back the buffer in download to the VIF.  if i recall this was the issue with the Slave to VU demo freezing, which i believe sudo fixed in software mode.

**Comment by karasuhebi** [comment]
@pete3k Did you try what @tiagoplacido suggested?

**Comment by pete3k** [comment]
Where are these settings.....

In the GSDX settings I only see crc hack level?

**Comment by karasuhebi** [comment]
Blending and Depth are settings exclusive to GSdx's OpenGL renderer, and only in pretty recent development builds. Once you update to a newer version, you should see this in your GSdx Plugin Settings window:
![2015-09-09 19_11_07-gsdx settings](https://cloud.githubusercontent.com/assets/6857825/9776471/9ed29e40-5726-11e5-9bfd-1fc77c10e4a5.png)

**Comment by blieque** [comment]
I'm experiencing the same issue. I recently upgraded a few things:

* Motherboard: Gigabyte 78LMT-USB3 to ASRock 970M Pro3
* Video Card: NVIDIA GT 610 to MSI R9 380 4 GB
* OS: Windows 7 64-bit to Windows 10 64-bit

The game worked fine, although a little slow with the GT 610, before, but I get red lines now. Using either Direct3D9 (I have DX9 installed for Mirror's Edge) or Direct3D11 renderers I get the issue, but with OpenGL I don't, granted Hardware Depth is enabled. If it isn't enabled, the lines show. Although the lines go, performance naturally takes a severe hit. If I can provide any more information of use, do say.

For reference:

![](https://cloud.githubusercontent.com/assets/5054638/13614569/169c7ff6-e569-11e5-9e30-2d9a3436520e.jpg)

**Comment by refractionpcsx2** [comment]
You will get issues with DX unless you put the CRC Hack level up to maximum which i think is DirectX Recommended.

**Comment by blieque** [comment]
Indeed, placing the CRC Hack Level to Aggressive does remove the lines. Thank-you!

**Comment by FlatOutPS2** [comment]
> You will get issues with DX unless you put the CRC Hack level up to maximum which i think is DirectX Recommended.

There's only one recommendation, Partial (OpenGL recommended), but no DX recommended. It defaults to Safest, which is the second highest setting.

**Comment by willkuer** [comment]
Full + skipdraw >= 3 or aggressive (which is probably just full + skipdraw) remove these issues on dx api's iirc. Using skipdraw you miss some effect though like the score overlay during/after jumps - again iirc. Obviously ogl is the api of choice here.

**Comment by refractionpcsx2** [comment]
> t defaults to Safest, which is the second highest setting.

Yes I think this is the DX recommended one, my apologies

**Comment by superjeepboy** [comment]
Hello,
I have found a solution to fix this glitch. Try switching D3D11 Hardware to Software mode, but when you switch back you will get the bars back. Hardware has the bars glitch, but best FPS, Or clean graphics with worst performance.

**Comment by willkuer** [comment]
Please read carefully what was posted in this thread. Probably your solution was already mentioned. If not: the forum (forums.pcsx2.net) is a better place to ask for support. If you request support it would be good to get all relevant information including your settings and everything that you tried so far.

**Comment by Tavy13** [comment]
> I have found a solution to fix this glitch. Try switching D3D11 Hardware to Software mode,

THIS GET RID OF THE RED BARS!!

**Comment by FlatOutPS2** [comment]
> THIS GET RID OF THE RED BARS!!

> Please read carefully what was posted in this thread.

Not sure if troll, or blind to anything but the second to last post.

**Comment by ssakash** [comment]
Closing the issue as it's resolved on OpenGL hardware mode.

**Comment by divinity76** [comment]
getting exactly the same problem with James Bond: Nightfire. should i open a separate issue?

**Comment by MrCK1** [comment]
@divinity76 Switch to the OpenGL renderer.

**Comment by lightningterror** [comment]
I disagree with closing issues just because they are fixed on only one render, adding tags should be enough, anyway this has been fixed on Direct3D as well.

**Comment by divinity76** [comment]
it only works on Software Renderer, right? hardware renderer is still unplayable? 
(i can't test now because my GTX1070 laptop is sent to repair, and i just got this shitty intel integrated graphics now :( )
