### ISSUE TITLE
[BUG]: Can't have different cover art for games that share the same serial number

### ISSUE THREAD

**Issue by Gabriel2Silva** [PCSX2/pcsx2#7690]
### Describe the Bug

Not sure if that's technically a bug, so I'm sorry if it's not, it's one of my first interactions on GitHub.

In Qt, I can't use different cover arts for different games with the same serial number.
I have two game files: `Monster Hunter 2 (Japan).chd` (original game dump) and `Monster Hunter 2 (Yuzucchi 5.0 translation).chd` (translated game). They're both SLPM-66280, only difference is one image is patched and the other one isn't.

When automatically downloading covers using the PCSX2 Cover Downloader with the "Use Serial File Names" box unticked, it saves the .jpg files using the game title. Only one `Monster Hunter 2.jpg` file is saved, so both games share the same cover art.

When downloading it with the "Use Serial File Names" box ticked, only one `SLPM-66280.jpg` is saved and once again both games share the same cover art.

Deleting this cover art .jpg file obviously deletes the cover art for both game entries.

When manually setting cover art for one of the two entries, the other one automatically gets the same cover art and there's no way to separate the two. Manually deleting the cover art file from the "covers" folder will once again delete the cover art for both entries.

### Reproduction Steps

1. In your Game List search directory, have two different game images that share the same serial number.
2. Click View > Game Grid.
3. Try to set two different cover art files for both game entries.

### Expected Behavior

The user should be able to set different cover art files for games that share the same serial number.

### PCSX2 Revision

v1.7.3786

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
You can rename the picture file to be the same name as the ISO if they share a serial, so if your ISO is called "my_game.iso" you call the picture "my_game.png" and it'll work.
