### ISSUE TITLE
[BUG]: GTForce has incorrect buttons: A/A/X/X instead of A/B/X/Y

### ISSUE THREAD

**Issue by Florin9doi** [PCSX2/pcsx2#7695]
### Describe the Bug

GTForce has incorrect buttons: A/A/X/X instead of A/B/X/Y:
![image](https://user-images.githubusercontent.com/2995486/209534573-c4bf4309-a682-4b38-8587-70c3f15b2fee.png)

### Reproduction Steps

Controllers > USB Port X > Wheel Device > GT Force

### PCSX2 Revision

v1.7.3791

### Operating System

Windows 11

**Comment by stenzek** [comment]
Button placement looks correct to me. See https://auctions.c.yimg.jp/images.auctions.yahoo.co.jp/image/dr000/auc0411/users/103a3fce570de55130014a8a756609c6570ebfe5/i-img778x583-1542802946o80nqn445129.jpg

**Comment by Florin9doi** [comment]
The issue is in the central image: 
![image](https://user-images.githubusercontent.com/2995486/209542053-286f5e5b-af30-4b78-809a-bbabeb9952c8.png)

**Comment by stenzek** [comment]
That would be one for @refractionpcsx2 then.

**Comment by refractionpcsx2** [comment]
I remember thinking that was weird at the time, either I'd hit my head or the reference image I had was incorrect.
