### ISSUE TITLE
[Feature Request]: Array value type

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7697]
### Description

Recent versions of PCSX2 have memory search feature including value type, which is currently called just and simply "Type", with options like 1 byte, 2 bytes, 4 bytes, 8 bytes, float, double and even string but unfortunately "Array" is not an option in this drop down list currently.

The "Array" value type option can be useful to find memory addresses of arrays in the game including executable MIPS assembly code which are always word arrays where each word is always 4 bytes in MIPS assembly.

Right now the "String" value type can be used for this purpose but only on arrays whose ascii values are printable characters (from 32 that is 0x20 and onwards) and cannot be used on any MIPS assembly code that contains at least one `nop` instruction(s), which are very common in MIPS assembly codes that contain either branch or jump instructions whose delay slot is usually `nop`, whose word is 0x00000000 because `nop` is 4 NUL characters according to the ascii table and NUL is not a printable character at all because NUL is 0 and 0<32 that is 0x0<0x20.

### Reason

There exist PlayStation 2 roms that allocate the executable MIPS assembly code of some systems randomly at runtime and their memory addresses change from time to time but not the MIPS assembly code itself.

So if the user used memory either read or write breakpoints to find the random memory address of some **piece of code** (**not** function) then the user can **manually** copy all the words of that **piece of code** (**not** function) to some text file (.txt) and when this **piece of code** (**not** function) is reallocated at different memory address then instead of find that **piece of code** (**not** function) again with memory either read or write breakpoints the user can just and simply do an array scan after copying all the words from the text file (.txt) into the "Value" TextBox in the "Memory Search" tab of the PCSX2 debugger and then select "Array" in the "Type" drop down list.

### Examples

In Kingdom Hearts re chain of memories when Sora enters into a moogle room all the executable MIPS assembly code that handle the functionality of the moogle shop are allocated on a random address.

After finding the memory address of the moogle points and then placing a read breakpoint there the user found the MIPS assembly code that checks whether or not Sora have enough moogle points to buy a card pack.

The user **manually** copy some words of that piece of code, which the user, **not** the emulator, decides or determines where this piece of code begins and where this piece of code ends, into some text file, let's say moogle.txt, and then the user "Assemble new instruction(s)" to make all the card packs free so Sora doesn't need enough moogle points to buy any card pack from the Moogle shop.

On the next moogle room the moogle shop executable MIPS assembly code has been reset and it has been reallocated on a different memory address and it is invoked by a `jalr` instruction obviously.

Instead of using again the same read breakpoint on the moogle points memory address to find the new memory address of the same piece of code, the user can copy all the words from the moogle.txt that the user made into the Value TextBox of the "Memory Search" tab and choose "Array" in the "Type" drop down list".

And after clicking on the "Search" button the user quickly found the new address of that piece of code and all what remains to do is again "Assemble new instruction(s)" to make all the card packs free so Sora can buy all of them even if he doesn't have even a single moogle point in his inventory. The user must make sure that the piece of code that the user **manually** copied to the text file is big enough so there won't be more than 1 result after clicking on the Search button in the "Memory Search" tab of the PCSX2 debugger.

The "Type" drop down list in the "Memory Search" tab of the PCSX2 debugger may be renamed to "Value Type" in the future of PCSX2 if #7696 will be accepted and the "Scan Type" drop down list will be added to the "Memory Search" tab of the PCSX2 debugger to avoid any confusions.

Also if #7696 will be implemented and added to PCSX2 in the future then I think that both "String" and "Array" value types should work only with "Exact value" scan type though with both "strcmp" and "memcmp" C standard functions you can theoretically make both "String" and "Array" value types work with another scan types like "Increased value" and "Decreased value" too though I don't think that this will be much useful for the user in practice.

According to stenzek comments and replies in #7523 finding functions on random addresses automatically in a generic way is impossible but the array scan feature is **not** used to find functions at all but any piece of code which is a much easier task.

Also please note that this is up to the user to **manually** decide or determine where the piece of code begins and where the piece of code ends. PCSX2 does **NOT** have to automatically make such decisions and determinations at all.

All what PCSX2 debugger has to do is to simply display the MIPS assembly code to the user and let the user to scroll down next MIPS instructions and scroll up previous MIPS instructions, go to any address, select multiple MIPS instructions, highlight all selected MIPS instructions and a context menu action or command or option or hotkey to copy them (all selected and highlighted MIPS instructions) to his or her clipboard which PCSX2 debugger already does.

What I meant to say in #7523 is that `addiu sp` may be a good start address for the piece of code (not function) and `jr ra` may be a good end address for the piece of code (not function) but not always in general of course.

Sorry that I was not clear enough and even confusing in #7523. My apologies.

If you still believe and think that the feature request is both redundant and superfluous then close this as "not planned" too but please at least let me know the reason and it should be convincing.

If you accept this feature request then please let me know about this and I would like to have it in the next stable release of PCSX2 after 1.6.0

Thank you so much that Qt finally has a debugger. I know that moving from wxWidgets to Qt was very difficult and not easy and well done that you managed to do this eventually.

If something anything is not understood or clear then don't hesitate to ask me about it.

**Comment by buruto** [comment]
I have done it by myself.

**Comment by RedDevilus** [comment]
??? Is this some weird ego trip that you did debugger contributions?

**Comment by buruto** [comment]
> ??? Is this some weird ego trip that you did debugger contributions?

What?

**Comment by RedDevilus** [comment]
Never mind, I thought you dropped the issue even if it didn't work. My aplogies.
