### ISSUE TITLE
[BUG]: Emulator Crashes "Possible incorrect Q value used in COP2. If the game is broken"

### ISSUE THREAD

**Issue by sa5mmm** [PCSX2/pcsx2#7706]
### Describe the Bug

Game does not load past start screen. Emulator loads the opening scene before game gets to start. When you press start program freezes. I normally have to end task via task manager. I have been getting error message:
"Possible incorrect Q value used in COP2. If the game is broken, please report to http://github.com/pcsx2/pcsx2."

Details:
Loading game from iso Jak and Daxter: The Precursor Legacy
USA Bios
Using Xbox S Series Controller (DX controller Enable XInput source)
Default Settings
Portable Mode

Bios and .iso game does not freeze on "Press Start" screen after press start and you can play part of the level.
Version it works:
- pcsx2-v1.6.0-windows-32bit-portable

Version it does not work:
- pcsx2-v1.7.3797-windows-64bit-SSE4-Qt
- pcsx2-v1.7.3797-windows-64bit-AVX2-Qt

### Reproduction Steps

Default settings Except for:
Enable Xinput

USA Bios
iso Jak and Daxter: The Precursor Legacy
Ran in portable mode

My computer:
Processor	Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor

Version it works:
- pcsx2-v1.6.0-windows-32bit-portable

Version it does not work:
- pcsx2-v1.7.3797-windows-64bit-SSE4-Qt
- pcsx2-v1.7.3797-windows-64bit-AVX2-Qt

1. Start emulator
2. Boot .iso
3. Game starts up (opening scene plays to press start screen)
4. press start on controller
5. Program freezes

The error message occurs before I press start, this is my first time using PCSX2 so I am not familiar with how the logs should look.

[1.7.379 Jak and Daxter SSE4.txt](https://github.com/PCSX2/pcsx2/files/10309509/1.7.379.Jak.and.Daxter.SSE4.txt)

### Expected Behavior

Game should not freeze after pressing start.
I am unsure if it is a settings issue, however same game and bios work in 1.6.0

### PCSX2 Revision

v1.7.3797

### Operating System

Windows 10 (64bit)

### CPU

i7-7700

### GPU

I'm not sure...

### GS Settings

I used default settings after you download portable
Except the following:

Enable XInput Input Source
Controller Port 1 Automatic mapping to SDL-0 (Xbox One controller for windows)
Tools
Enable system console
Enable File Logging
Enable Verbose Logging

**Comment by Mrlinkwii** [comment]
emulog?

**Comment by sa5mmm** [comment]
Sorry I renamed the emulog to [1.7.379 Jak and Daxter SSE4.txt](https://github.com/PCSX2/pcsx2/files/10309509/1.7.379.Jak.and.Daxter.SSE4.txt)

**Comment by stenzek** [comment]
Jak works fine here, please don't use the issue tracker for support - that's what the Discord is for.
