### ISSUE TITLE
[Feature Request]: QT Set Cover, allow for unique covers for titles that share title name

### ISSUE THREAD

**Issue by MattPonton** [PCSX2/pcsx2#7710]
### Description

Presently in the QT version you can set a cover for a game. However, even if you have two ISOs of different regions for the same game, and you can't set unique covers between the two. 

### Reason

I would like to set unique covers for each of my differing ISOs. Ideally it'd link it to the ps title code like SCPS-0123 instead of being linked to the currently uneditable Title name.

### Examples

An example is the title Dead or Alive 2. The US version differs both in game data and official cover art from both the PAL and JP versions. So I would like to set each of my three regions to their specific cover art. For the PAL version this is currently working fine as the title name is DOA2: Dead or Alive 2, but the US version and JP version come up with the same name (even though the JP version has a slightly different title, the database gives it the same name as the US). So setting a cover to one will set and override the other.

Another example is I have Rumble Roses which shares the name across all three regions but differs in the data for each and has alternate covers for each as well.

**Comment by Mrlinkwii** [comment]
" Ideally it'd link it to the ps title code like SCPS-0123 "

you already can

**Comment by Mrlinkwii** [comment]
![image](https://user-images.githubusercontent.com/17685135/209725268-6a97b681-f8a2-499b-a5cb-31c18f467ffc.png)

**Comment by MattPonton** [comment]
> " Ideally it'd link it to the ps title code like SCPS-0123 "
> 
> you already can

I'm sorry, I don't see how your screen shot shows how I can get a unique cover set per serial. Is that variable settable somewhere in one of the settings and I just missed it?

**Comment by refractionpcsx2** [comment]
I explain it here https://github.com/PCSX2/pcsx2/issues/7690#issuecomment-1364827553

**Comment by MattPonton** [comment]
> I explain it here [#7690 (comment)](https://github.com/PCSX2/pcsx2/issues/7690#issuecomment-1364827553)

Thank you, I didn't realize it was a feature already. Though I still believe it would be nice if the serial was the default.

**Comment by stenzek** [comment]
Then people would be complaining that they can't find the games they want in the covers directory. Can't make everyone happy.
