### ISSUE TITLE
Pipewire pcsx2 no audio when using pulse

### ISSUE THREAD

**Issue by AireagoirSteam** [PCSX2/pcsx2#7718]
### Describe the Bug

updated pcsx2 to current beta and had no sound when launching a game previous beta version worked with sound when using pipewire audio server.

there is a workaround to get audio by setting backend to alsa.
thought this bug should be reported in case anyone experiences it can and will attach any logs asked for

### Reproduction Steps

have pipewire installed 
open pcsx2 
attempt to run a game

### Expected Behavior

sound to work on either pulse or alsa as it did before

### PCSX2 Revision

pcsx2-v1.7.3805

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu studio 20.04

**Comment by stenzek** [comment]
Tried pipewire on Ubuntu 22.04, using the latest AppImage, works fine.

So likely a configuration or setup issue.

**Comment by AireagoirSteam** [comment]
Set to pulse?

**Comment by AireagoirSteam** [comment]
Since I was using the latest at the time with pipewire on ubuntu 20.04 have wire plumber install as recommended previous build worked.
No changes needed which was set to default.

Yet on default now have no sound so not sure what configuration changed do you think it could be with pipewire since I have sound using pulse on everything else except pcsx2

**Comment by stenzek** [comment]
pulse is the default, it has higher priority. But both work fine for me.

Regardless, this is a support issue (because I can't reproduce it), not a bug, and it sounds like you've already found a workaround.

**Comment by AireagoirSteam** [comment]
It wasn't 1.6 sinc ewas a previous nightly

**Comment by AireagoirSteam** [comment]
Anyway thanks was just wondering where you thought I should start checking confgi wise.
