### ISSUE TITLE
[BUG] Emulator hanging in PaRappa The Rapper 2

### ISSUE THREAD

**Issue by some-username-here1** [PCSX2/pcsx2#7723]
### Describe the Bug

When playing PaRappa The Rapper 2, the memory usage for `pcsx2_qt`, under Linux at least, increases with each stage selected that differs from the previous. Memory usage starts off at ~400 MB and increases up to ~768 MB at most and ~742 MB at least before the emulator, not pcsx2 itself, crashes, rendering the inability to force close it outside of using system monitor, or task manager for Windows.
The second time it crashed, didn't think much of the first crash until it happened again, was within the first 15 minutes or so (going up to 768 MB). The third time taking a lot longer to occur, around an hour or so, going up to 742 MB instead.

### Reproduction Steps

1. Launch PaRappa The Rapper 2, NTSC-U version (Although this could apply to NTSC-J and PAL as well.)
2. Note of the current memory usage at the title screen.
3. Go to the stage select map and select a random stage, any should do.
4. Rinse and repeat at least 3 times, with each stage being different from the last.
5. Note of the increased current memory usage.

### Expected Behavior

No memory leak or crash when playing the game for hours, as previously no crashes has happened prior to updating to version 1.7.3806.

### PCSX2 Revision

v1.7.3806

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian 11 (Bullseye)

### CPU

Ryzen 5600X

### GPU

RTX 3060 (with proprietary nvidia drivers, version 470.141.03)

### GS Settings

![image](https://user-images.githubusercontent.com/34193156/209884908-13c3ab74-068b-42d3-8ec2-2198581fcae1.png)
![image](https://user-images.githubusercontent.com/34193156/209884921-816fc106-990d-4673-8442-0cc974f1e026.png)
![image](https://user-images.githubusercontent.com/34193156/209884930-28d9ba99-8be5-428a-a2fe-a041914e54af.png)
![image](https://user-images.githubusercontent.com/34193156/209884940-5f421b6c-c763-4988-a932-6639a661bcec.png)
![image](https://user-images.githubusercontent.com/34193156/209884961-4e73547d-d134-4feb-b01d-d1f3c988efc1.png)
![image](https://user-images.githubusercontent.com/34193156/209884962-85b240c3-bb28-466c-aa62-cc4cc12e6ff9.png)
![image](https://user-images.githubusercontent.com/34193156/209884974-1d1f678f-7434-43ab-b685-c9f6286b37cf.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/34193156/209885040-a410d145-c3d9-49eb-8169-cf231c87e3ab.png)

**Comment by refractionpcsx2** [comment]
Well of course memory usage will increase, graphics change between stages. Some level of memory usage is not uncommon, does it crash? does it stop once it hits 768mb? because memory leaks don't stop.

**Comment by some-username-here1** [comment]
Really? Yeah the emulation stopped both times, forgot to mention that

**Comment by refractionpcsx2** [comment]
if it crashes, then sure that's no good, does it make a crash .dmp and txt file in your pcsx2 folder? that would be useful

**Comment by some-username-here1** [comment]
Unfortunately, no. It just stops the emulation and not pcsx2 itself, as said in the original post, making it hard to diagnose unless there's easy debug options.

**Comment by refractionpcsx2** [comment]
okay can you find out exactly where it stopped working properly? That would be helpful.

Thanks.

**Comment by some-username-here1** [comment]
Sometimes it's hard to say, but I think it was in-stage when it happened both times. Will try again in a bit or so

**Comment by some-username-here1** [comment]
I got it to happen again, this time happening right as I was selecting a stage mode, being single player in this case

**Comment by refractionpcsx2** [comment]
okay but can you make it happen reliably?

**Comment by some-username-here1** [comment]
Hard to say, but I could try one stage, finish and replay it again, then go to another stage and see if that's what causes it

**Comment by refractionpcsx2** [comment]
hang would be closer, I suppose, you said the emulator wasn't crashing.

**Comment by cuckydev** [comment]
in my testing the behavior of memory seems to be working as expected for assets being cached, with it settling around a given memory value depending on your settings (seems to be around 413mb for software renderer, 606mb for 3x d3d12)

**Comment by refractionpcsx2** [comment]
Also can you show your Emulation settings tab, and also the same one under view->properties when the game is running? 

thanks.

**Comment by some-username-here1** [comment]
Testing it again and this time it after completing a stage, while idling at the save screen for a few minutes

**Comment by refractionpcsx2** [comment]
hmm, I have a thought, gonna try here.

**Comment by refractionpcsx2** [comment]
@some-username-here1 can you test #7724 once it compiles?  Do you know how to get artifacts from the PR?

**Comment by refractionpcsx2** [comment]
can you try it @some-username-here1 ?

**Comment by some-username-here1** [comment]
hold on, I'm here now and I will do in a couple of minutes or so

**Comment by refractionpcsx2** [comment]
Thank you

**Comment by refractionpcsx2** [comment]
Just in case you're struggling to find them, this is the link to the app images https://github.com/PCSX2/pcsx2/actions/runs/3797704375

**Comment by some-username-here1** [comment]
Currently testing it right now, will comment back later if any crashes still occurs

**Comment by refractionpcsx2** [comment]
If you could let me know what happens either way, so I know if the fix is appropriate or needs further tweaking.

thanks for testing.

**Comment by some-username-here1** [comment]
45 minutes or so, and so far there hasn't been any crashes since

**Comment by refractionpcsx2** [comment]
Awesome, thanks!
