### ISSUE TITLE
[BUG]: Original xbox controller with USB to PC adapter doesn't work

### ISSUE THREAD

**Issue by Fabxx** [PCSX2/pcsx2#7731]
### Describe the Bug

The controller gets detected by the pcsx2 console, but the buttons can't be binded to it.

Device Description:
Bus 001 Device 010: ID 045e:0289 Microsoft Corp. Xbox Controller S
Bus 001 Device 009: ID 045e:0288 Microsoft Corp. Xbox Controller S Hub

### Reproduction Steps

attach the og xbox controller to the PC (tested on arch linux, on widows the cable adapter doesn't work). Run PCSX2 and try to bind controls, or try to auto.bind them, those won't be binded.

### Expected Behavior

This controller should be auto-binded like an Xinput controller.

### PCSX2 Revision

1.7.3816 nightly

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by stenzek** [comment]
Likely needs a SDL game controller db entry. See https://github.com/gabomdq/SDL_GameControllerDB.
