### ISSUE TITLE
[Feature Request]: Appeal for community sanctions

### ISSUE THREAD

**Issue by fdyyt** [PCSX2/pcsx2#7737]
### Description

Some users might have been problematic, or have been excluded because of a misunderstanding. But these users should have a chance to improve themselves through discussion via the support team. Due to a lack of proper sanctions appeals, people would be forced to assume alternate accounts to provide a route of appeal.

### Reason

This could make it much easier for people to have a chance to rectify themselves and improve their relations to the community.
These reformed users could use their second chance to learn how to contribute to the community and the emulator.
It allows people to have a legitimate second chance on the community, which are currently not possible..

### Examples

There already is a ban appeal forum implemented by another server:
https://docs.google.com/forms/d/e/1FAIpQLSfuT6DxP99Tm5_SY6jCfVRjh89eVRyqlBDKAtrhxDcvg-BDfQ/viewform

**Comment by RedDevilus** [comment]
You already had your 5000 chances.

**Comment by fdyyt** [comment]
@RedDevilus what were these "5000 chances"?

**Comment by RedDevilus** [comment]
5001

**Comment by fdyyt** [comment]
@RedDevilus The community never really gave me a chance.

**Comment by stenzek** [comment]
Please leave us alone.
