### ISSUE TITLE
Heavy screen flickering on 2D objects in FFXII DX11 mode  (August 18 SVN)

### ISSUE THREAD

**Issue by firaX** [PCSX2/pcsx2#774]
-PCSX2 version: v1.3.1-976-ga4f8c6d

-PCSX2 options: Defaults, no settings modifications affect the issue (I have, however, literally tried all hacks/options) 

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: In August 18 Version, as opposed to stable version, when selecting DX11 (DX9, OGL work fine) FFXII (possibly other games) shows heavy black flickering on 2D objects, such as entire Square Intro screen, Maps, Menu, Cursors. DX11 works fine in official 1.2.1 stable release. Windows 10, latest nvidia WHQL drivers. 

-How to replicate: August 18 SVN, FFXII (Zodiac). 

-Last known version to work: 1.2.1 Stable (haven't tested anything in between)

-PC specifications: Intel Core i5 6600k (3,5Ghz Quad), Nvidia GTX970 (latest WHQL Driver, Win10), 16GB DD4, Windows 10 Pro 64Bit. 

-Other comments: https://www.reddit.com/r/PCSX2/comments/3hl0o6/ff12_screen_flicker_dx11_nvidiawin10/

**Comment by karasuhebi** [comment]
Thanks for the report firaX! @refractionpcsx2, since he says it works fine on OpenGL, this one's probably for you. :)

**Comment by refractionpcsx2** [comment]
That sounds very much like the Nvidia hack striking again.  For some reason it doesn't play well on Windows 10 :(

**Comment by bositman** [comment]
Can't replicate here. Care to try some revisions from the buildbot, to find a newer version that works?
http://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by refractionpcsx2** [comment]
I get flickering on the minimap in DX11 when i run the FFXII demo, also noticed a shadow flicker.

**Comment by refractionpcsx2** [comment]
Can you try with the commit i just pushed? Seems to have fixed the issues with Nvidia cards for me.

**Comment by deadair3210** [comment]
Fixes the issue i was having with Kingdom Hearts where the save menu would flicker. Seems to be a problem with Square games

**Comment by refractionpcsx2** [comment]
Damn you square!! :P Glad its sorted, will close this issue now :)

**Comment by firaX** [comment]
I will check later, BTW I noticed flicker occurred also in the "cube" on
Sony bios boot screen (the cubes that move behind Sony ce logo).

**Comment by refractionpcsx2** [comment]
Yep that was one of the symptoms.  Sounds like fixing  this has reintroduced some stretching :(

**Comment by firaX** [comment]
In Game or bios? I only tested quickly , wide-screen in game on, plus ws in
emulator, game looks fantastic . But I only tested briefly.

**Comment by refractionpcsx2** [comment]
the BIOS cubes and the issues in the game were both symptoms.

**Comment by karasuhebi** [comment]
He's asking where you saw the new stretching that was introduced with the fix.

**Comment by refractionpcsx2** [comment]
Oh! Here: http://forums.pcsx2.net/Thread-GSdx-graphic-bug-on-Windows-10?pid=476345#pid476345
