### ISSUE TITLE
[Feature Request]: Logpoints

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7750]
### Description

A logpoint is like a breakpoint with the only difference that a logpoint prints the value of the PC register in the log window of PCSX2 on trigger unlike breakpoints which pause PCSX2 on trigger.

### Reason

There are memory addresses that are accessed by many different MIPS instructions and some of them are executed every frame while the others are executed only when something happens in the game and I want to find these MIPS instructions that are executed only when something happens in the game and not these that are executed every frame.

The problem is that if I add either read or write breakpoint then the game pauses every frame because of these MIPS instructions that are executed every frame and access these memory address every frame and trigger the read or write breakpoint every frame and because of this I am unable to proceed to the event.

The workaround is to assemble these problematic MIPS instructions so that they no longer access the memory address every frame and trigger the read or write breakpoint every frame so that I can proceed to the event but I will have to face all the consequences of assembling these MIPS instructions which may be not good at all like unexpected behaviours or game freezes at certain point in time or even causing PCSX2 to crash!

If I use either a read or write logpoint instead then I don't have to assemble these MIPS instructions that are executed every frame and face all these consequences at all because logpoints by definition don't pause PCSX2 at all so I can proceed to the event and then view the addresses of the MIPS instructions that accessed the memory address on the event in the log window of PCSX2 and at last remove the read or write logpoint if no longer needed.

### Examples

In Devil May Cry the clear time tells you how much time it took you to complete the last mission.

There is a `lw` instruction that reads the clear time before drawing it on screen but that `lw` instruction is executed only when completing the current mission.

If scan type will be added to PCSX2 Debugger that is #7696 somewhen then by doing "Unknown initial value" and repeatedly "Increased value" I can eventually find the memory address of the "clear time" of Devil May Cry.

Then add there a read logpoint before completing the current mission, then complete the current mission, wait to see the clear time, then view the log window of PCSX2 and there find the address of the `lw` instruction that read the value of the "clear time".

At last assemble that `lw register` instruction to `move register, zero` where "register" is the first operand of the `lw` instruction that can be either `a0`, `a1`, `a2`, `a3`, `v0`, `v1`, `t0`, `t1`, `t2`, `t3`, `t4`, `t5`, `t6`, `t7`, `t8`, `t9` and etc.

From the next mission and onwards you see that the clear time is always 0:00:00 no matter how much time it took you to complete it.

If I add there a read breakpoint instead then the game pauses every frame because there is another `lw` instruction that reads that "clear time" every frame and assembling it to `nop` causes Devil May Cry to freeze though the music is still playing in the background.

This is the reason that I should use a read logpoint instead of read breakpoint in this example.

**Comment by kakashi314** [comment]
+1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.

**Comment by buruto** [comment]
> +1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.

You mean like the "Replace with code that does nothing" of Cheat Engine? Well this is also something I would like to have but less important than the recent feature requests that I opened.

A pity that I still don't know why #7520 was closed as not planned.
Saying that it is a duplicate of #7453 does not sound a reason for me.

**Comment by Goatman13** [comment]
Should be very easy to implement. Because function is already there, just currently don't print pc. 

Changing  2 lines in dynarecMemLogcheck do the job. 
```
	if (store)
		DevCon.WriteLn("Hit store breakpoint @0x%x at 0x%x", start, pc - 4);
	else
		DevCon.WriteLn("Hit load breakpoint @0x%x at 0x%x", start, pc - 4);
```

```
[   84.7359] Hit load breakpoint @0x10009000 at 0x100c48
[   84.7424] Hit store breakpoint @0x10009000 at 0x29d908
```

Problem is that disabling breakpoint in new debugger is broken. When i untick "enabled", it will skip breakpoint like it should and print info. This happen only one time. Next time execution stop and breakpoint is re-enabled. With old debugger this work, just print to log without breaking execution.

**Comment by buruto** [comment]
> Should be very easy to implement. Because function is already there, just currently don't print pc.
> 
> Changing 2 lines in dynarecMemLogcheck do the job.
> 
> ```
> 	if (store)
> 		DevCon.WriteLn("Hit store breakpoint @0x%x at 0x%x", start, pc - 4);
> 	else
> 		DevCon.WriteLn("Hit load breakpoint @0x%x at 0x%x", start, pc - 4);
> ```
> 
> ```
> [   84.7359] Hit load breakpoint @0x10009000 at 0x100c48
> [   84.7424] Hit store breakpoint @0x10009000 at 0x29d908
> ```
> 
> Problem is that disabling breakpoint in new debugger is broken. When i untick "enabled", it will skip breakpoint like it should and print info. This happen only one time. Next time execution stop and breakpoint is re-enabled. With old debugger this work, just print to log without breaking execution.
> 
> Edit: There is actually little bit more. When i set it to disabled in "new" or "edit" breakpoint, it works as expected. Only "enable" tick toggle seems to be broken, and state is unchanged.

I think that I should bug report this because the old debugger is no more anymore.

**Comment by F0bes** [comment]
> +1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.

Added in #7755 

> There is actually little bit more. When i set it to disabled in "new" or "edit" breakpoint, it works as expected. Only "enable" tick toggle seems to be broken, and state is unchanged.

Fixed in #7755 

> and saying that https://github.com/PCSX2/pcsx2/issues/7520 is a duplicate of https://github.com/PCSX2/pcsx2/discussions/7453 does not sound to me a reason to close it as "not planned" even though this is a bit true.

It is a duplicate, it is the same information twice. I don't know why you're bothered by this as the issue isn't deleted and still can be used as a reference for someone who would like the implement such a feature. Don't worry about the 'not planned' mark, GitHub allows us to close an issue as 'Not Planned' or 'Completed'. We don't have any other option.

> If you can evaluate the complexity of https://github.com/PCSX2/pcsx2/issues/7750 then can you also evaluate the complexities of both https://github.com/PCSX2/pcsx2/issues/7696 and https://github.com/PCSX2/pcsx2/issues/7697 too?

https://github.com/PCSX2/pcsx2/issues/7696 is partially reasonable to implement, having less than or greater than isn't that difficult. It gets muddy with `unknown initial value` and scanning through those records as the performance is going to be worrisome 😅.

https://github.com/PCSX2/pcsx2/issues/7697 is again, not that difficult to implement. As you said in the pull request, it is alike the string type

---

As for the logpoints, it's not that difficult to implement, but I'm currently trying to refactor a lot of the debugger stuff, with the holidays, school, work, and personal life, it's quite difficult. I'm trying to tackle what I can.

**Comment by buruto** [comment]
> > +1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.
> 
> Added in #7755
> 
> > There is actually little bit more. When i set it to disabled in "new" or "edit" breakpoint, it works as expected. Only "enable" tick toggle seems to be broken, and state is unchanged.
> 
> Fixed in #7755
> 
> > and saying that #7520 is a duplicate of #7453 does not sound to me a reason to close it as "not planned" even though this is a bit true.
> 
> It is a duplicate, it is the same information twice. I don't know why you're bothered by this as the issue isn't deleted and still can be used as a reference for someone who would like the implement such a feature. Don't worry about the 'not planned' mark, GitHub allows us to close an issue as 'Not Planned' or 'Completed'. We don't have any other option.
> 
> > If you can evaluate the complexity of #7750 then can you also evaluate the complexities of both #7696 and #7697 too?
> 
> #7696 is partially reasonable to implement, having less than or greater than isn't that difficult. It gets muddy with `unknown initial value` and scanning through those records as the performance is going to be worrisome 😅.
> 
> #7697 is again, not that difficult to implement. As you said in the pull request, it is alike the string type
> 
> As for the logpoints, it's not that difficult to implement, but I'm currently trying to refactor a lot of the debugger stuff, with the holidays, school, work, and personal life, it's quite difficult. I'm trying to tackle what I can.

Well I didn't assume that you have a lot of time to work on this project but your answers satisfy me.

I would expect to see that #7520 was closed as "duplicate" instead of "not planned" but if you say that GitHub does not offer "Close as duplicate" then I understand. As long as #7520 is planned then I can calm down.

Also you said that "Replace with code that does nothing" has already been added in #7755 but I don't see it at all in the context menu that appears after right clicking any MIPS instruction.

**Comment by kakashi314** [comment]
> > > +1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.
> > 
> > 
> > Added in #7755
> > > There is actually little bit more. When i set it to disabled in "new" or "edit" breakpoint, it works as expected. Only "enable" tick toggle seems to be broken, and state is unchanged.
> > 
> > 
> > Fixed in #7755
> > > and saying that #7520 is a duplicate of #7453 does not sound to me a reason to close it as "not planned" even though this is a bit true.
> > 
> > 
> > It is a duplicate, it is the same information twice. I don't know why you're bothered by this as the issue isn't deleted and still can be used as a reference for someone who would like the implement such a feature. Don't worry about the 'not planned' mark, GitHub allows us to close an issue as 'Not Planned' or 'Completed'. We don't have any other option.
> > > If you can evaluate the complexity of #7750 then can you also evaluate the complexities of both #7696 and #7697 too?
> > 
> > 
> > #7696 is partially reasonable to implement, having less than or greater than isn't that difficult. It gets muddy with `unknown initial value` and scanning through those records as the performance is going to be worrisome 😅.
> > #7697 is again, not that difficult to implement. As you said in the pull request, it is alike the string type
> > As for the logpoints, it's not that difficult to implement, but I'm currently trying to refactor a lot of the debugger stuff, with the holidays, school, work, and personal life, it's quite difficult. I'm trying to tackle what I can.
> 
> Well I didn't assume that you have a lot of time to work on this project but your answers satisfy me.
> 
> I would expect to see that #7520 was closed as "duplicate" instead of "not planned" but if you say that GitHub does not offer you the "Close as duplicate" button or option then I understand.
> 
> As long as #7520 is planned then I can calm down.
> 
> Also you said that "Unknown initial value" is not so trivial and while I want to agree with you Cheat Engine did implement it somehow and I would like to know how does Cheat Engine do "Unknown initial value" first scan.
> 
> What about my new concept NoBreakpoints? I think that NoBreakpoints are harder than logpoints and this is the reason that I decided that #7750 will concern logpoints instead of NoBreakpoints but I would like to know what do you think about this concept.
> 
> Also you said that "Replace with code that does nothing" has already been added in #7755 but I don't see it at all in the context menu that appears after right clicking any MIPS instruction in the Assembly View in the Debugger window of PCSX2.
> 
> I do see there "Assemble new instruction(s)" but not "Replace with code that does nothing" at all neither below nor above it.
> 
> I don't see this option even in the latest nightly build of pcsx2 that is v1.7.3829 as of now.
> 
> I stared and glanced in #7755 a bit more and I see that you call it "NOP Instruction(s)" instead of "Replace with code that does nothing".
> 
> This is also good for me but I don't find that too not even on 3829.
> 
> Even on v1.7.3833 I don't find that "NOP Instruction(s)" anywhere.
> 
> Maybe I misunderstood you. You meant to say that "NOP Instruction(s)" is now planned but not added yet.
> 
> Correct me if I am wrong.
> 
> I looked even more in #7755 and I see that it is verified. Maybe it was not merged yet?
> 
> By the way are you planning that v1.7.5 is going to be the next stable release of pcsx2?
> 
> Just curious that's all.
> 
> Off Topic: How goes PS1 compatibility?

Nop instructions is replace with code that does nothing. 

Cheat engine just simply simplified the wording. it's the exact same function.

**Comment by buruto** [comment]
> > > > +1, Also i hope we get an option for nopping the selected addresses instead of pressing assemble and then writing nop everytime.
> > > 
> > > 
> > > Added in #7755
> > > > There is actually little bit more. When i set it to disabled in "new" or "edit" breakpoint, it works as expected. Only "enable" tick toggle seems to be broken, and state is unchanged.
> > > 
> > > 
> > > Fixed in #7755
> > > > and saying that #7520 is a duplicate of #7453 does not sound to me a reason to close it as "not planned" even though this is a bit true.
> > > 
> > > 
> > > It is a duplicate, it is the same information twice. I don't know why you're bothered by this as the issue isn't deleted and still can be used as a reference for someone who would like the implement such a feature. Don't worry about the 'not planned' mark, GitHub allows us to close an issue as 'Not Planned' or 'Completed'. We don't have any other option.
> > > > If you can evaluate the complexity of #7750 then can you also evaluate the complexities of both #7696 and #7697 too?
> > > 
> > > 
> > > #7696 is partially reasonable to implement, having less than or greater than isn't that difficult. It gets muddy with `unknown initial value` and scanning through those records as the performance is going to be worrisome 😅.
> > > #7697 is again, not that difficult to implement. As you said in the pull request, it is alike the string type
> > > As for the logpoints, it's not that difficult to implement, but I'm currently trying to refactor a lot of the debugger stuff, with the holidays, school, work, and personal life, it's quite difficult. I'm trying to tackle what I can.
> > 
> > 
> > Well I didn't assume that you have a lot of time to work on this project but your answers satisfy me.
> > I would expect to see that #7520 was closed as "duplicate" instead of "not planned" but if you say that GitHub does not offer you the "Close as duplicate" button or option then I understand.
> > As long as #7520 is planned then I can calm down.
> > Also you said that "Unknown initial value" is not so trivial and while I want to agree with you Cheat Engine did implement it somehow and I would like to know how does Cheat Engine do "Unknown initial value" first scan.
> > What about my new concept NoBreakpoints? I think that NoBreakpoints are harder than logpoints and this is the reason that I decided that #7750 will concern logpoints instead of NoBreakpoints but I would like to know what do you think about this concept.
> > Also you said that "Replace with code that does nothing" has already been added in #7755 but I don't see it at all in the context menu that appears after right clicking any MIPS instruction in the Assembly View in the Debugger window of PCSX2.
> > I do see there "Assemble new instruction(s)" but not "Replace with code that does nothing" at all neither below nor above it.
> > I don't see this option even in the latest nightly build of pcsx2 that is v1.7.3829 as of now.
> > I stared and glanced in #7755 a bit more and I see that you call it "NOP Instruction(s)" instead of "Replace with code that does nothing".
> > This is also good for me but I don't find that too not even on 3829.
> > Even on v1.7.3833 I don't find that "NOP Instruction(s)" anywhere.
> > Maybe I misunderstood you. You meant to say that "NOP Instruction(s)" is now planned but not added yet.
> > Correct me if I am wrong.
> > I looked even more in #7755 and I see that it is verified. Maybe it was not merged yet?
> > By the way are you planning that v1.7.5 is going to be the next stable release of pcsx2?
> > Just curious that's all.
> > Off Topic: How goes PS1 compatibility?
> 
> Nop instructions is replace with code that does nothing.
> 
> Cheat engine just simply simplified the wording. it's the exact same function.

I already know this. Since the developers of PCSX2 Debugger decided to call it "NOP Instruction(s)" then my question is where is this "NOP Instruction(s)" action?

I don't find it next to the "Assemble new instruction(s)" context menu not even on v1.7.3833.

**Comment by kakashi314** [comment]
That's because it hasn't been accepted into pcsx2 yet. if you are interested in downloading the build that has this then here you go https://github.com/PCSX2/pcsx2/suites/10127707546/artifacts/494287573

**Comment by buruto** [comment]
> That's because it hasn't been accepted into pcsx2 yet. if you are interested in downloading the build that has this then here you go https://github.com/PCSX2/pcsx2/suites/10127707546/artifacts/494287573

Where did you get that?

**Comment by kakashi314** [comment]
From here: https://github.com/PCSX2/pcsx2/actions/runs/3815216771
Go down to the artifacts tab and you will find the downloads.
As for it not being accepted yet. it will be. but it needs more testing.

**Comment by F0bes** [comment]
> Where did you get that? And why it hasn't been accepted if it is both useful and working? And why the context menu does not appear when I right click any MIPS instruction in the Disassembly view? It seems worse than v1.7.3833

It hasn't been accepted yet because it hasn't been reviewed yet. Changes are not made instantly. 
As for the context menu issues, I can not reproduce. As long as the VM is alive (paused or running as game) the context menu should show up.
This is me running the build from my PR (#7755) .
![image](https://user-images.githubusercontent.com/29295048/210182222-6e5fb3cc-9dfc-4dec-9c6b-acc0fc7fcae8.png)

**Comment by buruto** [comment]
> > Where did you get that? And why it hasn't been accepted if it is both useful and working? And why the context menu does not appear when I right click any MIPS instruction in the Disassembly view? It seems worse than v1.7.3833
> 
> It hasn't been accepted yet because it hasn't been reviewed yet. Changes are not made instantly.
> 
> > I looked even more in #7755 and I see that it is verified. Maybe it was not merged yet?
> 
> Yes, exactly.
> 
> > Also you said that "Unknown initial value" is not so trivial and while I want to agree with you Cheat Engine did implement it somehow and I would like to know how does Cheat Engine do "Unknown initial value" first scan.
> 
> I know how to do it, it pretty much creates a copy of the entire memory space. I just haven't done enough research to know how to do it in a not-hacked way.
> 
> As for the context menu issues, I can not reproduce. As long as the VM is alive (paused or running as game) the context menu should show up. This is me running the build from my PR (#7755) . ![image](https://user-images.githubusercontent.com/29295048/210182222-6e5fb3cc-9dfc-4dec-9c6b-acc0fc7fcae8.png)

When the "NOP Instruction(s)" will be reviewed then it is probably going to be accepted due to it's usefulness and time saving and if it is really working.

**Comment by buruto** [comment]
I noticed that #7755 has been merged to PCSX2 on v1.7.3843.
This new already warms my heart.
I wish that my feature requests will be implemented too someday.

**Comment by F0bes** [comment]
> ... this is still strange that from now on I have to start BIOS to make that context menu appear on right clicking any MIPS Instruction in the Disassembly view but I don't care much about this issue at all.

I don't understand this. You can start the BIOS or start a game and the context menu will be unlocked. This is due to the fact that the emulated CPU (the virtual machine in other terms) is not alive when a BIOS or game is **not** running. There would simply be nothing valid to debug / view / disassemble when the virtual machine is dead.
Disabling the context menu in this state was a design choice by me so you were unable to cause undefined behaviour and crash PCSX2 with the debugger.

**Comment by buruto** [comment]
I have done it by myself.

**Comment by RedDevilus** [comment]
You made a typo, 'Fobes' did it.

**Comment by F0bes** [comment]
I didn't. Let's try to not start battles on GitHub.
