### ISSUE TITLE
[BUG]: Killzone (SCUS_974.02) Black screening when trying to load the Online menu

### ISSUE THREAD

**Issue by Zero1UP** [PCSX2/pcsx2#7751]
### Describe the Bug

When trying to start up the online mode the emulator just goes to a black screen and halts. This wasn't something that recently broke. As far as I know it's been this way since early 1.7 builds.

### Reproduction Steps

At the main menu select Battlefields and then Online game. From there it will just go to a black screen.

### Expected Behavior

It should bring up your network settings to pick from.

### PCSX2 Revision

v1.7.3822

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 9 3900X

### GPU

GTX 970

### Logs & Dumps

[emulog.zip](https://github.com/PCSX2/pcsx2/files/10327933/emulog.zip)

**Comment by prafullpcsx2** [comment]
It was broken when disc swapping was implemented

https://github.com/PCSX2/pcsx2/commit/8d92c0668c5e2a1acebbff93dc4bf241944ff2f9
