### ISSUE TITLE
[Feature Request]: Multiple real-world inputs assigned to single emulator inputs

### ISSUE THREAD

**Issue by DieselVomit** [PCSX2/pcsx2#7752]
### Description

I am suggestion the expansion of the controller mapping system in the emulator currently to allow the user to map multiple inputs from their real-world peripherals to a single action in the emulator. 
For example, mapping both the D-pad UP and left analogue stick Y+  to the emulated ps2 controller's d-pad UP, or mapping the Right analogue stick y+ and topmost face button both to the emulated ps2 controller's Triangle.

### Reason

This feature will benefit people playing some specific games, such as the Armored Core entries on the PS2 platform or other games that do not natively utilise/recognise the analogue sticks as well as people who have more complicated controllers which would have buttons spare they may want to map as duplicate inputs for ease of use or other personal reasons. This is a situational quality of life improvement but I firmly believe an important one in usability. While some avenues for doing this already exist it can be extremely tetchy when using analogue stick inputs due to deadzones not being accounted for when the sticks are mapped to a non-analogue input EG a d-pad direction or face button.

### Examples

The button mapping systems present in software like Retroarch are more focused on assigning emulated inputs to the real-world peripheral's buttons, instead of the inverse which is currently present in the pcsx2 emulator. While a full reversal or even just the option to map things this way around instead could be too much, having a '+' button next to each ps2 input to add a slot for an additional input mapping would be an extremely clear and intuitive way to present this feature.

**Comment by refractionpcsx2** [comment]
Shift + left click the binding gives you a list you can add more bindings to.
