### ISSUE TITLE
[Feature Request]: Debugger - Implement help menu

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#7778]
As far as i can tell the Qt Debugger menu doesn't have any kind of help menu and it would be great to implement such a thing for new users.

**Comment by stenzek** [comment]
I'll leave this for fobes to decide, but we don't have in-application help _anywhere_ in the Qt interface - instead you're expected to use the wiki etc. So the debugger isn't really any different.

**Comment by Risae** [comment]
> I'll leave this for fobes to decide, but we don't have in-application help anywhere in the Qt interface - instead you're expected to use the wiki etc. So the debugger isn't really any different.

Oh, i see. But you have tooltips for various options, right? Maybe adding something like that wouldn't be too far fetched? Right now the user experience for new users using the Qt Debugger is rather... complicated.

**Comment by F0bes** [comment]
If there isn't a help dialog for other parts of the interface then I don't feel like spending my time creating one for the debugger. I'm happy to provide information on the wiki though.

> Oh, i see. But you have tooltips for various emulation options, right? Maybe adding something like that wouldn't be too far fetched? Right now the user experience for new users using the Qt Debugger is rather... complicated.

Yes, general accessibility (in particular tooltips), is something I've wanted to get in before our next stable release.
