### ISSUE TITLE
[Feature Request]: Debugger - Implement scrollbar for the disassembly view

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#7779]
Never really understood why the disassembly view doesn't have any kind of scrollbar and i think it would be a good addition to the Qt Debugger. Maybe add it as a toggleable option?

**Comment by stenzek** [comment]
And where would it scroll between? There's 32MB of RAM, you couldn't be precise enough with mouse movement in a scrollbar, and we don't necessarily know the bounds of the binary code. Plus code dynamically loaded/generated, etc.

**Comment by Risae** [comment]
> 

I am aware that the amount of code is huge. Questions i have asked myself in the beginning of using the debugger were "Am i actually at the beginning of the code or in the middle of nowhere?". This also makes it even more confusing when you think you are at the very top but you can actually still scroll higher (after starting a game). Having some kind of scrollbar would  give beginners a better understanding on where they are in the code disassembly view. In my opinion this would help the user experience, but i am not experienced enough to know what the implemented feature will feel like as a user.

**Comment by Oymat** [comment]
There was a scrollbar in wx but it was sadly never functional. i don't think adding a scrollbar that isn't functional into qt is a good idea :/

**Comment by buruto** [comment]
> This

I was using the debugger for a while and I never had to know where I am in the executable code of the game.

All what mattered to me is to remember the addresses of some MIPS instructions that I assembled to get some cheats in the game and also disable them.

As long as you can remember the addresses of the MIPS instructions that you want to assemble and go to any address by pressing Ctrl+G then you don't need any scroll bar to tell you where you are.

Besides a scroll bar won't be any better than Ctrl+G to go to a specific MIPS instruction at a specific address.

**Comment by lightningterror** [comment]
Closing as not planned.
