### ISSUE TITLE
VS 2015 Enterprise

### ISSUE THREAD

**Issue by Dokman** [PCSX2/pcsx2#778]
No se pudo cargar 'pcsx2' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\pcsx2\windows\VCprojects\pcsx2.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'SPU2-X' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\spu2-x\src\Windows\Spu2-X.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'GSdx' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\GSdx\GSdx.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'SoundTouch' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\soundtouch\SoundTouch.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'zlib' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\zlib\zlib.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'LilyPad' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\LilyPad\LilyPad.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'w32pthreads.v4' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\w32pthreads\pthreads.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'xpad' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\xpad\xpad.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'CDVDnull' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\CDVDnull\Windows\CDVDnull.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'USBnull' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\USBnull\Windows\USBnull.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'FWnull' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\FWnull\Windows\FWnull.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'DEV9null' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\dev9null\Windows\DEV9null.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'x86emitter' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\common\build\x86emitter\x86emitter.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'utilities' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\common\build\Utilities\utilities.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'bin2cpp' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\tools\bin2cpp\bin2c.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'libjpeg7' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\libjpeg\libjpeg.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'w32pthreads_lib' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\w32pthreads\pthreads_lib.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'cdvdGigaherz' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\cdvdGigaherz\src\Windows\cdvdGigaherz.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'GSnull' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\GSnull\Windows\GSnull.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'Padnull' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\PadNull\Windows\PadNull.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'portaudio' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\portaudio\build\msvc\portaudio.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'DEV9ghzdrk' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\dev9ghzdrk\Win32\DEV9ghzdrk.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'USBqemu' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\plugins\USBqemu\Win32\USBqemu.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'opencl' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\opencl\opencl.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'wxConfig30' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\wxwidgets3.0\build\msw\wx30_config.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'wxBase30' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\wxwidgets3.0\build\msw\wx30_base.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'wxAdv30' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\wxwidgets3.0\build\msw\wx30_adv.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'wxCore30' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\wxwidgets3.0\build\msw\wx30_core.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

No se pudo cargar 'libpng' del proyecto porque faltan componentes de instalación. Para solucionar este problema, inicie la instalación de Visual Studio con las siguientes selecciones:
Instalar compatibilidad con Windows XP para C++

E:\Repos\pcsx2\3rdparty\libpng\projects\vstudio\libpng\libpng.vcxproj : error  : Excepción de HRESULT: 0x80041FE2

**Comment by micove** [comment]
Luckily, I can read Spanish.

The issue is that as I mentioned before Windows XP support does not get installed by default with VS2015. The error message clearly asks to restart the setup and to install the optional "Wincows XP C++ compatibility".

Basically do a custom install instead of a typical install and ONLY install the red box:

![visual-studio-2015-c-setup](https://cloud.githubusercontent.com/assets/1458001/9376935/9c146a30-46e1-11e5-84d9-5797f9ff4da1.png)

**Comment by Dokman** [comment]
thanks!
