### ISSUE TITLE
[BUG]: Onimusha - Warlords (SLUS-20018) [NTSC-U] Opening Cinematic Extreme Flicker

### ISSUE THREAD

**Issue by Tyestor** [PCSX2/pcsx2#7787]
### Describe the Bug

Extreme flickering, like in a bug I previously reported: https://github.com/PCSX2/pcsx2/issues/6140

No issue in software. Issue exists in all hardware renderers.

**epilepsy warning**

Video: https://gfycat.com/spicyoddballcicada 

### Reproduction Steps

Boot Onimusha Warlords, fast or slow boot, select new game or wait a bit for the cinematic to play. It flickers a lot.

### Expected Behavior

No flickering, like in this video: https://www.youtube.com/watch?v=uH4sD5sSyFA - or in software mode.

### PCSX2 Revision

v1.7.3847

### Operating System

Windows 10 (64bit)

### CPU

AMD 5800X3D

### GPU

AMD 6900XT

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/4704145/210370130-0ca92a8a-e75d-4782-b174-803daefa2033.png)

![image](https://user-images.githubusercontent.com/4704145/210370173-86ae4185-c571-4ce1-a5b9-3e6b74331190.png)

![image](https://user-images.githubusercontent.com/4704145/210370224-208b2d71-a46c-43d3-a24a-64453f5611a8.png)

![image](https://user-images.githubusercontent.com/4704145/210370270-3113533d-87d7-4463-a530-1db303ceaed9.png)

![image](https://user-images.githubusercontent.com/4704145/210370329-c4627d89-b0a9-4329-bf56-7e9fbc80224b.png)

Tried with both my standard settings (pictured) and pure defaults, still flickering.

**Comment by kakashi314** [comment]
Did you try the switch to software renderer on fmvs gamefix ?

**Comment by stoniemahonie** [comment]
same applies to the PAL version of the game. switch to software does indeed help.
