### ISSUE TITLE
Official Ubuntu PPA points to Google code for issue tracking

### ISSUE THREAD

**Issue by Giroom** [PCSX2/pcsx2#779]
Sorry that this "issue" is incredibly miniscule, but I noticed the official PPA, https://launchpad.net/~gregory-hainaut/+archive/ubuntu/pcsx2.official.ppa, still lists Google code as the issue tracker.

**Comment by gregory38** [comment]
That a feature to avoid too much bug report :p I will change it. Thanks for the info.
