### ISSUE TITLE
[BUG]: Exception caught in GSopen: bad allocation on Windows 10

### ISSUE THREAD

**Issue by oddMLan** [PCSX2/pcsx2#7791]
### Describe the Bug

Since build [v1.7.3845](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.3845), I get an allocation error when I try to boot up any ISO.
![error](https://user-images.githubusercontent.com/7278372/210435653-3641a47e-dfb1-4f52-971a-0071e96130a8.png)

Build [v1.7.3844](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.3844) works for me.

### Reproduction Steps

1. Extract [build v1.7.3844](https://github.com/PCSX2/pcsx2/releases/download/v1.7.3844/pcsx2-v1.7.3844-windows-64bit-AVX2-Qt.7z) to a new directory. Set up Bios, etc.
2. Try to boot any iso or the bios (System > Start BIOS). It will work fine.
3. Extract [build v1.7.3845](https://github.com/PCSX2/pcsx2/releases/download/v1.7.3845/pcsx2-v1.7.3845-windows-64bit-AVX2-Qt.7z) on top of the old one, or a new directory (doesnt make a difference). Set up Bios, etc.
4. Try to boot any iso or the bios (System > Start BIOS). **Allocation error occurs.**

Emulog:
```
[    0.4883] PCSX2 Nightly - v1.7.3848 Compiled on Jan  3 2023
[    0.4884] Savestate version: 0x9a340000
[    0.4886]
[    0.4887] Host Machine Init:
[    0.4889]    Operating System =  Microsoft Windows 10+
[    0.4889]    Physical RAM     =  16233 MB
[    0.5008]    CPU name         =  Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
[    0.5008]    Vendor/Model     =  GenuineIntel (stepping 03)
[    0.5008]    CPU speed        =  2.591 ghz (8 logical threads)
[    0.5008]    x86PType         =  Standard OEM
[    0.5008]    x86Flags         =  bfebfbff 7ffafbbf
[    0.5008]    x86EFlags        =  2c100800
[    0.5023]
[    0.5024] x86 Features Detected:
[    0.5026]    SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
[    0.5028]
[    0.5033] Reserving memory for recompilers...
[    0.5057]    Fastmem area: 00000222793A0000 - 000002237939FFFF
[    0.9157] Scanning [redacted] (recursively)
[    1.3761] Current version: v1.7.3848
[    1.3775] Latest SHA: v1.7.3848
[    1.3784] Last Checked SHA:
[    1.3792] No update needed.
[    2.6778] Searching for a BIOS image in [redacted]...
[    2.6796] Bios Found: Japan   v01.00(17/01/2000)  Console
[    2.6802] Using BIOS [redacted] (Japan   v01.00(17/01/2000)  Console Japan)
[    2.6812] Opening CDVD...
[    2.6828] isoFile open ok: [redacted]
[    2.6836]    Image type  = CD
[    2.6843]  * CDVD Disk Open: DVD, Single layer or unknown:
[    2.6867]  * * Track 1: Data (Mode 1) (2218672 sectors)
[    2.6893] Opening GS...
[    2.7398] D3D Adapter: NVIDIA GeForce GTX 970M
[    2.9792] D3D12 Graphics Driver Info:
[    2.9807]    D3D_FEATURE_LEVEL_11_0
[    2.9807]    VID: 0x10DE PID: 0x13D8
[    2.9807]    NVIDIA GeForce GTX 970M
[    2.9807]    Driver Version: 31.0.15.2647
[    3.0282] Failed to map repeat 0 of size 4194304.
[    3.0300] Failed to map repeat 1 of size 4194304.
[    3.0334] Failed to map repeat 2 of size 4194304.
[    3.0351] Failed to map repeat 3 of size 4194304.
[    3.0362] Failed to reserve VA space of size 4194304. WIN API ERROR:487
[    3.0376] ReportErrorAsync: GS: GS error: Exception caught in GSopen: bad allocation
[    3.1262] GS failed to open.
[    3.1285] Failed to open GS.
```

### Expected Behavior

Be able to boot up the game without the allocation error.

### PCSX2 Revision

v1.7.3848

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
can you reboot your PC and try again?

**Comment by oddMLan** [comment]
> Also you're saying a newer version works, but I think this is just random because nothing has changed relating to this.

Sorry, copypaste mistake. I was hoping nobody would be quick enough to notice :p 
Fixed the links.

> can you reboot your PC and try again?

Already did originally, but just in case did that & tried with fresh directories. Still the get the same allocation error unfortunately.

**Comment by stenzek** [comment]
Nothing changed with memory allocation in that build.

I'm guessing you're using ESET or some other AV which is preventing our alias mapping, maybe the older build/path was excluded.

**Comment by oddMLan** [comment]
> I'm guessing you're using ESET or some other AV which is preventing our alias mapping, maybe the older build/path was excluded.

You are correct, I use ESET AV. Specifically it's the **Deep Behavioral Inspection** module (Advanced setup > HIPS) what's causing the conflict. I haven't had to make an exclusion for PCSX2 before. Assuming ESET baked the exclusion into their AV signatures, and that commit changed the signature that PCSX2 generated, therefore tripping up the detection.

@F0bes I see now you reported a [similar issue](https://forum.eset.com/topic/34627-deep-behavioural-inspection-breaking-mapviewoffile3-virtualalloc2/) with the memory allocator to them before. I don't have a forum account there. If you're able to reproduce my issue, would you kindly pass the word to them?

**Comment by refractionpcsx2** [comment]
We already told ESET about this issue like a month ago, and they promised a fix was coming, but I don't know where it is.

**Comment by F0bes** [comment]
> > I'm guessing you're using ESET or some other AV which is preventing our alias mapping, maybe the older build/path was excluded.
> 
> You are correct, I use ESET AV. Specifically it's the **Deep Behavioral Inspection** module (Advanced setup > HIPS) what's causing the conflict. I haven't had to make an exclusion for PCSX2 before. Assuming ESET baked the exclusion into their AV signatures, and that commit changed the signature that PCSX2 generated, therefore tripping up the detection.
> 
> @F0bes I see now you reported a [similar issue](https://forum.eset.com/topic/34627-deep-behavioural-inspection-breaking-mapviewoffile3-virtualalloc2/) with the memory allocator to them before. I don't have a forum account there. If you're able to reproduce my issue, would you kindly pass the word to them?
> 


I'll try to get some sort of minimal reproducible example or information around the issue and I'll report to them. Thanks for posting it here

**Comment by oddMLan** [comment]
@F0bes yes that executable fails for me
![image](https://user-images.githubusercontent.com/7278372/210800985-384c3d3c-cf24-407b-ae1a-f81b8279c145.png)

I'm using ESET Endpoint Security
![image](https://user-images.githubusercontent.com/7278372/210801317-867cbe3c-298f-4fdd-a0c6-5bc204593262.png)

DBI module is at version 1118 on mine, what version is it on yours? Is it possible that the home products have a different (newer) version of the DBI module?
![image](https://user-images.githubusercontent.com/7278372/210801380-efd0415d-09a6-4b01-9de8-cf65efab04b4.png)

**Comment by refractionpcsx2** [comment]
wow that module is ancient, there's definitely no updates available for you?

**Comment by oddMLan** [comment]
Okay, I 

> wow that module is ancient, there's definitely no updates available for you?
> 
> But it's good to know the test exe works (or doesn't, in this case)

Okay, for some reason the regular channel didn't have the latest DBI module. I set the update channel to pre-release, and now it says this.

![image](https://user-images.githubusercontent.com/7278372/210803157-f1182b12-6a37-45d4-9a69-02cad5e17dfa.png)
![image](https://user-images.githubusercontent.com/7278372/210802959-497e72d9-79e4-4d79-b36c-662d7a2f77ea.png)

The map test now runs correctly
![image](https://user-images.githubusercontent.com/7278372/210803278-9f73d526-0aa3-40a4-80fb-347cb5a1d231.png)

Awkward... sorry for sending you on a goose chase for something that was already fixed by ESET. I can only assume their enterprise line gets updates later than the home products.

**Comment by refractionpcsx2** [comment]
I hope they don't have it in pre-release for 2 long, 1 month is a long time, and this is an annoying problem that keeps cropping up.

Thanks for letting us know about the prerelease channel, didn't know about that.
