### ISSUE TITLE
[Feature Request]: NoBreakpoints

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7800]
### Description

NoBreakpoints are set the same way that breakpoints are set: They both are placed on a memory address, a size ranging from 1 to 4 bytes with three types: execute, write or read.

So the only difference between NoBreakpoints and breakpoints is their behaviour.

As you already know when a breakpoint is triggered then PCSX2 pauses but if NoBreakpoint is triggered then PCSX2 won't pause even if any breakpoint was triggered at the same time.

So in fact a breakpoint pauses PCSX2 if and only if it is triggered and no NoBreakpoint is triggered at the same time.

This means that NoBreakpoints can be used to prevent some instructions from pausing PCSX2 or if the user doesn't want that PCSX2 will pause on certain conditions.

### Reason

NoBreakpoints are another possible solution to the same problem that logpoints solve as described in #7750

### Examples

Assuming that #7696 is implemented and after doing "Unknown initial value" and repeating "Increased Value" until finding the memory address of the "clear time" value in Devil May Cry.

Then add a read breakpoint in that "clear time" memory address.

After that the game pauses every frame because there is a `lw` instruction that reads that "clear time" value every frame and because of this the game is unplayable until either the read breakpoint is either removed or disabled or the problematic `lw` instruction is assembled in such a way so it doesn't trigger the read breakpoint anymore and face the consequences of doing that that may be not good as said in #7750.

But if this feature request, that is #7800, will be implemented then simply add an execute NoBreakpoint on that problematic `lw` instruction to prevent that `lw` instruction from pausing PCSX2.

At last finish the current mission and PCSX2 will pause on the `lw register` instruction that reads the "clear time" value before it is drawn on the screen or window because of the same read breakpoint that is still exist and active.

The NoBreakpoint doesn't prevent that `lw register` instruction from pausing PCSX2 because the type of that NoBreakpoint is "Execute" and it is not placed there but on other `lw` instruction that reads the "clear time" every frame and that `lw register` reads the "clear time" value only when completing any mission and before the "clear time" is drawn on the screen or window so the NoBreakpoint is not triggered when that `lw register` instruction is executed.

All what left to do is to assemble that `lw register` instruction to `move register, zero` and then click on the "Resume" button.

Now you see that the clear time is 0:00:00 even though you didn't finish the mission with that time.

Some PCSX2 users may prefer breakpoints with NoBreakpoints more than logpoints if they don't want to mess up with the Logs window of PCSX2 in my opinion.

After all I am talking about an instruction that is executed every frame.

Adding a logpoint that will be triggered by such instructions might "flood" the Logs window very quickly and finding there the specific or particular instruction that user is interested at may be a bit hard.

With both breakpoints and NoBreakpoints the task is easier.

Unfortunately I can't think of another example with the other use case but fortunately I can theoretically both tell and describe what the other use case can be:

Assume that there is a `lw` instruction that reads from two different memory addresses and the user found it somehow:

The first is read by that `lw` instruction every frame while the other is read only when something happens in the game.

The user placed an execute breakpoint on that `lw` instruction and the game pauses every frame because the `lw` instruction reads the first memory address every frame and triggers the execute breakpoint every frame.

Through the debugger the user finds the memory address that `lw` instruction reads from every frame.

Place there a read NoBreakpoint of size 4 bytes, because `lw` always reads a word and a word is always 4 bytes, to prevent that `lw` instruction from pausing PCSX2 when it reads from the first memory address every frame.

Now the user finally can and he or she does what he or she wants to do in the game and causes that `lw` instruction to read from the second memory address.

Now PCSX2 pauses and again through the debugger the user found the memory address that he or she was interested at and the NoBreakpoint didn't prevent that `lw` instruction from pausing PCSX2 because it was not placed on the second memory address that the `lw` instruction reads from even though it's type is "Read".

Instructions that read from more than one different memory addresses can be usually be found inside for loops that traverses or iterates over an array of values to read the entire array.

A read NoBreakpoint can be used if the user doesn't want that PCSX2 will pause on when some elements of any array are read on certain indexes in this generic example.

### Possible Implementation

Let there be two bits which both default to 0: "Break" and "NoBreak"

When any breakpoint is triggered the "Break" bit becomes 1 and when any NoBreakpoint is triggered then the "NoBreak" bit becomes 1.

After drawing a frame:

If the "NoBreak" bit is 1 then the state of the "Break" bit is ignored (don't care) and PCSX2 won't pause.

This means that PCSX2 won't pause even if the "Break" bit is 1.

Else if the "NoBreak" bit is 0 then PCSX2 will pause if and only if the "Break" bit is 1.

In all possible scenarios PCSX2 will pause if and only if both the "NoBreak" bit is 0 and the "Break" bit is 1.

Note that the "NoBreak" bit always takes precedence over the "Break" bit and the "NoBreak" bit is always tested first before the "Break" bit to fulfil user desire to make PCSX2 not pause on certain instructions or conditions that are created by the breakpoints.

And both bits are 0 again before drawing another frame of course.

**Comment by F0bes** [comment]
Is #7870 a solution to your issue? You can check the target address directly in the breakpoint expression.

**Comment by buruto** [comment]
> Is #7870 a solution to your issue? You can check the target address directly in the breakpoint expression.

But how?

**Comment by buruto** [comment]
> Is #7870 a solution to your issue? You can check the target address directly in the breakpoint expression.

I read #7870 but I don't understand anything.
