### ISSUE TITLE
[BUG]: Gunvari Collection + Time Crisis (Japan): GunCon control shots firing too slowly in Time Crisis?

### ISSUE THREAD

**Issue by shnick1985** [PCSX2/pcsx2#7803]
### Describe the Bug

When trying Time Crisis in the collection with the GunCon 2 controls, there seems to be a half-second delay from when the button is pressed to when the shot is actually fired. This allows for only a slow rate of fire, making the game awkward to play. What's even stranger is that the screen flashes white immediately when the button is pressed, but it still takes a half a second before the shot goes off.

### Reproduction Steps

Go into the game, launch Time Crisis from the game selection menu, calibrate the GunCon controls and then try playing either the Story Mode or Special Mission mode as normal

### Expected Behavior

I'm thinking the shots should fire as fast as you can press the trigger button, like in the other Time Crisis games.

### PCSX2 Revision

v1.7.3857

### Operating System

Windows 11

### CPU

i7-12700

### GPU

GeForce RTX 3060

**Comment by shnick1985** [comment]
To add an additional note, the rate of fire seems to be faster (possibly even the normal rate) when on Time Crisis's main menu. It's during gameplay when the problem appears.

**Comment by shnick1985** [comment]
Upon further testing, it seems the problem is very similar to what Time Crisis: Crisis Zone suffers from. It can work as intended...but you need to keep recalibrating until it does.

**Comment by eyfix** [comment]
Try progressive scan mode.

**Comment by kim-sama** [comment]
The port itself has bugs like input lag

**Comment by pcnimdock** [comment]
In guncon2.cpp it's needed change 
GUNCON2_CALIBRATION_DELAY = 9 to GUNCON2_CALIBRATION_DELAY = 12

and 

if (us->calibration_timer == 0) to if (us->calibration_timer < 5)

**Comment by Tovarichtch** [comment]
The suggestion from @pcnimdock fixes a lot of problems:

1) Calibration button is required in few games once; then, shoot with the main trigger to adjust.
2) Offscreen reload is now on point, no issue at all.
3) Trigger the shot is very fast, almos instant like the original hardware.

I strongly suggestion you to submit a PR.

This was tested in Windows and Linux (Batocera v37-dev build).

**Comment by nadenislamarre** [comment]
applied on batocera.linux : https://github.com/batocera-linux/batocera.linux/pull/8759

**Comment by stenzek** [comment]
@nadenislamarre please stop advertising your fork in our repo. This is not the place for it, we don't support modified/third party builds.

**Comment by nadenislamarre** [comment]
it is nor an ad nor a fork.
we use the official pcsx2 commits. we just applied a patch and we do feedback on it.
sharing the link is a way to provide a strict way of what was tested.
i don't get the ideollogy behind removing our feedbacks/tests on the current issue ?
we are not a fork, just a distribution with a package system (like debian) and we try to improve emulation.
we do regularly pr for emulation projects : retroarch, mame, dolphin, rpcs3, and so on.
we don't get any money for that action. just helping on improving emulation.
