### ISSUE TITLE
[Feature Request]: Register Breakpoints

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7815]
### Description

A register breakpoint is a breakpoint that is set on a register, like a0, a1, a2, a3, v0, v1, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9 and so on, and there are two kinds of register breakpoints: Read and Write.

The write register breakpoint is used to pause PCSX2 whenever the value of the register, that the breakpoint is set on, has been changed in instructions like `li`, `lui`, `ori`, `andi`, `xori`, `addiu`, `move`, `or`, `and`, `xor`, `addu`, `subu`, `lb`, `lbu`, `lh`, `lhu`, `lw` and so on.

The read register breakpoint is used to pause PCSX2 whenever the value of the register, that the breakpoint is set on, has been used for some purpose in instructions like `move`, `or`, `and`, `xor`, `addu`, `subu`, `sb`, `sh`, `sw`, `beq`, `bne`, `beql`, `bnel` and so on.

### Reason

Some games read the value of some variable from the memory and store it in a register and use it much later.

I can use a memory read breakpoint to find out the `lb`, `lbu`, `lh`, `lhu` or `lw` instruction that reads this value and see the name of the register that the value is stored at but then I have to repeatedly do a lot of either "Step In" or "Step Over" in the debugger until I find when the value of the variable is actually used through the register.

### Examples

I recall playing Castlevania Symphony of the Night with PCSX-Redux and with the Memory Observer Delta-over-time search I found the address of some variable and then I added a memory read breakpoint.

When the value of that variable was read I found the `lbu` instruction that stored it in the `at` register.

But I saw the next 100 instructions and I didn't see that the `at` register was used at all in these 100 instructions.

I remember that I was clicking on the "Step In" or "Step Over" button like a hundred times but didn't see that the `at` register was used.

But knowing the behaviour of the game I know that somewhere it must be used in a conditional branch instruction.

Maybe if I had clicking "Step In" or "Step Over" thousands times instead of hundreds then I would find it eventually.

Even if this is true then I don't like to do "Step In" or "Step Over" even hundred of times.

In that case I would like to add a "read register breakpoint" on the `at` register and then click "Resume" and wait until the value of the `at` register is used and find the conditional branch instruction that I was looking for.

Of course that Castlevania Symphony of the Night is a PS1 game though maybe it will be playable on PCSX2 someday but I afraid that there maybe PS2 games that also behave like this and if this is true then I want the "register breakpoints" feature for these games.

If I am wrong then close this as not planned.

**Comment by stenzek** [comment]
This would need a non-trivial amount of change in both the interpreter and the dynarecs, and come with a considerable speed hit by doing so.

**Comment by buruto** [comment]
> This would need a non-trivial amount of change in both the interpreter and the dynarecs, and come with a considerable speed hit by doing so.
> 
> (plus, it wouldn't work if the value was loaded, spilled to the stack, and later reloaded).

If that so then give this feature a low priority then because fortunately this feature is no so important.

The scan type #7696 is what most important for me.

**Comment by stenzek** [comment]
Well I have no plans to bloat the recs with it. Up to @F0bes if he's interested in doing so, otherwise unless someone else wants to pick it up, we can probably close it.
