### ISSUE TITLE
[BUG]: Content of memory cards bigger than 8MB is not visible to emulator

### ISSUE THREAD

**Issue by tvoracek** [PCSX2/pcsx2#7816]
### Describe the Bug

Updated emulator to latest version, loaded few games (GT3, SSX etc) and see that their saves are not being loaded. When checked via GT3 file manager I can see that only 1 save file is visible (Baldurs Gate). No GT3 save, no SSX save visible in GT3 File Operations manager. When I open the card in mymc (http://www.csclub.uwaterloo.ca:11068/mymc/) I can see all my saves are there so it must be an issue in emulator.

Happenend sometime around version v1.7.3863

### Reproduction Steps

Try to use any memory card with non-standard size (16MB etc).

### Expected Behavior

Game saves are accessible by games.

### PCSX2 Revision

v1.7.3871

### Operating System

Windows 10 Pro

### CPU

Ryzen 5 3600

### GPU

RTX 3060Ti

**Comment by Mrlinkwii** [comment]
did you load the correct memcard in slot 1 ?

**Comment by tvoracek** [comment]
@Mrlinkwii I didn't change any setting for about a year. I am always using 16MB in slot 1 and 8MB in slot 2. 

Hmm checking MemoryCards in PCSX2 I can see it has 8MB card in Slot1 now. I didn't make that change. Some setting reset when downloaded recent version probably. Will try to change that and see what happens.
