### ISSUE TITLE
New stable version?

### ISSUE THREAD

**Issue by Neustradamus** [PCSX2/pcsx2#7826]
### Description

Dear @pcsx2 team,

It is planned to have a new stable release?

Last is 1.6.0 (2020-05-07), soon 3 years:
- https://github.com/PCSX2/pcsx2/releases/tag/v1.6.0

Thanks in advance.

### Reason

To have a new stable release.

### Examples

To have a new stable release.

**Comment by refractionpcsx2** [comment]
This is not an issue, it's a pointless request. We'll make a stable release when we're ready.

**Comment by Neustradamus** [comment]
Dear @PCSX2 team,

I wish you a Happy New Year 2024.

It is possible to have the new release build?

Last is 1.6.0 (2020-05-07), soon 4 years:
- https://github.com/PCSX2/pcsx2/releases/tag/v1.6.0

Thanks in advance.

**Comment by JordanTheToaster** [comment]
no
