### ISSUE TITLE
[FeatureRequest] Loading a filesystem as an ISO

### ISSUE THREAD

**Issue by ThatOneStruggle** [PCSX2/pcsx2#784]
Would it be feasible to have a filesystem act as a ISO, like if you had all your files in a directory and there was an option to route the loader into there?

**Comment by refractionpcsx2** [comment]
Generally not no, the PS2 demands a certain order for files to be on a disc so they boot, if all files are extracted to an OS folder, you lose any sort of ordering.

**Comment by willkuer** [comment]
And keeping the order in a metafile?

**Comment by colejohnson66** [comment]
It has to do with how computers boot. They load the first, say, 2048 bytes off the disk. Those bytes are actual program code that tell the computer how to load the next phase of the bootstrap. It's the same reason you can't just copy your entire C: drive to another drive; the hard drive contains extra data that tells the computer how to load Windows.
