### ISSUE TITLE
Odd shadows in Hardware mode for Aqua team, Ninja golf

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#785]
"Evil dead"
http://imgur.com/SgGQ0w9

"Aqua team"
http://imgur.com/NDCRx0M

**Comment by refractionpcsx2** [comment]
In the case of Evil Dead, this is a lighting bug in HW Mode across all renderers as far as I'm aware, it looks fine in software mode

**Comment by karasuhebi** [comment]
@twarnercool2 Have you tried the software renderers or the OpenGL hardware renderer for Evil Dead?

**Comment by twarnercool2** [comment]
Software is fine, but it slows down the game a lot. Hardware has the odd shadows. Unless they fixed it very recently.

**Comment by karasuhebi** [comment]
What was the last version you tested using a hardware renderer? Did you try the OpenGL one? Also depending on your CPU, you can change the number of "Extra rendering threads" to help out with performance when using a software renderer. :)

**Comment by refractionpcsx2** [comment]
No HW renderer fixes it, it's pretty much a Texture Cache issue, but Software Mode is fine.

**Comment by MrCK1** [comment]
@twarnercool2 Can you restest these games on latest git build?

**Comment by tadanokojin** [comment]
Evil dead issue #3176 keeping open for aqua teen.

**Comment by Hemporus01** [comment]
[aqua teen hunger force graphical artifacts gsdump.zip](https://github.com/PCSX2/pcsx2/files/8166801/aqua.teen.hunger.force.graphical.artifacts.gsdump.zip)

**Comment by refractionpcsx2** [comment]
Quite possibly related to #55

**Comment by stenzek** [comment]
I've added the merge targets tex-in-rt mode for this game to #8271, from the GS dump it looks all good now. But I don't have the game to test.
