### ISSUE TITLE
[BUG]: PINE not working in Qt builds

### ISSUE THREAD

**Issue by sstarbright** [PCSX2/pcsx2#7851]
### Describe the Bug

It seems that the Qt builds of PCSX2 simply lack the ability to use PINE. I compared the most recent (1.7.3877) build of PCSX2 to the final wxWidgets build. That last wxWidgets build works with the PINE tool I created, but none of the Qt builds I have tried have worked. There is no option in the emulator to even enable PINE or set the port either. I tried looking in the .ini and found EnablePINE, but setting this to true still seemed to do absolutely nothing.

### Reproduction Steps

1. Open the config for PCSX2
2. Set EnablePINE to true
3. Run a game in PCSX2
4. Run a PINE tool

### Expected Behavior

PINE tools should be able to connect to PCSX2, allowing them to read and write data. This does not work in Qt builds.

### PCSX2 Revision

1.7.3877

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
We know it's missing, it'll come once Govanify has time to do it
