### ISSUE TITLE
[BUG]: USB - KeyboardMania controller bindings are incorrect

### ISSUE THREAD

**Issue by Nocosix** [PCSX2/pcsx2#7861]
### Describe the Bug

The KeyboardMania USB pad has incorrect bindings. There are no bindings for Start, Select, and Wheel up/down, there is a third C which does not exist on the controller, and only the bottom notes up until the first G activate the correct notes. This problem was introduced with the QT interface and worked properly in the WXWidgets one.

### Reproduction Steps

1) Set up bindings for a KeyboardMania USB controller
2) Test the controller in Keyboardmania or Keyboardmania II

### PCSX2 Revision

1.7.3888

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by stenzek** [comment]
Dunno why people mention wx, it's gone, and the code was rewritten.

**Comment by lightningterror** [comment]
@Nocosix Can you test https://github.com/PCSX2/pcsx2/pull/7864 and see if the issue is resolved?

**Comment by Nocosix** [comment]
The Select button is not working, but all the other buttons are now functional.

**Comment by stenzek** [comment]
Should be fine with the last push, silly button ordering..

**Comment by Nocosix** [comment]
It works now, thank you so much!
