### ISSUE TITLE
[Feature Request]: Separate memory cards per game

### ISSUE THREAD

**Issue by Leafdomain** [PCSX2/pcsx2#7871]
### Description

An option so that there would be a separate memory card file per game.

### Reason

This would make it so much easier to manage transferring saves. Instead of having to deal with external methods of transferring each save into the memory card, the memory card file itself could just be dragged in. Having it separated per game would make it incredibly easier to manage and so much more useful. The way it currently is lengthens the process as well as making it unnecessarily complicated.

### Examples

Duckstation has this exact feature.
When I want to import a full save for a particular game, I can just drag in the memory card file that I previously prepared, instead of dealing with importing it into the memory card each time and getting it mixed in with the other games.
I find this to be an incredibly useful feature in Duckstation, making the process seamless.

Furthermore, Dolphin works similarly as well as since it just saves the files into a folder, and I can just drag in a save file into the folder.

Thus, Pcsx2 having such a feature will also help this process of save management very much. I would recommend having it exactly like Duckstation works, just adding a togglable option that enables the emulator to save a separate memory card per game.

**Comment by stenzek** [comment]
No, we're not doing something like Duckstation. It makes sense for PS1 because cards are so small, not so much for PS2. Plus, folder memory cards basically achieve this.

You can already do this anyway - just have to manually set the path in the gamesettings ini.

Closing since I have no plans to implement this in the UI, though, someone else can re-open if they want to.

**Comment by TellowKrinkle** [comment]
Have you tried folder memory cards?

**Comment by Leafdomain** [comment]
Ah what are those, either folder memory cards or the gamesettings.ini? How is it done?
