### ISSUE TITLE
[BUG]: Controller Not Working

### ISSUE THREAD

**Issue by Shad0wBlad321** [PCSX2/pcsx2#7872]
### Describe the Bug

in the newest version at time of writing i cannot get any of my mainstream controllers to work no matter what i do. i tried a ps5 controller, ps4 controller, and an xbox one controller using the appropriate settings for each and even binding manually each button. the best i can get is the dpad on the ps5 controller, everything else is completely non functional

### Reproduction Steps

simply setting up a controller as normal

### Expected Behavior

controller works as if native ps2 controller

### PCSX2 Revision

1.7.3892

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Please use the Discord server for support, the issue tracker is for reporting bugs.

**Comment by Shad0wBlad321** [comment]
This is a bug, I have done everything correctly and it does not work in the newest version, only in older ones

**Comment by stenzek** [comment]
Then you'll need to specify exactly which version worked.

But given nobody else has this problem, I'm still going with it being a configuration issue.

**Comment by Shad0wBlad321** [comment]
I noticed no one else has the issue, it works perfectly in 1.6, just as expected, perhaps I am doing something wrong but I’m not new to this so I’m led to believe it’s some ultra rare bug. But out of respect for you as a developer making one of the best emulators I’ve used I will for now move to discord until I confirm it is a bug

**Comment by stenzek** [comment]
![image](https://user-images.githubusercontent.com/11288319/212256090-ad5dce6c-ae9c-4a09-a9e6-6217b649e173.png)
Works fine.

**Comment by Shad0wBlad321** [comment]
Fair enough, if I find a genuine bug causing this I will return, but it still isn’t working for me

**Comment by BT-TGD** [comment]
Yes I'm having the same issue here

**Comment by Shad0wBlad321** [comment]
I should probably clarify, I was actually just a retard, I didn’t realize I had to load my profile

**Comment by BT-TGD** [comment]
then it means that I have another issue ,,
the dualshock2 is available but when I press Automatic Mapping 
I get keyboard and mouse  I don't know if it's normal or not ?
if you know how fix this please let me know 
Thanks ..

**Comment by stenzek** [comment]
@BT-TGD As I said above, please use the Discord server for support, the issue tracker is for reporting bugs.
