### ISSUE TITLE
Metal rendering doesn't work on M1 pro (MacOS 13.1)

### ISSUE THREAD

**Issue by matgaj** [PCSX2/pcsx2#7874]
### Describe the Bug

When set to Metal rendering, the emulation doesn't even start when I double click a game. A window appears and instantly disappears. Vulkan and Software seem to be fine. I tested MGS 3 and SH 3 since that's all I have downloaded. I'm on a MacBook Pro 14".

### Reproduction Steps

Set rendered to Metal
Double click game title

### Expected Behavior

Game launches normally (which is the case with Vulkan)

### PCSX2 Revision

1.7.3892

### Operating System

macOS 13 (Ventura)

### CPU

M1 pro

### GPU

M1 pro

**Comment by Mrlinkwii** [comment]
use 1.7.3896

**Comment by stenzek** [comment]
This was already fixed in https://github.com/PCSX2/pcsx2/commit/a2e3522862fee783a023cb1ee7662e475c96b17d.

It just hasn't released because the ubuntu package repository that the CI uses is pretty broken at the moment.
