### ISSUE TITLE
[Feature Request]: Opencl support

### ISSUE THREAD

**Issue by Oymat** [PCSX2/pcsx2#7879]
### Description

I want to request the pcsx2 staff to add support for Opencl as a gs renderer.

### Reason

It will be good for people using their cpu as a render device as it will make performance very good for them

### Examples

Can't think of any.

**Comment by stenzek** [comment]
.. no. While it's theoretically possible, Vulkan would be a much better choice for a compute-based renderer, and none of us have any interest in the monumental task of writing one.

Scheduling/handling hazards is the trickiest part.
