### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by PrototypeAdvanced** [PCSX2/pcsx2#7883]
### Describe the Bug

PCSX2 keeps force closing after adding a hard-drive to the scan directory. 

### Reproduction Steps

Added my hard-drive to the scan directory,  the emulator keeps force closing since.

Note: i had no issues scanning folders, but adding the hard-drive (ssd 1TB) was apparently too much, or at least there's a bug that makes PCSX2 force close. 

Fixed for now by deleting PCSX2 and install it again. 

### Expected Behavior

That i would be able to keep using PCSX2 after adding a hard-drive to the scan directory. 

### PCSX2 Revision

v.1.7.3900 windows AVX2

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
>Note: i had no issues scanning folders, but adding the hard-drive (ssd 1TB) was apparently too much, or at least there's a bug that makes PCSX2 force close.

no it found  a file it didnt like and then forced closed , this is user error , please make sure the folder you scan only has your games in it

**Comment by stenzek** [comment]
Then don't do it?

It's probably CDVD choking on some invalid files, it's not exactly robust code.

But it's not really an issue anyway, unless you want PCSX2 to take ages to start up while it iterates through every directory on your hard drive.
