### ISSUE TITLE
[BUG]: Game cursor stuck on the edges of the screen on games with mouse support

### ISSUE THREAD

**Issue by bruwyvn** [PCSX2/pcsx2#7887]
### Describe the Bug

I've mapped my mouse and keyboard on the Controller Settings to both of the USB ports for playing FFVII - Dirge of Cerberus. At first I only could map one axis to the pointer, but managed to do both editing the INI file. But when playing the cursor keeps moving on the screens' edges. The same error is reproducible on AOE II too.

### Reproduction Steps

- Enable Mouse Mapping in Global Settings;
- Change the USB Ports' device types to HID Mouse and HID Keyboard (the port order doesn't matter);
- Map the mouse buttons accordingly (L/R/Middle-Click);
- Verify the pointers axes names by my mapping and unmapping the mouse movement (should be Pointer-0 and Pointer-1);
- Edit `PCSX2.ini` so both axes are mapped:
``` ini
# PCSX2.ini
[USB1] # or [USB2] based on the order
Type = hidmouse
hidmouse_LeftButton = Pointer-0/LeftButton
hidmouse_RightButton = Pointer-0/RightButton
hidmouse_MiddleButton = Pointer-0/MiddleButton
hidmouse_Pointer = Pointer-0 
hidmouse_Pointer = Pointer-1
```

### PCSX2 Revision

v1.7.3892 (flatpak) v1.7.3902 (appImage)

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Fedora 37 Workstation (64-bit)

**Comment by refractionpcsx2** [comment]
why are you enabling mouse mapping AND USB mouse? That shouldn't be possible, since you can't control the right analog with a mouse and a USB mouse at the same time.

**Comment by bruwyvn** [comment]
@refractionpcsx2 that was the only way to get the cursor to at least move.

**Comment by refractionpcsx2** [comment]
Apparently I've been told they are linked and you need that option for USB mouse, so my bad.

**Comment by bruwyvn** [comment]
Did some testing and the bug only occurs on Wayland, on X.Org is working fine. Editing the configuration file is not necessary but you have map the pointer with the primary mouse button instead of sliding the mouse

**Comment by xDShot** [comment]
add `QT_QPA_PLATFORM=xcb` env var to make it work in Wayland

**Comment by stenzek** [comment]
No longer an issue since #10179, since Wayland is disabled by default.
