### ISSUE TITLE
[Feature Request]: onscreen Targeting reticule when Guncon 2 mode is enabled for USB

### ISSUE THREAD

**Issue by PABastien1** [PCSX2/pcsx2#7891]
### Description

A simple targeting reticule or crosshairs that appear on screen when Guncon mode is enabled in the USB settings, allowing you to see where you are aiming without having to unlock the mouse while playing games

### Reason

Due to the size of an average mouse icon, it can be hard to see where you are aiming at times in light gun games. By having a larger targeting reticule, it can be hard to see where you are aiming. A targeting reticule can also help players have a more seamless game experience as well, I believe.
Also, by having it be 2 separate reticule colours based on which usb port it is assigned to, this allows for possible 2 player guncon games to be playable.
This also might help for folks using a wiimote or or joycon gyro controls as a mouse pointer, which allows them the ability to use the controllers as a mock lightgun.

### Examples

I believe such a mode is activated when Guncon 1 and Justifier mode is enabled in duckstation
Certain versions of Melon DS (definitely in retroarch, not sure about standalone) have an onscreen reticule  to indicate where you are aiming/touching the second screen.
I believe Mame also has this for light gun games, but I can not recall exactly.

**Comment by Bitwolfies** [comment]
It's very odd cause according to[ this video](https://youtu.be/pDnRdlaraV4?t=268) (timestamped) there is a target, yet I cannot for the life of me make it appear, cant see my mouse either as it disappears into the window.

**Comment by bronzebrow** [comment]
@Bitwolfies I think that timestamp crosshair is specific to Time Crisis 2's calibration screen. It doesn't stick around for the full length of the game and it's not a standard feature of ps2.

However for TC2 specifically, if you use a controller or ps2 mouse as your USB device instead of Guncon, you should see a crosshair.

**Comment by PABastien1** [comment]
Yep. All guncon games when played in controller mode have a crosshair.
and @Bitwolfies those crosshairs only happen on a specific screen after you calibrate.
