### ISSUE TITLE
[BUG]: Cannot update nightly release v1.7.3902 to v1.7.3905, complains of missing staging output Debugger.pdf file

### ISSUE THREAD

**Issue by nawarnoori** [PCSX2/pcsx2#7897]
### Describe the Bug

I downloaded the latest nightly release (v1.7.3902) the other day, tried to update this morning, fails with:

![image](https://user-images.githubusercontent.com/27728412/212540479-ff405cfa-4bff-46be-b3aa-3619a3848698.png)

### Reproduction Steps

Be on v1.7.3902, accept this update:

![image](https://user-images.githubusercontent.com/27728412/212540575-8736184c-f285-4aeb-a5cd-9a6f54428133.png)

### Expected Behavior

The update completes successfully

### PCSX2 Revision

v1.7.3902

### Operating System

Windows 10 (64bit)

**Comment by Toastarrr** [comment]
Shot in the dark, but do you have protected folders enabled in Windows? Documents is one of the default folders it protects.

**Comment by RedDevilus** [comment]
As side-fix you could try deleting Debugger.pdf as permissions or something saved itself. Next update should get the pdf again.

**Comment by nawarnoori** [comment]
> Shot in the dark, but do you have protected folders enabled in Windows? Documents is one of the default folders it protects.

Looks like that was it, but normally I've not had issues updating other apps in Documents, plus it seemed to have got some way through before it failed, so I assumed it expected a file that was not there (before the update Debugger.pdf wasn't in that directory), since it looks like a me problem I will close, thanks for the help!
