### ISSUE TITLE
[Feature Request]: Port clean-room BIOS/firmware from Play! emulator

### ISSUE THREAD

**Issue by hardBSDk** [PCSX2/pcsx2#7898]
### Description

Play! emulator have a working clean-room BIOS, PCSX2 being the most mature PS2 emulator of the world, still relies on proprietary BIOS from original PS2.

https://purei.org/
https://github.com/jpd002/Play-

Improvement: the user don't need to dump BIOS files anymore.

### Reason

Less bugs with a rewritten BIOS and ease emulation configuration.

### Examples

Play!
PCSX ReARMed
PPSSPP

**Comment by refractionpcsx2** [comment]
Play! doesn't have a BIOS, it's all HLE'd and along with that it has a lot of baggage with having to write custom code to get every game to work, so we're not going down that route.

There needs to be a proper 3rd party file which replaces the BIOS properly, and if somebody wants to do that (clean room of course), they are welcome to.

**Comment by Oymat** [comment]
If pcsx2 did that, they'd be getting false issue reports left and right. so i hope you understand @hardBSDk

**Comment by RedDevilus** [comment]
Compatibilty would drop a lot too just like play. And all games needing patched to even run or work properly compared to the few now. Hence why the low priority on it.

More effort for dumping games as you need to do it multiple times vs once for BIOS dumping.

**Comment by hardBSDk** [comment]
@refractionpcsx2 @RedDevilus What you think about it?

https://github.com/Ravenslofty/biostation

I don't know if PCSX2 has an ongoing effort to clean-room the BIOS, it would put the emulator on the same level of PCSX ReARMed, Flycat and PPSSPP.

**Comment by stenzek** [comment]
We don't, nor is there any plans. There's much more important issues than a low-compatibility effort at making it easier for people to pirate games. Of course you're welcome to work on one yourself.

Asking users to have a PS2 console to dump a BIOS from isn't a big deal, considering it's unlikely you'd have a bunch of PS2 games with no console to go with them.
