### ISSUE TITLE
interface language is not selected

### ISSUE THREAD

**Issue by crazydownload** [PCSX2/pcsx2#7903]
### Describe the Bug

in the new launcher, the interface language is not selected. There is no drop-down menu on the Settings-> Interface tab, as if the languages ​​are not updated, although there are files in the folder [Click](https://i.imgur.com/hX1XGFK.png)
[translation folder as you can see is not empty](https://i.imgur.com/vhPYUuQ.png)

### Reproduction Steps

I don’t know what to write here, I just click the settings interface and there is no choice of languages

### PCSX2 Revision

PCSX2 Nightly - v1.7.3877

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Not a bug, there is no languages yet, they are coming.

**Comment by crazydownload** [comment]
I see, well, maybe they are from the old version of the emulator that was before the new launcher

**Comment by refractionpcsx2** [comment]
I have to mildly apologise, the files *are* in the builds, that was my mistake, but translations are still not ready to be done/or work, so the original result still stands, but the files are from the emulator, my bad.
