### ISSUE TITLE
[Feature Request]: Go to the nearest branch or jump instruction that skips this instruction

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#7907]
### Description

This is a new action for the context menu that appears after right clicking any MIPS instruction in the disassembly view of the debugger of PCSX2.

This action simply goes to the nearest branch or jump instruction that skips the right clicked MIPS instruction if the branch is taken.

Of course that the debugger cannot know how far is this nearest branch or jump instruction from the right clicked MIPS instruction.

Therefore the debugger will assume that the distance of that nearest branch or jump instruction from the right clicked MIPS instruction is not greater than 100 MIPS instructions.

This means that once the user clicks "Go to the nearest branch or jump instruction that skips this instruction" action then starting from the right clicked MIPS instruction the debugger will start to go back to the previous/above MIPS instruction over and over again until the debugger finds any branch or jump instruction that skips the right clicked MIPS instruction if the branch is taken.

The debugger will also count the number of times that the debugger goes back to the previous/above MIPS instruction and when this count reaches 100 then the debugger stops and does a "Step Out" operation to find the `jal` or `jalr` instruction that invoked the function that contains the right clicked MIPS instruction.

In case the call instruction is `jal` and not `jalr` then the debugger uses the same algorithm to find the nearest branch or jump instruction that skips that `jal` instruction if the branch is taken and if after another 100 times going back to the previous/above MIPS instruction that the debugger did not find any branch or jump instruction that it was looking for then again do another "Step Out" and after that all what I described above is repeated.

The debugger won't do more than 3 steps out.

If after the third step out the debugger did not find the branch or jump instruction that the debugger was looking for then the debugger will notify it's user that the debugger failed to find the branch or jump instruction that skips the right clicked MIPS instruction and that's it.

In case the call instruction is `jalr` then same thing because a `jalr` instruction may invoke more than one function and this can be unsafe to always skip a `jalr` instruction in general.

Always skipping a `jalr` instruction might make the game completely unplayable.

If you want you can give the user new options to change these numbers so that the maximum number of times that the debugger goes up to the previous/above MIPS instruction is not always 100 and the maximum number of times that the debugger steps out is not always 3.

In addition to "Go to the nearest branch or jump instruction that skips this instruction" you can add another two actions to the context menu of the disassembly view:

1. "Find the nearest branch or jump instruction that skips this instruction and make it unconditional".

2. "Find the nearest branch or jump instruction that skips this instruction and make it NOP".

Both do the same as "Go to the nearest branch or jump instruction that skips this instruction" but after that 1. also make the instruction unconditional branch if the debugger found skipping instruction and skipping instruction is a conditional branch, like `beq`, `bne`, `beql`, `bnel`, `beqz` and etc, while the other 2. simply makes it a `nop` instruction.

### Reason

This feature can be useful to easily and quickly make an invulnerability cheat in the game by easily and quickly find the conditional branch instruction that checks whether or not the character that you play with is hurt and if yes then damage him or her and at last replace it with either unconditional branch or NOP so that the code that damages the character that you play with is always skipped.

Note that invulnerability does not only mean that the character that you play with does not lose health on hit but in fact it means that the character that you play with is never hurt and this means that you will never see his or her pain animation and you will never hear him or her shouts if he or she gets hurt because he or she never gets hurt.

If you are invulnerable then all enemy attacks go through you like that you are a ghost that can go through walls.

This also means that you cannot be stunned and etc.

Just NOPing the `sw` instruction that decreases your health will not prevent the character that you play with to shout when he or she gets hurt nor being stunned.

### Examples

Let's begin a new game in Devil May Cry.

Let's make progress while there is no enemies to fight that attack Dante.

Before fighting the first enemies in the game let's find out the memory address of his health.

Unfortunately the health of Dante is drawn in a bar and thus I don't know the initial value of his health

Assuming that #7696 is implemented our first scan is going to be "Unknown initial value".

Now let's begin the first fight in the game and let the enemies hurt Dante.

Every time that Dante loses health our next scan is going to be "Decreased value" repeatedly until the address of his health is found.

Once the address of his health is found then just put a write breakpoint there and wait for the enemy to hurt Dante one more time.

Now the game should pause on the `sw` instruction that updates Dante health.

In this example the `sw` instruction decreases his health.

If I NOP this instruction (replacing it with a code that does nothing) then Dante won't lose health anymore when he will get hurt again but you will still hear him shout and you won't be able to control Dante until he is recovered from the enemy attack.

If you don't want this then you need to find the conditional branch instruction that checks whether or not Dante is hurt and if the branch is taken then the `sw` instruction that updates Dante's health is skipped.

To find this conditional branch instruction simply right click the `sw` instruction that updates Dante's health that you found with a write breakpoint and click on the "Find the nearest branch or jump instruction that skips this instruction and make it unconditional".

If the debugger will succeed to do this then from now on Dante is invulnerable and he does no longer get hurt from enemy attacks.

You will see that all enemy attacks go through him like that Dante is a ghost though Dante is still unable to go through walls.

For that you will have to work much harder.

If the Debugger was unsuccessful then either increase the numbers of going back and steps out or just manually scroll up or step out until you find it in the disassembly view of the debugger and at last use "Assemble new instruction(s)" to make it unconditional branch.

Note that there may be cases where you will have to make it NOP instead so if the "... make it unconditional" did not work for you then don't forget to try the "... make it NOP".

You can always manually at last use the "NOP Instruction(s)" new feature instead of "Assemble new instruction(s)" in case "... make it NOP" also failed.

This is not guaranteed that this feature will be successful in all cases but I believe that this feature will prove successful in most cases and so I believe that this is worth to implement it to make the debugger even more user friendly and easier to use.

**Comment by stenzek** [comment]
I didn't read this long essay but any sort of counting or complex tracking of positioning is not possible in the recs.

What you probably want is a scripting interface. And it'll be slow as heck for execution.

Imo close.
