### ISSUE TITLE
[BUG]: Rimokokoron(SCPS-11012) "Sony Computer Entertainment Inc. Presents" screen only shows up in Software Renderer

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#7923]
### Describe the Bug

 "Sony Computer Entertainment Inc. Presents" screen only shows up in Software Renderer

Others:
![Rimoko Koron_SCPS-11012_20230118144234](https://user-images.githubusercontent.com/121824800/213623223-3018aaa7-321f-457f-b4b5-068b1cfabe97.png)
Software Renderer:
![Rimoko Koron_SCPS-11012_20230118144303](https://user-images.githubusercontent.com/121824800/213623229-87e99a70-e031-43da-a721-3a4d86a8104c.png)

### Reproduction Steps

Boot up the game with Non-Software Renderer.

### Expected Behavior

as shown above.

### PCSX2 Revision

Nightly v1.7.3918

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### GS Settings

default.
Enabled "Preload Frame Data", but nothing changed.

### Emulation Settings

default.

### GS Window Screenshots

default.

### Logs & Dumps

GSdump:
[Rimoko Koron_SCPS-11012_SCEIPscreen.gs.zip](https://github.com/PCSX2/pcsx2/files/10463442/Rimoko.Koron_SCPS-11012_SCEIPscreen.gs.zip)

**Comment by Oymat** [comment]
Disable safe features seems to fix it, though i cannot add it to the GameDB due to it not supporting it.

**Comment by RedDevilus** [comment]
Yeah, that's a mix of multiple things in one checkbox. But not really a good fix as it can break other things further in games.

**Comment by Oymat** [comment]
> I tried it and now it's fixed.

if it doesn't break anything maybe we can get ref to add support for it in the gameindex

**Comment by SeruranBlue** [comment]
> if it doesn't break anything maybe we can get ref to add support for it in the gameindex

I gonna test entire games.

**Comment by SeruranBlue** [comment]
I reached ending and i found several issues.



In software renderer with all default settings, if zooming out maximaumly, the game speed slows down.
This issue doesn't occur with non-software renderer.

- stage 6: 45FPS (75%)
- stage 5: 50FPS (80%)
- stage 2: 43FPS (70%)

There is a chance that captured image turn into another image. this sometimes occurs when you push F9 (change renderer) or F4 (toggle frame limitter) or tab (Turbo),regardless renderer or Disable safe features.

![Rimoko Koron_SCPS-11012_20230121145733](https://user-images.githubusercontent.com/121824800/213846111-d51e2ef2-b7a3-4a0b-8c4d-fa84051cce88.png)

there are no other problems.

**Comment by Oymat** [comment]
> I reached ending and i found several issues.
> 
> In software renderer with all default settings, if zooming out maximaumly, the game speed slows down. This issue doesn't occur with non-software renderer.
> 
> * stage 6: 45FPS (75%)
> * stage 5: 50FPS (80%)
> * stage 2: 43FPS (70%)
> 
> There is a chance that captured image turn into another image. this sometimes occurs when you push F9 (change renderer) or F4 (toggle frame limitter) or tab (Turbo) after captureing the image, regardless of whether renderer or Disable safe features.
> 
> ![Rimoko Koron_SCPS-11012_20230121145733](https://user-images.githubusercontent.com/121824800/213846111-d51e2ef2-b7a3-4a0b-8c4d-fa84051cce88.png)
> 
> there are no other problems.

Software will always be slower, that's not a problem.

**Comment by SeruranBlue** [comment]
In case if you want an GS dump about corrupt images
[RimokoKoron_corruptimage.gs.zip](https://github.com/PCSX2/pcsx2/files/10472478/RimokoKoron_corruptimage.gs.zip)

**Comment by refractionpcsx2** [comment]
As I suspected, it is using scanmsk, so I've excluded that from our fast clear, since that would be invalid behaviour anyway #7933
