### ISSUE TITLE
[BUG]: Core Dumped, when I'm tring to run a PS2 game

### ISSUE THREAD

**Issue by visious25** [PCSX2/pcsx2#7954]
### Describe the Bug

Hi. Pcsx2 never worked for me. When I'm tring to run a PS2 game. I'm getting this in terminal:

$ pcsx2-qt
Program Path: /usr/bin/pcsx2-qt
AppRoot Directory: /usr/bin
DataRoot Directory: /home/visious/.config/PCSX2
Resources Directory: /usr/share/PCSX2/resources
Loading config from /home/visious/.config/PCSX2/inis/PCSX2.ini.
BIOS Directory: /home/visious/.config/PCSX2/bios
Snapshots Directory: /home/visious/.config/PCSX2/snaps
Savestates Directory: /home/visious/.config/PCSX2/sstates
MemoryCards Directory: /home/visious/.config/PCSX2/memcards
Logs Directory: /home/visious/.config/PCSX2/logs
Cheats Directory: /home/visious/.config/PCSX2/cheats
CheatsWS Directory: /home/visious/.config/PCSX2/cheats_ws
CheatsNI Directory: /home/visious/.config/PCSX2/cheats_ni
Covers Directory: /home/visious/.config/PCSX2/covers
Game Settings Directory: /home/visious/.config/PCSX2/gamesettings
Cache Directory: /home/visious/.config/PCSX2/cache
Textures Directory: /home/visious/.config/PCSX2/textures
Input Profile Directory: /home/visious/.config/PCSX2/inputprofiles
Unhandled page fault @ 0x00000000/home/visious/.cache/yay/pcsx2/src/pcsx2/common/Linux/LnxHostSys.cpp:97: assertion failed in function void SysPageFaultSignalFilter(int, siginfo_t*, void*): Unhandled page fault

Aborting application.
Aborted (core dumped)
---------------------------------------------------------------------------------------------
when I hit in terminal "sudo journalctl -p 3 -xb"

Jan 24 08:31:32 archlinux systemd-coredump[3415116]: [🡕] Process 3414010 (pcsx2-qt) of user 1000 dumped core.
                                                     
                                                     Module libnvidia-eglcore.so.340.108 without build-id.
                                                     Module libGLESv2.so.2 without build-id.
                                                     Module libnvidia-glsi.so.340.108 without build-id.
                                                     Module libEGL.so.1 without build-id.
                                                     Stack trace of thread 3415081:
                                                     #0  0x00007f80f20a164c n/a (libc.so.6 + 0x8864c)
                                                     #1  0x00007f80f2051938 raise (libc.so.6 + 0x38938)
                                                     #2  0x00007f80f203b53d abort (libc.so.6 + 0x2253d)
                                                     #3  0x000055dd9e5d5139 n/a (pcsx2-qt + 0xf3139)
                                                     #4  0x000055dd9ed8c1ae n/a (pcsx2-qt + 0x8aa1ae)
                                                     #5  0x000055dd9edac3e0 n/a (pcsx2-qt + 0x8ca3e0)
                                                     #6  0x00007f80f20519e0 n/a (libc.so.6 + 0x389e0)
                                                     
                                                     Stack trace of thread 3414025:
                                                     #0  0x00007f80f211437f __poll (libc.so.6 + 0xfb37f)
                                                     #1  0x00007f80f0a4326b n/a (libxcb.so.1 + 0xd26b)
                                                     #2  0x00007f80f0a44d1d xcb_wait_for_event (libxcb.so.1 + 0xed1d)
                                                     #3  0x00007f80eb5b1362 n/a (libQt6XcbQpa.so.6 + 0x4e362)
                                                     #4  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414047:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f20a76a0 n/a (libc.so.6 + 0x8e6a0)
                                                     #2  0x000055dd9ed9a44e n/a (pcsx2-qt + 0x8b844e)
                                                     #3  0x000055dd9e67796a n/a (pcsx2-qt + 0x19596a)
                                                     #4  0x000055dd9edac9ac n/a (pcsx2-qt + 0x8ca9ac)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414064:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f209efd4 pthread_cond_timedwait (libc.so.6 + 0x85fd4)
                                                     #2  0x00007f80f288ba0b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28ba0b)
                                                     #3  0x00007f80f2886895 n/a (libQt6Core.so.6 + 0x286895)
                                                     #4  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414045:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f20a76a0 n/a (libc.so.6 + 0x8e6a0)
                                                     #2  0x000055dd9e67657d n/a (pcsx2-qt + 0x19457d)
                                                     #3  0x000055dd9ea65617 n/a (pcsx2-qt + 0x583617)
                                                     #4  0x000055dd9eae426e n/a (pcsx2-qt + 0x60226e)
                                                     #5  0x000055dd9eaa6f18 n/a (pcsx2-qt + 0x5c4f18)
                                                     #6  0x00007f80f276bd00 _ZN7QObject5eventEP6QEvent (libQt6Core.so.6 + 0x16bd00)
                                                     #7  0x00007f80f3f759bc _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0>
                                                     #8  0x00007f80f272a258 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x12a>
                                                     #9  0x00007f80f272a42b _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt6Co>
                                                     #10 0x00007f80f294f348 n/a (libQt6Core.so.6 + 0x34f348)
                                                     #11 0x00007f80f151687b g_main_context_dispatch (libglib-2.0.so.0 + 0x5587b)
                                                     #12 0x00007f80f156dc89 n/a (libglib-2.0.so.0 + 0xacc89)
                                                     #13 0x00007f80f1515132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                                                     #14 0x00007f80f294d382 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlag>
                                                     #15 0x00007f80f2735604 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x135604)
                                                     #16 0x000055dd9eae4c4c n/a (pcsx2-qt + 0x602c4c)
                                                     #17 0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #18 0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #19 0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414065:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f209efd4 pthread_cond_timedwait (libc.so.6 + 0x85fd4)
                                                     #2  0x00007f80f288ba0b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28ba0b)
                                                     #3  0x00007f80f2886895 n/a (libQt6Core.so.6 + 0x286895)
                                                     #4  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414066:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f209efd4 pthread_cond_timedwait (libc.so.6 + 0x85fd4)
                                                     #2  0x00007f80f288ba0b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28ba0b)
                                                     #3  0x00007f80f2886895 n/a (libQt6Core.so.6 + 0x286895)
                                                     #4  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414067:
                                                     #0  0x00007f80f209c4b6 n/a (libc.so.6 + 0x834b6)
                                                     #1  0x00007f80f209efd4 pthread_cond_timedwait (libc.so.6 + 0x85fd4)
                                                     #2  0x00007f80f288ba0b _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28ba0b)
                                                     #3  0x00007f80f2886895 n/a (libQt6Core.so.6 + 0x286895)
                                                     #4  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #5  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #6  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414046:
                                                     #0  0x00007f80f211437f __poll (libc.so.6 + 0xfb37f)
                                                     #1  0x00007f80f156dbef n/a (libglib-2.0.so.0 + 0xacbef)
                                                     #2  0x00007f80f1515132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                                                     #3  0x00007f80f294d382 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlag>
                                                     #4  0x00007f80f2735604 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x135604)
                                                     #5  0x00007f80f281d778 _ZN7QThread4execEv (libQt6Core.so.6 + 0x21d778)
                                                     #6  0x00007f80f143a11f n/a (libQt6DBus.so.6 + 0x2d11f)
                                                     #7  0x00007f80f2885a21 n/a (libQt6Core.so.6 + 0x285a21)
                                                     #8  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #9  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414048:
                                                     #0  0x00007f80f211437f __poll (libc.so.6 + 0xfb37f)
                                                     #1  0x00007f80e82b0a95 n/a (libusb-1.0.so.0 + 0xca95)
                                                     #2  0x00007f80f209f8fd n/a (libc.so.6 + 0x868fd)
                                                     #3  0x00007f80f2121d20 n/a (libc.so.6 + 0x108d20)
                                                     
                                                     Stack trace of thread 3414010:
                                                     #0  0x00007f80f211437f __poll (libc.so.6 + 0xfb37f)
                                                     #1  0x00007f80f156dbef n/a (libglib-2.0.so.0 + 0xacbef)
                                                     #2  0x00007f80f1515132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                                                     #3  0x00007f80f294d382 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlag>
                                                     #4  0x00007f80f2735604 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x135604)
                                                     #5  0x00007f80f272ce7b _ZN16QCoreApplication4execEv (libQt6Core.so.6 + 0x12ce7b)
                                                     #6  0x000055dd9e5e0d17 n/a (pcsx2-qt + 0xfed17)
                                                     #7  0x00007f80f203c290 n/a (libc.so.6 + 0x23290)
                                                     #8  0x00007f80f203c34a __libc_start_main (libc.so.6 + 0x2334a)
                                                     #9  0x000055dd9e5e1de5 n/a (pcsx2-qt + 0xffde5)
                                                     ELF object binary architecture: AMD x86-64
░░ Subject: Process 3414010 (pcsx2-qt) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 3414010 (pcsx2-qt) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.

### Reproduction Steps

I don't know.

### PCSX2 Revision

v1.7.3753

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

Arrandale (Core i3)

### GPU

GT218M [GeForce G 105M]

**Comment by Mrlinkwii** [comment]
are you using the appimage ?

**Comment by visious25** [comment]
No, the community [package](https://aur.archlinux.org/packages/pcsx2).

**Comment by kenshen112** [comment]
I sensened the disturbance in the force

**Comment by kenshen112** [comment]
Can you go here, https://aur.archlinux.org/packages/pcsx2-git I'll be able to get you figured out if you can comment in there

**Comment by Mrlinkwii** [comment]
please use the appimage @visious25

**Comment by refractionpcsx2** [comment]
We don't support the packages, please use the app image as mentioned above.

If you require help with the appimage, please visit our discord, the github is not the place for support.

**Comment by visious25** [comment]
I switched to [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git)  I have the same results.

**Comment by kenshen112** [comment]
Ok, then there's something I need to fix. If you guys could, post in the above. Or email me I'll be happy to get this figured out.

**Comment by stenzek** [comment]
Which part of "we don't support the packages" is unclear?

Obviously the package is broken, because the appimage works fine. But we have no control over that.

**Comment by TheLastRar** [comment]
> No, the community [package](https://aur.archlinux.org/packages/pcsx2).

Didn't know that the official Arch package got demoted to an community/AUR.
