### ISSUE TITLE
[BUG]: Core Dumped, when I'm tring to run a PS2 game (AppImage)

### ISSUE THREAD

**Issue by visious25** [PCSX2/pcsx2#7955]
### Describe the Bug

Hi again. Pcsx2 (AppImage) never worked for me. When I'm tring to run a PS2 game. I'm getting this in terminal:

$ ./pcsx2-v1.7.3950-linux-AppImage-64bit-SSE4-Qt.AppImage 
Program Path: /tmp/.mount_pcsx2-a9nDqy/usr/bin/pcsx2-qt
AppRoot Directory: /tmp/.mount_pcsx2-a9nDqy/usr/bin
DataRoot Directory: /home/visious/.config/PCSX2
Resources Directory: /tmp/.mount_pcsx2-a9nDqy/usr/bin/resources
Loading config from /home/visious/.config/PCSX2/inis/PCSX2.ini.
BIOS Directory: /home/visious/.config/PCSX2/bios
Snapshots Directory: /home/visious/.config/PCSX2/snaps
Savestates Directory: /home/visious/.config/PCSX2/sstates
MemoryCards Directory: /home/visious/.config/PCSX2/memcards
Logs Directory: /home/visious/.config/PCSX2/logs
Cheats Directory: /home/visious/.config/PCSX2/cheats
CheatsWS Directory: /home/visious/.config/PCSX2/cheats_ws
CheatsNI Directory: /home/visious/.config/PCSX2/cheats_ni
Covers Directory: /home/visious/.config/PCSX2/covers
Game Settings Directory: /home/visious/.config/PCSX2/gamesettings
Cache Directory: /home/visious/.config/PCSX2/cache
Textures Directory: /home/visious/.config/PCSX2/textures
Input Profile Directory: /home/visious/.config/PCSX2/inputprofiles
Video Dumping Directory: /home/visious/.config/PCSX2/videos
Unhandled page fault @ 0x00000000../common/Linux/LnxHostSys.cpp:97: assertion failed in function void SysPageFaultSignalFilter(int, siginfo_t *, void *): Unhandled page fault

Aborting application.
Aborted (core dumped)

### Reproduction Steps

I don't know. I have the same results like community packages [pcsx2](https://aur.archlinux.org/packages/pcsx2) and [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git) to my previous [issue](https://github.com/PCSX2/pcsx2/issues/7954)

### PCSX2 Revision

v1.7.3950

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

Arrandale (Core i3)

### GPU

GT218M [GeForce G 105M]

**Comment by refractionpcsx2** [comment]
As I said in the previous thread, the github is not for support, if you have an issue, please visit our discord. 

Thanks.

**Comment by visious25** [comment]
That about the AppImage? Is not working too.

**Comment by Mrlinkwii** [comment]
@visious25 can you join the discord https://discord.com/invite/TCz3t9k :smile:

**Comment by visious25** [comment]
I'm [in](https://discord.com/invite/TCz3t9k). Could you plese open this issue again?

**Comment by Mrlinkwii** [comment]
@visious25 ask for help in unix-help on discord, n
