### ISSUE TITLE
[BUG]: Virtua Fighter 4 (Pai location flickering)

### ISSUE THREAD

**Issue by KamiLordus** [PCSX2/pcsx2#7959]
### Describe the Bug

The Pai location (aquarium) suffers from very noticeable flickering textures. The flickering can be noticed already during the presentation of the fighters, and later during the fight.
I leave a video showing the problem.
If possible please fix this issue.

https://www.youtube.com/watch?v=jusiHW424Xc

### Reproduction Steps

Activate the Arcade mode and reach the 3rd location (Pai - aquarium).

### PCSX2 Revision

1.7.3951

### Operating System

Windows 11

### CPU

I7 8700k

### GPU

GTX 1070

**Comment by Mrlinkwii** [comment]
gs dump ?

**Comment by KamiLordus** [comment]
[Virtua Fighter 4_SLUS-20323_20230124223402.zip](https://github.com/PCSX2/pcsx2/files/10494208/Virtua.Fighter.4_SLUS-20323_20230124223402.zip)

I hope I did it right.
I will only add that the error appears in Hardware and Software mode.

**Comment by Oymat** [comment]
I'll take a while guess and say that it's probably related to either VU0 or FPU

**Comment by Mrlinkwii** [comment]
#5893
