### ISSUE TITLE
[BUG]: Landscape (flipped) in full screen is not working right on secondary monitor set to Extend

### ISSUE THREAD

**Issue by ionGL** [PCSX2/pcsx2#7966]
### Describe the Bug

I have a portable **secondary** monitor connected via hdmi that i use in landscape mode, but flipped. From nvidia control panel, rotate display - Landscape (flipped). Everything works just fine.

But in pcsx2, when you go full screen, the image is displayed as landscape normal. When you toggle from full screen to windowed mode, the image is oriented correctly, as selected in nvidia control panel.

### Reproduction Steps

Have a secondary monitor set to extend, rotate display, set it to landscape flipped in nvidia control panel, go full screen.

### Expected Behavior

The full screen image orientation should correspond to what's selected in control panel.

### PCSX2 Revision

v.17.3959

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
change your primary display :slightly_smiling_face:

**Comment by ionGL** [comment]
Right, this monitor with the full screen issue is used as a secondary monitor, winkey+p --> extend.
I can get it right for full screen on it if i make it the only screen active, but i have to not use the main monitor.

**Comment by ionGL** [comment]
I found a fix!

It works as it should if i use Direct3D 11, 12, or Software.

Using Vulkan or OpenGL flips the full screen image based on main monitor's orientation

If i go with landscape flipped on the main monitor too, the full screen image is as desired on the secondary one, even on Vulkan and OpenGL

**Comment by stenzek** [comment]
Sounds like a driver issue - such things are out of our control. We just use an identity rotation on the swap chain, probably the same as almost every other application.

You could try changing the vulkan presentation mode in nvidia control settings I guess.

**Comment by ionGL** [comment]
Well this is embarrassing for me, as this is indeed a driver issue. 

This "Vulkan/OpenGL present method" was relatively recently introduced and i was using an older nvidia driver until yesterday. Now every vulkan/opengl using app does the same thing in full screen. Selecting any option there does not fix this. Must wait for others to report it and nvidia to repair it in the future.

![vulkan opengl present method](https://user-images.githubusercontent.com/80151979/214829220-210f5725-6438-4666-a377-92005ffb4ba0.jpg)
