### ISSUE TITLE
[Feature Request]: Hotkey to invert joysticks

### ISSUE THREAD

**Issue by ZeptoBST** [PCSX2/pcsx2#7968]
### Description

The idea is to have a hotkey that can invert and de-invert either sticks, alongside options (such as "X only", "Y only" and "Both").

### Reason

Some games, like Sly Cooper 1 and 2, do not feature the ability to invert the right joystick in-game.

No problem, it's possible to do so in PCSX2.

However, these games feature twin-stick shooter sections where you must rotate the right stick 360 degrees to shoot projectiles, and if you inverted the joystick in PCSX2, then these sections become nightmares.

### Examples

DualShock4-emulator features the ability to invert the right joystick using Left Thumb + Right Thumb + RB and de-invert using  Left Thumb + Right Thumb + LB.

https://github.com/ZeptoBST/DualShock4-emulator/releases/tag/Release2

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/214753510-569a2283-ceca-495f-b3d6-aaa744a0726e.png)

This not good enough?

**Comment by ZeptoBST** [comment]
Switching back and forth mid-game is annoying when you have to navigate through the menus, not to mention that sometimes (mostly in big picture mode) you have to restart the emulator for the setting to apply.

**Comment by RedDevilus** [comment]
You can also make controller profiles per game, not only limited to the Shared profile which could also be a potential solution.

**Comment by ZeptoBST** [comment]
The problem is, I have to invert and de-invert the right joystick mid-game.

In Sly 1, with normal controls: The camera is inverted, but the twin-stick shooter is normal.

With inverted right joystick: The camera is normal, but the twin-stick shooter is inverted.


I have to navigate through the menus, toggle the option, save the input profile and restart the emulator to apply the change (otherwise it doesn't work) every time in and out of each section.

**Comment by stenzek** [comment]
Sounds like a game issue.

This would not really fit into the way configuration is currently applied. Even if you changed the inversion temporarily, as soon as you changed *any* setting, it'd revert back to the original value, and that's just confusing.

(and changing the saved configuration on hotkey is something I deliberately avoided in Qt.)

And you'd need hotkeys for 8 possible controllers.

**Comment by fantasygone** [comment]
Came here to say the same, would love a hotkey to invert controls on the go (like clicking the right analog), but this is indeed a game specific issue, although an annoying one
