### ISSUE TITLE
Swap the order of "Boot CDVD (full)" and "Boot CDVD (fast)" + change Iso to ISO

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#797]
Boot CDVD (fast) is used more (and from what I understand it's also what's recommended) than Boot CDVD (full) so it would make sense for it to be listed first.

Another thing I'd like to see would be the changing of Iso to ISO in the CDVD menu. There's only two instances of it from what I can see.

**Comment by yorkiesandskittles** [comment]
The first one doesn't make a whole lot of sense. The second one is
something that has been bugging me for the longest time.

**Comment by mirhl** [comment]
What?
I always thought full was the recommended one (because I mean.. it's full, complete!)

And even because only with that e.g. Ace Combat loads localization setting.

**Comment by karasuhebi** [comment]
@yorkiesandskittles What doesn't make sense about it? Fast is used more often so it would be good to have it listed first.

@mirhl I'm not actually sure which one is recommended, I guess we'll wait for a dev to weigh in on it.

**Comment by ssakash** [comment]
I did a commit for this swap request and typo fix, I personally prefer the following since I usually use Fast Boot most of the time.

![Image of commit GUI](http://i.imgur.com/DTiJvKP.png)

**Comment by karasuhebi** [comment]
Thanks @ssakash!

**Comment by mirhl** [comment]
Well, I guess in english fast comes before full

**Comment by willkuer** [comment]
This is probably the most important PR in the last years...

**Comment by ramapcsx2** [comment]
I've closed that PR, @ssakash and @karasuhebi.
Please read the reason in #798.
If you still think this is more important, please discuss it further here.

**Comment by karasuhebi** [comment]
>Fast skips the BIOS setup routines that set some registers to specific values that we haven't been able to fully reverse yet.

Is there any games known to have issues with Fast? I believe @mirhl mentioned Ace Combat? Just because there's some stuff you haven't been able to reverse yet doesn't seem like a good enough reason to have that option first. If there is confirmed reports of Fast causing issues, then I'd totally say leave Full listed as the first option and keep recommending it over Fast.

**Comment by yorkiesandskittles** [comment]
I know that there are games which cannot be played in 16:9 unless Full is
used.

**Comment by avih** [comment]
"Full" is definitely the more compatible boot type (aspect ratio choice, language choice, etc), but "fast" still works well on most cases. I agree with @ramapcsx2  that "full" should stay first.

Nothing to do here.

**Comment by Husono** [comment]
Why don't we use a gameini file that overrides troublesome settings in games that only work with specific configurations. That way the boot option can default to CDVD(fast) and we can force CDVD(full) in the games that won't work properly without it.

**Comment by willkuer** [comment]
Forcing full would lead to compatibility issues on approximately 66% of all games since full boot doesn't overcome the region lock. For some games full boot solves graphical or audio issues. Still if I would consider to either play a game with glitches or not at all my choice would be clear.

So fast always needs to be an option.

I don't know when loading the gameindex.dbf happens but possibly after the selection of full/fast.

As already said probably nothing to do here...

**Comment by mirhl** [comment]
If I don't use full boot, AC games default to English, yes (and I don't see any way fast would be more compatible, given it's a hack)

Anyway as long as nobody calls it recommended, I see no real importance in whatever order the two options uses.

**Comment by karasuhebi** [comment]
>For some games full boot solves graphical or audio issues.

Would you mind mentioning some of these games? I'm curious as to which ones they are and what issues they have on fast boot.

**Comment by karasuhebi** [comment]
Nah, not at all. I thought that conversation was over already. I was just asking about which games have issues with fast boot as a matter of practicality. I do a lot of support work over at /r/PCSX2 and it'd be nice to know about these games and what issues there are.

**Comment by yorkiesandskittles** [comment]
Games that use the BIOS' aspect ratio cannot be played in widescreen with
Fast. Not sure if that's really a "graphical" issue, but it does hinder
functionality.

**Comment by karasuhebi** [comment]
Which games use the BIOS's aspect ratio? Could you give me some examples?

**Comment by yorkiesandskittles** [comment]
Burnout 3, Revenge and Dominator. They actually don't let you change it
in-game.

**Comment by karasuhebi** [comment]
Thanks!

**Comment by willkuer** [comment]
Jak games require full boot as well iirc. Either for the eye problem or the sound. I think the jak racing game needs full boot as well. I am not sure though.
