### ISSUE TITLE
[BUG]: Custom config is not applied on first boot from library

### ISSUE THREAD

**Issue by 13xforever** [PCSX2/pcsx2#7979]
### Describe the Bug

When I boot a game with custom configuration, at least some settings are not being applied:
1. I have hardcore achievements enabled in global settings and explicitly disabled in game profile, but on boot I still get notification that I can't restore state/hardcore achievements being disabled (because there are no achievements for the game)
2. No patches are being applied (probably as the consequence of 1., but it's inconsistent, so might be unrelated)

### Reproduction Steps

1. Enable achievements with hardcore mode in global settings.
2. Explicitly disable hardcore achievements per game
3. Have shutdown save state and/or patches enabled (widescreen, no interlace, cheats, what have you)
4. Restart PCSX2 (probably redundant)
5. Boot the game from the library, try to start from shutdown state, and/or boot normally and see if patches are being applied

Everything works as expected if you reset the game immediately after the initial boot (though you need to load the state manually), or if you shut it down and boot from the library again (does allow to boot from state).

![global settings](https://user-images.githubusercontent.com/36445/215161548-de5cafa6-bd05-44d9-ac96-21e1ec39b2e6.png)
![game profile](https://user-images.githubusercontent.com/36445/215161590-93cf3c2c-5d38-471b-ae40-674b18657624.png)
![resume from state](https://user-images.githubusercontent.com/36445/215161639-0812c770-2bee-405e-94d4-d3c7713e399d.png)
![fresh boot](https://user-images.githubusercontent.com/36445/215161762-9403d366-a12b-4daf-8cc2-5b7a419bd1d1.png)

### Expected Behavior

Custom game profile settings override global settings, disabling hardcore achievements, and allowing patches/save states

### PCSX2 Revision

1.7.3968

### Operating System

Windows 11

**Comment by stenzek** [comment]
not a bug with configs, first or subsequent boots make no difference there, and I don't care about achievements anymore, ra can actually do something for a change and fix it themselves, or drop it

**Comment by 13xforever** [comment]
How is it not a bug when settings from custom config are applied halfway the boot process, and some settings are used from global config and some are used from custom config?

Achievements is what I have issues with right now, but the behavior is fundamentally broken and will break something else sooner or later.

And what do you mean "first or subsequent boots make no difference", when it demonstrably does?

**Comment by stenzek** [comment]
> How is it not a bug when settings from custom config are applied halfway the boot process, and some settings are used from global config and some are used from custom config?

Because that's how it works. PCSX2 uses global settings to boot the BIOS, then the game settings are overlaid on top once the ELF is loaded. There's no "some settings are used from global, some from custom", the game settings always take precedence.

**Comment by 13xforever** [comment]
Except when Fast boot is enabled, you don't even boot the bios, much less when you try to restore save state, yet you have the situation when the emulator behavior falls back on global settings anyway. But then it respects custom settings on consequent boots. Which is inconsistent and does not reflect the expectation of how custom configuration should work from the user's perspective.

And if there's some fundamental issue that you decide to apply custom configuration in the middle and not merge it with global settings before starting any boot logic, then the settings that are affected by this should not be in there to begin with?

Well, at the very least this behavior is documented now in this issue.

**Comment by stenzek** [comment]
> Except when Fast boot is enabled, you don't even boot the bios

Wrong. The kernel is still initialized, it just loads the game instead of OSDSYS.

> And if there's some fundamental issue that you decide to apply custom configuration in the middle and not merge it with global settings before starting any boot logic,

You don't want any patches, hardware fixes, etc, running which might be incompatible with the BIOS.

**Comment by stenzek** [comment]
> But then it respects custom settings on consequent boots. Which is inconsistent and does not reflect the expectation of how custom configuration should work from the user's perspective.

Also incorrect. The game settings layer will be removed on reset, and re-added after the ELF is loaded. Just double-checked by overriding the renderer, and it switches back and forth as expected.
