### ISSUE TITLE
[BUG]: No game/achievement info popup on first boot from the library

### ISSUE THREAD

**Issue by 13xforever** [PCSX2/pcsx2#7981]
### Describe the Bug

When you boot a game for the first time from the library, there's no achievement popup overlay (mostly to tell you that the game doesn't have any). If you reset the game, then you get the popup.

This is especially confusing when you have hardcore achievements enabled, because on first boot you'll only see that they are disabled, and it's not obvious why (because the game doesn't have any).

### Reproduction Steps

1. Enable achievements, and make sure Fast boot is enabled
2. Boot the game from the library, wait a few seconds, observe no achievements popup
3. Reset the game, wait a few seconds, observe achievements popup

![image](https://user-images.githubusercontent.com/36445/215163066-e85fb98f-aa74-493e-83df-5f173a4c7469.png)
![image](https://user-images.githubusercontent.com/36445/215163144-8ebda4f3-6a52-4381-9eac-293c748dfd35.png)

### Expected Behavior

You see game info/achievements popup on every boot, including when you boot from the library

### PCSX2 Revision

1.7.3968

### Operating System

Windows 11

**Comment by stenzek** [comment]
works fine here, and don't care about achievements

**Comment by 13xforever** [comment]
Fixed with #7984
