### ISSUE TITLE
[BUG]: controller/keyboard not recognized

### ISSUE THREAD

**Issue by SoggyBacco** [PCSX2/pcsx2#7985]
### Describe the Bug

my controller and keyboard are not recognized until i enter a loadstate that is not in a game's main menu.

### Reproduction Steps

i have no idea what the cause is but it started when i added and launched a new iso.

### Expected Behavior

before this started i had no issues with my controller/keyboard inputs when starting a new game.

### PCSX2 Revision

v1.6.0

### Operating System

Windows 10 (64bit)

### CPU

amd a12

### GPU

amd radeon r7

**Comment by stenzek** [comment]
We don't accept issues for 1.6, it's no longer maintained. Please use the Discord server for support.
