### ISSUE TITLE
[Feature request] Cache failure to find a layer break

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#799]
Up until now when PCSX2 tries to read an ISO file >4,3 GB with the internal ISO loader, we initiate a layer break search, which searches the whole ISO file for it. 

If not found, the search can take even a whole minute when PCSX2 looks unresponsive.

Since there are several ways to have ISO files above 4,3 GB and without a layer break (like mods, undubs etc), each time a user tries to boot such an ISO file, they have to wait for PCSX2 to search the whole file and then fail.

I suggest we cache the failure in the LayerBreakCache.ini just like we cache the success (although we won't be storing any sector obviously) so in the next boot, the user will not have to wait for the whole ISO to be read again, with the appropriate console log message.

Relevant code:
https://github.com/PCSX2/pcsx2/blob/9fa473a57de5592ed39f74a1ee2f39587522132e/pcsx2/CDVD/CDVDisoReader.cpp#L161

**Comment by turtleli** [comment]
I copy part of my post from #1231 

>There might be a better strategy than starting from the middle of the disk/ISO:
```
Read Sector 16 (Layer 0 Volume descriptor)
Read bytes 80-83 (Layer 0 sector count in little endian format)
if (disk/ISO sector count > layer 0 sector count) {
    dual layer disc
    layer 1 starting sector = layer 0 sector count
} else if (disk/ISO sector count == layer 0 sector count) {
    single layer dvd
} else {
    funny business going on
}
```

If the above algorithm works, we only need to read one sector to figure out whether the disk is single or dual layered and where the layer break is. It should eliminate the need to cache the layer break. It would probably need a lot of testing though.
