### ISSUE TITLE
[BUG] No Inputs outside of main menu, and crash upon selecting race cup gran turismo 4

### ISSUE THREAD

**Issue by ForeskinJohn** [PCSX2/pcsx2#7992]
### Describe the Bug

upon attempting to start a cup, say in the beginner events for example, i get a black screen like the one shown here, control inputs also stop working after selecting a course to practice on in the image under the first one, i dont have a way of showing my inputs, but ill still show the menu im stuck on.

![Screenshot (44)](https://user-images.githubusercontent.com/64999311/215315842-b5b19390-6ca9-4773-a578-666877ade269.png)

![Screenshot (42)](https://user-images.githubusercontent.com/64999311/215315913-f6897741-af2b-477f-94bf-e0e2e68b8b0d.png)

### Reproduction Steps

just start the game (2.00 disc) and attempt to select a race or select a race course to practice or do a track day on. 

### Expected Behavior

game will freeze/hang/desync upon joining any race event, and upon selecting a course to practice on, inputs stop entirely.

### PCSX2 Revision

v1.7.3877

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3400G

### GPU

RTX 2060 6GB Card

### GS Settings

Default

### Emulation Settings

Default 

### Logs & Dumps

None generated, emulator did not crash, but game crashed/hanged

**Comment by ForeskinJohn** [comment]
just want to make sure everything is right, sorry about all of the edits

**Comment by stenzek** [comment]
Going to preemptively close this, if GT4 was broken, we'd be hearing it from everyone. Likely a bad dump - dump it from disc again and verify the hash against redump.org.

**Comment by ForeskinJohn** [comment]
> Going to preemptively close this, if GT4 was broken, we'd be hearing it from everyone. Likely a bad dump - dump it from disc again and verify the hash against redump.org.

why close this if i have already tried multiple dumps, this wont fix the issue at all

**Comment by ForeskinJohn** [comment]
i have tried with the 1.01 disc and 2.00 disc from multiple dumps, including my own ps2 disc that i dumped through external drive

**Comment by Mrlinkwii** [comment]
@ForeskinJohn  if you want help go to the   discord

**Comment by ForeskinJohn** [comment]
already tried that

**Comment by ForeskinJohn** [comment]
thats why im here

**Comment by Mrlinkwii** [comment]
can you try rn @ForeskinJohn

**Comment by ForeskinJohn** [comment]
maybe its the cheats/patches im using too, may have regressed there, will continue to update my findings here

**Comment by ForeskinJohn** [comment]
and ill try again there as well but i dont want to get kicked for repeating the same issue

**Comment by ForeskinJohn** [comment]
deleted my .pnach files, and re-dumped my non greatest hits (my 1.01 disc) and everything works, ill let everyone know in the discord as well, thank you for the responses and so quickly too!

**Comment by ForeskinJohn** [comment]
fixed it, it was the .pnach files containing Silent's Triggers patch, ill just bind triggers to analog up and down to maintain good throttle control

**Comment by ForeskinJohn** [comment]
i have a new finding, for some reason the glitch started to happen again, apparently i had corrupted my save file with the .pnach i used, so i have to restart, either way its working now for anyone else who has this issue. and screw the discord's warez policy, i may appeal one day, but that will stop no one from acquiring BIOS online
