### ISSUE TITLE
[BUG]: Graphical issues in Dragonquest 8

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#7994]
### Describe the Bug

There are graphical issues in the final scenes from Dragonquest 8. The hero is flashing in different colors.
I didn't have this issue in my last run (which is just a few months ago).

### Reproduction Steps

Beat the final boss and wait for the bug.

### Expected Behavior

Hero is not flashing in different colors.

### PCSX2 Revision

v1.7.3978

### Operating System

Windows 10 (64bit)

### CPU

i7-4790

### GPU

GTX 1050

### GS Settings

IR x3

### GS Window Screenshots

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230129163707](https://user-images.githubusercontent.com/41426906/215337936-f76a7265-fb64-4e59-8a0f-6d87a02d8477.png)

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230129163814](https://user-images.githubusercontent.com/41426906/215337941-717dc483-f0b6-4491-a954-09ff27f5353d.png)

### Logs & Dumps

[GSdump.zip](https://github.com/PCSX2/pcsx2/files/10530197/GSdump.zip)

**Comment by refractionpcsx2** [comment]
Looks like it needs a good bit of Tex In RT

![image](https://user-images.githubusercontent.com/6278726/215339728-ecb6bdaf-7fdb-4b05-9eab-016dd1bb8865.png)

**Comment by Kupo91** [comment]
Okay, that fixed the bug above, but introduced a bunch of new bugs...

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021114](https://user-images.githubusercontent.com/41426906/215368256-1b8b7a6b-45cf-4cba-baa1-f0f2ee02a49a.png)

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021220](https://user-images.githubusercontent.com/41426906/215368270-90e93ea1-3a81-41af-aa8f-0b4925c3cf42.png)

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021312](https://user-images.githubusercontent.com/41426906/215368279-b8c7576b-31cc-4f72-a666-5b0a237ab186.png)

[GSdumps.zip](https://github.com/PCSX2/pcsx2/files/10531384/GSdumps.zip)

**Comment by JordanTheToaster** [comment]
> Okay, that fixed the bug above, but introduced a bunch of new bugs...
> 
> ![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021114](https://user-images.githubusercontent.com/41426906/215368256-1b8b7a6b-45cf-4cba-baa1-f0f2ee02a49a.png)
> 
> ![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021220](https://user-images.githubusercontent.com/41426906/215368270-90e93ea1-3a81-41af-aa8f-0b4925c3cf42.png)
> 
> ![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230130021312](https://user-images.githubusercontent.com/41426906/215368279-b8c7576b-31cc-4f72-a666-5b0a237ab186.png)
> 
> [GSdumps.zip](https://github.com/PCSX2/pcsx2/files/10531384/GSdumps.zip)

Can you try enable manual hacks enable all the fixes it normally has and turn on CPU Sprite Render Size to 2 (128 Max Width) and see if that works for you? If it works I can add it to the gamedb.

**Comment by Kupo91** [comment]
Shouldn't I try to bisect the issue first? 
I already found out the issue exists in a build from the 1st november, but not in a build from 1st october.
Unfortunatelly each test takes arund 15 minutes, because I always have to beat the boss first to get to that scene

**Comment by JordanTheToaster** [comment]
> Shouldn't I try to bisect the issue first? I already found out the issue exists in a build from the 1st november, but not in a build from 1st october. Unfortunatelly each test takes arund 15 minutes, because I always have to beat the boss first to get to that scene

Try what I suggested first.

**Comment by Kupo91** [comment]
Where do I find these settings about manual hacks?

**Comment by JordanTheToaster** [comment]
> Where do I find these settings about manual hacks?

Settings> Graphics > Rendering then tick manual hacks.

**Comment by Kupo91** [comment]
Ah you meant the "Manual Hardware Renderer Fixes".
I enabled this option, set the CPU Sprite Render Size to 2 and ticked all the other options, but now the font produces white dots here and there:

![screen](https://user-images.githubusercontent.com/41426906/215462437-2dc1d115-a4b6-406e-8a3d-ec2c2d216c42.jpg)

I also **think** I had some lags which I usually don't have. The original issue about the hero is fixed, but the other issues which I posted after still exist.
I noticed that these issues are not introduced by "Tex in RT" or other manual hacks though. They also exist, if I disable manual hacks.
In the build from october, I have none of these issues

**Comment by refractionpcsx2** [comment]
The white dots are probably due to upscaling and you haven't applied those fixes.

Don't tick everything, just tick:
Texture in RT
Autoflush
Sset CPU sprite render to 2

then go to the upscaling tab and set: 
Half Pixel Offset to Special (Texture) 
Round Sprite to Half.

Don't touch anything else.

**Comment by Kupo91** [comment]
Yea that fixed the issue with the dots. But the other issues still exist.

Btw on the screenshot where the screen is half black, there should be actually a short video sequence. Audio is there but no video.

**Comment by refractionpcsx2** [comment]
can you make a savestate just before that point and upload it here?

**Comment by Kupo91** [comment]
Sure, here it is: 
[SLES-53974 (945FBF31).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/10535862/SLES-53974.945FBF31.01.p2s.zip)


I also made a video, what it currently looks like:
https://youtu.be/1UpNCxzoUOY

Go to: 0:55 for 1st bug
Go to: 2:20 for 3rd bug
I couldn't trigger the 2nd bug at 1:57, maybe it is fixed (can't say for sure, because it doesn't always happen) 

And a video from a previous build to show what it _should_ look like:
https://youtu.be/XAF5a7Jd-TU

**Comment by refractionpcsx2** [comment]
cool, thank, I'll take a look in a bit

**Comment by refractionpcsx2** [comment]
Can you try a build from the #8016 PR on DQ8 once it has built? I tested it with the Baumren summon and that seems to work just peachy, but if you can check the other bugs.

If you don't know how to get one of those builds (since they are not a normal update), let me know.

**Comment by Kupo91** [comment]
Hi, I think I got the right build from the PR. Should I test with these settings again?

> The white dots are probably due to upscaling and you haven't applied those fixes.
> 
> Don't tick everything, just tick:
> Texture inside RT
> Autoflush
> Set CPU sprite render to 2
> 
> then go to the upscaling tab and set:
> Half Pixel Offset to Special (Texture)
> Round Sprite to Half.
> 
> Don't touch anything else.

**Comment by Kupo91** [comment]
The issue about the failed FMV is fixed for me aswell, but the other two bugs unfortunatelly still exist:

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230131223612](https://user-images.githubusercontent.com/41426906/215889455-88537d66-3d7e-4f07-9316-f2deaa26a935.png)

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230131223659](https://user-images.githubusercontent.com/41426906/215889485-aa9af735-750a-4336-ba70-797fffbbb410.png)

**Comment by refractionpcsx2** [comment]
Are they fixed with the cpu sprite 2 thing? (with those other options enabled we had before)

**Comment by Kupo91** [comment]
Looks like ticking "Manual Hardware Renderer Fixes" is enough (I didn't touch CPU sprite render size and the other settings):

![a](https://user-images.githubusercontent.com/41426906/215894610-c3346305-9345-4ea2-9c15-36a76e9ac204.png)
![b](https://user-images.githubusercontent.com/41426906/215894633-05e4e544-44d4-48ef-bd37-a776210ee830.png)
![c](https://user-images.githubusercontent.com/41426906/215894650-1141ce37-9076-47c9-a31e-f82a25825a98.png)
![d](https://user-images.githubusercontent.com/41426906/215894663-88106f06-4d0c-40f5-9364-433ccc6924ec.png)

**Comment by refractionpcsx2** [comment]
Yes but that just disabled everything else and that's not really helpful, so I need to to try ticking the options we ticked before

**Comment by Kupo91** [comment]
ah okay, well with the other options enabled the bug with the dark ocean seems to be fixed. But the texture bug with the fire is still there

**Comment by refractionpcsx2** [comment]
Okay, can I easily get to those locations with your savestate?

**Comment by Kupo91** [comment]
Yes, just do the same as me in the video

**Comment by refractionpcsx2** [comment]
Okay thanks, appreciate it :)

**Comment by bigol83** [comment]
I want to add that the fire bug can easily be seen even at the very start of the game. Just save at the first church, exit the church and the fire corruption appears for a moment then it disappears and torches are back to normal. 

https://user-images.githubusercontent.com/38129260/216039841-8c10bb2e-9b95-4c9e-91a9-4f7ea5adcb22.mp4


I'm using latest nightly v1.7.3994 default settings

**Comment by refractionpcsx2** [comment]
Can you try #8016 again? I think I've caught everything.

**Comment by Kupo91** [comment]
yea, LGTM :)

**Comment by refractionpcsx2** [comment]
Awesome :) just need to wait on another potentially fixed game being checked, then hopefully I can merge it

**Comment by Kupo91** [comment]
I'm afraid it's broken again :/

![Dragon Quest VIII - Journey of the Cursed King_SLES-53974_20230209023005](https://user-images.githubusercontent.com/41426906/217692241-c19db348-c373-4f1d-aff7-d6ed9237e4e4.png)

**Comment by refractionpcsx2** [comment]
Can I get a new GS dump, please

**Comment by Kupo91** [comment]
> Can I get a new GS dump, please

yes. 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/10692956/snaps.zip)

**Comment by refractionpcsx2** [comment]
#8084 should fix it.

**Comment by Kupo91** [comment]
yes, that works for me

**Comment by refractionpcsx2** [comment]
Awesome, thanks for testing!
