### ISSUE TITLE
Feature Request: Framelimiter for GSDX for use in PSX emulators.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#8]
GSDX can be used in PSX emulators but without framelimiter it's way to fast in many cases. Could you please create some kind of framelimiting hack or option in GSDX for use in emulators like EPSXE and especially PCSX-Reloaded. Also dedicated hotkey to toggle this framelimiter would be helpful.

**Comment by Mohsen865** [comment]
I have added frame limiter and some other feature to the GSdx for PSX mode!
But it doesn't detect the limiting mode correctly....
Check this: (Watch in full screen) http://i.imgur.com/2TsZHfz.png
<a href="http://imgur.com/2TsZHfz"><img src="http://i.imgur.com/2TsZHfz.png" title="source: imgur.com" /></a>
------------------------------------------------------------------------
► I'm new to C++, so I need help to fix these problems! 
------------------------------------------------------------------------
