### ISSUE TITLE
xBRZ texture scaling and multi-pass CPU-based filter framework with Super xBR support.

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#800]
Would something like that be possible to implement in GSDX?
http://sourceforge.net/projects/xbrz/files/xBRZ/
https://github.com/gonetz/GLideN64/commit/daf18efabbae16454c83562456a6cc19b53255a1
https://github.com/gonetz/GLideN64/commit/5bf7a4e4dea9bc7f1b0cb68db5781b386a5470b7
https://github.com/gonetz/GLideN64/commit/65f29beba6f32f6887647baf28bdae07ad515b96
https://github.com/gonetz/GLideN64/commit/b81c8404fed4a1eb62d3c7354fb7151d1be9508b
https://github.com/gonetz/GLideN64/commit/58c48a8f60e06b77c2dd5133f94b43f7a34218cd
https://github.com/gonetz/GLideN64/commit/663b5d1f5e930d755b157a68fc804f0372622584
https://github.com/Tinob/Ishiiruka/commit/d2fb92518f50c6154f33f05be39128e48d6b83be
https://github.com/Tinob/Ishiiruka/commit/84f96aec7b2c52fda401e9d2419ab9a8787b349a
https://github.com/Tinob/Ishiiruka/commit/6bf5062b7656d9d1d026478a2a639497cad2357b
https://github.com/PeterTh/gedosato/tree/master/ext/xbrz
http://sourceforge.net/projects/xbrz/files/xBRZ/
https://github.com/libretro/common-shaders/tree/master/xbr
https://github.com/nagadomi/waifu2x
http://forum.doom9.org/showthread.php?t=170727
https://github.com/tapcio/PeteOpenGL2Tweak/tree/master/gpuPeteOpenGL2Tweak/xBRZ

https://github.com/citra-emu/citra/pull/5017/files
https://github.com/citra-emu/citra/pull/5166/files
https://github.com/hrydgard/ppsspp/pull/15109/files
https://github.com/hrydgard/ppsspp/pull/14789/files
https://github.com/hrydgard/ppsspp/pull/13235/files
https://github.com/hrydgard/ppsspp/pull/10393/files
https://github.com/hrydgard/ppsspp/pull/7449/files
https://github.com/hrydgard/ppsspp/pull/1599/files
https://github.com/hrydgard/ppsspp/pull/10845/files
https://github.com/hrydgard/ppsspp/pull/383/files

https://github.com/Tinob/Ishiiruka/commit/d2fb92518f50c6154f33f05be39128e48d6b83be
https://github.com/Tinob/Ishiiruka/commit/ae0669573dd4fabf90477a45139f1dd5bf89ddd9

**Comment by refractionpcsx2** [comment]
I think this has been discussed on the forum however I can't remember if the developers had much say on the matter. I guess it's entirely possible, but it's where we use it, do we limit it to 2d sprites, put it on all 3d textures? I dunno.  Texture quality on 3d textures is pretty ass on the PS2 :P

**Comment by karasuhebi** [comment]
> but it's where we use it, do we limit it to 2d sprites, put it on all 3d textures?

I'd leave it up to the user, sort of like how billinear filtering is done.

**Comment by hellbringer616** [comment]
Second leaving it up to the user, in some cases I'd like it on GUI elements and not textures, and in other cases I'd like it on both, i'm not sure which version ppsspp uses, but there is now a v1.4 of the codebase: http://sourceforge.net/projects/xbrz/files/xBRZ/

I know that Hyllian is working on a Super-XBR that is supposed to overcome many of his original works drawbacks, however i cannot seem to find the code for it.

**Comment by refractionpcsx2** [comment]
There's some code here: https://github.com/libretro/common-shaders/tree/master/xbr

**Comment by hellbringer616** [comment]
Found a video showcasing Super XBR-2p and another scaler called "NEDI"
https://www.youtube.com/watch?v=olz9Br7Ajdo
I feel Super XBR has more detail, but NEDI has a smoother image. i'm not sure if this is the "nnedi3" you mentioned though.

**Comment by refractionpcsx2** [comment]
yeh i found that video NEDI is a typo, you won't find anything on that in google, you have to search for nnedi3

http://avisynth.nl/index.php/Nnedi3

**Comment by ADormant** [comment]
@refractionpcsx2 @hellbringer616 @gregory38  xBR and Super-xBR are shaders I don't know if they can be used for texture scaling like xBRZ can. RetroArch uses them as fullscreen filters applied to the framebuffer only. xBRZ can be used to filter pre-rendered backgrounds and FMVs as well.
http://ngemu.com/threads/peops-opengl-1-78-xbrz-scalers-mod.173953/#post-2371609
http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/ 
@Zenju 
@Hyllian
@Tinob

**Comment by ADormant** [comment]
https://github.com/gonetz/GLideN64/commit/daf18efabbae16454c83562456a6cc19b53255a1
https://github.com/gonetz/GLideN64/commit/5bf7a4e4dea9bc7f1b0cb68db5781b386a5470b7
@gregory38

**Comment by gregory38** [comment]
Please stop spamming people. I check regularly the tracker.

**Comment by ADormant** [comment]
Multi-pass cpu filter framework is required for a cpu based version of Super xBR which can work directly on textures.
https://github.com/libretro/common-shaders/tree/master/xbr
https://drive.google.com/file/d/0B_yrhrCRtu8GYkxreElSaktxS3M/view?pref=2&pli=1
https://github.com/PeterTh/gedosato/tree/master/ext/xbrz
Here are screenshots of RE Remake on GC with Super xBR applied with RetroArch's image viewer core.
Super xBR on textures looks phenomenal on digitized games and games with pre-rendered backgrounds.
![retroarch-0104-045603c2lwi](https://cloud.githubusercontent.com/assets/10523326/12136881/4974021c-b44c-11e5-8611-b333008b11f7.png)
![retroarch-0104-045626t3yf9](https://cloud.githubusercontent.com/assets/10523326/12136887/53f015b4-b44c-11e5-853e-18b585491b1f.png)
![retroarch-0104-050239cgzx3](https://cloud.githubusercontent.com/assets/10523326/12136892/5b4e5adc-b44c-11e5-9391-898f64299610.png)
![retroarch-0104-050309hrlvx](https://cloud.githubusercontent.com/assets/10523326/12137288/6826473a-b44f-11e5-862f-b0f4bb41b852.png)
![retroarch-0104-045826iplny](https://cloud.githubusercontent.com/assets/10523326/12137295/805b4b8e-b44f-11e5-985d-b7640ea6ac13.png)

**Comment by ADormant** [comment]
http://forum.doom9.org/showthread.php?t=170727
https://github.com/nagadomi/waifu2x

**Comment by ADormant** [comment]
https://github.com/tapcio/PeteOpenGL2Tweak/tree/master/gpuPeteOpenGL2Tweak/xBRZ

**Comment by ADormant** [comment]
http://pastebin.com/cbH8ZQQT

**Comment by refractionpcsx2** [comment]
Super xBR does look good on that game, but Gamecube generally has much better textures than the PS2, I'm  not sure how well it would translate for us, also what is the performance impact?

**Comment by ADormant** [comment]
@refractionpcsx2 
I think that fast version of Super xBR is slightly slower that xBRZ. Though I believe Hylian still working on it.
If PS2 has worse textures then effect should be even more visible. In Ishiiruka xBRZ/Super xBR can even be used for upscaling dumped textures and loading them back at higher resolution.

**Comment by refractionpcsx2** [comment]
It would be interesting to take a ps2 texture (@gregory38 ? :P ) and run it through a Super XBR filter just to see how it comes out.

**Comment by ADormant** [comment]
@refractionpcsx2 @gregory38 
Not a PS2 game but a PS1 game RE3 so even worse textures.
![super xbr re3 2](https://cloud.githubusercontent.com/assets/10523326/14062024/195a2ece-f391-11e5-9878-4771f3803dfe.png)
![super xbr re3](https://cloud.githubusercontent.com/assets/10523326/14062026/65d215f0-f391-11e5-99cb-a258f56932ba.png)
![super xbr re3 3](https://cloud.githubusercontent.com/assets/10523326/14062029/6e2b2fd4-f391-11e5-8f2b-5717d706dc93.png)
![super xbr re3 4](https://cloud.githubusercontent.com/assets/10523326/14062032/776eaa6c-f391-11e5-8504-c0cae1aaa3d8.png)
![super xbr re3 5](https://cloud.githubusercontent.com/assets/10523326/14062035/809c7a42-f391-11e5-8359-11aec156eea0.png)

**Comment by refractionpcsx2** [comment]
They were static backgrounds, so the image quality was pretty good on them, same as with FFX in shops and buildings, there was a lot of static backgrounds with cleverly placed collision points to make it feel like it was really there.

**Comment by ADormant** [comment]
@gregory38 @refractionpcsx2 
https://github.com/Tinob/Ishiiruka/commit/c9a5b9030bd4bfa260790df8f9c55d47a34319ca
https://www.dropbox.com/sh/7f78x2czhknfrmr/AADhXhA0b8EIcCyejITS697Ca?dl=0
Jinc2-Sharper in my opinion looks better than xBRZ but is faster than Super xBR.

**Comment by refractionpcsx2** [comment]
Jinc2-Sharper looks a very subtle effect, not sure how much it will help.

**Comment by ADormant** [comment]
Jinc looks sharpest. First is bicubic, second xbrz and third jinc
![bicubic](https://cloud.githubusercontent.com/assets/10523326/14366178/d326119a-fd11-11e5-9b33-73bc3e6a64a3.png)
![xbrz](https://cloud.githubusercontent.com/assets/10523326/14366184/dbc5a14e-fd11-11e5-97b8-ae40c677f1f1.png)
![jinc2-sharper](https://cloud.githubusercontent.com/assets/10523326/14366187/e0e6bdd4-fd11-11e5-91d9-0a342d4f7de7.png)

**Comment by Eignar17** [comment]
@ADormant is good graphics 3 good sharpen :3 :+1:

**Comment by refractionpcsx2** [comment]
I don't like how his jacket looks in jinc, the rust on the van is good, but the jacket is too sharp, i actually prefer BRZ for that (even though it looks barely different to bicubic in these pictures)

**Comment by ADormant** [comment]
> the rust on the van is good, but the jacket is too sharp

That's probably because jinc makes little details more visible which isn't always needed but theoreticaly both can be implemented.

**Comment by shinra358** [comment]
So which is better? This or ScaleFX x9?

**Comment by ADormant** [comment]
@stenzek Hi, greak job with texture replacement. Thank you. Any chance you could implement xBRZ texture upscaling in PCSX2 like in Duckstation?

https://github.com/PCSX2/pcsx2/issues/10

**Comment by refractionpcsx2** [comment]
Please don't harass people in to implementing the crap you want.
