### ISSUE TITLE
[BUG]: transparent dialogue box (w/HW) in Taiko Drum Master (NTSC-J/SLPS-20413)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8002]
### Describe the Bug

dialogue box erroneously has transparency.

HW renderer
![Taiko no Tatsujin - Taiko Drum Master  with Tatacon _SLPS-20413_20230130221047](https://user-images.githubusercontent.com/121824800/215488823-af8993fc-5d12-45e6-bb0b-18e34b401280.png)

SW renderer
![Taiko no Tatsujin - Taiko Drum Master  with Tatacon _SLPS-20413_20230130221051](https://user-images.githubusercontent.com/121824800/215488827-95195888-d9ea-429b-9ed5-395848714a28.png)

### Reproduction Steps

Boot up the game without having savedata.

### Expected Behavior

from actual PS2
![Screenshot 2023-01-30 22-13-30](https://user-images.githubusercontent.com/121824800/215487999-0e2ba95c-dfce-4114-81c2-cbc425ef63b0.png)

### PCSX2 Revision

Nightly v1.7.3980

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[TDMJ_transparent.zip](https://github.com/PCSX2/pcsx2/files/10536122/TDMJ_transparent.zip)

**Comment by refractionpcsx2** [comment]
Put your Blending Accuracy up to High (probably maximum in DX)

**Comment by SeruranBlue** [comment]
same issue happen in _Taiko no Tatsujin: Atsumare! Matsuri da!! Yondaime_  (SLPS-20383)
![Taiko no Tatsujin - Atsumare! Matsuri da!! Yondaime_SLPS-20383_20230201012737](https://user-images.githubusercontent.com/121824800/215822878-91dd4520-c7bb-4b24-ad78-2c4d577a9f3a.png)

and you can fix by same setting.
![スクリーンショット 2023-02-01 012820](https://user-images.githubusercontent.com/121824800/215824420-25e8332d-6aaf-4a33-9600-802b316c573b.png)
