### ISSUE TITLE
[BUG]: Road surface marking rendered incorrectly with HW. (The Taxi: Utenshu wa Kimi da,SLPM-62483)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8004]
### Describe the Bug

![Simple 2000 Series Vol  48 - The Taxi - Untenshu ha Kimi da_SLPM-62483_20230130202421](https://user-images.githubusercontent.com/121824800/215533810-e77be126-1be2-4693-a289-42cd1382d52b.png)

I made a [video](https://www.youtube.com/watch?v=YJAK7R1pBBg) for explanation.

- Top left: Actual PS2
- Top Right: HW (default)  **Broken**
- Bottom left: SW (default) 
- Bottom Right: HW (MipMapping: basic or full)    **Kind of (Still broken)**

### Reproduction Steps

Play the game. or wait in title screen and see an demonstration.

### Expected Behavior

shown as above.

### PCSX2 Revision

Nightly - v1.7.3981

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[GSdump](https://github.com/PCSX2/pcsx2/files/10537668/TT_TWKD.zip)

**Comment by refractionpcsx2** [comment]
Full MIP + Trilinear (PS2) looks fine to me

![image](https://user-images.githubusercontent.com/6278726/215535499-77f41f8e-c865-4782-81ee-930116188039.png)

We can add those to the game db if you're happy.

**Comment by SeruranBlue** [comment]
I tried that and it seems good. thank you!

**Comment by refractionpcsx2** [comment]
No problem :) @Mrlinkwii will add it for you!
