### ISSUE TITLE
[BUG]: Several HUD items are small/narrow in HW (The Taxi 2 SLPS-20478)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8005]
### Describe the Bug

Several HUD items (clock hands, speedometer pointer, arrow in map) are small/narrow in HW

HW
![Simple 2000 Series Vol  109 - The Taxi 2 - Utenshi ha Yappari Kimi da!_SLPS-20478_20230130203333](https://user-images.githubusercontent.com/121824800/215542215-0e2f971f-8544-4d9e-822f-c8299a5a53c9.png)

SW
![Simple 2000 Series Vol  109 - The Taxi 2 - Utenshi ha Yappari Kimi da!_SLPS-20478_20230130203335](https://user-images.githubusercontent.com/121824800/215542224-4444bd08-75b4-405b-8f0f-e579b52a3d83.png)

### Reproduction Steps

Start the game.

### Expected Behavior

From actual PS2
![Screenshot 2023-01-31 02-03-38](https://user-images.githubusercontent.com/121824800/215544688-5ab899d9-5c72-49d8-bad5-027fe009c045.png)

### PCSX2 Revision

v1.7.3981

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### GS Settings

I changed several Rendering/Hardware Fixes settings, but none of them works.

### Logs & Dumps

[GSdump](https://github.com/PCSX2/pcsx2/files/10538049/TT2HUD.zip)

**Comment by refractionpcsx2** [comment]
I suspect it might be anti aliasing, not much we can do about that for hardware mode at the moment :(

**Comment by lightningterror** [comment]
Closing in favour of https://github.com/PCSX2/pcsx2/issues/5069
