### ISSUE TITLE
[BUG]: Mega Man X Command Mission

### ISSUE THREAD

**Issue by LiquifiedSnow** [PCSX2/pcsx2#8009]
### Describe the Bug

Trophies are just black sillouhettes

### Reproduction Steps

Obtain trophies and look at the trophy shelf

### Expected Behavior

Trophies should be colored.

### PCSX2 Revision

v1.7.3980

### Operating System

Windows 10 (64bit)

### CPU

Intel i7 6700k

### GPU

Radeon 6750XT

### Emulation Settings

Not sure where exactly to put it so I'll just toss it here, this can be fixed and I'm hoping for an update for automatic deployment when launched to turn this setting on.
![image](https://user-images.githubusercontent.com/6635720/215583358-015c38bd-155e-4404-bfbb-91ccec5a0bd2.png)

Played through 60-70% of the game with it enabled and no issues popping up and it fixes the trophies.

**Comment by refractionpcsx2** [comment]
Thanks :) We'll get it added
