### ISSUE TITLE
[Feature Request]: Gamepad-browsable menu

### ISSUE THREAD

**Issue by secondsabre** [PCSX2/pcsx2#8010]
### Description

Likely out of scope for iterative updates, but it would be really great to see some form of controller-friendly menu overlay built into this program.  Traditionally such menus are mapped to the 'Guide' button (or whatever you want to call it) on modern controllers, which would result in some kind of overlay menu with basic functionality, ie, Quit Game, Choose New Game, Change Disc, Save/Load State, etc.  This could (maybe?) even apply to the default UI in the qt builds, by making the UI browsable by controller.

As always, thanks for all the amazing work!

### Reason

-Being able to access common functions from a controller without having to get up and use a mouse would be a big plus to the user experience
-Ease of use for options like GameStream where K+M support can be sketchy

### Examples

-Retroarch has this functionality, of course
-RPCS3 has a pretty bare-bones implimentation (screencap attached)
![A1MHu9o393](https://user-images.githubusercontent.com/5251899/215590786-1ce840b0-e15f-4f65-9e4f-cc63be013983.png)

**Comment by refractionpcsx2** [comment]
you mean something like -bigpicture? but -bigpicture, exactly as -bigpicture is already implemented? ;)

**Comment by Mrlinkwii** [comment]
already  in pcsx2 
![image](https://user-images.githubusercontent.com/17685135/215591332-3d526b3f-d221-476d-ac9d-6d07fe09d9ef.png)

**Comment by refractionpcsx2** [comment]
you can also map "Pause menu" to your controller with a combination to bring that up for exiting the game etc with the controller.

**Comment by secondsabre** [comment]
Aw geez, don't know how I missed that.  Queue the sound of me eating crow, thanks for setting me straight.

**Comment by refractionpcsx2** [comment]
no problem :) Enjoy!
