### ISSUE TITLE
[Feature Request]: Save cover download url for future use

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#8013]
### Description

Odds are, once someone has found a URL to get covers from, they are going to continue using that URL until they have a reason not to. Saving the URL so it doesn't have to be input each time probably wouldn't be a horrible idea

### Reason

Inputting the URL each time means either writing it in a file to remind yourself, looking it up each time or trying to remember it. Plus, honestly, its just annoying to have to do it every time you happen to get a new game

### Examples

Either have the URL saved by default or ask the first time a URL is used if the user wants the URL to be saved

**Comment by stenzek** [comment]
You shouldn't be "finding a URL" - the feature is intended to be used with your own server/hosting. Wanting to save someone else's is out of scope, because that could arguably be piracy in the first place (if covers are considered copyrighted, I'm now a lawyer).

**Comment by Masamune3210** [comment]
Dolphin pulls covers from GameTDB, so if there is a line worth worrying about, others have already crossed it without issue. I will relent to your choice though

**Comment by stenzek** [comment]
Easy for you to say, you're not the one who's responsible if a publisher decides to protect their rights.

**Comment by vandersdg** [comment]
Crazy argument against it. Alright, the URL points to my server, why do I have to retype it every time? Why can't the software just remember it? Total nonsense.
