### ISSUE TITLE
[BUG]: Character outlines are thin in HW. (TVDJ SCPS-15002)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8017]
### Describe the Bug

![1](https://user-images.githubusercontent.com/121824800/215798655-5c08b83f-ea93-46f2-a457-22d3ddd09c7e.png)

Top left: actual PS2
Top right:SW
bottom left:HW (**thin**)

### Reproduction Steps

Boot up the game and watch opening.

### Expected Behavior

it's shown above

### PCSX2 Revision

Nightly v1.7.3986

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[tvdj_gsdump.zip](https://github.com/PCSX2/pcsx2/files/10547800/tvdj_gsdump.zip)
Tried Render/Hardware Fixes options but nothing worked.

**Comment by refractionpcsx2** [comment]
Looks like it's possibly antialiasing (or lack thereof) again.

**Comment by lightningterror** [comment]
Closing in favour of https://github.com/PCSX2/pcsx2/issues/5069
