### ISSUE TITLE
Playstation -> PlayStation

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#802]
In the About page and in the CLI page, it says Playstation instead of PlayStation (same thing with the website, but that's for @bositman to fix :P) and it drives my OCD up the wall. Could someone tell me where these strings are stored so I can make the change and PR it? Or would someone PR it for me? @turtleli :D

![2015-09-06 00_09_37-pcsx2 commandline options](https://cloud.githubusercontent.com/assets/6857825/9702452/927af578-542b-11e5-8fb5-f76577fff424.png)

**Comment by karasuhebi** [comment]
Oh BTW, --nogui doesn't have PCSX2 exit on Suspend which apparently its supposed to do. Does anyone know when it last worked properly so we can track down the issue?

**Comment by ssakash** [comment]
> Could someone tell me where these strings are stored so I can make the change and PR it?

About dialog box: https://github.com/PCSX2/pcsx2/blob/9fa473a57de5592ed39f74a1ee2f39587522132e/pcsx2/gui/Dialogs/AboutBoxDialog.cpp#L98

Command line : https://github.com/PCSX2/pcsx2/blob/6b11497cdc6919e9f850daf92b3dbc886b5d976e/pcsx2/gui/AppInit.cpp#L216

**Comment by karasuhebi** [comment]
Thanks @ssakash!

BTW I got the --nogui argument to work. I had to turn the "Hide window when paused" option back on. I turned that off because sometimes I like suspending the game and still being able to see the GS window.

**Comment by karasuhebi** [comment]
Fixed in #815.
