### ISSUE TITLE
[BUG]: Star Wars Battlefront II - Backgrounds "disappearing" in a few maps

### ISSUE THREAD

**Issue by Atsix** [PCSX2/pcsx2#8021]
### Describe the Bug

Sometimes, if you point your camera to a given direction, parts of the background (including the floor) disappear. Sometimes you can see a kind of silhouette or shadow of some elements of the background:

![2023-01-28 (4)](https://user-images.githubusercontent.com/123998118/215890522-7b9ddf0f-d737-4a2c-8107-9bbcdfc3e025.png)

![2023-01-28 (3)](https://user-images.githubusercontent.com/123998118/215890632-0f40084c-99c7-4cbe-bc94-66b35e2b69e3.png)

![2023-01-28](https://user-images.githubusercontent.com/123998118/215890707-3001a245-0582-44f7-922f-5cd9f96d99d8.png)

It seems only a few maps in the game have this issue though. I've encountered it in the "Geonosis" and "Mos Eisley" maps, as well as some space maps, like "Space Tatooine" (it doesn't happen as frequently as in the "Geonosis" and "Mos Eisley" maps, though). 

These maps have this glitch on every mode of the game (Instant Action, Galactic Conquest, etc). This issue is also present on both hardware and software modes.

### Reproduction Steps

- On the game's Main Menu, select "Singleplayer"
- On the Singleplayer Menu, select "Instant Action"
- On the Instant Action Menu, select "Add"
- Select either the "Geonosis" or "Mos Eisley" map
- Select "Launch"
- The glitch will happen as you play the match

### Expected Behavior

The maps' backgrounds should always be visible.

### PCSX2 Revision

v1.7.3985

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5800H

### GPU

NVIDIA GeForce RTX 3060

### GS Settings

- Software Renderer
- Anti-Blur disabled
- 4 extra rendering threads

**Comment by JordanTheToaster** [comment]
Caused by #7267

**Comment by Mrlinkwii** [comment]
@Atsix can you check #8034 or me :)

**Comment by Atsix** [comment]
Sorry for the delay, but I'm having some trouble building PCSX2 on Visual Studio. I'm pretty sure it's because I don't have qt 6.4 on my PC. As soon as I solve this, I'll test the game and see if #8034 fixes it.

**Comment by refractionpcsx2** [comment]
You could just download a build from the PR, so you don't have to build it yourself.

**Comment by Atsix** [comment]
> You could just download a build from the PR, so you don't have to build it yourself.

Well, almost three years working in software development and I didn't know about about that until now lol, thanks a lot!

Just tested the game, #8034 fixes this issue both on software and hardware (native res) modes! Thank you guys!

**Comment by RedDevilus** [comment]
To be fair, not every project gives artifacts that are pre-compiled by bots. Some only do releases or want you to compile like via visual studio (code).
