### ISSUE TITLE
[BUG]: When creating a new input profile, usb is not copied to new profile

### ISSUE THREAD

**Issue by PiperCalls** [PCSX2/pcsx2#8027]
### Describe the Bug

When creating a new input profile, a dialog box gives the option to copy inputs/settings from the existing profile. If Yes is selected it will copy controller inputs but usb inputs/settings is blank.

### Reproduction Steps

Starting with Shared input profile, attempted to create multiple new input profiles & Yes copy from current profile was chosen in each case. Any usb devices, inputs & settings are always blank in the new profile.

### Expected Behavior

When creating a new input profile & Yes copy from existing profile is selected, all usb device, inputs & settings will be copied over just like it does with controller inputs.

### PCSX2 Revision

1.7.3982

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
input profile is for controller not usb i think

**Comment by refractionpcsx2** [comment]
well, USB *is* input, so it probably should be.

**Comment by PiperCalls** [comment]
> input profile is for controller not usb i think

Input profile includes usb, is required for wheels, etc.

**Comment by hd-genius** [comment]
I think that the USB setting should copied over as well. It makes sense, like if you have two similar light gun games you can base the second profile off of the first light gun config.

I'm currently working on copying the USB settings over when we copy an existing profile. I'm hoping to get a PR out for it soon.

**Comment by Mrlinkwii** [comment]
Can this be rechecked on latest nightly :)

**Comment by PiperCalls** [comment]
> Can this be rechecked on latest nightly :)

Just updated & tested (v1.7.4599) and it is working correctly, copying over usb inputs as well. TY very much.

**Comment by Mrlinkwii** [comment]
cool,  im gonna  close the issue  as completed  then :)
