### ISSUE TITLE
[BUG]: Champions of Norrath(SLUS-20565) crashes when trying to start new game on higher difficulties

### ISSUE THREAD

**Issue by macmmm81** [PCSX2/pcsx2#8028]
### Describe the Bug

After completing the game it is possible to start a "new game plus" with your old save on higher difficulty. While doing that the game crashes. It's not because of the save, on the real console it loads normally and the new game feature works as intended.

### Reproduction Steps

With my save in the first slot:

Start New Game/ Normal Game/ One Player/ Courageous/ Import/ 2. Completed Game/ Import/ Accept.
The game crashes after "accept".

### Expected Behavior

The game loads without crashing.

### PCSX2 Revision

v1.7.3994

### Operating System

Windows 10 (64bit)

### CPU

i7-6700k

### GPU

GTX 970

### GS Settings

Widescreen Patches, 3.5x native res, GPU Palette Conversion on - changing these to default does nothing.

### Emulation Settings

All default.

### Logs & Dumps

Memcard with the save:
[CON_B.zip](https://github.com/PCSX2/pcsx2/files/10560120/CON_B.zip)

Savestate before accepting:
[con_sstate.zip](https://github.com/PCSX2/pcsx2/files/10560110/con_sstate.zip)

**Comment by refractionpcsx2** [comment]
Works for me :tm:
![image](https://user-images.githubusercontent.com/6278726/216133783-ec1c9296-914f-4614-9bed-e91af8084583.png)


If it crashes, does it create a crash dump in your PCSX2 folder? That would be handy.

**Comment by macmmm81** [comment]
Are you sure you've selected new game on the courageous difficulty with 2.Completed game? How come you are on the plane of air?

Here are my dumps:
[dumps.zip](https://github.com/PCSX2/pcsx2/files/10560685/dumps.zip)

**Comment by macmmm81** [comment]
Oh okay, you have the wrong game, I'm talking about Champions of Norrath (SLUS-20565), not Champions Return to Arms

**Comment by refractionpcsx2** [comment]
oh, you had both saves on the memcard, sorry. I'll try the other one, then. Looking at something else first.

**Comment by macmmm81** [comment]
It seems to have partially solved the problem, on Software, Vulkan and OpenGL it now works fine, but on D11 I still get crashes.

**Comment by Mrlinkwii** [comment]
@macmmm81  dose dx11 still crash?

**Comment by macmmm81** [comment]
Still crashes on dx11
[dumps.zip](https://github.com/PCSX2/pcsx2/files/10776732/dumps.zip)

**Comment by Mrlinkwii** [comment]
Can this be check on latest nightly with default settings ?

**Comment by refractionpcsx2** [comment]
Probably a driver problem, so closing for now, if the problem persists, please visit our discord.
