### ISSUE TITLE
[Feature Request]: Add "Sensitivity" setting for usb devices

### ISSUE THREAD

**Issue by PiperCalls** [PCSX2/pcsx2#8029]
### Description

This is primarily for tweaking steering wheel inputs but could be helpful for other analog usb devices. In the usb ports, if wheel is selected there is a settings tab with deadzone, etc. It would be helpful to add some kind of sensitivity setting that could go positive or negative to dial-in wheel inputs for various games.

### Reason

Steering wheel input varies wildy from game to game. It would be helpful to be able to dial in sensitivity on the wheel input in each input profile to make each game more usable.

### Examples

In the input profile, under usb port, wheel device selected and settings tab, include a sensitivity slider that could be adjust higher or lower. It would be nice if the adjustment was real time so it could be tested while in game to get the settings just right for that game. Also input profiles could be shared among users of the same wheel/hardware.

**Comment by refractionpcsx2** [comment]
Is that not down to your wheel driver to deal with?

**Comment by PiperCalls** [comment]
Yes, the wheel software (Logitech in my case) does this but only at the exe/emulator level. So I can set a wheel radius, sensitivity but it then applies to every pcsx2 game. Dift games need dift tweaks to it to make them playable. So the only options would be to have a dift copy of pcsx2 for each game (nightmare) or if we could get a sensitivity setting in the input profile. Some games have a wheel calibration built into the game, but only a few and it only does so much. A sensitivity setting would allow each game to be set perfectly via the input profile.

**Comment by stenzek** [comment]
#7999 already covers this (shift-click the bindings).
