### ISSUE TITLE
[BUG]: Crash after push "Add game direcory button"

### ISSUE THREAD

**Issue by artslay** [PCSX2/pcsx2#8035]
### Describe the Bug

When i trying add folder where my games, emulator freeze. If click something emulator not responding.

![1](https://user-images.githubusercontent.com/16070464/216308837-b1d0bac9-b45c-4a0c-9074-031cb32a460e.JPG)

### Reproduction Steps

Just click button.

### PCSX2 Revision

v1.7.3994

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Do you by chance have NewOldExplorer installed?

**Comment by stenzek** [comment]
You're using a broken shell extension (probably oldnewexplorer as mentioned above), they're incompatible with the shell dialogs that Qt requests.

If it's different issue, then you'll need to post the crash dump, but this sounds like a support issue rather than a bug.
