### ISSUE TITLE
Final Fantasy X core (?) bug in intro sequence

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#804]
There's an issue with FFX's intro sequence; the one that plays when you boot up the game, not the (very) similar one that plays when you start a new game. If you look closely, you will see some pixels missing from Yuna's sleeve. This doesn't happen on the PS2. I think it's a core bug because it happens on GSdx's D3D11 and OGL (hardware and software) renderers, as well as ZeroGS.

Here's what it looks like in PCSX2 (slowed down 50%):
https://www.youtube.com/watch?v=-IS79MpQppw

And here's what it's supposed to look like:
https://youtube.com/watch?v=ktTu6SGxZt0?t=174

**Comment by refractionpcsx2** [comment]
I see what you mean, not quite sure where that bug is gonna lie. ZeroGS is massively based on GSDX, so it could be an inhereted bug, or it could be a VIF Unpack thing (the intro relies heavily on skipping writes on this).

Im not sure when the dynarec vif unpack came in, can you try it on 0.9.8 or something to see if the glitch exists there?

**Comment by karasuhebi** [comment]
0.9.6, 0.9.7 and 0.9.8 all have it.

**Comment by refractionpcsx2** [comment]
have what? the pixels or the bug?

**Comment by karasuhebi** [comment]
Oh sorry, I meant the bug. XD

**Comment by refractionpcsx2** [comment]
OK :P Just wanted to check!

**Comment by karasuhebi** [comment]
So if it happens even before the VIF unpack change, do we still think it might be a core bug then? Or could it be a GS plugin bug?

**Comment by karasuhebi** [comment]
Still doing it as of the latest nightly, 1.3.1-1198.

**Comment by refractionpcsx2** [comment]
Yeh it's not something we've looked in to, 1 pixel being wrong isn't really something which is a priority :p

**Comment by karasuhebi** [comment]
It's not about the couple of pixels that are wrong, that doesn't really bother me. It's what fixing that (possibly) core issue could fix on other games. Maybe even undiscovered bugs. Who knows?!

**Comment by refractionpcsx2** [comment]
well that's it, we dunno what's causing it, it could just be a rounding problem, which may have very little effect on other games, it could be a massive oversight that fixes a ton of bugs, who knows!

**Comment by Nobbs66** [comment]
if it does it in the software renderer, then I would say it's likely a core issue.

**Comment by refractionpcsx2** [comment]
Then I'll mark it as such and see if it ever gets solved :p

**Comment by karasuhebi** [comment]
>it could just be a rounding problem

Should I try changing Round mode on EE/IOP and VUs to see if it fixes it then?

**Comment by gregory38** [comment]
Might worth to check the mmi overflow, who knows!

**Comment by karasuhebi** [comment]
How do I do that? Or is that something on the developer side?

**Comment by refractionpcsx2** [comment]
@gregory38  I was thinking that when I was replying last night lol

@karasuhebi It's something on the developer side mate, something we are actually planning on looking in to shortly.

**Comment by karasuhebi** [comment]
Oh OK sweet. Well let's hope that fixes this and many other problems then. Keep me posted please. Thank you!

**Comment by karasuhebi** [comment]
Any news on this one?

**Comment by gregory38** [comment]
Did you test latest git?

**Comment by karasuhebi** [comment]
Just tried it. It still does it. :(

**Comment by FlatOutPS2** [comment]
Do you still get this bug too? https://github.com/PCSX2/pcsx2/issues/995
If not, it should be closed.

**Comment by FlatOutPS2** [comment]
This is a GSdx regression, introduced between PCSX2 0.9.4 and 0.9.6.

GS dump:
[Final Fantasy X - Intro cutscene logo bug.zip](https://github.com/PCSX2/pcsx2/files/853405/Final.Fantasy.X.-.Intro.cutscene.logo.bug.zip)

**Comment by ramapcsx2** [comment]
Just a heads up: This is the bug: http://i.imgur.com/dqIuS2k.png

**Comment by FlatOutPS2** [comment]
The bug is also pointed out in the image that comes with the GS dump. ;)

**Comment by gregory38** [comment]
SW or HW or both regression ?

**Comment by FlatOutPS2** [comment]
@gregory38 It's broken for both SW and HW renderers.

**Comment by gregory38** [comment]
But was both renderer good on 9.4 ?

**Comment by FlatOutPS2** [comment]
Yes, both are fine on 0.9.4.

**Comment by seta-san** [comment]
i don't think the pixils are missing. if you watch it in hardware mode they are clearly rendered but then are covered by some sort of artifact.

**Comment by tadanokojin** [comment]
It's an EE transfer that is overrunning on that bit of memory where the logo is. Dobie has the same problem.

**Comment by seta-san** [comment]
it looks a bit like an alpha issue that gets more and more opaque 
![1](https://user-images.githubusercontent.com/8851653/95672701-afde0700-0b68-11eb-96eb-98f7171dc77d.jpg)
![2](https://user-images.githubusercontent.com/8851653/95672703-b2406100-0b68-11eb-97c6-ba6d913a4243.jpg)
![3](https://user-images.githubusercontent.com/8851653/95672706-b5d3e800-0b68-11eb-96ab-8f3b3c3f17bd.jpg)
![4](https://user-images.githubusercontent.com/8851653/95672712-ba989c00-0b68-11eb-9d09-75a3b25d33b4.jpg)

**Comment by refractionpcsx2** [comment]
It's not an alpha issue, a rogue write is screwing up the depth for that area causing it not to draw the logo.

**Comment by benderscruffy** [comment]
using v1.7.4662
still an issue
here is a GS Dump
https://mega.nz/file/kjY0ERAb#cgl4JAFu2IA9yeddPSvcL3nYQsJNzQKAPhoPJ-sQFEk
