### ISSUE TITLE
[BUG]: Changing UI theme resets game thumbnail size in the library

### ISSUE THREAD

**Issue by 13xforever** [PCSX2/pcsx2#8044]
### Describe the Bug

Here's before and after you change the theme pref:
![before](https://user-images.githubusercontent.com/36445/216746283-4837c221-b159-445a-bc7f-955edd10d539.png)
![after](https://user-images.githubusercontent.com/36445/216746294-1ae85a8b-cb8c-4fa0-91cd-919cad38977e.png)

Notice the scale slider retaining the position, however if you click on either List view or Grid view again, the slider position is updated to reset 50% position.

### Reproduction Steps

1. Have non-default thumbnail scaling
2. Open global settings and change theme to anything else

### Expected Behavior

Changing theme preserves current scaling preference

### PCSX2 Revision

1.7.4005

### Operating System

Windows 11

**Comment by RedDevilus** [comment]
Yeah, there are other issues like it remembers old colors (partially) for themes when you change on the fly and seems to break some other stuff. The behaviour kinda changed when Qt 6.4 was used, but not sure if that was main reason or side-effect.

**Comment by MrCK1** [comment]
Still looks to be an issue as of 1.7.4589

**Comment by Mrlinkwii** [comment]
Still looks to be an issue as of v1.7.4904

**Comment by kamfretoz** [comment]
Still looks to be an issue as of v1.7.4970
