### ISSUE TITLE
[Feature Request]: Conditional Breakpoints

### ISSUE THREAD

**Issue by buruto** [PCSX2/pcsx2#8049]
### Description

Conditional breakpoints are breakpoints that are triggered only when a certain conditions are met.

### Reason

Conditional breakpoints can solve the same problem that Logpoints and NoBreakpoints do.

### Examples

To find the `lw` MIPS instruction that reads the mission clear time before it is drawn in the mission clear screen or window in Devil May Cry first of all use the memory search of PCSX2 Debugger to find the memory address of the elapsed time since the beginning of the current mission.

You do this by first scan "Unknown initial value" (assuming #7696 is implemented) and then repeat next scan "Increased value" until the memory address of the elapsed time is found.

Then add a read breakpoint in that memory address and the game should pause immediately on the `lw` instruction that reads this data every frame.

Assuming that `0x12345678` is the memory address of that `lw` instrucition add the following condition to the new read breakpoint: `pc != 0x12345678` where `pc` is the program counter register.

Now you can finish the current mission and the game will pause on the `lw` instruction that reads the clear time before it is drawn in the mission clear screen.

**Comment by refractionpcsx2** [comment]
related to #512 so treating as a dupe (in the sense that it's conditional breakpoints..

**Comment by buruto** [comment]
> related to #512 so treating as a dupe (in the sense that it's conditional breakpoints on memory contents).

Understood. Thanks.
