### ISSUE TITLE
[Enhancement] Move certain folders (bios, snaps etc.) to a consistent location

### ISSUE THREAD

**Issue by yorkiesandskittles** [PCSX2/pcsx2#805]
There are some folders used by PCSX2 which would be much easier to work with if they were in Documents/PCSX2, or at least in a consistent location, these folders being:

bios
cheats
cheats_ws
memcards
plugins
shaders
snaps

It gets annoying if you take a snapshot in PCSX2 and forget which version you took it in, but as for savestates, I can understand that they can often mess up between different versions of any emulator, which is why I think their folder is fine where it is. 

Doing all of this should also help to reduce the space used by things like multiple memory card files (which you may end up not using if you tend to upgrade to frequently jump between different versions of PCSX2, like I do.)

I'm going to guess that if you get a new version, plugins should be the only folder overwritten during the setup process.

**Comment by willkuer** [comment]
Are you talking about stable releases installed by the full installer or portable stable releases and git build by orphis?

The latter are portable you know?
Portable strictly means you can not access folders outside its root folder...

**Comment by avih** [comment]
> Portable strictly means you can not access folders outside its root folder...

That's not true. They default to inside the root folder, but you can still point them someplace else via the plugins/folders config panel (or via the ini file for those which don't appear on that panel).

**Comment by willkuer** [comment]
That's true and that is already a nice feature most portable applications I use don't have. Still I think op asks for defaulting 'documents\pcsx2' as root folder even on portable builds. And that is to my knowledge not the desired or expected behaviour of a portable app.

**Comment by yorkiesandskittles** [comment]
We could have an ini file that sets the locations of each folder, so instead of having to manually change the directory of snaps, memcards etc., you could just move a config file into the PCSX2 folder, which has each location read from it. I'm terrible at explaining ideas.

**Comment by willkuer** [comment]
And that is the point where you defined pcsx2_ui.ini

**Comment by yorkiesandskittles** [comment]
I actually had no idea that file was a thing. To be honest though, to make things less of a mess, there should be a space between the last item of one list and the header of the next, like so:

![](http://i.imgur.com/iguOHdM.png)

This is kind of trivial, but I think "inis" should be renamed "config", as well.

**Comment by avih** [comment]
@yorkiesandskittles , please try to stay on topic. Empty lines at the ini file or changing its extension to `.config` are off topic subjects.

Please describe your issue exactly:
1. Do you use portable or installed version of PCSX2? and which PCSX2 version?
2. You do A.
3. You expect X, but instead get Y.

Please use this template and fill in A/X/Y to describe your issue.

**Comment by yorkiesandskittles** [comment]
If it's off topic, then I'd like to close this issue so I can open a separate issue that is more on-topic. The main reason I opened this issue is because I had no idea that PCSX2_ui.ini even existed.

**Comment by avih** [comment]
So I assume the original issue is not an issue anymore. Good. Thanks.

TBH, even if you file new issues for these requests, I don't think we'll add empty lines between sections at the ini file because it's super minor and it's also not a user facing thingy, and I also don't think we'll change the extension to config since it's an ini file format, and the ini format is established enough.

**Comment by yorkiesandskittles** [comment]
I meant changing the name of the folder to "config", but OK.

**Comment by willkuer** [comment]
One could possibly ask the user during runwizard if he wants to use the documents folder or the program dir as root folder or if he wants to use custom folders for memcard cheats and so on. Like a radio button that enables the custom folder selection. I could possibly do that but currently have no time to implement it. I guess you would need to wait for at least a month.
