### ISSUE TITLE
[BUG]: Scandal SCPS-15001 Menu & Asset Glitches

### ISSUE THREAD

**Issue by kanjieater** [PCSX2/pcsx2#8053]
### Describe the Bug

Menus at the start of the game and in game have visual issues.

### Reproduction Steps

Start the game w/ Software renderer. Press Start.  Press Up to set "start the game" (初めから)
Press O to start.

You can see visually the main menu has issues as in the screen shot 
The main menu has issues.

Click through the game until you get to the first in game choice. Press start. The main menu has glitches, especially in options.

### Expected Behavior

Assets should load properly w/o visual glitches.

### PCSX2 Revision

PCSX2 Nightly - v1.7.3182

### Operating System

Windows 11

### CPU

i9-13900ks

### GPU

4070TI

### GS Settings

![image](https://user-images.githubusercontent.com/32607317/216824189-273f3a93-d783-407e-8438-c1b71d0dc1e1.png)
![image](https://user-images.githubusercontent.com/32607317/216824199-35845d26-c9c3-4fe0-8c58-3a11374a2114.png)
![image](https://user-images.githubusercontent.com/32607317/216824204-19eb0955-f7b9-4f0c-9582-715d1d4264d9.png)
![image](https://user-images.githubusercontent.com/32607317/216824207-0ccad118-6ef6-4b9c-9c68-b12950bd5325.png)

Mostly default ( I think)

### Emulation Settings

![image](https://user-images.githubusercontent.com/32607317/216824230-c5f93358-d6a4-4a5b-a6fe-55a5c11b0560.png)

### GS Window Screenshots

![99e4f91e-9851-4e3f-924f-eb3bf15bdc16](https://user-images.githubusercontent.com/32607317/216823842-95f6d784-93f7-493a-80b4-a7445f5651cc.png)
![0f6b8728-f228-4b94-b724-2964ca1fb383](https://user-images.githubusercontent.com/32607317/216823844-193c4942-7ece-4139-89fb-612da4602b1e.png)

### Logs & Dumps
UPDATE: These were the snaps from the version I listed in the issue. I made new ones beneath with latest nightly
[gs dumps.zip](https://github.com/PCSX2/pcsx2/files/10611197/gs.dumps.zip)

**Comment by kanjieater** [comment]
Link on discord recommended I try on latest nightly & had the same issues

PCSX2 Nightly - v1.7.4009
[Scandal_SCPS-15001_20230205082621.zip](https://github.com/PCSX2/pcsx2/files/10611237/Scandal_SCPS-15001_20230205082621.zip)
Snap from latest

**Comment by kanjieater** [comment]
In game menu 
![Scandal_SCPS-15001_20230205082819](https://user-images.githubusercontent.com/32607317/216825395-092155fb-2003-4583-b570-85282bf4e0c5.png)
[ingame.zip](https://github.com/PCSX2/pcsx2/files/10611241/ingame.zip)

**Comment by refractionpcsx2** [comment]
This should be fixed in 1.7.4013 when it's built
