### ISSUE TITLE
[BUG]: Codebreaker ISO identifing gameDB as Rez

### ISSUE THREAD

**Issue by easelgames** [PCSX2/pcsx2#8062]
### Describe the Bug

Codebreakers ISO is mismatched to a GameDB entry of REZ. (latest nightly build)
Should be a simple fix and probably not a cheat iso used much, but still.

(linking to rom page bc it's the most accurate representation I can find on what the program is, not to share this myself.. couldn't find a decent alternative source)
~snip~

"CodeBreaker is a cheat device developed by Pelican Accessories, Currently available for PlayStation, PlayStation 2, Dreamcast, Game Boy Advance, and Nintendo DS. Along with competing product Action Replay, It is one of the few currently supported video game cheat devices." (comes in the form of an ISO file)

### Reproduction Steps

(simply having the iso in roms folder)

### Expected Behavior

Should be correctly identified .

### PCSX2 Revision

v1.7.4013

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
Codebreaker is a third party  tool that happens to use rez's serial and a few others  , blame the Codebreaker devs

**Comment by RedDevilus** [comment]
Linking piracy isn't allowed in any form whatsoever.
