### ISSUE TITLE
[BUG]: Upscaling fixes are used with native resolution if they are shipped in gameindex

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#8063]
### Describe the Bug

Title. 
Unsure if this logics blunder couldn't (somehow) also apply to all hardware fixes more in general, given that I eventually noticed this when I manually toggled the "manual hardware renderer fixes" checkbox. 

### Reproduction Steps

1. Start the first Ace Combat 4 level
2. See the plane horrifically blurred in every hardware renderer even on native resolution
3. Retry, but this time delete `mergeSprite` from the relative gameindex entry

### Expected Behavior

Gameindex shouldn't override the other "gating" logic

### PCSX2 Revision

v1.7.4013

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
You're right, there's no `CanUpscale()` check on MergeSprite.

**Comment by RedDevilus** [comment]
Thanks for reminding, I keep constantly forgetting about this issue.
