### ISSUE TITLE
[BUG]: Urban Reign: visual artefact

### ISSUE THREAD

**Issue by Bezbashni** [PCSX2/pcsx2#8067]
### Describe the Bug

When you have finished the last opponent this visual artefact appears.

### Reproduction Steps

Play first mission with hardware renderer. Software renderer is fine.

### PCSX2 Revision

v.1.7.4017

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800X

### GPU

RTX 3080

### GS Window Screenshots

![Urban Reign_SLUS-21209_20230207071316](https://user-images.githubusercontent.com/110776155/217148128-0199b3f9-7f9b-4db6-8aa9-1ea25fa1fcf1.png)

### Logs & Dumps
[Urban Reign_SLUS-21209_20230207125434.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/10673755/Urban.Reign_SLUS-21209_20230207125434.gs.xz.zip)

_No response_

**Comment by Bezbashni** [comment]
> Can you provide a GS Dump, please?

I've uploaded dump. See above.

**Comment by refractionpcsx2** [comment]
Awesome, thanks :)
