### ISSUE TITLE
[Feature Request]: .mgc files not detected in v1.7.xx

### ISSUE THREAD

**Issue by raja2505** [PCSX2/pcsx2#8072]
### Description

the .mgc files are not detected as discs. converting .mgc to .iso wont work.
can able to run in earlier versions. 
![image](https://user-images.githubusercontent.com/124249760/217267505-f732e1ff-d81a-4612-b218-0f4acfec79fd.png)
[log.txt](https://github.com/PCSX2/pcsx2/files/10675801/log.txt)

### Reason

.

### Examples

.

**Comment by refractionpcsx2** [comment]
I suggest using imgburn to dump your game.
