### ISSUE TITLE
[BUG]: Automatic Updater - Directory path slash orientation causing update failure

### ISSUE THREAD

**Issue by theemadbro** [PCSX2/pcsx2#8073]
### Describe the Bug

When updating PCSX2 via Automatic Updater, the updated fails because of mismatched filepath slash characters. 
![image](https://user-images.githubusercontent.com/36879680/217329238-0f9e7455-5049-42c1-ac12-48f7e8116901.png)

I believe I've pinpointed the specific issue to come from around [updater/Updater.cpp#L105](https://github.com/PCSX2/pcsx2/blob/a4f1f383a76fa22720c2d3e008f51870da875d35/updater/Updater.cpp#L105) (or L104 `FS_OSPATH_SEPARATOR_STR`) but this is only after no more than an hour looking at this code and having no experience with C++ ... so really take this as a novice suggestion / investigation 🙃 .

### Reproduction Steps

1. Launch PCSX2 with System>Settings>Interface>Automatic Updater> `Enable Automatic Update Check` turned on.
2. When prompted with Update Available screen, click `Download and Install...` button to initiate update.
3. Update process will continue until specified staging folders are reached

### Expected Behavior

Directory path separators from the Updater code use the same separators as end user.

### PCSX2 Revision

1.7.4005

### Operating System

Windows 10 (64bit)

**Comment by CookiePLMonster** [comment]
It's a valid visual defect, but I don't think those slashes themselves are an actual culprit, unless you've had the chance to make changes to the code and verify that it's related. On Windows both forward and back slashes are valid separators.

**Comment by dnmaia** [comment]
Having the same issue but with different file and folder. Have been having this error for the past few updates. always need to do a fresh install. the update inside the application is not working. Few days ago was updating normally. 

<img width="307" alt="image" src="https://github.com/PCSX2/pcsx2/assets/62720340/cd054ba3-004f-4336-b47b-f2a4bfbc7cca">


Reproduction Steps
Launch PCSX2 with System>Settings>Interface>Automatic Updater> Enable Automatic Update Check turned on.
When prompted with Update Available screen, click Download and Install... button to initiate update.
Update process will continue until specified staging folders are reached


PCSX2 Revision
1.7.4697

Operating System
Windows 11 (64bit)

**Comment by refractionpcsx2** [comment]
That's a problem with an SDL update we did which has been solved since your version, you will need to manually update from the website this time, then you will be fine.

**Comment by dnmaia** [comment]
Thank you. I updated manually to 1717 and now updated correctly to 1718.

**Comment by Mrlinkwii** [comment]
as their has been no updates saying that  updates have broken again  , im gonna assume this is fixed/ no longer an issue

**Comment by kistjan** [comment]
Hi have this exact error for another file. Failed to rename . . . UPDATE_STAGING\docs\Debugger.pdf to \docs\Debugger.pdf . Currently on version 4932

**Comment by Fadelgio** [comment]
Estou com um problema de renomear:
\UPDATE_STAGING\pcsx2-qt.exe to pcsx2-qt.exe

Como corrigir? 
![image](https://github.com/PCSX2/pcsx2/assets/155745472/0b9e6092-b902-4032-a206-98bcc608c104)
