### ISSUE TITLE
[BUG]: VK_ERROR_DEVICE_LOST with Intel ARC A770 LE

### ISSUE THREAD

**Issue by jacob1218** [PCSX2/pcsx2#8077]
### Describe the Bug

Starting any game results in this error. Log included.
![image](https://user-images.githubusercontent.com/6559034/217397322-04cbee41-f129-4df6-9d17-1a72abe67741.png)
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/10680549/emuLog.txt)

### Reproduction Steps

Start a game using the Vulkan backend on an Intel ARC GPU

### Expected Behavior

The game to start

### PCSX2 Revision

v1.7.4022

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
When did you last update your Intel drivers from their website?

**Comment by jacob1218** [comment]
was solved, the issue was with the overlay from Twitch Studio
