### ISSUE TITLE
Incorrect text in BIOS selection screen

### ISSUE THREAD

**Issue by flarn2006** [PCSX2/pcsx2#809]
In the screen where you select your BIOS files, the following text appears:

> PCSX2 requires a \*legal\* copy of the PS2 BIOS in order to run games.
> You cannot use a copy obtained from a friend or the Internet.
> You must dump the BIOS from your \*own\* Playstation 2 console.

This is completely untrue. I used a copy from the Internet, and it worked perfectly fine. And yes, I do own a PS2, so I am legally allowed to have a copy of the BIOS. Where I get said copy is irrelevant; I have a license.

However, the legality is not the point. The text says you *cannot* use a copy obtained from someone else, when in reality, it works fine. Since the text says something that is not actually true, it should be fixed.

**Comment by avih** [comment]
Obviously PCSX2 can't verify whether the bios is legally owned or not, but that's still a requirement in most places in the world. The message is fine.
