### ISSUE TITLE
[BUG]: Images with latin characters can't be booted through batch

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8095]
### Describe the Bug

As title says, file names with latin characters like the ñ can't be booted through .bat files. It shows a distorted character instead. Keep in mind that I don't know if this is a Windows issue or PCSX2 issue.

![imagen](https://user-images.githubusercontent.com/19964653/217915850-58769c8f-4475-44ef-96d4-b40cd1c4fb45.png)

### Reproduction Steps

1. Create a batch file inside PCSX2 folder containing this:
"pcsx2-qtx64.exe" "[location of ISO with latin characters in its name]"

2. Execute it and the error should display.

### Expected Behavior

PCSX2 should boot images even if there are latin characters in its file name.

### PCSX2 Revision

v1.7.4026

### Operating System

Windows 10 (64bit)

**Comment by silentbrains** [comment]
Windows problem, perhaps. Can insert `chcp 65001` in the .bat file, before the command to run pcsx2, to set the code page to utf-7. Then the game should launch correctly when running the batch.
(ref: https://ss64.com/nt/chcp.html )
(disclaimer, I only tested with "ñ")

**Comment by RedDevilus** [comment]
I heard about this issue for translation aspect and might need some extra support to Qt keymaps.

**Comment by CookiePLMonster** [comment]
If it's the batch script itself not providing correctly encoded Unicode paths, then there's not much there that can be done.

**Comment by ElTioRata** [comment]
Then it is a batch issue, closing this.
