### ISSUE TITLE
GSdx is no longer debuggable in Visual Studio

### ISSUE THREAD

**Issue by gabest11** [PCSX2/pcsx2#810]
Just noticed it actually. The only solution config is Debug now, which can't be matched with any of GSdx's project config names, so the debugger can't start. And even if I created one with this name, I'd be forced to copy the settings from one of the configs, which leaves the rest still not debuggable.

**Comment by gabest11** [comment]
Oh well, I think I can just manually change the config assigned to Debug each time. This sucks a bit.

**Comment by avih** [comment]
@micove might be able to help. He unified and simplified the build configurations. Maybe it can be improved.

**Comment by micove** [comment]
Would renaming:
"Debug SSE2" -> "Debug"
"Release SSE2" -> "Release"
in the GSdx project help?

Visual Studio always builds with SSE2 unless explicitly told not to so the name is a bit redundant and is the only project with the SSE2 suffix.

I don't have access to VS right now but if I understood the issue correctly that should let the debugger work for the SSE2 flavor and would require just adjusting the _M_SSE preprocessor variable if the other flavors are needed to be debugged.

**Comment by gabest11** [comment]
I'm just discovering it myself, but as you say, I have to use sse2 in debug, or change the line of gsdx in the solution config to something else I want to debug.

**Comment by micove** [comment]
@gabest11 

Could you check if PR #811 fixes it for you?

**Comment by micove** [comment]
Is the issue that you want to debug something besides SSE2? Or that SSE2 was not debuggable? Re-reading the last message make it seem like the former but the title implies the latter.

**Comment by gregory38** [comment]
Is it ok? Could it be closed?

**Comment by micove** [comment]
Never got a reply but if I understood correctly the issue is still there. All of them are debuggable it's just that the ones besides SSE2 require ~2 more clicks when compared to the old behavior. It can be re-added to the solution file if it's really annoying since the issue is that the shortcut got removed since it was annoying to test that all 5 debug builds always compile. Either way, some annoyance will remain, heh.
