### ISSUE TITLE
Changing the names of the two recommended options for Blending Unit Accuracy

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#812]
Correct me if I'm wrong but ramping up blending accuracy only taxes the GPU, not the CPU. If that is indeed the case, I think the options should be renamed to say "high-end GPU" instead of "high-end PC". I also think that the order of the words should be switched around:

The first time I saw the Blending Unit Accuracy option in PCSX2 and it was set to High, all I saw was "High (Recommended" and the rest got truncated. This immediately made me think that I was using the recommended option for Blending Unit Accuracy and that I didn't need to touch it. Little did I know I was using the option recommended for high-end PCs and that if I wanted to get better performance in some of the more GPU-intensive games, I needed to lower this.

I believe the wording should be switched to "High (high-end GPUs)" and "Basic (low-end GPUs)" so that the only thing the user sees next to the option chosen by default isn't the word "Recommended".

Any thoughts?

**Comment by ssakash** [comment]
I'm pretty sure that @gregory38 told it was CPU demanding since the there was a need to force in order operation and flush the texture cache, so the draw call gets splitted. not sure how it works, @gregory38  could explain :)

**Comment by gregory38** [comment]
String truncate must be fixed.

It impacts both cpu and gpu. It depends on game and the level. It depends on the internal resolution too.

**Comment by karasuhebi** [comment]
Oh gotcha. Alright so just the UI fix then. Seems like a job for @turtleli :D

**Comment by turtleli** [comment]
;_;

Well, the comboboxes needs to be made wider I guess. The strings aren't actually truncated.

I suppose I can do it after #803, there's something I need to add to the Windows GSdx GUI anyway, I can make the dialog and combobox wider while I'm at it.

**Comment by karasuhebi** [comment]
Yay :D

**Comment by bositman** [comment]
Should not be blocked by anything else now so go ahead?

**Comment by turtleli** [comment]
Done.

**Comment by karasuhebi** [comment]
Thanks for this @turtleli but I still think that the actual parenthetical text should be changed. Actually I'd like to take this a step further: I believe the tooltip should be changed as well. Blending Unit Accuracy seems to hit the GPU WAY harder than it hits the CPU but currently the tooltip for High currently says "A good CPU is required". I have a Core i5-4670K running at 4.1 GHz...is this not considered a good CPU? :P The problem here isn't my CPU, but the shitty performance my GPU gets on OpenGL due to its driver.

**Comment by turtleli** [comment]
Since I can't mind read and don't know exactly what you want to change, I suggest that you suggest what you want it to be changed to, and if others agree (or if you feel strongly about it), make the changes yourself ;)

If you do make changes, don't use the tab(\t) character in the tooltip descriptions - it will not look good on both Windows and Linux.

**Comment by karasuhebi** [comment]
My apologies, I don't know what I was thinking when I wrote that last comment. The parenthetical text is fine now since you stretched the window and now the whole label can be read. There's no more confusion there. It's the tooltip the thing I wanted to discuss. It should say "A good GPU is required" instead of "A good CPU is required". Or if we want to keep it consistent with the label it should just say "A good PC is required" or "A high-end PC is required" or "A high-end PC is recommended".

But hey since I brought up the parenthetical text anyway, I guess we could change that as well! Now that we have a bit more space, we could make it sound less like broken English by adding some words in. We can go from "Recommended high-end PC" to "Recommended for high-end PCs". What do you guys think?
