### ISSUE TITLE
"Treasure Planet" flips out at title screem

### ISSUE THREAD

**Issue by twarnercool2** [PCSX2/pcsx2#813]
Issue title: "Treasure Planet" flips out at title screem

-PCSX2 version: 1.3.0 GIT 9-9-2015

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: 
http://i.imgur.com/916yFjl.png?1

-How to replicate:Go to title screen and press start
-Last known version to work: Never worked

-PC specifications:  Geforce GTX750 , Windows10

**Comment by joder666** [comment]
This is a known "Broken" game.
Here http://wiki.pcsx2.net/index.php/Disney's_Treasure_Planet you'll fine a workaround in the comment on the test from "Cooprocks123e".

**Comment by twarnercool2** [comment]
Would it be possible to put the work around in as a hack?

**Comment by twarnercool2** [comment]
Thanks for the workaround!

**Comment by refractionpcsx2** [comment]
hmm, the EE timing fix under gamefixes may also have the same effect as using the EE Cycle Rate and possibly be a bit more stable.

**Comment by prafullpcsx2** [comment]
Copy pasting this from my thread on the forums:

Disney's Treasure Planet [SCUS 97146] (U) CRC=87C1609F
[SCES 51177] (E) CRC=B18207C5

Game seems to be playable if you enable EE timing hack (fixes hang before going ingame), Set EE roundmode to nearest (fixes characters flying into sky), EE clamping mode to extra+preserve sign (load areas correctly).

**Comment by FlatOutPS2** [comment]
The options mentioned in the post above will load the game correctly, so this can be closed.

**Comment by ssakash** [comment]
Are the required options added at GameDB ? if no,  then it'd be better to add them and close the issue.

**Comment by FlatOutPS2** [comment]
The are in GameDB, but I did spot 2 versions(PAL-M4, greatest hits) that do still lack the options.

**Comment by jcdenton2k** [comment]
Can someone update the wiki with these workarounds as 'Known Issues' so that others who encounter them might become aware of these workarounds?
