### ISSUE TITLE
[BUG]: GTA: San Andreas bloom skipdraw workaround minimizes autoflush HW hack in high speeds

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8132]
### Describe the Bug

It's written on the wiki that this bloom thingy can be disabled by using the skipdraw values 7/7. Unfortunately, what it doesn't say is that once you reach to certain vehicle speed, the issue that autoflush is meant to get rid off is showing up once again.
I don't know if there's a way to avoid this or maybe there's a better workaround out there, or maybe this issue is impossible to fix atm?

### Reproduction Steps

Set skipdraw to 7/7 and keep autoflush enabled, then go to the game, pick a vehicle and drive it as fast as you can. Make sure you have the int. resolution above native.

### Expected Behavior

The workaround shouldn't make the autoflush HW hack almost half-useless.

### PCSX2 Revision

v1.7.4073

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GTX 1060 3GB

### GS Window Screenshots

![Sin título](https://user-images.githubusercontent.com/19964653/218346344-caef2898-0137-41c5-96da-3db80e654d56.png)

**Comment by JordanTheToaster** [comment]
Hacks can break things especially as the emulator changes as you are seeing if you truly want to get rid of the blur in the least destructive way use the patch provided on the Discord.

**Comment by Mrlinkwii** [comment]
Not an issue , wiki is community maintained , and may not be 100% correct , as Jordan mentioned their are patches available to fix the issue if you don't like the blur  effect

**Comment by stenzek** [comment]
Of course skipdraw breaks things. Don't use it and it'll be fine. This is not a bug.

**Comment by GitHub-Khi** [comment]
I think this can help you: https://forums.pcsx2.net/Thread-GTASA-Ghosting-problem

**Comment by ElTioRata** [comment]
> I think this can help you: https://forums.pcsx2.net/Thread-GTASA-Ghosting-problem

Working perfectly. Thanks.
