### ISSUE TITLE
[BUG]: Messed up background color on the Pause menu (Keroro Gunso - Mero Mero battle Royale, SLPS-25399)

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#8146]
### Describe the Bug

In Keroro Gunso - Mero Mero Battle Royale, during a match in-game if you pause the game, on the lower 3/4 half of the background the colors looks all wrong, this only happens when the game is paused. Tested with both SW and HW mode, the glitch persist. To provide a bit of context, the glitch has been there for ages, even dating back to the 1.6 version. According to @refractionpcsx2, this could be a GS Download issue.

Here's the screenshot:
![Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214113828](https://user-images.githubusercontent.com/14798312/218641112-01a64fcc-095b-4299-804b-9466561d0d4b.png)

And video recording:

https://user-images.githubusercontent.com/14798312/218643717-2cf807ce-a62e-4548-a90e-b5d59ad4b2e2.mp4

### Reproduction Steps

1. Boot up the game.
2. Go to any match in-game.
3. Once you're in the match, pause the game.
4. Observe the lower part of the background color (should be very noticeable).

### Expected Behavior

The color shouldn't look wrong

Screenshot during normal gameplay:
![Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214102750](https://user-images.githubusercontent.com/14798312/218641212-12bc25ce-5418-44cd-b2ff-94ef28e8238e.png)

### PCSX2 Revision

v1.7.4080

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

Most settings are default apart from dithering being disabled, setting blending accuracy to full (tested with Basic, doesn't affect the issue),16:9 aspect ratio and changes to Internal Resolution. Vulkan are the renderer in use.

Display:
![Screenshot_20230214_114703](https://user-images.githubusercontent.com/14798312/218641845-e0907ae4-0231-43ee-9656-69535ee0c98e.png)

Rendering:
![Screenshot_20230214_114746](https://user-images.githubusercontent.com/14798312/218641921-33630c43-1bcd-44b7-8a5b-d65787918931.png)

### Emulation Settings

The only changes are enabling Cheats, Optimal Frame Pacing and Scale to Host Refresh Rate

![Screenshot_20230214_114848](https://user-images.githubusercontent.com/14798312/218642074-de6449e0-fc34-42f9-ab71-c05b5906296e.png)

### GS Window Screenshots

![Screenshot_20230214_115156](https://user-images.githubusercontent.com/14798312/218642424-ef812e93-9c5c-43af-b491-cae3f1585ce0.png)

### Logs & Dumps

Here is the GS Dump (You might have to extract it first):
[Keroro Gunsou - Mero Mero Battle Royale_SLPS-25399_20230214102750.zip](https://github.com/PCSX2/pcsx2/files/10728903/Keroro.Gunsou.-.Mero.Mero.Battle.Royale_SLPS-25399_20230214102750.zip)

**Comment by prafullpcsx2** [comment]
How does it look on real ps2? Do you have a comparison screenshot?

**Comment by refractionpcsx2** [comment]
I tried the dump on my PS2 but the GSPS2 runner died :( The game does readbacks and they're a little flaky atm.

**Comment by kamfretoz** [comment]
> How does it look on real ps2? Do you have a comparison screenshot?

I will check on it soon!
