### ISSUE TITLE
Sims 2 Castaway PAL/NTSC - SLES-54903 - Not properly rendered parts [BUG]: 

### ISSUE THREAD

**Issue by sarkatos** [PCSX2/pcsx2#8153]
### Describe the Bug

![image](https://user-images.githubusercontent.com/62260487/218889318-3ded4267-c35a-4bf4-b2a8-5d0169140940.png)
![image](https://user-images.githubusercontent.com/62260487/218889925-e55773d4-7b54-457b-93e2-6a195fe1333c.png)
![image](https://user-images.githubusercontent.com/62260487/218890060-4bbd9ee1-8341-4713-b443-6f7563574fbe.png)
![image](https://user-images.githubusercontent.com/62260487/218890106-34598d82-cab5-4c00-8efa-35ef2e23e7b8.png)
That happens on full window, window mode, and every resolution. Tried differente ISOs also and didn't worked. The game language is pt-br in the photo btw. 

### Reproduction Steps

Just run it normaly.

### PCSX2 Revision

v1.6.0

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 5600G with Radeon Graphics            4.20 GHz

### GPU

integrated

**Comment by RedDevilus** [comment]
What do you mean with trying different ISO?

**Comment by sarkatos** [comment]
Downloaded a ROM of the same game but from another site. Same problem.

**Comment by RedDevilus** [comment]
Downloading any copyright protected materials (games, BIOS) will endanger the project from shutdown, so I cannot help you unless you appeal.

**Comment by sarkatos** [comment]
Ok what if i buy the game and extract the rom. And them have the same issue?

**Comment by RedDevilus** [comment]
That's something else, if you can have the physical disc/case and put a piece of paper to appeal. Discord would be an easier method than via github.

**Comment by sarkatos** [comment]
Vítor Güez#4415
