### ISSUE TITLE
[BUG]: very minor graphical issue in ending of The Taxi 2 (SLPS-20478)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8164]
### Describe the Bug

In 1st ending, There is an gliched "line" under the "SKIP"
![Simple 2000 Series Vol  109 - The Taxi 2 - Untenshu ha Yappari Kimi da!_SLPS-20478_20230216220249](https://user-images.githubusercontent.com/121824800/219385315-b2bd7045-286c-4c78-a778-85ba7ec4f547.png)
It happened in both renderer/every deinterlaces.

### Reproduction Steps

Beat the game (earn 1 million yen.) and see an 1st ending.

### Expected Behavior

![asdfgh](https://user-images.githubusercontent.com/121824800/219387396-ee39eded-62b6-4c20-b4c2-27a82394a7ab.png)
(from https://youtu.be/jSfFCuB2954)

### PCSX2 Revision

v1.7.4097

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[tt2ed.zip_GSdump](https://github.com/PCSX2/pcsx2/files/10756808/tt2ed.zip)

**Comment by SeruranBlue** [comment]
well, it turns out that it's also occurs in actual PS2. (it took 5 hours to reach this screen...)
![20230218_033801](https://user-images.githubusercontent.com/121824800/219758228-96f71af4-fc48-4435-8582-30e63201f920.jpg)
Should I close this issue?

**Comment by refractionpcsx2** [comment]
Then yes, if it's PS2 accurate, I'll mark it as such
