### ISSUE TITLE
[BUG]: (Armored Core Nexus) "Invisible ceiling" when jumping in some missions

### ISSUE THREAD

**Issue by StingerTheRaven** [PCSX2/pcsx2#8171]
### Describe the Bug

In Armored Core Nexus, while jumping, sometimes your AC will get stuck on an "invisible ceiling" that prevents you from gaining altitude even while continuously boosting. This can happen anywhere, but is especially common for indoors levels. See link:
https://www.youtube.com/watch?v=RVfly11qy4Y

### Reproduction Steps

Enter a mission (most consistently occurs on indoor missions, but can happen anywhere). Try to jump, or to double-tap while boosting. Try multiple times, as sometimes you'll successfully jump.

### Expected Behavior

The AC should jump or fly up smoothly, without coming to a hard stop (unless hitting an actual ceiling, of course).

### PCSX2 Revision

1.7.4100

### Operating System

Windows 11

### CPU

Ryzen 7 5700G

### GPU

RTX 3060

### GS Settings

Vulkan renderer. 3x native internal resolution, nearest texture filtering, 16x anisotropic filtering. All else default.

### Emulation Settings

All default.

**Comment by Berylskid** [comment]
It seems caused by Vulkan.

- It doesn't occur by DirectX11, DirectX12, OpenGL, and Software.
- To test for differences of renderer, it must be changed __before__ starting mission.

**Comment by StingerTheRaven** [comment]
> * It doesn't occur by DirectX11, DirectX12, OpenGL, and Software.
Just tried with OpenGL, didn't seem to change anything w/ regard to jumping behaviour. Same settings otherwise.
https://www.youtube.com/watch?v=nWSNMCy5KI0

**Comment by StingerTheRaven** [comment]
This issue is recent in nature, in 1.7.3960 and earlier I can jump without issue.

**Comment by refractionpcsx2** [comment]
if you could find out where it broke, that'd be good, you could do a binary search, so pick something between 3960 and 4108, like, 4020, if that one is broke, try 3990 (roughly in the middle), if it does work, try 4070 (roughly in the middle the other way) and so on.

That would be very useful, thanks

**Comment by refractionpcsx2** [comment]
One possibly one I'm nervous about it being is 1.7.4032, so you could try 4031 then 4032.

**Comment by StingerTheRaven** [comment]
Couldn't find 4031 in the github releases, so I'm using 4030 and 4032.
4030: No problem. Jumps work exactly as I'd expect.
4032: Invisible ceiling, exactly as reported.

**Comment by refractionpcsx2** [comment]
as expected, okay, we'll remove that, thanks

**Comment by Berylskid** [comment]
I apologize, my bad
