### ISSUE TITLE
[BUG]: Choppy sound in Gran Turismo 4 

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#8186]
### Describe the Bug

Basically whenever you accelerate or even slip or anything you can hear choppy audio (USE HEADPHONES TO LISTEN)

### Reproduction Steps

You can hear it better if you use a car that wheelspins, or go to seattle circuit at the jumps.

So, get a car and crash or slowly start, you WILL hear it.

### Expected Behavior

Choppy sound, that's all. Very annoying.

### PCSX2 Revision

v1.7.4109

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 3600

### GPU

gtx 1650 super 

### GS Settings

ap 16:9
fmv ap 16:9
anti blur
vsync
4x native 
af 16x
dithering off
blending high
tp full
fxaa on 
shade boost

### Emulation Settings

mtvu 
enable cheats

**Comment by refractionpcsx2** [comment]
I ran the game on my PS2 and recorded a video of it


https://user-images.githubusercontent.com/6278726/219877044-e109e236-bc43-4619-9bb2-279395040d6c.mp4
