### ISSUE TITLE
[BUG]: The Games are freezing sometimes

### ISSUE THREAD

**Issue by Dantedevil10** [PCSX2/pcsx2#8187]
### Describe the Bug

i playing my games normally, but when i playing, the games and the pcsx2 make a little freezing and continue running,in the most older versions of nightly like the versions begining of 2022 this not happened , and i see when the emulator and the game freezing my HD turn to 100% , in the start of this bug only somegames freezing and the others running normally but in these updates more games are freezing and i dont know how to stop it / my setup i3-7100u, 8gb ram single channel, HD 1tb, intel hd 620, Win 10 , i use the AVX2 qtnightly

### Reproduction Steps

only run the game in whatever settings

### PCSX2 Revision

v1.7.4108

### Operating System

Windows 10 (64bit)

### CPU

i3-7100u

### GPU

intel hd 620

**Comment by Mrlinkwii** [comment]
dont use vulkan use DX11 , the intel igpu have spotty vulkan support on windows

**Comment by Dantedevil10** [comment]
i test in openGL , DX 11 , DX 12 and Vulkan ,in that renderers are freezing ,is like the emulator and game freeze for 3 or 6 seconds and back running normally, this happening while i playing and whatever part of the games

**Comment by stenzek** [comment]
This is not a bug. Please use the discord server if you need support.
