### ISSUE TITLE
Legacy of Kain Defiance, Kain bad rendering in hardware mode for DX and OpenGL.

### ISSUE THREAD

**Issue by joder666** [PCSX2/pcsx2#819]
PCSX2 version: Tested with build 53680d538def68ff0b07c788f9f0c48fbec956dc

PCSX2 options: Defaults, except for GSdx where i changed the backeds to test.
For OpenGL i also tested with Hardware Depth, Accurate Date and different Blending levels.

To replicate just boot the game, as soon as you get in game it'll happen or just play and move towards the tunnel/arc.

Last working: none. Tested a bunch of builds all the way back to 0.9.8, its present in all of them.

Emulog
http://www.mediafire.com/view/xbx8firq2s53env/log.txt

Screens
http://www.mediafire.com/view/9j2z5uje0b3wo73/gsdx_20150912221044.bmp -> problem
http://www.mediafire.com/view/gpcpn5lamw0c8n5/gsdx_20150912221052.bmp -> OK

GS dump
http://www.mediafire.com/download/09ujd53kl8e77z9/Kain_bad_draw.7z

**Comment by gregory38** [comment]
Just to be sure. What is the rendering issue? The shadow?

**Comment by FlatOutPS2** [comment]
The is a mipmapping issue just like Soul Reaver 2(Defiance is the sequel to Soul Reaver 2).

**Comment by FlatOutPS2** [comment]
Can now be resolved with the Hardware Mipmapping option, so I'm closing this.

**Comment by ssakash** [comment]
@FlatOutPS2 

[Gregory's advice is useful ;)](https://github.com/PCSX2/pcsx2/issues/694#issuecomment-252492055)

**Comment by FlatOutPS2** [comment]
It didn't seem necessary because the game is also included in the larger mipmapping issue.

**Comment by gregory38** [comment]
It is to ease future release changelog.
