### ISSUE TITLE
[Feature Request] Analog stick amount in macros

### ISSUE THREAD

**Issue by TheRhalf** [PCSX2/pcsx2#8190]
### Describe the Bug

The UI for sensitivity/binding customization of macros is bugged, and as such doesn't allow to set the deadzone/sensitivity of the macro.

![image](https://user-images.githubusercontent.com/125772989/219903851-469f8b98-503c-4f04-958d-cfb23ae5d1b7.png)

### Reproduction Steps

1. Settings
2. Controllers
3. Choose any controller port(Dualshock 2)
4. Macros
5. Shift+Click the trigger binding button.

### Expected Behavior

Same behaviour as when customizing bindings in the "Bindings" section of any controller port.

In my case I wanted to make a macro for using Shift+W in my keyboard for a 50% sensitivity trigger for LeftStick UP (For walking/sneaking in games)

![image](https://user-images.githubusercontent.com/125772989/219903964-8788401c-c2fd-4f79-9522-9d2d058dcdb5.png)

### PCSX2 Revision

v1.7.4110

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Not really a bug, it was never designed to be a "if I press it this much it triggers this macro", it was supposed to be a button press for a shortcut.
But that aside, your keyboard doesn't have sensitivity and deadzones, so I'm not quite sure what you're after?

**Comment by TheRhalf** [comment]
> Not really a bug, it was never designed to be a "if I press it this much it triggers this macro", it was supposed to be a button press for a shortcut. But that aside, your keyboard doesn't have sensitivity and deadzones, so I'm not quite sure what you're after?

i wanted to do the opposite of that: If i press this button, then it will trigger LeftAnalog's UP at a sensitivity of 50%, i wanted to do that to all the axis of the left stick so i could walk/sneak in games. However i understand if this feature was never intended and it's just a UI bug.

**Comment by refractionpcsx2** [comment]
Okay that's not sensitivity or deadzone, that's "Amount", that's an entirely different thing, but that would be a feature request rather than a bug.
