### ISSUE TITLE
[BUG]: Armored Core 3 & Silent Line Broken Textures/Booster VFX [NTSC-U]

### ISSUE THREAD

**Issue by Glumduk** [PCSX2/pcsx2#8194]
### Describe the Bug

The bug is two parts, both graphical in nature. 
A. Player/NPC textures break into a checkered mess, even at default settings.
B. Booster effects have a black/dark blurry aura around them.

Renderers Tested:
Direct3d 11/12: Bugs present
Open GL: Bugs present
Vulkan: Bugs present 
Software: Bugs absent

These issues were absent in v1.7.4013.0

### Reproduction Steps

1. Boot up AC3 or Silent Line
2. Go to Garage menu 
3. Begin 'AC Test' in the Garage menu 
4. Activate boosters 

### PCSX2 Revision

v1.7.4115.0 

### Operating System

Windows 10 (64bit)

### CPU

i7-4770k

### GPU

GTX1070

### Emulation Settings

I wanted to try eliminating settings as a variable - everything is default out of the box PCSX2 with native PS2 resolution; all suggested values are checked.

### GS Window Screenshots

![AC3TextureFXBug](https://user-images.githubusercontent.com/114959650/219909358-657b55a8-7f64-4f2f-8ed8-1cc0ef7e0cac.png)
![SLTextureFXBug](https://user-images.githubusercontent.com/114959650/219910044-541dc5fe-ed81-47be-992e-ad3ac9552ac3.png)

### Logs & Dumps

[AC3TextureFXBug.zip](https://github.com/PCSX2/pcsx2/files/10775596/AC3TextureFXBug.zip)
[SLTextureFXBug.zip](https://github.com/PCSX2/pcsx2/files/10775623/SLTextureFXBug.zip)

**Comment by refractionpcsx2** [comment]
Does this happen anywhere in the game or just in a specific spot?

if you switch to software mode (F9) does it go away? You will need to run the game, apparently GS dumps don't work for this.

**Comment by Glumduk** [comment]
> 

I've tried the Garage AC Test, a couple missions, and one Arena fight. Textures breaking at mission start seems to be unique to the test arena (pressing F9 here has no effect) - I have had it happen in other places during normal play, but I don't know how to replicate it. The Booster VFX bug was present in all tested locations. Pressing F9 makes the Booster VFX problem go away, but it comes back when F9 is pressed again (switching back to Hardware).  
I'm not sure if run the game means something more specific in a testing sense. Let me know if I can be more helpful

**Comment by refractionpcsx2** [comment]
yep, I've tested it here, you need to be in software from the menu to ingame for it to work, I'm investigating what's going on.  This is one of those, you fix one thing and uncover another bug things.. lol

**Comment by refractionpcsx2** [comment]
It looks like the booster effects were broken by #8107

But there's so much weird stuff happening with this game which the hardware renderer doesn't like, it's making a bit of a mess lol

**Comment by Glumduk** [comment]
I've gotten the impression third generation Armored Core is a little haunted in emulation. So weird. I appreciate you looking into it - hopefully there's a solve.

**Comment by refractionpcsx2** [comment]
Yeah it seems a little cursed, this might not be a quick fix unfortunately :(

**Comment by refractionpcsx2** [comment]
The textures should be okay again once 1.7.4130 is built, the VFX is still broken for the moment, need to investigate why that change broke it.

**Comment by Glumduk** [comment]
Booster FX seem to be fixed!
Textures are definitely better, but something funny is still happening. 
I appreciate y'all 
![ACSLTex](https://user-images.githubusercontent.com/114959650/221491066-3b953674-751e-46a8-87a5-179ae90aad3c.png)

**Comment by refractionpcsx2** [comment]
Can you try #8289 to see if that PR resolves the remaining issue?

you can get a build for windows from here: https://github.com/PCSX2/pcsx2/actions/runs/4433057288?pr=8289

**Comment by Glumduk** [comment]
On current Nightly, textures break sometimes in combat, but not into that wireframe pattern; it looks like a car hit them (Partial Target Invalidation fix, I'm guessing). No booster artifacts. It's not a really disruptive problem. 
I tried the linked build next. Textures look ok, I didn't notice anything breaking in weird ways. There still seems to be some booster artifacts in Arena battles, but only Arena battles(?). I tried a hand full of missions - they were fine. AC3 is the same. 
Including a GS Dump for an Arena test, just in case. 
![ACSL_booster](https://user-images.githubusercontent.com/114959650/225520921-c6b6e894-53cf-4f68-999a-7e8916fd9b2a.png)
[ACSL_Booster.zip](https://github.com/PCSX2/pcsx2/files/10986858/ACSL_Booster.zip)

**Comment by refractionpcsx2** [comment]
goddamnit it game :(

**Comment by refractionpcsx2** [comment]
So I did some investigating and it looks like the game gets itself in a bit of a mess with the hardware renderers, a bunch of uploading the VFX for the booster, then modifying parts of it and modifying just the alpha channel etc, and it ends up in a state where the booster effect doesn't exist and it makes a small target for the top left corner being copied from elsewhere, the game then picks this target up as a source for the VFX draw, but it's tiny, so it ends up repeating and writing garbage.

I have some local changes to fix this by expanding the target and reading the rest of the data from memory, but it may impact other things, so it will get good testing, so I will make a pull request separate to my current one.
