### ISSUE TITLE
[BUG]: "Enable Widescreen Patches" results in CTD with Darkwatch

### ISSUE THREAD

**Issue by TheRhalf** [PCSX2/pcsx2#8195]
### Describe the Bug

Checking "Enable Widescreen Patches" makes Darkwatch (SLUS-21042, CRC:327053E8) crash when starting the emulation **(no other patches active)**. This is most likely because of an incompatibility with the widescreen patches themselves since i searched for other widescreen patches and found one with exactly 29 cheats as well, this pnach file crashes the emulator the same way.

[327053E8.zip](https://github.com/PCSX2/pcsx2/files/10776329/327053E8.zip)

![image](https://user-images.githubusercontent.com/125772989/219934196-75c8f7b1-7c61-4d59-9a63-de39ed7dd09c.png)

### Reproduction Steps

1. Settings
2. Graphics
3. Check "Enable Widescreen Patches"
4. Start Darkwatch

### Expected Behavior

Widescreen patches working successfully or the emulator not crashing at least.

### PCSX2 Revision

v1.7.4116

### Operating System

Windows 10 (64bit)

### CPU

Xeon E3-1230v2

### GPU

GTX 1060

### GS Settings

![image](https://user-images.githubusercontent.com/125772989/219934178-e5f44b80-4101-4f66-87b5-15886e387983.png)

### Emulation Settings

Default settings

### Logs & Dumps

These files were in the PCSX2 directory right after the crash.

[crash-2023-02-19-02-58-03-025.txt](https://github.com/PCSX2/pcsx2/files/10776322/crash-2023-02-19-02-58-03-025.txt)
[crash-2023-02-19-02-58-03-026.dmp.zip](https://github.com/PCSX2/pcsx2/files/10776323/crash-2023-02-19-02-58-03-026.dmp.zip)

**Comment by Mrlinkwii** [comment]
Looks like a bad  patch , I'll have a look into removing/fixing  it

**Comment by lightningterror** [comment]
@TheRhalf Can you verify which patch causes the crash, you can comment them out one by one.

**Comment by MrCK1** [comment]
Please post the rest of your PCSX2 settings, I just tried on dev-4117 and everything is working as expected for me with the matching serial/CRC. 

Delete any other patches you downloaded from your user folder as well and post the emulog after the crash (if it still occurs)

![image](https://user-images.githubusercontent.com/16314399/219948864-6b283e21-1e6e-4f4f-a7fe-40b73d9da11a.png)

**Comment by TheRhalf** [comment]
The game seems to be working normally today 💀

> @TheRhalf Can you verify which patch causes the crash, you can comment them out one by one.

patch=1,EE,0045aaac,word,3c060050

seems to be the culprit



> Please post the rest of your PCSX2 settings, I just tried on dev-4117 and everything is working as expected for me with the matching serial/CRC.
> 
> Delete any other patches you downloaded from your user folder as well and post the emulog after the crash (if it still occurs)
> 
> ![image](https://user-images.githubusercontent.com/16314399/219948864-6b283e21-1e6e-4f4f-a7fe-40b73d9da11a.png)

still happens when I reset all settings to default

**Comment by TheRhalf** [comment]
> @TheRhalf Can you verify which patch causes the crash, you can comment them out one by one.

patch=1,EE,0045aaac,word,3c060050

seems to be the culprit



> Please post the rest of your PCSX2 settings, I just tried on dev-4117 and everything is working as expected for me with the matching serial/CRC.
> 
> Delete any other patches you downloaded from your user folder as well and post the emulog after the crash (if it still occurs)
> 
> ![image](https://user-images.githubusercontent.com/16314399/219948864-6b283e21-1e6e-4f4f-a7fe-40b73d9da11a.png)

still happens when I reset all settings to default

**Comment by MrCK1** [comment]
Is there a specific level this is crashing on? Have you tried playing a different level and see if it crashes?

**Comment by lightningterror** [comment]
Affecting patch was removed so should be fine now.
