### ISSUE TITLE
[BUG]: controls become stuck if automatic update window pops up while playing a game

### ISSUE THREAD

**Issue by matheusvb3** [PCSX2/pcsx2#8196]
### Describe the Bug

If the automatic update window appears while a game is running and some key is being pressed, the key press will become stuck. Resetting the game does not work, PCSX2 has to be closed and reopened for it to start working correctly again.

### Reproduction Steps

Enable automatic update check, start a game, give it some input and wait for the auto update window to appear.

In my case, if the key to move my character forward in the Ratchet & Clank games (any of them) is pressed when the window appears, he will keep walking forward forever.

### Expected Behavior

If the auto update window appears, the controls should not become stuck.

### PCSX2 Revision

1.7.4053 AppImage

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Zorin OS 16.2

**Comment by stenzek** [comment]
The automatic update should only take a couple of seconds max, are you starting a game that quickly?

**Comment by matheusvb3** [comment]
That's strange, it takes up to 40s for it to pop up for me.

**Comment by matheusvb3** [comment]
@stenzek Wouldn't it be possible to make the auto-update window not appear if a game has already been started?
