### ISSUE TITLE
[BUG]: Dynasty Warriors 5: Empire crashed after Player 2 chose a character

### ISSUE THREAD

**Issue by Jancoegers** [PCSX2/pcsx2#8197]
### Describe the Bug

An error occur after Player 2 joined and chose a character.
Singleplayer run without any problem and similar game like Samurai Warriors 2: Empire has no issue like this as well.
Here is the error message:
![Screenshot 2023-02-19 162946](https://user-images.githubusercontent.com/125797011/219941780-e2d95118-022e-4c1c-821f-529d96e0b7fe.png)

### Reproduction Steps

1. Boot up Dynasty Warrior 5: Empire (USA version)
2. Start a new game in empire mode
3. Go through starting a new game and invade, be sure to add at least 2 generals
4. on the prep screen press start on the second controller
5. select a general, then it will crash

### Expected Behavior

The game proceed to the Briefing or Preparation Menu

### PCSX2 Revision

PCSX2 1.7.4116

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3500U

### GPU

AMD Radeon Vega 8 Graphics

### GS Settings

I changed the CRC to Full and checked the GPU Pallete Conversion for I was playing Battlefield 2 Modern Combat... I return the settings to default afterward
![Screenshot 2023-02-19 172224](https://user-images.githubusercontent.com/125797011/219942168-04a646a2-9928-401a-9a93-1b4e299967ec.png)

### Emulation Settings

Never touching this settings... It stays default the whole time

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/10776613/emulog.txt)

**Comment by nickd550** [comment]
Have the same issue. Using the newest nightly build. Tried different / stable version and it’s the same. I’ve tried searching for different dw5 empire roms. I’ve only found the same USA zip  as well as some international version. I tried the EU/AU version and got the same error code.

**Comment by nickd550** [comment]
Coop works fine in free mode. I think the bug lies somewhere in the empire mode when it splits the game into splitscreen from solo.

**Comment by Jancoegers** [comment]
I remember playing DW5:E multiplayer just fine with the stable version 1.6.0 about a year ago.

> Have the same issue. Using the newest nightly build. Tried different / stable version and it’s the same. I’ve tried searching for different dw5 empire roms. I’ve only found the same USA zip as well as some international version. I tried the EU/AU version and got the same error code.

I haven't think about using the stable version to play nor test it until your reply came, so I did my own test and you're right!
The error is occurred, but you can choose **'Ignore'** and the game could continue to run (Although I do not playing it any further at the time of this writing) unlike the nightly build that keep getting the error messages over and over again.

Here is the result after choosing **'Ignore'**:
![Screenshot 2023-03-11 155049](https://user-images.githubusercontent.com/125797011/224475258-5e838ad4-8a98-44ad-97eb-31ba7389bfab.png)

**Comment by refractionpcsx2** [comment]
@nickd550 please don't discuss piracy on here ,you will be removed.

**Comment by nickd550** [comment]
Sorry, I'm new to this website and didn't understand the specifics of the rules. Edited my comment. If it needs to be edited further please let me know. I'm sorry for the issue I caused and having to take your time to let me know.

**Comment by nickd550** [comment]
@Jancoegers  Nice!!!! I actually feel silly, I didn't hit ignore and just hit abort. I'm glad it worked out! I'm going to download 1.6.0 if that's the version you used!

**Comment by Technostrophe** [comment]
Still an issue as of v1.7.5154

**Comment by Mrlinkwii** [comment]
still broken as of v1.7.5422

**Comment by Mrlinkwii** [comment]
still an issue as of v1.7.5698

but i have more info 

theirs a lot of Unknown VifCmd commands before it crashes 
```

3351.7747] Vif1: Unknown VifCmd! [43]
[ 3351.7747] Vif1: Unknown VifCmd! [1b]
[ 3351.7747] Vif1: Unknown VifCmd! [59]
[ 3351.7747] Vif1: Unknown VifCmd! [1b]
[ 3351.7747] Vif1: Unknown VifCmd! [54]
[ 3351.7747] Vif1: Unknown VifCmd! [43]
[ 3351.7747] Vif1: Unknown VifCmd! [1b]
[ 3351.7747] Vif1: Unknown VifCmd! [46]
[ 3351.7747] Vif1: Unknown VifCmd! [35]
[ 3351.7747] Vif1: Unknown VifCmd! [33]
[ 3351.7747] Vif1: Unknown VifCmd! [52]
[ 3351.7747] Vif1: Unknown VifCmd! [43]
[ 3351.7747] Vif1: Unknown VifCmd! [1b]
[ 3351.7747] Vif1: Unknown VifCmd! [46]
[ 3351.7749] Vif1: Unknown VifCmd! [21]
[ 3351.7749] Vif1: Unknown VifCmd! [22]
[ 3351.7749] Vif1: Unknown VifCmd! [52]
[ 3351.7749] Vif1: Unknown VifCmd! [34]
[ 3351.7749] Vif1: Unknown VifCmd! [25]
[ 3351.7749] Vif1: Unknown VifCmd! [1b]
[ 3351.7749] Vif1: Unknown VifCmd! [4c]
[ 3351.7749] Vif1: Unknown VifCmd! [54]
[ 3351.7749] Vif1: Unknown VifCmd! [54]
/home/runner/work/pcsx2/pcsx2/pcsx2/x86/newVif_Dynarec.cpp:216: assertion failed in function void VifUnpackSSE_Dynarec::ModUnpack(int, bool): Vpu/Vif - Invalid Unpack! [3]

```

**Comment by saffiriogiorgio** [comment]
Still an issue on nightly release 2.1.93

![image](https://github.com/user-attachments/assets/41539d19-5a81-48d4-bae6-f194228e2165)
![image](https://github.com/user-attachments/assets/7284051a-3e17-4717-8219-b3d9411e0ad2)

I also tried EE Timing Hack as many others suggested in other threads but nothing changed.

**Comment by neosarif** [comment]
Still an issue on nightly release 2.1.93

![image](https://github.com/user-attachments/assets/41539d19-5a81-48d4-bae6-f194228e2165)
![image](https://github.com/user-attachments/assets/7284051a-3e17-4717-8219-b3d9411e0ad2)

I also tried EE Timing Hack as many others suggested in other threads but nothing changed.

**Comment by Jancoegers** [comment]
> Still an issue on nightly release 2.1.93
> 
> ![image](https://github.com/user-attachments/assets/41539d19-5a81-48d4-bae6-f194228e2165) ![image](https://github.com/user-attachments/assets/7284051a-3e17-4717-8219-b3d9411e0ad2)
> 
> I also tried EE Timing Hack as many others suggested in other threads but nothing changed.
> 
> Edit: Tested on 1.6.0 stable, it triggers the same error but after selecting "ignore" the game continues to play although the error "Unknown Vif Cmd" keeps to be detected until the battle is started
> 
> ![image](https://github.com/user-attachments/assets/304f89a7-992b-4655-b9ad-df1e7b4a70af)

I can confirm this as I stated before:



> I remember playing DW5:E multiplayer just fine with the stable version 1.6.0 about a year ago.
> 
> > Have the same issue. Using the newest nightly build. Tried different / stable version and it’s the same. I’ve tried searching for different dw5 empire roms. I’ve only found the same USA zip as well as some international version. I tried the EU/AU version and got the same error code.
> 
> I haven't think about using the stable version to play nor test it until your reply came, so I did my own test and you're right! The error is occurred, but you can choose **'Ignore'** and the game could continue to run (Although I do not playing it any further at the time of this writing) unlike the nightly build that keep getting the error messages over and over again.
> 
> Here is the result after choosing **'Ignore'**: ![Screenshot 2023-03-11 155049](https://user-images.githubusercontent.com/125797011/224475258-5e838ad4-8a98-44ad-97eb-31ba7389bfab.png)

It works in 1.6.0 after choose '**Ignore**' as I and @neosarif experienced.

**Comment by Technostrophe** [comment]
No crashes observed with https://github.com/PCSX2/pcsx2/pull/12028, went through it a dozen times, picking different areas of invasions, adding a second player, no error message appears anymore.
