### ISSUE TITLE
[BUG]: PCSX2 crashes when trying to run a game using vulkan on Wayland

### ISSUE THREAD

**Issue by pupilo-py** [PCSX2/pcsx2#8198]
### Describe the Bug

Using the X11 graphics server works perfectly, but when I switch to the Wayland graphics server and try to run a game using vulkan, PCSX2 closes instantly, both in the appimage version and in the flatpak version.

![pcsx2_crash](https://user-images.githubusercontent.com/58078395/219949884-7239fb7c-91ff-4cce-9624-3997e4762242.png)

### Reproduction Steps

1 - Change the X11 graphics server to Wayland
2 - Use the Vulkan API
3 - I try to run a game
4 - PCSX2 closes.

### Expected Behavior

Run the game using the Vulkan API.

### PCSX2 Revision

v1.7.4116

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Kubuntu 22.10

**Comment by Mrlinkwii** [comment]
What's your system specs

**Comment by pupilo-py** [comment]
> What's your system specs

![image](https://user-images.githubusercontent.com/58078395/219950074-494e85db-8c7f-4d11-a124-7d02523b090c.png)

**Comment by stenzek** [comment]
Why are you reporting issues with the flatpak here?

Wayland works fine (or, well, as well as it does, since the whole thing is fundamentally broken).

<img width="995" alt="image" src="https://user-images.githubusercontent.com/11288319/219950189-e2445ec9-6e30-4014-8302-188be77bb128.png">

**Comment by pupilo-py** [comment]
I explained that this happens both in the appimage version and in the flatpak version

and the problem occurs when I use Vulkan on Wayland.

**Comment by pupilo-py** [comment]
Appimage version:
![image](https://user-images.githubusercontent.com/58078395/219951603-da49365c-16d2-4e1f-b03c-5a7cfc5a1b59.png)

**Comment by pupilo-py** [comment]
If I was only having this problem on the flatpak version, I wouldn't come here. But I am having the same problem in appimage version as well. In addition, I tested it several times and in different ways, precisely so as not to disturb your work.

**Comment by pupilo-py** [comment]
video proof:
![pcsx2_crash](https://user-images.githubusercontent.com/58078395/219952290-9a4ace17-b993-4776-a789-4205dca4646c.gif)
