### ISSUE TITLE
Smackdown vs Raw 2007 (PAL) cutscene timing problems.

### ISSUE THREAD

**Issue by Silanda** [PCSX2/pcsx2#82]
As per the description, the voiced cutscenes appear to run too fast, leading to an audiovisual desync and the scenes ending early. This is with no speedhacks on and occurs irrespective of gsdx mode or backend, and is using a current build. There are similar problems with the other games in the series too (SvR, the earlier Smackdown games seem to work fine), with lurching speed ups during wrestler entrances. 

The framerate counter does not show any untoward changes from 50fps, which makes it look like a timing problem internal to the emulator. It also sounds the same as the problem described some time ago here: http://forums.pcsx2.net/Thread-WWE-Smackdown-Vs-Raw-2k6-to-2010-Common-Problem

My Specs:
Intel i5 3570k @ 4.4 GHz
Nvidia GTX 780ti
16GB RAM
Windows 8.1

**Comment by ssakash** [comment]
@Silanda 

>> I've also tried changeing the code for the middle speedhack in iR5900-32.cpp to this:

case 2: // Sync hack x2
scalarLow = 2;
scalarMid = 3;
scalarHigh = 2;
break;

could you observe whether -1 (or) -2 on EE cyclerate produces better result on resolving the issues ? ( it's not the right fix though )

**Comment by MrCK1** [comment]
@Silanda Any status update on this?

**Comment by Silanda** [comment]
Wow, I'd forgotten about this. I just had a very quick play around with my somewhat recent build, and things seem okay. I'll test it more thoroughly tomorrow with a new, completely up to date build, and report back.

**Comment by Silanda** [comment]
Okay, tested again. AV sync is still wildly out in some cutscenes at default settings.

**Comment by MrCK1** [comment]
@Silanda just checking in for another update. Any idea if it's still an issue?

**Comment by Silanda** [comment]
Just had a quick go and I didn't see the audio sync problems. However, the videos on the Titantron don't play any more: they appear stuck on a single frame.

**Comment by refractionpcsx2** [comment]
Hopefully the Titantron's work on master now, however can you check for audio desync using PR #3862 ? If you have the NTSC version of course, if you're on PAL you might have to wait a bit longer.

**Comment by Silanda** [comment]
I've only got the PAL version I'm afraid.

**Comment by refractionpcsx2** [comment]
Darn, okay I'll ping you again when we add PAL to that PR :)

**Comment by tadanokojin** [comment]
I updated the PR but it sounds like the desync was sorted already.

**Comment by refractionpcsx2** [comment]
okay, well do the Trinitrons play on latest master now?

**Comment by refractionpcsx2** [comment]
Should be fixed on master now?

**Comment by seta-san** [comment]
i can confirm on the NTSC version that the audio desync used to happen and is now fixed.
