### ISSUE TITLE
[BUG]: Corrupted textures in Evergrace

### ISSUE THREAD

**Issue by Indextic** [PCSX2/pcsx2#8201]
### Describe the Bug

After a recent update, some textures in Evergrace seem to be corrupted. This is most noticeable on the pause menu, where many 2D elements are completely garbled. I was playing the game less than 24 hours prior with no issues, so there seems to be a very recent change causing this issue.
![pcsx2-qt_oaPbMwshgC](https://user-images.githubusercontent.com/51840096/219968774-5a0a550c-fb72-41c3-905e-6a1b97bef4a4.jpg)

I was able to fix this issue by simply rolling back to a previous version from a few days ago.
This issue is not being caused by any of my settings, as I downloaded a fresh copy of the newest version and ran into the exact same problem with default settings.

### Reproduction Steps

1. Using the newest version of PCSX2, start a new game in Evergrace.
2. After gaining control of the main character, open the pause menu.

### Expected Behavior

This is what the pause menu looks like in version 1.7.4107. I do not know if this is the last version where everything works properly, I just chose an older version from a time when I knew the game was working for me.
![pcsx2-qt_ofHNsgjvh4](https://user-images.githubusercontent.com/51840096/219968941-71454ab1-db15-4659-9d9d-583047a4631e.png)

### PCSX2 Revision

v1.7.4118

### Operating System

Windows 10 (64bit)

### CPU

i9-9900K

### GPU

GTX 2080 Ti

**Comment by Mrlinkwii** [comment]
GS dump?

**Comment by Indextic** [comment]
Sorry, new to this. Is this what's needed?
[EvergraceTextureBug.zip](https://github.com/PCSX2/pcsx2/files/10777693/EvergraceTextureBug.zip)

**Comment by refractionpcsx2** [comment]
Still broken in SW mode, damn I suspect a GS readback then :(

**Comment by refractionpcsx2** [comment]
Yeah it broke with #8188 I suspect this will be a From Software pandemic, because Armored Core 3/Silent Line is also broken.

**Comment by RoyalNexus** [comment]
Hi,

This has also introduced texture corruption in another From Software title, Eternal Ring. Software renderer _seems_ to fix it but I can't confirm if it's just completely random or not.

Hardware:
![pcsx2-qtx64-avx2_yEoa2YNq55](https://user-images.githubusercontent.com/45250649/219982718-b956f968-ff96-4d1d-9040-b48094641de8.png)

Software:
![pcsx2-qtx64-avx2_4mwjzaE5hw](https://user-images.githubusercontent.com/45250649/219982778-8a14e660-ebf3-442a-85fb-23bb79edbafb.png)

Also, it seems to only happen to these very initial textures. Playing through the next 10 minutes of the game yielded no other texture corruption. Interestingly if I backup and leave the initial cave immediately and go back out to the beach, the texture corruption can still be seen, however going back inside and waiting some 15 to 30 seconds fixes it.

![pcsx2-qtx64-avx2_CicSkHWnC0](https://user-images.githubusercontent.com/45250649/219983770-5a7e1a6d-45e5-46ef-9ffc-ac2ca3f09669.png)

![pcsx2-qtx64-avx2_eI6VPgaQhc](https://user-images.githubusercontent.com/45250649/219983781-3ecb87cb-f205-4b74-b33c-4e11ba8f0874.png)

**Comment by refractionpcsx2** [comment]
Yep, as I said, seems to be all From Software games, except King's Field IV, weirdly.

**Comment by refractionpcsx2** [comment]
Should all be fine again in 1.7.4130 (once it's built)

**Comment by refractionpcsx2** [comment]
#8249 should hopefully fix Eternal Ring
