### ISSUE TITLE
[BUG]: Glitchy cutscene screen in tokyo xrteme racer drift 2

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#8203]
### Describe the Bug

the screen completely breaks when a racer cutscene occurs

### Reproduction Steps

just play the game until a cutscene pops up, it usually happens the most with racer cutscenes

### Expected Behavior

broken screen
![Screenshot (861)](https://user-images.githubusercontent.com/125753543/219984625-727d546c-d3e3-4e9d-8663-887e5c5e35f6.png)

### PCSX2 Revision

1.7.4117

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 3600

### GPU

gtx 1650 super

### GS Settings

widesceen
fmv widescreen
enable widescreen
anti blur
vsync
enable no interlace
disable interlace offset

6x native
af 16x
blending high
texture preloading ful

### Emulation Settings

mtvu
cheats

**Comment by Mrlinkwii** [comment]
can this be check on latest nightly :)

**Comment by refractionpcsx2** [comment]
It'll be the same

**Comment by Emi-pcsx2** [comment]
is it fixed yet

**Comment by refractionpcsx2** [comment]
You're welcome to fix it, if you're in a hurry.

**Comment by Emi-pcsx2** [comment]
Is it fixed yet

**Comment by Mrlinkwii** [comment]
@Emi-pcsx2 try and see ?

**Comment by Emi-pcsx2** [comment]
Ok i will and report back

**Comment by refractionpcsx2** [comment]
> Is it fixed yet

If it's not, you just added a year on to me looking

**Comment by Emi-pcsx2** [comment]
I asked because it's been a long time sorry if it sounded ironic or bossy

**Comment by refractionpcsx2** [comment]
I believe it was a transition between cutscenes

**Comment by Emi-pcsx2** [comment]
yea it is still broken

**Comment by forrvalhalla** [comment]
Probably a nothingburger comment here but it seems CPU Sprite Render 2 changes it a bit, you can actually tell there's a car outline with it enabled lol. Again, it's probably nothing but I figured I'd give a bump just in case this gives any leads.

![Kaidou - Touge no Densetsu_SLPM-61121_20230907000558 - Copy](https://github.com/PCSX2/pcsx2/assets/53349573/29257af0-061f-45c9-947a-fe82a13225af)
And since I haven't seen it mentioned: Tested and this issue is also present on 1.4 and 1.6.

**Comment by refractionpcsx2** [comment]
yes, it's a bad shuffle, I need to look in to it. Interesting how the SW sprite render makes it make more sense though, as the default  seems to evidently be repeating the bad texture.

**Comment by TheMilkmanCan** [comment]
Wanna chime in here: There is a cheat/patch to fix this that you can use in the meantime. Made by Strawberry Shortcake from the TXR Discord Server.

[Fixes\Coloured Boxes Fix]
comment=Removes the coloured boxes before a race with a tricker
author=Strawberry Shortcake
patch=1,EE,203f5a1c,extended,3A83126F

Believe its for the US version only. Plop it into the .pnach and give it a go!

**Comment by Emi-pcsx2** [comment]
is it fixed? Sorry for not responding

**Comment by refractionpcsx2** [comment]
yes

**Comment by Emi-pcsx2** [comment]
> yes

Hello, I am on github app and idk how to report a problem, but in NTSC-U rumble racing, in dx12 the car shadows are flickering Very hard.

**Comment by refractionpcsx2** [comment]
Make a new issue for it, when you're not on the app.

**Comment by Emi-pcsx2** [comment]
Can you link me the website issue place please

**Comment by refractionpcsx2** [comment]
https://github.com/PCSX2/pcsx2/issues
