### ISSUE TITLE
[BUG]: PCSX2 hangs when I close ANY game. 

### ISSUE THREAD

**Issue by Crozh** [PCSX2/pcsx2#8204]
### Describe the Bug

Simply, whenever I get out of any game the application stops responding, I can move it around but that's all about it. 
Summarized: The "Confirm Shutdown" pop up disappears whenever I'm closing a game on fullscreen and renders the application useless, since it's on stand-by expecting me to hit a dialogue that doesn't exist. 

### Reproduction Steps

1. Open PCSX2 
2. Enable Fullscreen
3. Enable "Confirm Shutdown"
4. Execute any game  
5. Close game at any point 
6. Return to PCSX2 

### Expected Behavior

Game closes without showing the "Confirm Shutdown"  pop up, application hangs and hogs your resources as if the game were running.

### PCSX2 Revision

1.7.3761

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch KDE

**Comment by stenzek** [comment]
Can't reproduce, works fine here on both Wayland and X11.

Not much we can do about a "bug" which doesn't happen on our end if you're unable to debug it. Maybe use the pause menu instead.

**Comment by Crozh** [comment]
It's kind of strange to be fair, the thing doing it is the pop up flashing and disappearing if it's on fullscreen; fortunately it is a non-issue since I can turn it off.
