### ISSUE TITLE
[BUG]: PlayStation 2 boot logo corruption if game region is not same

### ISSUE THREAD

**Issue by megabytedesu** [PCSX2/pcsx2#8205]
### Describe the Bug

Hi, when is booting any ps2 game with Bios USA but the game is PAL, the boot logo is corrupted, but if the game is USA region, ALL GOOD.
Same if the bios is EURO and game iso is USA.

### Reproduction Steps

Just boot any USA game with EURO bios, or vice versa

### Expected Behavior

Correct boot logo, in any region game, with any region Bios

### PCSX2 Revision

v1.7.4118

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5700g

### GPU

GTX 1070

**Comment by RedDevilus** [comment]
The corrupted boot logo is I think just the encryption they did and every region has it's own encryption and when it mismatched regions it will look off, which means this is accurate behaviour:

- Example:
https://youtu.be/0ybUyKxHWxY?t=1432

Unless I'm wrong.

**Comment by refractionpcsx2** [comment]
The encryption is different per region, and relies on the disc to provide the decryption key, this is not a bug, this is jut how it is.
