### ISSUE TITLE
[Feature Request]: Automatic Cover Downloader

### ISSUE THREAD

**Issue by Odium78** [PCSX2/pcsx2#8206]
### Description

hello I'm currently using the cover downloader for the PCSX2, but it feels repetitive that I have to paste the url of the covers over and over again, at least add sort of a history on the previous urls I have put.

### Reason

It will be easier to download the cover art without going to another repo, copy its link, paste it to the cover downloader over and over again after installing ROMs

### Examples

Make a Prompt that a new ISO detected and would like to download a cover art using the cover art link the user provided.
or
keep the cover art link in the box so I wont have to get the link again.

**Comment by stenzek** [comment]
Been over this many times, not happening, the idea is for you to use your own server (which you should always know). Not to enable piracy.

**Comment by Odium78** [comment]
downloading pngs isn't piracy

**Comment by stenzek** [comment]
It absolutely can be argued to be. Covers are copyrighted, and the copyright owner did not give you or some web site permission to distribute them.

Hence why it's intended to work with your own artwork and servers.

**Comment by refractionpcsx2** [comment]
We got a takedown request for pcsx2.net because of screenshots, so png's can very much be copyrighted, especially covers which can be used to produce counterfeit versions.

**Comment by Someguy14201** [comment]
At least let us save our own URL for the cover downloader so it automatically uses OUR url to download. Instead of having us paste manually everytime.

**Comment by mulices396-cell** [comment]
Hola saludos cordiales soy ulicesmedina de argentina cuando  sale  la
versión Android 15
