### ISSUE TITLE
[Feature Request]: if the the exe is scanning a big folder / drive i dont want on reopen to continue

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8219]
### Description

I added by mistake to scan my 5 TB drive for games 
After i closed the tool on reopen it resumes scanning with no way to stop it .I want to be able to stop it .

### Reason

The exe is stuck scanning TB of data for games with no way to gracefully stop it.I am stuck now with a non responsive .exe

### Examples

Other sw use a separate thread for scanning for games which doesnt block the GUI. A stop button can be added which cancels this operation on reopening of the tool.

**Comment by Mrlinkwii** [comment]
settings-> interface-> game list , and remove the  path , this is a user issue , please join the discord for support

**Comment by ISuckGood** [comment]
Its an user and tool issue .I disagree.

**Comment by refractionpcsx2** [comment]
delete your ini file and reopen the emulator. it doesn't block so I'm not sure what's going on for you.

If you want support please use the discord/forum, the github is not for that.

**Comment by ISuckGood** [comment]
I dont know why this issue is closed . The .exe still hangs on big folder scan. This is not a support issue . Its a tool issue.

**Comment by refractionpcsx2** [comment]
Doesn't hang for me
