### ISSUE TITLE
Changing FPS counter to a percentage of speed

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#822]
As discussed in Issue https://github.com/PCSX2/pcsx2/issues/444#issuecomment-136069572, I'd like to request that the FPS counter in the GS window's title bar be changed to a percentage of speed. So if a PAL game is running at 25 "FPS" we'll just show it as "50%" in the title bar.

**Comment by yorkiesandskittles** [comment]
Will it be able to compensate for PAL games that natively run at 25FPS e.g.
Sonic Heroes?

**Comment by willkuer** [comment]
I think you are talking about internal fps. In that case the answer would be yes.

**Comment by ssakash** [comment]
I have made that change here: https://github.com/PCSX2/pcsx2/pull/827

though I've replaced "FPS" with "Game Speed", I suck at picking words. so if anyone has a better alternative word in mind, feel free to mention. :)

**Comment by karasuhebi** [comment]
Thanks @ssakash!
