### ISSUE TITLE
[BUG]: Chaos legion needs Half pixel offset "Normal vertex" instead of "Special Texture"

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#8220]
### Describe the Bug

The game has some transparent lines "But you can notice it" when the automatic hardware renderer fixes are activated. It is configured as "Special Texture" but needs "Normal vertex" to look perfect. 

Images attached. You can see the problem in the very center of the screen "Character's hair"

### Reproduction Steps

Just start the game with the automatic hardware renderer fixes, move the camera slowly to see the lines or move the camera closer to the character.

### PCSX2 Revision

Any 

### Operating System

Windows 11

### CPU

i7 4790k

### GPU

GTX 970

### GS Window Screenshots

![1 Special texture](https://user-images.githubusercontent.com/12205048/220460052-9712f9b1-e79b-4edc-a033-b212a64cb605.png)
![2 Normal Vertex](https://user-images.githubusercontent.com/12205048/220459433-64165506-222d-4ebb-a407-141c2005a0e5.jpg)
![3 Special texture](https://user-images.githubusercontent.com/12205048/220459067-fb2c3acb-e576-4658-b634-bf0e082e2cea.png)
![4 Normal Vertex](https://user-images.githubusercontent.com/12205048/220459091-1c617e62-0258-4f3f-9794-885653e6bacb.png)

**Comment by Mrlinkwii** [comment]
GS dump?

**Comment by LuismaSP89** [comment]
> GS dump?
Here you go:
[snaps.zip](https://github.com/PCSX2/pcsx2/files/10797870/snaps.zip)

You can notice this problem on the center of the screen "Please, do zoom on the image to see it better"

**Comment by refractionpcsx2** [comment]
how does the special effect during the first boss look when upscaled? That bright light effect tends to cause problems when upscaling and not using special texture.

**Comment by LuismaSP89** [comment]
> how does the special effect during the first boss look when upscaled? That bright light effect tends to cause problems when upscaling and not using special texture.

To be honest, I don't know, i didn't reached the first boss yet. I'm not planing to play this game as by now, I was only testing some games from my library. But If I have time (Seems +20 min or more to reach the first boss) I'll check it

**Comment by refractionpcsx2** [comment]
To be honest HPO Normal breaks the screen a lot for me, not just he boss fight, there's a lot of left and top border mess from it, so it's not really feasible on this game.

**Comment by Mrlinkwii** [comment]
as refraction mentioned that HPO Normal is not feasible on this game
