### ISSUE TITLE
[BUG]: SLUS-21464 — Winning Eleven - Pro Evolution Soccer 2007: Noisy image on hardware renderer

### ISSUE THREAD

**Issue by KawaiiDinosaur** [PCSX2/pcsx2#8222]
### Describe the Bug

When using the hardware renderer at the native PS2 resolution, the output is very noisy.

![Winning Eleven - Pro Evolution Soccer 2007_SLUS-21464_20230221234655](https://user-images.githubusercontent.com/36821201/220512477-cbcaf031-78b2-420e-bc1b-0cc09849158a.png)

### Reproduction Steps

Start a match at any game mode.

### Expected Behavior

The picture looks as it should on the software renderer.

![Winning Eleven - Pro Evolution Soccer 2007_SLUS-21464_20230221234717](https://user-images.githubusercontent.com/36821201/220512547-4f4b5d77-6434-47f7-bd62-7459d52e96d2.png)

### PCSX2 Revision

v1.7.4125

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 7 3700X

### GPU

RX 6750 XT

### Logs & Dumps

[Winning Eleven - Pro Evolution Soccer 2007_SLUS-21464_20230222002132.zip](https://github.com/PCSX2/pcsx2/files/10799751/Winning.Eleven.-.Pro.Evolution.Soccer.2007_SLUS-21464_20230222002132.zip)

**Comment by refractionpcsx2** [comment]
Best guess, it needs Mipmap full + trilinear (ps2)

**Comment by KawaiiDinosaur** [comment]
Changing mipmapping from Automatic to Full (PS2 Mipmaps) solved the issue, even with trilinear off.

![Winning Eleven - Pro Evolution Soccer 2007_SLUS-21464_20230222004930](https://user-images.githubusercontent.com/36821201/220517477-95d82ae1-1247-46d3-9a54-d0e7edaf4d19.png)

**Comment by refractionpcsx2** [comment]
Yea, it's just we might as well have trilinear too, it's basically free at that point xD

Hopefully one of the tester guys can do a gamedb entry for it so it's in automatically for you and others
