### ISSUE TITLE
Choice of cover art scaling filter, as existing method results in blurry art. [Feature Request]: 

### ISSUE THREAD

**Issue by brad86m** [PCSX2/pcsx2#8224]
### Description

The current cover art scaling filter blurs the source image. I have spent a lot of time acquiring very high quality cover art over the years, and would like to display them without the blurriness that the current scaling causes.

### Reason

.

### Examples

.

**Comment by Mrlinkwii** [comment]
the scaling is done by Qt, PR's welcome

**Comment by stenzek** [comment]
If you're not going to be bothered to write a proper request with examples, I'm not going to be bothered to try to guess why it's behaving like this.

**Comment by brad86m** [comment]
> If you're not going to be bothered to write a proper request with examples, I'm not going to be bothered to try to guess why it's behaving like this.

It's pretty self-explanatory. No need for the attitude. 

I appreciate all your efforts to the emulation scene in recent years, but my god do you have mood swings and poor attitude towards a lot of people, when it is just not justified.

**Comment by stenzek** [comment]
There's no "attitude". You blatantly ignored the template, typing nothing but a period in the fields. So how are we supposed to know what you're asking for?

**Comment by brad86m** [comment]
Again, the title is surely enough for this request/fix. You;re using a scaling filter for cover art that results in blurry images. A simple bicubic, or even nearest neighbour (raw) will fix the issue. 

Not interested, then don't bother. Thanks anyway. I won't ask here again for anything else.

**Comment by stenzek** [comment]
The template has fields for a good reason. Ignoring them because you think "a title is enough" is not being respectful, considering you're asking us to go out of our way to action your request.

Jumping straight to personal/character attacks because we couldn't read your mind, well, that clearly shows who has an attitude problem. I'll leave it at that.

**Comment by RedDevilus** [comment]
If I would make a request like that without following template, it would get closed as well.
