### ISSUE TITLE
CRASHES ALWAYS [BUG]: 

### ISSUE THREAD

**Issue by hermis2016** [PCSX2/pcsx2#8226]
### Describe the Bug

I started using the emulator recently on Ubuntu 22.04, it always crashes after only a few minutes of it being running and logs me out of my PC.

### Reproduction Steps

Just open the app normally and try to use it.

### Expected Behavior

I expected the app to run smoothly.

### PCSX2 Revision

v1.7.4126

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04

**Comment by stenzek** [comment]
Please use the Discord server for support, this is not a complete bug report, or indicative of a bug.
