### ISSUE TITLE
[BUG]: Final Fantasy X Anti-Blur Hack Breaks Shadows

### ISSUE THREAD

**Issue by vcx33** [PCSX2/pcsx2#8227]
### Describe the Bug

There's an issue with the anti-blur hack, previously this hack wasn't necessary but now without it the game is very blurry, but this causes another issue. The game mostly uses circle shadows, but in 2 specific instances it uses proper real time shadows, when anima uses her overdrive and when fighting the seymour omnis boss. This hack breaks the real time shadows and they appear interlaced. Also happens on software mode.

![shadow1](https://user-images.githubusercontent.com/118646244/220737828-5dec06d0-af14-4502-8fa2-647f843aefd3.jpg)
[Final Fantasy X International_SLPS-25088_20230222173607.gs.zip](https://github.com/PCSX2/pcsx2/files/10807648/Final.Fantasy.X.International_SLPS-25088_20230222173607.gs.zip)
![shadow2](https://user-images.githubusercontent.com/118646244/220737814-43eb0795-1dac-4447-9d80-38eaa2f7606b.jpg)

Correct Effect
![shadow normal1](https://user-images.githubusercontent.com/118646244/220737912-b921349a-ae01-469b-be10-9db59746207b.png)
![shadow normal2](https://user-images.githubusercontent.com/118646244/220737936-55902157-0545-417f-9d3b-c9e6c42fd20a.png)

### Reproduction Steps

enable the anti-blur hack and use anima's overdrive or fight seymour omnis

### PCSX2 Revision

1.7.4126

### Operating System

Linux (64bit) - Specify distro below

**Comment by GitHub-Khi** [comment]
You are right. The PAL-Version is also affected.

Single Frame GS-Dumps:
[Final Fantasy X-2_SLES-51817_20230222212104.zip](https://github.com/PCSX2/pcsx2/files/10808018/Final.Fantasy.X-2_SLES-51817_20230222212104.zip)

**Comment by vcx33** [comment]
[Final Fantasy X International_SLPS-25088_20230222201951.gs.zip](https://github.com/PCSX2/pcsx2/files/10808035/Final.Fantasy.X.International_SLPS-25088_20230222201951.gs.zip)
[Final.Fantasy.X.International_SLPS-25088_20230222173607.gs.zip](https://github.com/PCSX2/pcsx2/files/10808037/Final.Fantasy.X.International_SLPS-25088_20230222173607.gs.zip)
GS dumps

**Comment by BParks21** [comment]
Yeah FF X-2 comparison, was wondering what was causing this. 
![Screenshot (87)](https://user-images.githubusercontent.com/12180630/229644078-dd3faa1d-21c2-43e2-a6d3-c729d6aded22.png)
![Screenshot (86)](https://user-images.githubusercontent.com/12180630/229644083-c9cd949c-c1d7-449d-b59d-e96ed8e878dd.png)

**Comment by refractionpcsx2** [comment]
#8564 should fix it.

**Comment by BParks21** [comment]
Sick!
