### ISSUE TITLE
[BUG]: The SpongeBob SquarePants Movie bloom not working correctly.

### ISSUE THREAD

**Issue by TailsGuy** [PCSX2/pcsx2#8230]
### Describe the Bug

In the level "Now That We're Men..." bloom is glitched. I've attached a picture below. This is both viewable in resolutions above native, and at native resolution.

There's another glitch when you go beyond the window size resolution too.
When you're at 2x screen size (720p) and 4x resolution (1440p) it seems that there are vertical lines showing up on the screen.
I think this may be the dithering freaking out.
[These aren't internal resolution pictures.]

![SpongeBob SquarePants - The Movie_SLUS-20904_20230223031245](https://user-images.githubusercontent.com/70661792/220853331-3a5909fe-2f3f-48ff-ab47-a027b36f7886.png)

![SpongeBob SquarePants - The Movie_SLUS-20904_20230223031636](https://user-images.githubusercontent.com/70661792/220854063-db361909-4af4-463f-9f75-41201e12af4f.png)

### Reproduction Steps

Enter the level "Now That We're Men..." and you'll immediately see that there are blobs of yellow around the screen.

### Expected Behavior

Turn on Software Rendering and see what the original is supposed to look like.
There's some strong bloom in this game, and it's supposed to be radiating from the weird acid substances in the level.
No renderer fixes this other than Software.
![SpongeBob SquarePants - The Movie_SLUS-20904_20230223031443](https://user-images.githubusercontent.com/70661792/220853683-677ba507-8206-4e48-9c4f-74394acba7b3.png)

### PCSX2 Revision

v1.7.4126

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5700X (Undervolted, 4850mhz, Pretty stable.)

### GPU

EVGA GeForce RTX 3070 FTW3 Ultra

### GS Settings

![Screenshot 2023-02-23 031949](https://user-images.githubusercontent.com/70661792/220854763-e455810c-2a41-4a39-887e-2fd80ec35806.png)
![Screenshot 2023-02-23 032009](https://user-images.githubusercontent.com/70661792/220854772-23f22bc7-f45b-42be-b261-a31689ccdb9c.png)

### Emulation Settings

Default settings

### GS Window Screenshots

Well, they're in the bug descriptions.

### Logs & Dumps

[Spongebob GSDump.zip](https://github.com/PCSX2/pcsx2/files/10811581/Spongebob.GSDump.zip)

**Comment by kamfretoz** [comment]
Tested the GS Dump, game need Texture inside RT now.

![Screenshot_20230223_184943](https://user-images.githubusercontent.com/14798312/220897874-3e666ccd-68e8-458f-b10b-3012c31cc499.png)

also tested on another level which are also seems affected.
Before:
![Screenshot_20230223_190155](https://user-images.githubusercontent.com/14798312/220900295-17478a2a-d222-4c62-a422-9ec9e0c0d9f8.png)

After
![Screenshot_20230223_190114](https://user-images.githubusercontent.com/14798312/220900318-f00468a9-fa93-4cb8-8177-72a9fec623e1.png)

Notice the missing bloom.
