### ISSUE TITLE
[BUG]: Rom manager won't boot up rom instead boots up the emulator GUI

### ISSUE THREAD

**Issue by gabonsonofgabon** [PCSX2/pcsx2#8240]
### Describe the Bug

Downloaded rom manager couple of days ago, dolphin and pcsx2 booted up the specific rom fine, however I did a steam update then it wouldn't start the rom instead it only opened pcsx2 and dolphin application not the rom

### Reproduction Steps

Adding pcsx2 in rom manager
then hitting play on steam and it not booting up the rom but booting up pcsx2

### PCSX2 Revision

1.6

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Ask whoever made this "rom manager", nothing to do with us.

We also don't take new issues for 1.6, it's long stale.

**Comment by gabonsonofgabon** [comment]
apologies thought I posted this in there bug list my mistake
