### ISSUE TITLE
[Feature Request]: Frame rate patches

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8243]
### Description

PCSX2 has a separate cheat folders for widescreen patches and no-interlace patches. So, why not have one for frame rate patches?

### Reason

Just like ws and ni patches, less patch hunting on Google. Every patch condensed in one .zip is always more convenient for the user. Although it may need some curation process since not all frame rate patches are flawless.

### Examples

None that I can't think of.

**Comment by stenzek** [comment]
How many of those patches actually work correctly? Most of the "60fps patches" I've seen just change the vblank wait, and break the game/make it run at double speed...

**Comment by refractionpcsx2** [comment]
widescreen and no interlacing patches need special handling, that's why they are separate, 60fps patches do not, they should just "work", depending on the patch quality, so you can just dump them in your cheats folder.
