### ISSUE TITLE
[BUG]: EGBrowser running slower than normal when fully booted

### ISSUE THREAD

**Issue by SMB99thx** [PCSX2/pcsx2#8257]
### Describe the Bug

In newer builds of PCSX2, the game when fully booted (not fast booted) runs at 30 FPS instead of 60 FPS in the older builds.

### Reproduction Steps

Basically, run EGBrowser or any variants like EGBrowser BB, using any settings, on the recent builds. This will happen (note the 30 FPS)
![Screenshot 2023-02-25 21 57 32](https://user-images.githubusercontent.com/29501169/221360983-fcacf140-efe2-41f5-9dfe-2dee97171cdb.png)

### Expected Behavior

The game should run at 60 FPS normally. Here's a screenshot of me running EGBrowser with the build 3500. (note the 60 FPS)
![Screenshot 2023-02-25 21 57 15](https://user-images.githubusercontent.com/29501169/221361060-6eb64d54-7c80-44b0-9ed7-304e17246e25.png)

That running speed should be the correct one for EGBrowser. [This is an English patched version of EGBrowser recorded from years ago.](https://www.youtube.com/watch?v=vvcI_U9wi5o&t=82s) [This is a recording of EGBrowser BB from a real PS2.](https://www.youtube.com/watch?v=BLCh1SPBq-0)

### PCSX2 Revision

1.7.4141

### Operating System

Windows 11

### CPU

i7-10750H

### GPU

GTX 1650

### GS Settings

![Screenshot 2023-02-25 220600](https://user-images.githubusercontent.com/29501169/221361312-349c6a76-a9b3-4665-839a-8d11fe360943.png)

### Emulation Settings

![Screenshot 2023-02-25 220625](https://user-images.githubusercontent.com/29501169/221361321-b3fbb263-b3a0-48d6-8c8f-8ab8530b66a1.png)

### GS Window Screenshots

![EGBrowser BB_SLPM-62176_20230225231901](https://user-images.githubusercontent.com/29501169/222308205-0ad9ac19-aaba-414a-bb0e-4dc1c8908198.png)

### Logs & Dumps

[GS dump](https://www.mediafire.com/file/2yn0nqdg9bw2r6k/EGBrowserBBSlowdown.zip/file)

**Comment by Mrlinkwii** [comment]
Gs dump?

**Comment by SMB99thx** [comment]
https://www.mediafire.com/file/2yn0nqdg9bw2r6k/EGBrowserBBSlowdown.zip/file
This one right?

**Comment by Mrlinkwii** [comment]
would it be possible to find out when the issue started?

**Comment by SMB99thx** [comment]
When fast-booting the game, it has always been running at 30 FPS, but this also happened to fully-booted one since build 1.7.3987.
![Screenshot 2023-03-14 20 00 59](https://user-images.githubusercontent.com/29501169/224996149-e949c46e-1f55-4ce1-9845-6d4232429827.png)
![Screenshot 2023-03-14 20 03 47](https://user-images.githubusercontent.com/29501169/224996185-ed37cd2d-2efa-4621-8256-2e164a9b1608.png)
It may have to do with #8014

**Comment by refractionpcsx2** [comment]
if fast boot has always been 30fps and full boot was different until I corrected the reset behaviour, I would say that it's now right and it was wrong before.

**Comment by refractionpcsx2** [comment]
anyway, closing for piracy.
