### ISSUE TITLE
[BUG]: GS dump crashing Qt

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#8266]
### Describe the Bug

Qt crashes when Gsdump is run when it is still scanning (see progress bar on bottom left)

![image](https://user-images.githubusercontent.com/24227051/221390471-fb207312-c5e5-4396-b127-dd1fdb77ad12.png)

![image](https://user-images.githubusercontent.com/24227051/221390499-6468c47d-3835-4ed3-86f1-5c24b9fd315d.png)
![image](https://user-images.githubusercontent.com/24227051/221390509-5904a01f-0907-409e-91c5-f5b55e576b00.png)

### Reproduction Steps

- Scan games
- Still busy scanning
- Run a Gsdump
- Crash

### Expected Behavior

Not crash emulator. It's similar behaviour to how in the past when you were scanning your HDD/SSD and you were adding BIOS it crashed (damn you fast hands)

### PCSX2 Revision

v1.7.4145

### Operating System

Windows 10 (64bit)

**Comment by ISuckGood** [comment]
I think i opened a similar bug report which was rejected as "user error". In my case i was scanning a 5tb drive and the GUI was becoming unresponsive the more it scanned until the QT GUI stopped responding

**Comment by stenzek** [comment]
Not the same thing. Scanning a 5TB drive is user error. Of course it's going to slow down.

This is a startup issue, possibly specific to gs dumps.
