### ISSUE TITLE
[BUG]: Lego Racers 2 slow when EE overclock active without much CPU usage when looking toward sun on Linux/Steam Deck after #8221

### ISSUE THREAD

**Issue by JimScript** [PCSX2/pcsx2#8268]
### Describe the Bug

When you look towards the sun(even when it is behind terrain) and have EE overclock active, then the game activates a readback which slows down the game _without taxing the system_. Strangely, this isn't an issue on my Windows 10 computer, only on my Linux Steam Deck.

### Reproduction Steps

Load up the appimage version of PCSX2 and set EE clock to any value higher than 100(but 300 is recommended since it's not a tough game to run generally), then load up a race or adventure and look towards and away from the sun to see how different it runs, and watch your system's usage to see how much it _isn't_ using.

### Expected Behavior

I'd at the very least expect to tax my CPU when it does this, or for some parity between Windows, but I also expect generally the same performance throughout.

### PCSX2 Revision

v1.7.4141

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

SteamOS 3.4.5

**Comment by stenzek** [comment]
Unlikely this is a regression, the game is specifically reading the Z buffer it's rendering to, presumably to test whether the sun is occluded.

So, working as intended. If the hardware can't keep up, that's not a bug.

**Comment by JimScript** [comment]
I feared as much, I don't know why I bothered posting, but I still can't wrap my head around why it doesn't use very much CPU when it slows down. Is it less the CPU and more how fast it can communicate with other components?

**Comment by RedDevilus** [comment]
Can range from something that is basically free or fine on console but punishing for modern devices to emulate to other potential causes. Driv3r is even slow on native resolution, Marvel Nemesis will take forever to look good and run good probably many years for hardware to catch up.

**Comment by stenzek** [comment]
GS downloads cause the EE thread to wait for the GS thread, which flushes the GPU command buffer, and waits the GPU to idle, and then returns. Then the GS thread goes to sleep until the EE pushes more draws. Thus losing all parallelism. That's why the usage isn't maxed, all the threads are waiting for each other.

It's worse on mobile chips, because they aggressively downclock, which makes the time-to-idle even longer.

**Comment by JimScript** [comment]
Thanks for the information and your time, maybe I should go to the PCSX2 reddit for stuff like this first.
