### ISSUE TITLE
[BUG]: Missing Blending Layer in Enthusia Professional Racing

### ISSUE THREAD

**Issue by DonelBueno** [PCSX2/pcsx2#8270]
### Describe the Bug

The blending layer is missing on cars, it can be seen on the car selection screen or during races. The only way to "fix" it is to switch to software mode and then switch back to HW mode. You have to do it everytime there is a screen transition.

Tried other backends, other blending accuracy levels, native resolution, no luck.

HW Mode:
![PCSX2_2023_02_26_09_21_40_923](https://user-images.githubusercontent.com/4239694/221410579-918fb2c6-d595-4ce3-9e59-a251b167795f.png)

SW Mode:
![PCSX2_2023_02_26_09_21_40_980c](https://user-images.githubusercontent.com/4239694/221410585-2a5fa85a-e06b-4b8d-97f4-c6728c304225.png)

HW Mode (after switching back from SW Mode):
![PCSX2_2023_02_26_09_21_41_858](https://user-images.githubusercontent.com/4239694/221410589-e2518b26-adc1-4c18-8b1b-dc3b4444fe50.png)

### Reproduction Steps

Boot the game and get to a car selection screen, swtich to SW mode, see the difference, switch back to HW mode and see the difference vanish.

### Expected Behavior

Proper bleding.

### PCSX2 Revision

v1.7.4147

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5800x

### GPU

GTX 1070

### GS Settings

![image](https://user-images.githubusercontent.com/4239694/221410652-2c5d9163-854a-4ae4-ad90-de34a1b9acbc.png)

**Comment by lightningterror** [comment]
GS dump?

**Comment by DonelBueno** [comment]
> GS dump?

Shift+F8 isn't working. Do I need to enable an option?

**Comment by Mrlinkwii** [comment]
> > GS dump?
> 
> Shift+F8 isn't working. Do I need to enable an option?

tools> single frame gs dump , preferably  in SW

**Comment by DonelBueno** [comment]
[GS Dumps.zip](https://github.com/PCSX2/pcsx2/files/10834135/GS.Dumps.zip)

Took one in HW and other in SW.

**Comment by coornio** [comment]
On a related note, it appears the game displays nothing on the screen when Bilinear Sharp is used specifically on the D3D12/Vulkan renderer. The others work fine. Very weird.

**Comment by stenzek** [comment]
Nothing to do with blending, it was tex-in-rt, but using a C32 target with a C24 texture (the opposite of what you normally get).. part of the Tomb Raider fixes also sorts this out.
