### ISSUE TITLE
[BUG]: Dx12 vs Vulkan issue with  render pass area ?

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8274]
### Describe the Bug

I am not sure but it looks like vulkan is doing extra checks/drawings based on values different than on dx12 variant  in regard to checking the render pass area. (rectangle)

### Reproduction Steps

1. start the debug variant where we have more logging 
2. start Digital devil saga and go to first seconds after intro where you can move your character 
3. observe that the console view is spammed with 
![image](https://user-images.githubusercontent.com/42075250/221420313-a32981d6-45d2-4c19-a7b0-33560a733b7e.png)

4. switch to dx12 and check the render area values and observe are different than vulkan ones 
![image](https://user-images.githubusercontent.com/42075250/221420427-c29938f7-990b-4349-8a78-590bee2a6bdc.png)

I am not sure if these differences between the 2 renderers are intended or there is some issue with the coordinates of the drawing area

### Expected Behavior

Vulkan and OpenGl performance are not the same if we disable the frame rate limit . I got 220% on OpenGL/DX12 and 190%  speed increase on Vulkan in release version

### PCSX2 Revision

latest

### Operating System

Windows 11

**Comment by stenzek** [comment]
Restarting the render pass isn't an error. And it makes bugger all difference on desktop GPUs.

Vulkan being behind DX in readbacks isn't that uncommon. I saw the same behaviour when I used to work on Dolphin.

**Comment by ISuckGood** [comment]
Thank you for quickly clarifying this.
