### ISSUE TITLE
[BUG]: Save State doesn't work when swapping a disc

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#8275]
### Describe the Bug

This used to work with older versions of pcsx2 well before the UI change for sure.
This is how i noticed this issue, when starting code breaker 10 selecting cheats and swapping the disc the save state that is created isn't the crc of the swapped disc no it's the crc of  code breaker 10 (5207cca3 (5207CCA3).01) so when you start the game the game crashes when you try to lead the save state.

### Reproduction Steps

Starting code braker swapping the disc and creating a save state.
restarting the emulator selecting the game and try to load a save state the emulator will crash.

### Expected Behavior

Before the UI change it didn't crate the first boot crc save state file it created the swapped disc state file.

### PCSX2 Revision

1.7.4150

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
yes savestates wont work with swap disc ( probably never did)  due to do how saving savestates works  and i think would require  big rework to get them to work
