### ISSUE TITLE
[BUG]: Metal Gear Solid 3 intro cutscene rainbow border in both software renderer and hardware renderers.

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#8279]
### Describe the Bug

Metal Gear Solid 3 with latest build 4150 has now a rainbow line at the right side of the screen. This wasn't there just few days ago. 

It's not an upscaling issue or an hardware renderer issue because i tested it with software renderer and it still has this line. 

### Reproduction Steps

Just start the game, few seconds after intro starts you can already see a faint rainbow line.

### Expected Behavior

Intro should have no rainbow artifacts on the side.

### PCSX2 Revision

pcsx2 1.7.4150

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gt 1030

### Logs & Dumps

Gsdump

[Metal Gear Solid 3 intro2.zip](https://github.com/PCSX2/pcsx2/files/10834974/Metal.Gear.Solid.3.intro2.zip)

**Comment by bigol83** [comment]
Anyone else can test and see if it's some issue with my configuration or it's a real regression?

**Comment by refractionpcsx2** [comment]
I arbitrarily tried 1.7.3006 and the line was still there in software mode but not hardware, so I guess now we match software mode, at least :P

**Comment by bigol83** [comment]
I tested MGS3 on a widescreen LCD  with ps2 hardware and the rainbow line is there, so it's not an issue with the emulator, it's the way the game is coded. Probably that line was not meant to be seen on CRT screens so that's why I never really noticed it until this one test i did recently. So, the way it was before on Pcsx2 ( not showing this line) was not accurate to hardware. Generally accuracy means better graphics, in this case it uncovered an issue with the game itself. Like i said, they probably never thought about fixing it considering that CRT screens covered that part of rendering zone.

Anyway, the issue can be closed. In case you want to make the line disappear just use the crop option and crop 1 pixel to the right side.
