### ISSUE TITLE
[BUG] [Vulkan] True Crime NYC: Consistent Crashing 

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#8280]
### Describe the Bug

Using Vulkan, PCSX2 crashes consistently and constantly at specific spots ingame, such as while driving to specific locations outdoors or during cutscenes.  This does not occur with other renderers (tested OGL and SW).

Git bisect reveals the first bad commit to be 7d08a54ad9412d92757c5c4193b8f4c24e212d95

### Reproduction Steps

An easy way to reproduce the crash is to start the game, leave the station, get into a car, drive to 10th Avenue and turn right.  10th Avenue will eventually turn into Amsterdam Ave. PCSX2 will crash consistently as the car crosses the intersection of Amsterdam Ave. and 65th Street.

### Expected Behavior

PCSX2 behaves itself

### PCSX2 Revision

Commit 7d08a54ad9412d92757c5c4193b8f4c24e212d95

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.1

### CPU

Intel 10870H

### GPU

GTX 3070 / driver 525.78

### GS Settings

Will provide if needed.

### Emulation Settings

Will provide if needed.

### GS Window Screenshots

Will provide if needed.

### Logs & Dumps

Exception thrown to terminal is as follows:

```
pcsx2/common/Vulkan/Context.cpp:1257: assertion failed in function void Vulkan::Context::DoSubmitCommandBuffer(u32, Vulkan::SwapChain*, u32): Failed to submit command buffer.

Aborting application.
Aborted (core dumped)
```

**Comment by stenzek** [comment]
Record a GS dump in software, play it back in hardware. If it crashes, then upload it.

**Comment by Shoegzer** [comment]
Thanks. I assume you mean record a multi-frame GS dump. For some reason only single-frame dumps work - when using the hotkey for a multi-frame dump, I only get a single-frame result.  Any ideas?

**Comment by refractionpcsx2** [comment]
Either you're pressing the wrong keys (check hot keys in the controller setup area) or it's not registering a button for some reason. Maybe change the combo to something else, I use ctrl+O

**Comment by RedDevilus** [comment]
Control + Shift + F8 and hold it for amount of seconds you need, but it might be something annoying with your keyboard.
Shift + F8 only does single just like in GUI.

**Comment by Shoegzer** [comment]
Thanks, guys. I hadn't realized I had to hold the hotkey down, figuring it would record a block until the hotkey was pressed again. I've got it now.

I have the dump from SW, but how do I play it back in HW?  There doesn't seem to be a hotkey or menu item for that unless I'm just blind.

**Comment by refractionpcsx2** [comment]
Change to hw mode and go to "start file" and open it in your snaps folder

**Comment by Shoegzer** [comment]
Thanks, that worked.  It did crash, but the dump is over 800 MB.  I have a smaller dump that's over 300 MB but it was taken the moment it crashes so I'm not sure if it's a good dump.  Is there a place to upload either of these that would accept such large files?  Github itself only accepts files < 25 MB.

**Comment by refractionpcsx2** [comment]
Do you have a Google drive or something you can share it from?

**Comment by refractionpcsx2** [comment]
Also do compress it with 7zip,it will reduce it a lot

**Comment by stenzek** [comment]
>  I have a smaller dump that's over 300 MB but it was taken the moment it crashes so I'm not sure if it's a good dump. 

As long as it causes the crash if you open the file in hardware, but not software, it's fine.

**Comment by Shoegzer** [comment]
Nothing like that unfortunately.  However, I comressed the smaller dump with .7z and was able to get it under 300 MB which is the Sendspace limit, so here's a link to that: https://www.sendspace.com/file/oku324

.7z gets the larger dump down to around 750 MB but that's above any limits I'm aware of unless you know of a place I could use, assuming you still need that dump.

**Comment by stenzek** [comment]
Thanks. Try #8281 once it builds.

**Comment by Shoegzer** [comment]
Thanks! I made a custom build with that PR and can confirm it doesn't crash from texture uploads.

**Comment by Shoegzer** [comment]
Not sure we should close this just yet.  While the main test case no longer crashes, I dug a bit deeper and found another case where a crash continues to happen in the Vulkan renderer, at the start of a specific cutscene.  Again it does not crash in SW or OGL, so I created a [GS dump](https://www.sendspace.com/file/9y0pjb) in SW and observed it crashing when playing back in HW/Vulkan.  Hope it helps.

**Comment by stenzek** [comment]
Not seeing any crash or validation layer errors with that dump.

**Comment by Shoegzer** [comment]
That's odd but I'll take your word for it of course. Could it be related to linux builds? I'm seeing it occur with Vulkan during almost every cutscene in master builds now. [Here](https://www.sendspace.com/file/2wx65a) is another gs dump from a different cutscene, hopefully showing the crash.

System information:

* OS: Linux Mint 21.1 / kernel 5.19
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 525.78
* Compiler: gcc-11.3.0
