### ISSUE TITLE
[BUG]: Text is not visible in Dynasty Warriors 2

### ISSUE THREAD

**Issue by Mirraculous** [PCSX2/pcsx2#8285]
### Describe the Bug

In Dynasty Warriors 2, all of menu text is not visible. Happens on any renderer. It was working fine until I updated to latest nightly sometime in February (I always update to latest version when launching pcsx2).

### Reproduction Steps

Launch the game, go into Options menu. No text is visible.

### Expected Behavior

Correct rendering of text in menus.

### PCSX2 Revision

v1.7.4155

### Operating System

Windows 11

### CPU

i7-12700K

### GPU

RTX 3070 Ti

### GS Settings

First encountered this bug on 3x-native resolution. But it also happens on default settings, even while using software rendering.

### Emulation Settings

All settings are default.

### GS Window Screenshots

![Dynasty Warriors 2_SLUS-20079_20230227181352](https://user-images.githubusercontent.com/45313169/221580340-899b6d6f-32fe-4afc-be2a-5d1a234c6f76.png)

### Logs & Dumps

[Dynasty Warriors 2_SLUS-20079_20230227181352.gs.zip](https://github.com/PCSX2/pcsx2/files/10840230/Dynasty.Warriors.2_SLUS-20079_20230227181352.gs.zip)

**Comment by Technostrophe** [comment]
![billede](https://user-images.githubusercontent.com/124680696/221581329-b8561f8b-c8c8-4f8c-95ce-5e57a4acea95.png)
![billede](https://user-images.githubusercontent.com/124680696/221581395-f88254a1-9abc-450e-8e2e-04087b76f421.png)

This is on Software and Vulkan as of 1.7.4156, there has to be something on your end not being right.

**Comment by Mirraculous** [comment]
Thanks for checking this out. I was switching to SW renderer "mid-game" using F9 key in an attempt to fix this. Now I tried to switch to SW renderer BEFORE lauching the game, and the text behaves correctly. Still, the issue persists if the game is launched with an automatic renderer selection (Vulkan in my case), even on native resolution.

**Comment by Technostrophe** [comment]
I can attest to the same behavior now, should have been more thorough, my apologies for that. It only displays text if it starts in Software and you switch after. This affects all Renderers, from OpenGL to Vulkan.
