### ISSUE TITLE
[BUG]: Champions of Norrath (SLUS-20565) missing right half of the screen

### ISSUE THREAD

**Issue by mboch** [PCSX2/pcsx2#8287]
### Describe the Bug

The "half-screen" issue is back for Champions of Norrath when using any renderer except software. The issue is present even at default settings.

I narrowed it down to a regression in 1.7.4114 which appears to only contain this [merge](https://github.com/PCSX2/pcsx2/pull/8181) compared to 1.7.4113.

I've tried tweaking as many settings that I can think of, but no luck.

A few interesting things:
1. Changing the renderer while the game is running will fix the issue. For example, if the renderer starts as Vulkan, changing it to D3D12 will show the full screen. Changing the renderer back to Vulkan again will also maintain the full screen. This is true no matter the initial or final renderer.
2. The same is true when changing the resolution.
3. Champions: Return to Arms, Baldur's Gate Dark Alliance, and Baldur's Gate Dark Alliance 2 do not have this issue.

### Reproduction Steps

1. Download 1.7.4114 or later
2. Use the default settings
4. Load Champions of Norrath
5. Wait for the Sony Online Entertainment logo
6. Right half of the screen is now missing

### Expected Behavior

The right half of the screen should not be missing.

### PCSX2 Revision

1.7.4156

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5900X

### GPU

RTX 3080 Ti

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/8354696/221666520-fa87fc8f-783f-49ac-ad28-462d0499d701.png)

### Logs & Dumps

GSdump - [Champions of Norrath - half screen issue.zip](https://github.com/PCSX2/pcsx2/files/10841439/Champions.of.Norrath.-.half.screen.issue.zip)

**Comment by JordanTheToaster** [comment]
Appears fine here on latest.

![image](https://user-images.githubusercontent.com/80843560/221614820-dbff47ac-ccea-496d-a1ae-75f42d734325.png)

**Comment by Dreadmoth** [comment]
The issue doesn't seem to appear in GS dumps.

Reproduced with clean install, default config, PAL version:

![CoN_halfscreen](https://user-images.githubusercontent.com/8492684/221641590-ddc501d9-f176-4c58-9eba-0e482d816cda.png)
