### ISSUE TITLE
[BUG]: Rendering issue at higher resolutions in DQ8?

### ISSUE THREAD

**Issue by Kupo91** [PCSX2/pcsx2#8292]
### Describe the Bug

If I set the internal resolution to x3 in Dragon Quest VIII (PAL) it will build up a black bar on the right side of the screen...  
It's probably easier to show a video, so here it is:

https://youtu.be/I6_6UrXmL5Q

### Reproduction Steps

Sometimes it doesn't happen immediately, then I have to change the camera and walk around (like in the first seconds). Another time it happens straight forward.

### PCSX2 Revision

v1.7.4158

### Operating System

Windows 10 (64bit)

### CPU

i7-4790

### GPU

GTX 1050

### Logs & Dumps

[GSdump.zip](https://github.com/PCSX2/pcsx2/files/10849311/GSdump.zip)

**Comment by refractionpcsx2** [comment]
Not unexpected, but as it says in the issue template.

![image](https://user-images.githubusercontent.com/6278726/221832004-945e3ca0-139e-4460-a3d1-0dbc6ea892e1.png)

**Comment by crtJoe** [comment]
This seems to be a regression in recent nightly builds. Try v1.7.4117 or earlier and see if there's any improvement for you. I do see a black bar in earlier versions, but it hides itself pretty well. However, in recent nightlies there are multiple black lines on the right sides of the screen, and they are highly visible. This seems to be an old bug that's been fixed/mitigated and re-appears very recently.

https://wiki.pcsx2.net/Dragon_Quest_VIII:_Journey_of_the_Cursed_King
Black lines on edge of screen
Status: Fixed
Type: Minor
Description: When upscaling, black lines will appear along the bottom and right sides of the screen.

**Comment by bigol83** [comment]
This PR 

https://github.com/PCSX2/pcsx2/pull/8289

fixes it, but introduces a glitch with torches. That PR is still WIP though and @refractionpcsx2 is still working on it, so glitches are to be expected, Wait until it's merged.
