### ISSUE TITLE
[BUG]: Cannot change my file directory for my BIOS on linux

### ISSUE THREAD

**Issue by Susamongoose272** [PCSX2/pcsx2#8294]
### Describe the Bug

I cannot click on different file directories for my BIOS

### Reproduction Steps

On a linux os, go to the PCSX2 applicaiton and set up the settings. When it asks you for the BIOS and it opens the file manager, you can't click on any other file directories.

### PCSX2 Revision

latest

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian

**Comment by JordanTheToaster** [comment]
Please use the Discord for support issues.

**Comment by kamfretoz** [comment]
Works fine here on Arch Linux, not sure why it wouldn't work. 


Maybe check if your Desktop Environment is the culprit here?
