### ISSUE TITLE
[BUG]: God Of War 2, Steeds of time : Yellow crank doesn't play animation.

### ISSUE THREAD

**Issue by FireBlazR** [PCSX2/pcsx2#8298]
### Describe the Bug

The Yellow Crank in the image doesn't play animation and open up when I pull it.

![Godwar2_b04_196](https://user-images.githubusercontent.com/72492294/221949851-fc53f464-2421-41a5-b3cc-fd6b3b346472.jpg)

I have tried everything. I have replayed the game 3 times till this point, used 2 different iso files, tried both the stable and nightly build of pcxs2 and none it seems to work. Could anyone use these memcards and try if it works for you?

### Reproduction Steps

Load this save file and move towards the central part of the steeds of time. Rotate the yellow crank. Animation doesn't play

### PCSX2 Revision

v1.7.4161

### Operating System

Windows 11

### CPU

AMD Ryzen 5600H

### GPU

RTX 3050 laptop

**Comment by RedDevilus** [comment]
What save files? I don't see any posted.

**Comment by FireBlazR** [comment]
Sorry, I thought I had pasted the link
Here is the pcxs2 save file
https://drive.google.com/file/d/1k9BohirC3Nh8pqp6xEKHKc1uy-Oa89Qs/view?usp=share_link

**Comment by FireBlazR** [comment]
> What save files? I don't see any posted.
Sorry, I thought I had pasted the link
Here is the pcxs2 save file
https://drive.google.com/file/d/1k9BohirC3Nh8pqp6xEKHKc1uy-Oa89Qs/view?usp=share_link

**Comment by kevin98761234** [comment]
I was able to move on without any problems. This is the save right after the crank gimmick.
[gow2.zip](https://github.com/PCSX2/pcsx2/files/11008155/gow2.zip)

The image is too small to discern, but a possible cause of the problem is that you may not have turned the stick while holding down the R1 button. Is it a controller setting issue?

**Comment by Mrlinkwii** [comment]
is this still an issue on latest nightly

**Comment by FireBlazR** [comment]
No
