### ISSUE TITLE
Non-dll files included in bin/plugins directory for release builds

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#830]
They're package bloat.

**Comment by avih** [comment]
Could you be more specific please? Which files would you want removed?

**Comment by micove** [comment]
I'm guessing what is being called bloat is:
```
FOR /R "%~dp0\bin" %%F in (*.exe, *.dll) DO (
IF EXIST "%%~dpnF.bsc" del "%%~dpnF.bsc"
IF EXIST "%%~dpnF.exp" del "%%~dpnF.exp"
IF EXIST "%%~dpnF.ilk" del "%%~dpnF.ilk"
IF EXIST "%%~dpnF.iobj" del "%%~dpnF.iobj"
IF EXIST "%%~dpnF.ipdb" del "%%~dpnF.ipdb"
IF EXIST "%%~dpnF.lib" del "%%~dpnF.lib"
IF EXIST "%%~dpnF.pdb" del "%%~dpnF.pdb"
)
```

I could add my script to the repository and make it more newbie friendly. I'm currently cleaning/hand crafting all the projects so some disappear on my branch. The pdb files are not bloat so they remain. The .exp/.lib file will remain as long as the executable and plugins export symbols.

**Comment by avih** [comment]
How would they be useful to users?

Also @micove come over to irc.

**Comment by micove** [comment]
I meant it as they will always be generated by VS. The PDB files can't be unconditionally removed since then debugging would not work. The .exp/.lib are always generated due to leaking symbols from somewhere.

The build.cmd script could be updated to remove the "bloat" which is what I do.

**Comment by tony971** [comment]
If you download the binaries from the pcsx2 website, only the dll files are included. If you're building a release version, shouldn't this match?

**Comment by avih** [comment]
Oh, I misunderstood. I thought the builds at the buildbot include junk.

If it's only when building locally, then I don't think we should remove them. We don't have a "create a release package" script, and not including unrequired files would be the task of such script IMO. Not of building in visual studio.

**Comment by tony971** [comment]
Ah I just think of the bin directory as the "finished product" directory. Where everything would get copied into your PCSX2 install directory.

**Comment by avih** [comment]
It's not a finished product. It's the (release) build directory.

For a finish product we use the buildbot (I don't think the packaging script is part of the repository), or create an NSIS installer which includes only what's required.

I'm closing this issue, but please let me know if you think we should re-open it.

**Comment by micove** [comment]
@avih 

Yes, exactly. I have used the build.cmd as my unofficial "create a release package" script. I don't see any other use for that file. Also build.cmd is faster than the gui.
