### ISSUE TITLE
[BUG]: Going Commando cannot be finished.

### ISSUE THREAD

**Issue by mathew2214** [PCSX2/pcsx2#8300]
### Describe the Bug

Emulator crashes upon loading planet aranos

### Reproduction Steps

Play the game. Get to planet aranos. Crash.

### Expected Behavior

The level should load

### PCSX2 Revision

V1.7.4163

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

SteamOS

**Comment by stenzek** [comment]
Post a memory card or we can't investigate.

Also please note that we do not support emudeck.

**Comment by mathew2214** [comment]
here is the .ps2 file of my memory card. there is only 1 RAC2 save.
load the file, and once planet Aranos appears, the emulator freezes for a bit until it finally crashes. 

https://drive.google.com/file/d/1KepBa1yK8vA2RSsK9-_QgywyS0KHKjTt/view?usp=sharing

sorry for the gdrive link, github wont let me post the file directly for some reason.

**Comment by stenzek** [comment]
Seems fine to me. I also checked Linux.

<img width="599" alt="Untitled" src="https://user-images.githubusercontent.com/11288319/222097417-060cb3fe-825a-4650-9b23-c2c6d0b7af8e.png">

If you're using emudeck, could be why, or a bad dump. Without a backtrace I couldn't guess.

**Comment by Buzzardsoul** [comment]
Hi! @mathew2214 . Is your ee clock speed set at normal?

**Comment by mathew2214** [comment]
Yes it is. I've also tried the timing hack in the fixes menu. No change in behavior.

**Comment by F0bes** [comment]
Considering the EE is the main processor of the PS2 system and controls the DMAC, I would say the **EE** Timing hack has a relation to EE emulation 😉

**Comment by Buzzardsoul** [comment]
Regardless of what the fuck it is, or why it's named that way, it's not going to help @mathew2214 with fixing VU0 timing anytime soon.

**Comment by RedDevilus** [comment]
Neither is posting when you post on GitHub without it helping anyone for a moot point.
