### ISSUE TITLE
[BUG]: controls become stuck if PCSX2 window loses focus while playing a game

### ISSUE THREAD

**Issue by matheusvb3** [PCSX2/pcsx2#8306]
### Describe the Bug

This is derived from [issue 8196](https://github.com/PCSX2/pcsx2/issues/8196). If PCSX2 loses focus while input is being given to a game, that input will become stuck. You can cause this to happen by alt-tabbing or pressing the computer's screenshot key, which removes focus from the PCSX2 window. Resetting does not work, you have to quit and reopen PCSX2 for it to start working correctly again.

If "pause on focus loss" is enabled, the controls will still become stuck when focus is regained.

### Reproduction Steps

Launch any game, give it some input and alt-tab or press the screenshot key.

Using Ratchet & Clank as an example, if I press the key to make my character move forward and take an screenshot, he will keep walking forward forever.

### Expected Behavior

The controls should not become stuck.

### PCSX2 Revision

1.7.4146 AppImage

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Zorin OS 16.2

**Comment by stenzek** [comment]
Working as intended. If we never get the key up event, the input manager never knows it's been released.

Cycling the key will reset the state.

**Comment by matheusvb3** [comment]
Can I make it a feature request then? Also I'm not sure what you mean by cycling the key. I have to exit and reopen PCSX2 for it to work again.

**Comment by stenzek** [comment]
Press the key and release it after focus has been regained. That'll send both a down and release message, and the internal state of PCSX2 will be updated.

**Comment by matheusvb3** [comment]
Thank you very much, that will help a lot!

**Comment by stenzek** [comment]
I know it's not ideal, but there isn't really any other way of handling it if Qt doesn't get the event. The alternative would be constantly polling all keys' state, which is slow, and requires platform specific code.

**Comment by RedDevilus** [comment]
I use this bug as a feature, for photos/screenshots and other behaviours. Maybe an option to disable it on default for mormal gameplay makes sense though.
