### ISSUE TITLE
[BUG]: Depth Issues and Right side of screen problems in 10 Pin: Champions Alley

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#8313]
### Describe the Bug

There are two bugs with the game when running in HW mode.
1. Right side of menu screens is missing in HW mode. If you switch to SW mode and then back to HW the menu appears correctly.
2. In game have depth issues (mostly in right part of screen). This problem doesn't get solved by switching to SW mode and back. If you enable preload frame data the depth issues get fixed somewhat but then the flames disappear.

### Reproduction Steps

Start the game in HW mode and check menu screen and ingame

### Expected Behavior

Menus and ingame should appear correctly like SW mode.

### PCSX2 Revision

v1.7.4174

### Operating System

Windows 10 (64bit)

### CPU

i3-9100f

### GPU

GTX 1060

### GS Window Screenshots

![10 Pin - Champions Alley_SLES-53150_20230302201850](https://user-images.githubusercontent.com/12788199/222464568-b42896a4-7c5b-4255-be45-cb22c5be63dd.png)
![10 Pin - Champions Alley_SLES-53150_20230302201908](https://user-images.githubusercontent.com/12788199/222464578-8a7599ed-3c70-42a8-b7b7-36f6ef7ec1b4.png)
![10 Pin - Champions Alley_SLES-53150_20230302202003](https://user-images.githubusercontent.com/12788199/222464597-b5b375de-3f8c-4fcc-bc23-2595566925f8.png)
![10 Pin - Champions Alley_SLES-53150_20230302202709](https://user-images.githubusercontent.com/12788199/222464617-7ef5abc9-6ccd-4339-bd2b-fc47c7c3e0a4.png)

### Logs & Dumps

[10 Pin - Champions Alley_SLES-53150_20230302201908.gs.zip](https://github.com/PCSX2/pcsx2/files/10872580/10.Pin.-.Champions.Alley_SLES-53150_20230302201908.gs.zip)

**Comment by refractionpcsx2** [comment]
I imagine the two issues are directly related since they both conveniently split right down the middle of the screen :D

**Comment by refractionpcsx2** [comment]
#8289 makes this arguably better

![image](https://user-images.githubusercontent.com/6278726/225906179-368344ee-485e-442d-8d89-f6065b18209a.png)
