### ISSUE TITLE
[BUG]: No sound when using Logitech USB Headset (USB Plugin)

### ISSUE THREAD

**Issue by ShephardB3** [PCSX2/pcsx2#8316]
### Describe the Bug

on USB Port 1, using Logitech USB Mic or Logitech USB Headset. You will be able to see the mic showing, but when trying to talk, no sound will come from it, people won't be able to hear you and you won't be able to hear them. I tried games such as FlatOut 2 (people can hear you even if they don't have a headset), didn't worked, no sounds.
WX Widgets builds with USB implemented didn't had this issue at all when using the mics in Online games.

### Reproduction Steps

Try any Online working game that supports Headsets, Flatout 2 is the best exemple, when in a room, you will see that your mic is showing, but when trying to talk, nothing will happen, people won't be able to hear you.
![image](https://user-images.githubusercontent.com/126799811/222491767-bfb1a26a-ba25-4f1c-b87c-56d99116b4dd.png)

### Expected Behavior

the microphone icon is supposed to blink (!) whenever somones is talking in FlatOut 2 to hear any sound (I'm using WX)
![image](https://user-images.githubusercontent.com/126799811/222491767-bfb1a26a-ba25-4f1c-b87c-56d99116b4dd.png)
![image](https://user-images.githubusercontent.com/126799811/222491865-227cafa0-66d0-441c-9a59-99972b16202e.png)

### PCSX2 Revision

v1.7.4174

### Operating System

Windows 10 (64bit)

**Comment by ShephardB3** [comment]
I forgot to add the USB label….

**Comment by Mrlinkwii** [comment]
Can this be checked on latest nightly

**Comment by BOBCAMO** [comment]
figured i'd put my comment in here as someone who wants this also fixed since it still doesn't work right.

**Comment by stenzek** [comment]
Please don't bump threads such comments. It doesn't matter how many people "want this fixed", someone has to be interested in investigating why it's broken.
