### ISSUE TITLE
[BUG]: Gun Survivor 3 Dino Crisis cutscenes are interlaced

### ISSUE THREAD

**Issue by eyfix** [PCSX2/pcsx2#8332]
### Describe the Bug

In Gun Survivor 3 Dino Crisis (the japanese version of Dino Stalker), all the cutscenes are interlaced with hardware mode. It doesn't occur with software mode.
![Gun Survivor 3 - Dino Crisis_SLPM-65139_20230303125010](https://user-images.githubusercontent.com/124543637/222937452-2ca95065-85ec-4928-92de-a8520f92637f.png)
![Gun Survivor 3 - Dino Crisis_SLPM-65139_20230303125039](https://user-images.githubusercontent.com/124543637/222937457-ea63e212-0932-485a-ab42-982bdc4d6b19.png)

### Reproduction Steps

You can watch the first cutscene after the calibration at the start of the game.

### Expected Behavior

The cutscenes are non-interlaced.

### PCSX2 Revision

v1.7.4187

### Operating System

Windows 10 (64bit)

### CPU

i3-4160

### GPU

GT 1030

### Logs & Dumps

[Gun Survivor 3 - Dino Crisis_SLPM-65139_20230305110546.gs.zip](https://github.com/PCSX2/pcsx2/files/10890608/Gun.Survivor.3.-.Dino.Crisis_SLPM-65139_20230305110546.gs.zip)

**Comment by stenzek** [comment]
<img width="598" alt="Untitled" src="https://user-images.githubusercontent.com/11288319/222941366-44d14017-3821-4aab-9c37-e7fd70c1a759.png">
Looks fine to me with this GS dump :/

**Comment by RedDevilus** [comment]
Looks like another fucked up cutscene with MAD Deinterlacing like Onimusha and some others.

**Comment by eyfix** [comment]
@stenzek Sorry, it was took with software mode. The one below was with Vulkan.
[Gun Survivor 3 - Dino Crisis_SLPM-65139_20230305182431.gs.zip](https://github.com/PCSX2/pcsx2/files/10891489/Gun.Survivor.3.-.Dino.Crisis_SLPM-65139_20230305182431.gs.zip)

**Comment by bslenul** [comment]
Happening with the US version as well (Dino Stalker), appears fine with a GS dump but here's what it really looks like (also showing with and without de-interlacing):

/!\ EPILEPSY WARNING /!\ There's A LOT of flashing in the video!

https://user-images.githubusercontent.com/33353403/222958031-a584abe2-2522-48a5-ad6b-2194125c1f92.mp4

**Comment by bslenul** [comment]
Ah, it appears on multi frames GS dump (as long as the capture starts before the glitch happens): [Dino Stalker_SLUS-20485_20230305190013.gs.zip](https://github.com/PCSX2/pcsx2/files/10892549/Dino.Stalker_SLUS-20485_20230305190013.gs.zip)

**Comment by refractionpcsx2** [comment]
yeah this is one of those mis detecting the frame things, so it looks really freaky when using Adaptive, as it's only getting half the frames.

**Comment by refractionpcsx2** [comment]
This may be fixed as of v1.7.5228 if somebody can check

**Comment by bslenul** [comment]
Looking fine now with the US version (haven't tried EU/JP)! 👍

**Comment by refractionpcsx2** [comment]
Thanks for testing! Hopefully someone can try the other regions :)

**Comment by IlDucci** [comment]
Just tested the PAL ENG version on both 50 Hz and 60 Hz, all seems to be fine on Vulkan.

**Comment by refractionpcsx2** [comment]
Awesome, thanks for testing folks.

Fixed by #10296
