### ISSUE TITLE
[BUG]: The "Full Boot" option does not boot any game

### ISSUE THREAD

**Issue by giuse94** [PCSX2/pcsx2#8334]
### Describe the Bug

When I start a game using the "Full Boot" option, the game does not boot: after the Sony startup logo, the system automatically goes inside the Browser menu, where I see my memory card and the disc representing the game. Clicking on the disc, the system seems to load the game, but then the same screen appears.

This issue appears to be game-independent: I tried with the GTA, *Metal Gear* and *Ratchet & Clank* series (European version). Also note that booting games with the "Fast Boot" option just works fine.

### Reproduction Steps

In the game list, right click on any row and select the "Full Boot" option from the context menu. Alternatively, from the *Settings* > *BIOS* page, uncheck the "Fast Boot" option under the "Options and Patches" section, and then double click on any row in the game list to start a game.

### Expected Behavior

When we start the emulation with the "Full Boot" option, the game should boot automatically after the Sony startup logo, and the system should not enter the Browser menu. Moreover, when we click on the disc image in this menu, the game should start, and the system should not return to the same menu.

### PCSX2 Revision

v1.7.4187

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
It works fine, your games are a different region from your BIOS, this is not a bug.
