### ISSUE TITLE
[Feature Request]: Base analog input offset (anti hardcoded deadzone)

### ISSUE THREAD

**Issue by bugproof** [PCSX2/pcsx2#8339]
### Description

Some games (e.g. Vice City Stories) have hardcoded deadzone values that make it impossible to aim accurately. It would be nice to have some way to bypass that. Reversing the game to find where it sets the deadzone feels too time consuming

### Reason

Better aim accuracy in certain games

### Examples

I think adding some fixed offset to X,Y values from controller would fix that.

**Comment by stenzek** [comment]
I suspect this wouldn't work as well as you think it might. Either way sounds very game specific, and outside of scope.

Feel free to implement it yourself, you could just hardcode an offset to the incoming value here:
https://github.com/PCSX2/pcsx2/blob/c783fc0f5940db498d1cb6678ef2575032ad6944/pcsx2/PAD/Host/KeyStatus.cpp#L83

**Comment by bugproof** [comment]
Just tried this out added 0.2 offset and it works fine. Actually fixed game input for me.

**Comment by xPuls3** [comment]
Would this not have the same implementation as anti-deadzone? https://github.com/PCSX2/pcsx2/pull/9154

**Comment by bugproof** [comment]
> Would this not have the same implementation as anti-deadzone? #9154

Possibly... I beat VCS with a custom build with a hardcoded offset
