### ISSUE TITLE
[Feature Request]: Add custom resolution upscale configuration like 1.6.0

### ISSUE THREAD

**Issue by arthurthekidboy** [PCSX2/pcsx2#8355]
### Description

i have a weak pc and i can't run games like dragon ball z budokai tenkaichi 3 in a good resolution so it would be a good idea to add a custom resolution in configuration

### Reason

because i have weak pc

### Examples

configuration like 1.025x etc on video configuration

**Comment by stenzek** [comment]
You can set any floating point number manually in the ini. But it's going to break tons of games, that's why it's not exposed in the UI.

We won't provide any support if you do.
