### ISSUE TITLE
[Feature Request]: Cheat Manager (Automatic cheat list download) & Toggable Automatic Cover Manager.

### ISSUE THREAD

**Issue by KinecticStump** [PCSX2/pcsx2#8357]
### Description

I suggest giving PCSX2 a way to easily download a cheat list for the currently loaded game. Like DuckStation does for PS1 games and other emulators where you just open click on Tools > Cheat Manager and then a window pops up with all the downloaded cheats ready to be toggled on and off. Instead of having to search for individual gameshark codes or whatever.

Would be great too if we could toggle on an option to automatically download cover images from https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/${serial}.jpg without having to do anything every time we get a new game scanned on the list. If anyone wants to add their own cover image they can just toggle automatic cover download off and that's it.

### Reason

It would make life easier for everyone, especially new users that never used an emulator. They wouldn't have to ask or google at all. This would be a big quality of life improvement for all of our enjoyment. I love how the Cheat Manager is implemented in the mentioned emulators, even mobile emulators for the PS1 have this feature.

### Examples

DuckStation:

After selecting Tools > Cheat Manager while a game is loaded:
![duck1](https://user-images.githubusercontent.com/112200068/223720873-f68766fa-9316-4afd-86bf-eb5227f38148.png)

Clicking on "Yes" leads to the following:
![duck2](https://user-images.githubusercontent.com/112200068/223720881-0bcba6df-90fb-4c67-ad7d-16bf040feed8.png)

**Comment by stenzek** [comment]
Where would this "automatic cheat list" come from?

Duckstation only has it because someone went to the effort of scraping, curating and creating such a list. We're not going to do that for PCSX2, we have way too many other things to do, plus a lack of interest.

If someone wants to create such a list, then we can talk implementation, but for now I'm deeming this out of scope.

**Comment by thetherapygamer** [comment]
I've Got the list of Scrapped Codes for Every Game for PS2. Can we Chat? :-)

**Comment by Daniel-McCarthy** [comment]
> I've Got the list of Scrapped Codes for Every Game for PS2. Can we Chat? :-)

I'm curious, what format do you have that in? Do you have them grouped by serial? Region, CRC?
What all information do you have alongside the codes themselves? Depending on how it's stored/formatted can impact how much work it would be to get it into something consumable.

(I don't have say in the consideration of this issue, but I am somewhat intrigued.)

**Comment by stenzek** [comment]
I'd also be concerned about where the codes were sourced from, and whether we would have permission to use them.

**Comment by Daniel-McCarthy** [comment]
> I'd also be concerned about where the codes were sourced from, and whether we would have permission to use them.

Permission issues is something that also gave me hesitation. My initial feeling is that it would likely necessitate author submissions to a code equivalent to [PCSX2/pcsx2_patches](https://github.com/PCSX2/pcsx2_patches), ideally with a license.

**Comment by kamfretoz** [comment]
Might be better to further discuss this matter on Discord.

**Comment by stenzek** [comment]
IANAL, but as I understand it, any codes are going to be derived work of the original code, so cheat authors can't exactly put a license and copyright on codes (and the potential legal rabbit hole, whether shipping them constitutes fair use, etc). But that said, it's still preferable to attribute where possible and do the right thing.

**Comment by JordanTheToaster** [comment]
No
