### ISSUE TITLE
[BUG]: Fix Distant flickering textures while flying in Budokai Tenkaichi 3

### ISSUE THREAD

**Issue by arthurthekidboy** [PCSX2/pcsx2#8358]
### Describe the Bug

the pcsx2 update from 1.6.0 to nightly 1.7.4xxxx was good but since these versions when i play budokai tenkaichi 3 there is flickering in the scenery when flying and i would like someone to fix this hardware error since in the software it is heavy and does not run on my pc

### Reproduction Steps

D3D11
![image](https://user-images.githubusercontent.com/102826358/223766971-76a72324-6b52-47a8-8f2b-1316869f28fc.png)

### PCSX2 Revision

1.7.4198

### Operating System

Windows 10 (64bit)

### CPU

Athlon 3000g

### GPU

Vega 3

**Comment by Mrlinkwii** [comment]
Which 1.7 version exactly are you using and can you post a gs dump?

**Comment by arthurthekidboy** [comment]
Zstandard(zst)

**Comment by arthurthekidboy** [comment]
how to map the 32 bit to 0.1 range

**Comment by arthurthekidboy** [comment]
i dont use the software because for the bad performance on my pc

**Comment by stenzek** [comment]
Read what I said again. You can't fix it. The eventual solution will be to use ROV for depth everywhere, but that requires a high end GPU.

If you want to fix it, get a better CPU and use software. That is the only way.

Please use discord for further questions, the issue tracker is not for support.
