### ISSUE TITLE
[Feature Request] Exclusive (or real) Fullscreen

### ISSUE THREAD

**Issue by Nezarn** [PCSX2/pcsx2#836]
It would be nice to have this, because that way nvidia shadowplay should work (and also the new coop thingy, it would be interesting to try it with pcsx2)

**Comment by Nobbs66** [comment]
We've had this discussion before. We really don't have enough people to work on something like this. Also, just use the desktop capture in shadowplay.

**Comment by Nezarn** [comment]
@Nobbs66 but Nvidia share only works in real fullscreen (and since theres no netplay in PCSX2, it would be awesome if it worked, and i think it would be easier to implement fullscreen than netplay.)

**Comment by winneon** [comment]
Isn't this, like, a standard feature in every game, period? Why wasn't this one of the first things implemented after the emulator had a decent compatibility percentage?

**Comment by MrCK1** [comment]
We're still working on it. It isn't a well defined standard, so changes require a bit of guessing.

**Comment by ssakash** [comment]
> Isn't this, like, a standard feature in every game, period? Why wasn't this one of the first things implemented after the emulator had a decent compatibility percentage?

Exclusive full screen was present during the legacy GUI times (without WxWidgets), it was removed for the reasons stated here: https://forums.pcsx2.net/Thread-blog-A-new-kind-of-fullscreen?highlight=exclusive

> We're still working on it

Who exactly? I don't recall about anyone planning on adding it.

**Comment by lightningterror** [comment]
Closing this one. All of the info is stated in that thread.
