### ISSUE TITLE
[BUG]: Ar tonelico 2 small thin lines around textures

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8364]
### Describe the Bug

In some part of the game there are bounding THIN lines around texture rectangles.
Also sometimes half of the screen background in conversations gets garbled with random textures .

![2023-03-09_13h34_56](https://user-images.githubusercontent.com/42075250/224025411-63c0e4e3-fe79-41cc-bab5-c41f1d8fd278.png)
![2023-03-09_01h07_54](https://user-images.githubusercontent.com/42075250/224026695-ad700da3-c546-478f-a8d7-f8e0c5a5674b.png)

### Reproduction Steps

The texture garbling appears very often at various points when 2 or more characters speak with their portraits appearing on the screen usually when in a dungeon 

The thin lines appear on the pillar of light when a paradigm shift occurs on the cosmosphere map.

### Expected Behavior

No thin lines or garbled textures.

### PCSX2 Revision

PCSX2 Nightly - v1.7.4204

### Operating System

Windows 11

### CPU

i910850k

### GPU

rtx3080ti

### GS Settings

![2023-03-09_13h42_13](https://user-images.githubusercontent.com/42075250/224026330-7b1191f1-5485-4f41-812e-73c9029ae625.png)

### Logs & Dumps
[snaps.zip](https://github.com/PCSX2/pcsx2/files/10931584/snaps.zip)

_No response_

**Comment by Mrlinkwii** [comment]
gs dump?

**Comment by JordanTheToaster** [comment]
> I added snaps.zip who contain gsdump for the thin lines. The thin lines issue appear in the patched undub version also in the original US version . (outside of scope of this bug report but if someone can tell me if its possible to enable widescreen patches in the undub uncensored version of the game i would be grateful ) I dont have a gsdump for the garbled textures issue...

Please get a dump of the texture issue preferably using an unmodded ISO please.

**Comment by ISuckGood** [comment]
> > I added snaps.zip who contain gsdump for the thin lines. The thin lines issue appear in the patched undub version also in the original US version . (outside of scope of this bug report but if someone can tell me if its possible to enable widescreen patches in the undub uncensored version of the game i would be grateful ) I dont have a gsdump for the garbled textures issue...
> 
> Please get a dump of the texture issue preferably using an unmodded ISO please.

Well i booted the US version and i loaded the save state from the undub version using load save state from file ... The i dumped the core data. I hope thats ok .

**Comment by ISuckGood** [comment]
I am confused . Is everyone playing in software mode and reporting issues found there ? These thin lines dont appear in sw mode . But i doubt everyone who installed pcsx2 uses software mode to play the games. If only sw rendering issues are reported as issues how do we know these fancy opengl/d3d12/vulkan are even usable ?

From the pcsx2 rules:
"
We do not accept issues relating to upscaling at this time

    We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling
"

**Comment by RedDevilus** [comment]
We already give many warnings on several locations, upscaling can never be as buggy-free as the software renderer. People don't read warnings either way, but emulators don't replace physical console in terms of visuals especially as upscaling never happened on the console where approximations are inside pixel coordinates themselves so you get these issues. Anyway it's a non-issue.

**Comment by ISuckGood** [comment]
I added also a gsdump for the original US version unpatched game . I used a save state from the US uncensored version Japanese voices and loaded the save state into the original unpatched version . You can see the texture are broken in the background and this happens in sw and hw renderers with default settings
[snapsSLUS-21788_CRC_F95F37EE.zip](https://github.com/PCSX2/pcsx2/files/10933658/snapsSLUS-21788_CRC_F95F37EE.zip)

**Comment by RedDevilus** [comment]
![image](https://user-images.githubusercontent.com/24227051/224088217-a4838532-dac6-47f0-9de4-9b8012afeb6d.png)
Yeah no idea why it keeps half an old frame, the small lines around the characters face is gone with the automatic roundsprite setting.

**Comment by Mrlinkwii** [comment]
@ISuckGood  dose this game work at native res ?

**Comment by ISuckGood** [comment]
> @ISuckGood dose this game work at native res ?

The texture swapping on half screen occurs in software mode also /native res or not
