### ISSUE TITLE
GSdx Settings Window Doesn't Account for Hotkey Changes

### ISSUE THREAD

**Issue by yorkiesandskittles** [PCSX2/pcsx2#837]
1. Set a renderer in the GSdx settings window e.g. OpenGL (Hardware.)
2. Launch a game.
3. Press F9 to switch from HW to SW or vice-versa.
4. Go to the GSdx settings window again. Even though you changed your renderer with the F9 key, the GSdx window will appear as though the renderer was never changed, and it will change to what the settings window shows when you hit OK.

Apologies if an issue was already opened for this.

**Comment by bositman** [comment]
That is by design, the F9 toggle is seen as a temporary switch.
https://github.com/PCSX2/pcsx2/pull/611
