### ISSUE TITLE
[BUG]: Glitched countdown effect in HW renderer | Gran Turismo 4 Prologue (PBPX-95523)

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8370]
### Describe the Bug

Countdown effect is glitched with HW renderer
![Gran Turismo 4 - Prologue  PlayStation 2 Racing Pack _PBPX-95523_20230311205414](https://user-images.githubusercontent.com/121824800/224482962-8d9292a5-dfa8-4013-bc6d-95e763c711d3.png)

Sometimes, the color changes to not only green but blue or black.

### Reproduction Steps

Arcade Mode -> Start -> Tsukuba Circuit -> Nissan Fairlady 240ZG (HS30) '71 (leftmost car) -> Grand Prix White (rightmost color)
-> Start -> Start

### Expected Behavior

SW renderer

![Gran Turismo 4 - Prologue  PlayStation 2 Racing Pack _PBPX-95523_20230311205740](https://user-images.githubusercontent.com/121824800/224483345-9a91ff4c-f83c-4c19-a8cd-1f195d785ad4.png)

### PCSX2 Revision

v1.7.4207

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

GS Dump:
https://69.gigafile.nu/0318-j78aa284e36e1ce09dca7b32352e3c11a

**Comment by refractionpcsx2** [comment]
Can you provide a new GS dump? That link doesn't work. 

If possible, Zip the file up and attach it directly.

**Comment by SeruranBlue** [comment]
https://27.gigafile.nu/1124-0970bc51d7132235124548fb98331db2
due to limit of file size, I can't upload it directly.

**Comment by refractionpcsx2** [comment]
[Gran Turismo 4 - Prologue [PlayStation 2 Racing Pack]_PBPX-95523_20230815201503.gs.zip](https://github.com/PCSX2/pcsx2/files/12352359/Gran.Turismo.4.-.Prologue.PlayStation.2.Racing.Pack._PBPX-95523_20230815201503.gs.zip)

Here's a shorter dump which fits on the github issue. Only really needed one of the transitions
