### ISSUE TITLE
[BUG]: Radiata Stories Crashing during cutscenes

### ISSUE THREAD

**Issue by Talelelel** [PCSX2/pcsx2#8378]
### Describe the Bug

The game crashes during the opening salvo of cutscenes in recent Linux branches of pcsx2. Verified the game was working sometime in November 2022.

### Reproduction Steps

Start new game, after the initial cgi cutscene the game will crash during the following in-engine scenes. There is some variance as to timing of crash. Renderer set to automatic (uses OpenGL), crashes more quickly using Vulkan renderer.

### PCSX2 Revision

1.7.4217

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch (SteamOS)

### CPU

AMD APU

### GPU

AMD APU

### GS Settings

None

### Emulation Settings

None

**Comment by stenzek** [comment]
If this is from Emudeck or the discover/flatpak, we provide no support, speak to the packager.

If you're using the appimage, we'll need a backtrace of when it crashes. It should boil down to a SIGABRT, so you can tell gdb to skip the intentional segfaults with `handle SIGSEGV nostop noprint`.

**Comment by Talelelel** [comment]
This is on Steamdeck, but using the appimage. Additionally, the crash has also been verified on a Linux laptop. Ultimately, if I can’t get individual support atm that’s fine but I wanted to make the devs aware of a crash that afaik is happening only on Linux and across different devices.

**Comment by stenzek** [comment]
If you can't provide the backtrace and we can't reproduce the crash, there isn't much we can do. I can reboot into Linux to check it, but I'd rather not.

**Comment by Talelelel** [comment]
I’m not sure how to do that, but I will pass down what you said to the people troubleshooting this with me who are smarter than me and see what they say. If you do get the opportunity to check how it works on a Linux branch that would be appreciated.

**Comment by stenzek** [comment]
You should at least verify your dump is correct (and you're not using any cheats/patches, speedhacks, etc).

**Comment by Talelelel** [comment]
I have verified the dump via the MD5. Additionally no hacks are being used, cheats and even widescreen patches are disabled. I did try using the VuAddSub hack at one point, but that did not change anything

**Comment by Mrlinkwii** [comment]
@Talelelel  can you tell me when it broke  , November 2022 dosent help

**Comment by Talelelel** [comment]
Yes, someone is working on verifying the specific build already so I will offer that info when I can, that’s the closest we have narrowed it down to so far based on another user’s save data and when it was created

**Comment by Mrlinkwii** [comment]
@Talelelel  can you try #8336 for me ?

**Comment by stenzek** [comment]
#8336 appears to fix it... crux of the issue is it's invalidating the texture source before the draw.. and my PR has more accurate framebuffer heights, so that invalidation doesn't happen.

I think I'll move the invalidation to after the draw though, that's the "proper" fix.

**Comment by LeCharlatan** [comment]
Hi, verified the game here anyway, it effectively crash on both Intel and Nvidia and only with Vulkan, not crashing on OpenGL

**Comment by refractionpcsx2** [comment]
It's fine, we know what the issue is :) It's not renderer specific, but it's by luck it doesn't crash on Windows, for sure.

**Comment by LeCharlatan** [comment]
Hey @refractionpcsx2 yep I read it, I report in case :D

**Comment by Talelelel** [comment]
Hehe I fell asleep but it seems you all figured some stuff out which I’m happy to see! ^^
