### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Lupinbauwer** [PCSX2/pcsx2#8401]
### Describe the Bug

ルパン三世コロンブス　オープニングムービーの後、ルパンのアジトで隣の部屋への移動、外への移動ができない。画面が切り替わらない

### Reproduction Steps

プレイ画面でドアの前で〇ボタンを押しても切り替わらない。

### PCSX2 Revision

PCSX2 Nightly - v1.7.4232

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Xeon(R) CPU E5-2670

### GPU

Geforce Gtx760

**Comment by refractionpcsx2** [comment]
Can you translate to English please.

**Comment by RedDevilus** [comment]
English translation

Describe Bug:
Lupine III Columbus After the opening movie, it is impossible to move to the next room or move out of Lupine's hideout. screen does not switch.
Reproduction Steps:
Pressing the ○ button in front of the door on the play screen does not switch.

**Comment by Mrlinkwii** [comment]
@Lupinbauwer コントローラーをマッピングしましたか？

**Comment by Lupinbauwer** [comment]
マッピングしました

**Comment by Lupinbauwer** [comment]
刑務所内では、普通に部屋の移動はできました。
刑務所内でのゲームをクリアし、オープニングムービーが流れ
その後のルパンのアジトから始まるところで、ドアの向こう側への移動ができなくなります。

**Comment by Mrlinkwii** [comment]
English translation:

In prison, you can move between rooms normally.
Clear the game inside the prison and play the opening movie
After that, at the beginning of Lupine's hideout, you will not be able to move to the other side of the door.

**Comment by Lupinbauwer** [comment]
Outlook for iOS<https://aka.ms/o0ukef> を入手
________________________________
差出人: Mrlinkwii ***@***.***>
送信日r: Thursday, March 16, 2023 1:58:05 AM
宛先: PCSX2/pcsx2 ***@***.***>
CC: Lupinbauwer ***@***.***>; Mention ***@***.***>
件名: Re: [PCSX2/pcsx2] [BUG]: (Issue #8401)


English translation:

In prison, you can move between rooms normally.
Clear the game inside the prison and play the opening movie
After that, at the beginning of Lupine's hideout, you will not be able to move to the other side of the door.

―

**Comment by Lupinbauwer** [comment]
![Lupin](https://user-images.githubusercontent.com/127977005/225397715-6633c817-27bd-48f9-a0a9-a5f654067229.jpg)

**Comment by Lupinbauwer** [comment]
![Lupin2](https://user-images.githubusercontent.com/127977005/225398174-4e065341-8cbe-41cf-9fb3-77e604f22432.jpg)

**Comment by Mrlinkwii** [comment]
@Lupinbauwer メモリーカードやセーブステートはありますか

**Comment by Lupinbauwer** [comment]
[SLPS-25430 (B78086CD).01.zip](https://github.com/PCSX2/pcsx2/files/10985263/SLPS-25430.B78086CD.01.zip)
セーブステートです

**Comment by Berylskid** [comment]
ただの確認ですが、PCSX2じゃなくてPS2でプレイすれば、そのドアは開くんですかね？私はそのゲーム持ってないんで、確認できません。

**Comment by Mrlinkwii** [comment]
@Lupinbauwer #8404 をゲームでテストしていただけますか

**Comment by Berylskid** [comment]
@Lupinbauwer 上で言われてるのは[このビルド](https://github.com/PCSX2/pcsx2/suites/11593848788/artifacts/600983192)です。
このビルドで治るかどうか、テストをお願いします。

**Comment by Lupinbauwer** [comment]
治りました！
ありがとうございましたm(__)m
