### ISSUE TITLE
[Regression]: Narnia (2nd) game Prince Caspian, Palette issues perhaps

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#8403]
### Describe the Bug

The game had issues in the past but were fixed, but game back again differently where it has issues with screen having weird overlay.

Along with the dumps doing I don't know what:

Where you see fog, sun and sides turning black or bright or even completely dissapearing

### Reproduction Steps

- Start new game
- Skip 2 FMVs
- Run around the rock

### Expected Behavior

Not look shit

### PCSX2 Revision

1.7.4234

### Operating System

Windows 10 (64bit)

### CPU

i7-9750H

### GPU

RTX 2060M

### GS Settings

/

### Emulation Settings

/

### GS Window Screenshots

/

### Logs & Dumps

Video where you can see issue easily:
https://user-images.githubusercontent.com/24227051/225477389-dcb4bbcc-1daf-4900-8c3f-c0dbc0712efd.mp4

GS Hardware dumps:
![320176_f7925_rt0_03000_C_24](https://user-images.githubusercontent.com/24227051/225478126-dbbf33ad-b20b-4d4f-8ab9-49ce0baaabda.png)
[320176_vertex.txt](https://github.com/PCSX2/pcsx2/files/10985546/320176_vertex.txt)
[320176_context.txt](https://github.com/PCSX2/pcsx2/files/10985547/320176_context.txt)

GS Multiframe dump (till 15/04/2023) it's like 400 MB:

https://easyupload.io/m/7yv79l

**Comment by Sonny35** [comment]
I have the same problem. I'm using SLES-55144 version. This game only works with Direct3D 12 form me but half screen is flickering to black in the middle of gameplay.

If i change to Software renderer this glitch disappears, but the FPS but the fps and resolution drop so low that it is impossible to play.

All my settings are in the recomended value except Aspect Ratio (16:9) and internal resolution (3x - 1080p).

**Comment by JordanTheToaster** [comment]
Game works fine now bar a brief black half screen flicker on the left side in the dump provided.

**Comment by RedDevilus** [comment]
It's still broken, but in a lesser degree.

**Comment by RedDevilus** [comment]
[ChroniclesOfNarniaREEE.zip](https://github.com/PCSX2/pcsx2/files/11161926/ChroniclesOfNarniaREEE.zip)
![Chronicles of Narnia, The - Prince Caspian_SLES-55145_20230405202229](https://user-images.githubusercontent.com/24227051/230170373-70ced6de-2ade-4f0e-a811-eebf380936d8.png)

**Comment by Mrlinkwii** [comment]
seems a bit better on v1.7.4507 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/c387e41e-626f-4caa-80ae-1a99e4d5d2d5)

**Comment by Mrlinkwii** [comment]
seems to be  better on 1.7.4864
![image](https://github.com/PCSX2/pcsx2/assets/17685135/db0b8c8c-070e-41a0-b481-9ca9ba9a08d3)

**Comment by RedDevilus** [comment]
Yeah seemed fine from a week ago or so. No idea what fixed it. If some mad lad wants to find out :P

**Comment by refractionpcsx2** [comment]
Fixed by #9003 in build v.1.7.4608
