### ISSUE TITLE
[Feature Request]: Please add memcardFilters to GameDB for SLPM-65101 "Onimusha2".

### ISSUE THREAD

**Issue by kevin98761234** [PCSX2/pcsx2#8405]
### Description

When a memory card is used in folder mode, once saved and restarted, it cannot be loaded.

### Reason

Can be successfully checked and loaded when the memory card is used in folder mode.

### Examples

SLPM-65101:
  name: "Onimusha 2"
  region: "NTSC-J"
  memcardFilters:
    - "SLPM-65100"

**Comment by Mrlinkwii** [comment]
ive updated ##8404 with the fix
