### ISSUE TITLE
[BUG]: Rahxephon Object is floating in the air.

### ISSUE THREAD

**Issue by kevin98761234** [PCSX2/pcsx2#8407]
### Describe the Bug

Strange, but the chair is floating in the air.
I have checked GameFixes one by one, but no solution.
I have not tried ManualHardwareRendererFixes.

### Reproduction Steps

Start the game from NEWGAME and skip some movies by pressing the START button.

### Expected Behavior

The chair should be on the floor.
https://youtu.be/3ZxIQWESK2w?t=66

### PCSX2 Revision

v1.7.4235

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

Renderer: Software
It is exactly the same with any hardware.

### Emulation Settings

Press the "restore defaults" button to default.

### GS Window Screenshots

![RahXephon  Limited Edition _SLPS-25264_The chair is floating](https://user-images.githubusercontent.com/88806005/225663721-304f4f62-9582-4b0f-a718-2fadfd3f3cd9.png)

### Logs & Dumps

[RahXephon [Limited Edition]_SLPS-25264_The chair is floating.gs.zip](https://github.com/PCSX2/pcsx2/files/10992544/RahXephon.Limited.Edition._SLPS-25264_The.chair.is.floating.gs.zip)

**Comment by kevin98761234** [comment]
I found the cause of the problem.
If I uncheck the EnableRecompiler for EmotionEngine in SettingsAdvanced, the chair seems to be placed on the floor correctly.
![RahXephon  Limited Edition _SLPS-25264_eeRecompilerDisable](https://user-images.githubusercontent.com/88806005/225760392-e6006967-bced-43d7-8e43-457746424cd5.png)
[RahXephon [Limited Edition]_SLPS-25264_eeRecompilerDisable.gs.zip](https://github.com/PCSX2/pcsx2/files/10996193/RahXephon.Limited.Edition._SLPS-25264_eeRecompilerDisable.gs.zip)

**Comment by Mrlinkwii** [comment]
ok ive tried that here  , the game needs EE INT from boot
![image](https://user-images.githubusercontent.com/17685135/225762325-09180fbe-e59b-4599-84db-ad734a392742.png)

after the level loads changing back to the Recompiler dosent change it 

![image](https://user-images.githubusercontent.com/17685135/225763288-d98df535-257f-41ca-9928-ff355c41b660.png)

**Comment by Goatman13** [comment]
Interpreter use "Nearest FPU" rounding, maybe that's all you need to set for recompiler?

**Comment by Goatman13** [comment]
It's something else than rounding. Falling back to interpreter for DIV.S fix it. So i tried to figure out differences between int and rec here. But nothing worked so far. 

For rec i tried:
- Enter div by zero even when only exponent is 0 (didn't tested 0/0 that way though, game do both div by 0, and 0/0).
- Allowed negative clamp for result (-fmax for - inf and below)

**Comment by Mrlinkwii** [comment]
still an issue and EE int still fixes it as of v1.7.5316
![image](https://github.com/PCSX2/pcsx2/assets/17685135/a32799d9-8b7b-4d79-8259-5a92fc6ec75c)

**Comment by Goatman13** [comment]
Sorry I forgot to mention it here earlier. It turned out to be FPU DIV nearest rounding when i tested it later back in March.
Previously i assumed that fpu use nearest rounding for interpreter as in old pcsx2, apparently that's no longer the case. Anyway, it worked with removed force rounding, iirc also when set to positive (for DIV).
