### ISSUE TITLE
[BUG]: In macOS 10.14.6, pressing and holding mapped keyboard vowel keys causes vowel special character pop-up menus to appear on screen

### ISSUE THREAD

**Issue by DanielBielak** [PCSX2/pcsx2#8408]
### Describe the Bug

In macOS 10.14.6, when using the keyboard as a controller in PCSX2, in Gran Turismo 4, pressing and holding mapped keyboard vowel keys causes vowel special character pop-up menus to appear on screen.

### Reproduction Steps

- Run PCSX2
- Set the computer keyboard as the game controller 
- Run Gran Turismo 4 in PCSX2
- Select Gran Turismo Mode
- Select City Courses
- Select Seoul Central
- Select Practice
- Select A-Spec=Driver's mode
- Press and hold the "A" key (or any other game-controller-binded vowel key) on the computer keyboard 

### Expected Behavior

Pressing down the "A" key should only cause the vehicle to turn left, not also cause the "A" special character pop-up menu to appear on screen.

### PCSX2 Revision

v1.7.4235

### Operating System

macOS 10.14 (Mojave)

**Comment by refractionpcsx2** [comment]
does your OS usually pop up with that if you hold down A? cos that sounds like an OS thing rather than a PCSX2 issue.

**Comment by DanielBielak** [comment]
The menus only pop up when a vowel is pressed and held when the text cursor is in a text field.

**Comment by DigitalMajestic** [comment]
Appears to no longer be an issue. Tested 1.7.4529 in both macOS Ventura (13.4) and Mojave (10.14.6).
