### ISSUE TITLE
[Feature Request] Make the "Enable Cheats" menu work immediately

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#841]
When you enable the cheats while a game is already running,the cheats are not applied,you have to do one of those:
Pause the emulation and continue - do this twice(it will not work with only once)
Open and close any plugins window again twice
Click on the console scrollbar twice
Restart the game

The same goes for disabling the cheats...the menu just don't work by just enabling\disabling it,you have to do something extra twice to make the cheats work

**Comment by turtleli** [comment]
Should work now with latest commit (c540840cd4fef6afa9db808a31a35a039313237a). Please test.

**Comment by FlatOutPS2** [comment]
Selecting a (widescreen)cheatt applies it immediately, but deselecting doesn't remove it...

**Comment by turtleli** [comment]
For widescreen patches, that's somewhat expected - if the game doesn't overwrite an altered memory location with the original non-widescreen values, it cannot revert back.

**Comment by vsub** [comment]
Works fine,thanks and yes,the widescreen behavior is expected.The values are changed and some games never try to restore them.

Maybe for widescreen patches,pcsx2 should first check the values in the addresses and save them in some variable and when you disable it,to set those values...I don't how hard this(or if it's possible) is but just a suggestion

**Comment by turtleli** [comment]
Well, I suppose most people would just leave the widescreen patch option on or off and won't change it frequently (or at least that's my excuse for not investigating it).

Issue resolved.
