### ISSUE TITLE
[Feature Request]: Please add the memcardFilters option to the GameDB for the Ratchet&Clank series to the previous one.

### ISSUE THREAD

**Issue by kevin98761234** [PCSX2/pcsx2#8410]
### Description

GoingCommando(2) can load the save data of the first title.
UpYourArsenal(3) can load the saved data of the first title and GoingCommando(2).

However, if the saved data is used in folder mode, it cannot be loaded because memcardFilters is not set correctly.

### Reason

Matron, a vendor in GoingCommando (2), will give away weapons for free if you have the saved data from the first title.

Gadgetron vendor in UpYourArsenal(3) will give you a discount on weapons if you have a saved data of the first title.
SlimCognito of UpYourArsenal(3) will give you weapons for free if you have a saved data of GoingCommando(2).

https://ratchetandclank.fandom.com/wiki/Going_Commando_vendors
https://ratchetandclank.fandom.com/wiki/Up_Your_Arsenal_vendors

### Examples

Sxxx-xxxxx:
  name: "Ratchet&Clank series"
  memcardFilters:
    - "Sxxx-xxxxx"
    - "Sxxx-xxxxx"
    - "Sxxx-xxxxx"
    - "Sxxx-xxxxx"
    - "Sxxx-xxxxx"

**Comment by RedDevilus** [comment]
To be fair, memcard filters weren't the best feature to have, for stuff like this as you have to test every serial which is about impossible to ever complete. Instead of just allowing every serial to interact with other serial saves.
