### ISSUE TITLE
[BUG]: Dragon Ball Z: Budokai Tenkaichi 3 PAL Disc swap

### ISSUE THREAD

**Issue by LeCharlatan** [PCSX2/pcsx2#8412]
### Describe the Bug

The fusion Disc option in game doesn't work (nothing happens on swapping Disc)

If it helps, here Discs ID

**Disc DBZBT :**
Serial : SLES-53200
CRC : 92EA9EF0
**Disc DBZBT 2 :**
Serial : SLES-54164
CRC : 278722BF
**Disc DBZBT 3 :**
Serial : SLES-54945
CRC : A422BB13

### Reproduction Steps

Enter into Ultimate battle mode, try Disc Fusion option then change Disc when it's asked.

### Expected Behavior

Expecting Disc change working

### PCSX2 Revision

v1.7.4239

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro (Stable)

### CPU

Intel® Core™ i5-4690K CPU @ 3.50GHz

### GPU

Nvidia GTX 1070

### GS Settings

Internal Resolution : 2x Native (~720p)

### Emulation Settings

Default

**Comment by refractionpcsx2** [comment]
Confrimed, it detects the tray open but not the close and reading the game, for some reason.

**Comment by LeCharlatan** [comment]
Hi @refractionpcsx2 , forget to mention but, I've tested with physical original Disc and ISO, both same result.

**Comment by refractionpcsx2** [comment]
yes, they share the same code for disc swapping, which explains it :)

**Comment by refractionpcsx2** [comment]
I mean it detects that the disc gets removed, that's a start, right? :D
