### ISSUE TITLE
[BUG]: Regression: Driv3r (Driver 3) is not playable in hardware mode

### ISSUE THREAD

**Issue by Sonny35** [PCSX2/pcsx2#8415]
### Describe the Bug

The game is not playable. When you start the game you can't read the text that asks you about the Memory Card.

During the whole game no text can be read.

When you start a new game you can see that practically all the textures are wrong and there is an excessive drop in FPS.

I've tried all the renderings and it's the same for all except the software rendering, but it runs at such a low FPS that it's unplayable.

I'm using SLES-52153 version.

Thanks for the support!

### Reproduction Steps

Only start the game for texts and start new game for textures and FPS.

### Expected Behavior

To be able to read the texts and play at an acceptable FPS rate with as many textures as possible fixed.

### PCSX2 Revision

v1.7.4240 (Nightly SSE4 Qt)

### Operating System

Windows 10 (64bit)

### CPU

AMD A10-7850K Radeon R7

### GPU

AMD Radeon R9 200 Series (3 GB)

### GS Settings

All default except internal resolution, but it doesn't make any difference if I put it native.

### Emulation Settings

All default.
I have already tried unchecking MTU.

### GS Window Screenshots

![1](https://user-images.githubusercontent.com/9279268/226035482-5b85d3ed-fc5e-4c9f-bddb-1c7ffbaaf859.png)
![2](https://user-images.githubusercontent.com/9279268/226035505-7c728da1-3774-47b7-a93c-e9e40a1288b8.png)
![3](https://user-images.githubusercontent.com/9279268/226035521-58d19097-718e-4d87-9767-c01590f46fb5.png)
![5](https://user-images.githubusercontent.com/9279268/226035554-ca707fa4-b6dc-4efd-b570-1ef5a080a9ef.png)
![6](https://user-images.githubusercontent.com/9279268/226035592-dbc39346-19b3-45c8-8b30-07e28adf9267.png)
![4](https://user-images.githubusercontent.com/9279268/226035610-1bc79991-417f-4d5d-9c66-5776f935b563.png)

### Logs & Dumps

[Texts issue.zip](https://github.com/PCSX2/pcsx2/files/11006170/Texts.issue.zip)
[Textures and fps issues.zip](https://github.com/PCSX2/pcsx2/files/11006171/Textures.and.fps.issues.zip)

**Comment by JordanTheToaster** [comment]
The text has never worked outside of software or native resolution and the game looks the same as it has for me.

![image](https://user-images.githubusercontent.com/80843560/226047667-6235ac63-e669-4989-9062-ea1060f6330b.png)

**Comment by JordanTheToaster** [comment]
> Maybe it's hardware incompatibility but I have more than 100 games that work perfectly, I don't know. I hope they can fix it.

The game for now only works correctly in software which your CPU being very slow and old isn't going to handle at all.

**Comment by Sonny35** [comment]
Maybe, but while using software rendering the CPU doesn't even go to 100% and gives me a very low FPS rate.

![Sin título](https://user-images.githubusercontent.com/9279268/226056115-e5f7b7e4-e524-448f-8aeb-a05e2238e2ad.png)

**Comment by Mrlinkwii** [comment]
yeah your cpu is weak even for ps2 emualtion

**Comment by Sonny35** [comment]
For software rendering it may be, but for hardware there is no problem. If it could be fixed in hardware rendering it would be perfect, after all it's still a bug.

**Comment by stenzek** [comment]
This was specific to the DX11 renderer. The text looking like arse is because of the whacky way it draws the fonts, needs pixel perfect accuracy, or dropping back to sw.

Just because the CPU isn't at 100% doesn't mean it's not the bottleneck. The SW renderer needs to synchronize when there's hazards, so it's pretty much impossible for it to use 100%. Having a slower CPU means more time stalled/waiting, and bad performance.

Those APUs were slow when they were released, and **very** slow by today's standards. It's never going to run heavy games like this at full speed.
