### ISSUE TITLE
[Feature Request]: Netplay Client (delay based)

### ISSUE THREAD

**Issue by BevP90** [PCSX2/pcsx2#8425]
### Description

I'm sure this has been requested before, but would it be possible to see a delay-based P2P netplay client similar to what we've seen in the PCSX2 2012 netplay build or the Dolphin emulator? 
This would allow for offline split-screen co-op games or fighting games to be played online using either direct public IPs, match codes (as seen in Flycast Dojo Rollback), or Radmin VPN. 

The netplay client should ideally 

- Measure the ping in ms and be able to automatically recommend the correct input delay values for the connection
- Run as typical delay based netcode should, pausing the game briefly to keep both players synced if there's a spike in the ping
- Have sync checking to detect desyncs and display a warning message
- Be able to spectate matches 

### Reason

By having a netplay client on the latest build of PCSX2 the fighting game scene would be able to more reliably and consistently run events and tournaments for our favorite PS2 fighting games. Not only this, but other communities could benefit from this too when it comes to co-op split screen games that never had online play. 

GGPO rollback netcode was recently implemented into the Duckstation emulator, which is known to be no easy task due to how demanding rollback is as it requires the emulator to be able to save and load states quickly.
While saving and loading save states might not be fast enough for smooth rollback on PCSX2, going delay based would be alot less demanding for the emulator.

This is a feature that we haven't seen officially from the PCSX2 team, so I'm sure alot of people would be interested to hear what the team thinks of this idea and the possibility of a new delay-based netcode client. 

### Examples

Dolphin emulator (delay based netcode client) 
PCSX2 2012 Netplay build (delay based netcode client) 
PCSX2 Online Plus (the 2012 custom netcode ported over to a later PCSX2 build 1.6.0)
Flycast Dojo (Rollback using GGPO)
Duckstation (Rollback using GGPO)

**Comment by refractionpcsx2** [comment]
Duplicate #772
