### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by eyeslugger** [PCSX2/pcsx2#8426]
### Describe the Bug

Black stripes appear on the screen,with lagging sometimes，Render Error，and frequent screen flicker（GS：OpenGL vulkan Direct11/12）
![Transformers_SLUS-20668_20230318221206](https://user-images.githubusercontent.com/33159578/226114096-89ca1217-6e31-4879-9013-fc5e4f51887b.png)
![Transformers_SLUS-20668_20230318225335](https://user-images.githubusercontent.com/33159578/226114098-eb318296-0242-4c53-954c-8ad2e18be84b.png)
However，stripes，render error，and frequent screen，will be solved in the softwareGS，but lagging will be more
![Transformers_SLUS-20668_20230318220241](https://user-images.githubusercontent.com/33159578/226114111-62cca943-ce20-4749-b5d1-6eccd4f336af.png)
P.S.   I think the compatibility of this game is overestimated.

### Reproduction Steps

https://user-images.githubusercontent.com/33159578/226115238-2e69805f-0975-4a82-ae92-63ba0340a912.mp4

### Expected Behavior

Less lag，repair rander problem and no stripes

### PCSX2 Revision

v1.7.4243

### Operating System

Windows 10 (64bit)

### CPU

i5-8265U

### GPU

GeForce MX110

**Comment by refractionpcsx2** [comment]
duplicate #3025

**Comment by eyeslugger** [comment]
> duplicate #3025
This won't help deal the rendering problem of the Antarctica stage
![gsdx_20230319003351](https://user-images.githubusercontent.com/33159578/226119838-8a3e80f8-9136-4a48-b13f-66686c7137ff.png)

**Comment by refractionpcsx2** [comment]
It's all the same thing, that's also a shuffle problem.

**Comment by eyeslugger** [comment]
> 



> It's all the same thing, that's also a shuffle problem.

“Use Alpha fix with D3D11 to remove stripes. • Use Disable Depth Emulation fix with OpenGL.”It didn't work

**Comment by eyeslugger** [comment]
It just makes the stripes translucent，It is still visible at a specific brightness and angle of view

**Comment by eyeslugger** [comment]
or some stage such like“Antarctica”

**Comment by refractionpcsx2** [comment]
yes, that's not a fix, that's a hack to try and remove it.

**Comment by eyeslugger** [comment]
> yes, that's not a fix, that's a hack to try and remove it.

So will that be fixed in future versions ？

**Comment by refractionpcsx2** [comment]
Hopefully, yeah.

**Comment by Wraith1080** [comment]
Sorry to comment on a closed issue. But I think the problem went away on the latest build. Also setting the CPU render size to 384 with Blended Sprites/Triangles fixed most of the shadow issue for me.

The game looks like this on the latest build (1.7.4354) with the mentioned fixes

![image](https://user-images.githubusercontent.com/6779374/230724767-928fa61e-abf9-4ca2-a266-36b0467689c5.png)
