### ISSUE TITLE
[BUG]: Resident Evil Dead Aim - Grids on water textures with internal resolutions above x1.25

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8428]
### Describe the Bug

The title says it all, GS dump and screenshot below.

### Reproduction Steps

Reach to a stage with water textures and then set internal resolution to a value above x1.25.

### Expected Behavior

No grids on water textures.

### PCSX2 Revision

v1.7.4245

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GTX 1060 3GB

### GS Window Screenshots

![Resident Evil - Dead Aim_SLES-51448_20230318153654](https://user-images.githubusercontent.com/19964653/226129566-3d12ce20-b207-48f2-9244-dff831056348.png)

### Logs & Dumps

[GS Dump](https://drive.google.com/file/d/1AB0UQ6OTkMHMYIDBN-EtF6WH_8jlWvIr/view?usp=share_link)

**Comment by refractionpcsx2** [comment]
As the issue template says, we don't accept bug reports for upscaling problems,. we know it's buggy, that's just the nature of it.
