### ISSUE TITLE
SPU2-X, PortAudio ALSA output mutes itself at random

### ISSUE THREAD

**Issue by OrdinaryMagician** [PCSX2/pcsx2#844]
I'm on Arch Linux x64. PCSX2 built from [latest commit as of writing this](https://github.com/PCSX2/pcsx2/commit/cee0b795eea2e28fdaca7855087415952225987b).

It seems that when using ALSA output with PortAudio, sound will just mute itself until I reload the plugin, sometimes almost immediately, other times after less than a minute. What I find strange is that there is nothing in the log, nothing in stdout/stderr, it just happens without any warnings or errors.

If it's relevant, I have integrated Intel HD Audio and here's my [asound.conf](https://gist.github.com/OrdinaryMagician/6e856d6cc87e477680a4), which may or may not have any impact on this.

**Comment by gregory38** [comment]
Try SDL output.

**Comment by OrdinaryMagician** [comment]
SDL output works perfectly fine, at least for SDL 1.2. With SDL2 I get choppy sound.

**Comment by gregory38** [comment]
I just fixed SDL2 normally. PortAudio doesn't support pulseaudio which is now the linux standard. It could be related.

**Comment by OrdinaryMagician** [comment]
I don't even use pulseaudio or have it installed anyway, but I guess I'll switch to SDL2 now.

**Comment by Shoegzer** [comment]
Hello, I'm seeing the same issue on my end, even after upgrading to the latest PPA dated yesterday with SDL2 fixes.  Gregory, I've posted my SPU2-X config here for reference as you requested, hope it helps.

 ``` 
[SOUNDTOUCH]
SequenceLengthMS=30
SeekWindowMS=20
OverlapMS=10
[MIXING]
Interpolation=4
Disable_Effects=0
DealiasFilter=0
FinalVolume=100
AdvancedVolumeControl=0
VolumeAdjustC\(dB\)=0
VolumeAdjustFL\(dB\)=0
VolumeAdjustFR\(dB\)=0
VolumeAdjustBL\(dB\)=0
VolumeAdjustBR\(dB\)=0
VolumeAdjustSL\(dB\)=0
VolumeAdjustSR\(dB\)=0
VolumeAdjustLFE\(dB\)=0
[OUTPUT]
Output_Module=SDLAudio
Latency=120
Synch_Mode=0
[PORTAUDIO]
HostApi=ALSA
Device=default
Wasapi_Exclusive_Mode=0
Minimal_Suggested_Latency=1
Manual_Suggested_Latency_MS=20
[DEBUG]
Global_Enable=0
Show_Messages=0
Show_Messages_Key_On_Off=0
Show_Messages_Voice_Off=0
Show_Messages_DMA_Transfer=0
Show_Messages_AutoDMA=0
Show_Messages_Overruns=0
Show_Messages_CacheStats=0
Log_Register_Access=0
Log_DMA_Transfers=0
Log_WAVE_Output=0
Dump_Info=0
Dump_Memory=0
Dump_Regs=0
Access_Log_Filename=SPU2Log.txt
WaveLog_Filename=SPU2log.wav
DMA4Log_Filename=SPU2dma4.dat
DMA7Log_Filename=SPU2dma7.dat
Info_Dump_Filename=SPU2Cores.txt
Mem_Dump_Filename=SPU2mem.dat
Reg_Dump_Filename=SPU2regs.dat
 ```

**Comment by gregory38** [comment]
I found other bug report with the same issue on others applications.
For me the issue is related to bad interaction of portaudio and pulseaudio. SDL is the alternative.
