### ISSUE TITLE
[BUG]: We love katamari (SLPS-25467) |  A color of bottom of the screen during screen trantision is glitched.

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#8441]
### Describe the Bug

A color of bottom of the screen during screen trantision is glitched.
this happen with Both renderer, and no Hardware fixes works.
![Minna Daisuki Katamari Damacy_SLPS-25467_20230319230301](https://user-images.githubusercontent.com/121824800/226181233-4a6bc037-5c22-4def-adac-7112d94c3cdd.png)

### Reproduction Steps

If you have an savedata, select collection (Blue katamari)
you have to beat tutorial if you don't have it.

### Expected Behavior

![a](https://user-images.githubusercontent.com/121824800/226181181-2ef15a92-a07b-40d9-875d-155f3a7397b9.png)

### PCSX2 Revision

Nightly - v1.7.4252

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i5-8500 CPU 3.00GHz

### GPU

NVIDIA GeForce GTX 1050Ti

### Logs & Dumps

[WLK_sc_un_gli.zip](https://github.com/PCSX2/pcsx2/files/11011231/WLK_sc_un_gli.zip)

**Comment by Buzzardsoul** [comment]
This is a regression. It was non-existent just a couple of months ago.

**Comment by refractionpcsx2** [comment]
I'm surprised this ever worked, the transfer for the background happens in 2 halves and it gets offset in to a pixel as it finishes the first transfer, which is why the colours go bad.
