### ISSUE TITLE
[BUG]: Tony Hawk's Underground 2 Colorful dots on the left side of the screen

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#8447]
### Describe the Bug

Colorful dots on the left side of the screen in HW mode that are caused by a recent GS pr. This is a regression.

### Reproduction Steps

Just start a new game. Once you start the level, you'll see those dots.

### Expected Behavior

No dots. Just like SW renderer.

### PCSX2 Revision

1.7.4244

### Operating System

Windows 11

### CPU

i5-8600

### GPU

GTX 1080

### GS Settings

Normal

### GS Window Screenshots

![Tony Hawk's Underground 2_SLUS-20965_20230319225721](https://user-images.githubusercontent.com/126727903/226205912-752d50e8-3bc9-45c9-ad57-1abcfa3f3922.png)

### Logs & Dumps

[Tony Hawk's Underground 2_SLUS-20965_20230319225721.gs.zip](https://github.com/PCSX2/pcsx2/files/11012154/Tony.Hawk.s.Underground.2_SLUS-20965_20230319225721.gs.zip)

**Comment by refractionpcsx2** [comment]
Weird, it only happens in Native too.. alright, thanks

**Comment by refractionpcsx2** [comment]
It broke in 1.7.4130 #8223
so I guess that's on me :P

**Comment by stenzek** [comment]
Fixed in #8209, for the record, the clamp isn't.. well.. clamping, because of the precision of normalized coordinates when the target is tiny. #8209 kinda works around it by aligning targets to the page size.
