### ISSUE TITLE
Better save/load state shortcuts

### ISSUE THREAD

**Issue by MadaraUchiha** [PCSX2/pcsx2#845]
Currently, PSCX2 employs F1 and F3 as save state and load state respectively.

That works find for some use cases, but a common use case is to save at some save point in the past, and then save under a different state number during a break or during battle, where it is desirable to return to the past saved spot.

While this is possible via the menu, it's clumsy and clunky, also remember that not all games are pausable, so one may have to pause emulation altogether, then go to the menu, and resume emulation (which will abruptly continue the game, which is awkward, especially if during battle)

I propose adopting what Visual Boy Advance did for its save states: F1 to load from state 1 (or 0, whatever), and SHIFT+F1 to save on state 1 (or 0, whatever), or the other way around. F2 to load from state 2, and so on and so forth.

This will allow easy access to the full save-state capabilities of PCSX2, without ever leaving the game.

WDYT?

**Comment by willkuer** [comment]
Then we only have three savestates as all other f-keys are already in use.

What is the problem with f2?

I would actually hate it when I am trying to save a state but hit ctrl or capslock instead of shift and load the state. This could possibly send me back some gaming hours.

**Comment by MadaraUchiha** [comment]
The other F-keys can be remapped, this has various advantages. (And you know what? I can live with this only being true for 3 slots for starters)

Also, the same can be said to wanting to press F3 but accidentally pressing F1 or vice versa. That's why PCSX2 provides backups of save states by default.

**Comment by willkuer** [comment]
F3 and f1 have one key in-between. Hitting the wrong one would be hard to achieve. Remapping the functions keys as well doesn't sound nice to me.

Still what is the problem of using the current f2 switch system

**Comment by MadaraUchiha** [comment]
For starters, there's no readily available documentation. I don't even know what F2 does.

**Comment by MadaraUchiha** [comment]
As for hitting the wrong one being hard to achieve, it's not. It doesn't matter how different you make the save and load shortcuts, if the mind is confused, you'll hit the wrong one. It happens to everyone, and it definitely happened to me with PCSX2, and I don't blame the program. 

It's not like "I want to save, let's press F1, oh no, I pressed F3 because a sudden gust of wind moved my finger", it more like "I want to save, let's press F3..... crap."

**Comment by avih** [comment]
> For starters, there's no readily available documentation. I don't even know what F2 does

F2 goes to the next save slot (such that F1 or F3 will save/load from that slot respectively), and shift-F2 goes to the previous slot. The current slot is visible at the end of the game window title bar.

While it's true that the state of PCSX2 documentation is suboptimal, there is a `PCSX2_FAQ.pdf` file distributed together with PCSX2 itself at the `docs` dir (also with nightly/development builds), which lists all the default KB shortcuts. Also see next.

> As for hitting the wrong one being hard to achieve, it's not

You don't have to use KB shortcut if it's hard for you to remember (use the menu instead), or you could map them to to keys you're more familiar with, see https://github.com/PCSX2/pcsx2/blob/master/bin/PCSX2_keys.ini.default

We also have a "backup save" feature where per slot it also keeps the previous save. Such that if you accidentally saved and overwritten a state you wanted to keep, you can still load the backup save using shift-F3.

Other than those suggestions, I don't have a bright idea on how to prevent people from accidentally saving state instead of loading it, or vice verse.

**Comment by MadaraUchiha** [comment]
This feature request isn't about prevent accidental saves, PSCX2 is fairly good at that. It's about a better mapping for saving/loading on all save states, without having to remember/lookup which state you're on. (I for once, like playing on full screen most of the time).

I did mention the backup save feature, and already said it's great (saved my game more than once :+1:)

**Comment by avih** [comment]
At some stage you explained that the reason for the request is that it's hard/impossible to load different state without the menu and that you didn't know what F2 does - which is just allowing that.

On this case, "better" is a subjective thing. One could argue that it's easier to always use F1/F3 for save/load, and change slot using F2 once in a while, than using different shortcuts for different slots. Like, if it's hard to remember that F1/F3 saves/loads, imagine the strain on ones mind to recall to which slot he saved the previous time.

So it's possible to load save to all slots using the KB only, and personally (subjectively) I prefer this system over

**Comment by yorkiesandskittles** [comment]
Even better than this would be user-configurable hotkeys.

**Comment by avih** [comment]
> Even better than this would be user-configurable hotkeys.

You mean like the file I linked to two comments up?

**Comment by gregory38** [comment]
Is the issue still valid? Ini seems enough?

**Comment by avih** [comment]
Looks to me like the replies were good enough. S/he can ask to reopen if there are good reasons.

**Comment by MadaraUchiha** [comment]
Yeah, no. I got my answer. Perhaps documentation needs a bit of addressing, but that would be a different issue. Cheers.
