### ISSUE TITLE
[BUG]: Can't compile with Achievements disabled

### ISSUE THREAD

**Issue by DNDEBUG** [PCSX2/pcsx2#8457]
### Describe the Bug

If i turn off the USE_ACHIEVEMENTS option the compilation fails

### Reproduction Steps

set USE_ACHIEVEMENTS to OFF

### Expected Behavior

for it to be compiled with USE_ACHIEVEMENTS set to OFF

### PCSX2 Revision

1.7.4263

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Artix

**Comment by Mrlinkwii** [comment]
what build error do you get ( if any) ?

**Comment by LeCharlatan** [comment]
Tried to build without achievements to verify and get an error.

Here the terminal output : 

> /home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/CommonHotkeys.cpp: Dans la fonction « void HotkeyAdjustTargetSpeed(double) »:
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/CommonHotkeys.cpp:46:34: erreur: « Achievements » n'a pas été déclaré
   46 |         const double min_speed = Achievements::ChallengeModeActive() ? 1.0 : 0.1;
      |                                  ^~~~~~~~~~~~
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:4365: pcsx2/CMakeFiles/PCSX2.dir/Frontend/CommonHotkeys.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:6962:43: erreur: « bool FullscreenUI::OpenAchievementsWindow() » aurait dû être déclaré à l'intérieur de « FullscreenUI »
 6962 | bool FullscreenUI::OpenAchievementsWindow()
      |                                           ^
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:6962:6: erreur: rend ambigüe la nouvelle déclaration de « bool FullscreenUI::OpenAchievementsWindow() »
 6962 | bool FullscreenUI::OpenAchievementsWindow()
      |      ^~~~~~~~~~~~
Dans le fichier inclus depuis /home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:21:
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/./Frontend/FullscreenUI.h:36:14: note: ancienne déclaration « void FullscreenUI::OpenAchievementsWindow() »
   36 |         void OpenAchievementsWindow();
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:6967:43: erreur: « bool FullscreenUI::OpenLeaderboardsWindow() » aurait dû être déclaré à l'intérieur de « FullscreenUI »
 6967 | bool FullscreenUI::OpenLeaderboardsWindow()
      |                                           ^
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:6967:6: erreur: rend ambigüe la nouvelle déclaration de « bool FullscreenUI::OpenLeaderboardsWindow() »
 6967 | bool FullscreenUI::OpenLeaderboardsWindow()
      |      ^~~~~~~~~~~~
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/./Frontend/FullscreenUI.h:37:14: note: ancienne déclaration « void FullscreenUI::OpenLeaderboardsWindow() »
   37 |         void OpenLeaderboardsWindow();
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/{user}/Documents/Compilation/PCSX2/pcsx2-1.7.4263/pcsx2/Frontend/FullscreenUI.cpp:6972:49: erreur: « void FullscreenUI::DrawAchievementsSettingsPage() » aurait dû être déclaré à l'intérieur de « FullscreenUI »
 6972 | void FullscreenUI::DrawAchievementsSettingsPage()
      |                                                 ^
make[2]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:4381: pcsx2/CMakeFiles/PCSX2.dir/Frontend/FullscreenUI.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1071: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by DNDEBUG** [comment]
same thing as LeCharlatan posted
but english

**Comment by ISuckGood** [comment]
If i set this in windows 
![image](https://user-images.githubusercontent.com/42075250/227353048-ae7c6095-c984-492f-9f06-5d2b109bccd0.png)

I get this 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2653	'Achievements': is not a class or namespace name	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\CommonHotkeys.cpp	46	
Error	C2556	'bool OpenAchievementsWindow(void)': overloaded function differs only by return type from 'void FullscreenUI::OpenAchievementsWindow(void)'	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\FullscreenUI.cpp	6963	
Error	C2556	'bool OpenLeaderboardsWindow(void)': overloaded function differs only by return type from 'void FullscreenUI::OpenLeaderboardsWindow(void)'	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\FullscreenUI.cpp	6968	
Error	C3861	'ChallengeModeActive': identifier not found	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\CommonHotkeys.cpp	46	
Error	C2244	'DrawAchievementsSettingsPage': unable to match function definition to an existing declaration	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\FullscreenUI.cpp	6972	
Error	C2371	'FullscreenUI::OpenAchievementsWindow': redefinition; different basic types	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\FullscreenUI.cpp	6962	
Error	C2371	'FullscreenUI::OpenLeaderboardsWindow': redefinition; different basic types	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\FullscreenUI.cpp	6967	
Error	C2737	'min_speed': const object must be initialized	C:\Users\xxx\Source\Repos\pcsx2\out\build\x64-debug\pcsx2	C:\Users\xxx\source\repos\pcsx2\pcsx2\Frontend\CommonHotkeys.cpp	46	

Is this the error ?

**Comment by Mrlinkwii** [comment]
@ISuckGood  try #8458

**Comment by ISuckGood** [comment]
I dont know how to get your branch without doing manual copy of the 2 zips and the qt framework . Too much work unless you know of a trick without making a new git clone and patching these missing dependencies

**Comment by F0bes** [comment]
You can clone the fork independently

```
git clone https://github.com/TellowKrinkle/pcsx2.git --recursive --branch=FixNoAchievements
```

Or you can add it as a remote to an existing PCSX2 repository
```
git remote add tk https://github.com/TellowKrinkle/pcsx2.git
git fetch tk
git checkout tk/FixNoAchievements
```

Or, if you have Github's cli tool

```
gh pr checkout 8458
```

**Comment by ISuckGood** [comment]
Thank you for the suggestion i found a way :
![image](https://user-images.githubusercontent.com/42075250/227365636-22d5a77e-31d9-4607-acce-cb2374e8ec7d.png)

Also windows variant compilation of his branch works fine 
![image](https://user-images.githubusercontent.com/42075250/227365861-88dc44dd-2400-4d65-aa01-ee4455ba03e6.png)
