### ISSUE TITLE
[Feature Request]: Guitar support (not USB)

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#8459]
### Description

The ability to change from Dualshock to Guitar in the input settings.

### Reason

Make the Guitar Hero games etc. playable with a standard PS2 Guitar.

### Examples

Like it worked in Wx before. Maybe this is on a list of "coming" features, but I can't find an Issue for it.

**Comment by refractionpcsx2** [comment]
> Maybe this is on a list of "coming" features, but I can't find an Issue for it.

yes it is https://github.com/PCSX2/pcsx2/discussions/5947

No need for a request, it's coming
