### ISSUE TITLE
[BUG]: PCSX2 doesn't populate game list when disk images are stored on a network share

### ISSUE THREAD

**Issue by hansomdevil** [PCSX2/pcsx2#8467]
### Describe the Bug

When disk images are stored on an SMB shared folder, PCSX2 doesn't populate them in the game list. When I copy a file from the network share to a local drive, it shows in the game list. If you load the file directly from the network directory, the game boots and plays as expected.
<img width="794" alt="Screenshot 2023-03-22 084218" src="https://user-images.githubusercontent.com/20796275/226959048-3028b822-7b88-4741-ad40-ff3c7afa9fe1.png">
<img width="602" alt="Screenshot 2023-03-22 084143" src="https://user-images.githubusercontent.com/20796275/226959071-55a4ba4b-4cee-4227-97f8-f6e65688d1b5.png">
<img width="842" alt="Screenshot 2023-03-22 084240" src="https://user-images.githubusercontent.com/20796275/226959087-5a1a0f1e-f39a-4b50-8c21-aaad5ba14204.png">

### Reproduction Steps

Add a SMB network share directory to the game list search path. Copy a file from the network share to a local directory, and add that to the game list search path. The game list won't show anything from the network share, but the file copied to the local directory should show up.

### Expected Behavior

Something changed in the past week or so that prevents games on a network share from showing up in the game list.

### PCSX2 Revision

v1.7.4268

### Operating System

Windows 11

**Comment by hansomdevil** [comment]
> 

I think it's actually a problem on my end. I couldn't find a prior version that worked. But I copied the files to a new directory on the network share and added that directory to the game list search. PCSX2 recognized the files in the new directory. I must have some kind of file system error or cache problem.

**Comment by Mrlinkwii** [comment]
can this be rechecked on latest nightly

**Comment by refractionpcsx2** [comment]
I don't think anything has changed.

**Comment by Mrlinkwii** [comment]
whats the status of this ?

**Comment by TellowKrinkle** [comment]
BTW if you suspect caching issues, you can use Settings → Rescan All Games to clear the game cache and reload everything.
