### ISSUE TITLE
Formula One 2003 - Missing announcer voices

### ISSUE THREAD

**Issue by zteady** [PCSX2/pcsx2#8468]
### Describe the Bug

Audio working well but missing legendary announcer voices

### Reproduction Steps

Just start play game. No announcer voices.

### PCSX2 Revision

New nightly

### Operating System

Windows 11

### CPU

i9-12900k

### GPU

3080 TI

**Comment by prafullpcsx2** [comment]
Seems to be working fine for me. You may need to adjust ingame sound volumes to hear the announcer voices.

**Comment by zteady** [comment]
> Seems to be working fine for me. You may need to adjust ingame sound volumes to hear the announcer voices.

Tried setup everything down and only leaved "TV commentary" volume 100%. Silence.

**Comment by Mrlinkwii** [comment]
Seems to be working fine for me iswell  , announcer will talk  at the start of the race  and when your crash and at the end of the  race
