### ISSUE TITLE
PCSX2 writing to our iso's when it shouldn't be.

### ISSUE THREAD

**Issue by kamijoutouma** [PCSX2/pcsx2#847]
http://forums.pcsx2.net/Thread-PCSX2-is-writing-to-our-iso-s

**Comment by avih** [comment]
Next time please summarize the details at the issue you open. Posting a link to the forum is OK for additional info, but it doesn't replace an actual report.

Also, at the forum thread you pretty much only suggest that PCSX2 overwrites the ISO file and provide some irrelevant screenshot and a guess from a friend as "proof". 

It's highly unlikely that PCSX2 overwrites the ISO files, and your screenshot doesn't suggest that it does, neither to me nor to the other members which replied to you at the forum.

I'm closing this issue, please open another one or add more info here if you actually have some evidence for that happening.

**Comment by kamijoutouma** [comment]
[code]PCSX2 1.3.1-20150922011125 - compiled on Sep 22 2015
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Education (build 10240), 64-bit
	Physical RAM     =  32458 MB
	CPU name         =  Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  2.393 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfcbfbff fed87383
	x86EFlags        =  28100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. FMA

Reserving memory for recompilers...

Loading plugins...
	Binding   GS: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\GSdx32-SSE4.dll 
Windows 10.0.10240
	Binding  PAD: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\LilyPad.dll 
(GameDB) 9691 games on record (loaded in 461ms)
	Binding SPU2: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\SPU2-X.dll 
	Binding CDVD: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\cdvdGigaherz.dll 
	Binding  USB: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\USB_VB.dll 
	Binding   FW: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\FWnull.dll 
	Binding DEV9: C:\Users\Kamijou\Documents\emulators\PCSX2\plugins\DEV9ghzdrk.dll 
Plugins loaded successfully.
[/code]
using internal iso reader.

give me a sec i have to reextract so i can take screenshots.

EDIT:

in the initial screenshot if anyone hasn't noticed. That elf file has no elf header? anyone seeing what i mean by it got rearranged.
[img]http://s20.postimg.org/anxq02fsd/hack00.png[/img]

someone else sent me a screenshot of their iso.

notice their files actually have an elf header unlike mine and my friends
not to mention the top one looks completely different from the image below. How is pcsx2 doing this?
[img]http://i.imgur.com/z572hzK.png[/img]


can someone please explain how that's possible? when they exactly the same game.

screenshot of my copy btw

[img]http://i.imgur.com/1eoYQcD.png[/img]
Mine is the same as my freinds but different from the the screenshot that was sent.

**Comment by kamijoutouma** [comment]
Added more info

**Comment by avih** [comment]
None of these screenshot suggest to me that that PCSX2 has modified the ISO, or even that the ISO got modified at all.

You can start by ripping the DVD to an ISO, then do a checksum (md5/sha1/whatever) of the ISO file, and then after you think PCSX2 has modified it, do another checksum of the file.

If the two checksums are different, then the ISO file was modified. It's still not a proof that PCSX2 modified it, but it does say something modified it.

If, however, the checksum did not change, then the ISO was not modified.

Do this test and post the results here. Thanks.

**Comment by kamijoutouma** [comment]
http://i.imgur.com/7giDyc1.png
http://i.imgur.com/aSwf62K.png

well checksums are the same.

so how the heck are the files different?

**Comment by kamijoutouma** [comment]
the interesting part is

the checksum for the elf files inside of the iso's is different

http://i.imgur.com/3cmE0MQ.png
http://i.imgur.com/phQgXID.png

**Comment by avih** [comment]
I don't know how you check the checksum of the ELF inside the ISO, but if the ISO file checksum is not different, than except if you bumped into a very very unlikely case of hash collision, the file has not been modified, period.

**Comment by kamijoutouma** [comment]
It looks like Winrar is not extracting the iso correctly which is what is causing the elf file to be different.

**Comment by kamijoutouma** [comment]
extracting in 7zip and the checksum is the same and there is an elf header

**Comment by kamijoutouma** [comment]
looks like no more using winrar to make changes to iso's :|

**Comment by kamijoutouma** [comment]
sorry about this

**Comment by avih** [comment]
No worries. Thanks for confirming it's not an issue.
