### ISSUE TITLE
[BUG]: missing pcsx2\bin\resources\cheats_ni.zip pcsx2\bin\resources\cheats_ws.zip

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8472]
### Describe the Bug

When building the exe these files are not found at the end of the build:

pcsx2\bin\resources\cheats_ni.zip
pcsx2\bin\resources\cheats_ws.zip
![image](https://user-images.githubusercontent.com/42075250/227337270-256bc318-6b56-4888-9e8a-200c033cb210.png)

### Reproduction Steps

Build the project exe

### Expected Behavior

No build error. This was working fine a few weeks ago without manually copying these files from the web based installer . Idk whats the issue or if is an issue tbh.

### PCSX2 Revision

latest pulled

### Operating System

Windows 11

**Comment by RedDevilus** [comment]
Yeah it's kinda linked as a submodule from the other repo.

**Comment by ISuckGood** [comment]
Thank you for the responses . I am just copying the stuff from the normal exe installer in my own github project and i have no issues.
