### ISSUE TITLE
[BUG]: Secret Agent Clank NTSC-U "Whip it Good" impossible to get

### ISSUE THREAD

**Issue by LunarmanEXE** [PCSX2/pcsx2#8473]
### Describe the Bug

The objective for the skill point "Whip it Good" can't be done with the Plasma Cord on PCSX2. The skill point still unlocks with the Plasma Cord on console.

### Reproduction Steps

Start any challenge on Prison Planet with 40 or more enemies in it. Defeat a total of at least 40 using the Plasma Cord.

### Expected Behavior

The skill point should unlock after 40 kills with either the Plasma Whip or Plasma Cord. Unfortunately it never unlocks with the Plasma Cord, no matter how many enemies you kill with it.

### PCSX2 Revision

1.7.4269

### Operating System

Windows 10 (64bit)

### CPU

i7-2600

### GPU

GT 1030

**Comment by Mrlinkwii** [comment]
can this be rechecked on latest nightly

**Comment by TheTechnician27** [comment]
Hey, Lunar. If you can get me a save file or a save state, I'll be more than willing to test this and see if I can reproduce it.

**Comment by LunarmanEXE** [comment]
> Hey, Lunar. If you can get me a save file or a save state, I'll be more than willing to test this and see if I can reproduce it.

Sorry for the late response. I just uploaded both to my Google Drive. Here's a link.
https://drive.google.com/drive/folders/1-Ubjwfn-mCgtu2Qlomr3f54SjXx_Cn2Q?usp=sharing

**Comment by TheTechnician27** [comment]
Thanks a bunch! I can't say whether or not this was an issue in the past, but I managed to get the skill point in Amoeboid on a Pole, where thankfully there are a lot of fodder enemies. Currently on v1.7.5563. Attached is a screenshot of the obtained skill point and the memcard with the skill point in case you want it.

![Secret Agent Clank_SCUS-97623_20240218081129](https://github.com/PCSX2/pcsx2/assets/12673964/e08f92cc-e735-44f1-9148-9d033dfb0663)

[Mcd006.ps2.zip](https://github.com/PCSX2/pcsx2/files/14322807/Mcd006.ps2.zip)
