### ISSUE TITLE
Flatout 2 - Super annoying screen flickerin in left side of screen

### ISSUE THREAD

**Issue by zteady** [PCSX2/pcsx2#8474]
### Describe the Bug

There is annoying flickering happening in left side on screen. Only in game, not in menus.

Video:
https://drive.google.com/file/d/1Y6_Qfa62CSNe03JFqdXtrMW6dIVa6ZKD/view?usp=sharing

### Reproduction Steps

Start play normally

### PCSX2 Revision

New nightly

### Operating System

Windows 11

### CPU

i9-12900k

### GPU

3080 TI

**Comment by Mrlinkwii** [comment]
Can I have a gs dump? Also dose it happen at native res?

**Comment by coornio** [comment]
Testing this on v4438 and not noticing any artifacting or effects flickering on either side of the screen on a variety of stages. All seems to be good. Could probably close, unless author can prove this issue persists to this day but requires a particular trigger sequence.

**Comment by Mrlinkwii** [comment]
can this be checked , their has been no response for 3 months

**Comment by Technostrophe** [comment]
[FlatOut 2_SLUS-21251_20230709170137.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11995461/FlatOut.2_SLUS-21251_20230709170137.gs.zst.zip)

Looks to be fine as of 1.7.4708

**Comment by evildeadhc** [comment]
1.7.5592 I have exactly the same flickering in the left side on screen. I tried different settings etc, but nothing helped.

**Comment by refractionpcsx2** [comment]
please discuss it in #10865
