### ISSUE TITLE
[BUG]: Build fails if USE_OPENGL is set to OFF

### ISSUE THREAD

**Issue by DNDEBUG** [PCSX2/pcsx2#8477]
### Describe the Bug

having USE_OPENGL set to OFF
and USE_VULKAN to ON
results in
```
/pcsx2/pcsx2/GS/GSUtil.cpp:224:25: error: no member named 'Vulkan' in 'GSRendererType'
```

### Reproduction Steps

Set USE_OPENGL to OFF

### Expected Behavior

having only USE_VULKAN on
only vulkan be used in the final build

### PCSX2 Revision

v1.7.4272

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Artix

**Comment by stenzek** [comment]
The identifier is incorrect, but this is not a supported configuration, disabling GL is only for macs.

**Comment by ISuckGood** [comment]
Then we can throw a compiler error if the platform is not mac and opengl is disabled using #ifdef so that no one tries invalid  preprocessor directives

**Comment by JordanTheToaster** [comment]
> Then we can throw a compiler error if the platform is not mac and opengl is disabled using #ifdef so that no one tries invalid preprocessor directives. This should also avoid people opening a lot of invalid tickets and trying unsupported variations

They don't need to open tickets and I would like to ask if you could stop opening tickets or posting useless information as it just clutters up pull requests and the github feed.

**Comment by DNDEBUG** [comment]
shut up
i'm trying to sleep
