### ISSUE TITLE
Linux OnePad force feedback doesn't work

### ISSUE THREAD

**Issue by helkaluin** [PCSX2/pcsx2#848]
The is latest git at b9e00ab611efba883ad87295fd94be8231e774ea.

Wired XBox 360 controller.  fftest shows rumble/force feedback does work.  In-game however there's no force feedback.

Lilypad on Windows (on the same machine) does result in force feedback.  Tested game was FFXII.

Happy to provide logs and further details.  Just tell me what you need.

**Comment by OrdinaryMagician** [comment]
SDL 1.2 does not support force feedback, you'd need to build with -DSDL2_API='TRUE'.

Even then, force feedback support is still glitchy.

**Comment by helkaluin** [comment]
Darn.  Guess I'll have to stick with Pokopom and its hand-written conf then.  (At least with that force feedback works on Linux.)

**Comment by Shoegzer** [comment]
Wow, I had no idea there even WAS a plugin option that provided rumble for linux.  Thanks for mentioning it.  That said, it seems that it only supports xinput (I have a ds4 pad), and I'm not seeing where it writes the config file - at least, it's not in ~/.config/PCSX2.  Do you know?  

Beyond that though, I'm curious...  @KrossX: clearly you have experience and talent writing input plugins with rumble.  Is there any way you can be coaxed into adding libevdev/rumble support to OnePad if/when you have a spare cycle?  It seems the only major difference remaining between Windows and Linux variants and would certainly be well appreciated by many.  :)

**Comment by KrossX** [comment]
If it uses SDL, then I have no clue. In Pokopom I used the kernel API [Input + FF info](https://www.kernel.org/doc/Documentation/input/ff.txt). I think it's how fftest uses the device too. It is very WIP code that was good enough for me, but it's unreliable and can reduce the emulator's performance drastically (though I think that's the hot-plug support).

As for messing with OnePad's code me'self, it will have to wait until I install a distro that I'm comfortable to develop with. I am too used to Windows + VisualStudio.

**Comment by helkaluin** [comment]
@Shoegzer Pokopom's conf is written like where every other conf is written: `$PCSX2_CONF_PATH/inis/padPokopom.ini`

A skeleton one is created the first time you load the plugin.

**Comment by karasuhebi** [comment]
Interesting. I could have sworn I told him to check there when he asked me about this on IRC. Could you provide your config in here just in case he can't find one in his folder?

**Comment by helkaluin** [comment]
Here you go: https://gist.github.com/helkaluin/fb1784cb9b0cea5ae32f

**Comment by karasuhebi** [comment]
Thanks!

**Comment by Shoegzer** [comment]
@KrossX Indeed, OnePad currently uses SDL but the intent is to move towards evdev, using libevdev, which if I'm not mistaken, is preferable for many reasons including being simpler and easier to work with (see issue #662).  Other emus such as Dolphin have moved on from SDL to evdev as well, for the same reasons.

In any event, we deeply appreciate your looking into OnePad code whenever you get a chance - take whatever time you need - it's just nice to know it might get SOME love at SOME point.   :-)  I believe Gregory was planning to look into it himself, but then he became understandably busy with graphics-related issues (and doing quite an amazing job at that).
 
I did get a chance to check out Pokopom and you're right of course - performance takes a serious dive (and to correspond, PCSX2 CPU utilization went through the roof).  So, unfortunately doesn't seem too viable at least for PCSX2 in linux.  Ah well.

@karasuhebi Yep, you sure did, and in my case it should be in ~/.config/PCSX2/inis.  However, after loading the plugin, launching PCSX2 with a game, and quitting out, the file wasn't posted there.  Not sure why.  In any event for reasons above I don't think it's going to work on this setup unless I'm missing something fundamental.

**Comment by helkaluin** [comment]
@Shoegzer Fug, @3kinox's OnePad branch works marvellously.  (Tested games are FFXII, Katamari Damacy, and Taiko Drum Master.)

I don't have a forum account so I can't comment on the thread.  Once he posts his pull request here I'll be happy to provide test results.

**Comment by 3kinox** [comment]
I made the pull request just now, you can test my latest commits too. Normally, they don't change anything from outside point of view, just test if it crashes and such :) it is there to isolate every last dependency to SDL. evdev is coming(if I manage to understand it hahaha).

**Comment by karasuhebi** [comment]
Nice to see someone implementing force feedback on OnePad. Thanks @3kinox! I hope it gets merged soon :D

**Comment by helkaluin** [comment]
Fixed with https://github.com/PCSX2/pcsx2/pull/892
