### ISSUE TITLE
[BUG]: Fast CDVD notice shown twice in log

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#8481]
### Describe the Bug

Fast CDVD is enabled, this may break games. is shown twice in the log, once as the normal Unsafe Settings warning and right after, as OSD [unsafe_settings_warning]:  Fast CDVD is enabled, this may break games.

### Reproduction Steps

Enable Fast CDVD and the separate debug log window

### Expected Behavior

Warning to show only once

### PCSX2 Revision

PCSX2 Nightly 1.7.4274

### Operating System

Windows 11

**Comment by Masamune3210** [comment]
I know its a nightly, just wanted to get the notice out and wasn't sure how else honestly. Would fix it myself but I cant find from a cursory glance at the code where this would be coming from

**Comment by Mrlinkwii** [comment]
I believe this is how it's ment to be , one of them being the OSD prompt the users can see (users can turn this off  in the OSD settings)  and the other one is  the program logging the setting to help non users looking at the log if the OSD messages are turned off

**Comment by stenzek** [comment]
Working as intended, as link said.
