### ISSUE TITLE
[BUG]:  vkQueueSubmit failed:  (-4: VK_ERROR_DEVICE_LOST) in Burnout 3

### ISSUE THREAD

**Issue by hansomdevil** [PCSX2/pcsx2#8500]
### Describe the Bug

When using Vulkan, depending on the scaling resolution PCSX2, will throw a (DoSubmitCommandBuffer) vkQueueSubmit failed:  (-4: VK_ERROR_DEVICE_LOST) error when playing Burnout 3. The screen will go black, graphics driver crash, and then return with a black window where it was rendering. It seems to be triggered differently depending on the scaling factor. My system uses a Ryzen 9 5900, Radeon RX 7900 XT running Windows 11 with the latest AMD GPU drivers (23.3.2). I didn't experience a problem when using OpenGL. I also played Armored Core 3 using the same settings that caused Burnout 3 to crash and had no problem.

### Reproduction Steps

I was able to trigger the error consistently at 4x scale by starting the game normally from the game list, then in the main menu get to the the country select screen, and select a country. The error should trigger as the zoom-in animation plays. I was able to trigger the error at 3x as well, though less consistently. At 3x scale it would trigger most often during a race, usually after about 2 minutes of play time.

### Expected Behavior

Using Vulkan and resolution scaling shouldn't cause driver crashes.

### PCSX2 Revision

v1.7.4285

### Operating System

Windows 11

### CPU

Ryzen 9 5900

### GPU

Radeon RX 7900 XT

### GS Settings

Internal Resolution: 3x or 4x
Blending Accuracy: Full

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/11102339/emulog.txt)

**Comment by JordanTheToaster** [comment]
Sounds more like an AMD driver issue than a PCSX2 issue.

**Comment by hansomdevil** [comment]
> Sounds more like an AMD driver issue than a PCSX2 issue.

They did make some changes to the vulkan driver in this release. From Release Notes:

"Support for:
Resident Evil™ 4 Remake
The Last of Us™ Part 1
Additional Vulkan® extensions. Click here for more information."
