### ISSUE TITLE
[BUG]: Tokimeki Memorial 3: Strange box in opening animation

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#8507]
### Describe the Bug

long box at top of screen during part of the animation 
![Tokimeki Memorial 3_SLPM-65080_20230330014354](https://user-images.githubusercontent.com/8851653/228752890-12bc5f90-7b3b-41fe-a32e-6ec8d4785949.png)

### Reproduction Steps

start game . watch intro

### Expected Behavior

![toki opening](https://user-images.githubusercontent.com/8851653/228752834-061136c6-251e-4313-b027-bab45dd28442.jpg)

### PCSX2 Revision

1.7.4288

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

happens in both hardware and software renderer

### Logs & Dumps

[Tokimeki Memorial 3_SLPM-65080_20230330014354.gs.zip](https://github.com/PCSX2/pcsx2/files/11108644/Tokimeki.Memorial.3_SLPM-65080_20230330014354.gs.zip)

**Comment by refractionpcsx2** [comment]
if you're in software before you get to that point, is it fine? if so, what if you enable "Partial Target Invalidation" then repeat on Hardware mode?

**Comment by refractionpcsx2** [comment]
Duplicate #6567
