### ISSUE TITLE
[BUG]: Tokimeki Memorial Opening animation. screwed up 3d models

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#8508]
### Describe the Bug

might be a depth issue
![Tokimeki Memorial 3_SLPM-65080_20230330014455](https://user-images.githubusercontent.com/8851653/228754115-f2a96424-81c0-469c-a255-f8bb2bf59944.png)

### Reproduction Steps

start game and watch opening animation

### Expected Behavior

![Tokimeki Memorial 3_SLPM-65080_20230330015510](https://user-images.githubusercontent.com/8851653/228754079-21efe54d-4820-4384-bfcb-4953caf85834.png)

### PCSX2 Revision

1.7.4288

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

but doesn't happen in software. 

### Logs & Dumps

[Tokimeki Memorial 3_SLPM-65080_20230330014455.gs.zip](https://github.com/PCSX2/pcsx2/files/11108695/Tokimeki.Memorial.3_SLPM-65080_20230330014455.gs.zip)

**Comment by refractionpcsx2** [comment]
Did it ever work?

**Comment by refractionpcsx2** [comment]
Duplicate #6567

**Comment by seta-san** [comment]
It is a duplicate but also presents the 2 as seperate bugs and both the issues have a gsdump

**Comment by refractionpcsx2** [comment]
okay, but it's still a duplicate.
