### ISSUE TITLE
[BUG]: EA Sports Cricket 2002 (Europe) (v2.00) Graphic and Running Animation Bug

### ISSUE THREAD

**Issue by psspecificaccnt** [PCSX2/pcsx2#8509]
### Describe the Bug

1. A graphical bug when in any match in game, where a camera angle of the batting/bowling crease to the top left of the screen is displayed whenever the ball is hit, the camera however, overlaps with a picture from the menu screen. 

2. Running Animation issue- When batting and a ball is hit, you are unable to make a run as the batsmen simply move back and forth in a loop. This is also the case when the computer is on the batting team, however. occasionally the computer is able to make a run and display the entire running animation. 

![Cricket 2002_SLES-50424_20230330123455](https://user-images.githubusercontent.com/129375331/228785687-73e06dbe-2373-45e1-aedd-783e49f78566.png)
![Cricket 2002_SLES-50424_20230330125513](https://user-images.githubusercontent.com/129375331/228785750-44d41942-721f-468b-96dd-412c8909c62b.png)

### Reproduction Steps

Graphic Bug- Play Now > Select Batting or Bowling after the coin toss > Wait for if bowling or hit the ball if batting and the camera angle of the crease will display to the top left of the screen.

Running Animation Bug (Player Perspective)- Play Now > Select Batting after the coin toss > Hit the ball and press circle to make a run.

Running Animation Bug (Computer Perspective)- Play Now > Select Bowling after the coin toss > Bowl a ball and wait for the AI or computer to make a run. 

### Expected Behavior

The camera angle of the batting/bowling crease is not supposed to overlap with a patch/image from the menu screen.

The running animation is supposed to function as in the game of cricket where the two batsmen run across to each other's opposing end in order to complete a run. The current bug/glitch is detrimental to the fundamentals of the game as a single run affects the score in a match of a longer duration. 

The game's ball and batting physics is the best I have seen of a cricket game which is why I really hope these little yet very impactful details like the running animation could be fixed at the very least. 

![Cricket 2002_SLES-50424_20230330125513](https://user-images.githubusercontent.com/129375331/228796321-ae77e946-9198-48d1-91e8-b9e1ec1770b6.png)

### PCSX2 Revision

PCSX2 v1.7.4287

### Operating System

Windows 11

### CPU

AMD Ryzen 5 4500U

### GPU

AMD Radeon Graphics

### GS Settings

Rendering: Internal Resolution - 3x Native (1080p)

**Comment by Mrlinkwii** [comment]
Dose the graphical issues happen at native res?

**Comment by Buzzardsoul** [comment]
@psspecificaccnt Can you upload a gs dump?

**Comment by psspecificaccnt** [comment]
> @psspecificaccnt Can you upload a gs dump?

The file when creating the dump displays as ZST instead of GS, do let know if that's alright as I'm not too familiar with these terms. Thank you.
[EA Cricket 2002 GS Dumps.zip](https://github.com/PCSX2/pcsx2/files/11120038/EA.Cricket.2002.GS.Dumps.zip)

**Comment by Buzzardsoul** [comment]
@psspecificaccnt While the game is on Click on Settings then Game properties then Game fixes and Enable EE timing hack and let us know if that fixes it.

**Comment by psspecificaccnt** [comment]
@Buzzardsoul Omg, that actually worked, The EE timing hack fixed the running animation bug but it didn't fix the camera graphic. Both got fixed with software rendering though! Thank you so much you genius!

**Comment by psspecificaccnt** [comment]
F9 When in game for software mode/rendering.

**Comment by refractionpcsx2** [comment]
please don't close it, it's still an issue.

**Comment by prafullpcsx2** [comment]
There seems to be some confusion here. EE timing hack doesn't fix this game. I wonder how it came into discussion? The actual fix is EE rounding nearest which was recently added to gamedb. It fixes the behavior of batsman to complete a run which also fixes the animation.

**Comment by dhilipkumar-sk** [comment]
Thnx,bro.Its really working.Good job!

**Comment by refractionpcsx2** [comment]
Sorry, forgot my own advice lol
