### ISSUE TITLE
[BUG]: Ultimate Spider-Man - Random texture distortion at certain angles in HW

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8512]
### Describe the Bug

While looking at certain textures at certain angles, a distortion effect may appear.

### Reproduction Steps

1. Load up the game in HW mode.
2. Go to the alley that you pass by in one of the initial missions (the one in which you fight some bad guys).
3. Keep running to the wall and moving sideways like I did in the screenshot.
4. Witness the distortion.

### Expected Behavior

No texture distortion.

### PCSX2 Revision

v1.7.4287

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GTX 1060 3GB

### GS Window Screenshots

![Ultimate Spider-Man_SLUS-20870_20230330154505](https://user-images.githubusercontent.com/19964653/228934595-37a87baf-b564-45e9-90d4-7ba3b9dc8181.png)

### Logs & Dumps

https://drive.google.com/file/d/1-_3f85hsN4yrit6t9czS_HphHn7J73Gx/view?usp=share_link

**Comment by refractionpcsx2** [comment]
Mean to show this tab lol 
![image](https://user-images.githubusercontent.com/6278726/228935436-c9a82c17-eb96-42fb-aa56-2847b13757a2.png)
