### ISSUE TITLE
[BUG]: Compilation Failure (cannot find a header)

### ISSUE THREAD

**Issue by f0n1x** [PCSX2/pcsx2#8515]
### Describe the Bug

/home/f0n1x/pcsx2/pcsx2/Frontend/Achievements.cpp:35:10: fatal error: 'rc_api_info.h' file not found
#include "rc_api_info.h"

Compilation process seems unable to locate rcheevos header files even though they are present in pcsx2/3rdparty/rcheevos/rcheevos/include

### Reproduction Steps

git clone --recursive https://github.com/PCSX2/pcsx2.git
cmake *build flags*
make or ninja both fail

### Expected Behavior

expected behavior is for the compilation process to locate the appropriate headers and complete compilation.

### PCSX2 Revision

v1.7.4298

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Slackware64-15.0

**Comment by stenzek** [comment]
Going to say this is probably invalid and an environment issue, since it works fine on the CI, as well as locally (Ubuntu).

**Comment by kamfretoz** [comment]
also works fine on Arch

**Comment by strodown** [comment]
Hello, 
I am also subject to the same compilation problem as mentioned above 
I compile Pcsx2 under docker 
Ubuntu : 22:04 
buildroot : 2022.03.

```
[ 94%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/VMManager.cpp.o
[ 94%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/Frontend/Achievements.cpp.o
/home/strodown/pixL/pixl/output/build/pcsx2-v1.7.4297/pcsx2/Frontend/Achievements.cpp:35:10: fatal error: rc_api_info.h: No such file or directory
   35 | #include "rc_api_info.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:1725: pcsx2/CMakeFiles/PCSX2.dir/Frontend/Achievements.cpp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/home/strodown/pixL/pixl/output/build/pcsx2-v1.7.4297/pcsx2/INISettingsInterface.cpp: In function 'std::string GetTemporaryFileName(const string&)':
/home/strodown/pixL/pixl/output/build/pcsx2-v1.7.4297/pcsx2/INISettingsInterface.cpp:48:16: warning: ignoring return value of 'int mkstemp(char*)' declared with attribute 'warn_unused_result' [-Wunused-result]
   48 |         mkstemp(temporary_filename.data());
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: Leaving directory '/home/strodown/pixL/pixl/output/build/pcsx2-v1.7.4297/buildroot-build'
make[3]: *** [CMakeFiles/Makefile2:912: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
```

**Comment by stenzek** [comment]
We don't support such environments. If you want to use them, go nuts, but we can't provide any assistance for things we don't use.
