### ISSUE TITLE
[BUG]: -raintegration commandline no longer works

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#8517]
### Describe the Bug

RetroAchievements makes use of RAIntegration for the developer's side of things where they can add/edit achievements with the toolset. This was easily accessible via the commandline -raintegration after the shortcut leading to pcsx2-qtx64-avx2.exe. As of pr #8496 (pcsx2 build 4288) this .exe is no longer being used, and pcsx2-qt.exe is used instead. The commandline doesn't function on this.

### Reproduction Steps

1. Create a shortcut of pcsx2-qt.exe
2. Go to properties of that shortcut
3. On the Target line, add -raintegration

Normally if you start PCSX2 now, it would show that RAIntegration is being used instead of the built-in system. Instead it results in an error:

![pcsx2-qtx64-avx2_2023-03-31_09-17-18](https://user-images.githubusercontent.com/10039778/229058607-0ea1c820-f575-4103-b434-d5906d10fbd8.png)

### Expected Behavior

This is what SHOULD happen (taken on build 4287 where it last worked)

![pcsx2-qtx64-avx2_2023-03-31_09-51-44](https://user-images.githubusercontent.com/10039778/229059346-f1214558-4a9e-4e44-bb9a-1b1061331441.png)

![2023-03-31_09-51-57](https://user-images.githubusercontent.com/10039778/229059354-9150a48b-1add-41d1-9f59-4005fae994bf.png)

### PCSX2 Revision

1.7.4298

### Operating System

Windows 10 (64bit)

### Additional/Updated Info

I also found that editing the pcsx2.ini file and adding `UseRAIntegration = true` no longer works either to get it to work.

**Comment by stenzek** [comment]
Try #8253
