### ISSUE TITLE
Dark Cloud Pause screen has incorrect background

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#852]
In Dark Cloud, when you open the Triangle menu in the game on console the background is a blurred version of whatever was on screen before you opened the menu. In the emulator, the background is completely black except the very top of the screen where you can see the original background.

Version = PCSX2 1.3.1-20150925184220
Renderer = DirectX11
GSDX ini = https://gist.github.com/deadair3210/23b11c3309fa5390c106
All speed hacks on except Cycle Rate Stealing. Defult to fullscreen on open
Description - The game's equipment menu has a black background instead of a blurred background
How to replicate - Boot game and get to where you can open the triangle menu, open it
Last version to work - Unknown
PC Specs - i5 2500k @ 4.0 GHz, 11 GB DDR3 RAM, GTX 660 3GB

**Comment by deadair3210** [comment]
Sorry wrong ini
Here is the correct one
https://gist.github.com/deadair3210/23b11c3309fa5390c106

**Comment by bositman** [comment]
Please edit your issue to conform with the guidelines.
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by deadair3210** [comment]
Fixed

**Comment by bositman** [comment]
Test it with the OpenGL renderer and the new accurate options (hardware depth, accurate date set to maximum) and also you did not specify if this works using a software renderer.

**Comment by deadair3210** [comment]
Disabled all speedhacks, issue still appeared. Switched to OpenGL and set the hardware depth to High End PC and turned on Accurate date set and the issue went away. Software mode fixes the issue as well

**Comment by bositman** [comment]
OK now disable one by one, accurate date, hardware depth and lower levels of blending to find out which exact feature fixes this

**Comment by deadair3210** [comment]
Could not get the issue to appear on OpenGL hardware, only by switching back to DirectX did the issue reappear

**Comment by bositman** [comment]
Cool, I'll label this properly then.
