### ISSUE TITLE
Broken assertion failed Menu using dev build.

### ISSUE THREAD

**Issue by maximu** [PCSX2/pcsx2#853]
..\..\src\msw\toplevel.cpp(1544) : assertion failed:
    Function:  wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent
    Thread:    Main/UI
    Condition: m_menuDepth > 0
    Message:   No open menus?

I Try with Visual studios 2013 and 2015's same error.
![screenshot_133](https://cloud.githubusercontent.com/assets/1274014/10124984/dc4f9b1e-6564-11e5-8d4d-270ef51f901d.png)

**Comment by willkuer** [comment]
Reproducible? If yes, how to?

**Comment by turtleli** [comment]
I think I've figured this one out - wxWidgets is version checking for the menu handling but can't recognise Windows 10. I'll see if there's a wxWidgets commit to deal with it.

**Comment by maximu** [comment]
Yes i'm using Windows 10 and jump these assertion on any options or plugin to run

**Comment by micove** [comment]
I have not tested it but this one explains the issue:
https://github.com/wxWidgets/wxWidgets/commit/9280f836c2569d0f50301a1117f7ba144e5240d2

For W10 you might need
https://github.com/wxWidgets/wxWidgets/commit/1966dfb17d7cb106d1dfb44df6a15b92ba3b8d5f
https://github.com/wxWidgets/wxWidgets/commit/c87c432033f4277bc9995a4de1390a59b810a005
https://github.com/wxWidgets/wxWidgets/commit/a8c98a119145a77b1313337314853de75562e4ab

**Comment by turtleli** [comment]
Those will probably work.

The version check which is failing is (src/msw/toplevel.cpp, 449-457)
```
        case WM_EXITMENULOOP:
            // Under Windows 98 and 2000 and later we're going to get
            // WM_UNINITMENUPOPUP which will be used to generate this event
            // with more information (notably the menu that was closed) so we
            // only need this one under old Windows systems where the newer
            // event is never sent.
            if ( wxGetWinVersion() < wxWinVersion_98 )
                processed = HandleExitMenuLoop(wParam);
            break;
```

**Comment by micove** [comment]
Yeah, the enum for W8.1 and 10 is missing and as you said this happens:

>In this case, wxGetWinVersion() used to return wxWinVersion_Unknown. This in turn causes the version check against Windows98 in toplevel.cpp:450 to fail, ultimately leading to the mentioned assert.

**Comment by maximu** [comment]
With Delete src/msw/toplevel.cpp, 449-457 lines @turtleli  Fixed this problem :)

**Comment by turtleli** [comment]
Alright, tested and applied those commits. Thanks @micove.
