### ISSUE TITLE
[BUG]: Tomb Raider Legend Wierd artifacts only SW mode works with 5FPS

### ISSUE THREAD

**Issue by husitko** [PCSX2/pcsx2#8538]
### Describe the Bug

Wierd Texture artefacts  like in Video https://www.twitch.tv/videos/1781605006
Sometimes in water too same thing happend in croft manor doors to pool room
this does it on every render metod except for Software but in SW i have like 5FPS I5 10400f and only 5% cpu usage but PCSX2 nightly OSD show its 30fps ... 

### Reproduction Steps

Go to  croft manor doors to pool room 
Screenshot SW mode ![SW](https://user-images.githubusercontent.com/56807047/229285528-6820413a-aa46-4a73-8a36-732f331da4e3.png)
Screenshot  DX11 mode  ![DX11](https://user-images.githubusercontent.com/56807047/229285521-c02e7976-ac3f-47c5-beb6-a7e33c9231c9.png) - open GL vulkan and DX12 same issiue

### PCSX2 Revision

v1.7.4309

### Operating System

Windows 10 (64bit)

### CPU

I5 10400f / AMD r7 2700x

### GPU

RTX 3070ti

### Logs & Dumps

[3318282_context.txt](https://github.com/PCSX2/pcsx2/files/11129311/3318282_context.txt)
![3318282_f20329_itex_02c24_P_8_11_00_00_00_00](https://user-images.githubusercontent.com/56807047/229286190-356b207b-162c-4e31-945c-f8f8b4db48e3.png)
[3318282_vertex.txt](https://github.com/PCSX2/pcsx2/files/11129312/3318282_vertex.txt)

**Comment by JordanTheToaster** [comment]
Game looks fine here speed is just down to your hardware.

**Comment by husitko** [comment]
i reset defaults and SW is stabilazed to 60fps but original texture glitching are still there  ... is there possible to add something like choose render method for specific games? or maybe add upscale to SW mode?

**Comment by JordanTheToaster** [comment]
I'm going to suggest you delete any per game settings you have and reset your settings to default as the game works fine.

![image](https://user-images.githubusercontent.com/80843560/229287725-8b5e5417-b506-4dae-ab92-18cc01908d42.png)

**Comment by husitko** [comment]
try to go to that spot in doors to pool room as on my screenshot BCS only some textures and spikes traps does that shit to me

**Comment by husitko** [comment]
here is video : https://www.youtube.com/watch?v=zPDOHD93zJc 
me showing all settings wich are 99% default and just runing game to that spot but on SW is ok

**Comment by refractionpcsx2** [comment]
We don't support piracy.
![image](https://user-images.githubusercontent.com/6278726/229320072-ebe4fedb-799b-4502-a637-4db7ebf25e86.png)

**Comment by husitko** [comment]
why u close a issiue? bcs i had a lot of bioses? i was trying other bioses cause i was like maybe bios is corupted ... 
i found https://wiki.pcsx2.net/Tomb_Raider:_Legend its known bug but its still not fixed ...

**Comment by Miro8419** [comment]
FINALLY FIXED AFTER ALL THESE YEARS! I DID IT! Just add in the file name the right region in brackets, example: Tomb Raider: Anniversary (Europe). And use the correct BIOS for your version. PROBLEM SOLVED!

**Comment by husitko** [comment]
Good job, i switched to Bazzite linux but definitely i will try that hopefully upscaled Lara from my childhood will not glitch this time.

**Comment by Miro8419** [comment]
Please let me know! Tried It on Retroid pocket mini and Odin 2 portal and It worked! Emu: Nethersx2 turnip version.
