### ISSUE TITLE
Dynasty Warriors cutscene issues

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#854]
In Dynasty Warriors 3, the opening cut scenes flicker between the cut scene and the PlayStation 2 Logo at a very fast rate. The rest of the game displays fine, its just the cut scenes

Version - PCSX2 1.3.1-20150925184220
Renderer = DirectX11
All speed hacks on except Cycle Rate Stealing. Defult to fullscreen on open
Description - The opening videos flicker and jump between the video and the playstation 2 logo
How to replicate - Boot game and watch the opening cutscenes directly after the ps2 logo
Last version to work - Unknown
PC Specs - i5 2500k @ 4.0 GHz, 11 GB DDR3 RAM, GTX 660 3GB
Video - https://youtu.be/nECK_k0B2RM

**Comment by bositman** [comment]
Please edit your issue to conform with the guidelines.
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by deadair3210** [comment]
Fixed

**Comment by pgert** [comment]
Finding the "Last version to work" isn't that difficult (if there ever were any).
You have the GitHub archive here:
http://buildbot.orphis.net/pcsx2/index.php?m=fulllist
 and if that doesn't work, try with the older GoogleCode archive:
http://buildbot.orphis.net/pcsx2svn/index.php?m=fulllist

**Comment by deadair3210** [comment]
Think I may have found part of the issue with the cut scenes. If you start the cut scene and then trigger GSDx to restart by opening and closing the plugin menu the flashing issue stops. Maybe a buffer issue?

**Comment by deadair3210** [comment]
Tried to find when the last time this worked correctly, went back all the way to 726. Either we never handled this correctly or this is one stubborn bug

**Comment by deadair3210** [comment]
Another game that seems to have this same issue is Baulders Gate: Dark Alliance, same fix works, forced the plugin to restart and the cutscenes played fine

**Comment by willkuer** [comment]
What happens if you press F9 twice?

**Comment by deadair3210** [comment]
It works! Switching to software mode and back to hardware mode fixes the cutscenes. Thought it was causing the emulator to crash, but it was just me not giving the plugin time to recover from switching modes before telling it to switch again.

**Comment by deadair3210** [comment]
Could this issue be related somehow, as the same fix fixes the issue
https://github.com/PCSX2/pcsx2/issues/855

**Comment by pgert** [comment]
Tested the lasted build, and "Baldur's Gate: Dark Alliance"
 does not have the problem you desribe with me.

**Comment by deadair3210** [comment]
Video of my issue, Baulders Gate doesnt have part of other games in the garbage graphics, but acts close to the same way as the others and is fixed the same way
https://www.youtube.com/watch?v=r8sWqHfK1KI&feature=youtu.be

**Comment by pgert** [comment]
Why do you have this clip Private?
I'm not signing up for YouTube.

**Comment by deadair3210** [comment]
sorry meant to hit unlisted instead of privite, should work with this link
https://www.youtube.com/watch?v=r8sWqHfK1KI

**Comment by pgert** [comment]
No problem like in your clip for me.
Can't give you any suggestons, sorry.

**Comment by deadair3210** [comment]
Ok, I have a feeling that its caused by the same problem thats causing the Dynasty Warriors issue, but it could just be my computer

**Comment by deadair3210** [comment]
Another game that has this issue is Front Mission 3, fixed by toggling software mode

**Comment by gregory38** [comment]
Normally it must be fine in latest git.
