### ISSUE TITLE
[BUG]: HDD problem 

### ISSUE THREAD

**Issue by Dantedevil10** [PCSX2/pcsx2#8540]
### Describe the Bug

I try all i can but the problem not resolve,is my pc?

### Reproduction Steps

ㅤ

### Expected Behavior

https://user-images.githubusercontent.com/125316907/229308514-c0d95e24-2aef-4fce-a4bf-6b1148b5a736.mp4

### PCSX2 Revision

v1.7.4307

### Operating System

Windows 10 (64bit)

### CPU

i3-7100u

### GPU

intel hd 620

**Comment by Mrlinkwii** [comment]
can you be a bit more specific  , if thats ok?

**Comment by Dantedevil10** [comment]
that stuttering in the game

**Comment by RedDevilus** [comment]
Are you using any USB Externally storage (HDD/SSD)?

**Comment by Dantedevil10** [comment]
no ,is my internal HDD

**Comment by RedDevilus** [comment]
I think this is better done in the Discord server, GitHub issues is for emulator issues itself, not for hardware being finnicky with the emulator, it's too vague on the information provided which is the case.

**Comment by Dantedevil10** [comment]
ok sorry ,close this issue

**Comment by RedDevilus** [comment]
I'll re-open when it's a valid issue.
