### ISSUE TITLE
[BUG]: Incorrect graphical display in Gran Turismo 4 with 16:9 aspect ratio in-game screen mode enabled

### ISSUE THREAD

**Issue by DanielBielak** [PCSX2/pcsx2#8543]
### Describe the Bug

In Gran Turismo, when 16:9 aspect ration screen mode is enabled in the game (with each in-game "Video Output" mode: "Standard," "Progressive (480p)," and "HDTV (1080i)"), the driving mode screen displays improperly. This started happening with recent versions of PCSX2 (today or within the past day). It didn't happen earlier. The driving mode previously displayed properly with in-game Video Output mode "HDTV (1080i)" and in-game Aspect Ratio mode "16:9" enabled.

### Reproduction Steps

- Run Gran Turismo 4 with PCSX2.
- Select "Gran Turismo mode."
- Select "Home"
- Select "Options"
- Select "Screen"
- For "Aspect Ration" setting, select "16:9"
- Exit "Screen Settings"
- Exit "Options"
- Exit "Home"
- Select "City Courses"
- Select "Seoul Central"
- Select "Practice"
- Select "A-Spec=Driver's mode"

### Expected Behavior

The screen display should not be divided into a top half and a bottom half. The screen display should display should be unified and full.

### PCSX2 Revision

v1.7.4315

### Operating System

macOS 10.14 (Mojave)

### CPU

2.2 GHz Intel Core i7

### GPU

Intel Iris Pro 1536 MB

### GS Settings

Internal Resolution: 2x Native (~720p)

### Emulation Settings

Internal Resolution: 2x Native (~720p)

### GS Window Screenshots

<img width="1049" alt="Screen Shot 2023-04-01 at 7 40 03 PM" src="https://user-images.githubusercontent.com/101737437/229323424-48ae3a36-0020-4889-b3c5-7a976919b77c.png">
<img width="1049" alt="Screen Shot 2023-04-01 at 7 58 42 PM" src="https://user-images.githubusercontent.com/101737437/229323425-dd3ce467-a397-4ba1-a8c0-0e2c6f39f4f1.png">

**Comment by refractionpcsx2** [comment]
does this only happen in Metal? we are dealing with a couple of metal issues right now.

**Comment by DanielBielak** [comment]
Yes, it only happens in Metal. It doesn't happen in Vulkan or Software.

**Comment by refractionpcsx2** [comment]
If you could provide a GS Dump that would be good, that could be used to fix it.

**Comment by DanielBielak** [comment]
How do I do a GS Dump?

**Comment by DanielBielak** [comment]
In Tools menu item: "Save Single Frame GS Dump"?

**Comment by RedDevilus** [comment]
Yes,

```
How To Create A GS Dump
What is a GS dump?
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

Where do I make the dump?
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

How do I make the dump?
Stable 1.6.0 and Nightly 1.7 wxWidgets:
Use the key combination Shift + F8

Nightly 1.7 Qt:
Tools > Save Single Frame GS Dump

Where does the GS dump save to?
GS dumps are saved to the /snaps folder.
- If you used the PCSX2 installer, you will find it in Documents/PCSX2.
- If you are using a nightly build, you will find it next to the PCSX2 executable.

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump
```

**Comment by DanielBielak** [comment]
[Archive.zip](https://github.com/PCSX2/pcsx2/files/11130880/Archive.zip)

**Comment by DanielBielak** [comment]
I included in the ZIP file "Archive.zip" a .gs.zst file and a .png file. Is that what you need?

**Comment by RedDevilus** [comment]
That's what we need so thanks.

**Comment by DanielBielak** [comment]
Okay. Thank you.
