### ISSUE TITLE
[Feature Request]: FMV Replacement

### ISSUE THREAD

**Issue by alexankitty** [PCSX2/pcsx2#8545]
### Description

I know this is a bit of a longshot to ask for, but seeing as we have texture replacement I figured it wouldn't hurt to at least put it on the radar.  
Here's what my vision of this would look like, though I'm not completely familiar with this codebase so I apologize if some things are wrong.  
1. Remove the FMV dump option from the texture replacements field, I don't think this is useful in practice, at least in terms of replacements.
2. Add an option instead for FMV MP4 Replacements (or other codecs/containers, but I feel MP4 might be the best choice.)

Under the hood I would expect it to look something like this.
* Game makes a call to start playback of an FMV
* PCSX2 can already intercept these calls to adjust the widescreen aspect ratio.
* With FMV replacement enabled, once the FMV call is received, have PCSX2 disable the graphics renderer and audio, and begin playback of an MP4 in an FMV overrides folder that matches the Filename of the movie it's trying to play. (E.G game calls for P3CT001_01.SFD, PCSX2 finds P3CT001_01.MP4, disables the renderer while letting the engine continue going in the background and displays the specified movie instead.)
* Once the game calls an exit to FMV playback mode, PCSX2 then will stop playback of the movie, and re-enable the graphics renderer and audio.

### Reason

* How will it make things easier for you?
* It will make things easier by providing an easier method to replacing a game's FMVs with higher quality ones.

* How does this feature help your enjoyment of the emulator?
* This will help by allowing us to bypass the 6.8mbps limit on mpeg2 playback, and allow for less crunchy/compressed looking FMVs so that games can look their best.

* What does it provide that isn't being provided currently?
* It provides a means for having an actual functional FMV replacement system instead of the existing FMV texture dump that doesn't look good with on-the-fly replacements

### Examples

Currently I don't have an example of how this would look. The idea would be to effectively make PCSX2 act like a video player while the virtual PS2 is in FMV mode.

**Comment by refractionpcsx2** [comment]
This really isn't feasible, we don't detect what video it's playing at all, nor do we have any way to detect it which is clean, you're talking a lot of gross crap to try and catch the filename, something which we might not even be able to do.

So I'm gonna say a big fat no to this one.

**Comment by alexankitty** [comment]
Figured I'd try, thanks.

**Comment by refractionpcsx2** [comment]
Sorry, good idea, but not really feasible.
