### ISSUE TITLE
GSDX not clearing buffers correctly when switching games

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#855]
Version - PCSX2 1.3.1-20150925184220
Specs - i5 2500k @ 4.0 GHz, 11 GB DDR3, GTX 660 3GB, Windows 10 Pro x64
Details - If a game is played and then the game is later switched and Boot(Full) is run or the reset button is pushed in the swap discs dialog, GSDX does not correctly clear the buffers before preceding with booting the game.
Procedure - Play game, Switch to a different game, if the game is programmed to expect the buffers to be empty, you will see parts of the game you were playing before you switched to the new game.
![gsdx d3d11 hw _ 640x448 _ auto _ interlaced field _ limiter_ normal _ speed_ 100 59 70 _ ee_ 42 _ gs_ 9 _ vu_ 0 _ ui_ 0 _ state 0 9_28_2015 10_49_45 am](https://cloud.githubusercontent.com/assets/1053504/10141540/b248e122-65d2-11e5-9eed-035dded89666.png)
I belive this might be related to a issue that Kingdom Hearts has had for a while in that parts of the menu can be seen in the black areas of the cutscenes.
![gsdx d3d11 hw _ 640x448 _ auto _ interlaced field _ limiter_ normal _ speed_ 100 59 94 _ ee_ 37 _ gs_ 4 _ vu_ 0 _ ui_ 0 _ state 0 9_28_2015 11_22_53 am](https://cloud.githubusercontent.com/assets/1053504/10141642/4ab7d97c-65d3-11e5-8a7c-0f413cf35d5d.png)

**Comment by yorkiesandskittles** [comment]
Might #563 be related?

**Comment by deadair3210** [comment]
Maybe the caching issue is related, but i dont think the other problems are related to this

**Comment by gregory38** [comment]
related to #768

**Comment by gregory38** [comment]
For the record there are a combo of issues.
1/ RT aren't cleared
2/ better RT must contains real GS data
3/ potential texture cache issue.

**Comment by deadair3210** [comment]
Aah Ok

**Comment by gregory38** [comment]
A potential explanation of the bug could be found in #1222

**Comment by gregory38** [comment]
Could you test latest git.

**Comment by lightningterror** [comment]
@deadair3210 status ?

**Comment by vsub** [comment]
I tried the same order and only KH1 was fine
SO3=>TL=>KH1

Tried with the latest beta with the default settings

**Comment by MrCK1** [comment]
FWIW, it happens in other games too such as the screen borders in The Suffering's intro FMV.

**Comment by RedDevilus** [comment]
Interesting to note that the new cache for shaders will process it like this:
First time a FMV runs:
Broken
Second time a FMV runs:
Fixed

But that's only for the same game, the original issue where it retains caches from other games still happens.

Note this is only in cases where the shaders are broken and retaining trash.

**Comment by Mrlinkwii** [comment]
is this still an issue on master?

**Comment by Mrlinkwii** [comment]
its been mentioned that it should be no longer an issue and 'GS and TC gets fully reset, in fact, the whole thing gets torn down if you shut down'
