### ISSUE TITLE
[BUG]: Metal Gear Solid 2 Substance [NTSC-U] Tanker; Artifacting at top of screen.

### ISSUE THREAD

**Issue by TailsGuy** [PCSX2/pcsx2#8553]
### Describe the Bug

There's some artifacting on the top two rows of the screen at the very beginning of the game.
If you've seen something like a Sega Genesis/Mega Drive's overscan area having some pixels on the bottom with the active colors, that's kinda like what's going on here.

There's a lot of rain in the scene, but these two rows are pretty much unmoving.

### Reproduction Steps

Just hop into the game, preferably at native res (it is possible to see this with higher resolutions).

### Expected Behavior

Well, the two rows are supposed to be updating like every other row... You can switch to Software Renderer and see the difference.

### PCSX2 Revision

Nightly 1.7.4320

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5700X (Undervolted, 4850mhz, Pretty stable.)

### GPU

EVGA GeForce RTX 3070 FTW3 Ultra

### GS Settings

![Screenshot 2023-04-02 103015](https://user-images.githubusercontent.com/70661792/229359295-ae4f4ac1-a86e-48bf-bf2c-cd75a2c69958.png)

### Emulation Settings

All default settings

### GS Window Screenshots

![Metal Gear Solid 2 - Substance_SLUS-20554_20230402090521](https://user-images.githubusercontent.com/70661792/229359317-7c173f79-4ff8-4332-b0f7-5a9ccd8c7cc8.png)

### Logs & Dumps

[MGS2 Substance GSDump.zip](https://github.com/PCSX2/pcsx2/files/11132469/MGS2.Substance.GSDump.zip)

**Comment by Mrlinkwii** [comment]
are you upscaling?

**Comment by TailsGuy** [comment]
I am usually, but I like how it looks with native res occasionally, so I switch.
I'm also using a Xinput wrapper with dshidmini so I can use pressure sensitive buttons, by the way.
Don't know if that changes anything graphically, but I hear it was problematic once.

**Comment by TailsGuy** [comment]
Typically at 2K res. I don't have a 1440p monitor, but I put my window screen to 2x and use the quadruple res for super-sampling.
There was an issue in The Spongebob Movie Game where it would have odd dithering problems if your res was higher than your window size, so maybe that's similar.

**Comment by TailsGuy** [comment]
[MGS2 Substance 1440p GSDump.zip](https://github.com/PCSX2/pcsx2/files/11132482/MGS2.Substance.1440p.GSDump.zip)
Here's a dump at 1440p.

**Comment by refractionpcsx2** [comment]
it's possible this is happening, yeah, more noticable with upscaling.

The problem is that we're offsetting the picture as the game would expect for interlacing to be correct, but when you upscale it leaves obvious lines at the top of the screen as it would normally be 1 line, but in 1440p, that becomes 5 lines. If you tick "disable interlace offset" it'll probably go away, but the picture will look clearer.

If that is true if you try it, then this is gonna be a "won't fix" as it's not really something that can be fixed, you just have to crop your picture with the crop options if it upsets you.

**Comment by TailsGuy** [comment]
Ah, that's cool. I mean, it doesn't happen anywhere else in Tanker as far as I'm aware.
