### ISSUE TITLE
[Feature Request]: sortable games list

### ISSUE THREAD

**Issue by tassoman** [PCSX2/pcsx2#8558]
### Description

I can see filtering options for the games list, but I cannot find a sortable order

I would like to sort games for playing time, alphabetical, date added, game's year etc etc...

### Reason

More GUI usability 

### Examples

![immagine](https://user-images.githubusercontent.com/92727/229379142-623439cc-072c-4e56-a159-dcfc8e38b112.png)

For example you can add a dropdown menu: "Sort By" then a checkbox for "desc/asc"

**Comment by refractionpcsx2** [comment]
do you mean the cover view? because you can already sort the list view by play time, name etc... (not game year etc, we don't have that information, and don't plan on adding it)

**Comment by Mrlinkwii** [comment]
You can sort games by play time and region and type etc  already

**Comment by RedDevilus** [comment]
Just click on code or region, which already does descending or ascending alphabetically, numerically or whatever. So it's already implemented.

**Comment by tassoman** [comment]
I think you're pointing at table view, because covers view, have no control about sorting, as seen in the screenshot.  
I didn't tried already but, I bet clicking a column's table header will sort asc/desc the results. :thinking:

**Comment by lightningterror** [comment]
Sorting is already a thing.

**Comment by apennismightier** [comment]
How about sorting alphabetically when in Game Grid view? Seems like something that should be inherently added to begin with.

**Comment by refractionpcsx2** [comment]
> How about sorting alphabetically when in Game Grid view? Seems like something that should be inherently added to begin with.

set it alphabetical in list view, then swap back to game grid, then it'll be sorted alphabetically.

**Comment by tassoman** [comment]
Since happened at least twice, looks like UI/UX factor is not working well.

**Comment by refractionpcsx2** [comment]
What doesn't work? Sorting the list then going to the covers view works fine, and you don't need to redo it every time either.

**Comment by tassoman** [comment]
Technically working well, I agree, but not intuitive for humanity
