### ISSUE TITLE
[BUG]: Midnight Club 3 Dub Edition graphical glitches on Metal Renderer

### ISSUE THREAD

**Issue by thefakesound** [PCSX2/pcsx2#8559]
### Describe the Bug

Whole Screen messed up no matter in menus or in game itself. Changing settings doesn't help. Sometimes most visible area becomes half of the screen, sometimes stays in an upper left part.

### Reproduction Steps

Just run a game on Metal renderer on any settings, any upscaling etc

### Expected Behavior

Expecting to looks normal like it was before few updates

### PCSX2 Revision

1.7.4322

### Operating System

macOS 13 (Ventura)

### CPU

M1

### GPU

M1

### GS Window Screenshots

 
<img width="1440" alt="Screenshot 2023-04-03 at 10 32 29 AM" src="https://user-images.githubusercontent.com/56938252/229442847-a8bb4ed5-98b1-43cc-9e7c-238d1e17e80a.png">
<img width="1440" alt="Screenshot 2023-04-03 at 10 32 42 AM" src="https://user-images.githubusercontent.com/56938252/229442854-cff43652-e5ac-4c8e-91e6-3402675e087b.png">
<img width="1440" alt="Screenshot 2023-04-03 at 10 32 44 AM" src="https://user-images.githubusercontent.com/56938252/229442861-60d404e5-4af6-458f-ac4b-fc4473842280.png">
<img width="1440" alt="Screenshot 2023-04-03 at 10 31 49 AM" src="https://user-images.githubusercontent.com/56938252/229442865-19caa06a-49b4-45e2-ab39-70891cbed3af.png">

### Logs & Dumps
[Midnight Club 3 graphical bug.zip](https://github.com/PCSX2/pcsx2/files/11137921/Midnight.Club.3.graphical.bug.zip)

**Comment by JordanTheToaster** [comment]
It's known.

**Comment by thefakesound** [comment]
> Can I have a gs dump? :)

If I've done right, should be in updated post
