### ISSUE TITLE
[BUG]: something  wrong with "Start FullScreen"

### ISSUE THREAD

**Issue by RogerYe** [PCSX2/pcsx2#8560]
### Describe the Bug

Start game with "Start Fullscreen" on. then press ALT+F4,  pop up a message box "Are you sure you want to ....", and I select "No". After that, I can't return to the game, and PCSX2 lose control.

### Reproduction Steps

The game is: God of War II

### PCSX2 Revision

v1.7.4322

### Operating System

Windows 10 (64bit)

**Comment by RogerYe** [comment]
Sorry for my poor english.
"...... After that, the picture of game disappear, and return to the window with a list of select games(as below),which i can move it, but can't close it (by press ALT+F4), and can't activate any menu item either

![20230404002755](https://user-images.githubusercontent.com/33712470/229570843-92cb7cbf-3f3a-4f05-b82b-b21cb1791323.png)

**Comment by VincenzoLaSpesa** [comment]
If I do the same with the last nightly build, it actually crashes.
I have the dump of it (different game, same issue). 
[crashdump.zip](https://github.com/PCSX2/pcsx2/files/11142616/crashdump.zip)

The repro is:

- Enable Interface->GameDisplay->Start Fullscreen
- Start a game
- As soon as the game starts do Alt+F4
- Answer no to the msgbox
- The game window will close, the window with the game list will appear again.
- The window is frozen, click on it repeatedly, the emulator will crash

I'm running [v1.7.4325](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4325)

**Comment by bigol83** [comment]
Just tested it. It's not just with start fullscreen. Even if you have the game in a windows then double click to make it fullscreen, then press ATL+F4 to stop the virtual machine and answer no to the question, the emulator just crashes.

**Comment by stenzek** [comment]
Fixed in #8548. I'd recommend using the pause menu though (by default bound to escape), rather than ALT+F4, since that won't transition out of fullscreen in the first place.
