### ISSUE TITLE
[BUG]: Dark Cloud 2 - Broken lights in Zelmite Mine

### ISSUE THREAD

**Issue by PixelCrusader** [PCSX2/pcsx2#8562]
### Describe the Bug

The lights in the Zelmite Mine are broken in the hardware renderers. This issue looks to have been active since v1.7.4245. The issue persists in all renderers other than software.

### Reproduction Steps

You'll need a post-game save, as the Zelmite Mine is a bonus dungeon that isn't accessible during the main story. Go to the park in Palm Brinks and look for the mine entrance on the left. Play a stage in the Zelmite mine and look for the lights. The dungeons are randomized, but they aren't ususally hard to find.

Here's a save, if you need it:

https://anonfiles.com/k1d5K0ifzf/Dark_Cloud_2_ps2

### Expected Behavior

For the lights to work properly.

### PCSX2 Revision

v1.7.4324

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900k

### GPU

Nvidia 2080 Super

### GS Settings

All settings are at defaults.

### Emulation Settings

All settings are at defaults.

### GS Window Screenshots

The expected behavior (software mode)

![DarkCloud2Working](https://user-images.githubusercontent.com/40935002/229610086-926c4a95-a747-4111-89db-659779457f3a.png)

The current behavior (hardware mode)

![DarkCloud2Broken](https://user-images.githubusercontent.com/40935002/229610143-a7735b85-a44b-49c1-8957-e36824409d3f.png)

### Logs & Dumps

[Dark Cloud 2_SCUS-97213 Zelmite Mine Broken Lights.zip](https://github.com/PCSX2/pcsx2/files/11142334/Dark.Cloud.2_SCUS-97213.Zelmite.Mine.Broken.Lights.zip)

**Comment by refractionpcsx2** [comment]
I will shortly merge the above linked PR then it'll be fixed. Thanks

**Comment by PixelCrusader** [comment]
Cool. Thanks!
