### ISSUE TITLE
[BUG]: Ultimate Spider-Man - Missing fire effects

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#8569]
### Describe the Bug

Just reached the Goblin fight and the game doesn't render his fire balls, not even in SW mode.

### Reproduction Steps

1. Reach the Goblin fight.
2. Witness the lack of fire effects.

### Expected Behavior

Fire effects should be rendered like in the PS2!

### PCSX2 Revision

v1.7.4322

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GTX 1060 3GB

### GS Window Screenshots

![Goblin](https://user-images.githubusercontent.com/19964653/229885845-50744fe3-3a64-4ec8-bd98-175bb32dcd92.png)

### Logs & Dumps

https://drive.google.com/file/d/1cc4gLrrZK_KxbNa1GvlnzoTSbltkzn2r/view?usp=share_link

**Comment by refractionpcsx2** [comment]
Can you provide a save state please? GS dump isn't much good if the fireball doesn't appear in any mode, it's likely a core issue.

**Comment by ElTioRata** [comment]
https://drive.google.com/file/d/1A3zvQuMizyQiiZD1OSx-ASBI5axLDQ6t/view?usp=share_link

I'd like to add that _sometimes_ the fire effects DO render but for a couple of seconds.

**Comment by Buzzardsoul** [comment]
@ElTioRata Did you try different VU0/VU1 Clamping or Rounding combinations or XGKickHack?

**Comment by refractionpcsx2** [comment]
It'll be fixed in an update in about 20 minutes.

**Comment by jnackmclain** [comment]
Commenting on this as it was the first result I found googling the issue. Im on steam deck Linux using the flatpak version, completely updated, and I see this issue as well. I did notice it is not just the job goblin fight fire effects, but a lot of fire effects. For instance near the beginning of the game with a chase with Rhino, he busts through buildings and in the cutscenes there is fire, but not during gameplay. In a weird thing, as described in the original issue, sometimes it does show the fire for a few seconds. I've notice it seemingly renders if you move the camera and off center hobgoblin.
Tbh im on a plane right now making this issue so I apologize for not having the best report.

**Comment by jnackmclain** [comment]
In a complete aside, I went to the help option to try and verify the build I am currently running on my deck. The help button doesn't appear to show the current build. I'm not sure if I am missing where this is reported within the gui or if this may be an oversight. Wanted to mention as it is possible that I may not be on latest (I am trusting a flatpak updater) (not emudeck)

**Comment by jamekuz** [comment]
Let me start by saying, I understand if you cannot help me. My question is regarding Aethersx2 rather than PCSX2. I am running into this same issue though.

I was hoping you might be able to tell me what combination of clamping and rounding on VU and/or VU1 resolves the issue?

I understand a solution that worked on one emulator has not guarantee to work on another. There just are no other search results on this topic.

**Comment by refractionpcsx2** [comment]
This place is not an Aether support channel.
