### ISSUE TITLE
Graphical Corruption in Jak 2 if video is changed to Progressive Mode

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#857]
Version - PCSX2 1.3.1-20150928094130
Specs - i5 2500k @ 4.0GHz, 11GB DDR3, GTX 660
Description - If progressive mode is enabled through the game options, graphical corruption occurs which persists even if progressive mode is turned off afterwards
Procedure - Start Game, Start at title screen, options, graphics, progressive,turn on progressive mode, corruption occurs.
Video - https://youtu.be/B_MDBGCF_kQ

**Comment by Nobbs66** [comment]
it's not a bug with progressive mode, as it will also occur when loading a savestate that was made in the pause menu

**Comment by gregory38** [comment]
Status?

**Comment by deadair3210** [comment]
As far as i know, it still happens. Will test when i get a chance

**Comment by deadair3210** [comment]
This still happens, sorry I didnt reply. Got busy with another project

**Comment by ssakash** [comment]
can you test the latest development build and check whether the issue still exists ?

**Comment by Nobbs66** [comment]
I'll check in about an hour.

**Comment by Nobbs66** [comment]
Ok, I just tested on 1.4.0 stable, and it still occurs.


Here's the GS dump for it.
https://www.dropbox.com/s/kweoe8ukk9hkg4x/gsdx_20160204135657.7z?dl=0

**Comment by ssakash** [comment]
1.4 doesn't have the latest fix for the progressive mode games, try the latest development build.

**Comment by F0bes** [comment]
The linked GS dump is seemingly fine on the latest dev.
Can someone verify that this is in fact no longer an issue?

**Comment by refractionpcsx2** [comment]
Should be fixed with #8571

the problem was that the GS resets but expects the background information to be there, but before it was stored in a render target, which just got thrown out, meaning it ended up loading garbage from RAM.  But I've added a thing to my PR where it flushes the targets to GS memory when a software reset is done (different from the render switch one I did previously).
