### ISSUE TITLE
[Feature Request]: Individual input controllet settings

### ISSUE THREAD

**Issue by SonGokuuSSJ** [PCSX2/pcsx2#8570]
### Description

It would be great if we could create a custom input settings for each game, because some are better to be controlled with a gamepad, others with a wheel, and....my reason for this request, other games could be controlled with a Light Gun.

### Reason

Other emulators like RPCS3 allow custom input settings. 
It's very usefull and I'd love it for light guns.

### Examples

![image](https://user-images.githubusercontent.com/114095863/229936138-e37cb9c3-0da8-4d9d-8c97-758993f4a2ab.png)

**Comment by MageKing17** [comment]
See that "Input Profile: Shared"? Make a new input profile and change the game's settings to use that input profile.

**Comment by Mrlinkwii** [comment]
theirs per game controller setting already 
![image](https://user-images.githubusercontent.com/17685135/229938009-7bf33985-eef2-4eda-ab0d-2a54221a86b1.png)
do you mean to include USB devices ( light guns etc)?

**Comment by RedPanda4552** [comment]
This is already handled by input profiles. GitHub is not meant for support requests. If you need assistance, please use Discord or the forums.
