### ISSUE TITLE
[BUG]: Sly 3 looks like it's jumping and flickering even with deinterlacing patch

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8578]
### Describe the Bug

The game looks bad with the deinterlacing patch. Even with the patch disabled the automatic deinterlacing setting looks bad as well. I have to force it to Adaptive TFF for it to look right.  

### Reproduction Steps

Just boot the game you should see the flickering and blurriness immediately. 

### Expected Behavior

Should not flicker with deinterlacing the way it is. 

### PCSX2 Revision

Nightly 1.7.4336

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default. Tested with upscaling and native. 

### Emulation Settings

Default

**Comment by Mrlinkwii** [comment]
can i have a gs dump in regards the "Even with the patch disabled the automatic deinterlacing setting looks bad as well"

**Comment by BParks21** [comment]
Yeah sure. Toggling through the different deinterlacing methods using F5 with the patch off fixes it btw. 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/11163378/snaps.zip)

**Comment by Mrlinkwii** [comment]
Looks fine here with default settings, it look like how it would on hardware

**Comment by BParks21** [comment]
You don't see the shaking text right when you boot the game after the fmv opening? It's clearly shaking for me on hw mode at default settings.

**Comment by Mrlinkwii** [comment]
I loaded the first set of gs dumps , I dont have the game

**Comment by BParks21** [comment]
Let me give you another one with text on screen

**Comment by BParks21** [comment]
> I loaded the first set of gs dumps , I dont have the game

Here's another dump. I'm telling you something weird is going on with the deinterlacing for this game. When I hit F5 to cycle through all the deinterlacing modes back to automatic it stops flickering even though I started on automatic. 
[snaps.zip](https://github.com/PCSX2/pcsx2/files/11167555/snaps.zip)

**Comment by refractionpcsx2** [comment]
No problems with flickering here actually running the game, the intro movies have the wrong field order, but once you pass those it's fine.

As for the blur, that's built in to the game, the deinterlacing patches we merged last night disable that.

**Comment by BParks21** [comment]
Hmmm well the hud in the top left is definitely shaking. Like I said when I cycle through the different deinterlacing modes back around to auto it looks better for some reason the shaking is gone. That doesn't really make sense to me. Why would auto start looking bad then look good when going back to it. It should look the same.

**Comment by BParks21** [comment]
Ok everything looks good with the new blur removal added to the deinterlacing patch.
