### ISSUE TITLE
MTVU always defaults to off on Mac

### ISSUE THREAD

**Issue by DigitalMajestic** [PCSX2/pcsx2#8585]
### Describe the Bug

MacOS defaults to MTVU off regardless of how many CPU cores you have. Tested Monterey just now on an i7-9750H (6C/12T), IIRC it’s also broken in Ventura and on M1 based on previous testing.

### Reproduction Steps

Launch emulator with no preexisting config on machine with 4+ cores, or reset all settings to defaults via ini

### Expected Behavior

MTVU should be enabled by default on machines with 4+ cores

### PCSX2 Revision

1.7.4342

### Operating System

macOS 12 (Monterey)

**Comment by CatGreen90** [comment]
Also happening here (mid-2014 MBP on Big Sur with an i7-4870HQ).
