### ISSUE TITLE
[BUG]: Hasbro Family Game Night - Textures are busted

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8589]
### Describe the Bug

![image](https://user-images.githubusercontent.com/8139496/230538186-f6f7bffa-b0c1-45a8-b3a4-683aee5895e5.png)

### Reproduction Steps

The textures are totally messed up in battle ship, and in connect 4 you can't see the textures on the chip either.

### PCSX2 Revision

1.7.4342

### Operating System

Windows 11

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by refractionpcsx2** [comment]
Does this happen in software and hardware modes? do you know if this is a new bug?

**Comment by Meerkov** [comment]
[snaps.zip](https://github.com/PCSX2/pcsx2/files/11179870/snaps.zip)
Here is the GS Dump.

It seems to happen only in Hardware mode. Software mode fixes the issue.

**Comment by refractionpcsx2** [comment]
Looks like Mipmapping + Trilinear is the answer
![image](https://user-images.githubusercontent.com/6278726/230640809-ad6dfc7a-233a-41b4-9cec-cacb48620b73.png)
