### ISSUE TITLE
Coverity analyze

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#859]
@ssakash 
I assign you a couple of coverity issue. Feel free to analyze them and propose some good solutions to improve the situation.

Edit: I opened the issue so you can ask me any question if you need.

**Comment by ssakash** [comment]
@gregory38 

All of those issues are false positives, the intention of the code is correct, Coverity seems to not like the assertion trick for variables. according to coverity the computation for '''branchAddr``` is not done ( but it's false since it will be done after the assertion check, also confirmed it through testing it with few games).

you could silence those coverity warnings by revamping the code to disable the assertion check  (it's useless really, the assertion condition will always be satisfied) , the coverity issues should be fixed with something like this: https://github.com/ssakash/pcsx2/commit/cd58326ec76d824e65e42e8e035765f144c26fec

**Comment by gregory38** [comment]
Behavior is correct but code sucks. For me it isn't a false positive.

It is expected that branchAddr is a single statement macro not several of them. So either it needs a functions macro or it need to be converted to a single statement as you did.

```
 (it's useless really, the assertion condition will always be satisfied) 
```
Care to explain. Otherwise I'm in favor to find a way to keep the assertion. Assertions are really helpful to develop/debug new code.

**Comment by ssakash** [comment]
Unconditional Branching only takes place for lower instruction references and those are the only instances were ```branchAddr``` and ```branchAddrN``` have been used so a upper OP code is pretty much impossible during usage of the macro and the condition will always be true.

**Comment by ssakash** [comment]
I found another good solution preserving both the code quality and the assertions , please take a look: https://github.com/ssakash/pcsx2/commit/eb3483a05eb8ae712794e4a3d528da268787f4fe

what do you think ? @gregory38

**Comment by gregory38** [comment]
Hum, I didn't think about this kind of solution. I'm not sure it is a valid possibility because '?' operator need the same type for both returned value.

It seems macro only took a single parameter. Maybe we could just replace it with a real function.
static inline branchAddrN(const mV); // or const microVU& mVU

@refractionpcsx2 any idea?

**Comment by refractionpcsx2** [comment]
I think a function would probably be better, at least then as well we could try "best guess triage" of the error as we can throw a fail then guess if it should be the next lower op.  Providing nobody buggers up the MicroVU when they are making changes, we should never see that anyway, but at least then it will be receiving something legitimate and avoid a potential crash generating x86 code :P

**Comment by ssakash** [comment]
here's the updated code with respect to @gregory38 and @refractionpcsx2  suggestions. 

https://github.com/PCSX2/pcsx2/commit/09ae83b0a9223ff6a8e6b59e3179bc97d5878cf5

**Comment by refractionpcsx2** [comment]
Looks good to me. Make sure @gregory38 is happy with it then make a PR :)

**Comment by gregory38** [comment]
I'm not sure the macro IsLower is useful. IMHO it makes the code harder to read.

**Comment by refractionpcsx2** [comment]
I dunno if it'll make the code harder to read as such, at least for unknowing people they know what that is checking for now. Although for 2 uses, it wasn't very useful :P

**Comment by gregory38** [comment]
Well I'm fine. I don't know VU code so lower op means nothing for me however I know what is a PC. @ssakash could you do the PR?

**Comment by refractionpcsx2** [comment]
In microVU we do a lot of hopping between previous and future ops and upper and lower positions, that's done to make sure we are in the right position for calculating a branch address, if you calculate a branch address off the upper op, things are not going to go swimmingly.

**Comment by gregory38** [comment]
Hum, I didn't recover enough of the GS crazyness to understand VU stuff ;)

**Comment by refractionpcsx2** [comment]
That's fine, just trust me :P

**Comment by ssakash** [comment]
> @ssakash could you do the PR?

I was just doing some final checks and the patch seems to fine, https://github.com/PCSX2/pcsx2/pull/891

> calculate a branch address off the upper op, things are not going to go swimmingly.

I think you mean the lower op ?

**Comment by refractionpcsx2** [comment]
> I think you mean the lower op ?

if  you calculate off the lower op, you are doing things right.

**Comment by gregory38** [comment]
@ssakash 
In case you didn't notice it, you have others "small" issues assigned.

**Comment by ssakash** [comment]
Ahh, yes. I didn't notice that, I'll take a look on them. :)

**Comment by ssakash** [comment]
@gregory38 

I did some fixes for the assigned coverity issues , please take a look : https://github.com/PCSX2/pcsx2/compare/master...ssakash:coverity_fix

**Comment by ssakash** [comment]
Updated the fixes. https://github.com/PCSX2/pcsx2/compare/master...ssakash:coverity_fix

**Comment by gregory38** [comment]
is the above comment the latest version? The NULL check code feels really wrong.

**Comment by turtleli** [comment]
Yeah, the debugger fix is wrong - the proposed fix doesn't return a value when it's null. And that line doesn't need to be changed.

The correct fix should be done in pcsx2/DebugTools/Breakpoints.cpp.

**Comment by ssakash** [comment]
@turtleli 

agreed, that seemed stupid. no clue what I was thinking doing a null check on the find pointer function itself -_- 

Updated the code: https://github.com/PCSX2/pcsx2/compare/master...ssakash:coverity_fix

**Comment by gregory38** [comment]
Create a PR, it would be easier to discuss the change.

1/ be aware of the indendation
2/ better use a temp variable. Something like that.
```
auto disassembly_window = wxGetApp().GetDisassemblyPtr()
if (disassembly_window)
     disassembly_window->update();
```
3/ keep the "seem useless comment" in GSdx. It is used to separate the important step of the function.
4/ ```if(p->frames > 0 && ttpf != 0)``` can be compressed to  ``` if(p->frames && ttpf)```

**Comment by ssakash** [comment]
@gregory38 

done :+1:   : https://github.com/PCSX2/pcsx2/pull/894

**Comment by ssakash** [comment]
@gregory38 

I still have another issue assigned but I'm not sure of the intent of the code, how should we handle the case if both ``ds`` and ``rt`` are ``NULL`` ? what about the value of `` GSVector2i size`` at the assume scenario ?

**Comment by gregory38** [comment]
Good question. I think there are 2 possibilities
1/ use the previous size of the target (check code just below)
2/ set a 0 size vector

**Comment by ssakash** [comment]
which one of those possibilities would be a good solution ? I'm not sure :p 

``GSVector2i size = rt && ds != NULL ? rt->GetSize() : ds ? ds->GetSize() : GLState::viewport;``

(or)

``GSVector2i size = rt && ds != NULL ? rt->GetSize() : ds ? ds->GetSize() : 0;``

**Comment by gregory38** [comment]
You can choose the first. But I would prefer without the ```&&``` if rt is valid, you take rt size. Else if ds is valid, you take ds size. Otherwise the old value. It is more logical this way.

**Comment by ssakash** [comment]
#899 should fix the last coverity issue. ;)  sorry for separating it into two PR's though :(

**Comment by ssakash** [comment]
@gregory38 

Feel free to assign any more issues if you prefer :)  , I have lots of free time.

**Comment by micove** [comment]
@ssakash 

Well if you have lots of free time you can look into some memory errors that were not found by coverity. I found them in Linux when trying to reproduce #851 which I could never do with any of the reported games in Windows so I tried it in Linux.

It seems gcc-5 unlike previous gcc versions will crash at every single invalid read/write. It seems to take offense to this:
```
	template< typename T > inline
		void xWrite( T val )
	{
		*(T*)x86Ptr = val;  <------ gcc segfault
		x86Ptr += sizeof(T);
	}
```

As shown by the gdb stacktrace:
```
(gdb) bt
#0  0x083eb844 in x86Emitter::xWrite<unsigned short> (val=4111) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/include/x86emitter/internal.h:39
#1  0x083e8ec7 in x86Emitter::xWrite16 (val=4111) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/x86emitter/x86emitter.cpp:82
#2  0x083e5fde in x86Emitter::SimdPrefix (prefix=0 '\000', opcode=16) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/x86emitter/simd.cpp:117
#3  0x083e82c4 in x86Emitter::xOpWrite0F<x86Emitter::xRegisterSSE, x86Emitter::xIndirectVoid> (prefix=0 '\000', opcode=16, param1=..., param2=...)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/include/x86emitter/internal.h:57
#4  0x083e7276 in x86Emitter::xImplSimd_MoveSSE::operator() (this=0x856c0d0 <x86Emitter::xMOVUPS>, to=..., from=...)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/x86emitter/simd.cpp:583
#5  0x08332122 in VifUnpackSSE_Base::xUPK_S_32 (this=0xf2cfec64) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/x86/newVif_UnpackSSE.cpp:94
#6  0x08333130 in VifUnpackSSE_Base::xUnpack (this=0xf2cfec64, upknum=0) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/x86/newVif_UnpackSSE.cpp:347
#7  0x083335b9 in nVifGen (usn=0, mask=0, curCycle=0) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/x86/newVif_UnpackSSE.cpp:408
#8  0x08333760 in VifUnpackSSE_Init () at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/x86/newVif_UnpackSSE.cpp:432
#9  0x0808779f in hwInit () at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/Hw.cpp:40
#10 0x080877da in hwReset () at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/Hw.cpp:56
#11 0x080dd488 in cpuReset () at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/R5900.cpp:82
#12 0x082d87c3 in SysCoreThread::DoCpuReset (this=0xa002ac0 <CoreThread>) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/System/SysCoreThread.cpp:213
#13 0x081dc1bb in AppCoreThread::DoCpuReset (this=0xa002ac0 <CoreThread>) at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/gui/AppCoreThread.cpp:476
#14 0x082d8731 in SysCoreThread::_reset_stuff_as_needed (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/System/SysCoreThread.cpp:195
#15 0x082d8925 in SysCoreThread::StateCheckInThread (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/System/SysCoreThread.cpp:247
#16 0x081dc321 in AppCoreThread::StateCheckInThread (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/gui/AppCoreThread.cpp:536
#17 0x082d898d in SysCoreThread::ExecuteTaskInThread (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/System/SysCoreThread.cpp:269
#18 0x081dc3db in AppCoreThread::ExecuteTaskInThread (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/pcsx2/gui/AppCoreThread.cpp:552
#19 0x083b0ed0 in Threading::pxThread::_try_virtual_invoke (this=0xa002ac0 <CoreThread>, method=&virtual Threading::pxThread::ExecuteTaskInThread())
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/Utilities/ThreadTools.cpp:545
#20 0x083b13b2 in Threading::pxThread::_internal_execute (this=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/Utilities/ThreadTools.cpp:644
#21 0x083b1564 in Threading::pxThread::_internal_callback (itsme=0xa002ac0 <CoreThread>)
    at /build/pcsx2-1.3.1-1282-g5f78644+dfsg/common/src/Utilities/ThreadTools.cpp:684
#22 0xf6d90efb in start_thread (arg=0xf2cffb40) at pthread_create.c:309
#23 0xf6cc866e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

Also valgrind shows
```
==10844== Invalid write of size 2
==10844==    at 0x83EB844: void x86Emitter::xWrite<unsigned short>(unsigned short) (in /usr/games/PCSX2)
==10844==    by 0x83E8EC6: x86Emitter::xWrite16(unsigned short) (in /usr/games/PCSX2)
==10844==    by 0x83E5FDD: x86Emitter::SimdPrefix(unsigned char, unsigned short) (in /usr/games/PCSX2)
==10844==    by 0x83E82C3: void x86Emitter::xOpWrite0F<x86Emitter::xRegisterSSE, x86Emitter::xIndirectVoid>(unsigned char, unsigned short, x86Emitter::xRegisterSSE const&, x86Emitter::xIndirectVoid const&) (in /usr/games/PCSX2)
==10844==    by 0x83E7275: x86Emitter::xImplSimd_MoveSSE::operator()(x86Emitter::xRegisterSSE const&, x86Emitter::xIndirectVoid const&) const (in /usr/games/PCSX2)
==10844==    by 0x8332121: VifUnpackSSE_Base::xUPK_S_32() const (in /usr/games/PCSX2)
==10844==    by 0x833312F: VifUnpackSSE_Base::xUnpack(int) const (in /usr/games/PCSX2)
==10844==    by 0x83335B8: nVifGen(int, int, int) (in /usr/games/PCSX2)
==10844==    by 0x833375F: VifUnpackSSE_Init() (in /usr/games/PCSX2)
==10844==    by 0x808779E: hwInit() (in /usr/games/PCSX2)
==10844==    by 0x80877D9: hwReset() (in /usr/games/PCSX2)
==10844==    by 0x80DD487: cpuReset() (in /usr/games/PCSX2)
==10844==  Address 0x157bb000 is in a --- anonymous segment
==10844== 
==10844== 
==10844== Process terminating with default action of signal 11 (SIGSEGV)
==10844==  General Protection Fault
==10844==    at 0x80F6BC5: void memset_sse_a<(unsigned char)204>(void*, unsigned int) (in /usr/games/PCSX2)
==10844==    by 0x80F3DDD: RecompiledCodeReserve::OnCommittedBlock(void*) (in /usr/games/PCSX2)
==10844==    by 0x83B54C2: BaseVmReserveListener::CommitBlocks(unsigned int, unsigned int) (in /usr/games/PCSX2)
==10844==    by 0x80F3DB7: RecompiledCodeReserve::DoCommitAndProtect(unsigned int) (in /usr/games/PCSX2)
==10844==    by 0x83B56B9: BaseVmReserveListener::OnPageFaultEvent(PageFaultInfo const&, bool&) (in /usr/games/PCSX2)
==10844==    by 0x80F9D89: EventListenerHelper_PageFault<BaseVmReserveListener>::OnPageFaultEvent(PageFaultInfo const&, bool&) (in /usr/games/PCSX2)
==10844==    by 0x80B51C3: IEventListener_PageFault::DispatchEvent(PageFaultInfo const&, bool&) (in /usr/games/PCSX2)
==10844==    by 0x83B46B9: SrcType_PageFault::_DispatchRaw(std::_List_iterator<IEventListener_PageFault*>, std::_List_iterator<IEventListener_PageFault*> const&, PageFaultInfo const&) (in /usr/games/PCSX2)
==10844==    by 0x83B64E4: EventSource<IEventListener_PageFault>::Dispatch(PageFaultInfo const&) (in /usr/games/PCSX2)
==10844==    by 0x83B4686: SrcType_PageFault::Dispatch(PageFaultInfo const&) (in /usr/games/PCSX2)
==10844==    by 0x83A0676: SysPageFaultSignalFilter(int, siginfo_t*, void*) (in /usr/games/PCSX2)
==10844==    by 0x5276CCF: ??? (in /lib/i386-linux-gnu/i686/cmov/libpthread-2.19.so)
```

Every single call to xWrite is resulting in an invalid write of 1,2, or 4 bytes that matches the calling xwrite8, xwrite16 and xwrite32. 

It only crashes when run under a debugger and trying to load an iso. I don't really have time to look at it right now.

**Comment by gregory38** [comment]
It is done on purpose. Memory is mapped without access so every acces trigger a sigsegv signal. There is a dedicated handler that will reallocate the page. It is done to do
1/ lazy allocation (might be useless on linux)
2/ (I guess so not sure) detect self modyfing code

On coverity. I will look but Ref and I need to "fix" the register allocator. (Responsible of 50% of coverity reports).

**Comment by refractionpcsx2** [comment]
Yeah we need to go through putting drop back to interpreter instructions :(

**Comment by gregory38** [comment]
@micove you seems to imply that it was working/different with older GCC4?
I think some part of the recompiler isn't 100% compliant with i386/gcc ABI (stack alignment). Maybe gcc5 updates its behavior.

**Comment by micove** [comment]
Well, It looked like the previous gcc5 only crash in which code generated with the new libstdc++ ABI resulted in invalid memory writes/read that caused a crash. I compiled it in a jessie chroot so it picked up gcc 4.9.2 and it still crashes but I'm still using sid libraries. Since you are still in jessie you could see if running it as "gdb PCSX2" and trying to run a game throws a SIGSEGV. It happens instantly so it only takes a few seconds to see.

**Comment by gregory38** [comment]
```
[Switching to Thread 0xf2e5db40 (LWP 20444)]
0x083a61b6 in x86Emitter::xWrite<unsigned short> (val=4111) at /home/gregory/playstation/emulateur/pcsx2_merge/common/include/x86emitter/internal.h:39
39                      *(T*)x86Ptr = val;
(gdb) bt
#0  0x083a61b6 in x86Emitter::xWrite<unsigned short> (val=4111) at /home/gregory/playstation/emulateur/pcsx2_merge/common/include/x86emitter/internal.h:39
#1  0x083a3adf in x86Emitter::xWrite16 (val=4111) at /home/gregory/playstation/emulateur/pcsx2_merge/common/src/x86emitter/x86emitter.cpp:82
#2  0x083a15f7 in x86Emitter::SimdPrefix (prefix=0 '\000', opcode=16) at /home/gregory/playstation/emulateur/pcsx2_merge/common/src/x86emitter/simd.cpp:117
```

Just step by step. And you will see that it will call SysPageFaultSignalFilter to handle the SIGSEGV.
```
Source_PageFault->Dispatch( PageFaultInfo( (uptr)siginfo->si_addr & ~m_pagemask ) );  
// resumes execution right where we left off (re-executes instruction 
if (Source_PageFault->WasHandled()) return;    
```

Useful GDB command:
```
handle SIGSEGV noprint 
handle SIGSEGV nostop 
```

**Comment by micove** [comment]
Oh, yeah. I did not know about the memory being protected thing and the use of a signal handler. If it's normal then yeah configuring gdb to ignore the signals does it. Anyway, I will create a PR for some Linux warnings as a payback for wasting your time with this.

**Comment by refractionpcsx2** [comment]
Windows debugging will need fixing at some point as well as that complains.  Fortunately once you've clicked ignore a couple of times it goes away, but still annoying :P

**Comment by micove** [comment]
I thought the Windows one was fixed a couple of weeks ago by backporting some wx3.0 stuff. The linux one would probably need to be documented somewhere but then I realize that probably no one is going to read it anyway.

**Comment by refractionpcsx2** [comment]
I was trying to do some debugging the other day and it was freaking out every time the emu started

**Comment by micove** [comment]
Oh, I just tried it and it looks like the same exact issue I was having on Linux
```
*(T*)x86Ptr = val;
```
giving an access violation exception. Since apparently this is by design then you can go to 

Exception Settings -> Win32 Exceptions -> Untick 0xc0000005  Access violation.

Which is equivalent to unticking the "Break when this exception type is thrown" checkbox.

**Comment by refractionpcsx2** [comment]
Hmm I'll take a look next time I'm coding :)

**Comment by gregory38** [comment]
OoO PCSX2 is also a debugger PITA in windows too. Be aware that it will also disable real SIGSEGV, normally on linux it tries to raise a SIGTRAP (but it's only work for the EE thread)
You could find doc on wiki/dev post. Search Jake related entries on the virtual memory stuff.

Win is limited to 2GB but we have 4GB on linux. Maybe we could use a real EE buffer, it would cost extra 60MB worst case. But I don't know how exactly the protection of code is done (for the self mofying part).

**Comment by gregory38** [comment]
@ssakash I assigned you several reports. There are all about missing of the init in the constructor
1/ Either it just miss an init
2/ Or the member is completely useless
Do a single commit for each fixes. It will be easier to review.

**Comment by gregory38** [comment]
And test the compilation of each commits.

**Comment by gregory38** [comment]
Remaining coverity reports are minors. Postponed for later.
