### ISSUE TITLE
[BUG]: Adjusting OSD text scaling while running a game causes crash.

### ISSUE THREAD

**Issue by NadoPS** [PCSX2/pcsx2#8591]
### Describe the Bug

If you adjust OSD text scaling percentages with the up/down buttons on the right while having a game running the emulator crashes.

### Reproduction Steps

Run a game. Open global settings - graphics - OSD and adjust text scaling with the up/down button on the right.

### Expected Behavior

The emulator should update OSD text scaling in real time and not crash.

### PCSX2 Revision

v1.7.4344

### Operating System

Windows 10 (64bit)

**Comment by kamfretoz** [comment]
Can confirm and reproduce

**Comment by NadoPS** [comment]
Crash dumps.
[pcsx2-windows-64bit-Qt.zip](https://github.com/PCSX2/pcsx2/files/11176616/pcsx2-windows-64bit-Qt.zip)

**Comment by Berylskid** [comment]
> ### Reproduction Steps
> Run a game. Open global settings - graphics - OSD and adjust text scaling ___with the up/down button__ on the right.

It occurs even by using mouse wheel or up/down key.

**Comment by NadoPS** [comment]
Addition: Software and Vulkan crashes. Other renderers don't crash immediately but still might have other issues.

**Comment by kamfretoz** [comment]
Regression from 4338

**Comment by NadoPS** [comment]
No crashing in v1.7.4337.

**Comment by kamfretoz** [comment]
Some interesting observation:

- The crash is only occur when using Vulkan renderer
- When changing OSD Scale in OpenGL, it doesn't crash but the OSD itself glitches out (switching in and out of fullscreen fixes it)
![Screenshot_20230407_155508](https://user-images.githubusercontent.com/14798312/230584895-8e372626-583a-4a0b-8a2d-be3e43063beb.png)

**Comment by kamfretoz** [comment]
Here is the backtrace taken from Linux's AppImage Build:
```
*************** Unhandled SIGSEGV at 0xaa390c ***************
0x00000000f0449f CrashSignalHandler [../common/CrashHandler.cpp:358]
0x00000000f1af34 CallExistingSignalHandler [../common/Linux/LnxHostSys.cpp:69]
0x00000000f1af34 SysPageFaultSignalFilter [../common/Linux/LnxHostSys.cpp:126]
0x007f83cec51f4f
0x00000000aa390c GetView [../common/Vulkan/Texture.h:52]
0x00000000aa390c ApplyUtilityState [../pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp:3353]
0x00000000aa19e0 RenderImGui [../pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp:2356]
0x00000000aa19e0 EndPresent [../pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp:473]
0x00000000a4e006 EndPresentFrame [../pcsx2/GS/Renderers/Common/GSRenderer.cpp:526]
0x00000000a4e006 VSync [../pcsx2/GS/Renderers/Common/GSRenderer.cpp:631]
0x00000000a56392 VSync [../pcsx2/GS/Renderers/HW/GSRendererHW.cpp:153]
0x000000009c2c74 GSvsync [../pcsx2/GS/GS.cpp:517]
0x000000007e42b5 MainLoop [../pcsx2/MTGS.cpp:471]
0x000000007e42b5 ThreadEntryPoint [../pcsx2/MTGS.cpp:151]
0x007f83ce2d72c2 execute_native_thread_routine [/usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82]
0x007f83cec9ebb4
0x007f83ced20d8f
0xffffffffffffffff
*******************************************************************
fish: Job 1, 'QT_QPA_PLATFORM=xcb ./PCSX2.App…' terminated by signal SIGABRT (Abort)
```

As you might have noticed, the backtrace output is exactly the same as the one from #8594 
I feel like this is the exact same bug but manifested differently.

**Comment by stenzek** [comment]
Thanks, I'll sort this out tomorrow
