### ISSUE TITLE
[BUG]: Starting a game with Software and start fullscreen set as per-game settings froze the emulator

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#8592]
### Describe the Bug

If you attempt to start a game with SW renderer and start fullscreen set as per-game settings, the emulator would completely froze after passing through the BIOS and you have to use Task Manager to kill it

### Reproduction Steps

1. Pick any game you want to use and go to it's per-game settings
2. Enable Start Fullscreen and set the Renderer to Software
3. Launch the game and wait until it went through the BIOS
4. The emulator will become unresponsive

Here is the reproduction video:
https://cdn.discordapp.com/attachments/923492653788692480/1093781732697833492/2023-04-07_13-16-48.mp4

### Expected Behavior

The game starts normally without freezing

### PCSX2 Revision

v1.7.4344

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

**Comment by kamfretoz** [comment]
Also regression from v1.7.4338

**Comment by stenzek** [comment]
Can you check if #8605 fixes it? It seems fine on Windows, but I also couldn't reproduce the original crash, had to use a combination of different global renderer and fullscreen UI.
