### ISSUE TITLE
[BUG]: Emulator crashing after "PlayStation 2" logo with Vulkan renderer

### ISSUE THREAD

**Issue by Z0LiGamer** [PCSX2/pcsx2#8596]
### Describe the Bug

I've tried to run GTA: LCS and Mafia 1 with the Vulkan renderer after updating, but the emulator hangs, and then closes right after the boot sequence. Tried a fresh build, with the same results. The last version that worked for me was v1.7.4334. 

[crash-2023-04-07-18-11-56-535.txt](https://github.com/PCSX2/pcsx2/files/11180153/crash-2023-04-07-18-11-56-535.txt)

### Reproduction Steps

Change renderer to Vulkan.

### Expected Behavior

Emulator not crashing, and the game starting successfully.

### PCSX2 Revision

v1.7.4344

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
can you zip up the .dmp crash file as well and upload that please, the text file isn't much use to us alone.

**Comment by Z0LiGamer** [comment]
[pcsx2-v1.7.4344-windows-64bit-Qt.zip](https://github.com/PCSX2/pcsx2/files/11180288/pcsx2-v1.7.4344-windows-64bit-Qt.zip)

**Comment by refractionpcsx2** [comment]
thanks, one moment.

**Comment by refractionpcsx2** [comment]
Hmm, the crash dump doesn't really tell me a whole lot, except it's crashing in your intel graphics driver. Do you have a proper GPU?

**Comment by Z0LiGamer** [comment]
I have an integrated Intel UHD 620 on this PC

**Comment by refractionpcsx2** [comment]
Then you probably shouldn't be using vulkan on that, the drivers are pretty broken, you should be using DX11 really.
