### ISSUE TITLE
[BUG]: Radiata stuff randomly missing like character models, weapons, effects etc.

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8601]
### Describe the Bug

In battle a character performs a special attack called a votly attack, a short sequence begins with a dramatic scene. During this sequence character models, weapons the name of the attack across the screen or effects in the background can randomly be missing. It's usually only one of these things at a time. Seems to be most easily reproducible in the first battle in the game with Ridley. I've 2 gs dumps. One of Ridley's axe missing and the other of the effect in the background behind Ridley missing.  

### Reproduction Steps

Load the save state and proceed to the battle and survive until ridley performs her votly. It's random whether or not something will be missing. Usually at least one thing is missing. 

### Expected Behavior

No missing objects or character models or even 2d stuff like the name of the attack should be missing. 

### PCSX2 Revision

v1.7.4348

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default. HW mode.

### Emulation Settings

default. 

### GS Window Screenshots

![Radiata Stories_SLUS-21262_20230406011227](https://user-images.githubusercontent.com/12180630/230681377-418c6c8c-4932-42ac-8430-1812012c55b4.png)

This second screenshot is of the effect in the background behind Ridley missing, the purpose of this screenshot is not to compare to the first. It's to show that something different was missing this run.
![Radiata Stories_SLUS-21262_20230407170016](https://user-images.githubusercontent.com/12180630/230681378-aa71c122-9619-4730-9e09-f7a720275a36.png)

### Logs & Dumps

[Missing Stuff GS.zip](https://github.com/PCSX2/pcsx2/files/11181667/Missing.Stuff.GS.zip)

Save State:
[State.zip](https://github.com/PCSX2/pcsx2/files/11181675/State.zip)

**Comment by Mrlinkwii** [comment]
can this be re-checked for me :)

**Comment by BParks21** [comment]
Sure sorry for the late reply. It's pretty difficult to produce. I'll get back to you as soon as I have some time to test it again.

**Comment by BParks21** [comment]
@Mrlinkwii Yeah I'm still seeing missing effects like the background effect behind Ridley during the sequence.

**Comment by 2KRN4U** [comment]
It seems that the models are still there, however the models coordinates seem to get messed up.
https://streamable.com/mbuxra

**Comment by 2KRN4U** [comment]
I believe setting EE Clamping to Extra + Preserve Sign fixes this. 

I did 100 volty blasts with EE Clamping set to Normal and had the issue 8 times. I did another 100 volty blasts on extra + sign and I did not get the issue a single time.

**Comment by BParks21** [comment]
> I believe setting EE Clamping to Extra + Preserve Sign fixes this.
> 
> I did 100 volty blasts with EE Clamping set to Normal and had the issue 8 times. I did another 100 volty blasts on extra + sign and I did not get the issue a single time.

That can cause issues in other areas of the game though right?

**Comment by 2KRN4U** [comment]
> That can cause issues in other areas of the game though right?

Would have to test and see if it causes any issues. 
I think this would also fix the bug where the game would sometimes softlock when teleporting with the Journey Pig statues.

**Comment by BParks21** [comment]
Didn't know that was an issue.
