### ISSUE TITLE
[BUG]: God of War 2 dark chests

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8602]
### Describe the Bug

When using Progressive scan mode in HW mode chests appear dark, missing shading or something. I would provide a state but the bug doesn't occur when loading one. I noticed when progressive scan is activated there is a brief flash of garbage. Maybe related to Radiata issue?

### Reproduction Steps

Turn on progressive scan mode and get to a chest in the game, or load the GS dump. 

### Expected Behavior

Chest should not be dark. 

### PCSX2 Revision

v1.7.4348

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default HW

### Emulation Settings

Default

### GS Window Screenshots

![God of War II_SCUS-97481_20230407060553](https://user-images.githubusercontent.com/12180630/230682090-5b0c24dc-339c-4ccd-999c-bfd5e6860ea2.png)

### Logs & Dumps

[GoW 2 GS.zip](https://github.com/PCSX2/pcsx2/files/11181691/GoW.2.GS.zip)

**Comment by Mrlinkwii** [comment]
are you using no-interlace patches ?

**Comment by BParks21** [comment]
> are you using no-interlace patches ?

No, not for this game. Besides there isn't one for this game to my knowledge at least. I don't see why one would even exists if the game natively supports progressive scan mode.

**Comment by Buzzardsoul** [comment]
> Turn on progressive scan mode and get to a chest in the game, or load the GS dump.
The gs dump is fine
![image](https://user-images.githubusercontent.com/126727903/230736112-c01b410a-fa9d-4025-a327-4a76b223f399.png)

**Comment by BParks21** [comment]
Yeah I don't het why but save states and gs dumps for some reason are not showing the issue. You might wanna try just playing from my actual save
 I'll upload my memory card folder.

**Comment by BParks21** [comment]
Tested Nvidia Driver 531.41 (latest) issue persists. You have to get there from a standard save with progressive mode on.

**Comment by Buzzardsoul** [comment]
@BParks21 Does it also occur on 1.6?

**Comment by BParks21** [comment]
> @BParks21 Does it also occur on 1.6?

Not sure, when I get a chance I'll test it.

**Comment by refractionpcsx2** [comment]
Looks like the regression happened in #8123

This is not to say there is a bug with update, it could have just been masking the problem, but that is where the black chests began.

**Comment by BParks21** [comment]
Oh yeah the foot QTE lol

**Comment by refractionpcsx2** [comment]
And the door!

**Comment by BParks21** [comment]
> And the door!

Forgot about the door.

**Comment by stenzek** [comment]
Game has a C24 target at FBP 0 which it uses for... something (probably post-processing, I didn't bother looking). GS reset clears all registers, including the drawing environment, which sets the FRAME PSM to CT24. Then it draws whatever it is, leaving the PSM as 32, which means PCSX2 tries to load texture data from this render target instead of from local memory.

The PR above does fix it, but it needs hardware testing to indeed confirm this is the behaviour.
