### ISSUE TITLE
Second Sight fails to boot correctly

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#861]
Version - PCSX2 1.3.1-20150928094130
Specs - i5 2500k @ 4.0GHz, 11GB DDR3, GTX 660 3GB
Description - Second Sight(NTSC) fails to make it to the title screen or opening to the game. Game stalls directly after Playstation 2 Logo.
Procedure - Load Second Sight, Boot(Full),After the Playstation 2 Logo the game will sit at a black screen
Log - https://gist.github.com/deadair3210/2fec40218d5123b404b4

**Comment by prafullpcsx2** [comment]
Game works just fine for me. Try redumping your iso.

**Comment by refractionpcsx2** [comment]
Ok as it's confirmed to be working for others, i think this is a support issue, please continue any further correspondence on forums.pcsx2.net
