### ISSUE TITLE
[BUG]: Logitech Momo Racing wheel works incorrectly with current USB implementation in Gran Turismo 4

### ISSUE THREAD

**Issue by Resident007** [PCSX2/pcsx2#8612]
### Describe the Bug

When trying to play Gran Turismo 4 (any version, but I'm using Online Public Test (SCUS-97436), there are two major issues when it comes to using Logitech Momo Racing steering wheel:

1. Force Feedback does not work under any circumstances. Normally, the wheel should re-calibrate itself (turn all the way right, all the way left and center itself) when starting the game, which does not happen on Qt builds. I tried all wheel options (Driving Force, both Driving Force Pro versions and GT Force, connecting my wheel through both SDL and DInput), and the behavior does not change.
2. Calibration of the wheel seems to go off-center at some point when driving, after which we have to turn the wheel all the way left and all the way right to fix it.

Neither of the issues can be seen on WxWidgets build v1.7.3727 which is the last build to include old USB implementation:
![image](https://user-images.githubusercontent.com/25570319/230722812-22d1af01-84f8-4f05-9705-8745bc0b7e06.png)
And this one seems to work much better with this wheel. Force Feedback works, and calibration hasn't gone off-center at all after a couple of days of playing the game (wheel is emulated as Driving Force). The drivers for wheel are up-to-date and it works fine in other PC games.

### Reproduction Steps

1. Start latest Qt build and configure it.
2. Launch Gran Turismo 4 and try to go into any race with Logitech Momo Racing connected.
3. Check if Force Feedback works and if inputs get miscalibrated (presumably, after quickly rotating the wheel).

### Expected Behavior

Force Feedback works like in build v1.7.3727 WxWidgets and calibration does not randomly go bad (maybe we can have an option to use old USB implementation instead of the new one for better compatibility?)

### PCSX2 Revision

v1.7.4352

### Operating System

Windows 11

**Comment by KubKonstantin** [comment]
I have the same problem except one difference that I'm using emu on windows 10 22h2. Calibration works fine on wxwidgets versions with old USB plugin. When I'm trying to use my steering wheel in Qt version wheel disconnects appears and calibration doesn't work fine. 
Two ways as I see to resolve this problem in future builds for developers:
1) To get old USB plugin back and add option to choose whitch plugin to use
2) Recompile new USB plugin using old one as example how to work with steering devices

**Comment by Mrlinkwii** [comment]
@KubKonstantin  plugins are dead and never coming back  , if you want plugin use 1.6 :)

**Comment by KubKonstantin** [comment]
@Mrlinkwii I just want fine work of USB in next builds like it was in WxWidgets

**Comment by Resident007** [comment]
> @KubKonstantin plugins are dead and never coming back , if you want plugin use 1.6 :)

I think @KubKonstantin meant the old USB implementation, and the problem lies within the current USB implementation because the old one works fine despite the fact it was not an actual plugin. Version 1.7.3727 already does not have plugin systems as far as I'm aware, judging by lack of Plugins settings.
![image](https://user-images.githubusercontent.com/25570319/230724071-3a398bfe-b29d-4a1c-a1be-7c5b385ea65f.png)

**Comment by Resident007** [comment]
By the way, I found a PR that broke compatibility with Logitech Momo Racing wheel: https://github.com/PCSX2/pcsx2/pull/7534

**Comment by CookiePLMonster** [comment]
You found the PR that re-introduced USB to Qt under a new implementation so... it's not that surprising.

**Comment by stenzek** [comment]
You probably didn't bind FFB.

Regardless, if it doesn't work, none of the developers nor tested have wheels, so nothing can be done about it even if there is an issue. The old code was disgusting and unmaintainable, and had to go.

**Comment by Resident007** [comment]
> 

I did bind the FFB using both SDL and DInput, none of them work. So, the support for this wheel (which is pretty popular by the way) will just remain broken?

**Comment by stenzek** [comment]
Force feedback is only supported with SDL, not DInput.

> So, the support for this wheel (which is pretty popular by the way) will just remain broken?

It was tested by a couple of users prior to being merged, and worked fine.

Like I said, none of us have this hardware, so we can't do anything about it. You're welcome to debug what the issue is, fix it, and submit a pull request. But otherwise, no, nothing will change.
