### ISSUE TITLE
PAL Suikoden V lines in FMVs and main menu when upscaling

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#8619]
### Describe the Bug

There has been a regression with some of the latest builds. Now, Suikoden V PAL has lines dividing the fmvs and a side rainbow line. Also, white line in menu at 50 HZ. 

When choosing 50 HZ, the game has more noticeable graphical issues
When choosing 60 HZ, there is some corruption when changing modes, in main menu and a side line in ingame FMV. 

The emulator nightly i'm using is 1.7.4359

### Reproduction Steps

Start the game at resolution higher than Native, choose 50 HZ to see several graphical issues in fmvs and main menu or choose 60 HZ and notice some corruption when changing modes and right side line garbage in ingame FMV and main menu. 

### Expected Behavior

No graphical corruptions. 

### PCSX2 Revision

pcsx2 1.7.4359

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### GS Window Screenshots

50 HZ

![Suikoden V_SLES-54087_20230409130612](https://user-images.githubusercontent.com/38129260/230769032-2afef8fc-ef02-4769-8f8a-178207472fb9.png)
![Suikoden V_SLES-54087_20230409130633](https://user-images.githubusercontent.com/38129260/230769042-23788c7c-2c47-4e08-adf6-66c9f8ea2dbb.png)

![Suikoden V_SLES-54087_20230409130710](https://user-images.githubusercontent.com/38129260/230769046-f1ba92d2-44e7-4253-a977-8d445eaf111e.png)

60 HZ

![Suikoden V_SLES-54087_20230409133735](https://user-images.githubusercontent.com/38129260/230770395-535b3127-8805-4ee8-b017-41339450613d.png)
![Suikoden V_SLES-54087_20230409133634](https://user-images.githubusercontent.com/38129260/230770396-dbfdd19c-cce7-4f59-8e3f-679a05d31911.png)
![Suikoden V_SLES-54087_20230409133657](https://user-images.githubusercontent.com/38129260/230770398-5bbf673f-c381-40dc-8c43-8f3b9fbd396f.png)

### Logs & Dumps

50 HZ dumps
[suikoden V.zip](https://github.com/PCSX2/pcsx2/files/11185276/suikoden.V.zip)

60 HZ dumps
[suikoden V 60 hz.zip](https://github.com/PCSX2/pcsx2/files/11185326/suikoden.V.60.hz.zip)

**Comment by Mrlinkwii** [comment]
![image](https://user-images.githubusercontent.com/17685135/230770822-bad2f1e0-f0fc-4e3b-9788-fd094eebe9b4.png)
![image](https://user-images.githubusercontent.com/17685135/230770856-ccb1e49b-24aa-4d5d-bf19-81a9d2a89bd9.png)


works fine here with the gs dumps on v1.7.4359 :S

**Comment by bigol83** [comment]
I noticed the fps are 60 fps, so you tried the 60 HZ dumps. Have you tried the 50 HZ dumps?

**Comment by JordanTheToaster** [comment]
50hz dumps look correct and the line only appears when upscaling at native the FMVs look correct.

**Comment by stenzek** [comment]
- We do **not** accept issues relating to **upscaling** at this time
  - We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling
  - Please try your game at native resolution before creating an issue
  - If your bug is the result of upscaling please use the forums or discord for assistance with various upscaling workarounds.
  - Additionally, the unofficial PCSX2 [Wiki](https://wiki.pcsx2.net/Main_Page) often lists various fixes for upscaling issues

**Comment by bigol83** [comment]
Yeah, it's mostly an upscaling regression. It didn't use to have that line on FMVs before. 

@stenzek This one

https://user-images.githubusercontent.com/38129260/230770396-dbfdd19c-cce7-4f59-8e3f-679a05d31911.png

Happens at native too, when trying to switch to 60 hz mode.

**Comment by JordanTheToaster** [comment]
Please use the Discord or Forums so someone can help you there.
