### ISSUE TITLE
Emulator crashes when the Browse button is hit to pick a ISO

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#862]
Version - PCSX2 1.3.1-20150928094130
Specs - i5 2500k @ 4.0GHz, 11GB DDR3, GTX 660 3GB, Windows 10 Pro
Description - Sometimes, when the browse button is pushed to select a ISO, the emulator will just close, without any notice as to why. Possibly failing to open the Browse dialog?
Procedure - Open emulator, try to browse for a iso, emulator has a chance of crashing

**Comment by ssakash** [comment]
I can't reproduce this issue, is this a regression ? Please provide more steps in order to reproduce the issue successfully. any probability factor ?

**Comment by deadair3210** [comment]
No other steps are needed for the problem to manifest on my computer though I now think its a problem with my Windows install. Closing. Thanks anyway.
