### ISSUE TITLE
[BUG]: Missing FFMPEG

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8624]
### Describe the Bug

1) Download the nightly build of PCSX2.
2) Try to turn on Video Capture

![image](https://user-images.githubusercontent.com/8139496/230789947-2cc3e380-1e0d-433a-9aee-412be0314fd9.png)

### Reproduction Steps

see above

### Expected Behavior

I expected the video capture to work

### PCSX2 Revision

1.7.4342

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
Not a bug, intentional, you can get the DLL's from https://www.duckstation.org/upload/ffmpeg-dlls.zip

**Comment by Meerkov** [comment]
Can you add a link to this issue in that error message, so that other folks can see how to fix it more easily?

**Comment by refractionpcsx2** [comment]
This is only really a temporary measure, we need to decide how best to distribute these.

**Comment by SpiralofAnts** [comment]
this could just be a me issue, but the duckstation download seems to be down

**Comment by refractionpcsx2** [comment]
This isn't the Duckstation github.
