### ISSUE TITLE
[BUG]: All-Star Baseball 2004 - Opening Video Resolution Too Small

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8625]
### Describe the Bug

At the beginning of All-Star Baseball 2004 (and the other games in the same series) there is an opening video scene in the first few seconds.

Music can be heard, however the screen only shows a tiny image in the top left corner. I circled it in red.
![image](https://user-images.githubusercontent.com/8139496/230790115-06ccbc61-578f-48e9-a5cf-fb3e0efb9f5a.png)

### Reproduction Steps

1) Start All-Star Baseball 2004
2) Wait until "All Star" begins to play. 
3) Look at the top left corner and see the video file is not playing correctly.

I attached a GS dump of a second or two. I hope that helps.

4) Change to Software Rendering instead of Vulkan.
5) Reset the game
6) Notice that this time, you will see a Dolby logo, and the video files are playing correctly.

### PCSX2 Revision

1.7.4342

### Operating System

Windows 11

### CPU

i9-9900k

### GPU

RTX 3060

### Logs & Dumps

[All-Star Baseball 2004_SLUS-20569.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11186075/All-Star.Baseball.2004_SLUS-20569.gs.zst.zip)

**Comment by Buzzardsoul** [comment]
Target partial invalidation seems to fix it on my end

**Comment by RP32WEC** [comment]
With an older version setting the FMV hack to software fixed it for me but since recent updates only the background video will show or the menu text not both.

**Comment by RP32WEC** [comment]
Issue seems to be fixed as of build v1.7.4427 with the Software FMV game fix.

![Untitled-2](https://user-images.githubusercontent.com/94249324/234756378-26933201-06a0-4aa4-bb40-1d9b02d68e0f.jpg)
![Untitled-4](https://user-images.githubusercontent.com/94249324/234756385-b59b3f16-3716-4ceb-b91b-0f8c2bdf629f.jpg)

**Comment by Mrlinkwii** [comment]
as of v1.7.4919 m seems fixed withe the gs dump 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/b2815e4c-a8c8-41b7-959f-e80ea9fc760c)

idk how it is playing the game
