### ISSUE TITLE
[BUG]: Double free when using PCAP Bridged network with "any" Ethernet Device

### ISSUE THREAD

**Issue by 6e6f61** [PCSX2/pcsx2#8627]
### Describe the Bug

When starting a (network-enabled) game in PCSX2 with Ethernet enabled and set to "PCAP Bridged" with "any" Ethernet device, a double free occurs that leads to an emulator crash.

I'll note I'm using NixOS, and created a wrapper around PCSX2 that executes PCSX2 with additional capabilities necessary to use PCAP.

    security.wrappers.pcsx2 = {
      source = "${pkgs.pcsx2}/bin/pcsx2";
      capabilities = "CAP_NET_RAW+eip CAP_NET_ADMIN+eip";
      owner = ...;
      group = ...;
      permissions = "u+rx,g+x";
    };

Specifically selecting a network interface won't trigger this bug.
Logs:

    Could not get MAC address for adapter: any
    DEV9: Opening adapter 'any'...
    DEV9: Device uses DLT 113: LINUX_SLL
    ERROR: Unsupported DataLink Type (113): LINUX_SLL
    DEV9: Can't open Device 'any'
    free(): double free detected in tcache 2
    Aborted (core dumped)

The double free warning only appears sometimes - I'm not sure if that's because it isn't the cause of the crash, or something else.

### Reproduction Steps

1. Enable Ethernet
2. Set Ethernet Device Type to PCAP Bridged
3. Set Ethernet Device to any

### Expected Behavior

I presume "any" means "the first valid device", so PCSX2 should identify the first valid network device and use it.

### PCSX2 Revision

1.7.0-0

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

NixOS

**Comment by stenzek** [comment]
We don't support third-party packages. Unless you get a backtrace (which the appimage does print out on crash), there's nothing we can do.

**Comment by 6e6f61** [comment]
Got it. I might poke around again in the future, but I'm happy to presume this is Nix' fault.
