### ISSUE TITLE
[BUG]: Dokapon Kingdom Freeze after tutorial

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8629]
### Describe the Bug

The game freezes but the music continues.

### Reproduction Steps

1) Play Story mode
2) After completing the tutorial area, chapter 1 starts
3) The game freezes on your turn

### PCSX2 Revision

1.7.4342

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by Mrlinkwii** [comment]
game works here , i suspect either bad settings or a bad dump

**Comment by stenzek** [comment]
Likely a bad dump, please compare the hash of your ISO against redump.org. If it doesn't match, dump the game again from disc.

**Comment by Meerkov** [comment]
My hash looks right. SHA1:
> e3c15563d83f227f2cec886317b92cec65343441

**Comment by Mrlinkwii** [comment]
@Meerkov  join the discord  or the  forums for help
