### ISSUE TITLE
[BUG]: Difficult to Enable Video Recording on Game Start

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8630]
### Describe the Bug

It's difficult to get video recording mode to work correctly when starting a game. Often it breaks the emulator and makes it unusable without force quitting.

### Reproduction Steps

1) drag and drop a .bin onto the emulator
2) immediately press ESC to pause the game
3) Go to Tools> Video Recording
4) Begin a recording

Notice:
The filename *may not* include the game title if you didn't wait long enough (bug)

Notice:
If the game does have a title, but the status bar does not yet show "Vulkan", then the emulator will be frozen. You cannot shut the game down nor reset it. You must force quit the emulator and try again.

### Expected Behavior

If the video rendering system is not yet active, then it should start recording once the video renderer is available.

Otherwise, you need to time it very precisely to make sure you can start the recording as close to power-on as possible.

### PCSX2 Revision

1.7.4342

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
The pause menu gets the game from the same source as the window title, so it doesn't "know what game it is" before the ELF loads. I'm guessing OP is referring to the filename being displayed.

**Comment by refractionpcsx2** [comment]
yes, I know what they mean :P If you pause it and enable video recording, you get the BIOS CRC and the date, so I guess maybe not?

**Comment by stenzek** [comment]
We can query it early, but the best solution would probably be to automatically start recording after the game sets the video mode, since the ELF will definitely be loaded then. Yeah, you won't get the boot animation in the capture, but it's going to kill recording when the game switches from whatever mode the BIOS was in anyway...

**Comment by Mrlinkwii** [comment]
Can this be rechecked on latest nightly?

**Comment by JordanTheToaster** [comment]
Appears to be fine on current master the file names correctly.
