### ISSUE TITLE
[BUG]: Devil May Cry 3 - The shotgun's shrapnel is missing in the OPENGL renderer when upscaling

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#8634]
### Describe the Bug

When you use Dante's shotgun on the OPENGL renderer, the shrapnel effect is missing if you are upscaling, but isn't missing on other renderers when upscaling.

### Reproduction Steps

Just use my gs dump on the OPENGL renderer
[Devil May Cry 3 - Dante's Awakening [Special Edition]_SLUS-21361_20230410162251.gs.zip](https://github.com/PCSX2/pcsx2/files/11190748/Devil.May.Cry.3.-.Dante.s.Awakening.Special.Edition._SLUS-21361_20230410162251.gs.zip)

### Expected Behavior

Look at the other renderers and compare them to OPENGL

Direct3D 12:
![image](https://user-images.githubusercontent.com/126727903/230910498-ec3a4cc7-9d2c-4c0a-9fe3-84f6b546da66.png)

OPENGL:
![opengl](https://user-images.githubusercontent.com/126727903/230911451-5636bf9a-1661-48f3-b429-b6c821122324.PNG)

### PCSX2 Revision

1.7.4354

### Operating System

Windows 11

### CPU

i7-7800x

### GPU

GTX 1060 TI

**Comment by Mrlinkwii** [comment]
seems to be working here on opengl 
![image](https://user-images.githubusercontent.com/17685135/230911817-d89e249f-152d-49bf-8568-e5262d889da0.png)

**Comment by Buzzardsoul** [comment]
> seems to be working here on opengl ![image](https://user-images.githubusercontent.com/17685135/230911817-d89e249f-152d-49bf-8568-e5262d889da0.png)

Then I will close it as cannot reproduce. But I will mention that it is very weird, likely my gpu's fault. Anyways, thanks for testing.

**Comment by Buzzardsoul** [comment]
Update: It seems that it was because I was 2x upscaling. I didn't know that because I use custom settings for this game and I had forgotten that. My bad. But... it could be an issue since other renderers are ok with upscaling but opengl isn't. But I will leave it at that.

**Comment by Buzzardsoul** [comment]
Was fixed.
