### ISSUE TITLE
[BUG]: Nothing is been installed

### ISSUE THREAD

**Issue by hillwoodroc** [PCSX2/pcsx2#8635]
### Describe the Bug

I try to build pcsx2 1.7.4359 from source on openSUSE Tumbleweed. Compile successfully but nothing is installed. I use open build server to do this work, the open build server creates a empty package.

### Reproduction Steps

Build pcsx2 by the rpm spec
[pcsx2.tar.gz](https://github.com/PCSX2/pcsx2/files/11190885/pcsx2.tar.gz)

### PCSX2 Revision

1.7.4359

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

openSUSE Tumbleweed

**Comment by Mrlinkwii** [comment]
Can you try the appimage , self builds and the appimage are only supported

**Comment by hillwoodroc** [comment]
Thanks, but we need a openSUSE release package. I maintain this package on openSUSE.

**Comment by lightningterror** [comment]
If the appimage is fine then this isn't an issue.
