### ISSUE TITLE
[BUG]: Fatal Frame1 stops at last boss match

### ISSUE THREAD

**Issue by Newtypeman** [PCSX2/pcsx2#8636]
### Describe the Bug

Fatal Frame1 stops at last boss match

### Reproduction Steps

In the last boss match, the game randomly stops when the camera is lifted. It's the Korean version.
Is there a solution?

### PCSX2 Revision

v1.7.4366

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5600

### GPU

RTX 2060S

**Comment by Mrlinkwii** [comment]
this maybe the same as #5781 , if it is it happens on real hardware

**Comment by weirdbeardgame** [comment]
Aww shit, I didn't have the korean version to fix it. Lemme double back and see if there's any other versions I'm missing

**Comment by Newtypeman** [comment]
> Aww shit, I didn't have the korean version to fix it. Lemme double back and see if there's any other versions I'm missing



> Aww shit, I didn't have the korean version to fix it. Lemme double back and see if there's any other versions I'm missing

Thank you.

**Comment by refractionpcsx2** [comment]
I'll close this as it is a bug with real hardware, but I expect weirdbeard will submit a patch at some point soon.

**Comment by weirdbeardgame** [comment]
Btw, Newtypeman. If you have a discord. Can you come to the pcsx2 server and ping weirdbeardgame?
