### ISSUE TITLE
[BUG]: Texture replacement 

### ISSUE THREAD

**Issue by ESPPIRAL** [PCSX2/pcsx2#8640]
### Describe the Bug

While loading custom textures they don't render correctly instead they even look worse than the original ones despite being higer resolution/fidelity.

This is how it should look

Letft original textures- Right replacement textures (before the bug?)

![vlcsnap-2022-03-07-23h29m07s478](https://user-images.githubusercontent.com/29869781/231143561-682f58d9-5e1b-4ffb-969a-6266bade2716.png)

And this how it now looks, it seems like the textures has been downsampled to the original resolution

![PaRappa the Rapper 2_SCUS-97167_20230411131126](https://user-images.githubusercontent.com/29869781/231143918-78f9adea-b2c0-4804-9102-7b4297fd5c46.png)

### Reproduction Steps

Enable loading custom textures.

### PCSX2 Revision

v1.74370

### Operating System

Windows 10 (64bit)

### CPU

i5490

### GPU

r9 380x

**Comment by Mrlinkwii** [comment]
are you you sure , your on v1.74370 ,because those images of pcsx2  dont look like QT

**Comment by ESPPIRAL** [comment]
Yes
![image](https://user-images.githubusercontent.com/29869781/231146635-b4712910-be48-49ea-919f-0ec21d1a5a75.png)

The first image is from an old build that used to work correctly same as an old build of QT.

**Comment by ESPPIRAL** [comment]
Nope I didn't, and I have said they used to work perfectly.

**Comment by JordanTheToaster** [comment]
They game using mipmapping so I'd suggest you do that.

**Comment by ESPPIRAL** [comment]
They game won't dump any mip map.

**Comment by Pandavenom** [comment]
This is not a mipmap bug, this is something else. Many games have this problem since the last few update. Like Blood Will Tell, Sakura Wars, etc. I tried every settings, mipmaps, but nothing helps. 

W/O HD texture
![Blood Will Tell - Tezuka Osamu's Dororo_SLES-52755_20230319165641](https://user-images.githubusercontent.com/130554210/231423116-4e46efb9-5ab7-4b17-9962-eef97744820c.jpg)

With HD texture
![Blood Will Tell - Tezuka Osamu's Dororo_SLES-52755_20230319165626](https://user-images.githubusercontent.com/130554210/231423367-81611354-9385-4f08-b2aa-c96999ccfa3a.jpg)

**Comment by refractionpcsx2** [comment]
He didn't mean the mipmap setting, does the HD Texture pack come with the mipmaps also dumped? because if not, it's going to do weird stuff like that.

**Comment by Pandavenom** [comment]
Yes, with or without mipmaps the textures are bad. :(

![TOTALCMD64_LwPJ8phS9z](https://user-images.githubusercontent.com/130554210/231434334-bb0bfc5c-a08f-48ff-9660-ec629bbe4ff2.jpg)

![Blood Will Tell - Tezuka Osamu's Dororo_SLES-52755_20230412123453](https://user-images.githubusercontent.com/130554210/231434613-49635ceb-3a43-4d27-ac55-0aa8ed9f1501.jpg)

**Comment by refractionpcsx2** [comment]
okay it might be a bug then, thanks for checking.

**Comment by stenzek** [comment]
I'll need a single frame GS dump and **one** of the textures which causes issues (don't post a pack here).

**Comment by Pandavenom** [comment]
I hope this will help
[Blood Will Tell - Tezuka Osamu's Dororo_SLES-52755_20230415102627.zip](https://github.com/PCSX2/pcsx2/files/11238863/Blood.Will.Tell.-.Tezuka.Osamu.s.Dororo_SLES-52755_20230415102627.zip)

**Comment by stenzek** [comment]
Not sure if this would've been working "before", but shader sampling was getting used instead of hardware sampling, which is why it looked like arse.. linked PR above should hopefully sort out all these cases.

**Comment by Fuckay** [comment]
I got a simple solution, you could try turning off mipmapping, it worked for me, the texture got replaced
