### ISSUE TITLE
[BUG]: Crashed when save and load state

### ISSUE THREAD

**Issue by icefire112233** [PCSX2/pcsx2#8641]
### Describe the Bug

When trying to save state and load state using the latest nightly (v1.7.4371) version, the application crashed.

Reproducible on: SLPM-66690 (232C7D72), SLPM-66058(AEA1B3AD)

[crash-2023-04-12-00-12-09-724.txt](https://github.com/PCSX2/pcsx2/files/11202685/crash-2023-04-12-00-12-09-724.txt)
[crash-2023-04-12-00-12-09-726.zip](https://github.com/PCSX2/pcsx2/files/11202688/crash-2023-04-12-00-12-09-726.zip)

### Reproduction Steps

As above

### PCSX2 Revision

v1.7.4371

### Operating System

Windows 10 (64bit)

**Comment by cabaalexander** [comment]
I Agree, this happened on this last update 😢
