### ISSUE TITLE
[BUG]: Final Fantasy X-2 entering sub menus leads to graphical distortion

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8643]
### Describe the Bug

When you press triangle to enter the menu entering a sub menu like config causes a graphical bug to flash on the screen when entering and exiting the menu. 

### Reproduction Steps

Press triangle, then enter a sub menu like config, finally back out of the menu entirely. 

### Expected Behavior

No graphical junk when entering and exiting the menu. Should look like sw mode. 

### PCSX2 Revision

v1.7.4372

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default, tested native res and highest blending option. Also tested other renderers. 

### Emulation Settings

Default

### GS Window Screenshots

![Final Fantasy X-2_SLUS-20672_20230408003144](https://user-images.githubusercontent.com/12180630/231325812-5db73819-9aa1-4f2b-8ad3-cdc71dae9da5.png)

### Logs & Dumps

[Final Fantasy X-2 gs.zip](https://github.com/PCSX2/pcsx2/files/11206279/Final.Fantasy.X-2.gs.zip)

**Comment by BParks21** [comment]
> Cannot reproduce here.

Did you try without the gs dump? Maybe it's one of those.

**Comment by JordanTheToaster** [comment]
> > Cannot reproduce here.
> 
> Did you try without the gs dump? Maybe it's one of those.

I'm trying in game it seems to happen rarely for me most of the time it seems fine here.

**Comment by BParks21** [comment]
Hmm I can produce it every time I go to config and backing all the way out of the menu pressing circle.

**Comment by JordanTheToaster** [comment]
> Hmm I can produce it every time I go to config and backing all the way out of the menu pressing circle. You did produce it though just to clarify?

Yes I did just couldn't get it to happen frequently for me.

**Comment by BParks21** [comment]
Are you in a different are of the game? Maybe different locations have different results somehow?

**Comment by JordanTheToaster** [comment]
> Are you in a different are of the game? Maybe different locations have different results somehow?

Just at the very start after the first fight either way it's fine just wait on someone to have a look.

**Comment by JordanTheToaster** [comment]
Regression from #8289

**Comment by refractionpcsx2** [comment]
You're breaking my balls Jordan :(
