### ISSUE TITLE
[BUG]: Final Fantasy X-2 flying enemies die falling upward instead of to the ground.

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8644]
### Describe the Bug

When in battle killing a flying enemy results in their death animation to fall upward or rise. On real hardware they fall to the ground which makes sense. 

### Reproduction Steps

Get into a battle and kill some flying enemies early in the game. 

### Expected Behavior

Flying enemies should die falling to the ground. 

Real Hardware, watch at 1:38 https://www.youtube.com/watch?v=q_v0xVo7stI&list=LL&index=18

### PCSX2 Revision

1.7.4372

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

Save State:
[SLUS-20672 (48FE0C71).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/11206327/SLUS-20672.48FE0C71.01.p2s.zip)

**Comment by Buzzardsoul** [comment]
Try different Fpu rounding/clamping settings or fixes. Or better yet, turn off enable ee recompiler

**Comment by JordanTheToaster** [comment]
> Try different Fpu rounding/clamping settings or fixes. Or better yet, turn off enable ee recompiler

That won't help.

**Comment by Goatman13** [comment]
> That won't help.

Full EE clamping fix it for me.

**Comment by BParks21** [comment]
> > That won't help.
> 
> Full EE clamping fix it for me.

Thats good to hear. I wonder if it has any negative side effects?
