### ISSUE TITLE
[BUG]: Psychonauts distortion on right half of the screen in certain areas

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8645]
### Describe the Bug

There's this weird after image or distorted ghosting on right side of the screen in this area of the game. Not sure if it occurs in other areas but I imagine it does at some point. 

### Reproduction Steps

I guess get to this area of the game or load the state or gs dump.

### Expected Behavior

No distortion 

### PCSX2 Revision

v1.7.4372

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Default, looks fine in sw.

### Emulation Settings

default

### GS Window Screenshots

![Psychonauts_SLUS-21120_20230411204431](https://user-images.githubusercontent.com/12180630/231346037-66432db3-2d91-4648-8274-0052d86fcefe.png)

### Logs & Dumps

GS dump:
[snaps.zip](https://github.com/PCSX2/pcsx2/files/11206995/snaps.zip)

State:
[SLUS-21120 (2373FD16).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/11206997/SLUS-21120.2373FD16.01.p2s.zip)

**Comment by Buzzardsoul** [comment]
Cannot be reproduced by gs dumps on my end. But, I wonder if #8606 caused it

**Comment by refractionpcsx2** [comment]
Can reproduce it with the savestate
![image](https://user-images.githubusercontent.com/6278726/231445859-e76970a1-5cb6-46fd-82c1-22038190cb6f.png)

**Comment by refractionpcsx2** [comment]
[Psychonauts_SLUS-21120_20230412125111.gs.zip](https://github.com/PCSX2/pcsx2/files/11211008/Psychonauts_SLUS-21120_20230412125111.gs.zip)

Here's a multiframe dump which shows the error, which is good cos we just bumped the savestate version so regression testing would have been impossible :P

**Comment by prafullpcsx2** [comment]
This has been an ever present bug with pcsx2 hw mode. Tested it extensively few months ago.

**Comment by refractionpcsx2** [comment]
![alt text](https://media.discordapp.net/attachments/514592552389967881/794972454769917972/pcsx2treasuregob2.gif)

**Comment by BParks21** [comment]
> ![pcsx2treasuregob2](https://user-images.githubusercontent.com/6278726/231453047-3bbd91b8-f9d0-44e0-adb6-63308c7d5b8e.gif) [ ![pcsx2treasuregob2](https://user-images.githubusercontent.com/6278726/231453047-3bbd91b8-f9d0-44e0-adb6-63308c7d5b8e.gif) ](https://user-images.githubusercontent.com/6278726/231453047-3bbd91b8-f9d0-44e0-adb6-63308c7d5b8e.gif) [ ](https://user-images.githubusercontent.com/6278726/231453047-3bbd91b8-f9d0-44e0-adb6-63308c7d5b8e.gif)

That's me sorry lol
