### ISSUE TITLE
Texture flickering in Suikoden V PAL

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#8649]
### Describe the Bug

Playing Suikoden V in several situations there is lots of texture flickering. I managed to catch this one, but there are several others even more noticeable. 

This happens in software mode, too. Actually software renderer has worse flickering than hardware renderer at native resolution. 

### Reproduction Steps

Just play the game, you will notice many flickering issues, on characters textures, on walls, etc.

### Expected Behavior

No flickering. 

### PCSX2 Revision

pcsx2 1.7.4373

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### GS Window Screenshots

The issue is clearly visible into this screenshot circled in black. 
![Suikoden V_SLES-54087_20230412235206](https://user-images.githubusercontent.com/38129260/231597414-9de243da-91d0-4dd0-bd3c-08d895860496.png)

Medium camera screenshot
![Suikoden V_SLES-54087_20230417124138](https://user-images.githubusercontent.com/38129260/232465934-ca284b99-d6e7-42c8-a69b-d194a9c4ad10.png)

Low camera screenshot
![Suikoden V_SLES-54087_20230417124206](https://user-images.githubusercontent.com/38129260/232466006-9dfacf50-917a-4712-94a6-54e26db2da6c.png)

### Logs & Dumps

Sorry if this is a dump into a 7z archive, then added to zip file, but i had to use multiframe gsdump to show the issue and the size was always bigger than 25 MB. 

[Suikoden V.zip](https://github.com/PCSX2/pcsx2/files/11216437/Suikoden.V.zip)

Medium camera gsdump
[Suikoden V medium camera.zip](https://github.com/PCSX2/pcsx2/files/11249372/Suikoden.V.medium.camera.zip)

Low camera gsdump
[Suikoden V low camera.zip](https://github.com/PCSX2/pcsx2/files/11249382/Suikoden.V.low.camera.zip)

**Comment by refractionpcsx2** [comment]
Probably Z fighting, not much we can do about it for now.

**Comment by refractionpcsx2** [comment]
This looks like Z fighting, interesting that it's worse in software, usually it's the opposite. I'd be curious to see this on a real PS2.

**Comment by bigol83** [comment]
Added two more screenshots and gsdumps from other cameras. Suikoden V has three camera distances: default one is high camera, then there is the medium camera and low camera. You can switch between them pressing R1.

The three cameras have somewhat different levels of flickering: high camera has the highest flickering, medium camera has lower texture flickering and with low camera flickering is there but it's highly reduced. 

Wanted to add more details, so that it can be easier to analyze the issue.

**Comment by Mrlinkwii** [comment]
really ? :confused:  @trostboot

**Comment by trostboot** [comment]
Really. I no longer have a capture card usable on a modern system, but if you really want to, I suppose I could take a picture from the TV.

**Comment by refractionpcsx2** [comment]
If the real hardware is the same as PCSX2 then I'm going to mark this as such and close, as there's no point in us chasing a problem which exists on real hardware.
