### ISSUE TITLE
[BUG]: PS2 Linux won't start.

### ISSUE THREAD

**Issue by ChrisNonyminus** [PCSX2/pcsx2#8656]
### Describe the Bug

When running the official Linux for PlayStation 2 discs, installing or booting Linux won't work. After swapping to Disc 2 in the Runtime Environment screen and back to Disc 1, the screen fades to black, and the fades back in saying "PS2 Linux cannot be started."
![image](https://user-images.githubusercontent.com/50080567/231799470-7f5b1558-63ab-42ab-bfa3-ffbe4af3fe63.png)

### Reproduction Steps

Load PS2 Linux Runtime Environment disc (Disc 1).
Choose "Install" or "Boot".
Change Disc to Disc 2 (Software Packages) when prompted.
Change back to Disc 1 when prompted.

### PCSX2 Revision

v1.7.4378

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint

### CPU

i7-8700k

### GPU

RTX 3060 12GB

### Emulation Settings

HDD enabled, usb keyboard enabled.

**Comment by Mrlinkwii** [comment]
Known issue , I believe it's to do with needing full tlb emulation but could be wrong

**Comment by stenzek** [comment]
Well out of scope for now. I have a branch with full TLB emulation that's a work in progress, but it still craps itself once it gets into userspace. If you want to debug what's going on and contribute to it, the code is here: https://github.com/stenzek/pcsx2/commits/tlb

**Comment by dsmirc** [comment]
> Well out of scope for now. I have a branch with full TLB emulation that's a work in progress, but it still craps itself once it gets into userspace. If you want to debug what's going on and contribute to it, the code is here: https://github.com/stenzek/pcsx2/commits/tlb

I've compiled the WIP TLB fork you mentioned, and I can confirm that the issue persists.

**Comment by stenzek** [comment]
Not sure where I claimed that the branch allows Linux to boot fully. It was also only implemented for the int, not the rec.
