### ISSUE TITLE
[BUG]: Crash on closing the app

### ISSUE THREAD

**Issue by Bezbashni** [PCSX2/pcsx2#8660]
### Describe the Bug

On fresh pcsx2 builds that error started to appear.
![Без имени](https://user-images.githubusercontent.com/110776155/232055834-931d66ae-a7dc-4ffc-9ce1-f44980a067b4.jpg)

### Reproduction Steps

[crash-2023-04-14-16-15-17-961.txt](https://github.com/PCSX2/pcsx2/files/11233155/crash-2023-04-14-16-15-17-961.txt)
[crash-2023-04-14-16-15-17-961.zip](https://github.com/PCSX2/pcsx2/files/11233157/crash-2023-04-14-16-15-17-961.zip)

### PCSX2 Revision

v1.7.4380

### Operating System

Windows 11

**Comment by Bezbashni** [comment]
It was fixed in 1.7.4381 build. Thanks.)

**Comment by refractionpcsx2** [comment]
Did you manage to resolve your issue?

**Comment by Bezbashni** [comment]
> Did you manage to resolve your issue?
> 
> Edit: Weird, no idea why, that code hasn't changed for nearly a year!

Error message dissappeared but crashes still appeared. 
[crash-2023-04-14-21-23-00-573.txt](https://github.com/PCSX2/pcsx2/files/11236006/crash-2023-04-14-21-23-00-573.txt)
[crash-2023-04-14-21-23-00-573.zip](https://github.com/PCSX2/pcsx2/files/11236007/crash-2023-04-14-21-23-00-573.zip)

**Comment by refractionpcsx2** [comment]
That crash is from 3480

**Comment by Bezbashni** [comment]
> That crash is from 4380


[crash-2023-04-14-21-35-22-549.txt](https://github.com/PCSX2/pcsx2/files/11236099/crash-2023-04-14-21-35-22-549.txt)
[crash-2023-04-14-21-35-22-549.zip](https://github.com/PCSX2/pcsx2/files/11236100/crash-2023-04-14-21-35-22-549.zip)

I've reupload another crash dump and  version is exactly 1.7.4381.

**Comment by refractionpcsx2** [comment]
The last guy who had this had an audio CD in his games folder, is that true of any of yours?

**Comment by Bezbashni** [comment]
> The last guy who had this had an audio CD in his games folder, is that true of any of yours?

I have 1638 games different regions (PAL, NTSC-U, NTSC-J) in that folder. So i've copied NTSC-J and Pal region games to that folder and no crashes.  So it's one of NTSC-U games. But i don't know which one causes crashes.

**Comment by refractionpcsx2** [comment]
copy a chunk at a time, i guess :P

**Comment by Bezbashni** [comment]
> > The last guy who had this had an audio CD in his games folder, is that true of any of yours?
> 
> I have 1638 games different regions (PAL, NTSC-U, NTSC-J) in that folder. So i've copied NTSC-J and Pal region games to that folder and no crashes. So it's one of NTSC-U games. But i don't know which one causes crashes.

I've found it. It's Dave Mirra Freestyle BMX 2 (USA) and Arctic Thunder (USA).

**Comment by refractionpcsx2** [comment]
do those games work normally? also if you enable the system log under the tools menu, do you get any weird messages when adding them two games to the list.  actually if you could enable file logging, close the emu, add those two files back to the folder, then open the emu again, and close it (causing the crash, then upload your `emulog.txt` file from the logs folder, that'd be great.

**Comment by Bezbashni** [comment]
> do those games work normally? also if you enable the system log under the tools menu, do you get any weird messages when adding them two games to the list. actually if you could enable file logging, close the emu, add those two files back to the folder, then open the emu again, and close it (causing the crash, then upload your `emulog.txt` file from the logs folder, that'd be great.

I've try to load these games but no luck. Apparently bad dumps. So i've found another dumps of these games and they are loaded.  Case closed. Thank you for your help for identifying this issue.)

**Comment by refractionpcsx2** [comment]
No problem
