### ISSUE TITLE
[BUG]: GLSL 4.30 is not supported.

### ISSUE THREAD

**Issue by vetework** [PCSX2/pcsx2#8661]
### Describe the Bug

Cannot start any games. A pcsx2_bad_shader_1.txt is generated. The last sentence is 

Compile failed, info log:
0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 4.20, 1.00 ES, and 3.00 ES

### Reproduction Steps

xubuntu 20.04, i5-3210m cpu,  Intel HD Graphics 4000, pcsx2 1.7.4379

pcsx2 1.7.4373 and before can load games without error

### PCSX2 Revision

1.7.4379

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

xubuntu 20.04

**Comment by TellowKrinkle** [comment]
Have you tried Vulkan?  HD 4000 should have an experimental Vulkan driver.

I'll check what we're doing that requires GLSL 430 later, we might be able to get by with just some extensions

**Comment by lightningterror** [comment]
GL should work in this case, on windows I tested and it works which has far less support than linux.

**Comment by lightningterror** [comment]
@vetework Can you also upload the whole bad shader file?

**Comment by TellowKrinkle** [comment]
> GL should work in this case, on windows I tested and it works which has far less support than linux.

That's because it's so bad that we didn't even try to use vs expand

**Comment by vetework** [comment]
> > GL should work in this case, on windows I tested and it works which has far less support than linux.
> 
> That's because it's so bad that we didn't even try to use vs expand

Can use openGL now but the graphic is a mess

OpenGL:
![Mobile Suit Gundam - Gundam vs  Z-Gundam_SLPS-25419_20230415153616](https://user-images.githubusercontent.com/53935043/232209985-2197c5cd-8356-440e-84f4-a48b437b327f.png)

Vulkan:
![Mobile Suit Gundam - Gundam vs  Z-Gundam_SLPS-25419_20230415153631](https://user-images.githubusercontent.com/53935043/232210027-34794d70-d7fc-4233-b5c4-fa5b22a3290b.png)

**Comment by TellowKrinkle** [comment]
Can you test older versions and see if it was ever working in OpenGL?  Anything before v1.7.4377 should run fine without the GLSL 430 bug.

If you find that it was working in a previous version of PCSX2, please find the last version that worked.  If you're compiling from source, you can use `git bisect` for this, otherwise just keep downloading versions halfway between the one you tested working and the one you tested broken until you find the last working version.

**Comment by vetework** [comment]
> Can you test older versions and see if it was ever working in OpenGL? Anything before v1.7.4377 should run fine without the GLSL 430 bug.
> 
> If you find that it was working in a previous version of PCSX2, please find the last version that worked. If you're compiling from source, you can use `git bisect` for this, otherwise just keep downloading versions halfway between the one you tested working and the one you tested broken until you find the last working version.

now 1.7.4393 openGL's graphic is normal. The pervious working version is 1.7.4373.
