### ISSUE TITLE
[Feature Request]: SOCD Cleaner

### ISSUE THREAD

**Issue by ArgentumHook** [PCSX2/pcsx2#8666]
### Description

When pressing both up and down directions simultaneously, the input is displayed as no input direction, and pressing left and right is the same. That is to say, up + down=no direction, left + right=no direction.

### Reason

Input some commands like half circle forward + punch & half circle back + punch would be more convenient.

### Examples

In Street Fighter Alpha Anthology, I input left, down, right together. The input should be down, but it shows no direction.
![image](https://user-images.githubusercontent.com/41683041/232181321-718b3148-9da5-43f4-8a3d-33f378476ba4.png)
So when I want to input right, down, left and punch, the command half circle back + punch is hard to success.

**Comment by stenzek** [comment]
As far as I'm aware, it's not possible to concurrently push both left and right buttons on PS1/PS2 pads.

**Comment by kamfretoz** [comment]
I could be wrong in this, but i don't think you're supposed to be able to press the D-Pad buttons in which they're from opposing directions, so simultaneously pressing Up + Down or Left + Right at the same time aren't possible due to how the DualShock 2's D-Pad buttons are designed

**Comment by stenzek** [comment]
Each of the four directions is represented with individual bits, but since it's not possible on a physical pad, who knows how games might react to having both active at once. Could potentially break things.
