### ISSUE TITLE
hack/Fragment gamefixes database incorrect

### ISSUE THREAD

**Issue by Zederia** [PCSX2/pcsx2#867]
the current gameindex.dbf says this:
Serial = SLPS-25527
Name = dot Hack - Fragment
Region = NTSC-J
Compat = 5
EETimingHack = 1
OPHFlagHack = 1
DMABusyHack = 1

and the mpeg hack is required for the game to boot. I have fixed it locally by changing it to this:

Serial = SLPS-25527
Name = dot Hack - Fragment
Region = NTSC-J
Compat = 5
EETimingHack = 1
OPHFlagHack = 1
DMABusyHack = 1
SkipMPEGHack = 1

**Comment by ssakash** [comment]
Then make a new PR to include this in the gameDB ?

**Comment by refractionpcsx2** [comment]
I told him to put it here, presumed he didn't have a git setup
