### ISSUE TITLE
[BUG]: Sega Rally Championship '95 Loading Screens Black + Hash Cache Message

### ISSUE THREAD

**Issue by silentq** [PCSX2/pcsx2#8672]
### Describe the Bug

I noticed an issue with Sega Rally Championship '95 it appears that background textures are not showing in the loading screens.

Settings are default other than Upscaling to 4K and 4:3 Forced Aspect Ratio.  I have checked with just all default settings and this issue is still present.

You can see in the screens that any splash screens or background image assets seem to load blank.
![Sega Rally Championship '95_SLPM-62703_20230415105902](https://user-images.githubusercontent.com/2636426/232233014-a9007960-4097-4974-a4c5-cf8358ca68b3.png)
![Sega Rally Championship '95_SLPM-62703_20230415105518](https://user-images.githubusercontent.com/2636426/232233019-169bc123-a3c0-4f80-86b7-13b196d83cc2.png)

If you check the software renderer these images do in fact load.

I believe this is possibly related to #5582 and #5578 due to the fact that I am seeing the Hash Cache Message upon loading into the first area.  This seems like the only time this message appears.
![Screenshot 2023-04-15 110013](https://user-images.githubusercontent.com/2636426/232233027-a267e834-d118-487f-8b11-de40f78e3063.png)

### Reproduction Steps

Run Sega Rally Championship '95
Check the initial splash screen (Press Start Button Screen) and Car Select Screen.
Load into initial game play.

### Expected Behavior

Background images should be present and Hash Cache Message should not show on initial Gameplay Load in.

### PCSX2 Revision

1.7.4383

### Operating System

Windows 11

### CPU

Ryzen 5600X

### GPU

Nvidia RTX 3080 TI 

### GS Settings

Defaults other than:
Aspect Ratio Standard(4:3)
Renderer Automatic (Default) it is Vulkan by default
Internal Resolution 6X Native
Adapter: Nvidia Geforce RTX 3080 Ti

### Emulation Settings

All Defaults

### Logs & Dumps

[Press Start Screen.zip](https://github.com/PCSX2/pcsx2/files/11239890/Press.Start.Screen.zip)
[Select Car Screen.zip](https://github.com/PCSX2/pcsx2/files/11239891/Select.Car.Screen.zip)
[Hash Cache Message.zip](https://github.com/PCSX2/pcsx2/files/11239892/Hash.Cache.Message.zip)

**Comment by Buzzardsoul** [comment]
@silentq Can you provide me with a gs dump?

**Comment by silentq** [comment]
@Buzzardsoul Sorry added to my initial post.

**Comment by Buzzardsoul** [comment]
@silentq The first and the third only have a few garbage pixels in comparison to software. Highly inconsequential in my view.
The second one requires a larger CPU Sprite Render Size such as 8 or Disable depth emulation.

**Comment by silentq** [comment]
Ok Interesting right on the money with sprite render size 8.
![Screenshot 2023-04-15 124614](https://user-images.githubusercontent.com/2636426/232238851-43f2790f-48b8-4474-bfe7-669f484e3212.png)
![Screenshot 2023-04-15 124659](https://user-images.githubusercontent.com/2636426/232238853-e89c5476-1190-463e-8dab-a7633adaa059.png)

The consequences seem to be just turning on manual hardware fixes and setting CPU Sprite Render Size = 8 sent everything Else to Black and White.
![Screenshot 2023-04-15 124843](https://user-images.githubusercontent.com/2636426/232238932-d25d2f34-367d-46f6-8153-9520af59dd13.png)

Curious as to if some other fix needs to be in place when running manually?

**Comment by refractionpcsx2** [comment]
You need to re-enable the SW CLUT (Aggressive) fix, if you're gonna do manual fixes.

**Comment by silentq** [comment]
@refractionpcsx2 Thanks! Fixed the graphical glitches.  One question any reason why turning that on brings back the Hash Cache Message?  It seemed to go away without the SW CLUT setting?
![Screenshot 2023-04-15 125820](https://user-images.githubusercontent.com/2636426/232239508-df03988d-4344-4450-afba-f1f322085612.png)

**Comment by refractionpcsx2** [comment]
without it, you're moving the load somewhere else, which is why it runs like crap, I guess you could set Texture Preloading on the Rendering tab to "Partial" that should solve it.

**Comment by silentq** [comment]
@refractionpcsx2 Gotcha was just curious.  It seems to have no performance impact for my setup this game runs locked 60fps but I suppose this moving of the load somewhere else could affect others.

Thanks for all the help!

**Comment by Buzzardsoul** [comment]
> @refractionpcsx2 Gotcha was just curious. It seems to have no performance impact for my setup this game runs locked 60fps but I suppose this moving of the load somewhere else could affect others.
> 
> Thanks for all the help!

Don't close it, it's a valid issue

**Comment by silentq** [comment]
No problem!  Reopening.

**Comment by silentq** [comment]
Another comment here. @refractionpcsx2 moving to partial Texture loading as you mentioned seems to get rid of the Hash Cache Message. Thankfully I see no performance impact here after running through the game.  So it would appear the combination of the following settings gets this game running without a hitch at least on my system.

Rendering Tab:
Texture Preloading = Partial
Manual Hardware Fixes = Checked

Hardware Fixes Tab:
CPU Sprite Render Size = 8 (512 Max Width)
Software CLUT Render = 2 (Aggressive)

@Buzzardsoul hope this helps as well.  Thanks again to you both.

**Comment by stenzek** [comment]
There's very little legit reason to set CPU sprite render that high - it's only for debugging, and is going to be quite slow.

It's probably a TC bug.
