### ISSUE TITLE
[BUG]: PacMAn World 3 starts only in German.

### ISSUE THREAD

**Issue by gemimmo** [PCSX2/pcsx2#8674]
### Describe the Bug

PacMan World 3 starts only in German.

### Reproduction Steps

Launch PacMan World 3.

### PCSX2 Revision

v1.7.4385

### Operating System

Windows 10 (64bit)

### CPU

i7-6700hq

### GPU

gtx970

**Comment by refractionpcsx2** [comment]
What is the serial number of your game? SLES and the numbers following it

**Comment by Buzzardsoul** [comment]
@gemimmo What is the system language of your bios set to?

**Comment by gemimmo** [comment]
SLES53959. Bios is set to English. It depends on PS2 bios, I think.

**Comment by gemimmo** [comment]
It depends on the fact that is not possible to choose console language, yet. I close the issue.

**Comment by refractionpcsx2** [comment]
It is possible to choose console language, it's the same way you'd do it on a real console.
