### ISSUE TITLE
[BUG]: Adventures of Cookies & Cream - Graphical Lines

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8675]
### Describe the Bug

![image](https://user-images.githubusercontent.com/8139496/232245995-e53c9609-e9d6-4ba1-9053-d2ac166d87bb.png)

Everything seems to have lines through it, probably some kind of issue with interlacing?

### Reproduction Steps

Start the game. Notice that the logo and demo video are all lined.

### PCSX2 Revision

1.7.4385

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by Buzzardsoul** [comment]
@Meerkov Do you have a gs dump?

**Comment by Meerkov** [comment]
![Adventures of Cookie   Cream, The_SLUS-20170_20230415112712](https://user-images.githubusercontent.com/8139496/232247173-e6da768e-e953-4
[Adventures of Cookie & Cream, The_SLUS-20170_20230415112742.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11240323/Adventures.of.Cookie.Cream.The_SLUS-20170_20230415112742.gs.zst.zip)
d14-a517-382fc1b51c57.png)

Note: Switching to software rendering temporarily, and then switching back to hardware rendering... seems to fix the issue for some reason.

**Comment by refractionpcsx2** [comment]
Probably needs the SWFMV fix, but I think this might be a regression.

**Comment by Mrlinkwii** [comment]
can this be rechecked on latest nightly

**Comment by forrvalhalla** [comment]
FMVs look good to me, HW/SW are identical. Using a fresh install.
![pcsx2-qt_aqtF3mvqlV](https://github.com/PCSX2/pcsx2/assets/53349573/1f68e20d-3912-40a4-82df-bd90a72fa5c5)

**Comment by refractionpcsx2** [comment]
Thanks for testing!
