### ISSUE TITLE
[Feature Request]: possibility to choose console language .

### ISSUE THREAD

**Issue by gemimmo** [PCSX2/pcsx2#8676]
### Description

Some games have not language menu; the only language playable is the console language. 

### Reason

I'd like to play games in my language.

### Examples

PCSX2 1.6.0 does it.

**Comment by Mrlinkwii** [comment]
You can, boot the bios and set it :/

**Comment by gemimmo** [comment]
what a shame...

**Comment by RedDevilus** [comment]
It's either the game handles it with a prompt, or copies the value from BIOS or both or some sort of twist on it like default point to bios language but still change.

**Comment by refractionpcsx2** [comment]
What do you mean what a shame?? a shame you can do it? I don't get your issue...

**Comment by gemimmo** [comment]
I could think before write....
