### ISSUE TITLE
[BUG]: Shadow of Rome flickering pixels

### ISSUE THREAD

**Issue by howdoicodeplease** [PCSX2/pcsx2#8678]
### Describe the Bug

Pixels flickering constantly on screen when running shadow of Rome, this can be fixed by using skipdraw 0 to 1000 but then important gameplay information isn’t rendered such as health.There is also a haze across the screen which also disappears when skipdraw is changed to 0 to 1000

### Reproduction Steps

Run the game at ps2 render resolution

### Expected Behavior

No flickering pixels and a clear image

### PCSX2 Revision

V1.7.4319

### Operating System

Windows 11

### CPU

Ryzen 5 3600

### GPU

RTX 3070 ti

**Comment by RedDevilus** [comment]
Please give GS dump with picture, skipdraw on that big range isn't a solution, that's basically killing the post-processing that is perhaps failing.

**Comment by howdoicodeplease** [comment]
![Shadow of Rome_SLES-52950_20230416134352](https://user-images.githubusercontent.com/105949717/232312385-267b14be-7988-4fc8-be3c-b2e901449188.png)
[Shadow of Rome_SLES-52950_20230416134352.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11242295/Shadow.of.Rome_SLES-52950_20230416134352.gs.zst.zip)
I've played the game a while back and I don't remember this being an issue so either I enabled something by accident or an update caused this to change

**Comment by Buzzardsoul** [comment]
The game works fine here. The only thing it might need is a maximum blending for that floor. But that's pretty much it in my eyes

**Comment by Mrlinkwii** [comment]
the GS dump provided seems fine
![image](https://user-images.githubusercontent.com/17685135/232491460-0de98596-12c4-4f78-aaaa-3d7dc3a334ab.png)
heres software for comparison  
 
![image](https://user-images.githubusercontent.com/17685135/232491714-912d2ea5-eb07-4697-b8ea-b124acd105ca.png)

**Comment by JordanTheToaster** [comment]
The effect is intentional there is no issue here.
