### ISSUE TITLE
Memcard screen closure resumes emulation

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#868]
Once your game is running, escaping out and opening then closing the memcard screen resumes the emulation, correct behaviour should be that it just closes the memcard screen (like the emulation settings and plugin settings)

**Comment by avih** [comment]
Is this a regression? if yes, since when?

**Comment by refractionpcsx2** [comment]
OK it might not be a bug, it may have always done this ( can't tell without getting a bunch of old revisions)  but for usability sake it probably shouldn't

**Comment by turtleli** [comment]
It's probably always been that way, though I would consider it as a bug.

There's actually some similar behaviour when you escape out of a running game, then change plugins - the GS window opens up again, though it doesn't resume.

**Comment by avih** [comment]
Sure, it's clearly a bug, but would be helpful to know if it used to work well at some stage.

**Comment by refractionpcsx2** [comment]
Ok then relabeled as bug.  As i say, it was doing it as far back as 0.9.8, that's long enough ago to assume its always been like this.  Trying to find much older code will be a pain.

**Comment by avih** [comment]
Bug is something which doesn't work as expected. Regression is also a bug, with the additional info that we know it wasn't a bug at some earlier point in time.

**Comment by refractionpcsx2** [comment]
ok well further investigation shows it was bought in between 0.9.7 r3878 beta and 0.9.8, after WX was implemented. so between r3878-r4600, I can't check any closer than that
