### ISSUE TITLE
[Feature Request]: separate trilinear filtering options for FMV playback and gameplay

### ISSUE THREAD

**Issue by vim449** [PCSX2/pcsx2#8680]
### Description

In the settings->graphics->rendering tab, there is an option labelled "trilinear filtering." The feature request would turn this into two options "trilinear filtering" and "FMV trilinear filtering", where the standard trilinear filtering option is used like it is normal, but when an FMV is played, the FMV trilinear filtering option is used (I don't have in depth knowledge of the code base, but here already exists options to have different aspect ratios for FMVs and other gameplay, as well separate options to dump textures and FMV textures, so clearly there must be some portion of the rendering code that is able to determine when an FMV is playing and change parts of the rendering/display process, so I would think it should be possible to add such a delineation for trilinear filtering.

### Reason

For Persona 3 FES, all of the game's cutscenes look _drastically_ better when the trilinear filtering option is set to "forced". I have a 4K screen, so when the 368p FMVs are displayed, they have to be upscaled by a very massive amount. When not using forced trilinear filtering, this causes them to look extremely blocky/pixelated. Enabling forced trilinear filtering causes this issue to go away however, such that playback much more closely resembles what I would see on hardware when displaying on a tv of the same resolution, and also much more closely mirrors what I would see if I took the SFD file from the disc and played it back in a media player. _However_, enabling forced trilinear filtering introduces graphical bugs during gameplay, such as the tartarus minimap being less accurate to hardware than it currently is without it on, and characters blink animations become multiple pixels offset from their face such that you get harsh horizontal lines across everyone's faces. As such, I want a way to improve the visual quality of FMV playback in the emulator without affecting regular gameplay

### Examples

![image](https://user-images.githubusercontent.com/64444201/232261712-2d539ba5-de65-4b1f-87ea-ab1dfb5b033b.png)
![image](https://user-images.githubusercontent.com/64444201/232261847-88c168b8-6480-4b80-bcc6-0a78ee7e8010.png)
Comparison between trilinear filtering forced and trilinear automatic (default). As you can see, having it on during gamplay creates additional rendering bugs and is something that should be disabled.

![trilinear_on](https://user-images.githubusercontent.com/64444201/232261952-3dc2e961-e7c4-4235-a01b-701ffc0de2b0.png)
![image](https://user-images.githubusercontent.com/64444201/232261884-4dc69b92-3217-42c2-b39d-5106522c3c54.png)
Comparison between trilinear filtering forced and trilinear automatic (default). During FMV playback, having it on significantly improves the quality of the image, so it is an option I would like to have on.

**Comment by refractionpcsx2** [comment]
No, that's ridiculous.

**Comment by vim449** [comment]
> No, that's ridiculous.

Care to elaborate _why_ instead of closing the post without any documenation? Your code base clearly has the capability to change aspects of the rendering pipeline for FMVs as seen by the FMV aspect ratio, so there's no clear technical limitation that I can see as someone who hasn't worked with the code base before, and as documented above, having the ability to change it for FMVs without affecting everything clearly increases the quality of the image. If you can give an actual reason for why it's "ridiculous" I'm happy to drop it, but at least take the effort to detail why such a feature wouldn't be feasible

**Comment by refractionpcsx2** [comment]
Alright,

Well FMV's don't use trilinear filtering, trilinear is designed for smoothing textures between 3d polys as they go in to the distance, which aren't FMV's.

And I'm not going to waste my time adding more options for people to use the "forced" option.  Though you are welcome to implement it yourself and maintain your own fork.

**Comment by vim449** [comment]
Out of curiousity, if FMVs don't make use of trilinear filtering, then why do I see such a massive improvement to image quality during FMV playback when it's set to forced?

**Comment by refractionpcsx2** [comment]
if by improvement you mean blurring the crap out of it, then sure, it does that, because forcing trilinear forces bilinear filtering inherently as part of it (trilinear is bilinearing 2 textures together), you would potentially get a similar effect by using forced bilinear also, but either way, the drawing pipeline forces it to go through the trilinear filtering path, causing it to blur.

**Comment by RedDevilus** [comment]
Placebo effect for one, no one can escape that.

**Comment by alexankitty** [comment]
All we're asking is an option for filtering FMVs so they can look their best. FMVs in general seem to suffer from really nasty compression artifacting and we're at the limit of what we can do.
The entire point was to have an option so we don't have to use the forced option.
Also changing the bilinear settings has no impact on the FMVs, only that trilinear forced option.

**Comment by refractionpcsx2** [comment]
Triulinear filtering makes absolutely no sense for FMV's, and I'm not adding it so people can use it as a hack.

As I said, you're welcome to do it yourself and maintain a fork.
