### ISSUE TITLE
[BUG]: Super Robot Wars Impact fps drop

### ISSUE THREAD

**Issue by srw20166** [PCSX2/pcsx2#8684]
### Describe the Bug

Using attack command fps will drop to 30fps
Please fix

### Reproduction Steps

Using attack command fps will drop to 30fps
Please fix

### PCSX2 Revision

pcsx2-v1.7.4393

### Operating System

Windows 10 (64bit)

### CPU

I5 4460

### GPU

GTX 2060

**Comment by Mrlinkwii** [comment]
Can I have a gs dump

**Comment by srw20166** [comment]
> Can I have a gs dump

How to generate gs dump

**Comment by Buzzardsoul** [comment]
> > Can I have a gs dump
> 
> How to generate gs dump

Tools => Save Single Frame Gs Dump 

You will find it in the snaps folder, Zip it and upload it here.

**Comment by srw20166** [comment]
> > > Can I have a gs dump
> > 
> > 
> > How to generate gs dump
> 
> Tools => Save Single Frame Gs Dump
> 
> You will find it in the snaps folder, Zip it and upload it here.

[Super Robot Taisen Impact_SLPS-25104.zip](https://github.com/PCSX2/pcsx2/files/11243060/Super.Robot.Taisen.Impact_SLPS-25104.zip)

**Comment by JordanTheToaster** [comment]
Performance in game is fine so it's likely down to your system.
