### ISSUE TITLE
[BUG]: Totally Spies! Totally Party - Polygons are All Messed up

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8687]
### Describe the Bug

The polygons of all the character models are all crazy.
[Totally Spies! Totally Party_SLUS-21795_20230416131824.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11243313/Totally.Spies.Totally.Party_SLUS-21795_20230416131824.gs.zst.zip)
![Totally Spies! Totally Party_SLUS-21795_20230416131824](https://user-images.githubusercontent.com/8139496/232339891-afddaf6c-fd74-42ba-87cf-1db287ca4fa2.png)

### Reproduction Steps

Start the game, that's it. 

### PCSX2 Revision

1.7.4393

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by Mrlinkwii** [comment]
need EE+3  i believe

**Comment by refractionpcsx2** [comment]
yup, Mrlinkwii is right.

**Comment by Meerkov** [comment]
Huh? This still reproduces.

**Comment by refractionpcsx2** [comment]
If you followed the advice above, it's fine, and there's nothing we can do about this.

![image](https://user-images.githubusercontent.com/6278726/233587056-05476df7-ca5a-4d09-a31c-9a1a870f7c94.png)

**Comment by Meerkov** [comment]
Ok thanks, I changed that setting and now it looks right. I thought this was something that would be set in some game config for all users.

Does 1.7.x need to be set to 300% for all games? Should I put it back to 100% when changing games? I don't know what this setting is for, or when I should be using it
