### ISSUE TITLE
[BUG]: Dark Cloud - Broken Textures

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8689]
### Describe the Bug

Watch the intro cutscene. Some textures pop in and out or become invisible.

### Reproduction Steps

Watch the fat guy or the main dancer's legs to notice invisible textures popping in and out.

### PCSX2 Revision

1.7.4393

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

### Logs & Dumps

![Dark Cloud_SCUS-97111_20230416194518](https://user-images.githubusercontent.com/8139496/232365930-e7839ba2-f06d-449b-b931-2dde0d7add76.png)
[Dark Cloud_SCUS-97111_20230416194518.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11245687/Dark.Cloud_SCUS-97111_20230416194518.gs.zst.zip)

**Comment by refractionpcsx2** [comment]
Requires Partial Target Invalidation

![image](https://user-images.githubusercontent.com/6278726/232418164-45e59d2f-5b29-4726-b640-dc4bcce9335e.png)

We'll add it to the GameDB
