### ISSUE TITLE
 [Bug Report] Ape Escape 2 [NSTC-U]

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#869]
**PCSX2 versions used:** 
pcsx2-v1.3.1-1199-g379adf3-windows-x86 (latest dev build)
**# Emulation settings:** "Safest" preset 
**# Plugins used:** GSdx AVX2, using the OpenGL renderer (hardware and software)
**# Plugin settings:** CRC Hack Level "None", with all the accurate stuff on.
**# Description:** 
On hardware mode, far away 3D models have their textures being cycled fast through several other game textures.
This stops as the player gets closer. On software mode this does not happen.
According to the http://wiki.pcsx2.net/index.php/Ape_Escape_2, this bug is as old as revision 1.0 r5350 and was still present in revision 1.1.0 r5517. 

**# CPU:** Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
**# GPU:** NVIDIA GeForce GTX 970 (Driver: NVIDIA 355.98)

**# Screenshots:**

Here's software mode, expected to be correct:

![image:!](http://i.imgur.com/1M94OUW.png?1)

Here's hardware mode. Notice that the building in front has the wrong texture, the left row of sunflowers is messed up, among other things.

![image:2](http://i.imgur.com/hirx6Ri.jpg?1)

**GS DUMP:** http://forums.pcsx2.net/attachment.php?aid=57595

**Comment by gregory38** [comment]
Did you try without mipmap in SW?

**Comment by ssakash** [comment]
The issue seems to be present when mipmap is disabled on software mode.

**Comment by refractionpcsx2** [comment]
Can anybody confirm this now fixed?

**Comment by FlatOutPS2** [comment]
I wouldn't call a fixed. With whatever option you choose(Full mipmapping and Trilinear Ultra is required to emulate the image shown in SW), texture issues will remain.

**Comment by ctrlcctrlv** [comment]
The issue persists in 1.4.0, rendering the game virtually unplayable.
[Video of Ape Escape 2 gameplay affected by PCSX2 issue 869.zip](https://github.com/PCSX2/pcsx2/files/1179149/Video.of.Ape.Escape.2.gameplay.affected.by.PCSX2.issue.869.zip)

**Comment by TransparentBlue** [comment]
Mostly fixed in the current version ('1.7.2218) by booting and running the game with the following setting 

1. Using OpenGL or Vulkan
2. Turning GPU Palette conversion off
3. Turning Texture preload on
4. Anisotropic Filltering to 16x
5. Setting Mipmapping to full (auto doesn't work)
6. Setting Trilinear filtering to Ultra under the hack menu

https://user-images.githubusercontent.com/16150597/148918977-43edcc17-2691-4a4a-923c-741087975cf7.mp4

**Comment by ctrlcctrlv** [comment]
Heh, apparently I tried to play AE 2 in 2017 :wink:
