### ISSUE TITLE
[BUG]: Dragon ball z budokai tenkaichi 3 pal black screen issue

### ISSUE THREAD

**Issue by CasinoNight** [PCSX2/pcsx2#8691]
### Describe the Bug

black flashes only happens in pal version ntsc works well also happens in bt2 pal ,software mode default settings and hadware mode still happens ,in previous versions it did not happen

https://streamable.com/z3w1p0

### Reproduction Steps

.

### Expected Behavior

.

### PCSX2 Revision

1.7.4395

### Operating System

Windows 10 (64bit)

### CPU

I5 11400F

### GPU

RTX 3050

### GS Settings

Default

### Emulation Settings

.

### GS Window Screenshots

.

### Logs & Dumps

.

**Comment by stenzek** [comment]
Needs a GS dump (probably multi-frame in this case), and if you're claiming it didn't happen in a previous version, which version broke it.

**Comment by CasinoNight** [comment]
> this is how it should look, same settings all default, pal version, the bug It also happens at the end of a fight in lastest ver

previous version: v1.7.3650
https://streamable.com/8zxdbc

**Comment by lightningterror** [comment]
Can you find out which version broke it, also you didn't provide a gs dump.

**Comment by CasinoNight** [comment]
> Can you find out which version broke it, also you didn't provide a gs dump.

Where is located gs dump?

**Comment by refractionpcsx2** [comment]
I suspect a GS dump won't be enough, it looks like a GS download thing.

**Comment by stenzek** [comment]
Ah, I guess it could be download... I assumed shuffle based on the half screen lol

Either way, we'll need a GS dump or block dump.

**Comment by CasinoNight** [comment]
In ntsc this dont happens

**Comment by lightningterror** [comment]
Blockdump and savestate:
[DBZ BT3 PAL (2023-04-21 20-25-37).zip](https://github.com/PCSX2/pcsx2/files/11298390/DBZ.BT3.PAL.2023-04-21.20-25-37.zip)
[SLES-54945 (A422BB13).01.zip](https://github.com/PCSX2/pcsx2/files/11298386/SLES-54945.A422BB13.01.zip)

Regression build:
https://github.com/PCSX2/pcsx2/pull/8209

**Comment by CasinoNight** [comment]
Finally fixed, thanks for the support

https://streamable.com/cko1vg
