### ISSUE TITLE
[BUG]: Tokyo Xtreme Racer Zero (SLUS-20189) Exhibits Car Corruption in the Menu

### ISSUE THREAD

**Issue by sinisterseed** [PCSX2/pcsx2#8694]
### Describe the Bug

The cars appear corrupted in the menu, more exactly, they have a rainbow look.

This does not seem to extend to other parts of the game, such as the actual gameplay, but the cars being corrupted in the menu does very much make it impossible to choose the car you desire, making it a guessing game...

This happens in Vulkan, I haven't tried the other renderers.

### Reproduction Steps

Start up the game and go to the car lot. Every single car has corrupted textures.

### Expected Behavior

No psychedelic cars.

### PCSX2 Revision

v1.7.4395

### Operating System

Windows 10

### CPU

i5-6402P

### GPU

GTX 950

### GS Settings

Default.

### Emulation Settings

Default.

### GS Window Screenshots

![broken](https://user-images.githubusercontent.com/57503728/232536894-603eb2cd-3114-4a49-b73c-ace50fdfba3a.png)

**Comment by JordanTheToaster** [comment]
Regression from #8336
