### ISSUE TITLE
[BUG]: Godzilla: Save the Earth Texture Replacement Issues.

### ISSUE THREAD

**Issue by Boniepizza** [PCSX2/pcsx2#8696]
### Describe the Bug

Issue 1: Most glaring is this ground texture in particular. 93aa7c93a6a43b40-80001dc2.png

A ground texture in the Daytime version of the Monster Island Stage. 

![Screenshot_66](https://user-images.githubusercontent.com/32172084/232627484-05554f7e-bd56-4c02-a3c4-e446d800ba33.png)
![Screenshot_64](https://user-images.githubusercontent.com/32172084/232627487-6432e6eb-09cd-4467-929f-ca3a3403a7bf.png)
![Screenshot_65](https://user-images.githubusercontent.com/32172084/232627488-1a71050b-e0de-4ad5-85b4-2339b3174a7e.png)

(it also seems that mipmaps dump whether dump mipmaps are turned on or not)
![Screenshot_63](https://user-images.githubusercontent.com/32172084/232627486-bc02c8db-3013-4072-b877-762fa3cd398a.png)

I originally tried replacing this with a higher res texture, but after some fiddling with injector settings and troubleshooting, i simply tried to get a fresh dump from the game and i threw it right into replacements, after scribbling on it.
after pressing the reload texture replacements hotkey nothing changed. i then closed the emulator and restarted it, no changes still. and yes "Load Textures" Is turned on. It isnt just this texture that does this, but instead it seems any texture without a palette does this. 

This texture in particular actually did replace the first time i tried to do so, but for one reason or another nothing i do can get it to replace again. i tried:
Making the texture replacement black and white.
removing it from the replacement folder and getting a freshly dumped texture, like above.
Asking a friend to give the texture in particular a palette. This worked. he was successfully able to get it to replace after giving the texture (the in game texture, not the replacement mind you.) a palette.
![Screenshot_112](https://user-images.githubusercontent.com/32172084/232629111-127e6e88-9c1e-4797-b4ea-846abbfe60cc.png)
*His version of the game is very modded, which is why the textures look like that. The purpose of doing that to them is so that textures in each stage can have unique IDs. That way say if we wanted a stage to look snowy, those snowy textures wont be shared to other maps. This does not seem to affect this here bug in any way, as the first time i tried to replace it, was in one of these 'scrambled' stages.

As you can see the texture in question in this screenshot has now been successfully replaced (with a random screenshot).
Link to a discord conversation about this issue: https://discord.com/channels/309643527816609793/923492653788692480/1097362426279776258

Issue 2: 
We used the old injector, the PCSX2: EX one previously for our project, and other than performance it worked very well. 
This new injector though splits building tiles into single texture pieces (which happens to be inaccurate to the actual in game files, as in the files they are sheets of textures.) 
![Screenshot_67](https://user-images.githubusercontent.com/32172084/232628549-c93b9894-31af-4257-a014-cc634114eadf.png)
The sheet there is what is expected. The single tile to the side though also dumps. we aren't sure which one to replace, as it's inconsistent. sometimes replacing the sheet works, sometimes it doesn't. replacing both even doesn't always work.
These buildings, unlike the first issue mentioned DO have palettes. The ones that do or dont replace stay the same. The buildings in Monster Island for example just simply don't want to replace. or if they do its only partial or they revert back and redump the same exact texture in the dumps folder, despite already being in the replacements folder.

### Reproduction Steps

Issue 1: Open Godzilla: Save the Earth, and dump textures in the Monster Island Stage. 
Find 93aa7c93a6a43b40-80001dc2.png and either put it into your replacements folder with changes, or rename any png to "93aa7c93a6a43b40-80001dc2" inside the folder. 
Watch as nothing changes no matter what you do.

The Helicopters spinning blades texture, and the stage barriers behave the same. 

Issue 2: Attempt to replace different building textures in one of the city stages, though an easy example is back in Monster Island, the little turret buildings.

### Expected Behavior

I expected the textures to replace without issues, they did not.

### PCSX2 Revision

v1.7.4397 nightly

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3600 6-Cores

### GPU

NVIDIA GeForce GTX 980

### GS Settings

here's literally everything.

![Screenshot_68](https://user-images.githubusercontent.com/32172084/232630486-2193e4b3-cc90-49cf-8d76-2493a044d9b3.png)
![Screenshot_70](https://user-images.githubusercontent.com/32172084/232630494-d45a4d37-f131-4f3f-bd07-72faca1e0c41.png)
![Screenshot_71](https://user-images.githubusercontent.com/32172084/232630499-5f9a4778-ac00-436e-bbbe-62524185bc5d.png)
![Screenshot_72](https://user-images.githubusercontent.com/32172084/232630503-6f148e0a-4524-4d9a-8db2-6f39672ac1aa.png)
![Screenshot_73](https://user-images.githubusercontent.com/32172084/232630508-5916814a-86f9-41ba-b4b3-789cd71e2914.png)

**Comment by stenzek** [comment]
Unless you provide a GS dump, I can't say what's going on.

But it likely sounds the same as #8692 - the game using UV coordinate space, setting bogus texture width/height (as they're not used with UVs), and not using a clamp mode which PCSX2 can turn into a region texture.

Again, can't say without a GS dump.

**Comment by TheTohoSociety** [comment]
[Godzilla - Save the Earth_SLUS-20809_20230418115953.zip](https://github.com/PCSX2/pcsx2/files/11263936/Godzilla.-.Save.the.Earth_SLUS-20809_20230418115953.zip)
Here's the GS Dump (Also hi, this is from someone else that works on the mod).

**Comment by Boniepizza** [comment]
> Unless you provide a GS dump, I can't say what's going on.
> 
> But it likely sounds the same as #8692 - the game using UV coordinate space, setting bogus texture width/height (as they're not used with UVs), and not using a clamp mode which PCSX2 can turn into a region texture.
> 
> Again, can't say without a GS dump.
> 
> (basically, in clearer terms, when using UVs, there isn't really a concept of a "texture" - just a base pointer somewhere in video memory, a stride in blocks, and an offset - we don't know the height, and the stride doesn't necessarily equal the width).

my friend here offered a gs dump. i was at work so i couldn't right away. 
so more or less your theory is the game has a roundabout way of doing UVs that makes it strange? topaz tk's injector dumped them just fine.

**Comment by stenzek** [comment]
That GS dump is pretty... broken, local memory is messed up somehow. But anyway.

> (it also seems that mipmaps dump whether dump mipmaps are turned on or not)

These are correct. The game is specifically setting a 256x256 texture, and STQ coordinates (normalized).

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/11288319/233053597-795443fd-a619-481b-946f-2c13c945ea30.png">

The only issue I found was that non-paletted replacements weren't getting parsed correctly, which is fixed in #6596.

> so more or less your theory is the game has a roundabout way of doing UVs that makes it strange? topaz tk's injector dumped them just fine.

Then use it instead? You're probably not aware of the history, but the guy was a bit of a prick, abused several PCSX2 developers, myself included, took a bunch of money from people then ran off, and the "injector" was a massive hack (handling things at the API level, which will give incomplete textures). So we don't really want to hear about it.

PCSX2's texture replacement isn't an "injector". It (ab)uses the fact that we try to cache textures inbetween frames based on their hash, and instead of loading the texture data from emulated VRAM, loads a replacement from the host instead. Once the hash cache has been populated, the exact same drawing code runs, there's nothing external "injecting" stuff into PCSX2.
