### ISSUE TITLE
[Feature Request]: Add Game Fixes Settings for remove motion blur/ghosting effect in Sly Cooper games

### ISSUE THREAD

**Issue by cjunisl** [PCSX2/pcsx2#8698]
### Description

Inclusion of game fixes for Sly Cooper games to remove the motion blur/ghosting effect.

### Reason

This effect considerably impairs the quality of graphics in games, giving a blurred appearance. Currently there is already a patch created that allows to solve this problem in the three games and some prototypes/demos. My suggestion is to include this fix natively in the emulator.

### Examples

Video: https://www.youtube.com/watch?v=JaroRhCQiVg

![Sly screenshot 2](https://user-images.githubusercontent.com/57728845/232773701-ccd3c199-7681-487d-a84c-510df26e8758.png)
![Sly screenshot 3](https://user-images.githubusercontent.com/57728845/232773706-ddae804d-9da2-419d-8c90-e82725b0f17f.png)
![Sly screenshot](https://user-images.githubusercontent.com/57728845/232773707-a7af1b01-02c4-4fb6-af00-fa9b550f3a64.png)

**Comment by Mrlinkwii** [comment]
As mentioned use the no-interlace patch, otherwise it's working as intended

**Comment by cjunisl** [comment]
Unfortunately deinterlacing patch in the settings don't solve this problem. Just the video patch solved the problem perfectly.

**Comment by refractionpcsx2** [comment]
The ghosting/blur is intentional in the game, if somebody wants to improve the patch if it doesn't work, then that's on somebody else to do, but we're not adding a hack in to the emulator.
