### ISSUE TITLE
[BUG]: In-Game Progressive scan mode not activating 

### ISSUE THREAD

**Issue by thatman84** [PCSX2/pcsx2#8699]
### Describe the Bug

While testing lightgun games I have noticed the method of activating Progressive mode (Hold trigger offscreen+press select) is not taking effect.
(Interlaced is displayed only on OSD)

Games Tested (Not Working)

Dino Stalker - SLES-50930
Guncom 2 - SLES-52620
Time Crisis 2 - SCES-50300
Time Crisis II - SLUS-20219
Time Crisis 3 -  SCES-51844
Time Crisis 3 [with Guncon] - SLUS-20645
Vampire Night - SCES-50411
Virtua Cop - Elite Edition - SLES-51229

Game Tested (Working)
Burnout Revenge (PAL) Switched with X+Triangle and choose via displayed option

### Reproduction Steps

Set BIOS - Component Video Out to - Y Cb/Pb Cr/Pr

Load game and at calibration screen,

Hold Trigger Offscreen + Press Select (Virtua Cop was Trigger+Start maybe, it was tricky to get)

Onscreen message will appear with Progressive/High Density/High Resolution or something similar)

OSD Will not register the change to Progressive scan

### Expected Behavior

video output should change to Progressive scan

### PCSX2 Revision

 v1.7.4314

### Operating System

Windows 10 (64bit)

### CPU

i5 - 4690

### GPU

GTX 75Ti

### GS Settings

All settings default

### Emulation Settings

Default

**Comment by Mrlinkwii** [comment]
> have noticed the method of activating Progressive mode (Hold trigger offscreen+press select) is not taking effect.

are you sure the games support this ?

**Comment by refractionpcsx2** [comment]
According to this list, none of these games support progressive scan in the PAL region http://www.benoitren.be/480p-palps2.html

and this list doesn't contain Time Crisis 3 US https://playstation.fandom.com/wiki/List_of_PlayStation_2_games_with_alternative_display_modes

So I'm going to say your problem is, the game doesn't.

**Comment by thatman84** [comment]
According to the old Nuvee plugin creator at least the PAL Dino Stalker has 480p
https://github.com/mirror/nuvee/blob/master/nuvee_ps2_usb%20-%20guncon2%2C%20keyboard%2C%20mouse/ps2_lightgun_list.txt

Page 10 of the NTSC Time Crisis 2 manual describes Progressive mode also.

**Comment by refractionpcsx2** [comment]
That Dino Stalker in the nuvee file is NTSC.

**Comment by thatman84** [comment]
> That Dino Stalker in the nuvee file is NTSC.

Sorry, on my phone now. It was Guncom2

**Comment by thatman84** [comment]
![Uploading 9FD34817-57C8-4863-8528-1A3F87E1BCD3.png…]()

**Comment by thatman84** [comment]
I’m happy to dig further into this over time, is there anything that would help you guys identify an issue IF there even is one?

logs/dumps etc?

**Comment by refractionpcsx2** [comment]
I can't find anything to confirm Time Crisis 2 actually has a progressive scan MODE, I think that document is just talking about progressive scan televisions, where it might adjust the aiming system to compensate.  The closest I can find online is some dude who used some converter to convert his interlaced signal to progressive with an additional box.

**Comment by thatman84** [comment]
Thanks for checking, I did find this old conversation about original hardware which does clear up most of my confusion. It’s fairly conclusive that the guns don’t really work in true “progressive scan mode” but there to work around progressive TV’s in a way I don’t really understand.

Apologise for the time wasting!

https://shmups.system11.org/viewtopic.php?f=6&t=62076
