### ISSUE TITLE
HLE Bios 

### ISSUE THREAD

**Issue by LasagnaPie** [PCSX2/pcsx2#87]
PCSX2 really needs a HLE Bios, not many people have the know how to dump their PS2's bios.

Play! and PCSX-R both feature an HLE Bios.

**Comment by fjtrujy** [comment]
Hello guys,
I would like to know if this is nowadays something possible to achieve?

To have an `HLE Bios` would be fantastic for the `PS2` Development. By doing this we could implement UnitTesting in the CI/CD for the `PS2` toolchain or whatever `PS2 Homebrew`.

I can put a scenario.
I'm one of the maintainers of the `PS2 Toolchain`, whenever we introduce a change we would like to test if this are still working as expected, this requires right now, to download the code, and execute locally that things works.

However, if we could execute it in the `PCSX2` we can integrate the testing during the CI/CD (using dockers) and detect the issue out of the box.

Thanks

**Comment by PaperVb64** [comment]
Fun Fact: I don't have a ps2 so screw pcsx2
