### ISSUE TITLE
[BUG]: Armored Core Last Raven - Broken Garage Transitions

### ISSUE THREAD

**Issue by forrvalhalla** [PCSX2/pcsx2#8700]
### Describe the Bug

In Armored Core Last Raven, the transition screen between entering and exiting the Garage menu is broken in HW mode.

In versions v1.7.4087 or older [(#8142)](https://github.com/PCSX2/pcsx2/pull/8142), the transition is still slightly broken, but _much_ less noticeable than it is now, with only one or two frames having a small glitched effect. 

### Reproduction Steps

1. Start a new game
2. Enter Garage and back out

### Expected Behavior

Menu transitions should cleanly fade between screens, like in SW.

### PCSX2 Revision

v1.7.4397 ([v1.7.4088](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.4088) or newer)

### Operating System

Windows 10 (64bit)

### CPU

i5-7600K

### GPU

GTX 1050ti

### GS Window Screenshots

Current PCSX2 versions -

https://user-images.githubusercontent.com/53349573/232947588-a484e000-f92c-4246-8b68-ef4a2dc62ebc.mp4

All PCSX2 versions before v1.7.4088 -

https://user-images.githubusercontent.com/53349573/232947930-54f3b365-08c2-4f3c-9a3f-a57ddac93e38.mp4

**Comment by forrvalhalla** [comment]
Can confirm, looks great now. Marking as fixed, thanks!

**Comment by Berylskid** [comment]
On v1.7.4653 (current latest version), this issue occurs only at entering Garage menu for the first time after booting game. Not sure which PR caused it at this moment.
