### ISSUE TITLE
[BUG]: Tom Clancy's Splinter Cell - Lighting Issue

### ISSUE THREAD

**Issue by BakerIsHungry** [PCSX2/pcsx2#8730]
### Describe the Bug

This issue was addressed in the wiki, but it seems the fix doesn't work anymore. In a lot of dark areas, Sam or other NPCs appear to be lit up as if they were beneath a light source despite being in complete darkness. I have attempted to fix it by doing what was described on the wiki, but it seems to not work in Nightly.

### Reproduction Steps

Play the game on any renderer with Blending set to Full is what's recommended, but has no effect now.

### Expected Behavior

Sam and other NPCs should be hidden in the darkness, requiring use of the iconic night vision goggles.

### PCSX2 Revision

1.7.4414.0

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i7-4790K CPU

### GPU

NVIDIA GeForce GTX TITAN X

### GS Settings

![splint1](https://user-images.githubusercontent.com/130881357/234136978-5615bc07-d73b-4731-882c-1bad6dbfd6a6.png)

### GS Window Screenshots

![splint2](https://user-images.githubusercontent.com/130881357/234137597-b011a601-d0f2-4d70-a10c-d7d34922bd2a.png)

**Comment by BakerIsHungry** [comment]
I'll get a log in just a moment.

**Comment by refractionpcsx2** [comment]
a GS Dump would be good, if you can

**Comment by BakerIsHungry** [comment]
Enable File Logging, right? It's been a while with MGS3 being my only other time doing this.

**Comment by refractionpcsx2** [comment]
That kinda log probably won't help, if you could just do Tools->Single Frame GS dump, then upload the files it puts in the `snaps` folder

**Comment by BakerIsHungry** [comment]
Okay. I'm on it.

**Comment by refractionpcsx2** [comment]
you may have to zip up the actual dump, github is fussy about file extensions :(

**Comment by BakerIsHungry** [comment]
Yeah, it's a bit picky. Here you go.
[Splinter Cell Lighting Bug.zip](https://github.com/PCSX2/pcsx2/files/11315343/Splinter.Cell.Lighting.Bug.zip)

**Comment by refractionpcsx2** [comment]
hmm, it looks fine here

![image](https://user-images.githubusercontent.com/6278726/234139291-933c09fa-c178-4a35-8d51-ccebafafa364.png)

even matching software when using Blending Accuracy of Maximum

![image](https://user-images.githubusercontent.com/6278726/234139331-a4761a7f-9cb4-474b-aca2-e2cfbc7dced3.png)


I would suggest maybe you've messed with a bunch of settings somewhere or something

**Comment by BakerIsHungry** [comment]
It seems to be fine when I get to a blackout, but I may be overthinking it. Might just be that they didn't get the lighting quite right in a few spots. It is an earlier game after all.

**Comment by BakerIsHungry** [comment]
My bad. I just needed to adjust the brightness.

**Comment by BakerIsHungry** [comment]
Maybe we could get a brightness adjustment slider in the future?

**Comment by RedDevilus** [comment]
There is shadeboost which has 50 as default so lowering it can reduce brightness for the 3 stats.

**Comment by BakerIsHungry** [comment]
thank you.

**Comment by BakerIsHungry** [comment]
Lowering it does make the game darker, but now the night vision seems to do nothing aside from show the light that's already there from any present light source. Weird.

**Comment by RedDevilus** [comment]
Though this is just a workaround to be fair, not a real fix if it's a regression or something that accidentally worked before.

**Comment by BakerIsHungry** [comment]
I'll just keep it closed for now because the brightness for these games do require manual TV adjustment.
