### ISSUE TITLE
[BUG]: Video Capture freezes Emulation on Zatch Bell: Mamodo Fury

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8731]
### Describe the Bug

Have Discord Running.
Watch a stream on Discord.
Start Zatch Bell: Mamodo Fury.
Initiate Video Capture mode.
Allow the game to play the opening cutscene without pressing anything until "Press Start" appears.
Continue pressing X through the menus to begin story mode on Normal.

Click Normal, and it will fade to black and never recover. It will indicate 60 FPS, but nothing will happen.

### Reproduction Steps

When I tried to reproduce, it reproduced while Discord was open and receiving streams (2/2). Note: The vulkan render chugs hard even with nothing else running during the opening cutscene.

When I tried to reproduce (closing all other graphics heavy programs) I couldn't reproduce anymore (0/4). As such I was unable to get a capture of the issue.

### PCSX2 Revision

1.7.4414

### Operating System

Windows 10 (64bit)

**Comment by Meerkov** [comment]
[Uploading Zatch Bell! Mamodo Fury_SLUS-21363_20230424185333.gs.zst.zip…]()
![Zatch Bell! Mamodo Fury_SLUS-21363_20230424185333](https://user-images.githubusercontent.com/8139496/234156681-32ff1116-9a98-46fb-970a-5b99d1717002.png)


Ok I was able to get it to freeze, but I had to play through the first battle and cutscene. Now it freezes up when transitioning to the second fight.

**Comment by stenzek** [comment]
Does the log say anything?

Due to the all the factors involved, I'm wondering if this is actually our bug.

**Comment by Meerkov** [comment]
Yes, I was able to get the bug to repro (slower) by removing other GPU intensive processes. I guess the log didn't upload properly.
[Zatch Bell! Mamodo Fury_SLUS-21363_20230424185333.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11316284/Zatch.Bell.Mamodo.Fury_SLUS-21363_20230424185333.gs.zst.zip)

**Comment by stenzek** [comment]
I'm talking about the emulator log.

**Comment by Meerkov** [comment]
Might be something weird about my settings. I'm happy to close this since it seems fickle.
