### ISSUE TITLE
[BUG]: App crashes upon selecting a network folder to scan on Linux

### ISSUE THREAD

**Issue by MwenDavo** [PCSX2/pcsx2#8740]
### Describe the Bug

Whenever I start the app and try to either load a game from a network storage (using SMB) or add the folder that contains all the games to the list, the app itself crashes. I'm on nightly v1.7.4414 on Manjaro, installed from flatpak. The remote folder is set up through GNOME's default file manager Nautilus.

As a side note, ticking "Enable system console" doesn't show the console either.

### Reproduction Steps

On a fresh Manjaro installation, install PCSX2 from Flatpak. Then, try to load a game or add a folder to the list of scannable directories, select the "Other locations" on the file explorer and connect to the remote storage. Upon selecting the folder or a game to run, the app will become unresponsive.

### Expected Behavior

The app should be able to scan correctly the folder and populate the list of games.

### PCSX2 Revision

v1.7.4414

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

**Comment by JordanTheToaster** [comment]
We don't support Flatpack please use the appimage before making issues.
