### ISSUE TITLE
WRC: World Rally Championship [SLUS-20419], [SCES-50139]

### ISSUE THREAD

**Issue by Yohokaru-96** [PCSX2/pcsx2#8741]
### Describe the Bug

Unexplicable slowdown during playthrough of WRC: World Rally Championship (both PAL & NTSC-U versions). Drops to 30-ish FPS, instead of stable 50/60 FPS.

### Reproduction Steps

Run the game, start World Rally Championship, issue appears in first stage of Monte Carlo Rally

### Expected Behavior

Stable performance, no sudden framedrops

### PCSX2 Revision

1.7.4418

### Operating System

Windows 11

### CPU

i5-7300HQ

### GPU

GTX 1050

### GS Settings

3x Resolution (1080p), Vulkan Renderer

### GS Window Screenshots

![World Rally Championship_SCES-50139_20230425220421](https://user-images.githubusercontent.com/54458215/234391040-4c367e35-847c-45ae-8dfd-804091a849f9.png)

**Comment by Mrlinkwii** [comment]
lower upscale if your having performance issues ,also this seems like a user issue
