### ISSUE TITLE
[BUG]: No QT platform plugin could be initialized

### ISSUE THREAD

**Issue by jrt05** [PCSX2/pcsx2#8742]
### Describe the Bug

After the latest update, pcsx2-qt failed with the error "This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

I did a re-install, and same error.

### Reproduction Steps

Install latest version and attempt to run

### PCSX2 Revision

pcsx2-v1.7.4422-windows-64bit-Qt

### Operating System

Windows 11

**Comment by takeshineale128** [comment]
have the same issue on Windows 11

**Comment by refractionpcsx2** [comment]
We're fully aware of the problem, I'm hoping it'll be fixed in the next release shortly, but don't know yet...

**Comment by Sector0666** [comment]
Thank you for the work around, can confirm they work :D .

**Comment by XxSYNDROIXxX** [comment]
> Thank you for the work around, can confirm they work :D .

Which file did you put them in?

**Comment by EdHerdman** [comment]
Just compare the files in a previous standalone build with the one that's missing the files: You'll see that they just go in the same directory as pcsx2-qt.exe.

**Comment by EdHerdman** [comment]
I tried to make my post clearer, but basically: Just drag these files into the directory where pcsx2-qt.exe is. It's that simple.

**Comment by takeshineale128** [comment]
thanks that fixed it

**Comment by XxSYNDROIXxX** [comment]
> I tried to make my post clearer, but basically: Just drag these files into the directory where pcsx2-qt.exe is. It's that simple. Just be sure to extract them from the qt6.5plugins.zip. You want the files inside that compressed file.

i got it thank you so much!

**Comment by MxNova** [comment]
Do I replace the existing files with these new files? Help please

**Comment by refractionpcsx2** [comment]
yes, replace the old files

**Comment by brunoruas2** [comment]
the workaround works to me too.

Thank you!

**Comment by refractionpcsx2** [comment]
Looks like it was a bug reported here: https://bugreports.qt.io/browse/QTBUG-112204

and was fixed for release 6.5.1, which I believe hasn't happened yet, so we kinda unknowingly ran in to this bug, so I'm trying to implement a workaround for now.

**Comment by Wangan0** [comment]
So the "QT platform bug" was pretty recent? I have the same problem, with Windows 11 as well. The files that refractionpcsx2 fixed the application. Thank you for that.

**Comment by refractionpcsx2** [comment]
This will be resolved with 1.7.4424 also.

**Comment by jrt05** [comment]
The latest build appears to have fixed the issue. Would you like me to mark this as closed?

**Comment by refractionpcsx2** [comment]
Please leave it open for 24 hours if you can, just in case anybody who
still has the issue comes by looking for a fix

**Comment by jrt05** [comment]
Latest build fixes the issue.

**Comment by MediaMaquina** [comment]
This again on 1.7.5116
