### ISSUE TITLE
[BUG]: Dark Cloud 2 - Texture Issue

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8770]
### Describe the Bug

![Dark Cloud 2_SCUS-97213_20230429150218](https://user-images.githubusercontent.com/8139496/235336555-0df0c85b-6813-406e-9f47-8e17886cf809.png)
![Dark Cloud 2_SCUS-97213_20230429153240](https://user-images.githubusercontent.com/8139496/235336558-c640826e-683a-4c2f-8ed3-59ee1243d85f.png)

Glitching textures (appear black, or glitched while playing).
[Dark Cloud 2_SCUS-97213_20230429150218.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11360615/Dark.Cloud.2_SCUS-97213_20230429150218.gs.zst.zip)

### Reproduction Steps

Play the game until you meet Donny. The clown also has broken textures when you see him in the 4th dungeon.

### PCSX2 Revision

1.7.4393

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by refractionpcsx2** [comment]
Can you please update your PCSX2 before making reports please? Thanks.

**Comment by Meerkov** [comment]
Do me a favor and just assume it's up to date. Sometimes I forget to check what the new number is. It's the most up to date version yesterday.

**Comment by Meerkov** [comment]
As an alternative to my suggestion, you could have the version number included in the GS dump filename, to avoid any confusion in the future.

**Comment by refractionpcsx2** [comment]
Okay, putting it on us for your inability to fill out the form correctly is not on. You're providing the bug report, please provide accurate information.  The names for GS Dumps are long enough as it is, and not really relevant to the dump itself, so that doesn't make sense.

**Comment by Jakey757** [comment]
I played with the dump a little, cpu sprite render size 8 or above in sprites/triangles or blended sprites/triangles mode returned the blackened areas back to normal (along with the existing automatic fixes).

**Comment by bigol83** [comment]
With gsdump played on 1.7.4970 it appears to be fixed.
