### ISSUE TITLE
[BUG]: Poinie's Poin [SCPS-15013] - Seizure Inducing Graphics post-FMV sequences

### ISSUE THREAD

**Issue by yellows111** [PCSX2/pcsx2#8772]
### Describe the Bug

A graphical glitch that ~~looks like an abstract shader~~ makes every frame drawn appear with a less-than-ideal motion blur-on-scanlines effect after having viewed a FMV cutscene, making the game hard to play by having fairly distracting flickering.

Attempting to actually play the game in this state would be a horrible fate, as every thing gets this large, dark border around it.

This does not capture in GSDumps, either single-frame or multi-frame.

My game.ini and pcsx2.ini were renamed for this report. Default settings were used.

### Reproduction Steps

Simply starting a new save file or loading a Clear!! save to start a post-game save will show this issue imminently past the first cutscene.

This does not happen if loading a save from past a FMV cutscene, however, even with that, there will eventually be a part of the game where you see an FMV cutscene. This causes the same effect that the New Game Intro FMV cutscene would do.

### Expected Behavior

Being able to see the game without my eyes being strained within the next few minutes. It's pretty bad.

### PCSX2 Revision

v1.7.4450

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 2700X

### GPU

GTX 1080 Ti (11GB)

### GS Settings

AFTER reporting the issues as-normal I have tested changing the Texture Inside RT option to Inside Target/1 and Merge Targets/2. Neither of which remedied the issue, leading to the same result as the Image and/or Video.

### Emulation Settings

MTVU has been disabled for reporting purposes. The issue persists with or without it enabled. 

### GS Window Screenshots

![Poinie's Poin_SCPS-15013_20230430200223](https://user-images.githubusercontent.com/25440281/235371595-54b40a47-9fe7-41ed-9200-9133b6c58a57.png)
Video (seizure warning):

https://user-images.githubusercontent.com/25440281/235371636-1d2cf08b-be16-4d23-b55c-79920cee61fc.mp4

### Logs & Dumps

(No visual issues recorded in GSDump, despite being taken in the effected frames) 
[Poinie's Poin_SCPS-15013_20230430200223.multiframe.gs.zst.gz](https://github.com/PCSX2/pcsx2/files/11362099/Poinie.s.Poin_SCPS-15013_20230430200223.gs.zst.gz)

**Comment by refractionpcsx2** [comment]
This will require booting the game to trigger, but the regression started in #8703

@stenzek some CBT for you
