### ISSUE TITLE
[Feature Request]: Adding a Command Line Arg for Resuming State

### ISSUE THREAD

**Issue by ripp3rdoc** [PCSX2/pcsx2#8773]
### Description

Adding a command line parameter (such as: `-resume`) to simply start the game with the last saved state. 

When closing the game from the emulator, it shows a prompt to save the state, which can be used if you started the game again, it will automatically resume from this last saved state. So a command line argument for it would be helpful.

### Reason

It would make it easier to start games from other programs, or make it integrates easier with other software (e.g. LaunchBox, RetroArch)

### Examples

`C:\pcsx2.exe -resume "PATH\TO\ROM"`

**Comment by refractionpcsx2** [comment]
What if you use

`C:\pcsx2.exe -state resume` ?

**Comment by refractionpcsx2** [comment]
Fixed my suggestion, needed to check further in to the code, I also tested this.

**Comment by ripp3rdoc** [comment]
> What if you use
> 
> `C:\pcsx2.exe -state -1 "PATH\TO\ROM"` ?

Yup, that worked just fine. Thanks!
