### ISSUE TITLE
Console Window Snap Alignment is Incorrect

### ISSUE THREAD

**Issue by UlsterRose** [PCSX2/pcsx2#878]
The console window snaps to the main window alright, but the alignment is incorrect (on Windows 8.1, at least.)
![misalign_snap](https://cloud.githubusercontent.com/assets/8225831/10286923/34f22038-6b88-11e5-82ad-7b785d74ecd0.png)

I haven't manually moved the console window; this is what it looks like as soon as you open PCSX2. It's petty, but it still looks a bit wonky.

**Comment by vsub** [comment]
It's not just Win8,it happens on WIn7 too

**Comment by refractionpcsx2** [comment]
Looks fine on windows 10 :/ I even tried detaching it and then moving the main window to cause it to snap.
![windowalign](https://cloud.githubusercontent.com/assets/6278726/10354152/550db5d4-6d55-11e5-9f22-ef1685af5a89.jpg)

**Comment by turtleli** [comment]
This could probably be fixed if someone counts how many pixels the console is offset by for each OS.

**Comment by MrCK1** [comment]
@UlsterRose Do you still get alignment issues here on 8.1? Win 10 is fine as Ref reported earlier.

**Comment by UlsterRose** [comment]
I've since moved to Windows 10, so I'm not sure about 8.1 right now.

**Comment by lightningterror** [comment]
The snap alignment has been fixed on 1.5 dev builds. 1.4 and 1.2.1 both experience the issue.

As for the spacing refraction mentioned I agree, plus there are more people that like it so let's leave it at that.

I'll be closing this one since the original issue has been solved.
