### ISSUE TITLE
DRAKENGARD 1 - VERSION PAL - AUTO SKIP CUTSCENES - PCSX2 -[BUG]: 

### ISSUE THREAD

**Issue by Madara011X** [PCSX2/pcsx2#8787]
### Describe the Bug

When i play the game drakengard in pcsx2 nightly v 1.7.4462 the gameplay is perfect but the video scene doesnt works, the cutscene show me a little by 2 seconds and after it dissapears and charge the gameplay, i try the iso game in the pcsx2 1.6.0 and the cutscenes appears.
I try change every item in settings in the emulator and nothing works.
Please help me, i dont know how to play this game in this emulator fine.
Thanks for read and help me

### Reproduction Steps

1. Download ISO Pal of drakengard 1 for spanish language
2. Open Emulator Nightly PCSX2 and the game
3. Try see the cutscenes

### Expected Behavior

I want to play this game in my language (spanish) with good gameplay and cutscenes

### PCSX2 Revision

v1.7.4462

### Operating System

Windows 10 (64bit)

### CPU

i5-8400

### GPU

GTX 1060 - 6GB

### GS Settings

I try this settings
https://docs.google.com/spreadsheets/d/1sC19l0htx0Qu2QE1CFta5R35iqPBN332dCHfTg1BGlQ/edit#gid=1169400806

**Comment by stenzek** [comment]
Sorry, we don't support piracy, doing so would put us at legal risk.
