### ISSUE TITLE
[Feature Request]: Сontinuation of the PR discussion about #8789

### ISSUE THREAD

**Issue by GermanAizek** [PCSX2/pcsx2#8790]
### Description

Continuation of the PR discussion https://github.com/PCSX2/pcsx2/pull/8789

@RedDevilus,
You forget about Android or ARM single-boarders, the processor is weaker there. Any optimization like this for such devices will be better.

### Reason

The reserve() function speeds up the insertion of elements into container, since we know in advance the number of elements we need.

### Examples

PR affects the frequently called iopMemReadString function

**Comment by RedDevilus** [comment]
PCSX2 isn't even on Android or ARM single-boarders. Did you even research what platforms PCSX2 is on?
