### ISSUE TITLE
[BUG]: Battlefield 2 Modern Combat - framebuffer glitches during cutscenes

### ISSUE THREAD

**Issue by navaronbracke** [PCSX2/pcsx2#8809]
### Describe the Bug

When playing in Battlefield 2: Modern Combat, using the hardware renderer (Vulkan), the screen partially flickers during cutscenes at the end of missions. This reproduces consistently, regardless if in fullscreen mode or not.

In the screenshot below you can see the issue: (screenshot taken from the cutscene in the mission `Top Man`)
1) The cutscene is displayed in the rectangle in the center
2) The black areas around the middle rectangle are expected, as the cutscene does not fill the screen
3) The smaller rectangle at the top is the bug. It also flickers in and out of existence very fast

![reproduction](https://user-images.githubusercontent.com/23480364/236643990-9cefc9cf-818a-4092-b515-d3a7e140b673.png)

### Reproduction Steps

- Start `Battlefield 2: Modern Combat`
- Play the mission `Headshot` (is the third mission in total and the first one with a cutscene at the end)
- When the mission ends the cutscene is played
- While playing the cutscene, a region in the top left flickers with a partial frame from when the mission itself ended
- The rect in which the cutscene itself is played has no issues rendering the cutscene itself

### Expected Behavior

The cutscene should play in the center of the screen, while the area around the cutscene stays black.

### PCSX2 Revision

v1.7.4477

### Operating System

Windows 10 (64bit)

### CPU

i7-4790

### GPU

GTX 1070

### Logs & Dumps

emulog.txt

```
[ 3009.0349] [GameDB] Searching for 'sles-53729' in GameDB
[ 3009.0351] [GameDB] Found 'sles-53729' in GameDB
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: autoFlush to [mode=2]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=2]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: texturePreloading to [mode=1]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: cpuCLUTRender to [mode=1]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: getSkipCount to [mode=19]
[ 3009.0351] [GameDB] Enabled GS Hardware Fix: beforeDraw to [mode=8]
[ 3010.8835] Applying settings...
[ 3010.9982] [GameDB] Searching for 'sles-53729' in GameDB
[ 3010.9985] [GameDB] Found 'sles-53729' in GameDB
[ 3010.9987] [GameDB] Enabled GS Hardware Fix: autoFlush to [mode=2]
[ 3010.9990] [GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=2]
[ 3010.9992] [GameDB] Enabled GS Hardware Fix: texturePreloading to [mode=1]
[ 3010.9992] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[ 3010.9992] [GameDB] Enabled GS Hardware Fix: cpuCLUTRender to [mode=1]
[ 3010.9995] [GameDB] Enabled GS Hardware Fix: getSkipCount to [mode=19]
[ 3010.9997] [GameDB] Enabled GS Hardware Fix: beforeDraw to [mode=8]
[ 3021.3825] Applying settings...
[ 3021.3833] [GameDB] Searching for 'sles-53729' in GameDB
[ 3021.3837] [GameDB] Found 'sles-53729' in GameDB
[ 3021.3840] [GameDB] Enabled GS Hardware Fix: autoFlush to [mode=2]
[ 3021.3842] [GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=2]
[ 3021.3842] [GameDB] Enabled GS Hardware Fix: texturePreloading to [mode=1]
[ 3021.3845] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[ 3021.3845] [GameDB] Enabled GS Hardware Fix: cpuCLUTRender to [mode=1]
[ 3021.3847] [GameDB] Enabled GS Hardware Fix: getSkipCount to [mode=19]
[ 3021.3847] [GameDB] Enabled GS Hardware Fix: beforeDraw to [mode=8]
[ 3036.7153] (VMManager) Resuming...
[ 3047.6081] microVU1: Cached Prog = [560] [PC=33e8] [List=02] (Cache=7.107%) [4.3mb]
[ 3121.5913] FMV started
[ 3121.7858] FMV ended
[ 3121.9399] FMV started
[ 3136.2915] FMV ended
[ 3159.7131] (VMManager) Pausing...
[ 3168.7656] Applying settings...
[ 3168.7666] [GameDB] Searching for 'sles-53729' in GameDB
[ 3168.7666] [GameDB] Found 'sles-53729' in GameDB
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: autoFlush to [mode=2]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: halfPixelOffset to [mode=2]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: texturePreloading to [mode=1]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: textureInsideRT to [mode=1]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: cpuCLUTRender to [mode=1]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: getSkipCount to [mode=19]
[ 3168.7666] [GameDB] Enabled GS Hardware Fix: beforeDraw to [mode=8]
[ 3169.9152] Applying settings...
```

**Comment by stenzek** [comment]
Could be the same as multiplayer mode, which is an utter d*ck and basically impossible to handle in the TC without a terrible amount of hacking.

**Comment by navaronbracke** [comment]
Well, the multiplayer mode in this game does not apply here because 
a) The game fails to find a network adapter when I select multiplayer in the game, so it does not work
b) The multiplayer servers are down since 2014 or so

I was also specifically referring to the singleplayer campaign in the OP.

I also wonder why it did work previously and now its broken.
Not sure what TC stands for?

**Comment by navaronbracke** [comment]
All I do know is that on March 21st this did work as expected. I had posted a comment in a Discord of mine indicating that _yet another_ bug was fixed in the nightly build from the day before.

That's all I have in terms of timeline though.

**Comment by stenzek** [comment]
If you can bisect it to a specific build we can investigate.

**Comment by navaronbracke** [comment]
I'll try to do that when I find some time for it.

I'll report back when done.

**Comment by OmegaGG** [comment]
Not super relevant but the Multiplayer portion of the game has been revived and will be accessible to all in a few days.
@stenzek You are right in that the rendering for the Singleplayer and Multiplayer portions of the game are different and indeed an utter d*ck.

Your fixes in: [](https://github.com/PCSX2/pcsx2/issues/1565#top)
#1565)

solved much of the HW emulation bugs in the singleplayer but broke the multiplayer rendering.

Using PCSX2 build V1.7.3699 w. Vulkan there is only minor rendering bugs (but a huge networking hit.)

I'll create a new issue number for the multiplayer specifically.

![](https://cdn.discordapp.com/attachments/361333674551148545/1105131443769852075/image.png)

![](https://cdn.discordapp.com/attachments/361333674551148545/1105130000216228041/image.png)

![](https://cdn.discordapp.com/attachments/361333674551148545/1105129474707701780/image.png)

I'll create a new issue for the Multiplayer portion specifically.

**Comment by stenzek** [comment]
> I'll create a new issue for the Multiplayer portion specifically.

Don't bother. I'll close it as a wontfix, like I said, the game's abusing the GS in an insufferable way.

**Comment by navaronbracke** [comment]
@stenzek Managed to set things up locally, so I can start bisecting this. Will report back when I'm done with it

**Comment by navaronbracke** [comment]
@stenzek I cannot reproduce this bug with v1.7.4736 anymore. Seems that a patch fixed it along the way.
