### ISSUE TITLE
[BUG]: Vulkan Vsync having problems in Need for Speed Underground

### ISSUE THREAD

**Issue by madruded** [PCSX2/pcsx2#8812]
### Describe the Bug

Game: "Need for Speed Underground (NTSC/U)", when activating the fullscreen mode using Vulkan engine with Vsync on, the game runs extremely slow.

Disabling the Vsync option and setting it to fullscreen, the game runs normally, without slowdowns. But the screen tearing is annoying.

I tested the game on the Directx 11 engine, and it worked perfectly with Vsync active in full screen. I think it's some problem affecting Vsync+Vulkan

### Reproduction Steps

Graphic Settings -> Vulkan engine active, Vsync active -> I turn on fullscreen mode -> the slowdown comes in the game

### Expected Behavior

I wanted the game to run at its normal speed in fullscreen with these options enabled.

### PCSX2 Revision

PCSX2 Nightly v1.7.4480

### Operating System

Windows 11

### CPU

AMD Ryzen 5 4600G

### GPU

AMD Radeon Vega 7 (integrated with processor)

### GS Settings

I´m using the default option

### Emulation Settings

Default options

**Comment by refractionpcsx2** [comment]
That's because your GPU is struggling.  I recommend you get support on the forum or discord.

**Comment by madruded** [comment]
It´s not a GPU problem!

**Comment by refractionpcsx2** [comment]
dude, you have onboard graphics ,they are not strong. Plus you're not the first person we've had complain that things slow down when they go full screen on week hardware.

**Comment by oilbugxx** [comment]
> dude, you have onboard graphics ,they are not strong. Plus you're not the first person we've had complain that things slow down when they go full screen on weak hardware.

wait, is it true? i basically know nothing about technical shit, but i do have my msi overlay showing me that gpu is not even reached 50%. mine is 5600g igpu, its not quite 1:1 with op hardware but pretty close if its gpu. the weird thing is they are stable on either 30 or 60fps on certain scene.

**Comment by stenzek** [comment]
GPU usage is misleading. 30fps games tend to have one heavy frame, one light frame, because most of the draw calls happen in one 16ms/60fps period. If the GPU doesn't finish everything in that 16ms, and you have vsync on, it pauses until the next 16ms period, doing nothing, sitting idle for up to 16ms. Then the light frame gets rendered in the third 16ms period.

When the average is computed by the active time over the last second, of course it's not going to show 100%, because of the idle time. Doesn't mean that your GPU being too slow isn't causing dropped frames.

Enabling Skip Presenting Duplicate Frames will try to combine the "heavy" and "light" frames together, and can help on weaker systems, but then you end up with inconsistent frame pacing. Pick your poison.

**Comment by oilbugxx** [comment]
> GPU usage is misleading. 30fps games tend to have one heavy frame, one light frame, because most of the draw calls happen in one 16ms/60fps period. If the GPU doesn't finish everything in that 16ms, and you have vsync on, it pauses until the next 16ms period, doing nothing, sitting idle for up to 16ms. Then the light frame gets rendered in the third 16ms period.
> 
> When the average "GPU Usage" is computed by the active time over the last second, of course it's not going to show 100%, because of the idle time. Doesn't mean that your GPU being too slow isn't causing dropped frames.
> 
> Enabling Skip Presenting Duplicate Frames will try to combine the "heavy" and "light" frames together, and can help on weaker systems, but then you end up with inconsistent frame pacing. Pick your poison.

wow stenzek himself. sorry for the late reply i wasnt aware of my inbox before. 
aah, i think i kinda understand that. yeah that sucks. i only play rpg stuff with this pc so, it almost always fine with its framerate. but then when trying nfs most wanted it suddenly running like what op described. the think is like op said too, the directx11 run the game normally with the same condition, so this is something that you cant do anything about it then? or is this like the limitation of vulkan backend at the moment? hopefully the latter

thankyou for answering
