### ISSUE TITLE
Recommended CRC hack level GSDX HW

### ISSUE THREAD

**Issue by willkuer** [PCSX2/pcsx2#882]
Current implementation of CRC hack levels has the problem that the default/recommended CRC hack levels are different for different renderers. I would suggest to add another level called 'recommended' or 'automatic' which selects the appropriate CRC hack level for OGL ('Partial') and Dx9/11 ('Full') on configload.

I think this should increase usability and is more or less cheap to implement. If you consider this to be a reasonable extension I could try to do that by myself. (Probably one of the devs only needs 10 minutes so you can do it as well by your own.)

**Comment by willkuer** [comment]
My idea would be to add another element into the first position of the crc hack combobox. The saved value would be the itemposition-1. Like that all settings are compatible to old versions and 'automatic' would get the magic number -1, which seems to me appropriate. On getconfig(CRC level) the recommended level would be selected.

What do you think?

**Comment by willkuer** [comment]
Finished it in #62ba3fc

**Comment by gregory38** [comment]
Is it done? Could it be closed?

**Comment by willkuer** [comment]
It's not done and requires #1018 to fulfill the original idea.

**Comment by willkuer** [comment]
I close it for the moment. There seems not too much interest in the forum for such a function. It would be good though. Maybe I will find time later to do it.
