### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Danke-Boi** [PCSX2/pcsx2#8820]
### Description

In GT4, and in several other games, HW readbacks kill performance, and I would a like the option to disable them. I can emulate GT4 at 4k all day, with near maximum settings, but the second a readback starts, the framerate drops to roughly 60-70% speed. This may exist on Windows builds, but on MacOS, I cannot find it in any panel, even after checking multiple forum posts and the wiki. If it doesn't, I would appreciate this feature, even if it causes graphical issues. And, it probably should be under the "advanced" tab.

### Reason

I want to be able to complete the licenses in GT4, as the ones on a full track have issues working. Night tracks also have issues. The drag strip is unusable. This is on the M1, with no other programs open.
This would allow a compromise between graphical fidelity and playability. 

### Examples

I saw in previous posts in the forums that PCSX2 had this feature already, but those may be outdated, or just non-existent with MacOS using the Metal renderer.

**Comment by RedDevilus** [comment]
Should be here in per-game settings:
![image](https://github.com/PCSX2/pcsx2/assets/24227051/6351cb6e-39a0-4635-8114-2c212cfbabee)

Keep in mind you will delete legit effects for performance if you adjust this.

**Comment by Danke-Boi** [comment]
> Should be here in per-game settings Hardware Download Mode: ![image](https://user-images.githubusercontent.com/24227051/237480175-6351cb6e-39a0-4635-8114-2c212cfbabee.png)
> 
> Keep in mind you will delete legit effects for performance if you adjust this.

It isn't there

**Comment by Danke-Boi** [comment]
<img width="1440" alt="Screenshot 2023-05-10 at 3 06 09 PM" src="https://github.com/PCSX2/pcsx2/assets/72051710/5fb1cfb7-e9c9-4d4b-a75a-765813f463be">

**Comment by refractionpcsx2** [comment]
You're looking in the global settings, not per game, highlight one of your games and go to its properties.

**Comment by Danke-Boi** [comment]
@

> You're looking in the global settings, not per game, highlight one of your games and go to its properties.

I see it now, but why exactly isn't it in the global settings? The game specific settings by default use the general settings, but it's not in general settings. The forum posts I found all didn't mention that, and it seems illogical.

**Comment by refractionpcsx2** [comment]
It's not in global settings to stop people turning it on for everything and coming to us complaining half their games don't work properly.
