### ISSUE TITLE
[BUG]: Hitman Contracts hangs when loading Asylum Aftermath from memcard

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#8830]
### Describe the Bug

When loading the Asylum Aftermath level from a memcard, Hitman Contracts is hanging with a DMA error.

### Reproduction Steps

Launch game and load Asylum Aftermath from attached memcard

### Expected Behavior

Game should not hang

### PCSX2 Revision

v1.7.4490

### Operating System

Windows 11

### CPU

Ryzen 7900X

### GPU

RTX 4090

### GS Settings

Defaults

### Emulation Settings

Defaults, widescreen patches disabled

### Logs & Dumps

Emulog: [emulog.txt](https://github.com/PCSX2/pcsx2/files/11456900/emulog.txt)

Memory card: [HitmanContracts.zip](https://github.com/PCSX2/pcsx2/files/11456930/HitmanContracts.zip)

**Comment by MBeeBR** [comment]
I just discovered this same bug, put it to save and got stuck on this screen:
![unknown_2023 08 28-11 38_1](https://github.com/PCSX2/pcsx2/assets/136722551/47721c5a-e6a3-4358-8a88-e9cd375452b3)

**Comment by Mbee2** [comment]
something went right, I managed to save to the memory card without the entire game crashing this time
https://github.com/PCSX2/pcsx2/assets/136722551/adb7ba79-7a81-41d1-9e5c-cebed1269421

in one of the frames this messy image also appears
![vlcsnap-2024-01-13-17h49m28s588](https://github.com/PCSX2/pcsx2/assets/136722551/f1f61a3f-63e4-4870-97c8-bd78c3be047a)

**Comment by refractionpcsx2** [comment]
Hitman games are broken in hardware mode, so I'm not surprised.

Considering this complete, thanks for letting us know.
