### ISSUE TITLE
OpenGL regression in Kingdom Hearts - texture glitch caused by AF

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#884]
I'm seeing a weird glitch on the wall and floor textures: Some black lines are showing up when using the OpenGL renderer. FYI the lines are much thicker and more noticeable on native resolution. This does not happen when using the software renderer or the Direct3D11 renderer. I call it a regression because it also doesn't happen in the (much) older 1.3.0-882 build.

Build: PCSX2 1.3.1-1232
Renderer: OpenGL
Internal Resolution: 6x Native
Blending Unit Accuracy: High

CPU: Intel Core i5-4670K @ 4.10 GHz
GPU: AMD HD 7950 w/Boost @ 1000 MHz (core) / 1250 MHz (memory)

Here's a video of the problem:
https://www.youtube.com/watch?v=hr5n-FtnqOs

P.S. I included the video so you could see the slowdown that happens when the camera moves to show the windows. Is that normal? More info in the second paragraph of the video description.

**Comment by yorkiesandskittles** [comment]
Do you have Anisotropic Filtering enabled?

On Wed, Oct 7, 2015 at 10:43 PM, Jaime J. Denizard <notifications@github.com

**Comment by karasuhebi** [comment]
The problem is Anisotropic Filtering. Thanks for helping me narrow that down @yorkiesandskittles!

**Comment by karasuhebi** [comment]
BTW this Anisotropic Filtering glitch can be seen in other games. Look at the water:
![](http://i.imgur.com/Za9tyEP.png)

**Comment by gregory38** [comment]
Hum, I think I know the issue. AF is enabled for "shader SW" texturing whereas is must only be enabled when texturing is fully done in HW. Dx uses HW unit in wrong situation which creates others issue in normal mode.

**Comment by refractionpcsx2** [comment]
That bug with the blue lady having a chunk chopped out of her  headdress/white thing when the colour comes in is really annoying me now.. lol

**Comment by karasuhebi** [comment]
@gregory38 Good to hear you might know the issue. This can only mean good things. :D Good luck fixing it! ^_^

@refractionpcsx2 lol as it should. The Final Fantasy logos are usually some of the most beautiful artwork Amano does for the games. This Yuna one is actually one of my favorites.

**Comment by gregory38** [comment]
Could you test the PR?

**Comment by bositman** [comment]
Seems fixed here, good job

**Comment by karasuhebi** [comment]
@gregory38 thanks for the fix! Works great on my end. Confirmed that it was fixed in both FFX and KH.

What about the slowdown that happens when the camera moves to show the windows? Is that normal? There's more info on it on the second paragraph of the video description. If it isn't normal, let me know so I can file a separate Issue for it.
