### ISSUE TITLE
[Feature Request]: 60Hz mode for PAL games

### ISSUE THREAD

**Issue by Serie9** [PCSX2/pcsx2#8850]
### Description

Most PAL games luckily come with a 50 Hz and 60Hz selection screen, however this isn't true for all PAL games.

Some are only available in 50Hz.

For those games a "PAL to NTSC/60Hz" mode would be really nice to have.

### Reason

Smoother gameplay.

Fixes the "teleport"-like skipping effect on 60Hz FMVs that are played in 50Hz mode.

As most PAL games are multilingual, this will allow players to play their favourite games in their native language at the original 60Hz the game was designed at.

### Examples

Duckstation (PS1 Emulator) has a "Force NTSC Timings 60hz-on-PAL" toggle in the Enhancements menu.

It works fine with most games, except for those that have the games speed tied to the FPS.

Those few games run faster overall, the music will be played faster, the movment and animations are faster than intended, rather than maintaining the original speed. (when compared to the NTSC version of those games)

However, the majority of the PS1 games work well with this setting, allowing for NTSC FPS while playing, which introduces a wonderful smooth gameplay experience compared to PAL.

**Comment by refractionpcsx2** [comment]
You can already do this, you will need to enable advanced from under the tools. menu

![image](https://github.com/PCSX2/pcsx2/assets/6278726/182c69f6-ec7a-43b7-940a-4a0c91f3bde4)

I don't really want to add further hacks.  I would recommend doing this per game maybe so you don't break everything.
