### ISSUE TITLE
[BUG]: PCSX2 Modern Gui Settings Menu Issue

### ISSUE THREAD

**Issue by shinra358** [PCSX2/pcsx2#8855]
### Describe the Bug

Settings menu is too big for the screen if your screen rez is 720p. You cannot choose save at the bottom right hand side to save settings because it is offscreen. You also cannot resize the windows because instead of resizing, it moves the menu offscreen so you can't access it at all.

### Reproduction Steps

Open a settings menu in 720p resolution

Attempt to resize a settings menu

### Expected Behavior

To be able to resize the settings menus to fit onscreen so that one can access all of the options

### PCSX2 Revision

Latest dev version as of date this post was posted

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Won't fix. You're going to have this issue in plenty of applications in 2023.

Using big picture mode is an option.
