### ISSUE TITLE
[BUG]: GTA III Bright windows very noticeable flickering in hardware renderers.

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#8858]
### Describe the Bug

During night time ingame bright windows flicker like crazy in hardware renderers. There is very little flickering in software rendering,too, but that is actually how the game behaves in real hardware too, tested it few days ago. 

The difference in number of flickering windows between software and hardware renderers is noticeable though, it's actually distracting in hardware renderers. 

It happens in Native resolution too, so it's not an upscaling issue. 

### Reproduction Steps

Go ingame, wait for night time, look at the windows on palaces, bright windows should flicker like crazy when using hardware renderer.

### Expected Behavior

Software renderer light flickering is accurate to Ps2 hardware, that's how it should be. 

### PCSX2 Revision

pcsx2 1.7.4508

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### GS Settings

Native resolution, default settings. 

### Emulation Settings

Default.

### GS Window Screenshots

![Grand Theft Auto III_SLES-50330_20230514123029](https://github.com/PCSX2/pcsx2/assets/38129260/984324ae-ad7c-4f0f-a0af-ee359b20cb37)

### Logs & Dumps

[Grand Theft Auto III_SLES-50330_20230514123029.zip](https://github.com/PCSX2/pcsx2/files/11471710/Grand.Theft.Auto.III_SLES-50330_20230514123029.zip)

Videos showing the difference between Software and hardware renderers, both at Native resolution. 

Software renderer

https://github.com/PCSX2/pcsx2/assets/38129260/eb89d6d9-aaa5-4442-b47d-bf2ae398edbd

Hardware renderer

https://github.com/PCSX2/pcsx2/assets/38129260/b379ded6-7c4d-4fc1-b686-8ad5448fe07e

**Comment by lightningterror** [comment]
Closing in favor of #3692
