### ISSUE TITLE
[BUG]: Formula One 2003 Demo Graphics Issue

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#8866]
### Describe the Bug

Significant graphical issue that makes the game virtually unplayable.
This happens on Software Mode & have tested on Vulkan, DX11, DX12.

Screenshots & GS dump provided below:

### Reproduction Steps

*Start the game
*Choose your language
*Arcade Race
You will notice the issue immediately.

### Expected Behavior

No graphical problems.

### PCSX2 Revision

v1.7.4515

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Native settings

### GS Window Screenshots

![Bonus Demo 6_SCED-52390_20230516180932](https://github.com/PCSX2/pcsx2/assets/116039192/4bf2aac6-c67a-4068-9019-b79a48d32f3a)
![Bonus Demo 6_SCED-52390_20230516180935](https://github.com/PCSX2/pcsx2/assets/116039192/72dd701e-433a-4173-a9a4-93702676969d)
![Bonus Demo 6_SCED-52390_20230516181004](https://github.com/PCSX2/pcsx2/assets/116039192/8a976cc2-6114-4803-b892-ed70b4fd988f)

### Logs & Dumps

[Bonus Demo 6_SCED-52390_20230516181004.zip](https://github.com/PCSX2/pcsx2/files/11490363/Bonus.Demo.6_SCED-52390_20230516181004.zip)

**Comment by Mrlinkwii** [comment]
this  looks from a demo disc  , which mean you have to enable game fixed manually  , you need     - XGKickHack

**Comment by Mrlinkwii** [comment]
@StillPlay2 its per game only under game fixes

**Comment by Mrlinkwii** [comment]
ohh yeah you need  to enable the advanced settings , tools > advanced settings

**Comment by Mrlinkwii** [comment]
just to notice that may  break other games on the demo disc @StillPlay2

**Comment by refractionpcsx2** [comment]
Changed my mind :P We can add this to the gamedb, the xgkick sync hack is actually correct behaviour and should be harmless.
