### ISSUE TITLE
Ace Combat 5 NTSC-Japan Fixes

### ISSUE THREAD

**Issue by jcdenton2k** [PCSX2/pcsx2#888]
Current Source:
http://forums.pcsx2.net/Thread-Porting-fixes-of-Ace-Combat-games-NTSC-U-to-NTSC-J

Original Source:
http://forums.pcsx2.net/Thread-How-find-the-address-of-patches-Ace-Combat-5-NTSC-J

Can the below be merged into the GameDatabase file so that the fixes are updated automatically for this game?  Thanks!

[patches = 86089F31]
comment=Rearranging COP2 instructions that use old results

patch=0,EE,001A3B6C,word,48498800
patch=0,EE,001A3B70,word,4B00682C
patch=0,EE,001A3B7C,word,484A8800
patch=0,EE,001A3B80,word,4B0C682C

[/patches]

**Comment by mirhl** [comment]
You can find every explanation [here](https://code.google.com/p/pcsx2/source/detail?r=5737) and in [this](http://forums.pcsx2.net/Thread-Ace-Combat-5-is-still-not-playable-on-0-9-8?pid=323128#pid323128) thread.

**Comment by jcdenton2k** [comment]
You could've just said 'already fixed' and closed the issue, but sure. :P

**Comment by mirhl** [comment]
I just replied to you, if it was you
> I'm not aware how mebius1 found the correct address

But I don't think any of the NTSC-J ace combat games is fixed.
