### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Dradyoz** [PCSX2/pcsx2#8880]
### Describe the Bug

Nightly - whilst I can select 2 players utilising Guncon for player 1 and 2, both are still picking as one gun - tested with sinden and gun4ir.  This also feels like it needs demulshooter to able to deliniate between the two devices.

### Reproduction Steps

Controller player 1 and 2 setup - guncon - setup picks up what appears to be different guns, but looking and playing games its combined still :(

### Expected Behavior

Two Gun4IR lightguns should operate fully separate to each other.  Version 1.6 with Nuvee patch does this, this version still doesnt.

### PCSX2 Revision

Latest Nightly 1.7.4520

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
this is covered by the pull request #8437
but also the feature request of https://github.com/PCSX2/pcsx2/issues/7888
