### ISSUE TITLE
[Feature Request]: Read texture pack in zip format.

### ISSUE THREAD

**Issue by CristobalManga** [PCSX2/pcsx2#8881]
### Description

I Download a Pack of textures for the game GTA San Andreas. The pack came compressed in a zip format with a size of 700MB.
But unzipped it was 4GB.
The images that came inside the texture pack were in .dds format, I had never heard of that before.
I wonder if it is possible to implement the reading of textures through a zip file, just like the PPSSPP emulator that has it implemented and according to what I read, the reading of textures can be faster when it is compressed, since the processor processes it faster although I don't know the subject.

### Reason

This significantly benefits the size of texture packs.

### Examples

PPSSPP emulator

**Comment by stenzek** [comment]
1. We don't support distribution of texture packs, it could be argued to be piracy.
2. DDS textures are already compressed, limiting the benefit of further compression. PNG even further so.

**Comment by TellowKrinkle** [comment]
In my experience, dds textures do compress pretty well.

On the other hand, a lot of filesystems have compression built in.  Can you compress the files with https://github.com/Freaky/Compactor and see how close you get to the size of the zip?  If it's pretty close, I doubt we need zip support.

**Comment by stenzek** [comment]
> In my experience, dds textures do compress pretty well.

You'll still get repeated data, yeah. Hence why I said "limiting", not "negating" :)

It wouldn't even be _that_ complex to add, but I don't want to encourage piracy.

**Comment by CristobalManga** [comment]
> In my experience, dds textures do compress pretty well.
> 
> On the other hand, a lot of filesystems have compression built in. Can you compress the files with https://github.com/Freaky/Compactor and see how close you get to the size of the zip? If it's pretty close, I doubt we need zip support.

That tool that you mentioned really helped me a lot, now the textures folder has a weight of 1.5 GB, and the zip of 700mb.
