### ISSUE TITLE
[BUG]: Radiata broken shadows in certain areas of the game

### ISSUE THREAD

**Issue by BParks21** [PCSX2/pcsx2#8883]
### Describe the Bug

Some shadows are broken in parts of the game. Target Partial Invalidation use to fix the issue now nothing seems to fix it. 

### Reproduction Steps

Start a new game and watch the camera pan by the fire place and observe the shadows. Or try the save state and gs dump. 

### Expected Behavior

Shadows should look fine like they always use to. 

### PCSX2 Revision

1.7.4521

### Operating System

Windows 11

### CPU

i7 8086k

### GPU

Nvidia GTX 1080ti

### GS Settings

Deafault

### Emulation Settings

Default

### GS Window Screenshots

![Screenshot (116)](https://github.com/PCSX2/pcsx2/assets/12180630/ada19075-a85a-4029-9ca1-6fa6c93c1712)
![Screenshot (115)](https://github.com/PCSX2/pcsx2/assets/12180630/224757b1-ea85-48d8-a769-168aebce067e)

### Logs & Dumps

[Dump.zip](https://github.com/PCSX2/pcsx2/files/11524071/Dump.zip)

[SLUS-21262 (47B9B2FD).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/11524072/SLUS-21262.47B9B2FD.01.p2s.zip)

**Comment by refractionpcsx2** [comment]
"The game", can you be more specific in your information please.

**Comment by BParks21** [comment]
Yeah mb I corrected it pretty quickly I'm just super sleepy atm.

**Comment by refractionpcsx2** [comment]
Partial Target Invalidation seems to fix it, can you try more of the game with that enabled?

![image](https://github.com/PCSX2/pcsx2/assets/6278726/a1cb342d-4004-4b02-80a3-c65407d1906a)

**Comment by BParks21** [comment]
Doesn't fix it for me. Did you load the state or the dump?

**Comment by refractionpcsx2** [comment]
I used the dump, I don't have the game.

**Comment by BParks21** [comment]
How do you load the dumps again? Maybe it's not showing with the dump I forgot how to load them haha.......

**Comment by refractionpcsx2** [comment]
Start File then select the dump

**Comment by BParks21** [comment]
Ok

**Comment by refractionpcsx2** [comment]
can you do a longer GS Dump? Ctrl+Shift+F8 I think is the default for a multiframe dump, just hold it down for a few frames while the glitch is happening (maybe do it with partial invalidation on if that reduces how bad it is), then release the buttons when you're done.

**Comment by BParks21** [comment]
Yeah I'll do it later today.

**Comment by BParks21** [comment]
Here ya go I can confirm it shows up in the multi frame dump

https://drive.google.com/file/d/1U7SiOCS3ca3iNmt3hMXJeicEonPRut3d/view?usp=sharing

**Comment by BParks21** [comment]
Seems fixed!

**Comment by refractionpcsx2** [comment]
on the PR? yeah :P

But let's leave this open until that merges.
