### ISSUE TITLE
[Feature Request]: UI toggle for BIOS `print (0x75)` syscall message logging

### ISSUE THREAD

**Issue by abelbriggs1** [PCSX2/pcsx2#8886]
### Description

In #2558 and #2865, a feature was added to the PCSX2 logging system which logs the output of `syscall 0x75` to the system console.

This feature is toggled by `SysConsole.sysoutConsole.Enabled` and defaults to `false`, but there currently doesn't seem to be a code path which allows a user to enable it via the UI.

### Reason

The BIOS print logging itself is quite useful for reverse engineering, since it allows hackers to re-implement printf calls which were stubbed out by the developers in the original binary, or otherwise may not function correctly in all cases (DECI, for instance).

### Examples

I know the QT rewrite is ongoing, and many of the legacy logging options haven't been re-introduced yet. I'm not sure of the best way to add this one myself.

I have a working branch which modifies `LogSink.cpp` and couples `sysoutConsole.Enabled` to the EE console conditional, such that enabling debug EE console also enables the print syscall logging:

![image](https://github.com/PCSX2/pcsx2/assets/27463243/145c1200-a5ec-433b-a980-432fa25b980f)

Another option could be to add a new option in this list, but since BIOS print logging is fairly niche (and a no-op in most use cases), a separate option might be unnecessary.

**Comment by F0bes** [comment]
I'm not opposed to bunching the syscall to the EE logging.
If you'd like you can create a PR with the changes. Just prefix the commit with something like `QT/Logging`
