### ISSUE TITLE
[BUG]: Automatic Transmission bug in Gran Turismo 4

### ISSUE THREAD

**Issue by AquaSoma** [PCSX2/pcsx2#8903]
### Describe the Bug

The bug is that when the transmission is set to automatic, it fails to shift up a gear and you have to shift up manually although it has no problems down shifting. I'm unsure of what cars this bug affects (bro there's more than 700 cars in this game, i don't have time for that) but ive noticed it happen with some of the JGTC cars and the F1 car. Video below shows this bug in action.

https://youtu.be/4Rs1mgZ4td8

### Reproduction Steps

Take the formula gran turismo car into any track and just drive around the track for a bit with the transmission set to automatic

### Expected Behavior

automatic transmission should shift gears automatically

### PCSX2 Revision

v1.7.4534

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 5600G

### GPU

ASRock RX 6600 XT Challenger Pro OC

### GS Settings

![GS Settings](https://github.com/PCSX2/pcsx2/assets/134675195/e023c408-ead9-41b5-89b1-9cdb65499fe7)

### Emulation Settings

![Emulation Settings](https://github.com/PCSX2/pcsx2/assets/134675195/8d28d1f3-0f7a-4144-87d8-6db7ec08e65d)

**Comment by stenzek** [comment]
You're using cheats. That could be why.

**Comment by AquaSoma** [comment]
> You're using cheats. That could be why.

I'll check if that affects it

**Comment by refractionpcsx2** [comment]
Just be sure to do a clean boot to make sure the patches aren't loaded, using a savestate can result in keeping the modified data.

**Comment by AquaSoma** [comment]
Okay so unchecking the enable cheats box does affect it (idk how, someone explain pls) and it reduces the bug occurrence by a lot although just through some quick testing, the bug does still persist.

**Comment by AquaSoma** [comment]
ignore that, i literally made an account just to post this issue

**Comment by refractionpcsx2** [comment]
did you do a fresh boot after unticking cheats?

**Comment by AquaSoma** [comment]
I always do a fresh boot, i don't use the save state feature

**Comment by refractionpcsx2** [comment]
excellent, thanks :) so is there an easy way to reproduce this? can you provide a memory card?

**Comment by AquaSoma** [comment]
I'll have to continue this thread later just cause I got work.

**Comment by refractionpcsx2** [comment]
No problem, when you get chance

**Comment by TransparentBlue** [comment]
GT4 has that thing where holding the gear up / down button will prevent automatic gear changes, it might be possible that your controller is broken to some degree and registering enough of a press on a trigger to activate that effect (or a bug is making the game think a very low press is enough) .
You might wanna check if the bug still happen if you put gear up/down on digital buttons

**Comment by AquaSoma** [comment]
Okay i did a quick test and i think you might be right blue, im using one of those PowerA xbox wired controllers although im not holding down the trigger buttons at all when in a race. I did change the upshift and downshift controls to N/A and that seems to fix it. Might be a sensitivity thing.

**Comment by stenzek** [comment]
Working as intended then.

**Comment by AquaSoma** [comment]
Got there in the end
