### ISSUE TITLE
[BUG]: Emulator hangs when loading a save state while video capture is running occasionally

### ISSUE THREAD

**Issue by monster860** [PCSX2/pcsx2#8904]
### Describe the Bug

While video capture is running, loading a save state will occasionally cause a hang - the emulation will simply stop, and none of the pause/reset/shutdown commands will work at all, and the only way to get out of this state is to close the emulator and restart it. This doesn't happen every time but it happens pretty often.

### Reproduction Steps

1. Start a video capture
2. Make a save state
3. Load the save state (you'll have to do this a few times, doesn't happen every time)
4. Watch as it hangs

### PCSX2 Revision

v1.7.4534

### Operating System

Windows 10 (64bit)

### CPU

Intel i5-7600K

### GPU

Nvidia GTX 1060, 6GB

**Comment by Mrlinkwii** [comment]
Can I have a crash dump file when pcsx2 hangs ? To do so  open task explorer  right click pcsx2 and choose create dump file when pcsx2 hangs

**Comment by monster860** [comment]
> Can I have a crash dump file when pcsx2 hangs ? To do so open task explorer right click pcsx2 and choose create dump file when pcsx2 hangs

https://cdn.discordapp.com/attachments/517785193365504020/1111863194064003133/pcsx2.zip
