### ISSUE TITLE
[BUG]: Misaligned lights in Urban Chaos: Riot Response

### ISSUE THREAD

**Issue by Swordman14** [PCSX2/pcsx2#8907]
### Describe the Bug

I found a misaligned light in Native ps2 resolution. Gets fixed in software mode
![image](https://github.com/PCSX2/pcsx2/assets/87284261/7f44b328-d64c-40d3-b3f9-dfe96c570f23)

### Reproduction Steps

I dont know if there is more. Thats the first one i found. Its in the mission of Webster Street. I could attach a save state if asked

### PCSX2 Revision

PCSX2 Nightly - v1.7.4537

### Operating System

Windows 10 (64bit)

### CPU

i3 9100f

### GPU

rx 550 4gb

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/87284261/3de2a119-869a-44c1-9368-ac473d430215)
![image](https://github.com/PCSX2/pcsx2/assets/87284261/773a1efb-879d-4081-b326-e289c3d81953)

![image](https://github.com/PCSX2/pcsx2/assets/87284261/a043ba26-c916-49cc-8433-93d01c4620cc)

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/87284261/ed60fc6c-55d8-48c3-8661-dce0d8a3b45e)

**Comment by Mrlinkwii** [comment]
can i have a gs dump?

**Comment by Swordman14** [comment]
[Urban Chaos - Riot Response_SLUS-21390_20230527183854.zip](https://github.com/PCSX2/pcsx2/files/11583067/Urban.Chaos.-.Riot.Response_SLUS-21390_20230527183854.zip)
Is this what you want? Im not vey familiar with how to create a dump

**Comment by refractionpcsx2** [comment]
The missing ingredient is Autoflush, however when you upscale, that offsets it in a different direction, with the only solution being Half Pixel Offset Normal (Vertex), buuuuut that causes a horrible amount of edge glow. 

So definitely in terms of upscaling there's no great solution, but we can correct it for native resolution.
