### ISSUE TITLE
[BUG]: FullScreenMode bug

### ISSUE THREAD

**Issue by madafak4** [PCSX2/pcsx2#8909]
### Describe the Bug

I have a problem to select the resolution at which I want to emulate the games, when I want to select the "Fullscreen Mode" option, no other option appears other than "Borderless Fullscreen" and nothing more than that option, not even another resolution. Please, if anyone knows how to solve this problem, it would be very helpful.

![image](https://github.com/PCSX2/pcsx2/assets/86552558/8d5870fa-9fcd-4980-8901-41824dc33174) (image)

### Reproduction Steps

Since I downloaded the emulator it was like this

### PCSX2 Revision

v1.7.4537

### Operating System

Windows 10 (64bit)

### CPU

Ryzen  3 3200g 

### GPU

Vega 8 Graphics

**Comment by JordanTheToaster** [comment]
That's expected you'll only get options on DX11 and DX12.

**Comment by stenzek** [comment]
Not a bug. Exclusive fullscreen mode switching only exists in DirectX.
