### ISSUE TITLE
[BUG]: Regression: Onimusha Warlords FMV artifacting caused by #8865

### ISSUE THREAD

**Issue by shinra-electric** [PCSX2/pcsx2#8916]
### Describe the Bug

Intro FMV in Onimusha Warlords (SLUS-20018) has graphical artifacts. 

Last working build: v1.7.4518
First broken build: v1.7.4519

Caused by #8865

### Reproduction Steps

Start the game

### Expected Behavior

Clear FMV

### PCSX2 Revision

v1.7.4519 and later

### Operating System

macOS 13 (Ventura)

### CPU

M1 Pro

### GPU

M1 Pro

### GS Window Screenshots

v1.7.4518 (Working):
<img width="1218" alt="Screenshot 2023-05-29 at 18 12 05" src="https://github.com/PCSX2/pcsx2/assets/50119606/f949c51b-283e-4316-8689-0dd758522b5e">

v1.7.4519 (Broken):
<img width="1218" alt="Screenshot 2023-05-29 at 18 11 09" src="https://github.com/PCSX2/pcsx2/assets/50119606/317efde1-ecad-4edd-b15a-1321b5fedf4a">

### Logs & Dumps

[Onimusha - Warlords_SLUS-20018_FMV_bug.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11593057/Onimusha.-.Warlords_SLUS-20018_FMV_bug.gs.zst.zip)

**Comment by refractionpcsx2** [comment]
Oh I didn't realise I needed to add the SW switch to the US version too, we'll do that. (I guess all versions)
