### ISSUE TITLE
[BUG]: NTSC release of Jonny Moseley Mad Trix has broken FMVs in hardware mode (not #6636)

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#8922]
### Describe the Bug

In issue #6636 it was established that Jonny Moseley Mad Trix needs deinterlacing in order for its FMVs to not render as flashy and garbled.  However, sometime recently, likely within the past few weeks, something broke them and no longer play on any renderer other than software, and none of the deinterlacing settings fix it this time - you just get a black screen with the audio.  Something to note is that if you disable deinterlacing, it does render, but all garbled as shown in #6636.  Also, the PAL release of the game which runs at 50 FPS (if that matters) is unaffected by this issue.

### Reproduction Steps

- Set renderer to any of the Hardware renderers
- Enable any of the deinterlacing options except for None
- Boot the game

### Expected Behavior

Assuming deinterlacing is enabled, FMVs should render properly with no visual errors.

### PCSX2 Revision

v1.7.4546

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K

### GPU

NVIDIA RTX 2080 SUPER

### GS Window Screenshots

NTSC release's FMVs, hardware rendering, deinterlacing enabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/3f2e6752-8cc6-4c98-8f4c-5d7d0c31b11c)

NTSC release's FMVs, hardware rendering, deinterlacing disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/baf234e4-1d0b-4282-86fb-23f79dee22e7)

NTSC release's FMVs, software rendering, deinterlacing enabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/055cb2d9-92dc-474c-a136-96383c8fc1ae)

NTSC release's FMVs, software rendering, deinterlacing disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/c57b629e-b38c-459c-8581-b8cf5356de3c)

PAL release's FMVs, hardware rendering, deinterlacing enabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/69a67453-1a1b-4e02-b640-076d537c8ac7)

PAL release's FMVs, hardware rendering, deinterlacing disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/d7bcb0a3-8df3-4c87-bfd2-5f2babd1418c)

PAL release's FMVs, software rendering, deinterlacing enabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/f3923338-29b5-424d-8bcb-bd62c71ebc92)

PAL release's FMVs, software rendering, deinterlacing disabled:
![Capture](https://github.com/PCSX2/pcsx2/assets/58268914/94eba84b-2959-425a-bbe3-b0361c7bab82)

**Comment by refractionpcsx2** [comment]
Seems to work with a toggle to software and back again, no flashing, but yeah this needs looking in to, it must be doing something to confuse PCSX2. 

I just took a GS Dump and it does a memory clear of 512x1217 (very weird number, but sure) but I think because Z isn't masked (even though it's not in the same area), we don't catch it and avoid it.

I guess one thing we could do, instead of saying "oh you need Z? go on then", is to drop that back down to the software renderer (like we do already) and make sure we invalidate the Z too.

**Comment by refractionpcsx2** [comment]
Okay so this turns out to be an absolute mess of recursive drawing on itself and copying stuff around, which is basically just going to be ridiculous to get to work right, so we're just gonna add the SoftwareFMV switch to the game.
