### ISSUE TITLE
[Feature Request]: Allow PCSX2 to load custom textures from nested folders

### ISSUE THREAD

**Issue by vcx33** [PCSX2/pcsx2#8925]
### Description

Allow PCSX2 to load textures from various directories inside the replacements folder.

### Reason

This would make sharing and sorting custom textures a lot more convenient and easier, since most games have thousands of them.

### Examples

PPSSPP does this, it also allows custom textures to be loaded from a zipped file which allows for better performance.

**Comment by refractionpcsx2** [comment]
Pretty sure it already does?

**Comment by vcx33** [comment]
ah yes, you are correct i'll just close this.
