### ISSUE TITLE
[Feature Request]: Automatic GAMEDB fixes for Fifa Street 2

### ISSUE THREAD

**Issue by Lunafet** [PCSX2/pcsx2#8926]
### Description

I don't know if this is the right place to request this or even if you guys accept this type of suggestions but there are 2 fixes that make Fifa Street 2 Run perfectly which is:

 Enabling Frame Buffer Conversion: Fixes the ground textures for many maps
 EE Cycle Rate 300% [overclock]: Fixes artifacts on team flags
 
 Credits to [zBlake]

### Reason

It would be awesome if this could be implemented to make things easier for people new to emulation, and i would say that the fix for the ground textures is a must to make the game actually playable

### Examples

![FIFA3](https://github.com/PCSX2/pcsx2/assets/72381365/a351a91e-bd9c-4e77-b78b-6acec841eec1)

**Comment by Mrlinkwii** [comment]
EE Cycle Rate 300 cant be added to the gamedb , but is noted on the wiki/ other issues about this game

**Comment by refractionpcsx2** [comment]
You can add the EE Cycle rate change in your per game settings, but we can add the Frame Buffer Conversion, do you have an example of what that does?

**Comment by Lunafet** [comment]
The Frame Buffer Conversion supposedly fixes the textures on the floor, i've seen it before but i can't reproduce it anymore for some reason, tried disabling and enabling both of the settings listed and nothing changed

The EE Cycle Rate fix still works though, but apparently it can't be added right?

**Comment by Mrlinkwii** [comment]
game seems fine on v1.7.4549 with 300% overclock
![image](https://github.com/PCSX2/pcsx2/assets/17685135/afa92959-fe12-4db3-82f0-12d536de3084)

**Comment by lightningterror** [comment]
> Enabling Frame Buffer Conversion: Fixes the ground textures for many maps

It's an upscaling issue, 8bit shader will break if you use decimal upscaling like 1.25.
Also FBC hack is awful and shouldn't be added here.

**Comment by stenzek** [comment]
Indeed, fractional scaling can cause issues with palette conversion.

If it's fine at integer scale, then it definitely shouldn't be added. If it's not, upload a dump and I can take a look - I'd prefer to avoid adding that hack if possible, it's terrible and reads back (slow).
