### ISSUE TITLE
[Feature Request]: icon for when custom HD textures are detected?

### ISSUE THREAD

**Issue by Dorkrex** [PCSX2/pcsx2#8930]
### Description

well, lots of people have been busy personally making custom upscaled texture packs for PS2 games since that feature was enabled a few months back, but it's impossible to tell at a glance which games have upscaled textures enabled and detected, so maybe, from the game browser view, a little icon in the upper right of the game cover that says "HD" or has the little "HD" logo turned on, so you can quickly tell which games' have custom textures enabled and detected? the logo could be anything really, but it would be really useful IMO. 

### Reason

i have custom HD upscaled textures for 112 PS2 games (and counting) at the moment and it's a bit annoying to bounce back and forth between the emulator and the textures folder to check which ones worked, which ones didn't, and there's no real way to sort between the games with working/downloaded HD upscaled textures or not

sometimes the problem is only that the folder for the textures was named for a different region's GAMEID of the same game, or something similarly minor. 

it would also just help keep track at a glance from the game browser list as to which games you actually have, have custom textures downloaded for, and properly named the folder so as to actually be picked up by PCSX2, or when downloading many texture packs at once, or redownloading an update of a certain texture pack and maybe the name was changed of the folder accidentally, etc etc. 

### Examples

![image](https://github.com/PCSX2/pcsx2/assets/135386244/a903b437-3283-42ea-a929-edfe991680fa)

This is what the textures folder I have looks like atm. As you can tell, it's annoying to have to check that I haven't accidentally downloaded any specific texture pack twice, it's not particularly easy to keep organized on the PCSX2 side of things either. It can get messy very quickly... 

And there's just no easy way to tell until you go through and boot up every single game individually, one-by-one, that you've done it right and the emulator sees them correctly, you remembered to enable "custom textures" for that game, etc. etc.

**Comment by stenzek** [comment]
Nope. Scanner has no idea about texture replacements.

> This is what the textures folder I have looks like atm. As you can tell, it's annoying to have to check that I haven't accidentally downloaded any specific texture pack twice, it's not particularly easy to keep organized on the PCSX2 side of things either. It can get messy very quickly...

If those texture packs are derivative works of the original, that's piracy and we want nothing to do with it.
