### ISSUE TITLE
[BUG]: Force feedback when rotating the wheel only works with Driving Force selected as the emulated wheel in Enthusia Professional Racing

### ISSUE THREAD

**Issue by Lassii-** [PCSX2/pcsx2#8935]
### Describe the Bug

The force feedback effects of the wheel having a counter force and fighting back while turning only work when the basic Driving Force wheel is selected as the emulated device. When changing to Driving Force Pro (no difference between normal and rev11.02) or GT Force, the effects cease to function when turning the wheel. Other effects (like shaking when hitting a wall) seem to work no matter what is selected.

The wheel gets correctly detected as either Driving Force or Driving Force Pro in-game depending what you set PCSX2 to emulate so I think this is a PCSX2 bug as they both should have FFB available in same manner.

### Reproduction Steps

1. Configure a wheel (in my case Logitech G27) to be Driving Force Pro in PCSX2
2. Start the game, the wheel does the FFB initialization (rotating full 900 degrees before the Konami logo but after that the wheel is like there's no FFB at all when turning it

When you configure the wheel to be plain Driving Force, the FFB effects work as expected after the FFB initialization. I included some misc logs and possibly interesting things below in the logs section.

### Expected Behavior

The FFB effects working like they do with Driving Force (i.e. you can instantly feel the wheel resisting when turning after the FFB initialization.)

As as sidenote, I saw in another FFB related issue ticket that the developers and testers have no wheel setups available. I'm willing to help debug & fix this issue if that's possible somehow. Let me know if there's some logs or whatever else I could include in this ticket to help diagnosing.

### PCSX2 Revision

v1.7.4550

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 9 5950X

### GPU

Radeon RX6800

### GS Settings

I've done the testing with all settings on default just in case.

### Emulation Settings

I've done the testing with all settings on default just in case.

### Logs & Dumps

**lsusb**
`Bus 001 Device 014: ID 046d:c29b Logitech, Inc. G27 Racing Wheel`

**dmesg when plugging the wheel in**
```
[ 8093.557598] usb 1-4: new full-speed USB device number 16 using xhci_hcd
[ 8093.930286] usb 1-4: New USB device found, idVendor=046d, idProduct=c29b, bcdDevice=12.39
[ 8093.930291] usb 1-4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 8093.930293] usb 1-4: Product: G27 Racing Wheel
[ 8093.965148] input: G27 Racing Wheel as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-4/1-4:1.0/0003:046D:C29B.0011/input/input37
[ 8093.965228] logitech 0003:046D:C29B.0011: input,hidraw0: USB HID v1.11 Joystick [G27 Racing Wheel] on usb-0000:02:00.0-4/input0
[ 8093.965279] logitech 0003:046D:C29B.0011: Force feedback support for Logitech Gaming Wheels
```
**PCSX2 log when started with the wheel connected and configured, not sure if important**
```
[    0,4748] (SDLInputSource) Joystick 0 inserted
[    0,5263] (SDLInputSource) Controller 0 (joystick 0) returned player ID -1, which is invalid or in use. Using ID 0 instead.
[    0,5263] (SDLInputSource) Opened joystick 0 (instance id 0, player id 0): G27 Racing Wheel
[    0,5264] (SDLInputSource) Failed to create haptic left/right effect: Haptic: Effect not supported by haptic device.
[    0,5264] (SDLInputSource) No haptic rumble supported: Haptic: Effect not supported by haptic device.
[    0,5264] (SDLInputSource) Rumble is not supported on 'G27 Racing Wheel'
```
**PCSX2 log when starting the game with G27 configured as Driving Force Pro**
```
[    2,7670] (USB) Creating a Wheel Device in port 1
[    2,7670] (SDLFFDevice) Spring effect is not supported on 'SDL-0'
[    2,7670] (SDLFFDevice) Damper effect is not supported on 'SDL-0'
[    2,7670] (SDLFFDevice) Friction effect is not supported on 'SDL-0'
```
These lines about different effects not being supported do not appear when configured as Driving Force. I know for a fact that these effects are supported by G27 itself.

**Comment by stenzek** [comment]
What's supported (or not) by SDL is out of our control.

It's possible that the other wheel types use a different protocol for FFB, and it's not getting parsed correctly. But same as I've said in the other threads, nothing we can do about it, because none of us have the hardware.

**Comment by 7e3J4y** [comment]
I've been following issues regarding bad force feedback wheel support since the plugin system got axed and rewrote, eagerly awaiting the day this miraculously gets fixed. I see you guys closing all the issues stating "we don't have the hardware so there's nothing we can do," but OP asked how they could help as a person that _actually owns the hardware,_ and this question seems to fall on deaf ears.

Can you **please** shed _any_ information here about what users with this hardware can do to help solve this issue?
