### ISSUE TITLE
[BUG]:REGRESSION: Final Fantasy X glitched screen shatter effect 

### ISSUE THREAD

**Issue by vcx33** [PCSX2/pcsx2#8936]
### Describe the Bug

The screen shatter effect used when starting a battle turns black instead of having a screenshot of the viewport, this issue happens at random with no consistent way of reproducing it.
This issue only happens in Hardware Mode.

![Final Fantasy X International_SLPS-25088_20230604173231](https://github.com/PCSX2/pcsx2/assets/118646244/0a86d5dc-bb49-4311-b117-883576e4f53a)

CORRECT EFFECT:
![Final Fantasy X International_SLPS-25088_20230604173317](https://github.com/PCSX2/pcsx2/assets/118646244/64a49aa4-1b63-40c0-b5da-db8b321e8243)

GS DUMP: 
[Final Fantasy X International_SLPS-25088_20230604173231.gs.zip](https://github.com/PCSX2/pcsx2/files/11646153/Final.Fantasy.X.International_SLPS-25088_20230604173231.gs.zip)

### Reproduction Steps

Run around and trigger a battle

### PCSX2 Revision

v1.7.4550

### Operating System

Linux (64bit) - Specify distro below

### CPU

i7-4700

### GPU

GTX 1080

**Comment by refractionpcsx2** [comment]
How annoying, unfortunately GS Dump won't help as it's a readback issue, it's already gone wrong by the time the GS dump is taken (but you can't capture this anyway)

a savestate might be useful, just before you get in to a fight

**Comment by vcx33** [comment]
[SLPS-25088 (658597E2).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/11646239/SLPS-25088.658597E2.01.p2s.zip)
Here you go, i've been trying to trigger the glitch for a while and it never comes up now.

**Comment by refractionpcsx2** [comment]
Well that's frustrating :(  Just to rule it out, you didn't have Disable HW Readbacks enabled, did you?

**Comment by vcx33** [comment]
no, its set to accurate.

**Comment by lightningterror** [comment]
Do we know which build introduced the issue, if not @vcx33 can you narrow it down?

**Comment by stenzek** [comment]
Can't reproduce either.

Coincidentally, I *do* get the black transition if I ignore readbacks. So possibly user error, or cheats, who knows what else causing issues.
