### ISSUE TITLE
[BUG]: Cannot compile on Fedora 38

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#8938]
### Describe the Bug

Make or Ninja fails at the end with error saying:

"/usr/bin/ld: /usr/lib64/libc4core.so.0.1.11: error adding symbols: DSO missing from command line"

### Reproduction Steps

Follow the compiling instructions on Wiki page.

### Expected Behavior

Successful release build.

### PCSX2 Revision

Latest

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Fedora 38

**Comment by Mrlinkwii** [comment]
dose the appimage work?

**Comment by weirdbeardgame** [comment]
A quick seach reveals, https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line Meaning its not found the lib to link against.

Do you have c4core installed? `dnf install c4core-devel`

**Comment by YukiXXL** [comment]
> dose the appimage work?

Yes but I need Dev9 capabilities. Flatpak doesn't work even with the "setcap" code.

> A quick seach reveals, https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line Meaning its not found the lib to link against.

Do you have c4core installed? dnf install c4core-devel

Yes. Both i386 and x86_64.

**Comment by weirdbeardgame** [comment]
Why both?

**Comment by stenzek** [comment]
Stop trying to using system packages.

**Comment by YukiXXL** [comment]
> why both?

it fails on cmake without it. library missing error.

**Comment by YukiXXL** [comment]
> Stop trying to use system packages.

Then how should I compile it?

**Comment by weirdbeardgame** [comment]
So is this a 32 bit install? Or is this 64 bit

**Comment by YukiXXL** [comment]
> So is this a 32 bit install? Or is this 64 bit

64 bit

**Comment by TellowKrinkle** [comment]
c4core is a dependency of rapidyaml, which seems to love making breaking changes, making it a terrible package to try to use a system version of
I'd recommend trying to use the cmake flag `-DUSE_SYSTEM_RYML=OFF` to ignore the system installed copy, and use the bundled one

**Comment by YukiXXL** [comment]
it feels pointless to discuss about the issue unless somebody else here test aswell. like this, it would just be going nowhere.

**Comment by weirdbeardgame** [comment]
It has been tested in fedora. Got another guy who did the same thing you did. I'd try what Tellow said

**Comment by YukiXXL** [comment]
> c4core is a dependency of rapidyaml, which seems to love making breaking changes, making it a terrible package to try to use a system version of I'd recommend trying to use the cmake flag `-DUSE_SYSTEM_RYML=OFF` to ignore the system installed copy, and use the bundled one

so should I keep the i386 packages?

**Comment by weirdbeardgame** [comment]
No remove that entirely

**Comment by TellowKrinkle** [comment]
> so should I keep the i386 packages?

Since it should ignore the system package, it shouldn't matter.  If it makes a difference, that's a bug in someone's cmake file somewhere

BTW, just curious, if you do `file /usr/lib64/libc4core.so.0.1.11`, what does it print?

**Comment by YukiXXL** [comment]
/usr/lib64/libc4core.so.0.1.11: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=301604d3b84422d8a7a6c5914bb740748f636b1d, stripped

**Comment by YukiXXL** [comment]
> c4core is a dependency of rapidyaml, which seems to love making breaking changes, making it a terrible package to try to use a system version of I'd recommend trying to use the cmake flag `-DUSE_SYSTEM_RYML=OFF` to ignore the system installed copy, and use the bundled one

That actually worked. Thank you.

**Comment by TellowKrinkle** [comment]
Okay, looking at some info on "error adding symbols: DSO missing from command line", it's apparently the most confusing error message ever
"\<library>: error adding symbols: DSO missing from command line" means "Some other library needs symbols from \<library>, but \<library> was missing from the linker arguments".  There should have been a previous error message saying what symbol in what file was actually missing.

(If you're not interested in figuring out why your system rapidyaml isn't working with our build system, that's fine too, just keep using `-DUSE_SYSTEM_RYML=OFF` in that case)

**Comment by stenzek** [comment]
IMO we should just disable using system ryml by default. Anyone foolish enough to force it can deal with the consequences.
