### ISSUE TITLE
[Feature Request]: bring back forcefeedback gain multiplier

### ISSUE THREAD

**Issue by vichentem** [PCSX2/pcsx2#8952]
### Description

yeah so in older versions it was present.

### Reason

it enchances the experience by a lot, also i think that it may be fairly simple, because the code was merged from the old one right (?).

and

i miss it :(

### Examples

![image](https://github.com/PCSX2/pcsx2/assets/109481945/b167d73b-761e-41ae-9d39-f7ed3504242f)

**Comment by stenzek** [comment]
Not possible, SDL's gain already defaults to maximum. Unless you wanted to reduce it. But it's not supported by all devices anyway.

See SDL source: https://github.com/libsdl-org/SDL/blob/320f3fffbe06f4c412f5e62427812167b5bfffe3/src/haptic/SDL_haptic.c#L147-L150

> also i think that it may be fairly simple, because the code was merged from the old one right (?).

No, it was a near complete rewrite.
