### ISSUE TITLE
[BUG]: xbox game bar does not work with vulkan render on windows 11

### ISSUE THREAD

**Issue by soredake** [PCSX2/pcsx2#8957]
### Describe the Bug

With pcsx2+vulkan render and game booted when i press "win+g" nothing happens, xbox game bar is not shown (while it does with d3d11/d3d12 backends).

### Reproduction Steps

1) Have radeon gpu (not sure if this matters) and windows 11 pro.
2) Install latest build of pcsx2.
3) Select vulkan as renderer.
4) Boot any game.
5) Enter fullscreen.
6) Press "win+g".
7) Xbox game bar is not shown.

### Expected Behavior

Xbox game bar is shown, like with d3d11/12 renderers.

### PCSX2 Revision

1.7.4563

### Operating System

Windows 11

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/11713002/emulog.txt)

**Comment by refractionpcsx2** [comment]
```Vulkan and OpenGL Support
In many cases Xbox Game Bar cannot be shown when a game uses or Vulkan or OpenGL in full-screen mode. Vulkan or OpenGL games should use a "windowed" mode that shows a desktop-owned window border.```

https://learn.microsoft.com/en-us/gaming/game-bar/known-issues

**Comment by soredake** [comment]
That's sad considering vulkan is selected by default for and "borderless fullscreen" is already the default for vulkan.

**Comment by refractionpcsx2** [comment]
Sounds like it doesn't really work with vulkan properly, so nothing we can really do.

**Comment by soredake** [comment]
@refractionpcsx2 with yuzu+vulkan game bar is works, so it can be made to work.

**Comment by refractionpcsx2** [comment]
why do you need the game bar anyways? we have built in recording features

**Comment by soredake** [comment]
Should this issue be closed if it *can* be made to work? Especially closed as "completed" when nothing is done.

**Comment by refractionpcsx2** [comment]
I mean, Microsoft themselves say it may or may not work, if they aren't sure it should work, how can you expect us to make it work? if Microsoft make it 100% compatible with Vulkan, then we might be interested in looking in to it, but while they're basically saying "it sometimes works if you're lucky", I'm not going to waste my time and I don't really expect anybody else to. 

You're welcome to look in to it yourself if you wish. We will happily accept pull requests.

**Comment by soredake** [comment]
Okay, can you close this as "not planned/wontfix"?

**Comment by refractionpcsx2** [comment]
There, that's the only flag we have for it.  As I say, if you want to do video recording we have the capability internal to the emulator, you don't need the game bar.

if you don't have them already you will need these files: https://www.duckstation.org/upload/ffmpeg-dlls.zip
