### ISSUE TITLE
[Feature Request]: Add "New Game Mode" to retroachievements settings (that is the name in retroarch at least)

### ISSUE THREAD

**Issue by Elolawyn** [PCSX2/pcsx2#8958]
### Description

It is a setting available in retroarch that makes you elegible for all achievements in a game even though you have unlocked them already.

### Reason

Quality of life. It allows you to show achievement popup while making videos for youtube even after you have the achievement, or to check if another region iso seems to be working when you already have that achievement unlocked.

### Examples

- Login in PCSX2 retroachievements settings menu.
- Play a game normally, earning some achievements and then stop playing.
- Go back to retroachievements settings menu and activate "New Game Mode".
- Start the game again.
- A popup saying "All x achievements are active this session" appears.
- All achievements works so emulator shows popup about achievement earned even though you previously earned it.
- All non earned achievements are unlocked as normal when conditions are met (this setting does not affect this).

**Comment by refractionpcsx2** [comment]
Can you not just enable Test Mode?

**Comment by Elolawyn** [comment]
Yeah but with this mode, since achievements are working as usual and you can unlock them like usual you can just activate this option and forget about it.

**Comment by refractionpcsx2** [comment]
You can set test mode and forget about it.

I'm not exactly sure what you're wanting beyond this.  It sounds like you're not concerned about tracking your progress and you plan on killing it every time you load the game, so Test Mode being enabled should do exactly what you need.

**Comment by stenzek** [comment]
-1 as well, this is literally what test mode does (minus the uploading of not-unlocked achievements).

Using RA as justification is generally not a good idea, considering the fact that it's known for terrible UX (and abuse/license violation, but that's a separate issue).
