### ISSUE TITLE
[BUG]: Incorrect game title for SLPM-65501

### ISSUE THREAD

**Issue by qpwakaba** [PCSX2/pcsx2#8959]
### Describe the Bug

In PCSX2, the title of SLPM-65501 is displayed as Onimusha [Mega Hits!]. The correct code for Ominusha [Mega Hits!] is his SLPM-6**6**501 ([see wiki](https://wiki.pcsx2.net/Onimusha:_Warlords)).
The correct title for SLPM-6**5**501 is ["Frogger Rescue" or "Frogger's Adventures: The Rescue"](https://wiki.pcsx2.net/Frogger%27s_Adventures:_The_Rescue), and the region is NTSC-J

### Reproduction Steps

* Import Frogger's Adventures: The Rescue and see the list of games

### PCSX2 Revision

v1.7.4568

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment]
should be fixed with #8962 , after its merged all you need to do is rescan your games and it should be fine
