### ISSUE TITLE
[BUG]: Atelier Iris Eternal Mana widescreen pacthes dont work anymoe

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8965]
### Describe the Bug

It was working in a version 1 week ago . Wide screen patches.

### Reproduction Steps

Enable widescreen patches nothing happens

### Expected Behavior

Works

### PCSX2 Revision

174570

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
what is the CRC and serial for the game?

**Comment by Mrlinkwii** [comment]
@ISuckGood are you self compiling or using nightly releases ?

**Comment by ISuckGood** [comment]
I use nightly release. 
CRC and serial are E3981DBB and SLUS-21113

**Comment by refractionpcsx2** [comment]
Should be fixed in the next release, if you can't wait, grab the patches.zip from here https://github.com/PCSX2/pcsx2_patches/releases
replace the one in your `resources` folder

**Comment by ISuckGood** [comment]
Thanx but i already finished the game . I only had to fight the last boss ... Well it kinda sucked the image was small but WCYD . Its a free sofware .  Thank you anyway.
