### ISSUE TITLE
[BUG]: Dragon Ball Z Budokai Tenkaichi 3 - "1P VS 2P" greyed out

### ISSUE THREAD

**Issue by NeganLovesLoot** [PCSX2/pcsx2#8981]
### Describe the Bug

Whenever you choose duel the "1P VS 2P" is greyed out.

### Reproduction Steps

Go through the menus until you can choose duel. After chooshing duel youll see the option is greyed out., 

### Expected Behavior

Usually the option is not greyed out and you can play two player.

### PCSX2 Revision

 v1.7.4576

### Operating System

Windows 11

### CPU

AMD Ryzen 9 5900X 12-Core Processor

### GPU

NVIDIA GeForce RTX 3080

**Comment by AmyRoxwell** [comment]
You need to setup the second controller to make it work, if you dont have anything then the game will not let you , also, any screenshots?

**Comment by stenzek** [comment]
User error.

Please use the discord server for support, rather than assuming that it is a bug and opening an issue in the future, thanks.
