### ISSUE TITLE
[Feature Request]: PS2 immersive sound

### ISSUE THREAD

**Issue by MBeeBR** [PCSX2/pcsx2#8988]
### Description

here is a small suggestion, as we know the only physical part of the playstation 2 that emits mechanical sound is the Memory Card, so I recorded this sound from my console, check the result.

### Reason

it could be included in the emulator for a greater immersion.

### Examples

https://github.com/PCSX2/pcsx2/assets/136722551/09136571-1786-402a-b6aa-e1129d1823b4

**Comment by stenzek** [comment]
Sorry, that's a bit out of scope for us. You're welcome to implement it yourself, but sound effects when clicking on things tends to irritate users.
