### ISSUE TITLE
[GSDX] Sprite Scaling Problem

### ISSUE THREAD

**Issue by SnowRay** [PCSX2/pcsx2#900]
So, many games have problem with correct effect alignment when scaling, but ther is something else. Some effects become "multiplicated". For example in DMC3:

Native:
![dmc3_01](https://cloud.githubusercontent.com/assets/15099225/10561824/c4bfab0c-7544-11e5-9c92-7f88a1a84569.jpg)

Scaling 6x:
![dmc3_02](https://cloud.githubusercontent.com/assets/15099225/10561826/d351b07a-7544-11e5-85d0-e50a1345a5b2.jpg)

Notice the sawtooth effect. Tried half-pixel offset and round sprite hack without much luck.

**Comment by mirhl** [comment]
Did you try also *align sprite* and *sprite* (every combination possibly)?

**Comment by SnowRay** [comment]
Yeah, align sprite don't have any effect whatsoever and with other hacks there is slight difference, but main problem remains.

**Comment by mirhl** [comment]
I guess gregory would love you to attach a gs dump (shift + F8)

**Comment by SnowRay** [comment]
No prob, will do.

Hmm, I'm somewhat lost my save for DMC3, but I have one for Silent Hill 3, same problem, hope it won't be to scary to check out :)

Native:
![01](https://cloud.githubusercontent.com/assets/15099225/10567306/cb6a8caa-7608-11e5-9707-a7a9af75e9fb.jpg)

Scaling 6x:
![02](https://cloud.githubusercontent.com/assets/15099225/10567309/dc72ac4e-7608-11e5-9717-57d972e2d9c9.jpg)

GS dump:
https://drive.google.com/open?id=0B0-mO4UdUc6icUR1bFNBWGMyUzg

And noise filter working now, great job!

**Comment by gregory38** [comment]
Do you have the issue on 2x/3x?

**Comment by refractionpcsx2** [comment]
Also try the half pixel offset hack, that can sometimes align the lighting effects (GoW and Shadow of Colossus lighting effects are fixed by this afaik)

**Comment by SnowRay** [comment]
Yes, it starting to become apparent even on 2x although not as noticeable. Half pixel offset does not affect it in any way unfortunately, in SH3 and DMC3 it just adds glitches of its own.

**Comment by mirh** [comment]
Does this improve with 4effc70792d387189b7e7cb4c2cce12ead75b6de?

**Comment by SnowRay** [comment]
Hmm, so how can I test this, with which settings?

**Comment by refractionpcsx2** [comment]
Just use OpenGL with the same settings as before, you can grab a build from the buildbot http://buildbot.orphis.net/pcsx2/

**Comment by gregory38** [comment]
Don't bother. It won't work better unfortunately.

**Comment by SnowRay** [comment]
Yeah, no luck, there is still great deal of doubling in all affected games
