### ISSUE TITLE
[Feature Request]: Save the cover download link after pasting.

### ISSUE THREAD

**Issue by SlimDread** [PCSX2/pcsx2#9001]
### Description

Save the cover download link after pasting it in the "Download Covers" window instead of erasing it after closing.

### Reason

A bit more convenient.

### Examples

Save the link after closing for later use.
![image](https://github.com/PCSX2/pcsx2/assets/84397998/1318971b-ee65-433d-a99c-25de8d3347a4)

**Comment by refractionpcsx2** [comment]
No, for the reasons outlined here #8013
