### ISSUE TITLE
[BUG]: Corrupted Text and Font in Keroro Gunso - Mero Mero Battle Royale Z

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#9004]
### Describe the Bug

With Keroro Gunso - Mero Mero Battle Royale Z, when the game are booting in HW mode (or when switching between SW and HW) it suffers from corrupted and unreadable text. but when you start the game in SW mode, it all works fine and as soon as you switch to HW, the text got corrupted again.

![Keroro Gunsou - Mero Mero Battle Royale Z_SLPS-25575_20230618171631](https://github.com/PCSX2/pcsx2/assets/14798312/3395735e-7523-4883-ba10-ff6ac836c69b)

### Reproduction Steps

1. Boot the game in HW mode, during the memory card load process all the text will be invisible.
2. Then switch to SW and back to HW again.
3. Observe the text and font got completely messed up.

Alternatively, load up the provided GS Dump below and observe the difference between SW and HW mode.

### Expected Behavior

When booting in SW mode, it works fine:
![Keroro Gunsou - Mero Mero Battle Royale Z_SLPS-25575_20230618171147](https://github.com/PCSX2/pcsx2/assets/14798312/aa6d636e-de27-4633-ae30-90b27fce3154)

### PCSX2 Revision

v1.7.4592

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

All settings are default except internal resolution which is set to 4x

### Emulation Settings

All settings are also defaults.

### GS Window Screenshots

![Screenshot_20230620_152056](https://github.com/PCSX2/pcsx2/assets/14798312/671e1829-3e2f-43b5-b860-fba2b6d50c12)

### Logs & Dumps

Here is the GS Dump:

[Keroro Gunsou - Mero Mero Battle Royale Z_SLPS-25575_20230618171147.zip](https://github.com/PCSX2/pcsx2/files/11781199/Keroro.Gunsou.-.Mero.Mero.Battle.Royale.Z_SLPS-25575_20230618171147.zip)

**Comment by refractionpcsx2** [comment]
did you try enabling Preload Frame? We use that with Keroro

**Comment by kamfretoz** [comment]
> did you try enabling Preload Frame? We use that with Keroro

Still a no go :(
![image](https://github.com/PCSX2/pcsx2/assets/14798312/2a5c285a-eb42-4eef-9b8c-18a4abb8853a)
