### ISSUE TITLE
[Feature Request]: Selectable Cover Storing Style 

### ISSUE THREAD

**Issue by QbikEdge** [PCSX2/pcsx2#9005]
### Description

Would be nice to be able the Style of the `Cover-Storing` Method. I have in mind for example the `Cover-Storing` Style
of [`LaunchBox` ](https://www.launchbox-app.com/) It would be really easy to select the folder where `LaunchBox` stores
it the Images: It is the subfolder: `\LaunchBox\Images\Sony Playstation 2`

<details><summary>The structure is as follows: </summary>

![image](https://github.com/PCSX2/pcsx2/assets/32527357/4d3650e8-dde3-42a7-9726-835ddd2fd96f)

</details>

I think it would be nice to have the same structure in `PCSX2` as well. It would be really easy to add new Images to the.

We can use the current `PCSX2` Folder Structure and add a `dropdown` to the `PCSX2` Settings to select the `Cover-Storing` Style of `LaunchBox` or the `Cover-Storing` Style of `PCSX2`.

- If the `Cover-Storing` Style of `PCSX2` is selected, it will work how it works now. And we don't need to change anything.
    
- If the `Cover-Storing` Style of `LaunchBox` is selected, we need to add the following subfolders to the `covers` folder:
    - `Box - Front`
    - `Disc`
    - `Fanart - Box - Front`
    - `Fanart - Disc`
    - `Box - Front - Reconstructed`
    - <details><summary>
        
        The `Box - Front`, `Disc`, `Fanart - Box - Front`, `Fanart - Disc` and `Box - Front - Reconstructed` Folders can have the following subfolders:  </summary>

        - `Europe`
        - `Europe, Australia`
        - `France`
        - `Germany`
        - `North America`
        - `North America, Europe`
        - `Umited Kingdom`
        - `United States`
        - `World` </details>

        - the Regionless Covers can be stored directly in the `Box - Front`, `Disc`, `Fanart - Box - Front`, `Fanart - Disc` and `Box - Front - Reconstructed` Folders
        - Most like likely we don't need all the subfolders. But if we have them, we can add them as well. To not miss any Cover. Or we could recursively search for the Images in the `Box - Front`, `Disc`, `Fanart - Box - Front`, `Fanart - Disc` and `Box - Front - Reconstructed` Folders.

- I dont know if there are more subfolders in the `LaunchBox` Folder Structure. But if there are more subfolders, we can add them as well. To not miss any Cover. 
- The Images are in `png` and `jpg` Format. 

I think we don't need the `3D Box` and `Screenshot` Folders. But if you guys want to add a `3D Box` and `Screenshot` view to `PCSX2` as well, we can add the `3D Box` and `Screenshot` Folders as well.

### Reason

The reason for this Feature Request is, that i use the `PCSX2` Emulator with `LaunchBox` and i want to use the same `Cover-Storing` Style in `PCSX2` as well. And i don't want to store an extra copy of the Images in the `PCSX2` Folder.  

With this Feature Request, i can use the same `Cover-Storing` Style in `PCSX2` as well. And i don't need to store an extra copy of the Images in the `PCSX2` Folder.

### Examples

[`LaunchBox` ](https://www.launchbox-app.com/)

<details><summary>The structure is as follows: </summary>

<details><summary>Main folder for images </summary>

![image](https://github.com/PCSX2/pcsx2/assets/32527357/4d3650e8-dde3-42a7-9726-835ddd2fd96f)
</details>
<details><summary>Subfolder of importance</summary>

![image](https://github.com/PCSX2/pcsx2/assets/32527357/fb55c0fa-14da-4bd7-9da1-93e6f8d12089)
![image](https://github.com/PCSX2/pcsx2/assets/32527357/dba8e0ca-8e7f-4bff-8347-b5f2bae32f9c)
</details>
<details><summary>Sub-sub Folder</summary>

![image](https://github.com/PCSX2/pcsx2/assets/32527357/220da592-c733-4811-a0c7-699a474a812f)

</details>

**Comment by Daisouji** [comment]
If the major concern is no duplicates, the issue isn't file structure. You want to directly link your launchbox cover images to PCSX2

**Comment by QbikEdge** [comment]
That is right there is no need for duplication. On the LB side its all how it should be. I have there every platform im emulating. And the Covers/Box arts, ect. all set up. There for it does not make any sense to download the same amount of data to see the covers also in `PCSX2` .  To implement this from LB's perspective does not make sense, they have an automatic download for all platforms. So they would need to change there code for no benefit of there system. 

But it benefits the `PCSX2` User that all the data and files are organized, less space is used. And shown on the `PCSX2` Grid layout and also on Big Picture Mode.

Forgot to mention that i am currently on the `PCSX2 Nightly - v1.7.4592` 

This feature is not a high priority in my opinion. But it would make the organizing of files so much easier.  For the Users and Developers as well.

**Comment by stenzek** [comment]
Sorry, but expecting us to cater to the setup of a frontend, especially a paid one, isn't our problem. PCSX2 does not benefit at all from any of this, and frankly, if you're using a frontend, you're not even using our UI in the first place...

I'd suggest asking LB to be compatible with us instead, after all you're a paying customer.
