### ISSUE TITLE
[Feature Request]: More deinterlacing options

### ISSUE THREAD

**Issue by mk011** [PCSX2/pcsx2#9006]
### Description

The new motion adaptive deinterlacing method is not quite perfect and can at times produce combing artifacts which can be distracting. I would like an option to set another deinterlacing method(the old one) as the automatic default.
A toggle option for enabling "Anti-Blur" when deinterlacing is being used would also be helpful in reducing blur. At native resolution, just deinterlacing seems to be enough for making various transparency effects work.

### Reason

It would help me focus on the game and not combing artifacts. Manually setting deinterlacing for each game is a pain.

### Examples

Current MAD Balmung:
![MAD Balmung](https://github.com/PCSX2/pcsx2/assets/89043516/eb84baab-ab4f-4ede-8053-12b7c9af145c)

Old Blend Balmung:
![Blend Balmung](https://github.com/PCSX2/pcsx2/assets/89043516/0f5a5d9a-b7b5-443a-8b67-ddfbc344fddc)

**Comment by MrCK1** [comment]
> The new motion adaptive deinterlacing method is not quite perfect and can at times produce combing artifacts which can be distracting. I would like an option to set another deinterlacing method(the old one) as the automatic default. 

You can already do this - you just need to switch to any of the modes that aren't "Adaptive" 

![image](https://github.com/PCSX2/pcsx2/assets/16314399/cd278f4e-f1c7-4ad3-a9f9-5bf44d97555d)


> A toggle option for enabling "Anti-Blur" when deinterlacing is being used would also be helpful in reducing blur. At native resolution, just deinterlacing seems to be enough for making various transparency effects work.

I'm not sure what you're asking for here unless you can give an example.

**Comment by mk011** [comment]
> You can already do this - you just need to switch to any of the modes that aren't "Adaptive"

If you set a specific deinterlacing method, then deinterlacing is always enabled no matter what. With the "Automatic" setting it works differently, deinterlacing is only turned on when needed.

> I'm not sure what you're asking for here unless you can give an example.

I would prefer to have "Anti-Blur" disabled since it's less blurry than Blend deinterlacing, but if deinterlacing is forced on, I'd like "Anti-Blur" enabled again because there's no benefit to blurring the game twice.

Anti-Blur, No Deinterlacing (Not good):
![1](https://github.com/PCSX2/pcsx2/assets/89043516/9c7d4986-f6e9-4182-a33b-5824d5d83824)

No Anti-Blur, No Deinterlacing (Ideal, what I would prefer to use):
![2](https://github.com/PCSX2/pcsx2/assets/89043516/b43b6f78-eeb6-4b91-93ec-013013395e5c)

Anti-Blur, Deinterlacing(What I'm asking to be an toggle option):
![3](https://github.com/PCSX2/pcsx2/assets/89043516/8ff36de7-e8eb-4d9a-9f18-496bf4693056)

No Anti-blur, Deinterlacing (Double blurring, what I want to avoid):
![4](https://github.com/PCSX2/pcsx2/assets/89043516/c382d952-3910-4754-86a0-67ed5e3ed946)

**Comment by refractionpcsx2** [comment]
> > You can already do this - you just need to switch to any of the modes that aren't "Adaptive"
> 
> If you set a specific deinterlacing method, then deinterlacing is always enabled no matter what. With the "Automatic" setting it works differently, deinterlacing is only turned on when needed.

Incorrect, deinterlacing only ever enables if the game is interlaced. if you are using a no-interlacing patch and you're not set to auto, you will need to set it to auto (or none) on the game specific settings.

> Anti-Blur, No Deinterlacing (Not good): ![1](https://user-images.githubusercontent.com/89043516/246686178-9c7d4986-f6e9-4182-a33b-5824d5d83824.png)
> 
> No Anti-Blur, No Deinterlacing (Ideal, what I would prefer to use): ![2](https://user-images.githubusercontent.com/89043516/246686189-b43b6f78-eeb6-4b91-93ec-013013395e5c.png)
> 
> Anti-Blur, Deinterlacing(What I'm asking to be an toggle option): ![3](https://user-images.githubusercontent.com/89043516/246686277-8ff36de7-e8eb-4d9a-9f18-496bf4693056.png)
> 
> No Anti-blur, Deinterlacing (Double blurring, what I want to avoid): ![4](https://user-images.githubusercontent.com/89043516/246686264-c382d952-3910-4754-86a0-67ed5e3ed946.png)

Anti-Blur has nothing to do with deinterlacing.

**Comment by mk011** [comment]
> Anti-Blur has nothing to do with deinterlacing.

Fair enough.

My point is that the default automatic deinterlacing method is causing me issues.

**Comment by refractionpcsx2** [comment]
You're free to change it to another options, Blend is the old default.
As I said, if you need no-interlacing patches, you can change it per-game, but you probably don't need to with most patches.

**Comment by refractionpcsx2** [comment]
anyway, as mentioned, the deinterlacing can be set globally, no need to do it per game, I don't think there's anything else to be done here, so gonna close.

**Comment by mk011** [comment]
> no-interlacing patch
Not accurate. There is no no-interlacing patch for .Hack Infection.

> Incorrect, deinterlacing only ever enables if the game is interlaced. if you are using a no-interlacing patch and you're not set to auto, you will need to set it to auto (or none) on the game specific settings.
No, what I said is correct. Deinterlacing is always enabled if you pick a specific option manually, it is only enabled when needed if the automatic setting is used. The third picture(Anti-Blur, Deinterlacing) in my previous comment demonstrates this. Deinterlacing has worked this way for many years.

**Comment by stenzek** [comment]
> If the default option is causing problems, then the default option is wrong.

No, it's not. There's no way to automatically know which mode is going to be optimal for any particular game. If you have some insight and know of a better heuristic to determine the mode, then by all means, please go ahead and implement it, the relevant bits are in the GSRenderer class.

The current heuristics for automatic work well enough for the majority of games. If it doesn't, change it in the per-game configuration, problem solved.

> Not accurate. There is no no-interlacing patch for .Hack Infection.

You can always create one, assuming the game is rendering alternate fields with offsets.

> No, what I said is correct. Deinterlacing is always enabled if you pick a specific option manually,

Not in progressive modes. See `GSRenderer::Merge()`.
