### ISSUE TITLE
bug regression working game for v1.3.1 rev1274  

### ISSUE THREAD

**Issue by elcorsico** [PCSX2/pcsx2#901]
for this revision :Game Test :  the gregory horror show , 
Statut : no working now
the emu crash 

please re-fix this game

thanks developpers ;-)

nice day

**Comment by gregory38** [comment]
It could be related to the recent iop change. It might worth to look at it.

**Comment by refractionpcsx2** [comment]
Hmm I'll have a look

**Comment by refractionpcsx2** [comment]
That was probably because everything was crashing due to my compilation bodge at 3am ;p

The game works fine for me on the latest revision.

**Comment by gregory38** [comment]
Oh. Yes it could be.

**Comment by elcorsico** [comment]
ok , good re working,
thanks for this and other
nice emu
i'm french lover ps2 emu
continue to amelioration

**Comment by refractionpcsx2** [comment]
Enjoy :)
