### ISSUE TITLE
PCSX2 crashes before displaying a video

### ISSUE THREAD

**Issue by arubar0** [PCSX2/pcsx2#9015]
### Describe the Bug

Happened when updating from nightly v1.7.4596 (worked) onwards.
The game crashes just before displaying the intro of the game Ar Tonelico II.

### Reproduction Steps

Start the game and wait until the intro video and crashes.

### PCSX2 Revision

v1.7.4599

### Operating System

Windows 11

### Logs & Dumps

[crash-2023-06-20-18-02-28-524.zip](https://github.com/PCSX2/pcsx2/files/11803312/crash-2023-06-20-18-02-28-524.zip)

**Comment by Mrlinkwii** [comment]
What exact build dose it crash on?

**Comment by arubar0** [comment]
At least v1.7.4599, v1.7.4598 and v1.7.4597 went to the same crash

**Comment by refractionpcsx2** [comment]
It'll be fixed once #9017 merges
