### ISSUE TITLE
[Feature Request]: Implement option to disable dithering in SW

### ISSUE THREAD

**Issue by Bigmac9922** [PCSX2/pcsx2#9026]
### Description

Implement a option to disable dithering in software mode.

### Reason

It looks horrible on certain games especially on 1440p and 4k monitors. Add the option possibly in the Post-Processing tab or rendering tab like on hardware render as a simple toggle on and off.

### Examples

like hardware mode except no scaling just a simple on and off check box.

**Comment by MrCK1** [comment]
The point of the SW renderer is to be accurate to the PS2. Why not just use hardware mode with dithering turned off then? Most games are a match for SW these days.

**Comment by Bigmac9922** [comment]
Software mode is very accurate plays certain games almost flawless such as Grand Theft Auto: San Andreas.

**Comment by Mrlinkwii** [comment]
HW mode also plays GTASA flawlessly ( you can disable it their)

**Comment by Bigmac9922** [comment]
It seems to have a ghosting bug that gets worse with upscaling.

**Comment by refractionpcsx2** [comment]
This is a hard no.

**Comment by Bigmac9922** [comment]
Ok

**Comment by Mrlinkwii** [comment]
Theirs 0 ghosting bugs in GTA SA in HW mode  , all upscaling is optional

**Comment by refractionpcsx2** [comment]
> It seems to have a ghosting bug that gets worse with upscaling.

The ghosting is an intentional game graphical effect, there are patches included with pcsx2 to disable the game effect if you don't like it, they are under Game Properties->patches.

**Comment by Bigmac9922** [comment]
Ok thank you very much refraction I will check into that.

**Comment by Bigmac9922** [comment]
That fixed it thanks @refractionpcsx2
