### ISSUE TITLE
Spyro: Enter the Dragonfly

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#903]
[According to the wiki](http://wiki.pcsx2.net/index.php/Spyro:_Enter_the_Dragonfly#Known_Issues) this game needs a a cheat code just to get past the start screen. Shouldn't we include a .pnach file for this game then so that it just works for people?

We already include a Persona 4 .pnach for some reason, why not include one that's actually useful?

**Comment by willkuer** [comment]
Thats the idea of the gameindex.dbf. is is applied together with the automatic game fixes.

The persona cheats is just an example for those who want to create new cheats but dont know how they should look like.

I think spyro fix is already added to the gamedb. At least accoding to the thread.

**Comment by karasuhebi** [comment]
You are 100% correct. I just double-checked myself. Apologies!

**Comment by willkuer** [comment]
According to the spyro thread around march 2015. one could check the git list.

**Comment by willkuer** [comment]
And if you are even smarter and can read us dates it happened around september.

Thank you us for mm/dd/yyyy.
