### ISSUE TITLE
[BUG]: Per-game memory card overrides don't work until reinserted

### ISSUE THREAD

**Issue by modo-lv** [PCSX2/pcsx2#9032]
### Describe the Bug

Game-specific memory cards are ignored until manually re-inserted while the game is running.

### Reproduction Steps

1. Assign an empty memory card to Slot 1 in Settings
2. Assign a second memory card containing a game save to Slot 1 in Game Properties (I tested with Valkyrie Profile 2).
3. Start the game. The game will read the empty memory card instead of the one containing the save file.

Workaround:
1. In-game menu, game properties, eject/disable the game-specific memory card, return to game. Make sure the "Memory card re-inserted" notification pops up.
2. In-game menu, game properties, insert/enable the game memory card. It is now correctly read instead of the empty one.

### Expected Behavior

A memory card explicitly assigned to a specific game should be used instead of the default one.

### PCSX2 Revision

v1.7.4611

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment]
Yeah my bad, is fixed in #9033
