### ISSUE TITLE
[BUG]: Broken aspect ratio in progressive scan mode (720x960)

### ISSUE THREAD

**Issue by NicknineTheEagle** [PCSX2/pcsx2#9035]
### Describe the Bug

If progressive scan mode is enabled in-game with Deinterlacing disabled _and_ Screen Offsets enabled then the game appears with a broken aspect ratio where it's squished into the half the screen height.

### Reproduction Steps

1. Disable Deinterlacing and enable Screen Offsets in Graphics settings.
2. Run Prince of Persia: The Sands of Time (SLES-51918).
3. Go to Display options in-game and enable Progressive Scan.
4. PCSX2 thinks the video output is 720x960 rather than 720x480 so the game appears squished into half the screen height.

### Expected Behavior

The output is 720x480 and the game appears at the aspect ratio selected in Graphics options.

### PCSX2 Revision

1.7.4612

### Operating System

Windows 10 (64bit)

### CPU

i5-9600KF

### GPU

RTX 2060 Super

### GS Settings

Deinterlacing: None
Screen Offsets: On

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/6665256/80d5f4f1-a3ee-4753-8b72-647949bab219)

**Comment by Mrlinkwii** [comment]
What happens if you also enable overscan?

**Comment by Mrlinkwii** [comment]
why are you changing Deinterlacing ?

**Comment by NicknineTheEagle** [comment]
> What happens if you also enable overscan?

Nothing.

**Comment by NicknineTheEagle** [comment]
> why are you changing Deinterlacing ?

Does it matter? It's still a bug.

**Comment by Mrlinkwii** [comment]
>Does it matter? It's still a bug.

actually it dose ,  its fine on auto as far as i can see 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/baf38935-30ff-44bd-9ed3-5191a5b53226)

**Comment by NicknineTheEagle** [comment]
Well, yeah, I know that, that's why I specified that the bug only occurs on None, every other setting seems to be fine.

**Comment by socialenigma-og** [comment]
It's not exclusive to this game -- it also occurs in Shadow of the Colossus or Hitman: Blood Money, for example.
Still active even through the recently added Aspect Ratio option, 'Native 10:7'.
