### ISSUE TITLE
[BUG]: To All People - Garbage in screen transitions.

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9042]
### Describe the Bug

![Cross Channel - To All People  Limited Edition _SLPM-65546_20230623065746](https://github.com/PCSX2/pcsx2/assets/8851653/d4635ca8-8f77-43b2-98e4-3e1c7241e3e8)

### Reproduction Steps

start the game in hardware mode and look at first screen transition.

### Expected Behavior

above image should be black.

### PCSX2 Revision

1.7.4615

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Cross Channel - To All People [Limited Edition]_SLPM-65546_20230623065746.gs.zip](https://github.com/PCSX2/pcsx2/files/11848224/Cross.Channel.-.To.All.People.Limited.Edition._SLPM-65546_20230623065746.gs.zip)

**Comment by refractionpcsx2** [comment]
Gonna need a longer GS dump from before that point, the GS dump is broken in both renderers

**Comment by seta-san** [comment]
[Cross Channel - To All People [Limited Edition]_SLPM-65546_20230623073528.gs.zip](https://github.com/PCSX2/pcsx2/files/11848496/Cross.Channel.-.To.All.People.Limited.Edition._SLPM-65546_20230623073528.gs.zip)

**Comment by refractionpcsx2** [comment]
bleh that's broken too.  if it's the start of the game can you provide a blockdump instead?

**Comment by seta-san** [comment]
[Cross Channel - To All People (Japan) (Shokai Genteiban) (2023-06-23 07-48-53).zip](https://github.com/PCSX2/pcsx2/files/11848586/Cross.Channel.-.To.All.People.Japan.Shokai.Genteiban.2023-06-23.07-48-53.zip)

**Comment by refractionpcsx2** [comment]
yea that shows it, thanks
