### ISSUE TITLE
[BUG]: Snow - Alpha Issues

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9043]
### Describe the Bug

![Snow  First Limited Edition _SLPS-25332_20230623073034](https://github.com/PCSX2/pcsx2/assets/8851653/3ce95f91-3198-450f-adb3-a2c2ce0dcb1e)

### Reproduction Steps

play game in hardware mode

### Expected Behavior

![Snow  First Limited Edition _SLPS-25332_20230623073155](https://github.com/PCSX2/pcsx2/assets/8851653/896870e2-168b-44f5-8864-1f9295c535ce)

### PCSX2 Revision

1.7.4615

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Snow [First Limited Edition]_SLPS-25332_20230623073034.gs.zip](https://github.com/PCSX2/pcsx2/files/11848466/Snow.First.Limited.Edition._SLPS-25332_20230623073034.gs.zip)

**Comment by refractionpcsx2** [comment]
Requires High blending. Can add that to the GameDB

![image](https://github.com/PCSX2/pcsx2/assets/6278726/b583d98c-645d-479e-8ac6-1a25e99c169a)
