### ISSUE TITLE
[BUG]: Possible regression, graphics are entirely broken on Linux after v1.7.4613

### ISSUE THREAD

**Issue by ShortMomo** [PCSX2/pcsx2#9045]
### Describe the Bug

On Linux (endeavourOS which is Arch Based) with an AMD GPU (RX 6750XT) on Vulkan, using the mesa AMD graphics driver, emulation graphics completely break on any version after 4613 (related to "GS: Use 32-bit vertex positions for culling": https://github.com/PCSX2/pcsx2/pull/9000 ). Testing in Software Mode to confirm it's not GPU related.

Graphics on 4612 (Tokyo Xtreme Racer: Drift 2):
![image](https://github.com/PCSX2/pcsx2/assets/136559710/ff971e88-7258-4582-8816-bc86fbe4cbf0)

Graphics on 4613:
![image](https://github.com/PCSX2/pcsx2/assets/136559710/44b7a5cb-f85d-4486-84db-dcb28bddd732)

Pretty gnarly looking. GS Dump is attached.

### Reproduction Steps

1. Launch a game on either Software or Hardware renderer on Linux on any version prior to 4613 and observe the result
2. Launch a game on 4613 and observe the broken graphics

### Expected Behavior

Obviously regressions aren't supposed to happen, right?

### PCSX2 Revision

v1.7.4613, but also occurs on latest which is v1.7.4615

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

endeavourOS (Arch based)

### CPU

AMD Ryzen 5 5600X

### GPU

AMD Radeon RX 6750XT

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/136559710/1c19a4fd-b8c7-48d1-8948-ac0b92eb5906)

![image](https://github.com/PCSX2/pcsx2/assets/136559710/0d728c72-8006-4592-b587-0be249cc20ad)

![image](https://github.com/PCSX2/pcsx2/assets/136559710/95965940-5e7f-49ba-8e3a-769161022c55)

### Emulation Settings

![image](https://github.com/PCSX2/pcsx2/assets/136559710/3f8b35dd-28dd-403b-b42b-2003f1e3e3ca)

### Logs & Dumps

![Tokyo Xtreme Racer Drift 2_SLUS-21394_20230623223948](https://github.com/PCSX2/pcsx2/assets/136559710/00c3af57-ce53-4a2a-a7ab-9f5e566a9c86)
[Tokyo Xtreme Racer Drift 2_SLUS-21394_20230623223948.gs.zip](https://github.com/PCSX2/pcsx2/files/11848529/Tokyo.Xtreme.Racer.Drift.2_SLUS-21394_20230623223948.gs.zip)

**Comment by refractionpcsx2** [comment]
strange, the gsdump works fine here

![image](https://github.com/PCSX2/pcsx2/assets/6278726/88ac5ee4-85cd-45b4-9853-f7408cdad1ac)

**Comment by ShortMomo** [comment]
Yeah I believe this might be a Linux-only issue. Haven't had anyone on Windows around me that also use PCSX2 report it.

**Comment by refractionpcsx2** [comment]
I'm not sure the PR you linked to is the cause of the problem, that code is OS and renderer agnostic, since it happens before any of that happens.

can you confirm older versions still run fine?

**Comment by ShortMomo** [comment]
Yes I can confirm older versions run fine, playing on 4612 for the time being. I've only linked that PR in particular because that's the version number where the issue starts to occur, I may not be correct in pointing fingers at that change specifically.

**Comment by Mrlinkwii** [comment]
i can confirm its broken after v1.7.4613 ,  4612 works here

**Comment by stenzek** [comment]
Seems to be specific to the AppImage, and more specifically, building it on Ubuntu 20.04. Local builds on 23.04, as well as the flatpak work fine.

Might be a compiler issue or UB, need to install 20.04 to debug it.

**Comment by stenzek** [comment]
The rare case where it is actually a compiler bug and not our fault... :)
