### ISSUE TITLE
[BUG]:  singstar microphone not working

### ISSUE THREAD

**Issue by Mitsuperboy** [PCSX2/pcsx2#9059]
### Describe the Bug

Singstar microphone are showing connected but not working in emulator or rom

i'm using a steam deck and the singstar profile can anyone fix or help please

### Reproduction Steps

Singstar microphone are showing connected but not working in emulator or rom

i'm using a steam deck and the singstar profile can anyone fix or help please

### PCSX2 Revision

latest

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

steamos

### CPU

amd zen 2

### GPU

amd rdna 2

**Comment by stenzek** [comment]
Duplicate of #8974.
