### ISSUE TITLE
[BUG]: Clannad - Small Graphics issues

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9061]
### Describe the Bug

2 bugs i can see.

1. calendar in top left corner is transparent unless blending is set to high
2. upscaling artifact goes vertically through character portrait. only upscale fix i saw fix this was the wildarms hack (i know you don't like this one.

![Clannad_SLPM-66302_20230624105354](https://github.com/PCSX2/pcsx2/assets/8851653/4352851f-d713-452c-9cc4-b0c9e34e097a)

### Reproduction Steps

play game.

### Expected Behavior

![Clannad_SLPM-66302_20230624110523](https://github.com/PCSX2/pcsx2/assets/8851653/34fad1aa-b4d3-483d-86ad-53813660e283)

### PCSX2 Revision

1.7.4628

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Clannad_SLPM-66302_20230624105354.gs.zip](https://github.com/PCSX2/pcsx2/files/11857537/Clannad_SLPM-66302_20230624105354.gs.zip)

**Comment by refractionpcsx2** [comment]
Wild Arms seems to soften the image too, unless you changed so other settings between pictures, is that desirable?

**Comment by refractionpcsx2** [comment]
Wild Arms also doesn't help at higher upscales, at x8 it does basically nothing.

**Comment by seta-san** [comment]
> Wild Arms seems to soften the image too, unless you changed so other settings between pictures, is that desirable?

honestly i like software mode better for 2d games. it has a softer or pleasant image and less error prone. but i finally got japanese people to complain about games so i'm going to try to encourage that.

**Comment by refractionpcsx2** [comment]
I'm happy to add high blending, but I guess encourage playing the game in native resolution, none of the upscaling hacks truly help
