### ISSUE TITLE
[BUG]: Switching monitors when going fullscreen

### ISSUE THREAD

**Issue by weirdbeardgame** [PCSX2/pcsx2#9064]
### Describe the Bug

In Wayland, when I double-click the window to go full screen the window will randomly shift to the primary monitor double-click. Behavior happens across Nvidia or AMD Mesa. I've personally tested both ;)

Tested on Nvidia 2700, AMD 6950xt Gpus

### Reproduction Steps

Use pcsx2 in Wayland, go from windowed to fullscreen. Watch the window go to the left or right depending on what's set as primary. Wayland

### Expected Behavior

It should fullscreen on the monitor its already on

### PCSX2 Revision

1.7.4631

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by Mrlinkwii** [comment]
Dose it happen when using x11?

**Comment by stenzek** [comment]
Invalid. Wayland is broken-by-design garbage and gives us **zero** control over where the window is positioned. It completely ignores all position requests.
