### ISSUE TITLE
[BUG]: 5 Second Crash

### ISSUE THREAD

**Issue by edisionnano** [PCSX2/pcsx2#9065]
### Describe the Bug

I open the emulator and it crashes in about 5 seconds, if I'm fast enough i can load the game but then it still crashes once the time is up. I open it from Discover and it doesn't even give any logs

### Reproduction Steps

Click Launch
Wait
Crash

### Expected Behavior

Not Crashing

### PCSX2 Revision

1.7.4401

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### Logs & Dumps

none

**Comment by refractionpcsx2** [comment]
This isn't for support, can you please use the discord or the forum to find out why you're crashing, thanks.
