### ISSUE TITLE
[BUG]: WRC II Extreme - Special Demo (Europe) (SCED-51632)vertex explosions in software mode

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#9066]
### Describe the Bug

vertex explosions during game

### Reproduction Steps

just load game with software renderer

### PCSX2 Revision

v1.7.4634

### Operating System

Windows 11

### CPU

Ryzen 7 5700X

### GPU

NVIDIA RTX 3060

### GS Window Screenshots

![Unknown Game_ SCED-51632_SCED-51632_20230625093035](https://github.com/PCSX2/pcsx2/assets/2696404/62ede728-53c3-49ad-90d9-947b76744bd3)
[snaps2.zip](https://github.com/PCSX2/pcsx2/files/11858534/snaps2.zip)
![Unknown Game_ SCED-51632_SCED-51632_20230625093051](https://github.com/PCSX2/pcsx2/assets/2696404/5d612d22-7ef5-4dfc-8304-dff46186095e)
![Unknown Game_ SCED-51632_SCED-51632_20230625093059](https://github.com/PCSX2/pcsx2/assets/2696404/016adeae-85f7-4d75-8e71-66d135b862d1)
![Unknown Game_ SCED-51632_SCED-51632_20230625093106](https://github.com/PCSX2/pcsx2/assets/2696404/e5057249-2be4-4db7-9f17-7e5c67206c49)

### Logs & Dumps

[snaps.zip](https://github.com/PCSX2/pcsx2/files/11858532/snaps.zip)
[snaps1.zip](https://github.com/PCSX2/pcsx2/files/11858533/snaps1.zip)
[snaps2.zip](https://github.com/PCSX2/pcsx2/files/11858539/snaps2.zip)
[snaps3.zip](https://github.com/PCSX2/pcsx2/files/11858541/snaps3.zip)

**Comment by Mrlinkwii** [comment]
Can you please check #9067 for me :) ?

**Comment by benderscruffy** [comment]
@Mrlinkwii 
goes ingame with no glitches
