### ISSUE TITLE
[BUG]: WWF Smackdown! - Just Bring It [Demo] SCED-50478 players and ref flash in software mode

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#9071]
### Describe the Bug

during gameplay the players and ref keep flashing

### Reproduction Steps

just play the demo with the software renderer

### PCSX2 Revision

v1.7.4636

### Operating System

Windows 11

### CPU

Ryzen 7 5700X

### GPU

NVIDIA RTX 3060

### Logs & Dumps

it don't know if it is capture in the GS dumps its hard to tell ??

[snaps.zip](https://github.com/PCSX2/pcsx2/files/11858929/snaps.zip)
[snaps1.zip](https://github.com/PCSX2/pcsx2/files/11858930/snaps1.zip)
[snaps2.zip](https://github.com/PCSX2/pcsx2/files/11858931/snaps2.zip)

**Comment by F0bes** [comment]
If you don't know if it's captured in a GS dump, provide one anyways.
If you are unable to capture a GS dump, screenshots would be appreciated.

**Comment by Buzzardsoul** [comment]
If I had to guess, I'd assume it needs a different clamping mode. But I'll leave that to the testers to figure out.
![untitled](https://github.com/PCSX2/pcsx2/assets/126727903/7fdbb714-1924-4e75-9432-5e1b3870bba4)

**Comment by Buzzardsoul** [comment]
Tried all sorts of rounding/clamping modes, turned off recompiler modes, tried all gamefixes, even tried software mode too. Nothing seemed to fix it.

**Comment by prafullpcsx2** [comment]
Does this happen with demo only or full version of the game also suffers from this bug?

**Comment by prafullpcsx2** [comment]
I think it's not a bug with PCSX2. These are probably camera flash effect which has been overdone in this demo. I will suggest to run the demo on real ps2 and check if those flashes are still there.

**Comment by Buzzardsoul** [comment]
> I think it's not a bug with PCSX2. These are probably camera flash effects which are overdone in this demo. I will suggest to run the demo on real ps2 and check if those flashes are still there.
> 
> Edit: yeah, definitely not a bug. It's present on full version of the game and also real ps2 footage available on youtube.

I haven't tested it on a real PS2 yet, but it seems that the flashes are indeed normal. Idk about those jagged lines though. They might also be normal behavior Idk.
