### ISSUE TITLE
[BUG]: Persona 4 - Menu SW Renderer Flickering

### ISSUE THREAD

**Issue by JWatersMeet** [PCSX2/pcsx2#9073]
### Describe the Bug

Depending on the renderer selected, the color rendering of the Persona 4 UI changes. They can be put into three groups:

- Vulkan and OpenGL

**Vulkan**
![Persona 4 - Vulkan](https://github.com/PCSX2/pcsx2/assets/136824455/c537b1a0-46f4-4fb8-bcaf-5916483f7369)

**OpenGL**
![Persona 4 - OpenGL](https://github.com/PCSX2/pcsx2/assets/136824455/792a284d-a63f-4621-b4d9-be52b64f9328)

- DX11 and DX12

**DX11**
![Persona 4 - D3D11](https://github.com/PCSX2/pcsx2/assets/136824455/f12677b1-9238-48a7-935b-b78ba6226957)

**DX12**
![Persona 4 - D3D12](https://github.com/PCSX2/pcsx2/assets/136824455/b508d6f7-2591-40ee-a0d2-ee7bc952b23a)

- Software (also has flickering)

![Persona 4 - Software](https://github.com/PCSX2/pcsx2/assets/136824455/452477c7-8431-4f4e-a80d-e396ec463f36)

https://github.com/PCSX2/pcsx2/assets/136824455/a7f3de0d-fce9-47e3-962d-d26ac1fbe61f

### Reproduction Steps

- Start Persona 4 
- Open Saves Menu
- Switch Renderers

### Expected Behavior

- Color rendering should be consistent across all four.
- Software should have no flickering.

### PCSX2 Revision

1.7.4637

### Operating System

Windows 11

### CPU

Ryzen 5900HX

### GPU

RTX 3080 Mobile

### GS Settings

None

### Emulation Settings

None

### Logs & Dumps

![Shin Megami Tensei - Persona 4_SLUS-21782_20230625100714](https://github.com/PCSX2/pcsx2/assets/136824455/a30ec0aa-098e-4541-84e0-1ec366da886e)

[Shin Megami Tensei - Persona 4_SLUS-21782_20230625100714.zip](https://github.com/PCSX2/pcsx2/files/11859270/Shin.Megami.Tensei.-.Persona.4_SLUS-21782_20230625100714.zip)

**Comment by stenzek** [comment]
SW is a bug, dx11/dx12 being different is likely blending and a limitation of the api.

**Comment by Ir-boop** [comment]
Yeah, can confirm it to be a blending issue. The game also need at least high blending (vulkan/openGL) to properly render the menu effects. 

see:
Basic blending
![Shin Megami Tensei - Persona 4_SLUS-21782_20230625185859](https://github.com/PCSX2/pcsx2/assets/96909828/cc7b756a-5471-4e08-b9a7-bfb0dbee2c03)

![Shin Megami Tensei - Persona 4_SLUS-21782_20230625185852](https://github.com/PCSX2/pcsx2/assets/96909828/854341be-c555-4e3d-88d5-ce3ccffe467d)

High blending
![Shin Megami Tensei - Persona 4_SLUS-21782_20230625185729](https://github.com/PCSX2/pcsx2/assets/96909828/7f02dc41-81e0-41a2-94e1-7fc9763056ce)

![Shin Megami Tensei - Persona 4_SLUS-21782_20230625185753](https://github.com/PCSX2/pcsx2/assets/96909828/d9464904-5f88-48c1-88d5-6805a3d0f56d)

GS dumps (jus in case):
[Shin Megami Tensei - Persona 4_SLUS-21782_20230625185729.zip](https://github.com/PCSX2/pcsx2/files/11859495/Shin.Megami.Tensei.-.Persona.4_SLUS-21782_20230625185729.zip)

[Shin Megami Tensei - Persona 4_SLUS-21782_20230625185737.zip](https://github.com/PCSX2/pcsx2/files/11859504/Shin.Megami.Tensei.-.Persona.4_SLUS-21782_20230625185737.zip)

**Comment by stenzek** [comment]
Well, that's quite weird. Software looks fine for me if I switch to it, but if I start with software, it alternates between colours.

**Comment by Ir-boop** [comment]
> Well, that's quite weird. Software looks fine for me if I switch to it, but if I start with software, it alternates between colours.
> 
> Edit: Ugh, looks like a threading issue perhaps. It's fine with no extra threads...

Yeah, I try to run game from start with software rendering and the colour flickering happens. Weird is, if i move the saves selection the flickering gone. See:

https://github.com/PCSX2/pcsx2/assets/96909828/53e73a01-9ef2-4a27-9868-be69a9ceb3a1

With 0 extra threading it's not flickering but instead the colour is as if the blending is basic. However if i move the saves selection it's back to normal too.

**Comment by JWatersMeet** [comment]
Been doing some work to try and identify where the regressions occurred.

- Last known good build was 4541.
- In 4542, the colors in Software Rendering have changed (parts become darker). Possibly #8906 
- In 4554, the flickering begins. Possibly #8934 

![4541 - Good Colors](https://github.com/PCSX2/pcsx2/assets/136824455/94d5298d-5cfa-4ff1-8dcd-774669b7decc)

![4542 - Bad Colors](https://github.com/PCSX2/pcsx2/assets/136824455/88db8fda-7785-4395-b067-650ec30f3082)

https://github.com/PCSX2/pcsx2/assets/136824455/76a10eee-aeba-42ac-9e66-1850763e178f

**Comment by stenzek** [comment]
#8934 doesn't sound like a correct bisect, because it only changed HW.

**Comment by JWatersMeet** [comment]
Sure, I'll double check.

**Comment by JWatersMeet** [comment]
Seems to be a bad bisect - looks like the issue is intermittent. I'll see if I can find a way to trigger it.

**Comment by JWatersMeet** [comment]
Right, the flickering started at the same time as the color change above (Build 4542) - it seems somtimes it doesn't flicker, just says on the darkened colors. If that happens, the flickering can be triggered by fiddling with the number of software rendered threads until it starts.

**Comment by JWatersMeet** [comment]
Closed, no longer occurs in latest build. Have tried changing SW rendering threads, all good now.

**Comment by stenzek** [comment]
That's strange. I don't think anything was changed recently which would've affected it.. unless it was #9232
