### ISSUE TITLE
[BUG]: gzip indices are stored next to the iso, not in the cache directory

### ISSUE THREAD

**Issue by ToxicFrog** [PCSX2/pcsx2#9082]
### Describe the Bug

In `Settings -> Folders`, the cache directory is described as "used for storing shaders, gzip indices, and game list data". However, the gzip indices (`.pindex.tmp` files) are actually stored in the same folder as their corresponding iso.

### Reproduction Steps

- set `Cache Directory` to an existing folder -- the default of `$PCSX2DIR/cache` is fine.
- add a game in `.iso.gz` format to your game directory
- `Settings -> Rescan All Games`
- note that a `.pindex.tmp` file is created in your game directory, not in the cache directory

### Expected Behavior

All `.pindex.tmp` files are written to the cache directory.

### PCSX2 Revision

v1.7.4640 nightly

### Operating System

Windows 10 (64bit)

### Logs & Dumps

No logs, but some additional configuration fragments:

```ini
[Folders]
Cache = cache
[EmuCore]
GzipIsoIndexTemplate = $(f).pindex.tmp
```
At a guess, the `Folders.Cache` is not being prepended to the `EmuCore.GzipIsoIndexTemplate`. Manually setting `GzipIsoIndexTemplate` to `cache/$(f).pindex.tmp` works. So this is either a bug in the way gzip indices are stored, or (if this behaviour is intentional) a documentation bug in the way the cache folder is described, since it explicitly says gzip indices are stored there.

(They should probably also be named `.pindex.cache` or similar by default.)

**Comment by refractionpcsx2** [comment]
These files have never been written to the cache folder, they are stored with the iso's on purpose as they go together, otherwise the cache folder kinda ends up with loads of files nothing to do with pcsx2 (the cache folder is designed for the game list and shader cache).

Would you prefer they were stored in there? what would be your reasoning over the current situation?

**Comment by ToxicFrog** [comment]
The isos are stored on a network drive and I don't want it cluttered up with pindex files that are only used by the single computer that runs pcsx2 1.7.x.

That said, I do think storing them next to the isos is reasonable default behaviour, even if it's not what I personally want; in that case the only issue is that (a) there's no discoverable way to change that setting and (b) the settings UI *claims* that you can change that setting by changing the cache dir, but you can't. Fixing (b) should just be a matter of deleting the text "gzip indices, " from the help string for the cache dir.

**Comment by refractionpcsx2** [comment]
If the cache files are an issue because it's over the network, is there any reason not to convert them to CHD? those compress just as well (if not better) and do not require an index.

**Comment by ToxicFrog** [comment]
It's not performance I'm worried about, it's that it makes `ls` untidy. :) Maybe I could just add a leading `.` to the `GzipIsoIndexTemplate`?

Anyways, I have a workaround now, so I think the only *actual* issue is that the UI makes false claims about the role of the cache dir.

**Comment by refractionpcsx2** [comment]
You're righty, it does falsely claim the cache folder does that, maybe it was planned but never gone done. Alright, that's fair.
