### ISSUE TITLE
[BUG]: missing demos from gameindex

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#9087]
### Describe the Bug

missing demos from the gameindex
Battlefield 2 - Modern Combat (Europe) (Demo) SLED-53731
Ape Escape 2 (Europe) (Demo) SCED-51366
Stuntman (Europe) (Demo) SLED-51012
XIII (Europe) (Demo) SLED-52014
Zone of the Enders - The 2nd Runner (Europe) (Demo) SLED-51380

### Reproduction Steps

just load them and it comes up unknown

### PCSX2 Revision

v1.7.4636

### Operating System

Windows 11

### CPU

Ryzen 7 5700X

### GPU

NVIDIA RTX 3060

**Comment by benderscruffy** [comment]
@Mrlinkwii 
these 2 are labeled wrong in the database
XIII (Europe) (Demo) SLED-52014
you have put SLES-52014
Zone of the Enders - The 2nd Runner (Europe) (Demo) SLED-51380
you have put SCED-51380

**Comment by refractionpcsx2** [comment]
We'll get them corrected

**Comment by benderscruffy** [comment]
@Mrlinkwii 
here are a few more missing from the database
Driver - Parallel Lines (Europe) (Demo) SLED-53954
Def Jam - Vendetta (Europe) (Demo) SLED-51645

**Comment by benderscruffy** [comment]
@Mrlinkwii 
few more missing
Cold Winter (Europe) (Demo) SLED-53327
Crash Tag Team Racing (Europe) (Demo) SLED-53442
Buzz! Junior - Ace Racers (Europe) (Demo) SCED-55432

Burnout 2 - Point of Impact [Demo] SLED-51211 is missing the europe region flag

**Comment by benderscruffy** [comment]
@JordanTheToaster 
why did you put french for
Mashed - Drive to Survive (En,Fr,De,Es,It) (Demo) SLED-52506
![Screenshot 2023-07-05 141136](https://github.com/PCSX2/pcsx2/assets/2696404/50ca22ea-23ca-420e-bc6b-5fc1023b73c5)

**Comment by refractionpcsx2** [comment]
Somebody needs to tell redump people then, because that says it's just French http://redump.org/disc/50256/
