### ISSUE TITLE
[BUG]: Devil May Cry Special Edition (US) Not Rendering on MacOs

### ISSUE THREAD

**Issue by Toonycommitsarson** [PCSX2/pcsx2#9090]
### Describe the Bug

On the nightly version of pcsx2 for macos, as of a few recent updates i am unable to render DMC3 Special edition, about a quarter of the screen renders whether it is a fresh boot or a save state but the game is completely frozen. It also ramps up my processor and GPU causing my laptop to get extremely hot while attempting to render the game. The game had been working for weeks before this as i had over 60 hours on it. i attempted a factory reset of my Macbook as well and a full fresh install of the latest version of macOs monterey, the same issue persisted. 

### Reproduction Steps

In order to reproduce the behavior, use a mac device on the latest update for pcsx2, all settings default, and attempt to load into the game Devil May Cry 3 Special edition for the US. The game had been working for weeks before this as i had over 60 hours on it.

### Expected Behavior

the game should have just loaded normally.

### PCSX2 Revision

Latest

### Operating System

macOS 12 (Monterey)

### CPU

1.1 GHz Quad-Core Intel Core i5

### GPU

Intel Iris Plus Graphics 1536 MB

### GS Window Screenshots

![Devil May Cry 3 - Dante's Awakening  Special Edition _SLUS-21361_20230626161120](https://github.com/PCSX2/pcsx2/assets/71099940/08a36481-797f-4411-98c3-423af81aa978)

### Logs & Dumps

[Devil May Cry 3 - Dante's Awakening [Special Edition]_SLUS-21361_20230626161120.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11871035/Devil.May.Cry.3.-.Dante.s.Awakening.Special.Edition._SLUS-21361_20230626161120.gs.zst.zip)

**Comment by DigitalMajestic** [comment]
Bisected to 1.7.4613 #9000

**Comment by stenzek** [comment]
Probably the same clang issue then. See https://github.com/PCSX2/pcsx2/pull/9047

Try #9093 once it builds.
