### ISSUE TITLE
[BUG]: Twisted Metal Head On Extra Twisted rendering problem

### ISSUE THREAD

**Issue by adriangb** [PCSX2/pcsx2#9092]
### Describe the Bug

Works fine in single player mode, unusable tearing on player 2 in split screen co-op

### Reproduction Steps

Split screen co-op

### PCSX2 Revision

v1.7.4640

### Operating System

macOS 13 (Ventura)

### CPU

M1 Pro

### GPU

M1 Pro

### GS Settings

Haven't changed anything

### Emulation Settings

Haven't changed anything

### GS Window Screenshots

<img width="954" alt="Screenshot 2023-06-26 at 4 43 52 PM" src="https://github.com/PCSX2/pcsx2/assets/1755071/4f3a9cf8-467d-4f05-b54e-33eba249dc24">

**Comment by refractionpcsx2** [comment]
could also be related to #4964

**Comment by adriangb** [comment]
I get the same behavior in software render mode, so perhaps not

**Comment by refractionpcsx2** [comment]
wait what 👀 okay I didn't expect that.  did you start the game in software mode and experience it?

**Comment by refractionpcsx2** [comment]
Did this start recently by chance? we are tracking an annoying issue which macos is suffering from, which we recently fixed for windows builds due to an old version of clang having a compiler bug

**Comment by adriangb** [comment]
I'm pretty sure I started it in software mode yes. Here's the game properties from right clicking it on the main menu before starting and a screenshot right after it started
<img width="601" alt="Screenshot 2023-06-26 at 4 55 22 PM" src="https://github.com/PCSX2/pcsx2/assets/1755071/e5309219-d901-4c73-8dbe-0485718c61ec">
<img width="610" alt="Screenshot 2023-06-26 at 4 55 36 PM" src="https://github.com/PCSX2/pcsx2/assets/1755071/accee9d0-03d3-480a-b08d-cf78b238bd89">
<img width="1046" alt="Screenshot 2023-06-26 at 4 56 58 PM" src="https://github.com/PCSX2/pcsx2/assets/1755071/3d4e5cf3-8d0f-4d52-bd54-8485c6614712">

**Comment by adriangb** [comment]
> Did this start recently by chance?

Not sure, this was my first time using PCSX2 on this hardware and the first time I tried this game. I can try updating (even though I'm only 1 day behind on nightly)

**Comment by refractionpcsx2** [comment]
if 1.7.4612 is fine, then we might be already tracking the same problem

**Comment by adriangb** [comment]
Yup no change on updating. If you were surprised by it still happening in software rendering mode, could it be related to something else? Should I try tweaking some alias settings?

**Comment by refractionpcsx2** [comment]
If you could try the older version I mentioned

**Comment by adriangb** [comment]
Sorry I missed that you mentioned a different version than I was using. I can try that in a a bit, I just walked out wasn’t expecting such a quick reply 😂. Do you mean you tested with that version and it worked for you?

**Comment by refractionpcsx2** [comment]
I mean test with that version and see if it works for you, as I suspect it broke in 4613

**Comment by adriangb** [comment]
That version works! Please feel free to close this issue, although if you can link it to a fix PR (when there is one) to this issue that'd be nice so I can update at that point.

**Comment by refractionpcsx2** [comment]
I'm not closing the issue because it's still a problem :P

It'll be linked whenever a fix is made.
