### ISSUE TITLE
[BUG]: NARC - Broken Textures

### ISSUE THREAD

**Issue by TunaCat** [PCSX2/pcsx2#9096]
### Describe the Bug

After the tutorial battle, when you first get placed in the "open world", I have a strange visual glitch. All the game's visuals (textures?) are broken. It never occurs before the first 2 minutes of the game. Only after the 2nd cutscene, when the game starts proper. Sometimes my player character is unaffected, and sometimes he is. He was missing legs last time I tried.

Game is NTSC-U if relevant.

### Reproduction Steps

Start the game and play about 1-2 minutes, until you kill the drugged out criminal who came back to life. It'll be the 2nd cutscene in the game. After it plays, you'll be plopped into the "open world", and it should appear there as soon as the cutscene ends and you're in-game. I can't _not_ reproduce it. Happens 100% of the time.

Haven't seen anyone else mention it online though.

### PCSX2 Revision

1.7.4648

### Operating System

Windows 11

### CPU

i7-13700KF

### GPU

4070ti

### Emulation Settings

Everything should be basically default settings other than rendering and multi-threading, Please see this imgur for more info: https://imgur.com/a/eTcA05c

### GS Window Screenshots

https://i.imgur.com/hTlnhy3.jpg

### Logs & Dumps

![NARC_SLUS-20730_20230627174613](https://github.com/PCSX2/pcsx2/assets/13092217/ed31b22f-c15a-49aa-b9b5-e58ff734d418)

**Comment by stenzek** [comment]
Need a GS dump. This might be fixed on my clear PR (this game uses fbw clears).

**Comment by TunaCat** [comment]
> Need a GS dump. This might be fixed on my clear PR (this game uses fbw clears).

[TUNANarcGS.zip](https://github.com/PCSX2/pcsx2/files/11880983/TUNANarcGS.zip)

Thanks

**Comment by TunaCat** [comment]
PR fixes it.

Pulling PCSX2 from here fixed the issue,
https://github.com/PCSX2/pcsx2/actions/runs/5380663940

![Capture](https://github.com/PCSX2/pcsx2/assets/13092217/bfc2ac05-ee10-45f5-ac4a-00b80f248bb2)

**Comment by stenzek** [comment]
Great, thanks for checking.
