### ISSUE TITLE
Mahou Shoujo Nanoha As Portable The Gears of Destiny - Upscale Level - FPS low

### ISSUE THREAD

**Issue by n1dminhd** [PCSX2/pcsx2#910]
My PC
- Intel Pentium G645 2,9GHZ
- Ram 4GB DRR3
- Nvidia GT 730 _ Latest Driver

- I shut the Upscale Level
- 7x native

![01](https://cloud.githubusercontent.com/assets/4449742/10633521/67276cc2-7815-11e5-9601-820582a323c7.jpg)

- I turned Upscale Level : 5
- 1x native

![02](https://cloud.githubusercontent.com/assets/4449742/10633163/29c89a1a-7813-11e5-94e2-31ec59bd358b.jpg)
- Ram up to 96 % and PC Lag
- But in battle normal

![05](https://cloud.githubusercontent.com/assets/4449742/10633390/8a4ea400-7814-11e5-9666-6279d6fdde19.jpg)

- I turned Upscale Level : 5
- 5x native
- Speed 100 %
- Dragon Ball Z Tenkaichi Tag Team 

![03](https://cloud.githubusercontent.com/assets/4449742/10633407/a3d9d75a-7814-11e5-8eea-7a431e2c62e9.jpg)
![04](https://cloud.githubusercontent.com/assets/4449742/10633406/a3d841e2-7814-11e5-9c0a-a9620ffea32f.jpg)
- Digimon World Re - Digitize (Eng Patch)

![06](https://cloud.githubusercontent.com/assets/4449742/10633448/f9f5b29e-7814-11e5-9418-24bcc2945cef.jpg)
![07](https://cloud.githubusercontent.com/assets/4449742/10633449/f9fb2710-7814-11e5-9aab-c6dd2f4093f2.jpg)

**Comment by ssakash** [comment]
@n1dminhd

I think you came to the wrong place :p

**Comment by n1dminhd** [comment]
I am very sorry

**Comment by ssakash** [comment]
you can just close the issue (or) let the dev's handle the closure of the issue.
