### ISSUE TITLE
[BUG]: Tokimeki Memorial 3 - softlock

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9103]
### Describe the Bug

very early into the game you participate in a school track and field event. if you choose a couple of the options such as the 100 meter or the 3legged race right after the race it goes back to normal text mode except the game won't except inputs to advance the text.

### Reproduction Steps

play to 5/18 and choose one of the first two options at the athletic event. do the event and then get soft locked.

### Expected Behavior

text continues normally.

### PCSX2 Revision

1.7.4650

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### GS Settings

software renderer

### GS Window Screenshots

![Tokimeki Memorial 3_SLPM-65080_20230627213505](https://github.com/PCSX2/pcsx2/assets/8851653/a98e8522-397d-4a56-b630-14ba45b32b8b)

### Logs & Dumps

[SLPM-65080 (39F79CBA).01.zip](https://github.com/PCSX2/pcsx2/files/11889153/SLPM-65080.39F79CBA.01.zip)
save state

thank you 5ch.net

**Comment by seta-san** [comment]
maybe a better savestate before the competition
[SLPM-65080 (39F79CBA).01.zip](https://github.com/PCSX2/pcsx2/files/11889299/SLPM-65080.39F79CBA.01.zip)

**Comment by seta-san** [comment]
i found that the ee timing hack fixes this

**Comment by Mrlinkwii** [comment]
can this be checked on latest nightly

**Comment by seta-san** [comment]
this was fixed by https://github.com/PCSX2/pcsx2/pull/8480 in 1.7.4792
