### ISSUE TITLE
[BUG]: Gran Turismo 4 cant change video output to 480p

### ISSUE THREAD

**Issue by briocheman21** [PCSX2/pcsx2#9105]
### Describe the Bug

I am trying to change the video output in the settings to progressive 480p but every time i select ok it changes back to normal.

### Reproduction Steps

Clicking ok twice after changing output 

### PCSX2 Revision

v1.7.4652

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5500

### GPU

GTX 1050

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/71007793/12612e3a-fe94-480f-b5a6-88d3152ce209)
![image](https://github.com/PCSX2/pcsx2/assets/71007793/18b818ec-40f1-47db-b16d-fca06e63744a)
![image](https://github.com/PCSX2/pcsx2/assets/71007793/26d6aee3-14d4-4cf8-bf57-dee1e0a81376)

**Comment by refractionpcsx2** [comment]
That's normal, the menus don't stay progressive, they are always interlaced, only ingame is progressive.

Not a PCSX2 bug.

**Comment by briocheman21** [comment]
> That's normal, the menus don't stay progressive, they are always interlaced, only ingame is progressive.
> 
> Not a PCSX2 bug.

Thanks
