### ISSUE TITLE
[Feature Request]: Allows Author and Description on lines for groups of cheats

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#9106]
### Description

If pnach file has `author` or `description` property in cheats of `[group]`, PCSX2 shows it in Cheats tab.

example:
```ini 
[group\cheat_1]
pnach=1,EE,20406800,extended,00000000

[group\cheat_2]
pnach=1,EE,20406800,extended,00000040

[group]
author=Name of author
description=Do NOT enable multiple cheats in this group.
```

With above pnach, in Cheats tab, the line of `[group]` has author and description.

### Reason

- It will make author and description of cheats easier to read.
- It will reduce the amount of work involved in editting pnach files.
- When browsing through a series of grouped cheats on the Cheats tab, it is tough to read when they all have the same author and description.
- As an author, it makes no sense to paste same author and description to several grouped cheats.

### Examples

See Description section.

**Comment by stenzek** [comment]
This isn't really possible with how things are set up currently.

The tree view is purely a UI thing. From the patch system's perspective, both of your examples are above are entirely separate cheats, same with the big picture UI.

**Comment by lightningterror** [comment]
Closing as not feasible.
