### ISSUE TITLE
[BUG]: "Shadow of the Colossus" (PAL, SCES-53326) black screen shortly after boot, NTSC version is working

### ISSUE THREAD

**Issue by hoderer** [PCSX2/pcsx2#9117]
### Describe the Bug

The PAL version of "Shadow of the Colossus" (SCES-53326) does not boot properly. It freezes shortly after starting with a black screen. I tried multiple formats (ISO, CHD) and it's always the same. The US version is working. Thanks for looking into it!

### Reproduction Steps

Just boot "Shadow of the Colossus" (Europe, Australia) (En,Fr,De,Es,It).iso or chd (SCES-53326)

### Expected Behavior

The title screen should appear and the game should work (like the us version)

### PCSX2 Revision

 v1.7.4658

### Operating System

Windows 10 (64bit)

### CPU

i7-3930K

### GPU

GTX 1050

**Comment by refractionpcsx2** [comment]
I watched the whole intro (probably for the first time) and it booted absolutely fine.

I would suggest your ISO is broken and you should re-rip your disc. If you need further help, please visit our discord. Thanks.

![image](https://github.com/PCSX2/pcsx2/assets/6278726/ace6cac2-a946-4e1a-8480-dc05088af6b7)

**Comment by hoderer** [comment]
thanks for you quick reply. I had a (probably bad) .pnach-file in the cheats-folder (0F0C4A9C - Shadow of the Colossus SCES-53326.pnach). After deleting it, it worked. Sorry for bothering.

**Comment by refractionpcsx2** [comment]
Glad you found the solution, I forgot to mention patches! I would suggest that cheat is either broken or not for your version of the game.
