### ISSUE TITLE
[Feature Request]: Possibility to create desktop shortcuts for individual games

### ISSUE THREAD

**Issue by ImanolFotia** [PCSX2/pcsx2#9119]
### Description

As the title says, have the possibility to create desktop or taskbar shortcuts for individual games, so a single double click would start the emulator and launch the game as if it was native.
I searched for this feature but it doesn't seem to exist, if there's something that can already accomplish this within the emulator, I'll remove the issue.

### Reason

This will add the possibility to add games to other launchers, and reduce the amount of steps required to play specific games

### Examples

- Right click on the game
- Add shortcut
- Launch the game from the shortcut, even if the emulator is not running

**Comment by refractionpcsx2** [comment]
Duplicate #8349
