### ISSUE TITLE
[BUG]: Translation

### ISSUE THREAD

**Issue by xujibbs** [PCSX2/pcsx2#9122]
### Describe the Bug

Unable to translate below strings
1) Settings-Interface-Theme
2) Settings-Audio-Output Device- Strings "Default"
3) Settings-Network & HDD-DNS1 Address-Strings "Auto""Manual""Internal"

### Reproduction Steps

please update

### PCSX2 Revision

V1.7.4658

### Operating System

Windows 11

**Comment by Berylskid** [comment]
Can you write issue title?

**Comment by xujibbs** [comment]
One more translation error findings: Settings-Graphics-Rendering-Anisotrooic filtering-Strings "off (Default)"

**Comment by stenzek** [comment]
Please add to #9062 rather than creating duplicate issues.
