### ISSUE TITLE
[BUG]: SSX 3 graphical glitch in newest update

### ISSUE THREAD

**Issue by nmcassa** [PCSX2/pcsx2#9124]
### Describe the Bug

![SSX 3_SLUS-20772_20230629222303](https://github.com/PCSX2/pcsx2/assets/72278758/5c909586-bcdc-40fb-a846-87e0ed531cb8)
All popups are black and unreadable. This screenshot is a popup for one of the challenges.

### Reproduction Steps

It seems to be most popups, even when saving the game. I could've messed up something up but it started appearing after the last update.

### Expected Behavior

Normally the popup is readable. I couldn't find a screenshot on google or anything. Hopefully the problem is self explanatory 

### PCSX2 Revision

v1.7.4661

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 2700X

### GPU

Radeon RX 5700 XT

### GS Window Screenshots

![SSX 3_SLUS-20772_20230629222303](https://github.com/PCSX2/pcsx2/assets/72278758/53fa4d2c-371c-4b0a-b922-b9681f05074c)

**Comment by nmcassa** [comment]
![SSX 3_SLUS-20772_20230629224033](https://github.com/PCSX2/pcsx2/assets/72278758/9393dd34-c69a-4b76-b134-eca19c1868f5)
Tried it on a new memory card and it is still like this, here is another example.

**Comment by stenzek** [comment]
GS dump?

**Comment by nmcassa** [comment]
[popup.zip](https://github.com/PCSX2/pcsx2/files/11912513/popup.zip)

**Comment by DigitalMajestic** [comment]
Works on my machine. GS dump is from Mac but I tested both Mac and Windows without issue.

[SSX3-gsdump.zip](https://github.com/PCSX2/pcsx2/files/11913052/SSX3-gsdump.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/3c2d9318-bf3a-42cd-9b48-96f8c92d1a25)
the popup.zip works here in linux  and the gs dump @DigitalMajestic  posted  , 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/b10cfdff-ba8e-43d9-bfb9-1a37bd00e382)
  tho i do have an nvidia card  @nmcassa   can you please update and see if it still happens

**Comment by refractionpcsx2** [comment]
probably the line problem, try 4662 and see if that's ok

**Comment by stenzek** [comment]
Looks fine even on 4661 for me.

**Comment by refractionpcsx2** [comment]
sure, it was an AMD only problem :P

**Comment by stenzek** [comment]
Yeah, just checked, and it is drawing lines, just at the very end.

So it's probably fixed already.

**Comment by nmcassa** [comment]
It's working now. Thanks for the help guys!
