### ISSUE TITLE
[BUG]: FIFA Street 2 [Demo] SLED-53953 flag flashes corrupt sprites in software renderer

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#9127]
### Describe the Bug

during the gameplay the left hand flag keeps flashing corrupt sprites 

### Reproduction Steps

load game and play

### PCSX2 Revision

v1.7.4662

### Operating System

Windows 11

### CPU

Ryzen 7 5700X

### GPU

NVIDIA RTX 3060

### Logs & Dumps

here is a GS dump
https://mega.nz/file/YrJl3T6B#dMauJP-RddsRzCOrYS5208UYWLcWTfABko6ui8ubhVE

**Comment by refractionpcsx2** [comment]
probably needs the GIF FIFO gamefix for that, then EE Cycle Rate 300% for the uniforms ingame

**Comment by stenzek** [comment]
That was the first thing I looked for, gamedb already has GIF FIFO set.

**Comment by refractionpcsx2** [comment]
The heck, then game fixes must be disabled.

**Comment by stenzek** [comment]
Or it's not detecting the game correctly.

@benderscruffy can you check the log window for where it says "Disc Changed to ..." (it should be in green text), and paste the next few lines (Name/Serial/Version/CRC)?

**Comment by benderscruffy** [comment]
Name: FIFA Street 2 [Demo]
Serial: SLED-53953
Version: 1.00
CRC: 17BCD7B1
and i notice the name tag in the bottom left is also flashing the corrupt sprites aswell

**Comment by stenzek** [comment]
Should be picking up the gamefix then. Maybe the demo needs something different..

**Comment by refractionpcsx2** [comment]
can you provide a blockdump up to the point the flags show? You will need to enable it, boot the game, get to the point the flags show up, and wait there for like 10-15 seconds, then exit pcsx2 gracefully, then zip up the blockdump it made (will have the same name as your iso but end in .dump) and put it here, then we can check it.

**Comment by benderscruffy** [comment]
how do i enable the blockdump please ??

**Comment by benderscruffy** [comment]
here is the blockdump
[FIFA Street 2 (Europe) (Demo) (2023-07-01 12-54-45).zip](https://github.com/PCSX2/pcsx2/files/11924542/FIFA.Street.2.Europe.Demo.2023-07-01.12-54-45.zip)

**Comment by refractionpcsx2** [comment]
Thanks, go in to Settings->Game Properties then under the emulation tab change your Cycle Rate to 300%, then your problem will go away

**Comment by refractionpcsx2** [comment]
Been added to the DB
