### ISSUE TITLE
[BUG]: no analog stick movement in Sky Odyssey

### ISSUE THREAD

**Issue by omegadragon** [PCSX2/pcsx2#9131]
### Describe the Bug

the analog sticks  don't work in the game  after starting it.  i have the control input osd shown it confirms the program is picking up the controls looks like they are not being passed to the game properly.

### Reproduction Steps

start game analog sticks don't move menus or the planes rudders,ailerons,flaps,etc  (both sticks control them) 

### Expected Behavior

menu moves and plane controllable with the 

### PCSX2 Revision

1.7.4666

### Operating System

Windows 10 (64bit)

### CPU

ryzen 9 3900x

### GPU

nvida gtx 980 (evga sc)

**Comment by Mrlinkwii** [comment]
You have to press the analog button , to enable the analog sticks

**Comment by omegadragon** [comment]
XD they worked in older versions of the emulator (1.4) without that  but im assuming that was workaround/bug in that version ROFL fun fun thanks. kinda forgot that was required on the ps2 :)

**Comment by Mrlinkwii** [comment]
no worries , happy to help :)
