### ISSUE TITLE
[BUG]: Wrestle Kingdom - health gages break

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9132]
### Describe the Bug

the health gages break in game
does it in hardware
![Wrestle Kingdom_SLPM-66401_20230630154343](https://github.com/PCSX2/pcsx2/assets/8851653/10c46d86-4c4d-41e7-8de3-24e8ebaf089d)

### Reproduction Steps

start game
choose FREE FIGHT
play and lose
rematch (first option)
the health bars are screwd up

### Expected Behavior

![Wrestle Kingdom_SLPM-66401_20230630154844](https://github.com/PCSX2/pcsx2/assets/8851653/523b587d-64d5-4154-a857-2f6260a8cba6)

### PCSX2 Revision

1.7.4666

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Wrestle Kingdom_SLPM-66401_20230630154343.gs.zip](https://github.com/PCSX2/pcsx2/files/11923165/Wrestle.Kingdom_SLPM-66401_20230630154343.gs.zip)

**Comment by refractionpcsx2** [comment]
can you boot the game in software and see if it's fine, please :)

**Comment by seta-san** [comment]
Already tried.  It was broken slightly different

**Comment by refractionpcsx2** [comment]
can you show it please?

**Comment by seta-san** [comment]
When I get home. Picking up my son.

**Comment by refractionpcsx2** [comment]
alright, thanks

**Comment by seta-san** [comment]
never mind it's not showing in software. from boot

**Comment by refractionpcsx2** [comment]
do you mean the UI isn't showing or the bug isn't showing?

**Comment by seta-san** [comment]
The bug doesn’t show when booting into software.

**Comment by refractionpcsx2** [comment]
ok thanks

**Comment by refractionpcsx2** [comment]
Can't reproduce this, what's the easiest way to make this happen? I went through "Drama" mode and I had health bars.

**Comment by seta-san** [comment]
start game
choose FREE FIGHT
play and lose match
rematch (first option)
the health bars are screwd up

**Comment by refractionpcsx2** [comment]
Cool, seems fixed on #9315

**Comment by seta-san** [comment]
so it is~! excellent work
