### ISSUE TITLE
[BUG]: JOGO CARREGA ATÉ UMA PARTE, TRAVA E FECHA O PSCX2

### ISSUE THREAD

**Issue by LeoBilhalva** [PCSX2/pcsx2#9133]
### Describe the Bug

Boa noite, tudo certo?
Estou encontrando problemas ao executar dois jogos, naruto shippuden ultimate ninja 5 e Def Jam - Fight For NY. Os dois jogos aparentemente constam os mesmos problemas, travam após as cutscenes e fecha o PCSX2. Procurei em vários lugares, atualizei arquivos C++, reiniciei o pc, porém nada adiantou.

Conto com ajuda para resolução desse problema, em anexo o arquivo crash.
[crash-2023-06-30-20-17-12-914.txt](https://github.com/PCSX2/pcsx2/files/11923700/crash-2023-06-30-20-17-12-914.txt)

### Reproduction Steps

Após as cutscenes do jogo.

### Expected Behavior

Após as cutscenes do jogo. 

### PCSX2 Revision

1.7.4666

### Operating System

Windows 10 (64bit)

**Comment by LeoBilhalva** [comment]
Esqueci de insinuar... Rodei somente esses dois jogos.

**Comment by stenzek** [comment]
1. Sorry, we only accept bug reports in English.
2. The bug tracker is not for support, please use the Discord server for that (also in English, unless there's a volunteer who can speak your language).
3. These games run fine.
