### ISSUE TITLE
[BUG]: QT/GUI Memory Card Port Column not entirely visible

### ISSUE THREAD

**Issue by mrtawsiti3** [PCSX2/pcsx2#9139]
### Describe the Bug

Memory Card Port Column is not entirely visible when you rename it with a long name
( since the name is long the bar for scrolling left and right appears over it and it covers what it should not cover )

![PCSX2 QT GUI](https://github.com/PCSX2/pcsx2/assets/35630219/79d1b165-5fd4-4f3c-8a67-0c46ea76ff2e)

### Reproduction Steps

Create Memory Card and name it with a long name

### PCSX2 Revision

v1.7.4667

### Operating System

Windows 10 (64bit)

**Comment by DigitalMajestic** [comment]
Still an issue on version 1.7.4929. Tested on Mac.
