### ISSUE TITLE
[BUG]: Inconsistent behaviour with analog buttons; they're either inverted or have a high deadzone

### ISSUE THREAD

**Issue by Mikki-m8** [PCSX2/pcsx2#9140]
### Describe the Bug

Note that I'm using Wayland on Linux and this might be perfectly fine for Windows machines depending on drivers, but I have no way to test it. 

I'm using a DualShock 3 which has support for pressure sensitive buttons. Whenever I go manually map an input, the registered mapping will be different based on how hard I pressed the button. For example, if I were to press D-Pad Down, it will say `SDL-0/-Axis19` for a normal press, `SDL-0/+Axis19` for a hard press. Sometimes it will also say `SDL-0/FullAxis~` and `SDL-0/+Axis19~`, I have no idea what those mean but they also don't function anyway.

On padtest, if the binding is `-Axis19`, it will say 0 input until I press it even lightly, then it will be at 255, at which point the harder I press will lower the input received. The same is true for `FullAxis19~` and `+Axis19~`.  The binding `+Axis19` (no `~`) doesn't have this issue, and functions exactly how an analog button should. Unfortunately, even though the analog function works, it will read 0 input until it reaches what I would consider a hard press, almost as if it has a really high deadzone. Changing the sensitivity makes no difference. Both these factors make any game basically unplayable. 

Manually editing the .ini so it only has 'SDL-0/DPadDown' works for actual gameplay, but then you will only have digital input which is detrimental to a handful of games. 

I don't know if this is a bug with PCSX2 or with SDL either, but this is the only application I've ran into this issue with. 

### Reproduction Steps

Using a controller with pressure sensitive buttons, go to controller settings and shift-click an input. 
Click add binding, then press a button on the controller lightly. Click add binding again, and this time press the same button as hard as you can. Repeat. 

### Expected Behavior

The same input to be registered with each press. Instead you could have 2-4 different inputs with the same button. 

### PCSX2 Revision

v1.7.4671

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by stenzek** [comment]
Evidently I missed this one, sounds like you need to create a GameControllerDB entry for your controller. If it's reporting high numbered axes, that means it's coming through as a joystick instead.

See https://github.com/gabomdq/SDL_GameControllerDB

**Comment by Chopper1337** [comment]
@Mikki-m8 did you work anything out with this? I'm having the same issue on a DS3 controller.
