### ISSUE TITLE
[BUG]:  Metal Gear Solid 3 Snake Eater Skipping intro cutscene shows garbage.

### ISSUE THREAD

**Issue by bigol83** [PCSX2/pcsx2#9143]
### Describe the Bug

When starting Metal Gear Solid 3 PAL ITA trying to skip the final part of intro cutscene shows a flash of garbage. 

I tried with every renderer, it happens with DX, Vulkan and OpenGL even at native resolution. It doesn't happen with software renderer.

 

### Reproduction Steps

Start MGS3, skip several intro cutscenes until you see garbage. 

### Expected Behavior

No garbage when skipping cutscenes. 

### PCSX2 Revision

pcsx2 1.7.4672

### Operating System

Windows 10 (64bit)

### CPU

intel g4560

### GPU

nvidia gtx 1050 ti

### Logs & Dumps

GS dump

[Metal Gear Solid 3 - Snake Eater_SLES-82024_20230702115415.zip](https://github.com/PCSX2/pcsx2/files/11929182/Metal.Gear.Solid.3.-.Snake.Eater_SLES-82024_20230702115415.zip)

Video showing the issue

https://github.com/PCSX2/pcsx2/assets/38129260/73cc0639-d9fc-4cce-ad66-fabd084e4563

**Comment by refractionpcsx2** [comment]
Do you know when this started happening?

**Comment by bigol83** [comment]
Don't know, i just tested yesterday build 1.7.4671 to exclude it was because of this PR https://github.com/PCSX2/pcsx2/pull/8961but it still has the same issue. So, at least we can say it's not because of that.  

Will check previous builds and try to find the build it started when i have time.

**Comment by bigol83** [comment]
So, i just checked and the build that started this issue is 1.7.4483, that is this PR https://github.com/PCSX2/pcsx2/pull/8780

All the builds before this one don't have this issue.

**Comment by refractionpcsx2** [comment]
Thanks for checking :) It looks like invalidation is just breaking down for some reason, I think it worked before by chance. I'm working on a fix, but of course it has knock on effects like everything in our GS emulation...
