### ISSUE TITLE
Siren: Wall of fog, Double half clear issue.

### ISSUE THREAD

**Issue by weirdbeardgame** [PCSX2/pcsx2#9147]
### Describe the Bug

In the stages with fog there's a fog that is covering the screen, https://github.com/PCSX2/pcsx2/issues/2004 - previous issue about it.

The fog happens because of a double half clear effect that ref had previously fixed now seems to be borked again.

### Reproduction Steps

Play siren in hw mode

### Expected Behavior

The fog should render correctly 

### PCSX2 Revision

v1.7.4673

### Operating System

Linux

### If Linux - Specify Distro

Arch

### CPU

Ryzen 3700x

### GPU

6950xt

### GS Settings

Defaults except for upscale

### Emulation Settings

Defaults 

### Logs & Dumps
[Siren_SCUS-97355.zip](https://github.com/PCSX2/pcsx2/files/11931986/Siren_SCUS-97355.zip)

**Comment by weirdbeardgame** [comment]
Doesn't look like the GS dump uploaded right.

**Comment by refractionpcsx2** [comment]
[Siren_SCUS-97355_20230405024138.gs.zip](https://github.com/PCSX2/pcsx2/files/11931511/Siren_SCUS-97355_20230405024138.gs.zip)

Here's the old dump.
