### ISSUE TITLE
[BUG]: Blue background appear in help messages in Persona 3 FES

### ISSUE THREAD

**Issue by RVRZERO** [PCSX2/pcsx2#9149]
### Describe the Bug

Help messages in Persona 3 FES now causes the screen to be fully covered with blue background.

### Reproduction Steps

Just trigger any help message in the game in any PCSX2 version latest than 1.7.4671 (In another word 1.7.4672+):

![Help Screen Bug](https://github.com/PCSX2/pcsx2/assets/132889991/e1979b1e-7ef4-4009-9a55-d662252217e9)

### Expected Behavior

A help screen with no blue background. This screenshot is from version 1.7.4671:

![Help Screen no Bug](https://github.com/PCSX2/pcsx2/assets/132889991/63b928cc-22db-42ce-8893-1eca43d9c095)

### PCSX2 Revision

1.7.4674

### Operating System

Windows 10 (64bit)

### CPU

i7-7700K

### GPU

GTX 1080 TI

**Comment by lightningterror** [comment]
Can you upload a gs dump?

**Comment by RVRZERO** [comment]
Yeah sure.
[Shin Megami Tensei - Persona 3 FES_SLUS-21621_20230703033338.gs.zip](https://github.com/PCSX2/pcsx2/files/11931888/Shin.Megami.Tensei.-.Persona.3.FES_SLUS-21621_20230703033338.gs.zip)
