### ISSUE TITLE
Jikkyou World Soccer 2000: Final Edition (SLPM-62040) Displays Wrong Name in Console

### ISSUE THREAD

**Issue by DisorderIy** [PCSX2/pcsx2#915]
Don't think this is really a serious issue, but when playing Jikkyou World Soccer 2000: Final Edition, "J-League Winning Eleven 8: Asia Championship" is displayed in the console. Strangely, the serial number displayed is actually correct (SLPM-62040.)

I don't have J-League Winning Eleven 8: Asia Championship, but I'm curious as to what is displayed when that game is played.

**Comment by refractionpcsx2** [comment]
Sounds like it was just wrong in the sony index, we can fix that and check for a duplicate entry :)
