### ISSUE TITLE
[Feature Request]: gamepad vibration used as Force Feedback

### ISSUE THREAD

**Issue by re-bug** [PCSX2/pcsx2#9152]
### Description

I would like the allowance to utilize the vibration motors in a gamepad for the Force Feedback function.

### Reason

I make use of an Xbox 360 Wireless Speed Wheel, which is designed to be identifed as a regular gamepad and utilizes its vibration motors for the implementation of Force Feedback, to emulate the Logitech Driving Force.

This would contribute to a better control of the car; I've found myself unable to correctly determine when to countersteer in 'Gran Turismo 4' repeatedly.

### Examples

· 'GRID 2' on PC (the very only game I've played where this feature is made use of)
· 'Forza Motorsport 4' on Xbox 360
(the blinking green lights at the top of the controller are linked to the vibration motors)

**Comment by stenzek** [comment]
I don't really see how this would be possible without introducing a ton of additional complexity into how vibration is handled. You'd need to map the two vibration intensities to FF effects (probably constant), but that would require user configuration/tweakability, which doesn't fit into the current UI anywhere.

Force feedback in PCSX2 is local to USB, specifically USB wheels. The input system is completely unaware of it.

So, if anyone else wants to do this, please feel free, but it's out of scope for us.
