### ISSUE TITLE
[BUG]: Okage - Shadow King Depth of Field Glitch

### ISSUE THREAD

**Issue by TailsGuy** [PCSX2/pcsx2#9161]
### Describe the Bug

The game was quite an intense depth of field effect throughout the entire game, however on any renderer other than the Software Renderer, it's glitched. Actually, the effect is glitched as a whole, because the intensity isn't as it should be for anything very far from the camera.

There's an after image above many of the geometry found in the game, and while it's natural that anything gets blurrier the farther it gets from the camera, it gets very strange on the usual renderers. There's also a glitch in the night about 30 minutes into the game where Ari goes to the circus, however I didn't have GS Dump for that, so this will do for now.

### Reproduction Steps

Simply go outside of your house, and behold.
The effect is seen on Native resolution, so it isn't a resolution problem. 

However, the effect is much better understood at higher resolutions.

### Expected Behavior

There should be no double imaging effect on the models in the game

### PCSX2 Revision

1.7.4681

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5700X (Undervolted, 4850mhz, Pretty stable.)

### GPU

EVGA GeForce RTX 3070 FTW3 Ultra (Not Undervolted or Overclocked)

### GS Settings

Everything is default.

### Emulation Settings

Everything is default, however I *think* using the no interlacing patch mitigates this double image effect.
However, that is certainly not the origin of the problem, Software Rendering solves this, *and* it's still interlaced.

I have the game on disc, and can test it on a CFW PS3 with some emulation.

### GS Window Screenshots

![Okage - Shadow King_SCUS-97129_20230704073925](https://github.com/PCSX2/pcsx2/assets/70661792/30fd1a88-6f8f-42f7-b974-b619531a39cc)
![Okage - Shadow King_SCUS-97129_20230704073948](https://github.com/PCSX2/pcsx2/assets/70661792/1aebbe57-9460-4886-a3a6-be8f6b310698)

### Logs & Dumps

[Okage - Shadow King GSDump.zip](https://github.com/PCSX2/pcsx2/files/11949014/Okage.-.Shadow.King.GSDump.zip)

**Comment by stenzek** [comment]
Channel shuffle which we're not currently handling (it doesn't have any region repeat that we can select channels from).

There's a bunch of games that do this. We'll probably need to analyze the UVs instead.

![image](https://github.com/PCSX2/pcsx2/assets/11288319/e89745b7-41ea-4554-9341-a89f4d40ebdb)

**Comment by TailsGuy** [comment]
Ah, I see. Thanks for the hard work on this emulator, by the way.
