### ISSUE TITLE
[BUG]: Several Inexplicable Graphical Glitches in Dirge of Cerberus - Final Fantasy VII [SLUS-21419]

### ISSUE THREAD

**Issue by TailsGuy** [PCSX2/pcsx2#9163]
### Describe the Bug

Various bugs ranging from broken shadows and white textures flashing on screen plague the tutorial section of the game.
Broken shadows are prevalent in Vulkan, but the majority if not all GSDumps and pictures I took were in OpenGL, since after the shadows I figured I'd change renderers to see what the problem was, and white textures flash in, and slowly fade out.

I have several dumps.

All glitches are present in Native and any other resolution. There are also clusters of glitched pixels on the titlescreen of the game in Vulkan and OpenGL, so I'm assuming these glitches are relevant in all renderers except Software Mode.

### Reproduction Steps

Simply have any graphics renderer on, and enter the game. It should be immediately apparent what is wrong on the title screen after the intro FMV, and chose "Tutorial Menu" and play for a while in the tutorial. I think it's around Section Fiva and Six where the shadow and texture glitches become noticeable.

### Expected Behavior

Well... none of the texture files should be visible.
And also, of course, there aren't darkened squares in the occasional spot.

### PCSX2 Revision

1.7.4682

### Operating System

Windows 11

### CPU

AMD Ryzen 7 5700X (Undervolted, 4850mhz, Pretty stable.)

### GPU

EVGA GeForce RTX 3070 FTW3 Ultra (Not Undervolted or Overclocked)

### GS Settings

Everything is default, however I switched to 2X rendering occasionally. 

### Emulation Settings

Everything is default.

### GS Window Screenshots

![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102705](https://github.com/PCSX2/pcsx2/assets/70661792/5abc7f22-934f-4f15-ad3d-e81364e117de)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102737](https://github.com/PCSX2/pcsx2/assets/70661792/0c400ae4-ceb0-4c6c-b999-4bb6ebdf95bb)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102824](https://github.com/PCSX2/pcsx2/assets/70661792/05f38e66-a539-4edf-9f97-42958d54bd38)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102830](https://github.com/PCSX2/pcsx2/assets/70661792/535602d2-01b2-4d5e-a1ed-1026a93b4183)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704103354](https://github.com/PCSX2/pcsx2/assets/70661792/037984e0-e049-4da5-ba76-8957dd27ce4c)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704103403](https://github.com/PCSX2/pcsx2/assets/70661792/dd907db5-db63-4a2b-a987-afa687ed5601)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102422](https://github.com/PCSX2/pcsx2/assets/70661792/df195959-9df2-41cd-9a92-993e58b73252)
![Dirge of Cerberus - Final Fantasy VII_SLUS-21419_20230704102458](https://github.com/PCSX2/pcsx2/assets/70661792/45c7b045-4f51-4ef4-a42c-86a71e440744)

### Logs & Dumps

[Dirge 1.zip](https://github.com/PCSX2/pcsx2/files/11950411/Dirge.1.zip)
[Dirge 2.zip](https://github.com/PCSX2/pcsx2/files/11950412/Dirge.2.zip)
[Dirge 3.zip](https://github.com/PCSX2/pcsx2/files/11950413/Dirge.3.zip)

**Comment by stenzek** [comment]
All the GS dumps look fine apart from the shadows :/

Might be junk getting in the TC somehow, and not getting invalidated.
