### ISSUE TITLE
[BUG]: Broken UI and HUD on WWE SmackDown Here Comes The Pain

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#9167]
### Describe the Bug

#9150 seems to have cause a regression on WWE SmackDown Here Comes The Pain where it causes the HUD, UI and Pause menu to be missing.

![image](https://github.com/PCSX2/pcsx2/assets/14798312/ca291978-6978-4e14-a35c-095b8999a409)

Rolling back to v1.7.4675 fixes the issue.

### Reproduction Steps

1. Just boot up the game
2. Go into any match
3. Observe the UI and Pause menu is broken

### Expected Behavior

The UI/HUD shows up just fine
![WWE SmackDown! Here Comes the Pain_SLUS-20787_20230705154738](https://github.com/PCSX2/pcsx2/assets/14798312/64c0e958-9f6a-40f4-98c7-ccd1d4714c00)

### PCSX2 Revision

v1.7.4683

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

GS Dump:
[WWE SmackDown! Here Comes the Pain_SLUS-20787_20230705154738.zip](https://github.com/PCSX2/pcsx2/files/11955889/WWE.SmackDown.Here.Comes.the.Pain_SLUS-20787_20230705154738.zip)

**Comment by refractionpcsx2** [comment]
Pretty sure the wwe games have been broken since the first clear pr, not the regression fixes. Maybe in a different way, but it was already broken
