### ISSUE TITLE
[GSdx Hardware] Conflict - Desert Storm [PAL]

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#917]
***PCSX2 versions used:*** 
*pcsx2-v1.3.1-1304-g059d4a1-windows-x86
*pcsx2-v1.3.1-1292-gaff1467-windows-x86
*pcsx2-v1.3.1-842-g1f402b1-windows-x86
*pcsx2-v1.3.1-799-g000e11e-windows-x86
*pcsx2-v1.3.1-699-gc660ea8-windows-x86
*pcsx2-v1.3.1-641-gde644c5-windows-x86 (first available build with bug)
*pcsx2-v1.3.1-590-gcd8e31d-windows-x86 (bug does not occur here)
*pcsx2-v1.3.1-495-g4e82073-windows-x86 (bug does not occur here)

***Emulation settings:*** "Safest" preset, no hacks.

***Plugins used:*** GSdx-AVX2, cddvdGigaherz

***Plugin settings:*** CRC Hack Level "None"

#### Hardware Specifications 
***CPU:*** Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
***GPU:*** NVIDIA GeForce GTX 970 (Driver: NVIDIA 358.50)

#### Description
This is from the demo version in ops2m demo 33. 
None of the hardware renderers are able to draw the game without glitches.
Textures flicker, cycling from all black, wrong color. Even some HUD elements and text seem to flicker.
Software mode does not have the bug. Software mode without mipmapping also does not have the bug.

EE/FPU and VU0/VU1 Round/Clamping modes have no effect on the bug.
The bug also happens with the superVU dynarec.
None of the EE, FPU, VU, VIF1, DMAC, OPH Flag, Path 3 transfer related "game fixes" affect the bug.

#### Video
In the video I'm starting with  OGL HW renderer and toggling back into the SW renderer and back again to HW.
https://vid.me/W0we

***GS dump***:  http://forums.pcsx2.net/attachment.php?aid=57694

The issue seems to be caused by #628

**Comment by refractionpcsx2** [comment]
I'm assuming this happens in DX as well?

**Comment by ssakash** [comment]
Yes, every hardware renderers have this flickering issue after merge of #628. too lazy to check all the commits at the PR -_-  (I'll check if there are no leads yet)

**Comment by gregory38** [comment]
What is the regression exactly?

Edit: plugins/GSdx/GSRendererHW.cpp and replace the following 2 lines
```
	const bool no_rt = (context->ALPHA.IsCd() && PRIM->ABE && (context->FRAME.PSM == 1));
	const bool no_ds = !no_rt && (context->FRAME.FBP == context->ZBUF.ZBP && !PRIM->TME && !context->ZBUF.ZMSK && !context->FRAME.FBMSK && context->TEST.ZTE);
```
by
```
	const bool no_rt = false;
	const bool no_ds = false;
```

**Comment by refractionpcsx2** [comment]
@gregory38 the regression is apparently on OGL and DX, which is why I've tagged it as a TC regression.

**Comment by ssakash** [comment]
> Edit: plugins/GSdx/GSRendererHW.cpp and replace the following 2 lines

    const bool no_rt = (context->ALPHA.IsCd() && PRIM->ABE && (context->FRAME.PSM == 1));
    const bool no_ds = !no_rt && (context->FRAME.FBP == context->ZBUF.ZBP && !PRIM->TME && !context->ZBUF.ZMSK && !context->FRAME.FBMSK && context->TEST.ZTE);

> by

    const bool no_rt = false;
    const bool no_ds = false;

@gregory38 : The Flickering issues are still present after applying this change to the master branch.

**Comment by gregory38** [comment]
Snif. I will look into it when I have some free times.

**Comment by gregory38** [comment]
So there is a texture that isn't properly invalidated after a write. The branch barely touch this code.
On my side, ```cd8e31d85f555f71a9cfc313c65c54733e4770aa``` doesn't work. Could you confirm the good version.

**Comment by gregory38** [comment]
Thanks git bisect :)
```
85543db094af490a7b1dc3b2bfb3087cde92d9cb is the first bad commit
commit 85543db094af490a7b1dc3b2bfb3087cde92d9cb
Author: Gregory Hainaut <gregory.hainaut@gmail.com>
Date:   Thu Jun 25 19:09:26 2015 +0200

    gsdx-tc: trace the alpha channel update in TC
    
    Improve the rendering in MGS3 (even if the game is still broken
    due to others TC issues)
    
    // Typical bug (MGS3 blue cloud):
    // 1/ RT used as 32 bits => alpha channel written
    // 2/ RT used as 24 bits => no update of alpha channel
    // 3/ Lookup of texture that used alpha channel as index, HasSharedBits will return false
    //    because of the previous draw call format
    //
    // Solution: consider the RT as 32 bits if the alpha was used in the past

:040000 040000 0cbb96e24df616c082641f0b3908a0987753c9b6 222f71921c85401c14466bd26f7181306891e65e M	plugins
```

**Comment by refractionpcsx2** [comment]
Well caught :P

**Comment by gregory38** [comment]
The commit only impact a single if statement. Just a revert fix the game but likely break other. Now I need to remember what does this alpha channel trick :p

**Comment by refractionpcsx2** [comment]
As we say in england, I think you have opened a can of worms :P

**Comment by gregory38** [comment]
GSdx is at least a minefield :p

**Comment by ssakash** [comment]
Updated the status to resolved on the forums, awesome work @gigaherz  :+1:

**Comment by ssakash** [comment]
(stupid mobile) , I meant @gregory38
