### ISSUE TITLE
[BUG]: Onimusha 3, line down middle of screen when upscaling

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#9172]
### Describe the Bug

Gives line down middle of screen 

### Reproduction Steps

Go into sewer level in Paris 

### Expected Behavior

No line down middle,  might be another regression 

### PCSX2 Revision

1.7.4683

### Operating System

Windows 11

### CPU

I9-13900K

### GPU

4090

### GS Window Screenshots

![pcsx2-qtx64_2023-07-05_17-47-27](https://github.com/PCSX2/pcsx2/assets/60486562/aef527a5-084c-462b-9851-0d7de23dccd9)

### Logs & Dumps

[Onimusha_3_-_Demon_Siege_SLUS-20694_20230705180044.zip](https://github.com/PCSX2/pcsx2/files/11959882/Onimusha_3_-_Demon_Siege_SLUS-20694_20230705180044.zip)

**Comment by DrunkRichtofen** [comment]
Been going through the game and have so far seen this issue in the Arc de Triompe staircase area and most of the Sewer area. I'll keep going through and update on more areas that have this issue. I'll also go back a few biulds to try and narrow down when this occured, as I am fairly certain that this is a regression

**Comment by DrunkRichtofen** [comment]
I have managed to find the build that this regression was introduced in. It first appeared in v1.7.4672

**Comment by washingleavesandthensome23-434** [comment]
Can we have a build too test , I never can figure this out😕

**Comment by washingleavesandthensome23-434** [comment]
> Can you try it on here just to rule it out being already fixed: #9171

Can we have a build too test , I never can figure this out for the life of me😕

**Comment by bigol83** [comment]
Tested your dump with PR #9171. Line is still there at default settings. But it's an upscaling issue, because it doesn't happen at native resolution on hardware renderers.

**Comment by washingleavesandthensome23-434** [comment]
Interesting 😕 so a upscale regression?

**Comment by stenzek** [comment]
As with many things, it was only working before by chance. Now the target gets cleared out as it should.

Real issue is that it's bilinearing the dirty upload, causing the pixels at column 64 (upscaled column 128) to leak into 63 (upscaled column 127).

![image](https://github.com/PCSX2/pcsx2/assets/11288319/8f3cc945-7920-47ec-b61b-40863ce7cc03)

![image](https://github.com/PCSX2/pcsx2/assets/11288319/bad424b8-de5b-40c8-af4f-bd9dc2a028c8)

**Comment by washingleavesandthensome23-434** [comment]
Oh wow ...😕

**Comment by washingleavesandthensome23-434** [comment]
Noticed another issue, 

Hud missaligment issue



Can ya fix the emulator so auto fixes aren't needed, that way it shouldnt be an issue

**Comment by Mrlinkwii** [comment]
@washingleavesandthensome23-434  can i have a gs dump

**Comment by JordanTheToaster** [comment]
> Noticed another issue,
> 
> Hud missaligment
> 
> ![image_7-7-23_22-53-19](https://user-images.githubusercontent.com/60486562/251858474-8c7b70ce-c805-4dba-8df0-f4904107a052.png)
> 
> ![image_7-7-23_22-49-53](https://user-images.githubusercontent.com/60486562/251857819-3b90dbe4-1190-40a9-b7d5-69655e856f8f.png)
> 
> Can ya fix the emulator so auto fixes aren't needed, that way it shouldnt be an issue

While we'd love to pull a fix out of thin air for every issue that simply isn't possible and fixed are necessary.

**Comment by washingleavesandthensome23-434** [comment]
> @washingleavesandthensome23-434 can i have a gs dump

Yup a sec

**Comment by washingleavesandthensome23-434** [comment]
> > Noticed another issue,
> > Hud missaligment
> > ![image_7-7-23_22-53-19](https://user-images.githubusercontent.com/60486562/251858474-8c7b70ce-c805-4dba-8df0-f4904107a052.png)
> > ![image_7-7-23_22-49-53](https://user-images.githubusercontent.com/60486562/251857819-3b90dbe4-1190-40a9-b7d5-69655e856f8f.png)
> > Can ya fix the emulator so auto fixes aren't needed, that way it shouldnt be an issue
> 
> While we'd love to pull a fix out of thin air for every issue that simply isn't possible and fixes are necessary.

Very true

**Comment by RedDevilus** [comment]
> Noticed another issue, 
> 
> Hud missaligment 
> 
> ![image_7-7-23_22-53-19](https://github.com/PCSX2/pcsx2/assets/60486562/8c7b70ce-c805-4dba-8df0-f4904107a052)
> 
> 
> ![image_7-7-23_22-49-53](https://github.com/PCSX2/pcsx2/assets/60486562/3b90dbe4-1190-40a9-b7d5-69655e856f8f)
> 
> 
> Can ya fix the emulator so auto fixes aren't needed, that way it shouldnt be an issue

There aren't generic solutions and even so it would be multiple if else cases, the automatic fixes are pieces of code that can be shared between games if needed. 

It doesn't make it easier and some would label it as hacks but they are conveniences, if you want authentic experience there is still the software renderer.

**Comment by washingleavesandthensome23-434** [comment]
No I just was thinking bout solutions here don't misunderstand 🙂

**Comment by washingleavesandthensome23-434** [comment]
> @washingleavesandthensome23-434 can i have a gs dump

Dumps here

**Comment by refractionpcsx2** [comment]
> Can ya fix the emulator so auto fixes aren't needed, that way it shouldnt be an issue

Sure but I'm sorry, your computer is no longer capable of running ps2 games above 5fps and you can't go above native resolution.

Is that the answer you want? because otherwise your request is impossible :P

**Comment by washingleavesandthensome23-434** [comment]
As I said i was just making suggestions of possible fixes , I dunno what would be the proper way 😕 sorry

**Comment by washingleavesandthensome23-434** [comment]
Holy shit! Thank you!!! @stenzek , you are truly amazing 👏 👊😎
