### ISSUE TITLE
[BUG]: Changing the Internal Resolution causes games to be letterboxed.

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#9174]
### Describe the Bug

I used to have an issue when I sometimes reinstall PCSX2 and change the Internal Resolution. Most of the games and sometimes all games will be in letterbox except if I keep the resolution to 5K. This keeps happening and I reinstalled it yesterday and it seems like the bug is not taking effect but I'll have to be careful. 

### Reproduction Steps

Try to reinstall it
Update graphics drivers

### PCSX2 Revision

v1.7.4683

### Operating System

Windows 10 (64bit)

**Comment by weirdbeardgame** [comment]
And does changing the aspect ratio not do anything?

**Comment by AkihitoZero5454** [comment]
> And does changing the aspect ratio not do anything?

Nope

**Comment by stenzek** [comment]
Can't say I've ever experienced this, and without reproduction steps this is an invalid report.

Please use the Discord server for support.
