### ISSUE TITLE
[BUG]: Video Capture Freezes on Reset

### ISSUE THREAD

**Issue by sestain** [PCSX2/pcsx2#9176]
### Describe the Bug

If I start recording right after a reset, the emulator will freeze. If I'm recording and reset, the same thing happens.

### Reproduction Steps

First way:
Start game, pause emu, reset emu, start video capture, can't unpause (emu frozen).

Second way:
Start game, wait until the game starts, start video capture, reset, emu frozen.

### Expected Behavior

It should continue emulation without freezing when trying to record a reset (maybe by inserting blank frames into ffmpeg).

### PCSX2 Revision

v1.7.4683

### Operating System

Windows 11

### CPU

i5-12400F

### GPU

RTX 2080 Ti

### GS Settings

Bilinear Filtering: None
Show Overscan: Checked
Internal Resolution: 2x Native (~720p)
Dithering: Off
![image](https://github.com/PCSX2/pcsx2/assets/35299377/355f6d85-74c7-41e8-9c51-740887c0cb22)

### Emulation Settings

Enable Multithreaded VU1 (MTVU): Unchecked
Optimal Frame Pacing: Checked
Pause On TLB Miss: Checked

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/11962983/emulog.txt)

**Comment by stenzek** [comment]
> It should continue emulation without freezing when trying to record a reset (maybe by inserting blank frames into ffmpeg).

It'll have to stop the recording, because the resolution will temporarily change.

**Comment by kamfretoz** [comment]
> > It should continue emulation without freezing when trying to record a reset (maybe by inserting blank frames into ffmpeg).
> 
> It'll have to stop the recording, because the resolution will temporarily change.

Another small thing i notice is that switching from HW to SW renderer while recording also internally stops the recording but the Qt UI itself still thinks that the recording is still ongoing, it doesn't properly update the recording state.

**Comment by stenzek** [comment]
> Another small thing i notice is that switching from HW to SW renderer while recording also internally stops the recording but the Qt UI itself still thinks that the recording is still ongoing, it doesn't properly update the recording state.

Right, because there's no callback from the GS side to the UI. Could add one I guess.

The other option is automatically starting a new file.
