### ISSUE TITLE
[Feature Request]: add texture injection support for 2d prerendered backgrounds like oni2, not just for 3d

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#9177]
### Description

Allow texture injection for 2d prerendered backgrounds like oni2 has a ton of with my own upscale textures 

### Reason

Makes game look great using 4k prerendered textures vs native, and not just 4k upscaled textures for 3d

![pcsx2-qtx64_2023-07-05_13-55-43](https://github.com/PCSX2/pcsx2/assets/60486562/7ea3ced8-c83b-4dbd-b13b-be3ad5010e96)

Example from 3d walls but pretty much what could be done too 2d if implemented support

**Comment by washingleavesandthensome23-434** [comment]
https://github.com/PCSX2/pcsx2/issues/7563

**Comment by stenzek** [comment]
Nope. Game uploads one pixel row at a time, moves it around a bunch. Not possible.

**Comment by washingleavesandthensome23-434** [comment]
Shame 😕
