### ISSUE TITLE
[BUG]: Kingdom Hearts 2 Final Mix

### ISSUE THREAD

**Issue by SilencerOn** [PCSX2/pcsx2#9182]
### Describe the Bug

After beating the final boss in the game and watching through the entire game end credits. Specifically after the part where the Sora opens Mickey's letter. The screen turns black and stays black. Supposedly we should see a save screen to save the completion of the game. That's rather odd and I found this problem common for many people.

### Reproduction Steps

Finish the game and watch the end game credits

### Expected Behavior

As the screen turns black after the credits, it stays black

### PCSX2 Revision

v1.7.4688

### Operating System

Windows 10 (64bit)

### CPU

11th Gen Intel(R) Core(TM) i5-1135G7

### GPU

Intel Iris Xe Graphics

### Emulation Settings

I had default settings

**Comment by Mrlinkwii** [comment]
can i have a gs dump ?

**Comment by stenzek** [comment]
Verify your game dump.

We also can't investigate this without a save file.

**Comment by stenzek** [comment]
Closing due to lack of response. If you provide the required details/saves, we can reopen.
