### ISSUE TITLE
[Feature Request]: Increment selected save slot when saving

### ISSUE THREAD

**Issue by Gadetron** [PCSX2/pcsx2#9193]
### Description

An option to have save states cycle automatically to a new slot whenever you make a save state. (ie, you in save slot 1, you make a new save and it puts the save in 2 and moves you to slot 2 and keeps going until you hit 10 and it goes back to 1)

### Reason

would be very useful in preventing accidental overwrites and keep a good history of points to roll back to for various reasons, having 10 linear back up save slot points

### Examples

dont have any to show at this time.

**Comment by stenzek** [comment]
Just realized, you could probably already achieve this by binding the same key to both save and select next slot.
