### ISSUE TITLE
[BUG]: IOP debugger reading register as unsigned erroneously

### ISSUE THREAD

**Issue by EdnessP** [PCSX2/pcsx2#9197]
### Describe the Bug

To preface this, I haven't had time to extensively test it - it's possible this affects the EE debugger too, or maybe other instructions, but for me personally I've noticed this recurring issue while on the IOP side of the debugger, and always with the BGEZ/BLTZ instruction.  The emulation itself is fine, it's just the debugger seemingly visually interpreting a signed negative value as an unsigned value, and setting the step breakpoint at the wrong place.  BGTZ/BLEZ might also be affected.

I've first spotted it on an older build of v1.7.3550, and it still happens in the current latest nightly v1.7.4701.

### Reproduction Steps

In my case, the PAL version of Bully (Canis Canem Edit) SLES-53561, and setting an R3000 breakpoint at the SCREAM.IRX instruction `bgez $v0,0x000DDCE4` at address 0x000DDCC8 which should be hit whenever the game is playing back a sound effect (e.g. pressing Up/Down on the pause menu, but chances are you'll hit it very shortly after just loading up the game), and seeing if the value in $v0 is negative (which it usually should be) but erroneously evaluating to true.

Similarly, the LIBSD.IRX instruction `bltz $v0,0x0005AF90` at address 0x0005AF78 (which should be called and reached right after reaching the aforementioned SCREAM.IRX instruction) and again seeing if the value in $v0 is is negative (which it also again should be) but here erroneously evaluating to false.

Stepping forward will set the breakpoint where it thinks it should be from the incorrect evaluation, but the emulator will never actually reach that location and resume, continuing as intended until the next time it comes back around to those instructions and stop.
![attels](https://github.com/PCSX2/pcsx2/assets/55930127/2a3216cb-eb9d-42a3-961b-5d736877fff4)

### Expected Behavior

It should evaluate the values in the registers correctly, and set the next step breakpoint at the correct location, instead of where it would be if it evaluated to the opposite boolean.

### PCSX2 Revision

v1.7.4701

### Operating System

Windows 10 (64bit)

**Comment by Ziemas** [comment]
https://github.com/PCSX2/pcsx2/blob/ebb291e06dd84aea9dad3b0f8f700d0ec9c3b045/pcsx2/DebugTools/MIPSAnalyst.cpp#L371-L382
This looks pretty suspect, either this needs to account for register size or we need to sign extend in the R3000 `getRegister` implementation.

**Comment by Ziemas** [comment]
Can you see if #9199 fixes it?

**Comment by EdnessP** [comment]
Yep, those two previously mentioned cases are now evaluated correctly, thank you!
![attels](https://github.com/PCSX2/pcsx2/assets/55930127/6630084b-f161-4f23-85e2-263817c53fcc)
