### ISSUE TITLE
Possible typo in microVU_Flags

### ISSUE THREAD

**Issue by lioncash** [PCSX2/pcsx2#92]
I came across this [here](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/microVU_Flags.inl#L190)

I find the `||1` to be a little odd. Is it possible that this is a leftover from a hack or something?

**Comment by ssakash** [comment]
Seems like a hack to me on force disabling the flaginfo regardless of Mac flag status on the next block. What do you think ? @refractionpcsx2

**Comment by refractionpcsx2** [comment]
There has already been discussion on this, u though it had already been dealt  with in the code
