### ISSUE TITLE
[BUG]: Syphon Filter: The Omega Strain | WS Patches and auto game fixes not working properly

### ISSUE THREAD

**Issue by AgentLogan1** [PCSX2/pcsx2#9201]
### Describe the Bug

Upon entering the "NetGUI" menu, cheats, ws patches, and automatic game fixes all get disabled, and after exiting the NetGUI they don't work again unless the game is rebooted.
The issue happens in all versions of the game.
This wasn't happening before and it started in PCSX2 v1.7.4587 #8975

![image](https://github.com/PCSX2/pcsx2/assets/128261540/7fc7e00f-3024-4e6b-8fff-fb80806c96f3)
![image](https://github.com/PCSX2/pcsx2/assets/128261540/c70c2627-aef0-4836-b60f-e6a18f462ce7)

### Reproduction Steps

boot the game and go to play online and enter the NetGUI, you'll see an OSD message above saying the patches are disabled (shown in the screenshots above), exit the gui and play any level and now ws patches and cheats and auto fixes don't work.

### Expected Behavior

patches, cheats, and fixes should remain active after entering and existing the NetGUI just like they did in v1.7.4586 and before

### PCSX2 Revision

v1.7.4704

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 5600

### GPU

AMD Radeon RX 6700

**Comment by stenzek** [comment]
> patches, cheats, and fixes should remain active after entering and existing the NetGUI just like they did in v1.7.4586 and before

Gosh no. This was completely broken - the patch was applying when a different executable was running, stomping on memory and causing crashes. Just because it didn't break your game doesn't mean it didn't break tons of others.

Anyway, the issue here isn't with PCSX2, it's the stupid game. Every time you launch/exit the netui, it appends an extra `;1` the ELF path. `elf_path = "cdrom0:\\SCUS_972.64;1;1;1"`, `elf_path = "cdrom0:\\SCUS_972.64;1;1;1;1"` and so on.

Not really a fan of hacking around it, but the bios is able to locate the file :/

**Comment by YukiXXL** [comment]
Maybe make a function which checks if there are more than one ";1" and load it as it only has one ";1" or make an option to enable the old method of having cheats constantly enabled under Advanced Settings.

**Comment by refractionpcsx2** [comment]
old cheats just enable, there's no way you can make a UI for them. so as long as you enable cheats, the old ones will enable.

**Comment by stenzek** [comment]
> Maybe make a function which checks if there are more than one ";1" and load it as it only has one ";1" 

If you read the PR which closed the issue, I rewrote the ISO parser and stripped the suffixes completely.

> make an option to enable the old method of having cheats constantly enabled under Advanced Settings.

No. As I said above, this would corrupt data/code.
