### ISSUE TITLE
[BUG]: Syphon Filter: The Omega Strain | Lights Artifacts

### ISSUE THREAD

**Issue by AgentLogan1** [PCSX2/pcsx2#9206]
### Describe the Bug

As shown in the screenshots below, the issues are 2 fold, to make things easier i'll label them as "Lights issue 1" & "Lights issue 2"

-in PCSX2 v1.7.4244 none of these 2 issues existed
-in PCSX2 v1.7.4245 both issues appeared because of #8289
-in PCSX2 v1.7.4510 this #8845 states that the lights were fixed, but testing shows both Lights 1 & 2 still occur in v1.7.4510
-in PCSX2 v1.7.4608 is when it actually got fixed by #9003  (only lights 1 got fixed)

So the purpose of this report is about Lights issue 2 as shown below, this one still occurs up to the latest version v1.7.4708
i'll provide save states for the location of Lights issue 2 (you have to move around to trigger the lights artifacts)

Note: Lights 1 happens in a different location in the level

![Lights 1](https://github.com/PCSX2/pcsx2/assets/128261540/3c9ce265-9731-4154-8ca7-0813b2ab7297)
![Lights 2](https://github.com/PCSX2/pcsx2/assets/128261540/a1f105d7-7ed7-4bf0-bc4e-9df665d5e5b9)

### Reproduction Steps

Load up the provided save state and move around the lights
[UCUS98641_1.01_0.zip](https://github.com/PCSX2/pcsx2/files/11995335/UCUS98641_1.01_0.zip)

### Expected Behavior

Lights should not produce these artifacts as tested on PS2, Software renderer, and v1.7.4244 and before

### PCSX2 Revision

v1.7.4708

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 5600

### GPU

AMD Radeon RX 6700

**Comment by Mrlinkwii** [comment]
can i have a gs dump?

**Comment by AgentLogan1** [comment]
> can i have a gs dump?

Sure
[GS Dump.zip](https://github.com/PCSX2/pcsx2/files/11996076/GS.Dump.zip)

**Comment by AgentLogan1** [comment]
I think this might be relevant, i used levitation cheats and came to this area from above, the enemies didn't spawn and neither did the train cart, there is a train cart here with a big light coming from it and when the train along is not spawned then the artifact issue happens very little almost absent, here is some screenshots to elaborate and a save state with no train light
![image](https://github.com/PCSX2/pcsx2/assets/128261540/06d4dd61-631a-4a94-9e16-e6292ac9cd3e)
[UCUS98641_1.01_0.zip](https://github.com/PCSX2/pcsx2/files/11996507/UCUS98641_1.01_0.zip)
![image](https://github.com/PCSX2/pcsx2/assets/128261540/49c66a81-994c-4058-8bc8-44ab13ba80c0)

**Comment by AgentLogan1** [comment]
> may i ask how is this on latest nightly
![Untitled0](https://github.com/PCSX2/pcsx2/assets/128261540/864d1908-79b7-4e12-a274-7e796ee835d2)
![Untitled1](https://github.com/PCSX2/pcsx2/assets/128261540/ce7ab845-f197-4d5b-b089-ccadb2a46aae)

**Comment by AgentLogan1** [comment]
This is has been fixed by #10470 the issue stopped happening at PCSX2 v1.7.5357

**Comment by Mrlinkwii** [comment]
thanks for the update :)
