### ISSUE TITLE
[BUG]: No longer building in linux

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#9210]
### Describe the Bug

PCSX2 no longer builds in linux.  ECM seems to be the reason as stated in the build log; however `libecm-dev` is installed. 

Build log excerpt:
```
CMake Error at cmake/SearchForStuff.cmake:85 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake
```
Also CMakeError.log indicates:
`CheckFunctionExists.c:(.text+0x14): undefined reference to pcap_get_pfring_id'
`

Last good build was made from commit: 35387eeabb6a1bdca8b80652678b1db350ceb9ba so this issue is recent.  The only ECM-related PR I could find was #9168 however not sure if that's the cause.  I can bisect if needed.

### Reproduction Steps

Attempt to build pcsx2 in linux.

### Expected Behavior

Emulator builds.

### PCSX2 Revision

Commit: 81ae1ce3625aab6207ecf4fd7dc3cbb8095d9bc8

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.1

### Logs & Dumps

[build.log](https://github.com/PCSX2/pcsx2/files/11995642/build.log)
[CMakeError.log](https://github.com/PCSX2/pcsx2/files/11995643/CMakeError.log)
[CMakeOutput.log](https://github.com/PCSX2/pcsx2/files/11995644/CMakeOutput.log)

**Comment by Mrlinkwii** [comment]
Just to rule something out , dose the appimage work for you?

**Comment by Shoegzer** [comment]
Yes it does, just checked latest.

**Comment by stenzek** [comment]
Please read the log. It literally says that ECM is missing - it's needed to build PCSX2 now.

https://www.google.com/search?q=cmake+ecm

**Comment by Shoegzer** [comment]
Look in my post above though - ecm *is* installed.  Specifically `libecm-dev`, `libecm1`, `libecm1-dev` and `libecm1-dev-common` are all installed but it still will not build on linux (Ubuntu/Linux Mint at least).

**Comment by stenzek** [comment]
It builds fine on Ubuntu. That's what our CI runners use.

It's user error. You haven't installed the correct package.

**Comment by Shoegzer** [comment]
Okay, what is the correct package then?  All ecm-related packages are installed here.  Also **gmp-ecm** was installed, this and those posted above cover all the ecm-related packages in the Ubuntu base as I'm aware.

**Comment by stenzek** [comment]
I've never used Mint, so I have no idea. That's why I posted a Google link.

The packages we use for Ubuntu are listed in <https://github.com/PCSX2/pcsx2/blob/master/.github/workflows/scripts/linux/install-packages-qt.sh>

**Comment by Shoegzer** [comment]
Ah, I see now.  The required package is `extra-cmake-modules` which I guess makes sense, it's just misleading that the  Ubuntu repo also has packages prefixed with literally "libecm" which aren't required here.
