### ISSUE TITLE
[BUG]: Crashing in PaRappa the Rapper 2 (Regression)

### ISSUE THREAD

**Issue by cuckydev** [PCSX2/pcsx2#9212]
### Describe the Bug

PaRappa the Rapper 2 now crashes shortly after the splash screens. The crash locks the entire emulator up and requires the task to be killed via external means.

### Reproduction Steps

Boot up PaRappa the Rapper 2 (SCUS-97167 and SCPS-15017 tested), and the emulator will crash within a few seconds.

### PCSX2 Revision

v1.7.4710

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

RTX 2060

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/11995867/emulog.txt)

**Comment by refractionpcsx2** [comment]
Yep thanks, there was some code missing from when I did the Instant DMA changes, it was getting caught up with the new DMA changes I added today.

#9214 will fix it when I merge it soon (releases are slow at the moment, though, sorry)
