### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by CarrionB** [PCSX2/pcsx2#9213]
### Describe the Bug

Update is not being apllied

### Reproduction Steps

- Open emulator
- Updater shows up
- Download ans install update
- this happens:

![image](https://github.com/PCSX2/pcsx2/assets/10525559/f61e02a4-931f-4bc8-a03f-df45c1556e05)

I think there is a mistake defining the route, the slashes are shown as backslashes

### Expected Behavior

To complete the installation

### PCSX2 Revision

v1.7.4897

### Operating System

Windows 10 (64bit)

**Comment by kamfretoz** [comment]
Delete the .txt file mentioned on the error log, and redo the update process.

**Comment by refractionpcsx2** [comment]
Download a fresh copy from the website and overwrite your copy, we had a problem with SDL which is now fixed.
