### ISSUE TITLE
[BUG]: (OpenGL / Vulkan) Missing pixelation effect in PaRappa the Rapper 2

### ISSUE THREAD

**Issue by cuckydev** [PCSX2/pcsx2#9216]
### Describe the Bug

On Stage 6, there is intended to be a pixelation effect if you are failing during COOL status. This effect is missing on the OpenGL and Vulkan hardware renderers. It is present on D3D11, D3D12, and software renderers.

Software:
https://github.com/PCSX2/pcsx2/assets/44537737/16f8aaa2-70fd-4179-bedf-b20579a9f091

Vulkan:
https://github.com/PCSX2/pcsx2/assets/44537737/dd9cca0d-2d59-4cd3-93d1-36079e954e2b

Hardware video:
https://youtu.be/nqMo3x5M2Hs?t=120

GS Dump:
[PaRappa the Rapper 2_SCPS-15017_20230709164242.gs.zip](https://github.com/PCSX2/pcsx2/files/11996063/PaRappa.the.Rapper.2_SCPS-15017_20230709164242.gs.zip)

### Reproduction Steps

- Reach COOL status on Stage 6
- Fail a line, causing you to drop half-way to GOOD status
- On the affected renderers, a pixelation effect will not appear

### Expected Behavior

When you fail a line in Stage 6 on COOL status, a pixelation / mosaic effect should appear.

### PCSX2 Revision

v1.7.4710

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 5900X

### GPU

RTX 2060

**Comment by stenzek** [comment]
Linked issue should sort it out, I've only tested with the dump, but I'd guess the "effect" is just changing which bits get dropped, in which case it should be fine for the whole thing.

**Comment by cuckydev** [comment]
> Side issue for this game, it's moving this data from 0x1180 to 0x3DED:
> 
> ![image](https://user-images.githubusercontent.com/11288319/252316874-e79b3096-1b7c-4c53-af5e-68e09a6b0596.png)
> 
> With a Y offset of 16, which means it's getting downloaded from the GPU. Plus the fact that it's not page aligned means that it'd be too risky to do this move on-GPU.. so it'll be slower than ideal, but moves tend to be one the touchier things, so I'm not going to gamble on that.
> 
> Doing the sprite draws on the CPU is another option, but it doesn't match the current heuristics for triggering.

Do you know if this has anything to do with https://github.com/PCSX2/pcsx2/issues/8390 ?

**Comment by refractionpcsx2** [comment]
could be related, somehow disabling depth seems to fix it, but obviously a real fix would be nice :P

**Comment by stenzek** [comment]
I can take a look tomorrow.
