### ISSUE TITLE
[BUG]: Michigan - Report from Hell (SLES-53073) - Playability Issue

### ISSUE THREAD

**Issue by TwosomesUP** [PCSX2/pcsx2#9223]
### Describe the Bug

During the intro scene after starting a new game you're given a task to focus the camera on a group of boxes. In the latest nightly build this event does not seem to trigger properly. Instead of your reticle changing to an orange circle, indicating you can focus on the objects, nothing happens. Because of this, you are unable to progress past this point in the game.

According to the Michigan - Report from Hell Wiki, the last fully playable revision was 3191. Which I was able to test, and was able to progress normally using that build.

Also, this bug does not appear when playing the Japanese version of the game.

### Reproduction Steps

1. Start a new game
2. Interact with Brisco until you're prompted to focus on the boxes next to the starting point

### Expected Behavior

You are expected to be able to interact with these boxes so you can progress the game. When the boxes are interactable and highlighted, your reticle will transform into an orange dot.

### PCSX2 Revision

1.7.4718

### Operating System

Windows 11

### CPU

i9-9900KF

### GPU

RTX 3070 Ti

### GS Settings

All graphics settings are default except for Bilinear Filtering under Display Settings, which is set to None.

### Emulation Settings

All emulation settings are set to default. Attempted to update EE Cycle Rate to 75%, as suggested on the game's wiki to solve other problems, but this did not help.

### GS Window Screenshots

Behavior using revision 4718:
![Michigan-Revision4718 mkv_snapshot_00 59_ 2023 07 10_18 14 34](https://github.com/PCSX2/pcsx2/assets/137419624/f0afe979-eecf-49eb-aba6-018fc8bd9a2c)

Behavior using revision 3191:
![Michigan-Revision3191 mp4_snapshot_01 00_ 2023 07 10_18 15 20](https://github.com/PCSX2/pcsx2/assets/137419624/2ff8784c-7ab9-4a53-b15a-f52ce9af6082)

### Logs & Dumps

[Michigan-Dumps4718.zip](https://github.com/PCSX2/pcsx2/files/12009327/Michigan-Dumps4718.zip)

**Comment by refractionpcsx2** [comment]
It was broken by the patch added from #8715 in release 1.7.4406

I can try to take a look tomorrow, unless @Goatman13 wants to take a look and see if he can modify his patch.

**Comment by TwosomesUP** [comment]
Fantastic! I'll try disabling the compatibility patches. If there's anything else I can help with, let me know.

**Comment by Goatman13** [comment]
> I can try to take a look tomorrow, unless @Goatman13 wants to take a look and see if he can modify his patch.

I tried to figure out why it breaks, but i don't know. Maybe i'm overlooking something simple, but replaced code looks fine to me.

**Comment by refractionpcsx2** [comment]
The code in the patch looks fine, but I'm wondering if in some cases they are expecting an early value from that VF30 (as they have somewhat timed it) but in the library example they didn't, or they *did* time it and it was very cunning code.

**Comment by Goatman13** [comment]
Probably it is timed then. But it worked fine in older pcsx2 where VU0 was ahead at the start. For both, library floor, and this part of game. Sure, there is a chance that it was still doing more cycles than old kickstart (6500), but it is weird it worked fine. Not sure how to resolve this, if it is timing then removing patch and recommending people to change cyclerate could be only available solution.

**Comment by refractionpcsx2** [comment]
well we can set the cycle rate in the gamedb now, so we could add the lower cycle rate for this game, as long as the rest works fine with it.  But if it used to work with version 1.6, then I dunno why the new code wouldn't work, it doesn't make a great deal of sense :/

**Comment by TwosomesUP** [comment]
I appreciate the both of you looking into this! If I was more familiar with the code line and the inner workings of the PS2, I'd attempt to help.

Just to satisfy my own curiosity, how does reducing the cycle rate help resolve this issue? Mostly just looking for clarification on the technical side. Is it that the timings aren't always in sync on the CPU/GPU and it gives the game's logic time to catch up or execute?

**Comment by refractionpcsx2** [comment]
reducing the cycle rate allows VU0 to run faster than the EE Core (get more work done in the same time) so it runs plenty ahead of it and that's enough for it to work.

It's a hack and not ideal, but it seems to work.
