### ISSUE TITLE
[BUG]: Tekken Tag Tournament SLUS-20001 Intro Video Regression

### ISSUE THREAD

**Issue by LodanZark** [PCSX2/pcsx2#9225]
### Describe the Bug

Tekken Tag Tournament (SLUS-20001) Intro video it's presented with flickering, which didn't happen in a pcsx2 build from last week, so I assume it's a regression.

### Reproduction Steps

Simply booting the game, the intro video will start up right away.

### Expected Behavior

Playing the intro video without flickering.

### PCSX2 Revision

1.7.4721

### Operating System

Windows 11

### CPU

AMD Ryzen 7 2700x

### GPU

nVidia GeForce GTX 1050 Ti

### GS Settings

Enabled Widescreen Patches
Enabled V-Sync
Enabled No-Interlancing Patches

**Comment by refractionpcsx2** [comment]
Looks like a bad interaction with recent changes and the no-interlacing patch.  Disable the patch and it'll work fine.  I'll look in to it at some point.

**Comment by Mrlinkwii** [comment]
i cant recreate  the issue as of 1.7.5569 with Enabled Widescreen Patches
& Enabled No-Interlancing Patches

**Comment by Mrlinkwii** [comment]
@LodanZark  can you re-check this for me :)

**Comment by F0bes** [comment]
Issue has gone stale. If anyone can reproduce the issue still please mention it here.
