### ISSUE TITLE
[BUG]: Downsampling TV Shaders (4xRGSS, NxAGSS) don't work

### ISSUE THREAD

**Issue by AkitoFire** [PCSX2/pcsx2#9226]
### Describe the Bug

The TV Shaders 4xRGSS (4x Rotated Grid SuperSampling) and NxAGSS (Nx Automatic Grid SuperSampling) that should be downsampling the image don't actually work and don't do anything. 

### Reproduction Steps

1. Go to the Graphics tab
2. Set Renderer to Vulkan
3. Under Rendering, set 'Internal Resolution' to 4x
4. Under Post-Processing, set TV Shader to '4xRGSS downsampling (4x Rotated Grid SuperSampling)'

### Expected Behavior

The 4xRGSS TV Shader should downsample the 4x Internal Resolution back to 1x / Native PS2 resolution.

### PCSX2 Revision

1.7.4721

### Operating System

Windows 10 (64bit)

### CPU

i7-6700k

### GPU

GTX 1070

**Comment by refractionpcsx2** [comment]
It is working, but it doesn't work at lower upscales, the idea is to reduce aliasing at high upscaling resolutions when reduced down to the size of a normie monitor, so at 3x you're not going to notice much of anything at all, put it to x8, then you might notice something. I'm not sure what you were expecting, what would be the point in having a shader to downscale it back to native resolution? that seems a little silly...

For more information on how it works, please look at #7647

Here's an example, look at the bars at the back on the windows:

Normal x8:
![image](https://github.com/PCSX2/pcsx2/assets/6278726/b5002e8a-f262-4257-996d-a8914c76d98b)

RGSS:
![image](https://github.com/PCSX2/pcsx2/assets/6278726/d5446576-5e4f-469a-bd20-3dea1c4b117b)

**Comment by refractionpcsx2** [comment]
The point in the shader is to reduce aliasing when you're trying to generate an image higher than your native monitor resolution, it's not a cool downscaler to render at a high resolution and crapify it, nor is it an upscaling solution to make crap images look better, it's designed to reduce aliasing when you're trying to cram a high resolution image in to a lower resolution, and it does this swimmingly.

It wasn't condescending, I just think you've misunderstood the purpose of these shaders.

**Comment by AkitoFire** [comment]
I mean, isn't a 4x SSAA shader designed to downscale the resolution 4x? I understand now how the shader is supposed to work (setting the internal resolution to 8x, then downsampling to the monitor resolution) but then the shader is incorrectly labeled. A 4x SSAA shader should _always_ downscale four times, for example, 4k to 1080p. It shouldn't matter what your monitor resolution is set to, as a 4x SSAA technique is always dependent on the render resolution. The other option, however, NxAGSS, could work as you described and be dependent on the monitor resolution. 

Dolphin has a downsampling feature where you could choose the native 1x resolution combined with 4x SSAA if you wanted to:
![image](https://github.com/PCSX2/pcsx2/assets/14359199/65ebf173-c977-45e0-a59e-fedeecbe94f3)

Duckstation as well:
![image](https://github.com/PCSX2/pcsx2/assets/14359199/85a0a4f5-2c87-412a-80d5-06f6f9dbb462)


And it works wonders for sprite-based games that blend 2D and 3D art. Just setting the resolution to 4x or 8x would result in jarring-looking visuals with crisp 3D graphics and blocky 2D ones. Those games were designed to be played on a CRT after all, where the mixture of 2D and 3D looked great. 

With downsampling, you get an image where the sprite art is displayed at native res, and the 3D graphics are downsampled via 4x SSAA as well. So you basically get 'enhanced authenticity'. That's what I want, and 4xRGSS should allow that to happen.

**Comment by refractionpcsx2** [comment]
No.  the 4x means it takes 4 samples from around that point for the averaging, not to a x4 resolution.

I don't, know how Dolphin does it, but traditionally SSAA would render the image at a higher resolution (4x higher, for example) then anti alias the reduced the image.  We don't do the higher resolution step, we take whatever resolution we are currently rendering at, and the anti aliasing is done when the image is shrunk down to the window/screen size.  If you are at or below your monitors resolution, there will be little to no effect from the shader because there is no downscaling/downsampling, so it will appear to do nothing.

**Comment by KrossX** [comment]
The anti-aliasing methods you're describing are the usual features of API/Hardware that uses multisampled surfaces that get resolved into an anti-aliased image. There's currently no support for those methods.

This post processing shader is just doing the 4 samples fetches for each resulting pixel, thus supersampling. Note there's no AA in the name. This shader would be the same as a simple resolve method from the hardware AA feature. The main difference here is that internal resolution is not automatically increased to be resolved but instead, you have to manually set an internal resolution high enough for supersampling to be of use when rendering to the final size. An internal resolution smaller than twice the display resolution would just result in supersampling sampling the same source data, after all, bilinear is already blending two pixels of the source data.

When proper MSAA/SSAA is implemented this filter would be obsolete. For now, it's an interesting option for those who hate jaggies and have the gpu power to spare.

**Comment by AkitoFire** [comment]
> The anti-aliasing methods you're describing are the usual features of API/Hardware that uses multisampled surfaces that get resolved into an anti-aliased image. There's currently no support for those methods.

I mean that's true for MSAA, but SSAA completely operates on the pixel level and just needs a high enough render resolution to work. I thought this 4xRGSS shader was the PCSX2 implementation of SSAA, as you would just need to set the internal resolution high enough, add this shader and it would automatically downsample the image back to 1/4th of the resolution.

> An internal resolution smaller than twice the display resolution would just result in supersampling sampling the same source data, after all, bilinear is already blending two pixels of the source data.

I understand what you mean, but I thought this 4xRGSS filter took the high-res input image and downscaled it to 1/4th of the resolution. Regardless of whether or not the output ends up below the display resolution. I wanted to get a clean downsampled image at native 1x resolution to work together with a CRT shader, for mixed 2D and 3D games.

**Comment by KrossX** [comment]
I think DuckStation has a downsampling filter to native like you mention. Yes, this shader won't give you that result unless you play at 1x sized window or display resolution. The downsampling is done simply from internal resolution to window/display size.

Some CRTs do support low resolution like 320x200 but remember that PS2 games resolutions can vary even during gameplay.
