### ISSUE TITLE
Driv3r Flicker GSDX HW OGL, GSDump even weirder.

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#923]
Ok this is strange.

Note: I have tried the blending accuracy, depth settings and hw hacks, none make a difference from what I can tell.

In recent GSDX enhancements Driv3r has gotten much much better, however there is still some weird flickering textures over seemingly random areas, almost like lighting bugs.  The bug seems to go away for about a second or so if you switch renderer and back to HW OGL, then the flickering in random areas of the screen starts again.

What is strange, if you see the attached dump, this was taken ingame, i tried twice to make sure, however most of it displays the "Do you want to create a memory card save" screen with a single frame of the ingame graphics.

Hopefully this is some help to you @gregory38  :P

GS Dump: http://www.filedropper.com/driv3r-flicker

**Comment by gregory38** [comment]
The game uses a ton of effect. Was a GSdx version than that 

![screenshot - 10242015 - 10 35 03 pm](https://cloud.githubusercontent.com/assets/1569559/10712623/82e849cc-7a9f-11e5-9f5d-5c1e4c64c0f2.png)

**Comment by gregory38** [comment]
Oh level 3 of accuracy is a bit better.

**Comment by refractionpcsx2** [comment]
Doesn't look that bad when you're actually playing it :/

**Comment by gregory38** [comment]
Honestly, it would be very hard to fix it and I suspect the game is slow (VS the SW). I'm around 10K complex draw for a frame.
Anyway, the game uses very strange texture. Yes it is after palette conversion. I let's you imagine the filtering stuff.

![example](https://cloud.githubusercontent.com/assets/1569559/10712994/62205df8-7aac-11e5-8ea8-ac5fca0ae590.png)

Later the game will read back the RT as a 8 bits texture and reapply a new CLUT.

Anwyway, I think the first issue is related to PR #806 
Game reads depth as a 16 bits colors and my code wrongly implement it. I try to quickly fix it on the PR but it breaks others stuff. So I need to redo it.

**Comment by refractionpcsx2** [comment]
Cool, well I'm glad it's not too confusing of an issue anyway :) But you'll make a certain @JMC47 very happy if you manage to fix this game up :P

**Comment by JMC47** [comment]
The weird thing is when I was using OpenGL the other day, there weren't really any graphical glitches like displayed above in OpenGL hardware renderer.  I didn't play super long, but in the area shown above, it looks just fine.  My main issue with the game is performance, which honestly doesn't matter in terms of accuracy/everything working.

**Comment by gregory38** [comment]
Image is less horrible with (less) blending accuracy. However for the speed it would be hard to do better. There are tons of texture conversions and too much effects. 10K complex draw calls is just too much (probably close of 15-20K gl draw calls)

Potential improvements are
1/ Allow to sample-convert the texture in-place. For example the depth buffer is converted to a texture color with a dedicated shader. And then we use it to do the GS rendering. The idea is to fuse those 2 steps.
2/ Bypass some texture conversions to emulate the post-processing effect directly.

**Comment by refractionpcsx2** [comment]
The image is pretty much okay when you're actually playing it, you just get some very distracting black blocks flashing on the screen from what I can tell.

**Comment by FlatOutPS2** [comment]
This issue has recently been solved for software mode thanks to https://github.com/PCSX2/pcsx2/commit/a123e6518521f3d59c628678c11031a4d2d8358c

Still garbage textures on the cars in HW modes though.

**Comment by gregory38** [comment]
@FlatOutPS2 was it fixed or did you post the message in the wrong issue ?

**Comment by FlatOutPS2** [comment]
Wrong issue. I had both issues open at the same time and must somehow have switched tabs without noticing.

This is a hardware mode only issue.

**Comment by FlatOutPS2** [comment]
Although as I posted in my report on the forum(http://forums.pcsx2.net/Thread-DRIV3R-SLES-50876-E), using OpenGL with hardware depth and CRC hack level set to Partial most of the flickering and shadow issues are gone.

**Comment by refractionpcsx2** [comment]
Game looks fine now, although the cars have rainbow textures on them.
OGL is quite slow for me, about 30-50FPS, DX is locked at 60FPS

**Comment by tadanokojin** [comment]
If everything else besides the texturing is sorted I'm closing in favor of #451
