### ISSUE TITLE
[BUG]: Debugger - Run to cursor when paused causes infinite loop

### ISSUE THREAD

**Issue by refractionpcsx2** [PCSX2/pcsx2#9230]
### Describe the Bug

If you pause the emulation and go in to the debugger (I think this happens with pause in the debugger too), then right click somewhere in the assembly view, and choose "Run to cursor", the emulator will hang, since it is paused and never actually executes.

### Reproduction Steps

Pause emulator while running a game
Go to debugger
Right click on an instruction in the assembly after the currently running instruction
Choose "Run to cursor"
Feel sad that it hung

### Expected Behavior

Not hang, probably just not do anything.

### PCSX2 Revision

v1.7.4724

### Operating System

Windows 10 (64bit)

### Logs & Dumps

loadelf: fname cdrom0:¥SLES_543.70;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_543.70;1
0 00100000 00358f9c ..............
[    5.2626] (VMManager) Pausing...
[    5.2632] (Cubeb): G:\ps2\gitrepo\pcsx2\3rdparty\cubeb\src\cubeb_wasapi.cpp:1760:000002461A0E27D0: Stop and join render thread: 0000000000000C78 (0), phase=0
[    5.2637] (Cubeb): G:\ps2\gitrepo\pcsx2\3rdparty\cubeb\src\cubeb_wasapi.cpp:1794:stop_and_join_render_thread: Closing thread.
[   18.6494] (VMManager) Resuming...
[   18.6499] QMetaObject::invokeMethod: Dead lock detected
EE/iR5900-32 Recompiler Reset

**Comment by F0bes** [comment]
Uh oh
