### ISSUE TITLE
[Feature Request]: Map analog sticks to D-Pad in unsupported games

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#9231]
### Describe the Bug

If an analog input source and a button/key input source are mapped to a single input, the mapped button/key input source does not respond the bound input.

### Reproduction Steps

- Make sure your PC is not running any of third-party keybind tools.
1. Run PCSX2
2. Open Controller setting
3. Go to Controller Port 1 tab
4. Shift + Click an input
5. Click "Add Binding" and move an analog
6. Click "Add Binding" and press a button/key
7. Boot a game with "Show Inputs" (OSD)
8. Press mapped button/key (6.) to see how it works

Example: (`SDL-0/LeftShoulder` does not respond `Pad1 Up`)
![image](https://github.com/PCSX2/pcsx2/assets/91955473/7ba7007c-b434-44c8-b3e4-2757e68e67eb)
(Deadzone is set to 50% in this image, but it doesn' matter. This issue occurs regardless deadzone.)

### Expected Behavior

Mapped button should respond regardless if analog is mapped for same input.

### PCSX2 Revision

v1.7.4724

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Not really sure what you expect to happen here.

The analog values are constantly fluctuating, which fires any connected events. All buttons are pressure sensitive from the input system's perspective, so whatever value comes in last "wins". So if you press a button, the analog will soon override it - this is working as intended.

**Comment by stenzek** [comment]
Yes.

**Comment by Berylskid** [comment]
Self-resolved it by binding analogs with using Macros instead of with general bindings.
