### ISSUE TITLE
[BUG]: Hitman 2 Silent Assassin - texture error

### ISSUE THREAD

**Issue by MBeeBR** [PCSX2/pcsx2#9234]
### Describe the Bug

The texture of the game is completely destroyed when using the memory card.

https://github.com/PCSX2/pcsx2/assets/136722551/e618b3b1-34c5-4d84-a8d3-53996289626d

### Reproduction Steps

just press start, save the game and load the saved game, the texture will be corrupted.

![unknown_2023 07 11-21 53](https://github.com/PCSX2/pcsx2/assets/136722551/13560e1c-f634-4b0f-8b18-c1b735fa6ed8)

### PCSX2 Revision

1.7.4724

### Operating System

Windows 10 (64bit)

### CPU

E5-2640 v3

### GPU

RX-570 4GB

### GS Settings

no modifications or cheats

![unknown_2023 07 11-21 59_1](https://github.com/PCSX2/pcsx2/assets/136722551/33ac2381-04c7-4d5e-9a49-6915ecd0f96c)

### Emulation Settings

practically standard

![unknown_2023 07 11-21 58](https://github.com/PCSX2/pcsx2/assets/136722551/73f817e5-201e-4ea9-85bf-5d915335d8bc)

### Logs & Dumps

[Hitman 2 - Silent Assassin_SLUS-20374_20230711215704.gs.zip](https://github.com/PCSX2/pcsx2/files/12022632/Hitman.2.-.Silent.Assassin_SLUS-20374_20230711215704.gs.zip)

**Comment by MBeeBR** [comment]
one thing that might help, older versions of 1.7 don't have this bug 😉

**Comment by MBeeBR** [comment]
found out which version is breaking Hitman 2

1.7.4428 - Bad
![Hitman 2 - Silent Assassin_SLUS-20374_20230804155136](https://github.com/PCSX2/pcsx2/assets/136722551/05514cb4-d0a2-47c3-a8fb-172e1c12b1d0)
[Hitman 2 - Silent Assassin_SLUS-20374_20230804155136.zip](https://github.com/PCSX2/pcsx2/files/12263863/Hitman.2.-.Silent.Assassin_SLUS-20374_20230804155136.zip)

1.7.4427 - Good
![Hitman 2 - Silent Assassin_SLUS-20374_20230804155327](https://github.com/PCSX2/pcsx2/assets/136722551/c4d21ec3-8200-46c5-b6e8-978bc26c4804)
[Hitman 2 - Silent Assassin_SLUS-20374_20230804155327.zip](https://github.com/PCSX2/pcsx2/files/12263870/Hitman.2.-.Silent.Assassin_SLUS-20374_20230804155327.zip)

just load the saved game on the memory card that already starts with the bug
[Max-Card-1.zip](https://github.com/PCSX2/pcsx2/files/12263883/Max-Card-1.zip)

**Comment by lightningterror** [comment]
Seems that it's https://github.com/PCSX2/pcsx2/pull/8745

**Comment by MBeeBR** [comment]
The problem was partially solved, during the game I didn't see the texture error, but the start menu was completely black. I managed to enter the stage luckily.

![Hitman 2 - Silent Assassin_SLUS-20374_20230826133445](https://github.com/PCSX2/pcsx2/assets/136722551/8ed8b0d0-bf2c-4345-8044-cb7d7fc05954)

![unknown_2023 08 26-13 36](https://github.com/PCSX2/pcsx2/assets/136722551/aaff1c00-c459-46ba-9e47-5b9123bc6184)

GS [Hitman 2 - Silent Assassin_SLUS-20374_20230826133445.zip](https://github.com/PCSX2/pcsx2/files/12446102/Hitman.2.-.Silent.Assassin_SLUS-20374_20230826133445.zip)

**Comment by MBeeBR** [comment]
Despite the squares dividing the image, you can mark it as completed. It is already playable. 😀

![Hitman 2 - Silent Assassin_SLUS-20374_20230828112146](https://github.com/PCSX2/pcsx2/assets/136722551/d46f8ba3-b75a-4c68-b299-e3a7580e4a08)
![Hitman 2 - Silent Assassin_SLUS-20374_20230828112037](https://github.com/PCSX2/pcsx2/assets/136722551/852ee099-74b0-4a4d-a415-99861f097951)

**Comment by refractionpcsx2** [comment]
That's an upscaling problem, if it can be fixed with hacks then happy days.
