### ISSUE TITLE
[BUG]: Need for Speed: Underground 2 Carbon Fiber parts broken effect

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#9236]
### Describe the Bug

When you select any Carbon Fiber part it shows garbage on screen, possibly broken shine effect. Happens in both HW and SW modes and none of the rendering fixes solve it.

### Reproduction Steps

1. Go to Body Shop
2. Select Carbon Fiber
3. Garbage shows on screen

### Expected Behavior

It should look properly.

### PCSX2 Revision

1.74724

### Operating System

Windows 11

### CPU

i5-10700K

### GPU

GTX 3070

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/4414625/6eee2a08-b8e3-4ffb-b831-43c9b45c8f4e)

### Logs & Dumps

[UG2CarbonFiber.zip](https://github.com/PCSX2/pcsx2/files/12027175/UG2CarbonFiber.zip)

**Comment by refractionpcsx2** [comment]
Looks the same on my PS2

![Screenshot 2023-07-12 12-21-39](https://github.com/PCSX2/pcsx2/assets/6278726/4c2a5f48-8525-494e-9c31-e18e9629e486)

How should it look (at that angle?) Whatdo you consider wrong with it?

**Comment by Blackbird88** [comment]
Well damn, I could only find PC footage so I guess it's PS2 thing, my bad.
