### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Sennaton** [PCSX2/pcsx2#9237]
### Describe the Bug

I am unable to use the d-pad for either mapping the controller or playing the game

Important info:
Xbox Series S controller(Over USB)
Running Linux, changing kernel version or distribution seems to have no effect on this problem.

### Reproduction Steps

I don't have to do anything. The problem appears to be present as soon as I open the program, but I of course only notice when I go to remap my buttons or use the D-pad in the game.

### PCSX2 Revision

1.7.4724

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu, as well as another uncommon (Still debian-based) distro.

**Comment by Mrlinkwii** [comment]
did you map the controller?

**Comment by stenzek** [comment]
This is a support issue, not a bug. Please use the Discord server for support.

**Comment by Sennaton** [comment]
> 

Using the automap, yes. I cannot use the D-pad in any way during manual mapping.

**Comment by Sennaton** [comment]
> This is a support issue, not a bug. Please use the Discord server for support.

How so? I thought it was intended that controllers could, indeed, be mapped. I thought being unable to do so in the remapper would be a bug.

**Comment by refractionpcsx2** [comment]
This isn't a bug, this is a support issue because you've done something wrong (most likely) so please use our discord or forums to get help with your problem.
