### ISSUE TITLE
[BUG]: Cannot compile on Debian 12

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#9241]
### Describe the Bug

Get an error when trying to compile.

### Reproduction Steps

Try to compile on Debian

### Expected Behavior

No errors?

### PCSX2 Revision

Latest-git

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian 12: Bookworm

### Logs & Dumps

CMake Error at cmake/SearchForStuff.cmake:85 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)

**Comment by stenzek** [comment]
Please use google or github search next time: #9210.
