### ISSUE TITLE
[BUG]: Cheats disabled when launching another ELF

### ISSUE THREAD

**Issue by YukiXXL** [PCSX2/pcsx2#9243]
### Describe the Bug

Cheats get disabled when running another ELF.
I have Champions: Return to Arms Demo disc which has two ELFs. SLUS_291.26 runs first and CORE.ELF inside BG folder second.
In milisecond I can see that cheats loaded and then it shows that it couldn't find any compatibility or other patches/cheats message.

### Reproduction Steps

- Get any Demo disc game
- Enable cheats for the game on the demo disc
- Run the game

### Expected Behavior

Cheats working.

### PCSX2 Revision

Latest-git

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian 12

### CPU

AMD Ryzen 5 5600 6-Core Processor × 6

### GPU

Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]

### Emulation Settings

Cheats Enabled

**Comment by Mrlinkwii** [comment]
can i have an example of the cheat file  used?

**Comment by YukiXXL** [comment]
> 

I am launching the game normally. I checked the CRC from 1.6 and it uses the same one.

**Comment by YukiXXL** [comment]
> can i have an example of the cheat file used?

[7B564230.txt](https://github.com/PCSX2/pcsx2/files/12043949/7B564230.txt)

**Comment by Mrlinkwii** [comment]
it looks like you may have to update the cheat to thew new format https://forums.pcsx2.net/Thread-Sticky-Important-Patching-Notes-1-7-4546-Pnach-2-0

**Comment by YukiXXL** [comment]
> it looks like you may have to update the cheat to thew new format https://forums.pcsx2.net/Thread-Sticky-Important-Patching-Notes-1-7-4546-Pnach-2-0

I make codes on 1.6 since 1.7 is unstable and tends to crash more than 1.6 when testing.

**Comment by YukiXXL** [comment]
Found the CRC. It's C723B6C6 but now the problem is that selecting cheats isn't possible.

**Comment by Mrlinkwii** [comment]
you need to update to the new format , to be able to select cheats

**Comment by YukiXXL** [comment]
> you need to update to the new format , to be able to select cheats

I did just now.

[7B564230.txt](https://github.com/PCSX2/pcsx2/files/12044082/7B564230.txt)
[C723B6C6.txt](https://github.com/PCSX2/pcsx2/files/12044083/C723B6C6.txt)

**Comment by Mrlinkwii** [comment]
you need serial_crc.pnatch i think

**Comment by YukiXXL** [comment]
> you need serial_crc.pnatch i think

It doesn't work as it needs it's CRC from an ELF that gets launched first.

**Comment by YukiXXL** [comment]
Best thing right now is to stick with the old pnach system and enable/disable by commenting them out in the .pnach file and enabling cheats in the emulation settings.

**Comment by RedDevilus** [comment]
I would say it's better to accomodate to work better than to bypass the issue. 

PCSX2 is improving per revision, if people want to go back to older versions then we aren't doing something correct (yet)

**Comment by YukiXXL** [comment]
I also keep in mind to make the cheats work on real PS2 Hardware aswell. So far they work on mine fine with ps2rd. I don't know if cheats get loaded the old way or the new on PS2 but I aim for compatibility.

**Comment by refractionpcsx2** [comment]
one thing you can do, once it swaps elf, you can go in to the per-game properties and it should show the cheats for the currently loaded ELF, iirc.

**Comment by stenzek** [comment]
> one thing you can do, once it swaps elf, you can go in to the per-game properties and it should show the cheats for the currently loaded ELF, iirc.

It'll show the primary/disc elf.

1.6 is dead, move on, 2.0 release won't be that far away. I see the point about it being an edge case with a loader ELF - in this case, I'd suggest duplicating the pnach file for both CRCs, but leaving the codes empty for the loader.

We will **not** be restoring the old behaviour. It was broken from the beginning, and caused crashes/broken games when patches were applying to the wrong ELF.
