### ISSUE TITLE
[BUG]: Virus "Trojan:Win32/Randet.A!plock" detected in updater.exe

### ISSUE THREAD

**Issue by dftf-stu** [PCSX2/pcsx2#9244]
### Describe the Bug

The "updater.exe" executable is being detected as "Trojan:Win32/Randet.A!plock" by Windows Security, then deleted!

AV version info:
- Antimalware Client Version: 4.18.23050.5
- Engine Version: 1.1.23060.1005
- Antivirus Version: 1.393.218.0
- Anti-spyware Version: 1.393.218.0

I have not had any issues with the built-in AV flagging the "updater.exe" file until just-now, so I don't know if a change has been made to it in the last 24 hours (I last updated the app yesterday) that is suddenly causing this to trigger?

### Reproduction Steps

On a Windows 10 or 11 PC, do one of the following:
- Go into PCSX2, then (assuming you're using the "Nightly" channel) allow it to check for an update, then install it.  The alert will come up during the update process, advising you it has taken action
- Download the latest "pcsx2-v1.7.4727-windows-x64-Qt.7z" file from [here](https://pcsx2.net/downloads) using Microsoft Edge.  It will not allow the file to be saved, as it will advise "file cannot be downloaded - virus detected" (Firefox allows the download)

Windows Security (the built-in AV) will immediately quarantine the file, classing it as "Trojan:Win32/Randet.A!plock"

It will then delete the "updater.exe" executable soon after!

You can view this detection [here](https://www.virustotal.com/gui/file/6d63e9d14785f6484500514eb32436aab45d97fdaa21a14df31451b09796d6ee) on VirusTotal

### Expected Behavior

Either
- The "updater.exe" module should be free from viruses

or:
- A "false-positive" should be reported, as deleting this file means the app can no-longer update itself in future, and a fresh manual-download will be required by users to restore this file

### PCSX2 Revision

pcsx2-v1.7.4727-windows-x64-Qt

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

N/A

### Logs & Dumps

N/A

**Comment by refractionpcsx2** [comment]
not much we can do about it, it's a false positive. If you wanna submit it to Microsoft you're welcome to, but we just have to wait it out. Sorry.

**Comment by dftf-stu** [comment]
@refractionpcsx2 "...but we just have to wait it out"

No-one in this project can submit the file to Microsoft... you'd rely on users to do that?

And you're definitely-sure by closing this ticket so-quickly that there have been no-recent code-changes in the "updater.exe" file that could suddenly be triggering this, given I update the app regularly and this is the first-time that file has been flagged?

**Comment by refractionpcsx2** [comment]
I can guarantee it, this is *not* a virus.  We're no stranger to Defender flagging us up as a virus, and we've submitted them to microsoft before and gotten nowhere.

**Comment by RedDevilus** [comment]
The updater code seems to not have been changed in quite awhile either. Antivirusses these days are super paranoid but in the best they were too weak, kinda annoying.

**Comment by dftf-stu** [comment]
@refractionpcsx2 , @RedDevilus false-positive report filed with Microsoft, case ID: b0e6b0af-3f6d-4c07-95f6-761966eb0ab5 

HOWEVER: I notice that "updater.exe" and "pcsx2-qt.exe" are not digitally-signed (as are none of the DLL files).  Many AVs are less-picky about flagging files if they have a valid Digital Signature.  Is this perhaps something you could consider doing?  I know for websites, [Let's Encrypt](https://letsencrypt.org) is a free-option.  Maybe a similar, free service also exists for signing files? 🤔

**Comment by refractionpcsx2** [comment]
Yeah we used to have a certificate, the problem with the free one is you need to be sponsored to get it, otherwise it's paying for it, and that can be quite expensive for very little gain for us (we've had one previously, and tbh it didn't really help...)

But thank you for helping, I appreciate it.

**Comment by stenzek** [comment]
Authentication isn't really going to provide any guarantees about whether a binary contains malware or not - it's just to prove that the file was produced by who you expect, and wasn't modified during download. Malware could be digitally signed as well.

> I know for websites, [Let's Encrypt](https://letsencrypt.org/) is a free-option. Maybe a similar, free service also exists for signing files?

AFAIK Lets Encrypt is just TLS certs, not code signing certs. Code signing certs tend to be quite pricey.

**Comment by dio-gh** [comment]
Only EV (extended validation) certificates (~$500+/year) are worth anything, and those only silence SmartScreen, not Defender. The rationale behind that is as stenzek stated.

**Comment by Speedy11CZ** [comment]
Yesterday I submitted updater.exe to Microsoft for manual analysis. Today I received a reply. The file was found to be harmless and Defender now reports the file as harmless as well. Also according to VirusTotal, defender stopped detecting updater as malware. So I believe this issue is resolved.
