### ISSUE TITLE
[Feature Request]: external shader missing why now i dont can add shader Guest_AA_2o_Daisy...

### ISSUE THREAD

**Issue by zerr2019** [PCSX2/pcsx2#9259]
### Description

why remove this ?

now it's not going to add GS shaders

reshade won't change anything because reshade doesn't have a good filter that would smooth PS2 textures well

reshade has no shader : Guest_AA_2o_Daisy which smoothed textures well without glitches appearing.

will external shader come back?

so far there is no effective anti-alasing that would smooth jagged textures well without losing sharpness of course.

only this shader Guest_AA_2o_Daisy smoothed it out a bit, it made a bad image, but you could sharpen it with reshade, and you removed the external shader and reshade does not have the Guest_AA_2o_Daisy filter..

### Reason

missing external shader... GS

### Examples

edges cannot be smoothed effectively

and the standard options cause glitches in the graphics as you probably know.

**Comment by MrCK1** [comment]
If you want edge filtering, there are already plenty of options for texture filtering as well as applying FXAA

**Comment by stenzek** [comment]
Because it was terrible. Use reshade if you want post.
