### ISSUE TITLE
[BUG]: Settings icons stretched in native theme

### ISSUE THREAD

**Issue by Mbee2** [PCSX2/pcsx2#9269]
### Describe the Bug

The icons in the native theme are appearing stretched, maybe it's a programming error, the other themes are not affected.
Native:
![Native](https://github.com/PCSX2/pcsx2/assets/136722551/6e6d9c1b-c125-4ae8-a29d-cfbd376a61a7)
Theme Fusion:
![good](https://github.com/PCSX2/pcsx2/assets/136722551/c2b101d6-706b-454a-bf47-74eaed1571da)
![comp_unknown_2023 07 17-13 48_1](https://github.com/PCSX2/pcsx2/assets/136722551/1f556ec4-d1a9-4fe7-a244-336492435ef7)

### Reproduction Steps

Settings > Interface > Theme: native.  

compare with other themes.

### PCSX2 Revision

1.7.4746

### Operating System

Windows 10 (64bit)

**Comment by Felipefpl** [comment]
Sorry for using your post for this but i didnt want to create a new thread just for that since it's a small cosmetic issue, i can't see the links with the light fusion skin enabled:
![Sem título](https://github.com/PCSX2/pcsx2/assets/5569804/e3a6d356-d13e-4faa-827f-ddfd639f3610)

**Comment by kamfretoz** [comment]
> Sorry for using your post for this but i didnt want to create a new thread just for that since it's a small cosmetic issue, i can't see the links with the light fusion skin enabled, i'm using the latest build:

Looks fine here

![image](https://github.com/PCSX2/pcsx2/assets/14798312/e49609ea-738f-4f35-ba52-b7de8fa0b7b8)

**Comment by MBeeBR** [comment]
seems to be windows 7

**Comment by Felipefpl** [comment]
@kamfretoz - Strange, now pcsx2 loads the colors correctly but i didnt change the theme of win10 before selecting pcsx2's light theme. Weird for sure. Thanks for your help.

**Comment by Mrlinkwii** [comment]
i cant replicate the issue on v1.7.5081

**Comment by refractionpcsx2** [comment]
Replicated it here on windows
![image](https://github.com/PCSX2/pcsx2/assets/6278726/a094d036-8860-4183-8eeb-6cfe32a07d5d)

**Comment by TheTechnician27** [comment]
I can confirm that this doesn't seem to be an issue on Linux (Manjaro; Flatpak; v1.7.55537).

**Comment by kamfretoz** [comment]
> I can confirm that this doesn't seem to be an issue on Linux (Manjaro; Flatpak; v1.7.5537).

It only happens on Windows

**Comment by MrCK1** [comment]
Still exists on 1.7.5946

**Comment by JordanTheToaster** [comment]
Still an issue on v2.1.217.
