### ISSUE TITLE
Flashing cars in Midnight Club 3 DUB ntscu

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#9273]
### Describe the Bug

flashing cars

### Reproduction Steps

just play the game

### Expected Behavior

the cars when the camera moves flash into silver and then back to their color

### PCSX2 Revision

1.7.4748

### Operating System

Windows 11

### CPU

ryzen 9

### GPU

rtx 3080

### GS Settings

<img width="454" alt="image" src="https://github.com/PCSX2/pcsx2/assets/125753543/0a2a5798-527a-47ea-8be7-0dbeb839bd89">
<img width="450" alt="image" src="https://github.com/PCSX2/pcsx2/assets/125753543/bb6811a0-13ca-4c47-988d-a3baf78b90d8">
<img width="461" alt="image" src="https://github.com/PCSX2/pcsx2/assets/125753543/d522b171-ef0d-4b99-90ef-c36f1021aabc">

### Emulation Settings

<img width="449" alt="image" src="https://github.com/PCSX2/pcsx2/assets/125753543/8d4a8cf0-4f1d-45fa-a31d-265500cd02de">

### GS Window Screenshots

https://github.com/PCSX2/pcsx2/assets/125753543/536662ea-729b-4cc4-a510-c9dcc6e62ecf

**Comment by stenzek** [comment]
GS dump?

**Comment by Mrlinkwii** [comment]
game works fine here , would this be an issue with the texture pack your using?

**Comment by stenzek** [comment]
Texture pack could indeed cause issues. If it still occurs on the latest builds, without a texture pack, please post a GS dump and we can reopen.
