### ISSUE TITLE
[BUG]: `Patches`, `Cheats` and `Game Fixes` is missing if you don't add the game to the `Game List`

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#9283]
### Describe the Bug

I was wondering where the hell i can find the game options `Patches`, `Cheats` and `Game Fixes` after you start a game using `Run File`:

https://user-images.githubusercontent.com/11288319/240978795-0a08c463-587f-4c77-afe0-206da0556e11.png

After talking to the folks over at the PCSX2 Discord i noticed that people usually add their games to the `Game List`, which i did not do. If you don't add the game to the game list, the game options `Patches`, `Cheats` and `Game Fixes` are not available:

![Screenshot 2023-07-19 202228](https://github.com/PCSX2/pcsx2/assets/37260321/75b79dc9-8345-4593-891f-a8f84311dd8d)

### Reproduction Steps

1. Download PCSX2 nightly
2. Start PCSX2, uncheck `Automatic Updates` and do not add a `Game List directory`
3. Start a game using `Start File`
4. Check for the options `Patches`, `Cheats` and `Game Fixes` in the `Game Properties`

### Expected Behavior

I usually don't highly customize nightly PCSX2 builds, and this includes not adding a game list and disabling automatic updates. But i think that the `Game Properties` should display `Patches`, `Cheats` and `Game Fixes`, even if you don't add the game to the `Game List`. 

### PCSX2 Revision

pcsx2-v1.7.4752-windows-x64-Qt

### Operating System

Windows 11

**Comment by stenzek** [comment]
Not having it in the game list is going to create issues with per-game settings, since it can't pull metadata (e.g. that's why the title is showing as UNKNOWN). Tbh we probably should just disable it completely in this case.
