### ISSUE TITLE
NHL Hitz 2002

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9284]
### Describe the Bug

I didn't know where to post this issue as this is not technically a bug but an update to GameDB if possible as this game needs EE Cycle Skipping = Mild Underclock to be enabled for it to perform 100%.
As soon as you go into a match, the performance DRASTICALLY drops to 10-15 FPS.

I've added a GS dump down below if needs be.

### Reproduction Steps

Press Start, choose Exhibition, choose a team, select your players, select a stadium, wait until the players come out....

### Expected Behavior

Full performance

### PCSX2 Revision

V1.7.4752

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Default settings.

### Emulation Settings

Native settings.

### Logs & Dumps

[NHL Hitz 2002_SLUS-20140_20230719194314.zip](https://github.com/PCSX2/pcsx2/files/12099309/NHL.Hitz.2002_SLUS-20140_20230719194314.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/69f61f56-60c9-4778-9b9f-dc9aa84e135d)
works fine here with defaults

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/9cc40e2d-f9ac-43ad-8f4c-a2649a5c6239)
