### ISSUE TITLE
DEV9ghzdrk - Crash if WinPcap service isn't running

### ISSUE THREAD

**Issue by TheLastRar** [PCSX2/pcsx2#93]
If the WinPcap service isn't running, PCSX2 will crash if you try when you select shutdown or pause the emulator.

The plugin does correctly detect that it can't open the adapter, but doesn't seem to consider this when the emulator is paused.

**Comment by atomic83GitHub** [comment]
It is not realy an issue, DEV9ghzdrk is a winpcap based plugin. Maybe include winpcap in the pcsx2 installer can be a sort of fix or download CLR_DEV9 beta wich work with winsock (and winpcap if available).
