### ISSUE TITLE
[BUG]: Front mission 4 issues that were fixed before redesign

### ISSUE THREAD

**Issue by metalslayer** [PCSX2/pcsx2#9305]
### Describe the Bug

Text and Dialog Boxes issues in upscale (v1.6.0 Fix - Texture Offsets 0500 X , 0500 Y)
Blur in hangar (Wanzer Setup) issue in upscale  (v1.6.0 Fix - UserHacks_SkipDraw=2)

### Reproduction Steps

All setting in recent PCSX2

### PCSX2 Revision

v.1.7.4772

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 2660X

### GPU

RTX 2060

### GS Window Screenshots

![2023-07-22_15-01-47](https://github.com/PCSX2/pcsx2/assets/19173199/8c8218ac-e06c-4875-ab7f-1bc76cb45815)
![2023-07-22_15-37-08](https://github.com/PCSX2/pcsx2/assets/19173199/dc222801-67d7-426a-8fc9-fb465345ed93)
![2023-07-22_15-39-41](https://github.com/PCSX2/pcsx2/assets/19173199/693b6ab2-6d6f-4c54-a338-6cc8b283246c)

**Comment by stenzek** [comment]
> Text and Dialog Boxes issues in upscale (v1.6.0 Fix - Texture Offsets 0500 X , 0500 Y)
> Blur in hangar (Wanzer Setup) issue in upscale (v1.6.0 Fix - UserHacks_SkipDraw=2)

This is not helpful. Either bisect it to an exact build, and/or (preferably) upload a GS dump.

**Comment by stenzek** [comment]
Game uses region repeat on a tiny 8x8 region, so it's possible this has precision issues.

Either way, texture offset of 4 sorts it out. Skip draw always was and is a hack, you can't expect it to work reliably.

**Comment by metalslayer** [comment]
![2023-07-22_17-00-46](https://github.com/PCSX2/pcsx2/assets/19173199/84384d31-7734-46d0-b4ab-f7c1014e873b)
For some reason SLPM-65443 NTSC-J has less issues with blur and shadows compare to USA
