### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Mclaneinc** [PCSX2/pcsx2#9306]
### Describe the Bug

When trying to save a state to file I get and error re failed to save state use of usb.bin

### Reproduction Steps

I only tried a save state on Second Sight, tried to save the file state on the initial stealth training mission.

### Expected Behavior

To save a file state..

### PCSX2 Revision

1.7.4722

### Operating System

Windows 10 (64bit)

### CPU

i7 3.4ghz

### GPU

GTX 750ti

### GS Settings

stadard default using Vulkan engine..

**Comment by stenzek** [comment]
Since you didn't include any of your USB settings, nor a proper issue title, closing as invalid.

I'm guessing you've added the turntable device, because that's the only one which can't save.

**Comment by Mclaneinc** [comment]
Sorry Connor, I don't do many bug reports these days, missed those items to add. Apologies, but even after that you may well have fixed it, yes I did have the turntable enabled.Thank you, apologies again..

**Comment by stenzek** [comment]
FYI it should be resolved by #9318.

**Comment by Mclaneinc** [comment]
Yes I saw, thank you, and again, apologies for the lack of details. PS amazing work on Duckstation and PCSX2, great work by all the devs.
