### ISSUE TITLE
Jak and Daxter: The Precursor Legacy - Stuttering, Unknown Vifcmds

### ISSUE THREAD

**Issue by FirstRoboticsGuy999** [PCSX2/pcsx2#931]
PCSX2 versions used: pcsx2 v1.3.1-1350-gd81481a
Emulation settings: "Safest" preset, no hacks.
Plugins used: GSdx-SSE3, cddvdGigaherz
Plugin settings: DX11 HW, CRC Hack Level "None"

Hardware Specifications
CPU: Intel® Core™ i5-4460 CPU @ 3.20GHz
GPU: Intel HD Graphics 4600 (Driver 10.18.14.4294)
HDD: Western Digital Blue 1TB (WDC WD10EZEX-00BN5A0)
4GB Ram, Win 7 64-Bit Home Premium
Description

While walking around in the world, the game will stutter when large chunks of manual blocks are being cleared. The other issue is pretty minor I guess, but I have also noticed that the console spews several unknown Vifcmds while collecting Precursor orbs.

Log: http://www.filedropper.com/errorlog

**Comment by refractionpcsx2** [comment]
> C:\Users\Christian\Downloads\jak.iso

Get a legitimate version of the game, recreate the issue and then maybe we will help you. We don't support piracy.
