### ISSUE TITLE
[Feature Request]: Mobile phone support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [PCSX2/pcsx2#9313]
### Description

Port pcsx2 to Android and iOS.
Create apk, ipa, and deb files for each new release.
Make all of PCSX2's features available like cheats and widescreen patches.

### Reason

I like ps2 emulation, and I would like to do the same on my phone. I am currently using Play!, and it's not pretty good. So, I was thinking. Do you think you can port the emulator to android and iphone, as well as ipad and android tablet. Your emulator is much better and longer developed.

### Examples

You support multiple rendering softwares, custom resolution input instead of multiplying by 2, cheat support, retroachievements, anisotropic filtering, widescreen patches, and many more. Features that Play! doesn't support.

**Comment by refractionpcsx2** [comment]
No, we're not doing a mobile version after seeing how the aether devs were treated.

**Comment by F0bes** [comment]
Aethersx2 has android / arm support.
iOS is not emulation friendly and therefore would be very low priority.

**Comment by Iamthebestintheworld222** [comment]
No, I was maybe hoping if you, as the programmer, can tweek the emulator to support android and ios.

**Comment by F0bes** [comment]
I appreciate the enthusiasm, but it's a lot more work than "tweaking" the
emulator.
It's not a priority for us at this point in time.

**Comment by Iamthebestintheworld222** [comment]
Okay, remind me when you think about porting it to iOS and android.
