### ISSUE TITLE
[BUG]: Input Profile doesn't load even with Per-Game Settings active

### ISSUE THREAD

**Issue by PolygonSlayer** [PCSX2/pcsx2#9324]
### Describe the Bug

When setting the Input Profile in a games setting it does not seem to load as part of the per-game settings. Instead it will load the "default" input profile.
Have tried to run the game via default boot, fast and slow boot. Same result.

### Reproduction Steps

- Right-click on a title in the games list and select a different input profile than the default one.
- Run the game and notice that it does not load the correct profile.

### Expected Behavior

That the game will load with the desired input profile activated.

### PCSX2 Revision

v1.7.4779

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
It's working here.

Are you using big picture/nogui mode or anything?

**Comment by stenzek** [comment]
Also working fine here. Might be user error.

**Comment by PolygonSlayer** [comment]
Yep, Enable per-game settings is ticked in the main setting. It happens both by launching via a frontend and also just when I try and boot it via the games menu.
Am I correct in assuming the Input Profile should be loaded regardless of which mode you use to boot the game as well? for example Default, Fast and Full?

When I launch it via Launchbox I got -fullscreen -batch -fastboot as my commands.

My default settings in the emulator as just "Shared" for the controls, which has 2 pads connected. I made a Input Profile with multitap enabled and no matter what the games will boot with the Shared profile even when I got the config for the game (Right-click --> properties on the game, right?) set to be using the multitap profile.

**Comment by refractionpcsx2** [comment]
okay, what settings are you using which are different from the normal profile? Is it just the multitap?  Have you tried messing with the button config of the second profile to see if it picks up the alternate buttons?

**Comment by stenzek** [comment]
Also works fine with me putting multitap in the input profile.

Remove launchbox from the equation. Only use pcsx2. But I suspect this is a support issue.

**Comment by PolygonSlayer** [comment]
So for this specific game I'm trying it just has the multitap input profile as different to the default settings.
If I select the profile manually while the game is already running it does all work as expected with all 4 gamepads.

and, yeah, trying to troubleshoot this outside of LB as I can't get it to pick up the settings even inside pcsx2 right now.

**Comment by PolygonSlayer** [comment]
My main settings:
![image](https://github.com/PCSX2/pcsx2/assets/44800819/ceb2f996-061e-453b-ac6f-44856f6a06b5)

The game settings:
![image](https://github.com/PCSX2/pcsx2/assets/44800819/d475d9be-46f2-46cd-af7d-9c61b657ff12)

Booting the game and then checking controller settings:
![controllersettings](https://github.com/PCSX2/pcsx2/assets/44800819/805ad14f-7812-4385-a958-56130af2a6ff)

**Comment by kamfretoz** [comment]
@PolygonSlayer please continue on our Discord server as we're reaching the support territory.

**Comment by stenzek** [comment]
... yes, this is user error.

The settings dialog is showing you which profile you are **editing**. That has nothing to do with what the game is actually using. If you check the log, you should see that it is loading the profile.

**Comment by PolygonSlayer** [comment]
Ok, so enabled and checked the log and even though it is loading it apparently:

_Loading game settings from 'D:\Emulators\PCSX2\gamesettings\SLES-50078_288AA369.ini'...
[    5.0266] Loading input profile from 'D:\X_Emulators\PCSX2\inputprofiles\Multitap Port 1.ini'...
[    5.0266] Applying settings..._

 but there is definitely something else happening as well.
So when the game menu shows up, I can only select 1 Player:
![1p_only](https://github.com/PCSX2/pcsx2/assets/44800819/71ddcfe0-561d-4af8-8842-5ca09885be10)

While if I go into the controller menu and uncheck, and then check the multitap box it enables in game:
![4p](https://github.com/PCSX2/pcsx2/assets/44800819/57df8e9e-17b0-41d4-918b-f35aa95d845d)

Could not be a bug, but I don't know what it could be especially if it is loading the correct profile?

**Comment by Mrlinkwii** [comment]
If you need further help use the discord or forums :)

**Comment by PolygonSlayer** [comment]
alright, cheers

**Comment by RedDevilus** [comment]
Culprit could be:
https://github.com/PCSX2/pcsx2/compare/v1.7.4593...v1.7.4594

**Comment by Henrique-Tadeu** [comment]
I'm having the exact SAME problem. Did you find any solution?

**Comment by PolygonSlayer** [comment]
Nope, no current solution apart from manually re-enabling it after the game loads.
I got some help doing some debugging in the discord from @RedDevilus, which is why he tagged the potential culprit here, but the bug is still closed so not sure if anyone it looking into it more.
Glad I'm not the only one with this issue. :)

Its most definitely not a user issue, im pretty sure now. Despite my inital confusion of what the controller window was showing. The fact is that the game itself is not detecting the multitap on boot, even when it does show its loading via logs and shows in the OSD. I have to manually re-enable it for it to work, some games even show the player select screens change while doing it.

What I was wondering though was if I was the only one experiencing it then it might be something locally on my PC somehow.

**Comment by refractionpcsx2** [comment]
Wasn't the result something about multitap not working right, or something?

**Comment by PolygonSlayer** [comment]
So when I set a games properties to load a specific Input Profile. The emulators logs shows that the profile is loaded and the OSD show the pads are there, but the game itself, for whatever reason does not detect the multitap until you go into the settings and re-enable the multitap manually.
It's a really odd one :(

So I assume that all that I need to do is to make a Input Profile that has multitap enabled in the correct port for said game. Then in the games properties window I select the Input Profile to be used. I'm not missing something here?

**Comment by stenzek** [comment]
The multitap setting engages from the input profile - I checked this in the pad cleanup PR.

**Comment by Henrique-Tadeu** [comment]
Even when setting the multitap on the "shared" profile it won't work. As PolygonSlayer said, the multitap port needs to be disabled/re-enable when the game is ALREADY running.

**Comment by RedDevilus** [comment]
Confirmed that v1.7.4594 broke it.

Relevant: https://github.com/PCSX2/pcsx2/issues/9657

**Comment by stenzek** [comment]
The issue is not specific to input profiles.
