### ISSUE TITLE
[Feature Request]: There is no NTSC-K.

### ISSUE THREAD

**Issue by Hackjjang** [PCSX2/pcsx2#9333]
### Description

The PlayStation 2 in South Korea was released with the region code 'NTSC-J', and there is no separate region code 'NTSC-K'.

It seems to be a way to include users who were using it before it was officially released in Korea. In any case, NTSC-K doesn't exist.

Game titles that have been officially released in Korean localisation are also in NTSC-J.

**Comment by kamfretoz** [comment]
There is the region code for NTSC-K South Korean release, can you tell us which game are incorrectly labelled? we can fix it
![image](https://github.com/PCSX2/pcsx2/assets/14798312/a2d2b977-c510-4639-85b9-5719f805a17b)

**Comment by stuken** [comment]
There also isn't PAL-UK or NTSC-B. It's used to map the localization flag icon on the ui as the actual product codes don't always accurately reflect this info.

**Comment by stenzek** [comment]
I'm confused as to what you're asking for here.

**Comment by dio-gh** [comment]
They are (understandably) confused by the pseudo region codes the emulator uses (aimed at pairing every release with a corresponding economic area) and the region codes that were actually in use by the platform (NTSC-U/C, NTSC-J and PAL). They're asking for the region listings to be corrected or clarified (implied).

**Comment by RedDevilus** [comment]
The other issue is that Regions in PCSX2 are actually a combination of Region + Available languages (also only displays one of them for flag), which also means more broad filtering.

Personally I envision it more as

Old format:
NTSC-K

New Format:
NTSC-J
Korean + ... language support

**Comment by dio-gh** [comment]
I don't know where the current regions list was conjured from, seems completely made up. Region codings often utilize the given area's dominant [broadcast television system designation](https://en.wikipedia.org/wiki/Broadcast_television_systems#ITU_standards), but the actual meaning in practice is completely specific to the media format and vendor at hand. This is how you can have NTSC-K [region name] clash with the actual NTSC-K [non-existent television system], or have NTSC-J [region name] [be different to NTSC-J [the television system]](https://en.wikipedia.org/wiki/NTSC-J#Marketing_definition) and thus present in South Korea. The Internet has also contributed its own fair share of misleading names to this topic (think PAL-M6, which is really just PAL [region] MULTI-6 [six languages]).

If the project no longer wishes to partake in this madness, displaying the actual region information present on the discs, and using one of the many [country code](https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements) and [language code](https://en.wikipedia.org/wiki/IETF_language_tag#List_of_common_primary_language_subtags) standards on the side could be a good solution. This is also what OP has troubles with; that the NTSC-K [region] didn't exist back then, and so the current labeling is incorrect. Releases marked as NTSC-K right now are actually all NTSC-J.

**Comment by refractionpcsx2** [comment]
So who wants to completely rewrite our 53k line gamedb to change the region and language information to a system which isn't made up? anyone? 

I'm expecting crickets here, our system works fine, the first part specifies the type of signal that is used, the second part is our rough language for the area it was released in. It's not a standard, no, it was never meant to be, it's a system just for us.

**Comment by RedDevilus** [comment]
Bigger issue is that Sony itself doesn't know the full extent of it either, they didn't keep 100% track. The closest thing before redump and other places was: https://web.archive.org/web/20141105075540/http://sonyindex.com/

**Comment by lightningterror** [comment]
Trivial, if some game regions are wrong they can be corrected.
