### ISSUE TITLE
[Feature Request]: Allow macro to stay active when the game window is not

### ISSUE THREAD

**Issue by Serie9** [PCSX2/pcsx2#9339]
### Description

Currently:

Activate any Macro, for example "Press Circle every 2 frames".

Click away from the PCSX2 Nightly window to any other window or even just the desktop -> Macro stops.

Change:

Activate any Macro, for example "Press Circle every 2 frames".

Macro stays active, even if the PCSX2 window is in the background and you're surfing the internet or whatever.

### Reason

Some games require some heavy farming where an auto-fire button is needed.

With the help of a macro and the frame limiter off this can be made much faster, but the moment you click away from the PCSX2 window to a browser to watch YouTube or do whatever, the macro stops.

### Examples

Any application that offers a macro function and doesn't stop the macro once you click off it.

**Comment by stenzek** [comment]
Not possible for keyboard input.

I guess we could have an option to allow SDL background input for controllers:  https://wiki.libsdl.org/SDL2/SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS

**Comment by stenzek** [comment]
Checked this, the SDL flag above has no effect on PCSX2, because we don't use SDL's window subsystem.

Therefore, this is already the case - background controller input goes through fine, confirmed with a DS5.
