### ISSUE TITLE
Superman Returns: The Videogame - bad graphic

### ISSUE THREAD

**Issue by n1dminhd** [PCSX2/pcsx2#934]
v1.3.1-1352-gdc58857

Opengl HW
![opengl hw](https://cloud.githubusercontent.com/assets/4449742/10765681/77f2c268-7d06-11e5-8de7-49d640159fa6.jpg)
Opengl SW
![opengl sw](https://cloud.githubusercontent.com/assets/4449742/10765678/77edce98-7d06-11e5-8018-8c6027e638a9.jpg)
DX11 HW
![dx11 hw](https://cloud.githubusercontent.com/assets/4449742/10765692/8b1318c0-7d06-11e5-8fe3-e4bfa0159d01.jpg)
DX11 SW
![dx11 sw](https://cloud.githubusercontent.com/assets/4449742/10765693/8b3bbf96-7d06-11e5-81ff-d2867217fe6c.jpg)
Sorry, I bad Eng !

**Comment by ianvarivs** [comment]
Here's are some videos for reference
https://youtu.be/EM3J6MoxBqo
https://youtu.be/IqyFL2CbY7A

Apparently, polygons of sorts appear on SW mode and the red/green lines appear on HW mode if CRC is set to anything but None.

Polygons are gone whenever you fly far from the buildings.

**Comment by willkuer** [comment]
SuperVU vs microVU?

**Comment by ianvarivs** [comment]
Tried both.

Though, those videos were using microVU, both VU1 and VU2

**Comment by toozzb** [comment]
lighningerror could you explain me why this is happenig my pc is good i tried use the OpenGL ofc its the best feature for this game but that bug still remain there its something we need to do on pcx2

**Comment by lightningterror** [comment]
D3D should be better now compared to before (1.3/1.4). The vertical stripes should be gone.

**Comment by toozzb** [comment]
ligtnin the thing is when i use opengl the only thing for get rid of strikes, but the bug of building still there
anyway to fix this i uploaded the link for u

**Comment by toozzb** [comment]
I have another one on underground without building, this means i dont get bugged but if i go to building i get bugged

![vgf](https://user-images.githubusercontent.com/38509697/40499590-4ad38728-5f7a-11e8-90f5-d2e14ed961b5.png)


![gtg](https://user-images.githubusercontent.com/38509697/40499736-b5482780-5f7a-11e8-9466-04e0f037fdb6.png)

The cars are blinking underground

And the bug part
![vlff](https://user-images.githubusercontent.com/38509697/40499764-cc316ea2-5f7a-11e8-89de-6c463b4252c1.png)

**Comment by minanagehsalalma** [comment]
@n1dminhd 
@lightningterror 
@willkuer 
@ianvarivs 
is it fixed now ?

**Comment by lightningterror** [comment]
No.

**Comment by minanagehsalalma** [comment]
@lightningterror  why ?

**Comment by refractionpcsx2** [comment]
A patch for this has been added to master

**Comment by minanagehsalalma** [comment]
> A patch for this has been added to master

@refractionpcsx2 where ? The last master version is on May 7

**Comment by refractionpcsx2** [comment]
> > A patch for this has been added to master
> 
> @refractionpcsx2 where ? The last master version is on May 7

No it isn't, the latest master is today.

**Comment by minanagehsalalma** [comment]
> > > A patch for this has been added to master
> > 
> > 
> > @refractionpcsx2 where ? The last master version is on May 7
> 
> No it isn't, the latest master is today.

@refractionpcsx2 where ?  The one on the site is dated to  07-05-2020

And the one in the releases tab on here is may 7.

**Comment by tadanokojin** [comment]
https://buildbot.orphis.net/pcsx2/

**Comment by minanagehsalalma** [comment]
> https://buildbot.orphis.net/pcsx2/

@tadanokojin oh thanks that what i was lookin at right now but there is only 32 bit versions .

**Comment by tadanokojin** [comment]
You only need the 32bit version

**Comment by minanagehsalalma** [comment]
> You only need the 32bit version

@tadanokojin what about the Recommended system requirements 

> Windows 10 (64 bit)

**Comment by refractionpcsx2** [comment]
You need windows 8.1 or higher.

**Comment by minanagehsalalma** [comment]
> You need windows 8.1 or higher.

@refractionpcsx2 i know ... but how can i get use of the 8 GB ram with this 32 bit version?

**Comment by refractionpcsx2** [comment]
Just get the bloody download.

**Comment by minanagehsalalma** [comment]
> Just get the bloody download.

@refractionpcsx2 lol , okay mate and thanks for help

Sorry for bothering  :)

**Comment by RedDevilus** [comment]
PCSX2 doesn't even use beyond 1GB of RAM hence why 32bit or 64bit download doesnt matter.

**Comment by minanagehsalalma** [comment]
> PCSX2 doesn't even use beyond 1GB of RAM hence why 32bit or 64bit download doesnt matter.

@RedDevilus good to know .... but then i think the system requirements needs some editing.

**Comment by RedDevilus** [comment]
Using a 32bit OS in 2020 in my opinion is stupid, unless you have old hardware with 4gb ram or less but then you wont be able to use 1.6 or 1.7 versions which is what the requirements are based on. So no, it doesn't need adjusting.
