### ISSUE TITLE
[GSdx Hardware] Burnout Revenge (PAL)

### ISSUE THREAD

**Issue by DPersonalized** [PCSX2/pcsx2#935]
PCSX2 versions used: pcsx2-v1.3.1-1307-g8700132-windows-x86
Emulation settings: All speedhacks and game fixes off (except for MPEG Skip for better comparison)
Plugins used: GSdx AVX, using all renderers.
Plugin settings: CRC Hack Level "None"

Description:
In hardware mode, there seem to be random, dark grey dots and shapes in the characters of most text. For some reason, the load screen hint text does not suffer from this problem, despite using the exact same font as the smaller text in the pictures below. Software mode fixes this problem, hence the tag in the title. 

This bug is also present in **Burnout Dominator, Burnout 3: Takedown** and **Burnout 2: Point of Impact** and (going by what I've seen on YouTube) all regions of all of these games are affected. A similar bug is present in **Burnout**, but is fixed by setting the "Sprite" HW hack to "Half." The reason I chose to report this under Burnout Revenge is simply because it's the game where the bug is the most noticeable and is most prevalent. On the Wiki, this is the "Grey Lines Within Text" issue. All backends are affected and no setting combination fixes the issue in hardware mode, including the Sprite and Round Sprite settings.

Specs:
CPU: AMD Athlon X4 750K @ 4.1GHz
GPU: AMD Radeon HD 7770

Screenshots:

Hardware mode (Native Resolution):
![OpenGL Hardware](http://i.imgur.com/9IEOZJJ.png)

Hardware mode (8x Native Resolution) (huge image warning):
http://i.imgur.com/nc4smvq.jpg

Software mode (expected result):
![)](http://i.imgur.com/EmaPs7K.png)

Console:
![vlcsnap-2015-12-28-10h47m47s153](https://cloud.githubusercontent.com/assets/8225831/12017585/88e24358-ad50-11e5-879c-9b4711fe3c0b.png)

If you look at the 8x Native image, you can see that the dots/shapes are actually lines; very scribbly-looking lines at that. Such a strange bug (to me, anyway.)

GS Dump: https://drive.google.com/file/d/0B3AFeSVGmg9sS0syRXJESlo3ZzQ/view?usp=sharing

**Comment by refractionpcsx2** [comment]
Does it happen in "native" resolution as well?

**Comment by willkuer** [comment]
I think first embedded image is native. There the text is dotted. Resolution is bad.

In the additional link the dots appear as lines.

**Comment by DPersonalized** [comment]
Not sure if this is relevant at all, but when I do a texture rip with Ninja Ripper on the load screen, I get these 3 textures in Software:
http://imgur.com/a/HpiTz

But I get these 3 in Hardware:
http://imgur.com/a/aoblb

Just wondering what this is all about.

**Comment by refractionpcsx2** [comment]
It's a loading screen with different available languages, not at all relevant.

**Comment by DPersonalized** [comment]
No, not that. I was wondering about how two of the images from Hardware seem to be "scaled", even though I was using default settings:

Hardware:
![](http://i.imgur.com/7IoXxRm.png)

The equivalent image from Software:
![](http://i.imgur.com/yESE4M0.png)

The first image dumped from each also seem to be different. In Hardware, I got this:
![](http://i.imgur.com/3ROIWnd.png)

But in Software, I got a 640x448 black square. Maybe it's a problem with Ninja Ripper, maybe not. I'm curious, though.

**Comment by MrCK1** [comment]
Ninja Ripper's injector was always buggy - probably not the most reliable for finding bugs

On an unrelated note, I've noticed that alot of the problematic games all run on RenderWare; so some of the issues seem to be shared across games.

RenderWare Games with text issues
- GTA Series
- Burnout Series
- Bully

**Comment by DPersonalized** [comment]
At one point last year, I actually managed to play Burnout Dominator in hardware mode with the text being completely normal, just like in software mode, but I haven't been able to reproduce that behavior to this day. I was actually using an above-native internal resolution, too. Never been able to do it in any other Burnout game. I'll see if I can reproduce it again.

**Comment by DPersonalized** [comment]
Software still renders the text properly with mipmapping disabled, so I think a mipmapping issue is ruled out.

**Comment by willkuer** [comment]
Has anyone checked the influence of VU rounding and clamping, superVU? Maybe something is done wrong in the vu and rounding/imprecision problems in the gs then lead to different results but the root is actually the vu?

**Comment by DPersonalized** [comment]
@willkuer No effect, from what I can see.

**Comment by FlatOutPS2** [comment]
It always looked more like a depth issue to me. The shadows that should be behind the letters appearing infront of 'em.

**Comment by DPersonalized** [comment]
So I thought this was slightly interesting: here's the only scenario in which it is possible to see both shaded and unshaded letters together on the same screen:
http://i.imgur.com/kFEcs0D.jpg (Large image warning)

Notice how the only text without shading/outlines, "EFFECTS VOLUME" and "MUSIC VOLUME", do not have the problem. The same thing goes for the text on loading screens, which is also unshaded/has no  outlines and also shows up perfectly fine in hardware mode.

**Comment by DPersonalized** [comment]
@FlatOutPS2 Disabling depth emulation doesn't seem to have any effect on the issue. Could it still be a depth issue, regardless?

**Comment by FlatOutPS2** [comment]
Yes, it can. Disabling depth emulation would only have affected the issue if it had already been solved.

**Comment by gregory38** [comment]
Fwiw, I confirme it is the same issue as #1499

**Comment by gregory38** [comment]
The PR #1514 will improve the situation on burnout games (at least the one from the above dump). It would be nice if others games could be tested as well.

**Comment by DPersonalized** [comment]
#1514 Fixes this issue in Burnout Revenge, so I'll be closing this now.

**Comment by ssakash** [comment]
Please close the issue only after #1514 is merged.

**Comment by gregory38** [comment]
@DPersonalized do you have more game of the burnout series ? Or was the bug only for a single version of the game ?

**Comment by FlatOutPS2** [comment]
It affects all other Burnout games to some degree. The PR fixes all text issues in Burnout 3, Revenge and Dominator. Don't know about Burnout 1 and 2.

**Comment by DPersonalized** [comment]
@FlatOutPS2 Burnout 1 is already fixed by setting Sprite to Half. I don't have Burnout 2 to test, but I'm pretty sure the PR will fix it.

**Comment by FlatOutPS2** [comment]
Actually, Burnout 2 wasn't fixed by the origonal PR. I tried the demo and it wasn't fixed until gregory's update. It would be nice to to know if Burnout 1 is fixed as well, the half sprite fix might not be necessary anymore.

**Comment by gregory38** [comment]
Well there is a bug ib my depth handling. I need to correct it first.

**Comment by gregory38** [comment]
@FlatOutPS2 could you retest burnout 2 on latest git.

**Comment by FlatOutPS2** [comment]
It's still fixed on my port of your latest change, so it should be good.

**Comment by FlatOutPS2** [comment]
This has now been fixed in OGL and DX renderers, so time to close this.
