### ISSUE TITLE
Horizontal Lines (Scanline-esque)

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#936]
This is a bit of an odd issue, since I noticed it a while back in the DX backend for MGS3, but I didn't think it was serious since I don't use DX. But now it seems to affect GL, too. And it doesn't just affect hardware mode, it affects software mode.

Quantum of Solace:
![horizontal lines](https://cloud.githubusercontent.com/assets/10704701/10777722/120f4f02-7d6a-11e5-8934-b47287631577.PNG)

This is what a screenshot dump looks like, though.

![gsdx_20151028114431](https://cloud.githubusercontent.com/assets/10704701/10777744/5ceaadb4-7d6a-11e5-872d-57040da95869.jpg)

I can't imagine games are supposed to look this way. I tested a few other games (FFXII among them) and they all seem affected.

**Comment by vsub** [comment]
Try pressing F7 few times(that's a feature)

**Comment by AmbientMalice** [comment]
Thanks a bunch. IMO, it seems like the feature should be better documented, and probably listed in the GSDX configuration menu.

**Comment by gregory38** [comment]
Yes it could be interesting to add a menu entries. Could you open an issue for it?
