### ISSUE TITLE
Reduce register flushing before standard EE-RAM access

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#937]
After a lengtly discussion with @sudonim1 we got an idea to handling the flush of X86 register differently.

Current situation in pseudo code.
```
iFlushCall(FLUSH_FULLVTLB);
     => Flush EAX/ECX/EDX
     => Flush XMM/MMX registers
```
```
vtlb_DynGenRead64(bits); 
    => Generate X86 code to handle the memory access
    padd = compute_physical_address(eax, ecx)
    if physical address is a special handler 
    then 
            jump to indirect C++ dispatcher
    else 
            do a fast memory access
```
We currently need to flush for 2 reasons.
1/ We are currently using EAX/EBX/ECX/EDX in TLB stuff.
2/ We jump to a C++ function that might change the XMM/MMX registers.

The indirect dispatcher is just a wrapper that compute the address of the handler and call it.
```
0xa0e6080 <_ZL21m_IndirectDispatchers+128>:	movzbl %al,%eax
0xa0e6083 <_ZL21m_IndirectDispatchers+131>:	sub    $0x80000000,%ecx
0xa0e6089 <_ZL21m_IndirectDispatchers+137>:	sub    %eax,%ecx
0xa0e608b <_ZL21m_IndirectDispatchers+139>:	call   *0x9eea980(,%eax,4)
0xa0e6092 <_ZL21m_IndirectDispatchers+146>:	jmp    *%ebx
```

The idea is to defer the flushing of XMM/MMX registers in the dispatchers.

My hypothesis are
* Most of memory access target the EE RAM (so the fast path)
* Most of memory access that target a register likely use a constant address.

So we move the flushing of a couple of register from the hot path to the cold path. To ease the code. I propose to use a brutal save_mm_context/load_mm_context code around the C++ call in the dispatcher. In 32 bits the number of register are rather limited. So worst case will add 16 x 128 bits + 16 x 64 bits moves in the (already slow) path.

Opinions are welcome.

**Comment by gregory38** [comment]
@refractionpcsx2 what do you think about it?

**Comment by refractionpcsx2** [comment]
I guess it depends on the ratio of fast path vs slow path calls. presumably the fast path one are frequent and slow path are rare, but is it enough to negate the many more cycles it will take to do the full flush?

**Comment by gregory38** [comment]
Yes it is all depends on the frequency of those paths. We could potentially optimize the context saving part. I don't know the standard loading of the MM/XMM register (barely used, often used). The advantage of the context is to be lighter for caches. All memory caches will reuse same flushing code.

I propose to do a benchmark implementation. (on going).
* Only add the full context flush. Code will be useless but it is allow to see the negative impact
* Then remove the extra tlb flushing to see the positive impact.

**Comment by gregory38** [comment]
A question how do I move the register :p And also do I need to fiddle with EMMS?
I have their are 2 emitter syntaxes. With and without starting 'x'
I found
```
MOVDMMXtoM
MOVDMtoMMX
```
Versus
```
xMOVD
```

And 
```
SSE_MOVAPS_XMM_to_M128
SSE_MOVAPS_M128_to_XMM
```
vs
```
xMOVDQA
```

**Comment by gregory38** [comment]
Hum just found, xStoreReg and xRestoreReg for SEE :) Remains MMX.

**Comment by refractionpcsx2** [comment]
I don't think you need to fiddle with EMMS, I believe this is auto switched when using FPU instructions so you can get away with using xMOVD (i think this is the generic function to do the ones above it)

**Comment by gregory38** [comment]
I can't access MMX register content because of this code in the iFlushCall.
```
	if (x86FpuState==MMX_STATE) {
		EMMS();
		x86FpuState=FPU_STATE;
	}
```
My move triggers some assertion in soundtouch on floating point value. So I guess I need to use EMMS.

So I put it 2 times ater the loading and the restoring. So it is still booing the game :)

**Comment by refractionpcsx2** [comment]
Yeah that's going to make things painful >.<

What a stupid design intel lol

**Comment by gregory38** [comment]
At least on 64 bits, MMX doesn't exists anymore. I created a branch with the flush to measure the speed impact ```ee-no-flush-ram-access```

**Comment by refractionpcsx2** [comment]
I thought 64bit was half the reason we used MMX in a bunch of places?

**Comment by gregory38** [comment]
For me, we mostly used MMX to emulate the 64 bits operation of the EE (like the branch) + for the extra register + no alignment issue. However if we port the project to x86-64, we won't be able to access them. But we won't need them anyway.

Could you bench a bit the code :). I don't know which game is relevant and I would require a reboot of my computer to switch the GPU driver :( (or I could try to reclock my GPU, but I'm nearly that my driver will hardlock my PC)

**Comment by refractionpcsx2** [comment]
Why are you using a driver that sucks? lol

I can't test it till late tonight, at work now and going to mothers this evening.

**Comment by gregory38** [comment]
I'm on the Mesa free driver. It isn't that bad but it isn't finish. In particular it needs correct code to reclock the GPU from low power to high power mode (potentially it is working with latest git code but I want to keep some stabilities). I use it to generate a couple of patch for Mesa. However it is very nice for gl debugging.

Anyway, I gamed a bit with this extra patch. No crash so far. Actually I think  FLUSH_FREE_TEMPX86 is useless nowadays.  I need to check git history.
```
diff --git a/pcsx2/x86/iCore.h b/pcsx2/x86/iCore.h
index e066927..fcb8056 100644
--- a/pcsx2/x86/iCore.h
+++ b/pcsx2/x86/iCore.h
@@ -355,7 +355,7 @@ extern u16 x86FpuState;
 #define FLUSH_EVERYTHING       0x1ff
 //#define FLUSH_EXCEPTION              0x1ff   // will probably do this totally differently actually
 #define FLUSH_INTERPRETER      0xfff
-#define FLUSH_FULLVTLB FLUSH_NOCONST
+#define FLUSH_FULLVTLB         FLUSH_FREE_TEMPX86 // FLUSH_NOCONST
 
 // no freeing, used when callee won't destroy mmx/xmm regs
 #define FLUSH_NODESTROY (FLUSH_CACHED_REGS|FLUSH_FLUSH_XMM|FLUSH_FLUSH_MMX|FLUSH_FLUSH_ALLX86)
```

**Comment by refractionpcsx2** [comment]
hopefully that'll make a notable improvement over manually moving all xmm's to reg backups

**Comment by gregory38** [comment]
pseudo said that it will be awfully slow quoting him "It's going to slaughter performance". But we have some margins :)

**Comment by refractionpcsx2** [comment]
It might very well do, it depends how games react :P

**Comment by gregory38** [comment]
yeah. Potientially we can can separate memory dispatcher for example
* without context saving
* save SSE
* save MMX
* save both SSE/MMX.
I think we can have the information during the compilation (.inuse = 1). The open question is will be better to use some kind of generic code (add some jump) or uses a flat but duplicated code.

I will try to print a bit the register usage to see if we have room for optimization or not.

**Comment by refractionpcsx2** [comment]
Jumps/branches are expensive, if we can do it as inline code that would be better.  I mean you could do 1 function in the recompiler and just call it during recompilation.  The final code will have duplication but will be "fast code", but the recompiler will be nice and neat

**Comment by gregory38** [comment]
I just did a quick test (on gow) during the flush of TLB. Actually I'm not sure, it will have an impact on the perf. I mean to defer register save/restore.

Note: it is compilation not runtime-execution but here the stat
* 2165 <= memory access requires a XMM/MMX flush
* 109592 <= memory access doesn't use XMM neither MMX.

So if it seems the fastest solution will be 2 handlers with/without context saving. But I'm afraid that it will just increase code complexity for no gain.

**Comment by refractionpcsx2** [comment]
well if it's currently being called for all of them memory access's, technically that bit of code will be 50x faster :P  Not sure what that will translate in to, if anything at all, but every little helps

**Comment by gregory38** [comment]
Ok. New branch is available.
By the way, you can select any commit of the branch with ```git checkout hash_tag```

**Comment by refractionpcsx2** [comment]
OK, i dunno how much that is gonna help what you did if it just checks if anything is dirty then flushes the lot, i haven't checked the code yet, but that will nearly always be true.

**Comment by ramapcsx2** [comment]
I've benched the latest ee flush commit vs master and there's not much difference. In 400+ FPS scenes (basically nothing going on except some idle loops), the new flushing branch is a little slower.

**Comment by gregory38** [comment]
Well I'm not surprised. Most of compiled block 50:1 (GoW, Mana Khemia) don't need the MM flush. That why I separate both code. 

Anyway something we can try is to compact the indirect memory dispatcher. There are currently aligned on 64B. If we align them on 32B, we could fit 2 of them by cache line. (Well I think speed impact will be nearly NULL).
```
diff --git a/pcsx2/x86/ix86-32/recVTLB.cpp b/pcsx2/x86/ix86-32/recVTLB.cpp
index df13f4e..f8ac1f6 100644
--- a/pcsx2/x86/ix86-32/recVTLB.cpp
+++ b/pcsx2/x86/ix86-32/recVTLB.cpp
@@ -256,7 +256,7 @@ static u8* GetIndirectDispatcherPtr( int mode, int operandsize, int sign = 0 )
        // 7*64? 5 widths with two sign extension modes for 8 and 16 bit reads
 
        assert(mode || operandsize >= 2 ? !sign : true);
-       return &m_IndirectDispatchers[(mode*(7*64)) + (sign*5*64) + (operandsize*64)];
+       return &m_IndirectDispatchers[(mode*(7*32)) + (sign*5*32) + (operandsize*32)];
 }
 
 // ------------------------------------------------------------------------
```

**Comment by gregory38** [comment]
Hum, I'm curious if this can be done. A kind of dynamic instrumentation of the block access.
1/ Add a number of execution counter in the block. ```nb_execution```
2/ Add a bool (or a bitmap) that will be true when memory indirect dispatcher was used on the block. ```require_slow_dispatcher```

Then, each VSYNC iterate on the block list
```
if (nb_execution > 100) {
       if (require_slow_dispatcher) {
              recompile the block without the perf instrumentation (i.e. like we have currently)
       } else {
             recompile the block with fast direct memory access
       }
}
```

The idea is that load/store likely always target the same area. Hum we maybe need to separate the ROM/RAM/scratchpad access. But if we manage to know that the load/store target the RAM we can really optimize the access. Basically something like that
```
xAND(ADD, 0xFFF_FFFF)
xMOV(ptr(ADD), DATA)
```
No more lookup table neither X86 register flushes on each load/store.

**Comment by sudonim1** [comment]
Just to summarise some stuff from irc, doing accesses directly on vaddr (but not like that, the actual way is sub; jl; cmp; jge; mov) is an optimisation I planned to do back when I was actually actively coding.  Unlike the xmm flushing nonsense (sorry), it will absolutely be a big gain.

**Comment by ramapcsx2** [comment]
Cheers sudonim1 :)

**Comment by gregory38** [comment]
Ok. I will close the issue. I'm still planning to look at the profiling idea. I'm sure it could worth it. Free time is limed so I will first do some documentations on the recompiler.
