### ISSUE TITLE
[OnePAD] DS3 Face and shoulder buttons not being recognised in newest build

### ISSUE THREAD

**Issue by apemax** [PCSX2/pcsx2#938]
Hello,

I updated the PCSX2 Linux client today and the OnePAD plugin doesn't seem to be recognising the face buttons and shoulder buttons on my PS3 DS3 controller when I try to remap them through the OnePAD config window. Directional buttons, Analogue sticks, start and select buttons are all working fine.

This was working fine in the previous version I was using. (Can't quite remember the exact version now.) DS3 controller working fine in other programs too.

PCSX2 info:

PCSX2 1.3.1-0 - compiled on Oct 22 2015
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Linux 3.19.0-30-generic x86_64
	Physical RAM     =  7935 MB
	CPU name         =  Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  3.197 ghz (2 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 4ddaebbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...

Loading plugins...
	Binding   GS: /usr/lib/games/PCSX2/libGSdx-1.0.0.so 
	Binding  PAD: /usr/lib/games/PCSX2/libonepad-1.1.0.so 
	Binding SPU2: /usr/lib/games/PCSX2/libspu2x-2.0.0.so 
	Binding CDVD: /usr/lib/games/PCSX2/libCDVDnull.so 
	Binding  USB: /usr/lib/games/PCSX2/libUSBnull-0.7.0.so 
	Binding   FW: /usr/lib/games/PCSX2/libFWnull-0.7.0.so 
	Binding DEV9: /usr/lib/games/PCSX2/libdev9null-0.5.0.so 
Plugins loaded successfully.

(GameDB) 9692 games on record (loaded in 227ms)

Thanks. :)

**Comment by gregory38** [comment]
Did you try the ds3 hack option (both state), issue is likely related to sdl2.

**Comment by apemax** [comment]
If you mean the "Hack: Sixaxis/DS3 plugged in USB" option then yes I tried it and it happens when that option is both on and off.

I remember having a similar issue with the Dirt Showdown Linux port, After build 757342 (https://github.com/virtual-programming/dirtshowdown-linux) it didn't recognise some of the butttons (can't remember exactly now.) so I had to add the "—eon_calibrate_gamepads" option when launching the game. Don't know if it is related or not but it seems like a similar issue.

Also I know the DS3 controllers face and shoulder buttons are seen as both a axis and a button on Linux which can cause problems with some games.

**Comment by gregory38** [comment]
Hum could you just try in root? Maybe it is a permission issue.
I need to check the current status with my ds3

**Comment by apemax** [comment]
Just tried it as root (using Sudo) and the face and shoulder buttons still aren't being recognised.

**Comment by sergiobenrocha2** [comment]
uh, is this not related to #414 ?

Also: https://www.reddit.com/r/emulation/comments/3tnb51/controller_glitching_out_on_pcsx2_121/

**Comment by gregory38** [comment]
I confirm the issue. However it is working with SDL1.2 so potentially the issue isn't here.

**Comment by gregory38** [comment]
I created an option in latest build. Please test both value. If you change the option, you will need to restart the emulator.

**Comment by apemax** [comment]
Sorry for taking a while, Finally got round to building it. When I enabled the "Hack: Sixaxis/DS3 pressure" option all the buttons are recognised and start acting like buttons. Seems like your workaround worked.

**Comment by gregory38** [comment]
Great :)
