### ISSUE TITLE
[Core] mVU change in r957 causes artifacting in .hack // G.U. games

### ISSUE THREAD

**Issue by Sarania** [PCSX2/pcsx2#939]
Per this thread: http://forums.pcsx2.net/Thread-Best-hack-G-U-Settings and specifically this post http://forums.pcsx2.net/Thread-Best-hack-G-U-Settings?pid=488743#pid488743 the VU changes in this commit ( https://github.com/PCSX2/pcsx2/commit/9c7d4171e8b206f3a46bc7f4617894fc753b2dda ) caused the .hack //G.U. games to have glitchy shadows and artifacting.

Reasoning:
Bug not present in 956, appears in 963. No buildbot builds between those to test. BUT changing to SuperVU in affected builds DOES fix it. So it has to be a VU problem. 957 is the only VU commit between those two.

![oeszc2m](https://cloud.githubusercontent.com/assets/7574269/10840103/8c201e12-7ea9-11e5-9ed8-fb3ab1c6b872.jpg)

**Comment by refractionpcsx2** [comment]
From the look of @ssakash 's fix, this is only effected if you have the mVU Flag Hack enabled.
