### ISSUE TITLE
Shawn Murray Demo Crashes (Tony Hawk Pro Skater 4)

### ISSUE THREAD

**Issue by JMC47** [PCSX2/pcsx2#94]
PCSX2 Version:  1.3.0 June 18th 2014

PCSX2 Options:  Default, Zero modifications.

Plugin's used:  GDSX 0.1.16, SPU2-X 2.0.0, Lilypad, cdvdGigaherz 0.9.0, rest nulls

Plugins were not modified beyond their default settings.

Description:  Regardless of Software or Hardware, you get odd graphical glitches when trying to load Shawn Murray Demo from the options screen of Tony Hawk Pro Skater 4.  Despite this, it loads for a while before eventually freezing.  I'm guessing the graphical issues and actual freeze are separate.  It freezes at the same loading point every time.

![tonyhawkpcsx2](https://cloud.githubusercontent.com/assets/6598209/3485476/3bd3feee-03e2-11e4-89dc-0bf1e4844ae4.jpg)

Last known working revision:  Couldn't find a version where it loaded.

PC Specifications:  Core i5 3570K @ 3.4 GHz, NVIDIA GTX 760, Radeon HD5850, Windows 7 SP1

I searched the forum and wiki for more information, and found nothing.  When searching the forums I found nothing, but I'll admit I'm not too familiar with the PCSX2 forums.

**Comment by gregory38** [comment]
What is the status of this issue?

**Comment by willkuer** [comment]
I think the general agreement is that demos  of other games dont get an automatic gamefix unless the main game requires the same gamefix. If you want to see the demo you need to enable it manually.

It would be nice to mention this in the compatibility list.

**Comment by JMC47** [comment]
I cannot get in-game whatsoever in the latest development builds.  While loading the main menu, the game hangs about 60% of the way loading.  I tried various CPU rounding modes and was unable to work around this.

**Comment by refractionpcsx2** [comment]
Hmm, can you trace back at all to when it stopped working through the buildbot builds?

**Comment by JMC47** [comment]
I don't have time to do a super in-depth bisect tonight, but, I'll try to get to it asap.  I'm hoping it's just some kind of setting that got changed up.  I tried following the wiki settings, though.  Tomorrow, after work, I'll get on it.

**Comment by willkuer** [comment]
The full emulog after you observed the hang could be useful.

**Comment by refractionpcsx2** [comment]
Does it hang on the THPS4 main menu or the Shawn Murray demo menu? just for clarification?

**Comment by Nobbs66** [comment]
I'll do some testing when I get home tonight.

**Comment by JMC47** [comment]
I got the game booting fine, must have had some stupid speedhack left on from another test (probably Driv3r.)

Shawn Murray seems to be exactly the same as before.  Is there some kind of game fix I need to turn on for that game?

**Comment by willkuer** [comment]
According to ref:
> Enabling the XGKick hack in gamefixes seems to solve the issue mostly

**Comment by atomic83GitHub** [comment]
Any status for that demo?

**Comment by lightningterror** [comment]
@JMC47 is this still an issue ? If so can you tell me your game serial ?

**Comment by kozarovv** [comment]
Demo won't launch due to infinite loop on VU1. When we allow to force end it, demo run.

Related:
https://github.com/PCSX2/pcsx2/issues/2930#issuecomment-640904023
