### ISSUE TITLE
Linux: PCSX2 does not override power management settings

### ISSUE THREAD

**Issue by Shoegzer** [PCSX2/pcsx2#942]
On Mint/Cinnamon 17.2 x64, with system set to turn screen off after 30 minutes, the user needs to "wake" the system up while using PCSX2 for longer than that.  This is because PCSX2 obeys power management settings rather than override them as it should.  As a result the user needs to change the entire system's power management settings before using PCSX2, and revert the settings back when done.  This happens in Mint but is likely to occur on other systems as well.

**Comment by avih** [comment]
On windows there's code to prevent the screen saver from activating. I also added a placeholder where linux code could be added (entry points to disable screen saver and to enable it again), but I'm not familiar enough with the subject to actually put some real code there.

Someone should just put some implementation here https://github.com/PCSX2/pcsx2/blob/master/common/src/Utilities/Linux/LnxMisc.cpp#L58

**Comment by gregory38** [comment]
For reference
http://stackoverflow.com/questions/31498114/how-to-programatically-prevent-linux-computer-from-sleeping-or-turning-on-screen

**Comment by i30817** [comment]
But why would you want to prevent it if you're not using user imput for more than 30 minutes?

**Comment by gregory38** [comment]
Gamepads aren't considered as input (at least it used to, I guess it is still true today).  I think it just need a "keep me alive" X event

**Comment by i30817** [comment]
I see, then the real fix for gamepads (i use a keyboard obviously). I guess if there is a timed keep alive and it can be sent from user input one in a while manually it should while the gamepad drivers don't fix their shit.

**Comment by gregory38** [comment]
I will try to add a call to XResetScreenSaver

**Comment by Shoegzer** [comment]
Thanks, Gregory.  That should fix it.

**Comment by gregory38** [comment]
@Shoegzer 
Could you test this build: https://www.sendspace.com/file/gykydz

Thanks.

**Comment by gregory38** [comment]
New version
https://www.sendspace.com/file/m3okow

**Comment by tsunami2311** [comment]
does this mean after all this time windows blank screen saver wont get triggered when I using gamepad and pcsx2 now???

**Comment by Shoegzer** [comment]
@gregory38 tested and working fine here.  XResetScreenSaver did the trick - no more issues with the screen saver.  Thanks!  :+1: 

By the way, given the infrequent reset rate (once every 4096 Vsync) this wouldn't have any impact on performance right?  I didn't observe any but just curious.

**Comment by gregory38** [comment]
4096 VSYNCs are around 1 minute.  I expect no impact on performance
