### ISSUE TITLE
[Ubuntu] Consider setting up an automatic daily-builds PPA

### ISSUE THREAD

**Issue by helkaluin** [PCSX2/pcsx2#948]
It's very simple, and it'll save all Debian/Ubuntu testers a lot of time and effort in compiling (especially when we're using 64-bit distros and the multiarch dev lib support is just rather flaky).

 Simply get Launchpad to mirror the Github repo, and write a recipe so things get rebuilt everyday (if there are new commits).  You don't have to manually push source packages any more with this.  Automatic builds for all LTS and current stable and development releases.

I've set one up here for your reference: https://code.launchpad.net/~helkaluin/+archive/ubuntu/pcsx2-github-mirror-daily  It builds for Trusty, Vivid, Willy, and Xenial.  It's been compiling daily builds for a week now without problems.

**Comment by gregory38** [comment]
I'm not against it. But how do you do the setup? Could you share a recipe example.

There still an issue. A lots of regression appears, at least with controlled snapshot by me, the unstable version is kinda stable.

**Comment by helkaluin** [comment]
The recipe I'm using is this: https://code.launchpad.net/~helkaluin/+recipe/pcsx2-github-mirror-daily

The package version is currently hacked in, as you're deriving it with a script from SysForwardDefs.h, and Launchpad recipes can only derive things from either the debian/changelog or things like commit hash, time, date, tag, etc.  So the "3:1.3.1" is currently just hardcoded as I'm basically just using the barebones "debian-packager" in the official repo as the foundation of my "debian" folder.

I suppose the regression part is to be expected from an automatic daily build.  It's literally an automatic snapshot after all.

**Comment by helkaluin** [comment]
That said, once you've got your recipes up, you could always write another recipe such that it doesn't automatically build everyday.

With that, releasing a "semi-stable" snapshot or even a stable tag release would be as easy as clicking the "Build now" button (instead of fiddling with source packages and dput and all that).

**Comment by i30817** [comment]
I've been wanting this for a while. My dosbox recipe is like this:
https://code.launchpad.net/~i30817/+recipe/dosbox-daily

launchpad ppas are kinda strange in that all dependencies must be in the same ecosystem and built on the same ecosystem. So if you have outside depencies they must either be in the ubuntu universe repositories, or you put in their source into your repository and build them OR (cleaner) you create another recipe to build a package for them and publish those packages to the same archive as the target of your original build recipe.

As you can see from the example, it's also possible to merge patches at recipe build time from other repositories, but it's involved. Basically the merged directory containing the patch must not exist in the original repository (or merge conflict).

**Comment by gregory38** [comment]
I'm too busy currently, but I will look at it carefully.

**Comment by sergiobenrocha2** [comment]
@helkaluin you know you can make a "PCSX2 team" in launchpad right? So you can add @gregory38 and others to the team and you will not need to rely in only one person to update the packages/recipes. You can be their official packer.

**Comment by helkaluin** [comment]
@sergiobenrocha2 I'll look into that if the PCSX2 devs are into the idea.
@gregory38 Just say if you want me to go ahead with my already building PPA, then I'll create a Laucnhpad Team and add you into it and all that.

**Comment by gregory38** [comment]
Please go ahead. I'm really too busy. Please add @micove too (debian maintainer)

**Comment by helkaluin** [comment]
All done.  Relevant links as follows:
https://launchpad.net/~pcsx2-team
https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily
https://code.launchpad.net/~pcsx2-team/pcsx2-github-mirror/master
https://code.launchpad.net/~pcsx2-team/+recipe/pcsx2-github-mirror-daily

Closing issue.  Please do re-open if you find any problems/objections.

**Comment by helkaluin** [comment]
Sorry about the noise: The "Failed to upload" e-mail that you may or may not have just received is due to having 2 recipes (my old personal one and the new one that is owned by the team) trying to push to the same PPA.  Should clear itself up in a day with a new build.
