### ISSUE TITLE
Copyright/License Issues in the Repository.

### ISSUE THREAD

**Issue by micove** [PCSX2/pcsx2#950]
Currently the project is open source but there are some issues that make the software non-GPL compliant or only distributable by the PCSX2 authors. Usually most linux Distros and most Windows users don't care but Debian is really strict about it (Fedora/Red Hat is too but rpmfusion is kind of lax). What I currently do to go around it is just remove it from the source tarball before uploading it to Debian which ends up removing all this

```
3rdparty
bin/Langs
bin/cheats_ws.zip
common/include/comptr.h
common/src/Utilities/x86/MemcpyFast.cpp
fps2bios
pcsx2/windows/resource.h
pcsx2/windows/wxResources.rc
plugins/CDVDiso
plugins/CDVDisoEFP
plugins/CDVDlinuz
plugins/CDVDolio
plugins/CDVDpeops
plugins/FWnull/Windows/FireWireNull.rc
plugins/FWnull/Windows/resource.h
plugins/GSdx/GSdx.rc
plugins/GSdx/baseclasses
plugins/GSdx/resource.h
plugins/GSnull/Windows/GS.rc
plugins/GSnull/Windows/resource.h
plugins/LilyPad/LilyPad.rc
plugins/LilyPad/resource.h
plugins/PadNull/Windows/PadNull.rc
plugins/PadNull/Windows/resource.h
plugins/PeopsSPU2
plugins/SPU2null/Windows/SPU2null.rc
plugins/SPU2null/Windows/resource.h
plugins/SSSPSXPAD
plugins/USBnull/Windows/USBnull.rc
plugins/USBnull/Windows/resource.h
plugins/USBqemu
plugins/cdvdGigaherz/src/Windows/cdvdGigaherz.rc
plugins/cdvdGigaherz/src/Windows/resource.h
plugins/dev9ghzdrk
plugins/spu2-x/src/Windows/Hyperlinks.cpp
plugins/spu2-x/src/Windows/Hyperlinks.h
plugins/spu2-x/src/Windows/Spu2-X.rc
plugins/spu2-x/src/Windows/resource.h
plugins/xpad
plugins/zerogs
plugins/zerospu2
plugins/zzogl-pg/opengl/Win32/aviUtil.h
plugins/zzogl-pg/opengl/Win32/ps2hw.dat
plugins/zzogl-pg/opengl/Win32/resource.h
plugins/zzogl-pg/opengl/Win32/resrc1.h
plugins/zzogl-pg/opengl/Win32/zerogs.rc
plugins/zzogl-pg/opengl/ZeroGSShaders/zlib
plugins/zzogl-pg/opengl/ps2hw.dat
tools
```

(the resource.h and *.rc files are just removed because they are windows only and others are binaries).

The original package spent around ~6-7 months being reviewed for inclusion to Debian so in theory it should be fairly clean. There are some images here and there but they look like custom made logos and the controller in the about windows looks custom made so I guess you guys made them so hopefully those fall under the GPL-3+ umbrella. What I currently do is assume the current gutted source is safe and just monitor any new files coming in which usually are not that many. 

Anyway, recently a bunch of images got added to OnePad and I do agree it would look better with the new GUI but the images apparently come from a Konami manual. I believe that could cause issues since there is no indication that those images are free to use and distribute. Removing the OnePad plugin is not an option since it's the only Pad plugin on Linux and then it's either redraw the images (which I'm awful at drawing), revert the commit only in Debian (it's technically not legal everywhere) or the package gets removed in 30 days from Debian Testing and soon from Debian if someone finds it and complains.

There could be other issues that I'm not aware of but at least the OnePad issue would be easy to detect since monitoring new files is fairly easy to do.

Related #2493

**Comment by willkuer** [comment]
Do all files within pcsx2 that are not explicitly licensed automatically get the license of the pcsx2 project or does every file need to be licensed explicitly?

I think most images in emu core are selected from design contests in the forum. Not sure how they are licensed and how the contest was written.

**Comment by micove** [comment]
It should be explicit. No license does not guarantee free or distributable. Most of the stuff I remove falls under no license while others falls under Microsoft/Nvidia/AMD/Intel licenses that are not compatible with GPL and I'm not sure why they are there.

**Comment by gregory38** [comment]
Ok most of the stuff are unsupported plugging. And 3rdparty stuff.

I need to add a license header on GLSL file.

I used to have some patches for 
```
plugins/spu2-x/src/Windows/Hyperlinks.cpp
plugins/spu2-x/src/Windows/Hyperlinks.h
```
Which is potentially linked to
```
common/include/comptr.h
```

For `common/src/Utilities/x86/MemcpyFast.cpp` I think the remaining code is from zerofrog.

However you can help me on that `plugins/GSdx/baseclasses`. What is it? Is it useful?

**Comment by micove** [comment]
Yeah, most of the stuff is in deprecated plugins which is why I mentioned moving the 10-11 plugins that are never compiled in windows or linux to a different branch. They would still be in the repo for testing if needed.

I was mainly concerned about the OnePad images. I got used to removing the other files which are mainly windows only. The windows side should at least include a copyright file with the licenses of all the 3rd party stuff in the release tarball since I think some of them require the header to be either reproduced by the application or included with the binaries.

Anyway, I never really looked at the baseclass thing. I just saw it was windows only and had
```
Copyright (c) Microsoft Corporation.  All rights reserved.
```
which made me just delete the whole folder and be done with it. I think refraction commited those files around 0.9.6.

**Comment by turtleli** [comment]
The baseclasses is used for the built in video recording.

**Comment by gregory38** [comment]
Hum, would it be possible to move them in 3rd party?

**Comment by micove** [comment]
Move what? Baseclass, the plugins, the plugins or the images? The problem would still remain since the master branch would remain non-GPL compliant. You can get around it in Linux by removing everything manually like in Debian but other distros don't do it and just pack the master branch as a tarball. Windows need some serious work to get there since they use the files that I remove.The 3rdparty folder is annoying but it's mostly GPL complaint except maybe winpcap which I have never really looked at and currently includes the binary blobs only which makes it at the very least non-DFSG.

**Comment by gregory38** [comment]
Baseclass files. I didn't check the license but potentially there are usable on windows. I did a nice script to help to create a nice tarball ;) I hope that most distribution don't bother with 3rdparty.
Yes I know the situation isn't ideal but trust me it used to be much worst.

There no discussion on the Onepad image, they will be removed (not yet used anyway).

@refractionpcsx2 where did you get those baseclass file?

Here a reduced list of the issue (better for my heart :p ).
```
3rdparty

bin/Langs

bin/cheats_ws.zip
common/include/comptr.h
common/src/Utilities/x86/MemcpyFast.cpp
plugins/spu2-x/src/Windows/Hyperlinks.cpp
plugins/spu2-x/src/Windows/Hyperlinks.h

fps2bios
tools
plugins/GSdx/baseclasses

plugins/zzogl-pg/opengl/Win32/aviUtil.h
plugins/zzogl-pg/opengl/Win32/ps2hw.dat
plugins/zzogl-pg/opengl/Win32/resrc1.h
plugins/zzogl-pg/opengl/ZeroGSShaders/zlib
plugins/zzogl-pg/opengl/ps2hw.dat

plugins/CDVDiso
plugins/CDVDisoEFP
plugins/CDVDlinuz
plugins/CDVDolio
plugins/CDVDpeops
plugins/PeopsSPU2
plugins/SSSPSXPAD
plugins/USBqemu
plugins/dev9ghzdrk
plugins/xpad
plugins/zerogs
plugins/zerospu2
```

**Comment by micove** [comment]
Haha, yeah I just pasted the file I use. I just put them in a file and do
```
while read line; do rm -rf "$line"; done < ${CWD_DIR}/debian/get-orig-source-remove
```

Well, a few years ago we worked a bit on cleaning the source up so I remember that it used to be worse. My main concern with windows is the virus like property of the GPL license. Anything that touches GPL code becomes GPL code and has to abide by the GPL. This causes issues in Debian due to linking since you can't link GPL code with other "virus like" licenses or stuff that is not GPL compatible. Plugins also count as touched by the "virus" heh. I always worry about if the bios counts but I hope not.

Also, I'm not sure those MS/AMD/Intel/Nvidia files can be swallowed up by the GPL which is why I think the windows side has some work to do to clean that up.

**Comment by avih** [comment]
Re `bin/cheats_ws.zip`, it's taken from the forum and combines the contribution of many people (with [Devina](http://forums.pcsx2.net/User-Devina) maintaining it) , and I _think_ that even without explicit permission, the forum owners have the rights to distribute it.

But getting explicit permission, or preferably license would indeed be better.

**Comment by refractionpcsx2** [comment]
@gregory38 I didn't, I think @gabest11 is the person you want to ask :P

**Comment by gregory38** [comment]
I think the files are just a copy/past from a SDK (DirectX?/ Platform?/ MFC? ) Could you check if you have them on your windows install. Maybe it just requires a more complex setup in Visual Studio.

https://www.ptgrey.com/tan/10577

**Comment by refractionpcsx2** [comment]
Yeah i think the baseclasses come separate from the main DirectX SDK, probably why they have been included. Not sure if GSDX's capture still uses it or not.

Edit: Here

> The base class library is provided as a SDK sample in the Microsoft Windows Software Development Kit (SDK)

**Comment by gregory38** [comment]
I suspect it is used to interface with DirectShow. So it is mandatory to copy it in the git? Or is it possible to have it directly from the mentioned SDK?

**Comment by gregory38** [comment]
PR #952 to clean the non-free stuff in spu2x.

**Comment by refractionpcsx2** [comment]
I think it was included so it would be less of a pain in the ass to make PCSX2 compile from fresh for people, without having to scour the web for an SDK which I don't think is even actually supplied by microsoft any more (The page it was on redirects to "get windows 10")

**Comment by gregory38** [comment]
Hum, it would be interesting to know if there is a new way to do it. I guess it will stay longer in the db.

**Comment by micove** [comment]
Oh, the bin/cheats_ws.zip in practice should be safe but technically no explicit license makes it not GPL compliant and hence I can't put it in Debian. Even if the project used something like the BSD-3 license the main issue with no explicit license for a community driven thing is that it's 1 troll or angry user away from not having nice things. If there was a prior established license even if someone tries change the license of their contribution (which is fine) you can always "fork" it before the new license but without a pre-agreed license I think it would be stuck with whatever the user decided.

As, gregory mentioned then. Should the baseclass be moved to the 3rdparty folder then? I'm not sure if it's modified enough to justify staying in the plugins folder.

**Comment by gregory38** [comment]
Maybe create a non_free directory in 3rdparty. Or 3rdparty_non_free.

Any idea on `common/include/comptr.h`. It seems to be used by GSdx and spu2x Xaudio2.

**Comment by micove** [comment]
Looks like a subest of a standard MSVS header
```
// This is a part of the Active Template Library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Active Template Library Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the	
// Active Template Library product.

#ifndef __ATLCOMCLI_H__
#define __ATLCOMCLI_H__
```

Those exacts functions are in atlcomcli.h.

**Comment by gregory38** [comment]
Oh @gabest11 what did you do!

As far as I understand, there are just a kind of smart pointer. Will it be possible to port the code to C++11 smart pointer? Or maybe there are now always included in Visual Studio (I hope)

**Comment by gabest11** [comment]
_com_ptr is horrible, iirc it did not have a default __uuid(T) as the default second template parameter and had other casting issues. CComPtr is much nicer. As note says, at one point I removed all deps to the ATL/MFC libs, this was one of those little things that had to be carried over. And also Microsoft removed some ATL stuff from its own library, don't know if gsdx used any, but I remember missing them in my other projects. (https://msdn.microsoft.com/en-us/library/cc714309(v=vs.90).aspx)

**Comment by gabest11** [comment]
I think DirectShow and most of DirectX 7 is no longer in the SDK, they made those obsolite. Baseclasses was in the "samples" section of the SDK, but everyone had to use it, because no one could directly program DirectShow through the raw interfaces.

**Comment by gregory38** [comment]
Thanks for the info. MS doesn't really help up :( So far I propose to move those stuffs in a separate non-free directory and add a readme to explain the situation (until a better alternative exists)

**Comment by Sarania** [comment]
I wrote Devina about the cheats_ws issue and this is how he replied:
_____________________________________________
Devina wrote:
I'm not quite sure I fully "get it", but the patches are public, open source, free, and their sole purpose is to assist gamers and PCSX2 users.

When people submit a widescreen patch to the forum, they are essentially allowing us to use it. That's the way it's always been. For the community and by the community. Smile No one has objected to it, except the few times people want their name credited in the patch itself.

My forum archive post has: "All of these patches are open source - they can be improved by anyone at anytime. Just post in this thread and I will update the archive." It's been that way for a looooong time. The "they can be improved by anyone at anytime." part essentially means giving us the right to use them as we wish/please, and allowing others to edit/modify/use them.


PCSX2's devs have the right to include them, which is exactly what we want. They do not require a license, I give you and the entire PCSX2 team the right and permission to include them. You can make a special exception for them, I'm sure. 

_________________

However I don't think that "does it." Is there anything we CAN do to make the patches compliant? Or would we need the permission of literally every person who made a patch in the archive, some of which are long gone?

**Comment by micove** [comment]
Mmmm, I'm not really an expert  but I don't think that was enough. Well in general the patches should be 
- Open source
- Free for everyone.
- Distributable with or without modifications by anyone.
- Compatible with the license of the project which is GPL in this case.

I think the 1st one is covered but the others are kind of left to interpretation with some lose understanding that they hold. To be honest for the most part cheats are trivial patches that are not really copyrightable due to their triviality and one-way of doing them. I never really looked at the widescreen patches so I'm not sure how complex or what they even do (besides the obvious of making it wideeeee, heh) so I'm not sure about those. 

To avoid arguing semantics and what is trivial and what is not trivial it would be nice if it was spelled out better for people of what kind of license and their implications. I looked at the thread and those terms where used in page 100:
http://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=271674#pid271674

which is a bit hidden.

Anyway, it looks like the intention was and it was sort of agreed that is was public-domain. So I would add to the 1st post of the thread and to the devina post that information. Something like:

"By submitting patches you agree for the the information contained in them to become part of the public-domain. This implies that it is free for use by anyone for any purpose without restriction under copyright law."

Since there are a bunch of patches already another line should be added:

"If you never agreed to these terms please contact XXX so they can be removed."

A bit draconian but it should more or less work since new work should be fine and if someone does not agree they can ask for removal. A best effort should be given to contact the authors but it's unrealistic to contact them all. I usually see the "contact me if you don't agree" when they can't be found.

**Comment by gregory38** [comment]
Ok cool. I want to add that people are not lawyer so when they post a public forum without copyright, they likely expect that their works are copyright free. So I think the "contact us" is fine.

`fps2bios` is likely free but the authors are long gone.

What are the issue with `tools` ?

**Comment by micove** [comment]
I can't check now but I had this list in the README.source:
```
     + 3rdparty => embedded code (libraries).
     + bin/Langs => Remove the pre-generated language files.
     + common/include/comptr.h => Missing copyright information.
     + common/src/Utilities/x86/MemcpyFast.cpp => AMD copyright/license.
     + fps2bios => Missing copyright information. Possibly non-DFSG-free.
     + plugins/CDVDiso => Missing copyright information.
     + plugins/CDVDisoEFP => Missing copyright information.
     + plugins/CDVDlinuz => Missing copyright information.
     + plugins/CDVDolio => Missing copyright information.
     + plugins/CDVDpeops => Missing copyright information.
     + plugins/GSdx/baseclasses => Microsoft copyright/license.
     + plugins/PeopsSPU2 => Missing copyright information.
     + plugins/SSSPSXPAD => Missing copyright information.
     + plugins/USBqemu => Missing copyright information and not distributable.
     + plugins/dev9ghzdrk => Missing copyright information and Microsoft copyright/license.
     + plugins/spu2-x/src/Windows/Hyperlinks.cpp => codeguru license.
     + plugins/spu2-x/src/Windows/Hyperlinks.h => codeguru license.
     + plugins/xpad => Missing copyright information.
     + plugins/zerogs => Missing copyright information.
     + plugins/zerospu2 => Missing copyright information.
     + plugins/zzogl-pg/opengl/Win32/aviUtil.h => Missing copyright information.
     + plugins/zzogl-pg/opengl/Win32/ps2hw.dat => pre-built shader file.
     + plugins/zzogl-pg/opengl/ZeroGSShaders/zlib => embedded code (library).
     + plugins/zzogl-pg/opengl/ps2hw.dat => pre-built shader file.
     + tools => Missing copyright information.
     + Files autogenerated by Microsoft Visual C++
```

I'm guessing tools has at least 1 file w/o headers

**Comment by Sarania** [comment]
@micove - I contacted Devina again about including that language in the OP(and also making a post at the current position in the thread so currently active contributors who aren't likely to reread the OP will see it). I imagine he will be fine with it, and then I'll make the modifications to the posts.

Meanwhile this is example content of a WS patch. I would THINK it falls into the category of "too trivial to be copyrightable" but I am unsure:

`gametitle=Prince of Persia: Warrior Within (SLUS-21022)`
`comment=Widescreen hack by nemesis2000 (pnach by nemesis2000 )`

`//gameplay`
`patch=1,EE,00544dd4,word,3C023f40`
`patch=1,EE,00544df0,word,4600b046`
`patch=1,EE,00544df8,word,4600a306`
`patch=1,EE,00544dfc,word,4600ab46`

`//rfix`
`patch=1,EE,0052faec,word,3c014455`
`patch=1,EE,0052fb28,word,44810000`

That's the gist of it. They can contain more or less lines but basically the format is:
`patch=1,EE,addressToBeWritten,dataType,value`

**Comment by willkuer** [comment]
I think the comment line is dangerous. If somebody put his name under his work he thought about copyrights. Maybe the poster thought that this is CC-by-sa or something similar - which is probably not compliant to pcsx2. Putting the mentioned lines into the thread is probably mandatory.


But this is a general issue, or? This problem is valid for windows as well. If somebody is looking for trouble this could end bad?

**Comment by Sarania** [comment]
@willkuer it's actually part of the "correct" way to do it - put your name on the comment line. Not all do, but some do. It's just for keeping track.

The patches have always been released under the agreement they are free, so us distributing them is not the issue. It's only GPL compatibility stuff as far as I can tell.

**Comment by turtleli** [comment]
PR #955 should resolve the comptr.h issue.

**Comment by gregory38** [comment]
@avih are you the author of tools/GSDumpGUI ? If yes, could you add a copyright header.

```
tools/GSDumpGUI/Properties/AssemblyInfo.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Properties/Settings.Designer.cs: *No copyright* GENERATED FILE
tools/GSDumpGUI/Properties/Resources.Designer.cs: *No copyright* GENERATED FILE
tools/GSDumpGUI/Library/GSDump/GSData/GSTransfer.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GSData.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFPrim.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFReg.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegNOP.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegUnimpl.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GifImage.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegST.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegFOG.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegRGBAQ.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegAD.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/IGifData.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegXYZF.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegTEX0.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegPrim.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFReg/GIFRegUV.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFPacket/GIFTag.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSData/GIFUtil.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDump/GSDump.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/NativeMethods.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Library/GSDXWrapper.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Forms/frmMain.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Forms/frmMain.Designer.cs: *No copyright* UNKNOWN
tools/GSDumpGUI/Core/Program.cs: *No copyright* UNKNOWN
```

**Comment by gregory38** [comment]
@micove 
I created an unfree directory. So you will need to update your script. The idea is to move the unfree code in this subdirectory. Instead to have them in various place. I moved fps2bios.

**Comment by i30817** [comment]
The greatest problem is IMO cheats_ws.zip, which is much of the reason to use pcsx2 instead of a console. Could we (you) make mandatory to have the hacks gpl'ed when posting them on the forum, and try to get a hold of the authors to sign it off? I know it's stupid, but anything for the linux version not be castrated is fine with me.

**Comment by mirhl** [comment]
Cmon, even assuming somebody didn't want it gpl'ed (which seems completely nonsensical considering pcsx2 *is* gpl) can you really license/copyright.. memory addresses?

**Comment by refractionpcsx2** [comment]
I think the idea of licensing everything is getting a little bit OTT.  Patches are also not something which requires a license as people can steal them all they want, it isn't much use to anybody else and if it is that's great, but it's hardly theft or disrespect for other peoples work.

**Comment by gregory38** [comment]
```
I also find it ironic that a bios reimplementation called 'fps2bios' is not gpl'ed in a gpl project myself.
```
You can't infer the license based on the project or the name. I'm sure the authors wanted a GPL license (which one btw) but they didn't write it anywhere. So no license == unfree. Copyright laws are complex.

**Comment by refractionpcsx2** [comment]
as far as im aware, the fps2bios was being developed by pcsx2 developers before they left to do other things.

**Comment by gregory38** [comment]
```
as far as im aware, the fps2bios was being developed by pcsx2 developers before they left to do other things.
```
Yes I know. But I'm not sure we can copyright them as GPL (trust me it kills me). Anyway I don't think that it is critical. Current implementation is nice but it won't be usable on linux, they only accept source. Windows can provide a prebuilt version. At least on the EE side, we have an alternative. Hum, I'm curious on the IOP side if a trim-down version would be enough to start game.

**Comment by willkuer** [comment]
According to [this document](https://code.google.com/p/pcsx2/source/browse/fps2bios/doc/overview.doc?spec=svn261&r=261) fps2bios should be GPL compliant.

>The goal is to fully document the public interface so that a free (GPL) replacement BIOS can be developed for use in emulators such as PCSX2.

**Comment by gregory38** [comment]
Dunno, if it is enough. @micove what do you think?

**Comment by micove** [comment]
mmmm, if it's about the fps2bios thing then I think it's too vague so I'm not sure if it's enough.

For example, the quoted part is followed by:
```
The information contained in here has been collected from a number of sources but the main sources are the PCSX2 source code which documents the machine hardware and the open source ps2sdk found at ps2dev.org.
```

The ps2sdk is licensed under the AFL-2.0 https://github.com/ps2dev/ps2sdk/blob/master/LICENSE and as stated in http://www.gnu.org/licenses/license-list.html#AcademicFreeLicense it's not compatible with the GPL. I have not looked at it to see if the vague other sources or anything else is incompatible or if the ps2sdk is really used. Even in the best case scenario can't really guess which license to give to it.

It's not really a vital part of PCSX2 so I just remove it.

**Comment by Sarania** [comment]
The OP, Devina's archive post, and the current position in the thread have all been updated with:

By submitting patches you agree for the the information contained in them to become part of the public-domain. This implies that it is free for use by anyone for any purpose without restriction under copyright law. If you never agreed to these terms please contact [url=http://forums.pcsx2.net/User-Devina]Devina[/url] so your patches can be removed.

This should sort the GPL business for them whether they are copyrightable or not.

**Comment by micove** [comment]
Yeah, It should be fine. As mentioned before the patches were not a big issue since I believe they are not copyrightable. They are public-domain even w/o the note but the note makes it clear to avoid confusion. It was more of a pedantic issue and kind of OTT heh.

**Comment by mirhl** [comment]
I read the sources *of information* have been taken from ps2sdk etc., but there's no mention to actual code. 

Also, can the documentation of a GPL project be released under another license, I wonder?

**Comment by EmperorArthur** [comment]
That's a harder question to answer than you'd think, and it all comes down to if the documentation could be considered a derivative work.

In theory, if the code was designed from the docs, then the code is a derivative, but if the docs where made from the code, then it's probably the other way around.

Then you get into the legality of producing docs from black box reverse engineering.  Everyone knows just how much of a mess it would be if those were found to be derivative works.  Sadly, at least in the US, 'Oracle America, Inc. v. Google, Inc.' said APIs can be copyrighted, so even that's probably illegal.

Ironically, we can not accept this logic, because if we do then every emulator and compatibility layer everywhere would be considered infringing.  The good news is that Debian is also forced to ignore the ruling, because large amounts of software, including the Linux kernel, has some sort of compatibility layer.

**Comment by mirhl** [comment]
I guess you are right on the causality/derivability relation. The point should be all in here though. 
> The goal is to fully document the public interface so that a free (GPL) replacement BIOS can be developed for use in emulators such as PCSX2. Where source code examples are given, these refer to the fps2bios source code and not to any original Sony code. The information contained in here has been collected from a number of sources but the main sources are the PCSX2 source code which documents the machine hardware and the open source ps2sdk found at ps2dev.org.

More or less I believe we could sum up everything like this: 
`PCSX2 (GPL)` &nbsp;↘
&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`documentation (?) → BIOS (GPL) `
`ps2sdk (AFL)`↗

If we look at the documentation license state then (and after having tried to understand whatever AFL is not ok because it's just more loose than GPL) shouldn't we just deduce the greatest common divisor (aka GPL) applies?

Speaking of the legality of producing docs from black box reverse engineering instead, I guess the point is all in whatever *declaring code and the [○structure, sequence, and organization](https://en.wikipedia.org/wiki/Structure,_sequence_and_organization)* means. I tried to check the [actual sentence](http://cyber.law.harvard.edu/people/tfisher/cx/2014_Oracle.docx), but 21 pages are frankly too many.

**Comment by mirh** [comment]
So.. hoping not to piss anybody, I think @oobles @bigianb might know something about [fps2bios](http://web.archive.org/web/20041209174200/http://linuzappz.pcsx2.net/fps2bios/) license. 
Also tried to contact florin/[ro]man and linuzappz on sf.

**Comment by refractionpcsx2** [comment]
Good luck contacting florin and linuzappz, both disappeared off the face of the earth years ago

**Comment by refractionpcsx2** [comment]
Linuzappz got a job with Sony anyway so he's contractually not allowed to have anything to do with us again

**Comment by mirh** [comment]
For starters, it wouldn't be bad to figure out who's call is this in the first place. 
Anyway, unless florin deserted facebook too, you should be able to found him there.

**Comment by ramapcsx2** [comment]
Regarding fps2bios, we could always move it out of the main repository. As far as I know, there are no dependencies to it at all. It's a standalone project.

**Comment by turtleli** [comment]
I found copies of the baseclasses files at https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/directshow/baseclasses . There seems to be some minor differences, I haven't really looked into it.

The repo is MIT licensed (https://github.com/Microsoft/Windows-classic-samples/blob/master/LICENSE). So perhaps the baseclasses stuff can be moved from unfree to thirdparty.

**Comment by gregory38** [comment]
Yes we could if it MIT. Otherwise just drop a REAMDE with those informations.

**Comment by lightningterror** [comment]
GSDumpGUI copyrights still haven't been added. I could copy/paste the pcsx2 copyright and tweak it a little if that's fine.

 Aside from that is there anything else left that needs updating ?

**Comment by turtleli** [comment]
> GSDumpGUI copyrights still haven't been added. I could copy/paste the pcsx2 copyright and tweak it a little if that's fine.

No. Original author isn't around, and you can't just put on a copyright and license and assume it's what they intended.

**Comment by mirh** [comment]
Wait a moment.. Why is [fps2bios](https://web.archive.org/web/20040615173341/http://linuzappz.pcsx2.net:80/fps2bios/) license unclear, if its sources were uploaded for the first time onto pcsx2 sf repository?

**Comment by MrCK1** [comment]
Shall we postpone this until 1.8? I assume the only thing remaining is fps2bios?

**Comment by knight-ryu12** [comment]
@gregory38 I've fixed licensing info on ja_JP; FYI.

**Comment by vilhelmgray** [comment]
Would it make sense to start a new effort to implement a free bios to replace fps2bios if the license remains unclear?

**Comment by mirh** [comment]
More than unclear, I would argue the problem is just that it is unstated...
Anyway, there are already: https://github.com/ZirconiumX/biostation

**Comment by RokkumanX** [comment]
Hello!

Is there any update on this? I'm eagerly awaiting the upcoming 1.6 release.

**Comment by bigianb** [comment]
Just chipping in on the fps2bios. For my contributions - licence them however you like, it belongs to the project.
I think fps2bios has bigger problems though and should probably be dropped. Much of the code is sourced from de-compiling the Sony BIOS files and so that leaves the code with a questionable licence.

**Comment by mirh** [comment]
Can be closed I guess?

**Comment by lightningterror** [comment]
Not sure, there are some leftover things like language licences.

**Comment by arcum42** [comment]
If language was the main thing left on this issue, all the wx locale files are now gone...

**Comment by Oymat** [comment]
> Not sure, there are some leftover things like language copyright.

can be closed now ?
