### ISSUE TITLE
[VU0] Street Fighter EX3 - Broken cloth physics

### ISSUE THREAD

**Issue by rz5** [PCSX2/pcsx2#954]
**_PCSX2 versions used:**_
Pcsx2 0.9.6
Pcsx2 Beta 976
pcsx2-v1.3.1-1378-g8ab9cea-windows-x86

**_Emulation settings:**_ "Safest" preset, no hacks.

**_Plugins used:**_ 
GSdx-AVX2 
GSdx-SSE2 version 1.15
GSdx-SSE2 version 1.14
ZeroGS 97.1

**_Plugin settings:**_ CRC Hack Level "None"
#### Hardware Specifications

**_CPU:**_ 
AMD Athlon II 64 X4 @ 3.20GHz
Intel® Core™ i5-4690K @ 3.50GHz

**_GPU:**_ 
GeForce 9600GT
GeForce GTX 970 (Driver: NVIDIA 358.50)
#### Description

The dynamic cloth physics of the game are broken. Cloth items that are supposed to flow and instead
they are static and messed up.

This bug is not affected by EE/VU clamp/round mode, superVU and microVU are the same.
HW and SW renderers don't influence it either.
None of the gamefixes affect the bug.

Setting VU0 to "Interpreter" changes the bug slightly (the hakama isn't a disc anymore, but
it is still static and slanted to the left).
Due to this, I prefixed this issue with [VU0].
#### Screenshots

Character on the left incorrectly has the shirt bunched up and the neck scarf to the left.
Character on the right is supposed to be wearing some hakama pants; instead they appear as flat static discs attached to the character's waist.
![image:1](http://forums.pcsx2.net/attachment.php?aid=17335)

Another screenshot of the character with bugged hakama pants.
![image:1](http://forums.pcsx2.net/attachment.php?aid=17336)

**Comment by refractionpcsx2** [comment]
This is a long standing bug, I don't think it's ever been solved, not sure why lol

**Comment by gregory38** [comment]
Fixed with the above PR.
