### ISSUE TITLE
DEV9ghzdrk causes crash if previous adapter was removed

### ISSUE THREAD

**Issue by Volkanite** [PCSX2/pcsx2#959]
-PCSX2 version: [8ed56bd] (https://github.com/PCSX2/pcsx2/tree/8ed56bd971e7048527d615fda289b2a211d50048)
-OS: Win7 64-bit

-How to replicate: Open the plugin configuration and set and save a network adapter. After, physically remove the network adapter from the system(mine was a USB wireless adapter but an "Uninstall" in Device Manager might do the trick). Start PCSX2 emulation then close it.

-Other comments: Crash happens at DEV9ghzdrk/pcap_io.cpp, line 329, calling pcap_close() with a null pointer. Caused by pcap_open_live() (line 112) failing resulting in symbol 'adhandle' initialized with a NULL handle. Crash actually happens in wpcap.dll but we can at least implement a simple fix until/or if ever fixed in Winpcap.

**Comment by refractionpcsx2** [comment]
Sounds like we need to check the configured device exists on startup, then default it to not enabled if it doesn't. From the sounds of it, winpcap is still initialising when it shouldn't be.

**Comment by bositman** [comment]
Pinging @TheLastRar who has become our resident DEV9ghzdrk guru :P

**Comment by TheLastRar** [comment]
I'll take a look at this when I get time.

I suspect this issue (of which I never looked into in great detail) is may also be related https://github.com/PCSX2/pcsx2/issues/93

**Comment by TheLastRar** [comment]
DEV9ghzdrk already checks if pcap_open_live has failed, putting up a message box when it detects failure (which happened in #93, and also happened when I disabled my adapter), however it doesn't do much else with this information and fails to null check the handle pcap_close().

@refractionpcsx2 emulation of a removed Ethernet device seems to not work, the NAD I was testing with would get stuck loading for eternity when Ethernet was configured to disabled.

Should we instead indicate failure (return non-zero) in DEV9open? which would stop emulation as a result.

**Comment by refractionpcsx2** [comment]
We should probably attempt to emulate ethernet as well as Dev9null does if it is disabled.

**Comment by TheLastRar** [comment]
Dev9null plugin returns 0 always (effective a missing adapter?).

I could have this plugin do that when both HDD (default disabled) and Ethernet is disabled.
This would cause issues if someone decides to enable HDD (if the plugin ever gets support) but disables Ethernet.

I'm also not sure how a real ps2 would behave in an equivalent setup (has HDD, but is has no Ethernet cable plugged in?)
