### ISSUE TITLE
[Feature Request]: The ability to pause the emotion engine at a specific offset for specific amount of time

### ISSUE THREAD

**Issue by Farran666** [PCSX2/pcsx2#9614]
### Description

Just as the title says. But I'm oblivious as to whether or not the jit is able to handle it at its current state.

### Reason

It could potentially be used to help performance issues, and dare I say, turn games such as Marvel Nemesis into a playable state

### Examples

-

**Comment by refractionpcsx2** [comment]
It won't make Marvel Nemesis playable.

How are you proposing this will help? and how do you propose we do it?

**Comment by Farran666** [comment]
> It won't make Marvel Nemesis playable.
> 
> How are you proposing this will help? and how do you propose we do it?

Similarly to how PCSX2 handles patches. We select an offset and set an allocated interval of second or ms where the EE just pauses everytime the PC register hits that offset

**Comment by refractionpcsx2** [comment]
I'm not sure how that would help anything. The entire system, we already have speedhacks to slow down the EE by using the EE Cycle Rate, and it's much less intrusive than your suggestion.

Anyway, this sounds like a very niche (and sorry, but I'm not sure you quite know what impacts that would have or how difficult it would be to implement, just for a hack), so I'm going to say no to this.

Thanks for trying though.

**Comment by Farran666** [comment]
No hard feelings. You never know till you try
