### ISSUE TITLE
[BUG]: PCSX2 does not start on Ubuntu 22.04

### ISSUE THREAD

**Issue by Robyx456** [PCSX2/pcsx2#9618]
### Describe the Bug

I have installed PCSX2 from flatpack in the Ubuntu Software app. It now seems installed but does not start. I do not see any error message.

### Reproduction Steps

I have installed PCSX2 from flatpack in the Ubuntu Software app. It now seems installed but does not start.

### PCSX2 Revision

the last

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04

**Comment by stenzek** [comment]
I don't know what "Ubuntu Software" does, or whether this is even our package.

Installing from flathub with `flatpak install net.pcsx2.PCSX2` works fine here on Ubuntu 22.04. As would downloading the flatpak from pcsx2.net. Therefore not a bug, please use the Discord server for support.
