### ISSUE TITLE
[BUG]: PCSX2 main application exe file deletes itself after opening

### ISSUE THREAD

**Issue by TXLCyonixYT** [PCSX2/pcsx2#9620]
### Describe the Bug

The bug is that the main application file for nightly pcsx2 will delete itself after roughly 5-7 seconds of being open, and then the exe is nowhere to be found. The updater and all other related files are intact. 

It will also refuse to extract the main exe after said deletion when attempting to reinstall.

### Reproduction Steps

1. Download PCSX2 nightly build v1.7.4796
2. Extract file with 7z
3. The main application will either be missing or will crash after being open for 5-7 seconds.
4. After the crash, the main application will be gone.

### Expected Behavior

Expect for the exe to be deleted as well as the application to crash. May also cause a lag spike.

### PCSX2 Revision

v1.7.4796

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
This is a support issue, not a bug. Likely some anti-malware software flagging PCSX2 as a false positive.
