### ISSUE TITLE
[Feature Request]: Stick deadzones/threshold with macros

### ISSUE THREAD

**Issue by pintti** [PCSX2/pcsx2#9621]
### Description

Unlike regular controls which allow for deadzones for both buttons and analog sticks, macros completely ignore any possible deadzone setting. While this is obviously ideal for a keyboard, any macros that have their inputs mapped to an analog stick will activate at the slightest input.

So currently if I map Cross to SDL-0/-RightY (right analog stick down), the macro will constantly trigger. If macros would use the controller deadzone or have a set threshold this would not happen.

### Reason

Using macros with sticks would allow using the stick as a replacement for buttons. But if the controller is old and has any loose inputs the macros are unusable. 

### Examples

Retroarch allows controller macros and uses thresholds with them. 

![retroarch_button_press_threshhold](https://github.com/PCSX2/pcsx2/assets/55876906/51930b04-e73b-4cbc-a70e-bc2151b7221e)

**Comment by stenzek** [comment]
> So currently if I map Cross to SDL-0/-RightY (right analog stick down), the macro will constantly trigger.

Why are you using a macro for this? Just bind X to the stick, and you can set a deadzone by shift-clicking the binding.

I guess we could add a deadzone to the macro trigger, but it's not needed in this use case.

> Retroarch allows controller macros and uses thresholds with them.

Terrible UX. What if you want different deadzones for different buttons?
I'd appreciate you not posting stuff from that abusive group on our issue tracker, thanks.

**Comment by pintti** [comment]
> Why are you using a macro for this? Just bind X to the stick, and you can set a deadzone by shift-clicking the binding.

Currently I have done exactly that. However, by using macros I could use both the stick and buttons in games that do not usually support the stick. As an example, in Armored Core 2 the sticks are not supported. Obviously the left stick can be used in analogue mode, but the right stick does nothing. If I can bind the face buttons to right stick as macros, I can use the stick in missions, while still using buttons in the menus. It's for pure conveniences sake.

> I'd appreciate you not posting stuff from that abusive group on our issue tracker, thanks.

I know, but the issue requested examples and I provided them.

**Comment by pintti** [comment]
Accidentally clicked close, sorry.

**Comment by stenzek** [comment]
> If I can bind the face buttons to right stick as macros, I can use the stick in missions, while still using buttons in the menus. It's for pure conveniences sake.

You know you can bind multiple triggers to a single controller button, right? Same shift-click popup that you use to adjust deadzone. The button activation would always exceed the deadzone, so that won't be a problem.

**Comment by pintti** [comment]
> You know you can bind multiple triggers to a single controller button, right? 

I did not. I will close this issue now, to stop looking any more foolish. Thanks and sorry.

**Comment by stenzek** [comment]
I added it in #9623 anyway, because combining sticks with buttons can be a bit screwy if the device reports noisy analog values when there's no real stick movement.

**Comment by pintti** [comment]
Thank you!
