### ISSUE TITLE
[BUG]: PCSX2 Crashes after Quitting when Running Emulation

### ISSUE THREAD

**Issue by DanielBielak** [PCSX2/pcsx2#9627]
### Describe the Bug

PCSX2 crashes after quitting the application when running emulation.

### Reproduction Steps

Run Gran Turismo 4 with PCSX2
Quit PCSX2 by pressing Command+Q

### Expected Behavior

PCSX2 should close / quit without crashing.

### PCSX2 Revision

v1.7.4799

### Operating System

macOS 10.14 (Mojave)

### Logs & Dumps

[Dump.txt.zip](https://github.com/PCSX2/pcsx2/files/12166490/Dump.txt.zip)

**Comment by stenzek** [comment]
This was most likely fixed by #9625.
