### ISSUE TITLE
[BUG]: Corrupted text/icons in Online Settings (Burnout 3)

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9635]
### Describe the Bug

Some or all the text is missing in Vulkan when entering Online Mode on the Main Menu in Burnout 3. Icons show a black box instead of the corresponding PS2 button icon. When switching back & forth between Software/Hardware, the image glitches as you move up and down.

GSdump provided below:

### Reproduction Steps

Press Start, Go into 'Online Mode'

### Expected Behavior

As Software Mode.

### PCSX2 Revision

1.7.4809

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Default Settings.

### Emulation Settings

Native Settings.

### GS Window Screenshots

Hardware (Vulkan):
![Burnout 3 - Takedown Vulkan 2](https://github.com/PCSX2/pcsx2/assets/116039192/3e47a27e-c0d8-4952-9866-096c793538ab)
![Burnout 3 - Takedown Vulkan 9](https://github.com/PCSX2/pcsx2/assets/116039192/f8b296c2-fb4d-4df9-8591-8c641724f842)
![Burnout 3 - Takedown Vulkan 11](https://github.com/PCSX2/pcsx2/assets/116039192/85bb5f75-f649-4905-9c6e-410f524928ea)
![Burnout 3 - Takedown Vulkan](https://github.com/PCSX2/pcsx2/assets/116039192/56d90093-acf5-4035-b507-f6e4c6b2cc33)

Software:
![Burnout 3 - Takedown Software (2)](https://github.com/PCSX2/pcsx2/assets/116039192/8d669eff-2c1a-497f-a00f-5bf00631213c)
![Burnout 3 - Takedown Software 3](https://github.com/PCSX2/pcsx2/assets/116039192/01d4b080-b155-474b-b49c-c0e9f8f466a8)
![Burnout 3 - Takedown Software](https://github.com/PCSX2/pcsx2/assets/116039192/8bbe11ac-2f10-4459-8df3-647abd6e4540)

### Logs & Dumps

[Burnout 3 - Takedown Online.zip](https://github.com/PCSX2/pcsx2/files/12175764/Burnout.3.-.Takedown.Online.zip)

**Comment by refractionpcsx2** [comment]
Looks like it's a bad interaction with the CRC hack.

**Comment by refractionpcsx2** [comment]
can you try #9636 when it builds please.

**Comment by refractionpcsx2** [comment]
awesome, can you also check the game is ok :D

**Comment by refractionpcsx2** [comment]
perfect, thanks for testing!
