### ISSUE TITLE
[PAL] Ratchet and Clank 2 Going Commando crashes after clearing Jammer Array level

### ISSUE THREAD

**Issue by Hirato** [PCSX2/pcsx2#964]
It dumps this into the console when run without any speed hacks.

```
EE: Unrecognized MMI op 700000a5
EE: Unrecognized op 1108401
EE: Unrecognized op 3e83001
EE: Unrecognized op 1efd0bd
EE: Unrecognized op 1f63001
EE: Unrecognized op 1f4e8bd
EE: Unrecognized op 1eeb0bd
EE: Unrecognized op 1eeb0bd
EE: Unrecognized op 1eda9bd
EE: Unrecognized op 1108401
EE: Unrecognized op 3e83001
EE: Unrecognized op 1efd0bd
EE: Unrecognized op 1f63001
EE: Unrecognized op 1f4e8bd
EE: Unrecognized op 1eeb0bd
EE: Unrecognized op 1eeb0bd
EE: Unrecognized op 1eda9bd
EE: Unrecognized op 1108401
EE: Unrecognized op 3e83001
EE: Unrecognized op 1efd0bd
EE: Unrecognized COP0 op 41800000
EE: Unrecognized op 1e0c61e
EE: Unrecognized op 1fa3001
EE: Unrecognized op 1f4e8bd
EE: Unrecognized op 1f63801
```

I've also seen it throw this exception during several of the runs
    /home/hirato/sources/pcsx2-git/src/pcsx2/pcsx2/FiFo.cpp(47) : assertion failed:
        Function:  void ReadFIFO_VIF1(mem128_t*)
        Thread:    EE Core
        Condition: vif1Regs.stat.FQC != 0
        Message:   FQC = 0 on VIF FIFO READ!

```
Stacktrace:
[00] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[01] wxMDIParentFrameBase::TryBefore(wxEvent&)   
[02] 0x0x9fce112                                 
[03] 0x0x9f4b05f                                 
[04] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[05] wxString wxString::Format<char const*>(wxFormatString const&, char const*)
[06] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[07] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[08] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[09] 0x0xf64aa315                                
[10] clone                                       
```

the build script I'm using it outputting pcsx2-git-1.3.1.r2301.ac0e40a for the current build I'm using.

EDIT

https://gist.github.com/Hirato/86d846d6f6a362f6358a The console log is here.

It's not reliable though, sometimes it has the TLB miss section, sometimes not.
Sometimes the unrecognised opcodes are two instances of '1'
Sometimes it crashes and at other times it just leaves you with a black screen from which you can reboot or restore an earlier save state. 

What happens is that after clearing the Jamming Array level, a cutscene begins to play; The screen is black, the GS is seemingly doing nothing and the errors then pop up in the console.

No combinations of EE settings I've tried sidesteps the issue, ditto for any combination of speedhacks. I haven't messed around much with the plugin settings, but it also happens in software mode.

plugins are GSdx-OGL, onepad, and spu2x, rest are null drivers.

the ISO is one I ripped myself using the `dd` tool which plays fine on actual PS2 hardware, so I do not think the iso itself is broken.

**Comment by willkuer** [comment]
Please adjust your post to follow [this guideline](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues)

Please also show the full emulog and not only a small part of it.

**Comment by Hirato** [comment]
is that better @willkuer ?

**Comment by gregory38** [comment]
Did you test older version? Could you test to rip  your iso with k3b?

Which come first the assertion or the "Unrecognized op" ? Stacktrace is useless, I think it doesn't show the correct thread or something like that. @turtleli , I know that you love wx stuff ;) (note it used to work on the past).

@refractionpcsx2 any idea on the assertion.

**Comment by Hirato** [comment]
@gregory38 
As I've said, it's unreliable. It breaks at the same point, but what it prints out isn't constant.

On the runs the assertion was triggered, I believe it was after the error was through.
Most of the time it leaves me with a black screen that's seemingly hung, which as i've also stated, I can reboot from or restore a savestate.

Both dd and k3b generate an image with the md5sum `e184fc2a495a4654f748a8e8c587261c`, which matches the image I'm using in PCSX2.

The oldest revision I've tried thus far is described as pcsx2-git-1.3.1.r2117.31ee576 and it has the same exact output.

**Comment by willkuer** [comment]
Please dont use savestates until the problem is solved. Savestates can save bugs and reloading them will always reproduce the bugs independent on your settings.

Pleasr save to a memcard, shit pcsx2 down, restart, load from the memcard and try to reproduce the issue. If you can please post the full emulog after you the crash.

**Comment by Hirato** [comment]
It's a savestate I made by playing right to the problem point with no speedhacks from a game loaded via the memcard.
But here you go: https://gist.github.com/Hirato/11744c4b380694a61a13

**Comment by turtleli** [comment]
Does a dialog appear when the assertion happens? Something like:
![woosh](https://cloud.githubusercontent.com/assets/10976277/11071179/402439e4-87d7-11e5-8ea8-bc85a544607f.png)

**Comment by refractionpcsx2** [comment]
I have no idea, that message doesn't exist in my project.

**Comment by willkuer** [comment]
The second emulog is without savestate.

I dont know how trustworthy foldermemorycard is. I think we have another issue with an unexpected assertion hit where foldermemorycard is involved.

Can you please check if possible whether reverting to file memory card solves the issue?

**Comment by Hirato** [comment]
@turtleli On the rare occasion that did pop up, yes.

@refractionpcsx2 I used a savestate so that I didn't have to play the exact same 10 minute segment over and over :P

@willkuer https://gist.github.com/Hirato/74224c5adc3b555b7a3d
Doesn't seem to have made any difference, though I've got the other opcodes this time, which have also shown up with folder memcard.

**Comment by willkuer** [comment]
Thanks. Just didnt want to miss something.

Btw if you want to continue playing you could try to use the skip mpeg hack. Maybe you can upload your memcard save so that our bug squad team can easily reproduce the issue and check/test solutions.

**Comment by Hirato** [comment]
I didn't think to give manual game hacks a try, the EE timing hack sidestepped the issue and the post scenes played out as it should've; issue cropped up again as soon as I disabled that hack, even during the scenes.

This memcard has the ratchet and clank related saves I have, you should be able to just open it with 7z.
https://dl.dropboxusercontent.com/u/23891252/R%26Cbackup.ps2.xz

**Comment by willkuer** [comment]
So EE timing hack is a valid solution to your problem?
If it would be added to the gamedb as automatic gamefix everything would work nicely for you?

**Comment by gregory38** [comment]
Hum it would be nice to reproduce the issue on windows.

**Comment by Hirato** [comment]
@willkuer possibly, I've finished a few more planets without the need for that hack, so I don't know if it's an ideal solution; interim or otherwise.

I'll update the ticket if I find any other points that need it.

**Comment by willkuer** [comment]
[I asked for cross validation in the forum](http://forums.pcsx2.net/Thread-Possible-Bug-in-R-C2-pal)

**Comment by Ryudo300** [comment]
I can confirm it happens on Windows as well. Using PCSX2 GIT 1.3.1-1422. The audio of the cutscene played, but the screen remained black. You're forced to restart the game after the cutscene ends.

<code>(EE pc:002DE0E8) TLB Miss, addr=0x420b230 [store]
(EE pc:002DE0E8) TLB Miss, addr=0x4217320 [store]
(EE pc:002DE438) TLB Miss, addr=0x420b240 [store]
(EE pc:002DE71C) TLB Miss, addr=0x420b248 [load]
(EE pc:002DE71C) TLB Miss, addr=0x420b248 [store]
(EE pc:002DE724) TLB Miss, addr=0x420b250 [load]
(EE pc:002DE724) TLB Miss, addr=0x420b250 [store]
(EE pc:002DE72C) TLB Miss, addr=0x420b258 [load]
(EE pc:002DE72C) TLB Miss, addr=0x420b258 [store]
(EE pc:002DE734) TLB Miss, addr=0x420b258 [load]
(EE pc:002DE734) TLB Miss, addr=0x420b258 [store]
(EE pc:002DE73C) TLB Miss, addr=0x420b260 [load]
(EE pc:002DE73C) TLB Miss, addr=0x420b260 [store]
(EE pc:002DE744) TLB Miss, addr=0x420b258 [load]
(EE pc:002DE744) TLB Miss, addr=0x420b258 [store]
(EE pc:002DE744) TLB Miss, addr=0x42031a0 [store]
(EE pc:002DE71C) TLB Miss, addr=0x420b260 [load]
(EE pc:002DE71C) TLB Miss, addr=0x420b260 [store]
(EE pc:002DE724) TLB Miss, addr=0x420b268 [load]
(EE pc:002DE724) TLB Miss, addr=0x420b268 [store]
(EE pc:002DE72C) TLB Miss, addr=0x420b270 [load]
(EE pc:002DE72C) TLB Miss, addr=0x420b270 [store]
(EE pc:002DE734) TLB Miss, addr=0x420b270 [load]
(EE pc:002DE734) TLB Miss, addr=0x420b270 [store]
(EE pc:002DE73C) TLB Miss, addr=0x420b278 [load]
(EE pc:002DE73C) TLB Miss, addr=0x420b278 [store]
(EE pc:002DE744) TLB Miss, addr=0x420b270 [load]
(EE pc:002DE744) TLB Miss, addr=0x420b270 [store]
(EE pc:002DE744) TLB Miss, addr=0x42031b0 [store]
(EE pc:002DE71C) TLB Miss, addr=0x420b278 [load]
(EE pc:002DE71C) TLB Miss, addr=0x420b278 [store]
(EE pc:002DE724) TLB Miss, addr=0x420b280 [load]
(EE pc:002DE724) TLB Miss, addr=0x420b280 [store]
(EE pc:002DE72C) TLB Miss, addr=0x420b288 [load]
(EE pc:002DE72C) TLB Miss, addr=0x420b288 [store]
(EE pc:002DE734) TLB Miss, addr=0x420b288 [load]
(EE pc:002DE734) TLB Miss, addr=0x420b288 [store]
(EE pc:002DE73C) TLB Miss, addr=0x420b290 [load]
(EE pc:002DE73C) TLB Miss, addr=0x420b290 [store]
(EE pc:002DE744) TLB Miss, addr=0x420b288 [load]
(EE pc:002DE744) TLB Miss, addr=0x420b288 [store]
(EE pc:002DE744) TLB Miss, addr=0x42031c0 [store]
(EE pc:002DE71C) TLB Miss, addr=0x420b290 [load]
(EE pc:002DE71C) TLB Miss, addr=0x420b290 [store]
(EE pc:002DE724) TLB Miss, addr=0x420b298 [load]
(EE pc:002DE724) TLB Miss, addr=0x420b298 [store]
(EE pc:002DE72C) TLB Miss, addr=0x420b2a0 [load]
(EE pc:002DE72C) TLB Miss, addr=0x420b2a0 [store]
(EE pc:002DE734) TLB Miss, addr=0x420b2a0 [load]
(EE pc:002DE734) TLB Miss, addr=0x420b2a0 [store]
</code>

Will try the level again, this time with EE Timing to see if it fixes it.

**Comment by Ryudo300** [comment]
It works fine with the EE Timing Hack. Cutscene plays correctly, game progresses.

**Comment by Hirato** [comment]
I just finished the game, and I didn't encounter any other areas that required the EE Timing Hack.

**Comment by Nobbs66** [comment]
Does this also happen in the NTSC version of the game by chance?

**Comment by Nobbs66** [comment]
Ok, so it's localized to the pal version. I'll try to test that in the next few days

**Comment by Sarania** [comment]
That label. "Timing | Voodoo" I love it XD

To make my post actually add something I'll ping @Nobbs66 so he will remember to test XD

**Comment by Nobbs66** [comment]
Oh, thanks! Forgot to test. I'll test it sometime tonight while my phone is doing stuff.

**Comment by Nobbs66** [comment]
Well, it get's stuck in a loop. [Disassmbly with GPR view](http://anony.ws/i/2016/02/07/DisassemblywithGPR.png)

[Disassembly with VF registers](http://anony.ws/i/2016/02/07/disassemblywithVF.png)

[Savestates(slot 0 is right before the bug LARGE)](https://www.dropbox.com/s/ibx5m978sv8u9d9/R%26C2LLstates.7z?dl=0)

**Comment by Nobbs66** [comment]
any update on this? :/

**Comment by refractionpcsx2** [comment]
Don't think so.

**Comment by MrCK1** [comment]
I can't access the forums/wiki right now (can't remember if I posted something about this there) but I didn't encounter any crashes last time I tested my NTSC copy.

**Comment by FlatOutPS2** [comment]
Try a few PCSX2 versions between 1.4.0 and now to see if you can pinpoint when the cutsene stopped crashing.

**Comment by atomic83GitHub** [comment]
Why this issue was closed? The timing issue is still here.

**Comment by MrCK1** [comment]
The EE Timing Hack does the same thing as -3 EE cyclerate; but it can be automatically applied.

**Comment by atomic83GitHub** [comment]
Thanks for the info. Yes, it was added in the database with the same PR as Max Payne.
And for finish, the EETimingHack don't cause any major slowdown so it's a great deal :).

**Comment by majewsky** [comment]
This bug has reappeared for me. For reference, I'm currently running a release build of 49e316e488 with emulation settings at Preset 3.

It appears that the bug was reintroduced in commit 2b6905307d6681e8c7c92e97c882b55195367b8f which removed the EE Timing Hack from the game's GameDB entry. Turning on the EE Timing Hack manually allowed me to clear the Jammer Array without encountering the crash at the end.

**Comment by atomic83GitHub** [comment]
Unfortunately, this is a evil bug which can't be solve right now. The game does require the timing hack in that level but that also introduce massive slowdowns related to FMVs.
The best that can be done is to enable it only in that level, then turing it off.
Also, it appear that a another section will require the timing hack mich later in the game, when Ratchet grab the new wrench in the Aranos prison level.

**Comment by majewsky** [comment]
I see. Thanks for reopening, that should make it easier for others to find this issue and thus the workaround. I only found it myself because I vaguely remembered encountering this bug years ago.

**Comment by DanixPC** [comment]
**Solution:** Go to Config > Emulation Settings > Game Fixes > Enable manual game fixes > enable 'EE timing hack'.

**Comment by refractionpcsx2** [comment]
Game will no longer suffer slowdown when enabling the EE timing hack.
