### ISSUE TITLE
[BUG]: [MacOS 13] Gran Turismo 4 losing W-A-S-D input outside of racing

### ISSUE THREAD

**Issue by shaifulborhan** [PCSX2/pcsx2#9645]
### Describe the Bug

If you paused during racing or after the racing has finished, the W-A-S-D directional keys are not responding anymore in the menus. Other keys are still working normally.

### Reproduction Steps

I am using a 16" M1 Pro MacBook Pro. Tested using internal and external Bluetooth keyboards.

1. Enter the game and start a single race or a driving license event.

2. Pause in the middle of a race. The W-A-S-D keys stopped working in the menu but still works when you continue the race.

3. Finish the race. The W-A-S-D keys stopped working in the menu.

### Expected Behavior

The W-A-S-D directional keys to work as normal everywhere.

### PCSX2 Revision

1.7.4816

### Operating System

macOS 13 (Ventura)

### CPU

M1 Pro

### GPU

M1 Pro

**Comment by Mrlinkwii** [comment]
Can this be checked on lastest nightly?

**Comment by DigitalMajestic** [comment]
Can't reproduce on 1.7.4911, Ventura 13.4.1, Intel. I ran an arcade mode race and was able to back out and go into Gran Turismo mode and navigate there just fine. I haven't checked 1.7.4816.

**Comment by shaifulborhan** [comment]
I have tested on v1.7.4913, still seeing the same problem. So this might be an isolated case. I will further check by turning off background apps in my laptop and if anything I will report back in here in a couple of days. Thanks!

**Comment by shaifulborhan** [comment]
This issue was fixed after rebooting my Macbook 😄.  There might have been some minor side effects from not rebooting the laptop for months

**Comment by DTsapin** [comment]
I have same issue, so that's impossible to pass the license tests and restart races :(

**Comment by Mrlinkwii** [comment]
@DTsapin  if you need help can you please join teh discord or forum

**Comment by DTsapin** [comment]
> @Mrlinkwii Okay, it will be nice! What's a link for discord/forum?

**Comment by Mrlinkwii** [comment]
https://discord.com/invite/TCz3t9k

**Comment by shaifulborhan** [comment]
@DTsapin Try to use the arrow keys instead of W-A-S-D in the menus after the license tests or races.
