### ISSUE TITLE
[BUG]: Random Crash while playing

### ISSUE THREAD

**Issue by navaronbracke** [PCSX2/pcsx2#9646]
### Describe the Bug

I was playing normally when suddenly the emulator crashed during a loading sequence.

The level that I was about to play was about to load in, but instead of loading in the emulator gave a black screen for a bit and crashed.

### Reproduction Steps

I don't have clear repro steps but I was doing the following:

1) Start BF2:MC (SLES-53729)
2) Enter single player campaign
3) Play mission "End Game (China)" once
4) After the mission hit "Replay" instead of "Continue"
5) The intro of the mission starts
6) When the audio of the intro ends, the level should load in, but in my case the screen went black until the emulator crashed

### Expected Behavior

Don't crash?

### PCSX2 Revision

v 1.7.4816

### Operating System

Windows 10 (64bit)

### Logs & Dumps

Logs
[crash-2023-07-27-21-38-43-335.txt](https://github.com/PCSX2/pcsx2/files/12187654/crash-2023-07-27-21-38-43-335.txt)

Dumpfile
[crash-2023-07-27-21-38-43-336.zip](https://github.com/PCSX2/pcsx2/files/12187702/crash-2023-07-27-21-38-43-336.zip)

At the very end of the logs I see

```
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF7DE89A01B)
00007FF7DE89A01B (pcsx2-qt): (filename not available): bumpAllocator
```

**Comment by navaronbracke** [comment]
Done

**Comment by navaronbracke** [comment]
@refractionpcsx2 let me know if you need anything else. Unfortunately I don't know what the allocator does :/

**Comment by refractionpcsx2** [comment]
is there any chance you could provide a savestate from just before the crash point? The dump doesn't really tell us much except it looks like the EE JIT exploded, but it wasn't overly helpful, a savestate would be good! Thanks

**Comment by navaronbracke** [comment]
Sadly I do not have a savestate from just before the crash, I usually save to the memory card, and my last savestate is 10 days old. Not sure if that's sufficient?

I could try to repro it again, but not sure if it reproduces consistently.

**Comment by navaronbracke** [comment]
I cannot repro the original situation anymore and emulator runs fine. Not sure what happened?

**Comment by refractionpcsx2** [comment]
Must have just been a random crash, like a perfect storm of things happening... I guess if you can't repro we'll leave it here for now, but if you can find a way to reproduce it, let us know and we'll reopen this.

Thanks for reporting.
