### ISSUE TITLE
[BUG]: Final Fantasy X (SLPS-25050) Controller keeps vibrating

### ISSUE THREAD

**Issue by insea190** [PCSX2/pcsx2#9659]
### Describe the Bug

My controller keeps vibrating when I launch Final Fantasy X.

### Reproduction Steps

Launch Final Fantasy X with a vibration-enabled controller.

### PCSX2 Revision

v1.7.4831

### Operating System

Windows 10 (64bit)

### CPU

Ryzen5 3400G

### GPU

Radeon Vega 11 Graphics

**Comment by MageKing17** [comment]
Which version of FFX and what controller?

**Comment by insea190** [comment]
The version is the first edition and the controller is a GameSir T4 Kaleid.

**Comment by MageKing17** [comment]
> The version is the first edition

That's not what I meant; I meant like the serial number. I have SLUS-20312 and didn't get so much as a twitch from my DualShock 4 when I launched it.

**Comment by insea190** [comment]
SLPS-25050.
