### ISSUE TITLE
[BUG]: game slows downs at specific level in Gran Turismo 4 (SCPS-17001)

### ISSUE THREAD

**Issue by Wudbirt** [PCSX2/pcsx2#9663]
### Describe the Bug

the game speed slows down to 3fps, then show this error and crash 
![Screenshot_22](https://github.com/PCSX2/pcsx2/assets/88958110/41ffa7ac-5ef3-4655-9f83-360342735ed4)
this only happen in this specific level i tried others and starts without problem

### Reproduction Steps

1- go to second option
![Screenshot_23](https://github.com/PCSX2/pcsx2/assets/88958110/b04f1f6a-92b3-44a8-afb2-46696df2b474)
2- go to license center
![Screenshot_24](https://github.com/PCSX2/pcsx2/assets/88958110/183a4d50-691c-4505-966a-ac80b104a815)
3- go to the blue cone

4- and open level 5
![Screenshot_25](https://github.com/PCSX2/pcsx2/assets/88958110/d2508bcd-f782-4d06-9f98-6c513472e696)

the game don't let access to that part without completed the other levels so here is a save state if it help 
[SCPS-17001 (AEAD1CA3).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/12206159/SCPS-17001.AEAD1CA3.01.p2s.zip)

### Expected Behavior

i expected it show a menu to start the race and other options, just like other levels of license center

### PCSX2 Revision

v1.7.4831

### Operating System

Windows 11

### CPU

Athlon 300U

### GPU

Radeon Vega 3

### GS Settings

all default except renderer (Direct3D 12) and Aspect Ratio (Widescreen)

### Emulation Settings

![Screenshot_26](https://github.com/PCSX2/pcsx2/assets/88958110/7f1e95e4-e806-4445-86fa-9744de1b3004)

### Logs & Dumps

[crash log.zip](https://github.com/PCSX2/pcsx2/files/12206158/crash.log.zip)

**Comment by refractionpcsx2** [comment]
I suggest you read the wiki, license crashes are well documented, you need to set your clamping appropriately

**Comment by RedDevilus** [comment]
To iterate:

Gran Turismo 4 - How to Use EE Clamping:
Gran Turismo 4 makes extensive, non-standard use of floating point math on the PS2. You will need to switch the EE Clamping setting depending on what part of the game you are playing.

License tests and driving missions:
The game will crash if the incorrect clamping mode is used. To avoid issues, make sure to set EE Clamping to Normal. As a side effect, there may be issues with the race timer, and the "GET READY TO DRIVE" text may not disappear on certain events.

All other events:
The timer will not run and the "GET READY TO DRIVE" text will not disappear if the incorrect clamping mode is used. To avoid issues, make sure to set EE Clamping to Full. As a side effect, some license tests and driving missions will now crash the game.

How do I set EE Clamping?
- Tools > Show Advanced Settings
- Read the warning prompt to continue
- Right click Gran Turismo 4 in your games list, then hit Properties
- Go to the Advanced tab
- Locate the EE Clamping field and change as needed
