### ISSUE TITLE
[BUG]: Can't change game 'cover image' 1.7.4837

### ISSUE THREAD

**Issue by Crazyrzy** [PCSX2/pcsx2#9672]
### Describe the Bug

So basically, I put a cover image for the wrong game, and I can't change it to the correct one. 

### Reproduction Steps

Right click game
Press 'Set Cover Image...'
Choose 'Picture A'
Right click the same game
Press 'Set Cover Image...'
Choose 'Picture B'
A popup should open saying "A cover image for this game already exists, do you wish to replace it?"
Press 'Yes'
Nothing happens.

### Expected Behavior

I get the correct picture as a cover set.

### PCSX2 Revision

1.7.4837

### Operating System

Windows 10 (64bit)

EDIT: Deleting the wrong cover from the 'covers' folder then should solve the issue.

**Comment by RedDevilus** [comment]
In it's current form ,once you set a cover image, you can't replace it until you remove the cover from the cover folder. So yeah that is an issue.

**Comment by MBeeBR** [comment]
a  button "delete current cover" might help
