### ISSUE TITLE
 [BUG]: Ratchet & Clank: Up Your Arsenal and Deadlocked has seizure inducing artifacts when using Direct 11, 12 and Open GL.

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#9684]
### Describe the Bug

Ratchet & Clank: Up Your Arsenal and Deadlocked have seizure inducing artifacts when using Direct 11, 12 and Open Gl. Software and Vulkan don't have the issue.
 

### Reproduction Steps

Use Software or Vulkan

### Expected Behavior

Playing without seizure inducing artifacts.

### PCSX2 Revision

v1.7.4847

### Operating System

Windows 11

### CPU

AMD Ryzen 7  3700X  8-Core Processor 

### GPU

Nividia GTX 1070 TI

**Comment by Mrlinkwii** [comment]
Can I have a gs dump?

**Comment by RedDevilus** [comment]
What serials are affected?

**Comment by AkihitoZero5454** [comment]
> What serials are affected? (which will be revealed in gsdump itself)

![image_2023-07-30_200521939](https://github.com/PCSX2/pcsx2/assets/85499008/c342d6bf-721c-420c-9154-0fbef81ddaca)

**Comment by RedDevilus** [comment]
That isn't a gsdump,...

How To Create A GS Dump
What is a GS dump?
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

Where do I make the dump?
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

How do I make the dump?
Use the key combination Shift + F8

`On Qt builds of PCSX2, you can also use Tools > Save Single Frame GS Dump`

Where does the GS dump save to?
GS dumps are saved to the /snaps folder.
- If you used the PCSX2 installer, you will find it in Documents/PCSX2.
- If you are using a nightly build, you will find /snaps in the same folder as the PCSX2 executable.

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by AkihitoZero5454** [comment]
![Ratchet   Clank 3_SCPS-15084_20230730201406](https://github.com/PCSX2/pcsx2/assets/85499008/d49a4e00-d751-43d0-878d-d8a93a698ad2)
Made a GS Dump

**Comment by AkihitoZero5454** [comment]
[Uploading Ratchet & Clank 3_SCPS-15084_20230730201406.zip…]()

**Comment by RedDevilus** [comment]
You didn't give it enough time to upload, please retry.

**Comment by AkihitoZero5454** [comment]
[Ratchet.Clank.3_SCPS-15084_20230730201406.zip](https://github.com/PCSX2/pcsx2/files/12210451/Ratchet.Clank.3_SCPS-15084_20230730201406.zip)

**Comment by RedDevilus** [comment]
[Ratchet.Clank.3_SCPS-15084_20230730201406.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12210443/Ratchet.Clank.3_SCPS-15084_20230730201406.gs.zst.zip)

Okay kept the extensions in order, but it did succeed now.


Vulkan:
![image](https://github.com/PCSX2/pcsx2/assets/24227051/f03b86ce-7447-4741-9e22-8400f7d5a143)

D3D11:
![image](https://github.com/PCSX2/pcsx2/assets/24227051/b9ae8e2a-492b-45b8-99c9-d9929699b7b3)

D3D12:
![image](https://github.com/PCSX2/pcsx2/assets/24227051/6f02e7c4-9225-4f26-887b-ddfe4b783e46)

OpenGL

Logs:

![image](https://github.com/PCSX2/pcsx2/assets/24227051/4a9d705e-0b48-4705-b9d0-4f7344f29af1)
![image](https://github.com/PCSX2/pcsx2/assets/24227051/74bb4116-2f20-4d68-871d-a63e7ab29107)
![image](https://github.com/PCSX2/pcsx2/assets/24227051/1c2cf0ab-4be8-4a9c-95d7-9e788e553e8b)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/40759386-45b8-44a1-b0f0-5f61dace7675)
works here on opengl

**Comment by Jakey757** [comment]
The dump is completely fine for me in all renderers.
![image](https://github.com/PCSX2/pcsx2/assets/49990481/893e6a00-fa89-44f5-b2f1-ee6fb0be10cd)
The logs Red posted mention bad cache files. @AkihitoZero5454 Try deleting the bin files in `PCSX2/cache` and run the games again. Or alternatively just do a fresh install of PCSX2 somewhere else if you dont feel comfortable with that.

**Comment by lightningterror** [comment]
Broken here as well, dx11 and gl for me only.

**Comment by AkihitoZero5454** [comment]
> The dump is completely fine for me in all renderers. ![image](https://user-images.githubusercontent.com/49990481/257084308-893e6a00-fa89-44f5-b2f1-ee6fb0be10cd.png) The logs Red posted mention bad cache files. @AkihitoZero5454 Try deleting the bin and idx files in `PCSX2/cache` and run the games again. Alternatively just do a fresh install of PCSX2 somewhere else if you dont feel comfortable with that.

It wasn't a bad cache. It keeps having the issue still
