### ISSUE TITLE
[BUG]: Go Go Golf (SLPS-20037 NTSC-J), several textures are dark in HW renderer.

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#9687]
### Describe the Bug

Several texture are dark in HW renderer.
![Magical Sports - Go Go Golf_SLPS-20037_20230731171542](https://github.com/PCSX2/pcsx2/assets/121824800/bf31e2ea-7302-4ebb-b866-253c93a7c323)

SW renderer:
![Magical Sports - Go Go Golf_SLPS-20037_20230731171540](https://github.com/PCSX2/pcsx2/assets/121824800/d9bc2814-f5c1-4961-9982-a3775949fc6e)

### Reproduction Steps

boot the game and start any cources.

### Expected Behavior

from (https://www.youtube.com/watch?v=1B-wURL673A&t=106s)
![asassasasasa](https://github.com/PCSX2/pcsx2/assets/121824800/1468b222-fad7-414e-98fb-9b89abce00c7)

### PCSX2 Revision

Nightly - v1.7.4849

### Operating System

Windows 10 (64bit)

### CPU

Core i5-8500

### GPU

GeForce GTX 1050 Ti

### Logs & Dumps

[MSGGG_texture_dump.zip](https://github.com/PCSX2/pcsx2/files/12213463/MSGGG_texture_dump.zip)

**Comment by stenzek** [comment]
Try mipmapping.

**Comment by stenzek** [comment]
For documentation's sake:

Grass draw is here:
![image](https://github.com/PCSX2/pcsx2/assets/11288319/8a9dd51e-f03b-4b98-8f55-da9ffd9897dc)

Ad contains whether it's shadowed or not, but 128 is 1.0 in GS terms, but 0.5 in HW terms.

**Comment by SeruranBlue** [comment]
I rerun my GS dump, but still glitched (?) (1.7.4852)
![image](https://github.com/PCSX2/pcsx2/assets/121824800/711dfaf6-d3a0-4b44-8c80-ba5b75b42949)

**Comment by Mrlinkwii** [comment]
@SeruranBlue  what was added was the prompt 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/ce610204-40f7-4023-b1fd-a24ce66d2dcc)

**Comment by SeruranBlue** [comment]
oops, it works now.
