### ISSUE TITLE
[BUG]: Berserk: Millennium Falcon Hen Seima Senki no Shō has the same artifact problem as Up Your Arsenal and Deadlocked (Which the 2 mentioned games got fix though Berserk still has this problem) and keeps switching to software mode

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#9689]
### Describe the Bug

Berserk: Millennium Falcon Hen Seima Senki no Shō has the same problem the other two games faced yesterday though before it happened to them. The game will also switch constantly Hardware modes (Direct 11, Direct 12, Open GL, Vulkan) to software modes if the hardware modes are set by default.

[Berserk - Millennium Falcon-hen - Seima Senki no Shou_SLPM-65688_20230731115121.gs.zip](https://github.com/PCSX2/pcsx2/files/12216856/Berserk.-.Millennium.Falcon-hen.-.Seima.Senki.no.Shou_SLPM-65688_20230731115121.gs.zip)

### Reproduction Steps

Use Software mode by default 

### Expected Behavior

No artifacts and should do fine on Hardware modes

### PCSX2 Revision

v1.7.4853

### Operating System

Windows 10

### CPU

Ryzen 7 3700X 8-Core processor

### GPU

Nividia GTX 1070 TI

**Comment by AkihitoZero5454** [comment]
![Berserk - Millennium Falcon-hen - Seima Senki no Shou_SLPM-65688_20230731115121](https://github.com/PCSX2/pcsx2/assets/85499008/ca230b04-a6e7-4d0f-a4aa-9ad197cd1ce7)

**Comment by Mrlinkwii** [comment]
re: the hw changing to SW , the game has SoftwareRendererFMVHack  so that intended

**Comment by AkihitoZero5454** [comment]
> re: the hw changing to SW , the game has SoftwareRendererFMVHack so that intended

Oh okay

**Comment by refractionpcsx2** [comment]
are you sure this is not fixed on the newest version? A fix was submitted for this kind of thing 7 hours ago.

**Comment by AkihitoZero5454** [comment]
> are you sure this is not fixed on the newest version? A fix was submitted for this kind of thing 7 hours ago.

Not for this game. It had this issue before Ratchet & Clank: Up your Arsenal and Deadlocked suffered from (though the 2 Ratchet & Clank games do not suffer from automatic render switching)
