### ISSUE TITLE
[BUG]: SLUS-21596 Burnout Dominator: Slow-Mo, Extreme handling, changed FOV..

### ISSUE THREAD

**Issue by mrtawsiti3** [PCSX2/pcsx2#9691]
### Describe the Bug

Made issue only if you want to check it cuz i used widescreen patch and i believe the issue might be cause of it.
( when i disabled patch in game options it was still like this )

Slow-Motion Traffic, changed FOV, can't see where i'm driving when using nitro, extreme fast handling left and right, car also drive in slow motion.
Happened once first time i played Spiritual Towers Burning Lap event somewhere at the beginning of the game and upon restarting pcsx2 it was all good.

![Burnout Dominator_SLUS-21596_20230731192647](https://github.com/PCSX2/pcsx2/assets/35630219/16fa6490-a6ea-4331-92a0-cbe85cb7920b)

![Burnout Dominator_SLUS-21596_20230731192704](https://github.com/PCSX2/pcsx2/assets/35630219/1d8b785f-da97-432d-bebc-c07d0e39af3e)

### Reproduction Steps

Play Spiritual Towers Burning Lap event and game sometimes starts in wrong and weird ''mode''

### Expected Behavior

Racing is like in every other level

### PCSX2 Revision

1.7.4854

### Operating System

Windows 10 (64bit)

### CPU

AMX Ryzen 7 7700x

### GPU

RTX 4070 TI

### GS Settings

Widescreen patch
8x native
Vulkan
x16 anisotropic
High blending

### Logs & Dumps

[Nitro.zip](https://github.com/PCSX2/pcsx2/files/12217823/Nitro.zip)
[FOV.zip](https://github.com/PCSX2/pcsx2/files/12217825/FOV.zip)

**Comment by RedPanda4552** [comment]
Issues caused by patches are not accepted. Disabling patches without doing a fresh, savestate-less boot of the game does not have any effect.

If the issue still occurs with patches disabled on a fresh boot without using savestates, then this is still valid.
