### ISSUE TITLE
[Feature Request]: Adjustable Achievement Notification Duration

### ISSUE THREAD

**Issue by TwosomesUP** [PCSX2/pcsx2#9692]
### Description

As of right now we are able to turn notifications on or off, but it would be great to be able to adjust the amount of time the notification is on screen. Currently the amount of time the notification is on screen seems to be a tad too long and can interfere with the on screen action. Being able to reduce that would be amazing!

### Reason

The on screen achievement notifications can be intrusive if left on screen for too long and being able to reduce that amount of time could resolve that, especially for those who would like to keep the notifications on.

### Examples

A slider in the global settings under the achievements menu could be a great place to store this setting. The current value seems to be about 15 seconds, but a default of around 2 or 3 seconds would be sufficient. The slider could then have a range between 1 and 5 seconds (or longer if needed).

If you need any other information just let me know!

**Comment by TwosomesUP** [comment]
Unless someone else has already taken it, or would like to, I might try my hand at this enhancement.

**Comment by Mrlinkwii** [comment]
This is now fixed

**Comment by stenzek** [comment]
Added in https://github.com/PCSX2/pcsx2/pull/9722
