### ISSUE TITLE
Major League Baseball 2K6 hangs on splashscreen, crashes when you attempt to stop PCSX2

### ISSUE THREAD

**Issue by JMC47** [PCSX2/pcsx2#97]
PCSX2 Version: 1.3.0 June 18th 2014

PCSX2 Options: Default, Zero modifications.

Plugin's used: GDSX 0.1.16, SPU2-X 2.0.0, Lilypad, cdvdGigaherz 0.9.0, rest nulls

Plugins were not modified beyond their default settings.

Description:  Start up the game, it loads the initial splashscreen.  After that the game completely hangs, while the numbers at the top of the PCSX2 window keep moving.  Closing PCSX2 results in a crash.

Last known working revision:  Unable to find a working revision.  I'm setting up a way to test multiple versions quickly, but the fact builds aren't stored in easy to find places + not updated on the site makes that difficult.  I did not find a version that loaded the game in my attempts.

PC Specifications: Core i5 3570K @ 3.4 GHz, NVIDIA GTX 760, Radeon HD5850, Windows 7 SP1

I searched the forum and wiki for more information, and found nothing. The game wasn't even on the Wiki at all from what I could tell.  I also have limited experience with changing settings, so I didn't try a bunch of specialized settings or hacks.

**Comment by bositman** [comment]
First off, this game is -not- MLB 2006, that one has a different ELF file and a whole different game: 
http://wiki.pcsx2.net/index.php/MLB_2006

Now THIS is the actual game: Major League Baseball 2K6 http://wiki.pcsx2.net/index.php/Major_League_Baseball_2K6 Which matches the ELF noted above.

Tested even with VU and EE interpreters, the game hangs after the first splash screen still.
Last log entries:
Unknown device 'hdd'
Known devices are  pfs:(PFS)  mc:(Memory Card)  cdrom:(CD-ROM )  rom:(ROM/Flash)  tty:(CONSOLE) 
Unknown device 'hdd'
Unknown device 'hdd'
	[VC IRX module][ VCMain ] IOP system memory Free:0x97c00(621568) , MaxBlock:0x96f00(618240)
Unknown device 'hdd'
	[VC IRX module][ VCMain ] IOP system memory Free:0x96f00(618240) , MaxBlock:0x96f00(618240)
Unknown device 'hdd'
	[VC IRX module][ VCMain ] IOP system memory Free:0x97c00(621568) , MaxBlock:0x96f00(618240)
padman: *** VBLANK OVERLAP ***
padman: *** VBLANK OVERLAP ***

**Comment by JMC47** [comment]
oh wow, I feel stupid.  The game actually was in the PS2 when I bought it so I didn't really pay much attention to it.  Sorry for the mistake.

**Comment by karasuhebi** [comment]
Just a stab in the dark here: @bositman Do you think the 4GB patch would help here? Or do games that need that usually crash further into the game?

**Comment by bositman** [comment]
What would the 4gb patch do? The game only shows a splash screen, nothing taking up huge amounts of memory.

**Comment by karasuhebi** [comment]
I don't know, I just figured I'd ask you about it just in case it had the chance to fix something.

**Comment by lightningterror** [comment]
I gave this a go and the game is playable on the latest dev build.
1.4 also works.

**Comment by MrCK1** [comment]
@lightningterror please update the compatibility report.

**Comment by lightningterror** [comment]
Oh it seems I forgot that I had gamefixes enabled. Looks like @prafullpcsx2 made a patch for the game so that's why it doesn't crash.

```
Serial = SLUS-21235
Name   = MLB 2k6
Region = NTSC-U
Compat = 5
[patches = 88BB9A5C]
	//Patched by Prafull
	//Avoid hang at start
	patch=0,EE,003c4280,word,00000000
[/patches]
```

**Comment by FlatOutPS2** [comment]
So it still crashes without the patch?

**Comment by lightningterror** [comment]
Yes it does.
