### ISSUE TITLE
Visual Studio 2015 Express build broken

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#970]
Community edition is unaffected.  I think this was fixed for buildbot recently (VS2013).
<code>
1>------ Build started: Project: GSdx, Configuration: Release AVX Win32 ------
2>------ Build started: Project: SPU2-X, Configuration: Release Win32 ------
1>  stdafx.cpp
2>  DplIIdecoder.cpp
2>  SndOut_XAudio2.cpp
2>SndOut_XAudio2.cpp(24): fatal error C1083: Cannot open include file: 'atlcomcli.h': No such file or directory
2>  SndOut_Portaudio.cpp
1>c:\software\development\projects\pcsx2\plugins\gsdx\stdafx.h(45): fatal error C1083: Cannot open include file: 'atlcomcli.h': No such file or directory
2>  AboutBox.cpp
2>  PS2E-spu2.cpp
========== Build: 0 succeeded, 2 failed, 26 up-to-date, 0 skipped ==========
</code>

**Comment by gregory38** [comment]
Get community edition. Express isn't supported anymore.

**Comment by deadair3210** [comment]
It looks more like some of the build files are missing, not that the compilier is at fault. 
fatal error C1083: Cannot open include file: 'atlcomcli.h': No such file or directory

**Comment by refractionpcsx2** [comment]
Yeah express doesn't come with the ATL and MFC libraries, but Community does and it is also free, so just upgrade to that.

**Comment by willkuer** [comment]
Or just google visual studio express atl and use one of the provided solutions. It seems like one can just install atl afterwards.

**Comment by deadair3210** [comment]
Was unaware that Express did not come with atl libs.Good to know.

**Comment by stephenmcgruer** [comment]
FYI I updated the wiki (http://wiki.pcsx2.net/index.php/PCSX2_Documentation/Compiling_on_Windows) to reflect this issue, as it still recommends using Visual Express 2015 - I assume that's no longer a good idea and people should default to Visual Community 2015.
