### ISSUE TITLE
[BUG]: Armored Core 2 - Another Age: HUD gets glitched by closing pause menu on HW

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#9715]
### Describe the Bug

In Armored Core 2 - Anothre Age, HUD gets glitched every time closing in-game pause menu on HW renderer.
- It occurs on every HW renderer.
- It doesn't occur on SW renderer.
- Once it occurs, glitched HUD remains even on SW.
- I've tested only SLPS-25040 (NTSC-J). I don't have other region versions, so I'm not sure if it occurs on them.

### Reproduction Steps

1. Boot the game (Armored Core 2 - Anothre Age)
2. Start new game
3. Go in Garage
4. Start "AC TEST"
5. Press Select button to open pause menu
6. Press Select button to close pause menu, and then HUD gets glitched

### Expected Behavior

HUD shouldn't get glitched by closing pause menu even on Hardware renderer.

### PCSX2 Revision

v1.7.4869

### Operating System

Windows 11

### CPU

i5-8250U

### GPU

NVIDIA Geforce MX150

### GS Settings

Tested all renderers. All settings besides renderer are default.

### Emulation Settings

Changed nothing.

### GS Window Screenshots
(on Vulkan renderer)

<details><summary>Non-glitched HUD (before opening pause menu)</summary>

![Armored Core 2 - Another Age_SLPS-25040_20230804202533](https://github.com/PCSX2/pcsx2/assets/91955473/deac595e-85d5-4375-8987-f279c41abcf8)</details>
<details><summary>Pause menu</summary>

![Armored Core 2 - Another Age_SLPS-25040_20230804202554](https://github.com/PCSX2/pcsx2/assets/91955473/a233f905-fd80-44f9-999d-bb88240eb3f8)</details>
<details><summary>Glitched HUD (after closing pause menu)</summary>

![Armored Core 2 - Another Age_SLPS-25040_20230804202613](https://github.com/PCSX2/pcsx2/assets/91955473/815df546-72e7-4c38-8dfd-e21d5fef9669)</details>

### Logs & Dumps

[GS_dumps.zip](https://github.com/PCSX2/pcsx2/files/12260226/GS_dumps.zip)
Above three screenshots were generated at saving this three GS dumps.

**Comment by stenzek** [comment]
Smells like readbacks trashing local memory. Does disabling hardware readbacks change the behaviour at all?

**Comment by Berylskid** [comment]
Tested with set hw download mode to disabling hw readback, but it still occurs.

**Comment by Berylskid** [comment]
Just a report: Tested Armored Core 2 (SLPS-25007, NTSC-J) right now, and same glitch occured.

**Comment by Berylskid** [comment]
Found a thing actually affects this glitch.
- After getting glitched, changing "Texture Inside RT" to/from whatever fixes glitch instantly.
- Glitch always occurs regardless Tex in RT.

**Comment by vladimirputin11** [comment]
experienced this exact same issue with utmost consistency in the NTSC-U version of armored core 2

**Comment by forrvalhalla** [comment]
I went and did some bisecting for this issue, the glitched HUD after pausing seems to be caused by #9251 , v1.7.4756 PCSX2.
![Armored_Core_2_SLUS-20014_20231027174343](https://github.com/PCSX2/pcsx2/assets/53349573/b3a737b8-8aaa-4c2e-8de8-b1b259efc3fe)
