### ISSUE TITLE
[BUG]: When using hotkeys on controller to Quick Save, the buttons remain "pressed" after loading.

### ISSUE THREAD

**Issue by jonasos3** [PCSX2/pcsx2#9716]
### Describe the Bug

If using a hotkey/combination to Quick Save (I use R3+R1), R1 will remain pressed after loading that Quick Save. This didn't always happen, the issue started a few weeks ago. Currently on latest nightly, still happening.

### Reproduction Steps

Easy way to test, MGS2. Use hotkey R3+R1 to save. When loading the Quick Save, the view will be stuck in first person mode (as if holding down R1) until R1 is pressed again.

### PCSX2 Revision

v.1.7.4868

### Operating System

Windows 11

**Comment by stenzek** [comment]
> This didn't always happen, the issue started a few weeks ago. 

Please bisect to the exact build where it started, otherwise such information isn't really helpful.

**Comment by refractionpcsx2** [comment]
@RedPanda4552  might wanna check it out then :)
