### ISSUE TITLE
[Feature Request]: Add next scan in memory search.

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#9720]
### Description

On the memory search panel, we can search for values, but we cannot perform a next scan yet. This is a request to add it similarly to how Duckstation did.

### Reason

A memory search without a next scan feature is completely useless.

### Examples

Duckstation

**Comment by Buzzardsoul** [comment]
Before someone says "Just use Cheatengine." Why would I when PCSX2 searches way faster?

**Comment by Risae** [comment]
+1

**Comment by Meerkov** [comment]
+1 This makes it very difficult to do most common tasks. For example:

1. Search all addresses for my current HP value.
2. Take 5 damage.
3. Filter the current list of addresses to only the ones that are now == (HP-5).

It's currently *possible* but very tedious to manually check each address in (1) for the change.

**Comment by Daniel-McCarthy** [comment]
Just as a heads up, I am working on this feature and will have a pull request up for review on it within a few days.

**Comment by Mrlinkwii** [comment]
implemented in #10260
