### ISSUE TITLE
[BUG]: Klonoa 2: Lunatea's Veil pal

### ISSUE THREAD

**Issue by microbit16** [PCSX2/pcsx2#9727]
### Describe the Bug

the character is a bug out they have square  black I can see their face 

### Reproduction Steps

just the character has square black

### Expected Behavior

nothing behavior

### PCSX2 Revision

v1.7.4873

### Operating System

macOS 11 (Big Sur)

### CPU

Intel HD Graphics 5000

### GPU

1.3 GHz Dual-Core Intel Core i5

**Comment by stenzek** [comment]
Create and post a GS dump. This may be unique to your hardware, since it's a reasonably old GPU.

**Comment by stenzek** [comment]
Please retest this on latest master (after https://github.com/PCSX2/pcsx2/commit/147a6c81a18416b3fabe9b5ba30246acffa2aacb).

Game runs and renders fine for me now on M2 Pro.

**Comment by DigitalMajestic** [comment]
Tested 1.7.4857 and was able to reproduce the issue.

Tested 1.7.5033 and it's fixed (with both Radeon Pro 5300M and Intel UHD 630).
