### ISSUE TITLE
[BUG]: Intel HD 4600 HD4600 Direct3d 12 DirectX 12 crash at game launch

### ISSUE THREAD

**Issue by Git-beta** [PCSX2/pcsx2#9728]
### Describe the Bug

Used duplication in the title so it'll be easier to search.

As you might know, Intel disabled DX12 on older iGPUs due to security concerns. I tried to use a few still-DX12 supported drivers including the custom made PHDGD Skylake driver (it supports Haswell) but all crashed at game launch.

Granted, the HW only supports DX12 at D11.1 level but Duckstation, Xenia and Dolphin work fine, just PCSX2 crashes. 

Win 11 22H2
Multiple pre-DX12 removal drivers including the latest supported .5063 driver
PCSX2 1.7 4873 nightly
[hd4600dump.zip](https://github.com/PCSX2/pcsx2/files/12268800/hd4600dump.zip)
Error log dump added.

### Reproduction Steps

Explained

### PCSX2 Revision

1.7.4873

### Operating System

Windows 11

### CPU

4790

### GPU

hd4600

**Comment by stenzek** [comment]
Sorry, drivers are broken, can't do anything about it. Couldn't even find a workaround, since I don't have anything that old to debug on.

Intel's DX12 driver has other issues with PCSX2, even on my Arc GPU. OpenGL is broken on pre-Xe.

Your only option is DX11.

**Comment by Git-beta** [comment]
> Sorry, drivers are broken, can't do anything about it. Couldn't even find a workaround, since I don't have anything that old to debug on.
> 
> Intel's DX12 driver has other issues with PCSX2, even on my Arc GPU. OpenGL is broken on pre-Xe.
> 
> Your only option is DX11.

Awww. No worries. Thanks a lot for DX12 support on Duckstation though. Much appreciated!

**Comment by alessiot89** [comment]
intel removed directx 12 support in haswell graphics since they didn't want to fix a security bug in their drivers. If you want a "proper" d3d12 driver for haswell you need version 15.40.42.5063 or older: https://www.intel.com/content/www/us/en/download/18369/28662/intel-graphics-driver-for-windows-15-40.html

on later versions despite listened or not the support on the readme files, the basic initialization of direct3d 12 interfaces will fail.

**Comment by TellowKrinkle** [comment]
They said they *were* using those drivers and were experiencing crashes

Side note: Linux has experimental Vulkan support for Haswell, and AFAIK it does work with PCSX2, so if you're willing to use Linux you can get all the benefits that Vulkan/OGL has over DX11/DX12 like better blending without the bad performance of OGL

**Comment by alessiot89** [comment]
haswell direct3d 12 support is very old and may not work in the right way at all with recent versions of dxgi and d3d12. Also such driver reports wrong feature supports by d3d12 queries, like tiled resource which isn't supported at all despite the query will report the opposite.
