### ISSUE TITLE
[BUG]: Fullscreen mode crash when using Direct3D 11 on AMD Switchable Graphics

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [PCSX2/pcsx2#9732]
### Describe the Bug

I have an old but working laptop with AMD Radeon 6630M + Intel HD Graphics 3000 and it's shocking to me that the latest PCSX2 builds run pretty fast on those specs. However, every time I try to enter full screen mode when using Direct3D 11 it crashes the emulator. The same behavior happens on Duckstation and not through OpenGL, but I don't want to use it due to performance issues.

Also I expected #8738 to fix this problem, but nothing changed and later I forgot to report it here.

### Reproduction Steps

Boot the BIOS with Direct3D 11 backend and press Alt + Enter.

### PCSX2 Revision

v1.7.4873

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[crash-2023-08-07-00-13-41-440.zip](https://github.com/PCSX2/pcsx2/files/12270481/crash-2023-08-07-00-13-41-440.zip)

**Comment by stenzek** [comment]
No other AMD users have reported any issues. The crash is in AMD's driver, dereferencing a null pointer.

From a quick google search, looks like your driver is from 2016. Not going to dig further when it's likely a buggy 7 year old driver.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@stenzek still think it's definitely due to some Qt backend bug, since all other Direct3D 11 apps work fine, but I can't get the debugging setup right.

**Comment by stenzek** [comment]
Not sure what you expect us to do when we can't reproduce the issue. Hacking around a driver past halfway to a decade old is a little unreasonable.

**Comment by TellowKrinkle** [comment]
Just tested with a 6770M and AMD's Catalyst 15.7.1 (2015) driver, the last stable driver for this GPU, and it works fine.

8.17.10.1433 appears to match the version from the Crimson 16.2.1 Beta drivers.
Maybe try the non-beta driver?

**Comment by lightningterror** [comment]
Could also try the Nimez modded drivers.
