### ISSUE TITLE
[BUG]: Ipega 9078 won't auto detected.

### ISSUE THREAD

**Issue by agent13** [PCSX2/pcsx2#9736]
### Describe the Bug

when open the emulator, ipega 9078 won't auto detected.

### Reproduction Steps

*Turn ON the controller
* Open the emulator
The controller Is not detected when play a game. 

### Expected Behavior

The Controller work if turn off and turn on again, with emulator still open.

### PCSX2 Revision

v1.7.4874

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Please use the Discord server for support. You probably need to create a controller database entry for it.

**Comment by agent13** [comment]
> 

how to create a controller database?
