### ISSUE TITLE
[BUG]: Missing artwork for achievements

### ISSUE THREAD

**Issue by Valinore7** [PCSX2/pcsx2#9747]
### Describe the Bug

Failing to fetch artwork for game/achievements when using RetroAchievements.  
RetroAchievements recently had some downtime and i believe they made some changes to their servers. 

A response I got on their forum suggested a link template for fetching artwork would need to be updated in the emulator: 

> Here's example of the link that the emulator uses which no longer works.
> https://i.retroachievements.org/Badge/386706.png
> And here's the new working link.
> https://media.retroachievements.org/Badge/386706.png

Link to Bug report thread on RetroAchievements which includes images with more information:
https://retroachievements.org/viewtopic.php?t=22835&c=178707#178707

PS. Bug is also present in Duckstation (in case there is some dev overlap). 

### Reproduction Steps

Boot any unplayed game while logged in to RetroAchievements. 
It will fetch the Achievements but no artwork. Displaying only the placeholder image. 

### Expected Behavior

A list of Achievements with Game artwork and artwork for each achievement. 

### PCSX2 Revision

v1.7.4885

### Operating System

Windows 11

**Comment by Mrlinkwii** [comment]
Not a pcsx2 bug ,

**Comment by stenzek** [comment]
It is, indirectly, we need to bump the rcheevos submodule version.

**Comment by Valinore7** [comment]
@stenzek Would this fix apply to Duckstation as well?

**Comment by stenzek** [comment]
I've already pushed the change for DuckStation.

**Comment by Valinore7** [comment]
Awesome. Thank you very much.

**Comment by Mrlinkwii** [comment]
@Valinore7  can you check #9748

**Comment by Valinore7** [comment]
@Mrlinkwii I'm sorry, what do you need me to check? 
I tested the update for Duckstation and it's now working as intended.

**Comment by kamfretoz** [comment]
@Valinore7 check that PR to make sure that the issue has been fixed.

**Comment by stenzek** [comment]
I'm less concerned about the images (they'll work fine with the change), but more about any regressions to the achievement handling itself.

**Comment by Valinore7** [comment]
@Mrlinkwii @kamfretoz 
I'd be happy to check it out, but I can't figure out where to download that particular build >_<
I'm sorry, it's my first day on github, it's all a bit confusing. (I basically made this account to report the bug)

**Comment by Mrlinkwii** [comment]
@Valinore7 https://github.com/PCSX2/pcsx2/actions/runs/5807365744

**Comment by kamfretoz** [comment]
@Valinore7 Join our Discord and we'll guide you.
