### ISSUE TITLE
[Feature Request]: Windows 10/11 arm support

### ISSUE THREAD

**Issue by CCNHsK-Dev** [PCSX2/pcsx2#9749]
### Description

pls support windows 10/11 arm version. 

### Reason

x64 version running on windows 11 arm (Microsoft Surface Pro X) is laggy.
request native arm version, thank you:)

### Examples

N/A

**Comment by Mrlinkwii** [comment]
its not planned ,

**Comment by CCNHsK-Dev** [comment]
so sad :(
