### ISSUE TITLE
Maybe make bios specifically for pcsx2

### ISSUE THREAD

**Issue by twarnercool2** [PCSX2/pcsx2#975]
Maybe instead of having to get our own bios(which isn't that hard. Maybe Pcsx2 can has its own bios. It might be hard. But it be nice to have. It  might make some games run better too.

**Comment by willkuer** [comment]
This idea is not really new. Some people already started fps2bios - a free ps2 bios - but it never went far enough to replace th real bios. Play! (Alternative ps2 emulator) has its own ps2 bios iirc.

The first problem is the direct confrontation against sony. If we reverse-engineer the bios sony might want to start a law suite against pcsx2. So far you need to buy a ps2 to use pcsx2.

But also creating a working bios will take time and pcsx2 doesnt have a ton of free dev's.

I would say this sub project stopped until some enthusiast comes around starting from scratch reading what Play! and fps2bios achieved so far.

**Comment by gregory38** [comment]
The real problem is free time (and you can't have everything 64bits/speed/gs...). The 2nd problem is compatibility issue due to different timing. Anyway I'll close this issue because it is already on the list of feature that everyone want.
