### ISSUE TITLE
[BUG]: Gran Turismo 4 - Reward screen trophies have no reflection on D3D/OpenGL

### ISSUE THREAD

**Issue by TamiyaGuy** [PCSX2/pcsx2#9753]
### Describe the Bug

When using D3D11, D3D12 or OpenGL hardware renderers, the trophy in the results screen has no reflections. This happens with Blending Accuracy set to Basic - Maximum, but not Minimum. HW hacks do not seem to affect the issue. Other reflections (e.g. car reflections

This issue has only appeared recently in the nightly builds - I can't pinpoint which version showed the change, but definitely within the last two weeks.

### Reproduction Steps

Win a race with the Renderer set to D3D11/D3D12/OpenGL and Blending Accuracy at anything except Minimum.

### Expected Behavior

The trophy should have a reflection on it (as seen in Vulkan or Software renderers)

### PCSX2 Revision

v1.7.4892

### Operating System

Windows 10 (64bit)

### CPU

i7-7700k

### GPU

GTX 1070

### Emulation Settings

EE Clamping Mode: Full

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/132924578/72752034-643a-4632-823c-77b2150ba016)

**Comment by Mrlinkwii** [comment]
can i have a gs dump?

**Comment by lightningterror** [comment]
Regression from https://github.com/PCSX2/pcsx2/pull/9196

**Comment by lightningterror** [comment]
Game does accumulation blend `Cs*128 + Cd`, rt alpha min max are both 128, this worked on vulkan by chance because we were still reading the RT without any barriers, whereas on dx alpha was 0 and on gl undefined. We shouldn't be reading the RT in this case since we know what Ad will be.
