### ISSUE TITLE
[BUG]:   Jak X: Combat Racing racing IPU issue 

### ISSUE THREAD

**Issue by Mrlinkwii** [PCSX2/pcsx2#9754]
### Describe the Bug

Jak X: Combat Racing has an IPU issue when you boot the game  , 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/26c5e202-bd2a-470e-a32d-cbbd09838d0e)

### Reproduction Steps

boot said game .You have to skip the video for it to break

### Expected Behavior

game to work

### PCSX2 Revision

v1.7.4891

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu ,  but also happens on windows 

### CPU

Intel Xeon E5-1620 v3

### GPU

 NVIDIA Quadro K2200

### GS Settings

N/A

### Emulation Settings

default 

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/17685135/d084da97-908c-4e09-928d-c851b3556a29)

**Comment by refractionpcsx2** [comment]
I looked in to this and it appears to be the DMA is just too slow for Jak X, I have potential ideas to improve this in future (hardware testing pending), but for now I'll fix it with instant DMA.

**Comment by Goatman13** [comment]
Sorry for offtopic, but that vrsqrt / vaddq pair doesn't look good.

**Comment by refractionpcsx2** [comment]
it's fine, I do keep meaning to do a dynamic patch for the Jak games, but it's just a random number generator, so it doesn't matter.
