### ISSUE TITLE
[BUG]: God Hand Glitchy World

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9755]
### Describe the Bug

As you move around during where you fight the first set of enemies, the game world will begin to render in-n-out.
This happens on all renderers including Software Mode.

GSDump & screenshots provided below:

### Reproduction Steps

Beginning of the game, during where you first have control of the player.

### Expected Behavior

No glitchyness.

### PCSX2 Revision

v1.7.4892

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Native settings.

### Emulation Settings

Default settings.

### GS Window Screenshots

![God Hand_SLUS-21503_20230809172314](https://github.com/PCSX2/pcsx2/assets/116039192/5456ea3a-c1ab-4124-9930-5919c060e6b4)
![God Hand_SLUS-21503_20230809172342](https://github.com/PCSX2/pcsx2/assets/116039192/fb4c95df-25ae-4021-89de-48bd42cf6c71)
![God Hand_SLUS-21503_20230809172344](https://github.com/PCSX2/pcsx2/assets/116039192/86788970-eef1-4753-a782-7e83243678c7)
![God Hand_SLUS-21503_20230809172431](https://github.com/PCSX2/pcsx2/assets/116039192/ea086094-3158-4857-9109-cf716b8511fa)

### Logs & Dumps

[God Hand.zip](https://github.com/PCSX2/pcsx2/files/12304795/God.Hand.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/291b5000-e074-4a04-bf3f-38a44dd118c3) works here , make sure you havent enabled any cheats

**Comment by refractionpcsx2** [comment]
Can't reproduce at all, can you provide a savestate at the point it goes wrong?

**Comment by stenzek** [comment]
Verify your dump in Game Properties as well, and if it fails, re-dump the game from disc.

**Comment by refractionpcsx2** [comment]
Thanks, but please don't rename the state files, it just makes it more annoying :P
