### ISSUE TITLE
[BUG]: Demo did not play after certain period of time in titlescreen.

### ISSUE THREAD

**Issue by Cologarithm** [PCSX2/pcsx2#9756]
### Describe the Bug

after latest update the demo does not play anymore after waiting in title screen for certain period of time.
downgrade to version 1.7.4883, the game play demo normally.
already tried resetting all setting and remove cache.
Game tried:
1. Tales of Destiny Director's Cut (SLPS-25842)
2. Dynasty Warriors 3 - Xtreme Legends (SLUS-20617)
3. Dynasty Warriors 4 - Xtreme Legends (SLUS-20812)

### Reproduction Steps

1. Start the game
2. Wait at title screen for next demo to play.

### Expected Behavior

Demo play after certian period of time pass on title screen.

### PCSX2 Revision

1.7.4892

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 2700X

### GPU

GTX 2070

**Comment by Cologarithm** [comment]
Sorry it's yesterday vs today build I'll try the version in-between and then report back. I already try both change controller config to keyboard and not connected so I don't think it's controller. thank you for quick response!

**Comment by refractionpcsx2** [comment]
if you could check the in between builds and find the break point, that would be greatly appreciated, just makes testing easier for us and potential fixes :)

**Comment by Cologarithm** [comment]
Despite performing a clean installation, the issue still persists. The demo properly play on my 2 other PC, and I cannot reproduce the problem after updating them all to version 1.7.4892. All tested perform with controller config 'Not Connected' and everything else at default. I've also encountered a separate problem on my PC with another game, where there is no sound after the initial sound effect in DMC3SE on default which happen before update. this might be a hardware or OS installation issue on my end. since this is also Work PC I can't easily format and test so I will be closing this issue as can't repro. Thank you again for your time!

**Comment by refractionpcsx2** [comment]
Alright, thanks for letting us know :)
