### ISSUE TITLE
[Feature Request]: The ability to custom-arrange the game list

### ISSUE THREAD

**Issue by AgentLogan1** [PCSX2/pcsx2#9759]
### Description

The games in the game list when displayed as their respective covers are arranged in alphabetical order, the request is to have the ability to arrange them customizable-ly in any order the user wishes, as in drag the game cover and place it before or after another game and have it remain this way

### Reason

Mentioned above

### Examples

As explained above

**Comment by stenzek** [comment]
Not possible without significant changes to how the QListView works. You'd have to tie it into the sort model, and that would be quite messy, because there's no implicit order there.
