### ISSUE TITLE
[Bug Report] [Folder Memory Card] Final Fantasy XII - Corrupted Save Data when overwriting Save

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#976]
I found this through the Wiki and tested it myself, originally I couldn't reproduce it initially, but after further testing, I found out that once you attempt to load the save, it shows your data as corrupted.

Basically it's like this, you Save your game while using the Folder Memory Card system, and if you attempt to overwrite the Save it seems to have Saved ok (It'll show up correctly after Saving), but once you attempt to go to the load screen the data will have become corrupted.

Using the regular Memory Cards does NOT have this issue. It's a specific issue with the Folder Memory Card system.

![pcsx2 2015-11-16 10-03-06-805](https://cloud.githubusercontent.com/assets/10039778/11177953/9f063f86-8c49-11e5-84a7-00e07923cafb.png)

I haven't tested this with the International Zodiac Job System version yet, but it's safe to assume that the same thing will happen there as well, as they use the same Saving method.

**Comment by willkuer** [comment]
As he probably did not subscribe I just ping @AdmiralCurtiss here. Maybe he knows the issue.

What does it mean that you couldn't reproduce it first? Is there some special way to reproduce or to avoid the error?

**Comment by Ryudo300** [comment]
I was too quick in judging that it wasn't reproducable. 

When you first overwrite the Save, in the save screen it shows the 'updated' data. So I assumed it was working correctly.

But when you start up the game later on and attempt to load that save, it shows the screen from the screenshot instead. (aka the data became corrupt).

**Comment by AdmiralCurtiss** [comment]
Interesting. I'll check this out when I get home today.

**Comment by Ryudo300** [comment]
https://www.youtube.com/watch?v=OaS1JDxrzoc

Here's a video of the bug in action. 

Overwriting Save Slot 3 causes it to be corrupt later. The 'new' save data on Slot 2 functions fine.

**Comment by AdmiralCurtiss** [comment]
Yeah there's definitely something broken here.

**Comment by AdmiralCurtiss** [comment]
Okay, I have a suspicion about what's causing this, I'll check if that's actually it tomorrow and if so implement a fix for it. I think what's happening is the opened-file cache is incorrectly giving back the wrong file handle because the memory card address matches the previous address of the file handle but the file entry at that address now points to a different file. If that's actually it then I'm rather surprised this isn't affecting more games.

**Comment by Ryudo300** [comment]
It's possible other games suffer from the issue too perhaps, but it might not have been noticed yet. It could just be a select few games. Do you think it would be a 'global' fix? (So other potential games would have this issue fixed as well if they were suffering from it).

**Comment by AdmiralCurtiss** [comment]
Yeah it should be a global fix once implemented. I'll probably change the lookup to work by path instead of address.
