### ISSUE TITLE
[BUG]: [GameDB] SLKA-25330 Battlefield 2: Modern Combat missing from GameDB

### ISSUE THREAD

**Issue by OmegaGG** [PCSX2/pcsx2#9764]
### Describe the Bug

[NTSC-K] SLKA-25330 Battlefield 2: Modern Combat (배틀필드2 : 모던 컴뱃) is missing from GameDB and therefore doesn't benefit from the extensive GS fixes applied to the NTSC & PAL games SLUS-21026 & SLES-53729/53730.

The current GS fixes for PAL/NTSC games should work here with no issues. 

Image attached shows same issue as NTSC/PAL Versions had with top section of the screen rendering only in HW Vulkan rendering. 

```
[33783.7578] [GameDB] Searching for 'slka-25330' in GameDB
[33783.7578] [GameDB] Could not find 'slka-25330' in GameDB
```

### Reproduction Steps

Load Disc into PCSX2; Check Logs. 
Check Game fixes from PAL/NTSC Region games. 

### Expected Behavior

The GS Fixes to PAL/NTSC region variants of this game should work here. 

### PCSX2 Revision

v1.7.3858 (BF2:MC Works best here)

### Operating System

Windows 11

### CPU

i5-12600K

### GPU

RTX2070 SUper

### GS Settings

N/A

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/45330950/661e5ae7-b6be-46ec-9825-adafe7d9d7d7)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/6cd6e612-af39-4f44-b3d0-691542fd27af)
its already their but just missing fixes, also your on a very old build

**Comment by OmegaGG** [comment]
> ![image](https://user-images.githubusercontent.com/17685135/259992504-6cd6e612-af39-4f44-b3d0-691542fd27af.png) its already their but just missing fixes, also your on a very old build

Okay awesome.

Using v1.7.3858 as the Multiplayer section of the game doesn't work as well in later builds.
(Multi-ELF game and Multiplayer game uses different rendering from Singleplayer)

Previous git issue was closed as 'wontfix' by Stenzek so we stick with earlier builds for now.
