### ISSUE TITLE
Installation Errors [unmet dependencies]

### ISSUE THREAD

**Issue by SirStarshine** [PCSX2/pcsx2#977]
I'm running a fresh installation of Ubuntu 14.04 x64, and tried to install PCSX2. However when I get to the last step, "sudo apt-get install pcsx2" (stable or unstable), I get this message:
"
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
"
I've looked around, but I have no idea how to get past this. I'd really appreciate any help.

**Comment by yxmline** [comment]
sudo dpkg --add-architecture i386
sudo apt-get update

**Comment by SirStarshine** [comment]
Ok, I tried these commands in different order with the installation, but it hasn't changed anything. Could you be a little more specific?

**Comment by yxmline** [comment]
Package dependency was not written
Can be compiled from the source code to solve the problem

**Comment by willkuer** [comment]
Did you follow the linux compilation guide for ubuntu and installed all dependencies? I think only sdl2 and png++ libs are missing there. I followed [this guide](https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux) but possibly there are other guides that work as well.

**Comment by gregory38** [comment]
Forums are more efficient for this kind of issue. Anyway, if you don't post the full command and the full log we can't help you.

**Comment by SirStarshine** [comment]
@willkuer I couldn't even begin to follow that guide, unfortunately. I don't know anything about cmake.

@gregory38 I've looked for forums, or anything else that could help, but I never found anything. Anyway, I'm including a link to the full terminal log.
https://docs.google.com/document/d/1aZBrFo4JYBk2vufZi54bkMsh5mQWKALIRJFF5f_3QTM

**Comment by willkuer** [comment]
I can not access that document.

micove posted once a nice summary:

> sudo apt-get install build-essential cmake debhelper libaio-dev:i386 libasound2-dev:i386 libgl1-mesa-dev:i386 libgtk2.0-dev:i386 liblzma-dev:i386 libpng++-dev:i386 libpng-dev:i386 libsdl1.2-dev:i386 libsoundtouch-dev:i386 libwxbase3.0-dev:i386 libwxgtk3.0-dev:i386 libx11-dev:i386 portaudio19-dev:i386 zlib1g-dev:i386

I am not sure if this list is complete but I guess it is.

**Comment by gregory38** [comment]
This guide is for self-compilation.

@SirStarshine which version do you try to install my ppa or ubuntu version?
```
apt-cache policy pcsx2-unstable:i386
```
Then post the full log of
```
apt-get install pcsx2-unstable:i386
```

Again so far with your limited log
```
unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
Issue isn't related to PCSX2 but unity.

**Comment by gregory38** [comment]
No news, I close the bug report.

**Comment by weirdtalk** [comment]
I ran into this issue as well, but managed to work around it. Here are my steps for anyone needing them.

```
sudo apt-get remove gnome-control-center unity-control-center
```

You will be asked to install a bunch of replacements, type yes (you can install them again after you have pcsx2 installed).

```
apt-get install pcsx2-unstable:i386
```

Now reinstall what you uninstalled (otherwise you will have weird issues like not being able to change you desktop background).

```
sudo apt-get install gnome-control-center unity-control-center
```

I don't know why this works, but it seems to work just fine for me.

**Comment by DoobleD** [comment]
Thanks, this worked !

**Comment by Shawnnn** [comment]
When I tried to apt-get install pcsx2-unstable:i386,
the result showed, cannot loacate the pcsx2-unstable package

**Comment by gregory38** [comment]
Did you try an `apt-get update`

**Comment by Shawnnn** [comment]
Yeah, I tried it already.

**Comment by gregory38** [comment]
Open a thread on PCSX2's forum

**Comment by ivanlmj** [comment]
Sorry @gregory38  but, is that right?
Closing an issue which was not resolved?
I thought that this issue should be resolved here, where the pcsx2 project lives :), or am I wrong?

**Comment by gregory38** [comment]
This bug tracker is about PCSX2 bug. Not users/distribution issue. There are forums available for those kinds of issues. Beside the OP was on Ubuntu 14.04 which isn't supported anymore.
