### ISSUE TITLE
[BUG]: GTA Vice City Stories time bar too fast at 60fps

### ISSUE THREAD

**Issue by Necroso** [PCSX2/pcsx2#9772]
### (NTCS-U) [SLUS-21590] Grand Theft Auto - Vice City Stories

The mission uses the following time bar:
![alt text](https://imgur.com/kKtFDNT.png)

When running the game without the 60 FPS patch by the author asegaga, this bar fills up very quickly and it is impossible to load all the loads into the truck.

To better understand the mission, see here https://youtu.be/3DMnFimuFS0?t=248

### Reproduction Steps

Go to the game properties and activate the 60 FPS patch.

### Expected Behavior

Apenas habilitar 60 FPS sem causar outras alterações de comportamento ou dificuldade.

### PCSX2 Revision

v1.7.4905

### Operating System

Windows 11

### CPU

AMD Ryzen 5 4500

### GPU

GTX 1050 Ti

**Comment by refractionpcsx2** [comment]
We don't suppose 60fps patches, they are supplied as-is. If they case problems please take it up with the original author.

Thanks.
