### ISSUE TITLE
[BUG]: Lego Star Wars II: The Original Trilogy

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9774]
### Describe the Bug

Hello, I don't speak English, I use Google Translator, I wanted to comment that since the first updates today, Friday, there are games that do not display correctly, for example, Lego Star Wars II: The Original Trilogy, the shadows are displayed as rectangles and there is a semi-transparent rectangle that occupies the upper half.

It has been working correctly until v1.7.4896, in the following versions v1.7.4897... until v1.7.4906 it gives that error, I have also seen it in other games but I don't remember them (I was playing several).

### Reproduction Steps

open the game and start game, with vulkan as renderer

### PCSX2 Revision

v1.7.4906

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

### GS Window Screenshots

![LEGO Star Wars II - The Original Trilogy_SLES-54221_20230811232807](https://github.com/PCSX2/pcsx2/assets/142044650/c4f7f629-5860-4e08-a77c-6ab9648a18f0)

**Comment by lightningterror** [comment]
Can you post a gs dump?

**Comment by Parallax71** [comment]
> Can you post a gs dump?

I do not know how to do it

**Comment by RedDevilus** [comment]
> > Can you post a gs dump?
> 
> I do not know how to do it

**What is a GS dump?**
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

**Where do I make the dump?**
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

**How do I make the dump?**
Use the key combination `Shift + F8`

On Qt builds of PCSX2, you can also use `Tools > Save Single Frame GS Dump`

**Where does the GS dump save to?**
GS dumps are saved to the `/snaps` folder.
- If you used the PCSX2 installer, you will find it in Documents/PCSX2.
- If you are using a nightly build, you will find `/snaps` in the same folder as the PCSX2 executable.

*Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.*

More information on the PCSX2 forums:
<https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump>

**Comment by Parallax71** [comment]
> Can you post a gs dump?

![LEGO Star Wars II - The Original Trilogy_SLES-54221_20230811235305](https://github.com/PCSX2/pcsx2/assets/142044650/14e5de8a-9ed7-42ca-a858-90e20b27ab4e)

**Comment by Parallax71** [comment]
is that okay?

**Comment by lightningterror** [comment]
Can't reproduce, reset settings and try again?

**Comment by Parallax71** [comment]
> Can't reproduce, reset settings and try again?

hello, good morning, I just tried what you told me and the BUG has disappeared, that is, I have put all the default values, I have only changed the resolution to x2 (720p) and activated the v-sync, which is what I think I did a long time ago with the first versions v1.7... (the only thing that was different and coincided with the PCSX2 updates was a GPU update (GTX 1070), could that have been the cause of the all this? Thank you for your time and kindness.

[LEGO Star Wars II - The Original Trilogy_SLES-54221_20230812084754.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12326775/LEGO.Star.Wars.II.-.The.Original.Trilogy_SLES-54221_20230812084754.gs.zst.zip)
![LEGO Star Wars II - The Original Trilogy_SLES-54221_20230812084754](https://github.com/PCSX2/pcsx2/assets/142044650/db16f8e6-d85e-4ff9-b225-e6719689e405)
