### ISSUE TITLE
[BUG]: NBA Live 04 - Floor disappears on Metal renderer

### ISSUE THREAD

**Issue by arnaud352901** [PCSX2/pcsx2#9776]
### Describe the Bug

Floor disappear on Metal renderer, appears on Software mode

### Reproduction Steps

Game launch, runs ok, floor always disappear on Metal renderer

### Expected Behavior

Floor must appears on every renderer (Vulkan was ok too before)

### PCSX2 Revision

v1.7.4906

### Operating System

macOS 11 (Big Sur)

### CPU

I5

### GPU

Intel Iris 1536

### GS Window Screenshots

Metal Renderer

![6383F932-A946-4F81-90B3-2A7078C7A5EA_1_105_c](https://github.com/PCSX2/pcsx2/assets/123305418/b67ab203-f815-473e-9030-00540bcbda2c)

Software Renderer

![C994DEAB-C366-4C88-A3CE-DBB44FA3C114_1_105_c](https://github.com/PCSX2/pcsx2/assets/123305418/628e4880-bd5d-49fa-aba8-09314ad7cf7f)

**Comment by refractionpcsx2** [comment]
Is vulkan still okay? Your post casts doubt but specifically mentions metal, so I'm a little confused.

**Comment by arnaud352901** [comment]
Vulkan was good too before removing, it only happens on Metal. I tried default options with native resolution, other graphics tests, still the same thing

**Comment by stenzek** [comment]
GS dump?

**Comment by arnaud352901** [comment]
[NBA Live 2004_SLES-52008_20230812063245.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12326583/NBA.Live.2004_SLES-52008_20230812063245.gs.zst.zip)

**Comment by stenzek** [comment]
Seems fine here on M2 Pro:
![image](https://github.com/PCSX2/pcsx2/assets/11288319/41a539a6-1007-4e42-8a0e-995de02ca64a)

Unless it's not showing up in the GS dump for some reason.

**Comment by stenzek** [comment]
Majestic found that it was fine on Intel, but broken on AMD.

Could also be due to the older OS version.

Tagging @TellowKrinkle, because I can't reproduce the issue on my M2, and the draw doesn't seem anything out of the ordinary (it's all in a single render pass). No API validation errors either.

**Comment by arnaud352901** [comment]
Vulkan was the best renderer for this game for an old hardware like mine, any chance to get it on macOS in a PCSX2 further version?

**Comment by stenzek** [comment]
It was never the "best". MoltenVK adds considerable overhead compared to native Metal, and was missing extensions which cause rendering errors in a number of games. It was only intended as a debug tool, and it's not really useful there anymore, since there's multiple of us on the team with Mac hardware who can debug Metal issues now.

I'm not going to enable something which is known to render games correctly, that just creates support headaches.

We'll see if Tellow can identify if this is a driver bug, and whether it is possible to work around. In theory if MoltenVK used to render it correctly, it can be.

**Comment by arnaud352901** [comment]
Thanks for your explanations!

**Comment by arnaud352901** [comment]
Just tested PR #9786, everything runs fine now on Metal, great job! It can be merged now. Thanks for your work!

![8EB4FF2C-D58E-41A3-A76F-18622C0E3445_1_105_c](https://github.com/PCSX2/pcsx2/assets/123305418/d00931ba-9785-4798-86ea-07f0c4ced52f)

**Comment by refractionpcsx2** [comment]
Please leave it open until it merges, thanks.  It will auto close.
