### ISSUE TITLE
[BUG]: Haunting Ground/Demento: shadows volume issue 

### ISSUE THREAD

**Issue by abembritishav** [PCSX2/pcsx2#9787]
### Describe the Bug

Shadows can stretch out and stick to character model on applicable light sources. Seems to be easily work around with autoflush set to 2.

### Reproduction Steps

Easily observable but it can be spotted rather noticeably when upscaling.

### Expected Behavior

Shadows shouldn't stick up to character model.

### PCSX2 Revision

1.7.4915

### Operating System

Windows 11

### CPU

Core i5-4460

### GPU

HD Graphics 4600

### GS Settings

Default D3D11 with maximum blending, and fixed by autoflush mentioned above.

### GS Window Screenshots

w/o autoflush, native res.
![Haunting Ground_SLUS-21075_20230813143931](https://github.com/PCSX2/pcsx2/assets/75411083/bd598384-7919-4a6e-b612-e14cefc86f35)

with autoflush
![Haunting Ground_SLUS-21075_20230813143900](https://github.com/PCSX2/pcsx2/assets/75411083/4395b34b-823e-4ef6-9381-044b2a3908aa)

### Logs & Dumps

[dump_Haunting Ground_SLUS-21075_20230813143809.zip](https://github.com/PCSX2/pcsx2/files/12328995/dump_Haunting.Ground_SLUS-21075_20230813143809.zip)

**Comment by bigol83** [comment]
I checked the dump and want to add that this only happens with DX11 and DX12 renderers. It's not happening with Vulkan and Opengl.

**Comment by stenzek** [comment]
> I checked the dump and want to add that this only happens with DX11 and DX12 renderers. It's not happening with Vulkan and Opengl.

Indeed. It's hitting the Jak stencil path.

![image](https://github.com/PCSX2/pcsx2/assets/11288319/c08f7bb8-56fd-47e7-b873-e580c17c03c1)
![image](https://github.com/PCSX2/pcsx2/assets/11288319/b4544288-e529-4d80-8e10-70a62c80ace2)

That's also why changing autoflush affects it. But we're not going to hurt Vulkan performance for the sake of DX, which is never going to be accurate, except with ROV (and even then, just use Vulkan).
