### ISSUE TITLE
[BUG]: Code Lyoko - Missing Text from Dialogs

### ISSUE THREAD

**Issue by kamfretoz** [PCSX2/pcsx2#9790]
### Describe the Bug

Several In-Game dialog are missing the texts, also happens in SW mode as well.
According to @refractionpcsx2 this could be a core bug.

https://github.com/PCSX2/pcsx2/assets/14798312/6b7d5a6f-9944-4be1-a283-4ae03e258f0f

### Reproduction Steps

1. Boot up the game
2. Once in the main menu, go to the Save/Load section
3. Do either Save/Load game
4. Notice that the dialog does not have any texts on it

### Expected Behavior

The dialog has texts on it. I have checked on the actual PS2 and the text appears correctly.

https://github.com/PCSX2/pcsx2/assets/14798312/19ee5d88-c692-4c3b-bab3-6687b6498448

### PCSX2 Revision

v1.7.4915

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch Linux

### CPU

AMD Ryzen 7 5800X

### GPU

NVIDIA GeForce GTX 1660 SUPER

### GS Settings

All settings are default.

### Emulation Settings

All settings are default.

### GS Window Screenshots

![Screenshot_20230813_234828](https://github.com/PCSX2/pcsx2/assets/14798312/b4527c07-b851-4c78-a0cc-46fdfac2cb33)

### Logs & Dumps

Here is the GS Dump.

[Code Lyoko - Quest for Infinity_SLUS-21743_20230813221951.zip](https://github.com/PCSX2/pcsx2/files/12329955/Code.Lyoko.-.Quest.for.Infinity_SLUS-21743_20230813221951.zip)

**Comment by Goatman13** [comment]
Works with DIV negative rounding hack, but i don't know if rest of the game is happy with it.

**Comment by kamfretoz** [comment]
Enabling FPU DIV Negative Rounding Hack doesn't seems to break other stuff.
