### ISSUE TITLE
[BUG]: samurai warrios 2 xl black screen

### ISSUE THREAD

**Issue by Jarbas15** [PCSX2/pcsx2#9792]
### Describe the Bug

 in some stages of the game, usually dream stages, the game has
[Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20230813193035.zip](https://github.com/PCSX2/pcsx2/files/12330546/Samurai.Warriors.2.-.Xtreme.Legends_SLUS-21726_20230813193035.zip)
[Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20230813193045.zip](https://github.com/PCSX2/pcsx2/files/12330548/Samurai.Warriors.2.-.Xtreme.Legends_SLUS-21726_20230813193045.zip)
![Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20230813193035](https://github.com/PCSX2/pcsx2/assets/101490980/cd6f0ab4-d15d-48cb-9175-39380bc5dd4a)
![Samurai Warriors 2 - Xtreme Legends_SLUS-21726_20230813193045](https://github.com/PCSX2/pcsx2/assets/101490980/e7dae27f-b2d4-44a1-a0e2-63c62f3fbece)
 a black screen and background music.

### Reproduction Steps

Play with the Hideyoshi character until you reach the dream stage

### PCSX2 Revision

v1.7.4915

### Operating System

Windows 11

### CPU

i3 8100

### GPU

gt 1030

**Comment by Mrlinkwii** [comment]
the GS dump works in both 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/1a0761c1-4778-4b88-82ee-290b7525fc1c)
![image](https://github.com/PCSX2/pcsx2/assets/17685135/5f90042f-14f1-4f69-8ff0-3dbc7928850b)

**Comment by Jarbas15** [comment]
the bug occurs after I press start, there is a black screen and background music

**Comment by Jarbas15** [comment]
I managed to solve
Solution: I downloaded another clean Iso and imported another clean iso and it worked.
  The iso I reported the problem was modifying with the import on it

**Comment by MrCK1** [comment]
We don't provide further support for piracy.
