### ISSUE TITLE
[Feature Request] Big Picture mode / Pause Menu improvements

### ISSUE THREAD

**Issue by awsms** [PCSX2/pcsx2#9794]
### Description

There are a bunch of current behaviours that I find unnatural, or simply missing

I didn't feel like spamming feature requests for each, but please let me know if you'd prefer it that way so I can close this one and open others.

1. Add a hotkey to toggle the Pause Menu.
2. Do not exit the Pause Menu when going in a sub-menu (like Save State, or Achievements), and pressing the return button.
3. Enable analog controls (sticks + L2/R2) in the Pause Menu

This is a bit offtopic, but I found a bug where, when the Pause Menu is opened, going to the "Save/Load State" option, and pressing the "Open Pause Menu" hotkey, it will spawn another instance of a Pause Menu in the background

### Reason

1. I think users would be expecting to close and open a menu with the same button (that's how I feel though). Adding a hotkey for toggling the menu would do this.
2. I don't see the logic behind this behaviour really, the user would expect to go back to the previous menu (main pause menu in that case), not closing it entirely
3. You can only use the d-pad to browse menus, using the left analog stick/L2/R2 to scroll quickly would be cool too

### Examples

Thank you for reading my blog post :smile:

**Comment by awsms** [comment]
Was that menu actually created by the PCSX2 devs? I noticed it's identical in duckstation (was gonna make the same issue there before noticing it)

**Comment by stenzek** [comment]
1. There's already a hotkey, it's bound to escape by default.
2. This is doable.
3. Not possible with the current way controller input is handled in imgui.

**Comment by awsms** [comment]
> 1. There's already a hotkey, it's bound to escape by default.

Mh I can't see a hotkey for toggling it, only one to open the menu. The escape key is bound to "Shut Down Virtual Machine" for me

**Comment by stenzek** [comment]
Then change it? Escape will close, if you bind escape to open, it's effectively a toggle.

**Comment by awsms** [comment]
> Then change it? Escape will close, if you bind escape to open, it's effectively a toggle.

Oh I see. I don't want to bind it to escape or any keyboard key, but a controller key instead :octocat:

**Comment by stenzek** [comment]
Then pushing B/X (or A/O, I forget which I made it) will close the menu.

Hotkeys don't fire when imgui is active, because it'd be doing two things for each button press.

**Comment by awsms** [comment]
> > 3. Not possible with the current way controller input is handled in imgui.
> 
> Hi stanzek, I was wondering if the sticks part was still not currently doable on PCSX2? Since it's working on duckstation, just wanted to be sure. Thanks

Bump, it would be very welcomed in PCSX2!
