### ISSUE TITLE
[Regression]: GT4 shuffle misdetection heuristics

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#9798]
### Describe the Bug

Weird elements that pop up through tracks or flicker.

regression from https://github.com/PCSX2/pcsx2/pull/9745 (or 1.7.4899)

### Reproduction Steps

GT4 run a race I guess

### Expected Behavior

Now looks ugly

### PCSX2 Revision

v1.7.4919

### Operating System

Windows 10 (64bit)

### CPU

N/A

### GPU

N/A

### Logs & Dumps

Unzip:
[Gran_Turismo_4_Online_Public_Beta_SCUS-97436_20230815063859.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12341055/Gran_Turismo_4_Online_Public_Beta_SCUS-97436_20230815063859.gs.zst.zip)
[Gran_Turismo_4_Online_Public_Beta_SCUS-97436_20230815060733.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12341056/Gran_Turismo_4_Online_Public_Beta_SCUS-97436_20230815060733.gs.zst.zip)

Reported on Discord and I checked the dump and this breaks 

Previous behaviour:

![image](https://github.com/PCSX2/pcsx2/assets/24227051/672c0c8c-72ba-4a46-86b0-c3d601e9f336)

Master: 
Flickery and weird stuff

![image](https://github.com/PCSX2/pcsx2/assets/24227051/c9768496-8613-48c4-a5d1-d060908b1cee)

![image](https://github.com/PCSX2/pcsx2/assets/24227051/e6a3ddab-70b6-4ccf-af35-6bf9f3600027)

Hard to see when you change renderer from Hardware to software as it's a single frame:

![image](https://github.com/PCSX2/pcsx2/assets/24227051/0286721e-d0f3-4f06-b603-baee3d9b0eb9)

**Comment by refractionpcsx2** [comment]
This is nothing to do with shuffles, seeing 1 broken frame when you switch renderer is not uncommon.
