### ISSUE TITLE
[Regression]: Armored Core Nexus Corrupted Menu Icon

### ISSUE THREAD

**Issue by forrvalhalla** [PCSX2/pcsx2#9799]
### Describe the Bug

In Armored Core: Nexus (US & JP Tested), "No Parts" icon in the Sell Menu appears corrupted on versions v1.7.4882 and newer.

Regression from #9713 (v1.7.4882)

![Armored Core - Nexus  Disc 1 _SLUS-20986](https://github.com/PCSX2/pcsx2/assets/53349573/c6623228-5e52-4e39-b1d6-0b3337f960ed)

### Reproduction Steps

1. Clear first mission
2. Buy any part, then enter sell menu
3. Scroll up or down 

### Expected Behavior

"No Parts" icon should not be corrupted.

### PCSX2 Revision

v1.7.4920

### Operating System

Windows 11

### CPU

i5-7600K

### GPU

GTX 1050ti

### Logs & Dumps

https://cdn.discordapp.com/attachments/1098055222678528032/1140893640823164948/Armored_Core_-_Nexus_Disc_1_SLUS-20986.gs.zst

**Comment by refractionpcsx2** [comment]
Can you provide a savestate after the first mission, or the end of? 

Thanks

**Comment by refractionpcsx2** [comment]
Hopefully :)

**Comment by refractionpcsx2** [comment]
Okay I didn't need that much, a GS dump was fine as it turns out.
