### ISSUE TITLE
[BUG]: Family Planning SLPM-65889 - Random Black Kanji

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9804]
### Describe the Bug

![Kazoku Keikaku - Kokoro no Kizuna_SLPM-65889_20230816125914](https://github.com/PCSX2/pcsx2/assets/8851653/5228640b-579a-403b-937f-f74e7f344bb4)

### Reproduction Steps

play game.

### Expected Behavior

![Kazoku Keikaku - Kokoro no Kizuna_SLPM-65889_20230816125906](https://github.com/PCSX2/pcsx2/assets/8851653/1f77a206-c035-470b-9807-7bcaf3b3d84e)

### PCSX2 Revision

1.7.4923

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Kazoku Keikaku - Kokoro no Kizuna_SLPM-65889_20230816125703.gs.zip](https://github.com/PCSX2/pcsx2/files/12362237/Kazoku.Keikaku.-.Kokoro.no.Kizuna_SLPM-65889_20230816125703.gs.zip)

**Comment by Buzzardsoul** [comment]
The GPU Target CLUT needs to be replaced with Software CLUT Render.

**Comment by seta-san** [comment]
> The GPU Target CLUT needs to be replaced with Software CLUT Render.

yes. that works.
