### ISSUE TITLE
[Feature Request]: Close games without confirmation

### ISSUE THREAD

**Issue by R3negadeSpectre** [PCSX2/pcsx2#9809]
### Description

Seems like a small thing, but in my case this kind of little thing would go a long way. When a game is quit (in my case pressing select + start), there is a confirmation that comes up. It would be great if there is another checkbox in that pop up labeled something like "Do not ask again".....meaning that if checked, next time the user quits a game there wont be any confirmation pop up and the game will just quit (along with the pcsx2 ui).

### Reason

For background as to why I'm asking for this is because I'm playing on steam deck and it breaks the experience when quitting ps2 games... that confirmation will pop up, and when using steam deck in gaming mode that confirmation is actually nowhere to be found, so the game appears to just be frozen when in reality that popup is lingering around somewhere...so I'm force to close the game by pressing the steam button and hitting quit. The image below was taken in desktop mode, where I can actually see the confirmation...

### Examples

This is not something I've had to deal with in other emulators (other emulators just quit), but here's a picture of the confirmation pop up I'm talking about.

![img](https://github.com/PCSX2/pcsx2/assets/89402705/63b21fcb-c594-4ec3-ad65-56f99ec168c4)

**Comment by meiou5225** [comment]
Ah, thats what I get for not going through the settings lol. Thanks...works perfectly

**Comment by stenzek** [comment]
Or, y'know, use the big picture UI - it should be bound to escape by default, but you can use a button combination. No popup, and navigable by controller.
