### ISSUE TITLE
[BUG]: "View as Hex" does not work

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#9813]
### Describe the Bug

In debugger window, sometimes Registers viewer (`FPR` and `VU0f`) shows float decimals by default and "View as Hex" doesn't work.

### Reproduction Steps

1. Start PCSX2
2. Boot a game
3. Open debugger
4. Right-click `FPR` or `VU0f` viwer and hit "View as Hex"
5. But nothing happens

### Expected Behavior

"View as Hex" should work always.

### PCSX2 Revision

v1.7.4929

### Operating System

Windows 11

**Comment by Buzzardsoul** [comment]
It's working on my 1.7.4915. Not sure about latest though.

**Comment by F0bes** [comment]
I tried 1.7.4928 and built the latest PCSX2 locally (1.7.4932) on Windows 10. Both seem to be behaving normally.

**Comment by F0bes** [comment]
I'm wondering if it's due to the fact that a `1 bit` type doesn't exist on the cpu level and I haven't initialized those boolean values.
This could lead to a case where the booleans are something other than 1 or 0 🤨. I'll initialize them anyways because that's the right thing to do.
