### ISSUE TITLE
Naruto ultimate ninja 2 SPS

### ISSUE THREAD

**Issue by xXthecatXx** [PCSX2/pcsx2#9817]
### Describe the Bug

SPS in the character orochimaru

### Reproduction Steps

press back and circle near the character
https://github.com/PCSX2/pcsx2/assets/127200899/414d060f-8ff9-445b-b8c0-42926182612a

### PCSX2 Revision

PCSX2 Nightly - v1.7.4931

### Operating System

Windows 10 (64bit)

### CPU

i5 4690k

### GPU

gtx 1650

### Logs & Dumps

[Naruto - Ultimate Ninja 2_SLUS-21575_20230819212151.gs.zip](https://github.com/PCSX2/pcsx2/files/12386980/Naruto.-.Ultimate.Ninja.2_SLUS-21575_20230819212151.gs.zip)

[SLUS-21575 (D9D0E6DD).01.zip](https://github.com/PCSX2/pcsx2/files/12386984/SLUS-21575.D9D0E6DD.01.zip)

**Comment by RedDevilus** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/24227051/492939a6-3f2a-4073-8866-df4f6366543f)

**Comment by xXthecatXx** [comment]
this must be the same problem
![Speed_Racer_SLUS-21812_20230806230444](https://github.com/PCSX2/pcsx2/assets/127200899/02ca3e8f-8caa-46b1-95ac-3042c747413b)

https://github.com/PCSX2/pcsx2/assets/127200899/a3d94a79-ebb1-47d1-9d4a-554e22e7dfdd


[Speed_Racer_SLUS-21812_20230806230444.gs.zip](https://github.com/PCSX2/pcsx2/files/12398779/Speed_Racer_SLUS-21812_20230806230444.gs.zip)

**Comment by refractionpcsx2** [comment]
It isn't. Just because the symptom is "it's spikey" means absolutely nothing to the problem

**Comment by xXthecatXx** [comment]
I just remembered I had this gsump from this game and thought it was the same problem sorry.

**Comment by Goatman13** [comment]
Was it tested with XGKick sync gamefix? Interpreter sync by default if i understand correctly.

**Comment by refractionpcsx2** [comment]
> Was it tested with XGKick sync gamefix? Interpreter sync by default if i understand correctly.

yes, I tried everything. I think the problem is we're not clamping something on the VU1 JIT that it wants clamped, of course the interpreter clamps everything.

**Comment by Goatman13** [comment]
Works fine with VU1 extra clamping (both preserve sign,and not), but you need to disable gamefixes first, because... Game have VU0/1 no clamping in gamedb "# Fixes glow effects".  Per game settings can't overwrite it.

**Comment by refractionpcsx2** [comment]
Oh, goddamnit I'm such a derp.

**Comment by Goatman13** [comment]
Yeah. :D Anyway. I don't know this game too well, so i can't test if that break mentioned glow effect.

**Comment by refractionpcsx2** [comment]
If it's anything like the other narutos that need clamping, it might be that VU0 needs none clamping and VU1 needs Extra (+sign preferred)
