### ISSUE TITLE
[BUG]: MGS3: Subsistence text issues

### ISSUE THREAD

**Issue by tuantquy** [PCSX2/pcsx2#9818]
### Describe the Bug

![Metal Gear Solid 3 - Subsistence  Disc 1 of 3 _SLUS-21359_20230820180054](https://github.com/PCSX2/pcsx2/assets/138451202/d6b7ac88-fed6-4568-8b8a-6c84618c0c5c)

### Reproduction Steps

Play the game

### Expected Behavior

Dialogue in cutscenes have normal text but item/weapon text is not.

### PCSX2 Revision

1.7.4933

### Operating System

Windows 10 (64bit)

### CPU

i5-1035G1

### GPU

iGPU of the i5

### GS Window Screenshots

![Metal Gear Solid 3 - Subsistence  Disc 1 of 3 _SLUS-21359_20230820180054](https://github.com/PCSX2/pcsx2/assets/138451202/17d99f87-0e58-4b2f-a7b2-33049dcae25b)
![Metal Gear Solid 3 - Subsistence  Disc 1 of 3 _SLUS-21359_20230820180055](https://github.com/PCSX2/pcsx2/assets/138451202/b258553d-8218-4431-9d10-15a7e138492d)
![Metal Gear Solid 3 - Subsistence  Disc 1 of 3 _SLUS-21359_20230820180108](https://github.com/PCSX2/pcsx2/assets/138451202/cf1b32db-05bf-4a36-a547-6102f16564b3)

### Logs & Dumps

[MGS3Subsistence.zip](https://github.com/PCSX2/pcsx2/files/12388004/MGS3Subsistence.zip)

**Comment by bigol83** [comment]
Checked gsdump and can confirm it's an issue in both hardware and software renderers.

Also, checked Metal Gear Solid 3 base (not Subsistence) and **it doesn't have** this issue.

**Comment by Goatman13** [comment]
Difference between Subsistence and standard version is that Subsistence have Instant DMA hack enabled in game DB. Which is supposed to fix "missing letters in text such as E". Maybe something changed and that hack no longer work as expected for this game?

**Comment by bigol83** [comment]
Tried to check Instant DMA hack in Gamefixes to see if it actually corrupted letters like it happens in Subsistence, but i see no difference, no corruption.

**Comment by Buzzardsoul** [comment]
Does changing the EE's clock speed change anything?

**Comment by MrCK1** [comment]
To reproduce the text bug, you need to check the beginning area where you get the Thermal Goggles. If it is not working/disabled, it will look like this 

![image](https://github.com/PCSX2/pcsx2/assets/16314399/7de6fb94-0b09-46a6-a6ec-b867762dccb8)

**Comment by tuantquy** [comment]
I just reinstalled PCSX2 , reran Subsistence and it seems like it's fixed now somehow. So I think I
