### ISSUE TITLE
[BUG]: MYST 3 - Japan needs IPU patch

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9821]
### Describe the Bug

graphics are screwed up. 5chan requests fix.

### Reproduction Steps

just play game. 

### Expected Behavior

normal graphics.

### PCSX2 Revision

1.7.4933

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

**Comment by Buzzardsoul** [comment]
@seta-san Can you provide me with the elf file?

**Comment by Buzzardsoul** [comment]
> [SLPS_252.zip](https://github.com/PCSX2/pcsx2/files/12410744/SLPS_252.zip)

Seems that my conversion of the patch will work on it. Try it.

**Comment by seta-san** [comment]
it works

**Comment by F0bes** [comment]
What are you doing posting game ELFs on our GitHub? You know better than that.

**Comment by RedDevilus** [comment]
Homebrew elfs sure, not PS2 game elfs.

**Comment by F0bes** [comment]
Whether it be code, music, or artwork. It's all owned by their copyright holders.
