### ISSUE TITLE
[BUG]: Grandia Extreme SLPM65089 Extreme Flashing in opening

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9825]
### Describe the Bug

https://youtu.be/LxFN53AI0vA

### Reproduction Steps

start game

### Expected Behavior

title screen doesn't give you a seizure. 

### PCSX2 Revision

1.7.4933

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Grandia Xtreme_SLPM-65089_20230822091822.gs.zip](https://github.com/PCSX2/pcsx2/files/12409692/Grandia.Xtreme_SLPM-65089_20230822091822.gs.zip)

**Comment by Buzzardsoul** [comment]
Disable depth emulation fixes it.

**Comment by seta-san** [comment]
just changing the renderer or restarting the renderer by changing settings fixes it, even if you change the setting back

**Comment by Mrlinkwii** [comment]
can you check this on latest nightly for me

**Comment by seta-san** [comment]
seems to be fixed.
