### ISSUE TITLE
[BUG]: Growlanser 5 & 6 - Crashes after beginning a new game caused by #9713

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#9827]
### Describe the Bug

Since #9713 it doesn't seem possible to play Growlanser 5 or 6 on PCSX2 Nightly versions higher than `pcsx2-v1.7.4881-windows-x64-Qt`. The game crashes after you choose to start a new game (and some kind of character models appear? I'm not sure). The games are still not playable as of `pcsx2-v1.7.4933-windows-x64-Qt`.

I attached a GL5 US and GL6 JPN crash dump.

### Reproduction Steps

1. Download and extract `pcsx2-v1.7.4882-windows-x64-Qt` or the latest nightly version
2. Set language to English
3. Disable Automatic Update
4. Choose BIOS
5. Do not add a Game Folder
6. Start Growlanser 5 or 6
7. At the game's intro menu start a new game
8. Wait for it to crash

### Expected Behavior

Game doesn't crash.

### PCSX2 Revision

pcsx2-v1.7.4882-windows-x64-Qt and latest

### Operating System

Windows 11

### CPU

Ryzen 6900HX

### GPU

iGPU Radeon 680M

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

I renamed the .dmp files to .zip in order to upload them, just rename it back to .dmp.

[GL5US_crash-2023-08-22-20-41-12-183.txt](https://github.com/PCSX2/pcsx2/files/12411948/GL5US_crash-2023-08-22-20-41-12-183.txt)
[GL6JPN_crash-2023-08-22-20-32-01-838.dmp.zip](https://github.com/PCSX2/pcsx2/files/12411949/GL6JPN_crash-2023-08-22-20-32-01-838.dmp.zip)
[GL6JPN_crash-2023-08-22-20-32-01-838.txt](https://github.com/PCSX2/pcsx2/files/12411950/GL6JPN_crash-2023-08-22-20-32-01-838.txt)
[GL5US_crash-2023-08-22-20-41-12-183.dmp.zip](https://github.com/PCSX2/pcsx2/files/12411951/GL5US_crash-2023-08-22-20-41-12-183.dmp.zip)

**Comment by refractionpcsx2** [comment]
Can you provide crash dumps from the latest revision, please.

**Comment by refractionpcsx2** [comment]
Nevermind, I reproduced it.
