### ISSUE TITLE
Final Fantasy X core (?) bug in Kilika

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#983]
There's a small issue that I've noticed in Kilika. If you look closely at the provided screenshot, there's a part of untextured terrain showing up in there. It looks blue and it's down and to the right of Tidus. This doesn't happen on the PS2. I think it's a core bug because it happens on all of GSdx's renderers (D3D9, D3D11, OGL...hardware and software), as well as ZeroGS. It also happens on PCSX2 versions going as far back as 0.9.6.

At first I thought it was an issue with the widescreen patch since I've seen the issue happen before but on parts of the map that were clearly never supposed to be shown in a 4:3 aspect ratio (http://i.imgur.com/5CZ4nCC.png VS http://i.imgur.com/GH8i8Rn.png) so I turned off widescreen patches just in case.

Here's what it looks like in PCSX2:
![si1qet4](https://cloud.githubusercontent.com/assets/6857825/11254906/55e3269c-8e11-11e5-8a07-bc7df55cbb25.png)

Here's what it's supposed to look like:
![2015-11-18 10 33 34](https://cloud.githubusercontent.com/assets/6857825/11254851/0f96aec0-8e11-11e5-8bb7-00de9e0527cc.jpg)

Just for the lulz, here's what it looks like on PCSX2 0.9.6 using ZeroGS:
![fxi9xaz](https://cloud.githubusercontent.com/assets/6857825/11255630/45b74f1a-8e15-11e5-91dc-f18c2ac607b9.png)

**Comment by Sarania** [comment]
As we can see based on the last old ZeroGS picture, the small bug appears to be a complete gap in polys that is allowing the base color to show through. I'm guessing it's a precision issue in the GS core?

**Comment by FlatOutPS2** [comment]
This issue is still present in current latest git build, but I did notice something new.

The gap is larger when using the OpenGL Hardware renderer than any of the other rendererer(OGL SW, D3D9 SW & HW, D3D 11 HW & SW). The dark ground texture seems to move back when OGL HW is selected.

So it likely is a GSdx issue.

**Comment by refractionpcsx2** [comment]
Is this still an issue on latest dev builds?

**Comment by karasuhebi** [comment]
> Is this still an issue on latest dev builds?

I can test tonight and find out. I'll let you know.

**Comment by karasuhebi** [comment]
Yeah it's still there on the latest dev builds. I tested the latest one, 1.7.0-dev-685, using stock settings.

**Comment by refractionpcsx2** [comment]
Alright, thanks for testing anyways :)

**Comment by Lolibox** [comment]
Software mode's edge anti-aliasing fixes this, hardware mode has no equivalent. geometry appears to expand slightly when anti-aliasing is on.
![image](https://user-images.githubusercontent.com/49990481/111854277-b9785180-88f4-11eb-9285-e0bce00fc76b.png)
switch to software mode with f9 and press delete to toggle edge AA. tested on 1.7.0 dev 1803. I will check #3341 when i get there and update.
