### ISSUE TITLE
[BUG]: Wave Rally SLPS-20170 Crashes in opening video everytime

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9835]
### Describe the Bug

in the game's opening video the emulator freezes up before hard crashes to desktop without warning. This bug is skippable by just pressing the start button before the video crashes

### Reproduction Steps

start game and sit through videos

### Expected Behavior

emulator doesn't crash

### PCSX2 Revision

1.7.4940

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

https://ufile.io/c91xnzyq

**Comment by Mrlinkwii** [comment]
Duplicte of  #6909
