### ISSUE TITLE
[BUG]: Controller is not detected on first launch of the application

### ISSUE THREAD

**Issue by AleksandarBayrev** [PCSX2/pcsx2#9837]
### Describe the Bug

USB controller is not being detected on initial launch of the application, you have to unplug and plug it back in to work

before
![Screenshot from 2023-08-24 00-01-59](https://github.com/PCSX2/pcsx2/assets/15716076/a2ae4fc9-888e-4336-88d9-f01ff21d48a9)

after
![Screenshot from 2023-08-24 00-02-08](https://github.com/PCSX2/pcsx2/assets/15716076/7c036947-fa89-4044-9d8d-f3ce3666666a)

### Reproduction Steps

Connect the controller before launching PCSX2
Launch the app and observe if the controller is detected

### Expected Behavior

Controller is being detected on initial app launch

### PCSX2 Revision

v1.7.4939

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu 22.04.3 (flatpak version)

**Comment by stenzek** [comment]
Might be an SDL issue.

**Comment by AleksandarBayrev** [comment]
Great, how can this be solved? For example in duckstation I don't encounter this problem.

**Comment by stenzek** [comment]
DS uses an older version of SDL, it may be a new issue.

**Comment by stenzek** [comment]
Can't reproduce. Starting PCSX2 (latest flatpak) on Ubuntu 23.04:

![Screenshot_20230824_193520](https://github.com/PCSX2/pcsx2/assets/11288319/3f75d71d-cd6c-4f5e-84cb-0bac699782d3)

**Comment by AleksandarBayrev** [comment]
Interesting, I'll try later in a VM with 23.04 to see if it will do the job for me.

**Comment by Mrlinkwii** [comment]
@AleksandarBayrev  is this still an issue for you?

**Comment by kamfretoz** [comment]
@AleksandarBayrev can you specify what controller you use?

**Comment by AleksandarBayrev** [comment]
Hey, guys
Not anymore, forgot to update the ticket status.
