### ISSUE TITLE
[BUG]: Corrupted shader caches are not being invalidated

### ISSUE THREAD

**Issue by dio-gh** [PCSX2/pcsx2#9839]
### Describe the Bug

Last night a user on Discord (#help-windows) presented with [what appears to be a corrupted VK shader cache:](https://discord.com/channels/309643527816609793/315544036184293386/1144034531410722947)

```
[    7.3957] Opening GS...
[    7.6051] GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
[    7.6842] VK_EXT_provoking_vertex is supported
[    7.6842] VK_EXT_memory_budget is supported
[    7.6842] VK_EXT_calibrated_timestamps is supported
[    7.6843] VK_EXT_rasterization_order_attachment_access is NOT supported
[    7.6843] VK_EXT_attachment_feedback_loop_layout is NOT supported
[    7.6843] VK_EXT_full_screen_exclusive is supported
[    7.6843] VK_KHR_driver_properties is supported
[    7.6854] Read 33 entries from 'C:\Games\ps2\pcsx2-v1.7.4661-windows-64bit-Qt\cache\vulkan_shaders.idx'
[    7.8888] CompileShaderToSPV: Failed to link program, writing to C:\Games\ps2\pcsx2-v1.7.4661-windows-64bit-Qt\logs\pcsx2_bad_shader_1.txt
[    7.8899] ReportErrorAsync: GS: Failed to compile utility pipelines
[    7.8899] Failed to create GS device
[    7.9159] Skipping updating pipeline cache 'C:\Games\ps2\pcsx2-v1.7.4661-windows-64bit-Qt\cache\vulkan_pipelines.bin' due to no changes.
[    7.9385] ReportErrorAsync: Error: Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated.
[    7.9385] GS failed to open.
[    7.9385] Failed to open GS.
```

While I was unable to get them to actually remove their cache (it seemed from subsequent logs later that they failed to do so), a fresh install of PCSX2 worked for them, suggesting it was their shader cache that was indeed corrupted and causing an issue.

After looking into the issue a bit, it appears that it is possible for the shader cache to be loaded, despite the fact that whether SPIR-V code can be generated from it is only found out down the line whenever. In this specific case, it happened during this:

https://github.com/PCSX2/pcsx2/blob/b8cfd83d33b60bdc21e144df97ab0e53a0baf471/pcsx2/GS/Renderers/Vulkan/GSDeviceVK.cpp#L2094-L2099

To me this suggests that a corrupt shader cache can be loaded in, and whenever the way it is corrupt becomes problematic, then whatever tried relying on it will just die however it does. Therefore, checking for corruptions and invalidating the cache on load should be considered, so that it's not the support volunteers or the user who have to figure out that a cache refresh is necessary.

### Reproduction Steps

N/A

### Expected Behavior

Caches are tested for corruption on load, and are regenerated if they're found to be corrupted. Functions relying on the shader caches can then trust the cache to be valid, and won't fail by "chance" anymore.

### PCSX2 Revision

v1.7.4940

### Operating System

Windows 11

### Logs & Dumps

The user's [emulog (1).txt](https://github.com/PCSX2/pcsx2/files/12424237/emulog.1.txt).

Bad shader logs: 
[pcsx2_bad_shader_1.txt](https://github.com/PCSX2/pcsx2/files/12424240/pcsx2_bad_shader_1.txt)
[pcsx2_bad_shader_2.txt](https://github.com/PCSX2/pcsx2/files/12424241/pcsx2_bad_shader_2.txt)

**Comment by dio-gh** [comment]
> While I was unable to get them to actually remove their cache (it seemed from subsequent logs later that they failed to do so), a fresh install of PCSX2 worked for them, suggesting it was their shader cache that was indeed corrupted and causing an issue.

After thinking about what exactly may have went down on the user's end, I'm less confident about this analysis. Initially, they deleted the cache while PCSX2 was still running, so it is possible that there was a point where the log looked like this instead:

```
[    7.3957] Opening GS...
[    7.6051] GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
[    7.6842] VK_EXT_provoking_vertex is supported
[    7.6842] VK_EXT_memory_budget is supported
[    7.6842] VK_EXT_calibrated_timestamps is supported
[    7.6843] VK_EXT_rasterization_order_attachment_access is NOT supported
[    7.6843] VK_EXT_attachment_feedback_loop_layout is NOT supported
[    7.6843] VK_EXT_full_screen_exclusive is supported
[    7.6843] VK_KHR_driver_properties is supported
[    7.8888] CompileShaderToSPV: Failed to link program, writing to C:\Games\ps2\pcsx2-v1.7.4661-windows-64bit-Qt\logs\pcsx2_bad_shader_1.txt
[    7.8899] ReportErrorAsync: GS: Failed to compile utility pipelines
[    7.8899] Failed to create GS device
[    7.9159] Skipping updating pipeline cache 'C:\Games\ps2\pcsx2-v1.7.4661-windows-64bit-Qt\cache\vulkan_pipelines.bin' due to no changes.
[    7.9385] ReportErrorAsync: Error: Failed to create render device. This may be due to your GPU not supporting the chosen renderer (Vulkan), or because your graphics drivers need to be updated.
[    7.9385] GS failed to open.
[    7.9385] Failed to open GS.
```

This could happen if it's possible for PCSX2 to generate incorrect shader code, for example due to some edge case being hit in the post-processing infra.

I'm unable to confirm or rule out this theory however, as I'm not a graphics developer, so the badshader logs for me are not informative.

**Comment by stenzek** [comment]
This has nothing to do with the cache. User likely managed to use an old resources directory with a newer PCSX2 binary.

Cache stores SPIR-V programs and driver pipelines, linking happens before SPIR-V is produced.

**Comment by dio-gh** [comment]
> Cache stores SPIR-V programs

Right, this clears a lot up. So was the user's issue that they had outdated shaders in `\resources\shaders\vulkan`, and so when PCSX2 launched up those were not in cache, PCSX2 tried compiling them and adding them to the cache, and that failed to link?

**Comment by stenzek** [comment]
We don't differentiate between legitimate and modified resources. While we _could_ hash them and include the resulting hashes in the binary, I don't really see the need, at that point you may as well just embed the shaders in the binary in the first place. Which makes development slightly more annoying, because then you need to regenerate/recompile every time you change anything.

I don't see any issue here. If a user screws up their installation, that's on them, especially if they've gone out of their way to mismatch files.

**Comment by dio-gh** [comment]
I'm not per se invested in how you manage these resource files, my point was that this is nontrivial to diagnose when some rando pops in to the support channels.

**Comment by stenzek** [comment]
It was straightforward to me when I saw the log.

Again, if someone screws with an application's data files, they should expect it to break. That's the same of basically any application. Very few are self-healing/resilient.

Applying the next automatic update, or reinstalling would have fixed it anyway.

**Comment by dio-gh** [comment]
> It was straightforward to me

Alright.

**Comment by charlesthobe** [comment]
Oh I missed this one, this is nice :stuck_out_tongue:
