### ISSUE TITLE
[GSDX Hardware] Warship Gunner 2 Z ordering weirdness

### ISSUE THREAD

**Issue by disastranagant** [PCSX2/pcsx2#985]
Hardware GSDX renders background fog and underwater submarine deaths in front of everything else when they're supposed to be in the background.

Comparison screenshots: http://imgur.com/gallery/5F262/

**Comment by refractionpcsx2** [comment]
Can you take 2 screenshots the same distance from the land? You are much closer in the "software mode" shot. If you turn the engines right down that should keep you still while you take shots

**Comment by disastranagant** [comment]
http://imgur.com/gallery/pLLGR/

**Comment by refractionpcsx2** [comment]
Ok that's better though, it's much clearer to see the issue :)

**Comment by gregory38** [comment]
Might worth to test latest git

**Comment by disastranagant** [comment]
No change.

**Comment by disastranagant** [comment]
Actually.  Working fine with OpenGL.  D3D hardware modes no change.  Gonna test more, I recall OGL looking like shit last time I tried it.

**Comment by disastranagant** [comment]
Just noticed that D3D hardware modes are missing shadows.  Tried alpha and alpha stencil hacks and they're still missing. comparison screens: http://imgur.com/a/j7TkT

**Comment by disastranagant** [comment]
Video of OpenGL will be here soon https://youtu.be/yJ3DJjwKkD4

**Comment by gregory38** [comment]
D3D is dead. So gl is fine :)
