### ISSUE TITLE
[BUG]: McDonald's Original Happy Disc (SCPM-85101) graphical issues

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#9850]
### Describe the Bug

- PaRappa the Rapper 2
There is an black rectangle in top left screen.
HW:
![MCD_OHD_PTR2_HW](https://github.com/PCSX2/pcsx2/assets/121824800/190a1880-7fb1-4e53-bdba-7320b37d7a25)
SW:
![MCD_OHD_PTR2_SW](https://github.com/PCSX2/pcsx2/assets/121824800/345a044d-919f-480f-babb-ef5bf3c951d4)

- Pipo Saru 2001
Metal texture is different betweeen HW and SW.
HW:
![PS2001_HW](https://github.com/PCSX2/pcsx2/assets/121824800/7e84a5f7-555b-4683-a89c-bb57d9ca10e0)
SW:
![PS2001_SW](https://github.com/PCSX2/pcsx2/assets/121824800/edeef03a-398c-4b30-bbfd-3307f57346dc)

Several textures are different betweeen HW and SW.
Background buildings are a bit small in SW.

HW:
![PS2001_2_HW](https://github.com/PCSX2/pcsx2/assets/121824800/25967f09-0ace-4a4b-8d34-84d8b2065353)
SW:
![PS2001_2_SW](https://github.com/PCSX2/pcsx2/assets/121824800/65e1ba7a-c383-425e-b068-82097e163330)

### Reproduction Steps

Play the game.

### PCSX2 Revision

 v1.7.4944

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[MCD_OHD.zip](https://github.com/PCSX2/pcsx2/files/12443181/MCD_OHD.zip)

**Comment by Mrlinkwii** [comment]
PaRappa the Rapper 2  needs MTVU off and instant VU  off i think ,  how dose SW look in reference  to real hardware for ape escape ?

**Comment by SeruranBlue** [comment]
i gonna check in real hardware.

**Comment by SeruranBlue** [comment]
![Screenshot 2023-08-26 07-30-16](https://github.com/PCSX2/pcsx2/assets/121824800/5aa6e5c4-2ae2-440a-9989-a270fbf87f0b)
![Screenshot 2023-08-26 07-31-02](https://github.com/PCSX2/pcsx2/assets/121824800/70fc75ad-63a3-4c25-b7f1-4b9d1ed9004b)

**Comment by Mrlinkwii** [comment]
looks like HW  mode need what looks like  mippmaping and trilinerer  for ape escape

**Comment by SeruranBlue** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/121824800/4a566875-428a-4b54-ab45-4d7a0b9888a9)
parappa 2 looks good for MTVU off and instant VU off.
idk about "Warning" screen of ape escape, i tested mip mapping and trilinerer but none of them looks good

**Comment by Mrlinkwii** [comment]
re: ape escape , mip mapping:full  and trilinerer make it looks near enough SW in the  second picture , its about looking like SW , not about looking good

**Comment by LeWolfYT** [comment]
Instant VU turned off is default behavior for the final PTR2 build. Based on this, it should probably be made default for the demo.

**Comment by Mrlinkwii** [comment]
@LeWolfYT  due to theirs 2 games on the disc this cant be done currently :)
