### ISSUE TITLE
[Feature Request]: Window title includes a fixed text prefix/suffix, e.g. PCSX2

### ISSUE THREAD

**Issue by bigboss97** [PCSX2/pcsx2#9854]
### Description

It would be great if there a fixed text in the title. So I can switch the controller settings based on the active window.

### Reason

I'm using Keysticks to switch the gamepad control between applications based on the window title. Unfortunately, PCSX2 only shows the game name which changes for each game.

### Examples

PCSX2 - <game  name>
alternatively
<game name> - PCSX2

**Comment by stenzek** [comment]
I'm gonna say sorry, nope, for this one, not including PCSX2 in the title was a deliberate design decision on my part to keep the titles compact, and it's obvious it's PCSX2 based on the icon.

Any decent utility should be able to target the window based on process name, anyway.
