### ISSUE TITLE
[BUG]: Dirge of Cerberus - Final Fantasy VII_SLES-54185_20230829172946

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9873]
### Describe the Bug

En la captura que adjunto, se puede observar ese defecto grafico al fondo del escenario, pero que afecta a todo el escenario.
![Dirge of Cerberus - Final Fantasy VII_SLES-54185_20230829172946](https://github.com/PCSX2/pcsx2/assets/142044650/f93b0d88-7915-4d23-ac23-dde01b0153b2)

### Reproduction Steps

Iniciar el juego, esto empieza a ocurrir al inicio segun empiezas a jugar y tienes el control de tu personaje.

### PCSX2 Revision

v1.7.4965

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by refractionpcsx2** [comment]
Can you make your post English please.

Also can you post a GS dump?

**Comment by Parallax71** [comment]
> Can you make your post English please.
> 
> Also can you post a GS dump?

ok, sorry, Here I leave what you asked me, thank you. (Sorry for my english, I use google translate)

[Dirge of Cerberus - Final Fantasy VII_SLES-54185_20230829192509.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12467589/Dirge.of.Cerberus.-.Final.Fantasy.VII_SLES-54185_20230829192509.gs.zst.zip)
![Dirge of Cerberus - Final Fantasy VII_SLES-54185_20230829192509](https://github.com/PCSX2/pcsx2/assets/142044650/a04d9dcd-9ca0-41a4-a619-d89d9ff75cc9)

**Comment by refractionpcsx2** [comment]
This was broken in #8961

Hopefully won't be too bad to fix, need to investigate.

**Comment by refractionpcsx2** [comment]
So took a quick look at this, it does a strange clear where it does half the screen each at a strange size, but it's a non-zero clear too.

So yeah it's pretty annoying, no idea how this ever worked, probably by luck, or badly.
[00002_context.txt](https://github.com/PCSX2/pcsx2/files/12468126/00002_context.txt)
[00002_vertex.txt](https://github.com/PCSX2/pcsx2/files/12468127/00002_vertex.txt)

**Comment by Parallax71** [comment]
fantastic, now it plays perfectly, thank you very much for the work done. All the best.
