### ISSUE TITLE
[BUG]: Guitar mapping not working properly

### ISSUE THREAD

**Issue by Sonny35** [PCSX2/pcsx2#9877]
### Describe the Bug

When configuring the buttons they are not assigned to the button they should. The button set to BLUE presses the ORANGE button in the game, and the one set to GREEN presses the BLUE in the game. Almost none of the rest of the buttons work.
![image](https://github.com/PCSX2/pcsx2/assets/9279268/5c824c2a-42e6-442b-bd0b-aa26bcd865e6)

### Reproduction Steps

Set up the guitar and test the buttons.

### Expected Behavior

That the buttons work as you have configured them.

### PCSX2 Revision

v1.7.4965 Nightly

### Operating System

Windows 10 (64bit)

**Comment by Parallax71** [comment]
¿Que modelo de guitarra usas?, ¿tipo de adaptador?, yo estoy usando la guitarra oficial del Guitar Hero Warriors of Rock de PS2 con el adaptador  [https://www.amazon.es/Conversor-para-Conectar-Mandos-PS1/dp/B00K55HEMW/ref=sr_1_13?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1GDG2LV0NNZTK&keywords=adaptador+ps2+a+usb&qid=1693412830&sprefix=adaptador+ps2+a+usb%2Caps%2C103&sr=8-13](url)  y funciona correctamente

**Comment by Sonny35** [comment]
Tengo dos adaptadores y con los dos funciona todo bien excepto el vibrato, y la guitarra que uso es la del 3.
De todas formas eso no parece ser el problema, ya que si mapeo contra el teclado sigue haciendo lo mismo...
Es raro porque cada vez que mapeo todos los botones cambia, como si se asignasen aleatoriamente.

**Comment by Parallax71** [comment]
> Tengo dos adaptadores y con los dos funciona todo bien excepto el vibrato, y la guitarra que uso es la del 3. De todas formas eso no parece ser el problema, ya que si mapeo contra el teclado sigue haciendo lo mismo... Es raro porque cada vez que mapeo todos los botones cambia, como si se asignasen aleatoriamente.

me pillas justo delante del PC y emulador, voy a coger la guitarra, lo pruebo ahora mismo y te digo.

**Comment by Parallax71** [comment]
![cguitarra](https://github.com/PCSX2/pcsx2/assets/142044650/06ed7912-f4c9-4647-aad2-42e946f8f3d6)

**Comment by Parallax71** [comment]
pues me lo detecta todo perfectamente, salvo como dices la barra de tremolo (pero eso es debido al adaptador, ya que en el Clone Hero me ocurre lo mismo), lo que he hecho ha sido darle a "Asignacion automatica" y luego en los botones de colores ir haciendo "click" en ellos y pulsando el color correspondiente en la guitarra y todo perfecto, lo he probado varias veces, sin problema.

**Comment by Sonny35** [comment]
Estaba probando con el II en español (SLES-54442), es el mismo juego que utilizo yo desde hace años en consola, hice la iso de mi propio disco y en consola va bien, pero no tengo otro juego con el que probarlo ahora mismo la verdad

**Comment by Sonny35** [comment]
He hecho lo mismo que tu, asignación automática y es que parece que los botones se ajusten aleatoriamente, ahora mismo me funciona el botón verde y rojo (aceptar y cancelar) pero no me puedo mover arriba y abajo, no se, pero con el teclado me pasa exactamente lo mismo... y si intento poner a mano la cuerda (arriba y abajo) es como que se queda enganchado y se mueve infinitamente arriba... no lo se, se vuelve loco XD

**Comment by Sonny35** [comment]
Ahora mismo lo que me pasa (tanto en la guitarra como en el teclado) es que hace clic infinitamente hacia abajo y el menú se vuelve loco... es que cada vez que pruebo de configurar la guitarra hace algo diferente, y no tengo ni idea de lo que puede ser, ayer arriba/abajo funcionaba bien y los botones se cruzaban entre ellos, y hoy los botones parece que funcionan pero la palanca no, no entiendo nada

**Comment by Parallax71** [comment]
hola, pues siento decirte que a mi no me ocurre nada de eso que comentas, me va perfecto todo, he probado 3 guitar hero (metallica, Guitar Hero III y Warriors of Rock), tambien he salido y he vuelto a entrar en el emulador y me ha guardado los cambios cuando he asignado los botones y tal, o sea, todo correcto, no se que mas decirte compi, lo siento.

**Comment by Sonny35** [comment]
No te preogupes, gracias igualmente.
De hecho así haciendo purebas tal y como me funciona ahora puedo llegar a jugar si no configuro la cuerda hacia arriba y siempre pulso abajo, parece que ahora mismo funciona todo bien excepto la cuerda arriba, que si la configuro el juego se vuelve loco... pero almenos ahora mismo es jugable, siempre y cuando no me vuelva al mismo error que ayer T_T

Gracias por toda la ayuda igualmente!

**Comment by Parallax71** [comment]
por cierto, lo mejor que hay para aprovechar tu guitarra del Guitar Hero es el programa totalmente gratuito llamado CLONE HERO, es brutalísimo, 200% recomendado

**Comment by Sonny35** [comment]
> creo (estoy bastante convencido) a que lo de la cuerda "arriba" es porque no tienes "zona muerta" en el pulsador, por eso al mas minimo "toque" e incluso sin tocar "detecta" que has pulsado dicho boton, ya que ese pulsador "arriba - abajo" lo detecta como si fuese un "stick" analogico y por eso "cree" que estás pulsando en esa dirección. La solucion aunque parezca complicada... no lo es, desmonta la guitarra, son pocos tornillos, abrela y limpia los contactos del pulsador, y mira si el muelle que tiene para que vuelva al centro está estirado/deformado, solo lo tienes que ajustar volviendolo a "juntar" un poco y listos, en serio, no es complicado, es muy muy facil y estoy seguro al 100% de que es eso, o tienes los contactos "sucios"... o esa "palanca" está "desviada" hacia arriba y por eso hace contacto "sola".

De hecho lo hice hace poco porque al volver a coger la guitarra me la encontré con las pilas sulfatadas y tuve que limpiarla por dentro, pero insisto que ese no es el problema porque al configurarla en el teclado del pc me hace exactamente lo mismo, y cuando pruebo la guitarra con la herramienta de mandos de windows lo reconoce todo perfectamente.

Respecto a lo del clone hero me lo miraré, porque ya había escuchado hablar de eso pero nunca me decidí a ponerlo, gracias!

**Comment by refractionpcsx2** [comment]
Can we keep it English on here please (or at least BOTH translations), speaking in Spansih is no use to us, we can't understand it.

**Comment by Parallax71** [comment]
I spoke to him in Spanish because the user was Spanish, just that. It won't happen again, sorry.

**Comment by refractionpcsx2** [comment]
I understand that, but this github is run mostly by people who don't, apart from speaking in another language makes moderation difficult for us, it also doesn't help us fix any potential problems.

All I ask is you at very least provide an English translation, but if it is a support thing, it should be taken to Discord or the forums, as this tracker is for confirmed bugs or issues.

**Comment by Parallax71** [comment]
ok, ok, The fault above all has been mine, I have never used this platform except in the 3 or 4 bug reports of PCSX2 without knowing how all this works, as I said, my fault. The BUG that the colleague mentioned about PCSX2 in the end was not a failure of the program, but of its peripheral, that is what we have come to.

**Comment by stenzek** [comment]
Works fine as far as I can tell.
