### ISSUE TITLE
[BUG]: SLUS-20134 Sky Odyssey - Minimap Runway Rendering Issue

### ISSUE THREAD

**Issue by dojima** [PCSX2/pcsx2#9878]
### Describe the Bug

As you move further away from a runway, its appearance on the minimap becomes distorted.

### Reproduction Steps

1. Start any level
2. Fly away from the runway

### Expected Behavior

Runway appearance should remain identical regardless of distance.

### PCSX2 Revision

v1.7.4964

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

GTX 1660 Super

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/8037372/948b02f6-205d-4769-bb87-6cbc2db20f4f)

The runway is depicted as the distorted orange line toward the bottom of the minimap.  This YouTube video (https://youtu.be/ZoocnxvVxIk?&t=168) demonstrates how the runaway ought to render.  And as demonstrated by this video (https://youtu.be/GKAYp59YtFY?&t=322), it used to render correctly in `v1.5.0-dev-2243-g74282b46f`.

### Logs & Dumps

[sky_odyssey_runway_bug.zip](https://github.com/PCSX2/pcsx2/files/12471488/sky_odyssey_runway_bug.zip)

**Comment by stenzek** [comment]
Post a GS dump.
Also try mipmapping.

**Comment by dojima** [comment]
Updated post with dump.  No graphical options I've tried make any difference, including software renderer or mipmap settings.  Also happens regardless of internal resolution or window size.

**Comment by stenzek** [comment]
It being broken in software is pretty concerning. Unfortunately a bisect to 1.5 is the opposite of helpful, need to be much more specific.

**Comment by stenzek** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/11288319/320f3ede-a79a-4b22-aee7-11d20fe7a949)

If I had to guess, I'd say it's relying on the fact that the GS will fill at least one pixel per scanline. Surprising that this doesn't happen in software.

**Comment by refractionpcsx2** [comment]
I ran the dump on my PS2, and it looks broken there too

**Comment by dojima** [comment]
I believe my first video link is from actual hardware.  I own the game myself and could verify if necessary as well.  There also seems to be a point where it goes from being rendered correctly to being drawn incorrectly, so if a multi-frame dump would help, I could try that also.

**Comment by refractionpcsx2** [comment]
Okay problem is located, as I suspected, it was a core issue. I'm just about to PR a fix, which will close this issue once it merges :)
