### ISSUE TITLE
[Feature Request]: Add abilty to clear pergame settings in the QT menu, not just the Big Picture mode.

### ISSUE THREAD

**Issue by Bitwolfies** [PCSX2/pcsx2#9881]
### Description

If you've added custom settings to a game, you should be able to right click it and discard those settings to revert the game to following the default. Which you totally can do in Big Picture mode. 
![Screenshot_20230830_020122](https://github.com/PCSX2/pcsx2/assets/65789901/1d4c24c9-0e0f-47c0-80fa-6063a04976ad)
Though, as far as I can tell, doesn't exist in the QT ui.

### Reason

Makes sense to have it on the main ui and not just the ingame one.

### Examples

Big Picture mode.

**Comment by bigol83** [comment]
This would be great, i agree.
