### ISSUE TITLE
[BUG]: Taiko no Tatsujin (Drum Master) - Intro Video Invisible in D3D12 and Vulkan.

### ISSUE THREAD

**Issue by JWatersMeet** [PCSX2/pcsx2#9883]
### Describe the Bug

When starting Taiko no Tatsujin (Drum Master) - SLPS2022-1, the Into Video plays only when using Software rendering, and is invisible when using D3D12 or Vulkan rendering.
Strangely enough, switching to software mode while the intro is playing, and then back to D2D12 or Vulkan results in the video displaying normally.

https://github.com/PCSX2/pcsx2/assets/136824455/98e11a7d-a058-4c07-9964-482026c925a3

### Reproduction Steps

1. Set D3D12 or Vulkan renderer.
2. Start Taiko no Tatsujin (SLPS2022-1)
3. Note intro video is missing (black screen, music plays)
4. Switch to software mode while video is playing
5. Video appears
6. Switch back to D3D12 or Vulkan
7. Video remains working correctly.

### Expected Behavior

Video should be visible on D3D12 or Vulkan when selected as the startup renderer.

### PCSX2 Revision

1.7.4967

### Operating System

Windows 11

### CPU

Ryzen 5900 HX

### GPU

Integrated Radeon

**Comment by kamfretoz** [comment]
> This was working correctly around 1-2 weeks ago.

Can you try and bisect the exact version where it stops working?

**Comment by JWatersMeet** [comment]
Sure, works in 4942, broken in 4943, possibly the invalidation rewrite.

**Comment by kamfretoz** [comment]
Yep so it is regression from #9315
