### ISSUE TITLE
[BUG]: Counter Terrorist Special Forces - Fire for Effect SLES-53046

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9885]
### Describe the Bug

As can be seen in the screenshot, the smoke is not represented well, since it is represented with a geometric figure, it happens with all renderers (Vulkan, D3D11, OpenGL) and even with softare mode (which does not show those figures but this smoke is not well represented either)
<img width="862" alt="Counter Terrorist Special Forces - Fire for Effect_SLES-53046_20230830191338" src="https://github.com/PCSX2/pcsx2/assets/142044650/a0b3082a-22fd-4945-a694-685eea9d443f">

### Reproduction Steps

You just have to start the game and play the first mission that is like a tutorial

### PCSX2 Revision

v1.7.4967

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by Parallax71** [comment]
[Counter Terrorist Special Forces - Fire for Effect_SLES-53046_20230830191338.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12478532/Counter.Terrorist.Special.Forces.-.Fire.for.Effect_SLES-53046_20230830191338.gs.zst.zip)

**Comment by Buzzardsoul** [comment]
@Mrlinkwii Only needs vu1 clamping extra. Not a gs issue.

![image](https://github.com/PCSX2/pcsx2/assets/126727903/da2ee9ba-1200-4eeb-a4dc-e7e47d2de37b)

**Comment by Parallax71** [comment]
> @Mrlinkwii Only needs vu1 clamping extra. Not a gs issue.
> 
> ![image](https://user-images.githubusercontent.com/126727903/265852712-da2ee9ba-1200-4eeb-a4dc-e7e47d2de37b.png)

Hello, is there any option within the emulator that I can activate or whatever I need? thank you

**Comment by Buzzardsoul** [comment]
1: Tools > Show Advanced Settings
2: Run the game, then click on settings > game properties > advanced > and then set vu1 clamping mode to extra

**Comment by refractionpcsx2** [comment]
we'll get it added to the gamedb so it'll be automatic

**Comment by Parallax71** [comment]
ok, I found it, (VU1 is in the advanced options, be careful not to touch things there), it is now solved, thank you very much. By the way, to obtain a much more fluid game without input lag, I modified the PAL frequency from 50Hz to 59.94Hz in the same options section, so the game runs very fluid all the time. Greetings and I close this matter.

**Comment by Mrlinkwii** [comment]
im gonna reopen the issue , this needs to be added to the gameDB
