### ISSUE TITLE
[BUG]: The Getaway 2 progressive scan mode is broken

### ISSUE THREAD

**Issue by EnekoT2001** [PCSX2/pcsx2#9889]
### Describe the Bug

When setting the screen mode to progressive in any of the PAL versions (NTSC doesn't have options to change screen modes), the screen shows two images misaligned (check screenshot)

### Reproduction Steps

Load version 1.00, 1.03, 2.03 or 3.00 of the PAL game, go to options > screen and set mode to progressive

### Expected Behavior

Should look normal

### PCSX2 Revision

v1.7.4967

### Operating System

Windows 11

### CPU

Ryzen 7 3800X

### GPU

GTX 1050ti

### GS Settings

I tried with Vulkan, OGL, D3D11 and D3D12 at 1x-6x resolution, also tried software renderer, all show the same issue in the exact same way

### GS Window Screenshots

![Getaway, The_SCES-51159_20230831004407](https://github.com/PCSX2/pcsx2/assets/42989949/81fec7eb-10f7-4248-95f5-cfc7f8191bef)

### Logs & Dumps

[Getaway, The_SCES-51159_20230831004407.zip](https://github.com/PCSX2/pcsx2/files/12480719/Getaway.The_SCES-51159_20230831004407.zip)

**Comment by lightningterror** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/3381

**Comment by EnekoT2001** [comment]
oh sorry i didnt see this was already reported, i tried searching but it was at the end. so sorry
