### ISSUE TITLE
Have ISO loaded, then load ELF file

### ISSUE THREAD

**Issue by NJW1979** [PCSX2/pcsx2#9890]
### Description

On older versions of PCSX2, I could have an ISO loaded, without running the game, and then load the codebreaker ELF file, so I could select the cheats for the game and launch the game via the ELF file, so I could cheat.  This is not possible on the latest dev build.  Also, the latest dev build has no cheats section, like the PS1 emulator I use, DuckStation.  This means there is no possible way of using cheats on any PS2 game.  I have nerve damage and a brain injury, so I need to cheat so I don't die a couple of seconds into the game.  Can you either allow users to have an ISO selected, but not running and then allow them to load the ELF file, and launch the game from the ELF, or have a cheats section with a cheats database in the next release?

### Reason

This will allow me to play PS2 games.  I need to cheat to be able to play due to nerve damage and a brain injury.

### Examples

DuckStation has a cheat section and a cheat manager that allows me to add cheats manually from text if no cheat for that game is in the database.

Older versions of PCSX2 allow me to have an ISO selected, then allow me to load the codebreaker ELF file, from where I can select the game, select the cheats, and then launch the game from within the ELF.  Although I can launch the ELF in the latest dev build of PCSX2, I can't launch the game as the ISO isn't selected and it's not possible to select it in the way that was possible with PCSX2 v1.6.0.to

**Comment by refractionpcsx2** [comment]
There is a cheat section, right click the game and go to properties, then cheats.

You can also link ELF files to ISO's, but I forget how to do it.

**Comment by refractionpcsx2** [comment]
anyway, I think you can already do everything you're asking, I suggest you visit the discord if you need help setting it up.

**Comment by stenzek** [comment]
Game properties on the elf, and there's a iso mounting option.
