### ISSUE TITLE
[BUG]: freezes on games pcsx2

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9891]
### Describe the Bug

It happens to me in all games, only that in some games it happens at the beginning of putting them on and others while you're playing them, it doesn't always happen in the same place, it's like something "random", but it always happens, sooner or later, I don't know what It may be, I have restored the emulator values ​​to default but it still happens. I'm not sure if it's the fault of the emulator or the emulated games. I've been noticing this problem since v1.7.4856 approximately, only now it happens more often.

### Reproduction Steps

Reproducing the bug is difficult as it is random

### PCSX2 Revision

v1.7.4972

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by refractionpcsx2** [comment]
This sounds more like a support problem, unless you can be certain it's a problem caused by PCSX2. Please join our discord and discuss it in the help channels, the github isn't really designed for that.

Thanks.
