### ISSUE TITLE
[BUG]: Cannot access advanced settings in game properties in big picture mode

### ISSUE THREAD

**Issue by reece-bennett** [PCSX2/pcsx2#9892]
### Describe the Bug

In non big picture mode I can right click a game > Properties... > Advanced and set advanced options on a per-game basis. The advanced menu option is missing from the game properties menu in big picture mode. It can be opened in the main global settings menu but not on a per-game basis.

Non big picture has advanced on the game properties:

![Screenshot 2023-08-31 161532](https://github.com/PCSX2/pcsx2/assets/6674785/d8f5bdb7-758e-4dcd-9255-b054770d4fb1)

Big picture main settings has advanced:

![Screenshot 2023-08-31 161648](https://github.com/PCSX2/pcsx2/assets/6674785/54eb86d0-f83e-4f48-89d4-b5aaeab10f97)

Big picture game properties does not have advanced:

![Screenshot 2023-08-31 161625](https://github.com/PCSX2/pcsx2/assets/6674785/3696c931-0d52-46a4-93ba-efb5b3c93ca4)

### Reproduction Steps

1. Start big picture mode
2. Go to game list
3. Right click game tile
4. Open game properties
5. There is no option to open the advanced settings menu

### PCSX2 Revision

v1.7.4972

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Kinda working as intended. There isn't anything in advanced you should be overriding as a user.

**Comment by reece-bennett** [comment]
Toggling EE clamping is needed to be toggled on/off I'm Gran Turismo 4 depending on the part of game that is being played as per https://github.com/PCSX2/pcsx2/issues/9663#issuecomment-1656537129 and that setting now lives in the advanced menu. 

Having it available in big picture game options would mean I can toggle it for Gran Turismo 4 without messing up other games that don't need it.

**Comment by stenzek** [comment]
Not worthwhile just for one game, especially when the main UI still lets you do it.

The advanced section isn't meant to be visible in the first place.
