### ISSUE TITLE
[BUG]: Setting sticks as pads doesn't work correctly 

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9896]
### Describe the Bug

In games like Street Fighter EX3, Turok Evolution or the Tekken series for example, you cannot play with the sticks, and even if you redefine the up, down, left and right of the pad to do it with the analog sticks... it does not work correctly, I have I have tried modifying the sensitivity or dead zone values ​​of the analog sticks but there is no change and the aforementioned games go crazy when moving through the menus or trying to play, is this something that is not implemented correctly yet?. I am using a brand new XBOX ONE controller, working perfectly with those games that do not need to redefine the sticks.

### Reproduction Steps

Start any game mentioned above, and redefine the analog sticks as clickable directional buttons, or have created a control profile and select it in the games

### Expected Behavior

I expected a normal response once the controls were redefined, but that was not the case, I think it is a bug in the emulator of something that will be in development or not fully implemented.

### PCSX2 Revision

v1.7.4974

### Operating System

Windows 10 (64bit)

**Comment by DigitalMajestic** [comment]
This works as expected/as intended for other users so I believe there’s no bugs involved. This sounds like a support issue, please join the discord or forums for help.

**Comment by Mrlinkwii** [comment]
you need to set a deadzone like .02

**Comment by stenzek** [comment]
It works fine. You need to set a deadzone on the buttons, because any non-zero axis value will set the button as "active" in the bitset (most games use that, not the pressure).

Both the button deadzone setting, or setting a per-bind deadzone (shift-click the binding) works.
