### ISSUE TITLE
[BUG]: Xenosaga Episode II - Unable to Rematch Patriarch

### ISSUE THREAD

**Issue by NijikawaSatoki** [PCSX2/pcsx2#9910]
### Describe the Bug

There seems to be an emulation error when trying to move the large cube platform at the end of the Omega System to rematch the Patriarch during the post-game.
I move the party leader as close to the platform controls as I possibly can, and press [CIRCLE] at every conceivable angle, and no response. When attempted on original hardware, the platform controls work as expected.
Note: This is using the NTSC-J version of the game.

Additional notes: I also checked around to see if anyone else had this issue, and have come up empty-handed (or Google was being useless, which wouldn't surprise me).

### Reproduction Steps

1. Complete the game as usual.
2. Save your clear file.
3. Load your clear file.
4. Get to the large cube platform at the end of the Omega System.
5. Attempt to use the platform controls.

### Expected Behavior

Expected behavior: When the platform controls are interacted with, the dialog asking the player if they wish to move the platform should appear.

Actual behavior: Interacting with the platform controls do nothing.

### PCSX2 Revision

PCSX2 Nightly v1.7.4984

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz

### GPU

NVIDIA GeForce GTX 1650

**Comment by Buzzardsoul** [comment]
Save states can help. Meanwhile, try different clamping/rounding modes and see if it works then.

**Comment by NijikawaSatoki** [comment]
So... I just finished trying every conceivable setting regarding clamping and rounding modes (the ones under 'Advanced' in the Settings, right?) and even that's coming up empty-handed...

I have provided the save state (I think this is how it's done, right?). It was made at the final save point inside the Omega System. (This save state was made using the Japanese (NTSC-J) version, so to my knowledge it will not work with the North American (NTSC-U) version)
[XenosagaEpisode2_NTSC-J_SaveState.zip](https://github.com/PCSX2/pcsx2/files/12533552/XenosagaEpisode2_NTSC-J_SaveState.zip)

**Comment by Buzzardsoul** [comment]
Something tells me it's not a PCSX2 issue. I've tried everything too. Did you try using this very save on the original PS2? Or was it a different save?

**Comment by NijikawaSatoki** [comment]
The save that state is from originates from one I've been playing on stream. I do have another save where I also beat the game, albeit one where I did the Cathedral Skip prior to post-game. The stream save is one where I didn't do that particular trick (figuring it could cause potential problems and headaches)

Although, now that you do mention it, it is also making me wonder if that was only a thing added for the North American version (Since that version also did add 3 additional superbosses for some reason).
I'll dump the North American version as well and see if this happens with that version as well.
But I'll take care of that after my stream tonight. But if it does turn out that refighting the Patriarch after beating the game is NTSC-U exclusive, then that would be quite conclusive.

**Comment by Buzzardsoul** [comment]
@NijikawaSatoki Any update?

**Comment by Buzzardsoul** [comment]
I have tested it using your save on my PS2 and the game is working just as it does on PCSX2. So it's either your save has a problem, or you confused this normal behavior as an issue.
