### ISSUE TITLE
[BUG]: Densha de Go! Professional 2 | black stripes in menu

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#9913]
### Describe the Bug

HW:
![Densha de Go! Professional 2_SLPM-65243_20230906194751](https://github.com/PCSX2/pcsx2/assets/121824800/ae86dbba-8878-4376-81df-f5df79e12101)

SW:
![Densha de Go! Professional 2_SLPM-65243_20230906194759](https://github.com/PCSX2/pcsx2/assets/121824800/c8ac6a33-625a-43f0-979a-b9e972d745bc)

### Reproduction Steps

Boot up the game and press start button in title screen.

### PCSX2 Revision

 v1.7.4984

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[Densha de Go! Professional 2_SLPM-65243_20230906194751.gs.zip](https://github.com/PCSX2/pcsx2/files/12536488/Densha.de.Go.Professional.2_SLPM-65243_20230906194751.gs.zip)

**Comment by Mrlinkwii** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/17685135/e09bae99-5bb4-4551-b986-4dccf0f92718)
seems to be mostly fixed as of v1.7.5236, apart from a  small stripe fropm the top

**Comment by lightningterror** [comment]
Hw and sw look identical now.
