### ISSUE TITLE
[BUG]: Ver 1.7.4694 on MacOs, crashes shortly after launch or whenever action is done

### ISSUE THREAD

**Issue by MajmunX** [PCSX2/pcsx2#9915]
### Describe the Bug

I updated nightly  frequently, and then after one update. the app crashed either shortly after opening, or whenever I launch any game or even go in the menus

I forgot which one I had working correctly so,  traced back the updates I missed, and the last working version was 1.7.4693

It crashes on 1.7.4694, I looked at the dev changelog and it says " changes to SDL", which I assume this is controllers? 

I disconnected the controller PS3 Dual shock, and it did not crash, I unchecked the SDL option, and it works but obviously the controller does not anymore, whenever I connect it, it crashes again

I tried earlier versions, all worked, but anything later than 1.7.4694 crashes as I described, I'll attached the crash log.

### Reproduction Steps

Download 1.7.4693, and 1.7.4694 on Mac mini 2012 model

One will work as expected with ps3 controller, the later one will crash whenever just opened or when doing almost any action with the app (opening games, settings, etc...), it does not crash when SDL is unchecked or controller disconnected.

I am on MacOS, OCLP running Big Sur, Latest update 11.7.9
On a an i7 Mac mini 2012 16Gb Ram 1 TB SSD, Using Dual Shock 3 PS3 controllers

### Expected Behavior

Expected the emulator to work with the ps3 dualshock bluetooth controller

### PCSX2 Revision

1.7.4694

### Operating System

MacOS BigSur 

### Logs & Dumps

[log .docx](https://github.com/PCSX2/pcsx2/files/12540689/log.docx)

**Comment by stenzek** [comment]
Please post the full crash report.

**Comment by stenzek** [comment]
Okay, apparently it's just a docx.

That crash report does not match what you're describing. It shows the main thread with a slider being moved, and a game in the middle of booting.

Also a little suspicious of a hacked up system, since 2012 Mac Minis do not support Big Sur, perhaps that's the cause of the memory corruption... that or it's the double connection event issue which I forgot to PR a workaround for.

**Comment by stenzek** [comment]
So the version you linked is just the bump to the SDL version. So presumably it's an issue within SDL.

But I can't reproduce it on my system (M2 Pro). Running with asan on showed no errors either.

Best I can do is guess it's related to the MFI issue, which I'm working around in #9918, but otherwise no idea what's going on.

**Comment by TellowKrinkle** [comment]
If that doesn't fix it, could you join our Discord for further debugging?  You can ping me in the help-unix channel.

**Comment by MajmunX** [comment]
> Okay, apparently it's just a docx.
> 
> That crash report does not match what you're describing. It shows the main thread with a slider being moved, and a game in the middle of booting.
> 
> Also a little suspicious of a hacked up system, since 2012 Mac Minis do not support Big Sur, perhaps that's the cause of the memory corruption... that or it's the double connection event issue which I forgot to PR a workaround for.

Sorry I am new to all this. I just copied the crash report into a docx and uploaded.

My 2012 Mac mini is running Big Sure on OCLP, open core legacy patcher, it just makes it possible for unsupported Macs to install current versions of MacOs. I have no issues with PCSX2 or any other app because of it, I dunno about the memory corruption, if that is how it shows in the crash but I have tested it in this manner:

1) I downloaded like 20 versions after the one with DSL patch and they crash every time, My Dual Shock PS3 was always connected via bluetooth during testing. 
2) I tested downwards from a recent version. I came closer to the last working version I had all with crashes.  started testing upwards, until reached the one with the DSL, and the one before it that worked before the DSL update. 
3) since I know DSL has to do with controllers, I simply disconnected the controller, removed the ENABLE DSL option, and it did not crash. I started a couple of games, and worked fine, but I have no controller connected 
4) I downloaded a few later versions, they worked without the controller
5) I connected the controller while in game, it hung up then crashed.

I have not other controllers to test,

Let me try it a few more times, with various versions and upload other crash reports. 
I also have a 2014 Mac book Air running stock supported Mojave with no Open Core Patcher, , I will install PCSX2 there and try with those two versions using the same controller.

**Comment by stenzek** [comment]
I checked DS4 and DS5 via both wired and bluetooth on Ventura, no issues.

So it's either an SDL issue specific to DS3, or something to do with the older MacOS version. Downgrading SDL isn't really an option for us, so I'd suggest taking Tellow up on the offer above, and perhaps we can get whatever the issue is reported upstream to SDL.

**Comment by MajmunX** [comment]
I tried again with the version you built  v1.7.4986, same thing, crashes if the controller is connected, or if connected mid game, but works fine without it. Also seems those versions removed VULKAN from my options haha. I'll probably stick to the old working version then :)

Sure I took some screenvids, and saved a few more reports,  dunno if would be helpful; and would be happy to do some testing, I'll checkout discord and send to Tellow

**Comment by MajmunX** [comment]
> I checked DS4 and DS5 via both wired and bluetooth on Ventura, no issues.
> 
> So it's either an SDL issue specific to DS3, or something to do with the older MacOS version. Downgrading SDL isn't really an option for us, so I'd suggest taking Tellow up on the offer above, and perhaps we can get whatever the issue is reported upstream to SDL.

Also thanks a lot for the promptness and everything!

**Comment by stenzek** [comment]
Vulkan is disabled on the CI builds because MoltenVK does not support the required extensions. It was only ever intended as a debugging tool, the native Metal renderer performs much better, plus enables fbfetch.

**Comment by TellowKrinkle** [comment]
Bisected in DMs, it appears to be caused by https://github.com/libsdl-org/SDL/commit/5f344c17c2dcc31cfd998b7e1451551e27b6e08b

Will attempt to reproduce locally later

**Comment by lightningterror** [comment]
Closing as tellow was unable to reproduce it, if more people experience the issue then it can be re opened.
