### ISSUE TITLE
[BUG]: when starting the program with a playstation 2 control adapter, it crashes

### ISSUE THREAD

**Issue by Amauri20090** [PCSX2/pcsx2#9917]
### Describe the Bug

A few weeks ago, an alleged bug was noticed, in which when I connect a play2 control adapter and activate ximput, the program crashes and I can no longer enter it, just removing the adapter or deactivating Ximput. but that didn't happen before, and the experience of playing with the controller instead of the keyboard is much different and better. And in the photo I'm showing, it shows the option that recognizes parallel controls, and just to make it clear, the language is Brazilian

### Reproduction Steps

enter the pcsx2 app; go to global control settings; activate the ximput option; put the control adapter (or the other way around, put the adapter first and then activate ximput); crash app

### Expected Behavior

i hope it gets fixed and i can get back to playing my favorite games with the controller, actually that's why i downloaded the app, because of how easy it is with controller adapters

### PCSX2 Revision

v1.7.4985

### Operating System

Windows 11

### Logs & Dumps

![Captura de Tela (70)](https://github.com/PCSX2/pcsx2/assets/144281961/d216e90d-4bf3-452d-a20c-b3233a272d51)

**Comment by Mrlinkwii** [comment]
can i have an emulog

**Comment by stenzek** [comment]
I'm going to bet that this is the known buggy "USB Vibration" driver.

**Comment by Amauri20090** [comment]
![download](https://github.com/PCSX2/pcsx2/assets/144281961/fbb4dca9-783c-47fc-9220-258fc83a1b86)

this is a adapter

**Comment by RedPanda4552** [comment]
@Amauri20090 We are awaiting a crash text file. It will be in the same folder as your PCSX2 executable.
![image](https://github.com/PCSX2/pcsx2/assets/6377490/90832b53-6a6b-4ccd-a3fd-7afac6926bdb)

**Comment by Buzzardsoul** [comment]
> ![download](https://user-images.githubusercontent.com/144281961/266728080-fbb4dca9-783c-47fc-9220-258fc83a1b86.jpeg)
> 
> this is a adapter

I have the very same adapter and it's not crashing PCSX2.

**Comment by stenzek** [comment]
Alright, I'm going to preemptively close this. If you post the crash dump and it's not the `EZFRD64.DLL` driver, we can reopen. But that's what it sounds like.

See https://www.google.com/search?client=firefox-b-d&q=EZFRD64.DLL, it's a well-known buggy driver.
