### ISSUE TITLE
[BUG]: Tenchu - Wrath of Heaven SLES-51400, PCSX2 crashes to desktop

### ISSUE THREAD

**Issue by antmerino** [PCSX2/pcsx2#9920]
### Describe the Bug

It starts perfectly, but when I click to start a game, after selecting the mission, the application automatically closes.
I have created a video with the problem.
https://youtu.be/hUFI_PUIoyc?si=kiDQVQy8-odMX3YO

### Reproduction Steps

In the video you can see the entire process, I have tried the  Windows version  and it worked, it only happens on Linux and on Steam Deck SO

https://youtu.be/hUFI_PUIoyc?si=kiDQVQy8-odMX3YO

### Expected Behavior

I should be able to start the level well and not crash to the desktop

### PCSX2 Revision

PCSX2 v1.7.4985

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

SteamOS 3.0

### CPU

AMD Zen 2

### GPU

AMD RDNA 2

### GS Settings

Default

### Emulation Settings

Default

### Logs & Dumps

[emulog.txt](https://github.com/PCSX2/pcsx2/files/12552496/emulog.txt)

**Comment by refractionpcsx2** [comment]
Works fine for us, and piracy is not supported here.

> [  291.9221] BIOS Found: Europe  v01.60(04/10/2001)  Console 20011004-175839
> [  291.9260] BIOS Found: Japan   v01.00(17/01/2000)  Console 20000117-050310
> [  291.9310] BIOS Found: Europe  v02.00(14/06/2004)  Console 20040614-100914
> [  292.0126] BIOS Found: USA     v02.00(14/06/2004)  Console 20040614-100909
> [  292.0172] BIOS Found: USA     v02.00(14/06/2004)  Console 20040614-100909
> [  292.0255] BIOS Found: USA     v02.20(10/02/2006)  Console 20060210-142424
> [  292.0313] Enabling extension: VK_KHR_get_surface_capabilities2
> [  292.1615] BIOS Found: Japan   v01.00(17/01/2000)  Console 20000117-050310
> [  292.1919] BIOS Found: Europe  v01.60(04/10/2001)  Console 20011004-175839
> [  292.1991] BIOS Found: Europe  v01.60(04/10/2001)  Console 20011004-175839
> [  292.2048] BIOS Found: USA     v01.60(07/02/2002)  Console 20020207-164243
> [  358.1176] Loading BIOS...
> [  358.1219] BIOS Found: Europe  v01.60(04/10/2001)  Console 20011004-175839

**Comment by antmerino** [comment]
Ok, thanks , but , did you try on Steam deck?

**Comment by stenzek** [comment]
We don't have steam decks, and we do not support piracy.
