### ISSUE TITLE
[BUG]: Rule of Rose [SLUS-21448] FMVs remain black when subtitles appear

### ISSUE THREAD

**Issue by wesker265** [PCSX2/pcsx2#9925]
### Describe the Bug

This appears to be a recent regression with Rule of Rose since I played this game a month ago with no issues. I also noticed different behavior with regular 4:3 vs 16:9 with Widescreen Patches. (FMVs set to 4:3)

This is the behavior with Widescreen Patches enabled, Aspect Ratio=16:9, FMV Aspect Ratio=4:3 :
(Note: I use FMV Aspect Ratio 4:3 because the widescreen patches stretch FMVs horizontally, but not vertically)

Anytime an FMV plays, the screen will go black when the white subtitle text appears at the bottom. The white text is fully visible and sound is still narrating, but the animation on the FMV is completely gone. As soon as the subtitles disappear, the animation appears. Audio plays normally.

This is the behavior when playing without widescreen patches, Aspect Ratio=4:3, FMV Aspect Ratio=4:3:

All FMVs that contain subtitles are black for the duration of the video. Only white subtitle text appears at the bottom and the audio is normal. Other FMVs that don't contain any subtitles seem to play normally.

Switching to software mode fixes this issue and the FMVs play normally.

FMVs that do not have subtitles will play correctly during hardware mode (e.g. the first FMV upon booting the game).

### Reproduction Steps

Default behavior in 4:3 mode: Begin Rule of Rose. Start new game. The intro FMV (Once upon a time...there was a precious little girl) will remain black for the duration of the video.

Behavior in 16:9 + Widescreen patches: Start new game. The intro FMV (Once upon a time...there was a precious little girl...) will flicker between normal and black, with black screen appearing during subtitle appearance. When the subtitle goes away, the video appears normal.

### Expected Behavior

Begin Rule of Rose. Start new game. The intro FMV will not flicker black (or remain black) and will remain playing normal while displaying the subtitles. Software mode shows the FMVs correctly.

### PCSX2 Revision

1.7.4988

### Operating System

Windows 11

### CPU

i7-7700k

### GPU

RTX 3080Ti

### GS Settings

GS Display settings - All default except: Aspect Ratio (4:3 will render the FMVs as black) (16:9 + ws patches will be black during subtitle display only) ; FMV Aspect Ratio = Standard 4:3

Rendering - All default except: Internal Resolution 6x (Also present in Native and 4x)
Anistropic Filtering: 16x (Off-8x also causes issue)
Blending Accuracy: High (Basic also causes issue)

All other settings default

### Emulation Settings

All Default. MTVU on or off has no change. VU1 on or off has no change either.

### GS Window Screenshots

Note: The 2 "Sir Peter" snaps were taken back to back to demonstrate bugged vs normal.

![Rule of Rose_SLUS-21448_20230908023206](https://github.com/PCSX2/pcsx2/assets/45540160/40f88cf7-70ad-490d-93ad-2d94bc7db519)

![Rule of Rose_SLUS-21448_20230908024059](https://github.com/PCSX2/pcsx2/assets/45540160/ce07298b-ff4f-437b-861b-515db3960363)

![Rule of Rose_SLUS-21448_20230908024102](https://github.com/PCSX2/pcsx2/assets/45540160/111244ee-f5d9-4f59-9e27-c2212192fd1e)

![Rule of Rose_SLUS-21448_20230908023253](https://github.com/PCSX2/pcsx2/assets/45540160/05554d08-d9eb-4592-b3e9-7c7da087afbc)

![Rule of Rose_SLUS-21448_20230908023209](https://github.com/PCSX2/pcsx2/assets/45540160/66558b13-d89c-4d86-8851-cc94a9718eb2)

### Logs & Dumps

[Rule of Rose_SLUS-21448_20230908025527.gs.zip](https://github.com/PCSX2/pcsx2/files/12558136/Rule.of.Rose_SLUS-21448_20230908025527.gs.zip)

**Comment by Mrlinkwii** [comment]
for the issue with WS patches , you'll have comment on the forum for that , the WS patch probably is missing stuff , and their community made 
 
 the  issue with HW mode  might be a recent regression , when did the HW issue start ?

**Comment by wesker265** [comment]
This issue is present without the widescreen patches (completely black with subtitles only). I mention the widescreen patches because the behavior is slightly different (flickering between black and normal with widescreen patches on, completely black with widescreen patches off). This could help pinpoint what is actually causing the issue.

I last played Rule of Rose without widescreen patches between July 15th through August 17th 2023. I had PCSX2 updated to the latest nightly build every time I played. I never noticed any issues with FMVs then.

**Comment by Mrlinkwii** [comment]
as far as i can make out it broke in HW mode with  #9315 , interms of teh WS patch issue , mentione that on the forums

**Comment by Larrycura** [comment]
Changing in game the renderer to software fixes the problem, press F9 in fmv and press it again in gameplay.

**Comment by refractionpcsx2** [comment]
So I did some digging with this and it looks like the game draws 512x4 at the top of the screen (the black bar?), then draws then expands out to where the FMV actually is.

The problem is that currently when we expand we don't preload from GS memory, where the FMV data is stored, so the picture just stays black.

I did start trying to fix this, but oh boy I opened a can of worms, as always happens with the GS, so it might be a little while until this is fixed.

As a temporary measure, you can enable the SW FMV switch in the per-game settings
