### ISSUE TITLE
[Feature Request]: Analog Limiter

### ISSUE THREAD

**Issue by Slickbait** [PCSX2/pcsx2#9926]
### Description

An analog limiter feature for better help with games like MGS3 on KB+M where you can slowly walk if the left analog stick is at a certain percentage.

### Reason

It would make things easier by giving the convenience of not mapping the D-Pad to the arrow keys for example and having to switch to that everytime you want to sneak behind enemies etc. in mainly MGS3 or just straight up having to stick to full movement speed.

it would be quite helpful with my enjoyment for the emulator, because again, convenience.

the feature aims to provide a better way for KB+M users to enjoy games that mostly rely on the left analog stick to dictate how fast you go.

### Examples

How it could work is very similar to that of PPSSPP

1- you assign a key for it
![analog](https://github.com/PCSX2/pcsx2/assets/105936436/fa64d90e-59fc-43e6-be17-63e1d933a0d2)

2- you adjust the percentage for it
![image](https://github.com/PCSX2/pcsx2/assets/105936436/76fea902-77b0-485f-82d7-d3afe6f41b70)

**Comment by stenzek** [comment]
This can already be done with macros, and/or changing the sensitivity of binds (shift+click).

**Comment by Slickbait** [comment]
don't think I understood you, mind showing me a tutorial or something?

**Comment by RedPanda4552** [comment]
There is no tutorial. The functionality you are asking for already exists. You can set pressures individually on mappings, you can use the pressure modifier, or you can make macros.

GitHub is for technical discussion, not support. If you need assistance, consider using the forums or Discord.
