### ISSUE TITLE
[BUG]: Taiko no Tatsujin: DOKI! Shinkyoku Darake no Haru Matsuri | bottom screen in opening is glitched

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#9935]
### Describe the Bug

HW:
![Taiko no Tatsujin - Doki! Shinkyoku Darake no Haru Matsuri_SLPS-20272_20230909194253](https://github.com/PCSX2/pcsx2/assets/121824800/91753467-e970-45da-9504-d00a0a16080e)

SW:
![Taiko no Tatsujin - Doki! Shinkyoku Darake no Haru Matsuri_SLPS-20272_20230909194256](https://github.com/PCSX2/pcsx2/assets/121824800/2769ac76-aeec-4b52-b2db-40fb7f278ab5)

maybe related: #9912

### Reproduction Steps

boot the game.

### PCSX2 Revision

v1.7.4992

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
yes, it's the same bug, both games use the same engine, so going to consider this a duplicate.
