### ISSUE TITLE
[BUG]:  Ace Combat 5 The Unsung War - Pixelated clouds

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#9937]
### Describe the Bug

The game started showing the clouds since the 1.7.4943 build ( #9315 PR), but they're pixelated/broken. It's more obvious at higher resolutions. Software looks fine.

### Reproduction Steps

For me the easiest way is to start the Arcade mode and quickly turn to the left. You can see the broken clouds quickly.

### Expected Behavior

Not look broken.

### PCSX2 Revision

1.7.4994

### Operating System

Windows 11

### CPU

i7-10700K

### GPU

RTX 3070

### GS Window Screenshots
HW
![image](https://github.com/PCSX2/pcsx2/assets/4414625/e32e4a50-204c-40e9-983a-c4387b1cb22c)
SW
![image](https://github.com/PCSX2/pcsx2/assets/4414625/fc9adc92-3c7a-4300-ba14-b2cd73435234)

### Logs & Dumps

GS Dump
[AC5_Clouds.zip](https://github.com/PCSX2/pcsx2/files/12566571/AC5_Clouds.zip)

**Comment by refractionpcsx2** [comment]
Ace combat is a pie of problems with clouds, lens flare and other nonsense and no combination of settings seems to get them right.

**Comment by Blackbird88** [comment]
Oh damn. This is actually weirder than I thought. The versions older than the invalidation PR actually don't show them at all! I just assumed it's the background clouds, but no. So technically the PR actually makes them show, just broken.
1.7.4992 HW
![image](https://github.com/PCSX2/pcsx2/assets/4414625/dac975aa-5a32-4de2-8525-f5a0c306220d)
1.7.4992 SW
![image](https://github.com/PCSX2/pcsx2/assets/4414625/056bc0e1-db10-4e92-8658-e3c1c6f067bc)

**Comment by refractionpcsx2** [comment]
yup :P

**Comment by Blackbird88** [comment]
I just found out it's the cpuCLUTRender that breaks them. They look fine with it turned off or Agressive
Software CLUT Render
Disabled
![image](https://github.com/PCSX2/pcsx2/assets/4414625/bf375a61-8773-4097-bf56-5f24005d6979)
Normal
![image](https://github.com/PCSX2/pcsx2/assets/4414625/7c43fb85-a993-421b-be94-c6fa1369d9c5)
Agressive
![image](https://github.com/PCSX2/pcsx2/assets/4414625/ffaaf0ea-1ec6-48fd-90d7-ac2788890b3d)

**Comment by refractionpcsx2** [comment]
yes, I know, we've been here, you put on the clut renderer it breaks the clouds but fixes the sun, and visa versa, there's no combination of options that works for everything, the game needs a better solution

**Comment by Blackbird88** [comment]
I don't know what the sun bug is supposed to be, but lens flare appears even with SW CLUT disabled
![image](https://github.com/PCSX2/pcsx2/assets/4414625/728c185d-f373-4fd7-b96e-ca53ba3f667a)

**Comment by refractionpcsx2** [comment]
Sorry, not lens flare, but sun going through your plane

**Comment by Blackbird88** [comment]
Odd I don't see that either?
![image](https://github.com/PCSX2/pcsx2/assets/4414625/d4f73078-291a-46ad-9113-c9f7a957b6d7)

**Comment by refractionpcsx2** [comment]
Weird.... maybe it doesn't need it anymore for some reason? :/

**Comment by refractionpcsx2** [comment]
oh it was GPU CLUT it needs

![image](https://github.com/PCSX2/pcsx2/assets/6278726/a54185e8-8f13-4b58-8127-ad768f792919)
![image](https://github.com/PCSX2/pcsx2/assets/6278726/e24a087b-a856-48d4-b5b8-27db32a90a3f)

**Comment by Blackbird88** [comment]
That is strange. I can't reproduce this. Might be specific to some missions. All GPU CLUT does to me is break the sun entirely and not match SW.
Disabled
![image](https://github.com/PCSX2/pcsx2/assets/4414625/3cdb91fb-790a-40d9-a914-1e67fb628310)
Exact Match
![image](https://github.com/PCSX2/pcsx2/assets/4414625/0d5417b5-c89e-4f35-a719-ceb982e7c727)
SW
![image](https://github.com/PCSX2/pcsx2/assets/4414625/92a21540-34ba-4a3e-892f-28acb4d11a0e)

**Comment by refractionpcsx2** [comment]
the sun isn't behind the craft

**Comment by Blackbird88** [comment]
Looks fine even with GPU CLUT disabled.
![image](https://github.com/PCSX2/pcsx2/assets/4414625/d5aa5fa1-f6a0-4654-bf49-5b61c1aa930b)

**Comment by refractionpcsx2** [comment]
you have SW CLUT enabled and set to aggressive.

**Comment by Blackbird88** [comment]
I loaded the game properly to make sure it's not some save state screwing things up. Still looks fine to me.
![image](https://github.com/PCSX2/pcsx2/assets/4414625/aad87471-2d18-46a2-bed0-b22910c16e43)

**Comment by refractionpcsx2** [comment]
Then I don't know what to tell you :P Maybe the invalidation changes un-broke the CLUT draw, or something.

**Comment by Blackbird88** [comment]
Well the problem is that if you switch between HW and SW in this game, it seems to "clear" something, because the the game doesn't look same.
The dump is example itself. Just switching between HW and SW makes the sun look proper not even touching any per-game settings.
![image](https://github.com/PCSX2/pcsx2/assets/4414625/300d234f-3c8f-4af2-8870-74e184bc6bf5)

So here's my dump to test
[Ace Combat 5 - The Unsung War_SLUS-20851_20230910000231.zip](https://github.com/PCSX2/pcsx2/files/12566754/Ace.Combat.5.-.The.Unsung.War_SLUS-20851_20230910000231.zip)

**Comment by refractionpcsx2** [comment]
yes, it's probably drawing something to GS memory, and that's getting reused by the hardware renderer, where in HW it all gets stored on the GPU and probably later discarded

**Comment by Parallax71** [comment]
> yes, it's probably drawing something to GS memory, and that's getting reused by the hardware renderer, where in HW it all gets stored on the GPU and probably later discarded

Hello, a question, isn't this defect that this game has the same problem that "Timesplitters Future Perfect" has?. I mention it because it can still be fixed, or not?. That I have no idea, that you are the professionals, but the arrangement could still go that way. 
https://github.com/PCSX2/pcsx2/issues/9900

**Comment by refractionpcsx2** [comment]
There's a lot of games with light bleeding through objects, and they are all for different reasons. Unfortunately you can't assume they are all the same problem because the symptoms are the same, but sometimes it can be a hint.

**Comment by mirh** [comment]
AFAIK clouds started to work since #8826, not #9315. 
And it's not even the [first](https://github.com/PCSX2/pcsx2/issues/1860#issuecomment-1345598070), [second](https://github.com/PCSX2/pcsx2/issues/1547#issuecomment-1189227567) or [third](https://github.com/PCSX2/pcsx2/issues/6631) time that AC has these odd behaviours that only change by cycling renderers.

**Comment by refractionpcsx2** [comment]
You're misunderstanding, not *all* the clouds were fixed in #8826, #9315 introduced more clouds.
