### ISSUE TITLE
[Feature Request]: Qt - Add "Sort-by......" to Game Grid

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9939]
### Description

A request to add a "sort-by" right-click option on Game Grid such as recently added, recently played, region, most played, never played etc

For example, if I'm playing Zone of the Enders, it would be very helpful not to scroll all the way down to Z.
Very useful with users with a large collection of PS2 games.

Thanks

### Reason

Ease of use.

### Examples

Dolphin, RPSC3

**Comment by Mrlinkwii** [comment]
use the search function
![image](https://github.com/PCSX2/pcsx2/assets/17685135/943ff0ea-ae9a-477d-96b5-4730984ab3e8)

**Comment by refractionpcsx2** [comment]
Go to the list view (not covers) click on the column headings, you can add a column for last played and time played. Then you can go back to the covers It does everything you want, maybe could be more convenient, but that takes 2 seconds :P

**Comment by bigol83** [comment]
There already is this function, like refraction said. Just go to list view, sort by recently played, switch back to grid view and the sorting order is the same. It's not even a temporary sorting, it will stay in that sorting order in both grid and list view unless you change it.

**Comment by stenzek** [comment]
Already a thing as mentioned above, and tbh I'm not sure how this could be nicely exposed in the UI. Having a dropdown in options would desync from the list view, since both share the same model.
