### ISSUE TITLE
[BUG]: Intel's Driver Artifacts

### ISSUE THREAD

**Issue by Dantedevil10** [PCSX2/pcsx2#9940]
### Describe the Bug

in the most recent intel drivers of (i37100u, intel hd 620) the emulation in VULKAN make some artefacts in the games
the blending accuracy i set on the games are in maximum but Vulkan sometime i set on 'FULL' for better performance
the intel drivers version (27.20.100.9365) of 2021 run normaly and dont make that artifacts on games
the intel drivers of 2023 (31.0.101.2125) are the most recently drivers of my "intel hd 620" and they make that artifacts on games
in the others renderers i have no problem ,only in vulkan
i try set the blending accuracy on basic but dont change so much
![Need for Speed - Most Wanted  Black Edition  09_09_2023 17_51_39](https://github.com/PCSX2/pcsx2/assets/125316907/1667f85a-c725-42c0-b829-312555657f35)
![Need for Speed - Most Wanted  Black Edition  09_09_2023 17_52_30](https://github.com/PCSX2/pcsx2/assets/125316907/3b86b45b-248a-4c9b-ba13-e3807d29b469)

### Reproduction Steps

install the most recently drivers of intel and then try to play the games on vulkan 
with blending accuracy on basic ,full or maximum

### PCSX2 Revision

v1.7.4994

### Operating System

Windows 10 (64bit)

### CPU

i3-7100u

### GPU

intel hd 620

### GS Window Screenshots

![Need for Speed - Most Wanted  Black Edition  09_09_2023 17_51_39](https://github.com/PCSX2/pcsx2/assets/125316907/99de22b6-6176-4a24-a88a-20ea393f974c)
![Need for Speed - Most Wanted  Black Edition  09_09_2023 17_52_30](https://github.com/PCSX2/pcsx2/assets/125316907/5bb6f3cf-e1ec-478f-ad19-c235fa86f172)

**Comment by refractionpcsx2** [comment]
You expect us to fix driver bugs? You need to bother intel, not us.

I suggest you use an older driver until they fix it.

**Comment by Dantedevil10** [comment]
Thanks for explaining ,next time ill be more rude for explain "we cant do anything about it"

**Comment by refractionpcsx2** [comment]
Excuse me? You came to use with a driver problem, expecting us to deal with it. I explained we can't, I wasn't being rude, you do need to bother intel, we can't do anything about it.

No need to be an ass.

**Comment by refractionpcsx2** [comment]
Also just FYI, Vulkan is pretty broken on iGPU drivers, your best bet is using OpenGL.

**Comment by Dantedevil10** [comment]
Ok thank you and sorry for that

**Comment by refractionpcsx2** [comment]
No problem

**Comment by stenzek** [comment]
FYI GL will crash the GPU in some games as well. Hence why DX11 is the default for older Intel GPUs.

Both are fixed in the newer drivers for Arc. Not our bug.
