### ISSUE TITLE
[Feature Request]: Set the default ISO, Memcards, and BIOS etc folders in the documents directory

### ISSUE THREAD

**Issue by Buzzardsoul** [PCSX2/pcsx2#9956]
### Description

Currently, if you download a fresh install of PCSX2, you're gonna have to copy the mentioned folders into the new PCSX2 folder all over again. In which is a hassle, especially for the testers. This FR is going to aid testers substantially, and overwriting the currently installed PCSX2 folder with a new beta one is just wrong. I'd like to mention that this is merely a suggestion, if you guys were to dislike it, you're more than free to close this FR. 

P.S: I'm unaware as to whether or not this has been suggested before.

### Reason

Speeding up testing.
PCSX2's directory can change, but the documents folder cannot.

### Examples

No need.

**Comment by F0bes** [comment]
This is exactly what "stable" builds do.
1.7.xyzw builds are not considered stable and instead "portable"
This will be addressed when there is a new "stable" release.

**Comment by stenzek** [comment]
Or just delete portable.ini.
