### ISSUE TITLE
[BUG]: Mortal Kombat Deception Audio Bug

### ISSUE THREAD

**Issue by Blacksoul0123** [PCSX2/pcsx2#9957]
### Describe the Bug

When I start an Arcade Kombat match in MKD and enter the arena called Slaughterhouse, the sound does not work correctly during the Fight/Round announcement.

https://github.com/PCSX2/pcsx2/assets/144792609/a2a6c087-d6cc-4e15-ab3b-0e4a9737916f

### Reproduction Steps

There is no fight/round sound error on other aren, this track should work like that 
https://github.com/PCSX2/pcsx2/assets/144792609/1a737aa3-579c-4689-b01d-e1602b51293d

### PCSX2 Revision

v1.7.5006

### Operating System

Windows 10

### CPU

i7-4790

### GPU

GTX 970

### GS Settings

![bandicam 2023-09-13 18-49-49-576](https://github.com/PCSX2/pcsx2/assets/144792609/7946f958-19db-4816-a025-2f7b0a61308b)
![bandicam 2023-09-13 18-49-59-462](https://github.com/PCSX2/pcsx2/assets/144792609/1bc98f3f-f453-40db-8b79-fc31485022c7)
![bandicam 2023-09-13 18-50-05-652](https://github.com/PCSX2/pcsx2/assets/144792609/e8069b0f-d4ee-45eb-9d38-4dabb3aa74aa)

**Comment by Mrlinkwii** [comment]
closing due to we dont support piracy

**Comment by Blacksoul0123** [comment]
Because of bancicam ? if I record it with someone else, will you accept the bug report?

**Comment by Blacksoul0123** [comment]
Sorry, I thought this would also be needed for the bug report. Nevertheless, can I submit it again or should I stop trying? Of course, I will not send the filmware.
