### ISSUE TITLE
Debugger search functionality?

### ISSUE THREAD

**Issue by Scorpeg** [PCSX2/pcsx2#996]
Not sure for what reason it lacks simple binary search (PPSSPP debugger have it). Also Dump button is never active for me, so almost impossible to find what you need...

**Comment by gregory38** [comment]
@Kingcom maybe a job for you.

**Comment by Kingcom** [comment]
I think the reason I didn't implement this was that you (or at least I) could only access memory through readXX functions, instead of getting a pointer and a size of the region it points to to work with. This made the search logic complicated and the search itself very slow.

**Comment by gregory38** [comment]
You could directly read the EE physical memory if you want. It is stored in `eeMem->Main`

**Comment by retrobenny** [comment]
Would like to see this added too because its annoying to have to use an extra tool (Cheat Engine,reverse byte order) for one thing that would be way less of a hassle to use if it was built-in.

(didn't know about "go to" being hidden in a hotkey,to explain my new issue post from moments ago)
