### ISSUE TITLE
[BUG]: Ghost in the Shell - Stand Alone Complex

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9965]
### Describe the Bug

When the texts are output in the "Training" mode, for example, some vertical "separation" lines are shown. This happens with hardware renders, it does not happen with software (I put example screenshots and GS).

HW Mode:
![Ghost in the Shell - Stand Alone Complex_SLES-53020_20230915185845](https://github.com/PCSX2/pcsx2/assets/142044650/56006162-ffa7-4e41-8363-c636a79cc3c2)

SW Mode:
![Ghost in the Shell - Stand Alone Complex_SLES-53020_20230915190853](https://github.com/PCSX2/pcsx2/assets/142044650/4c5904bb-68cc-46ea-b8a2-0d3fe94600d2)

[Ghost in the Shell - Stand Alone Complex_SLES-53020_20230915185845.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12622119/Ghost.in.the.Shell.-.Stand.Alone.Complex_SLES-53020_20230915185845.gs.zst.zip)

### Reproduction Steps

Start the game, go to training mode, there in that mode it is faster to check this.

### Expected Behavior

it is expected that the separations will not be seen

### PCSX2 Revision

v1.7.5010

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by lightningterror** [comment]
It's an upscaling issue, nothing can be done atm, you can either play on native res or use software mode.

**Comment by Parallax71** [comment]
> It's an upscaling issue, nothing can be done atm, you can either play on native res or use software mode.

ok, thanks 👍
