### ISSUE TITLE
[BUG]: Flashing alternatingly colored lines on the right and bottom sides of the emulation screen.

### ISSUE THREAD

**Issue by DanielBielak** [PCSX2/pcsx2#9972]
### Describe the Bug

Flashing alternatingly colored lines on the right and bottom sides of the emulation screen.

### Reproduction Steps

- Run "Gran Turismo 4" with PCSX2
- Select "Gran Turismo Mode"
- Select "City Courses"
- Select "Seoul Central"
- Select "Practice"
- Select "A-Spec=Driver's Mode"

### Expected Behavior

No lines on the sides of the emulation screen.

### PCSX2 Revision

v1.7.5015

### Operating System

macOS 10.14 (Mojave)

### CPU

2.2 GHz Intel Core i7

### GPU

Intel Iris Pro 1536 MB

**Comment by Mrlinkwii** [comment]
can i have a gsdump

**Comment by Mrlinkwii** [comment]
can i have a gsdump

**Comment by DanielBielak** [comment]
How do I create or find a gsdump?

**Comment by RedDevilus** [comment]
> How do I create or find a gsdump?

How To Create A GS Dump
What is a GS dump?
A GS dump is a dump of PS2 graphics data. The dump allows helpers, testers and developers to figure out how to fix graphics bugs.

Where do I make the dump?
Get to a point in your game where the graphics bug is clearly visible. The issue must appear on your screen in order for it to be captured in the dump.

How do I make the dump?
Use the key combination Shift + F8 or use Tools > Save Single Frame GS Dump

Where does the GS dump save to?
GS dumps are saved to the /snaps folder.
On Windows, this is in the same directory as the PCSX2 executable.
On Linux and Mac, use Tools > Open Data Directory

Your graphics settings DO NOT affect the dump, and you will not need to change renderers, hardware fixes or any other settings.

More information on the PCSX2 forums:
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by DanielBielak** [comment]
Here is the gsdump. The lines don't appear in the snapshot image.
[gsdump.zip](https://github.com/PCSX2/pcsx2/files/12641365/gsdump.zip)

**Comment by DanielBielak** [comment]
Also:

I have the Internal resolution set to "2x Native (~720p)"

And, In Gran Tursmiso 4, before selecting "City Courses:

- Select "Home"
- Select "Options"
- Select "Screen"
- Select "HDTV (1080i)" as the "Video Output"

**Comment by Mrlinkwii** [comment]
ok this is an upscale issue  , use the crop setting on a per game bases 

as noted we dont take upscaling issues at this time
