### ISSUE TITLE
[BUG]: Can't build on GNU/Linux x86_64

### ISSUE THREAD

**Issue by vanfanel** [PCSX2/pcsx2#9973]
### Describe the Bug

When trying to build on GNU/Linux (Debian, Ubuntu LTS) I get this:
```

/home/manuel/src/pcsx2/pcsx2-qt/ColorPickerButton.cpp: In member function ‘void ColorPickerButton::updateBackgroundColor()’:
/home/manuel/src/pcsx2/pcsx2-qt/ColorPickerButton.cpp:45:9: error: ‘setStyleSheet’ was not declared in this scope; did you mean ‘setStyle’?
   45 |         setStyleSheet(QStringLiteral("background-color: #%1;").arg(static_cast<uint>(m_color), 8, 16, QChar('0')));
      |         ^~~~~~~~~~~~~
      |         setStyle
make[2]: *** [pcsx2-qt/CMakeFiles/pcsx2-qt.dir/build.make:321: pcsx2-qt/CMakeFiles/pcsx2-qt.dir/ColorPickerButton.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1330: pcsx2-qt/CMakeFiles/pcsx2-qt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Reproduction Steps

-Configure the code:
```

mkdir build
cd build

cmake .. -DCMAKE_C_FLAGS="-march=native -mtune=native" -DCMAKE_CXX_FLAGS="-march=native -mtune=native"
```
-Try to build

`make -j3`

### Expected Behavior

Should build without errors, I guess

### PCSX2 Revision

Latest GIT code

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian 12, Ubuntu

**Comment by TellowKrinkle** [comment]
Is your Qt built without stylesheet support?  If so, we don't support that.
If you're not sure how to check, can you upload your system's `qtcore-config.h`?

**Comment by stenzek** [comment]
Like tellow said, you've disabled stylesheets: https://github.com/qt/qtbase/blob/b0ba5c78eee0a476f5ab3e55e3bf3b5476e481c4/src/widgets/kernel/qwidget.h#L370

Please stop trying to disable everything under the sun and reporting bogus issues, it's starting to get annoying. Our build scripts are public (under the .github directory), if you want to build it any other way, this is an **unsupported** configuration.

**Comment by vanfanel** [comment]
@stenzek I am free to disable whatever I want on my QT6 builds.  You are free to ignore my bug reports.
In fact, **I ASK you to ignore my bug reports. I don't want to have a single word with you.**

Also, I believe that by "disabling everything under the sun" you mean this issue:
https://github.com/PCSX2/pcsx2/issues/9961#issuecomment-1720029574
**READ MY LIPS: When I tried to disable achievements, there was a CMake option for it. Someone (possibly not you) put that there, and hence it was supposed to be usable. I like to do light builds without dependencies like Discord or Achievements.
1-This is an opensource project
2-The option WAS there
I was simply building the way I want, which is what opensource is about.**

Jeez... never before did I try to build PCSX2, but finding you here too, after you banned me from your DuckStation repository because I reported audio issues (which are not present on the LR port) sure was BAD news...

@TellowKrinkle Thanks for that. That was very helpful, I enabled them and now it builds :)

**Comment by refractionpcsx2** [comment]
Strong advice, being sarcastic, condescending, generally rude to developers of open source, is not going to garner you any favours.

**Comment by stenzek** [comment]
Not going to respond to the first part or the other attacks, it's just inflammatory. But I will point out that being able to open issues is a privilege, not a right, and if you're rude to developers, that right will be revoked.

> Someone (possibly not you) put that there, and hence it was supposed to be usable.

It was me. It made sense when the feature wasn't supported across all platforms. It is now, so it makes no sense keep an option around which keeps breaking, because our CI doesn't build it, which I explained in the other thread. Even said if you had a compelling reason as to why it should be kept, that we'd consider it ;) But no, only flames it seems :)

> I was simply building the way I want, which is what opensource is about.

Open source is about collaborating, and having the right to create your own fork if you don't like the way upstream does things. You're more than welcome to do that.
