### ISSUE TITLE
[BUG]: Game Freezes (not in all, but in many)

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9984]
### Describe the Bug

Hello, I am encountering these performance drops that are random, it does not happen in all games but it does in many. The problem is that when I am playing a game, the game stops or "pauses" for 1 second or so, I can't find an explanation for it, since as I say, it doesn't happen in all games. (occurs in HW and SW mode, at any resolution, native or not). I leave a screenshot of the moment in which I was seeing the fps of the game, also a small video where you can see that error. Thank you.
![Simpsons, The - Hit   Run_SLES-51897_20230917131320](https://github.com/PCSX2/pcsx2/assets/142044650/bb06f056-0d29-466a-aac8-cffd5bff29cb)
[Simpsons, The - Hit & Run_SLES-51897_20230917131320.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12642701/Simpsons.The.-.Hit.Run_SLES-51897_20230917131320.gs.zst.zip)

video showing the problem and capture of one of the moments in which it occurs.
![caidrendim](https://github.com/PCSX2/pcsx2/assets/142044650/c6395336-b1bf-4ca0-a5de-35d9c5e6dff3)

### Reproduction Steps

It is something that happens randomly in certain games, in The Simpsons hit & Run it happens to me frequently

### Expected Behavior

I hope the games work without interruptions

### PCSX2 Revision

v1.7.5021

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by refractionpcsx2** [comment]
Please use the discord or forums for support. Thanks.

**Comment by Parallax71** [comment]
> Please use the discord or forums for support. Thanks.

I am not able to register, it never accepts the captcha, and so I cannot enter the forum

**Comment by refractionpcsx2** [comment]
then I suggest joining the discord, we have an invite link on our main site

**Comment by stenzek** [comment]
500ms delay sounds like I/O, especially if you're running the game off an external HDD. Or something running in the background stealing time away.

Regardless, the issue tracker isn't for support, but if you can't join Discord, that's a likely suspect.

**Comment by Parallax71** [comment]
> then I suggest joining the discord, we have an invite link on our main site



> 500ms delay sounds like I/O, especially if you're running the game off an external HDD. Or something running in the background stealing time away.
> 
> Regardless, the issue tracker isn't for support, but if you can't join Discord, that's a likely suspect.

In the end I managed to enter the forum and create an account (I had to do it with Microsoft Edge since with Firefox no captcha was recognized), this is the link to the problem, in case you want to look at it, although it is the same as I have explained here, thanks for everything.
