### ISSUE TITLE
[Feature Request]: Memory Search (Big/Little) Endian

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#9987]
### Description

Debugger Memory Search should allow the user to specify endian-ness. This is most relevant for searching for 2 to 8 byte values. Games that use the wrong endianness will be unable to locate the value you are searching for unless you manually convert the endianness.

### Reason

Some games use Big Endian or Little Endian. There is no option to control this in the search function.

### Examples

In Armored Core 2 - Another Age, I was unable to locate my HP value because it was stored in Little Endian (most significant digit is last). None of the returned addresses for my search were relevant as a result.

**Comment by Goatman13** [comment]
I don't think there is single game that store values in big endian on little endian cpu. That require byte reversing or byte by byte processing just to load/store anything. :) Excluding strings of course. However current search field expect human readable value, so kinda "big endian". You can use "Array of bytes" instead, that field expect "little endian" input.


So feature is already there, just hidden little bit.

**Comment by F0bes** [comment]
I agree with Goatman. Using "Array of bytes" makes more sense. A "big endian" type doesn't necessarily exist from the guests perspective.
