### ISSUE TITLE
[BUG]: Transformers (2004) Camera is stuttery/shakey when moving it in certain areas on hardware renders except OpenGL

### ISSUE THREAD

**Issue by AkihitoZero5454** [PCSX2/pcsx2#9991]
### Describe the Bug

The game when played on hardware rendering (except OpenGL) has a problem where the camera is shakey/stuttery when moving it.

### Reproduction Steps

Use software rendering or Open GL

### Expected Behavior

Screen should not shake or stutter when camera moves

### PCSX2 Revision

v1.7.5027

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 3700X 8-core processor 

### GPU

Nividia GTX 1070 TI

**Comment by AkihitoZero5454** [comment]
[Transformers_SLUS-20668_20230917220854.gs.zip](https://github.com/PCSX2/pcsx2/files/12644308/Transformers_SLUS-20668_20230917220854.gs.zip)

**Comment by stenzek** [comment]
Dump looks identical to me on GL and Vulkan..

**Comment by JordanTheToaster** [comment]
Cannot replicate myself on current master.
