### ISSUE TITLE
[BUG]: Steam Deck(Linux) emulated clock doesn't account for timezones or daylight savings

### ISSUE THREAD

**Issue by JimScript** [PCSX2/pcsx2#9997]
### Describe the Bug

PCSX2 will only use GMT for the emulated clock on linux.

### Reproduction Steps

Go into bios and then into System Configuration.

### PCSX2 Revision

v1.7.5031

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

SteamOS 3.5

**Comment by RedDevilus** [comment]
PS2 BIOS has option for timezones and daylight savings, are you saying that isn't working for you?

![image](https://github.com/PCSX2/pcsx2/assets/24227051/a388934a-f19d-4607-a362-9ac93c70c040)
![image](https://github.com/PCSX2/pcsx2/assets/24227051/29052ec5-bfad-4322-8262-7d03e9a6b604)

PS2 doesn't have automatic options for those, need to do those manually. With going to clock, then option and picking summer or winter time

**Comment by JimScript** [comment]
Right, I'm so sorry, that fixed it. I thought PCSX2 was _completely_ automatic with time, my windows version is years old(pre-Qt), so I must of forgot.

**Comment by RedDevilus** [comment]
Yeah, mine are desynced as well. Even on console I didn't really bother as it's just annoying. I suppose in future we could kinda hijack it like no-interlacing patches are to PCSX2. But doubt team will like that, though in future we do need custom date overwrites and not just be tied to your clock. So PCSX2 kinda is automatic with the time with the reboot, but just not with timezones and DST and if you ignore speeding up with Tab or F4.

So there is some weird desync from there.
